### PR TITLE
Set mouse cursor to visible after the color picker dialog closes

### LINKED ISSUE #42596: Cursor disappears permanently when dialog is closed
**Godot version:**

3.2.3 / ed33324

**Steps to reproduce:**
1. Open editor settings
2. Edit some color
3. Drag a value in a spin box
4. RIP
xtnyLxdqD6

### PR DESCRIPTION
**Pull request by JakubDemocko**
This should fix this bug: https://github.com/godotengine/godot/issues/42596

*Bugsquad edit:* Fixes #42596.

### CODE REVIEW

**Comment by akien-mga** [comment]
Can you describe what bug this is fixing?

**Comment by JakubDemocko** [comment]
Sure, sry. It deals with this bug: https://github.com/godotengine/godot/issues/42596

**Review by KoBeWi — COMMENTED** [review]
This doesn't seem to fix the issue. The cursor only appears when the ColorPickerButton is hidden, while the bug happens with the ColorPicker.

**Review by KoBeWi — DISMISSED** [review]

**Comment by akien-mga** [comment]
Sorry for the late review. The two commits should be squashed together, see [PR workflow]() for instructions.
Also note that the email used to author those commits (see https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/43262.patch) doesn't seem affiliated to your GitHub account, which is why the commits don't appear as authored by "@JakubDemocko". If you want to claim their ownership back, you can add this secondary email in your GitHub settings.

As for the fix itself, I'm confident that it does fix the issue but I can't shake the feeling that it seems to be a workaround that might hide the actual bug. I haven't done a deep investigation of what the bug is though so it might well be that this is the proper fix. WDYT @godotengine/gui-nodes.

**Comment by KoBeWi** [comment]
Sooo I actually tested the issue again and it turns out it's already fixed. There's another issue with SpinEdit, but it's unrelated. This PR is not necessary anymore at this point...

**Comment by akien-mga** [comment]
Superseded by #46739. Thanks for the contribution nevertheless!

**Pull request closed without merging**
