### PR TITLE
Bump the minimum Android target api to 21 (Android Lollipop)

### LINKED ISSUE #62464: dlopen failed: cannot locate symbol "in6addr_any"
### Godot version

4.0.alpha10

### System information

(Android Device)Oppo Mirror 5 Android 5.1 (Lollipop), ColorOS 2.1

### Issue description

Android app crashes with the following:
```

E/art     (32345): dlopen("/data/app/org.godotengine.godot4-1/lib/arm/libgodot_android.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "in6addr_any" referenced by "libgodot_android.so"...
E/AndroidRuntime(32345): FATAL EXCEPTION: main
E/AndroidRuntime(32345): Process: org.godotengine.godot4, PID: 32345
E/AndroidRuntime(32345): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "in6addr_any" referenced by "libgodot_android.so"...
E/AndroidRuntime(32345): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime(32345): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(32345): 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:48)
E/AndroidRuntime(32345): 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:461)
E/AndroidRuntime(32345): 	at org.godotengine.godot.Godot.onCreate(Godot.java:602)
E/AndroidRuntime(32345): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(32345): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
E/AndroidRuntime(32345): 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
E/AndroidRuntime(32345): 	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
E/AndroidRuntime(32345): 	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
E/AndroidRuntime(32345): 	at android.app.Activity.performCreate(Activity.java:6085)
E/AndroidRuntime(32345): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2373)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.access$900(ActivityThread.java:164)
E/AndroidRuntime(32345): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
E/AndroidRuntime(32345): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(32345): 	at android.os.Looper.loop(Looper.java:150)
E/AndroidRuntime(32345): 	at android.app.ActivityThread.main(ActivityThread.java:5408)
E/AndroidRuntime(32345): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32345): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(32345): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime(32345): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
E/WindowState(  877): getStack: Window{895cd7f u0 Starting org.godotengine.godot4} couldn't find taskId=21 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowState.getWindowList:1517 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2934 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 
E/WindowState(  877): getStack: Window{895cd7f u0 Starting org.godotengine.godot4} couldn't find taskId=21 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2939 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 com.android.server.wm.WindowManagerService.removeWindowLocked:2739 
```

### Steps to reproduce

export apk to Android 

### Minimal reproduction project

_No response_

### LINKED ISSUE #63945: Android crashes can't load "libgodot_android.so" (fails to access storage on Android 5.1)
### Godot version

4.0.alpha13

### System information

(Android Device)Oppo Mirror 5 Android 5.1 (Lollipop), ColorOS 2.1

### Issue description

App crashes on launch due to this:

```
E/QCOMSysDaemon( 5284): Can't find/open bootselect node: (No such file or directory)
E/Diag_Lib( 5284):  Diag_LSM_Init: Failed to open handle to diag driver, error = 2
E/QCOMSysDaemon( 5284):  Diag_LSM_Init failed : 0
E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
E/Vold    (  260): Failed to find mounted volume for /storage/sdcard1/Android/data/org.godotengine.godot4/files/
E/art     ( 5289): dlopen("/data/app/org.godotengine.godot4-1/lib/arm/libgodot_android.so", RTLD_LAZY) failed: dlopen failed: empty/missing DT_HASH in "libgodot_android.so" (built with --hash-style=gnu?)
E/AndroidRuntime( 5289): FATAL EXCEPTION: main
E/AndroidRuntime( 5289): Process: org.godotengine.godot4, PID: 5289
E/AndroidRuntime( 5289): java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libgodot_android.so" (built with --hash-style=gnu?)
E/AndroidRuntime( 5289): 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime( 5289): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.GodotLib.<clinit>(GodotLib.java:51)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.Godot.initializeGodot(Godot.java:474)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.Godot.onCreate(Godot.java:614)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
E/AndroidRuntime( 5289): 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
E/AndroidRuntime( 5289): 	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
E/AndroidRuntime( 5289): 	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
E/AndroidRuntime( 5289): 	at android.app.Activity.performCreate(Activity.java:6085)
E/AndroidRuntime( 5289): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2373)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.access$900(ActivityThread.java:164)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
E/AndroidRuntime( 5289): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5289): 	at android.os.Looper.loop(Looper.java:150)
E/AndroidRuntime( 5289): 	at android.app.ActivityThread.main(ActivityThread.java:5408)
E/AndroidRuntime( 5289): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5289): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5289): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime( 5289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
E/PhoneStatusBar(14116): updateNotificationTitleText  preIsInsidePanelCanSlide =true,misInsidePanelCanSlide = true,misInsidePanelOpen = false
E/WindowState(  915): getStack: Window{2f68804 u0 Starting org.godotengine.godot4} couldn't find taskId=16 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowState.getWindowList:1517 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2934 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 
E/WindowState(  915): getStack: Window{2f68804 u0 Starting org.godotengine.godot4} couldn't find taskId=16 Callers=com.android.server.wm.WindowState.getDisplayContent:891 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2939 com.android.server.wm.WindowManagerService.removeWindowLocked:2824 com.android.server.wm.WindowManagerService.removeWindowLocked:2739 
E/PhoneStatusBar(14116): updateNotificationTitleText  preIsInsidePanelCanSlide =true,misInsidePanelCanSlide = true,misInsidePanelOpen = false
E/LocSvc_LBSApiV02(  915): E/virtual int lbs_core::LBSApiV02::wifiAttachmentStatusInject(const WifiSupplicantInfo&):688]: Error : st = 11, ind.status = 0
```

### Steps to reproduce

Just making a new Project and export it to Android Lollipop(5.1) device.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by m4gr3d**
Following the discussion below, bump the minimum Android target api to **21** (**Android 5 Lollipop**).

Fixes https://github.com/godotengine/godot/issues/62464 
Fixes https://github.com/godotengine/godot/issues/63945

According to Google stats, raising the min supported version to Android 5 provides **98.8%** device coverage.

Screen Shot 2022-10-19 at 9 27 07 AM

### CODE REVIEW

**Comment by clayjohn** [comment]
Does this also apply when using the OpenGL renderer? 

I'd be hesitant to drop support for devices that can run the OpenGL renderer still.

**Comment by m4gr3d** [comment]
> Does this also apply when using the OpenGL renderer? 

It shouldn't, but that would require us to provide separate template builds for Android, one with Vulkan enabled and the other without.

It's worth discussing whether we're willing to increase the build and maintenance complexity of fully disabling Vulkan in a 4.0 build.

**Comment by himaghnam** [comment]
I think Android 7 as a minimum requirements is fine, no need for a seperate build template.

**Comment by akien-mga** [comment]
> It shouldn't, but that would require us to provide separate template builds for Android, one with Vulkan enabled and the other without.

We should be able to load the Vulkan library dynamically, and fallback to GLES3 if not present, no? That's the same principle for GLESv2 and GLESv3 support in 3.x.

For 3.x I think GLESv3 is provided as a stub even when not supported so we can fallback, but for Vulkan it should be even simpler as we use Volk which `dlopen`s the Vulkan lib. If it fails initializing, we can fallback.

So unless there's very significant benefit for moving to 7.0, I would prefer not dropping ~6% of the market.

**Comment by m4gr3d** [comment]
> We should be able to load the Vulkan library dynamically, and fallback to GLES3 if not present, no? That's the same principle for GLESv2 and GLESv3 support in 3.x.

According to [this blog post](https://marcelbraghetto.github.io/a-simple-triangle/2019/06/16/part-17/) that should be possible, though I'd like to get @BastiaanOlij take on it since he has been driving the mobile renderer implementation.

**Comment by Calinou** [comment]
I'd prefer to have the baseline on Android 6.0. We probably don't need to support Android below 6.0 when 4.0 is released, but I think there's still a fair amount of users on Android 6.0 wishing to use the OpenGL renderer.

Also, in my experience, Vulkan support is pretty broken on Android 7 and 8 anyway. The first version where it's actually usable is Android 9. If you actually set the baseline for
*good* Vulkan support, it would be Android 9, which is too high.

**Comment by m4gr3d** [comment]
Follow-up update:

Updated the min supported version to **21** (Android 5 Lollipop). This provides 98.8% device coverage and addresses the issues reported in https://github.com/godotengine/godot/issues/62464 & https://github.com/godotengine/godot/issues/63945

**Review by akien-mga — APPROVED** [review]
Bumping to API 21 makes perfect sense for Godot 4.0. OpenGL ES 3.0 support pre-Android 5 would anyway be quite unreliable, and any Google Play release now needs to support x86_64/arm64 so API 21 is a requirement.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
