### PR TITLE
Fix shrunk ColorPickers

### PR DESCRIPTION
**Pull request by ghost**
This PR sets minimum size for ColorPicker HSV selector to theme constant.

Before
screenshot from 2017-07-18 06-06-24
After
screenshot from 2017-07-18 07-36-16

Affects:
Theme Editor Plugin (ColorPickerButton)
Script Editor
Property Editor
Gradient Editor Plugin

### CODE REVIEW

**Comment by bojidar-bg** [comment]
I think I've seen shrunk pickers in other places as well, probably the remote inspector..

**Comment by Noshyaar** [comment]
Picker in the remote inspector [looks fine](https://user-images.githubusercontent.com/26753932/27796567-acfb91ca-6034-11e7-9835-88e26cdc60d3.png) for me. I'll check the source to see the usage of ColorPicker.

**Comment by bojidar-bg** [comment]
@Noshyaar Ah, ok, probably I messed up somehow...

**Comment by Noshyaar** [comment]
Not really. I've just found one in ScriptTextEditor. (and also learn about this functionality :P)
Hopefully this is all of them.

**Comment by reduz** [comment]
I don't understand the bug, but we should probably go to default_theme.cpp, set a default minimum size scaled by DPI and enforce it in the picker.

**Comment by Noshyaar** [comment]
Please test on Mid-HiDPI. Thank you.

**Comment by kubecz3k** [comment]
@Noshyaar Could you write some short description, and maybe upload some screen with the issue? It probably would be easier for reviewers to understand what exactly this pr is fixing :)

**Comment by Noshyaar** [comment]
Before
screenshot from 2017-07-18 06-06-24
After
screenshot from 2017-07-18 06-08-57

**Comment by akien-mga** [comment]
The fix looks a bit convoluted when it should be IMO just setting a minimum size for ColorPicker that scales with the DPI, but then I'm not fully familiar with this widget anyway :)

**Pull request merged**
