### PR TITLE
Fix spelling & grammar in comments, docs, and messages

### PR DESCRIPTION
**Pull request by asmaloney**

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Changes look good, could you squash commits into one?

And for reference, did you find those using [codespell](https://github.com/codespell-project/codespell) or a different tool?

**Comment by asmaloney** [comment]
> Changes look good, could you squash commits into one?

Oh, sure. I thought you would just use GitHub's "Squash & Merge".

> And for reference, did you find those using codespell or a different tool?

I did start with codespell. I think all but one spelling mistake was found using it. Of course it doesn't handle the grammar (e.g. amount vs. number).

**Comment by asmaloney** [comment]
BTW, in case anyone else wants to join the fun, here's the codespell command I used. It's not as clean as it could be, but it got me most of the way there.

```
codespell --skip="*.o,./doc/translations/*,./.git/*,*.pyc,*.a,*.png,./thirdparty/*,./editor/translations/*"
```

**Comment by akien-mga** [comment]
> BTW, in case anyone else wants to join the fun, here's the codespell command I used. It's not as clean as it could be, but it got me most of the way there.
> 
> ```
> codespell --skip="*.o,./doc/translations/*,./.git/*,*.pyc,*.a,*.png,./thirdparty/*,./editor/translations/*"
> ```

Nice! See also ab3bccdb78cc7dffb6ab796053ef63489f05558d for a list of words to exclude to reduce false positives.

**Comment by akien-mga** [comment]
Thanks!

**Comment by asmaloney** [comment]
>  list of words to exclude to reduce false positives.

Neat!

"merchantibility" - I reported that as a bug in the CC license. :-)

**Pull request merged**
