### PR TITLE
Added pitch scale property to AudioStreamPlayer, AudioStreamPlayer2D and AudioStreamPlayer3D

### LINKED ISSUE #15253: Audio time manipulation (with pitch change)
The new audio engine in 3.0 supports pitch changes without modifying the tempo, however it would be great to have a tempo/speed change effect. No need to keep the same pitch. Something like the pitch option for samples in 2.1.

### PR DESCRIPTION
**Pull request by mrcdk**
Should fix https://github.com/godotengine/godot/issues/15253

It let you do this:
https://streamable.com/o2bxj

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by akien-mga** [comment]
Does this fix #10094 too?

**Comment by mrcdk** [comment]
I think so. It's hard to tell because people tend to mix the terms and I don't blame them, they are a bit confusing. I'm no expert on the topic so I may be wrong but:

- Sometimes people want to change the pitch only which is what the `PitchShift` audio effect does. It changes the pitch without changing the tempo. 

- Sometimes people want to speed up the song and change the pitch too which is what this `pitch_scale` property and `AudioStreamRandomPitch` do.  It changes the pitch and the tempo (speeds up or down the song).

- And this is what I think reduz says it's too heavy processing (for a video game engine at least). People want to change the tempo without changing the pitch.

**Comment by hpvb** [comment]
Cherrypicked into 3.0.3

**Comment by MaaaxiKing** [comment]
Will there someday be the possibility to change only the pitch and only the tempo or does nobody care anymore about this because this was closed?

**Comment by Transaticka** [comment]
indeed being able to change just playback or just pitch would be golden.

**Comment by daniyyelfelipe** [comment]
Right now I need to do exactly this in one of my projects, change just the playback speed of a audio, would be great to have this option available at the engine.

**Comment by dancodedev** [comment]
Yes, this would also be great for me, it would be a great help.

**Comment by Calinou** [comment]
> Yes, this would also be great for me, it would be a great help.

You can use the audio bus effect AudioEffectPitchShift for this purpose. Make an AudioStreamPlayer play sound to a dedicated bus that uses this affect.

**Comment by dan-agenciat1** [comment]
@Calinou 

Hello, thank you very much for explaining, but I have been confused, what I really want is to change the speed without affecting the tone, that is, a Phase vocoder, Short-time Fourier algorithm. Do you know how it can do that? Thanks

**Pull request merged**
