### PR TITLE
Timeout when connecting to routers during UPNP discovery

### LINKED ISSUE #30195: UPNP discovery indefinitely freezes in some cases
**Godot version:**

9ca1a5af3e8186c396e5b8c74b2cebe1e25a65c9

**OS/device including version:**

Arch Linux

**Issue description:**

Calling `upnp.discover()` indefinitely freezes Godot, where it should eventually exit with an error code. 

**Steps to reproduce:**
Call `upnp.discover()` with a router acting as an access point in the current NAT.

**Minimal reproduction project:**

[godot-upnp-example.zip](https://github.com/godotengine/godot/files/3342307/godot-upnp-example.zip)

### PR DESCRIPTION
**Pull request by creikey**
Fixes #30195

### CODE REVIEW

**Comment by akien-mga** [comment]
Is there really no other solution than to modify third-party code? I would find it surprising that miniupnpc does not provide any public API to handle something as basic as a timeout.

**Comment by Faless** [comment]
@akien-mga I think this was fixed upstream:
https://github.com/miniupnp/miniupnp/commit/2656f41c7a9e5a6fb3856f0b69982351b290bc19 , we just need to update our thirdparty library.

**Comment by akien-mga** [comment]
Alright, updating to their current master branch would be good then. Apparently we're already on a master commit instead of 2.1 stable (though the commit hash referenced in `thirdparty/README.md` doesn't seem to exist...).

**Comment by Faless** [comment]
yep, I noticed, I'm working on it :)

**Comment by akien-mga** [comment]
Superseded by #30205. Thanks for the contribution nevertheless!

**Pull request closed without merging**
