### PR TITLE
Various fixes and small features

### PR DESCRIPTION
**Pull request by SaracenOne**
Sorry for the delay on this. Here's a cherry-picked branch containing some fairly minor bugfixes and small features which I hope you wouldn't mind including. I'll be sending more soon.

### CODE REVIEW

**Comment by akien-mga** [comment]
Wow, that's a lot of commits. Though there might be some very interesting fixes here, it likely won't get merged as is as it's just too hard to review so much stuff at once.

You should ideally do one separate PR for each feature and each bugfix that you are proposing. You can of course have several commits in the same PR, but they should all relate to the same feature or bugfix.

**Comment by SaracenOne** [comment]
Quite understandable. I probably should have been sending these a lot earlier and they gathered as a bit of a backlog, but I'm a still somewhat unfamiliar with intricacies of using Git collaboratively. I'll see if I can divide this into a bunch of seperate pull requests.

**Comment by akien-mga** [comment]
Basically you should be able to create one branch per pull request, and then from within a newly-created branch, cherry-pick the relevant commits from your pull_request branch (using ```git cherry-pick```).

**Comment by SaracenOne** [comment]
Thank you, I'm on it now.

**Pull request closed without merging**
