### PR TITLE
add Swift bridging header to iOS export template [3.2]

### PR DESCRIPTION
**Pull request by DrMoriarty**
@naithar 
This is necessary for using iOS plugins with Swift code

### CODE REVIEW

**Comment by naithar** [comment]
I don't really see a point in adding bridging header and swift support for every possible project. 

The downside of it - increased binary size just from a single file, even if no Swift code is actually used. This issue is even worse on older iOS versions. 
It would also require to keep `SWIFT_VERSION` and other swift-specific flags updated, not that it's a big issue really. And it could probably be simplified by using `xcconfig ` files. 

Also plugins are static libraries, shouldn't it just work as long as you don't call Swift code directly? `xcframework` might not load without `-ObjC` linker flags, but other than that everything should work fine. Or I'm wrong?

If bridging header is indeed necessary I would probably prefer to extend export and plugin configuration to support it. It might require to do some refactoring for `export.cpp` for iOS first to make it simplier.

**Comment by DrMoriarty** [comment]
This is what happens when someone compile exported project with any Swift enabled plugin:
image_2021_03_05T04_55_19_232Z

I think that it would be nice if iOS export window will have a parameter for enabling Swift if user wants it.

**Comment by naithar** [comment]
That's because Xcode project is missing Swift libraries. 

I guess it could be worked around somehow using `dependency` sections. 
But implementing `Support's Swift runtime` flag in export or plugin config would work better any way.

But as I said, it should be an option so users that don't use Swift-based don't get it's runtime.

**Comment by DrMoriarty** [comment]
Ok. I agree with you.

**Pull request closed without merging**
