### PR TITLE
Renamed Vector2.tangent to perpendicular

### PR DESCRIPTION
**Pull request by Chaosus**
One of the proposed renames from https://github.com/godotengine/godot/issues/16863#issuecomment-618294043

### CODE REVIEW

**Comment by aaronfranke** [comment]
The documentation is still "Returns a perpendicular vector", and it seems a bit strange for the only description to be the same as the name of the method. We may as well take this opportunity to update the documentation to be more descriptive. Specifically, it should note that the resulting vector is rotated 90 degrees counter-clockwise compared to the original, with the same length.

**Review by aaronfranke — APPROVED** [review]
I just rebased and tested this, looks good to me.

**Comment by reduz** [comment]
Well, in the context of where it is used, it should not be ambiguous, so I am not sure about this rename.

**Comment by akien-mga** [comment]
Superseded by #44149.

**Pull request closed without merging**
