### PR TITLE
Remove note about missing per-vertex-shading

### PR DESCRIPTION
**Pull request by TheYellowArchitect**
Followup to https://github.com/godotengine/godot/pull/83360

### CODE REVIEW

**Review by Calinou — DISMISSED** [review]
There's also a note that needs to be removed in BaseMaterial3D:

```
doc/classes/BaseMaterial3D.xml:
  352  			Sets whether the shading takes place, per-pixel, per-vertex or unshaded. Per-vertex lighting is faster, making it the best choice for mobile applications, however it looks considerably worse than per-pixel. Unshaded rendering is the fastest, but disables all interactions with lights.
  353: 			[b]Note:[/b] Setting the shading mode vertex shading currently has no effect, as vertex shading is not implemented yet.
  354  		</member>
```

**Comment by TheYellowArchitect** [comment]
Nice catch! :+1:

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Looks good to me. The commits need to be squashed into one before this can be merged. See [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) for one explanation on how to do do that.

**Comment by AThousandShips** [comment]
And please update your commit message to be more descriptive, the title of the PR would be appropriate, using `git commit --amend` (after squashing)

**Comment by TheYellowArchitect** [comment]
Thank you both for the suggestions. I didn't expect the rebase to be that easy (instead of `upstream/master` basically `master` lol)

I also did `git commit --amend` and at local git log it shows there is only 1 commit, but in github it shows 2, no idea what happened there

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉

**Pull request merged**
