### PR TITLE
 Update OSX joypad GUID to SDL uid conversion.

### LINKED ISSUE #39157: Issues with Input.get_joy_guid and Input.add_joy_mapping
**Godot version:** v3.2.1.stable.official
**OS:** macOS Catalina v10.15.5
**Other:** SDL Gamepad Tool v2.0.7

**Issue description:**
While using SDL Gamepad Tool, I noticed the GUID (from tool) is different than what is returned by `Input.get_joy_guid()`:

Tool: "Xbox One Wired Controller", **03000000c62400003a54000000000000**
Godot: "Xbox One Wired Controller", **c6240000000000003a54000000000000**

I first noticed this when attempting to use `Input.add_joy_mapping` because it was not working. After replacing the GUID with what Godot returns in `Input.get_joy_guid`, it did work, but:

`Input.add_joy_mapping` seems to ignore the `~` for inverting an axis, as in: `lefty:a1~`

**Steps to reproduce (`Input.get_joy_guid`):**
1. Download [SDL Gamepad Tool v2.0.7](https://generalarcade.com/gamepadtool/).
2. Run Gamepad Tool with a gamepad connected (usb or bluetooth both work with the same results).
3. Note the device GUID in the output window, just below "Found 1 gamepad(s):".
4. In Godot, create a script that prints `Input.get_joy_guid(0)`.
5. Observe the Godot GUID differs from the SDL Gamepad Tool GUID.

**Steps to reproduce (`Input.add_joy_mapping`):**
1. Run Gamepad Tool again and click `Create A New Mapping`.
2. Go through the steps to create a a new mapping.
3. Click `Copy Mapping String`.
4. In Godot, in the script created from above, paste the string from the Gamepad Tool.
5. Replace the GUID supplied from the Gamepad Tool with the GUID returned from Godot.
6. In the mapping string, locate `lefty:a1` (the value may not be `a1`), insert a `~` just after `a1` so that it looks like: `lefty:a1~`.
7. Program a simple player-controller using Input Actions that utilize the left stick Y axis.
8. Observe the axis is not inverted as it should with a `~` present.
9. Be sure to test without the `~` as well.

**Minimal reproduction project:**
[JoyGUIDAndMappingIssue.zip](https://github.com/godotengine/godot/files/4704993/JoyGUIDAndMappingIssue.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Should fix #39157.

Since I don't have controllers or even an macOS machine to test this with, I need help with testing.
cc @JohnCWakley

### CODE REVIEW

**Comment by JohnCWakley** [comment]
@madmiraal : I would be happy to test for you... I will clone the branch and give it a whirl...

**Comment by akien-mga** [comment]
Note that it's based on the `master` branch and you'll need the Vulkan SDK set up to build and run Godot on macOS.

But you can also apply those changes manually (or via `git cherry-pick`) on the `3.2` branch and it should work on 3.2.2-beta.

**Comment by JohnCWakley** [comment]
@akien-mga : Thank you for the note. I already have the vulkan sdk for my own research projects (it's soo verbose!)

@madmiraal : It still is not working and I know why. the `sprintf` call last argument is `0`. The SDL sdk uses the HID Version Number here. I added a few lines to your branch, may I commit them? Or paste them here?

**Comment by madmiraal** [comment]
@JohnCWakley Thanks for testing and identifying the HID version number being needed too.
> I added a few lines to your branch, may I commit them? Or paste them here?
Whatever is easiest for you.

**Comment by JohnCWakley** [comment]
I will commit my changes to your branch...

**Comment by madmiraal** [comment]
@JohnCWakley I've updated the commit and made you co-author. Test away.

**Comment by JohnCWakley** [comment]
@madmiraal : Thank you for making me co-author, I am honored. I've tested the changes and everything is working as expected.

There is one small caveat: I have an odd-ball controller who's vendor id is missing a leading zero, but that is another issue and I haven't fully investigated.

**Comment by madmiraal** [comment]
> There is one small caveat: I have an odd-ball controller who's vendor id is missing a leading zero, but that is another issue and I haven't fully investigated.

@JohnCWakley It sounds like we're not quite there. The vendor id shouldn't need a leading zero. We should be creating the correct uid from the information available. What is the uid from Godot vs. the SDL tool?

**Comment by JohnCWakley** [comment]
@madmiraal I am still investigating this. It may have been my own mistake. I will follow up with you as soon as I have an answer.

**Comment by JohnCWakley** [comment]
@madmiraal I started with a fresh set of constants in my test code and everything is working as expected with the odd-ball controller I was using. I must have left out a zero when manipulating the GUID sections around to better understand them. My apologies. I believe this we are good to go.

**Comment by akien-mga** [comment]
Thanks to you both :)

**Comment by JohnCWakley** [comment]
@akien-mga it has been my pleasure to contribute to this amazing project!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
