### PR TITLE
Renames: align to horizontal_alignment, valign to vertical_alignment, *Container/Tabs alignment, related

### PR DESCRIPTION
**Pull request by nathanfranke**
See: https://github.com/godotengine/godot/issues/54161 (no comment AFAIK)

Also unifies the repeated enums in different classes such as Label, Button, etc.

### CODE REVIEW

**Comment by pycbouh** [comment]
So in all those classes that didn't have horizontal fill option, does this introduce an undefined behavior now?

**Comment by nathanfranke** [comment]
> So in all those classes that didn't have horizontal fill option, does this introduce an undefined behavior now?

Looks like most classes add FILL as an alias of LEFT, so I did that for the rest of the switch statement.

**Comment by nathanfranke** [comment]
Any ideas on why the static check is failing? Even if I change the type to "Error" it shows "ERROR: Unresolved type 'Error', file: Button"

**Comment by pycbouh** [comment]
> Any ideas on why the static check is failing? Even if I change the type to "Error" it shows "ERROR: Unresolved type 'Error', file: Button"

I think you have a typo, you refer to `[HorizontalAlignment]` and `[enum HorizontalAlignment]` there in the docs in one place, both can't be true anyway, but I also think that neither will link properly. It should probably be `[enum @GlobalScope.HorizontalAlignment]`.

**Comment by akien-mga** [comment]
We discussed this in a PR meeting and agreed that this makes sense.

There's a couple points that could still be worked on though:
- `InlineAlign` should also be renamed to `InlineAlignment` for consistent (or everything back to `Align` if we think it's enough)
- Having those definitions in `math_defs.h` is weird, but that was already the case before this PR. But this looks like it could be moved to a class enum in `Control`. The only two classes which wouldn't have access to it right away would be `Font` and `TextParagraph`, but they could likely include `control.h` for that?

**Comment by nathanfranke** [comment]
> * Having those definitions in `math_defs.h` is weird, but that was already the case before this PR. But this looks like it could be moved to a class enum in `Control`. The only two classes which wouldn't have access to it right away would be `Font` and `TextParagraph`, but they could likely include `control.h` for that?

Doesn't look like it's easily possible. `control.h` depends on `text_server.h`, but now `text_server.h` also depends on `control.h`.

**Comment by akien-mga** [comment]
> > * Having those definitions in `math_defs.h` is weird, but that was already the case before this PR. But this looks like it could be moved to a class enum in `Control`. The only two classes which wouldn't have access to it right away would be `Font` and `TextParagraph`, but they could likely include `control.h` for that?
> 
> Doesn't look like it's easily possible. `control.h` depends on `text_server.h`, but now `text_server.h` also depends on `control.h`.

Maybe `text_server.h` is a good location for this? Not sure. WDYT @bruvzg?

**Comment by nathanfranke** [comment]
FYI `InlineAlignment`, `BoxContainer`, `TabContainer`, `TabBar` alignments are renamed. However the main enums are still in Global Scope

**Comment by bruvzg** [comment]
> Maybe text_server.h is a good location for this?

I guess it make sense to move text alignment enums to the text server. It should not cause any dependency issues, but I'm not sure if it's better than global space.

**Comment by akien-mga** [comment]
Alternatively if we want to keep them in global space, I think some of the enums in `math_defs.h` should be moved to a new dedicated file as they have nothing to do with math.
But that's maybe out of scope for this PR.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by nathanfranke** [comment]
@akien-mga Uh oh! Something slipped by GH actions somehow: https://github.com/godotengine/godot/blob/master/editor/plugins/material_editor_plugin.cpp#L128

Should I make a follow up, or can you just commit a fix?

**Pull request merged**
