### PR TITLE
Add missing new function parameter to fix button presses.

### LINKED ISSUE #61422: Editor: AnimationLibrary editor buttons do not work
### Godot version

v4.0.alpha.custom_build [410b6b5f7]

### System information

Linux (Fedora 36)

### Issue description

When managing animations on an AnimationPlayer, only the Add Library, Load Library, and OK buttons function. Pressing any buttons in the list of animations and animation libraries has no effect other than printing the following error:
```
ERROR: Error calling from signal 'button_clicked' to callable: 'AnimationLibraryEditor::AnimationLibraryEditor::_button_pressed': Method expected 3 arguments, but called with 4..
   at: emit_signalp (core/object/object.cpp:1131)
```

### Steps to reproduce

1. Open a scene with an AnimationPlayer node.
2. Select the AnimationPlayer, go to Animation -> Animation -> Manage Animations.
3. Add a library if there is none. Try clicking the buttons in the animation library list.

### Minimal reproduction project

[AnimationIssue.zip](https://github.com/godotengine/godot/files/8774530/AnimationIssue.zip)
Contains a scene with an AnimationPlayer with an empty default animation library.

### LINKED ISSUE #62149: Cannot save animation libraries
### Godot version

4.0.dev (15740c37a3)

### System information

Linux, 64-bit, Fedora 36, AMD RX 590, Vulkan

### Issue description

Trying to save an animation libraries fails, reporting _button_pressed called expected 3 arguments but was called with 4.

### Steps to reproduce

Try to save an animation library by clicking the save button in the the tree column.  The popup that allows you to select the message is never shown and an error is printed out.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by tdaven**
Fix the _button_pressed method to include 4 parameters instead of 3 so it doesn't fail when called.

*Bugsquad edit: This closes #62149 and closes https://github.com/godotengine/godot/issues/61422.*

### CODE REVIEW

**Comment by tdaven** [comment]
This fixes #62149.

**Comment by Calinou** [comment]
> This fixes https://github.com/godotengine/godot/issues/62149.

You need to write this in the first post for automatic closing on merge to work. I edited the first post accordingly :slightly_smiling_face:

**Comment by and-rad** [comment]
This PR would also fix #61422. There's already PR #61490 to fix it, but that one and this one do it slightly differently.

**Review by akien-mga — APPROVED** [review]
This is correct. Same as https://github.com/godotengine/godot/pull/62134 but it wasn't merged due to Git issues.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
