### PR TITLE
Port transformation window to 2D

### PR DESCRIPTION
**Pull request by MarcusElg**
Proposal: https://github.com/godotengine/godot-proposals/issues/1690

The transformation window is very useful if you quickly want to move something 10 units away for example so I've started the work of porting it to 2D. Spending all day on this and trying many different ways I finally got it working.

image

EDIT: Undo support has now been added so it would be great if someone could review this because I'm sure the code can be inproved!

### CODE REVIEW

**Comment by MCrafterzz** [comment]
Updated to add undo support :D

**Comment by asheraryam** [comment]
The changes look good to me 👍

**Comment by MCrafterzz** [comment]
@KoBeWi who would be the right person to review such a problem?

**Comment by groud** [comment]
Hmm, I am not sure about how useful is the feature in the current state.

Considering that what it does is simply modifying the properties themselves and provides no "common transform" for all selected objects. What you have here is simply equivalent to do adding an amount to the property in the inspector. For example, you can select your object rotation's property and append "+10" at the end of the property to increase the rotation of 10 degrees. So there is not need for such a panel for single objects.

The only thing it brings is the possibility to do that over several objects, which, IMHO, should be something handled better by the inspector. Something like a variable name when you select several node so that you can do operations with the value. (Adding 10 to the rotation of each node should be possible then)

An other solution might be to make the panel able to use a single transform to apply to all nodes. Like rotating all selected nodes around a given pivot. But this is quite difficult to implement, as I did not manage to do it for the basic rotation tool.

Anyway, this is definitely not my preferred way of allowing multiple nodes transform, but until we implement a way to apply an operation on a property of several nodes, I guess this could be added.
I would rather discuss that in a PR meeting first though.

**Comment by MCrafterzz** [comment]
> Hmm, I am not sure about how useful is the feature in the current state.
> Considering that what it does is simply modifying the properties themselves and provides no "common transform" for all selected objects. What you have here is simply equivalent to do adding an amount to the property in the inspector. For example, you can select your object rotation's property and append "+10" at the end of the property to increase the rotation of 10 degrees. So there is not need for such a panel for single objects.
> The only thing it brings is the possibility to do that over several objects, which, IMHO, should be something handled better by the inspector. Something like a variable name when you select several node so that you can do operations with the value. (Adding 10 to the rotation of each node should be possible then)
> An other solution might be to make the panel able to use a single transform to apply to all nodes. Like rotating all selected nodes around a given pivot. But this is quite difficult to implement, as I did not manage to do it for the basic rotation tool.
> Anyway, this is definitely not my preferred way of allowing multiple nodes transform, but until we implement a way to apply an operation on a property of several nodes, I guess this could be added.
> I would rather discuss that in a PR meeting first though.

@groud 
Sure it may not be the best way (idk) but I feel like such a system should be consistent between 3D and 2D and as this feature has long been accepted for 3D it should work in 2D.

**Comment by groud** [comment]
> Sure it may not be the best way (idk) but I feel like such a system should be consistent between 3D and 2D and as this feature has long been accepted for 3D so it should work in 2D. Don't you want consistency as well when it comes to similar systems?

Feature parity it is not needed for consistency if one of the two parts does not need it. 
The transform panel is useful in 3D because transforms can be much more difficult to handle. As in 3D rotations might be done in different orders, there is no simple way to transform object as you wish simply by modifying their properties. In 2D, this is significantly easier, so the need for a dedicated panel is more limited.

The toolbar being already crowded (specifically when you have editor plugins activated, like for tilemaps or control nodes), we have to be conservative about what we add in this toolbar.

**Comment by MCrafterzz** [comment]
> Sure it may not be the best way (idk) but I feel like such a system should be consistent between 3D and 2D and as this feature has long been accepted for 3D so it should work in 2D. Don't you want consistency as well when it comes to similar systems?
> 
> Feature parity it is not needed for consistency if one of the two parts does not need it.
> The transform panel is useful in 3D because transforms can be much more difficult to handle. As in 3D rotations might be done in different orders, there is no simple way to transform object as you wish simply by modifying their properties. In 2D, this is significantly easier, so the need for a dedicated panel is more limited.
> The toolbar being already crowded (specifically when you have editor plugins activated, like for tilemaps or control nodes), we have to be conservative about what we add in this toolbar.

Ok bring it up on the pr meeting and let me know!

**Comment by MCrafterzz** [comment]
@groud shouldn't you add the for pr meeting tag so people know?

**Comment by MCrafterzz** [comment]
@groud any update on this?

**Comment by MCrafterzz** [comment]
@aaronfranke have you still not had that meeting?

**Comment by groud** [comment]
Ah sorry, that's not really my fault but we kind of reorganized our workflow to focus on proposals now. I'll ask on IRC right now, but in any case I'll add it to the next proposal review meeting.

**Comment by fire** [comment]
Is it possible to rebase this on master? I don't have enough effort to rebase it correctly. Busy :(

**Comment by aaronfranke** [comment]
@MCrafterzz The last PR review meeting was 6 months ago in April, you'll need to ask @akien-mga when there will be more. Anyway, as @fire said, you should [rebase](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) this onto master for easier testing and to make sure it still works.

**Comment by MCrafterzz** [comment]
Failed rebase again

**Pull request closed without merging**
