### PR TITLE
EditorInspector - Custom EditorPlugin for Skeletons

### PR DESCRIPTION
**Pull request by marstaik**
The current skeleton editor in the EditorInspector lags hard with many bones and is very inflexible and hard to use for editing very large skeletons.

This is an initial push for a custom SkeletonEditor that has an instant load for complex skeletons with a Bone tree, allows bone re-parenting, keying, enabling/disabled bone pose activity, and all the basics that the previous system allowed.

Preview:
https://f.staik.net/f/2d1.mp4

Based off of: https://github.com/godotengine/godot/pull/33684

### CODE REVIEW

**Comment by RevoluPowered** [comment]
Please can this be considered for merge this is a really amazing addition.

**Comment by fire** [comment]
Bugfix.

```patch
diff --git a/editor/plugins/skeleton_editor_plugin.cpp b/editor/plugins/skeleton_editor_plugin.cpp
index 464720b53e6..08d76c9faf5 100644
--- a/editor/plugins/skeleton_editor_plugin.cpp
+++ b/editor/plugins/skeleton_editor_plugin.cpp
@@ -32,6 +32,8 @@
 
 #include "core/io/resource_saver.h"
 #include "editor/editor_file_dialog.h"
+#include "editor/editor_properties.h"
+#include "editor/editor_scale.h"
 #include "editor/plugins/animation_player_editor_plugin.h"
 #include "scene/3d/collision_shape.h"
 #include "scene/3d/physics_body.h"
@@ -680,8 +682,7 @@ void SkeletonEditor::_notification(int p_what) {
 			create_editors();
 			update_joint_tree();
 			update_editors();
-
-			get_tree()->connect("node_removed", this, "_node_removed");
+			get_tree()->call_deferred("node_removed", this, "_node_removed");
 			file_dialog->connect("file_selected", this, "_file_selected");
 			joint_tree->connect("item_selected", this, "_joint_tree_selection_changed");
 			joint_tree->connect("item_rmb_selected", this, "_joint_tree_rmb_select");```

**Comment by marstaik** [comment]
This work has been updated here: https://github.com/godotengine/godot/pull/36409

**Comment by sabudum** [comment]
How does one get this plugin?

**Pull request closed without merging**
