### PR TITLE
Fix VCS script attachment when using GDScript VCS plugins

### LINKED ISSUE #52195: Using EditorVCSInterface from GDScript triggers an ERR_FAIL_COND
### Godot version

3.4.beta4

### System information

Windows 10; Ubuntu 20.04

### Issue description

I implemented a trivial subclass of EditorVCSInterface in GDScript. The engine detects it, but when clicking the VCS 'Initialize' button, an internal error is printed to the console. See attached project for a sample test-case. Tested on both Windows 10 and Ubuntu 20.04.

Error text:
`
core/object.cpp:998 - Condition "script_instance != nullptr || !script.is_null()" is true.
`

Due to a failing `ERR_FAIL_COND` near line 870 in the current repo (Line 998 in 3.4beta4):

**PermaLink:**
https://github.com/godotengine/godot/blob/e0355d5db67bcdc5b1d3f6f23793b3361b5ae88d/core/object/object.cpp#L870

This appears to be caused by **godot/editor/plugins/version_control_editor_plugin.cpp** near line 110 in the current repo (or near line 120 in 3.4beta4)
```
104	EditorVCSInterface *vcs_interface = memnew(EditorVCSInterface);
105	ScriptInstance *addon_script_instance = script->instance_create(vcs_interface);
106
107	ERR_FAIL_COND_MSG(!addon_script_instance, "Failed to create addon script instance.");
108
109	// The addon is attached as a script to the VCS interface as a proxy end-point
110	vcs_interface->set_script_and_instance(script, addon_script_instance);                 // <-- HERE
```

**PermaLink:**
https://github.com/godotengine/godot/blob/7368004869671d1ada14d0628a11a5ba536147af/editor/plugins/version_control_editor_plugin.cpp#L110

It looks to me like the script instance is already set by `script->instance_create(vcs_interface)`, and that the `set_script_and_instance` line might(?) be redundant.

### Steps to reproduce

1. Load up the sample project
2. Project -> Version Control -> Set Up Version Control -> Initialize
3. Error is printed to the console

### Minimal reproduction project

[TestSCM.zip](https://github.com/godotengine/godot/files/7071202/TestSCM.zip)

### PR DESCRIPTION
**Pull request by twaritwaikar**
Fixes #52195

### CODE REVIEW

**Comment by ChronicallySerious** [comment]
@pycbouh This PR is currently only for 3.x. There is no VCS plugin for 4.0 as of now so there is no way to test this change on master.

**Comment by pycbouh** [comment]
@ChronicallySerious Sure, you've just made it against the master initially 🙂 Feel free to edit milestone and tags if you know what's best!

**Comment by ChronicallySerious** [comment]
Also this problem I think has arisen only because there is a difference in the behaviour implemented by `NativeScript` and `GDScript` behind the polymorphic `Script::instance_create()` function. For NativeScript, an `instance_create()` followed by a `Object::set_script_and_instance()` seemed to work fine but for GDScript, this was erroring out with a:

```
core/object.cpp:998 - Condition "script_instance != nullptr || !script.is_null()" is true.

``` 
(as seen in https://github.com/godotengine/godot/issues/52195)

**Comment by ChronicallySerious** [comment]
`GDScript::instance_create()` calls `set_script_instance()` on the owner as seen here: https://github.com/godotengine/godot/blob/3.x/modules/gdscript/gdscript.cpp#L94

But `NativeScript::instance_create()` doesn't do that, which makes it necessary for the caller to manually call the `set_script_instance()` function.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
