### PR TITLE
Improve the Timer wait time property hint

### PR DESCRIPTION
**Pull request by Calinou**
- Make it possible to enter more precise values (up to 3 decimals).
- Make it possible to enter values above 4096.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Would it be possible or make sense to use the configurable float step value? https://github.com/godotengine/godot/pull/30776

**Comment by Calinou** [comment]
@aaronfranke It seems I can't use it without manually getting the value from the editor settings, so that'd make it a bit tedious to apply in other places.

**Comment by Calinou** [comment]
@aaronfranke It seems I'd have to fetch the default float step manually to do this, as the property hint `"0.001,4096,or_greater"` won't do this automatically.

**Comment by Calinou** [comment]
@aaronfranke `PROPERTY_HINT_EXP_RANGE` doesn't make use of the default float step yet, so it won't be possible until that's changed.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
