### PR TITLE
Fix GPUParticles2D ignoring AtlasTexture region

### LINKED ISSUE #13923: Particles 2D ignore AtlasTexture region
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3 beta 1

**Issue description:**

Atlas texture region for particles is working in Godot2, but not in 3. 
Atlas texture works in Sprite in both.
The image shows same resource (AtlasTexture) for the two nodes:
I try all options of ParticlesMaterial / CanvasItem/ AtlasTexture etc... etc...

particles2ddoesntlikeatlas

### PR DESCRIPTION
**Pull request by Geometror**
Fixes #13923.
Also fixes GPUParticles2D's texture not updating in some cases.

### CODE REVIEW

**Comment by Calinou** [comment]
Out of curiosity, do you know if a similar approach can be used for GPUParticles3D?

**Comment by Geometror** [comment]
@Calinou The problem is GPU-/CPUParticles3D use regular meshes with normal materials, so the logic would have to go in BaseMaterial3D. As BaseMaterial3D supports many different kind of textures (normal, detail, roughness,...) I think this would get quite complicated or it wouldn't be feasable at all since you can't guarantee that every texture is an AtlasTexture.

**Comment by kleonc** [comment]
It won't work for AtlasTextures with margins. To properly take margins into account `points` would also need to be changed (and it would need to be taken into account in `uvs` as well). Also would be nice if these would be calculated iteratively so nested AtlasTextures would be supported too.

**Review by clayjohn — APPROVED** [review]
This matches the behaviour of CPUParticles2D and is a big improvement over doing nothing. 

To properly take margin into account, we will need to make further changes to how UVs are computed by both CPUParticles2D and GPUParticles2D, but that can be done in another PR

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by Geometror** [comment]
Rebased.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
