### PR TITLE
Make heightmap shape usable in PhysicsServer

### LINKED ISSUE #17790: Invalid size check prevents setting data of Heightmap shape
Godot 3.0.2

This line says it all: 
https://github.com/godotengine/godot/commit/ffc3ef86778f486823bedf66cc5a937fc09abe6a#diff-430f797c6368e08dfec81071fc14a62fR401
I just found the check is wrong, it must use locals instead of member vars.
I could fix it myself but it's too late, I need to sleep now. Maybe I can try and test tomorrow :) 

This also makes the engine crash though, I don't quite understand why.

### LINKED ISSUE #17807: Heightmap shape not working?
Godot 4a5723f59e0437dc9f83f7116b8fddd12e15c5d0

I've tested for the first time the Heightmap shape, implemented in Bullet and exposed through PhysicsServer, because I need it for my terrain plugin.

However, it looks like it doesn't work at all... so I'm either forgetting something, or there is a bug?

Here is a test project:
[HeightmapShape.zip](https://github.com/godotengine/godot/files/1853745/HeightmapShape.zip)

The cube is supposed to land, or at least tumble on the ground, but at the moment it just falls through it...
I tried the same code by creating a box with `PhysicsServer` instead, and it worked, so I think there is a bug.

cc @AndreaCatania 

That's the state of the shape when it gets added:
image

### PR DESCRIPTION
**Pull request by Zylann**
Fixes #17790 and fixes #17807

### CODE REVIEW

**Comment by Zylann** [comment]
Actually I found other issues similar to that one, which might be the cause of https://github.com/godotengine/godot/issues/17807.
I'm working to improve that.

**Comment by Zylann** [comment]
I updated the PR with more fixes and improvements:
- Fixed bad size check
- Fixed bad member initialization
- Removed unused cell_size (Bullet expects us to use localScaling)
- Accept precomputed min/max height, will be calculated if not provided

**Comment by Zylann** [comment]
Tested with a real heightmap https://www.youtube.com/watch?v=RedUqzO3Y7I&feature=youtu.be

**Comment by akien-mga** [comment]
CC @AndreaCatania for review - @reduz is fine with the change.

**Comment by AndreaCatania** [comment]
It's perfect! We now need create new godot shape type

**Comment by BastiaanOlij** [comment]
Nice one guys!!

**Comment by BastiaanOlij** [comment]
If this means that we can now use a planemesh (properly subdivided) together with a heightmap (i.e. vertex shader that uses the heightmap) to then couple a heightmap collision shape, then WOW.

Also good reason to update the tutorial that we have on the subject in the docs!

**Comment by aurodev** [comment]
Thanks!  On our way to an awesome terrain engine! 
/goodjob

**Comment by hpvb** [comment]
Cherry picked into 3.0.4

**Comment by ConnorBP** [comment]
Is this not added? There doesn't seem to be any way to add height maps to collision...

**Comment by Zylann** [comment]
@ConnorBP it was added at PhysicsServer level. It can be used from scripts (which I do in my GDScript plugin) but there are no high-level node or resource API for it yet. I think @BastiaanOlij has a pending PR for this.

**Comment by BastiaanOlij** [comment]
Yup, #27156 :)

**Comment by ConnorBP** [comment]
> Yup, #27156 :)

That's awesome :D good work hope it gets in. I may see about trying that in my local build.

**Pull request merged**
