### PR TITLE
Documentation: Treat deprecated/experimental members as documented

### PR DESCRIPTION
**Pull request by dalexeev**
* See https://github.com/godotengine/godot/pull/81458#issuecomment-1945884960.
* Don't show `There is currently no description for this <member_type>.` if member is marked as deprecated/experimental.
* Update `doc_status.py` and `make_rst.py`.
* Improve `EditorHelp` code style.

### CODE REVIEW

**Comment by Mickeon** [comment]
I do enjoy the codestyle changes in EditorHelp a lot, <sub>despite the fact that I'm going to be very miserable later because they conflict with a PR I have yet to publish because I forgot to.</sub>

**Review by Mickeon — APPROVED** [review]
Took a look at it again. This is good and great.

In my opinion it would be nice if only **one** newline was used (instead of two) for deprecated things, just to shorten how much space these messages occupy when a description ACTUALLY exists (I'm working on it). But it's very opinionated indeed.

**Review by Calinou — APPROVED** [review]
Code looks good to me at a glance.

It makes sense to ignore deprecated/experimental members in the completion percentage too.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
