### PR TITLE
Moving more thirdparty stuff (minizip, some single-file external libs) to the thirdparty directory

### PR DESCRIPTION
**Pull request by akien-mga**
That has been on my TODO list for a while... moving the big libraries to `thirdparty/` was a first step, but we still had some small single-file libraries bundled in `core/` and a few other places.

With this PR, most such external sources should be properly split to thirdparty, thus handling most files mentioned in #5248.

Still bundled are (that I know of):
- some platform-specific code: Android, BB10, UWP (check #5248)
- bundled source in `servers/physics/gjk_epa.cpp`
- bundled source in `servers/physics/joints_{,2d_}sw.cpp`

If you know of more bundled thirdparty code, I'm interested :)

### CODE REVIEW

**Comment by reduz** [comment]
Gjkepa is modified to fit godot and kind of harcoded.. so probably not much
of a point in moving it. Joints is the same.

Bb10 should probably go away at this point, the platform is officially dead.


On Apr 28, 2017 8:22 PM, "Rémi Verschelde" <notifications@github.com> wrote:

That has been on my TODO list for a while... moving the big libraries to
thirdparty/ was a first step, but we still had some small single-file
libraries bundled in core/ and a few other places.

With this PR, most such external sources should be properly split to
thirdparty, thus handling most files mentioned in #5248
<https://github.com/godotengine/godot/issues/5248>.

Still bundled are (that I know of):

   - some platform-specific code: Android, BB10, UWP (check #5248
   <https://github.com/godotengine/godot/issues/5248>)
   - bundled source in servers/physics/gjk_epa.cpp
   - bundled source in servers/physics/joints_{,2d_}sw.cpp

If you know of more bundled thirdparty code, I'm interested :)
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/godotengine/godot/pull/8572
Commit Summary

   - Move core thirdparty files to thirdparty/{minizip,misc}
   - Split thirdparty smaz.c out of compressed_translation.cpp
   - Move other lone thirdparty files to thirdparty/misc
   - Add a few missing copyright headers

File Changes

   - *M* core/SCsub
   <https://github.com/godotengine/godot/pull/8572/files#diff-0> (46)
   - *M* core/bind/core_bind.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-1> (4)
   - *M* core/compressed_translation.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-2> (211)
   - *M* core/image.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-3> (3)
   - *M* core/io/SCsub
   <https://github.com/godotengine/godot/pull/8572/files#diff-4> (2)
   - *M* core/io/compression.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-5> (8)
   - *M* core/io/file_access_encrypted.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-6> (11)
   - *M* core/io/file_access_zip.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-7> (4)
   - *D* core/io/sha-README.md
   <https://github.com/godotengine/godot/pull/8572/files#diff-8> (5)
   - *M* core/io/zip_io.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-9> (5)
   - *M* core/math/math_funcs.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-10> (3)
   - *M* core/os/file_access.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-11> (6)
   - *M* core/ustring.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-12> (5)
   - *M* drivers/convex_decomp/SCsub
   <https://github.com/godotengine/godot/pull/8572/files#diff-13> (9)
   - *M* drivers/convex_decomp/b2d_decompose.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-14> (3)
   - *M* editor/editor_export.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-15> (4)
   - *M* editor/export_template_manager.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-16> (33)
   - *M* editor/export_template_manager.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-17> (29)
   - *M* editor/io_plugins/editor_texture_import_plugin.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-18> (4)
   - *M* editor/plugins/curve_editor_plugin.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-19> (30)
   - *M* editor/plugins/curve_editor_plugin.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-20> (29)
   - *M* editor/plugins/gradient_texture_editor_plugin.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-21> (33)
   - *M* editor/plugins/gradient_texture_editor_plugin.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-22> (29)
   - *M* modules/openssl/SCsub
   <https://github.com/godotengine/godot/pull/8572/files#diff-23> (11)
   - *M* modules/openssl/stream_peer_openssl.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-24> (6)
   - *M* modules/stb_vorbis/audio_stream_ogg_vorbis.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-25> (3)
   - *M* modules/stb_vorbis/audio_stream_ogg_vorbis.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-26> (2)
   - *M* modules/theora/video_stream_theora.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-27> (3)
   - *M* modules/webm/video_stream_webm.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-28> (3)
   - *M* platform/uwp/export/export.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-29> (9)
   - *M* scene/2d/collision_polygon_2d.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-30> (5)
   - *M* scene/2d/navigation_polygon.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-31> (4)
   - *M* scene/SCsub
   <https://github.com/godotengine/godot/pull/8572/files#diff-32> (19)
   - *M* scene/resources/SCsub
   <https://github.com/godotengine/godot/pull/8572/files#diff-33> (1)
   - *M* scene/resources/dynamic_font_stb.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-34> (1)
   - *M* scene/resources/dynamic_font_stb.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-35> (3)
   - *M* scene/resources/surface_tool.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-36> (3)
   - *M* thirdparty/README.md
   <https://github.com/godotengine/godot/pull/8572/files#diff-37> (92)
   - *R* thirdparty/b2d_convexdecomp/b2Glue.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-38> (0)
   - *R* thirdparty/b2d_convexdecomp/b2Polygon.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-39> (0)
   - *R* thirdparty/b2d_convexdecomp/b2Polygon.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-40> (0)
   - *R* thirdparty/b2d_convexdecomp/b2Triangle.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-41> (0)
   - *R* thirdparty/b2d_convexdecomp/b2Triangle.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-42> (0)
   - *R* thirdparty/minizip/LICENSE-InfoZip.txt
   <https://github.com/godotengine/godot/pull/8572/files#diff-43> (0)
   - *R* thirdparty/minizip/LICENSE-MiniZip.txt
   <https://github.com/godotengine/godot/pull/8572/files#diff-44> (0)
   - *R* thirdparty/minizip/crypt.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-45> (0)
   - *R* thirdparty/minizip/ioapi.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-46> (0)
   - *R* thirdparty/minizip/ioapi.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-47> (0)
   - *R* thirdparty/minizip/unzip.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-48> (0)
   - *R* thirdparty/minizip/unzip.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-49> (0)
   - *R* thirdparty/minizip/zip.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-50> (0)
   - *R* thirdparty/minizip/zip.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-51> (0)
   - *R* thirdparty/misc/aes256.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-52> (0)
   - *R* thirdparty/misc/aes256.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-53> (0)
   - *R* thirdparty/misc/base64.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-54> (0)
   - *R* thirdparty/misc/base64.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-55> (0)
   - *R* thirdparty/misc/curl_hostcheck.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-56> (0)
   - *R* thirdparty/misc/curl_hostcheck.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-57> (0)
   - *R* thirdparty/misc/fastlz.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-58> (0)
   - *R* thirdparty/misc/fastlz.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-59> (0)
   - *R* thirdparty/misc/hq2x.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-60> (0)
   - *R* thirdparty/misc/hq2x.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-61> (0)
   - *R* thirdparty/misc/md5.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-62> (4)
   - *R* thirdparty/misc/md5.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-63> (0)
   - *R* thirdparty/misc/mikktspace.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-64> (0)
   - *R* thirdparty/misc/mikktspace.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-65> (0)
   - *R* thirdparty/misc/pcg.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-66> (0)
   - *R* thirdparty/misc/pcg.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-67> (0)
   - *R* thirdparty/misc/sha256.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-68> (0)
   - *R* thirdparty/misc/sha256.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-69> (0)
   - *A* thirdparty/misc/smaz.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-70> (207)
   - *A* thirdparty/misc/smaz.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-71> (20)
   - *R* thirdparty/misc/stb_truetype.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-72> (0)
   - *R* thirdparty/misc/stb_vorbis.c
   <https://github.com/godotengine/godot/pull/8572/files#diff-73> (0)
   - *R* thirdparty/misc/triangulator.cpp
   <https://github.com/godotengine/godot/pull/8572/files#diff-74> (0)
   - *R* thirdparty/misc/triangulator.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-75> (0)
   - *R* thirdparty/misc/yuv2rgb.h
   <https://github.com/godotengine/godot/pull/8572/files#diff-76> (0)

Patch Links:

   - https://github.com/godotengine/godot/pull/8572.patch
   - https://github.com/godotengine/godot/pull/8572.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/pull/8572>, or mute the thread

**Comment by tagcup** [comment]
`core/math/pcg.{cpp,h}`

We'll have changes in physics code during transition to 64-bit floats overall, so I think we should leave them there.

**Comment by akien-mga** [comment]
> core/math/pcg.{cpp,h}
>
> We'll have changes in physics code during transition to 64-bit floats overall, so I think we should leave them there.

I don't understand. What does it change for the physics code if the pcg implementation is in `core/math/` or `thirdparty/misc/`?

**Comment by tagcup** [comment]
Sorry, I didn't write it clearly. Those are two totally distinct things, having nothing to do with each other.

About joints stuff: it has already been modified to use real_t, which is relevant for switching to 64-bit floating point numbers.

**Pull request merged**
