### PR TITLE
Check input mesh is valid in SurfaceTool methods

### PR DESCRIPTION
**Pull request by rafallus**
Fixes: #46004

*Bugsquad edit: `3.x` version of https://github.com/godotengine/godot/pull/48376.*

### CODE REVIEW

**Comment by fire** [comment]
Prefer ERR_FAIL_NULL_V, ERR_FAIL_NULL instead of cond check is_null. I like the fix.

**Comment by fire** [comment]
The message variants of those cond checks exist too.

**Comment by rafallus** [comment]
Doesn't work with `ERR_FAIL_NULL`, gives the following `error: no match for 'operator!' (operand type is 'const Ref<Mesh>')`

**Review by fire — APPROVED** [review]
The code looks good to me.

**Comment by akien-mga** [comment]
These changes also seem relevant for the `master` branch.

**Comment by rafallus** [comment]
On master branch an error displays on the script editor with the message `Invalid argument for "create_from()" function`. The new Gdscript parser recognizes that the argument is invalid and just stops script execution (at least that's how I understand it). The only case where the program crashes is when the argument is an unassigned var:
```
var a
SurfaceTool.new().create_from(aa,0)
```
I guess in this case the parser has no way to know if `a` is of the correct type and doesn't shows any error. Is this something that should be solved on the Gdscript side? Or is it better to use the same solution as in 3.x branch?

**Comment by akien-mga** [comment]
@rafallus This crashes too:
```
	var aa = Mesh.new()
	SurfaceTool.new().create_from(aa,0)
```

Whatever validation GDScript can do upfront, the null dereference is still something that can happen from C++ or any valid way to pass a null object, so the guards are needed in `master` too.

**Comment by rafallus** [comment]
I don't get why `aa = Mesh.new()` acts like a null object when it clearly isn't, is just an empty mesh. Anyway I'm porting this to master branch

**Comment by akien-mga** [comment]
Needs a rebase (style change in `3.x` branch), otherwise seems good to merge.

**Comment by akien-mga** [comment]
Force pushed a rebase on latest `3.x`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
