### PR TITLE
Exposed internal kinematic test APIs

### LINKED ISSUE #18624: KinematicBody behaviour bugs with Bullet physics engine
**Godot version:**
af9a6202ebb1eda4f928d2d601162cf4b211752b

**OS/device including version:**
Windows 10

**Issue description:**
I had previously created an extension to Godot's KinematicBody node which includes features like ramp and stairs traversal, and which seemed to run exactly as intended under the old Godot physics system, but under the new Bullet physics, a variety of issues have appeared. These issues can be most obviously observed by testing with the provide test project I have linked to and trying it with both physics engines. The code which previously allowed seamless traversal over a variety of difficult surfaces now no longer works as intended. It should be worth noted however that not ALL of these issues which now appear were present in the last stable release of Godot, even when using the Bullet physics engine, and this can also be tested by running the provided project with a stable release of the engine. However, the stable release STILL does have issues with the Bullet physics engine which are just less obvious. These can often be observed by attempting to ascend the ramp from the side or attempting to land on the crack in the wall. @AndreaCatania has expressed an interest in trying to debug this issue further, but all help would be appreciated.

**Steps to reproduce:**
Simply test the provided project under the latest build of Godot and run it with both the old GodotPhysics engine and the new Bullet physics engine. If you want to test this under the previous stable release (I've only tested this with the Steam build assuming this is the latest stable build), use the 'extended_kinematic_body' godot_3_stable branch or download the stable zip file project.

**Minimal reproduction project:**
https://github.com/SaracenOne/godot_extended_kinematic_body_testbed
[godot_extended_kinematic_body_testbed_bleeding_edge.zip](https://github.com/godotengine/godot/files/1976306/godot_extended_kinematic_body_testbed_bleeding_edge.zip)
[godot_extended_kinematic_body_testbed_stable.zip](https://github.com/godotengine/godot/files/1976307/godot_extended_kinematic_body_testbed_stable.zip)

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixes #18624

### CODE REVIEW

**Comment by reduz** [comment]
I don't understand why you want to expose this, specially when the issue you make reference to mentions that he could do it without exposing these functions in the old Godot physics.

**Comment by reduz** [comment]
Also, adjusting feet to stairs or anything else is usually done with raycast from the hip to the feet, and then adjusting IK, so i am not quite sure what this is for

**Comment by AndreaCatania** [comment]
Expose it, gives the possibility to every create its own movement system and algorithm. For example you can find a lot of plugins in unity / unreal that implement kinematic motion from scratch supporting different cases that are not supported in the default agorithm and this is possible because the low level API are exposed.

Nothing change from the prospective of default API move_and_slide. It simply add two APIs that open more possibilities.

**Comment by reduz** [comment]
Sorry, I feel this should remain as-is. You can re-implement any motion algorithm you want even using the APIs in DirectSpaceState like cast_motion, rest info, etc. They were actually even originally done this way, but test_body_motion was added mainly for performance and adding some small hacks.

**Comment by and3rson** [comment]
It's a pity this was not merged. move_and_* are usually not enough, and their docstrings are really outdated and missing documentation.

**Pull request closed without merging**
