### PR TITLE
Fix drag notifications across windows.

### LINKED ISSUE #44390: Valid drop locations are not highlighted when inspector is made floating.
**Godot version:**
4.0 master 2020-12-15

**OS/device including version:**
Win 10

**Issue description:**
No highlighting on valid drop locations in inspector after it has been made floating.
floating_inspector_no_highlight

**Steps to reproduce:**
Make inspector floating, try to drag and drop.

### PR DESCRIPTION
**Pull request by reduz**
Fixes #44390.

### CODE REVIEW

**Comment by Sauermann** [comment]
This is an alternative approach to #67531.

From what I can tell, this PR solves a single problem (highlighting ValidDrop locations of child Windows and SubViewports) of the many problems related to Drag and Drop with Windows and SubViewports, while the other PR intends to solve all of them.

Since the other PR no longer makes use of `_propagate_viewport_notification` it could be considered as superseding this PR.

Here is a MRP for stress-testing Drag and Drop with Windows and SubViewports [BugDragNDrop.zip](https://github.com/godotengine/godot/files/9824946/BugDragNDrop.zip)

**Comment by reduz** [comment]
@Sauermann This fixes sub-viewports too (although i realized a problem in this PR that needs to be further fixed). The proper handling of the drag preview needs to be done by moving it to a transparent window with passthrough, but that should be implemented in a separate PR.

**Comment by Sauermann** [comment]
> I wrote #71509 as a far simpler way to solve this. I believe It fixes drags/drops accross viewports more elegantly.

After investigating this topic more deeply, one problem area, that I was able to identify is, that the Viewport, that the mouse is over, is identified in the following code section:
https://github.com/godotengine/godot/blob/23e10d1dfff00eb1ea932b0d3e89ca444b5c0a51/scene/main/viewport.cpp#L1830-L1845
And this code section doesn't account for SubViewports and embedded Windows.
My conclusion is, that in order to fix Drag and Drop for Viewports, it is necessary make this code-section aware of SubViewports and embedded Windows. This conclusion aligns with my tests of this PR with the previously linked MRP, which show that Drag and Drop with Viewports is not yet solved completely.

**Comment by YuriSizov** [comment]
Needs some consensus and conclusion. We can pick it for 4.0.x though, so bumping for now.

**Comment by akien-mga** [comment]
Superseded by #67531.

**Pull request closed without merging**
