### PR TITLE
Fix gridmap free octans

### PR DESCRIPTION
**Pull request by Valeryn4**
Fix GridMap problem [issue](https://github.com/godotengine/godot/issues/49995)

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
Looks great! This fixes #33648, #43712 and #49995 which are all the same bug.

The only thing is a PR should be opened on master instead of 3.3 branch. It's the usual process for fixes that can be applied to the latest version of Godot (it will still be cherry-picked for 3.3 and 3.4).

I would suggest to close this PR and open the same one on master (switching branches causes issues with github, it's interpreted as trying to merge the whole branch).

**Comment by Valeryn4** [comment]
> I would suggest to close this PR and open the same one on master (switching branches causes issues with github, it's interpreted as trying to merge the whole branch).

Sorry)
This error stopped my development progress)

**Comment by pouleyKetchoupp** [comment]
No worries at all, your fix is very welcome!

Let me know in case it's too much extra work for you to set things up on master. Instead another contributor can open the new PR on master and credit you for your work.

**Comment by Valeryn4** [comment]
Pull PR : [#50052](https://github.com/godotengine/godot/pull/50052)

**Pull request closed without merging**
