### PR TITLE
Fix seek end loop anim.

### LINKED ISSUE #85220: Seeking to looped animation end, actually seeks to beginning.
### Godot version

3.x

### System information

Godot v4.2.rc (a34814b0b) - Ubuntu 23.10 23.10 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) () - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

When you seek with code to end of looped animation it seeks to beginning.

	extends Node2D

	@onready var _sprite = $Sprite2D
	@onready var _animation = $Sprite2D/AnimationPlayer

	func _ready():
		_animation.seek(0.9, true)
		_animation.pause()

Fix: https://github.com/godotengine/godot/pull/85186

### Steps to reproduce

1. Create an animation, e.g. for scale
2. Set length to 0.9 and snapping to 0.1
3. Add a key at the beginning and end
4. Enable looping
5. run code to display last frame. but shows first

### Minimal reproduction project

[ReproductionProject.zip](https://github.com/godotengine/godot/files/13440804/ReproductionProject.zip)

### PR DESCRIPTION
**Pull request by rakkarage**
Closes: https://github.com/godotengine/godot/issues/85220

### CODE REVIEW

**Comment by AThousandShips** [comment]
Should be tested against the changes in https://github.com/godotengine/godot/pull/85193 to see if changes are needed based on this

**Comment by rakkarage** [comment]
Because it not use mod to go back to first frame when done.

Seek to start = mod(0.1, 0.9) == 0.1: unchanged
Seek to middle = mod(0.45, 0.9) == 0.5: unchanged
Seek to end = mod(0.9, 0.9) 0: Should be 0.9

Seek pingpong to end = pingpong(0.9, 0.9) = 0.9

**Comment by AThousandShips** [comment]
I'm just quoting the comment to ensure it is recognised here, I didn't report it

**Comment by TokageItLab** [comment]
The biggest problem with this implementation is that the loop animation does not loop when seeking beyond the length of the animation. If you seek 0.3 seconds from the 0.8 second point in a 0.9 length animation, it must be 0.2.

**Comment by TokageItLab** [comment]
This is a PR that has already been closed once, so it is closed again. As noted above, there may be room for improvement in the handling of the last key during seek,

> Since it is too rare case a important key at the end of a loop animation (and it is not supposed to be), and more often a important key at the beginning, so that check would cause more problems that the beginning key not being processed than the end key not being processed.

> If there are enough demands/samples for the use case of placing important keys at the end of loop animations with seeking, there may be room for improvement, but it should be in the key retrieval functions such as _track_get_key_indices_in_range(), not here, so the code here should never be changed.

but in any case, a different approach would need to be taken to improve this PR.

**Pull request closed without merging**
