### PR TITLE
[macOS export, 3.x] Implements ad-hoc signing on Linux/Windows.

### PR DESCRIPTION
**Pull request by bruvzg**
Backport of #51310 for 3.x

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Should be good to merge once rebased and reworked like the `master` PR.

The `platform/*/export/` refactor was also done in 3.4 (#52515) so the same logic can be used here.

**Comment by bruvzg** [comment]
> Should be good to merge once rebased and reworked like the master PR.

This one is more bitroten than a `master` version and will need a bit more work, it's no longer working as expected.

**Comment by bruvzg** [comment]
> need a bit more work, it's no longer working as expected.

Seems to work fine now. There's no `PoolVector` list initializers in 3.x, so I left this part as is.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
