### PR TITLE
[GDScript] Add `StringName` support to `@GDScript.len`

### LINKED ISSUE #8774: Add support for StringName in len function
### Describe the project you are working on

A weird text based game

### Describe the problem or limitation you are having in your project

len(&"test") throws an error, but is expected to return the length of the StringName, similar to how len("test") would show the length of the String. Strings and StringName can be used interchangeably in most other GDScript contexts however where len works for Strings, it does not work for StringNames.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Update the GDScript len function to also support returning the length of a StringName. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This would make len behave same for both Strings and StringNames, so you could do len(&"test") and get a result

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around using the StringName.length() function which does the same thing. However using len is the most common method and unexpectedly breaks for StringNames where all other string functions are shared between the two. 

### Is there a reason why this should be core and not an add-on in the asset library?

StringNames are core

### PR DESCRIPTION
**Pull request by AThousandShips**
* Closes: https://github.com/godotengine/godot-proposals/issues/8774

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Makes sense to me. Would be good to have this approved by someone from the GDScript team too.

**Review by dalexeev — APPROVED** [review]
It would be great to add tests for utility functions, but it is not required for this PR. The docs could be updated:

https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/modules/gdscript/doc_classes/%40GDScript.xml#L147-L151

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you! First PR of 2024!

**Pull request merged**
