### PR TITLE
UI: ability to add multiple child nodes in single click

### PR DESCRIPTION
**Pull request by d-j-a-y**
Usage:
When FOCUS on tree node, multiple nodes can be selected using the
[space] key . Hodling [ctrl] on single mouse click add to current
selection. [shift] mouse click also work for grouped selection.
If no node selected, [Create] button is desabled.

Nota:
* multiple node selection not active with search node feature.
* Multiselect mode is disabled for other than node creation.

### CODE REVIEW

**Comment by akien-mga** [comment]
To be honest I'm not convinced about the usefulness of such a feature, nor it's discoverability. In my experience it's pretty rare that one needs to instance multiple nodes each of a different type at once; most often you need to instance multiple nodes of the same time.

I'd be interested to have opinions from other users about it.

**Comment by toger5** [comment]
I think the workflow: `meta+a -> type in the node name -> up-arrao -> enter -> meta + a ...` is almost as good as it can get.
maybe there could be shift+meta+a to create a node to the parent of the selected node.
`shift+meta+a -> type in the node name -> enter` repeat...

**Comment by akien-mga** [comment]
I'm still no convinced, and since this got very little feedback from interested users, I guess it doesn't address a use case that Godot users really need. It's not a bad feature, but Godot's philosophy is to only add code if it addresses a real use case, to avoid have the code base growing to a hard to maintain state.

So closing for now. If some users are interested, the code is still available to be rebased and advocated for :)

**Comment by d-j-a-y** [comment]
I still loving you :-)

cheers.

**Pull request closed without merging**
