### PR TITLE
Use YXZ convention for Euler angles.

### PR DESCRIPTION
**Pull request by ghost**
As discussed in issues #1479 and #9782, choosing the up axis (which is Y in Godot) as the axis of the last (or first) rotation is helpful in practical use cases.
This also aligns Godot's convention with Unity, helping with a smoother transition for people who are used to working with Unity (issue #9905).

Internally, both XYZ and YXZ functions are kept, for potential future applications.

### CODE REVIEW

**Comment by HummusSamurai** [comment]
I took a look at https://github.com/godotengine/godot/issues/1479 and oh wow that was a lot of mathematical discussion to go through, but overall I'm glad this is how it will be done.

**Comment by RandomShaper** [comment]
I wasn't aware of the discussion that led to this, but I'm taking the chance to give my support to this.

Yaw, pitch, roll or sideways, up-down, lateral tilt is more natural for those like me that use Euler where possible. It covers better the use cases for us.

**Comment by Zireael07** [comment]
I don't recall any gimbal lock issues in Unity while I almost immediately ran into them in Godot, so making the Euler angles resemble Unity's is IMHO a very good idea.

**Comment by tagcup** [comment]
Thanks but this PR really can't solve any real issues at all, if you're using Euler angles correctly, all conventions are equivalent. Also you can't avoid gimbal lock with Euler angles, it will always be there whichever convention you use.

The hope here is to simplify (meaning, get a simpler set of Euler angles) for certain common situations.

**Comment by RandomShaper** [comment]
But as @HummusSamurai says (do he have a chef here?), yaw-pitch (Y, X), in that order, feels natural and fit use cases like simple first or third person approaches.

In the worst case, that eases prototyping for those, like me, less used to quaternions, etc.

Come on! Be happier about this PR! :)

**Comment by RandomShaper** [comment]
Well, you said something similar, too.

(It's a pity GitHub doesn't email-notify edits.)

**Comment by tagcup** [comment]
Ah, OK :)

**Comment by tagcup** [comment]
Just trying to keep expectations realistic

**Comment by tagcup** [comment]
@HummusSamurai I meant to include #1479 in the commit message but somehow missed it, thanks for pointing it out. I modified the commit message with it.

**Comment by HummusSamurai** [comment]
@RandomShaper "use cases like simple first or third person approaches."

Thank god!

And yes I dabble in the culinary arts. :D

**Comment by tagcup** [comment]
I haven't seen your changes in the platformer demo (maybe you haven't submitted a PR yet?), but such use cases are best handled using axis-angle parametrization: there is an axis-angle rotation function in Basis, or you can use it through quaternions if you want to interpolate rotations.

For game code, I can't think of a situation for which Euler angle parametrization is well suited,  except for simulating things that truly work like a gimbal. With this PR, the only use case I have in mind is hand-typed in-editor orientation.

**Comment by HummusSamurai** [comment]
You are correct, I have not submitted a PR (waiting for some discussion), but currently my code uses Basis rotations on the transformation matrix, so if that's more accurate then it'll probably stay.

**Comment by tagcup** [comment]
I haven't done an error analysis so I actually don't know which one would be more accurate, but what I wanted to say is that axis-angle representation is the proper way to parametrize rotations (not just for 3D rotations for SO(3), but for any Lie group).

Euler angle parametrization is different, it simulates a mechanical gimbal, which is essentially an ancient mechanical computer (long preceding digital computers) to calculate rotations, in a mathematically poor way (because they don't map to 3D rotations one-to-one). Nowadays, they make sense if you need to simulate something that actually works like a gimbal (maybe some mechanical device or head), or arranging things visually by eye in a non-rigorous way using 3 sequential rotations. Not much otherwise.

**Comment by HummusSamurai** [comment]
@tagcup Ah that makes more sense.

Well since the calls to transformation matrices won't be going away anytime soon, I guess the best option would be to implement a couple decent cameras and publish them on the asset store.

(One for a 3rd person camera that can rotate around the player, another for a 1st person camera like in most FPS games).

**Comment by m4nu3lf** [comment]
@tagcup Can't we expose both, or maybe expose a function that takes a constant to express the convention? Something like get_euler(Basis.PARAM_EULER_XYZ)?
I like the change but I also need the xyz Euler angles from a transform because the Generic6DOFJoint works with that convention and I need to translate from some rotation matrices to Euler angles.

**Pull request merged**
