### PR TITLE
Add info label to TileMap editor

### LINKED ISSUE #5792: Add debug label with mouse coordinates and hovered tile name to tilemap editor
### Describe the project you are working on

project with tilemap

### Describe the problem or limitation you are having in your project

placing tile in exact position/cell and viewing which tile already under mouse position

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

add simple label to view it

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

this is how it looks `3.x` branch
i believe this is cell + tile name under mouse position

image

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/5792

godot windows editor dev x86_64_ZJnl9T9QDf

The label will display current tile position and rectangle size if drawing rect.

### CODE REVIEW

**Review by kleonc — APPROVED** [review]
LGTM.

**Comment by Calinou** [comment]
Is it possible to display the the name/ID of the currently hovered tile?

**Review by mhilbrunner — APPROVED** [review]

**Comment by KoBeWi** [comment]
> Is it possible to display the the name/ID of the currently hovered tile?

Tiles no longer have name and their ID is simply their coordinates in the atlas.

We could probably display the source name and scene name in case of scene tiles, but implementing it isn't exactly trivial (I assume; at least with scene names), so it's something that can *maybe* be done later. Note that Ctrl+clicking a tile highlights it in the tileset, so this information can be easily found.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Comment by riazey** [comment]
Ahh I've been waiting for this! No more guesstimating what tile I need to teleport my character to xD

**Pull request merged**
