### PR TITLE
[Core] Move `Math` methods

### PR DESCRIPTION
**Pull request by Nazarwadim**
Here I made the `snap` method inline. And also moved very heavy methods and methods that are not used to `.cpp`.
Because I moved the heavy methods to `.cpp`, the engine size even decreased by 5 KB.

### CODE REVIEW

**Comment by MewPurPur** [comment]
Could you explain your reasoning for this? We shouldn't have to guess.

**Comment by Nazarwadim** [comment]
> I'm not sure about this one, these methods could potentially benefit greatly from optimization and are used in some somewhat intensive codepaths like animation, this could hurt performance, would be good to make sure it doesn't

Methods `cubic_interpolate_angle` `cubic_interpolate_angle` `cubic_interpolate_angle_in_time`
`cubic_interpolate_angle_in_time` method generally uses another heavy interpolation method as a return value.

**Comment by AThousandShips** [comment]
They might be optimized for example by elimination of stack transfers as they do have several large arguments, and since they mostly call other methods I wouldn't be surprised if there's a lot of room for optimization here to happen

**Comment by AThousandShips** [comment]
I'd suggest this change requires benchmarking to make sure, no use in guessing

**Pull request closed without merging**
