### PR TITLE
Make sun energy adjustable as a float in the 3D editor's preview sun

### LINKED ISSUE #76677: Sun Energy is int instead of float .
### Godot version

4.0.3

### System information

windows 10 amdA6 integrated graphics

### Issue description

The sun energy value displayed in the Preview Sun window is shown as an integer instead of a float value. This makes it difficult to adjust the sun energy efficiency precisely.
Currently, when i attempt to adjust the sun energy i are only able to do so in whole numbers. This is not ideal, as we often need to make more precise adjustments to get the desired lighting effect.
ScreenCapture20230428_233022_881
I would like to look into it if you also thinks its minor bug and can be a good first contribution.

### Steps to reproduce

go to the panel in the image.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by HotHead007**
This fixes #76677

### CODE REVIEW

**Review by clayjohn — CHANGES_REQUESTED** [review]
It looks like you have added a few empty files while making this PR. You will need to manually delete them, then rebase and force push to this branch. 

To do so, first delete the extra files you created then use:
```
git add .
git commit --amend
git push origin master
```
This is assuming that your fork is located at the remote origin

**Comment by HotHead007** [comment]
Sorry for the silly mistakes.

**Review by clayjohn — APPROVED** [review]
Looks good now! Great perseverance! Using git can be pretty tricky at first, but it gets easier.

**Review by smix8 — APPROVED** [review]

**Comment by clayjohn** [comment]
Thank you! And congratulations on your first merged contribution!

**Comment by Deozaan** [comment]
> This fixes #76701

It actually fixed #76677 🙂

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
