### PR TITLE
Add String.is_not_empty() and replace remaining String comparisons

### PR DESCRIPTION
**Pull request by KoBeWi**
See https://github.com/godotengine/godot/pull/43181#issuecomment-1140216508
IMO kind of not worth it if we don't have this method in containers too, but whatevs.

### CODE REVIEW

**Comment by timothyqiu** [comment]
Is there a dedicated word that describes "string not empty"? e.g. We use `ref.is_valid()` for `ref.is_not_null()`.

**Comment by aaronfranke** [comment]
@timothyqiu The closest would be `.has_content()`, but I think `.is_not_empty()` is better.

**Comment by lyuma** [comment]
functions with negatives in their name are harder to comprehend... and I'm afraid that someone might use `is_not_empty()`  in an if / else, leading to a double-negative.

If avoiding the use of `!is_empty()` is a goal, my suggestion is to use the existing `.length()` function, since the implicit boolean conversion will do the same thing as the proposed `is_not_empty()` function. This practice is common in other languages, such as `if len(x):
```
if (string.length()) { ... }
```

An idiom I'd like to propose which might be more deliberate is to use an `explicit operator bool()`, which will allow using simply `if (some_string) { ... }`

If we do this, it might also be cool to provide an `operator!()` to allow for `if (!some_string)` as an alternative to is_empty.

In the past, use of `operator bool` was discouraged because of type safety bugs in the c++ spec. The `explicit operator bool` solves this. Seeing as Godot uses operators in many other parts of the code it seems like a reasonable approach in the context of how Godot does things.

**Comment by KoBeWi** [comment]
This is pointless and doesn't seem like there is much interest in merging it, so closing.

**Pull request closed without merging**
