### PR TITLE
Various optimizations to compiler flags on X11

### PR DESCRIPTION
**Pull request by brakhane**
Various optimizations to the compiler flags on X11, ordered from least to most intrusive.
#### Prepend -O options instead of appending

This way, they can be overwritten by passing different CFLAGS/CCFLAGS to scons.
The last option takes effect, therefore we need to prepend them to the
user supplied flags.
#### pass "-pipe" to compiler and linker

GCC will use pipes instead of temporary files with this option,
which decreases compile time noticably.

clang's gcc compability layer also accepts the option, so we don't
have to check for it.
#### Use '-Og' for debugging if available.

Since 4.8 GCC supports the -Og optimization option. According to the
documentation:

> -Og enables optimizations that do not interfere with debugging.
> It should be the optimization level of choice for the standard
> edit-compile-debug cycle, offering a reasonable level of optimization
> while maintaining fast compilation and a good debugging experience.

clang doesn't support it, and people might use a pre 4.8 compiler, so
we check if the flag is supported and only use it if it is.

### CODE REVIEW

**Comment by zaps166** [comment]
Hi!
Did you try debugging with `-Og`?
Hmm, I've tried `-Og` many times and debugging with this is much worse than on `-O0` level. E.g.
```C++
#include <stdio.h>
static inline int asd()
{
	int i = 5;
	i += 5;
	return i;
}
int main()
{
	const int a = asd();
	printf("%d\n", a);
	return 0;
}
```
The `inline asd() {}` function is not debuggable on `-Og`, but is debuggable on `-O0`. Adding `-fno-inline` also doesn't fully help. Maybe I'm doing something wrong? Or `-Og` is buggy in my GCC?

According to:
> Request debugging information and also use level to specify how much information. The default level is 2.
Level 0 produces no debug information at all. Thus, -g0 negates -g.
Level 1 produces minimal information, enough for making backtraces in parts of the program that you don't plan to debug. This includes descriptions of functions and external variables, and line number tables, but no information about local variables.
Level 3 includes extra information, such as all the macro definitions present in the program. Some debuggers support macro expansion when you use -g3.


`-g2` is a default level, maybe use just `-g` or `-g3` for max. level of debugging?

**Comment by slapin** [comment]
The -Og option adds -f options which are safe for debugging.
-O0 will be easier in all cases, but -Og is good compromise.
Also -O0 might produce really different results than other optimization options,
so if something works with -O0 might not work with -O2. I think it is easier to edit SConstruct file
for your options (or add environment variable) than inventing all possible build configurations.
I'd leave that to engine users to decide.

Also don't mess -Og and -g options - they do totally different things.

**Comment by zaps166** [comment]
> Also don't mess -Og and -g options - they do totally different things.

Where I wrote that debugging level (`-g`) and optimization level (`-O`) are the same things :D ? I only mentioned that `-g2` is a default level and it is the same as `-g` (especially for GCC).

**Comment by brakhane** [comment]
@zaps166 `-Og` does indeed inline functions and does various optimizations. In your example, the whole function `asd` can be replaced by `return 10`, which gcc does indeed do. If `asd` would take an argument and uses that as a basis for calculation, you'd still be able to debug it somewhat (gdb supports `step` and `next` even when functions are inlined).

`-Og` is recommended for your normal compile-run-debug cycle where it's more useful to have decent performance than the ability to have the code do everything exactly as you specified. Most of the time, you can debug fine with it, it doesn't reorder instructions or something like it. 

In the rare cases where you can't debug it, you can always compile with -O0.

I've found while hacking on godot that -Og does improve the startup time of the editor noticably, and in 99% of the times i've started the editor, i wasn't even debugging.

**Comment by zaps166** [comment]
@brakhane It depends what is necessary. Sometimes it is enough to use `-O2 -g` :D

**Comment by tagcup** [comment]
Is there a reason for not using -Ofast for release builds?

**Comment by zaps166** [comment]
`-Ofast` is similar to existing `-O3 -ffast-math`. Sometimes more optimizations doesn't mean that it runs faster, but binary is larger.

AFAIK `-Ofast` doesn't exist on older compilers, so it must be checked, similar to `supports_Og` in this PR (I think that old compilers should be dropped for C++11 support).

**Comment by tagcup** [comment]
@zaps166 The same is true of -O2 vs -O3.
-Ofast [adds](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html) -fno-protect-parens and -fstack-arrays (which are for Fortran code anyway) in addition to -ffast-math, and flips on the param allow-store-data-races over -O3, so I don't see how these can actually increase the code size for C++ code. In fact, setting allow-store-data-races should can the binary size a little.

When binary size is a real concern, it should be compiled with -Os anyway.

**Comment by zaps166** [comment]
@tagcup Just for fun (64-bit, `scons p=x11 target=release -j 8 CC=gcc-5 CXX=g++-5 tools=no`, from #6490, stripped):

-O2 -ffast-math - 20.0 MiB
-O3 -ffast-math - 21.7 MiB (22753176 B)
-Ofast - 21.7 MiB  (22749080 B)
-Os -ffast-math - 14.9 MiB

Anyway if compiler supports `-Ofast` it could be enabled :) But `-Og` is not good idea for me as a `-O0` replacement... Maybe as an additional target? Also `-Os` could be as an additional target :smile:
Btw. shouldn't release binaries be stripped (especially for Android)?

**Comment by tagcup** [comment]
Has anyone tried `-flto` or `-fwhopr` with godot?

**Comment by zaps166** [comment]
@tagcup Smaller binary size, similar speed in `zylann` benchmark

Flags: `-flto -Ofast`

Compile time (4C, 8T, similar time to `-O0`): 1m20s
Link time (1T): 5m26s
Stripped binary size: 18.2 MiB

Additional warnings:
```
 extern const mpc_can_data mpc_can_Q [8][2];
                           ^
drivers/mpc/huffman.c:268:14: note: previously declared here
 mpc_can_data mpc_can_Q [6][2] = {
              ^
drivers/theora/video_stream_theora.cpp: In member function 'set_file':
drivers/theora/decode.c:400:49: warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
       qsum+=_dec->state.dequant_tables[qti][pli][qi][12]+
                                                 ^
drivers/theora/decode.c:396:3: note: containing loop
   for(qi=0;qi<64;qi++){
```

Also: `g++-5: error: unrecognized command line option '-fwhopr'`

Benchmark:
- `-Ofast`:
```
-------------------
For time: 28

The following times are in seconds for the whole test.

Empty func (void function call cost): 38
Increment: 14
Increment x5: 90
Increment with member var: 14
Increment with local (outside loop): 12
Increment with local (inside loop): 26
Increment Vector2: 13
Increment Vector3: 13
Increment Vector3 with constant: 13
Increment Vector3 coordinate by coordinate: 284
Unused local (declaration cost): 3
Divide: 31
Increment with dictionary member: 53
Increment with array member: 27
While time (for equivalent with manual increment): 29
if(true) time: 1
if(true)else time: 2
VariantArray resize: 578
VariantArray set element: 8
IntArray resize: 264
IntArray set element: 116
-------------------
Done.
-------------------
For time: 28

The following times are in seconds for the whole test.

Empty func (void function call cost): 36
Increment: 12
Increment x5: 81
Increment with member var: 14
Increment with local (outside loop): 13
Increment with local (inside loop): 26
Increment Vector2: 13
Increment Vector3: 12
Increment Vector3 with constant: 12
Increment Vector3 coordinate by coordinate: 282
Unused local (declaration cost): 3
Divide: 32
Increment with dictionary member: 53
Increment with array member: 27
While time (for equivalent with manual increment): 28
if(true) time: 2
if(true)else time: 1
VariantArray resize: 563
VariantArray set element: 9
IntArray resize: 262
IntArray set element: 114
-------------------
Done.
```
- `-Ofast -flto`:
```
-------------------
For time: 28

The following times are in seconds for the whole test.

Empty func (void function call cost): 38
Increment: 14
Increment x5: 78
Increment with member var: 15
Increment with local (outside loop): 14
Increment with local (inside loop): 28
Increment Vector2: 14
Increment Vector3: 14
Increment Vector3 with constant: 14
Increment Vector3 coordinate by coordinate: 275
Unused local (declaration cost): 6
Divide: 14
Increment with dictionary member: 55
Increment with array member: 28
While time (for equivalent with manual increment): 27
if(true) time: 3
if(true)else time: 2
VariantArray resize: 554
VariantArray set element: 11
IntArray resize: 276
IntArray set element: 115
-------------------
Done.
-------------------
For time: 29

The following times are in seconds for the whole test.

Empty func (void function call cost): 36
Increment: 13
Increment x5: 77
Increment with member var: 14
Increment with local (outside loop): 12
Increment with local (inside loop): 27
Increment Vector2: 14
Increment Vector3: 14
Increment Vector3 with constant: 14
Increment Vector3 coordinate by coordinate: 274
Unused local (declaration cost): 4
Divide: 13
Increment with dictionary member: 54
Increment with array member: 28
While time (for equivalent with manual increment): 28
if(true) time: 1
if(true)else time: 1
VariantArray resize: 561
VariantArray set element: 10
IntArray resize: 270
IntArray set element: 114
-------------------
Done.
```

**Comment by zaps166** [comment]
My suggestions:
- use `-Ofast` if compiler supports it, otherwise use `'-O3','-ffast-math'`,
- add `lto=yes` option to scons, it will use `-flto` for release build (also with `tools=yes`),
- add `opt_debug=yes` option to scons for `-Og` (detection not necessary in this case),
- fix sanitizer usage, currently `use_sanitizer` and `use_leak_sanitizer` do the same thing, so first should be undefined sanitizer (also with different suffixes),
- add `opt_size=yes` option which will use `'-Os','-ffast-math'` for release build (also with `tools=yes`),
- maybe use `-g3` instead of `-g2` - already used on OS X.

**Comment by brakhane** [comment]
There is much discussion about the -Og setting, but nothing about the other parts of the PR.

The PR consists of 3 commits, ordered from the least controversial to the most controversial one (-Og).

Should I update the PR to only include the first 2 commits so we can at least get those in?

**Comment by tagcup** [comment]
I think the other 2 commits are good, and `-Og` should be used for debugging. That's what it is designed for. Similar goes for `-Ofast`. So I'd say please *add* one more commit to use  `-Ofast`.

LTO takes a lot of time and results in marginal gains, so to me, it only makes sense as a new target (`release_lto`?). And maybe another target with `Os` (`release_size`?).

**Comment by akien-mga** [comment]
Superseded by #7645.

**Comment by brakhane** [comment]
#7645 doens't change Append to Preprend and doesn't add the "-pipe" flags. It only handles the last of the three commits.

Should create a new PR which only contains the first two commits?

**Comment by brakhane** [comment]
Also it doesn't add "-Og" to debug builds. Should I assume that the last one is rejected and keep my own fork for developing?

**Comment by tagcup** [comment]
> #7645 doens't change Append to Preprend and doesn't add the "-pipe" flags. It only handles the last of the three commits.

? Surely it adds -pipe flag. And I already added Prepend changes (many hours before your message).

> Also it doesn't add "-Og" to debug builds. Should I assume that the last one is rejected and keep my own fork for developing?

 I think it can still be added behind an option like "debug_opt" as discussed earlier.

**Comment by brakhane** [comment]
> Surely it adds -pipe flag. And I already added Prepend changes (many hours before your message).

I do apologize, I missed that. However, there are still quite a few `env.Append`s concerning CCFLAGS and LINKFLAGS, for exampl in use_lto or use_leak_sanitizer. Or even the "-pipe" flag is appended, not prepended.

I suggest that all compiler flags are prepended, that way, one can always override them if needed.

If you want, we can move the discussion to #7645
> I think it can still be added behind an option like "debug_opt" as discussed earlier.

Fair enough.

**Comment by tagcup** [comment]
I don't understand why we need to worry about those. Can you actually override -pipe? Or what's the point of overriding -flto after specifying use_lto=yes?
You're of course free to address those in a new PR, but I'd prefer to leave those as-is #7645 (which only allows users to override optimization/debug flags).

**Pull request closed without merging**
