### PR TITLE
Expose Object metadata property

### PR DESCRIPTION
**Pull request by marcelofg55**
This is useful when setting or getting the whole metadata.

### CODE REVIEW

**Comment by groud** [comment]
I'm not sure it is a good idea. For example, each plugin might need its specific set of metadata while another need another set. Allowing a global set might erase data from another plugins.

Also, I don't see any usecase for that.

**Comment by marcelofg55** [comment]
@groud For the use case: Currently on my project I have a data.gd that stores game data on a Dictionary variable, when loading/saving I need to get/set the whole Dictionary data on that variable. I've found out that I can use metadata for this instead and on GDNative its faster calling data->get_meta than doing a data->call.

**Comment by groud** [comment]
Well, what you could do is simply use a Dictionary as a metadata variable, instead of using the metadata as your dictionary.

Something like: 
```
var save_dict= {
    health = 10,
    level = 2
}  
my_object.set_metadata("_save_dict", save_dict);
```

That is a cleaner way to solve your problem, and keeps the metadata structure available for other uses (including plugins).

**Comment by marcelofg55** [comment]
Alright, thanks for the solution.

**Pull request closed without merging**
