### PR TITLE
[WIP] Better orbit distance scaling no gravity distance scale

### PR DESCRIPTION
**Pull request by ryanpeach**
REF: #41386

This is an alternative to the referenced pull request completely removing gravity_distance_scale. Which, without the +1, is a redundant parameter.

See this desmos for the comparison.

https://www.desmos.com/calculator/3bofinug4x

### CODE REVIEW

**Comment by madmiraal** [comment]
If the PR is not ready, please mark it as WIP and covert it to a draft.

**Comment by ryanpeach** [comment]
How do I mark it as WIP?

I think the logic is done but it needs testing. The documentation needs editing.

**Comment by madmiraal** [comment]
> How do I mark it as WIP?

I normally just prepend [WIP] to the title.

**Comment by ryanpeach** [comment]
Ok so one of the side effects to this is that gravity needs to be very high for large scales. I recommend we not do this.

**Comment by udit** [comment]
@ryanpeach can you explain what you mean by needing very high gravity for large scales? For the same set of 'g' and 'r' you will get a practically useful gravity when we use the distance scale with 0 < distance scale < 1, is that what you mean? Also, what computational errors were you referring to?

**Comment by ryanpeach** [comment]
I had to set gravity to the 1E5 range to get noticeable orbits at 100-1000 units distance. The slider only goes to 1024. At higher distances this would need to be even higher.

Further, dividing a large G with the square of a large distance may lead to computational errors at high distances, since the square could lead to incredibly large numbers.

Regards,
Ryan Peach
________________________________

**Pull request closed without merging**
