### PR TITLE
Fixed folders not showing in filesystem dock

### PR DESCRIPTION
**Pull request by robertdhernandez**

### CODE REVIEW

**Comment by Hinsbart** [comment]
Any opinions on this?
I think it should be made an option instead

**Comment by akien-mga** [comment]
I wanted to test it to better understand, as looking at the code it just seems to invalidate the split mode logic.

**Comment by robertdhernandez** [comment]
I searched what ```split_mode``` did, but it didn't seem like it was used anywhere. I would like some clarification on what it's supposed to do and be used for, and why it was there.

**Comment by akien-mga** [comment]
I finally got around to testing this and try to understand what it's supposed to do. To speed up the review process, some explanations about what the issue is, and what the fix does, would have been very welcome (especially with screenshots).

The current behaviour is that in split mode (when the Filesystem dock shares its column's height with another dock), folders will be displayed in the thumbnails view as it's the only way to access them:
spectacle h17340

In non split-mode (full height), the folders are shown in the top part of the dock, while the files are at the bottom (either as thumbnails, or as a list view). Having folders shown in the bottom part too would be redundant with the top part and defeats its purpose.
spectacle b17340

So in the end this change is not wanted as it would break the purpose of the full-height (non split) mode. If you would prefer to get the same behaviour as split mode while in full height, you could make a PR that makes this split mode optional in the editor settings.

**Pull request closed without merging**
