### PR TITLE
Fix crash when selecting a keyframe in AnimationPlayer

### PR DESCRIPTION
**Pull request by timoschwarzer**
This is a regression of #97415.

Crash reproduction:

1. Add an AnimationPlayer
2. Create a new track (type does not matter)
3. Create a keyframe in that track
4. Select the keyframe

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution, however there's already an open PR doing this exact fix open:
* https://github.com/godotengine/godot/pull/99148

Closing as a duplicate, thank you nonetheless

**Comment by timoschwarzer** [comment]
@AThousandShips Damn, I searched for "AnimationPlayer crash" but "AnimationPlayer" is not mentioned in that PR :laughing: Thanks!

**Comment by AThousandShips** [comment]
In the future you can use [prs-by-file](https://godotengine.github.io/godot-prs-by-file/) to check what other PRs modify files you are interested in, it can help with these sorts of duplicates!

**Comment by timoschwarzer** [comment]
Today I learned. Thank you!

**Pull request closed without merging**
