### PR TITLE
`:=` fails on some nodes fix: #37357

### LINKED ISSUE #37357: GDScript Animation `:=` false parser error
**Godot version:** 3.2.1

**OS/device including version:** windows

**Issue description:**
1. this line throws a false error 
```
var anim := Animation.new()
```
2. and there was no autocompletion for animation
3. Ctrl+Click also not working for animation methods

animation-not-working

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #37357

### CODE REVIEW

**Comment by bojidar-bg** [comment]
There are two other places in `gdscript_parser.cpp` which compare `PropertyInfo::name` without ensuring that it is not a group or category:
https://github.com/godotengine/godot/blob/fafb0ba06df9417a22bd8deb31a61feeb24de794/modules/gdscript/gdscript_parser.cpp#L7377-L7381
https://github.com/godotengine/godot/blob/fafb0ba06df9417a22bd8deb31a61feeb24de794/modules/gdscript/gdscript_parser.cpp#L7459-L7463

Should they get the same treatment?

**Comment by ThakeeNathees** [comment]
Done! @bojidar-bg  could you review it again

**Review by bojidar-bg — APPROVED** [review]
Odd define, but looks good

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
