### PR TITLE
[WIP] Remove "Bingo!" project manager message

### PR DESCRIPTION
**Pull request by mhilbrunner**
Removes the "Thats a bingo!" message from the project manager.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by YeldhamDev** [comment]
This will make that when toggling the info message, it will show just a empty space.

**Comment by mhilbrunner** [comment]
I'll see about that. Any suggestions for a better message than the current one, then?

**Comment by YeldhamDev** [comment]
@mhilbrunner I fail to see how the current one needs changing. The only argument that I could see is that is kinda silly, but we have dialogs with "Ugh" as their OK button, Godot has some silly places here and there.

**Comment by mhilbrunner** [comment]
I'd argue that "Ugh" needs changing as well, not that the "Bingo!" one is fine because it exists.

**Comment by Noshyaar** [comment]
I agree that it should be removed, the text makes no sense when translated. It's not only about silliness, it's a usability issue. Also, we're in translation freeze and shouldn't add/modify TTR text.

TBH the whole dialog needs to be improved as it's one of the first things new users see.

- Warnings/Errors shouldn't be hidden in the first place.
- Users shouldn't have to click a button to toggle the message.
- New folder should be created automatically if it doesn't exist.
- Buttons are usually used to trigger an action. In this case it hides/shows a label, a code folding arrow would suit better. (IMO)

**Comment by YeldhamDev** [comment]
@Noshyaar If translated literally, yeah, but translation is not about literally translating messages, but adapting then to the language. Also, errors make the message show itself automatically, and as for the other points, I agree.

**Pull request closed without merging**
