### PR TITLE
macOS: Only set entitlements for main binaries, fixing C# signing issues

### LINKED ISSUE #91469: [macOS] Godot 4.3 Dev Snapshot 6 (Mono) - macOS App from TestFlight not working
### Tested versions

- Reproducible in: 4.3 Snapshot 6 (Mono)

### System information

Godot v4.3.dev6.mono - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

### Issue description

I have opened a related issue a while ago, which was partially fixed with 4.3 dev 6 (PR #90428)

I use .NET 8, without AOT (because that caused errors on Apple's side).

Whenever I run the game downloaded via TestFlight I get this on startup:

```
TextServer: Primary interface set to: "ICU / HarfBuzz / Graphite (Built-in)".
.NET: Initializing module...
Found hostfxr: /Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib
ERROR: Can't open dynamic library: /Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib. Error: dlopen(/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib, 0x0002): tried: '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib' (code signature invalid in <A522E666-A68E-3843-8182-1A3913D8C4C4> '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00057030, codeBlobSize=0x00005D80), '/System/Volumes/Preboot/Cryptexes/OS/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib' (no such file), '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib' (code signature invalid in <A522E666-A68E-3843-8182-1A3913D8C4C4> '/Applications/dmArtRace.app/Contents/Resources/data_Art-Race_macos_arm64/libhostfxr.dylib' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00057030, codeBlobSize=0x00005D80).
   at: open_dynamic_library (platform/macos/os_macos.mm:236)
ERROR: Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND
   at: open_dynamic_library (platform/macos/os_macos.mm:233)
ERROR: .NET: Failed to load hostfxr
   at: initialize (modules/mono/mono_gd/gd_mono.cpp:393)
CORE API HASH: 0
EDITOR API HASH: 0

```

### Steps to reproduce

1. Export the game to macOS for App Store
2. Upload it via Transporter
3. Download it via Testflight
4. go to Applications > Game name > Right click on "Show Package Content" > go to Contents/MacOS/ and drag and drop the file to Terminal
5. add "--verbose" option and click enter

In my case it starts as expected, but whenever the game starts executing .NET code, it just crashes with the message above

### Minimal reproduction project (MRP)

I can't provide one at the moment, but I will try to create a similar project if required. However for reproduction an Apple Developer Account will also be necessary.

### PR DESCRIPTION
**Pull request by LeonardoDemartino**
This fixes [#91469](https://github.com/godotengine/godot/issues/91469)

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
That's fine for `.dylib`s but probably should be applied to `.framework`s as well (same issue is likely relevant for GDExtensions).

Something like:
```diff
diff --git a/platform/macos/export/export_plugin.cpp b/platform/macos/export/export_plugin.cpp
index 2ff02d2e74..de145d431f 100644
--- a/platform/macos/export/export_plugin.cpp
+++ b/platform/macos/export/export_plugin.cpp
@@ -1092,7 +1092,7 @@ void EditorExportPlatformMacOS::_code_sign(const Ref<EditorExportPreset> &p_pres
 			List<String> args;
 			args.push_back("sign");
 
-			if (p_path.get_extension() != "dmg") {
+			if (!p_ent_path.is_empty()) {
 				args.push_back("--entitlements-xml-path");
 				args.push_back(p_ent_path);
 			}
@@ -1153,7 +1153,7 @@ void EditorExportPlatformMacOS::_code_sign(const Ref<EditorExportPreset> &p_pres
 				args.push_back("runtime");
 			}
 
-			if (p_path.get_extension() != "dmg") {
+			if (!p_ent_path.is_empty()) {
 				args.push_back("--entitlements");
 				args.push_back(p_ent_path);
 			}
@@ -1237,7 +1237,7 @@ void EditorExportPlatformMacOS::_code_sign_directory(const Ref<EditorExportPrese
 		}
 
 		if (extensions_to_sign.has(current_file.get_extension())) {
-			String ent_path = p_ent_path;
+			String ent_path;
 			bool set_bundle_id = false;
 			if (sandbox && FileAccess::exists(current_file_path)) {
 				int ftype = MachO::get_filetype(current_file_path);
@@ -1357,7 +1357,7 @@ Error EditorExportPlatformMacOS::_copy_and_sign_files(Ref<DirAccess> &dir_access
 			_code_sign_directory(p_preset, p_in_app_path, p_ent_path, p_helper_ent_path, p_should_error_on_non_code_sign);
 		} else {
 			if (extensions_to_sign.has(p_in_app_path.get_extension())) {
-				String ent_path = p_ent_path;
+				String ent_path;
 				bool set_bundle_id = false;
 				if (p_sandbox && FileAccess::exists(p_in_app_path)) {
 					int ftype = MachO::get_filetype(p_in_app_path);
@@ -2210,7 +2210,7 @@ Error EditorExportPlatformMacOS::export_project(const Ref<EditorExportPreset> &p
 				if (ep.step(TTR("Code signing DMG"), 3)) {
 					return ERR_SKIP;
 				}
-				_code_sign(p_preset, p_path, ent_path, false, false);
+				_code_sign(p_preset, p_path, String(), false, false);
 			}
 		} else if (export_format == "pkg") {
 			// Create a Installer.

```
This will also ensure the same is done with built-in ad-hoc signer (which is irrelevant for the issue, but is good for consistency).

**Review by bruvzg — APPROVED** [review]
Seems to be working fine for out of App Store exports.

Please squash the commits into one, see [pull request workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase).

**Comment by akien-mga** [comment]
Thanks!

**Comment by TCROC** [comment]
This fixed it for me!  Just cherry picked it into my fork!  We were running into this issue with all of our gdextensions as well as additional macos frameworks such as godotsteam https://github.com/GodotSteam/GodotSteam

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
