### PR TITLE
Change default video mode for X11

### LINKED ISSUE #3149: Project manager window cursor offset
I recently compiled from source (I think December 26) and I discovered the project Manager window (the  first window you see when Godot launches) has changed to a bigger size.

The problem: there seems to be some kind of offset between the real cursor and the "virtual" cursor. This is visible if you move the cursor over the buttons and see the hover effects.

It's not a big bug, but it's definitively a bug.
Request: The project manager window should also be opened maximized.

### PR DESCRIPTION
**Pull request by vnen**
Fix #3149

### CODE REVIEW

**Comment by reduz** [comment]
patch is ok, but should be added to all PC platforms I guess
queston is, are there really monitors smaller than 1280x720 nowadays?

**Comment by vnen** [comment]
My laptop screen is bigger (1366x768) but with the window manager the usable space is actually less than that, hence the bug happens.

I'll change for other platforms to be consistent, though the bug is X11 only.

**Comment by reduz** [comment]
okay!

**Comment by reduz** [comment]
still, make the vertical default 600, i think godot editor can' t handle
less than that

**Comment by reduz** [comment]
1024x600 should do i think

**Comment by vnen** [comment]
@reduz updated.

**Pull request merged**
