### PR TITLE
Fix some 3D editor label positions

### PR DESCRIPTION
**Pull request by Chaosus**
Looks like FPS label currently is not fully visible due to have incorrect position 

image

this will fix it

image

### CODE REVIEW

**Comment by Chaosus** [comment]
Also fixed Information panel position

Before

image

After

image

**Comment by Chaosus** [comment]
Seems like its a regressions - 3.1.1 does not have that problem

**Comment by akien-mga** [comment]
While the fix seems ok, it would be good to know what caused the regression and see if that's a bigger problem (potentially causing regressions in games) than what this fixes.

**Comment by Chaosus** [comment]
Yeah, I will look on that soon. I close this for now.

**Pull request closed without merging**
