### PR TITLE
[3.x] Clean-up and refactor of the Android input implementation

### LINKED ISSUE #8151: Directories cannot be entered by selecting items from a FileDialog on Android
**Operating system or device - Godot version:**
OS: Android 7.1.1 / LineageOS 14.1
Godot: Godot 2.1.2

**Issue description:**

There is no way for me to choose a folder from the directory listing and make it the current directory. If I want to change the current directory I need to enter the directory name in the top bar.

**Steps to reproduce:**
1) Make a new project with just one scene that is a FileDialog, set to filesystem access and MODE_OPEN_FILE.
2) Go to the export menu for Android and make sure to enable the "Read External Storage" permission.
3) Deploy the project to an Android device.
4) Make sure the app has been given its permissions.
5) Open the app.
6) If the currently displayed directory is empty or only contains the parent directory link, use the top bar to navigate to "/sdcard" for on-device storage.
7) Try to change the current directory to one of the listed directories by choosing it from the menu. I have tried tapping, double tapping, and hitting "Open" after tapping a directory. None of these have changed the current directory.

**Link to minimal example project:**

[filetest.zip](https://github.com/godotengine/godot/files/870390/filetest.zip) (ZIP-exported Godot project)
[filetest-apk.zip](https://github.com/godotengine/godot/files/870391/filetest-apk.zip) (Contains an exported APK)

### PR DESCRIPTION
**Pull request by m4gr3d**
The first commit cleans up and refactors the Android input implementation:
- All input logic is delegated to the `GodotInputHandler.java` class which is now responsible for setting up and configuring the gesture handler logic
- The mouse & touch input logic has been refactored to rely primarily on the gesture handler
- The gesture handler logic was updated to include support for long press, multi-finger panning and scaling gestures. These gestures are disabled by default to mirror the current behavior
- The native input implementation was cleaned up to consolidate the logic in a few methods: `process_touch_event` for touch, `process_mouse_event` for mouse & stylus, and `process_magnify` and `process_pan` for scaling and panning gestures.

In the process, the PR addresses several existing Android input bugs:
Fixes #8151, #46100, #46101

Supersedes #59760, #54225

The second commit enables the long press, multi-finger panning and scaling gestures for the Godot Android Editor and fixes an input related bug that uses to cause a crash when clicking on the `play` button from the editor window.

Addresses some of the issues reported in https://github.com/godotengine/godot-proposals/issues/3931

https://user-images.githubusercontent.com/914968/188551474-33c3b7eb-b549-48c8-8a83-2e9c285c79c4.mp4

[master version](https://github.com/godotengine/godot/pull/65434)

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @madmiraal @thebestnom

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
Should this be considered for a 3.5.1 cherry-pick?

**Comment by m4gr3d** [comment]
> Should this be considered for a 3.5.1 cherry-pick? Having double-tap and right-click will make the Android editor much more usable, without having to wait for 3.6.

@Calinou I think it's risky for a `3.5.1` backport. Since it's a lot of change, I'm expecting to shake out any remaining issues in the new code throughout the `3.6` release process.

For the Android editor, I'm planning to put out a `3.6.beta` release either today or in the next few days for users to update and test without having to wait for the full Godot `3.6` release.

**Comment by VoxSkynned11** [comment]
> > Should this be considered for a 3.5.1 cherry-pick? Having double-tap and right-click will make the Android editor much more usable, without having to wait for 3.6.
> 
> @Calinou I think it's risky for a `3.5.1` backport. Since it's a lot of change, I'm expecting to shake out any remaining issues in the new code throughout the `3.6` release process.
> 
> For the Android editor, I'm planning to put out a `3.6.beta` release either today or in the next few days for users to update and test without having to wait for the full Godot `3.6` release.

:0 omg i am really looking forward to that, thanks for all the hard work

**Comment by VoxSkynned11** [comment]
> > Should this be considered for a 3.5.1 cherry-pick? Having double-tap and right-click will make the Android editor much more usable, without having to wait for 3.6.
> 
> @Calinou I think it's risky for a `3.5.1` backport. Since it's a lot of change, I'm expecting to shake out any remaining issues in the new code throughout the `3.6` release process.
> 
> For the Android editor, I'm planning to put out a `3.6.beta` release either today or in the next few days for users to update and test without having to wait for the full Godot `3.6` release.

:0 omg i am really looking forward to that, thanks for all the hard work

**Pull request merged**
