### PR TITLE
Fixes curious OpenGL crash on macOS

### PR DESCRIPTION
**Pull request by ghost**
This fixes an arcane crash I see on an iMac 5K running macOS 10.13.2 (I spent about 7 hours debugging it).

Every time I open this project, the editor immediately and reliably crashes:

[GodotCrash.zip](https://github.com/godotengine/godot/files/1624395/GodotCrash.zip)

Here's the arcane part: delete any file or alter any file's name, and it won't crash.

Here's the crash log:

[crash.txt](https://github.com/godotengine/godot/files/1624399/crash.txt)

The crash does not happen with Godot 3.0 beta 2. Bisection shows it happens first with a483edbdddd44c4f4f59819591be7177a7d72afc.

For some reason, the `hdr` option's renewed call of `RasterizerStorageGLES3::_render_target_allocate` makes a difference. This PR's `glFinish` seems to have a similar effect and fixes the crash for me.

### CODE REVIEW

**Comment by bruvzg** [comment]
Can't reproduce crash. Godot b90d53a, macOS 10.13.2 (17C205), AMD FirePro D300 2 GB.

**Comment by Melix19** [comment]
Can't reproduce the crash either. iMac 5k 2017, macOS 10.13.2, Godot 702e28f26 (Downloaded from http://godot3builds.digitecnology.com).

**Comment by poke1024** [comment]
This has to be some very ugly timing issue probably coupled with a driver bug on macOS. I'll try if a `glFlush` also does the trick on Monday.

**Comment by poke1024** [comment]
I've changed `glFinish()` to `glFlush()` since this also fixes the crash.

Side note: in my first debugging session, I originally tracked down the problem to the `canvas_item_ubo_data` buffer in `RasterizerCanvasGLES3`. Strangely, still, if I replace `glBufferSubData(GL_UNIFORM_BUFFER, 0, sizeof(CanvasItemUBO), &state.canvas_item_ubo_data);` in `RasterizerCanvasGLES3::reset_canvas` with `glBufferData(GL_UNIFORM_BUFFER, sizeof(CanvasItemUBO), &state.canvas_item_ubo_data, GL_DYNAMIC_DRAW);`, this fixes the crash. Some async driver bug stuff going on here.

**Comment by reduz** [comment]
I wonder if this happens in the GLES2 backend too

**Comment by akien-mga** [comment]
As no other user could reproduce this issue so far, it seems to be a specific driver bug more than a Godot issue.

Closing for now as there doesn't seem to be consensus for merging this workaround. If the crash is still reproducible, it might be worth opening an issue about it to keep track of debugging efforts (and for potential affected users to find it).

**Pull request closed without merging**
