### PR TITLE
Fix `VSlider` grabber area.

### LINKED ISSUE #81168: The VSlider Grabber Area Highlight doesn't go all the way down the slider and extends slightly when the value is changed.
### Godot version

4.1.stable

### System information

Windows 10

### Issue description

When clicked on, the VSlider specifically, not the HSlider, grabber area highlight doesn't go all the way down (0 value) by one pixel, and when sliding it, on certain values, will extend down again then shrink back. 

This behaviour is influenced by the value of step and of center grabber in theme overrides.
The higher step is, the more often this will happen. The higher center grabber is the less.

Since it is only one pixel it is barely noticable on projects with a large window size, mine's resolution is 220 by 150.

When opening a new godot project in compatibility mode, and putting a new VSlider without touching anything the issue happened so you should be able to see it on your end.

PS : It would solve this issue ( and also be nice ) to have the option to disable the highlight when focused function of the control nodes. 

image
image
image

### Steps to reproduce

Open a new godot project and put a VSlider node in the scene then play. It is more noticeable with a small window resolution size.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by WhalesState**
Fixes: https://github.com/godotengine/godot/issues/81168

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
Seems to fix it, but I wonder why HSlider does not need rounding.

**Comment by WhalesState** [comment]
Maybe because the vertical slider uses  `/ 2` for both position.y and size.y, while horizontal slider uses it once for size.x.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
