### PR TITLE
Add bsearch and bsearch_custom to Array

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/godotengine/godot/issues/12558

Pretty self explanatory, I guess. The main question is how to approach the API.

Samples:

```
var a = [1, 10, 50, 100, 120]
a.bsearch(40)
```

```
var a = [1, 10, 40, 40, 40, 50, 100, 120]
a.bsearch(40, false) # bisect from right
```

```
var a = [Vector2(5, 20), Vector2(-5, 30), Vector2(10, 100), Vector2(0, 120)]
a.bsearch_custom(Vector2(100, 50), self, "less_y")
```

The implementation is Python's time-proven `bisect_left` and `bisect_right` (https://hg.python.org/cpython/file/tip/Lib/bisect.py).

Not sure why the docs won't update.

### CODE REVIEW

**Comment by akien-mga** [comment]
Reviewed on IRC and it's good to merge, it just needs a rebase to fix the merge conflict.

**Comment by vnen** [comment]
I find this awesome, but I'm not fond of the naming.

**Comment by akien-mga** [comment]
> To clarify, `bsearch` sounds odd to me. But I noticed that C++ also has this function, so I guess it might be okay, though still strange for those not familiar with the terms.

I agree that for me, `bisect_left` and `bisect_right` would sound more familiar than `bsearch`, but I don't have a strong opinion either way. As long as it's well documented, it should be fine :)
We can always change the API later with a deprecation warning for the old name if it proves unclear to users.

**Comment by HummusSamurai** [comment]
@akien-mga I think bisect-left and -right sounds as if it splits the array in half.

**Pull request merged**
