### PR TITLE
[iOS export] Add support for privacy manifest configuration.

### LINKED ISSUE #90323: iOS NSPrivacyAccessedAPICategorySystemBootTime NSPrivacyAccessedAPICategoryFileTimestamp NSPrivacyAccessedAPICategoryDiskSpace
### Tested versions

4.3-dev5

### System information

Macos

### Issue description

trying to publish iOS version of https://www.jumpyarcade.com
https://play.google.com/store/apps/details?id=com.lonje.jumpjump
https://apps.apple.com/us/app/jumpy-arcade/id6446126962
getting this message after publishing for review
```
ITMS-91053: Missing API declaration - Your app’s code in the “JumpJump” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “JumpJump” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

ITMS-91053: Missing API declaration - Your app’s code in the “JumpJump” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryDiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

Apple Developer Relations
```

please help.

### Steps to reproduce

try to publish at appstoreconnect

### Minimal reproduction project (MRP)

adding empty proj

### PR DESCRIPTION
**Pull request by bruvzg**
Adds export settings to configure iOS privacy manifest.

<details>
  <summary>Click to expand</summary>

Screenshot 2024-04-08 at 08 35 16

</details>

Fixes https://github.com/godotengine/godot/issues/90323

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm a bit concerned about the usability of having to fill all these fields.

Are all those new fields things that users can leave empty as long as they don't make use of those features? How will they realize which fields they need to fill based on Godot's internal usage of some of those APIs?

What's the process like when doing a native iOS app in Xcode? Do devs also need to deal with all this there even for simple apps?

**Comment by bruvzg** [comment]
Collected data is fully about users code, internals do nothing, as for APIs there are default values selected (only boot time api is used for timing, the rest is just exposed to the scripting, so default value is as generic as possible).

But I guess we can make it a bit more complicated and move some calls from the static lib to a separate Obj-C wrapper source file (GDExtension init already does something like this), this way it should be possible to exclude any restricted API calls if nothing is selected.

**Comment by bruvzg** [comment]
> But I guess we can make it a bit more complicated and move some calls from the static lib to a separate Obj-C wrapper source file (GDExtension init already does something like this), this way it should be possible to exclude any restricted API calls if nothing is selected.

On the other hand, it might be more confusing that some functions do not work without something selected in the export settings (file timestamp for example include all `stat` calls, regardless of usage).

**Comment by bruvzg** [comment]
> What's the process like when doing a native iOS app in Xcode?

It's about the same (create privacy manifest and edit it with the plist editor), Xcode interface for the privacy manifest is even less clear than this change.

> Do devs also need to deal with all this there even for simple apps?

Seems like it will be required for apps starting from May.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
