### PR TITLE
OpenSSL: Cleanup and document update process from upstream sources + 1.0.2l

### PR DESCRIPTION
**Pull request by akien-mga**
This PR just documents the update process, tries to remove Godot-made changes in upstream sources (need testing on MSVC!) and gets rid of some unnecessary files.

The changes were based on the same 1.0.2h version as before. The last commit then updates to 1.0.2l.

### CODE REVIEW

**Comment by Ahmed0425** [comment]
Is this related to the build system termination bug?
I mean should it be tested with -j4 parameter on MSVC?

**Comment by akien-mga** [comment]
> Is this related to the build system termination bug?
I mean should it be tested with -j4 parameter on MSVC?

It's not related, no.

**Comment by vnen** [comment]
Can't build with MSVC:

```
thirdparty\openssl\crypto\o_str.c(67): fatal error C1083: Cannot open include file: 'strings.h':
No such file or directory
```

**Comment by akien-mga** [comment]
@vnen Can you try this patch?
```
diff --git a/thirdparty/openssl/openssl/opensslconf.h b/thirdparty/openssl/openssl/opensslconf.h
index 7e9af8062..504c10158 100644
--- a/thirdparty/openssl/openssl/opensslconf.h
+++ b/thirdparty/openssl/openssl/opensslconf.h
@@ -10,6 +10,13 @@ extern "C" {
 // -- GODOT start --
 #if defined(OPENSSL_SYS_WINDOWS)
 # define WIN32_LEAN_AND_MEAN
+// Seems like we have troubles properly using the logic in e_os2.h
+# if defined(_WIN32)
+#  define OPENSSL_SYS_WIN32
+# endif
+# if defined(_WIN64)
+#  define OPENSSL_SYS_WIN64
+# endif
 #endif
 // -- GODOT end --
 
```

**Comment by vnen** [comment]
Still have the same error

**Comment by akien-mga** [comment]
Looks like an upstream typo... Can you try this one?
```
diff --git a/thirdparty/openssl/openssl/opensslconf.h b/thirdparty/openssl/openssl/opensslconf.h
index 7e9af8062..19fad2342 100644
--- a/thirdparty/openssl/openssl/opensslconf.h
+++ b/thirdparty/openssl/openssl/opensslconf.h
@@ -10,6 +10,15 @@ extern "C" {
 // -- GODOT start --
 #if defined(OPENSSL_SYS_WINDOWS)
 # define WIN32_LEAN_AND_MEAN
+// Seems like we have troubles properly using the logic in e_os2.h
+# if defined(_WIN32)
+#  define OPENSSL_SYS_WIN32
+#  define OPENSSL_SYSNAME_WIN32
+# endif
+# if defined(_WIN64)
+#  define OPENSSL_SYS_WIN64
+#  define OPENSSL_SYSNAME_WIN64
+# endif
 #endif
 // -- GODOT end --
 
```

**Comment by vnen** [comment]
Still get the same error (though I have no idea why)

**Comment by akien-mga** [comment]
Just rebased with the fix we discussed on IRC. Also added the commit that updates it to version 1.0.2l (should not introduce issues a priori).

**Comment by vnen** [comment]
For reference, this now builds fine with MSVC.

**Pull request merged**
