### PR TITLE
Clarify documentation for TileSetAtlasSource `texture_region_size`

### PR DESCRIPTION
**Pull request by berarma**

### CODE REVIEW

**Comment by Mickeon** [comment]
I glanced at the code. Frankly, I'm not even sure what that statement in the class reference is useful for, and the explanation in the PR... well, there's none. Would you like to elaborate?

**Comment by berarma** [comment]
The tile set editor uses the tile size of the TileSet by default, thus I guess they can be equal and it makes sense to me. It can also be set to a smaller value but it would be unusual to have smaller tiles than the tile grid size and I don't know if it could cause problems. That's the reason for this proposal. Someone else will know better than me.

**Comment by groud** [comment]
> I glanced at the code. Frankly, I'm not even sure what that statement in the class reference is useful for, and the explanation in the PR... well, there's none. Would you like to elaborate?

Well, the default value for `texture_region_size` is equal to the `tile_size` (and can be increased), so the change is technically right.

**Review by Mickeon — APPROVED** [review]

**Comment by berarma** [comment]
I was only aiming for correctness but if anyone thinks the text could be improved in some other way I could try to give it a go.

**Comment by akien-mga** [comment]
Rebased and squashed the commits, this is now ready to merge.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
