### PR TITLE
Add cross-language script class support and expose the ScriptServer singleton

### LINKED ISSUE #22: Complete, consolidate, and optimize user-defined types in Godot Engine.
**Describe the project you are working on:**

Not Applicable.

**Describe how this feature / enhancement will help your project:**

The engine's codebase splits user-defined types between Custom Types and Script Classes. The newer, superior Script Class system has not yet been fully implemented for all languages and therefore results in things needing to account for both user-defined "named" types. This further complicates any and all type-checking logic in the editor.

For the purposes of cleaning up the codebase and simplifying the implementation of future engine features, I propose that we...

1. Add script class support to VisualScript.
2. Add script class support to CSharpScript.
3. Remove the Custom Type system and all references to it from the codebase.
4. Optimize the slowness of the CreateDialog that occurs when you add too many script classes to your project (as demonstrated in [this gif](https://gfycat.com/miserlypointlessbarb), shared by @HeartoLazor in [this comment](https://github.com/godotengine/godot/pull/27566#issuecomment-488160151)).

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

An interim PR that simply refactored Custom Types to be accessible by name, and which also optimized the CreateDialog can be found [here](https://github.com/godotengine/godot/pull/27566). @HeartoLazor also shared [this gif](https://gfycat.com/wastefulharmlessislandcanary) of the PR correctly optimizing the CreateDialog as needed, although with some other bugs related to autoloads. We would need to fix those bugs and split the work between 4 separate PRs that each introduces one of the features in isolation for testing purposes.

**Describe implementation detail for your proposal (in code), if possible:**

1. **VisualScript script classes:**
    1. Add GUI elements the VisualScript editor for defining an optional "class_name" and "class_icon" for a VisualScript.
    1. Implement `VisualScriptLanguage::get_global_class_name` to extract the values of these properties and return them to the EditorFileSystem for generating script class names.
2. **CSharpScript script classes:**
    - Note: I haven't the foggiest idea how any of this stuff works!
    1. Implement `CSharpScript::get_base_script()`. This is frequently how the editor tracks inheritance hierarchies for scripted types, so I believe this would need to correctly return a Script object that refers to the parent class of the CSharpScript.
    1. Implement a class-level attribute for ClassName and ClassIcon.
    1. Implement `CSharpScriptLanguage::get_global_class_name` to extract the values for this attribute and return them to the EditorFileSystem for generating script class names.
3. **Custom Types removal:**
    1. Find and refactor away all code that references "CustomType" anywhere.
4. **CreateDialog optimization:**
    - The slowness is triggered from attempting to quickly rebuild the entire Tree GUI that renders the inheritance hierarchy of all types that exist AND...
    - When attempting to search for a type by subsequence match, it not only rebuilds the Tree again on every character change in the LineEdit, but it also performs additional inheritance checks on the matching classes against every inherited class of the currently preferred type (on [this line](https://github.com/godotengine/godot/blob/master/editor/create_dialog.cpp#L356)) which only reduces the speed of building the Tree even further.
    - To solve this, one must do the following:
    1. Start rebuilding and caching the inheritance hierarchies used to build the Tree as early as possible, after every script class refresh in the EditorFileSystem.
    1. The first step involves determining which classes should even show up in the Tree, so all of the logic of filtering out classes that happens [here](https://github.com/godotengine/godot/blob/master/editor/create_dialog.cpp#L333) can also be moved elsewhere to be processed ASAP rather than on every Tree rendering.
    1. The code for [handling Custom Types](https://github.com/godotengine/godot/blob/master/editor/create_dialog.cpp#L370) can be stripped out.
    1. The re-occurring ternary `if cpp_type do ClassDB else do EditorData::script_class stuff` logic should be refactored to dedicated EditorData methods, such as in [this existing "export Resources" PR](https://github.com/godotengine/godot/pull/26162/files#diff-a8f630717e57fce152a8ea5fbb326d99R856)

I believe the problem is figuring out WHEN to actually execute these CreateDialog caching operations without triggering problems in other parts of the editor since I *suspect* that is the reason for the autoload issues that @HeartoLazor mentions in [his comment](https://github.com/godotengine/godot/pull/27566#issuecomment-488160151) (linking again for convenience).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Uhh....no.

**Is there a reason why this should be core and not an add-on in the asset library?:**

It involves extensive changes to multiple scripting languages and editor classes that already exist in the main repository. An addon cannot provide the necessary alterations.

### PR DESCRIPTION
**Pull request by willnationsdev**
This is a pull request to close godotengine/godot-proposals#22. (Edited 12/27/2020)

Note that, at time of editing, the master branch with mono isn't building properly. I have a branch that is building on Windows 10 from an earlier commit with the same set of changes so that this PR can be tested, along with a test project. You can find the branch at https://github.com/willnationsdev/godot/tree/P22/script-classes-2.

[Demo_GP22.zip](https://github.com/godotengine/godot/files/5745011/Demo_GP22.zip)

Things that it includes...

1. Add some utility methods to ScriptServer.
2. Refactors some class icon variable names for consistency + consolidates getting global class names for EditorFileSystem.
3. Exposes ScriptServer as an engine singleton for scripting. Global scripts become generated properties so that NativeScript/C#/etc. can access them by name with `.get(name)` without requiring global variables like GDScript does.
4. Add VisualScript support for script class names and icons.
5. Add VisualScript graph node to fetch a reference to a global class's script.
6. Add C# support for script class names and icons using a `[Global]` attribute.
    - Note, this was rather complicated. Script class metadata is gathered at the time the file is modified during EditorFileSystem scans, but the script class metadata on C# scripts isn't actually generated until the script is *built*. This means I had to...
        1. Do a post-update for individually recompiled files to update their file cache info in the EditorFileSystem
        2. Add a cache for the script class icon on these files to import from the `project.godot` file and use that version of the script metadata *until* the file is recompiled, at which point, it starts to defer to the runtime data from the script. Otherwise, the engine would start up and perceive that the C# class didn't exist until you recompiled it again.
        3. This script metadata caching is only performed on languages which override a new ScriptLanguage method `has_delayed_script_class_metadata()` and return `true` from it. Currently, C# is the only one, but future compiled languages would also need to do this. Not applicable to NativeScript since the metadata is stored on the `.gdns` resource and is updated immediately when the file is modified.
 7. Remove most CustomType-related stuff from the engine. They have now been effectively replaced by Script Classes, aka Global Classes, so there isn't much need for them to exist. IF you think of any other features that need to be reproduced, let me know and I'll implement it.
 8. Change the Scene dock to treat script classes like CustomTypes.
     1. If you have a script class on a node, it will now display an `extends` button where the add script button used to be. This will immediately attempt to create a script that extends the script class by name.
     2. By right-clicking and choosing to remove the script, it should block you from removing the script class.
     3. If you have a derived script inheriting a script class, then attempting to remove it should just restore the script class.
         - Note that this only works for languages that properly implement `get_base_script()`. For now, nothing does.  VisualScript/NativeScript/C# never had it to begin with and GDScript 2.0 doesn't set its `_base` correctly anymore - see #44186.

Special thanks to @aaronfranke, @neikeq, and @fire for consultations over the last several months.

### CODE REVIEW

**Comment by willnationsdev** [comment]
cc @neikeq If you eventually can find the time, I'd like to hear your thoughts on what I might be doing wrong to get the C# attribute detected.

**Comment by neikeq** [comment]
I'm absent for 3 days due to house reforms so I can't check yet.
What part is failing? Is it `has_attribute`?

**Comment by willnationsdev** [comment]
@neikeq Yes, that is correct. `has_attribute` keeps returning false.

**Comment by opl-** [comment]
I started looking at this issue yesterday and I think it's time to share my findings. I'd like to note that I rebased your branch onto master, so it's possible that I got some fix from there (`git rebase master`, where `master` was 9e34ba4855). I'd also like to note that I'm on Debian, in case that somehow fixed some issues.

You can take a look at my fork (which currently includes a bunch of debug logging) [here](https://github.com/opl-/godot/commits/P22/script-classes). The notable changes are:

-  the addition of `script_base_class_name` to `CSharpScript` to allow displaying the C# classes correctly in the "Create New Node" dialog.

- A poorly implemented way to correctly filter `Resource` types in the inspector (`return 2` from `CSharpScript::_try_get_member_export_hint`).

- A lot of `FIXME` and `TODO` comments.

---

`has_attribute` is correctly returning `true` for classes that had it. I'm not sure why it's not working for you. One thing I found is that for `script_class_name` etc to be updated from the assembly data, it can't already be cached by `editor_file_system.cpp`. I think this might be due to the script modification timestamp not being changed between Godot restarts. Manually deleting the `filesystem_cache6` file forced those to be updated.

I managed to get both nodes and resources to be displayed in the editor (in the "Create New Node" dialog and the editor inspector respectively). That said, this still isn't without issues:

1. Any new C# classes do not get registered in the editor until its fully restarted. I have no idea how those are supposed to be triggered. (That said, updates to exports do happen!)

2. Resource filtering isn't working and `CSharpScript` doesn't have proper caching for already initialized scripts, making it impossible to implement resource type hints that are both efficient and safe.

3. The editor likes throwing errors from the `ClassDB` (see below) due to my test resource implemented in C# not being found in it. I assume this is the correct behavior from `ClassDB`, as it seems to be for native Godot types, whereas `ScriptServer` should be the one holding references to non-native types. That said, this is still something that should be looked into. I believe it happens when interacting with the inspector.

```
ERROR: Cannot get class 'TestResource'.
   at: get_parent_class (core/class_db.cpp:322)
```

4. There's a lack of inheritance support in `CSharpScript`, making it pretty difficult to determine a script's base class if it's not a native one. I tried to work around this in my fork by adding `script_base_class_name` to `CSharpScript` together with a very naive way of setting it. It simply grabs the name of the base type (or the native type, see point 3 below) without checking if it's registered as a global type, which might lead to exceptions.

---

As a side-note and technically unrelated to this issue, the `CSharpScript` class is a mess:

1. There's some code repetition that made it difficult to figure out how things work (what is the difference between `static CSharpScript::initialize_for_managed_type` and `CSharpScript::reload`? Can't one of them call the other to prevent having two sections of code doing the same job?).

2. `CSharpScript::update_exports` gets called every time I click on any `Resource` type property in the inspector, despite the fact it should be cached after the first call until the script is changed.

3. Why is `base` not set if `native` is the same as the `base? ([one](https://github.com/godotengine/godot/blob/c853dd5ddba79620177614f273ce4d08664a3bf4/modules/mono/csharp_script.cpp#L2996), [two](https://github.com/godotengine/godot/blob/c853dd5ddba79620177614f273ce4d08664a3bf4/modules/mono/csharp_script.cpp#L3363))

**Comment by willnationsdev** [comment]
I've updated the original post with the latest changes. This PR should now have all of the general changes I expect to be making to the engine with it. When it gets fixed up to satisfy the various builds from GitHub Actions, and when everyone is satisfied with each commit, I can merge it all into one.

**Comment by reduz** [comment]
We are changing some of this logic with @vnen for upcoming GDNative, the idea is to do something similar so you can (optionally) reference scripts by global class name rather than resource. Haven't reached that point yet, but will let you know when we do and what we plan to do.

**Comment by willnationsdev** [comment]
@reduz Gotcha. Well, I'll just update it as needed whenever you guys have those changes ready. Thanks.

**Comment by reduz** [comment]
Alright, we will probably do some core changes, but your work on the usability side can be discussed and merged afterwards.

**Comment by willnationsdev** [comment]
@reduz Also, note that the feature to export user-defined resources was also tied to script class support, so my PR for that, which was going to be based on top of this one, will likely need to be modified to reflect your core changes as well.

**Comment by touilleMan** [comment]
Hi, just a small feedback: the `has_delayed_script_class_metadata` method should be exposed by PluginScript.

As a general rule of thumb, every new method added to the `ScriptLanguage` class should be exposed by PluginScript (given it role is to allow 3rd party module to declare additional `ScriptLanguage` :smile: )

btw @vnen as GDNative maintainer you can feel free to @ me if you need any help with this ;-)

**Comment by willnationsdev** [comment]
@touilleMan 

From what I can tell, that means that I just need to add a `godot_bool` to the `godot_pluginscript_language_desc`, and then define an implementation for it in the PluginScriptLanguage class just like `has_named_classes`, `supports_builtin_mode`, and `can_inherit_from_file`? Is there anything else that should be done to make it compatible?

**Comment by willnationsdev** [comment]
@touilleMan Done. Let me know if there's anything else you see that needs changing.

**Comment by touilleMan** [comment]
@willnationsdev seems pretty good to me ;-)

**Comment by willnationsdev** [comment]
Superceded by #48201 so closing.

**Pull request closed without merging**
