### PR TITLE
Signal arity warning [#12450]

### PR DESCRIPTION
**Pull request by jordgubben**
Adds a warning in the Connections dialogue when the number of arguments of a signal and the number of arguments on a connected method do not match up.

This solves, or at least alleviates, the problems described in  #12450.

It is a draft because there is still some optimazions/refactorings/tweaks to be explore. This is my first PR to the Godot project and I welcome early feedback.

### CODE REVIEW

**Comment by reduz** [comment]
I am planning in doing a big rewrite of these connection warnings, so may use this as reference I guess

**Comment by jordgubben** [comment]
Oh, snap. And I was hoping to forever embroider my name into the eternal weave of holy Godot. Still, if it's of help to the noble cause then it's of help to the noble cause. ;) 

I also have a small re-factoring. It might also be helpful; I'll submit it to.

**Comment by vnen** [comment]
This is cool but needs to be adapted to the new connections dialog.

**Comment by aaronfranke** [comment]
@jordgubben Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by jordgubben** [comment]
I got the impression from reduz that the whole module was going to be rewritten (see above). 
If not then I think this may still be a relevant fix.

**Comment by vnen** [comment]
I believe the idea was just to rewrite the connections dialog, which was already done.

**Comment by aaronfranke** [comment]
This PR has not received any new commits for over a year, closing. It can be re-opened or re-created if it is rebased and updated to work with the latest master.

**Pull request closed without merging**
