### PR TITLE
Add code-oss, vscode-oss, and visual-studio-code-oss to vscode path

### PR DESCRIPTION
**Pull request by TritiatedWater**
Continuation of https://github.com/godotengine/godot/pull/24622. CC @neikeq

### CODE REVIEW

**Comment by neikeq** [comment]
We are duplicating too much lines at this point. Can we make it an array we loop through?

**Comment by Supatier** [comment]
Something like this?
```CPP
if (vscode_path.empty() || !FileAccess::exists(vscode_path)) {
	static List<String> vscode_name;
	vscode_name.push_back("code");
	vscode_name.push_back("code-oss");
	vscode_name.push_back("vscode");
	vscode_name.push_back("vscode-oss");
	vscode_name.push_back("visual-studio-code");
	vscode_name.push_back("visual-studio-code-oss");
	// Try to search it again if it wasn't found last time or if it was removed from its location
	for (int i = 0; i < vscode_name.size(); i++) {
		vscode_path = path_which(vscode_name[i]);
		if (!vscode_path.empty() || FileAccess::exists(vscode_path))
			break;
		}
	}
}
```

**Comment by neikeq** [comment]
Yes, that's good.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
