### PR TITLE
Fix `draw_multiline_colors()` for `width < 0`

### PR DESCRIPTION
**Pull request by dalexeev**
* Fix `draw_multiline_colors()` always draws white lines when `width < 0`.
* Expose `canvas_item_add_multiline()` for consistency.
* And a couple of other minor fixes.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thank you!

**Comment by Calinou** [comment]
I noticed this wasn't cherry-picked, is that intended? If this PR is to cherry-picked, remember to also cherry-pick https://github.com/godotengine/godot/pull/76989.

**Comment by clayjohn** [comment]
I don't think we should cherrypick this due to the change in behaviour. While it is minor and it is more correct (so I wouldn't call it compat breaking), it still may surprise users.

**Pull request merged**
