### PR TITLE
WIP: Readd support for comma decimal separator in editor

### LINKED ISSUE #24531: Inspector no longer interprets Comma as decimal point in editor
**Godot version:**
3.1-alpha (2 and 3, didnt test alpha1)

**OS/device including version:**
Windows 10, non-english keyboard

**Issue description:**

Regression of issue #6028 in godot 3.1 alpha. Original issue fixed by PR #13240

In GODOT 3.0 editor you can use "," as decimal separator:

insert_with_comma_godot305
(comma is simply replaced by dot)

In GODOT 3.1-alpha (2 and 3, didnt test 1) everything after comma is trimmed:
insert_with_comma_godot31_alpha

**Steps to reproduce:**

Same as in issue #6028

1) In editor, write "1.1" to any float box (like "rotation degrees" on Node2D) - rotation is set to "1.1"
2) In editor, write "1,1" to any float box (like "rotation degrees" on Node2D) - rotation is set to "1"

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #24531, re-implements #6028 in new property editor.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
So, how would you do `pow(2, 3)` now? :smiley:

**Comment by akien-mga** [comment]
> So, how would you do `pow(2, 3)` now? smiley

Hm, didn't think about that. Should we make it optional, or just drop support for using comma as decimal separator in `EditorSpinSlider`?

**Comment by vinterskog** [comment]
Would be really disappointing not to be able to use comma in decimal values in GUI widgets anymore to be honest. There's parts of the world where that's just how it's done, you know? ;)
In fact, I did notice the regression immediately and found it instantly annoying.

**Comment by thomasruiz** [comment]
@akien-mga You need to change 2 things around [here](https://github.com/godotengine/godot/blob/master/core/math/expression.cpp#L1035-L1058) instead, I think. I don't know if that doesn't have a side effect somewhere though.

**Comment by bojidar-bg** [comment]
Well, it won't work with `pow(2,3)` then (as it will parse as one number), but I'm mostly fine with this.

**Comment by eon-s** [comment]
I prefer this optional, even if my local system uses comma, using dot is less confusing, is consistent with programming languages and allows to use things like the expressions mentioned before.

**Comment by thomasruiz** [comment]
It's probably a bad idea anyway, the `pow` problem that @bojidar-bg mentioned would make things tricky. It's a safer bet to allow only one decimal character, for consistency.

**Comment by akien-mga** [comment]
Given that it would break using commas for builtin methods like `pow`, I think it's better not to merge this.

IINM, the only reason why some users may *really* want this is because some keyboard layouts have a "comma" key in place of the "dot" key in the numpad (`KEY_KP_PERIOD` in Godot). I know at least German and Danish keyboard layouts do that. English US and French have a dot key in the numpad, like most other keyboard layouts I suppose (even though French uses comma as decimal separator).

So maybe instead of replacing commas by dots in the input text, we could catch `KEY_KP_PERIOD` and force it to input a dot in the evaluator widget? (I just checked with `setxkbmap de` and pressing the "comma" key on the numpad does trigger a `KEY_KP_PERIOD` event.)

**Comment by vinterskog** [comment]
Sounds like a good compromise. And yes, the numpad really is the issue here (for me at least).

**Comment by akien-mga** [comment]
> I just checked with `setxkbmap de` and pressing the "comma" key on the numpad does trigger a `KEY_KP_PERIOD` event.

Actually I was wrong, it currently reports "0" as scancode on X11. It's actually a `XK_KP_Separator` event which we currently ignore: https://github.com/godotengine/godot/blob/master/platform/x11/key_mapping_x11.cpp#L95
I checked Windows and macOS and we also ignore the similar event there.

So supporting detection of a keypress of this numpad comma will require some more work. I had a quick go at it, but it's too late for 3.1 so I'll look at it again later.

**Comment by splite** [comment]
> IINM, the only reason why some users may _really_ want this is because some keyboard layouts have a "comma" key in place of the "dot" key in the numpad (`KEY_KP_PERIOD` in Godot). I know at least German and Danish keyboard layouts do that. English US and French have a dot key in the numpad, like most other keyboard layouts I suppose (even though French uses comma as decimal separator).

French have comma too: https://brilliantmaps.com/decimals/


What about something simple like `if not textbox contains non-digit character with exception of dot/comma, then replace else nothing`?

or even better try to replace and check if its float? (i dont do c++, but pseudo code is`if(float.tryparse(input.replace)) then replace else nothing`)

**Comment by akien-mga** [comment]
> France have comma too: https://brilliantmaps.com/decimals/

Not on numpad. http://www.ibt.ca/v2/items/btc5121w/images/azerty_1.jpg
I have a French Azerty keyboard and can confirm that. Actually the actual non-numpad dot is so hard to reach (<kbd>Shift</kbd>+<kbd>;</kbd>) on French Azerty keyboard that many users use the numpad one for their punctuation needs.

> What about something simple like `if not textbox contains non-digit character with exception of dot/comma, then replace else nothing`?

That would start becoming quite involved if we need to parse the input strings all the time to check that, and that's also pretty random from an end user perspective.

> or even better try to replace and check if its float? (i dont do c++, but pseudo code is `if(float.tryparse(input.replace)) then replace else nothing`)

That would break on `pow(2,3)`.

**Comment by splite** [comment]
Umm... Never heard about azerty, but It should not really matter what is printed on keyboard (i have dot on mine, too), what matter is your setting in system (i write comma every time i hit that numpad button, look: ",,," 🤣  )

I can go to Windows Setting (https://resrequest.helpspot.com/index.php?pg=kb.page&id=279) and change what is printed after i hit "dot on numpad". I really dont want to do that only for godot, becouse it break every other app i am using.


> > or even better try to replace and check if its float? (i dont do c++, but pseudo code is `if(float.tryparse(input.replace)) then replace else nothing`)
> 
> That would break on `pow(2,3)`.

Actually thats the point 😄 I dont know c++, but in c# i would write it as

    // this is NOT c++ code!!!! Dont copy paste it in godot!!!
    TryReplace("pow(2,3)"); // return "pow(2,3)"
    TryReplace("2,3"); // returns "2.3"
    TryReplace("2.3");  // returns "2.3" too
    
    // this is NOT c++ code!!!! Dont copy paste it in godot!!!
    public string TryReplace(string input)
    {
      float tmp;
      if(float.TryParse(input.Replace(",", "."), out tmp))
      {
        return input.Replace(",", ".");
      }
      return input;
    }

**Comment by splite** [comment]
Let me say it this way:

Doesnt matter what keyboard layout you have (qwertz, qwerty, azerty, chinese) - what matter is you `CurrentCulture` windows setting.

We can swap your fancy keyboard for my cheap and dirty one and your keyboard will write comma on my desktop and my keyboard will write dot on your desktop.

**Pull request closed without merging**
