### PR TITLE
Allow plugins to not have an init script

### LINKED ISSUE #29356: Allow plugins to not have init scripts
**Godot version:** 3.1.1 and master

**Issue description:** With [Godot plugins](https://docs.godotengine.org/en/3.1/tutorials/plugins/editor/making_plugins.html), you are normally expected to define a script to initialize the plugin, and have this line in `plugin.cfg` to call it:

    script="mycoolthing_plugin.gd"

Yet sometimes, you don't need to do anything in the script to initialize the plugin. 

* If you remove the line, Godot gives you a warning about the plugin not containing a script. 
* If you change the line to `script=""`, Godot fails to load the plugin with an error that it can't find the script at the plugin's path.

Proposal: `script=""` should be interpreted as having no script, and show no warning.

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes https://github.com/godotengine/godot/issues/29356, it seems to work perfectly in my testing.

Most of the diffs are indentation changes, it's mostly just adding an if statement, but I also renamed "path" to "script_path", and added some comments.

### CODE REVIEW

**Comment by akien-mga** [comment]
Code seems OK, but I still don't really understand what would be the use case for plugins that don't have script. The whole point of plugins is to use the EditorPlugin API, and if no script is registered, EditorPlugin doesn't do anything (all its behavior depends on the script extending its virtual methods).

The example you gave in #29356 ( https://github.com/aaronfranke/GodotExtraMath ) doesn't have to be a plugin, it's simply be an asset that can be downloaded and used right away. There's no enabled/disabled logic that the plugin system would make use of.

**Comment by aaronfranke** [comment]
Try adding this plugin to a project: [addons.zip](https://github.com/godotengine/godot/files/3512292/addons.zip)

I've set the config to `script=""` but enabling/disabling still changes behavior because of `class_name`.

With regards to the first example I gave of ExtraMath, I want it to be a plugin so that I could add functionality in the future if I wanted to, but I don't need any right now.

**Comment by akien-mga** [comment]
> Try adding this plugin to a project: [addons.zip](https://github.com/godotengine/godot/files/3512292/addons.zip) I've set the config to `script=""` but enabling/disabling still changes behavior because of `class_name`.

Alright, with `class_name` there is *some* use case for a plugin without a plugin script, but even then it's not doing what you what to use it for. Enabling/disabling the plugin (after adding a dummy plugin script for it) only impacts what appears in the Add Node dialog. Even if the plugin is disabled, `Node25D` is still registered as a global class and I can extend it and use its API.
It seems like there's logic to exclude `res://addons/*` scripts unless their matching plugin is enabled, but it's not very thorough.

Still, I guess it makes sense to have a way to make some code opt-out, and using a plugin for that seems relevant, so let's merge.

**Comment by akien-mga** [comment]
Thanks!

**Comment by willnationsdev** [comment]
@akien-mga the tidbit of code that filters out script classes based on the plugin state is in CreateDialog. It does not check that in GDScriptLanguage::init, nor is there any centralized location tracking global variables. However, you might be able to have the EditorFileSystem's scanning process clear out script classes from the ScriptServer if they are in disabled `res://addons/*` directories.

**Comment by Xrayez** [comment]
> you might be able to have the EditorFileSystem's scanning process clear out script classes from the ScriptServer if they are in disabled res://addons/* directories.

Something tells similar process could be applied to solve #28232.

**Pull request merged**
