### PR TITLE
Moved mono module here

### PR DESCRIPTION
**Pull request by neikeq**
The [GodotSharp](https://github.com/neikeq/GodotSharp) repository will be abandoned and the development will continue here. I'll check all the issues open there and move here those that are still valid (we will need a mono label).

Building steps: https://github.com/neikeq/GodotSharp/wiki/Building
Demos will be added [to this repository](https://github.com/neikeq/GodotSharpDemos). Right now, the only demo in there is outdated and won't work.
There is also [this old document](https://github.com/neikeq/GodotSharp/wiki/API-Differences) that lists some of the differences with GDScript. It's very old and it will be updated once I finish re-witing/updating the bindings of the built-in types.

In general, many things will need to be documented. Please, review (alpha2 is around the corner), comment any doubt you could have and give feedback (specially related to Godot coding standards I may have broken).

I must note that there were [a few contributors](https://github.com/neikeq/GodotSharp/graphs/contributors), but it's not possible to use the commits from that repository (let me know If you know a way) and it was squashed into a single commit.

Travis will be failing for now, it's normal.

### CODE REVIEW

**Comment by neikeq** [comment]
Does this PR count as four? Winter is coming and I'm short on shirts.

**Comment by mrcdk** [comment]
The compilation will fail on msvc because it's not using latest master and is broken.
I've rebased to latest master locally and I get this error:
```
[ 99%] scons: *** [bin\GodotSharpTools.dll] Source `modules\mono\editor\GodotSharpTools\GodotSharpTools.sln' not found, needed by target `bin\GodotSharpTools.dll'.
```
Which is true, the file is in [here](https://github.com/neikeq/GodotSharp/tree/master/mono/editor/GodotSharpTools) though.

After adding it it compiles.

**Comment by tagcup** [comment]
Not sure if it's supposed to work eventually but it currently doesn't cross-compile with mingw on linux:

```
scons: Reading SConscript files ...
NameError: global name 'WindowsError' is not defined:
  File "/home/user/godot/SConstruct", line 369:
    config.configure(env)
  File "./modules/mono/config.py", line 51:
    mono_root = monoreg.find_mono_root_dir()
  File "modules/mono/mono_reg_utils.py", line 39:
    dir = _find_mono_in_reg(r'SOFTWARE\Mono')
  File "modules/mono/mono_reg_utils.py", line 24:
    except (WindowsError, EnvironmentError) as e:
```

**Comment by neikeq** [comment]
Rebased to latest master, added the missing .sln that was ignored by .gitignore and fixed the cross-compile error (just that one, maybe there are more).

**Comment by tagcup** [comment]
Yeah, it now gives

```
scons: Reading SConscript files ...
UnboundLocalError: local variable 'mono_root' referenced before assignment:
  File "/home/user/godot/SConstruct", line 369:
    config.configure(env)
  File "./modules/mono/config.py", line 53:
    if not mono_root:
```

**Comment by neikeq** [comment]
You will have to use the environment variables to locate the library when cross-compiling.
That condition should be `!= None` though.

**Comment by groud** [comment]
Was moving mono here discussed ? I though the current philosophy was to move all "unecessary to everyone" libraries to other repositories. I've got not problem considering it as an official (thus in the godotengine organization repositories list) and maintained library but not sure everyone will need it :)

**Comment by reduz** [comment]
Mono is huge, the module will need to be changed to not compiled by
defaut.. its just there is no support for that currently, need to be added,
As mono actually does support for compiling for all our target platforms,
it should not be needed to be bundled.

**Comment by reduz** [comment]
I added to config.py the optional function:

def is_enabled():

so you can add it to the mono module and return False by default. This will
make the module not build for most people pulling Godot.

**Comment by reduz** [comment]
In any case, the proper way to build this would be to, in the can_build()
option, you detect the platform and try to see if the right environment
variables or means to build are present, then return True or False
depending on whether build can happen or not.

This disables the module automatically.

**Comment by tagcup** [comment]
> You will have to use the environment variables to locate the library when cross-compiling.

Which environment variables? Sorry I'm totally clueless about Mono/C#

**Comment by mrcdk** [comment]
I didn't have much success running it. Windows 10 x64 MSVC 2015

Everything is compiled correctly but the C# code isn't running 😢 


I've tried printing with `GD.print()` , rebuilding everything from scratch, creating a new godot project,... But nothing happens.

**Comment by neikeq** [comment]
@groud Yes. In fact, the discussion during last week could be summarized as _"mono PR when?"_.

@reduz Not sure about `can_build`. I would like build to fail if the user decides to build with mono (`module_mono_enabled=no`) but for some reason it's not possible, instead of continuing silently without the module.

@mrcdk That should work. Could you upload an example project?

**Comment by mrcdk** [comment]
@neikeq Here you have, it's just a sprite with a script attached that should print something

[test_cs_2.zip](https://github.com/godotengine/godot/files/1347361/test_cs_2.zip)

**Comment by neikeq** [comment]
@mrcdk Oops, didn't notice this in your image. The script name must match the class name, and it's case sensitive. This will print a warning in the future, but right now the node warning API does not allow it...

@tagcup The environment variables are mentioned [in the build steps](https://github.com/neikeq/GodotSharp/wiki/Building#environment-variables). They must point to a directory that contains the `bin`, `include` and `lib` folders. An example would `C:\\Program Files\Mono` on Windows or `/usr` on Linux (supposing mono is installed in these locations). If you are cross-compiling, you will probably have to [cross-compile mono](http://www.mono-project.com/docs/compiling-mono/windows/cross-compiling-mono-for-windows/) as well for the target platform.

**Comment by kubecz3k** [comment]
@groud decision to make mono a core part of Godot was made long time ago, before works on mono module even were started for good.

**Comment by tagcup** [comment]
Ah OK, you first need a copy of mono compiled for windows somewhere and point to that via environment variables to make it work. Which makes sense since the module doesn't compile mono itself.

**Comment by reduz** [comment]
:tada: :tada: :champagne: :balloon:

**Comment by NathanWarden** [comment]
Woo hoo!

**Pull request merged**
