### PR TITLE
Improve input handling on Android

### PR DESCRIPTION
**Pull request by endragor**
- Dispatch input immediately as it comes, instead of delaying it to the
   next step().

 - Fix text box input handling when caret is at the middle of the text.

 - Minimize queueEvent calls on Java side.

### CODE REVIEW

**Comment by reduz** [comment]
As far as I know, this wont work because the game runs on the OpenGL thread while the input comes from the main thread... so the queue was for thread sync.

Unless this at some point changed. Maybe @RandomShaper or @volzhs knows.

**Comment by endragor** [comment]
I changed that as a part of #10422. Now calls from Java come on the OpenGL thread and Godot also  considers it to be the main thread.

**Comment by volzhs** [comment]
I assume that you tested this on real devices.
what kind of devices did you test this?

**Comment by endragor** [comment]
This PR was tested on Samsung Galaxy G6. #10422 was tested on Samsung Galaxy S6, Sony Xperia E5, Meizu M2 Note.

**Comment by volzhs** [comment]
@akien-mga seems ok to me :)

**Comment by reduz** [comment]
Ok, this also makes sense to me. Feel free to merge.

**Comment by volzhs** [comment]
would this fix #11664? i'm not sure. i will test after this merged.

**Comment by endragor** [comment]
Yes, it fixes that, too.

**Comment by volzhs** [comment]
@endragor @akien-mga wow. that's good news.

**Comment by volzhs** [comment]
it had many issues for 1 commit after all.
can't revert back partially about the **"Dispatch input immediately as it comes, instead of delaying it to the
next step()."**

**Comment by endragor** [comment]
I only see one issue that this caused (#11798) - could you please clarify regarding "many issues"? We are developing an Android game and input works fine there, beside the mentioned #11798.

**Comment by volzhs** [comment]
I mean that one commit fixes many issues.
I think i wrote wrongly in english. i'm sorry if my comment made some misunderstanding.

**Pull request merged**
