### PR TITLE
[3.2] Avoid signal methods in ColorPicker to access the tree when it isn't in the tree

### LINKED ISSUE #46098: Executing `ColorPicker.new()._screen_input(InputEventMouseMotion.new())` crashes Godot
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
ColorPicker.new()._screen_input(InputEventMouseMotion.new())
```

crashes with backtrace
```
ERROR: get_tree: Condition "!data.tree" is true. Returned: __null
   At: ./scene/main/node.h:280.
scene/gui/color_picker.cpp:591:37: runtime error: member call on null pointer of type 'struct SceneTree'
scene/gui/color_picker.cpp:591:37: runtime error: member access within null pointer of type 'struct SceneTree'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x16f757a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fc47d380210] (??:0)
[3] ColorPicker::_screen_input(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/gui/color_picker.cpp:591 (discriminator 1))
[4] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/mnt/Miecz/godot3.2/core/variant_call.cpp:1129 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript_function.cpp:1089)
[8] GDScriptInstance::_ml_call_reversed(GDScript*, StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1269)
[9] GDScriptInstance::call_multilevel_reversed(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/modules/gdscript/gdscript.cpp:1278)
[10] Node::_notification(int) (/mnt/Miecz/godot3.2/scene/main/node.cpp:152)
[11] Node::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot3.2/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/mnt/Miecz/godot3.2/core/object.cpp:931)
[15] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:197)
[16] Node::_propagate_ready() (/mnt/Miecz/godot3.2/scene/main/node.cpp:186 (discriminator 2))
[17] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot3.2/scene/main/node.cpp:2560)
[18] SceneTree::init() (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:464)
[19] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3628)
[20] godots(main+0x331) [0x16ee467] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fc47d3610b3] (??:0)
[22] godots(_start+0x2e) [0x16ee07e] (??:?)
```

### PR DESCRIPTION
**Pull request by gongpha**
Fixes #46098.

### CODE REVIEW

**Comment by akien-mga** [comment]
Is the issue not relevant for the `master` branch?

**Comment by gongpha** [comment]
@akien-mga Yes, In the `master` branch, these methods are inaccessible in GDScript.

**Comment by akien-mga** [comment]
But they could still crash when called at the wrong time from C++ no? So adding the sanity checks would be good there too.

**Comment by gongpha** [comment]
IMO, I think no one (C++ devs) plays by calling these signal methods. If so, they will notice that isn't allowed.

But at that moment, Crashing is one of my violent problems. I agreed with your feedback to add these to the `master` branch. For mistake checking. If they don't know really how those methods do. (^_^ ๐)

@akien-mga So, Should this PR need to be closed ? If I will restart to commit these changes on the `master` branch.

**Comment by akien-mga** [comment]
We can keep this PR for `3.2`, but you can open another one for `master` to also have the check there. I agree with you that it's much less important there, but it doesn't cost much and it's always good practice to validate pointers before dereferencing them.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
