### PR TITLE
[3.x] Fix broken links in Class Reference

### PR DESCRIPTION
**Pull request by timothyqiu**
`tutorials/gui` changed to `tutorials/ui`.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
There's more if you're interested, basically every `classes/class_*.rst` change from https://github.com/godotengine/godot-docs/pull/5412 needs to be applied here.

**Comment by timothyqiu** [comment]
Wow, that's huge. I'll check that and put them in this PR :factory_worker:

**Comment by timothyqiu** [comment]
Done. Also fixed a link title as the page's title has also been changed. ("Scenes and nodes" -> "Nodes and Scenes")

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Pull request merged**
