### PR TITLE
Alternative to PanoramaSkyMaterial for dynamic panorama generation with GLSL

### PR DESCRIPTION
**Pull request by pkpro**
### Why

- It is too expensive to use PhysicalSkyMaterial and to generate volumetric clouds
- Dynamic panorama generation with GLSL compute shaders  might be faster (with Forward+ render) and discrete GPUs then fragment shaders
- Sky and planetary surface are not changing as rapidly (at least in a distance), you do not need to generate them every frame however the static panoramas are not fit for each type of game
- Right now if you want to generate a panorama with GLSL compute shader, then you will need to copy output of a compute shader to system memory and then back to GPU by creating Texture2D object and assigning it to the sky_material (source_panorama sampler2D). On my AMD Ryzen 7 5800X 4.2GHz it takes ~100ms, and at the same time the simple panorama generation (from attached example) takes likes 0.015 -  0.022ms.

### How

The groundwork for this is already done by @BastiaanOlij in #79288
What is missing is the possibility to set the panorama like this:
`
panorama_rid=RenderingServer.texture_rd_create(compute_texture_rid)
$WorldEnvironment.environment.sky.sky_material.set_panorama(panorama_rid)
`

This RP introduces a PanoramaCommonSkyMaterial class that will serve as the base class for both old PanoramaSkyMaterial and new ComputePanoramaSkyMaterial (this class name might be misleading though, please give me some suggestions here). Common members and methods for old and the new class  are moved to PanoramaCommonSkyMaterial. The change itself is small, but it saves a lot of compute time.

ComputePanoramaSkyMaterial expects the panorama in 2:1 aspect ratio same as PanoramaSkyMaterial and provides the editor and script methods to get the required panorama size and to set the panorama scale (based on width of the panorama) limited to 8k, 4k, 2k, 1k. 

Here is the example project:
[ComputePanoramaSkyMaterial.zip](https://github.com/godotengine/godot/files/12245313/ComputePanoramaSkyMaterial.zip)

### Bugs

Error messages at start:

ERROR: Class PanoramaSkyCommonMaterial already has a method set_filtering_enabled.
   at: bind_methodfi (core/object/class_db.cpp:1416)

ERROR: Class PanoramaSkyCommonMaterial already has a method is_filtering_enabled.
   at: bind_methodfi (core/object/class_db.cpp:1416)

These errors are here because get/set filter bindings are in both the PanoramaSkyMaterial and ComputePanoramaSkyMaterial and I didn't figured out how to fix it without removing PanoramaSkyCommonMaterial.

### Disclaimer

This is my first PR, I'm looking forward for advise on the code and be able to allocate time in the next two weeks to fix related issues.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Why aren't you using the new `Texture2DRD` class so you can use the texture created by your compute shader in the normal panoramic sky material?

**Comment by pkpro** [comment]
> Why aren't you using the new `Texture2DRD` class so you can use the texture created by your compute shader in the normal panoramic sky material?

Because I missed it existence and I'm not sure how to use it at first glance on documentation.  Can you give a short example? If this class does what I need then I can simply close this PR.

**Comment by pkpro** [comment]
Ok, it looks i figured it out:

`    # instead:
       # panorama_rid=RenderingServer.texture_rd_create(compute_texture_rid)
       # use Texture2DRD
       
        var tex:=Texture2DRD.new()
	tex.set_texture_rd_rid(compute_texture_rid)	
	env.sky.sky_material.panorama=tex
`

It works fine, though I'm getting errors at some point (probably first time i set it):

`
  scene/resources/texture_rd.cpp:78 - Condition "!RD::get_singleton()->texture_is_valid(p_texture_rd_rid)" is true.
`

And there are errors on exit from editor with Texture2DRD:

`
ERROR: Attempted to free invalid ID: -9223370954523017128
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8492)
ERROR: Attempted to free invalid ID: -9223370950228049831
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8492)
ERROR: Attempted to free invalid ID: -9223370945933082534
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8492)
ERROR: Attempted to free invalid ID: -9223370941638115237
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8492)
ERROR: Attempted to free invalid ID: -9223370937343147940
   at: _free_internal (drivers/vulkan/rendering_device_vulkan.cpp:8492
`

Is this because i create new textures on RD with the timer? I mean that I create texture with both methods after each shader execution. Should I only create Texture2DRD once and it will be auto-updated with each shader execution?

**Comment by BastiaanOlij** [comment]
Yes, you should only create the texture once, the compute shader will overwrite the contents each time.

You also need to free the texture you've created on exit or you'll slowly fill up memory with unused copies.

**Comment by pkpro** [comment]
Thank you @BastiaanOlij !
I'm discarding this PR, because it is not required. One can inherit PanoramaSkyMaterial in gdscript and wrap around whatever functionality is required with Texture2DRD, which is much better solution.

**Comment by Zireael07** [comment]
> PanoramaSkyMaterial in gdscript and wrap around whatever functionality is required with Texture2DRD, which is much better solution.

Worth documenting IMHO - it would have never occurred to me otherwise

**Pull request closed without merging**
