### PR TITLE
Added GROW_DIRECTION_BOTH for controls

### PR DESCRIPTION
**Pull request by ghost**
This PR adds the option Both to Grow Direction in controls, allowing a control to expand equally in both directions from its center, as opposed to expanding fully towards Begin or End. This implements #16546.

I wasn't sure how to name the enum, maybe GROW_DIRECTION_EQUAL would be more fitting?

### CODE REVIEW

**Comment by girng** [comment]
oh, wow, so this would actually do it automatically instead of re-positioning the pivot offset everytime? +1, this is great

**Comment by volzhs** [comment]
travis complains

```
*** The following differences were found between the code to commit and the clang-format rules:
--- a/scene/gui/control.cpp	2018-02-12 04:08:31.607097138 +0000
+++ b/scene/gui/control.cpp	2018-02-12 04:09:06.614942105 +0000
@@ -1283,7 +1283,7 @@
 		if (data.h_grow == GROW_DIRECTION_BEGIN) {
 			new_pos_cache.x += new_size_cache.width - minimum_size.width;
 		} else if (data.h_grow == GROW_DIRECTION_BOTH) {
-			new_pos_cache.x += 0.5*(new_size_cache.width - minimum_size.width);
+			new_pos_cache.x += 0.5 * (new_size_cache.width - minimum_size.width);
 		}
 
 		new_size_cache.width = minimum_size.width;
@@ -1293,7 +1293,7 @@
 		if (data.v_grow == GROW_DIRECTION_BEGIN) {
 			new_pos_cache.y += new_size_cache.height - minimum_size.height;
 		} else if (data.v_grow == GROW_DIRECTION_BOTH) {
-			new_pos_cache.y += 0.5*(new_size_cache.height - minimum_size.height);
+			new_pos_cache.y += 0.5 * (new_size_cache.height - minimum_size.height);
 		}
 
 		new_size_cache.height = minimum_size.height;
```

**Comment by isaacremnant** [comment]
Should be good to go, I'll be sure to test the code with clang next time :)

**Comment by reduz** [comment]
I am wondering whether it would make more sense to simply remove growth direction and just deduce it from the anchors...

**Comment by reduz** [comment]
as in, for horizontal anchors.. if both are BEGIN(0), growth can happen to the right. If both are END(1), it can happen to the left, and inbetween we just interpolate...

**Comment by reduz** [comment]
@groud what do you think?

**Comment by groud** [comment]
Yeah In my opinion that's a good idea. I think in most cases it will be fine if it's deduced from the anchors. Also, if that's not the expected behaviour, users could still modify easily the position with a really simple line of code. So I guess it's ok.

Also, this would allow removing this grow_direction value that I find a little bit unintuitive.

**Pull request merged**
