### PR TITLE
Stop pasted child nodes being assigned an owner when previously unowned

### PR DESCRIPTION
**Pull request by snailrhymer**
Add a check in paste_nodes() so that pasted children aren't given an owner if the 'original' child on the clipboard didn't have an owner. This makes copy & pasting behave the same as directly duplicating.

Fixes one of the causes of #62614 for `master`. The fix for `3.x` is analogous but in a slightly different place; I can backport if this fix is approved.

### CODE REVIEW

**Comment by KoBeWi** [comment]
This breaks nodes with owner:
godot windows tools 64_gBct4s2qdc

**Review by KoBeWi — APPROVED** [review]
Needs rebase.

**Comment by YuriSizov** [comment]
Rebased and force-pushed.

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
