### PR TITLE
Add Vector4 to VisualShader

### LINKED ISSUE #3761: VisualShader add Vector2 & Vector4 input/output node connections
### Describe the project you are working on

3D Dungeon Keeper like game

### Describe the problem or limitation you are having in your project

Currently it isn't possible in to use Vector4 input/output node connections for expression nodes in VisualShader.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add missing Vector2/4 input/output node connections.
If you are working with vector4 you always first need to convert it into a vector3 and use two input/outputs (vec3 and one float) which is very anoying.
Same can be said for mat2 and mat3 which are also missing

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add the missing connection types to the input/output selection of the Expression node.

grafik

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There are workarounds to use a GlobalExpression node to store Vector2/Vector4 variables and use them in Expression Nodes.
But this solution would defy the reason to use VisualShader in the first place.

### Is there a reason why this should be core and not an add-on in the asset library?

Its a feature to be exprected in a visual shader editor.
Like Unity's shadergraph or Shader Forge.

### PR DESCRIPTION
**Pull request by Geometror**
Split from #59970, this PR adds Vector4 to VisualShader without introducing a new variant type.  'Quaternion' is used to transfer data to the shader instead of 'Plane' since its internal structure is more similar to a general Vector4 type (component names: xyzw, 4 floats instead of one normal Vector3 plus the displacement component). Still feels a bit off to use a Quaternion for that, but as #59970 requires more discussion or won't be merged at all, I think its ok for now (also, it can easily be changed).

Closes https://github.com/godotengine/godot-proposals/issues/3761

Detailed changes:
-   Added new Vec4Uniform and Vec4Constant nodes
-   Added Vector4 support to all vector operation nodes
-   Implement conversion between primitive types (behavior consistent with Vector2/Vector3)
-   [While at it] Fix incorrect conversion from vec2 to int

Screenshot_20220412_153436

### CODE REVIEW

**Review by Chaosus — CHANGES_REQUESTED** [review]
https://github.com/godotengine/godot/blob/67957f5faaeaf03e78de8eb89524d0582294750f/scene/resources/visual_shader_nodes.cpp#L2723-L2728 requires your attention - OneMinus operator does not work with Vector4 currently

**Review by Chaosus — CHANGES_REQUESTED** [review]
https://github.com/godotengine/godot/blob/67957f5faaeaf03e78de8eb89524d0582294750f/scene/resources/visual_shader.cpp#L2679-L2680 Add `BIND_ENUM_CONSTANT(VARYING_TYPE_VECTOR_4D);` to generate binding

**Comment by Geometror** [comment]
@Chaosus I overlooked a few things, but they should be fixed now:
- Fixed vector functions SATURATE, ONE_MINUS, RGB2HSV, HSV2RGB (made the last two invalid for Vector4, same behavior as for Vector2)
- Fixed vector operation CROSS and REFLECT (made them invalid, since the built-in reflect function does only accept vec3, however this could be changed in another PR as reflect is defined for all dimensions in GLSL and HLSL)
- Fixed documentation

**Comment by Geometror** [comment]
Missing branch in the get_port_type function used by `VisualShaderNodeVaryingSetter/VisualShaderNodeVaryingGetter`. Fixed now.

**Review by Chaosus — APPROVED** [review]
Everything looks correct for me for now. Thanks for this contribution, for good and qualitative work from you as usual.

**Comment by Chaosus** [comment]
Thanks!

**Pull request merged**
