### PR TITLE
Move transitions of textures from transfer workers to the graphics queue.

### LINKED ISSUE #98158: [DX12] Crash on startup due to missing transfer worker command buffer
### Tested versions

- Reproduced in Godot v4.4.dev (92e51fca7)
- Reproduced in Godot v4.4.dev (98deb2a00)
- Cannot reproduce in Godot v4.4.dev (3b41f7310)

### System information

Windows 10.0.26100 - Multi-window, 1 monitor - Vulkan (Forward+) - integrated AMD Radeon(TM) 780M (Advanced Micro Devices, Inc.; 31.0.24018.2001) - AMD Ryzen 7 7840U w/ Radeon  780M Graphics (16 threads)

### Issue description

Attempting to start the editor or run any project using the D3D driver leads to a crash when Godot attempts to create the default white cubemap texture in `texture_storage.cpp:255`:

``` cpp
default_rd_textures[DEFAULT_RD_TEXTURE_CUBEMAP_ARRAY_WHITE] = RD::get_singleton()->texture_create(tformat, RD::TextureView(), vpv);
```

This appears to be due to the command buffer on the transfer worker being invalid during the texture creation, which leads to a null pointer being de-referenced in `rendering_device.cpp:5110`:
image

I believe this is a regression caused by #90400. I used `git bisect` to identify `98deb2a00` as the commit that caused this regression.

Full debug log (with DLL load messages stripped):
```
Godot Engine v4.4.dev.custom_build.92e51fca7 (2024-10-10 23:13:24 UTC) - https://godotengine.org
onecore\windows\directx\dxcore\dll\dxcore-win.cpp(927)\dxcore.dll!00007FFE6CABF8EA: (caller: 00007FFE6CAB29B1) Exception(1) tid(317e8) C0000034 Object Name not found.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: wil::ResultException at memory location 0x0000008C19BF1660.
D3D Error 887e0003: (202728@233241203) at 00007FFE5CA76ED4 - Unable to load D3D12Core.dll.  Verify D3D12SDKPath is correct.
Microsoft.Direct3DUndocked\src\D3D\module.cpp(728)\D3D12.dll!00007FFE5CA76EF8: (caller: 00007FFE5CA7EBD5) LogHr(1) tid(317e8) 887E0003 The D3D12 SDK version configuration of the host exe is invalid.
    Msg:[Unable to load D3D12Core.dll.  Verify D3D12SDKPath is correct.]
D3D12 12_0 - Forward+ - Using Device #0: AMD - AMD Radeon(TM) 780M
WARNING: PSO caching is not implemented yet in the Direct3D 12 driver.
     at: RenderingDeviceDriverD3D12::pipeline_cache_create (drivers\d3d12\rendering_device_driver_d3d12.cpp:4876)
drivers\d3d12\rendering_device_driver_d3d12.cpp:4876 - PSO caching is not implemented yet in the Direct3D 12 driver.
ERROR: Close failed with error 0x80070057.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:2358)
Close failed with error 0x80070057.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF24D0.
D3D12: Removing Device.
ERROR: Reset failed with error 0x80070057.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:2341)
Reset failed with error 0x80070057.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF2AB8.
ERROR: Map failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:899)
Map failed with error 0x887a0005.
ERROR: Parameter "write_ptr" is null.
   at: RenderingDevice::_texture_initialize (servers\rendering\rendering_device.cpp:1260)
servers\rendering\rendering_device.cpp:1260 - Parameter "write_ptr" is null.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF2668.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF28B0.
ERROR: Condition "!(((HRESULT)(res)) >= 0)" is true. Returning: FenceID()
   at: RenderingDeviceDriverD3D12::fence_create (drivers\d3d12\rendering_device_driver_d3d12.cpp:2148)
drivers\d3d12\rendering_device_driver_d3d12.cpp:2148 - Condition "!(((HRESULT)(res)) >= 0)" is true. Returning: FenceID()
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF2678.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF28C0.
ERROR: Condition "!(((HRESULT)(res)) >= 0)" is true. Returning: SemaphoreID()
   at: RenderingDeviceDriverD3D12::semaphore_create (drivers\d3d12\rendering_device_driver_d3d12.cpp:2182)
drivers\d3d12\rendering_device_driver_d3d12.cpp:2182 - Condition "!(((HRESULT)(res)) >= 0)" is true. Returning: SemaphoreID()
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF2598.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF27D0.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF2840.
ERROR: CreateCommandAllocator failed with error 0x887a0005.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:2308)
CreateCommandAllocator failed with error 0x887a0005.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF18C8.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF1B30.
Exception thrown at 0x00007FFE6FBB83EA in godot.windows.editor.dev.x86_64.exe: Microsoft C++ exception: _com_error at memory location 0x0000008C19BF1BA0.
ERROR: Can't create buffer of size: 16384, error 0x887a0005.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:863)
Can't create buffer of size: 16384, error 0x887a0005.
Exception thrown at 0x00007FF6497F732A in godot.windows.editor.dev.x86_64.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

### Steps to reproduce

1. Compile the engine with D3D support.
2. Run the editor and try to load or create a project.  Alternatively, try to run a project directly from the command line.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by DarioSamo**
This seems to effectively fix https://github.com/godotengine/godot/issues/98158.

When using enhanced barriers, it is not possible to transition to anything but the COMMON layout in D3D12 when using a copy queue. The fix is split in two separate steps: a new layout has been added to represent this type along with a new API trait that says whether copy queues can only use that layout, and any post-copy transitions are now pushed to the graphics queue on the next possible frame.

Requires https://github.com/godotengine/godot/pull/98086 to be merged first, as I built the PR on top of it to avoid the future merge conflict.

### CODE REVIEW

**Comment by DarkKilauea** [comment]
Tested this PR, seems to fix #98158

**Review by Calinou — APPROVED** [review]
I can't reproduce https://github.com/godotengine/godot/issues/98158, but code looks good to me nonetheless.

**Review by Chaosus — APPROVED** [review]
Can confirm this fix a crash for me.

**Comment by clayjohn** [comment]
Thank you!

**Pull request merged**
