### PR TITLE
Add OS.request_attention() for Windows

### PR DESCRIPTION
**Pull request by vnen**
This makes the taskbar icon flash to request user attention.

On OSX there's the [`NSApplication.requestUserAttention()`](https://developer.apple.com/reference/appkit/nsapplication/1428358-requestuserattention?language=objc) function that does a similar job (makes the dock icon bounce), but I don't know Objective-C nor do I have a Mac to test it.

I found nothing about this for Linux though...

Related to #3292.

### CODE REVIEW

**Comment by neikeq** [comment]
The commit adds a new file called ` doc/base/classes.xml2` which looks like a duplicate of ` doc/base/classes.xml`. Is that a mistake?

**Comment by vnen** [comment]
@neikeq ugh! It's a mistake indeed, I'll fix.

**Comment by vnen** [comment]
Remove the extra file.

**Comment by Hinsbart** [comment]
I think this can be done using the "urgency" x11 hint on linux.
However it needs to be disabled manually, how should that be handled?

**Comment by vnen** [comment]
@Hinsbart maybe disable it when the window receive focus again? Then it should never do anything if the windows is already focused, which is not really bad.

**Comment by reduz** [comment]
Should we wait for more platforms to be suported?
Also it would be fantastic to add the progressbar hint too, which I have seen before in all OSs. 
Would be really useful for when Godot is procressing (shows the progress bar), specially when it's exporting

**Comment by vnen** [comment]
I've been thinking of the progress bar too. I'll see if I can figure this out, but I don't it'll be hard to do on Windows (unless they have another weird API).

It'd also be nice to someone with a Mac to have a look at this. It seems just a function call to make this work.

**Comment by vnen** [comment]
About the progress bar:

output

What is hard here is figuring out a nice API. Also, I couldn't find any generic solution for Linux, only for specific DEs (maybe @Hinsbart can find out more about it). For OSX there's [NSProgressIndicator](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSProgressIndicator_Class).

I think that using some OS-specific shell extensions might be nice too.

**Comment by supaiku-o** [comment]
@vnen There exists the https://wiki.ubuntu.com/Unity/LauncherAPI which is a Ubuntu standard, but also implemented by KDE since 5.6. ElementaryOS also [supports](https://elementary.io/docs/human-interface-guidelines#desktop-integration) it.

**Comment by akien-mga** [comment]
OSX support is added by #5662. I'd be for merging those two PRs and document that it's not implemented on Linux for now (and open a corresponding issue so that we don't forget to implement it). WDYT?

**Pull request merged**
