### PR TITLE
Fix 'TextEdit's line wrapping being highlighted incorrectly

### LINKED ISSUE #22867: Errors in TextEdit's word wrapping
**Godot version:**
e6cfaa1

**Issue description:**
- ~~It takes more characters than it should for the line to start wrapping, making some content be completely hidden.~~
- When wrapping a tabbed line, a the spacing also appears in the wrapping bellow, this also causes some visual errors with highlighting enabled:
screenshot at 2018-10-04 23-11-45

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #22867.

### CODE REVIEW

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Looks good, however, you can use the local var `indent_px` rather then recalculating.

**Comment by YeldhamDev** [comment]
@Paulb23 I actually can't, as it also can be "0".

**Comment by Paulb23** [comment]
It should be fine, as `indent_px` is only explicitly set to `0` when this condition will not be ran.

**Comment by YeldhamDev** [comment]
@Paulb23 Changes made.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
