### PR TITLE
Fasttracker II support

### PR DESCRIPTION
**Pull request by dahlgrenmartin**
Hello!

Sorry... this is not ready to be merged. It works, but not everything is implemented. I need to know if this is correct before I move on.
I used the AudioStreamSample as a reference and I dont know why sometimes it uses "wav" and sometimes "sample" as extension. Here I put everything as "xm".

I'm also wondering if I can output every module channel to its own AudioBus?

Apologies for doing a PR, dont know the correct channel for this sort of review.

/Martin.

### CODE REVIEW

**Comment by bruvzg** [comment]
Related PR: #16896

**Comment by groud** [comment]
Midi files support is provided via a gdnative plugin. It should likely be the se thing for such tracker files.

**Comment by mdahlgrengadd** [comment]
Great! I searched only issues and missed the modplug PR.

**Comment by mdahlgrengadd** [comment]
@groud I cant find the GDNative MIDI files support project. Do you have a link? 

I did find these:

https://bitbucket.org/arlez80/godot-midi-player/
https://github.com/DanielMatarov/Google-Summer-of-Code--Module-and-test-projects

...but neither are made as GDNative libraries.

**Comment by groud** [comment]
That's the one. But yeah, it's indeed a module, not a gdnative plugin. (it should likely be converted someday I guess)

But in any case, what I meant is that such feature does not belong to the core engine, they are too much corner case.

**Comment by mdahlgrengadd** [comment]
Just a note... There's seems to be allready a GDNative modplayer:
https://github.com/mdahlgrengadd/godot-FLMusicLib

**Comment by mdahlgrengadd** [comment]
I'm closing this PR. Thanks for the info everyone! 
Ps. I edited the gdnative-cpp-example to play a xm file:
https://github.com/mdahlgrengadd/gdnative_cpp_example/tree/xm-player
Next I want to make ShyRed's openmpt module as gdnative (if I can).

**Pull request closed without merging**
