### PR TITLE
Reverted the ParallaxLayer to use the Godot 3 offset formula to fix scrambled layers

### PR DESCRIPTION
**Pull request by ghost**
This pull request is in reference to the issue #75562 .

Everything relevant to the issue is there, but in summary, Parallax Layers weren't being correctly placed in Godot 4, and I basically reverted the offset formula to what it was in Godot 3, without adding anything to the classes except a getter for the ParallaxBackground screen_offset, since ParallaxLayer needed access to it.

All of this I've made assuming this wasn't an intended change, I asked in the Q&A site and posted this issue and no one has told me that it's supposed to be different from Godot 3, so I just created this pull request, feel free to reject it if this was in fact a wanted change and a new behavior for the Layers.

Thanks for your time.

### CODE REVIEW

**Comment by KoBeWi** [comment]
It was changed in #58567
IIRC it made it easier to setup the parallax, because the position is more predictable.

**Comment by strellydev** [comment]
> It was changed in #58567 IIRC it made it easier to setup the parallax, because the position is more predictable.

I see, I'll close the issue and pull request then, thanks for the info.

**Comment by strellydev** [comment]
Since I'm here, can I ask if there's a guide or something for the new parallax layer system? I can't for the love of god figure out where I'm supposed to put the layers, right now I have them in way different points of the map moving them slowly to see how they react and the documentation doesn't say anything plus the tutorials I see are all for Godot 3, and the only plugin I see that let's me preview layers in the editor is using the position formula for godot 3, so it shows them "correctly" but then they aren't when playing the game.

**Comment by KoBeWi** [comment]
When you start the scene with the default view (no camera), all layer objects will be at the position you placed them regardless of their motion scale. So you don't need to use any formula, stuff will appear just as you placed it.

**Comment by strellydev** [comment]
> When you start the scene with the default view (no camera), all layer objects will be at the position you placed them regardless of their motion scale. So you don't need to use any formula, stuff will appear just as you placed it.

And if I'm using a camera? I tried putting them in the spawn position of the camera but that doesn't fix it. I also tried putting it around the center of the whole map to see if maybe they'd move from there, but nothing seems to work as I imagine it should and the layers end up scrambled.

**Comment by strellydev** [comment]
> I mean the position within the default blue rectangle is the reference position for the default view. Once the camera moves out of this position, the layers are moved. So I guess the formula is something like `offset * motion_scale`, where offset is the position difference between current viewport transform and the default one (which is either Camera2D at (0, 0) with anchor mode set to top-left or at viewport size / 2 with anchor mode center (default)).

Oh my god, thank you so much, I see it now. You saved me a lot of headaches!

**Pull request closed without merging**
