### PR TITLE
[Docs] Add doc for Input::get_action_strength

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**

### CODE REVIEW

**Comment by KellyThomas** [comment]
Is this in the range 0 to 1?

It might be good to include the range in the docs.

**Comment by guilhermefelipecgs** [comment]
> Is this in the range 0 to 1?


Yes. I will include it tomorrow.

**Comment by groud** [comment]
I think the text is a little bit too vague :
- It should state, as said @KellyThomas, that the value is between 0 and 1.
- It should make it clear that the value correspond to "how strong" the action is. For an axis, it corresponds to how far the controller is from the deadzone.

**Comment by guilhermefelipecgs** [comment]
Description changed as suggested by @KellyThomas and @groud.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
