### PR TITLE
removed multiscript

### PR DESCRIPTION
**Pull request by karroffel**
After some testing it is clear that this feature isn't as useful as most people thought.
The opposite effect happened. Scripts are designed to be attached to one object, so there are unintuitive behaviours.

Now nobody can say we didn't try again 😛 

RIP MultiScript

### CODE REVIEW

**Review by neikeq — APPROVED** [review]
I told you this was madness.

**Comment by akien-mga** [comment]
`ELOGTOOSHORT`

Please be more explicit as to why you're removing it. The description of the commit log should mention that it was readded in commit $hash, but finally reverted as it brought various difficulties that would make multiscripts too convoluted. Please think of future contributors ;) If we had had those details in the previous commit removing the feature, we might not have retried it.

**Comment by akien-mga** [comment]
Also almost everyone is using a capitalized commit log name, why must you be different? ;)

**Comment by karroffel** [comment]
@akien-mga I'm special 😛 

Added a better git log

**Comment by akien-mga** [comment]
I know I'm annoying, but it's very important in big projects that commit logs are very explicit. They should not only clearly define what they do ("removed multiscript", that's already clear enough, though "Remove MultiScript module" would look better :P), but also explain the why of a decision. If the decision is trivial, it's of course not necessary, but as soon as some explanations would be useful, they should be given (as they are in your PR description, but nobody will read GitHub PR descriptions 3 years in the future when we're using a self-hosted federated GitLab instance :P).

**Comment by punto-** [comment]
I'm still curious about it, I never got to try it myself (it was supposed
to be used for Dog Mendonca before we figured out esc), what tests did you
do exactly?

**Comment by karroffel** [comment]
@punto- See #8546

**Pull request merged**
