### PR TITLE
Visual script function call set get improvement

### LINKED ISSUE #26717: Drag & drop creates function node instead of Set or Get
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script
when drag & drop from Scene tab to visual script area, it shows a list of properties, after select, it create a function node instead of Get or Set node.
when change the function it shows a list of methods.
https://drive.google.com/open?id=1QgBxuP37_D_dvUatKIo32HT4Ar_IgUKX

the correction :
when drag & drop it will show a list of methods.
properties can be added by drag & drop from inspector, or by holding shift and drag & drop from Scene tab to visual script area, then it will show a list of properties and create a Get or Set node.
https://drive.google.com/open?id=1LRnvQsdJsBr8FcoZDTlFjTNmHzRBZgJI

### LINKED ISSUE #49146: Visual Script CollisionShape2D Get Shape node throws "Invalid call" error
**Godot version:**

3.3.2

**OS/device including version:**

macOS

**Issue description:**

Happened: unhelpful error "Invalid call" with no explanation what went wrong.
Expected to get shape from node.
изображение

**Steps to reproduce:**
1) Create in the tree: Area2D, inside - CollisionShape2D, optionally - add RectangleShape2D
2) Drag node into visual script with Get Shape.
3) Use it in function (see repro). Experience error.

**Minimal reproduction project:**

[poolvector2arrayrepro.zip](https://github.com/godotengine/godot/files/6555034/poolvector2arrayrepro.zip)

### PR DESCRIPTION
**Pull request by Gallilus**
Supersedes #49184 
Supersedes #49172
Fixes #26717
Fixes #49146

### Editor changes
* Fix issue when of dropposition when in different zoom levels.
* Fix drag in Set and Get.

### VisualScriptFuncNode's changes
* Harmonize and improve the visual representation of the VisualScriptFuncNode's and there different modes.
* Update Functionality of VisualScriptFunction*Get* to include pass when using instance mode.

### CODE REVIEW

**Comment by pycbouh** [comment]
Just a heads up as you will be fixing the issues reported by CI: you need to rebase and squash your commits. Your PR must consist of a single commit with a succinct but descriptive message. See our git history for examples.

**Comment by DavidCambre** [comment]
Cool fast response team is here 🥇 
Let me see if I get all the checks to pass then I will learn how to squash.

**Comment by pycbouh** [comment]
Speaking of checks, you can speed some of it up by installing pre-commit hooks. That way some checks can be performed locally, even before you push. See `misc/hooks` in this repository.

**Comment by DavidCambre** [comment]
It seems that GIT is not my cup of tee. So I ended up creating a new PR #49749
One day I will learn how to fix git history,... not today

**Pull request closed without merging**
