### PR TITLE
Revert improve update tree

### LINKED ISSUE #70688: Path3D: Point handles invisible in editor
### Godot version

4.0 beta 10

### System information

Windows 10, Vulkan

### Issue description

While the fishbone pattern is visible, the points are not. (Invisible) points can be added to a path and deleted from it, but they can't be moved in the editor viewport, only via inspector properties.
I haven't used 4.9b, but I confirmed the point handles are visible in 4.8b on my system (same file).

### Steps to reproduce

Make a Path3d. Add points via Inspector. Fail to see point handles in the viewport.

### Minimal reproduction project

n/a

### LINKED ISSUE #70914: EditorPlugins that depend on the resources that Node has will not be visible when SubInspector is opened
### Godot version

4.0.dev(dc3175e4cdb4e54e1c6200b6c4d07646eea95284)

### System information

Any

### Issue description

EditorPlugins that depend on the resources that Node has will not be visible when SubInspector is focused.

https://user-images.githubusercontent.com/61938263/210553656-86669f57-e41f-427e-a650-30630c27d850.mp4

This is caused by two problems:

The first is caused by implicit editor deletion in Node3D. This is fixed by #70907.

The other is due to a change in inspector update timing, which is regression by #68498. Revert PR #70909 will fix this issue, but if not, we will need to update SubInspectorEditor in the correct way.

### Steps to reproduce

Select Path3D or CollisionPolygon3D and open a SubInspector such as Script.

### Minimal reproduction project

[plugintest.zip](https://github.com/godotengine/godot/files/10343962/plugintest.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #70914. Fixes #70688.

See also https://github.com/godotengine/godot/pull/70907#pullrequestreview-1235676384.

Many EditorPlugins rely on Inspector updates. In fact, some problems (#70588, #70688) were caused by #68498, so we need to revert them to restore stability. And we should be careful when changing the timing of inspector updates.

### CODE REVIEW

**Comment by YuriSizov** [comment]
> Many EditorPlugins rely on Inspector updates.

If there are plugins that rely on the expensive operation of rebuilding the tree to be performed immediately, up to several times a frame, that's a huge performance problem and an issue with those plugins (or with underlying systems in the plugin API).

**Comment by TokageItLab** [comment]
In the meantime, I've summarized the problem in #70914. If no one find the correct way of fixing it, we will have to revert them. cc @Rindbee

**Comment by Rindbee** [comment]
> In the meantime, I summarized the problem in #70914. If no one find the correct way of fixing it, we will have to revert them. cc @Rindbee

I agree with reverting them.

These issues are all caused by delayed calls. And the situation of executing multiple complete `update_tree()` in a single frame is not as much as imagined.

**Comment by YuriSizov** [comment]
> These issues are all caused by delayed calls.

I don't think so. I think they were uncovered by making the calls delayed, but existed anyway. Do you have another explanation to why making the tree update delayed would cause these behaviors?

**Review by akien-mga — APPROVED** [review]
I agree with reverting for now, and taking the time to redo these improvements while solving the bugs they uncovered.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Rindbee** [comment]
> I don't think so. I think they were uncovered by making the calls delayed, but existed anyway. Do you have another explanation to why making the tree update delayed would cause these behaviors?

Produced together with #61292. These conflict with #61292.

**Pull request merged**
