### PR TITLE
Cleaner iteration API for Objects

### PR DESCRIPTION
**Pull request by ghost**
The current iteration API for objects feels like an unfortunate hack to me. To declare an integer iterator for `range(6)`, you do this:

```
class MyIterator:
	func _iter_init(arr):
		arr[0] = 0
		return true

	func _iter_next(arr):
		if arr[0] >= 5:
			return false
		arr[0] += 1
		return true

	func _iter_get(iter):
		return item
```

Note that in `_iter_init` and `_iter_next` a 1-size array is used as a crutch for returning an out value. Then on `_iter_get` you suddenly get the iterator.

This PR changes the API to this:

```
class MyIterator:
	func _iter_init():
		return [0]

	func _iter_next(iter):
		if iter[0] >= 5:
			return false
		else:
			iter[0] += 1
			return true

	func _iter_get(iter):
		return iter[0]
```

It's now up to `MyIterator` how to construct an iterator object that can be modified using `_iter_next`. It can use an array with an integer, as in this case, but it could also (and might often) want to construct an object instance and return it; in the latter case, the whole array-1 crutch becomes obsolete and should not be enforced by the API.

`_iter_next` and `_iter_get` both get the iterator instance returned by `_iter_init`.

`_iter_init` returns `nil` if no elements are initially available.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by reduz** [comment]
My feeling with this is that the API is still a hack, no matter how much it's changed. Passing an array at least makes it more obvious how it needs to be used, even if less flexible, so I am not sure I am in favor of changing it. What would be an use case to make it more generic and variant based?

**Comment by poke1024** [comment]
The current implementation basically separates implementation from data, and encourages hacky, unreadable code IMHO:

```
class SomeComplexIterator:
	func _iter_init(arr):
		arr[0] = array(1, 3, 7)
		return true

	func _iter_next(arr):
		arr[0][0] = arcane_iteration_logic(arr[0][0], arr[0][1], arr[0])
		return arr[0][2]

	func _iter_get(iter):
		return iter[0] -- hu?
```

I mean, really, GDScript is OOP, so everyone expects things like this:

```
class SomeComplexIteratorState:
	var a
	var b
	var c

	func get():
		...

	func next():
		...
```

Now, for wrapping my nice, encapsulated `SomeComplexIteratorState` class into an data-free iterator, I can either have this:

```
class MyIteratorCurrent:
	func _iter_init(arr):
		arr[0] = SomeComplexIteratorState.new()
		return true

	func _iter_next(arr):
		return arr[0].next()

	func _iter_get(iter):
		return iter.get()
```

or this:

```
class MyIteratorWithPR:
	func _iter_init():
		return SomeComplexIteratorState.new()

	func _iter_next(iter):
		return iter.next()

	func _iter_get(iter):
		return iter.get()
```

To me, the latter is much more clear.

Upon re-reading the PR, I'm not even sure that `_iter_init()` should return `nil` if no elements are available.

Regarding use cases (not sure if I get your question right) I think implementing any of the following would make me want to use that dedicated `SomeComplexIteratorState` code + data model from above:

* https://docs.python.org/3/library/functions.html#zip
* https://docs.python.org/3/library/functions.html#reversed
* https://docs.python.org/3/library/functions.html#sorted (without full sorting, using a heap)
* https://docs.python.org/2/library/itertools.html#itertools.cycle
* https://docs.python.org/2/library/itertools.html#itertools.chain

**Comment by reduz** [comment]
I will close this for now, given there is not much desire to break compatibility and there is no really much of an urgency to improve this API. Lets discuss this again closer to 4.0, when we can break compatibility and change more core aspects of GDScript.

**Pull request closed without merging**
