### PR TITLE
Fix hovering on toggled link and texture buttons

### PR DESCRIPTION
**Pull request by samuelpedrajas**
It seems that DRAW_HOVER_PRESSED introduced a small bug in the TextureButton class. When one of these buttons is toggled (toggle mode being active) the button disappears when the mouse is over it.

Steps
1. Download this project: [TextureButtonBug.zip](https://github.com/godotengine/godot/files/2452450/TextureButtonBug.zip)
2. Play it.
3. Toggle the button and see how it disappears while the mouse is over it.

I basically copied the code from the DRAW_HOVER case to the DRAW_HOVER_PRESSED one and removed the `if (hover.is_null())` conditional. Let me know if this is the right way to do it!

### CODE REVIEW

**Comment by DualMatrix** [comment]
Wouldn't it be cleaner to move the check for HOVER_PRESSED above the check for PRESSED and just not break?

**Comment by samuelpedrajas** [comment]
Yes you're right @DualMatrix. I just changed my commit.

**Comment by DualMatrix** [comment]
So I looked back to #22384 where I added the HOVER_PRESSED mode and I'm unsure this is the best solution. IMO HOVER_PRESSED should't even be called when Pressed automatically implies Hovering like in regular Buttons. I thought this was already the case but apperenlty I implemented it a bit differently. I think I should move the check that tests whether hover_pressed is possible to where the notification in sent ,not where it is recieved. This would be the cleaner solution I think.

**Comment by samuelpedrajas** [comment]
I suppose it depends if we want to allow a "hover pressed texture" for TextureButtons in the future (I think it could make sense). If so, I think we can leave it like this. If not, I think you're right, the notification shouldn't even get there. What do you think?

**Comment by akien-mga** [comment]
The same bug likely happens in `LinkButton` where `DRAW_HOVER_PRESSED` is also discarded.

**Comment by samuelpedrajas** [comment]
You're right, I tested it with the "Font Color Hover" and "Font Color Pressed" and it is happening. I've updated the PR title and the commit, although @DualMatrix may come with a better solution.

**Comment by samuelpedrajas** [comment]
If it makes sense to have this "hover pressed" functionality for `TextureButton` and `LinkButton` (including being able to select a texture or a font color for it in the inspector) we could merge this as it is right now and open an "enhancement" issue (I can do it myself) about this new functionality. What are your thoughts on this?

**Comment by DualMatrix** [comment]
@samuelpedrajas I don't see how HOVER_PRESSED makes sense for regular buttons, since it being pressed automatically means it's being hovered over at the same time right?

**Comment by samuelpedrajas** [comment]
@DualMatrix If `toggle mode` is active then the button stays pressed even when the mouse is not over it, that's why I thought it was a good idea, but I may be missing something.

**Comment by DualMatrix** [comment]
@samuelpedrajas Oh, I wasn't aware of that, in that case the HOVER_PRESSED functionallity should probably be extended to all buttons that offer that mode

**Comment by Jalu1** [comment]
Came here from an issue relating to this bug...  It solves the bug, but Should there not be an option to add a texture for HOVER_PRESSED, and have it default to the PRESSED texture if not defined?

**Comment by DualMatrix** [comment]
@Jalu1 Yeah, thats also what I had in mind

**Comment by Jalu1** [comment]
the entire switch statement can be reworked to be more efficient, working on that now

**Comment by Jalu1** [comment]
Alright, I rebuilt the structure of the switch statement so it is cleaner and includes support for the extra texture. Can I add to the fork?

**Pull request merged**
