### PR TITLE
[WIP] Add graph node roundness option

### PR DESCRIPTION
**Pull request by Chaosus**
Its cool if user can control roundness of visual script nodes, so I've added possibility for this. I bring a new option interface->theme->Graph Node Roundness, Its off by default - "0" .

image

For example, If you change it to "10" - (changes will apply immediatly)

image - with header
image - without header

IRC summarize:

22:41:56IssueBot#17926: Add graph node roundness option | https://git.io/vximk 
22:42:17AkienIt looks nice, but I wonder why the added methods are private? 
22:42:18reduzto me this is pointless, if you guys like it go ahead, i see no reason to merge this 
22:42:46groud_Well i kind of agree 
22:42:59chaosus89because if they public the custom GraphNode could crash inside editor 
22:43:11groud_I mean, the style is nice, but i don't get why people want to add everything as an option 
22:43:19chaosus89its works only in VisualScriptEditor 
22:43:21chaosus89for now 
22:43:39groud_If people like I would just make it default 
22:43:51reduzalso exposing it in GraphNode makes no sense, we have a theme system for a reason 
22:43:52groud_And don't provide an option to change that 
22:44:22groud_Oh i did not think about that 
22:44:43groud_Making it part of editor theme makes more sense 
22:44:53reduzit already is part of the editor theme 
22:45:05falesyeah, fix it in theme in case. I agree roundness is nice (though title should not be rounded as in comment) but should really be done via theme 
22:45:05groud_So the option makes no sense then 
22:45:05reduzjust not esily exposed in editor settings 
22:45:54falesI don't really think it's should be an option in editor settings, we should go for a nice look by default and that's it 
22:46:05falesit should* 
22:46:27chaosus89oh, I can remove it and change to just a constant ? nice 
22:47:11reduzwho made the editor theme? was it not toger5 and djrm[m]? 
22:47:20groud_Probably yes 
22:47:43groud_Maybe we can tag them and if they agree to make it default 
22:48:19faleschaosus89, no, the stylebox for GraphNode in the editor theme should be changed in case. 
22:48:21AkienOk I'll quickly summarize our points and ping djrm, let's move to the next PR in the meantime, time flies

### CODE REVIEW

**Comment by Chaosus** [comment]
For some reason engine crashes when GraphNode creates by user in Editor if StyleBoxFlat used.. need time to investigate, do not merge for now

**Comment by Chaosus** [comment]
Ok, I think Im done, roundness is private for public usage on custom GraphNodes for now, but the new option is work for visual scripting nodes.

**Comment by PostPollux** [comment]
Thanks for that feature, I like it!
Though, for the version with header I think it would look better if the top corners of the inner body were not round. Like in this mockup:
mockup

**Comment by Chaosus** [comment]
> would that be possible, too?
I research the possibility of it, after(as well as rounded input fields)

**Comment by djrm** [comment]
i also think that roundness should be added to the whole theme, i was planning to do a theme update for 3.1 (rounded corners included).

**Comment by Chaosus** [comment]
@djrm I didnt knew :S, should I close this PR then ? :) 
(I see on this positive - I gain some experience)

**Comment by djrm** [comment]
@Chaosus yes i think it is better to close this, since even if it looks good, it is duplicating functionality in GraphNode (These kind of changes should be configured in editor_themes).

**Comment by Chaosus** [comment]
Ok

**Pull request closed without merging**
