### PR TITLE
Separate distraction mode for scene & script editor

### PR DESCRIPTION
**Pull request by RameshRavone**
Feature requested at #8453

### CODE REVIEW

**Comment by magyar123** [comment]
You should squash the committee's into one.
Here's one way: https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by RameshRavone** [comment]
I'm going with ‘Separate Distraction Mode‘

**Comment by bojidar-bg** [comment]
@RameshRavone Since it has nothing to do with the text editor specifically, and even less with theme, would you mind moving it under `interface/`? (So, `"interface/separate_distraction_mode"`)

**Comment by tr0q** [comment]
How about 2.1?

**Pull request merged**
