### PR TITLE
NatVis improvement & GDNative addition

### PR DESCRIPTION
**Pull request by ghost**
This PR improves NatVis for the engine by adding all of the core types, that are addable to the `Variant`, as well as implements GDNative's NatVis that was non-existent before. GDNative's debugger now looks something like this: 
NatVis

### CODE REVIEW

**Comment by IlyaStuurFedorov** [comment]
This is compatible with `master` as well as with `3.X`, so it could be cherrypicked if needed.

**Comment by IlyaStuurFedorov** [comment]
Sorry, had trouble deciphering what needed to be done from CI logs.

**Comment by fire** [comment]
Can you read https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html and apply them.

In particular, the squash the commits part.

**Comment by IlyaStuurFedorov** [comment]
Can I recreate this PR? I have no idea what happened due to new commits being pushed to master, but I don't think I can fix this.

**Comment by IlyaStuurFedorov** [comment]
Sorry, I am making things only worse, I will reopen it properly.

**Comment by IlyaStuurFedorov** [comment]
Proper PR is here https://github.com/godotengine/godot/pull/50168

**Pull request closed without merging**
