### PR TITLE
Fix test_body_motion() sometimes failing to extracting collision information

### LINKED ISSUE #16414: RigidBody2D#test_motion behaving weird
**Godot version:**
3.0.stable.official

**OS/device including version:**
macOS 10.13.3

**Issue description:**
Please see the attached test project, open and start Tester.tscn. The code is using test_motion to check for collisions when moving the left sprite one point to the right.

Maybe I just don't "get" test_motion right, but shouldn't that detect a collision? I also tried the same code in _process_physics, because I thought, that collisions would only be checked there, but with the same result.

I originally wanted to recreate another weird issue of three sprites where one sprite would be moved and test_motion would detect a collision with a completely unrelated sprite, however, I stopped here.

**Steps to reproduce:**
* Open Test project
* Open scene Tester.tscn
* Check attached script
* Run game with open scene
=> the script should output a collision information, instead it produces "NOT COLLIDING" as the result of test_motion is false.

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/1695376/Test.zip)

### LINKED ISSUE #23140: Kinematic body does not move when exactly in between two static bodies
Godot 3.1 alpha 1
Godot 3.0.6

As reported in this Q&A post: https://godotengine.org/qa/34661/how-can-i-simulate-no-friction-in-a-kinematic-body-2d

If I exactly place a box Kinematic Body 2D aligned horizontally between two static boxes (using pixel and grid snapping), that body will not be able to move vertically.
If I take out one of the static boxes, it can move.
Under the same situation, a rigidbody is able to move, but the kinematic one doesn't.

Example project:
[KinematicBoxBetweenTwoOthers.zip](https://github.com/godotengine/godot/files/2495904/KinematicBoxBetweenTwoOthers.zip)

### LINKED ISSUE #36432: Collision detection not always working using move_and_collide on KinematicBody2D with save_margin at 0.001
**Godot version:**
3.2 stable

**OS/device including version:**
Windows 10 x64

**Issue description:**
[Video showing the problem.](https://i.imgur.com/ndTF24V.mp4)
Collision detection is not always working using two KinematicBody2D objects with save_margin set to very low value like 0.001-0.004. In the gif above all three objects have save_margin at 0.001 and the only difference is a starting position.

**Minimal reproduction project:**
[CollisionBug.zip](https://github.com/godotengine/godot/files/4238398/CollisionBug.zip)
Don't forget to enable collision drawing in debugging menu.
Press up arrow key to move objects.

### LINKED ISSUE #37798: KinematicBody2D passing through tile when there is one cell between parallel tiles
**Godot version:** 3.2.1

**OS/device including version:** Ubuntu 19.10

**Issue description:**

KinematicBody2D passes through Tilemap when tiles are just one space from another. Look at this gif:

That doesn't happen when there is more than 1 cell of space.

**Steps to reproduce:**

1) Create a KinematicBody2D
2) Setup a Tilemap (16x16 tile size)
3) Create two rows of parallel tiles just one space from one another.
4) Set safe-margin to 0.001 (minimal) in the KB2D
5) Set the velocity to be 16 per frame, so it walks snapping to the cell size.
6) Test collisions.

**Minimal reproduction project:** 
https://github.com/raphaklaus/tilemap-godot-issue

### LINKED ISSUE #43346: KinematicBody2D doesn't collide with group of one way collision bodies
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

A KinematicBody2D enters the corner of a one way collision static body and doesn't register as a collision, which allows it to go through another one way collision static body that it will usually collide with.

phase

It's expected to hit the right-most one way collision static body, as shown when the left one is disabled.

collision

**Steps to reproduce:**

Run the test project.

**Minimal reproduction project:**

[test_move_one_way_diagonal_phase.zip](https://github.com/godotengine/godot/files/5498546/test_move_one_way_diagonal_phase.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, in Godot physics 2D and 3D, `test_body_motion()` sometimes fails to extract collision information, which results in the collision being ignored. This problem is aggravated when the collision margin is reduced. The most common reason for reducing collision margins is to overcome the problem that touching, but not overlapping objects are treated as colliding. This PR ensures:
1. Collision information is always correctly extracted regardless of the size of the collision margin
2. Touching, but not overlapping objects are not treated as colliding

Fixes #16414
Fixes #23140
Fixes #36432
Fixes #37798
Fixes #43346
Addresses [comment](https://github.com/godotengine/godot/pull/34219#issuecomment-578092722)

Although these issues all have the same source, fixing them required making multiple changes:
- Removing the dependence on a minimum contact depth
- Removing collision solver checks for a minimum penetration
- Preventing zero overlaps from being detected as collisions
- Ensuring that the 3D Godot physics static and distance collision algorithms treat zero pixel overlaps the same

To facilitate these changes this PR has refactored Godot 2D and 3D `SpaceSW`, the Godot GJK EPA API and the Godot 3D `solve_distance()` algorithm. I have kept all these changes in separate commits to facilitate review and potential future troubleshooting (the refactoring changes modified a lot of lines of code, but they should not change behaviour).

The refactoring of `SpaceSW` is comprehensive. To isolate the disparate issues, the code was standardised, which involved:
- Removing duplicated code, unnecessary loops and unnecessary checks
- Adding missing checks and generating appropriate errors
- Making all functions across 2D and 3D as similar as possible.
- Changing variable names so the code is easier to understand.

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge of #42574.

**Comment by madmiraal** [comment]
Rebased following merge of #43923.

**Comment by madmiraal** [comment]
Rebased following merge of #45519.

**Comment by madmiraal** [comment]
Rebased following merge of #37547.

**Comment by madmiraal** [comment]
Rebased following merge of #45852.

**Comment by madmiraal** [comment]
Rebased following merge of #45854.

**Comment by Emalton** [comment]
Is this something that can be merged? It appears like it could fix this type of behavior?
https://i.imgur.com/fdlxuTg.gif

**Comment by YuriSizov** [comment]
A lot of the linked issues have been addressed in other PRs, and this hasn't been updated in a while. So I think this needs to be remade against the current master to only fix the remaining issues.

**Comment by Emalton** [comment]
@madmiraal Could you rebase your? Many of the issues you listed have been fixed already, but #23140 and #43346 are still not fixed so it would be great if your fixes could be upstreamed!

**Pull request closed without merging**
