### PR TITLE
[WIP] Improve code editor status bar to make it more readable, specially when with long error messages

### PR DESCRIPTION
**Pull request by mateusfccp**
Possible solution for #22302.

I changed status_bar to VBoxContainer and added a children HBoxContainer to contain warning line alone. The result was the following:

captura de tela de 2019-01-02 13-04-17

The result is evidently better, but may not be the best solution, so feel free to reject if you think this way.

### CODE REVIEW

**Comment by akien-mga** [comment]
I think that's a lot of wasted space for people with wide monitors (16:9) which are the vast majority (as well as for short error messages):
screenshot_20190102_203837

This also seems to add some unused space below the "Warnings: .*" line, not sure why.

IMO the main issue is all those labels ("Warnings", "Font Size", etc.) taking way too much space. I would prefer to reduce their width, possibly by replacing their text by images (yellow alert icon for "Warnings", font icon for "Font Size", etc.).

**Comment by volzhs** [comment]
⚠️:4 | 🗛:12 (85%) | [36,24]
like this?

**Comment by akien-mga** [comment]
> warning:4 | 🗛:12 (85%) | [36,24]
> like this?

Something like that could be good yeah. I would use actual icons in Godot and not Unicode symbols though, so that we can make sure that they match the style of other icons, and also make them explicit using tooltips on the icon.

One thing to keep in mind though is that some space has to be left hardcoded to avoid having elements jumping all the time to the left and the right based on the width of currently printed characters. For example when going from line [99,24] to [100,24], everything would bump to the left. But even between [11,24] and [12,24], as "2" is usually wider than "1" in most fonts.

**Comment by mateusfccp** [comment]
> I think that's a lot of wasted space for people with wide monitors (16:9) which are the vast majority (as well as for short error messages):
> screenshot_20190102_203837
> 
> This also seems to add some unused space below the "Warnings: .*" line, not sure why.
> 
> IMO the main issue is all those labels ("Warnings", "Font Size", etc.) taking way too much space. I would prefer to reduce their width, possibly by replacing their text by images (yellow alert icon for "Warnings", font icon for "Font Size", etc.).

Well, maybe the ideal should be to have some kind of responsive layout? Keep it horizontal on wider screens and break it on smaller.

**Comment by volzhs** [comment]
responsive layout even better as you said.

**Comment by mateusfccp** [comment]
Well, I'm going to make changes to use icons instead of text. However, I don't think it's going to solve the issue attached, as in small monitors like mine it will still break. I suggest the following changes:

1. Substitute text with icons
2. Reduce font size (it's really big)
3. Make the `status_bar` go under method list
4. Make the `status_bar` responsive so it breaks when on small screens

**Comment by mateusfccp** [comment]
I'm working on the given hints and I already implemented the icons, the font resize and the responsive layout. About the last, we have to decide what would be a good threshold for the layout break.

output

I'm, however, having problem with alignment. No matter how I try, I can't align the content within the `HBoxContainer`. Also, there are a large space in the labels within `HBoxContainer`. Indeed, the space for the line/col counters are proposital as they are need as @akien-mga said, but the width of the brackets and the comma are not intended to left this much space, and I also can't find a way to remove it.

captura de tela de 2019-01-04 12-33-23

**Comment by mateusfccp** [comment]
Other possibility is to, instead of breaking the line when on a specific resolution, break it when the error label line count is greater than a specific number.

**Comment by eon-s** [comment]
If this can be added to 3, even as optional "experimental" feature, it would be great, because current style makes the error panel bigger than the code window on small screens.

**Comment by akien-mga** [comment]
Superseded by #25552.

**Pull request closed without merging**
