### PR TITLE
Load needed editor translation only on demand

### PR DESCRIPTION
**Pull request by ghost**
In master, `EditorSettings::EditorSettings()` loads all translations, which still (even with our latest optimizations) takes >= 500 ms in an optimized release build for the project manager and then the Godot main app. This PR loads the one translation table that is needed on demand:

- saves 2 times 500 ms
- saves time and memory by not loading all the other TR tables that will never be accessed

### CODE REVIEW

**Comment by volzhs** [comment]
does this PR load fallback translation?

**Comment by poke1024** [comment]
It should indeed as there's no change to the `TranslationServer`. This PR only affects the translations compressed inside `_editor_translations` using `editor/SCSub`, which AFAIK is not related to the rest of the translation engine. To test the fallback I probably need a string that is not localized in the main locale?

**Comment by volzhs** [comment]
@poke1024 

> To test the fallback I probably need a string that is not localized in the main locale?

yeap.

**Comment by poke1024** [comment]
So I tried to follow along http://docs.godotengine.org/en/stable/learning/workflow/assets/importing_translations.html and then use `tr`but somehow I can't any project translations this to work, even not with Godot 3.0 beta 2.

Anyway, this change is a tools-only change, as it only affects `EditorSettings`, I don't see how it could affect any translation functionality in the projects/runtime.

**Comment by volzhs** [comment]
oh. I see it.

**Comment by akien-mga** [comment]
Well the question is still valid for the editor translations though, does it still properly load the original EN string from editor.pot when there is no localized string?

**Comment by poke1024** [comment]
I'm very sure yes, as no code from outside `EditorSettings` can access any of these other translations, since I've removed the vector for it, and there are no getters, and it still compiles, so it all needs to happen in the one `Ref<Translation>` passed out from `EditorSettings`. Going to hunt for a non-localized string in the German translation to prove this :-)

**Comment by poke1024** [comment]
Fallback works, here's a screenshot from the "da"nish translation:

danish

I believe now that this works as follows: if `TR(x)` does not find anything useful in the current translation, use `x`. Not even sure if `editor.pot` is ever used in the building of `_editor_translations`.

**Comment by akien-mga** [comment]
> I believe now that this works as follows: if TR(x) does not find anything useful in the current translation, use x. Not even sure if editor.pot is ever used in the building of _editor_translations.

Good point. Thanks for checking :)

**Comment by akien-mga** [comment]
Great work, thanks!

**Pull request merged**
