### PR TITLE
[iOS] Fix multitouch not working correctly

### LINKED ISSUE #58550: Multitouch not working in 3.4.3 Release in iOS
### Godot version

Godot 3.4.3 Release

### System information

iOS 15.2.1 / iPhone SE / OpenGL ES 2.0 Renderer: Apple A9 GPU

### Issue description

First there were big glitches with touches in 3.4.3 RC 2 and I couldn't test multi-touches in it because of this issue - #58274

In the new version, this problem was fixed, but multitouch does not work completely.

### Steps to reproduce

The problem concerns both the _input and the SreenTouchButton events.

I have no way to run deeper tests to find out the cause of the problem, but this again prevents me from releasing the game for iOS...

### Minimal reproduction project

Any project with touch input control.

### PR DESCRIPTION
**Pull request by naithar**
Fixes https://github.com/godotengine/godot/issues/58550.
Enabled `GodotViewGestureRecognizer` to connect multiple touches to the view it's connected to.

Can be cherry-picked to the `3.x` and `3.4` branches.

### CODE REVIEW

**Review by Harry-Hopkinson — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]
I do not have any iOS device to test multitouch, but this change seems fine.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.4.

**Pull request merged**
