### PR TITLE
Add PS3 controller guide button

### PR DESCRIPTION
**Pull request by j8r**
This adds the guide button to the PS3 controller. It is the button 10 with my DualShock 3 Sixaxis.
This might be different for other models, for example the original Sixaxis.
At worst, the mapping will be incorrect, which likely means not doing anything.

### CODE REVIEW

**Comment by j8r** [comment]
I could have added this precision. This the the mapping for the browser Gamepad API, used by webapps, not the one for the native SDL library used by desktop applications.
[godotcontrollerdb.txt](https://github.com/godotengine/godot/blob/master/core/input/godotcontrollerdb.txt) is different from [gamecontrollerdb.txt](https://github.com/godotengine/godot/blob/master/core/input/gamecontrollerdb.txt), even though browsers themselves can use SDL.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.

**Pull request merged**
