### PR TITLE
Fix Context Validation Layer Errors

### LINKED ISSUE #41614: GUI unresponsive on Godot 4 (regression from the NVIDIA Linux 450.66 driver and later)
***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

> **Workaround: Enable *Single Window Mode* in the Editor Settings, or use the `--single-window` command line argument and open a project directly by specifying the path to its `project.godot` file.**
>
> If you can't get to the checkbox, open `$HOME/.config/godot/editor_settings-4.tres` and add this line:
>
> ```tres
> interface/editor/single_window_mode = true
> ```

___

**Godot version:** v4.0 Git commit f10c3810bb0abfa18b1a579ee927f460bf191b6d

**OS:** Archlinux latest (NVIDIA GTX 1060, 64 GB RAM, Intel Core i7)

**Issue description:** When initialize godot UI modals remains unresponsive

**Steps to reproduce:**

- Compile godot
- Open godot
- Create a new project
- Specify directory
- UI remains unresponsive
Godot bug UI unresponsive

*Bugsquad edit (keywords for easier searching): crash, crashing, freeze, freezing*
*Windows counterpart of this issue: https://github.com/godotengine/godot/issues/45325*

### LINKED ISSUE #49937: Attempting to edit `ShaderMaterial` leads to editor freezing
### Godot version

~92f75046378a63b46946e8acbd7c224f027ebfa5~ bde6f5eed1cec3639e5c81d1e5ee34ecf3fe7486

### System information

Windows 10

### Issue description

Attempting to edit a shader cause editor freeze with the following spam to console:

image

The error is:
```
ERROR: Condition "err" is true. Returning: ERR_CANT_CREATE
   at: VulkanContext::prepare_buffers (drivers\vulkan\vulkan_context.cpp:1728)
```

call stack:

```
 	godot.windows.opt.tools.64.exe!VulkanContext::prepare_buffers() Line 1729	C++
 	godot.windows.opt.tools.64.exe!RenderingDeviceVulkan::prepare_screen_for_drawing() Line 8137	C++
 	godot.windows.opt.tools.64.exe!RendererViewport::draw_viewports() Line 623	C++
 	godot.windows.opt.tools.64.exe!RenderingServerDefault::_draw(bool p_swap_buffers, double frame_step) Line 115	
 	godot.windows.opt.tools.64.exe!Main::iteration() Line 2539	C++
 	godot.windows.opt.tools.64.exe!OS_Windows::run() Line 622	C++
 	godot.windows.opt.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 163	C++
 	godot.windows.opt.tools.64.exe!_main() Line 187	C++
>	godot.windows.opt.tools.64.exe!main(int argc, char * * argv) Line 199	C++
```

### Steps to reproduce

Create a simple scene with a mesh, assign `ShaderMaterial` to material override property and try open it.

### Minimal reproduction project

[ShaderTest.zip](https://github.com/godotengine/godot/files/6721099/ShaderTest.zip)

### PR DESCRIPTION
**Pull request by reduz**
* Multisampling was wrongly selected, possibly fixes #49937
* Image semaphore acquisition is now per window, possibly fixes #41614

Please make sure to test the above two issues again, since I can't reproduce either anyway.

### CODE REVIEW

**Comment by reduz** [comment]
Tested on NVIDIA 1050 (mobile GPU) and NVIDIA 1650 (desktop GPU). No longer freezes, #41614 seems solved finally.

**Comment by Calinou** [comment]
This seems to fix the freezing on my Fedora 34 + GeForce GTX 1080 setup. :+1:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by SaracenOne** [comment]
Seems to also resolve this issue #49933

**Comment by voxelv** [comment]
Fixes freezing on my GTX 970 :tada:

**Pull request merged**
