### PR TITLE
freetype: Update to upstream version 2.11.1

### PR DESCRIPTION
**Pull request by akien-mga**
I did not include the new `src/dlg` folder as it seems needed only for `FT_DEBUG_LOGGING` which we don't define.

There's a new `src/sdf` feature which we now compile, though I haven't checked if it's actually enabled.

Changes: 
- https://sourceforge.net/projects/freetype/files/freetype2/2.11.0/
- https://sourceforge.net/projects/freetype/files/freetype2/2.11.1/

### CODE REVIEW

**Comment by akien-mga** [comment]
CI seems to crash on Windows. The backtrace is a bit weird as it points at `TestBasis`, but then `CodeEdit`:
```
 ================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.0.dev.custom_build (40d39b8c8c35fc92150a49216dec6f6d31497ff0)
Dumping the backtrace. Please include this when reporting the bug on godotengine/godot/issues
[0] af_loader_load_glyph (D:\a\godot\godot\thirdparty\freetype\src\autofit\afloader.c:306)
[1] af_autofitter_load_glyph (D:\a\godot\godot\thirdparty\freetype\src\autofit\afmodule.c:489)
[2] FT_Load_Glyph (D:\a\godot\godot\thirdparty\freetype\src\base\ftobjs.c:978)
[3] TextServerAdvanced::font_get_glyph_advance (D:\a\godot\godot\modules\text_server_adv\text_server_adv.cpp:2271)
[4] Font::get_char_size
[5] TextEdit::Text::invalidate_cache
[6] TextEdit::Text::invalidate_all
[7] TextEdit::_update_caches
[8] TextEdit::TextEdit
[9] CodeEdit::CodeEdit
[10] TestBasis::EulerToBasis
[11] doctest::Context::run
[12] test_main
[13] Main::test_entrypoint (D:\a\godot\godot\main\main.cpp:507)
[14] widechar_main
[15] _main
[16] main
[17] __scrt_common_main_seh (d:\a01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[18] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

**Comment by bruvzg** [comment]
Not sure what was wrong with CI, I was not able to reproduce this crash. But `2.11.1` is released anyway, probably this should be updated and re-tested.

**Comment by akien-mga** [comment]
Updated to FreeType 2.11.1.

> I did not include the new `src/dlg` folder as it seems needed only for `FT_DEBUG_LOGGING` which we don't define.

I actually had not properly removed that folder initially, now fixed. Also removed `include/dlg`.
That's imported from Boost so not including it saves us from having to also document the Boost license.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
