### PR TITLE
Fix simultaneous touches for different touch types in iOS

### LINKED ISSUE #60190: Multitouch with Apple Pencil + Finger does not work
### Godot version

3.4.4

### System information

Ipad 8th generation with OS 14.6

### Issue description

Cannot use Apple Pencil + Finger at the same time, only when one is released that the other starts to work.

Finger + Finger works fine.

### Steps to reproduce

Run the Game of Life (Shader) sample (see below)

### Minimal reproduction project

https://godotengine.org/asset-library/asset/842

### PR DESCRIPTION
**Pull request by pfeodrippe**
Fixes https://github.com/godotengine/godot/issues/60190.

It enables simultaneous touches for different touch types. For example, the user will be able to receive input events from both the apple pencil and the user finger.

### CODE REVIEW

**Comment by pfeodrippe** [comment]
I've tested using the 3.4 branch (as I didn't see apple press in `master`) and it works.

**Comment by pfeodrippe** [comment]
If approved and merged, can we cherry-pick it to the 3.4 branch?

**Comment by akien-mga** [comment]
CC @naithar @bruvzg

**Review by naithar — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.5.

**Pull request merged**
