### PR TITLE
Replace Array return types with TypedArray (part 2)

### PR DESCRIPTION
**Pull request by KoBeWi**
Follow-up to #63959

Supersedes #60053 and #60054

Right now it doesn't compile, because it depends on #63959 being merged first.

### CODE REVIEW

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Looks good to me, we should look into merging all of those.

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by akien-mga** [comment]
The .NET glue generation seems to fail:
```
ERROR: Return type from getter doesn't match first argument of setter for property: 'RDUniform._ids'.
   at: _generate_cs_property (modules/mono/editor/bindings_generator.cpp:1785)
ERROR: Failed to generate property '_ids' for class 'RDUniform'.
   at: _generate_cs_type (modules/mono/editor/bindings_generator.cpp:1510)
ERROR: Generation of the Core API C# project failed.
   at: generate_cs_api (modules/mono/editor/bindings_generator.cpp:1324)
ERROR: --generate-mono-glue: Failed to generate the C# API.
   at: handle_cmdline_options (modules/mono/editor/bindings_generator.cpp:3862)
```

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
