### PR TITLE
Remove dead code from Viewport::_gui_input_event

### PR DESCRIPTION
**Pull request by dozingpip**

### CODE REVIEW

**Review by EricEzaM — APPROVED** [review]
Noticed this a while back but never actioned :P thanks!

what about that commented out stuff just below?

**Comment by mhilbrunner** [comment]
reduz about the dead code in this class:
> I am wondering whether this is dead code or unimplemented after the move to DisplayServer
it seems i entirely forgot about it
I would be happy if either groud, KoBeWi, Yeldham or pycbouh can take a look to see if nothing looks out of place there and there is no reason to keep it, as my memory of all that areas is pretty hazy right now

**Comment by mhilbrunner** [comment]
cc @groud / @KoBeWi / @YeldhamDev / @pycbouh see reduz comments above :) Sorry for the pings!

**Comment by groud** [comment]
I am not very familiar with the input handling in Viewport, but it seems that the event is set as handled anyway later on in the code, while it also seems that nothing checks for whether the event was handled or not in between.

So indeed, it looks like dead code, and I can't deduce what it could have been useful for. So I guess a removal is fine.

**Comment by KoBeWi** [comment]
The commented-out code is 4+ years old, so it's fine to remove it too.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks!

@EricEzaM
> what about that commented out stuff just below?

There is a lot of dead code in Viewport, I'll see about cleaning that up more in a seperate PR.

**Pull request merged**
