### PR TITLE
Add editor icons for Occluder3D and OccluderInstance3D

### PR DESCRIPTION
**Pull request by Calinou**
This "eclipse" design was suggested by @pycbouh.

## Preview

image

<details>
<summary>Old revision of this PR</summary>

image
</details>

### CODE REVIEW

**Comment by YeldhamDev** [comment]
That looks like it would be a little too similar to the `Node3D` icon when smaller.

**Comment by pycbouh** [comment]
> That looks like it would be a little too similar to the `Node3D` icon when smaller.

We can go for a different shape, I guess?

**Comment by Joakker** [comment]
Why not make it a square on the inside? It's more easily differentiated, and you still preserve the idea of the original

**Comment by SlothDevLlama** [comment]
another option would be to make the eclipse even more obvious
like so:
image

**Comment by Calinou** [comment]
> another option would be to make the eclipse even more obvious
> like so:

Done, thanks for the idea :slightly_smiling_face:

The exact design is slightly different to make it more aligned to the pixel grid.

**Comment by SlothDevLlama** [comment]
@Calinou very good job! Looks crisp now :-)

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
