### PR TITLE
fix stb font property names

### PR DESCRIPTION
**Pull request by sanikoyes**

### CODE REVIEW

**Comment by slapin** [comment]
I think a few words on the PR and/or patch about what is actually done would be nice.

**Comment by bojidar-bg** [comment]
Well, to me it looks like it namespaces the DynamicFont's properties, so :+1:

**Comment by slapin** [comment]
I see this too, but it should not require looking into actual patch to understand what it does,
the comments should not be vague, not that it is always require details. but at least
what is done should be there. This particular phrase doesn't tell us that it is namespace fixup
of font properties, this is why I'm complain here. I have no complains about code itself, just
that I'd like to see good commit comments even for small changes.
The commit comments are a part of documentation. They tell us when and why the change was performed. Later in future, when digging some bug one will thank people who write proper comments
(and curse ones who did not). So the questions which commit comment should answer:
1. Why the change was performed. If it is a bug fix, then the bug title and number should be quoted
or in any other words rephrased the reason, or state before bug. This can be obvious to author, but
it is not for  a person, who looks at commit, which might happen a few months later.
2. What is the actual change - if it is some simple operation, like "rename", it should be indicated.
If it is something complex, like algorithm change, the whole idea in a few short phrases should be
recorded in the commit - you will be happy you did this.
3. What are the consequences, if any, from this change. The most important is side effects (API changes, behavior changes, etc.), also other results of change (tests passed, bugs fixed or partially fixed, etc.)

about 3. sometimes work on bug consists of several commits or several PRs, as the issues can be complex, and can't be fixed from one touch, so the result of commit might not mean that the issue is fixed, but the situation is somewhat improved or the base for a fix is prepared, Sometimes no change at all is intended behavior (i.e. refactoring). So indicating the consequences is important too.
The idea is that viewing git log you should not need to go check the bugs to see what is going on
and view actual change to guess what is changed and what side effects might be. When you debug regression such uninformative commits really slow you down and are major annoyance factor.

Thank you for understanding.

**Comment by reduz** [comment]
@sanikoyes Thanks! It seems I forgot to change the STB version. I also added a Fallback system in the Freetype version, not sure if you need that added too

**Comment by slapin** [comment]
@sanikoyes and thanks for the fix

**Pull request merged**
