### PR TITLE
Fix Standard Gamepad Mapping triggers

### PR DESCRIPTION
**Pull request by j8r**
The trigger mappings were incorrect for Chromium-based browsers.
The triggers are indeed axes in Firefox, but here there are buttons, even though their values are decimals.

I tested on Linux and Windows on the browser console with this code, after half-pressing a trigger:
```js
navigator.getGamepads().forEach((gamepad) => {
  if (gamepad) {
    console.log(gamepad.buttons[6].value, gamepad.buttons[7].value)
  }
})
```

### CODE REVIEW

**Comment by akien-mga** [comment]
Does it still work in Firefox after the change?

**Comment by j8r** [comment]
Note that I don't use Godot, I use the Gamepad API directly.

Firefox must not use `Standard Gamepad Mapping`, at least with all the controllers I tested on Linux.
One can add a `console.log(gamepad.mapping)` in the loop in the above example, it should return empty string - and `"standard"` on Chromium.
I haven't tested on Firefox on Windows though, only Linux.

In Firefox controllers like the PS3/PS4/Xbox ones (and likely others I haven't tested) must use their "dedicated" mapping, but in Chromium they will all have the same mapping, the `Standard Gamepad Mapping`.

**Comment by j8r** [comment]
Ok I tested on Firefox Windows. Unlike Firefox Linux, it behaves like Chromium Windows/Linux: it uses the `"standard"` mapping, and have thus the exact same issue as Chromium Windows.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.

**Pull request merged**
