### PR TITLE
Ensure OpenXR classes are declared properly

### LINKED ISSUE #70853: Object allocation is slower since 4.0.beta9
### Godot version

v4.0 beta9

### System information

Windows 11, 64bit

### Issue description

Since migrating from Beta 8 to Beta 10, I've noticed a serious performance hit. I've tracked the problem down to a place where I'm creating a couple thousand objects. The object allocation used to take a couple microseconds, but ever since Beta 9 it takes hundreds of microseconds to construct a new object.

### Steps to reproduce

Create a plain Godot class that extends Object. Create a few thousand of them. It takes a while. 

### Minimal reproduction project

[AllocationExample.zip](https://github.com/godotengine/godot/files/10333611/AllocationExample.zip)

### LINKED ISSUE #73936: Custom objects are slower to instantiate in Godot 4.0 GDScript compared to Godot 3.5.1
### Godot version

~~4.0 RC 3~~ 4.0 RC 5

### System information

Ubuntu 22.04.2 LTS, Intel® Core™ i7-8700K CPU @ 3.70GHz × 12, AMD® Radeon rx 6700 xt

### Issue description

Apologies if this is a duplicate issue or a known feature of the new engine, I didn't discover anything with the same description in the bug tracker or the noted in the documentation.

I noticed that some code I ported from Godot 3.5 was significantly slower in Godot 4.0 RC 3. I whittled down the issue to the instantiation of a large number of custom defined objects that I was using.

Instantiating 10000 custom objects in Godot 3.5.1 might take around 15 milliseconds. Doing the same thing in Godot 4.0 RC 3 takes over a second on my hardware. The difference seems significant enough to me to wonder if this something that I will need to work around in Godot 4, or if it will be reverted in future.

### Steps to reproduce

Writing a script in godot 3.5 that instantiates 10000 objects, custom objects (and for comparison custom resources), out puts some reasonable times:

**Godot 3.5.1 Script**:
```gdscript
class CustomObject extends Object:
	pass

class CustomResource extends Resource:
	pass

func _ready():
	var test_func_names = [
		"test_10000_objects",
		"test_10000_custom_objects",
		"test_10000_custom_resources",
	]
	for test_func_name in test_func_names:
		var test_func = funcref(self, test_func_name)
		var start_time: int = Time.get_ticks_usec()
		test_func.call_func()
		print("%s ran in %d usecs" % [test_func_name, Time.get_ticks_usec() - start_time])

func test_10000_objects():
	var test_array: Array = []
	for _i in range(10000):
		test_array.append(Object())

func test_10000_custom_objects():
	var test_array: Array = []
	for _i in range(10000):
		test_array.append(CustomObject.new())

func test_10000_custom_resources():
	var test_array: Array = []
	for _i in range(10000):
		test_array.append(CustomResource.new())

```

**Godot 3.5.1 Output**:
```text
Godot Engine v3.5.1.stable.official.6fed1ffa3 - https://godotengine.org
OpenGL ES 3.0 Renderer: AMD Radeon RX 6700 XT (navi22, LLVM 15.0.6, DRM 3.47, 5.19.0-32-generic)
Async. shader compilation: OFF
 
test_10000_objects ran in 784 usecs
test_10000_custom_objects ran in 15344 usecs
test_10000_custom_resources ran in 25674 usecs
```

Running a *similar*  script in Godot 4.0:

**Godot 4.0 Script**:
```gdscript
class CustomObject extends Object:
	pass

class CustomResource extends Resource:
	pass

func _ready():
	for test_func in [
		test_10000_objects,
		test_10000_custom_objects,
		test_10000_custom_resources,
	]:
		var start_time: int = Time.get_ticks_usec()
		test_func.call()
		print("%s ran in %d usecs" % [test_func.get_method(), Time.get_ticks_usec() - start_time])

func test_10000_objects():
	var test_array: Array = []
	for _i in range(10000):
		test_array.append(Object())

func test_10000_custom_objects():
	var test_array: Array = []
	for _i in range(10000):
		test_array.append(CustomObject.new())

func test_10000_custom_resources():
	var test_array: Array = []
	for _i in range(10000):
		test_array.append(CustomResource.new())
```

**Godot 4.0 RC 5 Output**:
```text
Godot Engine v4.0.rc5.official.6296b4600 - https://godotengine.org
OpenGL API 4.6 (Core Profile) Mesa 22.2.5 - Compatibility - Using Device: AMD - AMD Radeon RX 6700 XT (navi22, LLVM 15.0.6, DRM 3.47, 5.19.0-32-generic)
 
test_10000_objects ran in 1435 usecs
test_10000_custom_objects ran in 1147367 usecs
test_10000_custom_resources ran in 12831 usecs
```

### Minimal reproduction project

It's probably unnecessary, but I've included small projects that reproduce the issue with both Godot 4.0 RC 3 Forward+ and Compatibility set:

- [InstancingTestG4RC3Compatibility.zip](https://github.com/godotengine/godot/files/10831769/InstancingTestG4RC3Compatibility.zip)
- [InstancingTestG4RC3Forward.zip](https://github.com/godotengine/godot/files/10831770/InstancingTestG4RC3Forward.zip)

And I've also included a version of (more or less) the same code in Godot 3.5 as a comparison:

- [InstancingTestG35OpenGLES3.zip](https://github.com/godotengine/godot/files/10831773/InstancingTestG35OpenGLES3.zip)

### LINKED ISSUE #81014: Object is many times heavier than Node or RefCounted...?
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.3141) - Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 Threads)

### Issue description

I was perplexed with my game's memory usage. Basically, I have a dictionary of tile objects, the keys are all Vector2i.
Even fairly small maps (180x180 / ~32,400 tiles) were taking over 2GB of memory. I was considering switching over to dictionaries instead of using objects...
But, I decided to try using RefCounted as Tile's base type instead of Object, and the game's memory usage dropped from over 2GB to just around 80MB. Even if I made the tiles Nodes and added them as children of the test scene, the game's memory usage was sitting at 120MB.
I used Object thinking it would be the most efficient solution, only to be faced with this bizarre behavior. I'd think this must be a bug, there's no other explanation for this behavior. I thought it might be something to do with how they're allocated in the context of a dictionary or something like that, but nope, pushing them all into an array presents the same issue. Just changing the base type of the `Tile` class (which at this point is empty, by the way) to RefCounted or Node totally fixes the issue.

### Steps to reproduce

Make a scene and two scripts.
The first script should just look like this:
```GDScript
class_name MyObject
extends Node
```
Then, in the scene's script, paste this in:
```GDScript
extends Node

var objects = []

func _ready():
	for i in 32400:
		var object = MyObject.new()
		objects.append(object)
	print(objects.size())
```
The memory usage should be fine. Even better if RefCounted is used.
But try switching the base type of MyObject to Object, and if there's nothing wrong with my machine, your memory usage should soar to over 2GB and the scene take significantly longer to load.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
* Fixes: #81014
* Fixes: https://github.com/godotengine/godot/issues/73936
* Fixes: #70853

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Copying my question from the other PR:

@BastiaanOlij Since we're exposing this class properly now, it's worth thinking about the name. We use "metadata" as a single word throughout the Godot API, and this one is the only one using "meta data" (`MetaData` in the class name).

Is this a name derived from the OpenXR API, or something we chose ourselves? If the latter, it could be worth standardizing on `Metadata` / "metadata".

**Comment by BastiaanOlij** [comment]
> @BastiaanOlij Since we're exposing this class properly now, it's worth thinking about the name. We use "metadata" as a single word throughout the Godot API, and this one is the only one using "meta data" (MetaData in the class name).

@akien-mga nope, thats just me not knowing we wrote that as one word :) I'm more than happy with that change.

**Review by BastiaanOlij — APPROVED** [review]
lgtm, just akiens requested change to make meta data -> metadata

**Comment by akien-mga** [comment]
There's a use of "meta data" in the doc file, which would be worth changing too. Actually, there's a few more, most in OpenXR code, which we could change:
```
doc/classes/OpenXRInteractionProfileMetadata.xml:		This class allows OpenXR core and extensions to register meta data relating to supported interaction devices such as controllers, trackers, haptic devices, etc. It is primarily used by the action map editor and to sanitize any action map by removing extension-dependent entries when applicable.
modules/openxr/doc_classes/OpenXRInteractionProfile.xml:		This object stores suggested bindings for an interaction profile. Interaction profiles define the meta data for a tracked XR device such as an XR controller.
modules/openxr/openxr_api.cpp:	// If the io_path is not part of our meta data we've likely got a misspelled name or a bad action map, report
servers/xr/xr_interface.h:	enum Capabilities { /* purely meta data, provides some info about what this interface supports */
tests/scene/test_arraymesh.h:TEST_CASE("[SceneTree][ArrayMesh] Surface meta data tests.") {
```
(the `.po` file shouldn't be changed)

And finally, I also noticed that the doc file is in the wrong folder. It should be moved to the module's `doc_classes` (and for this to work, it should be listed in `modules/openxr/config.py`).

**Comment by AThousandShips** [comment]
Got it!

**Comment by AThousandShips** [comment]
I believe that's all now

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
