### PR TITLE
Fix `Color::get_{r,g,b,a}8`

### LINKED ISSUE #47022: `Color::get_{r,g,b,a}8()` use truncate instead of round
**Godot version:**
3.2.4-rc4, 4.0-dev

**OS/device including version:**
Kubuntu 20.10

**Issue description:**
These methods use truncate instead of round, which causes inconsistencies with `to_html` in some cases (see example below). Here are the code sections responsible for this:

https://github.com/godotengine/godot/blob/6eef187a81cbdd3cd314776de372e753f79f9831/core/math/color.h#L199-L206

https://github.com/godotengine/godot/blob/6eef187a81cbdd3cd314776de372e753f79f9831/core/math/color.cpp#L421-L441

**Steps to reproduce:**
```gdscript
tool
extends EditorScript

func _run():
    var c = Color.from_hsv(1/12.0, 0.25, 0.8)
    print(c.to_html(false))                    # ccb399
    print('%02x%02x%02x' % [c.r8, c.g8, c.b8]) # ccb299
```

**Minimal reproduction project:**
—

### PR DESCRIPTION
**Pull request by dalexeev**
Closes #47022.

### CODE REVIEW

**Review by aaronfranke — COMMENTED** [review]
This is good, but while we're changing these lines, this can be better. Color always uses 32-bit floats, so these should have `f` as a suffix (or we could also do `255` without the `.0` for the same behavior, but `255.0f` makes our intentions clear):

```cpp
	_FORCE_INLINE_ void set_r8(int32_t r8) { r = (CLAMP(r8, 0, 255) / 255.0); }
	_FORCE_INLINE_ int32_t get_r8() const { return int32_t(CLAMP(Math::round(r * 255.0f), 0.0f, 255.0f)); }
	_FORCE_INLINE_ void set_g8(int32_t g8) { g = (CLAMP(g8, 0, 255) / 255.0); }
	_FORCE_INLINE_ int32_t get_g8() const { return int32_t(CLAMP(Math::round(g * 255.0f), 0.0f, 255.0f)); }
	_FORCE_INLINE_ void set_b8(int32_t b8) { b = (CLAMP(b8, 0, 255) / 255.0); }
	_FORCE_INLINE_ int32_t get_b8() const { return int32_t(CLAMP(Math::round(b * 255.0f), 0.0f, 255.0f)); }
	_FORCE_INLINE_ void set_a8(int32_t a8) { a = (CLAMP(a8, 0, 255) / 255.0); }
	_FORCE_INLINE_ int32_t get_a8() const { return int32_t(CLAMP(Math::round(a * 255.0f), 0.0f, 255.0f)); }
```

**Comment by dalexeev** [comment]
Can we do this:

```cpp
_FORCE_INLINE_ int32_t get_r8() const { return CLAMP(int32_t(Math::round(r * 255.0f)), 0, 255); }
```
?

**Comment by aaronfranke** [comment]
The core devs did the opposite in this commit, so I don't think we should undo it: https://github.com/godotengine/godot/commit/771b3c583da1574c25f5aa49c5390a66f8ac1b3e#diff-338a6122d06ba451b648508685a84917a457cf904b0aa28e736c62fe4dd950b6R197

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
In #47022 you state that it affects `3.2.4-rc4` too, but the code seems different and does use `round` AFAICT:

https://github.com/godotengine/godot/blob/137f71fd75978249e6793803c6f808c84064b4e2/core/variant_op.cpp#L1664-L1671

https://github.com/godotengine/godot/blob/137f71fd75978249e6793803c6f808c84064b4e2/core/variant_op.cpp#L2507-L2518

If the issue is still reproducible in `3.x`, it likely needs a different fix.

**Comment by dalexeev** [comment]
@akien-mga The problem is reproduced in 3.3. But it seems that the reason is really something else. I can't figure out what.

**Pull request merged**
