### PR TITLE
Add subgraphing in VisualScript to create modular nodes

### PR DESCRIPTION
**Pull request by VikramSGIT**
Hey There!
I'm Vikram S. I would like to be a part of GSoc'22 contributors for Godot. I use this PR to showcase my ideas over this feature. Thank you

### CODE REVIEW

**Comment by theoway** [comment]
@VikramSGIT Let me know when it's ready for initial testing.

**Comment by fire** [comment]
Approved github actions.

**Comment by VikramSGIT** [comment]
For now only thing left is to integrate modules into the visual script editor.

image

I'm running into a issue. Idk if any new changes were made to EditorFileDialog.

**Comment by VikramSGIT** [comment]
I found a recent usage of the dialog [here](https://github.com/godotengine/godot/blob/04c17eb00389dff7add0459a5a4dd6e2886d3f05/editor/project_manager.h#L75). I'll look into it, hope that might fix.

**Comment by theoway** [comment]
> I found a recent usage of the dialog [here](https://github.com/godotengine/godot/blob/04c17eb00389dff7add0459a5a4dd6e2886d3f05/editor/project_manager.h#L75). I'll look into it, hope that might fix.

I'd recommend to first get only submodules working. After that, make a separate PR for additional features. Don't clutter everything in one PR, it'll be difficult for us to test everything in one PR.

**Comment by VikramSGIT** [comment]
For now the Visual Script loading issue has been solved. But crashes while creating a module.

**Comment by fire** [comment]
Can you provide a stack trace?

**Comment by akien-mga** [comment]
Closing as [we just removed VisualScript for 4.0](https://github.com/godotengine/godot/pull/64822), so this can no longer be evaluated as is.

The VisualScript module has been moved to https://github.com/godotengine/godot-visual-script with the aim that it might be ported to a GDExtension if there are interested contributors to do so. Further work to improve the features could be done on that repository too (so currently there isn't anyone dedicated to maintain this repository, it will depend again on whether some contributors step up to do so).

**Comment by Zireael07** [comment]
Subgraphing would be a big boost to visual script/visual shader usability, hoping it gets reopened.

**Comment by fire** [comment]
Subgraphing work will be in an Godot Engine proposal It's still wanted.

**Pull request closed without merging**
