### PR TITLE
Handle negative offsets better in AudioStreamPlayer

### PR DESCRIPTION
**Pull request by ghost**
When a negative offset is passed to AudioStreamPlayer::play or seek, the call would fail silently. This behavior is reasonable, but not very useful.

This adds a sane extension to the behavior, interpreting negative offsets as silent seconds before start. This would allow scripts to schedule audio ahead of time, compensating for the delay against the audio thread that _process introduces.

- - -

This is generally useful if one wants to play sounds in sync with a BPM that may or may not play well with the 60fps main thread.

For example, the adaptive music plugin [Godot-Mixing-Desk](https://github.com/kyzfrintin/Godot-Mixing-Desk) counts beats in _process for music transitions. However, the supposed point of transition can end up between two _process calls, introducing audible artifacts, especially with tracks that have prominent percussion parts, or with less than perfect framerates. This would allow it to schedule tracks a few frames before the transition, removing the lag.

### CODE REVIEW

**Comment by merumelu** [comment]
What about AudioStreamPlayer2D and AudioStreamPlayer3D?

**Comment by toasteater** [comment]
> What about AudioStreamPlayer2D and AudioStreamPlayer3D?

Looking at the code it does seem that they share the aforementioned behavior: silent failure. They can be modified to allow negative offsets as well, if such a functionality is desired.

**Comment by reduz** [comment]
I'm not completely sure why this is needed, is it not better to use AudioServer.get_output_delay to synchronize music with code? I am planning to write some documentation on using it properly.

**Comment by toasteater** [comment]
> is it not better to use AudioServer.get_output_delay to synchronize music with code?

@reduz It's less about output latency and more about the precision of `_process`. On most machines, `_process` is only called 60 times a second. That means without a way to schedule audio in advance, even if we compensate for the delay to the best of our ability, a difference of at most +-1/120 second (~+-8ms) that *fluctuates around* will always be present. It's the fluctuating part that makes it very noticeable to the ear, if you try to play some sound effect to each beat.

**Comment by toasteater** [comment]
Closing because I don't intend to continue working on this PR.

**Pull request closed without merging**
