### PR TITLE
register RenderingDevice as gdscript singleton

### PR DESCRIPTION
**Pull request by underdoeg**
Not sure if this is the intended use of the rendering device class but I did not see another way to interact with it

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Apparently that was wrong, it's not meant to be a singleton but it should be instantiated (`var rd = RenderingDevice.new()`).

**Comment by akien-mga** [comment]
Reverted by ff5dfcdf6.

@reduz has yet to fix the instantiation of local `RenderingDevice` instances, likely by moving `create_local_device()` to the `RenderingServer` singleton.

**Comment by underdoeg** [comment]
Ah I see. I thought local devices create their own context and to interact with the main one, You use the singleton

**Pull request merged**
