### PR TITLE
Remember Transform menu settings for the Spatial Editor

### PR DESCRIPTION
**Pull request by neikeq**
BTW, I followed the existing code and checked if `d.has("option")` before retrieving the option. But what's the point on doing so if there are ERR_FAIL_COND calls at the top that already do that?

### CODE REVIEW

**Comment by akien-mga** [comment]
> But what's the point on doing so if there are ERR_FAIL_COND calls at the top that already do that?

Good question. Should there be such fail conditions? Or should a default value be assigned if one of the state members is not defined?

**Comment by neikeq** [comment]
I was thinking about it. These fail conditions should be removed and just keep the default value if the option is not saved. Perhaps this should be done in a separate PR, since it would modify other plugins too (I still can remove the fail conditions of this PR though).

**Comment by neikeq** [comment]
Actually, in _/tools/editor/plugins/_ only the spatial editor plugin seems to has such fail conditions, should I remove them in this PR?

**Comment by akien-mga** [comment]
IMO you could remove the fail conditions yes, at least all those that have a default value if not set in set_state() (I guess all of them do, but it's worth double-checking)

**Comment by neikeq** [comment]
Done. **Viewport mode** is by default _MENU_VIEW_USE_1_VIEWPORT_, [established on ready](https://github.com/godotengine/godot/blob/3db379376fd55a1d5851bf6172affd0765b67b7c/tools/editor/plugins/spatial_editor_plugin.cpp#L3569). Not sure about each **viewport** though... I suppose it establishes its state by default too, because the first time the editor is run there may not be such saved states.

**Pull request merged**
