### PR TITLE
Script editor now automatically completes file paths in GDScript

### PR DESCRIPTION
**Pull request by mablin7**
I'm not sure this functionality is really desired by any other developers but for me, it was very helpful.
The completion turns on if you type in `load`/`preload` ~~or ` "res:` (in any function parameter),~~ and lists every file visible in the filesystem dock.
This might be annoying for some people, so I added an editor option for turning it off.
The only related issue I could find: #2982

### CODE REVIEW

**Comment by magyar123** [comment]
Oops, clang formatting

**Comment by bojidar-bg** [comment]
Can't we just get a `COMPLETE_PRELOAD` or `COMPLETE_PATH` instead of that rfind mess?

**Comment by reduz** [comment]
Indeed, that sounds better imo

**Comment by magyar123** [comment]
Actually haven't thought about it...
Will try that today

**Comment by magyar123** [comment]
Done

**Pull request merged**
