### PR TITLE
Cherry-picks for the 4.1 branch (future 4.1.4) - 1st batch

### PR DESCRIPTION
**Pull request by YuriSizov**
This is the first batch of two for the 4.1 branch. It includes ~almost~ every PR has been marked for cherry-picking and which is already included in 4.2:
https://github.com/godotengine/godot/pulls?q=is%3Apr+is%3Amerged+label%3Acherrypick%3A4.1+-label%3Acherrypick%3A4.2+sort%3Aupdated-asc+

~There are two more PRs fitting this criteria, but I need some help deciding on them. Can include them later, if we decide to pick them.~

The second batch is going to include all PRs which are currently marked for cherry-picking for both 4.1 and 4.2. After that we can start building RC1.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
Approving the doc picks

**Comment by YuriSizov** [comment]
That's more than enough for me :)

**Review by akien-mga — APPROVED** [review]
Looks good to me. Great work!

**Comment by YuriSizov** [comment]
Well that was timely! :D Thanks for reviews

**Pull request merged**
