### PR TITLE
Fix SortArray crashing with bad comparison functions

### LINKED ISSUE #3327: warn the user when the custom sort function isn't consistent
not always, but very often crashed on Windows 7.

``` gdscript
extends Node2D

func _ready():
    randomize()

    for i in range(20):
        var list = range(10)
        list.sort_custom(self, "shuffle_array")
        print(list)

func shuffle_array(a, b):
    return randi() % 2 == 0
```

I ran this code 20 times on Windows 7.
8 times good, and 12 times crashed.

1 of 30 crashed on Ubuntu 14.04.

and one more weird thing is sometimes element is missing.

``` gdscript
    for i in range(10): # changed 20 to 10
        var list = range(10)
        list.sort_custom(self, "shuffle_array")
        print(list)
```

this is on Windows 7.

```
9, 8, 4, 3, 2, 1, 6, 5, 7, 0
9, 8, 6, 5, , 0, 3, 1, 4, 7    > "2" is gone
8, 7, 4, 3, 6, 2, 0, 9, 1, 5
9, 5, 4, 3, 2, , 6, 8, 7, 0    > "1" is gone
9, 8, 7, 6, 2, 1, 0, 3, 4, 5
9, 8, 7, 6, 5, 0, 3, 1, 2, 4
4, , 2, 0, 8, 6, 9, 5, 7, 3    > "1" is gone
9, 8, 7, 5, 2, 0, 1, 3, 6, 4
7, 6, 1, 0, 4, 2, 8, 9, 5, 3
9, 7, 6, 4, 3, 2, 1, 0, 8, 5
```

this is on Ubuntu 14.04

```
8, 3, 2, 1, 0, 5, 7, 4, 6, 9
8, 6, 5, [], 1, 0, 2, 4, 7, 9
8, 6, 5, [], [], 0, 3, 4, 7, 9
9, 8, 7, 6, 4, 3, 2, 1, 0, 5
9, 8, 6, 5, 4, 2, 7, 0, 1, 3
8, 6, 5, 9, 4, 3, 7, [], 0, 2
5, 3, 2, 1, 0, 6, 4, 8, 7, 9
9, 6, 4, 2, 3, 7, [], 0, 5, 8
7, 6, 5, 4, 9, 2, 1, 0, 3, 8
7, 3, 2, 1, 6, 0, 4, 5, 8, 9
```

### LINKED ISSUE #10968: Problem with custom_sort
Hello, 

I'm on Windows 10 with godot 2.1.4

OK, so on my computer there is a bug with custom_sort. And its a very strange bug. Because it doesn't always happen, or its sometimes different in the way it happens. So I wrote a table that you can sort columns. But sometimes I get an error when I try to sort a column.

The easiest way to reproduce the problem is to try to sort the third column first, before sorting any of the other columns. If you sort the third column after you sorted the first or the second sometimes it works out fine.

[SortTest.zip](https://github.com/godotengine/godot/files/1275295/SortTest.zip)

### PR DESCRIPTION
**Pull request by ghost**
Fixes #3327
Fixes #10968

In master, `SortArray` crashes if the comparison function is not good (i.e. not totally ordered). Note that a comparator is already bad if it implements `<=` instead of `<`.

This PR prevents crashing with bad comparators and outputs nagging error messages instead (quite a lot, you won't miss them).

I ran an obligatory stress test against the sorter with good comparators for about 30 minutes, indicating that neither did the usual functionality got broken, nor does any of the three conditions this PR asserts as errors occur in normal operation:

```
extends Node2D

func _process(delta):
    test_sort()

func test_sort():
	randomize()
	var a = []
	for i in range(2 + (randi() % 1000)):
		a.append(randf())
	a.sort()
	for i in range(len(a) - 1):
		assert(a[i] <= a[i + 1])
```

## DETAILS

The sorting code is complex and relies on many implicit assertions, so here is some lengthy rationale why this is correct.

There seem to be three areas where problems with a bad comparison function could happen inside `SortArray` (note that I'm using Python slice notation, i.e. `x[a:b]` excludes `x[b]`):

(1) In `unguarded_linear_insert`.

With a totally ordered comparison function, `compare(p_value, p_array[next])` will never a return `true` here for `next == 0`.

For the sake of shortness, let's just state that if it did, the code would be erroneous, as `next--` would set `next` to `-1` and would next access the out-of-bounds `p_array[-1]` in the while head.

We can safely assume that if `compare` returns `true` for `next == 0`, the comparator is bad here.

Longer explanation: for good comparators, the condition just described (and checked for in this PR) will never happen:

* if  called from `linear_insert` this is achieved via checking `if (compare(val, p_array[p_first]))` before the call, thus `p_value` will never be smaller than some lower index element at `p_first >= 0`.
* if called from `unguarded_insertion_sort` there will have been a clever (bit obscure) partitioning via `introsort` beforehand (see `sort_range`) that always ensures some smaller item in the lower partition of the array (i.e. the call to `unguarded_insertion_sort(p_first + INTROSORT_THRESHOLD, p_last, p_array);` can never insert an item that will be smaller than all items in`p_array[p_first, p_first + INTROSORT_THRESHOLD]`).

(2) In `partitioner`.

In simple terms: `p_first`, going forward, must hit `p_pivot` (with a `false` compare) before going beyond the end of the partition range, and `p_last`, going backward, must hit `p_pivot` (with a `false` compare) before going before its beginning. If all compares, including the compares on the boundaries, return `true`, the comparator is bad.

Longer explanation: first note that for all calls of `partitioner`, `p_pivot` is always an element from `p_array[p_first:p_last]` (computed via `median_of_3`). 

That means there must an `x`, `p_first <= x < p_last`, such that `p_array[x] == p_pivot` and thus `compare(p_array[x], p_pivot) == false`.

The two `ERR_BAD_COMPARE` checks added by this PR check if the condition just stated fails, thus indicating that the comparator must be bad (e.g. for `p_first` this happens when `p_first` gets incremented until it reaches the original unmodified `p_last - 1` without hitting upon `p_pivot`).

Note that the `p_first++;` at the end of the `while` loop is always safe, as we know from `if (!(p_first < p_last))` before that `p_first < p_last < unmodified_last`, i.e. `p_first < unmodified_last - 1`, i.e. `p_first + 1 < unmodified_last`.

(3) The heap functions there should be no problem. `push_heap`'s loop is guarded by `parent`, and `adjust_heap`'s loop is guarded by `second_child`.

### CODE REVIEW

**Comment by reduz** [comment]
I don't really think it's a problem that it crashes, though the fix does not really seem to affect performance much. I prefer we merge this after 3.0 as it's not urgent

**Comment by vnen** [comment]
This should be a debug-only thing, right? Just to inform naive developers that the sort function must be consistent.

**Comment by poke1024** [comment]
I'm not sure. I'm not against having it in production as well, as the overhead is one additional register compare per iteration without memory access, which will be very hard to measure. While active, it can catch subtle errors in a comparator that might not crash otherwise but just produces wrong sort results (it can make it fail earlier than the crash). Godot has a lot of `ERR_FAIL` in production code, which is a similar approach.

**Comment by Zireael07** [comment]
I think it should go in production to avoid people's exported games crashing.

**Comment by poke1024** [comment]
@Zireael07 That was my idea as well.

**Comment by reduz** [comment]
I think I would do the following with this PR. Truth is that in some places this code is very performance critical (renderer), so the extra check is undesired. But it is true that for the case you mention (GDScript) it can be useful:
 
1. Add an extra template argument, by default false bool validate = false , so you can do if (validate)
2. When used from user code (Array in this case), create it with this set as true, otherwise leave as false.

**Comment by reduz** [comment]
And of course, enabling it always if DEBUG_ENABLED is true

**Pull request merged**
