### PR TITLE
Add an ERR_FAIL_COND when set_mesh is called with p_mesh == mesh

### LINKED ISSUE #11588: MeshInstance.set_mesh(MeshInstance) doesn't fail when not using static typing
Godot 2.1.3, Godot 3.0 master
Windows 10 64 bits

After 30 minutes of headbanging, I found the following code runs without producing any error:

```gdscript
var mi = MeshInstance.new()
mi.set_mesh(mi)
```

It should throw a type error.

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes #11588

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Shouldn't you add it for `mesh.is_null()`/`!mesh.is_valid()` instead?

**Comment by marcelofg55** [comment]
I think it shouldn't ERR_FAIL_COND on `!mesh.is_valid()`, because it can be called with `set_mesh(null)` to clear the value.
This fixes not throwing an error when incorrectly being called with self as the arg, like Zylann did:
```
var mi = MeshInstance.new()
mi.set_mesh(mi)
```

**Comment by bojidar-bg** [comment]
@marcelofg55 But, since MeshInstance does *not* inherit Mesh, calling `set_mesh(MeshInstance.new())` is equivalent to `set_mesh(null)`.

**Comment by marcelofg55** [comment]
Oh, okay, I see your point now, I'll fix the PR in a min..

**Pull request closed without merging**
