### PR TITLE
Fix pressing save in Import Defaults not working

### LINKED ISSUE #84248: After making changes to Project Settings, any changes are not saved to the project.godot file
### Godot version

v4.2.beta3.mono.official [e8d57afae]

### System information

Godot v4.2.beta3.mono - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX 580 Series (Advanced Micro Devices, Inc.; 31.0.21031.1005) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

After making a change to the Project->Project Settings->Import Defaults (tab)->Scene (option)->Embedded Image Handling value, and saving, the project.godot file did not update.

### Steps to reproduce

Create a new empty project

Go to this menu item
image

 Go to this tab and select this Importer
image

Change this option, click Save, then click Close
image

Close the project with Save & Quit and go back into the settings...the value did not update as expected
image

Video attached for reference

https://github.com/godotengine/godot/assets/28369028/efdca19b-c77d-47f8-8f74-d6b311d402e1

### Minimal reproduction project

Instructions above, don't believe an attached project is needed for this.
Please let me know if otherwise.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #84248

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

PS: Why do we have a **Save** button in that dialog in the first place? The usual approach in Godot is to save property changes automatically, but offer a way to undo/redo changes.

**Comment by jsjtxietian** [comment]
> Why do we have a **Save** button in that dialog in the first place?

I guess we have to ask reduz for that. Personally I think save property changes automatically is fine as .project file won't be too large.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
This is a regression from https://github.com/godotengine/godot/pull/80450, in 4.1 we still have the old signal and it should work fine. So a cherry-pick is not needed.

**Pull request merged**
