### PR TITLE
Updated Bullet version to the actual bullet master commit

### PR DESCRIPTION
**Pull request by AndreaCatania**
This PR updates the Bullet library to the last master branch commit 500264ca239d3fdf69162c75c5b40ee04baae458.

@akien-mga this PR is not yet merged, https://github.com/bulletphysics/bullet3/pull/2264, I'll do another PR once this is merged so in the meantime you can merge this one.

### CODE REVIEW

**Comment by akien-mga** [comment]
We don't need to add the CMakeLists.txt and premake files.

**Comment by akien-mga** [comment]
It looks like there are -Wreorser warnings still raised by Bullet headers.

**Comment by AndreaCatania** [comment]
I think that these flags, have to be disabled in thirdparty dir. However remove the unwanted file is possible, but is better to not do it, because the idea is to keep the bullet update easy like a drag and drop.

**Comment by akien-mga** [comment]
Try this maybe?
```diff
diff --git a/modules/bullet/SCsub b/modules/bullet/SCsub
index 16d694c23..2fe7a1b4c 100644
--- a/modules/bullet/SCsub
+++ b/modules/bullet/SCsub
@@ -186,7 +186,11 @@ if env['builtin_bullet']:
 
     thirdparty_sources = [thirdparty_dir + file for file in bullet2_src]
 
-    env_bullet.Prepend(CPPPATH=[thirdparty_dir])
+    # Treat Bullet headers as system headers to avoid raising warnings. Not supported on MSVC.
+    if not env.msvc:
+        env_bullet.Append(CPPFLAGS=['-isystem', Dir(thirdparty_dir).path])
+    else:
+        env_bullet.Prepend(CPPPATH=[thirdparty_dir])
     # if env['target'] == "debug" or env['target'] == "release_debug":
     #     env_bullet.Append(CPPFLAGS=['-DBT_DEBUG'])
```

**Comment by akien-mga** [comment]
I'll force push an update to this PR with this `-isystem` change, the current upstream master commit and unnecessary files removed.

**Comment by akien-mga** [comment]
Done, let's see if it passes CI now. At least locally it doesn't trigger errors for now with `werror=yes warnings=extra` and GCC 8.

**Pull request merged**
