### PR TITLE
[GDScript] Fix incorrect compound assignment

### LINKED ISSUE #75832: Multiplication of integer and float gives wrong result
### Godot version

4.1 61630d4

### System information

Windows 10 x64

### Issue description

```GDScript
var a := 1
a *= 1.0
prints("Result:", a)
```
Produces
```
Result: 4607182418800017408
```

Does not happen in 4.0 branch.

### Steps to reproduce

1. Run the code above
2. Observe the result

### Minimal reproduction project

N/A

### LINKED ISSUE #76041: Array += Array is broken
### Godot version

4.1.dev (4dcf2c5431ea6894c268c384df0d81e7fd96c341)

### System information

Debian Linux, rendering N/A

### Issue description

I noticed the following strange behavior on master as of 4dcf2c5431ea6894c268c384df0d81e7fd96c341:
```
func _ready():
        var list: Array = []
        list = [1,2,3,4]
        list += [1,2]
        print(list) # should print: [1,2,3,4,1,2] prints: [1,2]
        list += []
        print(list) # should print: [1,2,3,4,1,2] prints: []

        var list2: Array = [1,2,3]
        list += list2
        print(list) # should print: [1,2,...2,3] prints: [1,2,3]
```
It appears that `+=` overwrites the current data instead of appending.

FWIW, just writing `var list = []` doesn't trigger the problem. So it's likely something with type `Array`. `Array.append_array` doesn't suffer from the problem.

~~The problem is similar to #72948, however this involves not a typed array only the type Array, and I haven't seen an error. The data just disappears silently. But it might still be fixed by #73540. Haven't tested yet.~~

### Steps to reproduce

See issue description.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Reverts in-place compound assignments

Added test to ensure correctness

Added tests for array assignments as well, as per #76041

Found that this causes further bugs and decided to just revert the change and leave it up for future fixes as it seems very tricky and many pitfalls

This reverts #72056

Fixes #75832
Fixes #76041
Regression from #72056

### CODE REVIEW

**Comment by AThousandShips** [comment]
As this is a relatively destructive bug with very confusing effects and unpredictable I feel reverting is best, as it was a performance change

**Comment by vmedea** [comment]
i can confirm that this fixes #76041

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Pull request merged**
