### PR TITLE
Cherry-picks for the 4.1 branch (future 4.1.3) - 1st batch

### PR DESCRIPTION
**Pull request by YuriSizov**
This is probably the only batch for this release. I still need to update the changelog, but I can do it after this is merged, before starting the build.

### CODE REVIEW

**Comment by warriormaster12** [comment]
https://github.com/godotengine/godot/pull/82391 

Is it possible to add this pr to 4.1? It's small and it would help people who use SkeletonIk3D node but don't want to or can't switch to 4.2.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by YuriSizov** [comment]
> #82391
> 
> Is it possible to add this pr to 4.1? It's small and it would help people who use SkeletonIk3D node but don't want to or can't switch to 4.2.

Yeah, sure!

**Comment by YuriSizov** [comment]
Thanks for suggestions and reviews!

**Pull request merged**
