### PR TITLE
Revert #378b1e6 for s3tc

### PR DESCRIPTION
**Pull request by bruvzg**
Following up https://github.com/godotengine/godot/commit/378b1e6cf0cbcc9c30c61e0cabc7090f70fd380c and #10041

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you add a comment in the code about why the s3tc check can't be defaulted to true on GL core profile?

**Comment by Zireael07** [comment]
So what happens to the bugs 378b1e6 fixed?

**Comment by bruvzg** [comment]
@Zireael07 normal-map bugs are RGTC related and this PR only revert S3TC part.

**Comment by reduz** [comment]
wait, why did you guys revert S3TC? I did not know it was dictated by spec too so I Added there..

**Comment by reduz** [comment]
this merged PR sounds like bureaucracy gone wrong :P

**Comment by akien-mga** [comment]
@reduz It's patented, so not always included in core profile (at least not in the non-tainted version of Mesa), so we still need to detect it as it was done previously. It does not revert your previous commit, just the change that forced s3tc to true on desktop.

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/commit/378b1e6cf0cbcc9c30c61e0cabc7090f70fd380c#commitcomment-23508999

In a few months the patents expire though IIRC, so hopefully we can revert the revert then (though this commit also adds another fix for rgtc on mobile).

**Comment by reduz** [comment]
@akien-mga I understand, but RGTC is just S3TC too (a derivative), so it's the same thing.. detecting one and leaving the other on by default does not make much sense. 

We also have no alternative to provide to the non-tainted Mesa users, as Godot will fail if it does not find S3TC on desktop anyway.  I suggest just leaving both ones as turned on on desktop and not care about non-tainted Mesa users.

**Comment by reduz** [comment]
To make it clearer, Godot expects a compressed video texture format to be available for 3D to work, so 3D will not work (and never worked, since it was released as open source) for the non-tainted mesa users. As no one ever complained, the problem of the non-tainted Mesa users clearly does not exist :)

**Comment by akien-mga** [comment]
Ah ok, so I guess we should re-revert :) Not via git/GitHub revert though, as mentioned there is part of this commit which is still wanted. @bruvzg Can you do the change?

**Comment by bruvzg** [comment]
@akien-mga #10143

**Pull request merged**
