### PR TITLE
Tweak animation editor icon colors for easier visual grepping

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/54781.

This makes the Linear and Cubic icons in particular easier to distinguish from each other.

The Cubic interpolation icon's curve was also changed to be more distinguishable from the Linear icon's curve.

### Dark theme

| Before | After |
|-|-|
|  |  |

### Light theme

*Some icon color conversions are not working correctly – I don't know why.*

| Before | After |
|-|-|
|  |  |

### CODE REVIEW

**Review by fire — APPROVED** [review]
This is more recognizable. I pinged @lyuma and @TokageItLab for review too.

**Comment by fire** [comment]
I think that merging the new colours as is an improvement. The categories versus types of a category can be debated but not blocking. @TokageItLab Thoughts?

**Comment by TokageItLab** [comment]
@fire In any case, it's better than the current state. It is mergeable.

**Review by TokageItLab — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
