### PR TITLE
doc: Do not expose Variant::NIL as a type in the class reference

### LINKED ISSUE #12520: [DOCS] Nil constructors docs
The constructors for `Nil` show up in the docs, even though they seem to be inaccessible and do nothing (being void, not returning anything):

http://docs.godotengine.org/en/latest/classes/class_nil.html

Should those be removed somehow?

### PR DESCRIPTION
**Pull request by akien-mga**
Fix signals Variant arguments incorrectly listed as Nil.

Fixes #12520.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
`Nil` constructors are added in:
https://github.com/godotengine/godot/blob/1d64656f9edb6f2e45a5c2b38e47c4464d5e5096/editor/doc/doc_data.cpp#L540

Maybe just add a `if(i != Variant::NIL)` around that line?

**Comment by akien-mga** [comment]
I'm thinking to blacklist the whole `Nil` class as suggested by @vnen, I think that might be even better.

**Comment by bojidar-bg** [comment]
Wouldn't this break unfortunate random links to it, though?

**Comment by akien-mga** [comment]
> Wouldn't this break unfortunate random links to it, though?

There are none after this PR, the last occurrences were due to the bug handling signal arguments.

**Pull request merged**
