### PR TITLE
Get color constructor from ColorPicker

### PR DESCRIPTION
**Pull request by MarianoGnu**
Like this:
hue

### CODE REVIEW

**Comment by MarianoGnu** [comment]
Take a look @akien-mga

**Comment by bojidar-bg** [comment]
:+1: ²

**Comment by akien-mga** [comment]
That looks pretty cool :D I'd merge it already but I fear what will happen if I try to change the Color string and validate the input, so I'll test first ;)

**Comment by MarianoGnu** [comment]
Will ignore unless its a hexcode

**Comment by akien-mga** [comment]
> Will ignore unless its a hexcode

Indeed, I just tested and it works fine. I notice however that it discards the value and replaces it by `Color(0,0,0)` (or `000000` when giving a wrong hex value). Maybe you could make the LineEdit just do nothing if the input is wrong instead of discarding it? i.e. start by parsing the input, and if it's not wrong, make sure it's kept as the value for the LineEdit but return the function and do not try to change the latest colour picked.

**Comment by akien-mga** [comment]
It's a general enhancement idea though, can be done in another PR if you think it's a good idea (I also have a bug to report in another issue ;)).

**Comment by MarianoGnu** [comment]
Alien that behabiour was the same before this PR 😃

**Comment by akien-mga** [comment]
I know :) That doesn't mean that it's not worth changing ;)

**Pull request merged**
