### PR TITLE
Fix main window getting unfocused, when adding subwindows

### LINKED ISSUE #37531: Focus problems with popup menus
**Godot version:**
b50387c8b

**OS/device including version:**
Windows 10

**Issue description:**
The new popup menus will unfocus the editor, which leads to problems like this
image
These buttons no longer get hover event (you can see that different button is hovered from clicked). Also you always need to click them to open the menu.

It seems weird to me that the popup menus are basically sub-windows. I mean, uncofusing editor on menu open... I don't know any other application that does that.

### PR DESCRIPTION
**Pull request by HaSa1002**
It is an enhanced rebase of my previous attempt at fixing this problem in #38340 and therefore supersedes it. In order to achieve that, you have to tell the OS to not activate the window, but at the same time ensure, that the Input still gets to the window. 

supersedes #38340
fixes #37531

**Edit:** I am currently investigating different approaches. My notes: https://gist.github.com/HaSa1002/807444cc7334850a814a34251dff9af7

### CODE REVIEW

**Comment by HaSa1002** [comment]
now working on X11

**Comment by HaSa1002** [comment]
I added OSX support, but as I don't have one I don't know, if my changes had the desired outcome.

**Comment by bruvzg** [comment]
> I added OSX support, but as I don't have one I don't know, if my changes had the desired outcome.

Seems to work fine on macOS 11.2.2, OptionBox popups do not steel focus, and have working input.

**Comment by HaSa1002** [comment]
Ok. I remove the two unrelated commits then (they are relevant, but aren't needed in this PR) and mark this ready for review

**Comment by HaSa1002** [comment]
I implemented the feature for all relevant platforms (having multi-window support) and implemented a check that ensures correct behaviour, when subwindows are embedded. I moved some logic of the popup_menu up into the popup itself instead of leaving it there. That might be questionable. Appart from that the implementation is complete

**Comment by KoBeWi** [comment]
Tested on Windows 10
Works great, except the popup sometimes closes immediately after releasing button
O13dJ0SWeh

**Comment by HaSa1002** [comment]
@KoBeWi How long did you keep it pressed? This is desired behaviour in the popup menu, but only takes effect when you hold your mouse down for more than 500ms

**Comment by KoBeWi** [comment]
It seems to bug out after clicking randomly and closes even after short clicks (much less than 500ms). Maybe some timer isn't resetting properly?

Also, if you have popup open and hold button on another menu, you get 2 popups overlapping:
image

**Comment by HaSa1002** [comment]
Okay thanks. I try to reproduce this and track the issue. I have sort of an idea what is happening with the two popups, but I never experienced immediate closing popups.

**Comment by HaSa1002** [comment]
@KoBeWi I fixed your issues. The random click was because of the threshold being 100ms and if you click to slow it would be considered as a dragging click. I increased the threshold to 250ms. Perhaps this should be configurable, because people with movement disorders aren't able to click as fast. Idk.

**Comment by HaSa1002** [comment]
I just noticed that the PR exposes a bug with the input not being applied. Likely because of `NO_FOCUS` and some more stuff. I will investigate that the coming days.

**Comment by RandomShaper** [comment]
Isn't this approach like fighting against the windowing APIs too much, in a way that can break easily depending on the behavior of user and/or input devices? Maybe it is, and maybe even that's the only option, but, just in case, let me suggest the following:

The windowing API I know the best is the Windows one and I know that there it's quite difficult to keep both main and child windows focused, but there are a couple of approaches that, while still not being ideal, would be more robust: abusing the dialog or MDI APIs.

Regarding X11 and MacOS, isn't there a better way to achieve this?

Furthermore, if the windowing systems actually fail to provide APIs to do this well, wouldn't it be better to just keep small child windows as formerly? I mean small popups like menus are not real windows and leave the true windows approach for dialogs like file open, confirms, etc.

**Comment by KoBeWi** [comment]
The previous issues were fixed, but I spotted another one, with right-click menus:
image
(it's the same as double popup before, but with context menus)

**Comment by HaSa1002** [comment]
> 
> 
> Isn't this approach like fighting against the windowing APIs too much, in a way that can break easily depending on the behavior of user and/or input devices? 

Yes, you are fighting against the window apis. I don't think that it breaks depending on the user devices from the focus point of view. That is working relativly reliable. The bigger issue is the input. Our controls are designed to use actions (I think they work fine, although I have to confirm that) and use the mouse. I believe all, for this case, important InputEvents do inherit from InputEventFromWindow. Maybe we could add methods there to ensure correct behaviour of Input. One method I have in mind is `InputEventMouse::get_position`, where you could add a parameter to get the input in local coordinates for a different window.

> Maybe it is, and maybe even that's the only option, but, just in case, let me suggest the following:
> 
> The windowing API I know the best is the Windows one and I know that there it's quite difficult to keep both main and child windows focused, but there are a couple of approaches that, while still not being ideal, would be more robust: abusing the dialog or MDI APIs.

I took a quick look at both the dialog API and the MDI API (I never worked with os apis before.) I don't imagine both working nice with the current design of Godot's window. Currently, the window creation method is always the same and will always create a window with the same window api as the main window. The MDI api seems to be not really the api we want to use in our case, as we don't have embedded windows in the way the api is designed. What I don't understand is how other software is using the default menus. If I understand some parts of the Win32 api correctly (I doubt that), menus and ordinary input fields are all managed by the os and created through the window api. 

> Regarding X11 and MacOS, isn't there a better way to achieve this?

I don't know. I did brute force programming until I had something working on Windows and copied the approach to X11 and macOS.

> Furthermore, if the windowing systems actually fail to provide APIs to do this well, wouldn't it be better to just keep small child windows as formerly? I mean small popups like menus are not real windows and leave the true windows approach for dialogs like file open, confirms, etc.

I guess you mean embedding windows as in 3.2? That doesn't seem to work, as viewports either embed windows or don't.

**Comment by RandomShaper** [comment]
I thought that, given that MDI windows can be focused as the same time as the main one, we might have a chance by exploring that. However, there are indeed other differences that render the idea useless.

But maybe the dialog API still can by not really following it as it's intended to be used? The DisplayServer differentiates between main and child windows, and there may be a chance there, to create children as dialogs. Again, this is brainstorming that would require some research.

Regarding standard menu bars, yes, the OS manages them automatically, so it maybe does something beyond what is possible via standard use of the API.

I think that all you say makes sense in general. I just wanted to tell my view and give potential ideas because I'll be away for some weeks and I think it'd be good to raise a warning about your approach to try to help reaching a more robust solution.

Unfortunately, at this point I will no longer have time to do some research myself until I'm back.

**Comment by HaSa1002** [comment]
Thanks for the input. The warning is good, but I don't know if I am able to build up enough of a foundation to get to a point similar to this one. I will look into creating windows as dialogs, but at the same time try to fix the current approach or better check, what I need to fix the current approach.

**Comment by HaSa1002** [comment]
I did some experiments and I think the way to go for windows, is using `WS_CHILD` on Windows. There is some stuff, that is still fishy and I have to play more with it, but I believe we are going in the correct direction.

**Comment by HaSa1002** [comment]
I fixed the issue on Windows with a different approach that is much more robust. I am switching to the X11 Display Server now. Please let me know if there are more bugs left in the Windows fix.

**Comment by HaSa1002** [comment]
I get a segfault here: (`delete_sub_window` deletes the window, and `_dispatch_input_event` iterates over it).

<details>
<summary>Details</summary>

```
DisplayServer::_create_window 2 want rect: 8, 71, 329, 439 got rect 8, 71, 329, 439
[211] MapNotify window=62914675 (2) 
[211] MapNotify window=62914675 (0) 
[211] VisibilityNotify window=62914675 (2), state=0 
[211] Expose window=62914675 (2), count='0' 
[212] FocusOut window=62914564 (0), mode='0' 
	NotifyAncestor=0, NotifyVirtual=0, NotifyInferior=1,
	NotifyNonlinear=0, NotifyNonlinearVirtual=0, NotifyPointer=0,
	NotifyPointerRoot=0, NotifyDetailNone=0
[212] FocusIn window=62914675 (2), mode='0' 
	NotifyAncestor=1, NotifyVirtual=0, NotifyInferior=0,
	NotifyNonlinear=0, NotifyNonlinearVirtual=0, NotifyPointer=0,
	NotifyPointerRoot=0, NotifyDetailNone=0
[218] ButtonRelease window=62914564 (0), button_index=1 
[340] ButtonPress window=62914564 (0), button_index=1 
delete_sub_window: 62914675 (2) 
2
1
The crash occured later!
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7ffff787b950] (??:0)
[2] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (/home/ubuntu/Documents/godot/platform/linuxbsd/display_server_x11.cpp:2687)
[3] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (/home/ubuntu/Documents/godot/platform/linuxbsd/display_server_x11.cpp:2666)
[4] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/home/ubuntu/Documents/godot/core/input/input.cpp:642)
[5] Input::parse_input_event(Ref<InputEvent> const&) (/home/ubuntu/Documents/godot/core/input/input.cpp:465)
[6] Input::flush_accumulated_events() (/home/ubuntu/Documents/godot/core/input/input.cpp:857)
[7] DisplayServerX11::process_events() (/home/ubuntu/Documents/godot/platform/linuxbsd/display_server_x11.cpp:3535)
[8] OS_LinuxBSD::run() (/home/ubuntu/Documents/godot/platform/linuxbsd/os_linuxbsd.cpp:257)
[9] /home/ubuntu/Documents/godot/bin/godot.linuxbsd.tools.64.llvm(main+0x1dc) [0x457fa2c] (/home/ubuntu/Documents/godot/platform/linuxbsd/godot_linuxbsd.cpp:58)
[10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf2) [0x7ffff7862cb2] (??:0)
[11] /home/ubuntu/Documents/godot/bin/godot.linuxbsd.tools.64.llvm(_start+0x2e) [0x457f78e] (??:?)
-- END OF BACKTRACE --
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-4373iyjj.r6c" 1>"/tmp/Microsoft-MIEngine-Out-utnnopba.1f5"
```

</details>

**Comment by HaSa1002** [comment]
So... I finally managed to get X11 working.

**Comment by HaSa1002** [comment]
As I have no Mac, I can't really port the changes I did for X11 and Windows to OSX. The idea is pretty simple:
1. Create windows as child windows of the main window
2. Recalculate their position in the window creation, because Godots coordinate system is different to the window coordinate system
3. Do the same in `window_set_position`

The problem is getting 2 and 3 right and requires some testing that I cannot do without a Mac...

**Comment by HaSa1002** [comment]
I may got the Windows DisplayServer completly working. It is a mess right now and I did so much extensive brute force programming, but as far as I can tell, it works as expected. I still have to update Linux. I may drop macOS, because I have none and can't test. CI will pass once, I changed the create sub window API for all Display Servers.

**Comment by HaSa1002** [comment]
I managed to fix CI (finally). Windows should be fully working and I would appreciate a test. I am fighting with X11 to get it doing what I want, but right now I am stuck with an unhealthy loop of events that break the hovering back to parent popup menus. Eg. if you open a popup menu everything is fine until you open a sub popup window. You can hover it just fine, but you can't hover back to the old menu anymore. IIRC this is expected behaviour, if I understand that event page correctly. It looks like there are ways to configure that behaviour, but I am to blind: https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#events:input_focus

I won't continue to work on the macOS port of the code (I effectively port the code from Windows to X11 and back) apart from syncing the API change which was necessary to make the API more robust. Programming system API code without the system is not fun at all and I want to get this PR done. I started working on this bug about a year ago. It is time to finish it.

Apart from the mentioned bug, I have to do some clean up and rebase for safety reasons, but right now I want to keep the history.

**Comment by KoBeWi** [comment]
Tested on Windows, there seems to still be some issue with menus:
Problem
Hovering doesn't open them. Also the first clicked menu gets some permanent focus.

Another thing is that when right-clicking node while a context menu is open, the new menu will disappear in split second:
Bug2-2
The menu disappears when inspector (scene tree?) is refreshes, so maybe some update is killing it.

The issues I mentioned previously are fixed.

**Comment by HaSa1002** [comment]
> Tested on Windows, there seems to still be some issue with menus:
> 
> Hovering doesn't open them. Also the first clicked menu gets some permanent focus.

see #37771
This is broken for a longer time now. In my previous PR, both fixes worked fine together.

> Another thing is that when right-clicking node while a context menu is open, the new menu will disappear in split second:
> 
> The menu disappears when inspector (scene tree?) is refreshes, so maybe some update is killing it.

Interesting. I thought, I already hacked something together to prevent that... Thank your for the feedback. I will soon get back to it :)

**Comment by HaSa1002** [comment]
So I did another rebase (and partially screwed it up) and tested again.
Your issue, @KoBeWi, with the non opening context menu is not caused by this PR. This happens in master too. 

I know of another issue with the window shrinking logic that doesn't get propagated back to the controls (I think). Apart from that there is one issue with transient windows having transient children. I did some work to catch that, but I find a solution to close the correct window.
But maybe all the work is not worth it. If we decide to embed transient windows all the time and merge #46515 then we may end up with a more robust solution. To be honest, I am frusted about this issue since it feels like I am close to a solution, but I don't get to the finish line. So I am near giving up again on this. I have made three attempts now over a way too long time frame for such a cheap issue. Help and opinions appreciated.

**Comment by HaSa1002** [comment]
Superseded by #58490

**Pull request closed without merging**
