### PR TITLE
Fix C# bindings after recent breaking changes

### PR DESCRIPTION
**Pull request by neikeq**
Implementation for new Variant types Callable, Signal, StringName.
Added support for PackedInt64Array and PackedFloat64Array.

Add generation of signal members as events, as well as support for
user created signals as events.
NOTE: As of now, raising such events will not emit the signal. As such,
one must use `EmitSignal` instead of raising the event directly.

Removed old ThreadLocal fallback class. It's safe to use thread_local now since
it's supported on all minimum versions of compilers we support.

### CODE REVIEW

**Comment by neikeq** [comment]
> NOTE: As of now, raising such events will not emit the signal. As such,
one must use EmitSignal instead of raising the event directly.

The ideal thing would be that raising the event will also emit the signal. However, I still haven't figured out a good way to solve the problem with this circular call:
raise event -> emit signal
raise event <- emit signal

**Comment by neikeq** [comment]
Don't merge this yet. I forgot about clearing or possibly serializing managed callable delegates on hot-reload.

**Comment by neikeq** [comment]
This is ready now.

**Comment by neikeq** [comment]
@akien-mga I've updated the `Standard` in our `.clang-format` to `Cpp11` (which refers to all versions after C++11).
Without this, some new features are wrongly formatted (in my case that was `if constexpr`). However, this may change formatting in a lot of other places. One case in particular are double angle brackets (`>>`) in templates. Before this, they were formatted like `> >`, but with this change they are formatted like `>>` (as C++11 fixes ambiguity with the `>>` operator). This may make CI to fail on PRs.

**Comment by akien-mga** [comment]
> I've updated the Standard in our .clang-format to Cpp11 (which refers to all versions after C++11).

I was waiting for the `display-server` branch to be finalized and merged before doing style changes to avoid introducing avoidable merge conflicts, but if you need it for `if constexpr`, I guess it makes sense to update now.

I'll do a separate PR changing the Standard and applying it to the codebase that you can rebase upon once merged, so we get the whole codebase following the new standard.

**Comment by akien-mga** [comment]
#37106 is merged, you can rebase and drop the second commit.

**Pull request merged**
