### PR TITLE
Fix setting the default icon briefly with tools=no

### LINKED ISSUE #11242: macOSX application show briefly the godotengine icon when launched
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
macOSX sierra 10.12.6
Godotengine V2.1.4 stable.official
MacBookPro retina 2012

**Issue description:**

I export my application as a macOSX application and then if i launch it my custom icon is replaced by the godotengine icon briefly.
There is no way to remove the godot engine icon and i would like my application display only my icon and not the godotengine icon.

**Steps to reproduce:**
Export your project like a  macOSX application and launch it.

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes #11242

### CODE REVIEW

**Comment by hpvb** [comment]
LGTM

**Comment by akien-mga** [comment]
Won't that mean that if you don't have a custom icon defined, the app will lack a proper icon? https://github.com/marcelofg55/godot/blob/59eb7837519298a5feb74b408cf6cfe8f7e33f46/main/main.cpp#L1520-L1526

**Comment by marcelofg55** [comment]
@akien-mga I've just amended the PR so that even if the project has no icon defined it will have a proper icon.

**Comment by akien-mga** [comment]
But now tools build will have the icon set twice for no reason ;) Can't we remove the first one?

**Comment by marcelofg55** [comment]
Yeah, but if I remove the first one godot will lack an icon while loading. I've tested this on OS X and godot loads for 1-2 secs between the first set_icon place and the second one I've added.

**Comment by hpvb** [comment]
Whoops missed the 'no icon at all' case

**Comment by hpvb** [comment]
This looks good now, right? It seems to handle the no icon case.

**Comment by akien-mga** [comment]
Well the only issue is that for tools build we set the same icon twice, but maybe it's not that bad.

**Pull request merged**
