### PR TITLE
Improve template class conditionals with constexpr (code style)

### PR DESCRIPTION
**Pull request by Craig-Stoneham**
Refactored the following template classes by replacing runtime checks with compile-time checks using if constexpr for improved code clarity and maintainability:

-   RID_Alloc
-   SortArray
-  PagedAllocator

Changes made:

-   Updated conditional checks for THREAD_SAFE in the RID_Alloc class.
-   Updated conditional checks for Validate in the SortArray class.
-   Updated conditional checks for thread_safe in the PagedAllocator class.

### CODE REVIEW

**Comment by Chaosus** [comment]
Please squash the commits as it's required by our pipeline (see https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request).

**Comment by Craig-Stoneham** [comment]
Done

**Comment by lawnjelly** [comment]
Does this produce any difference to the compiled assembly?

**Comment by clayjohn** [comment]
> Does this produce any difference to the compiled assembly?

Even if it doesn't, it's probably beneficial to be explicit

**Comment by RandomShaper** [comment]
> Does this produce any difference to the compiled assembly?

I've done a few tests with this code snippet on Compiler Explorer:
```C++
int f() {
    int a = 23;
    if constexpr (1 == 2) {
        a *= 3;
    }
    return a;
}
```

Considering latest stable versions of all the compilers (and targeting x64, which shoudln't matter), this is the result:
|                     | GCC `-O0` / `-O2`  | Clang `-O0` / `-O2`  | MSVC `-Od` | MSVC `/O1` / `/O2` |
|---------------------|--------------------|----------------------|------------|--------------------|
| With `constexpr`    | ✂                  | ✂                    | ✂          | ✂                  |
| Without `constexpr` | ✂                  | ✂                    | NO         | ✂                  |

So, all of them already prune out the compile-time dead branch, except MSVC for debug builds.

If we use `constexpr` in the context of template specialization, like in the code below, all of them prune the branch out regardless the optimization level. I wonder if the standard mandates such behavior.
```C++
template<bool N>
struct C {
int f() {
    int a = 23;
    if constexpr (N) {
        a *= 3;
    }
    return a;
}
};

int main() {
    C<false> c;
    return c.f();
}
```

> Even if it doesn't, it's probably beneficial to be explicit

I agree. In low-level areas of the codebase, such as this one, the possibility of being explicit on what's going on is something to leverage. After all, that's akin the philosophy behind other decisions. The explicit nature of `SafeNumeric`, as opposed to adding operator overloads, comes to mind as an example.

**Review by RandomShaper — APPROVED** [review]
LGTM. In the case of `SortArray`, I think it'd be better to use `DEV_ASSERT`s for those validations, but I'd have to look closer to come with a conclusion on that and, anyway, that'd be out of the scope of this PR.

**Comment by RandomShaper** [comment]
If anything, the PR and commit message could be changed not to talk about optimization but code style.

**Comment by Craig-Stoneham** [comment]
> If anything, the PR and commit message could be changed not to talk about optimization but code style.

Thank you for testing this. I have updated both the PR commit message and description as per your request.

**Comment by Mickeon** [comment]
The changes to Project Settings and the addition of the new setting do not look related at all to this PR, from what I understand. I suggest you remove them.

**Comment by Craig-Stoneham** [comment]
> The changes to Project Settings and the addition of the new setting do not look related at all to this PR, from what I understand. I suggest you remove them.

I apologize. I just created a new branch for this, and I am trying to remove this now.

**Comment by AThousandShips** [comment]
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Review by AThousandShips — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
Code looks good to me. [This is a C++17 feature](https://en.cppreference.com/w/cpp/language/if#Constexpr_if) and we already use it in many other places, so it's OK to use.[^1]

[^1]: The only context where `if constexpr` requires C++23 is for expressions that are not `bool` or are implicit integer conversions to `bool`.

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase), you will need to rebase to remove the merge commits

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
