### PR TITLE
Separate DisplayServer from OS and add multiple windows support

### PR DESCRIPTION
**Pull request by akien-mga**
Same content as the `display-server` branch that @reduz worked on (with help from @kuruk-mm and @bruvzg), but rebased on top of the current `master` branch (only took ~5 hours!).

- `OS` is split into `OS` and `DisplayServer`.
- `X11` OS is renamed to `LinuxBSD` (Linux, FreeBSD and OpenBSD "desktop" systems as per Freedesktop), `X11` is now its first `DisplayServer` implementation (`DisplayServerWayland` can be added eventually).
- `Input` refactor (the singleton is now `InputFilter`).
- Adds `Window` node which is the new scene root.
- Multiple window support.
- Dialogs, Popups and Inspector docks now use Window.
- Lots of bugs, let's bring back instability to the `master` branch!

I forgot to use `--preserve-merges` when rebasing, so we lost the references to PRs #36936 and #37029 which were merged in `display-server`.

### CODE REVIEW

**Comment by neikeq** [comment]
Why are we renaming `Input` to `InputFilter`?

**Comment by bruvzg** [comment]
There is some `scancode`/`keycode` stuff not rebased the macOS DisplayServer.

**Comment by akien-mga** [comment]
> There is some `scancode`/`keycode` stuff not rebased the macOS DisplayServer.

I just fixed that normally.

You might want to check if I didn't miss anything else though, it took me several iterations to figure out that changes had been lost in the DisplayServer split for macOS and Windows - and Input changed too so that didn't help :D

**Comment by akien-mga** [comment]
> Why are we renaming `Input` to `InputFilter`?

See 8e6960a. As I understand it, windows are now handling input and the only thing left in the previously-named "Input" class was input filtering, so it was renamed accordingly.

**Comment by YeldhamDev** [comment]
@akien-mga
```
main/default_controller_mappings.gen.cpp:3:10: fatal error: main/default_controller_mappings.h: No such file or directory
    3 | #include "main/default_controller_mappings.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by akien-mga** [comment]
@YeldhamDev You know the drill after all these years and this happening twice a year ;)
```
find -name "*.gen.*" -delete
```
(Or `git clean -fxd` since all the `.x11.*` stuff is now obsolete too.)

**Comment by YeldhamDev** [comment]
@akien-mga Sorry, I tend to forget to clean up the files in those situations, probably because it reminds me of how much time it will take to compile everything again... :V

**Comment by bruvzg** [comment]
> You might want to check if I didn't miss anything else though, it took me several iterations to figure out that changes had been lost in the DisplayServer split for macOS and Windows - and Input changed too so that didn't help :D

There's `k->set.keycode(0);` instead of `k->set_keycode(0);` on the line `3040` of `display_server_osx.mm`, everything else seems to be OK.

**Comment by Xrayez** [comment]
> Why are we renaming `Input` to `InputFilter`?

I prepared a proposal already to discuss this: godotengine/godot-proposals#639. 🙂

**Comment by ballerburg9005** [comment]
This issue was referenced by one/some of the "multi monitor support" issues and I just installed Godot 4 from git because I was hoping that I could just pop the main tabs like the code editor or the help into a new window, so I can expand that window on one of my other monitors.

Oddly enough, everything but the code editor now pops into a new window (like context menus from the main menu, when I rightclick something the right click menu becomes a new window and so forth).

I am not sure how this works out for MS Windows, but I am on Linux and I also use a tiled/tabbed window manager and it totally breaks everything the program is virtually unusable. My window manager allows me to totally disable the tiling - so its not really an issue of WM either. Usually you only need to disable tiling for totally outlandish weird apps (like Acroread blob from 1998 and similar), but still no matter what I configure, the context menus open in the wrong place and flip open and closed back and forth sometimes.

I am not exactly sure if this commit is to blame, from what I saw at first glance it is.

But how on earth did it all play out like this? 

For multi-monitor: Couldn't you guys just quickly add a button "make floating" for some of the tabs, like the code editor (especially that!), or all of the tabs?

The "make floating" already is there for the Dock in the Dock context menu.

I mean, for multi-monitor support why make absolutely everything open in a new window even context menus? That seems totally mental to me. 

Just make a single button that opens a single additional window, in which you can hard-code a new code editor or dock tabs from the main screen to and hundreds of people can use at least two screens and will be totally happy.

**Pull request merged**
