### PR TITLE
Try to convert `OS::execute()` output to Unicode on Windows

### LINKED ISSUE #60897: OS.execute should output PackedByteArray?
### Godot version

v4.0.alpha7.official [3e9ead05f]

### System information

windows10 64bit

### Issue description

When I execute my PowerShell command on PowerShell's window, it output like this:

And I coding GDScript like this:

But It prints like this:

Because PowerShell return not valid UTF-8, so I think maybe OS.execute should output PackedByteArray and I can code like this for solve this problem:

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[OsExecTest.zip](https://github.com/godotengine/godot/files/8648569/OsExecTest.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Resolves #60897

Windows defaults to ANSI instead of 8-bit ASCII. Full characters are sent but using different encodings according to the code page. This is why godot prints lots of "Unicode parsing error" when trying to interpret these bytes as UTF-8 which is most of the time an incorrect encoding (but compatible with the ASCII part).

This PR uses `MultiByteToWideChar` to convert the output bytes from system default ANSI encoding to Unicode (`wchar_t`) so that a `String` can be constructed correctly. If the API fails, we fallback to the original "treat as UTF-8" approach.

I only tested this on a Simplified Chinese version of Windows. CC @bruvzg 

For cherry-pick: `is_empty()` → `empty()`.

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
`MultiByteToWideChar` probably will work for most cases

But I'm not sure about reading everything to the buffer and converting it at once. This will prevent receiving long output in portions (e.g., from the other thread).

Breaking it at the arbitrary points might break multibyte conversion, but the same is true for old code and Unix version. So might be better to look for the new like characters and do converting/adding to string for a single line at a time.

**Comment by timothyqiu** [comment]
Updated to convert available lines at each iteration.

**Review by bruvzg — APPROVED** [review]
It seems to be working fine.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
