### PR TITLE
Fixed bullet scale on get_transform and joints

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixed bullet scale on get_transform and joints

### CODE REVIEW

**Comment by AndreaCatania** [comment]
I really need this fix, please @reduz check it

**Comment by reduz** [comment]
do changes work the same in godot physics ?

**Comment by AndreaCatania** [comment]
Yes, but don't merge it in this moment because I have to fix more

**Comment by akien-mga** [comment]
@AndreaCatania Is this now ready to merge?

**Comment by AndreaCatania** [comment]
Yes merge it I'll fix others things in another PR

**Pull request merged**
