### PR TITLE
Remove HQ2X and the `Image.expand_2x_hq2x()` method

### PR DESCRIPTION
**Pull request by Calinou**
As of Godot 3.0, HQ2X is no longer used to upscale the editor theme and icons on hiDPI displays, which limited its effective uses. HQ2X was also used to upscale the project theme when the "Use Hidpi" project setting was enabled, but results were often less than ideal. The new StyleBoxFlat and SVG support also make HQ2X less important to have as a core feature.

This decreases binary sizes slightly (-150 KB on most platforms, -212 KB on WebAssembly release). These savings are pretty nice to have on size-constrained platforms like Android and WebAssembly :slightly_smiling_face:

This partially addresses #12419.

### CODE REVIEW

**Comment by Xrayez** [comment]
If HQ2X gets removed, it could be made available as part of [ImageTools](https://github.com/Xrayez/godot-imagetools) module.

I see this useful for upscaling pixel-art style images where simple resize with interpolation would make it blurry. The use case is mainly to enhance user-generated content, so this would have to be available at runtime as well.

**Comment by Calinou** [comment]
@Xrayez There's also the [OmniScale](https://godotengine.org/asset-library/asset/258) asset :slightly_smiling_face:

**Comment by Xrayez** [comment]
Yeah, though the idea is rather about turning pixel-art assets into non-pixel-art here, so the simple nearest-neighbor interpolation would make it "worse". I also do need an actual image on output, OmniScale makes it work via shaders, but I think it could be made possible to take a viewport snapshot to get the result as image that way.

**Comment by nobuyukinyuu** [comment]
@Xrayez 
I think hqx as it exists in the way it's currently exposed to Godot has very limited usage, mainly as was alluded to, for upscaling assets on a "once at runtime" pass.  Most hardware implementations of hqx out there weren't MIT-compatible when I last checked, which is why godot-OmniScale exists.  A module with the hqx functions might be best for your use case, if rendering assets to a `ViewportTexture` using OmniScale isn't acceptable.

**Comment by Xrayez** [comment]
I have a bunch of viewports already that render stuff for me in 2D, I'd rather avoid that. 😛

But yeah, I'm not against removing HQ2X, I'm not sure whether I'd use that either, but indeed seems like it could be useful in my use case at some point. I'll consider using OmniScale then, thanks for your work on this!

Not sure if Vulkan would change how shaders are being compiled/written to use OmniScale safely, but this is certainly wouldn't be a core feature so I could safely drop it at any point.

**Comment by akien-mga** [comment]
Needs a rebase, otherwise seems good to merge now.

**Comment by Calinou** [comment]
@akien-mga Done (I remade it from scratch, actually).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Xrayez** [comment]
For those who would still like to use the method, I've re-implemented it in the aforementioned [ImageTools](https://github.com/Xrayez/godot-imagetools) module:
```gdscript
ImageTools.resize_hqx(image, scale = 2)
```
https://github.com/Xrayez/godot-imagetools/commit/57b7c02931db6b9a349ed21751f1db4820a17f17

Not only that, I've taken the latest version from the [hqx](https://github.com/brunexgeek/hqx) library with some recent fixes, and exposed a way to resize an image with HQ3X algorithm as well.

This was added to [`master-gd3`](https://github.com/Xrayez/godot-imagetools/tree/master-gd3) branch for now, and will be later ported to [`master-gd4`](https://github.com/Xrayez/godot-imagetools/tree/master-gd4) branch once the Godot 4.0 is stable enough to use, or whenever I'm motivated enough to keep the branches in-sync feature-wise. 🙂

**Pull request merged**
