### PR TITLE
Fix "2D Polygon indices are barely visible on bright background" (#38009)

### LINKED ISSUE #38009: 2D Polygon indices are barely visible on bright background
**Godot version:**
3.2.1

**Issue description:**
image
Could be fixed with something like this #36530 probably

### PR DESCRIPTION
**Pull request by Cretezy**
Fixes https://github.com/godotengine/godot/issues/38009

Applied https://github.com/godotengine/godot/pull/60094 with updated outline rendering (`draw_string_outline`), using approach in https://github.com/godotengine/godot/pull/36530

image

image

<details>
<summary>And for reference, before (on current 0160fea1ced6697d5b72ad2f41332e8768080be4 master):</summary>

image

image

</details>

### CODE REVIEW

**Comment by AThousandShips** [comment]
What do you mean by "applied"?

**Comment by Cretezy** [comment]
@AThousandShips I mean that I took that as a base for these changes, in terms of which location the code should be changed (and the font). This PR should supersede the other PR

**Comment by AThousandShips** [comment]
I think it'd be best if the original PR got updated, don't see what's the justification for you copying and taking over when there's already a PR doing the same thing?

**Comment by Cretezy** [comment]
Additionally the following PR are also superseded: https://github.com/godotengine/godot/pull/66796

**Comment by AThousandShips** [comment]
I understand, I don't know what the policy here is, but to me I wouldn't see it as the proper way to collaborate unless the original author had abandoned it.

**Comment by KoBeWi** [comment]
If you copied code from another PR, just add the original author as co-author of the PR and the other PR becomes irrelevant.

**Comment by Cretezy** [comment]
@KoBeWi Done, added https://github.com/godotengine/godot/commits?author=eruhlinteractive as Co-authored-by to https://github.com/godotengine/godot/pull/70902/commits/8dc3162f038b56b20ca06b3c42780636b77ab1a2

**Comment by KoBeWi** [comment]
I wonder if the number shouldn't be bigger. It does look better now on bright background, but it's still barely readable when it intersects with lines.
image

**Comment by Cretezy** [comment]
@KoBeWi I agree. I also think the same should apply to the ruler tool:

(current)
image

With 1->1.3x font size and 2->4 outline and matching ruler color:

image
image

**Review by KoBeWi — APPROVED** [review]
I'm not sure about the hard-coded 1.3 multiplier. Maybe it should be a constant.

Visually it looks ok.

btw you need to squash your commits into 1.

**Comment by Cretezy** [comment]
@KoBeWi Squash done. I'm open to suggestions to replace the 1.3 multiplier.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
