### PR TITLE
Hide unused `exp_edit` from SpinBox's inspector

### PR DESCRIPTION
**Pull request by shahriarlabib000**
- Context: https://github.com/godotengine/godot/pull/97573#issuecomment-2464778277

### CODE REVIEW

**Comment by Calinou** [comment]
I don't see any references to `exp_edit` in Godot's codebase, other than two mentions in the class reference. The property seems to have no effect at all and could be deprecated (and hidden in the inspector) at the Range level.

**Comment by shahriarlabib000** [comment]
So i just need to do this in `Range.cpp` ?

**Comment by shahriarlabib000** [comment]
I think it's necessary for `Range::set_as_ratio` ,`get_as_ratio` etc

**Comment by KoBeWi** [comment]
Yes, `exp_edit` is used for `ratio`, which is relevant mostly for Slider.
It has no effect in Range controls that don't use ratio, like SpinBox.

**Review by KoBeWi — APPROVED** [review]
Context: https://github.com/godotengine/godot/pull/97573#issuecomment-2464778277 

@shahriarlabib000 You should've linked it in the PR description.

**Comment by shahriarlabib000** [comment]
Sorry!

**Review by Repiteo — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
