### PR TITLE
Leverage transfer queue in Vulkan RD

### PR DESCRIPTION
**Pull request by RandomShaper**
## Commits

This includes every commit from #55954, then adds the following:

- **Exclude additional validation messages [temp]**
  This was just to avoid some wrong validation messages that were annoying. To be removed in the final version of the PR.

- **Leverage transfer queue in Vulkan RD** 👉 Reviewing separately advised. 👈
  The main thing in thIs PR.
  I belive it's mostly correct, but I find it hard to test performance. Furthermore, I have the suspicion that to really unleash the performance gains this can give while loading resources something else must be done.
  One important thing is, **the setup command buffer is repurposed as a transfer command buffer**, under the assumption that there was no real need for a separate setup buffer. Wherever a dedicated transfer queue is not available, this new setup/transfer step won't happen.

- **Simplify staging buffer in Vulkan RD** 👉 Reviewing separately advised. 👈
  A tentative rework of the staging buffer, aimed to support granular flushing of transfers in old frames. The way context and RD interact currently doesn't make it easy, so that's future work, but theses changes may already be opening the door for it.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Pinging @RandomShaper

**Comment by mhilbrunner** [comment]
PR meeting, to quote Juan: "this needs to be done before 4.0 for performance reasons" :)

**Comment by akien-mga** [comment]
@RandomShaper This has been a draft for a while. Is this still relevant nowadays / something that will be revisited later, or should it be closed?

**Comment by RandomShaper** [comment]
This is no longer relevant, brilliantly superseded by @DarioSamo's work.

**Pull request closed without merging**
