### PR TITLE
Fix a pixel misalignment in the blue robot logo

### PR DESCRIPTION
**Pull request by MewPurPur**
Follow-up to #78015 because I've made a huge blunder :sob: 

https://github.com/godotengine/godot/assets/85438892/62938e76-e059-4e1a-9fa3-1cc339a901ab

- Fixes this.
- Deletes misc/dist/project_icon.svg as mentioned here: https://github.com/godotengine/godot/pull/78015#issuecomment-1583607900
- Optimizes TitleBarLogo.svg, adds width and height properties to it, and changes it to use the standard editor color #e0e0e0 instead of #fff.

### CODE REVIEW

**Comment by JekSun97** [comment]
What a terrible, dangerous problem )

**Review by Geometror — APPROVED** [review]

**Review by Chubercik — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by akien-mga** [comment]
Cherry-picked for 4.1.4.

**Pull request merged**
