### PR TITLE
[4.2] Fix running tests in template builds

### PR DESCRIPTION
**Pull request by AThousandShips**
Also fixes some errors with 3D disabled

Leaving `World3` exposed for right now unless desired, it is completely useless in non-3D builds but it doesn't break anything according to testing, unlike in #88452 where it exposes 3D physics

Partial backport of:
* https://github.com/godotengine/godot/pull/88704
* https://github.com/godotengine/godot/pull/88452

### CODE REVIEW

**Comment by Zylann** [comment]
My CI is currently breaking on Windows because of the lightmapper https://github.com/Zylann/godot_voxel/actions/runs/8033770184/job/21944596942
So despite the issue not being related to tests, that PR would fix it I think

**Comment by AThousandShips** [comment]
It does, see the note, it's because a cherry pick I've made here, the original PR should be cherry picked directly

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
