### PR TITLE
modified gles icons

### PR DESCRIPTION
**Pull request by ZX-WT**
I tweaked both gles2 and 3 svg, the result is not finalized yet.

### CODE REVIEW

**Comment by volzhs** [comment]
I couldn't notice what's different with attached image.
Here is closer look.
es_icon

**Comment by capnm** [comment]
My old eyes don`t see a significant difference. I would remove the line, it does not match the font style. According to Wikipedia, it's okay to write `GLES` as one word: https://en.wikipedia.org/wiki/OpenGL_ES

**Comment by Calinou** [comment]
> According to Wikipedia, it's okay to write GLES as one word: en.wikipedia.org/wiki/OpenGL_ES

It's a trademarked logo, it's probably not a good idea to modify it too much.

**Comment by capnm** [comment]
The logo is already very different ;)
image

**Comment by capnm** [comment]
Yes, you can't cut part of logo and think it will still work.

**Comment by ZX-WT** [comment]
I am good as long as that line is fixed, be it deleted or modified, just need a conclusion :)

**Comment by capnm** [comment]
> I am good as long as that line is fixed, be it deleted or modified, just need a conclusion :)

That's the hard part, I'm already out of smileys :)

**Comment by akien-mga** [comment]
I don't get why there is such a fuss about a pipe in a logo, but I don't care either way. If you guys prefer a slightly different logo or plain text, it's fine by me.

**Comment by capnm** [comment]
> I don't get why there is such a fuss about a pipe in a logo, but I don't care either way. If you guys prefer a slightly different logo or plain text, it's fine by me.

The designer part of my brain doesn't get why someone would cut a piece of a logo and pipe it somewhere, but I see many worse things every day.

**Comment by akien-mga** [comment]
Well so be it, let's go with plain text. Superseded by #22027.

**Pull request closed without merging**
