### PR TITLE
Moves switch for show scripts panel from File menu to status bar

### PR DESCRIPTION
**Pull request by Chaosus**
This may be subjective but I think its a more comfortable position for this switch than in File menu. 

panel

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Hi, there is still a small issue: can't toggle the panel when viewing the built-in help.

**Comment by Chaosus** [comment]
Ah.. not only built-in help but visualscript editor too..

**Comment by Chaosus** [comment]
> Hi, there is still a small issue: can't toggle the panel when viewing the built-in help.

Alright, I've fixed it

**Pull request merged**
