### PR TITLE
[4.2] GDScript: Lambda hotswap fixes

### PR DESCRIPTION
**Pull request by rune-scape**
cherrypicked https://github.com/godotengine/godot/pull/86569 for 4.2 :)

### CODE REVIEW

**Review by AThousandShips — DISMISSED** [review]

**Comment by AThousandShips** [comment]
Normally when something is easily done with `git cherry-pick` we leave it to the production team to handle, unsure if this was trivial

Will need a decision from the gdscript team and see if it doesn't cause any unforeseen issues before merging but code looks good

**Comment by rune-scape** [comment]
ah 👍 ya it was trivial, not much of the surrounding code changed ,  didn't know 👍

**Comment by AThousandShips** [comment]
Then future suggestion would be to ask on the PR if it can be cheery picked

**Comment by akien-mga** [comment]
@rune-scape Could you help us evaluate how risky this PR is, i.e. does it have potential to introduce regressions and are the issues it fixes worth it?

For stable branches we're usually quite conservative with what we cherry-pick, and this code specifically had a number of critical regressions in the phase leading to 4.2-stable. It's not clear whether users are affected by the issues #86569 fixes in the wild (no bug report), so if it has potential to instead break some functionality, I'd opt for not cherry-picking the PR (and let it get tested thoroughly in the 4.3 dev phase).

**Comment by akien-mga** [comment]
CC @adamscott @RandomShaper

**Comment by RandomShaper** [comment]
Given that I won't be very aware of how this turns out in the wild, all I can say is I agree with not cherry-picking at least until 4.3 has been thoroughly tested and also it's maybe not worth the risk if there are no reported issues in 4.2, anyway. I wouldn't oppose, though, regardless no reports, but, yes, let's see if the current approach crystalizes into stability in the wild.

**Comment by rune-scape** [comment]
technically not a critical bug, but the way that https://github.com/godotengine/godot/pull/81628 works is fundementally broken, the the PRs that followed didnt fix the fact that it invalidates basically all lambdas unless theres only 1 script with lambdas, making it safer than nothing ig
i can make an issue demonstrating this for 4.2,
the original code is convoluted and has 2 mutexes to lock in order to add a func ptr, which could deadlock if not done properly,,, thats what most of the following PRs helped with, but they also made the code even harder to follow and inspect
this code only uses 1 mutex very simply, i think its much safer in that regard

**Comment by akien-mga** [comment]
The thing is, if it's breaking hot reloading, it's not a big deal, it's just an editor time inconvenience. What it addressed however was runtime crashes which we're critical. I want to make sure we don't re-introduce runtime issues for the sake of improving editor lambda editing usability.

**Comment by rune-scape** [comment]
ok i understand, was giving my input and maybe was distracted from how important its stability is,
i do think the way this code is written is much safer than what is in 4.2 fwiw, but not tested nearly as much

**Comment by akien-mga** [comment]
Let's give it a go then and see what happens with 4.2.2 RC 1 tests.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
