### PR TITLE
Make it so that 2D viewport does not pan while editing tilemaps

### LINKED ISSUE #30875: While editing tilemap: pressing right mouse button scroll the screen
**Godot version:**
Working normal in commit: 31eb116d49a8648a560354c7caa895cc7a8661c5
Broken in commit: 017b224a87064a3d333ba63809a0f12cfe2c4412

**OS/device including version:**
Lubuntu 19.04

**Issue description:**
When editing tilemap you're expected to use LMB to place tiles and RMB to erase them. They are supposed to work the same way: if you hold mouse button and move the cursor you can "brush" tiles with LMB and erase with RMB.
RMB is broken (on my Lubuntu 19.04 at least, didn't try other one) here:
https://github.com/godotengine/godot/commit/017b224a87064a3d333ba63809a0f12cfe2c4412
With RMB continue to scroll the background, making the "eraser" impossible to operate

Attached animated PNG (hope Github don't mess with it)

sample

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #30875.
Fixup of #30713.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by groud** [comment]
Sorry I did not answered earlier, but I don't think that was the best way to implement this. InputEvents does provide an "handled" property that should have been used here I think.

**Comment by bojidar-bg** [comment]
@groud Hm, I don't see such a property on InputEvent.. Also, `accept_event()` is called _after_ `_gui_input_zoom_or_pan`.

**Comment by groud** [comment]
Yeah, this one, there is likely is_event_accepted too. 
This should be the normal way to precise an event was already handled. It's normal there are several place it should be called, whether it is before or after this function. It's not used a lot in the inspector though.

**Comment by groud** [comment]
Sorry forget what I said, this is supposed to stop events from propagating from one node to another. I don't really like the fact we have to add a weird "bool p_already_accepted" argument, but that might be the only way.

**Comment by bojidar-bg** [comment]
Well, there is another way -- put the `_gui_input_zoom_or_pan` call in the chain of `if`-s, then put only the `pan_pressed` part in another function (or directly in `viewport_gui_input`) which is called unconditionally.

**Comment by groud** [comment]
That might make more sense, and should likely be cleaner :)

**Pull request merged**
