### PR TITLE
Make ItemList selection box not include text

### PR DESCRIPTION
**Pull request by ghost**
Purely cosmetic, but I personally find the current `ItemList` selection a bit too high to be elegant:

master

With PR:

new

### CODE REVIEW

**Comment by groud** [comment]
I don't mind personally, bu it's probably compatibility breaking though.

**Comment by volzhs** [comment]
image

I'm using a custom font for the editor.
the selection box overlaps filename in my case with this PR.

**Comment by toger5** [comment]
Maybe downsizing the actual preview would make the whole editor look better.
than there also would be a little more spacing between text, preview.

example from OS X
screen shot 2018-03-28 at 02 26 40

**Comment by vnen** [comment]
The text should be highlighted, like @toger5's reference from OS X. All file managers that I remember also highlights the text.

**Comment by vnen** [comment]
As @groud said though, this might cause trouble for people using ItemList in other ways, so at least should be optional.

**Comment by akien-mga** [comment]
Personally I'm fine with the current looks, and I guess it will be difficult to reach a consensus as it's very much a matter of personal taste. I'm fine with the change if most users want it, but so far it doesn't seem to generate much enthusiasm.

As it's a compat breaking change and would impact games using ItemList, I'm also wary of such change. If there's a demand for it, it could make sense to add this as a parameter in ItemList (defaulting to the current system for compatibility) so that users can tweak it. I wouldn't expose it as an editor setting for the filesystem dock though.

**Comment by reduz** [comment]
I am also fine with the current way it looks..

**Pull request closed without merging**
