### PR TITLE
Make the icons in AnimationTrackEditor / BoneMapEditor store correctly

### PR DESCRIPTION
**Pull request by TokageItLab**
The same fixes pointed out in https://github.com/godotengine/godot/pull/71321#pullrequestreview-1248523968 were applied to AnimationTrackEditor. Also, the BoneMapEditor icons are now stored correctly.

### CODE REVIEW

**Comment by akien-mga** [comment]
I believe this should make use of the `theme_cache` structs @YuriSizov defined in various editor plugins. You can check e.g. `editor/plugins/mesh_editor_plugin.h` for an example of how it's defined and used.

**Comment by YuriSizov** [comment]
@TokageItLab I made the changes to use the theme cache and pushed to your branch. The bone mapper required extra work, since it already had a few classes that could benefit from this even before this PR, and because it didn't actually try to update the icons when the theme changed.

All code should be good now, but I don't have any project handy to test if it all works fine. Can you please double-check?

**Comment by YuriSizov** [comment]
Bump

**Comment by TokageItLab** [comment]
@YuriSizov I took a quick look and it seems that the current commit is causing BoneMapEditor to freeze, so I will investigate again later.

**Comment by TokageItLab** [comment]
It is probably out of date. I think others have solved some of the problems.

**Pull request closed without merging**
