### PR TITLE
Project Manager navigation improve

### PR DESCRIPTION
**Pull request by gamedevishard**
At the moment, keyboard navigation in the godot project manager is not intuitive. I tried to improve it
project_manager

Also, Buttons not related to local projects have moved to the top.
Before:
before2

After:
After

### CODE REVIEW

**Comment by AThousandShips** [comment]
Something pretty similar is already done in #50674

**Comment by AThousandShips** [comment]
I'd also suggest making a clean screenshot in an unmodified version of 4.2, to make sure the exact differences are clear (as it looks currently like the "before" has more contrast and more clear text)

**Comment by seppoday** [comment]
shameless plug, kinda related to that changes: https://github.com/godotengine/godot/pull/74561#issuecomment-1459976243

**Comment by AThousandShips** [comment]
Pinged the other PR and checked if they can rebase and update theirs, and suggested the two of you coordinate, and we'll see if they respond

I have some feedback ideas but I'll wait to see where we go between these two first, to spare everyone more work

**Comment by AThousandShips** [comment]
Closing as #70674 was closed, doing mostly the same thing

Thank you for contributing nonetheless

**Comment by starry-abyss** [comment]
And what's about keyboard navigation? I haven't touched it in that my PR.

**Comment by YuriSizov** [comment]
Improvements to keyboard navigation are welcome, though they should have been done as a separate PR anyway. So right now, a new PR focused on that should be made against the current master on top of your changes.

**Pull request closed without merging**
