### PR TITLE
Re-added the ability to set the angle from which one-way collision is active.

### LINKED ISSUE #12791: There is no way to set one-way collision directions
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 (x64), Godot 3 Alpha 2

**Issue description:**
In Godot 2.x, one-way collision was exposed in the form of a direction vector and a number for the maximum depth inside the body, which was great and fully customizable.
In Godot 3, all that is replaced with a boolean checkbox. Enabling it will make the shape only collide from the top, with no way to change this, at least none are exposed in the editor or outlined in any documentation for code. It always points up.

When the body rotates then this direction changes with the rotation just fine, meaning it can handle rotating the direction it's solid from.
Is there a reason the directional setting was removed?

As an aside, the documentation for `CollisionShape2D`'s [one_way_collision](http://docs.godotengine.org/en/latest/classes/class_collisionshape2d.html?highlight=collisionshape2d#member-variables) member states that you can somehow choose top or bottom, but it is always only solid from the top.
Which, by the way, is strange because the giant arrow that is drawn in the editor window always points down.

**Steps to reproduce:**
1) Create any `CollisionShape2D`, `CollisionPolygon2D` or `TileSet` tile with `One Way Collision` enabled.
2) Struggle to find a way to change the direction it is solid from.

### PR DESCRIPTION
**Pull request by timschellenberg**
As well as exposing them in the editor for CollisionPolygon2D, CollisionShape2D and TileSets.
Uses an angle instead of a directional vector as it did in 2.14, since the ability to toggle it on and off makes it easier to preserve the angle it had before it was turned off, which required a bit of housekeeping using the old vector method.

The side from which a shape is solid from is always displayed correctly in the editor now as well, displayed as an arrow pointing towards the edge that the shape is solid from, which I made a different color than it was before because it was hard to see the blue arrow on top of the blue collision shapes.

Closes #12791.

I learned C++ for this 2 days ago, so apologies if anything I did was egregiously wrong!

### CODE REVIEW

**Comment by reduz** [comment]
Heh, nice try but it's completely wrong :P

I would do this the following way:

1) Simply add a One Way Collision Angle to Shape
2) That value should be relayed to Physics2DServer as a vector for performance, some function like Physics2DServer::shape_set_one_way_collision_vector()
3) I would change the places where one way collision is checked, which are: body_shape_2d_sw.cpp (setup function), and space_2d_sw.cpp in the test_motion function (it also does check for KinematicBody)

TileMap,CollisionPolygon2D,etc. don't need any change at all.

If you want to give it another try, let me know if you need something!

**Comment by leoddd** [comment]
Gonna address these a bit out of order just to get the easier ones out of the way first:
Re: 3) What file do you mean by body_shape_2d_sw.cpp? I can't find any like that, and no file that sounds similar came up when I was looking through how one way collision is handled.
As for space_2d_sw.cpp, yea, that's  exactly what I did.
The 3 changes made to space_2d_sw.cpp in the test_body_motion are the only thing responsible for actually handling the collision_angle value I added to all the necessary classes. All it is doing is rotating the valid_dir Vectors that were previously always pointing upward to point towards the angle set by taking body rotation, shape rotation and the new angle value into account.
By the way, this was buggy before. The body would only ever be solid from the top, no matter how the body or shapes were rotated.


Re: 2) I have to admit I don't really know how to properly optimize this, because I'm not actually sure where the functions defined in physics_2d_server(_sw).cpp actually get called from. As far as I can tell, they never are and I really just added the one for the angle because I figured it would make sense to do so, since there also was a function for enabling one way collision and to disable the shape there.
What should I be changing here? Could you explain to me what these functions are used for?


Re: 1) This suggestion I'm a little bit confused about. It might just be that I am massively misunderstanding how the shapes system works, but none of the actual Shape2D classes have any information about their current physics state defined in them, as far as I can tell that is all handled by the shape owner.
It's a little bit more confusing because `one_way_collision_enabled` was found in exactly the classes I edited too, namely TileSet, CollisionShape2d and CollisionPolygon2D. Which I think makes sense, right? Since the shape classes themselves aren't actually used exclusively for physics, but also for things like drawing polygons with a regular Polygon2D node. It makes sense to me to keep that information out of the shape classes and retain it in the Body and Collision classes, where all the other information used for physics calculations is stored.

Additionally, even if we were to make an exception for this new member for some reason and move it to the Shape classes themselves, I think it would be sort of weird if the setting to enable one-way collision was in the editor helper classes CollisionPolygon2D and CollisionShape2D, but the actual angle to set that one-way direction is moved to the shapes.

**Comment by leoddd** [comment]
@reduz I'd like to get this in before the feature freeze but am still not very sure what to change right now, since I feel like I've mostly done exactly what you suggested to do.

Just to lay that out again, the only reason TileSet, CollisionPolygon2D etc. were edited was so that you can set the angle on each shape through the inspector, as well as tweaks to the arrow drawn in the editor window. All they do is edit the angle value that I gave Shape (as you had suggested).
They don't hold any new logic that checks for collision or anything, so even if I were to redo this I can't think of any way to make the angle variable show up in the inspector without editing those files.

The actual change in logic for this is all in space_2d_sw.cpp, where I only changed the way it calculates the normal it will detect collisions from (which I think is what you suggested as well).

**Comment by eon-s** [comment]
If this is ok to merge could be good to have it to test for any issues during beta period.

**Comment by leoddd** [comment]
I tried to resolve the conflicts, but that just made builds fail, oops. The changes work fine on my local copy so I'm not sure why that is..

**Comment by leoddd** [comment]
Since this is woefully outdated and wasn't the desired route to begin with, I'll close this for now.
Hope someone who knows how to work this out properly can do that eventually!

**Comment by akien-mga** [comment]
Thanks for your contribution though, it definitely gives a base to start another implementation. It will likely only happen for 3.1 though, but that should arrive soon.

**Pull request closed without merging**
