### PR TITLE
[3.2] Update get_configuration_warning() overrides to retrieve warnings from parent class

### PR DESCRIPTION
**Pull request by arrowinaknee**
Updated all get_configuration_warning() overrides to first retrieve warnings from parent class

Fixes issue #37224 

Tested with [this project](https://github.com/arrowinaknee/godot_warning_issue_demo)

### CODE REVIEW

**Comment by MCrafterzz** [comment]
Progess?

**Comment by kopcion** [comment]
Well, since it seems like there is no progress being made, I thought I could finish this issue. Found two more files to fix, scene/2d/navigation_obstacle_2d.cpp and scene/2d/navigation_agent_2d.cpp.

**Comment by akien-mga** [comment]
Note that Pull Requests should be made against the `master` branch, which is the main development branch. All stable releases are branched from `master`, so if we don't get the fix there, Godot 4.0 and later won't have it.

It can then be cherry-picked for `3.2` branch by release maintainers.

The commits should also be squashed into one, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by arrowinaknee** [comment]
@akien-mga
I fixed the thing for `master` branch in another branch of my fork but I don't seem to find any way to switch to it here. Is there any way of doing that or should i just make a new PR?

**Comment by arrowinaknee** [comment]
I made another PR (#38743) with another branch from my fork targetet to master branch. Should I close this one now?

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
