### PR TITLE
fix multitouch release problem

### LINKED ISSUE #1884: [1.1 rc2] Bug:screentouch multitouch pressed sequence wrong
when I put my fingers on screen  with two hands .

here is the touch index :
(left) 0-> (right)1->(right)2->(right)3->(right)4
released at this order:
(right)1->(right)2->(right)3->(right)4->(left) 0

then it won't set   index 2-4 pressed zero until I released 0.

there is log with grep ScreenTouch about it .I do each step about 1 sec.Not unitl I release index:0 ,index:2-4 won't released.
```
(hour:23), (minute:15), (second:17)Device 0 ID 3 Event: ScreenTouch Pressed: 1 Index: 0 pos 142,714
(hour:23), (minute:15), (second:20)Device 0 ID 7 Event: ScreenTouch Pressed: 1 Index: 1 pos 1677,610
(hour:23), (minute:15), (second:20)Device 0 ID 9 Event: ScreenTouch Pressed: 1 Index: 2 pos 1285,524
(hour:23), (minute:15), (second:21)Device 0 ID 11 Event: ScreenTouch Pressed: 1 Index: 3 pos 974,461
(hour:23), (minute:15), (second:22)Device 0 ID 15 Event: ScreenTouch Pressed: 1 Index: 4 pos 658,795
...
begin to release fingers
...
(hour:23), (minute:15), (second:23)Device 0 ID 18 Event: ScreenTouch Pressed: 0 Index: 1 pos 1677,610
...
here I released index 234 as sequence.but no feedback
...
(hour:23), (minute:15), (second:29)Device 0 ID 39 Event: ScreenTouch Pressed: 0 Index: 0 pos 142,714
(hour:23), (minute:15), (second:29)Device 0 ID 40 Event: ScreenTouch Pressed: 0 Index: 2 pos 1285,524
(hour:23), (minute:15), (second:29)Device 0 ID 41 Event: ScreenTouch Pressed: 0 Index: 3 pos 974,461
(hour:23), (minute:15), (second:29)Device 0 ID 42 Event: ScreenTouch Pressed: 0 Index: 4 pos 658,795
```

### PR DESCRIPTION
**Pull request by vipsbpig**
In android view godot send a wrong touchid, fixed the android about release problem. resolved #1884

### CODE REVIEW

**Comment by Razzlegames** [comment]
Shouldn't this be?:
```java
final int indexPointUp = (event.getAction() & ACTION_POINTER_INDEX_MASK)
   >> MotionEvent.ACTION_POINTER_INDEX_SHIFT;
```

http://developer.android.com/reference/android/view/MotionEvent.html

"Bit shift for the action bits holding the pointer index as defined by ACTION_POINTER_INDEX_MASK."

**Comment by vipsbpig** [comment]
@Razzlegames Yes , you are right,your fix is probably the safest way.I make a mistake.However,old one works well on my devices.But on other device maybe it won't works well.

**Comment by reduz** [comment]
send me a new pr with updated fix

**Comment by Razzlegames** [comment]
Here's the problem.  I don't see how this solved your issue, unless you were using a SDK with a bug.  The actual code SDK for ```getActionIndex(...)``` is the corrected version I suggested:

```java

    /**
     * Call {@link MotionEvent#getAction}, returning only the pointer index
     * portion
     */
    public static int getActionIndex(MotionEvent event) {
        return (event.getAction() & ACTION_POINTER_INDEX_MASK)
                >> ACTION_POINTER_INDEX_SHIFT;
    }
```

**Comment by Razzlegames** [comment]
Oh I'm sorry I see the fix, I think it should be this:

```java
final int indexPointUp = event.getActionIndex();
final int pointer_idx = event.getPointerId(indexPointUp); 
```

**Comment by Razzlegames** [comment]
I'll push a patch

**Comment by Razzlegames** [comment]
Hey @vipsbpig can you let me know if this patch still works for you?  
https://github.com/okamstudio/godot/pull/2017

Unless there's a bug in your SDK it should be correct.

**Comment by vipsbpig** [comment]
@Razzlegames I test your code .It did fix my problem .Good Job!
The old code I was found in cocos2d-x engine.It is very weired that this code will work great in my old games in any sdk I tried.

**Comment by Razzlegames** [comment]
Cool, thanks for confirming and glad it worked!

Re: Working before:  

There was probably no intersecting data to be masked in those cases.  In other words, it's either a rare edge case, or a future reserved area that can never happen now.

 Not sure what the mask (I didn't look it up)  but e.g.: if it were 0xFFFF0000 and the data to be masked was just 0xDEAD0000

0xFFFF0000 & 0xDEAD0000 = 0xDEAD0000

So no difference, even though the mask should always remove the lower 16bits etc.  Just a thought... not 100% on the bit meanings.

**Pull request merged**
