### PR TITLE
Fixes wrong vertical font layout in RichTextLabel

### PR DESCRIPTION
**Pull request by ghost**
In rc1, `RichTextLabel` computes the wrong vertical text offsets for lines with multiple fonts, as it lacks a proper layout step that determines the common baseline for a whole line that all fonts will be rendered on.

This fixes it. Not yet extensively tested.

Before:

before

After:

fixed

### CODE REVIEW

**Comment by poke1024** [comment]
Also happened with different font sizes; before:

master

Fixed:

fixed

**Comment by hpvb** [comment]
This PR caused a regression. See #17139

**Comment by hpvb** [comment]
Potential fix: #17144

**Comment by hpvb** [comment]
Another potential fix: #17145 <-- this one looks better I think

**Pull request merged**
