### PR TITLE
Add usage of indeterminate checkboxes to editor

### PR DESCRIPTION
**Pull request by KoBeWi**
Follow-up to #50752

fk0j6sQ15D
kdbmULZpIO

Let me know if I missed someplace where it could be also added.

### CODE REVIEW

**Comment by pycbouh** [comment]
Editor feature manager, perhaps?

**Comment by KoBeWi** [comment]
Feature manager seems to have different behavior. When parent is checked, it doesn't automatically check all children and if you uncheck it, the chilldren disappear from tree.

**Comment by pycbouh** [comment]
I'm concerned that the intermediate status is not easily readable on the icon that we use. Maybe it should be gray instead of blue or have a colored border instead of being filled?

**Comment by Calinou** [comment]
Some things we can try for the indeterminate checkbox color:

- Keep the unchecked background color, make the hyphen have the accent color.
- Or set the background accent color's opacity to 50%.

**Comment by pycbouh** [comment]
Some visual aid of options by Calinou and me (in the order of proposals):

half-tick-options

half-tick-options x2

**Comment by bruvzg** [comment]
> Let me know if I missed someplace where it could be also added.

The character range list in the Font "Advanced Import Settings" dialog might use this to indicate fully and partially selected ranges, in the same way BMFont generator do.

Screenshot 2021-09-25 at 15 28 47

Screenshot 2021-09-25 at 15 26 57

**Comment by KoBeWi** [comment]
> I'm concerned that the intermediate status is not easily readable on the icon that we use. Maybe it should be gray instead of blue or have a colored border instead of being filled?

Maybe it could be done in a separate PR, as it's not strictly related.

> The character range list in the Font "Advanced Import Settings" dialog might use this to indicate fully and partially selected ranges

I'll check it out.

**Comment by KoBeWi** [comment]
Ok added:
DV3onieu9I

**Comment by lyuma** [comment]
I don't know if clicking on the list item should force the whole thing to checked or unchecked if it's indeterminate.

Imagine you selected only a few glyphs in one range such that it shows [-] indeterminate. If selecting it checks all or unchecks all, how can you see which glyphs are selected?

would it not make more sense to require clicking the checkbox itself, at least in the case that it's in the [-] state?

**Comment by KoBeWi** [comment]
It's toggled on double-click (`item_activated` signal), selecting only changes the view. It can't be on checkbox click, because editable TreeItem only detects clicks on its whole area (i.e. checkbox and text).

**Comment by bruvzg** [comment]
> I'm concerned that the intermediate status is not easily readable on the icon that we use.

Maybe old Windows (non UWP) style will be more readable.
Screenshot 2021-09-26 at 22 50 22

**Comment by KoBeWi** [comment]
So as I said, this PR is only about the usage of indeterminate checkboxes. I opened a separate issue to discuss their appearance: #53101
It can be resolved independently.

**Comment by KoBeWi** [comment]
Rebased after #53276, the font import changes are stil relevant and don't use the new API.
I also included a minor fix for the docs.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
