### PR TITLE
Initial support for arm64-v8a

### PR DESCRIPTION
**Pull request by bvbfan**
Signed-off-by: Anthony Fieroni bvbfan@abv.bg

### CODE REVIEW

**Comment by wkubiak** [comment]
The platform:android label would be nice for this :)

**Comment by akien-mga** [comment]
Could you squash the two commits together as they cater to the same topic? Also ideally, removing the brackets would make the commit log better suited with regards to existing commits logs in Godot's repo ;)

**Comment by akien-mga** [comment]
There is now a merge conflict to resolve, as you had actually committed the same changes as in your other PR (#6723).

While you rebase, if you can remove the brackets in the commit log, that would satisfy my OCD of clear git history :)

**Comment by bojidar-bg** [comment]
Uh, better rebase the merge commit out before @akien-mga sees it :D

**Comment by bvbfan** [comment]
massacre

**Comment by bvbfan** [comment]
https://github.com/godotengine/godot/pull/6919
I made it on clean fork.

**Pull request closed without merging**
