### PR TITLE
Add option to export Geometry Nodes Instances in Blender importer

### LINKED ISSUE #8991: Add support for importing Geometry Nodes instances from .blend files
### Describe the project you are working on

Any 3D Project Using the .blend importer

### Describe the problem or limitation you are having in your project

importing Geometry Nodes Instances doesn't work.

it work trough GLTF though, look at this tweet:
https://twitter.com/passivestar_/status/1752195836950315347

this probably because the Godot blend importer doesn't check the option while importing.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add support for checking this option (coming in Blender 4.1)

image

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

PR:
https://github.com/godotengine/godot/pull/87735

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

### PR DESCRIPTION
**Pull request by ywmaa**
Should close: https://github.com/godotengine/godot-proposals/issues/8991

### CODE REVIEW

**Review by fire — COMMENTED** [review]
I approve of `Export Geometry Nodes Instances in blend importer` as as a Godot Engine proposal. I haven't done the technical review yet.

**Comment by ywmaa** [comment]
Hey, I just gave this PR a test, it works great if this is solved:
https://projects.blender.org/blender/blender/issues/122237

which is already solved, I think it will land with a new blender 4.1 minor release and/or with 4.2 release.

I think we can safely merge this PR if the issue on blender side is included with their distrubted blender version.

**Comment by ywmaa** [comment]
I kindly suggest merging this PR as it adds only 9 lines of code, that hopefully won't break anything, and the feature will be there once blender includes the fix on their end.

also the geometry nodes feature will only work if blender's major is 4 and minor is 1 or more, meaning it shouldn't do anything to users who still use blender 3.x as the importer.

**Review by fire — APPROVED** [review]

**Comment by ywmaa** [comment]
Great news, Blender 4.2 (Development) now has the issue solved:
https://projects.blender.org/blender/blender/issues/122379#issuecomment-1200660

so this PR will work with 4.2 without the 4.1 workaround.

This PR as it is now should work with 4.1 (with the workaround), and 4.2 and up (without any workaround).

**Comment by warcaninos** [comment]
Could this be merged for 4.3 or is it planned for 4.4 ?

**Comment by AThousandShips** [comment]
For 4.4 at the earliest, we're not accepting new features for 4.3 at this time

**Comment by ywmaa** [comment]
I just rebased and tested it with the new released Blender 4.2 LTS, and it works!

this PR should be ready when the door opens for Godot 4.4.

**Comment by ywmaa** [comment]
is it possible for this to get merged since 4.4 is now WIP ?

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
