### PR TITLE
Update Array.xml for negative array indexing

### PR DESCRIPTION
**Pull request by BornStellarMakesEternalLasting**

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Hey! Thanks for your first contribution.

Can you please squash those commits into one? :) Thanks.

Example: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

If you need more guidance, feel free to let us know here or on the development IRC (#godotengine-devel on Freenode IRC)

**Comment by akien-mga** [comment]
Thanks for the contribution! I went ahead and pushed an enhanced version with a code example to make things more explicit.

**Comment by akien-mga** [comment]
@hpvb adb16be can be cherry-picked.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request closed without merging**
