### PR TITLE
Improve Visual Shader Editor responsiveness

### PR DESCRIPTION
**Pull request by MarianoGnu**
According to 1.2 plan i'm working in the next points:
- [x] Shader new node placement
- [x] Multiple GraphNode selection and move
- [x] Box selection
- [x] Delete key removes nodes
- [x] Shader nodes duplicate
- [x] Default shader nodes values
- [ ] ~~Zoom for Visual Shader Editor~~

### CODE REVIEW

**Comment by reduz** [comment]
About to take the plane back to buenos aires, will check when I arrive

**Comment by MarianoGnu** [comment]
Box selection added.

Hold <Control> to make an additive selection without losing previous node selection:
sin titulo

Hold <Shift> to deselect nodes inside the rectangle:
sin titulo

**Comment by mamarilmanson** [comment]
I wonder why you went to Ctrl as additive and Shift as Subtractive? :)

**Comment by MarianoGnu** [comment]
Control is default for aditive selections on file browsers, maybe alt should be fine for substractive, i just felt this was enought straightforward (people usually learn these stuff just trying out)

**Comment by mamarilmanson** [comment]
Oh ok... here's what's really happening in other software/file browser...

SHIFT is for selecting multiple objects at the same time...
CTRL is for selecting multiple objects one at a time...
ALT is for Subtractive...

hope this info helps... :)

**Comment by reduz** [comment]
check how godot does it and do the same, honestly this is different in
every software

**Comment by zhagsenkk** [comment]
why not allow users to set shortcuts themselves?

**Comment by mamarilmanson** [comment]
That's the best idea... :+1: for that... I don't know how to code godot... so all I can give are ideas, suggestion and moral support...

@MarianoGnu ~ Please do implement custom shortcuts... :)

**Comment by reduz** [comment]
no custom shortcuts for now

**Comment by MarianoGnu** [comment]
A little addition to PR roadmap: Dele key remove selected nodes (except for Output of course)

**Comment by MarianoGnu** [comment]
I give up into implementing UI zoom... @reduz , @okamstudio you can merge this alredy if you want

**Comment by reduz** [comment]
no worries, i can try implementing this

**Comment by MarianoGnu** [comment]
@reduz this is finally fixed and ready to merge

**Pull request merged**
