### PR TITLE
Add an outlined version of logo.png and icon.png and put it in README.md

### LINKED ISSUE #44244: Godot Engine's SVG logo contrast is too low on Github's beta dark mode
Since Github finally added a (beta) dark mode, The words "Godot game engine" don't contrast enough with the dark background, making reading them a little too hard.
immagine

Maybe there should be an outline of sorts?

### PR DESCRIPTION
**Pull request by deralmas**
Fixes #44244 .
This PR adds an outlined version of both `logo.png` and `icon.png` for when the background colour might hide some elements, and replaces the regular version in the README.
Honestly the whole logo affair should be more discussed about, as there are some proposals for adding a press kit(see godotengine/godot-website#44), but I understand that this isn't a very high priority thing right now.

Before:
before

After:
after

There are a few holes in between some letters, but I don't know if I should fill them. Tell me if you'd prefer it this way.

### CODE REVIEW

**Comment by Riteo** [comment]
Oh, I deleted it by accident. I noticed just now.

**Comment by Riteo** [comment]
@Calinou could you remove the "archived" label? Sorry for the trouble.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
Since this can be cherry-picked to the `3.x` and `3.3` branches without conflicts, could this PR be cherry-picked to those branches? Thanks in advance :slightly_smiling_face:

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
