### PR TITLE
Add editor setting to enable or disable zooming with ctrl + Mouse wheel

### LINKED ISSUE #7997: Allow to disable script editor zoom shortcut
### Describe the project you are working on

Game with GDScript.

### Describe the problem or limitation you are having in your project

When writing some code in the built-in editor, I accidentally zoom the code surprisingly often. This causes editor settings save after ~2 seconds, which freezes the whole editor for a few seconds. If I don't undo the change quick enough, I'm getting another freeze after I reset the zoom. This is outrageous waste of time and there is no way to disable it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a way to disable script editor zoom shortcut, probably with an editor setting.

An alternative solution is of course fixing the freeze, but the editor setting for font size sits in `interface/editor`, which causes theme invalidation with every change. The only fix I can think of is moving this to another section.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Disable this
https://github.com/godotengine/godot/blob/d31794c4a26e5e10fc30c34a1ae9722fd9f50123/editor/code_editor.cpp#L821-L829

### If this enhancement will not be used often, can it be worked around with a few lines of script?

With a good amount of hacks, probably.

### Is there a reason why this should be core and not an add-on in the asset library?

It's much easier to implement in the source itself.

### PR DESCRIPTION
**Pull request by Stronkkey**
Supersedes #82928
Fixes [godot-proposals#7997](https://github.com/godotengine/godot-proposals/issues/7997)
PIC
Tooltip text: `If true, allows zooming in the script and text-based shader editor with [kbd]Ctrl + Scroll wheel[/kbd].`

### CODE REVIEW

**Comment by AThousandShips** [comment]
Needs a rebase

**Comment by Stronkkey** [comment]
Damn  messed up my commit history again

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by AThousandShips** [comment]
See the above instructions on how to fix it

**Comment by Stronkkey** [comment]
I do not have the expertise to fix this Merge request.
Closed indefinitely.

**Comment by AThousandShips** [comment]
I can help you if you need, but it'd be good to learn rebasing as it's an important skill in the PR workflow

**Pull request closed without merging**
