### PR TITLE
In CanvasItemEditor, prioritize selected items when dragging

### PR DESCRIPTION
**Pull request by ghost**
In master, when you try to drag an item that is selected but not the front-most visible, the item will get deselected (in the gif below, the green poly gets selected, even though I want to drag the red poly):

master

In complex scenes, where you want to drag a partially hidden object, this can get very annoying, since you have to find one visible inch of the object in order to get hold of it even though you've picked and selected it in the scene tree beforehand. I think that selected items should get prioritized; if the click is in the currently selected items, don't select something else, but just drag. This is what this PR effects:

demo

If no selection is there, then, of course, clicking at the point above will select the green poly again.

Demo project:

[SelectionTest.zip](https://github.com/godotengine/godot/files/1778494/SelectionTest.zip)

### CODE REVIEW

**Comment by Zylann** [comment]
The workaround for this is to press [alt], but I agree that's annoying

**Comment by groud** [comment]
This is probably not what should be done, checking afterwards if the click is inside the polygon (in the the `_gui_input_select` function is not a good idea, since it breaks the way I organized the `_gui_input* `functions.
Since the `_gui_input_move` is called before the `_gui_input_select`, this function should be able to return true (thus catching the event) before the `_gui_input_select` one.

**Comment by groud** [comment]
In fact the problem is at line 1499, since the functions returns true only if the object has been moved.
If should confirm the action (call _commit_canvas_item_state) only if the object has been moved but should return true in any case if the click is on the object.

**Comment by groud** [comment]
Ok, forget what I've just said. Your code is almost ok.
The only problem I have is that you define a new function that does almost exactly what `_find_canvas_items_at_pos()` does two lines after you call your own function.

It would be better if you could use the results of `_find_canvas_items_at_pos()` this function instead of defining a new one, probably by comparing the actual selection and the results from `_find_canvas_items_at_pos()`

**Comment by poke1024** [comment]
@groud That's true, what I did was clumsy. Changed to a much simpler approach now that simply checks if the pick list contains selected items.

**Comment by groud** [comment]
Ok, Looks good to me :)

**Review by groud — APPROVED** [review]

**Comment by hpvb** [comment]
Note to self: See if this makes sense in 3.0, and if so cherrypick/packport.

**Comment by groud** [comment]
It probably does not since it is due to my big rework of the CanvasItemEditor code

**Comment by volzhs** [comment]
after using editor for a couple of days with this PR, I felt it's like a bug.
I opened an issue with it #18128

**Comment by volzhs** [comment]
I think another node should be selected if user does not drag, at least.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
