### PR TITLE
HTTPClient: Keep the header value field case

### LINKED ISSUE #3767: HTTPClient Headers - Discussion
The HTTPClient makes the whole header to lower case that destroys one of my header values(linux path to a file)

https://github.com/godotengine/godot/blob/3db379376fd55a1d5851bf6172affd0765b67b7c/core/io/http_client.cpp#L310

http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

So maybe godot could provide the raw header and one that is to_lower() or leave the header as he is.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #3767

### CODE REVIEW

**Comment by AlexHolly** [comment]
response_headers.push_back(name_value[0]+":"+name_value[1]);

You sould add all name_value[] not only 0 and 1 
A value could have a ":" this will be removed.
I don't think that escaping is used in header values only in the request(URL) https://en.wikipedia.org/wiki/Percent-encoding

Example:
(uri:http://someurl.test) -> (uri:http)

**Comment by AlexHolly** [comment]
response_headers.push_back(name_value[0]+":"+name_value[1]);

You sould add all name_value[] not only 0 and 1 
A value could have a ":" this will be removed.
I don't think that escaping is used in header values only in the request(URL) https://en.wikipedia.org/wiki/Percent-encoding

Example:
(uri:http://someurl.test) -> (uri:http)

**Comment by AlexHolly** [comment]
response_headers.push_back(name_value[0]+":"+name_value[1]);

You sould add all name_value[] not only 0 and 1 
A value could have a ":" this will be removed.
I don't think that escaping is used in header values only in the request(URL) https://en.wikipedia.org/wiki/Percent-encoding

Example:
(uri:http://someurl.test) -> (uri:http)

**Comment by neikeq** [comment]
@AlexHolly you are right. I will rebase ASAP.

**Comment by punto-** [comment]
ok try my commit, that should fix it. The script gets the original headers
without case mangling (or anything else except strip_edges)

**Comment by neikeq** [comment]
@punto- what commit?

**Comment by punto-** [comment]
ok, now it's there, b7c504, I don't know why it became 2 commits tho.

**Comment by neikeq** [comment]
So we push the header with its original case and let the user handle that?

**Comment by neikeq** [comment]
Closed this PR since @punto- commit solves the problem. But we must specify somewhere that the headers are no longer lower case (to avoid breaking someones code).

**Comment by AlexHolly** [comment]
Yes now it leaves the key as it comes in. I used the same solution, this will break current code that is checking vor lower case keys. Maybe its okay to use this solution because its 2.0 anyway...

**Comment by punto-** [comment]
the lower case patch is relatively new, from a couple of weeks..

**Pull request closed without merging**
