### PR TITLE
Add "-rigid" suffix import feature to create rigid bodies

### PR DESCRIPTION
**Pull request by jay3d**
This feature will help setup and create scenes with many rigid bodies
automatically from Collada files (think dominos)

### CODE REVIEW

**Comment by slapin** [comment]
Like this
It is so good somebody finally done this.

**Comment by ilearain** [comment]
:cool:

**Comment by bojidar-bg** [comment]
:+1:

**Comment by zhagsenkk** [comment]
THX

**Comment by reduz** [comment]
was this missing? if so no need to close it

**Comment by jay3d** [comment]
Sorry I was resetting the the fork, I will update it again

**Pull request closed without merging**
