### PR TITLE
Ensure indentation works properly in rich text

### LINKED ISSUE #29810: Editor help no longer displays correctly
**Godot version:** Git https://github.com/godotengine/godot/commit/89ce9a6f4694711e383c3d3e42141d176a12529e

**OS/device including version:** Fedora 30, Clang 8.0.0

**Issue description:** The editor help no longer displays correctly. This is likely a regression from https://github.com/godotengine/godot/pull/29785. Maybe the editor help generation needs to be modified to take the above PR into account?

## 3.1.1 stable (good)

doc_3 1 1_1_good
doc_3 1 1_2_good

## Master (bad)

doc_master_1_bad
doc_master_2_bad

**Steps to reproduce:** Open any class in the editor help.

### PR DESCRIPTION
**Pull request by eligt**
Ensure indentation works properly in rich text

Fixes #29810.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Please make the commit message more descriptive.

**Comment by akien-mga** [comment]
A tip for commit logs: the first line (title) should be terse but explicit, and indicate in English what the commit does. References to issues being fixed can go in the commit log's body, and use relevant keywords: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Should be cherry-picked only if #29785 gets cherry-picked.

**Pull request merged**
