### PR TITLE
Remove `@GDScript.str` (duplicate of `@GlobalScope.str`)

### PR DESCRIPTION
**Pull request by dalexeev**
https://github.com/godotengine/godot/blob/833c0d24dbf3c442857fd9d7b1fd17918fadddc9/core/variant/variant_utility.cpp#L722-L742

https://github.com/godotengine/godot/blob/833c0d24dbf3c442857fd9d7b1fd17918fadddc9/modules/gdscript/gdscript_utility_functions.cpp#L115-L135

See [the comment](https://github.com/godotengine/godot-proposals/issues/1590#issuecomment-1170289422).

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by dalexeev** [comment]
Maybe we should remove `@GlobalScope.str` instead? `@GDScript` has `char` function, it makes sense if both are in the same place.

**Comment by vnen** [comment]
> Maybe we should remove `@GlobalScope.str` instead? `@GDScript` has `char` function, it makes sense if both are in the same place.

Note that `@GlobalScope` functions are available to other languages besides GDScript and to GDExtension as well, so I wouldn't remove the global one.

**Review by vnen — APPROVED** [review]

**Comment by dalexeev** [comment]
> Note that `@GlobalScope` functions are available to other languages besides GDScript

In this case, maybe we should move `char` to `@GlobalScope` as well?

`str()` is just `vararg` equivalent of `String()`. It seems to me that `str` and `len` were added to resemble Python.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
