### PR TITLE
SCsub: Add python shebang as a hint for syntax highlighting

### PR DESCRIPTION
**Pull request by akien-mga**
It's a Unix shebang but I know at least from @vnen that it works as a hint for python syntax highlighting in Notepad++ on Windows.

Works fine for syntax highlighting in Kate and nano.

### CODE REVIEW

**Comment by zaps166** [comment]
Also `#!/usr/bin/env python` can be used :)

**Comment by akien-mga** [comment]
> Also #!/usr/bin/env python can be used :)

True, but I've seen it used less often and wasn't sure that all text editors would recognize it properly. But I haven't tested it to confirm :)

**Comment by zaps166** [comment]
Works on Kate and Notepad++ :)

**Comment by akien-mga** [comment]
Rebased to use the env one ;)

**Comment by hubbyist** [comment]
Note: bin/SCsub, bin/tests/SCsub shebang's are different from other files.

**Comment by akien-mga** [comment]
Looks like [ripgrep](https://github.com/BurntSushi/ripgrep) ignores `bin/` folders, so I missed those when doing the search and replace :)

**Pull request merged**
