### PR TITLE
Fixed white image in margins when using same image in scene

### PR DESCRIPTION
**Pull request by azagaya**
Fixes white margins discussed in here  #40135

### CODE REVIEW

**Comment by lawnjelly** [comment]
Yes this is fine imo.

The problem is that white is being set directly with a glBindTexture, and thus invalidating `state.current_tex`. So to set the texture either needs calling glBindTexture directly, or forcing as in the PR.

I would double check that this isn't necessary in GLES2 as well. Check both with batching switched on and off. I'd be tempted to use the same technique in GLES2 irrespective of whether it is currently needed, because the bug may well crop up again in GLES2, and may only be working there 'by accident', so a pre-emptive approach may be wise (welcome opinion from @clayjohn / @reduz on that).

**Comment by azagaya** [comment]
@lawnjelly hey! The `_bind_canvas_texture` method does not have the force parameter in GLES2, so i cannot implement the same approach.

**Comment by lawnjelly** [comment]
Imo it would probably be ok with to leave it for now and keep an eye on GLES2 to see if that situation does occur in the wild before changing it. However as always would welcome other views, I'm not strongly opinionated one way or the other.

**Comment by akien-mga** [comment]
Let's merge as is and we can iterate later if more changes are needed.

It only impacts the non-default code path where margin textures are used, and seems to fix bugs, so it's low risk :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
