### PR TITLE
fixes #46839, ensure library_classes is cleared and free funcs are ca…

### LINKED ISSUE #46839: GDNative: exporting properties crashes Godot at exit.
*See originating issue https://github.com/godot-rust/godot-rust/issues/706*

**Godot version:**
3.2 branch, https://github.com/godotengine/godot/commit/311ca0c6f23784dfa831d8f058a335f698dcc5ea

**OS/device including version:**
Windows 10

**Issue description:**
I am using the Rust GDNative binding with a custom-built Godot version. Everything works fine, until I export a Rust field, to be accessible as a property from GDScript.

Then, the engine starts and appears to run normally, however it crashes on exit with the following log:
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] NativeScriptLanguage::_unload_stuff (D:\godot\modules\gdnative\nativescript\nativescript.cpp:955)
[3] NativeScriptLanguage::finish (D:\godot\modules\gdnative\nativescript\nativescript.cpp:1077)
[4] ScriptServer::finish_languages (D:\godot\core\script_language.cpp:185)
[5] Main::cleanup (D:\godot\main\main.cpp:2247)
[6] widechar_main (D:\godot\platform\windows\godot_windows.cpp:164)
[7] _main (D:\godot\platform\windows\godot_windows.cpp:184)
[8] main (D:\godot\platform\windows\godot_windows.cpp:196)
[9] __scrt_common_main_seh (D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[10] BaseThreadInitThunk
-- END OF BACKTRACE --
```

@toasteater had the suspicion it could be this commit (see link above):
```
Revision: 311ca0c6f23784dfa831d8f058a335f698dcc5ea
Author: geekrelief <geekrelief@gmail.com>
Date: 23.12.2020 15:23:41
Message:
Removes the gdnative library when no script (gdns) references it any longer. This enables hot reload for gdnative.

(cherry picked from commit cc5d8bb5adf46aef63828fb23095589e51cca783)
----
Modified: modules/gdnative/nativescript/nativescript.cpp
```

After building both this and the prior version, both toasteater and I can confirm that this is the first commit that leads to the crash.

**Steps to reproduce:**

Set up simplest possible GDNative Rust project, 1 single class (I used godot-rust's _Hello World_ example).
Add an exported property to that class:
```rust
#[property]
my_property: u32
```
Launch Godot.
Exit... 💥 

**Minimal reproduction project:**

[My fork of godot-rust, `crash` branch](https://github.com/Bromeon/godot-rust/tree/crash)

### PR DESCRIPTION
**Pull request by geekrelief**
…lled

Co-authored-by: toasteater <48371905+toasteater@users.noreply.github.com>
Co-authored-by: Jan Haller <bromeon@gmail.com>

*Bugsquad edit:* Fixes #46839

### CODE REVIEW

**Comment by Bromeon** [comment]
Thank you very much for the efforts! 👍🏼 

Are such bugfixes generally backported to the 3.2 branch? (godot-rust uses that one).

**Comment by geekrelief** [comment]
> Thank you very much for the efforts! 👍🏼
> 
> Are such bugfixes generally backported to the 3.2 branch? (godot-rust uses that one).

Calinou set it for cherrypick:3.2, so hopefully we'll get a merge soon.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Pull request merged**
