### PR TITLE
Particles: fix corrupted scene when saved after convert

### LINKED ISSUE #16353: Converting a ParticlesMaterial that uses a trail scale curve to a ShaderMaterial corrupts scene file
**Godot version:**
3.0

**OS/device including version:**
Kubuntu 14.04

**Issue description:**
If you have a Particles node with a ParticlesMaterial that has a trail scale curve assigned to it, converting it to a ShaderMaterial corrupts the tscn file. After saving the scene the game will refuse to open, and after closing the scene it gives the following error after loading the scene again:

```
ERROR: poll: res://main.tscn:200 - Parse Error: Unexpected identifier: 'sub_resource'.
   At: scene/resources/scene_format_text.cpp:523.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:149.
ERROR: _load: Failed loading resource: res://main.tscn
   At: core/io/resource_loader.cpp:186.
```

I've opened the file and it seems to be caused by an invalid shader uniform, with a missing value:
```
shader_param/trail_size_modifier = 
```
After removing that line, the scene file seems to be loaded successfully again.

**Steps to reproduce:**
1. Create Particles node
2. Assign a ParticlesMaterial process material and a draw pass mesh to it
3. In the ParticleMaterial, assign a trail scale curve
4. Go back to the Particles node, click the arrow next to it and select "Convert to ShaderMaterial"
5. Save the scene and close it
6. Try loading the scene again - you'll notice it throws an error 

**Minimal reproduction project:**
[particle_bug.zip](https://github.com/godotengine/godot/files/1691858/particle_bug.zip)
Open the project, select the ParticlesMaterial and convert it to a ShaderMaterial. After saving the scene and closing it you'll notice you cannot open it anymore.

### PR DESCRIPTION
**Pull request by ghost**
~~trail params are not in the param list, so it returns null when converted. Saving it causes corrupted scene.~~

Some params are pass as RID while it should be Texture, so it can't be saved to file.

Fixes #16353

### CODE REVIEW

**Comment by reduz** [comment]
Can you check this in SpatialMaterial and CanvasItemMaterial?

**Comment by reduz** [comment]
other than that it seems fine

**Comment by Noshyaar** [comment]
SpatialMaterial is not affected: albedo, metallic, roughness are saved correctly.
CanvasItemMaterial is not affected as it doesn't take textures.

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Pull request merged**
