### PR TITLE
Fix incorrect sky rotation based on camera axis

### LINKED ISSUE #56136: Vulkan: Environment custom sky rotation is not rendered correctly
### Godot version

4.0.dev (489f11ee0)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The environment custom sky rotation is not rendered correctly. The sky rotates wildly depending on the camera's angle in an unexpected manner.

### `3.x` (works as expected)

https://user-images.githubusercontent.com/180032/146974985-b3092e6c-13e8-404b-9c18-d86bf75fe364.mp4

### `master` (broken)

https://user-images.githubusercontent.com/180032/146975044-02bdac46-1a33-4375-8de2-9c48b9960c47.mp4

### Steps to reproduce

- Add a WorldEnvironment node with a PanoramaSkyMaterial. Adjust the sky's rotation in the resource options (try `(0, 0, 1.57)`, values are in radians in `master` but in degrees in `3.x`).
- Rotate the camera around in the 3D editor and see how the sky behaves compared to `3.x`.

### Minimal reproduction project

[test_lightmap_environment_custom_orientation_master.zip](https://github.com/godotengine/godot/files/7757010/test_lightmap_environment_custom_orientation_master.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Should fix https://github.com/godotengine/godot/issues/56136

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works.

**Comment by okla** [comment]
Out of curiosity, why does changing the order helps? How is it possible?

**Comment by Chaosus** [comment]
> Out of curiosity, why does changing the order helps? How is it possible?

Order is matter for matrixes: https://en.wikipedia.org/wiki/Matrix_multiplication#Non-commutativity

**Comment by okla** [comment]
Oh, so these are matrixes, I see, thanks!

**Pull request merged**
