### PR TITLE
Fix Windows Export

### PR DESCRIPTION
**Pull request by masoudbh3**

### CODE REVIEW

**Comment by akien-mga** [comment]
Fixed #2819.

**Comment by akien-mga** [comment]
Thanks! :)

**Comment by akien-mga** [comment]
@masoudbh3 Completely unrelated, but your commits are not affiliated to your GitHub account apparently, I guess you are using a different email address for git (see https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/2820.patch) and for your GitHub account. It might be on purpose though, but I just wanted to let you know :)

**Comment by masoudbh3** [comment]
tanks for notices.

**Pull request merged**
