### PR TITLE
[3.x] Return RID instead of Object id in area-body_shape_entered-exited signals.

### PR DESCRIPTION
**Pull request by madmiraal**
3.2 version of #42742.

### CODE REVIEW

**Comment by capnm** [comment]
The debugger doesn't like it;)
grafik

**Comment by madmiraal** [comment]
The debugger is saying the RID is not a valid resource of the `Area` or `RigidBody` that is running the code, which is true. It is, however, a valid RID of the `PhysicsServer`.

**Comment by madmiraal** [comment]
Rebased following merge of #42715.

**Comment by pouleyKetchoupp** [comment]
For info, the `Invalid RID` message is due to a known general issue with RID type in the debugger: #33797

**Comment by akien-mga** [comment]
The `master` PR was merged, so this should be mergeable once rebased too.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by belzecue** [comment]
Note that this did in fact silently break my project and silently stopped collisions for area-body_shape_entered-exited signals.

Today I tested my 3.3.2 3D project against 3.4 beta2 and wondered why it was no longer doing area-body_shape collisions.  I traced it back to this:

```
func _on_Area_body_shape_entered(body_id: int, body: Node, body_shape: int, local_shape: int) -> void:
	var parent := body.get_parent()
	var parent_class := parent.get_class()

	parent.visible = true
	if parent_class == "OmniLight":
		omnilight_controller._on_Camera_collider_entered(parent)


func _on_Area_body_shape_exited(body_id: int, body: Node, body_shape: int, local_shape: int) -> void:
	var parent := body.get_parent()
	var parent_class := parent.get_class()

	parent.visible = false
	if parent_class == "OmniLight":
		omnilight_controller._on_Camera_collider_exited(parent)

```

Notice I had typed "body_id" as int -- probably because I was originally printing the old returned object_ids in the console during testing and had removed that debug code since.  When run in 3.4B2, no errors were being thrown, it was just silently no longer doing those functions.

Once I switched body_id types to the new RID change, everything went back to working fine.

`func _on_Area_body_shape_entered(body_id: RID, body: Node, body_shape: int, local_shape: int) -> void:
`

So, noting here for anyone else who static-types religiously like me and may be wondering the same thing.

**Comment by pouleyKetchoupp** [comment]
You should get an error similar to this one at runtime:
`ERROR: Error calling method from signal 'area_shape_entered': 'Area(Area.gd)::_on_Area_area_shape_entered': Cannot convert argument 1 from RID to int..`

But it would be great to get an error in the script too. I wonder how complicated it would be to add.

**Comment by belzecue** [comment]
> You should get an error similar to this one at runtime

That is the case, yes. I missed seeing it first time around, in my panic :)

**Pull request merged**
