### PR TITLE
[macOS] Fix keyboard shortcuts on non QWERTY keyboard layouts.

### PR DESCRIPTION
**Pull request by bruvzg**
Hopefully fix shortcuts on all non QWERTY layouts, gets key mapping from os keyboard layout instead of hardcoded maps.

Fixes (on macOS) #11777

Please test this with physical non-QWERTY keyboards before merging, I have tested it with software layouts only.

### CODE REVIEW

**Comment by Calinou** [comment]
Does this change affect running projects? Also, will this fix be ported to other platforms as well?

**Comment by bruvzg** [comment]
Yes this will affect projects, but macOS already had remapping for main layout (AZERTY, QWERTZ, Colemak, Dvorak and Neo), this PR just extends remapping to all possible layouts.

No idea about other platform, I didn't look how layouts work on Windows/X11, currently there's not any remapping on other platform.

**Comment by bruvzg** [comment]
Some clarifications about this PR:

1. If I press highlighted key on `Dvorak` keyboard it will produce `KEY_P` scancode, both with and without this PR (There was hardcoded mapping for this specific variant of Dvorak, macOS support 3 additional Dvorak variants + user installable third-party layouts).
2. If I press highlighted key on `Turkish F` keyboard it will produce `KEY_Q` without PR and `KEY_F` with PR (There was no mapping for this layout before).
3. Both `Ğ` and `E` keys on `Turkish F` keyboard produce `KEY_E`.
4. Text input is NOT affected in any way, only scancodes.

dvrk

**Comment by bruvzg** [comment]
Checked on Debian GNU/Linux 9, Xfce 4, and it have similar behaviour as macOS with this PR.

Except keys like `Ğ` doesn't work. And with layout w/o latin letters at all (e.g. Russian) non of shortcuts can be rebinded (existing shortcuts work as QWERTY), on macOS it works as QWERTY with and without this PR, for both existing shortcuts and rebinding.

**Comment by bruvzg** [comment]
On Widows 10 it also works similar, except Turkish `Ğ` produce `KEY_SEMICOLON`.

So I guess Windows already works in this way and doesn't need this fix, and Linux may need some fixes for non-latin layouts.

**Comment by green-coder** [comment]
Compiled that version on my computer and tested it. The editor works, both the text input and the shortcuts are correct. Nice !

For the record, my computer runs on OSX 10.13.3, the keyboard was a QWERTY which I use as a Programmer Dvorak via software remapping (in the macOS' settings).

**Comment by bruvzg** [comment]
*I have removed some of the previous comments and consolidated all testing data from different platforms in this one.*

## Notes:
* Text input is NOT affected by this PR in any way, only scancodes.
* Other platforms are not affected by this PR (`latin_keyboard_keycode_convert` was only used on macOS).
* With this PR non-QWERTY latin layouts works similar on all platforms.
* Layouts w/o latin letters at all does not work correctly on Linux.

## Testing process:

### Test code:
```gdscript
func _unhandled_input(event):
	if event is InputEventKey:
		if event.pressed:
			print("%d %s" % [event.scancode, OS.get_scancode_string(event.scancode)])
```

### Steps to reproduce:
1. Select specified keyboard layout in OS settings.
2. Press all keys in top letter row (`QWERTYUIOP[]` on QWERTY keyboard) left-to-right one by one.

## Layout: DVORAK L (Left handed)

dvrk

| macOS without PR | macOS with PR | Debian GNU/Linux 9, Xfce 4 | Manjaro Linux 17, KDE | Windows 10 |
|:---:|:---:|:---:|:---:|:---:|
| 81 Q | 59 Semicolon | 59 Semicolon | 59 Semicolon | 59 Semicolon |
| 87 W | 81 Q | 81 Q | 81 Q | 81 Q |
| 69 E | 66 B | 66 B | 66 B | 66 B |
| 82 R | 89 Y | 89 Y | 89 Y | 89 Y |
| 84 T | 85 U | 85 U | 85 U | 85 U |
| 89 Y | 82 R | 82 R | 82 R | 82 R |
| 85 U | 83 S | 83 S | 83 S | 83 S |
| 73 I | 79 O | 79 O | 79 O | 79 O |
| 79 O | 46 Period | 46 Period | 46 Period | 46 Period |
| 80 P | 16777356 Kp 6 | 54 6 | 54 6 | 54 6 |
| 123 BraceLeft | 16777355 Kp 5 | 53 5 | 53 5 | 53 5 |
| 125 BraceRight | 61 Equal | 61 Equal | 61 Equal | 61 Equal |

## Layout: Crimean Tatar (Turkish F)

turkf

| macOS without PR | macOS with PR | Debian GNU/Linux 9, Xfce 4 | Manjaro Linux 17, KDE | Windows 10 |
|:---:|:---:|:---:|:---:|:---:|
| 81 Q | 70 F | 70 F | 70 F | 70 F |
| 87 W | 71 G | 71 G | 71 G | 71 G |
| 69 E | 69 E | 0  | 0  | 59 Semicolon |
| 82 R | 82 R | 0  | 0  | 73 I |
| 84 T | 79 O | 79 O | 79 O | 79 O |
| 89 Y | 68 D | 68 D | 68 D | 68 D |
| 85 U | 82 R | 82 R | 82 R | 82 R |
| 73 I | 78 N | 78 N | 78 N | 78 N |
| 79 O | 72 H | 72 H | 72 H | 72 H |
| 80 P | 80 P | 80 P | 80 P | 80 P |
| 123 BraceLeft | 81 Q | 81 Q | 81 Q | 81 Q |
| 125 BraceRight | 87 W | 87 W | 87 W | 87 W |

## Layout: Russian (Phonetic)

rusp

| macOS without PR | macOS with PR | Debian GNU/Linux 9, Xfce 4 | Manjaro Linux 17, KDE | Windows 10 |
|:---:|:---:|:---:|:---:|:---:|
| 81 Q | 81 Q | 0  | 0  | 81 Q |
| 87 W | 87 W | 0  | 0  | 87 W |
| 69 E | 69 E | 0  | 0  | 69 E |
| 82 R | 82 R | 0  | 0  | 82 R |
| 84 T | 84 T | 0  | 0  | 84 T |
| 89 Y | 89 Y | 0  | 0  | 89 Y |
| 85 U | 85 U | 0  | 0  | 85 U |
| 73 I | 73 I | 0  | 0  | 73 I |
| 79 O | 79 O | 0  | 0  | 79 O |
| 80 P | 80 P | 0  | 0  | 80 P |
| 123 BraceLeft | 123 BraceLeft | 0  | 0  | 123 BraceLeft |
| 125 BraceRight | 125 BraceRight | 0  | 0  | 125 BraceRight |

**Pull request merged**
