### PR TITLE
Supporting Android API 23 (Android 6.0)

### PR DESCRIPTION
**Pull request by volzhs**
If we update build gradle to use `compileSdkVersion 23`,
`org.apache.http` package causes error. (issue #4711)

We need to use `useLibrary 'org.apache.http.legacy'` to solve this problem.
To use `useLibrary`, we need to use latest gradle also.

And now, we faced another problem with `APK Expansion` java sources.

```
/platform/android/java/src/com/google/android/vending/expansion/downloader/impl/DownloadNotification.java
137 :             mCurrentNotification.setLatestEventInfo(mContext, mCurrentTitle, mCurrentText, mContentIntent); // causes error
```

So, some of APK Expansion java sources are updated by referencing commits from https://github.com/danikula/Google-Play-Expansion-File
And dropped V3CustomNotification.java which was for android 3.0, since godot supports android 14 (4.0) above officially.

Unfortunately, another problem, The 'MissingTranslation' error was occurred.
So, build.gradle is updated to use `disable 'MissingTranslation'`

Additionally, I updated `buildToolsVersion`, `targetSdkVersion` to latest version.

I tested APK Expansion funtionality on Android 6.0 (Nexus 9, Nexus 6p) and Android 4.4 (Galaxy Note 2)  with Google Developer console.

### CODE REVIEW

**Comment by SuperUserNameMan** [comment]
@volzhs : if a godot project is compiled with API23, will it still works on previous version of android ?

**Comment by volzhs** [comment]
@SuperUserNameMan yes. I tested this on both API 19 (Android 4.4) and API 23 devices.
I wish I had a API 14 (Android 4.0) device for sure.

**Comment by volzhs** [comment]
according to this https://developer.android.com/about/dashboards/index.html
I think I can't get an API 14 device even if I want one.

**Comment by akien-mga** [comment]
Looks good to me. @punto-, can you have a look?

**Comment by volzhs** [comment]
I found something on Lint Report.
**It's about using new API introduces API 16 (Android 4.1.2) with min target is 14.**

NewApi: Calling new methods on older versions

```
../../src/com/google/android/vending/expansion/downloader/impl/DownloadNotification.java:142: Call requires API level 16 (current min is 14): android.app.Notification.Builder#build
 139             mCurrentNotificationBuilder.setContentIntent(mContentIntent);
 140             mCurrentNotificationBuilder.setOngoing(ongoingEvent);
 141             mCurrentNotificationBuilder.setAutoCancel(!ongoingEvent);
 142             mNotificationManager.notify(NOTIFICATION_ID, mCurrentNotificationBuilder.build());

 143         }
 144     }

../../src/com/google/android/vending/expansion/downloader/impl/DownloadNotification.java:170: Call requires API level 16 (current min is 14): android.app.Notification.Builder#build
 167             mCustomNotification.setTimeRemaining(progress.mTimeRemaining);
 168             mCurrentNotificationBuilder = mCustomNotification.updateNotification(mContext);
 169         }
 170         mNotificationManager.notify(NOTIFICATION_ID, mCurrentNotificationBuilder.build());

 171     }
 172 
```

Note: This issue has an associated quickfix operation in Eclipse/ADT & Android Studio/IntelliJ Fix 
 Priority: 6 / 10
 Category: Correctness
Severity: Error
Explanation: Calling new methods on older versions.

This check scans through all the Android API calls in the application and warns about any calls that are not available on all versions targeted by this application (according to its minimum SDK attribute in the manifest).

 If you really want to use this API and don't need to support older devices just set the minSdkVersion in your build.gradle or AndroidManifest.xml files.

 If your code is deliberately accessing newer APIs, and you have ensured (e.g. with conditional execution) that this code will only ever be called on a supported platform, then you can annotate your class or method with the @TargetApi annotation specifying the local minimum SDK to apply, such as @TargetApi(11), such that this check considers 11 rather than your manifest file's minimum SDK as the required API level.

 If you are deliberately setting android: attributes in style definitions, make sure you place this in a values-vNN folder in order to avoid running into runtime conflicts on certain devices where manufacturers have added custom attributes whose ids conflict with the new ones on later platforms.

 Similarly, you can use tools:targetApi="11" in an XML file to indicate that the element will only be inflated in an adequate context. 


More info: 

To suppress this error, use the issue id "NewApi" as explained in the Suppressing Warnings and Errors section.

**Comment by volzhs** [comment]
I found a way to fix this error reported by lint.
http://stackoverflow.com/questions/32345768/cannot-resolve-method-setlatesteventinfo#33085754
But I can't test and confirm this would fix it or what happen just leave it as now, because I don't have a API 14 device now.

**Comment by akien-mga** [comment]
Could you just add a comment in the code that the NotificationCompat sutff is used to support API < 16, so that we can drop it in the future if we decide to support API 16 as a minimum for example?

**Comment by volzhs** [comment]
@akien-mga I will add a comment about ``NotificationCompat`` in code ASAP.

**Pull request merged**
