### PR TITLE
Added curve in/out (tangent) handle mirroring

### PR DESCRIPTION
**Pull request by sketchyfun**
Added a mirroring option to the path editing tool bar for manipulating curve in/out handles (also known as tangent handles), which makes creating curved paths a lot easier. I've added this functionality for both 2D and 3D curves. If you feel the way I've implemented is wrong or could be improved, please let me know :)

handles

### CODE REVIEW

**Comment by bojidar-bg** [comment]
I think it would be nice to have a way to mirror angles only, without the lengths. That way, the curve remains smooth, but you can have more control over it. (maybe as an additional option)

**Comment by Zireael07** [comment]
Good point about the lengths, @bojidar-bg

**Comment by sketchyfun** [comment]
Ah, interesting idea. I'll look into that now

**Comment by sketchyfun** [comment]
Okay, I've managed to add the length preserving option to both 2D and 3D curve editors. 2D was pretty easy, 3D felt a bit more hacky, but honestly with the way 3D stuff seems to be handled I couldn't figure out a better way..

2d

3d

**Comment by groud** [comment]
Nice feature ! :)

**Comment by sketchyfun** [comment]
I fixed a few problems, but I can't for the life of me seem to get rid of all those commit messages, the usual git rebase -i command doesn't seem to be doing what I need >_<

**Comment by sketchyfun** [comment]
Sorry, I've managed to completely mess this branch up, so I'm going to close it and re-open it on a fresh one before I ruin anything else :/

**Pull request closed without merging**
