### PR TITLE
Prevent calling 'Object::cast_to' method on NULL pointer

### PR DESCRIPTION
**Pull request by zaps166**
Make 'Object::cast_to' static which can properly handle NULL pointers
as an argument.

This patch fixes crashes on GCC 6 and makes the sanitizer happy. It
also removes some redundant checks before calling 'Object::cast_to'.

### CODE REVIEW

**Comment by zaps166** [comment]
@reduz I found it (https://gcc.gnu.org/gcc-6/porting_to.html)!

> **Optimizations remove null pointer checks for this**
When optimizing, GCC now assumes the this pointer can never be null, which is guaranteed by the language rules. Invalid programs which assume it is OK to invoke a member function through a null pointer (possibly relying on checks like this != NULL) may crash or otherwise fail at run time if null pointer checks are optimized away. With the -Wnull-dereference option the compiler tries to warn when it detects such invalid code.
If the program cannot be fixed to remove the undefined behavior then the option -fno-delete-null-pointer-checks can be used to disable this optimization. That option also disables other optimizations involving pointers, not only those involving this.

I think that is better to use `static` version of `cast_to` instead of `-fno-delete-null-pointer-checks` flag, especially when the patch is ready (needs rebase) and also sanitizer on other compilers complains about it.

**Comment by reduz** [comment]
guys, your work is enormously appreciated, but I stated again and again that **it should be considered a bug in Godot if cast_to<> is called with a null base pointer** and as such **it should be perfectly valid if it crashes in this situation**. We actually **want the crash to happen**.

**Comment by reduz** [comment]
Any code that calls cast_to<> with base null pointer is considered bad code and it must be fixed. For this, we need this function to crash.

**Comment by zaps166** [comment]
Ok, so I'll wait :)

I thought about other attempt: making it `static`, so there won't be necessary to find where `NULL` can happen (safer, easier, etc.). I also removed all remaining `NULL` checks in this patch, because there are checks after casting (`dynamic_cast` from `NULL` is still `NULL`).

The goal of my previous comment was to confirm that this is not a compiler bug, but it is intentional change :)

**Comment by slapin** [comment]
I think if you have sanitizer log in regard to cast_to I think it is best if you attach it here.
Also I think we need some sanitizer target for scons...

**Comment by zaps166** [comment]
Currently I don't have it, but I can prepare a simple sanitizer output :)

> Also I think we need some sanitizer target for scons

Yes, and also color output will be nice in scons for GCC >= 5 and Clang (http://stackoverflow.com/questions/9922521/why-doesnt-clang-show-color-output-under-scons)

**Comment by zaps166** [comment]
Is something wrong with current HEAD (compiled with undefiner sanitizer, Clang 3.8.0, `-Ofast` flag)?

`tools/editor/asset_library_editor_plugin.cpp:1285:2: runtime error: member call on null pointer of type 'Node'`

and crash. Also a lot of misaligned addresses in `Vector<>` and `DVector<>`

Can't start the editor, so can't do anything with current HEAD (f8f30662d93a46eb4b1ece6d45be28760d5ad58c).

**Comment by zaps166** [comment]
@reduz 

Godot crashes at startup with sanitizer (GCC 5 or Clang 3.8.0): `tools/editor/asset_library_editor_plugin.cpp:1285:2: runtime error: member call on null pointer of type 'Node'`

Godot runs w/o sanitizer (I don't know why it doesn't crash w/o sanitizer). It calls method on **uninitialized** variable `library_vb`! `library_vb` is allocated a few lines below, It can cause unexpected crashes at runtime...

Looks like this commit added wrong call: 5a9b18b665b250b54c0d8eb80354dc08e363377c

Call of uninitialized pointer: https://github.com/godotengine/godot/blob/master/tools/editor/asset_library_editor_plugin.cpp#L1285
Allolcation: https://github.com/godotengine/godot/blob/master/tools/editor/asset_library_editor_plugin.cpp#L1372

**Comment by zaps166** [comment]
PR: #5123 for above comment

**Comment by zaps166** [comment]
And three sanitizer outputs on top of #5123 (GCC 5.4.0)

[Editor2dPlatformer-ubsan1-crash.txt](https://github.com/godotengine/godot/files/307537/Editor2dPlatformer-ubsan1-crash.txt)
[Editor2dPlatformer-ubsan2-crash.txt](https://github.com/godotengine/godot/files/307538/Editor2dPlatformer-ubsan2-crash.txt)
[Game3dPlatformer-ubsan3.txt](https://github.com/godotengine/godot/files/307536/Game3dPlatformer-ubsan3.txt)

A lot of misalignment warnings, etc and crashes because of null-pointer-dereference.

Btw. is it possible to not crash on null-pointer-dereference when using sanitizer?

**Comment by zaps166** [comment]
Rebasing this will take some time :smile: If it is going to merge I can do this later, so what to do?

**Comment by akien-mga** [comment]
It's not sure what fixed what between this PR, #4691 and #4883.
I think @reduz wasn't too keen on merging either of them, so I wouldn't spend too much time rebasing until a decision has been reached. At the very least it can serve as a reference for the potential "better" fix that @reduz has in mind for 3.0.

**Comment by akien-mga** [comment]
Closing as @reduz has started working on the original issue with a different approach that involves a heavier refactoring of the core types, in line with Godot 3.0 changes.

**Pull request closed without merging**
