### PR TITLE
About: Add License info

### PR DESCRIPTION
**Pull request by ghost**
image

### CODE REVIEW

**Comment by reduz** [comment]
we should probably add the licenses from third parties here too. @akien-mga , you made a list right?

**Comment by reduz** [comment]
We should also probably add it in an extra tab (Third Party)

**Comment by akien-mga** [comment]
Yeah adding thirdparty licensing details in a 3rd tab would be good.

I made this list: https://github.com/godotengine/godot/blob/master/COPYRIGHT.txt
It's in Debian's machine-readable specification for debian/copyright files, so it should be possible to parse it in the python script and extract the relevant info.
We'd need to have to have it human-readable in the end, not sure what would be the best presentation (maybe we can check what other software do for that).

**Comment by akien-mga** [comment]
I know @Noshyaar started to look into documenting the thirdparty licenses too, but we can already merge this one as it's a good start.

**Pull request merged**
