### PR TITLE
Fix multiple 2D & 3D physics issues (2.1)

### LINKED ISSUE #6676: queue_free crashing physics server
**Operating system or device - Godot version:**
Linux (Arch) x64 - Godot master

**Issue description** (what happened, and what was expected):
When using `queue_free` in `_integrate_forces` or anywhere else on a RigidBody2D/KinematicBody2D (even if it is set to MODE_STATIC, with layer/collision mask == 0), the game would crash from time to time... seemingly without reason. This is pretty much a blocker for "me", since it makes bullets nearly impossible to do properly.

**Steps to reproduce:**
Run https://github.com/KOBUGE-Incubator/ringed (https://github.com/KOBUGE-Incubator/ringed/commit/7fecca7fb54c8635cb30ea83fe13440c4b488e9a in case something changes), and start shooting.. at some point in time, the game would crash (you might have to die a few zillion times before, but it is granted to happen). Now, retry with an older version, and see it doesn't happen there (good luck :wink:)

**GDB backtraces:**

```
#0  0x00000000015e655c in Space2DSW::get_body_angular_velocity_sleep_treshold (this=0x0) at servers/physics_2d/space_2d_sw.h:162
#1  0x00000000015e4c63 in Body2DSW::sleep_test (this=0x5b99040, p_step=0.0166666675) at servers/physics_2d/body_2d_sw.cpp:642
#2  0x00000000015ee3e2 in Step2DSW::_check_suspend (this=0x341c270, p_island=0x5b99040, p_delta=0.0166666675) at servers/physics_2d/step_2d_sw.cpp:110
#3  0x00000000015eeacc in Step2DSW::step (this=0x341c270, p_space=0x3946120, p_delta=0.0166666675, p_iterations=8) at servers/physics_2d/step_2d_sw.cpp:308
#4  0x00000000015da3f5 in Physics2DServerSW::step (this=0x34204e0, p_step=0.0166666675) at servers/physics_2d/physics_2d_server_sw.cpp:1277
#5  0x0000000001664df5 in Physics2DServerWrapMT::step (this=0x7fffe8265030, p_step=0.0166666675) at servers/physics_2d/physics_2d_server_wrap_mt.cpp:86
#6  0x00000000004327bf in Main::iteration () at main/main.cpp:1587
#7  0x0000000000416311 in OS_X11::run (this=0x7fffffffe020) at platform/x11/os_x11.cpp:1921
#8  0x000000000040e9f0 in main (argc=1, argv=0x7fffffffe538) at platform/x11/godot_x11.cpp:41
```

Or:

```
#0  0x00000000015edbfb in Comparator<Constraint2DSW*>::operator() (this=0x7fffffffd927, p_a=@0x7fffffffd9b0: 0x4acb980, p_b=@0xc4a3b5dc00000030: <error reading variable>)
    at core/typedefs.h:268
#1  0x00000000015ed40c in Map<Constraint2DSW*, int, Comparator<Constraint2DSW*>, DefaultAllocator>::_find (this=0x52d7960, p_key=@0x7fffffffd9b0: 0x4acb980) at core/map.h:248
#2  0x00000000015ed072 in Map<Constraint2DSW*, int, Comparator<Constraint2DSW*>, DefaultAllocator>::find (this=0x52d7960, p_key=@0x7fffffffd9b0: 0x4acb980) at core/map.h:560
#3  0x00000000015eceeb in Map<Constraint2DSW*, int, Comparator<Constraint2DSW*>, DefaultAllocator>::operator[] (this=0x52d7960, p_key=@0x7fffffffd9b0: 0x4acb980) at core/map.h:627
#4  0x00000000015eccdd in Body2DSW::add_constraint (this=0x52d77f0, p_constraint=0x4acb980, p_pos=1) at servers/physics_2d/body_2d_sw.h:188
#5  0x000000000168bb42 in BodyPair2DSW::BodyPair2DSW (this=0x4acb980, p_A=0x42f18a0, p_shape_A=0, p_B=0x52d77f0, p_shape_B=0) at servers/physics_2d/body_pair_2d_sw.cpp:537
#6  0x00000000016868b6 in Space2DSW::_broadphase_pair (A=0x42f18a0, p_subindex_A=0, B=0x52d77f0, p_subindex_B=0, p_self=0x3945f90) at servers/physics_2d/space_2d_sw.cpp:1129
#7  0x000000000167bcfc in BroadPhase2DHashGrid::_check_motion (this=0x3911fc0, p_elem=0x41c1398) at servers/physics_2d/broad_phase_2d_hash_grid.cpp:89
#8  0x000000000167cd82 in BroadPhase2DHashGrid::move (this=0x3911fc0, p_id=2793, p_aabb=...) at servers/physics_2d/broad_phase_2d_hash_grid.cpp:384
#9  0x00000000015e88c4 in CollisionObject2DSW::_update_shapes (this=0x42f18a0) at servers/physics_2d/collision_object_2d_sw.cpp:158
#10 0x00000000015e54f8 in CollisionObject2DSW::_set_transform (this=0x42f18a0, p_transform=..., p_update_shapes=true) at servers/physics_2d/collision_object_2d_sw.h:80
#11 0x00000000015e47f1 in Body2DSW::integrate_velocities (this=0x42f18a0, p_step=0.0166666675) at servers/physics_2d/body_2d_sw.cpp:562
#12 0x00000000015eea86 in Step2DSW::step (this=0x341c170, p_space=0x3945f90, p_delta=0.0166666675, p_iterations=8) at servers/physics_2d/step_2d_sw.cpp:298
#13 0x00000000015da3f5 in Physics2DServerSW::step (this=0x34203e0, p_step=0.0166666675) at servers/physics_2d/physics_2d_server_sw.cpp:1277
#14 0x0000000001664df5 in Physics2DServerWrapMT::step (this=0x7fffe8265030, p_step=0.0166666675) at servers/physics_2d/physics_2d_server_wrap_mt.cpp:86
#15 0x00000000004327bf in Main::iteration () at main/main.cpp:1587
#16 0x0000000000416311 in OS_X11::run (this=0x7fffffffe020) at platform/x11/os_x11.cpp:1921
#17 0x000000000040e9f0 in main (argc=1, argv=0x7fffffffe538) at platform/x11/godot_x11.cpp:41
```

Or:

```
#0  0x0000000001687290 in CollisionObject2DSW::get_type (this=0x13e013600) at servers/physics_2d/collision_object_2d_sw.h:98
#1  0x0000000001686734 in Space2DSW::_broadphase_pair (A=0x461f640, p_subindex_A=0, B=0x13e013600, p_subindex_B=-1057153242, p_self=0x3945ed0) at servers/physics_2d/space_2d_sw.cpp:1099
[didn't save rest :/]
```

**Bisect output:**

```
$ git bisect log
git bisect start 'servers'
# bad: [dabcabe9815612c7ef1c99909b14d632f13df165] Merge pull request #6658 from Faless/fix_bo_network
git bisect bad dabcabe9815612c7ef1c99909b14d632f13df165
# good: [9e2b9f8cb1c34fe7c3aa91bdd7f40ebb6a1a318f] bump to stable, congratulations everyone
git bisect good 9e2b9f8cb1c34fe7c3aa91bdd7f40ebb6a1a318f
# good: [64b4253dbfe3fdfc4efa405086d23765a9774d91] changed visual server free() to free_rid() like in the other servers. Fixes #4917
git bisect good 64b4253dbfe3fdfc4efa405086d23765a9774d91
# bad: [3725114a1658337d6de21bb7a5b6fde5f8a74d1f] Merge pull request #5383 from Ovnuniarchos/OptimizeOneWay
git bisect bad 3725114a1658337d6de21bb7a5b6fde5f8a74d1f
# bad: [b4b80625d175a151f05403c9dcbc5f13be652289] Change hash grid in 2D physics to contemplate large objects as separate cases, to avoid huge memory and performance penalty. Fixes #4662
git bisect bad b4b80625d175a151f05403c9dcbc5f13be652289
# good: [b7dbf9207abf9fb9e4cc46e8e1d67f3d6d40d58c] Drop empty files that are not used anywhere
git bisect good b7dbf9207abf9fb9e4cc46e8e1d67f3d6d40d58c
# good: [c3bf11d4d48c0499460dc294c6836acedbfd46cb] Drop fully commented-out files
git bisect good c3bf11d4d48c0499460dc294c6836acedbfd46cb
# first bad commit: [b4b80625d175a151f05403c9dcbc5f13be652289] Change hash grid in 2D physics to contemplate large objects as separate cases, to avoid huge memory and performance penalty. Fixes #4662
```

(I might have done something wrong with the bisect, since some of the good might be bad, or some of the bad might be some other bug...)

Anyway. it seems like b4b80625d175a151f05403c9dcbc5f13be652289 is the culprit here, though I have no idea why...

### LINKED ISSUE #7589: Raycast to Area not adhering to Layer/Mask
**Operating system or device - Godot version:**
2.1.1 STABLE
3.0-alpha

**Issue description:**
Raycast nodes have a Layer Mask property to filter which CollisionObjects are picked up by the cast. The Layer/Mask works properly for PhysicsBody objects such as KinematicBody, but not for Area. Regardless of which Layer/Mask is specified for Area or RayCast, the RayCast will detect a collision with the Area.

**Steps to reproduce:**
- Create node `Area`
 - Create child `CollisionShape` - Set to any desired shape
- Create node `RayCast`
 - Set Layer Mask to exclude Layer(s) used by Area
- Observe that `RayCast` node's `is_colliding()` returns `True`

**Link to minimal example project:**

This ZIP contains 2.1.1-Compatible and 3.0-alpha-Compatible scenes.

[test_proj.zip](https://github.com/godotengine/godot/files/719905/test_proj.zip)

### LINKED ISSUE #8856: Area_enter doesn't work after some load/instance/changetree
**Operating system or device - Godot version:**
- Windows 7 Pro, Service Pack 1
- 64 bits
- Godot_v2.1.3-stable_win64

**Issue description:**
In 100% of the cases, the following problem happens :
After reloading/reinstanciate a scene a few times, the area_object in it aren't detected by area_enter anymore.

**Steps to reproduce:**
- Create a scene 1
- Create a scene 2
- Create a scene 3
- Add some area objects in the scene 3
- Add scene 3 as child of scene 2
- Add one "area" as character in scene 2, and make it move in direction of the "area_objects" of scene 3. - Add a self.connect("area_enter",self,"someFunc") on the character of scene 2.
- Add a button on scene 1 to go to scene 2, and a button to scene 2 to go to scene 1.
- Make some "get_tree().changeScene("res://scene1")" and "get_tree().changeScene("res://scene2")" to switch between scene1 and scene2 a couple time.
- After this, some areas of scene 3 aren't detected anymore by the area_enter of the character.

PS: When it happens, it persists (it reset only when leaving the game and comeback). And it can be seen that the "Collision Pairs", in Physics3d, in the monitor of the debugger, are lower than normal.

**Link to minimal example project:**
https://github.com/Mbenoni1/GodotEngineTestProject

This is a minimalist version of my own project. To see the problem happens, just launch, click play, then move with the arrows of your keyboard to take some elements. It will after a short time automatically come back to menu. Click "play", etc, and see the bug happens after 2 to 4 cycle.

Thanks ! If you have any questions, don't hesitate !

### PR DESCRIPTION
**Pull request by RandomShaper**
- Use `NOTIFICATION_ENTER`/`EXIT_WORLD` for `Area` (intead of `*_TREE`).
- Now both bodies' and areas' constraints are cleaned up.
- And now also that happens as soon as the space is set to null (i.e., when exiting the tree) instead of only at freeing time.
- When clearing constraints, the loop goes on to the next if the current is already released, instead of breaking.
- When one has been already released, no error is shown from now on, as it's something expected, since a pair (our kind of constraint of interest) can be freed by any of its involved collision objects and the other will try again.
- Implement index shifting (or marking as -1) for shapes indices in collision pairs shapes are removed.
- Standarize behavior of bodies and areas so that anything that invalidates a given pair gives the same result (collision mask, actual collision, etc); for instance, triggering area enter/exit signals.
- Add missing member initializations.
- Extend the new-space-equals-area/body-current-space test to every case.
- Fix 3D ray-casts early accepting Areas (skipping the mask check).
- Fix unpairing of large elements (2D's `BroadPhase2DHashGrid`).

Some of these prevent random crashes caused by constraints with dangling pointers to involved objects.
Fixes #8856.
Fixes #7589.
Fixes #6676.
And maybe others.

~~__NOTE:__
One of the issues is fixed by #9094, so I've worked on this with that one merged so it's a dependency.~~

~~__UPDATE:__
I've started noticing an issue that can make the engine crash. Not sure if it's something directly due to my modifications or if I have uncovered a latent bug somehow. So still researching.~~

~~__UPDATE:__
What I am being hit by is #6676. So I'm trying to hunt that bug and add a fix for it to this PR.~~

~~__UPDATE:__
Now I know objects are being properly destroyed at the C++ level (AKA, the #9094 debacle), I'm looking in other places.~~

__UPDATE:__
On my part, this is ready to review and test.
Also someone should check the eligibility of some or all of these fixes for _master_ as I currently don't have the time to do it.

### CODE REVIEW

**Comment by RandomShaper** [comment]
I've tested my game and some 2D & 3D offical demos involving physics, and everything seems to be working OK.

So, on my part, this is ready to merge for early adopters to test it a bit more.

**Comment by RandomShaper** [comment]
@akien-mga, please have a look at my last 'update' in this PR's description.

**Comment by RandomShaper** [comment]
By the way, any chance for this to make it into 2.1.4?

If it's too late, it would be nice to have there at least the most straightforward fixes. I could make a separate PR out of them.

**Comment by akien-mga** [comment]
I wanted to merge it for testing yesterday but you had tagged it as WIP so I refrained :) I'll try to have a cursory look at the current state and merge it.

**Comment by RandomShaper** [comment]
I'm trying to do the split to move the fixes I'm less confident about to
another PR.

**Comment by RandomShaper** [comment]
Sorry for the annoyance. The thing is that I've been auditing the code and I think everything should go together.

**Comment by akien-mga** [comment]
I can't really assess all changes, but let's give it a spin and see how it goes.

**Comment by RandomShaper** [comment]
@akien-mga, I think some of these are needed for 3.0, but now I'm too busy. (And not forgetting #9518, which fixed a regression.)

What can we do? Wait for me being not so busy (no estimated timeframe) or what?

**Comment by RandomShaper** [comment]
No problem. It's not that much. I'm porting them myself.

**Pull request merged**
