### PR TITLE
Make AnimatedSprite able to play backwards

### LINKED ISSUE #17787: AnimationSprite does not have a play_backwards function
**Godot version:**
`master` branch 928cdb4f8a72c2de5751cddd3205c2a3c09e6f6d

**Issue description:**
Currently AnimationPlayer has a member function for playing an animation backwards, but this is not true for an AnimatedSprite.

It would be great to have this functionality.

### PR DESCRIPTION
**Pull request by YeldhamDev**
Salvaged from #18044. Fixes #17787.

### CODE REVIEW

**Comment by reduz** [comment]
seems fine

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
This breaks GDNative ABI. I'd like to discuss this, consider later.

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.

Since we broke GDNative for security purposes just pulled it in here. We will not do this again in 3.1

**Pull request merged**
