### PR TITLE
Added logs to .gitignore

### PR DESCRIPTION
**Pull request by djrm**

### CODE REVIEW

**Comment by groud** [comment]
Shouldn't it be `logs/*` ?

**Comment by bojidar-bg** [comment]
@groud it is equivalent actually, unless you un-ignore some specific file later on.

**Comment by groud** [comment]
I don't get it. Is the folder itself ignored or only its content then?

**Comment by akien-mga** [comment]
> I don't get it. Is the folder itself ignored or only its content then?

Folders don't exist in git. `logs/` in .gitignore means everything in `./logs/`, so it's the same as using a wildcard.

**Pull request merged**
