### PR TITLE
Overhaul web export page 

### LINKED ISSUE #2774: HTML5: No Release Export available
Currently it is only possible to export the debug version which includes the debugging console and emscripten logo inside the web page. The export option "enable debugging" doesn't do anything.

So I pledge for adding a release export template which only shows the actual game without anything else.

### PR DESCRIPTION
**Pull request by leonkrause**
This change trims the web export page.
## Changes
- Minimum size is canvas size, so no scrollbars as long as the game fits, e.g. for `iframe`
- Controls as overlay, hidden until hover
  - Can be disabled completely
- Status display as overlay
  - Hides on click (for emergency, in case status freezes...)
- Output only visible in debug export
  - Visibility can be toggled per controls
- Godot default theme style
- Should be HTML/XML polyglot (but hard to verify)
- Separate Emscripten interface `Module` logic from page `Presentation` logic
- Add export options to customize page:
  - Page title (`<title>`)
  - `<head>` include
  - Fonts (`font-family`)
  - CSS include
  - Controls visibility
- Prevent exception when clicking fullscreen button before fully loaded
- Fix canvas being smaller than game
- Fix iframed page not regaining focus on click
## Demonstration

web-export-options
_These settings are also used for the following demonstrations._
- Debug export:
  https://googledrive.com/host/0B1lsc05JnCtrSUtiT25pRVdTR1k
- Release export, controls disabled, in `iframe`:
  https://googledrive.com/host/0B1lsc05JnCtrVXdCNWh4TTRXaVE

Closes #2774
## To do later:
- Implement canvas resize
  - Substract output height when visible
- Implement fullscreen button properly
- Implement cursor lock toggle
- Less ridiculous vertical centering for status display
- Handle `webglcontextlost` event
- Style checkboxes — Hacky, would have to include "check" texture
- Spinner? — Seems annoying to me, maybe a loading bar when `setStatus` cooperates

### CODE REVIEW

**Comment by eska014** [comment]
Export templates based on 891e31b139b269fb154d30b8c7d7887267708d8b and Emscripten 1.35.0:
- Debug: [javascript_debug.zip](https://github.com/godotengine/godot/files/96981/javascript_debug.zip)
- Release: [javascript_release.zip](https://github.com/godotengine/godot/files/96983/javascript_release.zip)

**Comment by akien-mga** [comment]
Wow, this is super awesome! :D

**Comment by punto-** [comment]
How much stuff on this page is outside of the engine control? Could people
provide their own HTML file entirely, with some kind of macro for where to
include the game itself?

**Comment by Hinsbart** [comment]
How to get javascript export working? I tried the templates you provided and got errors similar to this:
`XMLHttpRequest cannot load file:///home/hondres/.godot/tmp/godot.mem. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`. It also complains about some other files, the same happens when I try to build my own templates.
I can run the examples you posted just fine though...

**Comment by eska014** [comment]
@punto-
I wrote it specifically so that it's easy to use another HTML file.
Linking the game files works as before:
`$GODOT_FS`, `$GODOT_MEM` and `$GODOT_JS` are substituted by the file name strings `<name>fs.js`, `<name>.mem` and `<name>.js` respectively.

The new parameters `$GODOT_CANVAS_WIDTH` and `$GODOT_CANVAS_HEIGHT` are substituted by the configured game window height and width, and would normally be used as values for the canvas' `width` and `height` attribute.

Additionally, these parameters are substituted by whatever the user enters in the export window:
- `$GODOT_HEAD_TITLE`
- `$GODOT_HEAD_INCLUDE`
- `$GODOT_STYLE_FONT_FAMILY`
- `$GODOT_STYLE_INCLUDE`

`$GODOT_CONTROLS_ENABLED` and `$GODOT_DEBUG_ENABLED` are replaced with the strings `true` and `false`, for usage in JavaScript.

Also, the `$GODOT` prefix now has an underscore for legibility, since some of them are longer.

**Comment by eska014** [comment]
@Hinsbart This is not the right channel for support.

Anyway, looks like you're trying to open the exported HTML file as a local file (`file://` protocol), which Chromium browsers do not allow. Open the file over http (Upload it, or use a local server) or start the browser with `--disable-web-security`. Also note issue #2758.

**Pull request merged**
