### PR TITLE
Fixed regression bug caused in #30095 and actually fix the issue it was supposed to fix(#26850).

### LINKED ISSUE #26850: Unused arguments warning but they are used
Godot 3.1 RC1

The following function marks `w` and `h` as unused:
```gdscript
static func grid_extract_area_safe_crop(x0, y0, w, h):
	
	var gw = 0
	var gh = 0
	
	if x0 < 0:
		w += x0
		x0 = 0
	if y0 < 0:
		h += y0
		y0 = 0
	
	if x0 + w >= gw:
		w = gw-x0
	if y0 + h >= gh:
		h = gh-y0
	
	return x0 + y0 + w + h
```
Note: this function makes no sense because I simplified it for repro.

### PR DESCRIPTION
**Pull request by Anutrix**
Fixes regression bug introduced in #30095.
Fixes #26850.
Also, we can change that switch to if statement. Should I?

### CODE REVIEW

**Comment by aaronfranke** [comment]
I can confirm that this solves the issue I experienced [here](https://github.com/godotengine/godot/issues/26850#issuecomment-489562284). By the way, in that code I'm actually using delta in two places, even with both present the argument was still marked as being unused, but I tested that now either usage by itself will cause it to be marked as used.

**Comment by Anutrix** [comment]
Great. Glad that it worked. So, should I change `switch` to `if`-`else` statements since there are only 2 cases.

**Comment by akien-mga** [comment]
Sure.

**Comment by Anutrix** [comment]
Now uses if-else instead of switch.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
