### PR TITLE
Change the call mode to self when adding nodes via the node search

### LINKED ISSUE #28614: Dragging a property from the search (control - f) will lack a self node.
**Godot version:**
0eb924a425281dfae4672ec114dc42b4067205ec

**Issue description:**
Dragging a property from the Generic Visual Search (control - f) will lack a self node.

Press control-f in an empty visual script.

### PR DESCRIPTION
**Pull request by Jummit**
Fixes #28614

### CODE REVIEW

**Comment by fire** [comment]
Reviewing.

**Comment by fire** [comment]
Screen Shot 2019-05-13 at 8 41 43 AM

Tested:

* Drag from _input
* Generic search property get 
* Generic search property set

Looks good so far.

**Comment by fire** [comment]
The get cell_size returns a "variant" port, so that's clearly wrong, but that's another pull request.

**Comment by Jummit** [comment]
This is probably not the right way of doing things, as it just looks if the node was added without dragging out from another node. Can you test dragging out from a sequence node? Wait, without #28837 there wont be any method nodes in there...

**Comment by fire** [comment]
I tried it with other nodes, at some point the method outputs get saved as Variant, but in theory we know the output type.

**Comment by fire** [comment]
Can you check if this looks good? The ports having variants is a different issue and in another pull request.

**Comment by Jummit** [comment]
All done and dusted.

**Comment by fire** [comment]
Compiling and checking now.

**Review by fire — APPROVED** [review]
Looks good. 

The output port being variant while the system knows its type is another issue for another PR.

Screen Shot 2019-05-24 at 8 33 40 AM

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
