### PR TITLE
EditorPlugin ability to open and reload scenes from scn filepath

### PR DESCRIPTION
**Pull request by kubecz3k**
EditorPlugin has new method `open_scene_from_path(filepath)`. 
It's possible to open scene from filepath inside editor with this method.

### CODE REVIEW

**Comment by kubecz3k** [comment]
In any case, please don't merge just yet.

**Comment by kubecz3k** [comment]
Fixed issue with not renderable editor 3D when user started editor with activated EditorPlugin which was trying to open scene inside `EditorPlugin.enter_tree()`. Think it's ready to merge

**Comment by vnen** [comment]
Would be interesting to expose [`EditorNode::reload_scene(String path)`](https://github.com/godotengine/godot/blob/0bf88e4b38ff6665cc3cc69c2d8a4723481b8586/editor/editor_node.cpp#L4791) to the EditorPlugin too.

**Comment by kubecz3k** [comment]
Yeah I'm willing to expose more stuff, I think this class can have a lot lot more info. What is reload_scene doing exactly?

**Comment by vnen** [comment]
@kubecz3k it reloads the scene in editor to take account the external changes. It'll be helpful for my Tiled importer, as it'll be able to update the inherited scene in editor when the source map change. This is already used in the scene importers like the Collada one.

**Comment by kubecz3k** [comment]
Oh if you already have use-case/need for it, I will look into it in Monday to add.

**Comment by kubecz3k** [comment]
@vnen done!

**Comment by kubecz3k** [comment]
`load_scene` and `reload_scene` are no longer inside `call_deffered` call. Added docs info to not use `load_scene` during plugin initialization. 
As far as I know it's ready to merge.

**Review by vnen — APPROVED** [review]

**Pull request merged**
