### PR TITLE
Fix clipping from flooring scrollcontainer position

### PR DESCRIPTION
**Pull request by realkotob**
Regression from #46409

~~Fixes? https://github.com/godotengine/godot/issues/46850~~

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @georgwacker

**Comment by akien-mga** [comment]
What about the `master` branch? It still uses `floor()` for now, but doesn't seem to have regressions (anymore). Maybe it was fixed differently there?

**Comment by asheraryam** [comment]
@akien-mga If this fixes the issues I was going to make a PR for master, otherwise I have to go and see how it was fixed in master, because the floor was _supposed_ to be the regression fix.

**Comment by akien-mga** [comment]
It's possible that the same regression happens in `master` indeed but nobody noticed it so far (though it would be a bit surprising as the `master` branch does have quite a few users). But I can't seem to reproduce the `3.2` issue on Linux/KDE Plasma with 1920x1080 monitor and both Intel and AMD chipsets, so it might be configuration specific.

**Comment by asheraryam** [comment]
@akien-mga I can't reproduce it either, but my guess is that it could be from this deleted code: https://github.com/godotengine/godot/pull/46409/files#diff-2b7ba034670859ced66e442b9ec59f7351febc3b4352e535bc85da804bcca266L466

Thing is, we don't want that code, that is what was causing the horrible jitter.

**Comment by georgwacker** [comment]
The code for updating the scroll container dimensions got shuffled around in https://github.com/godotengine/godot/commit/b8610dbd3159985f007deb0424a64df386832d07 but stayed the same otherwise. This code in master does call update_dimensions on ready, so I backported this to 3.2 and tested with the supplied project but the issue persists. 

So the crucial change must be elsewhere.

**Comment by asheraryam** [comment]
> So the crucial change must be elsewhere. The project looks fine on master.
> I suspect this commit [1adea98](https://github.com/godotengine/godot/commit/1adea98d070783c8b5a560eeb1f9ca636db28514) might be it.

I agree that the change must be elsewhere, but I don't think [1adea98](https://github.com/godotengine/godot/commit/1adea98d070783c8b5a560eeb1f9ca636db28514) is related since it was not backported to 3.2 (although `get_content_height()` does look suspicious).
I also checked bruvzg's other recent PRs for 3.2 and none of them seem related. https://github.com/godotengine/godot/pulls?q=is%3Apr+is%3Aclosed+author%3Abruvzg+milestone%3A3.2

**Pull request closed without merging**
