### PR TITLE
Fix RGBA Uniform autogeneration in ShaderGraph

### PR DESCRIPTION
**Pull request by MarianoGnu**
I'll add and check bugs fixed in this PR as i find and fix them.
- [x] ShaderGraph RGB Uniform broken (#2606)

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you run ```git rebase``` to get rid of the merge commits from upstream?

**Comment by MarianoGnu** [comment]
dude i hate rebase, what does "posta" have to do with this? that's an unused branch i just used for rebase -.-

**Comment by akien-mga** [comment]
Yeah git can be voodoo sometimes :D

**Comment by akien-mga** [comment]
Note that you don't need a specific branch to rebase, if your current branch is tracking godotengine/godot as upstream branch, ```git rebase``` should work without further argument. Else, ```git rebase https://github.com/godotengine/godot master``` might have worked too.

**Comment by MarianoGnu** [comment]
i use tortoise git, it asks me for a branch behind the comit's i'm interested to edit the rebase file

**Comment by neikeq** [comment]
About the 3th point, there does not seem to be F5 input handling on file dialog. I am not sure what makes it refresh.

**Comment by MarianoGnu** [comment]
i realized the same, but haven't been programing since sunday, so i still didn't find an answer.
Same happens to point 2, the undo action is launched by the scene menu using the Ctrl+Z shorcut, i supose GdScriptEditorPlugin also checks for this combination itself, got to see how the undo/redo contexts are linked, because i'm not sure if it uses the same one...

**Comment by neikeq** [comment]
If #3191 is merged, you could include the F5 shortcut there.

**Comment by MarianoGnu** [comment]
@neikeq cool, bool Control::window_is_modal_on_top(Control* p_modal) could be exactly what i need for both undo and F5 problems

**Comment by akien-mga** [comment]
Wouldn't it be better to merge this first fix and you can open different PRs for the other fixes? It's best to keep PRs as simple as they can be, and right now your first fix is kind of stuck until you find the fixes for the other bugs :)

**Comment by MarianoGnu** [comment]
You can merge if you want, i'm stuck with the other two

**Pull request merged**
