### PR TITLE
Fix extra padding for numbers with signs

### LINKED ISSUE #42413: Bug with `%Nd` substitution for negative numbers in GDScript
**Godot version:**
3.2, 4.0

**OS/device including version:**
All

**Issue description:**
The string formatting operator does not work correctly for `%Nd` substitution if the number is negative (it does not take into account that the minus sign occupies one character).

**Steps to reproduce:**
```gdscript
tool
extends EditorScript

func _run():
    print("%3.0f" % 5)
    print("%3.0f" % -5)
    print("%3d" % 5)
    print("%3d" % -5)
```

```
  5
 -5
  5
  -5
```

**Minimal reproduction project:**
—

### PR DESCRIPTION
**Pull request by sswx99**
Fixes #42413

### CODE REVIEW

**Comment by dalexeev** [comment]
If it's not difficult for you, please change

https://github.com/godotengine/godot/blob/5e726d8d2025f1bc52299894230d94ef5972cea4/modules/gdscript/doc_classes/%40GDScript.xml#L770

to

```
print("%2d %2d %2d" % [i, i % 3, posmod(i, 3)])
```

and force-push branch. In  #42059 I used `%2.0f` as a workaround.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by ssw99** [comment]
I am really happy to contribute to this great project.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
