### PR TITLE
Fix inverted link in docs

### PR DESCRIPTION
**Pull request by AThousandShips**
Title and url were swapped

### CODE REVIEW

**Review by Mickeon — APPROVED** [review]
I do not want to know how long this has been there

**Comment by ryevdokimov** [comment]
Regex will find more instances of these:

image

**Comment by AThousandShips** [comment]
Oh missed the second, will add, searched for it but it was missed

**Comment by ryevdokimov** [comment]
Oh I'm an idiot. Hah ignore me.

**Review by ryevdokimov — APPROVED** [review]

**Comment by Mickeon** [comment]
Thank you for the assistance @ryevdokimov

**Comment by ryevdokimov** [comment]
Mostly assisted myself in making a fool of myself, but always glad I can help 😂

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.
Cherry-picked for 4.1.4.

**Pull request merged**
