### PR TITLE
GDScript: Fix `get_*_list()` methods return incorrect info

### LINKED ISSUE #152: Add an indicator to method meta data to indicate static methods
**Describe the project you are working on:**
The GUT unit testing framework.

**Describe the problem or limitation you are having in your project:**
When creating doubles for objects I cannot determine if a method is static or not which causes error when instantiating said object.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
I can exclude static methods from doubling.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
In the results of `get_method_list` the dictionary would include some way to determine if a method is static or not.

**Describe implementation detail for your proposal (in code), if possible:**
NA

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
There is a workaround.  Barring any way to determine the status from info provided by the engine, I must make users specify a list of functions not to double.  This is more cumbersome for users than it is to code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I don't know how an add-on could supply this info.  It's also useful information that others may need at some point.  Most everything else about the method is provided by `get_method_list`

### LINKED ISSUE #25432: "class_name" field of property list item is wrong for use defined classes and for at least CanvasItem.material
**Godot version:**
Godot 3.1 beta 3

**OS/device including version:**
Linux 64bit ( Solus )

**Issue description:**
The property list returned by Object.get_property_list() includes a field called class_name for each entry. Said field never has the correct class name for any property that has a user defined class set as it's static type. Only the class_name of the last build-in base class is used. 
Might be related to #21789 

Further more, the class name field for the property material of the class CanvasItem has the string "ShaderMaterial,CanvasItemMaterial" whereas the actual class should simply be Material according to the docs. Possible that other classes might have similar behaviour.

In any case, class_name should be atomic and never a list.

**Steps to reproduce:**
Check get_property_list() Method on class that has members with user defined classes and CanvasItem.

### LINKED ISSUE #31181: Object.get_method_list()
Godot version: 3.1.1
Issue description:
function Object.get_method_list() does not return the names and types of arguments  in user-defined functions

### LINKED ISSUE #33624: get_method_list() returns an incorrect info about custom functions
**Godot version:**
3.1.1.stable.official
3.2.beta1.official

**OS/device including version:**
Linux

**Issue description:**
See the title above and the example below.

**Steps to reproduce:**

```gdscript
extends Node

func my_func(s: String, my_arg := 42000) -> bool:
    return my_arg % 7 == 0

func print_info(i):
    var args = ''
    for j in i.args:
        args += '%s:%s;' % [j.name, j.type]
    print('name=%s args=%s default_args=%s return.type=%s' %
            [i.name, args, i.default_args, i.return.type])

func _ready():
    for i in get_method_list():
        if i.name == 'my_func' || i.name == 'connect':
            print_info(i)
    for i in get_script().get_script_method_list():
        if i.name == 'my_func':
            print_info(i)

# name=connect args=signal:4;target:17;method:4;binds:19;flags:2;
    # default_args=[[], 0] return.type=2
# name=my_func args=arg0:0;arg1:0; default_args=[] return.type=0
# name=my_func args=:4;:2; default_args=[] return.type=1
```

**Minimal reproduction project:**

### LINKED ISSUE #55482: get_script_method_list() output differs from get_method_list() on same script and neither return 'default_args[]'
### Godot version

v4.0.dev.custom_build [cf67f18ce]

### System information

Linux, Vulkan

### Issue description

get_method_list()

doesn't return arg types

and both always return an empty 'default_args[]' array

### Steps to reproduce

```
extends Node

func test(arg, default_arg: String):
	pass

func _ready():
	for method in get_method_list():
		if method.name == "test":
			print(method.args, " default_args -> : ", method.default_args) #[{class_name:, hint:0, hint_string:, name:arg0, type:0, usage:7}, {class_name:, hint:0, hint_string:, name:arg1, type:0, usage:7}] default_args -> : []
	for method in get_script().get_script_method_list():
		if method.name == "test":
			print(method.args, " default_args -> : ", method.default_args) #[{class_name:, hint:0, hint_string:, name:arg, type:0, usage:524295}, {class_name:, hint:0, hint_string:, name:default_arg, type:4, usage:7}] default_args -> : []
```

### Minimal reproduction project

_No response_

### LINKED ISSUE #67544: GDScript 2.0: `get_method_list()` and `class_get_method_list()` return an incorrect function description
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I use `get_method_list` and `class_get_method_list` to create a function descriptor to create a spy or mock for a class and I strictly rely on the information provided being correct and complete.

I run into this issue when migrating my plugin GdUnit3 to Godot4 and my spy tests failing by creating invalid functions.
For example the function description `get_script` is broken in Godot4, the return type is TYPE_NIL but should be `Variant` 

There is no TYPE definiton for `Variant` sounds like TYPE_VARIANT is missing.

```
{
   "name":"get_script",
   "args":[
      
   ],
   "default_args":[
      
   ],
   "flags":5,
   "id":12,
   "return":{
      "name":"",
      "class_name":"&""",
      "type":0,
      "hint":0,
      "hint_string":"",
      "usage":262150
   }
}
```

### Steps to reproduce

- put the code in your script `testScene.gd` and execute

```
class_name TestScene
extends Node

func _ready():
	test_extract_functions()

func test_extract_functions() -> void:
	var script :GDScript = load("res://testScene.gd")
	var script_functions :Array = script.get_method_list()
	for function in script_functions:
		if function["name"] == "get_script":
			prints(script.resource_path.get_file(), function)
	var base_clazz :String = script.get_instance_base_type()
	if ClassDB.class_get_method_list(base_clazz):
		var clazz_functions := ClassDB.class_get_method_list(base_clazz)
		for function in clazz_functions:
			if function["name"] == "get_script":
				prints(base_clazz, function)
```
Output:
Godot 4 (return type is 0)
```
testScene.gd { "name": "get_script", "args": [], "default_args": [], "flags": 5, "id": 12, "return": { "name": "", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 262150 } }
Node { "name": "get_script", "args": [], "default_args": [], "flags": 5, "id": 12, "return": { "name": "", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 262150 } }
```
Godot 3 (return type is 17)
```
testScene.gd {args:[], default_args:[], flags:9, id:12, name:get_script, return:{class_name:Reference, hint:19, hint_string:Reference, name:, type:17, usage:7}}
Control {args:[], default_args:[], flags:9, id:12, name:get_script, return:{class_name:Reference, hint:19, hint_string:Reference, name:, type:17, usage:7}}

```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #25432.
  * See also #77618.
* Closes #31181.
* Closes #33624.
* Closes #55482.
* Closes #67544.
* Closes godotengine/godot-proposals#152.
  * The `METHOD_FLAG_STATIC` flag was added by #46378, this PR adds the flag for GDScript static methods.
* Supersedes #50425.
* See also #68454.
* See also #79366.

### CODE REVIEW

**Review by adamscott — DISMISSED** [review]
Looks fine! And even simplify a lot the code. Thanks as always, @dalexeev

**Comment by bitsawer** [comment]
Do you know if this helps or affects https://github.com/godotengine/godot/issues/66218 in any way?

**Comment by dalexeev** [comment]
> Do you know if this helps or affects #66218 in any way?

In the case of non-constant expressions (as well as arrays and dictionaries), the default value is unknown. We can only insert `null` instead.

**Comment by bitsawer** [comment]
I guess null could be a reasonable choice, at least that way it would be possible to figure out at least some default arguments. If understood that issue issue right, it's not currently possible in all cases. Then again maybe we could use some magic sentinel value instead of null, like return certain type of object etc. to mark that the value could not be used. That way it would also be possible to tell a difference between an actual null default vs non-constant expression.

Not really relevant to this PR, but thanks for answering!

**Comment by adamscott** [comment]
@dalexeev If you could comment the changes you made in this PR, as discussed in the GDScript meeting, it would be very appreciated!

**Comment by dalexeev** [comment]
This PR fixes GDScript "reflection" of **properties** (static and non-static variables, the latter can optionally be exported), **methods** and **signals**. There are many open duplicate issues, but in each of them there are some different details that I tried to cover everything.

1\. Prior to this PR, there was no single method for converting a GDScript data type into a `PropertyInfo` that best matches it. Unfortunately, it is not always possible to ideally represent a GDScript type as a `PropertyInfo` (for example, in the case of non-global classes, inner classes). This is a core issue that is still needs to be unified.

The `GDScriptDataType` class (which represents **runtime** type) had an `operator PropertyInfo()`, but it a. was not used everywhere (for example, signals) and b. loses some information (for example, enums). This is now the `to_property_info()` method in the `GDScriptParser::DataType` class (which represents **static** type) and its implementation has been improved.

2\. There was an issue with `Object.get_*_list()` and `Script.get_script_*_list()` methods returning different data due to duplicate implementations. Now this data is stored in `GDScript` (`MemberInfo::property_info`) and `GDScriptFunction` (`method_info`) structures. They are generated once in the compiler (in the analyzer for signals) and the `GDScript`/`GDScriptInstance` methods simply return the data, rather than generating it in different places.

3\. This PR fixes the inconsistent use of the `GDScript::name` property in some cases as a global name (in the `Script::get_global_name()` override) and in others as a local (inner class identifier).

4\. Minor reorganization of `GDScriptFunction`: dead code removed, properties and methods arranged more conveniently.

5\. Fixed incorrect function parameter names for `get_method_list()`, argument names and default argument values are now available in release builds too.

6\. Fixed bug with missing `PROPERTY_USAGE_NIL_IS_VARIANT` for `Variant` variables.

7\. Fixed bug with missing `METHOD_FLAG_STATIC` for static functions.

**Review by adamscott — APPROVED** [review]
Approved by the GDScript team in meeting. Great work @dalexeev, and especially great explanation of what you did. Magnificent.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
