### PR TITLE
Added insert comment option in visual script

### LINKED ISSUE #28079: Comment shortcut for Visual Script
In GDscript we can do Ctrl+K to comment/uncoment one or more lines. Maybe the same could be done in Visual Script, so Ctrl+K puts a comment node around the nodes you selected. Manually configuring a comments size is very tedious and could be made way easier with this.

### PR DESCRIPTION
**Pull request by Jummit**
Closes #28079
You can also double click on comment nodes to update the bounds.
I am making this two commits because they are kinda two separate features.

### CODE REVIEW

**Comment by fire** [comment]
Will take a build and look.

**Comment by fire** [comment]
Will review on Monday. Going to take the weekend to rest and recuperate.

**Comment by Jummit** [comment]
Sorry, but I think this isn't quite working right now. I tried it on a clean build and the sizes of the comments are slightly off. Will look into it, but I wouldn't try to merge it just yet.

**Comment by Jummit** [comment]
Turns out it was something to do with the editor scale. Fixed it now, ready to merge!

**Comment by akien-mga** [comment]
Could you squash commits together?

**Comment by fire** [comment]
Reviewing now.

**Comment by fire** [comment]
Is it expected that double clicking an empty comment will make it disappear?

**Comment by fire** [comment]
I'm interested in designing a grouping PR for VS. This allows the ability to move every single node in the comment box, but that's a more complicated design I've sketched in the proposals repository.

**Comment by fire** [comment]
I was expecting double clicking an comment enclosing nothing should do nothing.

**Comment by Jummit** [comment]
> I was expecting double clicking an comment enclosing nothing should do nothing.

Fixed. (Hopefully)

**Comment by fire** [comment]
@swarnimarun Can you review this?

**Comment by Jummit** [comment]
> Could you squash commits together?

Done.

**Comment by fire** [comment]
Will review when I have more bandwidth.

**Comment by fire** [comment]
Can you rebase to latest?

**Comment by Jummit** [comment]
> Can you rebase to latest?

Done.

**Comment by aaronfranke** [comment]
@Jummit Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by Jummit** [comment]
I think I won't port it to master.

**Pull request closed without merging**
