### PR TITLE
Take h_separation into account for label and icon positions (item_rect)

### PR DESCRIPTION
**Pull request by joao-pedro-braz**
## Description

This PR makes it so that when drawing an item_rect the h_separation is taken into account when computing the icon and label positions. The immediate effect is that TreeItem icons in the Editor are no longer drawn "hogging" the item's border, which was specially perceptible when using a Corner Radius greater than 3.

## Comparisons

image
*Default with Corner Radius 3*

image
*PR with Corner Radius 3*

image
*Default (RTL) with Corner Radius 3*

image
*PR (RTL) with Corner Radius 3*

image
*Default with Corner Radius 6*

image
*PR with Corner Radius 6*

### CODE REVIEW

**Comment by joao-pedro-braz** [comment]
Also, is there any particular reason on why antialiasing is not enabled by default in the Editor Theme?

**Comment by joao-pedro-braz** [comment]
I guess the root problem then is that the item_rect themselves don't have a stylebox, right?
They only get one if they're focused and/or selected.

If we were to add a default StyleBox to them, then I guess we could solve this problem through the Content Margins.
What do you think?

**Comment by YuriSizov** [comment]
Yeah, that sounds like a good idea. Just need to make sure that in the default theme that stylebox doesn't do anything (so existing themes work as expected).

**Comment by joao-pedro-braz** [comment]
Yeah, that's a good idea.
Working on it right now!

**Comment by joao-pedro-braz** [comment]
Closing due to https://github.com/godotengine/godot/pull/74321, which implements this feature as discussed.

**Pull request closed without merging**
