### PR TITLE
Compile Godot Engine as a library.

### LINKED ISSUE #4773: Build Godot Engine as a shared library
### Describe the project you are working on

Multiplayer Video game - https://github.com/V-Sekai

### Describe the problem or limitation you are having in your project

1. I want to have dynamic mesh plugins and Houdini and Houdini like effects from OpenMeshEffect.

2. @punto- Mentioned wanted to use Godot Engine from nodejs.

3. I want to call libgodot from elixir.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The standard architecture of Godot Engine is that we want things to be Godot Engine Extensions.

It should be possible to embed Godot Engine into a shared library for OpenMeshEffect standard and also as an Extension.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Build Godot Engine as a shared library.

Replace the entry points of main.

See pull request.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No! This is a buildsystem change to Godot Engine.

### Is there a reason why this should be core and not an add-on in the asset library?

Changing the build system of Godot Engine is difficult to most people.

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot-proposals/issues/4773

- [x] Replace the entry points of main of Windows and Linux.
- [x] Replace the entry points of osx.
- [ ] Replace the entry points of android.
- [ ] Replace the entry points of ios.
- [ ] Replace the entry points of uwp.
- [ ] Investigate the entry points of Javascript.
- [x] Cannot avoid 64k symbols limit on Windows dll format.
----

Part of the V-Sekai group. https://github.com/v-sekai

### CODE REVIEW

**Comment by Faless** [comment]
My understanding is that calling `godot_main` will basically result in the main loop starting and the function only returning when the main loop quits. Am I missing something? :eyes:

**Comment by fire** [comment]
Yes, in my example and tested on the Linux platform I run the scenetree iteration loop manually. 

https://github.com/V-Sekai/godot/blob/elixir/c_src/godot/godot_elixir.cpp

**Comment by Faless** [comment]
I see, so the windows version which only exposes the `godot_main` isn't usable for this purpose right?

**Comment by fire** [comment]
There are three problems on Windows.

1. there's a 64k symbols limit.

`scons -j32 library=true use_llvm=yes use_mingw=yes LINKFLAGS='-Wl,--export-all-symbols -Wl,-pdb=' CCFLAGS='-g -gcodeview' debug_symbols=no`

2. If we can't expose everything, mingw has a way to force map a list of symbols.

3. Need know what symbols to keep.

**Comment by bruvzg** [comment]
> If we can't expose everything, there's ways to force map a list of symbols.

It is necessary to directly exposing everything? Besides, exported C++ symbols are not portable and will be usable only if main app is built with exactly same compiler and C++ runtime version, which kinda makes it almost useless.

Maybe it's better to expose only a few pure-C wrappers for OS/Main initialization / finalization, and functions to get access GDExtension interface struct and register initializers/terminators, the and the rest can be done via GDExtension API.

**Comment by fire** [comment]
It’s a good suggestion to get at the gdextension api. Or at least the classdb and execution of the api. Can look

**Comment by fire** [comment]
Can be salvage or used as is. Closing for now.

**Pull request closed without merging**
