### PR TITLE
fix AnimationBlendTree graph update on input count change

### LINKED ISSUE #45437: AnimationNodeTransition does not visually update upon changing input count or input names
**Godot version:**

v3.2.3-stable

**OS/device including version:**

Manjaro Linux, running kernel `5.9.1-1-rt19-MANJARO` (64-bit), using KDE with Plasma version `5.20.4` in X11.

Using an Nvidia GeForce GTX 1060 6GB with driver version 455.45.01.

Performed in 2D mode, using GLES3.

**Issue description:**

Upon updating an Transition node's "Input Count" property or any input of the Transition node's "Name" property within an AnimationNodeBlendTree will not visually update the number of inputs or the names of the inputs until another node is added to the AnimationNodeBlendTree. 

Closing the editor (that is, quitting to the project list or closing the program entirely) and reopening the project also visually updates the Transition node. Closing the scene and reopening it does not update the Transition node.

Deleting the node and then undoing the action will also update the Transition node.

Deleting the parent AnimationTree and then undoing the action does not update the Transition node.

**Steps to reproduce:**
1. Within an AnimationNodeBlendTree, place a Transition node.
2. Update the "Input Count" parameter and/or the "Name" parameter of any input of the Transition node.
3. Place any other node within the AnimationNodeBlendTree to update the Transition node, OR close and reopen the project in its entirety, OR delete the Transition node and undo the action.

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/5864192/example.zip)

### PR DESCRIPTION
**Pull request by kodiwills**
Fixes https://github.com/godotengine/godot/issues/45437

Connects blend tree plugin to the `tree_changed` signal which is emited when set_input is updated. The signal then calls update_graph.

### CODE REVIEW

**Comment by kodiwills** [comment]
@unsignedFoo Pull request up. It fixes the issue but we need to make it better.

**Comment by unsignedFoo** [comment]
I'll proceed to compile and test

**Comment by unsignedFoo** [comment]
problem persist if we update the name of the property

**Comment by kodiwills** [comment]
Now fixes https://github.com/godotengine/godot/issues/49375 while also fixing the AnimationNodeAnimation name property as well.

**Review by phocodes — APPROVED** [review]

**Comment by unsignedFoo** [comment]
It works fine :+1:

**Comment by jcostello** [comment]
There are merge errors to fix

**Comment by kodiwills** [comment]
Yeah my git repo got a little messed up. When I tried to squash the commits I accidently pulled someone else's commit. It should be fixed now. I think the formatting error is fix now so it should pass. Sorry everyone.

**Review by lyuma — APPROVED** [review]

**Comment by reduz** [comment]
looks good, suggested changes with SNAME are required now in order to merge.

**Comment by kodiwills** [comment]
Created new pull request for the reason stated in the linked pull request.

**Pull request closed without merging**
