### PR TITLE
Docs: Fix SurfaceTool example caps typo

### PR DESCRIPTION
**Pull request by archsolar**
Example wasn't valid

### CODE REVIEW

**Review by RedworkDE — COMMENTED** [review]
Needs a better commit message / PR title as per https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind, eg something like `Fix typo in C# example of SurfaceTool documentation`

LGTM otherwise

**Review by mhilbrunner — APPROVED** [review]
LGTM. Pushed a rebase + added context to PR title and commit message.

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged Godot PR!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Pull request merged**
