### PR TITLE
[WIP] Add support for double precision floats #288

### PR DESCRIPTION
**Pull request by fire**
Work in progress. DO NOT MERGE.

See: https://github.com/godotengine/godot/issues/288

### CODE REVIEW

**Comment by fire** [comment]
```
1>  cl /Fothirdparty\libpng\pngrtran.windows.opt.tools.64.obj /c thirdparty\libpng\pngrtran.c /nologo /O2 /DDEBUG_ENABLED /MT /Gd /GR /nologo "/IC:\Program Files (x86)\Windows Kits\10\/Include" /DWINDOWS_ENABLED /DOPENGL_ENABLED /DRTAUDIO_ENABLED /DWASAPI_ENABLED /DTYPED_METHOD_BIND /DWIN32 /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /D_WIN64 /DREAL_T_IS_DOUBLE "/IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\include" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include" /I "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include" /I "/IC:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt" /I /I "/IC:\Program Files (x86)\Windows Kits\8.1\Include\um" "/IC:\Program Files (x86)\Windows Kits\8.1\Include\shared" "/IC:\Program Files (x86)\Windows Kits\8.1\Include\winrt" /I /I /w /DMSVC /GR -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DGLAD_ENABLED -DGLES_OVER_GL -DPNG_ARM_NEON_OPT=0 /Icore /Icore\math /Ieditor /Idrivers /I. /Iplatform\windows /Ithirdparty\zstd /Ithirdparty\zstd\common /Ithirdparty\zlib /Ithirdparty\rtaudio /Ithirdparty\glad /Ithirdparty\libpng
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\include\type_traits(2342): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  pngmem.c
1>drivers\gles3\shader_gles3.cpp(98): error C2664: 'void (GLint,GLsizei,GLboolean,const GLfloat *)': cannot convert argument 4 from 'const real_t *' to 'const GLfloat *'
1>  drivers\gles3\shader_gles3.cpp(98): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>  pngpread.c
```

Blocked until I investigate this futher.

**Comment by fire** [comment]
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_gpu_shader_fp64.txt Need to get the fp64 functions somehow.

**Comment by fire** [comment]
My plan is to split the patch into converting floats to real_t and  @akien-mga What do you think?

That means trying to do the first https://github.com/godotengine/godot/issues/288#issuecomment-326744158 .
```
1. There is some support for using doubles in binary serialization, but it's probably not complete. files such as resouce_format_binary.cpp and marshalls.cpp would need to be checked and made sure that doubles are written (and read) in a binary compatible way.
```

This is tested via float=64 option.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by aaronfranke** [comment]
@akien-mga This should definitely be considered a feature request and not a bug fix. It doesn't make too much sense to add to a 3.0.1 maintenance release, but the 3.1 milestone does make a lot of sense.

**Comment by reduz** [comment]
probably will make sense for 3.1, I definitely want this eventually added

**Comment by fire** [comment]
Was able to get a build running with many things converted to real_t (double).

Use `scons p=windows vsproj=yes float=64 -j36` to build with floating point being 64 bit.

I had to disable ptrcall, bullet and gdnative. Would be interested in people looking why they break.

Note that the graphics driver still converts back to float.

**Comment by fire** [comment]
Hm, it was actually having linking errors :/ However if someone could help that would be so useful.

**Comment by aaronfranke** [comment]
Color math can be left as single-precision if it doesn't cause any issues. 23 significant digits is enough for 20 bits per channel color math, and most displays and implementations only support 8 or 10 bits, and it would be extremely rare to have more than 16 bits per channel (or 64 bits per pixel).

**Comment by aaronfranke** [comment]
@fire I think it would be best if you created many smaller pull requests instead of this one big pull request. Not only does it get conflicts easily but also it's hard to review so many changes.

For example, you could make pull requests for "replace float with real_t in x and y files" or something.

**Comment by fire** [comment]
Got your message, I'll try to find effort to work on this.

**Comment by aaronfranke** [comment]
This PR should probably be assigned the "salvageable" tag.

**Comment by fire** [comment]
@aaronfranke What are your plans for taking this forward? Doing some spring updates and cleaning on my pull requests.

**Comment by aaronfranke** [comment]
After https://github.com/godotengine/godot/pull/21922 is merged I plan to pick-and-test parts of this one, since this PR is functional-ish.

**Comment by fire** [comment]
@aaronfranke Updated to lastest. Still work in progress.

**Comment by Anutrix** [comment]
Any updates?

**Comment by fire** [comment]
Rebased.

**Comment by akien-mga** [comment]
Moving to 4.0 milestone as that's when we'll handle #288 (via this PR, #21922 and some more changes needed).

**Comment by fire** [comment]
This pull request is very out of date. 

I'll take a look at rebasing on top of https://github.com/godotengine/godot/pull/21922 and Vulkan.

**Pull request closed without merging**
