### PR TITLE
Blend file import: Don't keep original files when not unpacking them

### LINKED ISSUE #82455: Importing .blend file results in Roughness texture being used as Metallic texture
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3713) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

When importing .blend files, the Roughness texture is used for both the Roughness and the Metallic properties of the imported material. I would expect the imported model to use the Metallic texture that was set up in Blender.

image

image

image

### Steps to reproduce

In Blender (3.6.3):
* Layout > Add > Mesh > Monkey
* Shading > New
* Create Metallic texture
  * Add > Texture > Image Texture
  * Connect Color to Metallic
  * Click New on the Image Texture and create image "Metallic"
  * Change the Image Texture's Color Space to Non-Color
  * Switch to Texture Paint and draw some shapes on the texture
* Create Roughness texture
  * Similar to steps for Metallic
* File > Save
* File > External Data > Pack Resources

In Godot (4.1.1):
* Create a new Forward+ project
* Drag .blend file into FileSystem's "res://" folder.
* Select it in the FileSystem, go to Import and click "ReImport"
  * Note: I had to do this in order to make the material have any textures at all. May be a separate bug.
* Create a 3D Node
* Drag .blend file from FileSystem to be a child of the 3D Node
* Open the imported scene in the editor (Click "Open Anyway")
* Inspect the mesh's surface material and observe that the Metallic and Roughness textures are both the Roughness texture that was created earlier.

### Minimal reproduction project

Godot project: [MetallicImportBugRepro_Godot.zip](https://github.com/godotengine/godot/files/12741593/MetallicImportBugRepro_Godot.zip)

Blender project: [MetallicImportBugRepro_Blender.zip](https://github.com/godotengine/godot/files/12741540/MetallicImportBugRepro_Blender.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
This depends on PR #96778. Fixes #82455 assuming it is acceptable to require users to uncheck a box.

Screenshot 2024-09-10 at 2 32 37 AM

In the current master, the Blend file import code always keeps the original files, and there is a checkbox to control if the original textures are unpacked. By default, the checkbox is checked, which unpacks the original textures, imports them, and uses them. However, this is not always the correct behavior, as pointed out in #82455 sometimes the correct textures are not the originals. If the user unchecks this box, then the original textures are not unpacked, but it still tries to keep using them, resulting in the textures simply being missing.

With this PR, the behavior of having the checkbox unchecked is different. Now when it is unchecked, keep originals will also be set to false, allowing Blender to convert textures as needed. For example, re-packing roughness and metallic into one roughness+metallic texture. This means that when the checkbox is unchecked, instead of failing to import the textures, it will successfully import.

Ideally, it would be nice if we could just have keep originals set to false, letting Blender do whatever conversion it needs when it needs it to make the textures correct, and then have the unpack checkbox only control whether those correct textures are saved in the project or not. However, it does not seem that Blender has an option for unpacking the altered textures, only the originals. I dug around the Blender glTF export code for a few hours and I was not able to figure it out. Regardless, if we do figure that out, this PR does not prevent doing so in the future. It would also be nice if there was a way to detect when a texture needs conversion, and convert it anyway, even if the arguments were to keep the originals (better to convert than to export a broken file). However, the Blender code [has a warning in it](https://github.com/KhronosGroup/glTF-Blender-IO/blob/295bbf7eda4c3de5429a01a0d919f42d90aaf5f9/addons/io_scene_gltf2/blender/exp/material/texture.py#L181-L184) already for this case, so I think it's intentionally not supported. All that said, this PR is the best solution I can come up with unless we want to modify Blender or do some weird hacks on our end.

### CODE REVIEW

**Comment by fire** [comment]
The design goals for the blender importer is that we keep the image originals and @reduz made great effort to request this several years ago.

- we can fail the blender import
- we can apply this pr
- ???

**Comment by aaronfranke** [comment]
@fire It still does keep the original images by default, but if the original files do not comply with the glTF specification, then the original images will not function correctly (the material will look wrong). Therefore, this PR allows the user to choose not to keep the originals by unchecking the box to unpack them.

**Comment by fire** [comment]
Why is this in draft mode?

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
