### PR TITLE
Update libtheora to GIT (2020.10)

### PR DESCRIPTION
**Pull request by DeeJayLSP**
As libtheora GIT (2020.10) was mentioned in #52410, I decided to take that update.

The patch folder was removed, as the newer version includes it.

As this PR mostly touches code that is unchanged from 3.x to 4.0, I believe this is cherry pickable.

By running some tests I got the conclusion that libtheora GIT is about **18% faster** than 1.1.1.

I tested decoding a 1080p50 video with both 1.1.1 and GIT built from source, both results ran on the same CPU. 
- 1.1.1 managed to decode at 68FPS 
- GIT managed to decode at 81FPS

### CODE REVIEW

**Comment by DeeJayLSP** [comment]
It seems that some builds break due to `cpu.c` being replaced with `x86/x86cpu.c` and `x86_vc/x86cpu.c`.

**Comment by DeeJayLSP** [comment]
I tried to build this on Linux and it worked just fine, any hints on what's happening with checks?

**Comment by aaronfranke** [comment]
```
thirdparty/libtheora/x86/x86int.h:55:11: fatal error: x86cpu.h: No such file or directory
   55 | # include "x86cpu.h"
      |           ^~~~~~~~~~
```

The file it's looking for does not exist. Here is the folder: https://github.com/DeeJayLSP/godot/tree/update_theora/thirdparty/libtheora/x86

Note that it does exist in the "x86_vc" folder, but it's missing from the "x86" folder.

**Comment by DeeJayLSP** [comment]
This is weird, it does exist on the folder I'm pushing.

Will try to figure out how to force it.

**Comment by DeeJayLSP** [comment]
This likely being caused by .gitignore, which has a `x86/` on it.

**Comment by DeeJayLSP** [comment]
I see that /arm is also missing. Requiring it later or not, I'm going to force it too.

**Comment by DeeJayLSP** [comment]
Running the binary from this PR on a phone with Vulkan support worked with no crashes and played the video just fine.

I would like to say this PR is complete.

**Comment by Calinou** [comment]
Out of curiosity, does this dependency update improve decoding quality?

**Comment by DeeJayLSP** [comment]
All I am 100% sure is that outside platforms that add either `x86_libtheora_opt_gcc` or `x86_libtheora_opt_vc` to env, you have one less file compiled in, which is cpu.c.

And according to [this 12 year old article](https://people.xiph.org/~xiphmont/demo/theora/demo9.html) there are some decoding optimizations.

**Comment by DeeJayLSP** [comment]
With further search (thanks to FNA-XNA/Theorafile, which recently updated to upstream libtheora), I now know that `arm/`, `c64x/`, `x86/` and `x86_vc` are optimizations for specific CPU types.

Unfortunately, the ARM optimizations within it (which would be amazing to have here) seem incompatible with Godot's buildsystem, since it isn't purely C/C++ (it includes GNU Assembler and Perl).

**Comment by DeeJayLSP** [comment]
One last force push just to remove arm/ and c64x/ folders. Both are not being used.

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

We have slight concerns about using a Git branch from a mostly dead project when their latest stable release was 1.1.1 from 2011... but apparently ffmpeg is using the Git branch for its binary releases and other projects are also using it successfully. Early test results also seem promising. So let's give it a spin and see how it goes.

As mentioned above, ARM optimizations should be added in a follow PR as we do want them for Android, iOS, macOS M1 and various Linux and Windows platforms.

**Comment by DeeJayLSP** [comment]
As I said in the review (and forgot to mention here), the ARM optimizations in libtheora GIT only build for arm32.

**Comment by akien-mga** [comment]
Thanks!

**Comment by DeeJayLSP** [comment]
I forgot to mention: even Firefox uses libtheora GIT.

**Pull request merged**
