### PR TITLE
[3.x] CPUParticles - fix non-interpolated `NOTIFICATION_TRANSFORM`

### LINKED ISSUE #80697: [3.6 beta3] CPUParticles2D glitch/stutter with Local Coords off
### Godot version

3.6 beta3

### System information

Windows 10

### Issue description

There is a coords/position problem with CPUPatricles2D with Local Coords off.

First problem: when you toggle the Local Coords in the editor, the node changes position for (1 frame I believe) before returning to its designated position.

Second problem: changing the position of the said CPUParticles2D node results in stutter of the already emitted sprites. The tricky bit is that it doesn't always happen, but it does happen regularly (and the problem is exacerbated in a real project).

### Steps to reproduce

See the MRP and click Local Coords on/off in the editor on the Fountain node.

### Minimal reproduction project

[CPUParticles2D_bug.zip](https://github.com/godotengine/godot/files/12363092/CPUParticles2D_bug.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
Updates global particle transforms immediately on receiving notification, to match legacy behaviour.

Fixes #80697

## Notes
* Godot 3.5 and earlier worked in this way. It isn't super efficient as it often transforms the particles twice on a frame, but it fixes the regression and allows making more efficient versions at leisure.
* One alternative way to fix this is to disable `GODOT_CPU_PARTICLES_2D_LEGACY_COMPATIBILITY`, so global particles are specified in proper global space and there is no need to "re-jig" when the parent object changes.

## Discussion
The whole system of using the inverse transform I have confirmed was a historical bodge to work with the existing `VisualServer`. So there is the opportunity to move the legacy particles to true global space as used by physics interpolated global particles.

On the downside, the bounds calculation is more complex when using true global space, because bounds are expected in local space (see fixes here in #80887 for physics interpolated particles) so I'm of the opinion it probably makes more sense to get this working and tested with physics interpolation before attempting the same with non-interpolated particles.

For this reason I'm moving this out of draft as it should be a good fixup in the meantime.

### CODE REVIEW

**Comment by oeleo1** [comment]
@lawnjelly Well, you made me compile Godot on Windows just to test this patch 👍 and indeed, I can confirm that it fixes the particle glitches seen in the 3.6 beta3 release and reported in https://github.com/godotengine/godot/issues/80697. Modulo the one idle frame when toggling Local Coords on/off but as you explained it is not critical, beyond being annoying.

I guess I am now set to test other patches...

**Comment by lawnjelly** [comment]
Thanks for testing! I suspect it will work fine when we test the other patch too.

I'll make a PR for this too soon, but I noticed another bug while working on the disabled `GODOT_CPU_PARTICLES_2D_LEGACY_COMPATIBILITY` version, which seems to be a transform problem in the fountain particles when physics interpolation is on with your MRP (the fountain moves twice as far as it should). I'll hopefully be tracking this down soon.

Be sure to try with physics interpolation on as well and report any strange behaviour. :+1:

**Comment by lawnjelly** [comment]
Have figured out the bug above with interpolated particles. I had previously been testing particle systems that were moved by their parent, and thus their local transform was 0.

When moving the particle system _directly_ (in this case the fountain), the local transform was changing too, and I had been applying this in visual server (so the particles were moving twice as far as they should). As the particles are already in global space, the obvious solution is not to apply either parent or local transform.

It has occurred to me we should also pass on the regular `final_transform` to any children, just in case anyone added a child to a particle system (so to the child it would appear as though the transforms were propagated normally).

I'll do a PR for this bug and the variation of this PR with disabled `GODOT_CPU_PARTICLES_2D_LEGACY_COMPATIBILITY`. :+1:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
