### PR TITLE
[#7212] Fixed missing 'Variant' return values in documentation.

### PR DESCRIPTION
**Pull request by ducdetronquito**
I fixed some missing Variant return value in the documentation.

I'm am not done yet: there are still missing Variant return values in the `Dictionary` and `Geometry` documentation for
* Dictionary::back()
* Dictionary:: front()
* Dictionary::pop_back()
* Dictionary::pop_front()
* Geometry::ray_intersects_triangle()
* Geometry::segment_intersects_segment_2d()

There is no `_bind_methods()` defined in `Dictionary.h`: do I need to create one ?

Ps: I opened a [previous PR](https://github.com/godotengine/godot/pull/9590) for this issue but I'm not able to select the correct branch when reopening it... sorry for that :/

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you revert the changes to `classes.xml` for now and keep only the cpp changes? There are a lot of unrelated changes in the file due to lack of sync with the current master branch (surprisingly so, I had synced not that long ago...), and you lost a lot of documentation in the process for methods where e.g. the number of arguments changed.

**Comment by ducdetronquito** [comment]
Oh sorry for that... Is the lost of documentation due to a mistake of mine ?

Anyway, I'm gonna revert the changes of `classes.xml` today.

Only one question left: is it OK to create a `_bind_methods()` in `Dictionnary.cpp` in order to declare the return type of the following methods ?
* Dictionary::back()
* Dictionary:: front()
* Dictionary::pop_back()
* Dictionary::pop_front()

**Comment by akien-mga** [comment]
> Oh sorry for that... Is the lost of documentation due to a mistake of mine ?

Not a mistake, it's just Godot's doctool which is a bit unforgiving, so you need to be careful when using it. The "normal" workflow described in the docs is good when the template is in sync and the API doesn't get broken every 2 days, but currently one needs to be pretty careful when running doctool. I will handle it if you want, once this PR is merged.

**Comment by ducdetronquito** [comment]
Yeah, it would be kind ! I am not confident enough yet with Godot code base and workflow ._.

**Comment by akien-mga** [comment]
You could have kept the PR and just used (untested):
```
git reset HEAD~1 doc/base/classes.xml
git add doc/base/classes.xml
git commit --amend
git push --force
```

**Comment by ducdetronquito** [comment]
Yeah... I had some trouble to get the original version of `classes.xml` so I recreated a branch to redo the changes I made. I didn't know a PR can't be reopen in that case...

I'm going to open a new and last one. So sorry for this.

**Comment by akien-mga** [comment]
No problem, thanks for persevering :)

**Pull request closed without merging**
