### PR TITLE
Add zoom to GraphEdit

### PR DESCRIPTION
**Pull request by MarianoGnu**
Also fix some responsiveness issues:
-Box selection no longer visible when connecting.
-Allow cancel connection with mouse's right button.

@reduz  @akien-mga check this out, it's scheduled for 2.0

### CODE REVIEW

**Comment by StraToN** [comment]
Hm, this PR reminds me I was looking for a "good" way to create a sort of "minimap" of a GraphEdit, in order to navigate over huge Graphs.

**Comment by akien-mga** [comment]
Code looks fine :)

**Comment by StraToN** [comment]
@akien-mga Indeed, that range in strange. Wouldn't it be a good idea to clamp it between [0.01, 1], or between [0, 10] ?

**Comment by akien-mga** [comment]
>  Indeed, that range in strange. Wouldn't it be a good idea to clamp it between [0.01, 1], or between [0.01, 10] ?

Well the range in itself is fine IMO. Remember it's a zooming factor to apply to the scale, so [0.01, 1] would mean you could only zoom back :)

It's actually a more general documentation problems, there are many functions that accept only a certain range of values, and unless they are manually documented after a source code review, there is no real way to know the extents of the range. It would be nice if there were a way in the GDScript binding to tell users (and doctool probably) about the hardcoded range.

**Pull request merged**
