### PR TITLE
Deprecate functionality to copy visual Mesh data directly to a NavigationMesh

### PR DESCRIPTION
**Pull request by smix8**
Deprecates `NavigationMesh.create_from_mesh()` function and MeshInstance3D EditorPlugin `Create Navigation Mesh` dropdown option.

Both are a constant source of false user errors. The documentation already says what the functions do, copy vertices and indices from Mesh to NavigationMesh (and they do not more) but even what they do is wrong in most cases.

The vast majority of visual meshes have inherently invalid data for navigation mesh use. It makes little sense to support such a data copy directly with a dropdown Editor option that most new users will stumble over.

Both functions are from a time where Godot had a very simplistic concept of what a valid navigation mesh could and should be, with no navigation mesh connections and no NavigationServer to worry about.

For baking a valid navigation mesh from visual meshes either use a NavigationRegion or the NavigationMeshGenerator.
For procedural navigation meshes all the usual functions still exist to add vertices and polygons to a NavigationMesh. It is also a lot faster at runtime to use your vertices and indices arrays directly as the RenderingServer will make your performance bleed for receiving the visual mesh arrays.

### CODE REVIEW

**Comment by Sauermann** [comment]
As I have just learned in https://github.com/godotengine/godot/pull/77452#discussion_r1211749589, the deprecated functionality should be wrapped in `#ifndef DISABLE_DEPRECATED`.

**Comment by smix8** [comment]
> For baking a valid navigation mesh from visual meshes either use a NavigationRegion or the NavigationMeshGenerator.
> For procedural navigation meshes all the usual functions still exist to add vertices and polygons to a NavigationMesh.

Zireael07 I think you are referring to the GridMap issue from today. I already gave a step-by-step.
There is nothing specific to baking navigation meshes from GridMaps, it is basic NavigationRegion3D use.

**Comment by tavurth** [comment]
@smix8 I would much rather see this function duplicated to `NavigationMesh.create_from_plane_mesh`, while deprecating the old version.

Previously you said that:

> This create_from_mesh() function is a legacy problem that should be deprecated which I made a pr for https://github.com/godotengine/godot/pull/77702. This function gives users the illusion that they do something correct by copying visual Mesh data directly to a NavigationMesh while this is 95% of the times wrong, and those 5% are mostly plane meshes. All the documentation script examples that use this function assume plane, or at least flat surface, meshes without mentioning it explicit but that is another issue.

Ok great, maybe we can keep that functionality? Or is there a planned replacement?

Currently it's relatively simple to create a Navmesh as you mentioned in this issue (https://github.com/godotengine/godot/issues/77690):

```gdscript
		# Add a navmesh
		var plane = PlaneMesh.new()
		plane.set_size(Vector2(0.25, 0.25))

		self.nav_mesh = NavigationMesh.new()
		self.nav_mesh.create_from_mesh(plane)
```

What would be the new proposed way to do this from code if we are deprecating this function?

**Comment by smix8** [comment]
> What would be the new proposed way to do this from code if we are deprecating this function?

You add a very simplistic mesh with 4 vertices and 4 indices by using the `NavigationMesh.set_vertices()` and `NavigationMesh.add_polygon()` functions.

```gdscript
var navmesh : NavigationMesh = NavigationMesh.new()
navmesh.vertices = PackedVector3Array([
	Vector3(-10.0, 0.0, 10.0),
	Vector3(10.0, 0.0, 10.0),
	Vector3(10.0, 0.0, -10.0),
	Vector3(-10.0, 0.0, -10.0),
])
navmesh.add_polygon(
	PackedInt32Array([0, 1, 2, 3])
)
$NavigationRegion3D.navigation_mesh = navmesh
```

This is an optimization over the PlaneMesh cause you do not stall the RenderingServer to create and access the PlaneMesh which is problematic at runtime especially with threads.

You can also use a convex polygon instead of the triangles of a PlaneMesh as the NavigationServer supports any convex polygon.

> Or is there a planned replacement which can handle more cases?

The replacement is navigation mesh baking which handles all cases.

**Comment by smix8** [comment]
Examples from just the past 2 weeks why that functionality is a landmine that new users constantly run as if it is some kind of competition.
https://github.com/godotengine/godot/issues/77695
https://github.com/godotengine/godot/issues/77690
https://github.com/godotengine/godot/issues/78245

**Pull request closed without merging**
