### PR TITLE
SceneTreeDock: dragging node by column != 0 reparents wrong node  #10026 

### PR DESCRIPTION
**Pull request by albertomjp10**
Omitted drag preview for visibility icon due to unnecessary preview in addition to displaying wrong name, this way, confusion can be avoided, and no preview is presented since it is not needed in this section. Solution was posed by comment section of the issue  #10026

### CODE REVIEW

**Review by evanjbecker — CHANGES_REQUESTED** [review]
I think if you're going to create a PR like this, you should at least rebase your commits.

**Comment by albertomjp10** [comment]
@beckerej how do I rebase my commits so they change here?

**Comment by albertomjp10** [comment]
thanks

**Comment by YeldhamDev** [comment]
@albertomjp10 https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by albertomjp10** [comment]
@YeldhamDev thank you so much, will do!

**Comment by akien-mga** [comment]
Still needs a rebase, but I'm not sure that it's the correct solution. If it is, the line should be removed, not commented out.

**Comment by albertomjp10** [comment]
Ok, will re do the pull request, thank you

**Comment by akien-mga** [comment]
Superseded by #27810.

**Pull request closed without merging**
