### PR TITLE
`RendererCanvasCull` Simplify drawing antialiased polyline

### PR DESCRIPTION
**Pull request by kleonc**
Previously `RendererCanvasCull::canvas_item_add_polyline` was drawing antialiased polyline always as 9 triangle strips: 1 actual polyline, 4 for antialiasing sides (begin/end/left/right) and 4 for antialiasing corners. Even closed/looped polyline was drawn like that,with begin/end triangles being zero-area.
This PR makes antialiased polylines be drawn as 3 triangle strips, relevant begin/end parts (including corners) are included within the middle/left/right triangle strips (but only when the polyline is not closed/looped).

### CODE REVIEW

**Comment by clayjohn** [comment]
Seems good to me. I haven't done a detailed code review yet, but I am wondering if we shouldn't be targeting 4.1 with this. Since this isn't fixing a bug it may be better not to risk merging it right now.

**Comment by kleonc** [comment]
> Seems good to me. I haven't done a detailed code review yet, but I am wondering if we shouldn't be targeting 4.1 with this. Since this isn't fixing a bug it may be better not to risk merging it right now.

I'll just tell that before opening the PR I went through some triangle spaghetti steps because of the swapped indices here and there etc. and now it should be all good. :slightly_smiling_face: But I do see your point and it's fine to me to change the milestone.

**Review by clayjohn — APPROVED** [review]
Looks fine to me! Should be good to include in 4.1

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
