### PR TITLE
Add `GradientTexture2D`

### PR DESCRIPTION
**Pull request by Xrayez**
Based on #31655, co-authored-by @MarianoGnu.

godot_gradients

(yes, this is radial gradient texture used in a `Light2D` node, and animated with `AnimationPlayer`).

Godot proposal: godotengine/godot-proposals#1677.

Changes when comparing to #31655:
- creates a new `GradientTexture2D` rather than modifying existing `GradientTexture`;
    - if we go this route, then `GradientTexture` is better renamed to `GradientTexture1D`;
- create texture placeholder for when `gradient` is empty, similarly to `NoiseTexture` (***NOTE:*** `GradientTexture` needs a similar fix).
- fixed `get_width` and `get_height` virtual overrides (***NOTE:*** `GradientTexture` needs a similar fix).
- renamed `enum`s to just `Fill` and `Repeat`, `NO_REPEAT` renamed to `REPEAT_NONE` (conform to existing naming convention).
- moved member initialization from constructor to class declaration;
- grouped `fill_` and `repeat_` properties in the inspector.
- added `PROPERTY_USAGE_EDITOR_INSTANTIATE_OBJECT` for `gradient` (doesn't work in current `master`, see #43015);
- written documentation;
- duplicated the same icon used by `GradientTexture` (for now);
- various code style fixes;

Not sure about `fill_from` and `fill_to`. Perhaps it would be better to rename this to `fill_start_offset` and `fill_end_offset`.

# To-do
- [ ] Update new icon from goostengine/goost#44.
- [ ] Optimize the case for generating solid color textures: https://github.com/goostengine/goost/commit/c9ff44de7a753298b26cf24c9a62e314f9300b9b.

**Test project:**
[gradient_texture_2d.zip](https://github.com/godotengine/godot/files/5424038/gradient_texture_2d.zip)

### CODE REVIEW

**Comment by Xrayez** [comment]
Build artifacts are also available now, by the way:
- 🐧 Linux: https://github.com/godotengine/godot/actions/runs/311007142
- 🏁 Windows: https://github.com/godotengine/godot/actions/runs/311007127
- 🍎 macOS: https://github.com/godotengine/godot/actions/runs/311007123

**Comment by Chaosus** [comment]
@Xrayez this need to be rebased

**Comment by Xrayez** [comment]
Rebased, fixed `get_width` and `get_height` virtual overrides in the process (same issue needs to be fixed for `GradientTexture`...)

See also test project attached in the original post.

**Comment by Chaosus** [comment]
It runs and seems to work correctly except for the light which does not apply the color mask even if it set up - I need to set it manually - but I think this bug is unrelated to this PR:

grad_test

**Comment by Xrayez** [comment]
Fixed by creating texture placeholder, similarly to how `NoiseTexture` does it in `master`:
```c++
RID GradientTexture2D::get_rid() const {
	if (!texture.is_valid()) {
		texture = RS::get_singleton()->texture_2d_placeholder_create();
	}
	return texture;
}
```
Invalid textures were treated as bad by `Light2D` so no changes were applied, should be ok now.

The same limitation exists in `GradientTexture` (1D), but the fix is probably not needed there.

This is another change which differs current implementation from #31655, likely it wasn't completely obvious what changes were needed to make it work in `master`, not sure.

**Review by Chaosus — APPROVED** [review]
Seems fine now :)

**Comment by Xrayez** [comment]
I think this needs `invert` property, because if you use it as a radial texture for lights, then by default this will be:

Screenshot 2020-10-25 190807

In GDScript, in theory you could extend `GradientTexture2D` to override this to have properly defined:

```gdscript
@tool
class_name RadialLightTexture extends GradientTexture2D

func _init():
	fill = GradientTexture2D.FILL_RADIAL
	fill_from = Vector2(0.5, 0.5)
	fill_to = Vector2(0.5, 0.0)
	gradient = Gradient.new()
	# Invert by switching black and white.
	gradient.set_offset(0, 1.0)
	gradient.set_offset(1, 0.0)
```

But extending textures doesn't work because `Texture` is not registered as virtual class: #42830.

If you set those properties via inspector, you'll get this:

Screenshot 2020-10-25 191156

So, currently it takes a lot of steps to setup a radial texture like this... Mainly talking about use case described in godotengine/godot-proposals#1717, so perhaps adding `invert` property could help this process.

**Comment by Xrayez** [comment]
The 3.2 version of this PR is now merged in Goost: goostengine/goost#43.

**Comment by Xrayez** [comment]
> So, currently it takes a lot of steps to setup a radial texture like this... Mainly talking about use case described in [godotengine/godot-proposals#1717](https://github.com/godotengine/godot-proposals/issues/1717), so perhaps adding `invert` property could help this process. Alternatively, see [godotengine/godot-proposals#1724](https://github.com/godotengine/godot-proposals/issues/1724).

I've added `LightTexture` class in Goost which helps this use case significantly: goostengine/goost#60.

**Comment by Xrayez** [comment]
`[salvagable]`

Sorry for closing this and my other PRs, but I'm currently in a quite bad depression right now, so I'll be unable to work on Godot for some time.

**Pull request closed without merging**
