### PR TITLE
Expose soft body pin methods to GDScript

### PR DESCRIPTION
**Pull request by bengtsts**
This change was merged into master #51364 but requires class name changes for 3.x in code and documentation.
Node3D changed to Spatial and SoftBody3D to SoftBody.

### CODE REVIEW

**Review by pouleyKetchoupp — APPROVED** [review]
Looks good! I've just re-run the linux job, I don't think it failed for a good reason.

**Comment by pouleyKetchoupp** [comment]
My bad, there's a legitimate error in mono:
```
/home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/SoftBody.cs(634,74): error CS1750: A value of type 'string' cannot be used as a default parameter because there are no standard conversions to type 'NodePath' [/home/runner/work/godot/godot/modules/mono/glue/GodotSharp/GodotSharp/GodotSharp.csproj]
```

I'm not sure why this is happening. Maybe something wrong with an empty NodePath as default parameter.

**Comment by pouleyKetchoupp** [comment]
I've just tested locally, it looks like it could be a bug in mono (maybe fixed only on master since this error happens on 3.x only).

The generated mono glue for the new exposed method is:
```
[DebuggerBrowsable(DebuggerBrowsableState.Never)]
private static IntPtr method_bind_34 = Object.godot_icall_Object_ClassDB_get_method(nativeName, "set_point_pinned");

[GodotMethod("set_point_pinned")]
public void SetPointPinned(int pointIndex, bool pinned, NodePath attachmentPath = "")
{
    NativeCalls.godot_icall_3_802(method_bind_34, Object.GetPtr(this), pointIndex, pinned, NodePath.GetPtr(attachmentPath));
}
```

Although the node path argument should be `NodePath attachmentPath = NodePath()` or `NodePath attachmentPath = NodePath("")`

@neikeq Do you know what could cause this issue?

**Comment by neikeq** [comment]
@pouleyKetchoupp

This:

https://github.com/godotengine/godot/blob/ef1c5093727d22d18d3f02eefb6f7e8e5e98eadd/modules/mono/editor/bindings_generator.cpp#L2578-L2581

should be:

```cpp
if (r_iarg.type.cname == name_cache.type_NodePath) {
	r_iarg.default_argument = "(%s)\"" + r_iarg.default_argument + "\"";
	r_iarg.def_param_mode = ArgumentInterface::NULLABLE_REF;
} else {
	CRASH_COND(r_iarg.type.cname != name_cache.type_String);
	r_iarg.default_argument = "\"" + r_iarg.default_argument + "\"";
}
break;
```

to match current [master](https://github.com/godotengine/godot/blob/18c0f0b3ba46caf3f6dda401362bc5993eaf7f8d/modules/mono/editor/bindings_generator.cpp#L3021-L3031).

**Comment by akien-mga** [comment]
Rebasing on latest `3.x` should fix the Mono build issue.

**Comment by pouleyKetchoupp** [comment]
Please squash your commits (see [interactive rebase](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase)) and it should be good to go!

**Pull request merged**
