### PR TITLE
Added low_memory_2d_mode

### PR DESCRIPTION
**Pull request by romulox-x**
Added low_memory_2d_mode to indicate when 3D post processing buffers and viewport depth buffers should not be allocated.

### CODE REVIEW

**Comment by romulox-x** [comment]
Perhaps this should be unified with the disable_3d scons build option?  That's the intended use right now, though you could use the currect code with 3D if you didn't want to use any post processing and you wanted to eliminate those buffers.  So does this option mean "I'm only using 2D, eliminate as much 3D stuff as you can" (in which case I guess it should be under the disable_3d flag) or does it mean "Remove the 3D post processing buffers, and the viewport depth buffers" (in which case it might need a new name)?

**Comment by MarianoGnu** [comment]
Don't think so, this just skips initialization, but those stuff are built anyways, disable_3d is a build flag, preventing from build unused stuff and making build faster and executable lighter, you can always check if disable_3d is enabled and set the low_memory_2d flag on by default in that case, but doesn't make much sense to crate a buildflag for this the way it's implemented (as i see it, you can turn on/off in runtime)

**Comment by romulox-x** [comment]
What's wrong with the build option also compiling the code differently, instead of just omitting certain classes?  Godot's got lots of ifdefs for this kind of thing.  Yeah, right now the build option is just to trim down the binary size.  But there's no reason it needs to stay that way.  We could make it do that and also make the memory usage lower at runtime.

And you can't really turn this on and off at runtime that way it's written.  It's stuck however it was set when you exported the project.  Also, I'm not a big fan of having very similar settings in multiple places.  If someone wants to disable all the 3D stuff (and this is definitely disabling things that are only used in 3D), I'd rather they didn't need to set the build option and then find this setting.  I'd like it to be one place to do all of it.  I see no reason to keep the options separate.  If you use the build flag right now, I can't think of a reason you wouldn't also want the low_mem flag.  Is there a good use case for omitting the build flag (keeping the 3D nodes), and then using the low_mem flag (disabling the 3D buffers at runtime)?  Basically, would you ever want one without the other?

This is, of course, assuming that "I'm only using 2D, eliminate as much 3D stuff as you can" is the correct answer to my question in the first post.  If this is intended to also be available in 3D if you just want to cut out the post processing buffer memory, integrating it with the disable_3d option is no good.  But if that's the case, I don't think the viewport depth buffer stuff should be part of this flag anyway, so it needs some modification.

**Comment by romulox-x** [comment]
Looks like I forgot to create a branch under a good name.  This is just on the master branch of my repo.  Should I fix this?  Does it matter?

**Comment by MarianoGnu** [comment]
no problem on use the build option for this, i meant you should not add another build option :)

romulox-x: So does this option mean "I'm only using 2D, eliminate as much 3D stuff as you can" (in which case I guess it should be under the disable_3d flag) or does it mean "Remove the 3D post processing buffers, and the viewport depth buffers" (in which case it might need a new name)?

**Comment by romulox-x** [comment]
Ah, gotcha.

Reduz pointed out a reason you'd want one without the other - you might disable 3D nodes, but still want to use the post processing buffers.  So, there we go.  They don't always go together, so it'll stay separate.

**Comment by akien-mga** [comment]
> Looks like I forgot to create a branch under a good name. This is just on the master branch of my repo. Should I fix this? Does it matter?

It's not a problem as long as you don't push new commits to your master branch, since they would be added to this PR (unless they're improving this PR of course).

**Pull request closed without merging**
