### PR TITLE
[Modules] Replace `ERR_FAIL_COND` with `ERR_FAIL_NULL` where applicable

### PR DESCRIPTION
**Pull request by AThousandShips**
Second to last one, the last one will be servers, can combine it with this one but it is significantly larger, but might be easier to just keep it to one final push as that one is relatively hard to individually investigate in any case.

Then we can all rest!

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by AThousandShips** [comment]
(testing an additional case)

**Comment by AThousandShips** [comment]
There's also one instance in `thirdparty/enet/godot.cpp` which doesn't seem to be "truly" thirdparty, can add that one too for completeness, but can be merged as is regardless (won't convert to draft, but testing an case I might have missed earlier)

**Comment by akien-mga** [comment]
> There's also one instance in `thirdparty/enet/godot.cpp` which doesn't seem to be "truly" thirdparty, can add that one too for completeness, but can be merged as is regardless (won't convert to draft, but testing an case I might have missed earlier)

Yeah feel free to add that one.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Pull request merged**
