### PR TITLE
[RTL] Add support for character code BBCode tag `[char=...]`.

### PR DESCRIPTION
**Pull request by bruvzg**
Implements https://github.com/godotengine/godot-proposals/issues/9481

### CODE REVIEW

**Comment by KoBeWi** [comment]
This will need to be documented here: https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html#reference

**Review by KoBeWi — APPROVED** [review]
Works correctly.
I only wonder about the name. Is `uni` a standard BB code for unicode?

**Comment by bruvzg** [comment]
There's no standard bbcode for it (same is true for a some other tags we use).

**Comment by akien-mga** [comment]
Would `[char=...]` be more explicit to users maybe?

**Comment by coppolaemilio** [comment]
if there isn't a standard I would go with the full word `[unicode=...]` or with `[char=...]` like Akien suggested.
The short versions like `[img]` instead of `[image]` seem to only exists if there are html tags with the same name, if not, the full word is used (as far as I can tell, making it up tbh, so feel free to ignore).

**Comment by akien-mga** [comment]
Based on the RC discussion, let's go with `[char=...]` then.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
