### PR TITLE
Enable iOS modules and fix missing symbols errors (3.2)

### LINKED ISSUE #18359: iOS build error (Undefined symbols for architecture arm64)
**Godot Version**
3.0.2

**OS Version**
macOS High Sierra 10.13.4

**Issue**
produces this error when tries to build on phone
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SKProduct", referenced from:
      l_OBJC_$_CATEGORY_SKProduct_$_LocalizedPrice in ios.a(in_app_store.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_SKPayment", referenced from:
      objc-class-ref in ios.a(in_app_store.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in ios.a(in_app_store.iphone.opt.debug.arm64.o)
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in ios.a(in_app_store.iphone.opt.debug.arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**How to reproduce**
the build works fine in a blank projects with no scenes, produces error when added a scene

sorry i'm not familiar with iOS, xcode and can't get help from Q&A, discord and forums

### PR DESCRIPTION
**Pull request by naithar**
Fixes #18359 and should be fixing all other issues connected to missing symbols from iOS frameworks. 
Would probably fix issues connected to XCode Capabilities that gets enabled automatically by linking specific framework and not allowing to build a game in XCode without enabling them at developer portal for game's AppID.

Enabling `-fmodules` and `-fcxx-modules` for iOS platform code allows application to automatically link frameworks used in the code. Which also removes the need to specify required frameworks in XCode project and this in turn will remove auto-enabling of unwanted XCode Capabilities that could potentially block the build.
This way adding or removing Capability for exported game would not cause any issues for building a project.

Push Notifications Capability are additionally handled in entitlements file, so it's here too.

I've tested this fix by using newly built `.a` files in existing XCode project. This allowed too remove `In-App Purchase` without breaking the ability to build and run on device or simulator
I've also tested it by creating new XCode project from export template I've managed to create with this fixes. No capabilities were enabled, so it should be building without any issue for non-paid developer account.

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Comment by naithar** [comment]
Should I make same PR against `master` branch or it can be cherry-picked there?

**Comment by akien-mga** [comment]
A dedicated PR for `master` would be great, as we usually cherry-pick from `master` to `3.2` but not the other way around. Note that you'll need to install the Vulkan SDK on macOS to build the `master` branch for iOS.

**Comment by naithar** [comment]
Well, right now same as in #39624 iphone platform on `master` branch is pretty much unbuildable, but I'll make PR.

**Comment by bruvzg** [comment]
> Note that you'll need to install the Vulkan SDK on macOS to build the master branch for iOS.

iOS port to MVK is incomplete and won't build at all.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
