### PR TITLE
CSGPolygon add interpolation

### PR DESCRIPTION
**Pull request by stebulba**
This new feature come from my proposal:
Add Scaling/Modify a CSG Polygon in PathFollow when PathNode is drawing the mesh
godotengine/godot-proposals#1062
This pull request supersede #41499 where is now updated with the last PR.
3.x version is here --> #53462
This new pull request can interpolate in all CSGPolygon mode.

The interpolation work using a Curve who interpolate between two polygon array. If both polygons are equal, a single scaling mode is active.

interpolate_exemple_angle_symplify
If the polygon2 is empty, when you active the interpolation bool, you make a copy of the first polygon to the second. Is a way to reset or help you for editing the polygons.
No interpolation are happening if the curve is null and if the size of polygon2 is different of the polygon.

The interpolation make 3 styles of modification, like a scaling, moving or expanding.
Those video show how that work for depth mode, spin mode and path mode. All videos is in 5 fps.

Mode Depth :
Doesn't use the avantage of path_interval. The interpolation is straight up from point to point of the curve.

https://user-images.githubusercontent.com/26193340/135149868-f7e1d897-661f-4d4f-9fb4-38775ad79819.mp4

Mode Path :
In a expand mode, to modify when you modifie x axis only in polygon2, you can for exemple make larger a racing/road in some point of your race.

https://user-images.githubusercontent.com/26193340/135149999-d6d5793e-4998-46bf-a76d-460f5b29e541.mp4

Mode Spin :
In mode spin I add a new property " spin_fix_neg ". When interpolation is enable, that will reverse/remove faces if the curve is negative. I don't like to add this additional property, but it's a constraint in mode spin if the user want set a negative position in the interpolate_curve.

https://user-images.githubusercontent.com/26193340/135150035-2080356b-1811-44eb-946f-b52d9c9281ac.mp4

I am waiting the 3.x merge of #52509 before to pull request the version 3.x.
I need a revision for the documentation. English is not my first language.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @BastiaanOlij @jitspoe

**Comment by BastiaanOlij** [comment]
I need to find time to give this a run for its money and see if I agree with the way it's implemented but at face value this is really cool and powerful enhancement. I've put this on my todo list to give it a proper once over.

**Comment by jitspoe** [comment]
Of course I would rename the simplifiaction angle to "path_simplify_angle" and now it's being used for more than just that.  Wonder if it should be just "simplify_angle"?

I feel like "interpolation" is maybe not the best way to describe this.  Blender calls it a "profile" when you use a curve to define the bevel shape.  Wonder what the shape is called on things like crown moulding.

**Comment by stebulba** [comment]
Note to me:
Conflict invert_faces to flip_faces. #60838
To fix in same time interpolation to do_interpolate and fix soustraction -1 on spin.

**Comment by akien-mga** [comment]
This was auto-closed by GitHub, probably because you pushed a state with no mergeable change (e.g. `master` branch) to your fork's `csg_interpolation` branch. AFAIK it can't be reopened when that happens so you'll have to open a new PR.

**Comment by stebulba** [comment]
That will be easier, because I am stock with bugs.
icudt71l.dat still always recognized as modified.
Git include random other file too.
I use Git from ubuntu 16.04 lts. Maybe this version of Git is broke.

**Comment by Calinou** [comment]
> I use Git from ubuntu 16.04 lts. Maybe this version of Git is broke.

This is likely what's causing the "file is always recognized as modified" issue.

Ubuntu 16.04 is EOL, and Ubuntu 18.04 will be soon, so I recommend upgrading to Ubuntu 20.04 or later. In your case, you'll probably need to reinstall to upgrade, so you might as well install Ubuntu 22.04 and get 5 years of support this way.

**Comment by stebulba** [comment]
> Ubuntu 16.04 is end-of-life, and Ubuntu 18.04 will be soon, so I recommend upgrading to Ubuntu 20.04 or later
Sure, I am thinking about since long time. It's a big job, lot databases to migrate etc. I waited to buy a new computer, but the pression will force me to migrate before that.

**Pull request closed without merging**
