### PR TITLE
Adds occurrence auto completion

### LINKED ISSUE #21726: Autocomplete is inaccurate due to alphabetical sorting of suggestions
Basically this:
image
I wanted to autocomplete Vector3, but writing Vec3 suggests me PoolVector3Array. This happens when you write letters in different order (in example above I'm skipping "tor"). Autocomplete ignores how you started writing a word and sorts everything alphabetically. I'd expect it to actually select Vector3 in above case.

Another example:
image
Actually for this one writing "minf" would work, but still, autocomplete could better predict what I'd like to write. I doubt anyone would start RemoteTransform this way.

Tested in 3.1 alpha.

For comparison, here are VS Code results for these completions:
image
image
(btw, see how VS Code highlights actual written letters, rather than just the beginning of the suggested words like it is in Godot. But I suppose I could create separate issue for that)

### PR DESCRIPTION
**Pull request by AlexHolly**
more accurate auto completion for TextEdit contains informations about occurrences index for highlighting.

closes https://github.com/godotengine/godot/issues/21726

related https://github.com/godotengine/godot/pull/21181

please give it a good test @KoBeWi.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Nice! Seems to work good in most cases, although I'd probably need to use it for some time and see how it feels overall.

Minor thing, but I found a case where it doesn't work as expected:
image

**Comment by AlexHolly** [comment]
Ah nice, I will try to fix this. Currently it orders only by word length maybe it can be optimized by order of occurrence index.

**Comment by AlexHolly** [comment]
Is there a way to remove the casts?
https://github.com/godotengine/godot/pull/21742/files#diff-0e0c9dec15a95e1c0d8e658a4ab39d4cR455

Is there a better way to pass a variable to the sort function?
https://github.com/godotengine/godot/pull/21742/files#diff-71709879dd36a28d4ff43c570b3b4c8bR5771
https://github.com/godotengine/godot/pull/21742/files#diff-0e0c9dec15a95e1c0d8e658a4ab39d4cR445
https://github.com/godotengine/godot/pull/21742/files#diff-0e0c9dec15a95e1c0d8e658a4ab39d4cR453

Some Examples

peek 2018-09-05 15-21
peek 2018-09-05 15-32


peek 2018-09-05 15-19
peek 2018-09-05 15-20

peek 2018-09-05 15-28
peek 2018-09-05 15-29

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and release freeze for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

Note: If it's merged after 3.1-stable is released, this change might be considered for cherry-picking into a later 3.1.x release.

**Comment by akien-mga** [comment]
This would be good to review and hopefully merge first, to reduce the complexity of the huge #21181 which includes it.

Given the timing I don't think it will cut it for 3.2 though, see also https://github.com/godotengine/godot/pull/21181#issuecomment-538345482 about changes to the `TextEdit` API for editor-specific needs.

**Comment by aaronfranke** [comment]
@AlexHolly Has there been any progress in solving the above issues?

I'm also wondering if the `find_occurrences` code could be simplified. Perhaps it could be a simple wrapper around `find`, each iteration starting the search from after the last one's end position.

**Comment by AlexHolly** [comment]
I will wait until this is resolved.
> Maybe these changes should wait on the refactor described in #31739 so that it can be done with a better architecture. (https://github.com/godotengine/godot/pull/21181#issuecomment-538345482)

I like the split idea and will look into `find_occurrences` when it happens.
> I think this should probably be split into separate PRs with a better separation of concerns, so that the code completion experience can be improved gradually with well tested iterations. (https://github.com/godotengine/godot/pull/21181#issuecomment-538345482)

**Comment by aaronfranke** [comment]
Closing this PR for now, it can be re-opened (or re-created) after #31739 is solved.

**Pull request closed without merging**
