### PR TITLE
Sync C# vectors with Core

### PR DESCRIPTION
**Pull request by raulsntos**
- Remove `Vector2.Lerp` overload that takes a weight parameter of type `Vector2`.
- Remove `Vector3.Lerp` overload that takes a weight parameter of type `Vector3`.
- Remove `Color.Lerp` overload that takes a weight parameter of type `Color`.
- Remove `Angle` method from `Vector2i`.
- Remove `AngleTo` method from `Vector2i`.
- Remove `AngleToPoint` method from `Vector2i`.
- Remove `Cross` method from `Vector2i`.
- Remove `DistanceSquaredTo` method from `Vector2i` and `Vector3i`.
- Remove `DistanceTo` method from `Vector2i` and `Vector3i`.
- Remove `Dot` method from `Vector2i` and `Vector3i`.
- Remove `PosMod` method from `Vector2i` and `Vector3i`.
- Remove `Orthogonal` method from `Vector2i`.
- Remove `&` operator from `Vector2i` and `Vector3i`.

### CODE REVIEW

**Comment by Chaosus** [comment]
Instead of removing them, do you consider placing them in the extension classes?

**Comment by raulsntos** [comment]
I'd keep them if they were available in Core/GDScript, to me it feels weird to add additional C# API unless it uses C# features not available in GDScript such as generics.

Users are also able to add these extension methods themselves, or just convert to the floating vector types where most of these methods are available:

```csharp
var v = new Vector2i(4, 2);
float angle = ((Vector2)v).Angle();
```

Extension methods are one of the greatest strengths of C# in my opinion, I'd love to see users publish libraries to NuGet that extend Godot types and add functionality instead of relying on having everything implemented in Core.

Is there a particular method that you think we should keep?

**Comment by realkotob** [comment]
I support removing the diverging methods in this case due to the aforementioned reasons.

In some cases it makes sense to have additional methods, but when it doesn't I'd rather keep C# as close to core and the GDExtension system used by other languages as much as possible, otherwise it would cause confusion and a maintenance burden.

I'd highly advocate for making nuget packages with additional extension features when it makes sense, maybe even an official one.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Hromon** [comment]
The stupidest idea, I would understand, if it was about rendering, physics, sounds, or really something that is part of the core, and here are the AUXILIARY methods for VECTORS...
You have nothing to do and you add PR out of boredom?

**Comment by Hromon** [comment]
Instead of making life easier for developers, you make it harder...
And it's not easier to add these methods to Core/GDScript than to remove them altogether?...

**Comment by akien-mga** [comment]
@Hromon Please mind your language and keep your comments constructive. You can disagree with the change on technical grounds and you're welcome to expose those, but attacking contributors is never OK and a breach of our [Code of Conduct](https://godotengine.org/code-of-conduct/).

**Comment by Hromon** [comment]
> @Hromon Please mind your language and keep your comments constructive. You can disagree with the change on technical grounds and you're welcome to expose those, but attacking contributors is never OK and a breach of our [Code of Conduct](https://godotengine.org/code-of-conduct/).

Where did I offend the participant? I called the idea stupid, not the person...

**Pull request merged**
