### PR TITLE
Codestyle changes for `Control` class

### PR DESCRIPTION
**Pull request by Xrayez**
Removed dead code, fixed comments style to use sentence case, no extra empty lines.

Renamed incorrect "hint" variable names to "usage" in `_get_property_list()`, as "hint" implies one of the `PROPERTY_HINT_*` values, which is not the case here.

### CODE REVIEW

**Comment by pycbouh** [comment]
Some empty lines are there for clarity when reading code. I wouldn't remove most of them, as I don't think they breaking any code style rules.

**Comment by Xrayez** [comment]
> Some empty lines are there for clarity when reading code. I wouldn't remove most of them, as I don't think they breaking any code style rules.

Please review or elaborate on which ones.

**Comment by pycbouh** [comment]
I don't think that individually reviewing a hundred of empty line removals is going to be productive. I'm also not sure what was the basis for those changes, because a lot of similar lines in these files were not touched by this PR. So I would propose not touching any, unless removing it improves understanding of the code.

**Comment by Xrayez** [comment]
These changes make the existing code style consistent with the rest of the code, so I'd still like to receive a review from you.

**Comment by KoBeWi** [comment]
Here's a list of lines that I think shouldn't be removed (I used red numbers from diff as reference):
```
Control.cpp
222
291
308
524
528
534
544
578
590
685
707
717
730
781
789
823
871
900
942
958
987
1015
1070
1095
1120
1145
1170
1195
1208
1242 (you could remove 1245 instead)
1257
1271
1286
1311
1703
1728
1783
1795
1807
1832
1841
1850
1884
1890
1939
1947
1959
1987
1991
2036
2043
2047
2083
2104
2116
2125
2144
2148
2168
2281 (maybe remove 2284 instead)
2311
2323
2358
2379
2414
2450
2454
2458 (remove 2460 instead)
2702
```
```
Control.h
55
61
67
76
82
103
122
129
136
143
164
```
Basically, any chunk of related code, especially code blocks, should be left separated. I didn't check the surrounding code though, you might need to *add* some lines for better consistency.

**Comment by Xrayez** [comment]
Yeah I agree, I think there's not much point in those changes, and perhaps it may be just me who prefers this particular style. Especially when #48688 was the real motivation behind those changes, I think I'll just avoid doing any codestyle changes because they're not documented at the moment: godotengine/godot-docs#4685.

Thanks for the work and constructive criticism, and not destructive criticism.

**Comment by KoBeWi** [comment]
But the other changes than I listed were ok 🙃

**Pull request closed without merging**
