### PR TITLE
Fix error in the console: `double free or corruption (!prev)` at exit of GDnative C++ application

### LINKED ISSUE #47607: double free or corruption (!prev) error on exit (GDNative c++)
**Godot version:**
Godot Engine v3.3.rc7.official

**OS/device including version:**
Linux Ubuntu 20.04

**Issue description:**
GDnative C++ application runs fine, but throws error in console: `double free or corruption (!prev)` on normal application exit.
Not visible when run from editor.

**Steps to reproduce:**
Any GDnative C++ project, start and exit.

**Minimal reproduction project:**
Any project, like this one https://github.com/BastiaanOlij/gdnative_cpp_example
Error happens somewhere after `Godot::gdnative_terminate(o);`

### PR DESCRIPTION
**Pull request by Bromeon**
Should resolve #47607.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Bromeon** [comment]
Would be great to get feedback from @sash-rc who reported the issue, or someone else who can test with the C++ binding 🙂

**Comment by Bromeon** [comment]
@sash-rc confirmed the fix works for him on the `3.x` branch.
We haven't had anyone test this on `master` directly, but it's probably OK, as the [`3.x` changes](https://github.com/godotengine/godot/compare/3.x...Bromeon:bugfix/gdnative-cleanup-3.x) match the ones in this PR.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Comment by BastiaanOlij** [comment]
Sorry for the late response here but I think we introduced a new issue here again. We're only supposed to clean the library up inside of this condition:
```
if (G && G->get()->get_library()->is_reloadable()) {
```

If the library is not reloadable (like with VR plugins) then when this logic triggers we clean up all the meta data but leave the library loaded. As soon as a new object is constructed the meta data is missing and the application will break.
I should have caught this in the previous PR

**Pull request merged**
