### PR TITLE
Fix autocompletion inserts an extra quotation

### LINKED ISSUE #70535: Autocompletion for string arguments adds extra quote (`'` or `"`) at the end of the string
### Godot version

4.0 beta 10

### System information

Windows 11

### Issue description

On the text editor when using autocomplete on function arguments that receive Input Map names after autocompleting the function name, the string autocompleted appears with an extra " at the end.
This doesnt happen if you write " and then accept the Input name in the dropdown

### Steps to reproduce

- On the script editor
- Start writing `Input.get_vector` but when the dropdown appears with the autocomplete suggestion for `Input.get_vector` press enter to accept it, then press enter again to accept the Input map suggestion
- The autocompleted input name should have an extra "

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by heppocogne**
This commit fixes #70535 and #70692 (duplicated issues).

https://user-images.githubusercontent.com/83043568/209918556-5729fd7c-49d4-4147-9a9c-dfc73444fc51.mp4

### CODE REVIEW

**Comment by Chaosus** [comment]
Need to fix these tests:

```
./tests/scene/test_code_edit.h:2933: ERROR: CHECK( code_edit->get_line(0) == "\"\"test\"\"" ) is NOT correct!
  values: CHECK( ""test" == ""test"" )

./tests/scene/test_code_edit.h:2934: ERROR: CHECK( code_edit->get_caret_column() == 7 ) is NOT correct!
  values: CHECK( 6 == 7 )
```

**Comment by heppocogne** [comment]
OK, I think it's fixed.
(`""test""` or `""test"` cause syntax errors, why do these tests expect such results ...?)

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Please don't hardcode characters if possible, also any chance you can add some unit tests for this case?

**Comment by akien-mga** [comment]
Superseded by #71402.

**Pull request closed without merging**
