### PR TITLE
Removed redundant assignment of `blur_pipeline`

### LINKED ISSUE #50852: Redundant assignment of `blur_pipeline`
### Godot version

4.0 2a8a59e

### Issue description

https://github.com/godotengine/godot/blob/2a8a59eac0f1bbec83d4d04cac9f428487a0d738/servers/rendering/renderer_rd/effects_rd.cpp#L1353-L1355

### PR DESCRIPTION
**Pull request by vitika9**
I am new,if I made any mistakes let me know :)

<i>Bugsquad edit:</i> Fix #50852.

### CODE REVIEW

**Comment by akien-mga** [comment]
There are code style issues, you used spaces for indentation instead of tabs, and your `else` brace style does not follow the code style used in surrounding code and the whole codebase.

See [Code style guidelines](https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html) for details.

**Comment by Vitika9** [comment]
@akien-mga thankyou very much

**Review by Calinou — APPROVED** [review]
Thanks! Congratulations for your first merged pull request :tada:

**Comment by Vitika9** [comment]
> Thanks! Congratulations for your first merged pull request :tada: 

Thanks for the support 😊

**Pull request merged**
