### PR TITLE
[Input] Release keys/actions pressed if window loses focus

### LINKED ISSUE #7297: Input actions don't update pressed states after OS window adjustment
Operating system: Windows 8.1(64)
Godot version: Godot_v2.1.1-stable_win64
Issue description: 
Input actions don't update pressed states after OS window adjustment. This may create an input saying its pressed even though you released it outside of the game.

Steps to reproduce:
1.) press and hold an action
2.) adjust OS window and release action 

Video of me doing it:
[https://youtu.be/3bZuJVrmGJw](https://youtu.be/3bZuJVrmGJw)

### LINKED ISSUE #18785: No key release event if window loses focus (Input.is_action_pressed)
**Godot version:**

3.0.2

**OS/device including version:**

Ubuntu Linux

**Issue description:**

Input.is_action_pressed continues to return true if window loses focus before key is released. It continues to trigger even when the game regains focus.

**Steps to reproduce:**
check Input.is_action_pressed() in a loop (like _physics_process). Start pressing the key, then click another window to cause the game to lose focus. Input.is_action_pressed() continues to return true, even when returning to the game window. You must press the key again to fix it.

**Minimal reproduction project:**

[input_action_bug_test.zip](https://github.com/godotengine/godot/files/1994082/input_action_bug_test.zip)

### LINKED ISSUE #19137: Persistent Input key pressed Bug/Glitch
**Godot version:**
3.0.2

**OS/device including version:**
Windows 7 x64 RX 470

**Issue description:**
Input is Stuck

**Steps to reproduce:**
Greetings everyone, I would just like to share that I've notice some bug and there are 3 ways to reproduce this issue. For example if you are player and is moving using move_and_slide or position movement.

If Godot or your computer freezes or hangs for a bit, the input is stuck and is being read as key pressed. Another way to reproduce this is when you drag around the window of running godot game while moving(which makes it stutter), the Input also ends up stuck. Lastly, the easiest way to reproduce this issue is when you rapidly press shift+key (which enables sticky key for windows), The input key pressed ends up stuck.

Also, just wanted to follow up, there are cases that when if godot stutters/hangs, it seems to skip some frames/cycles of the code and causes inaccurate calculation which I'm not sure if its normal.

### LINKED ISSUE #22265: Need to press F5/F6 twice on 3.x in release_debug
I see this #19576 closed, i open new one because bug not fixed.

**Godot version:**
All 3.x,  master 0de6514

**OS/device including version:**
Xubuntu 16.04.5 LTS, Nvidia GTX 750 Ti
Tested 3.x on Windows 7 on the same machine and it works.
I think is only affected x11.

**Issue description:**
Sometimes need to press F5 or F6 twice to run the project or scene with Godot 3.x.

**Steps to reproduce:**
1) Open scene.
2) Press F6 button and hold it and release after scene is run. 
3) Close windows and press F6.
4) Scene is not play, need press F6 twice.
5) Try several times it's difficult to reproduce.
 
On my machine this happens randomly not necessary to hold F6 button.

**Minimal reproduction project:**
Simple project with one 2DNode for version 3.1.
[f6.zip](https://github.com/godotengine/godot/files/2398814/f6.zip)

After compare 2.1 version with 3.x, i found what cause this behaviour on my machine.
https://github.com/godotengine/godot/blob/e20a28a7db090dbf39bc8c90487c3d7beb84cbb8/main/input_default.cpp#L266-L272

Sometimes keys_pressed.erase not reached, then **last_is_pressed == true**, and **k->set_echo(true)**
Because **BaseButton::_unhandled_input** verify if not **is_echo()**, scene not run, while key not pressed twice.. 
**New code from 3.x:**
https://github.com/godotengine/godot/blob/e20a28a7db090dbf39bc8c90487c3d7beb84cbb8/platform/x11/os_x11.cpp#L1684-L1694

### LINKED ISSUE #28440: actions are buffered when window looses focus
**Godot version:**
3.1 stable

**OS/device including version:**
tested on Win and Linux.

**Issue description:**
When an action is triggered and held within a _process function and the game window looses focus, the action is buffered and still active. 
Even after the window gains focus again, and no actual input occurs, the action is still "true".

**Steps to reproduce:**
1. open and run the sample project.
2. press and hold one of the arrow keys -> the label displays which butons are pressed and a counter increases.
3. click outside of the window so the window looses focus.
--> the counter still increases and the action is still active.

**Minimal reproduction project:**

[action_window_focus.zip](https://github.com/godotengine/godot/files/3120234/action_window_focus.zip)

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #7297
Fix #18785
Fix #19137
Probably Fix #22265
Fix #28440

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @godotengine/macos and @godotengine/uwp.

**Comment by homer666** [comment]
How will this affect gamepads? Godot can read their inputs when out of focus so that issue doesn't apply there, yet this PR seems to clear all input events regardless of where they came from.

**Comment by bruvzg** [comment]
On macOS behaviour is following:

- Key is released after window lose focus: Release `_input` event is received and action pressed status changes when key is release not on focus loss.

- Key is released while resizing window: Release `_input` event is received and action pressed status changes after resizing is finished.

- Key is released while moving window: `_input` event is NOT received, and action status does NOT change.


Adding `input->release_pressed_events();` from this PR to macOS `NOTIFICATION_WM_FOCUS_OUT` notifications doesn't change this behaviour in any way.

Following patch "fixes" moving window behaviour (action become unpressed instantly, regardless of actual key status):

```diff
diff --git a/platform/osx/os_osx.mm b/platform/osx/os_osx.mm
index 4bbe30a7d..c83983a40 100644
--- a/platform/osx/os_osx.mm
+++ b/platform/osx/os_osx.mm
@@ -337,6 +337,10 @@ static CVReturn DisplayLinkCallback(CVDisplayLinkRef displayLink, const CVTimeSt
 }
 
 - (void)windowDidMove:(NSNotification *)notification {
+
+	if (OS_OSX::singleton->get_main_loop()) {
+		OS_OSX::singleton->input->release_pressed_events();
+	}
 	/*
 	[window->nsgl.context update];
```

Original issue mention similar moving window problem on window as well, so maybe additional `release_pressed_events` call in Windows move callback/message is requirerd (I have not tested in on Windows).

**Comment by guilhermefelipecgs** [comment]
@homer666 Gamepads also will be stopped, but can be activated again if a new event is triggered (even out of focus).

**Comment by allkhor** [comment]
Relevant PR #24176?

**Comment by guilhermefelipecgs** [comment]
@allkhor Yeah, it's basically the same fix :)
@akien-mga Feel free to close my PR.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
So @reduz approved this PR but previously was against #24176, which is quite similar. It's normal procedure with reduz to get a 2-step approval :P

But I guess that means @guilhermefelipecgs and @marcelofg55 should cross-review each other's PR and see what should be merged exactly.

**Comment by guilhermefelipecgs** [comment]
Well, the only difference I see is that I didn't clear this variables:
https://github.com/godotengine/godot/blob/2ca36cce9a4a64e76bb8418adb0fbf1d74cdd5ee/main/input_default.cpp#L592-L593

I guess @reduz approved my PR because my changes are platform specific, so, I can merge the changes from @marcelofg55 into my PR if wanted.

**Comment by guilhermefelipecgs** [comment]
And tonight I can test in windows to ensure the changes it's working well.

**Comment by guilhermefelipecgs** [comment]
Changes from @marcelofg55 merged.
Windows tested and now it's working.

@akien-mga Now it's up to you. Maybe UWP still has this problem, but I don't know uwp works.

**Comment by KoBeWi** [comment]
Another related issue: #18785

**Comment by avencherus** [comment]
Also just saw this one:  https://github.com/godotengine/godot/issues/28440

**Comment by guilhermefelipecgs** [comment]
Added `flush_accumulated_events()` in `release_pressed_events` to fix #28440.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
