### PR TITLE
Fix error when dropping image onto the scene dock

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes a regression described in https://github.com/godotengine/godot/pull/92004#issuecomment-2134836842.

Dropping files onto the scene dock has 3 situations:

1. Any single resource file: Set type-matching property of that node.
2. One or more scene files: Instantiate the scene.
3. One or more audio files: Create an AudioStreamPlayer.

#92004 first tries to do the property drop (1 above). 2 and 3 will be tried if the resource file does not have any matching property, so that audio stream players are easier to create. But I did not check the "single file, not audio stream" situation, thus the error message.

CC @patwork

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by patwork** [comment]
@timothyqiu hi, just tested in 4.3.beta1 and now I cannot drop any image into scene tree (can drop them into editor window). 

```cpp
	if (ClassDB::is_parent_class(res_type, "PackedScene")) {
		_perform_instantiate_scenes(p_files, node, to_pos);
	} else if (ClassDB::is_parent_class(res_type, "AudioStream")) {
		_perform_create_audio_stream_players(p_files, node, to_pos);
	}
```

I guess images are not type "PackedScene"?

**Comment by timothyqiu** [comment]
> just tested in 4.3.beta1 and now I cannot drop any image into scene tree

You can't create nodes by drop images there in previous versions either.

**Comment by patwork** [comment]
Oh indeed, I'm so sorry, I was convinced that dropping in a scene tree would work the same way. :sweat::sweat::sweat:

**Pull request merged**
