### PR TITLE
Made 'draw relationship lines' (at Editor Settings) enabled by default.

### PR DESCRIPTION
**Pull request by CakHuri**

### CODE REVIEW

**Comment by groud** [comment]
Please don't, most people don't use them.

**Comment by CakHuri** [comment]
I found it more beginner friendly. Also, if I remembered, any tutor on youtube, have it enabled (though I'm not sure which one. It was sometime ago).

**Comment by YeldhamDev** [comment]
While this decision should be discussed, I do agree that with it being more beginner friendly, and generally helpful in scenes with lots of nodes.

**Comment by akien-mga** [comment]
Posting screenshots for comparison, please upvote (:+1:) the one you prefer as default.

No relationship lines (current default):
screenshot_20181025_173329

**Comment by akien-mga** [comment]
With relationship lines (default if this PR is merged):
screenshot_20181025_173415

**Comment by QbieShay** [comment]
I find the one with the lines more accessible for people with cognitive disturbs :)

**Comment by capnm** [comment]
> With relationship lines (default if this PR is merged)

I think then you don't need the the truncated boundary lines.

image

**Comment by eon-s** [comment]
I also agree that separators may not be needed if showing tree lines, or make separators even more dim.

**Comment by akien-mga** [comment]
The votes here and on https://twitter.com/Akien/status/1055485073846345728 have spoken, default it will be :)

As suggested here and on Twitter, it would indeed make sense to hide the horizontal separators when relationship lines are enabled.

**Comment by CakHuri** [comment]
Oh, I missed this one...


_"Deleting the branch now..."_

**Pull request merged**
