### PR TITLE
Single window mode is not lost after starting a project from the project manager

### LINKED ISSUE #42034: Single window mode is lost after starting a project from the project manager
**Godot version:**
Master f19c400bedf3f975e2e31cfabaaec9446461c68a

**OS/device including version:**
Windows 10

**Issue description:**
When starting the editor with `--single-window` command line argument and loading a project, single window mode is not applied anymore. It works properly when loading a project directly from the command line.

**Steps to reproduce:**
- Start godot with `--single-window` without loading a project directly
- Load any project from the project manager
- Observe the editor is using multi windows mode

**Minimal reproduction project:**
n/a

### PR DESCRIPTION
**Pull request by jak6jak**
Ran into so weird git stuff with rebasing got some help and they said to try a new pull request.  Previous pull request: https://github.com/godotengine/godot/pull/42071
This means you can start Godot with --single-window and it passes it through the project manager.

*Bugsquad edit:* Fixes #42034.

### CODE REVIEW

**Review by pouleyKetchoupp — APPROVED** [review]

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Seems good, but it will need to be rebased

**Comment by akien-mga** [comment]
Personally I'm not fond of keeping adding more hacks to `OS` to transfer things from project manager to editor or runtime. I know that there's no convenient other way currently so this PR is correct, but I just wanted to point out that we're bloating `OS` and `main` with stuff which shouldn't need to be there.

The proper approach would be to fully pass the config to each instance as a struct, similar to what #49362 is implementing, but this will likely be merged only after 4.0. So we can go with yet another workaround in the meantime...

**Comment by akien-mga** [comment]
Force pushed a rebase so that it can be merged.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
