### PR TITLE
Godot3 Exporter now converts .fnt to .font

### PR DESCRIPTION
**Pull request by marcelofg55**

### CODE REVIEW

**Comment by akien-mga** [comment]
Does the renamed .font files work in 3.0? I had implemented this locally but my .font files were seen as broken.

**Comment by marcelofg55** [comment]
Yes, I've only tested it with one project but it worked fine when I loaded it in 3.0.

**Comment by stubbsy345** [comment]
Has this update been merged with the master branch? Thanks

**Comment by Noshyaar** [comment]
This is not applicable in master branch as it is an update to 'Godot 2 to Godot 3' converter.

**Comment by stubbsy345** [comment]
But is the convertor not part of 2.1.3 and 2.1.4?

**Comment by Noshyaar** [comment]
master branch: 3.0
2.1 branch: 2.1.4

**Comment by stubbsy345** [comment]
Oh my confusion, sorry. Thanks

**Pull request merged**
