### PR TITLE
Fix some issues with instanced scenes

### PR DESCRIPTION
**Pull request by hoelzl**
There are some issues with instanced subscenes that have been reported for Godot 2.1, e.g., #12765 and #12139, and that seem to be present in current master as well.

To reproduce some of them with the attached project:

- Open scene `Rectangles-Duplicate-01.tscn`.
- Move `ColorRect3` between the other two color rectangles in the scene tree, so that the colors are yellow, blue, red.
- Save the scene. Close it and reopen it. The blue rectangle is again on the bottom of the list (i.e., yellow, red, blue).
- Move `ColorRect3` back into the middle position. Run the scene. The colors in the executable are yellow, red, blue.

- Duplicate the `VBoxContainer` node. The blue color rectangle disappears from the copy.

- Make an instanced node editable, perform changes, turn edit mode back off, save the scene. All changes made to the node disappear. Arguably this might be the intended behavior, but since there is no feedback about this in the editor (the changes remain until the scene is reloaded) and since the editable status itself behaves in some unexpected ways (e.g., since the editable nodes are stored with their node paths, renaming an editable node turns editing mode off), this behavior seems rather unfriendly to users.

The revised pull requests fixes the first two issues for my use cases, but not the last one.

<del>It's still very rough, and the patch currently greatly increases the size of the scene files because I'm saving way too many nodes. This could be fixed with some more work. But I'd be happy to talk to someone more familiar with the Godot codebase whether there is a better way to address the problem, since the solution in the PR seems rather heavy handed to me.</del>

[InstancingBugs.zip](https://github.com/godotengine/godot/files/1542504/InstancingBugs.zip)

### CODE REVIEW

**Comment by reduz** [comment]
Honestly, I think fixing this is worth it only if the fix is only a couple lines at much, otherwise adding a lot of complexity for an use case that is extremely rare is undesired. An alternative could be for the editor to simply not allow you to put custom nodes in the middle.

**Comment by reduz** [comment]
Still, why not simply save the position of the node? not quite sure why the solution needs to be so complex.

**Comment by hoelzl** [comment]
Thank you for your comments.

I'm not so sure whether this is so rare as use case. For example, I have quite a few reusable scenes for the UI of a game I'm currently developing, and it's pretty useful to be able to customize them with additional components that you place inside the existing HBoxes/VBoxes. But perhaps that's just me abusing node instancing.

I actually started out saving the positions of the nodes, but then dealing with reordered instanced nodes became slightly tricky. But since the name-based approach became more complicated than I wanted as well, I should probably try that again.

**Comment by reduz** [comment]
well, i mean rare as in, we didn't really get much complaint about it. I'm fine with fixing and your use case makes sense,  but I'm sure there has to be a simpler way as it's pretty much just saving an extra index for nodes in this situation

**Comment by hoelzl** [comment]
OK, when it's acceptable to ignore reordering of instanced nodes it is not so difficult to get a relatively simple fix for duplication. In that case, recreating the order takes just two lines of code, the rest of the commit handles picking up user-created nodes that are not immediate children of the root.

For packed scenes I guess the way to go would be to add an `index` field to `NodeData` and to use that to move the nodes to the correct position when inserting them. This would probably cover the most frequent cases without introducing a lot of complexity.

**Comment by reduz** [comment]
yeah if the base scene is reordered, I think it's expected that instances will not automatically fix

**Comment by reduz** [comment]
haven't checked much, but is there any reason why position needs to be moved after the node is added? as it's in order and the original scene is loaded beforehand, i would think that moving it right ater adding it might work the same

**Comment by hoelzl** [comment]
In `_duplicate()`, each `move_child()` follows immediately after its corresponding `add_child()` (in line 2211 for the add in 2209, and in line 2236 for 2231). and they implicitly make use of the fact that the children are added in order and the instanced nodes are already present.

The first add/move combination is for immediate children of `node`, the second is for non-instanced children of instanced nodes that are not immediately below `node`, so only one add/move pair should be executed per node.

**Comment by akien-mga** [comment]
@reduz says the PR seems perfect now, but it needs a rebase to fix merge conflicts.

**Comment by hoelzl** [comment]
Rebased on current master. 

Thank you @akien-mga and @reduz for the repeated feedback on this PR and the time and effort you invest into PRs in general.

**Comment by brainsick** [comment]
This looks like it adds a get_node_index method to the public API.

@hoelzl Would you be willing to add some documentation for that?  It would help us engine users.  :)

**Comment by reduz** [comment]
This broke binary compatibility with existing scenes, sorry I should have realized it sooner.

**Comment by reduz** [comment]
Fixing on my own so i don't have to revert

**Comment by volzhs** [comment]
yeah. this breaks compatibility. I needed to reimport all assets to work again...

**Comment by hoelzl** [comment]
@brainsick Yes, I can add documentation, but will wait for @reduz' s changes to see whether `get_node_index` remains in its current form.

**Comment by reduz** [comment]
@volzhs don't reimport, as the resulting reimport will be broken, i just commited a fix

**Comment by reduz** [comment]
@hoelzl i didn't change the API, only how it's encoded

**Comment by volzhs** [comment]
@reduz sadly... I didn't notice this problem. I already did. :cry: 
need to try again now...

**Comment by brainsick** [comment]
@hoelzl Thank you!  I felt silly even asking as it seems so obvious what it does given the context, but it's a discover-ability issue for me and users who rely on the documentation.

**Pull request merged**
