### PR TITLE
Remove unused FileAccessBuffered

### PR DESCRIPTION
**Pull request by Faless**
This seem to be a leftover from the very early (per-open source) age. All blames to the offending lines (commented and not) trace back to the first commit.

This PR:
- No longer uses `FileAccessBufferedFA` on HTML5 (it's not needed, and actually caused bugs with the interactive loaders)
- Removes all commented references to `FileAccessBufferedFA` and delete it along with `FileAccessBuffered`.
- Also remove the only active reference to `FileAccessBufferedFA` which is situated in an unreachable path according to my findings (and again, I suspect `FileAccessBufferedFA` is just bugged).

NOTE:  `USE_JAVA_FILE_ACCESS` does not seem to ever be defined in the build system, this suggests that there is also a bug on android, when APK expansion is enabled since `FileAccessJAndroid` is used in that case (by `DirAccessJAndroid`) but never set up (so calling `exists` should call a null pointer). Which might be related to #37695 .
  See https://github.com/Faless/godot/commit/a00fbb2a765abf1f9fae3da0209141fd27f770ed not included in this PR, and https://github.com/Faless/godot/commit/a00fbb2a765abf1f9fae3da0209141fd27f770ed#r44872072 (@m4gr3d you might have an answer to that question).

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]
@Faless I've also responded to https://github.com/Faless/godot/commit/a00fbb2a765abf1f9fae3da0209141fd27f770ed#r44872072. Feel free to include those changes in this PR as well.

**Comment by akien-mga** [comment]
I'll merge this one as is, @Faless can then make a follow-up PR for the Android changes.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
