### PR TITLE
Fix DNS resolve mutex locks

### LINKED ISSUE #49261: Subsequent requests in `HTTPRequest` don't resolve after #49026
**Godot version:**

`master` @ https://github.com/godotengine/godot/commit/9990f28d8414e27843eb0626fbf7f0277e6c9130

**OS/device including version:**

Windows 10

**Issue description:**

#49026 breaks file downloading (e.g. export templates downloading in the editor). The download stops at an unassuming status `STATUS_DISCONNECTED`:

image

If `use_threads` is disabled, the status changes to `STATUS_RESOLVING`, but it still stops at that and never downloads anything.

image

Code that doesn't work:
```cpp
	download_templates->set_download_file(EditorPaths::get_singleton()->get_cache_dir().plus_file("tmp_templates.tpz"));
	download_templates->set_use_threads(true);

	Error err = download_templates->request(p_url);
```

But requests like this do work:
```cpp
	request_mirror->request("https://godotengine.org/mirrorlist/" + p_version + ".json");
```

**Steps to reproduce:**
Build `master` from https://github.com/godotengine/godot/commit/9990f28d8414e27843eb0626fbf7f0277e6c9130 with `version.py` set to a valid stable release, then try to download export templates from the editor. Mirror list is successfully fetched, but file download hangs as described above.

**Minimal reproduction project:**

Not applicable.

### PR DESCRIPTION
**Pull request by sarchar**
This fixes #49261, which was happening because of a deadlock in the resolver mutex.  There was leftover old mutex code and it's all be converted to new MutexLock class now.

### CODE REVIEW

**Comment by akien-mga** [comment]
There's still three more calls to `unlock()` in early returns, shouldn't they be removed?

**Comment by sarchar** [comment]
> There's still three more calls to `unlock()` in early returns, shouldn't they be removed?

Yeah, I think they probably should be, but they were in the code before my original PR and so I was skeptical to touch them in case someone else added them for some actual purpose.

Should I remove them too?  They seem to all be in error condition branches that probably never get hit, which is why they've not been a problem.

**Comment by akien-mga** [comment]
Right, this might need checking by @RandomShaper who implemented the `Mutex` changes in 18fbdbb456c. In this commit he removed most `->unlock()` calls but he kept two of them as `.unlock()`, and then your PR added a third one following the same pattern.

**Comment by sarchar** [comment]
> Right, this might need checking by @RandomShaper who implemented the `Mutex` changes in [18fbdbb](https://github.com/godotengine/godot/commit/18fbdbb456c07a56b358bea2e392765fbcbb3283). In this commit he removed most `->unlock()` calls but he kept two of them as `.unlock()`, and then your PR added a third one following the same pattern.

OK, so wait and see what @RandomShaper says.  I can easily remove them if he says they're not needed.

**Review by RandomShaper — CHANGES_REQUESTED** [review]
Indeed, I took things out of balance by adding the RAII (`MutexLock`) style and forgetting to remove some of the explicit unlocks.

By the way, this PR makes the same mistake. 😃 Please remove the explicit unlocks inside the `if`s where you have switched to the scoped lock style, and please do so also in `get_resolve_item_status()`, where I forgot myself.

Furthermore, I don't think it will actually impact performance, but it's even better to enclose each `MutexLock` declaration along with the code it protects in a scope so the lock is released earlier instead of at the end of the function. I don't know if the original intent of the code regarding the early-unlock was optimization or just to avoid writing the unlock call many times, but, in any case, it won't harm.

**UPDATE:** To elaborate, I didn't have a strong reason to keep the explicit lock/unlock or fully switch to the scoped style. I just decided on a per case basis judging which would be more readable, but now I think it's better to use `MutexLock` everywhere, at least in this class, for consistency.

**Comment by sarchar** [comment]
> By the way, this PR makes the same mistake. 😃 Please remove the explicit unlocks inside the `if`s where you have switched to the scoped lock style, and please do so also in `get_resolve_item_status()`, where I forgot myself.

In that case, I'll remove the extra unlock() calls and push an update in 10 minutes.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
