### PR TITLE
Add way to look for templates at system wide level too

### LINKED ISSUE #1026: Godot should look for export template at system-wide level too
that's all :)

### PR DESCRIPTION
**Pull request by est31**
Useful for everybody wanting to package godot.
Fixes #1026.

-> Retain the old behaviour: path in error msg only when exporting.
-> User templates override system templates

### CODE REVIEW

**Comment by est31** [comment]
Note: I haven't tested anything but the linux tools + linux export templates combination.

**Comment by reduz** [comment]
This is interesting, I was thinking of adding not only export templates but
game templates to godot for 2.1 so it would be interesting to eventually
make this option a little more universal.

I would also like something like this for OSX and Windows, (OSX inside the
.app and Windows inside the Program Files folder -or inside a self
contained folder-), so we can eventually provide a better downloadable
package that can be installed and be ready to go.

**Comment by est31** [comment]
About the extra features for OSX and Windows, this PR unifies export the template path config into the `EditorExportPlatform::find_export_template` method, so one can easily add OS-custom changes here. Before, one would have had to change it for every single exported platform (as I did in my PR). So such changes will be easier.
But I guess it should be implemented by somebody who can also test it, because I neither have windows nor OSX.

Or is there a platform independent method in godot's code to determine the path to the executable? This can be then used to look for the templates inside some path relative to the executable.

**Comment by reduz** [comment]
I would add to what you did something like

virtual String OS::get_install_path() const;

that can be overriden by OS, and change the option you added to work in
OS_Unix and rename it to "unix_install_path", since it will only be useful
for that.

**Comment by est31** [comment]
Its less an install path, on unix stuff goes to multiple different places.
What about:

virtual String OS::get_global_settings_path() const;

**Comment by est31** [comment]
I think I'll go with "unix_global_settings_path" and OS::get_global_templates_path().

**Comment by reduz** [comment]
the rationale is that global settings path is more of an unix thing, but on
Windows and OSX it's an install location, example:

Program Files\Godot Engine

and you can have multiple versions of Godot installed, so it's not really a
global setting but an install location. On Unix this is more rare and stuff
is really
installed globally and system wide

**Comment by est31** [comment]
okay, OS::get_install_templates_path() then?

**Comment by reduz** [comment]
okay!

**Comment by akien-mga** [comment]
Good to merge for me if you're fine with the implementation @reduz.

**Comment by akien-mga** [comment]
Documented by @est31 in https://github.com/godotengine/godot-docs/pull/10

**Pull request merged**
