### PR TITLE
Fix Skeleton3DEditor crash

### LINKED ISSUE #65273: Skeleton3DEditor cause crash
### Godot version

4.0.dev (654a31df062b58b3b534e790b2b4a4cc0762f6a4)

### System information

Win10

### Issue description

When showing Skeleton3DEditor, it crash Godot. This regression caused by #65250.

### Steps to reproduce

Select Skeleton3D in TreeDock.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Rindbee**
Fix #65273.

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
I don't see how any of this could cause a crash or how it is related to the theme owner changes, but the change here makes sense from the code quality standpoint and if it helps with other issues, then good.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Rindbee** [comment]
Now the first `NOTIFICATION_THEME_CHANGED` will happen before `NOTIFICATION_ENTER_TREE`, and editors have not yet been created (by `create_editors`).

**Comment by Rindbee** [comment]
The key point is that it is notified in inheritance order: 
https://github.com/godotengine/godot/blob/b8977ca333fd0334669de0253f86abf6d401256a/core/object/object.h#L833

https://github.com/godotengine/godot/blob/b8977ca333fd0334669de0253f86abf6d401256a/core/object/object.cpp#L789-L790

https://github.com/godotengine/godot/blob/b8977ca333fd0334669de0253f86abf6d401256a/core/object/object.h#L513-L523

**Comment by YuriSizov** [comment]
Yes, of course. Thanks. I was just not sure why that would be a problem if it worked fine way before any changes we've made. The `NOTIFICATION_THEME_CHANGED` should've been sent early back then as well. But oh well, the code is better right now anyway. Thanks again for your work!

**Comment by Rindbee** [comment]
Before, `NOTIFICATION_THEME_CHANGED` was delayed notification at the end of `NOTIFICATION_ENTER_TREE`, but now, it is not delayed in `Control`, and it is still delayed in `Window`.

**Comment by YuriSizov** [comment]
No-no, it became a deferred call with Aaron's changes. But before Aaron's changes it wasn't delayed, it was run at the end of `NOTIFICATION_ENTER_TREE`. But only under some conditions. Guess they weren't met.

>  it is still delayed in Window.

Oops, that's actually a bug on my part.

**Pull request merged**
