### PR TITLE
[macOS] Add null checks for `NSString stringWithUTF8String`.

### LINKED ISSUE #88686: `+[NSString stringWithUTF8String:]: NULL cString` is printed on every engine startup
### Tested versions

- Reproducible in: 4.3.dev https://github.com/godotengine/godot/commit/b15105a3585c29c8448f3d2dc8fe20a578a2b41b, 4.2.1.stable, 4.1.3.stable, 4.0.4.stable

### System information

macOS Ventura 13.4.1 - Apple M1 Mac mini 2020

### Issue description

A debug message is printed before every startup of the editor or project, even if `--quiet` is specified:

```
$ godot
2024-02-22 22:22:48.779 godot[1442:13781] *** +[NSString stringWithUTF8String:]: NULL cString
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
OpenGL API 4.1 Metal - 83.1 - Compatibility - Using Device: Apple - Apple M1
```

This only occurs on macOS.

### Steps to reproduce

- Start Godot from a terminal (whether it's inside an .app bundle or not, this occurs regardless).

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Should fix https://github.com/godotengine/godot/issues/88686 (but I can't reproduce it to test).

### CODE REVIEW

**Comment by Calinou** [comment]
Strangely, I can't reproduce the original issue with self-compiled builds even if I move them to `macos_tools.app/Contents/MacOS/Godot`. Therefore, I don't know if this actually resolves the issue.

**Comment by stuartcarnie** [comment]
I see it in the debugger each time I launch Godot, as there is no `__CFBundleIdentifier` environment variable

**Comment by bruvzg** [comment]
Maybe it is not set by the debugger. But it should be set for a bundle, or when running from the terminal (to the id of terminal).

**Comment by stuartcarnie** [comment]
I can confirm it does fix this exception 👍🏻

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
