### PR TITLE
Move brief description after class name in docs

### PR DESCRIPTION
**Pull request by ghost**
The brief description in the docs currently has its own block and heading (and takes up quite some room):

rect2-master

spotlight-master

I wonder if this description, being brief by definition, shouldn't be moved to the class name:

rect2

spotlight

### CODE REVIEW

**Comment by leoddd** [comment]
While saving a bit of space in some way might be worth it, this is definitely not it in my opinion.
The very top there deals entire with class names, so throwing a sentence of english in the middle is mildly confusing.

**Comment by poke1024** [comment]
Updated to this:

canvasitem

dictionary

**Comment by reduz** [comment]
Looks good the way it is to me

**Comment by akien-mga** [comment]
Maybe just removing the "Brief Description:" title and keeping only the paragraph would be better? I also don't like the initial proposal which makes it hard to spot the brief description at all. The later proposal is better but it's weird to have the description come before the inheritance info.

**Comment by akien-mga** [comment]
Closing as so far feedback is mostly that the proposed changes are not wanted.

**Pull request closed without merging**
