### PR TITLE
Fix uneditable `LineEdit`, `TextEdit` and `CodeEdit` virtual keyboard popup on mobile

### LINKED ISSUE #97993: Tapping on a non-editable LineEdit still brings up the iOS keyboard
### Tested versions

- Reproducible in 4.3.stable

### System information

iOS 18.0.1

### Issue description

Disabling a LineEdit, via `line_edit.editable = false` will still bring up the virtual keyboard on iOS, even though nothing happens when typing.

You can disable the virtual keyboard by setting `line_edit.virtual_keyboard_enabled = false` but bringing up an inert keyboard feels like a bug.

### Steps to reproduce

- Create a LineEdit node and set `editable = false`
- Export and run on iOS
- Tap the text field
- Observe the virtual keyboard that does nothing

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by syntaxerror247**
Fixes #97993

### CODE REVIEW

**Comment by SkogiB** [comment]
Looks good to me! Alas, I cannot do reviews.

**Comment by AThousandShips** [comment]
@SkogiB if you are able to test this you are very welcome to provide feedback, a review by a maintainer will be required to merge this but anyone that is able to provide feedback is welcome to do so, especially testing (it helps a lot to test on different hardware and contexts)

**Comment by syntaxerror247** [comment]
@ajreckof I have updated it to keep it consistant between the two classes. Now check for editable is done before calling `show_virtual_keyboard()`.

**Comment by BrixsterPlanet** [comment]
Should the virtual keyboard automatically hide if the control is set to read-only after the keyboard has already been shown?

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
