### PR TITLE
Fix cyclic references issues with global classes

### LINKED ISSUE #21461: Some usages of `class_name` can produce cyclic errors unexpectedly
___

***Bugsquad edit:** This issue has been confirmed several times already. No need to confirm it further.*

___

Windows 10 64-bit - Godot 3.1 alpha

## Edit - Refined issue to focus on cyclic errors.

Certain uses of `class_name` can produce cyclic errors in situations where there are no cyclic references, and in fact sometimes no other references outside of the single one given.

I've noticed this most frequently in tool script when using `is` to make a class comparison, but it seems to happen at times in normal script situations.

Recreating it in a sample project has eluded me.

godot master_2018-08-27_00-47-02

### LINKED ISSUE #41027: Cyclic reference error in GDScript 2.0
**Godot version:**
Godot Eninge v4.0.dev.custom_build.ec678c5e9

**OS/device including version:**
Windows 10

**Issue description:**
Cyclic reference error:
image

**Steps to reproduce:**
1) Create class1 and class2
2) Initialize class1 in class2 and class2 in class1
3) Add class1 to scene

**Minimal reproduction project:**
[godot_cyclic_reference.zip](https://github.com/godotengine/godot/files/5023741/godot_cyclic_reference.zip)

### PR DESCRIPTION
**Pull request by adamscott**
~~This PR works in tandem with #65752 for fixing cyclic references issues.~~
**This PR is not needed if #65752 is merged, as it deals too with global classes.**

This makes possible to reference class `A` (`class_name A`) in class `B` (`class_name B`) and `B` in `A`. This is not possible actually.

```gdscript
# a.gd
class_name A
extends Node

enum Test {
	VALUE_A,
	VALUE_B
}

static func hello() -> void:
	prints("Hello from A")
	B.hello()

# b.gd
class_name B
extends Node

static func hello() -> void:
	prints("Hello from B")
	prints("from A:", A.Test.VALUE_A)
```

In the master branch, this code fails on runtime with this error: `Parser Error: Can't load global class B, cyclic reference?`

The compiler, in this PR, checks if the script of the global class can be loaded. When the script exists but cannot be loaded, it means usually that the script is loaded but not compiled. So, the compiler now tags this entity as temporary to be read dynamically instead of being considered as a constant.

Minimal reproduction project:
[cyclic2.zip](https://github.com/godotengine/godot/files/9543298/cyclic2.zip)

Fixes #21461, fixes #41027.

### CODE REVIEW

**Comment by nathanfranke** [comment]
Here's a quick script to merge and test both #65664 and #65752

```sh
pr() {
    : ${1?"Usage: pr 12345"}
    git fetch origin "pull/$1/head:pr/$1" || return 1
    git switch "pr/$1" || return 1
}

pr 65664
pr 65752
git checkout master
git merge --no-edit 'pr/65664'
git merge --no-edit 'pr/65752'
```

**Comment by adamscott** [comment]
@nathanfranke I think they should be separated. #65752 has some problems related to memory leaks that I must solve. This PR does not seem to share this problem.

**Comment by adamscott** [comment]
> Edit: Response to below: I don't plan to review the code much, I am mostly enjoying this for my "fork" for prototyping projects, so memory leaks aren't a huge deal for that.

Don't hesitate to report bugs here or on the other PR! I would love some feedback, even if it's not related to code review purposes.

**Comment by adamscott** [comment]
I updated the PR description to underline that it is not needed if #65752 is merged, as it deals with global classes too and is much more in depth.

#65752 updates the GDScript engine to use weak references for scripts, which permits cyclic references with `preload()` too.

**Comment by adamscott** [comment]
#65752 is the way to go. I'm closing this PR.

**Pull request closed without merging**
