### PR TITLE
Centers the 2D viewport in the editor

### PR DESCRIPTION
**Pull request by groud**
Enjoy ! :)
2DscreenCenter

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by groud** [comment]
Thinking about it, this implementation centers the view according to the center of the viewport window. It might make sense to center it according to the viewport content instead.

I'll have a look to that. :)

**Comment by Anutrix** [comment]
You mean by: 1. Getting position of all nodes. 2. Joining to make a closed shape. 3. Setting center of the view to center of that shape.

**Comment by groud** [comment]
Yeah more or less, but:

>  Joining to make a closed shape.

is more about computing an enclosing rect for all nodes on the screen, and compute its center.

**Pull request merged**
