### PR TITLE
fix for exported int reset when saving a scene.

### LINKED ISSUE #10063: Exported variables are reseted to default upon saving
**Operating system or device - Godot version:**
Linux, aef974e7a8577f857be8cf89f02844575d0839bb

**Issue description:**
Some types of exported variables seems to be reseted when saving scene. I can tell for sure that's a case for exported int types. (including enum style int hints(int, "Val1", "Val2")).
exportedintreset

**Steps to reproduce:**
1. Download sample project
2. Open "res://Issues/ExportedVariablesSaveIssue/ExportedVariablesSaveIssue.tscn"
3. Change values in inspector
4. Save scene with ctrl+s or from File menu.
5. Observe that changes made in exported int values are gone.

**Link to minimal example project:**
[ExportIntResetIssue.zip](https://github.com/godotengine/godot/files/1196633/ExportIntResetIssue.zip)

### PR DESCRIPTION
**Pull request by kubecz3k**
I guess the problem was that the `round()` is returning real type, and not an integer. 
closes #10063

### CODE REVIEW

**Comment by endragor** [comment]
The core problem (and it goes deep) is that integers are represented as reals in the editor. That makes it impossible to set absolute values greater than 2^52, even though Variant stores 64-bit integers. A better approach would be to use Variant for values, which supports converting numeric values seamlessly, but that requires plenty of changes.

I think in this quick fix you should convert to `int64_t` instead of `int` to avoid an even larger loss.

**Comment by kubecz3k** [comment]
Originally int value was stored... I'm not experienced with c++ but I would consider if using int64 won't cause some minimal slowdowns on 32bit systems, especially mobile, or possibly any kind of other rare problems?

**Comment by endragor** [comment]
Variant is usually used where scripting (dynamic typing) is involved. And in scripting using int64 vs int would be the last thing that causes slowdowns. Performance-critical code can use whatever type it sees fit. Your concern surely doesn't apply to the editor.

**Comment by kubecz3k** [comment]
Ok I see :)

**Comment by akien-mga** [comment]
Superseded by 475e8b28.

**Pull request closed without merging**
