### PR TITLE
[3.2] Fix shader constant sorting

### LINKED ISSUE #37457: Shader language doesn't allow assigning constants with constant arithmetic with other constants
**Godot version:**
v3.2.1.stable.official

**OS/device including version:**
PC running Windows 10 (10.0.18362)
Intel Core i5-8600K @ 3.60GHz, 6cores
NVidia GeForce GTX 1060 6GB (Driver version 432.00)
8GB RAM

**Issue description:**
The shader language doesn't seem to accept constants that use arithmetic operations involving other constants. In comparison, this seems to work in raw GLSL (https://github.com/McNopper/OpenGL/blob/master/Example11/shader/glass.vert.glsl).

**Steps to reproduce:**
Paste the following shader into a MeshInstance node's material:

```
shader_type spatial;
// Indices of refraction
const float Air = 1.0;
const float Glass = 1.51714;

// Air to glass ratio of the indices of refraction (Eta)
const float Eta = Air / Glass;
 
// see http://en.wikipedia.org/wiki/Refractive_index Reflectivity
const float R0 = ((Air - Glass) * (Air - Glass)) / ((Air + Glass) * (Air + Glass));

void fragment() {
    ALBEDO = vec3(1.0, 0.8, 0.5);
}
```
The shader breaks:
ShaderBug_ConstantAritmetic

If I rewrite the shader constants as:
`const float Eta = 1.0/ 1.51714;`
then the shader does not break.

**Minimal reproduction project:**
[ShaderBug_ConstantAritmetic.zip](https://github.com/godotengine/godot/files/4407871/ShaderBug_ConstantAritmetic.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
(For 3.2) Fix #37457

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by aaronfranke** [comment]
Has this also been fixed in master? What's the PR number? Pull requests should generally be made against master and then cherrypicked into older branches.

**Comment by Chaosus** [comment]
in master, these have changed directory, which prevents to cherry-picked (I think so)

**Comment by akien-mga** [comment]
A PR is needed for the `master` branch, I don't want us to fix the bug in 3.2 and then forget about it.

**Comment by Chaosus** [comment]
@akien-mga Alright, I made a 4.0 version.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
