### PR TITLE
Tweaks of Spatial, Transform and Transform2D docs.

### PR DESCRIPTION
**Pull request by SirPigeonz**
Some style changes and tweaks after @hubbyist feedback.

# WIP!

### CODE REVIEW

**Comment by groud** [comment]
I don't agree with most of those changes. Removing 's' and 'the' makes the sentence not a proper english.
See examples here: 
- https://docs.python.org/3/library/unicodedata.html
- https://docs.oracle.com/javase/7/docs/api/

**Comment by Zireael07** [comment]
At least 'returns' needs to be kept with the s. In most other cases, it doesn't matter if it's 3rd person sg. or not, but returns needs to stay as is.
About 'the', I'm on the fence.

**Comment by n-pigeon** [comment]
@groud I removed "s" to match rest of the docs where it is more "do something" than "does something" But I can change other way around and ad "s" everywhere :D 

The was my mistake I will fix articles "the".

**Comment by groud** [comment]
Actually it depends, in some cases you can use the infinitive form. But when you say what a function does you should use the indicative present. Here it's more like "(this function) returns..."

There still might be some places where the doc is wrong about that also ^^

**Comment by n-pigeon** [comment]
Sorry, I've created new branch, so I'm closing this PR and opening new #11255. ^_^'

**Pull request closed without merging**
