### PR TITLE
Add helper methods to check for tile transforms

### LINKED ISSUE #81942: There is no way to know if a cell is flipped or transposed in a TileMap
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Fedora Linux

### Issue description

There is no way to know if a cell is flipped or transposed in a TileMap.
In Godot 3 I can access with `is_cell_transposed`, `is_cell_x_flipped` and `is_cell_y_flipped`.

### Steps to reproduce

Create a TileMap, add a basic TileSet, paint a flipped or transposed cell and try to read that information from GDScript.

### Minimal reproduction project

Reproduction steps are trivial and don't require any project files to be followed.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #81942

### CODE REVIEW

**Comment by interacsion** [comment]
Is anything blocking this PR from going forward?

**Comment by KoBeWi** [comment]
It's missing a review.
CC @groud

**Review by groud — APPROVED** [review]
I think it's a nice to have.

**Review by kleonc — DISMISSED** [review]
`TileMap` is deprecated now, the methods should be added to `TileMapLayer` instead.

**Comment by KoBeWi** [comment]
Added to TileMapLayer.

**Review by kleonc — COMMENTED** [review]
Should it be added to both TileMapLayer and deprecated TileMap though? Or only to TileMapLayer? :thinking:

**Comment by KoBeWi** [comment]
I already had the code written for TileMap, so removing it would be extra work.  No harm in keeping it.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
For some reason GitHub didn't pick this up as a no-ff merge and didn't close this PR as merged, weird.
I see it also choked my scripts and failed to parse the `author` info to add to the merge commit message, I'll have to check that.

**Comment by akien-mga** [comment]
Merging another PR fixed it :upside_down_face:

**Pull request merged**
