### PR TITLE
Improved uniformity of RandomPCG::randf.

### PR DESCRIPTION
**Pull request by ghost**
When generating single precision floats, Godot casts a uint32_t to float, causing uniformity loss.

This new implementation (referred to as `randf_clz` below) samples the output of rand as the fraction part of an infinite binary number, with some tricks to reduce ops and branching. This method provides "good enough" uniformity at decent speed, for floats greater than 2^-64 (and doubles greater than 2^-96). Numbers smaller than the threshold are floored to 0. This threshold is completely arbitrary, as a way to balance between quality and performance.

The approach is inspired by the idea behind Taylor R. Campbell's random_real, but also differs greatly from it in implementation. I consider the current code original.

Performance numbers (200000 iterations):

```
noop time: 14229
randf_old time: 36782 (22553, +0.0%)
randf_clz time: 38461 (24232, +7.4%)
randf_campbell time: 39023 (24794, +9.9%)
```

- - -

EDIT: Summarize discussions.
EDIT2: Update OP according to current state of the branch.

### CODE REVIEW

**Comment by toasteater** [comment]
@Chaosus Could you take a look at this? Posting a comment as I can't request reviews.

**Comment by Chaosus** [comment]
If you provides a test where show the advantages of this method it would be much better ^^ otherwise it takes a time to recreate a test environment

**Comment by Chaosus** [comment]
Would it make sense to also fix randi_range (if you know how of course) ?

**Comment by Chaosus** [comment]
> There exists an algorithm that supposedly generate actually uniform floating point numbers by Taylor R. Campbell, which can be found at https://mumble.net/~campbell/2014/04/28/random_real.c, namely the random_real function. 

This needs to be tested - how much time it take off compared to the current method ? Games needs to generate number as fast as possible and Godot(which is game engine) should use fastest as possible methods everywhere.

**Comment by Chaosus** [comment]
Speed test:

	var rng = RandomNumberGenerator.new()
	rng.seed = 100
	var time_before = OS.get_ticks_usec()
	var s = PoolRealArray()
	for i in range(50000):
		s.append(rng.randf())
	var time_spent = OS.get_ticks_usec() - time_before
	print("Stuff time: ", time_spent)

For 3.1 stable : 15518, For the proposed commit : 23354

**Comment by Chaosus** [comment]
After some test I think ~10% slower than current method - nothing significally if its improves uniformity ) 

image

I think its good )

**Comment by toasteater** [comment]
> If you provides a test where show the advantages of this method it would be much better ^^ otherwise it takes a time to recreate a test environment

It's not very easy to do because this is a statistical problem, and it's random numbers after all. With the brute force approach you probably need millions of numbers before you can see anything concrete (and much, much more before you can see it visually), so Godot isn't a very suitable environment, not to mention the currently bugged seed function. Maybe we can try to use one of those RNG benchmarks.

> This needs to be tested - how much time it take off compared to the current method ?

Good point. I'll try profiling Campbell's method and come back with some numbers. If it's not too slow we can use that instead of truncation.

**Comment by Chaosus** [comment]
Yeah, its not seems much of difference for 1000-3000 samples

image

Need to have a millions as you said )

**Comment by toasteater** [comment]
Ok, so I tried using the brute force method but that didn't work out very well, so I tried another approach. Because of the nature of this bias, it's more manifest at the upper end, so I enumerated integers in the range 0xFFFFFE00 to 0xFFFFFFFF, 512 numbers in total. Then, I tried to map them using the old and new randf functions:

```
func randf_old(i):
	return float(i) / float(RAND_MAX)

func randf_new(i):
	return float(i & FLOAT_MAX_INT) / float(FLOAT_MAX_INT)
```

So here's the result: for all those 512 numbers, `randf_old` returned 1, which should really only happen for 0xFFFFFFFF, if it works like what it seems to be. `randf_new` mapped them without problems. Here's projects and screenshots for the interested, though there isn't even RandomNumberGenerator in it...

[randf.zip](https://github.com/godotengine/godot/files/2976587/randf.zip)
randf

**Comment by toasteater** [comment]
I implemented all three methods, compiled with optimization, and benchmarked with the following code on.

```
var rng = RandomNumberGenerator.new()
rng.randomize()
var s = PoolRealArray()
var iterations = 200000;
s.resize(iterations)
	
var time_before = OS.get_ticks_usec()
for i in range(iterations):
	s[i] = rng.randf()
var time_spent = OS.get_ticks_usec() - time_before
print("randf_old time: ", time_spent)
	
time_before = OS.get_ticks_usec()
for i in range(iterations):
	s[i] = rng.randf_truncate()
time_spent = OS.get_ticks_usec() - time_before
print("randf_truncate time: ", time_spent)

time_before = OS.get_ticks_usec()
for i in range(iterations):
	s[i] = rng.randf_campbell()
time_spent = OS.get_ticks_usec() - time_before
print("randf_campbell time: ", time_spent)
```

Results.  Campbell is actually surprisingly fast on my machine:

```
randf_old time: 38316
randf_truncate time: 35774
randf_campbell time: 39301
```

Campbell is supposed to be the best performing one statistics-wise (though as before, it's hard to visualize), and it actually have decent performance. The downside is that it comes with a license. Here are the sources for the `randf_*` functions:

```
_FORCE_INLINE_ float randf() {
	return (float)rand() / (float)FLOAT_MAX_INT;
}
_FORCE_INLINE_ float randf_truncate() {
	return (float)(rand() & FLOAT_MAX_INT) / (float)(FLOAT_MAX_INT);
}
_FORCE_INLINE_ float randf_campbell() {
	/*-
	* Copyright (c) 2014 Taylor R. Campbell
	* All rights reserved.
	*
	* Redistribution and use in source and binary forms, with or without
	* modification, are permitted provided that the following conditions
	* are met:
	* 1. Redistributions of source code must retain the above copyright
	*    notice, this list of conditions and the following disclaimer.
	* 2. Redistributions in binary form must reproduce the above copyright
	*    notice, this list of conditions and the following disclaimer in the
	*    documentation and/or other materials provided with the distribution.
	*
	* THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
	* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
	* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
	* ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
	* FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
	* DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
	* OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
	* HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
	* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
	* OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
	* SUCH DAMAGE.
	*/
	// Modified for uint32_t and float
	int exponent = -32;
	uint32_t significand;
	unsigned shift;
	while (unlikely((significand = rand()) == 0)) {
		exponent -= 32;
		if (unlikely(exponent < -149)) {
			return 0;
		}
	}

	shift = __builtin_clz(significand);
	if (shift != 0) {
		exponent -= shift;
		significand <<= shift;
		significand |= (rand() >> (32 - shift));
	}

	significand |= 1;

	return ldexp((float)significand, exponent);
}
```

**Comment by toasteater** [comment]
Fixed the old `randf` and added measurement of a noop loop for reference. Here's the results I got for 200000 iterations (same as before):

```
noop time: 13782
randf_old time: 38051 (24269, +0.0%)
randf_truncate time: 37129 (23347, -3.8%)
randf_campbell time: 40673 (26891, +10.8%)
```

Code:

```gdscript
var rng = RandomNumberGenerator.new()
rng.randomize()
var s = PoolRealArray()
var iterations = 200000;
s.resize(iterations)

var time_before = OS.get_ticks_usec()
for i in range(iterations):
	s[i] = 0
var noop_time = OS.get_ticks_usec() - time_before
print("noop time: ", noop_time)

time_before = OS.get_ticks_usec()
for i in range(iterations):
	s[i] = rng.randf()
var time_spent = OS.get_ticks_usec() - time_before
var base_time = time_spent - noop_time
print("randf_old time: ", time_spent, " (", time_spent - noop_time, ", ", "%+.1f%%" % ((time_spent - noop_time - base_time) * 100.0 / base_time), ")")

time_before = OS.get_ticks_usec()
for i in range(iterations):
	s[i] = rng.randf_truncate()
time_spent = OS.get_ticks_usec() - time_before
print("randf_truncate time: ", time_spent, " (", time_spent - noop_time, ", ", "%+.1f%%" % ((time_spent - noop_time - base_time) * 100.0 / base_time), ")")

time_before = OS.get_ticks_usec()
for i in range(iterations):
	s[i] = rng.randf_campbell()
time_spent = OS.get_ticks_usec() - time_before
print("randf_campbell time: ", time_spent, " (", time_spent - noop_time, ", ", "%+.1f%%" % ((time_spent - noop_time - base_time) * 100.0 / base_time), ")")
```

**Comment by toasteater** [comment]
Campbell's algorithm is a bit slow, and it comes with a license, so I searched for ways to improve it for Godot's purpose. In particular, it's very wasteful when it comes to `rand` usage: it calls `rand` twice about half of the time, and has the potential to call it up to 6 times. That's a *lot* of bits for a 24-bit significant number. It's understandable from a pure precision perspective, but probably not fast enough for Godot.

To minimize `rand` usage, I noticed one thing: the significand is directly taken from the random bits, but the exponent is produced from zeroes. The algo imagines the random bits to form an infinite binary number, so this is only natural. However, for random number generation, we only have to fit the distribution, and don't have to *actually* do that. In effect, there's a 2^-n probability for the exponent to have a -n offset, and float only has 23 bits for the significand, so what can we do with the remaining 9 random bits in a uint32? Produce an exponent offset from it! So here you go, a branch-less, license-less, (mostly) debiased randf with 33 bits of resolution (better than 32 of the biased original, 24 of randf_truncate. worse than the full 149 of randf_campbell but that is to be expected):

```cpp
_FORCE_INLINE_ float randf_ctz() {
	uint32_t r = rand();
	uint32_t significand = (r & 0x007FFFFF) | 0x00800000;
	return ldexp((float)significand, -24 - __builtin_ctz(r >> 23));
}
```

**How does it perform?**

**Speed:**
Faster than campbell, a bit slower than the old method.
```
noop time: 13999
randf_old time: 36208 (22209, +0.0%)
randf_ctz time: 37194 (23195, +4.4%)
randf_campbell time: 37838 (23839, +7.3%)
```

**Uniformity:**
8lsb
Screenshot of the **8 LSBs of the significands** of the numbers generated. Notice how randf_old has an obvious **even-odd** pattern, while ctz and campbell is free of it.

normal
Screenshot of **the numbers themselves** as a sanity test.

I'm still testing the new method, and will push after I document and port it to the PR branch!

**Comment by Chaosus** [comment]
I found a bug inside my normal generation PR - #27043

image
For some reason it generates 0 value twise as usual - if you can fix it in your PR this will be very cool - I've attached updated example
[TestRandom.zip](https://github.com/godotengine/godot/files/2982051/TestRandom.zip)

**Comment by toasteater** [comment]
@Chaosus This is unrelated. I tried all three `randf`'s and none worked, then it happened to me that I should try the function with my histogram as well... Turns out that the function is fine, it's the histogram that's broken (!)

gaussian

**Comment by Chaosus** [comment]
Phew.. Thanks for checking !

**Comment by toasteater** [comment]
I have updated the branch with a fixed version of my previous attempt at a license-free randf:

```cpp
uint32_t proto_exp_offset = rand();
if (unlikely(proto_exp_offset == 0)) {
	return 0;
}
return __builtin_ldexpf((float)(rand() | 0x80000001), -32 - __builtin_clz(proto_exp_offset));
```

Performance wise it's a bit faster than Campbell's, but around +10% slower than stable:

```
noop time: 14229
randf_old time: 36782 (22553, +0.0%)
randf_clz time: 38461 (24232, +7.4%)
randf_campbell time: 39023 (24794, +9.9%)
```

Quality wise, it should be on par with Campbell's for most of the range, with the exception that floats that would be smaller than 2^-64 are floored to zero. This is to minimize `rand` calls and lower the upper bound for the function.

8lsb
Screenshot of a histogram of the *8 LSBs* of the significands of the numbers generated. Notice how randf_old has an obvious even-odd pattern, while clz and campbell are free of it.

normal
Sanity test. No missing columns this time...

**Comment by reduz** [comment]
I have no idea what you guys are doing, but it looks great

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
