### PR TITLE
Limit directional shadow draw distance, fixes #559, optimization

### LINKED ISSUE #559: Shadow map garbage shadow outside of directional light Max Distance
I have quite big map and I need player to see quite far away.
So I made set-up with really big Camera Max distance view, and made my directional light Max Distance much smaller but enough to display RT shadows close to Camera, with reasonable sized shadow map.
Unfortunately in distance outside of Light Max Distance where should be no shadows, for some reason weird huge shadow is created.

Image:

### PR DESCRIPTION
**Pull request by mookiexl**
Shadow fade exponent is hardcoded for now. Someone with better understanding of Godot code could make it a parameter.

### CODE REVIEW

**Comment by reduz** [comment]
I was thinking of doing this by clearing the top of the shadow texture, so it always blends into white, will check into this hopefully next week

**Comment by akien-mga** [comment]
@mookiexl There is a lot of noise in this PR due to commits that you added and then reverted, and unnecessary merge commits. Ideally your PR should have only three commits: 3dc57ae, 4dbec4d and 6e4a683.

Could you clean this up somehow? (see ```git pull --rebase``` and ```git rebase -i HEAD~\<nb of commits to edit\>```)

**Comment by mookiexl** [comment]
OK, it should be cleaned up now.

**Comment by akien-mga** [comment]
Great, thanks :)

**Comment by akien-mga** [comment]
> I was thinking of doing this by clearing the top of the shadow texture, so it always blends into white, will check into this hopefully next week

@reduz Did you get to check it in the end?

**Comment by akien-mga** [comment]
> I was thinking of doing this by clearing the top of the shadow texture, so it always blends into white, will check into this hopefully next week

@reduz Did you get to check it in the end?

**Comment by akien-mga** [comment]
Any renderer experts to check this out? @reduz, @SaracenOne

**Comment by akien-mga** [comment]
Super ping :)

**Comment by SaracenOne** [comment]
I've just tested this out on a scene I have with very long shadows, and I can say it is a definetely a significant improvement. Would indeed support it being merged.

**Comment by akien-mga** [comment]
Alright, couldn't get @reduz to comment on this in one year, but since @SaracenOne approved of it, let's merge. It will anyway soon be made obsolete by the new PBR-based renderer.

**Pull request merged**
