### PR TITLE
Visual Studio: Improve performance of parsing project file

### PR DESCRIPTION
**Pull request by shana**
Visual Studio doesn't handle string parsing very well, so having all the files in one property slows down VS a lot when loading the projects. Splitting the files up into per-directory properties brings down project processing times from 20 seconds to 1 second (on my machine).

Also adding a `vsproj_props_only` flag to skip touching the vcxproj and sln files when regenerating the project files. This is so the rebuild command in VS can regenerate the build-specific project files without throwing away user customizations to the project. This flag is off by default, and only enabled in the Rebuild All command from VS (or if the user passes it on the command line).

Note: All the build-specific information is in the generated.props files, and the vcxproj and sln files only contain the generic list of platform configurations available to VS. The only time both sln and vcxproj file can change is when adding new platforms, and the only time the vcxproj file can change (but not the sln) is when adding/removing files (and this doesn't affect the build itself, but only the file listing in the VS Solution Explorer). All other build system changes only affect the .generated.props files. Therefore, most of the time, it's safe to regenerate only the generated.props files and not touch the vcxproj or sln files.

### CODE REVIEW

**Comment by akien-mga** [comment]
A more explicit commit message would be good (e.g. like I edited the PR too, if that's accurate). Otherwise there are lots of things I can think of as "VS performance" which wouldn't really relate to that (e.g. the performance of binaries compiled with MSVC).

**Review by akien-mga — APPROVED** [review]
Some style issues to fix by running `black -l 120` on the file (or installing the precommit hooks with `pip install pre-commit && pre-commit install`), but otherwise looks good!

**Comment by shana** [comment]
Oh hey, thanks @akien-mga! I'm just running some final tests to make sure nothing is broken (looks pretty good so far), and I'll clean it up :+1:

**Comment by shana** [comment]
Ok, tested it all, good to go! 👍

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
