### PR TITLE
Set `base_path` and `filename` during GLTF export when writing to a file

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR sets `base_path` and `filename` during the export process, and exposes `filename`. Previously only `base_path` was exposed and it was only used during the import process.

~~🚲🏚️: I used `file_name` for consistency with most of the engine's `file_path`, but as for just file names and not paths `filename` is twice as common as `file_name`. Personally I prefer `file_name`.~~

### CODE REVIEW

**Comment by fire** [comment]
I rather not add to the inconsistency. Any suggestions? @YuriSizov

**Review by lyuma — APPROVED** [review]

**Review by YuriSizov — APPROVED** [review]
Looks fine to me. Needs a rebase though.

Also, and this is not new to this PR, but shouldn't getters be const for `GLTFState` members? (Note that changing that would require adding compatibility methods for the GDExtension API.)

**Comment by aaronfranke** [comment]
@YuriSizov Rebased and re-tested. Thanks for the catch with GLTFState property constness. Since filename is being added in this PR and copyright is not in Godot 4.1, I have changed those to be const. But base_path and the other properties were already exposed in Godot 4.1 so those will have to wait for the future to be changed to const.

**Comment by akien-mga** [comment]
> But base_path and the other properties were already exposed in Godot 4.1 so those will have to wait for the future to be changed to const.

They could be changed now, you then just need to add compatibility methods so that existing compiled GDExtensions can find the old method hash and keep using it. See examples in #80168.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
