### PR TITLE
GDScript: Replace ptrcalls on MethodBind to validated calls

### PR DESCRIPTION
**Pull request by vnen**
This improves the performance of typed calls to engine methods when the argument types are exact.

Using validated calls delegate more of the work the core instead of doing argument unpacking in the VM. It also does not need different instructions for each return type, simplifying the code.

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Approved during the GDScript team meeting. We only reviewed the PR on the form, not the content. We trust @vnen on the performance improvements.

**Comment by akien-mga** [comment]
Might be worth a rebase and re-testing to ensure it still works as intended, since it was authored more than 2 months ago and we merged a bunch of changes in the meantime.

**Comment by dsnopek** [comment]
I've made PR https://github.com/godotengine/godot/pull/82794 to address the GDExtension performance issue I brought up in my previous comment. I've tested it with this PR, and it seems to be working fine (the automated godot-cpp tests pass).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
