### PR TITLE
Rename `NOTIFICATION_INSTANCED` to `NOTIFICATION_SCENE_INSTANTIATED`

### PR DESCRIPTION
**Pull request by MewPurPur**
Looks like we missed an instance of the old "instanced" verb

### CODE REVIEW

**Comment by YuriSizov** [comment]
Regarding keeping the terms in sync, this makes sense. But I'm not sure if this is a good name for the notification, and the description is just incorrect. Nodes don't get instantiated, packed scenes do. So there was another proposal for a rename from @QbieShay some time ago, trying to address that problem: https://github.com/godotengine/godot/issues/25538.

Maybe we should still consider a better name for this notification.

**Comment by MewPurPur** [comment]
Didn't know about this – should I edit this PR?

**Comment by YuriSizov** [comment]
You can definitely update the description of the notification to indicate that it is received when the node is at the root of a scene that was just instantiated. Basically, the reverse of what the `instantiate()` description tells.

As for the notification itself, probably more opinions are required. I don't have a preference. Can suggest something like `NOTIFICATION_SCENE_INSTANTIATED` maybe.

**Comment by akien-mga** [comment]
If it's received only by scene `owner`s, then yeah `SCENE_INSTANTIATED` makes sense to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
