### PR TITLE
Use a "text field" cursor for EditorSpinSliders in the animation editor

### PR DESCRIPTION
**Pull request by Calinou**
This makes them easier to recognize as fields that can be edited.

### CODE REVIEW

**Comment by akien-mga** [comment]
Why do this only for specific controls and not for all input fields though?

Currently EditorSpinSlider seems to use the `IBEAM` cursor when the text field is clicked. It's the same for all input fields in the inspector and those in the AnimationPlayer editor, so I don't think one should be treated differently from the others.

I'm not against making so that all EditorSpinSlider fields have an `IBEAM` cursor on hover, though we'd have to make sure that it properly reverts to the normal default cursor when out of bounds.

**Comment by Calinou** [comment]
@akien-mga I've tried enabling this for all EditorSpinSliders, but it feels strange when there's a grabber below because the cursor will suddenly switch from `CURSOR_IBEAM` to `CURSOR_ARROW` when hovering the grabber. Maybe this should be done only when `set_hide_slider(true)` has been called on the EditorSpinSlider? This would still be more "generic" than doing it just for the EditorSpinSliders in the animation track editor.

**Comment by akien-mga** [comment]
I don't know, it seems a bit too magic to me if something like this depends on the presence of a slider. The text input field is the same regardless of the presence of the slider, so it would be weird if hovering it produces different behavior.

**Comment by aaronfranke** [comment]
@Calinou Is this still desired? If so, it needs to be rebased on the latest master branch. While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

**Comment by akien-mga** [comment]
I'm still not convinced that this is a good idea, I don't think those two fields should get special treatment. We could change things in `EditorSpinSlider` directly if we reach a consensus on what would be better UX.

**Pull request closed without merging**
