### PR TITLE
Removes some unused functions and variables

### PR DESCRIPTION
**Pull request by benbot**
Removes some unused functions that @lyuma discovered while working on Skeleton3D and some unused variables I discovered while working on a water physics module.

### CODE REVIEW

**Review by fire — APPROVED** [review]
Removing skeleton functions that have no users in the engine and are badly modifying internal state without going through the skeleton API and thus incorrectly.

* set_bone_children
* add_bone_child
* remove_bone_child

Removed comments.

@reduz

**Review by fire — CHANGES_REQUESTED** [review]
Can you explain the reasoning for these removals?

```
linear_velocity = p_state->get_linear_velocity();
angular_velocity = p_state->get_angular_velocity();
inverse_inertia_tensor = p_state->get_inverse_inertia_tensor();
```

According to the pr guidelines the commit message need to be informative, and we need bug reports for the two commits of the skeleton removal and these physics changes.

**Comment by fire** [comment]
One commit is fine, can you revise the commit message.

**Review by fire — APPROVED** [review]
Since I and Lyuma proposed this, need someone like @akien-mga or @reduz to check for style and general architecture.

**Review by akien-mga — COMMENTED** [review]
Style wise it's fine, but I can't say if the removal is fine, I'm not familiar enough with the Skeleton3D bones workflow.

**Comment by akien-mga** [comment]
@reduz says:

> I have no idea what these are for, should probably use blame to find out 

Seems like those were added by @TwistedTwigleg in #51368. This predates later Skeleton3D / bone refactoring so it might indeed be obsolete. Would be nice if TwistedTwigleg could confirm :)

**Comment by TwistedTwigleg** [comment]
These functions were added as part of the Skeleton refactor to remove BoneAttachment3D and make it a modification super early on in my work on GSoC, before the system was really figured out and before Skeleton3D got major changes to how it all works internally. It can be removed - it is non-necessary and can be removed 👍

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
