### PR TITLE
Audio bus select effect fixed

### PR DESCRIPTION
**Pull request by Vinealius**
Make the appropriate selection of the effect on the audio bus.

> - Select an effect on more than one Audio bus the other ones remains selected, so if you press the Delete key you can delete one effect selected at a time of each diferent Audio bus.

> - Create a new node in the scene and create and select a Audio bus effect, then select the new scene node and press the Delete key to delete the node, the effect will be deleted instead.

### CODE REVIEW

**Comment by Calinou** [comment]
Pull requests should be opened against the `master` branch (unless they can't be applied there for some reason). We can then cherry-pick them to the `3.2` branch.

**Comment by aaronfranke** [comment]
@DashCell You need to cherry-pick your commit on the master branch, then force-push that to this PR. Currently your changes are based on 3.2 even though the PR targets master, which causes all commits from 3.2 to display here. For more information, see this documentation article: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html

**Comment by DashCell** [comment]
I need use the master banch? i made it from the 3.2.3_rc6. @Calinou

**Comment by aaronfranke** [comment]
@DashCell Yes, you need to use the master branch. As stated in the PR template:

```markdown
<!--
Pull requests should always be made for the `master` branch first, as that's
where development happens and the source of all future stable release branches.

Relevant fixes are cherry-picked for stable branches as needed.

Do not create a pull request for stable branches unless the change is already
available in the `master` branch and it cannot be easily cherry-picked.
Alternatively, if the change is only relevant for that branch (e.g. rendering
fixes for the 3.2 branch).
-->
```

**Pull request closed without merging**
