### PR TITLE
Make editor camera speed indicator use `m/s` and `m`

### PR DESCRIPTION
**Pull request by AThousandShips**

### CODE REVIEW

**Comment by AThousandShips** [comment]
Unsure if the normal camera indicator, which represents `cursor.distance`, is also meters

**Review by Calinou — APPROVED** [review]
For context, these were initially displayed as "units" as meter suffixes weren't present in inspector properties at the time I added these labels.

It makes sense to call them meters, now that we use this terminology elsewhere in the editor.

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
