### PR TITLE
Remove unexposed ProxyTexture, mark AnimatedTexture as deprecated

### PR DESCRIPTION
**Pull request by akien-mga**
According to reduz:

> [AnimatedTexture] should be removed together with ProxyTexture, its just
> not efficient at all in Vulkan and causes invalidation of all descriptor
> sets depending on it
> it was needed mostly for animated tilemaps, but nowadays there is not a lot
> of reason for it

Marking AnimatedTexture as deprecated accordingly, until we reach consensus for removing it completely.

Since ProxyTexture was unexposed, this technically only breaks compatibility for C++ modules. ProxyTexture was already not available from GDScript, C# or GDExtension.

Note that there's still a concept of proxy texture in the `RenderingServer.texture_proxy_create()`, which is currently used for ViewportTexture. This is not removed by this PR, only the high level resource.

Continuation of #64595 - the class was kept probably due to a misunderstanding, when reduz meant it's still used internally, he meant `RenderingServer.texture_proxy_create()` which is the backend for the (now removed) resource.

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
Off with the head!

**Comment by YuriSizov** [comment]
Thanks!

**Comment by Zireael07** [comment]
So how *does* one make animated tilemaps now?

**Comment by YuriSizov** [comment]
You can set up animation for any TileSet atlas in the new TileMap editor

**Comment by vaartis** [comment]
What about animating TextureRects?

**Comment by AnidemDex** [comment]
Is there a discussion board or issue open to know if the animated texture is going to be replaced or removed?

**Comment by LakshayaG73** [comment]
@reduz how concerning are these performance losses from using AnimatedTexture2D in say, a Line2D node that has a few hundred points?

**Pull request merged**
