### PR TITLE
Fix #6653, add an option to stop the update spinner from spinning

### LINKED ISSUE #6653: remove the little update spinner distracting animation/widget
**Operating system or device - Godot version:**
Win 7 32bit Pro
Godot 2.1
desktop with mouse

**Issue description** (what happened, and what was expected):
the spinner at the top right that shows repainting activity is to me an annoying distraction.
it would be nice to have a way to right click and disable it.

(please note as well for whatever it is worth that the menu it brings up when clicking on it is incorrect ux because it shows checkboxes but they actually are mutually exclusive as far as i can tell which means they should be radio buttons.)

### PR DESCRIPTION
**Pull request by J08nY**
- Adds an option in the spinner popup menu to disable its spin.
  screenshot from 2016-10-01 16-45-24
- Exposes `PopupMenu.get_item_tooltip(int p_idx)` and `PopupMenu.set_item_tooltip(int p_idx, String tooltip)`
- Creates and exposes `PopupMenu.toggle_item_checked(int p_idx)`

### CODE REVIEW

**Comment by Hinsbart** [comment]
I think an option to hide the spinner would also be nice :)

**Comment by bojidar-bg** [comment]
@Hinsbart How would you reshow it in this case? :smile:

**Comment by Hinsbart** [comment]
With a right click menu or some little arrow indicator that opens the menu, I guess.

**Comment by J08nY** [comment]
Hmm, how about just setting the icon when the user disables the spinner from spinning, to a "dropdown arrow" indicator. So that way the menu entry would become "Hide Update Spinner"

**Comment by J08nY** [comment]
Updated the PR to change the spinner icon when the spinner is disabled.

**Pull request merged**
