### PR TITLE
Coroutines, i.e Improving GDScriptFunctionState

### PR DESCRIPTION
**Pull request by busy8**
[Note: If just want to know what this **means** for GDScript, or **you are confused** (looking at you **confused** emoji) I really recommend skipping down to a shorter summary available here:

https://github.com/godotengine/godot/pull/29675#issuecomment-500995809

The original post (below) mentions implementation details more and so the implications for the user are not as clear. But since I worked on it I wanted to share some details that may be helpful to reviewers]

More technical exposition follows:
*********************************************************************************
This is a patch to the yield() feature of GDScript to address some issues and add features that complete it.
I created this because I need it but I think it may be of value to users broadly so I've made the PR
My last comment on the issue below outlines my general intentions.
https://github.com/godotengine/godot/issues/29494

Firstly, I made as few changes as possible but one that I found absolutely necessary was to change the GDScriptFunctionState's resume() method so that it no longer invalidates the state it is called on. Suspended functions (which I'm calling coroutines from now on) now have a clear identity which allows the rest of code to interact with them in a simple way. However, existing GDScript code that calls resume() may have to be updated since it is now improper to reassign to the GDScriptFunctionState. 

With this change, the GDScriptFunctionState is returned only when the first yield() [of any kind] is encountered during execution of the function body. Functions that yield() can be thought of as coroutine factories which create a different coroutine every time they are called. The returned object can be resumed many times without invalidating though it may enter states from which resumption is impossible (more later). Despite the added power demonstrated in the examples, there's little additional overhead. (In fact there could be savings since a GDScriptFunction state is only allocated on the first yield and is reused thereafter.)

An argument can be passed to resume (as before) and this becomes the value of the yield() expression in the resumed coroutine. However, I have completed the cycle by implementing yield(value) which passes 'value' as the return value of resume() when a coroutine yields. Since resume() no longer returns a new GDScriptFunctionState, its return value is available for this.

```
func create_accumulator(total):
	var amount = yield()
	while true:
		total = total + amount
		amount = yield(total)

var accum = create_accumulator(50)
print(accum.resume(10)) #prints 60
print(accum.resume(-2)) #prints 58
```

There is a slight complication when yield(value) is the first yield of a coroutine, in which case it has to return the GDScriptFunctionState AND the value. This is handled by yielding an additional time. That is,

```
func g():
	yield("hello")
```
behaves AS IF it were
```
func g():
	yield()			#yields GDScriptFunctionState instance
	yield("hello")		#yields "hello"
```
Ultimately, this is an implementation detail and it behaves largely as users would expect once they understand that pattern of use.
```
var co = g()
print(co.resume()) #prints "hello" and finishes if it is resumed again
```

This brings me to coroutine states. There are three functions for querying the important states: is_resumable(), is_blocked() or is_completed().
The function resume() will fail if called on a blocked (more later) or completed coroutine. A coroutine is completed after it returns. It will never be possible to resume() it again after that.

A coroutine is blocked whenever it executes the two argument version of yield [ie. yield(obj, "signal")]. It yields to the caller but only the signal can resume it. This resolves a reported issue in which a function that yielded and is waiting on a timer will stop waiting if resume()d. A blocked coroutine can become unblocked if it returns after the signal wakes it up (in which case it is_completed()) or if it subsequently does a yield() or yield(value) in which case it will become resumable and is_resumable() will return 'true'.

I have added a new signal to the coroutine (in addition to "completed") called "unblocked" to manage transitions out of the blocked state. It will be fired when a coroutine transitions from 'blocked' to 'completed' or 'resumable'. If it yields or returns a value at that point, it will be available as the signal's argument (and thus as the return value of the yield(obj, "signal")).

Because the two argument version of yield is so different one really needs a way to talk about it and find it easily in code (especially with yield(value) being available as well). Therefore I have introduced 'yield_await' as a synonym for it since it yields and waits on a signal. The two argument version of yield still works.

While it took many words to explain, the changes to the code are quite localized.
The most modified files are:
gdscript_function.h 
gdscript_gunction.cpp
I needed to change the GDSCriptFunctionState class the most and the GDScriptFunction::call() method in a few key places.

Other changed files are:
gdscript_parser.cpp: to accept yield(value) and yield_await
gdscript_compiler.cpp: to deal with yield(value) when writing the bytecode
gdscript_tokenizer.h: to declare yield_await as a valid token
gdscript_tokenizer.cpp: to add yield_await to the _kws array
gdscipt.cpp: to add 'yield_await' to the list of reserved words so that the editor will highlight it properly

I wanted to rewrite neat test cases but I ended up just including the test project file I was using when working on the changes.
It is kind of messy but it does show what the update can do and how one could use it.
I have included it as a zipped file with the PR.

[coroutine_test.zip](https://github.com/godotengine/godot/files/3276099/coroutine_test.zip)

Thanks for making Godot and I hope this is found to be useful to the project.

### CODE REVIEW

**Comment by Xrayez** [comment]
The only "problem" I have with `yield` is the following case:
```gdscript
func _ready():
	var ret = yield(obj, 'some_signal')
	 # OK
	do_something_with(ret)
```
```gdscript
func _ready():
	var ret = some_function()
	
	# FAIL, GDScriptFunctionState is passed, have to use:
	#
	# ret = yield(ret, 'completed')
	#
	# or even this (as the function may yield several times):
	#
	# while ret is GDScriptFunctionState:
	# 	ret = yield(ret, 'completed')
	do_something_with(ret)
	
func some_function():
	# Suppose this function may or may not yield too
	var ret = yield(obj, 'some_signal')
```
Is this what `yield_await` would able to solve?

**Comment by busy8** [comment]
@Xrayez 

Hi.

**yield_await** is just **another name** for **yield(ojbect, "signal")**. It does the same thing as that did before. This new keyword can be considered an optional aspect of the PR. However I also added the ability to yield a value just as you can return a value since current GDScript doesn't allow this, see: https://github.com/godotengine/godot/issues/1397. Since there are now three versions of yield [0, 1, or 2 arguments] and the third one [the signal one] is rather different in behavior, I gave it another name: yield_await (the original syntax still works). 

I think the PR may address your use case, however, I'm not 100% sure. Yielding and waiting for a signal with yield(object, "signal") [aka yield_await] has implications and these are handled by the PR. Now, as explained, the returned GDScriptFunctionState does not invalidate on resume() anymore with the PR. But when a function does yield(obj, "signal") [aka yield_await] it returns to the caller and is "blocked" so that it cannot be resumed directly until the signal fires and it does an ordinary yield or a return. With this patch, the caller can synchronize with this state change by yielding, itself, for the "unblocked" signal of the yielded function. [This is similar to how the "completed" signal is used currently to detect termination]

I'll give a mini example (which has to be contrived as snippets tend to be).
You can write a function like this:
```
func wait_a_little(timer):
	yield(timer, "timeout")
	var msg = yield("Time elapsed: ")
	print(msg)
```
Then you could create it and know when it has hit the yield(value) by having the caller yield for its "unblocked" signal.
Example:
```
func _ready():
	print("_ready starting")
	var w = wait_a_little($Timer)
	#w is blocked waiting on the signal because of yield(obj, "signal") aka yield_await
	$Timer.start()
	var ret = yield(w, "unblocked")
	print(ret)
	w.resume("\tYou may now enter")
	print("_ready finished")
```
This will print
```
_ready starting
Time elapsed: 
	You may now enter
_ready finished

```
Hope that helped to clarify.

**Comment by Xrayez** [comment]
Yeah, thanks for elaborating, I might as well checkout this PR later and see if this could really solve my use case, because I'm finding myself doing such pattern a lot (yielding to drawing signals).

`yield_await` might as well be renamed to `await` to further distinguish them better imo, but not sure how would this be confusing in terms of other languages.

**Comment by busy8** [comment]
> Yeah, thanks for elaborating, I might as well checkout this PR later and see if this could really solve my use case, because I'm finding myself doing such pattern a lot (yielding to drawing signals).
> 
> `yield_await` might as well be renamed to `await` to further distinguish them better imo, but not sure how would this be confusing in terms of other languages.

I very much considered `await` too but, in truth, `yield(obj, "signal")` does double duty. It yields to the caller, but doesn't allow the caller to resume() it [the signal must do so]. So if `yield(obj, "signal") is the first yield encountered in a function's execution it created a coroutine and returns a GDScriptFunctionState just like yield() and yield(value) do. So I thought keeping yield in the name as in `yield_await` would retain that conceptual link and make things easier to explain.
That is:
1) yield creates a coroutine
2) yield_await is a yield that also awaits [ie delegates resumption to] a signal

**Comment by busy8** [comment]
Here's a brief summary of what this PR does:
1) Functions are able to use `yield(value)` to yield a value that becomes the return value of resume.
2) yield(obj, "signal") can be invoked using yield_await(obj, "signal") [no functional change]
3) yield_await-ing puts coroutine in a blocked state which will cause direct coroutine.resume() to fail
4) Trying to resume a coroutine that has completed (i.e the function returned) will also fail
5) The "unblocked" signal can be used to used to detect when a coroutine exits the blocked state
6) State can also be queried with GDScriptFunctionState's is_blocked(), is_completed() or is_resumable()
7) To make all of the above possible resume() no longer invalidates the GDScriptFunctionState. A state is created only when the first yield is encountered during execution.

**Comment by Xrayez** [comment]
Just wanted to report that this PR doesn't seem to break anything in my existing project. Mostly yielding to signals.

**Comment by busy8** [comment]
I updated the summary post with a few more details for clarity. 
It got a little beefier but I think it's for the better.

**Comment by busy8** [comment]
One final note the motivation behind this:

I set out to do two things that I wanted, and which other people wanted (from issue list):
1) Be able to yield a value
2) Make it impossible for resume() to force-resume functions that did yield(object, "signal") but also make it convenient for such functions to indicate that, "I'm done waiting on signals, you can resume me again now". 
*****************************
Point 1) [ yield(value) ]

Consider a very simple generator that generates the next value of a range of integers less than an "end" value each time it is called. Without 1), you'd probably need a class to store each value generated since they can't be yielded directly. If you have to write a class, you could skip using yield() and write an ordinary method that updates the class variable (say 'counter') and returns instead of yields.
With the ability to yield a value this is pretty easy to do:
```gdscript
static func gen_range(end):
	var i = 0
	while i < end - 1:
		yield(i)	#This is NEW, you can't do it in Godot 3.1!
		i = i + 1
	return i
```
Note that the function is even **static** because it doesn't need access to instance variables of the class of which it is a part. It remembers the value of its local variables across yields. The loop is written that way so that the function returns the final value last instead of null. It can be used like this:
```gdscript
var r = gen_range(3)
while !r.is_completed():
	var i = r.resume()
	#do something useful with i
	print(i)
```
That'll print 0, 1, 2.
****
Point 2) [ blocking and the "unblocked" signal ]

This is about making communication between functions that yielded more harmonious even while dealing with the "wrinkle" introduced by waiting for signals with yield(obj, "signal") [for which I introduced the alternative keyword 'yield_await' as JUST another name]. Consider a function like this which can be written in current GDScript:
```gdscript
func wait_then_do():
	$Timer2.start()           #assume class has a timer $Timer2
	yield($Timer2, "timeout") #waiting for "timeout" so makes no sense to be able to resume it here
	print("doing something very interesting")
	yield()                  #it'll yield and can be resumed here; how will caller know?
	print("thanks for resuming me, bye!") 
	#imagine it does more stuff
	return                  #is complete after this
```
So let's say another function calls wait_then_do(), gets the state and wants to resume it after it does the second yield (hopefully you see why I want to call the first yield, 'yield_await'.) Quite a bit of machinery will have to be written in the current language. TBH, even then, I'm not quite sure how it would be done.

In today's GDScript, if you call resume() on the state right after calling `wait_then_do()` that might force it to forget it should be waiting on a signal ( https://github.com/godotengine/godot/issues/28942 ) so you have to wait, somehow. But once it does hit the second yield, the state the caller received when it initially called `wait_then_do()` becomes invalid so it can't be resumed with that! You'd have to retrieve the new one somehow. (good luck)

With this PR, you'd do:
```gdscript
var co = wait_then_do()
yield(co, "unblocked")   #aka yield_await
co.resume()
```
That's it.
(If co is a class member another option would be polling `!co.is_blocked()` in _process.)
This makes something that users can already express, into something that works reasonably.

To make all of this work seamlessly, I had to change user-facing behavior of resume() and the interface of the returned GDScriptFunctionState class. That is, there's no invalidation any more by resume() and there's the added ability to ask the state whether it's completed, blocked, etc. This refactor is responsible for most of the lines of code changed, more so than 1) and 2) which required it to work.

Whew, I think explaining things to humans is harder than doing it for the computer, lol.
I've covered the why, how, etc. so I'll probably be going pretty quiet until attention is turned to this again for merging (by 4.0 possibly), *wink.

**Comment by girng** [comment]
needs to be reduced, and new pr imo. this pr is too confusing

**Comment by busy8** [comment]
> needs to be reduced, and new pr imo. this pr is too confusing
> higher chance to be seen by lead devs too. (not discrediting you, great work, just saying from an outsider's perspective)
> 
> lead devs want to see real world use-cases, and how the pr will fix them. not explanations for newbies

Thanks for the input, both the compliment and criticism. 

I understood there is always a risk that PRs don't get accepted and the effort/time I expended so far was with recognition of that risk. I will not be directing any more attention to trying to get this merged. If the majority of users are satisfied with things as they are then there really isn't the general need that I thought existed.

Closing.

**Pull request closed without merging**
