### PR TITLE
Use a size Vector for adjusting the size of Rectangles and Boxes

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, to adjust the size of a `RectangleShape2D` or a `BoxShape3D` you modify the `extents`, which are half the size of the rectangle or box. This is confusing for the user. Furthermore, although a `BoxMesh3D` (a `CubeMesh` in 3.2) uses a `Vector3` for size, a `CSGBox3D` uses three `float`s: `width`, `height` and `depth`.

This PR allows a users to adjust the size of a `RectangleShape`, a `BoxShape`, a `BoxMesh` and a `CSGBox` consistently using a `Vector` property called `size`.

Part of #16863.

### CODE REVIEW

**Comment by aaronfranke** [comment]
It still says "Extents" in the corner when dragging the handles, I think this is not intentional:

Screenshot from 2020-12-08 06-13-53

For CSG, it says the name of which handle you are manipulating, but then the value is the size vector:

Screenshot from 2020-12-08 06-15-51

**Comment by madmiraal** [comment]
Updated to correctly display "Size" and the `Vector3` in the corners.

**Comment by aaronfranke** [comment]
This code looks good, and I agree that having a size property makes sense. It's 100% an improvement for CSG.

However, there is an argument for having both `size` and `extents` properties. There are a lot of places in this code where `size / 2` is used. More importantly, while a `Rect2` and `AABB` have their position defined as the negative corner (top-left for `Rect2`, bottom-north-west for `AABB`), the position for `BoxShape3D`, `RectangleShape2D`, and CSG nodes is defined as the center, not the corner. To find the edges/corners of a `Rect2` or `AABB`, you can take the position for one edge/corner, and the position plus size for the others. To do the same with `BoxShape3D`, `RectangleShape2D`, and CSG nodes, you would need to take the position and add/subtract the extents (half the size). So `BoxShape3D` currently behaves like [Unity's `Bounds`](https://github.com/godotengine/godot-proposals/issues/1528#issuecomment-696452411).

Anyway, I would like @akien-mga's feedback on this (and anyone else who wants to chime in).

**Review by akien-mga — APPROVED** [review]
We discussed this in a PR review meeting and agreed with the change.

(Half) extents are still used internally for performance, but it makes sense to standardize everything in the higher level API around sizes.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
