### PR TITLE
Allow negative coordinates in `AStarGrid2D`

### LINKED ISSUE #6373: Allow negative coordinates in `AStarGrid2D`
### Describe the project you are working on

This can be useful when combining `TileMap` and `AStarGrid2D`. I discovered this inconvenience while learning `AStarGrid2D`. I also simplified the implementation in the demo:

https://github.com/godotengine/godot-demo-projects/pull/861/files#diff-db94d2085d2c1c2f7f7a489bff4842b0bc7fb04560ca03127032faa1c56a99d5R18-R20

### Describe the problem or limitation you are having in your project

`AStarGrid2D` does not support negative cell coordinates, unlike `TileMap`. You can use `offset`, but this is less convenient.

<details>
<summary>Simple algorithm (non-negative coordinates)</summary>

```gdscript
var size := get_used_rect().end

var a_star := AStarGrid2D.new()
a_star.size = size
a_star.default_compute_heuristic = AStarGrid2D.HEURISTIC_CHEBYSHEV
a_star.default_estimate_heuristic = AStarGrid2D.HEURISTIC_CHEBYSHEV
a_star.update()

var point_a: Vector2i
var point_b: Vector2i

for i in size.x:
    for j in size.y:
        var id := Vector2i(i, j)
        match get_cell_atlas_coords(0, id).x:
            Tile.OBSTACLE:
                a_star.set_point_solid(id)
            Tile.POINT_A:
                point_a = id
            Tile.POINT_B:
                point_b = id

for point in a_star.get_point_path(point_a, point_b).slice(1, -1):
    set_cell(0, point, 0, Vector2i(Tile.PATH, 0))
```

[gd4_astar_test.zip](https://github.com/godotengine/godot-proposals/files/10849073/gd4_astar_test.zip)

</details>

<details>
<summary>Using <code>offset</code> for negative coordinates</summary>

```gdscript
var used_rect := get_used_rect()
var offset := used_rect.position

var a_star := AStarGrid2D.new()
a_star.size = used_rect.size
a_star.offset = offset
a_star.default_compute_heuristic = AStarGrid2D.HEURISTIC_CHEBYSHEV
a_star.default_estimate_heuristic = AStarGrid2D.HEURISTIC_CHEBYSHEV
a_star.update()

var point_a: Vector2i
var point_b: Vector2i

for i in range(used_rect.position.x, used_rect.end.x):
    for j in range(used_rect.position.y, used_rect.end.y):
        var id := Vector2i(i, j)
        match get_cell_atlas_coords(0, id).x:
            Tile.OBSTACLE:
                a_star.set_point_solid(id - offset)
            Tile.POINT_A:
                point_a = id
            Tile.POINT_B:
                point_b = id

for point in a_star.get_point_path(point_a - offset, point_b - offset).slice(1, -1):
    set_cell(0, point, 0, Vector2i(Tile.PATH, 0))
```

[gd4_astar_test_2.zip](https://github.com/godotengine/godot-proposals/files/10849091/gd4_astar_test_2.zip)

</details>

As you can see, the same cell in `TileMap` and `AStarGrid2D` has different cell coordinates. This creates a certain inconvenience, because you have to remember which coordinates you need at some point. When using the `offset` property, remember that `get_point_path()` returns transformed coordinates and `get_id_path()` returns raw coordinates. If you use a separate `offset` variable, you must offset (with a plus sign) the coordinates returned by `get_point_path()` as well.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a new `rect` (or `region`) property that allows you to specify a rectangular region for pathfinding. Make the `size` property an alias to `rect.size`, for compatibility.

<details>
<summary>Negative coordinates support in <code>AStarGrid2D</code></summary>

```gdscript
var used_rect := get_used_rect()

var a_star := AStarGrid2D.new()
a_star.rect = used_rect
a_star.default_compute_heuristic = AStarGrid2D.HEURISTIC_CHEBYSHEV
a_star.default_estimate_heuristic = AStarGrid2D.HEURISTIC_CHEBYSHEV
a_star.update()

var point_a: Vector2i
var point_b: Vector2i

for i in range(used_rect.position.x, used_rect.end.x):
    for j in range(used_rect.position.y, used_rect.end.y):
        var id := Vector2i(i, j)
        match get_cell_atlas_coords(0, id).x:
            Tile.OBSTACLE:
                a_star.set_point_solid(id)
            Tile.POINT_A:
                point_a = id
            Tile.POINT_B:
                point_b = id

for point in a_star.get_point_path(point_a, point_b).slice(1, -1):
    set_cell(0, point, 0, Vector2i(Tile.PATH, 0))
```

[gd4_astar_test_new.zip](https://github.com/godotengine/godot-proposals/files/10849101/gd4_astar_test_new.zip)

</details>

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

PR: godotengine/godot#74106.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You can use the `offset` property as shown above or use a separate `offset` variable. But this is inconvenient because you get different cell coordinates for `TileMap` and `AStarGrid2D`.

In some cases you can use a simpler algorithm version if you can exclude negative coordinates. But this can be inconvenient when procedurally generating open worlds. This can also be inconvenient when implementing a chunk system.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be done with an add-on.

### PR DESCRIPTION
**Pull request by dalexeev**
Closes godotengine/godot-proposals#6373.

### CODE REVIEW

**Comment by dalexeev** [comment]
I don't think this breaks compatibility in any way.

**Review by Chaosus — APPROVED** [review]
Make sense to me (we could consider the `size` to be a deprecated property).

**Comment by dalexeev** [comment]
Yes, I wanted to add a warning. Which name is better here: `rect` or `region`?

**Comment by Chaosus** [comment]
> Which name is better here: rect or region?

`region` sounds better (at least for me).

**Comment by Chaosus** [comment]
Alternatively to this approach you can implement the `position` property, then position + size could be used to replicate the region rect and nothing needs to be made deprecated.

**Comment by dalexeev** [comment]
> Alternatively to this approach you can implement the `position` property, then position + size could be used to replicate the region rect and nothing needs to be made deprecated.

I thought about it, but in my opinion a single property is better since you can use `Rect2` methods (and `end` property) instead of constructing it from `position` and `size`. Also when used with `TileMap` you can do

```gdscript
a_star.region = tile_map.get_used_rect()
```

instead of

```gdscript
var used_rect := tile_map.get_used_rect()
a_star.position = used_rect.position
a_star.size = used_rect.size
```

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
