### PR TITLE
Change logo in the About dialog box (return Godot's teeth)

### PR DESCRIPTION
**Pull request by dalexeev**
I understand that this change is not that important, but programmers are famous for their perfectionism. :smiley: 

`editor/icons/Logo.svg` (before and after):

* The logo in the image has been replaced with the canonical one (`icon.svg`).
* SVG is compressed using `svgcleaner` as recommended.
* I don’t know how it happened, perhaps when removing the outline, someone also removed this detail of the logo.

`icon.svg`:

`main/splash.png`:

### CODE REVIEW

**Comment by YeldhamDev** [comment]
The SVG file should end with a new line.

**Comment by dalexeev** [comment]
Check failed due to missing `\n` at the end of the SVG file.

**Comment by Calinou** [comment]
> Check failed due to missing \n at the end of the SVG file. This is how svgcleaner generated it. I added \n manually.

There's a flag to append a newline in svgcleaner Git, but it has yet to be added in a tagged release with precompiled builds. See https://github.com/RazrFalcon/svgcleaner/issues/221.

**Comment by Riteo** [comment]
Why not keeping the outline altogether? Why has it been removed in the first place?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
