### PR TITLE
Fix code editor Replace tool to work with 'Selection Only' option

### LINKED ISSUE #34787: Search and Replace tool from the Script editor doesn't filtrer by selection.
**Godot version:** 3.1.2.stable.official

**OS/device including version:** Windows 7 SP1, Edit: also Ubuntu.

**Issue description:** When use the "Replace..." Tool from the text editor (in menu Search), the tool does not limit the search to the selection, even with "Selection Only" marked. Happens either replacing oneor all instances of the word, that the search begins at the start of the file.

**Steps to reproduce:** 
1 - Open a Script. (The main node in the example file has one)
2 - Open the toon in Menu Search -> Replace...
3 - Type the words to search and replace.
4 - Mark selection only.
5 - Select the desired section of the text.
6 - Click either replace or replace all.

**Minimal reproduction project:** 
[search_and_replace_bug.zip](https://github.com/godotengine/godot/files/4020255/search_and_replace_bug.zip)

### PR DESCRIPTION
**Pull request by mrushyendra**
Ensures that when the `Selection Only` option is selected, the Replace tool replaces occurrences of the search phrase only within the selected region, and in order of occurrence.

Old Version: Selecting `Replace` causes phrases to be replaced in a haphazard fashion, and without regard to the selected region.
selectionOld

New Version: `Replace` is limited to the selected region, and replacements happen in order.
selectionNew

Closes #34787

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by belzecue** [comment]
What does "cherry-picked for 3.2.2" mean?  Does it mean the fix will be back-ported to 3.x?  Because I'm running 3.3.2 stable on Linux and this "selection only" bug continues to be a big frustration.

**Comment by Calinou** [comment]
> What does "cherry-picked for 3.2.2" mean? Does it mean the fix will be back-ported to 3.x? Because I'm running 3.3.2 stable on Linux and this "selection only" bug continues to be a big frustration.

It means ,the fix is available in 3.2.2 and later, which includes Godot 3.3 and the `3.x` branch.

**Comment by belzecue** [comment]
My mistake.  It's working fine in 3.3.2.  I made an invalid assumption about how it works and was expecting the "total matches" figure to change to only show the match count within the selection.  Also, I'm not used to having the active selection nulled upon retyping the search text, but I will get used to it now that I understand what's going on.  Thanks.

**Pull request merged**
