### PR TITLE
Fix some bugs in shader creation dialog

### PR DESCRIPTION
**Pull request by Chaosus**
+ Fixed a typo
+ Removed small invalid code part in `_validate_path` related to ScriptServer (unrelated to Shader system)
+ Fixed *.res files which not being accepted to save as shader before

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Chaosus** [comment]
Ah, I wished to finish that's why I marked it [WIP] but ok..

**Comment by akien-mga** [comment]
Ah I didn't see the title edit. You can mark as draft to prevent merge when it's not ready yet.

**Comment by Chaosus** [comment]
> You can mark as draft to prevent merge when it's not ready yet.

Ok, I take a note to myself

**Pull request merged**
