### PR TITLE
Fix text search bar not correctly switching from replacing to just searching

### PR DESCRIPTION
**Pull request by YeldhamDev**

### CODE REVIEW

**Comment by akien-mga** [comment]
`git blame` gives #31329 introducing this check, CC @KoBeWi.

**Comment by YeldhamDev** [comment]
From my tests, the changes introduced in that commit are still functional.

**Comment by KoBeWi** [comment]
VS Code works this way.

With your PR, when you press Ctrl + F and again Ctrl + R, the text in search field will change. With my behavior you can freely switch between the fields, but the text is still fetched when you select something, which is better and more useful IMO.

I'm against this PR >_>

**Comment by YeldhamDev** [comment]
@KoBeWi The only thing this PR does is hide the replace bar together with its buttons, I don't see how leaving a pointless `LineEdit` around can be useful.

I couldn't find any other change in behaviour with or without my commit. I could have just missed something, can you point out where?

**Review by KoBeWi — APPROVED** [review]
Ok, nevermind .-.
It actually works ok, I did a mistake while testing previously.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
