### PR TITLE
add pitch_mix to AudioEffectPitchShift

### PR DESCRIPTION
**Pull request by Th0rDaW**
Hi, this is my very first pullrequest. Hopefully everything is ok. I will take any advice to do better future pull requests. If there is a better solution to achive the mixin goal for the pitchshift-effect, please say and i will give it a try.
I was in need for a mix for the PitchShift effect to create a robotic voice and i don't want to use two seperate AudioStreamPlayers. It was not easy for me to understand the code and to abstract what i need to do, but at least it seems to work.
audioeffectpitchshiftmix

### CODE REVIEW

**Comment by reduz** [comment]
I will eventually add a graph for audio processing, where you will be able to do this properly

**Comment by akien-mga** [comment]
> I will eventually add a graph for audio processing, where you will be able to do this properly

Is this covered in the [changes made for 3.2](https://godotengine.org/article/godot-32-will-get-new-audio-features), or not yet?

**Comment by aaronfranke** [comment]
@Th0r12356 Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

I'm not sure what @reduz means by adding a graph for audio processing, but here's what `AudioEffectPitchShift` currently looks like in the inspector. There is no `pitch_mix`, but there are also more properties than before, which might cover the use case (I'm not an audio expert myself).

Screenshot from 2020-05-13 03-42-04

**Comment by aaronfranke** [comment]
This PR has not received any new commits for over a year and is abandoned, closing.

**Pull request closed without merging**
