### PR TITLE
Use PascalCase file names for editor icons

### PR DESCRIPTION
**Pull request by Calinou**
As discussed on IRC with @YeldhamDev and others, using PascalCase file names without any conversion step is less confusing to new contributors.

I've checked the editor and couldn't find any missing icons, but I'd like further testing :slightly_smiling_face:

## Renaming script

```python
#!/usr/bin/env python3

# Save this file to `editor/icons/move.py`.

import os
import sys

filename = sys.argv[1]

os.rename(filename, filename[5:-4].title().replace("_", "") + ".svg")
```

### Usage

```bash
cd editor/icons
for icon in *.svg; do
  ./move.py "$icon" &
done
```

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Not finding the recently added icons in #36489.

**Comment by Xrayez** [comment]
[Editor icons](http://docs.godotengine.org/en/latest/development/editor/creating_icons.html) doc page will need to be updated accordingly.

**Comment by Calinou** [comment]
@YeldhamDev Fixed, I forgot to rebase with the latest changes before opening this PR.

**Comment by Xrayez** [comment]
Is it possible to preserve compatibility with the icons having the old naming convention? Just saying that non-native Godot modules can define their own icons. I might be the only one currently using this feature though. 😛

Actually found some module: https://github.com/bruvzg/gdsdecomp/tree/master/editor/icons

**Comment by Calinou** [comment]
@Xrayez The builder can be modified here on the module side: https://github.com/bruvzg/gdsdecomp/blob/master/editor/icons/SCsub#L49

**Comment by akien-mga** [comment]
Seems good, as we discussed on IRC the force snake-casing of the matching type names was error prone, inconsistent and overall unnecessary (even though we do like our lower case filenames, but hey, we managed to live with `doc/classes/`).

I don't think keeping compatibility with old names is necessary, you'll have plenty of things to change in your modules already for 4.0, renaming a few SVG shouldn't be a problem.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YeldhamDev** [comment]
This page should be updated: https://docs.godotengine.org/en/latest/development/editor/creating_icons.html

**Pull request merged**
