### PR TITLE
HTML5: this.rtenv.callMain is not a function when using latest-upstream backend

### LINKED ISSUE #31297: HTML5: this.rtenv.callMain is not a function when using latest-upstream backend
**Godot version:**
master (https://github.com/godotengine/godot/commit/3418f76a9eab9f496e5b26310bd3bc1125b8119b)

**OS/device including version:**
Arch Linux

**Issue description:**
This error shows when loading the .pck with Chromium
console log:
```Swift
test.html:246 this.rtenv.callMain is not a function
displayFailureNotice @ test.html:246
```

**Steps to reproduce:**
```Swift
scons p=x11 bits=64 target=release_debug tools=yes use_llvm=yes use_lld=yes use_thinlto=yes -j 8
./emsdk install latest       OR:      ./emsdk install latest-upstream
./emsdk activate latest               ./emsdk activate latest-upstream
source ./emsdk_env.sh
scons p=javascript target=release_debug tools=no -j 8
python3 -m http.server
http://localhost:8000/test.html
```

Tested projects: Solus Sphere (https://github.com/HugeGameArtGD/Solus-Sphere) and material demo (both GLES2)

### PR DESCRIPTION
**Pull request by Mellondill**
Added needed changes for normal compiling with emscripten 1.38.41 and later

*Bugsquad edit:* Fixes #31297.

### CODE REVIEW

**Comment by LinuxUserGD** [comment]
Thanks for fixing https://github.com/godotengine/godot/issues/31297 :+1:

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
