### PR TITLE
Allow exporting vars by specifing the resource class Fix #6719

### LINKED ISSUE #6719: Godot program crash.
**Operating system or device - Godot version:**
Windows 10, v2.1.stable.official

**Issue description** (what happened, and what was expected):
If you add this code into you script. 

`Export var path = Path `

or some like that it will crash godot if you click on a another node in the tree or try to save. and if you save this as your start up scene it will crash godot every time you open it even if your not doing anything.

**Steps to reproduce:**
Open godot create a script add this code `Export var path = Path ` (Please note it's not just the path one it will crash if you use other ones to.) and click on a node in the tree view

**Link to minimal example project** (optional but very welcome):
[Bug.zip](https://github.com/godotengine/godot/files/512528/Bug.zip)

### PR DESCRIPTION
**Pull request by Faless**
`export var tex = Texture` will now export a Resource variable of type `Texture` (initialized to null).
Fixes #6719 . Closes #6730

### CODE REVIEW

**Comment by eska014** [comment]
> ```
> export var tex = Texture
> ```

This should either give an error or export a `GDNativeClass` object defaulting to `Texture`. Exporting `GDNativeClass` objects isn't implemented and is probably confusing to beginners, so I prefer just displaying an error.
But having it export a `Texture` object is inconsistent.

**Comment by bojidar-bg** [comment]
I agree that it shouldn't be done that way, since we already have `export(<type>) var x` for this

**Comment by Faless** [comment]
> This should either give an error or export a GDNativeClass object defaulting to Texture

We had a brief discussion on the dev channel and @reduz seemed to prefer this behavior over throwing an error. But I might have misunderstood
The main problem is that as of now writing that code and saving (even by mistake) on an instantiated script will crash the editor

**Comment by akien-mga** [comment]
I think you had misunderstood @reduz:

> [15:57:53] `<fales`> Anyway, I have a fix, but the question is if reduz wants it to actually work that way (although while "export(Texture) var t" is ok, I think "export var t = Texture" it's confusing if compared to "export var t = 0" which is different from "export var t = int")
[15:58:42] `<reduz`> fales, probably makes more sense to just make it work as export(Texture), the other is not very logical
[15:59:16] `<reduz`> the fact you came up with it somehow and no one did in years is proof of that :P

What he meant (in my understanding) was not to "make it work like export(Texture)", but to make that *just* export(Texture) works, the other one shouldn't as it's too weird a syntax.

**Comment by Faless** [comment]
> What he meant (in my understanding) was not to "make it work like export(Texture)", but to make that just export(Texture) works, the other one shouldn't as it's too weird a syntax.

Agreed. I must have misunderstood.
`export var t = Texture` is indeed very weird, we should go for #6730

**Comment by bojidar-bg** [comment]
@Faless Given that you've agreed, I guess I'll just close it :smile:

**Pull request closed without merging**
