### PR TITLE
Fixed bug where Viewport would be cleared with clear_mode NEVER

### PR DESCRIPTION
**Pull request by awsker**
SubViewport would clear with the default background color even when clear_mode was set to VIEWPORT_CLEAR_NEVER.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by awsker** [comment]
Yeah, I should've done this work in a branch. Not too familiar with git. The squash seems to have become its own commit instead. Maybe I shouldn't have merged the changes from master. It's a complete mess. Let's just say me and git are not on friendly terms.

**Comment by akien-mga** [comment]
Yes you should not merge `master` back into your branch after rebasing. You can **rebase** on top of `master` but not **merge**.

If you haven't done so, start with:
```
git remote add upstream https://github.com/godotengine/godot
git fetch upstream
```

Then, on your local `master` branch (used for this PR):
```
git rebase -i upstream/master
# Replace "pick" with "fixup" for commits 2, 3, and 4, confirm
git push --force origin master
```

**Comment by awsker** [comment]
You know what, I'll start over and do it right. It'll be good for me to get an understanding of the workflow. I'm sorry for the inconvenience.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/60705.

**Pull request closed without merging**
