### PR TITLE
Update AUTHORS.md

### PR DESCRIPTION
**Pull request by JosiasAurel**

### CODE REVIEW

**Comment by JosiasAurel** [comment]
i want to start participating in the development of my favorite game engine and i wish to know exactly where i can start thanks in advance

**Comment by JosiasAurel** [comment]
if there is anything i can start doing i will do i have downloaded the source code and Added some mods i will upload it as soon as i finish :)

**Comment by novhack** [comment]
This is not how authors are added. :D
"this file aims at listing the developers who contributed significant patches to this MIT licensed source code. "Significant" is arbitrarily decided, but should be fair".
So start coding and then you will be maybe eventually added as one of the authors.

**Comment by groud** [comment]
Indeed, that's not how we add authors. 
First you have to contribute, and after a significant amount of contributions (around 10 commits I think), you will be added automatically to the next author.md file update.

**Comment by groud** [comment]
> i wish to know exactly where i can start thanks in advance

Regarding that part, make sure to read that first: [https://docs.godotengine.org/en/3.1/community/contributing/ways_to_contribute.html#contributing-code](https://docs.godotengine.org/en/3.1/community/contributing/ways_to_contribute.html#contributing-code)

**Pull request closed without merging**
