### PR TITLE
VisualScript Modules

### LINKED ISSUE #16: Groups Nodes replace Functions in Visual Scripting
Groups Nodes replace Functions
---
Grouping of Nodes in a chain should be allowed to simplify the process of creation of Node Units and increasing reusability of parts of the Visual Scripts.

image
Quick Mockup.

> _Group Nodes should be stored as custom Nodes that are accessible from the same drop down for searching the Nodes and also allow for saving and loading groups as resources for use as custom nodes all across the project._

Probably even have a default folder where we can place all the Grouped Node(Custom Node) Resources that we want to be accessible across the project as custom nodes, automagically.
This would remove the need to newbie users to learn how to create Tool Scripts.

Details
---
The Groups will be simple and clean and will act like bookmarks that will take us to the respective Group Node Structure we double click on. 

The Groups will be a much simpler concept compared to functions but will technically use the same structure/codebase. It will also the first step towards addition of Unified Visual Script editor Graph.

Being able to save these can come extremely handy, such as having a module for simple visual script functions required and even Visual Shader node groups.

### PR DESCRIPTION
**Pull request by swarnimarun**
I am not quite sure about its mergeability yet, my first rebase had issues because I tried rebasing with all the commits originally(even this one had issues likely due to formatting changes in the refactor PR before merge), and the current commit history needs clean up as well.

So I believe it needs a bit more of testing and fixes if there is an issue, also because of the changes to the Window GUI which might not need some of the old changes anymore. Will make it a proper PR as soon as I can say it's mergeable.

Created this so we can start reviewing.

Fixes: https://github.com/godotengine/godot-visual-script/issues/16

### CODE REVIEW

**Comment by fire** [comment]
Tell me when it's ready for review.

**Comment by fire** [comment]
When you're ready, rebase and ping me.

**Comment by swarnimarun** [comment]
@fire ping. 
Done. :)

Only things left were the breakpoints and type-guessing requiring some fixes. I had to delay it as I happened to get my build to crash, and had to do some bug hunting over the weekdays to figure it out. Everything seems fine now.
Though I totally don't expect it to be bug-free (though I hope it's only a few lol 🤞).
And I also have to push a PR or two for some older bugs and issues which I can do as soon as we get this one done. As I am expecting some of them to be fixed by default in this PR.

Also @akien-mga or @Calinou,
While we are at it, is there a way we can change `Variant::is_null()` method to have a better name, like `is_object_null()`. This one had cost me an entire weekend when I was initially patching stuff because I thought it will check if Variant is of type NIL.
If there is room for discussion I can create an issue thread or get on IRC, really found it way too annoying.

I don't think the Variant API is publicly exposed other than "maybe" GDNative IIRC.

**Comment by fire** [comment]
Started review. Will take me some time.

**Comment by fire** [comment]
I apparently didn't compile correctly. Here's the second round.

1. The new module nodes are put in the wrong place
image
1. Nil means any node
image
1. Once in module editing mode, no clear way of showing how to return.
2. How do you save VS Modules? Loading appears to work.

**Comment by swarnimarun** [comment]
> "I noticed all the _process and _physics_process bindings are gone when clicking on the new functions."

Wait what...

> "Dragging a function from the left bar crashes Godot."

I get a feeling I messed up something in the rebase.... Or it's a multi-window issue that I didn't fix.

On it.

**Comment by swarnimarun** [comment]
image
Hmm...

Alright! let me do a clean build just in case.

**Comment by swarnimarun** [comment]
test_module_pr
Clean, build also worked fine for me :(

Though, did notice I forgot to change/improve the placement code for nodes when inside module.

**Comment by swarnimarun** [comment]
As for the popup on the module change button, it's changed because of changes to master, but yeah makes sense will make it more like how it used to be.

And yeah the save option does seem non-obvious.
image


Aside: Fixed Nil to Any and looking at what probable reason their might for the crash for dragging function to visual script graph.

**Comment by fire** [comment]
Will wait for the push. Good night.

**Comment by fire** [comment]
Some engine core changes were made, I asked for a review round on discord, but I need a updated branch.

**Comment by swarnimarun** [comment]
This should fix most of the UX and things that were annoying, couldn't reproduce the function crash bug, but I did make some changes as per my best guesses(if it still happens mind throwing the crash report/log).

Though I did end up finding bugs and annoyances in the Engine itself, like on a Dual Monitor setup new subwindows open on the primary display and there is no way to override it from outside Window class as far as I can see. So popups are slightly broken on dual monitors. And some more similar stuff.
I will create an issue on GitHub and then see if I need to submit a patch for it or if there is already a patch in works.

Also, I think a simpler solution is to just have popups and dialogs be in the same Window. Will have to write some extra code in Window class for it, or create a subclass that extends the functionalities of the Window class.

**Comment by fire** [comment]
@swarnimarun was unable to work on this due to personal reasons, so I'll see if I can update it.

**Comment by DavidCambre** [comment]
HI @swarnimarun @fire ,

I'm sorry to say,
I have been trying to test this build. It always crashes when trying to open or save.
Did not even get far enough to drag in one module in the script.

I did try to cherry-pick this after implementing PR #49749. The conflicts are minimal to fix and has similar issues.

**Comment by fire** [comment]
Can you post the branch where you were able to compile? I can try debugging.

**Comment by akien-mga** [comment]
Closing as [we just removed VisualScript for 4.0](https://github.com/godotengine/godot/pull/64822), so this can no longer be evaluated as is.

The VisualScript module has been moved to https://github.com/godotengine/godot-visual-script with the aim that it might be ported to a GDExtension if there are interested contributors to do so. Further work to improve the features could be done on that repository too (so currently there isn't anyone dedicated to maintain this repository, it will depend again on whether some contributors step up to do so).

**Pull request closed without merging**
