### PR TITLE
Fix node rename problem

### PR DESCRIPTION
**Pull request by sanikoyes**
If rename node to '.' or '..', will cause problems
1、rename node to '.'
2、rename this node again
3、node's parent name changed
4、remove this node
5、node's parent has removed...

And not recommended use '/' for node name

### CODE REVIEW

**Comment by Krzycho666** [comment]
Why this isn't merged? The problem still exists.

**Comment by akien-mga** [comment]
Looks good to me code-wise, will need to test it live.

> Why this isn't merged? The problem still exists.

Congrats on posting a comment for the 1-year anniversary of the PR :D

**Comment by akien-mga** [comment]
It looks like '/' characters are already ignored somehow in the rename function (as they don't appear in the new name after validating, nor in the .xscn diff. But it doesn't hurt to "forbid" them explicitly either.

Apart from that, I get a build issue on X11:
```
Compiling ==> tools/editor/scene_tree_editor.cpp
tools/editor/scene_tree_editor.cpp: In member function 'void SceneTreeEditor::_renamed()':
tools/editor/scene_tree_editor.cpp:661:86: error: '_TR' was not declared in this scope
   error->set_text(_TR("Invalid node name, contain illegal character(s):\n ('.', '/')"));
                                                                                      ^
```

**Comment by akien-mga** [comment]
Without the ```_TR()```, it works fine. Here's a diff that proposes some rephrasing too:
```
diff --git a/tools/editor/scene_tree_editor.cpp b/tools/editor/scene_tree_editor.cpp
index 5312c1b..3c3eaf5 100644
--- a/tools/editor/scene_tree_editor.cpp
+++ b/tools/editor/scene_tree_editor.cpp
@@ -658,8 +658,8 @@ void SceneTreeEditor::_renamed() {
        String new_name=which->get_text(0);
        if (new_name.find(".") != -1 || new_name.find("/") != -1) {
 
-               error->set_text(_TR("Invalid node name, contain illegal character(s):\n ('.', '/')"));
-               error->popup_centered_minsize(Size2(400,80));
+               error->set_text("Invalid node name, the following characters are not allowed:\n    \".\", \"/\"");
+               error->popup_centered_minsize();
                new_name=n->get_name();
        }
```

**Comment by akien-mga** [comment]
I've actually cherry-picked your fix and added my suggestions to it in #2767.

**Pull request closed without merging**
