### PR TITLE
PhysicsBone3D and Skeleton Improvements

### PR DESCRIPTION
**Pull request by marstaik**
## Demo
[Video demonstration of this MR](https://youtu.be/jy0iqu0VZFU) (beware, outfit is a little risque, may be NSFW)

## Summary
The aim of this commit is to improve the Physics bone system to create more impressive rigged 3d characters in Godot. It addresses some issues with flexibility (previously, there could be only one physical bone per bone) and simulation and ease of use issues.

I really recommend watching the above video, as it does a much better job of demonstrating how the new nodes work.

## Changes
This commit renames PhysicalBone3D -> PhysicsBone3D and converts PhysicsBone3D into a proper rigid body.

PhysicsBone3D has two modes - bone tracking and free simulation. In bone tracking - the body is in "kinematic mode" and continuously follows the bone. In free simulation mode, the bone is in rigid body mode, simulating with the world, and controls the position of the joint directly.

For joining free simulating bones, derived nodes of all of the Joint classes have been made specifically for bones, and whose joint position is automatically computed as the pivot point of the second bone. This allows full customization of the simulating joint hierarchy, and allows for combinations of free simulation and non free simulation.

Due to decoupling of character controllers kinematic bodies from free simulating bones, a PhysicsBoneCompensation3D node has been added which allows you to track velocities of a kinematic object and apply them to the bones.

Skeleton3D has also been updated to have an internal process tick for pose updates, as well as for partial pose re computation (only bones affected and their children will have their final poses recomputed)

### CODE REVIEW

**Comment by TokageItLab** [comment]
@marstaik Greetings, marstaik. I'm one of the people who want to improve the Skeleton system in Godot. I created a PR for #42681 before, but later realized that this PR existed. I fully support this PR, but I would like to add two implementations to the PR.

The first is simply get_bone_children(), which is useful for creating add-ons that do bone manipulation, and the second is force_update.

The second is force_update. In this PR, the update is done only once per Process. This improves performance, but when processing bones recursively in one process, there are cases where the transformation of the parent bone is not inherited by the child bones.

I have [commit](https://github.com/TokageItLab/godot/commit/3cfa5c25864d771a192647324f6fcbc0e9368958) for the two implementations, please consider merging them. And as soon as the commit is merged, the #42681 will be closed.

Regards,

**Comment by pouleyKetchoupp** [comment]
@marstaik This PR looks like interesting improvement for ragdolls. Would you be up for rebasing this PR and finalizing your work? It would be nice to have this kind of redesign for 4.0 since it's breaking compatibility, even if just for the renaming and making physics bones inherit from rigid bodies.

Let me know whether you plan to keep working on this, and I can either help with reviewing or make a new PR to finalize it and co-author you.

I have some questions about the general design too:

> PhysicsBone3D has two modes - bone tracking and free simulation. In bone tracking - the body is in "kinematic mode" and continuously follows the bone. In free simulation mode, the bone is in rigid body mode, simulating with the world, and controls the position of the joint directly.

1. Bone tracking vs. free simulation: Isn't it what physical bones already do by being simulated or not, after #36008? What is the difference in the new design?

> For joining free simulating bones, derived nodes of all of the Joint classes have been made specifically for bones, and whose joint position is automatically computed as the pivot point of the second bone. This allows full customization of the simulating joint hierarchy, and allows for combinations of free simulation and non free simulation.

2. Specialized joint nodes: What is the purpose of all these new classes? It seems they just inherit all the joint types and all use the same helper function to set their offsets. What about setting up the joints in the physics bone class instead using regular joints, and just setting their offset?

> Due to decoupling of character controllers kinematic bodies from free simulating bones, a PhysicsBoneCompensation3D node has been added which allows you to track velocities of a kinematic object and apply them to the bones.

3. PhysicsBoneCompensation3D: Could you provide a test project that shows the use of this feature?

> Skeleton3D has also been updated to have an internal process tick for pose updates, as well as for partial pose re computation (only bones affected and their children will have their final poses recomputed)

4. What is the purpose of this skeleton update change?

**Comment by TokageItLab** [comment]
@pouleyKetchoupp As for Question 4, I've written about the problem before #42681.

**Comment by EIREXE** [comment]
As @marstaik seems to have disappeared, I might have a go at rebasing this.

I will also try to respond to @pouleyKetchoupp 's concerns as best I can

> Bone tracking vs. free simulation: Isn't it what physical bones already do by being simulated or not, after Skeleton animates physical bones #36008? What is the difference in the new design?

I believe physics bones cannot collide with bones that are not being simulated, at least they don't in master, as per #51929 this seems to happen in 3.x too.

> Specialized joint nodes: What is the purpose of all these new classes? It seems they just inherit all the joint types and all use the same helper function to set their offsets. What about setting up the joints in the physics bone class instead using regular joints, and just setting their offset?

I have no response for this one.

>PhysicsBoneCompensation3D: Could you provide a test project that shows the use of this feature?

Physical bones are updated one physics frame late, which results in the position of bone tracking physics bones lagging behind, this is probably because of Skeleton3D having not synced its transforms or something like that. Hence the need for that node.

Below is a picture of said issue, sorry for the terrible quality:

imagen

**Comment by TokageItLab** [comment]
May be referenced by #56745.

**Comment by marstaik** [comment]
I'm back and using godot again, I'll try and get this PR up and running again when I have some time.

> Specialized joint nodes: What is the purpose of all these new classes? It seems they just inherit all the joint types and all use the same helper function to set their offsets.

IIRC this was simply to keep the original structure (before compat breaking for 4.0 was as aggressive as it now)

> What about setting up the joints in the physics bone class instead using regular joints, and just setting their offset?

A few of the reasons I can remember off the top of my head:
1) It makes it difficult to add the bones in the editor
2) Adding joints dynamically and keeping track of them is much harder as they are not full nodes (you would have to keep track of an index)

There's definitely more, but it will take me some time to remember all of the design constraints in particular. I do want to work on this because skeleton performance is very critical (especially for the games I work on).

**Comment by TokageItLab** [comment]
@marstaik Welcome back! Godot's Skeleton system has been significantly changed by #51368. I think it has made the architecture dirty and I believe it needs to be refactored.
I previously sent #55840, but it was rejected because it broke some IK systems... @lyuma and @fire is also concerned about refactoring the Skeleton system. I hope your work goes well.

**Comment by TokageItLab** [comment]
May will be superseded by #https://github.com/godotengine/godot-proposals/issues/4863.

**Comment by fabriceci** [comment]
What's the status on this?

**Comment by YuriSizov** [comment]
Given the comments above, seems that this needs to be at the very least re-evaluated and redone based on the modern version of the engine. And it will probably be at least partially superseded by the linked proposal. Feel free to reach out to the physics and the animation teams to get started again!

**Pull request closed without merging**
