### PR TITLE
Replace all instances of `erase` with `remove`

### PR DESCRIPTION
**Pull request by AaronRecord**
Array's `remove()` method was renamed to `remove_at()`
Dictionary, Array and Set's `erase()` methods were renamed to `remove()`

See https://github.com/godotengine/godot-proposals/issues/2885

### CODE REVIEW

**Comment by timothyqiu** [comment]
I think `remove_value` is a bit long. I wish it's `remove(value)` and `remove_at(index)` as named in many other languages / libraries, but it makes it harder to spot error when porting codes from 3.x to 4.0.

**Comment by LightningAA** [comment]
> I think `remove_value` is a bit long. I wish it's `remove(value)` and `remove_at(index)` as named in many other languages / libraries, but it makes it harder to spot error when porting codes from 3.x to 4.0.

I don't mind `remove_value()`, but I don't really mind `remove()` either, they both sounds good to me. Either is much clearer than `remove()` and `erase()`. Maybe a poll should be had about which people prefer?

**Comment by LightningAA** [comment]
I created an issue/poll (https://github.com/godotengine/godot-proposals/issues/2885).

**Comment by LightningAA** [comment]
Okay, based on feedback, I've renamed `remove_value()` to `remove()`. I might end of reverting this, but I've also replaced all occurences of `erase` in method names with `remove` (including renaming `Dictionary`'s and `Set`'s `erase()` methods) for consistency (`erase` was 1/5th as common as `remove`)

**Comment by LightningAA** [comment]
Okay, I think this would be smarter to do in individual PR's...

**Pull request closed without merging**
