### PR TITLE
Implement unit tests for Camera3D

### PR DESCRIPTION
**Pull request by TechnoPorg**
This PR adds unit tests for `Camera3D`. Methods tested are:
- `is_position_behind`
- `is_position_in_frustum`
- `project_position`
- `unproject_position`

The projection test is currently failing with `Frustum` projection mode. I don't really know how that mode works, to be honest, so any input would be appreciated.

A placeholder size variable is also added here to `DisplayServerHeadless` in order to make it possible to project points in headless mode. I'm not sure if this will have any unintended consequences, so I would appreciate feedback from a `DisplayServer` expert. If not, it could be helpful for https://github.com/godotengine/godot-proposals/issues/1760.

I noticed a fair bit of code duplication between `project_position`, `project_ray_origin`, and `project_local_ray_normal` while working on this. I think they can probably be refactored to all forward calls to a single function, but I thought that was better left for another PR.

Part of #43440.

### CODE REVIEW

**Comment by fire** [comment]
@JFonS Are you able to give some insight on the frustum node and how it relates?

**Comment by TechnoPorg** [comment]
I've rebased this PR to use `doctest::Approx`, following #68275.

**Comment by TechnoPorg** [comment]
@JFonS Sorry to bump, but would you mind taking a look at this when you have time?

**Comment by TechnoPorg** [comment]
Rebased on current `master`.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/84826 (which includes tests for all methods included in this PR). Thanks for the contribution nonetheless!

**Pull request closed without merging**
