### PR TITLE
Adds the display of the favorites into the file list

### LINKED ISSUE #22309: Selecting Favorites entry in the split mode should list the favorites
**Godot version:**

8e4b18a721bbf38623e9dde1b4fe8d89308cdaf9

**Issue description:**

image

### PR DESCRIPTION
**Pull request by groud**
Closes #22309
output
The search also works in favorites, even if I did not show it in the gif.

### CODE REVIEW

**Comment by capnm** [comment]
Some issues:

+ Clicking or double-clicking an entry should not open a collapsed `favorite:` entry

+ Sometimes, when dragging into the favorites I get a segmentation fault crash:
```
Thread 1 "godot3-wip" received signal SIGSEGV, Segmentation fault.
TreeItem::is_collapsed (this=0x0) at scene/gui/tree.cpp:352
352		return collapsed;
(gdb) bt
#0  TreeItem::is_collapsed (this=0x0) at scene/gui/tree.cpp:352
#1  0x000055555628ef7a in FileSystemDock::_go_to_file_list (this=this@entry=0x55555bf5cad0)
    at editor/filesystem_dock.cpp:847
#2  0x000055555628f52f in FileSystemDock::navigate_to_path (this=this@entry=0x55555bf5cad0, p_path=...)
    at editor/filesystem_dock.cpp:480
#3  0x000055555628fa7a in FileSystemDock::_select_file (this=this@entry=0x55555bf5cad0, p_path=...)
    at editor/filesystem_dock.cpp:826
#4  0x000055555628fba3 in FileSystemDock::_file_list_activate_file (this=0x55555bf5cad0, p_idx=<optimized out>)
    at editor/filesystem_dock.cpp:837
#5  0x000055555580aa19 in MethodBind1<int>::call (this=0x55555c1450a0, p_object=<optimized out>, 
    p_args=0x7fffffffc700, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:729
#6  0x0000555557985843 in Object::call (this=0x55555bf5cad0, p_method=..., p_args=0x7fffffffc700, p_argcount=1, 
    r_error=...) at core/object.cpp:968
#7  0x000055555798f588 in Object::emit_signal (this=0x55555bf7f250, p_name=..., p_args=p_args@entry=0x7fffffffc700, 
    p_argcount=1) at core/object.cpp:1254
#8  0x00005555579902cc in Object::emit_signal (this=this@entry=0x55555bf7f250, p_name=..., p_arg1=..., p_arg2=..., 
    p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:1307
#9  0x0000555556b1b99a in ItemList::_gui_input (this=0x55555bf7f250, p_event=...) at scene/gui/item_list.cpp:539
#10 0x0000555555a04a0d in MethodBind1<Ref<InputEvent> const&>::call (this=0x5555597749e0, p_object=<optimized out>, 
    p_args=0x7fffffffc990, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:729
#11 0x000055555798649c in Object::call_multilevel (this=0x55555bf7f250, p_method=..., p_args=0x7fffffffc990, 
    p_argcount=1) at core/object.cpp:802
#12 0x000055555798468f in Object::call_multilevel (this=this@entry=0x55555bf7f250, p_name=..., p_arg1=..., p_arg2=..., 
    p_arg3=..., p_arg4=..., p_arg5=...) at core/object.cpp:908
#13 0x0000555556a3aab1 in Viewport::_gui_call_input (this=this@entry=0x555559d314d0, p_control=<optimized out>, 
    p_input=...) at scene/main/viewport.cpp:1422
#14 0x0000555556a4928a in Viewport::_gui_input_event (this=this@entry=0x555559d314d0, p_event=...)
    at scene/main/viewport.cpp:1691
#15 0x0000555556a4c262 in Viewport::input (this=this@entry=0x555559d314d0, p_event=...) at scene/main/viewport.cpp:2456
#16 0x0000555556a4c397 in Viewport::_vp_input (this=0x555559d314d0, p_ev=...) at scene/main/viewport.cpp:1204
#17 0x0000555555a04a0d in MethodBind1<Ref<InputEvent> const&>::call (this=0x555559704220, p_object=<optimized out>, 
    p_args=0x7fffffffce90, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:729
#18 0x0000555557985843 in Object::call (this=0x555559d314d0, p_method=..., p_args=0x7fffffffce90, p_argcount=1, 
    r_error=...) at core/object.cpp:968
#19 0x000055555798461b in Object::call (this=<optimized out>, p_name=..., p_arg1=..., p_arg2=..., p_arg3=..., 
    p_arg4=..., p_arg5=...) at core/object.cpp:892
#20 0x0000555556a12a00 in SceneTree::call_group_flags (this=this@entry=0x5555594ca770, 
    p_call_flags=p_call_flags@entry=2, p_group=..., p_function=..., p_arg1=..., p_arg2=..., p_arg3=..., p_arg4=..., 
    p_arg5=...) at scene/main/scene_tree.cpp:262
---Type <return> to continue, or q <return> to quit---
#21 0x0000555556a1f036 in SceneTree::input_event (this=0x5555594ca770, p_event=...) at scene/main/scene_tree.cpp:418
#22 0x0000555555783762 in InputDefault::_parse_input_event_impl (this=0x5555594c5b70, p_event=..., 
    p_is_emulated=p_is_emulated@entry=false) at main/input_default.cpp:414
#23 0x0000555555783920 in InputDefault::parse_input_event (this=<optimized out>, p_event=...)
    at main/input_default.cpp:259
#24 0x000055555577667b in OS_X11::process_xevents (this=this@entry=0x7fffffffd570) at platform/x11/os_x11.cpp:1993
#25 0x0000555555777be5 in OS_X11::run (this=0x7fffffffd570) at platform/x11/os_x11.cpp:2819
#26 0x0000555555769c2c in main (argc=3, argv=0x7fffffffdcc8) at platform/x11/godot_x11.cpp:55
```

**Comment by groud** [comment]
> Clicking or double-clicking an entry should not open a collapsed favorite: entry

What do you mean ?

> Selecting and RMB-removing multiple files and dirs from favorites leaves the files in favorites

Indeed, the file list needs an update in that case. I'll work on that.

> Adding favorites to favorites produces an easter egg

Ah indeed.

> Sometimes, when dragging into the favorites I get a segmentation fault crash:*

That's true, I have been able to reproduce the bug.

Thanks for the tests ! :)

**Comment by capnm** [comment]
>>    Clicking or double-clicking an entry should not open a collapsed favorite: entry

>What do you mean ?

There is no reason to open the Favorites entries, if you [double-]click on some other entry: 

peek11

**Comment by groud** [comment]
Thanks, those problems should be fixed now.

**Comment by capnm** [comment]
To be on the same page, i use `godot-demo-projects/2d/role_playing_game` (cleaned up with `git clean -fdx`.

There still seems to be some problems with the fw. entries. I don't have time to investigate it now:
image

**Comment by groud** [comment]
> There still seems to be some problems with the fw. entries. I don't have time to investigate it now:

Thanks, it should be fixed now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
