### PR TITLE
Fix incorrect title in Inherit dialog

### LINKED ISSUE #44691: Incorrect title for Attach Node Script->Inherits
**Godot version:**

Godot v3.2.3 stable win64

**OS/device including version:**

Windows 10

**Issue description:**

**Steps to reproduce:**
1. Click the attach script to node button above the scene hierarchy
2. Hit the select node to inherit from button
3. Notice the selection menu header is "Create New Node" instead of something like "Select Node"

**Minimal reproduction project:**

Not relevant (I think)

### PR DESCRIPTION
**Pull request by VedatGunel**
Fixes #44691.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works. The **Create New Node** dialog name is still correct after you opening the **Inherit \<node\>** dialog.

**Comment by VedatGunel** [comment]
The confirmation button still says "Create". I guess I should also change that. Or would it be a better idea to change the popup_create function to account for this case instead?

**Comment by Calinou** [comment]
> The confirmation button still says "Create". I guess I should also change that. Or would it be a better idea to change the popup_create function to account for this case instead?

Either is fine, as long as you can find a suitable word for both use cases.

**Comment by VedatGunel** [comment]
Changed the button text as well. Since the popup_create function sets these values every time it's called, it shouldn't cause an issue with other types of dialogs. But I'm still not sure if I should modify that function directly insted of applying these after it's called.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
