### PR TITLE
Add support for dynamic navigation mesh creation (recast+detour)

### PR DESCRIPTION
**Pull request by slapin**
Hi guys!

This is result of several months work (well, only on weekends and some rare free time moments) of what I'd call agent-based navigation. It is in no means complete, but I hate to work alone without others feed back. I know there are probably unresolvable conditions which will prevent merging of this (using Recast at runtime and usage of Detour libraries) but lets pretend there is no such conditions and do some review.

What this already does:
1. All core detour functionality (navigation mesh creation and most of queries are implemented)
Need to point offmesh connections and navigation areas with costs. Also CSG mesh data are supported for navmesh build.
2. Crowd support with basic local collision avoidance (RVO-based) using DetourCrowd.
3. Dynamic obstacle support
4. Partial navmesh rebuild
5. Uses groups instead of parenting for selecting of geometry objects to build navigation meshes

What it does not yet:
1. List of editor helper nodes is incomplete and I look over mature engines for design ideas,
will implement that soon. So now everything is scriptable.
2. Some implemented helper nodes usage is not intuitive, especially using of offmesh connections.
I work on it, too.
3. Can't bake navmesh, it is built from script at run time. Had Godot serialization issues, but will overcome this eventually.
4. No documentation.

These shortcomings are top priority for completion of navigation support. I know about them.
But please report all nastiness you find. I hope this PR will get some interest at least a tiny bit
and that will motivate me to improve that. For my own projects current function state is close to completion.

My motivation behind this project was to implement runtime capable crowd navigation and this goal was achieved with this PR, as I use dynamic runtime-generated world and need navmesh support for that, also I use crowds of people, so I needed that too. Recast/Detour/DetourCrowd/DetourTileCache combination support what I need quite well and I'm happy with that, so I hope others will be happy too.

### CODE REVIEW

**Comment by slapin** [comment]
No way. If agent-based navigation is needed for 2D (I guess it is questionable due to different kind of constraints under 2D) this should be another project. I am not 2d person myself so I only can guess. Theoretically you can use 3D navmeshes for 2d but this looks more like using sledge hammer to get.screw in place - might work but not mostneffective way. Godot does have 2d navmesh and you could improve it for the job, but I think that for 2d games things like ledge climbing, agent local collision avoidance, etc.  will be implemented in different way and it is hard to find common set of features. 

For 3d navigation can help in lots of areas and navmesh data provided by libraries here are very useful common set of data and number of possible queries allow writing complex game mechanics. I cant figure out this for 2d and as 2d games tend to be more simple and most 2d devs even don't know what navmesh is, I hardly can imagine advanced navigation requirements for 2d. 

As I said, simple 2D navigation is already in place for a long time.

This recast/detour/detour crowd  navigation is aimed for 3d character based games with complex ai needs, gathering data for common needs in cooked form so that logic can run quickly and provide modern enough gameplay elements. It is too different from common 2d game requirements.

**Comment by slapin** [comment]
- Fixed for new coding style requirements
- Added CSG mesh data supported in navmesh generation

**Comment by TheWhiteLlama** [comment]
I love you! It took me some time to find this thread, since you and me seem to be the only one caring about missing navigation features on the internet I guess? :D 

Are there any plans on when Godot 3.2 with this feature is making it's way to alpha builds? :-)

**Comment by slapin** [comment]
I maintain the up to date version of the code, so I will update PR as I
test it this weekend.
Thanks for asking!

**Comment by slapin** [comment]
Well, finally updated to new set of tests.

**Comment by lupoDharkael** [comment]
If this gets refused in the core I'd love to see this as a module on its own repository as it would be pretty useful for my procedural game.

**Comment by slapin** [comment]
Well, looking at this https://github.com/godotengine/godot/pull/28328 and orginal story I decided to close this PR and will no longer maintain it. I will work in the feature though but will never try to PR anything to Godot again. Good luck.

**Comment by organicpencil** [comment]
NOoooOoooooo!
Well I will continue following your fork because this is an amazing feature. Seriously hope it finds its way into Godot some day.

**Comment by TheWhiteLlama** [comment]
is this because you've been using third party libraries? Maybe there is a way around this? :(

**Comment by slapin** [comment]
Well, we want to use well established third-party libraries instead of
own crappy NIH-motivated code because you want to get quality,
making sure you have high quality low level core as foundation.
Writing everything yourself is good strategy for some giant
corporations but for individual developer, when you finally finish
writing everything yourself you will get too old to actually use the
result.
More than that I think if there is already existing library, which
covers functions you need and of adequate quality and with acceptable
(compatible)
license, it should be used.
The recastnavigation stack of libs (Recast, Detour, DetourCrowd,
DetourTileCache) is well established set of libraries for various
navigation needs,
which handle various sets of problems and very nice to work with.
These are used by major engines like UE4. Having this and implementing
own
navigation instead is insult to all reason. Well, if you have some
special requirements you could, but in our case there is no such
requirements.
Implementing navigation system for Godot using these libs is very
nice, especially if you implement open world game with a lot of
procedural
generated and runtime placed stuff. Also offmesh connections are
supported, which can be used for jumps or other thngs directly. Also
ledge
info system for ledge climbing/"vaulting" system is automatic (navmeh
data can be filled with various polygon types and flags). The system
is very
friendly for complex navmesh use, especially with large number of
characters (i.e. per-agent polygon filters).

Godot is probably not ready to accept this kind of contributions due
to choosen direction vector and approaches to some problems. Also lack
of respect
to contributor's work in many cases (too many of you too little of
us), strange policy and other things make it impossible to invest time
into large
scale projects because they will be either ignored, rejected, or
removed later on the line. Also too many decisions are based on
misinformation,
ignorance or lack of interest of particular persons. Also common
stigma about each line of code increasing bloat, etc. makes it heavily
unlikely for
large contribution to be developed and integrated by outside
contributor, as in general internal developers do not need to pass
this and any policy
checks, so they can actually do something, but due to their lack of
enthusiasm and experience, that is unlikely to happen any time soon.

So the only current way I see to continue this work is as part of
"navigation" branch of my fork. I will update "navigation_pr" branch
from time to time
but without rebase which I did before. "navigation" branch contains
some other changes which might not be needed by people, so
"navigation_pr"
will contain only patches needed for navigation. If anybody will be
willing to merge this and will come up with plan, I will help as much,
but will not
produce any PR with this work directly. So for noow you will need to
pull changes from "navigation_pr" branch.

I'm very busy with my work these days, so I might work very slowly, so
if any contributions will be sent to me I will be more than happy
to share responsibility. The work plan which I see for now with
navigation is to move core code into its own DetourNavigationServer,
to be more
flexible to handle in more complicated setup. Also threading support
needs to be checked. After this the remaining helper nodes should be
implemented for easier implementing simple setups.  And last,
visualisation code should be implemented to have all the bits visible
in scene editor.

Need to also add that the most power of the system will still be
available from code, from powerful use of filters and navmesh queries.
For me,
helper nodes are not priority, but I understand that they greatly
increase usability. They require several design iterations to get
right though.

**Comment by akien-mga** [comment]
> Well, looking at this #28328 and orginal story I decided to close this PR and will no longer maintain it. I will work in the feature though but will never try to PR anything to Godot again. Good luck.

You see to have misunderstood that issue. I reverted a change that added *custom* code to Bullet, because I want our copy of Bullet to stay the one validated and released by upstream, and shipped by Linux distros.

So it's not at all about favoring a "do it yourself" strategy versus using established thirdparty libraries. It's the contrary actually. I reverted a "do it yourself" change to make sure we stick to the established thirdparty library code.

**Comment by TheWhiteLlama** [comment]
thank you akien-mga for having a look onto this topic! I really need and want this feature so much, and also think slapin did a great job here! :-)

**Comment by starry-abyss** [comment]
@akien-mga It's still unclear to me, is the reverted feature already available in Godot repo in thirdparty Bullet directory?
If it's not, then it strongly smells like a distro cult. The whole point of having forked upstream is to not depend on their release cycles, isn't it?

**Comment by slapin** [comment]
Well, my view to this is the following:
1. You reverted the change to reduce maintenance issues, this is
understandable, but
2. The change given serious benefit for real world performance to complex
terrain collisions
3. Similar change was accepted upstream.
4. The change was already in, reviewed and accepted.
5. Changes required to build system to make tree compile to any Bullet 2.88
out there is trivial, just a few lines of code
6. You ask people to persuade Bullet developer(s) to release new stable
version you can track,
which is not very responsible thing to say.

Your position is understandable because you do not really care if the
feature is really in, but maintenance work
is here and real, but I'm more into practical approach and need all these
little features which allow me to make
bigger features on top of them. I really understand your motivation, but
from my POV and my side of things
I want every feature I need in; I know that you want most of them out, so
here comes a conflict of interests.
Also implementing features is big time investment and nobody wants to spend
time for nothing polishing things
for engine while one could just implement much simpler ad-hoc version just
for oneself.

**Comment by akien-mga** [comment]
> The whole point of having forked upstream is to not depend on their release cycles, isn't it?

We did not fork upstream. We bundle a copy of the upstream repository for convenience. We could just as well use a git submodule of the upstream repo, but those provide terrible UX for various reasons.

Unless we have a **strong** motive for modifying thirdparty code, we don't do it. Especially not for a project actively maintained where we can instead get the changed merged upstream, and sync those changes from upstream. This could be done in this case, and it's what I advised in the original PR and in my revert.

> 3. Similar change was accepted upstream.

"Similar" is the problem. I don't want us to maintain code that Bullet doesn't ship. We need the same code, or none of it.

> 5. Changes required to build system to make tree compile to any Bullet 2.88 out there is trivial, just a few lines of code

Sure, which is why I mentioned on that PR that it could be redone with the changes you mention as being trivial. A revert does not mean that the feature is rejected, only that this specific implementation should not have been merged as is. I'm awaiting a new PR that implements the feature without breaking compatibility with the current stable Bullet release.

> 6. You ask people to persuade Bullet developer(s) to release new stable version you can track, which is not very responsible thing to say.

I don't see how it wouldn't be responsible. Bullet maintainers can do a release whenever they want, and if downstream users express that they would like the master branch's changes to made it to a stable release, that's good feedback for them. I doesn't mean that they *will* make a release, but it's good that they hear about the need.

**Comment by slapin** [comment]
I still don't understand why you can't simply cherry-pick the change which
was merged into Bullet, add some python code which checks the method exists
and if it does, emable th feature and if not
just disable the feature? Anyway, this is not really a point, that is minor
detail. If you do not like implementation you usually use review to tell
about it. If it is already in you do not remove feature.
you fix it up. This is how it worked for ages everywhere but not with
Godot. I know that it is easy - no code, no problem, but this way things
get really messy and unpredictable, especially
looking from outside. This does not look as established process,

**Comment by groud** [comment]
> I still don't understand why you can't simply cherry-pick the change which was merged into Bullet, add some python code which checks the method exists and if it does, emable th feature and if not just disable the feature?

If this is so simple, why don't you do it then ? This is a community-based developement, if you can do it, just do it, don't waste your time in asking for others to do the work.

> Anyway, this is not really a point, that is minor detail. If you do not like implementation you usually use review to tell about it. If it is already in you do not remove feature. If it is already in you do not remove feature. you fix it up. This is how it worked for ages everywhere but not with Godot. 

@slapin I think @akien-mga was pretty clear about what happened, the PR should never have been merged as is. 
As a lot of contributors here, he does not have the time to fix all bugs by himself. Because being able to build is far more important than having such a feature on a short term, he reverted the commit to fix the problem as soon as possible, and suggested that someone else proposes a correct implementation. Reverting a commit is anyway pretty rare, as merging bad PRs is not common in our workflow.

**Comment by starry-abyss** [comment]
> Unless we have a strong motive for modifying thirdparty code, we don't do it. Especially not for a project actively maintained where we can instead get the changed merged upstream, and sync those changes from upstream. This could be done in this case, and it's what I advised in the original PR and in my revert.

Syncing changes to upstream is good. When upstream has these changes. But not prior to that.

> I don't see how it wouldn't be responsible. Bullet maintainers can do a release whenever they want, and if downstream users express that they would like the master branch's changes to made it to a stable release, that's good feedback for them. I doesn't mean that they will make a release, but it's good that they hear about the need.

It's not very responsible, because it relies on hopes that the release will be made soon, the new PR will be made soon. Because it's isn't an internal 1:1 change, it's the change from working state, to unknown state, just like that, out of sudden, like an act of sabotage.

> As a lot of contributors here, he does not have the time to fix all bugs by himself. Because being able to build is far more important than having such a feature on a short term, he reverted the commit to fix the problem as soon as possible, and suggested that someone else proposes a correct implementation. Reverting a commit is anyway pretty rare, as merging bad PRs is not common in our workflow.

Being able to build what? Godot with Bullet provided by distros? Who asked for this? Why use distro-provided Bullet for game development?

**Comment by groud** [comment]
> Being able to build what? Godot with Bullet provided by distros? Who asked for this? Why use distro-provided Bullet for game development?

Because not being able to do would break some people workflows, which is definitely less acceptable than missing a not-even-released-yet feature.

> I don't want offend anyone, but at the same time, I wanted it to be heard: please don't make dangerous decisions like this one, on your own in the future.

I think @akien-mga is a lot more aware about what is dangerous for the project than any of us, and on this specific case I back him. Nothing dangerous happened here, the only thing that happened is that this revert disturbed the development of a single PR (and maybe broke few projects using master branch). That happens all the time, it's called a "merged conflict", and we generally ask the PR author to fix the conflict himself.

Sadly, there is little we can do about it. Considering the amount of PR made every day and how many contributors are able to review them, the backlogs accumulates and leads to merge conflicts. 
But that's how open source works.

**Comment by slapin** [comment]
Well, I generally understand the points, you do not need to repeat
anything. It is too easy to put oneself into maintainer position.
But major contributions require much less hostile environment. Small
ones do not need this. Anyway, lets agree to disagree.
Godot developers and maintainers do what they want, I also do what I
want and everybody is happy. It is just all my fault I was hoping for
some
collaboration, that is generally not possible, not now.

**Comment by akien-mga** [comment]
I can understand why you would feel that a revert is a "hostile" operation, but I'll reiterate that it is not. A revert is just an Undo, and it doesn't prevent a Redo. It doesn't mean that the contribution was bad, but that it should have been merged as is.

I was not the one to merge it, and I told @hpvb after the merge that it was a mistake, and reverted it within hours of the merge.

I also used to feel that reverts were "bad" or "hostile", but that's not the way we use them, and most contributors are well aware of this fact. We revert stuff all the time, and most of the time involved contributors agree to make a new PR that re-implements the reverted feature with the necessary changes.

Yes, I could have done the necessary changes myself, and yes, I don't have time to do it, so I'm asking any contributor who feels that this PR's content is a must-have to redo it while taking into account the requirements that I set. A lot more time has been spent discussing here than it would have taken to:
- Inquire upstream whether a new release is planned within a reasonable timeframe before the 3.2 release.
- Cherry-pick the patch that was actually merged in Bullet upstream (which is not what that PR contained), clearly identify those local changes, and put that code behind a preprocessor define so that it can still compile against Bullet 2.88, with that new feature disabled.

> it's the change from working state, to unknown state, just like that, out of sudden, like an act of sabotage.

The same applies for us. And upstream, they have the expertise to assess this code, which we don't. So if we add code which was not validated by upstream in a stable release, it should **at the very least** be the one that upstream reviewed and merged.

**Comment by starry-abyss** [comment]
I don't disagree generally. The thing is Godot builds with the PR, it passed CI.

The only reason for revert seems to be system-packaged Bullet. And I don't see any reason to cut Godot for the sake of system-packaged Bullet. It would be more logical to forbid using system-packaged Bullet for building Godot.

From my point of view there was no urgency to revert anything in this case.

**Pull request closed without merging**
