### PR TITLE
[Scene] Add `SceneStringNames::toggled`

### PR DESCRIPTION
**Pull request by Chaosus**
A core enhancement similar to previous @AThousandShips commits, 😃

### CODE REVIEW

**Comment by AThousandShips** [comment]
Sweet! Already had this ready but hadn't opened the PR yet

**Comment by Chaosus** [comment]
> far further down than more common cases, see https://github.com/godotengine/godot/pull/91939 for a comprehensive list of cases I'm working on)

But far more than, for example, "theme_changed" which is already presented as SceneStringName.

**Comment by AThousandShips** [comment]
Yes but among the candidates for addition, like `text_changed` and `value_changed` and `confirmed` and `item_selected`

**Review by akien-mga — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Would be worth rebasing / checking if there are other occurrences to convert, then it can be merged.

**Comment by Chaosus** [comment]
@akien-mga Seems to be no new "toggled" are introduced at the current time:

image

**Comment by akien-mga** [comment]
I'd still push a rebase for good measure :)

**Comment by Chaosus** [comment]
@akien-mga Done

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
