### PR TITLE
Fix scaling issue for texture button focus texture.

### PR DESCRIPTION
**Pull request by fire**
Reproduction project.
[focus_bug.zip](https://github.com/godotengine/godot/files/2970034/focus_bug.zip)

Bug:

Fix:

### CODE REVIEW

**Comment by groud** [comment]
Have you checked if it works with flipped textures ? 
I know some problem might happen when you modify a draw_texture_rect call.

**Comment by fire** [comment]
I'm preparing for GDC and unable to work on this, the test project is here, so maybe you can test.

**Comment by fire** [comment]
@groud 

What do you mean scale flipped?

I tried this.

**Comment by fire** [comment]
Sample project.

[focus_bug_flipped.zip](https://github.com/godotengine/godot/files/3007254/focus_bug_flipped.zip)

**Comment by groud** [comment]
Sorry, my bad, I though we had this option in the Import tab. The PR looks ok then :)

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Pull request merged**
