### PR TITLE
Add cartesian to polar conversion functions

### LINKED ISSUE #7263: Proposal: Adding cartesian to polar conversion functions
*Bugsquad edit:* Repurposing this issue based on https://github.com/godotengine/godot/pull/7285#issuecomment-272994312

@tagcup wrote:
> Conversion between degrees and a general 2D vector doesn't make any sense to me, in mathematical terms: the norm of a 2D vector isn't necessarily equal to 1. You can't convert between two degrees of freedom (Vector2) and one degree of freedom (an angle) in a meaningful way.
> 
> I would rather propose adding functions that converts between polar and cartesian coordinates in 2D: (x,y) <-> (r,θ) where θ is in radians. The API could be something like cartesian_to_polar(x,y) and polar_to_cartesian(r,θ), each returning a vector.
> 
> Or alternatively, simply a polar constructor for Vector2.

--------------

*Original proposal:*

I find that a lot of users (me included) have the need to convert angles (in radian or degrees) into a Vector2 direction.

The current way to get a Vector2 direction from an angle;
```
  var radian_value = PI # 180 degrees
  var my_vec2 = **Vector2(cos(radian_value), sin(radian_value))**
```

I propose that we add new functions such as **rad2vec**(rad_value) and **deg2vec**(deg_value) with the other functions found at the [core](http://docs.godotengine.org/en/stable/classes/class_@gdscript.html).

This will make the process much cleaner for everyone, and we wont have to know/remember this formula. :)

### PR DESCRIPTION
**Pull request by tato**
Fixes #7263
Original PR #12061

### CODE REVIEW

**Comment by akien-mga** [comment]
There are merge conflicts in `doc/classes/VisualScriptBuiltinFunc.xml`. See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase for how to rebase and solve those.

**Comment by ptato** [comment]
So I did a `git pull --rebase https://github.com/godotengine/godot master` and fixed the merge conflict. That is what you meant right? I'm paranoid of breaking the PR again.

**Comment by akien-mga** [comment]
Yes, if your `git log` looks fine, you can now force push.

**Comment by ptato** [comment]
Done

**Comment by tagcup** [comment]
Can you add those functions to Vector2 class (the C++ one) and call them from there?

Similar thing can be done for Vector3 BTW, spherical, cylindrical, etc

**Comment by akien-mga** [comment]
> Can you add those functions to Vector2 class (the C++ one) and call them from there?

You mean as `Vector2.to_polar()` and `Vector2.to_cartesian()`, leaving it to the user to read the docs to understand that base vector would have to be respectively cartesian and polar for the conversion to make sense?

**Comment by tagcup** [comment]
I meant something like `Vector2 Vector2::polar_to_cartesian()`

**Comment by tagcup** [comment]
And this is a separate issue but I'm hoping we can undo the 133t sp34k from certain function names for 3.0...

**Comment by akien-mga** [comment]
> And this is a separate issue but I'm hoping we can undo the 133t sp34k or sk4t3r boi kind of talk from certain function names for 3.0...

That would be worth opening a dedicated issue for discussion (with a list of relevant methods that would have to be renamed), it's kind of now for 3.x API removals/renamings.

**Comment by akien-mga** [comment]
Merged manually as 054a2ac5 to solve the merge conflicts.

**Pull request closed without merging**
