### PR TITLE
Add particles icon to CPUParticles

### LINKED ISSUE #31152: CPUParticles don't have a gizmo icon
**Godot version:**
3.1.1

**Issue description:**
Particles have a nice icon in 3D that show where they are
image
But CPUParticles don't have one. It's not really important, but it bothered me when I converted to CPUParticles and the icon disappeared.

### PR DESCRIPTION
**Pull request by creikey**
Fixes #31152

### CODE REVIEW

**Review by JFonS — APPROVED** [review]
Code looks good. I guess it would be nice to have a separate icon for CPUParticles, but I don't know how to convert the existing CPUParticles icon to  a gizmo-like one.

**Comment by creikey** [comment]
maybe something like this? image

for comparison this is the normal particles gizmo image

and this is the cpu particles icon in editor 
image

**Comment by JFonS** [comment]
@creikey That looks great to me :)

**Comment by akien-mga** [comment]
CC @Calinou

**Comment by Calinou** [comment]
@creikey That proposed icon looks good to me, feel free to add it :slightly_smiling_face:

**Comment by creikey** [comment]
image
With the latest force push the custom icon has been added as a gizmo to the cpu particles

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
