### PR TITLE
Avoid saving scene while already saving the scene

### LINKED ISSUE #85093: Editor crashes when saving built-in script with a non empty last line
### Godot version

4.2.rc1

### System information

Godot v4.2.rc1 - Windows 10.0.22621 - GLES3 (Compatibility) - Intel(R) Iris(R) Plus Graphics (Intel Corporation; 27.20.100.9621) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

The editor crashes when saving a scene that contains a built-in script with a non empty last line.
The save always seem to take place anyway with an empty line added to the problematic script.

### Steps to reproduce

- Add a built-in script to a node
- Give it the script below
- Save the scene
```
extends Node

func _ready() -> void:
	pass
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #85093
Does not fix my crash unfortunately.

### CODE REVIEW

**Comment by YuriSizov** [comment]
I wasn't sure about a solution like this. I think that this will prevent the updated script from saving. We first save the scene then the script editor modifies the script to add an empty new line, and then we attempt to save the same scene again, but this won't happen as far as I can tell.

In a pinch this is not the worst thing, but we need to handle this somehow, ideally.

**Comment by KoBeWi** [comment]
There are multiple callbacks for applying some changes before saving, like `NOTIFICATION_EDITOR_PRE_SAVE` or `apply_changes()`. ScriptEditor should use that instead of modifying the script while it's being saved.

**Comment by akien-mga** [comment]
> There are multiple callbacks for applying some changes before saving, like `NOTIFICATION_EDITOR_PRE_SAVE` or `apply_changes()`. ScriptEditor should use that instead of modifying the script while it's being saved.

Do you want to try that approach? :eyes:

**Review by akien-mga — APPROVED** [review]
Discussed with Yuri, should be a good approach for now to prevent the crash.

**Pull request merged**
