### PR TITLE
Add force_keep_data prop to Mesh (and -keepdata import flag)

### PR DESCRIPTION
**Pull request by RandomShaper**
~~I'm trying to implement~~ a mechanism by which a `Mesh` can be set to retain its data after being uploaded to VRAM regardless the global behavior set at the rasterizer (`keep_copies`). 

**Edit:**
At #5044 I presented the use case of needing to duplicate `Mesh` resources at runtime in order to have independent copies to deal with (for example, different materials or alterations of the geometry). The problem is that on mobile the original mesh data is dropped,

~~Now I need a way of ensuring that this property is set before the surfaces are passed to the rasterizer so it knows whether it has to keep the data or can drop it. Afterwards would be too late.~~

~~So this PR is still a work in progress. I would like to know if I'm on the right path. If my approach is good, 
I'd need some way of ensuring the order. Are properties expected to be unserialized in `_get_property_list()` order? Also if there is a more reliable way of ensuring.~~

**Edit:** Solved.

### CODE REVIEW

**Comment by slapin** [comment]
Looks like very good idea. Will surface access work for such meshes?

**Comment by slapin** [comment]
Please provide short description of PR motivation directly in PR cover, that will make it self-contained
and easier to reference in future.

**Comment by slapin** [comment]
as I don't have time to test currently - please provide info on code state (does it work, any issues?)
and some minimal script to test this.

**Comment by slapin** [comment]
I'm very interested in this, though.

**Comment by RandomShaper** [comment]
I've finished implementing and documenting it!

The general rule is: call `set_force_keep_data()` on the `Mesh` before adding surfaces. So if the mesh is included in the scene or loaded by code, it's already too late. In those cases the flag must be set right in the scene editor.

One problem I faced was that I needed the property `force_keep_data` to be set before those properties of surfaces. My way of solving it is tracking three states for the flag at the rasterizer level (unknown, enabled, disabled).

If explicitly disabled, the data already stored is immediately dropped and no future data will be retained. If kept unset (unknown) the rasterizer will add it to a purge list to drop it on the next frame. 

This sorts out some problems:
- The order in which properties are read/written doesn't matter.
- Even if keeping data is not desired, as the property will be eventually set to false, the memory it takes will be freed almost at the same time that if this mechanism had not existed (per `Mesh` setup).
- If the scene was saved by an earlier version of the editor, thus `force_keep_data` not being set, the rasterizer will bre free to drop the data anyway on the next frame (although it will have accumulated data of multiple `Meshe`s so a higher RAM peak usage will happen during start-up).

**Comment by slapin** [comment]
Thanks! Looks good.

**Comment by RandomShaper** [comment]
[Minimal example.](https://drive.google.com/open?id=0B-WnZEtQk02PYVRHMXlrbVU5VUk)

On mobile (tested on Android), without `force_keep_data` the cubes at the sides won't be created and some error messages will be logged.

**Comment by RandomShaper** [comment]
Sorry to stress Travis… but this needed a hopefully last important addition: a flag for the scene importer to set the `force_keep_data` on `Mesh`es if they are tagged with `-keepdata`.

**Comment by RandomShaper** [comment]
Rebased.

Do maintainers get a notification when I rebase or it's better that I comment like this?

**Comment by akien-mga** [comment]
> Do maintainers get a notification when I rebase or it's better that I comment like this?

It's good that you comment, I did not get a notification for the rebased commit.

**Comment by slapin** [comment]
Please always comment, as there are many PRs, and no messages about updated
PRs are sent
by Github.

**Pull request closed without merging**
