### PR TITLE
Add mono audio support to WASAPI

### LINKED ISSUE #25875: [2.1.5] Distorted sound on some Windows
**Godot version:**
2.1.5

**OS/device including version:**
Microsoft Windows 10 Pro
Realtek High Definition Audio

**Issue description:**
Sound distorted and crakling:
[DistortedSound.zip](https://github.com/godotengine/godot/files/2865201/DistortedSound.zip)

**Steps to reproduce:**
- Original music is an OGG file
- Project configuration
image
- StreamPlayer node configuration
image

- Piece of code used to strat playing the music
```
func _play_music(volume):
  music_nodes[MUSIC_PLAYER.MUSIC].set_volume(volume)

  if volume <= 0.0 and music_data.next != null:
    music_data.current = music_data.next
    music_data.next = null

    # Update current music
    music_nodes[MUSIC_PLAYER.MUSIC].set_stream(music_data.current.source)
    music_nodes[MUSIC_PLAYER.MUSIC].play()
    music_nodes[MUSIC_PLAYER.MUSIC].set_loop(music_data.current.loop)
```

- Audio file informations
```
Input #0, ogg, from '00-titlescreen.ogg':
  Duration: 00:01:36.01, start: 0.000000, bitrate: 194 kb/s
    Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      ENCODER         : FL Studio
```

### PR DESCRIPTION
**Pull request by KoBeWi**
Co-authored by *anonymous contributor* (it's not my code, I'm just opening the PR)

This is pretty much copy-paste from PulseAudio.

Fixes #25875
Fixes (?) #75109 (the issue seems *a bit* different, needs to be tested)

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @bruvzg - from what I saw in https://github.com/godotengine/godot/issues/25875#issuecomment-1526509134 this may also be needed for CoreAudio.

**Comment by bruvzg** [comment]
> from what I saw in https://github.com/godotengine/godot/issues/25875#issuecomment-1526509134 this may also be needed for CoreAudio.

Yes, it probably will need something similar.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
