### PR TITLE
Fix mouse release leaving dock area

### LINKED ISSUE #64695: Leaving dock area releases mouse button
### Godot version

0c5f254

### System information

Windows 10 x64

### Issue description

Seems like some recent regression.
ShDLmLrHNW
Tested only with tile editor.

### Steps to reproduce

1. Open tile editor (add tilemap with tileset etc)
2. Drag to select tiles
3. Leave tile area while dragging
4. The drag is cancelled

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by GuilhermeGSousa**
Small fix for #64695

*Bugsquad edit:*
- Fixes #64695

### CODE REVIEW

**Review by groud — APPROVED** [review]
Seems a straightforward fix to me. Thanks!

**Comment by GuilhermeGSousa** [comment]
I'm guessing a rebase should solve the linux build error?

**Comment by akien-mga** [comment]
Indeed, you'd need to rebase on latest master to fix it.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
