### PR TITLE
add polygons property description in Polygon2D

### PR DESCRIPTION
**Pull request by Streq**

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Please use more descriptive commit messages for contributions :) Besides that, this looks good to me. Thanks for contributing!

**Review by kleonc — APPROVED** [review]

**Comment by akien-mga** [comment]
The added documentation helps, but I'm still very confused by what `polygon` and `polygons` are and how they relate to each other. "The polygon's list of polygons" doesn't seem to tell much.

**Comment by Streq** [comment]
@akien-mga I agree it is confusing, I think some of the confusion stems from having `polygon` be named "polygon" and not something like `vertices`, which is more in line with what it actually represents. I could be more descriptive and change the text to 
```
The list of polygons, in case more than one is being represented. Every individual polygon is stored as a [PackedInt32Array] where each [int] is an index to a point in [code]polygon[/code]. If empty, this property will be ignored and the polygon will be composed of all points in [code]polygon[/code], using the order they are stored in.
```

**Comment by mhilbrunner** [comment]
@Streq I think that description would indeed be an improvement (with links to polygon).

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by timothyqiu** [comment]
Cherry-picked for 3.6.

**Pull request merged**
