### PR TITLE
Create user-dir, if non-existant, so it can be opened with Godot

### LINKED ISSUE #41680: Open Project Data Folder doesn't work immediately after renaming the project
**Godot version:** 3.2.2 and Git https://github.com/godotengine/godot/commit/64e0a129001b670a81ffa833aa85d8ed7bc73d39

**OS/device including version:** Fedora 31, GeForce GTX 1080 (NVIDIA 450.66)

**Issue description:**

The **Project > Open Project Data Folder** menu option doesn't work immediately after renaming the project. Since this can be worked around by running the project once or restarting the editor, this is a minor issue but it would still be nice to fix it.

This can be fixed by creating the folder before trying to open it, to ensure it's always present (even if it's empty).

**Steps to reproduce:**

Rename the project in the Project Settings by changing **Application > Config > Name** then try to use **Project > Open Project Data Folder** (without starting the project or restarting the editor beforehand).

**Minimal reproduction project:** N/A

### PR DESCRIPTION
**Pull request by Leleat**
Closes #41680.

As @Calinou suggested in the issue, I just created an empty folder.

### CODE REVIEW

**Comment by Leleat** [comment]
I don't know what failing the iOS build check means... or how to fix that :x 

Help would be appreciated.

**Comment by YeldhamDev** [comment]
> I don't know what failing the iOS build check means...

Seems that the error is not caused by the PR. It happens from time to time, don't worry.

**Comment by akien-mga** [comment]
This should be done with `OS::ensure_user_dir` when the project is renamed, not each time the user dir is accessed.

**Comment by Leleat** [comment]
> This should be done with `OS::ensure_user_dir` when the project is renamed, not each time the user dir is accessed.

Not sure where to put it else. There is no dedicated function/signal to a project rename. Instead `project_settings_editor` just connects its `property_edited` signal with `project_settings`'s save function. `project_settings_editor` doesn't include OS. And it kinda feels out of place to put this into the project settings' save function.

If the check happens with the button press of 'Open Project Data Folder', it may also catch the case when the user accidentally deletes the folder. I delete project folders every now and then to prevent clutter (like having New Game Project, New Game Project2... xD). What do you think?

**Comment by akien-mga** [comment]
> Not sure where to put it else. There is no dedicated function/signal to a project rename. Instead project_settings_editor just connects its property_edited signal with project_settings's save function. project_settings_editor doesn't include OS. And it kinda feels out of place to put this into the project settings' save function.

I thought we had some code to handle this already, but it seems to be the other way around (e.g. when you move/delete the main scene in the FileSystem dock, the main scene project settings is updated accordingly).

I guess this could be implemented in `ProjectSettingsEditor::_setting_edited()` when `p_name` is the name of that property.

> If the check happens with the button press of 'Open Project Data Folder', it may also catch the case when the user accidentally deletes the folder. I delete project folders every now and then to prevent clutter (like having New Game Project, New Game Project2... xD). What do you think?

Well the project dir is created automatically when you start Godot, so it's really a mild allowance that it might raise an error if you deleted it while Godot is editing the same project, so I wouldn't complexify the codebase too much to support this.

**Comment by Leleat** [comment]
> I guess this could be implemented in ProjectSettingsEditor::_setting_edited() when p_name is the name of that property.

Amended per your suggestion. 

But I noticed that `p_name` is only the property name and not the full path. So ensure_user_dir() will also run for other properties named `Name`. By default there are no such settings though, so it only applies to custom project settings. I guess this isn't a big deal?

**Comment by akien-mga** [comment]
> But I noticed that `p_name` is only the property name and not the full path. So `ensure_user_dir()` will also run for other properties named `Name`. By default there are no such settings though, so it only applies to custom project settings. I guess this isn't a big deal?

No that's a problem, we can't guarantee that there won't be such properties in the future, and custom properties can have any name (aside from the full path of another existing property).

**Comment by Leleat** [comment]
> No that's a problem, we can't guarantee that there won't be such properties in the future, and custom properties can have any name (aside from the full path of another existing property).

Well, I found a way to ensure a folder is created only when the project name property is edited. But I noticed that putting the code under `_setting_edited()` is pretty bad because every time a letter is pressed a new folder is created. I ended up with 29 new folders when testing xD.

I don't think there is a good way to know when the user "finished" renaming the project. So how about putting the code back to whenever the user presses "Open Project Data Folder"?

**Comment by akien-mga** [comment]
> I don't think there is a good way to know when the user "finished" renaming the project. So how about putting the code back to whenever the user presses "Open Project Data Folder"?

Yeah for now I think that's the best option. I'll look some more to see if there's a more clever way to handle it (as the `user://` dir can also be used by other features, like writing logs), but if not it might be good enough.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by akien-mga** [comment]
Undid cherry-pick for now as it depends on making `ensure_user_data_dir()` public as #39563.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4. (Via #45010.)

**Pull request merged**
