### PR TITLE
renamed all Rect3.pos to Rect3.position

### LINKED ISSUE #9040: Rect3 pos to position
same as #9019

### PR DESCRIPTION
**Pull request by AlexHolly**
Didn't see any changes in GDNative like there was with Rect2 I hope thats right.
@karroffel 

closes #9040

### CODE REVIEW

**Comment by nunodonato** [comment]
it seems you need to do some clang-format fixes ;)

**Comment by akien-mga** [comment]
> it seems you need to do some clang-format fixes ;)

Yeah this macro alignment stuff using spaces is ugly, but never found how to turn it off.

Would also need to rebase to fix merge conflicts with the modified `mesh.cpp`.

**Comment by akien-mga** [comment]
There are still clang-format issues and the branch should be rebased `git rebase upstream master` to get rid of the merge commit, but I can do it myself tonight if you want.

**Comment by AlexHolly** [comment]
I installed clang and tried to fix it but clang is just showing some code and is not telling what is actually wrong. I never used clang before is there some tutorial in the Godot docs?

**Comment by akien-mga** [comment]
> I installed clang and tried to fix it but clang is just showing some code and is not telling what is actually wrong. I never used clang before is there some tutorial in the Godot docs?

Not yet, but the syntax to apply clang-format on files is `clang-format -style=file -i <path/to/files>`.
Otherwise you can use the precommit hooks in `misc/hooks` (see the README.md there) which will apply clang-format for you when you commit.

**Comment by AlexHolly** [comment]
Okay I think I finally destroyed it.

**Comment by groud** [comment]
Hum... I believe you should have done a `git rebase` instead...

**Comment by akien-mga** [comment]
I'm cherry-picking the commit manually, don't worry.

**Comment by akien-mga** [comment]
Merged as 935f73017.

**Pull request closed without merging**
