### PR TITLE
[4.0] [iOS] iOS Plugins Migration

### PR DESCRIPTION
**Pull request by naithar**
A follow up commit for https://github.com/godotengine/godot/pull/41230 that removes iOS plugins from `modules`. 
WIP until I finish tests and scons build setup for plugins in separate repo.

### CODE REVIEW

**Comment by naithar** [comment]
`rsync -a -m -R --include '*/' --include '*.h' --exclude '*' ./ extracted_headers` seems to be the best way to extract headers from Godot's sources. 

@akien-mga is there any way to make `scons` only generate headers, so there would be no need to actually run and cancel a compilation?

**Comment by naithar** [comment]
@akien-mga I've temporary made repository on my account: https://github.com/naithar/godot_plugins_ios for all plugins. 
Everything seems to be working fine, but I'll double check on the week just to be sure.
Should I create a plugins repo on team account when everything is ready?

**Comment by akien-mga** [comment]
> I've temporary made repository on my account: https://github.com/naithar/godot_plugins_ios for all plugins.
Everything seems to be working fine, but I'll double check on the week just to be sure.
Should I create a plugins repo on team account when everything is ready?

Yeah you should be able to transfer your repo to @godotengine (you might lose Write access to it in the process, but I can fix that up once transferred). I'd suggest renaming it `godot-ios-plugins` as we tend to use `kebab-case` for repo names (with the exception of `godot_headers` for GDNative but that should be fixed).

> is there any way to make scons only generate headers, so there would be no need to actually run and cancel a compilation?

There's no option for that currently no. That's something that could likely be implemented if we go ahead with Meson port though #45093.

What headers do you need exactly though? Should it be the whole Godot tree? If so, isn't it simpler to just use the `godot` repo directly and have as a requirement to do a build once to generate the headers for the desired Godot commit/tag?

Or alternatively, have the Godot build generate a source archive like done for Android (CC @m4gr3d).

**Comment by naithar** [comment]
> What headers do you need exactly though? Should it be the whole Godot tree? If so, isn't it simpler to just use the godot repo directly and have as a requirement to do a build once to generate the headers for the desired Godot commit/tag?

Yeah, the whole Godot tree headers are needed, including generated `inc` files. 
You may be right. Using Godot whole source (with submodules or whatever) should be simplier - I did it with plugins example template, so maybe I shouldn't overcomplicate things with header extraction.

**Comment by naithar** [comment]
iOS plugins should now be testable: https://github.com/naithar/godot-ios-plugins/releases
I'll run some more tests and transfer the repo once everything is ready.

**Comment by naithar** [comment]
@akien-mga cleaned up and transferred repo to https://github.com/godotengine/godot-ios-plugins. 
Not sure about read/write access rights though.

From what I've tested everything seems to be working correctly.

**Comment by akien-mga** [comment]
> @akien-mga cleaned up and transferred repo to https://github.com/godotengine/godot-ios-plugins.
> Not sure about read/write access rights though.
> 
> From what I've tested everything seems to be working correctly.

Looks good! I gave Write permissions to @godotengine/ios there.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
