### PR TITLE
Fix the CanvasItemEditor jiggling around when zooming.

### PR DESCRIPTION
**Pull request by Macksaur**
I like having the editor view constrained to the scene but it behaves kinda funny when you zoom out.

This PR tackles two issues:
- The view centring code isn't stable and vibrates when zooming
- The scrollable area calculation often ends up negative and wont centre the scene when zoomed out

This PR fixes these issues by adding a dynamically sized border around the canvas item rect that's the larger of either
1) the size of the configured project's window size (same as before this PR) or
2) half of the editor's visible area.

This allows the canvas item editor to always centre exactly on one of the four corners of the scene when zoomed out. When zoomed in this PR behaves as before and allows panning the editor view up to one full configured project window size away.

Without this PR (jiggly + doesn't centre):
godot_constrain_zoom

With this PR (smooth + centres on any of the four corners):
godot_constrain_zoom2

### CODE REVIEW

**Comment by groud** [comment]
The constrained view was removed, so I guess this PR could be closed ?

**Comment by KoBeWi** [comment]
Yep, thanks for the contribution nonetheless.

I think this might be still relevant for 3.x.

**Comment by Macksaur** [comment]
> The constrained view was removed in the end

I think this PR would have prevented its removal but I don't know if it was ever brought up in meetings. I would very much rather this issue not dismissed so quickly.

**Comment by Macksaur** [comment]
I've tried to to link issues that people were having that this PR would directly solve. From what I can understand from the frustrations involved (mine included) removing the constrained view only feels like the correct solution when you give up on fixing it. It should have been last resort. People are turning off the constrained review not because it is broken. I don't think this PR was considered before it was removed.

I believe this PR makes the constrained view smooth and enjoyable to use. People can still turn it off if they must. But at least having it behave in a more regular fashion would be more appealing to me than its outright removal.

**Comment by KoBeWi** [comment]
Most of the issues weren't about scrolling experience, but about viewport getting locked at an arbitrary position. (e.g. #47007, #32163)

**Comment by Macksaur** [comment]
If you look at those issues, I've commented at the bottom that I believe this PR fixes those complaints...

**Comment by KoBeWi** [comment]
🤔
Ok sorry, I missed that you also adjusted the scrollable area.

Well, the feature can always be re-added if there is demand. Though there was little interest in fixing it; most people were fine once they learned that constrains can be disabled. You could maybe open a proposal and see if there is any support (although it would be probably nice if people could test the fixed version...).

**Pull request closed without merging**
