### PR TITLE
Add cell_item_changed signal to GridMaps

### LINKED ISSUE #11855: GridMap enhancement - A signal or callback for on_cell_changed()
The GridMap node would be an order of magnitude more powerful if I could have an editor script be able to detect whenever a cell has changed.

This could be achieved by any of a number of options. I'm not sure which would be the most appropriate method:

- A notification that i could check for in _notification()
- A signal (not sure if having signals that fire in editor/tool mode would be appropriate?)
- A method that could be overridden in a tool mode script that extends GridMap, maybe _on_cell_changed(cell_pos)

With this simple addition, I could write an auto-tile editor script in GDScript that I could share with everyone. You could have variation in tiles occur automatically; ie, place a tree tile and have a random one of six tree models spawn. You could have tiles automatically rotate in specific ways.

There would be lots of possibilities opened up by this.

### PR DESCRIPTION
**Pull request by WatchThemFall**
A signal called when a GridMap cell is changed. It returns the changed GridMap as an object, the changed cell's Vector3, the new item, and the previous item. Returns -1 as "previous" if no item existed, and returns -1 for the "new" item if it was an erase action.

Here's an example of what this can be used for:
https://i.imgur.com/1eZtotw.mp4
It makes GridMap quite a bit more powerful.

Fixes https://github.com/godotengine/godot/issues/11855
https://github.com/godotengine/godot/issues/10418

(Sorry I opened and closed a duplicate pull request earlier. I closed it because I ran it through some clang formatter, and it messed it up horribly. I didn't realize it wouldn't actually completely erase the PR.)

### CODE REVIEW

**Comment by aaronfranke** [comment]
@WatchThemFall Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by WatchThemFall** [comment]
Yes, it is still desired. It's the only way to get auto tiling gridmaps. I'm not very familliar with Github so I'm not sure why it closed it even though I never told it to close. I got a new PC so I had to recompile everything and remake a lot of stuff in my project since the update broke it, but it should be good now.

**Comment by aaronfranke** [comment]
@WatchThemFall What is your use case for this feature? Is there any reason you can't emit a signal in your own script when you are changing the GridMap?

**Comment by WatchThemFall** [comment]
No... it is mainly for an editor tool. There is no way to trigger anything in the editor like this without a signal as far as I'm aware.  There is already a cell_size_changed signal so why not cell_item_changed?

Another Example: https://imgur.com/a/nyHrH0N

**Comment by aaronfranke** [comment]
@WatchThemFall There is another implementation and more discussion in #40044, might be a good idea to leave your thoughs there as well.

**Comment by aaronfranke** [comment]
@WatchThemFall The other PR #40044 has been closed in favor of this one, however, the discussion there seems to indicate that this feature might not be desired since usually the thing changing the GridMap can also emit its own signal. For the video you made of your use case, that makes me think that GridMap needs an auto-tile system mostly.

If you still desire this feature, please rebase this pull request on the latest master branch so that we know it still works.

**Comment by WatchThemFall** [comment]
I'm not that familiar with Github so I'm not sure if what I did is what you wanted. I forgot what I did a year ago.  If it's not right just close this. It's been 2 years so if it's that much trouble I guess I will just compile my own Godot any time I need this signal. I agree that an auto-tile system would be better, but that would be a ton of work; way more work than 7 lines of code. There were at least 2 open issues for people asking for such a signal which is why I made a PR in the first place so I am not alone, and Cell_item_changed is way more useful than cell_size_changed which is already a signal.

**Comment by akien-mga** [comment]
Closing as per https://github.com/godotengine/godot/issues/11855#issuecomment-976721973, implementing this directly in GridMap doesn't seem to be the right approach for the use case that this aims to solve. This is meant to be for editor tooling and should therefore be provided via editor plugins APIs, which might need to be extended for this (e.g. to give access to GridMapEditorPlugin).

**Pull request closed without merging**
