### PR TITLE
Sanitize Android debug (2.1)

### LINKED ISSUE #10458: Remote debug over adb seems to be broken (2.1.4-beta)
**Operating system or device - Godot version:**
OSX, Android 4.4.2
Godot 2.1.4-beta (commit e5102a9)
**Issue description:**

If I set `Use remote debug over Adb` the debugging doesn't work at all.

[There I described the problem](https://godotengine.org/qa/17399/using-remote-debug-on-android-2-1-4-beta)

**Steps to reproduce:**

Set `Use remote debug over Adb` and try to debug on the android device.

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by RandomShaper**
~~'Remote debug over ADB' seems to be a left-behind of how Android debug worked a long time ago. Now it just breaks debugging.~~

~~What should be checked instead in order to enable remote debug and/or FS is just the fact that the project is deployed with such options toggled. Using ADB is always the case.~~

~~Also removing `EXPORT_REMOTE_DEBUG_LOCALHOST`, which was being only used for that.~~

__UPDATE:__

Reworked:
- _Commit 1:_ (the same as formerly but keeping localhost debug, needed for __`adb reverse`__)
'Remote debug over ADB' is removed as that will be always the case.
- _Commit 2:_
Fix Android remote debug not hitting breakpoints
RandomShaper committed an hour ago
A change in `Main`'s API is needed. Please read the comment in the diff for an explanation.

Closes #10458.

### CODE REVIEW

**Comment by reduz** [comment]
Remote debug over ADB is vital and should always be enabled if you plan to
use RemoteFS. In fact, it was not enabled by default because it's too new,
not too old. Otherwise, debug happens via wifi, which is unusable for
RemoteFS.

**Comment by reduz** [comment]
In fact, I think at this point we should enable remote debug over ADB
always..

**Comment by RandomShaper** [comment]
This PR makes debug-over-ADB the only option.

Is debug over Wi-Fi really needed? Since you have to use ADB anyway to deploy the game, you are expected to have the device already connected via USB.

Maybe I'm missing something.

**Comment by reduz** [comment]
oh I see, I misunderstood your PR

**Comment by RandomShaper** [comment]
My explanation has not been very good either. Indeed, I feel a bit confused about this. I have the feeling this is not completely OK, but I can't say why.

**Comment by reduz** [comment]
This seems ok to me. I also was thinking of making the options of deploy remote debug, as well as sync scene and script changes on by default

**Comment by RandomShaper** [comment]
Please don't merge yet.

**Comment by RandomShaper** [comment]
@reduz I've finally realized what I was missing: the localhost flag is needed for __`adb reverse`__. I've restored it.

And also added a second commit that allows breakpoints to work in Android.

Please have a look and give some feedback. :)

**Pull request merged**
