### PR TITLE
Mono/C#: Don't try to load project assembly in project manager

### PR DESCRIPTION
**Pull request by neikeq**
This was causing an error message when launching the manager,
because there is no project assembly to load.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Is this relevant for `3.2` too?

**Comment by neikeq** [comment]
Yes, but it isn't that important. Just gets rid of a false error in the project manager.
I say try it and just discard it if there are conflicts.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
