### PR TITLE
Extended ParticlesMaterial spread property to 360 degrees

### PR DESCRIPTION
**Pull request by siomnnn**
It's a bit weird that you couldn't set the emission spread to more than 180 degrees in the editor (e. g. if you want to make a particle system where particles fly off in every direction).

Before:

unnamed_2

After:

unnamed_1

This is my first commit, and I'm not really into GitHub yet, so tell me if I did something wrong.

EDIT: I messed the commits up and put them in the wrong place, so I had to delete them again. That's where the other commits come from.

### CODE REVIEW

**Comment by clayjohn** [comment]
A spread of 180 makes particles fly off in every direction. This is because spread goes in both the positive and negative directions. So a spread of 45 makes the particles emit in a 90 degree cone. While a spread of 180 makes the particles emit in all directions.

**Comment by Calinou** [comment]
@clayjohn I believe this could be changed in 4.0 for clarity, but it'd break compatibility.

**Comment by CowThing** [comment]
I think it's already clear as is. To me "spread" implies that it's the angle clockwise and the angle counter-clockwise of the particle direction, so I'd expect it to go from 0 to 180. And the documentation already mentions this on all the particle system pages.

**Comment by noname1477** [comment]
!!!SORRY EVERYONE!!!
I checked it again, and it was the way I told you. So I tried some stuff and found out that my installation was just broken (probably because I had to pause the download for some reason). After re-downloading and compiling it works perfectly well.
So again sorry for taking your time. I'll close this now.

**Pull request closed without merging**
