### PR TITLE
Pulling the request

### PR DESCRIPTION
**Pull request by flamestar**

### CODE REVIEW

**Comment by SuperUserNameMan** [comment]
Hey @flamestar 
I think something went wrong with your pull request.
Maybe you should close it.

**Comment by reduz** [comment]
wow what is this?

**Comment by silverkorn** [comment]
According to his profile, he's new since today...
I remember doing something similar @ my first attempt :smile:

**Comment by akien-mga** [comment]
Already, I believe you can close this PR @reduz, it's nonsense.
It's worrying that a random newly registered spam user could force the creation of a pull request from master to the 1.0 branch...

**Comment by akien-mga** [comment]
Closing, this issue is a total nonsense.

**Pull request closed without merging**
