### PR TITLE
Fix script editor errors with CustomCallables

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes the error part of #57057
I don't know what to do about the crash .-.

### CODE REVIEW

**Comment by reduz** [comment]
Would it not make sense to request the method name to the CallableCustom instead? if the CallableCustom does not support it it can throw an error.

**Comment by reduz** [comment]
Maybe eventually add whether it has a has_method() too

**Comment by KoBeWi** [comment]
> Would it not make sense to request the method name to the CallableCustom instead?

That was my first idea actually, but I thought that maybe there is a reason why CallableCustom has no `get_method()` and didn't want to change core stuff, so I went with a bit higher-level workaround. My first attempt was actually adding `get_method_from_callable()` to ScriptTextEditor 🙃

But I'll change it if you say it's ok.

**Comment by KoBeWi** [comment]
@reduz I added `get_method()` to CallableCustom.

I also reverted most of changes in `script_text_editor.cpp`, as they are not needed anymore. I left one thing as a optimization, not sure if relevenat.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
