### PR TITLE
[2.1] Enhanced debugger

### PR DESCRIPTION
**Pull request by Geequlim**
**Edited**

Refector debug related code to allow full access to variables to imporve develop experience.

- [x] Access more kind of properties from remote debugger
- [x] Change GDInstance to make it possiable to access script members with property list
- [x] Query Multiple remote object with debbger with better `ScriptEditorDebuggerInspectedObject`
- [x] Serialize/Unserialize informations accessed from `ScriptDebuggerRemot`e to `ScriptEditorDebugger`
- [x] Serialize dictionary variables from debugger remote  and unserialize them
- [x] Implements dictionary property editor
- [x] Battle test with real game projects in my company

Screen Recoder

### CODE REVIEW

**Comment by toger5** [comment]
It also would be amazing to have a console to run gd script during runtime. For reading out values from functions...  Running some math on variables.

**Comment by bojidar-bg** [comment]
@toger5 I think there was an issue about this (potentially closed), but I can't find it...

**Comment by Geequlim** [comment]
I think it would be convient if local variables can show up to members variables.
Do you agree with me

**Comment by Geequlim** [comment]
With latest commit the hacked debugger is done :P
Now we can check any variable value include class instances you defined in scripts while debugging our games. 
And we can even change the properties of objects' in the running game from inspect to debug our aswsome games.
Pin @reduz  and @akien-mga to review the code :)

**Comment by tagcup** [comment]
This looks really nice, good work! Did you try it with 3.0?

**Comment by Geequlim** [comment]
@tagcup I will port it to 3.0 after the 2.1 version is merged and the testing of my company pass

**Comment by Geequlim** [comment]
The data serialization/unserialization still need a refactor to handle some objects with thousands of properties or dictionary/array with a large number of elements.

**Comment by tagcup** [comment]
This may be related to an existing (and non-reported?) issue: if you instance many thousands copies of an object and try to debug/profile, it will crash the editor.

**Comment by Geequlim** [comment]
@tagcup No this problem won't happen before. 
And I have catch it so it will be solved soon :)

**Comment by Geequlim** [comment]
With last commit the property informations of objects are transfered with raw data between the debugger and the client.
The debugger now should hold most debug situation event with large scripts with large number of properties :)

**Comment by Geequlim** [comment]
@tagcup It seem the problem is already here, so I decide to open an issue #9034 and try to solve it now.

**Comment by Geequlim** [comment]
Everything should work fine now :)
Continue battle testing next week.
screen 4

**Comment by Geequlim** [comment]
After test for the dubgger with the real game project in development. I make some changes below:

* Add `self` reference to curent break point script file.
* List constants in the stack tree and also constant members of scripts in inspector.
* Open resource files directly from the remote objects by click its `path` property.
* Show constants defined in GDScript resources in the inspector.

New Screenshot

And Fix bugs cause the debugger server stopped with errors.

So I think it's time to have a code review :)

**Comment by Geequlim** [comment]
Make some code clean up and move `self` into `members` group in the stack variable tree.
Expand the `self` cell will show properties of the instance instead of Script resource's.

**Comment by akien-mga** [comment]
Little update here: @reduz has stated several times that he has other plans for the master branch (likely for 3.1) regarding refactoring the debugger, but at the same time he's OK with merging this for 2.1.

As for myself I find it a bit awkward to have a better debugger in 2.1 than what we'll have in 3.0, but if you guys are okay with that, then why not.

Before merging though, I'd like to see some rebase to squash some of the 14 commits together. There are many changes so it might make sense to keep some in separate commits, but there are also some fixup commits which should be squashed into their relevant parent commit.

**Comment by Geequlim** [comment]
All commits are squashed into one and rebase to the latest commit.

**Comment by karroffel** [comment]
Now for 3.0? :)

**Comment by Geequlim** [comment]
@karroffel As said by @akien-mga 
> @reduz has stated several times that he has other plans for the master branch (likely for 3.1) regarding refactoring the debugger.

This functionanlity is not urgently needed in new version as we don't  use 3.0 with real project yet.
So I don't want to disrupt his plan.

**Comment by reduz** [comment]
I dont really have a plan, it's just open for discussion. What I though for
3.x is that

1) Debugger and Remote inspector should be merged somehow
2) I'm not ok with arrays, dictionaries, etc. being opened in the general
property editor, we should make it happen in the debug one.

**Comment by akien-mga** [comment]
What about merging @Geequlim's improvements in master for 3.0, and rework the debugger based on this for 3.1?

**Comment by reduz** [comment]
As mentioned, much of his work is already replicated by the remote
debugger, so what's missing is currently more of a code reorganization than
improvements

**Comment by ElfEars** [comment]
Would probably be a good idea to merge the dictionary property editor even if his changes are discarded for 3.0 considering that godot doesn't have that functionality yet afaik.

**Comment by reduz** [comment]
As of dc62389, edited objects appear in the remote debugger (with tab automatically switched), with proper node selected in the tree in case it's a node. I think this maks a lot more sense. The size limit for sending objects is also fixed and checked. 

Not sure if all the rest of the features work, probably not but it could be interesting to start working over what already is there.

**Comment by Geequlim** [comment]
Does it allow us to check or change remote objects which are not a Node instance in the remote debugger panel ?

**Comment by reduz** [comment]
> Does it allow us to check or change remote objects which are not a Node instance in the remote debugger panel ?

Yeah, that should work fine, as far as I know it always worked this way

**Pull request merged**
