### PR TITLE
Script editor description on hover Implementation

### LINKED ISSUE #1393: Implement script editor description hint on hover a symbol/word
**Describe the project you are working on:**
Description hint on hover for the text edit(https://github.com/ThakeeNathees/godot/tree/TextEdit-hover-hint)

**Describe the problem or limitation you are having in your project:**
it's one of the essential feature for a fully featured script editor and currently we lack of. Also the implementation of GDScript doc comments (https://github.com/godotengine/godot/pull/41095) it'll improve the user experience.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
when a symbol is hovered by the mouse, the text editor emits a signal to validate the symbol (like when it's being hovered with a ctrl), and when validating for that symbol it'll add some additional data (like description, type, class_name, return_type, arguments, etc.,) and display them at the text edit's draw call.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A working example (this will work with doc comments when it'll be merged)
hint2

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, It would be a great usability improvement and can't be worked around with the script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
there is no way to implement this with an add-on

*Bugsquad edit (keywords for easier searching): tooltip*

### PR DESCRIPTION
**Pull request by ThakeeNathees**
This will draw the description of the symbol that is being hovered (closes https://github.com/godotengine/godot-proposals/issues/1393) This will work with #41095 (marked some TODOs for dependency) and the color values are hard coded which needs to be changed with the theme (not sure I'll be able to implement themes and colors)

### CODE REVIEW

**Comment by dreamsComeTrue** [comment]
LOVE THAT man! 😃 ❤️

**Comment by knadoor** [comment]
This is really good feature!! Love it 👍

**Comment by pycbouh** [comment]
@ThakeeNathees Can you rebase this PR, please? I think we should look into merging this soon.

**Comment by ThakeeNathees** [comment]
@pycbouh I've rebased it with the master, The spacing between text is broken, but drawing the hint box is for now is temporary to test the backend of the feature. Hope that would iteratively improve over reviews.

**Comment by KoBeWi** [comment]
> Maybe we should make it so hovering with, say, Ctrl pressed would make hints stay on screen and allow for users to interact with them?

In VS Code the hints appear above cursor and when you move cursor to hover the label it will stay until you click somewhere.
VS Code
I think the formatting should be fixed, but interactivity can be left for later PR.

**Comment by akien-mga** [comment]
You can lookup `EditorHelpBit` which has logic to make tooltips which handle the class reference XML properly, like `EditorHelp` does (used in the Inspector and Project Settings tooltips).

**Comment by Paulb23** [comment]
Yeah first thoughts are rather then handling hovering manually we can reuse tooltips. Haven't looked too much into it, but would be ideal if we could override them and keep it self contained to the editor side in `CodeEditor` / `ScriptTextEditor` as well, since it's using `ScriptLanguage`.

**Comment by Calinou** [comment]
Not critical for this pull request, but for keyboard-only users, we should add a keyboard shortcut to show help on the symbol currently under the caret. This way, you don't have to reach for the mouse to see help for a specific symbol.

Visual Studio Code uses the <kbd>Ctrl + K</kbd> then <kbd>Ctrl + I</kbd> combination for this, but I suggest picking a single shortcut for ease of use.

**Comment by akien-mga** [comment]
Superseded by #63908.

**Pull request closed without merging**
