### PR TITLE
Add AudioFrame to Variant

### PR DESCRIPTION
**Pull request by marcelofg55**
Based of this addition I have (almost ready) an audio effect that can be used to read and generate audio samples from scripts.

### CODE REVIEW

**Comment by marcelofg55** [comment]
With the mentioned audio effect procedural audio will be able to be generated (requested at #18135).

**Comment by reduz** [comment]
No, this is overkill.. and you can use a Vector2 if you want, which is pretty much the same.

I think the best way to approach this would be to create an AudioStream that you can simply feed via PoolFloatArray or PoolVector2Array (and improve gdscript performance to access it). Still it's really inefficient, better GDNative bindings are imo the best alternative.

**Comment by Zylann** [comment]
On a side note, if the script API gets a way to generate audio, then GDNative and also C# will get it for free as well, with no need to design a new specific interface that would only work in GDNative.

**Comment by akien-mga** [comment]
I also think it's too much to add a whole new Variant for this. Variant is one of the most intimate parts of the engine, additions to it need to have a very strong use case to justify them. I haven't looked at this in detail but if Vector2 can be used to the same effect, then adding a new audio-specific tuple seems overkill indeed.

**Comment by reduz** [comment]
That said, I think you could probably add a constructor and operator for AudioFrame that takes and returns a Vector2. This way you can use it in your C++ APIs and it will work for variant.

**Pull request closed without merging**
