### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./thirdparty,*.po,./DONORS.md -L ackward,ang,ans,ba,beng,cas,childs,childrens,dof,doubleclick,expct,fave,findn,gird,hist,inh,inout,leapyear,lod,nd,numer,ois,ony,paket,ro,seeked,sinc,switchs,te,uint,varn,vew`

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by fire** [comment]
Also reviewed the changes and looks good to me.

**Comment by mhilbrunner** [comment]
Thank you!

**Comment by akien-mga** [comment]
Is this using `codespell` from Git? I literally ran codespell 2.1.0 days ago.

**Comment by luzpaz** [comment]
@

> Is this using `codespell` from Git? I literally ran codespell 2.1.0 days ago.

Using codespell HEAD here. But you can keep main dictionary updated via:
https://github.com/codespell-project/codespell#updating-the-dictionaries

**Pull request merged**
