### PR TITLE
thorvg: Update to 0.14.9

### LINKED ISSUE #96491: Some SVGs are not displayed since 4.3.beta3
### Tested versions

- Reproducible in v4.3.beta3, v4.3.stable, v4.4.dev1
- Not reproducible in v4.2.2.stable, v4.3.dev1, v4.3.dev3, v4.3.dev5, v4.3.beta1, v4.3.beta2

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - AMD Radeon RX 6800 (Advanced Micro Devices, Inc.; 31.0.24033.1003) - Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz (4 Threads)

### Issue description

I tried upgrading a project from Godot 4.2.2 to Godot 4.3, which I made using a lot of SVGs but all textures that used .svg doesn't show anymore in the game.
No console errors, and the game runs fine, is just that the .svg textures are not been displayed.

If I open it with Godot 4.3 the .svg textures are not been displayed. Same with Godot 4.3.beta3 and later versions.
imagen

If I open the project on Godot 4.2.2 it works just fine. Same with Godot 4.3.beta2 and previous versions.
Captura de pantalla 2024-09-02 203305

I tested different Godot versions, and it seems to be reproducible in Godot 4.3.beta3 and later versions. But not reproducible (works fine) in Godot 4.3.beta2 and previous versions. (I'm always deleting the .godot folder after each test)

## The version I open the project first is the key to reproduce the error
For some reason, if I delete the .godot folder, and then open and import the project with 4.3.beta2 (which works fine), and after that, I open it again with 4.3.stable everything seems to work fine.
The same way, if I delete the .godot folder, and then open and import the project with 4.3.stable and then I go back to 4.3.beta2 the sprites don't appear. 

Seems like it all depends on which version I open the project with first. If it's Godot 4.3.beta2 or earlier it works just fine, if it's Godot 4.3.beta3 or later the sprites don't appear. 

## Only with .svg files
Other files, like .png seems to work fine, this is happening just with .svg files to me.

### Steps to reproduce

Clone or download this Godot Project "Poder Solar": https://github.com/antimundo/poder-solar
Open it in Godot 4.3
See how most sprites are not been displayed.

### Minimal reproduction project (MRP)

The project is open source and available at:
https://github.com/antimundo/poder-solar

### PR DESCRIPTION
**Pull request by akien-mga**
- Fixes #96491.

Update fix for #96262 to a simple revert of the problematic commit, as the upstream fix is still being debated and caused other issues.

Also include fix for upstream regression 2715 added in 0.14.9.

### CODE REVIEW

**Review by fire — COMMENTED** [review]
I'll try the test cases from @antimundo https://github.com/godotengine/godot/issues/96491 as a basic check.

- [X] The pr is a good bug fix from a conceptual point of view
- [X] Technical review was done upstream and doesn't modify godot engine code
- [X] Since it doesn't modify godot engine code, we'll defer to upstream style review
- [ ] Needs to follow a test plan of loading the test cases and checking if it's ok. There's the test Godot Engine project from @antimundo and the Omigroup logo from @aaronfranke

**Review by fire — APPROVED** [review]
I'll approve for now, but need help with the test plan.

**Comment by capnm** [comment]
Here is a fix that "Update to 0.14.9" introduces ;)
https://github.com/thorvg/thorvg/pull/2716

**Comment by akien-mga** [comment]
> Here is a fix for bug that "Update to 0.14.9" introduces ;) [thorvg/thorvg#2716](https://github.com/thorvg/thorvg/pull/2716)

Thanks, added.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
