### PR TITLE
Add type icons to Theme editor Import Items tab

### PR DESCRIPTION
**Pull request by fire-forge**
- Show type icons in the Import Items tab
- Replace "One" with "1" in data type counts
- Use a + icon for the "Add" button

| Before | After |
:---:|:---:
| image | image |
| image | image |

### CODE REVIEW

**Comment by YuriSizov** [comment]
I'm not sure about showing color previews. Looks cool, but in practical terms this window is for mass manipulation of data, so knowing exact values is not important there. On top of that, this means you need to rebuild this tree every time a color changes, which happens a lot, and often fast. You could debounce the update, but then, is it really worth to have colors there in the first place?..

**Comment by groud** [comment]
> I'm not sure about showing color previews. Looks cool, but in practical terms this window is for mass manipulation of data, so knowing exact values is not important there. On top of that, this means you need to rebuild this tree every time a color changes, which happens a lot, and often fast. You could debounce the update, but then, is it really worth to have colors there in the first place?..

I think it is worth if the performance impact stay small. It's a lot easier IMO to quick understand what those colors refer too, or spot specific ones into the list, if you can see their actual value.

**Comment by groud** [comment]
> But are colors special compared to other theme item types? Fonts, styleboxes, even icons don't get this treatment, and if what you say is true, it should apply to them as well.

Well, if it is possible, it could be useful. Though the performance impact might be too much IDK. But to be fair, I think colors identifiers are more difficult to distinguish from each other than the ones we use for styleboxes, so it might make the most sense for colors.

I understand your point, and maybe it is just me, but I feel like it is hard to find what colors like `base_color`, `dark_color`, `font_color` or `mono_color` correspond to without being able to see the color their are associated with in the default theme. So the version with the colors values is a lot more usable to me.

**Comment by YuriSizov** [comment]
> I understand your point, and maybe it is just me, but I feel like it is hard to find what colors like `base_color`, `dark_color`, `font_color` or `mono_color` correspond to without being able to see the color their are associated with in the default theme. So the version with the colors values is a lot more usable to me.

Oh, you're thinking mainly about the import tab. I was thinking mainly about the edit tab. There shouldn't be much need to redraw the import tab tree, so performance shouldn't be a concern there. And I can see how you'd find it useful there, although if you're picking and choosing that much, maybe you can just override the colors you want in the main editor panel and not in the import dialog.

I'm still not sure if it's a good idea to break consistency for colors. They do look nice and clean, but still...

**Comment by YuriSizov** [comment]
Would the import tab benefit from a quick preview for the selected item then? As a universal solution. Kind of like I do in the theme explorer plugin:

image

**Comment by groud** [comment]
> Would the import tab benefit from a quick preview for the selected item then? As a universal solution. Kind of like I do in the theme explorer plugin:

oh that actually looks like a really good idea.

**Review by YuriSizov — APPROVED** [review]
Code looks good to me. Feel free to work on the preview as we've discussed, if you want. I promise to review that one quicker :)

**Comment by fire-forge** [comment]
@YuriSizov Thanks! I'll write up a proposal so we can discuss the UX and design for the preview.

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
