### PR TITLE
Added get_v_scroll to item list, issue 6343

### LINKED ISSUE #6343: ItemList scrolling from GDScript - Impossible
**All OS / Godot 2.1**

Judging from the discussion:
[linc](https://godotengine.org/qa/7535/richtextlabel-itemlist-scrolling-from-gdscript)

Impossible ItemList scrolling from GDScript. Although this functionality is obviously needed.

### PR DESCRIPTION
**Pull request by Paulb23**
Added `get_v_scroll` to item list.

closes #6343

### CODE REVIEW

**Comment by akien-mga** [comment]
I guess it would make sense to have `set_v_scroll` too then, no?

**Comment by akien-mga** [comment]
BTW, for such small additions I think it's fine to add the docs directly in the initial commit, it still makes a relatively self-contained change.

**Comment by Paulb23** [comment]
I don't see the need for a setter as the function returns the VScrollBar itself, so you can adjust the properties as needed.

**Comment by akien-mga** [comment]
Oh right I read the diff a bit too fast :) I thought it would be an `int` like in ScrollContainer: http://docs.godotengine.org/en/latest/classes/class_scrollcontainer.html#class-scrollcontainer-set-v-scroll

**Pull request merged**
