### PR TITLE
Additional demos icons

### PR DESCRIPTION
**Pull request by akien-mga**
Add icons to some of the demos that did not have any, based on screenshots of the demos.
Also renamed polygon_path_finder_demo.

### CODE REVIEW

**Comment by bushig** [comment]
I think this demo should be moved from 'demos/2d' to 'demos/3d' becouse its actually a 3d scene.

**Comment by jackmakesthings** [comment]
Nice! :+1:

**Comment by akien-mga** [comment]
I'll be so bold as to merge it myself, as it's harmless and I need the polygon_path_finder_demo rename for my other PR.

**Comment by akien-mga** [comment]
> I think this demo should be moved from 'demos/2d' to 'demos/3d' becouse its actually a 3d scene.

Nice catch. I fixed this in 4120a93.

**Pull request merged**
