### PR TITLE
Fix 'popup_centered_minsize()' not working

### PR DESCRIPTION
**Pull request by YeldhamDev**

### CODE REVIEW

**Comment by akien-mga** [comment]
Is it `popup_centered_minsize()` that needs this fix, or `popup_centered()` as a whole as done in #24907?

**Comment by YeldhamDev** [comment]
@akien-mga I just tested that PR and it doesn't fix the issue on this one.

**Comment by akien-mga** [comment]
Would be nice if you described the issue this PR is fixing then :)

**Comment by YeldhamDev** [comment]
After analysing the function better, I found that it's actually is not intended to that what I thought it did (actually, its job seems quite useless, but alright), so my "fix" is moot. Closing it.

**Pull request closed without merging**
