### PR TITLE
[3.x] Remove hardcoded names in generated objects

### PR DESCRIPTION
**Pull request by Shatur**
This is a 3.x version of #47271.

### CODE REVIEW

**Comment by akien-mga** [comment]
Force pushed to solve merge conflicts.

**Review by akien-mga — APPROVED** [review]
Should be fine to merge like the `master` PR was.

**Comment by akien-mga** [comment]
Thanks!

**Comment by jamie-pate** [comment]
FYI this is a breaking change for some workflows..

If you have created a new scene which instances an imported scene, and then modified node properties then the tscn file will no longer modify the properties of the correct child object.
(e.g. there's no xyz-rigidcolonly so any rigid bodies who's mesh should not be shown need to be hidden in godot after import)

Probably should mention this in the release notes.

@fire

**Comment by fire** [comment]
Can you also post this in the documentation team so it doesn't get lost? I'm currently at Siggraph 2022.

**Comment by akien-mga** [comment]
It is mentioned in the curated changelog: https://github.com/godotengine/godot/blob/3.5/CHANGELOG.md#import

**Comment by jamie-pate** [comment]
> It is mentioned in the curated changelog: https://github.com/godotengine/godot/blob/3.5/CHANGELOG.md#import

It's mentioned, but there's no note that it's a **breaking change** like some other changes..

**Pull request merged**
