### PR TITLE
Improve logic to detect whether vulkan is used for rendering

### PR DESCRIPTION
**Pull request by m4gr3d**
Follow-up to https://github.com/godotengine/godot/pull/72780#discussion_r1097270282

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
The changes make sense to me. 

I guess if we fully want to protect against all the edge cases warned by Akien in https://github.com/godotengine/godot/pull/72780#discussion_r1097270282 we should be checking OS::get_current_rendering_method()`` instead of reading the project setting. But we can do that later.

**Comment by akien-mga** [comment]
> I guess if we fully want to protect against all the edge cases warned by Akien in [#72780 (comment)](https://github.com/godotengine/godot/pull/72780#discussion_r1097270282) we should be checking `OS::get_current_rendering_method()` instead of reading the project setting.

That would only tell you what you're running on the desktop host, not the Android export target.

**Review by akien-mga — APPROVED** [review]

**Comment by clayjohn** [comment]
> > I guess if we fully want to protect against all the edge cases warned by Akien in [#72780 (comment)](https://github.com/godotengine/godot/pull/72780#discussion_r1097270282) we should be checking `OS::get_current_rendering_method()` instead of reading the project setting.
> 
> That would only tell you what you're running on the desktop host, not the Android export target.

Ah, I missed that this is in export code.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
