### PR TITLE
ability to click on spatial subscene to select it

### LINKED ISSUE #2852: Selection in Spatial View doesn't work with instanced objects/scenes
As in title, also new ALT + RMB selection menu doesn't work with 3D instanced objects/scenes for the same reason probably.

### PR DESCRIPTION
**Pull request by kubecz3k**
After clicking at spatial subscene it should be selected. 
I got the initial idea on how to do this from some old code written by @TheoXD :+1: 
click_select_spatial_subscene

closes #2852

### CODE REVIEW

**Comment by kubecz3k** [comment]
Oh it seems this solves https://github.com/godotengine/godot/issues/2852 I think

**Comment by Zireael07** [comment]
Seems so, and it's a big usability improvement coming for the new people!

**Comment by suchaaver-chahal** [comment]
I'm surprised the fix is so simple. Is this really all the code needed?

**Comment by n-pigeon** [comment]
You rock!

**Comment by minifigmaster125** [comment]
It's a surprisingly simple fix. This really all that is needed?

**Comment by toger5** [comment]
Damn nice! also fixes:
#9145 and partially #10201 

It's just amazing how fast things get fixed ;)
this video literally got uploaded yesterday: https://youtu.be/lRbefcsYDi4

**Comment by Stajin** [comment]
Thanks for the fix, much appreciated!

**Comment by fracteed** [comment]
Nice work! Does this also work with marquee select, for single or multiple instanced scenes? As I detailed in #9145 there are some strange inconsistencies between click and marquee selection in the viewport.

**Comment by kubecz3k** [comment]
@fracteed I don't think so, this pr is only an addon for the function where click raycasting is performed.

**Comment by fracteed** [comment]
Ok, thanks. Shift click will have to do for now! Hopefully the marquee selection issues can be resolved at some stage :)

**Comment by HeadClot** [comment]
This is one of my major gripes solved with Godot. Any plans to solve drag and drop?

**Comment by bojidar-bg** [comment]
I think you should also fix `_find_items_at_pos` (for select-tool behavior) and `_select_region` for marquee selections.

**Comment by kubecz3k** [comment]
@bojidar-bg thanks for info I will look at those functions :)

**Comment by HeadClot** [comment]
It got merged! 🎉

**Comment by neikeq** [comment]
It got aki-merged

**Comment by tagcup** [comment]
I can't still seem to select an instanced scene which is made of other instanced scenes?

**Comment by kubecz3k** [comment]
@tagcup is this about such user case: ?
empty space click

**Comment by kubecz3k** [comment]
mean that would translate into "unable to select if scene visual content is far away from scene root" (that's the actual reason why this happens what's on this gif )

**Comment by tagcup** [comment]
Zooming in didn't fix it for me, I still can't select it. Can someone re-open this issue?

**Comment by reduz** [comment]
For reference, I rewrote this code.. now selection of instanced scene items works properly without hacks

**Comment by tagcup** [comment]
@reduz just tried but I'm still having the same issue: I have an instanced scene which contains a parent spatial and 3 subscenes as a child, and when I instance this scene in a large world, I can't seem to select any part of it at all.

**Pull request merged**
