### PR TITLE
GDScript parser sets error when _init() receive any arguments

### PR DESCRIPTION
**Pull request by ThakeeNathees**
see: https://github.com/godotengine/godot/issues/37907#issuecomment-614336557

_init(args)

### CODE REVIEW

**Comment by Calinou** [comment]
The constructor should be allowed to have optional arguments. This is a common pattern for Object-derived classes, but it can also be used for Node-derived classes to set some properties immediately (this is even done in the C++ code for nodes like Label).

**Comment by ThakeeNathees** [comment]
the `_init()` method never return any value and receive any arguments, and its being skipped to check function signature for virtual method override (may be for constructor can't be overridden)
https://github.com/godotengine/godot/blob/30ab5c9baae1cad3e157d906395a4eb8cef77e42/core/object.cpp#L1755
https://github.com/godotengine/godot/blob/30ab5c9baae1cad3e157d906395a4eb8cef77e42/modules/gdscript/gdscript_parser.cpp#L7908
in gdscript_parser.cpp every `new` method calls `_init`(a simplified code below) and if it's a native class (Label) it creates `GDScriptNativeClass` instance which then initialize the native class by allocating memory and initialize properties `_post_initialize()` which never needs the constructor argument 
```c++
			bool is_initializer = callee_name == "new";
			...
			if (is_initializer && original_type.is_meta_type) {
			...
				callee_name = "_init";
			...
			}
```
from the above code trying to call `new` with argument is similar to calling `_init` with argument and  calling `new` with argument is invalid with error message `Too many arguments for "_init" call.` for every single node. 
@Calinou

**Review by vnen — CHANGES_REQUESTED** [review]
This should not be an error. We can improve the runtime error message to be more clear when the number of arguments is invalid in the constructor. I think it shouldn't allow the object to be constructed at all.

The check for signature compatibility is important to make sure polymorphism works (i.e. a method called from a variable with a given type will also be valid if the actual value is a subtype). But for constructors you'll always have the actual type, so signature is not important (it's not really an override in this case, you need to call the parent's constructor explicitly).

**Comment by ThakeeNathees** [comment]
closing after https://github.com/godotengine/godot/pull/37923#pullrequestreview-397350075

**Pull request closed without merging**
