### PR TITLE
Allow non-tres text resources (for GDScript and C# currently) to store metadata

### PR DESCRIPTION
**Pull request by Lazy-Rabbit-2001**
The problem comes from https://github.com/godotengine/godot/pull/99748#issuecomment-2504004205
After days of work, I finally figured out a solution.

# `.gdmeta` file
Like `.uid` files, `.gdmeta` files are actually resuffixed config files (sorry but I don't know how to parse a format data file in a better way...), which is placed in the same directory as the resource files. When a text resource (referring to a resource that is stored directly with its texts) contains metadata and is going to store its data, a `.gdmeta` file will be created in the same directory of the resource file. When a resource has no metadata while its metadata file exists, the metadata file will be removed.

# Metadata files for `GDScript` and `C#`
Currently, this PR only supports GDScript and C# to store metadata files, and the other types of text resources will be allowed soon by future PRs of mine or other contributors.
In their definitions of formatters' `save()` and `load()`, there will be `save_meta()` and `load_meta()` respectively in the middle-bottom of the method body, which are defined in `ResourceFormatSaver` and `ResourceFormatLoader` correspondingly.

# Limitations
Currently, I'm not sure whether the method `load_meta()` should be written like that, or should be written with the background of multi-thread programming (i.e. `Mutex` or something else for multi-thread work). If you have better solution, feel free to share yours in this pr. :)

# WIPs
- [x] Add `.gdmeta` file for storing metadatas of text resources, and add meta `save_meta()` and `load_meta()` for operations of the file.
- [x] Allow `GDScript` and `C#` script resources to store metadata.
- [ ] Local test and feedback solution.

### CODE REVIEW

**Comment by Delsin-Yu** [comment]
We should merge `uid` and `gdmeta` and whatever metadata storage comes later, similar to what we did for `import` metadata file.
I'm afraid of metadata file inflation, as you never know when we will have another PR to add the `guidmeta` file for whatever use case. :worried:

**Comment by Delsin-Yu** [comment]
My point is to follow the format we use for `import`, which is TOML. I guess it's a Godot setting format under this context.

But I think we should eventually unify these three metadata files (`uid`, `import`, and your `gdmeta`) in the future.

**Comment by fire** [comment]
Will this break gdextension?

**Comment by KoBeWi** [comment]
> My point is to follow the format we use for import, which is TOML. I guess it's a Godot setting format under this context.

.import files, while effectively use CFG format, write and parse it manually. They don't use ConfigFile class.

**Comment by v6stXN46WdLBtp** [comment]
Merging .uid with this potential .gdmeta would probably be the most preferable. Especially if it could be done before the 4.4 release to avoid a .uid migration case. Multiple small files make things very hard to explore in file explorers and git, so consolidating them into one would help those use cases.

**Comment by akien-mga** [comment]
Before spending too much time on trying to merge `.uid` and this new proposed `.gdmeta` file:

What is the proposal here? Any feature PR needs to be backed by a proposal that shows significant support from the community.

So far we're not clear on any use case we want to support for metadata files, which is why we went with `.uid` and not `.meta` files in the first place (which has been evaluated and rejected - for now).

**Comment by adamscott** [comment]
> What is the proposal here? Any feature PR needs to be backed by a proposal that shows significant support from the community.

To add to that, there's need for actual real use of the metadata. We need real use-cases from the community, not just "it would be nice"

(I'm saying that even if I would love such metadata on script files too)

**Pull request closed without merging**
