### PR TITLE
libpng: Update to upstream 1.6.40

### PR DESCRIPTION
**Pull request by akien-mga**
```
Changes from version 1.6.39 to version 1.6.40
---------------------------------------------

 * Fixed the eXIf chunk multiplicity checks.
 * Fixed a memory leak in pCAL processing.
 * Corrected the validity report about tRNS inside png_get_valid().
 * Fixed various build issues on *BSD, Mac and Windows.
 * Updated the configurations and the scripts for continuous integration.
 * Cleaned up the code, the build scripts, and the documentation.
```

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
"Various build issues" is pretty broad, but I guess it shouldn't be risky if it's in a patch release.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.4.

**Pull request merged**
