### PR TITLE
Windows: Fix MinGW argument being passed to MSVC

### LINKED ISSUE #4620: Cannot compile with MSVC with latest master
**Operating system or device - Godot version:**
Windows 10 x64 - master https://github.com/godotengine/godot/commit/b5e0729fcd21a63fc71fe2f37804a02c1d446e40

**Issue description** (what happened, and what was expected):
When compiling with Visual C++ 2015 x86 i get an error about the argument **/Wno-error=implicit-function-declaration** not being valid. It seems that a GCC switch is appended to the linker even in msvc.

**Steps to reproduce:**
Open Native Vs Command Prompt 2015 x86 and do `scons platform=windows'

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #4620

### CODE REVIEW

**Comment by vnen** [comment]
Hey, but what if it's *not* Windows? I think this should be:

```Python
if (os.name!="nt" or os.getenv("VSINSTALLDIR")==None):
```

Maybe don't need even to check for OS?

**Comment by akien-mga** [comment]
Oops, my mistake. I used ``not (os.name!="nt" and ...)`` at first and changed it, but left it bogus.

**Comment by akien-mga** [comment]
Initially I used: ``if not (os.name=="nt" and os.getenv("VSINSTALLDIR")!=None)``. Maybe that was better? I didn't want to force the argument on e.g. clang if it's necessary only for MinGW, that's why I kept the OS check.

**Comment by akien-mga** [comment]
Hm no actually I can't find a proper solution if we don't want to force the argument on clang. But maybe clang is fine with ``-W`` flags?

**Comment by akien-mga** [comment]
Alright it support a similar syntax to GCC's, so let's just exclude MSVC: http://clang.llvm.org/docs/UsersManual.html#options-to-control-error-and-warning-messages

**Comment by punto-** [comment]
Try printing env['tool'] or env['tools'], don't remember which, but that should tell you which compiler it's configured? "msvc" might show up on windows

**Comment by akien-mga** [comment]
It should hopefully be better with c7292b1.

I tried ``env['tool']`` and ``env['tools']``, the former errors out and the latter returns ``yes`` :-P But yeah finding a proper way to identifier the compiler would be very helpful.

**Comment by punto-** [comment]
Oh right, env['tools'] is a flag we use to configure the build, and 'tools'
is a parameter when we create the environment. Our 'tools' doesn't break
the build out of sheer coincidence :p Try printing env['TOOLS'], that
should be the right one.

Mine prints

['default', 'gnulink', 'gcc', 'g++', 'gfortran', 'gas', 'ar', 'filesystem',
'm4', 'lex', 'yacc', 'rpcgen', 'jar', 'javac', 'javah', 'rmic', 'dvipdf',
'dvips', 'gs', 'tex', 'latex', 'pdflatex', 'pdftex', 'tar', 'zip', 'rpm',
'CVS', 'RCS']

on ubuntu and

['default', 'applelink', 'gcc', 'g++', 'gfortran', 'as', 'ar',
'filesystem', 'm4', 'lex', 'yacc', 'rpcgen', 'jar', 'javac', 'javah',
'rmic', 'tar', 'zip']

on osx while building for both osx and iphone. It should include "msvc"
when on windows and not using mingw

**Comment by akien-mga** [comment]
Nice! We should update the various files of our buildsystem to use that (SConscript, SCsub and detect.py), there are quite a few places were we use hacks such as the one I just committed to detect the compiler.

**Comment by vnen** [comment]
Here what I get in `env['TOOLS']` in Windows: 

```
['default', 'mslink', 'msvc', 'gfortran', 'masm', 'mslib', 'dmd',
 'msvs', 'midl', 'filesystem', 'lex', 'jar', 'javac', 'javah', 'rmic', 'zip']
```

**Pull request merged**
