### PR TITLE
enhance mipmaps, non power of 2 textures

### PR DESCRIPTION
**Pull request by playster000**

### CODE REVIEW

**Comment by hpvb** [comment]
@reduz this is a bit above my paygrade, does this make sense?

**Comment by akien-mga** [comment]
For the reference, the diff is easier to review with `?w=1` appended to remove whitespace changes: https://github.com/godotengine/godot/pull/17232/commits/60b2ee1624ef3eeed0a3be948f1c27b739fcb184?w=1

**Comment by reduz** [comment]
I don't understand what this does

**Comment by reduz** [comment]
If this is a more correct way, seems fine then.. I just find it odd as one row of pixels wont be read properly, but i understand filtering will be better.

**Pull request merged**
