### PR TITLE
Add half-pixel offset to lightmapper rasterization.

### LINKED ISSUE #63437: Vulkan: LightmapGI exhibits light bleeding through occluded areas and face edges
### Godot version

4.0 Alpha 12

### System information

Windows 10, GTX1080, i7 6700

### Issue description

Godot 4 LightmapGI exhibits light bleeding through completely occluded spaces and on the edges of faces.
The latter has the appearance of insufficient padding or texel resolution but seems to happen regardless of resolution.

### Edge Leaks:
These seem to happen regardless of what resolution the meshes are brought in as. Even in this small scene, an atlas resolution of 2048x2048 wasn't enough to resolve. Both shots from Godot 4.
LightmapLeaks_Ultra005Texels
LightmapLeaks_Ultra001Texels

### Edge Leaks, Godot 3 vs 4:
Godot 3's mapper doesn't really exhibit the same leak issues, so this seems to be a regression.
LightmapBleed01_Godot3
LightmapBleed01_Godot4

Occluded Areas, Godot 3 vs 4:
Completely occluded areas also seem to struggle. In this area where the object intersects with the plane, light bleeds through even with Godot 4's mapper set to Ultra.
LightmapBleed02_Godot3
LightmapBleed02_Godot4

### Steps to reproduce

MRP provided. Settings in both projects are matched.

### Minimal reproduction project

Godot 3:
[LightmapQualityExampleG3.zip](https://github.com/godotengine/godot/files/9181454/LightmapQualityExampleG3.zip)

Godot 4:
[LightmapQualityExampleG4.zip](https://github.com/godotengine/godot/files/9181458/LightmapQualityExampleG4.zip)

### LINKED ISSUE #69126: Vulkan: LightmapGI with Environment Mode set to a value other than Disabled exhibits light leaking through one-sided surfaces
*Related to https://github.com/godotengine/godot/issues/63437 (but not the same, as that issue is about general light leaking).*

### Godot version

4.0.beta6

### System information

Fedora 36, Vulkan Forward Plus, AMD Radeon RX 6900 XT

### Issue description

LightmapGI with Environment Mode set to a value other than Disabled exhibits light leaking, especially through one-sided surfaces. This light leaking is caused by environment lighting, which spreads incorrectly through corners.

While this can be worked around to an extent by ensuring all surfaces are two-sided (manifold), one-sided surfaces are fairly common in level design for optimization reasons.

Other things I've tried to no avail:

- Increasing/decreasing Bias on LightmapGI
- Disabling **Use Denoiser**
- Enabling **Interior**
- Increasing bake quality to **Ultra**

Environment Mode: Disabled | Environment Mode: Scene
-|-
 | 
 | 
 | 
 | 

(The little bit of light leaking that remains on the 3rd screenshot is from the shadow map, not the lightmap.)

### Steps to reproduce

- Import a 3D scene with its **Light Baking** property set to **Static Lightmaps**.
- Add a DirectionalLight3D node and WorldEnvironment.
- Add a LightmapGI node.
- Bake lightmaps.

### Minimal reproduction project

[test_lightmapgi_leak.zip](https://github.com/godotengine/godot/files/10086490/test_lightmapgi_leak.zip)

### PR DESCRIPTION
**Pull request by DarioSamo**
Add half-pixel offset to lightmapper to fix issues where the ray would be generated from the wrong spot corresponding to the pixel and causing light leaks. Fixes Issue #69126.

As said in the issue and code comments, this is required so the lightmapper doesn't spawn rays from the very edge of the faces. It _looks a bit hacky at first_ but there's a pretty solid reason behind it and as far as I can tell it fixes leaks in most scenarios I could find. Basically, by using this offset, the interpolated position the pixel shader receives will never be perfectly aligned at the edges of the faces but right on the middle of the pixel, which is what is usually desired.

Denoiser is recommended to be off when testing, as the current denoiser can cause light leaking on its own that doesn't exist in the noisy output due to the blurring.

Before
268679870-9d884417-2fc9-4389-bf2f-cd250e4c0414

After
268679903-96c80adf-a348-4f42-9ca3-09849a7caf2f

Before
image

After
image

(Lighting differences might be due to exposure adjustment or just less light leaking into the scene, but it's to be expected)

Testing out the fix in more scenes would be appreciated.

*Bugsquad edit:*
- Fixes #63437
- Fixes #69126

### CODE REVIEW

**Comment by Calinou** [comment]
Before | After
-|-
Screenshot_20230918_232446 | Screenshot_20230918_232917


Before | After
-|-
Screenshot_20230918_233633 | Screenshot_20230918_233753

**Review by Calinou — APPROVED** [review]
Great work!

**Review by clayjohn — APPROVED** [review]
Looks great! The changes make sense. I haven't tested locally, but I trust that the testing from other reviewers was adequate.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
