### PR TITLE
Don't pass -std=gnu++11 to MSVC

### PR DESCRIPTION
**Pull request by hoelzl**
This gets rid of some compilation warnings with Visual Studio.

### CODE REVIEW

**Comment by Valentactive** [comment]
I think for MSVC you would just use -std=C++11 instead of -std=gnu++11. But in this case we might not even need it maybe.

**Comment by hoelzl** [comment]
Yes, but according to the docs (https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version) there is no /std:c++11 switch, only c++14, 17 and latest. Everything compiles fine without the switch, so it seems best to leave it out.

**Comment by hpvb** [comment]
Could you change this to std=c++11 instead of gnuc++11? Me and @akien-mga were talking about making that change anyway, may as well do it in this PR to reduce shurn on these files.

Thanks!

**Comment by hoelzl** [comment]
No problem. I've pushed a changed PR.

**Comment by Valentactive** [comment]
Maybe because newer Visual Studio version are per default on C++11 (as a comparison Clang 6.0 from SVN also changed in the last days per default even to C++14 if you don't pass specifically another one). The "std=gnu+11" is only really needed for some extensions that are not in the official standard. It's not that important these days honestly (except for very specific libraries maybe). The "std=C++11" on the other hand is accepted by almost all important compilers out there as that would enable the official C++11 standard without those specific extensions.

**Pull request merged**
