### PR TITLE
Optimize `Node::is_readable_from_caller_thread()` by prioritizing the most common case

### PR DESCRIPTION
**Pull request by CrazyRoka**
## Perf: Optimize Node::is_readable_from_caller_thread() for common case

This PR aims to reduce CPU usage within the `Node::is_readable_from_caller_thread()` method, which is frequently called by node property accessors like `Node3D::get_position()`.

Profiling revealed very high CPU usage inside `Node3d::get_position()`. This PR reorders the conditions to prioritize the most common case where current thread is safe. 

### Benchmarks

This optimization leads to a significant reduction in CPU usage within the `Node3D::get_position()` method.

**Before:**

image

**After:**

image

This change should improve performance, especially in scenes with frequent node property access. 

### Testing

Tested locally with a scene that contains 20K cubes, all of them were moving around.
Profiled application before and after my change. Initial implementation was causing 5.54% of CPU usage on my laptop. Optimized version is using 1.12% of CPU.

Link to the test project: https://github.com/CrazyRoka/godot-benchmark-moving-cubes/tree/main

### CODE REVIEW

**Comment by RandomShaper** [comment]
It makes sense because the thread being safe for nodes is the most likely situation, so performing the other check before is worse.

However, to make the code more telling about this analysis I'd suggest decorating the `!data.inside_tree` check with `unlikely()`.

Could you please test if that delivers the same results without changing the order of the checks in the code? I'm not against changing the order in addition to adding the decoration, but I'm curious...

**Comment by CrazyRoka** [comment]
> Could you please test if that delivers the same results without changing the order of the checks in the code? I'm not against changing the order in addition to adding the decoration, but I'm curious...

I've just tested with `unlikely` and without changing the order. Results are very similar. Do you think it makes sense to change the order and use `unlikely` together? I can prepare a second revision if you agree.

```cpp
-                       return is_current_thread_safe_for_nodes() || !data.inside_tree;
+                       return unlikely(!data.inside_tree) || is_current_thread_safe_for_nodes();
```

image

**Comment by RandomShaper** [comment]
Thanks. Let's do both changes. The `unlikely()` should be the one that matters, but if a compiler doesn't honor it, at least source order will.

**Comment by CrazyRoka** [comment]
> Thanks. Let's do both changes. The `unlikely()` should be the one that matters, but if a compiler doesn't honor it, at least source order will.

I published a new revision and tested it locally with same results. Can you please review?

Also, don't you mind checking another PR? Your review is required for this: https://github.com/godotengine/godot/pull/94118

**Review by RandomShaper — APPROVED** [review]

**Comment by RandomShaper** [comment]
@AThousandShips, I think this is safe for 4.3.

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
