### PR TITLE
Enhance the tilemap transform buttons

### PR DESCRIPTION
**Pull request by groud**
This PR enhance the tilemap editor. It does:
- replace the existing transform buttons by 5 simpler buttons: clear transform, horizontal flip, vertical flip, rotate 90° left and rotate 90° right.
- displays the results of the transform directly on the palette.

Note that I had to a modify the ItemList class so that it can display transposed icons.

Preview: 

output

### CODE REVIEW

**Comment by groud** [comment]
Note, I think the rotate left / rotate right deserve new icons. 
I used the previous one for now but I think arrows would be more appropriate.

**Comment by akien-mga** [comment]
That looks great overall, but there's one thing missing that the previous system provided: there is no visual indication of which properties are enabled (`flip_h`, `flip_v`, which rotation if any). The previous systems marked the buttons as pressed (blue icon). This could still be done for the flip properties, for rotation where there are 4 possible states split over 2 buttons, it's maybe trickier. But currently to know if you have any non-1 transform applied, you'd basically have to use the reset button.

Speaking of which, I think the reset button should come last, not first.

**Comment by groud** [comment]
I don't think the visual indication of flipped stuff is really important. It does not provide important information to me, as this is already visible on the tile themselves. Also, I see them as action buttons, not "state" ones, that's why I did not brought back the blue color.


The only missing info could have been whether or not the tile was modified, but this is provided by the clear button being disabled or not.

I can indeed move the button to the right.

**Comment by groud** [comment]
But I'm not complitely against it the proposal makes sense too as, internally, it only toggles the flip_* value.

**Comment by groud** [comment]
I updated the PR to reorder the buttons: 
2018-10-30-144832_158x175_scrot

**Pull request merged**
