### PR TITLE
Added Left / Right arrow navigation in tree, issue 10737

### LINKED ISSUE #10737: Collapse / expand child nodes in scene tree by using left- / right-arrow keys
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.3
Godot 3

**Issue description:**

When navigating inside the scene tree using the keyboard, only the up-arrow and the down-arrow keys are working to select other nodes.

It would be helpful to be able to collapse all children nodes by pressing the left-arrow-key.
If there are no child-nodes, the selection should jump to the parent of the currently selected node.

If there are child-nodes, the right-arrow-key should expand these children.

Edit:
If the child-nodes are already expanded, the right-arrow-key should jump to the first child.
if there are no-child nodes, the right-arrow-key should jump to the next sibling

This way the tree could easily be traversed by holding the right-arrow-key.

Edit 2: 
As mentioned below, pressing the alt-key additionally could be used to expand/collapse all sub-nodes up to the scene-tree-leaves.

### PR DESCRIPTION
**Pull request by Paulb23**
Added Left / Right arrow navigation in tree.

Pressing left/right will collapse/expand the node, providing you are on the end column, if its already expanded/collapsed it will move up/down.

Pressing alt will collapse/expand the current and all its child nodes.

closes #10737

### CODE REVIEW

**Comment by hpvb** [comment]
LGTM

**Comment by BeayemX** [comment]
Hey thanks for implementing this!

Even though I have one suggestion. It should be possible to jump to the parent without going through all the previous siblings until the parent is reached.

Imagine you have 100 children nodes and the last one is selected, you would have to scroll through 100 nodes by holding Left until you can collapse the parent. Maybe Left should always jump to the parent when there are no children or the children are collapsed, because under that condition Left and Up have the same behavior .

Or alternatively this could be done by using Alt+Left when there are no children or they are already collapsed.

I think this would make navigating even easier.

**Comment by Paulb23** [comment]
@BeayemX It's not exactly like Up/Down arrows as it will round-robin the columns ie 
```
123
456
```
Whereas Up/Down will go vertically keeping the current column. Though I'd be up for adding another shortcut to make the jump to its parent.

**Comment by BeayemX** [comment]
I don't quite understand what you mean by round-robin the columns, are you using this inside the scene tree area?

As a side note: using the left arrow to jump to the parent directly is used in the Unity hierarchy area, in visual studio, in the windows file explorer side bar and in atom (with the exception that it also automatically collapses the parent). Maybe we should go with the same behavior?

**Comment by Paulb23** [comment]
@BeayemX  This applies to all trees. A tree can have multiple columns (editor_shortcuts is an example) so it will loop through the columns before dropping into the next row. 

However if that's the expected behavior, we could check for a single column, if so jump up to the parent else keep the current behavior?

**Comment by BeayemX** [comment]
Wow, I was only testing with the scene tree because that's where I use these shortcuts the most, I didn't notice the multi column stuff, that's really great.

But yeah, for single columns I think jumping to the parent would be the preferred behavior.

**Pull request merged**
