### PR TITLE
Show the 3D transform gizmo in the center when otherwise offscreen

### LINKED ISSUE #2673: Show the 3D transform gizmo when otherwise offscreen
### Describe the project you are working on

A 3D game in Godot that has objects that need positioning using the transform gizmo.

### Describe the problem or limitation you are having in your project

If the center/pivot/origin/etc of the object is not visible on screen, the gizmo currently isn't visible either. In some other prorgrams, the gizmo is always on screen. For example, @LillyByte uses [Nvil](https://store.steampowered.com/app/592350/Nvil/) which does this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The proposed feature is that, in cases where the gizmo currently is not on screen, the transform gizmo would be moved to be somewhere on screen. This can be helpful when trying to position an object when the center isn't on screen. For example, a character whose origin/pivot/etc is in the middle, but your camera is pointing at the feet that you're trying to align with the ground.

There are some open questions about where exactly to put the gizmo, if it should be put in the middle of the screen or on the edges. One argument in favor of placing the gizmo on the edges is to avoid teleporting the gizmo to the center, however there would instead be weird behavior if the gizmo was directly behind the camera.

Another question is if there should be a line pointing to where the object is. This makes sense, although I'm not sure what would be the proper way to do this inside of the 3D editor (should we use a 3D line, if so how? Or a screen space Line2D?).

There is also an open question about whether this should be a setting, as some users may not desire this functionality. If so, what should be the default setting?

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here is my work-in-progress implementation: https://github.com/godotengine/godot/pull/48307

https://user-images.githubusercontent.com/1646875/116612981-27f1fb80-a906-11eb-8fe7-a226bcef8ae7.mp4

Screenshot from 2021-06-19 20-28-46

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's part of the 3D editor.

### Is there a reason why this should be core and not an add-on in the asset library?

It can't be, it's part of the 3D editor.

### PR DESCRIPTION
**Pull request by fire**
Salvaging https://github.com/godotengine/godot/pull/48307

See also https://github.com/godotengine/godot/issues/57839

Fixes: https://github.com/godotengine/godot-proposals/issues/2673

### CODE REVIEW

**Comment by fire** [comment]
Tracker:

* https://github.com/godotengine/godot/issues/57839
* https://github.com/godotengine/godot/issues/57839

**Comment by fire** [comment]
@mbrlabs Cab you test again?

**Comment by fire** [comment]
ready for merge

**Comment by aaronfranke** [comment]
Does not work as expected. The line does not update after the first time it goes off screen. Some tests: try moving/rotating the camera once the object is off screen, and try resizing the viewport once the object is off screen.

Screen Shot 2022-09-06 at 6 07 40 PM

**Comment by fire** [comment]
Seems like the caching is too agressive.

**Comment by fire** [comment]
I retreated to removing the line. I'm not sure what happens to the node transform when the camera can't project it.

If this isn't ok, will probably need to drop this pr or think of an easier approach.

**Comment by reduz** [comment]
I think whatever is done here, if there is agreement that this is an useful feature, it should be an optional toggle.

**Comment by Calinou** [comment]
> I think whatever is done here, if there is agreement that this is an useful feature, it should be an optional toggle.

I would avoid adding settings for the sake of adding settings. Settings should only be added if there's significant demand from the community. In particular, features should never be disabled by default (unless they're accessibility options), as this pretty much guarantees a feature would remain unused most of the time (and therefore be dead weight in the binary).

**Comment by Saul2022** [comment]
I am not sure what you think, but maybe the merge could be a togglable option in the transform or view tab, but the option is enabled by default. As such it could be documented in the documentation. And then if after some weeks  people are happy with this feature or not, it could be enabled or disabled.

**Comment by Saul2022** [comment]
> Having been playing with this for a while in my fork, I will say it is very confusing when the gizmo ends up in the center of the screen because there is visually no difference between editing an object that is exactly in the center of the screen (such as focused with the `F` key), and one which is completely off the edge of the screen.

> Otherwise, I wonder if it might make sense to have the gizmo on the edge of the screen instead? Not really sure the right thing to do here. Are there any other applications which behave in this way that we could draw inspiration from?

maybe it would be good to add lilly idea about that, and also change the color 
Screenshot_2023-02-12-07-07-49-73_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by fire** [comment]
I have not been a good caretaker of this. Consider it salvagable.

**Comment by Zireael07** [comment]
Do we have a salvageable label?

**Comment by AThousandShips** [comment]
We do and this PR has it

**Comment by Zireael07** [comment]
Ah right I only saw the notification about archived label

**Pull request closed without merging**
