### PR TITLE
Fix `TabBar._update_hover` crash

### LINKED ISSUE #57710: Executing `TabBar._update_hover` crashes Godot
### Godot version

4.0.dev.custom_build. 9d1626b4d

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

When executing
```
func _process(delta):
	var temp_variable13269 = TabBar.new()
	add_child(temp_variable13269)
	temp_variable13269._update_hover()
```

Godot crashes with this backtrace
```
ERROR: Index p_index = 0 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:163)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.alpha.custom_build (9d1626b4d7a867b4778845dd12519c603f0cf88f)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x46520) [0x7f7528a2b520] (??:0)
[2] CowData<TabBar::Tab>::get(int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/cowdata.h:163 (discriminator 7))
[3] Vector<TabBar::Tab>::operator[](int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/vector.h:92)
[4] TabBar::_update_hover() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/tab_bar.cpp:769)
[5] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:237 (discriminator 4))
[6] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:380)
[7] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:280)
[8] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:837 (discriminator 1))
[9] Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/variant_call.cpp:1021)
[10] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1510)
[11] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1521)
[12] Node::_gdvirtual__process_call(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:230 (discriminator 5))
[13] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:57)
[14] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:48 (discriminator 14))
[15] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:848)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:856)
[17] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:456 (discriminator 2))
[18] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2693)
[19] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:342)
[20] /home/rafal/Downloads/godot.linuxbsd.tools.64(main+0x16c) [0x22bda32] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[21] /lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0) [0x7f7528a12fd0] (??:0)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f7528a1307d] (??:0)
[23] /home/rafal/Downloads/godot.linuxbsd.tools.64(_start+0x2e) [0x22bd80e] (??:?)
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)


```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by pfertyk**
Fixes #57710.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
`_update_hover()` shouldn't have been bound in the first place. It's something meant to be used from outside.

**Comment by pfertyk** [comment]
Should I change the name to `update_hover` ?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks like the binding could be removed indeed, at least in that class nothing refers to it by string.

**Comment by YeldhamDev** [comment]
@akien-mga Done: #57782

**Comment by akien-mga** [comment]
I was thinking we could have both changes in the same commit :)

**Comment by pfertyk** [comment]
I've replaced the if statement with `ERR_FAIL_COND` and removed the binding (like in @YeldhamDev 's PR). Please let me know if we need anything else ;)

**Comment by YeldhamDev** [comment]
I don't think that `!is_inside_tree()` should trigger `ERR_FAIL_COND`, it should still just return in that situation.

**Comment by pfertyk** [comment]
Changed as requested @YeldhamDev ;) I just realized that there are 3 commits in this branch, can you merge them into one using "squash and merge" on GitHub or should I fix the situation?

**Comment by akien-mga** [comment]
You should squash the commits locally and update the remote branch with a force push, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

**Comment by YeldhamDev** [comment]
The check for `!is_inside_tree()` should be done before the one for tab quantity.

**Comment by pfertyk** [comment]
Conditions reordered, commits squashed ;)

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
