### PR TITLE
Separate TextShaderEditor and ShaderEditorPlugin into different files

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR is entirely about organization in the editor code, it has no behavior changes.

The first commit renames `ShaderEditor` to `TextShaderEditor`, because it exclusively edits text shaders. The second commit moves `TextShaderEditor` and its helper classes into their own file, separated out from `ShaderEditorPlugin`, just like how `VisualShaderEditor` and its helper classes are already separated into their own file.

### CODE REVIEW

**Review by Paulb23 — COMMENTED** [review]
Shouldn't the file be called `shader_text_editor`? Given the class is `ShaderTextEditor` and to align it with `script_text_editor`.

**Comment by aaronfranke** [comment]
@Paulb23 No, the class is `TextShaderEditor`. Look at line 107 of the header. `TextShaderEditor` is the big class that has all of the code for editing text shaders, while `ShaderTextEditor` is an internal-only helper that inherits `CodeTextEditor`. I know the names are kinda similar, not sure how to make this less confusing, maybe `ShaderCodeTextEditor`?

**Comment by Paulb23** [comment]
Oh I see, that is confusing.

Looking at it again, we could probably get rid of `ShaderTextEditor` by merging it with `TextShaderEditor` (well would rename this `ShaderTextEditor` I guess) and have it use `CodeTextEditor` directly. Then it would work similarly to `ScriptTextEditor`. Except for extending `MarginContainer` rather then `ScriptEditorBase`.

I can't see a way to make these names less confusing otherwise unless we go with `ShaderTextEditorContainter` which is starting to get a bit ridiculous.

**Comment by aaronfranke** [comment]
@Paulb23 That makes sense, but that can be left to another PR. For this one I just want to give what we have a better name and move it out of the shader editor plugin file (similarly to how the visual shader editor is in its own file).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
