### PR TITLE
VisualScript sync and improve dropped variable and property

### PR DESCRIPTION
**Pull request by Gallilus**
The editor will no longer drop VisualScriptVariableGet or VisualScriptVariableSet when dragging in script variables.
That is now replaced by VisualScriptPropertyGet and VisualScriptPropertySet. These are more versatile so there is no reason to keep VisualScriptVariableSet/Get and may be deleted in another PR

Goal: less maintenance and more uniformity

VisualScriptVariableGet 
image
VisualScriptPropertyGet 
image

When possible the base_script information will be filled in this will give better autocompletion in the future.

This PR does not break compatibility with older versions.
CC: @fire

### CODE REVIEW

**Comment by fire** [comment]
Do you think VisualScriptVariableSet/Get should be deleted in this pr?

**Comment by Gallilus** [comment]
No, I think VisualScriptVariableSet/Get should be deleted in separate pr?
Easier when you want to backport this.

**Comment by LightningAA** [comment]
> No, I think VisualScriptVariableSet/Get should be deleted in separate pr? Easier when you want to backport this.

It could be done in a separate commit

**Review by fire — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
