### PR TITLE
New icons for ParallaxBackground & ParallaxLayer

### PR DESCRIPTION
**Pull request by projekt2502**
**ParallaxLayer** only works inside **ParallaxBackground**, icons make sense now.

Illustration

### CODE REVIEW

**Comment by akien-mga** [comment]
Sorry for the late review.

This makes sense but having two icons with different size like this looks weird. The "superimposed" icon makes sense logic wise but since it's never used it doesn't really matter.

I would make the ParallaxBackground icon the same size as the ParallaxLayer one, and the difference is that one is full, and one is only a contour.

**Comment by aXu-AP** [comment]
It seems that something went wrong with rebase. If you want, I can do it instead 😊

**Comment by junkajii** [comment]
i add the change of https://github.com/godotengine/godot/pull/72472 removing `opacity` too
and i think icons can't need `transform=translate` info and `g` tag i remove here too. (some icons yet have this things and can be cleaned)
```
// remove
<g transform="translate(0 -1036.4)">
transform="translate(0 1036.4)"
```

**Comment by YuriSizov** [comment]
@junkajii I'm not sure what it is that you're doing on your end, but it doesn't look like you're rebasing your PR against the current master. Make sure you fetch all the changes in the upstream (this) repository before attempting to rebase.

**Comment by junkajii** [comment]
@YuriSizov maybe i fix now

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks, and congrats on the first merged PR! Sorry it took as so long.

**Pull request merged**
