### PR TITLE
Fix Gradient Documentation's PackedColorArray default

### PR DESCRIPTION
**Pull request by Innocent-Traitor**
Fixes the default PackedColorArray default to reflect the correct way to construct a PackedColorArray.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for your contribution!

However this is not how these arrays are serialised and that's how the documentation defaults work, this would require a change of the core serialisation system which would break existing files or at least force all text base resources to be updated

The documentation files are generated automatically and as you can see this doesn't work as they are corrected to how they should be generated 

This is not a valid change in this form

**Comment by Mickeon** [comment]
> Also changing the way this type is serialised would make text based resources much larger, which isn't a good idea IMO

If anything it's been suggested the serialization should be **shorter**.

Changing the way all of these properties are displayed in the class reference would be a more ideal and encompassing solution.

So, not in favour of this PR, it cannot work as is.

**Comment by akien-mga** [comment]
I think we should change how the defaults are displayed in the EditorHelp (and in the generated rst), but not change the serialization indeed which is just a packed array of floats.

**Comment by AThousandShips** [comment]
> I think we should change how the defaults are displayed in the EditorHelp (and in the generated rst), but not change the serialization indeed which is just a packed array of floats.

Agreed, was going to suggest this, shouldn't be difficult will take a look at an implementation

**Pull request closed without merging**
