### PR TITLE
Remove unnecessary sections when exporting .import files

### PR DESCRIPTION
**Pull request by martok**
This adds logic to the editor to "strip" .import files when exporting to pack files by dropping the params and deps sections before storing the file.

Rationale: the `[params]` section is only used by the editor and not during runtime. In fact, only the `[remap]` section is used when loading a resource by following an import to the stex/scn/etc. However, the params can be excessively large for some resource types, which adds data that has to be stored, read, parsed etc. whenever it is accessed. In some cases (PackedScene, this is how I noticed it), the .import can even be much larger than the data it refers to.

This PR is based on master, the feature itself has been tested on 3.2 and is easily cherry-pickable.

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm not sure that's a good idea, instead I would aim to fix this which is a bug IMO:

> However, the params can be excessively large for some resource types, which adds data that has to be stored, read, parsed etc. whenever it is accessed. In some cases (PackedScene, this is how I noticed it), the .import can even be much larger than the data it refers to.

Please open an issue with a minimal reproduction project. Import parameters should not be a significant amount of data.

**Comment by martok** [comment]
> Please open an issue with a minimal reproduction project. Import parameters should not be a significant amount of data.

That would be a rerun of the closed godotengine/godot-proposals#1060. I hadn't actually seen before implementing this PR that it had been closed since I last read that issue about 2 weeks ago, but you already stated (IMO correctly) that there is no good forward-compatible way to make them smaller _for editor use_, since the defaults have to be stored regardless.

Since there is no way for ResourceFormatImporter to do anything but load the remap (the source file is not present, after all), I don't think there is any issue in just not having the import parameters stored?

**Comment by akien-mga** [comment]
>> Please open an issue with a minimal reproduction project. Import parameters should not be a significant amount of data.
>
> That would be a rerun of the closed godotengine/godot-proposals#1060.

No, I'm asking for an issue about this:

> However, the params can be excessively large for some resource types, which adds data that has to be stored, read, parsed etc. whenever it is accessed. In some cases (PackedScene, this is how I noticed it), the .import can even be much larger than the data it refers to.

godotengine/godot-proposals#1060 is a proposed solution, but it's not about the problem you mentioned. This is a typical [XY Problem](http://xyproblem.info/) situation.

**Comment by martok** [comment]
Right, no problem. Just to make sure it's clear, for me these are two orthogonal issues that don't have anything fundamentally to do with each other:

1. Some .imports are large(r than the source). This bothers some people, but I'm not one of them. Reported as #42468.
2. Exporting a game stores information that cannot be accessed without the editor (only ImportDock and EditorFileSystem read it), causing larger than strictly necessary packs. This would be less immediately obvious without (1), but is true independently. There may (I don't know) even be cases where this exposes information the developer is not aware of when releasing a game. This is what this PR addresses.

**Comment by akien-mga** [comment]
Yeah I agree that the problems are orthogonal, but if there was no problem with heavy `.import` files, there would be less incentive to go all the way to get this information removed from exports IMO, if the size gain was insignificant. Now #42468 shows that it doesn't seem to be a bug a priori that some files can end up serializing a ton of animation data, which does make this PR a meaningful optimization.

**Comment by fire** [comment]
Why is deps removed?

**Comment by martok** [comment]
> If you're using these properties at runtime, the info is lost.

That's the thing: it is not possible to use them at runtime. There is no code that accesses these properties outside of two editor-only classes. Nothing is lost.

In reply to an earlier version of your comment: don't think of it as removing info, instead creating a new remap-only file similar to the one placed by the "convert resources to binary" export option. Only the implementation is much simpler this way as the file happens to be already parsed.

> Yes, the .import is 31.8kb which compresses to 3.5kB.

PCK is not compressed, at least I found no option for it? But the size is not my issue, it's just really obvious if over 60% of the pack are useless information.

**Comment by Calinou** [comment]
> PCK is not compressed, at least I found no option for it?

Indeed, PCK is not compressed to speed up random access.

**Comment by fire** [comment]
Is there a proposal for this? I might have lost it.

**Comment by martok** [comment]
> Is there a proposal for this? I might have lost it.

There is none. When I made this PR, GIPs were optional for small changes and a finished PR was a valid starting point. Has this changed?

**Comment by Calinou** [comment]
> There is none. When I made this PR, GIPs were optional for small changes and a finished PR was a valid starting point. Has this changed?

No, but opening a proposal increases the changes of this pull request getting merged.

**Comment by martok** [comment]
I work in the public sector... I know what it means when after 8 months, one gets asked to _fill out another form_.

But in all seriousness, in my mind, this here is still a fix to a pre-existing bug/annoyance and not a new feature like the proposals.

I am unsure what a proposal even should be about, beyond [#4](https://github.com/godotengine/godot/issues/42441#issuecomment-702246143). I guess the problem could be generalized to something about size or "data-spill" optimizing the export, but that sounds even less likely to be accepted as-is since it sounds like a larger rework of the packaging itself which would require much more careful elaboration. Plus, I don't immediately know _any_ other problems.

**Comment by fire** [comment]
I don't understand the problem this solves. Sorry.

**Comment by filipworksdev** [comment]
I have tested this PR. Causes no side effects on exports. It seems that indeed both `[params]` and `[deps]` sections are used only by the editor while in the exported project only taking additional space.

**Comment by fire** [comment]
My argument is we should keep this metadata. I'm trying to filling in mentally your proposal and I can't determine how this pr is essential to your game.

Also the metadata is smaller than a single compressed 2d texture.

**Comment by filipworksdev** [comment]
Hi @fire  I'm only testing to as a second opinion. I usually pick older unresolved prs to test and report back here maybe start a 
process to cleanup and resolve some of these older PRs. 

Size can accumulate but you are right is not that much. The most I managed to get was doubling a project size by using a lot of very small files. 

What about his second concern of being a potential security issue. Will presence of  `[deps]` and `[params]`  in the pck allow for a game to be more easily hackable, crackable, modifiable?

**Comment by fire** [comment]
The security issue that is worse than https://github.com/bruvzg/gdsdecomp for an official godot engine developer?

**Comment by reduz** [comment]
It kind of makes sense, but I would not implement it this way, as this risk making export times slower. Headers are warranted to be in order, so maybe just using the line parser to read the relevant headers and skip the rest?

**Comment by martok** [comment]
I'm not hung up on any particular implementation, this implementation is basically what I was aware of at the time.

You bring up an interesting point, larger import files probably affect parsing time at runtime. That would make minimizing them a (small) performance enhancement?

**Comment by AThousandShips** [comment]
Closing as OP's fork and branch no longer exist

**Pull request closed without merging**
