### PR TITLE
Fix empty script interface crash on tscn load. #23495

### LINKED ISSUE #23495: Switch to the empty script interface and godot forces quit when the tscn scene file with script is loaded
**Godot version:**
 godot3.1 alpha2

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000
4g ram

**Issue description:**
peek 2018-11-04 14-07

**Steps to reproduce:**
1.Open a scene without a script (or not a loaded, empty scene)
2.Switch to script interface
3.Open a scene file with script

**Minimal reproduction project:**
[Test2.zip](https://github.com/godotengine/godot/files/2545616/Test2.zip)

### PR DESCRIPTION
**Pull request by fire**
Add fail conditions to protect the visual script functions and also fix the initiating cause.

@akien-mga Do you prefer if I fix the initiating cause, add the ERR_FAILs or both?

*Bugsquad edit:* Fixes #23495.

### CODE REVIEW

**Comment by fire** [comment]
Noticed an error with visual script function creation adding all VS functions rather than just the node's virtuals.

godot windows tools 64_2018-11-05_13-28-45

I'll make an issue for it.

**Comment by fire** [comment]
I think you can name a function anything as a node, so it would be good if has_function didn't crash.

**Comment by akien-mga** [comment]
> I think you can name a function anything as a node, so it would be good if has_function didn't crash. 

Would it crash though? `has_function` only uses `Map<StringName, ...>::has()`, which can take any kind of `StringName` and should return false if it's not in the map.

**Comment by fire** [comment]
I think my problem is that functions becomes null but that's not solved by the fails check.  Functions being null is when scripts is null.

**Comment by fire** [comment]
Removed has_function.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
