### PR TITLE
Add disabled theme icons for CheckBox

### LINKED ISSUE #8640: CheckBox and CheckButton don't change appearance when set to disabled.
**Godot version: 3.0 master**

**Issue description:**
CheckBox and CheckButton don't dim or change color when set to disabled.
Probably they are not finished in new Theme but not 100% sure.

### PR DESCRIPTION
**Pull request by KoBeWi**
Resolves #8640
image

~~HOWEVER I have no idea how to optimize the new images, so if anyone could advise what to use it would be nice >_>~~

### CODE REVIEW

**Comment by Calinou** [comment]
> HOWEVER I have no idea how to optimize the new images, so if anyone could advise what to use it would be nice >_>

I use [oxipng](https://github.com/shssoichiro/oxipng) or sometimes [OptiPNG](http://optipng.sourceforge.net/) with the following options:

```bash
# For larger images
oxipng -Zso6 image.png
# or:
optipng -o6 -zm1-9 -strip all image.png

# For small images (it's slow on large images)
oxipng -so6 image.png
# or:
optipng -o6 -strip all image.png
```

**Comment by KoBeWi** [comment]
Ok, images optimized.

**Review by Calinou — APPROVED** [review]
The default project theme will likely be overhauled for 4.0, but this is a good change in the meantime that can be cherry-picked to the `3.x` branch after 3.3 is released.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by Deozaan** [comment]
I just updated my project from 3.3.4 to 3.4 and this broke things for me. I'm using a custom theme based off the Editor theme, and it seems the Editor theme was not updated for 3.4 to include the new disabled icons.

So now I have mismatched icons when disabling/enabling any `CheckBox` nodes.

godot-3 4-checkbox

Godot 3 4 disabled CheckBox

Because the Editor theme doesn't have the disabled icons, I can't just import them into my theme.

Godot 3 4 Editor Theme CheckBox Icons Import

Meanwhile, the default theme of course does have them.

Godot 3 4 Default Theme CheckBox Icons Import

**Comment by Zireael07** [comment]
@Deozaan: There were enough changes in EditorTheme that your best bet is probably to reexport the theme anew.

**Comment by KoBeWi** [comment]
@Deozaan You can find these icons under EditorIcons group in the editor theme. They are called GUIChecked/UncheckedDisabled.

**Comment by Deozaan** [comment]
> There were enough changes in EditorTheme that your best bet is probably to reexport the theme anew.

@Zireael07 That's probably a good idea, but I don't see how that will help with the missing icons.

> You can find these icons under EditorIcons group in the editor theme. They are called GUIChecked/UncheckedDisabled.

@KoBeWi I don't see them.

Godot 3 4 Editor Theme EditorIcons Disabled

**Comment by KoBeWi** [comment]
You are right, they only exist in 4.0. They were added in #51722 and never backported. I opened an issue: #54742

In the meantime, if you need to use these icons, you can get them here:
https://github.com/godotengine/godot/blob/master/editor/icons/GuiRadioCheckedDisabled.svg
https://github.com/godotengine/godot/blob/master/editor/icons/GuiRadioUncheckedDisabled.svg
https://github.com/godotengine/godot/blob/master/editor/icons/GuiCheckedDisabled.svg
https://github.com/godotengine/godot/blob/master/editor/icons/GuiUncheckedDisabled.svg

**Comment by Deozaan** [comment]
Thank you!

**Pull request merged**
