### PR TITLE
GDScript: Fix conflict between property and group names

### LINKED ISSUE #67865: Singletons inaccessible when an exported group has the same name
### Godot version

4.0 beta3

### System information

Linux Manjaro, AMD Ryzen 2500U, Radeon Vega 8

### Issue description

Trying to access the Time singleton after naming a group "Time" using `@export_group("Time", "time")` produced the following error message: 
> Invalid call. Nonexistent function 'get_unix_time_from_system' in base 'Nil'

Commenting out the `@export_group("Time", "time")` line was what it took to fix this issue, so did changing "Time" to "Time ".

### Steps to reproduce

Write a script with an `@export_group` call, giving it the name of a singleton, such as "Time" or "RenderingServer", then try to access that singleton in any way.

### Minimal reproduction project

[SingletonNil.zip](https://github.com/godotengine/godot/files/9858998/SingletonNil.zip)

### LINKED ISSUE #68030: @tool and @export_group("", "") after prefixed @export_group do crash editor
### Godot version

4.0.beta3

### System information

Windows 10

### Issue description

@tool and little sorting out with @export_group do crash editor. I don't know if I actually made a mistake and this is not how it's supposed to be used but I'm sure that it shouldn't crash the whole engine

### Steps to reproduce

1. Attach @tool script onto a scene
2. With scene open, make a prefixed group and close it with @export_group("", "")
3. Make another prefixed group and close it with ("", "") as well.
4. Play around with commenting closing strings and immediately saving them
5. Enjoy your crash

minimal project attached

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/9894439/bug.zip)

### LINKED ISSUE #73843: Invalid call. Nonexistent function 'new' in base 'Nil'. if you use @export_group with same class name
### Godot version

4.0 RC 3

### System information

Macbook m1

### Issue description

If I normally use:
```
Skeleton2D.new()
```

if works.

If I use:
```
@export_group("Skeleton2D")
...
Skeleton2D.new()
```

I get error: `Invalid call. Nonexistent function 'new' in base 'Nil'.`

### Steps to reproduce

- Run a script where you have `@export_group` with same name as a node class name that you use `.new()` on.

```
extends Node2D
class_name Test

@export_group("Skeleton2D")

# Called when the node enters the scene tree for the first time.
func _ready():
	var skeleton = Skeleton2D.new()


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
```

### Minimal reproduction project

[BugNew.zip](https://github.com/godotengine/godot/files/10818936/BugNew.zip)

### LINKED ISSUE #78252: Using @export_category using the same name as a variable will overwrite the first variable in the category.
### Godot version

4.0.2.stable.mono

### System information

Windows 10 - 4.0.2.stable.mono - Any Renderer

### Issue description

In a script with an `@export` variable (with a non-default value), Godot will replace the first variable in the category with the same name. For example, if you're exporting a variable called "Vector", and the value is set to a non-default value, the first variable in the category called "Vector" will also be changed to the same value.

### Steps to reproduce

Attach said script to a node:
```
extends Node

@export var Vector: Vector2
@export_category("Vector")
@export var Var2: float = 1

func _process(delta):
	print(Var2)
```
When changing the value of the `Vector` export variable, the variable Var2 will contain the same value. This does not happen when the `@export_category` has a different name.

### Minimal reproduction project

N/A

### LINKED ISSUE #79804: Using the same export_group name in an inherited class and re-saving that class while the project is running crashes the project and sometimes the editor
### Godot version

4.1.1

### System information

Windows 10, i711800H, Forward+ Vulkan

### Issue description

When using @export_group("Name") in a BaseClass, then inheriting from that BaseClass in another class and there also using @export_group("Name"), with the same group name, then running the project and re-saving the inherited class the project crashes with 
```
ERROR: FATAL: Index p_index = 3 is out of bounds (size() = 3).
   at: get (./core/templates/cowdata.h:155)
```

sometimes the editor crashes too after a while.

### Steps to reproduce

1. open reproduction project
2. Run the project.
3. Open the "super"script
4. Press CTRL + S to save it.

### Minimal reproduction project

[MRP_.zip](https://github.com/godotengine/godot/files/12137412/MRP_.zip)

### LINKED ISSUE #79861: @export_category creates a variable that causes issues if another one has the same name
### Godot version

4.1.1stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3050 Laptop GPU (NVIDIA; 31.0.15.3179) - 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 Threads)

### Issue description

So, to make my code better I was using `@export_category("HEALTH")` to create categories in the editor.
Also, right under that, I had ```@export var HEALTH = 30; var current_health: float```. 

Turns out, the `@export_category` creates a boolean variable with the same name as my health variable with caused issues when I wanted to set `current_health` to `HEALTH`. 

Never in the editor this was said or implied by a console error.
I simply fixed it by removing `@export_category` even though I could have changed the name of the category instead.

Just wanted to point that out in case this wasn't intended.

### Steps to reproduce

Try the following code:

```gdscript
@export_category("NAME")
@export var NAME = 1
var my_name: int

func _ready():
    my_name = NAME

func _physics_process(delta):
    print(NAME)
    print(my_name)
```

### Minimal reproduction project

N/A

_Bugsquad edit:_ Fix formatting.

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #67865.
* Closes #68030.
* Closes #73843.
* Closes #78252.
* Closes #79804.
* Closes #79861.

### CODE REVIEW

**Comment by dalexeev** [comment]
Probably also covers #73843. See #73870, #73905 and #73933. I think #73870 can be safely reintroduced after this PR (but it requires testing).

СС @vnen

**Comment by YuriSizov** [comment]
Groups and categories are also properties, they just have special flags that make them behave differently. So the error that the user is facing is not a bug but a design limitation. While we can work around it somewhat with this PR, I think we should instead err and report name collisions in the parser. That would be more correct in terms of what the engine expects from the user input.

**Comment by dalexeev** [comment]
But you can achieve this with `_get_property_list()` and the Inspector handles this correctly (see test case output). `@group_*` is the key of the internal `HashMap` (which, unlike the property list, does not support repetitions), not the real name of the property. I don't think it makes sense to not allow it.

Also, #73843 is a bug anyway.

**Comment by YuriSizov** [comment]
Well, the inspector is pretty dumb, it just displays things :) But this structure of properties is still an error, because it implies you have 2 properties with the same name and different configuration. If anything, we should validate this more strictly in ClassDB as well.

**Comment by adamscott** [comment]
Will postpone this issue to 4.2, as there seem to be a discussion on if this is an issue by itself.

**Comment by dalexeev** [comment]
I would suggest simply not counting entries with group usage flags as properties. So they can be repeated, unlike regular properties. We already have such entries in native classes. Also, group ending entries use the empty string, which of course will be repeated if you have multiple group endings.



```
{ "name": "RefCounted", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 128 }
{ "name": "Resource", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 128 }
{ "name": "Resource", "class_name": &"", "type": 0, "hint": 0, "hint_string": "resource_", "usage": 64 }
{ "name": "resource_local_to_scene", "class_name": &"", "type": 1, "hint": 0, "hint_string": "", "usage": 6 }
{ "name": "resource_path", "class_name": &"", "type": 4, "hint": 0, "hint_string": "", "usage": 4 }
{ "name": "resource_name", "class_name": &"", "type": 4, "hint": 0, "hint_string": "", "usage": 6 }
```

**Review by adamscott — APPROVED** [review]
Discussed in the GDScript weekly meeting. We agree with @dalexeev, the group names should not count as properties for the check of name collision. So we approve this PR.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by dalexeev** [comment]
This PR is relatively small and fixes many issues. So in my opinion it's worth considering for cherry-pick. I've added the label beforehand, but note that the production team makes the final decisions on cherry-picks.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2. This seems to be isolated and simple enough indeed.

**Pull request merged**
