### PR TITLE
Update COPYRIGHT and allows unbundling libwebsockets and miniupnpc on Linux/BSD

### PR DESCRIPTION
**Pull request by akien-mga**
@Faless @mhilbrunner FYI, what should be done when adding thirdparty libraries.

### CODE REVIEW

**Comment by akien-mga** [comment]
@Faless Ah btw there's libwebsockets 3.0.0 available now. I've tested this PR against this version installed system-wide.

**Comment by Faless** [comment]
> Ah btw there's libwebsockets 3.0.0 available now

yes, I've read it, I'm planning to update both libwebsockets and mbedTLS (2.10 is out) ASAP

**Comment by Faless** [comment]
Note that clients do not detect disconnections with version `3.0` of `libwebsockets` as the callback for client disconnection has changed.

Anyway, I'm testing builds to bundle `3.0` (which will become the new minimal required version)

**Comment by mhilbrunner** [comment]
Noted for the next time :)

**Pull request merged**
