### PR TITLE
Remove static script reference from GDScript class

### LINKED ISSUE #36246: Editor crashes on startup [regression from ObjectID refactor]
**Godot version:** 4.0.dev.custom_build.264f20f8c

**OS/device including version:** macOS 10.15.2

**Issue description:**
The editor crashes on startup. This happens after the object-id refactorization.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff707a07fa libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff7085dbc1 libsystem_pthread.dylib`pthread_kill + 432
    frame #2: 0x00007fff70727a1c libsystem_c.dylib`abort + 120
    frame #3: 0x00007fff7081d647 libsystem_malloc.dylib`malloc_vreport + 548
    frame #4: 0x00007fff7082040e libsystem_malloc.dylib`malloc_report + 151
    frame #5: 0x000000010378f611 godot.osx.tools.64`Memory::free_static(p_ptr=0x000000011836bd20, p_pad_align=false) at memory.cpp:178:3
    frame #6: 0x00000001035bba90 godot.osx.tools.64`void memdelete<Object>(p_class=0x000000011836bd20) at memory.h:119:2
    frame #7: 0x00000001035127d6 godot.osx.tools.64`ClassDB::class_get_default_property_value(p_class=0x00007ffeefbf7660, p_property=0x00007ffeefbf7658, r_valid=0x00007ffeefbf766f) at class_db.cpp:1431:5
    frame #8: 0x0000000101bb991f godot.osx.tools.64`get_documentation_default_value(p_class_name=0x00007ffeefbf7660, p_property_name=0x00007ffeefbf7658, r_default_value_valid=0x00007ffeefbf766f) at doc_data.cpp:214:19
    frame #9: 0x0000000101bb3fa1 godot.osx.tools.64`DocData::generate(this=0x0000000117c53f60, p_basic_types=true) at doc_data.cpp:297:21
    frame #10: 0x00000001017190d1 godot.osx.tools.64`EditorHelp::generate_doc() at editor_help.cpp:1459:7
    frame #11: 0x00000001017b962a godot.osx.tools.64`EditorNode::EditorNode(this=0x000000010a14f210) at editor_node.cpp:5611:2
    frame #12: 0x00000001017d8175 godot.osx.tools.64`EditorNode::EditorNode(this=0x000000010a14f210) at editor_node.cpp:5598:26
    frame #13: 0x000000010004b570 godot.osx.tools.64`Main::start() at main.cpp:1748:18
    frame #14: 0x000000010001e483 godot.osx.tools.64`main(argc=4, argv=0x00007ffeefbff7c0) at godot_main_osx.mm:78:6
    frame #15: 0x00007fff706597fd libdyld.dylib`start + 1
```

Some log before the crash:

```
2020-02-15 22:53:52.080692+0800 godot.osx.tools.64[13284:8850686] ERROR: Method definition provides more arguments than the method actually has 'VisualServer::environment_set_ssao'.
at: bind_methodfi (core/class_db.cpp:1264)
ERROR: Method definition provides more arguments than the method actually has 'VisualServer::environment_set_ssao'.
   at: bind_methodfi (core/class_db.cpp:1264)
2020-02-15 22:53:52.082299+0800 godot.osx.tools.64[13284:8850686] ERROR: Method/Function Failed.
at: bind_integer_constant (core/class_db.cpp:700)
ERROR: Method/Function Failed.
   at: bind_integer_constant (core/class_db.cpp:700)
2020-02-15 22:53:52.082330+0800 godot.osx.tools.64[13284:8850686] ERROR: Method/Function Failed.
at: bind_integer_constant (core/class_db.cpp:700)
ERROR: Method/Function Failed.
   at: bind_integer_constant (core/class_db.cpp:700)
2020-02-15 22:53:52.082346+0800 godot.osx.tools.64[13284:8850686] ERROR: Method/Function Failed.
at: bind_integer_constant (core/class_db.cpp:700)
ERROR: Method/Function Failed.
   at: bind_integer_constant (core/class_db.cpp:700)
compilation success
2020-02-15 22:53:52.124394+0800 godot.osx.tools.64[13284:8850686] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x109481f80> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-02-15 22:53:52.151097+0800 godot.osx.tools.64[13284:8850686]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine
2020-02-15 22:53:52.151548+0800 godot.osx.tools.64[13284:8850686]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine

[mvk-info] Created 3 swapchain images with initial size (2560, 1510).
2020-02-15 22:53:52.352070+0800 godot.osx.tools.64[13284:8850686] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x117bd4ec0> 30010C1C-93BF-11D8-8B5B-000A95AF9C6A
2020-02-15 22:53:52.367573+0800 godot.osx.tools.64[13284:8850686] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x117bd4ec0> 30010C1C-93BF-11D8-8B5B-000A95AF9C6A
Registered camera FaceTime HD Camera with id 1 position 0 at index 0
2020-02-15 22:53:52.653513+0800 godot.osx.tools.64[13284:8850686] ERROR: Condition "p_elem->_root != this" is true.
at: remove (./core/self_list.h:84)
ERROR: Condition "p_elem->_root != this" is true.
   at: remove (./core/self_list.h:84)
2020-02-15 22:53:52.653554+0800 godot.osx.tools.64[13284:8850686] ERROR: Condition "object_slots[slot].object != p_object" is true.
at: remove_instance (core/object.cpp:2084)
ERROR: Condition "object_slots[slot].object != p_object" is true.
   at: remove_instance (core/object.cpp:2084)
2020-02-15 22:53:52.653568+0800 godot.osx.tools.64[13284:8850686] ERROR: Condition "!_p" is true.
at: _unref (core/dictionary.cpp:185)
ERROR: Condition "!_p" is true.
   at: _unref (core/dictionary.cpp:185)
godot.osx.tools.64(13284,0x109107dc0) malloc: *** error for object 0x117eecb60: pointer being freed was not allocated
godot.osx.tools.64(13284,0x109107dc0) malloc: *** set a breakpoint in malloc_error_break to debug
```

The project manager can start successfully, but crashes on exit.

**Steps to reproduce:**
Run godot using `/path/to/godot -e --path /path/to/project`

**Minimal reproduction project:** Any

### LINKED ISSUE #36298: GDScript is broken following ObjectID / Variant refactor (867d073)
**Godot version:**
Master (c92c434299278e035916e4d793f667fa609ac0ba).

**OS/device including version:**
Any

**Issue description:**
Since 867d073b98344b848c96012418912a7e72841a31, GDScript appears to be broken, which triggered a crash on startup (worked around by #36295, which should be reverted once a proper fix is written) and other crash scenarios when running projects.

Some logs from a discussion with @reduz on IRC:
```
[11:36:36] <reduz> maybe what is going on is that, as the code is now more correct regarding the use of placing reference pointers into variants, some stuff gets freed
[11:37:07] <reduz> so the manual memdelete() would be wrong in this context
[11:38:03] <reduz> so the question is why would this happen though
[11:39:13] <reduz> oh i see what is going on
[11:39:40] <reduz> I have no easy fix for this, probably will have to be checked by vnen once he gets back
[11:42:28] <reduz> Akien: my changes break gdscript basically, because the gdscript interpreter kind of assumes you can put a pointer to reference inside of variant with it being unreferenced
[11:43:03] <reduz> now it will always reference it, which is more correct and safer, but breaks gdscript
[11:43:40] <reduz> this needs a workaround, its probably not too difficult, but I would prefer to discuss it with vnen
```

**Steps to reproduce:**
- Revert #36295 and try running the editor, or run any non-trivial GDScript project

### PR DESCRIPTION
**Pull request by vnen**
With the changes in Variant it now causes a reference cycle. The script reference is now created on the function call, the same way as it's done for the instance reference.

Reverts #36295
Fix #36246
Fix #36298

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by avencherus** [comment]
Not sure where to ask given the history of this one.  Wondering though if one of the original issues https://github.com/godotengine/godot/issues/32383 will remain for 3.2?

There were PRs consider for 3.2 that were closed in favor of 867d073.

**Comment by vnen** [comment]
@avencherus I totally missed this. You should have asked in the issue itself, this PR has nothing to do with that one. But I think a solution was added for 3.2.

**Comment by vnen** [comment]
I came here to mention that I added a fixup: 0f1da724924fc494bfd316c57757e0e1d7b90143, since I forgot to actually set the new variable.

**Pull request merged**
