### PR TITLE
Better Tileset Editor

### PR DESCRIPTION
**Pull request by damarindra**
This is still in progress. Place it here to track issues.
This might be available for 3.1, since feature freeze. But I need a confirmation tho if this rejected to go for 3.0.

Changes :
- [x] Fixes lot of bug I found 🤣 
- [x] Tileset now have editor for collision, occluder, navigation
- [x] Tileset can access Texture Region Editor to edit texture from tileset

Issues :
- [ ] First time selecting tileset.res not draw the collision shapes
- [ ] Assign new Texture to tileset not updating tileset-list (sidepanel)
- [ ] ??

SS :
image
image

### CODE REVIEW

**Comment by blurymind** [comment]
very nice! :D 
It would close https://github.com/godotengine/godot/issues/13225

**Comment by blurymind** [comment]
Will putting all tiles on one atlas reduce the number of draw calls? This will make that possible and also reduce the number of steps required for setting up tiles and autotiles dramatically

**Comment by MarianoGnu** [comment]
> Will putting all tiles on one atlas reduce the number of draw calls?

Yes, it already works that way, as long as tiles drawn use the same textures and material it will be done in a single drawcall

**Comment by blurymind** [comment]
It would be quite nice if we could directly load an image file into the tileset editor instead of having to prepare a tres/res file

**Comment by MarianoGnu** [comment]
caml down men, this is a work in progress, it's still not posible on the video i saw, but it's planed afaik

**Comment by blurymind** [comment]
@MarianoGnu though of suggesting it to @damarindra here as something that would definitely improve the tileset editor. Have you started working on it?

@damarindra thank you for all of these fantastic updates to the editor! It is definitely a huge workflow improvement!!

**Comment by akien-mga** [comment]
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by MarianoGnu** [comment]
i think this feature is merged because there was a duplicated PR?

**Comment by akien-mga** [comment]
I don't know, the other PR with similar name had a much smaller scope: #15185

**Comment by damarindra** [comment]
#15185 only fix bugs which are I produced.

**Comment by blurymind** [comment]
My impression is that this PR adds to the autotile editor the ability to also author non-autotiles. This turns it into a powerful editor for tilesets that can set collision, occlusion and navigation shapes on the entire tileset- not just autotiles.

Another feature that it seems to add is the ability to author atlases that contain more than one autotile

@MarianoGnu have these features been merged in another pr?

**Comment by damarindra** [comment]
I will work on this again after Godot 3 released.

**Comment by MarianoGnu** [comment]
@blurymind nope, it was my mistake, these features are not on the other PR

**Comment by blurymind** [comment]
@akien-mga can we please get this merged in the 3.0 branch? @MarianoGnu  noted in
https://github.com/godotengine/godot/issues/15577#issuecomment-356907967
That this is an editor usability enhancement rather than a new API feature

**Comment by akien-mga** [comment]
Nope, it's too late for 3.0.

**Comment by akien-mga** [comment]
This can be reviewed again now that 3.0 is released.

It needs a rebase to solve merge conflicts though (be sure to use `git pull --rebase upstream master` to also get rid of the merge commits, see [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html)).

**Comment by damarindra** [comment]
I create another branch with more feature, but still not complete yet. I'm quite busy lately, please tell me if next release will come up soon, so I can cancel or speed up the new feature.

**Comment by blurymind** [comment]
@damarindra I think that all new commits are now going into 3.1 branch, which will probably not going  to be stable soon. You should be ok to add new features as @akien-mga noted, before we go into another freeze

**Comment by damarindra** [comment]
The problem is I haven't finished yet. That will be weird merging unfinished job.

**Comment by akien-mga** [comment]
Take your time, there's no hurry.

**Comment by damarindra** [comment]
Moved  #16772

**Pull request closed without merging**
