### PR TITLE
Fix `browse_dialog` in Blender scene importer to accept files

### LINKED ISSUE #93235: Blend import dialog window ask for folder, not file.
### Tested versions

- Reproduced in Godot 4.3 beta 1
- Reproduced in Godot 4.3 71699e08c9df78b7203fa4ef9cede28e995d6ace

### System information

Windows 11

### Issue description

The dialog window that comes up when a blend path is not specified but a blend file is being imported (`EditorFileSystemImportFormatSupportQueryBlend`), asks you to select a folder while it seems to only work if the full path to the `blender.exe` is specified.

Looking at the code there seems to be a difference in logic between Windows, Mac and Linux here (see `EditorFileSystemImportFormatSupportQueryBlend::_autodetect_path`) but I'm not familiar enough with the code to suggest a fix that doesn't break the other platforms.

### Steps to reproduce

Create a new project
Add a blend file to the project
Try and select blender in the dialog window.

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by raging-loon**
Changes EditorFileSystemImportFormatSupportQueryBlend::browse_dialog to accept file names. As it is now, it only accepts directory names. This will present an error as the callback "_select_install" and subsequent calls to "_validate_path" and "_get_blender_version" are all expecting filenames.

Closes #93235

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

However, the UI still refers to a Blender *installation*, which can be a bit ambiguous. I suggest renaming it to Blender *executable* instead.

image

On macOS, it might be worth hinting that you should point at `Contents/MacOS/blender` within `Blender.app` too (e.g. by appending to the label with `#ifdef MACOS_ENABLED`).

**Comment by raging-loon** [comment]
I could change "installation" to "executable". However, for Mac support, it would be better for someone else handle that, as I have never touched a Mac let along program one.

**Comment by akien-mga** [comment]
I pushed an update myself that adjusts the label and error messages for clarity.

**Comment by akien-mga** [comment]
For the record, I noticed #94914 while working on this, but it doesn't seem related to these changes, the bug also happens in RC 1.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
