### PR TITLE
Optimize many SVGs

### PR DESCRIPTION
**Pull request by MewPurPur**
Sorry for flooding y'all with these while you're trying to focus on more important things for 4.1-- Should be the last one.

Saves ~13 kB. This PR is more tame than the others. The optimizations consist of removing the rest of the unnecessary transforms, fixing quirks of some SVGs, merging arcs, etc.

I mostly wanted to sort out a grievance I had with us having super complex paths for our "rainbowy" icons such as StyleBoxFlat. Instead of one consistent shape, we needed to split it into little pieces for each color.

image

I solved this by hacking a constant gradient into SVG by duplicating each color stop (I checked and it's rendered properly). This helps reduce size a little for most of the icons, although a few SVGs did become bigger. But mostly the benefit is that the gradient can neatly be copied anytime we need the rainbow pattern in the future.

### CODE REVIEW

**Comment by MewPurPur** [comment]
Oh, here's a little thing I should ask, I reused the same gradient everywhere, although some of the rainbow's colors aren't used everywhere. For example, PhysicalSkyMaterial uses 5 of the colors, and LabelSettings only uses 4 (at the bottom). I just wanted to be consistent with it, but maybe size is more important to us still?

**Comment by YuriSizov** [comment]
> LabelSettings only uses 4 (at the bottom)

I think it's a question of readability rather than size. In the updated version you have one color that takes more space than others, for example. So it doesn't read as a rainbow gradient as clearly.

Also, the titles talks about one specific change, but over the half of the icons here are not using a rainbow gradient, or any gradient or color at all. Are these changes intended to be in the same PR?

**Comment by MewPurPur** [comment]
No, it was another generic SVG optimization PR, in hindsight yeah I should say that in the title instead of highlighting what I did with rainbow gradients.

Whaddya mean about colors? We always had them like red (0-3), yellow (3-5), green (5-7), turqoise (7-9), blue (9-11), purple (11-13), pink (13-16). Hence red and pink always took more space, and I haven't changed anything. It's just that while icons are 16x16, the icons are usually within the 14x14 square with rare exceptions.

**Comment by YuriSizov** [comment]
> in hindsight yeah I should say that in the title instead of highlighting what I did with rainbow gradients. I'll amend the commit too

Such details you can put on the second line of the commit message, actually. Not important, but can help to keep the specific changes that you've made in the commit history forever (instead of relying just on GitHub).

**Review by YuriSizov — APPROVED** [review]
Haven't really checked in depth, but I believe in you :)

**Review by Calinou — APPROVED** [review]
On Linux stripped editor binaries, this reduces binary size by 11.5 KB compared to 593d5ca29f32d07a8bf9f3bae5b33e67d0f4218f (tested when rebased against that commit).

I've looked at gradient icons in the editor and they render correctly:

image|image
-|-

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
