### PR TITLE
[3.x] Store `ObjectID` instead of `Object *` for Shape Owners

### PR DESCRIPTION
**Pull request by timothyqiu**
`3.x` version of #57182

### CODE REVIEW

**Comment by lawnjelly** [comment]
Codewise it looks ok to me, so there is mainly just any performance implications to look at, I saw the ObjectDB is using a hashmap and don't know how fast it is. I guess it would be good to check nothing here is getting hit in a hot loop, as there might be an alternate strategy if that were the case.

`shape_owner_get_transform()` doesn't seem to be used outside the editor from core (but is bound).
`shape_owner_get_owner()` is used from

`KinematicCollision2D::get_local_shape`
`KinematicCollision2D::get_collider_shape`

`KinematicCollision::get_local_shape`
`KinematicCollision::get_collider_shape`

I'm not absolutely sure on this, it looks like they are just bound so probably ok.

I'm also having no idea how fast Hashmap is, if it is O log (1) then then should be fine. I'm kind of not sure why it is a Hashmap rather than a Handle Pool, maybe the IDs of Godot objects increasing is required for some reason.

**Comment by timothyqiu** [comment]
> I'm also having no idea how fast Hashmap is, if it is O (1) then then should be fine.

`Hashmap` is O(1) if there is no hash collision. When there is, it'll go through a linear search among entries that have the same hash value.

**Review by lawnjelly — APPROVED** [review]
As far as I can see is ok. I can't see any evidence of it being performance sensitive.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
