### PR TITLE
Added PROPERTY_HINT_ENUM_AUTOSORT to sort enum values in the inspector

### PR DESCRIPTION
**Pull request by Chaosus**
This hint allows a better representation of enums - while keeping their index same, they sorted in alphabetical order in the inspector and property editor.

So, we can now add some beauty to their composition like:
image

I've added this also to GDScript (for named enums):

```
enum State{
	WALK,
	ZZZ,
	AWAKE
}

export(State, true) var state
```
will be presented like

image

### CODE REVIEW

**Comment by Calinou** [comment]
Nice work!

Could it be possible to use a named value in the export hint like for filesystem hints?

```gdscript
# This:
export(State, AUTOSORT) var state

# Instead of:
export(State, true) var state
```

**Comment by Chaosus** [comment]
Yeah, good idea thank you!

**Comment by Chaosus** [comment]
@vnen @akien-mga Seems ok for you guys?

**Comment by Chaosus** [comment]
I currently lost interest in this PR, maybe later, closed for now since it requires complex rebase

**Pull request closed without merging**
