### PR TITLE
Fix for Issue #23465

### PR DESCRIPTION
**Pull request by Arunkumar1998BOM**
I have resolved the issue by Introducing a separate signal named "Allow Only Rmb Sel". By enabling this, only the rmb signal works and thus can be used in a dedicated manner to execute a different action.
The functionality of the existing "Allow Rmb Sel" signal (to allow both rmb and lmb) is left untouched.
Corner case: If the user enabled both the options (Allow Rmb Sel and Allow Only Rmb Sel), he will be able to use both the rmb and lmb.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Sorry for late reply but

> I think I have oberved the issue Zylann is talking about. Ill explain:
When I do not select "Allow Rmb Sel" in the inspector for the ItemList, I find that I can select the items in my list only with lmb.
****Now, when I enable Rmb Sel, I can select with both rmb and lmb.
The type of functionality what Zylann is requiring that, when he enables Rmb Sel, He must be able to select only with the rmb and lmb must lie dead for him.

this is wrong. The issue is about being able to differentiate between LMB selection and RMB selection. I'd solve this by just adding a signal `item_lmb_selected`. The property you introduced doesn't have any practical use >_>

**Comment by Arunkumar1998BOM** [comment]
> Sorry for late reply but
> 
> > I think I have oberved the issue Zylann is talking about. Ill explain:
> > When I do not select "Allow Rmb Sel" in the inspector for the ItemList, I find that I can select the items in my list only with lmb.
> > ****Now, when I enable Rmb Sel, I can select with both rmb and lmb.
> > The type of functionality what Zylann is requiring that, when he enables Rmb Sel, He must be able to select only with the rmb and lmb must lie dead for him.
> 
> this is wrong. The issue is about being able to differentiate between LMB selection and RMB selection. I'd solve this by just adding a signal `item_lmb_selected`. The property you introduced doesn't have any practical use >_>

Okay, I got it, I will do this then. 
I will create a new signal item_lmb_selected -->This will allow him to use only left mouse button for his selections
I will modify the existing signal item_rmb_signal --> In a way as it will allow only right mouse button for his selections.
If he enables both the options in the inspector menu, he will be able to use both the mouse buttons for the selections he makes in the ItemList.
@KoBeWi 
I guess, this is the best way you can differentiate the two signals.

**Comment by Arunkumar1998BOM** [comment]
ItemList
So this is what the ItemList inspector would look like, If the user selects only "Allow Rmb Select" , the Rmb will be the only way of registering the signals, and similarly if user selects only "Allow Lmb Select", the Lmb will be the only way of registering the signals, and if the user selects both, then both the signals can be used.

**Comment by aaronfranke** [comment]
@Arunkumar1998BOM Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by aaronfranke** [comment]
Closing as abandoned by the author. If this is still desired, feel free to open a new PR based on the latest master branch.

**Pull request closed without merging**
