### PR TITLE
Use black for font outlines by default instead of white

### PR DESCRIPTION
**Pull request by Calinou**
This makes font outlines more usable out of the box, as black is one of the most commonly used colors for font outlines.

Now, to configure a working font outline, you just have to increase **Outline Size** in a supported Control node's custom constants:

image

### CODE REVIEW

**Review by AaronRecord — APPROVED** [review]

**Comment by KoBeWi** [comment]
White outlines are actually useful when combined with outline modulate. Question is whether black is more common that all other colors 🤔

**Comment by Calinou** [comment]
> White outlines are actually useful when combined with outline modulate. Question is whether black is more common that all other colors thinking

Should we make outline modulate black by default instead?

**Comment by YuriSizov** [comment]
> Should we make outline modulate black by default instead (and keep the outline glyphs white)?

Let's do that!

**Comment by YuriSizov** [comment]
I think this is something we can change in 4.x now.

**Comment by Mickeon** [comment]
A whole year has passed and it seems like this was _extremely_ desirable back when. How do we feel about this now?

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected.

> Should we make outline modulate black by default instead (and keep the outline glyphs white)?

I don't remember what this was about though. `outline_modulate` is only referenced in Window and Label3D (the latter is already solid black by default).

**Comment by KoBeWi** [comment]
`outline_modulate` was a theme color. It was used to modulate the outline color defined in Font (which this PR modified originally I think?), but the Font outline is now gone.

**Comment by akien-mga** [comment]
There are some style issues, clang-format didn't run.

**Review by akien-mga — APPROVED** [review]
Seems fine to me after fixing style issues.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
