### PR TITLE
Fix management of life cycle of volumetric fog related uniform sets

### LINKED ISSUE #77515: Changing between scenes that use volumetric fog causes unending error spam
### Godot version

v4.1.dev.custom_build [a67d37f7c]

### System information

Windows 10, Vulkan

### Issue description

When changing between scenes that have volumetric fog enabled in the world environment, for example with `change_scene_to_file`, after changing there will be a continuous stream of errors that doesn't seem to stop.
Leaving a copy of one of the errors here so it's findable when searching the issue: 
"RenderingDeviceVulkan::compute_list_bind_uniform_set: Condition "!uniform_set" is true.
  <C++ Source>   drivers\vulkan\rendering_device_vulkan.cpp:7816 @ RenderingDeviceVulkan::compute_list_bind_uniform_set()"

The MRP is the volumetric fog demo, with its main scene duplicated, and the left/right arrow keys being used to change between scenes.

Disabling vol fog in either scene makes the errors go away.

image

### Steps to reproduce

Use left/right arrow keys to change scene and back, then error spam should begin.

### Minimal reproduction project

[new hot volumetric_fog bug.zip](https://github.com/godotengine/godot/files/11575612/new.hot.volumetric_fog.bug.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #77515.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Just to elaborate, I assumed that the copy unform set's life cycle was bound to that of the three GI ones. It was wrong. I should have TIWAGOS.

**Comment by cridenour** [comment]
Can confirm this fixes the MRP from #77680 and my original project issue that caused me to investigate. 

Thanks for the quick fix!

**Review by clayjohn — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
