### PR TITLE
Fixes the month consistency issue in enums (OS::Month) and get_date etc

### PR DESCRIPTION
**Pull request by Razzlegames**
- Also updated the docs to reflect this.
- Added some vim temp files to gitignore

Ticket:
https://github.com/godotengine/godot/issues/4025

### CODE REVIEW

**Comment by blurymind** [comment]
Awesome work! Thank you for making it consistent! :)

**Comment by akien-mga** [comment]
Will that work as expected on all OS implementations?

**Comment by akien-mga** [comment]
If I understand the issue correctly, ``OS.get_date()`` was already starting to number months at 1, while the OS enum started at 0?

If so I agree with the change, but we need to make sure we won't break existing engine code that relies on the ``OS::Month``, and if we break games relying on ``OS::Month``, it has to be made clear in the release notes.

**Comment by akien-mga** [comment]
Things to check:
- https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L1648 (according to the MSDN doc you linked, it seems that it will work fine after your PR and was broken previously?)
- https://github.com/godotengine/godot/blob/master/platform/winrt/os_winrt.cpp#L464
- https://github.com/godotengine/godot/blob/master/platform/nacl/os_nacl.cpp#L252

**Comment by Razzlegames** [comment]
Yes that's correct.  The implementations I saw of get_date were indexing starting at Jan == 1. 

 For the platforms mentioned, I don't have any way check these since I don't have these systems.  If Travis has a built in Unit test framework (for auto running) this could be an option. 

I was actually surprised that there were no unit tests I could find in Godot.  This would be a great verification step for pull requests.

**Comment by Razzlegames** [comment]
All implementations found:

OS_Unix::get_date => verified...
OSNacl::get_date => indirectly verified (see code notes). This follows unix standard and needed to be +1 for month, to match Julian calendar style 1-12.
OS_Windows::get_date => Indirectly verified. SYSTEMTIME already follows 1-12 month format
OSWinrt::get_date => indirectly verified. SYSTEMTIME already follows 1-12 month format

**Comment by akien-mga** [comment]
Thanks, looks good :)
I'll merge once the travis CI checks are done.

**Pull request merged**
