### PR TITLE
Reduce gdscript VM instruction set and simplify VM code

### PR DESCRIPTION
**Pull request by SlashScreen**
The VM has, in my opinion, far far too many opcodes, and the code is, frankly, a bit messy and hard to understand to someone unfamiliar trying to work on it (no offense). In the pursuit of easier maintenance and improvement, I have sought to refactor much of the VM code to be easier to read and understand. I am not seeking to change the functionality of the VM in this PR.

I am doing the following:
- Reduce instruction set to 30 opcodes.
- Pull out blocks from their branches of the 3000-line behemoth VM run loop into their own smaller chunks.
- Structure the new functions in a way that they can be pretty easily refactored once other improvements are in place, I.E. unified type representation.
- Improving code clarity by reducing the use of unnecessary macros (such as `DISPATCH_OPCODE` instead of simply `continue`.) This is perhaps controversial and not the C++ way to do things, but I believe macros should be used to reduce repetitive work rather than make a DSL that someone has to learn in order to understand what's going on.
- Slight optimization where the different opcode executions are instead function pointers in an array, instead of a switch statement (preventing lots of branching).
- Documenting the code.

Opcode reduction strategy and rationale:
I noticed most of the opcodes were the same action in a different context. So I simplified by only having the one opcode for the action, and adding an argument to some of the opcodes that further defines which specific context it takes. The argument also carries a flag notifying whether the opcode is "validated" or not.
This may seem like kicking the can down the road, but this is in aim to make it easy to remove this behavior or modify it easily if things change in the future.
The current argument is a single byte formatted as follows:
```
0 | 000_0000
Is Validated? | Sub behavior
``` 
The sub behavior codes are stored in enums in `gdscript_function.h`. Currently the byte is stored as a full int, since each bytecode chunk appears to be an integer. 

This is a work in progress, as cleaning the code is tedious. If there's any changes you would like along the way, let me know. And yes, I'll squash the commits before the PR is actually done.

### CODE REVIEW

**Comment by YYF233333** [comment]
Note that `DISPATCH_CODE` series of macros is used to switch between two implementations, on compilers support computed goto (namely gcc and clang), a version utilizing `goto` is used and thus need to be in one function. You may want to keep the old code for compitability or delete them completely.

**Comment by SlashScreen** [comment]
> on compilers support
Is this a typo?
> You may want to keep the old code for compitability or delete them completely.
What code is affected by this goto discrepancy?

**Comment by YYF233333** [comment]
> What code is affected by this goto discrepancy?

`GDScriptFunction::call`, see this part: https://github.com/godotengine/godot/blob/99a8ab795d65e816ea7c452aa0fb55d02385c048/modules/gdscript/gdscript_vm.cpp#L230C1-L429C50

Sorry for my poor English, feel free to correct me 😄

**Comment by SlashScreen** [comment]
Ah, right, I was going to figure out what that was for at some point. Should I get rid of it if I'm not using the switch opcode execute loop?

**Comment by YYF233333** [comment]
If you have a completely different approach, just remove them all I think.

**Comment by dalexeev** [comment]
I haven't reviewed this PR in detail and I'm not an expert in VMs, but I doubt this is a good change.

1. We can't ignore performance considerations. VM is often a hot code path, we can't just say "let's sacrifice some performance for readability, elegance and other formal metrics like function size". As long as the code remains maintainable for us, we are willing to make any optimizations and "ignore" code style that would be unacceptable for normal code, since VM is a special case.
2. I don't agree that splitting into multiple functions improves readability and maintainability for VMs. Each opcode is already isolated from the others, so we don't face typical FSM problems, a giant `switch` is not a problem.
3. I don't think that reducing the number of opcodes is necessarily a good thing. For example, CPython has over 200 opcodes. Instead of a large number of opcodes, you get a lot of branching at runtime. While a larger number of opcodes allows you to avoid this and move some of the evaluations to the compilation stage. Yes, in return this leads to an increase in the code size, which can cause cache misses. But this requires careful measurements and balancing between the two extremes, there is no absolute good and absolute evil here.
4. In my opinion, this change is also debatable from the point of view of readability. Instead of a large function with a simple structure, you get many smaller functions and enumerations. Also, the essence of the opcode becomes more complex, instead of a simple identifier, it now has arguments (in addition to the bytecode arguments).
5. Macro magic is needed to use _computed goto_, which is not supported by all compilers.

As far as I know, the current VM organization corresponds to the generally accepted practices of organizing interpreters. Please read [The Design & Implementation of the CPython Virtual Machine](https://substack.com/@abhinavupadhyay/p-143567425), and you will find many similarities with the GDScript VM. The main difference is that CPython's source code is generated by scripts, while ours is written by hand, using a few macros.

**Comment by SlashScreen** [comment]
> We can't ignore performance considerations. 

I'm not. This was spawned from a [discussion in proposals](https://github.com/godotengine/godot-proposals/issues/6031) about improving performance, and we determined the VM needs to be heavily modified, as well as optimizations in other parts of the compilation process. This is merely step 1 of that process to make it easier to work on. I personally want to rewrite the whole thing into a register machine to follow Lua, but we don't know if that's necessary yet, since it would take a lot of effort on my part.

> I don't agree that splitting into multiple functions improves readability and maintainability for VMs.

We'll see. I found working within the main loop as it stands to be a mess that made me anxious, and I can't be the only one. 

>  For example, CPython has over 200 opcodes.

This assumes CPython is something we want to emulate. I don't think it's something to try to replicate, since we are trying to focus on performance.

> Instead of a large number of opcodes, you get a lot of branching at runtime.

I sort of agree here, but this is ignoring that my primary idea for the main loop would to index into an array of function pointers, rather than use a switch statement and then another switch statement inside the opcode functions. Hopefully in the future with a unified type system, a lot of the branching can be eliminated, since we would hopefully not need to switch on every primitive type.

> Instead of a large function with a simple structure,

Again, the 3000-line behemoth is, in my view, much less approachable or easily navigable than a lot of smaller functions.

>  Also, the essence of the opcode becomes more complex,

I do agree here mostly, although I view it as another bytecode argument than added to the opcode. Not all of the opcodes have these arguments.

> Macro magic is needed to use computed goto

I don't want to use computed goto.

**Comment by fire** [comment]
Is there a good reason to do this refactoring that's visible to the user developers using Godot Engine?

I only saw mention of a slight optimization. I would appreciate it if you could explain what benefits we would have.

**Comment by SlashScreen** [comment]
The goal was not to be significantly visible to the end user, but rather to make it easier to change in the future as part of a several step process for improving GDScript performance by simplifying how it works internally, performing some basic code optimizations, and rethinking how types are represented internally to allow for more flexibility in the language, which would come in a series of PRs like other large changes. Admittedly, perhaps this should have been a step further in the process, rather than the first.

**Comment by YYF233333** [comment]
> 5\. Macro magic is needed to use _computed goto_, which is not supported by all compilers

I recently open a proposal: https://github.com/godotengine/godot-proposals/issues/11418 discussing computed goto. I'd love to hear your opinion on this.

And @SlashScreen I recommand you open a proposal describing what you want to modify and link back to this PR. The diff is too big, it is much likely that this PR would not be accepted as it is. In best case you may be asked to split it into smaller parts. We need a stable place for these design discussions.

**Comment by SlashScreen** [comment]
Alright, I'll do that tomorrow.

**Comment by SlashScreen** [comment]
I have to rethink this.

**Pull request closed without merging**
