### PR TITLE
Rename plane shape to world margin shape in 3D physics server

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Same as already done for 2D and for the 3D shape resource, for consistency.
Also made the changes in Bullet server even though it's disabled for now.

Following up from https://github.com/godotengine/godot/pull/51636#issue-712533967 (CC @Calinou)

### CODE REVIEW

**Comment by reduz** [comment]
I understand why Plane shape is troublesome, but I am not sure if WorldMargin is the best possible name. How about WorldBoundaryShape ? I think Boundary has less room for misinterpretation than Margin.

**Comment by pouleyKetchoupp** [comment]
> How about WorldBoundaryShape ? I think Boundary has less room for misinterpretation than Margin.

Makes sense! Margin is already used in other places and it might add some confusion, so `WorldBoundaryShape` sounds good to me.
Let's just wait to see if @AndreaCatania or @Calinou have comments and I'll change the name in both 2D and 3D.

**Comment by Calinou** [comment]
WorldBoundaryShape sounds good to me. 👍

**Comment by pouleyKetchoupp** [comment]
Closing in favor of #52679.

**Pull request closed without merging**
