### PR TITLE
Improve compilation time with include-what-you-use (`core` folder)

### PR DESCRIPTION
**Pull request by Geometror**
Part of a series of PRs to reduce the compilation time with [include-what-you-use](https://include-what-you-use.org/) together with some manual fixes due to the complexity of the codebase. [see #57734, #57759]

This PR restructures the includes in the `core` subfolder, so it should probably be merged before the other PRs.

Could help with https://github.com/godotengine/godot/issues/53295.

### CODE REVIEW

**Comment by Geometror** [comment]
[copied from RocketChat for reference]
Did a bit of a read up, and I think I now have a better understanding of what iwyu does. Now I see that it does it quite well. Although it adds a bunch of includes and removes just a few, it has several benefits:
1. **design**: better vision/overview of the exact dependencies between files, valuable for refactoring
2. **self-containment**: even if there are redundant includes, they are basically free because of header guards (and modern compilers) and they can be a good thing since they help to achieve self-containment of headers, making the whole codebase more robust
3. **performance**: as already said, iwyu does indeed remove some unneeded includes, but only those which can be replaced by a subset of direct includes 

For example, if a file xyz.h includes node.h and node.h includes all headers xyz.h would need, but xyz.h also requires some definitions only present in node.h, iwyu will still add all the direct includes to xyz.h and keep the #include "node.h' - in this case there wouldn't be any improvement in build performance, but the benefit of point 1. and 2. still remains: If some includes (which xyz.h originally depended on) are removed from node.h, xyz.h would still compile fine since its self-contained.

Some flaws of iwyu I noticed (all related to templates), which required manual cleanup: Iwyu sometimes thinks a forward declaration is sufficient when it is not, which happens when a type is used as a parameter for a macro using template code. Also specializations of templates distributed across multiple files can cause problems because iwyu does not include all files.

**Comment by dmoody256** [comment]
Hello recently I did a include what you use tool for scons for mongodb skunkworks. It features a full build analysis mode and a changeset analysis mode: https://github.com/dmoody256/mongo/blob/skunkworks_iwyu/site_scons/site_tools/iwyu.py

I wrote it over the course of a week specifically to work with the mongodb build, so it's definitely alpha level code, but feel free to take ideas from it!

**Comment by vittorioromeo** [comment]
@YuriSizov 

> All in all, manual work and refactoring seem to be more beneficial and practical. Human developers can identify the underlying issue and rework the code in a meaningful way, adjust includes with a sensibility of a human reader.

I disagree with not merging this PR, as it would have been a better starting point for refactoring compared to what is already there, but I strongly agree with this sentence I quoted.

If you truly believe that, please then let contributors get started on this sort of refactoring with minimal friction. See https://github.com/godotengine/godot-proposals/discussions/9016 and https://github.com/godotengine/godot/pull/87893. 

If I have to spend time arguing about best practices and proving that small refactoring changes do indeed help the codebase compile a bit faster for every single PR I submit, then my motivation to improve the status quo is completely destroyed. 

I understand having a high level of scrutiny for larger PRs or for PRs that change the behavior of Godot, but refactoring PRs should feel like a breeze relatively to functionality PRs, otherwise nothing concrete would be achieved in the context of improving the header hygiene and structure of the codebase.

**Comment by adamscott** [comment]
> @YuriSizov

Unfortunately, [Yuri announced recently](https://twitter.com/YuriSizov/status/1752746144810041625) that he wouldn't contribute anymore to the engine.

**Pull request closed without merging**
