### PR TITLE
Fix a lint issue where the template argument is missing

### PR DESCRIPTION
**Pull request by hbina**
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>

### CODE REVIEW

**Comment by akien-mga** [comment]
What is that lint issue?

**Comment by hbina** [comment]
Something like "missing template parameter list for MutexLock". It shows up as a lint in vscode but it doesn't appear as a compile warning, maybe its a specific sanitizer.

**Comment by nathanfranke** [comment]
With these changes locally, I am still getting an error in VSCode:

> argument list for class template "MutexLock" is missing
```cpp
MutexLock lock(mutex);
```

Do you happen to know how this code works? All of the implementations of MutexLock I see have a template parameter, so I am surprised this even compiles.

**Comment by YuriSizov** [comment]
Since it's unclear why this change is needed and there are issues with it, I'm going to close it. But thanks for your contribution nonetheless.

**Pull request closed without merging**
