### PR TITLE
Add support for custom resource icons in the FileSystem window

### PR DESCRIPTION
**Pull request by Atlinx**
Fixes issue #32706.

Before:
before

After:
after

### CODE REVIEW

**Comment by pycbouh** [comment]
It’s very excessive to load every singe resource just to get the icon. I don’t think this is a good idea.

**Comment by Atlinx** [comment]
> It’s very excessive to load every single resource just to get the icon. I don’t think this is a good idea. We must look elsewhere for the solution.

Is there any other way to get the script that is attached to a resource? I feel like the only solution right now would be to load all the resources once on startup and cache their icon paths, which also doesn't sound too appealing.

**Comment by pycbouh** [comment]
I don't think we have anything ready for that purpose. I can imagine saving this information with the resource itself can be an option. Or treat it the same way we treat previews, where they are generated on demand and stored in editor cache.

**Comment by Atlinx** [comment]
> I don't think we have anything ready for that purpose. I can imagine saving this information with the resource itself can be an option.

The script actually is saved within the resource but I don't know how to selectively load just the script.

> Or treat it the same way we treat previews, where they are generated on demand and stored in editor cache.

For generating on-demand do you mean whenever the FileSystem dock is open?

**Comment by pycbouh** [comment]
> The script actually is saved within the resource but I don't know how to selectively load just the script.

Well, no, it's only referenced in the `.tres` file under normal circumstances. But I didn't even mean the script, I meant we could save the icon itself. Though I like the preview option more now anyway.

> For generating on-demand do you mean whenever the FileSystem dock is open?

Well, whenever we generate a preview we can also "generate" an icon for each individual saved resource. Previews are also generated for the benefit of the FileSystem dock (you can see them if you switch to the tiled mode from the list mode), so it seems fitting. So we could piggyback on the EditorResourcePreviewGenerator and cache icons for individual resources that way.

**Comment by Atlinx** [comment]
> Well, whenever we generate a preview we can also "generate" an icon for each individual saved resource. Previews are also generated for the benefit of the FileSystem dock (you can see them if you switch to the tiled mode from the list mode), so it seems fitting. So we could piggyback on the EditorResourcePreviewGenerator and cache icons for individual resources that way.

I'm currently combining icon fetching with resource previewing by adding an extra `custom_type_icon` parameter for the `EditorResourcePreview.queue_edited_resource_preview()` and I'm not sure if this is the correct way to go about implementing this since it seems like this would cause compatibility issues. Is it okay to add another parameter to this method?

**Comment by pycbouh** [comment]
> Is it okay to add another parameter to this method?

Generally, yes, it should be okay, and compatibility breakage is okay for 4.0 too.

Though looking at the code it does seem to start getting verbose, but I've not dug deep into preview generation to offer a better approach immediately. If we make it a separate action, it would still need to be called for every resource type alongside the preview method, which is more maintenance and a chance to forget to call it. Maybe we could cache the icon without exposing it to the outwards facing API?

**Comment by Atlinx** [comment]
Actually, I'm not sure if caching is the best way to go about doing this. To account for the case of the user changing their icon, we would have to check if the cache is valid by loading the resource to load the script that it is attached to, which defeats the purpose of caching in the first place.

**Comment by pycbouh** [comment]
That still doesn't account for users changing the icon and invalidating this information as a result.

**Comment by Atlinx** [comment]
Yeah it doesn't account for invalidation while the project is open but it would be inline with the current implementation of custom icons, which seem to only update on project restart (Though I don't know if this is intentional behaviour or not)

**Comment by Atlinx** [comment]
I'll be closing this now as there currently isn't a performant way to load icons. Development has also been moved to a [dedicated branch on my repo](https://github.com/Atlinx/godot/tree/feat/32706_custom_resource_icons).

I'll probably experiment with a "load all icons once at startup" strategy later sometime. If it works out I might reopen another PR from that branch.

**Comment by nhold** [comment]
I honestly think this implementation is 95% of the way there. The only offending codes loads a resource fully to get the type, but we could actually add a `fast_get_resource_icon` that will custom inspect the text file:

1. Check the first tag is [gd_resource...] as that means we are a resource. (early out here)
3. Grab the representing script,
e.g.
```
[gd_resource type="Resource" load_steps=4 format=2]
[ext_resource path="res://Systems/Crafting/CraftingResource.gd" type="Script" id=1]
```

5. Make use of the `filesystem_cache` to determine the icon, this is what, I believe, the Create New Resource dialogue uses.

```
CraftingResource.gd::GDScript::1651158176::0::1::::CraftingResource<>Resource<>res://icon.png::
```

**Comment by Atlinx** [comment]
Just to confirm, we don't need to cache anything ourselves then right? I think file reading shouldn't be too performance heavy, especially since we'll be reading only the first two lines.

**Pull request closed without merging**
