### PR TITLE
disable socket_posix for platforms that don't support it [3.1]

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
this change is on 3.2 branch

### CODE REVIEW

**Comment by Calinou** [comment]
Did you mean to open a pull request on the main Godot repository?

**Comment by jeronimo-schreyer** [comment]
yeah exactly. I meant to backport a feature from 3.2

**Comment by akien-mga** [comment]
This PR needs to be rebased:
- All the merge commits from merging PRs in your fork are not relevant to this repo's Git history (and even confusing)
- If you're backporting a change made in a later branch, you should link to it for traceability. In this case it's fe068b61ad4355372e454dc5bbaec0c42d58d67b, so you should use `git cherry-pick -x fe068b61ad4355372e454dc5bbaec0c42d58d67b` instead of redoing the commit manually.

**Comment by jeronimo-schreyer** [comment]
the file in that commit (which is in branch 3.2) is not quite actually the same as the one in branch 3.1

**Comment by akien-mga** [comment]
Superseded by f18a8d3ffc.

**Pull request closed without merging**
