### PR TITLE
Add support for atlas texture on set_custom_mouse_cursor

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
https://github.com/godotengine/godot/issues/16813#issuecomment-383089262

- [x] x11
- [x] windows
- [x] mac

### CODE REVIEW

**Comment by guilhermefelipecgs** [comment]
CC @avencherus

**Comment by avencherus** [comment]
@guilhermefelipecgs Checked it out.  Not sure if I recompiled the os_windows.cpp correctly or not, very new to the build process.  X)

But I got some odd results.  Using the `get_atlas()` gives the size error as before, but just using the .atex resource gives me a big black box the size of the atlas.

godot windows tools 64_2018-04-23_01-50-39

Here is a sample project, hopefully you can reproduce it:  
[Atlas Bug.zip](https://github.com/godotengine/godot/files/1936200/Atlas.Bug.zip)

**Comment by guilhermefelipecgs** [comment]
Thanks, I'll check asap.

**Comment by guilhermefelipecgs** [comment]
@avencherus Fixed, I think now it's all done. You don't need to call `get_atlas` anymore (and if you do, the error is expected). Can you test again?

**Comment by avencherus** [comment]
@guilhermefelipecgs Looking good on this end.  Thanks again for taking the time to fix it up.

**Pull request merged**
