### PR TITLE
Tabs enhancements: get_tab_rect(), move_tab()

### PR DESCRIPTION
**Pull request by kubecz3k**
exposed: `get_tab_rect(tab_idx)` can be used to determine position and size of concrete tab 
new and exposed: `move_tab_from_to(idx_from, idx_to)` can be used to rearrange tabs more easily

### CODE REVIEW

**Comment by akien-mga** [comment]
`move_tab(int from, int to)` would be a better method name no?

**Comment by kubecz3k** [comment]
yes, I think it would. (update pushed)

**Comment by kubecz3k** [comment]
will add early return when from==to

**Comment by kubecz3k** [comment]
done, now it's ready to merge.

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
