### PR TITLE
Rounded previews (and nicer script previews)

### PR DESCRIPTION
**Pull request by ghost**
Voilà:

previews

### CODE REVIEW

**Comment by capnm** [comment]
Rounding square things or squaring the circle;-) isn't something that I like.
I'd leave it as it is.

**Comment by akien-mga** [comment]
I don't mind either way for the rounded corners (though +1 for the improved script preview). CC @djrm and @toger5.

**Comment by djrm** [comment]
the general interface style for godot (at least currently) is very square-ish, in any case you could make the border radius more subtle and not like the godot default icon.

The changes to script preview look nice.

**Comment by toger5** [comment]
I like it. The preview always seemed cheap for my eyes.
With rounded corners it looks much better.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by poke1024** [comment]
@djrm Changed now to this:

v3-32

**Comment by djrm** [comment]
@poke1024 those fit the theme way better and are more neutral.

**Comment by Chaosus** [comment]
@poke1024 Could you make same for Graph editor nodes for visual script users ? That would be awesome..

**Comment by Chaosus** [comment]
And (I think its a good idea) adding slider to editor settings, which controls the "roundness" . So everybody could enjoy this change.

**Pull request merged**
