### PR TITLE
Remove `CustomPropertyEditor` completely

### PR DESCRIPTION
**Pull request by YuriSizov**
This PR removes the outdated `CustomPropertyEditor` dependency from both visual shaders and visual scripts, and replaces it with the familiar and supported widgets from the Inspector dock.

This PR also fixes a leak in visual shader editor plugin, that caused a stylebox to crash on exit (didn't find a reported issue for this).

-----

This change introduces some improvements to the property editors in VSes, but it doesn't change the base principle. It's still a button with a text value that brings up a popup panel with the property editor inside. The popup now stays open, because that's required for dragging in numeric fields. This PR also makes the popup respect the graph edit zoom in visual shaders (was already respected in visual scripts). Some property editors in visual scripts have been fixed too, it seems.

Some issues that are still present:

- Tabbing and shift-tabbing is not reliable, same as it is in the inspector. Probably a common bug and a common fix.
- Dragging in numeric fields breaks after one step, and mouse gets reset to the top left corner of the window. This is probably some issue with popups/windows.
- Values in visual shaders take a moment to update. This is present in the current master as well, but it's a bit too apparent when the popup stays open.
- In visual shaders default values of ports can benefit from defining some `PropertyInfo`s somewhere, so that we can configure these new widgets with more features enabled.

There seem to be other issues with the visual shaders, even prior to this PR. For example, the size of many nodes isn't computed correctly and the contents of these nodes overflows visual boundaries of a graph node. I think all of this should be fixed with a bugfixing/usability pass in future PRs.

-----
Testing of visual scripting is rather annoying because [we seem to have a regression and VS files cannot be opened upon the editor reload](https://user-images.githubusercontent.com/11782833/182220536-96309a3b-34af-4d74-8f4c-03bfbc4fdc6c.png).

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks great!

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Seems ok at a glance, guess testing will tell.

**Comment by reduz** [comment]
I completely forgot we never removed CustomPropertyEditor. It was the last vestige left of the old inspector that used Tree.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
