### PR TITLE
GDScript: Limit recursion depth for completion functions

### LINKED ISSUE #71446: Editor crash when using output of recursive function as array index
### Godot version

v4.0.beta.custom_build [60d031777]

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 1050 Ti (31.0.15.1694)

### Issue description

When typing out certain lines of code, the editor will suddenly crash.

It first happened when I was writing a Union-find data structure.

i.e.
```GDScript
extends RefCounted

var sets = []

func create(label):
	sets.push_back(label)

func find(label):
	if sets[label] == label:
		return label

	var root = find(sets[label])
	sets[label] = root
	return root

func union(a, b):
	a = find(a)
	b = find(b)
	if a != b:
		sets[a] = b
```
The editor will crash when trying to type out the last line.

### Steps to reproduce

```GDScript
var arr = []

func A():
	return A()

func B():
	arr[A()] = 1
```

- Create an array variable
- Create a function A that recursively calls and returns itself
- Create a function B that uses the output of function A as an array index, and attempt to set that array index to something
- The editor will crash when writing the equal sign in function B

### Minimal reproduction project

This project contains a script file which you can finish to crash the editor
[in editor crash.zip](https://github.com/godotengine/godot/files/10419400/in.editor.crash.zip)

### PR DESCRIPTION
**Pull request by vnen**
Avoid crashing if the completion gets stuck in infinite recursion while trying to guess the expression type.

Fix #71446

This adds an error message when it happens but perhaps it is a valid way to bail out in corner cases like the one in the linked issue, so we might consider removing the message if it gets triggered too often.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KnightNine** [comment]
Is this in 4.2.2?

When I crash the project window via recursion like this there's no error to be seen:
```gdscript
var run_size = 3500
var count = 0
func recur():
	count+=1
	print(count)
	if count >= run_size:
		return "x"
	
	var x = recur()
	return x

# Called when the node enters the scene tree for the first time.
func _ready():
	var x = recur()
	print(x)
```

I am also wondering what the limit on recursion is? It seems to crash somewhere past 300.

**Comment by akien-mga** [comment]
It works fine here on Linux with 4.2.2-stable:

image

**Comment by KnightNine** [comment]
@akien-mga 
Can you test it on windows?

**Comment by akien-mga** [comment]
@KnightNine I had two users check on rocket.chat and they both seem the same that I see, the debugger is properly catching the recursion and reporting it.

Are you running the project in the editor? Or exported with a release binary? The latter might crash, but a release export should only be made if you've made sure your project runs without errors in the debugger.

By the way, your issue is unrelated to this PR, which fixed a crash in the GDScript completion code.

**Comment by anniryynanen** [comment]
Here's what I see in Windows 11:

image

**Comment by KnightNine** [comment]
@akien-mga weird. ( yes. I am running it with the editor.) It works now when testing it with the official build. I don't thing I've done something to exclude this update when rebasing my local changes atop 4.2.2 because the crash happens before even the 1024 limit is triggered. 🤔

I'll need to test some things further.

**Comment by akien-mga** [comment]
So I gather you're doing a custom build with MSVC? If so that's probably why it doesn't work.
Could you open a dedicated bug report? Again, your issue is not related to this PR, which fixed a specific problem in the code completion, not running a project with recursion. Guards for infinite recursion were added years ago.

**Comment by KnightNine** [comment]
@akien-mga do certain things not work properly when compiled with scons on windows? is the official build compiled differently?
My issue isn't really not having guards against infinite recursion when it crashes at around 300-500 iterations of a recursive loop in this custom build... It's not related to this PR directly, I was just confused why my code wasn't even reaching the depth limit.

Maybe I didn't rebase it properly somehow idk, I have to look into it more to narrow down what the exact issue is.

**Comment by akien-mga** [comment]
> do certain things not work properly when compiled with scons on windows? is the official build compiled differently?

Official builds are made with MinGW-GCC, i.e. using the GNU GCC compiler.
You can also use it on Windows, but if your C++ compilation setup is Visual Studio / MSVC, that's what is used by default on Windows for custom builds.

Different compilers can different behaviors for similar configuration, or in this case they might have different config for the stack size between MSVC and GCC/Clang, which may cause this issue.

**Comment by KnightNine** [comment]
Maybe I shouldn't post this here but I was just thinking about how to circumvent the depth limit while still using a recursive function, it seems that depth is not preserved when a signal calls back to a lesser depth. So I made this loop that takes the recursive function and repeats it every 100 iterations while still preserving the parameters of the recursive function in case it's useful to anyone that comes here with a similar issue:

```gdscript
var run_size = 100
var total_run_size = 3500

signal x(local_count)
var last_x = null
var is_awaiting_x = false


#signal result_found()
#var last_result
func non_recur_loop():
	#last_result = "continue"
	var looping = true
	while looping:
		var local_count
		if last_x == null:
			is_awaiting_x = true
			local_count = await x
			is_awaiting_x = false
		else:
			local_count = last_x
		last_x = null
		
		if looping:
			
			var last_result = await recur(local_count)
			if last_result != "continue":
				looping = false
				return last_result
				
				
		

func pass_to_non_recur_loop(local_count):
	last_x = local_count
	if is_awaiting_x:
		emit_signal("x",local_count)
	



func recur(local_count = 0):
	
	print(local_count)
	
	if local_count >= total_run_size:
		return "x"
	if local_count >= run_size:
		pass_to_non_recur_loop(local_count+1)
		return "continue"
	else:
		var x = await recur(local_count+1)
		return x

# Called when the node enters the scene tree for the first time.
func _ready():
	print("---")
	pass_to_non_recur_loop(0)
	var x = await non_recur_loop()
	#stop loop:
	print(x)
	OS.alert(x)

```

**Pull request merged**
