### PR TITLE
added MacOS and Linux to GitHub Actions

### PR DESCRIPTION
**Pull request by RevoluPowered**
- Added GitHub actions for MacOS and Linux

### CODE REVIEW

**Comment by akien-mga** [comment]
> Moved static checks into the same workflow, and assigned name

What's the advantage to do this? I think it makes sense to have those separate.

**Comment by RevoluPowered** [comment]
> > Moved static checks into the same workflow, and assigned name
> 
> What's the advantage to do this? I think it makes sense to have those separate.

in some cases it was breaking the UI when I was pushing edits to the workflow it made it look like 3 runs were active rather than 2

**Comment by aaronfranke** [comment]
> > Moved static checks into the same workflow, and assigned name

> What's the advantage to do this? I think it makes sense to have those separate.

Speaking of this, why call everything "Godot CI"? Yeah, it's Godot's CI system... what else could it be? This name only shows up in the CI section of Godot commits and pull requests, so it's pretty redundant.

I think the main script should be renamed to "Builds" or something, and then "Static checks" should stay the same.

**Comment by RevoluPowered** [comment]
> > > Moved static checks into the same workflow, and assigned name
> > 
> > 
> > What's the advantage to do this? I think it makes sense to have those separate.
> 
> Speaking of this, why call everything "Godot CI"? Yeah, it's Godot's CI system... what else could it be? This name only shows up in the CI section of Godot commits and pull requests, so it's pretty redundant.
> 
> I think the main script should be renamed to "Builds" or something, and then "Static checks" should stay the same.

We can try it, but I prefer it being explicit, it's just a shame it repeats the name of the stages on the UI.

**Comment by RevoluPowered** [comment]
Screenshot 2020-07-14 at 22 29 49

I dislike this, so gonna leave it as Godot CI.

**Comment by RevoluPowered** [comment]
@aaronfranke better?

**Comment by aaronfranke** [comment]
Do [these names](https://github.com/aaronfranke/godot/commit/f58c494a5afe8f60b43dda2d405da464c8af49e7) not work?

**Comment by akien-mga** [comment]
Needs a squash, otherwise looks good to me. I might tweak the build matrix later on as as it stands we're only testing `target=release_debug tools=yes` and `target=release tools=no`, i.e. release binaries (which would make sense once we can host artifacts), but it would be good to get at least one build job testing `target=debug` eventually.

There's a lot of redundant set up for Python/SCons/caching in each job, it would be good if this can be factored out somehow eventually, but for now it should be fine.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I'll copy the whole `.github/workflows/` folder from `master` instead of cherry-picking individual commits.

**Pull request merged**
