### PR TITLE
fix to 'header_separator' requiring an extra space

### PR DESCRIPTION
**Pull request by quendera**
The HTTP spec does not require this extra space and therefore it throws an error with properly typed code on web export.

### CODE REVIEW

**Comment by akien-mga** [comment]
This will need a rebase to remove the merge commit, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

In general making a PR from upstream to your repo is not a correct way to update your fork's master branch, as both branches then have a different Git history. Instead, you should pull from the upstream repo locally, and then push to your fork.

**Comment by quendera** [comment]
my bad.
I'll redo it properly.

**Comment by akien-mga** [comment]
Well you could modify the PR by force pushing to your `master` branch as described in the above linked doc. Though I guess maybe you used the GitHub Web Editor, which is indeed too limited to properly handle a complex Git repository.

**Comment by akien-mga** [comment]
Specifically here this would have been:
```
git remote add upstream https://github.com/godotengine/godot
git fetch upstream
# Above two only needed once
git rebase upstream/master
git push origin master --force
```
(Assuming that `origin` is your fork, which should be the default if you cloned your fork.)

**Comment by quendera** [comment]
@akien-mga , fixed my fork's history, does the PR automatically update? Or should I make a new one?

**Comment by akien-mga** [comment]
It seems like the PR can no longer be reopened for some reason, so I guess you'll have to open a new one. Sorry for the trouble.

**Comment by akien-mga** [comment]
Superseded by #44121.

**Pull request closed without merging**
