### PR TITLE
JSON parser: add UTF-16 surrogate pairs support.

### PR DESCRIPTION
**Pull request by bruvzg**
Allow Unicode characters outside BMP (emoji, CJK extensions, etc.) in the parsed JSON strings.

See comments in https://github.com/godotengine/godot/pull/45545

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
I guess this might not be trivial to cherry-pick as is for `3.2` (if relevant/wanted)?

**Comment by akien-mga** [comment]
Thanks!

**Comment by bruvzg** [comment]
> I guess this might not be trivial to cherry-pick as is for 3.2 (if relevant/wanted)?

It should work as is (with `char32_t` replaced by `wchar_t`) on Linux/macOS but won't work at all on Windows (Godot string in 3.2 can't hold chars with values > 0xFFFF).

**Comment by akien-mga** [comment]
Thanks, then I guess it's best not to backport and keep this 4.0+.

**Pull request merged**
