### PR TITLE
[Scene] Add `SceneStringName::hover`

### PR DESCRIPTION
**Pull request by Chaosus**
Just an internal enhancement.

### CODE REVIEW

**Comment by AThousandShips** [comment]
I think it'd be good to establish some kind of limit where this is considered relevant

Did you have some limit when cleaning out some cases @KoBeWi?

**Comment by Mickeon** [comment]
The difference between these two macros still rather puzzles me, at least some comments would be nice.

**Comment by AThousandShips** [comment]
`SNAME` creates a static `StringName` in *each* place it is used, `SceneStringNames` is one single declaration that's reused

**Comment by KoBeWi** [comment]
> Did you have some limit when cleaning out some cases @KoBeWi?

I deleted names if they were used once or twice, so anything above would qualify. But it's different with adding new names. *Technically* adding new SceneStringNames has no downsides, but the more we have them, the more difficult is to keep track of them, which might eventually lead to inconsistencies like we had before. And opting for using a SceneStringName for everything is not very convenient. #99984 makes it easier to add new names, but it still requires major recompiling of the engine.
SNAME is a middle ground between performance and convenience. You can use it easily, but it comes with some drawbacks when overused.

> SceneStringName:
Uses a singleton
Allocated on startup
All uses of it are shared, and access should be optimized out

They also prevent typos.

**Review by KoBeWi — APPROVED** [review]
So as I said, we could technically add SceneStringName for everything, but that's lots of effort and not really worth it that much. If you went ahead and created another one then why not.

To keep consistency, we could create a script that detects missing usages of existing SceneStringNames. I think I had one when I was doing my cleanup🤔

**Pull request merged**
