### PR TITLE
embree: Allow building against system library on Linux

### PR DESCRIPTION
**Pull request by akien-mga**
Tested on my distro Mageia, I could successfully link against system-packaged `lib64embree3-devel-3.12.1-1.mga8` which seems to be the same version we vendor (and our patches are only for Windows/MinGW support).

### CODE REVIEW

**Comment by akien-mga** [comment]
Actually doesn't work with a build from scratch as the `common/math` stuff from Embree is not part of the public headers it seems, yet we rely on them:
```
modules/raycast/lightmap_raycaster.cpp:34:10: fatal error: math/vec2.h: No such file or directory
   34 | #include <math/vec2.h>
      |          ^~~~~~~~~~~~~
```

**Comment by JFonS** [comment]
I think I can get rid of those imports, I will take a look.

**Comment by akien-mga** [comment]
Rebased after #48089 and removed `thirdparty/embree/common` from the include path. Seems to work fine locally with both vendored and system Embree.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
