### PR TITLE
Update GDNative API

### PR DESCRIPTION
**Pull request by lupoDharkael**
This PR condenses all my finished PR's related to GDN. I did individual PR's because I thought atomic contributions would be the best option but I did more than I expected.

List of closed PRs:
https://github.com/godotengine/godot/pull/23155
https://github.com/godotengine/godot/pull/23182
https://github.com/godotengine/godot/pull/23152
https://github.com/godotengine/godot/pull/23151
https://github.com/godotengine/godot/pull/23150
https://github.com/godotengine/godot/pull/23149
https://github.com/godotengine/godot/pull/23197

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you squash the commits together?

**Comment by lupoDharkael** [comment]
squashed!
I found https://github.com/godotengine/godot/blob/master/modules/gdnative/gdnative_api.json has to be updated too. I can do it in this PR.

**Comment by akien-mga** [comment]
>  I found https://github.com/godotengine/godot/blob/master/modules/gdnative/gdnative_api.json has to be updated too. I can do it in this PR.

Sounds good, though maybe you should wait for @karroffel's feedback, I'm not sure if they should be added directly or via the "next" system.

If you amend, please consider making the commit log a bit more verbose (we prefer less commit but explicit ones :)), e.g. "Add missing Variant methods to GDNative API".

**Comment by lupoDharkael** [comment]
Maybe I should merge https://github.com/godotengine/godot/pull/23197 here and complete `godot_color_from_hsv`, as the PR I was waiting for has been delayed to 3.2
I'll have to add the const qualifier to 'from_hsv' of the Color class because the compiler was unhappy with this assignment:
https://github.com/godotengine/godot/pull/23197/files#diff-7d10d27d514f1af2f1ed9d463930f438R190

**Comment by karroffel** [comment]
> I'm not sure if they should be added directly or via the "next" system.

Yes, in #21602 I added a new GDNative core extension. Those things should live in there. Look at the diff of the json file to know where you have to put those functions.

**Comment by lupoDharkael** [comment]
I've merged #23197 here, updated gdnative_api.json and added the const qualifier to `from_hsv` of the class Color so it respects const correctness in the gdnative function.
I'll try to recheck the modifications gdnative_api.json because it's easy to make a mistake with so many things to track.

**Comment by lupoDharkael** [comment]
Everything is ready for the review.

**Review by karroffel — APPROVED** [review]
Looking good

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
