### PR TITLE
Upload artifacts as assets of a tip (nightly/latest) pre-release

### PR DESCRIPTION
**Pull request by umarcor**
This PR is based on #75338, which is a duplicate of #65232. Therefore, it is to be kept as a draft until #65232 is rebased and/or merged.

Currently, users can download artifacts from workflows. However, that requires login and it cannot be easily automated because workflow run URLs are not human-readable.  Therefore, they rely on third-party solutions or on manual action to get the pre-built editor and templates with latest fixes.

This PR adds a reusable workflow named `tip.yml` to be executed after all other workflows are finished and successful, as long as the CI run was triggered by a push to branch `master`. This workflow downloads all the artifacts, packages the content, computes the sha256sums and uploads everything as assets of a pre-release named `tip`, which is linked to tag `tip`. After uploading the assets, tag `tip` is updated.

As a result, users will have fixed URLs to download the very latest editor and templates, without requiring login.

Step 'Prepare assets' in this PR is just a naive prototype. I would need advice from some maintainer to properly decide which assets to upload and how to name them.

Related:

- godotengine/godot-proposals#1412
- #42422
- godotengine/godot-proposals#1458

---

Since the tag is updated, the pre-release in https://github.com/godotengine/godot/releases will always point to the commit that last updated the assets, and the description of the pre-release will be the body of that commit. However, the date will be "wrong". It will be the day the pre-release was created (which some maintainer needs to do before merging this PR). It seems that GitHub does not support changing the date of a release; it must be deleted and created again, which is unnacceptable for tip/nightly because it creates too much noise.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Builds produced by the CI are not suitable for publishing as official releases. They are not compiled with regular flags and optimizations, not all platform combinations are covered, and they are not signed. Therefore making those builds a part of the releases section would be misleading and not useful to most users.

Instead we plan to provide official nightlies in the future, signed and compiled with the appropriate flags for all supported platforms. We will also provide pre-compiled builds of important PRs, suitable for user testing and UX feedback.

**Comment by YuriSizov** [comment]
> tips are not expected to be comparable to official releases

Exactly, but this feature suggestion, this PR doesn't work without publishing the tip as an official pre-release. Which, as I explain, is a problem, because it sends a wrong message about the usability of these builds. If this was done as a dedicated resource, be it a separate repository or a third-party website, then it's not a problem. But there is more to consider when it comes to what we officially publish on the main channels.

There is no ETA for the nightlies, things in Godot development take time to materialize. But thankfully, you don't need to duplicate anything. Everything is already provided for anyone to use as https://github.com/godotengine/build-containers.

**Comment by YuriSizov** [comment]
> It should be pretty easy to set up and to publish as a GitHub Pages website. I might even do it this week, seems useful.

Here we go: https://godotengine.github.io/godot-commit-artifacts/
The "Latest" section contains permanent links. It's possible that sometimes not all builds are available (the database is refreshed every hour, but there may be many builds in progress, or artifacts could've expired). But it should make things easier.

**Comment by umarcor** [comment]
Well, that was an impressive turnaround. I'm speechless 😲 

Currently, none of the links is working for me. But, nevermind. I'll close this and we can handle it through issues/PRs in godot-commit-artifacts.

**Pull request closed without merging**
