### PR TITLE
Rename VisibilityNotifier2D/3D to VisibleOnScreenNotifier2D/3D

### PR DESCRIPTION
**Pull request by reduz**
* Renames for 2D and 3D, notifiers and enablers.
* Class name was confusing, given both 2D and 3D have a "visible" property that is unrelated to actual on-screen visibility.
* New name makes it clear that this is about visibility on screen.

### CODE REVIEW

**Comment by Zireael07** [comment]
Maybe shorten to "OnScreenNotifier"? VisibleOnScreenNotifier is kinda long...

**Comment by reduz** [comment]
@Zireael07 I don't think the name is that long, and what matters her is that its easy to understand what it does from the name, which was not the case before.

**Review by JFonS — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Some shorter name options were discussed but overall this seems to be the most explicit about what it does, so it's good. The main issue of `VisibilityNotifier` is that it wasn't clear to users.

**Comment by akien-mga** [comment]
Thanks!

**Comment by takhimi** [comment]
Hi. I have a question, if the VisibleOnScreenNotifier is visible =false or the parent node is visible=false, when it has entered the screen , it wont emit the "screen_entered" signal ?

**Pull request merged**
