### PR TITLE
Added Crash Handler for godot android editor.

### PR DESCRIPTION
**Pull request by ghost**
Hello devs of android editor, i have attached a screenshot of crash handler for android editor.
Screenshot_20230106_153623
 
This editor version i have tested on my mobile. And i clicked on open in file manager and then editor crashed, we got logs.
I hope this contribution helps godot to be more better.

### CODE REVIEW

**Comment by m4gr3d** [comment]
@Rajdave-dev I appreciated the effort, but I am not sure this functionality is needed. 
We'll be making the Godot Android Editor builds available through the Play Store which provides automatic crash reports with detailed device information when the app crashes; as such I don't see the need to roll out this functionality ourselves.

Do you have a use-case where this functionality would be needed?

**Comment by Rajdave-dev** [comment]
> @Rajdave-dev I appreciated the effort, but I am not sure this functionality is needed. We'll be making the Godot Android Editor builds available through the Play Store which provides automatic crash reports with detailed device information when the app crashes; as such I don't see the need to roll out this functionality ourselves.
> 
> Do you have a use-case where this functionality would be needed?

while godot is not published to play store.

**Comment by Rajdave-dev** [comment]
> Do you have a use-case where this functionality would be needed?

Godot android editor will has to be stable to publish on play store. Till editor is not stable this crash handler will give us logs to fix crashes who has no pc to debug app.

**Comment by Rajdave-dev** [comment]
@m4gr3d if you think this is not mergable close this pull request.

**Comment by Rajdave-dev** [comment]
I will create issue when i get logs. I am closing this.

**Pull request closed without merging**
