### PR TITLE
Fix theme for Mesh menu

### LINKED ISSUE #14583: Mesh menu dialogs don't have editor theme
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Antergos x86_64 - 36ce7c4

**Issue description:**

Dialogs in this menu don't have editor theme.
image
imageimage image image

### PR DESCRIPTION
**Pull request by volzhs**
Fix #14583

### CODE REVIEW

**Comment by Noshyaar** [comment]
Does this mean non-Control nodes breaks Theme inheritance? Is this intended?

**Comment by volzhs** [comment]
@Noshyaar I'm not sure but I guess so.

**Comment by Noshyaar** [comment]
```
<Noshyaar> Is it intended that non-Control nodes break Theme inheritance?
<reduz> Noshyaar: oh very possibly
<reduz> Noshyaar: should probably be fixed
```

I think it'd be better to make it inherits Theme properly so that the issue won't happen again.

**Comment by volzhs** [comment]
@Noshyaar as you know, it needs to dig deeper.
what about creating another issue for it?

**Comment by volzhs** [comment]
ok, I tested it with `Node2D` instead of `Control`.
and it works as expected also.
so, theme is inherited with `CanvasItem` (Node2D, Control) but not `Node`

**Pull request merged**
