### PR TITLE
Added multiplier to fix color in Mobile renderer

### LINKED ISSUE #79931: Clear color is lighter on mobile renderer
### Godot version

4.1.1

### System information

windows 11, mobile renderer

### Issue description

On Mobile Vulkan renderer, the clear color is 50% lighter than expected

See steps to reproduce and Minimal reproduction project below.

The box and background have the same color on Forward+ and compatibility, but not on Mobile
happens also in runtime on exported project, not only in editor preview

Images of the same scene from
compatibility:
compatibility
Forward+:
forward
Mobile:
mobile

### Steps to reproduce

 - add a CSGBox3D with "unshaded" shading, and albedo of #545454
 - add environment with Background = Custom color and color of #545454

Box and background are not the same color

### Minimal reproduction project

[bg_color.zip](https://github.com/godotengine/godot/files/12174822/bg_color.zip)

### PR DESCRIPTION
**Pull request by Vennnot**
Relevant [Issue](https://github.com/godotengine/godot/issues/79931)

I carried out the changes as stated in the original issue. Please let me know if this is not the best solution. I am a novice with C++ and even more so in a project such as Godot.

* *Bugsquad edit, fixes: #79931*
* *Bugsquad edit, alternative to: #80933*

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you for contributing!

You've included an incorrect file, you need to remove it

**Comment by Vennnot** [comment]
Whoops, my bad! I still don't know how to handle git log 😄 

I've deleted the file 👍

**Comment by Vennnot** [comment]
Should now be one commit!

Learning more and more

**Comment by Vennnot** [comment]
I hope so. I've always used GUIs for years but this is my first time doing it from console. Strange new world.

I still can't run Godot in CLion since it can't find Scons for some reason. But we're getting there!

**Comment by akien-mga** [comment]
Superseded by #80933.
Thanks for the contribution nonetheless!

**Pull request closed without merging**
