### PR TITLE
Optimize octree and fix leak

### LINKED ISSUE #38142: Game freezes and causes memory leak when changing spatial node's scale
**Godot version:** 
Godot 3.2.1

**OS/device including version:**
Windows 10 Home 64 bit

**Issue description:**
I wanted to make a simple animation through code for spike obstacle in my game, where spikes's scale would change using custom easing function. How it looks in GDScript:

```gdscript
func _physics_process(delta):
    # ... some logic code ...
    var s = _ease_out_back(t)
    _mesh.scale = Vector3.ONE * s
    # the value of t is in range from 0 to 1, _mesh is a reference to MeshInstance node

func _ease_out_back(t):
    t = clamp(t, 0, 1)
    t -= 1
    return 8.7*t*t*t + 7.7*t*t + 1
```

However, the moment this code is executed, the game suddenly freezes and quickly starts consuming a lot of RAM to the point my OS becomes very unresponsive. 

**Steps to reproduce:**
Open minimal reproduction project and run. The game will freeze at boot splash screen and will start consuming RAM, _so please be careful and close the scene from the editor after several seconds_. The scene named Sphere contains code from example above, and I noticed that the game runs fine if Sphere's translation is all zeros and the problem only occurs when translation has certain non-zero value (in the project it is (0, -1.592, 0)). 

**Minimal reproduction project:**
[minimum_reprod_project.zip](https://github.com/godotengine/godot/files/4522914/minimum_reprod_project.zip)

### LINKED ISSUE #41480: High velocity on move_and_slide causes OS freeze
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10
OpenGL ES 3.0 Renderer: GeForce GTX 1650 SUPER/PCIe/SSE2

**Issue description:**
OS freezes after the velocity of the player gets big
image

**Steps to reproduce:**
Open the project below and run it (i would press esc before everything gets slow or you will have to force shutdown your pc)

**Minimal reproduction project:**

[Project.zip](https://github.com/godotengine/godot/files/5115170/Project.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
## Octant Limit
Prevents adding new octants until a limiting number of elements have been added to the current octant. This enables balancing the benefits of brute force against the benefits of spatial partitioning. The limit can be set per octree.

Project settings are added for the rendering octree only to set the best balance per project depending on number of tests per frame / tick, and the amount of editing of the octree.

## Octant Leak
Fixes octants being leaked when removing elements.
_This is mirroring @naithar fix for the leak #41122, so it can be self contained.
On suggestion from @clayjohn I have updated the leak fix to be similar to the other PR, and added naithar as co-author in case this ends up getting merged together, to make things easier for Akien._

## Cached linear local_vectors
(second commit) Instead of using linked lists at runtime this maintains a dirty flag per octant and builds on demand a linear list of Element pointers and AABBs which can be used for quicker cull tests. This can lead to significantly better test performance.

This is offered as a second version of the octree, Octree_CL. It is only used for the rendering octree currently, as it has only been shown to offer performance increases there so far.

# Background
As discussed with reduz, this prevents adding new octants until a limiting number of elements have been added to the current octant, and is probably a better option than directly limiting the depth of the tree. This enables balancing the benefits of brute force against the benefits of spatial partitioning. The limit can be set per octree.

Preliminary tests indicate that for visibility culling brute force is significantly faster than using the octree as is.

The implementation so far is very simple, it doesn't split octants until the limit is reached. This means that on splitting, some of the elements in the parent octant may have been better off in the children. I have written code to rebalance the tree on splitting, but it isn't significantly faster so is left out at this stage.

Scenes which particularly benefit are those containing large numbers of objects, especially large number of moving objects / created / erased. It can also significantly speed up cull tests with the cached lists. Most 3d games will see a modest improvement, but some may gain a 2x improvement in fps or more. This is highly dependent on to what degree octree is a bottleneck in particular game.

Fixes #38142
Fixes #41480
Related to #40059

## Notes
* The PR is less extensive than it looks in terms of line numbers, because it moves most of the existing octree into a separate file for multiple inclusion, and the addition of local_vector from Godot 4.0.
* This is made against 3.2, there will be a bit of porting to get it to work with master because of changes to geometry. Also there may be further modifications to the version in the 4.x branch in future as we move to other spatial partitioning schemes.
* It also adds some basic debugging facilities to the octree (TOOLS only).
* I've experimentally tried a system to automatically set the limit depending on the use case - but it is a very difficult problem. For instance some frames may do more tests than others, or a lot of tests on e.g. level startup. I've tried maintaining a running average but the more I think about it the more I tend to think we should have this as a project setting, set to a reasonable value, and then tweakable for better performance. I'm aware of the project settings bloat problem but I can't see an easy better way around this, so I'm going to add this to the PR.

### Local Vector
This PR introduces `local_vector.h` from Godot 4.x. This might be better as a separate commit so the octree changes could be reverted without the local_vector being reverted, if something else is relying on local_vector. Note that PouleyKetchoupp's PR #40313 also contains local_vector.

We could potentially merge local_vector as a separate commit first, then me and Pouley could modify our PRs. Leave this up to Akien though as to whatever works best.

## Demo
To try it out, load this project, and try changing the project settings `rendering/quality/spatial_partitioning/render_tree_balance`.

* At a value of 0.0 I get 26fps, and at 1.0 I get 240fps.
* For reference, with the old octree I get somewhere around 23fps.
* The relative speedup in this example depends how many can be culled, when all are culled the speedup is higher, when all are showing, less so, because the bottlenecks are elsewhere.
* In most cases for rendering, shifting the balance towards 1.0 (in favour of octree editing rather than tests) will give best performance. Tests only start to become the bottleneck when you are doing lots of them (100s or 1000s per frame), in which case shifting towards 0.0 can help (and the benefits of the linear cache start to really show).
* A balance of 0.0 is closest to the old octree behaviour. However it should still be faster due to linear caching which is always on.

[octree_test.zip](https://github.com/godotengine/godot/files/5052230/octree_test.zip)

### CODE REVIEW

**Comment by lawnjelly** [comment]
@clayjohn Just for reference, I've done some profiling of the godot physics octree and it looks like the lack of improvement with larger octant limits may be due to the pairing, which I haven't altered (and am not planning on changing).

For this reason I'm now thinking in terms of removing the project setting for the physics octree and just sticking with old version functionality for the physics octree and probably the visibility notifier octree (for safety), as the performance improvements are probably limited to the rendering octree.

I'm also trying to get some non-ugly compile time switching of whether to use the cached lists too (yes for rendering, no for physics as it will save memory and makes little difference to performance).

**Comment by clayjohn** [comment]
That sounds like a pragmatic approach. Enable the optimization only for where we know it helps in all cases. That way we can reduce the risk of the change as much as possible.

**Comment by clayjohn** [comment]
I tested out this PR a little bit this evening. Unfortunately, I spotted a regression. 

In the TPS demo, just moving the character at full speed causes the character to disappear until they are moved back to the original position, and then if you walk slowly they will not disappear. I am guess something is getting lost when objects move too fast.

The performance was slightly better with ``world/3d/spatial_partitioning/render_tree_balance`` set to 1.0. Although, I didn't expect much of an improvement as there are not very many moving objects. And not much is being created or destroyed.

**Comment by lawnjelly** [comment]
> I tested out this PR a little bit this evening. Unfortunately, I spotted a regression.
> In the TPS demo, just moving the character at full speed causes the character to disappear until they are moved back to the original position, and then if you walk slowly they will not disappear. I am guess something is getting lost when objects move too fast.

Ah that's not good I'll try and track that down. Possibly somewhere I'm not refreshing the cached list. The limit per octant should not (in an obvious way at least) be able to introduce regressions, unless there is an existing bug in e.g. the pairing.

There is actually a small existing bug in the PR in the brackets which I've noticed while trying to come up with an elegant refactor to allow optionally removing the cached lists. I doubt it is causing the regression but I'll know soon. 

> The performance was slightly better with `world/3d/spatial_partitioning/render_tree_balance` set to 1.0. Although, I didn't expect much of an improvement as there are not very many moving objects. And not much is being created or destroyed.

Yes I think despite the hype in vblanco's thread #23998, optimizing the octree seems to only give a large overall improvement in certain scenarios - like you say lots of moving objects (say an asteroid type game). The octree is often running significantly faster, but when everything else is also slowing things down, it isn't always that much of a bottleneck in the overall frame time.

I don't think this is a good reason not to sort these problems though. I get the impression there are multiple key bottlenecks in Godot currently (including things like octree, gdscript, variants, nodes, threading overheads using things like visual server / physics, GPU fill rate, occlusion) and they will all need to be improved in order to get great performance overall. Improving any one of them will give good improvements in specific benchmarks, but won't massively improve an 'average' game, only their cumulative effect.

**Comment by Calinou** [comment]
If anyone needs the tps-demo, you can download it from here (link valid until September 2020): https://0x0.st/iY8e.zip

**Comment by lawnjelly** [comment]
Ok, regression hopefully fixed. I missed out setting the dirty flag on the octant in Move(). I've put in an optional debug check to catch any of these cases in future (not enabled by default as it slows performance).

**Comment by clayjohn** [comment]
I tested the TPS demo on the latest commit and it appears to work great! :)

**Comment by lawnjelly** [comment]
_For future reference:_

Although I think this PR should be merged as is, based on some discussion about this maybe fixing #38142, in the future it may be worth investigating whether tiny objects can also cause problems due to runaway octants in the visibility notifier and godot physics octrees.

There are now 2 versions of the octree, the old one and the new optimized one, and the new one is only applied in the visual server octree, where it was shown to give performance benefit - the visibility notifier and the godot physics still use the old one.

However if it turns out the other octrees are susceptible to the runaway behaviour (I hesitate to call it bug, but it is an unwanted feature) we should look at solving this, either by swapping to the new octree, or modifying the old one to guard against this without affecting performance, perhaps with a simple depth limit.

**Review by clayjohn — COMMENTED** [review]
As far as I can tell this looks good. I like the approach to splitting the octree implementations. But this is really going to need @reduz' approval before merging. Hopefully we can steal his attention for a bit once he finishes with particles.

**Comment by akien-mga** [comment]
Alright, time to merge and get this battle tested in 3.2.4 beta 1 :)

@reduz says the changes seem fine but he's not so familiar with this code anymore to give an in-depth review, yet he trusts the extensive work done by @lawnjelly and @naithar.

So let's merge and see what happens, we should have plenty of time until 3.2.4-stable to catch potential regressions, if any.

**Comment by akien-mga** [comment]
Thanks hugely!

**Comment by jamie-pate** [comment]
I was hopeful this would fix my bottleneck, but I think it's related to 'pairing' which you mentioned is left out.
image
Unfortunately I don't get what 'pairing' means in this context or why it's running so slow :)

image

**Comment by lawnjelly** [comment]
The pairing is used for e.g. linking a light with objects, and the code for it is quite convoluted, and would need quite a bit more time for me personally to invest as I didn't write it (and I have many higher priority tasks). It is known to be inefficient, that's why it is planned to be removed in 4.x, with a bit of a paradigm shift.

For 3.x the emphasis is on compatibility and not breaking existing functionality, so it is difficult to remove pairing, it would either need to be made more efficient as is or rewritten in a 'black box' fashion. If someone else has time to spend on this I'm sure it would be welcome.

Incidentally make sure to try changing the `rendering/quality/spatial_partitioning/render_tree_balance` project setting if you are just using defaults, it may have at least some effect on your performance.

**Comment by jamie-pate** [comment]
I'm still getting the 30ms frame times when setting the visibility of these lights. I have a workaround in mind where I will use a proxy script to relocate the actual light nodes to the root so they do not have to have their visibility toggled when the geometry is hidden. Hopefully that will smooth it over until Godot 4

**Comment by lawnjelly** [comment]
If you create an issue with a minimum reproduction project, it is more likely to get looked at (I might be able to profile it and find something obvious for example).

**Comment by jamie-pate** [comment]
Done

I'm be curious at what your method is for profiling? I've only hacked in some statistics to the object visibility calls. I guess with it toggling every frame any old profiling will do? (I was trying to catch stuff that only happens every once in a while, which is harder)
[object-profiling.diff.txt](https://github.com/godotengine/godot/files/5323763/object-profiling.diff.txt)

**Pull request merged**
