### PR TITLE
Add Editor UI for merging meshes

### PR DESCRIPTION
**Pull request by lawnjelly**
Allow right click and "merge meshes" to merge selected meshes in the SceneTree.

merge_meshes_right_click

## Notes
* This is playing with some alternative ways of exposing the mesh merging functionality introduced in #57661
* Merging meshes ahead of time in the editor is simple to understand. But it makes changes after merging more difficult as the process is one way (unless you keep the source nodes).
* Has the advantage of being a pre-process, so doesn't slow down level loading.
* Being a pre-process allows the possibility of more complex / time consuming merging techniques. 
* @JFonS has suggested for runtime we could have a new Node type that merges all the meshes under it, so I'll have a go at that next.
* The undo / redo is banditting the existing delete function. This would need improving but there is no need at this stage as we may not go with this approach.

### CODE REVIEW

**Comment by sairam4123** [comment]
Can the merged meshes still be culled by the view frustrum? It's of no use if the merged meshes can't be culled by the view frustrum.

**Comment by fire** [comment]
I’m interested to see if I can combine my previous tech on atlas ing.

**Comment by Zireael07** [comment]
@sairam4123 IIRC they can't because they are well, one mesh. But in many cases a single mesh with many vertices will give you a better performance over 20 meshes with fewer vertices if they're positioned in such a way that you see most of them at the same time (so only a few are culled)

**Comment by lawnjelly** [comment]
> Can the merged meshes still be culled by the view frustrum? It's of no use if the merged meshes can't be culled by the view frustrum.

As indicated in #57661 , merged meshes cull as a group. This is not usually a problem if you merge meshes in a localized area. Even spread throughout a map, especially for low poly, the benefits of lower drawcalls can vastly outweigh culling accuracy, especially on GLES.

**Comment by fire** [comment]
I haven't touched this for years, but it has the textured merging strategy mentioned. https://github.com/godot-extended-libraries/scene_merge

Also it needs a mesh unwrapped generator. I didn't include that here.

**Pull request closed without merging**
