### PR TITLE
Consolidate OpenGL extension handling / version detection

### PR DESCRIPTION
**Pull request by shartte**
Added Glad to all platforms and moved responsibility for initializing Glad to the platform layer.
In addition, I regenerated Glad with OpenGL ES support, switched from compat to core profile and removed the loader code (so that it does not force a dependency on libdl on platforms that don't need it).

I've now added the new shared GL debug code and inserted a few basic ranges to test it's functionality.

This will now give some basic info during frame debugging as to what's going on. It obviously needs more work, but the foundation is there now.

image

I've also added support for the two Apple specific extensions which should allow the same kind of info to show up in XCode when doing frame debugging there.

### CODE REVIEW

**Comment by shartte** [comment]
I've now added the new shared GL debug code and inserted a few basic ranges to test it's functionality.

This will now give some basic info during frame debugging as to what's going on. It obviously needs more work, but the foundation is there now.

image

**Comment by fire** [comment]
We had a problem with ContextGL, because we need to generate one for vulkan. 

I forget if a vulkan context was necessary or not.

**Comment by reduz** [comment]
No, please let's not do this. There is a lot of code that needs to be different and NOT having GLAD will help catch bugs when stuff is not available. GLAD should only be for where GLES is not supported, not the opposite.

**Comment by shartte** [comment]
@reduz But both GLES2 and GLES3 make use of extensions on *all* platforms. Even on those that support GLES natively. Also, since the rastizer code is shared between platforms that do and don't support GLES natively, there's no actual way around feature-testing, is there? 

I just think that having an actual common foundation to build the rasterizers on makes it much easier to understand what's going on, rather than having to constantly keep in mind whether you're building for a desktop platform or not.

I guess an alternative would be dropping GLAD and going for an extension loader that omits any functions/definitions present in the GLES2/GLES3 baseline. We'd still have to maintain our own function definitions that go beyond platform GL headers for the desktop platforms.
The extension loader would also still have to look up extensions dynamically rather than linking to the extension functions directly, what do you really gain by that?

**Comment by reduz** [comment]
I still think the way it is is ok. Also, this will get to be modified a lot when I start the Vulkan port, so let's just not do further changes.

**Comment by akien-mga** [comment]
Closing as per the above.

**Pull request closed without merging**
