### PR TITLE
Update zstd to 1.3.8

### LINKED ISSUE #17374: Remove usage of experimental/private APIs of zstd
**Godot version:**
3.0.2, current master (b8423694)

**OS/device including version:**
Any.

**Issue description:**
We currently use experimental APIs from zstd, which are as such not exposed publicly in stable zstd releases compiled as shared libraries (i.e. those we could link against on Linux).

I don't think we have any reason to use such APIs, it was likely done without paying much attention to their availability, or lack thereof, depending on build options.

**Steps to reproduce:**
Build against system libzstd with `builtin_zstd=no`. Tested against zstd 1.3.2 and 1.3.4.

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
~Fix - #17374.~ **(I need to test)**

File `thirdparty/zstd/1314.diff` removed because it's already merged in zstd.

### CODE REVIEW

**Comment by guilhermefelipecgs** [comment]
> I guess we could keep the code behind `#ifdef`'s and make it opt-in, so that people who may have a use case for it can enable it. Once the API is made stable upstream, we can remove the option and enable it for everyone.

@akien-mga `ZSTD_p_compressionLevel` was replaced by `ZSTD_c_compressionLevel` and is released in version 1.3.8. Then I didn't added any `#ifdef`'s, ok?

**Comment by akien-mga** [comment]
Awesome, thanks! I'll try now to compile against system zstd 1.3.8 with those changes.

**Comment by akien-mga** [comment]
Yeah it doesn't fix #17374 yet:
```
core/io/compression.cpp: In static member function 'static int Compression::compress(uint8_t*, const uint8_t*, int, Compression::Mode)':
core/io/compression.cpp:84:33: error: 'ZSTD_c_compressionLevel' was not declared in this scope
    ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, zstd_level);
                                 ^~~~~~~~~~~~~~~~~~~~~~~
core/io/compression.cpp:84:33: note: suggested alternative: 'ZSTD_decompressStream'
    ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, zstd_level);
                                 ^~~~~~~~~~~~~~~~~~~~~~~
                                 ZSTD_decompressStream
core/io/compression.cpp:84:4: error: 'ZSTD_CCtx_setParameter' was not declared in this scope
    ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, zstd_level);
    ^~~~~~~~~~~~~~~~~~~~~~
core/io/compression.cpp:84:4: note: suggested alternative: 'ZSTD_CCtx_s'
    ZSTD_CCtx_setParameter(cctx, ZSTD_c_compressionLevel, zstd_level);
    ^~~~~~~~~~~~~~~~~~~~~~
    ZSTD_CCtx_s
core/io/compression.cpp:86:34: error: 'ZSTD_c_enableLongDistanceMatching' was not declared in this scope
     ZSTD_CCtx_setParameter(cctx, ZSTD_c_enableLongDistanceMatching, 1);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/io/compression.cpp:86:34: note: suggested alternative: 'zstd_long_distance_matching'
     ZSTD_CCtx_setParameter(cctx, ZSTD_c_enableLongDistanceMatching, 1);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                  zstd_long_distance_matching
core/io/compression.cpp:87:34: error: 'ZSTD_c_windowLog' was not declared in this scope
     ZSTD_CCtx_setParameter(cctx, ZSTD_c_windowLog, zstd_window_log_size);
                                  ^~~~~~~~~~~~~~~~
core/io/compression.cpp: In static member function 'static int Compression::decompress(uint8_t*, int, const uint8_t*, int, Compression::Mode)':
core/io/compression.cpp:178:37: error: 'ZSTD_DCtx_setMaxWindowSize' was not declared in this scope
    if (zstd_long_distance_matching) ZSTD_DCtx_setMaxWindowSize(dctx, (size_t)1 << zstd_window_log_size);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
core/io/compression.cpp:178:37: note: suggested alternative: 'ZSTD_DStreamInSize'
    if (zstd_long_distance_matching) ZSTD_DCtx_setMaxWindowSize(dctx, (size_t)1 << zstd_window_log_size);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                     ZSTD_DStreamInSize
```

The update is still good to take though :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
For the reference, since those symbols are on the way to be added to stable releases (probably by 1.3.9 or 1.4.0 I guess?), we probably don't need to bother fiing #17374 ourselves, upstream will do it for us.
The main incentive was for distros to be able to unbundle zstd, but so far they seem fine with it being bundled. If a distro maintainer proposes a patch to allow unbundling, I'm open to merging it, though it would mean that distro and official builds would have slightly different behaviour on compression.

**Comment by akien-mga** [comment]
Will not cherry-pick for 3.0.x, there is no clear gain and we should avoid changes that may impact its stability.

**Pull request merged**
