### PR TITLE
Fix `TreeItem` `get_prev*` methods when `p_wrap` is `true`

### LINKED ISSUE #85032: TreeItem get_prev_visible and get_prev_in_tree wrap broken
### Godot version

4.1.3

### System information

Ubuntu

### Issue description

using `TreeItem.get_prev_visible(wrap = true)` and `TreeItem.get_prev_in_tree(wrap = true)` returns `null` when reaching the beginning of the tree, It should instead wrap around when `wrap` is set to true.
It works fine with `get_next_visible()` and `get_next_in_tree()`

*Documentation:*
```

[TreeItem](https://docs.godotengine.org/es/4.x/classes/class_treeitem.html#class-treeitem) get_prev_in_tree ( [bool](https://docs.godotengine.org/es/4.x/classes/class_bool.html#class-bool) wrap=false )

Returns the previous TreeItem in the tree (in the context of a depth-first search) or a null object if there is none.

If wrap is enabled, the method will wrap around to the last element in the tree when called on the first visible element, otherwise it returns null.

[TreeItem](https://docs.godotengine.org/es/4.x/classes/class_treeitem.html#class-treeitem) get_prev_visible ( [bool](https://docs.godotengine.org/es/4.x/classes/class_bool.html#class-bool) wrap=false )

Returns the previous visible sibling TreeItem in the tree (in the context of a depth-first search) or a null object if there is none.

If wrap is enabled, the method will wrap around to the last visible element in the tree when called on the first visible element, otherwise it returns null.
```

*And here is the error:*
Captura desde 2023-11-17 18-39-08

### Steps to reproduce

1 - make a tree
2 - add 2 elements
3 - call get_prev_visible(true) from a button on the currently selected TreeItem
4 - Error

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by pafuent**
Fixes #85032

The code that fix the issue is courtesy of @Jesusemora, I just added unit tests for it and did a rebase with the latest changes on master.

### CODE REVIEW

**Comment by KoBeWi** [comment]
You can add the previous contributor as co-author: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by pafuent** [comment]
I didn't add it because I wasn't able to find [Jesusemora](https://github.com/Jesusemora) email. But the link that you shared mentions something about `no-reply` email. I'll try to use it.

**Comment by pafuent** [comment]
Done!!!

**Comment by pafuent** [comment]
Friendly remainder

**Review by KoBeWi — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by pafuent** [comment]
@Repiteo https://github.com/godotengine/godot/pull/85109 should also be closed

**Pull request merged**
