### PR TITLE
Add CreateDialog search filters

### PR DESCRIPTION
**Pull request by willnationsdev**
This adds buttons to the CreateDialog for showing/hiding 2D and 3D nodes. It relies on code from #25675.

Here is a screenshot example of it hiding the Spatial nodes:

3d_toggled_off

Edit: I've added an extra space between the text and the buttons so they aren't so close together.

Edit: Updated the design. Screenshot below:

create_dialog_1

### CODE REVIEW

**Comment by groud** [comment]
I think the feature is a good idea, but that's not how I would present it, the design does not look really professional.

I would add a button (with the "filter" icon) at the right of the search field, that provides a drop-down menu with two checkboxes, one for 2D and one for 3D.

**Comment by willnationsdev** [comment]
@groud ok. I'll work on a mock-up at the next opportunity.

**Comment by willnationsdev** [comment]
I've managed to redo the implementation to be much more clean and customizable for the future.

create_dialog_1

However, I'm having a problem: any time I click on the PopupMenu that the filter button makes visible, it causes the entire CreateDialog to close. I've programmed the PopupMenu to close in response to a change the visibility of the create dialog now, so the PopupMenu also closes, but I can't get the CreateDialog to stay open while I mess with the search filters.

Do I need to make the CreateDialog exclusive and then manually close it when the user clicks somewhere else / clicks on one of the buttons? Or is there a simpler alternative?

**Comment by willnationsdev** [comment]
As far as I can tell, this PR is now fully operational and bug-free. I've also removed its dependency on any other PRs so it can be merged whenever.

**Comment by willnationsdev** [comment]
Oh wait, looks like I spoke too soon. There's some kind of Resources still in use / Object instances still in use at exit error.

ERROR: SelfList<class GDScriptFunction>::List::~List: Condition ' _first != 0 ' is true.
   At: godot\core/self_list.h:111
ERROR: SelfList<class GDScript>::List::~List: Condition ' _first != 0 ' is true.
   At: godot\core/self_list.h:111
WARNING: ObjectDB::cleanup: ObjectDB Instances still exist!
     At: core\object.cpp:2086
ERROR: ResourceCache::clear: Resources Still in use at Exit!
   At: core\resource.cpp:425

Anyone know the best way of debugging this?

**Comment by reduz** [comment]
I am going to work on a bit different feature for 3.2 to do these kind of things, which will make this unnecesary.

**Comment by willnationsdev** [comment]
Given the introduction of the "only use what features you want in the editor" feature, we can close this PR. As reduz stated, it's completely unnecessary anymore as you have *much* more fine-tuned control over which nodes and resources are available.

**Pull request closed without merging**
