### PR TITLE
Colored indication for project versions inside ProjectManager.

### PR DESCRIPTION
**Pull request by syskrank**
Recreated this PR to work from a separate branch. Addressing #25497.

### CODE REVIEW

**Comment by aaronfranke** [comment]
For reference, here's what this PR currently looks like:



Issue: the paths for my projects are cut off by these notifications.

One has the word "project" and one doesn't, it should probably be consistent. 

Or, even better, it might be more useful to display specific versions and have `project.godot` contain exact Godot versions. For newer Godot projects this can be always explicit ("3.1.2" etc), and for older projects where the only version info is "config_version=3" it could just display "3.0.x" as the version etc.

**Comment by reduz** [comment]
maybe notification can be on a line above instead of same as path

**Comment by akien-mga** [comment]
This PR still needs to be update to address the issue in https://github.com/godotengine/godot/pull/25899#issuecomment-464185692.

**Comment by aaronfranke** [comment]
@akien-mga It might be better to scrap this PR and implement https://github.com/godotengine/godot/issues/25497, then color it.

**Comment by akien-mga** [comment]
Closing for now as it can't be merged as is. I also think that showing version numbers as suggested in #25497 would be more useful than a generic "Old version".

**Pull request closed without merging**
