### PR TITLE
Tweak the ORMMaterial3D editor icon to follow the Godot design guidelines

### PR DESCRIPTION
**Pull request by Calinou**
## Preview

ORMMaterial3D icon dropdown

<details>
<summary>Old version</summary>

ORMMaterial3D icon dropdown
</summary>

### CODE REVIEW

**Comment by fire** [comment]
Anyone else got distracted by the fact that green is top rather than red?

**Comment by timothyqiu** [comment]
I find it hard to recognize the green block with grey outlines.

**Comment by Calinou** [comment]
> I find it hard to recognize the green block with grey outlines.

I've pushed a new version that makes use of negative space:

ORMMaterial3D icon dropdown

**Review by fire — APPROVED** [review]
Looks good to me merge if you like.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
