### PR TITLE
[Windows, 3.x] Improve console handling and execute.

### PR DESCRIPTION
**Pull request by bruvzg**
Alternative for the #55967 improved version of #41164, shouldn't be affected by #41328 (which was caused by `adb` running on background and usage of `_wpopen()`).

With these changes, console behavior on Windows should be the same as on Linux and macOS:
- When editor is started from the console (or by another process with active console), output will be redirected to the parent console (including output from the running projects).
- When editor is started from the GUI (shortcut, Windows Explorer, etc.), no console is opened.

Changes:
- Always build with the GUI subsystem.
- Redirect stdout and stderr output to the parent process console.
- Use CreateProcessW for blocking `execute` calls with piped stdout and stderr (prevent console windows for popping up when used with the GUI subsystem build, and have more consistent behavior with non-blocking calls).
- Add `open_console` argument to the `execute` to open a new console window (for both blocking and non-blocking calls).
- Remove `interface/editor/hide_console_window` editor setting.
- Remove `Toggle System Console` menu option.
- Remove `set_console_visible` and `is_console_visible` functions.

### CODE REVIEW

**Comment by DmitriySalnikov** [comment]
It turns out that it will no longer be possible to launch Godot from a shortcut on the desktop with output to the console?
And there is no way to add an argument to run godot with the console, for example `godot.exe --open_console`?

**Comment by bruvzg** [comment]
> It turns out that it will no longer be possible to launch Godot from a shortcut on the desktop with output to the console?

Command line argument won't be passed to the child processes and console will be allocated for the process manager (the same issue as with passing `--video-driver` etc.).

But, you can use a batch file, like this:
```bat
@echo off
godot.windows.opt.tools.64.exe
pause > nul
```

Or add `cmd /k` to the target in the shortcut:
Screenshot 2021-12-17 111505

In both cases behavior will be similar to old. The only difference, terminal won't auto close after exiting/crashing the editor.

**Comment by bruvzg** [comment]
Everything seems to be working, but there's one breaking change.

Previously, it was possible to directly `execute` built-in commands like `dir` (it was working only in the blocking mode with piped output), now it won't work anymore, and `cmd /c` should be prepended to the command.

It's consistent with the non-blocking `execute` and should not be an issue, but probably it's too big  change for 3.4.1 and should be kept for 3.5. Also, documentation need to be checked and updated accordingly.

Tested it with MSVC, MinGW/GCC and MinGW/LLVM builds (original `RedirectIOToConsole()` code was working with GCC only).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
