### PR TITLE
ColorPicker: Properties to toggle the editability and visibility of presets

### PR DESCRIPTION
**Pull request by ZahFox**
These additions are related to the enhancements suggested in issue #26176. 
image

**With visibility removed:**
image

**With editability removed:**
Looks the same but the preset items and button  don't respond to input events.

### CODE REVIEW

**Comment by groud** [comment]
Honestly, I think the original issue is pointless. If you don't want presets, just don't use them. We do not need an editor settings to disable each feature of the engine.

This is going to bloat the engine settings and burry the useful options.

**Comment by YeldhamDev** [comment]
I could see this being somewhat useful if it was a option for each `ColorPicker` node, which I think that's what the original issue was actually referring to.

**Comment by groud** [comment]
> I could see this being somewhat useful if it was a option for each `ColorPicker` node, which I think that's what the original issue was actually referring to.

Ah indeed, that might be a parameter of the ColorPicker node, if people want to use it in games.

**Comment by CowThing** [comment]
I actually meant for this to be something that could be set on the colorpicker itself, not an engine-wide setting. Sorry if my wording was bad.

The reason I want this is because I want to have a colorpicker that doesn't have any presets on it, while still allowing all other colorpickers to have presets on.

**Comment by ZahFox** [comment]
I'll update this later today so that the editor settings are removed and then replace the logic with properties for the ColorPicker class.

**Comment by merumelu** [comment]
There is already an older PR which looks like more or less the same thing: #22766. Maybe you can collaborate with @lupoDharkael.

**Pull request closed without merging**
