### PR TITLE
[Core] Remove zero check in `next_power_of_2`

### PR DESCRIPTION
**Pull request by Nazarwadim**
I just found an unnecessary check and why not remove it.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Why is it unnecessary? It causes overflow otherwise, how is that prevented?

**Comment by Nazarwadim** [comment]
From this #81917, due to the fact that we have a very large x, this method returns 0 as it should return.
If you look at the logic of its work. Then we subtract 1 from 0 and get `UINT_MAX`. Then 1 is added and we get 0.

**Comment by AThousandShips** [comment]
Yes that's for the `next_po2` but that's not the case for the other one, where is the protection for that?

**Comment by Nazarwadim** [comment]
It works the same way there.
I will explain on `uint8_t`:
x = 00000000; than we then subtract 1 from x. Now x = 11111111. Than
x |= x >> 1 
x >> 1 = 01111111
11111111 | 01111111 = 11111111
The same for  x |= x >> 2, x |= x >> 4;
We get 11111111.
And next we add 1. Now x = 0. 
With `x == 0` check we return the same.

**Comment by AThousandShips** [comment]
Then the check isn't unnecessary, I don't expect it to be so costly it's more expensive than 5 shifts, five ors, and two additions

**Comment by Nazarwadim** [comment]
The probability that x will be 0 is very small. And the jump instruction will probably take the same amount of time.

**Comment by Nazarwadim** [comment]
You can look here to see the difference between the compiled code of these two functions https://godbolt.org/z/h7MacGeEe.

**Comment by AThousandShips** [comment]
Can you show performance improvements? The compiled code might differ but that doesn't necessarily translate to a performance boost, I'd say we shouldn't modify such core code without good reason, it's known to work as it is, but weird bugs can creep in if things are modified, so to me it's not worth it to modify it without some tangible improvement

"Could" doesn't always translate to "is", nor even "should", and again this is very sensitive code used a lot

**Comment by Nazarwadim** [comment]
You were right. There is almost no difference in performance.

**Comment by AThousandShips** [comment]
Please show your performance differences if you have any

**Comment by Nazarwadim** [comment]
According to QuickBenchmark, it is up to one percent.

**Comment by AThousandShips** [comment]
Does that represent our code setup and realistic distribution? It working faster in an ideal test case doesn't translate to how the code works in the actual engine, and with a 1% difference under such conditions it's likely none in practice

**Comment by AThousandShips** [comment]
Thank you for your contribution nonetheless, and hoping for future performance work, your work to improve the engine code is very appreciated!

**Pull request closed without merging**
