### PR TITLE
Add null check in godot result callback

### LINKED ISSUE #22156: Crash calling cast_motion
**Godot version:**
9af72f0

**Issue description:**
PhysicsDirectSpaceState cast_motion causes crash

more in depth:
in godot_result_callbacks.cpp
in GodotClosestConvexResultCallback::addSingleResult
convexResult.m_localShapeInfo is accessed unconditionally, but its called from 
btCollisionWorld.cpp, line 661
btCollisionWorld::objectQuerySingleInternal 
localConvexResult second parameter (that is, m_localShapeInfo) is null

to fix it I tried imitating what happens in GodotClosestRayResultCallback::addSingleResult and appears to work, but I don't know if this is a symptom of something more severe

**Steps to reproduce:**
use cast_motion to cast a shape against a static or rigid collision object
also SpringArm with shape is affected
intersect_ray works fine

run repro project, for convenience enable visible collision shapes and sync scene changes if you want to change something

[cast_crash.zip](https://github.com/godotengine/godot/files/2386701/cast_crash.zip)

### PR DESCRIPTION
**Pull request by muiroc**
if there are no surprises, fixes #22156 
edit:
ok just noticed this #21843

### CODE REVIEW

**Comment by Chaosus** [comment]
Thirdparty bugfix should contain comment `// -- GODOT start --` and `// -- GODOT end --`, a .patch of the change, and the following comment to thirdparty/README.md:

```
Important: Some files have Godot-made changes. They are marked with // -- GODOT start -- 
and // -- GODOT end -- comments and a patch is provided in the [thirdparty_module]/ folder.
```

**Comment by Chaosus** [comment]
See #17035, as an example

**Comment by muiroc** [comment]
Thanks, I didn't know about that procedure, but I don't understand, isn't modules/bullet/godot_result_callbacks.cpp part of an engine module?

**Comment by LikeLakers2** [comment]
Stuff under `modules/` is engine code, not supplied by a thirdparty. I don't believe you need to follow that third-party bugfix procedure since you didn't modify anything under `thirdparty/`.

**Comment by Chaosus** [comment]
Ah.. sorry my fault, its ok then

**Comment by AndreaCatania** [comment]
Thanks you for your contribution, this PR is fine

**Comment by akien-mga** [comment]
Thanks!

Does `GodotAllConvexResultCallback::addSingleResult` need some null checks too?

**Pull request merged**
