### PR TITLE
Fix duplicated entries in script editor menu

### PR DESCRIPTION
**Pull request by dakennedyd**
Hey guys i fixed the issue #43707, on 3.2 branch, it seems is already fixed on master.

### CODE REVIEW

**Comment by akien-mga** [comment]
That bug was from a merge conflict resolution gone wrong in #40461, CC @pouleyKetchoupp.

We be good to review both the regression commit and this fix to make sure that the final list of entries is correct.

**Comment by akien-mga** [comment]
@dakennedyd Could you amend the commit log to be more explicit about what it's doing? Outside GitHub, an issue number is not sufficient information on what a bug is/was. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

A good commit message would be e.g.:
```
Fix duplicates entries in script editor menu

This was a regression from #40461.

Fixes #43707.
```

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Thanks for fixing this!

Just one little thing to change: there's a missing separator between undo/redo and cut/copy/paste.

Apart from that it looks exactly like before the regression.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by dakennedyd** [comment]
Thanks for the help guys :)

**Pull request merged**
