### PR TITLE
[3.x] Add animation reset track feature

### PR DESCRIPTION
**Pull request by RandomShaper**
Version of #43115 for 3.x.

Probably this would be worth merging just once 3.2.4 is out, because it may benefit from some testing so both 4.0 and 3.2.5 can benefit from any fixes for issues discovered on it.

~~**UPDATE:** When #45810 is fixed for 4.0, the fix will be integrated here. Switching to draft until that happens.~~ Done.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Rebased!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Torguen** [comment]
I have no idea what this suggestion consists of, there is no information about it. Only in the title something is said minimally but no details.

**Comment by akien-mga** [comment]
Check the `master` pull request which was linked in the first post:

> Version of #43115 for 3.x.

**Comment by chucklepie** [comment]
Maybe I'm being a bit dumb, I'm on latest 3.4.2 but I have absolutely no idea how to use this. Create a new or existing animation player and 'apply reset' is blank an no 'RESET' animation is created. Create a new animation with properties and add a key frame, 'apply reset' is blank and no new 'RESET' animation is created. I add a new animation called 'RESET' and it makes it a reset but it's blank. Repeat the above and nothing happens.

I thought I read 'RESET' is auto-created on first save as I have reset on save set, nothing happens for me.

I read about 'Create Reset Track(s)', but this is nowhere to be found.

**Comment by Calinou** [comment]
@chucklepie The RESET track should not be created manually. The editor will ask you to create it automatically when you insert a new track in an existing animation by clicking the key icon next to a property.

**Comment by chucklepie** [comment]
Ah, when I create a track I usually do it the longer way -  'add track' then select the node then select property. How is this different to clicking the key icon as they both do the same thing, but only one adds a reset entry?

**Comment by Calinou** [comment]
> Ah, when I create a track I usually do it the longer way - 'add track' then select the node then select property. How is this different to clicking the key icon as they both do the same thing, but only one adds a reset entry?

This is a known issue, see https://github.com/godotengine/godot/issues/55438.

**Pull request merged**
