### PR TITLE
Add `_get_configuration_warnings()` example

### PR DESCRIPTION
**Pull request by KoBeWi**
Inspired by #75573

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by MacdonaldRobinson** [comment]
Thanks for this @KoBeWi as mentioned in this comment here: https://github.com/godotengine/godot/issues/75573#issuecomment-1493318563

If you have inheritance setup, and you have @tool and  _get_configuration_warnings() at top most level you need to add @tool at all the levels or it wont work

**Comment by AThousandShips** [comment]
You only need `@tool` on the script attached to the node, which is to be expected as it won't run in the editor if it doesn't

**Comment by KoBeWi** [comment]
`@tool` not being inherited is another issue: https://github.com/godotengine/godot-proposals/issues/754

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.

**Pull request merged**
