### PR TITLE
Clip numeric vectors in property editor

### PR DESCRIPTION
**Pull request by ghost**
It would be nice to have some text clipping for vectors when the property tree is not wide enough, e.g. (look at the Translation vector dynamically adapting to the width of the property panel view):

https://www.dropbox.com/s/uhp1l71wg4l3c5s/demo-clip-numeric.mp4?dl=0

(usually I end up having an x coordinate of something like 382.478361 and don't see anything else).

Not sure if this PR's approach of adding `TreeItem::CELL_MODE_CUSTOM_NUMERIC` is a good idea, especially as it's an API change; it has to be a cell property though.

### CODE REVIEW

**Comment by Zylann** [comment]
tbh I find the area too small... wasn't there an issue about this? I can't find one but I'm sure it was mentionned at some point

**Comment by groud** [comment]
I am not sure it is a good idea. In some cases, some people want to test for specific property value. So if it's rounded in the editor they might not understand why their test does not work. 
For example, if x=0.9999 is rounded to 1.0 in the editor, and we test x >= 1.0, the result is false which is inconsistent with what the editor tells us. 

Honesty, I would wait for the rewrite of the inspector so that  we can see if a new design can overcome those problems.

**Comment by poke1024** [comment]
Not sure I understand which tests we are taking about here (automated tests?). Note that this is only a display feature and the underlying text in the tree cell is the untampered, unrounded number. Only if the cell width is not wide enough, will it get rounded for display.

**Comment by groud** [comment]
I mean any value test in the code. Like, considering the example above :
```
if (x >= 2.0):
  print("Do something")
```
If the column is not wide enough, we may have a displayed value that will be 2.0 instead of 1.9999,  while the above code prints nothing. It's inconsistent and people may complain about this. Also, you have no clue to tell you if the number has been rounded or no.

If we have to get some room here, it'd be better cutting (not rounding) the numbers and adding `...` to notify that the whole number is not displayed.

**Comment by poke1024** [comment]
Adding `...` is a good idea. But I still don't understand how any code could access that rounded number. It's stored nowhere (well, in a local variable in the cell's drawing function).

**Comment by groud** [comment]
No need to access the value. What I mean is that the rounded value displayed is different from the real value of the variable: this is misleading, and people might complain about it.

If we have the `...`, at least people will understand than the number is truncated (and will expand the column/click the property if needed).

**Comment by poke1024** [comment]
Changed to this:

transform

**Comment by poke1024** [comment]
Another variant would be this, not sure which one is better (I personally tend to this one):

v2

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by akien-mga** [comment]
Once again sorry for the very late answer.

`PropertyEditor` is now deprecated and has been replaced by `EditorSpinSlider`, so these changes would need to be ported over to the new system. Closing for now as the branch would need a complete rewrite, but feel free to make a new PR with those changes for `EditorSpinSlider` (a newer PR might also help with visibility to get prompt reviews).

**Pull request closed without merging**
