### PR TITLE
[3.2] Sync csproj when files are changed from the Godot FileSystem dock

### PR DESCRIPTION
**Pull request by neikeq**
Backport of #37116 to 3.2.

### CODE REVIEW

**Comment by akien-mga** [comment]
Don't you need to expose the FS dock too?

**Comment by neikeq** [comment]
@akien-mga I thought that would be cherry-picked separately, I forgot to mention that. Do you want me to include the commit in this PR?

**Comment by akien-mga** [comment]
Yeah since this PR is dependent on that cherry-pick, you might as well include it directly. You can use `git cherry-pick -x` to get a nice reference to the cherry-picked original commit.

**Comment by neikeq** [comment]
Done. The cherry-picked commit also needed to rebase because of the `connect` changes.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
