### PR TITLE
Add a new high quality tonemapper: ACES Fitted (3.x)

### PR DESCRIPTION
**Pull request by Lauson1ex**
3.x version of #52476.

Adds a new high quality, tonemapper mode which is more physically accurate. This one better represents how lighting works in the real world. High energy lights or emissive materials will become lighter as they get brighter, eventually becoming white if its color is bright enough to saturate the camera sensor.

Closes [#3214](https://github.com/godotengine/godot-proposals/issues/3214) 🙂

**Current Godot implementation:**
image

**ACES Fitted:**
image

**Current Godot implementation:**
image

**ACES Fitted:**
image

**Current Godot implementation:**
image

**ACES Fitted:**
image

Additionally, fixes a small bug in the tonemapper that clamped colors even when tonemapping was disabled. Fixes the issue found while reviewing PR [#51708](https://github.com/godotengine/godot/pull/51708#issuecomment-904963226). Now the PR should work as expected. 🙂

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Implementation looks good, I'm not sure what is going on with the documentation checks though, its saying the new enum should not be added.

**Comment by atirut-w** [comment]
> Implementation looks good, I'm not sure what is going on with the documentation checks though, its saying the new enum should not be added.

My attempt at an educated guess: forgot to update docs, maybe?

**Comment by bruvzg** [comment]
>  I'm not sure what is going on with the documentation checks 

`BIND_ENUM_CONSTANT(TONE_MAPPER_ACES_FITTED)` is missing from the `VisualServer::_bind_methods`

**Comment by Lauson1ex** [comment]
> `BIND_ENUM_CONSTANT(TONE_MAPPER_ACES_FITTED)` is missing from the `VisualServer::_bind_methods`

Thanks. Updated 🙂

**Comment by akien-mga** [comment]
Thanks!

**Comment by Leocesar3D** [comment]
Sorry to necropost, but shouldn’t this visual tweak be also available to the other Tonemap modes, like Filmic and the others? Being it just the way emissive materials behaves regardless of how you tonemap your scene. Is it possible?

**Comment by clayjohn** [comment]
@Leocesar3D this is not a change to the way emissive materials are handled. It is a different, more correct, way of implementing tone mapping using the ACES colour space.

**Comment by atirut-w** [comment]
Giving Filmic its own "Fitted" version still sounds good, though.

**Pull request merged**
