### PR TITLE
Change reserved keyword in Regex documentation code

### PR DESCRIPTION
**Pull request by VedatGunel**
See #45074.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by georgetye** [comment]
Am I missing something? It's still not changed.

image

**Comment by akien-mga** [comment]
It's changed in the engine repo, it will be changed in the docs next time they're synced with the engine code.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
