### PR TITLE
Corrects small typo in atan2() documentation.

### PR DESCRIPTION
**Pull request by ghost**
Try not to be overwhelmed.  😄

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Comment by avencherus** [comment]
@akien-mga I'm unfamiliar with how you handle the cherrypicks to older versions.  Should I leave my branch, or do you cherrypick from the master?  I was assuming from the master, but figured its worth double checking.

**Comment by bojidar-bg** [comment]
@avencherus He cherrypicked it as d02ee1ff0eb55aa4daed1aa333870c326e8b4f4d in the 3.1 branch.
It is usually done from the master branch, though it actually doesn't really matter which branch it is made from -- cherrypick just moves the commit to a new parent.

**Comment by avencherus** [comment]
@bojidar-bg Thanks.

**Pull request merged**
