### PR TITLE
added more gamepad mappings

### PR DESCRIPTION
**Pull request by adolson**
added some more mappings and cleaned up some existing ones (removal of superfluous platform variable).

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks :) Could you try to merge the "oops" commit into the first one as a "fixup" when doing a git rebase? i.e.
- ```git rebase -i HEAD~2```
- In the opened editor, replace "pick" before the 25548ee commit by "fixup".
- Save and quit, it will get rebased.
- If everything works fine, ```git log``` shows only 1 commit.
Then you can force push to your branch to update this PR.

**Comment by adolson** [comment]
Done. I didn't know I could do that...

**Comment by akien-mga** [comment]
Yeah git is quite hard to use, one learns new useful commands every now and then :)

**Comment by Hinsbart** [comment]
The linux mappings for the "Generic X-Box pad" and "Saitek PLC" have multiple definitions for some events (sometimes also mapping to different values). I think I also saw this in some of the mappings that came from SDLs db.

What tool did you use to get these mappings? ^^

**Comment by adolson** [comment]
Most come from https://github.com/gabomdq/SDL_GameControllerDB , but I also
used controllermap from SDL2 for a Hori pad. I have to dig out my other
gamepads and check those when I can.

**Comment by adolson** [comment]
Another thing I noticed - I sorted the mappings, and I see a couple dupes
in the Windows mappings. 79000600000000000000504944564944
and 8f0e0300000000000000504944564944, though the second field, the name, is
unique. Should the dupes be removed? Can we edit the name field here as
well, to match the model? And in cases of dupes, how do you choose which
name?

**Comment by Hinsbart** [comment]
The name field can safely be edited, yes. We don't use it at all.
Also I think the dupes should be removed, but regarding the question of which name to choose.. I have no idea

**Comment by adolson** [comment]
OK, I removed that Saitek one. It was just too messed up to guesstimate a fix. The Xbox one seemed trivial to fix. I also sorted the mappings which should help us catch dupes in the future.

**Pull request merged**
