### PR TITLE
Fix emission calculation for spatial shader

### PR DESCRIPTION
**Pull request by maxim-sheronov**
I think, that current emission calculation is incorrect, or at least not convenient.
Current logic sums color and value from texture. That means, that you can't use texture as mask to make some parts of mesh emitting. Or you can use black color on texture to not emit, but color become useless. And you can't use it as tint to colorize emission.

I suggest to use texture as mask by multiplying it with color instead of summation.

Also I changed hint color for case, when you don't need a texture.

### CODE REVIEW

**Comment by Zireael07** [comment]
and here I was wondering why my emission mask does nothing in 3.0, thanks man!

**Comment by fracteed** [comment]
Excellent! I have been meaning to create an issue for this. Look forward to trying it out :)

**Comment by reduz** [comment]
I thought it might be more useful the current way, but if you prefer this way I'm fine too. PR looks perfect.

**Comment by reduz** [comment]
I was thinking about it, and I'm not sure if this proposal is better. The rationale is the following:
- Emission and Emission texture in general are not used together, this is rare
- If using a multiplication, you will need to set emission to white besides setting a texture for it to work, I don't think this is very intuitive.
- The only benefit I see this could have is controlling the intensity of the emission, but you can already do this with the energy color

So I think after thinking about it for a while, that this PR is a bad idea, it just makes emission more restricted.

**Comment by tagcup** [comment]
Isn't the current behavior similar to how emission map works in Unity?

**Comment by maxim-sheronov** [comment]
@reduz, I think the main benefit of multiplying is ability to change Color of emission using texture as mask. 
And without multiplying you just can not colorize your emission by script. I think @Zireael07 and @fracteed was talking about that case.

And other engines works this way.
@tagcup, Unity works like in this PR, they uses multiplication.

**Comment by maxim-sheronov** [comment]
@Zireael07 yes, but to have control on light color of that emission you need multiplication of emission texture and emission color

**Comment by tagcup** [comment]
Then this would also mean that's how it works with Substance, right?

**Comment by reduz** [comment]
I'm still not convinced that it's more intuitive, I would probably just add an option to select the behavior..

**Comment by tagcup** [comment]
I'm not exactly sure how this works with Unity or Substance (is there an official doc about it?), but based on [this discussion](https://github.com/KhronosGroup/glTF/issues/947), the current behavior in Godot apparently matches Khronos shader in their gltf exporter repo.

**Comment by tagcup** [comment]
The current Godot implementation is also the one that physically makes more sense: in the absence of emission you should only get albedo (which is the reflected environmental light), and when you turn on an additional light source (which is the emission) it should just add to albedo.(electromagnetic waves add without interacting, neglecting quantum mechanical effects for bosons. also in reality, when you turn on the light source it will heat the object up changing transport properties a little such that the albedo will be slightly different but shouldn't be much.)

**Comment by fracteed** [comment]
@reduz I would imagine that this is directly related to #10534

**Comment by maxim-sheronov** [comment]
@reduz, I really don't know in what case it is convinient to have sum of emission color and texture. Maybe you can give an example of such use case? If it can be helpful in some situation, maybe to have an option is better idea. Because with current implementation it is impossible to do coloring of emission with mask.

@tagcup About Unity you can see [here](https://docs.unity3d.com/Manual/StandardShaderMaterialParameterEmission.html)
You can see on screenshots, that when they use texture, they set color to white, because of multiplying.

**Comment by tagcup** [comment]
I don't know whick picture you're referring to exactly but this one (from that page) is mostly black:

https://docs.unity3d.com/uploads/Main/StandardShaderEmissiveMaterialInspector.png

**Comment by Zireael07** [comment]
@tagcup: That's because it's partially a mask. Now if I were to apply this same picture as emission texture in Godot, the whole mesh would be emissive right now in 3.0 (and properly masked in 2.1.3).

**Comment by reduz** [comment]
Given there are good reasons for both use cases, I will do the following
* Given how Godot exports the parameters, the current usage is more intuitive for creating materials, it allows setting a texture and making sure it works on the first try
* Also given there is a valid use case in changing the emission mask color, I will add this as an extra option in the material.

**Comment by tagcup** [comment]
@Zireael07 I must've misunderstood what Godot is currently doing then. So according to what you're saying, Godot is currently adding albedo as emissive color on top of the given emissive texture

**Comment by maxim-sheronov** [comment]
@tagcup, as @Zireael07 sad, result is almost black. But on the right side you can see almost black texture with small green and orange squares, and to the left you will see white color

@tagcup, in current implementation Godot use color from texture plus emission color (and maybe plus Albedo). So when you are using emission texture, you can left emission color black. But in Unity you must set it to white, or other color to do coloring.

@reduz, good to know, that there will be an option to select behavior. Thanks

**Comment by maxim-sheronov** [comment]
@reduz , I have just added flag to select to use multiplication or not. Could you see is it good enough option to accept?

**Comment by hpvb** [comment]
Can you please squash the clang-format commit? It doesn't make much sense for the public git history. Other than that, @reduz is the multiplication flag that was implemented after your comment a good fix, should this be merged in this form?

**Comment by Zireael07** [comment]
What are we doing with this? Still unable to mask my emissions as of alpha 2...

**Comment by HummusSamurai** [comment]
I think this will be merged eventually since it adds a flag for users to choose whether they want additive or multiplicative mode.

**Pull request closed without merging**
