### PR TITLE
Added force_raycast_update GDScript method for RayCast[2D]

### PR DESCRIPTION
**Pull request by WalasPrime**
I was wondering why a RayCast2D instance returned the same collision point when I tried to use it multiple times during a single fixed process frame. I wanted an enemy to try and look at multiple players in one frame, and pick the one to follow, but yeah... I'd have to make n raycasters for n players, which doesn't seem optimal. So I added a force_raycast_update() method to make sure the raycast result is "refreshed". This little change saves the need to manually talk to the servers. Took care of RayCast2D and RayCast.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
YEAH!

**Comment by reduz** [comment]
There is one problem about this, it will not work if you are using physics as threaded.
If you guys are fine understanding this, let's merge it (there seems to be conflicts so please give them a fix before).

**Comment by WalasPrime** [comment]
Fixed, rebased

@reduz could you give more detail on that? We can communicate with the physics servers inside of GDScript, does that mean there is no reliable way to raytrace in multithreaded applications? (or with servers at all)

**Comment by RandomShaper** [comment]
Would it be unreliable even in `_fixed_process()`? AFAIK, that method is the "sync point" with the physics engine so I think it shouldn't, but who knows.

**Comment by akien-mga** [comment]
Ping @reduz for more details about:

> There is one problem about this, it will not work if you are using physics as threaded.

Then @WalasPrime could likely add the relevant info to the docs for `force_raycast_update` and then we'll merge.

**Pull request merged**
