### PR TITLE
Improve the description of follow_viewport_enabled

### PR DESCRIPTION
**Pull request by KoBeWi**
See https://github.com/godotengine/godot-proposals/issues/5329

### CODE REVIEW

**Comment by ALBATI-2005** [comment]
This is a much better and clearer explanation. Awesome! 👍
I hope it gets approved.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
