### PR TITLE
[iOS] [3.2] iOS Plugins

### PR DESCRIPTION
**Pull request by naithar**
Same as #41230 but for `3.2` branch.

Implements https://github.com/godotengine/godot-proposals/issues/1185 for `3.2` branch.
[Godot iOS Plugin template](https://github.com/naithar/godot_ios_plugin)
*Since this plugin implementation directly uses Godot's source headers it's important to use correct compilation flags.*

<details>

<summary>
ARKit test
</summary>

</details>

### CODE REVIEW

**Comment by naithar** [comment]
MacOS build seems to be using `werror=yes`, while it should use `werror=no`

**Comment by akien-mga** [comment]
> MacOS build seems to be using `werror=yes`, while it should use `werror=no`

No, all platforms build with `werror=yes` on CI to prevent adding warnings.

**Comment by naithar** [comment]
> No, all platforms build with `werror=yes` on CI to prevent adding warnings.

Yeah, just rechecked `workflow` files - mistook `ios` configuration for macOS's =/

**Comment by naithar** [comment]
Fixed CI and made some changes to loading logic. Now ARKit is working correctly. 
I guess same changes should be done for `master` too.

**Comment by naithar** [comment]
```
E: Failed to fetch https://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages.gz  File has unexpected size (5006 != 5219). Mirror sync in progress? [IP: 142.250.115.128 443]
96
   Hashes of expected file:
97
    - Filesize:5219 [weak]
98
    - SHA256:aafcd0c50256a44ebb7cfe022d1b0077867adf70c3da267c4093e22fd6c1102a
99
    - SHA1:f7a7b01739afef5d9c9030fa15c8e5353c689989 [weak]
100
    - MD5Sum:58a637d912b15164b953cdff585de01f [weak]
101
   Release file created at: Tue, 20 Oct 2020 13:53:20 +0000
102
E: Some index files failed to download. They have been ignored, or old ones used instead.
103
Error: Process completed with exit code 100.
```

GitHub CI fails with this. Is it something on my side or CI is just going crazy again?

**Comment by akien-mga** [comment]
So the `master` version was just merged in #41230.

@naithar @bruvzg @BastiaanOlij How do you think we should proceed for the `3.2` branch? Should we merge this version as is now to test in 3.2.4 beta 2, or give the `master` version some more time to be fine-tuned before including the tested changes in the `3.2` branch?

**Comment by naithar** [comment]
I think making changes to `master`'s AppDelegate first and also migrating plugins to separate repo (with an option to build them for `3.2` branch) could be a way to go. Then we can merge everything into `3.2`.

**Comment by BastiaanOlij** [comment]
@akien-mga I'm not in a position to test atm but if this all seems to work I would merge and work out any kinks. I'll try and find some time in the weekend to see if my ARKit demos work properly with these changes.

**Comment by naithar** [comment]
I'm testing https://github.com/naithar/godot/tree/feature/pluggable_app_delegates and https://github.com/naithar/godot/tree/feature/pluggable_app_delegates_3.2 right now. It's probably the only functionality change left for plugins.
Only migrating modules to plugins in separate repo will be left after this.

**Comment by naithar** [comment]
#43557 and #43556 should allow to cover almost any platform specific case for iOS. I've tested push notifications, but it should be fine with anything that depends on extending `UIAppDelegate`.

**Comment by akien-mga** [comment]
@godotengine/ios Should we merge this and #43557 now for inclusion in 3.2.4 beta 6 in a few days?

What's the impact from those changes on current 3.2.x users (both game devs and plugin makers), especially in terms of compatibility?

**Comment by naithar** [comment]
This change should not affect compatibility. https://github.com/godotengine/godot/pull/42459 and https://github.com/godotengine/godot/pull/42582 are more serious in that respect. But everything seems to be easily fixable: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/issues/41. So it's more of an addition to current way of creating iOS specific code.

The only issue users might be encountering is access to GameCenter, iCloud and other iOS modules that was previously built into iOS platform code. They are temporarily moved to `modules` folder and would require some additional packaging as plugins until separate repo is done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by naithar** [comment]
@akien-mga since plugins have been merged and beta was released, should I start working on separating modules from plugins? 
I've noticed that iOS export template still contains `arkit` and `camera` libraries, should I also address this somehow?
Can I create a `godot-ios-plugins`/`godot-plugins-ios` repo for all plugins or what is the better way to approach this?

**Pull request merged**
