### PR TITLE
CI: Re-add `CHANGED_FILES` logic for pre-commit checks

### LINKED ISSUE #91831: [CI] Style checks are broken
### Tested versions

N/A

### System information

N/A

### Issue description

Code style checks are no longer being applied, see for example:
https://github.com/godotengine/godot/commit/82f5bd630c7b693d69e16e4a0f4ac530528a230f

Seems to be a regression from:
* https://github.com/godotengine/godot/pull/91597

All checks are now marked as `skipped` and claims there are no files to check

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
- Follow-up to #91597.
- Fixes #91831.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
Based on that some checks now show "passed" instead of "skipped" this seems to be working correctly

**Review by Repiteo — APPROVED** [review]

**Comment by Repiteo** [comment]
I'm curious if explicitly passing files overrides certain include/exclude logic; probably not a concern, but it's unfortunate that pre-commit doesn't have an automatic system for this

**Comment by AThousandShips** [comment]
It has an automatic system, it just doesn't work for existing commits, and doesn't seem to support listing a relative reference etc.

**Comment by akien-mga** [comment]
> I'm curious if explicitly passing files overrides certain include/exclude logic

Seems fine:
```
$ git diff --staged
diff --git a/thirdparty/mbedtls/library/aes.c b/thirdparty/mbedtls/library/aes.c
index b1a5c3ed10..2fea85495c 100644
--- a/thirdparty/mbedtls/library/aes.c
+++ b/thirdparty/mbedtls/library/aes.c
@@ -4,6 +4,12 @@
  *  Copyright The Mbed TLS Contributors
  *  SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later
  */
+
+
+
+
+
+
 /*
  *  The AES block cipher was designed by Vincent Rijmen and Joan Daemen.
  *
$ pre-commit run --files thirdparty/mbedtls/library/aes.c
clang-format.........................................(no files to check)Skipped
black................................................(no files to check)Skipped
mypy.................................................(no files to check)Skipped
codespell............................................(no files to check)Skipped
eslint-engine........................................(no files to check)Skipped
eslint-libs..........................................(no files to check)Skipped
eslint-sw............................................(no files to check)Skipped
eslint-html..........................................(no files to check)Skipped
make-rst.............................................(no files to check)Skipped
doc-status...........................................(no files to check)Skipped
jsdoc................................................(no files to check)Skipped
copyright-headers....................................(no files to check)Skipped
header-guards........................................(no files to check)Skipped
file-format..........................................(no files to check)Skipped
dotnet-format........................................(no files to check)Skipped
```

**Pull request merged**
