### PR TITLE
 3.0 recompute_aabb on add_surface

### LINKED ISSUE #8446: Object bounding boxes are always zero
**Operating system or device - Godot version:** v3 master, Linux

**Issue description:**
I've been wondering why performance seems to be affected when I hide objects which are already outside the screen and eventually found out that the bounding boxes are not being calculated and/or used correctly.
get_aabb() always returns a rect with all zeros too.

### PR DESCRIPTION
**Pull request by RameshRavone**
fixes #8446

### CODE REVIEW

**Comment by akien-mga** [comment]
Note that you don't need to put "3.0" in the commit log, the commit being in the master branch is enough information about the version it affects :)

**Comment by reduz** [comment]
I think this is unnecesary and likely needs to be reverted. Recomputing the
aabb is costly there land will affect load times. It also does not solve
the problem it intend to fix.

Also, please dont merge rendering related prs before I can take a look at
them

**Comment by reduz** [comment]
Yes, just checked, all this PR will do is severely affect load times,
please revert it

**Comment by reduz** [comment]
Let me try to explain the problem better (cellphone typing sucks). There
are two ways to add data to a mesh (both in Mesh and VisualServer) in 3.0.

One is giving an array of arrays, which is userfriendly but inefficient.
This generates aabbs automatically.

 The other is providing a pooled array, which is low level and only
intended to be used for serialization. Does no generation of anything for
performance.

If I'm not mistaken, the mesh aabb should be saved, or pregenerated from
the aabbs of each surface, but never generated when supplying low level
data.

Unfortunately I'm away from computers for two more weeks, so can't check
much :(

**Pull request merged**
