### PR TITLE
Add Feature to customize the minimap

### PR DESCRIPTION
**Pull request by Lu-TheCoder**
# Minimap (line spacing and line scaling) Feature
Added feature that allows us to edit the line spacing and line scale of the Minimap.

Screenshot 2024-05-01 at 05 25 56

https://github.com/godotengine/godot/assets/90724319/1ce6e157-3928-4a62-9389-f0d63ac69604

## Why?

The current minimap in Godot is tiny and small.. This PR increased the default size and allows for customization to look more visually appealing.

### CODE REVIEW

**Comment by Naros** [comment]
Hi, please squash your commits and use a commit message that resembles your PR title.

**Comment by Lu-TheCoder** [comment]
> Hi, please squash your commits and use a commit message that resembles your PR title.

Hi is it better now?

**Comment by Lu-TheCoder** [comment]
> Great!, but the commits need to be squashed (always).

Thank you.. I am trying to squash them but it says there's a merge amongst the commits.. so now I don't know how to squash them or remove the merge between the commits..

**Comment by Chaosus** [comment]
> Thank you.. I am trying to squash them but it says there's a merge amongst the commits.. so now I don't know how to squash them or remove the merge between the commits..

I recommend using a GUI-based git client to do it (GitKraken for example) - where you can easily select multiple commits, click the squash button in context menu and force-push it to the remote repo.

**Comment by Chaosus** [comment]
If you stuck completely - you can close this PR and recreate it (nothing bad in it, this is common problem across newcomers).

**Comment by Lu-TheCoder** [comment]
> If you stuck completely - you can close this PR and recreate it (nothing bad in it, this is common problem across newcomers).

Alright I think I'll close it an create a new PR then.. since I'm struggling :)

**Comment by Lu-TheCoder** [comment]
Closing and reopening a new one.. (having problems fixing Squash Issues)...

**Pull request closed without merging**
