### PR TITLE
Better edit rect margins for polygons in canvas editor.

### PR DESCRIPTION
**Pull request by ghost**
In master, when editing 2d polygons in the canvas editor, the outer handles for changing size and position are very near the polygon vertex handles, which makes it hard to tell which are which (e.g. see top right corner):

now1

There used to be a fixed margin added in `Polygon2D::_edit_get_rect`, probably to avoid this, which I remember removing at some point. The problem with that fixed margin size in `Polygon2D::_edit_get_rect` was and is that it will only fix the problem for certain zoom levels. In the following pictures, the first zoom level is OK, but the second is not:

bad1
bad2

With the fix in this PR, the margins are calculated inside `CanvasItemEditor` based on the correct zoom transform and the actual selection handle size, so that the distance will be correct on all zoom levels:

fix1
fix2
fix3

I added a new `CanvasItem::_edit_needs_rect_margin` to make a canvas item tell the editor if it wants its rect expanded like this (currently only activated for `Polygon2D`), as `Polygon2D` is a border case and other canvas items do not want this kind of margin expansion.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @groud

**Comment by groud** [comment]
Honestly I'm not sure this is a good idea, it make the snapping area hard to understand and the meaning of the rect more confuse. 
If this is really a problem, I would instead make the rect disappear when you edit the polygon, maybe by providing an "edition mode" when double clicking on the polygon or something like that.

**Comment by groud** [comment]
Maybe we could also change the polygon handle icon for something less confusing when close to the resize one, such as a diamond maybe ?

**Comment by poke1024** [comment]
I like the idea of a double click mode, that will hide the rect and show the polygon vertices.

**Comment by groud** [comment]
Thinking about it as I am reworking the way the rect in handled. It might be worth removing the rect completely in fact, which should be done easily when my rework gets merged.
It might need a better edition tool to select multiple vertices or something like that, but for now as it scale the rect it's not really useful.

**Comment by groud** [comment]
I think we can close this PR, since it seems that we agreed that a "vertice edit mode" would be better for the Polygon Editor (see #17193).

**Pull request closed without merging**
