### PR TITLE
[3.x] Document that `Area` only works with box shapes

### PR DESCRIPTION
**Pull request by CristianoSimao**
I lost various hours to discover that Area only detect body_entered if the collision shape is of type BOX.

### CODE REVIEW

**Comment by Calinou** [comment]
Is this actually the case? I don't remember seeing this restriction. This would also explain https://github.com/godotengine/godot/issues/64588.

**Comment by Calinou** [comment]
You can't just change the base branch of the pull request, as commits won't match. You have to create a new pull request based on `master`.

**Comment by YeldhamDev** [comment]
If this is actually the case, a node warning would be good as well.

**Comment by YuriSizov** [comment]
As mentioned, please open a new PR against the master branch. If this note is indeed correct, this existing PR can be used to update the docs for `3.x`. But we can also close it if you want.

**Comment by CristianoSimao** [comment]
I created other request in master.
I not have experience in GitHub but I hope I have place in the right place now.
You can close here if all is ok.
Thanks.

**Pull request closed without merging**
