### PR TITLE
Add EditorInterface.get_selected_paths()

### PR DESCRIPTION
**Pull request by EspeuteClement**
Exposes the selected paths in the editor filesystem dock.
Implements this proposal : https://github.com/godotengine/godot-proposals/issues/2424

### CODE REVIEW

**Comment by KoBeWi** [comment]
Not sure if having both `get_selected_path()` and `get_selected_paths()` is a good idea. The former should either be renamed or removed.

btw `get_selected_paths()` can be `const`.

**Comment by dallonf** [comment]
I need something like this for a plugin I've been working on. A `selected_paths_changed` signal would also be very helpful. @EspeuteClement do you need help with this PR?

**Comment by EspeuteClement** [comment]
> Not sure if having both `get_selected_path()` and `get_selected_paths()` is a good idea. The former should either be renamed or removed.
I don't know how the Godot team want to handle the removal/deprecation of existing function in the API. Removing this function could break some projects that rely on it

> btw `get_selected_paths()` can be `const`.

I could try to add that yes

**Comment by YuriSizov** [comment]
> I don't know how the Godot team want to handle the removal/deprecation of existing function in the API. Removing this function could break some projects that rely on it

Before 4.0 beta is released, we can break compatibility. That said, `get_selected_path` is a bad name for the existing function.

`get_current_path` returns the selected path, as is.
`get_selected_path` returns the base directory for the selected path, if it's a file, or the selected path as is, if it's a directory.

I'd rename it to, say, `get_current_folder` or `get_current_directory`. Then the new method's name is not a problem at all.

**Comment by EspeuteClement** [comment]
I can try to update this PR, but now that the godot 4 beta is released, I don't know if the suggested breaking changes can be implemented.

**Comment by akien-mga** [comment]
We can still do some compat breaking changes on a case by case basis, if approved by maintainers.

In this case I think introducing `get_selected_paths` next to `get_selected_path` creates a documentation / readability problem, so changing the name of `get_selected_path` makes sense to me if it's not clear enough.

**Comment by EspeuteClement** [comment]
I have renamed get_selected_path to get_selected_directory, and I've changed get_selected_paths to be const. I've also updated the doc to match the changes.

Here is a small project to test the changes (it contains a small addon that add a "Print Selected Files" in the Project -> Tools menu)

image

[TestEditor.zip](https://github.com/godotengine/godot/files/10005903/TestEditor.zip)

**Comment by YuriSizov** [comment]
I still think it should be `current`, not `selected for the renamed method. It's a companion of `get_current_path`, so it makes sense to have it called `get_current_directory`.

**Comment by EspeuteClement** [comment]
Okay that makes sence, I'll make the edit. Where can I find the project convertor map of renames ? I'll add that too.

**Comment by YuriSizov** [comment]
> Where can I find the project convertor map of renames ?

It's in `/editor/project_converter_3_to_4.cpp`.

**Comment by EspeuteClement** [comment]
Okey, everything should be in order now !

**Comment by akien-mga** [comment]
You need to run `--doctool` (or manually swap the two `member`s in the XML) to keep alphabetical ordering: https://github.com/godotengine/godot/actions/runs/3464728865/jobs/5786615082

Then please also squash the commits, and this should be good to go. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by EspeuteClement** [comment]
I fixed the doc and squashed the commits.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by neikeq** [comment]
Since we have `EditorPlugin.get_file_system_dock` (which didn't exist when #14882 was introduced), those methods should be in `FileSystemDock` instead now.

**Comment by YuriSizov** [comment]
> Since we have `EditorPlugin.get_file_system_dock` (which didn't exist when #14882 was introduced), those methods should be in `FileSystemDock` instead now.

That's probably true, but we need to do a clean-up in general. EditorPlugin and EditorInterface have a lot of general purpose stuff without much rationale for that. Since we already have plans to refactor EditorNode in 4.1, we can look into this then. (Yep, this would require either breaking compat or leaving aliases for the new methods in EditorInterface anyway)

**Pull request merged**
