### PR TITLE
abstract Display functionality (step one for wayland) RENAME x11 -> linux

### PR DESCRIPTION
**Pull request by toger5**
This time keep the OS class as it is. Just make `OS_X11` inherit from `OS_Linux`, so that there can be `OS_Wayland` inheriting from `OS_Linux` as well.

**also I renamed most of x11 to linux** (including `scons p=linux`)

### CODE REVIEW

**Comment by lupoDharkael** [comment]
Are you sure this is a good name? what about FreeBSD and others of the BSD family?

**Comment by YeldhamDev** [comment]
What about `linux-bsd`?

**Comment by NathanWarden** [comment]
Is it possible to use linux and bsd as aliases of each other? So, `scons p=linux` and `scons p=bsd` would actually run the exact same build code.

**Comment by NathanWarden** [comment]
Something like `freedesktop` as @lupoDharkael mentioned does seem to be the best way to keep it simple though if we're going to change it :)

**Comment by toger5** [comment]
> Is it possible to use linux and bsd as aliases of each other? So, `scons p=linux` and `scons p=bsd` would actually run the exact same build code.

that is actually a really good idea.

**Comment by toger5** [comment]
Other than the naming convention. Does anyone has concerns about this implementation?

**Comment by toger5** [comment]
also there are a bunch of unused private fields that i need to fix. so travis is okay with it ;)

**Comment by akien-mga** [comment]
> Something like freedesktop as @lupoDharkael mentioned does seem to be the best way to keep it simple though if we're going to change it :)

The design we discussed months ago with @hpvb and @reduz was indeed to use `freedesktop` which is the common denominator between GNU/Linux and *BSDs. Then yeah there could be aliases for SCons to do `p=linux` if wanted (I'm all for it), but that doesn't change the actual name of the platform.

@hpvb had a pretty well thought-out design (started in #16744 but then we discussed it further and changes were pending), but it's been intentionally left out for 3.2 as it's too late for such a compat breaking change.

**Comment by toger5** [comment]
yea renaming wouldnt be an issue.

I still would love to hear what made the DisplayDriver approach necassary.
basically there are two pr's in existance atm: this one, and #23209.
I worked closely with wmww (the guy who implmented #23209) and we came to the conclusion it is overkill.

@hpvb if you are around definitly contact me on matrix to discuss.
@akien-mga are there any specific flaws with this simpler approach?

**Comment by aaronfranke** [comment]
"freedesktop" is a bit of a weird name to me. There are non-Linux non-BSD free and open-source desktop operating systems out there. Haiku, ReactOS, FreeDOS, OpenSolaris, are a few. There are also Android forks which run on desktop computers made with FOSS software and won't run software designed for Ubuntu and might also not run software designed for Android.

I would suggest "linuxbsd" as it's descriptive of what it actually is - a compile option for Linux and BSD. Support for non-Linux non-BSD platforms shouldn't be implied. Plus, this name is [already used for the tag on GitHub](https://github.com/godotengine/godot/labels/platform%3Alinuxbsd).

**Comment by akien-mga** [comment]
@aaronfranke `freedesktop` is not about the free-ness of the desktop, it's the name of the project to which X11 and Wayland are affiliated: https://en.wikipedia.org/wiki/Freedesktop.org

**Comment by aaronfranke** [comment]
In that case:

* There is also the matter of server distros of Linux and BSD, which can be CLI-only. And if the goal is to change `p=server` to `server=yes` then it would be ironic calling it "freedesktop" if it does not use any components of the free desktop project.

* You can run X11 on MacOS and other non-Linux non-BSD platforms. And maybe Wayland someday too. But Godot compiled for "x11" today won't run on MacOS.

**Comment by toger5** [comment]
@hpvb have u already had time to work on your approach of the seperation?

**Comment by ddevault** [comment]
How about calling this unix?

**Comment by ddevault** [comment]
I'm a little bit more educated on the naming issue now, let me share a more informed opinion.

Summary of the naming problem: X11 and Wayland runs on more than just Linux, including BSD, Solaris, Minix, etc.

Summary of solutions:

1. Alias "bsd" et al to "linux". Problems: it's not actually Linux
2. Call it "freedesktop", as they're the organization behind xorg-server and Wayland. Problem: they aren't the ones who made X11, less than a hundred people even know what "freedesktop" is
3. (my proposal) Call it generic-unix (`OS_GenericUnix`), to contrast with the more specialized unices which derive from `OS_Unix` (e.g. Android, macOS)

**Comment by akien-mga** [comment]
Superseded by #37317, but thanks for the contribution nevertheless!

**Pull request closed without merging**
