### PR TITLE
miniupnpc: Sync with upstream master (4436632)

### PR DESCRIPTION
**Pull request by CodeforEvolution**
This is primarily for building the Haiku port

### CODE REVIEW

**Comment by akien-mga** [comment]
I know you're working from the 3.2 branch as advised, but PRs should be made on the master branch. Our workflow is to cherry pick from master to stable, not the other way around.

**Comment by CodeforEvolution** [comment]
I see, will do in a bit!

**Comment by akien-mga** [comment]
Ping ;)

**Comment by CodeforEvolution** [comment]
Sorry for the delay! I have been under a heavy workload this week. I should be able to get this done this weekend. :)

**Comment by CodeforEvolution** [comment]
Well, this rebase is not going so well...I'm going to open a new pull request.

**Pull request closed without merging**
