### PR TITLE
Make core/ includes absolute, remove subfolders from include path

### PR DESCRIPTION
**Pull request by akien-mga**
This allows more consistency in the manner we include core headers,
where previously there would be a mix of absolute, relative and
include path-dependent includes.

It also prevents confusion where some of our headers might have the same name as system headers, and can cause issues both with our own code and with thirdparty code.

More complete take on @karroffel's #10545 :)

### CODE REVIEW

**Comment by Faless** [comment]
:crying_cat_face:  this kills my PR.
Well, no problem, I'll just rebase in case :tongue:

**Comment by LikeLakers2** [comment]
I'm noticing some `core/` files, when they include their `.h` counterpart, use the absolute filename (i.e. [core/io/multiplayer_api.cpp](https://github.com/akien-mga/godot/blob/include-core-absolute/core/io/multiplayer_api.cpp#L31)) while others use a relative filename (i.e. [core/io/ip_address.cpp](https://github.com/akien-mga/godot/blob/include-core-absolute/core/io/ip_address.cpp#L31)). Maybe double-check and make all of those consistent too?

**Comment by akien-mga** [comment]
> I'm noticing some core/ files, when they include their header counterpart, use the absolute filename (i.e. core/io/multiplayer_api.cpp) while others use a relative filename (i.e. core/io/ip_address.cpp). Maybe double-check and make all of those consistent too?

Good point, I hadn't noticed that one. All .cpp files should include their header counterpart as a relative filename.

**Comment by LikeLakers2** [comment]
Wonder how many PRs will need to be rebased... heh.

Anyways, I took a quick look at any files you hadn't changed, and found a couple more includes for you to fix up:

* `core/compressed_translation.h` (`translation.h` -> `core/translation.h`)
* `core/variant_construct_string.cpp` (`variant.h` -> `core/variant.h`)

**Comment by akien-mga** [comment]
> - core/compressed_translation.h (#include translation.h -> #include core/translation.h)

Thanks, fixed. I should have used a better regexp :/

> - core/variant_construct_string.cpp (#include variant.h -> #include core/variant.h)

This one is actually intentional, as `variant.cpp`, `variant_call.cpp`, `variant_op.cpp` and `variant_construct_string.cpp` all implement the things defined in `variant.h`.

Rebased to fix merge conflicts after #21990.

**Pull request merged**
