### PR TITLE
Exposes capture methods to AudioServer + documentation

### PR DESCRIPTION
**Pull request by SaracenOne**
This PR exposes the AudioDriver capture methods to the AudioServer and scripting system so they can be manually manipulated. I require this for a GDNative plugin I'm working on. It also renames some of the methods and variables for consistency, changes Vector class to a PoolVector so it can be exposed to the scripting API, and adds some missing documentation.

### CODE REVIEW

**Comment by StraToN** [comment]
Out of curiosity (but maybe useful for documentation): is audio recording a blocking task? If so, if maybe interesting to indicate this in the docs and propose to setup a thread use in this specific case. 

Also I guess a demo will be interesting to make after this PR is merged.

**Comment by SaracenOne** [comment]
I should be able to provide a demo showing this off soon, yes (https://github.com/SaracenOne/godot_speech). I just need to provide a demo and provide a compiled version. As for blocking, everything done regarding recording is done via a thread spun up in the audio driver, and the callbacks are likewise done in this thread too.

**Comment by StraToN** [comment]
@SaracenOne Alright then, thanks for the precisions. In this case, documentation part is ok for me.

**Review by StraToN — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
This should be reverted, not only having a signal emit in the audio thread is unsafe (Connecting is not thread safe), but some of what happens in there may allocate memory, which is forbidden in the audio thread and should never be done.

**Comment by akien-mga** [comment]
Reverted via #35359.

**Pull request merged**
