### PR TITLE
Fix mono module build errors for release templates

### LINKED ISSUE #30526: Missing methods when building mono release exports
**Godot version:**
master 7a46726

**OS/device including version:**
windows 10 (1803)
mono 5.20.1.19
visual studio 2019 16.1.6 (16.1.29102.190)
msbuild 16.1.76+g14b0a930a7

**Issue description:**
When I build the mono release export for windows with this sequence:

    call scons.bat -j 8 platform=windows tools=yes module_mono_enabled=yes mono_glue=no 
    bin\godot.windows.tools.64.mono.exe --generate-mono-glue modules/mono/glue
    call scons.bat -j 8 platform=windows tools=no module_mono_enabled=yes mono_glue=yes copy_mono_root=yes target=release

The final command fails with these messages:

    modules\mono\class_db_api_json.cpp(86): error C2039: 'get_argument_type': is not a member of 'MethodBind'
    D:\Projects\godot\godot\core/method_bind.h(211): note: see declaration of 'MethodBind'
    modules\mono\class_db_api_json.cpp(94): error C2039: 'get_argument_info': is not a member of 'MethodBind'
    D:\Projects\godot\godot\core/method_bind.h(211): note: see declaration of 'MethodBind'
    [ 37%] Compiling ==> modules\mono\mono_gc_handle.cpp
    scons: *** [modules\mono\class_db_api_json.windows.opt.64.obj] Error 2
    mono_gc_handle.cpp
    scons: building terminated because of errors.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #30526

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
```
g++-9 -o bin/godot.x11.tools.64.mono -rdynamic -pipe -no-pie -rdynamic platform/x11/godot_x11.x11.tools.64.o platform/x11/context_gl_x11.x11.tools.64.o platform/x11/crash_handler_x11.x11.tools.64.o platform/x11/os_x11.x11.tools.64.o platform/x11/key_mapping_x11.x11.tools.64.o platform/x11/joypad_linux.x11.tools.64.o platform/x11/power_x11.x11.tools.64.o platform/x11/detect_prime.x11.tools.64.o -L/usr/lib main/libmain.x11.tools.64.a main/tests/libtests.x11.tools.64.a modules/libmodules.x11.tools.64.a platform/libplatform.x11.tools.64.a drivers/libdrivers.x11.tools.64.a editor/libeditor.x11.tools.64.a scene/libscene.x11.tools.64.a servers/libservers.x11.tools.64.a core/libcore.x11.tools.64.a modules/freetype/libfreetype_builtin.x11.tools.64.a -lXcursor -lXinerama -lXrandr -lXrender -lX11 -lXi -lasound -lGL -lmonosgen-2.0 -lm -lrt -ldl -lpthread
modules/libmodules.x11.tools.64.a(csharp_script.x11.tools.64.o): In function `CSharpLanguage::init()':
/home/travis/build/godotengine/godot/modules/mono/csharp_script.cpp:107: undefined reference to `class_db_api_to_json(String const&, ClassDB::APIType)'
/home/travis/build/godotengine/godot/modules/mono/csharp_script.cpp:109: undefined reference to `class_db_api_to_json(String const&, ClassDB::APIType)'
```

**Comment by neikeq** [comment]
We should consider moving the `DEBUG_METHODS_ENABLED` definition to the compiler command line options, instead of defining it in `core/method_bind.h`.

**Comment by Anutrix** [comment]
Shouldn't the ifdef be outside the if block?

**Comment by neikeq** [comment]
If you mean outside the `if (!try_load_api_assemblies) {` block, then no, it should be inside.

**Pull request merged**
