### PR TITLE
Fix unable to change directory in user access mode for 3.x

### PR DESCRIPTION
**Pull request by keptsecret**
Fix for #59828  
Uses the solution from #58772

### CODE REVIEW

**Comment by akien-mga** [comment]
I know we already merged the same fix in `master`, but I think we should also make sure that we understand where the regression stems from. Both for `master` and 3.5 this was reported as a regression so we should be able to find which PR caused the behavior change and was backported to `3.x`, and whether this fix is the proper follow-up or if something else should be done.

**Comment by keptsecret** [comment]
On `master` I believe it was the introduction of OS specific stuff (for Windows) that meant the directories FileDialog was in and what the game was actually in were different. I haven't looked too closely into the `3.x` branch yet though.

**Comment by akien-mga** [comment]
Oh I see, so that might be a consequence of #56012 (4.0) and #55987 (3.x).

CC @bruvzg for additional context on your review of #58772.

**Comment by bruvzg** [comment]
> Oh I see, so that might be a consequence of https://github.com/godotengine/godot/pull/56012 (4.0) and https://github.com/godotengine/godot/pull/55987 (3.x).

I guess it can affect the current working directory of the editor process on Windows, but `--path` should reset in on the start, and it should only affect `res://` in this case. Also, #59828 is reported on Linux, so I'm not sure if it might cause it.

**Comment by bruvzg** [comment]
It's possible it was always broken, but editor was overwriting file dialog settings with some valid (on the developer machine, it's not necessery valid for the end user) value before #54399, so it was not noticed.

**Review by bruvzg — APPROVED** [review]
Fix should be valid, regardless of the case of the issue, CWD is not appropriate default path for USER or RESOURCE file systems.

**Comment by akien-mga** [comment]
Sounds great, thanks for looking into it.

**Comment by akien-mga** [comment]
Thanks!

**Comment by keptsecret** [comment]
Ah, it might be a different problem on Linux then because I'm working on Windows and I found that `get_user_data_dir()` from https://github.com/godotengine/godot/blob/20e4fa2ccc4b76bc07a7d2e10f11375e781e3c47/core/os/dir_access.cpp#L38-L47
was returning a value (somewhere in %appdata%) that led to preventing changing of directories (coming from `os_windows.cpp` instead of `os.cpp`). It seems to be the same bits on both `master` and `3.x`. And in both, it does return CWD on Linux, so I guess the fix remains valid.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.5.

**Pull request merged**
