### PR TITLE
Fix Linux `move_to_trash` wrongly reporting files as not found

### LINKED ISSUE #67157: OS.move_to_trash() gives wrong error message for non-existent file.
### Godot version

4.0 beta 2

### System information

Linux Mint 20.3, i7 9th Gen, NVIDIA GeForce GTX 1650, Vulkan

### Issue description

I am using `OS.move_to_trash("abcd.txt")` in a script. The file abcd.txt does not exist. We expect an error like "File not found" or "File does not exist". Instead the error message displayed is `_ready: Can't rename file "abcd.txt" to "/abcd.txt"`.

### Steps to reproduce

Use the following _ready function in a GDScript file and let it run. 
```
func _ready():
	OS.move_to_trash("abcd.txt") 
```
If the file abcd.txt exists, then the code will work as expected. 
If the file abcd.txt does not exist, then this error will appear `_ready: Can't rename file "abcd.txt" to "/abcd.txt"`.

### Minimal reproduction project

[WrongErrorMsg.zip](https://github.com/godotengine/godot/files/9741967/WrongErrorMsg.zip)

*Bugsquad edit (keywords for easier searching): move_to_trash*

### LINKED ISSUE #79108: Unable to delete files when project is on non-`/home` drive / mount point without pre-existing `.Trash` folder
### Godot version

v4.1.stable.official [970459615]  < Steam

### System information

Godot v4.1.stable - Debian GNU/Linux trixie/sid trixie - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1060 (nvidia) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

On this machine, I have my projects stored on a separate drive to my system and home directory. This drive is mounted at `/data`.

Since 4.1, if I attempt to delete a project file through the in-editor file browser, I get an error dialog (though the window opens much larger than this screenshot):

Screenshot_20230706_161340

The editor output console shows the (misleading) error:

>   platform/linuxbsd/os_linuxbsd.cpp:968 - move_to_trash: No such file or directory as /data/src/godot/default/new_script.gd.

However, if Godot is run from the command-line, we also get the following additional information prior to that error output:

> gio: file:///data/src/godot/default/new_script.gd: Unable to find or create wastebasket directory /data/.Trash-1000 to move /data/src/godot/default/new_script.gd to

Indeed, the root of the `/data` mount point is not writeable by regular users, and there's no trash directory in there already.

Prior to 4.1, it appears that deleted files would be moved into my home dir's trash, across filesystems, since my `~/.local/share/Trash` is seemingly full of stuff I have previously deleted from my current project.

### Steps to reproduce

1. Use Linux
2. Create or open a project on a secondary drive (one which doesn't also contain your home dir).
3. Open the project in the Godot editor
4. Delete a file (eg. `icon.svg`) from the editor's FileSystem panel.
5. :eyes: :exclamation: 

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by akien-mga**
We can't rely on the error code from `gio` or `kioclient5`, in my rudimentary testing they return `1` for both missing files and other situations like not having a Trash can on the mounted volume.

~I added path existence checks to all platforms as that seemed useful, even if it was wrongly implemented for Linux.~
*Edit:* This would need more work, I left it out of this PR for now.

Fixes #79108.
Partially reverts #67158, but still fixes #67157.

CC @amoriqbal @romlok @starccy I only did basic tests on Linux, would appreciate you checking that it solves #79108.
You can test with CI artifacts once the build finishes.

### CODE REVIEW

**Comment by starccy** [comment]
Thank you for your work, I'll test it later.

**Comment by starccy** [comment]
I can confirm the error has disappeared on my system (Linux + Gnome).

**Comment by romlok** [comment]
The only Linux editor artifact I could see was the `-mono` version, which didn't work on my machine, but I was able to compile the branch locally and can confirm that this change fixes the issue for me too :+1:

**Review by YuriSizov — APPROVED** [review]
Approving based on the comments above.

**Comment by starccy** [comment]
Oops, I missed a special use case.    
When I create a broken symlink file, I cannot delete the file itself. And the "No such file or directory" error be presented.

if I get it correctly, the `DirAccess::file_exists` only checks the file it points to, but not for the symlink itself.
https://github.com/godotengine/godot/blob/ef155c1aeb216fa5a732913b6f2dc321e4b512dc/drivers/unix/dir_access_unix.cpp#L75

I was wondering why to use `stat` here instead of `lstat`, is this an expected behavior?

**Comment by akien-mga** [comment]
Thanks for testing further, that's indeed a regression compared to 4.0.3, where `move_to_trash` handles deleting symlinks fine on Linux.

Changing `stat` to `lstat` in DirAccessUnix could be considered but it's a very core change with a lot of implications, that would need to be assessed in depth.

For this PR I'll remove the check added in all platforms to handle missing files, and just let Linux behave like Windows and macOS: no validation.

**Comment by starccy** [comment]
Yes, the error messages from gio/kioclient5 are annoying, but thankfully the method still works as properly : )

> Changing stat to lstat in DirAccessUnix could be considered but it's a very core change with a lot of implications, that would need to be assessed in depth.

In fact, some languages like Python, have separate APIs to let users decide to choose the one they think is appropriate: `os.path.exist` and `os.path.lexists`, which can be imitated in gdscript to avoid breaking changes as much as possible. AFAIK, the gdscript users have no chance to determine if a file is a symlink. They might never or hard to check existence for a broken symbolic link.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.

**Pull request merged**
