### PR TITLE
Request mic access only when is needed

### LINKED ISSUE #23682: Microphone usage required on iOS and macOS, requires NSMicrophoneUsageDescription to be keyed in plist
Godot is attempting to access the microphone on the device when the project isn't in need of it. My setup is using MacOS High Sierra to run XCode 10.1 for iOS 12 support.

Issue tested using Godot 3.1 Alpha 2 (non mono version) with matching templates installed. I haven't tested elsewhere to see if it's a common problem on say Godot 3.0 or any mono builds yet. 

Steps are to Export a simple project to iOS and Run it live on the device from XCode. _Note you may need to add the StoreKit framework to the linker if you go through the Auto manage signing toggle loop of disabling IAP and Notifications from the Capabilities section in XCode to assign your provisioning profile._

When attempting to run Godot on Device in this case an iPhone 6, XCode will quickly report a crash as no value was set for NSMicrophoneUsageDescription was set in the PList.

`2018-11-12 22:45:28.546782-0500 YOUR-GAME [669:85574] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.`

_Note if you end up adding the key to your plist then push it to your device, removing the key again will not allow the error to persist (no privacy prompt). You will have to rename the bundle identifier (myapp2) to test microphone prompt on the same device again regardless of your answer. Even deleting the app from the device will not reset the test case history. Otherwise if you don't add the key to the plist you can test over and over._

More details may follow in the forums. 
https://godotdevelopers.org/forum/discussion/20217/bug-why-is-godot-3-1-ios-builds-requiring-the-microphone-permission-key-set-in-the-plist#latest

### PR DESCRIPTION
**Pull request by volzhs**
Fix #23682

edit : `Project Settings` > `Audio` > `Enable Audio Input` option is added. default is `false` (disabled)

### CODE REVIEW

**Comment by marcelofg55** [comment]
Some devices won't work with this, for example the Focusrite Scarlett 6i6. Not sure why but if you don't initialize the input at the start it won't work afterwards.

**Comment by marcelofg55** [comment]
I proposed one possible solution on this comment https://github.com/godotengine/godot/issues/23682#issuecomment-438304077
If we could implement a feature tag called `audio_input` and only enable the Microphone code if that tag is present the issue should be solved.

**Comment by volzhs** [comment]
what a about having a `Use audio input` option at Project settings > Audio?

**Comment by marcelofg55** [comment]
Sounds okay to me. Maybe `Enable Audio Input` might suit better for the name.
It should be disabled by default and maybe warn or automatically enable it if the user adds a AudioStreamMicrophone on the project.

**Comment by volzhs** [comment]
it seems to need to take care of all kind of audio driver (core, pulse, rt, wasapi, xaudio2) right?

**Comment by volzhs** [comment]
@marcelofg55 If I understand codes correctly, pulse and wasapi looks to initialize capturing device on demand.
would you take a look changes?

**Review by marcelofg55 — CHANGES_REQUESTED** [review]
It should be documented on the `ProjectSettings.xml`. And state that this needs to be enabled for audio input to work when using CoreAudio driver.

**Comment by volzhs** [comment]
updated

**Review by marcelofg55 — APPROVED** [review]
Looking good!

**Comment by volzhs** [comment]
@marcelofg55 thanks for the review. :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
