### PR TITLE
Add dot and cross product to Vector3i.

### LINKED ISSUE #71547: Missing functions on Vector{2,3,4} types
### Godot version

4.0beta11

### System information

n/a

### Issue description

This seems small enough that I don't have to report separate issues. I noticed that the following functions are missing (at least from the [latest docs](https://docs.godotengine.org/en/latest/) and from the `extension_api.json`):

- `Vector2::inverse()` (exists on `Vector3` and `Vector4`)
- `Vector4::limit_length()` (exists on `Vector2` and `Vector3`)
- `Vector4::move_toward()` (exists on `Vector2` and `Vector3`)
- `Vector{2,3,4}i::distance_squared_to()` (they have `length_squared()`, and `Vector{2,3,4}` do have `distance_squared_to()`)

Their absence is probably just an oversight, since they could all easily be implemented and could make sense in certain niche situations.

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by piwicode**
Added two missing functions.
More will come if it is considered useful.

fixes godotengine/godot#71547

### CODE REVIEW

**Comment by AThousandShips** [comment]
`dot` should be added to all the integer vectors if they're added to any IMO

**Comment by piwicode** [comment]
I propose to get feedback on `Vector3i` and if it looks good to the reviewer, I will add all missing bits, either on this PR or in a follow-up.
Appart for the comment above. Does the change look good?

**Comment by clayjohn** [comment]
See the comment on the original issue: https://github.com/godotengine/godot/issues/71547#issuecomment-1385719753

While this work is appreciated, we try not to add new things to core unless they are highly demanded by users. This is how we keep the engine lightweight and easy to maintain. Importantly, we avoid adding things "just because we can". 

So while logically it makes sense to have a dot product and cross product in Vector3i, it seems that users haven't really run into a need for it. There, in my opinion, it makes sense for us to wait until users express a need for these before we add them

**Comment by piwicode** [comment]
Sure, now worries.

I happen to use the dot product to convert integer coordinates to and array offset. I use `Vector3i` for coordinates in a voxel. For sure I could use `Vector3` as easily, but I use the type to differentiate voxel cell coordinates from local coordinates.

I get the point about aligning on actual user need.
Here I doubt anyone will need is so badly they will write a proposal.
It is easy to workaround by to `Vector3` and the back to `Vector3i`.
Maybe it means it is not useful, still it is one of those little surprising quirk that hurt the flow and you have to remember.

I would also be surprised that completing vector operation coverage bloats the engine. It this is the case, the problem may be elsewhere.

**Pull request closed without merging**
