### PR TITLE
Make ensure_correct_normals working on GLES2

### LINKED ISSUE #47536: Normal is wrong with scaled mesh (SpatialMaterial Ensure Correct Normals not implemented in GLES2)
**Godot version:**

3.3.rc b38a36923a

**OS/device including version:**

Kubuntu 20.10 / AMD RX570 / both GLES2 & GLES3

**Issue description:**

Normal goes wrong with scaled mesh.
Left - no scale, Center - 0.2 scaled on Y, Right - 5.0 scaled on Y
Screenshot_20210401_113341
it looks Normal of the center and the right one is swapped.
same result on both gles2 and 3.

**Steps to reproduce:**
[scale normal.zip](https://github.com/godotengine/godot/files/6240583/scale.normal.zip)

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by volzhs**
Fix #47536
image

### CODE REVIEW

**Comment by volzhs** [comment]
I found that **vertex lighting** with **ensure correct normals** makes unexpected light strength. :cry: 

GLES3

gles3


GLES2

gles2

have no clue...

**Comment by volzhs** [comment]
I think vertex lighting issue is another thing.
vertex lighting
I had pretty good result with ensure correct normals on gles2 without vertex lighting, even on mobile.

**Review by JFonS — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
