### PR TITLE
Fix invalid transform when skip_vertex_transform used

### PR DESCRIPTION
**Pull request by Chaosus**
Fixes https://github.com/godotengine/godot/issues/13010

### CODE REVIEW

**Comment by vnen** [comment]
Citing @reduz from IRC:

> I don t understand that one,  the point of using skip transform _is_ to skip the transform

**Comment by Chaosus** [comment]
looks like PROJECTION_MATRIX multiplication does not give same result on vertex than direct multiplication on projection_matrix in code, this PR enables the correct usage of code below... 
```

shader_type spatial;
render_mode skip_vertex_transform;

void vertex() {
         VERTEX = (MODELVIEW_MATRIX * vec4(VERTEX, 1.0)).xyz;
        //or:
	//VERTEX = (INV_CAMERA_MATRIX * WORLD_MATRIX * vec4(VERTEX, 1.0)).xyz;
}
```
but I still not sure, maybe @reduz knows where is problem better than me ?

**Comment by reduz** [comment]
ah i see, it makes sense it works this way

**Comment by reduz** [comment]
i would just remove the whole ifdef here and leave:

`gl_Position = projection_matrix * vec4(vertex_interp,1.0);`

since the other case makes no sense

**Comment by Chaosus** [comment]
Done !

**Pull request merged**
