### PR TITLE
[WIP, 3.x] Build and export iOS Mono libs as `.xcframework`s, for M1 iOS simulator support.

### PR DESCRIPTION
**Pull request by bruvzg**
Followup to #45480 for the Mono libs.

Export template build depends on https://github.com/godotengine/godot-mono-builds/pull/30, https://github.com/godotengine/build-containers/pull/68 and https://github.com/godotengine/godot-build-scripts/pull/16

### CODE REVIEW

**Comment by naithar** [comment]
`3.2.4 beta1` also doesn't seems to be working. On export editor gives `Mono AOT compiler exited with code: 134`.
`3.2.3` exports the same project without an issue.

**Comment by naithar** [comment]
This issue could be related: https://github.com/godotengine/godot/issues/42378. 
At least `Runtime critical type Mono.RuntimeStructs/MonoError not found` error seems to be the same.
Maybe mono version should be downgraded?

**Comment by akien-mga** [comment]
There's this issue which seems related: #43065.

I thought it was I was still using a pre-built AOT cross-compiler from Mono 6.10 even though the rest of Mono was 6.12, but as of 3.2.4 RC 1 both Mono and the pre-built AOT cross-compiler are from the same 6.12.0.114.

**Comment by naithar** [comment]
> There's this issue which seems related: #43065.

Yeah, that's the issue that gets fixed by manually linking the libraries.

`3.2.3` also misses a library if there is no `C#` script in Godot project, but when even an empty script is added everything works fine. 
Which Mono version was used for `3.2.3` release?

**Comment by akien-mga** [comment]
>  Which Mono version was used for `3.2.3` release?

6.6.0.166 I think. At least that's what the 3.2.3 RC 6 post mentions: https://godotengine.org/article/release-candidate-godot-3-2-3-rc-6

Then 3.2.4 beta moved to 6.12.x, which might indeed be part of the issue.

**Comment by naithar** [comment]
Tested `6.4.0` version. Same issue.

**Comment by naithar** [comment]
I've noticed that I'm also getting `It was not possible to find any installed .NET Core SDKs` warning. Installing `.NET Core` removed the warning, but still didn't fix the error. Reverting `mono` module to `3.2.3` stable version also didn't help - getting same `Runtime critical type Mono.RuntimeStructs/MonoError not found` error on export.

**Comment by naithar** [comment]
After Installing Xamarin export fails silently and doesn't give any error anymore.
There are also this error now:
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.HotReloadAssemblyWatcher.RestartTimer () [0x00000] in <d651d08a41ab4937bb48b0e2dc9dfd78>:0 
  at GodotTools.HotReloadAssemblyWatcher._Notification (System.Int32 what) [0x00008] in <d651d08a41ab4937bb48b0e2dc9dfd78>:0 
ERROR: debug_send_unhandled_exception_error: System.NullReferenceException: Object reference not set to an instance of an object
   At: modules/mono/mono_gd/gd_mono_utils.cpp:371.

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at GodotTools.HotReloadAssemblyWatcher.RestartTimer () [0x00000] in <d651d08a41ab4937bb48b0e2dc9dfd78>:0 
  at GodotTools.HotReloadAssemblyWatcher._Notification (System.Int32 what) [0x00008] in <d651d08a41ab4937bb48b0e2dc9dfd78>:0 
  at (wrapper managed-to-native) System.Threading.Monitor.Exit(object)
  at Godot.GodotTaskScheduler.ExecuteQueuedTasks () [0x00050] in <128686e36e4345c892524365e31d2d29>:0 
  at Godot.GodotTaskScheduler.Activate () [0x00001] in <128686e36e4345c892524365e31d2d29>:0 
  at (wrapper native-to-managed) Godot.GodotTaskScheduler.Activate(Godot.GodotTaskScheduler,System.Exception&)
```

**Comment by naithar** [comment]
Okay, so in the end it seems like installing Xamarin fixed the issue. Reverting `mono` module back to the current `3.2` state and recompiling seems to be fixing the error that popped during export.

But exported project is broken:
* XCFrameworks are embedded, while they shouldn't as they contain `.a` libraries
* Mono libraries are linked multiple times.
* `-force_load` doest seem to like `.xcframework` values. Also it seems like it should be `libmonosgen` that needs to be force loaded. So changing to `-force_load "$(SRCROOT)/libmonosgen-2.0.xcframework/ios-arm64/libmonosgen.a"` seems to be fixing this compilation problem. But I don't think that will work for simulators.
  Maybe using something like this would work:
  ``` 
  OTHER_LDFLAGS = (
	  "-rdynamic",
	  "-force_load",
	  "\"$(SRCROOT)/libmonosgen-2.0.xcframework/ios-arm64/libmonosgen.a\"",
  );
  "OTHER_LDFLAGS[sdk=iphoneos*]" = (
	  "-rdynamic",
	  "-force_load",
	  "\"$(SRCROOT)/libmonosgen-2.0.xcframework/ios-arm64/libmonosgen.a\"",
  );
  "OTHER_LDFLAGS[sdk=iphonesimulator*]" = (
	  "-rdynamic",
	  "-force_load",
	  "\"$(SRCROOT)/libmonosgen-2.0.xcframework/ios-arm64_x86_64-simulator/libmonosgen.a\"",
  );
  ```

**Comment by bruvzg** [comment]
Superseded by #49248

**Pull request closed without merging**
