### PR TITLE
[macOS] Fix file associations

### PR DESCRIPTION
**Pull request by bruvzg**
* Replaces deprecated OS X 10.4 style `CFBundleTypeExtensions` file type declaration with 10.5+ `UTExportedTypeDeclarations`.
* Adds declaration for project files (*.godot)
* Adds document icon for associated file types.

screenshot 2018-11-10 at 00 31 13

### CODE REVIEW

**Comment by samgreen** [comment]
Looks good to me, I'd love to see this merged.

**Comment by akien-mga** [comment]
Looks fine, but the new icon should not be in the root folder. `misc/dist` would be a better location.

**Comment by bruvzg** [comment]
> `misc/dist` would be a better location.

Done

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
