### PR TITLE
22586: Dragging file icon on to another file causes "Error Moving" in FileSystem dock

### PR DESCRIPTION
**Pull request by dualtagh**
Fix for https://github.com/godotengine/godot/issues/22586

Make drag and drop consistent for both FileSystem views

### CODE REVIEW

**Comment by groud** [comment]
No, that is not the right fix, this function is used in several other places where returning the file might be needed. The function name is misleading though, it should be `_get_drag_target()`

**Comment by dualtagh** [comment]
@groud Thanks for the feedback. Would this be more appropriate? The line I removed `to_dir = to_dir.ends_with("/") ? to_dir : (to_dir + "/");` is causing problems because it is treating a filename as a folder after appending the slash

**Comment by groud** [comment]
Well, the thing is that I would like to keep the drag&drop on another file, so that it move the file in the target file's folder when it happens.
I should give it a check, but the only thing to be done is probably to check if we drag the files in the same place as before or something like that.

**Comment by dualtagh** [comment]
I see. I was just trying to fix the issue described in the ticket so that both views behave consistently

**Comment by groud** [comment]
Ok my bad, after a code review the solution was indeed to modify `_get_drag_target_folder()`.
It is used in several places in the code but it is always for dragging operations.

The solution is to replace line 1956 by:
```
target = ltarget.ends_with("/") ? ltarget : path.get_base_dir();
```
(adding .get_base_dir() to path)

Sorry for the inconvenience.

**Comment by dualtagh** [comment]
@groud No problem, I will change that soon

**Comment by dualtagh** [comment]
@groud I get this dialog (after dragging a file onto another file) with the change you proposed:
image

Is that the desired functionality?

**Comment by groud** [comment]
> Is that the desired functionality?

Yeah, it makes sense. I don't know if it's the best UX but at least it fixes the error message.
This can be solved in another PR.

**Review by groud — APPROVED** [review]

**Comment by dualtagh** [comment]
@akien-mga Squashed and build is passing

**Comment by akien-mga** [comment]
Thanks!

**Comment by avencherus** [comment]
@dualtagh I ran into another drag & drop file manager issue the other day.  https://github.com/godotengine/godot/issues/22122

I came across this PR, and was wondering if it might be related in some way, or if you might know more about it.

Thanks.

**Pull request merged**
