### PR TITLE
Fix version check for GDExtension

### PR DESCRIPTION
**Pull request by AThousandShips**
The version check only checks individual entries, not lexicographical comparison, this would cause a plugin requiring at least "4.1.1" to fail if you are on "4.2.0"

(Not technically needed for 4.1 as the condition won't be true there)

Could alternatively be written as:
```cpp
if (VERSION_MAJOR != compatibility_minimum[0]) {
	compatible = VERSION_MAJOR > compatibility_minimum[0];
} else if (VERSION_MINOR != compatibility_minimum[1]) {
	compatible = VERSION_MINOR > compatibility_minimum[1];
} else {
	compatible = VERSION_PATCH >= compatibility_minimum[2];
}
```

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Seems fine.

Could use `VERSION_HEX` alternatively for a simple comparison: https://github.com/godotengine/godot/blob/7ba79d68bd0f97797d7cb37452da6a036ba7c7c9/core/version.h#L55

**Comment by Bromeon** [comment]
Also, for lexicographical comparison, `std::make_tuple(l0, l1, l2) < std::make_tuple(r0, r1, r2)` is usually a good trick.

In this case, the hex comparison seems simpler though.

**Comment by AThousandShips** [comment]
Oh I'd have used that if I were to use the standard library

**Comment by Sslaxx** [comment]
Fixes https://github.com/godotengine/godot/issues/80590?

**Comment by AThousandShips** [comment]
Don't think so, they are on 4.1.1 and the check won't fail for them

**Review by dsnopek — APPROVED** [review]
Thanks!

I think any of the variations discussed here would be fine, including the one currently used in the PR.

**Review by Gallilus — COMMENTED** [review]
Seems to make sense.
Only check sub_versions if you are on the relevant branch.
If we are in a newer major version it should be compatible.

Out of the scope of this bug fix but the only thing I can think of is that we are not supporting backporting compatibility.

I will mention that in Rocket Chat.

THANKS

**Comment by AThousandShips** [comment]
Switched check to match the one used in https://github.com/godotengine/godot-cpp/pull/1208

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
