### PR TITLE
GLES3: Remove unimplemented texture_create() declaration

### PR DESCRIPTION
**Pull request by Wuqiqi123**
Reopen this https://github.com/godotengine/godot/pull/78258#issuecomment-1594287018

### CODE REVIEW

**Comment by AThousandShips** [comment]
Why did you need to close the old one?

**Comment by Wuqiqi123** [comment]
> Why did you need to close the old one?

I reset my master to godot's, and the automatically closed.
Sorry for not reading the document before open the pr.

**Comment by AThousandShips** [comment]
Oh I'm sorry, didn't realize that could happen, thought since you linked to the comment

In the future make sure you use a dedicated branch for your changes

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
