### PR TITLE
macOS export: Fix validation of codesigning certificate password

### PR DESCRIPTION
**Pull request by j-mattsson**

### CODE REVIEW

**Comment by Mickeon** [comment]
Could you elaborate? What does this do? What does this fix?

**Comment by akien-mga** [comment]
The fix seems correct, but indeed the commit message and PR title should be made more explicit about what this does.
For example, "macOS export: Fix validation of codesigning certificate password".

**Comment by lawnjelly** [comment]
Also agree with @akien-mga this looks fine barring the commit message. If you no longer want to update this PR do let us know and we can sort out the fix. :+1:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
