### PR TITLE
Expose to_int64() to gdscript

### PR DESCRIPTION
**Pull request by volzhs**
```gdscript
var text = "123456789123456789"
prints("to_int :", text.to_int())
prints("to_int64 :", text.to_int64())
```

output

```
to_int : -1395630315
to_int64 : 123456789123456789
```

### CODE REVIEW

**Comment by reduz** [comment]
I think GDSCript should just use to_int64 by default, since it uses 64 bits integers and doubles., we should just change the function.

**Comment by volzhs** [comment]
how can gdscript's `to_int` points to `to_int64`?

**Comment by volzhs** [comment]
I found that `int()` returns int64. :)
```gdscript
var text = "123456789123456789"
printt(text.to_int())  # -1395630315
printt(int(text))      # 123456789123456789
```

**Comment by bojidar-bg** [comment]
> how can gdscript's `to_int` points to `to_int64`?

Just expand the `VCALL_LOCALMEM0R` macro manually:
https://github.com/godotengine/godot/blob/27a3557a75403ccd2b3f57541902d72edec3a4b5/core/variant_call.cpp#L212-L213
https://github.com/godotengine/godot/blob/27a3557a75403ccd2b3f57541902d72edec3a4b5/core/variant_call.cpp#L417-L423

**Comment by akien-mga** [comment]
So this still needs changes IIUC?

**Comment by volzhs** [comment]
yes. `to_int()` needs 64 bits.

**Comment by aaronfranke** [comment]
Closing as superseded by #38713. As @reduz said, GDScript should get the 64-bit version by default. We don't need the 32-bit versions at all for 4.0, but even if we did, this PR is still not good as-is.

**Pull request closed without merging**
