### PR TITLE
animation_started signal for AnimationPlayer

### PR DESCRIPTION
**Pull request by kubecz3k**
signal is called `animation_started` and have one parameter `name` of the animation that had just started

### CODE REVIEW

**Comment by slapin** [comment]
Does it work with blended animations?

**Comment by kubecz3k** [comment]
Yeah it should work with blended animations as well, the signal is emitted from the 'play' function which is the only one which is able to start an animation directly (blending is configured inside this function also).

**Comment by reduz** [comment]
I have just noted this, from the #10729 issue, by philosophy we never add signals that are emitted when a function is directly called, so I guess this should be reverted/removed

**Comment by kubecz3k** [comment]
What with the case when animation is played because of `next (auto queue)` in blend times dialog? 
Or when animation is started by external animation player (lets say someone who cant code is using additional animation player to steer animation playback of other animation players?)

**Pull request merged**
