### PR TITLE
Expose instance_from_id to GDNative

### LINKED ISSUE #28478: Implement & expose godot_is_instance_id_valid() to GDnative
**Godot version:** Godot 3.1, custom build from git 6697fd9a05859914fc320b4b4321fd9fb6170f71 (Apr 17th)

**OS/device including version:** Gentoo Linux 4.19.27, KDE Plasma 5, GTX 1080 w/NVidia proprietary drivers 418.43

**Issue description:**
When referencing another scene node in GDnative, currently the only safe way to do that is by `NodePath`.

That requires 1. a string path lookup in the scene tree followed by 2. a `cast_to` to the actual node type in order to obtain the node. This often needs to be repeated each physics and/or visual frame.

This could be greatly improved if we could check for the validity of an `instance_id` in GDnative. It's already possible to obtain the `instance_id`, so we could *cache* the looked-up and already-cast node pointer together with its instance id and just check whether it's still valid (for the price of one has table lookup instead).

```
/// <summary>Controls the behavior of an actor within the scene</summary>
public: void set_kinematic_body_node(godot::KinematicBody *kinematic_body) {
    this->kinematic_body = kinematic_body;
    if(kinematic_body != nullptr) {
        this->kinematic_body_instance_id = kinematic_body->get_instance_id();
    }
}

public: godot::KinematicBody *get_kinematic_body_node() const {
    if(this->kinematic_body != nullptr) {
        if(!godot::is_instance_id_valid(this->kinematic_body_instance_id) {
            this->kinematic_body = nullptr;
        }
    }

    return this->kinematic_body;
}
```

While I'm at it, I'd also suggest killing the `ObjectDB::instance_checks` hash table which is currently used by `ObjectDB::instance_validate()` to check the validity of a godot `Object *` - it's redundant because there's already the `instances` hash table and risky because a deleted `Object` can well be reported a valid once another `Object` is allocated to the same address.

Switching internal checks to use the instance id instead would avoid those issues.

### PR DESCRIPTION
**Pull request by ghost**
This function is available to GDScript but not to GDNative. When exposed, it allows building more ergonomic safe abstractions over the GDNative APIs, and covers the use cases of the original PR.

Close #28478. Supersedes #28791.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @godotengine/gdnative

**Comment by akien-mga** [comment]
Some comments from IRC:
```
12:13 <Akien> reduz: do you agree with adding an ID validity check method to object? Seems needed for GDNative: #34986
12:13 <IssueBot> #34986: Add is_instance_id_valid() method to allow GDNative ptr caching | https://git.io/JvvMk
12:29 <reduz> I think the function to get an object from an ID is kind of the same already
12:29 <reduz> it returns null if it fails
12:29 <reduz> so not quite sure if there is any point
12:33 <Akien> reduz: So you mean doing `Object::is_instance_valid(Object::get_instance_from_id(p_instance_id))` should be equivalent?
12:33 <Akien> Well that's GDScript names but you get the point :P
```

In GDScript, it would be:
```
	var node = Node.new()
	var instance_id = node.get_instance_id()
	print(is_instance_valid(instance_from_id(instance_id)))
```

Seems like what's missing is simply a GDNative binding for what GDScript has as `instance_from_id` (which likely uses `static Object *get_instance(ObjectID p_instance_id);`).

**Comment by toasteater** [comment]
Updated implementation to just exposing `instance_from_id`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by NicholasShatokhin** [comment]
How to use it method in my Node2D class?

I tried:

`godot_object* instanceInt = godot_instance_from_id(mousePointsToObject);
Object* instance = (instanceInt) ? (Object*)godot::nativescript_1_1_api->godot_nativescript_get_instance_binding_data(godot::_RegisterState::language_index, instanceInt) : nullptr;
`

But got an error:

`Error	LNK2019	unresolved external symbol godot_instance_from_id referenced in function "public: void __cdecl godot::PlayerController::_process(float)"`

**Pull request merged**
