### PR TITLE
Fix grammar in Marker2D.xml

### PR DESCRIPTION
**Pull request by ghost**
Changes "You can set cross' visual size..." to "You can set **the** cross' visual size..." on https://docs.godotengine.org/en/stable/classes/class_marker2d.html

### CODE REVIEW

**Comment by BWPanda** [comment]
I'm constantly reading through the documentation, so I can add to this PR if/when I come across any other class-related changes.

**Comment by dalexeev** [comment]
> We usually prefer that PRs to the main repository do a bit more substantial changes.

* Related: #46975

Perhaps we should create some kind of tracker to collect single typos and periodically fix them in batches?

**Comment by YuriSizov** [comment]
> Perhaps we should create some kind of tracker to collect single typos and periodically fix them in batches?

Well, we are currently on a bug tracker platform, this can be reported as an issue as well :)

The problem is with attribution and making sure that main repo commits have significance. If someone wants to make a PR, but it doesn't pass the bar of significance, then what should we do? If the policy is to reject it, track it, and then make a batch, then the author of that batch will take all the credit. Which is not very encouraging for the original poster.

So it's better to ask first-time contributors bringing these PRs to look for more cases. Chances are, they can add more meat to their contribution and take their deserved credit. And if in the meantime someone else does a PR that incorporates their change, intentionally or not, then so be it.

**Comment by YuriSizov** [comment]
> I guess you can make this pass the bar of significance by polishing up the whole documentation of these nodes.

Fixing only grammar here would be fine. We don't want our contributors to go down a rabbit hole like that when all they have right now is one missing article :)

**Comment by akien-mga** [comment]
I've included this fix directly in e1075e9c7ce41705a0a8df8b8d89819aaf7e47d6 while fixing various other typos, and credited you as co-author. Thanks for the contribution!

**Pull request closed without merging**
