### PR TITLE
Validate code tags in documentation for potential params

### PR DESCRIPTION
**Pull request by YuriSizov**
This PR adds a check to `make_rst.py` to look for matches between the text inside of the `[code][/code]` tag and known method parameter identifiers.

In the majority of cases this points to outdated descriptions, predating the `[param foo]` tag, which prevents us from validating those identifiers and leads to incorrect documentation. I fixed most of what was found, except for a couple of places which are legit. In some places I also "fixed" the issue by adding quotation marks around the identifier, because the description there described dictionary keys. I couldn't apply this approach everywhere, though, without creating inconsistencies.

So we still have some warnings, which add noise to the output. Perhaps it is time to hide warnings by default, I don't know. In any case, this is a useful check and it uncovered over 200 identifiers previously missed from documentation passes.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> So we still have some warnings, which add noise to the output. Perhaps it is time to hide warnings by default, I don't know.

I wouldn't hide warnings by default, because it would make it harder to catch new warnings and fix them. But the fact that we have a lot of false positives also makes it harder to spot new warnings.

Maybe we can add an argument that allows us to mark false positives as such, so they don't generate a warning? E.g. `[code nolint][/b][/code]`.

**Comment by YuriSizov** [comment]
That was one of the options we discussed. I need to dig up the PR that added the first warning where our possibilities were outlined.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Pull request merged**
