### PR TITLE
Clarify `AStarGrid2D.is_in_bounds` functionality

### LINKED ISSUE #82723: AStartGrid2D is_in_bounds() does not account for offset
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10 - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz   2.20 GHz

### Issue description

When checking if in bounds for a tile it does not take into account the offset property. I have to subtract my cell id by the offset inside of the `is_in_bounds()` command.

### Steps to reproduce

1. create a new project
2. create a Node2D
3. attack script to Node2D

paste following into script:
```
extends Node2D

var astar_grid:AStarGrid2D

func _ready():
	_init_grid()
	print(astar_grid.is_in_bounds(10,10))	#should be out of bound
	print(astar_grid.is_in_bounds(125,125)) #should be in bounds
	
func _init_grid() -> void:
	astar_grid = AStarGrid2D.new()
	astar_grid.size = Vector2i(100,100)
	astar_grid.offset = Vector2i(50,50)
	astar_grid.cell_size = Vector2(16,16)
	astar_grid.update()
```

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/12792262/New.Game.Project.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
* Fixes: #82723

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by kleonc** [comment]
>Clarify `AStarGrid2D.is_in_bounds` functionality

Currently this PR updates the docs for `AStarGrid2D.is_in_boundsv` but there's also a separate `AStarGrid2D.is_in_bounds` method, its docs should be updated too.

**Comment by AThousandShips** [comment]
Will do, thought it'd be excessive to add to both, as they are connected, but better be thorough

**Comment by kleonc** [comment]
> Will do, thought it'd be excessive to add to both, as they are connected, but better be thorough

For a short description duplication should be fine. If description would be longer then it would indeed make sense to make one of them e.g. something like _"Equivalent of ... but taking ... as argument(s)."_.

**Review by kleonc — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picking for 4.1.4 would affect translations, so since this is a clarification and not a fix for some mistake, I'd keep the descriptions as is.

**Pull request merged**
