### PR TITLE
Fix #65567: UI overlap with feature profiles

### LINKED ISSUE #65567: Multiple tabs combined on top of each other
### Godot version

4.0.alpha16

### System information

Win10

### Issue description

Multiple tabs show on top of each other

image
image

### Steps to reproduce

https://user-images.githubusercontent.com/102416174/189336851-ebab4f14-5257-4198-8e18-e190abcb8cb6.mp4

Manage Editor Features > Apply any preset > Reset to default

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by RedMser**
*Bugsquad edit:*
- Fixes #65567

### CODE REVIEW

**Comment by YuriSizov** [comment]
Huh, I guess this is present in 3.x as well?

**Comment by RedMser** [comment]
Just tried in 3.5 and doesn't seem like it happens there. 🤔

**Comment by YuriSizov** [comment]
The code is pretty similar, which is concerning. Would be worth to check why we regressed.

**Comment by YeldhamDev** [comment]
To be fair, there are some bugs with the docks in 3.5 when toggling them out:
image

**Comment by YuriSizov** [comment]
Superseded by https://github.com/godotengine/godot/pull/66194.

**Comment by akien-mga** [comment]
Superseded by #66194.

**Comment by YuriSizov** [comment]
Agreed.

**Pull request closed without merging**
