### PR TITLE
Mono: Bindings no longer relie on DocData for accessors

### LINKED ISSUE #15128: Mono fails to build with Error 47
**Godot version:**

Current Head: 7f1265b41fc52def42c433e5d324070bc6454d6b

**OS/device including version:**

Ubuntu 16.04

**Issue description:**

Make a bare bones project with a single script. It won't compile even with a brand new project.

**Steps to reproduce:**
1) Make a new project using the Mono version
2) Add a script
3) Try to build
4) It fails with "Error 47"
Note: nothing seems to print to the terminal when run from it.

screenshot from 2017-12-28 12-26-24

**Minimal reproduction project:**

[MonoBuildFail.zip](https://github.com/godotengine/godot/files/1591750/MonoBuildFail.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #15128

### CODE REVIEW

**Comment by neikeq** [comment]
That typo :(

**Comment by NathanWarden** [comment]
Thanks, I can confirm that this fixes it :)

**Comment by EugenEistrach** [comment]
@neikeq 
Compiled latest master branch with manually edited file with the changes from this pull request

It fixed  #15128 but I got a new issue. I created a new project with one node and a script attached to the node. The script has this two lines in the _Ready Method:

`var dir = new Directory();`
`dir.Open("res://");`

The second line crashes the game with following console output:

> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] <couldn't map PC to fn name>
> [1] <couldn't map PC to fn name>
> [2] <couldn't map PC to fn name>
> [3] <couldn't map PC to fn name>
> -- END OF BACKTRACE --

Before I compiled the engine (64bit) I cleaned the scons cache and followed the steps [here](https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_windows.html) and [here (for mono)](https://godot.readthedocs.io/en/latest/development/compiling/compiling_with_mono.html)

Did I do something wrong or is this crash reproducable?

**Comment by AllanDaemon** [comment]
This works for me too.

**Pull request merged**
