### PR TITLE
Use S, V in hue bar of ColorPicker

### PR DESCRIPTION
**Pull request by KoBeWi**
godot windows tools 64_dgO9R8HTlf

### CODE REVIEW

**Comment by groud** [comment]
Hmm, are other software doing it like this ? I suppose it's a more adequate way to visualize what will happen when you change the slider, but on the other hand it kind of make it impossible to set the hue first when the color defaults to white.

**Comment by KoBeWi** [comment]
> Hmm, are other software doing it like this ?

I've seen this in GIMP

> it kind of make it impossible to set the hue first when the color defaults to white.

Yeah, that could be an issue. On the other hand, setting hue first has no effect, so displaying it as white is more accurate.

**Comment by KoBeWi** [comment]
btw OKHSL color mode has similar behavior (and issues...):
godot windows tools 64_TfFh0hijLQ

**Comment by fire** [comment]
Does https://github.com/godotengine/godot/pull/67534 resolve any of these issues?

**Comment by KoBeWi** [comment]
Not really. Not sure if it's even fixable, because technically the colors are displayed correctly. So it's just sliders are not very useful for OKHSL.

**Comment by KoBeWi** [comment]
Rebased. I also added the same for OKHSL. This mode is weird, because changing hue seems to affect brightness, but well 🤔

https://user-images.githubusercontent.com/2223172/199502304-5d3689d7-eca3-4615-a88c-da4bdfec1eeb.mp4

tbh I'm not 100% sure about this change either. It makes the displayed color more accurate at a cost of some usability.  I opened the PR because it bothered me that hue bar doesn't change.

**Review by Calinou — COMMENTED** [review]
On principle, I like the idea of this :slightly_smiling_face: 

I've tested a version locally rebased against `master`, it looks like this:

### HSV

image

### OKHSL

image

The hue slider is rotated. I just accepted the incoming changes as-is when rebasing, which I guess is incorrect due to https://github.com/godotengine/godot/commit/84d6549c75abe27232d40f973f25a3cc2bad0078.

**Comment by Calinou** [comment]
For reference, GIMP's color picker behaves this way too – it displays previews on all sliders when in HSV mode:

image

**Comment by KoBeWi** [comment]
Rebased. I also fixed OKHSL mode (it was using HSV functions).

**Comment by Calinou** [comment]
>  GitHub did not pickup my push for whatever reason 🤔

That's strange, I see your latest commit on your fork: https://github.com/KoBeWi/Godot/tree/%F0%9F%8D%9D

That said, static checks are failing.

**Comment by KoBeWi** [comment]
Static checks are outdated.

**Comment by KoBeWi** [comment]
I am still unable to revive this. I'll reopen a new PR with a new branch.

**Review by Calinou — COMMENTED** [review]
<br>

**Pull request closed without merging**
