### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by djrm**

### CODE REVIEW

**Comment by reduz** [comment]
do you think you could also add an icons2x folder with the twice as big
versions? this way we can use these for hidpi

**Comment by reduz** [comment]
or actually probably better to add icons/2x/iconshere.png

**Comment by djrm** [comment]
2x version already there, but i have to tell that not all the original icons are in svg already, the ones i couldnt find in the editor were not vectorized, but let me now if you find any that is not vectorized

**Comment by reduz** [comment]
Testing them, so far they look fantastic!

The only change I would request is making the instance icon a chain again,
which I believe makes a bit more sense on how you are linking another scene.

**Comment by reduz** [comment]
As soon as I can, I will test them with hidpi

**Comment by djrm** [comment]
I think you're right about the instance icon, i tried to put a chain inside the scene icon, but failed miserably.

**Pull request merged**
