### PR TITLE
FileSystem dock now filters the import options based on search filter.

### PR DESCRIPTION
**Pull request by geekrelief**
In conjunction with PR #41242, you can have directories
of mixed import types, filter by part of a file name
and select a directory to reimport all the matching files.

### CODE REVIEW

**Comment by geekrelief** [comment]
The macOS Build failed. Is there a way to rerun the check?

**Comment by Calinou** [comment]
> The macOS Build failed. Is there a way to rerun the check?

You can force-push an unmodified commit (`git commit --amend && git push -f`).

**Comment by geekrelief** [comment]
@Calinou Thanks!

**Comment by geekrelief** [comment]
Same error happened again this time the iOS Builds and macOS Builds both report the same error:

 Post Load .scons_cache directory

**Comment by aaronfranke** [comment]
@geekrelief Was it intentional to close this PR?

**Comment by geekrelief** [comment]
Ooops no, I was removing some stale branches.

**Comment by aaronfranke** [comment]
@geekrelief Can you [rebase](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and test on the latest master branch? While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

**Comment by geekrelief** [comment]
It's a bit of a nuisance.  I'm going to close and reopen the pr, so I can track my commits properly.  I'm working off the 3.2 branch, so I want to maintain the master branch in a separate directory.

**Comment by geekrelief** [comment]
In master, any time a file is selected, its .import file is parsed multiple times. I have a project with several hundred 3D objects, and when selecting a folder the call to parse the .import file is called thousands of times, stalling the editor for a couple of seconds even with an SSD. The current patch, caches the config file after its been parsed.  For 150 objects this consumes about 40MB of memory.  The config file is used to determine the settings to populate the ImportDock, so I'm not sure there's a way around caching the configs.

I clear the cache of files when they're removed from FileSystemDock. I adde a signal to DependencyRemoveDialog with all the files paths for the files and files in directories removed.  Then FileSystemDock connects to the signal and passes the paths to ImportDock.

**Comment by geekrelief** [comment]
There's a bug with clearing the ImportDock config_cache.  After moving the files back from the trash, for some reason the paths are still in the cache even though they should have been erased.

**Comment by geekrelief** [comment]
Fixed the erase issue.

**Comment by KoBeWi** [comment]
Looks like something is bugged here
WAVs

**Comment by geekrelief** [comment]
> Looks like something is bugged here
> WAVs

Can you post a simple project that repo's this for me to test?

**Comment by geekrelief** [comment]
@KoBeWi Pushed a fix, please try it out.

**Comment by KoBeWi** [comment]
Seems the same as before.

Here's some project:
[TestProject.zip](https://github.com/godotengine/godot/files/6101033/TestProject.zip)
Click the Test folder, filter for wav or png and look at the number of files in the Import tab.

**Comment by geekrelief** [comment]
Thanks for the sample.  I'm not sure what's the fix yet.  There might be a bug in `tree.cpp`.  Basically, the tree is returning the wrong item selected after you type into the search filter. If you select `res://Test/` then type `w`, the tree returns `res://` as the selected path.  Seems like when the tree is being recreated as a result of the search filter, the selection is kinda lost, but the tree is still being highlighted correctly.

**Comment by KoBeWi** [comment]
If this is really Tree problem, it should be fixed in another PR.

**Comment by geekrelief** [comment]
I see the issue. https://github.com/godotengine/godot/blob/26d1b30d35d0897e18e4bc9521c1833eb1bdcf0c/editor/filesystem_dock.cpp#L168
This sets the `tree->selected_item`.

When the search string has a value, and a tree item's name matches, all its parent tree items are set to be open. `subdirectory_item->set_collapsed(false)` sets the tree's selected_item to the subdirectory_item. So as we go from the selected item, up the hierarchy we reach `res://` which gets set to the selected_item because the tree's select_mode is `Tree::SELECT_MULTI`
https://github.com/godotengine/godot/blob/8af3d566310b32def773220167e796731b3c4124/scene/gui/tree.cpp#L395

**Comment by geekrelief** [comment]
I think the solution might be to save the selection in FileSystemDock's `_tree_multi_selected`, so when the tree is recreated in `_update_tree` the selection can be restored as long as the items pass the search filter.

**Comment by geekrelief** [comment]
@KoBeWi Can you try again?  I think it's good now.

**Review by KoBeWi — DISMISSED** [review]
Looks ok functionality-wise.
The code seems good too at quick glance, but maybe someone should take a deeper look.

**Comment by geekrelief** [comment]
Cool. Yes, I'd appreciate if someone does take a closer look. 

I was a little surprised how the SceneTreeDock handles the tree selection vs the FileSystemDock.  FileSystemDock is reliant on Tree and a singular path making the restoration of the user's TreeItem selection do double work to select and open TreeItem after the tree has been recreated.  I didn't want to alter behavior unnecessarily, so I tried to keep the edits small, but there's a lot of hidden behavior going on because Tree is kind of messy.  It has as notion of 1 `selected_item` TreeItem pointer, but at the same time has an api to deal with multiple selections.  And it kind of mixes these things, making selection and deselection a little convoluted.

I haven't taken a close look at SceneTreeDock, but it seems to mirror Tree's with Nodes and is better behaved. The filtering and selection in SceneTreeDock is well behaved too.  I tried to make FileSystemDock match its behavior.

One thing I haven't tested or worked on is when the FileSystemDock is split. Selecting files from the file list doesn't seem to update the tree properly.

**Comment by geekrelief** [comment]
One issue I want to deal with before this is merged: If you have lots of imports, it can take a significant amount of time on click to walk the directory structure, which produces a pause while clicking through the filesystem.  If there's a way to do a visibility check on the Import Dock, I could defer the update until the dock is visible, or even better if there's a way to asynchronously update the dock so we don't pause the main thread, that'd be great.  If the asynch route is possible, then the `Import Dock could have a message `"Processing..."` and disable the `Reimport` button until it's ready.

**Comment by geekrelief** [comment]
I've moved the processing of the import files to a thread, so the main thread isn't blocked.  When the ImportDock is not visible no processing occurs.  I also added the ability to interrupt the import processing when selecting a different item in the FileSystemDock or when the ImportDock is hidden.
zjNKlQ6E6x

**Comment by geekrelief** [comment]
I did a memory benchmark.  And decided to clear the `config_cache` in the ImportDock when it's hidden.  I'm assuming reimporting is a short lived but intense operation, so it shouldn't be holding onto the config files unnecessarily. The screenshot shows the memory usage when I load several hundred 3d assets and pngs, then click on the Scene dock, then go back to the ImportDock where the 3d assets config files are then reprocessed into the config file cache.
Q8EXNOtgSF

**Comment by geekrelief** [comment]
I also have this working on 3.x.  So a backport is easy.

**Comment by geekrelief** [comment]
I just discovered a bug with my changes to `tree.cpp`.  Seems like it's affecting the Scene tree when I select a node lower in hierarchy then I select a node above it, both are selected. 
zD0NajFake
  This doesn't happen in the FileSystemDock. I've narrowed it down to one of the changes I've made where in `Tree::select_single_item` I deselect the `selected_item` if it's not `NULL`.  If I remove this code I get a crash if the FileSystemDock has a non-zero string in it, and the ImportDock is visible.  But if I leave it in, I get the Scene tree selection issue.

**Comment by geekrelief** [comment]
I've fixed the issue with selection in the scene tree dock and fixed several other issues related to using a thread in the import dock.

**Comment by geekrelief** [comment]
Pushed another change to improve the "selection memory" when using the search filter and clicking in the tree. Also made more changes to make the code more idiomatic with the rest of the code base.  Replaced thread + `NOTIFICATION_INTERNAL_PROCESS` with thread + `call_deferred` to make the code easier to follow.


https://user-images.githubusercontent.com/27040/112726875-dc9a9680-8edc-11eb-91e1-44b20442ec1b.mp4

**Comment by fire** [comment]
Is this pr ready?

**Pull request closed without merging**
