### PR TITLE
[Net] MultiplayerAPI remote scene spawning/despawning.

### PR DESCRIPTION
**Pull request by Faless**
Tentative implementation for godotengine/godot-proposals#75 .

`PackedScene`s can be configured to be spawnable via a new `MultiplayerAPI.spawnable_config` method (this will be done automatically at startup for selected scenes via project settings).

They can be configured either to be spawned automatically when coming from the server or to always require verification.

Another method, `MultiplayerAPI.send_spawn` lets you request a spawn on the remote peers.

When a peer receive a spawn request:
- If it comes from the server and the scene is configured as `SPAWN_MODE_SERVER`:
  - Spawn the scene
  - Emit signal `network_spawn`.
- Else:
  - Emit signal `network_spawn_request`.

When an instantiated node enters the tree:
- If the scene is registered in thhe MultiplayerAPI:
  - If configured as `SPAWN_MODE_SERVER`:
    - call `send_spawn` automatically
  - Emit signal `network_spawnable_added`.

```gdscript
func _ready():
	# This should be done by the engine/project settings.
	var id = ResourceLoader.get_resource_uid(Player.resource_path)
	multiplayer.spawnable_config(id, MultiplayerAPI.SPAWN_MODE_SERVER)
	# But also custom if you wish.
#	var id = 1000
#	ResourceUID.add_id(1000, path)
#	multiplayer.spawnable_config(id, MultiplayerAPI.SPAWN_MODE_SERVER)

	multiplayer.network_peer_connected.connect(self._peer_connected)
	multiplayer.network_peer_disconnected.connect(self._peer_disconnected)
	run()

func _peer_disconnected(id):
	if multiplayer.is_network_server():
		print("Despawning ", id)
		if $Players.has_node(str(id)):
			# Previously replicated scenes that exit the tree are despawned
			# automatically on clients when in SPAWN_MODE_SERVER
			$Players.get_node(str(id)).queue_free()

func _peer_connected(id : int):
	if multiplayer.is_network_server():
		print("Spawning ", id)
		# New spawns in the server are replicated automatically to clients
		# when in SPAN_MODE_SERVER.
		# Removing the node from tree later on will also despawn it remotely.
		# When joining mid-game previously network spawned scenes are
		# also replicated.
		var p = Player.instantiate()
		p.name = str(id)
		$Players.add_child(p)

#		# Or do everything manually in SPAWN_MODE_CUSTOM
#		# See signals:
#		# network_spawn_request, network_despawn_request
#		# network_spawnable_added, network_spawnable_removed
#
#		# Send old players
#		for p in $Players.get_children():
#			# Ideally a more friengly API lets you
#			# multiplayer.send_spawn(id, node)
#			multiplayer.send_spawn(id, ResourceLoader.get_resource_uid(Player.resource_path), p.get_path())
#		# Spawn this player
#		var scene_id = ResourceLoader.get_resource_uid(Player.resource_path)
#		multiplayer.send_spawn(0, scene_id, p.get_path(), str(id))
```

~De-spawning is not handled yet, while I wrap my head around it.~
**Also added automatic despawning and synchronization of previously spawned scenes in `SPAWN_MODE_SERVER`**
Will also need some work on the project settings editor, but that shouldn't be too hard.

While this is far from a complete synchronization system, it should have enough hooks for specialized addons, while allowing at least fast prototyping of client/server architecture.

Feedback is welcome.

Tagging interested parties: @jonbonazza @AndreaCatania @mhilbrunner @SaracenOne @jordo @fire  (I probably forgot someone, sorry in advance).

### CODE REVIEW

**Comment by Faless** [comment]
I've also added some basic Project Settings UI [here](https://github.com/Faless/godot/tree/mp/4.x_spawnable_gui) (only configure `SPAWN_MODE_SERVER`)

netgui

**Comment by Calinou** [comment]
> I've also added some basic Project Settings UI [here](https://github.com/Faless/godot/tree/mp/4.x_spawnable_gui?rgh-link-date=2021-08-04T13%3A30%3A32Z) (only configure `SPAWN_MODE_SERVER`)

I'd add a label on the top to explain what this is about, and rename the "/" folder to "res://" to make it consistent with the FileSystem dock.

**Comment by mhilbrunner** [comment]
Tested and played around with this a lot. Good work :)

As discussed in chat, there currently is a problem with spawning/despawning nodes that were auto-renamed on the server due to name collisions by Godot (e.g. 'nodeA' vs '@nodeA@2')

**Comment by Faless** [comment]
@mhilbrunner thanks a lot for the review. I've added a commit to specifically allow auto-generated node names.

**Comment by mhilbrunner** [comment]
I can confirm this fixes the issues with autonmated nodes. :)

**Review by mhilbrunner — APPROVED** [review]

**Review by fire — DISMISSED** [review]
We have concerns about design of the pr to be discussed at the next networking meeting.

**Comment by mhilbrunner** [comment]
> 
> 
> We have concerns about design of the pr to be discussed at the next networking meeting.

Sure :) Plan was to discuss this tomorrow. Anything you can share in advance?

**Comment by mhilbrunner** [comment]
Note from the networking meeting yesterday: 

Eeryone basically agreed that this is a good first step and should be merged soon-ish so it can be built upon. Fales wants to get a small addition in checking for a attached script/certain method to call on scenes.

Saracen/iFire brought up that they had some concerns about extendability but agreed after investigating this PR more that its good to go and most concerns didn't apply, and that we maybe need to see about extendability in the future (both for this PR and the multiplayer API as a whole). Note to @SaracenOne and @iFire: feel free to start documenting your pain points with the API somewhere and add us. :)

It was agreed that this is good work (cheers fales :) and that we should see about additions soon. Some concerns:
- This only handles spawning. A general, flexible and lightweight solution to handle state synchronisation is very much desired, even in core, and even if its just a good starting point complex games need to override/build their own. Better to have a good starting point people can use at the beginning than not have anything at all for something everyone who builds multiplayer needs.
- The current implementation can lag the server on client join if the server has to send a lot of spawn requests at once to catch up state, as its done in a single frame in a tight loop. Improvements should be investigated (threading? staggering over multiple frames?). Problem is the multiplayer API has a buffer and if that gets too full/not drained fast enough, that might cause disconnects. Same issue when receiving a lot of spawn requests at once on a client.
- We should try to take care that the API doesn't encourage stuff spawning at 0,0,0 unitialized for a frame before getting the first state sync, as thats ugly.

I think thats mostly it. Thanks fales for the good work, and thanks everyone for testing this and giving feedback!

**Comment by Calinou** [comment]
> We should try to take care that the API doesn't encourage stuff spawning at 0,0,0 unitialized for a frame before getting the first state sync, as thats ugly.

Spawning at very high coordinates might be a decent workaround, as this will prevent other players from seeing the instance at the origin for one frame.

**Comment by Faless** [comment]
As a follow up... the special script function approach for getting the state seems to work, but I would like to make some more thoughts into it (in terms of also serializing variants).
So, since it's taking a bit more time then expected, I'll merge this one as agreed, and open another pull-request (ideally today) specifically for initial state synchronization where we can discuss the best way to do it.

**Comment by mhilbrunner** [comment]
> So, since it's taking a bit more time then expected, I'll merge this one as agreed, and open another pull-request (ideally today) specifically for initial state synchronization where we can discuss the best way to do it.

Sounds good, go ahead. :)

**Pull request merged**
