### PR TITLE
3.x)Additive blending fix 

### PR DESCRIPTION
**Pull request by Riordan-DC**

### CODE REVIEW

**Comment by Riordan-DC** [comment]
I'm writing up a detail pull request and accidentally hit submit I think? SMH. How frustrating.

**Comment by Riordan-DC** [comment]
That fact that it is more like a feature proposal made me want to make a really good case for this PR so I am very embarrassed having this be accidentally submitted before it's ready. ;_;

**Comment by Riordan-DC** [comment]
Thanks for your help!

**Comment by Riordan-DC** [comment]
Sorry my mistake. I don't think I can reopen a PR.

**Comment by Riordan-DC** [comment]
I'm writing from my mobile rn. Maybe I can reopen it from my desktop.

**Comment by akien-mga** [comment]
This PR has 1500 commits so there's not much point reopening it as is, it would be better to redo it with only the relevant commit.

**Comment by Riordan-DC** [comment]
> This PR has 1500 commits so there's not much point reopening it as is, it would be better to redo it with only the relevant commit.

Ill make another, properly. Apologies for this mistake and thanks for your advice.
@akien-mga
Last time I caught up my branch I rebased then edited the commit history such that my commit was the most recent. Is that a good method of catching up my branch with the most recent 3.x changes or is there a better way?

**Comment by Riordan-DC** [comment]
> There's already a PR that makes animation blending additive in `3.x`: #53893

Cool! Should I make a PR for my solution or just discuss my solution in that thread?

**Comment by Calinou** [comment]
> Cool! Should I make a PR for my solution or just discuss my solution in that thread?

See that comment first: https://github.com/godotengine/godot/pull/53893#issuecomment-1172947478

If your implementaion is indeed different, then leave a comment in https://github.com/godotengine/godot/pull/53893.

**Pull request closed without merging**
