### PR TITLE
Add `set_slot_custom_icon` and `get_slot_custom_icon` to GraphNode

### PR DESCRIPTION
**Pull request by 4d49**
Add `set_slot_custom_icon` & `get_slot_custom_icon` to GraphNode.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Is there a proposal?

**Comment by ze2j** [comment]
I was about to make a very similar PR too :)

I didn't find a proposal but, IMHO, the justification is obvious: these icons are the only parameters of the `set_slot` method which cannot be modified individually. This PR fixes this.

```
void set_slot(int p_slot_index, 
              bool p_enable_left,
              int p_type_left,
              const Color &p_color_left, 
              bool p_enable_right,
              int p_type_right, 
              const Color &p_color_right, 
              const Ref<Texture2D> &p_custom_left = Ref<Texture2D>(), 
              const Ref<Texture2D> &p_custom_right = Ref<Texture2D>(), 
              bool p_draw_stylebox = true);

bool is_slot_enabled_left(int p_slot_index) const;
void set_slot_enabled_left(int p_slot_index, bool p_enable);

void set_slot_type_left(int p_slot_index, int p_type);
int get_slot_type_left(int p_slot_index) const;

void set_slot_color_left(int p_slot_index, const Color &p_color);
Color get_slot_color_left(int p_slot_index) const;

// New
void set_slot_custom_icon_left(int p_slot_index, const Ref<Texture2D> &p_custom_icon);
Ref<Texture2D> get_slot_custom_icon_left(int p_slot_index) const;

bool is_slot_enabled_right(int p_slot_index) const;
void set_slot_enabled_right(int p_slot_index, bool p_enable);

void set_slot_type_right(int p_slot_index, int p_type);
int get_slot_type_right(int p_slot_index) const;

void set_slot_color_right(int p_slot_index, const Color &p_color);
Color get_slot_color_right(int p_slot_index) const;

// New
void set_slot_custom_icon_right(int p_slot_index, const Ref<Texture2D> &p_custom_icon);
Ref<Texture2D> get_slot_custom_icon_right(int p_slot_index) const;

bool is_slot_draw_stylebox(int p_slot_index) const;
void set_slot_draw_stylebox(int p_slot_index, bool p_enable);
```

**Comment by ze2j** [comment]
I have somewhere a working implementation for 4.1 and 4.0 if you want to backport this. Let me known if you are interested in.

**Comment by 4d49** [comment]
> Is there a proposal?

Is it really necessary to create a new proposal here? I actually only created methods for the existing functionality. It is obvious that these methods were simply forgotten to be added before.  The comment of the person above confirms it.

**Comment by KoBeWi** [comment]
No, I think the justification in that comment makes sense. I'm not that familiar with GraphNode API.

**Review by Geometror — APPROVED** [review]
Makes sense and looks good :)

**Review by AThousandShips — APPROVED** [review]
Looks good, please update your commit message to be more clear, the title of the PR would be sufficient (it wasn't clear from a glance what thing these were added to)

**Comment by 4d49** [comment]
> Looks good, please update your commit message to be more clear, the title of the PR would be sufficient (it wasn't clear from a glance what thing these were added to)

@AThousandShips did I do the right thing?

**Comment by AThousandShips** [comment]
The commit message hasn't been changed, you need to `git commit --amend` and then `git push -f`

**Comment by AThousandShips** [comment]
No it should be `Add set_slot_custom_icon & get_slot_custom_icon to GraphNode` 🙂

**Comment by 4d49** [comment]
> No it should be `Add set_slot_custom_icon & get_slot_custom_icon to GraphNode` 🙂

@AThousandShips sorry. And now?

**Comment by akien-mga** [comment]
It seems like it's still a bit off, you modified the *description* of the commit, instead of its *title* (the first line if in a plain text editor), so it looks like this:

image

I'll fix it up for you :)

**Comment by 4d49** [comment]
> I'll fix it up for you :)

@akien-mga thank you😭

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
