### PR TITLE
Changed Mononoki font to Hack font

### PR DESCRIPTION
**Pull request by djrm**
You can ❤️ if you like the current font (**Mononoki** https://madmalik.github.io/mononoki/) or 👍if you prefer the proposed font (**Hack** http://sourcefoundry.org/hack/), you can also discuss which one is better if that helps, also you can provide evidence about your arguments, in any case this might end up with a weighted pseudo-democratic voting.

here are screenshot of how they look in Godot:
Current (**Mononoki**)
screenshot from 2017-09-14 19-39-29

**Hack**
screenshot from 2017-09-15 19-25-48

### CODE REVIEW

**Comment by willt** [comment]
Hack looks pretty nice to me. Maybe we should just have them both and let the user decide? :)

**Comment by Noshyaar** [comment]
Mononoki's capital O looks a bit too thin for me. Other than that they're both okay.

**Comment by cbscribe** [comment]
Good work! ((Hopefully you haven't sparked off a font war. :P)

**Comment by n-pigeon** [comment]
Hopefully no one judges from screenshots :D Mononoki is scaled down here.

**Comment by Geequlim** [comment]
I hope this font can aligns CJK characters fine in the right way.

**Comment by Geequlim** [comment]
image

**Comment by Geequlim** [comment]
image

**Comment by djrm** [comment]
@Geequlim, thats hack font.
screenshot from 2017-09-16 23-58-22

as far as i can tell none of these fonts support CJK, the one i've seen that supports CJK is NotoMono, but with the CJK variation

**Comment by willt** [comment]
I don't see a lot of CJK characters in code. Wouldn't those mainly be in localization files? Doesn't seem like an issue to me.

**Comment by Geequlim** [comment]
@willt  It is not a serious issue.

**Comment by TeddyDD** [comment]
Related discussion #11321

**Comment by toger5** [comment]
why is the font size bigger in your screenshot? just setting?
The current default font size is a little small too. so if you could increase it in that pr too would be good (for code editor not docs)

**Comment by djrm** [comment]
@akien-mga i think this is also safe to merge, it seems that people prefer the hack font.

**Pull request merged**
