### PR TITLE
Add editor icons for MultiplayerSpawner and MultiplayerSynchronizer

### PR DESCRIPTION
**Pull request by Calinou**
These designs are kind of placeholders; let me know if you can think if something more evocative. My idea was to have something like a globe icon but with the arrows for MultiplayerSynchronizer (like HTTPRequest), and sparkles for MultiplayerSpawner (or maybe a literal "plus" symbol).

## Preview

image

### CODE REVIEW

**Comment by akien-mga** [comment]
The arrows in the circle don't seem very readable at this scale, I had to zoom in to see that it's arrows. I wonder if it could work better with something inspired from a reload/refresh icon with circling arrows:
image

**Comment by Calinou** [comment]
> Maybe something like this? grafik

Looks good to me :slightly_smiling_face: 

Could you send me the SVGs? I'll add you as a co-author in the commit.

**Comment by Calinou** [comment]
> 

The uploaded SVGs seem to be broken (possibly due to GitHub preprocessing them). Can you try putting them in a ZIP archive and uploading that instead?

**Comment by Geometror** [comment]
Directly out of Inkscape:
[multiplayer_spawner_sync_icons.zip](https://github.com/godotengine/godot/files/8943478/multiplayer_spawner_sync_icons.zip)

Or the minified code:
MultiplayerSpawner
```svg
<svg height="16" width="16" xmlns="http://www.w3.org/2000/svg"><path style="fill:none;fill-opacity:.996078;stroke:#e0e0e0;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:16.5;stroke-opacity:1;paint-order:stroke markers fill" d="M4.936 7.429A4 4 0 0 1 8 6a4 4 0 0 1 3.064 1.429M1.872 4.858A8 8 0 0 1 8 2a8 8 0 0 1 6.128 2.858"/><path d="M7 9v2H5v2h2v2h2v-2h2v-2H9V9Z" fill="#5fff97"/></svg>
```
MultiplayerSynchronizer
```svg
<svg height="16" width="16" xmlns="http://www.w3.org/2000/svg"><path style="fill:#5fff97;fill-opacity:1;stroke:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;paint-order:stroke fill markers" d="M5 10h3l-2 4-2-4Z"/><path style="fill:#ff5f5f;fill-opacity:1;stroke:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;paint-order:stroke fill markers" d="M9 14h3l-2-4-2 4Z"/><path style="fill:none;fill-opacity:.996078;stroke:#e0e0e0;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset:16.5;stroke-opacity:1;paint-order:stroke markers fill" d="M4.936 7.429A4 4 0 0 1 8 6a4 4 0 0 1 3.064 1.429M1.872 4.858A8 8 0 0 1 8 2a8 8 0 0 1 6.128 2.858"/></svg>
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
