### PR TITLE
Add Always Incremental update mode + `queue_update()` in ReflectionProbe

### LINKED ISSUE #26292: Reflection probes only refresh on editor restart
**Godot version:**

3.1.0 beta 6

**OS/device including version:**

Windows 10.0.15063 with NVidia GeForce GTX 1070

**Issue description:**

I had added some tiles to a gridmap around a reflection probe, expecting the probe to update while in the editor to reflect the new geometry. The probe's capture only refreshed when I closed and reopened the editor. First image is before restarting, second image is after.

Before restart
After restart

**Steps to reproduce:**
- Add a reflection probe to the scene.
- Change geometry around it (in my case, filling more tiles in a gridmap).
- Observe that the old geometry is still reflected.
- Restart the editor.
- Observe now that the reflection capture reflects the previous edits.

### PR DESCRIPTION
**Pull request by Calinou**
The Always Incremental update mode behaves like the Once update mode, but it always updates even when its parameters aren't changed. Since it updates one cubemap face per frame, it will update at 10 Hz when running at 60 FPS. This is not quite as smooth for fast-moving objects such as cars, but it can be sufficient for slower-moving objects and when targeting low-end configurations.

Always Incremental update mode also uses higher-quality roughness filtering compared to the Always Full update mode.

`queue_update()` can be used to manually force an update on a ReflectionProbe without having to move it for at least one frame. This is useful when modifying a nearby object to ensure the ReflectionProbe has up-to-date reflections.

This change can be backported to `3.x` if desired (both GLES3 and GLES2).

This closes https://github.com/godotengine/godot/issues/26292. See also https://github.com/godotengine/godot-proposals/issues/2934.

**Testing project:** [test_reflection_probe_queue_update.zip](https://github.com/godotengine/godot/files/7712240/test_reflection_probe_queue_update.zip)
Press <kbd>C</kbd> to cycle between ReflectionProbe update modes, <kbd>F</kbd> to force a ReflectionProbe update (only relevant when using the Once update mode) and <kbd>Space</kbd> to toggle the dynamic object's visibility.

## Performance

**OS:** Fedora 34
**CPU:** Intel Core i7-6700K
**GPU:** GeForce GTX 1080

| Update mode | FPS |
|-|-|
| Once | 391 FPS (2.56 mspf) |
| Always Incremental | 340 FPS (2.94 mspf) |
| Always Full | 217 FPS (4.61 mspf) |

### Update Mode: Once

https://user-images.githubusercontent.com/180032/146015437-b7f86797-ff8a-4ea1-b9ac-2b8181c49cad.mp4

### Update Mode: Always Incremental

https://user-images.githubusercontent.com/180032/146015445-738a6682-dd23-4fda-94eb-71499eed9b26.mp4

### Update Mode: Always Full

https://user-images.githubusercontent.com/180032/146015469-339215dd-04a8-4c84-b4a8-f47b1c174cf5.mp4

### CODE REVIEW

**Comment by clayjohn** [comment]
We need to do a proposal for time slicing of reflection probes. While I am certain this is an improvement over the previous options. I am not sure it will be ideal in practice. The reason for that is that the performance tradeoffs involved will change depending on the complexity of the scene. For a relatively simple scene we can almost ignore the cost of updating the base layer of the reflection map. But for a complex project, rendering the base layer may be even more expensive than updating the roughness mipmaps. 

With this PR updates are done as follows:
1. UPDATE_ONCE: 6 frames to update base reflection, 6 frames to update Mip1, 1 frame for each additional mip level
2. UPDATE_INCREMENTAL: 6 frames to update base reflection, 6 frames to update Mip1, 1 frame for each additional mip level
3. UPDATE_FULL: updates all reflections and mips in each frame

I have a feeling we need to untie the rendering update from the roughness map processing. So that users can choose what tradeoffs they would like to make.

**Comment by Calinou** [comment]
> I have a feeling we need to untie the rendering update from the roughness map processing. So that users can choose what tradeoffs they would like to make.

I was thinking about something similar. Maybe we should have 3 properties:

**Filter Mode:**

- High Quality
- Real-Time

**Update Policy:**

- Once (if https://github.com/godotengine/godot-proposals/issues/2934 is accepted)
- When Moved
- Always

**Update Slicing:**

- 1 Face per Frame (Faster, More Latency)
- 2 Faces per Frame
- 3 Faces per Frame
- 6 Faces per Frame (Slower, Less Latency)

From my understanding, the real-time roughness filter *needs* all 6 faces of the cubemap to be available at the same time. Therefore, choosing it would ignore the **Update Slicing** property's value.

**Comment by clayjohn** [comment]
That mostly sounds good to me. One thing to keep in mind is that the roughness mips get updated after the base reflection is updated regardless. Accordingly, you don't need to ignore update slicing when using the "real-time" roughness filter. For example, if you set time slice to 6, it will take seven frames to update when using real time filtering.

For update policy, we should connect it to the objects it draws so that it only updates when objects within its range update. I think shadows do this to some extent. So update policy should be "once, on change, always" (there might not be a reason to update always) I am also not sure about update_once. I think it may become unnecessary if we allow a separate sky for reflections.

With respect to the update slicing options, we probably don't need the granularity of 1, 2, 3, and 6. I took a peak at Unity, and they only allow 3 options. All update in one frame, update base in one frame and roughness over 8, and update base over 6 frames and roughness over 8. It may be best for us to just offer 1 and 6. But I don't feel strongly about that. Let's see what users would prefer.

**Comment by Calinou** [comment]
> I think it may become unnecessary if we allow a separate sky for reflections.

Indeed, I agree that with the workaround presented in https://github.com/godotengine/godot-proposals/issues/3593#issuecomment-994006311, there isn't much need to support `update_once` anymore.

**Comment by jtnicholl** [comment]
Will this make it into 4.0? If not, could we at least split off the `queue_update()` method to its own PR and get that in? Moving probes to make them update feels like such a hack.

**Comment by Calinou** [comment]
> Will this make it into 4.0? If not, could we at least split off the `queue_update()` method to its own PR and get that in? Moving probes to make them update feels like such a hack.

`queue_update()` can be split into its own PR, but I don't have time to do this right now. I'd recommend you open a pull request for this if you need this in 4.0 (or at least in your own fork).

**Comment by Calinou** [comment]
- Superseded by https://github.com/godotengine/godot/pull/97773.

I've redone this PR from scratch following https://github.com/godotengine/godot/pull/55929#issuecomment-993958945, which adds many new options to choose from.

**Pull request closed without merging**
