### PR TITLE
fixed border on the right of viewport

### PR DESCRIPTION
**Pull request by toger5**
(merge fast pls ;) )
mentiend in the discussion of
#11207 

seen here
screen shot 2017-09-12 at 23 23 52

### CODE REVIEW

**Review by djrm — APPROVED** [review]

**Comment by toger5** [comment]
@akien-mga cherry picked another change into this pr.
I can remove It but I was really curious what happens when one of them gets merged...
maybe someone can also just tell me.
I want to know how it behaves, since that would allow me to cherry pick a relevant commit from another pr to get rid of potential merge conflicts.

**Comment by groud** [comment]
So, should we merge this PR ?

**Comment by toger5** [comment]
@groud so this is basically not a really good idea...
I didn't notice yet, that cherry-picked commits DO have different hashes.

hm...
apparently rebase would work to get rid of the cherry picked commit... but therefore the other commit has to be in master before.
ill just remove it and then we can merge...

**Comment by toger5** [comment]
@ground fixed and ready to merge.

**Pull request merged**
