### PR TITLE
Reimplement ping-pong animation and reverse playback

### LINKED ISSUE #50636: AnimationTree function call track loop
### Godot version

3.3.2

### System information

macOS Catalina (10.15.7)

### Issue description

When calling a function from an AnimationPlayer activated by an AnimationTree a loop is triggered in some cases.

- When a frame takes too long to process.
- When the call method keyframe is at the very end of the track.

### Steps to reproduce

1. Create AnimationPlayer instance
    - add function call track
    - add function call keyframe (at the end time of the track)
2. Create AnimationTree instance
    - link animation player to tree
    - create AnimationNodeBlendTree as root
    - add animation node and connect it to output
3. `print_debug` in the called function and behold!

When adding the call method somewhere in the middle of the animation a breakpoint can also trigger this loop. In some exports with slower performance this can also occur when a frame takes too long to process.

### Minimal reproduction project

[GodotAnimationPlayerFunctionCallLoop.zip](https://github.com/godotengine/godot/files/6846709/GodotAnimationPlayerFunctionCallLoop.zip)

### LINKED ISSUE #54619: AnimationTree repeats the methods and properties that trigger the last frame of the acyclic animation
### Godot version

3.x Latest

### System information

windows 10 

### Issue description

AnimationTree repeats the methods and properties that trigger the last frame of the acyclic animation.
I only pressed the button once.
As shown in the figure, I don't know whether it is a bug or a feature?
How can I keep the last frame of the current animation instead of switching to the next animation to solve this problem?

AnimationTree 会重复触发非循环动画的最后一帧的方法和属性.
我只按了一次Button.
如图所示,不我知道是BUG还是特性?
如何可以保持当前动画的最后一帧,而不是切换到下一个动画来解决这个问题?

image

image
image

### PR DESCRIPTION
**Pull request by TokageItLab**
This is a resend of #48332.

Once approved before, but temporarily reverted due to conflicts with a huge overhaul of the animation features.

Until that overhaul is finished, it will be left as a draft PR to check and resolve conflicts.

_Bugsquad edit:_ Fixes #50636. Fixes #54619. Supersedes #51576.

### CODE REVIEW

**Comment by fire** [comment]
Ah it's not ready yet, I was pinged.

**Comment by TokageItLab** [comment]
@reduz @fire Rebased. I did a quick test using a previous project but Blendshape and compressed tracks were not tested (for some reason, the mesh instance with Blendshape crashes, and I don't know much about compression tracks in terms of how they are generated), but the code seems to be fine.

[ping-pong_demo_re.zip](https://github.com/godotengine/godot/files/7465413/ping-pong_demo_re.zip)

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by magian1127** [comment]
Can fix the bug of 3.X?

**Comment by TokageItLab** [comment]
We need to cherry-pick #51576 to fix #50636 and #54619.

**Comment by timothyqiu** [comment]
Ah, I tested those issues and they were resolved by this PR. I thought this would be backported... Should I reopen my PR?

**Comment by TokageItLab** [comment]
This PR is large, so it is difficult to backport it. So, smaller fixes should be cherry-picked separately for 3.x.

**Pull request merged**
