### PR TITLE
Clarify that `Callable` will not be encoded with `var_to_bytes`

### LINKED ISSUE #79802: Callables and lambdas stored with FileAccess store_var() become null::null after get_var().
### Godot version

v4.1.1.stable.official.bd6af8e0e

### System information

Windows 10.0.19045 - Vulkan (Compatibility) - GeForce GT 540M- Intel Core i7-2670QM CPU @ 2.20GHz (8 Threads)

### Issue description

Storing a callable or a lamba to a file with FileAccess.store_var(full_objects = true), and then reading it, causes it to be lost - printing it outputs it as null::null.

Calling the loaded callable results in an error: `Attempt to call function 'null::null (Callable)' on a null instance.`

Other types of variables can be stored in the same file, with the same method, and retrieved without problems.

### Steps to reproduce

0. Run the minimal reproduction script.
1. Read the print() outputs in the console.
2. Observe how the callable and the lambda are lost after loading.
3. Test the script again with `var allow_objects` changed to `false` - result should be the same.
4. Uncomment the call statements at the end of the script.
5. Observe the error appearing when a call on the loaded callable is attempted.

### Minimal reproduction project

```gdscript
var allow_objects = true


func test_func():
	print("ok")


func _ready():

	var text_before = "test_before"
	var callable = Callable(self, "test_func")
	var lambda = func(): print("success")
	var text_after = "test_after"

	print("Printing input to store_var(): ")
	print(text_before)
	print(callable)
	print(lambda)
	print(text_after)
	print()

	print("Calling functions before storing: ")
	callable.call()
	lambda.call()
	print()

	print("Saving and loading.")
	var file = FileAccess.open("user://save.dat", FileAccess.WRITE)
	file.store_var(text_before, allow_objects)
	file.store_var(callable, allow_objects)
	file.store_var(lambda, allow_objects)
	file.store_var(text_after, allow_objects)
	file.close()

	await get_tree().create_timer(1).timeout

	file = FileAccess.open("user://save.dat", FileAccess.READ)
	var loaded_text_before = file.get_var(allow_objects)
	var loaded_callable = file.get_var(allow_objects)
	var loaded_lambda = file.get_var(allow_objects)
	var loaded_text_after = file.get_var(allow_objects)
	file.close()
	print()

	print("Printing output from get_var(): ")
	print(loaded_text_before)
	print(loaded_callable)
	print(loaded_lambda)
	print(loaded_text_after)
	print()

	print("Calling functions after loading: ")
	#loaded_callable.call() # causes an error
	#loaded_lambda.call() # causes an error
```

### PR DESCRIPTION
**Pull request by AThousandShips**
Only added to `@GlobalScope`, can add to `FileAccess` as well if desired, but it links there so didn't want to repeat too much

* Fixes: #79802

### CODE REVIEW

**Comment by Ybaedbaenn** [comment]
Thank you for fixing!

**Comment by adamscott** [comment]
I wonder if this should be in the `Callable` doc instead.

**Comment by AThousandShips** [comment]
I'd say here or both, as you won't necessarily think to look at `Callable` when doing IO

**Comment by AThousandShips** [comment]
Also the matching detail for `var_to_str` is here from a previous PR

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
