### PR TITLE
Add a scale mode to the 2D editor

### LINKED ISSUE #21873: Node2D Scaling Handles Gone
**Windows 64-bit v3.1.alpha.custom_build.4b6846a**

Started doing some node work in 3.1, and just noticed that the scaling handles are gone from Node2D.  This makes certain tasks very tedious.  Is this a bug or is there a new option, or change?

### 3.0 - This can be very handy for manipulating root transforms.
scale

### 3.1 - Am I missing something?
noscale

Position2D seems to also suffer from this too, possibly many others.  I suppose I like that it seems easier to select nodes by clicking, but now a lot of manual entry for scaling is needed.

Am I missing something?

Thanks.

### PR DESCRIPTION
**Pull request by groud**
Adds a new scale mode in the 2D editor.
- Shift key : uniform scaling
- Ctrl+Alt keys: activate scaling in select mode 

Would be good to have this for 3.1, as removing the previous handles had a significant impact on the workflow speed for some people. 

output

Closes #21873

### CODE REVIEW

**Comment by avencherus** [comment]
Quite loving it so far, going to be a massive improvement, and a great implementation.  Glad you were able to find the room for the modifiers too.

Ran into a couple of slight problems.  Some may just be me not understanding the behavior of the gizmo, but it seems at least one issue has an accumulation thing going on.

Are the handles expected to snap back to a default size after releasing?

Thinking it would at least be a big visual bonus if they kept their size increases, you'd know right away that non-uniform scaling was present and roughly the ratio.

Here in these examples it is super obvious it is taller.  XD  But maybe in subtler instances I wouldn't know if the art was just a bit stretched in the texture itself and overlook there was some added scaling.

### Scaling up to non-uniform.
a1 188

### Handles reset.  
_(Maybe they shouldn't?  Sort of expect the scale X == Y when seeing this.)_
a2 277


The snapping seems a bit jumpy at least, more so when they go into negative scaling.  

ezgif com-optimize

Then when doing the uniform scaling, it appears to accumulate when repeating the process.  Up until a situation where the handles are negative, but the scaling is not yet negative.

ezgif com-optimize 1

**Comment by groud** [comment]
This was done on purpose, as it keeps the gizmo always with a reasonable size even with extreme scales. This is how it's done in most 3D softwares.

I personally believe it's quite an expected behaviour but I understand I might be weird to use when you need a specific scale. But in that case you have the inspector.

If it's not enough, I could display the current scale next to the handles as a helper.

**Comment by groud** [comment]
Anyway, most of this should be solved by implementing grouped scaling.

**Comment by groud** [comment]
That being said, the impact on the scale should maybe depend on the zoom level, that would make it more pertinent

**Comment by avencherus** [comment]
>>> That being said, the impact on the scale should maybe depend on the zoom level, that would make it more pertinent

Some scaling with zoom level would definitely be a nice touch.

>>> This was done on purpose, as it keeps the gizmo always with a reasonable size even with extreme scales. This is how it's done in most 3D softwares.

I see, I can imagine it going rather wild at larger scales.

The value hints could be handy.  Thinking about what you said I another idea popped up.  It might be non-sensical though.  X)

I know this very much falls from what is standard, but when it returns to the base lengths what if the ratio was checked, and the smaller of the two dimensions go scaled from the base length.

Like if it were (2, 1), the red handle is 100% and the green handle is 50%.  And for (1, 2), the opposite.

With of course probably some minimum clamping, but how often does 10 to 1 and such come up?

Were the things in the bottom two GIFs issues?  It seemed like negative drags had some dead spots for the handle tips, and the uniform scaling reset was losing track of where 0 was.

**Comment by avencherus** [comment]
Here's a mock up of that idea.  Hopefully it isn't too dumb.  XD

godot windows opt tools 64_2018-09-10_22-10-21

```
if(x > y): handle_y_len max(handle_y_len * (y/x), min_len)
elif(x < y): handle_x_len = max(handle_x_len * (x/y), min_len)
```

**Comment by aaronfranke** [comment]
I don't know why this was merged, it's a pretty glaringly obvious flaw that the Y axis handle is pointing up while Godot's handedness in 2D has the Y axis pointing down...

**Comment by avencherus** [comment]
It's a much needed usability feature, since the removal of the Node2D rectangle that allowed fast scaling.

I wouldn't say flawed, but maybe the handles can be seen as inconsistent.  Though this question can probably be aimed at other things too, like the collision shapes.

image

Scaling on the Y axis will increase the size in both directions, so I never really thought much of this.  A translation handle might be a different story, then it might get a little odd looking if they were both different.

**Pull request merged**
