### PR TITLE
Fixed TextureRegion autoslice issue.

### LINKED ISSUE #37614: TextureRegion Autoslice not showing up
**Godot version:** 3.2.1.stable

**OS/device including version:** Win

**Issue description:**
_The first time_ a project has a Sprite with a Texture Region set, the Autoslice regions won't show up and are not selectable. 
To make them show up, you have to either click on a different Node in the Scene Panel, then come back to the Sprite and open the TextureRegion bottom panel. They will also show up when you switch to a different OS window and then back to Godot.
If the TextureRegion was used only once in the project, this bug is no longer reproducible.

autoslice_bug

**Steps to reproduce:**
1. Create a new project or open a project that never used TextureRegion bottom panel before,
2. Add a Sprite to your scene or select existing Sprite in the ScenePanel,
3. Load the spritesheet texture to your Sprite Texture and open the bottom "TextureRegion" panel,
4. Change "Snap Mode" to "Autoslice" 

**Minimal reproduction project:**
Best to try with new project. Test texture:
icon_texturepack

### PR DESCRIPTION
**Pull request by dankan1890**
Fix #37614.

### CODE REVIEW

**Comment by akien-mga** [comment]
Please amend the commit log to be more explicit, we want commits to make sense when visualized through `git log` (which can be grepped with keywords to find commits relevant to a given keyword).

See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by dankan1890** [comment]
Done!
Sorry, I pushed before going to sleep and I would have corrected it and I didn't think it was reviewed so quickly ;)

**Comment by akien-mga** [comment]
Thanks!

**Comment by golddotasksquestions** [comment]
I think this was the fastest I've seen any issue I've ever reported being closed by a fix! Thank you so much for your contribution!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
