### PR TITLE
Use Rect2's get_end().

### PR DESCRIPTION
**Pull request by AnilBK**
1.Use Rect2' get_end() function, where it doesn't hurt readability.
https://github.com/godotengine/godot/blob/87de2e7c4a38b1258d9a554c7f50cdbd8ac825fa/core/math/rect2.h#L319-L321

~~2.Simplified Cases like this:
`(rect.get_position() + rect.get_end()) / 2` to `rect.get_position() + rect.get_size() / 2`~~
 (Merged in https://github.com/godotengine/godot/pull/52878)

### CODE REVIEW

**Review by aaronfranke — COMMENTED** [review]
This looks good. The many uses of `position + size / 2` makes me wonder if we should add a `get_center` method (and potentially a center property) to Rect2 (and AABB).

**Comment by AnilBK** [comment]
> 
> 
> This looks good. The many uses of `position + size / 2` makes me wonder if we should add a `get_center` method (and a center property) to Rect2 (and AABB).

I was thinking of same. So, I did a quick search for possible usages.
.position + .size * 0.5  = 29 Results
.position + .size / 2    = 10 Results
Total = 39 results.

For comparision to popular methods:
get_global_position():105 results in 43 files.
.get_position():57 results 
.get_size():41 results.

I guess it's worth adding. Would specially help for readability.

**Comment by aaronfranke** [comment]
Go ahead and add `get_center`, the consensus is that it's a good idea. From RocketChat:

center

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
