### PR TITLE
Add all clang-tidy checks, ignore all unwanted ones

### PR DESCRIPTION
**Pull request by sondredl**
adds all clang-tidy checks, then ignores any that make changes to the code in its current state

### CODE REVIEW

**Comment by sondredl** [comment]
@Calinou should i do something to get a review on this, or does it just happen some time in the 4.x milestone pipeline?

**Comment by Calinou** [comment]
I haven't used clang-tidy extensively, so I don't know if this list is suitable.

In fact, the current list already doesn't pass:

```
pre-commit run --hook-stage manual clang-tidy --all-files
...
725 warnings generated.
clang-tidy applied 37 of 37 suggested fixes.
424 warnings and 1 error generated.
Error while processing /home/hugo/Documents/Git/godotengine/godot/core/config/engine.h.
```

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/pull/93401, which should likely be merged first. CC @Repiteo 

I wouldn't enable any clang-tidy check that currently passes fine without evaluating whether it's actually a code quality guideline we want to follow. But it's a good idea to review the various checks offered by clang-tidy.

**Comment by sondredl** [comment]
> See #93401, which should likely be merged first. CC @Repiteo
> 
> I wouldn't enable any clang-tidy check that currently passes fine without evaluating whether it's actually a code quality guideline we want to follow. But it's a good idea to review the various checks offered by clang-tidy.

Is there a code quality guideline we are currently following? If so, where can i find it?
My experience with clang-tidy is that the ones that offer automatic fixing are the ones that are the simplest to enforce. The error you sow above is one caused by the compile_commands.json file not containing the path to an include

**Comment by dalexeev** [comment]
Unrelated whitespace changes in `modules/gdscript/tests/scripts/`.

**Comment by AThousandShips** [comment]
I don't think any checks or changes should be run in `thirdparty`

**Pull request closed without merging**
