### PR TITLE
Fix tiled EXR import

### LINKED ISSUE #21422: Crash with some exr images.
**Godot version:**

8c435a343e9739f30cb2e347df95835c91c1ff1a

**OS/device including version:**

Linux

**Issue description:**

Godot crashes with some exr images, the size doesn't matter. Both included test-pictures can be opened with other software, with godot only the one.

image

```
Thread 1 "godot3" received signal SIGSEGV, Segmentation fault.
ImageLoaderTinyEXR::load_image () at modules/tinyexr/image_loader_tinyexr.cpp:151
151						reinterpret_cast<float **>(exr_image.images)[idxR][i],
(gdb) l
146	
147			// Assume `out_rgba` have enough memory allocated.
148			for (int i = 0; i < exr_image.width * exr_image.height; i++) {
149	
150				Color color(
151						reinterpret_cast<float **>(exr_image.images)[idxR][i],
152						reinterpret_cast<float **>(exr_image.images)[idxG][i],
153						reinterpret_cast<float **>(exr_image.images)[idxB][i]);
154	
155				if (p_force_linear)

(gdb) bt
#0  ImageLoaderTinyEXR::load_image () at modules/tinyexr/image_loader_tinyexr.cpp:151
#1  0x0000555557939f72 in ImageLoader::load_image () at core/io/image_loader.cpp:66
#2  0x0000555556413f18 in ResourceImporterTexture::import () at editor/import/resource_importer_texture.cpp:376
#3  0x000055555628eece in EditorFileSystem::_reimport_file () at editor/editor_file_system.cpp:1538
#4  0x0000555556295dda in EditorFileSystem::reimport_files () at editor/editor_file_system.cpp:1692
#5  0x00005555562975d8 in EditorFileSystem::_update_scan_actions () at editor/editor_file_system.cpp:552
#6  0x0000555556298308 in EditorFileSystem::_notification () at editor/editor_file_system.cpp:1072
#7  0x00005555577a4264 in Object::notification () at core/object.cpp:978
#8  0x00005555568ee748 in SceneTree::_notify_group_pause () at scene/main/scene_tree.cpp:957
#9  0x00005555568f1324 in SceneTree::idle () at scene/main/scene_tree.cpp:510
#10 0x0000555555784bb4 in Main::iteration () at main/main.cpp:1796
#11 0x000055555577c3c1 in OS_X11::run () at platform/x11/os_x11.cpp:2695
#12 0x000055555576decc in main () at platform/x11/godot_x11.cpp:55
```
**Steps to reproduce:**
Open the attached project, godot crashes.

**Minimal reproduction project:**

[floor-test-exr-bug.zip](https://github.com/godotengine/godot/files/2321070/floor-test-exr-bug.zip)

### PR DESCRIPTION
**Pull request by elasota**
Update tinyexr to new version that fixes uncompressed EXRs being full of corrupt data, and fix crash when importing tiled EXR.

Fix #21422

### CODE REVIEW

**Comment by akien-mga** [comment]
There are some style issues for clang-format: https://travis-ci.org/godotengine/godot/jobs/420956270

**Comment by akien-mga** [comment]
Please also update the tinyexr git commit reference in https://github.com/godotengine/godot/blob/master/thirdparty/README.md#tinyexr

**Comment by elasota** [comment]
Should be fixed now

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
