### PR TITLE
LocalVector - Add exact resizing and shrink_to_fit

### PR DESCRIPTION
**Pull request by lawnjelly**
Add the ability to resize and reserve to exact capacities, rather than power of two. Also adds a "shrink_to_fit" function to compact the vector.

* Alternative to #64120
* Replaces "tight" template argument from #55954
* Changes the small amount of code already using `TightLocalVector` to use the new functionality.

## Notes
The addition of the "tight" argument to `LocalVector` is problematic, in the sense that the logical conclusion of this approach is to add reallocation on each `push_back` and `insert`, as exemplified in #64120 . This makes such a `TightLocalVector` incredibly easy to misuse, because reallocation on each `push_back` could be prohibitively expensive.

Instead of having a specialization of `LocalVector`, an alternative approach is to simply integrate the ability for exact sizing into the regular `LocalVector`. This has several advantages:

* Regular `LocalVector`s can benefit from exact sizing, for instance for compaction after unloading a game level, or after an unknown number of `push_back`s.
* Exact sized `LocalVector`s are protected from the misuse that would occur by calling `push_back` etc.
* As these are regular `LocalVector`s, exact sized vectors can be passed to external functions that take a `LocalVector` as argument.

`shrink_to_fit` is named after the similar function in `std::vector`, with the small addition that this one can optionally shrink to power of two boundaries.

N.B. Marked milestone as 4.0 because as a core data structure further work and PRs will depend on this - already code is being written using `TightLocalVector` so it makes sense to make decision on this area sooner rather than later.

### CODE REVIEW

**Comment by lawnjelly** [comment]
Note after discussion, this could be pared back to just a `shrink_to_fit()` method, but leaving it all in as reference, and welcome more bikeshedding on how everyone would prefer to proceed with the area in the two PRs (this and the linked one #64120 ) . :+1: :slightly_smiling_face:

**Comment by Geometror** [comment]
I'm in favor of this approach. (both the ability for exact resizing and shrink_to_fit). 
Could be useful for #64198. IMO this doesn't make the API more complicated.

**Comment by RandomShaper** [comment]
> Note after discussion, this could be pared back to just a `shrink_to_fit()` method, but leaving it all in as reference, and welcome more bikeshedding on how everyone would prefer to proceed with the area in the two PRs (this and the linked one #64120 ) . 👍 🙂

I'd agree with doing that. I see no danger in a parameter-less `shrink_to_fit()` which does exact resizing and then we keep discussing a bit more.

For the records, in case we finally decided to extend `LocalVector`'s API instead of adding a new, compatible container type, I'd rather have an enum so you could write `vector.resize(n, LocalVector::RESIZE_EXACT);`. It's more verbose, but much better for readability. In any case, I think we are reaching some consensus about the more types approach (in the comments is other PR), something which I believe it's better.

**Comment by lawnjelly** [comment]
> For the records, in case we finally decided to extend `LocalVector`'s API instead of adding a new, compatible container type, I'd rather have an enum so you could write `vector.resize(n, LocalVector::RESIZE_EXACT);`. It's more verbose, but much better for readability.

I've added this, with `ALLOC_EXACT` (as it is used for `reserve` and `shrink_to_fit` as well, and the RESIZE_ prefix could be confusing. The only slight annoyance is that we can't really just use `LocalVector::`, because it would require a fully qualified template prefix, which would be cumbersome to use. So I've created a stub class `LocalVectorT` to hold the enum.

> In any case, I think we are reaching some consensus about the more types approach (in the comments is other PR), something which I believe is better.

Myself and @Geometror seem to be of the opinion that having exact sizing available in `LocalVector` would be the most overall useful approach - as it covers every scenario.

Having said that, I wouldn't be against the idea of an extra new container that enforced a fixed size (I can see the value of preventing resizing of say, a super expensive object, or using templated fixed size array rather than dynamic allocation), but would see it ideally as addition to the base functionality in `LocalVector`, rather than a replacement.

**Comment by RandomShaper** [comment]
I think we need more eyes looking into this, so more mouths giving opinions.

For my part, I feel that having a super flexible container plus a subset of its features in another would be awkward.

**Comment by RandomShaper** [comment]
Also: https://github.com/godotengine/godot-proposals/issues/5144

**Comment by lawnjelly** [comment]
I'll leave this archived for reference, @reduz is currently of opinion to leave `LocalVector`.

> lawnjelly to be honest, for performance reasons, I feel more inclined to leave LocalVector as is, since in far most cases it just does what it has to do
the use cases are generally very specific, and shrink_to_fit is IMO quite pointless in real life

**Pull request closed without merging**
