### PR TITLE
3d shapes

### PR DESCRIPTION
**Pull request by linusheck**
This is documentation for Shape, RayShape, SphereShape (pretty basic, but I'm learning how to do this). I got "inspiration" from the 2D classes and the other 3D shapes for this. Sorry for the two commits that have the same name, up-arrow-mistype.

### CODE REVIEW

**Comment by akien-mga** [comment]
It would be nice if you could squash the commits into one, see the related doc: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by glatteis** [comment]
The text error that should open when I type git rebase -i HEAD~4 doesn't work on CMD and PowerShell and is a broken VIM on Cygwin :(

**Comment by akien-mga** [comment]
Try `GIT_EDITOR=notepad.exe git rebase -i HEAD~4`.

**Comment by glatteis** [comment]
Had luck with this command:

    git config --global core.editor "'C:/Program Files (x86)/Notepad++/notepad++.exe' -multiInst -notabbar -nosession -noPlugin"

New pull request: https://github.com/godotengine/godot/pull/11511

**Pull request closed without merging**
