### PR TITLE
add controller_number & controller_value to allow printing of all MIDI event data

### PR DESCRIPTION
**Pull request by AlexMitchellMus**

### CODE REVIEW

**Comment by akien-mga** [comment]
Makes sense, but wouldn't it be better as `controller_number` and `controller_value`? That's the name of the properties and `cc` is not immediately obvious as it's never used in Godot's API or documentation for MIDI events.

**Comment by alcomposer** [comment]
CC is an established convention in MIDI. I was also thinking of minimising the amount of room that the message took on the console.

In actuality, `controller` isn't in the spec, it's either `Control Change` or `Continuous Control`.

**Comment by alcomposer** [comment]
I was thinking about reducing the space used in the console, and also that CC is an established MIDI spec concept.

However I take your point.

**Comment by akien-mga** [comment]
Yeah following the spec more closely is a valid change proposal but this would need to be done consistently over the whole API and documentation, so it's outside the scope of this issue (and too late for Godot 4.x as it would break the API).

The docs could be amended to mention CC where relevant though, which would likely be good enough to make the `controller` <> CC relationship clear.

Could you squash the commits (and amend the resulting message to mention the property names)? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by alcomposer** [comment]
Ok now?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
