### PR TITLE
Add a switch to hide the visual shader/script nodes in the docs

### LINKED ISSUE #55267: The problem with VisualShader/VisualScript nodes count
### Godot version

3.4 / 4.0

### System information

W10

### Issue description

Soo this has bothered me for a while, but we have a huge number of exposed classes for VisualShader/VisualScript. Each visual node has its dedicated resource type, which is overkill.

My main problem with this is that each of these nodes can be documented, but no one really bothers to do it and it impacts doc completion. I once made a PR that documented "all" VisualShader nodes, but before it was merged even more nodes were already added.

With VisualScript it's a bit better, because the nodes are edited in the inspector and you can actually see their documentation. But for VisualShader it's not the case; the docs aren't displayed anywhere and also VisualShader editor has its own description for every function. So documenting everything is pointless, but then we end up with empty docs.

Assuming this is a concern, is it maybe possible to unexpose the nodes? They could be internal classes and the actual node (the one saved in the scene) would only hold information about what type it is and and the property list would depend on that. This way we could have single class for VisualScript/VisualShader, so the class ref isn't so cluttered.

### Steps to reproduce

Just look at this
4mojLMKP2G

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
Alternative to https://github.com/godotengine/godot/pull/55993 (fix #55267) which does not add a special tag to classes but just uses a pre-defined array to compare.

hide_doc_items

### CODE REVIEW

**Comment by fire** [comment]
Would it be better to change "Hidden Items" to be "Show All Items"? The request is to make the boolean positive.

**Comment by fire540** [comment]
Would it make sense to also include the "GLTF..." resource classes here? They're undocumented and they don't appear to have any use outside of the GLTF importer and exporter.

146586863-76ce022f-cda6-4fb4-91eb-2713c81c75fe

**Comment by Chaosus** [comment]
> I guess you wanted the default to be true so "Show Default Items"?

No, I wanted it to be false

**Comment by groud** [comment]
I don't really like the idea of adding a switch there. As the problem is mainly in the tree view, and less in the list view (IMO) I think a better solution would be to simply make the `VisualShaderNode` class collapsed by default, instead of expanding it automatically like others.

**Pull request closed without merging**
