### PR TITLE
Restore cubemaps in visual shaders

### PR DESCRIPTION
**Pull request by Chaosus**

### CODE REVIEW

**Comment by aaronfranke** [comment]
Will the casing eventually be changed back to `CubeMap`?

**Comment by Chaosus** [comment]
If users asked for that then yes..

**Comment by akien-mga** [comment]
I guess it was changed on purpose.

**Comment by Chaosus** [comment]
Cubemap was created by Juan, it seems like more strict binding for classDB was implemented recently.

**Comment by akien-mga** [comment]
It was renamed as part of 3f335ce3d446372eeb9ed87f7e117099c4d2dd6a.

**Comment by Chaosus** [comment]
Ah, then it seems incorrect - I think I should rename it back!

**Comment by akien-mga** [comment]
> Ah, then it incorrect - I think I should rename it back!

No... All `*CubeMap*` classes were renamed to `*Cubemap*`.

**Comment by Chaosus** [comment]
Ah, ok..

**Pull request merged**
