### PR TITLE
Expose `String.SimplifyPath` in C#

### PR DESCRIPTION
**Pull request by raulsntos**
Follow up to #52041 in C#

### CODE REVIEW

**Comment by neikeq** [comment]
Not sure if a custom implementation is worth it compared to an internal call. We will have to make sure it's kept in sync with the original one if there are changes. The downside of the internal call is we have to copy the string into a native one. Would be worth checking if this makes a big difference.

**Comment by Calinou** [comment]
I agree that performing an internal call is likely the better solution here. `simplify_path()` is very unlikely to be used often enough to cause performance issues.

**Review by neikeq — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
