### PR TITLE
Expose `NOTIFICATION_EXTENSION_RELOADED` to `ClassDB`

### PR DESCRIPTION
**Pull request by EterDelta**
Currently, the extensions reload notification lacks of ClassDB binding in the Object class.
This prevents it from being generated in the bindings, which doesn't make sense since it was introduced to be used by extensions in the first place. (https://github.com/godotengine/godot/pull/80284#issuecomment-1732641407)

Something that stands out in that discussion is whether it should be removed, as there are no _real world use cases_.
But in fact there are! We can take a look at how **engine classes** like [Bone2d](https://github.com/godotengine/godot/blob/9adb7c7d130c6d4eb0e80b92d6eebd71fac3384d/scene/2d/skeleton_2d.cpp) cache parent pointers when entering the tree. These cached pointers are also used for **editor** tasks, like configuring warnings.
This would be imposible without the reload notification in an extension, as everytime we hot reload, the pointers become dangling, causing us to lose track of whatever we were pointing to in the editor.

### CODE REVIEW

**Comment by dsnopek** [comment]
Yes, I agree this should be exposed!

I'd mark it as approved, but it looks like it needs a docs update to pass CI.

**Comment by Mickeon** [comment]
Right off the bat, while exposing it is probably a good idea, it being among both **NOTIFICATION_POSTINITIALIZE** and **NOTIFICATION_PREDELETE** definitely stands out like a sore thumb... It is useful, but it is not useful every day, so to speak? I'm a bit wary of that.

If it is agreed that exposing the constant is fine, then I would see no reason to keep **NOTIFICATION_PREDELETE_CLEANUP** hidden, either.

**Comment by dsnopek** [comment]
In this case, `NOTIFICATION_EXTENSION_RELOADED` is meant to be used by GDExtensions, but the code generation used in most (all?) GDExtension bindings won't know to generate if it's not exposed. I suppose they can still use it by referring to the integer value? In any case, the point I'm trying to make is that this was added _in order_ to be exposed to GDExtension, there's no use for it in core itself :-)

**Review by Mickeon — APPROVED** [review]
I see, well... In that case it's fine. I just wish we didn't have to document it in full display like this.
Autocompletion would always show it, even if it can really only be used for GDExtension. It's among a few things that contribute to bloat.

It could be defined in the GDExtension class, couldn't it? ProjectSettings does something similar.

**Review by dsnopek — APPROVED** [review]

**Comment by dsnopek** [comment]
> It could be defined in the GDExtension class, couldn't it? ProjectSettings does something similar.

Do you have a reference to the ProjectSettings thing?

We could manually define it in godot-cpp without exposing it. But that won't help any of the other bindings, they'd all have to manually define it too (whereas exposing it the normal way it'll just get picked up by the code generation).

**Comment by EterDelta** [comment]
I mean, its usage can extend beyond  _just GDExtension_. 🤔
As I wrote in the doc, derived classes also get notified, that includes **scripts**.
So, maybe tool scripts that extend extensions classes could implement some custom synchronization that needs to be notified each time the parent reloads.

**Comment by Mickeon** [comment]
> Do you have a reference to the ProjectSettings thing?

Sorry, I actually meant **EditorSettings**. Important distinction

What I do mean is, just because it is received by every **Object** does not mean it needs to be defined in **Object**. **EditorSettings** notifies **NOTIFICATION_EDITOR_SETTINGS_CHANGED** to everything in the tree, and editor nodes answer accordingly. For example:
https://github.com/godotengine/godot/blob/9adb7c7d130c6d4eb0e80b92d6eebd71fac3384d/editor/project_manager.cpp#L107-L112

**Comment by dsnopek** [comment]
Hm. Well, I guess we could do that. Personally, I prefer having it on `Object` because I feel like GDExtension is very much a part of `Object`, however, I'm clearly biased. :-) I'll defer to whatever the @godotengine/core team thinks is best!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Makes sense to me that it's exposed in `Object`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
