### PR TITLE
Proposed fix for volume ramp based fade-in cutting off the beginning of sounds

### LINKED ISSUE #66452: Godot 4 - Audio clips have their beginning cut off
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10, Vulkan, NVidia RTX 2070 Super

### Issue description

In Godot 4, some audio clips sound incorrect in engine for me; it sounds like the start is being cut off. I've tried both .ogg and .wav files and it happens with both, I've tried tweaking the import settings on the sound to no effect, and I've tried an identical setup in Godot 3.4.2 and the issue does not occur.

Here's a video comparing the original sound file, the sound in Godot 4, and the sound in Godot 3. You can hear that in Godot 4 the sound file sounds less "sharp" at the beginning as it does in the original file and Godot 3. Both these projects were created with no changes made to any settings.

https://user-images.githubusercontent.com/3895119/192319165-d8c13f8f-4ce7-4a0c-a10f-9e494e10ac65.mp4

### Steps to reproduce

1. Create a new project in Godot 4
2. Import a short sound like the one I used (It's most noticeable on very short 8-bit style sounds)
3. Play through the preview or through an AudioStreamPlayer and compare with the original sound file

### Minimal reproduction project

Godot 4.0 beta project: 
[Soundtest.zip](https://github.com/godotengine/godot/files/9647648/Soundtest.zip)

Godot 3.4.2 project:
[Soundtest3.zip](https://github.com/godotengine/godot/files/9647650/Soundtest3.zip)

### PR DESCRIPTION
**Pull request by ellenhp**
Proposed fix for #66452. Implements an explicit fade-in based on the same exponential method used for fade-out.

*Bugsquad edit:*
- Fixes #66452

### CODE REVIEW

**Comment by reduz** [comment]
I don't think this is a good idea, and you don't want to do this universally. Many times there are sounds with high transient and the fade in will muffle them. Additionally, doing it in the audio server is also a bad idea because in many places the mixing happens at later places in the stream (as example, interactive music).

I would approach this problem a bit different.

* For MP3 and OGG, check the beginning and the end of the sounds to see if they begin at DC or there is some significant offset.
* If this is the case, store flags that ramping is needed on fade in and fade out.
* Apply this fade in only for those streams. Fade out only if they don't loop.
* For wav, this fade can be done directly in the audio data on import.

**Comment by ellenhp** [comment]
There's a linear volume ramp over the entire 512 sample mixing window right now. This PR reduces that to a 64 sample exponential ramp-up. Whether we want to remove fade-ins entirely or do them for only some playbacks is another question, but I'd be opposed to doing it selectively for complexity reasons, and doing so is pretty complex because sometimes you don't play from the very beginning of an audio track.

**Comment by reduz** [comment]
@ellenhp then the linear volume ramp is also wrong and should be fixed, we should never force ramp out audio when it starts, this is not the right approach.

**Comment by ellenhp** [comment]
What about for seeks? You can't ensure that the arbitrary position in the file is at a zero crossing so it might make sense there. Removing this is a very easy fix though so I'm not necessarily opposed as long as we're okay with pops on `$Player.play(x)`

**Comment by reduz** [comment]
@ellenhp Again, all this should be taken care at stream level, not at audio server level. AudioServer lacks the context to do any sort of fixing for this, so ramping in is a hack.

**Comment by reduz** [comment]
We don't need to have pops on play if we fix this at stream level as I described above, and we should only actually apply ramp if there _is_ a need to ramp (stream begins/ends at DC != 0). If there is not, then we should not ramp else we muffle transients unnecessarily.

**Comment by ellenhp** [comment]
Okay, I'll remove this after I'm done with https://github.com/godotengine/godot/issues/64775.

**Comment by ellenhp** [comment]
Also I just want to confirm that it's okay to keep fade-out in the audio server? Right now it happens unconditionally over 64 samples, same as this PR.

**Comment by bluenote10** [comment]
> Also I just want to confirm that it's okay to keep fade-out in the audio server? Right now it happens unconditionally over 64 samples, same as this PR.

Good question. I was wondering about that as well. My first impression was that the notion of the lookahead buffer makes the logic in the audio server more complex than it needs to be. There is also a performance penalty for use cases that don't require fade out at all. Basically the lookahead buffer needs to be copied twice per mix step ([first here](https://github.com/godotengine/godot/blob/master/servers/audio_server.cpp#L346-L348) and [then here](https://github.com/godotengine/godot/blob/27b2260460ab478707d884a16429add5bb3375f1/servers/audio_server.cpp#L373-L375)). Copying 2 x 64 samples over isn't much, for unnecessary overhead for streams that are playing constantly.

My gut feeling is similar to what @reduz suggests and solve such things at the stream level and keep the audio server as simple (and performant!) as possible.

**Comment by ellenhp** [comment]
I forgot to respond to you @bluenote10 but that will cause pops when a player is removed from the tree without being stopped at least one mix before that. This is a bug we fixed for 4.x. I've spent literally hundreds of hours designing and implementing the 4.x audio system and I've put a lot of thought into it. It hurts on a very visceral level when people talk about undoing or reverting major parts of it in ways that will introduce bugs that I will be unable to fix.

**Pull request closed without merging**
