### PR TITLE
[WIP]is_debugger_present method

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds is_debugger_present method. is_debugger_present method provides basic debugger detection. Now implemented for windows platform. 

A little demo
[isdebugger.zip](https://github.com/godotengine/godot/files/3702826/isdebugger.zip)

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Should be documented and stated that it only works on Windows currently.

**Comment by vnen** [comment]
1. What is this useful for?
2. The name should be more explicit that is the engine code being debugged. It can be confused with the script debugger.

**Comment by ibrakap** [comment]
@YeldhamDev I will write a documentation about that method.

**Comment by ibrakap** [comment]
@vnen 
1-It's useful for third party debugger detection. A developer might want detect third party debugger for not allowed code modifications.

2- Yes you are right. Method name is not explicit. Can you give any advice for method name? It ignores script debugger. It detects third party debugger.

Thanks for all opinions.

**Comment by Calinou** [comment]
> A developer might want detect third party debugger for not allowed code modifications.

I see many issues with this…

1. How difficult is it to circumvent this?
2. Do macOS and Linux have reliable ways to detect this?

I'm generally wary of adding "protection tools" to an open source engine like Godot, because it tends to go against its philosophy and can give false hopes to people.

**Comment by ibrakap** [comment]
1- Yes it's bypassable. But it's might useful for some cases.
2- I don't have development experience with linux and osx.

**Comment by akien-mga** [comment]
The use case is not so clear, we'd need explicit examples and not just a statement that "it might be useful". If we do add it, it should also be added for other platforms where it's relevant - that can be done by other interested contributors though.

All in all, this should likely go through the godot-proposals process at https://github.com/godotengine/godot-proposals, so that we can discuss the proposed addition, its use cases and whether we think it useful in Godot.

**Comment by akien-mga** [comment]
Closing for now as per above comments, I think this needs to go through the godot-proposals workflow before further review of code changes.

**Pull request closed without merging**
