### PR TITLE
Fix WebSocketMultiplayerPeer server crash when a client tries to connect.

### LINKED ISSUE #73810: WebSocketMultiplayerPeer server crashes if it's configured with a TLS certificate.
### Godot version

4.0.dev

### System information

Windows 10

### Issue description

If a WebSocketMultiplayerPeer server is configured with a TLS certificate, the program crashes whenever a client tries to connect.
I don't get any error messages (which is driving me crazy)

I tried with a self-signed (in Godot) certificate and a properly signed Let's Encrypt certificate, but same results.

### Steps to reproduce

1. Configure a WebSocketMultiplayerPeer server with a TLS certificate
2. Try to connect to the server

### Minimal reproduction project

[test_client.zip](https://github.com/godotengine/godot/files/10812125/test_client.zip)
[test_server.zip](https://github.com/godotengine/godot/files/10812126/test_server.zip)

### PR DESCRIPTION
**Pull request by Vsono**
Fixes #73810
I believe this one line change resolves the problem.

I get no problems after the change.

### CODE REVIEW

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by Vsono** [comment]
> For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.
> 
> _Edit:_ You actually have an empty email configured in your local Git config, so this commit can't be attributed to anyone: https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/73811.patch

I haven't noticed that until now, thank you
What do I need to do after configuring the user name and email?
Should I fork and commit again?

Sorry for bothering you

**Comment by akien-mga** [comment]
You should be able to fix the commit in your current branch with:
```
git commit --amend --reset-author
```
And then update the PR with:
```
git push --force
```

**Review by Faless — APPROVED** [review]
LGTM :+1:

**Comment by Vsono** [comment]
> You should be able to fix the commit in your current branch with:
> 
> ```
> git commit --amend --reset-author
> ```
> 
> And then update the PR with:
> 
> ```
> git push --force
> ```

Thank you :)

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
