### PR TITLE
No need for "raised_from_completion", and fix #22504 and #16064

### LINKED ISSUE #16064: "Saving Scene" loading dialog appears behind the code editor sometimes
**Godot version:**
 0181681

**Issue description:**
When saving a scene while having the code editor active, it can happen that the "Saving Scene" loading dialog will appear behind it.

### LINKED ISSUE #22504: Tooltip under editor when autocomplete popup is shown
**Godot version:** 3.0.6 Stable

**OS/device including version:** KDE neon 5.13.5

**Issue description:** When autocomplete popup is shown the tooltip is displayed behind the editor window.
image

**Steps to reproduce:** Make the autocomplete to show in the editor and hover over anything to show a popup and it will be behind the editor.

### PR DESCRIPTION
**Pull request by zhagsenkk**
No need for "raised_from_completion" now.

#1257 will not arise because now the code-autocomplete hint can berth at editor’s side.
#6769 will be fixed cased by "raised_from_completion"(it's exit in the master branch!).see below:

#6690 can't be reappeared.
#22504 will be fixed.

*Bugsquad edit:* Fixes #16064, fixes #22504.

### CODE REVIEW

**Comment by akien-mga** [comment]
The change seems fine to me provided it does not introduce regressions as you mentioned.

However, could you edit the commit log (`git commit --amend` and then force push) to be more explicit? Something like this would be clearer when reading the changelog:
```
Remove no longer necessary "raise_from_completion" in TextEdit

This is no longer needed to fix #1257 and #6690 because <explain why here in a short sentence>.
Fixes #22504.
```

Note the `<explain why here in a short sentence>` in my suggested log; I'm not sure to understand *why* `raise_for_completion` is no longer needed to fix the old bugs.

**Comment by YeldhamDev** [comment]
This will fix #16064 as well.

**Review by 27thLiz — APPROVED** [review]

**Comment by zhagsenkk** [comment]
...I dont know if i do correctly.

**Comment by akien-mga** [comment]
> because the code-autocomplete hint can berth at editor’s edge now.

What do you mean with "berth"?

**Comment by akien-mga** [comment]
> What do you mean with "berth"?

Just tested and I guess you meant that the hint can now *stop* at the edge. There's a small issue from your rebase as you now have 3 commits instead of 1 (see [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for help on rebasing and amending commits), so I'll rebase and merge it manually.

**Comment by akien-mga** [comment]
I used GitHub's "allow edit from maintainers" feature to push a rebase: 67ba4dc

**Pull request merged**
