### PR TITLE
Better pre-selection of search result node in "Create New Node" dialog.

### LINKED ISSUE #26010: Create New Node search inaccurate
**Godot version:**

d9cf780a702b6776cc10eb5b9a2c943a76decd7e

**OS/device including version:**

Arch Linux

**Issue description:**

The search bar in the Create New Node dialogue has some odd predictions sometimes:

image
Expected: DampedSpringJoint2D
Predicted: AudioStreamPlayer2D

image
Expected: CanvasLayer
Predicted: CanvasModulate

image
Expected: Button
Predicted: TouchScreenButton

image
Expected: Tabs, or TabContainer
Predicted: VisibilityEnabler2D

image
Expected: Particles, Particles2D
Predicted: VSeparator

image
Expected: NinePatchRect
Predicted: TabContainer

image
Expected: VisibilityNotifier/2D
Predicted: VisibilityEnabler2D

image
Expected: HScrollBar
Predicted: TouchScreenButton

And so on.  It's usually not a problem, but if you're going fast and not paying attention, you might accidentally get the wrong node added and have to backtrack; if you are paying attention, you wind up having to type in extra characters to get the node you're really looking for.  One would expect, when typing in a particular string, that you'd get the node whose name most closely matches it starting from the beginning, but instead the predictor seems to try to find a match anywhere in the name and returns the first thing it finds that contains all the characters provided; I also assume it favors nodes which match the root node of the scene, though it's common to combine different kinds of nodes together (such as a UI in a 2D scene.)  I think it would be better if the predictor stuck more closely to matching the search criteria from start to end before trying to find other matches.

### PR DESCRIPTION
**Pull request by mbrlabs**
I'm not sure what the reasoning behind the current implementation was, but i think this one is more intuative for the user. 
The suggested selection when searching for a node is now based on the prefix of a node. So for example if i search for "Nine" or "nine" the selection would be "NinePatchRect" rather than "Container" (like in current master).

Edit:
After some more thinking i'm not looking for prefixes now but i'm checking for both substrings and subsequences. The current implementation only searched for subsequences. I also value substrings higher than subsequences.

Fixes #26010

### CODE REVIEW

**Comment by volzhs** [comment]
what about typing "aaa" then?
`ARVRCamera` is selected with current master.
Screenshot_20190625_221015

**Comment by mbrlabs** [comment]
@volzhs right, this needs some improvements. I'm gonna update it later.

**Comment by mbrlabs** [comment]
Alright, i updated my PR. The main problem with the current implementation was, that it only searched for subsequences (see: https://github.com/godotengine/godot/pull/5177 for an explanation) and not at all for simple substrings. For some search terms this resulted in weird results. I changed it, so that the search prefers substrings and falls back to subsequences if no substring is found.
I also now take `preferred_search_result_type` into account which prefers eg. 2D nodes when the root node is a 2D node.
I will post some screenshots soon to issustrate the new behaviour.

**Comment by mbrlabs** [comment]
nine
button
aaa
picker
aaa

Awareness of root node and `preferred_search_result_type`:

visibilitye_2d
visibilitye_3d

**Comment by akien-mga** [comment]
Great work, thanks!

**Pull request merged**
