### PR TITLE
GDScript: lambdas

### PR DESCRIPTION
**Pull request by ghost**
A proposal for lambdas.

Two supported syntax variants:

(1) short form:
```
var f = func x: x + 1
```

(2) long form: 
```
var f = func x:
    return x + 1
```

Note that `return` is implicit with the short form.

Captures are explicit. I propose using `[]`:

```
var f = func x [a, b]:
    return x + a + b
```

There will be discussion about this. Here's my arguments for having explicit captures:

* Getting implicit captures right means breaking various assumptions in the compiler regarding compile orders and dependencies (it's a probably disruptive change)
* Being less magic and more explicit might be more in the general philosophy of GDScript (compare https://github.com/godotengine/godot/pull/15561 vs https://github.com/godotengine/godot/pull/15216)
* With GDScript being a ref-counted, non-gc language, and JS and Python people jumping onto lambdas, automatic captures might do more harm than good. With explicit lambdas it might be much cleaner to separate strong from weak references, as you are encouraged to think about the type of each single capture.

Together with https://github.com/godotengine/godot/pull/16089, this PR could introduce a syntax for weakrefs that is fully transparent:

```
var f = func x [a, weakref b]:
    a.some_method() # a is strong
    if b: # b is weak
        b.my_method()
```

Further notes:

* Lambdas without captures are static functions and thus need no allocation. Lambdas with captures create one instance allocation.
* As this uses a `_call` method internally, this is designed to work together with https://github.com/godotengine/godot/pull/15486. I.e. while with this PR alone you'd need to write `var f = func x: x + 1; f._call(1)`, together with https://github.com/godotengine/godot/pull/15486 you can write `var f = func x: x + 1; f(1)`.

### CODE REVIEW

**Comment by groud** [comment]
Related #12170

**Comment by Noshyaar** [comment]
Also #2704

**Comment by reduz** [comment]
@vnen is doing a GDScript overhaul to add optional typing. Afterwards it should be easier to see how to do lambdas.

**Comment by vnen** [comment]
I would probably be less conservative with this by adding a new type of node in the parser and doing the needed changes in the compiler (and bytecode, if need be). But yeah, lemme finish my optional typing proposal first.

**Comment by akien-mga** [comment]
For of all thanks for working on this and for bringing a working proposal for lambda support in GDScript.

As we discussed together in our IRC meeting on June 20 (http://godot.eska.me/irc-logs/devel/2018-06-20.log from 21:10), this should be added in Godot 3.2 following the GDScript roadmap that we agreed upon: godotengine/godot-roadmap#23.

So I'll close this PR for now, and it will likely be used as reference for finally implementing and merging lambdas in GDScript after the other prerequisites have been done (and gladly by you or with your help :)).

**Pull request closed without merging**
