### PR TITLE
Add `PROPERTY_USAGE_CLASS_IS_BITFIELD` to global scope

### PR DESCRIPTION
**Pull request by TokageItLab**
It is missing and make error in master CI test.

### CODE REVIEW

**Comment by bruvzg** [comment]
> It is missing and make error in master CI test.

It's not the only thing missing, see #62906. (https://github.com/godotengine/godot-cpp/pull/783 shouldn't be merged without #62906 first,  but it was).

**Comment by TokageItLab** [comment]
@bruvzg Ah, okay thanks. I want to merge it ASAP.

**Comment by TokageItLab** [comment]
Superseded by #62906.

**Comment by akien-mga** [comment]
> It's not the only thing missing, see #62906. ([godotengine/godot-cpp#783](https://github.com/godotengine/godot-cpp/pull/783) shouldn't be merged without #62906 first, but it was).

#62906 was failing its godot-cpp build so I merged the other one first. Chicken and egg problem again with our godot-cpp build here.

**Pull request closed without merging**
