### PR TITLE
Fixed issue in TextureAtlas import of images with wrong size.

### LINKED ISSUE #42057: TextureAtlas bug with transparency.
**Godot version:**

Godot_v3.2.2-stable_win64 and Godot_v3.2.2-stable_mono_win64

**OS/device including version:**

Windows 10

**Issue description:**

Attemted to create atlas with small size textures (8x8, 16x8, 24x8)  Godot created atlas with wrong sizes. It's scaled up.
examples with input output:
ball     8x8 -> 9x9
brick 16x8 -> 17x9
paddle 24x8 -> 25x9

below left side is what godot creates, right is what must be created. I filled transparency with black color for readability.
Atlas

**Steps to reproduce:**
1. Open attachment with Godot
2. Follow instuctions -> https://godotengine.org/article/atlas-support-returns-godot-3-2

**Minimal reproduction project:**

[AtlasBug.zip](https://github.com/godotengine/godot/files/5219360/AtlasBug.zip)

### PR DESCRIPTION
**Pull request by dankan1890**
Fix #42057

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, last commit on this code was #39271 (@RandomShaper).

**Comment by akien-mga** [comment]
The fix seems to work fine, and I could reproduce the issue before applying it.

> For the reference, last commit on this code was #39271 (@RandomShaper).

I checked and #39271 did not cause this issue though, it's already present in 3.2.1-stable.

**Comment by RandomShaper** [comment]
I'm not sure this fix is totally correct. I think that if the `<`s are changed to `<=`s, the the `- 1`s applied to `width` and `height - p_offset.y` should be removed, since otherwise the cases where the right and/or bottom edges of the atlas are reached the last 1-pixel row or column would be left transparent.

However, I haven't tested it. and I'm not sure I'll have time reasonably soon. If one of you was able to test it, that'd help.

**Comment by akien-mga** [comment]
> However, I haven't tested it. and I'm not sure I'll have time reasonably soon. If one of you was able to test it, that'd help.

It does solve the problem in #42057, but it would likely be worth testing on more configurations to see how it behaves.

This code is not the easiest to parse and indeed, it seems a good spot for having off-by-one errors here and there which might counterbalance each other.

**Comment by boruok** [comment]
@akien-mga can this PR be merged in **3.x** branch? compiled it with **3.3.3-stable** and it does solve #42057 issue.

**Review by akien-mga — APPROVED** [review]
I've tested that the changes fix the bug last time - couldn't get anyone to review the code change in depth as it probably gives everyone a headache, me included. Let's merge and see if we spot any regression in testing builds.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
