### PR TITLE
Add high quality glow mode (3.x)

### PR DESCRIPTION
**Pull request by Calinou**
This backports the high quality glow mode from the `master` branch. Thanks @clayjohn for the original implementation :slightly_smiling_face:

Previously, during downsample, every second row was ignored. Now, when high-quality is used, we sample two rows at once to ensure that no pixel is missed. It is slower, but looks much better and has a much high stability while moving.

High quality also takes an additional horizontal sample the width of the horizontal blur matches the height of the vertical blur.

This closes https://github.com/godotengine/godot/issues/43110.

### GLES3

| Low quality (default) | High quality |
|-|-|
|  |  |

### GLES2 (Bloom = 1, since there is no HDR)

| Low quality (default) | High quality |
|-|-|
|  |  |

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Fracteed requested this. It is not a risky change and is opt-in so @akien-mga if you are comfortable we could merge this for 3.4

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by RichardR01** [comment]
Btw I hardly notice the difference between low and high, except that high quality seems to blend better. Also it would be nice if we had a tagging system where the glow only effects certain objects. You wouldn't even need a new identifier, you can use the already existing grouping functions. So like if I add "glow" to the group for specific objects, then only those objects would be affected by the post process effect. Even if it can't work exactly like that, an identifier of some sort would be great. (This has been asked before).

**Comment by Calinou** [comment]
> I hardly notice the difference between low and high, except that high quality seems to blend better. Also it would be nice if we had a tagging system where the glow only effects certain objects. You wouldn't even need a new identifier, you can use the already existing grouping functions. So like if I add "glow" to the group for specific objects, then only those objects would be affected by the post process effect. Even if it can't work exactly like that, an identifier of some sort would be great. (This has been asked before).

This can already be done by increasing the glow effect's HDR Threshold property and making your "glowy" objects bright enough. Surfaces darker than the HDR threshold won't generate any glow.

**Pull request merged**
