### PR TITLE
WorkerThreadPool: Revamp interaction with ScriptServer

### LINKED ISSUE #95809: WorkerThreadPool doesn't call `ScriptServer::thread_exit()`
### Tested versions

Godot 4.3 stable

### System information

Windows 10

### Issue description

We are upgrading our Kotlin language binding to Godot 4.3, but the engine doesn't want to close anymore.
Before our embedded JVM can close, it waits for all "attached" threads to be closed. 
We usually attach/detach threads to the JVM using the callback `ScriptServer::thread_enter` / `ScriptServer::thread_exit`.

It seems that a recent change to `WorkerThreadPool` makes all threads call `ScriptServer::thread_enter` (in a delayed manner because the pool is initialized before the `ScriptServer`). The issue seems to be that `ScriptServer::thread_exit` is never called by it before the `ScriptServer` is terminated. Instead, it only happens when the pool threads are deleted as part of the WorkerThreadPool's destructor, which happens in the very last steps of `Main::cleanup`.  
I also can't find any callbacks that would be executed this late either (`MessageQueue` is freed before the pool as well).

I'm not certain that this is the source of our issue but we confirmed that we received more `thread_enter` calls than `thread_exit `calls. So it's either the pool, or some mysterious other thread somewhere in Godot that is not terminated in time.

@RandomShaper 

### Steps to reproduce
-

### Minimal reproduction project (MRP)
-

### LINKED ISSUE #96931: Deadlock when exiting and using Multithreaded renderer
### Tested versions

- Master (anything after 2d1dd41ef5dcb51ddb607ba572e63b605b9191be)
- 4.4 dev2 (does not reproduce)

### System information

Godot v4.4.dev (2d1dd41ef) - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Xe Graphics (TGL GT2) - 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 Threads)

### Issue description

The WorkerThreadPool deadlocks in the `main::cleanup()` function during shutdown. 

This is a regression and I bisected it to 2d1dd41ef5dcb51ddb607ba572e63b605b9191be

https://github.com/godotengine/godot/pull/96760 makes it so the WTP is finalized before the servers have a chance to shut down. When using the MT thread model, the servers yield to the WTP until a command is pushed to them. 

During finalizing, the WTP waits for all threads to finish, this locks the main thread. However, the command to finalize the rendering thread happens after the WTP finalizes. So the main thread gets stuck indefinitely. 

This bug also impacts any other system that creates a long running thread through the WTP and relies on yielding. 

### Steps to reproduce

1. Enabled the Multi thread rendering model
2. Run the project
3. Try to close the project 

### Minimal reproduction project (MRP)

[mt-deadlock.zip](https://github.com/user-attachments/files/16984701/mt-deadlock.zip)

### LINKED ISSUE #96978: Application stops responding upon calling SceneTree.Quit and never really quits
### Tested versions

- Reproducible on v4.4.dev.mono.custom_build [74de05a01c8716a42d4e3427f607d7bea76b35e5] when using Run on Separate Thread for either or both of the physics (2D/3D)

### System information

Windows 11 x64 and Ubuntu 24.04 ARM64

### Issue description

When calling the SceneTree.Quit, instead of correctly quitting the application, instead, the application stops responding and does not actually quit, it stays lingering into an non-responsive state, may it be running from console only or with actual UI, as long as "Run on Separate Thread" is ticked on either of the physics (2D and/or 3D).

### Steps to reproduce
- Enable Run on Separate Thread on project settings
- Simply call SceneTree.Quit

### Minimal reproduction project (MRP)

[mrp-quitbug.zip](https://github.com/user-attachments/files/16999018/mrp-quitbug.zip)

### LINKED ISSUE #97073: Single-threaded Web exports are broken
### Tested versions

- Bisected to #96760
  - **EDIT:** as the PR has two commits, it actually bisects to https://github.com/godotengine/godot/pull/96760/commits/2d1dd41ef5dcb51ddb607ba572e63b605b9191be

### System information

Godot v4.4.dev (2c136e617) - macOS 14.6.1 - Metal (Forward+) - integrated Apple M3 Max (Apple9) - Apple M3 Max (16 Threads)

### Issue description

This errors shows up on non-threaded web exports.

```plain
ERROR: Can't add a group task because the WorkerThreadPool is either not initialized yet or already terminated. [tmp_js_export.js:474:18](http://localhost:8060/tmp_js_export.js)
   at: _add_group_task (core/object/worker_thread_pool.cpp:546) [tmp_js_export.js:474:18](http://localhost:8060/tmp_js_export.js)
```

Capture d’écran, le 2024-09-16 à 08 46 14

### Steps to reproduce

1. Export a web game without thread support
2. See that there's a flood of the described error

### Minimal reproduction project (MRP)

n/a

### PR DESCRIPTION
**Pull request by RandomShaper**
First, this reverts 2d1dd41ef5dcb51ddb607ba572e63b605b9191be from #96760. The approach there is not enough, given that with separate thread rendering, there's a cyclic dependency chain on shutdown:
- `WorkerThreadPool` must finish before `ScriptServer`.
- `RenderingServer` must finish before `WorkerThreadPool`.
- `ScriptServer` must finish before `RenderingServer`.

A way of breaking the cycle, which this PR implements, is splitting `WorkerThreadPool` regular lifetime into ~two~ three🆕 "runlevels":
- One that works as usual.
- One that waits until all the threads are idle, with no more tasks queued, plus adding more tasks blocked (not rejected, just they have to wait). 🆕
- One that also works normally, but where languages have already been terminated.

I've put the pure refactor into its own commit, which would help a lot for bisect and also for easier reviewing.

It should still fix #95809 (CC @CedNaru).

Fixes #96931.
Fixes #96978. 🆕
Fixes #97073. 🆕🆕

---

**Cherry-picking note:** We don't have `MutexLock::temp_unlock()`/`temp_relock()` in 4.3. Therefore, the most recent commit in this PR needs to have the following patch applied:
```diff
diff --git a/core/object/worker_thread_pool.cpp b/core/object/worker_thread_pool.cpp
index 37a605cb10..2f0e3d4c2a 100644
+++ b/core/object/worker_thread_pool.cpp
@@ -233,11 +233,11 @@ void WorkerThreadPool::_post_tasks(Task **p_tasks, uint32_t p_count, bool p_high
        // in custom builds.
        bool process_on_calling_thread = threads.size() == 0;
        if (process_on_calling_thread) {
-               p_lock.temp_unlock();
+               task_mutex.unlock();
                for (uint32_t i = 0; i < p_count; i++) {
                        _process_task(p_tasks[i]);
                }
-               p_lock.temp_relock();
+               task_mutex.lock();
                return;
        }

@@ -576,9 +576,9 @@ bool WorkerThreadPool::_handle_runlevel(ThreadData *p_thread_data, MutexLock<Bin
                } break;
                case RUNLEVEL_EXIT_LANGUAGES: {
                        if (!p_thread_data->exited_languages) {
-                               p_lock.temp_unlock();
+                               task_mutex.unlock();
                                ScriptServer::thread_exit();
-                               p_lock.temp_relock();
+                               task_mutex.lock();
                                p_thread_data->exited_languages = true;
                                runlevel_data.exit_languages.num_exited_threads++;
                                control_cond_var.notify_all();
```

### CODE REVIEW

**Comment by CedNaru** [comment]
Ho so it's not a full revert of the previous PR. We still have the bookkeeping done by the ScriptServer.

My bad, I thought I tested with the multithreaded renderer, but it seems I messed up (Doesn't change that I still tested against the 4.3-stable and confirmed the difference in behaviour).

Otherwise, it seems to be an improvement again. Now the WorkerThreadPool calls thread_exit() directly instead of letting the Thread do it itself, just like with thread_enter().

So if I understand, the order of execution is:
- Godot starts
- WorkThreadPool is initialized before all servers (including ScriptServer and so no `thread_enter()` possible)
- Servers are started, and their loop added as a task to the pool if multithreaded.
- ScriptServer and its languages are initialized.

- Whenever a new task is started by the pool or that a long-running one yields, `thread_enter()` is called if not done yet.

- Godot is closing and cleanup happens.
- WorkThreadPool calls `exit_languages_threads()`, which change the "mode" of the pool. From now, the logic is inverted and any task finishing or yielding will call thread_exit()
- ScriptServer terminates.
- The rest of the server terminate too.
- WorkThreadPool is deleted last.

Now my doubt: What happens if tasks are still queued when we switch to RUNLEVEL_EXIT_LANGUAGES mode. Won't it mean that those tasks will run after `thread_exit()`  was called. The ScriptServer (and its languages) is still up at this point, it's possible the remaining tasks execute code from another language during that short window.

**Comment by clayjohn** [comment]
Testing locally I can confirm that this fixes https://github.com/godotengine/godot/issues/96931

**Comment by RandomShaper** [comment]
@CedNaru, very good assessment. To address the issue about outstanding scripting tasks, I've added a pre-langs-exit runlevel that blocks the addition of new tasks and waits until the queues are empty.

I'm not quite happy with the added complexity even before the last push. For all the reviewers: the new push performs some additional refactoring so the new logic is more self-contained and can be more easily replaced or further unified in the future. I have considered many approaches and this is the only one that would work.

**Comment by CedNaru** [comment]
Indeed, that quite a bit of complexity added to handle the ScriptServer. If I may ask, wouldn't that be possible to revert the logic and make that the ScriptServer, the one with multiple "run levels" instead of the WorkerThreadPool ?
The core of the issue is that threads are started after the ScriptServer, and terminated after the ScriptServer. There are probably a lot of reasons why the ScriptServer has to be initialized last and ended first (I can already think of a few myself), Wouldn't a two-stage (before and after Servers) initialization and termination of the ScriptServer do the trick ?
Sadly, I don't see it being possible without breaking changes to Language (and would probably force languages to register at the core phase at least) but asking anyway.

**Comment by RandomShaper** [comment]
Sounds intriguing, but I'm not sure it'd be worth the hassle at this point. I've simplified a bit the code so the end result is not that daunting and, provided it does the trick and maintainability is good, I'd deem this one worth mergeable. Let's see if CI succeeds now (there was a missing initializer causing logic errors).

**Comment by adamscott** [comment]
Tested out a single-thread export with this PR and it fixes the issues that currently occur on master.

**Review by clayjohn — APPROVED** [review]
Tested locally and confirmed that it is working for the MT servers

**Comment by clayjohn** [comment]
I'm going to go ahead and merge this as we accidentally merged https://github.com/godotengine/godot/pull/95915 first which will introduce the deadlock to many more projects.

**Comment by clayjohn** [comment]
Thank you for the quick turnaround!

**Comment by RandomShaper** [comment]
Added a note about cherry-picking for 4.3 to the main description.

**Pull request merged**
