### PR TITLE
 Move hardcoded theme colors from editor_node into editor_themes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by reduz** [comment]
This is fine where it is, nothing in scene/ uses this. It's used from within editor.

**Comment by rollenrolm** [comment]
though it does overwrite colors in a custom theme set in editorsettings, which is kind of annoying

**Comment by reduz** [comment]
The custom theme overrides these settings because it's set in a child node, so don't worry about checking if these values were overriden

**Comment by rollenrolm** [comment]
So how about this solution? As i already said, those colors override the ones set in a custom theme, which kinda defeats the purpose of a custom theme. :)

**Comment by reduz** [comment]
ah, I see, these are created into the editor theme, not the base theme..
what you could do to fix it is to create these values here:

https://github.com/godotengine/godot/blob/master/tools/editor/editor_themes.cpp#L51

The editor has two themes, the one created using the godot default, and the
custom one it puts on top (so it can use the default one as fallback if
something is missing).
If you put these values in the default section, you should be able to
override them in the custom theme

**Comment by rollenrolm** [comment]
Done. Works fine here. Thanks for the heads up!

**Comment by akien-mga** [comment]
Could you rebase your branch to get rid of all those unnecessary merge commits? Only the last commit should be kept I guess.

**Comment by rollenrolm** [comment]
Rebased only last commit on current master. Thanks @akien-mga for the heads up

**Pull request merged**
