### PR TITLE
Allow Tweens with duration 0 and above

### PR DESCRIPTION
**Pull request by DevinPentecost**
Hi,

This is the change that appears to work to resolve the following issue:
[https://github.com/godotengine/godot/issues/29567](https://github.com/godotengine/godot/issues/29567)

I've built it and confirmed that it works. However I do not know how to run unit tests to confirm it does not break anything else. Additionally, I'd like to add a unit test for this particular condition if possible to make sure it is not broken in the future.

If you could please direct me to how to ensure this fix does not break tests and how to add my own test to this pull request I'd appreciate it.

Thanks,
-Devin

### CODE REVIEW

**Comment by Calinou** [comment]
> However I do not know how to run unit tests to confirm it does not break anything else. Additionally, I'd like to add a unit test for this particular condition if possible to make sure it is not broken in the future.

The short answer is that we don't add unit tests for new features; see discussion in https://github.com/godotengine/godot/issues/2641 :slightly_smiling_face:

**Comment by bojidar-bg** [comment]
There are 5 other instances of `p_duration <= 0` in the same file. Shouldn't they be changed as well?

**Comment by DevinPentecost** [comment]
I think you're absolutely correct. For some reason my search didn't find
them. Let me update later tonight (unless someone else wants to do that
beforehand :) )

Thanks,
-Devin

**Comment by DevinPentecost** [comment]
I added a bunch of comments and did some *light* refactoring...
Hopefully I didn't break too much with it, I'll try to take a look later tonight to verify more

**Comment by DevinPentecost** [comment]
For some reason a comment+whitespace is resolving in a 'bogus' merge conflict. I can't resolve this apparently... any ideas/help?

Thanks,
-Devin

**Comment by DevinPentecost** [comment]
Making a few more fixes, I'll keep working on them over the weekend

**Comment by DevinPentecost** [comment]
Hi,

I think I've done all I intend to do with this PR. Please review the changes.

Thanks!
-Devin

**Comment by Chaosus** [comment]
You need to squash commits together as described in http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase Be careful if you didnt do it before (better test it on one of your local repositories)

**Comment by DevinPentecost** [comment]
Hi,

I'm working on squashing the commits. I may need to reopen the PR with a new branch.

Thanks,
-Devin

**Pull request closed without merging**
