### PR TITLE
[Core] [Mono] Add Vector2i and Vector3i types

### PR DESCRIPTION
**Pull request by aaronfranke**
EDIT: https://github.com/godotengine/godot/issues/16023 should probably be solved first, since this breaks VisualScript compat.

This PR adds Vector2i and Vector3i types internally, to Variant, to GDScript, to VisualScript, and to Mono/C#, and adds docs for them, as well as updating other docs and making some other vector code more consistent.  See https://github.com/godotengine/godot/issues/3286

I, and many others, need this feature. I can always implement my own structs, but it's much nicer if the engine functions can use it and it is available to everyone.

What this PR does not do:

* Add Vector2i or Vector3i to GDnative. I took a peek at the code and it looks like quite a lot of work, so EDIT: See below.

* Use these types anywhere internally (EDIT: anywhere addtionally) (so this PR doesn't close but helps solve https://github.com/godotengine/godot/issues/3286), currently it's just for user code. I'll make another PR after this for using these types internally one this PR is reviewed, accepted, and merged.

Fairly large PR, there are also a few other minor changes to problems that I noticed in here, so please review carefully. Suggested milestone: 4.0.

* EDIT: I would try to implement it, unless of course @karroffel wants to do the GDnative part himself, it seems there are some issues with ABI compatibility? I do wonder if we should strive for maintaining ABI compatibility between minor releases if API compatibility is preserved and all that's needed is a recompile. @karroffel also expressed concern with [this PR](https://github.com/godotengine/godot/pull/20371) and I can imagine that we'd have to yet again be bothered with GDnative ABI issues if we wanted to implement [Vector4](https://github.com/godotengine/godot/issues/20907) and there are probably many other ABI-breaking proposals that I'm not aware of.

### CODE REVIEW

**Comment by karroffel** [comment]
While I very much welcome the PR, the way it is implemented breaks already compiled GDNative libraries. This can be worked around, and that would have to be done when this gets merged, but in the current state it's a breaking change.

**Comment by aaronfranke** [comment]
@karroffel Would it be a better idea for compatibility if the items in the `Variant::Type` enum were given explicit integer values? For example, `NIL = 0`, `VECTOR2 = 100`, or something like that?

**Comment by LikeLakers2** [comment]
After looking at this PR, I'm a little confused. Is this adding Vector2i and Vector3i to GDScript?

And if so, will Vector2i be usable where the parameter type is a Vector2? Or will the function have to explicitly ask for a Vector2i?

**Comment by aaronfranke** [comment]
Yes, it adds it to GDScript (and C#). There might be a way to do implicit conversions but right now I have an explicit `to_vector2()` [method](https://github.com/godotengine/godot/pull/22205/files#diff-b46b143575b088be0d861aa5d91ae805R329), I'd love some feedback from the devs here (I have casts set up in C#).

**Comment by NathanWarden** [comment]
Nice, thanks Aaron :)

I think it would be nice if it followed C# conventions.

int -> float : implicit due to no precision loss
float -> int : explicit due to precision loss

so...

Vector2i -> Vector2 : implicit
Vector2 -> Vector2i : explicit

**Comment by aaronfranke** [comment]
Yep, that's [exactly how I did it](https://github.com/godotengine/godot/pull/22205/files#diff-71338a8a0c674e093da66f7bf1626ce7R333), my only concern is "how do I best do this in GDScript?"

**Comment by aaronfranke** [comment]
Things to fix before merging this:

* In GDScript, these types show up as another color, @vnen what code do I need to change to fix this?



* In VisualScript, the icons for Vector2i and Vector3i don't show up. I can't figure out what I need to do to fix this. Who do I even ping? I saw @fire working on it before. Visual script is not listed in the [CODEOWNERS file](https://github.com/godotengine/godot/blob/master/CODEOWNERS), which itself should probably be fixed, cc @akien-mga.

* What to do about GDNative? @karroffel We can change the code in `variant.h` if that's easiest.

**Comment by fire** [comment]
@aaronfranke https://github.com/godotengine/godot/blob/master/modules/visual_script/visual_script_editor.cpp#L493 for the icons

**Comment by aaronfranke** [comment]
@fire I [added that already](https://github.com/godotengine/godot/pull/22205/commits/1e3cc2345bfc27914b75072d1d88824008e2ce97#diff-bc4de62b8d91eb9cc820c6cce706d8b3R498) and it doesn't show up.

**Comment by fire** [comment]
https://github.com/godotengine/godot/blob/b16c309f82c77d606472c3c721a1857e323a09e7/editor/property_selector.cpp#L168 Try debugging here.

**Comment by fire** [comment]
Look at where set_icon is being done.

**Comment by akien-mga** [comment]
As discussed on IRC, this is a nice change overall, but will have to wait for 4.0 where we can make better use of it consistently through the API.

**Comment by aaronfranke** [comment]
I rebased this on top of master (a few commits not yet pushed), and it builds fine locally, but I'm getting an extremely weird error in Travis. This only shows up with the docs commit pushed, the previous ones pass the Travis checks just fine, and all commits build fine too.

    ERROR: Unresolved member 'length', file: Vector2i

I'm very confused about this, the Vector2i docs have the same fields generated by `--doctool`, and `length` works perfectly fine in a project with this test code:

	var v = Vector2i(1, 2)
	print(v.length())

What would cause the Travis static checks to fail like this?

**Comment by aaronfranke** [comment]
I'm closing this for now. There are just too many conflicts and a few other things that should be solved first, I am 100% confident that some of my other PRs will conflict with this, and the last time I tried rebasing I ended up with a mysterious crash that dumped the stack trace. Plus, I know that there is a plan to close all old PRs sometime soon anyway. It would have been vastly easier if this was merged before the massive refactoring.

Later, when my other pull requests are merged and this can stay in a stable state for more than a week again, we can re-open this - I'll probably just end up redoing the whole thing from scratch.

**Pull request closed without merging**
