### PR TITLE
[4.x] Allow extending MultiplayerPeerExtension from GDScript

### PR DESCRIPTION
**Pull request by dsnopek**
Godot 4 implementation of https://github.com/godotengine/godot-proposals/issues/4873

It looks like the 3.x version (PR https://github.com/godotengine/godot/pull/63163) was just merged!

### CODE REVIEW

**Review by Faless — CHANGES_REQUESTED** [review]
See comments, looks good otherwise :+1: !

**Comment by dsnopek** [comment]
@Faless Thanks! I've made the requested changes :-)

**Review by Faless — APPROVED** [review]
Great work :+1: :trophy:

**Comment by Faless** [comment]
Thanks!

**Pull request merged**
