### PR TITLE
Fix SceneTreeEditor::_update_tree() binding

### LINKED ISSUE #45938: Various signal errors in editor, related to TileMap [3.2.4-rc2]
**Godot version:**
3.2.4.rc2.official

**OS/device including version:**
Ubuntu Linux 20.04

**Issue description:**
In the editor, when loading a scene that contains TileMaps - or adding a TileMap to an existing scene - 9 identical errors are written to the console:

```
 core/object.cpp:1257 - Error calling method from signal 'timeout': 'SceneTreeEditor::_update_tree': Method expected 1 arguments, but called with 0..
```

When deleting a TileMap, this error is printed twice:

```
 Attempt to disconnect a nonexistent connection to signal 'idle_frame' in [SceneTree:1228], with target '_on_workspace_process' in [TileSetEditor:15462].
```

**Steps to reproduce:**
As above.

**Minimal reproduction project:**
n/a

### LINKED ISSUE #45964: Locked nodes don't have a lock icon in the scene tree
**Godot version:**
3.2.4 rc2 and latest master 041cccc28773fe2d832a90888416df106f2a6d79

**OS/device including version:**
Windows 10

**Issue description:**
In the editor you can lock certain nodes, so that they can't be moved by accident (lock icon). Currently when you do this, the lock icon won't show up next to the node in the scene tree unless you save the scene and reopen it. Same goes for the "Make child nodes not selectable" feature. It's a purley visual bug (missing icon in scene tree). The nodes will actually be locked.

This is not happening in RC1.

Capture

**Steps to reproduce:**
- Add a Sprite2D to the scene
- Lock it by clicking on the lock icon in the editor
- It's locked, but there is no icon next to it in the scene tree
- Save the scene and reload it -> now it shows the icon

### LINKED ISSUE #45988: Nodes added via EditorPlugin don't refresh the Scene Dock automatically
**Godot version:**
Godot Engine v3.2.4.rc2.official

**OS/device including version:**
Windows 10

**Issue description:**
When adding nodes to the currently edited scene via a tool script, nodes are not automatically shown in the Scene Dock.  If you click on another node in the Scene Dock, then the added nodes will appear.

Nodes do appear automatically with Godot Engine v3.2.4.rc1.official, so I believe this is a recent regression.

Behavior in RC1:

https://user-images.githubusercontent.com/1929107/107864626-fc856780-6e12-11eb-8ea4-2618ff0895fa.mp4

Behavior in RC2:

https://user-images.githubusercontent.com/1929107/107864630-04450c00-6e13-11eb-9ecd-961cbc7a154c.mp4

Code used to add nodes:
``` gdscript
var node := scene.instance(PackedScene.GEN_EDIT_STATE_INSTANCE if Engine.editor_hint else PackedScene.GEN_EDIT_STATE_DISABLED);
node.name = palette.get_item_name(item_id);

var spatial := node as Spatial;
if spatial:
        spatial.translation = get_global_cell_position(coordinate);

self.add_child(node, true);

# Climb the nodes above us, looking for an owner to attach to.
var parent: Node = self;
while parent:
        if parent.owner:
	        node.owner = parent.owner;
	        break;
        parent = parent.get_parent();
```

**Steps to reproduce:**
1. Download the reproduction project linked below and open it in RC2.
2. Select the "SceneMap" control.
3. Select "Floor" in the right hand dock.
4. Left click in the scene to paint tiles.

**Minimal reproduction project:**
https://github.com/DarkKilauea/godot-scene-map/tree/361d3ef90c067c1102a477a8362a49f15c9c7a75

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #45964.
Fixes #45938.
Fixes #45988.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by mbrlabs** [comment]
@RandomShaper This does not seem to have fixed #45964 entirely. I'm still able to reproducte it in rc3 if the node in question is hidden. If it's not hidden it works however.

**Comment by RandomShaper** [comment]
I can reproduce in 3.2.4-rc3, but not on the latest 3.2 branch.

**Comment by mbrlabs** [comment]
Ah nevermind, i just realized this is also in 3.2.3. If a node is hidden you apparently can't lock it.

**Pull request merged**
