### PR TITLE
Clean up EditorFileSystem script parsing

### PR DESCRIPTION
**Pull request by reduz**
* Optimize only update modified/added/removed files.
* Clean up documentation parsing.

### CODE REVIEW

**Comment by adamscott** [comment]
`ScriptLanguage::get_global_class_name()` doesn't seem to be called by your new code. How does it make sure that a script loaded is meant to be global?

**Comment by reduz** [comment]
@adamscott this has been scanned and cached in the EditorFileSystemDirectory structure above during the scan.

**Comment by adamscott** [comment]
Looks good to me!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
