### PR TITLE
Remove Request Docs button in the script editor due to various issues

### PR DESCRIPTION
**Pull request by Calinou**
The Request Docs button is partly responsible for layout overflow issues on narrow displays, such as #31133.

It also tended to attract spam and low-effort issues that were difficult to act upon. The call-to-action we have on missing property descriptions is probably sufficient for now.

### CODE REVIEW

**Comment by akien-mga** [comment]
I tend to agree with that removal for the sole reason that it takes too much horizontal space.

Still, we do need to make the godot-docs repo and its issue tracker discoverable for engine users, so an alternative might be needed.

**Comment by akien-mga** [comment]
Some very low quality issues that I assume might be the result of the "Request Docs" button:

- https://github.com/godotengine/godot-docs/issues/3068
- https://github.com/godotengine/godot-docs/issues/3085
- https://github.com/godotengine/godot-docs/issues/3110
- https://github.com/godotengine/godot-docs/issues/3218
- https://github.com/godotengine/godot-docs/issues/3227
- https://github.com/godotengine/godot-docs/issues/3233
- https://github.com/godotengine/godot-docs/issues/3245
- https://github.com/godotengine/godot-docs/issues/3253
- https://github.com/godotengine/godot-docs/issues/3256

I think that's evidence enough that this button is not a good solution as is.

**Comment by akien-mga** [comment]
Can be merged after a rebase.

> Still, we do need to make the godot-docs repo and its issue tracker discoverable for engine users, so an alternative might be needed.

Can you add a link to the docs tracker in the Help menu? Maybe rename the current "Issue Tracker" to "Report a Bug", and add the docs tracker as e.g. "Docs Feedback"? Not the best name, but not sure what to use.

**Comment by pycbouh** [comment]
Since we are adding things to "Help", maybe proposals repo should be mentioned as well?

**Comment by akien-mga** [comment]
Bump :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
