### PR TITLE
Add editor icons for all AudioStream resources

### PR DESCRIPTION
**Pull request by Calinou**
Follow-up to https://github.com/godotengine/godot/pull/62250.

## Preview

image

### CODE REVIEW

**Comment by akien-mga** [comment]
The mic icon shows much bigger in the GitHub preview, I assume its internal size wasn't set to 16x16?
image

**Comment by Calinou** [comment]
> The mic icon shows much bigger in the GitHub preview, I assume its internal size wasn't set to 16x16? image

I used another editor node/resource icon SVG as a base, but I don't remember which one. I'm not sure why some of them had their base size changed.

**Comment by Calinou** [comment]
I double-checked `AudioStreamMicrophone.svg` in Inkscape. Its document and viewbox dimensions are correct:

image

I don't know why browsers show it much larger compared to other icons (this occurs even when **View raw** is selected in GitHub's file dropdown).

**Comment by nathanfranke** [comment]
Looks like the root tag doesn't have width or height set. Not sure what this actually equates to in Inkscape for example, but that's probably the cause for different rendering in browser. I wouldn't worry about it too much, maybe in a future PR we can run all the SVGs through some program that makes them all the same format.

other `<svg height="16" viewBox="0 0 16 16" width="16" ...>`
microphone `<svg viewBox="0 0 16 16" ...>`

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
