### PR TITLE
[dotnet6 branch] Move runtime_interop P/Invoke to function pointers

### PR DESCRIPTION
**Pull request by raulsntos**
- Moves runtime_interop methods to UnmanagedCallbacks struct that contains the methods as function pointers and is passed to C#.
- Implements UnmanagedCallbacksGenerator, a C# source generator that generates the UnmanagedCallbacks struct in C# and the body for the NativeFuncs methods (their implementation just calls the function pointer in the UnmanagedCallbacks).

The purpose of moving to function pointers is being able to call these methods when Godot is compiled with `target=release_debug`.

For convenience these are the files output by the source generator:
[Godot.SourceGenerators.UnmanagedCallbacksGenerator.zip](https://github.com/godotengine/godot/files/8367145/Godot.SourceGenerators.UnmanagedCallbacksGenerator.zip)

**TODO:**
- [ ] We have the same problem in [`GodotTools.Internals.Internal`](https://github.com/godotengine/godot/blob/8b85bc71595e1b95f66857d13a6558d492505927/modules/mono/editor/GodotTools/GodotTools/Internals/Internal.cs). I guess we'll want to use the source generator there too.
- [x] ~Methods that have a parameter of type `DebuggingUtils.godot_stack_info_vector` can't be generated because it's not one of the GodotInteropStructs and it's a `ref struct` so I can't use Unsafe or CustomUnsafe to get the pointer.~ These methods are now generated using by-ref parameters or copying to the stack so no need to convert to pointer.
- [ ] I created a separate `Godot.SourceGenerators` project for the `GodotSharp` assembly since we only want to run this generator and not the others but I should probably move this generator to the original `Godot.SourceGenerators` assembly. Alternatively we can have separate source generators projects for `GodotSharp` and for user projects that could share common code with a shared library.
- [ ] `out` parameters are assigned `default`, otherwise the compiler complains that they are not assigned before leaving the method. Can we really avoid this?

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
[#warning TODO hot-reload](https://github.com/godotengine/godot/blob/75471075750bd5028791dd03553791dc45b045db/modules/mono/mono_gd/gd_mono.cpp#L525)

Cause compiling problem as [discussed](https://gist.github.com/lewiji/2b86f47dcb142a10e104504a343c38ff?permalink_comment_id=4105157#gistcomment-4105157).

**Comment by raulsntos** [comment]
@GeorgeS2019 I'm aware of this. This PR intends to solve a different problem. I didn't want to fix the warnings in this one because it was getting big enough already as it is.

**Comment by GeorgeS2019** [comment]
@raulsntos  A quick feedback, I tried introduced the changes and it builds without problem for Windows MSVC.

**Comment by neikeq** [comment]
Superseded by #64089 (I cherry-picked your changes there with some modifications)

**Pull request closed without merging**
