### PR TITLE
Support CSGBox3D conversion of width/height/depth in 3 to size in 4

### LINKED ISSUE #66420: CSGBox sizing is reset to (1,1,1) when updating project from 3.5 to 4.0.beta1
### Godot version

4.0.beta1

### System information

Windows 10, Vulkan, Nvidia 2070 Super

### Issue description

When import and updating a project from 3.5 to 4.0, all CSGBoxes are resized to (1,1,1)
image
image

### Steps to reproduce

1. Create a new project in Godot 3
2. add CSGBox, resize box to something other than (1,1,1)
3. Import and update project to 4.0.beta1
4. all CSGBox sizes will be reset to (1,1,1)

### Minimal reproduction project

[csg demo.zip](https://github.com/godotengine/godot/files/9641924/csg.demo.zip)

### PR DESCRIPTION
**Pull request by GK-GreyGhost**
- Fixes https://github.com/godotengine/godot/issues/66420

I think I did everything correctly from https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#doc-pr-workflow and 
https://github.com/godotengine/godot/blob/84f2c68c84bde10026454292578e5fdcc9ab69a3/CONTRIBUTING.md

this has been tested and works on windows 10, I don't have the capabilities to test on other platforms at the moment

very excited and nervous for my first pull request, please let me know if I did anything wrong

Thank you,
Harrison

### CODE REVIEW

**Comment by fire** [comment]
Hi, we have a #new-contributors channel on rocketchat and please read the https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html.

**Comment by GK-GreyGhost** [comment]
whoops, I thought I was amending correctly, that is the guide I was using, I will squash them now, thank you 👍

**Comment by GK-GreyGhost** [comment]
I fear I have broken the branch irreparably, I have been reading guides for a few hours now and am not experienced enough in git to fix it, I don't want to waste anymore of anyone else's time, I think I should just close the pull request?

**Comment by akien-mga** [comment]
Sorry for the delay. This looks good to me, I rebased the PR to make sure it still builds and passes tests.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by GK-GreyGhost** [comment]
Thank you so much for helping me make my first open source contribution! I'm excited to contribute more 😁🥂🎉

**Pull request merged**
