### PR TITLE
Packed*Array Custom Sort and Search

### PR DESCRIPTION
**Pull request by mashumafi**
Adding `sort_custom` and `bsearch_custom` to `Packed*Array` classes. This is a follow-up of #52850.

Added some tests that uses `Callable` to check that the whole stack works out. Updated docs as well with unique examples.

The goal here is to get `Packed*Array` to be on par with `Array` so that `Array` doesn't have to be the go-to option because it currently supports more functionality.

### CODE REVIEW

**Comment by Calinou** [comment]
@mashumafi Did you mean to close this pull request, or was that a mistake?

**Comment by mashumafi** [comment]
I think it was a mistake on my part, I can take a look and get this ready for review. I think there maybe some conflicts with merging it.

**Comment by mashumafi** [comment]
Yeah this is good to go actually. I think it was meant to fix the conflicts of https://github.com/godotengine/godot/pull/53413. I think the only issue is that the commits are not squashed.

**Comment by mashumafi** [comment]
Actually sorry for the confusion. I am going to close both of these PRs and do smaller ones.

**Pull request closed without merging**
