### PR TITLE
Add preload() to resource path when holding Ctrl

### LINKED ISSUE #2786: Add preload() to resource path when dropping into script editor and holding Ctrl
### Describe the project you are working on
Game using GDScript.

### Describe the problem or limitation you are having in your project
I noticed that whenever I drop a resource into script editor, I usually want to preload it. Autocompletion for preload sucks, I never use it, so I'm just dropping files. It's a bit inconvenient though. To preload a resource, you need to type `preload(` then drop file at the caret and type `)`.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
We could add an optional modifier which when held would automatically wrap the dropped file path in `preload()`.
(we don't need the same for `load()`, because the path is constant and `preload()` > `load()`)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Drop

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It's about convenience.

### Is there a reason why this should be core and not an add-on in the asset library?
Not really possible as an addon right now.

### PR DESCRIPTION
**Pull request by KoBeWi**
Drop

Closes https://github.com/godotengine/godot-proposals/issues/2786

### CODE REVIEW

**Comment by EricEzaM** [comment]
If you do this with multiple files it will end up with a syntax error, `preload("file1", "file2", "file3")`
Could ignore this functionality when multiple files are selected, or make it insert preloads for each file...?

**Comment by KoBeWi** [comment]
Changed the logic a bit to support multiple files:
6CzadHtr92
Might be useful for making resource arrays.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
