### PR TITLE
Optimize member access with self

### LINKED ISSUE #5404: Huge performance or scene start-up hit when using `self.` in nested for loops
Ubuntu 16.04 - Godot vs. 2.0.3.stable.official

**Issue description** (what happened, and what was expected):
When using `self.` in nested for loops it decreases performance dramatically (on the order of x100 to x1000 or so - time of execution). You'll notice that with `self.`, the time to execute the scene dramatically increases. It might not even be performance issue but just some bug related to the nested for loops because it takes a while to initialize and start the scene, not really to execute the script now that I think about it.

**Steps to reproduce:**
Make for loops (maybe only for nested for loops?!) and access a variable with `self.`.

**Link to minimal example project** (optional but very welcome):
I've uploaded a project file demonstrating the issue with comment in `map.gd` script where it makes the difference.
[godot_debug.zip](https://github.com/godotengine/godot/files/332930/godot_debug.zip)

It's a pity cause I really like using `self.` because it's more explicit and I'm an adept of the philosophy of code readability (over conciseness). Hope this is particular only to these for loops...

### PR DESCRIPTION
**Pull request by RandomShaper**
Let the compiler take the fast path when a member is superfluously accessed with `self.`.

Apparently fixes #5404, but in that case this is only masking the underlying issue.

### CODE REVIEW

**Comment by RandomShaper** [comment]
I've tried to cover all cases. For instance, when the member has a getter the fast path won't be taken.

Nonetheless, it'd be nice anyone familiar with the internals had a look.

**Comment by reduz** [comment]
Originally I thought that leaving self to use the slow path makes more
sense because you can do stuff like:

1) Accessing variables of stuff higher in the hierarchy
2) let the setget properties execute when modifying the member (something
that does not happen if you don't use self)

But I'm not really sure if this is the right way, as a lot of people seems
to like using self, even though it's not necessary, this PR probably makes
more sense to merge.
Let me give it a check once I have a bit of time before merging

**Comment by reduz** [comment]
maybe it makes more sense to simply detect if the local member exists and
use the fast path, so at least we solve the limitation of 1)

**Comment by RandomShaper** [comment]
Since a code snippet is worth a thousand words:
```
extends Node

class A:
	var x1 = 1001
	var x2 = 2002 setget set_x2, get_x2
	
	func get_x2():
		print("getting x2 via getter")
		return x2
	
	func set_x2(new_x2):
		print("setting x2 via setter to ", new_x2)
		x2 = new_x2

class B extends A:
	func work():
		print(self.x1)
		print(x1)
		x2 = 3003
		print(x2)
		self.x2 = 4004
		print(self.x2)

func _ready():
	var b = B.new()
	b.work()
```

With the PR merged and a `print_line()` when the fast path is enforced by it:
```
[...] // Trim a lot of now faster accesses to _perm (and one to repeat)
Force fast for x1
1001
1001
3003
setting x2 via setter to 4004
getting x2 via getter
4004
```

To try to understand you better, now you see this, what can you tell me about the behaviour/limitations?

**Comment by reduz** [comment]
nevermind, I misunderstood what the PR was about

**Pull request merged**
