### PR TITLE
Fix #12220: Add Decompress Bc5 to Squish

### LINKED ISSUE #12220: File Preview Image Corruption
**Operating system**: Arch Linux
**GPU:** GTX 1050M
**Driver:** nvidia-dkms 387.12-2

**Issue description:**
Getting strange texture corruptions on the left file preview. On the *right, the preview seems just fine.
<br/> 
Image Preview Corruptions

### PR DESCRIPTION
**Pull request by gad-o**
This Commit fixes the corrupted file preview described in #12220.
Added DecompressColourBc5 function to squish.

### CODE REVIEW

**Comment by reduz** [comment]
Wow you rock

**Comment by gad-o** [comment]
Thanks!
Actualy this is a partialy solution. I think, we should implement bc4 compression also...

**Comment by akien-mga** [comment]
So we're forking libsquish?..

Have you tried to propose this change upstream?

**Comment by gad-o** [comment]
I try solve without touch squish but you can see actually Bc5 and Probably bc4 not working.

Yes, i search for issue tracker or push for upstream, i can't find any way to how contirubute. Also try another project that uses libsuqish for how they resolve these decompression but cant find. I think there is no way arround it but fork or wait for upstream. What i see, this is critical for godot and godot more fast development cycle.
I think we should fork library and patch if it work. Or wait for bc5 compression became mature

**Comment by tagcup** [comment]
How about maintaining this as a patch and maybe wrap it in between markers like `/* GODOT start */` until we get this into upstream (which might take some time)? We already have this kind of stuff in [third party](https://github.com/godotengine/godot/tree/master/thirdparty).

**Comment by akien-mga** [comment]
> How about maintaining this as a patch and maybe wrap it in between markers like /* GODOT start */ until we get this into upstream (which might take some time)? We already have this kind of stuff in third party.

That's what should be done, yes, but I want to see a discussion with upstream at least *start*, so far I see no indication that contact with them was made. As upstream dev for various projects, I know that it's very important that downstream users tell you when they want API changes :)

**Comment by gad-o** [comment]
> That's what should be done, yes, but I want to see a discussion with upstream at least start, so far I see no indication that contact with them was made. As upstream dev for various projects, I know that it's very important that downstream users tell you when they want API changes, even more so if they have patches for it already :)

You're right. I will try contanct with them.

**Comment by akien-mga** [comment]
Thanks! Feel free to put me in CC with my email from https://godotengine.org/contact

**Comment by akien-mga** [comment]
Any news from the Squish devs?

**Comment by gad-o** [comment]
I put you on cc; since than, no news.

**Comment by akien-mga** [comment]
Seems like things might take a while with upstream, so I merged this manually with comments to properly show what we did: e021097c8

**Pull request closed without merging**
