### PR TITLE
[Windows] Implement native file selection dialog support.

### PR DESCRIPTION
**Pull request by bruvzg**
Follow up to https://github.com/godotengine/godot/pull/47499

Implements `DisplayServer.file_dialog_show()` for Windows.

- *Production edit: This partially addresses https://github.com/godotengine/godot-proposals/issues/1123.*

### CODE REVIEW

**Comment by YuriSizov** [comment]
The passthrough option from the `FileDialog` seems to work correctly. But when calling `DisplayServer.file_dialog_show()`, I can't seem to change the current directory with any of these:

```gdscript

DisplayServer.file_dialog_show("Hello!", ".", "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_ANY, [], _callback)
DisplayServer.file_dialog_show("Hello!", "res://", "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_ANY, [], _callback)
DisplayServer.file_dialog_show("Hello!", ProjectSettings.globalize_path("res://"), "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_ANY, [], _callback)
DisplayServer.file_dialog_show("Hello!", "C:/", "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_ANY, [], _callback)
DisplayServer.file_dialog_show("Hello!", "C:\\", "", false, DisplayServer.FILE_DIALOG_MODE_OPEN_ANY, [], _callback)
```

It always opens the user directory instead. Windows 11 by the way.

**Comment by KoBeWi** [comment]
Tested on Windows 10, I also can't change current directory.
Although it does not always open in user. It opens the last directory I picked something from. I observed such behavior in various apps (most notably in Chrome), so it's at least consistent with how native file dialogs usually work on Windows.

**Comment by bruvzg** [comment]
Setting directory should be fixes.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
I think that might be by design? Isn't it always blocking the main window when a native app brings that dialog? But feel free to open the issue.

**Comment by KoBeWi** [comment]
I checked how Chrome handles it. When you click outside the dialog, the dialog will briefly blink and play the Background sound.

**Pull request merged**
