### PR TITLE
Added release function to PoolVector::Access.

### PR DESCRIPTION
**Pull request by ibrahn**
For clarity, assign-to-release idiom for PoolVector::Read/Write replaced
with a function call.
Existing uses replaced (or removed if already handled by scope)

### CODE REVIEW

**Comment by ibrahn** [comment]
If this PR sounds like a good idea, I'll go through and swap all the existing `writer = PoolVector::Write()` to use close instead or remove them if they're already handled by scope.

**Comment by akien-mga** [comment]
Some comments from @reduz on IRC:
```
21:46 <Akien> reduz: WDYT of #30206 ? I like that it makes things more explicit, I was always configured by these stray `w = PoolVector<uint8_t>::Write();` coming last
21:46 <IssueBot> #30206: Added close function to PoolVector::Access. | https://git.io/fjKfn
21:46 <Akien> TMM: ^
21:47 <reduz> Akien: can't say i like it
21:48 <reduz> close is also not a good name, and i can't think of anything good
21:49 <Akien> Could be unref() I guess
21:49 <reduz> it's not a reference either
21:49 <reduz> maybe release()
21:49 <reduz> it's also not something very important to merge now
21:49 <reduz> but if you want to merge it, hope you have fun migrating all this to 4.0 :P
21:50 <Akien> Well there is enough stuff merge for me to spend a full day rebasing the vulkan branch, so I don't mind some more :)
21:50 <reduz> heh ok
```

**Comment by ibrahn** [comment]
Does this want putting on hold and resurrecting/rebasing when the vulkan branch merges in or closing as not useful?

**Comment by akien-mga** [comment]
IMO it could be merged, it shouldn't be hard to rebase the `vulkan` branch after it (I just rebased the whole vulkan branch on current master).

The question is mainly if it should be `close()` or `release()` then. I have no strong opinion but @reduz says the latter would be more accurate.

**Comment by ibrahn** [comment]
I agree, release is better.
Updated version pushed

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
