### PR TITLE
CTRL+Click on extends with relative path provide Errors #22224

### PR DESCRIPTION
**Pull request by evandropoa**
Fix issue CTRL+Click on extends with relative path provide Errors #22224 and adds code completion to the extends keyword when extending from a file.

### CODE REVIEW

**Comment by evandropoa** [comment]
Well, the problem is the way the lookup and code completion works, it breaks the text at cursor position by inserting a unicode to create a token, this subdivide the text and breaks the parser.

Of course I could just do brute force in the lookup to find if it is just a resource file, but its not the right to do, since the tokenizer breaks text in two parts at cursor, there must a partial token continuing it so the parser could rebuild it.

I did this partial token only for this specific case (strings constants), but really it should not break the parser only becouse the cursor is inside the code.

Bether yet, this full code lookup and completion in the parser should not be so envasive and handled in another way.

**Comment by evandropoa** [comment]
I don´t think we should take a way functionality becouse issues in the code :)

**Comment by vnen** [comment]
I don't know, it's a big change and it needs to be reviewed carefully, since it has implications in GDScript as a whole. Especially in code completion, and while this change might be something that can improve completion in the future, it needs to be seen if it's not making it worse right now.

Also, some errors are a bit cryptic, like "partial constant needs to be a string". If an user ever bump into this they'll be confused by what is a "partial constant" and how they can make one (which is not something they can find in the documentation). Since this should never happen in a regular file, this should be reported as a "parser bug" (like some other errors that can happen).

Just to point out, there are some cosmetic changes mixed up (adding brackets and removing tabs), which makes it harder to review. While those changes aren't bad, ideally they should be made on their own commit to make review easier.

**Comment by evandropoa** [comment]
Well, I agree, but the fact is the way the lookup is happening today in the tokenizer its breaking the parser, if you click at the extends file name, it will throw a error msg becouse the parser cannot find the correct file just becouse the tokenizer has broken the constant string and the parser isn´t aware of it.

**Comment by evandropoa** [comment]
Sry, my english isn´t the best. maybe we can talk in portuguese if you could not understand.

**Pull request closed without merging**
