### PR TITLE
[Android editor] Update the Android editor flavors

### PR DESCRIPTION
**Pull request by m4gr3d**
Update the Android editor flavors to avoid vendor-specific references:
- switch from `google` to `android`
- switch from `meta` to `horizonos`

### CODE REVIEW

**Review by dsnopek — APPROVED** [review]
Makes sense to me! The code looks good. I tested building both the Android and HorizonOS variants, and it seemed to work correctly

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
I guess this also needs to be updated? https://github.com/godotengine/godot-build-scripts/blob/fa404f8c17dc9312b9d16902d1e30bb55ed22787/build-android/build.sh#L45

**Comment by dsnopek** [comment]
Yes, the build artifacts from Gradle will be named differently after this PR, for example

- `android_editor-google-release.apk` -> `android_editor-android-release.apk`
- `android_editor-meta-release.apk` -> `android_editor-horizonos-release.apk`
- etc for the debug versions and the `.aab`s

I imagine we'll want to rename `android_editor_meta.apk` to `android_editor_horizonos.apk` as well

**Comment by m4gr3d** [comment]
> I guess this also needs to be updated? https://github.com/godotengine/godot-build-scripts/blob/fa404f8c17dc9312b9d16902d1e30bb55ed22787/build-android/build.sh#L45

Added https://github.com/godotengine/godot-build-scripts/pull/101 to update the build scripts.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
