### PR TITLE
Update HarfBuzz to 7.1.0

### PR DESCRIPTION
**Pull request by RandomShaper**
According to the changelog, 7.0.0 should be perfectly backwards compatible with 6.0.0 and brings faster shaping speed.

**UPDATE:** Moved to 7.1.0. The backwards compatibility guarantees stay.

That said, this was primarily done as part of #73051 (see there for full context), but spinned off for more convenient maintenance.

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Comment by RandomShaper** [comment]
Pushed just to update the `COPYRIGHT.txt` file.

**Comment by akien-mga** [comment]
For the record, there's 7.0.1 now (but not a priority to update right now :)).

**Comment by akien-mga** [comment]
This could now be merged, but in the meantime HarfBuzz 7.1.0 was released, so it would be good to update to it.

**Comment by RandomShaper** [comment]
Updated. Smoke tested locally.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
