### PR TITLE
Add support for Android Themed Icons (monochrome)

### LINKED ISSUE #5572: Add support for Android Themed Icons
### Describe the project you are working on

Android 13 introduces a new kind of customization: Themed Icons.
With it, it's possible to make the app's icons use the theme color.

Example:
<center>
</center>

- Godot already supports Adaptive Icons.

### Describe the problem or limitation you are having in your project

Currently Godot doesn't support Themed Icons without create a custom project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot could have a `theme icon` field in the Launcher Icons options.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Basicly, Godot supports adaptive icons with the following XML:

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/icon_background"/>
    <foreground android:drawable="@mipmap/icon_foreground"/>
</adaptive-icon>
```

By adding one line, it will support themed icons (`<monochrome android:drawable="@mipmap/icon_monochrome"/>`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/icon_background"/>
    <foreground android:drawable="@mipmap/icon_foreground"/>
    <monochrome android:drawable="@mipmap/icon_monochrome"/>
</adaptive-icon>
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If not used, all we have to do is omit the `<monochrome android:drawable="@mipmap/icon_monochrome"/>` line and it will work as is today.

### Is there a reason why this should be core and not an add-on in the asset library?

We already support Adaptive Icons and Themed Icons is part of it.
By adding this Godot will also to encourage the right Android customization support.

### PR DESCRIPTION
**Pull request by syntaxerror247**
This PR adds support for Android Themed icons. 

Closes godotengine/godot-proposals#5572

https://github.com/user-attachments/assets/75d75630-2dba-42f8-ae4e-29ea48a3ef78

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Could you amend the commit message to be more explicit and follow our guidelines? https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

This PR's title would be a good commit message.

(I'd normally do it myself but it seems like you toggled off the option that lets repo maintainers update this PR directly.)

**Comment by syntaxerror247** [comment]
I have just turned on edits by maintainers. You can now set it whatever you want.

**Comment by akien-mga** [comment]
Thanks, updated :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by lucasnlm** [comment]
Nice! @syntaxerror247 thanks for implement it! 👏

**Comment by m4gr3d** [comment]
@syntaxerror247 Both this PR and https://github.com/godotengine/godot/pull/99378 have a cherrypick tag for 4.3. 
Given this is a new feature, is there a need to backport it to 4.3?

**Comment by syntaxerror247** [comment]
> @syntaxerror247 Both this PR and #99378 have a cherrypick tag for 4.3. Given this is a new feature, is there a need to backport it to 4.3?

This is part of the adaptive icons, which is why I requested it to be cherry-picked. I believe it introduces no significant changes that could be hard to backport.

**Comment by m4gr3d** [comment]
> > @syntaxerror247 Both this PR and #99378 have a cherrypick tag for 4.3. Given this is a new feature, is there a need to backport it to 4.3?
> 
> This is part of the adaptive icons, which is why I requested it to be cherry-picked. I believe it introduces no significant changes that could be hard to backport.

Okay, let's make sure we have a fix for https://github.com/godotengine/godot/pull/99378 before we cherrypick this PR; we may need to create a separate PR specially for 4.3 with that merges the two referenced PRs.

**Pull request merged**
