### PR TITLE
Make breakline(\n) understandable to buttons

### LINKED ISSUE #2967: Button text ignores breakline (\n) (fixed in `master`)
If I set a text with a breakline like "Hello\nthere" and set this text to the Button text and tooltip, the breakline works on the tooltip but is ignored on the text.

### PR DESCRIPTION
**Pull request by Undid-Iridium**
If I understood the issue correctly this can serve as a solution. If this is not appropriate/was not the correct interpretation of the problem I would be more than willing to go back and fix any potential issues. Thanks for your time.

_bugsquad edit:_ Fix #2967

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Sorry but this is not the correct solution. As mentioned in this [comment](https://github.com/godotengine/godot/issues/2967#issuecomment-164590141) in the original issue, tooltip already works as expected. It's that the text on the button itself ignores linebreaks.

**Comment by Naryosha** [comment]
Please check out my [branch](https://github.com/Naryosha/godot/tree/btn-linebreak) if you're interested in fixing the original issue. I've replaced simple button text drawing with Label overlay.

It's almost there but still looks ugly in some cases. I don't have time to finish.
image

**Comment by Gutierrezjdr** [comment]
@Naryosha What did you want to fix about the label overlay? Is it specifically margin and borders with other objects on the button?

**Comment by Naryosha** [comment]
Yes. Mainly about the margin, not only for Button but also its derivatives.

Label already has a functionality to align text horizontally and it's very difficult to reimplement it for buttons. I prefer reusing existing functions.

**Comment by FrancisXIrizarry** [comment]
I see. I miss-understood the problem as a result of looking at the wrong comments. I also now understand what you were getting to, and the purpose of it. I will look into it. Thanks.

**Comment by akien-mga** [comment]
Closing since this is not the desired solution for #2967. Thanks for the proposal nevertheless!
It might be worth relinking @Naryosha's WIP in #2967 and continue the discussion there.

**Pull request closed without merging**
