### PR TITLE
GDScript access to copyright, license, author and donor information.

### LINKED ISSUE #18888: Make license and copyright info available in GDScript
It might be useful to expose the information from `editor/license.gen.h` in GDScript, to make it easy to build license screens, like the about page in the editor

### PR DESCRIPTION
**Pull request by ibrahn**
Adds following functions to the Engine singleton:
get_author_info - names of Godot authors
get_copyright_info - detailed source copyright get_license_info
get_donor_info - donor names
get_license_info - full text of licenses used, indexed by license names
get_license_text - the text of the Godot Expat license

fixes #18888

### CODE REVIEW

**Comment by ibrahn** [comment]
Added these to the Engine singleton because the existing get_version_info there seemed like the closest match. Is this a sensible place to put them?
Also looking for opinions on names, layout of the returned dictionaries and documentation wording.

**Comment by reduz** [comment]
This is a very nice PR, seems fine to me

**Comment by akien-mga** [comment]
Checking it now, sorry for the delay.

**Comment by akien-mga** [comment]
This is great, thanks a lot! And kudos for refactoring the about dialog to use the new feature.

**Comment by akien-mga** [comment]
@hpvb If/when cherry-picking this one, #19227 should be included too.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
