### PR TITLE
Delete `set_all`, `set_axis`, and `get_axis` methods from Vector2/3/3i/4/4i

### PR DESCRIPTION
**Pull request by aaronfranke**
`set_all` is not a very useful method, it was only used in one place in BVH. However, the rest of the BVH code just iterates over the axis count, so this PR changes the `set_all` code to use this approach and removes `set_all`. Also, `set_all` was broken in Vector4, which is what got me investigating this method in the first place.

I deleted the `set_axis` and `get_axis` methods because they are not used internally anywhere (except for the tests) and they do the same thing as the array operator anyway. Also, Vector2i did not have it.

### CODE REVIEW

**Comment by akien-mga** [comment]
> I deleted the `set_axis` and `get_axis` methods because they are not used internally anywhere (except for the tests) and they do the same thing as the array operator anyway. Also, Vector2i did not have it.

Can all language bindings use the C++ array operators? How does it work in GDExtension?

**Comment by aaronfranke** [comment]
GDScript can use the array operator. C# and GDExtension C++ each have the vector types implemented natively in their language with array operators of their own. I don't know how it works for non-C++ GDExtension.

**Review by akien-mga — APPROVED** [review]
Nobody seems opposed to it so let's go.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
