### PR TITLE
Properties painting in tileset editor

### PR DESCRIPTION
**Pull request by groud**
Implement property painting over tiles:
Peek 23-06-2021 16-10

Other changes:
- TileSet's collision shapes have been replaced by polygons. Internally, when you set a Tile's polygon, it creates a set of ConvexPolygonShape2D. Those are then accessible with `get_collision_polygon_shape(...)`.
- A little change in editor_properties.h/cpp allows me to retrieve the default property editor for a given property. That's how I get the editor used to select the value to be painted.
- Allow panning in the TileAtlasView with either right click of middle click.
- Generate the icons for terrains at the right size now.
- Simplifies a the tile creation in atlases by merging the two creation menus together.
- Remove the unused tile_skew property
- Remove the ScrollContainer in TileAtlasView, it lead to undesired behavior went trying to zoom in/out. I used a custom panning system instead.

### CODE REVIEW

**Comment by KoBeWi** [comment]
The top panel should have constant height, otherwise everything is jumping :/
V10B1lgCDQ

Modulate doesn't take effect until you change tool:
RcC6wTsib7
And Texture Offset doesn't seem to work at all.

**Comment by groud** [comment]
> The top panel should have constant height, otherwise everything is jumping :/

It isn't really possible, the polygon editor is pretty wide and it would look weird for all other editors. But TBH, I don't think this is a big problem, there's not a lot of situations where you would navigate through each property like that. Maybe I could set a minimum size at least to the one for Vector2s, but I am not sure it is worth.

> Modulate doesn't take effect until you change tool:

Yeah, I know that. Problem is that it require the redrawing of the whole atlas which might have a performance impact (it seems like it does on my side). I could try again it though. Maybe another solution might be to have each tile in its CanvasItem and only update the ones modified but I am not sure (at it's quite some work).

> And Texture Offset doesn't seem to work at all.

It does work, but need to have big tiles to be able to see it.

> Also the list feels very cramped on default size:

Yeah I agree, I think it would be great to find away to move the TileSet/TileMap button elsewhere, but I am not sure where to put it or how we could change it to something else. Maybe vertical tabs at the left? Though we have thing nowhere else in the editor.

On a side note, I would like to allow the Tree node to have its scrollbar disabled. That would avoid the two scrollbars next to each other. But that's for another PR.

**Comment by Calinou** [comment]
> On a side note, I would like to allow the Tree node to have its scrollbar disabled. That would avoid the two scrollbars next to each other. But that's for another PR.

https://github.com/godotengine/godot/pull/48008 was recently merged. I guess Tree needs to have similar methods?

**Comment by groud** [comment]
> #48008 was recently merged. I guess Tree needs to have similar methods?

It's not only about hiding, it's also about setting the minimum size. Like if there was no ScrollContainer at all.
Maybe it needs a modification of ScrollContainer to allow that (probably by having scrolling modes like "enabled", "hidden", "disabled").

**Comment by groud** [comment]
> Yeah, I know that. Problem is that it require the redrawing of the whole atlas which might have a performance impact (it seems like it does on my side). I could try again it though. Maybe another solution might be to have each tile in its CanvasItem and only update the ones modified but I am not sure (at it's quite some work).

I fixed the issue. But to make sure things work fast, I had to use Mesh2D to draw the tiles. It should work fine but needs https://github.com/godotengine/godot/pull/49826 to be merged first.

As a side note, I also removed the unused tile_skew property.

**Comment by EricEzaM** [comment]
> > The top panel should have constant height, otherwise everything is jumping :/

> It isn't really possible, the polygon editor is pretty wide and it would look weird for all other editors. But TBH, I don't think this is a big problem, there's not a lot of situations where you would navigate through each property like that. Maybe I could set a minimum size at least to the one for Vector2s, but I am not sure it is worth.

In my eyes it hurts usability a lot - you cannot easily quickly switch between different painters because it jumps around a lot. I think this could be fixed if the `Painting` property editor was put _after_ the `Paint Properties` tree, so that the tree itself would not be moved, it would just be made shorter/longer.

> > Modulate doesn't take effect until you change tool:

> Yeah, I know that. Problem is that it require the redrawing of the whole atlas which might have a performance impact (it seems like it does on my side). I could try again it though. Maybe another solution might be to have each tile in its CanvasItem and only update the ones modified but I am not sure (at it's quite some work).

The box showing the painted colour gives immediate feedback, which is good. What if you just do the redraw on `mouseup`? This would decrease the frequency of the redraws while not requiring users to switch to another tool to see their changes.

**Comment by groud** [comment]
> In my eyes it hurts usability a lot - you cannot easily quickly switch between different painters because it jumps around a lot. 

I don't think it does. Jumping quickly switch between properties to paint is maybe something you do now by exploring the new editor, but in real life use cases, you will spend time in a given property. Because you need first to select the property, and even if you need to verify a single tile, your eyes have to move to the right side.

Honestly I think this is the most acceptable solution, I cannot add a new column as it would take too much space and it keeps the the order consistent (the most global menus are at the bottom). We could possibly make the top panel collapsible, but I am not sure it would be the best.

> The box showing the painted colour gives immediate feedback, which is good. What if you just do the redraw on mouseup? This would decrease the frequency of the redraws while not requiring users to switch to another tool to fully preview their changes.

I changed it on my side, the issue is solved and it does not seem to cause slowdowns.

**Comment by EricEzaM** [comment]
> Honestly I think this is the most acceptable solution

Sorry, what is "this"?

**Comment by groud** [comment]
> Sorry, what is "this"?

The current implementation in this PR. ^^

**Comment by EricEzaM** [comment]
Have you tried putting it below? At least then the tree itself will not jump around.

**Comment by groud** [comment]
> Have you tried putting the property editor below the tree? At least then the tree itself will not jump around.

Nope, but I don't want to. The order of the menu in the column is consistent, with the most global settings being at the bottom and the most specific ones being at the top. And it makes sense, because when you are in a menu, you want the most specific part (thus the thing you are working with right now) the easiest to access. This is especially the case here: because the bottom menu is quite small on small screens, I want users to have access to the painted value first, no the list of properties they would not care about now.

**Comment by pycbouh** [comment]
I'm just chipping in to agree with the rest that things jumping away from under your mouse can get very annoying very quick. The whole panel feels very cramped too.

Do we need **Atlas Properties** to be simultaneously available with the painting tools? We are switching contexts, and the painting one is pretty heavy on its own, so I would suggest we hide irrelevant/not immediately required sections.

The `Tree` of painting modes is a control for selecting a tool, and putting selection of the tool below the tool's context is a weird decision. Like others suggest, I would put it above the **Painting** section. To make it more usable, since you suggest we shouldn't expect users to jump around and quickly change the painting mode, the `Tree` can be replaced with an `OptionButton` or something similar to it. It can provide the same grouping capabilities, but won't be as cramped into the limited space of the panel. And a button would be compact and fixed in size too.

So the flow would be that after selecting the Painting mode your top-most control in the panel would be a dropdown list of properties to paint, and below that — the settings for the selected property. And nothing else.

**Comment by pycbouh** [comment]
> A dropdown list would be better indeed, but I won't go that way unless we have a way to group entries. I could maybe embed a tree in a Popup but not sure. I'll give it a try.

Multi-level PopupMenus can work. You could make your own combination of a button and a popup menu or you can probably hack around OptionButton too (submenus obviously do not update OptionButton):

image

I guess a popup with a tree can also work. I don't think we have anything like that, but it can be an interesting control to have in general.

**Comment by groud** [comment]
Ok I updated the PR with a rework of the interface. Here is how it looks now:
Peek 29-06-2021 11-09

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
