### PR TITLE
Rename AudioStreamPlayer to AudioPlayer

### PR DESCRIPTION
**Pull request by madmiraal**
Also renames:
- AudioStreamPlayer2D to AudioPlayer2D
- AudioStreamPlayer3D to AudioPlayer3D

Originally suggested by @dalexeev in [#16863](https://github.com/godotengine/godot/issues/16863#issuecomment-766173614).

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge of #46740.

**Comment by mhilbrunner** [comment]
Thanks! Sorry its taking time to review due to the backlog situation.

Discussed this with other team members and there does not seem to be consensus for this change, so I'm closing it for now.
Still, thank you for suggesting it :)

**Comment by madmiraal** [comment]
@mhilbrunner what is the argument for not making this change? Has it been decided to rename `VideoPlayer` to `VideoStreamPlayer` instead?

**Comment by mhilbrunner** [comment]
There was no clear consensus for the renames either way. If we are going forward with these renames, it should go through the proposal process to demonstrate there is clear support first.

**Comment by dalexeev** [comment]
I opened a proposal where you can vote: godotengine/godot-proposals#3624.

**Comment by madmiraal** [comment]
Can we reopen this PR to support godotengine/godot-proposals#3624, or do I need to create a new one?

**Comment by Calinou** [comment]
This PR can't be reopened since the `audio-stream-player` branch was force-pushed or recreated.

**Comment by madmiraal** [comment]
I've created a new PR: #55583.

**Pull request closed without merging**
