### PR TITLE
[3.6] Add alpha awareness to Multiply blend mode

### LINKED ISSUE #29105: Fix Subtract and Multiply modes on CanvasItemMaterial to also work on alpha
**Godot version:** 3.1.1

**OS/device including version:** Solus Gnome NVIDIA GTX 1050 TI

**Issue description:**

Currently the Subtract and the Multiply modes of the CanvasItemMaterial doesn't operate on the alphas of the CanvasItems below it, so we cannot perform simple boolean operations.

ezgif com-video-to-gif

Ideally it should take the alpha of the canvas item below it and multiply by its own, clipping them.

**Steps to reproduce:**
1. Create 2 CanvasItems (Preferably a Line2D so you can have graphics to overlap)
1. Add a CanvasMaterial to one of them
1. Set the CanvasMaterial blend mode to `Mul`
1. Set the Modulate or SelfModulate alpha to 0
1. Intersect both CanvasItems

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by GithubPrankster**
Fixes #29105.

This changes the Multiply blend equation to utilize `GL_ONE_MINUS_SRC_ALPHA` for the background value, allowing alpha to affect how much is being multiplied.

image

The **current caveat** is that proper usage of this blend mode requires transparent textures to use _pre-multiplied alpha_, this also extends to Modulate usage as not multiplying it otherwise generates a pseudo-additive effect.

image

I've not been able to find a proper way to modify Modulate usage to automatically do pre-multiplication if the blend mode being used is Multiply, so for now the next best thing is doing it yourself in a shader.

https://user-images.githubusercontent.com/33995085/181118285-dae5b3b5-9f5f-4be5-bc82-ee8833b89e68.mp4

`	vec4 modulate = MODULATE;
	modulate.rgb *= modulate.a;`

In spatial shaders, remember to multiply `ALBEDO` by `ALPHA`.

One observation is that automatically doing pre-multiplication for the Premultiplied Alpha blend mode would also get rid of its pseudo-additive behavior. Unfortunately since this is my first PR I am not aware at all of where I could change this, but the user should have a better multiply blend mode now. I've also made a `master` version of this PR. (#63630)

### CODE REVIEW

**Comment by Calinou** [comment]
Should this change also apply to 3D like in the [`master` version of this PR](https://github.com/godotengine/godot/pull/63630)? Right now, only 2D seems to be affected.

**Comment by GithubPrankster** [comment]
Isn't hard to also add it to the GLES3/GLES2 3D renderers. I'll look into it right now. 👍

**Review by Calinou — APPROVED** [review]
Code looks good to me, though we should decide if the visual breakage that may occur in a few projects is worth doing in 3.6. (This isn't a concern for the [`master` version of this PR](https://github.com/godotengine/godot/pull/63630).)

Personally, I'd say it's worth the risk as not many projects are using the Multiply blend mode currently, but I'll let others weigh in.

**Comment by akien-mga** [comment]
Please squash the commits.

**Comment by lawnjelly** [comment]
> Personally, I'd say it's worth the risk as not many projects are using the Multiply blend mode currently, but I'll let others weigh in.

I suppose someone may have developed a "look" with the current blend modes, and this could break their game.

The problem imo with blend modes, is that as we don't specify them exactly (in an attempt to simplify them, and cover bases with different APIs), it's open to interpretation what users might want, and there are a lot of combinations. We could probably add an extra blend mode to the enum to handle this (but then where do you end.. :grin: ).

That said I'm no expert on which blend modes are actually useful (I normally copy paste them myself  :grinning: ), so maybe this is more useful than the old multiply.

Another alternative might be to keep the existing blend modes but add an advanced version where everything can be specified. Probably should have more input from other rendering contributors before merging.

**Comment by clayjohn** [comment]
I am also concerned about this PR. IMO it makes the multiply blend mode more useful for some, but is likely to break workflows for others. This is really an entirely new blend mode, so it should likely have an option to change behaviour, or it should be made as an entirely new blend mode.

**Comment by GithubPrankster** [comment]
I do not know how to really add more blend modes so I can't really say what I'll do. I'll just get working on squashing commits for now.

**Comment by GithubPrankster** [comment]
I do not know how to do a rebase for non-master branch so for now I'll wait for if this PR should be scrapped in favor of @clayjohn's idea.

**Pull request closed without merging**
