### PR TITLE
Fix nested YSort breaking "Use parent material"

### LINKED ISSUE #28115: Enabling YSort property on Tilemap removes shader effect
**Godot version:**
3.1 official

**OS/device including version:**
Windows 10.0.17134 Build 17134

**Issue description:**
I am using the following sprite outline shader that was provided by the community:

	shader_type canvas_item;
	render_mode unshaded;
	
	uniform float width : hint_range(0.0, 16.0);
	uniform vec4 outline_color : hint_color;
	 
	void fragment()
	{
		vec2 size = vec2(width) / vec2(textureSize(TEXTURE, 0));
	
		vec4 sprite_color = texture(TEXTURE, UV);
	
		float alpha = sprite_color.a;
		alpha += texture(TEXTURE, UV + vec2(0.0, -size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(size.x, -size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(size.x, 0.0)).a;
		alpha += texture(TEXTURE, UV + vec2(size.x, size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(0.0, size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(-size.x, size.y)).a;
		alpha += texture(TEXTURE, UV + vec2(-size.x, 0.0)).a;
		alpha += texture(TEXTURE, UV + vec2(-size.x, -size.y)).a;
	
		vec3 final_color = mix(outline_color.rgb, sprite_color.rgb, sprite_color.a);
		COLOR = vec4(final_color, clamp(alpha, 0.0, 1.0));
	}

I am using it on a tilemap. When the tilemap's ysort property is enabled, the shader stops working.

From:
https://godotengine.org/qa/43740/enabling-ysort-on-tilemap-removes-shader-effect

**Steps to reproduce:**
In the project attached below:
    - disable ysort for Tilemap3
    - enable ysort for Tilemap3
    - notice that the outline shader stops working when ysort is enabled

**Minimal reproduction project:**
[ysort-tilemap3.zip](https://github.com/godotengine/godot/files/3088507/ysort-tilemap3.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #28115

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by CngKO** [comment]
Many thanks, @bojidar-bg!

@akien-mga, will this fix be released with 3.2 or with an earlier bugfix version (ie. 3.1.1)?

**Comment by akien-mga** [comment]
It's labelled to be cherrypicked for 3.1.x.

**Comment by hpvb** [comment]
Consider for 3.1.2

**Comment by akien-mga** [comment]
Note: cherry-picking this depends on #27843.

**Pull request merged**
