### PR TITLE
Add AutoLoad option to the script creation dialog

### PR DESCRIPTION
**Pull request by Chaosus**
Editor QoL enhancement which adds an option to auto-add the new script to the autoload list:
autoload_script2

Note: this option would be available only for scripts created in FileSystem.

### CODE REVIEW

**Comment by reduz** [comment]
image
I suggest changing the UI to be like this.

**Comment by Chaosus** [comment]
I would try to do both ^^ and in the next PR meeting the desired one would be choosen

**Comment by aaronfranke** [comment]
IMO, having this checkbox be in the script creation dialog is unnecessary clutter and will be confusing to new users.

* It encourages users to use AutoLoads, which should be used sparingly.
* All new users need to learn about the script creation dialog. This adds more things that need explaining.
* Users may check this box thinking "Yes, I want this code to load automatically!" not knowing what AutoLoads are.

IMO, @akien-mga's suggestion of having a create script button in the script creation dialog would be good:

autoload-create-script

**Comment by Chaosus** [comment]
Seems undesired. Closed.

**Pull request closed without merging**
