### PR TITLE
Disable autowrap for export dialog errors

### LINKED ISSUE #25065: Project export resizes height too much when adding/opening android preset for the first time
**Godot version:**
07e2046980c903268ef0d2f5a73caea77d511519

**OS/device including version:**
Win 10 Pro
Gigabyte HD 7950 - drivers 18.12.2

**Issue description:**
When android preset is added or opened for the first time in a newly opened project, the popup is resized too much (even beyond screen bounds, but that depends on a size of the Godot window)
androidexport

**Steps to reproduce:**
1. Open any project (preferably a new one)
2. Open project export
3. Add android preset or open an existing android preset (you cannot have had opened any preset previously - you will need to reopen the project for this to occur again)

### PR DESCRIPTION
**Pull request by ankitpriyarup**
*Bugsquad edit:* Fixes #25065.

### CODE REVIEW

**Comment by akien-mga** [comment]
Please be more explicit in commit logs, the message should explain what the commit does and not just reference the GitHub issue that it fixes. Remember that the `git log` is something that can (and is) often referred to locally, not always on GitHub. Something like this would be clearer:
```
Disable autowrap for export dialog errors

Fixes #25065.
```

**Comment by akien-mga** [comment]
That being said, I'm surprised by the fix. I think we *do* want export errors to be autowrapped, otherwise long errors will mean that the export dialog will become very wide. It's surprising that autowrap on the error label would cause such a vertical stretching issue.

**Comment by SoIAS** [comment]
@akien-mga 
> I think we _do_ want export errors to be autowrapped, otherwise long errors will mean that the export dialog will become very wide

I was also working on this issue, but was checking on different ways to fix it and didn't make PR. So, there is another way to fix this, basically by showing the error label at initialization instead of hiding it, this way, we don't remove the functionality of autowrapping (more on that below). It would be showing an empty error label, so visually, nothing would change . I am leaving it up here in case @ankitpriyarup wants to make changes: 5cd0ac1184523771c61cf5fcfad8931fa9cff32f

>  It's surprising that autowrap on the error label would cause such a vertical stretching issue.

Basically the bug comes to initial width of the `export_error` label. When the `export_error` is hidden, the initial width is not set when the export popup is shown, thus when we try to add a text to the label and show it for the very first time, it breaks the text into multiple lines on any space or new line character (suprisingly normal text is shown, probably because draw calls for recalculation and the actual width is already set). 
When the label is shown at initialization, the initial size is set via `BoxContainer::_resort -> Container::fit_child_in_rect`.

The screenshot below shows some debug information between first pass (when the label's width is not set yet) and the second pass (when the label's width is already set). Data is taken after calling `Label::show`.
passes

**Comment by akien-mga** [comment]
@SoIAS Thanks for the detailed explanation!

@reduz says that autowrap is too hacky and should not be used, so it seems like removing it is indeed the right fix. It was added in #24203 to fix another layout issue, but it should stay fixed with the min size change added in that PR. I'll push another fix for the actually problematic error line in #24202 where two errors are on the same line without line break.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
