### PR TITLE
Allow plugin scene change signal to report null for empty scenes.

### PR DESCRIPTION
**Pull request by ghost**
This one line change should allow the plugin's "scene change" signal to report a null scene, so that a plugin can know that the editor has switched to an "Empty" scene, and most importantly, _always signal that a scene has been changed in the editor_.

Motivated by this request:  https://github.com/godotengine/godot/issues/22123

I'd also find it handy from time to time.  It does add a small inconvenience to check that a scene is null in your tool.

The current behavior has a sneaky side effect to it.  If you use this signal to know when a scene is changing (as it implies), switching to an empty scene doesn't fire the signal.  Meaning your script will behave as if the scene hasn't been changed, even though it has.  It really does create a need for a lot of awkward and time consuming work-arounds for particular types of tools.

Test project: [Scene Changed to Empty Test.zip](https://github.com/godotengine/godot/files/2387934/Scene.Changed.to.Empty.Test.zip)

This might break compatibility if there is a plugin that relies on the current functionality, and it expects that this signal will never fire when an Empty / null scene is selected.

I've tested it out a bunch, it appears to be working as intended, but please let me know if I'm missing something subtle.

### CODE REVIEW

**Comment by akien-mga** [comment]
That's a good change IMO, I'd also expect such signal to be emitted when changing to an empty scene. This does mean however than one should do null checks in the plugin before using the passed parameter.

@vnen @kubecz3k Thoughts?

**Comment by avencherus** [comment]
Yeah, it would move that line into one's script, but in situations when trying to know when the scene changes, it won't signal at all if you switch to an empty scene.  The work around I found for this is much uglier.  X)

**Comment by kubecz3k** [comment]
The change is ok for me. 
It should be noted somewhere so we could write about this change at the time of 3.1 release.

**Comment by akien-mga** [comment]
@reduz confirmed that it makes sense for him too, so should be good to go. Could you amend the commit to also complete the documentation for this signal in `doc/classes/EditorPlugin.xml`, to make it clear that the parameter can be NULL when changing to an empty scene?

**Comment by avencherus** [comment]
@akien-mga Sure thing.  If its not a problem, I made some tiny grammar fixes to the documentation of the signals above and below it.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
