### PR TITLE
add stop button 

### PR DESCRIPTION
**Pull request by rdcklinux**
add stop button to each sample item on sample library editor plugin

### CODE REVIEW

**Comment by rdcklinux** [comment]
Hi folks, I added some improvements: toggle button play and stop and add remove button in row.

**Comment by akien-mga** [comment]
Nice work, I'll try to have a look over the week-end.

Regarding the commits themselves, I think it could be nice to merge them all into one commit, as they are all more or less related to the same thing (i.e. adding a stop button + remove button). It would also remove the unnecessary noise of the indentation change in a6442b8 and f94d4f7 + 53195bd, as the end result would be what this shows: https://github.com/godotengine/godot/pull/3339/files

To do so, you'll have to use ```git rebase -i HEAD~5```(or more than 5 if needed, I'd have to check, you need to be able to see all commits up to the first one, but I think the merge commits won't be shown) with git CLI. If you're using a git GUI, then I'm not sure how to do it :)

In the interactive rebase mode, it should open a text editor with the last commits listed, something like:
```
pick b89464a add stop button to each sample item on sample library.
pick a6442b8 fix identation
pick 8267d52 fix range dB and Pscale
pick f94d4f7 change to toggle button and add remove button
pick 53195bd revert changes over tree and sampele_player code
```

You can then change it to:
```
reword b89464a add stop button to each sample item on sample library.
fixup a6442b8 fix identation
fixup 8267d52 fix range dB and Pscale
fixup f94d4f7 change to toggle button and add remove button
fixup 53195bd revert changes over tree and sampele_player code
```
and then save and quit the editor. "fixup" means "merge into the previous commit and discard this commit's log message", and "reword" will show a new editor so that you can change the log of the first commit (then you can mention for example the fact that you also added a delete button, and maybe also rephrase the initial log to say that you made the play but toggleable as "play/stop").

Once this is done, if everything goes fine, you should see only one commit on top of the master branch in ```git log```. ```git show``` should show that all your changes are in it.

You can then update this pull request by force pushing to your remote branch.

**Comment by freemanfromgodotengine** [comment]
As there is no normal way to stop playing samples now (I don't count deleting sample from playlist as a normal way to stop it) and if the imported sample is a long one, you have to wait and wait and... I had it like that few time, so I know I would appreciate this one.

**Comment by akien-mga** [comment]
Superseded by #4033.

**Pull request closed without merging**
