### PR TITLE
Move storage for Mesh, MeshInstance, MultiMesh and Skeleton into MeshStorage

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Move storage for Mesh, MeshInstance, MultiMesh and Skeleton into MeshStorage

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Thinking about adding particles into this as well.

**Review by clayjohn — APPROVED** [review]
Looks good to me. 

I don't think there is enough overlap between Particles and Mesh to put particles in MeshStorage. Instead I would do ParticlesStorage that covers Particles and ParticlesCollision.

**Comment by BastiaanOlij** [comment]
@clayjohn yeah that makes sense

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Yes I agree particles actually does have a lot of code, which would be best it goes its separate class.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
