### PR TITLE
Added first batch of svg icons

### PR DESCRIPTION
**Pull request by djrm**

### CODE REVIEW

**Comment by reduz** [comment]
wow, you are amazing

**Comment by djrm** [comment]
Thanks

**Comment by akien-mga** [comment]
Sneak peak:
spectacle zb3380

**Comment by akien-mga** [comment]
Those new icons are pretty good, and I'm quite impressed by how fast you could make them :D

There's just ``icon_g_d_script.svg`` that I'm not so fond of, I think the Godot logo itself looks better unaltered, so I'd prefer to keep something like the plain cogs we current have, or maybe reuse the parchment icon from the scene panel.

Also you have both ``icon_node`` and ``node`` ;)

**Comment by nunodonato** [comment]
@reduz do we really need to color the icons? I was thinking one advantage of making it just all white is that we could then modulate the color in the editor as we see fit. That way we could save time not doing repeated icons with different colors (node, sprite), and will also give us the possibility of later changing colors in a few places, if necessary, without changing the icons again.

**Comment by oliver-ruehl** [comment]
I agree with nunodonato

**Comment by djrm** [comment]
I do agree, the script that exports to png (to be written) could handle the coloring of the icons, and certain transformations, like rotation for the progress icon

**Comment by nunodonato** [comment]
the only disadvantage to that is that icons must stick to a monochrome style. So for instance, those questions marks and check marks that you have above, could not have the white in the middle. I guess its a matter of weighting the pros and cons

**Comment by bojidar-bg** [comment]
@nunodonato We can always adapt them so they look nice with transparency in the middle :smile: Also, we can have a few icons (like the question mark) that are exempt from the monochrome rule.

**Comment by djrm** [comment]
the more important ones are the node icons since there are lots of them, and it could save some time to have only one version of them, also there are some dimmed versions for dissabled icons, avoid those could also save some time.

**Comment by akien-mga** [comment]
If we're going for shades of grey, make sure to define precisely which shapes should be used for what, so that they end up being colored the same when modulated in the editor. (i.e. all 2D nodes should use the same grey to be modulated to the same blue in editor).

**Comment by nunodonato** [comment]
yeah, would be nice to have a small style guide for this.

perhaps decide a few fixed shades and where to use each one


Às 15:35 de 30-05-2016, Rémi Verschelde escreveu:
>
> If we're going for shades of grey, make sure to define precisely which 
> shapes should be used for what, so that they end up being colored the 
> same when modulated in the editor. (i.e. all 2D nodes should use the 
> same grey to be modulated to the same blue in editor).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/godotengine/godot/pull/4897#issuecomment-222505426>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABkOH1mbZ3ror4FnoopkG3-BuTGsKL6Vks5qGvWqgaJpZM4Ipcm9>.
>

-- 
Nuno Donato
nuno@estudiodigital.pt | 966956602

estúdio digital <http://www.estudiodigital.pt>
www.estudiodigital.pt
Programação e Artes Digitais

**Comment by djrm** [comment]
Probably i could make a style guide, with instructions on how to make the icons, and the metrics used, so future contributors can replicate the icons style.

**Comment by reduz** [comment]
Just make it 1:1 as the .png files around, please don't change everything,
specially the color codes

coloring the icons using code is simply more work than with
inkscape/illustrator. It's not a problem if the same icon is repeated with
different colors

**Comment by djrm** [comment]
The problem is that having 16x16 svgs leaves no space for border, so the border have to be coded in the gui, also, a problem with having repeated icons, is that we have to replace all of them when we modify some icon that happens to be repeated, i dont think that tinting the icons in the godot code is a good idea either (unless we use the svgs directly in the editor, which doesnt seem to be a good idea either), but i think a script can handle that task, so no modifications in godot are needed.

Also im only modifying color codes for the icons that didn't have a color code to begin with, i left color codes untouched for control, 2d and spatial nodes, also all the editor icons have their original color.

**Comment by alelepd** [comment]
Yeah. Its finally happen. Vector icons and hpdi UI :D
@djrm Congrats! these icon are nice improvement!
I noticed you are using a 32x32 grid. Looks that I can work with that. Hope I can help with something.

So far I think the checkmark and question icons need more contrast. The white on top of the light green is hard to read, same with the white on top of the yellow.

The save icon is still too abstract I think (but maybe that justs my perception). On the godot icon, maybe you can try by removing the inner circles on the eyes (to become holes instead of rings) and the last (right) square on the mouth.

The hand works fine on 32x32 both a smaller sizes the space between fingers begin to dissapear.

Minor thing: anychange the loop icon could be fully symmetrical? the bottom margin is bigger than the top one.

**Comment by djrm** [comment]
Im currently working on 16x16 icons, they look better on standard DPI screens, about the contrast, its hard to read on white background but godot uses a dark bakground.

About the symmetry, i wish i could do all icons symmetrical but, i have to align them to pixel boundaries, so they look good when exported.

**Comment by alelepd** [comment]
Mm, I wasn't talking about all the icons, that's maybe too hard. But in the case of the loop it is posible. In fact, the current icon is not fitting well on pixels. Here are some alternatives, they all fit well on the pixel grid of 32. I also did some 16x16 grid version, which also fit perfect on pixels.

godot_icons_example_grid

And this is real size example:
godot_icons_example_realsize

Btw, I also geeky about icons (I have designe many in the past for user interfaces), so I do understand the process of getting everything pixel perfect or proportionally right in many resolutions ;)

**Comment by djrm** [comment]
mm the new 16x16 i made looks exactly as the one you proposed, i going to make a PR, and then you can check the icons that are already done, so we do not repeat work, also you can modify directly in the source if you like.

**Comment by djrm** [comment]
The development of the icons is now [here](https://github.com/djrm/godot-design), please join if you are interested with godot design

**Comment by alelepd** [comment]
This is great!

**Pull request merged**
