### PR TITLE
2D Physics bodies documented.

### PR DESCRIPTION
**Pull request by Ovnuniarchos**
PhysicsBody2D and its descendants have been documented. The meaning of the values for friction and bounciness is left almost unexplained, as I couldn't find an appropriate explanation.

### CODE REVIEW

**Comment by Ovnuniarchos** [comment]
Oops! Thanks!

**Comment by akien-mga** [comment]
Could you maybe merge all commits into one, this will get rid of the WIP stuff that you committed like those TODO comments. Those things should not appear in commits but stay on your end while you're working on stuff :)

**Comment by akien-mga** [comment]
To merge all commits into one you can do:
```
git rebase -i HEAD~6
```
Then in the editor that shows up, change the first "pick" words to "r" for the first one (to be able to reword it), and "f" for all subsequent ones (so that they are merged into their parent and the commit log discarded), i.e.:
```
r 39575ee Area2D documented
f 28571a0 PhysicsBody2D documented
f 06f8374 RigidBody2D (sans friction) documented.
f 940b612 KinematicBody2D documented.
f 7884d53 All 2d bodies documented.
f 7988a39 "Linear" mistake corrected.
```
Then upon saving and closing the editor it should ask you to reword the first commit, and then it will perform the merge.

**Comment by Ovnuniarchos** [comment]
I found a problem with doctool, though. It insists that KinematicBody2D.get_collider_metadata returns void when, in fact, it returns Variant. (tested)

**Comment by akien-mga** [comment]
Thanks for the rebase, it looks great.
I'll have a look at the issue you mention for KinematicBody2D.get_collider_metadata; it's likely a bug in the binding if it's misinterpreted by doctool.

**Pull request merged**
