### PR TITLE
Use relative path property hint for windows export icon

### LINKED ISSUE #25513: Picking a Windows icon file in the export dialogs sets a local path
**Godot version:**
463123a

**Issue description:**
When picking a Windows icon file (.ico) for the Windows export preset via the FileDialog, it will set it as a local path, instead of a relative one ("/home/user/project/icon.ico" instead of "res://icon.ico").

### PR DESCRIPTION
**Pull request by Kanabenki**
Closes #25513

### CODE REVIEW

**Comment by Calinou** [comment]
I remember seeing the `res://` prefix causing issues with rcedit (which is used to [change the application icon on Windows](https://docs.godotengine.org/en/latest/getting_started/workflow/export/changing_application_icon_for_windows.html)). Here in one of my projects, [I wrote just `icon.ico` by hand in the export preset](https://github.com/Calinou/escape-space/blob/ddfee8392dce366b57203ff3693ffa5301dffc92/export_presets.cfg#L46) instead

**Comment by Kanabenki** [comment]
Thanks for the info, I added the path globalization before executing rcedit and it seems to be working.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
