### PR TITLE
Fix particle trail glitch

### LINKED ISSUE #54771: Particle trails glitch for the first frame they are visible
### Godot version

v4.0.dev.custom_build [ce634e03d]

### System information

Linux Arch, Radeon RX 590

### Issue description

Trails connect to the origin (of the particle system if in local coords, of the world if not in local coords) in the first frame in which they are visible. Length secs of the trail doesn't seem to influence the length of the glitch.

https://user-images.githubusercontent.com/7917475/140791807-bf21b971-37b2-417e-81a9-ce92d7743637.mp4

See in particular:
Screenshot_2021-11-08_18-39-45

### Steps to reproduce

Open "TrailTest.tscn" in the provided reproduction project

### Minimal reproduction project

[GodotVFX4.zip](https://github.com/godotengine/godot/files/7498984/GodotVFX4.zip)

### LINKED ISSUE #55842: Vulkan: GPUParticles trail leave a trail towards world origin when dying
### Godot version

4.0

### System information

Arch Linux, KDE Plasma, Radeon RX580, amdgpu driver

### Issue description

Here's what happens when the lifetime randomness is disabled (set to 0) - the problem doesn't occur:
https://youtu.be/O39GyzSdZfc

Here's what happens when lifetime randomness is at maximum (set to 1) - this produces unwanted erronous streaks:
https://youtu.be/WCQGEkOHSxM

### Steps to reproduce

1. Create a particle system with a ribbon mesh using particle trails and explosiveness at 1.0
2. Now enable life time randomness.

Observer as particles that die before the full cycle resets go back to the world origin, creating unwanted trails.

### Minimal reproduction project

[SSIL Test.zip](https://github.com/godotengine/godot/files/7697903/SSIL.Test.zip)
(the project was made to play with the SSIL feature preview).
Built from commit 0eff109a21fb5c0bd031a91c540983e77e75343b (clayjohn/Vulkan-ASSGI)

### PR DESCRIPTION
**Pull request by floppyhammer**
- Fixes https://github.com/godotengine/godot/issues/54771
- Fixes https://github.com/godotengine/godot/issues/55842.

### CODE REVIEW

**Comment by TechnoPorg** [comment]
This is great! I was also working on #55842, but I was nowhere near a solution. I really like this fix, because it will work for any situation, for example in a custom particle shader, where a trailed particle is deactivated.
If I understand correctly, though, the particle trail will still be emitting, but at the position where the trailed particle stopped. That could maybe cause spots at those points, which isn't desirable. If that doesn't happen, this behaviour seems fine, since ceasing emitting the trail would likely require slowing performance more than it would increase performance.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
I don't think this is a good fix, it will break when inactivating regular particles.

**Comment by reduz** [comment]
Correct fix is likely considerably more involved. This one needs revert.

**Comment by reduz** [comment]
My feeling is that possibly the solution could be to ensure particle is inactivated when not restarted, this would make this PR actually work, but it needs more testing in different use case scenarios.

**Comment by floppyhammer** [comment]
@reduz You are right. I went through more tests and see the problem. Besides that, I made another mistake.
```gdsript
// Set scale zero to make it invisible.
    txform[0].xyz = vec3(0);
```
should be 
```gdsript
// Set scale zero to make it invisible.
    txform[0].xyz = vec3(0);
    txform[1].xyz = vec3(0);
    txform[2].xyz = vec3(0);
```
Yes, we need to revert this.

**Pull request merged**
