### PR TITLE
Remember Template checkbox in Create Script Dialog

### LINKED ISSUE #67988: Disabling script template is not remembered after editor restart
### Godot version

4.0 11e1bac

### System information

Windows 10 x64

### Issue description

When you disable script template to have an empty script, it will only be remembered until you exit the editor. Next time you will have to disable it again. Pretty sure it wasn't like that when the feature was implemented for the first time.

### Steps to reproduce

1. Add script to node
2. Uncheck this
image
3. Restart the editor
4. It's enabled again

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dalexeev**
Closes #67988.

### CODE REVIEW

**Comment by KoBeWi** [comment]
This will work per-project, not globally like it used to before.

**Comment by dalexeev** [comment]
> This will work per-project, not globally like it used to before.

It seems to me that this is a more correct option, since different projects may have different templates. In addition, quite a lot of other metadata of the editor is also bound per project, not globally (for example, advanced mode of the Project Settings editor, dialog rects).

Perhaps this case (removing the necessary metadata in #59603) happened only because the `set_meta` solution looks more like a hack, due to the fact that there is `set_project_metadata`.

**Comment by KoBeWi** [comment]
> It seems to me that this is a more correct option, since different projects may have different templates.

Well my problem is that whenever I open a project for the first time, I always use the default template by mistake, until I finally set empty template after a few scripts. It was annoying to me and I was very happy when #53957 finally resolved this issue. Templates for node type can be per-project, but disabling templates altogether should be a global thing.

> the set_meta solution looks more like a hack

idk, I thought it's a clever solution when I first seen it, because it allows to have editor settings that don't show in the settings dialog. Although you can probably achieve the same by using `_`.

**Comment by YeldhamDev** [comment]
> the set_meta solution looks more like a hack
> > idk, I thought it's a clever solution when I first seen it, because it allows to have editor settings that don't show in the settings dialog.

`set_meta` would still be fine as long it's properly commented as to why it's being used.

**Comment by akien-mga** [comment]
Superseded by #69443.

**Pull request closed without merging**
