### PR TITLE
fix area2d monitorable changes

### LINKED ISSUE #23484: Area2D doesn't update its overlapping areas when monitorable changes in the areas it's overlapping
**Godot version:**
3.1 alpha2 mono x64

**Issue description:**
An area that is monitoring will never detect that an area exited if the other area leaves while it is not monitorable and will remain in the list returned by get_overlapping_areas. Similarly  an area that is monitoring will never detect that an area entered if the other area enters while it is not monitorable and switches to monitorable while it's inside.
**Steps to reproduce:*
This can easily be reproduced with a static area switches between monitorable and not monitorable and another area that checks if get_overlapping_areas is empty

**Minimal reproduction project**
[Area2DProblem.zip](https://github.com/godotengine/godot/files/2545259/Area2DProblem.zip)

### PR DESCRIPTION
**Pull request by Raphael2048**
close #23484

I know we shouldn't use dynamic_cast in our codes, but I can't find a better solution, what should I do to cast `Constraint2DSW` here?

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Wouldn't this work with just:
```c++
if (!moved_list.in_list() && get_space())
		get_space()->area_add_to_moved_list(&moved_list);
```
Added to `set_monitorable`?

**Comment by raphael10241024** [comment]
> Wouldn't this work with just:
> 
> ```c++
> if (!moved_list.in_list() && get_space())
> 		get_space()->area_add_to_moved_list(&moved_list);
> ```
> 
> Added to `set_monitorable`?

It doesn't works.
Firstly, we must remove this:https://github.com/godotengine/godot/blob/4357be1072c18361314913b423bfeebcb0d13f4b/servers/physics_2d/area_2d_sw.cpp#L173
We shouldn't change it's status to static
Secondly Area2DPair only refresh montinor status when it's collision status changes
https://github.com/godotengine/godot/blob/4357be1072c18361314913b423bfeebcb0d13f4b/servers/physics_2d/area_pair_2d_sw.cpp#L98-L130
So I think it's a good time point to reset it here

**Comment by aaronfranke** [comment]
@raphael10241024 Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by akien-mga** [comment]
I guess this is superseded by #41698? @madmiraal

**Comment by madmiraal** [comment]
> I guess this is superseded by #41698?

Yes, assuming #41698 is merged. ;-)

**Comment by aaronfranke** [comment]
Closing as abandoned by the author, and also #41698 supersedes this (although it's not merged yet).

**Pull request closed without merging**
