### PR TITLE
Correct jitter in move and slide 2D

### PR DESCRIPTION
**Pull request by fabriceci**
I fixed a remaining jitter in the function and clean a bit of code.

Before (slowdown to see the jitter)
jitter

After
fixed

### CODE REVIEW

**Review by pouleyKetchoupp — APPROVED** [review]
Looks good and didn't spot any regression.

**Comment by TokageItLab** [comment]
Is this PR solve [jittering on slope edge problem](https://github.com/godotengine/godot/pull/51027#issuecomment-892158467)?

**Comment by fabriceci** [comment]
@TokageItLabThis was already fixed, this jitter is a new one.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
