### PR TITLE
[AudioStreamPlayer/2D/3D] Reduce the max value of pitch_scale's inspector slider

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by akien-mga** [comment]
Why?

**Comment by WARIO-MDMA** [comment]
32x playback speed is way too fast for pretty much anything; currently, most of the `pitch_scale` property's slider range turns your audio into an unintelligible mess. Limiting it to 4x keeps things sane.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Pull request merged**
