### PR TITLE
Fixed an issue in UWP export caused by duplicate entry for extensions in content types file.

### PR DESCRIPTION
**Pull request by Anutrix**
Thx to @ZodmanPerth. Info at https://github.com/godotengine/godot/issues/30558#issuecomment-667926124.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by ZodmanPerth** [comment]
@Anutrix I'm trying to test this fix on 3.2.  I've cherry picked the fix onto the 3.2 branch, added the `UWP_ENABLED` preprocessor directive to the Godot solution and got it compiling.  However the UWP export is missing, so I need to generate the template.

To continue I've been trying to build the UWP export template.  I've installed the prerequisites as per the [instructions](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_uwp.html) and am running `scons platform=uwp target=release_debug`.

Things are compiling properly up until I get the following error:
```scons
[Initial build] Compiling ==> thirdparty\libvpx\vp8\common\arm\neon\loopfiltersimplehorizontaledge_neon.c
cl : Command line error D8004 : '/AI' requires an argument
scons: *** [thirdparty\libvpx\vp8\common\arm\neon\loopfiltersimplehorizontaledge_neon.uwp.opt.debug.32.arm.obj] Error 2
scons: building terminated because of errors.
```
Side note: To get Angle to compile I ended up retargeting the platform to 142 (Visual Studio 2019) from 140 (Visual Studio 2015).  I'm wondering if there's a subtle difference causing the problem.

Do you have any advice on how I can proceed, or alternative way to test this fix?

**Comment by Anutrix** [comment]
@ZodmanPerth Thx for testing it. It would be better if you make new issue about this. We can discuss it there.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
