### PR TITLE
Adds Object::set_script_and_instance

### PR DESCRIPTION
**Pull request by neikeq**

### CODE REVIEW

**Comment by karroffel** [comment]
This would solve #9721's problem in a cleaner way. 👍

**Comment by neikeq** [comment]
Superceded by 3b2dfae

**Comment by endragor** [comment]
@karroffel 
It doesn't solve the problem entirely, unless I'm missing something. At best this can replace NativeScript::_new call, but what about the rest? We need to obtain and instantiate the script from its name, that's the major part.

**Comment by karroffel** [comment]
@endragor 

```cpp
Object *parent = memnew(WhateverTypeYourScriptExtends);

NativeScriptInstance *inst = memnew(NativeScriptInstance);
inst->userdata = <<your allocated data here>>;
inst->owner = parent;
inst->script = the_type_of_script;

parent->set_script_and_instance(inst->script, inst);
```

That should go into a native wrapper of course, but that's how it would work.

**Comment by endragor** [comment]
Yeah, as I said, you are talking about the easy part. That function from #9721 looks simple/clean: https://github.com/godotengine/godot/pull/9721/files#diff-428ed07c01d088154b3ba4a22db10a14R193

The problem is getting `the_type_of_script` (in your sample) from `class_name`, that's where the dirty part is.

**Comment by karroffel** [comment]
The problem is that two different libraries can register two classes with the same name, so you need to know *which* library you're referring to. If you want to do that from within a library then you can save a ref to the used GDNativeLibrary and use that to construct such a script on the fly.

**Comment by endragor** [comment]
Yes, it is the main problem. We can look up the current library, but I don't think it's the best solution conceptually. Even looking up all native libraries like #9721 does is not enough. The native script code could be made aware of the presence of other scripts and types defined in them (like it is made aware of native types). In that case it could query a kind of ScriptDB to construct the object by its name (and maybe namespace to help with clashes). The ScriptDB would then use the constructor registered by corresponding scripting language and return the object. That way different languages/bindings could interact seamlessly.

**Pull request closed without merging**
