### PR TITLE
Refactoring of 2d polygon editors

### PR DESCRIPTION
**Pull request by ghost**
Refactoring needed for #10618.

Still work in progress.

### CODE REVIEW

**Comment by poke1024** [comment]
OK, I guess this should be it. Maybe someone else wants to take a look. Does not yet include anything of #10618 as I think it's cleaner to do and commit the refactoring first.

**Comment by groud** [comment]
I think the refactoring should be deeper than that. To understand what I mean is that for the moment we have something like:
- Polygon2d extends the Node2D class,
- NavigationPolygon extends Resource, NavigationPolygonInstance extends Node2D 
- CollisionPolygon2d extends the Node2D class.

To have something more consistent, we should have:
- Polygon2d as a Resource
three type of nodes extending Node2D:
- PolygonInstance
- NavigationPolygonInstance
- CollisionPolygonInstance
(The names should be discussed)

Then when you select one of those node, you in fact edit the resource polygon instead. Like with the AnimationPlayer (when you select it you edit the related Animation resource)

Once we have that I think we should have a good base to start creating a flexible editor.

**Comment by poke1024** [comment]
I think I get the resource polygon idea, but I'm not familiar enough with Godot and the code to pull it through. Wouldn't changing Polygon2D and CollisionPolygon2D into resources and adding PolygonInstance and CollisionPolygonInstance have an immediate effect on how we compose those nodes in the Godot editor, just like it's with NavigationPolygonInstance right now? I'm just not sure I really understand. Users would no longer add a Polygon2D, but instead a PolygonInstance to where they'd (auto-)attach a Polygon2D. Is this how it should work?

One problem we have is that we are actually dealing with three kinds of polygons: a set of outlines for navigation, one outline for collision, and one polygon (meaning outline + uv + texture) for the regular Polygon2D. For now I've added a EditablePolygon2D that interfaces/abstracts these three forms into one common form the editor can work with. I imagine EditablePolygon2D could be inherited from Resource and then specialized, so basically EditablePolygon2D could then be the central resource the editor deals with, as @groud described it.

**Comment by toger5** [comment]
What about waiting until mesh2d is introduced. (for the really clean implementation that group proposed)
Since a polygon as a resource is basically the same than a mesh2d (at least how I think of a mesh2d).
So I think working on a unified editor for now is a good idea. And keeping the structure of different polygons for collision, draw_polygons... is fine, for now. Since when introducing mesh2d it would be nice to replace all the polygons anyways so there will be some additional work than.

**Comment by Zylann** [comment]
@toger5  A Polygon2D isn't exactly like a Mesh2D, but more like a kind of Mesh2D. It exposes an interface where you define anticlockwise/clockwise points. Also, collision polygons must handle convex and concave status.
A Mesh2D, on the other hand, can be the result of the triangulation of a Polygon2D, but not only that. It can have holes, have islands, or even not be a polygon but just a bunch of lines or points.

**Comment by poke1024** [comment]
@toger5 @Zylann Thanks for clarifying Mesh2D. Mesh 2D is the right general idea though, there has to be some kind of generic abstraction the editor can work with. There are really two dimensions one has to model here:

* polygon type
	* pure outlines (CollisionPolygon2D, NavigationPolygon)
	* textured, colored polygons (Polygon2D)
* cardinality
	* one polygon (Polygon2D, CollisionPolygon2D)
	* multiple polygons (NavigationPolygon)

One side detail is that all this has to support undo/redo semantics, so there has to be some partner involved that is derived from Object (pure Resources are not eligible).

This diagram shows the state of things in 94b1064 of this PR:

diagram-new

The idea here was to introduce EditablePolygonNode2D that offers everything the editor works with. Open for discussion.

**Comment by poke1024** [comment]
Some more experimental brainstorming on structure/terminology (implemented in 0655302, some terms adapted from http://esri.github.io/geometry-api-java/doc/Polygon.html):

- A set of vertices that defines a closed outline is called a ring (`Ring2D`). Rings are `Resource`s.
- The shape of a polygon is defined by 1 or more rings. A polygon without holes consists of exactly one ring. A polygon with holes consists of >= 2 rings.
- A simple polygon (without holes) without additional graphical attributes can be represented using just a `Ring2D` (e.g. `CollisionPolygon2D`).
- A `Polygon2D` is a `Resource` attached to a `PolygonInstance`.  `Polygon2D` consists of a `Ring2D` and graphical attributes like uv, texture, etc.
- A `Mesh2D` would consists of several `Ring2D`s and graphical attributes (and an internal trimesh?)

poly1
poly2
poly3

A `PolygonNode2D` is a `Node2D` that contains one or more polygons, e.g. collision or navigation polygons. There's some interface that allows the polygon editor to access and manipulate its polygons and rings using a single, generic implementation, something like this:

```
	virtual int get_polygon_count() const = 0;
	virtual Ref<Resource> get_nth_polygon(int p_idx) const = 0;
	virtual int get_ring_count(Ref<Resource> p_polygon) const = 0;
	virtual Ref<Ring2D> get_nth_ring(Ref<Resource> p_polygon, int p_idx) const = 0;

	virtual void add_polygon(const Vector<Point2> &p_vertices);
	virtual Ref<Resource> new_polygon(const Ref<Ring2D> &p_ring) const = 0;
	virtual void add_polygon_at_index(Ref<Resource> p_polygon, int p_idx) = 0;
	virtual void remove_polygon(int p_idx) = 0;
```

classes

**Comment by Zylann** [comment]
I might have been misunderstood here: I think that wether it's a ring, concave or convex polygon to edit, I believe the underlying resource could be down to a Mesh with only X and Y components, in places where using a 2D mesh is relevant. Remember that as far as the renderer is concerned, it only needs a soup of triangles, lines or points. So you could have, say, an ArrayMesh2D for arbitrary meshes or meshes imported from a 3D editor, then you could also have PolygonMesh2D, CircleMesh2D, RectangleMesh2D for procedurals (similar to 3D).
I'm still curious about what @reduz has in mind though.

**Comment by poke1024** [comment]
Yes, I think I understand. Still there might be cases where there has to be some abstraction for the (polygon) editor as is now the case for the navigation polygons (which take "outlines" and then build vertex pooled polygons) and the collision polygons. In that way some variants of mesh2d might build/compile its renderable triangle mesh from some higher level polygon representations. I don't know. On the highest level, in the polygon editor UI code, a polygon/rings abstraction looks nice to implement against and that code is where I'm currently coming from here. But I'm really just dabbling around, trying to get some ideas that might turn out useful.

**Comment by reduz** [comment]
Resource Polygon is too much IMO, maybe in the future but I honestly don't
think we need this right now.

Also, by the way, Navigation allows you to draw many polygons, so you can
make holes in it, is this supported?

**Comment by poke1024** [comment]
@reduz You're right, creating holes using navpolys works fine using several polys. Closing this PR to come up with something much smaller and more focused to just refactor the polygon editor (without changing any polygon related API).

**Pull request closed without merging**
