### PR TITLE
Android: Remove redundant semicolons from Kotlin/gradle files

### PR DESCRIPTION
**Pull request by melquiadess**
As in subject, probably a Java habit remnants ;)

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
This makes sense as per the Kotlin style guide: https://kotlinlang.org/docs/coding-conventions.html#semicolons

PS: Please double-check you've removed *all* semicolons from the Kotlin codebase (other than third-party files), so that we don't need a follow-up PR.

In the long run, we may want to set up a Kotlin linter/formatter on CI.

**Comment by melquiadess** [comment]
> PS: Please double-check you've removed _all_ semicolons from the Kotlin codebase (other than third-party files), so that we don't need a follow-up PR.

According to Android Studio - that is the case (the ones shown are valid)

image

But that reminds me - some `.gradle` files also contain a few stray semicolons - fix coming imminently...

> In the long run, we may want to set up a Kotlin linter/formatter on CI.

👍

**Review by m4gr3d — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
