### PR TITLE
Cherry pick IPv6 patches to 2.1.x

### LINKED ISSUE #7129: IPv6 for Godot 2.1.x
The recently-implemented IPv6 support in the master branch seems to behave, at least @punto- reports that some guys were able to publish their iOS game without any trouble (so Apple did not complain about missing support - and I suppose the game worked too :)).

There have been quite a few commits about this, so instead of trying to cherry-pick them myself, I'd like someone who understands this stuff to do it :)

@Faless Would you mind preparing a pull request to the 2.1 branch to add all the IPv6-related commits?

You can cherry-pick with `git cherry-pick -x <commit-hash>` - the `-x` part adds the hash of the original commit to the description of the cherry-picked commit, I'm using this as a convention for better traceability.

### PR DESCRIPTION
**Pull request by Faless**
This PR includes the 2 main IPv6 patches (#6925 and  #6981) plus a small fix for the windows build script to include the proper socket library.

I managed to get a build for Windows, Linux, and OSX. So far so good.
Closes #7129 .

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks! Just one thing: is it OK to use merge commits to cherry-pick new developments instead of cherry-picking the individual commits? Personally I tend to discard merge commits mentally as noise, and wouldn't expect them to be the actually implementation of a feature.

**Comment by Faless** [comment]
> Personally I tend to discard merge commits mentally as noise, and wouldn't expect them to be the actually implementation of a feature.

@akien-mga , I see your point, I'll rebase everything cherry picking the single commits.


Additionally, I might have found a problem with the current IPv6 implementation on Android, I'm looking into it, but I think we'll need another commit on the master branch before merging this :(

**Comment by Faless** [comment]
I rebased the branch and cherry picked each single commit.
We need to wait for #7271 to be merged into master (for android, tcp, and hostname resolution fixes) than I'll push the additional cherry picked commits here.

**Do not merge yet.**

**Comment by Faless** [comment]
@akien-mga I added all the commits from #7271 as requested there.

**Tested compile**: linux/windows/osx/android/iphone
**Tested behavior**: linux/windows/android

@punto- and I also discussed another fix for TCP `connect`. It only affects OpenBSD users, I will make another PR for it.

**Comment by akien-mga** [comment]
Awesome work, thanks!

**Pull request merged**
