### PR TITLE
Add relative pivot to control nodes

### PR DESCRIPTION
**Pull request by creikey**
Continuation of #30305 due to my previously poor branch management skills ( not the business kind ).

### CODE REVIEW

**Comment by groud** [comment]
The implementation looks good, we only need to decide whether or not the feature is desired.
Personally, I believe it makes sense to have it.

**Comment by Zireael07** [comment]
I would love the ability to have a relative pivot - I have been faking it by using Node2D's or dummy controls so far.

**Comment by KoBeWi** [comment]
Needs rebase. Also the pivot tool is broken when relative offset is non-zero.

Here's a related proposal: https://github.com/godotengine/godot-proposals/issues/129
It has considerable support. The PR doesn't implement it fully, but it's a good start.

**Comment by YuriSizov** [comment]
Superseded by https://github.com/godotengine/godot/pull/70646.

**Pull request closed without merging**
