### PR TITLE
Change godot.ico to uncompressed/fixed size

### PR DESCRIPTION
**Pull request by pkowal1982**
I think it should go into 3.x first but as the workflow says that master should precede everything, I'm creating PR to master.

Change is small and unobtrusive but fixes some Windows exporting issues.

Using windows icon file which is uncompressed (has fixed size) allows for easy icon replacement even in executables with pck embedded. Of course replacement icon should have the same size.
To create such icon you'll need a tool which I've happily already created:

:arrow_right: https://github.com/pkowal1982/godoticon :arrow_left:

Don't worry, no external tools needed.

## How to use it:
1. Prepare your icon (or icon versions in proper resolutions) in graphics editor
2. Convert created graphics into icon with provided script: https://github.com/pkowal1982/godoticon/blob/master/CreateIcon.gd
3. Export your game with proper windows template (template should use fixed size icon)
4. Replace default icon with the one created in the second step using script: https://github.com/pkowal1982/godoticon/blob/master/ReplaceIcon.gd

Pros:
- Works with embedded pck (no need to recompile template with custom icon, official one should work)
- No need to download/use magick
- No need to download/use rcedit which becomes real pain in the ass if you're using Linux. If you still like to use rcedit you can, it should work as before but also for executables with embedded pck
- Just run these Godot scripts from console, no external tools needed, it's system independent

Cons:
- uncompressed Windows template/executable is bigger by 243 KB

### CODE REVIEW

**Comment by Calinou** [comment]
This effectively reverts https://github.com/godotengine/godot/pull/9285, but I guess it's fine as 250 KB isn't so much for a Windows binary by 2022 standards.

**Comment by pkowal1982** [comment]
Padding description with spaces should work. Extending the replacement script should be easy basing on what's already implemented and it can be done independently of this PR as I assume there are some decisions to be made about version "fixed" format which can take time.

**Comment by aaronfranke** [comment]
Is there a reason that we can't make it easy to change the icon during export instead of using icon replacement tools after export?

**Comment by bruvzg** [comment]
> Works with embedded pck (no need to recompile template with custom icon, official one should work)

It's easy to fix by running `rcedit` before embedding PCK, see #56093. But adding an extra 200 KB isn't an issue. And it won't break anything, so it should be fine.

**Comment by pkowal1982** [comment]
@aaronfranke The reason to use icon replacement tool is, that this tool already exists and all it needs is merging this "fixed" icon to master and 3.x branches. If someone will rewrite logic from the script to the editor itself it won't need external tools anymore. But it will still need this fixed size approach.
@bruvzg rcedit is fine if you're using Windows for development. Running rcedit on Linux it's not so easy. :)

**Review by Calinou — APPROVED** [review]
I think the pros outweigh the cons here, so we can give this a try in `master` at least (and then consider it for `3.x`).

Compressed binary size (e.g. within a ZIP) shouldn't be affected much by this change, so download times for editor and export template binaries should remain almost identical.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by hsandt** [comment]
Sorry to comment on an old PR, but that sounds like a nice alternative to rcedit, shouldn't it be more promoted and added to the doc (https://docs.godotengine.org/en/stable/tutorials/export/changing_application_icon_for_windows.html)? Is it an issue because it is third-party code and cannot not fully endorsed by the Godot team?

Also, to avoid the leftover warning in the export popup:

> The rcedit tool must be configured in the Editor Settings (Export > Windows > rcedit) to change the icon or app information data.

and on build:

> WARNING: Resources Modification: Could not start rcedit executable. Configure rcedit path in the Editor Settings (Export > Windows > rcedit), or disable "Application > Modify Resources" in the export preset.

It seems we must disable "Application > Modify Resources" so Godot doesn't try to access rcedit. Can you confirm that it won't have other side effects, and that the only "modified resource" is the icon?

Finally, we could add the hint about disabling "Application > Modify Resources" to the first warning, in the export popup, so the user doesn't have to wait for an actual export to see the hint in the second warning.

If you're okay with this, I'll open respective issues in godot-docs repo and godot-proposals.

**Comment by pkowal1982** [comment]
@hsandt You should probably look at https://github.com/godotengine/godot/pull/75950

**Pull request merged**
