### PR TITLE
[WIP] Pack of enchancements for help in Shader/VisualShader

### PR DESCRIPTION
**Pull request by Chaosus**
Changes:

- New buttons (under new _Help Tab_) _Online Docs_ and _GLSL Docs_ added to the status bar of opened shaders - they will open Godot Shader page and Khronos GLES3 reference by pressing respectivly

_Online Docs_ references to http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/index.html

_GLSL Docs_ references to https://www.khronos.org/registry/OpenGL-Refpages/es3/html/index.php

image

- New information popup to replacing old ugly tooltip.

demo:
popup

It solves problem where you cannot see the full parameter list due to restriction of this tooltip

image

I provide information about parameter names, so instead 

image

You can now see its names like

image

For built-in functions it also have a button which opens the docs on Khronos page in your browser

image

^^ for _clamp_ it will opens the https://www.khronos.org/registry/OpenGL-Refpages/es3/html/clamp.xhtml

### CODE REVIEW

**Comment by Chaosus** [comment]
Fix VisualShader built-in descriptions to be equal to the Shader(which help the translation). I leave it untouched only for Step and Smoothstep. "(GLES3 only)" now will be apply procedurally rather to be a part of  the description.

**Comment by groud** [comment]
It's a little bit inconsistent with the rest of the editor. I'd rather improve the tooltip itself (by implementing a scrollable tooltip or increasing its size) than adding a right panel used nowhere else.

**Comment by Chaosus** [comment]
Ok, will look at this soon..

**Comment by Chaosus** [comment]
As @groud requested I pushed the new popup into TextEdit

image

^ It shows first 4 overloads - the other will be visible when user scroll down this list

**Comment by groud** [comment]
Well, that's not really what I meant. I think the old style was better as a lot more compact, but needed only few improvements.

If we want something good, we could have a look to what Eclipse does. Their completion tool keeps a compact list for the available options, but displays a second tooltip (it could be a side panel inside our tootip in our case) to display the documentation of the selected entry in the completion list:
687474703a2f2f692e737461636b2e696d6775722e636f6d2f5756707a542e706e67
(We can make something nicer though, but the idea is here ^^)

**Comment by Chaosus** [comment]
>  I think the old style was better as a lot more compact, but needed only few improvements.

The old style doesnt use the controls at all - its using raw draw_string calls. I can modify the new one to be appear like the old one..

**Comment by Chaosus** [comment]
Ok, I cut-off this feature, if its not desired in the presented view..

**Comment by Chaosus** [comment]
I better subdivide this PR into smaller parts, closed

**Pull request closed without merging**
