### PR TITLE
[3.x] Give each RigidBody its own DirectBodyState wrapper.

### PR DESCRIPTION
**Pull request by madmiraal**
3.2 version of #42928.

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge of #42168.

**Review by pouleyKetchoupp — APPROVED** [review]
These changes are welcome for 3.x since #49471 would be a bit much to backport.

It just needs a rebase but it should be good to go.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
There's a couple style issues with empty lines at the start of blocks.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
