### PR TITLE
Added ability to edit Animation in Frames instead of Seconds.

### LINKED ISSUE #6149: Option to choose frames or seconds display in AnimationPlayer's timeline
The timeline in AnimationPlayer, by default, shows the time in seconds, and the cursor snaps to the seconds subdivisions instead of individual frames.

timeline

This is not good when importing an external animation made through frames reference (like importing from Blender), and when is needed to have more precision too. I suggest to add an option to toggle the individual frames display (changing the grid and snapping as well).

And a question: Godot have an animation frame rate parameter? Thanks.

### LINKED ISSUE #12165: AnimationPlayer: Ability to Edit Animation in Frames / Steps (in addition to Seconds / Time)
In Godot 2.14, animating using a AnimationPlayer and I am having a painfully slow experience. The issue is the timing in AnimationPlayer is done by seconds and not frames.

Can we add an interim fix that will show the frame number of wherever the timeline head is? Right now I am trying to make a simple NES era style animation and I find that I need to keep my calculator open and keep converting seconds to frames by taking the seconds and dividing it by 30 in order to get the frame number.

I'm thinking adding something like this should be simple, no?

I would also like to see previewing Animation by scrubbing the playhead in the timeline. 

Thoughts?

### PR DESCRIPTION
**Pull request by Piet-G**
Added ability to edit Animation in Frames instead of Seconds. You can now choose which mode you want to edit in seconds/frames with a simple button:

You can also easily change at which framerate you want to edit the animation:

This does not alter any functionality to animations themselves and are contained wholy within the animation editor.

Currently there is still a need for a new icon for the newly introduced button (It will replace the all caps ENABLE_FRAME_MODE).

This is my first PR that's not just a bugfix, so some of the code might be a bit odd, any advice is appreciated!

This fixes #12165 and fixes #6149.

### CODE REVIEW

**Comment by fracteed** [comment]
Oh yeah, thanks for adding this! Many users have been begging for this for while now :)

**Comment by DualMatrix** [comment]
@fracteed Snapping can still be  edited like you could in time mode, the last one just happens to have a snap of 3 because it converts whatever you snap choice was in time mode to frames in this case O.1 -> 3.

As for the highlighting,i have no idea what that is supposed to indicate, it doesn't seem to be the snap setting but I'm unsure what it does indicate. It seems rather odd indeed.

**Comment by fracteed** [comment]
@DualMatrix  so if you are in frame mode and enter a snapping value of 2, you would be snapping to every second frame? I guess the "(s)' text would have to update itself to a "(f)" when switching modes.

**Comment by DualMatrix** [comment]
@DualMatrix Yup that's how it works, and yeah that should probably be done, good catch.

**Comment by avencherus** [comment]
Did a Win10 64-bit build and cherry picked this.  I got this crash and stack trace when clicking on an AnimationPlayer from an existing project that had animation on it, or when making a new AnimationPlayer, the moment after creating a new animation and giving it a name.

cmd_2018-09-28_22-26-07

**Comment by DualMatrix** [comment]
@avencherus That doesn't look good, I'll go over the code and make sure that doesn't happen anymore. Thanks for testing 👍

**Comment by avencherus** [comment]
No problem.  Looked like an interesting feature and was curious.  X)

**Comment by lupoDharkael** [comment]
I think this fixes https://github.com/godotengine/godot/issues/6149 too

**Comment by akien-mga** [comment]
Superseded by 42032669238bdc807bc7b8f03fff87e6cb5847f1.

**Pull request closed without merging**
