### PR TITLE
Fix RichTextLabel custom_effects export to be properly filtered in the Editor

### PR DESCRIPTION
**Pull request by EricEzaM**
Fixes https://github.com/godotengine/godot/pull/40383#issuecomment-865053866
Supersedes #49832

image

### CODE REVIEW

**Comment by akien-mga** [comment]
This partly reverts #40383 and thus will reintroduce the unexpected hint in the GDNative API json. @touilleMan did it pose actual issues for GDNative, or were you changing it just to cleanup something that seemed weird (and is indeed cryptic)?

**Review by bruvzg — APPROVED** [review]

**Comment by bruvzg** [comment]
This is the only place this syntax is used (I'm using it #47524 PR as well), maybe we should change it to something more readable, use the same values in the text form for example.
```
Object/PROPERTY_HINT_RESOURCE_TYPE:RichTextEffect
```

**Comment by EricEzaM** [comment]
I am also using it in a Work In Progress PR. But I tried to copy the original implementation of RichTextLabel and it didn't work... Which led me to investigate this issue. There has been some discussion on rocketchat I think between groud and reduz about the possibility of using dictionaries to simplify the definitions, rather than relying on cryptic string formatting.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
