### PR TITLE
Add Vertical Align to text for Line Edit

### PR DESCRIPTION
**Pull request by thimenesup**

### CODE REVIEW

**Comment by hpvb** [comment]
Thanks for your contribution! There are some small style changes in this commit:
```diff
--- a/scene/gui/line_edit.cpp	2018-03-02 16:54:23.720066542 +0000
+++ b/scene/gui/line_edit.cpp	2018-03-02 16:55:09.114302732 +0000
@@ -612,10 +612,8 @@
 
 			int font_h = font->get_height();
 
-
 			int vbegin = 0, vsep = 0;
 
-
 			switch (valign) {
 
 				case VALIGN_TOP: {
```

If you can amend your previous commit with those extra white lines removed that'd be great!

**Comment by Paulb23** [comment]
Your commit appears to revert #16422 .

**Comment by thimenesup** [comment]
I don't think that is a regresion exactly, is just that the branch its from the 3.0 stable release where that issue wasn't fixed.

**Comment by akien-mga** [comment]
> I don't think that is a regresion exactly, is just that the branch its from the 3.0 stable release where that issue wasn't fixed.

Well nevertheless, to get it merged in the master branch it should not be undoing changes that were merged since you worked on it.

**Comment by reduz** [comment]
I think there is no reason for LineEdit text to not be always centered vertically, so I that probably would be the right PR

**Pull request closed without merging**
