### PR TITLE
Made stepify() working as expected

### LINKED ISSUE #54896: `stepify()` and format strings round `5` down
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

`stepify()` and format strings round `5` down instead of up.

```
	print(stepify(0.150, 0.1))
	print("%.1f" % 0.150)

	print("---")

	print(stepify(0.151, 0.1))
	print("%.1f" % 0.151)

	breakpoint
```

Prints:
```
0.1
0.1
---
0.2
0.2
```

Expected:
```
0.2
0.2
---
0.2
0.2
```

### Steps to reproduce

Run code above

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by vitika9**
Fixes #54896

### CODE REVIEW

**Comment by nathanfranke** [comment]
What is the purpose of converting the double into a float?

**Comment by Vitika9** [comment]
> What is the purpose of converting the double into a float?

I am not sure but may be it's a fault in the inbuilt method (floor which accepts a double), you can test it by passing a double of value 2 and it will return 1 but incase of passing a float with value 2 it will return 2(which is expected). Anyway, I don't think precision will matter here because what we want is just a integer value.

**Comment by Vitika9** [comment]
> What is the purpose of converting the double into a float?
Screenshot from 2021-12-21 12-46-52
Output:1

Screenshot from 2021-12-21 12-46-32
Output:2

And the most confusing part is..
Screenshot from 2021-12-21 12-47-18
Output:2
(Same as the first case but different output)

IDK what's the reason and please correct me if I am wrong, anyway we only need the integer value out of it and I think passing a float variable won't give any unexpected output.

**Comment by aaronfranke** [comment]
The values you are working with are not exact floats, so the math isn't working as you expect.

When you write `(0.150 / 0.1)`, those values get converted to the nearest float values to those values. For 32-bit floats it would be `(0.1500000059604644775390625 / 0.100000001490116119384765625)` (same thing with 64-bit, but with more `0`s before the unreliable digits).

This fix isn't correct (casting to float will work in some cases but break others), but there is no way to fix this function for those values because the numbers you're passing in are not what you expect, so it the math error happens before we even get to the code of the function.

The best suggestion I can offer you is to use an epsilon value, so instead of `snapped(value, step)`,
do `var epsilon = 0.000001` and `snapped(value + epsilon, step)`.

**Comment by Vitika9** [comment]
> 

Thanks for explanation

**Pull request closed without merging**
