### PR TITLE
Fix is_point_in_triangle function

### LINKED ISSUE #16438: point_is_inside_triangle rounding issue.
Hello everyone.

Godot version: Godot_v3.0-stable_x11.64
OS: Linux Ubuntu 17.10

I'm currently using the Geometry function point_is_inside_triangle to create custom meshes. Although I'm getting some strange values back.

```GDScript
var point_a = Vector2(0,0)
var point_b = Vector2(4,0)
var point_c = Vector2(0,4)

var main_point = Vector2(0.25, 0.25)
	
print(Geometry.point_is_inside_triangle(main_point, point_a, point_b, point_c)) #false
print(Geometry.point_is_inside_triangle(main_point, point_a, point_c, point_b)) #false
print(Geometry.point_is_inside_triangle(main_point, point_b, point_a, point_c)) #true
print(Geometry.point_is_inside_triangle(main_point, point_b, point_c, point_a)) #true
print(Geometry.point_is_inside_triangle(main_point, point_c, point_a, point_b)) #false
print(Geometry.point_is_inside_triangle(main_point, point_c, point_b, point_a)) #false

```
Thanks to DemiPixel in the discord we have narrowed it down a bit. You can see [here](https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/core/math/geometry.h#L504-L515) that the values are converted to an int at the top. That means any float values are being rounded down (?). Not really what I'm expecting.

I hope someone can create a fix for this.

### PR DESCRIPTION
**Pull request by Chaosus**
Closes #16438

### CODE REVIEW

**Comment by Noshyaar** [comment]
I'm not sure, but shouldn't it be `real_t` instead of `float`?

**Comment by simonpuchert** [comment]
I have a different implementation that you can use, if you want. Maybe it's easier to grasp (also it's more symmetric).

```c
static bool is_point_in_triangle(const Vector2 &s, const Vector2 &a, const Vector2 &b, const Vector2 &c) {
	Vector2 an = a - s;
	Vector2 bn = b - s;
	Vector2 cn = c - s;

	bool orientation = an.cross(bn) > 0;

	if ((bn.cross(cn) > 0) != orientation) return false;

	return (cn.cross(an) > 0) == orientation;
}
```

Including the boundary can be achieved by replacing every ">" with ">=".

**Comment by Chaosus** [comment]
@Noshyaar, Done..
@simonpuchert Im not sure about changing code to this is good idea, isnt it just refactoring it to more easy view ? If so, cross function in Vector2 is not inline and is more performance ineffecient. You could open your own PR for this..

**Comment by simonpuchert** [comment]
Well, with e.g. g++ -O2 (or the equivalent clang ), the function should be inlined by the compiler (see [https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Optimize-Options.html](https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/Optimize-Options.html)).

So, the only difference in release builds is that my implementation might save some subtractions (but that should also be easy for the compiler to do) and it's easier to understand / verify in my opinion.

**Comment by Noshyaar** [comment]
I guess using `cross` is okay since `point_in_projected_triangle` also use it (in 3D), but I think #16485 should be merged first.

**Comment by Chaosus** [comment]
@Noshyaar Okay..

**Pull request merged**
