### PR TITLE
X11: Fix maximized boot splash

### PR DESCRIPTION
**Pull request by 27thLiz**
When instructing the window manager to (un-)maximize a window, the resulting resolution
is received via an `XEvent` of type `ConfigureNotify`.

The problem here was that these events were only handled in the `OS_X11::process_xevents()` method,
which is initially called on the first iteration of the main loop.
Because of this, the `VideoMode` still hadn't been updated yet when doing the boot splash setup.

### CODE REVIEW

**Comment by Hinsbart** [comment]
Supercedes #2291.

**Comment by iboshkov** [comment]
This crashes Godot on X11, something is wrong with the code trying to capture the XConfigureNotify event.

**Comment by Alex-doc** [comment]
I confirm: this breaks Godot for me too.

**Comment by akien-mga** [comment]
Reverted the PR for now as @Hinsbart agreed on IRC.

**Pull request merged**
