### PR TITLE
Fixes normals of the generated geometry from CSGPolygon3D (follow along Path3D)

### LINKED ISSUE #48408: CSGPolygon3D when set to Path mode, Path Rotation set to PathFollow and attached to a Path3D, the resultant geometry normals are inverted.
**Godot version:**
v4.0.dev.custom_build.8abd50359

**OS/device including version:**
Windows 10

**Issue description:**
CSGPolygon3D when set to Path mode, Path Rotation set to PathFollow and attached to a Path3D, the resultant geometry normals are inverted.
This is similar to #48233 except that Path Rotation is set to PathFollow.

image

**Steps to reproduce:**
1. Add a Path3D
2. Create a curve for the Path3D (Add points)
3. Add a CSGPolygon3D
4. Set Mode to Path, assign the Path3D and set Path Rotation to PathFollow

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/6415325/test.zip)

### PR DESCRIPTION
**Pull request by aole**
Fixed normals by inverting how the faces were getting created when CSGPolygon3D is set to mode Path and followed along a Path3D. Fixes #48408
The order of vertices have been reversed for the creation of faces. Fixed the face normal at the ends of the path also (reversed the vertices order).

image

### CODE REVIEW

**Comment by aole** [comment]
Let me know if this is not how the issue needs to be addressed. I just reversed the order of vertices to flip the face normals.

**Comment by Calinou** [comment]
cc @madmiraal

**Comment by BastiaanOlij** [comment]
Often noticed that you had to flip the faces (which is an option in CSG) or in certain modes it would end up inside out. If this fixes that issue we need to be aware that this is a breaking change where lots of people will need to uncheck that option.

**Comment by akien-mga** [comment]
Superseded by #49314. Thanks for the contribution nonetheless!

**Pull request closed without merging**
