### PR TITLE
Fix consistency of GradientTexture changes

### PR DESCRIPTION
**Pull request by KoBeWi**
Gradient texture queues an update when a property changes, EXCEPT in `set_gradient()` in GradientTexture2D, which calls the update immediately and emits the changed signal twice. Another weird thing is that gradient texture changes would queue the update and the changed signal would be emitted in the `_update()` method. That's not how this signal works.

This PR removes the inconsistency and `_queue_update()` is now called for every change, but the deferred `emit_changed()` is removed. Instead the signal is emitted right in the setter. I also added a public (not exposed) method `update_now()`, which forces the pending texture update to be done right now. It's automatically called when you attempt to get the image.

### CODE REVIEW

**Comment by YuriSizov** [comment]
> EXCEPT in `set_gradient()` in GradientTexture2D

Just for future readers, this except comes from https://github.com/godotengine/godot/pull/60361.

**Comment by KoBeWi** [comment]
The interesting part is that this change wasn't done in GradientTexture1D.

**Review by Geometror — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
Yes.

**Comment by kleonc** [comment]
> This PR removes the inconsistency and `_queue_update()` is now called for every change

Some leftovers (for whatever reason it's connecting to `GradientTexture1D::_update` instead of `GradientTexture1D::_queue_update`):
https://github.com/godotengine/godot/blob/bc88dca176cef6b8943ded58c68a60f7c127baea/scene/resources/gradient_texture.cpp#L66-L72

**Pull request merged**
