### PR TITLE
Fix invalid use of markdown syntax in classref

### PR DESCRIPTION
**Pull request by timothyqiu**
Also changed `[b]true[/b]` to `[code]true[/code]`.

### CODE REVIEW

**Comment by dalexeev** [comment]
1\. I checked it, I couldn't find any other matches for invalid use of Markdown. :+1:

2\. Some possible incorrect `[b]` and `[i]`. I think `[code]` or class reference is more appropriate here.

https://github.com/godotengine/godot/blob/dcd187da9580b41688f4e5110acd767d4deab8de/doc/classes/%40GlobalScope.xml#L365-L366

https://github.com/godotengine/godot/blob/dcd187da9580b41688f4e5110acd767d4deab8de/doc/classes/%40GlobalScope.xml#L648

https://github.com/godotengine/godot/blob/dcd187da9580b41688f4e5110acd767d4deab8de/doc/classes/Area3D.xml#L9

https://github.com/godotengine/godot/blob/dcd187da9580b41688f4e5110acd767d4deab8de/doc/classes/AudioEffectDelay.xml#L41-L49

https://github.com/godotengine/godot/blob/dcd187da9580b41688f4e5110acd767d4deab8de/doc/classes/ConvexPolygonShape2D.xml#L9

3\. This is more like material for another PR, but I noticed that some "strong" words ("not", "must") are sometimes in bold and sometimes in italics.

<details>
<summary>italic "not" - 54 matches</summary>

```
doc/classes/@GlobalScope.xml: 1
400: 35: 				[b]Note:[/b] This function is [i]not[/i] the same as [code]int(x)[/code], which rounds towards 0.
doc/classes/Array.xml: 2
378:160:  values. However, the reverse is not true. Returning identical hash values does [i]not[/i] imply the arrays are equal, because different arrays can have identical hash values due to hash
651:143: 	Compares the left operand [Array] against the [param right] [Array]. Returns [code]true[/code] if the sizes or contents of the arrays are [i]not[/i] equal, [code]false[/code] otherwise.
doc/classes/BaseMaterial3D.xml: 2
 62:143: ] and a [member detail_albedo] texture is specified, [member albedo_color] will [i]not[/i] modulate the detail texture. This can be used to color partial areas of a material by not speci
155: 43: 			[b]Note:[/b] [member detail_albedo] is [i]not[/i] modulated by [member albedo_color].
doc/classes/BoneAttachment3D.xml: 1
 28:246:  has a bone that has changed its pose. This function is where the BoneAttachment3D node updates its position so it is correctly bound when it is [i]not[/i] set to override the bone pose.
doc/classes/Callable.xml: 1
160:163:  values. However, the reverse is not true. Returning identical hash values does [i]not[/i] imply the callables are equal, because different callables can have identical hash values due t
doc/classes/Camera2D.xml: 1
181: 53: 			[b]Note:[/b] [member FontFile.oversampling] does [i]not[/i] take [Camera2D] zoom into account. This means that zooming in/out will cause bitmap fonts and rasterized (non-MSDF) dynamic
doc/classes/CanvasItem.xml: 2
293: 54: 				[b]Note:[/b] [member FontFile.oversampling] does [i]not[/i] take [param scale] into account. This means that scaling up/down will cause bitmap fonts and rasterized (non-MSDF) dynamic
590: 49: 			If [code]true[/code], this [CanvasItem] will [i]not[/i] inherit its transform from parent [CanvasItem]s. Its draw order will also be changed to make it draw on top of other [CanvasIte
doc/classes/Control.xml: 2
 16: 32: 		[b]Note:[/b] Theme items are [i]not[/i] [Object] properties. This means you can't access their values using [method Object.get] and [method Object.set]. Instead, use the [code]get_them
1022: 53: 			[b]Note:[/b] [member FontFile.oversampling] does [i]not[/i] take [Control] [member scale] into account. This means that scaling up/down will cause bitmap fonts and rasterized (non-MSD
doc/classes/Dictionary.xml: 1
264: 58: 				[b]Note:[/b] Dictionaries with equal hash values are [i]not[/i] guaranteed to be the same, because of hash collisions. On the contrary, dictionaries with different hash values are gu
doc/classes/EditorFileSystem.xml: 1
 17:147:  resource type of the file, given the full path. This returns a string such as [code]"Resource"[/code] or [code]"GDScript"[/code], [i]not[/i] a file extension such as [code]".gd"[/code].
doc/classes/EditorFileSystemDirectory.xml: 1
 71:147:  resource type of the file at index [param idx]. This returns a string such as [code]"Resource"[/code] or [code]"GDScript"[/code], [i]not[/i] a file extension such as [code]".gd"[/code].
doc/classes/EditorSettings.xml: 3
284:254: gle into account for the movement. The "Freelook Up" and "Freelook Down" keys will move in an "absolute" manner, [i]not[/i] taking the camera's pitch angle into account for the movement.
285:151: reelook Forward", "Freelook Backward", "Freelook Up" and "Freelook Down" keys will move in an "absolute" manner, [i]not[/i] taking the camera's pitch angle into account for the movement.
324:120: 			If [code]true[/code], invert the horizontal mouse axis when panning or orbiting in the 3D editor. This setting does [i]not[/i] apply to freelook mode.
doc/classes/Engine.xml: 2
 31: 54: 				[b]Note:[/b] [method get_architecture_name] does [i]not[/i] return the name of the host CPU architecture. For example, if running an x86_32 Godot binary on a x86_64 system, the retur
305:280: [code]false[/code] in a [code]@tool[/code] script, this will also impact the editor itself. Do [i]not[/i] report bugs before ensuring error messages are enabled (as they are by default).
doc/classes/GPUParticlesCollision3D.xml: 1
  8:158: 		Particle collision shapes in real-time and can be moved, rotated and scaled during gameplay. Unlike attractors, non-uniform scaling of collision shapes is [i]not[/i] supported.
doc/classes/GeometryInstance3D.xml: 1
 65:546: arency sorting. However, unlike using a transparent material, setting [member transparency] to a value greater than [code]0.0[/code] (exclusive) will [i]not[/i] disable shadow rendering.
doc/classes/Light3D.xml: 1
201: 37: 			[b]Note:[/b] Hiding a light does [i]not[/i] affect baking [LightmapGI]. Hiding a light will still affect baking [VoxelGI] and SDFGI (see [member Environment.sdfgi_enabled).
doc/classes/LightmapGI.xml: 1
125:174: [WorldEnvironment] node, this will act like [constant ENVIRONMENT_MODE_DISABLED]. The editor's preview sky and sun is [i]not[/i] taken into account by [LightmapGI] when baking lightmaps.
doc/classes/MovieWriter.xml: 2
 13:101: Writer is available for use in both the editor and exported projects, but it is [i]not[/i] designed for use by end users to record videos while playing. Players wishing to record gamepla
 56: 95: 				[b]Note:[/b] Pressing [kbd]Ctrl + C[/kbd] on the terminal running the editor/project does [i]not[/i] result in [method _write_end] being called.
doc/classes/Node.xml: 3
182: 71: 				[b]Note:[/b] For performance reasons, the order of node groups is [i]not[/i] guaranteed. The order of node groups should not be relied upon as it can vary across project runs.
301: 71: 				[b]Note:[/b] For performance reasons, the order of node groups is [i]not[/i] guaranteed. The order of node groups should not be relied upon as it can vary across project runs.
995:108: when the node's name or one of its parents' name is changed. This notification is [i]not[/i] received when the node is removed from the scene tree to be added to another parent later on.
doc/classes/OS.xml: 2
623:259: y process executed with [method execute] after running [method set_environment]. The environment variable will [i]not[/i] persist to processes run after the Godot process was terminated.
680:287: d with [method execute] after running [method unset_environment]. The removal of the environment variable will [i]not[/i] persist to processes run after the Godot process was terminated.
doc/classes/Object.xml: 1
 23:200: hout being set to [code]null[/code]. To check if an object has been deleted, do [i]not[/i] compare it against [code]null[/code]. Instead, use [method @GlobalScope.is_instance_valid]. It'
doc/classes/PolygonOccluder3D.xml: 1
 15: 21: 			The polygon must [i]not[/i] have intersecting lines. Otherwise, triangulation will fail (with an error message printed).
doc/classes/ProjectSettings.xml: 4
218:169: nt to display to the user that the editor must be restarted for changes to take effect. Enabling [method set_restart_if_changed] does [i]not[/i] delay the setting being set when changed.
2210:127: essing filter to make banding significantly less visible in 3D. 2D rendering is [i]not[/i] affected by debanding unless the [member Environment.background_mode] is [constant Environment.
2640: 44: 			[b]Note:[/b] Changing this setting does [i]not[/i] impact textures that were already imported before. To make this setting apply to textures that were already imported, exit the edito
2645: 44: 			[b]Note:[/b] Changing this setting does [i]not[/i] impact textures that were already imported before. To make this setting apply to textures that were already imported, exit the edito
doc/classes/RDPipelineMultisampleState.xml: 1
 22:439:  [code]1.0[/code], fragment invocation must only read from the coverage index sample. Tile image access must not be used if [member enable_sample_shading] is [i]not[/i] [code]1.0[/code].
doc/classes/RenderingServer.xml: 3
1390:126:  on the CPU in milliseconds. This value is shared across all viewports and does [i]not[/i] require [method viewport_set_measure_render_time] to be enabled on a viewport to be queried. Se
1688:458: parency sorting. However, unlike using a transparent material, setting [param transparency] to a value greater than [code]0.0[/code] (exclusive) will [i]not[/i] disable shadow rendering.
3698:278: ering/2d/sdf/scale]. This is used when sampling the signed distance field in [CanvasItem] shaders as well as [GPUParticles2D] collision. This is [i]not[/i] used by SDFGI in 3D rendering.
doc/classes/ResourceImporterScene.xml: 1
  9: 43: 		[b]Note:[/b] [ResourceImporterScene] is [i]not[/i] used for [PackedScene]s, such as [code].tscn[/code] and [code].scn[/code] files.
doc/classes/ResourceImporterShaderFile.xml: 1
  7:137: 		This imports native GLSL shaders as [RDShaderFile] resources, for use with low-level [RenderingDevice] operations. This importer does [i]not[/i] handle [code].gdshader[/code] files.
doc/classes/String.xml: 2
321: 53: 				[b]Note:[/b] Strings with equal hash values are [i]not[/i] guaranteed to be the same, as a result of hash collisions. On the countrary, strings with different hash values are guarant
895:262: racters of the first page of the ASCII table (values from 0 to 31), such as tabulation ([code]\t[/code]) and newline ([code]\n[/code], [code]\r[/code]) characters, but [i]not[/i] spaces.
doc/classes/StringName.xml: 2
304: 53: 				[b]Note:[/b] Strings with equal hash values are [i]not[/i] guaranteed to be the same, as a result of hash collisions. On the countrary, strings with different hash values are guarant
802:262: racters of the first page of the ASCII table (values from 0 to 31), such as tabulation ([code]\t[/code]) and newline ([code]\n[/code], [code]\r[/code]) characters, but [i]not[/i] spaces.
doc/classes/StyleBoxFlat.xml: 4
149:100: ike [member StyleBox.content_margin_bottom], [member expand_margin_bottom] does [i]not[/i] affect the size of the clickable area for [Control]s. This can negatively impact usability if u
153: 96:  Unlike [member StyleBox.content_margin_left], [member expand_margin_left] does [i]not[/i] affect the size of the clickable area for [Control]s. This can negatively impact usability if u
157: 98: nlike [member StyleBox.content_margin_right], [member expand_margin_right] does [i]not[/i] affect the size of the clickable area for [Control]s. This can negatively impact usability if u
161: 94: b] Unlike [member StyleBox.content_margin_top], [member expand_margin_top] does [i]not[/i] affect the size of the clickable area for [Control]s. This can negatively impact usability if u
doc/classes/Vector3.xml: 1
273:127: n only be used for [method normalized] vectors. [method octahedron_encode] does [i]not[/i] check whether this [Vector3] is normalized, and will return a value that does not decompress to
doc/classes/Viewport.xml: 1
348:127: essing filter to make banding significantly less visible in 3D. 2D rendering is [i]not[/i] affected by debanding unless the [member Environment.background_mode] is [constant Environment.
modules/csg/doc_classes/CSGPolygon3D.xml: 1
 51:146:  This can be a convex or concave polygon with 3 or more points. The polygon must [i]not[/i] have any intersecting edges. Otherwise, triangulation will fail and no mesh will be generated.
```

</details>

<details>
<summary>italic "must" - 14 matches</summary>

```
doc/classes/CPUParticles3D.xml: 4
129:177: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
133:190: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
137:182: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
159:187: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
doc/classes/GeometryInstance3D.xml: 1
 25: 84: 	[b]Note:[/b] For a shader uniform to be assignable on a per-instance basis, it [i]must[/i] be defined with [code]instance uniform ...[/code] rather than [code]uniform ...[/code] in the s
doc/classes/ImageTextureLayered.xml: 1
 16:218: data format. The first image decides the width, height, image format and mipmapping setting. The other images [i]must[/i] have the same width, height, image format and mipmapping setting.
doc/classes/Object.xml: 1
212:183: ng custom properties, which is particularly useful for editor plugins. Note that a property [i]must[/i] be present in [method get_property_list], otherwise this method will not be called.
doc/classes/ParticleProcessMaterial.xml: 4
134:177: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
138:190: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
142:182: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
161:194: ffect on a [BaseMaterial3D], [member BaseMaterial3D.vertex_color_use_as_albedo] [i]must[/i] be [code]true[/code]. For a [ShaderMaterial], [code]ALBEDO *= COLOR.rgb;[/code] must be inserte
doc/classes/ProjectSettings.xml: 1
2661: 16: 			The texture [i]must[/i] use a lossless compression format so that colors can be matched precisely. The following VRS densities are mapped to various colors, with brighter colors repres
doc/classes/ResourceImporterTextureAtlas.xml: 1
 14: 40: 			Path to the atlas spritesheet. This [i]must[/i] be set to valid path to a PNG image. Otherwise, the atlas will fail to import.
doc/classes/Viewport.xml: 1
367: 16: 			The texture [i]must[/i] use a lossless compression format so that colors can be matched precisely. The following VRS densities are mapped to various colors, with brighter colors repres
```

</details>

**Comment by timothyqiu** [comment]
> It raises the mathematical constant [b]e[/b] to the power of [param x] and returns it.

The mathematical constant 𝑒 is usually italic. I think it should be `[i]` as long as it's not referring to something in code.

> go to the [b]Sprite2D[/b] menu

This is referring to the text on the menu button. I don't think it should be `[code]`, but I'm not sure whether it should be `[i]` or `[b]`.

> [b]Tap2[/b] delay time in milliseconds.

Judging from the context, although related the function's name, it's just a stylized "Tap 2", or second tap. I think `[code]tap2[/code]` should be changed to plain `tap 2` or `[b]tap 2[/b]`.

**Comment by YuriSizov** [comment]
> Judging from the context, although related the function's name, it's just a stylized "Tap 2", or second tap.

I think it's just capitalized because it's at a start of a sentence 🙃 Though the sentence itself is poorly phrased, IMO. I don't mind if we fix it, and if we replace `tap2` with "the second tap".

**Review by YuriSizov — APPROVED** [review]
Changes so far are good, but feel free to address brought up concerns.

**Comment by timothyqiu** [comment]
Added the following changes:

* Use `[i]` for mathematical constant "e".
* Use `[b]` for button text & menu item text. Because only `Area3D` uses `[i]` for this.
* Replace "tap1" and "tap2" to "the first tap" and "the second tap" accordingly.

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
