### PR TITLE
Bind drag forwarding methods

### LINKED ISSUE #48726: Drag forwarding methods not available in autocompletion and documentation
**Godot version:** master(6054feb) / 3.x(7417467) / 3.3

**OS/device including version:** not graphics-related

**Issue description:**

When `set_drag_forwarding` is set on a `Control` node, the forward owner's `get_drag_data_fw`, `can_drop_data_fw`, and `drop_data_fw` are used instead of the control's non-postfixed ones.

* Searching the built-in documentation shows no such methods on `Control`. They are only mentioned in the documentation of `set_drag_forwarding`.
* There is no autocompletion for these methods. When writing these functions in GDScript, one have to autocomplete the non-postfixed version, and then add the `_fw` postfix and extra argument. This becomes quite a lot of work when type hints are used.

**Steps to reproduce:**

* Create a control node, add a script, and try to type `get_drag_data_fw`.
* Search `get_drag_data_fw` in help.

**Minimal reproduction project:** N/A

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #48726

### CODE REVIEW

**Comment by groud** [comment]
I don't think this is a good fix. Those methods aren't only implementable by Control nodes, but by any kind of Object (and thus Nodes too). As a consequence, there's no reason why those functions should be added there and not in Object.

However I don't think we should add them to Object either, it seems a little bit overkill to add such specific methods in a very core type. So for me I think the original issue is a wontfix.

**Comment by akien-mga** [comment]
> I don't think this is a good fix. Those methods aren't only implementable by Control nodes, but by any kind of Object (and thus Nodes too). As a consequence, there's no reason why those functions should be added there and not in Object.

I'm not sure that's by design though, it's just a consequence of doing a simple `call()`. Do we have any non-Control that implements this? What's the use case?

IMO those should be converted to proper virtual methods in Control.

**Comment by KoBeWi** [comment]
> Do we have any non-Control that implements this?

Yes, Window-based nodes (e.g. EditorSettingsDialog).

**Comment by groud** [comment]
> I'm not sure that's by design though, it's just a consequence of doing a simple call(). Do we have any non-Control that implements this? What's the use case?

Well, I use it quite often. I put those methods on the root of my scene, whatever its type, and handle those there.

The drag forwarding thing behaves a little bit like signals I think. Though, instead of connecting one method, you connect to 3 methods at once. And, like, signals, there should be no restrictions on which kind of Object/Node you connect it to.

**Comment by akien-mga** [comment]
> > Do we have any non-Control that implements this?
> 
> Yes, Window-based nodes (e.g. EditorSettingsDialog).

Then I think it should be implemented both in `Control` and in `Window`. Alternatively they could be given a common `UINode` ancestor but I don't think we want to bother with that, duplicating it should be fine and is common for e.g. transforms in `CanvasItem` vs `Node3D`.

**Comment by groud** [comment]
> Then I think it should be implemented both in Control and in Window

IMO, that does not make a lot of sense. The target used for drag forwarding can be anything (and it's a valid use case IMO), so I don't see why we would add documentation specifically for those two nodes.

If we want to solve this in a cleaner way, I think those should be defined directly in the source's class documentation (here emitted by Control, thus in the Control class documentation), but should be differentiated from other unimplemented virtual method. They should likely be defined with a "target type" maybe (for autocompletion), and likely appear in a dedicated "Callbacks" section. Autocompletion would then work globally for such callbacks (as soon as the target type corresponds).

But of course, that's a lot more work.

**Comment by timothyqiu** [comment]
I didn't realize that `set_forwarding_target()` allows any Object :(

I'm closing this PR for now since adding these methods to Object is considered an overkill, and only adding these for `Control` looks like a hack for autocompletion and documentation.

**Pull request closed without merging**
