### PR TITLE
small typo in TextServer, changes bitwise to logical which can be faster in some cases via "short circuiting"

### PR DESCRIPTION
**Pull request by firefly2442**
Conditional logical is probably better.  It also allows "short circuiting".

### CODE REVIEW

**Comment by fire** [comment]
What is the problem being solved here?

**Comment by pooroligarch** [comment]
> What is the problem being solved here?

bitwise `&` changed to logical `&&`, more idiomatic and can be faster in some cases

**Comment by YuriSizov** [comment]
That's probably just a typo. The commit message needs to be more explicit though, e.g. mention that your fix is in TextServer.

**Comment by firefly2442** [comment]
Apologies, I've adjusted the commit to be more clear.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
