### PR TITLE
Replace threaded renderer particle function fail conditions with warnings

### LINKED ISSUE #54964: Vulkan GPUParticles3D related error spam with multithreaded renderer
### Godot version

4.0.dev (19571c9c4b)

### System information

W10, Vulkan, RTX2060

### Issue description

When using GPUParticles3D in a scene with `driver/threads/thread_model=2` (Multithreaded render mode), this error is printed repeatedly:
```cpp
E 0:00:07:0555   RendererStorageRD::particles_is_inactive: This function should never be used with threaded rendering, as it stalls the renderer.
  <C++ Error>    Condition "RenderingServerGlobals::threaded" is true. Returning: false
  <C++ Source>   servers\rendering\renderer_rd\renderer_storage_rd.cpp:5697 @ RendererStorageRD::particles_is_inactive()
```

The only place this could be called every frame is here:
https://github.com/godotengine/godot/blob/16dc607f8ad2055c8dec543bcd427fe74e5d6059/servers/rendering/renderer_scene_cull.cpp#L2700

### Steps to reproduce

Create a 3D scene with GPUParticles3D set up.
Enable multithreaded rendering mode.
Run project, see errors.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by briansemrau**
Fixes #54964

~~These checks make no sense to me, as these functions don't do anything to stall anything.~~

Nevermind, I forgot they get pushed through the command queue.

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this still relevant as of 4.0 RC 1?

**Comment by brianwinterpixel** [comment]
The linked issue is still reproducible, and this approach should still fix it. 

This isn't a critical issue, however. 

```cpp
E 0:00:01:0602   particles_is_inactive: This function should never be used with threaded rendering, as it stalls the renderer.
  <C++ Error>    Condition "RenderingServerGlobals::threaded" is true. Returning: false
  <C++ Source>   servers/rendering/renderer_rd/storage_rd/particles_storage.cpp:1541 @ particles_is_inactive()
```

Perhaps the GPUParticles design needs to be altered to not call these functions if possible, but I think demoting these errors to warnings is appropriate.

**Comment by brianwinterpixel** [comment]
Someone on the rendering team should check in on this issue some time.

**Comment by YuriSizov** [comment]
The linked issue has been closed by https://github.com/godotengine/godot/pull/76859. So I guess we can say this is superseded now. Thanks for your contribution nonetheless!

**Pull request closed without merging**
