### PR TITLE
Renames Type to OpType in VisualShaderNodeMultiplyAdd

### PR DESCRIPTION
**Pull request by Chaosus**
To prevent possible conflicts with C# and other languages.

### CODE REVIEW

**Comment by Chaosus** [comment]
However, there are some other classes with "get_type" : 
image

I tested it with C# and notice that object.GetType is just getting replaced by the custom GetType with no conflicts (but this prevents usage of common GetType). I'm not sure whether this change is really needed, or it's needed for all of these classes too, cc @neikeq

**Comment by neikeq** [comment]
I'm not against this rename, but IMO we should make the C# bindings generator detect the name and change it to `GetType_` or something else.

**Comment by aaronfranke** [comment]
@Chaosus Please see #36382 for renaming other instances of `type` and `get_type` and more.

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
