### PR TITLE
Remove the rect surrounding 2D nodes in 2D editor when it's not pertinent

### LINKED ISSUE #4255: Change default Node2d select-area size
Hello, everyone! I've been enjoying Godot and am very impressed and loving it. Thanks to all those putting their hard work into it. I searched through the issues and it seems no-one's requested this in particular. I hope so, anyway!

So, onto the problem/feature request: it seems certain nodes (I think it's node2d and everything that inherits it that has no specific size attribute -- kinematic body, area2d, etc.) have a default select-area size of 64x64 px in the editor. This is the area that you can select objects in the editor, and it seems there's no way to change this size.

select_area

(The player root node shown above is a kinematic body, but again, it seems it's many nodes with this default, non-change-able size) As you can see above, in a low resolution game where every object is based on 16x16 tile-size, this makes selecting and arranging objects in the editor difficult (though the drop-down select tool helps). It would be super helpful to be able to set these node select-areas to something that fits the game you're making -- 16x16 in this case.

**The feature**, then: would it be possible to add a field in project settings marked, maybe, "set default node select size", and you could set a width/height there? That way if you're working on a game based around 16x16 tile-size you could type that in, and all of these kinds of nodes would have that size, allowing you to move and select and align things with no problem. Or maybe even just a way to set this kind of thing on a node-by-node basis, though I think just having a default you could set would be helpful enough!

Thanks again in advance, and I hope I'm doing this right.

### LINKED ISSUE #13967: Snap to grid behaves inconsistently when selecting multiple nodes
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot 3.0 beta1

**Issue description:**
When moving one node, it works as expected and snaps the center of the node, but when selecting multiple nodes it snaps the top left of the nodes.
The same problem happens with plain Node2D nodes, not just centered Sprites.

It's hard to see the grid in the .gif but it's 64x64, the same size as the sprites.

### LINKED ISSUE #16454: Godot 3.0 Option to hide Lock/Children-selector icon if node is hidden
Didn't see a duplicate.

**Godot version:**
Godot 3.0 Stable 64-bit

**OS/device including version:**
Windows 7 64-bit SP1

**Issue description:**
Lock/Children-selector icon stays visible if a node is hidden (In 2d view at least). 2.1.4 hid these while the node was hidden and it was very useful. Requesting option to either restore the 2.1.4 way or have it be an option in the editor settings. (If there is an option already there for this I can not find it.)

**Steps to reproduce:** 
Switch to 2d view
Add a 2D node
Select lock/children-selector icon (or both)
Hide node

nodes

### LINKED ISSUE #17101: Change the editor gizmos for 2D nodes when they have no "rectangle"
**Godot version:**
3.1

This is a feature request.
We could replace the default placeholder rect used to select nodes in the 2D editor by a "point" (instead of a rectangle). This would avoid missclicks when trying to move a node and scale it instead (which is quite unusual). Node that have a meaninful rectangle, such as Sprites, can keep the rectangle.

Also, to identify more clearly what are each node, we might use each Node's icon to identify its type. Probably with an option to hide them too.

### LINKED ISSUE #17148: Making a node's children not selectable no longer works.
**Godot version:**
234dfde22f42cd18c3f6e390f1e7a30916ef8c9e

**OS/device including version:**
Windows 

**Issue description:**
Making a node's children not selectable no longer works as it did in **Godot v 3.0.1**

Below is the issue in visual form using the Godot version indicated above:

godotselectchildren

Below is how the same actions behaved in **Godot v 3.0.1**:

godot-3 0 1

**Steps to reproduce:**
1) Create a new scene.
2) Create a Sprite
3) Attach a StaticBody2D to theSprite node
4) Attach a CollisionShape2D to the StaticBody2D node
5) Create a collision shape in the CollisionShape2D node
6) Set the Sprite parent by clicking the "Object group button" image
7) Try to select the sprite by clicking on it, and instead the CollisionShape2D will be selected.

**Minimal reproduction project:**
[NodeChildren.zip](https://github.com/godotengine/godot/files/1772207/NodeChildren.zip)

### PR DESCRIPTION
**Pull request by groud**
In most cases, the rectangle surrounding a node in the 2D editor is not really pertinent, especially when it modifies the scale of a node. Indeed, it's pretty rare having to modify the scale of a Node, thus in most cases the rectangle is more annoying than useful. When necessary, this PR replaces the rect by a position marker that can still be moved an rotated.

Also, to know where to click to select the node, I added the display of the node icon+name when hovering hover the position point.

output

And one more thing, no more annoying rect for collision shapes. ;)
output

Also, fixes #17148, fixes #17101 and fixes #16454.
Fixes #4255.
Probably closes #13967 too.

### CODE REVIEW

**Comment by puppetmaster-** [comment]
How does snap to grid work with an instanced Scene (node2d as root and sprite as child)?

**Comment by groud** [comment]
> How does snap to grid work with an instanced Scene (node2d as root and sprite as child)?

Only the position of the Node2d snaps to the grid

**Comment by puppetmaster-** [comment]
I think it's great that you want to change something in this section, but here are my doubts
- it will be far too fiddly to select a node with only a little cross.
- snap to grid will not work when child has no even size (Sprite 13x13), grid need to be 7.5 
- most of my scene have a node2d root (easy prototyping), this change forces me to change my workflow

I know that a fixed selection area is not optimal but none is not better. There should be something in between.

**Comment by groud** [comment]
> it will be far too fiddly to select a node with only a little cross.

It's not, the selectable area is pretty wide and the little cross is visible even if the node is not selected.
Also, if you have the node2d as root and sprite as child as an instanced scene, clicking on the Sprite selects the whole instantiated scene.

> snap to grid will not work when child has no even size (Sprite 13x13), grid need to be 7.5

Well, you can move the Sprite pivot depending on where you want the sprite to snap. So no, the grid can stay 13x13. Or you can also move the sprite relatively to the Node2d root.

> most of my scene have a node2d root (easy prototyping), this change forces me to change my workflow

Not at all.

**Comment by groud** [comment]
Please test the the PR by yourself. And tell me if you see any other problem.

**Comment by puppetmaster-** [comment]
I'd love to do that so I don't make premature conclusions based on animated gif.
I've never created any build. Is it possible to share a windows build?

**Comment by groud** [comment]
Well I have no clue about how I can do that from Linux. Maybe have a look to the documentation for how to build, but I can't help you much more.
But anyway, if anyone else want to give it a try I'd be happy to answer questions ^^

**Comment by akien-mga** [comment]
CC @poke1024 @reduz

**Comment by poke1024** [comment]
I see how this makes perfect sense for collision shapes and it's much less cluttered for them now. For normal shapes, the click is still "on the shape", so you won't need to hit the cross, so no problem there. 

Some observations (I only looked at sub scenes, sprites, collision shapes, polygons):

* For the line collision shapes (LineShape2D, RayShape2D) you indeed want to hit the cross sometimes (in order to move the whole thing without the move tool), and I felt that hitting the cross there was a bit finicky (maybe a larger click radius?).
* Since each parent node now gets a cross you can click on, large scenes with deep trees might have lots of crosses - this might get confusing. Would only displaying the crosses of all parents of the currently selectem item be an idea?
* I think embedded scenes should keep getting a rect; personally, I need to scale them all the time.

**Comment by groud** [comment]
> For the line collision shapes (LineShape2D, RayShape2D) you indeed want to hit the cross sometimes (in order to move the whole thing without the move tool), and I felt that hitting the cross there was a bit finicky (maybe a larger click radius?).

The radius used is the same as the resize handle. For me it feels fine, but I guess it's something we can easily modify if users complain about that. I would test in production for that ^^

> Since each parent node now gets a cross you can click on, large scenes with deep trees might have lots of crosses - this might get confusing. Would only displaying the crosses of all parents of the currently selectem item be an idea?

The point of the crosses are to be visible in any situation, so that you can select the node you are interested in. If we hide it it becomes pointless. ^^ Maybe I can hide it for children of instanced scenes/locked nodes/unselectable children nodes. That may avoid bloat if there are a lot of them.

> I think embedded scenes should keep getting a rect; personally, I need to scale them all the time.

I'm not against it, but I'm not sure that it will works in a consistant manner in all situation. For example, if you have a scene with two Node2D seperated by 5 px, it might appear as a 5x5 rect, without any content, and will probably be hard to select. If I use a "default rect" (like 64x64 as before), it might look a little bit out compared to the other. 
Instead, what I'm thinking of is maybe adding a "scale tool", a little bit like what we have in 3D with "boxes arrows" gizmos, that would allow scaling any node. It could be activated with a shortcut too, like the rotation one.

**Comment by poke1024** [comment]
Played around a bit more with this. This is great when compositing scenes with prefab instances. In these cases a scale tool would work well I guess.

In complex scenes though, I'm still very confused by the inner nodes that get displayed though. Here's a sample project:

[CanvasDemo.zip](https://github.com/godotengine/godot/files/1814982/CanvasDemo.zip)

Depending on where I hover near the instance cross in scene.tcsn, I get one of those three:

q1

q2

q3

**Comment by groud** [comment]
Oh ok, that's probably a bug I have to fix then.

**Comment by groud** [comment]
But what do you mean by "inner" node ? I though you were talking about those nodes added via code that are invisible in the scene tree. But as you use only basic Node2Ds I wonder what are those "inner" and "area" nodes.

**Comment by eon-s** [comment]
I like the use on collision shape but not the rest, rectangles are better to see things like rotations and Position2D are for when we need to have some visual feedback of positions (and will be annoying to see these icons all the time on complex trees).

**Comment by poke1024** [comment]
@groud They're nodes from inside instanced scenes (and from instanced scenes in instanced scenes).

**Comment by groud** [comment]
Ho I did not understand they were instanced, your screenshot is cut on the right side.

**Comment by chanon** [comment]
Since you are already working on related issues in this PR, I would suggest considering implementing #17648 to help reduce clutter.

**Comment by groud** [comment]
Ok I updated the PR fixing the display of "inside nodes" of instanced scenes. I think this is good to merge like this, so that we can get feedback from users :)

**Comment by kenneth-leblanc** [comment]
Thank you for removing the rectangle around collision shapes! Thank you!
just... Thank you!

I do think you need to hide them for instanced scenes/locked nodes/unselectable children nodes.

**Comment by NikodemL** [comment]
The change seems ok in general, but can we get back the option to have rect on particles? Having the rect to set the scale of particles was a pretty useful feature.

We lost this:
particlescale2

**Comment by groud** [comment]
@NikodemL I'l probably add a scale tool someday to workaround this easily. But honestly I don't think this is really useful for Particles2D, since your particles will look distorded when you scale the node.

The Rect may be used to define the emission area though (not the scale).

**Comment by NikodemL** [comment]
@groud  Scale tool would be good to have, doing it manually is quite a chore.
We actually have all the particles scaled currently, they don't distort if you scale them by the same value in both directions and sometimes it doesn't even matter if they get distorted (some sparks, smokes, etc)

**Pull request merged**
