### PR TITLE
[WIP] Implement iOS one-click deploy.

### LINKED ISSUE #2703: One click deploy for iOS
I saw somewhere @reduz tried to find a way to implement `one click deploy for ios`.
But, it is not done yet and I leave it here for future task.

### PR DESCRIPTION
**Pull request by bruvzg**
Implements onc-click deploy to iOS simulators (via xcode `xcrun simctl`) and devices (via third-party tool - `ios-deploy`).

https://streamable.com/zqca9

`ios-deploy` part needs testing, I do not have any iDevices to test it on real hardware.

There's already PR for the same thing but it only supports real devices via `ios-deploy`: #11765

Fixes: #2703

### CODE REVIEW

**Comment by Calinou** [comment]
> Implements onc-click deploy to iOS simulators (via xcode xcrun simctl)

That reminds me, do the official iOS export templates contain x86 binaries for use with the Simulator?

**Comment by bruvzg** [comment]
> That reminds me, do the official iOS export templates contain x86 binaries for use with the Simulator?

Yes:

3.1.1 templates have `i386`, `armv7`, `x86_64`, `arm64` libs.
3.2 alpha 3 templates have `x86_64`, `arm64` libs.

**Comment by bruvzg** [comment]
> That reminds me, do the official iOS export templates contain x86 binaries for use with the Simulator?

XS/XR+ iPhones use ARMv8.3 CPUs (`arm64e`), probably we should add this to officeal template as well, but AFAIK it's optional and normal `arm64` libs should work on new devices too. (#26267)

**Comment by asheraryam** [comment]
Slightly related but I also found this repo that tries to do the same thing, might be helpful as a reference.

https://github.com/PrestonKnopp/godot-ios-deploy

**Comment by Relintai** [comment]
I gave this a whirl with my iphone 7, and ipod touch, it works really well so far.

**Comment by samgreen** [comment]
This works in the simulator but not on the device for me. @Relintai can you confirm this works from a mac to a device and without using the simulator?

**Comment by Relintai** [comment]
It did work for me. As I said I tried it with my real iPhone 7, and my iPod touch (5th gen). It worked flawlessly with both of them, every single time, also with multiple projects.

Something might have changed since then though, because for example now ios-deploy says to uninstall the npm version (commit from yesterday), and I had the npm version.

I'll clean rebuild, update everything on my mac and test again in a few days.

**Comment by bruvzg** [comment]
This is too outdated and need to be redone.

**Pull request closed without merging**
