### PR TITLE
Fix DoF artifacting at high blur amounts

### PR DESCRIPTION
**Pull request by ghost**
The artifact is actually always there, just that it's more visible the greater the blur amount.

Also fixes background blur incorrectly blending in over more in-focus objects (see https://github.com/godotengine/godot/pull/65322#issuecomment-1236349159).

| master | fixed |
| --------- | ------------- |
| dof4_artifact | dof4_artifact_fixed |

### CODE REVIEW

**Comment by ceLoFaN** [comment]
For some reason this breaks the far blur (which it didn't use to do last time I applied it), so I'll need to take another look...

**Comment by ceLoFaN** [comment]
Actually I think it's because now the background won't incorrectly blur over more in-focus objects, but I fooled myself with my test scene, since it looked somewhat prettier:

| with this patch | master |
| --------- | ------------- |
| dof-bg-blend-fix | dof-bg-blend-bug |

Unfortunately there are some artifacts visible around edges, which afaik are somewhat visible in the original implementation from https://tuxedolabs.blogspot.com/2018/05/bokeh-depth-of-field-in-single-pass.html as well:
https://4.bp.blogspot.com/-aJhORjPOHOE/WuwyXaWuO4I/AAAAAAAABEg/_EK3plrMEfMh6_l_ap33blyTDesqpCwkwCLcBGAs/s1600/bild7.png

There, the author said:

> After some experimentation I changed the clamping of sample size to clamp(sample size, 0, center size*2.0). For larger max radius I increase it even more. This controls how much of the background gets blended into a blurry foreground. It is totally unphysical and is only there to approximate the occluded information behind the foreground object.

I tried that a bit, but didn't get any satisfying results so far.

**Comment by ceLoFaN** [comment]
I also applied the fix to `bokeh_dof_raster.glsl` but I'm not sure how to test that one...

**Comment by Calinou** [comment]
> I also applied the fix to `bokeh_dof_raster.glsl` but I'm not sure how to test that one...

Switching to the Vulkan Mobile backend in the project settings should allow you to test it, as raster depth of field it's used in the mobile backend (as opposed to compute in Vulkan Clustered).

**Comment by ceLoFaN** [comment]
Well good thing I tested... should be OK now.

**Review by clayjohn — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
