### PR TITLE
Re-maps KEY_BRACELEFT/RIGHT for OSX users

### LINKED ISSUE #28098: The indent left and indent right key labels are inverted
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
The `Indent Left` and `Indent Right` key labels are inverted, ie, they are doing the opposite.

### PR DESCRIPTION
**Pull request by KLee1248**
Should fix #28098.

### CODE REVIEW

**Comment by KLee1248** [comment]
I don't have a OSX machine to test this change. It seems obvious to me, but it should be tested before accepting.

**Comment by cbscribe** [comment]
Tested ok here, thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by akien-mga** [comment]
Not relevant for 3.0 branch.

**Pull request merged**
