### PR TITLE
Add vsproj=yes to Visual Studio project build command

### PR DESCRIPTION
**Pull request by LATRio**
QoL change. This takes care of addition/removal of files when building project from VS after pull.

### CODE REVIEW

**Comment by akien-mga** [comment]
Does this have an impact on incremental rebuild time?

**Comment by fire** [comment]
Is there a hyperfine alternative for windows I can use to test?

**Comment by Calinou** [comment]
> Is there a hyperfine alternative for windows I can use to test?

Hyperfine *is* available for Windows, here's a download: https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine-v1.12.0-x86_64-pc-windows-gnu.zip

**Comment by akien-mga** [comment]
> Does this have an impact on incremental rebuild time?

Can anyone using Visual Studio and the `vsproj=yes` option comment on whether they would find this change useful, and whether it has any negative impact on incremental rebuilds? Also worth checking what happens in a workflow where users would modify the generated solution.

**Comment by akien-mga** [comment]
No update so closing for now. I'm happy to reconsider this if/when we get more details on what it impacts exactly.

**Pull request closed without merging**
