### PR TITLE
Reset ruler tool when switching tools with shortcuts

### LINKED ISSUE #37056: Ruler tool origin point is not reset when switching tool via shortcut
**Godot version:**
3.2.1

**Issue description:**
QnxQ99IN6A

**Steps to reproduce:**
1. Select Ruler Tool
2. Start measuring
3. Switch tool to Select/Move etc. using shortcut (don't stop measuring)
4. Select ruler tool again
5. The old origin point persisted and you need to unclick to stop measuring

### PR DESCRIPTION
**Pull request by dreamsComeTrue**
Fixes: #37056

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
Sorry for late review. The fix is correct, but needs rebase.

Looks like this PR has its anniversary today. Good time to merge it I guess 🤔

**Comment by dreamsComeTrue** [comment]
Thanks! Rebased as requested 😉

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
