### PR TITLE
Remove PROPERTY_HINT_OBJECT_TOO_BIG constant

### PR DESCRIPTION
**Pull request by Mickeon**
See the [this RocketChat link,](https://chat.godotengine.org/channel/devel?msg=e2pnZqyq6Z5kamcJj) and [this](https://chat.godotengine.org/channel/core?msg=NJquKPM9jpirz4izP) _(although as of the time of writing this no answers have been given)_.
**PROPERTY_HINT_OBJECT_TOO_BIG**  is almost entirely unused by the engine. This property was added by https://github.com/godotengine/godot/commit/dc62389739bcc9ece889230cdd07cc6a2cb04a2d. However, over time, it seems like its original intent was lost, and now it is only internally used as a way to "zero-out" a property hint, before passing a property to the debugger. It seems like that can be done just fine by replacing it with **PROPERTY_HINT_NONE**. 

This PR probably requires some input from someone that knows the inner workings of the debugger.

### CODE REVIEW

**Comment by Faless** [comment]
I think the flag itself makes sense, and instead of removing it we should display something like "Too big" instead of "null" in the inspector when such a variant is received.

**Comment by Mickeon** [comment]
To me it sounds weird that an USAGE flag is required for this to be done, quite frankly. Because this is prickly core stuff, I acknowledge I do not have much experience to say that confidently, however.

**Comment by Faless** [comment]
> To me it sounds weird that an USAGE flag is required for this to be done

It's not a USAGE flag in fact, but a PROPERTY_HINT

**Comment by Mickeon** [comment]
Yeah, the sleep is getting over me. Still does feel hacky to me, but if it can be expanded to not be, somehow, so be it, I suppose...

**Comment by akien-mga** [comment]
Since we're about to release 4.0 stable, it's now too late for such changes.

**Pull request closed without merging**
