### PR TITLE
Use suffixes for units in nodes and resources

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR fulfills a goal of #50009 left for future PRs ("someone needs to go through the rest of the engine and add all remaining suffixes") although this PR is only for nodes and resources in the inspector, not around the whole engine.

While making this, I also fixed some limitations that would prevent suffixes from working properly with some inspector types, such as by ensuring the unitless parts of Plane/Transform2D/Transform3D stay so.

### CODE REVIEW

**Comment by Whimfoome** [comment]
Can we add hints, when exporting variables from GDScript, to use the proper unit?

**Comment by aaronfranke** [comment]
Updated this PR. Since #50042 is closed I redid this PR so that it no longer depends on #50042. Now this PR uses the `suffix:` system and adds suffixes in hundreds of places.

**Review by mhilbrunner — APPROVED** [review]
Approved in today's editor team meeting.
Good work! Also needs a rebase :)

**Comment by fire-forge** [comment]
Glad this is finally merged! I've started working on a follow-up PR to add suffixes to the nodes and resources this PR missed.

**Comment by fire-forge** [comment]
Ok, I opened a follow-up PR that covers almost all of the remaining node and resource properties: https://github.com/godotengine/godot/pull/61240

Project and editor settings still need to have suffixes added.

**Pull request merged**
