### PR TITLE
SCons: Address minor `show_progress` issues

### PR DESCRIPTION
**Pull request by Repiteo**
- Followup to #98154

Realized a minor regression introduced by the above PR causing node count to not be tracked whatsoever if not displaying a progress bar. Additionally, `progress_finish` as an SCons action is unnecessary & doesn't catch all cases; it's now handled via `atexit` like the cache cleaning

### CODE REVIEW

**Comment by hpvb** [comment]
LGTM

**Comment by dustdfg** [comment]
Is it about a fact that `[Initial build]` disappeared recently?

**Review by hpvb — APPROVED** [review]
LGTM

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
