### PR TITLE
Fixed mismatched disable half float property string

### LINKED ISSUE #39425: Unmatched half_float GLOBAL_DEF and GLOBAL_GET
**Godot version:**
9901eac9f54dc5148a668acc5767d63da0665136

**OS/device including version:**
Arch Linux

**Issue description:**
```
W 0:00:00.388   _get: Property not found: rendering/gles2/debug/disable_half_float
  <C++ Source>  core/project_settings.cpp:209 @ _get()
```

**Steps to reproduce:**
* Clear disable half float settings on project.godot directly using a text editor.
* Set disable half float using the editor on project settings.
* Run editor.

### PR DESCRIPTION
**Pull request by Rubonnek**
Fixes #39425

### CODE REVIEW

**Comment by akien-mga** [comment]
That seems wrong to me?
```
$ rg disable_half_float
doc/classes/ProjectSettings.xml
1006:           <member name="rendering/gles2/debug/disable_half_float" type="bool" setter="" getter="" default="false">

drivers/gles2/rasterizer_storage_gles2.cpp
5976:   bool disable_half_float = GLOBAL_GET("rendering/gles2/debug/disable_half_float");
5977:   if (disable_half_float) {

servers/visual_server.cpp
2433:   GLOBAL_DEF("rendering/gles2/debug/disable_half_float", false);
```

**Comment by akien-mga** [comment]
Nevermind, I was checking on a slightly older commit. This changed in #39068.

**Comment by akien-mga** [comment]
Thanks!

**Comment by lawnjelly** [comment]
Thanks! :+1: Sorry it's been a bit mad with the project settings changes! :grin:

**Pull request merged**
