### PR TITLE
Remove `CPUParticles2D` damping limit to 100

### LINKED ISSUE #56324: CPUParticles2D damping is limited to 100
### Godot version

Godot_v3.4.2-stable_x11

### System information

Ubuntu desktop

### Issue description

In the editor, the value for [CPUParticles2D.damping](https://docs.godotengine.org/en/stable/classes/class_cpuparticles2d.html#class-cpuparticles2d-property-damping) is arbitrarily clamped to 100.0:

image

This can be hacked around by creating a damping curve that moves from zero immediately to the actual value you want (eg, 250):

image

It may also be hackable by setting the value in code (I haven't confirmed this).

### Steps to reproduce

- Create a CPUParticles2D node
- Give it some high velocity that you want to dampen quickly (say, 1000)
- Try to dampen it to 300
- See that you can't raise the value above 100

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by albinaask**
similar fix for #56324 that I made for 3.x, now made for 4.0

<i>Bugsquad edit:</i>
- Fix #56324

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request!

Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) (`git commit --amend`). This way, people reading the Git log can easily figure out what's going on :slightly_smiling_face:

**Comment by albinaask** [comment]
I think I did it now, if this was not what you wanted, then you'll have to say so and I'll fix it ;)

**Comment by Calinou** [comment]
Looks good to me, please squash the commits together so we can merge this. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) for instructions :slightly_smiling_face:

**Comment by albinaask** [comment]
Ok, I somehow made it worse... now there are more than 4 commits, by other people as well... Idk, can somebody give like a list of witch commands to run to fix this? I want to understand and do it myself so I learn for next time, but I don't get it... like at all

**Comment by YuriSizov** [comment]
cc @QbieShay

**Comment by QbieShay** [comment]
A very good and welcome change (i assume the changes to XR and android are accidental)

**Comment by YuriSizov** [comment]
@albinaask Can you please rebase and make sure that only relevant changes are included?

**Comment by YuriSizov** [comment]
This PR is welcome, but it needs to be salvaged.

**Comment by albinaask** [comment]
I'll give it another try in the coming days, but I seem to have a real problem wrapping my head around the technical aspects of the rebasing process in git. Is it something that someone is willing to give me some hands on help with. I've watched plenty of videos, but can't really get it to work correctly.

**Comment by YuriSizov** [comment]
@albinaask You can try joining the [Contributors chat](https://chat.godotengine.org/), there is a channel for new contributors as well as a general discussion channel where people may be able to help you.

**Comment by QbieShay** [comment]
I think for this change it's easier to pick the changes in cpuparticles2d and 3D and write them again from latest upstream rather than getting headaches with git rebase :D

**Comment by albinaask** [comment]
I made a new pull request with what I think is one commit containing the relevant changes without al the garbage that I somehow went up with last time.

**Pull request closed without merging**
