### PR TITLE
More work on splitting up RendererStorage

### PR DESCRIPTION
**Pull request by BastiaanOlij**
I plan to handle a number of different RendererStorage related tasks here.

Done:
- Merged Canvas, Texture and Decals into TextureStorage
- Moved RenderTarget into TextureStorage
- Move light, lightmap and probe into LightStorage
- Extract particles and related classes into ParticleStorage

Todo (I'll do these in separate PRs afterall, it just gets hard to manage if I try to do all in one):
- Extract VoxelGI into VoxelGIStorage or see if we can move this into the VoxelGI implementation classes
- Extract Fog into FogStorage or see if we can move this into the Fog implementation classes

### CODE REVIEW

**Comment by clayjohn** [comment]
That sounds like I good idea. I will take a closer look when I can. I have a feeling https://github.com/godotengine/godot/issues/59968 is related.

**Comment by BastiaanOlij** [comment]
I need to start doing more testing on GLES3, it's easy to get something mixed up. Though it compiles for me so wonder what that other issue is about, weird issue

**Comment by Calinou** [comment]
GLES3 was likely already broken by earlier pull requests (which landed in 4.0alpha6). See https://github.com/godotengine/godot/issues/60106.

**Comment by BastiaanOlij** [comment]
@Calinou to be honest, once we split all this stuff out it probably is more efficient to just do one big push getting GLES3 cleaned up. I noticed that almost all the stuff I'm splitting out isn't even implemented in GLES3, I'm guessing because we've only done the 2D stuff and I've hardly touched that so..

**Review by clayjohn — APPROVED** [review]
Looks mostly fine to me. I am a bit concerned about GLES3, but I am happy to dig into those issues after we merge this PR.

**Comment by clayjohn** [comment]
Thanks!

**Pull request merged**
