### PR TITLE
Fix autotiling bug added at #19127

### PR DESCRIPTION
**Pull request by marcelofg55**
I've introduced a bug for autotiles on #19127 without being aware of that, this PR fixes that bug and when autotiling the old undo logic is used.

### CODE REVIEW

**Comment by MarianoGnu** [comment]
I'm not sure if this is gonna work, try drawing with a normal tile over a big autotile area and then undo it (can't try myself right now)

**Comment by marcelofg55** [comment]
@MarianoGnu Yeah, just tried that, doesn't works as expected. Maybe we could use the optimized undo only if the tileset has no autotiles?

**Comment by MarianoGnu** [comment]
That would "work" but at the same time woudn't, since wont fix the original problem when you have a big map with autotiles, the Editor will freeze

**Comment by marcelofg55** [comment]
I don't think this is that hacky, it's simply using a better undo way for single tiling.
For whoever that reviews this if this PR is not accepted #19127 should be reverted.

**Comment by mhilbrunner** [comment]
Sounds like maybe this one should be reverted until a proper fix is found?

**Comment by akien-mga** [comment]
> Sounds like maybe #19127 should be reverted until a proper fix is found?

Agreed for now, I've reverted #19127 in #19159.

We'll still need a new fix for #18996 (which could end up being #19127 again + this #19146 if we don't find a better path).

**Pull request closed without merging**
