### PR TITLE
Clean up _validate_property

### PR DESCRIPTION
**Pull request by reduz**
-Made it multilevel (no need to keep track of parent)
-Replaced _hide_script_from_inspector by _validate_property, removed functionality from inspector.

Supersedes #34474

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
As discussed in #56530, the check added in #55530 could likely also be removed.

**Comment by raulsntos** [comment]
> As discussed in #56530, the check added in #55530 could likely also be removed.

I don't think that check can be removed or replaced with `_validate_property` because the problem in that case is that we have two `script` properties and we only want to hide one (not both).

As for #34474, `MultiNodeEdit` should hide the `script` property since it uses `scripts` so right now it still shows 2 properties in the inspector.

I'm also seeing a `script` property in the inspector for `AnimationTrackKeyEdit` which is supposed to hide it so I don't think this is working, I guess `_validate_property` is not being called, not sure why.

**Comment by akien-mga** [comment]
> As for #34474, `MultiNodeEdit` should hide the `script` property since it uses `scripts` so right now it still shows 2 properties in the inspector.

IMO this could be changed to not special case things in MultiNodeEdit. It should just show singular `Script` like for all other properties.

**Comment by raulsntos** [comment]
> > As for #34474, `MultiNodeEdit` should hide the `script` property since it uses `scripts` so right now it still shows 2 properties in the inspector.
> 
> IMO this could be changed to not special case things in MultiNodeEdit. It should just show singular `Script` like for all other properties.

Setting `script` is intercepted by `Object::set`:

https://github.com/godotengine/godot/blob/feb34dfb2e4ed748f9ea672e24cff69d1bfe1cd1/core/object/object.cpp#L416-L421

If the property is `script` it calls `set_script` and never reaches `setv` which would call the `_set` implementation in `MultiNodeEdit`. This sets the `script` for the active node which would set the `script` property of the `MultiNodeEdit` node, instead of setting the `script` property of all the selected nodes.

The `MultiNodeEdit` node itself is just a fake to act on behalf of multiple selected nodes, so we don't want to set any of its properties, its `_set` implementation just forwards this action to the selected nodes, but since the `script` property is intercepted by `Object::set` we can't modify this behavior from `MultiNodeEdit` unless we use a different name for the property.

**Comment by YuriSizov** [comment]
Can we at least replace `_validate_property` with a multilevel call, and then discuss removing the hack? I can revive this for you, @reduz. Accidentally, I worked on this myself today and this needs a rebase anyway. So I can make a new PR that only makes it a ML-call, and then a new PR can be made regarding the hack.

Sounds good?

**Comment by YuriSizov** [comment]
I've opened https://github.com/godotengine/godot/pull/64339 for the multilevel call part. The removal of the hack should be discussed separately, evidently. Can be patched in a follow-up.

**Pull request closed without merging**
