### PR TITLE
AudioDriverJavaScript buffer size calculation.

### LINKED ISSUE #35937: HTML5 Audio Slow / Stuttering on iOS
**Godot version:** 3.2 (also seeing the same issue with Godot 3.1, and 3.1.1)

**OS/device including version:** iPad 5th generation running iOS 13.3.1

**Issue description:** I'm seeing audio playing REALLY slow and stuttering (sounding robotic) on iPad HTML5 builds using .wav and ogg files.

**Steps to reproduce:**  Create a blank project,, add an AudioStreamPlayer and load a .ogg or .wav file in the AudioStreamPlayer and set it to play that audio file on a loop. Export to HTML5 and play on an ipad and the audio will play very glitchy, it will sound slow and robotic.

**Minimal reproduction project:** https://drive.google.com/file/d/14XzsamzGlBn_vx2y2OXpdhtkwTxjWEco/view?usp=sharing

### PR DESCRIPTION
**Pull request by Faless**
`AudioDriverJavaScript` now compute buffer size based on mix rate and expected latency like other audio drivers do.

Also move `audio/mix_rate` and `audio/ouput_latency` project settings to `AudioDriverManager`.
They used to be defined in each `AudioDriver` but the setting names are not driver specific.
Overriding is still possible via platform tags.

Fixes #35937 .
It should simply be fixed out of the box, but stuttering on low end devices is still possible, in that case `audio/output_latency` project setting could be adjusted during export, optionally as a platform override, with the relation `Higher latency = Less stuttering`.

I also have a [3.2-based branch](https://github.com/Faless/godot/tree/js/fix_audio_driver) if someone wants to try it (and for potential cherry-pick).

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by ChronoDK** [comment]
The sound on iOS is indeed perfect now, but instead it has the same lagging issues on Windows in Google Chrome! This needs a further look.

**Comment by Faless** [comment]
@ChronoDK did you try adjusting `audio/ouput_latency` and check the results? (Higher = less likely to stutter, Lower = less latency). What are the specs of your windows machine?

**Comment by ChronoDK** [comment]
@Faless Thanks, I have found that 70 is the lowest value that works on my Windows machine. It still works on iOS too, so I can just keep it at 70 right? Maybe that should be the default value instead of 15? My machine is usually not slow - Ryzen 5 1600, 16GB Ram.

**Comment by Faless** [comment]
70 is a very high latency, much above the 50ms threshold that is considered acceptable in terms of latency. Maybe it's some chrome-specific issue? Can you try Firefox and see if you can have lower latency?

**Comment by ChronoDK** [comment]
@Faless It works fine on Firefox with latency at 15. Microsoft Edge works too. So only Chrome has trouble with the low latency.

**Comment by Faless** [comment]
@ChronoDK Turns out the parameter we were not passed correctly can you try out this fix? https://github.com/Faless/godot/commit/f46c8746fb4e751c162ee4c6328acff6cc064110 . Alternatively we could revert back to not using `latencyHint` at all.

**Comment by ChronoDK** [comment]
@Faless You will have to send me a build of editor / export templates for me to test it. Sorry. 
Reverting the use of latencyHint would be bad right, if that is what made iOS work?

**Comment by ChronoDK** [comment]
@Faless But I guess the default value should be "interactive" as is recommended.

**Comment by ChronoDK** [comment]
Can confirm sound is working on both Chrome for Windows and Safari for iOS now with beta 4! Latency at 15ms. Great work!

**Comment by nice-shot** [comment]
Hi, I'm using the 3.2.2 beta and the sound seem to be working perfectly in Chrome for Windows and Chrome\Safari for iOS.
However, the lagging is now happening on android devices. Specifically tested on:
* Chrome 83.0.4103.101 on Galaxy S8 with Android  9
* Chrome 83.0.4103.96 on OnePlus 5T with Android 9

**Comment by Faless** [comment]
@nice-shot I presume you are using the latest beta (`3.2.2 beta 4`), can you try increasing the `Output Latency` value in `Project Settings -> Application -> Audio`? Does higher values make the audio better (e.g. 20/30 ms)? If yes, what values work well for you?

**Comment by nice-shot** [comment]
After playing with the `Output Latency` I've found that 50 gave out semi-decent results. It didn't stutter on Android but there was a bit of delay until the sound was played. The delay wasn't as noticeable on Windows or iPhone.
But it also happens that most of the audio files in my game are very short - usually less than 2 seconds. There is one audio file that's 5 seconds and it did stutter on Android a bit.

**Comment by thomazette** [comment]
I try with 60, and works well on tablet, IPAD, and android phone!!!

**Pull request merged**
