### PR TITLE
Fixed syntax highlighting setting not being saved

### LINKED ISSUE #21815: syntax highlighter setting not saved
latest master.
In the editor:
 - Go to GDS Editor
 - Click  syntax highlighter
 - Change it

reload godot, not saved

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed syntax highlighting setting not being saved

Fixes #21815

### CODE REVIEW

**Comment by akien-mga** [comment]
Yeah that's too much code just to save a tiny option like that IMO, it should reuse an existing format. Or at least it should be made more future proof so that it can be used to save other such contextual menu settings in the future.

CC @Paulb23

**Comment by DualMatrix** [comment]
You guys were totally right, updated to save settings in project metadata.

**Comment by girng** [comment]
Thanks!

**Comment by Paulb23** [comment]
This won't work as syntax highlighter setting's need to be done per open file, whereas this creates a global one. Therefore if you open a file, change the syntax highlighter, restart Godot every opened file will now have that syntax highlighter selected. 

In addition the `idx` cannot be trusted, if the syntax highlighter is removed, fails to load or a new syntax highlighter is added you'll end up with a random selection. It would be better to rely on the name.

The fix would be adjusting the loading under [set_window_layout](https://github.com/godotengine/godot/blob/master/editor/plugins/script_editor_plugin.cpp#L2467) and saving in [get_window_layout](https://github.com/godotengine/godot/blob/master/editor/plugins/script_editor_plugin.cpp#L2530) in `ScriptEditorPlugin`. Currently its just a list of files, but would have to be coveted to some kind of `HashMap` allowing storage of metadata.

This has been to my todo list for a while, but to store the last caret position, selection etc between sessions. (#19109).

**Pull request merged**
