### PR TITLE
[macOS] Extend editor contents to the window title bar for better space usage.

### PR DESCRIPTION
**Pull request by bruvzg**
Follow up for #63950

Enabling macOS global menu leave wasted empty space in the place of embedded menu, this PR extends contents of the window to the title bar for more efficient space usage.

- Adds `FLAG_EXTEND_TO_TITLE` to the `DisplayServer` / `Window` and `DisplayServer` methods to determine safe-area and behavior of dbl-click for title bar `window_get_safe_title_margins`, `window_maximize_on_title_dbl_click`, and `window_minimize_on_title_dbl_click` (implemented on macOS only).
- Applies it to the main editor window, if global menu is active.

The empty spacer parts between window control buttons, `2D / 3D / ...` tabs, and `Play ...` buttons act as a title bar for moving a window.

Screenshot 2022-08-23 at 13 49 04

Can be used with embedded menu as well, or disabled in the editor settings.

Screenshot 2022-08-24 at 13 56 09

<details>
  <summary>Demo project for using the same features</summary>

Screenshot 2022-08-26 at 15 40 19

Project: [Archive.zip](https://github.com/godotengine/godot/files/9433220/Archive.zip)

</details>

Partially implements https://github.com/godotengine/godot-proposals/issues/4846

### CODE REVIEW

**Comment by seppoday** [comment]
I know it is really hard to implement it on Windows. But, do you plan to try it also on that OS?

**Comment by seppoday** [comment]
> I know it is really hard to implement it on Windows. But, do you plan to try similar thing also on that OS?

**Comment by coppolaemilio** [comment]
Today I was able to test this a bit and I absolutely love it.

The only issue I found was that upon restart, the editor doesn't scale to the full size of the monitor, it leaves the gap where the previous title bar was.

Thank you so much for working on it!

**Comment by akien-mga** [comment]
I hate this feature because it makes me want to have a Mac and I don't like it. Hope we can have something like this with Wayland too in the future :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by stephannv** [comment]
Will this PR and https://github.com/godotengine/godot/pull/63950 be backported to 3.x?

**Comment by paddy-exe** [comment]
> Will this PR and https://github.com/godotengine/godot/pull/63950 be backported to 3.x?

Afaik the DisplayServer is new in Godot 4 and there were a lot of compatability breaking changes. So imo it's very unlikely that this will be backported to 3.6

**Pull request merged**
