### PR TITLE
General enhancements to the Polygon2D, TextureRegion, and TileSet editors

### LINKED ISSUE #17459: Bottom scrollbar in UV editor goes outside the window with large Polygon2Ds
**Godot version:**
 eceba5a

**Issue description:**
Self-explanatory:
screenshot1

### LINKED ISSUE #22280: Clicking on Polygon2D resets vertices and enters placement mode after using the Poly/UV editor.
**3.1 alpha 463af5b6ef0b4014b4d235364eb3a9713f7bc314**

It should be related to this https://github.com/godotengine/godot/issues/21698, it appears at least this was two problems together. 

@groud fixed the polygon manipulation getting trapped:  https://github.com/godotengine/godot/pull/22247

# Summary

When creating a new polygon in the poly/uv editor, the first thing that happens when attempting to drag or move it, is that it resets and goes back into edit mode as if there were no vertices.  So there may be some loss of information when swapping between the UV window and the main canvas.

No longer does it get stuck, but this will reset your polygon.

ezgif com-video-to-gif

# Steps to Reproduce

1. Create a Polygon2D (Don't assign any vertices here.)
2. Assign a texture.
3. Enter the **UV** editor from the toolbar.
4. Switch to the **Poly** tab.
5. Draw out a polygon here.
6. Hit OK and return to the canvas viewport.
7. Try to drag the newly created polygon.  (It will reset)

As far as I can tell nothing else appears to be selected on the canvas toolbar that may cause this, but it is at the very least an unexpected/undesirable behavior.  XD

### PR DESCRIPTION
**Pull request by YeldhamDev**
## All
- Added a style override for the main contents using `Tree`'s "bg" element.
- Made them obey container rules (truly fixing #12679).
- Made scrollbars stay inside the editors (fixes #17459).

## Polygon2D
screenshot at 2018-11-25 16-06-42
- Made the window resizable.
- Removed the slight window transparency.
- Changed the grid color to a more subtle tone.
- Show previous outline (if enabled) when editing polygon points.
- Made the bone list resizable.
- Made the list start with one bone already selected.
- Made possible to sync bones when there's no skeleton or bones, basically cleaning all bones present.
- Made the snap option actually do something (It's not perfect, it works fine in single-point editing, but the other modes get kinda wacky. Still, better than do nothing at all).
- Make the canvas' polygon editor change to edit mode when creating a new polygon (fixes #22280).
- Make possible to undo a newly created polygon, and fixed crash when undoing a `Polygon2D` node removal.
- Save current state in the project's metadata.

## TextureRegion
screenshot at 2018-11-26 01-33-14
- Made the snapping menu an true `OptionButton`.
- Moved it back besides the snap menu.
- Placed the zoom buttons at the top left of the region editor, like it is in the canvas editor.
- Make do/undo action feedback instantaneous, instead of needing to get the editor out of focus.

## TileSet
screenshot at 2018-11-26 03-41-23
- Made zooming with `CTRL + Mouse Wheel` levels be same as with the zoom buttons.
- Disabled "New Tile" buttons when not texture is selected.
- Fixed tile ID errors when first opening the editor.
- Various drawing fixes.
- Added tooltips.

### CODE REVIEW

**Comment by avencherus** [comment]
Nice.

Seeing this made me think back about an older issue I had https://github.com/godotengine/godot/issues/22280, and wonder if you might know more about it.   

The Canvas 2D and Polygon2D editor toolbars don't seem to be very well coordinated with each other.

**Comment by YeldhamDev** [comment]
@avencherus It seems that the problem is not with the UV editor, but just with the canvas. If you click in a polygon node without points, and then click in one with some, it will be in create mode as well.

I will see what I can do later.

**Comment by avencherus** [comment]
@YeldhamDev That was quick.  XD  Thanks so much for looking into it and including it.  I just did a test build, and the change works much better now.

I'm going split out those secondary issues in that thread into enhancement requests.

**Comment by YeldhamDev** [comment]
@avencherus Just did some final touch-ups in the UV editor, would you mind doing some corner case testings, to see if everything is already (or at least, not worse than before)?

**Comment by avencherus** [comment]
@YeldhamDev Sure thing.  First chance I get in the morning I will play around with it.

**Comment by avencherus** [comment]
@YeldhamDev Some initial testing results.  X)

Most things seem working just fine.  The window resizing is a very welcome change.  A couple minor things that I wonder about, and only one thing so far that's an issue.  It might be unrelated or a bad build on my part, hopefully you can recreate it.

There was a crash involving undo, and some other issues with using undo.

First is a question.  Should their be a redo?  Maybe I'm using the wrong hotkeys?

Then I found problems when you hit Undo multiple times beyond what was done in the Polygon 2D Editor.

The first problem that arises is that it begins undo'ing the things in the editor behind the tool, and then beyond that, if you keep going, it will crash.  Below is a video of the undo clearing the texture that I added, and then also I included a trace of the crash that occurred when spamming undo.

### Video
Here I undo all the polygon work, and at the end, an extra undo clears the Inspector's texture property.  The editor doesn't reflect this change until you try to do an edit on the polygon.
ezgif com-video-to-gif 1

### Stack Trace
A few more undo operations crashed the editor with this output.
> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] Ref<Texture>::ref (c:\godot\custom\core\reference.h:70)
> [1] Ref<Texture>::Ref<Texture> (c:\godot\custom\core\reference.h:204)
> [2] Polygon2D::get_texture (c:\godot\custom\scene\2d\polygon_2d.cpp:424)
> [3] Polygon2DEditor::_uv_draw (c:\godot\custom\editor\plugins\polygon_2d_editor_plugin.cpp:874)
> [4] MethodBind0<Polygon2DEditor>::call (c:\godot\custom\core\method_bind.gen.inc:139)
> [5] Object::call (c:\godot\custom\core\object.cpp:945)
> [6] Object::emit_signal (c:\godot\custom\core\object.cpp:1231)
> [7] Object::emit_signal (c:\godot\custom\core\object.cpp:1288)
> [8] CanvasItem::_update_callback (c:\godot\custom\scene\2d\canvas_item.cpp:447)
> [9] MethodBind0<CanvasItem>::call (c:\godot\custom\core\method_bind.gen.inc:139)
> [10] Object::call (c:\godot\custom\core\object.cpp:945)
> [11] MessageQueue::_call_function (c:\godot\custom\core\message_queue.cpp:256)
> [12] MessageQueue::flush (c:\godot\custom\core\message_queue.cpp:302)
> [13] SceneTree::iteration (c:\godot\custom\scene\main\scene_tree.cpp:477)
> [14] Main::iteration (c:\godot\custom\main\main.cpp:1834)
> [15] OS_Windows::run (c:\godot\custom\platform\windows\os_windows.cpp:2736)
> [16] widechar_main (c:\godot\custom\platform\windows\godot_win.cpp:150)
> [17] _main (c:\godot\custom\platform\windows\godot_win.cpp:172)
> [18] main (c:\godot\custom\platform\windows\godot_win.cpp:184)
> [19] __scrt_common_main_seh (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253)
> [20] BaseThreadInitThunk
> -- END OF BACKTRACE --

Other than that, just some minor things.  Wondering if the polygon and texture origin should be aligned to the center of the editor, rather than to the top-left?  I always find myself zooming and realigning to get a better view of the left and top sides of the texture when I enter the tool.

The other is this remove splits icon.  I puzzled over it for a minute, and then after experimenting, realized it was to break the split.  XD

godot windows tools 64_2018-11-28_12-15-25

Lastly, there was mention of metadata being stored.  I didn't catch it on my simple scene, so I'm not too sure what triggers it, or if it's temporary.

image

**Comment by YeldhamDev** [comment]
@avencherus
- There's a redo, it's `CTRL + ALT + Z`.
- Undoing past the UV Editor happens because the editor's `UndoRedo` resource is global, so the history is shared. You can see you're also able to undo actions in something like the Editor Settings even if the dialog was closed for example.
- I was not able to reproduce the crash, could give me a step-by-step?
- The UV Editor not redrawing is because changes made outside of it don't request it. I'm still seeing what can be done about that. Without a `Texture` resource, you should not even be able to have the UV Editor open.

**Comment by avencherus** [comment]
Thanks.  The redo is working fine.

The crash only happens when a new polygon is created.  Saved scenes with saved textures don't cause it.  So the steps I'm doing are:

1) Create a new Polygon2D
2) Assign a texture to it's texture property.
3) Go directly into UV editor.
4) Switch to Poly tab and define a Polygon.
5) Spam Undo (CTRL + Z) until it crashes.

**Comment by avencherus** [comment]
@YeldhamDev Nice work. 👍 

It is working smoothly now to undo/redo back up.  

Yes, I do quite like the previous outline feature.  Very nice addition.  X)

When closing out, I noticed I had some editor errors from Undo/Redo.  Can't seem to replicate it, but it happened after I drew a bad polygon, doubtful about if that caused it.

I will post back if I ever figure out how to reproduce it.

image


image

**Comment by YeldhamDev** [comment]
@akien-mga Are you sure you want to move this to **3.2**? This doesn't add any major features, and the editors (specially the UV one) where kinda of a mess before.

I also just concluded messing around on this PR, there are some more improvements I want to make, but it's already a little too big for its own good.

**Comment by akien-mga** [comment]
Well I really like what I see in the description and overall code changes, but it's a lot of changes for a post-feature freeze PR. If other contributors can help review and are relatively confident that it's a net improvement with little to no risk of introducing new bugs, I'm happy considering it for 3.1.

@groud maybe?

**Comment by YeldhamDev** [comment]
I could also chop it into smaller PRs if that would help.

**Comment by groud** [comment]
I read the changes really fast, and they looks mostly good to me. Please next time split that into several PRs, it is easier to review local changes, especially when they are independent. :)

Honestly, I think this is good to merge. The UX was so bad with those editors so that anything that can improve them before 3.1 is good to take. And they probably kept mostly untested also because of that.
(I personally could not manage easily to make the polygon editor work).

**Comment by YeldhamDev** [comment]
@akien-mga Glad to be useful!

@groud This was supposed to be a small PR at the beginning, just to fix #17459 and make the editors use the `Tree` background style. But as I was digging, I found more and more problems with them, and I just couldn't contain myself.

**Pull request merged**
