### PR TITLE
Make environment energy adjustable as a float in 3D editor's preview environment

### LINKED ISSUE #76742: Sky energy is an integer in preview environment.
### Godot version

4.0.3

### System information

Windows 10

### Issue description

In the preview environment popup environment energy is an integer which makes it different to adjust.
Related to #76677  
While reporting this i don't notice that environment panel also have the same problem.
I will try to fix this too.

### Steps to reproduce

Go to preview environment popup.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by HotHead007**
this closes #76742

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Seems fine to me

**Review by smix8 — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
LGTM, thanks!

**Comment by HotHead007** [comment]
I am sorry I am new to git. Did u mean make a branch of my fork of godot and then make my changes merge it back to my fork and open PR?
Wouldn't it be same?

**Comment by Zireael07** [comment]
Yes, making branches of your fork. Don't merge them into your master, open PR from the new branch

**Comment by mhilbrunner** [comment]
See also: https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Pull request merged**
