### PR TITLE
`Image` Fix `rotate_90`/`rotate_180` methods

### LINKED ISSUE #64048: `Image.rotate_90()` exhibits scaling artifacts
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 10, 64bit

### Issue description

Image.rotate_90 not perfect, look:
Cap

### Steps to reproduce

Please run the reproduction project

### Minimal reproduction project

[RotTest.zip](https://github.com/godotengine/godot/files/9276746/RotTest.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Changes/fixes `Image::rotate_90` so it doesn't use `Image::resize` as it's not needed (and was resulting in interpolating the pixels). Now rotation happens in-place by direct pixel manipulation (and swapping `width` and `height` after all).
Fixes #64048.

Fixes `Image::rotate_180` which was not flipping the middle row for odd-height images. It's also ~2.5x faster now.

Also now these methods don't throw an error on `width == 1` or `height == 1`.

|4.0.alpha14|this PR|
|-|-|
|zISWfVcjSu|EMHrxEzPTa|
|Godot_v4 0-alpha14_win64_LJ4oFX4Zof|YcZLVwjPhb|

More details on `rotate_90`:
Pixels are being moved according to the cycles in the permutation the given 90 degrees rotation (clockwise/counterclockwise) defines (rotating just permutes 1D pixel buffer of the image).
Current implementation is based e.g. on [this paper](https://www.hpc2n.umu.se/sites/default/files/events/para06/papers/paper_218.pdf). But it's applying rotation-permutation, not transposition-permutation (rotation could be made by transposition+flip in 2 steps but in this PR it's done directly in 1 step). Nonetheless, this is a simple, naive implementation (the part determining which pixels were not yet moved).
It can be fast/slow depending on how permutation decomposes into cycles (it's quite random for rectangular matrices). It's correct and in some cases super fast but the worst case could be slower than the current incorrect implementation which uses resizing. Treat it as a bug-fix. I'll look into improving it performance-wise (the worst case) some time later in another PR.

### CODE REVIEW

**Review by groud — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]
Approved by PR meeting and the consul of Yuris

**Comment by akien-mga** [comment]
Thanks!

**Comment by kleonc** [comment]
> Approved by PR meeting and the consul of Yuris

YR_Yuri's_subliminal_propaganda

**Comment by akien-mga** [comment]
Heh, had to reverse image search to understand, so saving some folks the trouble ;)
https://villains.fandom.com/wiki/Yuri_(Command_%26_Conquer)

**Pull request merged**
