### PR TITLE
Fixed #8526, popup menu width now responds to submenu icon

### LINKED ISSUE #8526: PopupMenu submenu arrow is misplaced
Tested on Godot 2.1.2 and master
Windows 10 64 bits

The following test code:

```gdscript
	var menu = PopupMenu.new()
	menu.add_item("One")
	menu.add_submenu_item("Submenu", "Submenu")
	add_child(menu)
	var submenu = PopupMenu.new()
	submenu.add_item("Apple")
	menu.add_child(submenu)
	menu.popup()
```

Produces a menu with sub-menu, but the arrow is not included in the calculation of the width, making it overlap with the text:

image

A workaround is to manually hardcode the size of the menu.

### PR DESCRIPTION
**Pull request by AlexHoratio**

### CODE REVIEW

**Comment by AlexHoratio** [comment]
I'm not a Github veteran.. what does the Travis CI want me to do? :/

**Comment by Zireael07** [comment]
Probably format according to clang specs? @AlexHoratio

**Comment by volzhs** [comment]
https://github.com/godotengine/godot/tree/master/misc/hooks
this will help.

**Comment by AlexHoratio** [comment]
Hooray, I've satisfied Travis CI after a bit of flailing

**Comment by akien-mga** [comment]
Now you'll need to satisfy @godotengine/pr-mergers with a bit of spring cleaning of this commit history :) http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by AlexHoratio** [comment]
Since it really didn't need more than one commit, I've stuck them all together. Thanks for your help!!

**Pull request merged**
