### PR TITLE
Replace render tree bvh with version from 3.x

### PR DESCRIPTION
**Pull request by lawnjelly**
Some modifications of the collision routines to allow it to work more efficiently with the template callback mechanism of the old dynamic_bvh API.

This adds a new wrapper `BVH_Simple` for a front end of this simplified version for the render tree compared to the `BVH_Manager` (which creates the full pairing version, which is used in the physics and also Godot 3).

## Notes
* This should hopefully be a pretty smooth changeover, as the BVH is already pretty tested, the only change is the new simple interface, and mechanism for callbacks used in Godot 4, and hopefully any bugs in this should be easily fixed. 
* It turns out Godot 4 doesn't use the BVH for frustum culling so I've tried to test as best I can.
* There's still some unnecessary data being stored in the simple BVH that was to do with pairing. I can try and figure out a way to compile this out, it's not strictly necessary to get started though, it should just improve performance / memory use a tad in extreme cases.
* I'm kind of torn about whether to cover both collision paths in the same code (as this does) or separate them out to neaten things. As there still may be a bug in the BVH (#48749, #48790) there is an argument to making sure that is fixed, before separating them out for greater readability - it's a little bit more ugly than it could be at the moment, but this may be temporary.
* I've tried to check the performance of the existing physics and the changes supporting both paths do seem to be optimized out as far as I can see.

Feel free to try this out and let me know bugs.

Performance wise I don't have a good test case yet, because Godot 4 isn't typically making many BVH tests, so I've only been able to compare the general tree updating. The updates alone for 10,000-20,000 spinning boxes seem to give me a frame rate about 1.5-2x faster than the old version. But as ever I emphasise the changes are primarily for stability rather than performance (render tree is unlikely to be a major bottleneck in most games).

I tried the examples in godot-benchmarks repository, but I'm not sure they really stress the bvh, and the results weren't very repeatable when I tried them, making them a bit harder to interpret. In general spinning a bunch of objects on a central axis is a good test of spatial partitioning because it forces continuous rebuilding the tree, and this is the test that I quoted above which seems faster.

I did still notice this bug occurred #44973 even with the new bvh, but it turns out on investigation the problem isn't in the bvh, but in the visual server, and we have some fixes in the works so that shouldn't hopefully be a problem much longer.

### CODE REVIEW

**Comment by lawnjelly** [comment]
Having refreshed my memory on this PR (was a couple of months since I worked on it), it has been performance tested (see above) and is good to go I think. Just needs a review. It's pretty much a thin wrapper on the existing BVH to cover the new simple interface in 4.x.

There's a fair amount of boiler plate going on, due to retaining compatibility with the existing BVH so we can keep a common codebase, but it should be compiled out as it is a template. We could alternatively produce a stripped down version just for the rendering, but this doubles the bug surface, and work because of keeping them both updated. So I'm not convinced this is a good idea, especially at this stage (certainly something we could look at in future though).

**Comment by lawnjelly** [comment]
I've gone over running the `godot-benchmarks` again and these all seem pretty much within the margin of error from each other. The margin of error in these benchmarks seems very large (due to gdscript, log outputs etc, what is running in background?), and I'm not sure they are very efficiently measuring what we are interested in, or stressing the BVHs - there seems very little movement in these scenes, and hence "node churn". Often I was getting variation of 10% + between runs.

But here's 3 tests each, using the BVH at 256 leaf size, and 32 leaf size, and the old BVH. On these benchmarks 32 leaf size does better, but doesn't mean it is a better choice overall:
```
Static 256 : (5.70, 5.66, 5.68) 32: (5.72, 5.79, 5.78) OLD: (5.82, 5.83, 5.89)
Dynamic 256: (13.04, 13.07, 13.19) 32:(12.29, 12.70, 12.58) OLD: (12.59, 12.65, 12.69)
Static Lights 256: (9.69, 10.26, 10.22) 32:(9.61, 9.92, 9.86) OLD: (10.1, 10.18, 10.32)
Dynamic Lights 256: (12.85, 12.70, 12.59) 32:(11.38, 11.20, 10.90) OLD: (11.13, 10.73, 10.99)
Directional Light 256: (16.35, 16.62, 16.01) 32:(15.56, 15.44, 15.42) OLD: (16.04, 16.4, 16.15)
```
As I say in tests with rotating the scene, the new BVH is 1.5 - 2x faster. It's possible to tune things for some particular benchmark, but more interesting is the performance in worst case scenarios. I'll try and dig out the benchmark I used for this.

**Comment by reduz** [comment]
The test you care about is dynamic cull (https://github.com/godotengine/godot-benchmarks/blob/main/rendering/culling/dynamic_cull.gd). The measure is how much the scene takes doing this. during rendering (no nodes used and timing is confined to actually what matters)

**Comment by lawnjelly** [comment]
Just to keep this updated, this is ready for a review in terms of getting in before the 4.0 alpha, it should be pretty easy as it is just a thin wrapper.

We had a look at the performance, and reduz is happy that is within the same region as the old version in his test case (it was just to check that this wasn't dramatically slower or something like that).

**Comment by lawnjelly** [comment]
I had to rebase it and something went wrong, it could have been the bug with the formatting tools that deleted a load of code (it nearly deleted a load of code in another PR, I mentioned it at the time). I'll have to see whether I can recover it, I'm not very good with git. Or else rewrite the PR...

**Comment by lawnjelly** [comment]
Closing this for now as I'll probably end up rewriting this once we have transferred the refactored BVH from 3.x to 4.x, and this version no longer compiles.

**Pull request closed without merging**
