### PR TITLE
added get_root_node()

### PR DESCRIPTION
**Pull request by AlexHolly**
http://www.godotengine.org/forum/viewtopic.php?f=11&t=1317

### CODE REVIEW

**Comment by eska014** [comment]
The forum link is no longer valid — what's the point of this function?
Except for the `NULL` check, it appears equivalent to `get_tree().get_current_scene()`.

The function identifier is somewhat misleading, since it retrieves the current scene root rather than the actual root node.

**Comment by AlexHolly** [comment]
The forum link was showing a solution to get the root node and it looked like this

var root = get_tree().get_root()
var root_node = root.get_child(root.get_child_count() - 1)

is that equal to "get_tree().get_current_scene()"?

**Comment by eska014** [comment]
The *scene tree root* is retrieved using `get_tree().get_root()`.

The root of the current scene can usually be retrieved using the code you posted, since the the current scene is always the last child of the scene tree root, after the *autoload nodes*.
However, if there is no current scene, or if it's been moved above one of its siblings, and there are autoload nodes, the last autoload node will (likely unintentionally) be returned instead.

`get_tree().get_current_scene()` accomplishes the same thing, but returns NULL when there is no current scene, even with autoload nodes. This works because the scene tree main loop implementation stores a pointer to the current scene.

**Comment by AlexHolly** [comment]
So I think "get_tree().get_current_scene()" is exactly what I was looking for.
I tested on one example and it works.

"get_tree().get_current_scene()" is new to me thanks.

**Comment by akien-mga** [comment]
Excellent explanation @eska014 :) If it's not somewhere in the wiki already, it should definitely be added :)

**Pull request closed without merging**
