### PR TITLE
Expose `String::camelcase_to_underscore`

### PR DESCRIPTION
**Pull request by dalexeev**
This function can be useful in plugins for converting filenames or in code for converting identifiers between different languages.

### CODE REVIEW

**Review by aaronfranke — CHANGES_REQUESTED** [review]
This method should be named with either `snake_case` or `snakecase`. "underscore" is ambiguous because there is also `TO_HTML` which uses underscores but isn't lowercase.

**Review by neikeq — CHANGES_REQUESTED** [review]
I haven't tested this but I can already see calls to `isUpper` and `isDigit` in C# code. Those functions should be PascalCase, if they exist.
I suggest replacing it with an internal call though.

**Review by neikeq — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs a rebase, otherwise should be fine to merge.

**Comment by mhilbrunner** [comment]
@dalexeev Can you rebase this? :)

**Comment by dalexeev** [comment]
> Can you rebase this?

Done. But I think we'd better implement this:

> ```
> s.to_lower()
> s.to_upper()
> s.capitalize()
> s.to_snakecase()
> s.to_camelcase()
> s.to_pascalcase()
> ```

**Comment by akien-mga** [comment]
> Done. But I think we'd better implement this:
> 
> > ```
> > s.to_lower()
> > s.to_upper()
> > s.capitalize()
> > s.to_snakecase()
> > s.to_camelcase()
> > s.to_pascalcase()
> > ```

I think that's a good idea. Should we then close this PR and have someone (you?) work on that proposal (which solves https://github.com/godotengine/godot-proposals/issues/719 I suppose)?

**Comment by dalexeev** [comment]
> I think that's a good idea. Should we then close this PR and have someone (you?) work on that proposal (which solves [godotengine/godot-proposals#719](https://github.com/godotengine/godot-proposals/issues/719) I suppose)?

#63902

**Pull request closed without merging**
