### PR TITLE
[3.x] implements sky contribution saturation on ambient light

### PR DESCRIPTION
**Pull request by Gnumaru**
This PR implements a sky ambient light contribution saturation control via an environment resource parameter as shown in the attached video.

Since this is specific to 3.x, I'm doing the PR over 3.x instead of master.

https://user-images.githubusercontent.com/5783414/157850644-819b64c3-49cb-4458-a564-b5bee84f9460.mp4

### CODE REVIEW

**Comment by clayjohn** [comment]
The idea looks great! 

Could you please open [a proposal](https://github.com/godotengine/godot-proposals) so that other users can let us know if they would find this useful? We try to only add new features that have a significant demand from multiple users.

If others say they would also find this useful for their projects, then you will also need to make a 4.0 version of this PR so that the feature can be merged to 4.0 and 3.x simultaneously.

**Comment by Gnumaru** [comment]
I've created this proposal for everyone to discuss the topic.

https://github.com/godotengine/godot-proposals/issues/4211

**Comment by Gnumaru** [comment]
[NotBlue3D.zip](https://github.com/godotengine/godot/files/8310158/NotBlue3D.zip)

I'm attaching a minimal sample project showing how someone could, with the current godot 3.x stable release, decouple the sky box colors from the actual ambient light. It involves using a second camera inside a second viewport, and using different environments for each camera. It is a much more complex setup than just having a single property for adjusting the ambient light saturation as I propose.

Please note that just setting the ambient light color to pure white and the sky contribution to zero does not yields the same outcome, because setting the sky contribution to 1 generates a nice fake shadow for faces pointing downward, since the sky is in most usage scenarios much brighter than the ground, resulting in faces with normals pointing up being much more bright and faces pointing down much more dark. With sky contribution set to zero the ambient color is used regardless of face orientation, there is no "fake shadows", which yields a very different result.

**Comment by Calinou** [comment]
> I'm attaching a minimal sample project showing how someone could, with the current godot 3.x stable release, decouple the sky box colors from the actual ambient light. It involves using a second camera inside a second viewport, and using different environments for each camera. It is a much more complex setup than just having a single property for adjusting the ambient light saturation as I propose.

A simpler alternative is to use a desaturated background sky, place a large sphere in the scene with an unshaded material and add your saturated sky texture as the albedo texture of that sphere. In a script, move this sphere to be at the same position as your camera in `_process()` (but don't rotate it).

**Comment by Gnumaru** [comment]
Indeed. Using a sphere mesh with flipped normals, a sky texture, and desaturating the procedural sky default environment colors is really a much simpler approach.

But there are some nice things that can be made with a visible procedural sky, like procedurally changing the sky colors and the sun size and position according to the time of day. Reproducing this kind of effects with a textured skybox mesh would require more effort.

I still agree, though, that for static skies, a giant textured sphere with flipped normals is far simpler.

**Comment by Zireael07** [comment]
Looks like something went wrong, tons of unrelated commits?

**Pull request closed without merging**
