### PR TITLE
Add disable ambient light flag to shaders and materials

### PR DESCRIPTION
**Pull request by EIREXE**
Useful for mixing toon shaders and other types of diffuse.

### CODE REVIEW

**Comment by CptPotato** [comment]
Good contribution, but I'm a bit confused, as there already is a "no_ambient_light" boll in scene.glsl

**Comment by EIREXE** [comment]
@CptPotato We can remove that bool, as it's never used.

**Comment by EIREXE** [comment]
I've gone ahead and removed the bool as it's unused and replaced all uses of it with preprocessor commands.

**Comment by akien-mga** [comment]
Could you rebase to get rid of the merge commit? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by EIREXE** [comment]
Oh right I forgot to do it, I'll do it as soon as I wake up.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
