### PR TITLE
[4.0] iOS Game Center improvements

### PR DESCRIPTION
**Pull request by PoqXert**
#40557 for 4.0

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you squash commits into one, and make the commit title a bit clearer? E.g.:
```
iOS GameCenter: Add authenticate method

And no longer connect automatically.
```

**Comment by akien-mga** [comment]
And could you add the matching documentation to https://docs.godotengine.org/en/latest/tutorials/platform/services_for_ios.html#game-center ?

**Comment by naithar** [comment]
@PoqXert you will need to rebase your commit, since `master` branch was updated to support Vulkan on iOS.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
