### PR TITLE
pcre2: Update to upstream version 10.40

### PR DESCRIPTION
**Pull request by akien-mga**
Changelog: https://github.com/PCRE2Project/pcre2/blob/pcre2-10.40/ChangeLog

### CODE REVIEW

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
@bruvzg Seems like this update broke support for older macOS:
```
In file included from thirdparty/pcre2/src/pcre2_jit_compile.c:79:
In file included from thirdparty/pcre2/src/sljit/sljitLir.c:275:
thirdparty/pcre2/src/sljit/sljitExecAllocator.c:156:2: error: "Must target Big Sur or newer"
#error "Must target Big Sur or newer
```

I wonder if we should patch it out, or revert to 10.39 (at least for 3.5)?

**Comment by akien-mga** [comment]
Seems like we could cherry-pick this: https://github.com/carenas/sljit/commit/de8fc816bc6698ab97316ed954e133e7e5098262

**Comment by bruvzg** [comment]
Was added in https://github.com/zherczeg/sljit/pull/111

> Seems like we could cherry-pick this: https://github.com/carenas/sljit/commit/de8fc816bc6698ab97316ed954e133e7e5098262

Yes, this seems to be fine. But I would simplify it to just the second `available` branch.

**Comment by akien-mga** [comment]
> > Seems like we could cherry-pick this: [carenas/sljit@de8fc81](https://github.com/carenas/sljit/commit/de8fc816bc6698ab97316ed954e133e7e5098262)
> 
> Yes, this seems to be fine. But I would simplify it to just the second `available` branch.

I'd go with the upstream solution for now, but feel free to PR the simplification there, that makes sense.

**Pull request merged**
