### PR TITLE
Samplelibrary size

### LINKED ISSUE #5556: Access to SampleLibrary size() - feature proposal
**Operating system or device - Godot version:**
v2.0.3.stable.official

**Issue description** (what happened, and what was expected):
A feature proposal.
I wanted to know on runtime the size of a SampleLibrary content to play a random sample.
Therefore I can't find a way to get the size of samples (sound files) inside a SampleLibrary in script.
It'll be nice to have a 'size()' or a 'count()' or even a 'play_random()'

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

### PR DESCRIPTION
**Pull request by J08nY**
Added `SampleLibrary.size()` and `SampleLibrary.get_sample_names()`
fixes #5556 

EDIT: Changed to `SampleLibrary.get_sample_count()`

### CODE REVIEW

**Comment by eska014** [comment]
`size()` is usually implemented only for data structure classes, isn't `sample_lib.get_sample_names().size()` good enough? Performance shouldn't be too bad, it's not like a SampeLibrary has thousands of entries.
Otherwise, how about something like `SampleLibrary::get_sample_count()`

**Comment by J08nY** [comment]
Hmm, yeah I will rename it to `get_sample_count()`

**Comment by akien-mga** [comment]
@J08nY I guess @reduz either overlooked the fact that this was a PR, or forgot to comment about why he'd prefer to implement it differently, but I guess your commits were obsoleted by 49b288d.

**Comment by reduz** [comment]
Oh sorry, I didn't realize you made the fixes mentioned. I also took the chance to fix the constness of the functions, which seems I got wrong when wrote the code originally

**Pull request closed without merging**
