### PR TITLE
Expose `AudioServer.capture_device` as a property

### PR DESCRIPTION
**Pull request by Calinou**
Follow-up to https://github.com/godotengine/godot/pull/58104.

This is more consistent with `AudioServer.device` (for output), which is already exposed as a property.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs doctool sync.

**Comment by akien-mga** [comment]
There's still a diff between doctool output from Linux and this PR. Is that a system-specific setting that should be overridden, or is it "Default" for all platforms?

**Comment by Calinou** [comment]
> There's still a diff between doctool output from Linux and this PR. Is that a system-specific setting that should be overridden, or is it "Default" for all platforms?

It's supposed to be `"Default"` (case-sensitive) on all platforms, but maybe some OS implementations aren't following this.

**Comment by akien-mga** [comment]
Well that's what the CI wants you to add, maybe you didn't run doctool with these changes? Or does your local doctool actually fail setting "Default" as default value?

**Comment by akien-mga** [comment]
Well that means PulseAudio gives your `""` as output for `capture_get_device()`, which sounds like a bug, as the code is written with the expectation that it would be `"Default"`.

Either way, you can just add a `ADD_PROPERTY_DEFAULT` to work it around and make it consistent for the docs.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
