### PR TITLE
Update etcpak to 2.0

### PR DESCRIPTION
**Pull request by BlueCube3310**
Depends on #89567

Updates etcpak to 2.0, the latest official version. Said version also includes bc7enc as a dependency (though not used by Godot's importer), should it be removed with a Godot-specific patch?

### CODE REVIEW

**Comment by fire** [comment]
It makes sense to add a readme addition to remove bc7enc

**Comment by clayjohn** [comment]
It looks like all this does is remove `CompressEtc1Alpha` and `CompressEtc2Alpha` and adds `CompressBc7`. But I guess it would be nice to be back on an official release. 

Is there any value in us using the BC7 compression here? Or do we use a different/better library already?

**Comment by BlueCube3310** [comment]
The BC7 compression is much faster than CVTT (what Godot uses currently), although the quality is generally lower (only 4 block modes are available) and most of the performance improvements require SSE4/AVX2.

**Comment by clayjohn** [comment]
> The BC7 compression is much faster than CVTT (what Godot uses currently), although the quality is generally lower (only 4 block modes are available) and most of the performance improvements require SSE4/AVX2.

Ah, so probably not worth integrating yet. I would do a Godot-specific patch to remove it just due to the size

**Comment by BlueCube3310** [comment]
I'm closing this for now as the upstream changes aren't significant to Godot's implementation, plus now it requires a patch.

**Pull request closed without merging**
