### PR TITLE
Make direct casting among Error and godot_error enums (#23015).

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @karroffel @touilleMan

**Comment by karroffel** [comment]
Does this change fix a problem that you encountered?

**Comment by marxin** [comment]
> Does this change fix a problem that you encountered?

Yes, it's fixing:
```
modules/gdnative/pluginscript/pluginscript_language.cpp: In member function 'virtual Error PluginScriptLanguage::complete_code(const String&, const String&, Object*, List<String>*, bool&, String&)':
modules/gdnative/pluginscript/pluginscript_language.cpp:176:16: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   Error err = *(Error *)&tmp;
                ^~~~~~~~~~~~~
```

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
