### PR TITLE
Workaround negative delta by clamping it to zero

### PR DESCRIPTION
**Pull request by nathanfranke**
**EDIT: Go to** #35617 **for improved changes**

Workaround for #26887 

CC @reduz, not sure what time_deficit is supposed to do. (Is it related to issues with the time diverging?)

Edit: Good project for reproducing this bug, it causes a lag spike about once every 4 ticks. I haven't had any problems after making this change.  
[TimeBug.zip](https://github.com/godotengine/godot/files/4112856/TimeBug.zip)

### CODE REVIEW

**Comment by nathanwfranke** [comment]
@Calinou I think this effects all platforms

**Comment by nathanwfranke** [comment]
This still needs to be tested. There is a problem with delta being way too large

problem

**Comment by nathanwfranke** [comment]
I think that the solution to this problem is probably not to remove `time_deficit`. I made it so the idle time is clamped to zero as a workaround. There is definitely still an issue and this PR is only a temporary workaround

**Comment by lawnjelly** [comment]
The negative deltas seems to be showing up a bug in the jitter fix. With jitter fix set to 0.0 I'm no longer getting negative deltas.

Rather than just clamp the deltas here, I think we additionally need to investigate whether a bug fix in the 'jitter fix' code is needed. I agree that for last ditch safety imo we should probably clamp, however there is also a good argument for outputting a WARN_PRINT_ONCE message, e.g.
```
WARN_PRINT_ONCE("Negative delta detected");
```
Because when this occurs it indicates an error in the timing code, and we need to address this if it happens in future (rather than ignore it). I.e. it is silently working around an error which should _not_ be occurring, and we need to flag this.

Disabling time_deficit is not really an option, that's a central part of how the timing works (it accumulates time over frames in order to decide how many physics ticks to run).

**Comment by nathanwfranke** [comment]
Check #35617 for improved changes by @zmanuel. I will probably close this right after their commit is merged

**Comment by akien-mga** [comment]
Superseded by #35617.

**Pull request closed without merging**
