### PR TITLE
[TileMap] Fix forcing cleanup on exiting tree/canvas

### LINKED ISSUE #89769: Tilemap light occluders affect all open scenes in the editor
### Tested versions

- Reproducible in v4.3.dev.mono.custom_build [fe01776f0] and v4.2.2.rc.mono.custom_build [15c5e10ea]
- Not reproducible in v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.2.rc.mono (15c5e10ea) - Ubuntu 22.04.4 LTS 22.04 - Wayland - Vulkan (Forward+) - integrated AMD Unknown (RADV RENOIR) () - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

When adding a tile from a tileset with a light occluder to a scene, it affects all other open scenes in the editor. That is, the light is blocked on all scenes. It seems to be only the case with tiles and not other occluders.

Scene1
Scene2

### Steps to reproduce

In the MRP open Scene1.tscn and Scene2.tscn. The light-blocking tiles from Scene1 also block the light in Scene2 in the editor.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/godotengine/godot/files/14716151/mrp.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
The code relies on that the deferred call is handled after the node exits the tree or canvas, this is because before the end of these notifications call both `is_inside_tree` and `is_visible_in_tree` retain the values they had before, so these changes being called immediately makes it not force cleanup properly

This feels like a pretty robust fix, and removes some unnecessary code, like the dedicated destructor flag, with the `p_force_cleanup` argument doing double duty here, I also moved the `pending_update` clearing to `_internal_update`, this avoids going through two other methods to reach the update (`update_internals` -> `_deferred_internal_update` -> `_internal_update`), while still catching any pending updates that might come after

~Edit 2: Will write up a 4.2 dedicated version as this can't be cherry-picked directly, will open a PR for that when this is approved~
Done, as the solution got a basic go-ahead and will wait on other changes in 4.3

---

* Fixes: https://github.com/godotengine/godot/issues/89769

### CODE REVIEW

**Comment by Macksaur** [comment]
I tested this on my end, looks good!

**Comment by groud** [comment]
I prefer we merge https://github.com/godotengine/godot/pull/89179 first as it's a bigger change, but that looks like a correct fix to me. We can merge this PR afterwards.

**Comment by AThousandShips** [comment]
Agreed, just wanted a confirmation that it looks right, I'll rebase this on top of #89179 and fix the differences

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
