### PR TITLE
[macOS] Avoid color flash on window resizing

### PR DESCRIPTION
**Pull request by bruvzg**
Depends on https://github.com/godotengine/godot/pull/71289

Adds macOS implementation.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by RandomShaper** [comment]
This is amazing. Gives me a great feeling of collaboration.

**Comment by akien-mga** [comment]
Now we need a hero to save poor old X11 (KDE Plasma / KWin X11, Mesa 22.3, Intel HD 630) :pleading_face: 

https://user-images.githubusercontent.com/4701338/212312956-225ebe48-48a0-4abf-8c3e-208fdb4fcddc.mp4

**Comment by RandomShaper** [comment]
I may try myself. I'm working on Godot for X11 for some other bug. No promise. 🙂

**Comment by bruvzg** [comment]
I have tried ro implement it on X11, seems like setting window background pixel fix the transparent parts on startup, but cause blinking on the resize (whole window is filled with bg color every other frame), so no idea how to do it properly.

**Pull request merged**
