### PR TITLE
Use a Big Sur-style macOS icon for the Godot editor

### LINKED ISSUE #1616: Big Sur compatible new macOS app icon proposal
**Describe the project you are working on:**
Big Sur compatible new macOS app icon,

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Big Sur compatible new macOS app icon

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
godot1
godot2

I uploaded this to https://macosicons.com/, if you search for "godot" you will see.

### PR DESCRIPTION
**Pull request by Calinou**
This provides a more coherent visual look with the rest of macOS.

This closes https://github.com/godotengine/godot-proposals/issues/1616.

Thanks @hazarek for providing the icon :slightly_smiling_face:

## Preview

I don't have a macOS setup at hand right now, so here's Gwenview rendering it for now:

image

### CODE REVIEW

**Comment by bruvzg** [comment]
Icon is overeiden during startup. Changing one in the bundle template won't fully change app icon, see #48685 for the relevant code (disables icon override), or the same code can be changed to use macOS specific icon.

**Comment by Calinou** [comment]
It works successfully following the merge of https://github.com/godotengine/godot/pull/48685:

image

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
