### PR TITLE
Add character selection to font importer

### PR DESCRIPTION
**Pull request by masoudbh3**
pic

### CODE REVIEW

**Comment by reduz** [comment]
A few questions..

1) I can imagine the options only appear if you select the "selection option"
2) Please use "Custom Blocks" instead of "Selection", as "Blocks" is the name Unicode gives to those
3) Arent there like, dozens of blocks? are all of them there? :|

**Comment by masoudbh3** [comment]
1) yes.
2) no it's not Unicode block. Unicode blocks are big. i separate Latin & Latin number glyphs and in the same way for Arabic and Persian glyphs and in below can add custom glyphs from text file.
i don't know Hebrew , Japanese or Chinese glyphs for add in this Selection list.

**Comment by reduz** [comment]
ah right what happened with the custom option?

**Comment by masoudbh3** [comment]
custom option there in selection mode.
for example you can select Latin glyphs and custom glyphs.

**Comment by akien-mga** [comment]
This PR now has merge conflicts to resolve (likely due to removing trailing spaces everywhere in the code). Is it still relevant now that we have TTF support? (I guess, for games that would like to use a lightweight font for some languages only?)

**Comment by akien-mga** [comment]
No answer and no external feedback from interested users, so closing as old. Feel free to cherry-pick and rebase the commit and make a new PR if it's still a wanted feature.

**Pull request closed without merging**
