### PR TITLE
Rename OmniLight3D to PointLight3D

### PR DESCRIPTION
**Pull request by AaronRecord**
This makes it more consistent with Blender, Unity, Unreal, etc.

See https://github.com/godotengine/godot/issues/16863#issuecomment-869587241
And https://github.com/godotengine/godot/pull/50067

### CODE REVIEW

**Comment by LightningAA** [comment]
Rebased

**Comment by fire** [comment]
While I collect approvals, the pr awaiting rebase.

**Comment by reduz** [comment]
I reject, OmniLight3D and PointLight2D work different, it would be confusing to have them named the same. OmniLight3D also can have a size, so its not a point either.

**Comment by fire** [comment]
Renaming OmniLight3D to PointLight3D was discussed with other contributors and the consensus was to take no action.

**Pull request closed without merging**
