### PR TITLE
Check for nullptr expression in parse_precedence function

### LINKED ISSUE #53696: GDScript 2.0: Godot crashes when after typing `$=$` into a GDScript function
### Godot version

4.0 dev (16b27304d90880b0a3a6bfefbb19f2718d5919af)

### System information

OpenSuse Tumbleweed 2021-10-05

### Issue description

Godot crashes when after typing `$=$` into a function in GDScript

Backtrace:
```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (16b27304d90880b0a3a6bfefbb19f2718d5919af)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x427a0) [0x7fed287887a0] (??:0)
[2] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x13f98ed] (/~/godot/modules/gdscript/gdscript_parser.cpp:2323)
[3] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x13f3de1] (/~/godot/modules/gdscript/gdscript_parser.cpp:2007 (discriminator 4))
[4] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x1404273] (/~/godot/modules/gdscript/gdscript_parser.cpp:2030)
[5] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x1405270] (/~/godot/modules/gdscript/gdscript_parser.cpp:1373 (discriminator 6))
[6] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140accf] (/~/godot/./core/templates/cowdata.h:386)
[7] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x1414ab7] (/~/godot/modules/gdscript/gdscript_parser.cpp:704 (discriminator 4))
[8] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140cb4e] (/~/godot/./core/templates/cowdata.h:386)
[9] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140d7c5] (/~/godot/./core/templates/map.h:680)
[10] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140e213] (/~/godot/modules/gdscript/gdscript_parser.cpp:365)
[11] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x13d6d70] (/~/godot/modules/gdscript/gdscript_editor.cpp:2389)
[12] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x2057f1f] (/~/godot/./core/templates/cowdata.h:386 (discriminator 2))
[13] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x234fd36] (/~/godot/./core/templates/list.h:467)
[14] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe5d73] (/~/godot/core/object/object.cpp:1102)
[15] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe69bb] (/~/godot/core/object/object.cpp:1155)
[16] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x27a7d3e] (/~/godot/./core/variant/variant.h:261)
[17] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe5d73] (/~/godot/core/object/object.cpp:1102)
[18] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe69bb] (/~/godot/core/object/object.cpp:1155)
[19] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x2726a08] (/~/godot/./core/variant/variant.h:261)
[20] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fd7f84] (/~/godot/core/object/object.cpp:843)
[21] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x271128a] (/~/godot/scene/main/scene_tree.cpp:859)
[22] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x27129a7] (/~/godot/scene/main/scene_tree.cpp:453)
[23] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9fd027] (/~/godot/main/main.cpp:2573)
[24] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9d6611] (/~/godot/platform/linuxbsd/os_linuxbsd.cpp:342)
[25] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9c6ff5] (/~/godot/platform/linuxbsd/godot_linuxbsd.cpp:58)
[26] /lib64/libc.so.6(+0x2d540) [0x7fed28773540] (??:0)
[27] /lib64/libc.so.6(__libc_start_main+0x7c) [0x7fed287735ec] (??:0)
[28] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9d5015] (/home/abuild/rpmbuild/BUILD/glibc-2.34/csu/../sysdeps/x86_64/start.S:118)
-- END OF BACKTRACE -- 
```

### Steps to reproduce

Type `$=$` into a GDScript function.

### LINKED ISSUE #54692: Editor crash in GDScript 2.0 when accidentally adding assignment operator after node value.
### Godot version

4.0.dev (bd31af3)

### System information

Windows 10

### Issue description

If you have an onready node, and you assign a node to it with a cast, accidentally adding an assignment operator in between the node value and the cast triggers an exception that crashes the Editor.

### Steps to reproduce

1. Add a new scene with a root node and a child Node2D.
2. Add a script to the root node.
3. In the script, add the following (should compile fine):

    ```gdscript
    extends Node
    @onready var child: Node2D = $Node2D as Node2D
    ```

4. Now add an `=` character with a space after the `$Node2D`, like so:

    ```gdscript
    @onready var child: Node2D = $Node2D = as Node2D
    ```

    The static analyzer will throw an exception.

### Minimal reproduction project

_No response_

### LINKED ISSUE #54703: Crash when using invalid GDScript syntax
### Godot version

4.0.dev.custom_build.9f46ce865

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

```
extends PhysicalBone3D
func _ready() -> void:
	yield = ] in match Krokiet var [ 
```
cause  to show this crash
```
modules/gdscript/gdscript_parser.cpp:2360:30: runtime error: member access within null pointer of type 'struct ExpressionNode'
modules/gdscript/gdscript_parser.cpp:2360:30: runtime error: member access within null pointer of type 'struct Node'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (9f46ce86523e01435ad34de467de586485448278)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s(+0x30a930f0) [0x55f90eeeb0f0] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46520) [0x7fd41dfd7520] (??:0)
[3] GDScriptParser::parse_assignment(GDScriptParser::ExpressionNode*, bool) (??:0)
[4] GDScriptParser::parse_precedence(GDScriptParser::Precedence, bool, bool) (??:0)
[5] GDScriptParser::parse_expression(bool, bool) (??:0)
[6] GDScriptParser::parse_statement() (??:0)
[7] GDScriptParser::parse_suite(String const&, GDScriptParser::SuiteNode*, bool) (??:0)
[8] GDScriptParser::parse_function() (??:0)
[9] void GDScriptParser::parse_class_member<GDScriptParser::FunctionNode>(GDScriptParser::FunctionNode* (GDScriptParser::*)(), GDScriptParser::AnnotationInfo::TargetKind, String const&) (??:0)
[10] GDScriptParser::parse_class_body(bool) (??:0)
[11] GDScriptParser::parse_program() (??:0)
[12] GDScriptParser::parse(String const&, String const&, bool) (??:0)
[13] GDScript::reload(bool) (??:0)
[14] void call_with_ptr_args_ret_helper<__UnexistingClass, Error, bool, 0ul>(__UnexistingClass*, Error (__UnexistingClass::*)(bool), void const**, void*, IndexSequence<0ul>) (??:0)
[15] void call_with_ptr_args_ret<__UnexistingClass, Error, bool>(__UnexistingClass*, Error (__UnexistingClass::*)(bool), void const**, void*) (??:0)
[16] MethodBindTR<Error, bool>::ptrcall(Object*, void const**, void*) (??:0)
[17] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (??:0)
[18] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (??:0)
[19] Node::_gdvirtual__process_call(double) (??:0)
[20] Node::_notification(int) (??:0)
[21] Node::_notificationv(int, bool) (??:0)
[22] Object::notification(int, bool) (??:0)
[23] SceneTree::_notify_group_pause(StringName const&, int) (??:0)
[24] SceneTree::process(double) (??:0)
[25] Main::iteration() (??:0)
[26] OS_LinuxBSD::run() (??:0)
[27] godot4s(main+0x42c) [0x55f90eee89e5] (??:0)
[28] /lib/x86_64-linux-gnu/libc.so.6(+0x2dfd0) [0x7fd41dfbefd0] (??:0)
[29] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7fd41dfbf07d] (??:0)
[30] godot4s(_start+0x25) [0x55f90eee84f5] (??:0)

```

### Steps to reproduce

Open this script in editor

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by SaracenOne**
Closes #54703
Closes #54692
Closes #53696

### CODE REVIEW

**Comment by SaracenOne** [comment]
Updated PR, moved the nullptr check to the inside of the loop to resolve a second similar crash issue

**Comment by SaracenOne** [comment]
Added another bug fixed by this PR

**Comment by lyuma** [comment]
@vnen  This would be nice to get in for 4.0 alpha

**Review by akien-mga — APPROVED** [review]
Approving on behalf of @vnen who's having a major power outage since several days.

> [vnen] In general if those are null checks on the parser/analyzer it should be fine to merge without my review

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
