### PR TITLE
Added .cpp files for all .h files (except  for thirdparty/ and .gen.h)

### PR DESCRIPTION
**Pull request by marstaik**
I made a script to create .cpp files for all `.h` files that did not have an associated `.cpp` or `.c` files.

Doing this also caught an ancient file `audio_filter_sw.h` which is completely unused by any code in godot and has ancient code - so I deleted it.

This allows for Visual Studio (https://github.com/godotengine/godot/issues/34371) and the Compilation Databases (https://github.com/godotengine/godot/pull/32848) to find all project files correctly now.

### CODE REVIEW

**Comment by marstaik** [comment]
Binary sizes are identical (duh, no actual code changes) and Build times are identical, if not a tiny bit faster generally.

```
Before CPP real    1m40.985s
Before CPP binary  114,307 KB

After CPP real     1m38.555s
After CPP binary  114,307 KB
```

**Comment by Faless** [comment]
`modules/websocket/websocket_macros.h` only contains macros, I don't think the cpp file is needed at all there.
`packet_buffer` should likely be moved to the cpp appropriately (i.e. separating declaration and definition).

**Comment by marstaik** [comment]
> 
> 
> `modules/websocket/websocket_macros.h` only contains macros, I don't think the cpp file is needed at all there.

There is no harm for having a cpp file, even for macro only files.

> `packet_buffer` should likely be moved to the cpp appropriately (i.e. separating declaration and definition).

I think that should be done in a separate commit, as that is an issue with that particular file.

**Comment by akien-mga** [comment]
That seems overkill, I don't see why we should add empty `.cpp` files to workaround a tooling issue. We should just fix the tools to support a project that has header-only code, which is very common in any C++ project.

**Comment by marstaik** [comment]
In what way can you improve the tooling? MSVC cannot build header files (and I don't think gcc can either).

Scons definitely complains about trying to add a .h as a target:

```
scons: *** While building `['cowdata.windows.tools.64.obj']' from `['cowdata.h']': Don't know how to build from a source file with suffix `.h'.  Expected a suffix in this list: ['.c', '.C', '.cc', '.cpp', '.cxx', '.c++', '.C++', '.f', '.for', '.ftn', '.F', '.FOR', '.FTN', '.fpp', '.FPP', '.f77', '.F77', '.f90', '.F90', '.f95', '.F95', '.f03', '.F03', '.f08', '.F08', '.s', '.asm', '.ASM', '.S', '.spp', '.SPP', '.sx', '.d'].
File "C:\Projects\godot\methods.py", line 26, in add_source_files
```

Adding cpp files is most definitely not just a tooling issue as well. Compiling header files individually also has benefits. In fact, it already corrected a few issues.

Being able to build any file individually is beneficial for sanity/syntax checking.

**Comment by LikeLakers2** [comment]
I would object to this too. Having empty .cpp files just... lying in the directories, seems sort of bad for navigating the directories, as now we have all this extra space being used just to support one or two bad tools.

That said, if you *really* need an empty .cpp file next to the .h files, you should edit the SCons scripts to automatically generate those at build-time, rather than generating them prior. We already generate some header files for things such as the editor icons.

Also: A 2.5 second improvement doesn't immediately sound to me like something that including blank .CPP files would do, and honestly sounds like something that might have been caused by other conditions on your system. Could you run the test a few more times, both before and after adding the empty .CPP files? I get the feeling the times on both will average out to being about the same.

**Comment by marstaik** [comment]
> I would object to this too. Having empty .cpp files just... lying in the directories, seems sort of bad for navigating the directories, as now we have all this extra space being used just to support one or two bad tools.

I really think this point is negligible. In fact, for me it helps in consistency in the directory structure when I can see both .h and .cpp files. But that is a pure personal preference.
 
> That said, if you _really_ need an empty .cpp file next to the .h files, you should edit the SCons scripts to automatically generate those at build-time, rather than generating them prior. We already generate some header files for things such as the editor icons.

That sounds like completely unnecessary build overhead. Scons is already slow, having it ask the os to check for cpp file existence and then creating them for 140 files on every rebuild just adds bloat. And what are you going to call it? .gen.cpp ?

There is already dead time in the scons build, I would not like any more.

> Also: A 2.5 second improvement doesn't immediately sound to me like something that including blank .CPP files would do, and honestly sounds like something that might have been caused by other conditions on your system. Could you run the test a few more times, both before and after adding the empty .CPP files? I get the feeling the times on both will average out to being about the same.

I did run multiple tests. The point I was making is not that it makes the build faster, but that it does not affect the build negatively. The max delta of around 15 runs is +-2 seconds.

There is also compiler error checking to be had with the empty .cpp's not just making the tooling/ide's happy...

**Comment by neikeq** [comment]
I'm not a big fan of having these empty '.cpp' files just for the sake of it, but I wouldn't reject it only based on that considering what it fixes.
What worries me is that there may be headers that are not always included as they're not always meant to be compiled. By adding these '.cpp' files we would be compiling them everytime as Godot uses wildcards (`*.cpp`).

From what I understand, the problem is not too much about these tools not supporting headers, but SCons not generating the projects (at least for Visual Studio) with these headers included. If that's the case, maybe we could manually keep a list of header files. Although that may be easier to forget about than it is to forget adding a '.cpp'. Perhaps we could use a wildcard? I think `.vcxproj` supports this: `<Content Include="**\*.h" />`.

**Comment by Faless** [comment]
> There is no harm for having a cpp file, even for macro only files.

There is no point in having a .cpp for a macro only header.That file does not need to be build, only included.
Adding the cpp is just a waste of space and extra clutter (that is the harm).

**Comment by seebs** [comment]
I don't understand why you would *want* to "build" a header. Headers aren't there to be built, they're there to be included by other things.

C++, like C, has *never* required that there be a correspondingly-named source file for each header, and it's fairly common for projects to have headers that do not have a corresponding source file. They don't need to be "compiled", they just need to be *included* by the source files which use them.

If you have tools that are not handling this well, those tools are broken.

Can you explain what you mean by this claim:

> Compiling header files individually also has benefits. In fact, it already corrected a few issues.

I can't make sense of this.

**Pull request closed without merging**
