### PR TITLE
Fix UPNP on windows after #30205.

### LINKED ISSUE #35792: UPnP discover does not work on Windows
**Godot version:**
3.1.2 and 3.2, with and without Mono

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
UPnP discovery does not work. All I'm getting is this:
```
Socket error: bind, 10049
ERROR: get_gateway: Condition "devices.size() < 1" is true. Returned: __null
   At: modules/upnp/upnp.cpp:267
```
I talked about this with someone on Discord, and Linux version is working just fine.

**Steps to reproduce:**
1. Create new project
2. Create a scene
3. Add a root Node named "TEST" to the scene
4. Attach GDScript/C# script to the root node
5. Replace generated code with this one:
* GDScript version:
```
extends Node

func _ready():
    var upnp = UPNP.new()
    upnp.discover()
    print(upnp.get_gateway())
```
* C# version:
```
using Godot;
using System;

public class TEST : Node
{
    public override void _Ready()
    {
        var upnp = new UPNP();
        upnp.Discover();
        GD.Print(upnp.GetGateway());
    }
}
```

**Minimal reproduction project:**
See above

### PR DESCRIPTION
**Pull request by Faless**
The problem could be related to different byte ordering when copying
the interface address over the binding address.

Fixes #35792 (regression after #30205). Will report upstream.

### CODE REVIEW

**Comment by akien-mga** [comment]
You added the patch but did not apply it to our sources it seems.

**Comment by Faless** [comment]
Thanks, :eyes:

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.3.

**Comment by akien-mga** [comment]
For the reference, this has been fixed differently in #47027 (and the changes from this PR are now undone for 3.3/4.0).

**Pull request merged**
