### PR TITLE
Python header generator now generates strings with escape characters.

### PR DESCRIPTION
**Pull request by SaracenOne**
This fixes some compile errors when trying to use Visual Studio as the lexer. Even for setups where this does compile, it also seems to correct some rendering issues with people's names with unicode characters such as @zaps166's name.

### CODE REVIEW

**Comment by SaracenOne** [comment]
Actually, hold off on this commit for a moment. This hasn't yet been tested on Python 3.

**Comment by SaracenOne** [comment]
Actually, just after I committed this, another commit 158c3fbf3cf0116cdf5d7b74237db6c56db24e4f introduced changes which also broke the MSVC compile path. It's marked as such for lacking an MSVC implementation in the preprocessor #ifdef, but it is separate issue.

**Comment by SaracenOne** [comment]
Um...actually, does anyone know how to force SCons to use Python 3? I already know it works in Python 2.

**Comment by Supatier** [comment]
What OS/distro are you on?

**Comment by Supatier** [comment]
I've tested it, and there seems to be no problem....

**Pull request merged**
