### PR TITLE
Fix visual shader inputs to follow alphabetical order

### PR DESCRIPTION
**Pull request by Chaosus**
Currently, many inputs don't follow the alphabet order they intended to follow (IMO). This PR will fix it. It should not break the backward compatibility, because input node operates with the property name rather than index.

### CODE REVIEW

**Comment by QbieShay** [comment]
I'm pretty sure there's some part that refer by index, like the default connection?

**Comment by Chaosus** [comment]
Ports/connections should not been changed... I pushed this fix to 4.3 to make sure this will be well tested.

**Comment by QbieShay** [comment]
I will ask users to test!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
