### PR TITLE
Fix Updating New Node Dialog Description of Custom Nodes

### LINKED ISSUE #67535: Create New Node dialog doesn't update the description field when selecting a custom class
### Godot version

4.0beta1, 4.0beta2, 4.0beta3

### System information

Windows 10

### Issue description

In the `Create New Node` window, when we click a node, its `Description` is shown. 
The `GDScript documentation generation system` are supported after godot 4, but the `Description` of custom nodes isn't shown while we click the nodes in `Matches`: 
2022年10月17日20时15分49秒-01

BTW, if you click the nodes in `Recent` or `Favorites`, or search the custom node, the `Description` will display properly: 
2022年10月17日20时17分44秒-01

### Steps to reproduce

omitted

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Sauermann**
The text of the first column in the selection Tree is used to compare Node names.
Since this text contains for custom nodes additionally the path to the file, it doesn't match anything.

This patch separates the path and adds it as suffix.

resolve #67535

### CODE REVIEW

**Comment by Mickeon** [comment]
Could you take a screenshot to showcase how this looks with two columns?

**Comment by Sauermann** [comment]
Sure, here is a showcase

https://user-images.githubusercontent.com/6299227/196302184-a9879dc9-0b98-46ec-8e18-45ad533c0d79.mp4

**Comment by MewPurPur** [comment]
Not sure... 19yo me who doesn't know about custom nodes would think that not selecting the full row is janky UI.

Wouldn't it be simpler to make it so before searching for a description, the text is cut out when " (" is encountered?

**Comment by Sauermann** [comment]
I found a way to keep the old visuals.
The trick is to put the "(...)" not into the text, but to add it as suffix.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
