### PR TITLE
Allow AudioStreamPlayer(2D) to provide `pitch_scale` on playback

### LINKED ISSUE #53585: AudioStreamPlayer: pitch scale property does nothing
### Godot version

4.0.dev [58aa020a1]

### System information

Kubuntu 21.04

### Issue description

Pitch Scale property of AudioStreamPlayer isn't changing the pitch of the audio at all.

### Steps to reproduce

1. Create/Open a project
2. Make an AudioStreamPlayer
3. Assign any Stream and check autoplay
4. Run and listen to the sound
5. Go back and change the pitch scale
6. Run and listen to the sound, unchanged.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Fixes #53585 

AudioServer forcibly gives the stream's pitch scale a value of 1 when calling `start_playback_stream()`. These changes ensure any pitch scale from `AudioStreamPlayer` and `AudioStreamPlayer2D` are the ones provided before calling `play()`

### CODE REVIEW

**Comment by ellenhp** [comment]
Could you use this function signature instead?

https://github.com/godotengine/godot/blob/ca11f8ad3045c280b559adea4e2263c38c2c6df4/servers/audio_server.h#L373

That way this will occur atomically. With this change the AudioServer could choose to start playing audio between one line and the next which could cause pitch to change abruptly several milliseconds after playback has started. Ears are really fast so that causes audible artifacts.

**Comment by DeeJayLSP** [comment]
I have added a pitch scale parameter to the convenience method, which then provides the value to the second `start_playback_stream()`. Tested and worked fine.

**Comment by ellenhp** [comment]
Good idea. I'll take a look in a few hours. That base method has a ridiculous number of parameters and given that we need pitch scale in multiple places that's definitely the smart thing to do. 

Oct 10, 2021 1:57:37 PM Douglas Leão ***@***.***>:

**Comment by DeeJayLSP** [comment]
Convenience change: instead of providing `p_pitch_scale` as the fourth parameter on the second `start_playback_stream()` it will provide as the second, so no empty parameters need to be provided by the first one. `AudioStreamPlayer3D.cpp` changed to fit.

**Review by ellenhp — APPROVED** [review]
Looks great. Thank you so much for fixing this one! I've had a hard time finding time to work on Godot lately.

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
