### PR TITLE
8 uvs for glTF2, URI decode and Vertex Custom api

### LINKED ISSUE #2266: New UV Channel imports into a scene file
### Describe the project you are working on
3d project

### Describe the problem or limitation you are having in your project

We wanted to import more UV channels for use in Godot games.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The GLTF2 importer will use the all-new extended mesh format to store UVs.

The GLTF2 exporter will store the UV channels from the mesh into the gltf2 file.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Discussed at the rendering meeting. https://gist.github.com/fire/878b71a2b69fcb47c1c685e96163e05d

New glTF importer will have a dropdown to select the lightmap channel:

We default to texcoord1.

* None
* texcoord0
* texcoord1 
* .. 
* texcoord7

This vec2 is to be stored into custom3 (vec4) and aligned to XY because it would waste two floats if not aligned.

The layout for UV:

The glTF importer will write 

* texcoord0->uv,
* texcoord1->uv2
* texcoord2,3->custom0
* texcoord4,5->custom1
* texcoord6,7->custom2

The PackedScene to glTF2 exporter will write:

* uv->texcoord0
* uv2->texcoord1
* custom0->texcoord2,3
* custom1->texcoord4,5
* custom2->texcoord6,7

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Adding new UV channels is not a script change. It is a gltf2 importer change.

### Is there a reason why this should be core and not an add-on in the asset library?

Importing UV channels is a core change. It is unable to be integrated with the scene importer/exporters and still be a script.

### LINKED ISSUE #44552: Support multi uv channels in gltf2.
**Godot version:**
c2e0c6cc2282669017707596c810cde996414131 fork. should test on master.

**OS/device including version:**
win10. Nvidia. Vulkan

**Issue description:**
Fails on multi uv test case.

https://github.com/godotengine/godot/pull/44319 supports four custom uv channels.

See https://github.com/godotengine/godot-proposals/issues/2192

**Steps to reproduce:**
Load MultiUVTest

**Minimal reproduction project:**

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MultiUVTest

Multiuvs

image

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/44552
Fixes: https://github.com/godotengine/godot-proposals/issues/2266

Based upon the work of thenegativehunter2.

Use https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MultiUVTest to test.

Use for import tests:
[gltf_test_8_uvs.zip](https://github.com/V-Sekai/godot/files/7131982/gltf_test_8_uvs.zip)

Use for export tests:

https://github.com/thenegativehunter2/godot_custom_vertex_attribute_demo/blob/master/assets/meshes/DualSurfaceMesh.mesh:

[gltf_uvbug01glb.zip](https://github.com/V-Sekai/godot/files/7132079/gltf_uvbug01glb.zip)

### CODE REVIEW

**Comment by fire** [comment]
Current status:

1. exporting a godot scene to gltf2 seems to export texcoord0 to texcoord7
2. Import gltf2 with texcoord0 to texcoord7 doesn't seem to work

**Comment by lyuma** [comment]
Updated the review with support for float based custom formats in SurfaceTool, EditorSceneImporterMesh and GLTFDocument.

Future work: support importing uvs to half-based or unorm-based CUSTOM* channels; support half and unorm/snorm types in SurfaceTool::create_vertex_array_from_triangle_arrays and support exporting half and unorm/snorm types to TEXCOORD_ channels in gltf.

Here's a shader program I use to test UVs. It shows 3 of the 4 channels based on screen quadrant:
UV/UV2 in left 25%, CUSTOM0 in 25%-50%, CUSTOM1 in 50%-75% and CUSTOM2 in 75%-100%

[test_8_uvs.gdshader](https://github.com/godotengine/godot/files/7133389/test_8_uvs.gdshader.txt)

**Comment by fire** [comment]
Demo Project and video.


https://user-images.githubusercontent.com/32321/132632190-366120f9-04ab-49f5-9e54-835e53747ed0.mp4

[multi_uv_set_test.zip](https://github.com/godotengine/godot/files/7133860/multi_uv_set_test.zip)

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Looks good to me, will merge later today or tomorrow if no one else objects.

**Comment by peteski** [comment]
Hi! Just wondering, are any of these channels available in the MeshDataTool? It looks like you can only get to UV and UV2 at the moment but it would be really handy to get all of the available data.

**Comment by fire** [comment]
I think it should be, but we're looking for noise to direct our limited attention.

See priorities page.

**Comment by peteski** [comment]
Hey that's good to know :) I have a little workaround but it would be really handy. Is this the priorities page? - https://godotengine.org/priorities/ ?

**Pull request merged**
