### PR TITLE
Script editor: Don't open dominant script in external editor

### LINKED ISSUE #13429: External script editor gets focused after changing scenes or selecting any C# script in the Inspector
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot v3.0.beta.build1.mono
Windows 10
Single UltraWide Monitor 2560x1080.
GTX 780, 16 gb ram.

**Issue description:**
Visual studio code is sent to the front of the screen everytime any script.cs is on the Inspector tab

**Steps to reproduce:**
- Create new Project
- Create Any Node
- Attach new C# script ( Visual Studio Code opens here, if not, select visual studio code as current Editor )
- Go back to godot editor
- Press inspector arrows to select the node, then select the script.
- At this moment Visual Studio Code should be on your screen ( not sure if this will work with multiple monitors ) 

If this is working as intended, its somewhat annoying, making this toggleable in the settings would be very much appreciated.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #13429.

### CODE REVIEW

**Comment by neikeq** [comment]
Hmm, this probably won't work with the ScriptLanguage external editor API which is what C# uses: https://github.com/godotengine/godot/blob/master/core/script_language.h#L316-L317
Should work with something like:
```cpp
const bool use_external_editor =
        EditorSettings::get_singleton()->get("text_editor/external/use_external_editor") &&
        script->get_language()->overrides_external_editor();
```

**Comment by akien-mga** [comment]
Shouldn't this be `||`?

**Comment by neikeq** [comment]
Yes :sweat_smile:

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
