### PR TITLE
Select non-perfect matches if necessary in the Search Help dialog

### PR DESCRIPTION
**Pull request by YeldhamDev**
This makes the Search Help dialog imitate the behavior of the Create dialog, as in, if no perfect match is found, select the item that is the closest one.

Peek 2021-03-27 21-58

### CODE REVIEW

**Comment by KoBeWi** [comment]
Would it be difficult to consider case match for score if `SEARCH_CASE_SENSITIVE` is active? Otherwise it has little use.

**Comment by YeldhamDev** [comment]
> Would it be difficult to consider case match for score if `SEARCH_CASE_SENSITIVE` is active? Otherwise it has little use.
This doesn't apply here, since if something doesn't exactly match the case while case sensitive mode is enabled, it doesn't appear at all.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
