### PR TITLE
support gamepad remapping on android

### LINKED ISSUE #1839: get_joy_name no implementation on Android
The get_joy_name inmplementation on android is not proper. I would love to see it working. It would make controllers mappings much easier.

### PR DESCRIPTION
**Pull request by 27thLiz**
Also fixes #1839

I could only test this with one gamepad, as that's the only one recognized by my phone (ps4 pad, sony z2/android 5.1.1).
So some further testing would be appreciated.
I think it should be good to go if the following conditions are met:
- Works on Android < 4.0
- Actual sdl mappings work. Right now the only one we have is for the nvidia shield, so it would be cool if someone can check that thing.

APKs for testing (arm only):
[joystick-demo.apk.zip](https://github.com/godotengine/godot/files/102170/joystick-demo.apk.zip)
[joystick-mapping.apk.zip](https://github.com/godotengine/godot/files/102169/joystick-mapping.apk.zip)

### CODE REVIEW

**Comment by punto-** [comment]
Last time I tested the joystick on android, the nvidia shield matched the
"default" layout provided by the android api, isn't that the case? Same
with the joystick that samsung ships with the gear vr

**Comment by Hinsbart** [comment]
Ok, right. That should be the case.

**Comment by punto-** [comment]
But the thing is that default mapping was remapped to godot events directly
by the code that deals with the joystick, because I assumed the api would
be consistent across devices.. Is that what changed? Should be use a
"default layout" for all devices that don't have a mapping on android?

**Comment by Hinsbart** [comment]
Yes, we now map the recieved keycodes to the indices sdl uses instead of ours.
And the "default layout" thing is exactly what I did, good to hear you had the same thought.
This default mapping is also responsible for the various added `#ifdef`s in InputDefault :P

So yeah, in theory this should work nicely without any visible difference to the user.
But as I said I couldn't really test it extensively, so I just wanted to make sure... idk, I've seen a lot of strange things when working on all this gamepad stuff ^^

**Comment by punto-** [comment]
Can you add something to let the OS specify an optional fallback mapping
for unrecognized devices? like, "map all unkown devices with using mapping
for uuid X". That would be better than having ifdefs, and I think it would
be useful for other platforms.. Ideally we would have no platform specific
code there.

**Comment by Hinsbart** [comment]
Ok, done :)

**Comment by punto-** [comment]
I think it would be better if you pass the UUID to the function
set_fallback_mapping, instead of the full mapping string. The mapping
string can be loaded previously, and you don't need to run that code that
swaps the previous mapping with the new one (which could catch a device
that's actually assigned to that mapping because it was recognized with
that uuid). When an event comes in, if the mapping for the device is -1 and
there's a fallback, use that to lookup the event.

**Comment by punto-** [comment]
the actual mapping can be added on input_main.cpp like all the others (and
some day we should probably move those to each OS, so we don't have
platform specific stuff outside of platform/ )

**Comment by akien-mga** [comment]
I think it should be mergeable now @punto-?

**Comment by punto-** [comment]
yeah, looks good, thanks :)

**Comment by Hinsbart** [comment]
right after rc1, I'm a bit scared now ^^

**Comment by punto-** [comment]
it was merged before rc1, it should be live now.. I don't know how many
people use pads on android tho :p

**Pull request merged**
