### PR TITLE
Make FileDialog directory selection less misleading

### LINKED ISSUE #5989: FileDialog directory selection is misleading
**Operating system or device - Godot version:**
Mageia 6 x64, Godot 2.1 RC1

**Issue description** (what happened, and what was expected):
The way FileDialog wants users to select folders is relatively misleading. A good example is the FileDialog used when clicking on "Scan" in the project manager.

- First situation: Folder selected, but current folder is its parent
spectacle lh1262
If I click "Open", the contents of the `kobuge` folder will be scanned, and not that of the `juck` folder, even though one could expect that when clicking "Open" after having selected the target folder.

- Second situation: What the FileDialog expects is that the user opens the folder first in the FileDialog, before clicking "Open". This leads to this situation:
spectacle tq1262
Here clicking "Open" will properly scan the contents of the `juck` folder, even though the selected entry is `..`, i.e. its parent folder.

It would make more sense IMO that clicking "Open" opens the selected folder instead of the currently browsed one; if no folder is selected (e.g. if it's a file that is selected when a folder is expected, or maybe (to be discussed) if the `..` entry is selected), the current behaviour (opening the cwd) could be used.

### PR DESCRIPTION
**Pull request by TheKK**
This should fix #5989.

Changes which applied to FileDialog and EditorFileDialog are basically the same:
- show `.(current working directory)` in Tree/ItemList
- append name of selected item with current directory when under MODE_OPEN_DIR

Here's some screenshots:

Please let me know if there's anything could be improved and make thing works better!

### CODE REVIEW

**Comment by akien-mga** [comment]
This looks good to me, though maybe `../` should be hidden when in `res://` ? As it wouldn't work AFAIK.

**Comment by TheKK** [comment]
Oh, I didn't notice that. I'll find a way to prevent this case.

**Comment by reduz** [comment]
Does it make sense to show this in EditorFileDialog? There is an up arrow

**Comment by TheKK** [comment]
@reduz
If you mean the `.. (previous directory)` in the list, then I'm afraid I can't answer that for you. The changes I made here is only showing `. (current working directory)` since we want to select it. 

@akien-mga
hmm, I just find out that `..` was always there. I think we can create a new issue for it if you wish.

**Comment by hubbyist** [comment]
Showing upper directory as `..` is a good way of showing there exists an upper directory clearly IMO, but when you reach to a top level like res:// and still there is a `..` this will make showing `..` pointless and confusing.

For showing `.` seeing the contents of the folder may help if folders are named by numbers or unrecognizable sequence. This will save a click per operation.

**Comment by TheKK** [comment]
BTW, I'm not sure which code style/format should I follow. Is there project standard or guideline talks about them? If so, I'll be glad to read it through and apply them to this PR :)

**Comment by akien-mga** [comment]
@TheKK There is no standard yet but we want to write one (#3916). But the informal standard is that your code should be similar to existing code, so tab indentation is the main point.

**Pull request merged**
