### PR TITLE
[mono] handle marshalling of nullable types

### PR DESCRIPTION
**Pull request by paulloz**
Hey 🙂 

At the moment, the following code will throw a marshalling error because of `Vector2?`. This PR makes sure the marshaller actually uses the underlying type instead of the nullable generics instance.
```csharp
public class Foo
{
    public void SomeMethod(Vector2? vector)
    {
    }

    public override void _Ready()
    {
        CallDeferred("SomeMethod", new object[] { new Vector2(1f, 1f); });
    }
}
```

I'm not a big fan of the recursive call to `variant_to_mono_object` because `variant_to_mono_object_of_genericinst` could also be called from `variant_to_managed_unboxed` 🤔 but that last function has been introduced in Godot 4, and I'm not 100% sure about how to handle this situation. Please feel free to chime in on that.

I can make another PR for 3.2 if that's needed (this one probably can't be cherry-picked directly).

### CODE REVIEW

**Review by neikeq — CHANGES_REQUESTED** [review]
Current code looks good, but this also needs to be added to `managed_to_variant_type`:
https://github.com/godotengine/godot/blob/3d7ce1c529a3c7b145181f73ee1fb0b5609aa691/modules/mono/mono_gd/gd_mono_marshal.cpp#L237

`GDMonoField` uses `GDMonoMarshal::variant_to_mono_object_of_genericinst` so there's no need to add it there:
https://github.com/godotengine/godot/blob/1e59443cd242cae1ba556803a258a30b29a2b407/modules/mono/mono_gd/gd_mono_field.cpp#L278

**Comment by paulloz** [comment]
> Current code looks good, but this also needs to be added to `managed_to_variant_type`:

I wasn't sure it was necessary, I'll update that tomorrow. Could you point out quickly what `r_nil_is_variant` is about in `managed_to_variant_type`? Is it to distinguish between an actual `Variant::NIL` and an unknown type?

**Comment by neikeq** [comment]
Ignore `r_nil_is_variant`. It's only for when the type is `object` (could store anything).

Regarding `managed_to_variant_type`, I don't know what `Variant::Type` it should return. I think if it's `Variant::VECTOR2` for a `Vector2?` then it won't allow assigning null in the Godot Inspector, and not sure what value it would display if it's already null.

Also, my apologies because I forgot another method you should implement this in, which is  `mono_object_to_variant_impl`:
https://github.com/godotengine/godot/blob/7739db379944d7479c5ea2ebad9a78e3bf33fc6f/modules/mono/mono_gd/gd_mono_marshal.cpp#L1176

**Comment by paulloz** [comment]
I'm switching this PR to draft because I'm hitting some difficulties with exported fields/values. It may be a little more work than anticipated.

**Comment by paulloz** [comment]
Quick heads-up.  

> Regarding managed_to_variant_type, I don't know what Variant::Type it should return. I think if it's Variant::VECTOR2 for a Vector2? then it won't allow assigning null in the Godot Inspector, and not sure what value it would display if it's already null.

I've been wondering about this too. For me the #1 use cases wouldn't be to have full editor support for nullable fields though, but to be able to use nullable types in callbacks, signal parameters, etc. I'm afraid there's no way currently to have e.g. a Vector2 exported and not assigning it a value. FWIW if the currently assigned value is `null`, it'll show as a `Vector2.Zero`.

> Also, my apologies because I forgot another method you should implement this in, which is `mono_object_to_variant_impl`:
> 
> https://github.com/godotengine/godot/blob/7739db379944d7479c5ea2ebad9a78e3bf33fc6f/modules/mono/mono_gd/gd_mono_marshal.cpp#L1176

I'm not sure this is necessary, while testing I haven't been in any situation where the code actually run through this case. I suppose it's because boxing occurs on the underlying object and not the nullable itself ([source](http://docs.go-mono.com/?link=T:System.Nullable))?  

I'm still facing a wall with some types of exported properties and I can't really wrap my head around the issue.  
Considering the following node.  
```csharp
public partial class Test : Node2D
{
    [Export] Vector2? TestVector = null;
    [Export] int? TestInt = 90;
    [Export] Godot.Texture2D? TestTexture;
    [Export] String? TestString = "Some default string";

    private void Print()
    {
        GD.Print($"Vector2: {TestVector}");
        GD.Print($"Int: {TestInt}");
        GD.Print($"String: {TestString}");
        GD.Print($"Texture: {TestTexture}");
        if (TestTexture != null) {
            GD.Print($"size({TestTexture.GetWidth()}, {TestTexture.GetHeight()})");
        }
    }
}
```
image

Calling `Print` will produce the following values. The `String` and `Texture2D` ones are OK but the `Vector2` and `int` ones seem to just contain random data.
```
Vector2: (0, -2,161859E-26)
Int: 0
String: Hello world :)
Texture: [StreamTexture2D:-9223372009759570994]
size(64, 64)
```
I imagine there's a difference between handling value types that I don't fully get. I'll keep digging around but if you spot something obvious that I'm missing here, do tell me 🙂

**Comment by neikeq** [comment]
> > Also, my apologies because I forgot another method you should implement this in, which is `mono_object_to_variant_impl`:
> > https://github.com/godotengine/godot/blob/7739db379944d7479c5ea2ebad9a78e3bf33fc6f/modules/mono/mono_gd/gd_mono_marshal.cpp#L1176
> 
> I'm not sure this is necessary, while testing I haven't been in any situation where the code actually run through this case. I suppose it's because boxing occurs on the underlying object and not the nullable itself ([source](http://docs.go-mono.com/?link=T:System.Nullable))?

This will be called when passing a nullable as a parameter that expects Variant. The parameter in C# is of type `object`. There may also be other cases where it's called.

> I'm still facing a wall with some types of exported properties and I can't really wrap my head around the issue.
> Considering the following node.
> 
> ```cs
> public partial class Test : Node2D
> {
>     [Export] Vector2? TestVector = null;
>     [Export] int? TestInt = 90;
>     [Export] Godot.Texture2D? TestTexture;
>     [Export] String? TestString = "Some default string";
> 
>     private void Print()
>     {
>         GD.Print($"Vector2: {TestVector}");
>         GD.Print($"Int: {TestInt}");
>         GD.Print($"String: {TestString}");
>         GD.Print($"Texture: {TestTexture}");
>         if (TestTexture != null) {
>             GD.Print($"size({TestTexture.GetWidth()}, {TestTexture.GetHeight()})");
>         }
>     }
> }
> ```
> 
> image
> 
> Calling `Print` will produce the following values. The `String` and `Texture2D` ones are OK but the `Vector2` and `int` ones seem to just contain random data.
> 
> ```
> Vector2: (0, -2,161859E-26)
> Int: 0
> String: Hello world :)
> Texture: [StreamTexture2D:-9223372009759570994]
> size(64, 64)
> ```
> 
> I imagine there's a difference between handling value types that I don't fully get. I'll keep digging around but if you spot something obvious that I'm missing here, do tell me slightly_smiling_face

I suppose you're compiling with nullable references enabled, hence why `Texture2D?` and `String?` are allowed. When compiled those fields are just `Texture2D` and `String` with a `Nullable` attribute.
For the value types, the best is probably to place a breakpoint in this method (it's called when Godot assigns values to a property of the script instance):
https://github.com/godotengine/godot/blob/master/modules/mono/csharp_script.cpp#L1599

**Comment by paulloz** [comment]
Closing for now. This is completely stale, and I don't really see any good solution to what is blocking me.

**Pull request closed without merging**
