### PR TITLE
Highlight all occurrences of selected word

### PR DESCRIPTION
**Pull request by Paulb23**
Added a configurable option that highlights all occurrences of the selected word within the current file in the text editor.

### CODE REVIEW

**Comment by neikeq** [comment]
@akien-mga Code looks good.

**Comment by akien-mga** [comment]
Looks fine indeed, nice feature :)

**Comment by lorenzobeccaro** [comment]
Very nice feature but this behaviour is expected?
github_test

**Comment by akien-mga** [comment]
It seems to look good to me, highlight would be for word matches while underlined would be for substring matches in bigger word (though I would expect ``dock`` used as an argument on lines 11 and 16 to be highlighted too).

**Comment by neikeq** [comment]
@akien-mga weird thing is that I only see one rect being added in the diff and it highlights all the word: https://github.com/godotengine/godot/pull/4076/commits/b0488cacf27cb98c4a0dd58661c83262236e18a0#diff-71709879dd36a28d4ff43c570b3b4c8bR823

**Comment by akien-mga** [comment]
That's right :D Quite peculiar hehe.

**Comment by akien-mga** [comment]
Oh now I understand what @lorenzobeccaro meant. He underlined himself the words that should have been in his opinion highlighted, but are not.

**Comment by Paulb23** [comment]
Yeah, it's not meant to highlight the substrings, but I don't see why it's not highlighting the arguments, i'll take a look into it.

**Comment by neikeq** [comment]
I noticed this bug only happens if there is one or more substring in the same line before the word that fails to be highlighted:

``` GDScript
dock # dock is selected
fun _docks(dock) # fails to highlight the parameter dock
fun _hello_there(dock)_docks # successfully highlights the parameter dock
```
I also noticed that it will only highlight the occurrences when selecting with double click. Selecting with mouse drag or shift won't work. Is that the intended behaviour?

**Comment by neikeq** [comment]
The cause seems to be that **findn** [won't be called twice](https://github.com/godotengine/godot/pull/4076/commits/b0488cacf27cb98c4a0dd58661c83262236e18a0#diff-71709879dd36a28d4ff43c570b3b4c8bR3226) if the word found in the line is a substring, when calling `_get_column_pos_of_word` [before iterating through the line columns](https://github.com/godotengine/godot/pull/4076/commits/b0488cacf27cb98c4a0dd58661c83262236e18a0#diff-71709879dd36a28d4ff43c570b3b4c8bR671).

**Comment by Paulb23** [comment]
I noticed that too, have to add some kind of loop to check until we get no matches. Just checked how sublime text handles mouse drag or shift, seem like it should be added.  Just fixed it [here](https://github.com/Paulb23/godot/commit/4cc3fbeaffcffe5fe834b2b2afda18661836f769 )

**Comment by Paulb23** [comment]
I'll try to fix the other issue then i'll send in a pull request.

**Comment by Paulb23** [comment]
I guess the other way would be to check the line for check the line for the word every loop, though that seems wasteful.

**Comment by neikeq** [comment]
Try this. I can't test it right now, but it should loop until it finds the correct word or until it reaches the end of the line:

``` C++

int TextEdit::_get_column_pos_of_word(const String &p_key, const String &p_search, int p_from_column) {
	int col = -1;

	if (p_key.length() > 0 && p_search.length() > 0) {
		if (p_from_column < 0 || p_from_column > p_search.length()) {
			p_from_column = 0;
		}

		while (col==-1 && p_from_column<=p_search.length()) {
			// match case
			col = p_search.findn(p_key, p_from_column);

			// whole words only
			if (col != -1) {
				p_from_column=col;

				if (col > 0 && _is_text_char(p_search[col-1])) {
					col = -1;
				} else if (_is_text_char(p_search[col+p_key.length()])) {
					col = -1;
				}
			}

			p_from_column+=1;
		}
	}
	return col;
}
```

**Comment by Paulb23** [comment]
That seems to have done the trick. Thanks :) i'll send in the pull request.

**Pull request merged**
