### PR TITLE
Add missing N.L factor to Burley's contribution to radiance.

### PR DESCRIPTION
**Pull request by ghost**
The thing that gets add to light_amount variable is f(L,V,N) (N.V), which is (normalized) BRDF multiplied by (N.V), which, after multiplying with incoming irradiance gives the radiance per solid angle.

Some of the variables here and there probably needs a rename to avoid such confusions...

We should probably take the N.V factor out of light_amount, rename it to diffuse_brdf, and multiply it by N.V at the end when calculating the radiance to be added to diffuse light to avoid any mistakes in the future.

Non-physical ones which can't be written in terms of a BRDF (meaning those which don't contribute to radiance in the form f(L,V,N) L_i (L) (N.V) dΩ, such as toon) can be added to diffuse light directly

### CODE REVIEW

**Comment by tagcup** [comment]
@reduz Since we're at it, any chance we can get #11694 merged too? ;)

I accidentally added a diffuse_color factor to Oren-Nayar BRDF a few days ago (because I was again confused by the naming light_amount) and that fixes it too

**Comment by reduz** [comment]
This is what I meant with Burley diffuse not making that much sense to me. I just merged this PR, but the whole lighting is darker, which i guess is to be expected by multiplying by NoL:

image

**Comment by reduz** [comment]
All implementations I found add that back-lighting, which screws up shadow mapping. I dont know if it's intended in the original paper. Multiplying by NoL will get rid of it, but it makes sense that things will become darker... so I honestly don't know how it's supposed to be used. This is why I think it must only make sense in path tracers..

**Comment by tagcup** [comment]
Lambert should actually be darker, it's π times brighter than it should be

**Comment by tagcup** [comment]
Ah no, N.L is there for all BRDFs. It's also there in Burley's notes, in the sense that he just gives f, which you just plug into the reflection equation which contains the N.L factor.

I mean Burley itself doesn't contain any N.L factors, it comes from the reflection equation

**Comment by tagcup** [comment]
You can see Eq. (1) [here](http://blog.selfshadow.com/publications/s2012-shading-course/hoffman/s2012_pbs_physics_math_notebook.pdf) which contains the N.L factor, and [Burley's notes](http://blog.selfshadow.com/publications/s2012-shading-course/burley/s2012_pbs_disney_brdf_notes_v3.pdf) just gives the f to be plugged into that

**Comment by reduz** [comment]
So then, it makes sense that it's darker just as is? I wonder what does Substance Painter use by default..

**Comment by tagcup** [comment]
BTW, for Lambert, f = 1/π

**Comment by tagcup** [comment]
Ah yeah, I think it looks dark because actually Lambert it too bright, because it's not normalized (for which I have #11694 ;))

**Comment by tagcup** [comment]
Yeah, I want to check substance painter's shader code in general, for D and G functions too and compare the approximate models we use against them...

**Pull request merged**
