### PR TITLE
Make EditorToaster's handler thread-safe

### PR DESCRIPTION
**Pull request by RandomShaper**
Might help with #55619.

Needs #71644. **UPDATE:** Needs #75994 for 4.0.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Rebased on top of 4.1.

**Review by akien-mga — APPROVED** [review]
Looks good to me. Needs a rebase.

**Comment by RandomShaper** [comment]
Rebased!

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Comment by YuriSizov** [comment]
Cherry-pick reverted and removed from 4.0.3.

**Pull request merged**
