### PR TITLE
[3.x] Rationalize property reversion

### PR DESCRIPTION
**Pull request by RandomShaper**
Version of #46270 + #51173 + #51180 for 3.x.

### CODE REVIEW

**Comment by RandomShaper** [comment]
In the cherry-picked commit from 4.0, I've replaced the cases of `#warning` with `WARN_PRINT_ONCE`, to avoid errors in the CI. Moreover, given that they are about not-yet-implemented stuff, merging this PR would require tracking the progress of it in 4.0, to backport the missing pieces when they are available.

**Comment by akien-mga** [comment]
> In the cherry-picked commit from 4.0, I've replaced the cases of `#warning` with `WARN_PRINT_ONCE`, to avoid errors in the CI. Moreover, given that they are about not-yet-implemented stuff, merging this PR would require tracking the progress of it in 4.0, to backport the missing pieces when they are available.

This needs to be implemented in this PR to be mergeable IMO. We used `#warning` in `master` for things that couldn't reasonably be implemented at the same time as the main feature that caused the need to implement them. But there's a big difference between 4.0.dev in `master` and 3.4.beta in `3.x` in terms of expectations of stability and feature completeness.

**Comment by neikeq** [comment]
I was about to comment this but the diff changed and it seems `inherits_script` is no longer a thing? Here it is any way in case it may be of some use:

I haven't tested this code nor whether this PR breaks anything for C#, but this is probably how `inherits_script` should be implemented for C#:

```cpp
bool CSharpScript::inherits_script(const Ref<Script> &p_script) const {
	if (!script_class)
		return false;
	Ref<CSharpScript> cs_script = p_script;
	if (cs_script.is_null())
		return false;
	if (!cs_script->script_class)
		return false;
	return cs_script->script_class->is_assignable_from(script_class);
}
```

**Comment by neikeq** [comment]
It seems the new `inherits_script` cannot be overridden and relies on `get_base_script`, which is also not implemented for C#. In fact `get_base_script` is much harder to implement for C#, so if C# could override `inherits_script` that would be better.

**Comment by RandomShaper** [comment]
@akien-mga, sorry for the stream of updates.

Since a showstopper for this PR was the lack of many implementations of `inherits_script()`, I've added the NativeScript one myself and cherry-picked the C# one. So, the only one missing at this point is the PluginScript one, which I don't think is a big issue. (If it is, please let me know, since I'm not very familiar with it and I may be missing some important consequences of that.)

With all the commits included here, this is fully aligned with _master_ and should be ready to merge once #51173 and #51180 are validated.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
