### PR TITLE
[TextServer] Fix `get_word_breaks` and its uses.

### LINKED ISSUE #78646: `TextServer::string_get_word_breaks()` may return wrong results for Chinese text
### Godot version

v4.1.beta.custom_build [19e7490c9]

### System information

Linux Mint 21.1 (Vera) - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 515.105.01) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 Threads)

### Issue description

For Chinese text, the array returned by `TextServer::string_get_word_breaks()` may contain elements with the value `-1`, which is incorrect. This result is used by TTS, which may cause speech stuttering.

https://github.com/godotengine/godot/blob/030c1a950e8cee19e72104b4fb79caba17a2d678/modules/text_server_adv/text_server_adv.cpp#L6515

Using `UBRK_SENTENCE` instead of `UBRK_LINE` is good for the smoothness of the speech, but I'm not sure if it has bad effects elsewhere. But at this point its name might not be appropriate. 

### Steps to reproduce

Import and open MRP, and run the project.

Output:

```output
Chinese test
天行健，君子以自强不息；地势坤，君子以厚德载物 
string_get_word_breaks:
chars_per_line = 0:  [0, 1, 0, 1, 0, 3, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, 10, 11, -1, 0, -1, 0, 14, 15, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, 22, 23] 
chars_per_line = 5:  [0, 3, 10, 15, 22, 23]

English test
Godot Engine 
string_get_word_breaks:
chars_per_line = 0:  [0, 5, 6, 12] 
chars_per_line = 5:  [0, 5, 6, 11, 11, 12]
```

`-1` should not exist in the array, and the elements of the array should be sorted from small to large.

Better output (Using `UBRK_SENTENCE` instead of `UBRK_LINE`, this is the result of the sentence break):
```
Chinese test
天行健，君子以自强不息；地势坤，君子以厚德载物 
string_get_word_breaks:
chars_per_line = 0:  [0, 3, 4, 11, 12, 15, 16, 23] 
chars_per_line = 5:  [0, 3, 4, 9, 9, 11, 12, 15, 16, 21, 21, 23]

English test
Godot Engine 
string_get_word_breaks:
chars_per_line = 0:  [0, 5, 6, 12] 
chars_per_line = 5:  [0, 5, 6, 11, 11, 12]
```

### Minimal reproduction project

[string_get_word_breaks_issue.zip](https://github.com/godotengine/godot/files/11857045/string_get_word_breaks_issue.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/78646

### CODE REVIEW

**Comment by YuriSizov** [comment]
@Rindbee Could you test these changes?

@bruvzg And could you rebase your PR so it runs fresh CI, since its been too long? 🙂

**Comment by Rindbee** [comment]
The stuttering of tts is gone. The results returned by `string_get_word_breaks` are still not particularly ideal.


English test text: "Godot Engine, the game engine you've been waiting for."
```
Before:
chars_per_line = 0:  [0, 5, 6, 12, 14, 17, 18, 22, 23, 29, 30, 33, 34, 36, 37, 41, 42, 49, 50, 54] 
chars_per_line = 5:  [0, 5, 6, 11, 11, 12, 14, 17, 18, 22, 23, 28, 28, 33, 34, 36, 37, 41, 42, 47, 47, 49, 50, 54]
After:
chars_per_line = 0:  [0, 5, 6, 12, 14, 17, 18, 22, 23, 29, 30, 33, 34, 36, 37, 41, 42, 49, 50, 53] 
chars_per_line = 5:  [0, 5, 6, 11, 11, 13, 14, 17, 18, 22, 23, 28, 28, 33, 33, 36, 37, 41, 42, 47, 47, 49, 50, 54]
```
It is worth noting that the test results for the English text changed.

Chinese test text: "天行健，君子以自强不息；地势坤，君子以厚德载物"
```
Before:
chars_per_line = 0:  [0, 1, 0, 1, 0, 3, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, 10, 11, -1, 0, -1, 0, 14, 15, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, 22, 23] 
chars_per_line = 5:  [0, 3, 10, 15, 22, 23]
After:
chars_per_line = 0:  [0, 1, 1, 2, 2, 3, 4, 6, 6, 7, 7, 9, 9, 11, 12, 14, 14, 15, 16, 18, 18, 19, 19, 21, 21, 23] 
chars_per_line = 5:  [0, 4, 4, 9, 9, 14, 14, 19, 19, 23]
```
When `chars_per_line = 0`, the breaks here seem to have no rules.
In the case of `chars_per_line = 5`, if a punctuation mark is encountered, English will still break even if it does not reach 5, but Chinese will not.

**Comment by bruvzg** [comment]
> The results returned by string_get_word_breaks are still not particularly ideal.

Not sure if I see anything wrong with it, the difference is only in presence of space, English text breaks on punctuation since it can't fit the next word and a space, so behavior is the same for both.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
