### PR TITLE
Better gamepad support

### PR DESCRIPTION
**Pull request by 27thLiz**
This is an updated and fixed up version of my original PR #2796

It should now build properly on all platforms and I also fixed most of the remaining bugs.
There's only a minor problem left, but as I [discussed](https://github.com/Hinsbart/godot/pull/8#issuecomment-165582019) with punto recently, it's not really a dealbreaker.
I'll open an issue about that, so we can figure this out.

Also, I tried to adress the problem of tabs vs spaces, and now it's certainly cleaner. The only space indentation left is in the new files, joystick & joystick_linux, and a bit of input_default... It's really tiresome to do this manually, any tips?

### CODE REVIEW

**Comment by vnen** [comment]
> It's really tiresome to do this manually, any tips?

On Linux you can use `unexpand` from `coreutils`:
`unexpand --tabs=4 --first-only joystick_linux.cpp > temp && mv temp joystick_linux.cpp`

Though you should try to change your code editor settings when working with Godot's codebase. Some editors can reformat the code, which might be helpful too.

**Comment by punto-** [comment]
Great work! thanks :D

**Comment by TheoXD** [comment]
I might be wrong, but this commit could have potentially disabled triggers on xbox controller (on windows). Gonna check soon with a version before this commit and verify.

**Comment by punto-** [comment]
The still exist, but they're mapped to buttons L2 and R2 via de SDL mapping
data.

**Comment by TheoXD** [comment]
@punto, I want to get analogue input, currently it's not possible with godot API after this commit.

**Comment by punto-** [comment]
Yeah.. we were discussing this in another issue, they'll be buttons events
and axis events, on axis 6 and 7..

**Pull request merged**
