### PR TITLE
Document default values for transition type and ease type.

### LINKED ISSUE #6567: Default easings/transitions in SceneTreeTween
**Your Godot version:**
3.5.1

**Issue description:**
It's probably obvious to most but it would be nice for the Scene Tree Tween to explicitly state default values used when you start using it with no other method calls, e.g. if you call tween_property and tween_method, is the default transition linear with ease in/out?

This would avoid people doing this on every tween creation, 'just in case'
mytween.tween_property(...).set_trans(Tween.TRANS_LINEAR).set_ease(Tween.EASE_IN_OUT)

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_scenetreetween.html

### PR DESCRIPTION
**Pull request by sarice8**
- Fixes https://github.com/godotengine/godot-docs/issues/6567

### CODE REVIEW

**Comment by sarice8** [comment]
Note, follows pattern of documentation of set_pause_mode  (except tried to avoid ambiguous meaning of default)

**Comment by Zireael07** [comment]
Add a # before the number to create an automatic GitHub link ;)

**Comment by sarice8** [comment]
Fixes issue #6567

**Comment by akien-mga** [comment]
I assume it's this one instead (godot-docs repository): https://github.com/godotengine/godot-docs/issues/6567

**Comment by sarice8** [comment]
Yes, I guess the two repositories have separate issue databases :)

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
