### PR TITLE
Add mention of AudioListener2D in AudioStreamPlayer2D class reference

### PR DESCRIPTION
**Pull request by danboo**
Add mention of AudioListener2D in in AudioStreamPlayer2D class reference, copied and modified from AudioStreamPlayer3D class reference.

Also small change to use 'an' instead of 'a' in AudioStreamPlayer3D class reference.

### CODE REVIEW

**Comment by Chaosus** [comment]
Please, squash the commits as required by our pipeline.

**Comment by danboo** [comment]
Sorry about that, I assumed that the merge to master would squash the commits. I believe it is fixed now. Thanks!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
