### PR TITLE
Make nodes with popups consider camera

### LINKED ISSUE #48016: OptionButton popup menu opening at incorrect location in combination with Camera2D and a negative x/y coordinate.
**Godot version:**
3.3 RC9

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
I've seen that when we have an OptionButton with a Camera2D as a child, and the position.x or position.y of the button is negative, the popup menu does not open directly underneath the button, but at an offset.

This also happens if we have a sub-scene with an option menu in it, and then add a Camera2D as the child of the instantiated scene.

**Steps to reproduce:**
1. Create a new project.
2. Add a Node2D as root node
3. Add an OptionButton as a child to the root
4. Add a Camera2D as a child of the OptionButton
5. Move the OptionButton to the left so that it's x coordinate is negative (or move it up so that y is negative)
6. Run the scene, then click on the option button. The popup menu appears in a wrong location.

**Minimal reproduction project:**
[test-option.zip](https://github.com/godotengine/godot/files/6334550/test-option.zip)

### PR DESCRIPTION
**Pull request by menip**
Fixes #48016.

The affected nodes I discovered: ColorPicker, MenuButton, OptionButton. 
If there are others, let me know I will update PR.

Project tested with: [FixTest.zip](https://github.com/godotengine/godot/files/6605192/FixTest.zip)

---
Pushed formatting changes to make CI happy
Pushed to update commit email

### CODE REVIEW

**Comment by pycbouh** [comment]
Just so you know, it seems that commits weren't made with an email associated with your GH account (looking at it, it's not an email at all, but `menip <@MenipTweet>`). I think that it means they won't count towards your contribution.

**Comment by menip** [comment]
> Just so you know, it seems that commits weren't made with an email associated with your GH account (looking at it, it's not an email at all, but `menip <@MenipTweet>`). I think that it means they won't count towards your contributions.

Thanks, fixed!

**Comment by KoBeWi** [comment]
Still breaks when you zoom the camera. Instead of using only origin, you should probably use the whole transform. Something like `get_viewport()->get_canvas_transform()->basis_xform(position or sth)` (or `xform_inv()`)

**Comment by menip** [comment]
Note that we don't consider rotation of ColorPicker/etc when spawning popup, and we don't update position after popup if some movement has happened.

**Comment by menip** [comment]
@KoBeWi I can deal camera zoom on popup, but I think it's a larger bug with  `Point2 Control::get_screen_position()` function, as it doesn't consider screen scale.

**Comment by menip** [comment]
I've submitted #49468, once that is merged this PR will be updated to be simpler (will only need to consider get_size()).

**Comment by menip** [comment]
`Control::get_screen_position()` was fixed in #49468, so I've updated this PR to consider parent's scaled size when spawning a child. This result in correct child placement, as can be seen with the below example.

Note that this PR does not fix negative camera zoom, nor does it change child scale.
image

**Review by KoBeWi — APPROVED** [review]
Seems ok. AFAIK other nodes just create popups at cursor position, so they are not affected by this issue.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Would need a manual backport for `3.x` as the code changed significantly.

**Pull request merged**
