### PR TITLE
Added additional constants to GDScript and Visual Script

### PR DESCRIPTION
**Pull request by DavidHusicka**
This PR does the same as https://github.com/godotengine/godot/pull/33166 but is updated and rebased against current master. This branch is ready to be merged. I will close the old merge request since this one replaces it.

Edit: Found out that CI fails. Will fix asap.

Edit: CI fixed

### CODE REVIEW

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This looks good, feel free to rebase.

**Comment by DavidHusicka** [comment]
> This looks good, feel free to rebase.

Rebased

**Comment by DavidHusicka** [comment]
I am sorry for the CI failure. I had wrong decimal precision in the documentation. Should be fixed now.

**Comment by akien-mga** [comment]
Like https://github.com/godotengine/godot/pull/48190, I'm not convinced that adding such constants at the language level is the best way to do it. It requires significant boilerplate. Why can't we add those as `@GlobalScope` constants so they're automatically available to all language bindings?

**Comment by akien-mga** [comment]
As mentioned above, I think these constants should be added to the `@GlobalScope` (or possibly to a new `Math` singleton to keep them in a place where they're easy to find and document as suggested in https://github.com/godotengine/godot-proposals/issues/2411#issuecomment-1249259766).

So I'll close this PR, but the proposal to bind such math constants is still relevant, and should likely be properly opened on https://github.com/godotengine/godot-proposals/issues to track future implementation efforts and agree on how it should be done.

**Pull request closed without merging**
