### PR TITLE
Allow tab key to be used for shortcuts

### LINKED ISSUE #8799: Tab key can't be used in editor shortcuts.
**Operating system or device - Godot version:**
Linux - Master

**Issue description:**
When pressing an Editor shortcut that involves the `Tab` key, Godot will focus the next `control` instead of activating the shortcut. Easily testable with the default "next/prev scene" shortcut.

**Steps to reproduce:**
- Have 2 or more scenes open.
- Press `ctrl + tab` or `ctrl + shift + tab`
- ...
- Don't Profit :(

### LINKED ISSUE #24064: Can't switch between tabs by Ctrl+Tab
**Godot version:** 3.0.6

**OS/device including version:** Xubuntu 18.04

**Issue description:** 

Ctrl+Tab and Ctrl+Shift+Tab doesn't work to switch between tabs. If I change keybindings and replace the Tab button to something else, it will work, but this is not a solution.

### PR DESCRIPTION
**Pull request by NilsIrl**
Fix #8799 
Fix  #24064

Allows to use `Ctrl+Tab` to switch between tabs (and `Ctrl+Shift+Tab`).

### CODE REVIEW

**Comment by NilsIrl** [comment]
A concern I have is that the code to fix this was already done in https://github.com/godotengine/godot/commit/5e361ba2ea84a3d1395b86451d5d395bb0a37bd4#diff-b0e269beca0e7df95d035998c40ecb64R2077.

Except @reduz did it only for 
* `ui_up`
* `ui_left`
* `ui_right`
* `ui_down`

and not for `ui_focus_next` and `ui_focus_prev`.

If this was just because he wasn't aware about `Ctrl+Tab` or because it was an oversight then it is fine. However if he purposely excluded `ui_focus_next` and `ui_focus_prev` for a reason then this "reason" needs to addressed.

**Comment by NilsIrl** [comment]
https://github.com/godotengine/godot/blob/cafb888361eba08297dd88b18dc71f4d418525c0/scene/main/viewport.cpp#L2287-L2289

Why is `k` created in this case?

**Comment by YeldhamDev** [comment]
>Why is `k` created in this case?

Likely to make sure that `p_event` is an `InputEventKey`. Otherwise, `k.is_valid()` returns `false`.

**Review by groud — COMMENTED** [review]
This should not prevent the user to assign *Ctrl+Tab* or *Shift+Tab* to the "ui_focus_next" or "ui_focus_prev" actions. Are you sure this is still possible with your solution ?

**Comment by NilsIrl** [comment]
> This should not prevent the user to assign _Ctrl+Tab_ or _Shift+Tab_ to the "ui_focus_next" or "ui_focus_prev" actions. Are you sure this is still possible with your solution ?

I tested it and can confirm that it doesn't change anything.

```gdscript
extends Node2D

func _process(delta):
	if Input.is_action_pressed("ui_focus_prev"):
		print("ui_focus_prev")
	if Input.is_action_pressed("ui_focus_next"):
		print("ui_focus_next")
```

and here is the output, when pressing `Ctrl+Tab` and then `Ctrl+Shift+Tab` on the `master` branch *and* `tab_key` branch(this PR):

```
ui_focus_next # Ctrl+Tab
ui_focus_next
ui_focus_next
ui_focus_next
ui_focus_next
ui_focus_next
ui_focus_next
ui_focus_prev # Ctrl+Shift+Tab
ui_focus_next
ui_focus_prev
ui_focus_next
ui_focus_prev
ui_focus_next
ui_focus_prev
ui_focus_next
ui_focus_prev
ui_focus_next
ui_focus_prev
ui_focus_next
ui_focus_prev
ui_focus_next
ui_focus_prev
ui_focus_next
ui_focus_prev
ui_focus_next
```

I pasted my testing to show that there seems to be a behaviour that can be said to be a bug. That is when `ui_focus_prev` is pressed, `ui_focus_next` is also pressed.

**Comment by groud** [comment]
In that case, I guess it's ok to merge. :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Oops, forgot to check that there was an extra merge commit :/ Well, too late. Be sure to use `git pull --rebase` when updating PRs in the future to avoid those.

**Comment by akien-mga** [comment]
Reverted for now with 3d6f991a1742d89640b4b2c104d602de00dc0741 due to a regression (#34405).

**Pull request merged**
