### PR TITLE
GDScript: Load global classes when running debug tests

### PR DESCRIPTION
**Pull request by vnen**
So when running compiler debug tests it works with dependencies within a project.

### CODE REVIEW

**Comment by dalexeev** [comment]
I tested it. This works under the following conditions:

1. It's `bin/<godot executable> --test gdscript-compiler <path/to/script.gd>` command (`test_gdscript.cpp`).
2. There is `project.godot` file.
3. There is correct `.godot/global_script_class_cache.cfg` file.

It doesn't work for regular tests (`gdscript_test_runner.cpp`). Is it intentional?

**Comment by anvilfolk** [comment]
Interesting! So this only works because it's done within the context of a project. Is there any situation in which this might be run but there is no `ProjectSettings` singleton, which might cause a crash?

I was working on something similar to try to add a unit test to #79205, but there we cannot rely on `ProjectSettings`, I believe. My attempted solution was to add global class names found in `.gd` test scripts, as well as `.notest.gd` test scripts. Unfortunately that wasn't enough to make the class loadable and I didn't investigate further.

**Comment by vnen** [comment]
> It doesn't work for regular tests `bin/<godot executable> --test` (`gdscript_test_runner.cpp`). Is it intentional?

Yes, the test runner does not use a project nor the global classes config. It generates the index on the fly from all the test files: 

https://github.com/godotengine/godot/blob/f6187014ec1d7a47b7201f64f3a8376a5da2f42d/modules/gdscript/tests/gdscript_test_runner.cpp#L321-L337

> Interesting! So this only works because it's done within the context of a project. Is there any situation in which this might be run but there is no `ProjectSettings` singleton, which might cause a crash?

I don't think there's such case. This code is really only run from one code path AFAIK.

**Review by adamscott — APPROVED** [review]
Approved. It has been tested and it works. Thanks @vnen!

**Pull request merged**
