### PR TITLE
Add LabelSettings resource for quick Label theme property override.

### PR DESCRIPTION
**Pull request by bruvzg**
~Depends on #62108~

Adds `LabelSettings` resource, to quickly override text properties of the `Label`.

Screenshot 2022-06-17 at 12 13 14

### CODE REVIEW

**Comment by AaronRecord** [comment]
How does this work with theme overrides? I thought similar functionality was already possible with https://github.com/godotengine/godot/pull/50169?

**Review by reduz — APPROVED** [review]

**Comment by bruvzg** [comment]
Rebased to match latest `Font` and `FontFile` change of #62108.

**Comment by YuriSizov** [comment]
@bruvzg Needs a rebase, and also we've decided that this shouldn't be added to Button. Otherwise, can merge!

**Comment by nathanfranke** [comment]
> Regarding better interoperability with themes, we've discussed it at length and decided that it can be solved at a later point.

When that is done, will `LabelSettings` be removed?

**Comment by YuriSizov** [comment]
> > Regarding better interoperability with themes, we've discussed it at length and decided that it can be solved at a later point.
> 
> When that is done, will `LabelSettings` be removed?

The two options mentioned in the meeting were to either extend FontVariation to include colors and what not, or to incorporate LabelSettings into the theme. In either case, I guess not removed, no.

In my own opinion, a proper solution would require some significant changes to theming, so it is unlikely we'll get there with the upcoming versions. I imagine we'd need to split theme properties into states so each state can have its own configuration of fonts and styles. Then those would probably need to be able to partially override each other (the need for this already exists for styleboxes). So for the foreseeable future we're "stuck" with LabelSettings and maybe some smaller changes to FontVariation.

**Review by YuriSizov — APPROVED** [review]
Approving to indicate the consensus of the review meeting

**Comment by nathanfranke** [comment]
> The two options mentioned in the meeting were to either extend FontVariation to include colors and what not, or to incorporate LabelSettings into the theme. In either case, I guess not removed, no.

These are all included already in theme overrides. We would only need to add a shortcut.
image

**Comment by AaronRecord** [comment]
I personally agree with @aaronfranke, to me this just feels like adding a new system that does the exact same thing as theme overrides and theme types. The only use case I see that this adds that doesn't already exist is having a resource based source for theme overrides, but that only exists for labels. Maybe theme overrides could be made into a resource? Although couldn't you already do something similar by just creating a custom scene with a label as it's only node where you set the theme override settings appropriately? The biggest issue I see with the current system is theme overrides are a little less convenient and probably less intuitive for beginners, but I think this could be solved like with what aaronfranke said. The people that are vouching for this change are a lot more experienced than I am, so maybe this is a good idea, I'm just struggling to see why this is useful.

**Comment by aaronfranke** [comment]
@AaronRecord I think you mean @nathanfranke

**Comment by YuriSizov** [comment]
@AaronRecord We've discussed this in the meeting, with the same arguments being brought up. Ultimately, this PR a) gives better usability for people who want simple things and don't want to deal with themes, and b) it supports non-themeable nodes like Label3D.

I would really want this kind of customization to be available as a part of the theme as well, as it's more convenient and more organized, but we decided to postpone resolving that part.

**Comment by nathanfranke** [comment]
FYI a) is invalid because I've already proposed an alternative.
As for b) I don't even think we should have Label3D. Rather, we should make it easier to display a UI hierarchy in 3D (e.g. viewport with a 3d billboard texture).

**Review by akien-mga — APPROVED** [review]
We discussed this again in a maintainers meeting and agreed to go with this approach for now.

As others here I'm personally not fully happy with the redundancy this introduces with Theme and theme override properties, but we agreed that solving this problem is quite complex and would require rethinking Theme in a way that's not feasible for 4.0 in a timely manner. So we go with this for now and we'll see if/how to improve things further later on.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
