### PR TITLE
Fix comment typo in `gdscript_parser.h`

### PR DESCRIPTION
**Pull request by ryanabx**
Very simple PR. Found a typo while looking through `gdscript_parser.h` today.

### CODE REVIEW

**Review by dalexeev — APPROVED** [review]
Looks good, but I'm wondering if there are spell checkers (other than codespell) that will find more typos? By the way, I remembered another typo:

https://github.com/godotengine/godot/blob/8c25a98fdf68dc388eddaefa188f3386236cdfe4/modules/gdscript/editor/gdscript_translation_parser_plugin.cpp#L43

**Comment by akien-mga** [comment]
Might be worth fixing that "GDSript" typo in this same PR indeed.

**Comment by ryanabx** [comment]
> Might be worth fixing that "GDSript" typo in this same PR indeed.

Done

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
