### PR TITLE
Fixed #42149: bug where the default C# script template would sometimes produce an invalid class name

### LINKED ISSUE #42149: Default C# script naming system can cause invalid class name
**Godot version: 3.2.3 mono stable**

**OS/device including version: Windows 10 x64**

**Issue description:**

**1)** Create a new scene by right clicking file dock & selecting `New Scene...`

**2)** In the popup for scene name, enter a name with spaces (e.g: "my scene")

**3)** Now create a new .cs script in this new scene. Use the defaults.

**4)** As the .cs file loads in editor observe red squiggly error lines as the class name is now 
`my scene : Node2D`
A class name cannot have a space.

_Maybe to resolve this the new script dialog should not allow script names with spaces by default?_

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by eddsanity**
Fixes #42149, where mono would produce invalid class names by not discarding the space's in the object's name.

I simply replace all the spaces with an underscore in the mono code responsible for producing the C# Script template.

### CODE REVIEW

**Comment by eddsanity** [comment]
The PR is failing the static check even though it was passing on my local repository. I checked to see why I failed the check and the code snippet that's failing isn't something I changed at all so I am unsure what the cause of this is (I am also somewhat new so it might be my fault and I am unaware), but I did look over at my commits and I confirmed I changed nothing about the snippet that's failing the static check.
But looking at the snippets, I am guessing my editor (vscode) changed the indentation and there are specific indentation rules? Would really appreciate someone helping out with this.

**Comment by eddsanity** [comment]
The PR is failing the static check even though I ran the `clang-format` command on my local repository. I checked to see why I failed the check and the code snippet that's failing isn't something I changed at all so I am unsure what the cause of this is (I am also somewhat new so it might be my fault and I am unaware), but I did look over at my commits and I confirmed I changed nothing about the snippet that's failing the static check. This is exactly as `clang-format -i modules/mono/csharp_script.cpp` made it. 
Can someone help with this? I am kind of lost

**Comment by akien-mga** [comment]
You're likely using `clang-format` 11 which changed the way it handles indentation for continuation lines. The CI still uses clang-format 10, so to pass the checks you should change that section manually back to how it was.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/44515.

**Pull request closed without merging**
