### PR TITLE
Sort GDNative api.json

### LINKED ISSUE #27755: Sort GDNative api.json ?
It looks like api.json isn't sorting methods and properties or maybe they are sorted on the hashing? I get pretty large diffs between versions which just seem to indicate the order in which things are added to this file has changed drastically. 

I think its worth having a closer look.

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Not 100% sure if this does the trick, it looks like its sorting the classes properly but it may need more to sort the methods and properties.

I kept running into problems with added api.json to our godot_headers repository, every time the order of things is different generating massive diffs. 

Once we're sure this does the right thing it'll fix #27755

### CODE REVIEW

**Comment by karroffel** [comment]
Seems fine, as long as generation time does not explode, but it should be fine

**Comment by BastiaanOlij** [comment]
It seems to be sorting the classes correctly but I'm not 100% sure if its sorting the rest. It's obviously sorting on whatever sort function is implemented on the type of record contained within the list so it might just be sorting on something else then name.

It generated pretty fast for me, it's not that much data to process and its something you only run once in awhile.

**Comment by BastiaanOlij** [comment]
Ok, I don't think this actually sorts but I can't really follow the logic here.
So I call the sort function on the list. Looking at list.h that ends up calling sort_custom.

Inside of sort custom it builds a list of element pointers that it can sort and then uses the AuxiliaryComparator<C> structure to define the compare function it uses.

That does a compare using the original class, so best I can tell is that it will call operator() on the class.
Now these are implemented inside of structs but they don't seem to exist on the class itself.

**Comment by BastiaanOlij** [comment]
Ok, I figured it out and everything now sorts properly as far as I can tell.
I am not 100% sure about the sort functions I've added for MethodInfo and PropertyInfo, I'm surprised they don't exist yet and maybe should move into object.h so they are more widely available.

Other then that, I'm pretty happy with this and I think it can be merged.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
