### PR TITLE
Added possibility to go back/forward script history by mouse buttons

### PR DESCRIPTION
**Pull request by Chaosus**
I think its nice QoL change for users which have mouses with additional buttons (X1, X2) :)

### CODE REVIEW

**Comment by Calinou** [comment]
Note that these shortcuts will conflict with an eventual implementation of https://github.com/godotengine/godot/issues/16554 and https://github.com/godotengine/godot/issues/26272. Still, I think having this is better than nothing :slightly_smiling_face:

**Comment by Chaosus** [comment]
> We could bind those to keys instead

Why not do both ? Unfortunately seems like editor shortcuts cannot be binded to mouse.

**Comment by Calinou** [comment]
@Chaosus I didn't realize it was possible to implement both. Sounds good to me then.

**Comment by aaronfranke** [comment]
Hopefully this is optional, I use my extra mouse buttons for push-to-talk in programs like Discord, it would be a shame if I could no longer talk while editing code in Godot. I'm assuming that "script history" means undo/redo history.

**Comment by Zylann** [comment]
I like this idea, I use the `Previous` mouse button a lot now that i discovered it does that in code editors^^
I use the `Next` mouse button for push to talk as well, so I agree it should be optional, but it's still a  really handy shortcut.

**Comment by Chaosus** [comment]
> "script history" means undo/redo history.

This means pressing these buttons 

image

> my extra mouse buttons for push-to-talk in programs like Discord

These hotkeys reacts only if the cursor within script window

**Comment by Chaosus** [comment]
Sure, I can make a setting which disabling this behavior - how to name it ?

**Comment by BeayemX** [comment]
Could this also be extended to work with the inspector history (#19772) and maybe within the file system dock?

**Comment by aaronfranke** [comment]
"Use forward and back mouse buttons" would be my suggestion. I would want such a setting to globally disable their usage, including if #16554, #19772, and/or #26272 use them.

**Comment by Chaosus** [comment]
Meh, I'm to bored to make this PR properly

**Comment by aaronfranke** [comment]
Probably worth assigning the "salvageable" tag.

**Pull request closed without merging**
