### PR TITLE
Add `popup_centered_clamped()` method to Popup

### PR DESCRIPTION
**Pull request by ghost**
`Popup::popup_centered_maxsize` takes a `Size2`/`Vector2` defining the size of the popup, and a `float` representing the ratio to clamp each dimension to, should the viewport be too small to fit it. I added this to reduce unnecessary code duplication, as there are a few editor dialogs that use the exact same logic, plus it makes it way easier to use in other dialogs (I've identified a few places that could really use it).

### CODE REVIEW

**Comment by akien-mga** [comment]
The functionality seems good, but the name is misleading IMO. `popup_centered_minsize` shows the popup with the minimal size it can have while fitting its contents. I would expect a `_maxsize` pendent to show it as big as possible, so filling the full extent of its parent node, which is not what this method does.

**Comment by akien-mga** [comment]
I'll merge #28451 once CI passes, so that's another occurrence to take into account.

As for the name, maybe `popup_centered_clamped`?

**Comment by homer666** [comment]
@akien-mga Yeah, I like that name better. I made the change.

Also, is there a specific tool used to generate docs for new methods? Or do we just add in the entries to the XML manually?

**Comment by akien-mga** [comment]
> `godot --doctool .`

**Comment by homer666** [comment]
@akien-mga Perfect. Added documentation for the method. The wording might be kind of awkward, so please review.

**Comment by akien-mga** [comment]
Thanks! Sorry for the delay.

**Pull request merged**
