### PR TITLE
Implement shader uniform groups/subgroups

### PR DESCRIPTION
**Pull request by Chaosus**
Implement uniform groups using syntax like:

```
uniform_group MyUniformGroup {
// ... uniforms
	  uniform_group MyUniformSubGroup {
	   // ... uniforms
	  };
};
```

Example screenshot:

image

Intended to close part of https://github.com/godotengine/godot-proposals/issues/4827. If this is accepted I would like to try to implement them to visual shader to close it completly but not for now.

### CODE REVIEW

**Comment by akien-mga** [comment]
I noticed that within a group the uniforms are listed alphabetically, is that intended?
In GDScript exports are listed in the order they're defined in the script, which allows to give them a meaningful order.

**Comment by Chaosus** [comment]
> I noticed that within a group the uniforms are listed alphabetically, is that intended? In GDScript exports are listed in the order they're defined in the script, which allows to give them a meaningful order.

It's not related to this PR, it's because uniforms originally placed to `HashMap`(with alphabetial sorting) instead of a `Vector`.

**Comment by Calinou** [comment]
We should probably update the shader style guide to mention recommended casing:

```c
uniform_group SomeGroup {
   // ...
}
```

Or:

```c
uniform_group some_group {
   // ...
}
```

**Comment by AaronRecord** [comment]
> We should probably update the shader style guide to mention recommended casing:
> 
> ```c
> uniform_group SomeGroup {
> 	// ...
> }
> ```
> 
> Or:
> 
> ```c
> uniform_group some_group {
> 	// ...
> }
> ```
> 
> I'd go for snake_case personally, as the editor's automatic capitalization will probably do a better job with it.

I'd prefer PascalCase as that way it doesn't look like a keyword and then the editor can just display the group name as is

**Comment by Chaosus** [comment]
@reduz Alright - I did it as you said:

image

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

We're not all convinced by the implemented syntax, and some more discussion might be warranted to see what's the best syntax for this (taking into account that shaders don't have strings), but the feature implementation itself is good.

So we'll merge this now to have the feature and we can still change the syntax before 4.0 beta if we get a better suggestion.

**Comment by akien-mga** [comment]
Thanks!

**Comment by ArseniyMirniy** [comment]
Can this be done in Visual Shaders already? (maybe I'm missing something)

**Pull request merged**
