### PR TITLE
Update AnimationNodeTransition to have the correct enabled inputs in the blend tree automatically after tweaking in the inspector

### PR DESCRIPTION
**Pull request by Huxellberger**
Update AnimationNodeTransition to have the correct enabled inputs in the blend tree automatically after tweaking in the inspector

### CODE REVIEW

**Comment by Calinou** [comment]
Does this close an already-reported issue on this tracker? If so, please edit your first post to add "This closes #xxxx" :slightly_smiling_face:

**Comment by Huxellberger** [comment]
Not sure, something I noticed when using the editor myself. I will double check.

**Comment by Huxellberger** [comment]
Can't see an issue for it logged at the moment

**Comment by aaronfranke** [comment]
@Huxellberger Is this still desired? If so, it needs to be rebased on the latest master branch.

**Pull request closed without merging**
