### PR TITLE
Allow to declare varying of more shader types to be passed from `fragment` to `light`.

### PR DESCRIPTION
**Pull request by Chaosus**
Since `fragment` -> `light` varyings internally may be of any other shader type(`bool`, `int`, `uint`, etc, except samplers of course) - I removed the restriction from varying declaration - instead, this check will occur, <b>only</b> when varying is assigned in the vertex function which makes it 'truly' varying.

image

image

### CODE REVIEW

**Comment by reduz** [comment]
I think integer types require the flat qualifier by the way

**Comment by reduz** [comment]
though i guess that can be automated in the codegen

**Comment by Chaosus** [comment]
Added a check to prevent shader crashes while declaring such varying in global space without using it in 'fragment' -> 'light' functions.

**Comment by Chaosus** [comment]
I think it's bringing up confusion to the users - I better close it for now. If there is a lot of request, I will recreate it.

**Pull request closed without merging**
