### PR TITLE
Add explicit types to `enum`s

### PR DESCRIPTION
**Pull request by Muller-Castro**
Set type for scoped, unscoped, named and unnamed enums.

~~I used the following logic:~~
~~* if the smallest value is greater than or equal to `0`, prefix the type with `u`~~
~~* if it's unsigned:~~
~~- if the largest value is greater than `65535`, type is `32`~~
~~- else if the largest value is greater than `255`, type is `16`~~
~~- else the type is `8`~~
~~* if it's signed:~~
~~- calculate `abs_largest_value = max(abs(largest_value), abs(smallest_value))`~~
~~- if `abs_largest_value ` is greater than `32767`, type is `32`~~
~~- else if `abs_largest_value ` is greater than `127`, type is `16`~~
~~- else the type is `8`~~

~~Most enums ended up as 8 bit.~~

Edit:
I used the following logic:
* all enums are signed to avoid tons of warnings
* calculate `abs_largest_value = max(abs(largest_value), abs(smallest_value))`
* if `abs_largest_value ` is greater than `int(2 ** 32 / 2) - 1`, type is `64`
* else the type is `32`

### CODE REVIEW

**Comment by AThousandShips** [comment]
This is very large, and reviewing it in detail is critical, so this should be split into dedicated parts (over 500 files, and 1500 lines is pretty unmanageable when you have to go through and ensure everything is correct)

**Comment by AThousandShips** [comment]
So we can already see some impacts, namely that typed enums are incompatible with literals in some contexts

Further, for review we need to make sure this doesn't affect binary data storage in some cases, as if you access the memory location of one of these values they might contain garbage, if, for example, it's now 8 bits and was 32 bits before (the default enum type is `int`), and the next member is not 8 bits aligned there will be a padding gap that might contain uninitialized memory, also cases with `memcpy` etc. that could cause problems

**Comment by Muller-Castro** [comment]
shouldn't this be resolved by cleaning all obj files and rebuilding the project? for the compiler to redo the alignment

**Comment by AThousandShips** [comment]
> shouldn't this be resolved by cleaning all obj files and rebuilding the project? for the compiler to redo the alignment

Not what I'm talking about, I'm talking about:
```cpp
MyEnum val;
int some_other;
```
Where the enum is 8 bits, the following 3 bytes will be possibly undefined 

But my question is: why is this change needed and what does it actually achieve

**Comment by Muller-Castro** [comment]
Oh okay, got it;

**Comment by Muller-Castro** [comment]
think that in the end this can only be useful to enhance type safety and improve code readability.

so it's better to set everything as 32 bit?

**Comment by AThousandShips** [comment]
I don't see how this improves code readability, it only tells something, marginally, if it's small, otherwise it says "okay this is larger than 16 bits but smaller than 32" which is a ridiculously big range (especially for enums that aren't flags)

**Comment by Muller-Castro** [comment]
Should I proceed this way?

> I'd say we should instead decide on a size to use, and then apply it for all cases that fit (the ones that don't will already have uint64_t I believe), as this saves little to nothing, but incurs risks (and, actually some times performance losses)

I'll set all enums to `int32_t` or `uint32_t` and fix those errors the check bots are throwing

**Comment by AThousandShips** [comment]
I'm not convinced this change is necessary, but I'd say if anything should be done that would be it

**Comment by Repiteo** [comment]
For a project like this, it's important to understand what the underlying types can potentially be for enums. The notes on the `std::underlying_type` reference page[^1] specify that scoped enums default their underlying type to `int`, but requiring manual conversion against literals makes it less relevant. Legacy enums are implementation-defined, so their underlying type can vary drastically; I imagine this behavior is so the conversion process can happen against literals "automatically". Based off the build results, making the underlying type a specific value *seems* to override that process & compares literals to that underlying type directly, making signed mismatches more likely.

This is all to say that the underlying types of enums is a whole other can of worms that probably warrants more discussion. Clearly this took a good deal of work to setup so I don't wanna discount the effort, but with ramifications and scope this large it helps to have a clear direction and endgoal from the outset.

[^1]: https://en.cppreference.com/w/cpp/types/underlying_type

**Comment by Muller-Castro** [comment]
Sorry guys, I still don't have in-depth knowledge to opine on so I'm pushing the fix suggested by @AThousandShips.

Any changes please let me know (I'm not doing it by hand so it's not taking any effort).

**Comment by AThousandShips** [comment]
I'd suggest splitting it up as suggested first, branch off to keep the rest of the changes and keep just the ones in core for example

**Comment by bruvzg** [comment]
What's the point of this? Apart from a few special cases, there are not many reasons to set enum type.

**Comment by Muller-Castro** [comment]
Closing as this will bring more problems than solutions (next time I'll open up a proposal first).

**Comment by RandomShaper** [comment]
My two cents is a codebase-wide such as this would be better scheduled for major releases. We can live with some legacy.

**Pull request closed without merging**
