### PR TITLE
Fix for #6156

### PR DESCRIPTION
**Pull request by vkbsb**
Adding enet to include paths while building the module.

### CODE REVIEW

**Comment by vkbsb** [comment]
The windows build doesn't seem to be working.. unable to fix it :(

**Comment by vnen** [comment]
This fix the builds for non-tools. Four commits for a single line change is too much though.

**Comment by akien-mga** [comment]
Indeed, would be great if you could squash the four commits together and adjust the commit log accordingly before merge.

**Comment by akien-mga** [comment]
Superseded by 2cf781d.

**Pull request closed without merging**
