### PR TITLE
Prioritize proximity to green arrow when selecting overlapping transitions in AnimationNodeStateMachine

### PR DESCRIPTION
**Pull request by vaner-org**
Addresses usability problem mentioned in [#10976](https://github.com/godotengine/godot-proposals/issues/10976).

https://github.com/user-attachments/assets/b93f7f5b-e41f-4ccd-afcd-e19f8a856197

When transition lines are overlapping, selection between them is undefined, leading to some guesswork on which transition will be selected. Using proximity to the green arrow always present at the midpoint of each line as bias makes selection much more predictable.

https://github.com/user-attachments/assets/e02c8015-5b7b-45f1-a00b-fc9d0c282e9f

This PR is a companion to https://github.com/godotengine/godot/pull/98402, which improves visibility when selecting nodes and transitions in complex `AnimationNodeStateMachine` cases.

As this is my first PR, criticism and feedback would be very much appreciated.

### CODE REVIEW

**Comment by vaner-org** [comment]
My last commit reduced the scope of this PR to just handle overlaps of <2px, so as not to overreach. I've included an animtree with some extreme case overlaps below.
I also do not have a hiDPI display and I'm unsure if that makes a difference, so some testing with one would be appreciated.
[green-arrow-test-animtree.zip](https://github.com/user-attachments/files/17515015/green-arrow-test-animtree.zip)

**Comment by Jesusemora** [comment]
this helps a lot! I hope it gets approved.
it would be even better if lines going in and lines going out were to be colored. a line going out could be green and one going in could be red, change the green triangles too.

**Review by SaracenOne — APPROVED** [review]
I think this is fine, but like the other PR, I would recommend squashing this PR into a single commit.

**Comment by vaner-org** [comment]
All done, ready for you.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
