### PR TITLE
[DOCS] SceneTree

### PR DESCRIPTION
**Pull request by mhilbrunner**

### CODE REVIEW

**Review by cbscribe — CHANGES_REQUESTED** [review]
A few small style changes

**Comment by mhilbrunner** [comment]
@cbscribe Fixed those, thanks. :)

**Comment by denisw** [comment]
The [Scripting (Continued) tutorial](https://github.com/godotengine/godot-docs/blob/aa851506462361fa49abee9979e15fb710172f8a/getting_started/step_by_step/scripting_continued.rst) still mentions that the `SceneTree` class is "incomplete". I guess this sentence can be updated now? 🙂

**Comment by aaronfranke** [comment]
What else needs to be done for this issue?

**Comment by mhilbrunner** [comment]
Pretty sure that was just a mistype and https://github.com/godotengine/godot/pull/18096 was meant instead of this issue (https://github.com/godotengine/godot/pull/18069), so 96 at the end instead of 69... because I don't see how that has anything to do with this old docs PR :)

**Comment by groud** [comment]
> What else needs to be done or reviewed for this issue?

Nothing, @mhilbrunner is right. I mistyped the PR number on my phone ^^

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Pull request merged**
