### PR TITLE
Fix GLES2 ambient light flickering with multiple refprobes

### LINKED ISSUE #36399: Limited number of Reflection Probes
Godot 3.2

verified on PC Linux and Oculus Quest

I'm using GLES2, I've set multiple reflection probes for covering the various rooms in a building, only the first two probes works.

Hide all the probes and the show them by clicking in a different sequence, only the first two you made visible will work.

[testcase_reflection_probe.zip](https://github.com/godotengine/godot/files/4233166/testcase_reflection_probe.zip)

### PR DESCRIPTION
**Pull request by clktmr**
Fixes #36399

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good, subject to CI passing!

_edit: for future reference, this PR fixes the ambient light flickering experienced by users when there are 2 or more probes in the scene and it documents the limitation that each object on receives light from the nearest 2 reflection probes_

**Comment by clayjohn** [comment]
Can you please squash your two commits into one before we merge? How to do so is described here: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
Windows build failure is unrelated to this PR (GitHub Actions availability issue).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
