### PR TITLE
Rename tabs in the project manager

### PR DESCRIPTION
**Pull request by aaronfranke**
In the Discord discussion today, it was mentioned that the Godot Asset Library is not very visible to users.

* One of the problems is that the tab in the project manager is called "Templates". People may ignore "Templates" because they don't have any templates already and they don't realize it's a tab for downloading new projects from the Godot Asset Library. This PR renames it to "Asset Library Projects", which should be more discoverable.
* Another thing is that really both tabs are about projects, it's just that the "Projects" tab is for local projects, and "Templates" is for downloading new projects to install locally. Therefore, I renamed "Projects" to "Local Projects".

Preview:

Screenshot from 2021-04-13 17-41-10

This is not super vital, but it's also a very simple change, so I marked it as cherry-pick for 3.3.

### CODE REVIEW

**Comment by Calinou** [comment]
The tab is called "Templates" because it filters assets to *only* show template projects. I think this is an important distinction to keep. The placeholder now mentions it, but I'd still name the tab to make this obvious. For instance, it could be named "Templates on Asset Library".

**Comment by aaronfranke** [comment]
@Calinou This is not the case though, it shows more than templates. You can also download demos, for example.

**Comment by Calinou** [comment]
> @Calinou This is not the case though, it shows more than templates. You can also download demos, for example.

By "templates", I meant "projects that can be installed as stand-alone". For instance, assets like editor plugins can't be installed as stand-alone projects since they don't contain a `project.godot` file.

**Comment by aaronfranke** [comment]
@Calinou I would assume this would be self-evident, but maybe it should be "Asset Library Projects" or "Projects on Asset Library".

**Comment by pycbouh** [comment]
May be worth substituting `Asset Library <x>` for `Community <x>`. Less of the mouthful.

**Comment by vrid** [comment]
How about 'Download Projects' or even just 'Download'(It's obvious that you cant start script or asset only.) as it is indicative that you can't run projects from that tab but download only. 

Asset Library in editor is Assetlib so its not consistent everywhere and 'Projects on Asset Library' is imo too long. I'd keep it simple. 

'Local Projects' seems reasonable.

**Comment by akien-mga** [comment]
> This is not super vital, but it's also a very simple change, so I marked it as cherry-pick for 3.3.

This breaks translations, so it's too late for 3.3. Can be added in 3.3.1 once translators have had time to catch up with the change.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
