### PR TITLE
Fix empty zero assigners for the variant types

### LINKED ISSUE #56223: Variables in loops are not reset between iterations
### Godot version

v4.0.dev.custom_build [b5c825af0]

### System information

Kubuntu 21.10

### Issue description

Variables declared in the body of the loop are not reset between iterations unless you explicitly initialize them (`var a = 0`). This is a regression to 3.x. Also, in the while loop, the uninitialized variable is for some reason equal to 4.

### Steps to reproduce

v3.4.1.stable.official [aa1b95889]:

```gdscript
tool
extends EditorScript

func _run() -> void:
    for _i in 5:
        var a
        print(a)
        a = 1
    
    print('---')
    
    var i = 0
    while i < 5:
        var a
        print(a)
        a = 1
        i += 1
```

```
Null
Null
Null
Null
Null
---
Null
Null
Null
Null
Null
```

v4.0.dev.custom_build [b5c825af0]:

```gdscript
@tool
extends EditorScript

func _run() -> void:
    for _i in 5:
        var a
        print(a)
        a = 1
    
    print('---')
    
    var i = 0
    while i < 5:
        var a
        print(a)
        a = 1
        i += 1
```

```
null
1
1
1
1
---
4 # ?!
1
1
1
1
```

### Minimal reproduction project

—

### PR DESCRIPTION
**Pull request by Chaosus**
Finally, closes https://github.com/godotengine/godot/issues/56223.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
By comparing with the other types, it seems to make sense. But do we have any idea why this was not done originally?

**Comment by Chaosus** [comment]
> But do we have any idea why this was not done originally?

I have no idea, probably @reduz should be asked since he wrote these strings 2 years ago.

**Comment by akien-mga** [comment]
Some comments:
```
<Akien> Do you remember why you didn't implement those back then? #70355
<reduz> Akien probably because it was meant to just initialize stuff that was needed, not everything, but it looks like the zero assigner was then used for other stuff and caused bugs
<reduz> likely due to bad naming
```

`VariantZeroAssigner<T>` seems to be only used for `VariantTypeChanger<T>::change_and_reset()`, which itself is only used in `VariantConstructNoArgs<T>`. I think initializing everything makes sense when constructing a Variant?

**Review by reduz — APPROVED** [review]
This has a bit redundancy when zero is used for the packed byte arrays, but I guess its ok as it should be not something terrible performance wise.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
