### PR TITLE
Add option to disable blending when drawing a texture rect.

### LINKED ISSUE #26603: Light2D subtractive mode not working.
**Godot version:**

b63c506

**OS/device including version:**

Win10 64-bit

**Issue description:**

The subtractive mode on Light2D seems to be broken, producing a full fill of some color.  It starts to partially work when it begins to overlap with another Light2D texture.

image

**Steps to reproduce:**
Make a Light2D and choose subtractive mode.

**Minimal reproduction project:**

[3.1 Light2D Issue.zip](https://github.com/godotengine/godot/files/2927697/3.1.Light2D.Issue.zip)

### PR DESCRIPTION
**Pull request by MadEqua**
Fixes #26603.

As discussed on the issue page this will make possible to draw the viewport on the editor without having blending active.

It adds a parameter `p_force_disable_blending` to the chain of `draw_texture_rect` and `draw_texture_rect_region` methods which will end up stored on a CanvasItem. 

Honestly I'm not a huge fan of  the solution, but couldn't think of a better way of doing it.

### CODE REVIEW

**Comment by clayjohn** [comment]
Im not certain this is the best approach. My skepticism comes from the fact that things are working perfectly fine in GLES2 without this added flag. IMO, if things are working in GLES2, we should try to mirror that behaviour in GLES3.

**Comment by MadEqua** [comment]
> Im not certain this is the best approach. My skepticism comes from the fact that things are working perfectly fine in GLES2 without this added flag. IMO, if things are working in GLES2, we should try to mirror that behaviour in GLES3.

I agree with that. In GLES2 blending is still active when rendering the viewport quad, but it seems that all the render textures are GL_RGB so there are never problems with alpha, it's just discarded.

**Comment by aaronfranke** [comment]
@MadEqua Is this still desired? If so, it needs to be rebased on the latest master branch and updated to work with Vulkan.

**Comment by MadEqua** [comment]
> 
> 
> @MadEqua Is this still desired? If so, it needs to be rebased on the latest master branch and updated to work with Vulkan.

I don't think it's worth the effort. It feels too much hackish to me, even tough it fixes the existing problem.

**Comment by akien-mga** [comment]
Closing then. This PR will still be linked in #26603 so it can be used as reference.

**Pull request closed without merging**
