### PR TITLE
Fix bug in animationplayer editor not using subproperties properly

### LINKED ISSUE #19448: AnimationPlayer - New bezier keys don't use current value for some variant types
**Godot version:**
Current master

**Issue description:**
When you add a new bezier key for a float value, it will insert the key with the current value of that float property.
However, if you add a new bezier key for a Vector2, Vector3, or I guess anything that uses a '.' at the end of the property path (i.e position.x) then the value of the key always ends up being 0

I looked into the code and it looks like it's unable to resolve the property path of properties with '.x' etc on the end, so it ends up being NIL and thus 0

**Steps to reproduce:**
Add Sprite to scene, set its position to something other than 0,0
Add Animation player
Add Bezier track for sprite's position
Add new key for x
Notice how the key value is 0, even though the sprites X position is not 0

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes  #19448.
(Pun in title not intended.)

### CODE REVIEW

**Comment by reduz** [comment]
I am not sure about this, I would go the opposite way. I know your fix it makes more sense on the technical side, but I think the way it is now is more user friendly. I would just fix the bug on insert key to get the current value instead, and left the rest of the code alone.

**Comment by bojidar-bg** [comment]
Reverted the dubious changes, hopefully didn't break anything in the process.

**Comment by dodgyville** [comment]
Hi, was any code from this checked in today? When I add a keyframe to a bezier track it asks to create a new track (instead of adding a keyframe to the existing translation track) until it crashes. Seems like a new bug that might be related to this? Thought I'd check before opening a new issue.

**Comment by akien-mga** [comment]
> Hi, was any code from this checked in today?

Yes:
screenshot_20180727_095314

**Pull request merged**
