### PR TITLE
RegEx re-implemented as a module

### PR DESCRIPTION
**Pull request by leezh**
Re-wrote nrex as a module using godot-specific parts and new features:

Removed use of mutable variables in RegEx. RegExMatch is returned instead. Example:

```
var re = RegEx.new()
re.compile("\\w+ (\\w+)")
var match = re.search("Hello world!")
print(match.get_string())
print(match.get_string(1))
```

Output:

```
Hello world
world
```

Added string substitutions. Example:

```
var re = RegEx.new()
re.compile("(\\w+) (\\w+)")
print(re.sub("John Doe", "\\2, \\1"))
```

Output:

```
Doe, John
```

Named groups are now supported. Example:

```
var re = RegEx.new()
re.compile("(?P<greet>\\w+) .+")
print(re.sub("Goodbye World", "You said \\g<greet>"))
var match = re.search("Hello world!")
print(match.get_names())
print(match.get_string("greet"))
print(match.expand("And I said \\g<greet>"))
```

Output:

```
You said Goodbye
[greet]
Hello
And I said Hello
```

Things left on the TODO list: Documentation and making RegEx an exportable resource.

I should also add the warning:
# THIS WILL BREAK EXISTING CODE.

### CODE REVIEW

**Comment by leezh** [comment]
Issue thread discussing this was at #6853

**Comment by akien-mga** [comment]
You should likely also `git rm -r drivers/nrex` no?

**Comment by leezh** [comment]
@akien-mga Done. Pushed an ammended commit.

Also, did the documentation, added support for global substitution and added bounds checking (realised it was a major security flaw :P).

All that is left is exposing RegEx fields to the editor.

**Comment by leezh** [comment]
Right, so modifying it to inherit Resource instead seems to be working for the most part, except that using Ctrl-S doesn't actually update the file. You'd have to manually save it from the inspector panel. Could someone have a look and see why that's happening?

**Comment by bojidar-bg** [comment]
@leezh Merge conflicts, seems like too many people touched the same tests file ^^

**Comment by akien-mga** [comment]
Yay for compatibility breakage! :D
The new API looks quite good.

**Pull request merged**
