### PR TITLE
Support menu key in TextEdit and LineEdit controls

### LINKED ISSUE #15542: Menu Key does not cause a context-menu to pop up
The [Menu Key](https://en.wikipedia.org/wiki/Menu_key) should cause a right-click context menu to pop up when pressed, as it does across the entire OS and most applications.

Useful not only for broken computer mice (which I'm suffering from right now), but also for accessibility and consistency with what a user might expect.

### PR DESCRIPTION
**Pull request by ptrojahn**
Related to #15542

### CODE REVIEW

**Comment by akien-mga** [comment]
Changes look fine overall, but I'm not sure it's worth it to add a `pixel_pos` member to TextEdit and LineEdit only far that. Wouldn't there be a way to get the local offset based on `line`/`col` or `pos`?

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Over all it looks good to me, the changes should be applied to `shader_editor_plugin` and `text_editor` as well. 

The one issue I ran across, is outside the editor the menu appears far away from the caret. My guess is the use of `get_global_transform().xform()`.

image

**Comment by ptrojahn** [comment]
Should be fixed now!

**Comment by Paulb23** [comment]
`TextEdit` and the "Script Edtiors" LGTM!

However, `line_edit` is still suffering from the menu being offset.

**Comment by ptrojahn** [comment]
Do you have a specific example for that line_edit issue? I fixed a bug that behaved just like you described and I can't reproduce it anymore.

**Comment by Paulb23** [comment]
Sure, running the scene in the attached project has the menu offset for me.

[line_edit_menu.zip](https://github.com/godotengine/godot/files/3638673/line_edit_menu.zip)

**Comment by ptrojahn** [comment]
Ah. Didn't consider vertical stretching of the LineEdit.

**Review by Paulb23 — APPROVED** [review]
LGTM.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
