### PR TITLE
Scripts can now access the audio buffer

### PR DESCRIPTION
**Pull request by marcelofg55**
This PR allows read access to the audio buffer using:

- `AudioServer.get_output_buffer`
- `AudioServer.get_output_position`
- `AudioServer.get_output_channels`

Works with ALSA, CoreAudio, PulseAudio and WASAPI.

I built a simple audio meter project using this:

screenshot from 2018-07-04 23-24-55

Audio Meter v3 Project: [AudioMeterv3.zip](https://github.com/godotengine/godot/files/2205734/AudioMeterv3.zip)

### CODE REVIEW

**Comment by marcelofg55** [comment]
I've finished implementing this, can be reviewed.

**Comment by groud** [comment]
Isn't GDscript too slow for audio processing ?  I'm wondering if such a low level access is pertinent in GDscript, because people may complain later on about bad performances on that part.

**Comment by LikeLakers2** [comment]
I don't think the intent of this PR is about audio processing, more just allowing people to access more audio data in case their applications need it for some reason. In all likelihood, anyone who's interested in actual proper audio processing will probably be using GDNative.

**Comment by groud** [comment]
Well, accessing the audio buffer and the playing position there is pretty low level. If we can't modify its content I wonder if so much information is worth being accessible.

Accessing the current volume is obviously pertinent. But aside from that I don't see a lot of other use case. Maybe you could do a Fourier transform on the, who've buffer to have frequency levels, but in GDscript this is probably going to be to slow.

**Comment by vnen** [comment]
GDScript isn't *that* slow, it can do some stuff with this data. And this PR also exposes this for every scripting language, so it can be used by NativeScript and C# too.

**Comment by groud** [comment]
It is not that slow, but to handle audio samples in real time I believe it is. I guess it makes more sense for C# though.

**Comment by marcelofg55** [comment]
I've re-based this due to some recent audio code changes, I'll re-check it and re-test as well.
Do not merge yet.

**Comment by marcelofg55** [comment]
Re-checked and re-tested.
Can be merged.

**Comment by reduz** [comment]
Sorry, I don't see the use of this myself, I can't understand the use case and given how GDScript works, this will be really inefficient.

**Comment by marcelofg55** [comment]
> Sorry, I don't see the use of this myself, I can't understand the use case and given how GDScript works, this will be really inefficient.

This can be used with C# and C++ scripts too, not only GDScript. I think that it can be used efficiently with C++ at least.
About the use case, besides the simple audio mixer project I made for testing it could also be used to write the audio output to a file (like a record audio feature on the game) and to create some audio effects based on the audio output. It could also be used for frequency analysis of the output audio and stuff like that.

**Comment by reduz** [comment]
@marcelofg55 I think it makes a lot more sense to expose AudioEffect somehow to C++ (specially via GDNative using a custom API, buffers is probably not a good idea as processing the audio is too dirty), then you can do pretty much any of that without adding hacks to drivers or the audio server.

**Comment by marcelofg55** [comment]
> @marcelofg55 I think it makes a lot more sense to expose AudioEffect somehow to C++ (specially via GDNative using a custom API, buffers is probably not a good idea as processing the audio is too dirty), then you can do pretty much any of that without adding hacks to drivers or the audio server.

Maybe I could try adding a signal at the AudioEffect process function? Or maybe I could instead add an audio_effect_signal effect that would emit a signal on the process function? Or maybe an audio_effect_buffer that could be used to read and write the buffer to use it on the process function? I'm thinking out loud mostly here :) any suggestion about these ideas?

**Comment by marcelofg55** [comment]
I'll re-work this out in another PR, closing this now.

**Pull request closed without merging**
