### PR TITLE
fixed disappearing items within the MenuButtons with assigned Shortcuts

### PR DESCRIPTION
**Pull request by syskrank**
Addresses #25900 and #25519.

### CODE REVIEW

**Comment by Awkor** [comment]
Consider using the following structure insted, as already discussed [here](https://github.com/godotengine/godot/pull/25841#discussion_r256360346):
```
String text = items[i].xl_text;
if (items[i].shortcut.is_valid()) {
	text += String(tr(items[i].shortcut->get_name()));
}
```
I think the AppVeyor build failed because of the misaligned indentation.

**Comment by syskrank** [comment]
Is that really necessary  to expand the ternary here?
We've got some really long lines around popup_menu.cpp:470, and no code style rule on this whatsoever.

Fixed formatting with clang-format.

**Comment by akien-mga** [comment]
This needs to be rebased as #25841 was reverted in #25901.
A re-do of #25841 that ensures that #25900 doesn't appear would be welcome, though I'll probably wait for after 3.1 to merge it.

**Comment by akien-mga** [comment]
Closing as per the above, it's no longer relevant after the revert of #25841.

**Comment by akien-mga** [comment]
Looks like I was wrong in the above comment, this PR is still relevant. #25841 was reverted, but this PR re-does its fix while preventing the #25900 regression.

**Comment by akien-mga** [comment]
Ah nevermind, now I remember. The original bug still needs a fix similar to what this PR does, but this PR itself is invalid as it builds upon a revert commit, and was never rebased. I'll do a new PR.

**Pull request closed without merging**
