### PR TITLE
[3.x] Switch to embree-aarch64

### PR DESCRIPTION
**Pull request by JFonS**
Switch the `embree` library for the ARM64 compatible version `embree-aarch64`. I also included some minor fixes to the SCsub so that 3.x and master use basically the same SCsub file.

### CODE REVIEW

**Comment by akien-mga** [comment]
Remember to update `thirdparty/README.md` too.

And I notice that we didn't add `thirdparty/embree` to `COPYRIGHT.txt`, but we should add `thirdparty/embree-aarch64` now.

**Comment by JFonS** [comment]
I forgot about that, will update in a bit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
