### PR TITLE
[macOS] Add default Window menu.

### PR DESCRIPTION
**Pull request by bruvzg**
Implements https://github.com/godotengine/godot-proposals/issues/7768

Screenshot 2023-10-15 at 21 05 43

### CODE REVIEW

**Comment by lostminds** [comment]
If this will now populate with all app windows (for multi-window projects), it might be an idea to add the [excludedFromWindowsMenu](https://developer.apple.com/documentation/appkit/nswindow/1419175-excludedfromwindowsmenu?language=objc) flag to popup windows like AcceptDialog (maybe all windows with the Window.popup_window flag set?) to prevent them from appearing in the menu automatically.

**Comment by bruvzg** [comment]
> it might be an idea to add the [excludedFromWindowsMenu](https://developer.apple.com/documentation/appkit/nswindow/1419175-excludedfromwindowsmenu?language=objc) flag to popup windows like AcceptDialog (maybe all windows with the Window.popup_window flag set?) to prevent them from appearing in the menu automatically.

This is a good idea, added it for windows with `popup` and `no focus` (tooltips) flags.

**Comment by YuriSizov** [comment]
Is this superseded by https://github.com/godotengine/godot/pull/83987?

**Comment by bruvzg** [comment]
> Is this superseded by https://github.com/godotengine/godot/pull/83987?

Yes.

**Pull request closed without merging**
