### PR TITLE
typo ellipsis, added

### PR DESCRIPTION
**Pull request by leela52452**
[source](https://hosted.weblate.org/projects/godot-engine/godot/source/review/?type=check%3Aellipsis)

### CODE REVIEW

**Comment by Chaosus** [comment]
You need to squash all these commits together, see http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by akien-mga** [comment]
This is not really a typo, it's done on purpose since as of 2019, there is still no easy way for lambda computer users to input `…` on their keyboard. If you're a bit tech savvy you might know how to do it, or if you're a bit less tech savvy you'll type `...` in an advanced editor like Word, let it convert it, and copy paste it everywhere... But it's definitely not a convenient workflow.

So now, I don't want to presume that translators will be able to do this extra work, so IMO it's better to simply use three dots in the source form. If we want the editor to then *display* an ellipsis character, that can be done programmatically.

**Comment by akien-mga** [comment]
Before spending too much time doing such changes, I'd advise discussing with upstream whether this is done on purpose and if it should be fixed. Otherwise it's potentially a lot of time lost for you if we end up rejecting the proposal.

**Comment by akien-mga** [comment]
Closing for now as per above comments. I'm not strongly against the change, but it has to be discussed beforehand and then handled properly in a single commit. We also have to take care not to invalidate hundreds of translations needlessly, so .po files should likely see the same substitution for languages where this character is relevant.

**Pull request closed without merging**
