### PR TITLE
D3D12: Use the right state for resources in certain heap types

### LINKED ISSUE #93670: D3D12 renderer crash when it can't create buffer
This is a bug report by @matheusmdx, I just branched it off from #93249 to a new ticket.

@matheusmdx wrote:

I followed the steps to reproduce the bug but in my case the crash happens after set the rendering device to d3d12 and restart the editor so i'm not sure if my crash is exactly the same cause, also if i start using --rendering-driver d3d12 imediatly crash the engine even if i don't try open any project. Here the errors + backtrace: 

```
PS C:\Users\Matheus\Downloads\Godot Source\bin> .\godot.windows.editor.dev.x86_64.exe --rendering-driver d3d12 --debug
PS C:\Users\Matheus\Downloads\Godot Source\bin> Godot Engine v4.3.beta.custom_build.170af05c8 (2024-06-17 11:30:20 UTC) - https://godotengine.org
D3D12 12_0 - Forward+ - Using Device #0: AMD - AMD Radeon RX 580 2048SP
ERROR: Can't create buffer of size: 262144, error 0x80070057.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:917)
ERROR: Condition "!block.driver_id" is true. Returning: ERR_CANT_CREATE
   at: RenderingDevice::_insert_staging_block (servers\rendering\rendering_device.cpp:242)
ERROR: Condition "err != OK" is true. Continuing.
   at: RenderingDevice::initialize (servers\rendering\rendering_device.cpp:5510)
ERROR: Can't create buffer of size: 262144, error 0x80070057.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:917)
ERROR: Condition "!block.driver_id" is true. Returning: ERR_CANT_CREATE
   at: RenderingDevice::_insert_staging_block (servers\rendering\rendering_device.cpp:242)
ERROR: Condition "err != OK" is true. Continuing.
   at: RenderingDevice::initialize (servers\rendering\rendering_device.cpp:5510)
WARNING: PSO caching is not implemented yet in the Direct3D 12 driver.
     at: RenderingDeviceDriverD3D12::pipeline_cache_create (drivers\d3d12\rendering_device_driver_d3d12.cpp:4941)
ERROR: FATAL: Index p_index = 0 is out of bounds (size() = 0).
   at: CowData<struct RenderingDevice::StagingBufferBlock>::get (C:\Users\Matheus\Downloads\Godot Source\core/templates/cowdata.h:205)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.beta.custom_build (170af05c8022ad3e0cefb287ca0cb3790c8747f6)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] CowData<RenderingDevice::StagingBufferBlock>::get (C:\Users\Matheus\Downloads\Godot Source\core\templates\cowdata.h:205)
[1] Vector<RenderingDevice::StagingBufferBlock>::operator[] (C:\Users\Matheus\Downloads\Godot Source\core\templates\vector.h:97)
[2] RenderingDevice::_staging_buffer_allocate (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\rendering_device.cpp:261)
[3] RenderingDevice::_texture_update (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\rendering_device.cpp:1228)
[4] RenderingDevice::texture_create (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\rendering_device.cpp:826)
[5] RendererRD::TextureStorage::TextureStorage (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\renderer_rd\storage_rd\texture_storage.cpp:114)
[6] RendererCompositorRD::RendererCompositorRD (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\renderer_rd\renderer_compositor_rd.cpp:305)
[7] RendererCompositorRD::_create_current (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\renderer_rd\renderer_compositor_rd.h:138)
[8] RendererCompositor::create (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\renderer_compositor.cpp:43)
[9] RenderingServerDefault::_init (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\rendering_server_default.cpp:220)
[10] RenderingServerDefault::init (C:\Users\Matheus\Downloads\Godot Source\servers\rendering\rendering_server_default.cpp:261)
[11] Main::setup2 (C:\Users\Matheus\Downloads\Godot Source\main\main.cpp:2833)
[12] Main::setup (C:\Users\Matheus\Downloads\Godot Source\main\main.cpp:2465)
[13] widechar_main (C:\Users\Matheus\Downloads\Godot Source\platform\windows\godot_windows.cpp:165)
[14] _main (C:\Users\Matheus\Downloads\Godot Source\platform\windows\godot_windows.cpp:206)
[15] main (C:\Users\Matheus\Downloads\Godot Source\platform\windows\godot_windows.cpp:220)
[16] WinMain (C:\Users\Matheus\Downloads\Godot Source\platform\windows\godot_windows.cpp:234)
[17] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[18] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

<br>

If my case is a different bug please inform me and i'll open a separated issue

_Originally posted by @matheusmdx in https://github.com/godotengine/godot/issues/93249#issuecomment-2173465395_

### PR DESCRIPTION
**Pull request by RandomShaper**
When enhanced resource barriers are not available, and thus the legacy barriers are used, buffers in an upload heap need to have the `D3D12_RESOURCE_STATE_GENERIC_READ` status (otherwise, the creation fails and also the debug layer complains about it).

**2024-07-01:** Also using `D3D12_RESOURCE_STATE_COPY_DEST` for readback heaps.

Fixes #93670.

### CODE REVIEW

**Comment by clayjohn** [comment]
I am still getting a crash with this PR, but the crash happens later. It seems it crashes when trying to read back data from a texture. I was able to reproduce this just by opening a project in the editor. I'll do more testing to see if I can find more info for you

```
ERROR: Can't create buffer of size: 3904, error 0x80070057.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:922)
ERROR: Condition "!tmp_buffer" is true. Returning: Vector<uint8_t>()
   at: RenderingDevice::texture_get_data (servers\rendering\rendering_device.cpp:1615)
ERROR: Condition "data.is_empty()" is true. Returning: Ref<Image>()
   at: RendererRD::TextureStorage::texture_2d_get (servers\rendering\renderer_rd\storage_rd\texture_storage.cpp:1272)
ERROR: Can't create buffer of size: 3904, error 0x80070057.
   at: (drivers\d3d12\rendering_device_driver_d3d12.cpp:922)
ERROR: Condition "!tmp_buffer" is true. Returning: Vector<uint8_t>()
   at: RenderingDevice::texture_get_data (servers\rendering\rendering_device.cpp:1615)
ERROR: Condition "data.is_empty()" is true. Returning: Ref<Image>()
   at: RendererRD::TextureStorage::texture_2d_get (servers\rendering\renderer_rd\storage_rd\texture_storage.cpp:1272)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.3.beta.custom_build (181e9e1ede994a265de73136b9ae0bcb1b05b66c)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] Image::get_size (F:\dev\godot\core\io\image.cpp:453)
[1] Image::get_size (F:\dev\godot\core\io\image.cpp:453)
[2] AnimationPlayerEditor::_notification (F:\dev\godot\editor\plugins\animation_player_editor_plugin.cpp:163)
[3] AnimationPlayerEditor::_notificationv (F:\dev\godot\editor\plugins\animation_player_editor_plugin.h:48)
[4] Object::notification (F:\dev\godot\core\object\object.cpp:873)
[5] Node::_notification (F:\dev\godot\scene\main\node.cpp:126)
[6] Node::_notificationv (F:\dev\godot\scene\main\node.h:50)
[7] CanvasItem::_notificationv (F:\dev\godot\scene\main\canvas_item.h:45)
[8] Control::_notificationv (F:\dev\godot\scene\gui\control.h:48)
[9] Container::_notificationv (F:\dev\godot\scene\gui\container.h:37)
[10] BoxContainer::_notificationv (F:\dev\godot\scene\gui\box_container.h:37)
[11] VBoxContainer::_notificationv (F:\dev\godot\scene\gui\box_container.h:90)
[12] AnimationPlayerEditor::_notificationv (F:\dev\godot\editor\plugins\animation_player_editor_plugin.h:48)
[13] Object::notification (F:\dev\godot\core\object\object.cpp:873)
[14] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:294)
[15] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[16] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[17] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[18] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[19] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[20] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[21] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[22] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[23] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[24] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[25] Node::_propagate_enter_tree (F:\dev\godot\scene\main\node.cpp:313)
[26] Node::_set_tree (F:\dev\godot\scene\main\node.cpp:3164)
[27] SceneTree::initialize (F:\dev\godot\scene\main\scene_tree.cpp:449)
[28] OS_Windows::run (F:\dev\godot\platform\windows\os_windows.cpp:1684)
[29] widechar_main (F:\dev\godot\platform\windows\godot_windows.cpp:181)
[30] _main (F:\dev\godot\platform\windows\godot_windows.cpp:206)
[31] main (F:\dev\godot\platform\windows\godot_windows.cpp:220)
[32] WinMain (F:\dev\godot\platform\windows\godot_windows.cpp:234)
[33] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[34] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

**Comment by DarioSamo** [comment]
> otherwise, the creation fails and also the debug layer complains about it

It doesn't do it for me either with and without Agility SDK. Is it dependent on the driver? I recall having trouble with this elsewhere on other systems but couldn't find any details on the specification about why COMMON is banned from being used in upload. I'm just confused as to why the validation says nothing to me in this case.

**Comment by RandomShaper** [comment]
I found this at what https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_heap_type says:
> `D3D12_HEAP_TYPE_UPLOAD`
> [...]
> Resources in this heap must be created with `D3D12_RESOURCE_STATE_GENERIC_READ` and cannot be changed away from this. The CPU address for such heaps is commonly not efficient for CPU reads.

And also this, I've just found the debug layer complains about in my case as well:
> `D3D12_HEAP_TYPE_READBACK`
> [...]
> Resources in this heap must be created with `D3D12_RESOURCE_STATE_COPY_DEST`, and cannot be changed away from this.

I've updated the PR so we meet this latter requirement as well. I no longer get errors about that. @clayjohn, can you confirm this fixes the issue for you, too?

**Comment by DarioSamo** [comment]
> I found this at https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_heap_type:

Seems like a good enough reason to change it then, apologies for the change to common then. I can't help but wonder why the debug layer accepts it on some systems and not in others though. I'll ask if the promotion was added at some point.

**Comment by RandomShaper** [comment]
> Seems like a good enough reason to change it then, apologies for the change to common then. I can't help but wonder why the debug layer accepts it on some systems and not in others though. I'll ask if the validation was added at some point.

No need to apologize! We do changes to our best judgement. I'm curious about the validation difference, too.

**Review by clayjohn — APPROVED** [review]
Looks good to me. 

I have tested with the original MRP and with Desert Light and neither are crashing now!

**Comment by akien-mga** [comment]
Thanks!

**Comment by TCROC** [comment]
I can confirm this PR seems to be fixing the crash we were experiencing in #93670 on our NVIDIA 1070 Windows 10 computer.  When we get back home, I'll test on our AMD Radeon Windows 10 computer and see if it is fixed there as well! Thanks everyone and great work! :)

**Comment by TCROC** [comment]
Can confirm the PR fixes both AMD and NVIDIA issues on Windows 10 :)

**Pull request merged**
