### PR TITLE
Add libopenmpt for mod tracker music playback (mod, it, s3m, xm, etc.)

### PR DESCRIPTION
**Pull request by ShyRed**
# What is this?

This pull requests adds [libopenmpt](https://lib.openmpt.org/libopenmpt/) as a module to godot. Libopenmpt is the library responsible for mod tracker music playback in the [OpenMPT](https://openmpt.org/) music player.

The library is free (BSD license), open source, crossplatform, actively maintened by the openmpt dev team and supports 
**43** music media types:
mod s3m xm it mptm stm pt36 nst m15 stk st26 ice wow ult 669 mtm med far mdl ams dsm amf okt dmf ptm psm mt2 dbm digi imf j2b plm sfx sfx2 mms stp dtm gdm umx mo3 xpk ppm mmcmp

# Why?

Mod tracker music is a bit like the midi file format: it contains mostly control commands to play samples. Unlike midi the tracker files contain the sample data instead of relying on the OS to provide them. This makes tracker music file size a bit larger than midi (usually 100kb - 1MB), but still much smaller than a wav, ogg or mp3 file.

By using mod tracker songs the dev can reduce game file size and also get a certain "retro" feeling to their game.

... also, mod support is part of the Godot GSOC-2018 list ( https://github.com/godotengine/roadmap/blob/master/GSOC-2018.md#plugins-for-midi-and-mod-support ) ... so there is that.

# So what has been done?

1. Added libopenmpt to the thirdparty folder
2. Implemented module for importing & playback (pretty much the same like the ogg module)
3. Added entry in SConstruct, Scons (mo3 and  j2b rely on ogg vorbis / miniz/zlib)
4. Compiled on windows 7 with Visual Studio 2017 & Tested with demo project

# The future

libopenmpt provides support for midi playback which has not been made use of in this pull request. In order to implement midi support this might be use as a base.

Mod tracker files include a lot of meta information (instruments, samples, songs in song, etc). If desired, these information can be exposed to the user to display information about the song currently being played.

# Demo project

Attached is a small demo project featuring 4 sample songs of different media types taken from https://modarchive.org

testproject
[Libopenmpttest.zip](https://github.com/godotengine/godot/files/1744839/Libopenmpttest.zip)

# Last words

So this is my first "big" pull request and it mostly is a learning exercise for me. Please feel free to provide feedback on what is good, bad and what can be improved. If this gets merged, then I'm happy. If it does not get merged, I'm still happy because I learned a lot :smile:

### CODE REVIEW

**Comment by ShyRed** [comment]
Mh, you're right. It shouldn't be too much effort to turn this into a GDNative plugin. :smile:

I'm honestly confused as to why the complete travis build failed, though. It seems that the library does not compile with linux... I'll try to look into that and come up with a proper working plugin.

Shall I close this pull request?

**Comment by reduz** [comment]
Yeah, I suggest this is put on a repo on github and submitted to our asset
library as a GDNative add-on.

**Comment by reduz** [comment]
please come by to #godotengine-gdnative to discuss with the guys and get
some help on doing this

**Comment by reduz** [comment]
on irc.freenode.net

**Comment by aaronfranke** [comment]
@ShyRed Any progress on making a GDNative plugin? [/u/sunnysmiles17](https://www.reddit.com/r/godot/comments/afvalx/godot_40_game_engine_to_work_on_vulkan_port_big/ee23uz5/) would like mod tracker support.

**Comment by ShyRed** [comment]
@aaronfranke No progress. Mod tracker support plugin is up for grabs.

**Pull request closed without merging**
