### PR TITLE
Disable update spinner when debug redraw is active

### PR DESCRIPTION
**Pull request by KoBeWi**
https://github.com/godotengine/godot/pull/79169#issuecomment-1675956081

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by clayjohn** [comment]
I don't understand why we would disable this. The point of debug redraw is to show when things are redrawn. Since the update spinner updates every frame, it makes sense that it constantly triggers the debug redraw code.

Is the concern about having something flashing on the screen?

To me it looks like it's working as intended.

**Comment by KoBeWi** [comment]
The problem is that update spinner triggers debug redraw, which causes the update spinner to redraw and it runs into an infinite redraw loop. Update spinner is supposed to indicate that something is being updated, but here it's signalling its own update, which is pointless. I think perfectly the update spinner should be an exception from debug redraw, but it's such a niche feature that anything more than a quickfix isn't probably worth it.

**Comment by clayjohn** [comment]
> The problem is that update spinner triggers debug redraw, which causes the update spinner to redraw and it runs into an infinite redraw loop. Update spinner is supposed to indicate that something is being updated, but here it's signalling its own update, which is pointless. I think perfectly the update spinner should be an exception from debug redraw, but it's such a niche feature that anything more than a quickfix isn't probably worth it.

Ah, okay right. That makes sense.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
