### PR TITLE
Make property description in the animation editor actually show it

### PR DESCRIPTION
**Pull request by YeldhamDev**
**Fun fact:** that feature never worked as far as I'm aware of! :wink:

Screenshot at 2021-08-08 22-59-21

### CODE REVIEW

**Comment by fire** [comment]
:eyes: @TokageItLab 

That's great!

**Comment by Calinou** [comment]
Nice :slightly_smiling_face: 

Maybe the method/property name should be displayed in bold before the description, similar to https://github.com/godotengine/godot/pull/50505.

**Comment by YeldhamDev** [comment]
@Calinou Changes made (see the updated preview image).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.

**Pull request merged**
