### PR TITLE
 Add editor option for automatically closing the output when stopping the game (2.1)

### PR DESCRIPTION
**Pull request by RandomShaper**
(back-ported from 1bd1af776c111f1efdd9a3b0259d8f916c052ef2)

### CODE REVIEW

**Review by bojidar-bg — APPROVED** [review]
LGTM, though I'm not sure if the default should be "false" or "true".

**Comment by kubecz3k** [comment]
I think it would be the best if that could be semi-automatic. If user had turn it on in editor then it should not hide automatically. If user hid it in editor then it should hide when game is stopped.

**Comment by RandomShaper** [comment]
Well, this is just a backport of what's already merged for 3.0. So it's 
done as long as it works.

Nonetheless, your suggestion can be studied as a separate feature 
request. But I'm not sure I get what you're telling.

By "turn on" do you mean having the output pane visible or having the 
setting enabled?

**Comment by kubecz3k** [comment]
I meant having the panel visible, I think that way we could maybe even get rid of additional setting since behavior would be based on what user was doing recently with this panel. Was not aware of the fact it's a backport from 3.0, just wanted to share what seemed the best from my perspective. Thanks!

**Comment by RandomShaper** [comment]
That may be interesting. Please open a feature request issue so others can share their impressions.

So we can consider this one complete.

**Pull request merged**
