### PR TITLE
Refactored Variant Operators.

### PR DESCRIPTION
**Pull request by reduz**
* Using classes to call and a table
* For typed code (GDS or GDNative), can obtain functions to call prevalidated or ptr.

### CODE REVIEW

**Comment by qarmin** [comment]
There are memory leaks when opening and closing  project manager:
```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f20fd753517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0x12725c31 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:76
    #2 0x12725b30 in operator new(unsigned long, char const*) core/os/memory.cpp:41
    #3 0x12572ae3 in void register_op<OperatorEvaluatorInArrayFind<Vector<double>, int> >(Variant::Operator, Variant::Type, Variant::Type) core/variant_op.cpp:1851
    #4 0x124c1fb2 in register_variant_operators() core/variant_op.cpp:2287
    #5 0x11e0c6c7 in register_core_types() core/register_core_types.cpp:117
    #6 0x1e3411e in Main::setup(char const*, int, char**, bool) main/main.cpp:506
    #7 0x1d23ef5 in main platform/linuxbsd/godot_linuxbsd.cpp:51
    #8 0x7f20fc5200b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f20fd753517 in malloc (/lib/x86_64-linux-gnu/libasan.so.6+0xb0517)
    #1 0x12725c31 in Memory::alloc_static(unsigned long, bool) core/os/memory.cpp:76
    #2 0x12725b30 in operator new(unsigned long, char const*) core/os/memory.cpp:41
    #3 0x124f09a3 in void register_op<OperatorEvaluatorMul<Color, Color, Color> >(Variant::Operator, Variant::Type, Variant::Type) core/variant_op.cpp:1851
    #4 0x124c0612 in register_variant_operators() core/variant_op.cpp:1915
    #5 0x11e0c6c7 in register_core_types() core/register_core_types.cpp:117
    #6 0x1e3411e in Main::setup(char const*, int, char**, bool) main/main.cpp:506
    #7 0x1d23ef5 in main platform/linuxbsd/godot_linuxbsd.cpp:51
    #8 0x7f20fc5200b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
```
Also undefined sanitizer shows usage of non-initialized memory
```
core/variant_op.cpp:985:12: runtime error: load of value 3200171710, which is not a valid value for type 'Type'
core/variant_op.cpp:985:12: runtime error: load of value 3200171710, which is not a valid value for type 'Type'
core/variant_op.cpp:985:12: runtime error: load of value 3200171710, which is not a valid value for type 'Operator'
core/variant_op.cpp:962:12: runtime error: load of value 3200171710, which is not a valid value for type 'Type'
core/variant_op.cpp:962:12: runtime error: load of value 3200171710, which is not a valid value for type 'Type'
core/variant_op.cpp:962:12: runtime error: load of value 3200171710, which is not a valid value for type 'Operator'
```

Also code(where `i` is a node)
```
i.get_name() != "Camera":
```
causes this error
```
Invalid operands 'StringName' and 'String' in operator '!='
```
Project to test this(should work fine in master) - https://github.com/qarmin/RegressionTestProject/archive/master.zip

**Comment by reduz** [comment]
@qarmin thanks!

**Comment by qarmin** [comment]
Code `node.get_parent() != null:` shows error `Parser Error: Invalid operators "Node" and null for "!=" operator`

Also
```
var use_Object: bool = true
	if ! use_Object:
```
shows error: `Invalid operand of type "bool" for unary operator "not"`


Project which works without hard errors(normal errors and warnings are disabled) on master - [TheWorstGodotTestProject.zip](https://github.com/godotengine/godot/files/5495833/TheWorstGodotTestProject.zip)

**Comment by qarmin** [comment]
Code `36235 in ["asfasfqw","asfqwgqani",36235]` shows now - `Invalid operands "int" and "Array" for "in" operator`
Code `36235 and 36235` -  `Invalid operands  to operator and, int and int`
Code `36235 && 36235` -  `Invalid operands  to operator and, int and int`
Code `36235 or 36235` -  `Invalid operands  to operator and, int and int`
Code `36235 || 36235` -  `Invalid operands  to operator and, int and int`

**Comment by reduz** [comment]
@qarmin yeah, numbers were not supported in and/or, had to add them

**Comment by reduz** [comment]
ah, I messed up the order in the "in" operator..

**Comment by qarmin** [comment]
```
var move_vector : Vector2 = Vector2(1,1)
move_vector = -move_vector
```
shows error
```
Invalid operand of type Vector2 for unary operator "-(negation)"
```
Project - [RegressionTestProject.zip](https://github.com/godotengine/godot/files/5499274/RegressionTestProject.zip)

**Comment by qarmin** [comment]
This code worked fine in master and 3.2 branch, but now shows errors
```
func _ready() -> void:
	for i in [Vector2(),Vector3(),float(),int()]:
		i = -i
		i = i
		i = i * i
		i = i * 1.0
		i = i / 1.0
		i = i * 1
		i = i / 1
	for i  in [Basis(),Transform(),Transform2D()]:
		i = i
		i = i * i
```

**Comment by reduz** [comment]
@qarmin alright, force pushed fixes, thanks! lets hope it all works now.

**Comment by qarmin** [comment]
Still
```
var ss : float = 2.0
-ss
```
shows error about invalid unary iterator - [Test Project](https://github.com/qarmin/RegressionTestProject/archive/master.zip)

```
var use_Object : bool = false
	if ! use_Object:
		return
```
shows error ` Parse Error: Invalid operand of type "bool" for unary operator "not".` - [Test Project](https://github.com/qarmin/The-worst-Godot-test-project/archive/master.zip) - works very slow

**Review by vnen — APPROVED** [review]
Haven't looked super thoroughly but in terms of GDScript it looks fine. It'll allow me to remove specific instructions for each operator combination.

**Comment by reduz** [comment]
@qarmin I can't see anything wrong from my side for that, have the feeling this is a bug in the GDScript interpreter because calling conditions now are more strict. Most likely a non nil variant is being passed as a second argument.

**Comment by reduz** [comment]
merging for now since it seems to work for the most part, and I need to continue working on this stuff. If more problems are found we can fix them later.

**Pull request merged**
