### PR TITLE
Clarify what happens when return value is discarded in GDScript warning text

### LINKED ISSUE #68896: Improve clarity of "Return Value Discarded" GDScript warning
### Godot version

4.0 dev Beta 5

### System information

Arch Linux

### Issue description

I get a flood of this:
image

Despite having set this:
image

### Steps to reproduce

1. Use a function that returns a value that you discard.
2. Run the project and see a warning (default)
3. Go to Project > Settings (Advanced Settings must be enabled) > Debug > GDScript > Unused Variable and change the value to Ignore
4. Rerun your project and see that it had no effect
5. Change it to Error
6. Try again and see that this has an effect

### Minimal reproduction project

[Beta 5 Warnings.zip](https://github.com/godotengine/godot/files/10047841/Beta.5.Warnings.zip)

### PR DESCRIPTION
**Pull request by souplamp**
Fixes #68896.

Improve `RETURN_VALUE_DISCARDED` warning text by clarifying that the return value of a function isn't just unused, but discarded.

This change makes the warning more consistent with the language of similar 'discarded' warnings, such as `INTEGER_DIVISION` (see below). This will also make it easier for users to find "Return Value Discarded" in Project Settings -> Debug -> GDScript, as the previous warning text implied it would be found with the prefix "Unused."

### **Before:**
before-warning

### **After:**
update_after

### CODE REVIEW

**Comment by timothyqiu** [comment]
I think "use" is still better than "store it in a variable". This is valid and does not need a variable:

```gdscript
# warning
produce_value()

# no warning
consume_value(produce_value())
```

**Comment by souplamp** [comment]
> I think "use" is still better than "store it in a variable".

I was thinking the same. 
How about this: `The function returns a value that will be discarded if not used.`

**Comment by souplamp** [comment]
Not entirely sure why these checks aren't successful? I only changed the warning text, but I see it fails to build the editor on MacOS/Linux which I haven't tested on.

**Comment by clayjohn** [comment]
> Not entirely sure why these checks aren't successful? I only changed the warning text, but I see it fails to build the editor on MacOS/Linux which I haven't tested on.

The warning text in the tests needs to be updated to match the new warning text. 

What the tests do is running the script and check if the output is the same as when the test was written. If the text differs, it fails. Since the text includes the warning, you have to update the test output when you change the text of the warning.

**Comment by souplamp** [comment]
> The warning text in the tests needs to be updated to match the new warning text.

Thank you! I completely missed the unit tests. All check have passed now :)

**Review by clayjohn — APPROVED** [review]
Great work! Its passing all tests now. I think this is a useful improvement over the old text

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
