### PR TITLE
Remove `PROPERTY_HINT_IMAGE_COMPRESS` constants

### PR DESCRIPTION
**Pull request by Mickeon**
Removes **PROPERTY_HINT_IMAGE_COMPRESS_LOSSY** and **PROPERTY_HINT_IMAGE_COMPRESS_LOSSLESS**. These do not actually do anything, at all. These were used in 3.x, but are no longer necessary now.

### CODE REVIEW

**Comment by nikitalita** [comment]
What about lossy-compressed webps? Textures can still be encoded as those.

**Comment by nikitalita** [comment]
Also, this should be labeled as "breaks-compat" since it changes the enum and the values in those fields would change.

**Comment by Mickeon** [comment]
> What about lossy-compressed WEBPs? Textures can still be encoded as those.

Don't worry, these are not import options. I reiterate, these property hints do not do anything in the engine.

**Comment by nikitalita** [comment]
> > What about lossy-compressed WEBPs? Textures can still be encoded as those.
> 
> Don't worry, these are not import options. I reiterate, these property hints do not do anything in the engine.

These are not import options, but texture resources that were imported prior to this would become invalid because those property fields would no longer be accurate.

You are correct that these property hints do not do anything in the engine; I checked the code and it appears that our webp module just encodes whether or not it's lossless into the header, it no longer sets that property field. I think that is a mistake; even if it is not required to decode the webp, the engine should still have that information available.

**Comment by Mickeon** [comment]
This PR's failing check has made me discover that PROPERTY_HINT_INT_IS_POINTER and PROPERTY_HINT_ARRAY_TYPE are exposed in the wrong order and should be swapped. Putting it out here as a mental note.

**Comment by nikitalita** [comment]
I am sorry, I had thought that this also removed `COMPRESS_LOSSLESS` and `COMPRESS_LOSSY`; those values would remain unchanged and those are still encoded in the texture. The PropertyHint is only set after the resource is imported. I withdraw my objection.

**Comment by nikitalita** [comment]
After some searching through the code, I don't see any Object that encodes PropertyHint directly into a resource. I don't think this will break any Godot resources; it might break resources in extensions that do that, though. It might also break third-party editor tools that rely on the PropertyHint enum they get from the language server directly.

In either case, the enum values started changing back in April, here: https://github.com/godotengine/godot/pull/60458

At the time, It was decided to just merge and cleanup later. So I guess that's something to worry about later? 🤷

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting, those are unused (also unused in 3.x but we don't want to break compat there).

**Comment by Mickeon** [comment]
Rebased.

**Pull request merged**
