### PR TITLE
Added returning an exit code by the blocking OS::execute method

### LINKED ISSUE #31881: OS.execute produces no output and a wrong return code
**Godot version:** v3.1.1

**OS/device including version:** Windows 10

**Issue description:**

`OS.execute()` when blocking always returns -2 as return value (even if the program crashes) and an empty string as output.

This is the script (`gita` is an inexistent program):

image

This is the editor's console:

image

And this is the Godot's console:

image

As you can see, it runs normally, I just can't retrieve both results at the editor (even if I run as a game, not as a tool). This means if the `git clone` fails, there's no way for me to know.
Despite using a `git clone`, we can reproduce this with any program.

### PR DESCRIPTION
**Pull request by NNesh**
As a way to resolve #31881

### CODE REVIEW

**Comment by Calinou** [comment]
The documentation should be reflected to update this :slightly_smiling_face: 

https://github.com/godotengine/godot/blob/da2af72d7357498dac7ce425c9ad3ab66eadb32f/doc/classes/OS.xml#L89-L123

**Comment by akien-mga** [comment]
Looks good to me, could you squash commits together?

**Review by akien-mga — APPROVED** [review]
Should we ok to merge pending squash.

**Comment by akien-mga** [comment]
I squashed the commits (and slightly amended the commit log).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
