### PR TITLE
Fix for Visual Shader Editor #22906: Cannot change color on Color Con…

### PR DESCRIPTION
**Pull request by fire**
Fix for #22906

### CODE REVIEW

**Comment by fire** [comment]
@DualMatrix Can you comment on why this was changed?

**Comment by fire** [comment]
From https://github.com/godotengine/godot/commit/5f2f1089086ad64636efc2a4096e55e4483c927a

**Comment by fire** [comment]
I don't have a test project for #22536 So can someone test that function is still correct?

**Comment by DualMatrix** [comment]
So as far as I recall this wasn't actually intended. I think I accidentally changed that line while working on the for #22536 and I must've forgotten to delete it. Sorry, my bad :(

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
