### PR TITLE
[TextServer] Reset subpixel shift on blank glyphs.

### LINKED ISSUE #98659: Multiline text glyph precision issue (TextEdit, TextParagraph etc.)
### Tested versions

Present in current master:
v4.4.dev.custom_build [8004c7524]

Bisect:
[dc8d7ef43ea881ccc4fbb391f9dc22fa46168a7f]

### System information

Godot v4.4.dev (8004c7524) - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6094) - AMD Ryzen 9 7950X 16-Core Processor (32 threads)

### Issue description

The pixel position of glyphs in multiline shaped text (`TextEdit`, `TextParagraph`) varies based on the length of the previous lines even if the word/line-boundaries don't change. In `TextEdit`, for example, the glyphs jitter around distractingly when editing the text in the middle.

Demonstration using 2 `TextEdit`s. The red one at the bottom has a single 'A' fewer but the lines are justified the same. Observe that despite this, the glyphs from second row on don't align and the red glyphs shine though.

Screenshot 2024-10-30 032441

### Steps to reproduce

Use any multiline-text-editor.

### Minimal reproduction project (MRP)

[unstable_textedit.zip](https://github.com/user-attachments/files/17564876/unstable_textedit.zip)

This is what the demo.tscn scene should look like:

Screenshot 2024-10-30 034912

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/98659

Regression from https://github.com/godotengine/godot/pull/93256, accumulated subpixel shift remainder was unnecessarily preserved over word/line break.

### CODE REVIEW

**Comment by Lielay9** [comment]
Most of the jittering is gone but some still remain:
Screenshot 2024-10-31 011355

```gdscript
var font_regular: Font = get_theme_default_font() # Antialias none
var raw_text1: String = "w\n\nord1 word2 word3 word4 word5 word6 word7"
var raw_text2: String = "w\n \nord1 word2 word3 word4 word5 word6 word7"

var font_size: int = 32

func _draw() -> void:
	draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE * 5.0)
	draw_rect(get_rect(), Color.BLACK)
	var text_paragraph: TextParagraph = TextParagraph.new()
	text_paragraph.width = size.x # 247px
	text_paragraph.add_string(raw_text1, font_regular, font_size)
	text_paragraph.draw(get_canvas_item(), Vector2.ZERO, Color.RED)

	text_paragraph = TextParagraph.new()
	text_paragraph.width = size.x # 247px
	text_paragraph.add_string(raw_text2, font_regular, font_size)
	text_paragraph.draw(get_canvas_item(), Vector2.ZERO)
```
4.2 for reference:
Screenshot 2024-10-31 011521

**Comment by Lielay9** [comment]
Mandatory linebreaks work, `BREAK_ADAPTIVE` and `BREAK_GRAPHEME_BOUND` still cause issues (first line missmatch expected but second and third should be identical),
Screenshot 2024-10-31 212227

**Comment by Lielay9** [comment]
Additionally, even content on the same line is rather flickery compared to 4.2.

FLICKERING WARNING!

4.4 ,

https://github.com/user-attachments/assets/4dfb13b1-5da2-4d88-a42f-6f5616575250

4.2 ,

https://github.com/user-attachments/assets/3cbe74a6-2e0d-4bd1-bbd3-1c4156047d6e

**Comment by bruvzg** [comment]
> Additionally, even content on the same line is rather flickery compared to 4.2.

That's looks expected, kerning always have subpixel values, and glyphs are aligned to the pixel boundaries. If you do not want it to be aligned, enable subpixel positioning in the font import settings.

> Mandatory linebreaks work, BREAK_ADAPTIVE and BREAK_GRAPHEME_BOUND still cause issues (first line missmatch expected but second and third should be identical),

Enabling subpixel positioning should fix it as well. Fixing it for the pixel aligned font require either full resahping of the sub-strings (a big performance impact), or moving rounding step to draw (can't be done since draw calls do not have any global context), or rounding each glyph position individual (like it was in 4.2, which will reintroduce #93199). I guess we can make #93256 and optional import setting as well.

**Comment by Lielay9** [comment]
> That's looks expected, kerning always have subpixel values, and glyphs are aligned to the pixel boundaries. If you do not want it to be aligned, enable subpixel positioning in the font import settings.

Thanks, using more aggressive subpixel setting seems to alleviate most of the remaining issues.

> Enabling subpixel positioning should fix it as well. Fixing it for the pixel aligned font require either full resahping of the sub-strings (a big performance impact), or moving rounding step to draw (can't be done since draw calls do not have any global context), or rounding each glyph position individual (like it was in 4.2, which will reintroduce #93199). I guess we can make #93256 and optional import setting as well.

I cannot speak for the technical side so I have no opinion on that front. That said, the issue (https://github.com/godotengine/godot/issues/98659) was found in our accessibility tests flagging a multiline text editor as a potential source of epilepsy. Of course, sizable blocks of text are notoriously bad for photosensitive individuals moving or not, but flickering is definitely not helping ([read more](https://gameaccessibilityguidelines.com/avoid-flickering-images-and-repetitive-patterns/)). It might be a false flag on our part, but I'd rather err on the side of caution in these kind of issues. 

Therefore, if I'm to understand that https://github.com/godotengine/godot/pull/93256 is necessary for some fonts to function correctly and fixing the remaining issues isn't feasible, I'm in favor of exposing the original behavior. In addition, maybe the AUTO subpixel positioning could be made more aggressive? It seems to only take effect on sizes [no game should probably even use](https://learn.microsoft.com/en-us/gaming/accessibility/xbox-accessibility-guidelines/101#text-size).

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
