### PR TITLE
Implement visibility_condition for Node3D and CanvasItem.

### PR DESCRIPTION
**Pull request by EMBYRDEV**
Implements https://github.com/godotengine/godot-proposals/issues/3433.

image

Also makes CanvasItems visibility testing a little cleaner.

I have seen #56446 and believe that this is a less intrusive solution to the problem of level design markup. 

The "Runner Only" mode may also be useful for things like intrusive post-processing/fog-volumes/effects that you might not always wish to see in-editor.

When a node is hidden in the editor, it will show with an open eye that is greyed out, signifying to the user that the node is actually marked visible but that is overriden at the moment.

image

### CODE REVIEW

**Comment by dalexeev** [comment]
There should probably be a better name (`visibility_mode`?). `visibility_condition` sounds like an expression that is evaluated to determine if a node should be shown.

**Comment by EMBYRDEV** [comment]
> `visibility_mode`

That was also my first name choice but some nodes such as TouchScreenButton already use visibility_mode. I wanted to minimise breaking changes with this PR.

**Comment by EMBYRDEV** [comment]
image

I have added a debug option that allows developers to view editor only nodes in the running project.

**Comment by dalexeev** [comment]
> but some nodes such as TouchScreenButton already use visibility_mode

Yes, in this case we are forced to choose some other name. Perhaps there is another option that is still better than `visibility_condition`. For example `visibility_flags` (but this also changes the enum values). Or something different.

**Comment by EMBYRDEV** [comment]
Appologies for the commit spam, still working this all out, I will close and reopen a squashed PR when I this passes checks.

**Comment by dalexeev** [comment]
New PR: #77301.

**Pull request closed without merging**
