### PR TITLE
Fix TileSet Editor polygon point grabbing

### LINKED ISSUE #34001: TileSet Editor: Polygon point grabbing does not take into account zoom level.
**Godot version:**
3.2

**OS/device including version:**
Reproduced on Windows 10 and Arch Linux

**Issue description:**
When working with polygons in the tileset editor, the current zoom level is not taken into account when detecting the grabbed point. Makes editing very small tiles (e.g. 3x3 pixel tiles) extremely laborious as the user must click somewhere outside the active tile and make hopeful guesses about which anchor point the algorithm will ultimately select for them.

Also causes an annoyance when creating a new shape with more than 4 points, where the polygon will be prematurely closed when the user tries to create a point too close to the starting point.

**Steps to reproduce:**
Create a tileset with a very small subtile size (e.g. 3x3). Zoom all the way in and try creating/editing some polygons. Reproduction project has a polygon created on the Collision page.

image

**Minimal reproduction project:**
[TileSetPointGrabDistance.zip](https://github.com/godotengine/godot/files/3905609/TileSetPointGrabDistance.zip)

**Workarounds**
Can be sort of worked around currently by setting **editors/poly_editor/point_grab_radius** to 1 but it will still be a little fiddly.

### PR DESCRIPTION
**Pull request by norton-corbett**
Fixes #34001

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you amend the commit log to be more explicit? It's good to mention the issue it fixes, but that's not enough to tell a `git log` reader what the commit actually solves. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by norton-corbett** [comment]
I'm new to git and not sure how to do that. I've done a 'git commit --amend' in my local repo, what now?

**Comment by akien-mga** [comment]
That's good, now you should use `git push --force` to update your remote branch with that amended commit. See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by norton-corbett** [comment]
Done, thanks for the help. and I'll be sure to read this doc.

**Review by KoBeWi — COMMENTED** [review]
It doesn't seem to be handling lower zooms well:
tkWX8LLfaZ

This is on 1:1 (default zoom). This worked fine originally.

**Comment by norton-corbett** [comment]
This is because the points were being iterated sequentially and we were breaking out of the loop as soon as we found a point that was "close enough", rather than actually finding the closest point.

I suppose this just wasn't noticeable before at lower zoom levels because the point_grab_radius setting wasn't being scaled properly in the first place.

By the way this code is in dire need of a refactor! Debugging a ~500 line function is not fun. But that's another issue :)

**Review by KoBeWi — COMMENTED** [review]
Seems to work now. Code looks good too, although maybe you should change `distance_to` to `distance_squared_to`, because the latter avoids unnecessary `sqrt` call.

**Comment by norton-corbett** [comment]
For consistency I was using `AbstractPolygon2DEditor` as a reference which also uses `distance_to`. I suppose the code should really be shared between these modules but that would require a bigger change, and probably for someone with more experience with the codebase :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
