### PR TITLE
Change icon for position key

### PR DESCRIPTION
**Pull request by KoBeWi**
Before

After
~~https://github.com/godotengine/godot/assets/2223172/340a6b54-32ac-4ea7-b950-f130bfa9eb10~~
image

### CODE REVIEW

**Review by ryanabx — APPROVED** [review]

**Review by YeldhamDev — APPROVED** [review]

**Comment by Mickeon** [comment]
I suppose nothing much can be done for it looking more like DOS than POS, but it is an improvement

**Comment by MewPurPur** [comment]
I don't think we need to compromise like this, let me try.

**Comment by MewPurPur** [comment]
KeyTrackPosition: `<svg height="16" viewBox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><path d="M4.226 3.46a.76.76 0 0 0 0 1.078L7.46 7.775a.76.76 0 0 0 1.078 0l3.236-3.236a.76.76 0 0 0 0-1.078L8.54.225a.76.76 0 0 0-1.08 0zM8 9a3 3 0 0 0 0 6 3 3 0 0 0 0-6zm0 2a1 1 0 0 1 0 2 1 1 0 0 1 0-2zm5-2a1 1 0 0 0 0 4h-2v2h2a1 1 0 0 0 0-4h2V9zM0 9h2a2.5 2.5 0 0 1 0 5v2H0zm2 3.5a1 1 0 0 0 0-2z" fill="#e0e0e0"/></svg>`

KeyTrackRotation: `<svg height="16" viewBox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><path d="M4.226 3.46a.76.76 0 0 0 0 1.078L7.46 7.775a.76.76 0 0 0 1.078 0l3.236-3.236a.76.76 0 0 0 0-1.078L8.54.225a.76.76 0 0 0-1.08 0zM11 7v5a3 3 0 0 0 3 3h1v-2h-1a1 1 0 0 1-1-1v-1h2V9h-2V7zm0 5a3 3 0 0 0-6 0 3 3 0 0 0 6 0zM4 9a3 3 0 0 0-3 3v3h2v-3a1 1 0 0 1 1-1h1V9zm4 2a1 1 0 0 1 0 2 1 1 0 0 1 0-2z" fill="#e0e0e0"/></svg>`

KeyTrackScale: `<svg height="16" viewBox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><path d="M4.226 3.46a.76.76 0 0 0 0 1.078L7.46 7.775a.76.76 0 0 0 1.078 0l3.236-3.236a.76.76 0 0 0 0-1.078L8.54.225a.76.76 0 0 0-1.08 0zM11 7v5a3 3 0 0 0 3 3h1v-2h-1a1 1 0 0 1-1-1V7zM3 9a2 2 0 1 0 0 4H1v2h2a2 2 0 1 0 0-4h2V9zm6 0a3 3 0 1 0 0 6h1v-2H9a1 1 0 0 1 0-2h1V9z" fill="#e0e0e0"/></svg>`

**Comment by KoBeWi** [comment]
image

**Review by akien-mga — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by fire** [comment]
I'm personally ok with it, I wonder what @TokageItLab thinks.

**Comment by TokageItLab** [comment]
I am a little concerned about the inconsistent thickness of the lines.

**Comment by MewPurPur** [comment]
Version with slightly higher thickness, should be a fair tradeoff between the descender length and the thickness of the bowl:

`<svg height="16" viewBox="0 0 16 16" width="16" xmlns="http://www.w3.org/2000/svg"><path d="M4.226 3.46a.76.76 0 0 0 0 1.078L7.46 7.775a.76.76 0 0 0 1.078 0l3.236-3.236a.76.76 0 0 0 0-1.078L8.54.225a.76.76 0 0 0-1.08 0zM8 9a3 3 0 0 0 0 6 3 3 0 0 0 0-6zm0 2a1 1 0 0 1 0 2 1 1 0 0 1 0-2zm5-2a1 1 0 0 0 0 4h-2v2h2a1 1 0 0 0 0-4h2V9zM0 9h2a2.7 2.7 0 0 1 0 5.4V16H0zm2 3.7a1 1 0 0 0 0-2z" fill="#e0e0e0"/></svg>`

**Comment by KoBeWi** [comment]
image

**Review by TokageItLab — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
