### PR TITLE
[EditorFileDialog] Do not update file selection on filter change if nothing was previously selected.

### LINKED ISSUE #100077: [Regression] When selecting a folder in the project import window, the first file\folder is selected
### Tested versions

Happens in 4.4 dev6
Does not happen in 4.4 dev5

### System information

Godot v4.4.dev6 - Windows 10.0.19045 - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 threads)

### Issue description

When navigating through folders, in the window for selecting an imported project, or in the window for selecting a directory for a new project, the first folder or file is selected.
_Looks like we need dev7_.

### Steps to reproduce

1. Open the project manager
2. Click the Create a new project or import button
3. Navigate through the folders
4. The first file or folder is selected

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/100077

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by JekSun97** [comment]
@bruvzg  This issue is still present in dev7 :/

**Comment by vPumpking** [comment]
was the patch uneffective?

**Comment by akien-mga** [comment]
The fix was merged after dev7 was released, so that's normal, you'd need to test the `master` branch or wait for beta1.

**Pull request merged**
