### PR TITLE
[MinGW] Remove unused WinAPI includes/defines from RVO2.

### LINKED ISSUE #36104: fatal error: SDKDDKVer.h: No such file or directory (when cross-compiling for Windows with Mono on Linux using MinGW)
**Godot version:**
master
**OS/device including version:**
Arch Linux
**Issue description:**
When cross-compiling for Windows with Mono (maybe also without?) on Arch Linux using mingw, I get this error (also tried it with clean build `git clean -xqf`)
**Output:**
```Swift
[user@archlinux git] $ ./godot_compile
Already up to date.
Mono
Build temporary windows binary
scons: Reading SConscript files ...
Configuring for Windows: target = debug, bits = default
Using MinGW
Checking for `thread_local` support ... supported
Found Mono root directory: / run / media / user / user / git / mono / dependencies / mono-64
Checking for C header file mntent.h ... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Linking Static Library ==> modules / libmodule_gdscript.windows.tools.64.a
[Initial build] Compiling ==> thirdparty / rvo2 / src / Agent.cpp
[Initial build] Compiling ==> thirdparty / rvo2 / src / KdTree.cpp
In file included from thirdparty / rvo2 / src / Agent.h: 40,
                 from thirdparty / rvo2 / src / Agent.cpp: 33:
thirdparty / rvo2 / src / API.h: 42: 10: fatal error: SDKDDKVer.h: No such file or directory
   42 | #include <SDKDDKVer.h>
      | ^ ~~~~~~~~~~~~
compilation terminated.
In file included from thirdparty / rvo2 / src / KdTree.h: 39,
                 from thirdparty / rvo2 / src / KdTree.cpp: 33:
thirdparty / rvo2 / src / API.h: 42: 10: fatal error: SDKDDKVer.h: No such file or directory
   42 | #include <SDKDDKVer.h>
      | ^ ~~~~~~~~~~~~
compilation terminated.
[Initial build] Compiling ==> modules / gdnavigation / gd_navigation_server.cpp
[Initial build] Compiling ==> modules / gdnavigation / nav_map.cpp
[Initial build] Compiling ==> modules / gdnavigation / nav_region.cpp
[Initial build] Compiling ==> modules / gdnavigation / navigation_mesh_editor_plugin.cpp
In file included from thirdparty / rvo2 / src / KdTree.h: 39,
                 from modules / gdnavigation / nav_map.h: 38,
                 from modules / gdnavigation / nav_map.cpp: 31:
thirdparty / rvo2 / src / API.h: 42: 10: fatal error: SDKDDKVer.h: No such file or directory
   42 | #include <SDKDDKVer.h>
      | ^ ~~~~~~~~~~~~
compilation terminated.
[Initial build] scons: *** [thirdparty / rvo2 / src / Agent.windows.tools.64.o] Error 1
Compiling ==> modules / gdnavigation / navigation_mesh_generator.cpp
scons: *** [thirdparty / rvo2 / src / KdTree.windows.tools.64.o] Error 1
scons: *** [modules / gdnavigation / nav_map.windows.tools.64.o] Error 1
In file included from thirdparty / rvo2 / src / KdTree.h: 39,
                 from modules / gdnavigation / nav_map.h: 38,
                 from modules / gdnavigation / gd_navigation_server.h: 36,
                 from modules / gdnavigation / gd_navigation_server.cpp: 31:
thirdparty / rvo2 / src / API.h: 42: 10: fatal error: SDKDDKVer.h: No such file or directory
   42 | #include <SDKDDKVer.h>
      | ^ ~~~~~~~~~~~~
compilation terminated.
scons: *** [modules / gdnavigation / gd_navigation_server.windows.tools.64.o] Error 1
In file included from thirdparty / rvo2 / src / KdTree.h: 39,
                 from modules / gdnavigation / nav_map.h: 38,
                 from modules / gdnavigation / nav_region.cpp: 33:
thirdparty / rvo2 / src / API.h: 42: 10: fatal error: SDKDDKVer.h: No such file or directory
   42 | #include <SDKDDKVer.h>
      | ^ ~~~~~~~~~~~~
compilation terminated.
scons: *** [modules / gdnavigation / nav_region.windows.tools.64.o] Error 1
Ranlib Library ==> modules / libmodule_gdscript.windows.tools.64.a
scons: building terminated because of errors.
[user@archlinux git] $
```

**Steps to reproduce:**
```
cd godot && \
git pull && \
echo 'Mono' && \
echo 'Build temporary windows binary' && \
scons p=windows tools=yes module_mono_enabled=yes mono_glue=no mono_static=yes copy_mono_root=yes mono_prefix='/run/media/user/user/git/mono/dependencies/mono-64' -j 8 && \
echo 'Generate glue sources for windows' && \
wine bin/godot.windows.tools.64.mono.exe --generate-mono-glue modules/mono/glue && \
echo 'Windows' && \
scons p=windows target=release_debug tools=yes module_mono_enabled=yes mono_static=yes copy_mono_root=yes mono_prefix='/run/media/user/user/git/mono/dependencies/mono-64' -j 8 && \
scons p=windows target=release_debug tools=no module_mono_enabled=yes mono_static=yes copy_mono_root=yes mono_prefix='/run/media/user/user/git/mono/dependencies/mono-64' -j 8 && \
```

### PR DESCRIPTION
**Pull request by bruvzg**
Remove unused and conflicting WinAPI defines to fix MinGW cross-build, and unused `RVO.h` header (part of RVOSimulator).

Fixes https://github.com/godotengine/godot/pull/34776#issuecomment-584569637.
Fixes #36104.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Calinou** [comment]
Could this be sent upstream as well? (Is it still active?)

**Comment by AndreaCatania** [comment]
Are you sure that this doesn't lead to incorrect RVO behaviour on Windows?

**Comment by bruvzg** [comment]
> If relevant, could this be sent upstream as well if it's still active?

It's last update in 2016.

> Are you sure that this doesn't lead to incorrect RVO behaviour on Windows?

I have tested demo project form the #34776 top comment on macOS and Windows and didn't notice any difference.

`SDKDDKVer.h` - used to define `_WIN32_WINNT`, that's already defined by Godot build config.
` NOMINMAX` - disables deprecated macros, already defined by Godot build config.
`windows.h` with significant portion of it disabled by `WIN32_LEAN_AND_MEAN` and `NOxxx` - not sure why it's there.
`__declspec()`s - only used if RVO is built as Windows `.dll`. 
`_USE_MATH_DEFINES` - used to define `M_` constants, but non of these are used in the RVO.

**Review by AndreaCatania — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
