### PR TITLE
Convert TileSet Atlas Merge input images to RGBA8 to match output, if needed

### LINKED ISSUE #80870: RGB8 images not shown or copied when TileSet Atlas Merge
### Godot version

v4.2.dev3.official [013e8e3af]

### System information

Windows 11, Core i5-12400F, RX 6600

### Issue description

Any images without transparency become RGB8.
Any images with transparency become RGBA8.

When doing a TileSet Atlas Merge RGB8 images do not show up in merge dialog (just empty space) and do not merge.

imageScreenshot 2023-08-21 203922

### Steps to reproduce

- merge any solid image with no transparency

### Minimal reproduction project

https://github.com/rakkarage/TestTestTest333

EDIT: Added simpler example Test2.tscn, without margin, separation, and using real default size tiles...

### PR DESCRIPTION
**Pull request by rakkarage**
closes: https://github.com/godotengine/godot/issues/80870

### CODE REVIEW

**Review by jonathandw743 — APPROVED** [review]

**Comment by jonathandw743** [comment]
This fixes a problem that has been bugging me for a while.

**Review by groud — APPROVED** [review]
LGTM.

I was a bit worried that using the result of `get_image()` could end up in the modification of something internal to the atlas source. However, it seems like `get_image()` always return a newly allocated Image object, so that should be fine.

**Comment by jonathandw743** [comment]
Yay

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.

**Comment by Griphen116** [comment]
@YuriSizov is this not included in 4.1.3?
I see you removed the cherrypick label. I'm on 4.1.3 stable and i am still having issues with the atlas merge tool.

**Comment by jonathandw743** [comment]
Idk why the cherrypick has been removed, the fix was working very well for me.

**Comment by KoBeWi** [comment]
The label is removed when after the commit is cherry-picked, so it is included in the release. Are the issues you experience the same as fixed by this PR?

**Comment by Griphen116** [comment]
@KoBeWi Yes, just experienced the same issue today that was demonstrated in the videos linked as clones of this issue. Trying to merge 2 atlases resulted in a blank atlas.

**Comment by KoBeWi** [comment]
I tested the MRP from the issue. The bug happens in 4.1.2, but it's fixed in 4.1.3. Your problem is something different, open a new issue if it doesn't exist.

**Comment by jonathandw743** [comment]
Are you sure your actually using 4.1.3?

**Comment by KoBeWi** [comment]
Yes.

**Comment by jonathandw743** [comment]
I meant that for griphen

**Pull request merged**
