### PR TITLE
SCons: Disable misbehaving MSVC incremental linking

### LINKED ISSUE #77968: Subsequent builds are slower on Windows + MSVC due to linking
### Godot version

4.1.dev 72b59325cf7beba7e6e9170cf6023a079fd58672

### System information

Windows 11 22H2 - MSVC 2022 - Intel Core i9-13900K, OS and Godot repository on a fast M.2 SSD

### Issue description

Subsequent builds are slower on Windows + MSVC due to the linking step performing incremental linking, but it's counterproductive for Godot.

This is on MSVC 17.4.3 (version from early 2023):

```
1st build after cleaning all build files
[Time elapsed: 00:00:57.752]

2nd build after modifying scene/main/node.h
[Time elapsed: 00:01:30.433]

3rd build after modifying scene/main/node.h again
[Time elapsed: 00:01:27.513]

4th build after modifying scene/main/node.h yet again
[Time elapsed: 00:01:31.877]

5th build after removing bin/ folder and modifying scene/main/node.h another time
[Time elapsed: 00:00:26.683]

6th build after removing bin/, but not changing any other file
[Time elapsed: 00:00:05.874]

7th build after removing bin, not changing any other file and using progress=no (Windows console I/O is slow :))
[Time elapsed: 00:00:05.559]
```

Updating to MSVC 17.6.2 (latest version available as of June 2023) improves the situation somewhat, but it's still much slower until you remove `bin/`:

```
1st clean build
[Time elapsed: 00:00:51.550]

2nd build after modifying scene/main/node.h
[Time elapsed: 00:00:54.424]

3rd build after modifying scene/main/node.h again
[Time elapsed: 00:00:54.931]

4th build after removing bin and modifying scene/main/node.h again
[Time elapsed: 00:00:23.995]

5th build after removing bin, but not changing any other file
[Time elapsed: 00:00:05.793]
```

This behavior does not occur on Linux with GCC + mold. Link times are consistent regardless of whether the `bin/` folder was previously erased. Removing all `**/*.a` files also does not impact total build time.

### Steps to reproduce

Use `git clean -dfxi` to remove all build files before compiling (only the first time).
- Using MSVC 2022 on Windows, perform a clean build of Godot using it: `scons dev_build=yes scu_build=dev`.
- Modify `scene/main/node.h` to add a line break at the beginning of the file.
- Build again and compare the build time.
- Modify `scene/main/node.h` again to add a line break at the beginning of the file.
- Build again and compare the build time for a second time
- Remove the `bin/` folder, modify `scene/main/node.h` yet another time then build again. Compare the build time.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #77968.

Testing welcome from MSVC users, to see both whether you could reproduce #77968 and confirm this fixes it, or if you couldn't reproduce it, confirm that it speeds up or doesn't slow down your linking time.

### CODE REVIEW

**Review by lawnjelly — APPROVED** [review]

**Comment by YuriSizov** [comment]
I've repeated my experiment from [here](https://github.com/godotengine/godot/issues/77968#issuecomment-1581170298). I used the same commit and applied this change directly. It resulted in subsequent builds being twice as fast as before (45-50 seconds faster).

```
Fresh build (reset using git clean -dfxi)
[Time elapsed: 00:02:30.193]

1 new line 🧛
[Time elapsed: 00:00:45.407]

2 new lines 🧛🧛
[Time elapsed: 00:00:44.263]

3 new lines 🧛🧛🧛
[Time elapsed: 00:00:44.248]

4 new lines 🧛🧛🧛🧛
[Time elapsed: 00:00:44.745]

Empty build (no changes compared to above)
[Time elapsed: 00:00:06.146]
```

Out of curiosity I've removed the patch, and it's the same as before with noticeably longer linking times:

```
Fresh build (reset using git clean -dfxi)
[Time elapsed: 00:02:01.338]

1 new line 🧛
[Time elapsed: 00:01:33.458]

2 new lines 🧛🧛
[Time elapsed: 00:01:35.264]

3 new lines 🧛🧛🧛
[Time elapsed: 00:01:38.123]

4 new lines 🧛🧛🧛🧛
[Time elapsed: 00:01:34.067]

Empty build (no changes compared to above)
[Time elapsed: 00:00:06.188]
```

I'm not sure why the initial build is slightly slower now, but that's a fair trade-off if that's what we have for subsequent builds. (Note that in the linked issue my initial time is way too slow because I wasn't plugged in until mid-through the build.)

**Review by YuriSizov — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]

**Comment by darksylinc** [comment]
This PR may have caused issues when compiling with:

```bash
scons p=windows vsproj=yes optimize=none debug_symbols=True tests=False dev_mode=True dev_build=True
```

I keep getting silly errors like this one:

```
console_wrapper_windows.windows.editor.dev.x86_64.obj : warning LNK4099: PDB 'vc140.pdb' was not found with 'console_wrapper_windows.windows.editor.dev.x86_64.obj' or at 'C:\Projects\Godot\godot\bin\vc140.pdb'; linking object as if no debug info
LINK : error LNK1218: warning treated as error; no output file generated
scons: *** [bin\godot.windows.editor.dev.x86_64.console.exe] Error 4099
```

**Comment by anvilfolk** [comment]
I had this error exactly. Just tried recompiling a few days later (with no changes other than a restart), and got:

`platform\windows\joypad_windows.cpp: fatal error C1041: cannot open program database 'C:\dev\godot\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FSplatform\windows\vulkan_context_win.cpp: fatal error C1041: cannot open program database 'C:\dev\godot\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS`

Then recompiled again and it worked.

**Comment by lawnjelly** [comment]
Sounds like it does indeed needs the `/fs` option (force synchronous PDB writes), as the error messages suggests.
https://learn.microsoft.com/en-us/cpp/build/reference/fs-force-synchronous-pdb-writes?view=msvc-170 

It could be e.g. a timing error with multiple `cl.exe` trying to write to the same PDB at the same time, and the timing will have changed without incremental linking.

**Comment by bruvzg** [comment]
> Sounds like it does indeed needs the /fs option (force synchronous PDB writes), as the error messages suggests.

We do already set it, it's useless. The error seems to be from the linker not form `cl.exe`.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
