### PR TITLE
Adds Vector.angle_to(Vector other), fixes #3912

### LINKED ISSUE #3912: Where is Vector3.angle_to ?
Vector2.angle_to( Vector2 ) is a possible function, a useful onetoo.
So where is Vector3.angle_to( Vector3 ) ?
It isn't very complicated to implement, I don't know how the Vector2 one is made but the one I custom-make constantly works like this:

`cos(a.dot(b) / (a.length() * b.length()))`

EDIT: A more efficent way to do this;
`acos( a.dot(b) / sqrt(a.length_squared() * b.length_squared()) )`
(Thanks @bojidar-bg )

Also cos should be acos instead, sorry typo

### PR DESCRIPTION
**Pull request by J08nY**
Adds Vector.angle_to(Vector other), fixes #3912

### CODE REVIEW

**Review by akien-mga — CHANGES_REQUESTED** [review]
You're using mixed tabs and spaces, fixing the indent is good but it should be done 100% with tabs :)

**Comment by J08nY** [comment]
Oh yeah, will fix. Happens when using editors with different settings and they get kinda confused :smile:

**Comment by J08nY** [comment]
Pushed the fixed indent. Also this brings a question, should the godot repo adopt a well-defined c++ coding style and use a formatter to check and format the repo?

**Comment by akien-mga** [comment]
> Also this brings a question, should the godot repo adopt a well-defined c++ coding style and use a formatter to check and format the repo?

Yes: #3916

**Pull request merged**
