### PR TITLE
Add ByteArray

### PR DESCRIPTION
**Pull request by cjmxp**

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks, but could you explain why you want this added? And why as a module instead of a core type?
AFAIK we already have a ByteArray class, so why add a new one? https://github.com/godotengine/godot/search?utf8=%E2%9C%93&q=ByteArray

**Comment by cjmxp** [comment]
请问你是中国人么? 我英文实在是太差了,首先内部的"  typedef DVector<uint8_t> ByteArray;  "
Bytearray仅仅只是个DVector<uint8_t>的别名,由于我cpp太烂所以也不敢修改内部类型,才加了这个内部ByteArray功能太少.

**Comment by cjmxp** [comment]
My English is very bad, first of all, "DVector ByteArray typedef";"
Bytearray only just DVector alias, because our CPP sucks so did not dare to modify internal type and add the function of this internal bytearray too little.

**Comment by akien-mga** [comment]
Closing, as it can't be integrated in the main tree in this state. There are bogus commits and such changes should not be made as a module but directly in the core types (and should thus be discussed with @reduz beforehand, as there are likely reasons for the way ByteArray are defined at the moment).

**Pull request closed without merging**
