### PR TITLE
Add Vertical Align for text in LineEdit

### PR DESCRIPTION
**Pull request by thimenesup**
Add Vertical Align for text in LineEdit

### CODE REVIEW

**Comment by groud** [comment]
You put the file in the wrong place, it should be in godot/scene/gui/

**Comment by thimenesup** [comment]
Not sure what github did but should be fixed now.

**Comment by hpvb** [comment]
There seem to be 5 commits on this PR now. Could you please squish them into 1?

**Comment by thimenesup** [comment]
AFAIK I can't unless I close this PR and open another one. Should I do it?

**Comment by groud** [comment]
Well, If you can't manage to squash the commits, yes, go ahead.

**Pull request closed without merging**
