### PR TITLE
Clicking on subscene icon will open it

### PR DESCRIPTION
**Pull request by kubecz3k**
All options are moved into RMB menu

subscene-click

### CODE REVIEW

**Comment by volzhs** [comment]
it might be personal preference, but I like current state.
I'm using "Enable children" on/off more often than "Open in editor".

**Comment by akien-mga** [comment]
I think it might be better to have the options specific to instance nodes be at the top of the list in the RMB menu, otherwise they're a bit harder to reach than previously.

**Comment by kubecz3k** [comment]
@akien-mga I would rather not reposition them on top, add_child_node, attach_script and couple others also are commonly used, and I think it would be better to have fixed positions for as many options as it's possible (muscle memory).
@volzhs Around week ago I made a lot smaller pr that was adding this option with double click, without removing RMB submenu. Conclusions were made that bigger changes are needed. Old implementation was working like this since it was implemented back in the past when there was no support for RMB, and more modern way is to have those options in RMB menu.

**Comment by akien-mga** [comment]
Let's go the reduz way for this one, we can fine tune it if users complain after using it:

> we can merge as is for now, if users complain we change it

**Comment by Noshyaar** [comment]
Instancing options appear when right clicking a scene root that is not inherited scene. I don't think that's supposed to happen.

**Comment by kubecz3k** [comment]
@Noshyaar Thanks for info, will fix asap

**Pull request merged**
