### PR TITLE
Clarify how 'audio/driver/output_latency' project setting works

### PR DESCRIPTION
**Pull request by benjarmstrong**
Updated docs as requested by @clayjohn in discussion for #38210.

The ambiguity surrounding this setting had me diving into the code to figure out why it didn't seem to be working, so I'm hoping this saves future users a lot of time.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

When cherry-picking for `3.x`, should I edit the "Note:" or is the state the same there? (i.e. does Windows 10 support depend on #38210?)

**Comment by benjarmstrong** [comment]
Yeah, this setting has no effect on all windows versions for 3.X

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Pull request merged**
