### PR TITLE
Add Color.from_hsv()

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/godotengine/godot/issues/15782

Adding full static function support to built-in types ("Variants") is a bigger change. However, this PR allows the following without even one change in the core:

`V.f(a, b, c)` gets transformed into `V().f(a, b, c)` if `f()` is `const` and `f()` returns `V`

Which allows us to support `Color.from_hsv` (implemented from Wikipedia):

```
func _draw():
	for s in range(180):
		for h in range(360):
			var c = Color.from_hsv(h, s / 180.0, 0.5)
			draw_rect(Rect2(Vector2(h, s), Vector2(1, 1)), c)
```

hsv

With core changes, this can be made more restrictive (only really "static" funcs may be called like above); the first step would be to add `_static` to `FuncData` and `addfunc` in `variant_call.cpp`. To make this more efficient, a special bytecode opcode could be added. Both are not strictly necessary IMHO.

### CODE REVIEW

**Comment by DeadlyLampshade** [comment]
I appreciate this pull request and definitely advocate for it. I like working with HSV.

**Comment by blurymind** [comment]
AWESOME and very useful. Hope it gets merged and even backported to 2 👍

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by TheOnlyJoey** [comment]
@hpvb Ohai, can i request this for backporting to 3.0? Using this feature for correct color generation for players using the golden ratio in the Equidistribution theorem :)

**Comment by hpvb** [comment]
@TheOnlyJoey I'll review it for 3.0.4, I don't want any new stuff in 3.0.3 now. Sorry!

**Comment by vnen** [comment]
While the function itself should be fine for cherry-picking, the static access might be a bit too much.

**Comment by hpvb** [comment]
@vnen yeah, I sometimes cherry-pick only partial commits. In this case probably only the new method

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
