### PR TITLE
Apply new input validation method for Create Plugin dialog

### PR DESCRIPTION
**Pull request by eugene87222**
- #76681 
- Add status panel to the create plugin dialog
- Remove unused info icons (for old validation)

### CODE REVIEW

**Comment by brno32** [comment]
If I'm not mistaken, instead of having a merge commit in your source branch you'll wanna rebase off of the upsteam master and squash all your commits into one.

**Comment by eugene87222** [comment]
@brno32 would you like to teach me how to merge them😢
My git tree becomes little messy right now

**Comment by brno32** [comment]
https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase

A bit simpler might be to first rebase

`$ git pull --rebase upstream master`

then squash your commits with `git rebase -i HEAD~2`

You'll need to force push after rewriting your history.

**Comment by eugene87222** [comment]
Hmm I think it would be more convenient for me to create a new PR given my current situation.
I just forgot to pull the latest code before starting to fix the issue😿. I'll remember to do it next time.

**Pull request closed without merging**
