### PR TITLE
GDScript: allow vars to be declared as "weakref"

### PR DESCRIPTION
**Pull request by ghost**
This adds transparent handling of `weakref`s by letting users declare members vars as `weakref` (you still need to check for `null` though). With this PR, the following:

```
var weakref member_ref

func f(local_ref):
    member_ref = p_ref

func g():
    if member_ref:
        h(member_ref)
```

is equivalent to:

```
var member_ref

func f(p_ref):
    member_ref = weakref(p_ref)

func g():
    if member_ref and member_ref.get_ref():
        h(member_ref.get_ref())
```

Only member vars can be declared in this way, as for local vars weakrefs usually don't make sense.

The change generalizes to all kinds of accesses, e.g. `some_instance.member_ref = abc`.

While this might seem like an esoteric,  very limited use case, it's actually an important feature if we want to have transparent weakrefs with lambas.

### CODE REVIEW

**Comment by Zylann** [comment]
Weakrefs can actually make sense in locals if you use yield. Also, declaring a member as container of weakref seems like a typed approach. I find `weakref(ref)` is fine tbh.
I like the transparent null check, but then you can't check if the var really is null anymore (which again brings closer to implicit static typing)

**Comment by raymoo** [comment]
Does `get_ref` return null if the object being pointed to has already been freed from somewhere else (This isn't documented on the docs wiki)? If so, using your suggested design could result in errors in a multithreaded environment (or when using yields like @Zylann mentioned), if a Reference thing gets freed in between the check and the code that uses the value. This could be prevented in the current design by first assigning the result of `get_ref` to a variable (thus creating a "strong reference" if the object is still alive), and then checking this new variable for being null before using it. This is similar to how C++'s weak pointers work.

**Comment by poke1024** [comment]
@raymoo Yes, `get_ref` returns `null` if the reference has gone away.

You're right that the example I give above contains a race condition in a multithreaded environment. One would need to move the null check into the called function `h` such that the dereferencing happens once (implicitly) when calling `h`, i.e.:

```
var weakref member_ref

func g():
     h(member_ref)

func h(ref):
    if ref: # this will be null or a strong ref
       ...
```

**Comment by raymoo** [comment]
@poke1024 That wouldn't solve the issue, because the thread could still be preempted between the if statement condition and if statement body.

**Comment by poke1024** [comment]
@raymoo The parameter `ref` in `h` is already a strong reference, as the conversion from weak to strong (or null) happens at the time of access to `member_ref`, i.e.  in `h(member_ref)`, at the time `member_ref` is read.

In general, to avoid race conditions with this approach, you'd always have to copy the ref to a var first, since then an implicit conversion from weak to strong has already taken place:

```
var weakref member_ref

func g():
    var strong_ref = member_ref
    if strong_ref: # ok
        ...
``` 

Let me note that this whole PR (i.e. the `weakref` keyword addition to `var`) is kind of a garbage product of https://github.com/godotengine/godot/pull/16090 and I see its main use in the context of lambdas (https://github.com/godotengine/godot/pull/16090), where some kind of mechanism might be useful to produce simple, transparent weak refs.

**Comment by raymoo** [comment]
@poke1024 Thanks for the explanation, I understand better how your approach could work now.

I would be fine with this as long as the existing weakref mechanism still exists.

**Comment by reduz** [comment]
After ff1e7cf , weakrefs don't make much sense save for rare cases, so this PR has lost it's meaning. Still, thanks for taking the work to do it!

**Comment by Zylann** [comment]
@reduz why? In GDScript, to hold a weak reference to an object that inherits Reference, the only way is to use `weakref`.

**Comment by vnen** [comment]
I'm not sure as well, `weakref` is to more to avoid cyclic references than it is about checking if an object was freed.

**Comment by akien-mga** [comment]
Reopening for now until a consensus is reached.

**Comment by mhilbrunner** [comment]
No consensus could be found for merging this in todays meeting. Main point against it was that weakrefs have become way less important after https://github.com/godotengine/godot/commit/ff1e7cfbf4b7ad9b327588ce7dffb43d31fee3e9, so improving them further isn't worth the additional complexity. Also, the reduced transparency may have downsides.

Still, thanks for your work!

**Comment by reduz** [comment]
From the discussion on irc:

The main use case for WeakRef is to tell if a node was deleted or not. Other than that users barely touch this. 

With the addition of is_instance_valid() in GDScript, using WeakRef for this lost any meaning and is only relegated for using with references, in cases where you want to do a graph structure or similar.  Given this is very corner case (users don't do this kind of stuff often at all), my point of view is that having this as a built-in script type is not really worth it. For corner cases as the ones described, explicit referencing works fine and the code is cleaner because it's clear that the member is a weak reference.

**Pull request closed without merging**
