### PR TITLE
Improve CheckButtons in the default editor theme

### PR DESCRIPTION
**Pull request by Calinou**
This replaces CheckButton images with a simpler text-free design.

**Preview:**

check_button_unchecked_default_1x
check_button_checked_default_1x

check_button_unchecked_light_1 5x
check_button_checked_light_1 5x

check_button_unchecked_godot-2_2x
check_button_checked_godot-2_2x

### CODE REVIEW

**Comment by girng** [comment]
colors might be confusing because hard to tell which one is off or on. and left/right. text variant is  simpler imo

**Comment by Calinou** [comment]
@girng Perhaps a localizable on/off text could be added next to CheckButtons, similar to the recommendations in the [Windows 10 design guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles).

**Comment by YeldhamDev** [comment]
Could you also fix this #15584?

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and *release freeze* for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

**Comment by toger5** [comment]
I really like the design. I also think, it is fairly easy to tell what is on and off. 
Even the left/right position is almost enough to tell if it is on/off.

**Comment by akien-mga** [comment]
Let's give it a try and see how users like it :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
Gnome recently made a similar change, and they decided to make the "On" buttons colored (rather than just white) to distinguish their status. 

I'm not sure if this would be a good idea for Godot, since the background already has a color of blue, it might blend in to have a blue button, and other colors would look out of place. But just in case people find it confusing, here's an idea to discuss.

**Pull request merged**
