### PR TITLE
Improve space management for EditorFileDialog

### PR DESCRIPTION
**Pull request by vPumpking**
Move buttons related to the file view on the container above so that they take less horizontal space and make search bar similar to the one in FileDialog

see #97344 and #88673

### CODE REVIEW

**Comment by vPumpking** [comment]
I noticed a problem with the makedir button: on my screen, It's off the window due to the dir field being too large, but i can't find why
image

**Comment by vPumpking** [comment]
I will fix the check errors in 1 or 2 days

**Comment by TheYellowArchitect** [comment]
May be related with https://github.com/godotengine/godot/issues/97886

**Comment by vPumpking** [comment]
checks need a restart

**Comment by AThousandShips** [comment]
Please rebase to fix a CI problem

**Comment by vPumpking** [comment]
I'll have to report it to tomorrow

**Comment by AThousandShips** [comment]
Report?

**Comment by vPumpking** [comment]
This branch was based on the wrong repository

**Pull request closed without merging**
