### PR TITLE
convert Remove All Theme Items icon colors from Godot 4 to Godot 3

### PR DESCRIPTION
**Pull request by poyribn**
in #62559, @akien-mga found a third icon
that mistakenly had the Godot 4 colors instead of the Godot 3 colors.
this causes the icon's colors to not be adjusted in Light Theme, so i fixed it.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Since you've updated the rainbow as well, check the `icon_theme_remove_custom_items.svg` icon too. It uses the same rainbow and is likely affected as well.

**Comment by Sosasees** [comment]
> After a few PRs you're going to have a mess if you keep using your main branches.

thank you for this tip for the future.

today is my first time committing to another repository (that is maintained by someone other than me). i plan to delete my fork after fixing the icon colors.
unless more is found, there's only 1 icon left to fix.

**Comment by Sosasees** [comment]
why can't i add a EndOfFile now?

last time, opening the file in _nano_ and saving it without changes added a EndOfFile.

**Comment by YuriSizov** [comment]
Not sure, but please don't tag people in commit messages. That creates a lot of noise now, and then in future when this commit gets into other people's forks.

**Pull request closed without merging**
