### PR TITLE
Add ability to pick random value from array

### PR DESCRIPTION
**Pull request by nonunknown**
Returns a random value from the target array.
```
var array: Array[int] = [1, 2, 3, 4]
print(array.pick_random())  # Prints either of the four numbers.
```	

Implements: https://github.com/godotengine/godot-proposals/issues/3454

### CODE REVIEW

**Comment by kleonc** [comment]
Alternative PR: #65077.

**Comment by jcostello** [comment]
`pick_random` is an intuitive name, but just to let you know, other language or libraries call a similar method `sample`

**Comment by fire** [comment]
Math::rand() is not the only way of getting a random number, by default Godot picks a not so random number generator.

**Review by mhilbrunner — APPROVED** [review]
Approved in https://github.com/godotengine/godot/pull/57007, and approved in today's PR meeting :)

**Comment by mhilbrunner** [comment]
@nonunknown If you can update the docs to insert the new method's docs at the right place alphabetically, instead of the current place so CI passes, we can merge this. You can ping me once you updated it :)

**Comment by nonunknown** [comment]
@mhilbrunner I have a serious problem with commit squashing, so if I can have support for squashing I can do this now!

**Comment by mhilbrunner** [comment]
@nonunknown Sure, I can help you on RC or otherwise just squash the commits for you.

**Comment by nonunknown** [comment]
I've checked https://github.com/godotengine/godot/pull/54940 and seems it doesnt interfere on this PR anymore, so this can be approved without worries!

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks! 🎉

**Comment by theraot** [comment]
May you bring this to 3.x?

**Comment by handre-dev** [comment]
Is there any chance `PackedStringArray` and the others get `pick_random()` as well?
Don't know if it's intended but they don't inherit it from `Array`.

**Pull request merged**
