### PR TITLE
Fix Editable Children issues with node renaming, moving, duplicating and instancing.

### LINKED ISSUE #20409: Rename an "Instanced Scene as Node" disables "Editable Children"
https://github.com/godotengine/godot/commit/89e1b302b504feb1cea218adcc6fac77c8ae0052
x11

It only happen if it's a name that the node never had before.

peek 2018-07-24 15-22

### LINKED ISSUE #23979: Data in editable children lost without warning when moving node in tree
**Godot version:**
3.1.aplha. c025f52

**OS/device including version:**
Windows 10

**Issue description:**
When moving an instanced scene with editable children, the "editable children" flag is lost. Moving the scene back re-enables the flag. If scene is saved when instanced scene is in new location, all children data is lost without warning.

**Expected behaviour:**
When moving an instanced scene with editable children, all modifications are preserved.

**Actual behaviour:**
When moving an instanced scene with editable children, editable flag is lost. Child modification data is lost as soon as scene is saved to disk.

**Steps to reproduce:**
1. Instance a scene with editable children.
1. Make modification to the children. 
1. Move the instanced scene in scene tree. 
1. Save and reopen.

Probably related to #20409 and #6455.

### LINKED ISSUE #27023: Editable Children doesn't overwrite properties some times
**Godot version:** 3.1.stable

**OS/device including version:** Solus 3.9999

**Issue description:**

When merging or instantiating, but especially merging, after you enable `Editable Children` and try to modify some properties of the children, when the game loads it doesn't override them.

merging_issue

**Steps to reproduce:**
1. Create a scene with some Sprites
2. Save it
3. Instance it on another scene
4. Turn on `Editable Children`
5. Change its `position`
6. Create a new scene
7. Merge the instanciated scene from step 3
8. Test the scene

### LINKED ISSUE #27064: Editable Children Flag Turns Off Due to Node Path Change
**Godot version:**
3.1

**OS/device including version:**
OSX Latest

**Issue description:**
I changed the node path of a node that has `Editable Children` enabled, and it disabled `Editable Children`. The edits made to the children do not change, but the child nodes are not accessible anymore. If I turn `Editable Children` back on, everything seems to go back to normal since the children node states are somehow preserved.

For example, if I enable `Editable Children` on a node, and I edit one of the children, the edit is preserved despite `Editable Children` being disabled from changing the path.

**Steps to reproduce:**
1. Open a Godot file
2. Make a new scene, say `Scene A`
3. Make new scene, say `Scene B`, and instance A in it
4. Enable `Editable Children` for the `Instance A` in `Scene B`
5. Change the name of `Instance A` in `Scene B`.
6. (Alternative to 5) Change the name of a parent node for the `Instance A` in `Scene B`

Expected: The name changes and that's it
Actual: The name changes, but `Editable Children` gets disabled

Edit:
As a side note, I'm having a hard time finding documentation for what `Editable Children` actually does. The inspector properties are all red, I don't know what that means. I don't know the limitations to `Editable Children` either.

### LINKED ISSUE #28861: Editable children property persists after node deletion
**Godot version:**
3.1.1

**Issue description:**
Editable children property is stored as NodePaths in scene root and they aren't removed/updated on node move/update, which leads to unexpected results (like #20409).

**Steps to reproduce:**

1. Create a scene (e.g. SceneA.tscn)
2. Create another scene (e.g. SceneB)
3. Create a main scene
4. Instance SceneA
5. Toggle editable children of SceneA
6. Delete SceneA
7. Instance SceneB
8. Rename SceneB to SceneA
9. SceneB will get editable children upon rename

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/3175254/ReproductionProject.zip)
Initial setup for point 3 in steps to reproduce.

### PR DESCRIPTION
**Pull request by hilfazer**
Hopefully fixes all the issues on KoBeWi`s tracker:
https://github.com/godotengine/godot/issues/33790

I'm aware it won't get merged to 3.2 but 4.0 is too unstable ATM to work with. Also i didn't managed to compile it yet.

I'm putting it here so people can test it properly. I did some testing myself but there's only so much one person can test (:

*Bugsquad edit:*
Fixes #28861
Fixes #27064
Fixes #23979
Fixes #20409
Fixes #27023

### CODE REVIEW

**Review by KoBeWi — COMMENTED** [review]
You could remove the first argument from `set_editable_instance` to simplify code a lot. Instead of
```
EditorNode::get_singleton()->get_edited_scene()->set_editable_instance(node, false);
```
you could do

```
node->set_editable_instance(false);
```
Same with `is_editable_instance`.

Aside from that, the code looks ok. Still, I assume there was a reason to keep editable instances in scene root instead of a property, so we should ask @reduz about that first.

EDIT:
So this is what he said on IRC:
> I think this also ensures that editable is per scene and not per subscene. If you instantiate a scene that instantiates a scene using editable children, there is no point in propagating that

**Comment by hilfazer** [comment]
@KoBeWi Sure, i can do that.
But what about an error check from `Node::set_editable_instance(Node *p_node, bool p_editable)`?

`ERR_FAIL_COND(!is_a_parent_of(p_node));`

Put it before that `node->set_editable_instance(false);` ?

**Comment by KoBeWi** [comment]
Not sure if this check is necessary. But yeah, you can put it before that.

**Comment by hilfazer** [comment]
I think i'll skip renaming those methods. `is_editable_instance` is called in many places and i'd need to make sure there's a check for `nullptr` everywhere. Too big potential for a mistake.

The less i'll change the less i'll break.

**Comment by hilfazer** [comment]
As for reduz's comment (assuming i understood correctly) - my implementation keeps the desired behaviour in following cases:
- instancing an inherited scene
- instancing a scene that contains an instanced scene

but doesn't do the right thing in one case
- merging from a scene  that contains an instanced scene (a subscene)

Editable Children checkbox gets propagated if you merge. Which leads to a nasty bug where a node has 2 children with same names. I'll see what i can do about it.

**Comment by hilfazer** [comment]
I've changed Subscene Editor so it clears `editable children` checkbox when reparenting nodes.

**Comment by KoBeWi** [comment]
Someone brought up the issue on Twitter, so I took another look at this PR.

I think I understand what problem reduz mentioned (but not why is this a problem, heh). Here's a small project that displays this:
[ReproductionProject.zip](https://github.com/godotengine/godot/files/5422883/ReproductionProject.zip)

It has SceneA, SceneB instancing SceneA with editable children and SceneC instancing SceneB.

Now, when you go to SceneC and turn on editable children in the SceneB instance:
- without this PR, only SceneB will have editable children. In the tscn file you will see
```
[editable path="SceneB"]
```
- with this PR, SceneA will also have editable children, because it was saved in the instance. In the tscn file you will see
```
[editable path="SceneB"]
[editable path="SceneB/SceneC"]
```

To prevent this, when instancing a scene, we should check whether its parent (ancestor) is an instance. If it's an instance and doesn't have editable children enabled, discard the editable children for this node.

**Comment by KoBeWi** [comment]
Ok, so this is impossible. The editable instances are set when PackedScene is being instanced and it doesn't know yet whether it has parent scenes. So we'd have to clear the editable instances from parent scene (i.e. a scene instances and checks if child scenes have editable instances they shouldn't have).

But IMO this is much less severe issue than what this PR fixes. I have a pretty big project and never had a scene that would reproduce the "problem" caused by the PR. And even if I had, this doesn't sound like something serious. And the way the editable children are handled currently can lead to data loss, which is rather bad.

**Comment by PLyczkowski** [comment]
> And the way the editable children are handled currently can lead to data loss, which is rather bad.

Can confirm data loss occurring in day-to-day work with how it's set up currently.

**Comment by hilfazer** [comment]
> 

> EDIT:
> Also
> 
> > I've changed Subscene Editor so it clears editable children checkbox when reparenting nodes.
> 
> What does it exactly mean? It doesn't sound like something desired.

I made a video to explain that:
https://www.dropbox.com/s/133x1asor6cwytp/GodotEditChldrnMergeFromScene.mp4?dl=0

"Subscene Editor" is used when the user chooses "Merge from Scene" and selects a scene to merge from. A window names "Select node(s) to import" appears. By "reparenting" i meant moving nodes from that new window to the Scene tab.

I did that in order to prevent the very problem you've described for "Merge from Scene" case. But as we can see from the video it doesn't work properly with multiple instantation levels. I'll see what i can do about it.

**Comment by KoBeWi** [comment]
This looks the same as the issue I mentioned in https://github.com/godotengine/godot/pull/39533#issuecomment-714474715
If you can fix this then ok, but it's not necessary to do in this PR.

**Comment by hilfazer** [comment]
I've added a `recursive_disable_editable_children()` function that unchecks "editable children" in all nodes added with "Merge From Scene" option. Now merging nodes with multiple levels of instantation won't propagate their "editable children" setting.

And... i've found an inconsistency with "Merge From Scene" in Godot 3.2.1 stable. The video will explain it better than i ever could:
https://www.dropbox.com/s/tqjgux6hhsfrvp7/Godot321InconsistentMergeFromScene.mp4?dl=0

With my recent change all those checkboxes are unchecked every time.

**Comment by KoBeWi** [comment]
> And... i've found an inconsistency with "Merge From Scene" in Godot 3.2.1 stable.

That's #28861

**Comment by KoBeWi** [comment]
I checked if this PR fixes all issues from my tracker and seems like it doesn't fix #27023

When merging from other scene, the editable children should be preserved, because it's the same as copy-pasting a node to another scene.

**Comment by hilfazer** [comment]
Ok, so i've reverted any changes specific to "Merge From Scene".
I went through all issues from the tracker to make sure they are all fixed (i've checked that on 3.2.4 beta build).

**Review by KoBeWi — APPROVED** [review]
This should be ok now.

Here's a patch for master:
[Patch.zip](https://github.com/godotengine/godot/files/5446306/Patch.zip)
Just use `git apply file.patch` and open a new PR against master. Although I'd wait for @reduz to approve it too. I explained him on IRC how this works and he said that it should be fine (the change is fully backwards compatible and doesn't change how the information is stored in scenes).

**Comment by djrain** [comment]
So I just discovered a related problem in my project and I don't know whether this PR addresses it or not. 

Basically I have a level editor scene where I use PackedScene.pack() to save out arbitrary branches of the tree (and leave that branch there, local, for further editing, as opposed to "save branch as scene"). I recursively loop over all the node's subnodes and set their owner so PackedScene will include them. 

The problem is that in the freshly saved scene, any instances are now expanded (I can see and edit the children). Almost as if I manually checked "editable children" on the instance, except that this box is still unchecked, and the subnode names are not greyed out as they would normally be (though their inspector properties do display in red). And if I then try to check editable children, new children get added and I have duplicate node names.

 Is this a known problem, or should I open a new issue?

**Comment by KoBeWi** [comment]
> Is this a known problem, or should I open a new issue?

It's not even a bug. All nodes whose owner is the scene root will have their children visible. Instanced scenes have owner pointing to themselves instead of the scene root, hence their children are hidden by default. The "editable children" property basically exists so that instanced nodes could have their children displayed, even if their owner is different.

From what you say, all your nodes have the same owner, so it's natural that they all show.

**Comment by djrain** [comment]
> Instanced scenes have owner pointing to themselves instead of the scene root, hence their children are hidden by default. 

I was under the impression that a node had to have the edited_scene_root as its owner, otherwise it wouldn't be visible at all? Perhaps you can tell me how to accomplish this, as I don't see how one can make instances own themselves after packing the scene.

And aren't subnodes of an instance supposed to always have their names greyed out? If so, this is buggy because they are still white after the save. And the children with identical names aspect is a bug, although I suppose that's been addressed already...?

**Comment by hilfazer** [comment]
> 
> 
> > Instanced scenes have owner pointing to themselves instead of the scene root, hence their children are hidden by default.
> 
> I was under the impression that a node had to have the edited_scene_root as its owner, otherwise it wouldn't be visible at all? Perhaps you can tell me how to accomplish this, as I don't see how one can make instances own themselves after packing the scene.
> 
> And aren't subnodes of an instance supposed to always have their names greyed out? If so, this is buggy because they are still white after the save. And the children with identical names aspect is a bug, although I suppose that's been addressed already...?

Sibling nodes with same name is indeed a bug and it's been reported: https://github.com/godotengine/godot/issues/31744
The bug reporter has came up with a solution and asked reduz and Akien for guidance.

This PR isn't addressing that problem.

**Comment by akien-mga** [comment]
We'll need a `master` PR with those changes before this can be considered for merging, as we don't fix bugs in `3.2` to keep them in future releases.

**Review by akien-mga — APPROVED** [review]
Master PR: #45265.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
