### PR TITLE
Add optional default value to `get_meta()`

### LINKED ISSUE #2383: Allow get_meta() return default value similar to Dictionary.get()
### Describe the project you are working on
Game using GDScript

### Describe the problem or limitation you are having in your project
I use object metadata quite a lot. My problem is that `get_meta()` throws an error when given meta doesn't exist. This is often inconvenient, because I have to add `has_meta()` in a way that makes the code more ugly.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
`get_meta()` could take second argument, in which case instead of error that value would be returned (just like `Dictionary.get()`). Alternatively, if erroring non-existent metas is desired, new `get_meta_or_default()` method could be added.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Let's say I want to add a meta property when a projectile hits an object. It will be used by this specific projectile, so there's no reason to add a regular property. Also this meta will be increased with each hit.

Currently the code has to be either
```
var hit_bonus = 0
if object.has_meta("hit_bonus"):
  hit_bonus = object.get_meta("hit_bonus") + 1
object.set_meta("hit_bonus", hit_bonus)
```
or
```
if object.has_meta("hit_bonus"):
  object.set_meta("hit_bonus", object.get_meta("hit_bonus") + 1)
else:
  object.set_meta("hit_bonus", 1)
```

While with my proposal it could just be
```
var hit_bonus = object.get_meta("hit_bonus", 0)
object.set_meta("hit_bonus", hit_bonus)
```
It's twice shorter.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Well, it can, but I'd use it relatively often.

### Is there a reason why this should be core and not an add-on in the asset library?
You can't extend existing types and alternative would be some utility singleton.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/2383

### CODE REVIEW

**Comment by Calinou** [comment]
I'd prefer to add an optional third argument to `get_meta()`, which would be more similar to `Dictionary.get()`.

**Comment by KoBeWi** [comment]
> get_meta_or_null() 

I don't think having such method makes sense. We have `get_node_or_null()` because you can literally only return either node or null. In case of Dictionary or meta, the default value can be any Variant. And returning `null` in case of missing value means that you have to add more code if you want a different default.

> Having a separate method is warranted for having get_meta_or_null() in the future (once we make get_meta() return an error when the value doesn't exist and no default is specified).

This basically means that we'd add `get_meta_or_null()` just to have a version of `get_meta()` with `null` default value that doesn't throw error. Instead of having two methods with default for such a weird reason, it's better to have one.

**Comment by EricEzaM** [comment]
> As mentioned in the PR review, that doesn't cover the use case that get_meta_or_default(meta, null) would, but we thought that this specific use case doesn't necessarily need to be supported (and can be handled with has_meta).

Tbh I think the `_or_default` method is useful and covers a lot of cases. Searching for `has_meta(` in the code base returns a number of results where this new method could be used to simplify the code. I think adding a param to `get_meta` (as described in quoted text above) but not having it work (without error) 100% of the time is a bit of a half measure.

**Comment by KoBeWi** [comment]
> adding the default value to get_meta itself

Done.

**Comment by akien-mga** [comment]
Does this need a rebase after #59452 or is it fine as is?

**Review by akien-mga — APPROVED** [review]
Approved based on what we discussed last time.

**Comment by KoBeWi** [comment]
Tested, still works.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
