### PR TITLE
Mono/C#: WebAssembly and initial AOT support

### LINKED ISSUE #20270: Mono/C# support for HTML5
Bringing Mono/C# to the HTML5 platform will probably come only after #20267 and #20268, but opening this issue to keep track of what needs to be done and progress.

CC @neikeq

### PR DESCRIPTION
**Pull request by neikeq**
WebAssembly for C# is now working, although we only support the interpreter right now, which is much slower than AOT.

Initial AOT compilation support was added for other platforms. There's still more work to do here. We do not support LLVM yet (although you may experiment with that using the "Extra Aot Options" setting).

More info will come once I update the [Compiling with Mono](https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html) docs.

*Bugsquad edit:* Fixes #20270.

### CODE REVIEW

**Comment by CaptainStack** [comment]
Woah! Does this mean we can expect C# -> WebGL soon?

**Comment by Calinou** [comment]
@CaptainStack That's what this pull request implements :slightly_smiling_face:

**Comment by akien-mga** [comment]
As discussed with @neikeq, this should hopefully not introduce regressions for existing desktop and Android builds, so let's merge.

We likely won't ship 3.2 with AOT, but I might manage to get the WebAssembly templates in time (worked on it the past few days). AOT will be refined in master and we'll cherrypick relevant changes for a later 3.2.x release when it's ready.

**Comment by akien-mga** [comment]
Thanks!

**Comment by nhold** [comment]
Great work, I was super interested in how this was going to be done. I also really enjoyed the branch name :P.

**Pull request merged**
