### PR TITLE
Mask out shadows on CanvasItems that don't have a matching `item_shadow_mask`

### LINKED ISSUE #64939: CanvasItem light_mask is ignored by LightOccluder2D occluder_light_mask
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Ubuntu, Nvidia

### Issue description

By setting CanvasItem light_mask to a different layer than LightOccluder2D light_mask, it was possible to have shadows not being drawn on top of sprites. This does no longer work.

Godot 3:

image

Identical setup in Godot 4:

image

Especially in topdown games you generally need this to work.

### Steps to reproduce

1. Set your PointLight2D's range_item_cull_mask to cover layer 1 and 2
2. Set your Sprite2D's light_mask to 2 only
3. Add LightOccluder2D that remains on default for occluder_light_mask and light_mask (layer 1)
4. have the LightOccluder2D polygon cover (part of) the sprite
5. hit F6 and note that the shadow is rendered on top of the sprite. the shadow should not be rendered on top of the sprite as is the case in Godot 3.

### Minimal reproduction project

projects for both godot 3 and 4 to compare:

[light-occluder-sprite-bug.zip](https://github.com/godotengine/godot/files/9435066/light-occluder-sprite-bug.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/64939

Fixing this required a small amount of refactoring to move some of the per-instance flags into a new per-batch flag. This was needed to free up the required 16 bits for the shadow mask. We do the actual masking on the CPU and then just store a binary value for whether that lights shadow impacts that CanvasItem. This saves instructions in the shader.

### CODE REVIEW

**Review by huwpascoe — APPROVED** [review]
It works as intended.

**Comment by Repiteo** [comment]
Gonna need to be rebased before this can be merged

**Comment by clayjohn** [comment]
Rebased, should be good now!

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
