### PR TITLE
Rename `hint_tooltip` to `tooltip_text` & setter getter

### PR DESCRIPTION
**Pull request by Mickeon**
Okay, so...

`set_tooltip()` is the setter of `hint_tooltip`. Name technically mismatches. Alright...
However, `_get_tooltip()` is the getter of `hint_tooltip()`. Underscore, it's hidden to the Docs, probably because... it's not to be confused with `get_tooltip()`, the method that accepts the `position_at` parameter, that, as a virtual method internally, is often overridden to display a more specific tooltip.

So, let's recap. `get_tooltip()` returns the tooltip text at a specific local position, not to be confused with `_get_tooltip()`, which is the getter of `hint_tooltip()`, whose setter method is `set_tooltip()`.

So in this PR:
`hint_tooltip` -> `tooltip_text`
`set_tooltip` -> `set_tooltip_text`
`_get_tooltip` -> `get_tooltip_text`

Applies across the internal code, as well. Updates documentation, and the group name, too.

image

~This PR previously was renaming it to tooltip_hint~
~And, with this opportunity, shouldn't the previous `get_tooltip` be now called _get_tooltip as well, since it's actually a **virtual** method?~

### CODE REVIEW

**Comment by KoBeWi** [comment]
`tooltip_hint` is weird. Why not `tooltip_text` or just `tooltip`?

**Comment by Mickeon** [comment]
I wanted to keep the "_hint_" in there because I thought there may be an ulterior meaning to it far beyond my understanding. But if that's a question that has been asked, I would be totally okay calling it `tooltip_text`, but not `tooltip`, to avoid confusing it with the actual PopupPanel and to allow the far more utilised `get_tooltip()` to remain as is.

**Comment by Mickeon** [comment]
I made an oopsie, reverting commit.

**Comment by Mickeon** [comment]
Good to go!

**Comment by akien-mga** [comment]
Missed occurrences (I advise using grepping tools like `ripgrep` to validate such changes, aside from refactoring tools like QtCreator's to change all symbols at once):

```
editor/plugins/packed_scene_translation_parser_plugin.cpp
126:    lookup_properties.insert("hint_tooltip");

modules/gdscript/editor/gdscript_translation_parser_plugin.cpp
44:     // Search strings in AssignmentNode -> text = "__", hint_tooltip = "__" etc.
224:            // If the assignment is towards one of the extract patterns (text, hint_tooltip etc.), and the value is a string literal, we collect the string.
333:    assignment_patterns.insert("hint_tooltip");
```

And this one is wrong:
```
editor/project_converter_3_to_4.cpp
500:    { "set_hint_tooltip", "set_tooltip_text" }, // Control
```
The method to rename was `set_tooltip`.

There's however a problem as `TreeItem` also has `set_tooltip`, so it would be wrongly renamed.

`TreeItem` could maybe have its method renamed too, but then there's also `Control::get_tooltip` to consider. So... I'm starting to doubt again if this is really worth the hassle. If it is, we might have to go all the way.

**Comment by Mickeon** [comment]
> `TreeItem` could maybe have its method renamed too, but then there's also `Control::get_tooltip` to consider. So... I'm starting to doubt again if this is really worth the hassle

I myself, I'd do **all** it takes for this one because the previous names did screw me up a couple of times.

**Comment by Mickeon** [comment]
Sorry for the trouble, I'm usually more thorough than this, it was the last-minute rush.

**Comment by YuriSizov** [comment]
> There's however a problem as `TreeItem` also has `set_tooltip`, so it would be wrongly renamed.
> 
> `TreeItem` could maybe have its method renamed too, but then there's also `Control::get_tooltip` to consider. So... I'm starting to doubt again if this is really worth the hassle. If it is, we might have to go all the way. (But this requires discussion first, and could be done in another PR.)

I wouldn't touch `TreeItem` here, it's not too important. It's not a control, or even node, and you can only work with it in code, so there isn't the same issue as we're solving with controls here.

As for `Control::get_tooltip`, the name is okay. It can be made more specific, though the argument kind of does that already. More importantly, I think it needs to be a GDVIRTUAL method, so that scripts can override it, not just the built-in classes. Then it wouldn't look so confusingly similar to `get_tooltip_text` too.

**Comment by akien-mga** [comment]
> As for `Control::get_tooltip`, the name is okay. It can be made more specific, though the argument kind of does that already. More importantly, I think it needs to be a GDVIRTUAL method, so that scripts can override it, not just the built-in classes. Then it wouldn't look so confusingly similar to `get_tooltip_text` too. That's a material for a different PR though, IMO.

IMO it could be `get_tooltip_text_for_position(Vector2 position)` if we want to be consistent. I find it weird to rename `set_tooltip()` everywhere to be `set_tooltip_text()` and partially solve the confusion with the a tooltip Control as defined by `make_custom_tooltip()`, but still have other `get_tooltip()` methods that returns strings.

**Comment by YuriSizov** [comment]
> IMO it could be `get_tooltip_text_for_position(Vector2 position)` if we want to be consistent. I find it weird to rename `set_tooltip()` everywhere to be `set_tooltip_text()` and partially solve the confusion with the a tooltip Control as defined by `make_custom_tooltip()`, but still have other `get_tooltip()` methods that returns strings.

Fair enough, but since this needs to be changed for a virtual API method anyway, we can probably do it in another PR.

**Comment by Mickeon** [comment]
I can't believe this: **EditorProperty** already has `get_tooltip_text()`, I will do some slight refactoring.

**Comment by YuriSizov** [comment]
From looking at `get_tooltip_text` in the inspector, I don't believe it works. It is defined for both EditorProperty and EditorCategory, but the value is only ever set when creating a custom tooltip, which would already override any tooltip logic there is. The only code that calls `get_tooltip_text` in the current master is in Viewport, and it may look like it would work. But if you look closely, you notice that the method is called on the generated tooltip popup:

```cpp
gui.tooltip_popup->call("get_tooltip_text");
```

This node is just a `PopupPanel`, created by the viewport itself, internally. Which is neither the tooltip node created by controls, nor the node that creates the tooltip. So the existing `get_tooltip_text` definitions which are on the controls that _spawn_ the tooltip are never reached.

I think this code can be removed completely...

**Comment by YuriSizov** [comment]
> Alright then, that's... very peculiar. One thing at a time, then. For now I still need to rename otherwise the check will never pass.

I'd avoid renaming it aimlessly just to avoid conflict in this PR. Let me remove it properly in a separate one, then this one can be rebased.

**Comment by YuriSizov** [comment]
You can rebase now!

**Comment by Mickeon** [comment]
Happy days!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
