### PR TITLE
GDScript: automatic dependency resolution for inner classes

### PR DESCRIPTION
**Pull request by ghost**
In GDScript, inner classes in a script currently only see other inner classes that were declared before them (also, they cannot see themselves). This can become a nuisance. One common example is writing state machines:

```
class StateA:
	func nextState(cond):
		if cond:
			return StateA.new() # error, StateA not known
		else:
			return StateB.new() # error, StateB not known

class StateB:
	func nextState(cond):
		...
```

This PR adds a graph search, so that the order of declaration of inner classes in the file doesn't matter (though you will get an error if your dependencies are cyclic), such that - for example - the following code compiles:

```
class A extends B:
	var a_value = 7
	
	func _init():
		C.X.hello(a_value, b_value)
		
class C:
	class X:
		static func hello(a, b):
			print("hello! ", a, " ", b)
	
class B:
	var b_value = 123
	
```

As this change allows class names to be published earlier than currently, this also solves the self-reference issue of inner classes mentioned earlier; it doesn't allow to self-reference the main script though (but see https://github.com/godotengine/godot/pull/15816).

Technicalities: the GDScript compiler internally needs to follow a strict compilation order on classes due to its optimized allocation and access of member variables; the change is not trivial. I'm confident I got it right, though I don't think I understand what `p_keep_state` in `GDScriptCompiler::_parse_class` is for.

The main change is filling `constants` and `subclasses` as soon as possible. For `constants` this doesn't pose any problem - if a constant is accessed, it's never inspected in detail and the compiler won't even know what hides behinds the constant at this stage (i.e. if the class behind it is completely compiled or not); even if it were deep checked in methods compilation, it would be fine, since at that point compilation for the class is finished. For `subclasses` though, the checks done for inheritance need to ensure finished compilation of all base classes (this is done by calling `_finish_compile_class` on every base class in that case). This is also important for `member_indices` of the member variables, as they need to be known and fixed for the class itself and all ancestors of the class at the time a certain class gets compiled.

### CODE REVIEW

**Comment by Geequlim** [comment]
This is really useful!

The self class type can be used in a strange way and it doesn't work for static functions for now.
```gdscript
class A:
  func hello():
      var Self = get_script()
```

**Comment by raymoo** [comment]
Thank you so much, this was bothering me in the exact same example use case.

**Comment by raymoo** [comment]
Does this support mutually-recursive references between inner classes? E.g. StateA can return StateB as the new state, and StateB can return StateA as the new state.

**Comment by poke1024** [comment]
@raymoo Yes, that should work, and this was my use case as well; the PR should make all class names available before compiling the methods' code, and thus every class name defined in the file should be available everywhere else in the file.

It will only fail with an error if there's a cycle in the `extends` dependencies, e.g.:

```
class A extends B:
    ...

class B extends A:
    ...
```

**Comment by raymoo** [comment]
@poke1024 Awesome!

**Comment by reduz** [comment]
This is useful, but i'm not convinced on the implementation. I wonder how it can be dealt with, given optional typing is being added..

**Comment by vnen** [comment]
This issue is more prominent with static typing, since a type hint can refer to a class below in the file as well (it's not a problem for the parser, but it is for the compiler). Given that any level of nested classes is allowed, everything is quite complex to solve.

The solution I had in mind is a multi-pass approach, making a step in every class, then going to another step and doing every class again. Something like this:

1. Create a script for every class in the file (or reference the old script if we're keeping the state).
2. Determine the inheritance for every class (which would be solved by the parser, but script references are done by the com
3. Compile all the class-level stuff (constants, )

**Comment by mhilbrunner** [comment]
Obsoleted by @vnen's PR with typing

**Pull request closed without merging**
