### PR TITLE
Add Clamp To Border option for textures

### PR DESCRIPTION
**Pull request by CedNaru**
OpenGl allows for 4 different behaviours when you set UVs outside the range of 0 to 1.
c3_clamping

The fourth one doesn't exist in Godot which can be troublesome with some shaders.
I added this option in the editor and made some changes in the visual server in order to use the GL_CLAMP_TO_BORDER texture parameter.

clampToBorderEditor

beforeafter

Sadly this clamp doesn't exist in OpenGl ES so this option will be equivalent to the Clamp To Edge (Repeat disabled flag in Godot) on mobile device.

### CODE REVIEW

**Comment by volzhs** [comment]
https://github.com/godotengine/godot/blob/6697fd9a05859914fc320b4b4321fd9fb6170f71/doc/classes/VisualServer.xml#L3949-L3954

the difference on mobile should be mentioned between here if it's accepted to merge.

**Comment by aaronfranke** [comment]
Wouldn't this better be called "Surround with black/empty" or something? Or just "Centered"?

**Comment by CedNaru** [comment]
It is not about centering a texture. 
Here an example, I created a polygon2D with points and UVs like this: 
polygon2D

Here the result with the four different flags: 
Exemples

With the repeat flag disabled, if my texture has colored texel on the edge, those pixel will "leak" for UVS outside the texture.

Here a more practical example. I use a shader to animate a grass texture. If a disable the flag repeat I get this issue: 
grasswind

**Comment by reduz** [comment]
This can't be merged for technical reasons explained below:

* OpenGL ES does not support it (only 3.2 which is only on few devices), so this won't work on most mobile devices or WebGL.
* Eventually when Godot is moved to Vulkan, support for the more exotic repeat modes will not be possible due to the usage of bindless textures (this will have to be emulated in shader).

**Comment by akien-mga** [comment]
Closing as per the above, @reduz has also expressed on other issues that he doesn't want to merge GLES3-specific features for 3.2 if they're going to be removed in 4.0.

**Comment by Calinou** [comment]
> Here a more practical example. I use a shader to animate a grass texture. If I disable the repeat flag I get this result:

For future readers here, note that you can avoid this by ensuring that the texture is surrounded by at least 1 pixel of fully transparent edges.

**Pull request closed without merging**
