### PR TITLE
[DisplayServer] Implement `has_hardware_keyboard` method for Android and iOS.

### PR DESCRIPTION
**Pull request by bruvzg**

### CODE REVIEW

**Comment by Calinou** [comment]
For context, this is needed to resolve https://github.com/godotengine/godot/issues/88235 in a way that doesn't harm usability when a physical keyboard is connected.

**Comment by syntaxerror247** [comment]
Just tested it on android and it is working properly.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Is this something that can be implemented for Web too, when using it on mobile devices?

**Comment by WhalesState** [comment]
> Is this something that can be implemented for Web too, when using it on mobile devices?

If we use this to return from (LineEdit/TextEdit) `show_virtual_keyboard` when `DisplayServer::get_singleton()->has_hardware_keyboard()` is true, it will never show the virtual keyboard on Web (android/ios) since it will always return true on Web.

**Comment by akien-mga** [comment]
Yeah I'm fine merging this to have the feature for platforms that support it, but we need to be very careful before we rely on it for engine functionality. There are also Windows or Linux tablets with virtual keyboards where this would return `true` currently, even if no hardware keyboard is attached.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
