### PR TITLE
Fix LLVM warnings, use std type traits for operations triviality checks.

### PR DESCRIPTION
**Pull request by Faless**

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]

**Comment by RandomShaper** [comment]
Looks like `<type_traits>` is already being transitively included. However, it may be a good idea to include it explicitly in those files where it's already present by luck, not because some well-known include is expected to include it. Not sure which case each of these files lies in.

**Review by akien-mga — APPROVED** [review]
Looks good. For context this fixes a warning introduced in LLVM 15 with this change: https://github.com/llvm/llvm-project/commit/0b89d1d59f82cf5b45c250cd5c3351e43ce35ef9

All compilers seem to support the "new" `std::is_trivially_*` checks aside from GCC < 5, which we don't support anymore.

> Looks like `<type_traits>` is already being transitively included. However, it may be a good idea to include it explicitly in those files where it's already present by luck, not because some well-known include is expected to include it. Not sure which case each of these files lies in.

Good point, in the past we've had issues with e.g. MinGW-GCC not having it implicitly included unlike other toolchains.

**Comment by Faless** [comment]
> Looks like `<type_traits>` is already being transitively included. However, it may be a good idea to include it explicitly in those files where it's already present by luck

Fixed, thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
