### PR TITLE
End benchmark of `Main::setup` properly before calling `setup2`

### PR DESCRIPTION
**Pull request by alvinhochun**

### CODE REVIEW

**Comment by alvinhochun** [comment]
This is a very straightforward bugfix that should be included in 4.3.

**Comment by AThousandShips** [comment]
Please open a bug report for this or where was this being a bug discussed? I'm not sure this is a bug, what makes `startup2` not part of `Main::Setup`?

**Review by AThousandShips — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks correct, `setup2` has its own benchmark.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
