### PR TITLE
Add icons to the Project Manager side buttons

### PR DESCRIPTION
**Pull request by fire-forge**
Adds icons to the Project Manager right side buttons. I picked from the icons already available, so a few of them are not ideal: the Scan button uses the search icon, and the About button has no icon. If you have any suggestions or want to contribute a new icon, feel free to!

| Before | After |
---|---
| image | image |

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
I like the idea.

Maybe there could be a tiny bit more horizontal spacing between the icon and the text in the case of "Remove Missing" (and thus I guess for all buttons because some translations might be longer than that for other buttons too)?

**Comment by fire** [comment]
Germany has problems with being lengthy.

Arabic has reversed text and is also lengthy.

**Comment by fire-forge** [comment]
I adding some extra spacing between the icons and text now.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
