### PR TITLE
Remove code to add patches menu

### LINKED ISSUE #42437: Exporting patch PCKs is not functional
**Godot version:**
3.2.3.stable.official

**OS/device including version:**
Any

**Issue description:**
Project > Export > *select preset* > Patches tab > Make Patch
is not functional. That is to say, nothing happens when clicking this button.
Yet, this UI for creating patch PCKs is in the stable build without any mention of it being WIP.
I suggest that the Patches tab should either be made invisible or made functional.

**Steps to reproduce:**
In short:
Using the Patches tab mentioned above, try to create a PCK file that only contains modified files.

In steps:
1. Download and unzip this demo project:
[export_patch_not_functional.zip](https://github.com/godotengine/godot/files/5307652/export_patch_not_functional.zip)
2. Open in editor and export the project
3. Notice:
- When running the exported binary, the scene will have a text on it saying "INITIAL EXPORT"
- The game's PCK file is around 5 MB (that is because there's a 5 MB image in there)
4. In the editor, open the test.tscn and change the RichTextLabel node to say something else
5. Save the scene and open the export window again, but this time select the Patches tab
6. Select the PCK of the initial export to compare against when making the patch
7. Notice:
- Nothing happens when clicking "Make Patch"
- When clicking "Export PCK/Zip" after "Make Patch", notice that the exported PCK once again is 5 MB
- The expected result would have been a tiny PCK file that only contains the modified tscn file.

### PR DESCRIPTION
**Pull request by rsubtil**
Removed all code related to the unimplemented patching feature.

Fixes #42437

### CODE REVIEW

**Comment by akien-mga** [comment]
I'd say remove the code completely. It hasn't been implemented in over 2 years, so when it is eventually, that code might not be the most relevant to do it anyway.

**Comment by Ev1lbl0w** [comment]
Alright, I've deleted the disabled code then.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
