### PR TITLE
Hide axis gizmo after translating 3D nodes

### PR DESCRIPTION
**Pull request by timothyqiu**
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>

Peek 2022-10-29 16-14
</td>
<td>

Peek 2022-10-29 16-21
</td>
</tr>
</table>

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Simple fix. Seems good to me.

**Comment by adamscott** [comment]
I suggest to add the cherrypick tag to this PR.

**Comment by timothyqiu** [comment]
`3.x` does not have the axis gizmo when translating, so this PR is not relevant.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
