### PR TITLE
Best practices for gamedev - use cache

### PR DESCRIPTION
**Pull request by techtonik**
SCons allows to cache built files -
http://scons.org/doc/latest/HTML/scons-user/ch24.html
which is very useful in shared development with a lot of resources
to be built. It helps to speedup workflow in teams and can be
useful for Godot developers / extender teams as well

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@techtonik ~ Is the cache directory `.gitignore`-ed, or is it outside the repo?

**Comment by techtonik** [comment]
> @techtonik ~ Is it save for different operating systems and CPU architectures?

Good question. I guess SCons needs to build file once on target system anyway to get its build signature and record it in `.sconsign` file, and only after that it will be able to retrieve it from cache. But I asked the question on SO anyway https://stackoverflow.com/questions/37388159/how-scons-cache-works-with-different-os-and-cpu-architectures

> Also, I don't think binaries should be committed to the repository.

They won't be.

**Comment by akien-mga** [comment]
I've tried the patch and I don't really see the benefit. The `.o` and `.a` files are still build inside the source tree, and we already had incremental compilation. Based on the SCons documentation, the CacheDir is meant to be a central location shared between all developers; it's not the case here as all Godot developers have their own git clone in their own $HOME, so there's no way to have such a central location unless we setup a NFS-mounted file system, but the interest is quite limited.

So all in all, it just seems to add 900 MB worth of binary data in `.cache`, with no particular benefit :/

**Comment by techtonik** [comment]
Yes, it looks like SCons already caches everything, but if you're doing game development inhouse (I don't know if all Godot developers are working remotely), then it may be useful to use SCons for managing Godot assets compilation as well. Frankly, I don't know if people are building Godot from scratch for their games. Maybe it is just my requirement.

So yea, perhaps it could be just moved to some docs about using SCons with Godot and game development.

**Comment by akien-mga** [comment]
Yeah a mention to the docs about how to enable a shared cache for developers working on the same infrastructure should do the trick. I think it's too much of a corner case to make it a default behaviour in the buildsystem (you need at least two people working on the same infrastructure *and* from different git clones for it to be useful), but documenting such tricks doesn't hurt.

**Comment by slapin** [comment]
Godot builds around 3 minutes here - I don't see any benefit.

**Comment by akien-mga** [comment]
As mentioned, there is no real gain with this PR, mainly wasted disk space.

**Pull request closed without merging**
