### PR TITLE
[3.x] Document lack of iOS support for WebM

### LINKED ISSUE #75214: The identifier "VideoStreamWebm" isn't declared in the current scope
### Godot version

3.5.2 stable

### System information

MacOS 13.2.1, Apple M1

### Issue description

After exporting to iOS `VideoStreamWebm` appears to be undefined but works just fine in a local build or even in Android build.

### Steps to reproduce

1. add scene and script
2. add `func _ready() -> void: var webm: = VideoStreamWebm.new()`
3. run and see it works
4. export for iOS
5. run iOS build and see it doesn't works

### Minimal reproduction project

-

### PR DESCRIPTION
**Pull request by AThousandShips**
Fixes #75214

### CODE REVIEW

**Comment by Calinou** [comment]
> Should I specify anything about RISC-V?

You could do that at the same time, yes.

**Comment by AThousandShips** [comment]
Then I'll amend when I'm back by computer, how does

**Review by lawnjelly — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
