### PR TITLE
Fix release build.

### LINKED ISSUE #6134: Compile error if target=release
**Operating system or device - Godot version:**
compile on Windows 10 with MSVC 14. Godot current head (b9e8bddf19a277b6a5302ec1e12ace780ed86b12)

**Issue description** (what happened, and what was expected):
```
core\variant_call.cpp(1196): error C2039: 'arg_names': '_VariantCall::FuncData' is not member.
core\variant_call.cpp(1209): error C2039: 'return_type': '_VariantCall::FuncData' is not member.
core\variant_call.cpp(1211): error C2039: 'return_type': '_VariantCall::FuncData' is not member.
```

**Steps to reproduce:**
scons platform=windows tools=no **target=release**
scons platform=android tools=no **target=release**

### PR DESCRIPTION
**Pull request by hurikhan**
This pull request does the following:
-  **variant_call.cpp:** make the members`arg_names` + `return_type` also available for the release build.
- **visual_script_nodes.cpp:** move single`}`outside of the `#ifdef DEBUG_ENABLED` ... `#endif`.

This should fix #6134  + #6291.

@reduz please check if this is okay for you.

### CODE REVIEW

**Comment by vnen** [comment]
Looks fine to me.

**Comment by akien-mga** [comment]
The changes look ok, but I'd like @reduz to have a look at the VariantCall change before merging, as it changes a code chunk that had not been modified since Feb 2014, so the bug might be in the use of these variables more than their declaration.

**Comment by akien-mga** [comment]
The VisualScript code change was obsoleted and now conflicts, could you rebase to keep just the VariantCall fix?

**Comment by hurikhan** [comment]
Okay. My git fu leaves me alone...
I will redo the pr. :-|

**Comment by akien-mga** [comment]
What would have worked:
```
git rebase -i HEAD~2
// remove the last commit
// redo the change manually
git add core/variant_call.cpp
git commit -m 'Fix release build with visualscript module`
git push myfork fix_release_build --force
```

A simple `git pull --rebase upstream master` + fixing the merge conflict might have worked too, but might need some more git fu or at least experience with conflict resolution :)

**Comment by hurikhan** [comment]
@akien-mga Thanks, this will be my first tatoo %-)
My task for tomorrow is... [git rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing)
(Schande schande schande ;))

**Pull request closed without merging**
