### PR TITLE
vulkan: Update volk, headers and glslang to 1.3.204 (take 2)

### PR DESCRIPTION
**Pull request by akien-mga**
Redo of #57948 which was reverted due to #57978.

It's still the same commits and thus has the same bug for now, so opening as draft.

We need to fix our push constants apparently, as per @clayjohn:

> Looks like its intended behaviour. `https://github.com/KhronosGroup/glslang/pull/2810`
>
> We should go through our push constants and remove the binding assignment.

Let's make sure to get this tested on all desktop OSes at least this time. I'm still puzzled that #57948 was working OK for both @bruvzg on macOS and me on Linux... but I don't see any other PR merged in between that would trigger this bug.
*Edit:* Seems we were both fooled by the shader cache which didn't update properly, and still gave us old, working shaders.

### CODE REVIEW

**Comment by clayjohn** [comment]
It looks like specifying a binding for push_constants is not supported behaviour and now glslang is erroring when it is used. What we need to do is go through our ``.glsl`` files and removing the binding assignment. 

For example, this:
https://github.com/godotengine/godot/blob/cf13f8af648c075282e596744e48d60c25fae283/servers/rendering/renderer_rd/shaders/blit.glsl#L7
should become:
```
layout(push_constant, std140) uniform Pos { 
```

**Comment by akien-mga** [comment]
That seems to fix it for me, I'll add this change as first commit in this PR.

**Comment by akien-mga** [comment]
Tested on my system with both Intel HD 630 and Radeon RX Vega M, the current state of this PR seems to work fine.
I tried both with and without `res://.godot` in a project, and both with and without `~/.local/share/godot/shader_cache`.

Marking as ready, though it still needs more testing results before we can merge it.

**Comment by Logharaa** [comment]
Tested on Windows 10 with RTX 2080: the editor works normally without any error

**Comment by Geometror** [comment]
Tested on my desktop system (Windows 10 build 19044.1526, RTX 3060Ti driver version 511.65) and on my notebook (Linux[OpenSUSE Tumbleweed] with kernel 5.16.5, MX150 driver version 470.103). It seems to work fine, before and after the deletion of the shader cache.
The test project I used contains several fog volumes and nearly all lighting effects(SDFGI, SSGI, SSAO, etc.) are enabled, so it should cover a large part of what could potentially break :)

**Pull request merged**
