### PR TITLE
[GDExtension] Implement support for typed arrays.

### PR DESCRIPTION
**Pull request by bruvzg**
Exposes missing `Array` methods, and add typed arrays to the GDExtension JSON.

`godot-cpp` part - https://github.com/godotengine/godot-cpp/pull/841

### CODE REVIEW

**Comment by raulsntos** [comment]
Does this supersede https://github.com/godotengine/godot/pull/64249?

**Comment by bruvzg** [comment]
As usual, it will need rebase after https://github.com/godotengine/godot-cpp/pull/841 merge to pass CI.

**Review by akien-mga — APPROVED** [review]
Looks fine, but I don't see what are the TypedArray related changes in TextServers?

**Comment by akien-mga** [comment]
This also the discussion on #64249 on how to handle this kind of generics in different languages.

**Comment by bruvzg** [comment]
> Looks fine, but I don't see what are the TypedArray related changes in TextServers?

TextServer already was using TypedArrays (and was unbuildable for this reason), TS changes are to make it buildable as an extension again, but not directly related to TypedArray.

**Comment by bruvzg** [comment]
> This also the discussion on https://github.com/godotengine/godot/pull/64249 on how to handle this kind of generics in different languages.

`TypedArray`s are its own subtype in the engine, so for `godot-cpp` method binds should have it as an independent type as well.

The generics, like `Dictionary` content or more specific contents of the generic `Array`, are used only for properties, and irrelevant for C++ bindings. So I guess it's better to have it as extra info (like in #64469) for other language bindings, if they need it.

**Comment by akien-mga** [comment]
I'll merge even though the CI build with godot-cpp hasn't completed yet, to unblock other PRs (as the counterpart merged in godot-cpp breaks building against current Godot code until this is merged).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
