### PR TITLE
Add one-way indicator to tile collision editor

### PR DESCRIPTION
**Pull request by KoBeWi**
When drawing tile collisions, it's difficult to tell which tiles have one-way collision enabled and which not. You need to pick the tile to know it. This PR adds an indicator that shows over tiles with one-way enabled:
image
Uses MoveDown icon.

### CODE REVIEW

**Comment by Mickeon** [comment]
Surprisingly appropriate icon.

**Comment by groud** [comment]
It looks ok-ish, a bit invasive IMO as it blocks the view of the things behind it. We can try lowering the opacity, but I wonder if we should not use a textured blue color for the polygons instead. Something like that: https://www.vectorstock.com/royalty-free-vector/abstract-seamless-geometric-pattern-with-arrows-vector-21697037

Also, the arrows should be pointing upward no? As the most common use case is to go through platforms from bottom to top with your character.

**Comment by Mickeon** [comment]
> Also, the arrows should be pointing upward no? As the most common use case is to go through platforms from bottom to top with your character.

That would be an inconsistency with the CollisionShape2D that we could spend a lot of time arguing on, honestly.
image

**Comment by KoBeWi** [comment]
Replaced the icon with a pattern:
image
It's less visible, but also less intrusive I guess. Also it *might* make drawing one-way polygons slower.

**Comment by groud** [comment]
> It's less visible, but also less intrusive I guess. Also it might make drawing one-way polygons slower.

I don't really get why it would be less visible, but I guess it is because we paint the polygons with a lower opacity?
If that's the case, I would suggest drawing the polygons twice, once with the default color, then another one with only the icon on top of it. 

The difference in performance should be pretty negligible. There should not be a lot of one-way tiles in your TileSet. Also if we want it in the TileMap debug and it causes issues, I think there are ways to improve the drawing.

**Comment by KoBeWi** [comment]
@groud Like this?
image
image

**Comment by groud** [comment]
> @groud Like this?

I would have inverted the white and transparent part though, I think. So that the arrows get more visible.

**Comment by KoBeWi** [comment]
image

**Comment by groud** [comment]
It looks ok-ish, I thinks. Could you try increasing the opacity of the arrows ?

**Comment by KoBeWi** [comment]
image

**Comment by MewPurPur** [comment]
What happens if the collision shape is smaller, like the 2x8 here?

image

**Comment by KoBeWi** [comment]
I didn't test, but the texture should get stretched.

**Comment by MewPurPur** [comment]
To 2px tall? I don't think this would communicate one-wayness well.

**Comment by KoBeWi** [comment]
It looks good when you zoom in
image
The texture is 16x16, so it supersamples.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
