### PR TITLE
Added new Wrap functions for numbers

### PR DESCRIPTION
**Pull request by Chaosus**
Hi godot community. I want to be a new contributor to this exellent engine. In adventures of game programming I found the wrap pattern. Its very useful algorithm which acts like an extended clamp. Number can infinitly loop within min and max, and its very cool and useful..  it can be used for anything from simple sprite animations to complex things like a 3D planet creation. Wrapping is required for many tasks and users needs it in base shelf. Sadly a newcommers may use ugly and ineffecient realizations with "if" keyword or worse("while"), so I want to contribute it in more effecient way... 
So I want to push it as a core function to GDScript. My implementation uses two functions **wrapi** for integers and **wrapf** for floats. Here is a simple screenshot which shows how it work.

image

I hope you like it. Cheers.

EDITED - video demo https://www.youtube.com/watch?v=9YlEcXdUJYw

### CODE REVIEW

**Comment by n-pigeon** [comment]
This is nice! :D
Remember to squash commits into one :)

**Comment by Chaosus** [comment]
@n-pigeon thanks :D Ok, I merge it, but still something wrong with math_funcs.h, and static compilation rejects it

**Comment by Chaosus** [comment]
Hmm... I think I should unify results between wrapi and wrapf, so wrapi(5, 0, 5) will return 0 instead 5 as wrapf(1.5, 0.0, 1.5) return 0...

**Comment by bojidar-bg** [comment]
How is this different from fmod and the % operator (on integers)?

**Review by bojidar-bg — DISMISSED** [review]
Should have an implementation of the function in VisualScript.

**Comment by Chaosus** [comment]
@bojidar-bg Well I think it should work with negative numbers too - look at https://stackoverflow.com/questions/707370/clean-efficient-algorithm-for-wrapping-integers-in-c

What should I do to change in visual script ?

**Comment by Chaosus** [comment]
@bojidar-bg Please check, is everythig ok ?

**Comment by Chaosus** [comment]
"Hmm... I think I should unify results between wrapi and wrapf, so wrapi(5, 0, 5) will return 0 instead 5 as wrapf(1.5, 0.0, 1.5) return 0..."

damn, I can just simply subtract an integer from max parameter to achive this effect...

**Comment by Chaosus** [comment]
Ok, now I think its completly ready for merging, wrapi and wrapf working alike, so there is no confuse between them

**Comment by HummusSamurai** [comment]
Out of curiosity and for future reference, can you give an example use case for this?

**Comment by Chaosus** [comment]
@HummusSamurai Ok, in case of creating a playback of sprite animation in loop(used script attached to Sprite)
for example instead of writing 

```
frame+=1
if frame >= 10:
   frame = 0
if frame < 0
 frame = 9
set_frame(frame)
```

you could simple write 

`set_frame(wrapi(frame + 1, 0, 10)`)

wrapf is usefull when creating infinity 3D surfaces(eg. useful with ImmediateGeometry), works simular to wrapi but for floats.

**Comment by akien-mga** [comment]
@Chaosus It looks like the email address used to sign your commits is not linked to your GitHub account. It's not an issue, but the commit does not show as authored by your GitHub account. If you want to fix it, you can just add the email used in your local git config to your GitHub account.

Also, next time you rebase/amend the commit, don't hesitate to clean up the description as all the "reformat(damn I forgot)" or "fixed bug" information is not particularly relevant to the final state :)

**Comment by Chaosus** [comment]
@akien-mga Thank you, I will learn the complex github system :)

**Comment by Chaosus** [comment]
@akien-mga Is it ready for merge.. ? Now I think its complete...

**Comment by Chaosus** [comment]
Yeah, looks like it worked as expected
here is a test visual script, code in gdscripts also works
image

**Comment by Chaosus** [comment]
@akien-mga I used "git commit --amend" on this PR, is it OK now for merging ?

**Comment by akien-mga** [comment]
Git-wise it's perfect, but now it still needs to be reviewed technically. Do we want the feature, does it do what it says, etc. Please don't pressure maintainers to merge PRs, we do it when it's time.

**Comment by Chaosus** [comment]
@akien-mga Ok, sorry. I will wait then...

**Comment by groud** [comment]
Isn't that what the Math::range_lerp function is more of less doing ?

**Comment by Chaosus** [comment]
range_lerp map a value from one range to another range, it does nothing with wrapping concept

**Comment by groud** [comment]
Oh I see.
Still I don't get what this brings more than the modulo operator. I mean the implementation for the modulo operator is up to us. If we want % to act as a wrap we could do that. The behaviour is undefined in C but it could be defined in GDScript.

**Comment by Chaosus** [comment]
I dont think modulo works great for floats so simply as well as with negative numbers, and apply it to code is not very cool looking than call a specific function

**Comment by groud** [comment]
You can't use % for floats, it's not defined. You have to use fmod().

>  apply it to code is not very cool looking than call a specific function.

That's a personal opinion, I don't agree on this one.

Do you have any example of others math API that define this function ? (it doesn't not look like it's in the python API)

**Comment by Chaosus** [comment]
https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX.Mathematics/MathUtil.cs - ok, here it is

**Comment by Chaosus** [comment]
Ok for example I write : print(-20 % 100) it doesnt prints 80 it prints -20

**Comment by groud** [comment]
> Ok for example I write : print(-20 % 100) it doesnt prints 80 it prints -20

Yeah but as we are in GDscript we could make the % return 80 instead. :)

**Comment by Chaosus** [comment]
hmm.. do you mean you could make a wrapping operator ? This sounds interesting

**Comment by akien-mga** [comment]
> Yeah but as we are in GDscript we could make the % return 80 instead. :)

No, our modulo operator and fmod implementation are standard, we shouldn't change them. I prefer to add wrapi/wrapf if they answer a different use case.

**Comment by Chaosus** [comment]
"var wrapped_int = min + x % (max - min)" - its not correct algorithm, for negative numbers

**Comment by groud** [comment]
> No, our modulo operator and fmod implementation are standard, we shouldn't change them. I prefer to add wrapi/wrapf if they answer a different use case.

In python it works as wrapi, if you do `-5 % 4` it returns `3`

**Comment by Chaosus** [comment]
And what about lower edge of func like (-20 % 100) - what about if I want to limit -50 to 100 ? So wrapi(-51,-50,100) == 99 ?

**Comment by groud** [comment]
Proof:
2017-10-13-144214_721x163_scrot

And the algorithm would be more like:
`int wrapped_int = (x-min) % (max-min) + min`

**Comment by Chaosus** [comment]
Oh, In python... in C++ it write a crap

**Comment by groud** [comment]
Note: If this has to be modified someday, it's at line 1060 of variant_op.cpp

**Comment by Chaosus** [comment]
(x-min) % (max-min) + min - suppose this works corretly, users must write it foreach line they wanted to apply the wrapping algotithm or separate it in static function which they can reach from every script ? Why it cannot be implemented as basic function like clamp ?

**Comment by groud** [comment]
> Why it cannot be implemented as basic function like clamp ?

It could be implemented. 
Still we have to take care not to bloat the API too much, haing too many functions is both confusing to the user and harder to maintain.

Also, as GDscript looks like python, using the python API as a reference for what to implement or not is usually a good choice.

**Comment by Chaosus** [comment]
You right, there are lots of functions in the world and wrap is not very often occur.. 
I just dont take in mind that Math API may be bloated.. and you dont accept new ideas in that direction :(

**Comment by groud** [comment]
> I just dont take in mind that Math API may be bloated.. and you dont accept new ideas in that direction :(

We do sometimes (the discussion for range_lerp was stormy ^^), but the pros and cons have to be discussed first. 

To be honest I am for having this function in the API if we don't change the way the modulo operator works. But if we do implement a python-like modulo, this warp function is less useful.

**Comment by akien-mga** [comment]
Sorry for the delay; I was waiting for more opinions about whether this feature would be useful or not, not much has happened but there were no strong opinions against it, so let's give it a spin.

**Pull request merged**
