### PR TITLE
Improve the asset library download UX

### PR DESCRIPTION
**Pull request by Calinou**
The progress bar is now correctly set to 0% while initiating the download and is hidden once the download is completed.

Feedback on file downloads has also been improved: the size of the currently-downloaded data is now displayed and the total file size is hidden once the download is completed.

## Preview

[](https://gfycat.com/gifs/detail/UnripeGrippingChick)

**Update:** The buttons no longer jump around while the asset is being downloaded. This is not reflected in the preview above.

### CODE REVIEW

**Comment by TailyFair** [comment]
Looks good, but maybe it shouldn't change horizontal size while numbers change ? Nothing more infuriating than buttons sliding around :)

**Comment by Calinou** [comment]
@TailyFair Fixed by increasing the minimum width of download boxes from 250 to 310 :slightly_smiling_face:

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
