### PR TITLE
TextEdit code completion with ItemList h_scroll

### LINKED ISSUE #16542: Auto-complete popup is not big enough
Godot 3.0

When getting nodes from a form, I ended up with paths too long for the auto-completion box:

image

Maybe it should expand if paths are too big?

### LINKED ISSUE #22121: Autocompletion doesn't work on constants defined below the typing area.
**Version: 4547e223**

@vnen Perhaps related to something else ongoing, but noticed that constants when place below a code block will stop appearing for the auto-completion.  I think maybe some other things here and there as well, but didn't think to isolate them at the time.  Wasn't sure of the cause, and thought maybe there were some general stability issues with code completion.  (Like this:  https://github.com/godotengine/godot/issues/21915)

# Above, working as normal.
godot_master_2018-09-15_22-45-46

# Below, not so much.
godot_master_2018-09-15_18-03-02

### LINKED ISSUE #23264: Autocomplete doesn´t list functions after if, while and for blocks.
**Godot version:**

Godot 3.1dev
451e5fd0511bc2c17a66fc73a0de9a5169109517

**OS/device including version:**

Win764bit

**Issue description:**

Autocomplete only list variables and constants after if,while and for blocks:
autocompletebug

Related:
https://github.com/godotengine/godot/issues/21915

### PR DESCRIPTION
**Pull request by AlexHolly**
closes https://github.com/godotengine/godot/issues/16542, closes https://github.com/godotengine/godot/issues/23264, closes https://github.com/godotengine/godot/issues/22121

Tests
Min Length (you can see a small jump on pressing backspace no idea why it happens)
peek 2018-08-19 13-10

Show scrolls only when needed
peek 2018-08-19 13-14

H Scroll for long words
peek 2018-08-19 13-16

### CODE REVIEW

**Comment by AlexHolly** [comment]
I intregrated https://github.com/godotengine/godot/pull/21742 to see the result.
You can close it and merge this one instead.

The finished version
peek 2018-09-05 23-40

peek 2018-09-05 23-51

**Comment by KoBeWi** [comment]
I wrote some (a bigger some) code with your auto-completion changes and while in itself it works perfectly, it has some issues:

- The highlighted text is hard to read. This has something to do with colors or maybe it should be bold, but it's just a bit unreadable.
- Scroll bars, especially the horizontal one, overlap the text.
image
As you can see, the last line isn't really visible and it's a bit bothering. Especially since this popup would do well without scrolling at all, as it's so small.
- Third, and the worst issue, is that sometimes it ignores what you already wrote and appends the whole text instead of missing part. Sadly, I can't find a way to reproduce it consistently, but I wrote many lines and it happens enough to be really annoying. E.g. when you write Vec and auto-complete it to Vector3, you sometimes end up with VecVector3. Terrible.

Other than that, great work. It really makes coding faster, because results are more predictable.

**Comment by AlexHolly** [comment]
1. We can optimize the style (Bold/Color) later for now I made the color editable and green (related https://github.com/godotengine/godot/issues/22552) 
image
https://github.com/godotengine/godot/pull/21181/commits/0ca6637d31ceba095ee0502c0e3bf6f97f53a921#diff-71709879dd36a28d4ff43c570b3b4c8bR5737

2. Should be better now.
image

3. The only case I know is using the completion inbetween but this was there before.
peek 2018-10-05 14-45

Fixed Mouse Scrolling, the selection was moving out of view.

I still don't like the sort function so many casts and the `input` variable is the same on each `Entry` 

> Is there a way to remove the casts?
https://github.com/godotengine/godot/pull/21742/files#diff-0e0c9dec15a95e1c0d8e658a4ab39d4cR455

> Is there a better way to pass a variable to the sort function?
https://github.com/godotengine/godot/pull/21742/files#diff-71709879dd36a28d4ff43c570b3b4c8bR5771
https://github.com/godotengine/godot/pull/21742/files#diff-0e0c9dec15a95e1c0d8e658a4ab39d4cR445
https://github.com/godotengine/godot/pull/21742/files#diff-0e0c9dec15a95e1c0d8e658a4ab39d4cR453

**Comment by KoBeWi** [comment]
I found a way to reproduce my third issue. Actually 2 ways, not sure if there was another case or it always happened like this.
They both boil down to autocompletion somehow "remembering" a position in word and completing by starting from that position, instead of where is the cursor. You can see that on a video: https://youtu.be/8qYieOiW8gk

It actually doesn't happen with vectors, as I usually don't write them this way.

**Comment by AlexHolly** [comment]
Hmm I am still not able to reproduce. Can you create a minimal example? Is it only happening with this PR or was it there before?

**Comment by KoBeWi** [comment]
After further investigating, seems like this issue doesn't happen in clean Godot (tested with official alpha). The reason it doesn't is that auto-complete closes after you complete the word. With your changes, it doesn't disappear and if you press Enter to close it, it produces unexpected outcome.

Here's a guide how to reproduce it, again with Vector type:
1. Start with writing Vec and press Ctrl + Enter or just wait for auto-complete to appear
image
2. Complete the word, either as Vector2 or Vector3
image
3. As you can see, the auto-complete prompt is still there. Now press Enter, and depending probably on timing, it will produce either VVector2 or VecVector3.
image

So probably to fix this, the prompt should close automatically or replace whole word.

**Comment by AlexHolly** [comment]
I am still not able to reproduce it, 
peek 2018-10-11 16-53

I think we should simply fix the issue that was always there it will probably fix this issue too(if there is any).
peek 2018-10-11 16-58

**Comment by AlexHolly** [comment]
Now I can reproduce, thanks.
Looks like a perfect match has some issues.

**Comment by AlexHolly** [comment]
I fixed a few things, needs testing.

1. Highlight color is now using `cache,word_highlighted_color` this means you can edit it in 
Editor -> Editor Settings -> Text Editor -> Highlighting -> Word Highlighted Color
The default color looks pretty bad, maybe we need to change it?

2. Code completion in words now replaces the whole word (needs testing)
3. Perfect match will close the completion window (the issue was in the code_editor.cpp missing update call `text_editor->code_complete` on build in types(specific error? See prev post)).
peek 2018-10-26 03-05

4. I don't like that the scroll space is used even if it is not needed
https://user-images.githubusercontent.com/4741886/46813409-e95fba00-cd76-11e8-9a70-5af0b9be0bee.gif

5. There is still a bug with replacing old word if the cursor is between the word and `()` it works better than before so far.
peek 2018-10-26 03-07

**Comment by AlexHolly** [comment]
It works for me, can you give more details?
peek 2018-10-27 04-10

**Comment by KoBeWi** [comment]
Well, seems like it's conflicting with something on master branch, as cloning your fork fixed the issue. To reproduce my crash, you can get the official master branch and apply your PR (I did it using patch).

**Comment by AlexHolly** [comment]
small bug
peek 2019-02-12 19-41

**Comment by KoBeWi** [comment]
Also related: #4704
Not sure if it fully closes that though, looking at this comment: https://github.com/godotengine/godot/pull/17357#issuecomment-371801589

**Comment by KoBeWi** [comment]
@AlexHolly Could you rebase the PR? >_>

**Comment by AlexHolly** [comment]
@akien-mga This take more and more time to solve, is it going to be merged anytime soon?
@KoBeWi I have no time to test it, I used the master code for the following case(s) since functions don't end with '(' anymore, it looks like that kind of issues are back again.

**Comment by KoBeWi** [comment]
I did a brief test yesterday and, aside from what you already mentioned, spotted 4 issues:
1.
Bug1
Long text overlaps scroll bar.

2.
Bug2
Sometimes selecting with Enter when two words start with the same, it inserts the first word from the list, instead of the one you selected.

3.
Bug3
The quotes bug. It was fixed by #31450, so you have regression in your code.

4.
Bug4 (nie alfabetycznie)
Sorting isn't alphabetical. Not sure what it's caused by. Also, this particular example is affected by 1. I selected position and it inserted scale.

**Comment by AlexHolly** [comment]
Thanks for testing it.
1. Feels like I am fixing this the third time :full_moon_with_face: 
2. `completion_current` was still in some places which is now replaced by `completion_options[completion->get_current()]`
3. Should be fixed again I added some `_cancel_completion` in the prev. commit to solve a case where I got stuck in the Path scope but I am not able to reproduce anymore.
4. Sort Order
    1. By Length
    2. *new: If same length, By alphabet
  image

**Comment by KoBeWi** [comment]
Oh, also you can't change the match color. It seems to always be red. (the previous fixes seem to work alright btw)

**Comment by AlexHolly** [comment]
`cache.word_highlighted_color` is not working for some reason, I used get_color(...), should work now.
`cache` probably needs a cleanup

**Comment by KoBeWi** [comment]
Me again XD
Two things (hopefully last ones):

- autocompletion for paths is terribly inaccurate:
image
See how I looked for Food.tscn and it showed at the bottom of the list, preceded by some irrelevant entries with partial matches.

- I'm not sure if `word_highlighted_color` is a good choice. It's used when you select something to highlight all occurrences of the selection. Default one is very subtle and not very visible in autocompletion and setting a more vibrant color makes word highlighting much less readable.
image
image
Not sure which color from the existing would be good here. You could set a matching color, but totally irrelevant to the function. I guess it could be easier to introduce a new color, but this should be avoided.

**Comment by AlexHolly** [comment]
I have no idea why a new color is not working, a color change in editor settings will not update the color.

**Comment by akien-mga** [comment]
While the enhancements from this PR seem quite interesting to have, the scope is very big and there's a lot of code to review... and visibly various regressions or outstanding bugs to resolve.

I think this should probably be split into separate PRs with a better separation of concerns, so that the code completion experience can be improved gradually with well tested iterations.

I'm also concerned about making TextEdit even more complex for the purpose of the code editor, when it's meant as a general purpose text edition field and not an IDE Control (see #31739). Maybe these changes should wait on the refactor described in #31739 so that it can be done with a better architecture.

Moving to the 4.0 milestone as it's sadly too late in any case to integration this in 3.2.

**Comment by aaronfranke** [comment]
@AlexHolly Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by aaronfranke** [comment]
This PR has not received any new commits for almost a year and is abandoned, closing.

**Pull request closed without merging**
