### PR TITLE
Set all icons to maximum opacity

### PR DESCRIPTION
**Pull request by algorev**
Some icons were darker than others or had inconsistent brightness in general. This was due to the icon SVGs having different opacities.

This PR fixes this by removing all opacity attributes from the SVGs.

_Note: This is my first PR ever, I'm trying to do everything according to the guide, but I might still have gotten some steps wrong, so please be kind with me._

**See godotengine/godot-proposals#3025 for more info.**

### CODE REVIEW

**Comment by Calinou** [comment]
> This PR fixes this by removing all opacity attributes from the SVGs.

Some icons such as RootMotionView are clearly intended to have an opacity attribute, especially in their gradient. I recommend double-checking all the icons individually to check for undesired visual differences.

**Comment by algorev** [comment]
That's one use case i hadn't thought about.
Luckily, my changes hadn't targeted the gradient properties, only the fill and stroke properties, so all that should have changed shou'd be the shapes where the opacity change isn't part of a gradient, i.e. those where the opacity applies to the whole of the shape. Icons like RootMotionView are unaffected.

After that, the question remains as to what degree the opacity on a given icon is intentional. I wanted to change the icon opacities because i thought they had varying opacities mainly because of some kind of error, and wanted ot fix that as i thought it hindered contrast and ui legibility.

If, however, the variations in brightness between many of the icons turn out to be voluntary, i cannot really say i'd be able to do it right. The designer(s) made choices, the rationale of which i do not know. Even if i revised the 700 or so icons one at a time, i don't think i could have a much better judgement than my script did.

To settle the debate, we'd need to bring in one of the people who designed the icons to know:
1. To what degree the variations in opacity were voluntary
2. If so, whether there are many icons where it is important that might have been affected in this PR.
-------- Original Message --------

**Comment by Calinou** [comment]
> To settle the debate, we'd need to bring in one of the people who designed the icons to know:

@djrm designed most of the editor icons, but he's no longer active. Either way, I doubt the varying opacity was an intentional choice for 99% of the editor icons.

**Comment by algorev** [comment]
I see. I'll take a good look and see what i need to change.
-------- Original Message --------

**Comment by algorev** [comment]
Okay, so I had a good look at the icons. I found only one (Group.svg) that relied on fill transparency in an intentful way. I added back the opacity on that one. Normally the icons are all good.

Those force-merges in the PR are just me squashing my commits together. I had a lot of problems catching up to the upstream, but I think I got around them without damage to the history. At least, as far as I could see. I really need to learn git better before my next contribution... But that's another story. The icons should be in order now.

So here it is. I _hope_ I haven't done anything wrong. If I have, tell me and I'll go back and fix it.

**Comment by fire** [comment]
You can have better reviews by showing a preview image of all the icon changes.

**Comment by algorev** [comment]
That's… a very good idea. I'll look into it.

-------- Original Message --------

**Comment by MewPurPur** [comment]
This PR should be closed. It breaks a lot of icons (I mean, it only takes a brief look...)

image

image

In my overhaul of SVGs I've removed all unintended ones like the quite common "opacity=.992"

**Pull request closed without merging**
