### PR TITLE
Use Hermite instead of Bezier for glTF spline interpolation

### LINKED ISSUE #93596: Spline interpolation for glTF wrongly uses Bezier instead of Hermite
### Tested versions

- Reproducible in: 4.3dev [6b281c0], 4.2.1.stable

### System information

Godot v4.2.1.stable - Manjaro Linux - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3090 (nvidia; 550.90.07) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

When importing a glTF or glb file that contains animations using GDScript, the animations that  use spline interpolation on the translation channel are wrong. This is due to the fact that the current implementation of spline interpolation treats the coefficients present in the file as Bezier coefficient, while glTF uses Hermite splines.

The test project provided below shows the same animation created in Blender. The right one has been exported preserving the animations keys, while the left one has the animation baked. Both should look identical.

Here are 2 videos showing the wrong and correct behaviors.

Wrong:

https://github.com/godotengine/godot/assets/4774550/f84a0cde-7dd6-4ac4-bf64-2cbb736db5ba

Correct:

https://github.com/godotengine/godot/assets/4774550/031c16d7-f52c-4a09-b2d2-befa50ef30e9

Animation track in Blender:

animation_track

### Steps to reproduce

To reproduce, just start the project provided below.

### Minimal reproduction project (MRP)

[SplineInterpolationTest.zip](https://github.com/user-attachments/files/15973591/SplineInterpolationTest.zip)

### PR DESCRIPTION
**Pull request by Gurvan**
The cubic spline interpolation implementation in glTF animations wrongly uses Bezier splines instead of Hermite splines ([gltf 2.0 spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#interpolation-cubic), [Hermite Spline](https://en.wikipedia.org/w/index.php?title=Cubic_Hermite_spline)).
This results in incorrect interpolation, see related [issue](https://github.com/godotengine/godot/issues/93596).

Thankfully, there is an easy conversion [from Hermite coefficients to Bezier coefficients](https://en.wikipedia.org/w/index.php?title=Cubic_Hermite_spline&oldid=1219643794#Representations) that fixes the issue with minimal change.

* *Bugsquad edit, closes: https://github.com/godotengine/godot/issues/93596*

### CODE REVIEW

**Comment by fire** [comment]
We’ll look into this.

**Review by TokageItLab — COMMENTED** [review]
Shouldn't it is fixed in `SceneFormatImporterGLTFInterpolate T bezier()` instead it?

**Comment by Gurvan** [comment]
Yes, it is the other option. I went for the minimal change in the code, but changing the `bezier` function to properly compute the interpolation the way it's explained in the glTF spec would probably be clearer.
In that case it would also be better to rename the function from `bezier` to `hermite`, and also rename the Quaternion one (that doesn't do Bezier nor Hermite interpolation by the way).

**Comment by AThousandShips** [comment]
You merged your branch incorrectly or rebased incorrectly, taking over other commits, please fix by:
```
git reset --hard b653ec8
git rebase -i master
```

Then add your fixes again and
```
git push --force
```

**Comment by fire** [comment]
Is the test case in https://github.com/godotengine/godot/issues/93596 ok to validate this or is there other cases?

**Comment by Gurvan** [comment]
It does test the spline interpolation for translation and scaling (rotation works differently) for arbitrary values and tangents.
A case that combine translation and scale could be made, but it wouldn't test anything more than the test in #93596.
The glTF samples repository has infact an [InterpolationTest.glb](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/InterpolationTest/glTF-Binary), but all the tangents in the file are 0, so it can't be used as a actual test case.

Personally, I would be confident to use it as it is.

**Comment by fire** [comment]
I will try to do a review in a few days.

**Review by TokageItLab — CHANGES_REQUESTED** [review]
I agree that rename the method to `hermite()`.

However, in fact, these calculations are already defined in Godot's Math function which is completely the same, so all you need to do is to call it.

- `catmull_rom()` is same with `Math::cubic_interpolate()`
- `hermite()` is same with `Math::smoothstep()`

For now, if you change the code to call the Math function in those method, it should be approve-able.

~BTW, to be consistent with the Math function, it would be also okay to revert the renaming of `harmite()` to `smoothstep()`, and rename `catmull_rom()` to `cubic()`.~

**Review by TokageItLab — APPROVED** [review]
Oh sorry, `smoothstep()` does not allow to set start and end tangents individually, so you probably need to define a function called `hermite_interpolate()` in Math class. Well, since that is an additional feature, we can follow up later. I think this PR is fine, although `catmull_rom()` could be renamed to `cubic()` (but might be odd since glTF definition calls the hermite spline as cubic...).

**Comment by Gurvan** [comment]
There are so many different types of cubic splines, I would say it's probably better to keep their names explicit when possible.
I would be happy to follow up with another PR for moving the interpolation functions into Math.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Gurvan** [comment]
Thanks to the Godot team for making the whole process feel great!

**Comment by TokageItLab** [comment]
@Gurvan If you have time, give it a try the PR to implement `hermite_interpolate()` in the `Math` class and call them in the glTF import :) Although the merge will probably be 4.4.dev at the earliest.

**Pull request merged**
