### PR TITLE
Documentation for most of ItemList control.

### PR DESCRIPTION
**Pull request by gau-veldt**
The icon stuff is incomplete since I haven't used icons.

### CODE REVIEW

**Comment by gau-veldt** [comment]
I figured I'd document the portion of the class that I've used a fair bit now.

**Comment by gau-veldt** [comment]
Ehh?  This isn't even a cxx file why is the build failing???

**Comment by neikeq** [comment]
It's a regression from previous commits. Hopefully it will be fixed soon...

**Comment by gau-veldt** [comment]
Ok so everyone's getting failed CI builds right now...

**Comment by neikeq** [comment]
@godotengine/documentation Quick review anyone? :)

**Comment by StraToN** [comment]
No problem for me. Ok for merge if @akien-mga or @vnen is ok.

**Pull request merged**
