### PR TITLE
[3.x] Add benchmark logic

### PR DESCRIPTION
**Pull request by m4gr3d**
Add benchmarking measuring methods to `OS` to allow for platform specific overrides which can be used to hook into platform specific benchmarking and tracing capabilities.

On Android for example, this allows to hook into the Android SDK tracing APIs, which can be used with tools like [systrace](https://developer.android.com/topic/performance/tracing/command-line).

- Opening the Godot Android Editor project manager on a Pixel 5:
```
I/GodotBenchmark: BENCHMARK:
    	- Godot::onCreate : 0.068 sec.
    	- core : 0.072 sec.
    	- create_custom_theme : 2.171 sec.
    	- create_editor_theme : 2.171 sec.
    	- editor_register_and_generate_icons_all : 0.417 sec.
    	- editor_register_fonts : 1.727 sec.
    	- project_manager : 2.338 sec.
    	- startup_begin : 3.213 sec.
```

- Opening a project in the Godot Android Editor on a Pixel 5:
```
I/GodotBenchmark: BENCHMARK:
    	- Godot::onCreate : 0.043 sec.
    	- core : 0.049 sec.
    	- create_custom_theme : 2.002 sec.
    	- create_editor_theme : 2.001 sec.
    	- editor : 5.914 sec.
    	- editor_load_scene : 0.275 sec.
    	- editor_register_and_generate_icons_all : 0.343 sec.
    	- editor_register_fonts : 1.639 sec.
    	- startup_begin : 6.551 sec.
```

### CODE REVIEW

**Comment by lawnjelly** [comment]
This looks good. :+1: 

I am wondering what the platform / OS specific code is needed for, given that essentially we are just using a timer (which all platforms should support) and saving to a file. (I'm sure there is a reason but it would be nice to make that clear.)

**Comment by m4gr3d** [comment]
> This looks good. 👍
> 
> I am wondering what the platform / OS specific code is needed for, given that essentially we are just using a timer (which all platforms should support) and saving to a file. (I'm sure there is a reason but it would be nice to make that clear.)

@lawnjelly On Android for example, this allows to hook into the Android SDK tracing APIs, which can be used with tools like systrace.

Here's an example trace data screenshot

Screenshot 2023-01-16 at 10 52 42 PM

Looking at the screenshot for example, we can see that there's an opportunity to parallelize the `scenes` / `servers` setup in order to reduce startup latency even further.

**Review by lawnjelly — APPROVED** [review]
This seems mostly ok to me, so I'll give it a preliminary thumbs up because I'd imagine, being for 3.x, it would wait in purgatory without an approval. :grin: 

It probably needs a once over by e.g. @Calinou because I don't know what the longterm plans are in terms of benchmarking and automated testing for performance regressions and how it fits in with that (I don't know if any scheme would be 4.x only, or we would be keeping these in sync or whether we are free to do what we want in 3.x).

Caveats : I've personally never needed to place trackers for external profilers so can't vouch for the usefulness of this versus just a cross-platform approach, and I'm not a java / android guy so that might need another set of eyes.

**Comment by Calinou** [comment]
> It probably needs a once over by e.g. @Calinou because I don't know what the longterm plans are in terms of benchmarking and automated testing for performance regressions and how it fits in with that (I don't know if any scheme would be 4.x only, or we would be keeping these in sync or whether we are free to do what we want in 3.x).

https://github.com/godotengine/godot-benchmarks uses a different way to track engine startup/shutdown times. This new approach is useful for contributors looking to optimize startup, but it's also more complex to integrate in an automated benchmark system (especially as field names may change over time, making comparisons more difficult).

**Pull request merged**
