### PR TITLE
C# Improve the "Tag" conversion of documents

### PR DESCRIPTION
**Pull request by magian1127**
image

image

### CODE REVIEW

**Comment by neikeq** [comment]
Can you confirm if `bold`, `italic` and `underline` work in other IDEs? (VSCode, Rider). I think I remember testing this and finding out it only worked on Visual Studio, or some problem like that.

**Comment by neikeq** [comment]
Also, this needs a better description. Other than the bold/italic/underline and the Variant part, I don't understand well what these changes do. I don't know what I'm supposed to see in the first image.

**Comment by magian1127** [comment]
Only [CSharp] in [CodeBlocks] is retained, and [gdscript] is removed.
Added the conversion of [param XXX], [i], [b], [u].

VS
image

Rider
image

VS Code
image

It seems that we can only remove the underline.

**Review by raulsntos — CHANGES_REQUESTED** [review]
Can you update the commit message to list all the tags that this PR intends to add support for? As far as I can tell it's these ones:

- `[codeblocks]` for code snippets (or more specifically the `[csharp]` tag contained inside).
- `[param]` for referencing parameters (using `<paramref>` in C#).
- `[b]` for bold text.
- `[i]` for italic text.
- ~~`[u]` for underlined text.~~

Also mention the fix about referencing the `Variant` type.

**Comment by magian1127** [comment]
I have already revised it.

my english is not very good. The description is translated by machine, and there may be some accuracy problems. So some of the description is copied directly from yours.

**Review by raulsntos — COMMENTED** [review]
Sorry it took me so long to review this.

Because of the `[param]` tag in the signals documentation I'm getting errors like:

```
godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/AnimationLibrary.cs(146,101): warning CS1734: XML comment on 'AnimationLibrary.AnimationAdded' has a paramref tag for 'name', but there is no parameter by that name
```

This is because the signal documentation is making a reference to a parameter of the delegate but this documentation gets added to the event in C#, not to the delegate.

I'm not sure how to fix this, unfortunately I don't think we can reference the delegate parameters from the event. We can probably just use `<c>` for `[param]` when the member is an event.

**Comment by magian1127** [comment]
I can't determine whether the current line's bbcode belongs to the signal summary.
It may be simpler to use "pragma warning disable CS1734".

**Review by raulsntos — APPROVED** [review]
LGTM, we can likely improve support for `[param]` later.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
