### PR TITLE
[Android editor] Enable automatic install of exported apks for the Android editor

### PR DESCRIPTION
**Pull request by m4gr3d**
Adds support for automatically installing the exported APK for the Android editor.
An editor setting is added as well to allow enabling / disabling the feature (enabled by default).

https://github.com/user-attachments/assets/dde7355e-e60e-44bb-857f-70e111d0c7cd

### CODE REVIEW

**Comment by UnderGamer05** [comment]
Can you add Gradle build support for Android Editor? It will be vary useful.

**Review by Calinou — APPROVED** [review]
Tested locally on a Samsung Galaxy Z Fold4 running Android 14, it works as expected. I've only tested the debug export, as release export can't be done using the built-in debug keystore (the autogenerated keystore path starting with `assets://` isn't considered valid in the Export dialog).

The exported project (Truck Town in this case) runs successfully after installation.

Code looks good to me.

PS: In the future, we could integrate similar "run after export" options for desktop and web platforms.

**Review by syntaxerror247 — COMMENTED** [review]
I think we should keep it's default to `false`. 
Auto-installing by default might inadvertently replace an existing version of the app on the device, which could be disruptive if the installed version contains different configurations or data that user want to keep separate from the newly exported build.

**Comment by m4gr3d** [comment]
> I think we should keep it's default to `false`. Auto-installing by default might inadvertently replace an existing version of the app on the device, which could be disruptive if the installed version contains different configurations or data that user want to keep separate from the newly exported build.

I am not sure I understand the concern:
- the feature is only for the Android editor which means that a previous install would have also been likely added by the Android editor
-  the auto-install feature only applies to an exported project build meaning that is the dev has already gone through the intent of generating the build. If installing is not desired, then the dev can still cancel the installation (a dialog prompt is shown prior to installation)
- Upgrade to existing Android apps conserve the app data so no risk of loosing data unless the dev decides to uninstall the app first

**Comment by syntaxerror247** [comment]
I personally use my own apps, and during development there are many times when I make breaking changes that can also lead to corruption of the saved data. That's why I test my apps on a new user profile. I believe keeping this feature enabled by default could lead to unwanted installations if users aren't aware of it.

> If installing is not desired, then the dev can still cancel the installation (a dialog prompt is shown prior to installation)

Oh, I wasn't aware of that. If a dialog is shown, then it should be fine.

**Comment by m4gr3d** [comment]
> Oh, I wasn't aware of that. If a dialog is shown, then it should be fine.

@syntaxerror247 I've updated the description with a video of the install flow for illustration.

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
