### PR TITLE
Fix compilation on Visual Studio 2013 (#10219).

### PR DESCRIPTION
**Pull request by starry-abyss**
Works on my machine. :-)

### CODE REVIEW

**Comment by karroffel** [comment]
GDNative part looks okay, but I didn't think that nested `extern "C"` would cause trouble. Anyway, this should be fine.

**Comment by starry-abyss** [comment]
Seems it doesn't like going above some amount of nesting. I left things nesting in `gdnative.h`

**Comment by akien-mga** [comment]
Merged manually as 3ba5ee42c to fix style issue.

**Comment by starry-abyss** [comment]
@akien-mga Oh no, it comes again:

```
editor\plugins\canvas_item_editor_plugin.cpp(251) : error C2666: 'fmod' : 3 overloads have similar conversions
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(1193): could be 'long double fmod(long double,long double) throw()'
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(1077): or       'float fmod(float,float) throw()'
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(496): or       'double fmod(double,double)'
        while trying to match the argument list '(real_t, double)'
editor\plugins\canvas_item_editor_plugin.cpp(321) : error C2666: 'fmod' : 3 overloads have similar conversions
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(1193): could be 'long double fmod(long double,long double) throw()'
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(1077): or       'float fmod(float,float) throw()'
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(496): or       'double fmod(double,double)'
        while trying to match the argument list '(real_t, double)'
editor\plugins\canvas_item_editor_plugin.cpp(338) : error C2666: 'fmod' : 3 overloads have similar conversions
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(1193): could be 'long double fmod(long double,long double) throw()'
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(1077): or       'float fmod(float,float) throw()'
        D:\build\Microsoft Visual Studio 12.0\VC\INCLUDE\math.h(496): or       'double fmod(double,double)'
        while trying to match the argument list '(real_t, double)'
```

Can CI be taugth to compile with VS2013?
Because it may be really annoying to check manually and do a PR every time

**Pull request closed without merging**
