### PR TITLE
Added a new member to Node's data called "time_scale"

### PR DESCRIPTION
**Pull request by KokaKnut**
Added a new member to Node's data called "physics_time_scale". This allows
speeding up and slowing down the amount of time a node thinks has passed.

For example, a Timer can have its physics_time_scale set to 2.0 to count at
double speed (two seconds per one real time).

Use the inherit bool to inherit changes to the parents timescale

NOTE: This only effects physics processing. Idle processing may find strange behavior were it to have matching implementation.

Adds functionality for #6885

### CODE REVIEW

**Comment by aaronfranke** [comment]
What exactly does this affect? The size of `delta`? Just `_physics_process` or also other physics code? Does it affect only the one node, or also its children and grandchildren etc?

**Comment by KokaKnut** [comment]
Yes, it just changes the size of delta as seen by the node during physics process. It only affects itself until a child has the inherit bool checked off. Then the child would get its parents delta instead of getting it right from the tree.

**Comment by TheDuriel** [comment]
Would be nice if this was extended to idle processing as well. Not all games run their logic through the physics server, as doing so is often not performant enough. If this was done it would be a huge boost to the existing Engine.time_scale functionality.

**Comment by KokaKnut** [comment]
It would be very simple to extend to idle processing, I can try it out and test today. I only worry about inaccuracies with rapid changes to this variable during frame rate fluctuation. But I haven't tested so I don't know if it would actually be a problem. The other thing to improve would be a better inheritance system, probably mirroring the way pause behavior is inherited through the enumerator. But I don't fully understand that system enough to implement that here.

**Comment by KokaKnut** [comment]
It looks like my fears were unfounded. I can't seem to create inconsistencies even with heavy frame jitter. I'm updating the pull request now.

**Comment by lawnjelly** [comment]
Although you can change the delta passed to _physics_process, presumably this relies on the game using this delta in movement calculations.

If you are using e.g. rigid bodies in actual physics (i.e. Bullet), does it actually use this new node timescale? Or is the whole physics stepped at the same time with one delta?

**Comment by KokaKnut** [comment]
This new variable was never meant to influence how often something is processed. So when you ask if the physics would step at the same time, of course, that wouldn't be changed. But when you say with one delta, that is a different matter. I have made no changes to how physics works, and to do so would be very complex and require some new physics calculations on collisions.

My reason for implementing as much as i have was for 2D games with strict movement done in move_and_slide(), animations, and timers. all of these use the time_scale variable perfectly.

If anyone wants to look into the physics portion of this, i can give you some places to look.

**Comment by lawnjelly** [comment]
I've just had another look at this PR, as I'm currently working on the physics stepping / timescaling. Although I can see the potential usefulness of such an approach, I have two major concerns:

**1. The naming could be misleading.**
Adjusting this physics_time_scale (or just time_scale in the later commit) variable may cause some changes in some code paths (moveandslide, timers, value passed to _physics_process), but not in others (e.g. rigidbodies). This value (get_physics_process_delta_time()) also seems to be used in some areas in the animation too which might be a tad confusing.

You mention adding it to other parts of the physics but I'm not sure that would be straightforward or even possible. If you for example modify the velocity of timescaled rigid bodies surely this will have knock on (pardon the pun) effects on other rigid bodies.

Admittedly I can't think of a good way around the issue that it might sometimes have effect and sometimes not, so the naming might have to be a bit of a compromise.

**2. Efficiency**
The whole recursive checking the parent timescale, and the parents parent, every time the function is called (at least every physics tick per node, possibly more) currently seems very inefficient, especially for something that may rarely be used. If possible something like this should have no cost when switched off.

The transforms for example need to do a similar operation, but they maintain a local cached value, and a dirty flag, such that the cached value is only calculated (from the parent cached value) when necessary. This is just an example, but the existing code in the PR seems to recursively calculate parent values again and again even when values could be reused.

If you try a simple scene with deep node hierarchy and print out the node every time get_physics_process_delta_time() is called you will see this, each node is being calculated multiple times per physics tick. On top of this, recursive jumping through the nodes like this is bad for the cache (of course there is a fair amount of this in godot already lol(!)).

The next question would be, is something like this be possible to implement in gdscript, as needed in a game? Is it something that needs to be part of the core engine? Myself I can see arguments for both, but if it is part of core it needs a rethink for efficiency.

**Comment by KokaKnut** [comment]
@lawnjelly I'm glad you looked into it!

**1. The naming could be misleading.**
I agree, the name only makes sense if it were implemented all the way, physics included. I can't really think of a better name though (time_scale_except_for_simulated_physics?). If it changes the speed animations play, isn't that a good thing?

Adding it to the physics is certainly not straightforward and certainly possible. This kind of ties in with your next point though. I would only see adding the timescale to physics as a niche but cool effect that would have a processing hit on everyone else too. Unless you were to keep parallel versions of each physics engine, one with time_scale behavior and one without, it wouldn't be overall a great change IMO.

As for what the physics calculations would actually look like, I suppose that would be up for debate as it's entirely theoretical. There is probably a "most intuitive" solution, but that is a discussion for whoever would actually implement them.

**2. Efficiency**
There is certainly room for improvement on the efficiency. I did mention it needs an improved inheritance system, but that I'm not familiar enough to work on that right now. But, I did make sure that it is off by default, so there aren't any calls to the parent unless the user set it specifically to do so. if this was to be reworked to mirror the pause_mode system, with notification propagation and locally storing your parents full inherited time_scale, I could see this being efficient even with deep trees like you stated. But for now, if you only need a couple nodes to inherit a time_scale, it works.

I set this up to work for my own project. I needed the _physics_process:delta, animations and timers to scale with each other. In a 2D project with tight controls and no physics simulations, it is fully functional (at least as far as my tests have shown).

**Comment by lawnjelly** [comment]
Ah good point, I was jumping the gun and assuming it would be inherit by default, but if the default is non-inherit this is less of a problem. :+1:

**Comment by aaronfranke** [comment]
@KokaKnut Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by KokaKnut** [comment]
Well, I don't know if I did it right, but it seems to be working.

**Comment by aaronfranke** [comment]
@KokaKnut It seems that you accidentally merged instead of rebasing. Please see this article for more information: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html

**Comment by KokaKnut** [comment]
@aaronfranke Something definitely went wrong... I thought i was following the same thing I did the last time. How can I fix it?

**Comment by Calinou** [comment]
Note that this pull request conflicts with https://github.com/godotengine/godot/pull/34544. https://github.com/godotengine/godot/pull/34544 may have higher chances to be merged since it's more self-contained (it only modifies Timer).

**Comment by TheDuriel** [comment]
Has there been a reason for not merging this besides the conflicts?

**Comment by Calinou** [comment]
> Has there been a reason for not merging this besides the conflicts?

There hasn't been much consensus for merging this feature (e.g. in a [proposal](https://github.com/godotengine/godot-proposals)).

**Comment by TheDuriel** [comment]
We may want to consider making accompanying proposals mandatory for things like that. Fine, I'll make one for this because I think it's very useful.

**Comment by aaronfranke** [comment]
This was discussed on Godot's RocketChat. The consensus is that this change is not necessary, and therefore this PR is not desired. You can scale time yourself in the script, and other nodes such as particles or animation already support time scaling.
For physics time scaling won't work anyway because the solver will break. So, closing.

**Comment by jitspoe** [comment]
Why would this break the solver?  I wanted this feature for physics specifically (I have a time distortion sphere that impacts the time scale of objects inside of it -- like a stasis sphere).  Being able to set a time_scale on rigid bodies would be nice.  I've handled the other cases.

**Pull request closed without merging**
