### PR TITLE
[Need more work] Add Node::reparent

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
What do you think @reduz? #1905

I create the Node:reparent and the NOTIFICATION_REPARENT.

This method need the documentation yet, I don't know where to put.

Edit:
Missing code for Spatial.

### CODE REVIEW

**Comment by guilhermefelipecgs** [comment]
I don't know if it's a good idea the reparent receive to_pos argument and call move_child, maybe the reparent should put always in last position of children nodes.

**Comment by guilhermefelipecgs** [comment]
If the node has no parent, the method reparent is allowing it to be reparented. Maybe it's better deny reparent for nodes that has no parent.

**Comment by HeartoLazor** [comment]
Ok after many tries, we found the best way to overcome this bug with our implementation:
https://gfycat.com/UniqueEveryHoki
is to skip ONLY ready on reparent, the calls of enter_tree / exit_tree are necessary for the integrity of all trees and references from child nodes, and remove those calls, implies hard to track errors on different subnodes, the one from the video comes from canvas_node for example, so we take another approach on this problem, which is don't ignore enter_tree/exit_tree, give the tools for know when the node is reparenting and take actions on specifics events from each type of node, so now:
* The reparent only ignores the ready event
* Now exist a new method for query is_reparenting(), this one should be queried on  enter_tree or exit_tree for skip/change behaviour on problematic nodes who loses his state on reparent.
* Two new notifications,NOTIFICATION_REPARENTING and NOTIFICATION_REPARENTED, and is called when the reparenting process start and ends, its like an exit/enter tree. This events set the bool of is_reparenting to true and false on node.cpp
* For clarity, the reparent uses the destination parent only, not the pos

For now we modified/check this node as an example with the enter_tree /exit_tree on reparenting behaviour using the is_reparenting() flag:
* Animation Player

Also my demo for testing reparenting is added to demos/misc/ with many features for debbuging issues and test if some another nodes lose state on reparent.
qtsr3sz 1

For example the error from the video was recreated by moving the node, then remove it and this trigger erase error on canvas node, this was an example of the corruption from ignore enter_tree/exit_tree, which is fixed on my pull request.

I will open another pull request with this changes for help with the check and fix of another nodes with the demo, but the core for reparent is finished.

**Comment by okamstudio** [comment]
_ready() is just an extra call after enter_scene

it should still happen when you reparent, add some sort of flag on
_exit_scene if you don't want to execute code on it



On Tue, May 19, 2015 at 11:01 PM, Hearto <notifications@github.com> wrote:

> Ok after many tries, we found the best way to overcome this bug with our
> implementation:
> https://gfycat.com/UniqueEveryHoki
> is to skip ONLY ready on reparent, the calls of enter_tree / exit_tree are
> necessary for the integrity of all trees and references from child nodes,
> and remove those calls, implies hard to track errors on different subnodes,
> the one from the video comes from canvas_node for example, so we take
> another approach on this problem, which is don't ignore
> enter_tree/exit_tree, give the tools for know when the node is reparenting
> and take actions on specifics events from each type of node, so now:
>
>    - The reparent only ignores the ready event
>    - Now exist a new method for query is_reparenting(), this one should
>    be queried on enter_tree or exit_tree for skip/change behaviour on
>    problematic nodes who loses his state on reparent.
>    - Two new notifications,NOTIFICATION_REPARENTING and
>    NOTIFICATION_REPARENTED, and is called when the reparenting process start
>    and ends, its like an exit/enter tree. This events set the bool of
>    is_reparenting to true and false on node.cpp
>    - For clarity, the reparent uses the destination parent only, not the
>    pos
>
> For now we modified/check this node as an example with the enter_tree
> /exit_tree on reparenting behaviour using the is_reparenting() flag:
>
>    - Animation Player
>
> Also my demo for testing reparenting is added to demos/misc/ with many
> features for debbuging issues and test if some another nodes lose state on
> reparent.
> [image: qtsr3sz 1]
> <https://cloud.githubusercontent.com/assets/12376042/7717345/d291bac0-fe6d-11e4-8e37-1fafa44dafe4.png>
>
> For example the error from the video was recreated by moving the node,
> then remove it and this trigger erase error on canvas node, this was an
> example of the corruption from ignore enter_tree/exit_tree, which is fixed
> on my pull request.
>
> I will open another pull request with this changes for help with the check
> and fix of another nodes with the demo, but the core for reparent is
> finished.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/1943#issuecomment-103721896>.
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
i'm not quite udnerstanding what the problem is with:

node.get_parent().remove_child( node )
new_parent.add_child( node )

I suppose having a reparent may be a helper, but why is there a need for it?


On Tue, May 19, 2015 at 11:03 PM, Juan Linietsky <juan@okamstudio.com>
wrote:

> _ready() is just an extra call after enter_scene
>
> it should still happen when you reparent, add some sort of flag on
> _exit_scene if you don't want to execute code on it
>
>
>
> On Tue, May 19, 2015 at 11:01 PM, Hearto <notifications@github.com> wrote:
>
>> Ok after many tries, we found the best way to overcome this bug with our
>> implementation:
>> https://gfycat.com/UniqueEveryHoki
>> is to skip ONLY ready on reparent, the calls of enter_tree / exit_tree
>> are necessary for the integrity of all trees and references from child
>> nodes, and remove those calls, implies hard to track errors on different
>> subnodes, the one from the video comes from canvas_node for example, so we
>> take another approach on this problem, which is don't ignore
>> enter_tree/exit_tree, give the tools for know when the node is reparenting
>> and take actions on specifics events from each type of node, so now:
>>
>>    - The reparent only ignores the ready event
>>    - Now exist a new method for query is_reparenting(), this one should
>>    be queried on enter_tree or exit_tree for skip/change behaviour on
>>    problematic nodes who loses his state on reparent.
>>    - Two new notifications,NOTIFICATION_REPARENTING and
>>    NOTIFICATION_REPARENTED, and is called when the reparenting process start
>>    and ends, its like an exit/enter tree. This events set the bool of
>>    is_reparenting to true and false on node.cpp
>>    - For clarity, the reparent uses the destination parent only, not the
>>    pos
>>
>> For now we modified/check this node as an example with the enter_tree
>> /exit_tree on reparenting behaviour using the is_reparenting() flag:
>>
>>    - Animation Player
>>
>> Also my demo for testing reparenting is added to demos/misc/ with many
>> features for debbuging issues and test if some another nodes lose state on
>> reparent.
>> [image: qtsr3sz 1]
>> <https://cloud.githubusercontent.com/assets/12376042/7717345/d291bac0-fe6d-11e4-8e37-1fafa44dafe4.png>
>>
>> For example the error from the video was recreated by moving the node,
>> then remove it and this trigger erase error on canvas node, this was an
>> example of the corruption from ignore enter_tree/exit_tree, which is fixed
>> on my pull request.
>>
>> I will open another pull request with this changes for help with the
>> check and fix of another nodes with the demo, but the core for reparent is
>> finished.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/pull/1943#issuecomment-103721896>.
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*

**Comment by guilhermefelipecgs** [comment]
You can close when you want ok, I don't think this code is good enough.
Thanks.

**Pull request closed without merging**
