### PR TITLE
Merge execute and present commands for RenderingDeviceDriver.

### PR DESCRIPTION
**Pull request by DarioSamo**
After discussing with @stuartcarnie the best strategy for https://github.com/godotengine/godot/pull/88199, I refactored the execute and present methods in command queue to one, as they allow the driver to do further optimizations than if the methods are separate.

No changes in application behavior are expected, but testing is recommended as always. It's not critical to merge this until Metal is supported but it does change significant parts that some of my other PRs rely on.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally on godot-reflection, 3d/platformer and tps-demo (Linux + GeForce RTX 4090 with NVIDIA 545.29.06), it works as expected. I can't observe a performance difference but it's likely because the time taken to present is negligible on this GPU.

**Comment by DarioSamo** [comment]
> Tested locally on godot-reflection, 3d/platformer and tps-demo (Linux + GeForce RTX 4090 with NVIDIA 545.29.06), it works as expected. I can't observe a performance difference but it's likely because the time taken to present is negligible on this GPU.

The existing backends shouldn't show any difference whatsoever, it's just code reorganization. It's pretty much exclusively Metal that will benefit from it.

**Review by clayjohn — APPROVED** [review]
Seems fine to me

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
