### PR TITLE
WIP: Fix CI warnings for iOS platforms

### PR DESCRIPTION
**Pull request by FrazerClews**
Mainly using deprecated modules for iOS 7

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Please squash your commits: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by FrazerClews** [comment]
> Please squash your commits: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

Will do when it's no longer WIP sorry, makes it easier for fixing

**Comment by naithar** [comment]
Should be already handled by https://github.com/godotengine/godot/pull/41504, https://github.com/godotengine/godot/pull/42503 and https://github.com/godotengine/godot/pull/42582 for both `master` and `3.2` branches.

**Comment by akien-mga** [comment]
Closing as superseded by the above linked PRs.

Thanks for the contribution nevertheless!

**Pull request closed without merging**
