### PR TITLE
Added some details in skeleton docs.

### PR DESCRIPTION
**Pull request by tagcup**
Workaround for #19551.

What is the use of get_bone_transform() for BTW?

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

Note that empty lines should not be used in the `<description>` tags, each line is considered a `<p>` (there are no "simple" line breaks). I'll merge as is anyway as I've seen quite a few other places with empty lines in the doc, I'll fix them all at once.

> What is the use of get_bone_transform() for BTW?

No idea :| `git blame` shows the original `GODOT IS OPEN SOURCE` commit by @reduz so git history doesn't tell us much here about the intended use case. What's true is that nothing uses the method internally, so it might actually be unnecessary if it doesn't have a real use case in scripting.

**Comment by tagcup** [comment]
@mysticfall I can't see anything specific about `get_bone_transform` on that page. But I filled in the documentation for that function in this PR based on what I saw in the source file skeleton.cpp.

So I know what it does, I just don't understand how it's useful at all.

**Comment by mysticfall** [comment]
I see. In my case, I'm using the method to emulate so called 'root motion' which involves reading a relative position of the 'position bone' to the skeleton in each frame, and applying the delta to the character itself.

But I don't know if the same feature could have been better implemented by using one of the ohter methods.

**Comment by tagcup** [comment]
Oh, OK, maybe you can expand on the docs about it then.

It definitely needs to be renamed though because the current name doesn't convey the information that "it's the 'delta' transform between the pose and the rest, written in the skeleton reference frame"!

**Comment by mysticfall** [comment]
Oh, sorry for the confusion. What I meant was I'm storing the value of `get_bone_transform` to calculate the delta per each frame, rather than the API itself provides that info.

I was just worried if an API I'm currently using might be deemed redundant and removed. And also I wanted to know if the functionality provided by the method could be perfectly replaced by some other API, if in case it proved to be redundant indeed.

**Comment by tagcup** [comment]
It's just "global" pose (which is accessible through the current API) times inverse of "global" rest (which is not exposed but exposing this makes more sense to me, compared to get_bone_transform) so it'd a essentially be a one-liner.

**Comment by mysticfall** [comment]
I don't mind changing my code to use some other API, if such an alternative would be provided before removing `get_bone_transform`.

**Comment by akien-mga** [comment]
Cherry-picked into 3.0.4.

**Pull request merged**
