### PR TITLE
Fix for drag and drop audio effect resources to audio bus layout

### LINKED ISSUE #17066: Allow drag and dropping audio effects on an audio bus
**Godot version:** 3

It would be convenient to be able to drag and drop a saved AudioEffect file on top of an audio bus to add the effect to it, see: 
audioeffect

I haven't found a way to add a saved effect to the bus layout using the editor, so drag and dropping would be the most intuitive way to add this functionality.

### PR DESCRIPTION
**Pull request by Waranoi**
Fix #17066. I tried to make the code easy to follow to the best of my ability, but I'm not confident in my results. Also should we do anything about audio effect resources not having a name by default? 

When adding a new effect to a bus you would expect the effect to have the same name as the filename, but since the default name is empty the name of the effect in the bus is also empty. Having to explicitly set the name of every new audio effect resource feels like bad user experience to me. I believe that setting the name of the resource to be the same as the filename when created is a good solution.

image image

Also changing the name of an audio effect resource doesn't automatically update the bus layout, I don't know what the best solution for that would be.

### CODE REVIEW

**Review by groud — APPROVED** [review]
Sorry for the late review, but it looks good to me.

**Comment by akien-mga** [comment]
This PR is still marked as a draft, are there known issues / more things that you planned to handle @Waranoi?

**Comment by Waranoi** [comment]
> This PR is still marked as a draft, are there known issues / more things that you planned to handle @Waranoi?

There are only the two issues I listed above: "What to do about audio effect resources not having a name by default?" and "Changing the name of an audio effect resource doesn't automatically update the bus layout." I don't know what the best way to resolve these would be. (Or _if_ any of them should be resolved in this PR)

**Comment by groud** [comment]
> What to do about audio effect resources not having a name by default?

Well, simply use the class name or the file name instead I guess.

> Changing the name of an audio effect resource doesn't automatically update the bus layout.

Resource emit a "changed" signal when they are modified. You may want the editor to register to the change and update the name accordingly.

**Comment by Waranoi** [comment]
> Resource emit a "changed" signal when they are modified. You may want the editor to register to the change and update the name accordingly.

The changed signal does not seem to be emitted automatically on change. https://github.com/godotengine/godot/issues/30179 Do you have any other ideas on how to automatically update the bus layout when changing the name of a referenced resource? 

> Well, simply use the class name or the file name instead I guess.

Have you considered the suggestion in my first post? "I believe that setting the name of the resource to be the same as the filename when created is a good solution." The audio bus layout already uses the resource name internally, that's why the name of the drag and dropped audio effect is blank, because the name of the resource is blank by default.

**Comment by akien-mga** [comment]
Superseded by #62802 which rebases and updates this commit.

**Pull request closed without merging**
