### PR TITLE
Make GDNative DLLs work on UWP

### PR DESCRIPTION
**Pull request by vnen**
The DLL file isn't included in the export for some reason, but apparently this is broken for all platforms.

### CODE REVIEW

**Comment by fire** [comment]
Can you do Win32/64 too?

**Comment by vnen** [comment]
> Can you do Win32/64 too?

Don't know what you mean, for Windows Desktop it should be working already.

**Comment by fire** [comment]
Thought this fix was for https://github.com/godotengine/godot/issues/15183 .

**Comment by vnen** [comment]
No, this doesn't fix the export itself.

**Pull request merged**
