### PR TITLE
Rename 'Discard Instancing' to 'Make Local'

### PR DESCRIPTION
**Pull request by razcore-rad**
Rename the option in the right click menu in the Scene nodes
because Discard Instancing is confusing (it could imply deleting the
instance). I renamed it to Make Local which is used for example in
Blender as well when talking about appending assets from other files.
I think it's clearer. Or it can be renamed to Make Instance Local, but I
thought it's a bit oo long so I went just with Make Local as this option
appears in the menu only when the node is an instance anyway.

### CODE REVIEW

**Comment by groud** [comment]
I don't think you should modify the translation files like that, since they are generated automatically.
But @akien-mga will confirm.

**Comment by YeldhamDev** [comment]
You just don't touch them. Editing the string in the source code is enough.

**Comment by razcore-art** [comment]
I think I got the files right, if not someone let me know

**Comment by razcore-art** [comment]
By the way, those *.po files should be in gitignore if they're generated

**Comment by groud** [comment]
There is still the editor.pot file that should not be modified.

And no, the files are generated manually by running a specific command, not automatically when running Godot. (We synchronize them manually with the translation web app). We also do not run the command automatically to avoid bloating the git log. Thus they should not be added to the gitignore.

**Comment by akien-mga** [comment]
If we agree on that change (I have no strong opinion myself, comments welcome), `TOOL_SCENE_CLEAR_INSTANCING` should also be renamed in the code IMO.

**Comment by akien-mga** [comment]
For the reference, updating the POT/PO files is fine in theory, but currently the *master* translations are still synced with the *3.0* source code, so that I can keep using the Weblate translations for stable builds (we only translate one branch on Weblate, which is the *master* branch, but I want it to have 3.0 translations).

**Comment by razcore-art** [comment]
oright, not big deal

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
