### PR TITLE
Control: Anchor is now 0 to 1 float (WIP)

### LINKED ISSUE #9520: Control node enhancement
After a discussion with @kubecz3k on the IRC, we came with several enhancements that could be made to the Control node. Most are inspired from the Unity Rect Transform component (https://docs.unity3d.com/Manual/UIBasicLayout.html).

- [x] Add a pivot point for both rotation and scale
- [x] Replace anchors begin/center/end by a float value between 0 and 1 (should break compatibility :/) 
- [x] This probably means keeping the margin the same sign. For now the margin is set as the distance to the right side when anchored right. This should be negative, as it left to the right side.
- [x] Add a visualization for the anchor
- [x] Allow the anchors to be dragged
- [x] Add a vizualisation for the pivot point
- [x] Add a grow direction (Done, but I can't understand what this does... ^^) ?

Related: #5245, #5775, #4339, and maybe #7654, #8525, #2965

### PR DESCRIPTION
**Pull request by ghost**
Partially fixes #9520
It kinda works now but still needs some changes to be user-friendly.

### CODE REVIEW

**Comment by reduz** [comment]
We had ratio anchoring in the past, which provided a similar function, but
was removed as it was very user unfriendly.
Thanks for the work, though I myself am not convinced this is an
improvement.
The reasoning is that, In 99.99% of cases, you just want to anchor to begin
or end so making the user experience worse for a different, corner case is
generally not a good idea

**Comment by volzhs** [comment]
I'm little late. but I got evidence what @reduz said.
image
This is screenshot with Godot 1.1

**Comment by reduz** [comment]
Still the PR is not exactly the same, I think what it does is pretty cool,
but It's not very user friendly. This is why for more complex behaviors,
containers are preferred.

**Comment by Geequlim** [comment]
How can I make a Button keep align Bottom-Left by 10px after this change?

**Comment by volzhs** [comment]
> How can I make a Button keep align Bottom-Left by 10px after this change?

I wonder that too.

**Comment by Geequlim** [comment]
I don't think this is a good idea as this would break almost all of the ui scenes imported from 2.x in the feature.

**Comment by Noshyaar** [comment]
> How can I make a Button keep align Bottom-Left by 10px after this change?

| | Anchor | Margin |
| - | - | - |
| Top | 1 (ANCHOR_END) | ? |
| Left | 0 (ANCHOR_BEGIN) | 10 |
| Right | 0 (ANCHOR_BEGIN) | ? |
| Bottom | 1 (ANCHOR_END) | 10 |

**Comment by reduz** [comment]
I'm not denying it's a good idea from the technical standpoint. just that
it's not as user friendly.

**Comment by Noshyaar** [comment]
I think the frontend could be left unchanged (keeping the Begin,End,Center in the property selector) while internally support float via scripting.

**Pull request closed without merging**
