### PR TITLE
[WIP] Replacing lock button

### PR DESCRIPTION
**Pull request by Janglee123**
Many graphic design softwares have this type of approach, which I found more suitable though I am open to discuss the pros and cons. 

Peek 2020-02-07 00-23

### CODE REVIEW

**Comment by arkology** [comment]
How does it look when you minimize this panel?

**Comment by Janglee123** [comment]
@arkology It's just adding toggling functionality to the unlock button. 

Peek 2020-02-09 01-35

**Comment by volzhs** [comment]
it looks wasting space to have a lock icon for all nodes.
especially for the deep node or long node name.

**Comment by Janglee123** [comment]
Fair point @volzhs. On small screens, it can be a problem.

**Comment by groud** [comment]
I agree with @volzhs, this is OK for the toolbar, but in the scene tree the waste of space is too much for it to be worth.

**Comment by avencherus** [comment]
Because they are so similar looking, with hundreds of nodes, it is no longer possible to see what is or isn't locked with a quick glance.

**Comment by Janglee123** [comment]
Now it seems like not a bad idea as the scene tree can have a bunch of deep nodes, and it's hard to differentiate locked and non-locked. I got the idea cause I am used to locking nodes as it cants selected by mistake, but finding the lock button from the toolbar is pretty annoying. 
Nonetheless, above reasons are more equitable. :smile:

**Comment by KoBeWi** [comment]
>  got the idea cause I am used to locking nodes as it cants selected by mistake, but finding the lock button from the toolbar is pretty annoying.

Adding a shortcut for this button would be a better idea.

**Comment by Janglee123** [comment]
I am checking for this one. @KoBeWi

**Pull request closed without merging**
