### PR TITLE
[mono] Generic Typed GetNode, GetChild, etc.

### PR DESCRIPTION
**Pull request by paulloz**
Related issues are #16871, #16309.  
As discussed, this solution with extensions may be temporary.  

This PR introduce the following extension methods to the `Node` class:

* `GetNode<T>() where T : Node`
* `GetChild<T>(int) where T : Node`
* `GetOwner<T>() where T : Node`
* `GetParent<T>() where T : Node`

It is trying to `(T)` cast the return value and throws an `InvalidCastException` if needed.  
To comply with GDScript version of these methods, it returns `null` if the `Node` we're trying to access can't be found.

### CODE REVIEW

**Comment by exts** [comment]
Should change the return type to `Nulltable<T>` and let people deal with null themselves. I know some people have mixed feelings when dealing with exceptions.

**Comment by paulloz** [comment]
@neikeq If consistency with GDScript is not needed on this, I'd be down to throw a `NodeNotFoundException` instead of returning `null` and providing a `GetNodeOrNull<T>` method. Let me know.

**Comment by neikeq** [comment]
If it's about not repeating the code, I would do `node.GetNode(path)?.CastTo<T>();` instead of `returnCastedObjectOrNull`. `CastTo` would be a private extention method.

Is there a reason to use a custom message for the InvalidCastException? The default one already contains a message with the same details: https://dotnetfiddle.net/vtMyLo

**Comment by neikeq** [comment]
> @neikeq If consistency with GDScript is not needed on this, I'd be down to throw a `NodeNotFoundException` instead of returning `null` and providing a `GetNodeOrNull<T>` method. Let me know.

I'm not sure. I guess an exception is best in this case. For consistency with GDScript, we already have the generated non-generic `GetNode`.

**Comment by paulloz** [comment]
I wrote a custom message because here's what I get if I leave the default one. I can't seem to get the one you linked :thinking: 
image

**Comment by neikeq** [comment]
Hmm, what is printed to the terminal?

**Comment by paulloz** [comment]
Yay, I thought too it was another difference between terminal and debugger but no:
```
Unhandled Exception:
System.InvalidCastException: Specified cast is not valid.
  at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
  at Godot.NodeExtensions.GetNode[T] (Godot.Node node, Godot.NodePath path) [0x0000b] in /home/paulloz/.local/share/godot/mono/solutions/3262494009131521873_2_3/GodotSharp/Core/NodeExtension.cs:27 
  at MonoTestProject.child._Ready () [0x00001] in /home/paulloz/Documents/MonoTestProject/child.cs:11 
```

**Comment by reduz** [comment]
Gdscript will throw an error if you get node and it does not exist. We were
discussing get_node and get_node_or_null

**Comment by neikeq** [comment]
Oh, the mono runtime doesn't add those details to the exception message: https://repl.it/repls/WoefulMeatyAssociate
I don't know... the type it's casting to seems pretty obvious to me by looking at the line that calls it. Perhaps we should open an issue in the mono repository?

**Comment by paulloz** [comment]
Yep, that's another possibility.

**Comment by paulloz** [comment]
@reduz yes it's throwing an error but when you do this, `n` will still be assigned `null`.
```gdscript
var n = get_node("this_does_not_exist")
```

**Comment by neikeq** [comment]
I forgot about this issue. `GetNode<T>` was introduced in #20298.

As mentioned in #16871, I'm againt `NodeNotFoundException` and `IndexOutOfRangeException`, as the non-generic version of these methods don't throw these.

The `Get*OrNull<T>` methods should use the `as` operator instead of casting, otherwise they may throw.

Also, I missed this when I reviewed the PR, but `CastTo` is actually not needed, since both cast and `as` work on null references.

**Review by neikeq — CHANGES_REQUESTED** [review]
I forgot about this issue. `GetNode<T>` was introduced in #20298.

As mentioned in #16871, I'm againt `NodeNotFoundException` and `IndexOutOfRangeException`, as the non-generic version of these methods don't throw these.

The `Get*OrNull<T>` methods should use the `as` operator instead of casting, otherwise they may throw.

Also, I missed this when I reviewed the PR, but `CastTo` is actually not needed, since both cast and `as` work on null references.

Other than the previous, the methods look good.

**Comment by paulloz** [comment]
Well, is this PR even still needed? As #20298 (which basically is what this branch was before discussions in #16871 started) is merged, I'm pretty sure this one can be closed.

**Comment by neikeq** [comment]
#20298 only added `GetNode<T>`. I still think the other methods are useful.

**Comment by paulloz** [comment]
@neikeq here they are then.

**Comment by neikeq** [comment]
I'm fine with the `Get*OrNull` methods if you want to add them. They just need to use the `as` operator.
Otherwise, looks good to me.

**Review by neikeq — APPROVED** [review]

**Comment by paulloz** [comment]
@neikeq I think all the methods in this file already return `null` when they don't find what you're looking for.

**Comment by neikeq** [comment]
I mean `Get*OrNull` that return null on invalid cast, if that's desired. Otherwise we can merge.

**Comment by paulloz** [comment]
I see where the confusion is coming from 😅 I'll do that tomorrow.

**Comment by paulloz** [comment]
Done.

**Comment by neikeq** [comment]
Thanks!

**Comment by akien-mga** [comment]
Does it fix any of the linked issues? (If so, don't forget to close them)

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
