### PR TITLE
Use different icons for revertable instanced properties in the inspector

### LINKED ISSUE #2581: Use different "reset" icons for instanced scene properties in the inspector
### Describe the project you are working on

The Godot editor :slightly_smiling_face:

### Describe the problem or limitation you are having in your project

Right now, the Reset button next to a property looks identical in the inspector, regardless of its "reason":

- A property can have a reset button because its value differs from the node's default value.
- For instanced scenes, a property can have a reset button because its value differs from the parent scene's default value.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use slightly different icons (and/or different colors) to distinguish between a reset icon that is shown because the property is different from its default value, and a reset icon that is shown because the instanced scene has a value different from its parent.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The Reset icon could have a different color when comparing against a parent scene (compared to the default value).

For instanced scene properties, we could also have an icon that means "modified from the default value, but identical to parent scene". This icon could take the form of an asterisk (similar to the "modified" marker used in the window title). This icon wouldn't be clickable, though.

See https://github.com/godotengine/godot/issues/45536#issuecomment-816812532.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as EditorInspector is drawn by the engine's C++ code.

### Is there a reason why this should be core and not an add-on in the asset library?

See above.

### PR DESCRIPTION
**Pull request by Calinou**
Properties modified from their default value (but otherwise unmodified from the instanced/inherited scene) will display a non-clickable asterisk icon as well.

This closes https://github.com/godotengine/godot-proposals/issues/2581.

Some questions:

- Should the instanced revert icon have a different icon color? It's not that easy to distinguish at a glance right now. I made it have a "dashed" appearance to mimic the PackedScene's "movie clap" icon.
- Should the asterisk icon be slightly faded out? It can't be clicked after all (I already disabled the hover feedback for it).

### Base scene

image

### Inherited scene

*Flip H was manually unchecked.*

image

### CODE REVIEW

**Comment by YeldhamDev** [comment]
I like the asterisk one, but the new reload icon looks too detailed for its size, and kinda ugly as a result.

**Comment by groud** [comment]
I am not strictly against a change here, but do we really need to make a distinction between "real default values" and "default values by inheritance"? I am not sure I understand problem to solve behind this. For me, the "revert to default value" simply mean reverting to the inherited class default value, so the distinction between the two does not seem very necessary.

Maybe another solution might be to simply find a way to notify that a property was modified in the hierarchy. Like by changing the font color to red or something like that? That's more or less what the asterisk does but in a more subtle way I guess?

**Comment by reduz** [comment]
I understand the good intention here but I think this is bad usability.  The revert icon works very well even if you cant distinguish between scenarios. Changing this will make it worse for more people than those who it helps.

**Comment by Calinou** [comment]
Closing due to lack of support.

**Pull request closed without merging**
