### PR TITLE
Allow [] * int to repeat arrays

### PR DESCRIPTION
**Pull request by ghost**
My use case is for GDScript: in order to call functions like `draw_polygon(vertices, colors)` with one color, it would be very convenient if there would be a Python-style multiply operator `array * integer` that repeats arrays, so one could write `draw_polygon(my_vertices, [my_single_color] * len(my_vertices))`. Another common use case: preparing zero-filled arrays for counting things.

This is a core change in `Variant`. However it's small as it's implemented as a generalization of `append_array`. `append_array` now takes a parameter how often an array should get appended. This is then used to implement the `* ` operator.

Example:

```
print([1, 2, 3] * 3)
> [1, 2, 3, 1, 2, 3, 1, 2, 3]
```

### CODE REVIEW

**Comment by karroffel** [comment]
I commented on this feature proposal a while ago, I still think it's bad. https://github.com/godotengine/godot/issues/12193#issuecomment-339428591

**Comment by akien-mga** [comment]
Yep, I still agree with @karroffel's assessment. A `repeat([1, 2, 3], 3)` method would be much better.

**Comment by vnen** [comment]
I would make this a function of Array: `[1, 2].repeat(3)`. This way it's available to all the bound languages and avoid adding stuff to GDScript globals.

**Comment by poke1024** [comment]
There's nothing bad about `*` acting as repeat on an array and I have my problems understanding why https://github.com/godotengine/godot/issues/12193 got closed. The arguments given there are not sound to me. I have prepared a separate PR with `repeat(x, n)` as a builtin (https://github.com/godotengine/godot/pull/16291), and it's sure a valid way to go, but it's one more global name.

The first and underlying question here is why should `[1, 2] + [3, 4]` mean `[1, 2, 3, 4]` on GDScript's array (and pool array) types? And that's a good question. There's nothing natural about this, it's not at all obvious, and it does harm autocompletion, as `+` now suddenly appears on non-numeric operands. But that's how it is. By convention. Someone decided so.

If one accepts that convention, i.e. that `+` means "concatenate" on an array (and string) algebra in GDScript, then it's very obvious what `*` must mean, by expecting what any common algebra like the real numbers does. In any such field, multiplication happens to be the n-fold sum: `x * 3 = x + x + x`. Thus, here `*` obviously must mean "concatenate n times" due to the definition of `+` as concatenation. Nothing fancy, bad or unlogical. Quite the opposite. There is one common valid definition here and this is it.

On the other hand, a vector-like distributive definition of `*`, e.g. `[a, b] * d = [a * d, b * d]` implies a `+` operator that is not "concatenate", but distributive as well, i.e. `[1, 2, 3] + [1, -1, 0] = [2, 1, 3]`.

If GDScript had a type `Vector` that behaves like a mathematical vector, i.e. like `Vector2` and `Vector3` but with more dimensions, then both `+` and `*` should obviously distribute on components. But an array is an array and not a vector. And that difference is already there due to the definition of `+`.

If there is `+` as it currently is, then there should be `*` as it's proposed here.

**Comment by buckle2000** [comment]
Please, no more operator overload.

**Comment by groud** [comment]
I have to admit I had to check if this was what python does before approving (by a thumb up) the PR.
But consequently, I think that something like what @vnen proposes seems more straightforward and less confusing.

**Comment by vnen** [comment]
TBH I hate `+` for concatenation, exactly because it brings all the mathematical assumptions. `"1" + 2`  should be `"3"`, `"12"` or give a type error? At least for `+` the operands have to be of the same type (which GDScript does better then JavaScript). Though when you're tossing around values in a dynamically typed language, especially if getting values form the user, you might end up with `"1" + "2"` and get `"12"` as a result when you actually wanted to convert to numbers and get the sum.

But it's already there and it's hard to change conventions. Doesn't mean we have to build up on the mistake. I doubt that whoever started using `+` for concatenation was thinking about defining an algebra for array operations.

I get this proposal is not actually adding this to strings, but since strings are essentially arrays of characters and have all of the array properties (concatenation, indexing, length), it's bound to happen that someone will argue to add it to string too, and it would make sense to, since the same logic applies.

Sorry for the rant.

**Comment by reduz** [comment]
closing due to no consense

**Pull request closed without merging**
