### PR TITLE
Correct C++ highlighting settings in `.gitattributes`

### PR DESCRIPTION
**Pull request by C-BJ**

### CODE REVIEW

**Comment by Calinou** [comment]
C files are not C++, so they shouldn't be highlighted as C++.

**Comment by C-BJ** [comment]
> C files are not C++, so they shouldn't be highlighted as C++. A lot of C++'s syntax that would be highlighted is not valid C syntax.
> 
> We use C++ highlighting for `.h` files because they're usually headers for C++ files. This means C++ syntax is allowed in those files.
> 
> In hindsight, we should probably have used the `.hpp` syntax for C++ headers, but this doesn't have universal consensus and doing so will break a ton of pull requests.

My bad and I fix it

**Comment by aaronfranke** [comment]
@Mickeon Unfortunately, Git still gets confused whenever one branch renames a file and one branch modifies that file, so it would still break a lot of pull requests since they would need to rebase.

**Review by Repiteo — APPROVED** [review]
For the record, I'm 100% onboard with transitioning to `.hpp` for headers, albeit through some sort of long-term, gradual process.

Still, with the current state of the repo in mind, this looks good!

**Review by aaronfranke — APPROVED** [review]
I agree with @Repiteo's points above.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
