### PR TITLE
macOS plist: Fixes GDScript UTI

### LINKED ISSUE #41356: Wrong Gdscript UTI type for macOS
**Godot version:**
3.2.3 rc official

**OS/device including version:**

macos 10.15.6

**Issue description:**

Quicklook cannot preview gdscript files because the gd extension is defined as public.data in this file;
https://github.com/godotengine/godot/blob/65730ab9f6fbae34bb161113161b43f8b3fcd4d2/misc/dist/osx_tools.app/Contents/Info.plist#L114

**Steps to reproduce:**
Open it with Quicklook, only the icon will appear.

terminal command for UTI info
```
> mdsl player.gd
...
kMDItemContentType                     = "public.gd"
kMDItemContentTypeTree                 = (
    "public.gd",
    "public.data",
    "public.item"
)
...
```
It should be something like this;

```
kMDItemContentType                     = "public.gd-script"
kMDItemContentTypeTree                 = (
    "public.gd-script",
    "public.shell-script",
    "public.script",
    "public.source-code",
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)
```

https://en.wikipedia.org/wiki/Uniform_Type_Identifier#UTI_structure

### PR DESCRIPTION
**Pull request by setanarut**
fixes #41356

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Comment by bruvzg** [comment]
Might be worth changing `UTTypeIdentifier` from `public.gd` to `public.gd-script` for consistency with the other [predefined scripting languages](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html).

**Comment by hazarek** [comment]
I did `public.script `but `public.shell-script `could also be. I guess it doesn't make a difference. Someone more experienced can recreate the plist file.

Identifier (Constant) | Conforms to | Tags | Comments
-- | -- | -- | --
public.perl-script | public.shell-script | .pl, .pm, text/x-perl-script | Perl script.
public.python-script | public.shell-script | .py, text/x-python-script | Python script.
public.ruby-script | public.shell-script | .rb, .rbw, text/ruby-script | Ruby script.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
