### PR TITLE
Create multiple folders at once through Create Folder dialog.

### PR DESCRIPTION
**Pull request by Nufflee**
Folder name `folder1/folder2/folder3` will create the following folder structure:
```
folder1
└ folder2
  └ folder3 
```

I couldn't find an issue for this but it seems like a really neat feature. 
The history is a bit messed up but I couldn't really fix it.

### CODE REVIEW

**Comment by volzhs** [comment]
doesn't this do the same thing?
https://github.com/godotengine/godot/blob/814fdd398507bf697f249d58b8b349f253bb0289/core/os/dir_access.cpp#L139

**Comment by Nufflee** [comment]
@volzhs Seems like it, didn't notice that method, I'll fix it now.

**Comment by Nufflee** [comment]
Another issue is that folder name `folder1\\\\\\//\\/folder2` is still valid. I'm not sure if/what I should do about it.

**Comment by Nufflee** [comment]
@OvermindDL1 Oh, then that's fine. Thanks for letting me know.

**Comment by akien-mga** [comment]
That's not a good idea to allow / and \ in folder names, it would make "res://" paths very awkward (and potentially break things). All for a feature that most people won't use, it's quite rare that one needs to create folders recursively (or then it should be like with shell expansion but that's another beast).

**Comment by Nufflee** [comment]
@akien-mga  I'm not allowing slashes in folder names, they're just used o indicate recursive folder creation.

**Comment by Zephilinox** [comment]
I really like this, It's a pain typing in the path you want an realising you need to create most of those folders manually

**Comment by akien-mga** [comment]
Please squash the commits together ([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html)).

**Comment by akien-mga** [comment]
Closing for now as it's not in a mergeable state.

If the feature is wanted, either OP or another contributor are welcome to open a new PR with squashed commits.

**Pull request closed without merging**
