### PR TITLE
Fix Clang warnings on Windows

### LINKED ISSUE #37490: -Wunused-variable -Wswitch -Wunused-private-field build errors in display_server_windows.cpp and display_server_windows.h
**Godot version:**
master build https://github.com/godotengine/godot/commit/f7b8d0c688dc15b8841ac13990569dda81bf0652

**OS/device including version:**
Windows 10

**Issue description:**
```
D:\Godot\compile_space\godot>scons -j2 use_llvm=true
scons: Reading SConscript files ...
Automatically detected platform: windows
Configuring for Windows: target=debug, bits=default
Using MinGW
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  3%] [94mCompiling [95m==> [93mplatform\windows\display_server_windows.cpp[0m
[  6%] [94mCompiling [95m==> [93mmain\tests\test_oa_hash_map.cpp[0m
[  6%] [94mCompiling [95m==> [93mmain\tests\test_ordered_hash_map.cpp[0m
[  6%] [94mCompiling [95m==> [93mmain\tests\test_physics_2d.cpp[0m
=====
b"platform\\windows\\display_server_windows.cpp:451:2: warning: touchscreen not working [-W#warnings]
#warning touchscreen not working
 ^
platform\\windows\\display_server_windows.cpp:1022:20: error: unused variable 'wd' [-Werror,-Wunused-variable]
        const WindowData &wd = windows[p_window];
                          ^
platform\\windows\\display_server_windows.cpp:1033:10: error: enumeration values 'WINDOW_FLAG_MAX', 'WINDOW_FLAG_TRANSPARENT_BIT', and 'WINDOW_FLAG_NO_FOCUS_BIT' not handled in switch [-Werror,-Wswitch]
        switch (p_flag) {
                ^
platform\\windows\\display_server_windows.cpp:1066:10: error: 4 enumeration values not handled in switch: 'WINDOW_FLAG_NO_FOCUS', 'WINDOW_FLAG_MAX', 'WINDOW_FLAG_TRANSPARENT_BIT'... [-Werror,-Wswitch]
        switch (p_flag) {
                ^
In file included from platform\\windows\\display_server_windows.cpp:31:
platform\\windows/display_server_windows.h:269:7: error: private field 'force_quit' is not used [-Werror,-Wunused-private-field]
        bool force_quit = false;
             ^
1 warning and 4 errors generated.
"
=====
scons: *** [platform\windows\display_server_windows.windows.tools.64.o] Error 1
scons: building terminated because of errors.
```
4 errors and 1 warning.

**Steps to reproduce:**
`scons -j2 use_llvm=true`

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #37490.

@Anutrix Can you confirm that it fixes the issue? Or if there are more errors coming up later, please do a build with `werror=no` and paste all warnings in the issue.

### CODE REVIEW

**Comment by Anutrix** [comment]
Yeah that is fixed. 
```
[ 57%] [94mCompiling [95m==> [93mdrivers\vulkan\vulkan_context.cpp[0m
=====
b'In file included from drivers\\vulkan\\vulkan_context.cpp:38:\r\nthirdparty\\vulkan\\vk_enum_string_helper.h:35:9: error: unknown pragma ignored [-Werror,-Wunknown-pragmas]\r\n#pragma warning( disable : 4065 )\r\n        ^\r\n1 error generated.\r\n'
=====
scons: *** [drivers\vulkan\vulkan_context.windows.tools.64.o] Error 1
scons: building terminated because of errors.
```
Next error.

**Comment by akien-mga** [comment]
That's an upstream bug, can you test this?
```diff
diff --git a/thirdparty/vulkan/vk_enum_string_helper.h b/thirdparty/vulkan/vk_enum_string_helper.h
index 00c2b9d1d5..f72bca6347 100644
--- a/thirdparty/vulkan/vk_enum_string_helper.h
+++ b/thirdparty/vulkan/vk_enum_string_helper.h
@@ -31,7 +31,7 @@
 
 
 #pragma once
-#ifdef _WIN32
+#if defined(_WIN32) && defined(_MSC_VER)
 #pragma warning( disable : 4065 )
 #endif
 
```

**Comment by Anutrix** [comment]
It works.

**Comment by akien-mga** [comment]
Thanks for testing!

**Pull request merged**
