### PR TITLE
Add AT_LIGHT_PASS builtin to canvas shaders

### PR DESCRIPTION
**Pull request by RandomShaper**
This one allows for complex shaders paired with a simple lighting shader to skip code that would otherwise be pointlessly (and wastefully) run during the light pass.

Depending on your game (number of items and lights), this can yield some performance gain.

__Bonus:__ Add initializer to some member, whose absence was making a crash. Keeping it in a separate commit is intended.

### CODE REVIEW

**Comment by reduz** [comment]
it's probably much simpler to do something like

#ifdef USE_LIGHTING
bool at_light_pass=true;
#else
bool at_light_pass=false;
#endif

and that's it, then make your AT_LIGHT_PASS global variable convert to this

I'm still not understanding the performance benefits, though.

**Comment by RandomShaper** [comment]
Something similar is being done, but instead of adding another `#if`-`#else` construct, I've interleaved the declaration of the `m_IN_LIGHT_PASS` flag with the `#ifdef USE_LIGHTING` blocks already present.

Regarding performance, the key is that this is implemented as a macro instead of a variable, and that's the reason for handling this special case changing a normal `if` into a preprocessed `#if` for `AT_LIGHT_PASS`.

My rationale is that, although a shader compiler is expected to realize it can remove the branching about a constant, compilers for lower-end hardware (I.e., low-mid end mobile) are known to be not so efficient at optimizing. The point is that there would be no benefit in being able to check if you are at the light pass on them, which are precisely the ones this would make a bigger difference on.

So by making it a preprocess-time check we can be sure the unneeded code is removed along with the check itself.

**Comment by reduz** [comment]
Don't worry about that, I've tested this on pretty much all hardware since
6 years ago and I'm confident that this optimization is being done. At
least if you do the PR for 3.0, all hardware that is supported by 3.0 is
100% certain to work.

**Comment by RandomShaper** [comment]
Then, may we keep it for 2.1 and close unmerged for 3.0 as not constructive?

**Comment by reduz** [comment]
i suppose just feel free to change it to what I suggested for 3.0, as it's
a lot less code and leave it as you did for 2.1

**Comment by RandomShaper** [comment]
Done and pushed.

**Comment by reduz** [comment]
ah, check shader_compiler_gles3.cpp , thats where you add the conversion to a local variable.
Just name the variable in the shader as at_light_pass, so the shader itself is more readable I guess

**Comment by RandomShaper** [comment]
Do you mean adding rename from AT_LIGHT_PASS to at_light_pass in order to
avoid the uglyness of m_AT_LIGHT_PASS in canvas.glsl?

**Comment by reduz** [comment]
yup

**Comment by RandomShaper** [comment]
Pushed! Please have a look.

**Comment by reduz** [comment]
awesome, thanks!

**Pull request merged**
