### PR TITLE
Exposed billboard_keep_scale to Sprite3D

### PR DESCRIPTION
**Pull request by Chaosus**
I think this is a good change which makes possible to easily resize billboards when needed.

test

### CODE REVIEW

**Comment by groud** [comment]
Could you explain what this parameter is supposed to do ? It is a little bit unclear from the gif.

**Comment by Chaosus** [comment]
If it is enabled - the user could change sprite scale when Billboard mode set to Enabled or Y-Billboard mode

**Comment by groud** [comment]
@Chaosus hmm, ok. But shouldn't be this the default behavior ? Why would the scale be overridden in billboard or Y-billboard modes ?

**Comment by Chaosus** [comment]
I think, If we are changing it - it could break some people projects.

**Comment by Chaosus** [comment]
Ah, however maybe it may not, if the user intended to change its scale then its his/her decision... we may not predict everything

**Comment by groud** [comment]
> I think, If we are changing it - it could break some people projects.

I don't know, if we consider this as a bugfix, it kind of make sense to have it. 
I think it is generally better to break compatibility for a bugfix than adding a new parameter, as retrocompatubility will have to be kept here.

> Ah, however maybe it may not, if the user intended to change its scale then its his/her decision...

Yeah, that's what I think too.

**Comment by groud** [comment]
But it might be worth discussing if there is a reason why this happened before, to make sure this was not an intended behavior.

**Comment by Chaosus** [comment]
Ok, I release a bugfix in new PR then.

**Comment by Chaosus** [comment]
> But it might be worth discussing if there is a reason why this happened before, to make sure this was not an intended behavior.

Yeah, I think its better too )

**Pull request closed without merging**
