### PR TITLE
Mono: support exported parent class fields

### PR DESCRIPTION
**Pull request by cart**
This exposes exported parent class fields in the inspector.  It behaves like C# overriding / hiding.  If the child class has a field with the same name as one of its ancestors, we use the child's field.

@neikeq: I have no clue if this is the right approach.  Let me know if I did something wrong 😄

### CODE REVIEW

**Comment by neikeq** [comment]
`GDMonoClass` should only contain the fields of the class it represents. This should be done in `CSharpScript::_update_exports`:

https://github.com/godotengine/godot/blob/b759d1416f574e5b642413edd623b04f2a1d20ad/modules/mono/csharp_script.cpp#L1184-L1244

with a loop similar to the one in [`CSharpInstance::get`](https://github.com/godotengine/godot/blob/b759d1416f574e5b642413edd623b04f2a1d20ad/modules/mono/csharp_script.cpp#L780).

**Review by neikeq — CHANGES_REQUESTED** [review]
`GDMonoClass` should only contain the fields of the class it represents. This should be done in `CSharpScript::_update_exports`:

https://github.com/godotengine/godot/blob/b759d1416f574e5b642413edd623b04f2a1d20ad/modules/mono/csharp_script.cpp#L1184-L1244

with a loop similar to the one in [`CSharpInstance::get`](https://github.com/godotengine/godot/blob/b759d1416f574e5b642413edd623b04f2a1d20ad/modules/mono/csharp_script.cpp#L780).

**Comment by cart** [comment]
Cool that makes sense.  I'll make it happen!

**Comment by neikeq** [comment]
Looks good. Thanks!

**Review by neikeq — APPROVED** [review]

**Pull request merged**
