### PR TITLE
Add checks and tests for empty/unnamed arguments

### PR DESCRIPTION
**Pull request by YuriSizov**
Sometimes developers forget to change the argument information in method bindings when changing the method itself. This results in unnamed arguments in the documentation, which doesn't make good docs. We sometimes fix it by hand, but with this change we should start catching the issue on CI for every PR.

It would look something like this and the Static Checks task would fail.:
https://github.com/YuriSizov/godot/runs/7706112708?check_suite_focus=true

Code_2022-08-06_19-16-18

I've decided to change the default name of the unnamed argument/parameter for better grepping. I don't think it would break anything, and if it does then **name your parameters** 😈

-----
I briefly played with an option to fail in the doctool itself, so developers can test it locally while running it to sync up the docs, but we don't have a way to fail CI from the doctool at the moment (even if you return a non-zero exit code). It is still possible to add checks to the doctool without making it fail, something like this (if we still want to report an exit code; otherwise swap for the `ERR_CONTINUE_MSG` macro):

```cpp
// Log as error, but don't fail.
if (arginfo.name.is_empty() || arginfo.name.begins_with("_unnamed_arg")) {
	exit_code = EXIT_FAILURE;
	ERR_PRINT(vformat("In '%s' the '%s' method has unnamed argument in position %d; check '%s::_bind_methods'.", lang->get_name(), md.name, j, lang->get_name()));
}
```

We also don't typically check anything about classes in doctools, it just creates XML and `make_rst.py` does the checking on CI. So this would be an extra option, on top of this PR, if we want that.

For the reference, `make_rst.py` can be run locally with `--dry-run` to not produce any files and only check for errors. Can probably include in pre-commit hooks as a simpler solution?

### CODE REVIEW

**Comment by akien-mga** [comment]
While having a check in `make_rst.py` is nice to have, I think this should be checked by `test_class_db.h` directly.

As a matter of fact, this PR doesn't catch some methods which do lack argument names, because they're setters and their argument name isn't listed in the XML. But you can see them in the GDExtension API:

```
$ rg arg0
godot-headers/extension_api.json
34240:                                                  "name": "arg0",
67272:                                                  "name": "arg0",
212688:                                                 "name": "arg0",
```

**Comment by YuriSizov** [comment]
Ah, I knew about setters, but didn't think about them in the context of the API generation. Makes sense. But it doesn't look like `test_class_db.h` would be enough. We also need to test the global scope (servers/singletons, variant utilities), and each script language built-ins.

**Comment by akien-mga** [comment]
Also for the record, in GDNative in `3.x` the problem is much worse as all the "private" underscore methods bound for signals/UndoRedo/call also often don't have argument names, since we don't really care and they don't show in the docs. So there's plenty of `arg0` and `arg1` in the `3.x` GDNative JSON: https://raw.githubusercontent.com/godotengine/godot-headers/3.x/api.json

**Comment by YuriSizov** [comment]
Well, thank god we don't have tests in 3.x then 😛

**Comment by YuriSizov** [comment]
From `test_class_db.h` testing alone, there are 17 cases of unnamed parameters, mostly setters:

```
===============================================================================
[doctest] test cases:     596 |     595 passed |  1 failed | 1 skipped
[doctest] assertions: 2298748 | 2298731 passed | 17 failed |
[doctest] Status: FAILURE!
```

<details>

```
===============================================================================
C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(833):
TEST SUITE: [ClassDB]
TEST CASE:  [ClassDB] Add exposed classes, builtin types, and global enums
  [ClassDB] Find exposed class

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'AnimationPlayer.set_movie_quit_on_finish_enabled'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'BitMap._set_data'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'ConfirmationDialog.set_cancel_button_text'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'Curve2D._set_data'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'Curve3D._set_data'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'MultiMesh._set_transform_array'.       

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'MultiMesh._set_transform_2d_array'.    

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'MultiMesh._set_color_array'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'MultiMesh._set_custom_data_array'.     

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'OptionButton._select_int'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'PackedDataContainer._set_data'.        

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'PackedScene._set_bundled_scene'.       

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'PolygonPathFinder._set_data'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'ResourcePreloader._set_resources'.     

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'SpriteFrames._set_animations'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'TextEdit.set_fit_content_height_enabled'.

C:\Projects\godot-engine\master\tests/core/object/test_class_db.h(377): ERROR: CHECK_FALSE( (p_arg.name.is_empty() || p_arg.name.begins_with("_unnamed_arg")) ) is NOT correct!       
  values: CHECK_FALSE( true )
  logged: Unnamed argument in position 0 of method 'Translation._set_messages'.
```

</details>

I'll see how to test singletons, utility functions, and scripting languages next.

**Comment by YuriSizov** [comment]
@akien-mga Done! I hope this is to your satisfaction. I've added a second commit that adds tests to ClassDB, Variant, and GDScript, and fixes what these tests have unearthed.

**Review by akien-mga — APPROVED** [review]
Looks amazing!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
