### PR TITLE
Rename 2D NoiseTexture to NoiseTexture2D

### PR DESCRIPTION
**Pull request by aaronfranke**
This rename would be helpful to have done before implementing https://github.com/godotengine/godot-proposals/issues/4946

However, I think this stands on its own. Since it inherits Texture2D it makes sense to have the name end in Texture2D, so I'm opening a PR just for this. I briefly discussed this on RocketChat.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Discussed on Rocketchat, we should merge this before beta so that we have room to implement a NoiseTexture3D in the future without breaking compatibility.

**Comment by akien-mga** [comment]
What about all the other `*Texture` classes though, like `AnimatedTexture` or `CanvasTexture`?

**Comment by aaronfranke** [comment]
@akien-mga I don't know about each case, but in general that makes sense and I would be in favor of renaming some of those too. For this PR, in addition to the Texture2D inheritance, I am focused on this case because 3D noise is known to be a desired feature so making the 2D one explicit makes more immediate sense.

**Comment by akien-mga** [comment]
Discussed it with @reduz who seems to be fine with the change:

```
<Akien> @reduz Thoughts on #64864 ? My main doubt is that it adds more inconsistency in the naming of our texture classes.
Currently, most classes inheriting Texture2D don't use the 2D suffix:
[img of the classes inheriting Texture2D]
<reduz> @Akien it would make sense if we think a NoiseTexture3D makes sense
which may do
the others are clearly 2D only
<Akien> Yeah this PR is in support of a proposal to add NoiseTexture3D
My doubt is whether we'll ever want to also add AnimatedTexture3D or something like that.
<reduz> probably not, and that reminds me that i need to remove ProxyTexture
its not so useful now and its not so efficient in Vulkan 
```

**Pull request merged**
