### PR TITLE
Update the `launchMode` for the `GodotApp` activity

### LINKED ISSUE #83924: Android activity launchMode should set to "singleTask"
### Godot version

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.22011.4008) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.22011.4008) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

Currently it sets to "singleInstance", which causes black screen when

1:  The game integrates SDK that have another activity, e.g  ads sdk
2:  The user switched the game to background while the full screen activity is on top. e.g, a reward ad is being played
3:  Android system had determined to kill the game activity (onDestroy was called)
4:  The user switched the game back to foreground

I'm not familiar with Android development, so I took a look at an Unity built apk with ads sdk, and I noticed the launchMode is "singleTask". I changed apk built by Godot to "singleTask", and the issue went away.

It seems singleTask doesn't cause any other problem, at least in my project. So it might be good to change this in Godot export template as well.

### Steps to reproduce

as stated in issue description

### Minimal reproduction project

Can't provide because it need my ads sdk key :(

### PR DESCRIPTION
**Pull request by m4gr3d**
This allows other activities to be part of the same task

For details, see https://developer.android.com/guide/topics/manifest/activity-element#lmode

Fixes https://github.com/godotengine/godot/issues/83924

[3.x version](https://github.com/godotengine/godot/pull/84279)

### CODE REVIEW

**Comment by m4gr3d** [comment]
Waiting for confirmation this fixes the issue in https://github.com/godotengine/godot/issues/83924#issuecomment-1779628692

**Review by akien-mga — APPROVED** [review]
Approving as it seems confirmed to fix the issue.
There's still a question about whether `singleInstancePerTask` or `singleTask` would be best.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.

**Pull request merged**
