### PR TITLE
Add RTL text support and fa locale

### PR DESCRIPTION
**Pull request by masoudbh3**
Add RTL text support for all section of godot engine.
for use rtl text in godot engine import a font that contains arabic
glyphs and use that for editor font or gui font. (godot default fonts
not contains arabic glyphs)

Before : 
RTL_Before
After : 
RTL_After

and add fa (persian) locale.

### CODE REVIEW

**Comment by punto-** [comment]
the 'fribdi' library seems to be LGPL, unless I'm missing a second license?
also it should go on drivers/

**Comment by reduz** [comment]
yeah, fribidi is awesome, but lgpl license makes it impossible for use on
mobile devices or consoles. Is the algorithm used by fribidi that complex?
Maybe the functions themselves could be isolated

**Comment by okamstudio** [comment]
this is a very good patch though, are you sure you can't get the
functionality for bidi_visual_string from somewhere else?


On Thu, Jul 23, 2015 at 9:15 AM, Juan Linietsky <notifications@github.com>
wrote:

> yeah, fribidi is awesome, but lgpl license makes it impossible for use on
> mobile devices or consoles. Is the algorithm used by fribidi that complex?
> Maybe the functions themselves could be isolated
>
>
>
> On Thu, Jul 23, 2015 at 9:01 AM, punto- <notifications@github.com> wrote:
>
> > the 'fribdi' library seems to be LGPL, unless I'm missing a second
> license?
> > also it should go on drivers/
> >
> > On Thu, Jul 23, 2015 at 8:55 AM, masoud bh <notifications@github.com>
> > wrote:
> >
> > > Add RTL text support for all section of godot engine.
> > > for use rtl text in godot engine import a font that contains arabic
> > > glyphs and use that for editor font or gui font. (godot default fonts
> > > not contains arabic glyphs)
> > >
> > > Before :
> > > [image: RTL_Before]
> > > <
> >
> https://cloud.githubusercontent.com/assets/9015847/8849636/7b0b9f5c-3156-11e5-8ad8-5aa69199ddd4.png
> > >
> > > After :
> > > [image: RTL_After]
> > > <
> >
> https://cloud.githubusercontent.com/assets/9015847/8849637/7b44c7c8-3156-11e5-9ffe-5a2694161f42.png
> > >
> > >
> > > and add fa (persian) locale.
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/okamstudio/godot/pull/2297
> > > Commit Summary
> > >
> > > - Add FA Locale
> > > - Add RTL Text Support
> > >
> > > File Changes
> > >
>
> > > - *M* core/SCsub
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-0> (1)
> > > - *A* core/fribidi/SCsub
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-1> (7)
> > > - *A* core/fribidi/arabic-misc.tab.i
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-2> (94)
> > > - *A* core/fribidi/arabic-shaping.tab.i
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-3> (205)
> > > - *A* core/fribidi/bidi-type.tab.i
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-4> (5821)
> > > - *A* core/fribidi/bidi-types.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-5> (61)
> > > - *A* core/fribidi/common.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-6> (186)
> > > - *A* core/fribidi/debug.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-7> (113)
> > > - *A* core/fribidi/fribidi-arabic.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-8> (193)
> > > - *A* core/fribidi/fribidi-arabic.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-9> (88)
> > > - *A* core/fribidi/fribidi-begindecls.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-10> (3)
> > > - *A* core/fribidi/fribidi-bidi-types-list.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-11> (98)
> > > - *A* core/fribidi/fribidi-bidi-types.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-12> (125)
> > > - *A* core/fribidi/fribidi-bidi-types.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-13> (389)
> > > - *A* core/fribidi/fribidi-bidi.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-14> (998)
> > > - *A* core/fribidi/fribidi-bidi.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-15> (149)
> > > - *A* core/fribidi/fribidi-common.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-16> (126)
> > > - *A* core/fribidi/fribidi-config.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-17> (28)
> > > - *A* core/fribidi/fribidi-config.h.in
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-18> (26)
> > > - *A* core/fribidi/fribidi-deprecated.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-19> (314)
> > > - *A* core/fribidi/fribidi-deprecated.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-20> (243)
> > > - *A* core/fribidi/fribidi-enddecls.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-21> (3)
> > > - *A* core/fribidi/fribidi-flags.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-22> (78)
> > > - *A* core/fribidi/fribidi-joining-types-list.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-23> (50)
> > > - *A* core/fribidi/fribidi-joining-types.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-24> (118)
> > > - *A* core/fribidi/fribidi-joining-types.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-25> (258)
> > > - *A* core/fribidi/fribidi-joining.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-26> (193)
> > > - *A* core/fribidi/fribidi-joining.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-27> (81)
> > > - *A* core/fribidi/fribidi-mem.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-28> (140)
> > > - *A* core/fribidi/fribidi-mirroring.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-29> (96)
> > > - *A* core/fribidi/fribidi-mirroring.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-30> (94)
> > > - *A* core/fribidi/fribidi-run.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-31> (376)
> > > - *A* core/fribidi/fribidi-shape.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-32> (69)
> > > - *A* core/fribidi/fribidi-shape.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-33> (78)
> > > - *A* core/fribidi/fribidi-types.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-34> (162)
> > > - *A* core/fribidi/fribidi-unicode-version.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-35> (14)
> > > - *A* core/fribidi/fribidi-unicode.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-36> (105)
> > > - *A* core/fribidi/fribidi.c
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-37> (105)
> > > - *A* core/fribidi/fribidi.def
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-38> (26)
> > > - *A* core/fribidi/fribidi.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-39> (73)
> > > - *A* core/fribidi/joining-type.tab.i
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-40> (4551)
> > > - *A* core/fribidi/joining-types.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-41> (59)
> > > - *A* core/fribidi/mem.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-42> (97)
> > > - *A* core/fribidi/mirroring.tab.i
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-43> (1148)
> > > - *A* core/fribidi/readme/AUTHORS
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-44> (40)
> > > - *A* core/fribidi/readme/COPYING
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-45> (504)
> > > - *A* core/fribidi/readme/README
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-46> (153)
> > > - *A* core/fribidi/readme/THANKS
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-47> (30)
> > > - *A* core/fribidi/run.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-48> (157)
> > > - *M* core/translation.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-49> (2)
> > > - *M* core/ustring.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-50> (49)
> > > - *M* core/ustring.h
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-51> (1)
> > > - *M* core/variant_call.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-52> (2)
> > > - *M* doc/base/classes.xml
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-53> (7)
> > > - *A* platform/android/java/res/values-fa/strings.xml
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-54> (16)
> > > - *M* scene/gui/label.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-55> (22)
> > > - *M* scene/gui/line_edit.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-56> (8)
> > > - *M* scene/gui/rich_text_label.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-57> (3)
> > > - *M* scene/gui/text_edit.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-58> (2)
> > > - *M* scene/resources/font.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-59> (8)
> > > - *M* tools/editor/output_strings.cpp
> > > <https://github.com/okamstudio/godot/pull/2297/files#diff-60> (2)
> > >
> > > Patch Links:
> > >
> > > - https://github.com/okamstudio/godot/pull/2297.patch
> > > - https://github.com/okamstudio/godot/pull/2297.diff
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/okamstudio/godot/pull/2297>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/pull/2297#issuecomment-124076144>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2297#issuecomment-124078431>.
>



-- 

*OkamStudio*

**Comment by masoudbh** [comment]
I was not very familiar with license.
I'll try to implement bidi algorithm.

**Comment by masoudbh** [comment]
bidi changed , what's your opinion.

**Comment by mohaalak** [comment]
I wrote [RTL support with firbidi](https://github.com/okamstudio/godot/issues/982) some time ago , but I think this bidi is awesome , @masoudbh did you implement earab too? I write it in persian so you know what I mean.
سلام آقا شما کسره فتحه تشدید و اینارو گذاشتی چون من دارم کار میکنم رو این قسمتش از رو کد که به نظرم نزدی درسته؟

**Comment by masoudbh** [comment]
this bidi class derived from fribidi library code with some bug fixes. this class is a demo.
soon we together implement bidi algorithm from unicode site:  http://unicode.org/reports/tr9/ and change this class from base. 
this class is only an interface.
you still can't compile this class statically in commerical games.
this class support earab (fatha,kasra,shada,...).

**Comment by mohaalak** [comment]
the class support earab but godot does not .every letter is going to move
cursor forward but when you type earab cursor should not mive and every
letter should be typed in the same exact spot. I write it today using
fribidi. I can change using your code from bidi. is bidi algorithm does
have a license or not?

**Comment by masoudbh** [comment]
no, bidi algorithm is not licensed and provided by "The Unicode Consortium".
there are many implement of bidi algorithm.
fribidi , harfbuzz , python-bidi , ...
LGPL , old MIT  , LGPL , ...
godot support earab only with bitmap font and not with distance field font.
bidi_earab
thanks to the efforts of godot engine team for good (very good) implement of font rendering.
but again I say, this class now have license issue for commerical games and can only used for open source games.

**Pull request closed without merging**
