### PR TITLE
Implement 3D shadows in the GL Compatibility renderer

### LINKED ISSUE #66596: OpenGL: Light3D shadow rendering is not reimplemented yet
### Godot version

4.0.beta1

### System information

Windows 10/11

### Issue description

Shadow dont work when using OpenGL3 driver

In editor:
image

In Game:
image

### Steps to reproduce

1. Create a Project
2. Change on **Project Settings** the _Rendering Driver_ to OpenGL3
3. Add some MeshInstance3D with Mesh
4. Add DirectionalLight3D or any light node and active Shadow on Inspector
5. Add Camera3D

### Minimal reproduction project

[shadow.zip](https://github.com/godotengine/godot/files/9674620/shadow.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/66596

Implementation of 3D shadows for the Compatibility renderer

Implementation based on https://github.com/godotengine/godot-proposals/issues/3959

### Main approach

Particularly this uses a multipass approach to lighting so that we can benefit from prefetch when using hard shadows. In practice this means:
1. All lights without shadows are rendered during base pass as well as one light with shadows
2. Each additional light with a shadow requires drawing the object again with additive blending
3. Lights with shadows are blended in sRGB space instead of linear, so the colors blow out very quickly (i.e. lights with shadows look like they do in the Godot 3.x GLES2 renderer) (Lights without shadows look normal)

### Comments

There is still one outstanding bug where shadow atlas textures are getting out of date with multiple shadowed lights in the scene.

Pictures:
<details>
  <summary>Linear vs sRGB blending</summary>

_Lighting in linear space (no shadows)_
Screenshot from 2023-05-25 20-49-27

_Lighting in sRGB space_
Screenshot from 2023-05-25 20-51-26

_Lighting in sRGB space with reduced brightness and attenuation_
Screenshot from 2023-05-25 20-51-08

</details>

<details>
  <summary>Compatibility vs Forward+</summary>

_Compatibility_
Screenshot from 2023-09-27 16-59-51

_Forward+_
Screenshot from 2023-09-27 16-25-52

</details>

### CODE REVIEW

**Comment by Calinou** [comment]
> My gut tells me the performance gains from doing multipass in terms of prefetchare outweighed by the performance losses from having to render each object multiple times.

In practice, we can't expect every mobile project to be using fully baked lightmaps, so I think improving performance of rendering multiple real-time lights with shadows is key.

**Comment by piramidamsc** [comment]
Directional Light doesn't work properly for me, I'm using your custom godot 4.1 dev build

**Comment by piramidamsc** [comment]
Directional Light doesn't work properly for me, I'm using your custom godot 4.1 dev build

**Comment by filipworksdev** [comment]
Does this fix the longstanding issue where shadows ignore shader parameter POINT_SIZE for point meshes Mesh.PRIMITIVE_POINTS?

**Comment by Calinou** [comment]
> Does this fix the longstanding issue where shadows ignore shader parameter POINT_SIZE for point meshes Mesh.PRIMITIVE_POINTS?

Please open a separate issue with a minimal reproduction project attached.

**Comment by reduz** [comment]
@clayjohn 
> In order to avoid lights flickering between Linear and sRGB blending, shadowed lights always have to be in a separate pass. In https://github.com/godotengine/godot-proposals/issues/3959 reduz assumed we could render one positional and one directional light in the base pass, but in practice this looks really bad.

I can see why. That said, I would still try to, at least, do the directional light in a single pass merged with the non shadowed lights. Directional + non shadowed lights is the most common way to do lighting on mobile.

Also shadow filter is ok and expected to be non-pcf on mobile by default (only enable linear interpolation so it does hardware accelerated PCF4, which is per spec on GLES3).

**Comment by reduz** [comment]
@Calinou I am surprised performance is not similar to Godot GLES2 to be honest. We really should aim for as closest as that if possible.

**Comment by clayjohn** [comment]
> @clayjohn
> 
> > In order to avoid lights flickering between Linear and sRGB blending, shadowed lights always have to be in a separate pass. In [godotengine/godot-proposals#3959](https://github.com/godotengine/godot-proposals/issues/3959) reduz assumed we could render one positional and one directional light in the base pass, but in practice this looks really bad.
> 
> I can see why. That said, I would still try to, at least, do the directional light in a single pass merged with the non shadowed lights. Directional + non shadowed lights is the most common way to do lighting on mobile, so this as single pass is ideal.
> 
> I know this would break if you have more than one directional light, but we could have a setting `allow_multiple_directional_lights` on compatibility that works as you describe _only_ if user enables it.
> 
> Also shadow filter is ok and expected to be non-pcf on mobile by default (only enable linear interpolation so it does hardware accelerated PCF4, which is per spec on GLES3).

I already have a plan. I will move the calculation of the additional lights to after the tonemapping step in the shader. That way, we can have the first light with shadows calculated in the original pass, but still in sRGB space. Should be enough to improve performance a little bit and ensure we get the best performance possible when using only a few lights.

**Review by AThousandShips — COMMENTED** [review]
My bad had missed some in my first pass

**Review by reduz — APPROVED** [review]
Absolutely outstanding work!!

**Comment by reduz** [comment]
I still wonder why the GLES2 version of Godot is faster, what do we do different there?

**Comment by BastiaanOlij** [comment]
@reduz maybe it's faster because we don't do any of the HDR lighting calculations? All lighting is kept LDR while here we do some conversions to/from HDR while we write out LDR?

**Review by BastiaanOlij — APPROVED** [review]
I'll find some time to properly test this in VR as soon as I can but as far as I can tell this looks sublime! Amazing stuff Clay!

**Comment by clayjohn** [comment]
> I still wonder why the GLES2 version of Godot 3 is faster, what do we do different there?

Those measurements were taken with the old version of this PR. Back then we did an additional pass per light with shadows. Now the base pass includes one shadowed light so it is much faster

**Comment by Calinou** [comment]
I've run benchmarks again on the latest revision of this PR (same hardware as my prior test, also in 3840×2160):


3.5.2 GLES3 | 3.5.2 GLES2 | `master` Forward+ | `master` Mobile | `master` Compatibility<br> *(no shadows)* | 4.x Compatibility<br> *(this PR)*
-|-|-|-|-|-
1705 FPS (0.59 mspf) | 2550 FPS (0.39 mspf) | 1249 FPS (0.80 mspf) | 1247 FPS (0.80 mspf) | 2890 FPS (0.35 mspf) | 1828 FPS (0.55 mspf)

Directional shadow rendering still appears broken in the running project, even though it works in the editor:

Screenshot_20230928_143329 webp

In comparison, this is how the scene looks like in Forward+:

Screenshot_20230928_143932 webp

Visual comparison in the editor:

Forward+ | Mobile | Compatibility
-|-|-
Screenshot_20230928_143726 webp | Screenshot_20230928_143744 webp | Screenshot_20230928_143751 webp

**Comment by YuriSizov** [comment]
Woohoo! Thanks!

**Comment by clayjohn** [comment]
Just noting a comment from the top post:

> There is still one outstanding bug where shadow atlas textures are getting out of date with multiple shadowed lights in the scene.

I'll investigate that outstanding bug and any new reports ASAP

**Pull request merged**
