### PR TITLE
Improved A-star (adapted from #7823)

### PR DESCRIPTION
**Pull request by ghost**
Created a reviewable PR for @supagu's patch in #7823 because it sounded interesting (adapted to 3.0 branch).

### CODE REVIEW

**Comment by SaracenOne** [comment]
This looks cool. It might actually help a lot with some of the AI experiments I'm doing.

**Comment by akien-mga** [comment]
If you've reached a consensus on what the API should be like in #7823, this PR would need a rebase to fix the merge conflicts (you might want to check https://github.com/godotengine/godot/issues/7955#issuecomment-284265872 for tips on rebasing past the reformat commit).

**Comment by tagcup** [comment]
This PR was just meant to be temporary reference, such that others can review it. @supagu do you want to submit a new PR according to the latest discussions in #7823? In any case, I'm closing this one

**Comment by supagu** [comment]
Opened a new PR. See https://github.com/godotengine/godot/pull/8146

**Pull request closed without merging**
