### PR TITLE
Fixes a bug in multimesh_instance_get_color

### PR DESCRIPTION
**Pull request by H4kor**
Found while trying to fix another bug.

### CODE REVIEW

**Comment by reduz** [comment]
This is not a bug, this is intended. color data beings after the transform, so it needs to be offseted by the amount of floats in an xform

**Comment by H4kor** [comment]
No, the current version is wrong. On master it adds the `color_floats` to the offset, but the patch changes this to adding `xform_floats` to the offset. 
+ The byte version is broken.

If you want to test this, here is a project that sets the color to (1,0,0,1) and reads it back to the console.
https://www.dropbox.com/s/cx6vo1zk4lbad2w/multimesh_color.zip?dl=0

**Comment by H4kor** [comment]
@reduz or @kubecz3k : please re-open this PR.

**Comment by bojidar-bg** [comment]
Reopening, seems to be still valid to me.

**Comment by reduz** [comment]
Apologies, I misread your fix, its perfectly valid

**Pull request merged**
