### PR TITLE
Update freetype to 2.10.4

### PR DESCRIPTION
**Pull request by volzhs**
it's updated at 2020-10-10 :smile: 

edit : updated again from 2.10.3 to 2.10.4

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs a rebase to fix CI (temporary issue on `master`, not linked with this PR).

**Comment by akien-mga** [comment]
Could you update directly to 2.10.4 released today? Security fix.
https://www.phoronix.com/scan.php?page=news_item&px=FreeType-2.10.4-Released

**Comment by volzhs** [comment]
it's updated to 2.10.4

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
