### PR TITLE
Fix regression in visual nodes hotzones (reverted)

### LINKED ISSUE #78555: Hotzones of visual shader nodes are too small
### Godot version

4.1

### System information

Fedora, RX 590

### Issue description

Between 4.0.2 release and 4.0.3 RC1 the hotzone of the visual shader nodes have shrunk on the side that overlaps the node itself.
Screenshot from 2023-06-22 12-14-19

### Steps to reproduce

Download 4.0.2 release and 4.0.3-rc1. 

Open MRP, navigate to hotzone.tres shader.

Zoom out to this level of zoom: 
image

Try to extract a pin from ColorOp node.

In 4.0.3 you can observe how if you're not very precise you will drag the node around.

### Minimal reproduction project

[hotzone.zip](https://github.com/godotengine/godot/files/11832820/hotzone.zip)

### PR DESCRIPTION
**Pull request by QbieShay**
Fixes https://github.com/godotengine/godot/issues/78555

### CODE REVIEW

**Comment by QbieShay** [comment]
I wrote it on the issue (ups) but this PR does re-introduce the bug with the eye icon being hard to click. I do think however it is an acceptable casualty considering how finnicky it became to make a VS right now.

**Comment by YuriSizov** [comment]
@QbieShay Could you please amend your commit message though?

**Comment by QbieShay** [comment]
Done

**Review by KoBeWi — APPROVED** [review]
> this PR does re-introduce the bug with the eye icon being hard to click.

I tested and didn't notice such bug. The port clashes with eye icon on high zooms, but it happens even without this PR.
I can confirm the PR fixes a bug with low zoom.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
