### PR TITLE
Fix expression node crashes

### LINKED ISSUE #29960: Editor crash when using VisualShaderNodeGroupBase::set_inputs
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fab513f4f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::set_inputs(String const&) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1767 (discriminator 2))
[5] MethodBind1<String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fab513d7b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 5d147e55c127b5bf7af79bf1f9166de5cf293f1f
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/5d147e55c127b5bf7af79bf1f9166de5cf293f1f.zip

### LINKED ISSUE #29963: Editor crash when using VisualShaderNodeGroupBase::set_outputs(String const&)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f0ede552f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::set_outputs(String const&) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1799 (discriminator 2))
[5] MethodBind1<String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f0ede535b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 11509a07e3a8ce47db70c254c102e93049e01eb0
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/11509a07e3a8ce47db70c254c102e93049e01eb0.zip

### LINKED ISSUE #29981: Editor crash when using VisualShaderNodeGroupBase::remove_input_port(int)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fec5d270f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::remove_input_port(int) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1867 (discriminator 1))
[5] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fec5d253b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 91123faa29e2679bdf08256f1f4edf04eb9ad4a1
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/91123faa29e2679bdf08256f1f4edf04eb9ad4a1.zip

### LINKED ISSUE #29982: Editor crash when using VisualShaderNodeGroupBase::remove_output_port(int)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f8be6401f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::remove_output_port(int) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1935 (discriminator 1))
[5] MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[7] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[8] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[9] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[10] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[11] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[14] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[15] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[16] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[17] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[18] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[19] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[20] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f8be63e4b6b] (??:0)
[21] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 35e36ec43eaf28a3b2d69f853c28b6d70d23772e
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/35e36ec43eaf28a3b2d69f853c28b6d70d23772e.zip

### LINKED ISSUE #29983: Editor crash when using VisualShaderNodeGroupBase::set_input_port_name(int, String const&)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f65da640f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::_apply_port_changes() (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:2104)
[5] VisualShaderNodeGroupBase::set_input_port_name(int, String const&) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1992)
[6] MethodBind2<int, String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f65da623b6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)

```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 0fe11b5318a1694940cf900b202806a3fe8c841d
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/0fe11b5318a1694940cf900b202806a3fe8c841d.zip

### LINKED ISSUE #29984: Editor crash when using VisualShaderNodeGroupBase::set_input_port_type(int, int)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fca7a807f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::_apply_port_changes() (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:2104)
[5] VisualShaderNodeGroupBase::set_input_port_type(int, int) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:1962)
[6] MethodBind2<int, int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fca7a7eab6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 8ce0b88c82a2f9df6ef76a032995e73d4aac5440
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/8ce0b88c82a2f9df6ef76a032995e73d4aac5440.zip

### LINKED ISSUE #29985: Editor crash when using VisualShaderNodeGroupBase::set_output_port_name(int, String const&)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fb9e9feaf60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::_apply_port_changes() (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:2111)
[5] VisualShaderNodeGroupBase::set_output_port_name(int, String const&) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:2051)
[6] MethodBind2<int, String const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fb9e9fcdb6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit ec599eeb36c7876dc92cc950956966641ae4a4c4
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/ec599eeb36c7876dc92cc950956966641ae4a4c4.zip

### LINKED ISSUE #29986: Editor crash when using VisualShaderNodeGroupBase::set_output_port_type(int, int)
**Godot version:**
3.2.dev.custom_build. 02319dceb

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f9d5a287f60] (??:0)
[2] CowData<String>::get(int) const (/home/rafal/Pulpit/godot/./core/cowdata.h:151 (discriminator 7))
[3] Vector<String>::operator[](int) const (/home/rafal/Pulpit/godot/./core/vector.h:85)
[4] VisualShaderNodeGroupBase::_apply_port_changes() (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:2111)
[5] VisualShaderNodeGroupBase::set_output_port_type(int, int) (/home/rafal/Pulpit/godot/scene/resources/visual_shader.cpp:2022)
[6] MethodBind2<int, int>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:1523 (discriminator 19))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1073 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1086)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1922)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x1390871] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f9d5a26ab6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x13906da] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit aad0964763c3ef31021dcb87e24cfc943d14dbea
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/aad0964763c3ef31021dcb87e24cfc943d14dbea.zip

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #29960
Fix #29963 
Fix #29981 
Fix #29982 
Fix #29983 
Fix #29984 
Fix #29985 
Fix #29986

### CODE REVIEW

**Comment by LinuxUserGD** [comment]
Isn't this similar to this PR?
#29980

**Comment by Chaosus** [comment]
Err.. I see now

**Comment by Chaosus** [comment]
Ok, let the @Dentrax to fix these crashes instead

**Comment by akien-mga** [comment]
I prefer the fixes in this PR for the VisualShader issues.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
