### PR TITLE
2to3 exporter: Fix NodePath prop remaps in .scn

### PR DESCRIPTION
**Pull request by akien-mga**
The previous fix from 13d1df2e4b was applied when writing the NodePath
as text for .tscn/.tres, and thus not used for .scn. So we move the
conversion earlier, while processing all tracks.

@laverneth Could you test this one too? :)

### CODE REVIEW

**Comment by laverneth** [comment]
Yep. It works !
Good job.

**Comment by akien-mga** [comment]
Thanks for testing :)

**Comment by laverneth** [comment]
I think there ils also an issue in scale and position, I'll make a bug
tomorrow asap.

**Comment by laverneth** [comment]
Added a new test with scaling and position as NodePath props. I haven't been able to test with the latest version of godot 2.0.1 however I had the issue yesterday.
[test_export.zip](https://github.com/godotengine/godot/files/1775113/test_export.zip)

**Pull request merged**
