### PR TITLE
Replace invalid chars in pasted text in LineEdit

### PR DESCRIPTION
**Pull request by ptrojahn**

### CODE REVIEW

**Comment by reduz** [comment]
What are the invalid chars exactly? Is there an issue open about this?

**Comment by Calinou** [comment]
LineEdit isn't *supposed* to contain multi-line text, however, it's apparently possible to paste line feed and tab characters into LineEdit.

Here's a LineEdit where I pasted a line feed where the cursor is placed – pressing <kbd>←</kbd> or <kbd>→</kbd> will cause the cursor to stand still, since it's moving back and forth the line feed character:

image

**Comment by ptrojahn** [comment]
It's interesting that for you the character has no width. For me, new line and tab characters get replaced by question marks:
image

**Comment by Calinou** [comment]
@ptrojahn The screenshot I made is from a running project, which uses the default bitmap font (instead of the editor font, which is a DynamicFont with a larger character set).

**Comment by akien-mga** [comment]
We discussed this on IRC and approved the proposal to strip those characters, but decided on a different approach using `String::strip_escapes()` to strip all non-printable control characters (`< 32` in the ASCII table). Thanks for the contribution nevertheless!

**Pull request closed without merging**
