### PR TITLE
Enable EditorPlugin to add/remove autoloads

### PR DESCRIPTION
**Pull request by willnationsdev**

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
@hpvb Might be considered for cherry-picking.

**Comment by willnationsdev** [comment]
@akien-mga ? It's already merged...Wouldn't a cherry-pick add the commit again? I'm confused...

**Comment by akien-mga** [comment]
It's merged in the master branch, the cherry-pick label is about 3.0.x

**Comment by willnationsdev** [comment]
ah.

Also, I just noticed something off here. `editor_autoload_settings.cpp`, line 543, sets up a "set_persisting" value for the node to true when it undoes removal (sounds correct), but that property is never messed with during the `autoload_add` method. I can't seem to locate `set_persisting` in `ProjectSettings` or `Object`, so I'm not sure what that may be a reference to...

**Comment by willnationsdev** [comment]
Oh, nevermind. It should probably be fine. The original code was only ever doing it in the deletion process anyway. Ignore me.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
