### PR TITLE
Improve RichTextLabel `install_effect()` documentation

### PR DESCRIPTION
**Pull request by Calinou**
See https://forum.godotengine.org/t/trying-to-make-the-highlight-of-a-richtextlabel-blink/38042/7.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
LGTM

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.

**Pull request merged**
