### PR TITLE
Respect text editor highlighting color changes

### LINKED ISSUE #14838: Text editor color settings have no effect
**Godot 3.0 beta**

I set the color for comments in the script editor. But it changes nothing in reality.

### PR DESCRIPTION
**Pull request by volzhs**
Fix #14838 

editor-color

- Text color will be updated based on current color scheme (Adaptive or Default)
- `Text Editor/Theme` will be changed to `Custom` automatically

### CODE REVIEW

**Comment by djrm** [comment]
Nice, but this has to be also applied to shader code editor.

**Comment by volzhs** [comment]
oh. i will check that.

**Comment by volzhs** [comment]
done to shader code editor too.

**Comment by Paulb23** [comment]
You'll need to add checks inside of `load_text_editor_theme`, `save_text_editor_theme` and `save_text_editor_theme_as` for "custom"

**Comment by volzhs** [comment]
@Paulb23 done :)

**Pull request merged**
