### PR TITLE
Added method to clear input events of an action

### PR DESCRIPTION
**Pull request by AndreaCatania**
Added API that make easy the input event cleaning

### CODE REVIEW

**Comment by groud** [comment]
I would name it with "clear" inside, it will avoid mistypes with the single event version.

**Comment by AndreaCatania** [comment]
I thought it, but it seems more consistent like now.. The miss typing is difficult because you need to put the event in the case you want to clear the single event.

Also I would rename the function `get_action_list` to `get_action_events`, It returns the list of events but the name doesn't imply it

**Comment by groud** [comment]
Well I don't know, I'd say "clear" is explicit enough. Might be discussed though

**Comment by groud** [comment]
@mhilbrunner, we could have discussed the naming in a PR meeting... ^_^"

**Comment by mhilbrunner** [comment]
@groud Sorry, you're right, but I agreed with your `I'd say "clear" is explicit enough. ` Also, IMO `clear` would be inconsistent with the method for erasing a single event.

If someone wants to discuss this, we can do that and rename at in a new commit. Sorry!

**Comment by groud** [comment]
> Also, IMO clear would be inconsistent with the method for erasing a single event.

Well, "clear" is a really common shorcut for "erase all". I would have said `action_erase_all_events()` would have been sufficient to perfectly distinguish the two functions, but `clear` is far more common.
I think `action_clear_events()` would have been the most obvious and expected option. But well, it's not really important I guess.

**Pull request merged**
