### PR TITLE
Avoid infinite loop in GDScript at shutdown

### LINKED ISSUE #42339: Engine hangs on exit after executing GDScript unit tests using GUT
**Godot version:**
3.2.4 beta 4162df439727fad01b0d1240df69f59ba97ed422.
Related to #42305. (CC @RandomShaper).

**OS/device including version:**
Tested on Windows 10, Linux server platforms.

**Issue description:**
After #42323, the crash is resolved, but the engine hangs after all tests are finished. When I pause the debugger, occasionally this ends up with a call stack similar to this:
```
godot.windows.tools.64.goost.exe!Ref<class Script>::Ref<class Script>(void) (Unknown Source:0)
godot.windows.tools.64.goost.exe!GDScriptLanguage::~GDScriptLanguage() Line 2256 (d:\usr\src\godot\goostengine\goost\godot\modules\gdscript\gdscript.cpp:2256)
godot.windows.tools.64.goost.exe!GDScriptLanguage::`scalar deleting destructor'(unsigned int) (Unknown Source:0)
godot.windows.tools.64.goost.exe!memdelete<GDScriptLanguage>(GDScriptLanguage * p_class) Line 119 (d:\usr\src\godot\goostengine\goost\godot\core\os\memory.h:119)
godot.windows.tools.64.goost.exe!unregister_gdscript_types() Line 180 (d:\usr\src\godot\goostengine\goost\godot\modules\gdscript\register_types.cpp:180)
godot.windows.tools.64.goost.exe!unregister_module_types() Line 228 (d:\usr\src\godot\goostengine\goost\godot\modules\register_module_types.gen.cpp:228)
godot.windows.tools.64.goost.exe!Main::cleanup() Line 2255 (d:\usr\src\godot\goostengine\goost\godot\main\main.cpp:2255)
godot.windows.tools.64.goost.exe!widechar_main(int argc, wchar_t * * argv) Line 164 (d:\usr\src\godot\goostengine\goost\godot\platform\windows\godot_windows.cpp:164)
godot.windows.tools.64.goost.exe!_main() Line 184 (d:\usr\src\godot\goostengine\goost\godot\platform\windows\godot_windows.cpp:184)
godot.windows.tools.64.goost.exe!main(int _argc, char * * _argv) Line 196 (d:\usr\src\godot\goostengine\goost\godot\platform\windows\godot_windows.cpp:196)
[Inline Frame] godot.windows.tools.64.goost.exe!invoke_main() Line 78 (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78)
godot.windows.tools.64.goost.exe!__scrt_common_main_seh() Line 288 (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
kernel32.dll!00007ffe5d5e7bd4() (Unknown Source:0)
ntdll.dll!00007ffe5d9ace51() (Unknown Source:0)
```

Seems to happen on project `get_tree().quit()` once tests are finished.

See GUT log at https://github.com/goostengine/goost/runs/1164928377, where the testing stage kept running for 5 hours, until it got automatically cancelled by GitHub, which fail CI result.

**Steps to reproduce:**
Likely running some GUT tests could reproduce this, but in case if you need the exact state:

```bash
git clone https://github.com/goostengine/goost
cd goost
scons
```
Then run GUT tests using the `tests/run.sh` with the resulting binaries, or manually...

**Minimal reproduction project:**
I haven't yet created a minimal project to test this out, seems to happen with more complex testing procedures, but perhaps this could already provide some insights.

### PR DESCRIPTION
**Pull request by RandomShaper**
I have to say I haven't been able to find a reproduction project. That said, I'm 90% sure I understood why the freeze was happening. The old approach was assuming the current first element of the list was freed for sure as a consequence of the current step. However, that's not guaranteed, so the way it was looping could lead to getting stuck at a the current first element.

The new approach ensures the loop is able to move on and traverse the list up to the end.

@Xrayez, I've tried using this on top of the _gd3_ branch in Goost, but I have experienced some build issues on Windows, so I'd be very grateful if you could test this PR yourself. (This is trivially cherry-pickable in to 3.2.)

Fixes #42339.

### CODE REVIEW

**Comment by Xrayez** [comment]
Yes, this fixes #42339, at least on my machine. 🙂

> I've tried using this on top of the gd3 branch in Goost, but I have experienced some build issues on Windows

I guess that's because it forcefully resets the working tree, so even if you applied the patch manually, it would remove it? Should probably make it optional, but in any case, that's just a module which can be compiled in the same way as the other modules in Godot.

Anyways, sorry for not providing a reproduction project in a timely manner, I couldn't reproduce this either with simple test scripts.

**Comment by akien-mga** [comment]
Thanks!

**Comment by RandomShaper** [comment]
Thanks for testing, @Xrayed.

I noticed what you describe and disabled that code path to avoid the reset, but I was getting some error related to modules. Next time I'm in front of my PC, I'll tell you exactly what it was.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
