### PR TITLE
Improve the SnapGrid editor icon

### LINKED ISSUE #819: Tweak GridSnap editor icon to not look like an abbreviation for "Antialiasing" in Chinese
The current icon for [Grid Snap](https://github.com/godotengine/godot-design/blob/e88d4958b835497776d36f5bac397ecdda63adb0/engine/icons/svg/icon_snap_grid.svg) looks very similar to the Chinese character "抗"(anti-), which is often used as an abbreviation for "抗锯齿"(anti-aliasing) in a graphic software context.

The current icon looks like this on the toolbar. As a native speaker, I can't resist thinking it's an antialiasing toggle every time I look at the button in Godot :(

current

I suggest using a more "grid" like graphic like this (icon taken from [here](https://www.iconfinder.com/icons/612278/grid_magnet_magnetic_snap_icon))

sample

### PR DESCRIPTION
**Pull request by timothyqiu**
Make the icon more grid-like and snap to the 16x16 grid.

Closes https://github.com/godotengine/godot-proposals/issues/819

100% Scale
ksnip_20220113-231409

200% Scale
ksnip_20220113-232828

<details>
<summary>Previous Version</summary>

100% Scale
x1

200% Scale
x2

</details>

For `3.x` cherry-pick: `SnapGrid.svg` → `icon_snap_grid.svg`.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Looks way too noisy for such a small icon.

**Comment by timothyqiu** [comment]
Here's an alternate version:

ksnip_20220113-225554

In order to stick with the 16x16 grid, there's not much thickness choices...

**Comment by akien-mga** [comment]
How about keeping 3 lines/3 columns with width 1, and just make the grid 15x15 in the top-left corner? So there's one empty line on the right and bottom sides, and the bottom right corner of the magnet touches the bottom right corner.

**Comment by timothyqiu** [comment]
Thanks for the suggestion :) I think it looks better now, two small variants:

With center pixel connected:

ksnip_20220113-231409

With center pixel disconnected:

ksnip_20220113-231726

**Comment by YeldhamDev** [comment]
Much better. I personally prefer the latter version.

**Comment by timothyqiu** [comment]
Updated the 200% scale version for easy comparison.

**Comment by akien-mga** [comment]
I'd go with the connected version, looks great IMO.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
