### PR TITLE
`.scons_env.json` logging improved

### PR DESCRIPTION
**Pull request by Repiteo**
- Many more types are now serialized
- Any remaining unserialized types now have the same `pprint` wrapper SCons utilizes
- File guaranteed to export as utf-8; allows `ensure_ansi` to be disabled

### CODE REVIEW

**Comment by Repiteo** [comment]
Oh that is... A lot of failed runs

Maybe the defines are different from the latest SCons versus 3.0? Gonna have to look into this further, whoops

**Comment by akien-mga** [comment]
Could you clarify what's your use case for this, what the output looks like before and after, and whether this impacts build time?

**Comment by Repiteo** [comment]
Sure thing!
- **use case**: In local testing, I noticed that the `env.Dump()` method from SCons 4.0 had a `pretty` option in addition to the `json` option that's very similar to what we use — the former was quite a bit more verbose because it ended up natively serializing more types. At first this was just pretty-printing the non-serialized types, which technically worked, but it ended up as long strings for a lot of the types and I really wanted the proper json representation instead. So I dug into a lot of the classes that weren't serialized but really should be & implemented simple logic to have them display in a human-readable format. This is all to the end of making this debugging file much more usable for debugging
- **diff**: https://gist.github.com/Repiteo/45a92567fea3ea3ea01d6cdb0f6c419f
- **build time**: `methods.dump()` before ≈ 0.00102s, after ≈ 0.00203s. Ended up being roughly twice as long, but the original method was already *extremely* fast, so it safely remains a drop-in-the-bucket for overall build time

**Comment by Repiteo** [comment]
Added a few more serializations, and made all conversions one-liners: https://gist.github.com/Repiteo/388bbdf82ff7c4cd5d4d5e37e6bdfaa5

Also, the build time might be even less impacted than I thought. I'm actually getting ranges from 10-20ms with no real consistency from what I can find, so that range may very well be inherent to the function regardless of what all has been added

**Comment by Repiteo** [comment]
Better parsing logic was added to SCons upstream, so this is no longer needed.

**Pull request closed without merging**
