### PR TITLE
Fix failing CI, due invalid importing of resources

### PR DESCRIPTION
**Pull request by qarmin**
This should fix errors about leaks(due not importing all resources properly) like in this run - https://github.com/godotengine/godot/pull/43049/checks?check_run_id=1329394149

Godot for now doesn't have any method to safely import all resources.
The best option would be to create a command line argument to import all assets - https://github.com/godotengine/godot-proposals/issues/1362

Importing is done 3 times, because I want to be sure that everything should works fine.

### CODE REVIEW

**Comment by akien-mga** [comment]
Why did CI start failing now? It uses to work fine for weeks.

Having two runs of 25 s each before the last one feels pretty hacky and might add extra time to an already fairly long build... I'll merge as is to fix CI but I'd like to see this improved further.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by qarmin** [comment]
Before RegressionTestProject doesn't have any images/resources which needs to import(even icon.png was missing), so it will work even without opening editor.

But yesterday I pushed new commit with 2 new images - 32x32 icon.png(~7KB) and 512x512 icon.png(~60KB) and since this time, CI started to fail randomly.

Godot with address sanitizer opens editor a little longer than normal and 25s should be enough to calmly import all assets, but as CI shows, this doesn't work.

This looks like a bug in Godot, but I don't know for now what is cause of this behavior and even how to debug it.

**Comment by akien-mga** [comment]
Some PRs are failing due to these new changes: https://github.com/godotengine/godot/pull/43126/checks?check_run_id=1336423811

I think it would be better to pin a specific commit of RegressionTestProject so that CI doesn't break on updates, and test updates you want to make by changing the pinned commit in a PR. Having unrelated PRs fail their CI checks due to third-party repo changes is not a good workflow.

**Comment by qarmin** [comment]
Now it shouldn't break on any project updates, because project CI is almost same as Godot CI(have 2 not 3 editor opening steps and run project for 60 second instead 20, so it should easier find bugs).
 
https://github.com/qarmin/RegressionTestProject/blob/3.2/.github/workflows/linux_builds.yml

For this reason I think that pinning a specific version of the project is not necessary (until of course there are some bugs in the latest version, but CI should prevent this)

**Comment by akien-mga** [comment]
Sounds good, if you test changes with the same CI job on RegressionTestProject before merging, that's fine with me to keep tracking HEAD indeed.

**Pull request merged**
