### PR TITLE
Tweak lightmapper warning message to mention Rosetta emulation on macOS

### PR DESCRIPTION
**Pull request by Calinou**
See https://github.com/godotengine/godot/issues/48082.

### CODE REVIEW

**Comment by bruvzg** [comment]
Might be worth mentioning it in the https://godotengine.org/article/godot-3-3-has-arrived#lightmapper and release notes as well.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
We should remember to revert this once embree-aarch64 is integrated :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Comment by akien-mga** [comment]
I added a mention to it in the blog post:

Screenshot_20210422_181113

**Comment by akien-mga** [comment]
> We should remember to revert this once embree-aarch64 is integrated :)

Done with 0a4eb472cfe0d02e11ee02bc741e4c03f7a34e0f.

**Pull request merged**
