### PR TITLE
[4.0] Fix output port type mismatch for some VisualScript nodes

### PR DESCRIPTION
**Pull request by TheWathis**
#51084 brought bug with it.
Visual nodes snapped, lerp, lerp_angle, inverse_lerp, range_lerp, smoothstep and move_toward had a float output before #51084
After the PR theses nodes had the output 'any'

Before fix:
image

After fix:
image

### CODE REVIEW

**Comment by haskaris** [comment]
This PR was initially designed to fix the float, but since I'm looking at the code, I can fix other thing related to theses function, like:
image
This function return a 'any' value (Variant::NIL in the code), but -1, 0 or 1 according to the doc. So it should be an integer

Could also group cases by type to uniform the code

**Review by aaronfranke — APPROVED** [review]
Aw man, I really should have been paying more attention to this code.

**Comment by akien-mga** [comment]
The fix looks good, could you amend the commit message to be more explicit? The commit should describe what it fixes in the engine, not only refer a GitHub issue or PR.

So here it could be something like:
```
Fix output port type mismatch for some VisualScript nodes

This was a regression from #51084.
```

You can amend the message with `git commit --amend` and update the PR with `git push --force`.

**Comment by Gallilus** [comment]
> This PR was initially designed to fix the float, but since I'm looking at the code, I can fix other thing related to theses function, like:

@haskaris 
Do you intend to folow up on this PR?
I quickly checked the status of buildinFunc 3.4.beta2
image

**Comment by haskaris** [comment]
I didn't want to make a mistake with the PR, that's why I asked earlier. But I'll take care of it

**Comment by haskaris** [comment]
I've fixed the nodes that mismatched output port type
Before (every function with 'any' output)
image
After
image
For the nodes that still have 'any' output, I honestly don't know how to fix theses since it's dynamic. Plus since it's dynamic it's not really a mismatch.

**Comment by Gallilus** [comment]
I think you are supposed to squash your commits in to one.
This is looking good I will try to make time, next weekend at the latest, to do a function test  of all the basic nodes.

**Comment by haskaris** [comment]
I'd need help to do a proper squash... I've already made a lot of mistakes on #51122

**Comment by haskaris** [comment]
Now at #51147
Since I had the wrong branch

**Pull request closed without merging**
