### PR TITLE
Bug/lsp ignore $ notifications

### PR DESCRIPTION
**Pull request by ofrank123**
Ignores $/ notification so that an error is not thrown to client.  This is per the [LSP specification](https://microsoft.github.io/language-server-protocol/specification.html#dollarRequests).  Also adds an option so users can choose whether non-standard messages are sent (in particular the gdscript/capabilities and gdscript_client/changeWorkspace messages).

### CODE REVIEW

**Comment by akien-mga** [comment]
This needs to be merged in `master` first (in a separate PR) before it can be considered for the `3.2` branch.

**Comment by akien-mga** [comment]
I guess this is related to #42070, CC @Razoric480 for review.

**Comment by Razoric480** [comment]
Didn't see this one when I made mine.

This looks like a more comprehensive solution, in that it could be later extended if we want to actually implement those notifications, whereas mine went for the smallest unit of code that would do the job of ignoring $ messages.

So it might depend on just which direction we'd want to go with.

**Comment by akien-mga** [comment]
Superseded by #42070.

**Pull request closed without merging**
