### PR TITLE
Allow boolean operators for all Variant types

### LINKED ISSUE #44688: GDScript: logical and/or between non boolean  value cause a parser error
**Godot version:** 7d972b8c6

**OS/device including version:** windows10

**Issue description:**
if both operands of the and/or operator are compile time known non boolean values, the parser throws error (where it shouldn't)
```gdscript
func _ready():	
	if "" or []:
		pass
## Parse Error: Invalid operands "String" and "Array" for "or" operator.
```

**Minimal reproduction project:**
N/A

### PR DESCRIPTION
**Pull request by vnen**
- Add `OP_NOT` for all types in Variant.
- Allow any opeand for `and` and `or` in GDScript. Those have short-circuit semantics and do not rely on Variant operators.

Fix #44688

### CODE REVIEW

**Comment by DaloLorn** [comment]
So... what's the status on this PR? I was hoping to continue porting my game to 4.x when 4.1 released (got halfway through before finding out about #44688 the hard way...), but at the rate it's going, I'm starting to worry it might not *get into* 4.1 in the first place. 😟

**Comment by akien-mga** [comment]
That hardly seems like a game breaking bug? You can simply be explicit about casting to booleans.

**Comment by DaloLorn** [comment]
Yeah, I was just about to point that out. 😂

**Review by adamscott — APPROVED** [review]
Looks good to me for a merge in 4.1

Thanks @vnen for the PR and the extensive unit tests.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
