### PR TITLE
Added API to propagate checkmarks to children and parents.

### LINKED ISSUE #4829: add "export all resources into SELECTED directories"
**Operating system or device - Godot version:**
official 2.0.3stable

**Issue description** (what happened, and what was expected):
When exporting a project, the editor currently offers these 3 methods regarding resources : 

1. Export selected resources (including dependencies)
2. Export all resources into the project.
3. Export all files in the project directory.

The first option requires you to select EACH file one after each other, and there is no way to select ALL the resources that are contained into a directory.

It could be cool it was possible to apply a default action ("export" or "bundle" or "--") to all the files contained into a directory.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

### PR DESCRIPTION
**Pull request by Phischermen**
Fixes #4829 

Old Behavior
OldBehavior

New Behavior
NewBehavior

This also adds a new method to TreeItem called get_next_checked() which returns the next tree item affected last time set_checked() was called. This allows the user to respond to each check/uncheck that results from the original check/uncheck.

I have started to refactor some things like the asset installer and the project export dialog to take advantage of this behavior, but it won't be done until I can finish testing. I'd also like to try and write a test for this, to ensure it's working as intended.

### CODE REVIEW

**Comment by Phischermen** [comment]
I found and modified the gui unit test, but I can't figure out how to run it. I was expecting to run it via --sf="\*test_gui\*" but that doesn't appear to run the test.

**Comment by dreamsComeTrue** [comment]
If at least one child is unchecked - shouldn't the parent indicate that somehow visually (like replacing 'check' mark icon with 'minus' icon, like in other software) ?

**Comment by Phischermen** [comment]
@dreamsComeTrue That would be cool. I'll see about adding that!

**Comment by Phischermen** [comment]
I added indeterminate checkmarks to this PR. Here is how they appear in the application.
CheckDemonstration
The icon's name is "indeterminate".

**Comment by pycbouh** [comment]
We definitely use this pattern a lot in the editor, but do we actually want this to be the default and only behavior? I would probably opt for a way to mark a column as check-propagate-able, which would turn this behavior on for it.

Same goes for the intermediate state.

For an example of a more complex behavior with propagating checks see the new theme editor's import items dialog.

**Comment by KoBeWi** [comment]
Yeah, see #43538 for example. Usually when you have check propagation, you want some more logic along with it. So having this done automatically is rather undesired, unless there is a way to know which items were checked as a result of propagation (in which case you'd have to update the currently used "propagators" to your new system).

I like the indeterminate checkmarks though.

**Comment by groud** [comment]
Same opinion as @pycbouh and @KoBeWi for me. I think it's better to leave this choice to the user and keep the behavior simple by default.

**Comment by Phischermen** [comment]
@KoBeWi Coincidentally, I used the project export tree to test my new check marks. I'm aware that every time the check status changes, a collection needs to be updated. I added a method called TreeItem::get_next_affected_by_check() which allows the user to iterate through the propagators. For testing purposes, I modified project_export.cpp to like this
```
while (item) {
  String path = item->get_metadata(0);
  if (!path.ends_with("/")) {
	  bool added = item->is_checked(0);
	  if (added) {
		  current->add_export_file(path);
	  } else {
		  current->remove_export_file(path);
	  }
  }
  item->get_next_affected_by_check();
}
```
The loop ends when item is null, which will happen once the root is reached.
I plan on changing stuff like this in a separate PR.

@pycbouh I'll take a look at the new theme import dialogue. Adding a method to disable indeterminate checks and check propagation won't be hard. I'll update this as soon as I can!

**Comment by KoBeWi** [comment]
> I plan on changing stuff like this in a separate PR.

Shouldn't it be done now? Otherwise the PR will break stuff.

**Comment by Phischermen** [comment]
@KoBeWi Good point! I'll do it in this PR after I finalize the new check behavior.

**Comment by Phischermen** [comment]
I have refactored EditorAssetInstaller, ThemeItemImportTree, and ProjectExportDialog to use my new methods. It was not necessary to "turn off" check propagation to achieve this. Since I didn't have to do that, I would prefer not to implement a method to mark columns as propagatable, at least not until we absolutely need it.

**Comment by pycbouh** [comment]
My main concern wasn't if we could adapt all of our editor UIs to this, but if it's a good idea to make it the default for users. So I would still make it optional and opt-in.

**Comment by Phischermen** [comment]
I made the behavior optional. It now has to be enabled by calling Tree::set_column_propagate_checks().

**Comment by groud** [comment]
In my opinion, I still think such behavior should be coded by the user of the Tree node. It makes the Tree API more complex for something quite specific, while the Tree API is already very complex.

I am not against adding an API to allow implementing the "indeterminate" status though.

**Comment by Phischermen** [comment]
@groud Although it does make the Tree API a little more complex, it reduces complexity in other parts of the engine by erasing check helper methods that all mostly do the same thing. Instead of having EditorAssetInstaller::_update_subitems(), EditorAssetInstaller::_uncheck_parent(), ThemeItemImportTree::_update_parent_items(), ProjectExportDialog::_check_dir_recursive(), and ProjectExportDialog::_refresh_parent_checks(), all that logic can be represented in  small and digestable while loops in the item_edited callback method. Each of those helper methods would get more complex if I added an API for "indeterminate" status rather than an API for propagating checkmarks. 

Although this does solve a specific problem, that being "checking and unchecking lots of items in a list is inconvenient," it is a problem that appears often in game development. Users write all kinds of importers and exporters, and I think all of them would rather put their focus on the functionality of the tool than its UX. I anticipate almost all would be excited by the prospect of making their tools more convenient with less programming.

**Comment by groud** [comment]
> @groud Although it does make the Tree API a little more complex, it reduces complexity in other parts of the engine by erasing check helper methods that all mostly do the same thing. Instead of having EditorAssetInstaller::_update_subitems(), EditorAssetInstaller::_uncheck_parent(), ThemeItemImportTree::_update_parent_items(), ProjectExportDialog::_check_dir_recursive(), and ProjectExportDialog::_refresh_parent_checks(), all that logic can be represented in small and digestable while loops in the item_edited callback method. Each of those helper methods would get more complex if I added an API for "indeterminate" status rather than an API for propagating checkmarks.

I'd rather have the "checking propagation" made a helper method then. The current API is quite simple, as each TreeItem is independent from one another, and there's almost no internal behavior impacting several TreeItem at once. If you want to create methods like `propagate_check()` and `uncheck_parents` or something like that, I am ok with it. I don't mind helper functions that much, as they don't do things behind the user's back.

And no, adding a method of "undeterminate" status does not make the API more complex, it makes it simpler in fact. Basically because it's very explicit to the user, while an internal status changing in some situation (but not accessible) is quite confusing.

**Comment by Phischermen** [comment]
> Basically because it's very explicit to the user, while an internal status changing in some situation (but not accessible) is quite confusing.

I see. What would you think of this:

Right now set_checked() can do one of two things based on whether the user has called set_column_to_propagate_checks().

I can split set_checked() into two methods, set_checked(), which sets but does not propagate, and set_checked_propagate(), which sets but also propagates a check to children and parents and updates pointers for get_next_affected_by_check().

set_column_to_propagate_checks() can be made to control which of those two methods a Tree uses when the user presses a checkbox.

I can add a new method called set_indeterminate() to let the user set indeterminate status.

I would rename get_next_affected_by_check() to get_next_propagated_check(). It would still function the same the way it does now.

**Comment by groud** [comment]
> Right now set_checked() can do one of two things based on whether the user has called set_column_to_propagate_checks().

That could work.

> set_column_to_propagate_checks() can be made to control which of those two methods a Tree uses when the user presses a checkbox.

I don't think it's needed. My idea was to let the user connect to the "item_edited" signal and propagate the checking if needed. That being said I though we would have an "item_checked" signal, maybe such signal would be needed then?

> I can add a new method called set_indeterminate() to let the user set indeterminate status.

Makes sense.

> I would rename get_next_affected_by_check() to get_next_propagated_check(). It would still function the same the way it does now.

I still fail to understand what this function does and why it is needed. From my understanding, all you seem to need is being able to recursively iterate over the children of an item. But I don't think we need a dedicated function for that.

**Comment by Phischermen** [comment]
> > I would rename get_next_affected_by_check() to get_next_propagated_check(). It would still function the same the way it does now.
> 
> I still fail to understand what this function does and why it is needed. From my understanding, all you seem to need is being able to recursively iterate over the children of an item. But I don't think we need a dedicated function for that.

I admit that method is non-essential since there are methods to iterate through children and methods to iterate through parents already, but it is a super helpful method because it enables the user to iterate through the appropriate items in a single while loop in the item_edited callback function.

Right now, when set_checked is called and the user has set a column to propagate checks, each child is (un)checked iteratively and recursively. In each iteration, the previous item updates a pointer named "next_checked" to point to the current item. This would look like:

original_item -> child1 -> child2 -> last_child

After all children have been taken care of, then the parents are iterated through and (un)checked based on how many of their children are (un)checked. Their pointers are updated the same way; previous to current. A null pointer is used to mark the end of the list. That looks like:

original_item -> child1 -> child2 -> last_child -> parent_of_original_item -> grand_parents -> null.

get_next_propagated_check() is meant to let the user traverse that linked list in a single while loop instead of iterating through children recursively in a while loop and then parents in a while loop using existing methods like get_first_child() and get_parent().

**Comment by groud** [comment]
> I admit that method is non-essential since there are methods to iterate through children and methods to iterate through parents already, but it is a super helpful method because it enables the user to iterate through the appropriate items in a single while loop in the item_edited callback function.

Yeah, to be honest I think this is too specific and quite hard to understand what it does. Unless users express need for something like that I would not add it. In general I think there are not a lot of situations where you would need to iterate over the modified entries. Most of the time users will most likely do a pass on the whole tree once it is "validated" (though it could also be done every time something is checked if there's not a lot of elements in the Tree). So for now, I think this function is not worth the trouble.

Also, it relies on an internal pointer which makes it dependent on another function call, which is not something I like that much. This easily create a mess when you modify the tree while iterating over it. It would create inconsistent states, and most importantly likely crashes (if you remove the TreeItem pointed by next_checked, you can have a segfault if you make a call to get_next_affected_by_check).

**Comment by KoBeWi** [comment]
I think we all agree that indeterminate checkmarks are good idea. I haven't looked into the propagation code much, but if there is no consensus, maybe you should move it to a separate PR (with this one having only the new checkmarks) and open a proposal? There shouldn't have been so much discussion in the PR comments.

**Comment by Phischermen** [comment]
Sorry, I got carried away. I'm very enthusiastic about this PR and the feedback discussions! I'll make this PR just have the icons, API to set tree items as indeterminate, and documentation.

**Comment by Phischermen** [comment]
Closing in favor of #53276

**Pull request closed without merging**
