### PR TITLE
Fix dangling and awkwardly reassigned `Variant`s [wip]

### LINKED ISSUE #32383: Reference to freed object can return a random different one
**Godot version & OS/device including version:**
3.1.1 Windows 10. 

**Issue description:**
I think this is a simple explanation of an issue I have on my project. I have raised this issue without an example project because it will take some time to reproduce in a simple form and I would like some godot experts to look at what I am describing, and let me know if the issue is already logged and known (and perhaps fixed) before I spend more time working on a reproduction cases

----
Say I have a RobotFactory class and it can instantiate Robots, but it is only allowed to have one active in the world at once.  It saves the instantiated robot in a var. 

var my_robot = RobotScene.instance()

The robot walks around the world for a while an then is destroyed by something so in its own script it calls queue_free() on itself. 

Sometime later in the RobotFactory we call is_instance_valid(my_robot) to see if we should create a new robot. 

In my project I have found that sometimes is_instance_valid(my_robot) returns true after my_robot has been freed, but that it is pointing to some other random object in the scene that has been instantiated. Perhaps sometime after the queue_free, but before is_instance_valid call. 

The only thing I think could be happening is that there is some kind of underlying pooling system and my_robot is pointing to somewhere that is being reused after the robot is freed. 

Please let me know if this is a known issue, is already logged, or if I should do some more work to explain the issue better. 

---

*Bugsquad edit:* Keyword: previously freed instance

### PR DESCRIPTION
**Pull request by RandomShaper**
This is what the main commit does:
> This applies to non ref-counted `Object`s (i.e., any that is not a `Resource`).
> 
> When an object is freed while there are still `Variant`s referring to it, these are nullified and a warning about this is printed.
> 
> This is made possible thanks to a linked list (the 'sentinel chain') of such `Variants`. It's kept collaboratively
> - by `Object`, which contains a pointer to the first `Variant` in the chain
> - and by `Variant`, which contains a pointer to the next one.
> 
> The sentinel list is kept valid at all times by handling operations over `Variant`, such as reassignment and clearing.

The other important change is making `CowData` aware of non-trivially copyable types, much needed for the main part to work right.

Notes:
- I've tested this with pretty script-intensive projects, with no problems and **negligible performance degradation**.
- This will get us rid of crashes due to accessing freed `Object`s in scripts.
- This will fix the bug by which a script variable is reassigned to a new `Object` senselessly.
- This will help catching bugs in script logic, as the warning will let you know about those cases waiting to bite you, that were formerly hidden.

Fixes #32383.

----

**This code is generously donated by IMVU.**

### CODE REVIEW

**Comment by qarmin** [comment]
This is probably correct issue #32383

**Comment by akien-mga** [comment]
This is definitely wanted for 3.2, but it's too late as the release is imminent, so it will have to wait a bit.
Hopefully we can get it merged and tested for 3.2.1, as it will fix a pretty critical issue of 3.1 / 3.2.0.

**Comment by RandomShaper** [comment]
This will need a little bit more work. @punto- has called my attention about its lack of thread safety.

I can fix that, but let's see what the final impact on performance is.

**Comment by RandomShaper** [comment]
While thinking about how to make this thread-safe, a new, much better way of doing this
came to my mind.

Current aproach (A):
- Linked list of `Variant`s pointing to the same `Object`.
- Making if thread-safe would imply locking (maybe spin-locking) the list, i.e. locking
  a mutex in the `Object`.
  
Potential new approach (B):
- Just a reference count in the `Object`: the number of `Variant`s pointing to it.
  Making it thread-safe is trivial: let the counter be atomic.
- This wouldn't need the enhancement done on `CowData` (by which for types not trivially copyable
  it doesn't use `realloc` but allocate-copy-free and adds a destroy step if the type
  is not trivially destructible), but it may be wanted anyway for correctness/realiability.
  
When an `Object` is freed while still are `Variant`s referencing it, only approach A is
able to solve the situation by nullifying them all.

However, a different action may be taken -and, for that, approach B is enough-: preventing
the `Object` from being freed, thanks to its predelete handler. In that case, the `Object`
could be marked as "garbage-collectable" so it frees itself when the reference count reaches
zero.

Will its reference count reach zero for sure? In other words, is it guaranteed that all
`Variants` are destroyed on shutdown? I think so, but if that weren't the case, the `ObjectDB`
would just need to complain about it still existing at cleanup. No big deal, even desirable
as a further reminder that something has been done wrongly.

It could be considered that this approach of retaining the `Object` has implications on `Node`,
-that upon deletion unparents itself and frees its children-. However, there's no such issue because,
either retained or not, it will still get its `NOTIFICATION_PREDELETE`, where it performs such
cleanup and the `Object`'s predelete handler will still have the chance to prevent its deallocation.

In addition, special handling is needed when the `Object` is being deleted through a `Variant`
call to `free`, since in that case the reference count will be 1, being that enough to let it
be deallocated. A possible solution is decrementing the reference count before dispatching
the call.

(How does all this play with C# or VisualScript?)

**Comment by RandomShaper** [comment]
It seems that the approach that is being implemented for 4.0 will be backported to 3.2 so this no longer makes sense.

I'll create a new PR with the `CowData` fix, for 4.0.

**Comment by avencherus** [comment]
@randomshaper Could you link it when it's available?  Will it still solve #32383.

**Comment by RandomShaper** [comment]
The fix for 4.0 is being done by @reduz. I don't know for sure when it will be available, but I can tell you upfront it will indeed solve the issue you mentioned.

**Comment by avencherus** [comment]
Cool, thanks.  I've noticed the issue mostly in my tool scripts.

**Pull request closed without merging**
