### PR TITLE
ScriptTextEditor: fix capitalize offset

### LINKED ISSUE #17445: Script Editor: Capitalize results offset by one character
**Godot version:**
`Godot Engine v3.0.2.stable.official`

**OS/device including version:**
Windows 10

**Issue description:**
The `Edit > Convert Case > Capitalize` option found in the Script editor is offset by one.

Related https://github.com/godotengine/godot/issues/12927

**Steps to reproduce:**

1. Write any pair of words between quotes. Example: `"hello godot"`
2. Highlight all written text.
3. Press `Shift+F2` (or use the menu: `Edit > Convert Case > Capitalize`)
4. Result should be `hello Godot"`

**Minimal reproduction project:**

gif with reproduction steps

### PR DESCRIPTION
**Pull request by ghost**
Fixes #17445 

Editor assumes that `capitalize` wouldn't change the string's length. This is no longer the case after #12932. Also, capitalizing `"hello godot"` won't give you `"Hello Godot"`, but `"hello Godot"` instead.

### CODE REVIEW

**Comment by toqueteos** [comment]
> Also, capitalizing "hello godot" won't give you "Hello Godot", but "hello Godot" instead.

May I ask why? I'd expect `Hello Godot` to be the expected output.

**Comment by Noshyaar** [comment]
`"` is count as part of the word 'hello' as the string is sliced by space character.

**Comment by Zylann** [comment]
Why does capitalize change string length? Aren't characters wide chars?

**Comment by Noshyaar** [comment]
Apparently `capitalize` changes string length since 2.1 or before. All consecutive spaces are replaced with one space, but in 3.0 the string is also trimmed.

```
print("   this is godot 2.1 capitalize   \n   _ready snake_case camelCase PascalCase   ".capitalize())

 This Is Godot 2.1 Capitalize 
 Ready Snake Case Camelcase Pascalcase
```

```
print("   this is godot 3.0 capitalize   \n   _ready snake_case camelCase PascalCase   ".capitalize())

This Is Godot 3. 0 Capitalize 
 Ready Snake Case Camel Case Pascal Case
```

IMO these functionalities are both desired in different situations and one should not replace another. It should be an argument.

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Pull request merged**
