### PR TITLE
Explicitly declare python helper modules in SConstruct to avoid unexpected shadowing

### LINKED ISSUE #56652: Unable to compile master branch, scons ModuleNotFoundError
### Godot version

4.0

### System information

Debian 11

### Issue description

scons report the following error:

scons: Reading SConscript files ...
ModuleNotFoundError: No module named 'editor.template_builders'; 'editor' is not a package:

### Steps to reproduce

clone the master repository and try to compile with:
/usr/bin/env python3 /usr/local/bin/scons --jobs=8 platform=linuxbsd target=release_debug

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by touilleMan**
fix #56652

### CODE REVIEW

**Comment by jmb462** [comment]
Seems to be a lot cleaner than my solution.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs some extra lines around the `def` block to satisfy the `black` formatting

The macOS error is a cache corruption unrelated to this PR, so I'll need to fix the cache before this can pass CI.

**Comment by akien-mga** [comment]
Rebased to fix CI.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
It looks like this breaks the build on my [nightly build system](https://github.com/Calinou/godot-builds-ci):

```
AttributeError: module 'editor' has no attribute 'template_builders':
  File "/builds/Calinou/godot-builds-ci/godot/SConstruct", line 764:
    SConscript("modules/SCsub")
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/builds/Calinou/godot-builds-ci/godot/modules/SCsub", line 46:
    SConscript(name + "/SCsub")  # Built-in.
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/builds/Calinou/godot-builds-ci/godot/modules/gdscript/SCsub", line 25:
    SConscript("editor_templates/SCsub")
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/root/.local/lib/python3.6/site-packages/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/builds/Calinou/godot-builds-ci/godot/modules/gdscript/editor_templates/SCsub", line 5:
    import editor.template_builders as build_template_gd
```

**Comment by touilleMan** [comment]
@Calinou do you have a link for you build logs ? what platform / python version is it running on ?

**Comment by mhilbrunner** [comment]
Looking at https://hugo.pro/projects/godot-builds/ / https://github.com/Calinou/godot-builds-ci

Seems to be `ubuntu:18.04` which is Bionic Beaver, package is here: https://packages.ubuntu.com/bionic/python3
Latest seems to be Python `3.6.5-3`

Runner specs are here:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

**Comment by Calinou** [comment]
> Runner specs are here:
docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

I'm using GitLab CI, not GitHub Actions.

**Comment by touilleMan** [comment]
The issue comes from the fact the `editor` module is an empty shim given we only declare `editor.template_builders`. This is fine with Python>3.7, but Python 3.6 doesn't play along

With Python 3.6.8
```python
>>> import editor
>>> dir(editor)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']   # No template_builders field, this is normal
>>> import editor.template_builders   # import works
>>> editor.template_builders  # but access doesn't given it is resolved as `getattr(editor, 'template_builders')`
*** AttributeError: module 'editor' has no attribute 'template_builders'
>>> import editor.template_builders as tb  # this also doesn't work :(
*** AttributeError: module 'editor' has no attribute 'template_builders'
```

With Python3.7.9
```python
>>> import editor
>>> dir(editor)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> import editor.template_builders
>>> editor.template_builders  # Same getattr as in Python 3.6
*** AttributeError: module 'editor' has no attribute 'template_builders'
>>> import editor.template_builders as tb  # This work given it is a lookup into `sys.modules`
>>> dir(tb)
['StringIO', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'make_templates', 'os', 'parse_template', 'subprocess_main']
```

A solution is to use the "from ... import ..." statement instead of the import:
so `import editor.template_builders as build_template_gd` becomes `from editor import template_builders as build_template_gd`
(this way Python find the module by doing a lookup with the `editor.template_builders` instead of potentially first finding `editor` module, then accessing it `template_builders` attribute)

However given nothing prevent from using the wrong import style, we could end up with this bug reappearing in the future :/

The even simpler solution is to consider Python 3.6 is end of life since 23/12/2021. So we could update to `EnsurePythonVersion(3.7)` at the start of `SConstruct` and be done with it.
But given this is end of life occurred fairly recently (and as @Calinou showed, ubuntu 18.04 - which is really common on CI - is still using it) I'm not sure it is the correct solution 😄 

Finally the more violent solution is to further improve the `_helper_module` method to create the parent modules (and update them so that they contain children modules as attributes) along the way. I've implemented this as PR #56766  ;-)

**Pull request merged**
