### PR TITLE
Add speed override to AnimatedSprite

### PR DESCRIPTION
**Pull request by Vega-KH**
Adds the option to override the animation speed of AnimatedSprites. The override speed can be attached to curves and smoothly ramp up and down the animation speed.

Per my own feature suggestion #18007

### CODE REVIEW

**Comment by robfram** [comment]
You should read the details in https://travis-ci.org/godotengine/godot/jobs/363605896

The errors are code style related. As your code doesn't follow the clang style imposed in Godot source code. For example, placement of curly braces, extra new lines, etc. You could run clang locally before pushing or let git do it auto before commit using the hooks in godot/misc/hooks dir of the source code.

BTW, related to #18044 (for the sake of discussion).

**Comment by Vega-KH** [comment]
Thank you @robfram . I was confused by the message at first because it said:

\-   
\+

And I was confused... it wants me to delete my blank line and add a blank line!? But then I realized my blank line had a hidden indent added by the code editor. Doh. Anyway, I think your PR and mine should be compatible, but one of us may need to rebase.

**Comment by akien-mga** [comment]
The commits would need to be squashed together to consider this PR for merging, see [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase). Note that there's also a counter proposal by @groud for the same feature, we'll compare both to see which makes the most sense.

**Comment by Vega-KH** [comment]
@akien-mga sorry about that.  I have now squashed the PRs. I left a note on the other PR by @groud on reasons why I prefer this method, but his method works too so I am happy with whatever you guys decide.

**Comment by Vega-KH** [comment]
Killing this as I did something horribly wrong with GIT and got it completely screwed up.  If someone decides they like the way I did the override, I will push a new commit.

**Pull request closed without merging**
