### PR TITLE
Add tests for `Projection`

### PR DESCRIPTION
**Pull request by Flarkk**
This PR adds nearly full test coverage for struct `Projection`.

The following few methods are not covered yet and left to further PR(s) :
- `set_for_hmd()` and `create_perspective_hmd()`
- `set_perspective()` with eye input
- `set_orthogonal()` with aspect input and `create_orthogonal_aspect()`
- `set_frustum()` with aspect input and `create_frustum_aspect()`
- `get_pixels_per_meter()`
- `get_lod_multiplier()`
- and a few operators (==, !=, `Transform3D`)

### CODE REVIEW

**Comment by Flarkk** [comment]
Sorry for these repeated force push. The workflow stopped on a weird error with asan. I ended up removing the `DOCTEST_STRINGIFY_VARIANT` I had added for `Vector4`, `Vector4i` and `Projection` in `test_macros.h` as I suspect it was related to the stringification  logic. Hope it's ok now.

**Comment by Flarkk** [comment]
Last force push I hope... Everything builds and runs fine in my environment

**Comment by Flarkk** [comment]
Allright, ready for review !

**Comment by Flarkk** [comment]
Rebased on top of #95303

**Review by Calinou — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
