### PR TITLE
Add `Vector2.from_angle()` method

### PR DESCRIPTION
**Pull request by Xrayez**
3.x version of #48237 by @KoBeWi. I will update this PR once #48237 is finally merged.

### CODE REVIEW

**Comment by akien-mga** [comment]
Did you test it? :)

There's no support for static methods in GDScript in 3.x.

**Comment by Xrayez** [comment]
> There's no support for static methods in GDScript in 3.x.

You can test `Color.from_hsv()`:
```gdscript
extends Node2D

func _ready():
	var c = Color.from_hsv(1, 0.5, 1)
	print(c)
	var v = Vector2.from_angle(PI)
	print(v)
```

`Vector2.from_angle` is implemented similarly here. 🙂

**Comment by kleonc** [comment]
> You can test `Color.from_hsv()`

`Color::from_hsv` isn't static though (both in [`3.x`](https://github.com/godotengine/godot/blob/94235fad033d168dc4a17b719afac612683586ea/core/color.h#L197) and [`master`](https://github.com/godotengine/godot/blob/1c2766e24073314a7dff711095610e737784bd46/core/math/color.h#L192)) and is `const`.

Not sure exactly how this works but TIL these (for example) also seem to "work" in GDScript (at least in `3.3`):
```
print(Vector2.ceil())               # (0, 0)
print(Vector2.floor())              # (0, 0)
print(Vector2.round())              # (0, 0)
print(Vector2.sign())               # (1, 1)
print(Vector2.posmod(1))            # (0, 0)
print(Transform2D.inverse())        # ((1, 0), (0, 1), (-0, -0))
print(Transform2D.affine_inverse()) # ((1, -0), (-0, 1), (0, 0))
```
Quite interesting. :smile:

**Comment by Xrayez** [comment]
I guess this mostly boils down to run-time behavior, since constructs like `const` on C++ level have syntactic meaning. Not necessarily the same case with `static`, but I think it's just about memory access at the end of the day, so this would work regardless. Probably it just allocates memory to hold a "static" internal instance of `Color` and binds directly to function address of that instance.

My stance on this: if that's already a feature in 3.x, then it should be safe to merge, especially if (when?) the same feature is going to be merged in 4.x (with "proper" way of doing this, but likely `master` branch just has a refactored version of the same feature).

**Pull request closed without merging**
