### PR TITLE
Extract shader and material storage

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Extract our global variable, shader and material storage classes

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
I'm still hunting a bug when exiting where it looks like it frees up materials before meshes are destroyed with the result its accessing materials while cleaning up that are no longer applicable.

It could also be that they are not removed from the dirty list correct (seems to go past them)

But I've been working on this all day and my brain is fried.

Put it ready for review because this is 99% complete and this one is HUGE

**Comment by BastiaanOlij** [comment]
Note, CI is happy now that I've added an extra NULL condition check however on exit of the application I'm still getting the errors mentioned in the previous post around Materials being accessed for which the RID is no longer valid.

I'm stuck on knowing why.

**Comment by BastiaanOlij** [comment]
Oh FFS... Just found out the material errors on close also happen in master and were probably introduced by something else...
Needs to be fixed but I don't think they are introduced by this PR so I call this ready for full review.

**Review by clayjohn — APPROVED** [review]
I moved shaders and materials into their own files in GLES3 in my local copy of the engine. I am dreading the rebase :(

Great work though!

**Comment by reduz** [comment]
By looking at it, I now feel materials, shaders and global variables could be a single file (Renderer::Material) since more or less they are all part of the same thing and interact at the very low level.

**Comment by reduz** [comment]
Following this logic it may make more sense to have:

Renderer::MeshStorage (containing mesh, multimesh and skeleton)
Renderer::LightStorage (containing all light information)
Renderer::GIStorage (containing reflection probe, voxelGI and lightmap) // <- Either this or we make GI a whole object merging storage and logic
Renderer::Particles (containing both storage and particle system logic)
Renderer::VolumetricFog (containing fog storage, fog volume and fog logic, including volumetric fog?)
Renderer::RenderTarget (containing render target data)

I would not be so afraid to mix up logic and storage for many things that make sense.

The problem is mostly that we have some functions like:
`virtual RS::InstanceType get_base_type(RID p_rid) const` 
or
`virtual void base_update_dependency(RID p_base, DependencyTracker *p_instance) = 0;` 

That kind of relies on everything being in the same place.

**Comment by Calinou** [comment]
> Renderer::GIStorage (containing reflection probe, voxelGI and lightmap) // <- Either this or we make GI a whole object merging storage and logic, or separate out ReflectionProbe.

Shouldn't reflection probes go together with decals, since both are clustered elements?

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Looks good to me! Pending @clayjohn to re-review I guess.

**Review by clayjohn — APPROVED** [review]
Looks good to me

**Comment by Shnazzy** [comment]
When I try to compile after this commit, (Windows, MSVC version 14.1, arch amd64, bits=64), I'm getting an error saying the `Shader` class is ambiguous:

[CompilationError.txt](https://github.com/godotengine/godot/files/8414928/CompilationError.txt)

I imagine other compilers have better methods of disambiguating, but I was able to fix it on my end [by making the namespace reference explicit](https://github.com/Shnazzy/godot/commit/6a6007611374756193bdddcebe242f6d8aee01ea)

Is this correct?

**Pull request merged**
