### PR TITLE
Add compat rename for OpenSimplexNoise

### LINKED ISSUE #59953: Materials with OpenSimplexNoise won't load in alpha 6
### Godot version

4.0 alpha 6

### System information

Linux Manjaro, Vulkan, Intel Kaby Lake

### Issue description

Title.
This is understandable because OpenSimplexNoise was removed in favor of FastNoiseLite, but without some sort of an automatic conversion - or tips on how to fix the .tres file - this is a problem.

### Steps to reproduce

Sample file attached.

### Minimal reproduction project

[road_shadermat.tres.zip](https://github.com/godotengine/godot/files/8429304/road_shadermat.tres.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #59953.

### CODE REVIEW

**Comment by clayjohn** [comment]
Does this still work when there are different parameters between the old class and the new class?

**Comment by akien-mga** [comment]
It will work only for the parameters which are the same, and should discard the ones which differ. So it's not a 1:1 port but at least it should replace the resource with the closest match (which can then be further configured to get back to similar results).

But I haven't actually tested this yet, I should probably :P

**Comment by akien-mga** [comment]
Before:

image

After:

image

So most settings differ aside from `seed`, but at least it's still noise and not a message about the scene being corrupted.

**Review by clayjohn — APPROVED** [review]
Looks good to me. The new noise is a compatibility breaking change. So we can't expect it to look the exact same.

**Comment by Zireael07** [comment]
Yep, I don't expect to have the same output, I just want my materials not to break completely ;)

**Pull request merged**
