### PR TITLE
Clear SelfList when destroying GDScriptLanguage

### LINKED ISSUE #78136: Game crashes on exit if closed while awaiting a signal and there are unfreed objects
### Godot version

4.0.3

### System information

Ubuntu 22.04.2 LTS

### Issue description

If awaiting a signal, and there are unfreed objects in memory, and the user closes the game, then the executable crashes with this error:
```
ERROR: Condition "_first != nullptr" is true.
   at: ~List (./core/templates/self_list.h:106)
```
In a build (rather than running from the editor), this is followed by this error:
```
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object/object.cpp:1982)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/io/resource.cpp:489)
```

This happens whether the object in question is an `Object` subclass that has not been freed or a `RefCounted`. 

What I expect to happen is that the application should close without throwing these errors. I expect any such memory to be automatically freed on application exit, or at least for the application to close gracefully, without throwing an error. The application's giving an error code produces a bad user experience that I cannot avoid if using signals and non-Node scripts.

I have seen the same behavior on Windows 10, although I am writing this report from Linux.

Note that these errors show up in the terminal that launched Godot (the engine or the built game), not within Godot's "Output" window.

### Steps to reproduce

Please see the attached minimal reproduction project. Run `main.tscn` and close the running application: it will produce an error. Run the application again and click the button, whose `pressed` signal is being awaited in the script. Now close the application, and no error will be produced.

The error is easiest to see if godot itself was started from the command-line: this error is reported in the terminal that launched Godot, not within Godot's built-in terminal.

Whether the allocated object is an unfreed `Object` or a `RefCounted` does not seem to matter. The example project uses `item.gd` as a minimal `RefCounted`. Once can change it to an `Object` and stick an `_item.free()` at the end of the `_ready()` function, and the same behavior will occur.

To make your own reproduction:
- Make a custom `Object` or `RefCounted` script
- In the main scene, e.g. in `_ready`, create an instance, then await a signal
- Run the application and close it before that signal is received.

Here is a sample. Given a script like this:
```
class_name Item
extends RefCounted
```
Then the following scene will generate the problem if closed before clicking a button in it:
```
extends Control

func _ready():
	var _item := Item.new()
	await $Button.pressed
```

### Minimal reproduction project

[repro_await.zip](https://github.com/godotengine/godot/files/11722690/repro_await.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #78136
Not sure if correct, maybe the list elements need some cleanup too.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Ok moved the code to `finish()`.
`script_list` seems to get cleaned up properly, not sure about `function_list` (but it doesn't look like it needs to delete anything?).

**Comment by RedworkDE** [comment]
Given that the original report is on 4.0.3, which doesn't have the DEV_ASSERT and it crashes anyways, I don't think this really fixes things and likely just makes it go back to crashing occasionally with an access violation.

**Comment by AThousandShips** [comment]
Since the list entries are removed on delete, and the list isn't empty, it does sound like an access violation trying to access the script and function instances after the language has been deleted

**Comment by KoBeWi** [comment]
The DEV_ASSERT is in destructor and is clearly expecting the list to be empty, so I'm just fulfilling the requirement 🤷‍♂️ If the crash happens without DEV_ASSERT, it just explains why it was there. And my changes fix it (unless you can find a case where it still crashes?).

**Comment by AThousandShips** [comment]
I'd add some null checks to those places just to be sure if we aren't digging deeper into what causes the error in the first place, as those access checks could be more spurious theoretically

**Comment by KoBeWi** [comment]
What places exactly? >_>

**Comment by AThousandShips** [comment]
Here:
https://github.com/godotengine/godot/blob/ae896bbd85d0c9f1883c81f138045c3753ccef01/modules/gdscript/gdscript.cpp#L1457

And here:
https://github.com/godotengine/godot/blob/ae896bbd85d0c9f1883c81f138045c3753ccef01/modules/gdscript/gdscript_function.cpp#L165

**Comment by AThousandShips** [comment]
Confirmed that it's not a crash on 4.0.x so should be safe to just clear the lists

**Review by adamscott — APPROVED** [review]
@KoBeWi, you're cleared for take off.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
