### PR TITLE
Fix running tests in template builds

### PR DESCRIPTION
**Pull request by AThousandShips**

### CODE REVIEW

**Comment by AThousandShips** [comment]
I did some testing and it doesn't really make sense to have tests enabled with export, will look at disabling it completely for this as well

**Comment by akien-mga** [comment]
> I did some testing and it doesn't really make sense to have tests enabled with export, will look at disabling it completely for this as well

What are the issues? In theory it seems useful to me that we can run unit tests on non-tools builds (especially the release template), to validate that the API behaves as intended even in release builds.

It's not something we would enable for official export templates of course, but ideally we would run such tests on CI. If some tests depend on editor-only functionality, they should be `#ifdef TOOLS_ENABLED` away.

**Comment by AThousandShips** [comment]
Indeed, will look deeper into the specific issues, but there are some tests that simply won't work without even being in the correct directory, but will leave this for later digging and not add it here

Note that we couldn't use it in CI unless we do an export completely as the template binary can't be run then

**Comment by AThousandShips** [comment]
That's strange it popped up the dialog for me first, you're right it works fine in that case, then no worries here, then I'll just leave it as such for now :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Well actually in second thought, since `dev_mode` is for engine developers, I do think we should have tests enabled by default in dev builds even for templates. We just need to fix the bugs with running tests, by disabling the tests which can't work.

**Comment by AThousandShips** [comment]
I'll take a look :)

**Comment by AThousandShips** [comment]
Identified the first issue, the file `modules/gdscript/tests/scripts/analyzer/errors/cyclic_ref_override.gd` crashes on release builds, unsure how to fix that, will see if I can get better output details

**Comment by AThousandShips** [comment]
For now I'm disabling some of the offending GDScript tests, to be fixed later, and fixing some other tests and improving them, will push soon

**Comment by AThousandShips** [comment]
There, some temporary fixes in there but this makes it possible to generally run tests, with some improvements

There are still some test cases that fail on `disable_3d` builds but will look into those specifically in a separate PR as they're a bit trickier

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
