### PR TITLE
Make Tree control create items with the passed parent. Fixes #12118

### LINKED ISSUE #12118: Tree control does not always create items with the passed root
Linux, Debian 8
Godot 3, build bf5a927 (Oct 14, from calinou's nightly builds)

Tree.create_item(parent) doesn't always create the item with the passed parent. It does not behave as described in the docs (which it should, the behavior described in the docs makes sense).

**Steps to reproduce:**
```
var root = tree.create_item() # becomes root, as expected

var section1 = tree.create_item(root) # become child of root, as expected

var item1 = tree.create_item(section1) # becomes actual root and the var root becomes child of item1, not expected
var item2 = tree.create_item(section1) # becomes actual root and item1 becomes child of item2, not expected

var section2 = tree.create_item(root) # becomes child of the var root, as expected, but var root is no longer the actual root of the tree

var item3 = tree.create_item(section2) # becomes actual root and item2 becomes child of item3, not expected

var no_parent = tree.create_item() # becomes actual root and item3 becomes child of no_parent, not expected
```

**Link to minimal example project:**
[github](https://github.com/RodeoMcCabe/godot-tree-bug)
[tree-test.gz](https://github.com/godotengine/godot/files/1385165/tree-test.gz)
[tree-test.zip](https://github.com/godotengine/godot/files/1385166/tree-test.zip)

### PR DESCRIPTION
**Pull request by ghost**
Tree::create_item(p_parent) now creates the item with p_parent as the item's parent. The item is added as the last child. If no parent is passed, the item is added as the last child of the tree root. If there is no root yet, the item becomes the root.

NOTE: In my test project I originally had chained method calls like so: `tree.create_item(section1).set_text("Section 1")` However, this caused subsequent items that were created with `section1` passed as the parent, to be parented to root instead. I don't know what the problem is there. If you don't chain method calls there is no problem.

Fixes #12118.

### CODE REVIEW

**Comment by JuanDidNothingWrong4** [comment]
This is not a high priority at all. Downvoted, and voting to close.

**Comment by RodeoMcCabe** [comment]
After some more testing it turns out that `Tree::create_item()` works as expected without this fix so long as no method call is chained to it. This PR improves behavior in that the root now always remains the same, but items are still always created as a child of root (when chaining method calls to `create_item()`

Yes, not a priority, but we're in beta now and bugfixes are supposed to be the focus. Obviously it doesn't have to be merged but I don't see a reason to close it. In any case, the behavior described above should be fixed entirely before merging.

**Comment by JuanDidNothingWrong4** [comment]
@RodeoMcCabe I'm being facetious sir. Read this:

(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)



Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(

**Comment by JuanDidNothingWrong4** [comment]
@RodeoMcCabe I love your PR actually (just mocking the lead developer) how he treats people who give feedback like human garbage. It's pathetic.

**Comment by RodeoMcCabe** [comment]
Well, after reading through that comment thread, I'm going to carefully say that I have no opinion on the matter.

I will say this however: this PR is not a high priority, you were absolutely right about that facetious or not. But I needed it fixed so I could get on with my project, so I fixed it myself. Everyone's giving their free time to contribute to Godot, so I can't ask them to fix it for me, just because I need it. My point here is that if you see a problem with Godot, try thinking about what you can do yourself to help fix it. You might be going at it alone for now if other devs don't think it's a high priority, but nonetheless everyone will be grateful for the effort you would be putting into it.

**Comment by JuanDidNothingWrong4** [comment]
@RodeoMcCabe Well, just saying. You are contributing to a project where the lead developer treats people like human fucking garbage (after giving honest feedback), hence that reddit thread. And what that user experienced when Juan pm'd him through facebook. He did not deserve that at all, all of his issues were valid criticisms.

Just be weary in the future, wouldn't spend that much time on this repo if I were you

**Comment by RodeoMcCabe** [comment]
Well, reduz is not my favorite guy either, in fact I made a comment about that on Reddit today. **But**, that doesn't mean I can ignore the great work he's done and the huge contributions he's made to FOSS in the gaming industry. I'll make PRs if I need to, and I will see it as contributing to FOSS.

Anyway, I've given my thoughts on the matter and this is all terribly off-topic, so I'll leave it at that.

**Comment by JuanDidNothingWrong4** [comment]
@RodeoMcCabe 

No doubt, the work he's done is awesome. He's smart as fuck

But the way he treats people who give feedback is uncalled for, and his passive aggressiveness and how akien defends his behavior is sickening.

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/issues/14660#issuecomment-352185335

**Comment by RodeoMcCabe** [comment]
Not working on this anymore at the moment. In the future I might come back to it. @RayKoopa might want to look at this, but feel free to close the PR if you like.

**Comment by RayKoopa** [comment]
Do we have a definitive decision on how it should behave now? Reduz didn't sound too sure D:

I'd just implement it throwing an error if root already exists, together with the PR adding an optional insertion index parameter I was working on anyway.

**Comment by RodeoMcCabe** [comment]
>an optional insertion index parameter I was working on anyway.

That would be wicked.

I still don't know what would be the best behavior for the parent parameter. I leaning back towards just sticking with what the docs say now. I don't know. Either way you decide to do it, just make sure the docs reflect the current behavior or confusion will ensue. If the docs are right, people can learn to work with whatever behavior easily enough.

**Comment by HummusSamurai** [comment]
Superseded by https://github.com/godotengine/godot/pull/14801 ?

**Comment by RayKoopa** [comment]
yes

**Comment by RodeoMcCabe** [comment]
@RayKoopa thanks for your PR. Closing this one.

**Pull request closed without merging**
