### PR TITLE
 Improve the error message about MAX_EXTENSIONS. Add two comments about where extensions are being registered

### PR DESCRIPTION
**Pull request by lucbf**
Some error checks therefore were removed.

See: https://github.com/godotengine/godot/issues/36405

### CODE REVIEW

**Comment by groud** [comment]
I don't see why removing those checks would be a good idea. Those initialization functions are run once, so there is absolutely no significant loss of performance due to those checks.

**Comment by M4gma** [comment]
My reasoning was just to improve readability because the cap is already very high

**Comment by groud** [comment]
> My reasoning was just to improve readability because the cap is already very high

I don't think you improve readability by removing checks and replacing them by big comments.
It can be improved by adding comments, not by removing code.

But in any case, rendering code is always hard, it's kind of normal it's hard to read. :/

**Comment by M4gma** [comment]
I see myself so shortsighted now xD. I'll add them back

**Comment by akien-mga** [comment]
I don't really see the point of doing this, because errors typically serve two purposes:
- Tell the user (who typically doesn't compile Godot) that something is wrong so they understand why it does work.
- Tell contributors (who compile Godot) where an error was raised so that they can inspect the code and see what to do.

Adding some info in the error message that tells *contributors* what they should change for a hypothetical issue is not very useful. They can check the code and understand that they have to bump `MAX_EXTENSIONS` if it's too low for some reason.

**Pull request closed without merging**
