### PR TITLE
Document `Image.save_exr()` only being available in editor builds

### PR DESCRIPTION
**Pull request by Calinou**
See https://godotforums.org/discussion/comment/51257/#Comment_51257.

### CODE REVIEW

**Comment by fire** [comment]
Not this documentation change, but what was the reasoning behind save_exr() being removed from templates?

**Comment by Calinou** [comment]
> Not this documentation change, but what was the reasoning behind save_exr() being removed from templates?

See https://github.com/godotengine/godot/pull/42947.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.

**Pull request merged**
