### PR TITLE
Split monolithic physics class files

### PR DESCRIPTION
**Pull request by smix8**
Splits monolithic physics class files.

This PR moves things around a lot, but what this PR primarly does is to split the monolithic physics class files into subfiles. Something that was imo overdue for a very long time. E.g. physics body was harboring all the rigid, static, character, and what-not bodies. This made the file already lag in editors and resulted in all kind of functionality that only needed a single physics base class to include near everything physics has to offer.

All the main physics classes are now in their own file in a `scene/2d_or_3d/physics` subfolder.
Same with bone joints, each bone joint now has its own file in a joints subfolder.
Main means the class is primarily or exclusively used with or for physics.
E.g. raycast, shape cast, physics bones, collision shapes, objects and bodies.

A few random includes that were discovered as no longer needed are also removed.
E.g. the NavigationObstacle no longer uses physics so no need to include physics classes.

### CODE REVIEW

**Comment by fire** [comment]
It is very hard to review these changes. Especially when the github web interface freezes on my computer. The typical strategy is make sure the tests pass and let the testing go to the wider community.

**Review by fire — APPROVED** [review]
Aha. I switched from Firefox to Safari and it loaded. See previous comment. Assuming that there is no functionality change.

**Comment by smix8** [comment]
Added the physics and joints folders to the scu script and fixed the gltf includes.

**Review by akien-mga — APPROVED** [review]
Looks good to me, and compiles fine. A quick test shows the GDQuest TPS demo with 3D physics seems to work.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
