### PR TITLE
Change DirAccess::list_dir_begin return value(true=success, false=fail)

### PR DESCRIPTION
**Pull request by sanikoyes**

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Quick question, why not use `OK` and `ERR` constants?

**Comment by AlexHolly** [comment]
I always ignored the returned value of "list_dir_begin()" because I opened the directory one line before.
I just checked and it really returns false on a successful "list_dir_begin()"

**Comment by reduz** [comment]
it's a super old engine class, predating godot actualy.. for some reason I
forgot to change that function to use Error
and now it' s probably too late

**Comment by reduz** [comment]
might do it for 3.0, where some compatibility is expected to be lost

**Comment by punto-** [comment]
was this only happening on linux, and on windows it's the opposite? It
seems to be the unix way, where it returns true on error

**Comment by akien-mga** [comment]
I added a mention to fixing the return type of `list_dir_begin` for 3.0 in #5696, so this PR can be closed.

**Pull request closed without merging**
