### PR TITLE
Removed a useless computation

### PR DESCRIPTION
**Pull request by hbina**
This was probably a leftover from some old code.

### CODE REVIEW

**Comment by lawnjelly** [comment]
Presumably the `imgs.sort()` isn't needed either?

**Comment by pycbouh** [comment]
There was a print, but then this happened:
https://github.com/godotengine/godot/commit/22419082d9bedbc9dc060ea5784bb0871f8710a3#diff-e502152dcdc1583c9b88373dfdc2b32f

**Comment by aaronfranke** [comment]
@hbina Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch.

**Comment by akien-mga** [comment]
Superseded by #46505 which implements the proper fix (i.e. fixing the regression pointed out by @pycbouh).

**Pull request closed without merging**
