### PR TITLE
Fix skeletons when generating multiple Godot scenes from one GLTF

### LINKED ISSUE #80832: Error when generating multiple Godot scenes from one GLTFState
### Godot version

Latest master 4.2.dev 5444afae63f37cb4b890c781e5679a3b7ee5a392

### System information

macOS 13.4.1

### Issue description

The GLTF code has the file parsing and node generation steps split up. This should allow generating multiple Godot scenes from the same imported GLTF file. However, this does not currently work as expected. Example GDScript code:

```gdscript
func _ready() -> void:
	var gltf_document := GLTFDocument.new()
	var gltf_state := GLTFState.new()
	gltf_document.append_from_file("res://mannequiny-0.3.0.glb", gltf_state)
	var scene_node: Node = gltf_document.generate_scene(gltf_state)
	add_child(scene_node)
	scene_node = gltf_document.generate_scene(gltf_state)
	add_child(scene_node)
```

Basically, the Godot node generation should all be happening in the orange circle, but the current code has a problem where some of it is happening in the red circle:

Godot GLTF import

### Steps to reproduce

Open the minimal reproduction project and hit the play button. The project contains the above code.

With the current master: Godot crashes.

With only #80272: The second scene is missing a skeleton, and errors are spammed in the console.

With both #80272 and #80831: Both scenes have a skeleton (the correct behavior).

### Minimal reproduction project

[GLTFGenerateMultipleScenes.zip](https://github.com/godotengine/godot/files/12389153/GLTFGenerateMultipleScenes.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #80832.

### CODE REVIEW

**Review by Scoppio — APPROVED** [review]
Tested the issue presented and it does fix it, also I appreciate the use of very specific error messages instead of a generic message, helps alot to understand what is happening and what could be the problem.

**Review by fire — APPROVED** [review]
Community testing suggests that it is working and Aaron has done his testing so it looks good, but I am not able to fully test this myself.

**Comment by aaronfranke** [comment]
I did re-test this tonight using the reproduction project in #80832 and it still works, and also I tested on The Mirror.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
