### PR TITLE
Page allocation in MessageQueue

### LINKED ISSUE #35653: Change MessageQueue to a page allocator to prevent overflow
**Godot version:**
Master (3cfb67e0f)

**OS/device including version:**
Any

**Issue description:**
As discussed a few times on IRC, and exemplified by many bug reports, our current fixed size for the Message Queue is problematic.

It currently defaults to `1024` (see `memory/limits/message_queue/max_size_kb`), and many users need to increase it to prevent overflow when handling a large amount of messages (which can happen easily in the editor when using e.g. large TileSets #29238 or Skeletons #35652).

As discussed with @reduz, Message Queue should be changed to use a page allocator so that its size can grow as needed, preventing overflows.

Situations which can cause a Message Queue overflow like #29238 or #35652 should however be fixed in the Inspector itself, as even increasing the MQ will just make things functional again, but it will still freeze a long time while populating all those controls.

### PR DESCRIPTION
**Pull request by staddy**
Fixes #35653

### CODE REVIEW

**Comment by reduz** [comment]
I have pending to work on this on the 4.x branch in the next days, but I want to use a bit of a different approach. I suggest we wait some days and then discuss the PR again

**Comment by aaronfranke** [comment]
@staddy Is this still desired? If so, this needs to be rebased on the latest master branch.

The core internals of the engine have changed a lot for 4.0, so it's possible this PR isn't relevant anymore.

**Comment by reduz** [comment]
In the end, I think it should be easier to just resize the buffer, given no pointers are kept to it either way.

**Comment by akien-mga** [comment]
Superseded by #62303, thanks for the contribution nevertheless!

**Pull request closed without merging**
