### PR TITLE
[HTML5] Add Stadia controller to database

### PR DESCRIPTION
**Pull request by Powerbyte7**
Add web support for the Stadia controller.

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request!

The game controller database is maintained in [another repository](https://github.com/gabomdq/SDL_GameControllerDB). Please open a pull request there, as changes here would be lost upon synchronizing from upstream :slightly_smiling_face:

**Comment by Calinou** [comment]
Is there a reason the mapping should be added here instead of [upstream](https://github.com/gabomdq/SDL_GameControllerDB)?

**Comment by Powerbyte7** [comment]
> Is there a reason the mapping should be added here instead of [upstream](https://github.com/gabomdq/SDL_GameControllerDB)?

This file is exclusive to Godot, SDL doesn't have the HTML5 controller mappings.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
