### PR TITLE
2D and 3D Skeleton modification api changes in preparation for 4.0 beta.

### PR DESCRIPTION
**Pull request by lyuma**
* Remove SkeletonModificationStack3D and related resources, to be added back later when apis have been tested.
* Remove local bone override and several deprecated functions from the Skeleton3D api.
* Fix array property glitch in SkeletonModificationStack2D.
* Mark SkeletonModificationStack2D and related APIs as experimental.
* Mark SkeletonIK3D as deprecated.
* PhysicalBone2D no longer relies on SkeletonModification2DPhysicalBones to update bone positions.

Most of this change is removing stuff. I decided to keep the 2D modifications as resources because their design is simpler given Bone2D being a node, and the 2D modifications do not rely on deprecated APIs, and furthermore all of the modifications (other than PhysicalBone) are already working fine. We can still change this in the future, but it's not urgent.

As for why I included `PhysicalBone2D` in this PR, it's because I wanted to make sure all modifications in TwistedTwigleg's project were working, but PhysicalBone was broken in master, so I changed a lot of code in PhysicalBones2D to make my test project work, and in doing so removed the need for the `SkeletonModification2DPhysicalBones` resource.

### CODE REVIEW

**Comment by josefkaragoli** [comment]
Why remove this?

**Comment by TokageItLab** [comment]
Release Beta means a feature freeze, so as much as possible, break compatibility changes should be avoided after that.

The ModificationStack has a lot of APIs implemented in the Skeleton that should not be there, since it was implemented without going through a formal review by GSOC in the first place. That must be removed and reimplement outside of Skeleton.

Also, the current ModificationStack is significantly broken and needs to be refactored and reimplemented as a Node. Unfortunately, this refactoring is taking a long time, sorry.

And that refactoring means breaking compatibility with projects that use the ModificationStackResource and projects that use the ModificationStackNode, so we need to remove the ModificationStackResource once and make sure that it does not create incompatible projects between Beta and RC.

**Comment by fire** [comment]
For clarify some review comments were made in rocketchat and not reflected here. https://chat.godotengine.org/channel/animation

image

**Comment by akien-mga** [comment]
See #65799 for a simpler option for beta 1.

**Comment by lyuma** [comment]
Superseded by #65801

**Pull request closed without merging**
