### PR TITLE
Fallback to CLOCK_MONOTONIC when CLOCK_MONOTONIC_RAW is not stable

### LINKED ISSUE #87086: Delta time, `TIME` and physics not working on Essential PH-1 with LineageOS
### Tested versions

- Reproducible on 4.3.dev1 4.2.1.stable, 4.1.3.stable, 4.0.4.stable
- Not tested on 3.x

### System information

Godot v4.2.1.stable - Android 13 (LineageOS 20-20231234-NIGHTLY-mata) on [Essential PH-1](https://www.gsmarena.com/_essential_ph_1-8710.php)

### Issue description

I have a simple `RigidBody2D` which falls in PC but not when I export to Android.

I see this on the debugger tab:

```
W 0:00:00:0999   advance_checked: Final value of `time_accum` is larger than `p_physics_step`. It should always be between 0 and `p_physics_step`. This hints at an engine bug.
  <C++ Source>   main/main_timer_sync.cpp:475 @ advance_checked()
```

### Steps to reproduce

Create a simple scene with a `RigidBody2D`, sprite and collision shape. Test on PC and it falls. Export to Android. There it doesn't fall.

### Minimal reproduction project (MRP)

[physics_test.zip](https://github.com/godotengine/godot/files/13906117/physics_test.zip)

### PR DESCRIPTION
**Pull request by cesarizu**
On my android phone, using `clock_gettime` with `CLOCK_MONOTONIC_RAW` returns seemingly random values for the nanoseconds. This PR makes it fallback to `CLOCK_MONOTONIC` to prevent issues with timing.

This fixes #87086

### CODE REVIEW

**Comment by Faless** [comment]
This seems like a LineageOS bug, and should be reported there, instead of
making clock functions slow on any Linux/Android device.

**Comment by cesarizu** [comment]
Created a related bug report for LineageOS here: https://gitlab.com/LineageOS/issues/android/-/issues/6742

**Comment by cesarizu** [comment]
Created a related bug report for LineageOS here: https://gitlab.com/LineageOS/issues/android/-/issues/6742

**Comment by Faless** [comment]
Closing, as this needs to be fixed by LineageOS.

**Pull request closed without merging**
