### PR TITLE
Update Camera 2D to fix and remove some notifications

### LINKED ISSUE #28492: Camera2d has a one frame delay
**Godot version:**

3.1.1.stable.official

**OS/device including version:**

Windows 10

**Issue description:**

Camera2D with no margin or smoothing, attached to a Sprite with a simple movement script, follows the Sprite, but with a one frame delay on its position. This is most visible during the very start of the motion, and the very end.

**Expected behaviour:**
Camera2D follows the sprite exactly.

**Other notes:**
This looks like it's a result of internal node functionality happening on NOTIFICATION_INTERNAL_PROCESS before gamecode-driven position updates happen on NOTIFICATION_PROCESS.

**Minimal reproduction project:**

[Random.zip](https://github.com/godotengine/godot/files/3125148/Random.zip)
Launch, and use arrow keys to move. Watch at the start and end of movement to see the issue.

### PR DESCRIPTION
**Pull request by ghost**
This simple pull request will fix : #28492
By removing the if statement that stops the camera from updating using `NOTIFICATION_TRANSFORM_CHANGED `.
And removing the `NOTIFICATION_INTERNAL_PROCESS `as it has no use.
As well as `NOTIFICATION_PROCESS`

### CODE REVIEW

**Comment by lawnjelly** [comment]
I did write a little about it here: 
https://github.com/godotengine/godot/issues/28492#issuecomment-735966978

as this is basically just a PR on:
https://github.com/godotengine/godot/issues/28492#issuecomment-732183992

It may be reasonable to do this, but I agree with reduz .. we need to take care in this area. There needs to be a lot more research into why the `if` statement was there in the first place, and what the knock on effects of such a change will be, before merging such a change. Perhaps you have done this, but it needs to be documented here.

It is very possible that by fixing this in this way will introduce other bugs, or have bad effects on performance, or be compatibility breaking with existing games. For instance objects updated before the object in the scene tree will see it one position, and objects updated afterward will see it in another. Order of operations like this can be a minefield.

In addition you would need to discuss this with reduz and convince him, as he probably wrote the code originally.

**Comment by TechnoArtStudio** [comment]
@lawnjelly 

As I stated in #28492  
My debugging shows that the `_update_scroll` after the `if statement`  never get called.
That mean its broken in that state.

>>Also, how expensive is the _update_scroll?

It is expensive, that's why We refused to use `force_update_scroll()`


>>why the if statement was there in the first place

My theory is that reduz  tried to call `_update_scroll` only when the camera changes position.
by masking `NOTIFICATION_TRANSFORM_CHANGED` using that if statement.

my evidence is he checks if  `is_processing_internal` is off.
(we think he should check it for on)

We did a test to see how many times does:
`NOTIFICATION_INTERNAL_PROCESS ` and `NOTIFICATION_TRANSFORM_CHANGED `

is called the same time.

So maybe there is no performance problems.


only reduz can confirm our hypothesis.

**Comment by lawnjelly** [comment]
We should probably revisit this PR, as it should fix the remaining problems with camera snapping. We just need to make sure it doesn't cause any regressions.

**Comment by lawnjelly** [comment]
Actually I woke up this morning realising why it is done this way, and have a better way of solving this, same basic idea though. Will prepare a PR.

**Comment by TechnoArtStudio** [comment]
Thanks to @lawnjelly  #46697

We could close this PR.

**Some notes** 
I want to side note the major difference between this PR and #46697

-This PR deletes some notification cases and letting the `_update_scroll` called every time, while his PR keeps the notification cases only changes the condition that allow `_update_scroll` to be called.

Hopefully his change will not result in a bug.

As @reduz quoted in his PR:

> Yes, processing is enabled wrongly, so this is not a complete fix, it may break during process.


Thank you.

**Comment by lawnjelly** [comment]
Yup there's I've got another PR in to improve the process logic: #46717, but I'll do this in consultation with the others.

It would still run ok as is I think, as the fixed version will call `_update_scroll` in more cases, not less, but the process logic could do with clearing up. Reduz was keen to make sure the `_update_scroll` didn't run in the transform notification when smoothing was off, I wasn't 100% sure on this but his explanation sounded reasonable.

I'm also a fan of removing the other notification cases if not necessary, on the other hand with the fixed logic, they may not get called at all anyway if `internal_process` and `internal_physics_process` are switched off. Yes on reflection I think this is solved already with the logic PR.

Also, I haven't timed or profiled but I'm not completely sure that `_update_scroll` is actually that expensive in the end.

**Pull request closed without merging**
