### PR TITLE
Fix Godot getting swamped by debug events

### PR DESCRIPTION
**Pull request by ghost**
If you run a script that produces a lot of error events, both the player and the Godot main app will currently hang (tested in Godot 3 beta 2 and master), since Godot's main app will never leave the process notification where it consumes ever new incoming events.

This PR sets a processing time limit for incoming debug events; as this processing happens as `NOTIFICATION_PROCESS`, this will only delay processing of some events to a later time, not cancel them.

Fixes Godot becoming totally unresponsive and hanging in case of the runner going havoc.

### CODE REVIEW

**Comment by akien-mga** [comment]
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by akien-mga** [comment]
Moving back to 3.0 as it works around a freeze, though as mentioned in #15150 I'm not sure it's the proper fix.

**Comment by reduz** [comment]
@Geequlim would you like to give a check to this? for stdout I remember having written a limit of messages per second (or frame), I guess errors should have a similar mechanism.

**Comment by poke1024** [comment]
@Geequlim @reduz Also see https://github.com/godotengine/godot/pull/15297

**Comment by Geequlim** [comment]
@reduz I think #15297 is reasonable to solve this problem.

**Comment by akien-mga** [comment]
I've merged #15297 which is a good security. I'd suggest to close this PR as I think it hides the issue, and instead investigate what causes message overflows that will now be properly reported after #15297.

**Comment by poke1024** [comment]
I'm not sure. I think there should be an upper time limit Godot stays in that loop here. We could print out error messages in these cases to guard against this hiding a bug. Still, if it hits that loop, it's a hard hang, you won't be able to save and you will have to kill the Godot process.

**Comment by akien-mga** [comment]
Ok, fine with me to keep the guards and output an error in such case.

**Comment by akien-mga** [comment]
@reduz says there's no need to output an error, though the value is a bit too magic.. but we'll see, let's merge.

**Pull request merged**
