### PR TITLE
Fix issues with BlendSpace2D BLEND_MODE_DISCRETE_CARRY

### LINKED ISSUE #41028: Blendspace2D BLEND_MODE_DISCRETE_CARRY freezes or doesn't carry
**Godot version:**
3.2.2

**OS/device including version:**
Windows 10

**Issue description:**
Making pixel art game with AnimationPlayer animating frames in Sprite (using discrete mode - frame by frame). Running has a blend for aiming diagonally and forward (like NES contra). When changing blends they restart animation position using BLEND_MODE_DISCRETE_CARRY but in some cases can freeze whole node (all running animations but then all animations are frozen in the same position).
Happens in the editor too.

**Steps to reproduce:**
Have a couple of animations (frame by frame in Sprite) that have common visual cues. Set the blend mode to carry.
While Blendspace2D is playing, change blend_position.

**Minimal reproduction project:**
[AnimationTreeBug.zip](https://github.com/godotengine/godot/files/5024445/AnimationTreeBug.zip)
Move with arrows and Enter used for a secondary blend.
Notice that when flipping in MOVE state with UP and DOWN dot that goes around is staying in the same place.

### PR DESCRIPTION
**Pull request by rune-scape**
bug fix for #41028. introduced in #20135.
I left my notes on what the problems were in #41028

*Bugsquad edit:* Fixes #41028.

### CODE REVIEW

**Comment by fire** [comment]
I asked @TokageItLab to review.

**Review by fire — APPROVED** [review]
@TokageItLab 's review said this also affects 3d animations.

He says the pr fixes the stated problem.

**Comment by TokageItLab** [comment]
https://user-images.githubusercontent.com/61938263/116825552-cc0bc900-abca-11eb-86f3-580e43ce7b19.mov

[blendspace2d_blendmode_test_with_3d.zip](https://github.com/godotengine/godot/files/6412136/blendspace2d_blendmode_test_with_3d.zip)

This video blends three of the same animations, but it is wrong for such a transition to occur in `BLEND_MODE_DISCRETE_CARRY`. This PR fixes that problem, so I am favor of it.

**Comment by akien-mga** [comment]
Could you amend the commit message to be [more explicit](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) about what it does? Referencing a GitHub issue is useful, but not sufficient information to know what the commit does when not on GitHub.

**Comment by bowling-allie** [comment]
done

**Review by fire — APPROVED** [review]
Didn't want this to be in limbo.

Already approved earlier.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
I prefer not to cherry-pick for `3.3` at this stage.

**Comment by beuted** [comment]
Hey I'm not sure to understand if this fix is included in which version of Godot this fix has been included in the end could you help ?

**Pull request merged**
