### PR TITLE
Rename Godot-specific resource extensions

### LINKED ISSUE #9199: Rename "sugar" resource extensions to avoid conflicts with established thirdparty extensions
Prompted by the fact that OBJ's `.mtl` material extension is the same as Godot's `.mtl` (and we might want to add support for OBJ's `.mtl` in the future), we propose to rename those "sugar" resource extensions (they're synonyms for the actual `.res` binary format) to avoid conflicts.

The idea is to use full names instead of 3-letter short names, so "mtl" becomes "material" and so on.

Proposal (might have missed some extensions, if so comment):

| Old | New |
| --- | --- |
| anm | animation |
| asogg | oggstream(?) |
| atex | atlastexture | 
| cbm | cubemap |
| cvtex | curvetexture |
| fnt | font |
| gt | meshlib |
| ltex | largetexture |
| mmsh | multimesh |
| msh | mesh |
| mtl | material |
| pbm | pbm (standard) |
| res | res (flagship extension) |
| room | room (no change needed) |
| sbx | stylebox |
| scn | scn (flagship extension) |
| sgp | shadergraph |
| shd | shader |
| shp | shape |
| smp | sample |
| tex | texture |
| thm | theme |
| wrd | world |
| xl | translation |

### PR DESCRIPTION
**Pull request by vnen**
Let's break compatibility a little more for a good cause.

Closes #9199.

### CODE REVIEW

**Comment by reduz** [comment]
seems good, but just remove "shd", I will add a specific resourceloader/saver that handles this resource as text for the .shader extension

**Comment by vnen** [comment]
I rebased to leave .shd unchanged then. It can be changed when the custom loader/saver is added then.

**Comment by vnen** [comment]
It seems I missed some changes in the import savers.

**Comment by vnen** [comment]
Should be all done now.

**Pull request merged**
