### PR TITLE
Fix inspector update after changing anchor from buttons

### LINKED ISSUE #27013: Anchors are not updated in the inspector when their value is changed via Layout
**Godot version:**
3.1

**OS/device including version:**
x86_64 GNU/Linux (Ubuntu)
NVidia GTX 660
NVIDIA Driver Version: 390.116
Server Vendor Version: 1.19.6

**Issue description:**
Anchors are not updated in the inspector when their value is changed via "Layout"

**Steps to reproduce:**
bug

### PR DESCRIPTION
**Pull request by qarmin**
Fix #27013

### CODE REVIEW

**Comment by groud** [comment]
I'm pretty sure that's not how to fix it, generally nodes tell themselves to the inspector that one of their property changed (with change_notify)

**Comment by qarmin** [comment]
Sorry, miss clicked.

**Comment by qarmin** [comment]
Hmm... I don't really understand what _change_notify do and I'm not really sure if direct call notification function is right.

**Comment by groud** [comment]
Line 1391 of control.cpp, we have:
`_change_notify("anchor");`
The bug is here, as _change_notify is used to notify the inspector so that a property has changed.
This line should likely be replaced by something like:
```
_change_notify("anchor_left");
_change_notify("anchor_right");
_change_notify("anchor_top");
_change_notify("anchor_bottom");
```

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Pull request merged**
