### PR TITLE
Allow for getting/setting "dotted" properties of objects

### LINKED ISSUE #8257: Tween function for single axis position/translation
Godot 3 got better property access, making possible to move a node with something as simple as `translation.z += some_float`.

But Tween still does not have access to a single axis, it can only interpolate full translations or positions limiting the use of interpolation to full translation; if Tween is able to interpolate a single axis, it will allow more complex animations.

I don't mind general vector item interpolation but only single axis position/translation for nodes, because these are the most used and may have their own complexity if involves transform.

ps: this could be a new method, like `interpolate_axis`, no need to alter the regular property access.

### PR DESCRIPTION
**Pull request by bojidar-bg**
**Do not merge without proper review!** There might be a faster way to do it, I'm not completely sure yet.

Additionally includes a commit that makes it easier to use `Tween::{interpolate,targeting}_property`, by auto-`get()`-ing the initial value if `null` is given.

I'm open to discussions about better solutions, either here or on the original issue (#8257).

[GIF Recording of work](https://cloud.githubusercontent.com/assets/5276727/26603684/6afa37a4-4590-11e7-82ef-57cc1b9ab4f9.gif) (its dimensions are a bit too large, so I won't inline it here)
Code used for recording:
`main.gd`
```gdscript
extends Node2D

func _ready():
	var tween = get_node("Tween")
	tween.interpolate_property(get_node("KinematicBody2D"), "position:x", null, 500, 2, Tween.TRANS_BOUNCE, Tween.EASE_OUT, 0)
	# Without first commit:
	#tween.interpolate_property(get_node("KinematicBody2D"), "position:x", get_node("KinematicBody2D").position.x, 500, 2, Tween.TRANS_BOUNCE, Tween.EASE_OUT, 0)
	tween.start()
```
`kinematic_body_2d.gd`
```gdscript
extends KinematicBody2D

func _fixed_process(delta): # Note: 3.0, thus doesn't need set_fixed_process(true)
	move(Vector2(-50, 50) * delta)
```

As you can see, the Tween applies to the X axis only, while the Y axis is moved by the KinematicBody2D.

Closes #8257. Revamp of #9003.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Here are some stats:
```
# Set property (position)

(... = z) x 1000000
	0.647000 seconds (0.000647 msec/rep) -- fastest

set(.., z) x 1000000
	1.417000 seconds (0.001417 msec/rep) -- 2x slower, probably because of stringname conversion

set_indexed(.., z) x 1000000
	1.716000 seconds (0.001716 msec/rep) -- 3x slower, because of having to search for a "."

# Set subproperty (position.x)

p=get(..); p.x=z.x; set(.., p) x 1000000
	2.310000 seconds (0.002310 msec/rep) -- fastest

set(.., Vector2(z.x, get(..).y)) x 1000000
	2.397000 seconds (0.002397 msec/rep) -- slightly slower, since it has to create a new Vector2

set_indexed(...x, z.x) x 1000000
	3.014000 seconds (0.003014 msec/rep) -- 1.5x slower, since it has to split the string
```

<details> 
<summary>Code used to generate it: (click to expand)</summary>

```gdscript
func _ready():
	var thing = $Node2D
	var repetitions = 1000000.0
	
	print("(... = z) x %f" % [repetitions])
	var direct_time = OS.get_ticks_msec()
	for i in repetitions:
		
		thing.position = Vector2(randf() * 500, 100)
		
	direct_time = OS.get_ticks_msec() - direct_time
	print("\t%f seconds (%f msec/rep)" % [direct_time / 1000.0, direct_time / repetitions])
	
	print("set(.., z) x %f" % [repetitions])
	var set_time = OS.get_ticks_msec()
	for i in repetitions:
		
		thing.set("position", Vector2(randf() * 500, 100))
		
	set_time = OS.get_ticks_msec() - set_time
	print("\t%f seconds (%f msec/rep)" % [set_time / 1000.0, set_time / repetitions])
	
	
	print("set_indexed(.., z) x %f" % [repetitions])
	var set_indexed_time = OS.get_ticks_msec()
	for i in repetitions:
		
		thing.set_indexed("position", Vector2(randf() * 500, 100))
		
	set_indexed_time = OS.get_ticks_msec() - set_indexed_time
	print("\t%f seconds (%f msec/rep)" % [set_indexed_time / 1000.0, set_indexed_time / repetitions])
	
	
	print("p=get(..); p.x=z.x; set(.., p) x %f" % [repetitions])
	var setget_time = OS.get_ticks_msec()
	for i in repetitions:
		
		var p = thing.get("position")
		p.x = randf() * 500
		thing.set("position", p)
		
	setget_time = OS.get_ticks_msec() - setget_time
	print("\t%f seconds (%f msec/rep)" % [setget_time / 1000.0, setget_time / repetitions])
	
	
	print("set(.., (z.x, get(..).y)) x %f" % [repetitions])
	var setget_opt_time = OS.get_ticks_msec()
	for i in repetitions:
		
		thing.set("position", Vector2(randf() * 500, thing.get("position").x))
		
	setget_opt_time = OS.get_ticks_msec() - setget_opt_time
	print("\t%f seconds (%f msec/rep)" % [setget_opt_time / 1000.0, setget_opt_time / repetitions])
	
	print("set_indexed(...x, z.x) x %f" % [repetitions])
	var set_indexed_x_time = OS.get_ticks_msec()
	for i in repetitions:
		
		thing.set_indexed("position.x", randf() * 500)
		
	set_indexed_x_time = OS.get_ticks_msec() - set_indexed_x_time
	print("\t%f seconds (%f msec/rep)" % [set_indexed_x_time / 1000.0, set_indexed_x_time / repetitions])
```

</details>

**Comment by bojidar-bg** [comment]
I'm just worried that it would negatively affect AnimationPlayer performance, which might be problematic...

One way of optimising it further would be to store the splitted String in the StringName, so I don't have to split it every set or get, but I'm still not certain about the usefulness of that.

**Comment by reduz** [comment]
Actually I changed my mind, maybe what we could do is modify NodePath to
include sub-properties and use this.
This way, for set_indexed/get_indexed you just pass a node path (And the
path part is ignored). It should be more efficient than parsing a string
and have virtually no cost if only one property is there.

**Comment by bojidar-bg** [comment]
New stats:
```
# Set property
(... = z) x 1000000
        0.592000 seconds (0.000592 msec/rep)
set(.., z) x 1000000
        1.384000 seconds (0.001384 msec/rep)
set_indexed(@.., z) x 1000000
        1.127000 seconds (0.001127 msec/rep)
# Set subproperty
p=get(..); p.x=z.x; set(.., p) x 1000000
        2.246000 seconds (0.002246 msec/rep)
set(.., (z.x, get(..).y)) x 1000000
        2.326000 seconds (0.002326 msec/rep)
set_indexed(@...x, z.x) x 1000000 # Using nodepath
        1.855000 seconds (0.001855 msec/rep)
set_indexed(...x, z.x) x 1000000 # Using string
        4.530000 seconds (0.004530 msec/rep)
```
Code is nearly the same as before, just using nodepaths instead of strings for set_indexed.

**Comment by bojidar-bg** [comment]
Note that it now uses `:` for indexing instead of `.`.

**Comment by eon-s** [comment]
Would be great to have this for beta, any chances to get it merged soon?

**Comment by akien-mga** [comment]
It needs a rebase, and a review by @reduz.

**Comment by bojidar-bg** [comment]
Update, fixed a big bug when passing only one name to `set_indexed`. I have to debug why AnimationPlayer doesn't detect the type of the property properly and sets it in discrete mode..

**Comment by bojidar-bg** [comment]
Ok, that bug was fixed as well... Anything else I should test?

**Comment by akien-mga** [comment]
I'd say let's Test in Production™.

**Comment by mrcdk** [comment]
This PR may have broken something https://github.com/godotengine/godot/issues/13162

**Comment by IVHM** [comment]
Hey i don't know if this is the right thread for it. But can we get this addition of syntax sugar for interpolating Vector Variants to the documentation somewhere.

**Pull request merged**
