### PR TITLE
ResourceLoader: Add last resort life-time insurance for tokens

### PR DESCRIPTION
**Pull request by RandomShaper**
This was intended to come in #94169, but when reorganizing the commits it got lost.

It makes sure that even if all the load requesters are no longer referencing a token, it's still alive until the corresponding load task completes so the task itself isn't removed until not even the resource loader itself is done with it. It's kinda an edge case.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Cherry-pick for 4.3 included in #96606.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by RandomShaper** [comment]
Rebased!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
