### PR TITLE
Use namespaces instead of underscore prefix for core bind classes

### PR DESCRIPTION
**Pull request by neikeq**
I propose this as a replacement for the underscore thing.
This PR doesn't remove the existing extra code that is needed to support classes with underscores (#26922 lists most of them).

The namespace names are just placeholders. I don't know what's our naming convention for namespaces.
There is a lot of `::ClassDB::bind_method` lines in core_bind.cpp, which could be avoided if we move `core_bind::ClassDB` to its own namespace so it doesn't bother the other classes. **Edit:** Moved to its own namespace.

### CODE REVIEW

**Comment by fire** [comment]
Are there any problems from the c-api end? Aka gdnative?

**Comment by neikeq** [comment]
@fire I don't think there is any, but I didn't check. Most if not all the code that works around these underscores is just to strip it (or add it in case of a lookup).

**Comment by reduz** [comment]
I am surprised, never expected anything like this to work, if it really does feel free to go ahead and merge.

**Comment by neikeq** [comment]
It may be safer to leave this for 4.0. I don't think it breaks anything, but I don't know what some GDNative language bindings out there are doing, so just to be safe...

**Comment by neikeq** [comment]
The only annoyance I found is that we can't use `VARIANT_ENUM_CAST` because the template specializations it declares must be in the same namespace where the template was originally declared (which is why I moved all the `VARIANT_ENUM_CAST` to the bottom outside the namespace in _core\_bind.h_).

**Comment by aaronfranke** [comment]
Does this change anything on the front end?

**Comment by ptrojahn** [comment]
I created #30153 which only removes the checks.

**Comment by vnen** [comment]
Any news in this regard? I'm now rewriting GDScript code and it would be nice to not have to deal with those pesky underscores.

**Comment by neikeq** [comment]
I'll be revisiting this soon, but right now I'm focusing on other tasks.

**Comment by Xrayez** [comment]
Inspired by this PR, I've already done something similar while developing a custom module. But stumbled upon another bug while regenerating documentation and then generating the mono glue, see Xrayez/godot-geomtools#3.

**Comment by neikeq** [comment]
@Xrayez The issue is with your `PolyDecompType` enum. Enums in namespaces needs [the changes](https://github.com/godotengine/godot/pull/26990/commits/5965d818bf3a23f983dc8abdb9061ed0520d56ab#diff-ab4a4dbc7e347c30974e169e8d55e703) I made to type info in this PR.

**Comment by Xrayez** [comment]
Oh ok, so it would be nice for these changes to be cherry-picked to 3.2, else I'd have to make similar changes and/or revert to how it's now.

**Comment by Xrayez** [comment]
Just saying that I have some other module with having enums in namespaces which is an issue in and of itself (which is worth treating via separate PR perhaps which can be cherry-picked), for instance see: https://github.com/Xrayez/godot-anl/commit/642b470e8c1e1943e5c8016be2fc28213d5702b8#diff-142e17f094b421b5777b79be43c94633R336-R339. I've just had to duplicate enums eventually.

**Comment by aaronfranke** [comment]
@neikeq This was last rebased over a year ago, what's the status of this?

**Comment by neikeq** [comment]
It should be easy to re-do it for the master branch, but I haven't had time for that yet. Maybe next month.

**Comment by neikeq** [comment]
I've added this to my TODO list for July.

**Comment by akien-mga** [comment]
Superseded by #51627.

**Pull request closed without merging**
