### PR TITLE
Add check for zero length motion at beginning of each sweep test loop in SpaceBullet::test_body_motion

### PR DESCRIPTION
**Pull request by madmiraal**
Addresses: https://github.com/godotengine/godot/pull/34210#issuecomment-563256399

### CODE REVIEW

**Comment by AndreaCatania** [comment]
For code clarity I would like to revert this: https://github.com/godotengine/godot/pull/34225/files#diff-a61d01bcaef4874b6713c0b00e6d4571R948

and add the motion check here: https://github.com/godotengine/godot/pull/34225/files#diff-a61d01bcaef4874b6713c0b00e6d4571R963

```cpp
for (int shIndex = 0; shIndex < shape_count && !motion.fuzzyZero(); ++shIndex) {
```

**Comment by madmiraal** [comment]
@AndreaCatania I've updated the commit as suggested.

**Comment by akien-mga** [comment]
Ping @AndreaCatania

**Comment by AndreaCatania** [comment]
Awesome thanks!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
