### PR TITLE
Categorize the class reference into folders

### PR DESCRIPTION
**Pull request by aaronfranke**
~~This PR categorizes VisualShader docs into their own subfolder. This is the first step towards solving https://github.com/godotengine/godot-proposals/issues/4543. I decided it would be better to leave the bikeshedding of how to set up specific categories to a future PR. This PR focuses on the code changes to allow loading documentation from subfolders, and creates a category for VisualShader classes, which are the most noisy when trying to browse through the docs since there's nearly 100 of them.~~

This PR categorizes the class reference into subfolders. This is part of solving https://github.com/godotengine/godot-proposals/issues/4543. It categorizes everything in the `doc/classes` folder. We can bikeshed the categories here.

The first commit is the actual code changes, and the second commit is purely running doctool.

Preview: https://github.com/aaronfranke/godot/tree/doc-folders-visual-shader/doc/classes

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm not so fond of the idea, and I don't really see the point.

It breaks encapsulation because now `DocTools` has to make exceptions for specific node types, and this won't be accessible to thirdparty modules/extensions.

I get the proposal to add categories in the class reference but this should be done at the class level by defining metadata (which we first need to agree on), which can be consumed by `DocTools` appropriately. This PR doesn't solve anything.

**Comment by aaronfranke** [comment]
@akien-mga Originally I had `_get_class_category` as a public method in ClassDB so it can be consumed elsewhere, but it was suggested to move this logic into `DocTools` because that's where it used.

> thirdparty modules/extensions

With the current version of this PR, subfolders are not used in modules.

> This PR doesn't solve anything.

It's a first step towards categorizing this very long list: https://docs.godotengine.org/en/stable/classes/index.html

**Comment by akien-mga** [comment]
> It was discussed in a meeting a few weeks ago: https://github.com/godotengine/godot-proposals/issues/4543#issuecomment-1164639354

Yes, that's about creating categories, not subfolders. Categories are things both the editor and `makerst.py` should be able to consume to make something useful out of it.

But also, we need to define a list of categories before implementing them. I'm not in favor of merging a change that just moves VisualShader docs to a subfolder, that's inconsistent and not useful to solve proposal 4543.

**Comment by aaronfranke** [comment]
@akien-mga Here is a branch where the entire class reference is categorized into subfolders, if you want to see my attempt at fully implementing this: https://github.com/aaronfranke/godot/tree/doc-folders

I can undo the splitting up of these changes into smaller PRs, so that we have one PR that solves 4543. And I can move the categorization logic back into ClassDB so that it can be consumed elsewhere such as by the editor.

**Comment by aaronfranke** [comment]
Bikeshedded in a Godot PR meeting. It was discussed that reduz is interested in a more comprehensive category system which wouldn't be implemeneted until Godot 5.0, but is not interested in how this PR works. Reduz also says that he wouldn't bother with folders in case we want classes to have multiple categories. If we do have folders, the suggestion was to have it completely based on inheritance, like all Node-derived classes are grouped together.

**Pull request closed without merging**
