### PR TITLE
Multiple improvements to converter 3 to 4.

### PR DESCRIPTION
**Pull request by FeralBytes**
Catch:
Thread.is_active() to is_alive().
Signal "idle_frame" to "process_frame"
Settings for Window size width/height to viewport_width/height. OS.real_window_size(), get_screen_size(), get_window_size() to DisplayServer equivalents.
OS.get_system_time_secs() to Time.get_time_dict_from_system()['seconds'].

I currently removed the fix for: String.plus_file() to path_join() because the Linux mono build says the function does not exist.
I removed get_network peer fix because it too does not match a direct function call since it is actually a method call which returns an object to call a second method in order to fix the Godot 3 sequence.  get_network_peer() -> get_multiplayer().get_multiplayer_peer()

I also think it would be easy to fix:

- Engine.editor_hint to [Engine.is_editor_hint()](https://docs.godotengine.org/en/latest/tutorials/plugins/running_code_in_the_editor.html#doc-running-code-in-the-editor)
- MainLoop.NOTIFICATION_WM_QUIT_REQUEST to NOTIFICATION_WM_CLOSE_REQUEST
- MainLoop.NOTIFICATION_ to NOTIFICATION_

Although I think it would be easy to implement the above I also think I would break your code trying to do so.
Everything else that I mentioned [here](https://github.com/godotengine/godot-proposals/issues/387#issuecomment-1251909261) will be much more difficult.

### CODE REVIEW

**Comment by FeralBytes** [comment]
```Missing GDScript function in pair (get_network_peer - ===> get_multiplayer().get_multiplayer_peer <===)```
This failure is valid, but not sure how to handle that change, any suggestions or just remove it for now?
```Missing GDScript function in pair (plus_file - ===> path_join <===)```
However is not valid. I am using path_join() right now in a beta4 project.

Of note I followed the directions that the Static Checks produces and attempted to do a git commit --amend. That does not work. So how would you like to proceed to fix my git history? Sorry I am not a git master. I know just enough to be dangerous.

**Comment by Calinou** [comment]
> Of note I followed the directions that the Static Checks produces and attempted to do a git commit --amend. That does not work. 

Since you have more than 1 commit already, you need to [perform a rebase](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase) instead of amending your latest commit.

**Comment by FeralBytes** [comment]
Thanks @Calinou. I believe that should fix the git history.

**Comment by Calinou** [comment]
There's a further list of conversions that could be performed here: https://github.com/godotengine/godot-docs/pull/6393#issuecomment-1320901678

**Comment by FeralBytes** [comment]
This PR: https://github.com/godotengine/godot/pull/69712  will result in my PR needing a change too.

**Comment by YuriSizov** [comment]
Needs to be rebased, but also will have to wait for the time after 4.0 (can probably be merged in 4.0.x, definitely in 4.1, if approved).

**Comment by FeralBytes** [comment]
It is stale now and has conflicts. Closing.

**Pull request closed without merging**
