### PR TITLE
Fix windows issue with multiple file patterns in the file dialog

### LINKED ISSUE #81781: Windows file dialog doesn't support multiple file patterns in a single file filter
### Godot version

v4.2.dev.custom_build [ba54c3455]

### System information

Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 with Max-Q Design (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

The `FileDialogue` class allows for multiple file types to be specified for a single file filter. Example: `"Supported images (*.png,  *.jpg, *.jpeg"`. This makes it convenient for the user to be able to find the file they're looking for. However, when using `DisplayServer.file_dialog_show()` on Windows, using this syntax does not yield the expected results. Due to how the strings are parsed, the string that produces the filter above for FileDialogue (`"*.png,*.jpg,*.jpeg;Supported Images"`) causes the separate file extensions to be merged together, preventing the use of multiple extensions as filters.

### Steps to reproduce

1. Create a file dialogue using `DisplayServer.file_dialog_show()`
2. Set the filters array to include a filter set with multiple file patterns, such as `"*.png,*.jpg,*.jpeg;Supported Images"`

### Minimal reproduction project

[windows_file_dialogue_test.zip](https://github.com/godotengine/godot/files/12641981/windows_file_dialogue_test.zip)

### PR DESCRIPTION
**Pull request by JerryLi-lab**
Try to fix this issue. https://github.com/godotengine/godot/pull/81781

* *Bugsquad edit, fixes: https://github.com/godotengine/godot/pull/81781*

### CODE REVIEW

**Comment by AThousandShips** [comment]
For reviewers, see:
* https://github.com/godotengine/godot/pull/81218
* https://github.com/godotengine/godot/pull/81782

**Comment by AThousandShips** [comment]
Please use `git pull --rebase` to update your branch in the future, if keeps your history clean, see [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch).

**Comment by AThousandShips** [comment]
Please follow the above instructions, do not use this method but the linked method

**Comment by JerryLi-lab** [comment]
> @JerryLi-lab if you need help to update your branch in the instructed way please say so

Thank you. I will try it.

**Comment by AThousandShips** [comment]
You have also included a different fix unrelated to this, you need to put it on a separate branch, this is why it is better to use a dedicated branch for a PR and not `master`

**Comment by JerryLi-lab** [comment]
> You have also included a different fix unrelated to this, you need to put it on a separate branch, this is why it is better to use a dedicated branch for a PR and not `master`

I got it. I want to fix another issue. Should I clone a new brunch?

**Comment by JerryLi-lab** [comment]
> Yes, using `git branch`

I have submitted something, please tell me how to delete it

**Comment by AThousandShips** [comment]
Though it might be easier if you close this PR, restore your branch using `git reset --hard upstream/master` and recreate your changes manually, on a new branch

**Comment by AThousandShips** [comment]
You've added yourself as the author of unrelated commits

**Comment by AThousandShips** [comment]
Did you follow the specific instructions? Using `git rebase -i`?

I'd say it'd be easier to start fresh

**Comment by AThousandShips** [comment]
I'd suggest using `git reset --hard upstream/master` and adding your fix manually, as it's so short

**Comment by JerryLi-lab** [comment]
> Did you follow the specific instructions? Using `git rebase -i`?
> 
> I'd say it'd be easier to start fresh

Yes. Could I delete this fork to remove them. and adding my fix manually

**Comment by AThousandShips** [comment]
No not your fork, just follow the instruction with `git reset --hard upstream/master`

**Comment by AThousandShips** [comment]
Do you have a remote registered? With `git remote add upstream https://github.com/godotengine/godot.git`

**Comment by JerryLi-lab** [comment]
image
Thank you. It works. Please tell me what should I do next?

**Comment by AThousandShips** [comment]
Add your changes back, make a single commit, and use `git push --force`

**Comment by JerryLi-lab** [comment]
> Add your changes back, make a single commit, and use `git push --force`

Thank you for your patient teaching. Should I use a new branch to modify another issue? Delete this branch after merging?

**Comment by AThousandShips** [comment]
Yes, make sure your other branch doesn't include this one though, base it off `upstream/master`

**Comment by JerryLi-lab** [comment]
> Yes, make sure your other branch doesn't include this one though, base it off `upstream/master`
> 
> Once merged, or not, reset this branch the same way again

I now want to submit the code for another issue. Can I use a new branch? Will it affect here?

**Comment by AThousandShips** [comment]
Create a new branch it won't affect this

**Pull request closed without merging**
