### PR TITLE
Debug PR to test full reimportation on Android Editor

### PR DESCRIPTION
**Pull request by Hilderin**
This draft PR only includes debug prints to track down the issue #94416.

I'm not able to reproduce the problem on my Android device, so if someone can use the artefact from this PR, test the editor on Android with the MRP from https://github.com/godotengine/godot/issues/94416#issuecomment-2247454559 and paste here the output logs, it would be greatly appreciated.

EDIT: Even if it does not pass every build, the Android Editor artefact was generated: https://github.com/godotengine/godot/actions/runs/10087688942/artifacts/1737806253

### CODE REVIEW

**Comment by Saul2022** [comment]
`Godot Engine v4.3.rc.gh-94717 (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started on port 6006 ---
--- GDScript language server started on port 6005 ---
Selected screen scale:  1.79999995231628
get_modified_time (jandroid) /data/data/org.godotengine.editor.v4.debug/files/config/godot/editor_settings-4.3.tres
_get_modified_time /data/data/org.godotengine.editor.v4.debug/files/config/godot/editor_settings-4.3.tres = 1721906620619
get_modified_time /data/data/org.godotengine.editor.v4.debug/files/config/godot/editor_settings-4.3.tres = 1721906620619
get_modified_time (jandroid) /storage/emulated/0/Download/testreimportbug/testreimportbug/project.godot
_get_modified_time /storage/emulated/0/Download/testreimportbug/testreimportbug/project.godot = 1721906621159
get_modified_time /storage/emulated/0/Download/testreimportbug/testreimportbug/project.godot = 1721906621159
_scan_filesystem
_scan_filesystem reading cache file...
_scan_filesystem reading cache file... done
_scan_filesystem - _process_file_system - cache size 3
get_modified_time (Unix) res:// = 1721906515
get_modified_time res:// = 1721906515
get_modified_time (Unix) res://icon.svg = 1721811674
get_modified_time res://icon.svg = 1721811674
get_modified_time (Unix) res://icon.svg.import = 1721811674
get_modified_time res://icon.svg.import = 1721811674
_process_file_system - needs reimport res://icon.svg : 1721811674 1721811674
  Formatting error in string "  fc: %s": not all arguments converted during string formatting.

get_modified_time (Unix) res://node_3d.tscn = 1721811674
get_modified_time res://node_3d.tscn = 1721811674
get_modified_time (Unix) res://Sword.glb = 1721811674
get_modified_time res://Sword.glb = 1721811674
get_modified_time (Unix) res://Sword.glb.import = 1721811674
get_modified_time res://Sword.glb.import = 1721811674
_process_file_system - needs reimport res://Sword.glb : 1721811674 1721811674
  Formatting error in string "  fc: %s": not all arguments converted during string formatting.

_scan_filesystem - _process_file_system done
_scan_filesystem - done
get_modified_time (Unix) res://icon.svg.import = 1721811674
get_modified_time res://icon.svg.import = 1721811674
get_modified_time (Unix) res://Sword.glb.import = 1721811674
get_modified_time res://Sword.glb.import = 1721811674
EditorFileSystem: Importing file: res://icon.svg
get_modified_time (Unix) res://icon.svg = 1721811674
get_modified_time res://icon.svg = 1721811674
get_modified_time (Unix) res://icon.svg.import = 1721906621
get_modified_time res://icon.svg.import = 1721906621
EditorFileSystem: Importing file: res://Sword.glb
  editor/editor_data.cpp:885 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:750 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:691 - Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
get_modified_time (Unix) res://.godot/imported/Sword.glb-e2e34e72bfb64487f552687a141d5b06.scn = 1721906622
get_modified_time res://.godot/imported/Sword.glb-e2e34e72bfb64487f552687a141d5b06.scn = 1721906622
update_files res://.godot/imported/Sword.glb-e2e34e72bfb64487f552687a141d5b06.scn ...
update_files res://.godot/imported/Sword.glb-e2e34e72bfb64487f552687a141d5b06.scn ... continue
get_modified_time (Unix) res://Sword.glb = 1721811674
get_modified_time res://Sword.glb = 1721811674
get_modified_time (Unix) res://Sword.glb.import = 1721906622
get_modified_time res://Sword.glb.import = 1721906622
_save_filesystem_cache
_save_filesystem_cache done
_save_filesystem_cache
_save_filesystem_cache done
get_modified_time (Unix) res://Sword.glb = 1721811674
get_modified_time res://Sword.glb = 1721811674
get_modified_time (Unix) res://node_3d.tscn = 1721811674
get_modified_time res://node_3d.tscn = 1721811674
get_modified_time (Unix) res://node_3d.tscn = 1721811674
get_modified_time res://node_3d.tscn = 1721811674
get_modified_time (Unix) res://icon.svg = 1721811674
get_modified_time res://icon.svg = 1721811674
get_modified_time (Unix) res://icon.svg = 1721811674
get_modified_time res://icon.svg = 1721811674
get_modified_time (Unix) res://node_3d.tscn = 1721811674
get_modified_time res://node_3d.tscn = 1721811674
get_modified_time (Unix) res://Sword.glb = 1721811674
get_modified_time res://Sword.glb = 1721811674
get_modified_time (Unix) res://icon.svg = 1721811674
get_modified_time res://icon.svg = 1721811674
get_modified_time (Unix) res://node_3d.tscn = 1721811674
get_modified_time res://node_3d.tscn = 1721811674
get_modified_time (Unix) res://Sword.glb = 1721811674
get_modified_time res://Sword.glb = 1721811674
get_modified_time (Unix) res://icon.svg = 1721811674
get_modified_time res://icon.svg = 1721811674
get_modified_time (Unix) res://node_3d.tscn = 1721811674
get_modified_time res://node_3d.tscn = 1721811674
get_modified_time (Unix) res://Sword.glb = 1721811674
get_modified_time res://Sword.glb = 1721811674
get_modified_time (Unix) res://icon.svg = 1721811674
get_modified_time res://icon.svg = 1721811674
get_modified_time (Unix) res://node_3d.tscn = 1721811674
get_modified_time res://node_3d.tscn = 1721811674
get_modified_time (Unix) res://Sword.glb = 1721811674
get_modified_time res://Sword.glb = 1721811674
`
,

**Comment by akien-mga** [comment]
> Idk how to put logs as you guys do

Use triple backticks:

<pre>
```
code or log goes here
```
</pre>

**Comment by Hilderin** [comment]
I added some more debug prints, can you try again and this time, start the editor, save the log, close the editor, restart it, save the log. If you can share these 2 logs, I think I should have a really good picture of what is going on.

Lastest artefact: https://github.com/godotengine/godot/actions/runs/10101056002/artifacts/1741345142

Thanks

**Comment by Hilderin** [comment]
I'm closing this PR, a fix for the problem has been found and we confirm that there's a problem with the last date time on some Android Device.

**Pull request closed without merging**
