### PR TITLE
Fix for a possible compile error under OS X

### PR DESCRIPTION
**Pull request by marcelofg55**
This fixes this error I'm getting on OS X Yosemite:
```
In file included from main/main.cpp:38:
In file included from core/os/os.h:34:
In file included from core/engine.h:35:
In file included from core/os/main_loop.h:34:
In file included from core/os/input_event.h:36:
In file included from core/resource.h:37:
core/reference.h:261:29: error: member access into incomplete type 'EditorHelpSearch::IncrementalSearch'
                if (reference && reference->unreference()) {
                                          ^
core/reference.h:279:3: note: in instantiation of member function 'Ref<EditorHelpSearch::IncrementalSearch>::unref' requested here
                unref();
                ^
editor/editor_help.h:49:7: note: in instantiation of member function 'Ref<EditorHelpSearch::IncrementalSearch>::~Ref' requested here
class EditorHelpSearch : public ConfirmationDialog {
      ^
editor/editor_help.h:57:8: note: forward declaration of 'EditorHelpSearch::IncrementalSearch'
        class IncrementalSearch;
              ^
8 warnings and 1 error generated.
```

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks much cleaner this way.

**Comment by bruvzg** [comment]
Can confirm error with old clang: master 79f48cd, release-debug tools with Mono.

macOS 10.13.3 (17D47), SDK/Xcode 9.2 (9C40B), Apple clang 900.0.39.2, Mono 5.8.0.108:
 **Build OK**

---

OSX 10.9.5 (13F1911), SDK/Xcode 6.2 (6C131E), Apple clang 600.0.57, Mono 5.8.0.108:
**Same build error**
```
In file included from main/main.cpp:38:
In file included from core/os/os.h:34:
In file included from core/engine.h:35:
In file included from core/os/main_loop.h:34:
In file included from core/os/input_event.h:36:
In file included from core/resource.h:37:
core/reference.h:261:29: error: member access into incomplete type 'EditorHelpSearch::IncrementalSearch'
                if (reference && reference->unreference()) {
                                          ^
core/reference.h:279:3: note: in instantiation of member function 'Ref<EditorHelpSearch::IncrementalSearch>::unref' requested here
                unref();
                ^
./editor/editor_help.h:49:7: note: in instantiation of member function 'Ref<EditorHelpSearch::IncrementalSearch>::~Ref' requested here
class EditorHelpSearch : public ConfirmationDialog {
      ^
./editor/editor_help.h:57:8: note: forward declaration of 'EditorHelpSearch::IncrementalSearch'
        class IncrementalSearch;
              ^
1 error generated.
scons: *** [main/main.osx.opt.tools.64.o] Error 1
scons: building terminated because of errors.
```
**With this PR, build still fails but much later (`__nullable` is not supported by this clang version)**
```
drivers/coreaudio/audio_driver_coreaudio.cpp:40:155: error: expected ')'
  ...inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress *inAddresses, void *__nullable inClientData) {
                                                                                                           ^
drivers/coreaudio/audio_driver_coreaudio.cpp:40:38: note: to match this '('
static OSStatus outputDeviceAddressCB(AudioObjectID inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress *inAd...
                                     ^
drivers/coreaudio/audio_driver_coreaudio.cpp:41:57: error: use of undeclared identifier 'inClientData'
        AudioDriverCoreAudio *driver = (AudioDriverCoreAudio *)inClientData;
                                                               ^
2 errors generated.
scons: *** [drivers/coreaudio/audio_driver_coreaudio.osx.opt.tools.64.o] Error 1
```

---

OSX 10.9.5 (13F1911), SDK/Xcode 6.2 (6C131E), MacPorts clang 5.0.1, Mono 5.8.0.108:
**Build OK**

**Comment by marcelofg55** [comment]
@bruvzg I think we can remove that `__nullable`, does it finishes compiling without that?

**Comment by bruvzg** [comment]
All this `__nullable` annotations are for Obj-C to Swift bridging.

Without `__nullable` Xcode 6.2 clang build finishes without errors, Xcode 9.2 clang works as well. Should be safe to remove it.

**Comment by marcelofg55** [comment]
Perfect, I've just added the `__nullable` removal too on the changes.

**Pull request merged**
