### PR TITLE
Basis RotationQuat should be public.

### LINKED ISSUE #42239: Mono C# class Basis.cs has RotationQuat internal
**Godot version:**

Godot Engine v3.2.3.stable.mono.official

**OS/device including version:**

Windows, GLES3

**Issue description:**

On TPS Demo it's used `orientation.basis.get_rotation_quat()` and on C# the same method `RotationQuat` is defined as `internal`. shouldn't it be public?

**Steps to reproduce:**
https://github.com/godotengine/godot/blob/3.2/modules/mono/glue/GodotSharp/GodotSharp/Core/Basis.cs#L210

**Minimal reproduction project:**

### LINKED ISSUE #42241: Mono C# Quat works differently from GD to C#.
**Godot version:**

Godot Engine v3.2.3.stable.mono.official

**OS/device including version:**

Windows, GLES3

**Issue description:**

I have migrated the TPS Demo to C#, besides the fact that RotationQuat is internal and I opened a issue already for that https://github.com/godotengine/godot/issues/42239 . I tried to copy the method from godot, which is a simple one, but it crashes with the Exception:
```
E 0:00:12.743   Godot.Quat Godot.Quat.Slerp(Godot.Quat , Single ): System.InvalidOperationException: Quat is not normalized
  <C++ Error>   Unhandled exception
  <C++ Source>  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Quat.cs:236 @ Godot.Quat Godot.Quat.Slerp(Godot.Quat , Single )()
  <Stack Trace> Quat.cs:236 @ Godot.Quat Godot.Quat.Slerp(Godot.Quat , Single )()
                PlayerEntity.cs:232 @ void GodotThirdPersonShooterDemoWithCSharp.Player.PlayerEntity._PhysicsProcess(Single )()

```

There is also another issue, when the level loads the player is not on screen:
image

If I normalize the Quat()
image

It runs but the Slerp doesn't look right
The aimed rotation does't look right, I checked many times and I couldn't find any difference or mistake.
image

**Steps to reproduce:**
Just run the game from the mono_csharp branch
https://github.com/ricardoalcantara/godot-tps-demo-with-csharp/

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by ricardoalcantara**
closes #42241 and closes #42239

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Please read the second paragraph of https://github.com/godotengine/godot/issues/42241#issuecomment-698112184 before merging, but anyway the code is good.

**Comment by ricardoalcantara** [comment]
@aaronfranke Since you've fixed this already in other PR you may close this one.

**Comment by aaronfranke** [comment]
@ricardoalcantara No, I fixed the bindings generator, not RotationQuat's accessibility. This PR is still good.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
