### PR TITLE
FileDialog: enlarge the file list a bit

### PR DESCRIPTION
**Pull request by ghost**
After:

Edit: changed the ratio from 4:1 to 4:3 
image
image

Before:
[screenshot from 2017-10-06 21-08-19](https://user-images.githubusercontent.com/26753932/31281748-8a57eb78-aada-11e7-8451-5843f350c140.png)[screenshot from 2017-10-06 21-03-26](https://user-images.githubusercontent.com/26753932/31281661-4fa2250c-aada-11e7-93b3-653b574b513e.png)

### CODE REVIEW

**Comment by djrm** [comment]
@Noshyaar maybe it would be better if the filter button shows all its contents, instead of clipping them.

**Comment by akien-mga** [comment]
I like the change, but yeah something should be done for the filter drop-down list.

**Comment by akien-mga** [comment]
Bump - any idea how to improve this clipping of the file type selector?

**Comment by djrm** [comment]
the easiest way in my opinion (might not work on all possible cases) is to reduce the size of the file name input, file names are not that long, also the text could be clipped some units before the arrow, i dont think godot has a feature to mark clipped text (like ..., or some fade)

**Comment by Noshyaar** [comment]
Changed the ratio from 4:1 to 4:3

**Comment by akien-mga** [comment]
Looks good.

**Pull request merged**
