### PR TITLE
Add coloring for completion of Color components

### PR DESCRIPTION
**Pull request by Chaosus**
(Continuation of https://github.com/godotengine/godot/pull/74809)

изображение

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` 71699e08c9df78b7203fa4ef9cede28e995d6ace), it works as expected.

image

**Comment by Mickeon** [comment]
Using the axes colours makes sense, but feels somewhat "janky". Would it be worth to add other theme colours?

**Comment by Calinou** [comment]
> Using the axes colours makes sense, but feels somewhat "janky". Would it be worth to add other theme colours?

We could have generic editor colors that can be reused, similar to what https://github.com/godotengine/godot/pull/77114 adds for its own needs.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
