### PR TITLE
Fix SVG font rendering.

### PR DESCRIPTION
**Pull request by bruvzg**
- Fixes SVG font rendering broken by latest ThorVG update.
- Removes usage of private ThorVG API.

### CODE REVIEW

**Comment by fire** [comment]
Let us know when it's ready to be tested.

**Review by fire — APPROVED** [review]
I don't know how this works, but fewer private apis are good, and avoiding regressions is also good.

**Comment by fire** [comment]
What was broken? is there a mrp?

**Comment by bruvzg** [comment]
> What was broken?

Everything, it was failing to load any SVG font since private API we were using start returning zero size bounding box after some of the updates.

**Review by Repiteo — APPROVED** [review]
Codestyle checks out

**Pull request merged**
