### PR TITLE
Added support for generic type exported properties in gdscript

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
This change allows scripts to use untyped properties. Their type can be changed in the inspector the same way as for elements in `Array` or `Dictionary`.

This implementation uses properties of type `TYPE_NIL` with the existing usage flag `PROPERTY_USAGE_NIL_IS_VARIANT`.

Syntax for property list:
```
{
	"name": "generic_var",
	"type": TYPE_NIL,
	"usage": PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_NIL_IS_VARIANT,
	"hint": PROPERTY_HINT_NONE,
	"hint_string" : "",
}
```

Syntax for exported variable:
`export(Variant) var generic_export_var`

Property in the inspector:

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Why not handle this using `PROPERTY_USAGE_NIL_IS_VARIANT`?

**Comment by pouleyKetchoupp** [comment]
> 
> 
> Why not handle this using `PROPERTY_USAGE_NIL_IS_VARIANT`?

I guess I could! Thanks for the feedback.

I'm going to test and see if it causes any problem, since this flag is used for slightly different cases than the ones my changes handle. And if everything works fine, I'll add it to the documentation too.

**Comment by pouleyKetchoupp** [comment]
Done. I've also updated the PR description.

**Comment by aaronfranke** [comment]
@pouleyKetchoupp Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by pouleyKetchoupp** [comment]
Rebased on master and fixed. I think this feature is still needed as afaik there's no other way for scripts to use Variant properties.

If needed, I can write a proper proposal for this feature, but given that it's not very complex and doesn't change a lot of code it seems like a faster process can be applied.

Here are some details about the use case:
It's needed for any script system that works with generic types. I'm using it for an action sequence system for cutscenes implemented in gdscript. It supports condition nodes which compare values of any type set in the inspector with a variable from a database and that would be very cumbersome to implement without generic type properties.

**Comment by aaronfranke** [comment]
@vnen What do you think about this? I know there was a discussion of an `any` type in GDScript, and I think that feature should be harmonized with this one to use the same words (ex: either the generic type is `Variant` or here we would have `export(any)`).

**Comment by Xrayez** [comment]
> @vnen What do you think about this? I know there was a discussion of an `any` type in GDScript, and I think that feature should be harmonized with this one to use the same words (ex: either the generic type is `Variant` or here we would have `export(any)`).

I've stumbled upon this PR by accident, and worth mentioning that I've implement `VariantResource` class for this purpose in goostengine/goost#30 in 3.2. Treating this as a resource allows property hints and usage to be configured from within the resource as well, and of course allows to store such a thing as a regular resource on disk (also being able to generate resource previews etc.)

I can make a proposal about this upon pre-approval from the core developers.

**Comment by Xrayez** [comment]
I also have a dedicated PR to expose `PROPERTY_USAGE_NIL_IS_VARIANT` to scripting in #43185, which this PR also exposes.

**Comment by fire** [comment]
Is this pr still valid?

**Comment by Pennycook** [comment]
Is anybody still working on this?

I'm currently working around the lack of this feature by using `_get_property_list` and two properties (one denoting the type, another storing the `Variant`) which feels like a hack.

It's surprising to me that the Inspector provides support for untyped `Array`s, allowing selection of the type for every element individually, but does not support the case of a single value.

**Comment by aaronfranke** [comment]
Closing because this PR has conflicts and the original author is no longer interested in working on it. However, if anyone wants this feature, you are welcome to salvage it and work on it further.

**Comment by Pennycook** [comment]
> Closing because this PR has conflicts and the original author is no longer interested in working on it. However, if anyone wants this feature, you are welcome to salvage it and work on it further.

@aaronfranke, I'm interested in salvaging this.  What's the right way to do that?  Open a new PR?

**Comment by aaronfranke** [comment]
@Pennycook Yes, you will need to grab the changes, rebase them, push them to a branch on your fork, and open a PR.

**Pull request closed without merging**
