### PR TITLE
Fixed link errors when building in debug with RegEx module disabled

### LINKED ISSUE #30761: Can't compile godot without regex support
**Godot version:**
3.2.dev.custom_build. 47ab209b5

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
Can't compile godot with this command
```
scons p=x11 module_bmp_enabled=no module_bullet_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_gdnative_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_mbedtls_enabled=no module_mobile_vr_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_regex_enabled=no module_squish_enabled=no module_tga_enabled=no module_thekla_unwrap_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_vorbis_enabled=no module_webm_enabled=no module_websocket_enabled=no -j6
```
because this error shown after line `[ 82%] Linking Program        ==> bin/godot.x11.tools.64`
```
/usr/bin/ld: main/tests/libtests.x11.tools.64.a(test_string.x11.tools.64.o): in function `TestString::test_26()':
/home/rafal/Pulpit/godot/main/tests/test_string.cpp:440: undefined reference to `RegEx::RegEx(String const&)'
/usr/bin/ld: /home/rafal/Pulpit/godot/main/tests/test_string.cpp:441: undefined reference to `RegEx::sub(String const&, String const&, bool, int, int) const'
/usr/bin/ld: /home/rafal/Pulpit/godot/main/tests/test_string.cpp:440: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: /home/rafal/Pulpit/godot/main/tests/test_string.cpp:440: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: editor/libeditor.x11.tools.64.a(rename_dialog.x11.tools.64.o): in function `RenameDialog::_regex(String const&, String const&, String const&)':
/home/rafal/Pulpit/godot/editor/rename_dialog.cpp:516: undefined reference to `RegEx::RegEx(String const&)'
/usr/bin/ld: /home/rafal/Pulpit/godot/editor/rename_dialog.cpp:518: undefined reference to `RegEx::sub(String const&, String const&, bool, int, int) const'
/usr/bin/ld: /home/rafal/Pulpit/godot/editor/rename_dialog.cpp:516: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: /home/rafal/Pulpit/godot/editor/rename_dialog.cpp:516: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: editor/libeditor.x11.tools.64.a(rename_dialog.x11.tools.64.o): in function `RenameDialog::_postprocess(String const&)':
/home/rafal/Pulpit/godot/editor/rename_dialog.cpp:536: undefined reference to `RegEx::RegEx(String const&)'
/usr/bin/ld: /home/rafal/Pulpit/godot/editor/rename_dialog.cpp:537: undefined reference to `RegEx::search_all(String const&, int, int) const'
/usr/bin/ld: /home/rafal/Pulpit/godot/editor/rename_dialog.cpp:545: undefined reference to `RegExMatch::get_start(Variant const&) const'
/usr/bin/ld: /home/rafal/Pulpit/godot/editor/rename_dialog.cpp:536: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: /home/rafal/Pulpit/godot/editor/rename_dialog.cpp:536: undefined reference to `RegEx::~RegEx()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
This change allows to build godot with a command line like:
`scons platform=windows tools=no target=release_debug module_regex_enabled=no`

One of the string tests involving RegEx was causing link errors. Instead the test will fail with a specific message.

*Bugsquad edit:* Fixes #30761.

### CODE REVIEW

**Comment by qarmin** [comment]
Still can't compile, but it fix first part of issue.
Only this issues are now valid
```
/usr/bin/ld: editor/libeditor.x11.tools.64.a(rename_dialog.x11.tools.64.o): in function `RenameDialog::_regex(String const&, String const&, String const&)':
/home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:516: undefined reference to `RegEx::RegEx(String const&)'
/usr/bin/ld: /home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:518: undefined reference to `RegEx::sub(String const&, String const&, bool, int, int) const'
/usr/bin/ld: /home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:516: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: /home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:516: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: editor/libeditor.x11.tools.64.a(rename_dialog.x11.tools.64.o): in function `RenameDialog::_postprocess(String const&)':
/home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:536: undefined reference to `RegEx::RegEx(String const&)'
/usr/bin/ld: /home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:537: undefined reference to `RegEx::search_all(String const&, int, int) const'
/usr/bin/ld: /home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:545: undefined reference to `RegExMatch::get_start(Variant const&) const'
/usr/bin/ld: /home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:536: undefined reference to `RegEx::~RegEx()'
/usr/bin/ld: /home/rafal/Pobrane/godot-fix-test-regex-disabled/editor/rename_dialog.cpp:536: undefined reference to `RegEx::~RegEx()'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```

**Comment by pouleyKetchoupp** [comment]
Are you compiling with `tools=yes`? It probably doesn't make much sense to compile the editor and disable a feature that it needs to function correctly.

**Comment by qarmin** [comment]
So maybe it would be a good idea to block this option before editor compilation takes place?
But from other side, this seems to be only used in editor in rename_dialog, so disabling it  when compiling without regex, shouldn't be so hard.

**Comment by pouleyKetchoupp** [comment]
In what case would someone need to build a version of the editor with a feature disabled?

According to the documentation, these flags are used only for optimization purpose when building export templates.
https://docs.godotengine.org/en/3.1/development/compiling/optimizing_for_size.html

**Comment by qarmin** [comment]
I don't know why someone might to want to use Godot without Regex support, but it is possible to (try)compile engine without it.
Good example is a flag disable_3d, because when I try to compile Godot with scons disable_3d=yes, console shows this message
```
Build option 'disable_3d=yes' cannot be used with 'tools=yes' (editor), only with 'tools=no' (export template).
```
 and doesn't even start a compilation process

**Comment by pouleyKetchoupp** [comment]
Ok, I'll add the same thing for regex then.

**Comment by pouleyKetchoupp** [comment]
Done! I've made it so it will be easy to add more modules required for the editor in the future.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Note: If anyone is bothered by the mandatory `regex` module dependency in the editor, it should be trivial to make all regex code optional in the editor (it's only used in one place so far).

**Pull request merged**
