### PR TITLE
Fix routing of InputEventScreenDrag events to Control nodes

### LINKED ISSUE #29525: Control _gui_input inconsistent behavior with InputEventScreenTouch
**Godot version:**
3.1.1 (Live Steam version)

**OS/device including version:**
Windows, deploying to Android

**Issue description:**
When trying to respond to InputEventScreenTouched events on multiple buttons using multiple fingers, I am unable to get consistent events to the actual input events. One button will respond as expected, the other only responds to touch press, not touch released.

Instead, all buttons should get the appropriate touch events for pressed and released, instead of it being inconsistent.

**Steps to reproduce:**
Create two buttons with a simple script that prints messages for InputEventScreenTouch, the event ID, and whether it was pressed. Deploy this to Android with remote debugging. Use two fingers to press the buttons, first by pressing them individually. Then press the two buttons at once and release the left button while pressing down on the right. Then press the right button while holding down on the left.
In the given example, the left button will print out messages for touch DOWN and UP, the right button will only get the event for DOWN.

**Minimal reproduction project:**
[MultiTouch Input Button.zip](https://github.com/godotengine/godot/files/3260074/MultiTouch.Input.Button.zip)
You can use the given APK if you trust random files on the internet, otherwise export it yourself (remember to use remote debugging!)

**Notes**
Overall I'm a little disappointed in Godot's multitouch/mobile support for this input. The regular button does not have standard hooks for these inputs and there are no subclasses that could handle it either. Writing custom code for every button seems overkill when I simply want to fire on relevant touch/drag/press/release events that aren't strictly 'mouse like'. I noticed a Node2D button but it's not obvious what it's for, how to use it, and how to tie it in to an established Control-based GUI.

Thanks!
-Devin

### PR DESCRIPTION
**Pull request by m4gr3d**
Multitouch support enables multiple concurrent `InputEventScreenTouch` and `InputEventScreenDrag` events each differentiated by their `index` property.

An `InputEventScreenDrag` event typically follows another `InputEventScreenDrag` or `InputEventScreenTouch` event and thus should be routed to the target that last matched the previous touch event. 
Prior to this fix, in a multitouch scenario only the target of the first touch event was tracked, causing all subsequent multitouch drag events to be routed to that invalid target. The PR tracks the touch targets using the touch event's `index` property, and use that data to properly route drag events based on their matching `index` property.

[3.x version](https://github.com/godotengine/godot/pull/68630)

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/29525

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @Sauermann

**Comment by Sauermann** [comment]
I had a look at this PR and here are a few thoughts:

- The implementation seems to work for `Controls` in the root `Viewport` in my test-cases (I moved `Controls` around with `event.relative`) and the events are sent to the expected `Control`
- Same is valid for `Controls` in different `SubViewports`
- When a `Control` `A` is in the root `Viewport` and a different `Control` `B` is in an embedded `Window`, and both are dragged, then `A` doesn't receive `InputEventScreenDrag` events.
- Dragging or resizing an embedded `Window` has the effect, that no other `Control` or `Window` receives `InputEventScreenDrag` events, even if they were receiving these events previously.
- I didn't test `TouchScreenButton`

In order to make this work with `Windows` (not sure, how much of that should be supported), a necessary aspect would be to keep in each `Viewport` track, to which embedded `Window` each event should be sent in `Viewport::_sub_windows_forward_input`.
https://github.com/godotengine/godot/blob/aa4c286808bbf4b16346de40307fcd5b29f19697/scene/main/viewport.cpp#L2473

**Comment by m4gr3d** [comment]
> I had a look at this PR and here are a few thoughts:
> 
> * The implementation seems to work for `Controls` in the root `Viewport` in my test-cases (I moved `Controls` around with `event.relative`) and the events are sent to the expected `Control`
> * Same is valid for `Controls` in different `SubViewports`
> * When a `Control` `A` is in the root `Viewport` and a different `Control` `B` is in an embedded `Window`, and both are dragged, then `A` doesn't receive `InputEventScreenDrag` events.
> * Dragging or resizing an embedded `Window` has the effect, that no other `Control` or `Window` receives `InputEventScreenDrag` events, even if they were receiving these events previously.
> * I didn't test `TouchScreenButton`
> 
> In order to make this work with `Windows` (not sure, how much of that should be supported), a necessary aspect would be to keep in each `Viewport` track, to which embedded `Window` each event should be sent in `Viewport::_sub_windows_forward_input`.
> 
> https://github.com/godotengine/godot/blob/aa4c286808bbf4b16346de40307fcd5b29f19697/scene/main/viewport.cpp#L2473

@Sauermann From a quick look at `Viewport::_sub_windows_forward_input`, it doesn't seem to support raw touch events (no reference to `InputEventScreenTouch` or `InputEventScreenDrag`), so this fix doesn't apply to it.

If we intend to support touch events (and multi-touch) in a viewport's subwindows, then it should be another PR since we wouldn't be fixing an existing behavior, but adding a new capability.

**Comment by Sauermann** [comment]
Alternative to #49215
fixes #29525
Possibly related to #62597

**Comment by RandomShaper** [comment]
I see a possibility of dangling pointers to `Control`s in case they are deleted while they are still referenced. Maybe a simple fix is to store their `ObjectID` instead, similarly to what picking does.

**Comment by m4gr3d** [comment]
> I see a possibility of dangling pointers to `Control`s in case they are deleted while they are still referenced. Maybe a simple fix is to store their `ObjectID` instead, similarly to what picking does.

@RandomShaper Do you have reference for the picking logic I can look at?

The current approach follows the pattern I've seen in the [`GUI` struct](https://github.com/godotengine/godot/blob/0bb1e89fb7046209f64d46ccedc6b42645c96573/scene/main/viewport.h#L351) where `Control` nodes are held by their pointers ([example](https://github.com/godotengine/godot/blob/0bb1e89fb7046209f64d46ccedc6b42645c96573/scene/main/viewport.h#L378)).

**Comment by RandomShaper** [comment]
I mean usages like this:
https://github.com/godotengine/godot/blob/0bb1e89fb7046209f64d46ccedc6b42645c96573/scene/main/viewport.cpp#L668

In that specific case, the relevant `Control`s remove themselves from the list upon destruction. That said, it'd be interesting to know for sure if the other cases of use of raw pointers have safety guarantees because of some careful handling.

In this case of tracking which touch index is relevant to a specific control, I'd say that basing it on `ObjectID` is better than having to deal with some sort of callback mechanism to prune the map.

**Comment by m4gr3d** [comment]
@RandomShaper I've updated the logic to use the `ObjectID` instead.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
