### PR TITLE
[WIP] Add animation motion-matching

### PR DESCRIPTION
**Pull request by fire**
Improved UI and better matching. Frame choosing behavior working

TODO: Correct the cost and trajectory predictions

Try to get https://github.com/godotengine/godot/pull/29892 merged. Attempt to fix all the cicd errors.

### CODE REVIEW

**Comment by akien-mga** [comment]
Wouldn't it be worth asking @Aa20475 to do changes in #29892 instead of forking the PR?

**Comment by fire** [comment]
My goal is to keep it current so the system doesn't rot too much.

@Aa20475 Feel free to comment or take control.

Noticed that cicd is failing on unsigned integers versus integer comparisons.

**Comment by fire** [comment]
Resolved CICD errors, but lacking test project and design documentation.

**Comment by fire** [comment]
Closing due to the inability to use this in a game project. This animation motion matching pr is salvageable.

**Pull request closed without merging**
