### PR TITLE
Remove support for legacy bone binds from godot. All skin binds must be named

### PR DESCRIPTION
**Pull request by lyuma**
@fire informed me that numbered bone binds for Skin are a legacy feature, and that godot is moving in the direction of using named binds for Skins.

After running into the issue leading to PR #48913 , I think that it is error-prone and confusing to support two different Skin systems. Clearly this change should not be made in the 3.x branch as it could break compatibility, but I think 4.x ought to consider removing the legacy system.

### CODE REVIEW

**Review by fire — APPROVED** [review]
I approve of this, but I think the decision is on reduz. He's the expert on this.

We chatted in Godot Engine chat about how backwards compatibility breakage is not a concern, but it wasn't clear why this is blocked.

**Comment by reduz** [comment]
Scenes made in 3.x wont work, although it may be an option to ask users to re-import them with this setting on before loading them on 4.0. Not sure what others think about it.

**Comment by fire** [comment]
We discussed bind id (integer) vs bind name (string) between I and Lyuma:

1. Most of the time, users will be using skins imported from a glb that is already using bind names.
2. A revision to this proposal is to force the remaining importers to use bind names in 3.x and then remove bind ids in 4.x.
3. This implies a workflow that people need to open the project in compatibility upgrade version of 3.x.

**Comment by fire** [comment]
@lyuma Task to rebase.

**Comment by lyuma** [comment]
Just to note, this change will break all existing Skin objects and require a reimport. I tried opening a project from an older build of godot 4, and I get these errors:
```
ERROR: Skin bind #0 does not contain a name nor a bone index.
   at: Skeleton3D::_notification (scene\3d\skeleton_3d.cpp:249)
ERROR: Skin bind #1 does not contain a name nor a bone index.
   at: Skeleton3D::_notification (scene\3d\skeleton_3d.cpp:249)
ERROR: Skin bind #2 does not contain a name nor a bone index.
   at: Skeleton3D::_notification (scene\3d\skeleton_3d.cpp:249)
```
It looks like this:
image

(all bones appear to be bound to bone 0)

**Comment by lyuma** [comment]
Closing because there wasn't consensus.

**Pull request closed without merging**
