### PR TITLE
[3.x] OSX: Add signing of directory structure when exporting for OSX

### PR DESCRIPTION
**Pull request by piiertho**
Port of #56047

### CODE REVIEW

**Comment by pycbouh** [comment]
Please amend the commit to use the original commit message, at least as the first line.

**Comment by piiertho** [comment]
> Please amend the commit to use the original commit message, at least as the first line.

This is done :)

**Comment by piiertho** [comment]
Why some checks have been cancel ?

**Comment by Calinou** [comment]
> Why some checks have been cancel ?

I re-ran them manually; let's see if they complete this time.

**Comment by piiertho** [comment]
> > Why some checks have been cancel ?
> 
> 
> 
> I don't know. I re-ran them manually; let's see if they complete this time.

Still fails with cancel :s

**Comment by akien-mga** [comment]
There's a GitHub Actions bug on this PR, when builds are queued for too long (which happens with macOS jobs as they're more limited so we run out of allocated resources fast) it cancels them.

I think it's because this was a first time contributor PR with manual approval, there must be a buggy codepath there.

I've tried to restart them 4 times but there's always an hour or more of waiting time for a macOS build so they get cancelled.

Maybe try to rebase and force push. Now that you have a merged PR it should no longer require approval and might side step that bug.

Though there seems to be another CI bug on the 3.x branch right now so maybe wait a bit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
