### PR TITLE
[Drivers] Improve error messages with `vformat`

### PR DESCRIPTION
**Pull request by AThousandShips**
See:
* https://github.com/godotengine/godot/pull/98091

### CODE REVIEW

**Comment by clayjohn** [comment]
Have you validated that this doesn't have any performance overhead? A lot of the driver code contains relatively hot paths, so the impact of a performance regression will be more notable.

**Comment by AThousandShips** [comment]
That's a good point, will close this one until I've done my performance improvements to the performance of `vformat`

**Comment by AThousandShips** [comment]
Note though that the error message is only evaluated *if* the error condition is triggered or the warning is actually printed, see the error macro:
https://github.com/godotengine/godot/blob/ec6a1c0e792ac8be44990749800a4654a293b9ee/core/error/error_macros.h#L417-L422

But staying on the safe side with these and reopening when I've done my performance improvement on `printf` that I've been planning for these

**Comment by clayjohn** [comment]
> Note though that the error message is only evaluated if the error condition is triggered or the warning is actually printed, see the error macro:

That's right, and when you are hitting the error condition you also have the overhead of printing the error to console etc. Which is why some some performance analysis is in order. It may be the case that the cost of vformat is a drop in the bucket compared to the other costs associated with printing an error. But that needs to be checked. 

Also, since this is part of an effort to standardize a codestyle across the codebase, we need to consider whether it is worth having one codestyle for error messages and another for other parts of the code.

**Comment by AThousandShips** [comment]
> Also, since this is part of an effort to standardize a codestyle across the codebase, we need to consider whether it is worth having one codestyle for error messages and another for other parts of the code.

There's no distinction between error and non-error code enforced here, these are just the most clear and direct cases I chose to apply to, it's just that error cases are the most simple and numerous to apply on

**Comment by AThousandShips** [comment]
Now for the relative performance I don't know how we'd benchmark error printing itself directly, and I suspect there's some non-insignificant overhead already just by printing it to console etc.

But if the benchmarks are anything to go by using `vformat` takes about 18% longer, and will hopefully be improved by my planned improvements there

**Pull request closed without merging**
