### PR TITLE
Documented classes Curve*, Path*, and PathFollow*

### PR DESCRIPTION
**Pull request by Ovnuniarchos**
This is a split of #2347 .
I've added, some documentation for the classes Curve*, Path*, and PathFollow*. I tried to make them as detailed and "for dummies" as possible, but my wording might not be the best.
Anyone able to explain better, feel free to do so.

### CODE REVIEW

**Comment by jackmakesthings** [comment]
Nice, but it looks like your commit deletes the documentation for GraphNode, among others - probably want to clean that up before merging, unless those deletions were intentional.

**Comment by akien-mga** [comment]
@Ovnuniarchos As mentioned above you mistakenly removed some stuff in your above commit, and since there is now a merge conflict, could I ask you to do it based on the current master branch?

**Comment by Ovnuniarchos** [comment]
There should be no conflicts now.

**Comment by akien-mga** [comment]
Thanks, the overall diff looks better indeed. Could you try to merge the second commit into the fix one as a fixup? I.e., in your branch, do:
- ```git rebase -i HEAD~2```
- Then change the "pick" keyword in front of 19a2bd0 to "fixup", and save the changes
- It should then have merged the second commit into the first one
- ```git push -f origin DocCurvePathPFollow```

**Comment by Ovnuniarchos** [comment]
Done.

**Comment by akien-mga** [comment]
Awesome, thank you! Keep them coming, the goal is to have the classes fully documented for 2.0.

**Pull request merged**
