### PR TITLE
Add files to tree view

### LINKED ISSUE #21473: Add ability to sort filenames in FileSystem Panel by value.
**Godot version:**
3.1 5df9109

**OS/device including version:**
Windows 10 HD 4600

**Issue description:**
I have some folders with levels which are named like 1,2,3... but level in 10 folder is putted between 1 and 2 instead after 9 

I tried to found option in settings but I can't find it. 

Current sort - checks character by character
niepos

Better for me sort - first checks the value of the number. It should be sorted also with name before number like "ziemniak7", "ziemniak8", "ziemniak9", "ziemniak10"
pos

### PR DESCRIPTION
**Pull request by groud**
Alright, this is a big PR donated by Gamblify.

It allows managing files in the file system tree view. It features:
- Multiple selection,
- RMB operations as you can have in the file list,
- Files saved as favorites,
- Small type icons for each type of file.
- etc...

output

This is **disabled by default** for performance reasons. We have to measure the impact of this PR on big projects first.

I'll rebase everything once it get's accepted, I don't want to loose my history for now. :)

Edit : Also adds small thumbnails for textures in the tree:
2018-09-13-162906_206x230_scrot

Closes #21473

### CODE REVIEW

**Comment by groud** [comment]
Ping @uldall and @Keetz

**Comment by aaronfranke** [comment]
Would it be feasible for this to completely replace the bottom file view? I'm not too big a fan of having the view split if it's not necessary.

**Comment by groud** [comment]
It is already possible, you can disable the split view in the editor settings.

**Comment by uldall** [comment]
@jesperkondrup Will you test this as well?

**Comment by groud** [comment]
> We have talked about it briefly, but it would be great if textures would show a small thumbnail of the image.

It is indeed planed. but I keep it for a separate PR. It should make the review easier.

**Comment by jesperkondrup** [comment]
Current Issues: 
- [ ] It's not possible to select a file in the tree view and press the "delete button" this will delete a node in if you have the scene view open. 
- [ ] There should be a small thumbnail preview of png images instead of the icon.

**Comment by groud** [comment]
> Issue: It's not possible to select a file in the tree view and press the "delete button" this will delete a node in if you have the scene view open.

Fixed :)

**Comment by groud** [comment]
I also added changes to fix #21473. The files are now sorted by natural order.

**Comment by groud** [comment]
I added the thumbnails in the tree for textures and materials:
2018-09-13-162906_206x230_scrot

**Comment by groud** [comment]
Alright, added search to the tree view and drag&drop into favorites:
output

**Comment by groud** [comment]
Display mode toggle + favorite drag&drop
output

**Comment by akien-mga** [comment]
> Alright, added search to the tree view

The "discard" icon in the search widget looks weird, as if upscaled.
See how it looks like in current master:
screenshot_20180914_095140
screenshot_20180914_095156

**Comment by groud** [comment]
> The "discard" icon in the search widget looks weird, as if upscaled.
See how it looks like in current master

yeah I noticed that too. Does it happen if you checkout my branch ?

**Comment by groud** [comment]
In fact it's a problem from my build, the same problem happens on master.

**Comment by Keetz** [comment]
A few bugs and observations testing:

- There doesn't seem to be thumbnails on favorites

- I get an error when I start dragging something in the filesystem (tree or not), it works but gives an error
```
ERROR: set_drag_preview: Condition ' get_viewport()->gui_is_dragging() ' is true.
   At: scene/gui/control.cpp:772.
```

- If you have just a single favorite file and you drag it above itself, it gives a index out of size error and it disappears from the favorites. Not only happening with a single favorite, it was just to simplify it. It happens when dragging a favorite to the first position in the list
```
ERROR: insert: Index p_pos=-1 out of size (size() + 1=1)
   At: ./core/cowdata.h:168.
```
- Godot crashes when testing on a project with a large number of files. Maybe trying to generate the  thumbnails? (https://github.com/jesperkondrup/GodotFileSystemTest)
```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f0df1d284b0] (??:0)
[2] EditorResourcePreview::_generate_preview(Ref<ImageTexture>&, Ref<ImageTexture>&, EditorResourcePreview::QueueItem const&, String const&) (/home/rke/git/external/godot_groud/godot/editor/editor_resource_preview.cpp:161 (discriminator 14))
[3] EditorResourcePreview::_thread() (/home/rke/git/external/godot_groud/godot/editor/editor_resource_preview.cpp:240)
[4] EditorResourcePreview::_thread_func(void*) (/home/rke/git/external/godot_groud/godot/editor/editor_resource_preview.cpp:94)
[5] ThreadPosix::thread_callback(void*) (/home/rke/git/external/godot_groud/godot/drivers/unix/thread_posix.cpp:72)
[6] /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f0df2b696ba] (??:0)
[7] /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f0df1dfa41d] (??:0)
-- END OF BACKTRACE --
```

**Comment by akien-mga** [comment]
Thanks @groud and Gamblify for the contribution!

**Comment by jesperkondrup** [comment]
Nice work! This has been on our wish list for the last two years :)

**Pull request merged**
