### PR TITLE
Fixed bullet kinematic char sliding

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixed sliding of kinematic character in bullet.

The problem was caused by threshold that Bullet use by default and also the reported penetration in particular cases are positive but valid.

### CODE REVIEW

**Comment by hpvb** [comment]
Could this be safely cherry picked into stable? I'm wondering what will happen to projects that have already worked around the issue.

**Comment by AndreaCatania** [comment]
Basically the workaround is increase the safe margin a bit. I don't think that it could be a big problem since it's easy reset it

**Comment by hpvb** [comment]
Users shouldn't have to adjust their projects for it to start working again though. I can see if we can detect  this workaround and not apply this fix maybe?

**Comment by AndreaCatania** [comment]
It's simple reset this parameter when they open the editor but If you don't like the idea to "force" him to reset the margin is better to not cherrypick it and leave the bug ...

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.

**Pull request merged**
