### PR TITLE
Fix Editor Crash on closing

### LINKED ISSUE #10034: Crash on close editor
**Operating system or device - Godot version:**
Windows 10
Build on comit https://github.com/godotengine/godot/commit/3180827387f3a0f240f911227fd42d93bb4c9b13

**Issue description:**
Godot editor is crashed on quit after commit https://github.com/godotengine/godot/commit/3180827387f3a0f240f911227fd42d93bb4c9b13
Version before this commit quit correctly.

**Steps to reproduce:**
Close editor on windows OS

### PR DESCRIPTION
**Pull request by ISylvox**
Should fix #10034 

Edit: Tested and worked on Win 10 x64.

### CODE REVIEW

**Comment by akien-mga** [comment]
cc @marcelofg55

**Comment by ISylvox** [comment]
Pretty ping @reduz (^_^)

**Comment by ISylvox** [comment]
Thing is going to be complicated. Simple doesn't always mean bad. We really do not need to add unnecessary audio_server->finish() to void Main::cleanup(). Let's keep in mind that AudioDriver singleton is NOT the same as AudioDriverManager. But, well... (^-^)

**Comment by marcelofg55** [comment]
Well, if you remove the audio_server->finish() line then AudioServer::finish is never called and the variable buses is never freed, and so we have a memory leak there. So in my opinion the audio_server->finish() is not unnecessary.

**Comment by ISylvox** [comment]
AudioServer::finish doesn't need to be called at Main::cleanup, because AudioServer will just need to be destroyed if still exist in memory : 

	if (audio_server) {
		memdelete(audio_server);
	}

From : https://github.com/godotengine/godot/pull/10028

"I found out about this when I got a crash on the update_mix_time function, since the AudioServer::finish was not getting called the audio process function was still running and then I got a crash on update_mix_time (it happens rarely on quitting)." --- marcelofg55

"It happens rarely on quitting" doesn't mean it's a fixed problem, instead an uncertain or random problem which could be checked further.

**Comment by marcelofg55** [comment]
Did you check that without the audio_server->finish() line I added the AudioServer::finish actually doesn't get called ever? It's not a useless function, it must be called when godot is quitting.

**Comment by ISylvox** [comment]
Sure, it doesn't get callled. This is where our opinion differs. You do think that AudioServer::finish need to be called, while I don't see a need to call that function inside Main::cleanup() . I can't guarantee that my solution is better. What I would say is that: with audio_server->finish included, I have godot editor always crash on quitting, while never encounter even a single crash if audio_server->finish() removed. Thus, this PR was submitted. But, a better solution is always appreciated. :-)

**Comment by akien-mga** [comment]
@ISylvox Did you check #10045?

**Comment by ISylvox** [comment]
@akien-mga Just checked and tested https://github.com/godotengine/godot/pull/10045 . I'm getting Godot Editor crashing when quit it. So, I did force close.

marcelofg_01


Let's take a look at the real issue:
This problem was introduced when this PR (https://github.com/godotengine/godot/pull/10028) merged. 

As we know, his PR (https://github.com/godotengine/godot/pull/10045) want to solve new issue that introduced by https://github.com/godotengine/godot/pull/10028. While, actually https://github.com/godotengine/godot/pull/10028 itself is already an issue. Why? Because it was trying to solve an unclear issue that happen rarely or randomly, also no steps provided how to reproduce the issue mentioned in the PR (https://github.com/godotengine/godot/pull/10028) itself.

In other words:

PR https://github.com/godotengine/godot/pull/10028 want to solve an unclear issue which happen rarely or randomly, mentioned in PR https://github.com/godotengine/godot/pull/10028 itself -->> PR https://github.com/godotengine/godot/pull/10028 introduced New Issue -->> Now, PR https://github.com/godotengine/godot/pull/10045 comes to solve issue that introduced by https://github.com/godotengine/godot/pull/10028 (the previous PR).

Well... Let's do a win-win solution: Close this https://github.com/godotengine/godot/pull/10045 -->> merge this https://github.com/godotengine/godot/pull/10036 -->> Search for exact issue (as mentioned here https://github.com/godotengine/godot/pull/10028) that could happen  --> Write steps to reproduce the issue -->> Discussing solution

Thanks... And please, forgive my mistake. :-)

**Comment by ISylvox** [comment]
@akien-mga Just checked and tested https://github.com/godotengine/godot/pull/10045 . I'm getting Godot Editor crashing when quit it. So, I did force close.

marcelofg_01


Let's take a look at the real issue:
This problem was introduced when this PR (https://github.com/godotengine/godot/pull/10028) merged. 

As we know, this PR (https://github.com/godotengine/godot/pull/10045) want to solve new issue that introduced by https://github.com/godotengine/godot/pull/10028. While, actually https://github.com/godotengine/godot/pull/10028 itself is already an issue. Because it was trying to solve an unclear issue that happen rarely or randomly, also no steps provided how to reproduce the issue mentioned in the PR (https://github.com/godotengine/godot/pull/10028) itself.

In other words:

PR https://github.com/godotengine/godot/pull/10028 want to solve an unclear issue which happen rarely or randomly, mentioned in PR https://github.com/godotengine/godot/pull/10028 itself -->> PR https://github.com/godotengine/godot/pull/10028 introduced New Issue -->> Now, PR https://github.com/godotengine/godot/pull/10045 comes to solve issue that introduced by https://github.com/godotengine/godot/pull/10028 (the previous PR).

Well... Let's do a win-win solution: Close this https://github.com/godotengine/godot/pull/10045 -->> merge this https://github.com/godotengine/godot/pull/10036 -->> Search for exact issue (as mentioned here https://github.com/godotengine/godot/pull/10028) that could happen  --> Write steps to reproduce the issue -->> Discussing solution

Thanks... And please, forgive my mistake. :-)

**Comment by marcelofg55** [comment]
Did it say where it crashed?
I really don't understand why you think that calling the AudioServer::finish function is an issue, it's like saying that we shouldn't call VisualServer::finish when godot quits.

**Comment by akien-mga** [comment]
Superseded by #10045.

> Just checked and tested #10045 . I'm getting Godot Editor crashing when quit it. So, I did force close.

@ISylvox If you still reproduce that issue now that #10045 was merged (it was a good technical change and harmonization of the audio server finishing), please open a new bug report so that it can be investigated further. This call to `AudioServer::finish()` makes sense and should be kept, so if there's still a bug it should be fixed someplace else.

**Pull request closed without merging**
