### PR TITLE
Improve editing of box collision shapes

### LINKED ISSUE #452: Allow moving only one side of extents-based rectangles/boxes using editor gizmos
**Describe the project you are working on:**
2D game.

**Describe the problem or limitation you are having in your project:**
I often use CollisionShape2D nodes with rectangle shapes. Their problem is that you need to place the rectangle in the middle of the object and expand the extents to match the object's size. Because the extents increase from both sides and it's not always obvious where object's center may be, it often requires trial-and-error to get done correctly, which is simply a waste of time.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
If I could change the rectangle's extents with handles on any side, like this is done with scaling Sprites or resizing Control nodes, it would save some time and make adding colliders more friendly.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
image
image

**Describe implementation detail for your proposal (in code), if possible:**
RectangleShapes2D should be edited like Control rectangles. This can be achieved by editing `extents` of RectangleShape2D and `position` of CollisionShape2D simultaneously.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, it would require a plugin.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a QoL thing for collision shapes.

### LINKED ISSUE #5669: Allow EditorNode3DGizmoPlugin to get initial handle value
### Describe the project you are working on

Playing around with the built-in gizmo plugins.

### Describe the problem or limitation you are having in your project

The current `EditorNode3DGizmoPlugin` workflow is like this:

* When `_set_handle()` is called, the plugin updates the `Node3D` according to the handle value.
* When `_commit_handle()` is called:
    * If `canceled`, the plugin resets the `Node3D` with the provided initial handle value.
    * If not `canceled`, the plugin creates an undo-redo entry for the initial & current value.

The initial handle value is fetched by `EditorNode3DPlugin` when clicking the handle.

Not knowing the initial value makes it hard to switch modes when dragging the handle. For example, when dragging a rectangle `CollisionShape2D`, it allows you to switch between changing size only and changing both size and position. This is not possible in 3D as you lost the original node translation once dragged.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With the original value available, properties can be updated in `_set_handle()` by relative value instead of absolute value.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Provide a way to get the initial handle value.

* Add a parameter in `_set_handle()`, or
* Add a method on `EditorNode3DGizmo` to provide the initial value, or
* Add a `_prepare_handle()` method to let the user record it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

* Create a custom `EditorNode3DGizmo` and add a `initial_value` property.
* In `_set_handle()`, check if `initial_value` is ever set. Save the current handle value when not.
* In `_commit_handle()`, clear `initial_value`.

This is hacky I think because it relies on `_commit_handle()` always being called, so a "begin" state can be detected.

### Is there a reason why this should be core and not an add-on in the asset library?

It needs to modify how 3D gizmo plugin works.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/452

There is still some weird jitter issue I need to fix.
godot windows editor dev x86_64_d82DN0hJzE

EDIT:
Closes https://github.com/godotengine/godot-proposals/issues/5669

### CODE REVIEW

**Comment by lukester535** [comment]
vvonderful

**Comment by KoBeWi** [comment]
Jitter is fixed 🥳

https://user-images.githubusercontent.com/2223172/217683832-c3ae3594-de94-41df-a07a-7b238b4fe042.mp4

There's a small issue where the box can't be shrunk past its center position:

https://user-images.githubusercontent.com/2223172/217686193-ecc229d7-0d59-4ee9-a581-e53c435a1df6.mp4

But this is caused by the fact that the result of `get_closest_points_between_segments()` never goes below 0. It's probably solvable some more math tricks, but I don't want to touch this anymore .-.

Another thing is that there are at least 4 different gizmos for box editing and this PR handles only one. I plan to make a follow-up PR and unify this. And maybe do the same treatment for capsule and cyllinder shapes, because they have the same 2-side problem.

**Comment by rburing** [comment]
When the shape resource is shared this will have the same issue as https://github.com/godotengine/godot/issues/73186, since the position is not part of the resource. I wonder how we should handle this, since I do like the otherwise improved editor experience.

**Comment by KoBeWi** [comment]
See my comment in that issue.

**Comment by Calinou** [comment]
Tested locally, it mostly works correctly. One issue is that snapping acts weirdly: your non-snapped movement is still added to the final size if you start holding <kbd>Ctrl</kbd> after moving the mouse, which is unexpected. Instead, the size should be snapped to an absolute value.

**Comment by KoBeWi** [comment]
> When downsizing, you can't resize to below half of the original size unless the mouse moves slowly enough.

As I mentioned before, it's a result of how `get_closest_points_between_segments()` works. Although I have an idea for workaround, maybe it will work 🤔

> Also, once the logic behind this is stabilized, this should probably be moved to reusable functions so that it can be implemented in similar gizmos like CSGBox3D, VoxelGI and ReflectionProbe.

That's what I plan to do, but I wanted this PR to be merged first.

**Comment by rburing** [comment]
Unless shape resources are going to be duplicated on copy by default, I think the convenience of this PR is not worth the confusion that will be caused by applying this operation to a shared shape resource.

With that big side effect I don't think we can reasonably make this behavior the default. If it is implemented at all it should somehow be made clear that it affects (in a weird way) other resources sharing the same shape.

**Comment by KoBeWi** [comment]
The problem with shared shapes is that they change size unexpectedly, not that they are displaced. This PR doesn't make it any worse.

**Comment by KoBeWi** [comment]
Ok rebased.
I fixed snapping and the half-size bug.
I also noticed that for some reason pressing any key would cancel gizmo operation (which most notably made using Alt/Ctrl impossible). I changed it to use only Escape/Backspace.

**Comment by Calinou** [comment]
Works great now! The only issue I noticed is that the snap length is halved when not extending relative to the center by holding <kbd>Alt</kbd>. (For instance, snap length is 0.5 units when it should be 1 unit.)

**Comment by KoBeWi** [comment]
Unfortunately I don't know how to fix the half snapping. If I simply multiply by 2, I end up with some weird offset. I tried different combinations, but none made it work correctly :/
It's a minor thing compared to the overall better usability, so IMO this is something that can be fixed later.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of on top of `master` dfebfd10a863b6df8491933384d00f6757da0a66), it works as expected.

Code looks good to me at a glance. Given how much this improves usability, I think this can be merged now and @KoBeWi can take a look at making this code more generic to work with similar 3D gizmos.

https://github.com/godotengine/godot/assets/180032/f0e83970-c040-42ca-abb6-ee09f6efb1d9

**Comment by akien-mga** [comment]
Probably worth a rebase before merging as this was last updated in April.

**Comment by akien-mga** [comment]
Thanks!

**Comment by ashelleyPurdue** [comment]
> It's a minor thing compared to the overall better usability, so IMO this is something that can be fixed later.

On the contrary: the "half snapping" bug makes this feature nearly useless for level design(which, I assume, is its intended purpose).  If you can't reliably snap to a grid, then you can't ensure that your walls are correctly lined up with your floors and ceilings, for example.  Please don't try to write it off as something to be fixed "later".

**Comment by Kluskey** [comment]
Thank you!! This is super helpful

**Comment by huesonmcgee** [comment]
Will this apply to CSG as well?  If not that would be exceptionally helpful during the prototyping stage.

**Comment by KoBeWi** [comment]
There was a follow-up that applied it to every existing box gizmo: https://github.com/godotengine/godot/pull/80278

**Comment by huesonmcgee** [comment]
Awesome, thank you.  This is a well appreciated addition.

**Comment by TrainzMarcel** [comment]
this is awesome!!!! this is something ive wanted for so long

**Pull request merged**
