### PR TITLE
Fix subpixel layouts in text rendering

### PR DESCRIPTION
**Pull request by botero-dev**
The RGB subpixel layout configuration was actually doing subpixel rendering for the BGR layout.

### CODE REVIEW

**Comment by YuriSizov** [comment]
@0xafbf Sorry for not getting back earlier. Could you demonstrate the difference? It looks like a typo, but it's hard to say if the output looks as expected or not with or without these changes.

**Comment by bruvzg** [comment]
IMG_20231110_201341

I'm not 100% sure, but existing order seems to be working correct.

On the picture display, subpixel order is horizontal R→G→B, and Godot AA setting have it set to HRGB (default). A text rendered by Godot has blue tint is on the left red on the right, so it is already working as expected.

So this change is probably wrong.

**Comment by 0xafbf** [comment]
In the screenshot you share, look how the red subpixel gets lit when the blue one should be lit, and it is unlit when the blue one should be unlit
image

**Comment by bruvzg** [comment]
> In the screenshot you share, look how the red subpixel gets lit when the blue one should be lit, and it is unlit when the blue one should be unlit

Yes, you are probably right, and tint is likely chromatic aberration from the lens. After looking at a different angle and closer distance (can take a photo in this position) it looks more correct with the changed order.

**Review by bruvzg — APPROVED** [review]

**Comment by 0xafbf** [comment]
I already had the picture when I saw you already commented. I'm posting it for reference. Left is previous, right is with PR fix:
Untitled

Picture quality is not the greatest, because I was taking photo from microscope screen. The change is the most noticeable with text with lines of a single pixel width.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
