### PR TITLE
Docs: vertical methods layout

### PR DESCRIPTION
**Pull request by ghost**
A vertical layout for methods in the docs:

| master | PR |
| --- | --- |
| pre1 | post1 |
| pre3 |  post3 |
|  pre2 | post2 |

### CODE REVIEW

**Comment by akien-mga** [comment]
Personally I find the existing style more readable, but let's see what others think about the proposal.

I don't understand why there is a vertical space between `aspect()` and `bounce()` but not between `angle_to_point()` and `aspect()` though, seems inconsistent.

**Comment by groud** [comment]
> Personally I find the existing style more readable

Me too.

**Comment by poke1024** [comment]
The spacing is just a grouping by the first letter to add some structure. For some cases, like `get_`, `set_`, `move_`, `to_` this makes sense.

**Comment by HummusSamurai** [comment]
I think it should be possible to toggle between the styles with a button placed in the Docs pages.

**Comment by groud** [comment]
> I think it should be possible to toggle between the styles with a button placed in the Docs pages.

No, no need to bloat the interface with close to pointless buttons. The more we add that kind of option,  the harder you make the learning of the engine usage.

Regarding the PR, the only change I like is that the function description is closer to the text. But there is too much space between two desriptions.

**Comment by puppetmaster-** [comment]
Do I get a carriage return on my inserted text when I select and copy the text with the mouse and paste it into script? Or is it just a display flaw in the image?
image

**Comment by akien-mga** [comment]
As mentioned here and confirmed with @reduz on IRC, we prefer #14692, so closing this one.

**Pull request closed without merging**
