### PR TITLE
zstd: Make sure `huf_decompress` is only applied to 64-bit x86.

### LINKED ISSUE #96295: Compilation failure when cross-compiling for RISC-V
### Tested versions

- Reproducible in all Godot 4.x versions

### System information

Godot v4.3.rc (322e93592) - Debian GNU/Linux trixie/sid trixie - X11 - Vulkan (Forward+) - (software emulation on CPU) llvmpipe (LLVM 17.0.6, 256 bits) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (4 Threads)

### Issue description

When cross-compiling for RISC-V, once it reaches the end and tries to link the binary, it fails with this error:
```bash
[Initial build] Compiling core/config/engine.cpp ...
[Initial build] Compiling core/config/project_settings.cpp ...
[Initial build] Compiling core/error/error_list.cpp ...
[Initial build] Compiling core/error/error_macros.cpp ...
[Initial build] progress_finish(["progress_finish"], [])
[Initial build] Generating servers/rendering/renderer_rd/shaders/environment/voxel_gi_sdf.glsl.gen.h ...
[Initial build] Generating servers/rendering/renderer_rd/shaders/giprobe_write.glsl.gen.h ...
[Initial build] Linking Static Library core/libcore.linuxbsd.template_debug.rv64.llvm.a ...
Ranlib Library core/libcore.linuxbsd.template_debug.rv64.llvm.a ...
[Initial build] Linking Program bin/godot.linuxbsd.template_debug.rv64.llvm ...
mold: fatal: huf_decompress_amd64.linuxbsd.template_debug.rv64.llvm.o: incompatible file type: riscv64 is expected but got x86_64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.linuxbsd.template_debug.rv64.llvm] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:22:31.85]
```

### Steps to reproduce

1. Follow the instructions [here](https://github.com/godotengine/godot-docs/pull/9862) to have a risc-v cross-compilation toolchain.
2. Execute the build command in the above guide
3. Wait for link failure.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MBCX**
Fixes #96295

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
This looks like a good change. We should never be including x86_64 assembly when not on x86_64, so that architecture check really should be there. In fact, it is surprising that non-x86_64 architectures work at all with the existing code, I wonder why?

**Review by fire — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]
The ASM file seems to have a stub for the ARM to allow keeping it included, but the actual code is x86-64 only.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Comment by WhalesState** [comment]
> This looks like a good change. We should never be including x86_64 assembly when not on x86_64, so that architecture check really should be there. In fact, it is surprising that non-x86_64 architectures work at all with the existing code, I wonder why?

arm64 build is broken.

**Comment by WhalesState** [comment]
arm64 build may be broken after this change.

**Comment by akien-mga** [comment]
> arm64 build may be broken after this change.

What error are you getting?

**Comment by WhalesState** [comment]
> > arm64 build may be broken after this change.
> 
> What error are you getting?

```
/usr/bin/ld: core/libcore.linuxbsd.template_release.arm64.llvm.a(huf_decompress.linuxbsd.template_release.arm64.llvm.o): in function HUF_decompress4X2_usingDTable_internal':
huf_decompress.c:(.text+0x2512): undefined reference to HUF_decompress4X2_usingDTable_internal_fast_asm_loop'
/usr/bin/ld: core/libcore.linuxbsd.template_release.arm64.llvm.a(huf_decompress.linuxbsd.template_release.arm64.llvm.o): in function HUF_decompress4X1_usingDTable_internal':
huf_decompress.c:(.text+0x46ab): undefined reference to HUF_decompress4X1_usingDTable_internal_fast_asm_loop'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/blazium.linuxbsd.template_release.arm64.llvm.mono] Error 1
scons: building terminated because of errors.
[10:20 AM]
Linux build
[10:21 AM]
/usr/bin/ld: core/libcore.linuxbsd.editor.arm32.llvm.a(huf_decompress.linuxbsd.editor.arm32.llvm.o): in function HUF_decompress4X2_usingDTable_internal':
huf_decompress.c:(.text+0x2182): undefined reference to HUF_decompress4X2_usingDTable_internal_fast_asm_loop'
/usr/bin/ld: core/libcore.linuxbsd.editor.arm32.llvm.a(huf_decompress.linuxbsd.editor.arm32.llvm.o): in function HUF_decompress4X1_usingDTable_internal':
huf_decompress.c:(.text+0x431b): undefined reference to HUF_decompress4X1_usingDTable_internal_fast_asm_loop'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/blazium.linuxbsd.editor.arm32.llvm.mono] Error 1
scons: building terminated because of errors.
```
Building with flags: platform=linuxbsd target=editor tests=false verbose=yes warnings=no progress=no module_mono_enabled=yes arch=arm32 use_llvm=yes lto=none

**Comment by akien-mga** [comment]
Thanks, I can reproduce it with clang on Fedora 41. I'll open a dedicated bug report.

**Comment by WhalesState** [comment]
> Thanks, I can reproduce it with clang on Fedora 41. I'll open a dedicated bug report.
> 
> _Edit:_ Done: #103251.

Thank You, I have this change for now which should revert it back to the old behavior for arm `if env["platform"] in ["android", "ios", "linuxbsd", "macos"] and env["arch"] in ["arm32", "arm64", "x86_64"]:`  but i was wondering if `decompress/huf_decompress.c` will be ever used for `arm32` which is causing the linking issue.

**Comment by akien-mga** [comment]
@WhalesState That workaround might work, but you'll find out that the produced binary is actually for the x86_64 architecture. Cross-compilation on Linux with Clang is not properly supported yet.

**Pull request merged**
