### PR TITLE
Fix cyclic reference errors while reducing identifiers

### LINKED ISSUE #71230: [4.0 Beta 11 x64 Linux] - Parser Error: Could not resolve member "Icons": Cyclic reference. ?
### Godot version

Godot 4.0 Beta 11 x64 Linux Official

### System information

Linux Mint 21.1 Cinnamon 64Bit Linux OS

### Issue description

Hi,

On Godot 4.0 Beta 10 everything was OK.
On new Godot 4.0 Beta 11, our game does not run?

Getting strange errors like below:
```
for index in range(0, 4):
	InterfaceCore.Icons.IconAnimationTimer[index] = -1
# Parser Error: Could not resolve member "Icons": Cyclic reference.
```

Any ideas?

### Steps to reproduce

Reproducible when running game on Godot 4.0 Beta 11 x64 Linux version.

### Minimal reproduction project

https://github.com/BetaMaxHero/GDScript_Godot_4_T-Story

### PR DESCRIPTION
**Pull request by adamscott**
Fixes #71230

### CODE REVIEW

**Comment by adamscott** [comment]
@vnen @vonagam Don't ask my how or why, but it didn't work the last time around.

**Comment by anvilfolk** [comment]
As long as you can still open large projects using cyclic dependencies, this sounds like a perfect solution, right?

**Comment by vonagam** [comment]
It is because of change in Enums PR, there was a line in compiler, not connected to enums, which made compiler ignore reduced value of constant if they are meta type.

I think there are some gotchas about usage of that incomplete reduced value in other constants (arrays, dictionaries, callables). Need to check.

**Comment by anvilfolk** [comment]
Here's the line in question:
https://github.com/godotengine/godot/blob/60d031777b2a922cba03210181c9ba7ad3a6f3ab/modules/gdscript/gdscript_compiler.cpp#L216

So basically, if a thing is a metatype, it usually is a constant. If it's constant, we expect a reduced value. Right now that is being inefficient, because it really ought to check whether it's an enum so it can use the underlying constant dictionary.

But is there a way that we can also use some reduced value for class metatypes?

**Comment by vonagam** [comment]
Hm... Cannot reproduce an issue with usage of class inside other constants. Strange, I had same PR ready six days ago, but decided to not to publish - I thought I encountered some issue, but now I'm not sure, maybe I just imagined it. So, I guess, it is ok.

> not using the enum's underlying reduced value

No, as I said in the comment to that line of that PR, enum value gets used, the only inefficiency is that compiler needs to do lookup again to resolve which thing the identifier refers to. In my "PR" I had this line to avoid this small bother and to show that this line is specifically about classes:
```diff
- if (p_expression->is_constant && !p_expression->get_datatype().is_meta_type) {
+ if (p_expression->is_constant && !(p_expression->get_datatype().is_meta_type && p_expression->get_datatype().kind == GDScriptParser::DataType::CLASS)) {
```

**Comment by anvilfolk** [comment]
> No, as I said in the comment to that line of that PR, enum value gets used, the only inefficiency is that compiler needs to do lookup again to resolve which thing the identifier refers to. In my "PR" I had this line to avoid this small bother and to show that this line is specifically about classes:

Sorry, yeah, that's what I meant. It still works, it's just inefficient because it does the lookup again. You should create a PR adding that extra requirement :)

**Comment by adamscott** [comment]
> I thought I encountered some issue, but now I'm not sure, maybe I just imagined it. So, I guess, it is ok.

There was a lot of code change in the last days. I'm sure it's not just your imagination. I was the first surprised to see that my PR worked.

**Comment by vonagam** [comment]
It can go in this PR to show why it became possible, but if Adam does not want it - I can open such small PR.
Also next line - error message - should be updated, since it is just shallow script now, not full one.
Just as an example, I had it updated to:
```cpp
vformat(R"(Error while getting cache for script "%s".)", p_identifier_datatype.script_path)
```

**Comment by adamscott** [comment]
Updated the error message with your snippet, @vonagam.

**Comment by adamscott** [comment]
@vonagam I added the `if (p_expression->is_constant && !(p_expression->get_datatype().is_meta_type && p_expression->get_datatype().kind == GDScriptParser::DataType::CLASS)) {` line in `GDScriptCompiler::_parse_expression`.

I added you as a co-author too, as you contributed more lines than me in this PR. :P

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
