### PR TITLE
Translated_hi.po

### PR DESCRIPTION
**Pull request by Devashishsingh98**
I have translated some of the lines in the Hindi file section. :smile:

### CODE REVIEW

**Comment by volzhs** [comment]
use weblate for translating, not modify `.po` file directly.
https://hosted.weblate.org/projects/godot-engine/godot/

**Comment by Devashishsingh98** [comment]
> use weblate for translating, not modify `.po` file directly.
> https://hosted.weblate.org/projects/godot-engine/godot/

sir, Will it be counted as contribution in godot ?

**Comment by volzhs** [comment]
for hacktoberfest?

**Comment by Devashishsingh98** [comment]
> for hacktoberfest?

yes, for thehacktoberfest.

**Comment by volzhs** [comment]
i think not.
and translation has been synced from time to time with weblate by @akien-mga

**Comment by akien-mga** [comment]
>  thanks for the quick reply,so what are the things that i can do for contribution to any organisation. Since, I am new in this field. I don't know, What else i can do? I know beginner level of C programming language.

You can check issues labeled with "junior job": https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3A%22junior+job%22

**Pull request closed without merging**
