### PR TITLE
Change default curve range for particle angles to [-1, 1]

### LINKED ISSUE #91404: ParticleProcessMaterial: Default curve range for particle angles of -360 to 360 is not very useful
### Tested versions

v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

When you add a curve to the _Spawn_ > _Angle_ setting of a `ParticleProcessMaterial`, this is initialized with a range of -360 to to 360. Since the curve value is actually **multiplied** with the particle angle and not **replacing** it, I think this range does not make a lot of sense in most cases as it will just send all the particles heavily spinning if you multiply their angle with 360.  I think a default range of -1 to 1 would make more sense to me here.

https://github.com/godotengine/godot/assets/327257/54e8c7ec-fce1-4b4f-8656-7d6885a7f89a

### Steps to reproduce

- Create a `GPUParticles2D` Node
- Add a `ParticleProcessMaterial` to it.
- In the _Spawn_ > _Angle_ setting, add a curve.
- The curve has default values of -360 to 360.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ghost**
Change the default curve range for particle angles from [-360, 360] to [-1, 1].

Fixes #91404

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by aXu-AP** [comment]
Was there some problem with this pr? Is it salvageable?

**Comment by akien-mga** [comment]
The changes are correct, but the OP seems to have deleted their GitHub account... So yeah, someone else needs to redo it.

**Comment by aXu-AP** [comment]
I'm available, I'll do it

**Pull request closed without merging**
