### PR TITLE
Gizmo subscene visibility option

### PR DESCRIPTION
**Pull request by LRJiao**
Referencing [#8220](https://github.com/godotengine/godot-proposals/issues/8220), this pull will create an option in view for both 2D and 3D scenes that will hide all gizmos of subscenes in addition to any current gizmo options selected.

Before toggle:
image
After: (Cylinder shape added in base scene for reference)
image

### CODE REVIEW

**Comment by Chaosus** [comment]
Commits needs to be squashed (see https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

**Comment by LRJiao** [comment]
> Commits needs to be squashed (see https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html).

Squashed, thank you for letting me know.

**Comment by fire** [comment]
> Gizmo subscene visibility option

This option is good feature wise, but I don't think the toggle should be in the Gizmos list. This toggle is not the same as the other toggles

What about putting Gizmo subscene visibility option beside the top level gizmos entry?

**Comment by LRJiao** [comment]
> > Gizmo subscene visibility option
> 
> This option is good feature wise, but I don't think the toggle should be in the Gizmos list. This toggle is not the same as the other toggles
> 
> What about putting Gizmo subscene visibility option beside the top level gizmos entry? Also use a check box.

image
image

Adjusted to be a checkbox, similar to the 2D option.

**Comment by LRJiao** [comment]
Accidentally closed due to renaming, new [PR](https://github.com/godotengine/godot/pull/98370) is up

**Pull request closed without merging**
