### PR TITLE
Don't throw error on unrecognized #pragma for compatibility with glsl3.0

### LINKED ISSUE #97738: GDShader "invalid pragma directive" error on unrecognized pragma should be dropped
### Tested versions

- Reproducible in: v4.3.stable.flathub [77dcf97d8]

### System information

Godot v4.3.stable (77dcf97d8) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - Vulkan (Forward+) - integrated Intel(R) HD Graphics 5500 (BDW GT2) - Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 Threads)

### Issue description

The [GLSL ES 3.00 spec](https://registry.khronos.org/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf) says on page 15:
> `#pragma` allows implementation dependent compiler control. Tokens following `#pragma` are not subject to preprocessor macro expansion. **If an implementation does not recognize the tokens following `#pragma`, then it will ignore that pragma.**

I believe the whole point of `#pragma` is to allow forward-compatibility, by letting any unrecognized instructions be ignored. So I believe showing an error like "Invalid pragma directive" defeats the whole purpose, no? Invalid pragma lines should be ignored like how it is in the spec.

In fact, both C and GLSL preprocessors don't complain at all if you add a custom pragma.

### Steps to reproduce

```glsl
shader_type spatial;
#pragma some_custom "etc" 3.14 // unrecognized pragma should be ignored instead of raising error
```
```sh
cd /tmp
echo '#pragma some_custom "etc" 3.14' | tee a.c > a.frag
echo '=== GLSL ==='; glslang -E a.frag; echo '=== C ==='; gcc -E a.c
```

Of course, the error should still show for recognized pragma lines that are malformed:
```glsl
#pragma disable_preprocessor blah blah // should still raise the error
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by ghost**
Fixes: https://github.com/godotengine/godot/issues/97738

```glsl
// unrecognized pragma directive; skip with no errors
#pragma custom param1

// defined pragma directive; wrong arguments; error
#pragma disable_preprocessor blah blah

// defined pragma directive; correct arguments; no error
#pragma disable_preprocessor
```

About throwing warning instead of silent skip. I found only way to throw error from shader but not warning

### CODE REVIEW

**Comment by dustdfg** [comment]
TODO: Look at tests, add these cases to tests

**Review by Chaosus — APPROVED** [review]

**Comment by clayjohn** [comment]
I don't think this is a good idea. Our goal is explicitly _not_ to carry over the entire GLSL preprocessing stack and take on that complexity. 

The only pragma we support is `#pragma disable_preprocessor`, so we should error if anything else is used. In GLSL this doesn't provoke an error because vendor extensions can add pragmas and the code needs to be portable across vendors. That isn't the case for us, we fully control what pragmas a user can use, anything that we don't provide will never work. 

Just think about the simplest case here, let's suppose a user writes `#pragma disable_preprocesor`. It's an easy mistake to make, with this change, we would just silently ignore that error and the user will be left confused.

**Comment by geekley** [comment]
@clayjohn The whole point of a `#pragma` is to allow forward-compatibility. It's like this not just in GLSL, but in C too (see linked issue). If the language wants to force new syntax to be recognized or else raise an error, then it should not use pragmas, instead create a new keyword or directive. Pragmas let you introduce behavior that doesn't break in previous versions. In fact, `disable_preprocessor` should be a directive, not a pragma.

**Comment by geekley** [comment]
An example of a `#pragma` that could be introduced later without breaking a previous version is an equivalent of GDScript's UID comments (if that gets merged) for shader files:
```c
#pragma uid "uid://abcdef"
```
If this line has significance to the parser, it's better as a pragma instead of a "special" comment.

**Comment by dustdfg** [comment]
@clayjohn I agree with both points of view but in this case a question why pragma was chosen in first place? Just because it already was defined somewhere GLSL? Why not to use something different? I mean there is `shader_type <type>` which is not `pragma` and not preprocessor thing. It is a fully new thing of GD Shading Language. I mean you want to add something new. What will you consider adding something entirely new in terms of syntax like `shader_type` or somethng defined through `pragma`? It seems for me that you won't add anything to pragma anyway... Though as `pragma` is for preprocessor `disable_preprocessor`. It "should" be with `#`. So I agree with @geekley though not about concrete syntax of `#disable_preprocessor` but I agree with the idea in core

**Comment by clayjohn** [comment]
>  I agree with both points of view but in this case a question why pragma was chosen in first place? Just because it already was defined somewhere GLSL? Why not to use something different? 

I don't know why it was chosen, I'm assuming it was just to match the GLSL syntax. I also don't like it, but its too late to change it now.

**Comment by dustdfg** [comment]
Looks like won't be merged and I don't want to remember about it

**Comment by geekley** [comment]
> by this logic, #disable_preprocessor should have been introduced as a directive, not a pragma.

> I don't know why it was chosen, I'm assuming it was just to match the GLSL syntax. I also don't like it, but its too late to change it now.

To be clear, I wasn't suggesting it should change now. Is perfectly fine to have mandatory pragmas. GLSL has it too. And the new Godot's flavor of GLSL (as per proposal https://github.com/godotengine/godot-proposals/issues/11274) will have mandatory pragmas too under a reserved prefix.

But the main purpose of a pragma is forward-compatibility in syntax, and it can only be done properly by allowing optional directives. When languages don't have those and need forward-compatibility, they have to resort to awful solutions like adding significance to comments or dangling strings like `"use strict"` in JS.

**Comment by geekley** [comment]
> let's suppose a user writes `#pragma disable_preprocesor`. It's an easy mistake to make, with this change, we would just silently ignore that error and the user will be left confused.

@clayjohn This particular mistake is quite harmless IMO because if the user is doing it correctly (no other preprocessor directives), the behavior is the same with or without the pragma. If there is any other directive you may get unexpected behavior instead of an error, but it's extremely easy to see that you have a directive after that pragma on the same file (since not even `#include` is allowed, I believe). You can just CTRL+F `#`.

Also note that auto-completion already triggers when typing. But if you want to be extra careful to avoid confusion, you could still make the syntax-coloring mark recognized pragmas with e.g. a keyword color.

**Pull request closed without merging**
