### PR TITLE
[Windows] Remove meta_mem update on keyup/keydown.

### LINKED ISSUE #74957: Cannot use 'backspace' key and key combinations are not working after alt-tabbing
### Godot version

4.0.1.rc1

### System information

Windows 11

### Issue description

The backspace key is not functioning in the 'Create New Node' pop-up in Godot 4.0.1.rc1.
Noted also that the Ctrl+A is not functioning for adding new child nodes in the scene tree.

No errors were shown in the logs or console.

Edit: After restarting Godot Editor, the backspace key was working.  So there must be more steps to reproduce this issue.
The Ctrl+A was also working after restarting Godot Editor.

### Steps to reproduce

Edit: After restarting Godot Editor, the backspace key was working.  So there must be more steps to reproduce this issue.
The Ctrl+A was also working after restarting Godot Editor.

Right click in the scene tree to add a new node.  Ctrl+A does not seem to be working either, another bug report.
Click on "Add Child Node"
Expected: "Create New Node" pop-up is shown.
In my test the text was re-populated with 'sprite'.
Press 'backspace' on the keyboard to delete the text.
Expected: The text is edited showing 'sprit'.
Actual: The text will not 'backspace' remove from the end.

Workaround:
Click the 'x' at the right on the textbox to delete the text.
Now you can type text in the textbox, but still cannot use 'backspace' key.

### Minimal reproduction project

Edit: After restarting Godot Editor, the backspace key was working.  So there must be more steps to reproduce this issue.
The Ctrl+A was also working after restarting Godot Editor.

### LINKED ISSUE #75138: Keyboard language switch breaks script editor
### Godot version

4.0.1-RC2

### System information

Windows 10, with multiple keyboard layouts

### Issue description

Arrow keys, backspace, enter stop working if I switch language.

I have English, Estonian, Russian layouts. If I switch those in editor using WIN+Space shortcut only the letter keys work. CTRL, ALT, arrows and enter stop working.

### Steps to reproduce

Steps:
1. Open the editor script window
2. Type aa and erase them with backspace
3. Hit Win+Space
4. Type aa and erase them with backspace
Backspace fails to work until I restart the editor.

Notes: 
- There is a similar issue [mentioned for Ubuntu](https://github.com/godotengine/godot/issues/49771)
- I did not experience this in Godot 4.0.0

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/74957
Fixes https://github.com/godotengine/godot/issues/75138

### CODE REVIEW

**Comment by bruvzg** [comment]
> Does this also fix https://github.com/godotengine/godot/issues/75138?

Probably, but I can't reproduce it to check.

**Comment by AThousandShips** [comment]
Tested and confirmed that it solves it for me

**Comment by AThousandShips** [comment]
This should probably be considered for cherry picking, it has quite an impact in #75138 for people who use multiple layouts, granted just a minor inconvenience if you *know* how to make it go away, but a QOL issue still

(Also you've got a typo in fixes)

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.

**Comment by ShatReal** [comment]
Hi, just wondering if this will be merged into the 4.1.1 branch. Alt-tabbing stops an input that was held down before alt-tabbing from registering.

**Comment by akien-mga** [comment]
This was merged in `master` before the 4.1-stable release, so it's part of 4.1-stable, and thus of 4.1.1-stable already.

**Comment by ShatReal** [comment]
Oh. Well the issue this should solve is occurring for me. Unless it's a different issue?

**Comment by akien-mga** [comment]
It must be a different issue, please open a new bug report.

**Pull request merged**
