### PR TITLE
Added link for Default Shortcuts in Help menu

### PR DESCRIPTION
**Pull request by dreamsComeTrue**
That's one more approach to the original work of @zaksnet in PR  #39676

### CODE REVIEW

**Comment by pycbouh** [comment]
Perhaps version information should be fetched and put into the URL instead of `stable`?

**Comment by Calinou** [comment]
Indeed, as @pycbouh says, we should probably use the `major.minor` version number to determine the documentation URL. That said, we don't have a `4.0` branch on the documentation repository yet, so we'd have to use `latest` on versions higher than 3.2 right now.

**Comment by dreamsComeTrue** [comment]
Changed from `stable` to `latest`

**Comment by pycbouh** [comment]
Was there a problem with implementing the `major.minor` scheme though? `latest` is only useful for those who compile `master`, for stable versions it is preferable to refer to the documentation related to that version. Someone using 3.2 wouldn't get much help reading the `latest` shortcut list and can even be confused by it.

**Comment by dreamsComeTrue** [comment]
Ok, I'll amend that with git version when I get back to PC today. I wasn't just sure which path we should follow on this 👍

**Comment by akien-mga** [comment]
The problem with using `major.minor` is that it won't work for the `master` branch, as we don't branch off the docs to `4.0` until `4.0` is ready to be released as stable.

So you'd have to parse `VERSION_STATUS` to see if it's `"stable"` to decide if you should use `VERSION_MAJOR.VERSION_MINOR` or point to `latest`... it's a bit overkill IMO but if you folks think it's important, why not.

**Comment by pycbouh** [comment]
I agree, that there is no simple solution here and that proper support for documentation versions feels like an overkill, but I just don't see a point in linking docs for a wrong version. One can argue that there is little chance that there are going to be huge changes to that article, but that cannot be proved.

Honestly, the original PR didn't give any good reason for including this link in the first place. What use-case is solved here? Do we need it even?

PS. On the upside, any solution for version resolution between the engine and the docs can be used for any link to the online documentation within the editor, not just by this link.

**Comment by akien-mga** [comment]
My initial feeling is also that I'm not sure why this page in particular should be linked in the editor menu and not several others, which would make the menu bloated.

Default Shortcuts can be found directly by browsing the Editor Settings, so all the information is readily available.
The page in the docs is convenient as an online reference and for search engines, and to give some extra context, but I'm not sure it warrants being in the Help menu.

**Comment by aaronfranke** [comment]
@dreamsComeTrue Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch. While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

**Comment by pycbouh** [comment]
I don't think this is desired at all, as per discussion.

**Comment by KoBeWi** [comment]
The online key reference is a bit more readable, but it's not very useful for people that work offline. Also it's not something you need to check really often. Only when you are beginning using Godot.

That said, and given discussion above, this PR needs a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by pycbouh** [comment]
Given the discussion above, I don't think this should be merged. Thanks for the contribution nonetheless!

**Pull request closed without merging**
