### PR TITLE
Fix selecting recent node in CreateDialog

### LINKED ISSUE #24044: Selecting recent node during Node creation selects wrong node
**Godot version:**
3.1 alpha 2

**Issue description:**
Not sure how this happened, but when I select Node from recent nodes, it selects InterpolatedCamera. Happens also when I mess with history and reorder recent nodes.

**Steps to reproduce:**
https://gfycat.com/CalmInformalIndochinahogdeer

### PR DESCRIPTION
**Pull request by aole**
If the add_type function finds a type that exactly matches the search term, then that is the one that should be selected.

This is my first contribution. Please let me know if I missed something or the fix has unintended consequences.

Thanks!

63884486-44f16100-c9a4-11e9-9a85-6545c49dfbc7

_Bugsquad edit: Fix #24044_

### CODE REVIEW

**Comment by akien-mga** [comment]
Note for reviewers: the diff is easier to check with whitespace changes ignored: https://github.com/godotengine/godot/pull/31754/files?w=1

Changes look fine, but the commit log should be amended (with `git commit --amend`, then `git push --force`) to make it more explicit. For Godot commits, we want the first line/summary to be a short but explicit description of what the commit does, for example "Fix selecting recent node in CreateDialog". Then you can have the "Fixes #31754" in the body of the commit message.

See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by aole** [comment]
@akien-mga thanks for the review. Please let me know if this looks good.

**Review by akien-mga — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks and congrats for your first merged PR :)

**Comment by aole** [comment]
Wohoo, my first merge!!!

**Pull request merged**
