### PR TITLE
Fixed GDScript crashed when two consecutive unary operators are analyzed/(script is saved).

### LINKED ISSUE #70094: Editor crashes when right click on plus '+' only line in function definition
### Godot version

4.0.dev (1c5cfc4)

### System information

Windows 11 21H2

### Issue description

Editor crashes when right click or typing underscore '_' on indented plus '+' line in func definition.
Shortest code which reproduce the crash is as follows:
```
extends Node3D

func _ready():
	+
```
Editor crashes when right clicking on caret as following screenshot.
image

Also, editor crashes when appending underscore '_' to end of line 5.

This crash doesn't occur on Godot 4 beta 8.

### Steps to reproduce

1. Import minimal reproduction project.
2. Open script example.gd
3. Right click at end of line 5.
4. Editor freezes and crash (reproduced).

### Minimal reproduction project

[editor_crash_script_plus_underscore.zip](https://github.com/godotengine/godot/files/10233657/editor_crash_script_plus_underscore.zip)

### PR DESCRIPTION
**Pull request by stmSi**
Fixed: #70094 
(my first ever PR in OSS)

### CODE REVIEW

**Comment by akien-mga** [comment]
The fix in this PR looks good :+1: 

There's just a small issue with the Git identity you used to author this commit:
```
From: Your Name <you@example.com>
```

This isn't a valid email, and is not attributed to your @stmSi account. You would need to configure your Git identity: https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git
See also https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address regarding the email address, in case you want to use an anonymous one that would still identity your GitHub account.

One the Git identity is configured (globally, or just for your Godot repo), you can amend this PR's commit and reset the author info with `git commit --amend --reset-author`, and then update this PR with `git push --force`.

**Comment by stmSi** [comment]
oh

**Comment by stmSi** [comment]
done

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
