### PR TITLE
Inf and NaN support added to GDScript

### PR DESCRIPTION
**Pull request by SaracenOne**
Exposes Inf and NaN so they can be used in scripting.

### CODE REVIEW

**Comment by Geequlim** [comment]
I prefer they could be named with same format with constants like `PI`.

**Comment by RebelliousX** [comment]
Also, would you add max integer constant too? It can be used as one of the arguments for tween iirc, which is cumbersome to copy the value from the tooltip and put it in the script while typing the function signature.

**Comment by SaracenOne** [comment]
@Geequlim Do you mean having them uppercase? Yeah, they can be uppercase sure.
@RebelliousX Sure, that could be added too. The main reason I wanted access to infinity is for raycasts, but it's clear there's a couple of useful math constants which are missing.

**Comment by akien-mga** [comment]
NaN was added to Math as part of this change: https://github.com/godotengine/godot/pull/7815/commits/b696beea65bbffd31edac169ccf9708f46ab9652#diff-993a9b7e9377b9826f6cfcb6400dedcdR42

Could you check this PR and maybe rebase to ensure we're not defining it twice?

**Comment by SaracenOne** [comment]
@akien-mga Should be resolved now.

**Pull request merged**
