### PR TITLE
Add 'is_point_in_circle()' to Geometry class, and general file cleanup

### PR DESCRIPTION
**Pull request by YeldhamDev**
This adds the `is_point_in_circle()` method to the `Geometry` class, and cleans up several files (removal of dead code and proper comment formatting).

Now, why add a method for something so easy to calculate, you may ask. Simply put, it's just a small QOL addition. While the way to calculate its very small:

```
return circle_position.distance_to(point) < radius;
```

It can quickly add up if needed multiple times. And if you need to use it in multiple scripts, it can be bothersome having multiple user-made methods to condense the calculation in each file (unless you make it in a global script, which is generally something you want to avoid).

### CODE REVIEW

**Comment by avencherus** [comment]
Must say, always felt this was missing.  😄 

`return point.x <= circle_position.x + radius and point.x >= circle_position.x - radius and point.y <= circle_position.y + radius and point.y >= circle_position.y - radius`

I think this is a point in a rectangle.

When I give up looking for the `point_in_circle()`, I generally write something like:
`if((a - b).length_squared() <= radius * radius):`

**Comment by akien-mga** [comment]
When adding features + doing a cleanup of a whole class, I'd prefer two separate commits (can still be in the same PR) for readability. It's hard to spot what the actual logic changes are in a commit with so many comment changes.

**Comment by volzhs** [comment]
I usually check this by 

```gdscript
if a_pos.distance_to(circle_pos) < radius:
    # it is inside
```

**Comment by YeldhamDev** [comment]
@akien-mga Noted.

@avencherus Never have been good with vector math. Fixed.

@volzhs Yep, this is a shorter and more efficient (and actually correct) way to calculate it. Replaced my wrong math with it. I still think the addition is welcomed, as at a glance is easier to realize what it's doing.

**Comment by Xrayez** [comment]
It would be wrong if I wouldn't mention about ellipse, perhaps it could be generalized to `is_point_in_ellipse`, with two [focal points](https://en.wikipedia.org/wiki/Ellipse#/media/File:Ellipse-var.svg) being at exact position = `is_point_in_circle`.

**Comment by avencherus** [comment]
@volzhs This does make me wonder what is expected with "inside", do most consider the edge inside or outside the circle?

**Comment by YeldhamDev** [comment]
@avencherus I think most people expect the edge to count.

**Comment by MunWolf** [comment]
`if a_pos.distance_to_squared(circle_pos) <= radius * radius:`
is the more efficient way to do this check, though the implementation of the is_point_in_circle function seems to be missing from the PR?

**Comment by YeldhamDev** [comment]
@MunWolf The diff that contains it is not rendered because of its size, click in "Load diff".

**Comment by MunWolf** [comment]
Ahh yeah, didn't notice that :D
But my comment still stands.

**Comment by YeldhamDev** [comment]
How is `point.distance_to_squared(circle_pos) <= radius * radius` faster than `circle_pos.distance_to(point) <= circle_radius`, since the former has two calculations instead of one?

**Comment by akien-mga** [comment]
> How is `point.distance_to_squared(circle_pos) <= radius * radius` faster than `circle_pos.distance_to(point) <= circle_radius`, since the former has two calculations instead of one?

Square root is more expensive than multiplication.

**Comment by MunWolf** [comment]
@YeldhamDev You are confusing function calls with calculations :D
`circle_pos.distance_to(point) <= circle_radius`
is equal to `sqrt((circle_pos.x - point.x)^2 + (circle_pos.y - point.y)^2) <= circle_radius`
while `point.distance_to_squared(circle_pos) <= radius * radius`
is equal to `(circle_pos.x - point.x)^2 + (circle_pos.y - point.y)^2 <= circle_radius * circle_radius`
same number of calculations, but multiplication is way easier then a square root.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
