### PR TITLE
Added loop_begin and loop_end to OggVorbisStream

### LINKED ISSUE #11468: Small "pop" noise when looping .ogg file
**Operating system or device, Godot version**
Linux Mint 18.2 Cinnamon x64, Godot master d7468fe

**Issue description:**
Upon looping, a .ogg stream will produce a small "pop" noise, which doesn't seem to be preventable by the user. A way to solve this problem (according to @reduz) is to add in a small crossfade at the end of a loop, removing the pop and making loops seamless.

### PR DESCRIPTION
**Pull request by mrcdk**
It adds `loop_begin` and renames `loop_offset` to `loop_end`

It also fixes https://github.com/godotengine/godot/issues/11468

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks fine to me, but I'd like @reduz to check it.

**Comment by reduz** [comment]
Sorry, I reverted this. Most users don't need to set a loop end position and just want the whole thing to loop from beginning to end. 

I would change this to either:
1) Have a loop mode enum: (Disabled, All, Region)
2) Assume loop end as 0 means end of file (though this may be a bit confusing).

**Comment by reduz** [comment]
I also think loop in these files needs a XFade setting to avoid pops, just setting custom loop/end will not do.

**Comment by mrcdk** [comment]
Loop end as 0 is already assumed to be the end of the file in this PR.

Also, there is no need to fade anything to avoid pops but to fill the correct position in the buffer when mixing it which is what this PR also does.

**Comment by mrcdk** [comment]
Just to reiterate, the loop_end has nothing to do with this issue https://github.com/godotengine/godot/issues/11468 it just that this PR also fixes that issue

**Comment by reduz** [comment]
Ah, it did not seem to me like that 0 was considered as loop end when looking at the PR. Apologies.
In any case, I understand that setting the right loop point will not cause pops, but how are users supposed to find that at the frame level? This is why I suggested adding optional XFade, as most will not be able (or hav any idea) how to do it without complex audio editing software.

**Comment by mrcdk** [comment]
`loop_end` will be considered the end of the track when loading the stream data (so, when `loop_end` is 0 in the import settings). If you later set the `loop_end` to 0 by code then it will be 0. I could modify that behavior so when setting `loop_end` to 0 by code it would set it to the end of the track but at that point is it an engine issue or an user issue?

The loop points are set in seconds as floats, not frames. For example, the Web Audio API uses also seconds as floats for its loop values.

Audacity also uses seconds + milliseconds by default for its selection points so I think that, if an audio editing software uses it, it should be enough for a game engine. You can go back and forth from samples to seconds in Audacity if you need extreme precision.

We could always expose the loop points as frames (it's already being used internally anyway)

**Comment by piratesephiroth** [comment]
uh... this looked pretty nice however I see it hasn't come back.

It's necessary if the track has an introduction that we obviously don't want to be included in the loop.

**Comment by xKamuna** [comment]
loop_end would be super nice, is there any other way to achieve it while keeping the audio file intact?  Sometimes I want to play the end, but during loop, I don't want to play the end, and also want to start from a developer-defined point.  loop_offset only has half of this functionality.

**Pull request merged**
