### PR TITLE
Right-clicking will not close popup in windows

### LINKED ISSUE #59181: Popup in 2D editor teleports for one frame
### Godot version

fb28025

### System information

W10

### Issue description

Poopoop
When clicking outside menu, it changes position to cursor and then gets closed immediately. Happens also on events that should open it again, e.g. right-clicking in another place will not prevent closing the popup.

It might have similar cause to #58726

### Steps to reproduce

1. Right-click in 2D editor
2. Right-click somewhere else

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by vitika9**
Fix #59181

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
This PR makes it impossible to close popup menus with a right-click. That's not really a proper fix 🙃

**Comment by Vitika9** [comment]
@KoBeWi Popup on right clicking first updates it's location then due to the code under the switch case it gets closed. As this closing thing is right only for PopupMenu not for Popup is there any way that we can differentiate between PopupMenu and Popup in MouseProc function so that we can skip closing popup on right click?
And for the Popup with list tool, we can check for CanvasItemEditor's tool property.

**Comment by KoBeWi** [comment]
But right-clicking should close any popup, including menus. That's how it works in every app.
The issue is that events are handled in incorrect order. The popup should close first and then reopen, right now it's the opposite. Also this PR is Windows-only, it's possible that same issue exists on Linux/macOS.

**Comment by Vitika9** [comment]
> But right-clicking should close any popup, including menus. That's how it works in every app. The issue is that events are handled in incorrect order. The popup should close first and then reopen, right now it's the opposite. Also this PR is Windows-only, it's possible that same issue exists on Linux/macOS.

Ok, I will look into this

**Comment by KoBeWi** [comment]
Keep in mind that this is not really a simple issue if it's that low-level.

**Comment by derammo** [comment]
@KoBeWi I am working in a related area at the moment.  Is this PR staying in the master?  We just won't listen to right mouse click any more except in non-client areas?

**Comment by KoBeWi** [comment]
I'd say that we should revert this, as it only causes more issues.

**Comment by derammo** [comment]
I am new here and don't know whom to ask.   I would like to take a stab at finding the root cause of this, but not if the path forward is to just disable right clicks.

**Comment by KoBeWi** [comment]
Try `#platforms` channel on Godot chat.

**Pull request merged**
