### PR TITLE
Fixes cases where the runtime ResourceLoader cannot load gltf images.

### LINKED ISSUE #69090: GLTFDocument cannot load texture from gltf file.
### Godot version

4.0 Beta5

### System information

macOS v13.0

### Issue description

GLTFDocument cannot load texture from gltf file. Error message is
```
E 0:01:02:0964   _load: No loader found for resource: /Users/allen/Downloads/bevy/assets/models/FlightHelmet/FlightHelmet_Materials_RubberWoodMat_Normal.png.
  <C++ Error>    Method/function failed. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:222 @ _load()
```

### Steps to reproduce

```
var file = "...some.gltf"
var gltf_doc = GLTFDocument.new()
var gltf_state = GLTFState.new()
var err = gltf_doc.append_from_file(file, gltf_state)
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/69090

### CODE REVIEW

**Comment by fire** [comment]
Off-thread discussion was made with @akien-mga about how this code works but this is pretty hacky. We do desire a better file import api.

**Review by lyuma — APPROVED** [review]
glTF permits texture URI references to non-data URIs without a mimetype, and the mime type is inferred from the file extension.
This code implements that behavior for the case where ResourceLoader.load returns null
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#file-extensions-and-media-types

**Review by akien-mga — APPROVED** [review]
Seems fine. Would be good to do the change suggested by Lyuma.

**Comment by fire** [comment]
Updated.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
