### PR TITLE
Add ability to set "keep screen on" for android & iOS. fixes #2428

### LINKED ISSUE #2428: Some api to be able to go to sleep for mobile device.
Godot forces always on for mobile device.
But some api to be able to go to sleep for mobile device would be great.

### PR DESCRIPTION
**Pull request by volzhs**
Can change "Set Keep Screen On" at Project settings.

2 methods are added to `OS`.

```
OS::set_keep_screen_on(bool)
bool OS::is_keep_screen_on()
```

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks! Could you maybe merge the first three commits into one using ```git rebase -i HEAD~5``` and prefixing 2nd and 3rd commits (94c0715 and 3d91aa7) with "fixup" instead of "pick"? They seem to be quick fixes to the first commit.

**Comment by volzhs** [comment]
I tried to do it.
This makes more commits. it is fine?

**Comment by akien-mga** [comment]
Thanks. It seems to have worked to some extent but it did not remove the old commits, that's weird.

I'll see if I find a procedure to fix it.

**Comment by akien-mga** [comment]
Ok I managed to fix it locally with:
```
git rebase -i HEAD~4   // it will show way more than 4 commits, that's weird, but git is some voodoo magic sometimes
// remove the last five lines which surprisingly correspond to your _old_ commits
// save
```

So you should see at first
```
pick de18945 Add ability to set "keep screen on" for android
pick 77de9b4 Add ability to set "keep screen on" for iOS
pick a52540b add documentation for OS::set_keep_screen_on
pick 8fb4864 Add ability to set "keep screen on" for android
pick 94c0715 change way to set initial value of "keep screen on"
pick 3d91aa7 set initial value properly for "keep screen on"
pick d2726a2 Add ability to set "keep screen on" for iOS
pick d8015ac add documentation for OS::set_keep_screen_on
```
and then keep:
```
pick de18945 Add ability to set "keep screen on" for android
pick 77de9b4 Add ability to set "keep screen on" for iOS
pick a52540b add documentation for OS::set_keep_screen_on
```

Afterwards check ```git log``` to make sure it worked okay, and force push again.

**Comment by volzhs** [comment]
I made another PR for it. so, closed this.

**Comment by akien-mga** [comment]
Thanks, sorry for the nit-picking :)

**Pull request closed without merging**
