### PR TITLE
Fixed editor settings disappearing.

### LINKED ISSUE #12463: Unchanged EditorSettings properties appear as revertable, and disappear when reverted (regression from 5676c42ae)
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Mageia 6 x86_64, current master (87dbb716)

**Issue description:**
When browsing the Editor Settings, many properties appear as revertable, even though I know that I never modified them. Reverting them either does nothing or reverts to Null, and in some cases the property disappears from the list with a corresponding console warning, e.g. `EditorSettings::_get - Warning, not found: filesystem/file_server/password`.

spectacle m19962

It's obviously a regression, but I can't tell from when for now. Bisect welcome :)

**Steps to reproduce:**
- Delete/rename your `editor_settings-3.tres` for a clean testing environment
- Start Godot once to get the file generated
- Restart Godot (easier to reproduce this way in my experience, though maybe not mandatory)
- Check the Editor Settings, e.g. in the `filesystem/file_server` category: both the `port` and `password` properties should be shown as changed. If you revert `password`, its values goes from 0 to Null and it then disappears.

### PR DESCRIPTION
**Pull request by djrm**
Some items that are no longer defined may disappear, but thats expected i guess.

closes #12463

### CODE REVIEW

**Comment by akien-mga** [comment]
It doesn't fix the bug, and the console is spammed with errors:
```
$ ERROR: set_initial_value: Condition ' !props.has(p_name) ' is true.
   At: editor/editor_settings.cpp:1216.
ERROR: set_initial_value: Condition ' !props.has(p_name) ' is true.
   At: editor/editor_settings.cpp:1216.
```

**Comment by akien-mga** [comment]
Well that's only for the first run without a pre-existing settings file. Subsequent runs don't show the errors, on the other hand the bug is still there for various settings:

spectacle m30118
(revertable editor language is fine, it's the only setting I changed)
spectacle q30118
spectacle s30118
spectacle r30118
spectacle v30118
spectacle n30118
(and also `mono/builds/build_tool` but I've reverted it already in this example so the setting disappeared, I can't show it).

**Comment by djrm** [comment]
@akien-mga most of the settings you mentioned are changed by the system, even if you dont notice, for example, the window bounds (thats the way it remembers them), and also the editor colors (thats caused by the adaptive theme, it has to be that way), the other settings im not sure, they might not be properly initialized, i will take a look, also i think i will make the unused settings hidden, so if you reactivate them, they still have their last value.

**Comment by djrm** [comment]
updated, the only missing one was mono/editor, the rest of the settings are changed during excecution, like the text editor colors or the subwindow size and position

**Pull request merged**
