### PR TITLE
Add ability to set "keep screen on" for android & iOS. fixes #2428

### LINKED ISSUE #2428: Some api to be able to go to sleep for mobile device.
Godot forces always on for mobile device.
But some api to be able to go to sleep for mobile device would be great.

### PR DESCRIPTION
**Pull request by volzhs**
Can change "Set Keep Screen On" at Project settings.

2 methods are added to `OS`.

```
OS::set_keep_screen_on(bool)
bool OS::is_keep_screen_on()
```

### CODE REVIEW

**Comment by punto-** [comment]
Looks good, but you need to use tabs to indent the ios code (android looks
fine), and I'd probably rename the property to display/keep_screen_on

**Comment by volzhs** [comment]
I will change and test it on phone.
I will try to make clean commits but if I fail, I will create another PR...

**Comment by punto-** [comment]
thanks!

**Comment by volzhs** [comment]
I created another PR for this. #3360

**Pull request closed without merging**
