### PR TITLE
Fix color-picker sliders

### PR DESCRIPTION
**Pull request by capnm**
I guess these hacks are relics from HSV mode.

image

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by MarianoGnu** [comment]
Raw mode was suposed work that way to be able to make colors with componnts greather than 1 and use them on Multiply operations
CC @reduz he explained it to me earlier

**Comment by akien-mga** [comment]
Ah right, so indeed only the alpha channel should be limited. So should it be changed back to how it was, with just the addition of the step of `1` for the non-raw mode?

**Comment by MarianoGnu** [comment]
the step of 0.1 is un purpose too, otherwhise you can only move from 1 on 1 making it less usefull for color operations

**Comment by akien-mga** [comment]
Thanks, I'll revert the change for now then. We can continue discussing if there's a need to actually change some of those lines or not.

**Comment by capnm** [comment]
Ah, I see. But it looks still like very broken design for me ;) The arrows doesn't
work reliably in the RGBA mode, the slides for that kind of raw mode are more than useless.
Why not just use line_edit to entry 4 arbitrary float values?

**Comment by MarianoGnu** [comment]
Nothing prevents you from using the spinboxes next to the sliders.
Maybe they could be replaced with the new spinslider, would give a lot more space for decimal digits

**Comment by capnm** [comment]
@MarianoGnu The spin boxes (and mouse scroll-wheel) doesn't work in the non-raw mode in the new inspector. Try it yourself. That was the reason I made this PR.

**Comment by MarianoGnu** [comment]
Sliders are kind of useless, since a range from 0 to 100 is very high, but as i said, this is not meant to pick a Color for drawing con a canvas, it's meant for color Operations (personally think 100 is too much, but dont have the experience to come to a conclusion)
Maybe step could be changed to logaritmic so it's easier to pick small values?

**Comment by capnm** [comment]
Sorry, I do not understand what you mean by "color operations", isn't it obvious that you can calculate with any float rgba values?

I think there is no reason to limit the raw input. I just changed the raw input UI into the 4 new user-friendly **float** input fields and used this (successfully) as input for further calculations in a shader.

**Comment by capnm** [comment]
Nothing you said so far implies that the float range **must be limited** to 0-10 or 0-100. Why shouldn't it be possible to use a regular float input and e.g. hand over a Color(-0.42, -0.42, -0.42, -1) to the shader and then do not multiply but **add** it to some other color?

**Pull request merged**
