### PR TITLE
Replace NULL with nullptr

### PR DESCRIPTION
**Pull request by lupoDharkael**
Replace NULL with nullptr for better type safety.
I've used clang-tidy's [modernize-use-nullptr](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html) but it didn't replaced all the NULL occurrences.
I had to do manual replace with the following patterns:
```
return NULL;
= NULL
NULL,
, NULL)
(NULL)
)NULL
: NULL;
NULL :
NULL }
	NULL
```
It needed some manual fixes afterwards.

### CODE REVIEW

**Comment by lupoDharkael** [comment]
CI is complaining a lot, I'll try to fix the problems tomorrow.

**Comment by lupoDharkael** [comment]
The style problems should be almost fixed but there are problems with some Windows API pointer types like `LONG_PTR`. I don't have a Windows machine right now to fix the compilation. Should I revert the changes in `platform/windows/*` and do the changes to those files in other PR?

**Comment by akien-mga** [comment]
If you can rebase (might as well restart from current master and apply the clang-tidy tool again) I can have a look at the Windows build issue.

**Comment by lupoDharkael** [comment]
I'm doing it right now!

**Comment by lupoDharkael** [comment]
@akien-mga rebased and Travis CI is now passing, the windows build needs to be fixed.

**Comment by lupoDharkael** [comment]
I've tried to crosscompile Godot for Windows from Linux, I think I've fixed the build problems. I'm pushing the changes as soon as the mingw build finishes.

**Comment by akien-mga** [comment]
Sorry I added a merge conflict with #37504, could you rebase again? I'll then review and merge this in priority.

**Comment by akien-mga** [comment]
I found a few more occurrences of `NULL` that could be converted to `nullptr`. I'm not sure about the Windows changes though as I couldn't get it to build locally with MinGW, but that seems unrelated to this PR.

https://paste.centos.org/view/53ee7776

I suggest that we merge this before making more changes though. There's also the Obj-C++ code in `.mm` files where `NULL` can likely be converted to `nullptr` too.

**Comment by akien-mga** [comment]
And once all uses of `NULL` are removed from our own code, we could try something extreme like this to prevent adding new code that doesn't use `nullptr` (outside thirdparty libs):
```diff
diff --git a/core/typedefs.h b/core/typedefs.h
index bafbffcded..0a6df4d8ee 100644
--- a/core/typedefs.h
+++ b/core/typedefs.h
@@ -44,6 +44,11 @@
 #include "core/error_list.h"
 #include "core/int_types.h"
 
+// Enforce use of nullptr in our code.
+#ifdef NULL
+#undef NULL
+#endif
+
 // Turn argument to string constant:
 // https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html#Stringizing
 #ifndef _STR
```

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
