### PR TITLE
Add get_camera_rid method to Camera

### LINKED ISSUE #29028: No way of getting the RID of a camera
**Godot version:**
3.1.1

**Issue description:**
Some of the methods in VisualServer require an RID of a camera, but there is no `get_rid` in Camera, like how it exists in most other classes that are used by VisualServer.

### PR DESCRIPTION
**Pull request by Jummit**
fixes #29028

### CODE REVIEW

**Review by bojidar-bg — APPROVED** [review]
Maybe add a link to RID as well?

**Comment by Jummit** [comment]
I copied the description from the viewport class. If I add one in Camera, then there should be one in Viewport aswell.

**Comment by bojidar-bg** [comment]
Ah, actually the type information can be accessed via the return type, so it is fine. Nevermind then :smiley:

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
