### PR TITLE
clang-format config changes to discuss

### PR DESCRIPTION
**Pull request by akien-mga**
I tried two changes to our `clang-format` config which make it stricter, but should also enforce a style that we are more or less using already, with exceptions.

- `AllowShortCaseLabelsOnASingleLine`: If true, short case labels will be contracted to a single line.
- `AllowShortIfStatementsOnASingleLine`: If true, `if (a) return;` can be put on a single line.

*Edit:* To be clear, the proposed changes is to **disable** both of those, so disallow short case labels and if statements on a single line.

See https://clang.llvm.org/docs/ClangFormatStyleOptions.html

I only open this PR for discussion, I'm not necessary convinced that we should do this change, but it's worth discussing.

### CODE REVIEW

**Comment by aaronfranke** [comment]
> `AllowShortCaseLabelsOnASingleLine`

What about switch statements with fallthrough cases? Would this happen:

```
case Thing1:
case Thing2: do_something(); break;
```

**Comment by fire** [comment]
I noticed sometimes 

```
if (a) return;
```
and

```
if (a)
  return;
```
is used.

I would prefer 
```
if (a) {
  return;
}
```

However, using braces is a massive style change. 

Using braces is better because the braces allow future modification without changing the style.

Thoughts?

**Comment by aaronfranke** [comment]
For simple statements, I think it looks fine to have:

    if (a) return;

But I would prefer to explicitly include braces:

```
if (a) {
    return;
}
```

Over not doing so:
```
if (a)
    return;
```

**Comment by lawnjelly** [comment]
Isn't the usual reason given to prefer if statements over more than one line ease of debugging?
```
* if (a) return;
```

```
if (a)
    * return;
```
Where * represents a breakpoint. With the latter you can break on the condition.

Personally I'm fine with the non-braced version, as it makes things less verbose so you can fit more on screen (and less of those clang errors :smile_cat: ). But is a matter of taste.

**Comment by akien-mga** [comment]
I'll close this for now and come back to it after 3.2, these changes should not be done before merging the `vulkan` branch into `master` anyway.

**Comment by akien-mga** [comment]
We actually agreed to apply both those changes at the Godot Sprint with several core contributors, so I'll make another PR once `vulkan` has been merged with `master`.

**Pull request closed without merging**
