### PR TITLE
Add icons for editor settings tabs

### PR DESCRIPTION
**Pull request by ghost**
This morning I tried finding the editor shortcuts tab and actually overlooked it:

before

How about adding icons here?

after

### CODE REVIEW

**Comment by reduz** [comment]
Please lets not get into the adding icons everywhere trend, I tried to avoid this since forever

**Comment by groud** [comment]
I prefer without too.

**Comment by poke1024** [comment]
I have to admit it's actually cleaner without icons.

**Comment by leoddd** [comment]
Cleaner and simpler to maintain, since people won't have to go looking for/making a fitting icon every time they add a new tab anywhere!

**Comment by poke1024** [comment]
OK, I agree, closing this :-)

**Comment by akien-mga** [comment]
The tab theme could be improved though, I agree that it's hard to notice the non active tabs currently.

**Comment by djrm** [comment]
maybe we could avoid dimming the text or dim less

**Pull request closed without merging**
