### PR TITLE
Fix error when dragging anchors with parent's size == 0

### LINKED ISSUE #41212: Can't move anchor: "editor/plugins/canvas_item_editor_plugin.cpp:847 - Condition "parent_rect.size.x == 0" is true. Returned: Vector2()"
**Godot version:**
v3.2.2.stable.official

**OS/device including version:**
Windows 10 v1909

**Issue description:**
When trying to move a PanelContainer's anchor using the UI element this is logged in the output:
` editor/plugins/canvas_item_editor_plugin.cpp:847 - Condition "parent_rect.size.x == 0" is true. Returned: Vector2()`

**Minimal reproduction project:**
[repro.zip](https://github.com/godotengine/godot/files/5066526/repro.zip)

### PR DESCRIPTION
**Pull request by groud**
Fixes #41212

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by ysfdc** [comment]
I am seeing this error in version 4.1.1 when trying to drag anchors on a panel.
scene/gui/control.cpp:856 - Condition "parent_rect_size.x == 0.0" is true.

I can change through transform without getting this error.

**Comment by YuriSizov** [comment]
@ysfdc This PR is 3 years old and for an entirely different version of the engine. Please open a new bug report and describe how you're reproducing the issue.

**Pull request merged**
