### PR TITLE
[3.2] Set 2D weight equal to mass x gravity.

### PR DESCRIPTION
**Pull request by madmiraal**
3.2 version of #40796.

### CODE REVIEW

**Comment by akien-mga** [comment]
It breaks compat, so I'm not sure it's a good change for `3.2`.

**Comment by madmiraal** [comment]
I don't think it breaks compat, because it's just a value that's displayed based on mass. It's not used in any calculations other than when it's changed in the editor to change the mass. Existing projects will just display the new value without the scaling factor.

**Comment by akien-mga** [comment]
But you can set mass via `weight`/`set_weight` in scripts or in the inspector, which will use the changed method to calculate the new mass.

So if you had scripts that assign `weight`, the compat will be broken due to the removal of the *10 factor.

**Comment by madmiraal** [comment]
True. I'll close it then.

**Pull request closed without merging**
