### PR TITLE
Add note for Windows on function `move_to_foreground()`

### PR DESCRIPTION
**Pull request by eskandrej**

### CODE REVIEW

**Comment by Calinou** [comment]
If `move_to_foreground()` doesn't work on Windows, this sounds like a bug.

**Comment by bruvzg** [comment]
> If move_to_foreground() doesn't work on Windows, this sounds like a bug.

On Windows, there are a lot of restriction on for moving the window to the foreground, so it's not a bug.

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow#remarks

**Comment by eskandrej** [comment]
There is a workaround. If you set Window.always_on_top = true and after Window.always_on_top = false it will bring window to front but it will not be focused. I thought about adding tip but it's hacky.

**Review by Mickeon — CHANGES_REQUESTED** [review]
`move_to_foreground` is deprecated in favour of `grab_focus` now. So, if this note has to exist it would have to be defined there.

**Pull request closed without merging**
