### PR TITLE
Fix LOD sort order; checks in add_surface; and document all parameters of `ArrayMesh::add_surface_from_arrays`

### PR DESCRIPTION
**Pull request by RedworkDE**
`ArrayMesh::add_surface_from_arrays` had a few undocumented parameters, whose usage was not exactly clear from just type and name, so document them.

Additionally:
- Rename the `compress_flags` parameter to `flags`, because the compress flags are just a subset of that flags that are passed and that is what the parameter is called in C++ and the corresponding `ImporterMesh` method.
- Clarify the description of some `ArrayType` values.
- Expose the `ArrayFormat::ARRAY_FLAG_USES_EMPTY_VERTEX_ARRAY` flag, because the is an error message telling users to pass it.
- Copied a check about the number of blend shapes from `ImporterMesh` because the mesh will cause errors when trying to use it if this check fails.
- Added a check about the maximum number of surfaces to ArrayMesh, because otherwise the surfaces in the ArrayMesh and in RenderingServer could diverge and cause lots of errors down the line.
- Sort the LOD levels, or LOD levels could get missed if they were not added to the dictionary in order.

To consider (in maybe a different PR?):
- Unexpose `ArrayFormat` members: `ARRAY_FORMAT_CUSTOM_BASE`, `ARRAY_FORMAT_CUSTOM_BITS`, `ARRAY_FORMAT_CUSTOM_MASK`, and `ARRAY_COMPRESS_FLAGS_BASE`; they only exist to compute other members and there is not really a reason to use them and they just confuse by polluting the enum.
- Remove the `MAX_MESH_SURFACES` limit, at least on desktop, nothing breaks when increasing it and if the intention was to use 8 bit integers for it somewhere it is one too large anyways.

### CODE REVIEW

**Comment by fire** [comment]
Is the lod sorting accurate? There are a few lod bugs

**Comment by fire** [comment]
The uv maak is needed for 8uv support calculations

**Comment by fire** [comment]
Ok with unifying the flags for clarity and accuracy

**Comment by RedworkDE** [comment]
> Is the lod sorting accurate? There are a few lod bugs on issues

Yes, they need to be added in order of increasing distance (the key in that dictionary) and that sort ensures that.

Without that, this test script would create a mesh with only one lod, because the 0.02 key is added first; and with the oder in the dictionary doesn't matter and both lods are always effective.

<details>
<summary>Test Script</summary>

Add to a MeshInstance3D with a AnimationPlayer sibling

```gdscript
@tool

extends MeshInstance3D

# Called when the node enters the scene tree for the first time.
func _ready():
	var allIdx = PackedInt32Array([0, 1, 2, 3, 4, 5])

	var idxs = [0, 1, 2]
	var idx2 = [3, 4, 5]

	var arr_mesh = ArrayMesh.new()
	arr_mesh.add_blend_shape("s")
	arr_mesh.add_blend_shape("u")
	
	for i in range(0, 10):
		var vertices = PackedVector3Array()
		vertices.push_back(Vector3(i + 0, 1, 0))
		vertices.push_back(Vector3(i + 1, 0, 0))
		vertices.push_back(Vector3(i + 0, -1, 0))
		vertices.push_back(Vector3(i + 0, 1, 0))
		vertices.push_back(Vector3(i + 0, -1, 0))
		vertices.push_back(Vector3(i + -1, 0, 0))

		# Initialize the ArrayMesh.
		var arrays = []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = vertices
		arrays[Mesh.ARRAY_INDEX] = allIdx

		# Create the Mesh.
		arr_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays, [
			[vertices, null, null, null, null, null, null, null, null, null, null, null, null],
			[vertices, null, null, null, null, null, null, null, null, null, null, null, null],
		], {
			0.02: idx2,
			0.01: idxs,
		})
	mesh = arr_mesh
	
	var anim = Animation.new()
	
	var track = anim.add_track(Animation.TYPE_BLEND_SHAPE)
	anim.blend_shape_track_insert_key(track, 0, 0)
	anim.blend_shape_track_insert_key(track, 1, 1)
	anim.track_set_path(track, "MeshInstance3D:s")
	
	var animLib = AnimationLibrary.new()
	animLib.add_animation("blend", anim);
	$"../AnimationPlayer".remove_animation_library(&"test")
	$"../AnimationPlayer".add_animation_library(&"test", animLib)
```

</details>

---

I am not sure I understand what you mean with your other comments, can you elaborate a bit?

**Comment by fire** [comment]
ARRAY_FORMAT_CUSTOM_BASE I believe this is used for 8 uv in shader code. This allows creation of meshes for shaders storing data in the custom attributes of a mesh.

Rename the compress_flags parameter to flags: YES!

**Comment by fire** [comment]
@clayjohn I don't know if you prefer this, but in the past separating the various debatable portions of the pr makes it easier to review.

I recommend separate prs:

1. Rename the compress_flags parameter to flags
2. Clarify the description of some ArrayType values.
3. Expose the ArrayFormat::ARRAY_FLAG_USES_EMPTY_VERTEX_ARRAY flag
4. Copied a check about the number of blend shapes from ImporterMesh
5. Added a check about the maximum number of surfaces to ArrayMesh
6. Sort the LOD levels

I can check the sort lod levels.

**Review by lyuma — APPROVED** [review]
Hi!
Looks good overall.

I like the flags being named `compress_flags` because it hints that it contains only a subset of the full flags, most of which are computed on the rendering backend.

Please change the commit message to indicate that this affects sort order of LODs and adding checks: If a commit affects how code runs, a commit message must say something other than just "Document".

**Comment by RedworkDE** [comment]
Updated the commit message, left the parameter name change for now because as I see it the compress flags are the subset of flags that use `ARRAY_COMPRESS_FLAGS_BASE` to compute their value, of which there are 3: 2D_VERTICES, is set automatically, DYNAMIC_UPDATE only works with one renderer, leaving about 1.5 compress flags and 5 other flags that should be passed to that parameter: USES_EMPTY_VERTEX_ARRAY could arguably also be considered a compress flag, but the custom format flags are almost certainly not compress flags.

If this interpretation is not correct or someone has a better idea for the parameter name, I am not particularly attached to the name change; but in that case should the parameter in ImporterMesh be changed to match instead?

**Pull request merged**
