### PR TITLE
Support for binary literals

### LINKED ISSUE #25755: GDScript binary literals
Godot 3.1b3

I was doing some experiments in a test project involving binary masks, and I found GDScript does not have a binary literal format. It does have decimals (`12345`), it has hexadecimals (`0xfa57f00d`) but no binary: `0b00100110`. Could this be added in the language in the future? I use hex in the meantime but straight binary is easier for my head to wrap around due to the way I choose bit positions.

### PR DESCRIPTION
**Pull request by JellyWX**
~(Almost)~ Resolves #25755

Adds binary literals in the form of `0bxxxx`, e.g `0b01110` => 14
These are useful for things like bitmasking.
MSB is not treated as negative- representation is unsigned.

Issues:
~- No highlighting for binary literals within the script editor~

### CODE REVIEW

**Comment by vnen** [comment]
Looks okay to me but you should try to change `gdscript_highlighter.cpp` to add the highlighting for the binary notation.

**Comment by JellyWX** [comment]
Done, highlights binary literals identically to hex.

A potential consideration is fractions- I've set this to *not* permit a binary point within a literal, however I understand that GDscript does allow hex points e.g `0xFF.12`.

Should binary points be allowed? I doubt anyone would reasonably want to use a binary point

**Comment by JellyWX** [comment]
Actually, from just testing, placing a hex point turns the hex value to just be 0. I can change this to be treated as an error (not permit a `.` in a hex literal), unless someone thinks that hexadecimals should allow reals along with integers

**Comment by akien-mga** [comment]
Could you squash all those commits together, and make the resulting commit log more descriptive? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) and [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#contributing-pull-requests).

**Comment by JellyWX** [comment]
the answer to that seems to be no... i'll try to copy all the changes to another branch and recommit. Will I need to open a new PR once that's done?

**Comment by akien-mga** [comment]
You can update this PR from any branch by force pushing from the local branch to the remote one used by this PR. E.g. if you have a new `binary-literals` branch and your fork is `origin`, you can do:
```
git push --force origin binary-literals:master
```
to overwrite the `master` branch of your `origin` remote.

**Comment by JellyWX** [comment]
I've messed this PR up beyond repair. Is it possible to reconfigure the base repo, otherwise I'll need to recreate because I ended up deleting the repo from GitHub and re-forking it to get a clean copy.

Changes, within a single commit, are at https://github.com/JellyWX/godot/tree/binary-literals

**Comment by akien-mga** [comment]
If the original fork was deleted, you'll have to open a new PR indeed.

**Pull request closed without merging**
