### PR TITLE
[2.1] Editor Debugger: Changed the Color of Child Process Connected

### PR DESCRIPTION
**Pull request by ISylvox**
Cherry-picked https://github.com/godotengine/godot/pull/10191 for Godot 2.1.x

### CODE REVIEW

**Comment by akien-mga** [comment]
This also changed colors of actual errors:
spectacle w11044

I'll revert for now as the added friendliness for the "Child Process Connected" is not worth having all errors show up as friendly :)

**Comment by ISylvox** [comment]
Oh, my bad... Child Process Connected is not alone... It has friends. 😎

**Comment by RandomShaper** [comment]
Oh, this breaks my heart!

Friendly errors were a good feature to make Godot more appealing to new users. XD

Seriously now, I hope this can be done properly since I loved the greenish-blueish message.

**Comment by akien-mga** [comment]
To do it properly, I guess it should distinguish between actual errors, warnings and info messages.

**Pull request merged**
