### PR TITLE
Fix errors when re-importing 3D asset files

### LINKED ISSUE #87451: Reimporting GLTF causes "Attempt to disconnect a nonexistent connection" in inherited scene, duplicate meshes and crash
### Tested versions

Tested in v4.2.1 (latest stable version)

### System information

Godot v4.2.1 - Windows 10, Forward+/Vulkan GTX 1060 6GB

### Issue description

Reimporting a gltf file (either by opening the .gltf in Godot and clicking "reimport" or by dragging the gltf and accompanying .bin file into godots ressource directory letting godot reimport it) causes a
`Attempt to disconnect a nonexistent connection from 'test:<Node3D#1825814147267>'. Signal: 'replacing_by', callable: 'EditorNode::set_edited_scene'.`
error to be printed in the output window. The asset also doesn't get reimported.

reimport

Also, if we create another scene and place the inherited scene in there and try to reimport the asset, it fails and creates a duplicate instance of the reimported asset at the center of the scene.

"level.tscn" which has "test.tscn" placed in the scene with a translation offset:
before

After reimporting the gltf:
after

Note also how the Scene view on the left side on the screen doesn't match what we actually see in the 3D preview. (it shows the nodes from the inherited scene)
This in turn can also cause Godot to crash shortly after. (somewhat random.)

I attached the reproduction sample/project as a zip.

### Steps to reproduce

1) start godot
2) export a mesh as a GLTF file from blender (can be the default cube which is already placed in the scene).
3) drag the .gltf and .bin file into the res:// directory of godot
4) right click on the gltf > new inherited scene
5) save the opened scene in the res:// directory of godot
6) open the gltf in godot and click "Reimport"

### Minimal reproduction project (MRP)

[ReimportTest.zip](https://github.com/godotengine/godot/files/14002853/ReimportTest.zip)

### PR DESCRIPTION
**Pull request by Rindbee**
Some 3D asset files (gltf/glb) are treated as scenes and may cause some errors when importing.

~~Manually updating the cache in advance resulted in some bugs when `EditorNode::set_edited_scene()` was automatically called for the second update.~~

When working through different scene tabs, we need to temporarily add the scene root to the SceneTree to ensure that `editor_selection->add_node()` can work smoothly. This avoids the error message: `ERROR: Condition
"!p_node->is_inside_tree()" is true.`

This also ensures that no other scenes are accidentally added to the SceneTree causing the wrong display. When there is an inherited scene tab open and it is not the current tab, the new root node is accidentally added as a child node of `scene_root` during replacement.

Instantiate the scene early so caches in SceneState that are cleared due to loading are rebuilt early. This avoids numerous error messages: `This operation requires the node cache to have been built.`

Supersedes #89428.

Fixes #87451.

### CODE REVIEW

**Review by lyuma — APPROVED** [review]
I'll admit I don't understand this code very well, but currently I get randomly duplicated nodes and this crash constantly and it's driving me nuts.

If this PR has even a remote chance of solving that, I'm in. It can't possibly make things worse than they are now.

**Comment by KoBeWi** [comment]
The cube is still duplicated 🤔

https://github.com/godotengine/godot/assets/2223172/981f9e85-c10f-46b0-a73c-83c974dacd57

It's gone when you switch scene tab.

**Comment by Rindbee** [comment]
Sorry for the late reply.

It reloads scene tabs one by one, so it's better to switch scene tabs first and then process them later.

In addition, it does not seem to save scene modifications when necessary, so re-importing resources may cause the scene to lose unsaved modifications.

**Comment by KoBeWi** [comment]
Something is still wrong:

https://github.com/godotengine/godot/assets/2223172/5571f4bc-ca17-4361-b655-140d88021e7f

The level scene gets replaced by test (only visually). It doesn't always happen though. I also had a bug where test.tscn had 2 cubes.

**Comment by Rindbee** [comment]
Two scenes appear to be open in the 3D screen at the same time. It seems that `get_tree()->set_edited_scene_root()` is not switched correctly.

**Comment by KoBeWi** [comment]
Now it seems to work correctly, but there is an error spam 🙃

https://github.com/godotengine/godot/assets/2223172/422436ac-5424-4105-83d7-32ff199fef15

Also the current changes make updating scenes after reimport much more expensive. Though maybe it doesn't matter unless someone opens, like, 50 scenes with instances to update.

**Comment by Rindbee** [comment]
https://github.com/godotengine/godot/blob/214968243c442c0fdcbdfef23943c1547aeafdbc/editor/editor_node.cpp#L5658

Reloading a `PackedScene` clears the cache, which is not rebuilt until `instantiate()` is called.

**Comment by Rindbee** [comment]
If the scene has unsaved modifications before reimporting, these modifications will not be saved after reimporting, but the unsaved mark (`*`) will disappear.

Should these modifications be saved before reimporting?

**Comment by KoBeWi** [comment]
IIRC reloading a scene tries to re-apply unsaved changes, so nothing should be lost. Though maybe it's different for regular instances vs imported scenes.

**Comment by Rindbee** [comment]
But it doesn't prompt to save when closing the tab.

https://github.com/godotengine/godot/assets/30386067/8209650a-ea4a-4fad-a4e2-c2be739e1bb5

**Comment by KoBeWi** [comment]
That's because the scene does not appear unsaved. It should retain the unsaved status after soft-reload.

**Comment by KoBeWi** [comment]
Needs rebase due to conflicts >_>

**Comment by Rindbee** [comment]
The conflict has been resolved.

The latest commit in master no longer restores the changes caused by the import, which should refresh the 3D Screen to show the latest changes, but it seems that only the inherited scene will be refreshed, not other scenes.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Bonkahe** [comment]
I apologize for adding a comment here, not sure if I should have just posted it in the issue (bit new to issues and all of this honestly), but here goes.
I believe this commit is causing an issue with restarting scenes when reimporting resources, resulting in enter tree being called multiple times, you can see my issue here: [https://github.com/godotengine/godot/issues/92623](https://github.com/godotengine/godot/issues/92623)

Is this intended or is this a bug?
It's a bit of a blocker to me.

**Pull request merged**
