### PR TITLE
Fix bug #1165 filtering when downscaling sprites

### PR DESCRIPTION
**Pull request by jotson**
Here's the forum thread and demo project that demonstrates the problem: http://www.godotengine.org/forum/viewtopic.php?f=11&t=1331#p6410

### CODE REVIEW

**Comment by reduz** [comment]
I see the problem, though will fix it in a different way, minification will only be set to GL_NEAREST if both filter and mipmaps are disabled. If mipmaps are enabled, I assume the effect desired is more akin to Minecraft.

**Comment by jotson** [comment]
Thanks. I'll be happy as long as there's some way I can get GL_NEAREST always. :+1:

**Comment by reduz** [comment]
this should be fixed at this point, please let me know it works for you, so i can close this

**Comment by jotson** [comment]
Yep, this is fixed. Thanks!

**Pull request closed without merging**
