### PR TITLE
More tweaks to the 2d polygon editor

### PR DESCRIPTION
**Pull request by ghost**
Actually 3 changes that I think might be quite useful:

(1) A new option "Delete Points With Lmb" that allows point to be deleted via a simple short click on them. This is off by default, as mouse users will probably usually use the right mouse button to delete points. However, this is very useful for touch screens: you can now just tap on a point and thereby delete it using this option; only a very short tap without move produces a delete.

del-lmb

(2) A new lock option at the right hand of the editor toolbar, only visible while in edit point mode.:

lock-icon

Is enabled, locks the edges (or the number of points) for mouse editing; this means that if locked, you can no longer add or delete points with the "click on edge" or the new "click on point" functions. There might situations/phases/users where you really want to stick with the polygon point number as it is and only edit the positions (and might actually get annoyed if you add or delete points). This is what this lock is useful for, I believe: select it, and you only edit the positions. The lock setting is persistent across polygons meaning, you can adjust it to your workflow and edit a whole bunch of polys with the same lock setting.

(3) Fixes a small line overdraw glitch when drawing, i.e. this is fixed:

glitch

### CODE REVIEW

**Comment by akien-mga** [comment]
cc @groud

**Comment by groud** [comment]
1) Not really convinced by this one, Godot is not meant to be used with touch screens, and that would probably never be the case. For me this option will probably never be used, thus it bloats the settings more than it brings value.

2) I think this is only for a corner-case situation, and also confusing as is (as it looks like the other lock, but I guess the icon should be changed)

3) No problem with that :)

Keep in mind that we have to keep the interface as simple as possible, it's better to find ways to reduce the number of buttons to the minimum. To me, the editor would be better with only two modes:
- A "Select mode", to move points around, select several points, delete them with "Del", add a point when you double click on an edge and remove a point when you double click on it. 
- An "Edit mode" to add with single left-click and remove the last one created with single right-click.

**Comment by poke1024** [comment]
Hi @groud, my thoughts on this:

First, I think that considering touchscreen support for this editor is valid. Use Godot on something on a Surface Pro or a Wacom Cintiq with a stylus and you're on a stylus/touchscreen device - for level building and editing this scenario is common and not esoteric.

Especially on such an input device, a one-click interface to add and delete points feels very natural to me. The single-click deletion proposed in this PR is a logical extension of the single-click adding of points already in place - together, it's just the fastest and snappiest way of adding, deleting, and moving points that to me feels intuitive, efficient and simple: it saves additional clicks and key strokes (i.e. delete), as it's only one click each time for each operation. I know this is subjective, but using a stylus, this just feels right.

Now, I agree that the solution you propose using double clicks is a very good general solution as it covers cases where one does not want to add and delete points by accident and where the user's focus is to just move points. I want that mode as well. I just believe that one wants to switch between this mode and the first one. That is the idea of this lock button, only that it's not a lock button at all.

Maybe we should re-establish the mode you suggest as a default (thereby disabling the current one-click-on-edge-to-add-point in top of tree), and then add a setting "One Click Editing" that enables the current one-click-on-edge-to-add-point and the new one-click-to-delete proposed in this PR. For me, it would even be better if "One Click Editing" would be a button on the toolbar and not hidden in the settings, as I can imagine switching between one and the other, but I see that this causes problems (e.g. when users accidentally click there and do not understand the effect). But to me, it boils down to having a setting that defines if you need 1 click or 2 clicks to add or delete points. I'll think about this some more, maybe there can be a button with a good, intuitive icon to represent exactly this, but I'm not sure and I see the risk of overloading/confusing the interface an unintuitive button.

But, anyway, if we had such a setting "one-click-editing", the delete button in the toolbar is obsolete, as one-click-editing offers exactly that delete function.

By the way, I like the idea of selecting several points.

**Comment by groud** [comment]
To be honest, I think too few people use touchscreens for them to be considered at this point. We may add support for that later, like by emulating the right click or something like that, activated with a "touchscreen mode" setting (this mode could activate this "one click editing" too) . But for now the priority is to be user friendly to normal computers.

I personally think this one click editing is not that useful, having to draw a lot of points in a polygon is a really rare use case. It would make sense in a drawing software like Inkscape, as it would speed up the workflow. But in our case people will generally rather be precice that fast. 

Anyway more opinions on that are welcome :)

**Comment by poke1024** [comment]
This discussion is getting pretty confused. I'm going to split this PR into three separate PRs which should then get discussed separately:

(1) Add click-to-delete as logical completion of current top-of-tree click-to-add (thereby removing delete button)
(2) Focus on the question if there should be an option/decision to disable/remove the current click-to-add functionality completely (and how this option should look like)
(3) Fix the drawing glitch

**Comment by poke1024** [comment]
Abandoned for the two follow-up PRs.

**Pull request closed without merging**
