### PR TITLE
Don't allow adding Objects to the project settings

### LINKED ISSUE #33667: Adding ProjectSettings value with TYPE_OBJECT make Godot Project unrecognizable
**Godot version:**
Godot 3.2 beta 1

**OS/device including version:**
Windows 10

**Issue description:**
I added to ProjectSettings value with type TYPE_OBJECT and give it a Resource value. When Godot Restarted, the Project is gone from the Project Manager.

**Steps to reproduce:**
o Open Project I uploaded below
o Open and Run ps_adder.gd, this will create 2 new value in Project Setting
o Open Project Setting and notice the value we created before is there
   image
o Now close Godot.
o Reopen Godot, notice that this Project is Gone.
o Try reopen using import and select the project's project.godot file
o The project will not open instead The Project Manager Window opened again.
o Now locate the project.godot file and erase our 2 ProjectSetting value that we added before.
   image
o Reopen Godot. Voila! Now the Project is reappear

**Minimal reproduction project:**
[ObjectPS.zip](https://github.com/godotengine/godot/files/3855164/ObjectPS.zip)

### PR DESCRIPTION
**Pull request by Calinou**
Godot doesn't support serializing objects.

**Note:** I haven't tested this since I can't open the Project Settings in the current `master` branch due to a DisplayServer bug (even in single window mode).

This closes #33667.

### CODE REVIEW

**Comment by akien-mga** [comment]
This fails building and should be rebased (and tested).

**Comment by KiritoAM** [comment]
@Calinou I've tested this on latest and all seems good. Regarding #33667, I can't repro this issue on latest - I can select the Object type from the dropdown and try to create a setting, but it fails to create it (and add it to project.godot upon saving the settings). Not sure exactly where it fails to add the setting; it makes it through ProjectSettingsEditor::_add_setting, but the Object value created in the function is nil. Would be nice to get your change in.

**Comment by Calinou** [comment]
Rebased and tested, it works fine.

**Comment by KiritoAM** [comment]
The IOS build failure doesn't look like it has anything to do with your change. Guessing the procedure in this situation is to just restart the build and hope the build machine doesn't trip over again?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
