### PR TITLE
Fix SSR not working properly in stereo

### LINKED ISSUE #86987: SSR is broken in stereo rendering
### Tested versions

- Reproducible in 4.3-dev 84e205b5a17bfe7ace96b78c410ec10aa52241d2
- Reproducible in 4.2-stable
- Works in 4.1.3-stable

### System information

Windows 10 - 4.3-dev 84e205b5a17bfe7ace96b78c410ec10aa52241d2 - Vulkan Forward+

### Issue description

Applying SSR in stereoscopic rendering messes up, look like an issue with either the left and right eye images getting mixed up or eye offset not being applied correctly. Was able to verify that the shader code looks to still include the right parts. Need to investigate further.

image

Notice the misalignment on the right image in the screenshot. To paraphrase Captain Picard, "There is ONE sphere!"

### Steps to reproduce

Make sure you have some shiny materials and enable SSR

### Minimal reproduction project (MRP)

[TestStereoSSR.zip](https://github.com/godotengine/godot/files/13870699/TestStereoSSR.zip)

(note, no VR hardware is needed to run the MRP).

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Fix typo that caused #86987

*Bugsquad edit:*
- Fixes #86987

### CODE REVIEW

**Comment by akien-mga** [comment]
Remember to use closing keywords in the OP :)
Fixed it already.

**Comment by akien-mga** [comment]
There are a lot more cases still using `MULTIVIEW`, are the rest intended?
```
$ rg "if.* MULTIVIEW"
servers/rendering/renderer_rd/shaders/effects/copy_to_fb.glsl
7:#ifdef MULTIVIEW
25:#ifdef MULTIVIEW
44:#ifdef MULTIVIEW
65:#ifdef MULTIVIEW
94:#ifdef MULTIVIEW
100:#ifdef MULTIVIEW
111:#endif /* MULTIVIEW */
132:#ifdef MULTIVIEW
168:#ifdef MULTIVIEW
180:#endif /* MULTIVIEW */

servers/rendering/renderer_rd/shaders/effects/tonemap.glsl
7:#ifdef MULTIVIEW
27:#ifdef MULTIVIEW
47:#ifdef MULTIVIEW
128:#ifdef MULTIVIEW
189:#ifdef MULTIVIEW
276:#ifdef MULTIVIEW
367:#ifdef MULTIVIEW
402:#ifdef MULTIVIEW

servers/rendering/renderer_rd/shaders/effects/vrs.glsl
7:#ifdef MULTIVIEW
16:#ifdef MULTIVIEW
26:#ifdef MULTIVIEW
37:#ifdef MULTIVIEW
46:#ifdef MULTIVIEW
52:#endif /* MULTIVIEW */
57:#ifdef MULTIVIEW
63:#ifdef MULTIVIEW
78:#endif /* MULTIVIEW */

servers/rendering/renderer_rd/shaders/effects/specular_merge.glsl
33:#ifdef MULTIVIEW
```

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
> MULTIVIEW

Yep, those all seem to use `#define MULTIVIEW`

**Comment by akien-mga** [comment]
Shouldn't we unify those so they all use the same name?

**Comment by clayjohn** [comment]
> Shouldn't we unify those so they all use the same name?

We could, there would be no harm in doing it

**Comment by dsnopek** [comment]
The compatibility renderer consistently uses `USE_MULTIVIEW`. It'd be nice to unify all the shader code on the same define.

**Comment by BastiaanOlij** [comment]
> Remember to use closing keywords in the OP :) Fixed it already.

Thanks, I always forget the syntax, so I just add it manually on the right side.

**Comment by BastiaanOlij** [comment]
And yes, I agree that we should unify these, thats probably how the bug got introduced. But I suggest we do that in a separate PR as a mistake will break stuff.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
