### PR TITLE
fix(editor): Create new icon for TileMap Rectangle

### PR DESCRIPTION
**Pull request by erictuvesson**
Rationale: https://github.com/godotengine/godot/pull/42972#issuecomment-714346313

### CODE REVIEW

**Comment by groud** [comment]
Could you squash the two commits together? So that the PR only has one?

**Comment by erictuvesson** [comment]
@groud I squashed them

**Comment by groud** [comment]
> @groud I squashed them

You likely did a mistake somewhere then, it looks like your PR includes changes from another change. You might have to amend your commit and eventually rebase it on master. (or start eventually a new branch if you don't want to bother).

**Comment by erictuvesson** [comment]
Hmm, I see that it is screwed up now. Must have been because it was a merge commit.... I should just do rebase in the future...

**Pull request closed without merging**
