### PR TITLE
Switch out 65535 with UINT16_MAX in a few places for clarity

### PR DESCRIPTION
**Pull request by souplamp**
Changing out various instances of `65535` with `UINT16_MAX` where applicable.
This is strictly a codestyle change, and not at all a logical/functional change.

Draft until I've caught more cases; let me know if I'm missing any, or if I mistakenly changed anything!

### CODE REVIEW

**Comment by adamscott** [comment]
I think you need to update the documentation for your change to [`GLOBAL_DEF("rendering/limits/global_shader_variables/buffer_size", UINT16_MAX);`](https://github.com/godotengine/godot/pull/68984/files#diff-dc12bc981c6b42b8579800ffb22b4f82e4f1153acb40db6dfc98a6655bcad0b8R3002)

```
Running --doctool to see if this changes the public API without updating the documentation.
If a diff is shown, it means that your code/doc changes are incomplete and you should update the class reference with --doctool.
```

https://github.com/godotengine/godot/actions/runs/3519271115/jobs/5899046914#step:12

**Comment by akien-mga** [comment]
The commit message needs to be made clearer, as it doesn't say anything about the functional change. `65536` and `UINT16_MAX` are not the same numbers, so it's not just a codestyle change, this changes the logic.

And the scope of such change would be much larger than what this commit message suggests, as you're only changing a handful of places (so it sounds more like a targeted bugfix for #68965 than a codebase wide change as the commit implies).

```
$ rg 65536 -g'!thirdparty' | wc -l
76
$ rg 65535 -g'!thirdparty' | wc -l
458
```

**Comment by souplamp** [comment]
> The commit message needs to be made clearer, as it doesn't say anything about the functional change. `65536` and `UINT16_MAX` are not the same numbers, so it's not just a codestyle change, this changes the logic.

Thank you for pointing that out; I completely overlooked that. I might have to rethink the scope as I didn't intend to change any logic, but make it clearer that `65535` has a purpose (as the largest value of uint16_t).

> And the scope of such change would be much larger than what this commit message suggests, as you're only changing a handful of places (so it sounds more like a targeted bugfix for #68965 than a codebase wide change as the commit implies).

According to https://github.com/godotengine/godot/pull/68965#issuecomment-1323174502, the original issue cannot use UINT16_MAX elegantly, so #68997 proposes using (1 << 16) which makes more sense in that context.

I'll see if I can pick a smaller scope and make relevant changes, but if anyone wants to do this sooner, feel free to supersede this!

**Comment by souplamp** [comment]
Had some difficulty finding examples that weren't context dependent (and as akien mentioned, there is a LOT of them). I'll just close this for now.

**Pull request closed without merging**
