### PR TITLE
Add support for `inf` and `nan` values to `JSON::stringify` and `JSON::parse_string`

### LINKED ISSUE #89777: JSON.stringify (and JSON.print in 3.x) produces invalid JSON for INF/NaN floats
### Tested versions

Godot Engine v4.2.2.rc1.official.c7fb0645a

Also seen in an otherwise-unspecified 3.5 build by someone I know

### System information

Windows 10, amd rx 480 gpu

### Issue description

The `JSON.stringify` function (`JSON.print` in 3.x) produces illegal JSON if the given data contains INF or NaN floats.

JSON numbers must be finite real numbers, not arbitrary floating point numbers. This means that the JSON stringifier can produce text that the JSON parser cannot parse.

firefox_2024-03-22_06-12-16

The JSON stringifier should either produce an error, or use best-approximation values (e.g. `DBL_MAX` or `+1e9999` or similar for INF, `0.0` or `null` for NaN, or strings saying "INF/-INF/NaN") when fed numbers that can't be stored as finite real numbers.

### Steps to reproduce

Run the following code in the _ready() function of a new scene in the editor and hit the "run current scene" button:

```gdscript
    prints("json: ", JSON.stringify([1.0/0.0]))
    prints("json: ", JSON.stringify([sqrt(-1.0)]))
```

Observe this output in the debug console output:

```
json:  [inf]
json:  [nan]
```

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by FireCatMagic**
- Fixes https://github.com/godotengine/godot/issues/89777

This is my first time ever contributing to Godot, I'm sorry if I did anything wrong.

This PR adds an optional extra parameter to `JSON::stringify`  called `allow_nonfinite`, defaulting to `false`

Also adding support for the parsing of the following keywords in `JSON::parse_string`:
- NaN
- Infinity
- -Infinity
- inf
- -inf

In `JSON::stringify`, regarding the new `allow_nonfinite` parameter:
When set to true, the following will occur:
- NAN values become the keyword `NaN`
- INF values become the keyword `Infinity`
- -INF values become the keyword `-Infinity`

This is based on a somewhat common nonstandard extension that is compatible with, at the minimum, Python's own JSON functions and a few other places. (See here https://evanhahn.com/pythons-nonstandard-json-encoding/)
The rationale of these keywords is to not be arbitrary, and instead the commonly supported.

The previous behavior of `JSON::stringify` with these values was to just directly place the keywords `inf`, `-inf`, and `nan` into the JSON, which would break when attempting to decode. 
The default value of `false` removes this behavior in this PR to still allow standard-compliant JSON. This PR fixes the previous default behavior of decoding breaking entirely when these values were used. It'll also allow the loading of the keywords `inf`, `-inf`, and `nan` which previously would not parse correctly.

The new behavior of `JSON::stringify` with `allow_nonfinite` set to `false` is to replace INF, -INF, and NAN values with:
- INF becomes `1e9999`
- -INF becomes `-1e9999`
- NAN becomes `null`
(the exponent values become their respective INF counterparts when parsed, it just isn't very explicit looking at it)
These are all compliant to the JSON standard.

ALSO: while testing this I found an issue of full_precision not being included recursively inside the contained arrays or dictionaries. This fixes that, it was necessary for this PR since the new parameter also must be included recursively.

### CODE REVIEW

**Comment by fire** [comment]
Did not review the code, but the proposal make sense as a way to avoid encoding invalid json.

**Comment by FireCatMagic** [comment]
why did it fail just the one check, how do I fix this?

**Comment by fire** [comment]
The error messages might help.

```
 ERROR: EditorSettings not instantiated yet.
   at: _EDITOR_DEF (editor/editor_settings.cpp:1403)
diff --git a/doc/classes/JSON.xml b/doc/classes/JSON.xml
index fe5fdfa..b7dda92 100644
--- a/doc/classes/JSON.xml
+++ b/doc/classes/JSON.xml
@@ -89,6 +89,7 @@
 			<param index="1" name="indent" type="String" default="&quot;&quot;" />
 			<param index="2" name="sort_keys" type="bool" default="true" />
 			<param index="3" name="full_precision" type="bool" default="false" />
+			<param index="4" name="allow_nonfinite" type="bool" default="false" />
 			<description>
 				Converts a [Variant] var to JSON text and returns the result. Useful for serializing data to store or send over the network.
 				[b]Note:[/b] The JSON specification does not define integer or float types, but only a [i]number[/i] type. Therefore, converting a Variant to JSON text will convert all numerical values to [float] types.
```

**Comment by FireCatMagic** [comment]
> The error messages might help.
> 
> ```
>  ERROR: EditorSettings not instantiated yet.
>    at: _EDITOR_DEF (editor/editor_settings.cpp:1403)
> diff --git a/doc/classes/JSON.xml b/doc/classes/JSON.xml
> index fe5fdfa..b7dda92 100644
> --- a/doc/classes/JSON.xml
> +++ b/doc/classes/JSON.xml
> @@ -89,6 +89,7 @@
>  			<param index="1" name="indent" type="String" default="&quot;&quot;" />
>  			<param index="2" name="sort_keys" type="bool" default="true" />
>  			<param index="3" name="full_precision" type="bool" default="false" />
> +			<param index="4" name="allow_nonfinite" type="bool" default="false" />
>  			<description>
>  				Converts a [Variant] var to JSON text and returns the result. Useful for serializing data to store or send over the network.
>  				[b]Note:[/b] The JSON specification does not define integer or float types, but only a [i]number[/i] type. Therefore, converting a Variant to JSON text will convert all numerical values to [float] types.
> ```

I've never messed with the docs before, I don't really understand what this error means

**Comment by AThousandShips** [comment]
It means you need to add that, it's a git diff, the plus sign means to add

You should generate the documentation yourself, see [here](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html#updating-class-reference-when-working-on-the-engine)

**Comment by FireCatMagic** [comment]
Was trying to rename my fork branch but it seems I can't if i want it to be connected to this pr, sorry about all that.

**Comment by Bromeon** [comment]
Thanks a lot for your contribution! 🙂 


> In `JSON::stringify`, regarding the new `allow_nonfinite` parameter: When set to true, the following will occur:
> 
>   * NAN values become the keyword `NaN`
>   * INF values become the keyword `Infinity`
>   * -INF values become the keyword `-Infinity`
>
>
> This is based on a somewhat common nonstandard extension that is compatible with, at the minimum, Python's own JSON functions and a few other places. (See here https://evanhahn.com/pythons-nonstandard-json-encoding/)
> The rationale of these keywords is to not be arbitrary, and instead the commonly supported.

The problem is still that it's non-standard, and calling it "JSON" is misleading. It's not JSON, but a custom protocol that has JSON as a subset.

While such extensions address the problem of having a serialization format that Godot can save and read again, they simultaneously cause interop problems for every non-Godot JSON deserializer, e.g. webservers, tools like `jq`, and JSON libraries in almost all programming languages. 

I don't think we are doing users a favor by locking them into a format that can only be understood by Godot and Python, especially not under the cover of the `JSON` class. It's not obvious for people unfamiliar with the protocol that these extensions are unsupported in the majority of software.


---

Maybe taking a step back, it would be good to know which problem we are exactly solving. Could you elaborate in which context you needed this?

Related, do we really want to encourage NaN (which is often the result of logic errors) to creep into serialization formats? Can we not expect users to handle these values explicitly and define a domain-specific value for them? I don't think the engine should make such a choice, precisely because there's no standard way of representing them in JSON and different applications may have different preferences.

**Review by Bromeon — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution! 🙂 


> In `JSON::stringify`, regarding the new `allow_nonfinite` parameter: When set to true, the following will occur:
> 
>   * NAN values become the keyword `NaN`
>   * INF values become the keyword `Infinity`
>   * -INF values become the keyword `-Infinity`
>
>
> This is based on a somewhat common nonstandard extension that is compatible with, at the minimum, Python's own JSON functions and a few other places. (See here https://evanhahn.com/pythons-nonstandard-json-encoding/)
> The rationale of these keywords is to not be arbitrary, and instead the commonly supported.

The problem is still that it's non-standard, and calling it "JSON" is misleading. It's not JSON, but a custom protocol that has JSON as a subset.

While such extensions address the problem of having a serialization format that Godot can save and read again, they simultaneously cause interop problems for every non-Godot JSON deserializer, e.g. webservers, tools like `jq`, and JSON libraries in almost all programming languages. 

I don't think we are doing users a favor by locking them into a format that can only be understood by Godot and Python, especially not under the cover of the `JSON` class. It's not obvious for people unfamiliar with the protocol that these extensions are unsupported in the majority of software.


---

Maybe taking a step back, it would be good to know which problem we are exactly solving. Could you elaborate in which context you needed this?

Related, do we really want to encourage NaN (which is often the result of logic errors) to creep into serialization formats? Can we not expect users to handle these values explicitly and define a domain-specific value for them? I don't think the engine should make such a choice, precisely because there's no standard way of representing them in JSON and different applications may have different preferences.

**Comment by FireCatMagic** [comment]
> Maybe taking a step back, it would be good to know which problem we are exactly solving. Could you elaborate in which context you needed this?
> 
> Related, do we really want to encourage NaN (which is often the result of logic errors) to creep into serialization formats? Can we not expect users to handle these values explicitly and define a domain-specific value for them? I don't think the engine should make such a choice, precisely because there's no standard way of representing them in JSON and different applications may have different preferences.

The problem being it isn't currently possible to store `inf` or `nan` values inside the JSON - in fact doing so currently breaks decoding entirely be allowing invalid JSON.
For my own personal use case, users can build their own 3D levels and some blocks inside the game are allowed to have values of `inf`. The game provides a JSON export option for people who want their levels in a text-readable format.
Currently, when saving `inf` or `nan`, the JSON is unable to be loaded again due to the invalid serlization.


I understand where you are coming from though and I think you are right.
Would a good compromise to be:
- Remove all the code relating to the new parameter
- Remove all the code relating to the inf and nan keywords
But instead:
- Change this to only include the parts where it makes the JSON serializer not break when encoding these values (inf becomes 1e9999, which turns back into inf when turned into a float, nan becomes null)
To the above I may just make a new PR with only the fix that prevents encoding invalid JSON and close this PR.

**Pull request closed without merging**
