### PR TITLE
Added import hint "singleconvcol" for QuickHull convex decomposition when importing 3d scenes

### LINKED ISSUE #29971: Convex decomposition leads to inaccurate shape for simple meshes
**Godot version:** 05a0a68c72cc16c443301398ab93e8d838401ac0

**OS/device including version:**
Windows 10 x86_64

**Issue description:**
Using the old quickhull method, when using the Mesh->Create Convex Collision Sibling, a simple scaled cube mesh would produce a perfect convex hull collision shape. Now, with the new convex decomposition, the same simple cube mesh produces an inaccurate shape:
shape

**Steps to reproduce:**
Import this gltf file to a godot project:  [cube.zip](https://github.com/godotengine/godot/files/3316424/cube.zip)
Use Mesh->Create Convex Collision Sibling(s)
See that the collision shape does not line up with the mesh instance (use wireframe mode for a better look)

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/3316426/test.zip)

### PR DESCRIPTION
**Pull request by kilojool**
This fixes #29971

Adds "singleconvcol" and "singleconvcolonly" to the options of import hints, making the importer use the QuickHull convex decomposition method instead of VHACD. I'm not sure if it's the best terminology, but I think it's nice to have the option at least.

### CODE REVIEW

**Comment by akien-mga** [comment]
Some feedback from discussion on IRC:
```
14:45 <@Akien> reduz: OK with #40622 ?
14:47 <reduz> Akien: I don't think so, quickhull is not a great idea because if the geometry is complex, it will create a very complex convex object that will be unusable in practice
14:47 <reduz> Akien: would be interesting to know the use case behind such a feature also, likely better to open a proposal instead
14:49 <reduz> Akien: to be honest, we should  at some point discuss with blender how to better expose physics stuff via the Blender API and via extensions to gltf or escn so we stop using the current hackish way
14:50 <reduz> Akien: also, it is possible to make an import script that does this, so there is not much of a need to add this as a feature, given how rare the use case probably is
14:50 <@Akien> reduz: well check the referenced issue
14:50 <@Akien> The problem is that for simple geometries, quick hull works well and the other option we use now is bogus
14:51 <@Akien> So adding this import mode is just a workaround, the better fix would be to fix VHACD I guess
14:51 <reduz> Akien: i have seen this, but you can already export simple meshes with hints afaik
14:52 <PouleyKetchoupp> reduz: Akien: Just want to mention the QuickHull thing is the first PR by this contributor, so it would be nice to give them advice or direction if it´s not the right fix :)
14:54 <reduz> PouleyKetchoupp: I don't think its a problem of advise as much as something that would require discussing what the best solution would actually be
14:57 <reduz> PouleyKetchoupp: the PR itself is ok, the problem is whether this is wanted or not, it seems very corner caseish to me and the problem in the original issue has better solutions (so its most likely a documentation problem?), on the other hand the PR is small and does not hurt much, the problem is that users may misunderstand it if we add it and create unusable geometry for physics easily
14:58 <reduz> we had this functionality before and it was literally unusable because users would throw complex geometry to quickhull, which would result in extremely complex convex objects that killed performance
```

So in short, the PR's implementation is fine, but it's not decided yet whether it's a good thing to re-expose a QuickHull import option as it can be misused for complex meshes and lead to issues.

**Comment by kilojool** [comment]
Understandable! I learnt a lot from this so I'm happy anyway!

**Comment by Flavelius** [comment]
It's unfortunate that this doesn't seem to be merged. For my level the standard decomposition creates a huge amount of unnecessary collision shape chunks where meshes are already convex (and _not_ concave-convex) by design which leads to problems with my character controller (many small gaps between these highpoly collision chunks).
As this suffix is optional and does not replace the default, _misuse_ (it shouldn't even be called that) is left to the intention.
And as the nature of open source is, some intentions of fixing other libraries or just creating a whole new export option should generally be considered to be in the 'maybe' or 'later' realm, so fixes that don't break functionality but add more freedom (and even allow fixing certain misbehaviour), like this one, should be given more consideration than dismissal.
Please rethink merging this.

This:
grafik

vs this:
grafik

**Comment by Calinou** [comment]
Since we now expose this in the Mesh menu at the top of the 3D viewport, we should also provide this as an import hint. Otherwise, the exposed feature set is inconsistent depending on your workflow.

**Comment by Flavelius** [comment]
For anyone in need of this feature, as it's not merged for now, here's a workaround (creates single convex static collision children);
This script has to be assigned in the import dialog as 'Custom Script':
```
tool
extends EditorScenePostImport

func post_import(scene):
	iterate(scene)
	return scene
	
func iterate(node: Node):
	if node != null:
		if "-singleconvcol" in node.name and node is MeshInstance:
			node.name = node.name.replace("-singleconvcol", "") #optional
			node.create_convex_collision()
		for child in node.get_children():
			iterate(child)

```

**Pull request closed without merging**
