### PR TITLE
[GDScript] Fix some test file paths

### PR DESCRIPTION
**Pull request by AThousandShips**
Fixed spaces or `-` instead of `_`

### CODE REVIEW

**Review by dalexeev — APPROVED** [review]
This is my typo. :scream: Thank you for the fix!

**Comment by AThousandShips** [comment]
Should I go ahead and normalize the names completely? With `-` -> `_` or should I leave it?

**Comment by dalexeev** [comment]
> Should I go ahead and normalize the names completely? With `-` -> `_` or should I leave it?

That would be great!

**Comment by AThousandShips** [comment]
TIL that Windows file explorer has a batch rename feature, helped a lot for this

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
