### PR TITLE
Make the physics engine deterministic

### PR DESCRIPTION
**Pull request by m4nu3lf**
Makes the the physics engine, *if taken in isolation* deterministic. This is useful for debugging

### CODE REVIEW

**Comment by reduz** [comment]
i think you could probably make it deterministic if you disable ASLR for debugging, no need for this..

**Comment by reduz** [comment]
https://askubuntu.com/questions/318315/how-can-i-temporarily-disable-aslr-address-space-layout-randomization

**Comment by m4nu3lf** [comment]
@reduz Actually I was thinking the same initially but that won't help here because there are other parts of the engine doing memory allocation that are not tied to the physics engine (like having the rendering code running either in parallel or at unpredictable rate) that are causing allocations to be non-deterministic from the physics engine perspective. Could also this be useful from a user perspective?

**Comment by reduz** [comment]
i dont really think so, its too difficult to make things deterministic..

**Comment by m4nu3lf** [comment]
Hum, so, the physics engine with this change would be "deterministic" in the sense that given the same input to the physics engine the output will always be the same, but If the input comes from the logic running in the _process() or the user that will not be in sync with the physics engine and thus the result won't be deterministic as the input will be likely received by the physics engine at different frames.

But for instance this helped me in that I've been able to create a minimal scene reproducing an issue and running it over and over while debugging (without any input) having always the same things happening in each frame

**Comment by Xrayez** [comment]
From the user perspective, this feature would be especially useful for creating replay files of "played matches" that are very compact (only inputs are stored and not game states) and can be played back by the game, at least locally. This is actually one of the features I'm going to try to implement in my own game.

**Comment by reduz** [comment]
I will insist this not ever going to work. Floating point operations may
vary between compiler, compiler version, engine version, platform, etc. The
only way to get determinism is via integer math.

On Sun, Oct 22, 2017 at 9:43 AM, Andrii Doroshenko <notifications@github.com

**Comment by m4nu3lf** [comment]
@reduz AFAIK floating point arithmetic is standardized, unless you change from float 32 to double everything should playback the same

**Comment by m4nu3lf** [comment]
@Xrayez to make that work all thre logic of the game should be in the _physics_process, if something is in the _process update function and it interacts directly or indirectly with the physics engine the result won't be deterministic as the framerate is variable

**Comment by reduz** [comment]
closing, because i dont think this is ever expected to work properly

**Pull request closed without merging**
