### PR TITLE
fix buffer write performance

### PR DESCRIPTION
**Pull request by dragmz**
replaces per-byte fwrite call with a single fwrite call when writing a buffer

### CODE REVIEW

**Comment by neikeq** [comment]
Can you do the same for other platforms? I remember at least unix doesn't override the method either.

**Comment by dragmz** [comment]
Added for Unix however I'm unable to benchmark on any other than Windows at the moment

**Comment by dragmz** [comment]
The GDScript code below runs ~30x faster with the fix on Windows 10 (3350ms vs 120ms):

````
var buffer = PoolByteArray()
buffer.resize(4096)

var f = File.new()
f.open("C:\\temp\\test.dat", File.WRITE)

for i in range(0, 25600):
    f.store_buffer(buffer)

f.close()

**Comment by xsellier** [comment]
@dragmz Do you think you can backport it to branch 2.1 ?

**Review by neikeq — APPROVED** [review]

**Comment by neikeq** [comment]
@xsellier If there are no conflicts, this could be simply cherrypicked IMO.

**Comment by akien-mga** [comment]
Great work! Will merge it as soon as @reduz can give it a check (likely later this week).
In the meantime, if a Unix user can benchmark the performance on Linux, macOS or Android, it could be interesting to know what we gain from this fix on Unix :)

**Comment by neikeq** [comment]
@akien-mga I talked with reduz about this a few months ago and he agreed with changing this; and then I forgot about it.

**Comment by xsellier** [comment]
@akien-mga I will backport it to 2.1.4 and bench it on Linux and android.

**Pull request merged**
