### PR TITLE
Fix DynamicFont outline does not draw using draw_char

### LINKED ISSUE #30309: DynamicFont outline does not draw using draw_char
**Godot version:**
v 3.1.1.stable.official

**OS/device including version:**
Windows 10 x64

**Issue description:**
Dynamic font outline does not show using draw_char() of CanvasItem.  An outline is expected to appear.  Outlines are working for draw_string().

**Steps to reproduce:**
1. Create a root node with Node.
2. Create a child node with Control or Node2D node and attach a GDScript to it.
3. Instantiate a new DynamicFont and initialize with a outline_size and color.
```
func _ready():
	dynamic_font = DynamicFont.new()
	dynamic_font.font_data = load("res://KGMissKindergarten.ttf")
	dynamic_font.size = 120
	dynamic_font.outline_size = 5
	dynamic_font.outline_color = Color( 0, 0, 0, 1 )
	dynamic_font.use_filter = true
```
4. Override the _draw() method and draw some characters with draw_char()
```
func _draw():
	for i in string.length():
		var c = string[i]
		var next_char = string[i + 1] if i + 1 < string.length() else ''
		var advance = draw_char(dynamic_font, pos, c, next_char, Color.red)
		pos.x += advance
```

**Minimal reproduction project:**
[DrawCharTest.zip](https://github.com/godotengine/godot/files/3357867/DrawCharTest.zip)

### PR DESCRIPTION
**Pull request by Raphael2048**
fix #30309

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm not familiar with font drawing, but in FontDrawer in `scene/resources/font.h` the logic seems a bit different:
- The outline for all `draw_char` calls is drawn first, taking into account an outline color.
- The characters are then drawn on top when the FontDrawer is destroyed.

I assume this is done to ensure that all characters are on top of their outlines, and that you don't end up with an outline of the next character drawn on top of the previous character.

**Comment by raphael10241024** [comment]
If you choose to use draw_char(), you need to accept the result that new char overlaps last one, it's correct behavior. If you wish to draw un-overlapped string, using draw_string() is better. Furthermore, the letters seldom overlaps unless you have a very large outline size or you mean to place them together.

**Review by Anutrix — COMMENTED** [review]
Shouldn't there be a return statement?

**Comment by akien-mga** [comment]
> Shouldn't there be a return statement?

No, the outline is drawn first if enabled, and then the character itself should be drawn.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
