### PR TITLE
[DOCS] Update PhysicsDirectSpaceState.cast_motion

### PR DESCRIPTION
**Pull request by ghost**
Since GodotPhysics has been un-deprecated, I've updated the docs to highlight a small discrepancy between it and Bullet, mentioned here: https://github.com/godotengine/godot/issues/21212#issuecomment-423780563

### CODE REVIEW

**Comment by homer666** [comment]
I have no idea what I just did. How do I fix this?

**Comment by bojidar-bg** [comment]
@homer666 I think, try `git rebase HEAD^` followed by `git push --force` or something like it.

**Comment by homer666** [comment]
uh oh

**Comment by homer666** [comment]
Made a new PR for this: #25506

**Pull request closed without merging**
