### PR TITLE
Document the BaseMaterial3D billboard mode not being suited for VR

### PR DESCRIPTION
**Pull request by Calinou**
See #41567.

### CODE REVIEW

**Review by NathanLovato — APPROVED** [review]

**Comment by Calinou** [comment]
I amended the pull request per @goatchurchprime's comment.

**Comment by akien-mga** [comment]
CC @BastiaanOlij

**Review by BastiaanOlij — APPROVED** [review]
I'm fine with the description, it might be slightly too strong as it can still be used for certain particle effects where it's not noticeable like fire effects etc. but it will tell people that when used for proper billboarding it just doesn't look good at all in VR and you need to use different more expensive techniques.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
