### PR TITLE
Add a minimap to the GraphEdit

### LINKED ISSUE #672: Add an optional minimap to GraphEdit
**Describe the project you are working on:**
Editor tools for my game with a logic graph.

**Describe the problem or limitation you are having in your project:**
Working with a large enough graph can be a challenge, as you can get lost between different nodes. Zooming out is an option, but it's not really that handy or fast. Plus, at zoom levels other than default text can look ugly and unreadable due to scaling. So it's not really possible to work at those zoom levels permanently.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
An overview in a form of a minimap can be used to make `GraphEdit` more accessible with larger graphs. It gives a user a complete look at the graph with immediate feedback on their actions and provides a quick navigation option.

Here is an example I've made in GDScript:
image

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
There are several problems that need to be solved along the way, but in concept it should work like this:
* `GraphEdit` has one more child, a Panel, that is semi-transparent;
* Position of this panel can be configurable to anchor to any angle, it can also support resizing;
* This panel receives information about all the nodes and connections present on the parent graph;
* Assuming the panel must render a complete map, its dimensions are used to scale actual node coordinates to the minimap ones;
* Nodes are represented by a small circle or square, color of which must be approximated from the node's style, or manually provided by user, who created it;
* Connections function the same as on the parent graph, though their Bezier settings must be adjusted to a smaller scale;
* Minimap is updated in real time, with every node added, removed, or moved, and after each connection or disconnection.

Not shown in the image above is a rectangle representing "camera", or rather `offset` of `GraphEdit`. Additionally, clicks on the minimap should move the offset to the location corresponding to the click.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be created with a script, at least partially. However, similar to code editor minimap some built-in graph editors (Visual Script, Visual Shader) can benefit from it as an option. And the implementation feels like a natural extension of the `GraphEdit` itself, so making it part of the engine allows everyone to rely on it and use in their own projects.

**Is there a reason why this should be core and not an add-on in the asset library?:**
See above.

P.S.: I can work on this myself.

### PR DESCRIPTION
**Pull request by YuriSizov**
Closes godotengine/godot-proposals#672.

This is a port of [my GDScript implementation](https://gist.github.com/pycbouh/7a88b55697138b646f69da0de40f71ac) with a few tweaks. As such, I expect that some things can be simplified to work better as a part of the engine core. I would appreciate pointers and suggestions for improvements.

Features:
* Shows all nodes and connections as they appear relatively to each other;
* Shows the viewport of `GraphEdit`'s "camera".
* Can be toggled off and resized;
* Picks colors based on `GraphNode`'s stylebox and connection colors, if it can.

Here's how it looks currently:

[Editor look](https://user-images.githubusercontent.com/11782833/98569429-5aaa2800-22c3-11eb-8928-23539254fcb7.png)
[Default theme look](https://user-images.githubusercontent.com/11782833/98569442-5d0c8200-22c3-11eb-947d-a44ae0e2d082.png)
[Settings panel](https://user-images.githubusercontent.com/11782833/98569456-5f6edc00-22c3-11eb-80c6-4241d5de530b.png)

It is supposed to be semi-transparent, but due to #43394, I am unable to tweak and test it in master.

Otherwise, this is the minimal implementation, but it can be enhanced in the future, if there is demand for it. Transparency for the editor tools can be turned into an editor setting. Additional visual features, such as suggested in the proposal like icons and shapes for nodes, can be implemented in some form. Node minimap colors can be made configurable as a separate `GraphNode` property. Etc.

I think this should be portable to 3.2 as well, and I can make a separate PR when this one is validated and approved.

PS. That `zoom_hbox` at the top can really use some semi-transparent background as well.

### CODE REVIEW

**Comment by fire** [comment]
I'm not able to review right now, but I comment that I support adding a minimap.

**Review by Chaosus — APPROVED** [review]
Tested - seems perfect

**Comment by akien-mga** [comment]
Thanks!

> I think this should be portable to 3.2 as well, and I can make a separate PR when this one is validated and approved.

Sounds good, please do.

I guess it would make sense to enable it in the VisualScript and Visual Shader editors in a follow-up PR?

**Comment by pycbouh** [comment]
> I guess it would make sense to enable it in the VisualScript and Visual Shader editors in a follow-up PR?

It should be enabled by default for every `GraphEdit`, because from the feedback I got from my GDScript script and my proposal this seemed to be essential for usability. I can disable it by default and only turn on for these editors, of course, if you want it.

> Sounds good, please do.

Will do!

**Comment by Chaosus** [comment]
There are some problems with zooming in + I would suggest to make lines a bit thinner:
image

**Comment by akien-mga** [comment]
> It should already be enabled by default for every GraphEdit, because from the feedback I got from people I've shared my GDScript script with and from my proposal this seemed to be essential for usability. I can disable it by default and only turn it on for these editors, of course, if you want it.

Ah no it's fine if it's enabled by default already. We'll see if this needs to changed based on player feedback, but it's good to make users aware of its existence :)

**Comment by pycbouh** [comment]
> There are some problems with zooming in + I would suggest to make lines a bit thinner

Hm, I've definitely tested zooming in and out before. Need to look into it.
As for lines, I guess this is because of the antialiasing fixes in master? At any rate, I'll address all of this. Thanks for letting me know.

**Comment by Chaosus** [comment]
`As for lines, I guess this is because of the antialiasing fixes in master?`

Indeed, but I think it's easy can be fixed. Maybe AA should be disabled for these lines.

**Pull request merged**
