### PR TITLE
Implemented connection swapping for visual shader graph

### PR DESCRIPTION
**Pull request by Chaosus**
QoL change:
swap

### CODE REVIEW

**Comment by Chaosus** [comment]
To prevent incorrect behavior like:
swap_bug
I've added additional signal `GraphEdit.connection_cancel`, is it ok @akien-mga?

**Comment by fire** [comment]
I wonder if it is possible to push implementation entirely to the Graph Edit.

This doesn't seem like a Visual Shader only feature.

**Comment by Chaosus** [comment]
Hmm, yeah but in that case, GraphEdit should be seriously modified

**Comment by fire** [comment]
Yes, GraphEdit and VisualShader/Script editors should be modified. Connection swapping code doesn't belong in Visual Shader.

**Comment by Chaosus** [comment]
@fire Do you suggest to close this PR? (so, I agreed that this is a temporary solution)

**Pull request closed without merging**
