### PR TITLE
Loop over faces in create_trimesh_shape()

### PR DESCRIPTION
**Pull request by lupoDharkael**
Small optimization to reduce overhead operations in the loop.

### CODE REVIEW

**Comment by akien-mga** [comment]
Did you measure if it actually makes any positive difference?

**Comment by lupoDharkael** [comment]
I couldn't test in release because the engine creashes (amdgpu) but testing in debug the loop is a 20-25% faster with the meshes I've tested. I makes sense as [loop unrolling](https://en.wikipedia.org/wiki/Loop_unrolling) commonly increases speed in tight loops.
It may be equally of sightly faster in release, or have a similar acceleration ratio as the debug build. It depends on the compiler but the change is small and I think it is worth it.

**Comment by asheraryam** [comment]
It does seem like a negligible change but it's avoiding 2/3 of the calls to `faces.get()`, is that a performance bottleneck we are aware of?

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
