### PR TITLE
Continuation of work on visual particles system

### PR DESCRIPTION
**Pull request by Chaosus**
This is a continuation of my work to the particle system in visual shaders. 

Added new shader modes:

- **Emit(Custom)**
- **Process(Custom)**

Added nodes:

New **Emit** nodes:

image

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleOutput** : `VisualShaderNodeOutput`

Description: Created automatically in all modes of particle shader.
Have different input ports (depending on the shader mode).

Availability: Everywhere

Common Input ports (on all shader modes):

vec3 velocity - an initial velocity vector, translates to VELOCITY
vec3 color - translates to COLOR.rgb
float alpha - translates to COLOR.a
Transform position - translates to TRANSFORM
float scale
bool active

Emit:

- (Common Input ports)
- float lifetime_scale
- float initial_angle
- float anim_offset

Emit (Custom):

- (Common Input ports)
- vec3 custom
- float custom_alpha

Process:

- (Common Input ports)

Process (Custom):

- (Common Input ports)

End:

- (Common Input ports)

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleEmitter** : `VisualShaderNode`

Description: Abstract base class for all emitters.

Availability: Emit

Output ports:

- Transform `position` - position of the particle, need to be connected to the `position` input port inside `VisualShaderNodeParticleOutput`.

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleBoxEmitter** : `VisualShaderNodeParticleEmitter`

Description: Generates a position inside a box.

Availability: Emit

image

Input ports:

- vec3 `extents` (default: vec3(1, 1, 1)) - Defines a volume of the box.

Output ports:

- Derived from **VisualShaderNodeParticleEmitter**

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleRingEmitter** : `VisualShaderNodeParticleEmitter`

Description: Generates a position inside a ring.

Availability: Emit

image

Input ports:

- float `radius` (default:10) - A radius of the ring.
- float `inner` (default:0) - An inner volume size of the ring.
- float `outer` (default:0) - An outer volume size of the ring.

Output ports:

- Derived from **VisualShaderNodeParticleEmitter**

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleSphereEmitter** : `VisualShaderNodeParticleEmitter`

Description: Generates a position inside a sphere.

Availability: Emit

image

Input ports:

- float `radius` (default:10) - A radius of the sphere
- bool `use_inner_space` (default:`true`) - if `false` the particles will generates on a sphere but not inside it.

Output ports:

- Derived from **VisualShaderNodeParticleEmitter**

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleTextureEmitter** : `VisualShaderNodeParticleEmitter`

Description: <not yet implemented> (I think @reduz should implement it himself since I'm not sure how to make it properly).

Availability: Emit

Input ports:

- sampler2D `position`
- sampler2D `normal`

Output ports:

- Derived from **VisualShaderNodeParticleEmitter**

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleRandomness** : `VisualShaderNodeParticleEmitter`

Description: Generates a random scalar or a vector.

Availability: Everywhere

Properties: Op
Type - OP_TYPE_SCALAR / OP_TYPE_VECTOR which affect a type of result

vsp_randomness

Input ports:

- float/vec3 `min` (default: 0.0/vec3(-1, -1, -1)) - a minimum value to generate
- float/vec3 `max` (default: 1.0/vec3(1, 1, 1)) - a maximum value to generate

Output ports:

- float/vec3 `random` - a generated value

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleConeVelocity**

Description: Generates a velocity normalized vector inside a cone.

Availability: Emit

vsp_cone

Input ports:

- vec3 `direction` (default: vec3(1, 0, 0)) - a direction vector
- float `spread(degrees)` (default: 45.0) - spread amount

Output ports:

- vec3 `velocity` - a velocity normalized vector inside a cone.

---------------------------------------------------------------------------------------------------------------------------------------------

class **VisualShaderNodeParticleAccelerator** : `VisualShaderNode`

Description: Intended to modify particle velocity via time.

Availability: Process

Properties: Mode: MODE_LINEAR/MODE_RADIAL/MODE_TANGENTIAL

vsp_accel

Input ports:

- vec3 `velocity`
- vec3 `amount`
- float `randomness`

---------------------------------------------------------------------------------------------------------------------------------------------

**Notes**:

- The internal code is mainly copy/pasted from ParticlesMaterial and their outputs is almost identical

- All these new types have a "Particle" suffix to make sorting/seeing of them easy.

### CODE REVIEW

**Comment by Chaosus** [comment]
`UPDATE (12/10/2020):`

- Added Emit(Custom) and Process(Custom) basic implementation - @reduz is still working on it and there will be separate functions for them in the near future.
- Added Collide mode - to provide a way to handle colliders
image


- Removed TextureEmitter since I still don't understand how it should work
- Added Emit node to provide a way to emitting - this node does not have outputs instead every instance of it proceeded independently (after Output processing)

image

- Changed position type of EmitOutput to vector, I think it's better to handle and modify rather than matrix, and logically position associated with vectors.
- Added rotation_axis port to EmitOutput - now it will work with initial_angle to rotate a mesh transformation

**Comment by Chaosus** [comment]
- Removes custom modes from the mode list and attached additional Custom checkbox for comfortability: image

**Comment by Chaosus** [comment]
Update 08/03/2021

- Added height parameter to RingEmitter - which provide a way to make cylinder (or tube) shapes

image

**Comment by QbieShay** [comment]
Hello @Chaosus 

Thank you for the effort towards making particles more user-friendly!

I will try this PR for a bit and give feedback in the next days.

**Comment by QbieShay** [comment]
Hey @Chaosus !

I have tried out your branch and I will write my feedback here.
I do not think that all of my feedback needs to be addressed in this PR.

# Common
I think that it is needed to have the outputs of the emit part in the inputs of the process part. For example, I'm not sure how to achieve scale over life + random scale with the current setup. ( `initial_scale * texture(scale_over_life, vec2(custom.y))` can't be achieved properly if initial scale is randomized in the emit part

Another thing that I noticed is that the emitter nodes have a transform output, which makes it a bit annoying to change rotation or add an offset to the particle spawn. (Extracting the position from the transform and then going back doesn't seem super user friendly).
I think that it would be best to hide the transform property for the default emitter and give a position instead, so that the transform can be constructed internally and users don't need to worry about it (they can meddle with the transform if they use the custom emitter instead)

# Custom nodes
## SphereEmitter
Instead of selecting `use_inner_space`, I'd give a second float parameter that defines the inner offset.

## Box emitter
Works :+1: 

##  Point emitter
Works :+1: 

## RingEmitter
I LOVE :heart:  this one and I think it's a very very nice addition to the emitter crew. I needed it many many times.
I'd suggest removing the outer radius as the same effect can be achieved by tweaking radius+inner radius.
Alternatively, the inner and outer parameters can be kept, but I think that it would make sense then to do the same with the sphere emitter.
I'd like to have the angle on the horizontal plane as an output if possible, so that i could orient the particle to face the direction of the spawn, or create radial patterns.

## ParticleRandomness
It seems to generate an error every time i connect it somewhere, but I do like the concept a lot :+1: 
Screenshot_2021-04-10_22-02-18
Screenshot_2021-04-10_22-02-06

## Cone velocity
Works :+1: 

## Accelerator
Works :+1: 

## Sub particle emitter
I get a lot of errors int he console if i connect it anywhere:
```
Attempting to use an uninitialized RID
  drivers/vulkan/rendering_device_vulkan.cpp:6861 - Condition "!pipeline" is true.
  This compute pipeline requires (0) bytes of push constant data, supplied: (32)
  No compute pipeline was set before attempting to draw.
Nodes Disconnected
```
# Conclusion
Thanks a lot for all this work! I think that it goes in a very good direction to enable more people to do cool stuff with particles.
Let me know if I can help with addressing some of the feedback that I have mentioned here, and if I can help in general with visual nodes for particles.

**Comment by Chaosus** [comment]
@QbieShay Thanks for reviewing, I tried to fix the problems you pointing.

> SphereEmitter
> Instead of selecting use_inner_space, I'd give a second float parameter that defines the inner offset.

Thanks, modified.

> RingEmitter
> I'd suggest removing the outer radius as the same effect can be achieved by tweaking radius+inner radius.
> Alternatively, the inner and outer parameters can be kept, but I think that it would make sense then to do the same with the sphere emitter.
> I'd like to have the angle on the horizontal plane as an output if possible, so that i could orient the particle to face the direction of the spawn, or create radial patterns.

Removed outer_radius, added axis/angle(degrees) parameters

> ParticleRandomness
> It seems to generate an error every time i connect it somewhere

Thanks, bug fixed

> I get a lot of errors int he console if i connect it anywhere:
> 
> Attempting to use an uninitialized RID
>   drivers/vulkan/rendering_device_vulkan.cpp:6861 - Condition "!pipeline" is true.
>   This compute pipeline requires (0) bytes of push constant data, supplied: (32)
>   No compute pipeline was set before attempting to draw.
> Nodes Disconnected

I guess this is a problem not related to the visual shader but on the rendering side. There are some bugs with particles that you should address to @reduz.

**Comment by Chaosus** [comment]
PS: Ah, I missed the conclusion, while fixing the other issues, I need to answer it too :S

**Comment by Chaosus** [comment]
Okay, the second part of my answer to @QbieShay 

> I think that it is needed to have the outputs of the emitting part in the inputs of the process part. For example, I'm not sure how to achieve scale over life + random scale with the current setup. ( initial_scale * texture(scale_over_life, vec2(custom.y)) can't be achieved properly if the initial scale is randomized in the emit part

Yeah, I've added scale now and axis/rotation of particles geometry. Not sure how to scale overtime should be handled. My first approach is to simply assign a little bit bigger or smaller than 1.0 to the scale in Process:

test2

The process will multiply the transform matrix each frame so the result is sufficient and visible. Maybe a separate node should be created for this case - I don't know.

test

> Another thing that I noticed is that the emitter nodes have a transform output, which makes it a bit annoying to change rotation or add an offset to the particle spawn. (Extracting the position from the transform and then going back doesn't seem super user friendly).

I think this type should not be changed (as it's originally suggested by @reduz) - because users may want to apply their own transformations modifiers to the transform rather than provided from the emitter and allow them to create their own emitters. Instead, the new nodes may be introduced to modify these transform themselves.

> I think that it would be best to hide the transform property for the default emitter and give a position instead so that the transform can be constructed internally and users don't need to worry about it (they can meddle with the transform if they use the custom emitter instead)

Well, there is a `PointEmitter` to define the original position and apply them to transform. I'm not sure how you suggest hiding it in the `EmitOutput` and what is the concept of "default" emitter. Please explain it in more detail.

**Comment by QbieShay** [comment]
Hey @Chaosus , thank you for your reply.

Regarding scale:
Multiplying the matrix every process is not a good approach, see: https://github.com/godotengine/godot/issues/33357
and https://github.com/godotengine/godot/pull/46687

Regarding emit output:
What i suggest is to hide the "transform" parameter and expose a "position" parameter instead. There are two different types of output, both for process and emit. One is the default one, and the other one is the one that you get if you tick "custom".
In my opinion the one that you get if you tick custom is the advanced and more low level emitter, while the one that you get as a default is a more user friendly emitter. 

PS: I love the teapots flying around with random rotation :+1:

**Comment by Chaosus** [comment]
Ok, I will rest and afterward will attempt to modify it as you said. I Will report when I'm done.

**Comment by Calinou** [comment]
Does this PR make the ring emitter available for GPUParticles3D when *not* using visual shaders?

**Comment by QbieShay** [comment]
@Calinou no, ring emitter is available only in VS

**Comment by Chaosus** [comment]
@QbieShay Alright let's continue:
I've changed the port type to vector, removed PointEmitter (cuz it seems redundant - you can simply connects a 
vector constant instead), added a new Node called `MultiplyByAxisAngle` to provide an easy way to rotate the emitter position:
image
Also, I've removed most of "custom" ports and leave only Custom Color/ Custom Alpha, I'm not sure about this change and I not sure the rest of the ports are so needed to preserve.

> Multiplying the matrix every process is not a good approach

I didn't find another way to keep and modify these parameters per frame (aside from using a CUSTOM built-in). There are no built-ins for scale and rotation, and you need to apply them to TRANSFORM in any way. Suggest your way to solve it.

Please review this PR again.

**Comment by QbieShay** [comment]
Hi @Chaosus !
I have tested the PR :)
MultiPlyByAxisAngle: great node! Maybe it could have a way also to multiply directions? I'm using it to also tilt the cone direction (the difference is that when you make it into a vec4, the last component should be 1 for positions and 0 for directions)
I like the new work, I think it makes the particles easier to use.

Regarding custom, i didn't find a way to use it at all. Because there is no transform output, there is no way to move particles, but only to change color and custom vector. I think that all the built-in outputs of particles should be present (transform, velocity, active, custom, color (i hope I didn't forget any))

For how to bring the initial scale etc. into the process, i think that it should just be recalculated using the same list of operations inside of start. because all the random use the particle index, it should all be deterministic.

**Comment by QbieShay** [comment]
I have made a shader with scale over life and random scale
https://user-images.githubusercontent.com/7917475/115954465-83c91880-a4f1-11eb-9eb3-e3719a76f671.mp4

```
shader_type particles;

uniform sampler2D scale_curve;
float rand_from_seed(inout uint seed) {
	int k;
	int s = int(seed);
	if (s == 0)
	s = 305420679;
	k = s / 127773;
	s = 16807 * (s - k * 127773) - 2836 * k;
	if (s < 0)
		s += 2147483647;
	seed = uint(s);
	return float(seed % uint(65536)) / 65535.0;
}

float rand_from_seed_m1_p1(inout uint seed) {
	return rand_from_seed(seed) * 2.0 - 1.0;
}

uint hash(uint x) {
	x = ((x >> uint(16)) ^ x) * uint(73244475);
	x = ((x >> uint(16)) ^ x) * uint(73244475);
	x = (x >> uint(16)) ^ x;
	return x;
}

void start(){
	uint rand = uint(NUMBER);
	float scale = rand_from_seed(rand);
	float x_pos = float(NUMBER);
	TRANSFORM = mat4(
		vec4(scale,0.0,0.0,0.0),
		vec4(0.0,scale,0.0,0.0),
		vec4(0.0,0.0,scale,0.0),
		vec4(x_pos,0.0,0.0,1.0)
	);
}

void process(){
	uint rand = uint(NUMBER);
	float scale = rand_from_seed(rand);
	TRANSFORM[0][0] = scale * texture(scale_curve, vec2(CUSTOM.y)).r;
	TRANSFORM[1][1] = scale * texture(scale_curve, vec2(CUSTOM.y)).r;
	TRANSFORM[2][2] = scale * texture(scale_curve, vec2(CUSTOM.y)).r;
	CUSTOM.y += DELTA/LIFETIME;
}
```

**Comment by QbieShay** [comment]
The only issue with repeating the initial values is that everything that uses random needs to be redone in the same exact order, otherwise it will yield a different result, because the random seed is an out variable, so it is modified every time it's used.

**Comment by Chaosus** [comment]
> MultiPlyByAxisAngle: great node! Maybe it could have a way also to multiply directions? I'm using it to also tilt the cone direction (the difference is that when you make it into a vec4, the last component should be 1 for positions and 0 for directions)

Did you mean this?

image

Not sure if it's too complex even for new users to do so. I could add an integer property to provide multiple directions (max 3 for example), yeah, I just not sure if it's so important.

> Regarding custom, I didn't find a way to use it at all. Because there is no transform output, there is no way to move particles, but only to change color and custom vector. I think that all the built-in outputs of particles should be present (transform, velocity, active, custom, color (i hope I didn't forget any))

Me too to be fair. As far as I understand @reduz `custom` acts like a varying to transfer data between `start` and `process` functions. So there is no difference if I rid of the `custom` mode and push custom color/alpha to `start` mode outputs. Correct me if I'm wrong.

**Comment by Chaosus** [comment]
@QbieShay I guess if I provide a separate TRANSFORM output for process mode which does not been multiplied each frame the problem with scaling should solve?

**Comment by QbieShay** [comment]
Hey @Chaosus 

> Did you mean this?
I didn't mean that but it's super cool. What I meant is that when you transform a vec3 into a vec4, you need to use 1 as the last component if you're transforming a position, while 0 if you are transforming a direction. But it's not that important right now :)

> Me too to be fair. As far as I understand @reduz custom acts like a varying to transfer data between start and process functions. So there is no difference if I rid of the custom mode and push custom color/alpha to start mode outputs. Correct me if I'm wrong.

I think that the old node that you had with outputs custom, custom alpha, custom color, transform and velocity was fine

> I guess if I provide a separate TRANSFORM output for process mode which does not been multiplied each frame the problem with scaling should solve?

No, I think the right solution is to provide a node that gives the outputs of the start function. It is possible to rebuild it manually but it would be better if people just had it I believe, but it doesn't have to be in this PR, since it's just an addition.

**Comment by Chaosus** [comment]
@QbieShay I'm a bit confused (especially after a long lay in hospital) - what should I change here in order for this PR to be accepted? I think I need an exact list.

**Comment by QbieShay** [comment]
Sorry @Chaosus , i hadn't seen the comment :( 

> @QbieShay I'm a bit confused (especially after a long lay in hospital) - what should I change here in order for this PR to be accepted? I think I need an exact list.

For when the mode is set to custom, color, alpha, custom vector and transforms should be brought back in the output node, for both start() and process().

**Comment by Chaosus** [comment]
@QbieShay Fixed

**Comment by QbieShay** [comment]
Sorry, i forgot that earlier, i think velocity should be there too. Other than that, it's looking good!

**Comment by Chaosus** [comment]
Fixed again...

image

PS: Ah, you said something about scaling and modifying transform in process - what should I fix for this?

**Comment by QbieShay** [comment]
I think that it can be looked at later(another PR) for that :) right now I'm not really capable of articulating that

**Comment by Chaosus** [comment]
Alright, I too happy with what I've done. If there is any bug or field of enhancement I will continue to improve in the next PR's.

**Comment by QbieShay** [comment]
Well I don't have a button to formally approve, but i do approve :D

**Review by QbieShay — APPROVED** [review]
Can't comment from a code perspective, but I did try out the PR and it already adds pretty good functionalities. It's solid work that will already bring Godot's particle shaders miles ahead in terms of accessibility! :+1:

**Comment by clayjohn** [comment]
I tested this out locally and played around with it for a bit. The only odd thing I noticed was that ``Velocity`` was added to ``VELOCITY`` in the normal process shader, but overwrote ``VELOCITY`` in custom mode. In my opinion, it makes more sense to overwrite velocity every frame in the process shader. That way users can actually control velocity/acceleration. When you specify a value to increase velocity, you are actually specifying acceleration.

**Comment by Chaosus** [comment]
@clayjohn I removed `VELOCITY` from custom mode - does it looks ok now?

**Comment by Chaosus** [comment]
I managed to make scaling and rotation CurveTexture properly works with Process, but this required an additional matrix to be attached to each particle to keep started transformation: `START_TRANSFORM`.

particles

**Comment by Chaosus** [comment]
@reduz said that he would add new built-ins for user data to better performance so I've reverted the changes I made about introducing START_TRANSFORM to the particles renderer. This PR can be merged as it is as it mostly worked properly.

**Comment by clayjohn** [comment]
> I removed VELOCITY from custom mode - does it looks ok now?

I was not suggesting that you remove ``VELOCITY``. I was suggesting that, when you use the Velocity port, you write directly to ``VELOCITY`` instead of adding to ``VELOCITY``

**Comment by Chaosus** [comment]
Sorry, then I wrongly understood you (probably I'm tired). Bring it back and fixed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
