### PR TITLE
show Buttons in Scene tree dock if empty scene

### PR DESCRIPTION
**Pull request by volzhs**
new_scene

### CODE REVIEW

**Comment by akien-mga** [comment]
IMO it's a good addition. @reduz mentioned on IRC that if we were to add such contextual buttons, it should be done consistently and thus he seemed not to interested to have them just for the empty scene tree.

So, people of Godot, do some lobbying if you think it a good enhancement :p

**Comment by volzhs** [comment]
Of course, there is two button for creating new node beside of search field with current head.
But, I think, this is good for beginner of godot to help to start creating first scene.

**Comment by neikeq** [comment]
I am fine with this addition. I've seen people confused the first time using Godot. Some of them don't know about adding nodes at first. This may be a good introduction :)

**Comment by reduz** [comment]
given that some buttons for this were now added, I suppose this is not needed

**Pull request closed without merging**
