### PR TITLE
Fully expose the data variable in AudioStreamSample and AudioStreamOGGVorbis

### PR DESCRIPTION
**Pull request by gradientvera**
The "data" variable on AudioStreamSample and AudioStreamOGGVorbis seemed to be missing from the docs.

This if my first PR, so please tell me if there's anything I can improve!

### CODE REVIEW

**Comment by vnen** [comment]
Thanks for your contribution. However, those XML files are generated from the code, so this change will be lost in the next sync. The `data` property does not appear in the XML because it is deliberately hidden in code (see the `PROPERTY_USAGE` flags): https://github.com/godotengine/godot/blob/1c419531a009f48aa074f9b5f93b98d387c33723/scene/resources/audio_stream_sample.cpp#L554

We can discuss whether or not the property should be fully exposed, but if it is to be exposed, it should be done properly in the bindings.

**Comment by ZDDM** [comment]
Ah, I apologize. I didn't know the XML files were generated from the code! I'll try to be more careful next time I create a pull request.

And I personally think it should be fully exposed because of 'consistency'...
The [Image](https://godot.readthedocs.io/en/latest/classes/class_image.html#member-variables) resource has a similar 'data' method that's exposed, so I believe the data method in AudioStreamSample and AudioStreamOGGVorbis should be fully exposed too.

**Comment by ZDDM** [comment]
I've changed the scope of this PR to also cover fully exposing the data variable on both classes.
As an additional change, I've changed the setters and getters to be more consistent with similar methods in the Image resource. However, whether this change is fine or not might still need to be discussed.

**Comment by akien-mga** [comment]
Please squash all changes into one commit so that they can be reviewed and discussed as a whole (and potentially merged), see [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by bugsalad** [comment]
Apologies for the necromancy, but it seemed better to write here than to create a separate issue.

AudioStreamSample.data (from WAVs) contains PCM frames, but AudioStreamOGGVorbis.data (from OGGs) is just the raw file bytes. Decompressing the actual OGG audio would seem more useful.

Thanks!

**Comment by Calinou** [comment]
@bugsalad Please open a [proposal](https://github.com/godotengine/godot-proposals) if you need this feature for a project.

**Pull request merged**
