### PR TITLE
Fix CSGBox size

### PR DESCRIPTION
**Pull request by jmf**
CSGBox is currently twice the size it should be. A box of size 1x1x1 is actually 2x2x2 units large. This pull request fixes this bug for CSGBox. All other CSG objects appear to respect the parameters and create the object properly.

### CODE REVIEW

**Comment by jmf** [comment]
This will break existing scenes with CSGBox, by the way. Boxes in old scenes will be halved in size.

**Comment by mhilbrunner** [comment]
That shouldn't be too bad if we fix this pre-3.1 alpha, as CSG is only released with 3.1

**Comment by jmf** [comment]
Please don't merge this yet.
I just discovered an issue with the gizmo position that is introduced with this fix. I will fix this asap.

**Comment by jmf** [comment]
This works now and can be merged.

**Comment by akien-mga** [comment]
Removed "breaks compat" label as it's a master-only feature, so we never shipped it in a stable release requiring to keep compatibility.

**Comment by akien-mga** [comment]
As `CubeMesh` has the same size (extents 1, size 2), I don't think `CSGBox` should differ from that. As @reduz mentions too, this is done this way to allow better snapping.

We can change those default dimensions if needed for both `CubeMesh` and `CSGBox` in 4.0 with compatibility breakage.

**Comment by jmf** [comment]
This pull request isn't about resizing the CSGBox to an other size. It is about a bug that causes the CSGBox to be twice as big as actually entered. When e.g. creating a box with height 2.5 units, it will end up being 5 units high.

**Pull request closed without merging**
