### PR TITLE
Fix free(RID) abuse by various classes

### LINKED ISSUE #64199: Invalid RIDs detected upon opening the Editor
### Godot version

3.x at a7559fcb6ef230d9b64f6f71bd7bdd87da7ffcbb

### System information

Arch Linux

### Issue description

By just opening the Editor you'll see several invalid RID error messages in the terminal.

These messages started appearing in `3.x` after #55764 was merged.

### Steps to reproduce

1. Create a new project and close the Editor.
2. In a terminal, open the project with `godot -e --path /path/to/project`
3. You'll see the following invalid RIDs error messages in the terminal:
```
ERROR: Invalid RID.
   at: free (servers/visual/visual_server_raster.cpp:69)
ERROR: Invalid RID.
   at: free (servers/visual/visual_server_raster.cpp:69)
ERROR: Invalid RID.
   at: free (servers/visual/visual_server_raster.cpp:69)
ERROR: Invalid RID.
   at: free (servers/visual/visual_server_raster.cpp:69)
```

### Minimal reproduction project

An empty new project ~is enough.~ using GLES2 suffices.

### PR DESCRIPTION
**Pull request by TokisanGames**
Fixes #64199 RID Error messages opening up GLES2 projects.

@lawnjelly @akien-mga

### CODE REVIEW

**Comment by lawnjelly** [comment]
I suspect this would be better done by adding a `safe_free()` wrapper function in `VisualServer`. Something like:

```
void safe_free(const RID &p_rid)
{
	if (p_rid.is_valid()) {
		free(p_rid);
	}
}
```
As well as being less verbose, this also allows adding debugging code to all calls easily, should we want to show these on e.g. a DEV_ENABLED verbose build or something.

I'm still not totally convinced we are gaining massively here by flagging NULL RID deletes, but hey ho it seems fairly harmless (apart from the false positives which we can deal with). :man_shrugging:

**Comment by tinmanjuggernaut** [comment]
The RID system is inherently not safe. All of these error messages and checks are non-comprehensive hacks to try and push responsibility for handling RIDs with care on to the user.

Safe_rid is a name that gives a false sense of security. Call it check_and_free if you like, or we could remove the first error entirely and silently fail. But these will lead to more RID abuse, rather than less.

This is not safe:
```
RID a = VS::get_resource() 
VS::safe_free(a) 
VS::safe_free(a) # Error: not found

RID b = get_resource()
VS::safe_free(a) # Could free b's memory 
```

This is exactly what happened in #53374. That took me months of suffering, and two months of troubleshooting, testing, and debugging to fix. Because of these messages, I was able to find and fix 4 classes in a few minutes instead of months. I call that a massive gain.

**Comment by lawnjelly** [comment]
Yes, `check_and_free()` is fine too imo. :+1: 

I only suggested `safe_free()` because I have encountered similar naming conventions in the past (e.g. DirectX with `SAFE_RELEASE` and `SAFE_DELETE`).

**Comment by tinmanjuggernaut** [comment]
> I only suggested safe_free() because I have encountered similar naming conventions in the past (e.g. DirectX with SAFE_RELEASE and SAFE_DELETE).

Understandable, but in the example, it's probably actually safe. RIDs are not safe at all.

Is this a for sure change you want me to make?
* check_and_free() in the 5 servers: VisualServer, Bullet/SW/2D PhysicsServers, and NavigationServer
* change the 4 classes modified here to call it?

It's actually _more_ code to do the same thing, but I'll put it in if that is the direction.

**Comment by akien-mga** [comment]
I feel this is fine as is personally. It's not worth it to refactor things significantly in `3.x`, if this needs better semantics this should be done for 4.x.

**Review by clayjohn — APPROVED** [review]

**Comment by lawnjelly** [comment]
> * check_and_free() in the 5 servers: VisualServer, Bullet/SW/2D PhysicsServers, and NavigationServer

Sorry I wasn't proposing this, just in `VisualServer`, as in my comment. `VisualServer` tends to be the one that I've seen making the most use of deleting NULL RIDs.

Doing the check in the calling code imo isn't clear that it is _expected_ that NULL RIDs will be passed, rather than simply protective code (consider coming back to the same code in 6 months). But it's a matter of taste so I won't hold up the other approach.

Also bear in mind there is also the possibility that there may be further false flags to deal with that haven't cropped up yet. We were expecting some, as said on the original PR.

**Comment by lawnjelly** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
