### PR TITLE
Rename several transform built-ins in shaders

### PR DESCRIPTION
**Pull request by Chaosus**
Remake https://github.com/godotengine/godot/pull/59092

> WORLD_MATRIX rename to MODEL_MATRIX
> WORLD_NORMAL_MATRIX rename to MODEL_NORMAL_MATRIX
> 
> CAMERA_MATRIX rename to INV_VIEW_MATRIX
> INV_CAMERA_MATRIX rename to VIEW_MATRIX

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by novaplusplus** [comment]
Need to get the docs updated to reflect this - took me awhile to figure out why my shaders blew up!

**Comment by clayjohn** [comment]
It looks like https://github.com/godotengine/godot-docs/pull/5700 mistakenly only updated the fragment shader part of the docs, the same changes are still needed for the vertex shader section

**Pull request merged**
