### PR TITLE
Add "Show" (in Explorer) button to project explorer

### PR DESCRIPTION
**Pull request by ghost**
show

### CODE REVIEW

**Comment by groud** [comment]
I don't get the use case. Being able to do that once you're in the editor makes sense, but in the project list I don't get it.

**Comment by poke1024** [comment]
The use case is having several projects you cannot differentiate by name alone (like version v1, v2, v3, v4 of the same project); you need to look inside them (and the asset files) to differentiate which one you want to open.

**Comment by groud** [comment]
Well, no. They'll have different paths. So you just have to look at their path.

**Comment by poke1024** [comment]
Yes, but for me project names are often not that explanatory, in the worst case something like "TestProjectA", "TestProjectXYZ", ... I need to see what's inside to know which project I'm actually dealing with.

**Comment by groud** [comment]
Well at a given point you have to help yourself for that... I think the project manager has already too much buttons and we sould avoid adding more for a really corner case situation. But I wouldn't be against it if we moved that to a dropdown menu or something like that.

But anyway, IMHO the project manager UI definitely needs a rework to be more user friendly.

**Comment by poke1024** [comment]
I agree on that. It's a bit confusing.

**Comment by akien-mga** [comment]
I think "Show" is a bit confusing, since you had to mention in this PR that it's "(in Explorer)", but this info is missing from the project manager. As is, I'd expect it to give me a preview of the project somehow in Godot.

If the intent is to disambiguate, I think the path shown below the name handles most of it already - if you created your projects with both confusing names and confusing paths on the filesystem, you're not helping yourself :P

Eventually, there could be a RMB menu with a "Show in Filesystem" option.

But yeah we really need to rethink the whole project manager, currently it's quite limited and limiting.

**Comment by poke1024** [comment]
Based on the comments above, changed to an unnamed filesystem button with a redesign of button locations:

bildschirmfoto 2017-12-23 um 15 57 44

**Comment by poke1024** [comment]
Changed again to a minimal file explorer button in front of the path:

pm

The button appears in front of the path for selected item only. Clicking on it will "open in explorer".

No other changes.

**Comment by poke1024** [comment]
Another common use case for this is backing up your project or packaging it in a zip to send it somewhere.

**Comment by akien-mga** [comment]
I like that last version :)

It just lacks a tooltip IMO (using `TTR("")` so that it can be translated).

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by poke1024** [comment]
Added a tooltip, `TTR("Show In File Manager")` already exists.

screen

**Comment by akien-mga** [comment]
Thanks a lot, merged manually as 1d2d08da5 to fix the merge conflict.

**Pull request closed without merging**
