### PR TITLE
Make static collider use multi-convex instead of trimesh.

### PR DESCRIPTION
**Pull request by fire**
Part of https://github.com/godotengine/godot/pull/51053

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
Is there a specific reason to switch to multi-convex in this case? Triangle mesh is the correct type in most cases, it should probably be the default, and then have separate options for convex shapes instead (single / simplified / multi).

**Comment by Calinou** [comment]
I think trimesh should be the default, with convex options used if better performance is needed.

It's very uncommon for level geometry to be able to use multi-convex shapes reliably.

**Comment by fire** [comment]
Will close due to second opinions from the physics team.

**Comment by pouleyKetchoupp** [comment]
Just to be clear, I do think it would be great to have options to convert to convex hull in the new 3D import settings, as extra settings. Going through a proposal could help with discussing what options would be needed and how the UI would look like.

**Pull request closed without merging**
