### PR TITLE
Made toplevel a property for Node3D and CanvasItem

### LINKED ISSUE #10453: set_as_toplevel() could be exposed to property
Making Spatial toplevel (be like global spatial) is quite useful shame it can be activated only from scripting.

### PR DESCRIPTION
**Pull request by Duroxxigar**
Fixes [#10453](https://github.com/godotengine/godot/issues/10453).

### CODE REVIEW

**Comment by Duroxxigar** [comment]
Made a mistake for working late on #36092 - my apologies. Felt like it would take longer to fix that one rather than open a new one in my current delirious state.

**Comment by aaronfranke** [comment]
As mentioned in #16863, this should likely be renamed to `top_level`.

**Comment by akien-mga** [comment]
Thanks!

> As mentioned in #16863, this should likely be renamed to top_level.

That can be done in a second step, for this PR I prefer not to break compat so it can be cherry-picked.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by akien-mga** [comment]
Cherry-picked reverted to fix regression #42545.

The change is still there in the `master` branch, but might also trigger similar issues, which need to be debugged.

**Pull request merged**
