### PR TITLE
Fix crash on null expressions in GDScript

### LINKED ISSUE #53862: GDScript 2.0: Typing "." number crashes the engine
### Godot version

v4.0.dev.custom_build [bf322bacd]

### System information

manjaro 21, AMD Radeon r7 200 series, Vulkan, 8GB Memory

### Issue description

When you're using the script editor, and type something starting with the `.` the engine crashes!

https://user-images.githubusercontent.com/58845030/137552684-e21ae8b0-a92f-495e-aaae-7e0ada7da6f5.mp4

### Steps to reproduce

in order to reproduce I will do the same I did:

* Create a built-in script
* in the function _process
* type:
```gdscript
for i in range(4):
  var number = .5 # here when you type the dot the engine should crash

```

if this doesnt work try to do like in the video, which is an array of materials

### Minimal reproduction project

N/a

### LINKED ISSUE #55553: Godot 4 crashes when writing -. in a script
### Godot version

v4.0.dev.calinou [cf67f18ce]

### System information

Windows 10, Vulkan, NVIDIA - GeForce GTX 1650

### Issue description

When writing GDSript, writing "-." (minus dot) after another variable has Godot crash and close. Before crashing it shows 
image
in the command line.

### Steps to reproduce

Write a variable and `-.` in a "Script" window of GDScript type.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Scony**
Fixes #53862
Fixes #55553

### CODE REVIEW

**Comment by Scony** [comment]
@vnen 2min review here

**Comment by cdemirer** [comment]
This also fixes #55553.

**Review by vnen — APPROVED** [review]
LGTM. Sorry for the delay in the review.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
