### PR TITLE
debugger copy error now only copies error text

### LINKED ISSUE #5233: A way to copy error message without additional information
### Describe the project you are working on

this isn't really project dependent, it's a small debugger quality improvement so it would work benifit any project

### Describe the problem or limitation you are having in your project

Sometimes when getting an error message in the Errors section of the Debugger I want to copy the message so I can search for a solution on the internet or maybe send to someone etc.. but doing so copies not only the message itself but additional information like full path, file name and line number.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

what I would like to have is 2 options when right clicking a message:
"Copy Error", which copies the error message itself to the clipboard
"Copy Detailed Error" (or something like that), which copies the entire message including all the additional information

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

as stated before you would ideally have two seperate options to copy error message when you right click it in the Debugger

### If this enhancement will not be used often, can it be worked around with a few lines of script?

it is an editor feature so I don't think I can, and there is no editor plugin type that could add this functionality as far as I can tell

### Is there a reason why this should be core and not an add-on in the asset library?

not possible to have this feature in the asset library

### PR DESCRIPTION
**Pull request by DissonantVoid**
Fixes https://github.com/godotengine/godot-proposals/issues/5233

### CODE REVIEW

**Comment by xX-Void-Xx** [comment]
Callinou [recommended](https://github.com/godotengine/godot-proposals/issues/5233#issuecomment-1224282308) that I simply change the "Copy Error" option so that it only copies the error text and not other info, but I'm not sure if it's a better idea to add a new option that does that while keeping the "Copy Error" option as it is.
so in this pr I added a new option with the name "Copy Error Brief" that copies only the error message while I kept the "Copy Error" option as it was.
which method is better ? should we have 2 options or just one with the new functionality ?
also is "Copy Error Brief" a good name ?

**Comment by Calinou** [comment]
I don't think there should be two different options to copy text, as it can cause confusion and generally make usability worse for the 90% use case.

If you're a developer, you're probably running Godot from a terminal, so you can copy any messages that are printed easily.

**Comment by xX-Void-Xx** [comment]
yep that's reasonable, it's better to keep things simple and clean, got it !

**Comment by YuriSizov** [comment]
While we won't merge this for 4.0, keep in mind that this needs to be squashed into a single commit.

**Pull request closed without merging**
