### PR TITLE
Keep editable instances data when replacing tree root node

### LINKED ISSUE #4297: Replacing root node loses Editable Children data
**Operating system or device:**
Windows 10

**Issue description** (what happened, and what was expected):
Replacing the tree root node loses **Editable Children** data.

**Steps to reproduce:**
replace_node

**Link to minimal example project** (optional but very welcome):

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #4297

Ping @reduz since I am not sure if we want to expose `data.editable_instances` to outsiders :)

### CODE REVIEW

**Comment by volzhs** [comment]
wow, so fast fix.

**Comment by akien-mga** [comment]
> Ping @reduz since I am not sure if we want to expose data.editable_instances to outsiders :)

I guess we can merge, and decide if the function should be exposed to GDScript in a future PR?

**Comment by neikeq** [comment]
@akien-mga why would we want to expose it to GDScript? AFAIK it's only used by the scene tree dock.

**Comment by akien-mga** [comment]
I don't know, you were the one asking if it should be exposed to outsiders ;) Or did you mean only expose it to other C++ classes as a public method?

**Comment by neikeq** [comment]
Yes, that's what I meant :P

**Pull request merged**
