### PR TITLE
Make `replacing_by` emit slightly earlier

### LINKED ISSUE #73009: Editor freezes when changing node type Popup to AcceptDialog
### Godot version

4.0rc1

### System information

Windows11

### Issue description

After changing node type Popup to AcceptDialog the editor becomes unresponsive...
This only happens if the Popup node is the root node. If the Popup node is a child to other node the issue does not emerge.

### Steps to reproduce

Create new scene with Popup node as a root.
Change type to AcceptDialog

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Rindbee**
This mainly fixes bugs that occur when replacing scene roots with certain node types.

To reproduce the bug:
1. Create a new scene,
2. Add some visible 2D child nodes to the scene,
3. Select the scene root node, right-click to open the menu, select Change Type, and then select the Camera2D type to change.
4. The display of nodes in the 2D screen is offset.

| 248e5bfba | This PR |
| :----------: | :-----------: |
|  |  |

Fix #73009,

### CODE REVIEW

**Comment by ajreckof** [comment]
This is introducing a compatibility breakage. Codes that would be broken by this change can most likely just await tree_entered on the node sent with the signal. Another solution would be to defer the connection to the signal which would put the call after children have been moved.

**Review by ajreckof — APPROVED** [review]

**Comment by ajreckof** [comment]
To be clear even with the compatibility breakage I'm fully in favor of this being merged.

**Comment by KoBeWi** [comment]
I assume the problem is `set_edited_scene()` connected to `replacing_by` signal? Wouldn't it be enough to manually call `set_edited_scene()` when replacing root?
Also looks like the PR needs rebase, because it removes a file that doesn't seem to exist.

**Comment by Rindbee** [comment]
Some classes require us to check the current scene when entering the tree in order to improve the interactivity of the editor.

As for the situation when the node exits the tree, I forgot whether I have investigated it.

If no class needs to check the current scene when exiting, it is OK to manually call `set_edited_scene()` before `replace_by()`. However, in this case, it may be necessary to check whether the replaced node is the current scene root.

**Comment by KoBeWi** [comment]
> it may be necessary to check whether the replaced node is the current scene root.

That's what I mean. Whenever a node is being replaced (by scene tree dock action), check if it's the scene's root and set edited scene if it is.

**Comment by Rindbee** [comment]
The choice to use signal was made in #68599, presumably because `EditorNode::set_edited_scene()` might automatically add new node to the tree, which would then fail when calling `Node::replace_by()`.

https://github.com/godotengine/godot/blob/5f1184e93fe1021c86520460dc0a6619bff3c1fb/editor/editor_node.cpp#L3726-L3729

https://github.com/godotengine/godot/blob/5f1184e93fe1021c86520460dc0a6619bff3c1fb/scene/main/node.cpp#L2993

**Comment by KoBeWi** [comment]
So the solution is removing the node after setting it as scene 🙃
```C++
if (oldnode == edited_scene) {
	EditorNode::get_singleton()->set_edited_scene(newnode);
	newnode->get_parent()->remove_child(newnode);
}
```
It's best to avoid a core compatibility breakage due to editor issue.

**Comment by akien-mga** [comment]
Superseded by #92760.

**Pull request closed without merging**
