### PR TITLE
Rename "Clone Down" -> "Duplicate Line"

### LINKED ISSUE #36670: Duplicate Line missing shortcut setting
**Godot version:**
Godot_v3.2.1-rc1_x11.64

**Issue description:**
I've got CTRL+D set to Toggle Comment for scripts because that's what I'm used to from other editors and it's way more convenient than CTRL+K. There are several other settings for duplication in the rest of the editor (which I use with CTRL+D just fine). But I can find no shortcut setting for duplicating lines (which I don't need as a shortcut). So I can't easily toggle comments anymore.

Also: After resetting the Toggle Comment, I can't set it to CTRL+D again if any text editor is open (script or shader) because it detects only CTRL and then duplicates a line in the editor instead.

### PR DESCRIPTION
**Pull request by dreamsComeTrue**
That also requires adding new translations in PO files

Fixes #36670

### CODE REVIEW

**Comment by akien-mga** [comment]
I prefer not update .po and .pot files in PRs, I do this myself when syncing translations with Weblate.
Especially now, translations are kept in sync with the 3.2 branch/

**Comment by dreamsComeTrue** [comment]
> 
> 
> I prefer not update .po and .pot files in PRs, I do this myself when syncing translations with Weblate.
> Especially now, translations are kept in sync with the 3.2 branch/

Ok, so are we trashing that PR, or should I just left *.cpp change and those translations will be added later?

**Comment by akien-mga** [comment]
Keep the .cpp changes, just leave out `editor/translations/`.

**Comment by dreamsComeTrue** [comment]
Done as requested :)

**Review by Calinou — APPROVED** [review]

**Pull request closed without merging**
