### PR TITLE
Enhance TextureButton and TextureRect with resize

### PR DESCRIPTION
**Pull request by Geequlim**
Add STRETCH_KEEP_ASPECT_COVERED to TextureRect StretchMode
Make TextureButton to the same resize behavior with TextureRect

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks like I merged a bit fast (travis being regularly broken by other changes in the master branch doesn't help with CI), build now fails on X11 and Windows:
```
scene/gui/texture_button.cpp: In member function 'void TextureButton::_notification(int)':
scene/gui/texture_button.cpp:123:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:126:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:127:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:130:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:134:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:138:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:139:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:149:26: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:156:12: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_SCALE_ON_EXPAND' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_SCALE' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_TILE' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_KEEP' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_KEEP_CENTERED' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_KEEP_ASPECT' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_KEEP_ASPECT_CENTERED' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp:122:13: warning: enumeration value 'STRETCH_KEEP_ASPECT_COVERED' not handled in switch [-Wswitch]
scene/gui/texture_button.cpp: In static member function 'static void TextureButton::_bind_methods()':
scene/gui/texture_button.cpp:212:38: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:213:28: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:214:27: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:215:27: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:216:36: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:217:34: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:218:43: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp:219:42: error: 'StretchMode' is not a class or namespace
scene/gui/texture_button.cpp: In constructor 'TextureButton::TextureButton()':
scene/gui/texture_button.cpp:316:17: error: 'StretchMode' is not a class or namespace
```

**Comment by akien-mga** [comment]
I guess it's simpler/cleaner if you just reimplement the StretchMode enum in TextureButton instead of trying to proxy it from TextureRect :)

**Comment by Geequlim** [comment]
I have compile and tested the code on X11.
I have to make another PR to fix this?

**Comment by akien-mga** [comment]
> I have compile and tested the code on X11.

Maybe you're using clang which would be more forgiving in this case?

> I have to make another PR to fix this?

Yes, since this one is merged already.

**Comment by Geequlim** [comment]
OK I will check and make a new PR.

**Pull request merged**
