### PR TITLE
Fix a few issues with await in GDScript

### LINKED ISSUE #48830: await keyword bug
**Godot version:**

4.0

**OS/device including version:**

window10

**Issue description:**

```
func f1():
    await get_tree().process_frame

func _ready():
    await f1() # work ok
    f1() #parse error: Fuction "f1()" is a coroutine, so it must be called with "await"
```
In the latest GDScript reference,it say I can not use await to immediately execute next code.
**Steps to reproduce:**

**Minimal reproduction project:**

### LINKED ISSUE #49484: GDscript execute failed
### Godot version

v4.0.dev.calinou.cb8244273

### System information

Windows 10

### Issue description

捕获
await in 2 for loop execute failed and report: Trying to call an async fuction without "await"
only 1 for loop will execute ok.
please look the image.

### Steps to reproduce

1. Run the reproduction project
2. You will execute failed because the error reported.

### Minimal reproduction project

[AwaitTest.zip](https://github.com/godotengine/godot/files/6630665/AwaitTest.zip)

### LINKED ISSUE #49721: GDScript analyizer fails to interpret assignment of signal prefixed with await by its arguments
### Godot version

9b0800cbf92f4165de2981f34dab6a55201fdcd9

### System information

Windows 10

### Issue description

When you use the keyword ```await``` in front of a signal and attempt to assign the result to a variable, the script analyzer will interpret the result as a signal rather than its arguments, which would make it a variant despite internally this being a valid logic flow.
godot windows tools 64_Sdjw1pmUS1
The analyzer presumably needs special-case handling for signals prefixed with an await to treat them not as signals, but their results.

### Steps to reproduce

Write the line such as ```var result = await some_signal``` and they try to evaluate it as a variant ```if result == true:```. This will trip an error like the one shown in the description.

### Minimal reproduction project

[testgd4.zip](https://github.com/godotengine/godot/files/6679544/testgd4.zip)

### LINKED ISSUE #50894: Await on non-coroutine function does not return value
### Godot version

4.0 dev

### System information

Mac OSX 11.1

### Issue description

Calling await on a non-coroutine function returns a null value, no matter what is passed back from the function. This can be problematic if you do not know if the function is a coroutine or not when calling it. It would seem that a non-coroutine function should always return their value, whether await is used or not. Awaiting the non-coroutine function means waiting until it is finished (which would be at the last line in the function), correct?

### Steps to reproduce

func _ready():
	var functions: Array[Callable]
	functions.append(Callable(self, "func_a"))
	functions.append(Callable(self, "func_b"))
	var results = []
	for function in functions:
		results.append(await function.call())
	for i in range(results.size()):
		print("%s: %s" % [i, results[i]])

func func_a():
	return "a"

func func_b():
	await get_tree().create_timer(0.1).timeout
	return "b"

// returns:
// 0: Null
// 1: b
//
// should return:
// 0: a
// 1: b

### Minimal reproduction project

[AwaitTest.zip](https://github.com/godotengine/godot/files/6878964/AwaitTest.zip)

### PR DESCRIPTION
**Pull request by vnen**
Fix #48830
Fix #49484
Fix #50894
Fix #49721

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by vnen** [comment]
> See [this](https://github.com/godotengine/godot-proposals/issues/3469#issuecomment-952297911) and [this](https://github.com/godotengine/godot/pull/39093#issuecomment-636367570). As I understand it, an async function called without `await` should return a signal. Or was it decided to abandon it during the implementation process?

That was not the case, I never intended coroutines to return signals. The only thing is that if a function does return a signal, it can be "awaited" (that is, it can make the current function wait until the signal is emitted).

This PR is about the case in which you don't use the return value of the coroutine, so you can call it without waiting for the final result. If you do need the result, then you have to wait until it's completed.

**Comment by dalexeev** [comment]
@vnen Thank you, I agree. But this is what remains:

> In any case, I find the error message somewhat confusing, as an async function _can_ be called without `await`, at least in the statement context.

> ```gdscript
> var t = async_func() # Function "async_func()" is a coroutine, so it must be called with "await".
> ```
>
> ```gdscript
> var t = async_func.call() # Runtime error: Trying to call an async function without "await".
> ```

**Comment by vnen** [comment]
@dalexeev the message can be improved, but please open an issue about it, because comments on closed PRs tend to be forgotten.

**Pull request merged**
