### PR TITLE
GDScript: tweaks for randi() and randf()

### PR DESCRIPTION
**Pull request by ghost**
What this PR suggests is basically redundant functionality - still, having dedicated builtins for `randf()` and `randi()`, they could be more versatile with their arguments:

| current form in GDScript  | alternative suggested by this PR |
| ------------------------- | ---------------------------- |
| randf() | randf() |
| x * randf() | randf(x) |
| rand_range(x, y) | randf(x, y) | 
| randi() | randi() |
| randi() % x | randi(x) |
| x + randi() % (y - x) | randi(x, y) |

Also, the docs to `seed()` could use a reference to `randomize()`, as many libraries understand `seed()` without arguments to behave like `randomize()` in Godot.

### CODE REVIEW

**Comment by puppetmaster-** [comment]
For me it would be even more clearer if the range function would remain and for int you would add an additional one.

- randf_range(x,y)
- randi_range(x,y)

**Comment by poke1024** [comment]
`rand_range` will remain in any case, since we cannot break backward compatibility AFAIK.

**Comment by Sslaxx** [comment]
Oh _please_, could we **finally** have a `randi_range` function in GDScript?

**Comment by akien-mga** [comment]
As mentioned above, since those changes would break compatibility and might be better suited eventually as part of the `RandomNumberGeneration` class (#19369), we've decided not to merge this PR. Thanks for the proposal though, and I think the suggested APIs will be useful to determine what to implement in the RNG class.

**Pull request closed without merging**
