### PR TITLE
Fix KEY_KP_ENTER not working as KEY_ENTER on the editor

### LINKED ISSUE #9843: Enter Key does not save Property values in Inspector
**Operating system or device - Godot version:**
MacOS 10.12.6
Godot 2.1.3.stable.official

**Issue description:**

When editing values in the Inspector, pressing the Enter key (on the number pad) does not save the edited value.

Pressing the Enter key should save the new property value the same way as using the Return key.

**Steps to reproduce:**
Alter a property value in the Inspector and press the Enter key on the Number pad.

Given that most properties are numeric, anyone with a full NumPad keyboard will encounter this issue almost immediately.

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes #9843.

### CODE REVIEW

**Comment by Noshyaar** [comment]
Conflict with #9871?

**Comment by akien-mga** [comment]
Indeed, we've established that `KEY_KP_ENTER` is superfluous, and #9872 removes it in master. For 2.1, to avoid breaking compatibility, #9871 just fixes the incorrect OSX binding.

**Comment by marcelofg55** [comment]
@akien-mga I see, isn't it a different key though? I'm used to games being able to map different actions to Enter and to NumPad Enter.

**Comment by Noshyaar** [comment]
Enter is KEY_RETURN.

**Comment by bruvzg** [comment]
- On Windows both Enter and Num Enter are KEY_RETURN (native keycode VK_RETURN), no KEY_ENTER or KEY_KP_ENTER defined;

- On Linux/X11 Enter is KEY_RETURN (XK_Return), Num Enter is KEY_ENTER and KEY_KP_ENTER (same keycode XK_KP_Enter, get_keycode() return KEY_ENTER);

- On macOS Enter is KEY_RETURN (0x24), Num Enter is KEY_KP_ENTER (0x4c), no KEY_ENTER defined.

**Comment by marcelofg55** [comment]
@bruvzg It's possible to determine If the key pressed is Enter/Return or NumPad Enter on windows as well, using the extended flag of the WM_KEYDOWN event, when lParam bit 24 is 1 it's possible to check for NumPad Enter (https://msdn.microsoft.com/en-us/library/windows/desktop/ms646280(v=vs.85).aspx).

**Comment by bruvzg** [comment]
Yep windows ["os_windows.cpp"](https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L808) and UWP ["app.cpp"](https://github.com/godotengine/godot/blob/master/platform/uwp/app.cpp#L420) need to be fixed.

`key_args->KeyStatus.IsExtendedKey` for UWP
https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core.KeyEventArgs

**Comment by marcelofg55** [comment]
Yeah I think it would be nice to fix it, in my opinion we shouldn't remove the KEY_KP_ENTER

**Comment by akien-mga** [comment]
@marcelofg55 KEY_ENTER and KEY_KP_ENTER were the same thing: the numpad Enter key.
The main Enter/Return key (below Backspace) is KEY_RETURN.

**Comment by bruvzg** [comment]
@marcelofg55 KEY_KP_ENTER is redundant, KEY_RETURN for main Enter and KEY_ENTER for Numpad

**Comment by marcelofg55** [comment]
Oh alright, sorry for confusion :)

**Pull request closed without merging**
