### PR TITLE
Added workaround for Linux/DRI3 stuttering.

### PR DESCRIPTION
**Pull request by bnpfeife**
see: https://github.com/godotengine/godot/issues/15146

### CODE REVIEW

**Comment by Zireael07** [comment]
Why close?

**Comment by bnpfeife** [comment]
Sorry, I haven't had any experience working on repositories where I'm not a collaborator. I thought that I had to submit a new pull request if it failed a test.

**Comment by Noshyaar** [comment]
Thanks for contributing! Would you mind squashing commits together? ([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request))

**Comment by bnpfeife** [comment]
Sure, I've squashed them into one commit.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by reduz** [comment]
This was superseded by the jitter fix, so closing

**Pull request closed without merging**
