### PR TITLE
AnimationPlayer FPS mode fixes

### PR DESCRIPTION
**Pull request by ghost**
- Fix inserting and moving keys in FPS mode (this was really broken... try it out for yourself)
- Change animation time tooltip when toggling snap mode
- Set animation length slider step to 1 when in FPS mode

I don't know the full implications of my changes so please review thoroughly.

### CODE REVIEW

**Comment by homer666** [comment]
Don't merge yet, inserting keys via right-click menu is still busted.

**Comment by homer666** [comment]
Alright, fixed that.

**Comment by hpvb** [comment]
Thanks!

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.

**Pull request merged**
