### PR TITLE
Set editor hint for the project manager

### LINKED ISSUE #21823: Godot fails to load config and creates a new one every time.
The the 3.1 alpha f1e5b7c build, it seems like the editor is no longer able to make good use of the editor settings file.  I've wiped it out, and it doesn't even like the new one it creates when I reopen to the project screen.

godot_master_2018-09-07_05-52-37

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #21823.

### CODE REVIEW

**Comment by akien-mga** [comment]
The bug doesn't affect 3.0 (yet), but this could be cherry-picked anyway for consistency and to prevent the bug from happening if f1e5b7cf was ever cherry-picked.

**Comment by akien-mga** [comment]
If this gets cherry-picked, c0df3b14 should go with it.

**Comment by avencherus** [comment]
Nice.  Rebuilding immediately!  XD

This one has been a surprisingly major source of pain.

**Comment by AlexHolly** [comment]
Is it possible that this is still broken for the server platform?

```
ERROR: set_locale: Invalid locale: C
   At: core/translation.cpp:943.
ERROR: instance: Class 'EditorSettings' can only be instantiated by editor.
   At: core/class_db.cpp:518.
ERROR: poll: /root/.config/godot/editor_settings-3.tres:3 - Parse Error: Can't create sub resource of type: EditorSettings
   At: scene/resources/scene_format_text.cpp:560.
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:153.
ERROR: _load: Failed loading resource: /root/.config/godot/editor_settings-3.tres
   At: core/io/resource_loader.cpp:190.
WARNING: create: Could not open config file.
   At: editor/editor_settings.cpp:845.
WARNING: grab_focus: This control can't grab focus. Use set_focus_mode() to allow a control to get focus.
   At: scene/gui/control.cpp:2067.
```

**Comment by akien-mga** [comment]
I'll have a look. I'd advise not to run Godot as root btw...

**Comment by akien-mga** [comment]
Works fine for me:
```
./bin/godot_server.server.tools.64 --path /home/akien/tmp/godot/test/v3.1_test/
30
1
```
(those prints are just debug stuff in my test project)

**Comment by AlexHolly** [comment]
I was not specific enough :(
I use CI to export my projects(thats why root should be fine)
This is the command I use(tested locally same result)
`./../godot_server.server.tools.64 --path ./ --export "Linux/X11" ./../exports/test.x86_64`

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7. (Together with c0df3b147.)

**Pull request merged**
