### PR TITLE
fix editor top dark box

### PR DESCRIPTION
**Pull request by masoudbh3**
before:
before
after:
after

### CODE REVIEW

**Comment by bojidar-bg** [comment]
:+1:

**Comment by jackmakesthings** [comment]
:+1:

**Comment by akien-mga** [comment]
Good to merge IMO.

**Comment by okamstudio** [comment]
Will merge ndee's theme soon though

**Comment by akien-mga** [comment]
> Will merge ndee's theme soon though

Will it override the current theme, or be proposed as an alternative?

**Comment by akien-mga** [comment]
> Will merge ndee's theme soon though

IMO it would be nice to merge this PR anyway since it doesn't seem to conflict so far, in case @ndee85's theme doesn't take into account this very detail. Unless it would make your implementation work harder of course.

**Comment by reduz** [comment]
top black zone was removed recently, so closing this

**Pull request closed without merging**
