### PR TITLE
x11: Add support for filesystem drag & drop using xdnd

### PR DESCRIPTION
**Pull request by 27thLiz**
Accepting only the `text/uri-list` type for now, as it seemed the most common to me.

Tested with the following File managers:
- Dolphin
- Thunar
- Whatever the e20 one is called

and these DEs:
- KDE Plasma 5.6
- Cinnamon
- Enlightenment

All on Arch Linux, kernel 4.5, Xorg 18.3

~~The only one that didn't work was Nemo (on all WMs)... it seems not to send XdndEnter events to our window. I have no idea what's happening there yet.~~ **Edit:** Nemo works now, as does PCManFM

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm testing on Mageia 6, Plasma 5.6 with Dolphin, but somehow I don't manage to make it work. Maybe I misinterpreted what is supposed to be working, could you give an example of a successful drag and drop (to or from the file manager, what file type)?

**Comment by Hinsbart** [comment]
Well, the drop is kinda like a shortcut for importing. So everything that you can import via the import submenus, you could also drop into the engine now.
Try it with a .png, that should make the Texture import popup show.

**Comment by akien-mga** [comment]
Alright that works fine, thanks :)
The only missing thing might be to support .tscn/.scn/.xscn import via the "Import > Scene".

There used to be "Import > Nodes from Scene" too but it got removed recently apparently.

**Comment by akien-mga** [comment]
Tested:
- Dolphin from Plasma 5: **OK**
- Double Commander 0.6.6 (Lazarus/FPC file manager), Qt 4: **OK**
- Double Commander 0.6.6 (Lazarus/FPC file manager), GTK+2: **OK** (not always, but it's a bug of the application itself IMO as it does not always allow dragging outside its window)
- Firefox GTK+3 file browser (e.g. when clicking "Browse.." on a file upload page)
- PCManFM from LXDE: **NOK**
- PCManFM-Qt from LXQt: **OK**

Pretty good so far :)

**Comment by Hinsbart** [comment]
@akien-mga Alright, I fixed the issue with Nemo. PCManFM (gtk) should also work now :)

**Comment by akien-mga** [comment]
You rock :D

**Comment by akien-mga** [comment]
I confirm that it now works with PCManFM (gtk).

**Comment by reduz** [comment]
@Hondres since we are at it, I just added a function  OS::get_screen_dpi(int screen=0)
do you think you could make it work in X11?

**Comment by Hinsbart** [comment]
@reduz I'll have a look at it

**Pull request merged**
