### PR TITLE
Add XR Environment Blend Mode Support

### PR DESCRIPTION
**Pull request by rbessems**
Adds support for controlling the XR Environment Blend mode.

```
var acceptable_modes = [ XRInterface.XR_ENV_BLEND_MODE_OPAQUE, XRInterface.XR_ENV_BLEND_MODE_ADDITIVE ]
var modes = xr_interface.get_supported_environment_blend_modes()
for mode in acceptable_modes:
	if mode in modes:
		xr_interface.set_environment_blend_mode(mode)
		break
```

Also cleans up the openxr_util.cpp file by leveraging the OpenXR reflection header.

### CODE REVIEW

**Review by m4gr3d — COMMENTED** [review]
Looks good to me!

**Review by BastiaanOlij — APPROVED** [review]
Nice! Love the cleanup of our enum helpers, macros for the win :)

**Comment by BastiaanOlij** [comment]
@m4gr3d I'm not sure if this is just different for pure AR devices like the ML2 where we don't have a pass through image, do you think we need a little more information in the documentation setting up pass through?

Maybe that is something we need a separate page for on the documentation website, we probably need a page for pass through anyway, but I think with the pass through extension of Meta things work slightly differently.

Anyway, that's besides the point of this PR, being able to set the blend mode of the main presentation layer was highly needed.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
