### PR TITLE
[Mono] Add Vector2i and Vector3i and Rect2i

### PR DESCRIPTION
**Pull request by aaronfranke**
This is a subset of #22205 which only adds these types to C# (plus the marshaling code), since reduz has already added them in core.

This should likely wait until after @neikeq gets C# working in master again, but the C# files work fine by themselves, and I'm fairly sure the C++ code is good to go, so I'm opening this now.

Also, alphabetize Vector2.Cross, and optimize Vector2.Reflect by doing all scalar math first.

### CODE REVIEW

**Review by neikeq — APPROVED** [review]

**Comment by aaronfranke** [comment]
@neikeq For some reason this compiles but doesn't run. I get the error message:

```
ERROR: Mono Cache: Member cached_data.class_Vector2i is null.
   at: (modules\mono\mono_gd\gd_mono_cache.cpp:235)
ERROR: Failed to load one of the prebuilt API assemblies.
   at: (modules\mono\mono_gd\gd_mono.cpp:903)
CrashHandlerException: Program crashed
```

All of the C++ code in this PR was created by copy-pasting the code for Vector2/Rect2/Vector3 and then changing it to work with integers. I don't know why `cached_data.class_Vector2i` is null because I don't know where the code is that makes `cached_data.class_Vector2` *not* null. I've looked over this for an hour and I can't figure out what to do, so I'll let you finish this up.

**Comment by neikeq** [comment]
Did you regenerate the glue?

**Comment by aaronfranke** [comment]
Yes, this is the script I use. There don't seem to be any errors before runtime.

```
scons -j6 p=windows tools=yes module_mono_enabled=yes mono_glue=no
./bin/godot.windows.tools.64.mono.exe --generate-mono-glue modules/mono/glue
scons -j6 p=windows tools=yes module_mono_enabled=yes mono_glue=yes
```

**Review by neikeq — APPROVED** [review]

**Comment by neikeq** [comment]
Thanks! :)

**Pull request merged**
