### PR TITLE
Revert "Fix selecting popup menu items on mouse release"

### LINKED ISSUE #88324: Editor: The popups selecting menu options on mouse move
### Tested versions

Bug introduced by this commit: 06c2cda848b4bca8ee2f54a09417a97a7c1384d3

### System information

macOS 14.1, Apple M3 Pro

### Issue description

~When editing an exported `Dictionary` property, trying to change the type of a property opens a popup to chose the new type.~

In fact, this seems to be the case of every popup menus. The right click menus for example have the same problem, if you maintain the right click and drag over a menu item, this menu item will be clicked once you start moving the mouse again after releasing the mouse button.

If the mouse doesn't immediatly move after clicking of the edit button, the popup will close itself when the mouse begins to move, using whatever type is under the mouse as the selected type.

### Steps to reproduce

 - Create a script with an exported dictionary
 - Add this script to a node
 - Open inspector for this Node
 - Edit dictionary
 - Click on the ✎ button
 - Don't move the mouse for ~1s
 - Move the mouse

https://github.com/godotengine/godot/assets/3855602/f460ea12-4b91-4a24-89ef-cf220229216e

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by EmrysMyrddin**
This reverts commit 06c2cda848b4bca8ee2f54a09417a97a7c1384d3.

fixes #88324 

It's not clear why this was done this way, but reverting this commit is actually fixing the linked issue.
Not sure what was supposed to be broken in the first place.

* *Bugsquad edit, reverts: #86952*

### CODE REVIEW

**Comment by KoBeWi** [comment]
Outright reverting the PR is not a proper fix, especially when it was merged so recently.

**Comment by EmrysMyrddin** [comment]
I understand, It's more like a starting point. But this change actually broke every Godot's popup. And since there is no issue linked to the original PR, it's difficult to understand what was the purpose of the changes.

Perhaps @ryevdokimov you can help me understand what was the goal of the PR ?

**Comment by ryevdokimov** [comment]
The PR was to fix/introduce a very common functionality of being to select popup menu options with one cycle of a mouse click. I am having trouble reproducing this issue, so I suspect it might be OS specific (I'm on Windows).

**Comment by KoBeWi** [comment]
> I understand, It's more like a starting point.

A starting point is opening an issue, which you already did. The problem should be discussed in the issue.

> The PR was to fix/introduce a very common functionality of being to select popup menu options with one cycle of a mouse click.

The functionality has existed in Godot 3 and was lost sometime during DisplayServer refactor. The code was still there, it just wasn't functional. So it was more a bugfix.

**Comment by EmrysMyrddin** [comment]
After some tests, I still don't understand what the change was supposed to fix.
It introduces 3 bugs:
 - If the popup opens under the mouse (which is arguably a bad UI pattern but it exists in multiple places in Godot), moving the mouse after a 250ms delay will activate the menu item hovered by the mouse
 - If the menu opens with a click (right or left) and the mouse button is not released before the mouse goes over the menu, the menu item hovered by the mouse after the button release will be activated on next mouse movement.
 - The menu items are now activated on button down instead of button up, which means:
 	- You can't click on an item and drag your mouse over another if you changed your mind
 	- You can't cancel a click on a menu item by dragging outside of the menu popup

The 2 last items are very confusing since it's not how every native menus are working. It breaks users assumption about how to interact with the UI.

**Comment by ryevdokimov** [comment]
This should probably be discussed under the issue you created, so we don't have to jump back and forth.

**Pull request closed without merging**
