### PR TITLE
Added missing property "size" to VisualShaderNodeGroupBase

### PR DESCRIPTION
**Pull request by Chaosus**
I think I missed it when created this node...

### CODE REVIEW

**Comment by akien-mga** [comment]
Can you sync doctool too?

**Comment by Chaosus** [comment]
Ah ok..

**Comment by akien-mga** [comment]
To clarify, I just mean running `godot --doctool .` to generate the `size` property in the docs (and it should also remove the setter and getter).

**Comment by Chaosus** [comment]
Done. I need to remember that `doctool` workflow.

**Pull request merged**
