### PR TITLE
Windows: Hide the mouse cursor when MOUSE_MODE_CAPTURED is activated.

### PR DESCRIPTION
**Pull request by hurikhan**
The reference of the [Input class](http://docs.godotengine.org/en/latest/classes/class_input.html#numeric-constants) constants states:

> **MOUSE_MODE_CAPTURED**: Captures the mouse. The mouse will be hidden and unable to leave the game window. But it will still register movement and mouse button presses.

This pull request will hide the mouse cursor on `Input.set_mouse_mode(MOUSE_MODE_CAPTURED)` and shows it on `Input.set_mouse_mode(MOUSE_MODE_VISIBLE)`.

### CODE REVIEW

**Comment by mattiascibien** [comment]
@hurikhan guess I missed this when working with this. Nice catch :)

**Comment by vnen** [comment]
Works for me.

**Comment by akien-mga** [comment]
What about the other platforms? Do they already have the same behaviour?

**Comment by hurikhan** [comment]
@mattiascibien Thanks, it was an easy catch for me. I am just creating some kind of FPS. So this mouse cursor in front of your nose looks a little bit strange.
@vnen Thanks for review.
@akien-mga I only can speak for the X11 platform. X11 works for me.

On a second look onto the implementation of  [set_mouse_mode()](https://github.com/hurikhan/godot/blob/f0b6a242cc1934fb15c53e3e1724451c397bcb8b/platform/windows/os_windows.cpp#L1351-L1374) for windows, I see, that the constant [MOUSE_MODE_HIDDEN](http://docs.godotengine.org/en/latest/classes/class_input.html#numeric-constants) is not evaluated. I can fix this in a new pull request. Let's behave atomic.

Tomorrow i will extend the [window_management](https://github.com/godotengine/godot-demo-projects/tree/master/misc/window_management) demo to include such kind of test case.

**Pull request merged**
