### PR TITLE
ThorVG: Sync with upstream 0.8.0

### LINKED ISSUE #58898: Upgrade ThorVG to v0.8.0
### Godot version

f470979732513436124c01a465b22f948637b5fa

### System information

Fedora 35, Nvidia 3000 series

### Issue description

You interested in updating this one? @AnilBK

https://github.com/Samsung/thorvg/releases/tag/v0.8.0 has released

Update thorvg to v0.8.0.

Replace url in thorvg (linux) upgrade script to "0.8.0"

Update `thirdparty/README.md`

Do a visual confirmation that nothing obvious in the editor startup broke.

[](https://github.com/Samsung/thorvg/releases/tag/v0.7.1)https://github.com/godotengine/godot/blob/master/thirdparty/thorvg/update-thorvg.sh

### Steps to reproduce

Launch godot to check it is the older version.

### Minimal reproduction project

Not applicable.

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/58898

### CODE REVIEW

**Comment by fire** [comment]
Checking on a bug https://github.com/Samsung/thorvg/issues/1205 upstream.

**Review by akien-mga — CHANGES_REQUESTED** [review]
Looks good, just one thing: please bump the copyright version in `COPYRIGHT.txt` too:
```diff
diff --git a/COPYRIGHT.txt b/COPYRIGHT.txt
index df1ab0c849..7f6c9b3dc0 100644
--- a/COPYRIGHT.txt
+++ b/COPYRIGHT.txt
@@ -399,7 +399,7 @@ License: Expat
 
 Files: ./thirdparty/thorvg/
 Comment: ThorVG
-Copyright: 2020-2021, Samsung Electronics Co., Ltd.
+Copyright: 2020-2022, Samsung Electronics Co., Ltd.
 License: Expat
 
 Files: ./thirdparty/tinyexr/
```

**Review by akien-mga — APPROVED** [review]
Meant to click "Approve".

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
