### PR TITLE
import fixes

### LINKED ISSUE #12866: OBJ mesh does not receive updates when it must
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
(tested on linux), latest master

**Issue description:**
 The OBJ mesh resources does not receive update when re-export from Blender happen. After first automatic import, it cannot be updated even by using reimport button. Only after complete delete asset and export from Blender again, mesh gets its update.

### PR DESCRIPTION
**Pull request by djrm**
fixed mesh importing with multiple material, this is quite important since the previous version caused crashes. closes #12866

edit:
also improved the packed scene preview, not much but i think they are clearer now

BEFORE
screenshot from 2017-11-17 21-41-39

AFTER
screenshot from 2017-11-17 21-40-27

### CODE REVIEW

**Comment by reduz** [comment]
It shouldn't be slow in 3.0, it would be better to find why it is slow if
this is the case

On Nov 17, 2017 8:13 PM, "Daniel Ramirez" <notifications@github.com> wrote:

i noticed that updating the scene preview in every save was a bit slow, so
i removed that behavior, i think a better way would be to have some timer,
so only after certain time the preview updates.

Also fixed mesh importing with multiple material, this is quite important
since the previous version caused crashes.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/godotengine/godot/pull/13000
Commit Summary

   - Do not update scene preview in every save
   - Fixed mesh importing when multiple materials are present

File Changes

   - *M* editor/editor_node.cpp
   <https://github.com/godotengine/godot/pull/13000/files#diff-0> (11)
   - *M* editor/editor_node.h
   <https://github.com/godotengine/godot/pull/13000/files#diff-1> (2)
   - *M* scene/resources/mesh.cpp
   <https://github.com/godotengine/godot/pull/13000/files#diff-2> (10)

Patch Links:

   - https://github.com/godotengine/godot/pull/13000.patch
   - https://github.com/godotengine/godot/pull/13000.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/pull/13000>, or mute the thread

**Comment by djrm** [comment]
@reduz it is quite noticeable, and that functionality was not there before, i added it, so for now im removing it until i find a better solution or as you say the root cause of the problem.

**Comment by reduz** [comment]
I definitely dont want it removed unless it can be sped up. Also, this functionality is in 2.1 too, and it was even slower.

**Comment by djrm** [comment]
@reduz ok, will put it back with some minor improvements, the delay is actually not that bad, in my computer goes from saving is super fast, to showing a message for 1-2 seconds.

**Comment by reduz** [comment]
what could be slow is getting the whole screen buffer in high res and/or
resizing it. Worst case we resize it on GPU then retrieve it.. but it may
be something else.

**Comment by djrm** [comment]
@reduz i improved the packed scene preview, but i had to add a version of crop that accepts coordinated, so i can select the center of the image.

**Comment by djrm** [comment]
@reduz, maybe its not that slow after all, it may be only that it shows the saving progess while just saving doesnt

**Pull request merged**
