### PR TITLE
Optional polygon 2D editor single click editing

### PR DESCRIPTION
**Pull request by ghost**
Following the discussion in https://github.com/godotengine/godot/pull/12740, this makes the whole new single click editor introduced in #10618 optional and it's no longer the default. The default is now the pre-10618-state of things with the additional ability to add and remove point using double clicking.

If single click editing is enabled in the editor options, it is now improved by adding a new one-click-delete (i.e. just click once on point to delete) that is the logical conclusion of #10618.

In both modes, the "delete point" button is now removed, as it's not needed in either mode.

### CODE REVIEW

**Comment by reduz** [comment]
what is the problem with the current mode? (not sure if i missed something)

**Comment by poke1024** [comment]
I hope @groud is ok with quoting him from https://github.com/godotengine/godot/pull/12740:

> I personally think this one click editing is not that useful, having to draw a lot of points in a polygon is a really rare use case. It would make sense in a drawing software like Inkscape, as it would speed up the workflow. But in our case people will generally rather be precice that fast.

As an answer to that, this PR moves one-click-editing to an option for those who find it incredibly useful (me + anyone?) and want even more of it - namely also deleting points with one click (not there in HEAD but in this PR) - and yet doesn't strain the nerves of those who feel that this is a wrong direction.

**Comment by reduz** [comment]
I don't generally like the idea of providing this kind of flexibility to
hidden options, it should just work properly and be consistent.

We could, instead, for example, modify the polygon editor and add support
for selecting and moving many handles at once, and also make them deletable
with delete key

**Comment by poke1024** [comment]
@reduz Ok, I’ll close this PR then.

I already added selection of points and deletion via delete keys in https://github.com/godotengine/godot/pull/10618.

**Pull request closed without merging**
