### PR TITLE
SCons: Fix Python 3.12 SyntaxError with regex escape sequences

### PR DESCRIPTION
**Pull request by akien-mga**
I ran into errors with these on a Fedora 39 container.

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
Seems like a correct usage of r-strings.

**Comment by akien-mga** [comment]
Cherry-picked for 4.1.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.4.

**Pull request merged**
