### PR TITLE
Rename Array, Dictionary and Variant.duplicate() to copy()

### PR DESCRIPTION
**Pull request by madmiraal**
Does the same internally for `Vector<>`, which includes all `PackedArray` types.

Part of #16863.

Note: The [original suggestion](https://github.com/godotengine/godot/issues/16863#issuecomment-441376010) suggested either `copy()` or `clone()` and #16863 actually suggests `clone()`, but all the documentation uses the work "copy" in the descriptions; so I think it makes more sense to use `copy()`.

### CODE REVIEW

**Comment by aaronfranke** [comment]
The problem with `copy` is that it's too imprecise of a word, it can be interpreted as copying a reference, while `clone` implies a brand new array with the same contents.

**Comment by madmiraal** [comment]
> The problem with copy is that it's too imprecise of a word, it can be interpreted as copying a reference, while clone implies a brand new array with the same contents.

I think this is even more reason why `copy` is a better name for the methods. If you want to clone it i.e. copy the data too, you need to set the 'deep' parameter to `true`.

**Comment by madmiraal** [comment]
Rebased following 4ca1e73ff9ae4.

**Comment by madmiraal** [comment]
Rebased following merge of #46991 and #47166.

**Comment by madmiraal** [comment]
Updated documentation with `--doctool .`.

**Comment by madmiraal** [comment]
Rebased following 29775a1714d01f35570ef708d24a1cde77aa1a5a.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting today and the consensus was that we didn't see much value in the rename. `duplicate()` is quite explicit and matches language used in the editor too (Duplicate Node, Duplicate Resource, etc.).

As long as we're consistent in our own API, I think keeping `duplicate()` is fine.

**Pull request closed without merging**
