### PR TITLE
Borderless windows

### PR DESCRIPTION
**Pull request by SaracenOne**
Adds borderless window support to the Windows build of the engine. Also centers the window by default.

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you maybe merge the second commit into the first one using ```git rebase -i HEAD~2```? Once a commit is pushed to the main repo this kind of hotfix commits are of course needed, but for a pull request it's best to get it right from the start since you can rebase as much as you want in your fork (else I guess a ```git bisect``` landing on 86b2027 would fail for example).

**Comment by SaracenOne** [comment]
The issues you raised should be resolved now. Still figuring out how to properly use the rebase command, but this should at least be alright now.

**Comment by akien-mga** [comment]
We merged a big pull request that removed all trailing spaces in the code, so it introduced merge conflicts with your PR. Could you have a look at rebasing it to solve the merge conflicts?

**Comment by SaracenOne** [comment]
This one should be resolved now too :)

**Comment by SaracenOne** [comment]
Sorry, which line was it. I can resubmit it if you want.

**Comment by SaracenOne** [comment]
Ah, I see them now. Strange, these things didn't show up when I did the rebase.

**Comment by SaracenOne** [comment]
Okay, whitespace issues are sorted here now.

**Comment by akien-mga** [comment]
Thanks! :)

**Comment by akien-mga** [comment]
Oops, I assumed that your PR would be working as we have travis CI performing tests on all PRs, but apparently this one was created before we configured travis. It seems to break on all platforms, could you have a look? https://travis-ci.org/godotengine/godot/builds/115544726

**Comment by akien-mga** [comment]
Should be fixed with 801221d.

**Pull request merged**
