### PR TITLE
Draw arcs to indicate angles being measured by ruler

### PR DESCRIPTION
**Pull request by ajweeks**
This PR adds a helper function to draw arcs and uses it to show the angles that the ruler tool measures.

### CODE REVIEW

**Comment by Zireael07** [comment]
Please expose the draw_arc function to GDScript. I find myself drawing arcs A LOT.

**Comment by clayjohn** [comment]
Take a look at ``_bind_methods()`` and see how you bind new functions to GDScript. 

https://github.com/godotengine/godot/blob/119bf237209414a49879fba40459f22315ab1467/scene/2d/canvas_item.cpp#L1103-L1236

**Comment by ajweeks** [comment]
What might be causing that build error?

**Comment by Calinou** [comment]
@ajweeks It seems like it's an unrelated SCons cache issue, you can ignore it: https://travis-ci.org/godotengine/godot/jobs/600124487

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
