### PR TITLE
[3.x] Fix TouchScreenButton not redrawn when texture changes

### PR DESCRIPTION
**Pull request by timothyqiu**
`3.x` version of #75016

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by AThousandShips** [comment]
Is the issue in 4.x relevant?
* https://github.com/godotengine/godot/pull/77161

**Comment by AThousandShips** [comment]
Would you mind co-authoring me as:
"Co-authored-by: A Thousand Ships <96648715+AThousandShips@users.noreply.github.com>"
Thank you

**Comment by AThousandShips** [comment]
Thank you!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
