### PR TITLE
astcenc: Fix build with SSE3 but no SSSE3

### LINKED ISSUE #71700: ASTCENC update breaks compiling on Windows with MinGW
### Godot version

master (commit 360b61084a4a5bc0f9577212a3079430601b3408 (HEAD -> master, origin/master, origin/HEAD))

### System information

Windows 11

### Issue description

Seems that this commit (https://github.com/godotengine/godot/commit/696346f4cc63b9395cc156da0e8d8fb65260c055) breaks building on windows.

```

=====
In file included from C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/immintrin.h:37,
                 from thirdparty\astcenc\astcenc_mathlib.h:85,
                 from thirdparty\astcenc\astcenc_internal.h:34,
                 from thirdparty\astcenc\astcenc_decompress_symbolic.cpp:22:
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h: In function 'vint4 vtable_8bt_32bi(vint4, vint4, vint4)':
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to 'always_inline' '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
  136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~
In file included from thirdparty\astcenc\astcenc_vecmathlib.h:96,
                 from thirdparty\astcenc\astcenc_mathlib.h:433:
thirdparty\astcenc\astcenc_vecmathlib_sse_4.h:1112:43: note: called from here
 1112 |         __m128i result2 = _mm_shuffle_epi8(t1.m, idxx);
      |                           ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to 'always_inline' '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
  136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~
thirdparty\astcenc\astcenc_vecmathlib_sse_4.h:1109:42: note: called from here
 1109 |         __m128i result = _mm_shuffle_epi8(t0.m, idxx);
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to 'always_inline' '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
  136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~
thirdparty\astcenc\astcenc_vecmathlib_sse_4.h:1109:42: note: called from here
 1109 |         __m128i result = _mm_shuffle_epi8(t0.m, idxx);
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to 'always_inline' '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
  136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~
thirdparty\astcenc\astcenc_vecmathlib_sse_4.h:1112:43: note: called from here
 1112 |         __m128i result2 = _mm_shuffle_epi8(t1.m, idxx);
      |                           ~~~~~~~~~~~~~~~~^~~~~~~~~~~~

=====
=====
In file included from C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/immintrin.h:37,
                 from thirdparty\astcenc\astcenc_mathlib.h:85,
                 from thirdparty\astcenc\astcenc_internal.h:34,
                 from thirdparty\astcenc\astcenc_ideal_endpoints_and_weights.cpp:26:
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h: In function 'vint4 vtable_8bt_32bi(vint4, vint4)':
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to 'always_inline' '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
  136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~
In file included from thirdparty\astcenc\astcenc_vecmathlib.h:96,
                 from thirdparty\astcenc\astcenc_mathlib.h:433:
thirdparty\astcenc\astcenc_vecmathlib_sse_4.h:1087:42: note: called from here
 1087 |         __m128i result = _mm_shuffle_epi8(t0.m, idxx);
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
C:/Users/kuhnc/scoop/apps/mingw/current/lib/gcc/x86_64-w64-mingw32/12.2.0/include/tmmintrin.h:136:1: error: inlining failed in call to 'always_inline' '__m128i _mm_shuffle_epi8(__m128i, __m128i)': target specific option mismatch
  136 | _mm_shuffle_epi8 (__m128i __X, __m128i __Y)
      | ^~~~~~~~~~~~~~~~
thirdparty\astcenc\astcenc_vecmathlib_sse_4.h:1087:42: note: called from here
 1087 |         __m128i result = _mm_shuffle_epi8(t0.m, idxx);
      |                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

### Steps to reproduce

* Pull master
* Compile
* Receive error

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #71700.
Patch submitted upstream.

Thanks @kuhnchris for the help debugging and coming up with a solution.

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Woohoo CI finally passed!

**Comment by kuhnchris** [comment]
Great, thanks for fixing and sorry for bringing up a weird corner-case like this, but I assume it may come up again randomly if someone tries to compile like this, so I guess it's best to deal with this, especially if it's just a easy fix, before having to dig around for it later. ;-)

Just a quick question tho: The "patch" was applied in the source, and there is a `patches/fix-build-no-ssse3.patch` file added aswell, isn't that kind of redundant, or is that on purpose?

Again, thanks and great work for fixing this up guys! :-) 👍

**Comment by akien-mga** [comment]
Thanks for reporting it, it was an important bug to solve :)

> Just a quick question tho: The "patch" was applied in the source, and there is a `patches/fix-build-no-ssse3.patch` file added aswell, isn't that kind of redundant, or is that on purpose?

The patch files are how we document the changes that we made to upstream source code which do not match the tagged release we claim to vendor in `thirdparty/README.md`. This way we can easily re-apply the custom changes next time we update the thirdparty library, if our changes haven't been PR'ed or merged upstream.

Since the patch was merged upstream, it will be removed next time we update astcenc to a new tagged version or Git snapshot.

**Comment by kuhnchris** [comment]
Thanks for clarifying!

**Pull request merged**
