### PR TITLE
Allow `SCREEN_UV` to be used in light function of spatial shader

### LINKED ISSUE #10222: Add the built-in SCREEN_UV to the spatial shader's light() function
### Describe the project you are working on

simple puzzle game with a stylized lighting look

### Describe the problem or limitation you are having in your project

I've created a light() shader that uses a screen-space texture to give shadows a stylized look. In order to accomplish this, I need to access the screen UV to place the texture. Because the light() function does not actually have SCREEN_UV, I  do the following:

```
void light() {
	vec2 SCRN_UV = (VIEW.xy + FRAGCOORD.xy) / VIEWPORT_SIZE;
       ...
}
```
(If I name the variable SCREEN_UV, it causes issues. Not sure if that's intended behavior or not)

I admit, I don't even know if this is the right solution to get the actual screen UV. It looks right in-game though.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add `SCREEN_UV` as a built-in for the light() function, exactly the same as it is in the fragment() function. This would simplify the process of getting the screen's UV, and also make it more intuitive.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

You would be able to access SCREEN_UV in the light() function, and it would return a vec2 of the Screen UV coordinate of the pixel currently being processed.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

As mentioned above, you can use something like `vec2 SCRN_UV = (VIEW.xy + FRAGCOORD.xy) / VIEWPORT_SIZE;` to make your own SCREEN_UV variable in the light() function (I don't know if this is correct even), though IMO it feels intuitive that there would just be a SCREEN_UV bulit-in.

### Is there a reason why this should be core and not an add-on in the asset library?

SCREEN_UV is a very basic built-in for the fragment() function. Such a built-in for the light() function would also be very basic.

### PR DESCRIPTION
**Pull request by Chaosus**
- Closes https://github.com/godotengine/godot-proposals/issues/10222

изображение

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/3978628c6cc1227250fc6ed45c8d854d24c30c30), it works as expected in all rendering methods.

**Testing project:** [test_pr_94981.zip](https://github.com/user-attachments/files/16448410/test_pr_94981.zip)

One concern though is that this increases the number of shader versions compiled whenever the feature is used, which didn't occur with the workaround described in https://github.com/godotengine/godot-proposals/issues/10222. This has a performance impact.

**Comment by Chaosus** [comment]
Yeah, maybe its not good. At least there is a simple workaround to use varying:
```glsl
shader_type spatial;

varying vec2 screen_uv;

void fragment() {
	screen_uv = SCREEN_UV;
}

void light() {
	DIFFUSE_LIGHT = vec3(screen_uv, 0.0);
}
```

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
