### PR TITLE
ran cppcheck, fixed cases where array index is used before limits check

### PR DESCRIPTION
**Pull request by firefly2442**
Is the index check in `main.cpp` really needed?  Maybe better to just remove them or put them all in an outer conditional check so it's easier to read?  If you would rather it be something else, let me know and I can redo this PR.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
:+1:

**Comment by vnen** [comment]
For me this seems very subjective and mostly a matter of preference.

The checks in the `main.cpp` are looking for CLI arguments, so it has to check it the option parameter (which is the next CLI argument) is actually is there before getting it.

I think that one way to clean this is to make the check for the next argument and inside the block check for the individual options that require parameters.

**Comment by firefly2442** [comment]
I think I agree regarding your `main.cpp` comments.  However, I think it's still good practice to do the index value constraint check before accessing the value.  I'll try to refactor it when I get a chance.

**Comment by firefly2442** [comment]
I updated the commit (force push) as per suggestions by @vnen.  I think this is cleaner and easier to read.  As always, please double check. :)

**Comment by reduz** [comment]
well, the code is prettier so..

**Pull request merged**
