### PR TITLE
GLTF import external images correctly

### PR DESCRIPTION
**Pull request by LunaticInAHat**
This PR corrects three distinct defects that were present in the initial implementation of PR #66856:
  1. Textures that referenced images in external files were not imported correctly (fix in line 3081)
  2. GLTF assets that did not have a 1-1 correspondence between samplers and textures ended up using the wrong samplers for textures (fix in line 3216)
  3. Godot would crash when trying to import invalid GLTF assets that referenced images, textures, or samplers that did not exist

### CODE REVIEW

**Comment by LunaticInAHat** [comment]
@Sirus97 Could you please validate this PR with the assets that you have, to make sure it still works on your end?

**Comment by LunaticInAHat** [comment]
I have rechecked the 4.x implementation that was merged in PR #59481 and I do not believe that it is susceptible to the first two defects addressed by this PR -- they are specific to the way things had to be done in 3.x.
The 4.x implementation is also less susceptible to crashing when importing invalid GLTF files, but perhaps not as resilient as it could be. Would it be desirable for me to open a PR to enhance the 4.x importer's robustness?

**Review by fire — APPROVED** [review]
@Sirus97 and @LunaticInAHat has checked and approved.

I'm too distant from godot 3.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
