### PR TITLE
Added multi-monitor support for center_window()

### PR DESCRIPTION
**Pull request by ghost**
Added the screen position to the centering formula, so it will center the window on the current screen.  Currently it will send the window back to the default monitor.

(Also removed extra divisions.)

### CODE REVIEW

**Comment by Noshyaar** [comment]
No whitespace characters on empty lines.

**Comment by avencherus** [comment]
@Noshyaar Awesome, thanks.  Will give that a try.  Is there a reference for these formatting rules somewhere?

**Comment by Noshyaar** [comment]
I don't think there is. I usually match the formatting to adjacent codes and run clang-format on the files before committing, automatically fixing them. The rules are defined in /.clang-format

**Comment by avencherus** [comment]
Cool, that is a starting point for me at least.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
