### PR TITLE
[3.2] Fix splash screen loading on Android

### PR DESCRIPTION
**Pull request by m4gr3d**
Fix issue #21824

This is done by leveraging the Android theme to setup the app splash screen ([reference](https://medium.com/@vatani.ahmad/android-optimal-splash-screen-without-extra-activity-or-fragment-b60fea45a0cc)).

**Note:** 
- The splash screen `fullsize` and `use filter` parameters are not supported due to limitations of the Android theme api
- The PR is made against the `3.2-android-app-bundle` branch since that branch includes numerous updates to the Android build process.
- The feature targets the Godot **3.2.4** release.

### CODE REVIEW

**Comment by m4gr3d** [comment]
@akien-mga should I reopen this PR against the 3.2 branch?

**Comment by akien-mga** [comment]
Ah, it got closed because the target branch was deleted I guess? Then yes, unless this one can be reopened with its target branch changed.

**Comment by akien-mga** [comment]
(Well I see the reopen button is greyed out, so a new PR will be necessary.)

**Comment by m4gr3d** [comment]
Replaced by PR #42389

**Pull request closed without merging**
