### PR TITLE
Optimised vector and quaternion normalisations adding fast inverse square root

### PR DESCRIPTION
**Pull request by puthre**
I've added Math::fast_inv_sqrt that computes 1/sqrt(x) almost 5 times faster and modified the Vector2, Vector3 and Quat classes to make use of it for normalization. Normalizations should be now A LOT faster.
See https://en.wikipedia.org/wiki/Fast_inverse_square_root

### CODE REVIEW

**Comment by isaacremnant** [comment]
This only does one step of Newton, iirc it isn't too accurate (0.1%??). It might be preferable in some circumstances to leave the default sqrt behavior, or at least run a few iterations of `y * (1.5F - 0.5F * x * y * y)`.

_Disclaimer: I do scientific computations, maybe this is more than sufficient in games._

**Comment by puthre** [comment]
> This only does one step of Newton, iirc it isn't too accurate (0.1%??). It might be preferable in some circumstances to leave the default sqrt behavior, or at least run a few iterations of `y * (1.5F - 0.5F * x * y * y)`.
> 
> _Disclaimer: I do scientific computations, maybe this is more than sufficient in games._

It's used successfully in commercial games since Quake 3.

**Comment by lawnjelly** [comment]
Probably not a good option, but just in the interest of rounded discussion, worth mentioning there is also inverse square root in SIMD instruction sets, which afaik is faster and more accurate:

https://www.xaymar.com/2016/12/16/what-is-the-fastest-way-to-get-an-inverse-square-root/

However there are lots of downsides too - it requires all the usual boiler plate for detecting what is supported and selecting a code path (and on different platforms). And it only seems to get significantly faster when you are doing a bunch of these at a time. So it probably doesn't make a lot of sense unless Godot had a general framework for using SIMD.

Anyway questions I'd be wondering: :thinking: 

- Are there any bits of code where profiling has indicated this as a bottleneck?

- Are there any implications of changing the accuracy in other bits of code (epsilons etc)? (An alternative approach might be to have alternative functions such as normalize_fast() if this was a problem.)

**Comment by puthre** [comment]
@lawnjelly It really depends on the game you are making. My profiling data showed that this is used a lot in CPUParticles2D for example and that's how I got to it. If you do a point and click type of game, it probably won't help you much.

**Comment by isaacremnant** [comment]
Yeah I'm sort of opposed to inaccuracies in a _basic_ function like `Vector2.normalize()`. The functions offered by Godot should be accurate up to machine precision by default, and you should _choose_ to trade accuracy for speed _only if_ you need it.

The best option is to expose `fast_inv_sqrt` and other such "hacks," but let the user or specific pieces of code use it when needed, i.e., replace calls to `normalize()` with `*fast_inv_sqrt(vec)` where needed instead of modifying `normalize()` itself.

**Comment by Calinou** [comment]
@isaacremnant Indeed, it would make sense to use a fast inverse square root method for things like CPUParticles, but keep the current accurate method for scripting.

**Comment by puthre** [comment]
@Calinou In games you need speed by default to keep those 60 fps running. I've never heard a complaint about normalized vectors being 0.1% off but lots about slow games. If you ever need >0.1% accuracy you can normalize your vectors using the math sqrt function.

**Comment by mwerezak** [comment]
@puthre suppose I am working with a simulation that uses vectors in the computation and I don't want my system to go bonkers and explode due to accumulated error, what do I do?

My point is that what level of error is acceptable is highly use case dependant. 

Just because someone wants precision doesn't mean they no longer care about performance either. Having to normalize the vector using sqrt in script would be slow, wouldn't it?

So I think if you are going that route, having two methods for normalization representing the different tradeoffs would be the way to go.

**Comment by puthre** [comment]
> Having to normalize the vector using sqrt in script would be slow, wouldn't it?
It should not be. Why would it be slow?
> So I think if you are going that route, having two methods for normalization representing the different tradeoffs would be the way to go.
Yes, that another way to do it, probably the safest.

**Comment by mwerezak** [comment]
> It should not be. Why would it be slow?

I presumed that there would be overhead in gdscript for the extra operations and function call. I could be mistaken though.

**Comment by lawnjelly** [comment]
I've just profiled your fast sqrt code against the original Vector3::normalize, and with -O3 the fast sqrt code comes out slower, both with and without allowing inlining of the normalize call. This is on an Intel Core i5-7500T, 2.7ghz x 4. Compiled with gcc / g++.

_(Time taken) Without inlining:_
**Old** : 260, **FastSqrt** : 298

_With inlining:_
**Old** : 245, **FastSqrt** : 290

Obviously the results might change on a different CPU, or depending on whether SIMD used etc. And as with any testing of this sort it's possible I've made a mistake and the timings are artefacts, I'd double check this yourself independently.

This is the assembly generated  (no inline) for the

**Old method**
```
	.section	.text.unlikely._ZN7Vector39NormalizeEv,"axG",@progbits,_ZN7Vector39NormalizeEv,comdat
	.align 2
.LCOLDB1:
	.section	.text._ZN7Vector39NormalizeEv,"axG",@progbits,_ZN7Vector39NormalizeEv,comdat
.LHOTB1:
	.align 2
	.p2align 4,,15
	.weak	_ZN7Vector39NormalizeEv
	.type	_ZN7Vector39NormalizeEv, @function
_ZN7Vector39NormalizeEv:
.LFB1649:
	.cfi_startproc
	movss	(%rdi), %xmm4
	pushq	%rbx
	.cfi_def_cfa_offset 16
	.cfi_offset 3, -16
	movss	4(%rdi), %xmm3
	movaps	%xmm4, %xmm1
	movaps	%xmm3, %xmm0
	movss	8(%rdi), %xmm2
	mulss	%xmm4, %xmm1
	mulss	%xmm3, %xmm0
	addss	%xmm1, %xmm0
	movaps	%xmm2, %xmm1
	mulss	%xmm2, %xmm1
	addss	%xmm1, %xmm0
	pxor	%xmm1, %xmm1
	ucomiss	%xmm1, %xmm0
	jp	.L2
	jne	.L2
	movss	%xmm1, 8(%rdi)
	movss	%xmm1, 4(%rdi)
	movss	%xmm1, (%rdi)
	popq	%rbx
	.cfi_remember_state
	.cfi_def_cfa_offset 8
	ret
	.p2align 4,,10
	.p2align 3
.L2:
	.cfi_restore_state
	sqrtss	%xmm0, %xmm1
	ucomiss	%xmm1, %xmm1
	movq	%rdi, %rbx
	jp	.L10
.L5:
	divss	%xmm1, %xmm4
	divss	%xmm1, %xmm3
	movss	%xmm4, (%rbx)
	divss	%xmm1, %xmm2
	movss	%xmm3, 4(%rbx)
	movss	%xmm2, 8(%rbx)
	popq	%rbx
	.cfi_remember_state
	.cfi_def_cfa_offset 8
	ret
.L10:
	.cfi_restore_state
	call	sqrtf
	movss	(%rbx), %xmm4
	movaps	%xmm0, %xmm1
	movss	4(%rbx), %xmm3
	movss	8(%rbx), %xmm2
	jmp	.L5
	.cfi_endproc
.LFE1649:
	.size	_ZN7Vector39NormalizeEv, .-_ZN7Vector39NormalizeEv
	.section	.text.unlikely._ZN7Vector39NormalizeEv,"axG",@progbits,_ZN7Vector39NormalizeEv,comdat
.LCOLDE1:
	.section	.text._ZN7Vector39NormalizeEv,"axG",@progbits,_ZN7Vector39NormalizeEv,comdat

```
**Fast sqrt**
```
.LHOTB4:
	.align 2
	.p2align 4,,15
	.weak	_ZN7Vector310Normalize3Ev
	.type	_ZN7Vector310Normalize3Ev, @function
_ZN7Vector310Normalize3Ev:
.LFB1651:
	.cfi_startproc
	movss	(%rdi), %xmm3
	movaps	%xmm3, %xmm0
	movss	4(%rdi), %xmm2
	movaps	%xmm2, %xmm1
	mulss	%xmm3, %xmm0
	movss	8(%rdi), %xmm5
	mulss	%xmm2, %xmm1
	movaps	%xmm0, %xmm4
	addss	%xmm1, %xmm4
	movaps	%xmm5, %xmm1
	mulss	%xmm5, %xmm1
	addss	%xmm1, %xmm4
	pxor	%xmm1, %xmm1
	ucomiss	%xmm1, %xmm4
	movaps	%xmm4, %xmm0
	jp	.L12
	je	.L16
.L12:
	movd	%xmm0, %edx
	mulss	.LC2(%rip), %xmm0
	movl	$1597463007, %eax
	movss	.LC3(%rip), %xmm4
	sarl	%edx
	subl	%edx, %eax
	movl	%eax, -4(%rsp)
	movss	-4(%rsp), %xmm1
	mulss	%xmm1, %xmm0
	mulss	%xmm1, %xmm0
	subss	%xmm0, %xmm4
	movaps	%xmm4, %xmm0
	mulss	%xmm1, %xmm0
	mulss	%xmm0, %xmm3
	mulss	%xmm0, %xmm2
	mulss	%xmm5, %xmm0
	movss	%xmm3, (%rdi)
	movss	%xmm2, 4(%rdi)
	movss	%xmm0, 8(%rdi)
	ret
	.p2align 4,,10
	.p2align 3
.L16:
	movss	%xmm1, 8(%rdi)
	movss	%xmm1, 4(%rdi)
	movss	%xmm1, (%rdi)
	ret
	.cfi_endproc
.LFE1651:
	.size	_ZN7Vector310Normalize3Ev, .-_ZN7Vector310Normalize3Ev
	.section	.text.unlikely._ZN7Vector310Normalize3Ev,"axG",@progbits,_ZN7Vector310Normalize3Ev,comdat
.LCOLDE4:
	.section	.text._ZN7Vector310Normalize3Ev,"axG",@progbits,_ZN7Vector310Normalize3Ev,comdat
```

**Comment by puthre** [comment]
@lawnjelly In my test the fast inv sqrt it was 4.58 something faster (Intel(R) Xeon(R) CPU X5670  @ 2.93GHz) on 1 million iterations on different random numbers. 
here is my quick and dirty test code
```
#include <cstring>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

float FastInvSqrt(float number);
float Q_rsqrt(float number);
float fastInvSqrt(float x);
#define N 1000000

int main() {
  float x = 0;
  time_t t;

  srand((unsigned)time(&t));

  int i = 0;

  double sum_time2 = 0.0;
  double sum_z1 = 0.0;
  double sum_z2 = 0.0;
  float num[N];

  for (int x = 0; x < N; x++) {
    num[x] = (float)(rand() % 100) * 1.22158 + 0.0001;
  }

  clock_t start2 = clock();
  do {

    float z = 1.0 / sqrt(num[i]);

    sum_z1 += z;
    i++;
  } while (i < N);
  clock_t end2 = clock();
  sum_time2 = (end2 - start2);

  printf("1/sqrt() spends %13f sec.\n\n", sum_time2 / (double)CLOCKS_PER_SEC);

  double sum_time1 = 0.0;

  i = 0;
  clock_t start1 = clock();

  do

  {
    float y = Q_rsqrt(num[i]);
    sum_z2 += y;
    i++;
  } while (i < N);
  clock_t end1 = clock();
  sum_time1 = (end1 - start1);

  printf("FastInvSqrt() spends %f sec.\n\n",
         sum_time1 / (double)CLOCKS_PER_SEC);

  printf("fast inverse square root is faster %f times than 1/sqrt().\n",
         sum_time2 / sum_time1);
  printf("sumz1 %f sumz2 %f \n\n", sum_z1, sum_z2);

  return 0;
}

inline float FastInvSqrt(float x) {
  float xhalf = 0.5F * x;
  int i = *(int *)&x;            // store floating-point bits in integer
  i = 0x5f3759df - (i >> 1);     // initial guess for Newton's method
  x = *(float *)&i;              // convert new bits into float
  x = x * (1.5 - xhalf * x * x); // One round of Newton's method
  // x = x * (1.5 - xhalf * x * x);      // One round of Newton's method
  // x = x * (1.5 - xhalf * x * x);      // One round of Newton's method
  // x = x * (1.5 - xhalf * x * x);      // One round of Newton's method
  return x;
}

float fastInvSqrt(float x) {
  int i = *(int *)&x;
  i = 0x5f3759df - (i >> 1);
  float y = *(float *)&i;
  return y * (1.5F - 0.5F * x * y * y);
}

float Q_rsqrt(float number) {
  /*    static_assert(std::numeric_limits<float>::is_iec559,
                    "fast inverse square root requires IEEE-comliant 'float'");
      static_assert(sizeof(float)==sizeof(std::uint32_t),
                    "fast inverse square root requires 'float' to be 32-bit");
                    */
  float x2 = number * 0.5F, y = number;
  int i;
  memcpy(&i, &y, sizeof(float));
  i = 0x5f3759df - (i >> 1);
  memcpy(&y, &i, sizeof(float));
  return y * (1.5F - (x2 * y * y));
}
```
compile with 
gcc test.cpp  -O3 -lm

**Comment by lawnjelly** [comment]
I was specifically testing its use with normalize in Vector3. Although the fastsqrt may be faster than sqrt, that doesn't mean it will be the faster approach in the context of the whole function (specifically this normalize).

In the context of the Vector3::normalize, the crucial thing is that the CPU can do everything at once. I tested this myself yesterday in another context .. the difference between doing this operation:

Consider you want to divide a Vector3 by A.

2 Approaches:

1
```
x /= A; y /= A; z /= A;
```
2
```
B = 1.0 / A
X *= B; Y *= B; Z *= B;
```
I was expecting approach (2) to be faster. In fact, when profiled, although the multiply is marginally quicker than the divide, the extra divide at the beginning translates to an extra op, whereas the rest can be done with SIMD.

So the actual result I found was that approach (1) is a similar speed to (2) in the case of non-inlined, and in the case of inlined, (1) was many times faster than (2). This was the opposite to what I was expecting.

The same thing is happening in the Vector3::Normalize. Not because of the fast sqrt itself, but because you are using the 2 operations instead of 1.

**Comment by lawnjelly** [comment]
Here's my testbed, there may be an obvious mistake (it is easy to make mistakes in the measurement!):

```
#include <iostream>
#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include <string.h>

using namespace std;

#define  NO_INL __attribute__ ((noinline))


struct Vector3
{
	float x, y, z;
	void Blank()
	{
		x = 10000.0f * (((float) rand() / RAND_MAX)-0.5f);
		y = 10000.0f * (((float) rand() / RAND_MAX)-0.5f);
		z = 10000.0f * (((float) rand() / RAND_MAX)-0.5f);
	}

	float length_squared() const {return (x * x) + (y * y) + (z * z);}

	void NO_INL Normalize()
	{
		float lengthsq = length_squared();
		if (lengthsq == 0) {
			x = y = z = 0;
		} else {
			float length = sqrt(lengthsq);
			x /= length;
			y /= length;
			z /= length;
		}
	}


	// fast inverse square root, see https://en.wikipedia.org/wiki/Fast_inverse_square_root
	float fast_inv_sqrt(float x) {

		float x2 = x * 0.5F, y = x;
		int i;
		memcpy(&i, &y, sizeof(float));
		i = 0x5f3759df - (i >> 1);
		memcpy(&y, &i, sizeof(float));
		return y * (1.5F - (x2 * y * y));
	}

	void NO_INL Normalize3()
	{
		float lengthsq = length_squared();
		if (lengthsq == 0) {
			x = y = z = 0;
		} else {
			float inv_length = fast_inv_sqrt(lengthsq);
			x *= inv_length;
			y *= inv_length;
			z *= inv_length;
		}
	}

};


// BEWARE that RDTSC is subject to speedstep and multicore switching
// Consider using QueryPerformanceCounter and CLOCK_MONOTONIC_RAW as well
uint64_t get_time()
{
    unsigned int lo,hi;
    __asm__ __volatile__ ("rdtsc" : "=a" (lo), "=d" (hi));
    return ((uint64_t)hi << 32) | lo;
}


int main()
{
	int64_t start;
	int64_t end;

	int64_t timeA;
	int64_t timeB;

	const int data_size = 100000;

	Vector3 data[data_size];
	Vector3 data_out[data_size];

	for (int n=0; n<data_size; n++)
	{
		data[n].Blank();
		data_out[n].Blank();
	}

	const int repeats = 20;

	int countA = 0;
	int countB = 0;

	// use several runs, cache might not be warm (repeatable) on the first
	for (int tries=0; tries<5; tries++)
	{
		start = get_time();

		// repeat profiling the same data several times
		for (int r=0; r<repeats; r++)
		{
			for (int n=0; n<data_size; n++)
			{
				// use the same test data input each time
				data_out[n] = data[n];
				data_out[n].Normalize();

				// this is to prevent compiler optimizing out the test .. we need to DO something with test data result
				if (data_out[n].x > 0.5f)
					countA++;
			}
		} // for repeat

		end = get_time();
		timeA = end - start;

		start = get_time();

		// repeat profiling the same data several times
		for (int r=0; r<repeats; r++)
		{
			for (int n=0; n<data_size; n++)
			{
				// use the same test data input each time
				data_out[n] = data[n];
				data_out[n].Normalize3();

				// this is to prevent compiler optimizing out the test .. we need to DO something with test data result
				if (data_out[n].x > 0.5f)
					countB++;
			}
		} // for repeat

		end = get_time();
		timeB = end - start;


		char szOut[64];
		sprintf(szOut, "%i", (int) timeA);
		cout << szOut;
		cout << "(a)\n";
		sprintf(szOut, "%i", (int) timeB);
		cout << szOut;
		cout << "(b)\n";
		sprintf(szOut, "%i %i", (int) countA, (int) countB);
		cout << szOut;
		cout << "(counts)\n";
	}

	return 0;
}
```

**Comment by puthre** [comment]
> A similar thing may be happening in the Vector3::Normalize. Not because of the fast sqrt itself, but because it ends up splitting into more operations.

I've modified my test to do actual normalizations and it's even faster (5.45 times faster)

```
#include <cstring>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

float FastInvSqrt(float number);
float Q_rsqrt(float number);
float fastInvSqrt(float x);
#define N 1000000

int main() {
  float x = 0;
  time_t t;

  srand((unsigned)time(&t));

  int i = 0;

  double sum_time2 = 0.0;
  double sum_z1 = 0.0;
  double sum_z2 = 0.0;
  float num[N+3];

  for (int x = 0; x < N+3; x++) {
    num[x] = (float)(rand() % 100) * 1.22158 + 0.0001;
  }

  clock_t start2 = clock();
  do {
    float l = sqrt(num[i]);
    float z1 = num[i+1] / l;
    float z2 = num[i+2] / l;
    float z3 = num[i+3] / l;

    sum_z1 += z1+z2+z3;
    i++;
  } while (i < N);
  clock_t end2 = clock();
  sum_time2 = (end2 - start2);

  printf("1/sqrt() spends %13f sec.\n\n", sum_time2 / (double)CLOCKS_PER_SEC);

  double sum_time1 = 0.0;

  i = 0;
  clock_t start1 = clock();

  do

  {
    float invl = Q_rsqrt(num[i]);
    float z1 = num[i+1]*invl;
    float z2 = num[i+2]*invl;
    float z3 = num[i+3]*invl;
    sum_z2 += z1+z2+z3;
    i++;
  } while (i < N);
  clock_t end1 = clock();
  sum_time1 = (end1 - start1);

  printf("FastInvSqrt() spends %f sec.\n\n",
         sum_time1 / (double)CLOCKS_PER_SEC);

  printf("fast inverse square root is faster %f times than 1/sqrt().\n",
         sum_time2 / sum_time1);
  printf("sumz1 %f sumz2 %f \n\n", sum_z1, sum_z2);

  return 0;
}

inline float FastInvSqrt(float x) {
  float xhalf = 0.5F * x;
  int i = *(int *)&x;            // store floating-point bits in integer
  i = 0x5f3759df - (i >> 1);     // initial guess for Newton's method
  x = *(float *)&i;              // convert new bits into float
  x = x * (1.5 - xhalf * x * x); // One round of Newton's method
  // x = x * (1.5 - xhalf * x * x);      // One round of Newton's method
  // x = x * (1.5 - xhalf * x * x);      // One round of Newton's method
  // x = x * (1.5 - xhalf * x * x);      // One round of Newton's method
  return x;
}

float fastInvSqrt(float x) {
  int i = *(int *)&x;
  i = 0x5f3759df - (i >> 1);
  float y = *(float *)&i;
  return y * (1.5F - 0.5F * x * y * y);
}

float Q_rsqrt(float number) {
  /*    static_assert(std::numeric_limits<float>::is_iec559,
                    "fast inverse square root requires IEEE-comliant 'float'");
      static_assert(sizeof(float)==sizeof(std::uint32_t),
                    "fast inverse square root requires 'float' to be 32-bit");
                    */
  float x2 = number * 0.5F, y = number;
  int i;
  memcpy(&i, &y, sizeof(float));
  i = 0x5f3759df - (i >> 1);
  memcpy(&y, &i, sizeof(float));
  return y * (1.5F - (x2 * y * y));
}
```

**Comment by lawnjelly** [comment]
It may be an inlining difference. I'd made a small mistake in my test data, and the with loop unrolling the new version is faster, but without, the old is faster. I'll try your version. :+1:

**Comment by puthre** [comment]
> It may be an inlining difference. I'd made a small mistake in my test data, and the with loop unrolling the new version is faster, but without, the old is faster. I'll try your version.
here is the result of your version on my cpu
```
120703756(a)
60861428(b)
557520 557160(counts)
120899024(a)
60412924(b)
1115040 1114320(counts)
120816380(a)
60400812(b)
1672560 1671480(counts)
120754280(a)
61206052(b)
2230080 2228640(counts)
120683052(a)
60779992(b)
2787600 2785800(counts)
```

fast version seems twice as fast.

**Comment by lawnjelly** [comment]
Is that with the inlining switched on or off? If as posted, it should be preventing inlining (you can double check this by just changing the #define NO_INL to blank, let us know the two timings).

If it's faster without inlining that is quite interesting the difference, maybe from the CPU or the compiler is producing different output?

**Comment by puthre** [comment]
> Is that with the inlining switched on or off? If as posted, it should be preventing inlining (you can double check this by just changing the #define NO_INL to blank, let us know the two timings).
> 
> If it's faster without inlining that is quite interesting the difference, maybe from the CPU or the compiler is producing different output?
I've set NO_INL to blank:
```
134505712(a)
57245276(b)
557520 557160(counts)
134536720(a)
57342616(b)
1115040 1114320(counts)
134392448(a)
57176740(b)
1672560 1671480(counts)
134399988(a)
57236264(b)
2230080 2228640(counts)
134354916(a)
57251972(b)
2787600 2785800(counts)

```

**Comment by lawnjelly** [comment]
Ok, try this:
```
#include <iostream>
#include <stdint.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <time.h>

using namespace std;

#define  NO_INL __attribute__ ((noinline))
//#define NO_INL

struct Vector3
{
	float x, y, z;

	void Zero() {x = y = z = 0.0f;}
	void Add(const Vector3&o) {x += o.x; y += o.y; z += o.z;}

	void Blank()
	{
		x = 10000.0f * (((float) rand() / RAND_MAX)-0.5f);
		y = 10000.0f * (((float) rand() / RAND_MAX)-0.5f);
		z = 10000.0f * (((float) rand() / RAND_MAX)-0.5f);
	}

	float length_squared() const {return (x * x) + (y * y) + (z * z);}

	void NO_INL Normalize()
	{
		float lengthsq = length_squared();
		if (lengthsq == 0) {
			x = y = z = 0;
		} else {
			float length = sqrt(lengthsq);
			x /= length;
			y /= length;
			z /= length;
		}
	}


	// fast inverse square root, see https://en.wikipedia.org/wiki/Fast_inverse_square_root
	float fast_inv_sqrt(float x) {

		float x2 = x * 0.5F, y = x;
		int i;
		memcpy(&i, &y, sizeof(float));
		i = 0x5f3759df - (i >> 1);
		memcpy(&y, &i, sizeof(float));
		return y * (1.5F - (x2 * y * y));
	}

	void NO_INL Normalize3()
	{
		float lengthsq = length_squared();
		if (lengthsq == 0) {
			x = y = z = 0;
		} else {
			float inv_length = fast_inv_sqrt(lengthsq);
			x *= inv_length;
			y *= inv_length;
			z *= inv_length;
		}
	}

};


// BEWARE that RDTSC is subject to speedstep and multicore switching
// Consider using QueryPerformanceCounter and CLOCK_MONOTONIC_RAW as well
uint64_t get_time()
{
#define USE_RDTSC
#ifdef USE_RDTSC
    unsigned int lo,hi;
    __asm__ __volatile__ ("rdtsc" : "=a" (lo), "=d" (hi));
    return ((uint64_t)hi << 32) | lo;
#else
	clock_t t = clock();
	return (uint64_t) (t * 1000);
#endif
}


int main()
{
	int64_t start;
	int64_t end;

	int64_t timeA;
	int64_t timeB;

	const int data_size = 100000;

	Vector3 data[data_size];
	Vector3 data_out[data_size];

	Vector3 sumA;
	Vector3 sumB;

	for (int n=0; n<data_size; n++)
	{
		data[n].Blank();
		data_out[n].Blank();
	}

	const int repeats = 20;

	// use several runs, cache might not be warm (repeatable) on the first
	for (int tries=0; tries<5; tries++)
	{
		sumA.Zero();
		sumB.Zero();

		start = get_time();

		// repeat profiling the same data several times
		for (int r=0; r<repeats; r++)
		{
			for (int n=0; n<data_size; n++)
			{
				// use the same test data input each time
				data_out[n] = data[n];
				data_out[n].Normalize();

				// this is to prevent compiler optimizing out the test .. we need to DO something with test data result
				sumA.Add(data_out[n]);
			}
		} // for repeat

		end = get_time();
		timeA = end - start;

		start = get_time();

		// repeat profiling the same data several times
		for (int r=0; r<repeats; r++)
		{
			for (int n=0; n<data_size; n++)
			{
				// use the same test data input each time
				data_out[n] = data[n];
				data_out[n].Normalize3();

				// this is to prevent compiler optimizing out the test .. we need to DO something with test data result
				sumB.Add(data_out[n]);
			}
		} // for repeat

		end = get_time();
		timeB = end - start;


		timeA /= 10000;
		timeB /= 10000;

		char szOut[64];
		sprintf(szOut, "%i", (int) timeA);
		cout << szOut;
		cout << "(a)\n";
		sprintf(szOut, "%i", (int) timeB);
		cout << szOut;
		cout << "(b)\n";
		sprintf(szOut, "%i %i", (int) sumA.x, (int) sumB.x);
		sprintf(szOut, "%i %i", (int) sumA.y, (int) sumB.y);
		sprintf(szOut, "%i %i", (int) sumA.z, (int) sumB.z);
		cout << szOut;
		cout << "(counts)\n";
	}

	return 0;
}
```
The battle is to stop the compiler from optimizing out the test code. The previous version I only used the x value from the output data, and there was an if statement. This version simply adds up the sum of the output vectors, and prints out all the x, y, and z values to ensure they are not optimized out.

The results on mine are now:

**NO INLINE**
```
3133(a)
3736(b)
840 842(counts)
3107(a)
3742(b)
840 842(counts)
3096(a)
3757(b)
840 842(counts)
3162(a)
3908(b)
840 842(counts)
3254(a)
3889(b)
840 842(counts)
```
**WITH INLINE**
```
2624(a)
2963(b)
840 842(counts)
2581(a)
2991(b)
840 842(counts)
2581(a)
2974(b)
840 842(counts)
2575(a)
2972(b)
840 842(counts)
2609(a)
2951(b)
840 842(counts)
```
This seems more sensible output, but it is showing the original is faster in both cases now. I'll have a look at your testbed and see if we can work out why they are giving different results.

**Comment by puthre** [comment]
no inline
```
12187(a)
7074(b)
840 842(counts)
12064(a)
7141(b)
840 842(counts)
12128(a)
7086(b)
840 842(counts)
12109(a)
7072(b)
840 842(counts)
12087(a)
7065(b)
840 842(counts)
```
inline
```
12039(a)
5173(b)
840 842(counts)
12052(a)
5197(b)
840 842(counts)
12026(a)
5133(b)
840 842(counts)
12035(a)
5139(b)
840 842(counts)
12038(a)
5143(b)
840 842(counts)
```

**Comment by lawnjelly** [comment]
Ahha! I have spotted a possible problem in your testbed:

You are using this to try and prevent the compiler optimizing out:
```
    float z1 = num[i+1] / l;
    float z2 = num[i+2] / l;
    float z3 = num[i+3] / l;

    return z1+z2+z3;
```
The problem is this can be done by simply adding all the values, then dividing by l once.

**Comment by lawnjelly** [comment]
It does show what a minefield it is .. exact same source code and depending on the compiler and CPU giving different results. :smile: 

Really for a good test we need to use the same executable. The different GCC versions might be better / worse at optimizing, mine might be be older. Or it might be producing different SSE intrinsics (I don't know how it decides the default, I haven't specified an SSE version in my command line, perhaps I can try this).

**Comment by lawnjelly** [comment]
I just tried a really inefficient SIMD version using _mm_rsqrt_ss, and it is faster than fast_inv_sqrt on mine too. Note this is _really_ awful as I haven't done any SIMD for months (and it's doing only 1 where it could be doing 4) but lol:
```
	float SIMD_inv_sqrt(float x)
	{
		__m128 m = _mm_set_ss(x);
		__m128 res = _mm_rsqrt_ss(m);
		float fres[4];
		_mm_store_ps(fres, res);
		return fres[0];
	}
```
My only question is, I'm not sure how to coax the compiler into auto-producing this intrinsic without writing platform specific code.

With e.g., addition, it's obvious, but not so much for rsqrt. Using `1.0f / sqrt(x)` does not work, presumably because the result is not exactly the same as doing them individually.

I will experiment. This might be another alternative to using the quake version as if it is auto-produced by the compilers it is reported to be faster and more accurate.

**Comment by puthre** [comment]
```
12025(a)                                                                                                                                                                                                                                                                      
5121(b)                                                                                                                                                                                                                                                                       
-1301 3417 840 -1300 3414 842(counts)                                                                                                                                                                                                                                         
12037(a)                                                                                                                                                                                                                                                                      
5121(b)                                                                                                                                                                                                                                                                       
-1301 3417 840 -1300 3414 842(counts)                                                                                                                                                                                                                                         
12018(a)                                                                                                                                                                                                                                                                      
5112(b)                                                                                                                                                                                                                                                                       
-1301 3417 840 -1300 3414 842(counts)                                                                                                                                                                                                                                         
12022(a)                                                                                                                                                                                                                                                                      
5122(b)                                                                                                                                                                                                                                                                       
-1301 3417 840 -1300 3414 842(counts)                                                                                                                                                                                                                                         
12018(a)                                                                                                                                                                                                                                                                      
5153(b)                                                                                                                                                                                                                                                                       
-1301 3417 840 -1300 3414 842(counts)
```

It seems that it really depends on the cpu and I guess that the newer the cpu, the smaller the difference. An android test would be very interesting to see.

**Comment by lawnjelly** [comment]
Yep don't get me wrong, I think the fast sqrt trick is cool, and overall I think it will probably be useful, I just wanted to double check the timings. Another thing is that if we are separating any functions to be 'fast' versions, then presumably they will be even better if they can be written to operate on multiple data e.g.:

`void FastNormalize(Vector3 * pInput, int nElements)`

This will properly allow the compiler to unroll loops and take advantage of autovectorization. But it might not be appropriate for Variants. I don't know if pool arrays of Vector3 are contiguous in memory?

**Comment by aaronfranke** [comment]
@puthre Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by puthre** [comment]
@aaronfranke I don't think there is much interest for it. I'll close it.

**Pull request closed without merging**
