### PR TITLE
Hide TextFiles

### LINKED ISSUE #36297: Review TextFile name, exposure, implementation and usage for 4.0
*Bugsquad edit:* Issue repurposed to track necessary changes to `TextFile` as per https://github.com/godotengine/godot/issues/36297#issuecomment-586982345

------

**Godot version:**
Godot Engine v4.0.dev.custom_build 705ad947e

**OS/device including version:**
64 bit Windows 10 Enterprise 1909.

**Issue description:**
When opening any project, the console is spammed with 
```
ERROR: Cannot get class 'TextFile'
   at: (core\class_db.cpp:356)
```
quite a few times along with some other errors(I think they are mentioned in other issues already).

**Steps to reproduce:**
Just open any project.
Simple project and console log attached.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/4213510/test.zip)
[test.log.txt](https://github.com/godotengine/godot/files/4213528/test.log.txt)

### LINKED ISSUE #37999: Can't edit text file resource after renaming
**Godot version:**
3.2.1

**OS/device including version:**
Win 10

**Issue description:**
Renaming .tres textfile resource causes file to become uneditable inside godot editor

**Steps to reproduce:**
- create a new project
- right-click & add new textfile resource to "res://" folder
- save / edit / close / re-open file as expected
- rename file to anything else
- you can no longer view or edit the file inside godot editor

### LINKED ISSUE #39964: TextFiles resources are uneditable after closing the editor
**Godot version:**
3.2.2.stable

**OS/device including version: **
Windows 10

**Issue description:**
TextFile .tres ressources with data in them gets uneditable inside Godot Editor after closure.

**Steps to reproduce:**

1. Create a TextFile .tres ressource file
2. Write some text in it
3. Save the file
4. Close Godot
5. Open Godot
6. The TextFile ressource is now a common Ressource file and can't be opened anymore.

### PR DESCRIPTION
**Pull request by Paulb23**
With #47301 the `TextFile` resources can at last be hidden. 

Given both #47301 and #47268 have been cherry picked for `3.x`, I'm tempted have this backported as well, as I hope nobody is relying on `TextFiles`. But, this would be a breaking change that would need communicating on the release.

Included another minor bug fix that I missed in #51698.

closes #36297
closes #39964
closes #37999

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by thebigG** [comment]
So I recently ran into this. It was actually very confusing as I read docs and thought I could just load the TextFile as a Resource and of course I couldn't load it as a resource. So thanks for hiding them!

I did some digging and I think you guys are very close to being able to just load it as a resource in script. If I understand correctly, part of the challenge for that to happen is that resources have a special syntax like the following:

```
[gd_resource type="TextFile" load_steps=2 format=2]
[resource]
```
which makes a lot of sense because all resources are reloaded through a unified interface(`ResourceImporter` class) and so in essence one would have to write an importer such as `ResourceImporterCSVTranslation`. Something like `ResourceImporterTextFile`...and then the editor can have an option to "re-import" as we do with a lo of other resources.

As a user I still think this might be useful for something like a Story(which is the case in my team) that we would like to keep as text file and have it behave like any other resource that we can load.

Not sure if this is the right place for this comment, but figured might leave it here since the PR is related.

Hope these points make sense(perhaps I missed something?).
Thanks for making such an awesome game engine!

**Comment by thebigG** [comment]
I should add that I'll be willing to write this code. I know y'all busy so I would not mind working on this, but I figured I'd bring it first in case there something I'm missing.

**Comment by Paulb23** [comment]
@thebigG If you need read plain text, you should use the [File](https://docs.godotengine.org/en/stable/classes/class_file.html) class.

**Comment by thebigG** [comment]
Thanks for the quick reply!
I see what you mean...it might be overkill to make a plan and simple text file a resource.

**Pull request merged**
