### PR TITLE
Fix TreeItem's button being rendered under "Selected" highlights

### LINKED ISSUE #62951: Tree node - "Selected" and "Selected Focus" highlights are rendered on top of TreeItem's buttons
### Godot version

4.0 alpha11

### System information

Macbook Air M1 2020

### Issue description

When Tree node's "Select mode" is set to "Row", both "Selected" and "Selected Focus" highlights are rendered on top of TreeItem's buttons.
If "Selected Focus" is overridden with StyleBoxFlat using a solid color, the buttons will not be visible, but will still be there and can be clicked.
The buttons should be rendered on top.

Also, when Tree node's "Select mode" is set to "Row", when a TreeItem is selected, both the row and the TreeItem's "middle part" highlight are rendered. The middle part is highlighted twice.
In this "Select mode", Only the row should be highlighted.

Screen Shot 2022-07-12 at 10 42 52

### Steps to reproduce

The minimal reproduction project has two trees. Selecting an item on each tree will show that the problem happens with both the "Selected" and "Selected Focus" highlights.

Both item's buttons are bellow the highlights. The "Selected Focus" style override on one of the trees can be changed to a solid color to verify that the buttons on that tree will no longer be visible when the item is selected.

### Minimal reproduction project

[tree-bug-test.zip](https://github.com/godotengine/godot/files/9096070/tree-bug-test.zip)

### PR DESCRIPTION
**Pull request by marzecdawid**
Fixes #62951

obraz

### CODE REVIEW

**Comment by YuriSizov** [comment]
I've rebased this PR just in case, but this doesn't seem to be a correct solution. The code that you have moved affects some global properties (namely, `w`) which are used below the old code, but above the new code. This means that the adjustments are no longer applied and the math is wrong.

What should be done is the computing code and the drawing code should be split. Computing code should remain at the top, and the drawing code can be moved lower, so that the buttons are drawn on top of everything.

**Comment by marzecdawid** [comment]
@YuriSizov It should be correct now.

**Comment by YeldhamDev** [comment]
Analyzing the code, wouldn't it be simpler to just move the two button-related code blocks down instead of adding another `for` loop?

**Comment by YuriSizov** [comment]
@YeldhamDev Please see the above discussion. Those code blocks affect some scope variables which are used by other, intermediate code.

**Comment by YeldhamDev** [comment]
@YuriSizov I saw it and already deleted the comment, but I guess I wasn't fast enough to avoid a reply. :stuck_out_tongue:

**Review by YuriSizov — APPROVED** [review]
Code looks good to me. There is a lot of room for improvement, but we need someone brave to do a complete refactoring. But this should work to solve the issue :)

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
