### PR TITLE
Convert `OpenSimplexNoise` to `FastNoiseLite`

### PR DESCRIPTION
**Pull request by Maran23**
This PR adds the conversion of:
- `OpenSimplexNoise` to `FastNoiseLite`
- Noise property `octaves` to `fractal_octaves`.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by fhgaha** [comment]
What about other properties like period, persistence, lacunarity?

**Comment by Maran23** [comment]
> What about other properties like period, persistence, lacunarity?

`period` and `persistence` do not exist anymore. Therefore it is not easy to convert them.
We can consider converting `lacunarity`. As far as I can tell, it works the same, just got renamed to `fractal_lacunarity`.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.

**Comment by fireworx** [comment]
backport to 3.5 please :-)

**Pull request merged**
