### PR TITLE
Initial color management support

### PR DESCRIPTION
**Pull request by ghost**
This adds LUT based color management on the Rasterizer layer, to ensure that all content blitted
to screen are processed exactly once. `Rasterizer::set_screen_lut` and `VisualServer::set_screen_lut` are added. Implemented for both GLES3 and GLES2.

The feature is accessible under Editor Settings / Interface / Color Management. It depends on LittleCMS to handle ICC profiles. This implements #26826.

- - -

EDIT: Updated OP to reflect current state of the branch. Again.

### CODE REVIEW

**Comment by Calinou** [comment]
> The feature is put behind a new command line flag --cm-lut, as I don't believe the interface is suitable for end users yet. Note that the flag is lost when you open an editor from the project manager.

Would this be better suited as an editor setting? This way, it would be preserved when editing a project using the Project Manager.

**Comment by toasteater** [comment]
> Would this be better suited as an editor setting? This way, it would be preserved when editing a project using the Project Manager.

Possibly, although I don't think it's very easy to use right now You still have to generate the LUT outside Godot somehow. I think an option for an ICC profile would be more fitting for an editor setting, in that it's an "easy" interface. That requires dependency (or a new ICC profile parser) however.

I can make it an editor setting if that's ok. Could you enlighten me a bit on the proper place in the code base to add a new setting?

**Comment by JFonS** [comment]
Related to #26101 by @QbieShay.

**Comment by toasteater** [comment]
#26101 and this PR address different needs. The former is for "in-game" grading (artistic effect), while this one is for global output gamut conversion (sRGB -> device gamut), intended to be used with the editor.

**Comment by groud** [comment]
I am not sure this needs to be in the core. I think it might better suit a plugin.

**Comment by toasteater** [comment]
> I am not sure this needs to be in the core. I think it might better suit a plugin.

This needs to happen in Rasterizer to ensure that all outputs to screen are processed *exactly once*. I'm not aware of a way to plug into the Rasterizer. This cannot be a Node because:

* A Node can be added multiple times. As a result, some content can be transformed more than once.
* A Node is not guaranteed to be processed as the last step of rendering. As a result, some content may get rendered without being transformed.

Because this feature is for color space conversion, *not* artistic effect, both situations are entirely undesirable. That leaves me no options other than putting it in the core. For more detailed background of this PR please see #26826.

**Comment by toasteater** [comment]
Minor correctness fix in the shader and rebased on current master.

Moved clamp before texel alignment, so in the off case that HDR data is passed to this shader it would not wrap and print bad colors.

**Comment by toasteater** [comment]
I have pushed an alternate version which allows users to choose an ICC profile in editor settings. It depends on [LittleCMS](http://www.littlecms.com/) for profile handling.

@Calinou Do you think this is better?

**Comment by groud** [comment]
It does not need to be in the rasterizer. You can use a screen shader to do so.

**Comment by toasteater** [comment]
> It does not need to be in the rasterizer. You can use a screen shader to do so.

So where do I apply this screen shader?

**Comment by groud** [comment]
I would say by using a Color rect node, taking the full scree size, and using SCREEN_TEXTURE as input. But indeed that requires that you have only one of them, and  that it is put on top of your display. 

But I mean, it might be OK as built-in, as long as it is a needed feature. Which I am not sure it is in the general case.

**Comment by Zireael07** [comment]
SCREEN_TEXTURE does not take into account stuff using transparent pipeline, though (so anything with alpha won't show)

**Comment by QbieShay** [comment]
@groud in that case I vote for world environment

**Comment by groud** [comment]
> @groud in that case I vote for world environment

Yeah it might make sense there.

**Comment by toasteater** [comment]
@groud I'm not exactly sure how I can make sure that the ColorRect stays where it should without touching core stuff. AFAIK anyone can just place Nodes where they like.

I certainly believe this is needed as I need it, but I do understand that the rest of the community may not care about working with other color managed applications. If the community decides that this is unnecessary I'll respect the verdict.

@QbieShay This feature and your contribution work together. Where artist can use your tools to convey their vision, color management ensures that the exact vision is shown on the screen as correctly as possible.

**Comment by groud** [comment]
> AFAIK anyone can just place Nodes where they like.

Yeah, but that's not a problem. It is not up to us to check if users are using a node correctly (we must document things though) It's like, you cannot complain about one of your camera not working if you put cameras in your tree.

Anyway, I think that if it should be built in it has to be a parameter of a WorldEnvironment node, as @QbieShay suggested.

**Comment by toasteater** [comment]
> > AFAIK anyone can just place Nodes where they like.
> 
> Yeah, but that's not a problem. It is not up to us to check if users are using a node correctly (we must document things though) It's like, you cannot complain about one of your camera not working if you put cameras in your tree.
> 
> Anyway, I think that if it should be built in it has to be a parameter of a WorldEnvironment node, as @QbieShay suggested.

It appears that you have misunderstood the purpose of [color management](https://en.wikipedia.org/wiki/Color_management). This is not related to WorldEnvironment and is not something artists tweak or even put into the end game. It's for the editor itself, so that colors are correctly translated from sRGB to the color space of your monitor, so that they do not appear [over-saturated and blown out](https://github.com/godotengine/godot/issues/26826).

WorldEnvironment does not work with 2D and most importantly does not reach the Editor UI, so it doesn't cover the use case at all.

**Comment by groud** [comment]
Ah indeed sorry. If it's required for specific hardwares and in the editor it indeed has to be built in. Sorry for the inconvenience.

**Comment by toasteater** [comment]
No inconvenience felt. It's sad but true that color management is little known or understood outside the artist/photographer crowd, but it's a great thing and we should work to make it more mainstream!

**Comment by toasteater** [comment]
Added support for GLES2.

I accidentally created a doppelganger commit while rebasing which triggered a review from neikeq because apparently I can't count commits...

**Comment by toasteater** [comment]
Rebased on current master branch.

**Comment by Megalomaniak** [comment]
> Ah indeed sorry. If it's required for specific hardwares and in the editor it indeed has to be built in. Sorry for the inconvenience.

Unnecessary perhaps, but to add furthermore to this, godot has been claiming linear workflow to be supported this whole time where it seems to me that has not been the case. If color management was not properly supported up to now, then any linear workflows/content pipelines were effectively broken this whole time, too. That is admittedly assuming artists working both in their dedicated DCC's as well as evaluating their assets in editor.

**Comment by toasteater** [comment]
@Megalomaniak This PR adds display profile awareness (sRGB to device space, i.e. "Color Management" as in Krita/Photoshop/GIMP/...) to Godot. For conversion from scene linear to sRGB (i.e. "Color Management" as in Blender), you'll want to look at Godot's scene rasterizer and the tonemapper options in the Evironment resource.

What you're referring to is not in the scope of this PR, and would have the best chance of getting considered/implemented by the community if you create a new issue for it.

**Comment by Megalomaniak** [comment]
Yes, I understood that, but as I said, this is important too for those that are evaluating their work in godot. That is exporting from dcc and then importing to godot to view it there.

**Comment by fire** [comment]
Is it possible to get Window's device LUT automatically?

**Comment by fire** [comment]
Little CMS has a thread on the topic of getting Window's default device profile. https://sourceforge.net/p/lcms/mailman/message/19649917/

**Comment by fire** [comment]
This pr should get the ability to get Godot's current monitor and that monitor's device profile and set it as the screen lut.

Platforms:
* Windows 10
* Mac
* Linux
  * May be specific to the desktop manager? Will need investigation.

**Comment by fire** [comment]
Can you update https://github.com/godotengine/godot/blob/master/thirdparty/README.md for the license information of LCMS?

**Comment by toasteater** [comment]
> Can you update https://github.com/godotengine/godot/blob/master/thirdparty/README.md for the license information of LCMS?

@fire This PR does contain an update to that file. See https://github.com/godotengine/godot/pull/26869/files#diff-6a71cf880a735be694f22266c46ec066

> This pr should get the ability to get Godot's current monitor and that monitor's device profile and set it as the screen lut.

I agree that the feature is nice to have, but I don't believe it's immediately necessary for this PR to work. I think it's more appropriate as a separate PR, after/if the base functionality get merged.

**Comment by fire** [comment]
Sounds good.

**Comment by toasteater** [comment]
Rebased and resolved merge conflicts.

**Comment by fire** [comment]
Some errors compiling on windows:

```
1>cl : Command line warning D9025: overriding '/w' with '/W3'
1>cl : Command line warning D9002: ignoring unknown option '-std=c99'
1>cl : Command line warning D9002: ignoring unknown option '-O3'
1>cmscgats.c
1>thirdparty\lcms2\cmscgats.c : warning C4828: The file contains a character starting at offset 0x2748 that is illegal in the current source character set (codepage 65001).
```

Will report what happens when I start Godot.

**Comment by fire** [comment]
I tried the PR it works. If I apply the icm profile twice by removing it and apply it. The twice application causes the editor to turn darker than normal. Not sure if it's related.

image

**Comment by fire** [comment]
Here is some research for how to fetch the device's icc profile and links:

* https://stackoverflow.com/questions/13533754/code-example-for-wcsgetdefaultcolorprofile
* Posted a question for OSX (https://stackoverflow.com/questions/56898204/get-osx-icc-default-color-profile-from-c)

**Comment by toasteater** [comment]
> If I apply the icm profile twice by removing it and applying it causes the editor to turn darker than normal. Not sure if it's related.

@fire There is an unrelated bug in Godot where the background dim from modal dialogs (e.g. engine settings & file browser) will persist after closing in some cases. That one looks like what you're getting. It may have something to do with the lag that LUT generation introduces, but I don't think fixing that within this PR's scope.

> errors compiling on windows

I'll check the build scripts on Windows as soon as possible.

> how to fetch the device's icc profile

Thanks for the pointers. I'll get to it after/if the base functionality get merged.

**Comment by fire** [comment]
@toasteater Can you point me to the bug number for the background dim?

**Comment by toasteater** [comment]
@fire Didn't find an existing report, so I reported it at #30368, along with a way to reproduce it.

**Comment by akien-mga** [comment]
Since this impacts the renderer and conflicts with the work done in the `vulkan` branch, this will have to wait for after the 3.2 release to be merged. At that point it will also need to be rebased once the `vulkan` branch is merged in `master`.

It can still be reviewed and tested as is, but merging it now would make rebasing the `vulkan` branch trickier (and this wouldn't be implemented for Vulkan either).

**Comment by fire** [comment]
@toasteater Since the vulkan branch has a 2d branch in theory we could try this in the editor.

**Comment by toasteater** [comment]
@fire I don't see a separate 2d branch. Maybe I don't have the permissions? In any case I'd rather wait until things get more stable, after it's merged in `master` at least. 4.0 still seems very far away, I don't think rebases make sense currently.

That's said, if anyone wants to pick this feature up and start maintaining it for vulkan right now, please feel free to do so. From what I've seen about the `vulkan` branch, you probably have to do the rasterizer stuff from scratch, so the only thing you could reuse is the `cm` module, which is just rather trivial glue. If anyone is interested, please let me know!

**Comment by toasteater** [comment]
Closing because I no longer have the intention to port the feature to 4.0. Again, if anyone is willing to pick this up, please feel free to do so.

**Comment by fire** [comment]
I want to have this feature in 4.0

**Comment by toasteater** [comment]
There are two commits in this PR. The first one adds LUT support at `Rasterizer` level, and the second one adds `lcms` glue and the user interface. Only the first one should conflict with `vulkan`.

I think if you implement `set_screen_lut` and modify `blit_render_targets_to_screen` for `RasterizerRD`, you can just cherry-pick the second commit and it should just work. For `blit_render_targets_to_screen` you need to write a shader to sample the LUT. Texel offset must be taken into consideration, or you'll get wrong colors from interpolation. The LUT itself is a cube texture with X as R, Y as G, Z as B.

The sampling has to happen at `blit_render_targets_to_screen` (instead of, say, during tonemapping), to ensure that everything is transformed once and only once.

**Comment by fire** [comment]
@toasteater Is it ok to change the design so the lut is per rendertarget?

**Comment by toasteater** [comment]
Why would you want to do that? How are you going to make sure the colors are transformed exactly once?

**Comment by fire** [comment]
I was trying to figure out how to do per screen effects, but godot doesn't have an api for that.

**Comment by toasteater** [comment]
I believe Godot is single-windowed-only at this moment? I don't think window managers allow us to see which part of the window is on which screen anyway. I have only seen applications that switch profiles depending on which screen it's mostly staying on, but not ones that do split rendering. It's probably too much work to be worthwhile for most cases.

**Comment by toasteater** [comment]
Also, there were a lot of misunderstandings in the thread, and I see that it still persists, so I think it bears repetition here at the bottom:

Please do bear in mind that this is **NOT** for artistic effects. It **DOES NOT** replace the environment effect that is called "color correction", which should be used for artistic effects. It should not be applied in any way, other than **for each pixel rendered to the screen, uniformly, and exactly once, as the last step of rendering**. Literally any other way to use it is a misuse.

**Comment by fire** [comment]
I am salvaging this.

**Pull request closed without merging**
