### PR TITLE
Fix right-click on tilset atlas popup wrong position

### LINKED ISSUE #71327: TileSet editor cell's context menu position is incorrect
### Godot version

Godot 4.0 beta 11

### System information

Windows 10, all renderers, Nvidia GTX1060

### Issue description

The position of the right mouse context menu is correct ONLY on my first display and the Godot editor is fullscreen, in other scenarios the context menu position is off.
Both my displays are 4K.
image

### Steps to reproduce

Editing a tileset and clicking with the right mouse clicking on the tileset cell for context menu to appear (Create a tile/ Create alternate tile or delete cell).

### Minimal reproduction project

[TileSet reproduction.zip](https://github.com/godotengine/godot/files/10411935/TileSet.reproduction.zip)

### PR DESCRIPTION
**Pull request by groud**
Fixes [#71327](https://github.com/godotengine/godot/issues/71327)

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Sauermann** [comment]
Technically you are adding points of different coordinate systems:
- `get_screen_position()` is in Screen/Viewport coordinates
- `get_local_mouse_position()` is in CanvasItem-local coordinates

I didn't look in depth into this, but could you test, if the PR works, if the editor has a non-default Display Scale and is not in Single-Window-Mode? If not, you could try instead of the addition:
`get_screen_transform().xform(get_local_mouse_position())`

Conceptually the conversion to the Screen coordinates was definitively missing.

Maybe you could extend this PR to address
https://github.com/godotengine/godot/blob/e514e3732a9588b650776cc962a9e4d8e6ded058/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L1976

**Comment by groud** [comment]
> get_screen_transform().xform(get_local_mouse_position())

This seems indeed cleaner. I'll test it.
And yeah, I need to fix the issue in the other place, you are right. I'll amend the PR.

**Comment by groud** [comment]
Done. I also fixed a similar issue in AnimationLibraryEditor.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
For the record, there's a few more cases of this `get_screen_position() + get_local_mouse_position()` which could be worth reviewing:
```
$ rg get_screen_pos.*get_local_mouse
scene/gui/line_edit.cpp
251:                    menu->set_position(get_screen_position() + get_local_mouse_position());

doc/classes/Control.xml
427:                            popup_menu.position = get_screen_position() + get_local_mouse_position()

editor/editor_audio_buses.cpp
759:    delete_effect_popup->set_position(get_screen_position() + get_local_mouse_position());

editor/plugins/visual_shader_editor_plugin.cpp
3821:                   Point2 gpos = get_screen_position() + get_local_mouse_position();
3840:           Point2 gpos = get_screen_position() + get_local_mouse_position();
4682:                   _comment_title_popup_show(get_screen_position() + get_local_mouse_position(), selected_comment);
4685:                   _comment_desc_popup_show(get_screen_position() + get_local_mouse_position(), selected_comment);

editor/plugins/animation_blend_tree_editor_plugin.cpp
390:    add_node->get_popup()->set_position(graph->get_screen_position() + graph->get_local_mouse_position());

editor/plugins/script_editor_plugin.cpp
3086:   context_menu->set_position(get_screen_position() + get_local_mouse_position());

editor/animation_track_editor.cpp
2821:                           menu->set_position(get_screen_position() + get_local_mouse_position());

editor/editor_inspector.cpp
709:            menu->set_position(get_screen_position() + get_local_mouse_position());

editor/scene_tree_dock.cpp
2604:                   menu_properties->set_position(get_screen_position() + get_local_mouse_position());
2972:           filter_quick_menu->set_position(get_screen_position() + get_local_mouse_position());

editor/debugger/editor_debugger_tree.cpp
120:    item_menu->set_position(get_screen_position() + get_local_mouse_position());
```

**Comment by Sauermann** [comment]
From a quick look, there are several occurrences of `get_screen_position` which look problematic in "scene/gui". I should probably investigate them after my `get_screen_transform`-fix gets merged.

**Pull request merged**
