### PR TITLE
See: #29878 Added ERR_FAIL_COND checks for `Ref<AnimationNode>` in `AnimationNodeStateMachine::remove_node`

### LINKED ISSUE #29879: Editor crash in AnimationNodeStateMachine::remove_node
**Godot version:**
3.2.dev.custom_build. 0f543ba99

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f1bca1d7f60] (??:0)
[2] HashMap<StringName, Object::Signal, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::getptr(StringName const&) (/home/rafal/Pulpit/godot/./core/hash_map.h:318)
[3] Object::_disconnect(StringName const&, Object*, StringName const&, bool) (/home/rafal/Pulpit/godot/core/object.cpp:1542 (discriminator 2))
[4] Object::disconnect(StringName const&, Object*, StringName const&) (/home/rafal/Pulpit/godot/core/object.cpp:1538)
[5] AnimationNodeStateMachine::remove_node(StringName const&) (/home/rafal/Pulpit/godot/scene/animation/animation_node_state_machine.cpp:602 (discriminator 5))
[6] MethodBind1<StringName const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1920)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x138a9a1] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f1bca1bab6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x138a80a] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 79fc7368fc0e5cbb144f5869a0122bb74274a2f8
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/79fc7368fc0e5cbb144f5869a0122bb74274a2f8.zip

### PR DESCRIPTION
**Pull request by Dentrax**
Fixes #29879

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Travis is complaining about trailing tabs, but there's none in the actual code.

**Comment by akien-mga** [comment]
GitHub does not show it properly, but there is a trailing tab in the patch: https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/29883.patch

**Comment by akien-mga** [comment]
BTW, this change is also in #29878, so it should be either removed there, or kept there and this PR closed.

**Comment by Dentrax** [comment]
@akien-mga Oh, I didn't realize that. I am going to close this. In addition, i don't know how to remove _trailing tab_. How can I fix it?

**Comment by akien-mga** [comment]
@Dentrax There is an unnecessary tab indent on this line: https://github.com/godotengine/godot/pull/29883/commits/612c2e84a85e0214b3750fec0f847fb66096f92c#diff-bcfe4b035701d43316a3aa6b57a40e4bR602

Since there is no content after this tab, it's called a "trailing" tab as it comes at the end of the line and is thus unnecessary whitespace. The `clang-format` tool we use to enforce the style guide will complain about those.

To fix it, you should open the file, remove this tab indent, `git add` the file and `git commit --amend` to edit the commit, which you can then `git push --force` to update the PR.

**Pull request closed without merging**
