### PR TITLE
Fixed crash if passing invalid image ref to TextureLayered

### PR DESCRIPTION
**Pull request by Chaosus**

### CODE REVIEW

**Comment by Chaosus** [comment]
Hmm.. maybe it's reasonable to add such check to VS::texture_set_data_partial which potentially can fix several other crashes.

**Comment by bojidar-bg** [comment]
Not sure about it, but shouldn't passing a `null` image to a certain layer clear that layer?

**Comment by Chaosus** [comment]
If you pass null it will crash because texture_set_data will implicitly try to get access for the reference

**Comment by Calinou** [comment]
@Chaosus Speaking of TextureLayered, would you happen to know how to fix #34312?

**Comment by Chaosus** [comment]
@Calinou The difference from existed behavior is this line:

image

It will prevent to call that function if the invalid image is passed:

image

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
