### PR TITLE
More info on global menu usage

### PR DESCRIPTION
**Pull request by zoeesilcock**
* Clarify that the `Callable` passed to various `DisplayServer.global_menu_***` methods require a single argument, otherwise they won't be called.
* Fix a typo where the word label read labe instead.

### CODE REVIEW

**Review by realkotob — APPROVED** [review]

**Comment by realkotob** [comment]
Is it possible to clarify better what the Callable will get as a passed value?

> it will contain the tag associated with the menu item.

I tried finding the location in the codebase where the Callable is getting called but I could not find.

**Comment by zoeesilcock** [comment]
Sure, the value will be whatever value was passed to the `tag` parameter when the menu item was created. I'm guessing this is to allow using the same callback for multiple menu items and then doing different things depending on which tag is received.

Do these descriptions make it clearer?

global_menu_add_*** (these methods accept the parameter in question so we can refer to it directly):

> it will contain the value passed to the [param tag] parameter.

global_menu_set_item_[callback/key_callback] (these methods don't accept the parameter in question):

> it will contain the value passed to the tag parameter when the menu item was created.

**Comment by realkotob** [comment]
@zoeesilcock Thank you for clarifying these descriptions do make it clearer 👍 

Just to be clear, when you say "it will contain" you mean that the callable parameter is an object that _contains_ the tag property, or is this parameter the tag property itself?

We could add a simple property access code example to clear up the confusion in case it is the former, like:

```
func set_item_callback(result):
    print(result.tag) # This is the tag property set on the menu item
```

I apologize for nitpicking on this 🙏  Just trying to make sure it's clear when I myself have not seem the code for it.

**Review by bruvzg — COMMENTED** [review]
Seems good. But it might be worth adding an extra note to encourage use of MenuBar node instead of using DisplayServer API directly.

**Comment by zoeesilcock** [comment]
@realkotob No worries on nitpicking, this is my first PR on this project and I wasn't able to find an example of how to describe the method signature needed for a callback, so your input is appreciated.

What I was trying to describe is that the parameter that is passed to the callback is whatever value was passed to the `tag` parameter when creating the menu item.

Based on your example the correct code would be:
```
func set_item_callback(tag):
    print(tag) # This is the tag property set on the menu item
```

I have changed the wording to this:

> The [param callback] and [param key_callback] Callables need to accept exactly one Variant parameter, the parameter passed to the Callables will be the value passed to [param tag].

and this:

> The [param callback] Callable needs to accept exactly one Variant parameter, the parameter passed to the Callable will be the value passed to the tag parameter when the menu item was created.

Unfortunately I haven't found where the callback i actually called. I learned about this by trial and error when trying to troubleshoot why the callback wasn't being called. Looking at how Godot uses these methods internally was what gave me the clue that it needed a parameter. You can see an example by looking at the callback provided at `editor/project_manager.cpp:1283`. The callback itself is defined on line 1399 and shows the tag parameter in question.

@bruvzg that sounds like a good idea. I would have to do some testing with that Node in order to know exactly what to suggest. I was working on updating one of the demos in the godot-demo-projects which uses the DisplayServer directly so I wasn't aware that it can be done via the `MenuBar` node also.

**Comment by realkotob** [comment]
@zoeesilcock The changes look good to me, this is much clearer now 🙏 

There are the changes suggested by bruvzg but that can be added in another PR when you have had time to check out how MenuBar works.

**Review by realkotob — APPROVED** [review]
@zoeesilcock The changes look good to me, this is much clearer now 🙏 

There are the changes suggested by bruvzg but that can be added in another PR when you have had time to check out how MenuBar works.

**Comment by Calinou** [comment]
Should the [Operating System Testing demo](https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/misc/os_test) be adapted to use MenuBar in the long run?

**Comment by zoeesilcock** [comment]
This PR is ready to merge from my perspective.

**Review by aaronfranke — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by zoeesilcock** [comment]
@akien-mga Sure, I can squash it down to a single commit. I thought squashing was for extraneous commits like fixes to input. In this case it's two different changes that weren't related to input so I assumed it would be better for git history to keep them as separate commits.

Thanks for the input. Just a heads up that the URL you referred to appears to have changed in the latest version of the docs. Seems to be this now: https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase

**Comment by akien-mga** [comment]
You're right, but "Fix a typo" commits in the Git history aren't very useful so if we can avoid it by including it together with another update to the same class, that's better. That helps keep the history readable (and _slightly_ reduces the amount of steps needed when bisecting regressions, especially if close to that change).

> Just a heads up that the URL you referred to appears to have changed in the latest version of the docs. Seems to be this now: [docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

Thanks, fixed!

**Comment by zoeesilcock** [comment]
Fair enough, thanks for the clarification!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
