### PR TITLE
Fix issue when switching between FileSystem and other editor docks

### LINKED ISSUE #5384: Scene/Filesystem panel resizes on switch
**Operating system or device - Godot version:**
Issue started at an unknown point in previous commits (after Node panel was introduced) and persists in current (9e0b605) master

**Issue description** (what happened, and what was expected):
When putting the Scene and Filesystem panels to share space, switching to Filesystem resizes the panel layout for no clear reason, as seen in these screenshots. It doesn't matter if you manually enlarge the area vertically, Filesystem will always take space away from the bottom panels. (so greedy)
ihbl1jq tkqodnn

This is a minimal thing, a papercut if you will, but there's no obvious reason for it to behave like this.

**Steps to reproduce:**
Put Scene and Filesystem panels in the same position, with other panel at the bottom, and switch between them.

### PR DESCRIPTION
**Pull request by samuelgrigolato**
Fix #5384.

### CODE REVIEW

**Comment by vnen** [comment]
Thanks for the contribution. But two things: Add "Fix #5384" to the PR description, so if this is merged the related issue will be automatically closed. And it would be good if you rebased your branch to get rid of that merge commit, since those types of commits add no value to the history.

**Comment by samuelgrigolato** [comment]
@vnen alright, did it! Now, about the rebase thing, do I need to close this PR and open another one? Or are you just saying it for the next time?

**Comment by akien-mga** [comment]
You can rebase your branch (`git rebase`) and force push (`git push --force`), it will update the PR.

**Comment by samuelgrigolato** [comment]
@akien-mga well.. it seems like I got it right now.. thanks very much!

**Comment by reduz** [comment]
Please guys don't merge these kind of PRs without trying to understand what they do. Such lines of code are there for a reason, so randomly removing them will not fix things.

In this case, This broke the panel when used in full height.

image

**Comment by akien-mga** [comment]
Right, my bad.

**Pull request merged**
