### PR TITLE
Clip text in EditorPath button to avoid dock size changes

### LINKED ISSUE #33741: The "Inspector" dock resizes itself when selecting a node with a long name
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
win10 64 home

**Issue description:**
Selecting some nodes causes the editor (the inspector doc) to resize windows called "docs" by itself.
I think that should not happen, simply if there is not enough space all the editors draw what fits in the space.

Size resizing occurs in the "Inspector" and "Node" right zone.

**Steps to reproduce:**
Simply select the "AnimationPlayer" node and then the "CollisionShape2D" node.

In the gif you can see that I allocated a lot of space and still, the editor is still resizing.
This cannot happen even if there is not enough space, the buttons and all panels must maintain their fixed position as long as the user does not change it.

GIF

This cannot be a problem of space because there is enough room to draw everything.

GIF

**Minimal reproduction project:**
[testEditor.zip](https://github.com/godotengine/godot/files/3864967/testEditor.zip)

### LINKED ISSUE #35324: 3.2 RC1 Regression.  Inspector panel sizes change when using debugger.
**Godot version:**
3.2 RC1

**OS/device including version:**
Win10 64-bit

**Issue description:**
When I step through code using the debugger the inspector now changes size and quickly changes back.  This misplaces the buttons which can result in mis-clicking, and it is very jarring when trying to watch where the code is stepping to.

Not happening in the versions of 3.1 I have been using.

May be related to:  https://github.com/godotengine/godot/issues/33741

ezgif com-video-to-gif

**Steps to reproduce:**
Step along a GDScript break point.

**Minimal reproduction project:**
Any project will do.

### LINKED ISSUE #35367: The "Signals" dock's size jumps when selecting nodes
**Godot version:**
3.2 RC2

**OS/device including version:**
Windows 10

**Issue description:**
When selecting and deselecting nodes in editor, the signals dock changes its horizontal size suddenly.

f8DSWpNyiA

The issue is present in 3.2 RC2, goes through to as far as 3.2.beta1 and is not present in 3.1.2.stable.

May be related to #33741 and #35324

**Steps to reproduce:**
Add a node, select it, see the signal dock change its size.

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #33741.
Fixes #35324.
Fixes #35367.

### CODE REVIEW

**Comment by avencherus** [comment]
Wow that was fast.  Thanks for the quick response.

I did a rebuild with this, appears to solve the three issues, so they are one and the same.

**Comment by YeldhamDev** [comment]
@avencherus Even #35367? That doesn't even use `EditorPath`. Must be because the dock also takes hidden tabs into account.

**Comment by akien-mga** [comment]
Thanks!

**Comment by avencherus** [comment]
> @avencherus Even #35367? That doesn't even use `EditorPath`. Must be because the dock also takes hidden tabs into account.

@akien-mga @YeldhamDev My mistake, I missed that I have a different layout than him, but on reconfiguration and double checking, when the signal dock is split apart it does suffer from shifting about.  https://github.com/godotengine/godot/issues/35367 is unrelated and can be re-opened.

**Pull request merged**
