### PR TITLE
Implement exponential operator (**) to GDScript/Expressions

### LINKED ISSUE #1045: Add exponentiation operator (**) to GDScript
**Describe the project you are working on:**
A game

**Describe the problem or limitation you are having in your project:**
There is no exponentiation operator in GDScript. There is only the `pow()` function, which is a bit inconvenient.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
1. `A ** B` does not add extra parentheses
2. `A ** B` little shorter than `pow(A, B)`
3. the infix operator is more familiar than the prefix function

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
`A ** B == C`, where `A`, `B`, `C` are `float`, `C == pow(A, B)`

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, you cannot add your own operators in GDScript.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Yes. This is available in many programming languages, for example, JavaScript, Python.

### LINKED ISSUE #1580: Add exponentiation operator (`**`) to the Expression parser
**Describe the project you are working on:**
A Game

**Describe the problem or limitation you are having in your project:**
The `Expression` Parser does not support `**` as a `pow` operator. While `pow(a,b)` may have a better readability when used in a complex expression it is way slower to write than `a**b`. Especially in the case of Input fields, where the expression is lost after submitting, I don't think a lot of people will write smaller expressions more often then complex ones.
With pull request [godotengine/godot#42376](https://github.com/godotengine/godot/pull/42376), this problem is increased due to commas no longer working in EditorSpinSlider.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add `**` to the operators for the `Expression`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
In `expression.cpp`:
Add Token `TK_OP_POW` in `_get_token` and the operator switch in `_parse_expression`.
Add Variant `OP_POW`, here we need to put it between `OP_NEGATE` and `OP_MULTIPLY` i.e. increase the `priority` for everything >= `OP_MULTIPLY` by one and give `OP_POW` `priority = 1`.
In `variant_op.cpp`:
Add `OP_POW` to `CASES(PREFIX)`, in `evaluate` the basic Case is obviously numbers, but at least for `a**b, b ∈ ℤ` most things that work for Multiplication could be adopted, this would make this more versatile than the `pow` function.

**If this enhancement will not be used often, can it be worked around with a few lines of code**
The basic version should be about 20 lines of code, implementing more functionality would increase that by a bit.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It could not be easily done by an add-on, and it could be implemented parallel to #1045, so that both gdscript and the number input use the same syntax.

**I am able to make a pull request for this, at least for a basic numbers only version.**

### PR DESCRIPTION
**Pull request by Chaosus**
Added a support for pow operator to GDScript and Expressions:

pow_expression

Closes https://github.com/godotengine/godot-proposals/issues/1045
Closes https://github.com/godotengine/godot-proposals/issues/1580

### CODE REVIEW

**Comment by Mickeon** [comment]
Aah, I wish **^** wasn't reserved for the Bitwise XOR in GDScript, too. It would've been a nice opportunity to make it closer to the mathematical symbol, but I do digress.

Because of Python's influence, would it mean that, should this PR get merged, the Floor Division operator would be added, as well?

**Comment by Chaosus** [comment]
> Aah, I wish ^ wasn't reserved for the Bitwise XOR in GDScript, too. It would've been a nice opportunity to make it closer to the mathematical symbol, but I do digress.
> 
> Because of Python's influence, would it mean that, should this PR get merged, the Floor Division operator would be added, as well?

Well, if the community have an interest in it - then why not? But as a proposal its better to be show on the godotengine/godot-proposals first.

**Comment by Mickeon** [comment]
Never mind about the Floor Division proposal. [It didn't go so well last time](https://github.com/godotengine/godot-proposals/issues/1866).

**Comment by Chaosus** [comment]
> Never mind about the Floor Division proposal. As a point of reference, https://github.com/godotengine/godot-proposals/issues/1866.

Ah, I see. Than maybe it may be a source of confusion and not so needed for games as for a python developers.

**Comment by reduz** [comment]
Variant already provides the pow() function as builtin method. I would not add this to Variant as its more bloat. It can be simply syntax sugar in Expression and GDScript that ends up calling pow() internally.

**Comment by Chaosus** [comment]
@reduz To be honest without adding it to Variant is much more "bloating" to do it rather than otherwise.

**Review by fire — COMMENTED** [review]
Agree with reduz that this addition duplicates the pow function and adds confusion.

**Comment by Chaosus** [comment]
I decided to cut off the GDScript part of this PR - and leave only the change to Expression parser, If this change would be desired and merged - I will probably make another PR to target scripting language.

**Review by reduz — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks good to me, there's just a stray `modules/gdnative` that got re-added and should be removed.

**Review by vnen — APPROVED** [review]

**Comment by Chaosus** [comment]
@akien-mga Done, I've removed it!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
