### PR TITLE
Toggle checkable items in PopupMenus when activating them

### PR DESCRIPTION
**Pull request by MystMagus**
At the moment the checkable items feature doesn't seem to work.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Can you please open an issue report tracking this so it can be investigated and discussed

**Comment by KoBeWi** [comment]
The current behavior is intended, see the documentation:
> Note: Checkable items just display a checkmark, but don't have any built-in checking behavior and must be checked/unchecked manually. See set_item_checked() for more info on how to control it.

**Comment by MystMagus** [comment]
Huh. That's weird but okay.

**Comment by MystMagus** [comment]
No, I get it more or less. It does allow for mixing behaviors in more complex ways, though it requires more manual setup.

**Pull request closed without merging**
