### PR TITLE
GDScript: unpacking of arrays using Python-like syntax

### PR DESCRIPTION
**Pull request by ghost**
Probably @bojidar-bg is already working on something like this, but if not, this is a proposal how to add simple multiple return values to gdscript (without having to use `[...]`), i.e.:

```
func f():
    return 10, 20

func g():
    var a
    var b
    a, b = f()
```

Internally it returns a vector. Note that this is bare bones (no `*` operator or the like). No bytecode changes either.

### CODE REVIEW

**Comment by poke1024** [comment]
Added variable unpacking inside `for` and `enumerate`, so you can now do:

```
for i, x in enumerate(["a", "b", "c"]):
    print(i, ": ", x)

> 0: a
> 1: b
> 2: c
```

Works for any iterable variant type.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by letheed** [comment]
@poke1024 How about keeping it less magical and more like destructuring/pattern matching?

```
func foo():
    return [1, 2]

func bar(dict):
    var [a, b] = foo()
    for [k, v] in dict.items():
        ...
```

**Comment by poke1024** [comment]
Moved `enumerate` to separate PR https://github.com/godotengine/godot/pull/15562

**Comment by akien-mga** [comment]
We've discussed this PR on IRC today with many core developers, and decided that we'd go with the matcher-like syntax proposed in #15562 instead, so closing this one.

**Pull request closed without merging**
