### PR TITLE
Use `#pragma once` in all header files

### LINKED ISSUE #18143: Replace include guards to pragma once ?
`#pragma once` is more clean and error-prone method to defend headers from inclusion and supported on all compilers now. How about removes include guards and change them to `#pragma once` ?

### PR DESCRIPTION
**Pull request by Calinou**
Replaced using the guard2once command-line utility (which is part of [guardonce](https://github.com/cgmb/guardonce)).

This PR should be evaluated after 3.2 is released. Discussion in #18143 isn't over yet, but I figured we can have a PR open to merge it if we reach an agreement.

This closes #18143.

### CODE REVIEW

**Comment by RaTcHeT302** [comment]
compiled on win 10 1709 buld 16299.431
with scons -j 16 platform=windows vsproj=yes


please tell me what commands i should use, if you want a different result (because i don't know what to really do)

(can i provide the text scons spits out and anonymize it? would it help? for warnings and stuff)

i don't know what i'm doing (the custom release)


the current release (3.1.2)


the executable file, it compiled as debug
(because i have no idea, what commands to actually pass in scons, to make a release)
(sorry)

https://drive.google.com/file/d/1WoUQVDo7xGTfTCyjQjBUR8E3q3qpr4ha/view?usp=sharing

hash
godot.windows.tools.64.exe
F8F8A54C62076AEC38F170ACA258FCB6A09A1F233FB31268E3B09BD794614600

how much space it all took up (does this help in any way? i have no clue at all)


i don't have an actual game to test, i'm just figuring it all out as i go, i'm not a programmer so it'll take me a while

i don't know how to benchmark the compile times, is there a way for scons to just, type some benchmark data at the end for me? usually godot takes me 2 minutes to compile as debug

**Comment by RaTcHeT302** [comment]
can someone teach me how to do these things

- save a log from the compiler, with the stuff it says it did, all anonymized
- run an automated benchmark, between the current release, and the custom release
- run some automated tests (i don't have an actual game to test this with, there's no way to tell if there are any invisible problems)
- what scons commands to pass, and what builds should be compiled (release and debug can drastically differ, sometimes both builds might behave completely differently)

i have a ryzen 1700, and compiling doesn't seem to take too long as debug (2 minutes) - if it doesn't waste too much time, i could compile other builds to be safe

i'm used to the unreal engine 4 taking up to 45 minutes or an hour to compile... buuuut hopefully it won't take that long

**Comment by Calinou** [comment]
@RaTcHeT302 Please ask support questions on one of the other [community channels](https://godotengine.org/community), not here.

**Comment by RaTcHeT302** [comment]
@Calinou no you don't understand, you asked for people on Windows to compile this right? i wanted to be a bit more thorough

**Comment by Anutrix** [comment]
This should be fine for 3.2 once the conflict is resolved right?

**Comment by Anutrix** [comment]
I think it's time for this to be evaluated since 3.2(latest being 3.2.1) is out.

**Comment by akien-mga** [comment]
We discussed this on IRC a couple weeks ago: http://godot.eska.me/irc-logs/devel/2020-02-19.log (from 13:32). There are a few issues that come with using `#pragma once`, so there's no clear consensus to use it for now.

**Comment by aaronfranke** [comment]
Since there is no clear consensus as mentioned above, and the fact that this kind of PR gets conflicts very easily since it affects all header files, I'm closing this.

If it is desired to use `#pragma once`, this will have to be re-created from scratch. Therefore, I am explicitly not adding "salvageable". In the meantime, the discussion can continue in #18143.

**Pull request closed without merging**
