### PR TITLE
Fix for shader bug on window re-sizing when using stretch mode "viewport"

### PR DESCRIPTION
**Pull request by rippledodger**
Fix for #1571 and #2342 shader problem when using stretch mode "viewport" and re-sizing the window.

-Edit-
Before: http://gfycat.com/MistySpotlessGadwall (1.1 Stable)
After: http://gfycat.com/GrimAlarmedAphid

### CODE REVIEW

**Comment by LeonardMeagher2** [comment]
+1 this would help a lot


A work around for this, is to create a separate view port with the dimensions you want, then render to a texture and I use a texture frame that fits to the original view port, and set the scale mode to 2D

**Comment by akien-mga** [comment]
Nice work @rippledodger! Could you maybe merge the two commits into one, as the first one is broken without the second?

You can do it with ```git rebase -i HEAD~3``` and then replace "pick" by "fixup" in the line for 92d8890. Then save the changes and force push to your branch with ```git push -f```.

**Comment by rippledodger** [comment]
Merged the two commits using `git rebase -i HEAD~3` as suggested, now there is a bunch of conflicts that weren't there before.

Is there a way to fix this?

**Comment by akien-mga** [comment]
@rippledodger That's weird indeed. Assuming that the godotengine/godot repo is not already defined as an "upstream" remote in your local clone of your fork, could you try:

```
git remote add upstream https://github.com/godotengine/godot
git fetch upstream
git pull --rebase upstream master
```

To stay on the safe side, you can also before that format your commit as a patch using ```git format-patch f15bd9c``` so that you can easily restore it in a clean branch later on if anything goes awry :)

**Comment by reduz** [comment]
I'm not sure if i understand this, but the fix I think beats the purpose of the feature. I'll give it a better look as soon as I have a little time

**Comment by rippledodger** [comment]
@reduz I'm not sure what feature you're referring to, I'm actually addressing the issue described in #1571 which looks more like a bug than a feature.

@akien-mga Regarding my problems rebasing, if you click on the Commits tab in this page you can see commits that don't belong to me. If this fix actually becomes relevant I will create a new branch and push my changes there.

**Comment by akien-mga** [comment]
> I'm not sure if i understand this, but the fix I think beats the purpose of the feature. I'll give it a better look as soon as I have a little time

Closing then, I've referenced the relevant commit in #1571 so the work won't be lost anyway, @reduz can have another look at it when implementing his fix (or cherry-pick it directly if it's good enough).

**Pull request closed without merging**
