### PR TITLE
Fixes crash when exiting with --verbose with leaked resources

### LINKED ISSUE #44850: Godot crash when printing info about leaked nodes due to optional forced flush
**Godot version:**
3.2.4.beta.custom_build. adfc646f8 - but code is similar in version 4

Regression from  https://github.com/godotengine/godot/pull/44393 - CC @Calinou 

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When info about leaked nodes is printed, then Godot crash
```
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
   At: core/object.cpp:2132.
Leaked instance: GDScriptNativeClass:563
core/io/logger.cpp:234:7: runtime error: member access within null pointer of type 'struct ProjectSettings'
core/object.cpp:484:6: runtime error: member access within null pointer of type 'const struct Object'
handle_crash: Program crashed with signal 11
Dumping the backtrace. 
[1] godots() [0x13aec6a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fc0f58c6210] (??:0)
[3] Object::get(StringName const&, bool*) const (/mnt/Miecz/godot3.2/core/object.cpp:484)
[4] StdLogger::logv(char const*, __va_list_tag*, bool) (/mnt/Miecz/godot3.2/core/io/logger.cpp:234 (discriminator 2))
[5] CompositeLogger::logv(char const*, __va_list_tag*, bool) (/mnt/Miecz/godot3.2/core/io/logger.cpp:256 (discriminator 1))
[6] OS::print(char const*, ...) (/mnt/Miecz/godot3.2/core/os/os.cpp:132)
[7] print_line(String) (/mnt/Miecz/godot3.2/core/print_string.cpp:80 (discriminator 4))
[8] ObjectDB::cleanup() (/mnt/Miecz/godot3.2/core/object.cpp:2149 (discriminator 17))
[9] unregister_core_types() (/mnt/Miecz/godot3.2/core/register_core_types.cpp:313)
[10] Main::cleanup() (/mnt/Miecz/godot3.2/main/main.cpp:2299)
[11] godots(main+0x336) [0x13a5b5c] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:59)
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fc0f58a70b3] (??:0)
[13] godots(_start+0x2e) [0x13a576e] (??:?)
-- END OF BACKTRACE --
Przerwane (zrzut pamięci)
```

Relevant code - https://github.com/godotengine/godot/blame/adfc646f8cb497d520ea2238482ab674fe90d43a/core/io/logger.cpp#L234-L238

**Steps to reproduce:**
1. Run minimal project with this flags - `godot -e -q -v`

**Minimal reproduction project:**
https://github.com/jegor377/godot-gdgifexporter/archive/8e754c09dc10ec1f25ec2510c688bc1b35ee6b64.zip

### PR DESCRIPTION
**Pull request by groud**
Fixes #44850.

### CODE REVIEW

**Comment by groud** [comment]
cc @Calinou

**Review by Calinou — APPROVED** [review]
Looks good to me. I think it makes sense to always flush on every line if the ProjectSettings singleton isn't available.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4. (As part of the #44393 cherry-pick commit.)

**Pull request merged**
