### PR TITLE
Implement support for loading system fonts (on Linux, macOS / iOS and Windows).

### LINKED ISSUE #306: Allow to import system fonts from within Godot
**Describe the project you are working on:**
This applies to numerous projects, all using GUI.

**Describe the problem or limitation you are having in your project:**
Every time I create a new project that uses GUI, I inevitably fall into the same problem - I need a font. Now, I'm used to needing to find a TTF file and import it into project so that I can put some labels. But I've come into _some engines_ that handle this in better way which is, most importantly, more friendly towards beginners. Making labels of different size has multiple problems. Scaled labels/buttons look super-ugly, but aside from that, their anchors are broken (https://github.com/godotengine/godot/issues/19068). So using a dynamic font for text size is a necessity.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The biggest problem with this workflow is whenever you want to have nice text, you have to go out of your way and get a TTF file from somewhere. It might be web or system fonts, but I imagine this is not obvious step for beginners.

I've seen that in _some other engines_, the fonts are seemingly built-in. Not sure if they are provided with the engine (which is a no-no-no for Godot), but the option to get a system font into your project without having to navigate to Windows/Linux directory would be really useful.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
image
(imagine there's some button saying "Import system font" here and clicking it opens some dropdown/lists of system fonts, clicking which will copy the font into your project)

**Describe implementation detail for your proposal (in code), if possible:**
I don't recall any similar system in Godot, so can't recommend any copy-paste material here, but the idea is to access system's font directory (like C:/Windows/Fonts or /Linux/Fonts) and allow to copy a font into your project without leaving the editor. So it requires platform-specific code.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This will be used by everyone the second this is added, trust me.

**Is there a reason why this should be core and not an add-on in the asset library?:**
The purpose is to be friendly to newbies, so having this in asset lib and being basically a "standard plugin to use" would make it a bit pointless...

### PR DESCRIPTION
**Pull request by bruvzg**
Adds support for loading and using system fonts:

https://user-images.githubusercontent.com/7645683/179501314-fbf0af68-13da-447d-ab13-d06770ea3b40.mov

### Demo project:

https://user-images.githubusercontent.com/7645683/179197438-f858b4e5-816c-4bba-958c-b7b4f88a7bae.mov

[sys_font.zip](https://github.com/godotengine/godot/files/9119682/sys_font.zip)

Fonts can be enumerated using `OS.get_system_fonts()` and loaded using `SystemFont` class (multiple family names can be specified, including generic `serif`/`sans-serif`/`monospace`, first found is used).

Implemented for:
- [x] ~Android~ No documented API to get font names (info can be extracted from `/system/etc/fonts.xml`, but file explicitly say not to use it to get system font info).
- [x] macOS / iOS (CoreText)
- [x] Linux (fontconfig)
- [x] Windows (DirectWrite)
- [x] ~Web~ (App won't be able to access host file system).

Implements https://github.com/godotengine/godot-proposals/issues/306

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/306.*

### CODE REVIEW

**Comment by akien-mga** [comment]
> Fonts can be enumerated using `OS.get_system_fonts()` and loaded using `FontSystem` class

Shouldn't it be `SystemFont`? Both because that sounds more like what it is (a system font) and because that's usually how we compose names with inheritance (`Texture2D` -> `CompressedTexture2D`).

**Comment by bruvzg** [comment]
> Could be done in a future PR, but what if there was a drop-down with a list of the currently installed system fonts, and selecting one would add it to the list of font names; along with some note that not all fonts will be available on all platforms.

It can be done with an editor inspector plugin, but I'm not sure what's the best UI for this. The demo I have added to the top comment is doing pretty much it (with a few GDScript lines), so it's not hard to do.

> Even cooler would be if it could tell you which fonts are installed by default on which platforms, but probably too difficult/not worth the effort.

That's what fallback names (`sans-serif`, `serif`, `monospace`, `fantasy`, `cursive`) are for. Exact lists of installed fonts are available for Windows and macOS, but different Linux distros will have different sets of fonts.

**Comment by xix-xeaon** [comment]
The only reason I would use this feature would be to avoid including large CJK fonts in a small game for mobile and web. Can this really not work on Android and web?

**Comment by Calinou** [comment]
> No documented API to get font names (info can be extracted from /system/etc/fonts.xml, but file explicitly say not to use it to get system font info).

Aren't the fonts available on recent Android versions standard enough that you can assume certain fonts to be always available (such as Roboto)?

**Comment by bruvzg** [comment]
### For Android:
- We can either get list of filenames from the OS API (but there's no readable names, we'll need to load every single font to get them).
- Or we can parse XML files in the `/system/etc/`, which can be slightly different depending on Android version and might be changed in the future version.

I guess we can generate readable names from the filenames, they all seem to be `Name-Style.ttf` or `Name-VF.ttf` (for variable fonts). Event if it changes and the names won't be perfect, it should at least work.

### For Web:

No, I do not think it's possible to access font data.

**Comment by xix-xeaon** [comment]
It seems this can be used for web: https://web.dev/local-fonts/

> "the ability to request low-level (byte-oriented) SFNT container access that includes the full font data"

Seems freshly implemented in Chrome, but I don't think the others have said anything about implementing it.

**Comment by bruvzg** [comment]
> I guess we can generate readable names from the filenames, they all seem to be Name-Style.ttf or Name-VF.ttf (for variable fonts). Event if it changes and the names won't be perfect, it should at least work.

While it's possible to get reasonable names for the file paths, the app doesn't seem to be able to directly access font files, so it's useless.

**Comment by reduz** [comment]
This is very incredible work. I suppose probably what may be needed is the possibility to bundle the font during export.
I want to work on an export plugin architecture that lets you do changes to scenes during the export process (with proper caching) so you can do these kind of operations. 

It seems to be needed for a couple things already (like server export and converting text resources to binary without the existing hacks we have).

**Review by reduz — APPROVED** [review]

**Comment by bruvzg** [comment]
> I suppose probably what may be needed is the possibility to bundle the font during export (of course totally up to the user to ensure what they are doing is legal).

> I want to work on an export plugin architecture that lets you do changes to scenes during the export process.

This PR is primarily for the user controlled font change in runtime. But I was thinking of adding an option to import system fonts into the project as well.

With the ability to enumerate system fonts from this PR, it should be really easy to add, but I'm not sure where to add it in the editor UI. With ability to changes stuff during export, it's probably can be done with a single `bool embed` property of the `SystemFont` or something like this.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
@bruvzg I think usability wise it may be better to have it an export option is you ask me rather than importing. Of course we could have something to do this in the Tool menu somewhere, but IMO the workflow is much better if you just forget about it and then export the game and it gets bundled.

**Comment by Calinou** [comment]
> I suppose probably what may be needed is the possibility to bundle the font during export (of course totally up to the user to ensure what they are doing is legal).

Most system fonts are not legally redistributable (in particular Windows and macOS'), so I would prefer not to delve into this.

**Comment by timothyqiu** [comment]
I noticed that fonts in the add font menu are not in ascending order (on Arch Linux).

Should `get_system_fonts()` guarantee some order, or should the font menu sort the available fonts?

**Comment by TechnoPorg** [comment]
If it's possible given the way the editor is set up, it would be interesting to have the names of the system fonts in the editor dropdown actually show up in that font. Right now, they're all just in the default editor font, so it's not very handy for quickly picking a font. If one needs a generic cursive font, they have to go look through a list of fonts elsewhere to know which is which.

**Comment by fire** [comment]
can you copy and paste have the names of the system fonts in the editor dropdown actually show up into a feature proposal?

**Comment by Calinou** [comment]
> If it's possible given the way the editor is set up, it would be interesting to have the names of the system fonts in the editor dropdown actually show up in that font. Right now, they're all just in the default editor font, so it's not very handy for quickly picking a font. If one needs a generic cursive font, they have to go look through a list of fonts elsewhere to know which is which.

There's a PR implementing this: https://github.com/godotengine/godot/pull/70550

**Comment by TechnoPorg** [comment]
> Do you mean displaying what each alias corresponds to (Sans Serif, etc)?

I think so, yes. When setting the `font_names` property of a `SystemFont` resource, the popup that appears would still contain the same list of fonts, but each of those font names would be rendered in the font they represent.

For example, Magneto would not be drawn in the default editor font, as they currently all are:
image
But be rendered the way it will look in-game:
image

I'm purely talking about the font selection dropdown for `SystemFont`s here, as a matter of improving usability.

**Comment by Calinou** [comment]
> I think so, yes. When setting the font_names property of a SystemFont resource, the popup that appears would still contain the same list of fonts, but each of those font names would be rendered in the font they represent.
>
> For example, Magneto would not be drawn in the default editor font, as they currently all are:

That's something entirely different :slightly_smiling_face: 

This needs to be tracked in a dedicated proposal. It's likely not easy to implement due to the rendering overhead of using so many different fonts.

**Comment by bruvzg** [comment]
> I think so, yes. When setting the font_names property of a SystemFont resource, the popup that appears would still contain the same list of fonts, but each of those font names would be rendered in the font they represent.

It's not necessary hard to implement, but will involve quite a lot of stuff of a questionable benefit:
- It will require loading all system fonts, which will consume hundreds of megabytes of memory (on a clean Windows install, users might have much more custom fonts) and will take at least a few seconds. So preview images probably should be generated in a background thread and cached as images.
- Some fonts do not have Latin characters (but font name is usually Latin), so each font need to be analyzed to get supported characters and both readable preview string and name should be displayed (even slower than loading fonts).
- PopupMenu, which is used to display font list, do not support per-item font changes.

**Comment by TechnoPorg** [comment]
I created a proposal to track this idea: https://github.com/godotengine/godot-proposals/issues/6882

**Pull request merged**
