### PR TITLE
Batching - fix number of verts in translation

### LINKED ISSUE #48109: Godot 3.3 2D Batching causing a Native Crash
**Godot version:**

v3.3.stable.mono.official

**OS/device including version:**

Windows 10 Home
OpenGL ES 3.0 Renderer: Intel(R) HD Graphics 400
OpenGL ES Batching: ON

**Issue description:**

After running a scene of my project for a while, it causes a Native Crash, outputing something like this in the terminal:
```
ERROR: _translate_batches_to_larger_FVF: FATAL: Condition "!(cv)" is true.
   At: ./drivers/gles_common/rasterizer_canvas_batcher.h:3024
=================================================================
        Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Managed Stacktrace:
=================================================================
=================================================================
```
After some testing, I discovered that the combination of Line2D with a higher number of points + a shader that I wrote would cause the crash. In my tests it took 517 points to crash. The shader that I created is a grass shader with wind effect.

**Steps to reproduce:**
I'm not sure what steps is needed to reproduce this issue, but I'll link the reproduction project that I made to test with CSharp, GDScript, GLES 3.0 and GLES 2.0, all of then caused the crash.

**Minimal reproduction project:**

[BatchingCrashIssue.zip](https://github.com/godotengine/godot/files/6360930/BatchingCrashIssue.zip)

### PR DESCRIPTION
**Pull request by lawnjelly**
The translation to larger vertex formats was assuming that batches were rects, and not accounting that the num_commands had a different meaning for lines and polys, so the calculation for number of vertices to translate was incorrect in these cases.

Also prevents infinite loop if a single polygon has too many vertices to fit in the batch buffer.

Fixes #48109

## Notes
* Rather an embarrassing bug that makes you think 'how did this ever work???' :grin: 
* As a leftover from the first version of the batching, translating verts to larger FVFs was assuming they were all rects
* When implementing the polys and lines I'd forgotten to change the code here because the batch stores the number of commands, NOT the number of verts, and the meaning of number of commands depends on the batch type. (I did actually try storing the number of verts instead but commands ended up being more efficient, I forget the details.)
* This begs the question, how did it ever work - lines and polys must have been translating 2x and 4x as many verts as necessary. Luckily these were just extra buffer space in most cases, otherwise the crash seen in the issue would have occurred.
* This should increase the efficiency of drawing lines and polys.

## Infinite loop
While fixing the issue, there is one further problem - a single poly that has too many indices (rendered verts) for the batch buffer will never render, keeping deferring, and form an infinite loop. To prevent this a poly that is too 'large' is now simply not rendered, and a warning message is issued. This occurs somewhere around 2000 indices for the default batch buffer size, which should be enough in most cases - the user can increase batch buffer size in project settings if necessary.

The alternative would be to try and split the polygon into more than one, or to have some kind of other special case for this situation. It is something that would require a dedicated PR and I'm not sure at this stage whether it is necessary.

It may also be possible to partially draw the offending polygon in such a situation rather than simply not draw it at all. However not drawing it draws attention to the problem so it can be fixed by the user.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
Implementation looks fine to me. I can help test this out a bit over the weekend too.

**Comment by lawnjelly** [comment]
I'm pretty sure it should be fine, it's just good to let it stew for a day if we aren't in a hurry, as this will be for 3.3.1 now. Aside from the testing, sometimes an idea pops in my head of a better way of doing it etc.

For the super large polys, we could just revert to using the legacy renderer. But I'll leave that for a separate PR. The legacy renderer could on the other hand be vulnerable to a similar problem of overrunning the polygon buffer instead of the batching buffer ... :thinking:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
