### PR TITLE
Fix X11 BadMatch when calling XSetInputFocus.

### LINKED ISSUE #60690: Editor crashes when child window is closed in another workspace (DisplayServer regression)
### Godot version

4.0.dev (504708ae2)

### System information

Arch Linux, i3wm

### Issue description

When moving any child windows to another workspace than the editor, closing the child window causes editor to crash.

Impacts any prompt windows, including game window.

Log: https://gist.github.com/valters-tomsons/d6c37a65bdf49bb667aafc5440757b3f

godot_crash_lldb

### Steps to reproduce

1. Start `i3wm` session
2. Open godot
3. Open a child window
4. Move child window to another workspace
5. Close child window
6. Editor crashes

### Minimal reproduction project

Can be reproduced without a project.

### LINKED ISSUE #62635: Linux window freeze when unfocusing while loading window open
### Godot version

Godot 4.0 alpha 11 from godotengine.org

### System information

Arch linux, i3 WM, Vulkan @ NVIDIA GeForce GTX 1050 Ti, driver 515.48.07

### Issue description

When there's a operation that opens a loading window (e.g. saving, importing) and refocusing the editor window, it completely freezes.
This seems to only happen when the editor is not visible (e.g. another virtual desktop/workspace).

Logs (some of it may be my unported project):
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  42 (X_SetInputFocus)
  Serial number of failed request:  8026
  Current serial number in output stream:  8026
ERROR: BUG: Unreferenced static string to 0: physics_process_internal
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: _update_script_names
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: GizmoLightmapGI
   at: unref (core/string/string_name.cpp:129)
ERROR: BUG: Unreferenced static string to 0: EditorRect2D
   at: unref (core/string/string_name.cpp:129)
WARNING: Property not found:
     at: _get (core/config/project_settings.cpp:319)
ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:276)
ERROR: BUG: Unreferenced static string to 0: PrevScene
   at: unref (core/string/string_name.cpp:129)
ERROR: Method argument to Callable constructor must be a non-empty string
   at: Callable (core/variant/callable.cpp:276)
```

### Steps to reproduce

- Open any project (can be empty)
- Save or import
- Switch to a different workspace/virtual desktop (might also work when minimizing)
- Wait
- Godot's window freezes, no new frame is drawn
- Godot now needs to be closed with htop through SIG_TERM, ^C does nothing, nor does WM_CLOSE

Video (3.3MiB):
https://user-images.githubusercontent.com/57371001/177003823-a9649355-0fd6-4ce3-870a-dff4f778f9e5.mp4

### Minimal reproduction project

An empty project will do

### PR DESCRIPTION
**Pull request by MatthewZelriche**
Should fix #62635
Should fix #60690

Certain X11 window managers (eg, i3wm) seem to unmap ancestors of windows that are on an inactive virtual workspace. This results in Godot windows having the X window attribute `IsUnviewable`. According to the Xlib docs, `XSetInputFocus` will fail if the window you are applying it to is not viewable. To solve the issue, we simply need to confirm the window is viewable prior to attempting to set input focus. If it is not viewable (because it's on an inactive workspace), there's no need to set the input focus. This was actually already being done under the `ConfigureNotify` event, but not the `MapNotify` event or the `window_set_transient` method.

This is my first pull request, so  apologies in advance if I've made any errors.

### CODE REVIEW

**Comment by MatthewZelriche** [comment]
I have also only just noticed that a very similar change within the same source file seems to fix #60690, however I am unsure if should be placed into a separate pull request.

**Comment by akien-mga** [comment]
If the two fixes are related, you can amend the commit to fix them both at once.

**Comment by MatthewZelriche** [comment]
I have amended the commit to include the related fix.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
