### PR TITLE
Add FRUSTUM camera mode, allowing tilted frustums

### PR DESCRIPTION
**Pull request by JFonS**
This new camera mode makes it easy to create tilted frustums for mirror
or portal effects.

This work was kindly sponsored by IMVU.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
@JFonS Could have saved yourself a bundle of trouble: #7778
There are many more similar PRs over the years from other contributors :)

As I remember the main reason these changes not being merged is because you need to calculate the values you want to use to create a sensible frustum, the engine thus presents you with a very un-intuitive interface. 
Everyone understands "your camera has a field of view of 60 degrees", try and explain what the values you need to specify for a camera frustum are and you need to give someone a crash course in optics first.

I'm intrigued though, why do you need it for mirror and portals? I kinda get portals because it can be handy to have asymmetric frustums, but for mirrors you're just inverting your camera. What Godot lacks is being able to apply a stencil to a viewport.

**Comment by akien-mga** [comment]
Moving to 3.2 milestone for now as there's no clear consensus. It can still be merged and cherry-picked for 3.1.x later on, but it's not in focus for the imminent 3.1 release.

**Comment by BastiaanOlij** [comment]
I'm fine with it being merged, my comments were merely that that was the reason I was told why similar PRs weren't merged in the past. 
Personally I'm a fan of a camera mode exposing a full frustum and accepting that if that mode is chosen it's not for the inexperienced, but I get the argument that we rather avoid that. JFons' solution sounds like a good middle ground

**Comment by hpvb** [comment]
Thanks!

**Pull request merged**
