### PR TITLE
2.2 (Adding multiple classpath and gradle plugins)

### PR DESCRIPTION
**Pull request by RameshRavone**
adding gradle classpath.
> env.android_add_gradle_classpath("com.google.gms:google-services:3.0.0")

> buildscript {
        repositories {
                jcenter()
        }
        dependencies {
                classpath 'com.android.tools.build:gradle:2.1.0'
                classpath 'com.google.gms:google-services:3.0.0'
        }
}
>

apply gradle plugins.
> env.android_add_gradle_plugin("com.google.gms.google-services")

>android {
        ........
        { gradle configs }
        ........
}
apply plugin: "com.google.gms.google-services"
>

### CODE REVIEW

**Comment by RameshRavone** [comment]
Helps with Firebase integration and more

**Comment by akien-mga** [comment]
CC @RandomShaper @volzhs

**Comment by RandomShaper** [comment]
This looks good, but the commits should be squashed together.

**Review by volzhs — APPROVED** [review]

**Comment by volzhs** [comment]
commits should be squashed as @RandomShaper said, and cherry-pick on 2.1 and master branch too.

**Comment by akien-mga** [comment]
Squashed and merged manually in 27c7d253.

**Pull request closed without merging**
