### PR TITLE
Fixed the arguments type of GraphEdit's signal "connection_drag_started"

### PR DESCRIPTION
**Pull request by Daylily-Zeleen**
QQ截图20220812172315

QQ截图20220812172407

Fixed this error.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Thanks for your contribution! You need to update the documentation as well. Please [run the `doctool`](https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html#updating-the-documentation-template) locally with the build of the engine from this PR and commit that as well.

Make sure to [squash your commits](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase) into one afterwards.

**Comment by KoBeWi** [comment]
The `from` argument should be a StringName, like in other methods.

**Comment by Daylily-Zeleen** [comment]
> The `from` argument should be a StringName, like in other signals.

Only fix `slot` from `String` to `int`

**Comment by KoBeWi** [comment]
But it's the same line, you could as well do it in the same PR.

**Comment by YuriSizov** [comment]
Superseded by https://github.com/godotengine/godot/pull/64315

**Pull request closed without merging**
