### PR TITLE
Increase RemoteDebuggerPeerTCP poll to 6.9ms to reduce CPU usage

### LINKED ISSUE #57256: Godot 4.x uses minimum 20% CPU on Mac while debugging (Intel)
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Mac OSX (Intel 2019)

### Issue description

**Vulkan Mobile renderer**

Adding `Low processor mode` does not seem to have an effect on CPU usage in the latest alpha release of 4.x

While playing with the settings and trying to understand if I could decrease CPU usage on my Mac I found that enabling this setting does not seem to have an effect.

My mac continues to use around 20% of the CPU for running the window.

### Steps to reproduce

1. Open a project with the Vulkan mobile renderer
2. Enable low CPU mode
3. Set the CPU delay to 40,000

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by tavurth**
Closes https://github.com/godotengine/godot/issues/57256

Screenshot 2022-02-01 at 22 17 32

And profile report:

Screenshot 2022-02-01 at 22 20 23

### CODE REVIEW

**Comment by Faless** [comment]
Please use a descriptive commit name, e.g.:
```
Increase RemoteDebuggerPeerTCP poll interval to 10ms

Fix high CPU usage on MacOS.
```

Did you try with `1ms` instead? Does it make much difference?

**Comment by tavurth** [comment]
@Faless I will check that now, and I will add a more descriptive name & force push

**Comment by tavurth** [comment]
1ms seems to result in an increase of around 6% CPU with `sleep_usec` set to `40,000`.

Screenshot 2022-02-01 at 22 30 30

I will try @ 5ms

**Comment by tavurth** [comment]
@Faless 4.1ms seems to be a good compromise as it leads to only 1% increase in CPU while updating at 144hz.

Thoughts?

Screenshot 2022-02-01 at 22 35 09

**Comment by Faless** [comment]
> @Faless 4.1ms seems to be a good compromise as it leads to only 1% increase in CPU while updating at 144hz.
> 
> Thoughts?

@tavurth that sounds good. Thanks!

**Comment by tavurth** [comment]
Updated commit message and force pushed

**Comment by Calinou** [comment]
4.1 ms doesn't match a 144 Hz refresh rate, it matches (roughly) a 200 Hz refresh rate. Nonetheless, if it works well, you can keep it :slightly_smiling_face:

**Comment by tavurth** [comment]
Oh yes you are correct, I did `60 / 144` instead of `144 / 60`.

If you want I can update that to reflect the actual refresh rate?

**Comment by tavurth** [comment]
Hmm I was doing `60 / 144` to give `4.1ms` is my math off somewhere?

**Comment by tavurth** [comment]
Oh yes I see 😅 Well as long as it's not causing too much thrashing I guess it should be OK for now, if you'd like I can update to `7ms` as per 144hz?

**Comment by tavurth** [comment]
`7ms` seems to give a slight cpu reduction but not so much

Screenshot 2022-02-01 at 23 32 40

**Comment by tavurth** [comment]
Seems ready

**Review by akien-mga — APPROVED** [review]
Nice :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Let's give this value a try, and if some users find it still too high, or too low for real-time updates, we could also consider making it configurable.

**Comment by tavurth** [comment]
@akien-mga configurable would be very nice!

I'm not sure if this needs to be cherry picked back to 3.x because as far as Calinou stated the system was rewritten for 4.x

**Comment by Faless** [comment]
Yeah, we don't need the cherry pick, the new debugger code (which uses threads) was not ported to 3.x

**Pull request merged**
