### PR TITLE
Add `backwards` as a property of `AnimatedSprite`.

### LINKED ISSUE #30785: Add the argument 'backwards' in the class AnimatedSprite as a property.
The variable 'backwards' doesn't have a getter neither a setter.

https://github.com/godotengine/godot/blob/master/scene/2d/animated_sprite.cpp#L730

Since the variable is private, right now you can't check if the current animation is playing backwards or not. So i propose adding a getter and setter to 'backwards' to solve this problem.

Also, in the documentation of AnimatedSprite (https://docs.godotengine.org/en/3.1/classes/class_animatedsprite.html#method-descriptions), it says that 'backwards' is a property, but is not present in the list of Properties (https://docs.godotengine.org/en/3.1/classes/class_animatedsprite.html#properties).

### PR DESCRIPTION
**Pull request by cgxeiji**
Fixes https://github.com/godotengine/godot/issues/30785.

### CODE REVIEW

**Comment by hbina** [comment]
I don't see what's the purpose of this? It doesn't do anything as a property of `AnimationSprite`

**Comment by aaronfranke** [comment]
@cgxeiji Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by KoBeWi** [comment]
The new property needs documentation. Also the `backwards` argument of `play()` is no longer needed; it could be removed.

**Comment by fire** [comment]
@TokageItLab didn't you add backwards loop?

**Comment by TokageItLab** [comment]
@fire My implementation affect only animation tree, not sprite.

**Comment by YuriSizov** [comment]
Seems like there is no interested in this PR from any side. So closing.

**Comment by TokageItLab** [comment]
P.S. ^ I added alternative recently in #71907.

Now AnimatedSprite can play backwards with `play_backwards()` and retrieve playback direction with `backward = get_playing_speed() < 0`, it is same with AnimationPlayer.

**Pull request closed without merging**
