### PR TITLE
Code Editor: Add button to toggle between search and search+replace

### LINKED ISSUE #10675: Add a button to switch between 'Search' and 'Replace' in the code editor
### Describe the project you are working on

Noob following noob tutorials for now.

### Describe the problem or limitation you are having in your project

In most IDEs I usually `Command+F` instead of `Command+Option+F` even when I want to do replacements, because I find the keybind cumbersome. Most IDE have a button on the left to open the Replace panel from the Search panel. But the Godot Editor doesn't.

**Godot Editor**
Capture d’écran 2024-09-06 à 23 05 30

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a arrowhead button on the left of the text field(s) in the Search panel to toggle the Replace panel.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

**VSCode**
Capture d’écran 2024-09-06 à 23 18 22
Capture d’écran 2024-09-06 à 23 00 05

I **guess** (I know nothing about the inner workings of the editor): the button added on each panel would only have to use the signal sent by `Command+Option+F` and `Command+F`, since the latter already reverts back to the Search panel from the Replace Panel.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around by moving your fingers a few more centimeters lol.
But it should be easy to implement. I guess I could do it myself, and I might in the future :))

### Is there a reason why this should be core and not an add-on in the asset library?

Ergonomics / IDE standards

### PR DESCRIPTION
**Pull request by elliotfontaine**
Closes https://github.com/godotengine/godot-proposals/issues/10675
## Screenshots
Capture d’écran 2024-09-07 à 15 20 16
Capture d’écran 2024-09-07 à 15 21 33

It has a dynamic tooltip ("Show Replace" / "Hide Replace"), which also gives the shortcut to Replace (or Search if Replace is visible).
Capture d’écran 2024-09-07 à 15 21 59

## Behavior
Tested on the script editor and the shader editor.

### CODE REVIEW

**Comment by JekSun97** [comment]
The interface doesn't look very nice, maybe it's worth adding a Label above LineEdit to indicate it?

**Comment by elliotfontaine** [comment]
@JekSun97 Could you draw a quick sketch of what you would prefer? I'm not sure I get it.

In case you're talking about the FindReplaceBar not having a "title", it already gives it purpose away with the placeholders (not shown in my screenshots).
Capture d’écran 2024-09-07 à 16 35 54

**Comment by tetrapod00** [comment]
Can't we use the same `>` and `v` icons that are already available for the inspector folding, to match VSCode?


Godot_v4 3-stable_win64_bqNSWumjnF

VSCode:
Code_Cia8zAUFJn
Code_cb23vjMshP

**Comment by elliotfontaine** [comment]
Capture d’écran 2024-09-08 à 08 40 21
Capture d’écran 2024-09-08 à 08 40 11

Is `GuiTreeArrowDown` / `GuiTreeArrowRight` good enough ? It's a little darker, so its color matches the _"Find Previous"_ / _"Find Next"_ on the right rather than the _"Toggle Script panel"_ above, which isn't part of `FindReplaceBar`.

I'm waiting for feedback before adding the commit.

**Comment by tetrapod00** [comment]
@elliotfontaine Yeah, I'd wait for an actual review from someone who knows this area better. I just saw a plausible improvement to better match VSCode behavior and pointed out potential icons to use, but I don't know what the best specific arrow icons to use are.

**Comment by elliotfontaine** [comment]
@tetrapod00 Sadly the whole `FindReplaceBar` doesn't use RTL at the moment. I could make the button RTL compliant, but what about all the others sitting on the right ?

I think handling it should be done in a PR of its own.

But good call! That would be my next contribution :)

**Comment by tetrapod00** [comment]
FYI you'll have to squash all the commits into one at some point, using the interactive rebase process described [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request). You can either try now or wait until the changes are finalized. In the future you might want to consider using the amend workflow instead of multiple commits and squashing.

**Comment by tetrapod00** [comment]
Testing this out, and it works as expected.

Ideally we would have brighter arrow icons, to match the color of the other icons on this panel. That should be a simple recolor of the existing icons (if good icons don't already exist) but I'd wait to do the work until someone else reviews.
godot windows editor x86_64_LtzEMpUe19

The focus behavior of the icons on this panel is also maybe inconsistent. The `Toggle Scripts Panel` button is focusable, but `Next Match`, `Previous Match`, and `Hide` are not focusable. If there's a true consistent logic here I can't see it - it seems like most the icon buttons are not focusable, but `Toggle Scripts Panel` is. If that needs fixing, it should be another PR. The `Show/Hide Replace` button is not focusable, which does match this panel's current behavior.

**Comment by elliotfontaine** [comment]
> Potentially the button could be renamed to Toggle Replace. Not sure if there is a preference here.

Just FYI, the button is named "Toggle Replace" in the code, which mean things like `toggle_replace_button = memnew(Button);` or `_update_toggle_replace_button()`.
**Show Replace** / **Hide Replace** are just the tooltips. Which could be replaced by a single **Toggle Replace** if wanted.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/84dcdde9088d512efebb0033fb881d8f7fd9c107), it works as expected.

Code looks good to me.

While testing this PR, I noticed that hovering icons with the mouse doesn't provide much of a visible highlight. This is an issue shared with other icons in the find/replace bar (and even CheckBoxes in general), so it should be addressed separately. Ideally, all icons should have the same hover feedback as the one used by icons at the top of the 2D/3D editor viewports.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
