### PR TITLE
Fix 2d editor not able to reach min and max zoom values

### PR DESCRIPTION
**Pull request by nodj**
By simply rejecting invalid zoom values, we cannot reach max and min zoom values.
Instead of rejecting invalid values, target is clamped to the valid range.
This slightly improves the look n feel (avoid being stuck on random values)

### CODE REVIEW

**Comment by nodj** [comment]
@groud Hi, this is my first contribution, my first PR even... Not sure if I'm doing this right, probably not... Sorry for that
Reading other issues, I think you could be a reviewer for this PR ?
I haven't opened an issue for this, should I ?

**Comment by groud** [comment]
The problem is that this solution makes it impossible to go back to a round value (like 100%) once you reached a  maximum or a minimum. The way the zoom is computed is by multiplying it by a given factor at every step, so if you not clamp to a good value you won't be able to go back to the 1/1 ratio, which is not acceptable.

**Comment by nodj** [comment]
Thank you Gilles,
I see, and agree entirely. In my use case (pixel art, high zoom) I find
frustrating to never hit 'nice' round factors (400%, 1600%, etc).
This is resolved with the buttons on the top left that provide a sqrt(2)
scale factor, do every 2 hits, the scale doubles, which is nice.
I suggest to use the twelveth root of two (approx 6% instead of 5) which
would provide the ability to reach nice numbers while keeping a geometric
growth. Also, a suggest to have a max zoom capped at x64 or x128 in order
to improve boundaries behaviour and clamping stuff.

What do you think of those suggestions? May I go ahead and propose an
updated PR ?

**Comment by nodj** [comment]
Closed because:
- I didn't made a proper branch for the fix
- I've failed to pass CI test.

I'll make a proper issue + PR
Sorry for that

**Pull request closed without merging**
