### PR TITLE
Load OGGs from file system

### LINKED ISSUE #61091: No longer possible to load PackedByteArray into AudioStreamOGGVorbis
### Godot version

Godot_v4.0-alpha8_win64

### System information

Windows 10

### Issue description

In Godot 3.5, the AudioStreamOGGVorbis class contains a data property which accepts a PackedByteArray value.
In Godot 4.0 alpha 8, it is replaced by the OGGPacketSequence property.
I didn't find a function to convert the PackedByteArray to an OGGPacketSequence.
No more information in the Godot 4.0 documentation.

### Steps to reproduce

-

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by rohanrhu**
Meowww this is related to: https://github.com/godotengine/godot/issues/61091

Now we are able to load and play OGGs from anywhere on file system:
```gdscript
var path = "/Users/oguzhan/Projects/3DAudioVisualization/assets/audio/Dubmood - Chicago Chiphop.ogg"
var stream = AudioStreamOggVorbis.from_filesystem(path);
$AudioStreamPlayer.stream = stream
$AudioStreamPlayer.play(0)
```

Fixes https://github.com/godotengine/godot/issues/61091

### CODE REVIEW

**Comment by Calinou** [comment]
Out of curiosity, can you check if this can be done with MP3 as well?

**Comment by ellenhp** [comment]
Nit: remove commented out 'private' but otherwise lgtm for audio.

**Comment by DarkKilauea** [comment]
`ResourceImporterOggVorbis` does not appear to be available outside of the editor (tools build), this will not work in exported projects.

If that is intended, you should wrap the additions in `#ifdef TOOLS_ENABLED`.

**Comment by Calinou** [comment]
> `ResourceImporterOggVorbis` does not appear to be available outside of the editor (tools build), this will not work in exported projects.
> 
> If that is intended, you should wrap the additions in `#ifdef TOOLS_ENABLED`.

A method similar to Image's `load_png_from_buffer()` should be implemented for run-time WAV/OGG/MP3 loading. See https://github.com/godotengine/godot/pull/47389.

**Comment by rohanrhu** [comment]
> Out of curiosity, can you check if this can be done with MP3 as well?

Okiii I will look

> `ResourceImporterOggVorbis` does not appear to be available outside of the editor (tools build), this will not work in exported projects.
> 
> If that is intended, you should wrap the additions in `#ifdef TOOLS_ENABLED`.

Okiiii

**Comment by ellenhp** [comment]
It would be a bit misleading if we only had this available in editor builds
because of a tools preprocessor check imo. I had forgotten about the
importer being conditionally compiled. I think the right move is probably
to do what calinou suggested.

**Comment by KoBeWi** [comment]
@rohanrhu  the PR broke. Are you going to update it?
I encountered this issue today and it would be nice to have it resolved. (having such function for WAV would be nice too, because loading them is not possible either (unless something changed))

**Comment by rohanrhu** [comment]
> @rohanrhu the PR broke. Are you going to update it? I encountered this issue today and it would be nice to have it resolved. (having such function for WAV would be nice too, because loading them is not possible either (unless something changed))

Sureee I will loooook

**Comment by Calinou** [comment]
> Any progress on this? I desperately need that method :(

4.0 is in feature freeze, and this PR still needs rebasing (something wrong happened during rebase, which is why the diff appears to be soo large).

**Comment by akien-mga** [comment]
Closing as this can't be salvaged in the current form.

**Comment by Overvault-64** [comment]
Will this ever make it to Godot 4? :(

**Comment by Calinou** [comment]
> Will this ever make it to Godot 4? :(

It needs to be salvaged by a contributor, but there is nobody with the knowledge to do so currently available.

**Comment by KoBeWi** [comment]
Remaking this does not really require any knowledge, you just need to dig through 800+ commits and find the one added by this PR xd

**Comment by fire** [comment]
Oh that's easy :3 /me grabs my tea.

**Comment by akien-mga** [comment]
Superseded by #78084.

**Pull request closed without merging**
