### PR TITLE
Bump mbedtls to 2.16.12

### PR DESCRIPTION
**Pull request by Faless**
New mbedtls release: https://github.com/ARMmbed/mbedtls/releases/tag/v2.16.12

Remove upstreamed patches.
Re-apply padlock and uwp patches.

NOTE: We could replace our padloack patch with https://github.com/ARMmbed/mbedtls/pull/3452 (we could also ask to backport it maybe?)

### CODE REVIEW

**Comment by akien-mga** [comment]
> NOTE: We could replace our padloack patch with ARMmbed/mbedtls#3452 (we could also ask to backport it maybe?)

Yeah both sound good to me :+1:

**Comment by akien-mga** [comment]
So as per https://github.com/ARMmbed/mbedtls/pull/3452 2.16.12 is the last release in the 2.16 LTS branch, so we'll have to upgrade to their new LTS eventually. There's probably no point changing the padlock patch at this point then.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.2.

**Comment by Faless** [comment]
> There's probably no point changing the padlock patch at this point then.

Yeah, that was my feeling, I'll start working on the 2.28.0 update.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.5.

**Pull request merged**
