### PR TITLE
Fix natural sorting order in EditorFileDialog, FileDialog and EditorFileSystemDirectory

### LINKED ISSUE #8712: Browse for file dialog - incorrect ordering
**Operating system or device - Godot version:**
Godot_v2.1.3-stable_win64

**Issue description:**
When importing a large number of files (textures in my case) the browse for file dialog does not order the file list correctly, which makes it difficult for building SpriteFrames because I must click individually through the files to have the correct frames loaded in order.
As you can see from the screenshot the order is 0, 1, 10, 1000.
Note that when I open up a folder in Windows I do get the correct order, so this behaviour is a bit surprising.

**Steps to reproduce:**
Import -> Texture -> Click the '...' button next to source textures, and browse to a folder with a large list of numbered images.

**Link to minimal example project:**
screen

Additional information:
I am guessing the offending line is below which uses a NoCaseComparator:
https://github.com/godotengine/godot/blob/df61dc4b2bd54a5a40c515493c76f5a458e5b541/scene/gui/file_dialog.cpp#L340

The link below shows a sorting implementation for this:
https://psycodedeveloper.wordpress.com/2013/04/11/numeric-sort-file-system-names-in-c-like-windows-explorer/

### PR DESCRIPTION
**Pull request by damianday**
Make EditorFileDialog, FileDialog and EditorFileSystemDirectory alphanumerical sorting more natural

Added a new method 'naturalnocasecmp_to' and comparator 'NaturalNoCaseComparator' to String.

Fixes #8712.

### CODE REVIEW

**Comment by karroffel** [comment]
If you write `fixes #8712` in the PR description then the associated issue will automatically be closed if this PR gets merged. Just FYI

**Comment by Hinsbart** [comment]
Cool, thanks for the fix :)
But `Fixes [8712]` is neither a good PR nor commit title, you should at least briefly tell what this does.

**Comment by akien-mga** [comment]
>  But Fixes [8712] is neither a good PR nor commit title, you should at least briefly tell what this does.

Indeed. A better commit log would be e.g.:
```
Make FileDialog alphanumerical sorting more natural

Adding a new comparator to String to achieve that.
Fixes #8712.
```

**Comment by tagcup** [comment]
Can you rename it to [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order) or something along that lines, since that's how it's called? "Logical" doesn't make any sense to me.

**Comment by akien-mga** [comment]
BTW, here's brand new documentation on how to modify a commit in your PR with `git rebase` or `git commit --amend`: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

**Comment by damianday** [comment]
@tagcup I have changed it from logical to natural
@akien-mga Thank you for the reference, I'll be sure to use that in the future :)

**Comment by volzhs** [comment]
nice work. :smile:

**Pull request merged**
