### PR TITLE
Change Import > Sub-Scene to Import > Node from scene

### LINKED ISSUE #3072: Import > Sub-Scene is confusingly named
The "sub-scene" term is used in several places but can be quite confusing to newcomers und especially developers new to Godot's scene system, see e.g. this Facebook post: https://www.facebook.com/groups/godotengine/permalink/703042476499016/

The PR #2928 based on @Fiona's proposal already moves the "Export -> Sub-Scene" menu entry to an icon in the scene tree panel ("Create new scene from node(s)"), but the "Import -> Sub-Scene" entry could also use some love.

As this import function actually seems to *copy* the selected nodes of a scene to the current scene, a name like "Import nodes from scene" would be more explicit.

### PR DESCRIPTION
**Pull request by wbrbr**
The name "Sub-Scene" was confusing/not very clear. Fixes #3072

### CODE REVIEW

**Comment by kubecz3k** [comment]
@nounoursheureux I'm not sure about "Node from scene" guess you meant "Scene from node"?

**Comment by akien-mga** [comment]
> I'm not sure about "Node from scene" guess you meant "Scene from node"? Since with this option users are creating new scenes from the nodes...

Nope, that's precisely the confusion this PR is trying to solve :) "Import > Sub-Scene" imports one or several nodes from another scene into the current scene (as copies, not inherited). It's different from "Scene > Export > Sub-Scene" which creates a new scene based on the selected node and its children.

**Comment by akien-mga** [comment]
@nounoursheureux I think "Node**(s)** from scene" would be better, as it can import one or several nodes. Could you maybe add this as a fixup to your above comment? (using rebasing to merge the two commits into one).

**Comment by kubecz3k** [comment]
Oh my I thought it's about Scene->Convert to, sorry a lot!

**Comment by nounoursheureux** [comment]
@akien-mga Well you can't really choose multiple nodes, you can just choose one and it will also import its children. I think a plural would imply that you can select multiple nodes at the same time.
If you want I can change it, this is just my opinion.

**Pull request merged**
