### PR TITLE
In SnapDialog, repleaced "OK"/"Close" with "Apply"

### PR DESCRIPTION
**Pull request by greenfox1505**
I think this edit will makes it clear that a change will happen when the button is pressed.

### CODE REVIEW

**Comment by akien-mga** [comment]
This was already changed in #39262 by @aaronfranke from "Close" to "OK", which is the default and common "accept changes and close" button that Godot dialogs use.

Changing it again to "Apply" might make things clearer, but I'm not sure it's consistent with other dialogs that behave the same way.

**Comment by greenfox1505** [comment]
I realized that commit already happened while trying to commit my change. I thought "Apply" was still more clear.

If there are other unclear dialog boxes, I can run through them as well.

**Comment by Calinou** [comment]
In general, in UI conventions:

- **OK** applies the change and closes the dialog.
- **Apply** applies the change *without* closing the dialog.

This convention has been used since the Windows 9x days. I wouldn't dare to break it :slightly_smiling_face:

**Comment by aaronfranke** [comment]
I think "OK" is best. Aside from that, pull requests should be made against the master branch first, and they can later be cherrypicked for stable branches. Don't make PRs directly for the 3.2 branch.

**Comment by Calinou** [comment]
> Don't make PRs directly for the 3.2 branch.

To clarify, it's acceptable to do this for changes that can't be applied to the `master` branch (like #39376). That said, this PR could have been made against the `master` branch just fine.

**Comment by akien-mga** [comment]
Closing as per https://github.com/godotengine/godot/pull/39377#issuecomment-640280465, it's best as is then.

**Pull request closed without merging**
