### PR TITLE
Add apply node transforms option to rest fixer

### LINKED ISSUE #63641: Animation Retargeting Scale is .01 and corrupts the visuals
### Godot version

4.0 Alpha 13

### System information

Windows 11

### Issue description

During testing I noticed my rig after retargeting the scaling went to .001
image

image

I have attached my file and discussed it with @fire and it seems to be a bug.

I have found a workaround with using Fbx2GLTF importer

### Steps to reproduce

* I imported a mixamo rig into blender and moved the blend file into Godot.
* Retarged the rig 
* Opened the scene
* Scaling was broken

### Minimal reproduction project

[AnimationTest.zip](https://github.com/godotengine/godot/files/9222618/AnimationTest.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #63641. Implement apply node transforms in rest fixer.

image

This option discards all rotations and scales of the Skeleton's parent nodes and includes them in Rest (then that Scale is converted to Translate).

This can cause problems if there are Skeleton sibling objects or BoneAttachment in the scene, but since this is probably a corner case and this option can be disabled, so I think that it is not a problem for now.

### CODE REVIEW

**Comment by fire** [comment]
Lyuma had some off github discussion:

> トカゲ I'm not convinced this is the best approach
> I still think we should add a new bone as parent of other bones, which counteracts the node scale

**Comment by fire** [comment]
An alternative approach is start the skeleton at the common parent that is not identity transform

**Comment by TokageItLab** [comment]
The approach Lyuma described was to insert a bone to cancel the transform further into the parent of the bone root and keep parent node transform, but I disagree.

That approach requires a reserved word and means that if you take out the Skeleton after Make Local, the Transform of the Skeleton will change. This is an obstacle when creating a game with only the Skeleton extracted.

Also, unlike concepts such as virtual bones to fill in missing bones created during mapping, such as UpperChest, the insertion of cancel bones is a complete hack. It would be confusing because the average user would not realize that applying a deformation and implicitly adding a cancel bone are related.

So I rather prefer to correct the scale of the entire scene correctly in the pre process as in #60115.

**Comment by TokageItLab** [comment]
After discussions with @lyuma and @fire, we have reached an agreement that this PR has a different purpose than #60115 and that both can be implemented.

#60115 feature is intended to modify the root scale, and it fixes the LOD, etc. of the Mesh at a stage prior to PostImportProcess.

This PR feature is there mainly for retargeting and removes not only the Transform of the root node, but also all Transforms from SkeletonNode to the root node by applying them to the Bone.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This seems good, I feel we should ask a bit more for advise on some of the names for these things which may not be entirely obvious at first glance, although given we can document these properties nowadays it may not be as important.

**Comment by TokageItLab** [comment]
Yes, it is my todo to document retargeting and changed blend animations after the feature freezes.

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
Should this setting be disabled when Apply Root Scale is disabled? It seems counter-intuitive to have code that applies node transforms (including scale) when the import setting to apply root scale is disabled.

**Comment by TokageItLab** [comment]
This option is performed in priority to the disabling of Apply Root Scale because it is an option to eliminate all Transforms of the Skeleton's parent regardless of whether the node is root or not to remove visual differences in Skeleton.

**Pull request merged**
