### PR TITLE
Add an import setting to rotate the imported scene by 180 degrees

### LINKED ISSUE #6198: Add an option to fix the Z-forward vector when importing a GLTF file
### Describe the project you are working on

A 3D Game.

### Describe the problem or limitation you are having in your project

The GLTF specification says:

> glTF uses a right-handed coordinate system, that is, the cross product of +X and +Y yields +Z. glTF defines +Y as up. The front of a glTF asset faces +Z.

Which, for some reasons, contradicts Godot, which recommends that -Z be the forward direction.

In blender, if I have a character set up the conventional way:

Front view with -Y forward
*Front view with -Y forward*

I export it as gltf and import it into godot, my character is facing the wrong way.

Front camera is showing the back of my character.
*Front camera is showing the back of my character (he is looking towards +Z)*

image

This is what I found about GLTF decision:

- https://github.com/KhronosGroup/glTF-Blender-IO/issues/712
- https://github.com/KhronosGroup/glTF/issues/1043

--- 

This is not a discussion about which convention is the "right one". 

Changing the Z direction (or any other axis) in the editor has already been discussed [multiple](https://github.com/godotengine/godot-proposals/issues/545) [times](https://github.com/godotengine/godot/issues/17872#issuecomment-377691846) and rejected. This is a core design decision of Godot.

---

I don't want to manually flip all my characters so that they are facing the right way in Godot.
The vast majority of 3D tools with GLTF export will consider +Z as the forward direction.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I suggest adding an import option for GLTF, FBX  and blend files (they are all essentially importing GLTF) that allows users to flip the meshes and skeletons by 180° around the Y axis.

It should be convenient for users to use this as the default for all 3D imports.

Maybe this should even be the default behavior, otherwise meshes will be facing backwards most of the time.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

A checkbox in the importer labelled "-Z is forward (godot convention)" or something like that.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

One could write a custom import script that flips the root node.
But I think it is a question of having good defaults: using any model generated by 3D tools that export to GLTF will face backwards in the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

This reduces confusion when people use default methods like `look_at` and copy code from official tutorials, while using the vast majority of available 3D assets.

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR implements and closes https://github.com/godotengine/godot-proposals/issues/6198

This PR adds an import setting to rotate the imported scene by 180 degrees. This sets a negative X/Z scale that rotates by 180 degrees on the first level child nodes (same math as a Basis with rotate 180 deg Y, don't worry there are no negatively-scaled nodes in the final scene, even with apply root scale unchecked).

Bikeshedding: What should this option be called? I'm not totally sold on `rotate_180_degrees` since it doesn't describe how we're doing the rotation, but it is easy to guess that it's a rotation around Y (really on the XZ plane).

EDIT: Be aware that I changed the implementation since initially opening this PR. I collapsed several comments below as outdated. The new implementation does the rotation after most of the import logic, so it should be much safer.

### CODE REVIEW

**Comment by QbieShay** [comment]
Hey @aaronfranke , do you think it's possible to add a project settings flag to make this the default behaviour project wide?

**Comment by aaronfranke** [comment]
Screenshot 2023-02-05 at 6 17 01 AM

This is already possible, but I don't recommend it. Even for projects importing many characters and props facing +Z, it would be undesired to rotate other assets such as maps/terrain. Plus, even after testing and bug fixing, there will likely be edge cases broken with this enabled, so I would recommend users have it disabled by default and selectively enable for each asset they want to be rotated.

**Comment by fire** [comment]
Please do not merge until it works on all cases like the skeletons. You can see the previous attempts that were not conpleted. I believe the best way to do the flip is flip two axes of the scale and then apply the scale. Then there is some trickery with skins and its relation to the mesh transform.

**Comment by geowarin** [comment]
This does work for me in simple case where no skeletons are involved:

image

=>

image

But only when creating a new inherited scene. Previously created scene containing the model do not get updated.

It is very broken when a skeleton is involved:

image

**Comment by aaronfranke** [comment]
I attempted to fix the skeletons but I was not able to figure it out. I updated this PR to use a different approach, now it rotates the first-level child nodes instead of rotating the individual resources. This should be safer, although potentially not as optimal since some nodes have rotations, but since the root node is unscaled and unrotated it'll work with `look_at` etc. I tested with the mannequiny model and it works, so this PR can be re-tested.

However, please also give #72777 a test. I split the cleanup work into its own PR for easy reviewing, so we want to merge that one first before this PR can be undrafted. We want to verify that #72777 does not change behavior.

**Comment by QbieShay** [comment]
Does it affect root motion?

**Comment by TokageItLab** [comment]
If you have changed the orientation of the scene in the glTF document, the T-poser, etc. will not work properly because the retarget is based on +Z in accordance with glTF. It is necessary to save the rotation in the glTF document in meta or someway, and rotate the reference model using that as a flag.

**Comment by TokageItLab** [comment]
Also, since Godot has a glTF exporter, it should be necessary to implement rotation on that side as well. @fire

**Comment by aaronfranke** [comment]
@QbieShay No idea, do you have an asset we can test with?

@TokageItLab Same to you, do you have an asset we can test with?

> Also, since Godot has a glTF exporter, it should be necessary to implement rotation on that side as well.

It's not necessary, but we could add it as an optional feature. However what we should really do at some point is create a menu for the GLTF exporter that allows users to adjust various export options.

> In other words, if this is implemented for the sake of consistency, then it should be mandatory

I am VERY against this. We should *not* force assets to be rotated on import.

**Comment by fire** [comment]
The current status is that game developers need to scale/rotate their imported scenes manually ignoring the matters of axes convention.

I am against changing the gltf importer as importers should be defined in one way and gltf spec doesn't define an extension to rotate its conventions.

Something like an scene import option that adds a rotate basis and then applies it probably ideal. Similar to the float root scale that is applied.

I made an attempt to do this in a previous version of the apply root pr, but I decided to submit what I had then to only apply uniform scale.

If you can apply an non uniform scale like the two axes flipped, you can implement this feature there.

**Comment by TokageItLab** [comment]
I confirmed that the T-Poser is not working due to Apply 180 degrees, and the neck and legs are twisted and cursed.

What appears to be broken here is not the Pose (animation) of the model, it is the Rest. This means that the animation blending interpolation by AnimationTree will not work correctly.

image

However, Retargeter's Apply Transform option works fine, since it was added in the first place to remove the Transform of the Skeleton's parent.

image

But if you share the animation with a model that does not use the Apply Transform option, the animation will be broken. When sharing animations, we should not make the user think that the Skeleton's parent can have rotation.

image

For T-Poser to function properly, Apply 180 degree must be taken into account by Retargeter.

Alternatively, applying rotation after Retargeter is one workaround. That means creating it as a PostImportPlugin instead of a ResourceImporter and processing it later than Retargeter.

But, it remains rotation in the node and may further confuse the user, as mentions above.

[audio_blend_test.zip](https://github.com/godotengine/godot/files/10669745/audio_blend_test.zip)

> I am VERY against this. We should not force assets to be rotated on import. In fact it should be off by default.

I am confused as to your position. It makes it sound as if you are saying that glTF should hold assets in -Z Forward. In fact that did not happen, so glTF assets should be created +Z Forward.

Why do you against to force all object to -Z Forward? The T-poser is broken because it was designed based on +Z Forward in the first place, and if it had been designed with -Z Forward from the beginning, there would be no problem.

If what you mean is that Godot has already allowed +Z Forward to exist and cannot enforce it now, then I suppose it would would be helpful and compatible straightforward way to provide an API that supports +Z Forward, like #72795 does.

> Something like an scene import option that adds a rotate-scale basis and then applies it probably ideal. Similar to the float root scale that is applied.

This idea I might be able to agree with, it could be used to correct a non +Y UP model such as an imported in FBX to +Y UP +Z Forward to make the retargeting work. It does not conflict with #72795 for that purpose.

As a side effect, it can be used to import assets with -Z Forward, although that is not the normal and not recommended.

**Comment by aaronfranke** [comment]
> It makes it sound as if you are saying that glTF should store assets in -Z Forward.

If they want to, sure.

> Why do you against to force all object to -Z Forward?

* Not all models have a forward direction that needs adjusting. I don't want Godot rotating my terrain models.
* Not all models have the forward direction as +Z, that's just the recommended convention. Forcing all objects to rotate by 180 degrees will break any asset that is already facing the desired direction.

**Comment by TokageItLab** [comment]
I understand your statement, you want to allow -Z fronted assets in the glTF.

If you are the only one who uses an asset with a butt forward, that's fine, but it breaks the consistency of glTF and it should never be distributed in the asset store or elsewhere.

The fact that the asset is +Z Forward is a [glTF specification](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#coordinate-system-and-units). You may have doubts about that https://github.com/godotengine/godot-proposals/issues/6198#issuecomment-1417640334, but I am absolutely against supporting a -Z forward glTF on your doubts.

But, as noted in the comment above, if that is not the normal use, I think node rotation can be supported somewhere for non +Y UP model or something.

**Comment by aaronfranke** [comment]
@TokageItLab I tested your project and discovered something interesting. There is a pre-existing bug in Godot (in the current master) that is preventing the feature in this PR from working as intended.

I took some screenshots with this PR, testing the rotate 180 degrees setting and with apply root scale enabled, we can see that Blender-chan does not have its first-level node given a rotation. The retargeting is broken because something (the retargeter?) is changing the transform, applying it to the skeleton, and that something it is not able to handle the rotation.

<details>

Screenshot 2023-02-06 at 7 06 22 PM

Screenshot 2023-02-06 at 7 11 15 PM

</details>

The Blender-chan model always has the transform being applied, even when Apply Root Scale is disabled. This does not behave correctly even in master. The below screenshots are from master, and both GLTF models have the import settings set to a scale of 2 and Apply Root Scale disabled.

<details>

Screenshot 2023-02-06 at 7 19 41 PM

Screenshot 2023-02-06 at 7 19 46 PM

</details>

This also leads to another interesting observation: Godot has two different code paths for applying the root scale. One of them is triggered by the Apply Root Scale setting, and the other is applied afterwards, on top of the first scale application, on some models. This is extremely weird and it seems like a major issue to have two systems for doing the same thing (applying the root scale). How this did ever become a thing?

**Comment by TokageItLab** [comment]
See also https://github.com/godotengine/godot/pull/63662.
image

**Comment by aaronfranke** [comment]
I've spent several hours trying to solve this issue and I have been unable to. However, I did determine that the bug is actually not with Apply Node Transforms, because it happens even with that setting disabled. Anyway, I opened an issue, #72820 needs to be solved first in order for this PR to fully work correctly.

**Comment by TokageItLab** [comment]
This is a Fix Silhouet issue, not Apply Node Transforms. As explained above, SkeletonProfile(reference rest pose) is based on +Z Forawed, which means that if you want to apply rotation before PostImportPlugin, you also need to rotate SkeletonProfile.

So, as a simpler solution, I suggest creating a PostImportPlugin that does the rotation later than Retarget.

**Comment by aaronfranke** [comment]
I updated the PR with help from @TokageItLab. The fix ended up being simple, perform the rotation after all of the skeleton logic is run, so that the rotation does not interfere with the skeleton logic. It should be fully working now.

**Comment by TokageItLab** [comment]
This should work well, but a consensus is needed to decide if this is merged or not.

For now, it should be possible to create a PostImportPlugin add-on that provides the same functions, so we should provide that in the meantime.

---

**I have described retargeting at length above, but I will summarize it again:**

The retarget applies its parent's transform to match the direction of the bone and the direction of the movement animation with the visual (World coordinate).

At this point, the Forward axis of the asset must be defined to only one. Currently it is +Z, following the glTF specification.

At first this PR was trying to do a rotation before retargeting, which could cause the forward axis to not be defined as one. That is why I said it should be mandatory and not optional.

Now this PR does the rotation after the retarget, so there is no problem there.

---

However, this PR leaves the concept of +Z Forward on the asset.

I don't know what will be influenced by having a rotation on the parent node. (IK or PhysicsBone or something?)

Also, it makes the necessary hierarchy deeper due to the nodes for rotation.

So I still think we need +Z Forward support as well as #72795.

I think this PR and #72795 can coexist, but personally I want to give priority to A because the rotation of the parent node still looks like a hack.

If we don't want the parent node to have rotation, we would have to force -Z Forward on all processes as I said above, but it would no longer be possible.

---

Well, this is what we can do now for now.

> For now, it should be possible to create a PostImportPlugin add-on that provides the same functions, so we should provide that in the meantime.

**Comment by aaronfranke** [comment]
> Also, it makes the necessary hierarchy deeper due to the nodes for rotation.

It doesn't, at least not in this PR. Since GLTF allows defining multiple root nodes, Godot already imports an extra root node already, so we can just rotate the GLTF scene's root node which doesn't mess with any nodes deeper down.

> I think this PR and https://github.com/godotengine/godot/pull/72795 can coexist

I agree, they are not in conflict. If we accept both, we are giving users options. If we are picking one, we are enforcing a particular workflow. I would give priority to this PR, because it's the system I would rather use myself and it keeps a consistent forward direction, but I am not at all against your PR.

> because the rotation of the parent node still looks like a hack.

To be honest, you're right, it kinda is. My initial thought was to rotate all the meshes/skeletons/etc, but that's much more complicated and I was not able to figure it out. This setting could be improved in the future for Godot 5.0 or 6.0 or whatever so that it doesn't rotate the nodes and instead rotates the meshes/skeletons/etc. But this PR should work for nearly every use case, or maybe every use case, even if it's not theoretically the most optimal solution.

**Comment by aaronfranke** [comment]
@TokageItLab I don't think there is a point to abstracting this code out to a plugin with a whole other class. It's a very small amount of code. At most I could turn it into a method. Also, since it's a very small amount of code that many people would find useful, I think this should be in core.

**Comment by TokageItLab** [comment]
Lyuma and I agreed that having this just there as a checkbox is too little information and rather it makes more confusing.

After the #76060 or #76082 merge, this should no longer be necessary for those who follow the correct export/import process.

If it is a useful case for most people - if you have a model in the asset store that is facing the other way and you are using it to put it back in the right direction, you will need to rotate the Node before retargeting, not after retargeting.

But this PR stuff doesn't so, and should be an Add-on because it is focused on a special workflow. This is the view from the glTF pipeline team.

**Comment by akien-mga** [comment]
Is this still wanted after the other changes merged to handle this issue?

**Comment by aaronfranke** [comment]
I won't be using this option personally. I still think this is handy to have in core to give users the freedom to alter their assets after import, but I won't be sad if this PR is closed.

**Comment by aaronfranke** [comment]
While this option may be useful for some users, since I will not be using it personally, and as Tokage explained this is not used in the "files are +Z, game logic is +Z" workflow and it does not help the "files are -Z" case whenever skeletons are involved. Also as Tokage explained, the "files are +Z, game logic is -Z" case is considered an unsupported / special workflow and Tokage says this should be an add-on (and really, it can be, there is no reason this can't be done in user code, it's just a question of if it's convenient to have in core). Therefore, I am closing this PR.

For the record with the above discussion, [handedness is a mathematical concept](https://en.wikipedia.org/wiki/Chirality_(mathematics)), it is not related to how the default orientations of cameras and assets are laid out relative to each other.

**Pull request closed without merging**
