### PR TITLE
Fix animation not stopping after seeking to the end

### LINKED ISSUE #10228: AnimationPlayer.seek() causes animation to get stuck
**Operating system or device - Godot version:**
Ubuntu 16.04
godot 2.1.3-stable
godot 2.1.4-beta_20170731

**Issue description:**

AnimationPlayer.seek() to the exact start or end time of an animation causes it to get stuck. Meaning if for example opacity is set to 0 at that time, the animation keeps setting opacity to 0, and can't be changed unless the AnimationPlayer is manually stopped or given another animation to play.
```
animation_player.play("anim")
animation_player.seek(animation_player.get_current_animation_length(), true/false)
```
or
```
animation_player.play_backwards("anim")
animation_player.seek(0, true/false)
```

**Steps to reproduce:**

1. Create an AnimationPlayer
2. Create a simple animation that animates a property
3. Create a script that starts the animation and then seek to 0 or the animation length
4. Try and modify the same property from the Remote Inspector and observe as it changes back

If you seek to 0.1 second instead of 0 or to animation length - 0.1 instead of animation length, it stops the AnimationPlayer correctly.

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by RandomShaper**
~~The issue fixed is explained at #10228. Since that was reported for 2.1, the specific PR for that version is the one that closes it.~~

Fixes #10228.

### CODE REVIEW

**Comment by akien-mga** [comment]
> Since that was reported for 2.1, the specific PR for that version is the one that closes it.

Too bad that "Fixes #issue" works only when merging on the master branch ;)

**Comment by RandomShaper** [comment]
Hmm... That explains why it didn't work «sometimes». XD

I don't get what you mean in your second paragraph. If it helps, the issue was reported for 2.1 but I've reproduced it on _master_ as well.

**Comment by akien-mga** [comment]
I just meant that if an issue is reported against 2.1 but also affects master, it should be fixed in master in priority. Backporting the fix to 2.1 for a potential 2.1.x release is just a bonus, the proper commit that fixes the issue would be the one of the master branch.

**Comment by RandomShaper** [comment]
OK!

"Fixes" moved to this one.

**Pull request merged**
