### PR TITLE
Remove up/down input for text search in Tree

### LINKED ISSUE #34941: Toggle select issue in multi-select mode Tree
**Godot version:** v3.2.beta.custom_build.e7b7dc57f

**OS/device including version:** macOS Catalina 10.15.2 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

In multi-select mode Tree, the "ui_select" action can be used to toggle the selection state of the current focused cell. But after toggling, the next Up/Down arrow key fails to move the cursor. (Left/Right arrow key works fine.)

I tested the official builds, this behavior exists in 3.2 alpha0, and does not happen in 3.1.2 stable.

Also, in the default Input Map, both "ui_select" and "ui_accept" contains the Space key. I have to remove the Space key from "ui_accept" to make the toggling work. (Otherwise, the Space key will do activation instead of toggling.)

FYI: 3.1.2 uses direct key handling instead of the action mechanism.

**Steps to reproduce:**
1. Prepare the project (or use the reproduction project below)
    1. Create a Tree, and set its "Select Mode" to "Multi"
    2. Delete "Space" from the "ui_accept" action in Input Map
    3. Add some items to the tree with the script
2. Run the project
3. Click on any cell to select it
4. Play with the Up/Down key freely, the cursor will move accordingly
5. Press Space, the selection state of current cell is toggled
6. Press Up/Down, the cursor won't move
7. Press Up/Down again, the cursor moves

**Minimal reproduction project:**
[Test3.1.2.zip](https://github.com/godotengine/godot/files/4038277/Test3.1.2.zip)

### PR DESCRIPTION
**Pull request by marzecdawid**
Fixes #34941

If you press any key with unicode>0 you get this "bug" (Space bar has code 32). Actually it is not a bug; if you start the text search by pressing any char key then for 1sec you can move to next or previous matching item by up and down keys, so if there is no more items it just do nothing.

For me it also looked like a bug so I think this functionality should be removed as you can iterate through matched items by clicking again the same char key, and blocking the up and down input for 1 sec is more annoying than helpful.

### CODE REVIEW

**Comment by EricEzaM** [comment]
Yeah this feature is not super consistent I will give you that.

> I think this functionality should be removed as you can iterate through matched items by clicking again the same char key

Not if you have typed a larger string - say, 5 characters.

You can also only use the "press an arrow key to go to next match" once, because after you press an arrow key the below condition is triggered and the last_keypress is reset. So the feature doesnt really work properly anyway.

https://github.com/godotengine/godot/blob/91713ced81792b10fdc9367b7f355738e5d52777/scene/gui/tree.cpp#L3369-L3373

Removing it is probably fine. But some may want to salvage the feature rather than remove it so I have added the discussion label for now to see what people think.

**Comment by marzecdawid** [comment]
> Not if you have typed a larger string - say, 5 characters.

> Currently, you can also only use the "press an arrow key to go to next match" once, because after you press an arrow key the below condition is triggered and the last_keypress is reset. So the feature doesnt really work properly anyway.

So the usefulness of this functionality looks to be very small, especially that so far no one has reported the problem that you can only move once using arrow keys.
I would suggest to remove it and eventually consider improving navigation by using char keys; for example ability to jump to previous matching results by SHIFT + char key.

**Review by KoBeWi — APPROVED** [review]
I agree that this "feature" is rather odd. You can achieve the same just by pressing the same char again, which is consistent with how incremental search works in other controls.

**Comment by akien-mga** [comment]
Looks good to me too. I agree that if it only works once for a given pattern, then it doesn't seem to be actively in use.

I'd suggest rebasing the PR on latest `master` for good measure. It should still build fine without any problem but having it rebased will avoid a big jump back in time in case a git bisect step lands on this commit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
