### PR TITLE
Fix crash when printing leaked nodes

### LINKED ISSUE #39937: Crash when printing info about leaked nodes
**Godot version:**
4.0.dev.custom_build. 481151be0

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When I run `godot4s -e -q -v` then Godot crashes with this backtrace
```
core/object.cpp:2055:29: runtime error: member access within null pointer of type 'struct Object'
handle_crash: Program crashed with signal 11
Dumping the backtrace. 
[1] godot4s() [0x19c4a60] (/mnt/Miecz/mojgodot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f834d5d1210] (??:0)
[3] ObjectDB::cleanup() (/mnt/Miecz/mojgodot/core/object.cpp:2055)
[4] unregister_core_types() (/mnt/Miecz/mojgodot/core/register_core_types.cpp:317)
[5] Main::cleanup() (/mnt/Miecz/mojgodot/main/main.cpp:2430)
[6] godot4s(main+0x32b) [0x19c2831] (/mnt/Miecz/mojgodot/platform/linuxbsd/godot_linuxbsd.cpp:59)
[7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f834d5b20b3] (??:0)
[8] godot4s(_start+0x2e) [0x19c244e] (??:?)
```
For now in master it may crash in a different places due other bugs

**Steps to reproduce:**
1. Run project with this flags `godot4s -e -q -v`

**Minimal reproduction project:**
[Mini.zip](https://github.com/godotengine/godot/files/4844388/Mini.zip)

### PR DESCRIPTION
**Pull request by qarmin**
Fixes #39937
I couldn't find any reason why object is nullptr, because code looks fine.
This is maybe not the best solution, but allows to get info about leaked nodes which is very helpful to find regression and leaks.

CC @reduz since this code was added in https://github.com/godotengine/godot/commit/867d073b98344b848c96012418912a7e72841a31

### CODE REVIEW

**Comment by RandomShaper** [comment]
I'm not sure that's enough. That could skip some objects.

I've been trying to come up with the algorithm that would iterate through the used object slots (by the way, that would apply both for `ObjectDB::cleanup()` and `ObjectDB::debug_objects()`).

After playing a bit with creating and destroying objects in different orders, I've reached this state in the `object_slots` array:
image
(With `slot_count = 7`,  `slot_max = 16`.)

After considering that case, the only solution that comes right now to my mind is the following, but I suspect this is not leveraging the design of this data structure for doing it more optimally:
```
uint32_t count = 0;
for (uint32_t i = 0, count = slot_count; i < slot_max && count != 0; i++) {
	if (object_slots[i].validator) {
		// Do whatever with object_slots[i].object

		count--;
	}
}
```

**Comment by RandomShaper** [comment]
I'd still like to know @reduz's opinion about this implementation, because I still think there is a non-brute-force approach.

Anyway, I guess this could get merged because it already addresses the issue and an optimization can be done later.

**Review by RandomShaper — APPROVED** [review]

**Comment by reduz** [comment]
Looks ok to me

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
