### PR TITLE
Use `virtual` and `override` whenever possible.

### PR DESCRIPTION
**Pull request by hbina**
I have noticed that some of them does not properly overload the base class because they  do not use the `virtual` keyword.

I am on Linux so this will inevitably fail to compile with other stuff. But I thought some of you may find this interesting.

While refactoring, I also had to add a new macro `BIND2_NO_OVERRIDE`. Quite interesting that this is only needed _once_.

I have no hope of this every merging.

Additionally, I have also discovered instances of pass by value of `String`s which AFAIK, requires atomic operation. Will make a different  PR for that.

### CODE REVIEW

**Comment by kuruk-mm** [comment]
You also refactor thirdparty, I don't think that necessary.

**Comment by hbina** [comment]
@kuruk-mm yea, that is probably undesirable. 

I have noticed that `object.h` have some very common names like `_set` and `_get`.
Considering how much hierarchies are utilised in the project, I think  making the compiler error out when the user unintentionally overrides a base class is something that we all want to have.

**Comment by aaronfranke** [comment]
@hbina Is this still desired? If so, this needs to be rebased on the latest master branch, and the above feedback addressed.

**Comment by akien-mga** [comment]
This would need to be redone on the current codebase, ideally with tooling so that it's easy to update if needed (did you use `clang-tidy` for this or another tool?).

**Pull request closed without merging**
