### PR TITLE
SCons: Replace `_find_scu_section_name` function with SCons builtins

### PR DESCRIPTION
**Pull request by ghost**
Not only that it is a clean up and ammending of custom workaround but it also transparently allows to process SCons specific paths which contains `#` in the starts (which in turn in the future should allow me to implement SCU for thirdparty sources which should greatly increase compilation speed)

### CODE REVIEW

**Review by Repiteo — APPROVED** [review]
More native SCons implementations are always a plus!

**Comment by dustdfg** [comment]
I've just found that `scu_builders.py` have a `Ctrl+C, Ctrl+V` version of methods I am deleting in this PR. I think this should be done in this PR too. I've also noticed that tendency not to use SCons related stuff inside builders... An when I tried to add `from misc.utility.scons_hints import *` to file and it didn't work :sweat_smile: I delayed that question as much as possible but it is time to ask. Why does builders doesn't use SCons?

**Comment by dustdfg** [comment]
> I've just found that `scu_builders.py` have a `Ctrl+C, Ctrl+V` version of method I am deleting in this PR.

Oh. I was a bit wrong. It returns in format `dir_dir_dir` instead of `dir/dir/dir` so it is for another PR  :thinking:  or for this... Anyway this PR again can be considered as ready to be merged :sweat_smile:

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
