### PR TITLE
Open the directory where the project was exported to in the default file manager

### LINKED ISSUE #4114: Add ability to open the directory where the project was exported to in the default file manager
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

It's often tedious to find the directory where the project was exported to, especially when working on networking or while having complicated folder structures. Unity solves this by automatically opening the directory where the project was exported to, so a similar feature for Godot would be useful and save some time.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an optional setting to Godot that allows opening of the directory where the project was exported to.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The option can be enabled/disabled in the editor settings when the user presses the export project or export pck buttons, upon successful export the directory that the files were exported to will be opened in the default file manager.

Here is a demo of the proposed feature.

https://user-images.githubusercontent.com/46562098/155687463-65388a59-f19e-4963-9f2f-92f99946fee5.mp4

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If this enhancement is not desired, it could be easily switched off in the editor settings, Implementing a similar feature in a script can be a hassle.

### Is there a reason why this should be core and not an add-on in the asset library?

This is a usability enhancement that should improve the general workflow of users who do lots of iterative builds, for example while working on networking projects, such a feature can be implemented with an add-on, but I think this will hurt the said feature as it would not be as widely known of and will force the user to either find a working add-on or implement a similar feature themselves which can be tedious.

### PR DESCRIPTION
**Pull request by doot24**
It's often tedious to find the directory where the project was exported to, especially when working on networking or while having complicated folder structures. Unity solves this by automatically opening the directory where the project was exported to, so this pull requests adds the same feature to Godot.

https://user-images.githubusercontent.com/46562098/155611130-7bb6f2a8-72b5-4283-9134-faa86fb48cbb.mp4

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/4114.*

### CODE REVIEW

**Comment by Calinou** [comment]
Make sure to check the behavior of this when exporting in headless mode (`--headless` command line argument in `master`). This option should always be considered disabled in headless mode, as people may be running headless mode on actual desktop systems.

**Comment by doot24** [comment]
> This is a good idea, but make sure to check the behavior of this when exporting in headless mode (`--headless` [command line](https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html) argument in `master`). This option should always be considered disabled in headless mode, as people may be using headless project exporting on actual desktop systems. Opening windows without prompting the user is considered disruptive for the user's workflow, so it should be avoided.
> 
> Some other notes:
> 
> * This should be implemented for all platforms, not just Windows/macOS/Linux exports. This behavior won't be needed as often for Android, HTML5 and iOS, but we should strive for consistency.
> * When using the **Export All** button, only one file manager instance should be opened (and not several), regardless of how many export presets there are.
> 
> PS: Consider opening a [proposal](https://github.com/godotengine/godot-proposals/issues) to gather community support. This will make it more likely that this pull request is merged 🙂

Having some difficulty with --headless mode, is trying to get the argument from the command line not the right way to check if the build is in headless mode?

**Comment by doot24** [comment]
Opening android and web directories are now working, hesitant to do it for ios since I can't test if the process will work without any issues since I can't export for ios.

As for Export For All, how should it behave? Since there are multiple exports, figuring out which the player wishes to be opened is difficult, should it be based on which ever is first in the list or should Export For All not open any directories since that goes beyond the 'frequent exporting is tedious' reasoning.

**Comment by mhilbrunner** [comment]
We discussed this in today's PR meeting and agreed this would be nice to have.

If the feedback above is adressed (especially that of Calinou) in time for 4.0, it can still go in, otherwise it'll go into the next 4.x release once its ready.

**Comment by doot24** [comment]
> We discussed this in today's PR meeting and agreed this would be nice to have.
> 
> If the feedback above is adressed (especially that of Calinou) in time for 4.0, it can still go in, otherwise it'll go into the next 4.x release once its ready.

Decided to resubmit this pr after re doing it.

**Comment by akien-mga** [comment]
Superseded by #65201.

**Pull request closed without merging**
