### PR TITLE
SkeletonDefinition Implementation

### PR DESCRIPTION
**Pull request by marstaik**
Allows Skeletons to share a common definition, as well as export skeletons for future use in other scenes.

### CODE REVIEW

**Comment by marstaik** [comment]
Quick preview about what this SkeletonDefinition allows users to do:
https://f.staik.net/f/2cx.mp4

**Comment by fire** [comment]
Imagine you want to exporting clothes when you don't have all the bones. 

A master skeleton scene has every bone. So this skeleton structure should also have all the information to look up the name of the bones in the master skeleton.

The skin will do the remapping of the skeleton. The bone indices are indices to the skin which remap to indices in the skeleton.

Assumption: The new scene's skeleton is already assigned to existing mesh instances-likes.

My proposal is that SkeletonDefinition will follow every assigned mesh and create such skins after the import of the SkeletonDefinition.

**Comment by fire** [comment]
I've updated the pull request for the crash fix and to implement the above feature.

https://github.com/fire/godot/commit/249568989ff6458745297a6ba01a922419c65b58

Visually, it's importing skeleton defintions.

**Comment by marstaik** [comment]
Replaced partially by https://github.com/godotengine/godot/pull/36409

You can also now use scene instances of a skeleton to achieve the same effect, as meshes wont fail to bind by bone name anymore.

**Pull request closed without merging**
