### PR TITLE
SIMD optimization for AABB::intersects_segment

### PR DESCRIPTION
**Pull request by caospacifico**
"AABB::intersects_segment" is optimized with Intel SSE instructions and runs ~2X as fast as the original.

Running:
valgrind --tool=callgrind --toggle-collect=TestAABB::test_aabb\* --cache-sim=yes --branch-sim=yes ./bin/godot.x11.64 -test aabb

then:
kcachegrind callgrind.out.*

Normal binary output shows a cycle estimation of 971474:
KCachegrind AABB No SIMD

SIMD optimized binary shows a cycle estimation of 515142:

KCachegrind AABB SIMD

NOTE: Only optimized for GCC, Intel SSE, and single precision floating point!  It will compile on other platforms but won't be optimized.

### CODE REVIEW

**Comment by reduz** [comment]
this is pretty cool, I was planning to do a whole overhaul of the math
stuff using simd after next version, so will most likely use this PR as a
base

**Comment by jjdicharry** [comment]
I was trying to make the Vector3 class SIMD optimized but that created more problems because Intel requires SSE operations to be aligned at address that are multiples of 16.  So I created a Vector3_simd class that I only use in AABB::intersects_segment where I can control its alignment.

**Comment by reduz** [comment]
It should be ok to add an extra float, I think I wrote all the code in the
engine with the expectation that an extra one would eventually be added.

**Comment by jjdicharry** [comment]
Thanks for thinking my contribution is cool! It did speed things up quite a bit!  Also, I know about the extra float in Vector3.  The problem is more complicated than that though.  You have "new" and "malloc" which aren't guaranteed to be aligned. Vector3 could be in a struct or class, i.e. "struct {int a, Vector3 v};" that will throw the alignment off by 4 bytes.  These are issues that are not impossible to fix but there are a lot of fixes to be made.  Another thing is that other contributors in the future would have to consider the alignment when they want to use these SIMD objects.  I just wanted to commit to the project without introducing a lot of bugs!

**Comment by jjdicharry** [comment]
I may have a solution to the alignment issue.  The SSE "movups" instruction
can be used to move unaligned data to "xmm" registers which can be used on
each math operation.  This way the SSE instructions can be used without
issues. But I don't know if adding "movups" instructions will make every
math operation faster.

**Pull request closed without merging**
