### PR TITLE
Fix debug navmesh errors

### LINKED ISSUE #59845: Debug navmesh throws errors if navmesh is not pre-baked
### Godot version

3.x

### System information

manjaro linux

### Issue description

In case of runtime 3D navmesh baking it's pretty normal to not have pre-baked (empty) navmesh when running the scene.
If one enables `Debug->Visible Navigation` flag in the above situation, 2 non-critical errors are being thrown:
```
ERROR: Condition "array_len == 0" is true.
   at: mesh_add_surface_from_arrays (servers/visual_server.cpp:1065)
ERROR: Condition "len == 0" is true.
   at: add_surface_from_arrays (scene/resources/mesh.cpp:797)
```

### Steps to reproduce

1. Create a 3D scene with intact `NavigationMeshInstance`
2. Enable `Debug->Visible Navigation` flag
3. Run the scene

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Scony**
fixes #59845

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this also relevant for the `master` branch?

**Comment by Scony** [comment]
@akien-mga yes. Do you want me to create cherry-pick MR? Or would you like to try automatic cherry-pick first (should be doable)?

**Comment by akien-mga** [comment]
A dedicated PR would be good, we cherry-pick down, not up.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Scony** [comment]
@akien-mga done: https://github.com/godotengine/godot/pull/59893

**Pull request merged**
