### PR TITLE
[3.x] Fix the editor theme application for the Mono build log

### PR DESCRIPTION
**Pull request by YuriSizov**
A `3.x` version of https://github.com/godotengine/godot/pull/51220.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Flavelius** [comment]
Should this be found in 3.3.3? This seems to have been merged at aug 3, 3.3.3 according to the website was released on aug 19; but it still has the illegible output panel in light theme.

**Comment by aaronfranke** [comment]
@Flavelius The 3.x branch will become 3.4, not the next 3.3.x release. The 3.3 branch is for the next 3.3.x release, but this PR has not been cherry-picked to the 3.3 branch. We can still do that for 3.3.4 if this feature is known to not cause regressions and there is consensus that it should be backported. Typically 3.3.x primarily gets bugfixes since it's the stable branch.

**Comment by pycbouh** [comment]
It should be okay to cherrypick for the next 3.3 release, I think.

**Comment by raulsntos** [comment]
If this is cherry-picked, #51325 should be cherry-picked too.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.4.

**Comment by akien-mga** [comment]
So this probably requires a dedicated PR if wanted in `3.3` as there's too many issues for me to cherry-pick it safely without risk of breakage:
- #51325 must be included too
- `font_color_readonly` doesn't actually exist in `3.3`

**Pull request merged**
