### PR TITLE
Fix #6913, theme editor regression in 2.1.1 rc

### LINKED ISSUE #6143: ConfirmationDialog wrong position buttons
**Operating system or device - Godot version:**
Windows 10-64 bit - 2.1-stable

**Issue description** (what happened, and what was expected):
What happened : 

capture

What was expected :

capture_2

**Steps to reproduce:**
I have create a button and when i click it to open the pup up(ConfirmationDialog). The popup it shows but the OK button and the Cancel button at wrong position (Picture 1). When i try to move the popup the buttons get the right position (Picture 2).

### LINKED ISSUE #6913: Theme editor regression in 2.1.1 rc
**Operating system or device - Godot version:**
Ubuntu 16.04 / Windows 7 64b

**Issue description** (what happened, and what was expected):
Dialogs for adding / removing properties to / from theme have misplaced buttons.
It's working properly on 2.1 stable.

**Steps to reproduce:**
Open theme editor and then one of dialogs.

**Link to minimal example project** (optional but very welcome):
theme_bug

### PR DESCRIPTION
**Pull request by pkowal1982**
After #6423 which fixed #6143 absolute layout of theme editor popups stopped working.
It should work now. I had a little problem with centering (maybe it's another thing to fix) so any help appreciated with this `show()` before `popup_centered()`.

### CODE REVIEW

**Comment by akien-mga** [comment]
What about the master branch?

**Comment by pkowal1982** [comment]
It says can't automatically merge. Should I create new commit based on master?

**Comment by akien-mga** [comment]
If the regression is in the master branch too, please do yes.

**Comment by pkowal1982** [comment]
Ok, I've checked the log once again. The problem was caused by #6748 which was reverted in master by #6986 today. So there is no need to create PR for master because problem is gone.

**Comment by pkowal1982** [comment]
As the issue was fixed by #6986 I'm closing this one. Probably I'll clean up the code in theme editor a little more and then do the commit to the master, as it is still worth to change layout from absolute to grid.

**Pull request closed without merging**
