### PR TITLE
Make GDNative work on Android

### PR DESCRIPTION
**Pull request by endragor**
The changes include work done to ensure that GDNative apps and Nim
integration specifically can run on Android. The changes have been
tested on our WIP game, which uses godot-nim and depends on several
third-party .so libs, and Platformer demo to ensure nothing got broken.

 - .so libraries are exported to lib/ folder in .apk, instead of assets/,
   because that's where Android expects them to be and it resolves the
   library name into "lib/<ABI>/<name>", where <ABI> is the ABI matching
   the current device. So we establish the convention that Android .so
   files in the project must be located in the folder corresponding to
   the ABI they were compiled for.

 - Godot callbacks (event handlers) are now called from the same thread
   from which Main::iteration is called. It is also what Godot now
   considers to be the main thread, because Main::setup is also called
   from there. This makes threading on Android more consistent with
   other platforms, making the code that depends on Thread::get_main_id
   more portable (GDNative has such code).

 - Sizes of GDNative API types have been fixed to work on 32-bit
   platforms.

### CODE REVIEW

**Review by karroffel — APPROVED** [review]
GDNative stuff looks all fine! I am no Android developer, but the Java part looks reasonable too 😄 

Maybe some Android wizard should take a look too, but it all looks good to me.

**Comment by reduz** [comment]
@RandomShaper @volzhs Would appreciate if you take a look at this.

Also, I think the way the .so libraries are handled needs to be improved, so the exported is told precisely which ones get exported and which ones do not.

**Comment by endragor** [comment]
We simply use include filters to select .so libraries. Could you please elaborate your idea? The problem with Android is that libraries should be located precisely within `/lib/<ABI>/` folder and you should use the name of the .so file within that folder. So .apk may have `/lib/armeabi-v7a/libmy.so` and `/lib/arm64-v8a/libmy.so` and you should call `dlopen("libmy.so")` and the runtime will select the correct library. In Godot project you can have `lib/android/armeabi-v7a/libmy.so`, `lib/android/arm64-v8a/libmy.so` and specify include filter `lib/android/*.so`  for shared libraries to be exported correctly.

**Comment by akien-mga** [comment]
I know that @reduz and @karroffel discussed some changes to the GDNative API regarding exporting, but I think we could still merge the current state of this PR (after a rebase) as it improves the situation a lot. I'm sure @endragor will also be up to do further adjustments when the GDNative API does change (which won't happen right away as @karroffel is quite busy).

**Pull request merged**
