### PR TITLE
Only display a virtual keyboard if the text can be edited.

### PR DESCRIPTION
**Pull request by capnm**
@pouleyKetchoupp I found this very useful, but I can only test & commit to the 3.2 branch.

### CODE REVIEW

**Comment by Calinou** [comment]
This makes it no longer possible to copy read-only text in a LineEdit/TextEdit. That said, I think the rest of the Android/iOS system behave like that?

**Comment by capnm** [comment]
Oh, I only tested the Android virtual keyboard and couldn't find any copy / paste function, so I found opening the keyboard just annoying. Is it broken or how is it supposed to work?

Another way I could imagine would be to revive something like #33597 so you can at least disable it manually.

**Comment by Calinou** [comment]
@capnm You can select the text by doing a long press then choosing **Copy** in the pop-up dialog that appears. That's how it works in native Android applications at least.

**Comment by capnm** [comment]
> You can select the text by doing a long press on the text itself then choosing Copy in the pop-up dialog that appears. That's how it works in native Android applications at least.

Godot uses its own widgets (TextEdit, LineEdit) so that doesn't work. I think opening the virtual keyboard here doesn't bring any functionality and feels very annoying.

**Comment by KoBeWi** [comment]
> Godot uses its own widgets (TextEdit, LineEdit) so that doesn't work.

Well, we'd need to implement it ourselves, because every app does it differently. The Copy button should appear when a text is selected (and this could be added to RichTextLabels too).

**Comment by capnm** [comment]
> Well, we'd need to implement it ourselves, because every app does it differently. The Copy button should appear when a text is selected (and this could be added to RichTextLabels too).

I think that is clear to everyone;) But I am talking about and have to deal with the current state.

**Comment by pouleyKetchoupp** [comment]
Your use case makes sense, but instead of making specific changes for read-only, I would rather go for the more generic option B that you mentioned, which is to revive something like #33597.

I'll try to find some time tomorrow to open a new PR for it on master and then we can backport it to 3.2.

**Comment by pouleyKetchoupp** [comment]
Superseded by #40588.

**Pull request closed without merging**
