### PR TITLE
Allow drag and dropping ShaderMaterial in 3D viewport

### LINKED ISSUE #90075: the "drag and drop a material on a mesh instance" does not work for a ShaderMaterial
### Tested versions

- Reproducible in 4.2.1.stable (both linux flatpak and download from godotengine.org)

### System information

Godot v4.2.1.stable (b09f793f5) - Freedesktop SDK 23.08 (Flatpak runtime) - X11 - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) () - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

PR #56597 adds drag-and-drop support for materials in 3D instances. However, it appears that it does not work for ShaderMaterials.

https://github.com/godotengine/godot/assets/1830798/0591786e-487d-4064-92ee-fb0f51047008

I assume this is a bug and not a feature request. However, I noticed that in the issue description #87425 it is mentioned that "_shader materials cannot be dragged_". So, is this actually normal behaviour? What would be the reason to exclude ShaderMaterials from this wonderful experience? :)

### Steps to reproduce

- Create ShaderMaterial resource
- Add a new Shader to the material
- Drag the material over a MeshInstance3D in the viewport

### Minimal reproduction project (MRP)

[minimal.zip](https://github.com/godotengine/godot/files/14816570/minimal.zip)

### PR DESCRIPTION
**Pull request by themancalledjakob**
Fixes #90075

### CODE REVIEW

**Review by fire — APPROVED** [review]
I don't recall any reason why this would fail, but it's also a long time ago.

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by themancalledjakob** [comment]
> For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

good catch! thanks

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
