### PR TITLE
Make non pressure sensitive device behavior consistent.

### PR DESCRIPTION
**Pull request by bruvzg**
- Sets pressure to `1.0f` when primary button is pressed and to `0.0f` otherwise for devices that are not pressure sensitive (e.g. mouse). This behavior is already default on macOS, on Windows and Linux it was always retuning zero pressure. This change allows use of the same input code for both mouse and tablet.
- Add some extra checks on Windows, to avoid reading unsupported pressure/tilt values.

Related proposal - https://github.com/godotengine/godot-proposals/issues/426

### CODE REVIEW

**Comment by SleepProgger** [comment]
I realize the relevant codebase seem to have changed a bit, but any chance in this being backported to 3.2 ?

**Comment by bruvzg** [comment]
> I realize the relevant codebase seem to have changed a bit, but any chance in this being backported to 3.2 ?

It's just moved from OS to DisplayServer, relevant code is the same, backporting will be easy, and #37756 should be cherry-picked first.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
