### PR TITLE
Moved paragraph spacing to XML files in help docs

### PR DESCRIPTION
**Pull request by leezh**
Rather than being generated automatically (and inaccurately).

Also, using dedent() the use of tabs in code blocks works now, so you can easily copy/paste code from the help files.

I also did a quick pass-over, doing minor corrections wherever I see them.

### CODE REVIEW

**Comment by akien-mga** [comment]
Not OK. It's much better to let the engine do the job properly than to impose such restrictions on doc writers.

**Comment by akien-mga** [comment]
I mean, this is one of the possible solutions, but I'm not sure changing constraints on the source is better than fixing it downstream so that it's parsed as it was meant to be. At any rate, it should be discussed beforehand with the doc team to see which workflow will provide the most consistency.

In the online docs in reST (but markdown would be the same), there are no line breaks. A newline == a new paragraph (`<p>`). So all those added newlines will mean empty paragraphs and terrible online docs. Of course we can fix the reST conversion script so that it no longer doubles newlines to make paragraph, but that means that the offline and online docs will behave differently: line breaks will work as written in the offline docs, and will be reflowed on the previous line on online docs.

Now, the only issue with the downstream processing is that you're doing string replace in the whole description content. `[codeblock]` is meant to be parsed as preformatted text (minus the tab-based indentation, and the space based code indentation should stay as is), so newlines should of course not be doubled in it. So a `description.replace("\n", "\n\n")` can't work, it needs to parse the data and isolate the codeblock stuff.

If `dedent` is too eager and breaks stuff, it's quite easy to just remove the right amount of tabs, as it's hardcoded in the XML generation too. Each kind of `<description>` field will have a fixed number of tabs based on the element it's describing.

**Comment by leezh** [comment]
I might've put a few changes into one commit. Sorry if it caused some confusion.

For the moving of the double-newline to the XML docs: I agree it could probably be done with better downstream processing. I'll see what I can do about that.

For the `dedent` related changes, nothing was broken. It's just that now you don't need force the docs team to use four space indentation just so that it can be preserved, and I wanted to do those changes to reflect that. The output with and without those changes are exactly the same.

**Comment by leezh** [comment]
I'll abandon this pull request and once I've come up with a more elegant solution I'll open up a new one.

**Comment by akien-mga** [comment]
> For the dedent related changes, nothing was broken. It's just that now you don't need force the docs team to use four space indentation (mixed in with the tabs) just so that it can be preserved, and I wanted to do those changes to reflect that. 

Yeah but actually that was a feature, since the normal XML indentation and the codeblock indentation are completely unrelated concepts, so it's good to use different indentation styles IMO. We could decide to use tabs if most contributors think it more convenient, but at least so far it was not pointed out as a bother.

CC'ing @godotengine/documentation as I've expressed my own opinion, but some might have different feelings about the proposed changes. The single/double newline stuff is often confusing to new contributors, so it's worth asking ourselves if we want to adapt it (even if, as I expressed above, I'm not sure that putting less constraints on the formatting on the input side will help have a consistent style).

**Comment by akien-mga** [comment]
Maybe we should define exactly what we want both the online and offline docs to be like once post-processed, and then define what the common source format should be like. I didn't mean to reject your proposal as a whole even if I might have been a bit snappy in my first comment; there are various issues with the current workflow that might be worth addressing via a bigger change.

**Comment by leezh** [comment]
Oh, no probs. Looking back, those changes looked quite messy anyways and it'd be easier doing any changes from scratch. But yeah, a discussion on how it should look would be nice. Perhaps an issue tracker?

Once finalised, I'd be happy to volunteer implementing the offline side of things.

**Pull request closed without merging**
