### PR TITLE
[3.x] Add support for single compilation unit builds

### PR DESCRIPTION
**Pull request by lawnjelly**
_AKA Unity / Jumbo builds._

Adds support for simple SCU build (DEV_ENABLED only). This speeds up compilation by compiling multiple cpp files within a single translation unit.

This is an **optional** extra build that occurs when you set `use_scu=yes` in Scons. It currently only works in conjunction with DEV builds. All other regular builds work as normal.

## FAQ
* SCU builds are **TOTALLY OPTIONAL**.
If you wish you can totally ignore the existence of this build, and forget they exist.
* SCU builds are primarily for contributors, to speed up iteration time during development by reducing compilation time. This is particularly useful for people who would prefer to be productive.

## Introduction
<details>
<summary>Especially relevant for those that have not used this type of build before.</summary>
SCU builds (aka "unity" or "jumbo" builds) are a widely used technique for speeding up compilation. 
https://en.wikipedia.org/wiki/Single_compilation_unit

In a vanilla build one cpp file is fed to the compiler each time (one translation unit). In suboptimal setups, each cpp can end up including a large chain of header files, and might easily result in tens of thousands of lines of code to compile, for a cpp that may only be small.

If we consider that the majority of time is spent compiling headers that have a "once" directive (or include guards) then we can speed up compilation dramatically by compiling several cpps in the same translation unit. We can do this by supplying a master cpp file (called a "scu" file here) which is simply a list of the multiple cpp files we wish to include in the translation unit.

Thus for instance:
`scu_drivers_gles2.gen.cpp` contains:
```
#include "../rasterizer_canvas_base_gles2.cpp"
#include "../rasterizer_canvas_gles2.cpp"
#include "../rasterizer_gles2.cpp"
#include "../rasterizer_scene_gles2.cpp"
#include "../rasterizer_storage_gles2.cpp"
#include "../shader_compiler_gles2.cpp"
#include "../shader_gles2.cpp"
```
Any headers are compiled once and shared between all the cpps in the scu file.

This typically greatly speeds up compilation.

In return there are several downsides:
### SCU builds rely on not polluting the global namespace
If variables / functions within the cpps in the translation unit are duplicates, you will get build conflicts. These must be resolved (or better avoided in the first place), or else excluded from the accelerated build (and use old style compilation).

In general, polluting the global namespace is now regarded as a faux pas in modern programming, so this helps, but you will still find old school code that abuses global namespace, and relies on single cpp as a primitive form of scoping. Many of our third party libraries are not suitable without modification.

### Touching any file within a scu translation unit will cause the whole translation unit to recompile
Vanilla builds touching a single cpp are often cheaper. But generally touching a header (which is the rate limiting step) will be _much_ cheaper in SCU builds.
</details>

## Description
<details>

The PR contains 3 elements:

1) New functionality in `scu_builders.py` which is called from `SConstruct` (if the `use_scu=yes` Scons option is set).

This code builds all the necessary `scu_*.gen.cpp` files in corresponding `scu` subfolders that are necessary for the build to work. `scu_builders.py` should rarely need modifying, and only is concerned with keeping the scu build working, the regular builds are unaffected.

2) `SCsub` files _only_ for those modules we want to accelerate (mostly Godot core) are slightly modified to use the `add_source_files_scu()` function instead of `add_source_files()`. These should be for folders that have a corresponding entry in `scu_builders.py`.

`add_source_files_scu()` is usually used to add the main folder for the `SCsub`, using something like `*.cpp` for the file list. It returns either `True` (if the SCU build is active) or `False` if a regular build is taking place, in which case `add_source_files_scu()` passes the arguments directly through to the regular `add_source_files()`.

The return value allows the possibility of combining several folders into the same scu translation unit (which is more efficient). If this is desired it should be done by adding the extra folders in the master list in `scu_builders.py`.

3) Modification of a limited amount of the Godot source code where there are naming conflicts that would occur when compiling files in the same translation unit. This is usually due to conflicts within global namespace - static functions defined only within cpp files are often culprits.

Alternatively, these files can be excluded from the scu build in the master list in `scu_builders.py`, which will avoid the need for changing any source code. However this will result in slower SCU builds.
</details>

## Instructions
<details>
<summary>Instructions for users (contributors)</summary>

### Instructions for users (contributors)

1) Add `use_scu=yes` to your Scons args.
2) Make sure to compile with a non-scu (regular) build _prior_ to submitting PRs. This is because SCU builds by nature include headers from earlier cpps in the translation unit, therefore won't catch all the includes you will need in a regular build. The CI will catch these errors but it will usually be faster to catch them on a local build on your machine.
That's it. :smiley: 

`use_scu=yes` automatically runs `scu_builders.py` to generate the `scu` folders and `scu` generated files for different modules. It is rerun each time Scons is invoked, because if you are adding or removing files from the monitored folders the scu files must be regenerated (it's quite fast).
</details>

<details>
<summary>Instructions for regular build maintainers / contributors adding new folders</summary>

### Instructions for regular build maintainers / contributors adding new folders

1) For most SCsub files (outside core especially) continue to use `add_source_files()` as usual.
2) For the core folders that are already converted, try to keep the `add_source_files_scu()` versions for the main folders.

If you need to add new folders for compilation, either add an `SConscript` for the new folder `SCsub` file, or use `add_source_files()` as you normally would (but outside any `if` clause for the `add_source_files_scu()` command).
</details>

<details>
<summary>Instructions for SCU build maintenance</summary>

### Instructions for SCU build maintenance

1) Periodically a SCU build maintainer (presumably myself at least to start with) will make any small modifications to ensure the SCU build is optimizing as many folders as possible.
2) Occasionally PRs are expected to break the SCU build. This will be things like naming conflicts. This won't affect regular builds, but there will be occasional fixup PRs to either:
* Correct the naming conflict in the source code
* Exclude the files concerned from the SCU build (in `scu_builders.py`, these files can be marked as exceptions in the master list)

The master list contains entries like the following:
```
process_folder(["scene/3d"], ["baked_lightmap"], 2, "cpp")
```
The arguments are:
1) List of folders to be included in the translation unit. The first folder will be the folder that a `scu` subfolder is added to, and will determine the filename of the scu files. In most cases only a single folder will be in the list. Any more entries must be subfolders, relative to the first.
2) List of _exceptions_, filenames that will not be included in the scu translation unit. They will be compiled as separate cpps. This will prevent the speedup, but easily allows dealing with files that contain naming conflicts.
3) Number of translation units to employ. This will usually be 1, but can be increased to separate into groups, which will decrease the memory use by compiler processes.
4) Extension. Usually `cpp`, but can be `c` for e.g. third party libraries.

Only the first argument is required, the rest have defaults, and are rarely used.

It is highly likely I would maintain the SCU build to start with, but it is fairly simple to do, so any maintainer with an interest can keep it running well.
</details>

## Limitations
DEV builds only currently, because the compile instances use a lot more memory. This is ok in debug builds, but in optimized builds clang at least can use more than 2Gb so could run out of memory depending on the PC.

## Some benchmarks
<details>

I originally converted a lot more of the engine, but this version mainly involves just Godot core for simplicity. As such, full rebuilds aren't as fast as they can be, but touching important headers results in quite a bit faster compilation.

#### Full rebuild
Normal build 7mins 53
SCU build 3mins 41

#### Touching `node.h`
Normal build 4mins 10
SCU build 1min 42

With a fuller SCU conversion I had full rebuild down to 3 mins 3 (or 1 min 48 with `custom.py`), and touching `node.h` down to 1 min 30. However I'm not sure at this stage the maintenance cost was worth it as these were mostly thirdparty changes.
</details>

## Notes
* I'm not an expert in python by a long shot (in fact I had to look up `hello_world.py` just the other day :grin: ) so would probably need some good checking / fixing up of any python / Scons script.

#### ToDo
* Test on other OS (only tested on linux, so path slashes might need different on windows?). However this can be done in a followup PR, even just working on linux would be good to start, and I don't have access to windows machines.

### CODE REVIEW

**Comment by lmurray** [comment]
I have worked on several projects over the years that had unity builds but ultimately they were all removed as the penalties ended up being more major than they first appeared. Adding this to Godot is most likely going to introduce maintenance effort that exceeds the amount of time saved on build times. Chromium for example had multiple breakages per week related to unity builds that required maintainers to make corrective action. There are generally better ways to reduce build times such as switching away from SCons, restructuring code to reduce the amount of headers needed to be loaded per compilation unit, deprecating support for slow compilers (Clang supports most platforms and is relatively fast), or switching to cloud compilation systems.

**Comment by Calinou** [comment]
> There are generally better ways to reduce build times such as switching away from SCons

There is an [ongoing effort to switch to Meson](https://github.com/godotengine/godot-proposals/issues/1797), but it's a long way from being merged.

> deprecating support for slow compilers (Clang supports most platforms and is relatively fast),

Even with a fully optimized buildsystem setup (Linux + Clang + mold + SCons run via Pyston), I find incremental build times slower than I'd like, especially on `master`.

> switching to cloud compilation systems.

Most contributors don't have access to one or money for pay for one :slightly_smiling_face:

**Comment by lmurray** [comment]
The most major penalty with unity is that every single symbol in the global namespace needs to be unique in the entire project (or at least within the size of a unity translation unit) across all platforms and build configurations. This may require adding even more tests to automated PR workflows which will increase the time needed for PRs to be tested.

**Comment by lawnjelly** [comment]
@lmurray you clearly have had bad experiences, and strong opinions, but I think you are misunderstanding. This PR is not swapping Godot over to using unity builds, or to have it as part of CI. It's just an optional extra tool for engine developers (who either understand how they work or are prepared to learn to get the advantages).

> I have worked on several projects over the years that had unity builds but ultimately they were all removed as the penalties ended up being more major than they first appeared. Adding this to Godot is most likely going to introduce maintenance effort that exceeds the amount of time saved on build times. Chromium for example had multiple breakages per week related to unity builds that required maintainers to make corrective action.

Relying totally on unity builds to some extent requires all the devs involved to understand how they work (and some basics of how compilers work). As you observe, this is not always practical when you mix up people who don't understand this. To include in CI for example, you have to include both unity and regular builds, something that compiles in unity build may not compile in regular build and vice versa, this is a fact of life. To roll out as was done in Chromium requires that commitment and the knowledge that will be regular breakages that need fixing - maybe that trade off made sense for them at the time, but they later changed tack.

> There are generally better ways to reduce build times such as switching away from SCons, restructuring code to reduce the amount of headers needed to be loaded per compilation unit, deprecating support for slow compilers (Clang supports most platforms and is relatively fast), or switching to cloud compilation systems.

As a project I think we are aware of these. Generally my preference is to start by minimizing the header dependency chains, forward declaration etc, and there has been some efforts towards this (see e.g. PRs @Calinou posted). Unfortunately in Godot, the dependency chains are ingrained and may be difficult to remove, both in terms of coding and politically. There is a also a lot of inertia and the need to justify refactoring (if it isn't broke, why fix it?). Also consider that many of the contributors are not familiar with how and when to reduce dependencies - we have a mixture of experienced and less experienced contributors, so we have a lot of new code coming in all the time that brings in even more "header hell". That's not to say the battle is not worth fighting.

> The most major penalty with unity is that every single symbol in the global namespace (which includes macros and other preprocessor directives) needs to be unique in the entire project (or at least within the size of a unity translation unit) across all platforms and build configurations.

Yes, I tried to be very clear about this, this is why I've kept the PR to translation units (scu files) that don't currently seem to suffer from global namespace conflicts. Within the Godot core, we tend for the most part to be good about global namespace and mostly use classes for scope. We keep on top of this in terms of coding standards in review, with a few outliers sneaking by (see the modifications in the PR for a few global functions defined in cpps).

As I said I originally converted a lot of the thirdparty code too, but decided overall that the trade off might not be worth it, and just aimed to cover the low hanging fruit with the most bang for the buck (Godot core).

> What gives you the impression that use of the global namespace is a faux pas these days? In many of the large C++ projects that I've worked on use of the global namespace is still extremely commonly used as it doesn't make sense for single-use functions to be a part of a larger group of functions that must be explicitly named.

We'll have to agree to disagree on that one. I very much got the impression that the trend in programming has been away from using global namespace as much as possible to prevent conflicts. This is particularly important for things like libraries which have to exist in other ecosystems. There are of course trade offs between scoping and ease of use.

**Comment by lmurray** [comment]
As long as all maintainers are aware that unity builds come with additional maintenance effort and are not always helpful then I'll leave it to your own judgement as to whether or not it makes sense for Godot to include them as an option. I do admit that my experience is from commercial projects that could easily afford throwing more hardware at the problem which may not be appropriate for a wide community project that needs to be buildable on less controllable hardware.

**Comment by eli-schwartz** [comment]
> There is an [ongoing effort to switch to Meson](https://github.com/godotengine/godot-proposals/issues/1797), but it's a long way from being merged.

Incidentally, if/when that ever gets merged, people who want unity builds will get them for free. Meson has a core option to produce unity builds out of the box (and an option that controls the block size, so it isn't all or nothing and people can choose exactly how many files they would like to unity-build together, and determine their preferred tradeoff in memory, incremental rebuilds, etc.)

**Comment by lawnjelly** [comment]
> Meson has a core option to produce unity builds out of the box
https://mesonbuild.com/Unity-builds.html

Although from the look of it, they haven't really addressed naming collisions (and just refer to them as bugs). This is where having some manual control can be handy, with the PR here we can exclude certain problematic files / folders etc, and only require preventing collisions within a translation unit that is well specified (usually a folder).

**Comment by eli-schwartz** [comment]
Right, source compatibility with unity builds is not really a solvable problem at the buildsystem level.

What you can do, though, is compile those files with `override_options: ['unity=off']`. That's work you need to put into unity builds -- but it's a lot less work than doing that *and* implementing creation of unity files / source collection, *and* implementing chunking. So it's a lot easier for users to test, while simultaneously requiring extremely little commitment from the project as a whole. (Maintaining a unity attribute knob on per-folder internal object libraries is an easier sell than maintaining the internal plumbing for unity builds.

**Comment by lawnjelly** [comment]
> There's no urge, but now that the `master` version was merged, you could update this one to follow a similar structure.

Yes, will do, and include the bug fixes for compatibility. :+1:

**Comment by lawnjelly** [comment]
Closing in favour of #78113 which contains refinements from the master version, and also accelerates some third party.

**Pull request closed without merging**
