### PR TITLE
some doc for directory

### PR DESCRIPTION
**Pull request by AlexHolly**

### CODE REVIEW

**Comment by AlexHolly** [comment]
I get a "Doc exists. Merging.." no errors on ```./godot.x11.tools.64 -doctool ../doc/base/classes.xml
```. Do you mean the example code? I did copy it in gd editor and it looked fine.

I have problems selecting doc text in the godot doc viewer. I can select the upper half but not the lower. I have to scroll down first, is this a known issue?

**Comment by akien-mga** [comment]
> I get a "Doc exists. Merging.." no errors on ./godot.x11.tools.64 -doctool ../doc/base/classes.xml . Do you mean the example code? I did copy it in gd editor and it looked fine.

Then check the ``git diff``, it should show you that it reformatted some stuff you added. No need to commit those changes though, it will be done next time someone regenerates the template to add stuff.

> I have problems selecting doc text in the godot doc viewer. I can select the upper half but not the lower. I have to scroll down first, is this a known issue?

Could be worth opening a bug report yes.

**Comment by AlexHolly** [comment]
Okay now I see.

Another question. Why is Dictionary.parse_json( String json ) showing int as return value and not Error
see https://github.com/godotengine/godot/blob/199a29b353748245e9589d3ef38877613eef0ede/core/dictionary.cpp line 198 is the classes.xml not generated from the source code?

**Comment by akien-mga** [comment]
> Why is Dictionary.parse_json( String json ) showing int as return value and not Error
see https://github.com/godotengine/godot/blob/199a29b353748245e9589d3ef38877613eef0ede/core/dictionary.cpp line 198 is the classes.xml not generated from the source code?

It's generated from the source code, but not directly from the C++ header. The definitions used to generate the docs (and bind to GDScript) use custom macros such as ``BIND_METHOD`` which are usually in the same cpp file. For Dictionary though, as it's a core variant type, it is handled a bit differently by this line: https://github.com/godotengine/godot/blob/c247f5ad61f2575c321fb8117ed4212611e8cdf4/core/variant_call.cpp#L1430
And here it indeed defines ``INT`` as return type. It could be a typo, or that ``ERROR`` would not be a valid VariantType, I'm not sure.

**Pull request merged**
