### PR TITLE
Fix for the sprite display position jumps when placed at subpixel locations and moving the camera

### LINKED ISSUE #35606: 2D Sprite "jittering", very noticeable when using camera smoothing
**Godot version:**
3.1.2 stable, GitHub master (3.2), Vulkan branch (4.0)

**OS/device including version:**
Windows 10 x64 v1909

**Issue description:**
Pretty much as soon as I made my test level larger than a single screen, I noticed something was off. After a bit of testing, I've found out what it is. It seems like any time the camera moves, there is some sort of inconsistency in the positions sprites are being rendered at, causing them to "jitter" back and forth by one pixel even though the camera is only moving in one direction.

Example gifs showing the issue:
A5aCVeO
EhPwu5N

How noticeable it is depends on circumstances. Generally, from what I've found, it's most noticeable if you have camera smoothing turned on and the smoothing speed set to a very low value, but the problem isn't related to the camera smoothing. It's also present with camera smoothing turned off, just harder to notice.

In case it was a bug that had already been fixed, I tried compiling Godot myself from both the master (presumably what will become 3.2) and vulkan (4.0?) branches to try them out, but unfortunately the problem still seems to be present in both of those. It looks a bit different in the Vulkan branch, due to what I assume is some sort of smoothing/blur filter being applied (there may be a way to turn that off, but I couldn't find it) to the background, but it is definitely still there.

**Steps to reproduce:**

1. Start minimal reproduction project
2. Run far enough to the right that the camera starts scrolling and stop.
3. Watch the vertical lines of the background brick wall or the ground near the player to see the sprite jittering back and forth by one pixel until the camera fully stops

**Minimal reproduction project:**
[godot-jitter-repro-project.zip](https://github.com/godotengine/godot/files/4115122/godot-jitter-repro-project.zip)

### LINKED ISSUE #41491: Sprites with subpixel world positions are displayed with unexpected and uneven displacements
I tried finding this issue reported but I've come empty handed.

**Godot version:**

3.2.2 official build.

**OS/device including version:**

Windows, happens both with GLES2 and GLES3.

**Issue description:**

Creating a small test level I dragged many (parallax) map objects together without caring about perfect positioning of anything, so about all of them ended up in non integer (X, Y) positions.

When moving the camera the elements display at slightly unexpected positions, separating ones from the others even though all of them have equal parallax parameters, thus destroying the illusion of cohesion of the elements. If I erase the subpixel amounts of the coordinates everything displays as expected.

Further tests showed this behavior is not limited to parallax elements but is a more general issue that happens with regular 2D sprites too. If sprites have non integer positions the final display positions get jumpy, like if the final position is sometimes rounded up and sometimes down, depending on the relative position to the camera.

I think it's important to remark that the Pixel Snap option does nothing to prevent this behavior.

**Steps to reproduce:**

Draw a bunch of 2D sprites at non integer coordinates and scroll slowly to experience the issue.

**Minimal reproduction project:**

I'm including a small project with two cameras in split screen that slowly move in circles over a bunch of sprites. At the left the sprites have subpixel positions and experience this issue. At the right the sprites are at integer positions and all can be seem displaying as a solid block. I think it's reasonable to expect the left camera to display the static sprites always at the same positions relative to each other.

GIF 24-Aug-20 16-00-08

[spritepositions.zip](https://github.com/godotengine/godot/files/5118245/spritepositions.zip)

### PR DESCRIPTION
**Pull request by m6502**
Fixes the 2D canvas display positions jumping pseudo randomly when the are located at fractional coordinates and the camera changes location. Fixes #41491, fixes #35606 etc. Godot 4.0 branch.

### CODE REVIEW

**Comment by m6502** [comment]
Improved the fix for 4.0 too. More info at the 3.2 pull request: #41535

**Comment by m6502** [comment]
What is required to get a review of this pull request as to unblock it so it gets merged?

**Comment by akien-mga** [comment]
This would need to be rebased to squash commits into one and use a meaningful commit message, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind.

**Comment by akien-mga** [comment]
Superseded by #43194 (4.0) and #43554 (3.2.4).

**Pull request closed without merging**
