### PR TITLE
Add automatic and linear bezier presets to Animation Bezier Editor

### PR DESCRIPTION
**Pull request by Razoric480**
Implements godotengine/godot-proposals#3561 

- Adds the automatic bezier preset, which makes the bezier handles Balanced but makes them point along the tangent between the previous and the next keyframes
- Changes the balanced bezier preset, which makes the bezier handles flattened horizontally
- Adds the linear bezier preset, which makes the bezier handles of length Zero and prevents them from being selected in the bezier editor
image

### CODE REVIEW

**Comment by TokageItLab** [comment]
I think there is issue that when the handle mode is Linear, moving a key cancels the Linear mode. There is no need to show the handles when Linear is selected, and Linear should only be implicitly released when you select something other than Linear in the Bezier menu.

This is the ideal behavior based on After Effects.

- When Free is selected, the Bezier type is changed to Free, and nothing happens to the handle.
- When Balanced is selected, the Bezier type is changed to Balanced, and the behavior of the Extend Handle (Balanced) of the [image](https://github.com/godotengine/godot-proposals/issues/3141#issuecomment-922247544) (godot-proposals#3141) is applied.
- When Linear is selected, it changes the Bezier type to Linear and sets the length of the handle to 0. It is not just Bezier preset, so while the Bezier Type is Linear, the user is prohibited from manipulating the handle.
- When Automatic is selected, it changes the Bezier type to Balanced and performs the Auto Tangent (Balanced) behavior of the image.

I don't know why Mirrored mode is gone, but if you want to keep it, just add the above replacing Balanced with Mirrored.

I think it would be ideal to have a context menu like below.
```
----
- Free [Change Key Type]
- Balanced [Change Key Type & Make Handle Horizontal]
- Mirrored [Change Key Type & Make Handle Horizontal]
- Linear [Change Key Type & Make Handle Zero Length]
----
- Automatic (Balanced) [Change Key Type & Make Handle Auto Tangent]
- Automatic (Mirrored) [Change Key Type & Make Handle Auto Tangent]
----
```

**Comment by Razoric480** [comment]
@TokageItLab 
I'm not against making those changes, though I would like it if elaborated on why it'd be ideal, besides that it's how After Effects did it. I can argue the same for Autodesk Maya, for instance, which continues to give access to the handles in linear mode.

As for mirrored, it went away in #53298

**Comment by TokageItLab** [comment]
@Razoric480 In general, I consider the animation features that come with 3D software to be an added bonus. It is supposed to work with IK and other animation software.

As for linear mode, the obvious problem is that when you move a key that is in linear mode, it is no longer linear.

**Comment by Razoric480** [comment]
Fair points. Thank you for elaborating.

**Comment by TokageItLab** [comment]
In addition, Horizontal is similar to Ease, and it is easy to make Cubic or Quad Ease-like adjustments when you move the length of the handle without moving its angle.

**Comment by Razoric480** [comment]
Should be good to go with the latest update now.

**Comment by reduz** [comment]
My feeling is that these things should not be part of the animation, but editor related. Its OK the key contains a hint on the type of mode but it feels to me that this should only be for the editor, since at the end the animation should only bother about the final value.

**Comment by TokageItLab** [comment]
@reduz Is that a problem that can be solved with `#ifdef`?

**Comment by Razoric480** [comment]
Superseded by #64647

**Pull request closed without merging**
