### PR TITLE
Fix multiselect change property

### PR DESCRIPTION
**Pull request by AlexHolly**
Fixes Point 2 in https://github.com/godotengine/godot/issues/21104

@qarmin Can you test it?

### CODE REVIEW

**Comment by qarmin** [comment]
It works great!
https://streamable.com/l8f1f

**Comment by AlexHolly** [comment]
What about Point 1 with deleting nodes is it still present?

**Comment by groud** [comment]
The PR looks good to me. It needs a rebase, and I would make "" a default value of the property_changed function (so that it does not need to be copy-pasted for all function call)

Also, I wonder if _property_changed_update_all and _multiple_properties_changed need this argument too.

**Comment by reduz** [comment]
I changed my mind about this, I couldn't implement it better. This has some bugs though, which I will try to figure out after merging.

**Pull request merged**
