### PR TITLE
Fix opening URLS with special characters in macOS

### PR DESCRIPTION
**Pull request by danielzting**
Fixes issue #39971

### CODE REVIEW

**Comment by bruvzg** [comment]
This will reintroduce issue with opening folders/files with spaces (and probably other special chars) in name, see #13422.

**Comment by DanielZTing** [comment]
Maybe I should only do this for strings in URL format?

**Comment by bruvzg** [comment]
> Maybe I should only do this for strings in URL format?

Probably, skip escaping if it starts with "scheme://" or something like this.

**Comment by naithar** [comment]
A hashtag (`#`) could probably just be added to character set that is used for percent encoding, like so:
```objc
NSMutableCharacterSet *godotURLCharacterSet = [[NSCharacterSet URLFragmentAllowedCharacterSet] mutableCopy];
[godotURLCharacterSet addCharactersInString:@"#"];
```

**Comment by DanielZTing** [comment]
Thank you all for your helpful suggestions. I decided to skip escaping only if the string starts with `https://`. According to my testing this works with filenames and URLS with special characters now. And you can't have a slash in a macOS filename anyways, so hopefully this shouldn't break things. As per the contributing guidelines I've put everything in one commit.

**Comment by bruvzg** [comment]
> only if the string starts with https://

It's better to extend it at least to: `http`, `ftp`, `mailto` (and maybe other popular schemes). Or to `{anything}://`, if it's  follows URL format, we can assume it is properly escaped.

**Comment by DanielZTing** [comment]
That would be a good idea. But `mailto` only uses the colon and not the slash, right? Would only checking for `:` work? Godot forbids creating a file/folder with a colon in the name anyways and colons are a semi-reserved character in the macOS filesystem. So I don't think that would break anything.

**Comment by bruvzg** [comment]
Or maybe do it in opposit way, escape only if it starts with the `file://` or no scheme? Something like

```obj-c
	NSURL *uri = [[NSURL alloc] initWithString:[NSString stringWithUTF8String:p_uri.utf8().get_data()]];
	if (!uri || !uri.scheme || [uri.scheme isEqual:@"file"]) {
		uri = [[NSURL alloc] initWithString:[[NSString stringWithUTF8String:p_uri.utf8().get_data()] stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLFragmentAllowedCharacterSet]]];
	}
	[[NSWorkspace sharedWorkspace] openURL:uri];
```

**Comment by DanielZTing** [comment]
Thanks for the suggestion. That does seem like the most surefire way.

**Comment by akien-mga** [comment]
Changes seem fine, but:
- PRs should be make against the `master` branch, which is where Godot development happens. Relevant changes like this one can then be cherry-picked to stable branches (like `3.2`) by release managers.
- The two commits should be squashed into one, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

**Comment by DanielZTing** [comment]
My apologies! I am new to the Git workflow with open source. The problem is that the `master` branch won't run on my main development machine; Godot says something about missing Vulkan drivers (UPDATE: I tried recompiling the `master` branch so I could get the specific error message, now it won't compile at all—apparently `main/default_controller_mappings.gen.cpp` can't find its `main/default_controller_mappings.h`). But I think what I should have done is cherry-picked my commit onto `master` and then after testing on another computer, make a PR with my `master` branch (is that right?).

Anyways, Github only lets me change the "base" branch and not the "compare" branch. Should I delete this PR and make a new one? Thanks for your patience BTW.

**Comment by akien-mga** [comment]
You need to install the Vulkan SDK for macOS to build the `master` branch: https://www.lunarg.com/vulkan-sdk/

And when switching between branches in the same Git clone, you should clean build objects as they're not compatible (especially `.gen.{cpp,h}` files. See https://docs.godotengine.org/en/latest/development/compiling/introduction_to_the_buildsystem.html#cleaning-generated-files

**Comment by DanielZTing** [comment]
Welp, I feel incredibly dumb now, doing a full clean fixed it. I'll open another PR with the correct branch.

**Pull request closed without merging**
