### PR TITLE
Fix multi-line string highlighting with single quotes.

### PR DESCRIPTION
**Pull request by HolonProduction**

### CODE REVIEW

**Comment by MewPurPur** [comment]
Could you show what this solves?

**Comment by HolonProduction** [comment]
```
var a = ''' 'hello world '''
```
In the above example the hello world will not have the string color. This is because the highlighter thinks that the single quote in front of it terminates the string because it is not aware of multiline strings that bginn with three single quotes.

**Review by akien-mga — APPROVED** [review]

**Comment by dalexeev** [comment]
> Should I close this PR then?

No, as this PR fixes some bug. I just noticed the fact.

**Comment by YuriSizov** [comment]
Let's merge it then to address the issue. Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
