### PR TITLE
Implemented local shader arrays

### PR DESCRIPTION
**Pull request by Chaosus**
Arrays are missed as described in https://github.com/godotengine/godot/issues/10751. This PR is partly fixing it by implementing arrays support inside functions. 

I do not touch the uniform arrays since they are required to change the visual server (and now its under heavy development by @reduz). But the provided feature is also good - for example its allows easy implement the Voronoi noise on https://thebookofshaders.com/12/

image

So about tech details..

The arrays can be any type(except sampler) and must have at least 1 element.

image

The accessing of the array using constant integer instruction. I've added static guard code to prevent user entering invalid indexes:

image

 But If you pass an invalid index indirectly (by calling function inside or using variable) the rendering pipeline(not engine) will crash(I dont found a good way to solve this problem - maybe new render_mode is required to prevent this - and the shader code will suffering by using "if" statements - I prefer leave this untouched for now

If you need to get the size of the array - it provides the length function.

image

### CODE REVIEW

**Comment by Chaosus** [comment]
Ok, feel free to merge @akien-mga, all warnings are eliminated. The only missing feature for local arrays is ability to pass them into functions - I temporary disable this feature and added warning stab since its pretty boring to implement for me right now.. maybe later

**Comment by Chaosus** [comment]
@clayjohn Can you check and approve this please ?

**Review by clayjohn — APPROVED** [review]
Looks good to me so far. I don't have a lot of knowledge about the shader compiler stuff, but from what I can tell it looks fine. I tested out this branch pretty extensively and it seems to work great. 

A few notes for documentation:
- No multidimensional arrays
- No array uniforms
- constants cant be arrays
- cant be initialized using array constructor syntax (e.g. float[5](1.0, 1.0, 1.0, 1.0, 1.0))
- cant be used as parameters in functions (yet)
- shader crashes if you read outside array length

**Comment by Chaosus** [comment]
Thanks @clayjohn ! Some notes quotes about:

> No multidimensional arrays

They are not supported in GLES3 - only GL4 feature set can support them - so they cannot be implemented (until Vulkan is come)

> No array uniforms

Yeah, as mentioned above - I dont want to interrupt great work of @reduz

> cant be initialized using array constructor syntax (e.g. float[5](1.0, 1.0, 1.0, 1.0, 1.0))

It's a bit a syntax sugar - as far as I can see the GLSL does not have this feature. Can be implemented later..

> constants cant be arrays

Ah, yeah, I miss it.. 

> shader crashes if you read outside array length

Yeah, its not simple to fix problem - if simply push internal "if" instruction to check array bounds the performance will be greatly suffering

**Comment by clayjohn** [comment]
@Chaosus I wasn't being critical, those are notes for when we document the new feature. :) They are just important things that users will need to be aware of. 

Take a look at https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Array_constructors it describes the default array constructor.

**Comment by Chaosus** [comment]
Of course, I just express my thoughts..
Damn, true, they also have a constructor..

**Comment by Chaosus** [comment]
> I wasn't being critical, those are notes for when we document the new feature. :) 

@clayjohn Nvm.. sorry sometimes things are slip away from my mind :)

**Comment by Calinou** [comment]
> Yeah, its not simple to fix problem - if simply push internal "if" instruction to check array bounds the performance will be greatly suffering

Maybe this could be done in editor/debug builds only?

**Comment by Chaosus** [comment]
Probably, someone could ask @reduz can this feature be added to 3.2 ? I dont want to work on the PR if its state is undefined

**Comment by akien-mga** [comment]
As discussed with @reduz, this should be fine for 3.2, and will likely need to be partly reimplemented for Vulkan. Testing is needed on a wide range of hardware to make sure that those arrays don't run into hardware/driver limitations.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
