### PR TITLE
Added binding for Autotile Center

### PR DESCRIPTION
**Pull request by TrevorPeyton**
When adding autotile bitmasks in script, you have to include BIND_CENTER to allow autotiling to work. 

The binding is currently missing, this adds it.

### CODE REVIEW

**Comment by TrevorPeyton** [comment]
Also, should BIND_CENTER automatically get added if the autotile bit mask is explicitly modified and is not set to 0?

If this is modified through script then it seems a bit unnecessary to have to pass that in as a flag for every bit mask. The same goes for the tileset editor. It may be a bit more clear if the center bit flag is always automatically added since it's needed _unless_ there is no bit mask for that sub tile.

**Comment by akien-mga** [comment]
Looks good. Could you add the matching documentation in https://github.com/godotengine/godot/blob/master/doc/classes/TileSet.xml#L751 ?

You can generate it automatically by calling `bin/your.godot.bin --doctool .` (the final dot is important). Then you can use `git commit --amend` to include the updated docs in the existing commit, and `git push --force` to update the PR.

**Comment by akien-mga** [comment]
> Looks good. Could you add the matching documentation in https://github.com/godotengine/godot/blob/master/doc/classes/TileSet.xml#L751 ?

Nevermind, I'll do it together with other unrelated changes to the docs.

**Comment by akien-mga** [comment]
Thanks!

**Comment by TrevorPeyton** [comment]
@akien-mga Thanks, I wasn't aware of the docs, I'll know for next time!

**Pull request merged**
