### PR TITLE
Fix Node2D::global_position to have Vector2 type

### PR DESCRIPTION
**Pull request by endragor**

### CODE REVIEW

**Comment by aaronfranke** [comment]
I'm surprised this bug managed to exist in the first place. Surely anyone trying to use `Node2D::global_position` would immediately notice? :+1: for the fix.

**Comment by rosshadden** [comment]
@aaronfranke I immediately noticed ;) I searched the codebase for `get_global_position` but every occurrence I saw was Vector2 or Point2. I guess I didn't look thoroughly enough, because I ended up with the conclusion it was godot-nim's fault and bitched to endragor.

**Comment by vnen** [comment]
> I'm surprised this bug managed to exist in the first place. Surely anyone trying to use Node2D::global_position would immediately notice?

I don't think so. The property binding is pretty much only for documentation purposes, the property access would still return a Vector2 since that's what the getter returns. Of course, people using GDNative and language bindings rely on this metadata so it fails fast for them.

It would be good if the macro could have some static type checking, but I don't know if it's possible.

**Comment by akien-mga** [comment]
While at it, it would have been good to fix `global_scale` :)

**Comment by akien-mga** [comment]
> While at it, it would have been good to fix `global_scale` :)

Done with 8852ca145, should also be cherry-picked @hpvb.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
