### PR TITLE
Add `item_hovered` signal to `ItemList`

### PR DESCRIPTION
**Pull request by kolunmi**
Hello! This pr adds an `item_hovered` signal to the `ItemList` node. I believe this will be useful in many situations. Thank you!

### CODE REVIEW

**Comment by MewPurPur** [comment]
This is already implemented for 4.1

**Comment by kleonc** [comment]
> This is already implemented in 4.1

@MewPurPur I don't think it is. Such signal was not added in #74739 (or after).

**Comment by KoBeWi** [comment]
The signal clearly does not exist, based on this PR that added documentation without any problem. Unless it's named differently.

**Comment by MewPurPur** [comment]
Okay, fair, I got it mixed up with the theming, so I marked the comment as outdated already. When I wrote it checks hadn't ran yet

**Pull request closed without merging**
