### PR TITLE
Add plugin to edit GDNativeLibrary

### LINKED ISSUE #14618: Cannot set library for GDNativeLibrary
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 compliled with  b110813  on Windows 7

**Issue description:**

Here is no way to set the dynamic library for any platform.
The door to GDNative is totally closed :(

**Steps to reproduce:**
* Create a GDNativeLibrary resource in the inspector
* The inspector lost the platform section
image

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by Geequlim**
Rename GDNativeLibraryEditor to GDNativeLibrarySingletonEditor
Fix #14618

### CODE REVIEW

**Comment by karroffel** [comment]
Wow, this looks cool! It seems great for a "quick" library creation and quick editing, but it does take away some flexibility.

I think a more flexible approach would be to have some presets (like you already made, for example OS + bits) to select from, but basically an entry is just a set of feature tags and an associated value. The same for the dependencies.

So maybe a way to add a new entry (entries are checked from top to bottom, the first match will be used) and set the tags for that entry. A way to move entries would be nice since order can matter. Then a way to set the value of an entry?

I really like the way it looks from the screenshot, I'll build and test it soon!

But yeah, a more "dynamic" approach would be better in the long run, but this seems to be really nice for usability already

**Comment by Geequlim** [comment]
@karroffel OK. I'm making it better.

**Comment by reduz** [comment]
Libraries are dependent on feature tags (which can include debug, or custom
tags entered by the user), not harcoded platform strings. If you can make
an UI where you add a library and check the relevant feature tags, it
should be good.

To get a list of feature tags, I recommend you check ProjectSettingsEditor,
which shows a dropdown list in the project settings for overrides.

**Comment by Geequlim** [comment]
@karroffel Changed lot by merging to tree into one and add a filter.


@reduz Still use the harcoded way as we just need tags for architectures here. There is not related api found to get the architecture lists for all of the platforms now.

**Comment by reduz** [comment]
@Geequlim yes there is, you get all architectures from the feature tags. In fact GDNativeLibrary only obeys feature tags now.

**Comment by Geequlim** [comment]
@reduz  I did went through the ProjectSettingsEditor and EditorExport. But I still can't find the way to get architectures features.

**Comment by karroffel** [comment]
@Geequlim you can't get the feature tags, you can only test if some tag is available or not. So a super brain dead UI for adding tags to an entry should be enough.

For some platforms some of the tags are known, but users can define their own tags at export time and there are no "fixed presets"

**Comment by Geequlim** [comment]
The entries can be customized now.

**Comment by karroffel** [comment]
Okay I tested this, it's good as a preset already. A few more things as there seems to be a bit of misunderstanding about how the feature tags are supposed to be used.

A GDNativeLibrary consists of a few settings (load once, prefix, singleton) as well as two list of entries.
Those entries are flat ordered lists of **feature tags** to a) a path to a file for the entry point and b) a list of paths to dependencies.

An entries key is a set of **feature tags**. Those tags can be set at export time but some are also baked into the Godot binary. All the feature tags are separated by `.`.

The entries are checked from top to bottom, if **all feature tags are supported** the entry will be used and the search will be stopped.

----

As an example, I could work on a game and have a compiled library that contains a stub network handler (I don't want to write test data to a production database for example).

So when I export the game for QA I set a new tag `QaBuild`.

If the list looks like this:
```
X11.64.QaBuild="custom_lib_with_stub_network.so"
X11.64="some_file.so"
X11.32="some_other_file.x86.so"
```
then the first entry will be used (assuming it's a 64 bit linux export).

If I want to export the game for a proper update to release to the players I would want to switch the real one back in, so I would just *not* define the "QaBuild" tag.

Without the QaBuild tag the first entry will not match, so the search continues and it would stop at `X11.64`.

-----------

I really like the way it looks and I think having a predefined list of common tags per-platform is really nice, I like it!

But as you can see, the platform is actually just another tag in the set of tags of an entry.

What I'm missing is to be able to move entries around (since order matters) and to be able to *modify existing tags*.

The predefined list is awesome and the platform-categories look really good, but for the sake of simplicity I'd say that having a flat list of "entries" would be enough. There could still be the same predefined entries, but without the strict platform separation and with a *clear view what the tags look like*. Currently you can't see the full feature tag set of an entry.

----

 On a side note, I'm not able to remove an entry and got errors:
```
ERROR: get_value: Couldn't find the given section/key and no default was given
   At: core/io/config_file.cpp:89.
```

**Comment by Geequlim** [comment]
@karroffel I hope this time it should work fine.

* Add reorder support for entries
* Only save entries with file selected

Rename entry is not supported but we can remove and add new one instead.

For `X11.64.QaBuild`, just add an entry with name `64.QaBuild` under the `Linux/X11` platform.

image

**Comment by karroffel** [comment]
@Geequlim That looks nice, will test it later!

**Comment by karroffel** [comment]
@Geequlim this works very nice, I like it!

Thank you for making this UI. Can you squash the commits and while you are at it, there are clang-format complaints on Travis.

If that's done I'll merge.

Thanks again! 🎉

**Comment by Geequlim** [comment]
@karroffel That done. You are welcome :)

**Pull request merged**
