### PR TITLE
Fix script list only showing their names regardless of display option

### LINKED ISSUE #45103: Script list only shows the script name regardless of option
**Godot version:**

3.2.4 beta 0a8cc0a565

**OS/device including version:**

not related

**Issue description:**

Script list only shows the script name even with `Parent Directory And Name` or `Full Path` option in editor settings.
it's regression from #44598

**Steps to reproduce:**
Change value of `Sort script by` at Editor Settings > Text Editor > Script List

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #45103.

### CODE REVIEW

**Comment by volzhs** [comment]
is still this part needed?
https://github.com/godotengine/godot/blob/4194447a2158e9022214b326f451f2890fa411a1/editor/plugins/script_editor_plugin.cpp#L1932-L1946

**Comment by YeldhamDev** [comment]
> is still this part needed?

As far as my tests go, yes. And I can't bring the new logic to that section of code either, as it fails to fix the original bug.

**Review by volzhs — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
