### PR TITLE
Fix invalid DEFVAL in SpatialEditorGizmo::add_unscaled_billboard

### LINKED ISSUE #19543: EditorSpatialGizmo.cs failed - Build project with C# script is impossible - regression
**Godot version:**
ea5512f

**OS/device including version:**
Windows10

**Issue description:**
Try attach c# script and build - you see the error.

**Minimal reproduction project:**
No need - its very simple to reproduce

### PR DESCRIPTION
**Pull request by akien-mga**
Likely added by mistake in #19487.
Should fix #19543.

### CODE REVIEW

**Comment by akien-mga** [comment]
@neikeq Since the Mono build is so sensitive to any binding mistake, we really need to improve the workflow in this regard, to either:
- get compilation errors when bindings are invalid
- or get clearer error messages at runtime

**Comment by neikeq** [comment]
> - get compilation errors when bindings are invalid

Not possible, bindings happen at runtime. However, I've planned for a long time to add a test for the ClassDB bindings. So ideally, if you made changes to the bindings, you run this test before opening a PR and it would report any anomalies. It's in my TODOs list.

> - or get clearer error messages at runtime

I will have to check if this is possible.

**Comment by akien-mga** [comment]
> However, I've planned for a long time to add a test for the ClassDB bindings. So ideally, if you made changes to the bindings, you run this test before opening a PR and it would report any anomalies. It's in my TODOs list.

That would be nice, we could have it run on the CI with the server/headless binary to catch those at build time.

**Comment by JFonS** [comment]
That would definitely be welcome. I try to double check the bindings every time I make a PR, but it seems I am not that good at it.

**Pull request merged**
