### PR TITLE
ThorVG: Update to 0.14.0

### LINKED ISSUE #91781: Godot crashes when importing a certain SVG icon with embedded PNG images
### Tested versions

Godot Engine v4.2.stable.official.46dc27791 also happens with mono version

### System information

Windows 11

### Issue description

Godot crashes when importing a certain SVG icon

### Steps to reproduce

Simply place this file somewhere in the project folder and return to the editor. Godot will attempt to import the file and crash.
SpikedBulletIcon

### Minimal reproduction project (MRP)

If you don’t want to create a minimal reproducible project (MRP) yourself, you can use mine.
[godot-crash.zip](https://github.com/godotengine/godot/files/15269030/godot-crash.zip)

### PR DESCRIPTION
**Pull request by capnm**
+ Fixes the v0.13.8 PR issue: https://github.com/thorvg/thorvg/issues/2468
+ See https://github.com/thorvg/thorvg/releases/tag/v0.14.0

I have successfully tested the PR under 64-bit Linux.

Fixes #91781

### CODE REVIEW

**Comment by capnm** [comment]
... and someone should check it on a 32-bit platform :smile_cat:

**Review by fire — APPROVED** [review]
I did not test. The update makes sense and looks good.

Checking:

`pre-release` upstream now.

**Review by akien-mga — APPROVED** [review]
The release is fully published upstream now with the same commit.

Tested that it compiles fine with mingw for Windows x86_32.

I'm a bit wary of jumping on a new feature branch right as it's released, but upstream is quick to solve regressions so it's worth giving it a go and it should hopefully be stable enough by the time we release 4.3.

**Comment by capnm** [comment]
A remarkable synergy between two open-source projects in their bug hunting endeavors :1st_place_medal:

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
