### PR TITLE
GDScript: Support `%` in shorthand for `get_node`

### LINKED ISSUE #4583: Allow accessing Scene Unique Nodes without quotes in GDScript
### Describe the project you are working on

An application for procedurally generating 2D maps.

### Describe the problem or limitation you are having in your project

Scene Unique Nodes require using quotes to access them in GDScript, which causes syntax highlighting to turn yellow instead of green in 3.x. I frequently use the green syntax highlighting color to quickly identify node references in scripts, but this does not work with the Scene Unique Nodes feature.

In 4.0 paths after the `$` sign are green even with quotes, but it would still be more convenient to not require typing quotes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Allow accessing Scene Unique Nodes without quotes.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Current:
```gdscript
$"%NodeName"
```

After:
```gdscript
$%NodeName
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, GDScript syntax cannot be modified by a script.

### Is there a reason why this should be core and not an add-on in the asset library?

This cannot be made as an addon.

### PR DESCRIPTION
**Pull request by vnen**
The `%` is used in scene unique nodes. Now `%` can also be used instead of `$` for the shorthand, besides being allowed generally anywhere in the path as the prefix for a node name.

This is the syntax in GDScript to use the feature introduced in #60298. 

Samples of the valid syntax:

```gdscript
var hey = $Child/Hey
var howdy = $Child/Hey/SubChild/Howdy

print(%Hey == hey)
print($%Hey == hey)
print(%"Hey" == hey)
print($"%Hey" == hey)
print($%"Hey" == hey)
print(%Hey/%Howdy == howdy)
print($%Hey/%Howdy == howdy)
print($"%Hey/%Howdy" == howdy)
```

A similar thing could be done for 3.x since it doesn't break compatibility.

Closes https://github.com/godotengine/godot-proposals/issues/4583

### CODE REVIEW

**Comment by Mickeon** [comment]
I don't know about allowing the lone **`%`**. It sounds nice and cool on paper, but I personally find `$%` to be more explanatory.

**Comment by fire-forge** [comment]
Awesome! This also closes https://github.com/godotengine/godot-proposals/issues/4583

**Comment by Mickeon** [comment]
Actually, my reasoning goes further than that. I would personally hold off the lone `%` operator as it does affect all of **GDScript2**. It's been fine for the `$` operator, as accessing Nodes is fairly common in Godot, but introducing another wholy lone operator that does around the same thing, but only works in a "Scene & Node" context may be excessively cramped.

That's also because, in GDScript, `%` is already used in two wholy different contexts:
- Modulus
- String formatting

Introducing a third, completely unrelated purpose for it, I find to really be too much.

And that's not even mentioning, should https://github.com/godotengine/godot-proposals/issues/4593 be implemented a certain way (and it really should, it'd be a massive usability improvement), autocompletion may display even if the context does not warrant it.

**Comment by vnen** [comment]
@Mickeon I don't think it's that much of a problem. This context is quite different from the others where `%` is used, it should be clear from the start that's a different thing. Completion should not be affected by this as it should only show nodes when `%` is used as a prefix operator.

If there's a lot of the demand I could still change it, but for what I've seen most people are okay with the syntax I implemented here.

**Comment by KoBeWi** [comment]
Could you maybe add better support for dropping node path?
godot windows tools 64_uZW6jIerMr
It should drop without quotes and `$`.

The relevant code is here:
https://github.com/godotengine/godot/blob/8a21f7231f0851aec4c06abee28a549b1f8083fd/editor/plugins/script_text_editor.cpp#L1592-L1617

**Comment by reduz** [comment]
@vnen This is awesome, you rock!

**Comment by vnen** [comment]
@KoBeWi update the code to improve the drag & drop. Not sure if this works well with instanced scenes, but it can be improved further in the future.

**Review by akien-mga — APPROVED** [review]

**Comment by zenvoid** [comment]
> It's been fine for the `$` operator, as accessing Nodes is fairly common in Godot, but introducing another wholy lone operator that does around the same thing, but only works in a "Scene & Node" context may be excessively cramped.
> 
> That's also because, in GDScript, `%` is already used in two wholy different contexts:
> 
> * Modulus
> * String formatting
> 
> Introducing a third, completely unrelated purpose for it, I find to really be too much.

I agree. While it shouldn't be a problem in practical terms, it's starting to look too much like Perl and I find it ugly. "Ugly" being completely subjective, other people seem to like it and that's fine. Not a big problem for me, I can live with it. Just trying to publicly manifest how much I hate this new syntax ;)

**Comment by SaranSundar** [comment]
I haven't been able to get this working in C#, is the syntax for % only in gd script?

**Pull request merged**
