### PR TITLE
Fix issue causing the textedit to move upward

### LINKED ISSUE #37190: TextEdit will move upward after input tens of lines on Android
**Godot version:**
3.2.1
**OS/device including version:**
Android 
**Issue description:**
after input tens of lines into the TextEdit, the rect_position of the TextEdit will move upward.
**Steps to reproduce:**
see the demo project

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/4360599/bug.zip)

### PR DESCRIPTION
**Pull request by m4gr3d**
Fix #37190

### CODE REVIEW

**Comment by m4gr3d** [comment]
@capnm Can you text this fix and see if it resolves your issues.

**Comment by m4gr3d** [comment]
@akien-mga Can you let me know when the other PRs are reverted from the `master` branch so I can provide a matching fix.

**Review by pouleyKetchoupp — APPROVED** [review]
Changes look good to me & I can confirm it works well in my test cases.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
