### PR TITLE
Added possibility to minimize GraphNodes

### PR DESCRIPTION
**Pull request by Chaosus**
Shrink off GraphNodes gives user possibility to making graph less messy when there are lot of them. And apply this to VisualScript/Shaders of course.
 
minimize2

The minimized state of the nodes supports undo/redo and correctly saving and restoring, the visual scripts/shaders created before this change should not be damaged - I checked it carefully. This minimization button is optional and disabled by default, to not corrupt the custom graph nodes of users.

### CODE REVIEW

**Comment by fire** [comment]
This seems like a jumping point for implementing reroute nodes. 

https://github.com/godotengine/godot/pull/22869

**Comment by fire** [comment]
One can take the reroute node and "minimize" it turning it into a point?

**Comment by Chaosus** [comment]
> One can take the reroute node and "minimize" it turning it into a point?

Well, the reroute node in the form is written that PR can be minimized as other standart nodes

**Comment by fire** [comment]
How difficult is it to add a shortcut so double clicking on the spline will add a reroute node?

**Comment by fire** [comment]
Does hovering over the minimized node give a tooltip?

**Comment by Chaosus** [comment]
> How difficult is it to add a shortcut so double clicking on the spline will add a reroute node?

Dont know, this requires research.

> Does hovering over the minimized node give a tooltip?

Currently no, by doing so we will need to add a button controls instead draw_textures directly.. Maybe after that PR ?

**Comment by fire** [comment]
> Does hovering over the minimized node give a tooltip?

> Currently no, by doing so we will need to add a button controls instead draw_textures directly.. Maybe after that PR ?

Sounds good.

**Comment by fire** [comment]
@swarnimarun @Jummit Can you guys review this? I'm busy.

**Comment by swarnimarun** [comment]
@fire Will do. (You removed "i".. sad)

Seems to be working fine on my machine.

But I noticed that if had nodes with multiple inputs outputs connections can't be seen without. Especially a big problem with sequence ports, increases mistaken cases of leaving them unconnected as you can't tell if a minimized node is connected to sequence or not.

image

So I think atleast in Visual Script we might want to show sequence ports separately.

**Comment by swarnimarun** [comment]
__Also at the moment it's too easy to click on the close button over the minimize button__, and I feel like we should allow the connections present to be somehow represented or be visible even in minimized mode, cause this way we are simply hiding data which we will have to frequently minimize and maximize to be able to check.
I feel like something like what blender does might be better atleast give some idea of what is going on with the nodes.
image

**Comment by fire** [comment]
flowhub Does it this way.

https://noflojs.org/noflo-ui/ You can play around with flow hub.

**Comment by Jummit** [comment]
> Does it this way.
> 
> https://noflojs.org/noflo-ui/ You can play around with flow hub.

This would require making GraphNodes as large as they need to show all ports. Is this wanted? It is in my opinion, but this would make the whole thing useless on nodes with many ports, which you may want to minimize.

**Comment by Chaosus** [comment]
So, the only problem here is color of connections ?

**Comment by Jummit** [comment]
My solution would be to just make the connection a bundle of all the ports.
sdf

**Comment by fire** [comment]
What is the last status on this?

**Comment by fire** [comment]
The last thing I remember was having the minimize have two modes. One is the minimized node and the other is the single dot collapsed mode.

The minimized node isn't that useful, but the single dot collapsed node is useful for reroute nodes.

I think adding bundled ports is another separate feature request.

**Comment by Chaosus** [comment]
I kinda forgot about it, when been busy for creating Expression nodes. I think this need to only change the gray color to the color of non-minimized connection.

**Comment by Chaosus** [comment]
@iFire I continue to work on Reroute, note this PR is for minimization of nodes and not reroute(this will be a separate PR).

**Comment by Chaosus** [comment]
I currently get stuck and loss interest to continue to do this PR(due to increased amount of hard-to-do "wishes"). If someone can handle it - I will gladly appretiate it

**Comment by fire** [comment]
I couldn't find the pr for reroute node. #11001

**Comment by Chaosus** [comment]
sorry.. I forgot about it (while working on other interesting PR's)... I think I can try to recreate the closed one.

**Comment by Norrox** [comment]
will this be in master ?

**Comment by clayjohn** [comment]
No, if it was in master it would say "merged" this PR says "closed" because it was closed before merging. The label salvageable means that if an interested user wants to pick up from where chaosus' left off they can try to improve it and make it merge quality.

**Pull request closed without merging**
