### PR TITLE
Add ability to use a relative offset in control nodes

### PR DESCRIPTION
**Pull request by creikey**
Partially implements #19529

### CODE REVIEW

**Comment by groud** [comment]
I don't think this is a good idea. 
The anchor system is meant to solve this problem, as you simply have to use a child node with the centered layout to solve the mentioned problem. IMHO, this adds bloat for little gain.

**Comment by creikey** [comment]
@groud Are you saying that in order for the `scale` and `rotation` properties of the Control to take effect from the center of the node, to use the `Layout->centered` option? Because that does not work if the layout of the GUI node is being managed by a `Container` node, which is what most menus that I design use.

**Comment by groud** [comment]
Ah, sorry I was wrong. The original issue is mainly for rotating the control nodes. Indeed, an automatically centering pivot is not possible with Control nodes for now.

TBH, I don't like that much this system, whether it is for Sprites or Control. I think a more robust solution would be to implement a "relative pivot" system, similar to what the anchor system does, instead of those "centered" booleans.

**Comment by creikey** [comment]
Until something like that is implemented, this fix should suffice to aid in creating animated GUIs.

**Comment by groud** [comment]
> Until something like that is implemented, this fix should suffice to aid in creating animated GUIs.

It's not as simple, if we implement "dirty" fixes, it means we have to keep compatibility later on. So sometimes it's better to wait. ^^ But yeah, that could be enough too, it needs to be discussed with other core developers.

**Comment by creikey** [comment]
I think that as it's unlikely something like that is going to be implemented in time for 3.2, it is better to be consistent throughout Godot and have a centered flag like in the `Sprite`  node rather than not having the feature at all.

**Comment by groud** [comment]
> it is better to be consistent throughout Godot and have a centered flag like in the Sprite node rather than not having the feature at all.

As explained in the mentioned issue, this can be worked around with a single line of code. 
So no, it might not be worth adding the feature for now.

**Comment by creikey** [comment]
I agree with you that it is an easily fixable issue by using a script, however, when GUIs get complicated, and there are say 7-8 different kinds of buttons each with their own scripts in a scene, inserting that one line of code into each can become a tedious and error-prone process. There is the possibility of using composition, having a child node change the pivot offset of its parent to be in its center, however, there is no way to have the child node know when the pivot offset is accessed, i.e setter function overloading from a child node. Constantly setting the offset in the `_process` function is overkill, and with many  nodes on screen, can end up slowing down Godot unnecessarily. 

There is no elegant way to have a fully expressive an animated GUI system in Godot right now, without resorting to manually pasting code around. Either this feature or a fully-fledged anchor-like offset positioning system is needed to create said GUI. Given these facts, I believe that this feature is an absolutely necessary addition to Godot 3.2, given a lack of a fleshed-out offset setting system.

**Comment by TheDuriel** [comment]
> There is no elegant way to have a fully expressive an animated GUI system in Godot right now, without resorting to manually pasting code around. Either this feature or a fully-fledged anchor-like offset positioning system is needed to create said GUI. Given these facts, I believe that this feature is an absolutely necessary addition to Godot 3.2, given a lack of a fleshed-out offset setting system.

Fully agree. I am currently forced to update the pivot position every frame via script, just so animations dont break,

**Comment by groud** [comment]
To be honest, the GUI system was never meant to be animated, and it is still not meant to be. I agree making it this more flexible is needed, but I personally won't be in favor of bloating the system just for animations. You should use sprites instead if you need complex animation on GUI elements.

But in any case, as it can be worked around in one line of code, I will disagree on changes we are not sure about. Maintaining this code is already a pain (a thing I mostly do myself), I don't want to have to implement a bunch of workarounds to keep backward compatibility on a fix made too fast.

**Comment by creikey** [comment]
If you make the entire GUI's text out of sprites, then there is still a huge code reuse problem when you want the GUI to organize itself. These changes are necessary for a fully fledged, animated GUI.

**Comment by volzhs** [comment]
yeah. I have the same workaround with @TheDuriel for animating GUI in some cases.
we have a great power of animation system that anything can be animated.
I second this PR.

**Comment by groud** [comment]
Once again, this is not flexible enough. We are really fast going to have people asking for the pivot to automatically stick to the center-right of the control for example, or to the bottom center. The center option in sprites is bad as is, and spreading this bad design is not a good idea.

I'd accept this PR if it implemented instead a Vector2 "relative pivot", so that we don't have to code that again later on.

**Comment by creikey** [comment]
I can do that now, my only concern is the lack of consistency with the Sprite node.

**Comment by volzhs** [comment]
@groud good point. I agreed.

**Comment by creikey** [comment]
Instead of a vector2, I'm going to use an array of floats like margin so it can be clamped from `0` to `1` in the editor

**Comment by groud** [comment]
It should not be clamped between 0 and 1, the pivot can be outside the node. 
So a Vector2 is a better option.

**Comment by creikey** [comment]
I might be confused as to what you're saying. Are you describing a `Vector2` that is scaled so that `1` is the full length of the rect in the respective dimension?

**Comment by groud** [comment]
I am not sure what you mean by scaled but yeah, 0 would mean left/top of the control's rect and 1 would mean right/bottom. With the x value of the vector2 for horizontal axis and y for the vertical one. As the pivot can be outside the rect those value must not be constrained between 0 and 1 (like the anchors).

Also, the final pivot position should be computed somehow `(relative_pivot * rect_size) + pivot` (pivot being the current pivot property, which is absolute) .

**Comment by creikey** [comment]
The way I'm doing it now is just having the final pivot be the `relative_pivot * rect_size + pivot_offset`. I was only wanting to constrain the property to make it easier to edit within the editor, but I now don't think that's very important.

**Comment by groud** [comment]
Yeah, an editor hint to constraint the vectors properties is not possible yet. But such constraints could be added later on without compatibility breakage, so it is less important. :)

**Comment by creikey** [comment]
I could also change the `Sprite` node so it has a `relative_offset` instead of a centered flag as well. I'm not sure how deeply ingrained the `centered` property is in the engine though.

**Comment by groud** [comment]
You can open another PR for that if you want, but if I were you I would wait for this one to be merged first. To be sure we all agree on the design. :)

**Comment by creikey** [comment]
Yes, that seems to make sense. Not only that, but many projects depend on the sprite having the centered flag, so it's more likely a change for 4.0 I think, because it is breaking.

**Comment by TheDuriel** [comment]
How about replacing the current pivot property with said relative pivot?

0, 0 = top left corner
1, 1 = bottom right
-1, -1 = position - size aka. to the top left of  the control

This pivot would need to be displayed in the Scene view. (Like a Position2D node or anchor handle.)


I don't think there is much demand for an absolute units based pivot, except in pixel perfect games. But a percentage based one would fit well with the already adaptive nature of Control nodes.  (Which prefer sprites over control nodes anyways and use Controls mostly for layout. And are not hampered by this due to their fixed resolution.) Doing so would also avoid some of grouds bloat concern, as we are not stacking a modification on top of existing code.

**Comment by groud** [comment]
No, as I said the pivot should be allowed with negative values, we cannot use such trick.

The absolute pivot should be kept for compatibility reasons, and for people that do not need resizing their controls it makes more sense than a relative one.

**Comment by TheDuriel** [comment]
>No, as I said the pivot should be allowed with negative values, we cannot use such trick.

Not sure what you mean. There's negative values in my example which would place the pivot outside the control.

Also, how is typing (16, 16) any different to (0.25, 0.25) for a size (64, 64) control?

**Comment by groud** [comment]
A - 1,-1 vector2 in a relative mode means the pivot is one rect length and height to the left/right outside the node. This is an acceptable value  so we cannot use such trick.

Removing the possibility to have an absolute pivot might lead to a lot of people complaining they have to manually set their pivot again everytime they resize their node (the exact same claim as you did before), a thing that they did not have to do before. Both property can coexist, it is not a problem. If we see later that the absolute pivot is rarely used, we might remove it someday, but for now the property should stay.

**Comment by TheDuriel** [comment]
>A - 1,-1 vector2 in a relative mode means the pivot is one rect length and height to the left/right outside the node. This is an acceptable value so we cannot use such trick.

That's the point though.

I guess having both systems coexist is fine for now.

**Comment by groud** [comment]
Ah sorry, I have just realized I misunderstood your last messages. I though you wanted negative values to become a pixel-based offset. ^^
But yeah, re-reading them, we agree on the way the relative pivot is computed.

**Comment by akien-mga** [comment]
Could you rebase and squash commits together? http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

**Comment by reduz** [comment]
I would rename functions to:
```
set_pivot_centered(bool)
is_pivot_centered() const
```
for more consistency

**Comment by reduz** [comment]
I missed part of the discussion it seems. I am really against making this more complex.
You can already put a Control as a child of a Node2D and use anchoring to control how it will scale, so replicating this functionality and making it more complex is not wanted.

**Comment by groud** [comment]
> Adding a centered property is a simple solution to avoid a complex workaround. Anything more complex is deserving of a complex workaround.
If this was just centering it, its a simple convenience that its easy to find and understand, but anything more complex should not be merged.

Since we had a discussion on IRC, I will stand my point here too.

For me, there is no more reasons to suppose that centering the pivot of a control node is a more simple or common use case than having the pivot to the middle-right or the bottom-center of the control node. Those use cases would be covered if we use a Vector2, but not if we use a "centered" boolean.

But well, as @reduz stated those ones do not have a valid and honest issue, that "needs to be something you stumbled upon because you needed it." So if anyone has stumbled upon such problem, she or he can open an issue I guess. (I cannot open an issue, that would be invalid and dishonest since I am apparently biased :p)

**Comment by creikey** [comment]
The workaround @reduz stated of placing the control that you are trying to manipulate, e.g rotating a label, under a node 2d or a control and then taking advantage of the already present mechanisms to center a child control rather than introducing this new relative pivot does not work if you are using a `Container` node, such as an `HBoxContainer` or a `GridContainer`.

**Comment by creikey** [comment]
@akien-mga I've rebased into a single commit

**Comment by akien-mga** [comment]
There's a rebase gone wrong in this PR, it includes over 500 commits.

**Comment by creikey** [comment]
This PR has several issues including merging from the master branch of my fork, so I'm going to close this, fix my master branch, then reopen a new PR on a new branch that links to this one, as I have since then properly learned how to rebase a branch.

**Pull request closed without merging**
