### PR TITLE
Added new notification: NOTIFICATION_IGNORED_TRANSFORM_CHANGED

### PR DESCRIPTION
**Pull request by Phischermen**
This notification is sent when a translation occurs but the node is set to ignore translation notifications.

Another notification is necessary because certain nodes, such as visual instances, rely on the transform notification to update servers/gizmos. If the user sets a node to ignore transform changes, then the gizmo/visual instance will not be placed correctly.

I haven't written docs yet, and I was thinking of changing the name of the notification. Any suggestions would be appreciated!

### CODE REVIEW

**Comment by Phischermen** [comment]
This could be cherry picked for 3.2. All the code changes in node_3d.cpp and node_3d.h would just have to go in spatial.cpp and spatial.h

**Comment by akien-mga** [comment]
It seems a bit weird to set a node to ignore translation notifications, but then add a new notification type for nodes that ignore translation notifications... Why ignore notifications in the first place?

**Comment by Phischermen** [comment]
> Why ignore notifications?

There are certain cases, like I discovered after I opened #37283, where a transform notification can be sent endlessly. In summary, I found out it's important to ignore transform changes when responding to a transform change notification. But then I discovered another problem; gizmos and visual instances would not update if the node was set to ignore transform notifications. I found out that these things rely on the transform notification to update.

Technically, the user could get around this by manually updating these things in their tool script like so
```
func _notification(what):
        match what:
        NOTIFICATION_TRANSFORM_CHANGED:
            set_notify_transform(false)
            #snap to grid
            translation = translation.snapped(Vector3.ONE)
            update_gizmo()
            VisualServer.instance_set_transform(instance, global_transform)
            set_notify_transform(true)
```
This feels redundant to me, because this logic already exists at the engine level. To solve this issue, I added the new notification, and hooked it up so that it updates gizmos and visual instances.

**Comment by aaronfranke** [comment]
@Phischermen Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch. While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

**Comment by Phischermen** [comment]
I am definitely still interested in this PR. I'll rebase it in the near future.

**Comment by reduz** [comment]
The whole point of having to set that you want to receive transform notifications is to improve performance by _not_ receiving it when not needed. If this is added, then that optimization goes away and there is no point for it existing on the first place.

Because of this, there is no point in this PR, closing it.

**Pull request closed without merging**
