### PR TITLE
Make md5's not be in the same file as the import settings

### PR DESCRIPTION
**Pull request by sdfgeoff**
This is an initial pull request relating to #17103 
This version creates a new file called `<filename>.import.md5` which contains the hashes for the source and destination files. This is one solution to the earlier mentioned issue with version controlling the .import files.

------------------------

edit: this has now been updated so instead of `<filename>.import.md5` it creates `<filename>-<hash>.md5` inside the `.import` folder

### CODE REVIEW

**Comment by akien-mga** [comment]
Unrelated to this PR, but for the reference: the email you're using to sign your commits is not linked to your GitHub account, so the commits don't appear as authored by @sdfgeoff. It's not an issue, but if you want nice GitHub stats to brag about your contributions, you may want to add that email as secondary email in your GH settings.

**Comment by NathanWarden** [comment]
Very nice, thank you! :)

**Comment by akien-mga** [comment]
BTW your system clock seems to be configured to NZ local time with CET timezone (GMT+1), so your commits come from the future ;) 
image

**Comment by sdfgeoff** [comment]
Should be fixed now, both the squash and the clang-format.

....Having a time machine really helps productivity, you know....

**Comment by Zylann** [comment]
What if you have two assets with the same name? Or two similar assets in different folders?

**Comment by sdfgeoff** [comment]
It uses the same path as the exported resource does. And godot has a clever way of handling this whereby they use the path <filename>-<hash> whereby the hash is the hash of the filepath. This means it handles matching filenames just fine.

**Comment by akien-mga** [comment]
Thanks a lot for this fix :)

**Comment by hpvb** [comment]
cherry picked into 3.0.3

**Pull request merged**
