### PR TITLE
Documentation for StyleBoxFlat

### PR DESCRIPTION
**Pull request by toger5**
The sync is really big since there were some bigger changes like enum...
Before merging someone should check if it is all good.

### CODE REVIEW

**Comment by akien-mga** [comment]
I prefer to do the necessary sync myself, there's some manual work necessary.

**Comment by toger5** [comment]
@akien-mga okay so I just wait until the Stylebox changes are in master and than propose mac changes?

The docs currently propose that this is done by contributors. Should that be removed?

**Comment by akien-mga** [comment]
The docs are correct for the normal workflow, it's just that we are in a transition time which makes it a bit tricky.

I think you can just copy paste your documented StyleBoxFlat, and add it manually to the non-synced classes.xml. It should be then kept when I sync.

**Comment by toger5** [comment]
That is a good solution (copy paste with everything also enum="" ...)

**Comment by toger5** [comment]
I close this one scene I opened one based on your sync

**Pull request closed without merging**
