### PR TITLE
Fix editor drawing snapping lines for wrong edge/corner when resizing elements with smart snapping enabled

### LINKED ISSUE #32342: Resize-snapping lines bug
**Godot version:**
28fcc5e

**Issue description:**
I accidentally discovered it when checking something else:
62g2JI7fdd

The editor seems to be snapping the bottom line, even though I'm moving the top one. This brings some weird results.

Somewhat related to https://github.com/godotengine/godot/issues/32324#issuecomment-535057692, because implementing snapping for all sides would probably fix this.

### PR DESCRIPTION
**Pull request by ericrybick**
fixes #32342

### CODE REVIEW

**Comment by groud** [comment]
I don't get it. How can this have an impact ? Nothing is supposed to be modifyed by calling snap_point.

I am not sure this is the correct way to solve the problem.

**Comment by ericrybick** [comment]
`snap_transform` is the transform that is used to decide where the line is drawn in and `snap_transform` is set at the end of the `snap_point()` function.

`snap_point():`
tngzj


`draw_smart_snapping():`
abc

**Comment by groud** [comment]
OK, I guess it make sense then. I would rather find a cleaner way to solve the problem, but I am not sure it is possible without a significant refactor of the code.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
