### PR TITLE
Replace Array return types with TypedArray (part 1)

### PR DESCRIPTION
**Pull request by KoBeWi**
This PR replaces return types of methods from Array to TypedArray or PackedArray where possible. I only changed methods exposed to scripting that have return type "Array" and methods called by these methods.

Obviously the changes turned out to be enormous, so I'm splitting it into multiple PRs (there will be 2 or 3 more).

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
Text server changes looks fine.

_Note: do we have `TypedArray` template in the `godot-cpp`? It probably will be necessary to support custom GDExtension text server implementations._

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Looks fantastic! Needs rebase and should be ready to merge.

**Comment by akien-mga** [comment]
Needs another rebase :upside_down_face:

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
