### PR TITLE
Update CSG documentation to explain how to make hidden collision CSGShapes

### LINKED ISSUE #55557: Non-Collision bug on CSGCombiner when hidden/non-visisble (in-game and editor)
### Godot version

v3.4.1.rc1.official [7b0801c7f]

### System information

Windows 10, GLES3, Nvidia RTX 2080 SUPER

### Issue description

I noticed that when you make any CSGCombiner Hidden or Non-Visible it causes the collision to stop calculating or working, resulting in Non-Collision. I was wondering if the collision was supposed to work regardless of whether any CSG object is non-visible?

Here is a link to a video demonstration to the bug I'm trying to explain:
https://youtu.be/GHgZliDruGk

I've also attached a sample project with everything shown in the video that showcases the bug.

### Steps to reproduce

In Godot's 3D viewport/space, place a Spatial node first, then a CSGCombiner Node as a child node to the Spatial, use either KinematicBody or RigidBody object/node to test the collision on the CSG to see if you can see the bug occurring.

### Minimal reproduction project

[3point4_Test.zip](https://github.com/godotengine/godot/files/7644626/3point4_Test.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Closes #55557.

### CODE REVIEW

**Comment by hoontee** [comment]
No longer applicable after #40814 / #58938. Root CSG shapes retain their collision when hidden.

**Comment by Calinou** [comment]
> No longer applicable after #40814 / #58938. Root CSG shapes retain their collision when hidden.

Was the portion that affects hidden collision shapes reverted in the end? I haven't fully followed things.

**Comment by hoontee** [comment]
> Was the portion that affects hidden collision shapes reverted in the end? I haven't fully followed things.

Root CSG collision shapes retain their collision when hidden since https://github.com/godotengine/godot/pull/40814 / https://github.com/godotengine/godot/pull/58938 was merged. It didn't get reverted.

**Comment by hoontee** [comment]
@YuriSizov #55621 which is the 3.x version is still open.

**Pull request closed without merging**
