### PR TITLE
Mesh::convex_decompose: Remove unneeded vector copy

### PR DESCRIPTION
**Pull request by lupoDharkael**

### CODE REVIEW

**Comment by asheraryam** [comment]
Looks good to me, I took a look at the convex_decompose() function and indeed it does not seem to modify the faces vector passed to it.

https://github.com/godotengine/godot/blob/a7f49ac9a107820a62677ee3fb49d38982a25165/modules/vhacd/register_types.cpp#L35

Note that there is currently only one convex_composition_function, and if other alternative functions are added they should also not modify the p_faces being passed -- which is good to avoid in any case so I don't think we should compromise for the sake of a potential bad practice happening later.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by akien-mga** [comment]
Removed cherry-pick as this code was actually useful in `3.2` (converting `PoolVector<Face3>` to `Vector<Face3>`).

**Pull request merged**
