### PR TITLE
Fix crash in audio callback when recording audio

### LINKED ISSUE #54879: Crash when recording audio in WASAPI audio driver
### Godot version

4.0 (1aa3c84)

### System information

Windows 10

### Issue description

Godot crashes when running a project that attempts to record audio. Tested on Windows 10 but likely affects all versions of Windows.

The crash stems from inside the audio callback in the WASAPI audio driver in `drivers/wasapi/audio_driver_wasapi.cpp` in `AudioDriverWASAPI::thread_func`, specifically at line 717:

    hr = ad->audio_output.render_client->GetBuffer(write_frames, &buffer);

It appears to fail because of a bad `write_frames` value.

I believe I have solved the issue and will link a PR shortly.

### Steps to reproduce

Attempt to open and run [the minimal reproduction project](https://github.com/benjarmstrong/mic_record_godot_4)

### Minimal reproduction project

[Uploading example_project.zip…]()

### PR DESCRIPTION
**Pull request by benjarmstrong**
Fixes #54879

### CODE REVIEW

**Comment by benjarmstrong** [comment]
The fix works because `buffer_frames` is only meant to be used for rendering to the output device, but was assigned when initializing both the input and output devices. If input were initialized after output, then it would assign a value to `buffer_frames` that is potentially too large to be used in the audio callback. 


I couldn't help but notice this too:

        if (!p_capture) {
            buffer_frames = max_frames;
        }
        
        int64_t latency = 0;
        audio_output.audio_client->GetStreamLatency(&latency);
        // WASAPI REFERENCE_TIME units are 100 nanoseconds per unit
        // https://docs.microsoft.com/en-us/windows/win32/directshow/reference-time
        // Convert REFTIME to seconds as godot uses for latency
        real_latency = (float)latency / (float)REFTIMES_PER_SEC;

which I think should probably be:

        if (!p_capture) {
                buffer_frames = max_frames;
                
                int64_t latency = 0;
                audio_output.audio_client->GetStreamLatency(&latency);
                // WASAPI REFERENCE_TIME units are 100 nanoseconds per unit
                // https://docs.microsoft.com/en-us/windows/win32/directshow/reference-time
                // Convert REFTIME to seconds as godot uses for latency
                real_latency = (float)latency / (float)REFTIMES_PER_SEC;
        }

There's also this line:

    real_latency = (float)output_latency_in_frames / (float)current_pwfex->nSamplesPerSec;

Which I think should also only run `if (!p_capture)`

**Comment by akien-mga** [comment]
CC @EIREXE

**Comment by benjarmstrong** [comment]
Just a thought, maybe `buffer_frames` should be renamed to something like `output_buffer_frames` or `render_buffer_frames` to better indicate that it's not used for capture at all

**Comment by akien-mga** [comment]
> Just a thought, maybe `buffer_frames` should be renamed to something like `output_buffer_frames` or `render_buffer_frames` to better indicate that it's not used for capture at all

`output_buffer_frames` makes sense yeah. As for the other proposed checks, I'm not familiar with that driver code but it seems sensible if this code is not used for audio input.

**Comment by benjarmstrong** [comment]
> As for the other proposed checks, I'm not familiar with that driver code but it seems sensible if this code is not used for audio input.

Yeah okay, I'll see if I can produce a bug with it and file a separate issue + fix

**Comment by benjarmstrong** [comment]
I've confirmed the code that assigns `real_latency` leads to an issue where `AudioServer.get_output_latency()` incorrectly reports 0 while an audio input source is enabled. The fix is really simple (it's exactly what I proposed above) but this behaviour can't be observed in the master branch until this is merged (otherwise Godot simply crashes the moment you enable an input source to reproduce the bug).

**Comment by akien-mga** [comment]
I think it would be fine to add the subsequent fix to this PR directly, they're kinda related.

**Comment by benjarmstrong** [comment]
> I think it would be fine to add the subsequent fix to this PR directly, they're kinda related.

Updated the PR accordingly

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
