### PR TITLE
Fix `gdextension_compat_hashes.cpp` for double precision builds

### LINKED ISSUE #86346: GDExtension: double-precision builds differ in method hashes and lack compatibility
### Tested versions

4.3.dev.custom_build.3ce73e5d4 (built from 3ce73e5d4)

### System information

Windows 10

### Issue description

I built a recent `master` version with both `precision=single` and `precision=double` options in scons.

Now I would like to export the `extension_api.json`. For the single version, it works fine, but for the double version I'm met with dozens of warnings about hash incompatibilities, like this:

```
WARNING: Compatibility hash 1057544502 mapped to non-existent hash 3656773645. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2055804584 mapped to non-existent hash 1980270704. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2055804584 mapped to non-existent hash 1980270704. Please update gdextension_compat_hashes.cpp.
```

<details>
<summary>Full output</summary>

```
λ godot.windows.editor.dev.double.x86_64.console.exe --dump-extension-api --headless
Dumping Extension API
Godot Engine v4.3.dev.custom_build.3ce73e5d4 - https://godotengine.org

WARNING: Compatibility hash 1057544502 mapped to non-existent hash 3656773645. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2055804584 mapped to non-existent hash 1980270704. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2055804584 mapped to non-existent hash 1980270704. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1634855856 mapped to non-existent hash 153818295. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 3283884939 mapped to non-existent hash 288975085. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2437345566 mapped to non-existent hash 4175465202. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 3836314258 mapped to non-existent hash 2931053748. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 860410478 mapped to non-existent hash 3042891259. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1358907026 mapped to non-existent hash 1816663697. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1868867708 mapped to non-existent hash 1579955111. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1222433716 mapped to non-existent hash 3344325384. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1149405976 mapped to non-existent hash 1851767612. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 3489634142 mapped to non-existent hash 703945977. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2747409789 mapped to non-existent hash 1282766827. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 3123400617 mapped to non-existent hash 2882425029. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 4067663783 mapped to non-existent hash 2086826090. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1002852006 mapped to non-existent hash 2754756483. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 496058220 mapped to non-existent hash 4288681949. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 496058220 mapped to non-existent hash 4288681949. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 496058220 mapped to non-existent hash 4288681949. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1002852006 mapped to non-existent hash 2754756483. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1002852006 mapped to non-existent hash 2754756483. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1002852006 mapped to non-existent hash 2754756483. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 754862190 mapped to non-existent hash 339056240. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 754862190 mapped to non-existent hash 339056240. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 34330743 mapped to non-existent hash 205485391. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 34330743 mapped to non-existent hash 205485391. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 34330743 mapped to non-existent hash 205485391. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 4040559639 mapped to non-existent hash 3711419014. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 4040559639 mapped to non-existent hash 3711419014. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 110375048 mapped to non-existent hash 390416203. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 110375048 mapped to non-existent hash 390416203. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 110375048 mapped to non-existent hash 390416203. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 4252992020 mapped to non-existent hash 2468082605. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 832527510 mapped to non-existent hash 2406300660. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 338791288 mapped to non-existent hash 244650101. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1278520651 mapped to non-existent hash 1062245816. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2180266943 mapped to non-existent hash 1333997032. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 3548053052 mapped to non-existent hash 316450961. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 3346058748 mapped to non-existent hash 3580801207. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 311501835 mapped to non-existent hash 4061635501. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 496058220 mapped to non-existent hash 4288681949. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 496058220 mapped to non-existent hash 4288681949. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 496058220 mapped to non-existent hash 4288681949. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1002852006 mapped to non-existent hash 2754756483. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1002852006 mapped to non-existent hash 2754756483. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 1002852006 mapped to non-existent hash 2754756483. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
WARNING: Compatibility hash 2613124475 mapped to non-existent hash 2498990330. Please update gdextension_compat_hashes.cpp.
     at: GDExtensionCompatHashes::get_legacy_hashes (core\extension\gdextension_compat_hashes.cpp:68)
```

</details>

---

Furthermore, the **two generated `extension_api.json` files are different**. 
Primarily, method parameters differ:
1. Parameters have `"meta": "double"` instead of `"meta": "float"`
2. `hash_compatibility` is absent
3. `hash` is sometimes different
4. very rarely, `PackedFloat64Array` is used instead of `PackedFloat32Array`

Which of the above are intended, and which are not?
* If the signatures are supposed to be different, why do we have the `builtin_class_sizes` JSON object? That one lists all possible configurations, not just the current one -- so why would other places be specific to the current build?
* This makes it harder to build a GDExtension for double precision, without first recompiling the engine. Typically people have the engine around, but theoretically one can just program against the API and run it elsewhere (different machine, deployment server, CI, ...).
* Could we use the `real` type (`real_t` in C++) to abstract some of those differences?

I'll attach the two files, as well as the diff from single to double.
* [extension_api_single.json](https://github.com/godotengine/godot/files/13721134/extension_api_single.json)
* [extension_api_double.json](https://github.com/godotengine/godot/files/13721135/extension_api_double.json)
* [difference.patch](https://github.com/godotengine/godot/files/13721137/difference.patch)

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/86346

I also added the class and method name to the message about mapping to non-existent hashes, since that's pretty critical information for debugging this sort of issue.

cc @Bromeon

### CODE REVIEW

**Comment by fire** [comment]
What sort of review are we looking for? I have a pet interest in double precision.

**Comment by dsnopek** [comment]
Ah, well, this is a little tricky to review. It's easy to see that running `godot --dump-extension-api` with a double precision build no longer prints out the ~40 warning messages. However, actually checking that the hash mappings are correct would be pretty tedious.

I made this PR by:

1. Compiling the engine with double precision on https://github.com/godotengine/godot/commit/60947380599b8fbba741752729db34dde151717d (this is the commit before PR https://github.com/godotengine/godot/pull/81521 was merged, which fixed the hashing algorithm) and generating the `extension_api.json`
2. Compiling the engine with double precision on `master` and generating the `extension_api.json`
3. Processing the two files with a Python script to figure out the hash mapping and generate some code in a text file
4. Manually going through `gdextension_compat_hashes.cpp` and copy-pasting the code in where needed with the addition of the `#ifdef`'s

So, to _really_ check it, you'd need to generate the two `extension_api.json` files and go through each one, which I'm not sure is something anyone would really be willing to do :-)

It may be easiest to approve/merge based on the warnings having gone away, and then we can fix any issues if users find any?

**Review by fire — APPROVED** [review]
> Approve/merge based on the warnings having gone away, and then we can fix any issues if users find any?

Sure!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
