### PR TITLE
Add Audio Server profiling time to the profiler

### PR DESCRIPTION
**Pull request by marcelofg55**
This PR adds profiling data for audio related processing.
Includes includes profiling time from Audio Effects, Audio Server and Audio Driver (CoreAudio, ALSA, PulseAudio and WASAPI).

audioprofiling

### CODE REVIEW

**Comment by marcelofg55** [comment]
Update: I've finished implementing the code, PR can be reviewed now.

**Comment by mhilbrunner** [comment]
Has a conflict :)

**Comment by mhilbrunner** [comment]
Conflict again, sorry :/

**Comment by marcelofg55** [comment]
Solved

**Pull request merged**
