### PR TITLE
Add PowerA Xbox Series X Controller Linux bindings to gamecontrollerdb.txt

### LINKED ISSUE #83178: Event Configuration in Input Mapping confusing Controller Triggers with Horizontal Right Axis
### Godot version

4.1.2 4.2.dev.6

### System information

Windows 11 -  Godot v4.1.2 stable - Compatibility render - Controller

### Issue description

Controller: Xbox One S, latest firmware. (I don't have other controller to test)

In the event configuration, when I try to select the triggers by pressing them, Godot interprets it as if I’m using the right axis (the side depends on which side I press, left or right).

This only happens in the event configuration part of the input map menu. In the game, both the axis and triggers work as intended.

Screenshots:

input captured:
image

Input that I actually pressed:
image

### Steps to reproduce

- Go to Project Settings and select Input Map
image

- Add an event to any action you created
image

- Instead of seraching choose filter by input and press any of the triggers using a controller (I only tested with the Xbox One S controller in the lastest firmware)
image

### Minimal reproduction project

any project

### PR DESCRIPTION
**Pull request by emanvidmaker**
In my attempt to fix #83178 I discovered that #83178 is caused by missing SDL bindings, so i added the binding for my controller and that fixed the issue for me, however this only fixes the issue for  PowerA Xbox Series X Controller users on linux.
Any controller missing its bindings gets affected by #83178 so this still doesn't fix it just partially alleviates the problem and gives us more insight on #83178.

I Also PR this change upstream on mdqinc/SDL_GameControllerDB/pull/762

### CODE REVIEW

**Comment by emanvidmaker** [comment]
Upstream merged it

**Comment by emanvidmaker** [comment]
This SDL bindings issue is still present in 4.3 stable

Im going to build with an updated gamecontrollerdb.txt from  https://github.com/mdqinc/SDL_GameControllerDB/  and see if that fixes it and PR that

**Comment by adamscott** [comment]
cc. @Sauermann

**Comment by emanvidmaker** [comment]
Update: 
* 4.4Dev4 Still has the bug
However...
> Im going to build with an updated gamecontrollerdb.txt from https://github.com/mdqinc/SDL_GameControllerDB/
I have built it and it solves it. Here the new PR that fixes it, https://github.com/godotengine/godot/pull/99304

**Comment by akien-mga** [comment]
Superseded by #99304.

**Pull request closed without merging**
