### PR TITLE
Add low processor workaround to ´ensure_control_visible´ docs

### PR DESCRIPTION
**Pull request by RoniPerson**
The example provided for ´ensure_control_visible´ in the docs wont work in editor plugins. (Tested on 3.4.2)

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request :slightly_smiling_face: 

Pull requests (especially ones that break backwards compatibility) should be opened against the `master` branch instead of `3.x`. This is because feature development occurs in the `master` branch. We can then cherry-pick specific PRs to the `3.x` branch if they don't break backwards compatibility.

Also, it sounds like the original bug should be reported and investigated. It may be an easy fix and is better than just mentioning a workaround in the documentation.

**Comment by Calinou** [comment]
@RoniPerson Bump :slightly_smiling_face: Could you do this?

> Also, it sounds like the original bug should be reported and investigated. It may be an easy fix and is better than just mentioning a workaround in the documentation.

**Comment by RoniPerson** [comment]
Completly forgot about this PR.

I don't think, that this is a bug. Based on #55609 I assume that it is known that waiting for the next frame is neccesarry and didn't consider it a bug. And that the workaround won't work in low processor mode lies in the nature of low processor mode as I understand it. It just won't process thr idle frame every frame so it is not given, that the signal will be called on the next frame.

I opened the PR against 3.x because I didn't know if the behavior of `grab_focus` was touched in the master branch. But I tested it in the beta just now and it still seems to apply. Will update when I find time.

**Comment by RoniPerson** [comment]
Seems I screwed up with updating. Will open again when i fixed it.

**Pull request closed without merging**
