### PR TITLE
Fix Android Export jarsigner error with *.import whitelist

### LINKED ISSUE #34525: Android Export with "*.import" export filter tries to export the same file multiple times resulting in an error.
**Godot version:**
3.2.3 Stable

**OS/device including version:**
Linux Mint 19.2
Kernel: x86_64 Linux 4.15.0-72-generic

**Issue description:**
"*.import" whitelist will try to export import files twice which causes jarsigner to fail.

**Steps to reproduce:**
Export to Android on the Project

**Minimal reproduction project:**
[Test1.zip](https://github.com/godotengine/godot/files/3991818/Test1.zip)

### PR DESCRIPTION
**Pull request by nathanfranke**
Fix #34525 

Explicitly disallow *.import filter.

### CODE REVIEW

**Comment by akien-mga** [comment]
A more explicit commit message would be good, you're not "fixing Android export". This fixes an edge case in the Android export workflow, the not whole workflow itself (which would imply that the Android export is broken).

**Comment by nathanfranke** [comment]
Thanks for the suggestion, I made it the same as this PR title which is explicit enough.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
