### PR TITLE
Updated `get_groups` documentation in `Node` to not falsely state that internal groups start with underscores

### PR DESCRIPTION
**Pull request by Arecher**
The documentation for `get_groups` states that in 3.5 it returns internal groups with an underscore prefix format, but this is incorrect. This change has only been added to 4.x (see https://github.com/godotengine/godot/pull/62605)

### CODE REVIEW

**Comment by AThousandShips** [comment]
You need to target the 3.x branch which is the current development for the 3.x version, it can then get cherry picked for 3.5

**Comment by Arecher** [comment]
It stated that **all** of them had underscores, which would still be incorrect in that case. I ran into this in my own project, with `idle_process_internal`, which is an internal group name without the underscore prefix. So it seemed to me that the documentation stating you could filter all internal groups by looking for the underscore prefix was incorrect.

Sorry about targeting the wrong branch! Can I still change this?

**Comment by AThousandShips** [comment]
You can retarget your branch, see [here](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch)

**Comment by AThousandShips** [comment]
> It stated that all of them had underscores

It doesn't necessarily say that, it says that it "uses some group names internally", but most names follow the convention and it was in place by 3.x, it was just overlooked

**Comment by Arecher** [comment]
> It doesn't necessarily say that, it says that it "uses some group names internally"

It actually says:

>The engine uses some group names internally (all starting with an underscore)

Which clearly states *all* starting with an underscore. So that's just incorrect, which means the example, meant to store `non-internal` groups only, also doesn't do that. It at most filters 'some' of the internal groups.

It's wrong either way!

Although it might be worth adding a 'some of which start with an underscore' back in.

**Comment by AThousandShips** [comment]
It should indeed be changed to say "some" as removing it entirely is *more* wrong as *most* groups do have underscore

**Comment by AThousandShips** [comment]
To clarify: The issue in 3.x *isn't* the documentation as much as it is that some cases are not following the already established practice, and the change to fix that was not backported to 3.x

**Comment by Zireael07** [comment]
Anyway the PR will need to be recreated as I see a ton of unrelated changes

**Comment by AThousandShips** [comment]
It needs a rebase as it targets the wrong branch

**Comment by Arecher** [comment]
I'll just close it. Just thought I'd make an easy change to some incorrect documentation, but it's way more convoluted than I expected!

**Comment by AThousandShips** [comment]
Thank you for your work nonetheless!

**Pull request closed without merging**
