### PR TITLE
[WIP] Begin input map action reordering (only the UI for the moment)

### PR DESCRIPTION
**Pull request by Dumbeldor**
Hi,

This is PR for #16833 
It is a beginning. I will continue but i'm open to comments. ;)

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Hey! Thanks for your work. Whats the status of this? :)

**Comment by akien-mga** [comment]
Closing as it's still WIP and no longer getting updates. The proposed feature would be good to have though, so don't hesitate to make a new PR (OP or any other contributor) with a working implementation.

**Comment by Banderi** [comment]
This would indeed be really nice to have! What's missing from this WIP?

**Comment by justinluk** [comment]
I would love to see this happen! @Dumbeldor any interest in picking this back up?

**Comment by Dumbeldor** [comment]
Aye ! I have a lot of work to do on other projects. For the moment i dont have time to continue on Godot engine. But if no one can really finish it, i'll have to finish it myself.

**Comment by justinluk** [comment]
No worries @Dumbeldor - it's really more of a nice to have anyways. Thanks for taking an initial look at it in the first place!

**Pull request closed without merging**
