### PR TITLE
Properly refer to functions definition color in description

### LINKED ISSUE #64684: Highlighting's "Function Color" description calls "Function Definition Color" "Declaration"
### Godot version

v4.0.alpha.custom_build [0c5f25495]

### System information

Windows 10

### Issue description

image

Which one would it be?

### Steps to reproduce

Look at the Theme's Highlighting settings

### Minimal reproduction project

No need.

### PR DESCRIPTION
**Pull request by Mickeon**
Fixes https://github.com/godotengine/godot/issues/64684.

Can probably be cherrypicked to 3.x.

### CODE REVIEW

**Comment by Calinou** [comment]
> Can probably be cherrypicked to 3.x.

3.x doesn't have documentation for editor settings, so this can't be backported.

**Review by YuriSizov — APPROVED** [review]
Hmm, another one of those misnomers in programming jargon. I think technically, this does refer to the declaration, i.e. the name part, not the definition. But since the setting is called `text_editor/theme/highlighting/gdscript/function_definition_color`, I guess that's a valid change.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by Mickeon** [comment]
Is it worth it _at this time_ to rename the setting for accuracy sake?

**Comment by YuriSizov** [comment]
No, I don't think so. IMO it wouldn't be too meaningful of a change, given that in GDScript there are no header files, so everything is declared and defined tightly together.

**Pull request merged**
