### PR TITLE
Check if old mouse column is still available.

### LINKED ISSUE #40947: Tree: hover mouse column, remove column, hover again causes crash [regression from #39350]
**Godot version:**
works: 3.2, 3.2.1
crashes: 3.2.2, 3.2.3.rc3

**OS/device including version:**
Linux Mint 18.3

**Issue description:**
When a tree is hovered, has columns removed, then hovered again, Godot game crashes.

**Steps to reproduce (in MRP)**:
1. run the scene.
2. hover the mouse over the tree.
3. remove a column (Columns: `-`)
4. hover the mouse over the tree. Games crashes.

**Observed Exceptions**
(note: it seems as though if the mouse is over where the tree will be when the game window is starting up, that will count as a hover.)
- Run scene, hover mouse over the tree, remove a column, _hover the mouse over something else_, then hover over tree. Game _might_ not crash.
- Run scene, avoid hovering mouse over tree, remove a column, hover over tree. Game does not crash.
- Run scene, hover mouse over a column that _won't_ be removed (move mouse vertically out of window to avoid hovering other columns; can have hovered any column so long as last hovered column is one that won't be removed), remove a column, hover over tree. Game does not crash.
- Run scene with mouse away from tree, slide mouse from right onto a cell, slide off to right from same cell, remove a column, hover over tree. Game _probably_ won't crash.
- Run scene, hover mouse over only the column that will be removed, remove the column, hover over tree. Game _might_ not crash.
- Run scene, hover mouse over tree, add a column, hover mouse over tree. Game does not crash.

**Backtrace**:
(Calinou godot-3.2.2-debug-linux-gcc5.4)
```
ERROR: get: FATAL: Index p_index = 2 is out of bounds (size() = 2).
   At: ./core/cowdata.h:152.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354c0) [0x7fe2b3ae04c0] (??:0)
[2] CowData<TreeItem::Cell>::get(int) const (/godot/./core/cowdata.h:152 (discriminator 7))
[3] Vector<TreeItem::Cell>::operator[](int) const (/godot/./core/vector.h:85)
[4] Tree::_gui_input(Ref<InputEvent>) (/godot/scene/gui/tree.cpp:2518 (discriminator 1))
[5] MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) (/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[6] Object::call_multilevel(StringName const&, Variant const**, int) (/godot/core/object.cpp:764 (discriminator 1))
[7] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/godot/core/object.cpp:865)
[8] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/godot/scene/main/viewport.cpp:1669 (discriminator 2))
[9] Viewport::_gui_input_event(Ref<InputEvent>) (/godot/scene/main/viewport.cpp:2265 (discriminator 3))
[10] Viewport::input(Ref<InputEvent> const&) (/godot/scene/main/viewport.cpp:2825 (discriminator 2))
[11] Viewport::_vp_input(Ref<InputEvent> const&) (/godot/scene/main/viewport.cpp:1445)
[12] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[13] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/godot/core/object.cpp:922 (discriminator 1))
[14] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/godot/core/object.cpp:849)
[15] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/godot/scene/main/scene_tree.cpp:275)
[16] SceneTree::input_event(Ref<InputEvent> const&) (/godot/scene/main/scene_tree.cpp:431 (discriminator 6))
[17] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/godot/main/input_default.cpp:416)
[18] InputDefault::parse_input_event(Ref<InputEvent> const&) (/godot/main/input_default.cpp:260)
[19] InputDefault::flush_accumulated_events() (/godot/main/input_default.cpp:679)
[20] OS_X11::process_xevents() (/godot/platform/x11/os_x11.cpp:2698)
[21] OS_X11::run() (/godot/platform/x11/os_x11.cpp:3263)
[22] /home/thomas/Downloads/Godot_v3.2.2-debug/godot.x11.tools.64(main+0x116) [0x1424b7c] (/godot/platform/x11/godot_x11.cpp:57)
[23] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fe2b3acb840] (??:0)
[24] /home/thomas/Downloads/Godot_v3.2.2-debug/godot.x11.tools.64(_start+0x29) [0x1424999] (??:?)
-- END OF BACKTRACE --
Socket error: 104
```

**Minimal reproduction project:**
(This is my MRP from https://github.com/godotengine/godot/issues/25392#issuecomment-665285218)
[25392.zip](https://github.com/godotengine/godot/files/4991193/25392.zip)

### PR DESCRIPTION
**Pull request by madmiraal**
Fixes #40947.

### CODE REVIEW

**Comment by akien-mga** [comment]
See also #41874 - which fix is the most correct?

CC @giulianob @HaSa1002

**Comment by HaSa1002** [comment]
I think they are both correct, except that I failed to put the arithmetic operator correctly

**Comment by HaSa1002** [comment]
Ah nervermind. This one is better.

**Comment by akien-mga** [comment]
Thanks to you both for looking into this!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
