### PR TITLE
Add `await` keyword as alias for yield(async_func(), "completed")

### LINKED ISSUE #22947: Add `await` keyword
It would be amazing if I could write `var result = await method(arg)` instead of `var result = yield(method(arg), "completed")` as it highly improves code experience with low cost (no back compat issues, not so difficult to implement, etc.). I assume `async` to be a be a unary expression like `return` with only `FunctionState` possible operand. 

I'm a big fan of `yield` to signals and have a lot of code like
```GDScript
func failed():
  errors += 1
  if errors == 3:
    errors = 0
    level = max(0, level-1)
    yield(view.cat.remove(), "completed")
    generate()
    yield(view.grow(), "completed")
    yield(view.reset(), "completed")
  else:
    yield(view.soft_reset(), "completed")
```
This code is harder to write, harder to read then
```GDScript
func failed():
  errors += 1
  if errors == 3:
    errors = 0
    await view.cat.remove()
    level = max(0, level-1)
    generate()
    await view.grow()
    await view.reset()
  else:
    await view.soft_reset()
```
This is feature proposal/discussion but I'm already on the road of implementing this for local fork.

### PR DESCRIPTION
**Pull request by jkb0o**
This PR allows to await async function in less-typing, easer-reading way:
```GDScript
func _ready():
  var result = await get_frames_time(10)
  print("Time to wait 10 frames: ", result)

func get_frames_time(i):
  var t = 0
  while i > 0:
    yield(get_tree(), "idle_frame")
    t += get_process_delta_time()
    i -= 1
  return t
```
Closes #22947 & #21039.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
That wouldn't match `await` in other languages though, it's conceptually different.

**Comment by LikeLakers2** [comment]
I'm still not sold on the idea of an alias. It still seems unnecessary compared to just making a non-asynchronous function. You could also have that function spin up a [Thread](http://docs.godotengine.org/en/latest/classes/class_thread.html) that you could return, then `wait_to_finish()`.

**Comment by jjay** [comment]
@OvermindDL1  can you please point me to conceptually difference please? I really do not understand.
Wiki says
```
Coroutines are computer-program components that generalize subroutines
for non-preemptive multitasking, by allowing multiple entry points for
suspending and resuming execution at certain locations.
```
As far as GDScript allows you to suspend invocation, save state between invocations and return result when it is complete, I can say with confidence that it has coroutines. 

Languages implement coroutines different. Python implements it over iterators, (with gevent/greenlet modules, when I worked with 2.7). Python coroutines was transparent to the user and have no need to expose coroutine state (3.5 introduce explict async/await). JavaScript uses Promises inside and `await` to await the result. C# looks much the same.

GDScript use signals and MessageQueue to implement coroutiness. I need to say `var result = yield(coroutine(), "completed")` to await the result. There is no any difference with python/javascript/C#/etc. This PR just clarifies this.

**Comment by jjay** [comment]
@LikeLakers2 it is important to not use Threads. They are heavy. And I need to run almost all code in a single thread to avoid locking and all other multithreading stuff. I want to explain approach bit deeper.

I use coroutines as building blocks of my game, it is all about decomposition. Imagine some character class in the boardlike game. Let's suppose it can turn and can move forward. This 2 simple actions are not just animation, they change state over time (transform, animation frames, etc.). With coroutines it is super easy to queue this actions and wait for result:

```GDScript
func on_run_turn_pressed():
   ui.disable_input()
   run_turn_button.disabled = true
   await unit.rotate_left()
   await unit.move_forward()
   await unit.move_forward()
   await unit.rotate_right()
   ui.enable_input()
   run_turn_button.disabled = true
```

Without coroutines, to implement this simple game logic part I need to write complex `_process` logic with own `turns` queue or use state machines which become complex over time and not even readable or whatever. And without `await` it is a lot of bullshit typings. I use coroutines heavily. Almost 500 `yields` of 1000 in my game is `yields` to `completed` signal. This is why this PR here.

**Comment by OvermindDL1** [comment]
> As far as GDScript allows you to suspend invocation, save state between invocations and return result when it is complete, I can say with confidence that it has coroutines.

GDScript does have single-shot coroutines yes (though it lacks multi-resumeable coroutines, not that those are really useful for await implementations though).

The thing is, if GDScript ever gets something like Algebraic Effects or any other high level coroutine idiom where something like `await` can be implemented from within the language itself, making `await` a keyword kills that future abilities, where `yield` is just a function call style and is basically inherent to coroutine usage.  I.E. it is gaining the ability to save a couple of characters now in exchange for ruining a possible API later.  Heck, may as well just implement Algebraic Effects now with full multi-resumeable coroutines (say via a `clone` call on the coroutine environment or so to make that cost explicit) then you can implement proper await as well as a *significant* amount of other idioms that GDScript does not currently support without substantial scaffolding.

**Comment by jjay** [comment]
@OvermindDL1 This makes sense, I have to agree. Thanks for the detailed answer. I will provide another PR with single argument `yield` as suggested in #21039, seems easy.

**Pull request closed without merging**
