### PR TITLE
Re-add a way to generate a single convex shape from the editor

### LINKED ISSUE #35692: No more option to generate a single Convex Shape for a MeshInstance?
**Godot version:**
3.2.stable.official

**OS/device including version:**
Not applicable.

**Issue description:**
The option to just have Godot generate a single Convex CollisionShape for a MeshInstance is no longer available, it seems to be replaced by the new Convex decomposition method in 3.2.
I get that this is a needed addition, but why remove the older option?
Wouldn't it make more sense to have both options available in the drop-down menu?
I realize that this is still possible to do with a tool script, but it seems illogical to me to directly replace it in the editor, was this done for a specific reason?

Congrats on the 3.2 release by the way!

### PR DESCRIPTION
**Pull request by Calinou**
It was removed after the implementation of VHACD. Generating a single shape can lead to better performance, so it may still be desired.

This also adds tooltips for several options in the Mesh menu.

This closes #35692.

### CODE REVIEW

**Comment by EzraT** [comment]
Thank you!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Comment by YBPN** [comment]
I just downloaded Godot 3.2.2 for Mac, and there is no “Create Convex Static Body” in the Mesh menu. There is only “Create Trimesh Static Body”. 

I’m not sure I understand what happened in this thread (I’m new to Godot), but shouldn’t “Create Convex Static Body” be in the Mesh menu?

**Pull request merged**
