### PR TITLE
Fix `RichTextLabel`'s modified stack being wiped on translation changes

### LINKED ISSUE #96937: Rich text labels resetting unexpectedly when scene tree modified in game Godot 4.3-stable
### Tested versions

- Reproducible in: 4.3.stable, - Not reproducible in: 4.2 stable, 4.1.stable, and earlier godot versions

### System information

Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce MX250 (NVIDIA; 31.0.15.4629) - Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 Threads)

### Issue description

image

For reference, I am using above code to change in-game scenes. This has worked for all versions until now and this property has been crucial for my project.
As of now, rich text labels are being reverted to default when above function switches to another mini-scene, then back.

Below is the edited rich text label using parsed bbcode(I tested and the code that edits the text does not run when switched back)
image

Now when the first function is called twice to change to another section then back, it turns into this, which is what it looks like initially and in the editor. No other nodes are affected except rich text labels.

image

Interestingly enough, with one of my rich text labels that was edited through a multi-threaded-process, it seems to keep the edits even with the scene change, however, the other rich text labels in that scene revert back to default.

### Steps to reproduce

1: Create scene with rich text label
2: Add functionality to parse bbcode and change the text
3: Create a main scene
4: Use supplied function

For the project!
1: click the change scene button
2: click the change rich text button
3: click the change scene button twice
4: see the result

### Minimal reproduction project (MRP)

[richlabelbug.zip](https://github.com/user-attachments/files/16985667/richlabelbug.zip)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #96937.

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
- `set_effects()` and `install_effect()` use 
```c++
if ((!text.is_empty()) && use_bbcode) {
	parse_bbcode(atr(text));
}
```
instead of
```c++
if (!text.is_empty()) {
    _apply_translation()
}
```
and should be updated to take `stack_externally_modified` into account (unlike other cases, it's only updating is bbcode is enabled).

- `remove_paragraph()` should also set `stack_externally_modified = true;`.
- `_apply_translation()` can have early `if (text.is_empty()) { return; }` to avoid calling parsers.

**Comment by YeldhamDev** [comment]
@bruvzg Sorry for the wait, changes made.

**Review by Repiteo — APPROVED** [review]
Codestyle checks out

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
