### PR TITLE
ThemeEditor: fix broken dialog

### PR DESCRIPTION
**Pull request by ghost**
Before
image

After
image

Currently, this PR only puts controls in containers. Usability fixes will come later. (Move name to the bottom etc.)

### CODE REVIEW

**Comment by toger5** [comment]
is it possible to use consistent Gui elements? I'm referring to the use of a different dropdown ( icon: arrow, type+name: ..) ?

**Comment by Noshyaar** [comment]
Type/name box can be typed in.

**Comment by toger5** [comment]
@Noshyaar oh okay that makes sense. 
What about replacing it with a h-button array with toggle buttons. this would allow to only open the dialog once to add the icon + stye style box for an Item.

**Comment by Noshyaar** [comment]
You mean replacing Data Types dropdown with HButtonArray? I think that's possible because the number of types is constant (5).

**Comment by toger5** [comment]
@Noshyaar yea exactly.
If a ui element doesn't has a field for an icon the according button could be greyed out.

Maybe it even could be compleatly redesigned. I don't like, that there are two add options (add item class, add item)
Maybe they can be merged into one.
First selecting a class, than OPTIONALLY adding a name or data types to not add the whole class.

Also renaming the Theme button to: `Add Theme Items` or any other call to action phrase. Would be a nice addition. (don't know if it fits in your pr though? )

**Comment by Noshyaar** [comment]
I'll try to redesign it. Maybe something like this? This will merge Add/Remove/Add all/Remove all together in a dialog.
img

**Comment by akien-mga** [comment]
Wow! So editor, such modern, very theme!

**Comment by toger5** [comment]
that is a great idea! I also was thinking about how to also add the removing.
this design solves it perfectly

**Comment by toger5** [comment]
also did a mock:
screen shot 2017-07-27 at 11 23 13

Added a search bar.
I also think it would be best to use a tree instead of a list. the tree could be almost the same one than the "add node dialog" except it only has elements which can get themed.
for each element there than could be subelements for the different data types.

**Comment by akien-mga** [comment]
Merging the current state, feel free to discuss a refactoring further and implement it :)

**Pull request merged**
