### PR TITLE
Added rsplit() method to String class

### PR DESCRIPTION
**Pull request by Krakean**
Script used for testing:
...

	var some_string = "Milk, Chicken, Bread, Butter"

	#var t0 = some_string.rsplit(", ", false, 0)  # ['Milk', 'Chicken', 'Bread', 'Butter']
	#var t1 = some_string.rsplit(", ", false, 2)  # ['Milk, Chicken', 'Bread', 'Butter']
	
	var t0 = some_string.rsplit(" ", false, 0)  # ['Milk,', 'Chicken,', 'Bread,', 'Butter']
	var t1 = some_string.rsplit(" ", false, 2)  # ['Milk, Chicken,', 'Bread,', 'Butter']

	print("source: " + some_string)
	print("====")

	for word in t0:
		print("t0: " + word)	
	
	print("====")

	for word in t1:
		print("t1: " + word)

...

### CODE REVIEW

**Comment by reduz** [comment]
I think this can be worked around quite easily with regular split() or get_slice() API. Not really sure if worth merging. Would like to hear others about it.

**Comment by QuentinCaffeino** [comment]
Well It could be useful if you have a long string)

**Comment by mhilbrunner** [comment]
I think `string` is one place where having a more extensive standard library makes sense. I could have used this a few times in the past and had to roll my own :)

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Pull request merged**
