### PR TITLE
[macOS, 3.2] Implement confined mouse mode.

### PR DESCRIPTION
**Pull request by bruvzg**
Same as #40053 for 3.2

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by jamie-pate** [comment]
This doesn't seem to work if the mouse cursor is over the dock when the mode is switched :(
https://streamable.com/6i7fd9

This is the code that I'm using to switch mouse modes:
```Python
func _set_active(value):
	active = value
	if $PlayerHead/Camera and value:
		$PlayerHead/Camera.current = value
	if value:
		var w: Node = world_mgr
		if w && w.has_method('get_arg'):
			if !w.get_arg('no-capture-mouse'):
				Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	else:
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		velocity = Vector3()
```

**Comment by bruvzg** [comment]
> Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

`MOUSE_MODE_CAPTURED` and `MOUSE_MODE_CONFINED` are completely different modes:
- Captured: no system cursor visible, mouse is locked in the center of window and receive only relative movement data.
- Confined: system cursor is visible and moving normally, but can't leave window bounds.

This PR have nothing to do with captured mode. If captured mode is not working properly please open new issue with the minimal reproduction project.

**Comment by jamie-pate** [comment]
Thanks for the clarification, here's a new issue for the existing bug.
https://github.com/godotengine/godot/issues/42321

**Pull request merged**
