### PR TITLE
Prevent identifiers from naming as built-in funcs and global classes

### PR DESCRIPTION
**Pull request by Chaosus**
I think preventing users from using internal names like `abs`, `floor` or `Input` for their function or variables is good, it may lead to bugs and autocompletion failures.

### CODE REVIEW

**Comment by vnen** [comment]
Maybe this should also be done for local variables. Essentially the same check in the `parse_variable()` function.

**Comment by Chaosus** [comment]
@vnen Done, also added same check for signals

**Comment by vnen** [comment]
@Chaosus for signals and enums it is redundant since `parse_class_member()`  is already called for them, so the check is being done twice. In `parse_variable()` it is still useful since this is used by local variables too.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by dalexeev** [comment]
I'm against and suggest revert this PR. Some names like `load` are common. And besides, it becomes impossible to override some of the built-in class methods. IMO this is not the way we should solve problems.

**Comment by Chaosus** [comment]
> Some names like load are common

The problem with these names is that you cannot use them within the script which defines them.

> And besides, it becomes impossible to override some of the built-in class methods

Provide an example, please

**Comment by dalexeev** [comment]
> Provide an example, please

See above. For example, you cannot override the `ConfigFile.load` method.

**Comment by dalexeev** [comment]
> The problem with these names is that you cannot simply use them within the script which defines them.

No, I can. `self.load`.

**Comment by briansemrau** [comment]
As a compromise, the error could be made a warning. Using these names still works, it just requires careful use. Just like integer division or implicit type narrowing.

**Pull request merged**
