### PR TITLE
Fix `RichTextLabel` not correctly returning text with `get_text()`

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes a bug with the match counter on help pages not updating.

Regression from #39148.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @HaSa1002

**Review by bruvzg — CHANGES_REQUESTED** [review]
That's what `get_parsed_text()` is doing, I guess help pages should use it instead.

**Comment by HaSa1002** [comment]
What should I say? bruvzg is correct. I forgot to search for get_text in the codebase and only searched for get_bbcode.

**Comment by YeldhamDev** [comment]
I see. Will close this and open a new PR with that change.

**Pull request closed without merging**
