### PR TITLE
fix(tileset): Recreate custom data editor if type has changed 

### LINKED ISSUE #57642: (4.0) New Tileset editor don't update custom_data layer type
### Godot version

4.0 alpha 1

### System information

Windows 11

### Issue description

Editor don't update custom data type. In gif there is "int" type whole time...

### Steps to reproduce

Godot_v4 0-alpha1_win64_iURQNni84S

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by MisterMX**
Reload the property editor if the type of the tileset's custom data layer has changed.

Fixes https://github.com/godotengine/godot/issues/57642

### CODE REVIEW

**Comment by KoBeWi** [comment]
Is this a fix for #57642?

**Comment by MisterMX** [comment]
> Is this a fix for #57642?

Yes, that should fix it.

**Comment by akien-mga** [comment]
CC @groud @KoBeWi

**Review by groud — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
