### PR TITLE
TextureProgress: `progress_offset` now added to relative center

### LINKED ISSUE #55338: `progress_offset` of TextureProgressBar doesn't move the reference cross
### Godot version

2681d93 (and probably 3.4)

### System information

W10

### Issue description

When you set the fill mode of TextureProgressBar to radial (e.g. clockwise), you get this reference cross in the middle that denotes the radial center: 
LJWzo7VSjq

The problem is that if you move `progress_offset` property, it moves the texture along with its center, but not the reference cross:
tSXXgVW77u

### Steps to reproduce

1. Add TextureProgressBar and assign a texture
2. Change fill mode to clockwise
3. Change the `progress_offset` property

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by RedHeadphone**
`progress_offset` of TextureProgress wasn't moving the reference cross. Hopefully this would fix it.

fixes #55338

### CODE REVIEW

**Review by KoBeWi — CHANGES_REQUESTED** [review]
This isn't a right fix. E.g. here
https://github.com/godotengine/godot/blob/52b7d5fa347fb88aa016e1e30414abd01e800381/scene/gui/texture_progress_bar.cpp#L478-L479
the `progress_offset` is added to the relative center, so it's applied twice.

I'd instead adjust only the cross position, so add the offset somewhere here:
https://github.com/godotengine/godot/blob/52b7d5fa347fb88aa016e1e30414abd01e800381/scene/gui/texture_progress_bar.cpp#L495-L506

**Review by KoBeWi — APPROVED** [review]
Looks good now, but you need to [squash your commits](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase).

**Comment by RedHeadphone** [comment]
@KoBeWi 
I squashed the commits, can you let me if I did it correctly.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Pull request merged**
