### PR TITLE
Fix get_base_dir windows top level directory logic

### LINKED ISSUE #52048: get_base_dir returns wrong path with top level directories on windows
### Godot version

3.2.4.beta5

### System information

Windows 10

### Issue description

`get_base_dir` seems to be returning some paths wrong. 

```
print("C:\\puff".get_base_dir()) # outputs "C:\p"
print("C:/puff".get_base_dir()) # outputs "C:/p"
```

I tested multiple versions of Godot. 

These return "C:" : 3.0.stable, 3.2.stable, 3.2.2.stable, 3.2.3.stable, 3.2.4.beta3, 3.2.4.beta4
These fail※: 4.0.dev※※, 3.4.beta4, 3.4.beta3, 3.3.3.stable, 3.3.2.stable, 3.2.4.beta6, 3.2.4.beta5

※: Meaning they return what I said in comments above.
※※: Built 13bd020a23008cd4e51be21865c620e12e3b3ded

Thus, something went wrong from 3.2.4.beta4 to 3.2.4.beta5. I went over the commits between them, that lead me here: https://github.com/godotengine/godot/commit/cddff0404dbeadbe04d575c0211adba7fa4b3355

### Steps to reproduce

Run this code:

```
print("C:\\puff".get_base_dir()) # outputs "C:\p"
print("C:/puff".get_base_dir()) # outputs "C:/p"
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by theraot**
This is a fix for https://github.com/godotengine/godot/issues/52048

If we look at the diff for https://github.com/godotengine/godot/commit/cddff0404dbeadbe04d575c0211adba7fa4b3355 we observe that before it was looking for a `3` character string (`"://"`), and now it is looking for a `2` character string (either `":/"` or `":\\"`).

Edit: Updating the use of `substr` accordingly fixes windows top level directories (e.g. `"C:\\puff"`) but breaks Godot paths (e.g. `"res://puff"`). Also, it is worth noting that the code already has an special case for the unix root directory (`"/"`). Thus, we need to handle:

- Finding `"://"` (`3` characters).
- Finding `":\` (`2` characters).
- Finding `":/"` (`2` characters).
- `"/"` at the start (`1` character).

And we need to be careful with order in which we check because `"://"` contains `":/"`.

---

This code demonstrate the change:

```
func test(s:String):
	print("\"", s, "\" -> \"", s.get_base_dir(), "\"")

func _ready() -> void:
	test("C:")
	test("C:\\")
	test("C:\\puff")
	test("C:\\puff\\")
```	

Before https://github.com/godotengine/godot/commit/cddff0404dbeadbe04d575c0211adba7fa4b3355 (tested in Godot 3.2.3) the output is:

```
"C:" -> ""
"C:\" -> "C:"
"C:\puff" -> "C:"
"C:\puff\" -> "C:\puff"
```

After https://github.com/godotengine/godot/commit/cddff0404dbeadbe04d575c0211adba7fa4b3355 (tested in Godot 3.3.3) the output is:

```
"C:" -> ""
"C:\" -> "C:\"
"C:\puff" -> "C:\p"
"C:\puff\" -> "C:\puff"
```

With this PR (tested in custom build of Godot 4.0) the output is:

```
"C:" -> ""
"C:\" -> "C:\"
"C:\puff" -> "C:\"
"C:\puff\" -> "C:\puff"
```

*Bugsquad edit:* Fixes #52048.

### CODE REVIEW

**Comment by theraot** [comment]
I think this pull request at the time of writing introduces a new bug: `"res://".get_base_dir()` return `"res:/"`. I'll address this.

**Comment by theraot** [comment]
Added new test cases. They pass on my machine.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by theraot** [comment]
I opened a pull request for the 3.x branch (I had not noticed the file ustring.cpp was in a different path, which prevent cherrypicking it).

**Pull request merged**
