### PR TITLE
Haiku: platform support

### PR DESCRIPTION
**Pull request by Max-Might**
Hello.

I have been working on platform support for the Haiku operating system.
This pull request adds support for the editor, platform support for keyboard, mice and sound (using the media kit API).

At the moment there is no export functionality.
Most of the code is in `platform/haiku` and `drivers/media_kit`.

I had to make it link dynamically with `libglew` because this library has a native port for Haiku and I could not make the one included in the source compile.

There are also three ifdefs to make it use `<fcntl.h>` instead of `<sys/fcntl.h>`.
I think the POSIX one is `<fcntl.h>` and Haiku uses it. Maybe `<sys/fcntl.h>` is a linuxism, I am not sure as I do not have that much knowledge in this area.

Feedback is welcome :)

### CODE REVIEW

**Comment by punto-** [comment]
is Haiku the new BeOS? can we add OS::is_computer_on() ?

**Comment by Max-Might** [comment]
Yes, might add OS::is_computer_on_fire() while we are at it :)

**Comment by reduz** [comment]
this looks pretty good. Given haiku is kind of a self-contained platform,
i'd just move the audio driver to platform/haiku too
other than that, it looks fine to me and can be merged

**Comment by punto-** [comment]
Is this audio api available anywhere else? Like some bsd or something?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Juan LinietskySent: Thursday, August 13, 2015 10:28 PMTo: okamstudio/godotReply To: okamstudio/godotCc: punto-Subject: Re: [godot] Haiku: platform support (#2369)this looks pretty good. Given haiku is kind of a self-contained platform,
i'd just move the audio driver to platform/haiku too
other than that, it looks fine to me and can be merged


On Thu, Aug 13, 2015 at 5:03 PM, Костадин Дамянов <notifications@github.com>
wrote:

> Yes, might add OS::is_computer_on_fire() while we are at it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2369#issuecomment-130823621>.
>


—Reply to this email directly or view it on GitHub.

**Comment by Max-Might** [comment]
Haiku's API consists of several 'kits' - game, application, package, network, storage and others.
The media kit is used by multimedia applications to play audio and video.
As far as I know it is not available on other platforms.
I will move the code to `platform/haiku`.

**Comment by punto-** [comment]
yeah that makes sense then..

On Fri, Aug 14, 2015 at 12:40 PM, Костадин Дамянов <notifications@github.com

**Comment by Max-Might** [comment]
Audio code moved to platform/haiku.

**Comment by reduz** [comment]
thanks! will merge asap

**Comment by skarmiglione** [comment]
I want test it, how can i? i am not programmer but enjoy testing soft on haiku os

**Comment by Max-Might** [comment]
@skarmiglione Check out my branch.
Then compile by typing `scons platform=haiku` and run the executable in the bin directory.
Beware that it runs quite slow because does not yet have hardware accelerated 3D drivers so everything is rendered on the CPU.

**Pull request merged**
