### PR TITLE
Implemented check_vadjust in CheckBox & CheckButton. It was exposed to the editor, but not used.

### PR DESCRIPTION
**Pull request by MuffinManKen**
…but wasn't used.

### CODE REVIEW

**Comment by akien-mga** [comment]
It's also defined and unused in `CheckButton`.

Do you need it for something specific? If it never worked in two nodes but was never reported by any user, it might be better to simply drop this constant.

**Comment by MuffinManKen** [comment]
Yes, the reason I realized it wasn't implemented was that I was trying to use it and it didn't do anything.  Without this constant it can be challenging to get the icons to nicely line up with it's text.

**Comment by MuffinManKen** [comment]
I can look at the code for CheckButton too.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
