### PR TITLE
Implement XMLParser.get_current_line()

### PR DESCRIPTION
**Pull request by KoBeWi**
I measured how it affects parsing speed (as this performs a comparison for each char in a file); I parsed `XMLParser.xml` 10 times in a loop and with this PR the parsing time went from 9-10ms to 10-11ms, so it's acceptable.

### CODE REVIEW

**Comment by Calinou** [comment]
Could you open a proposal to justify the use case for this? While the method is marked as not currently implemented, I'm not sure what would be the use cases for it.

**Comment by KoBeWi** [comment]
https://github.com/godotengine/godot-proposals/issues/4810

**Review by akien-mga — APPROVED** [review]
Looks good.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
