### PR TITLE
[macOS] Fix rendering on retina displays with HiDPI support disabled.

### LINKED ISSUE #25501: Application renders too small on Mac with Retina Display
**Godot version:**
3.06.stable.official.8314054

**OS/device including version:**
MacOS 10.14.2
OpenGL ES 3.0 Renderer: AMD Radeon Pro Vega 64 OpenGL Engine

**Issue description:**
After playing a simple empty "game" on a retina display, the resulting window flickers red and only shows the game in a corner.

screen shot 2019-01-30 at 8 20 36 pm

**Steps to reproduce:**
open project on a Mac with retina display (tried on 2017 iMac Pro and 2017 13" MacBook Pro)
[test.zip](https://github.com/godotengine/godot/files/2815685/test.zip)
click play button
→ the resulting window contains 1/4 game, the rest is double buffering flickering between red and grey every frame.

expected behavior: game renders into full window. (either the window is 1/4 of the size or the contents get upscaled)

If "enable HiDPi" is set in the project settings, it works.

**Minimal reproduction project:**
attached. it's really just an empty project.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #25501

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by groud** [comment]
Does this fixes #21416 too ?

**Comment by akien-mga** [comment]
@bruvzg Unrelated to this issue, but can you ping me on IRC/Matrix or by email? I'd like to discuss RTL plans with you :)

**Comment by bruvzg** [comment]
> Does this fixes #21416 too ?

Nop, it's fix for rendering with disabled HiDPI.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
