### PR TITLE
Implement on-the-spot IME support for X11

### PR DESCRIPTION
**Pull request by raulsntos**
Implements the linux part of #53658

Currently the area with the options is rendered in the wrong position:
image

### CODE REVIEW

**Comment by voylin** [comment]
Thanks for your work on this, any idea when this may finally get reviewed so it can be added to the next update?

**Comment by raulsntos** [comment]
The suggestion list still shows in the wrong position and I could not figure out why, so until that's resolved this won't be merged since it offers no benefit over the current implementation that uses `over-the-spot`.

If anyone more knowledgeable about X11 knows what I'm doing wrong I'd really appreciate the help.

**Comment by segfault-god** [comment]
I'm not familiar with X Input Method so I've been investigating for a few days, But unfortunately XIM may not have a way to specify a candidate position when using `on-the-spot` style. https://gist.github.com/garasubo/8ebb893f2af1950254df715fcf1de58e#gistcomment-4012210

In SDL2, the candidates are correctly displayed (at least in my Fcitx environment) at the position specified by `SDL_SetTextInputRect` ([sample](https://gist.github.com/jai-x/062258441a5e6e78eb0f5d10addef677)). But it looks like it is communicating directly with Fcitx ([code](https://github.com/libsdl-org/SDL/blob/120c76c84bbce4c1bfed4e9eb74e10678bd83120/src/core/linux/SDL_fcitx.c#L366)) and IBus ([code](https://github.com/libsdl-org/SDL/blob/120c76c84bbce4c1bfed4e9eb74e10678bd83120/src/core/linux/SDL_ibus.c#L526)) through DBus...

**Comment by voylin** [comment]
I've been looking up some info about this, but it is a quite a bit above my level. I hope somebody will be able to do this by the time the beta's start rolling out.

**Comment by bruvzg** [comment]
> I'm not familiar with X Input Method so I've been investigating for a few days, But unfortunately XIM may not have a way to specify a candidate position when using on-the-spot style.

If it's displayed under the window, I guess we can try adding an invisible sub-window as a host for IME, add use its position to move candidate window.

**Comment by raulsntos** [comment]
I've tried to create a sub_window to use for IME but then the sub_window steals the focus and I can't give back focus to the main window because it seems when I try to focus back on the main window the LineEdit still has the focus and reopens the IME sub_window, maybe I'm doing it wrong.

For now, I rebased but I'm marking this PR as a draft and moving the milestone to 4.x since I don't think I'll finish this for 4.0.

**Comment by voylin** [comment]
I may give this a try, not certain if I can succeed or not.
Don't have that much time so if I don't come up with anything within this month then I probably failed.

**Comment by raulsntos** [comment]
Superseded by https://github.com/godotengine/godot/pull/70052

**Pull request closed without merging**
