### PR TITLE
Properly mute `-Wundefined-var-template` Clang warning in SafeBinaryMutex

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixup of #94169, hopefully addressing this: https://github.com/godotengine/godot/pull/94169#issuecomment-2309753103

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Could we silence this with a `#pragma` instead? I'm not so fond of outright disabling this warning for the whole codebase to workaround one instance where it seems to be wrong / bothersome.

**Comment by RandomShaper** [comment]
Makes sense. I've force-pushed with a local approach. I haven't tested it myself, though.

**Comment by RandomShaper** [comment]
This is notwithstanding that someone finds out how to make the compiler happy via code. I gave up after trying lots of options.

**Review by akien-mga — APPROVED** [review]

**Comment by aaronfranke** [comment]
Thanks, I've confirmed that this fixes compiling.

**Comment by RandomShaper** [comment]
Cherry-pick for 4.3 included in #96606.

**Pull request merged**
