### PR TITLE
Rect2: add function returning same rect with positive w and h

### LINKED ISSUE #13344: Suggestion - Rect2 translator to positive width and height
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10

**Issue description:**

I was creating an RTS style drag selector - a rectangle that can select units onscreen. I noticed that if I dragged the rectangle "to the left" I was unable to use Rect2.encloses() to check if my units were inside the selection.

I believe it means that Rect2 with a negative size.x or size.y cannot be used for an encloses call, it will always fail. So I wrote a GDScript to translate the rectangle to a positive width and height by shifting the position relative to those numbers.

I suggest an additional method on the Rect2 class that would do this shifting (or making the other methods that compare rectangles allow for legitimate rectangles specified in this way).

**Steps to reproduce:**
Check the project for an explicit example.

**Link to minimal example project:**

[Rectangles.zip](https://github.com/godotengine/godot/files/1506569/Rectangles.zip)

### PR DESCRIPTION
**Pull request by ghost**
Not sure about the name. I put in "abs" for now.

Fixes #13344, using the same test case:
```
	var r1 = Rect2(100,0, -50, 50)             # r1.abs() = Rect2(50,0, 50, 50)
	var r2 = Rect2(80,1, 5, 5)
	print("R1 encloses R2: ", r1.encloses(r2))                  # Returns False
	print("+R1 encloses +R2: ", (r1.abs()).encloses(r2.abs()))  # Returns True
```

### CODE REVIEW

**Comment by akien-mga** [comment]
Do we even want to support negative `size` components for `Rect2`? Sounds a bit weird. What's the use case?

**Comment by Noshyaar** [comment]
When origin is to the right/bottom of the endpoint? I'm not sure tbh. I don't think it's specified anywhere that negative value is not supported. I know that sizes can't be negative, but since it's just Vector2 I can kinda imagine it is going in the opposite direction.

**Comment by goodyttoor** [comment]
Would it be easier to check for negative size at Rect initialization and convert it to positive size with offset origin?

**Comment by Noshyaar** [comment]
@goodyttoor I was thinking the same. That'd be a better approach IMO. I'm not sure if it would be unexpected for users. They might expect the position to stay the same after a creation of Rect2. Still, this is better than misleading them to create (useless) Rect2 with negative sides.

**Pull request merged**
