### PR TITLE
[macOS, X11] Redirect mouse motion events to the active popup.

### LINKED ISSUE #88324: Editor: The popups selecting menu options on mouse move
### Tested versions

Bug introduced by this commit: 06c2cda848b4bca8ee2f54a09417a97a7c1384d3

### System information

macOS 14.1, Apple M3 Pro

### Issue description

~When editing an exported `Dictionary` property, trying to change the type of a property opens a popup to chose the new type.~

In fact, this seems to be the case of every popup menus. The right click menus for example have the same problem, if you maintain the right click and drag over a menu item, this menu item will be clicked once you start moving the mouse again after releasing the mouse button.

If the mouse doesn't immediatly move after clicking of the edit button, the popup will close itself when the mouse begins to move, using whatever type is under the mouse as the selected type.

### Steps to reproduce

 - Create a script with an exported dictionary
 - Add this script to a node
 - Open inspector for this Node
 - Edit dictionary
 - Click on the ✎ button
 - Don't move the mouse for ~1s
 - Move the mouse

https://github.com/godotengine/godot/assets/3855602/f460ea12-4b91-4a24-89ef-cf220229216e

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/88324

### CODE REVIEW

**Comment by bruvzg** [comment]
> How does this PR relate to https://github.com/godotengine/godot/pull/85583 which goes in the opposite direction?

Hm, I guess we might want to send event to all popups (or to the popup mouse is hovering), instead.

**Comment by akien-mga** [comment]
The problem is reproducible on Linux/Wayland too, so it likely needs the same fix.

**Comment by bruvzg** [comment]
> The problem is reproducible on Linux/Wayland too, so it likely needs the same fix.

It's something else, Wayland do not support multiple windows, so it should be something similar in the embedded window handling (probably reproducible on all platforms with singe-window mode).

**Comment by bruvzg** [comment]
Superseded by https://github.com/godotengine/godot/pull/88392

**Pull request closed without merging**
