### PR TITLE
Add hexadecimal and binary number literal support to Expression parser

### LINKED ISSUE #57171: Evaluating script snippets in editor gives incorrect result when using hexadecimal/binary literals
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 10

### Issue description

In the script editor, evalutaing a code snippet (Ctrl+Shift+E) involving a hex or binary literal such as `0xf4` or `0b11110100` sometimes incorrectly evalutates to `0`.

image

### Steps to reproduce

Current behaviour:

1. Evalutating any mathematical operating involving one or more hex or binary literals evaluates to `0`.
I'd expect example this to evaulate to either `0xf5` or `245`, or to cause no change to stay consistent with examples 2 and 3.
`0xf4 + 0x01` -> `0`
`0xf4 + 1` -> `0`

2. Evalutaing a hex literal by itself causes no change. 
I'd expect this example to evaluate to `244` but that's a design decision rather than a bug
`0xf4` -> `0xf4`

3. Evaluating a snippet using a hex or binary literal in a function causes no change.
`sqrt(0x04)` -> `sqrt(0x04)`
`sqrt(0x04 * 2)` -> `sqrt(0x04 * 2)`

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Haydoggo**
- Adds hex and binary literal support to [`Expression`](https://docs.godotengine.org/en/latest/classes/class_expression.html)'s parser.
- Resolves #57171

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you squash the two commits together? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for details.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
