### PR TITLE
Expose parameters for open_scene_from_path method in EditorInterface

### LINKED ISSUE #3907: Add a method to create a new inherited scene from code
### Describe the project you are working on

2D isometric car race game.  currently in Godot 3.4.2

### Describe the problem or limitation you are having in your project

In my game I will  have to add about 1000-2000 vehicles of 200-400 types (for now i have 256 in 42 types). Each vehicle must be unique beacuse only one instance can be in game scene at once. I have base CarTemplate scene. Then I create default CarType which inherits from CarTemplate. Then I make specific Car scenes (usualy 6- 10) which inherit from CarType and have its unique features. Making one CarType by hand takes me about half an hour. 

I designed EditorPlugin which helps with tedious process of making new Car scenes. It takes assets from named folders and creates nessesery Resources (e.g. SpriteFrames, simple scripts inherited from CarTemplate.gd script I have, etc.) and then ataches them to corresponding Car scenes. 

Unfortunately whole proccess can not be fully automatic. Car scenes must be made by hand if I want to use benefits of inheritance... It takes time and makes a risk of typing mistakes.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With ability to create a new inherited scene directly from GDScript, it would be possible to fully automate process of creating inherited scenes inside editor and thus could save a lot of developer's time. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It could be a **new Method** added to **PackedScene**.

The code in GDScript should allow something like:
```gdscript 
var inheriting_scene : PackedScene = load("res://InheritingScene.tscn")
var inherited_scene : PackedScene = inheriting_scene.create_new_inherited_scene()
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

There is no code for this. Only tedious clicking and typing in the editor.

### Is there a reason why this should be core and not an add-on in the asset library?

The proposal looks like core to me. Also I suppose change like that is imposible to do whitout changing base engine code and recompiling it.

### PR DESCRIPTION
**Pull request by Xwdit**
Close https://github.com/godotengine/godot-proposals/issues/3907

### CODE REVIEW

**Comment by KoBeWi** [comment]
That's a lot of parameters. I don't think users need that many and also you didn't even document what they do.

I'd just remove all new arguments except `set_inherited`.

**Comment by TheDoorworlds** [comment]
Excited to see a pull request for this!  Thank you for working on it.

**Review by YuriSizov — CHANGES_REQUESTED** [review]
I agree with @KoBeWi, we don't need most of these parameters in the public API. We have a specific request at hand and can cover that with just one flag. And it does need to be documented.

**Comment by akien-mga** [comment]
Superseded by #90057. Thanks for the contribution!

**Pull request closed without merging**
