### PR TITLE
Allow for vec2/vec4 to be used in reflect and refract

### PR DESCRIPTION
**Pull request by Geometror**
I think there is no reason why this should be restricted to vec3 since GLSL and HLSL both provide vec2 and vec4 variants of reflect and refract.

### CODE REVIEW

**Review by reduz — APPROVED** [review]
I think nobody will ever use this, but no harm in adding it for compatibility with GLSL shaders.

**Comment by Chaosus** [comment]
You need to add this to the members dialog (constructor of `VisualShaderEditor`).

**Review by Chaosus — CHANGES_REQUESTED** [review]
You need to add this to the members dialog (in the constructor of `VisualShaderEditor`).

**Comment by Geometror** [comment]
@Chaosus Done:)

**Review by Chaosus — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
