### PR TITLE
Implement per-light Specular property in DirectionalLight3D

### LINKED ISSUE #80737: DirectionalLight3D currently has no Specular property
_Note: This issue was transferred from the godot_docs repository. What appeared to be an issue with the documentation turned out to be an issue with the feature itself. clayjohn has commented below a bit of background. Ultimately, the ghost documentation highlights that we removed a setting by mistake. The solution is to restore the setting._

**Your Godot version:** 4.1 Stable

**Issue description:** DirectionalLight3D missing Specular property, current documentation states this should exist

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/tutorials/3d/lights_and_shadows.html
https://docs.godotengine.org/en/stable/tutorials/3d/global_illumination/faking_global_illumination.html

**Additional information:**

https://github.com/godotengine/godot-docs/blob/05fe756d9d1e6abab198da4721ba8f0407f0e45e/tutorials/3d/lights_and_shadows.rst?plain=1#L44

According to the text (from Godot Engine 4.1 - 3D Lights and Shadows, linked above) and the screenshot of common light properties above it, `DirectionalLight3D` (like Omni and Spot lights) should have a `Specular` property but currently doesn't (4.1 Stable). Not sure if this is a bug, a documentation issue or due to on going work.

directionallight3d_missingspecular
<sub>specular property missing from DirectionalLight3D</sub>

Due to this, currently unable to remove the specular blob from DirectionalLights when following "Godot Engine 4.1 - Faking global illumination". Which specifically mentions setting `Specular: 0.0` on `DirectionalLight3D`.

https://github.com/godotengine/godot-docs/blob/05fe756d9d1e6abab198da4721ba8f0407f0e45e/tutorials/3d/global_illumination/faking_global_illumination.rst?plain=1#L48

### PR DESCRIPTION
**Pull request by Calinou**
- This closes https://github.com/godotengine/godot/issues/80737.
- Supersedes https://github.com/godotengine/godot/pull/80742. Thanks @AndrewShobbrook for the original implementation :slightly_smiling_face:

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good to me for RD. I expect a slight performance decrease when using DirectionalLights from this change as I think that part of the shader is relatively load/store bound. However, this was a missing feature so there is no way around it. I would avoid cherry picking this PR for that reason though

For compatibility, have you checked if the property is being sent from the CPU?

**Comment by Calinou** [comment]
> I expect a slight performance decrease when using DirectionalLights from this change as I think that part of the shader is relatively load/store bound. 

Can we do bitpacking or use FP16 in the future to reduce the performance impact? This float doesn't need much precision - half precision would be fine, possibly even lower if it's converted from a fixed-point value.

**Comment by clayjohn** [comment]
> Can we do bitpacking or use FP16 in the future to reduce the performance impact? This particular value doesn't need much precision, as it's between 0.0 and 1.0 most of the time (rarely above 3.0). Half precision float would be fine, possibly even lower if it's converted from a fixed-point value.

Bitpacking would most likely help as long as the bottleneck continues to be load/store related. You just need to find a property to pack with it

**Comment by Repiteo** [comment]
Needs rebase before it can be merged

**Comment by clayjohn** [comment]
> While testing this, I've also found that the Specular property doesn't do anything with any light type on vertex-shaded materials. This is an issue on all rendering methods. I believe it should be addressed separately as it'll require more shader changes.

This is intentional. Neither metallic nor specular are used.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
> This is intentional. Neither metallic nor specular are used.

I meant the light's Specular property, not the material's specular property (which is a derivative of its metallic behavior). Light3D Specular only affects the specular lobe, and it should be possible to make it affect vertex-shaded materials too.

**Pull request merged**
