### PR TITLE
Fix segfault at quiting editor

### PR DESCRIPTION
**Pull request by volzhs**

### CODE REVIEW

**Comment by akien-mga** [comment]
Fix seems OK, but looking at the code, wouldn't it be better to move the instancing of `Popup` and `ColorPicker` in the constructor, and show/hide them accordingly based on the use? https://github.com/godotengine/godot/pull/18922/commits/e639db0529d97f6b797503617906cd26c2a06021#diff-a6f0c42713fe6fcee354a228c5bc8aceR731

Currently it seems a bit weird to have them initialized on the first click, which means that if you don't click then you'll have NULL `picker` and `popup` being accessed everywhere unless guarded as here. CC @MarianoGnu

**Comment by akien-mga** [comment]
I don't know, it just seems more Godot-like to me to initialize the children in the constructor, and use them when needed, instead of creating them on the fly and having to check that they were created each time.

But I'm not sure, maybe it's better as is, I don't have a strong opinion :)

**Comment by volzhs** [comment]
there are many color picker buttons on the inspector dock, almost every node has one or more, but actually not using it often.
so, I think it's good to make picker on demand.

**Comment by reduz** [comment]
This was done to save on performance in the new inspector, as initializing the color picker is relatively more expensive than the other controls. I now have realized I should have added a comment about why this was done, though.

**Comment by hpvb** [comment]
Cherry picked into 3.0.5

**Pull request merged**
