### PR TITLE
Fix tilemap world_to_map return error map coordinates

### LINKED ISSUE #31468: TileMap world_to_map unexpected result with half offset
**Godot version:**
bcd2f24

**OS/device including version:**
Windows 10

**Issue description:**
For a TileMap node, using world_to_map, with a negative position on the border between 2 tile rows while half offset is active, it returns the wrong position by 1 depending on the other axis.

**Steps to reproduce:**
calling
world_to_map(Vector2(-49,-64))
on a TileMap with cell size 64,64, and half offset x
Should be -2,-1 or -1,-2 as those are the 2 tiles it's on the border of, but returns -1,-1

Minimal project
[minproject.zip](https://github.com/godotengine/godot/files/3513637/minproject.zip)

### PR DESCRIPTION
**Pull request by myhalibobo**
_Bugsquad edit:_ Fixes #31468.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Looking over the code, aren't the old and new expressions mathematically equivalent?

Looks good overall, just I'm not sure it will change anything.. :smiley:

**Comment by akien-mga** [comment]
> Looking over the code, aren't the old and new expressions mathematically equivalent?

There's a difference when the float is already "round":
```gdscript
	printt(int(-2.9) - 1, int(floor(-2.9)))
	printt(int(-2.9999988) - 1, int(floor(-2.9999988)))
	printt(int(-3.0) - 1, int(floor(-3.0)))
	printt(int(-3.0000012) - 1, int(floor(-3.0000012)))
	printt(int(-3.1) - 1, int(floor(-3.1)))
```
Prints:
```
-3      -3
-3      -3
-4      -3
-4      -4
-4      -4
```

But the ternary operator can likely be dropped, `int(floor(ret.y))` could be used for both positive and negative numbers.

**Comment by bojidar-bg** [comment]
Ah, guess the program I used to graph the functions smoothed the steps, so I couldn't notice this.
Yeah, replacing the ternary with just `int(floor(ret..)) & 1` is a good idea.

**Comment by akien-mga** [comment]
Force pushed an update with the requested changes. Also changed `default:` to be explicit, to avoid an unnecessary catch-all that could introduce bugs.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
