### PR TITLE
Add MethodInfo to signal datatype

### LINKED ISSUE #62645: Assigning a built-in signal to a custom signal doesn't err
### Godot version

4.0 alpha 11

### System information

Windows 10, Ryzen 5900 X, Radeon 5700 XT

### Issue description

When you try to assign one signal to another, it should err, as this operation doesn't make sense and signals are considered constants.

It errs correctly when left hand part is a built-in, but it doesn't err at all when the left hand part is a custom signal. The scene can be run, the line of code just doesn't do anything (ignore the debugger errors, that's something to do with rendering and refers to Vulkan):

Godot_v4 0-alpha11_win64_2022-07-02_22-51-04

Godot_v4 0-alpha11_win64_2022-07-02_22-51-44

### Steps to reproduce

Create a script with a custom signal and try to assign to it like any other variable in one of the class methods, like `_ready`.

### Minimal reproduction project

Should be trivial to reproduce.

### PR DESCRIPTION
**Pull request by anvilfolk**
Fixes #62645 and is more general than its current proposed solution #62660.

### CODE REVIEW

**Comment by anvilfolk** [comment]
In the future, if `signals` ever implement default parameter values, we can use the following code
```if (param->default_value) {
	reduce_expression(param->default_value);
	if (!param->default_value->is_constant) {
		push_error(R"(Signal parameter default values values must be constant.)", param->default_value);
	} else {
		mi.default_arguments.push_back(param->default_value->reduced_value);
	}
}
```

**Comment by adamscott** [comment]
@anvilfolk Can you create unit tests for this fix?

**Comment by anvilfolk** [comment]
> @anvilfolk Can you create unit tests for this fix?

Hahah, I have been busted! I always tell others to do that and forgot it for myself. Touché!

But now done, there's a unit test for signal assignment :)

**Review by rune-scape — APPROVED** [review]
happy to see this one :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
