### PR TITLE
Rename `remove()` to `remove_at()` when removing by index

### LINKED ISSUE #2885: Array & Vector: rename `remove()` to `remove_at()`, Array, Dictionary & Set: rename `erase()` to `remove()`
See https://github.com/godotengine/godot/pull/49701
### Describe the project you are working on
Godot
### Describe the problem or limitation you are having in your project
Array's current [`erase()`](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-erase) and [`remove()`](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-remove) methods are poorly named because the words "erase" and "remove" are (for the most part) synonymous.
### Describe the feature / enhancement and how it helps to overcome the problem or limitation
```gdscript
remove(position) -> remove_at(index)
erase(value) -> remove(value)
```

It was [originally proposed](https://github.com/godotengine/godot/issues/16863#issuecomment-441376010) to rename `erase()` to `remove_value()`, but people seem to prefer renaming it to `remove()` (https://github.com/godotengine/godot/pull/49701#issuecomment-863752431).

I think `Set`'s and `Dictionary`'s `erase()` methods should be renamed to `remove()/remove_value()` too for consistency. 
### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
n/a
### If this enhancement will not be used often, can it be worked around with a few lines of script?
No.
### Is there a reason why this should be core and not an add-on in the asset library?
This is core.

### PR DESCRIPTION
**Pull request by AaronRecord**
Part of https://github.com/godotengine/godot/issues/16863
Closes https://github.com/godotengine/godot-proposals/issues/2885

### CODE REVIEW

**Comment by LightningAA** [comment]
Rebased.

**Comment by LightningAA** [comment]
Rebased following 7adf4cc9b5de6701a41e27690a69b9892d5eed85

**Comment by aaronfranke** [comment]
@LightningAA This needs a rebase. I'm in favor of the change overall since it makes the code more clear.

**Comment by LightningAA** [comment]
> although I'm not sure about your follow-up idea of renaming `erase` to `remove`, I'd imagine that would create confusion.

That was my plan, since originally I was planning on renaming `erase` to `remove_value` as suggested in the original comment, but then people said they'd prefer it to simply be `remove`. In hindsight though, I think `erase` is fine as long as `remove` is renamed to `remove_at`, since the original problem was that `erase` and `remove` would get mixed up because their names don't make the difference between them clear. I probably personally do still prefer `remove` to `erase` a little bit, but even if that did happen I think it'd make sense to do that sometime after 4.0 and after marking `erase` as deprecated, because renaming `erase` to `remove` is likely to cause all sorts of hard to find bugs for people converting projects from 3.x to 4.0 (especially if they're not using automatic conversion tools, if there's one that comes with built-in it might not be as bad), since `erase(some_int)` is also semantically valid.

**Comment by LightningAA** [comment]
Rebased. There's still a number of methods (e.g. https://github.com/godotengine/godot/blob/master/editor/editor_data.cpp#L538, `remove.+?\(int (p_)?[_a-zA-Z0-9]+?in?de?x`) that could have `_at` appended to them, but I've chosen to only focus on the array/vector methods to keep this PR's scope more reasonable. If desired though, I could rename those methods, or they could be done in a separate PR etc.

**Comment by LightningAA** [comment]
rebased

**Review by aaronfranke — APPROVED** [review]
I think this is a good idea.

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
This was approved in PR review meeting (sorry for the delay), it just needs a rebase (or redo if that's easier).

**Comment by LightningAA** [comment]
rebased

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
