### PR TITLE
Rework creating new folders in editor

### PR DESCRIPTION
**Pull request by KoBeWi**
Inspired by https://github.com/godotengine/godot/pull/93372#discussion_r1757855514, this makes EditorFileSystem responsible for creating new folders.

I also added `update_all()` method to FileSystemDock. I needed it for something, but it ended up as simple helper.

### CODE REVIEW

**Comment by Hilderin** [comment]
I like it. The flow seems really better to me!!!

**Comment by Hilderin** [comment]
I found 2 little issues:

### Issue 1
- Click create folder
- Input `test/test` but do not press OK
- Go create the folder test and subfolder test via File Explorer
- Got back to Godot and press OK
- The folders will be duplicate:
image


### Issue 2:
- Click create folder
- Input `test` but do not press OK
- Go create the folder test via File Explorer
- Got back to Godot and press OK
- I expected a popup waying that the folder could not be created, but I only got an error in the output:
image

For the rest, it seems to work perfectly!! Good job, I can't wait to see the other files operations implemented that way. Don't hesitate if you need help for some implementation or some testing.

**Comment by KoBeWi** [comment]
1. fixed
2. it's a pre-existing behavior. Seems to be a bug with DirCreateDialog, which validates path before attempting to create the folder.

**Review by Hilderin — APPROVED** [review]
Great!!
Tested and works perfectly, as expected!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
