### PR TITLE
Scene preview (and cell redesign) in project manager

### PR DESCRIPTION
**Pull request by ghost**
Loosely related to https://github.com/godotengine/godot/pull/14952

preview

**EDIT** the "Show" button from #14952 showing up here was not intended (I messed up my branches).

### CODE REVIEW

**Comment by homer666** [comment]
Hmm, I dunno about this... The scene preview doesn't really give you any information of value, and the project list becomes a lot uglier as a result of the change. I don't think it's worth it.

**Comment by Hinsbart** [comment]
I agree.
Though, maybe this could work as a tooltip like in the scene tabs.

**Comment by poke1024** [comment]
Changed to display details only for the currently selected item:

bildschirmfoto 2017-12-24 um 11 08 31

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by Zireael07** [comment]
Will this go in?

**Comment by akien-mga** [comment]
> Will this go in?

As is I don't know, nobody seems really thrilled about the change so far.
I think @Hinsbart's proposal might be a good compromise:

> Though, maybe this could work as a tooltip like in the scene tabs.

**Comment by mhilbrunner** [comment]
Closing this, as there doesn't seem to be any consensus on merging it. Still, thank you for your work :)

**Pull request closed without merging**
