### PR TITLE
Adjust FileSystem dock split mode's height threshold

### PR DESCRIPTION
**Pull request by ghost**
This makes the FileSystem dock's "split mode" activate at a smaller height (`window_height / 2` rather than `window_height * 3/4`.) This allows other docks to be positioned in the same column at a more reasonable size, without FileSystem reverting back to the single-view mode.

Old: http://i.imgur.com/4Mh2xQc.png (if the Import dock were any taller the thumbnail view would [disappear](http://i.imgur.com/4WHVKXN.png))
New: http://i.imgur.com/Ahk2KQf.png

### CODE REVIEW

**Comment by MrMaidx** [comment]
I like this change. It makes more sense.
I also would prefer change one day to split FileSystem dock into two separate Folders and Files docks. I know it's all tightly bound together but on very wide monitors (which are more and more common) there could be gain from possibility to position Folders and Files next to each other. But it's nothing necessary.

**Comment by Keetz** [comment]
I kind of disagree with this PR. I personally really don't like the split filesystem in general, and has always used another dock in the same column to keep it in the single-view mode. This PR forces me to keep the filesystem dock, not only in a column with something else but also below half the total height.

Just making it a bit more of a hazzle to keep it in single-view mode.

I guess this is more a general grudge on the split filesystem dock, and would like to refer to #7446

I can see why this is a perfectly fine feature if you don't mind the split filesystem, so don't take this as criticism directly to work done here :)

**Comment by homer666** [comment]
@Keetz Yeah, I'm not really a fan of the "auto split-mode activation" altogether, and would prefer to leave the choice between single- and split-view modes to the user. That said, when I made this PR I was under the impression that you actually could force it into single-view by clicking an icon or something, but that doesn't seem to be the case... sorry for whatever inconvenience I caused :$

**Comment by Keetz** [comment]
@homer666 don't be sorry! Again this is by no mean criticism to the work you have put into this, i love that you are supporting godot, and for sure hope you will keep up the good work!

I just want to share my opinion, as this topic have been up for discussion before without a real conclusion, and i want to keep the discussion alive.

Unfortunately i didn't see that the topic was brought up again back in august, hence the 4 month delay here :D else i would have joined in back then.

**Pull request merged**
