### PR TITLE
Windows: Fix `WINDOW_EVENT_FOCUS_IN` not delivered in some cases

### LINKED ISSUE #90473: Renaming a file sometimes shows an error popup
### Tested versions

can happen in v4.3.dev.custom_build [a7b860250]

### System information

linux

### Issue description

https://github.com/godotengine/godot/assets/71937306/bb13f73d-9f4a-45c5-a59e-6edc88f09c41

- as you can see in this clip, renaming a file to an unused name still reports that the name is used in a popup. (the operation doesn't fail though)
- it is not consistent (happened for a while on a test file and then, after writing the report, it stopped happening within the same editor instance)

### Steps to reproduce

rename a file

### Minimal reproduction project (MRP)

any

### LINKED ISSUE #90569: Caret invisible in EditorFileDialog
### Tested versions

4.3 b2f425f
Fine in 4.3 dev5

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/e265cc81-08b4-4ef1-a6ec-46b7d2f5e0a7

Apparently re-focusing the dialog fixes it.

### Steps to reproduce

1. Scene -> Open Scene
2. Type something in **File:** field

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #90569.

**UPDATE:** This also fixes #90473 on Windows as well.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Something seems to be broken with your branch or git, this commit is empty

**Comment by RandomShaper** [comment]
I wonder how that can happen. 🤔 Well, fixed.

**Review by akien-mga — COMMENTED** [review]
#91112 was approved, so approving this one to merge first.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
