### PR TITLE
Fix anisotropic GGX D function, and introduce and use anistropic GGX …

### PR DESCRIPTION
**Pull request by ghost**
…G function.

Also added references.

### CODE REVIEW

**Comment by reduz** [comment]
seems good to me

**Comment by tagcup** [comment]
Let me quickly add a proper reference to Burley 2012 in comments

**Comment by tagcup** [comment]
OK, done, just added the title of Burley's 2012 talk at SIGGRAPH in the comments

**Comment by tagcup** [comment]
Also for further reference, this is based on [Burley's SIGGRAPH 2015 notes](http://blog.selfshadow.com/publications/s2015-shading-course/burley/s2015_pbs_disney_bsdf_notes.pdf) (see section "Smith G").

**Pull request merged**
