### PR TITLE
Make Input `mouse_mode` and `use_accumulated_input` properties

### PR DESCRIPTION
**Pull request by fire-forge**
Converts Input `mouse_mode` and `use_accumulated_input` from setter/getter functions to properties. Also adds a missing getter for `use_accumulated_input` (it only had a setter before).

### CODE REVIEW

**Comment by LightningAA** [comment]
I bound mouse_mode as a property in https://github.com/godotengine/godot/pull/50940 but it's just been sitting for a year

**Review by AaronRecord — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by fire-forge** [comment]
> I bound mouse_mode as a property in #50940 👀

@LightningAA My bad, I should have looked for that before making a PR.

**Comment by LightningAA** [comment]
> @LightningAA My bad, I should have looked for that before making a PR.

No you're totally good, I'm just happy it's finally merged 🙂

**Comment by Calinou** [comment]
I noticed DisplayServer has `mouse_get_mode` and `mouse_set_mode`. Should it be made into a property? Also, how do these methods differ from the ones in the Input singleton?

**Pull request merged**
