### PR TITLE
Show custom icons in autocompletion suggestions

### LINKED ISSUE #91721: Autocomplete doesn't show custom icons
### Tested versions

4.2.2

### System information

Linux PopOS, this is all I'm going to say, I'm on the go and I'm reporting this from my phone, sorry (like, I'm 100% sure my system specs are irrelevant for this issue anyway)

### Issue description

image

Autocomplete doesn't account for custom class icons. It also treats everything with an unknown icon as an object, even if it's actually a node (e.g. the EditorCommandPalette node, which is shown as a node in most places)

Correct icons:

image

### Steps to reproduce

You can reproduce one of the described issues by typing out "EditorCommandPal" and seeing that the autocomplete option has the object icon.

You can add these scripts to reproduce the other issues:

```gdscript
@icon("res://icon.svg")
class_name GodotIconClass extends 
```

```gdscript
class_name ControlExtension extends Control
```

### Minimal reproduction project (MRP)

Editor issue

### PR DESCRIPTION
**Pull request by hakro**
Fixes #91721

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Makes sense to me.

But might be worth evaluating what's the cost of this function in e.g. a project with a lot of class icons. I remember we wanted to do some caching, was it implemented in the end @KoBeWi ?

**Comment by KoBeWi** [comment]
`get_class_icon()` does not have cache, only `get_script_icon()` in EditorData does.
We're missing a method that uses cache and would return an icon for anything 🤔

**Comment by akien-mga** [comment]
BTW something to look into potentially:
```cpp
Ref<Texture2D> ReplicationEditor::_get_class_icon(const Node *p_node) {
        if (!p_node || !has_theme_icon(p_node->get_class(), EditorStringName(EditorIcons))) {
                return get_theme_icon(SNAME("ImportFail"), EditorStringName(EditorIcons));
        }
        return get_theme_icon(p_node->get_class(), EditorStringName(EditorIcons));
}
```

We seem to use `get_class_icon` a lot already throughout the editor, so I guess one more use case shouldn't have dramatic impact if the rest of the editor behaves.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
