### PR TITLE
Fix `get_breakpointed_lines` crashing Godot

### LINKED ISSUE #60668: Executing `CodeEdit.get_breakpointed_lines` crashes Godot
### Godot version

4.0.alpha.custom_build. cbdc33bcf

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

When executing
```
func _process(delta):
	var temp_variable3767 = CodeEdit.new()
	add_child(temp_variable3767)
	temp_variable3767.undo()
	temp_variable3767.menu_option(2)
	temp_variable3767.cut()
	temp_variable3767.paste()
	temp_variable3767.remove_gutter(0)
	temp_variable3767.remove_gutter(0)
	temp_variable3767.get_breakpointed_lines()
```

Godot crashes with this backtrace
```
ERROR: Index p_index = 0 is out of bounds (size() = 0).
   at: get (./core/templates/cowdata.h:156)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.0.alpha.custom_build (cbdc33bcf73090962e60c1cf5ee50a21b29e4bad)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f3e8bbaf520] (??:0)
[2] CowData<TextEdit::Text::Gutter>::get(int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/cowdata.h:156 (discriminator 7))
[3] Vector<TextEdit::Text::Gutter>::operator[](int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/templates/vector.h:92)
[4] TextEdit::Text::get_line_gutter_metadata(int, int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/text_edit.h:226)
[5] TextEdit::get_line_gutter_metadata(int, int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/text_edit.cpp:4861)
[6] CodeEdit::is_line_breakpointed(int) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/code_edit.cpp:1224)
[7] CodeEdit::get_breakpointed_lines() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/code_edit.cpp:1238)
[8] void call_with_variant_args_retc_helper<__UnexistingClass, Array>(__UnexistingClass*, Array (__UnexistingClass::*)() const, Variant const**, Variant&, Callable::CallError&, IndexSequence<>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:705 (discriminator 4))
[9] void call_with_variant_args_retc_dv<__UnexistingClass, Array>(__UnexistingClass*, Array (__UnexistingClass::*)() const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:501)
[10] MethodBindTRC<Array>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:582)
[11] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:839 (discriminator 1))
[12] Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/variant_call.cpp:1021)
[13] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1544)
[14] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1543)
[15] bool Node::_gdvirtual__process_call<false>(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:235 (discriminator 5))
[16] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:57)
[17] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:45 (discriminator 14))
[18] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:850)
[19] SceneTree::_notify_group_pause(StringName const&, int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:855)
[20] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:456)
[21] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2722)
[22] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:441)
[23] godot4(main+0x16c) [0x23a6ab2] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:70)
[24] /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7f3e8bb96fd0] (??:0)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f3e8bb9707d] (??:0)
[26] godot4(_start+0x2e) [0x23a688e] (??:?)
-- END OF BACKTRACE --
================================================================

```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by pfertyk**
Fixes #60668.

### CODE REVIEW

**Comment by Geometror** [comment]
CC @Paulb23

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Ah, not sure I missed this, but, `gutters.size()` should be identical to `text[p_line].gutters.size()`. However, `[add|remove]_gutter` loops over every line in both `TextEdit` and `TextEdit::Text` so we end up removing the same amount of gutters as there are lines.

Probably best to remove the loops in `TextEdit` not `TextEdit::Text`. Might also be worth adjusting the test cases to catch this in the future.

**Comment by pfertyk** [comment]
@Paulb23 I think I've found the loops you mentioned. It seems that `TextEdit` was looping over the lines, and then `TextEdit::Text` was doing the same thing, at least when adding and removing gutters ;)

Could you check the code again? If this is the solution you wanted me to implement, I'll check if I can update the test cases as well ;)

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by pfertyk** [comment]
So ... should I add tests for this? ;) I was waiting for the confirmation about the solution, but it got merged so fast :D

**Comment by Calinou** [comment]
> So ... should I add tests for this? ;) I was waiting for the confirmation about the solution, but it got merged so fast :D

Feel free to open a pull request to add more tests :slightly_smiling_face:

**Pull request merged**
