### PR TITLE
Add shape cast 3d.

### LINKED ISSUE #710: Add ShapeCast3D node for collision sweep and immediate overlap queries (already implemented in 2D)
See the 3D version of this proposal at #2896.
Aims to supercede #72, #709.
Helps #740, #2577.

### Describe the project you are working on:

[Goost](https://goostengine.github.io/) - Godot Engine extension

### Describe the problem or limitation you are having in your project:
Ray casting is not as flexible or robust when it comes to detecting collision bodies along the ray cast area/volume (can easily miss objects, for example beam weapons which has a notion of width of a beam, which raycast doesn't have). For that one needs to cast multiple ray cast in the same direction, which is a hacky thing to do.

It's also difficult to get collision overlaps with `Area2D/3D` and often requires waiting a couple of frames before collision information is available to these nodes, when immediate information is preferable. One can use signals for that, but that mostly leads to inconveniences because you have to ensure that no duplicate bodies is detected within the signal callback, and you need to collect a list of overlapped bodies manually. Using the low-level direct space state API is the only way to fetch immediate overlap information which is robust (with or without shape sweep test), but again it's quite cumbersome to use for most users.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation:
Creating `ShapeCast2D` and `ShapeCast3D` analogously to `RayCast2D` and `RayCast3D` nodes. Ability to assign any existing `Shape2D` or `Shape3D` is enough for this to overcome limitations of ray casting.

### Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:
I've managed to implement this via C++ modules in [Goost](https://github.com/goostengine/goost), and replaced some GDScript classes already with it in my own projects.

#### Editor view

godot-shape-cast-2d

#### Inspector

godot-shape-cast-2d-inspector

#### API

godot-shape-cast-2d-api

The implementation is based on `RayCast2D` (copy-pasted and adapted), uses `PhysicsDirectSpaceState.cast_motion` along with `PhysicsDirectSpaceState.get_rest_info` internally, so in most cases it reflects `RayCast2D` API, with the following differences:

* obviously you need to assign any `Shape2D` resource before using. For 2D, `CircleShape2D` can be possibly instantiated by default.
* ability to configure collision `margin` for shapes.
* casting can work with `cast_to == Vector2()`. In this case, such node can be used as a general-purpose, (continuous) collision detection area which can overcome limitations of `Area2D`. Immediate information can be forced with `force_shapecast_update`. Quite similar to [PhysX Overlaps](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/SceneQueries.html#overlaps). Can also help workaround CCD issues: godotengine/godot#9071.
* can return multiple results (the number of results is limited by `max_results` property for performance reasons). `get_closest_*` methods should be used instead if you come from `RayCast2D`. See also [PhysX closest hit](https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/SceneQueries.html#closest-hit).
* exposed `collision_result` as a property so that if there's a need to fetch more collision information not provided by the API by default (collider's `linear_velocity`, `metadata` etc).
* `get_closest_collision_safe/unsafe_distance` used for querying the intersections exactly outside/inside collision. You can move the shapecast along safe distance to repeat the process from that point without the node being stuck inside the collider, for instance.
* the `ShapeCast` node's own transform can be modified to alter the shape in any way by translating, rotating and scaling.

### If this enhancement will not be used often, can it be worked around with a few lines of script?:
Cannot be worked around with a *few lines* of script.

### Is there a reason why this should be core and not an add-on in the asset library?:
There's no particular reason why this should be part of the core. This can be implemented via plugin/module. Performance is the only reason why this might be needed for core. Some engines like Unity already provide similar functionality though, also the mentioned PhysX library.

In fact, given the same logic, the existing `RayCast` nodes *can* also be re-implemented via script.

If you think it's worth adding an entire `ShapeCast2D/3D` to Godot core and you feel like the described implementation is logical/fits the requirements, I can make a PR, but additional work is needed to port this to 3D.

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot-proposals/issues/710

Todo: 
- [ ] Generate preview 3d mesh using triangulate shape meshes.
- [ ] Generate demo project https://github.com/V-Sekai/godot-shape-cast

*Bugsquad edit: 3D counterpart of https://github.com/godotengine/godot/pull/54803.*

### CODE REVIEW

**Comment by Zireael07** [comment]
Bump. Any news?

**Comment by elvisish** [comment]
A couple of shapecast examples here, would be amazing if this could be done in much fewer lines of code to get the same result: https://github.com/godotengine/godot/issues/2217#issuecomment-1043043731

**Comment by fire** [comment]
I'm not able to work on this as much. Consider this salvageable.

**Comment by elvisish** [comment]
I wonder if shpaecast 3D could just be a high level wrapper for direct space queries? Godot has everything needed to do the casting, it just needs to be packaged up in much more user friendly syntax.

**Comment by fire** [comment]
Yes. this is what this pr does.

**Comment by fire** [comment]
Superseded by: https://github.com/godotengine/godot/pull/63161

**Pull request closed without merging**
