### PR TITLE
Fake a newline at the end of GDScripts while tokenizing

### LINKED ISSUE #28151: Debugger doesn't show local variables if debug line is the last line of file
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 7 x64

**Steps to reproduce:**
1. Make function with some local variables,
2. Make breakpoint in **the last line of file**,
3. Run project

**Result:** there are no local variables in debugger window 
bug1

**Expected:** variables are displayed

**Note:** if you add one line, even empty one (which makes debugger line is not last of file) - variables are displayed in debugger
bug2

**Minimal reproduction project:**
You should put break point in the last line of script file, run project and you will see than there are no local variables in debugger
[18042019.zip](https://github.com/godotengine/godot/files/3092845/18042019.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #28151

Probably not the best solution, but likely the easiest :confused:.

### CODE REVIEW

**Comment by vnen** [comment]
Wouldn't be enough to simply inject a new line opcode in the compiler?

**Comment by bojidar-bg** [comment]
@vnen well, that won't be enough, since the StackDebug lists emitted by the compiler need to have proper lines (currently it lists the variables as exiting scope on that last line, that why it breaks).

**Comment by akien-mga** [comment]
What's the state on this PR?

**Comment by bojidar-bg** [comment]
I still think it is not done as it should be, so I will have to rework it at some point. Not sure when I'll be able to, though.

**Comment by akien-mga** [comment]
> Potentially, it could be closed + tagged "salvageable".

Doing that for now then to reduce PR backlog :)

**Comment by aaronfranke** [comment]
Removing "salvageable" since Godot 3.2 automatically inserts the final newline at the end of GDScript files, so there's no need to have fake one.

**Pull request closed without merging**
