### PR TITLE
iPhone X support and iOS-related fixes

### LINKED ISSUE #17358: launch screens should be optional for iOS export.
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

Set each launch screens one by one is time consuming for fast test project. And for the exported project users may prefer to use launch screen file instead of launch image. 

**Steps to reproduce:**

**Minimal reproduction project:**

### LINKED ISSUE #17428: x86_64 iOS template crashes in simulator
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

exported iOS project can not test on simulator.

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by endragor**
Starting from April 2018 Apple no longer accepts apps that do not
support iPhone X. For games this mainly means respecting the safe area,
unobstructed by notch and virtual home button. UI controls must be
placed within the safe area so that users can interact with them.

This commit:

- Adds OS::get_window_safe_area method that returns unobscured area of
  the window, where interactive controls should be rendered.

- Reorganizes how launch screens are exported - the previous way was
  incorrect and modern iPhones did not pick up the correct screens and
  because of that used a non-native resolution to render the game.

- Adds launch screen options for iPhone X.

- Makes launch screens optional in the export template. If not
  specified, a white screen will be used.

- Add App Store icon (1024x1024) export option as it now has to be
  bundled with the app instead of being provided in iTunes Connect.

- Fixes crash when launching games in iOS Simulator. It happened because
  controllerWasConnected callback came before the engine was
  initialized. Now in such case the controllers will be queued up and
  registered after initialization is done.

- Fixes issue with the virtual keyboard where for some reason
  autocorrection panel would intersect with the keyboard itself and not
  allow you to use the top row of the keyboard. This is fixed by
  disabling autocorrection altogether.

Closes #17358. Fixes #17428, #17331.

### CODE REVIEW

**Comment by endragor** [comment]
Travis uses outdated Xcode by default. We need Xcode 9+ with iOS SDK 11 (Apple doesn't accept new submissions built with earlier versions). It seems `osx_image` needs to be set according to instructions here: https://docs.travis-ci.com/user/languages/objective-c/

**Comment by akien-mga** [comment]
@endragor Can you rebase on the master branch to get #18108?

**Comment by endragor** [comment]
@akien-mga done.

**Comment by hpvb** [comment]
cherry picked into 3.0.3

**Pull request merged**
