### PR TITLE
X11 boot screen fills window when maximized

### PR DESCRIPTION
**Pull request by ghost**
In X11 if the engine launches in maximized mode the boot screen will not fill the window. This fixes that bug.

### CODE REVIEW

**Comment by akien-mga** [comment]
Hi @blackwc and sorry for not coming back to you earlier. It looks like their are merge conflicts, could you rebase to handle them if the PR is still relevant?

**Comment by blackwc** [comment]
I'm not sure if it's still relevant. I haven't tested the latest. However, if it is still relevant I'm going to refactor the code so that it's more similar to the establish style.

**Comment by blackwc** [comment]
Alright. I updated. This seems to work for me. I can't confirm if it works on multi-monitors or not.

**Comment by akien-mga** [comment]
It's working great here on X11, but I don't have a multiple monitors to test further.

**Comment by akien-mga** [comment]
Good to merge for me, but I'll let @reduz glance at it.

**Comment by akien-mga** [comment]
We merged a big pull request that removed all trailing spaces in the code, so it introduced merge conflicts with your PR. Could you have a look at rebasing it to solve the merge conflicts?

(then I'll likely merge it, nobody said it would be a bad change so far so I'll assume it's a good change :))

**Comment by akien-mga** [comment]
I'll cherry-pick this one.

**Comment by Calinou** [comment]
I confirm this pull request works, even with multiple monitors, but only with maximized windows, not fullscreen windows.

**Comment by blackwc** [comment]
OK. I fixed the fullscreen issue @Calinou

**Comment by akien-mga** [comment]
As discussed today on IRC:
```
[15:42] <Akien> reduz: WDYT about https://github.com/godotengine/godot/pull/2291 ? It has been around for a while and seems relatively harmless but a "nice to have" for X11
[15:58] <reduz> seems more like a hack, i would probably prefer to fix the problem the right way, though I have no idea why it happens
[15:58] <reduz> in other platforms it works fine as is
[15:58] <reduz> the commands to resize the window are being sent properly to X11, but it seems to take a while until we get the window resized notification
[15:59] <reduz> in other platforms they are received instantly
[16:00] <reduz> i mean, this is a bug in our X11 window management code, i prefer it stays visible until someone who clearly understands more about X11 than I do fixes it properly
```

@Hinsbart maybe? :D

**Comment by Hinsbart** [comment]
uhh :D 
I'll have a look at it when I got some time.
Can't promise anything though, I've got soo much work planned on doing before 2.1 :P

**Comment by bojidar-bg** [comment]
I guess it might be possible now that the pirate locale is added (ea87f0f9d905b0766e489d9f31ce2746d581949a)

<small>_I'm obviously joking, but counts as a "pretty" ping_</small>

**Comment by akien-mga** [comment]
Superseded by #7125.

**Pull request closed without merging**
