### PR TITLE
Fixed renaming/moving of nodes with exported NodePaths in the editor

### LINKED ISSUE #30534: Incorrect dynamic value for exported NodePath after reparenting in Editor
I believe this is a bug in the implementation of #9801

**Godot version:**

3.1.1.stable.custom_build

**OS/device including version:**

Linux

**Issue description:**

When reparenting an object that exports a `NodePath` in the editor, the `NodePath` updates dynamically, but can end up pointing to a nonexistent path.

**Steps to reproduce:**

`Parent.tscn`:

```
Parent (path : NodePath = './Child')
|
| - Child
```

--- 

`World.tscn`:
```
World
|
| - SubWorld1
| | - Parent (path : NodePath = './Child')
| - SubWorld2
| |
```

Drag Parent to SubWorld2:

```
World
|
| - SubWorld1
| |
| - SubWorld2
| | -  Parent (path : NodePath = './Child')
```

Drag Parent back to SubWorld1:

```
World
|
| - SubWorld1
| | -  Parent (path : NodePath = '../../SubWorld2/Parent/Child')
| - SubWorld2
| |
```

Note that the path now incorrect.

out

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/3386197/example.zip)

### LINKED ISSUE #35226: Renaming a node loses nodepath references from that node to children (and vice versa), and references within the branch.
**Godot version:**
3.2 beta5 or any earlier I've tried.

**Issue description:**
When renaming a node that has node path references to children nodes (any nested inside), those references are kept after first rename, but renaming it again loses the references - they are left pointing at the situation after the first renaming. In addition to the renamed node losing its references, it also happens for the kids: any nested child node referring to the renamed node (by nodepath) loses the tie - exactly in the same way as above (after 1st works, after 2nd broken). 
**Edit:** #30534 seems very related. Note also that the situation "breaks" (internally?) already after the first renaming. Before that it works, after that, no more renaming support.

**Steps to reproduce:**
- Create a node with a script that has an export variable of NodePath type (or use an internal node that uses those): `export(NodePath) var my_path`
- Duplicate that node and move it inside the original node - now we have two nodes nested.
- Assign the parent node's `my_path` to the kid, and the kid's `my_path` to the parent.
- Rename the parent node (eg. to `name_after_1st`) and check the situation: Seems refs are correct (by inspector UI look as well as hovering to see the path, as well as trying by script).
- Rename again (eg. to `name_after_2nd`) and check the situation: Now the parent refers to `../name_after_1st/kid` where as the kid refers to `../../name_after_1st`. So both refs are broken.

**Workarounds:**
- I currently have a system that tracks those special nodes (using node path refs) using mostly `_enter_tree` and `_exit_tree` functionality (+ some idle_frame waits and switching scene tabs special hacks). The core of the solution is to split the path into two: path to the common parent and then the sub path from it to the target node. Although this is hacky and annoying and adds boilerplate to each script using node path refs in editor (there are hundreds of them), it works for all cases except renaming the root node - which I haven't found a solution for. A tiny bit related is #35222 (problems on changing type of the root node). 

**Notes on the above workaround for renaming and moving (copied from the script):**

Background:
- When a node is moved, Godot will automatically update its new location to any node in the scene that refers to it (by NodePath).
- Problem is that, if the updated node is moving as well, the new location will be wrong (it should not be updated at all).

Solution:
1. We can use the ancestor part of the updated node path to get the common parent. Eg. in "../../../something/new_location", the "../../../" gives us the common parent.
2. We split the path at the common ancestor. Upon exiting we store the common ancestor as a node + then the sub path down from it.
3. Upon entering, we get the stored common parent and sub path, get the node at the sub path, and update the NodePath ref by getting path to that sub node.

**Update:**
The scope of the issue seems to be larger: Renaming a node, will break all node path references that point **from within** the node **to within** the node. So in the scenario below, `NodeWithNodePath` has a export(NodePath) variable reference to `TargetNode`, and renaming the container `NodeToRename` will break this path - in the way described above.
```
> NodeToRename
> NodeToRename > NodeWithNodePath
> NodeToRename > TargetNode
```
Potential solution:
If Godot really stores the paths as relative, then the solution would be to simply skip the renaming procedure for nodes that are within the renamed node (children or grand-children) - as they were correct, no smart-renaming needed.

### LINKED ISSUE #42277: Exported NodePath reference invalid if referencing node is moved up/down the node hierarchy
**Godot versions:**
3.2.2, 3.2.3 and master 215fa6e85b8a22e75081190293460f720291f6a5

**OS/device including version:**
Windows 10

**Issue description:**
Basically what the title says. Exported NodePaths won't get updated if i move them up/down the node hirachy in the inspector. However if i move the referenced Node (in the example below that would be `Path1`) the path gets updated automatically.

I found some open NodePath related issues, but nothing exactly like this (#35226, #34872).
The same issue exists in the master branch, but i can't provide a MRP because of a bug where the node path gets set to null if saving the scene.

**Steps to reproduce:**
Export a NodePath via a script like so:
```
extends Node

export var my_path: NodePath

func _ready():
	print(my_path)
	print(get_node(my_path))
```
attach the script to a node (here called `Receiver`) and set the NodePath (here `Path1`) like so:
ok

Now move `Receiver` into `Container` and the NodePath will be invalid:
broken

**Minimal reproduction project:**
[NodePathBug.zip](https://github.com/godotengine/godot/files/5269587/NodePathBug.zip)

### PR DESCRIPTION
**Pull request by mbrlabs**
Fixes #42277
Potentially also fixes #35226, but haven't tested that yet.

*Bugsquad edit:* Fixes #42277, fixes #35226 and fixes #30534

### CODE REVIEW

**Comment by mbrlabs** [comment]
I just tested if this fixes the other issue i linked and it does not. However, this is closley related, so i MIGHT be able to fix it as well over the weekend. Please don't merge until then ;)

**Comment by mbrlabs** [comment]
So i integrated the fix in #35319 into this PR since they are conflicting. 
This PR now fixes #42277, #35226 and #30534

I did test this pretty thoroughly and it seems solid. @KoBeWi maybe you could test this as well if you have time

**Comment by KoBeWi** [comment]
I moved nodes around a bit and seems like the path remains correct with all common operations. It's still possible to break it with e.g. Make Scene Root, but it's probably not important for now (the linked issues don't mention it).

**Comment by mbrlabs** [comment]
@akien-mga Bump :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
