### PR TITLE
Fix #64975 by introducing a new initialization level. 

### LINKED ISSUE #64975: 4.0 GDExtension: global_get_singleton not returning expected singletons.
### Godot version

v4.0.alpha.custom_build.0c5f25495

### System information

Ubuntu 22.04 Vulkan

### Issue description

I'm writing a set of GDExtension/GDNative Go bindings ans attempting to load all of the global singletons. I have tried loading them both at level 3 initialization time (`GDNATIVE_INITIALIZATION_EDITOR`) and/or when `_ready` is called on a extension class. A select number of them fail to load and while I expected that Javascript and JavaClassWrapper fail because they require certain environments. I did not expect the Server types to fail.
```
ERROR: Failed to retrieve non-existent singleton 'JavaClassWrapper'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'JavaScript'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'DisplayServer'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'RenderingServer'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'AudioServer'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'PhysicsServer2D'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'PhysicsServer3D'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'NavigationServer2D'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'NavigationServer3D'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'XRServer'.
   at: get_singleton_object (core/config/engine.cpp:251)
ERROR: Failed to retrieve non-existent singleton 'CameraServer'.
```
I might add that calling `Engine.get_singleton("DisplayServer")` for example, does work from GDScript. Is there something special about these 'Server' singletons? How is the initialization for these singletons meant to work from GDExtension?

### Steps to reproduce

Call `global_get_singleton` on a `GDNativeInterface` with any of the failing cases shown in the Issue Description.

**Example**
```c
p_interface.global_get_singleton("DisplayServer")
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Splizard**
Previously, GDExtension libraries would fail to return Server singletons
'global_get_singleton' at any initialization level #64975 (they were registered at the very end of setup2). 

This enables Server singletons to be retrieved at the 'new'
GDNATIVE_INITIALIZATION_COMPLETE.

### CODE REVIEW

**Comment by Splizard** [comment]
Looks like the singletons are returning as nil, so perhaps this isn't quite the fix that is needed. Happy to have some guidance here.

**Review by bruvzg — DISMISSED** [review]
`register_server_singletons` is already exactly where it supposed to be, you can't register singletons before servers are created and initialized, and the last (navigation server) one is initialized just one line before the current location of `register_server_singletons`.

**Comment by Splizard** [comment]
@bruvzg
got it would a better fix be to introduce a new initialization level for GDExtension (and trigger this at the end of setup2)? or are singletons not meant to be retrievable at extension initialization time.

**Comment by bruvzg** [comment]
I guess the proper way to fix it, is to register each singleton as soon as server is created (from a server constructor), instead of dedicated `register_server_singletons`. This way, availability of servers for GDExtension will be the same as for the engine.

**Comment by Splizard** [comment]
Adding the new initialization level and using it fixes the issue and enables all server singletons to be retrieved. Perhaps `GDNATIVE_INITIALIZATION_READY` should be called something else?

* `GDNATIVE_INITIALIZATION_COMPLETE`
* `GDNATIVE_INITIALIZATION_FINAL`  
* `GDNATIVE_INITIALIZATION_DONE`  

Let me know and I can change this.

**Comment by touilleMan** [comment]
My 2c here: I'd rather introduce a `GDNATIVE_INITIALIZATION_SINGLETONS` step in order to make it obvious where the singleton should be registered (and hence that the singleton cannot be fetched before that !)

I've myself spend quite some time to understand how to fetch a singleton (I thought I was using the API wrong when I was just querying it to soon)

As a more general wish, I think it would be great to add a small comment in `gdnative_interface.h` for each initialisation level to give examples of what kind of extension should be initialized when

**Comment by Splizard** [comment]
Would it be possible to rerun the workflows for this PR? Also please let me know if I should squash my commits (requires me to make a force push to the branch).

**Comment by akien-mga** [comment]
Yes the commits should be squashed. I would also recommend rebasing at the same time so that you get the latest master commits.

**Comment by Splizard** [comment]
Have rebased against master, will this PR and/or fixing #64975 still make it in before 4.0 release?

**Comment by groud** [comment]
We reviewed this PR in the GDextension meeting, and we don't think this is the right solution to the problem. The singletons should be available a lot earlier than what they are right now so adding another initialization level is not the right solution to the issue. Singletons should instead be loaded earlier on.

Since the solution we would prefer is very different from that proposed here, we'll close this PR.  We've also added the corresponding issue to the 4.0 release milestone. Thank you nonetheless.

**Pull request closed without merging**
