### PR TITLE
[3.2] Fixed the inverse(mat3) polyfill for GLES2

### LINKED ISSUE #44171: [3.2] Rotation gizmo outline wrong due to missing inverse function in GLES2
**Godot version:**
3.2.4 beta3

**OS/device including version:**
Windows 10

**Issue description:**
I backported the improved rotation gizmo from @JFonS in #43016, but i just noticed that the circular gray outline around the gizmo is rotated wrongly when using the GLES2 backend. It should always face the camera, but that is not working in GLES2 because it lacks the built-in [inverse ](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/inverse.xhtml) shader function (this should be noted in the [docs](https://docs.godotengine.org/en/stable/tutorials/misc/gles2_gles3_differences.html#shading-language)).

This is relevant part of the shader code: https://github.com/godotengine/godot/blob/364d019fee656ee822a3ac502e89362dd31d0640/editor/plugins/spatial_editor_plugin.cpp#L5410

GLES3:
gles3

GLES2:
gles2

**Solution**
I used a custom `inverse` function based on [this implementation](https://stackoverflow.com/questions/22643604/glsl-es-2-0-inverse-matrix) to fix it in this particular case. A more general approach would be to add a polyfill `inverse` function on the engine level, so it works with all shaders. This is a bit more involved though, because it requires to write versions for `mat2`, `mat3` and `mat4` (probably not worth it). 

If the custom `inverse` function idea sounds good, i can open a PR :)

### PR DESCRIPTION
**Pull request by mbrlabs**
Fixes #44171
Based on: https://github.com/glslify/glsl-inverse/blob/master/index.glsl#L10

CC @clayjohn

### CODE REVIEW

**Comment by Chaosus** [comment]
Of course, I didn't invent this code and now I don't remember where I took this, it either to be GLM: (https://github.com/g-truc/glm/blob/9fcec4bbfac3c539ffa7f36da888a48969daafdf/glm/gtc/matrix_inverse.inl) or NVidia site like (https://developer.download.nvidia.com/cg/inverse.html) or somewhere else... So if it's incorrect then it should be changed - if you check whether the other overloads of this function (for mat2 and mat4 works correctly) that would be appreciated.

**Comment by mbrlabs** [comment]
@Chaosus I can check that later this evening. It's a bit tricky though because it's a shader, but something like `M*M^-1 == I` and then painting something red if it's true should work.

**Comment by mbrlabs** [comment]
So i did some testing: `inverse(mat2)` is correct, but the `mat4` implementation is wrong. The original  `mat3` version also failed the test but with my fix it works. I'm gonna update this PR and add a fix for the `mat4` version as well (probably not today).

This is the test shader i used (canvas item turns red when successful, black otherwise): 

```
shader_type canvas_item;

bool approx(float test_var, float expected) {
	if (abs(expected - test_var) < 0.001) {
		return true;
	}
	return false;
} 

bool test_mat2() { // test successful
	mat2 m = mat2(vec2(1.0, 2.0), vec2(0.0, 1.0));
	mat2 m_inv = inverse(m);
	mat2 i = m*m_inv;

	return 	approx(i[0][0], 1.0) && approx(i[0][1], 0.0) && 
			approx(i[1][0], 0.0) && approx(i[1][1], 1.0);
}

bool test_mat3() { // test successful with my fix
	mat3 m = mat3(vec3(1.0, 2.0, 3.0), vec3(0.0, 1.0, 5.0), vec3(5.0, 6.0, 0.0));
	mat3 m_inv = inverse(m);
	mat3 i = m*m_inv;

	return 	approx(i[0][0], 1.0) && approx(i[0][1], 0.0) && approx(i[0][2], 0.0) && 
			approx(i[1][0], 0.0) && approx(i[1][1], 1.0) && approx(i[1][2], 0.0) && 
			approx(i[2][0], 0.0) && approx(i[2][1], 0.0) && approx(i[2][2], 1.0);
}

bool test_mat4() { // test failed
	mat4 m = mat4(vec4(1.0, 0.0, 0.0, 1.0), vec4(0.0, 2.0, 1.0, 2.0), vec4(2.0, 1.0, 0.0, 1.0), vec4(2.0, 0.0, 1.0, 4.0));
	
	mat4 m_inv = inverse(m);
	mat4 i = m*m_inv;

	return 	approx(i[0][0], 1.0) && approx(i[0][1], 0.0) && approx(i[0][2], 0.0) && approx(i[0][3], 0.0) &&
			approx(i[1][0], 0.0) && approx(i[1][1], 1.0) && approx(i[1][2], 0.0) && approx(i[1][3], 0.0) &&
			approx(i[2][0], 0.0) && approx(i[2][1], 0.0) && approx(i[2][2], 1.0) && approx(i[2][3], 0.0) &&
			approx(i[3][0], 0.0) && approx(i[3][1], 0.0) && approx(i[3][2], 1.0) && approx(i[3][3], 1.0);
}

void fragment() {
	if (test_mat4()) { // replace with test_mat2() or test_mat3() to test these versions
		COLOR = vec4(1.0, 0.0, 0.0, 1.0);
	} else {
		COLOR = vec4(0.0, 0.0, 0.0, 1.0);
	}
}
```

**Comment by mbrlabs** [comment]
Oops, my `mat4` test is wrong (copy paste error). I wrote `approx(i[3][2], 1.0)` instead of `approx(i[3][2], 0.0)`
It actually works! So this is good to go.

**Review by Chaosus — APPROVED** [review]

**Comment by Chaosus** [comment]
ok, then I'll add a [WIP] tag to the PR title - feel free to remove it when you ready

**Comment by mbrlabs** [comment]
@Chaosus Well like i said, all my tests for `mat2`, `mat3` and `mat4` passed. So this is ready to be merged as is as far as i'm concerend :)

**Comment by Chaosus** [comment]
Thanks!

**Pull request merged**
