### PR TITLE
Fix `TreeItem` returning null for the previous item when wrapping is enabled

### LINKED ISSUE #85032: TreeItem get_prev_visible and get_prev_in_tree wrap broken
### Godot version

4.1.3

### System information

Ubuntu

### Issue description

using `TreeItem.get_prev_visible(wrap = true)` and `TreeItem.get_prev_in_tree(wrap = true)` returns `null` when reaching the beginning of the tree, It should instead wrap around when `wrap` is set to true.
It works fine with `get_next_visible()` and `get_next_in_tree()`

*Documentation:*
```

[TreeItem](https://docs.godotengine.org/es/4.x/classes/class_treeitem.html#class-treeitem) get_prev_in_tree ( [bool](https://docs.godotengine.org/es/4.x/classes/class_bool.html#class-bool) wrap=false )

Returns the previous TreeItem in the tree (in the context of a depth-first search) or a null object if there is none.

If wrap is enabled, the method will wrap around to the last element in the tree when called on the first visible element, otherwise it returns null.

[TreeItem](https://docs.godotengine.org/es/4.x/classes/class_treeitem.html#class-treeitem) get_prev_visible ( [bool](https://docs.godotengine.org/es/4.x/classes/class_bool.html#class-bool) wrap=false )

Returns the previous visible sibling TreeItem in the tree (in the context of a depth-first search) or a null object if there is none.

If wrap is enabled, the method will wrap around to the last visible element in the tree when called on the first visible element, otherwise it returns null.
```

*And here is the error:*
Captura desde 2023-11-17 18-39-08

### Steps to reproduce

1 - make a tree
2 - add 2 elements
3 - call get_prev_visible(true) from a button on the currently selected TreeItem
4 - Error

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Jesusemora**
fixes #85032
 `TreeItem.get_prev_visible` and `TreeItem.get_prev_in_tree` don't return null anymore when setting wrap to true.

I have compiled the code and it works.

Here is a test. make sure to select one of the items before pressing the button. if the first item selected is root it will return null.

otherwise pressing the button while an item is selected will allow to navigate through the TreeItems indefinitely, mimicking the behaviour of TreeItem.get_next_visible and TreeItem.get_next_in_tree.
[TestTree.zip](https://github.com/godotengine/godot/files/13404825/TestTree.zip)

### CODE REVIEW

**Comment by AThousandShips** [comment]
You should target `master` not `4.1`, changes can then be cherry picked.

If you need more information about the update process please see: [PR Workflow - Updating your branch](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#updating-your-branch). If wanted I can fix the branch for you.

**Comment by KoBeWi** [comment]
Rebasing on master and force-pushing should fix it.
But generally changing branches means review spam as seen above and I don't think it can be avoided (now it's too late anyway, so could as well finish it).

**Comment by pafuent** [comment]
@Jesusemora if you don't have time to try rebase and force-push as was recommended by @KoBeWi, I can do it for you if GitHub access and permissions let me. If that is not possible, I can create a new PR with this changes and try to add you as author.

**Comment by KoBeWi** [comment]
This PR has been inactive for a year. Feel free to open a new one at this point.

**Comment by pafuent** [comment]
[Here](https://github.com/godotengine/godot/pull/97157) is the PR with the fix code and some new unit tests added by me

**Comment by KoBeWi** [comment]
Superseded by #97157
Thanks for the contribution nonetheless.

**Pull request closed without merging**
