### PR TITLE
[Doc] Fix casing of some C# names

### LINKED ISSUE #9120: InputEventMIDI is incorrectly written InputEventMidi (upper case MIDI instead of Midi)
**Your Godot version:**
4.2.1

**Issue description:**
The `InputEventMIDI` type [in the doc](https://docs.godotengine.org/fr/4.x/classes/class_inputeventmidi.html) is actually called `InputEventMidi`. This is a minor mistake and IDE will easily spot it but the example code is invalid for this reason.

**URL to the documentation page:**

https://docs.godotengine.org/fr/4.x/classes/class_inputeventmidi.html

*I'll open a pull request myself later eventually  if I find the time.*

### PR DESCRIPTION
**Pull request by AThousandShips**
I think I got them all, hard to identify exactly everything

* Fixes: https://github.com/godotengine/godot-docs/issues/9120

### CODE REVIEW

**Review by paulloz — APPROVED** [review]
All of the new names are correct 👍

**Review by skyace65 — APPROVED** [review]
All the names look correct!

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by akien-mga** [comment]
Cherry-picked for 4.1.4.

**Pull request merged**
