### PR TITLE
Add optional background `StyleBox` to `FlowContainer`

### PR DESCRIPTION
**Pull request by conspiracy0**
Minimal change, surprised the ability to do this wasn't already there. Let me know if any naming/style conventions are violated by my changes.

### CODE REVIEW

**Comment by ghmart** [comment]
Containers are for layout only.

Read this https://godotforums.org/d/19091-container-border-and-background and this #30769 for example.

**Comment by conspiracy0** [comment]
The functionality of a FlowContainer cannot be replicated by placing it inside of a PanelContainer, as when the FlowContainer is placed as a child, the FlowContainer's maximum size is set by the PanelContainer's boundaries, nor can the functionality of this PR. 

The desired feature is that the panel texture should grow as a UI element as the FlowContainer dynamically grows bigger, which the current system does not support. If there is some arbitrary design distinction requiring a completely different class in order to have a FlowContainer with a background, then why don't I simply move this functionality into a new class, called, say, PanelFlowContainer?

**Comment by KoBeWi** [comment]
> the FlowContainer's maximum size is set by the PanelContainer's boundaries

PanelContainer does not impose a maximum size, it will always fit to the minimum size of its children. If FlowContainer grows, its parent PanelContainer will also grow, if it has flags set correctly.

Can you share an example scene setup that works with this PR and doesn't work with PanelContainer?

**Comment by Mickeon** [comment]
These kind of additions where it's not clear they're objectively good are usually accompanied by a [proposal](https://github.com/godotengine/godot-proposals) explaining their use-case.

**Comment by conspiracy0** [comment]
Closing until I have a proposal

**Pull request closed without merging**
