### PR TITLE
recolor FlowContainer icons to the same color as Control icon

### PR DESCRIPTION
**Pull request by poyribn**
according to the discussion in issue #62553,
the FlowContainer icons don't get color-adjusted for Light theme
and it's because the color code is off.

to fix this issue, i recolored them to be the same icon as the Control icon,
an icon that i already know Does get recolored for Light theme.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Hey, you need to have new lines at the end of the files to pass all the checks. Normally, graphics editors don't add any, so you have to edit the files manually after you change them with a tool.

**Comment by akien-mga** [comment]
I found an extra icon with the same color, I think it should also be changed maybe:
```
$ rg 8eef97 -l
editor/icons/icon_h_flow_container.svg
editor/icons/icon_theme_remove_all_items.svg
editor/icons/icon_v_flow_container.svg
```

For context, the `#8eef97` color is the new fill color for Control icons in the 4.0 theme, but indeed in `3.x` it should be `#a5efac`. I should keep this in mind when cherry-picking new icons to `3.x`.

**Review by akien-mga — APPROVED** [review]
Seems good to merge. But as I mentioned there's a third icon which would be worth fixing in the same commit.

**Comment by Sosasees** [comment]
if i add the third icon, ``editor/icons/icon_theme_remove_all_items.svg`` — which is a rainbow icon instead of just _Control_-colored, into the same commit, the title "recolor FlowContainer icons to the same color as Control icon" no longer makes sense. i could amend the commit to change the title, but i won't because of this:

i want to merge this pull request as it is now.
i will fix the rainbow icon as a new commit since this removes my fear of messing up this existing commit.

**Comment by akien-mga** [comment]
Alright, if the theme icon is rainbow color then maybe it's not meant to be remapped at all in the first place, so it's probably fine to leave it as is.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
> Alright, if the theme icon is rainbow color then maybe it's not meant to be remapped at all in the first place, so it's probably fine to leave it as is.

It has both a rainbow bit and a control-colored bit. It should be fixed as well (and it's my fault in the first place, sorry).

**Comment by Sosasees** [comment]
after a bit of research, i found [this list of icon color codes](https://github.com/godotengine/godot/blob/b9f2e57d6240346f1833fd0390de195c956299e7/editor/editor_themes.cpp#L122-L184).
since the _Control_ icon color in Godot 3 is ``#a5efac`` and this list also shows the _Control_ color to be ``#a5efac``, i am confident that it is the Godot 3 version of the list and not the Godot 4 version.

i am about to use this table to convert ``editor/icons/icon_theme_remove_all_items.svg`` to the right colors.

**Pull request merged**
