### PR TITLE
GDScript: Don't highlight unexposed classes

### LINKED ISSUE #19834: Script editor indicates certain classes exist that don't seem to be there
Godor Version 3.0.3

This happens for certain EditorPlugin classes, they do exist in C++ form in the Godot source, but when one tries to access/extend them from GDscript there's trouble.

When entering the name of the class in the script editor it turns green, this only seems to happen for valid classes, which indicates that the class is available, yet when I try to extend it I get the following message:

` built-in:1 - Compile Error: Unknown class: 'CanvasItemEditorPlugin'`

This happens for a bunch of EditorPlugin classes eg:

- Path2DEditorPlugin
- CanvasItemEditorPlugin
- CollisionPolygon2DEditorPlugin
- ...

The documentation of these classes when retrieved from the editor also turns up nonexistent.

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #19834

### CODE REVIEW

**Comment by HolonProduction** [comment]
Using those names as `class_name` seems to work just fine, GDNative class name restrictions don't really seem relevant to GDScript highlighting IMO

**Comment by HolonProduction** [comment]
Now I wonder why it works with `class_name` :thinking: Seems a bit inconsistent

**Comment by HolonProduction** [comment]
image
Hmmmm I don't know what I did but all of a sudden it does not produce the error anymore

**Comment by dalexeev** [comment]
Nevermind, this is a bug in my test project. To some extent, it _should_ work, because we have the following check:

https://github.com/godotengine/godot/blob/92e51fca7247c932f95a1662aefc28aca96e8de6/modules/gdscript/gdscript_analyzer.cpp#L6216-L6218

But still, naming a class or other identifier as a native class (whether it's exposed or not) is a bad idea, the user risks encountering strange bugs, since scopes and shadowing are not implemented very well.

**Review by dalexeev — APPROVED** [review]
> To be honest I'd just emit a warning if a user is doing that, and keep it out of the highlighting. Users won't understand the implication behind it just from highlighting, and if there is a warning I don't feel an extra highlight color would add much value.

I think this makes sense. As far as I understand, the current assumption is that shadowing unexposed classes should work (and it does work to some extent, despite possible issues). If we decide to limit this, then we shouldn't rely on syntax highlighting alone. And we can always revisit syntax highlighting in the future.

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
