### PR TITLE
Use `SceneStringName` in more places

### PR DESCRIPTION
**Pull request by AThousandShips**
Mainly cases involving `text_submitted` but a few other stragglers as well

### CODE REVIEW

**Review by Mickeon — APPROVED** [review]
Sometimes I wonder if this is actually faster, but this change is consistent with the codebase and doesn't affect surrounding code.

**Comment by AThousandShips** [comment]
It will unconditionally be faster than raw strings, and saves memory compared to `SNAME`

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
