### PR TITLE
Fix default NodePaths saved in scene

### LINKED ISSUE #91591: [4.3dev] Exported node path in child scene are reflected in the parent scene file
### Tested versions

- Reproductible in any 4.3 dev

### System information

macOS Monterey 12.6.5

### Issue description

Exported nodes in a child scene will be reflected in the parent scene file when saving a scene, BUT only if the parent scene is opened in the editor.

### Steps to reproduce

- Create an empty scene called MyLevel
-  Create a scene called Menu. Create a node with a script that exports some other nodes from the same scene (example: `@export var nodes: Array[Label]`)
-  Instantiate the Menu scene in MyLevel as a child scene
-  Keep both scenes open in the editor and save
-  Using an external tool (VSCode, vim, cat, etc...), inspect the MyLevel scene and observe that exported nodes from Menu are reflected in the MyLevel file

image

### Minimal reproduction project (MRP)

[exported-node-issue.zip](https://github.com/godotengine/godot/files/15213582/exported-node-issue.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #91591

I spent whole day writing tests for both #91591 and #82670
In the end it turned out that disabling #83343, or at least part of it, fixes both issues. I don't know what to think about it, maybe I'm missing something.

Putting as draft. If it's a correct solution I assume more code needs to be removed.

### CODE REVIEW

**Comment by Cronos87** [comment]
Maybe it would be good to ask @warriormaster12 to try this MR; it could help to make progress on it?

That would be beneficial to prevent regression on #83343.

**Comment by warriormaster12** [comment]
I can certainly give it a look however I'm not sure if I'm going to be able to give any useful input on the matter since my understanding of the code is as much as I touched.

**Comment by warriormaster12** [comment]
Hmm the assumption that I made in ```property_utils.cpp``` in regards of affecting duplication was wrong. Duplicating a node still works even without if check. The only thing that changes is an ability to revert exported Node values in  ```my_level.tscn``` provided by @Cronos87. Reverting them does nothing. Other variable types don't allow you to revert values in an instantiated  scene unless a user has changed the values. 

However, if this only causes a cosmetic inconsistency then I don't see an issue in reverting the change.

image

**Comment by KoBeWi** [comment]
Pushed a solution that doesn't break reverting.

**Comment by akien-mga** [comment]
There's a shadowing warning:
```
2024-06-02T09:13:55.7158314Z In file included from tests/test_main.cpp:115:
2024-06-02T09:13:55.7160011Z ./tests/scene/test_node.h: In function 'void TestNode::DOCTEST_ANON_FUNC_6591()':
2024-06-02T09:13:55.7446392Z ##[error]./tests/scene/test_node.h:526:9: error: declaration of 'child' shadows a previous local [-Werror=shadow]
2024-06-02T09:13:55.7448644Z   526 |   Node *child = ps->instantiate(PackedScene::GEN_EDIT_STATE_MAIN);
2024-06-02T09:13:55.7449569Z       |         ^~~~~
2024-06-02T09:13:55.7451191Z ./tests/scene/test_node.h:498:8: note: shadowed declaration is here
2024-06-02T09:13:55.7452605Z   498 |  Node *child = memnew(Node);
2024-06-02T09:13:55.7453464Z       |        ^~~~~
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Cronos87** [comment]
Many thanks for the fix and review! 🙏

**Pull request merged**
