### PR TITLE
Vulkan: loader, headers, and glslang updated to sdk-1.2.162.0

### PR DESCRIPTION
**Pull request by jacobcoughenour**
Updated glslang and Vulkan headers/loader following the instructions found in thirdparty/README.md.

glslang was updated to the 'known good' matching Vulkan SDK version 1.2.162.0.  
Vulkan headers and loader were updated to the commit tagged for sdk-1.2.162.0.

'vk_mem_alloc.h' and 'vk_mem_alloc.c' are unchanged since there hasn't been a new tagged release since 2.3.0.
The fix-mingw-snprintf patch in glslang was not applied in the previous update (#42817).  Assuming this was a mistake, I re-applied the patch.

Here are the relevant Vulkan SDK release notes:
https://vulkan.lunarg.com/doc/sdk/1.2.162.0/windows/release_notes.html

### CODE REVIEW

**Comment by jacobcoughenour** [comment]
I just noticed the typo in my branch name (126 should be 162).  I don't want to make it look like I'm spamming with an identical PR so let me know and I'll open a new one with the correctly named branch: jacobcoughenour:vulkan-sdk-1.2.162.0

**Comment by akien-mga** [comment]
> I just noticed the typo in my branch name (126 should be 162). I don't want to make it look like I'm spamming with an identical PR so let me know and I'll open a new one with the correctly named branch: jacobcoughenour:vulkan-sdk-1.2.162.0

It's fine, the branch name doesn't matter much as long as the commit itself is correct.

**Comment by akien-mga** [comment]
> The fix-mingw-snprintf patch in glslang was not applied in the previous update (#42817). Assuming this was a mistake, I re-applied the patch.

@bruvzg Do you know if this patch is still relevant? We do enable `MINGW_HAS_SECURE_API`, but do we sometimes compile without actually having support for those? Or should we try to get a fix upstream?

**Comment by akien-mga** [comment]
@fire Maybe you can give this a try before we merge as your MinGW pipeline often breaks on Vulkan SDK updates.

**Comment by bruvzg** [comment]
> The fix-mingw-snprintf patch in glslang was not applied in the previous update (#42817).

> but do we sometimes compile without actually having support for those?

No, it's supported on all Windows newer than XP. Original issue is probably fixed in upstream by https://github.com/KhronosGroup/glslang/pull/2333, at least I did not encounter any errors with the current master.

**Comment by akien-mga** [comment]
@bruvzg Thanks! @jacobcoughenour You can undo the `fix-mingw-snprintf` patch changes then and remove the patch file (and its mention in `thirdparty/README.md`.

**Comment by fire** [comment]
It's my vacation. So things are slow. I was pinged. I'll see what I can do.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
