### PR TITLE
Fix erroneous `pad_zeros()` warning

### LINKED ISSUE #79195: String::pad_zeros regression with padding less digits than length of string
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 11

### Issue description

Using `String::pad_zeros` on a string containing digits with greater length than the argument `digits` raises the error `Parameter count should be a positive number.` of `String::repeat`, because it is called with a negative parameter.
(Actually this error is not 100% correct, it should be non-negative)

4.0 Code:
https://github.com/godotengine/godot/blob/c8e0bd50c57de91c061866db1de407f2e7a74acd/core/string/ustring.cpp#L4127-L4155

Example: `"2023".pad_zeros(2)`
`begin == 0`
`end == 4`
`end - begin < p_digits == false` => No "0" is inserted, the string is returned unchanged.

4.1 Code:
https://github.com/godotengine/godot/blob/ce5c6151fc498b39fe0c188045a4685e0f627854/core/string/ustring.cpp#L4266-L4290

Example: `"2023".pad_zeros(2)`
`begin == 0`
`end == 4`
`zeros_to_add == 2 - (4 - 0) == -2`
=> `s.insert(0, String("0").repeat(-2))` is called => Error.

I don't know why this was changed, but I think ensuring that `zeros_to_add > 0` should be ensured internally and not by the user. If this condition is not fullfilled the string should be returned unchanged as in the 4.0 implementation.

### Steps to reproduce

Try my above mentioned example in 4.0 and 4.1

### Minimal reproduction project

Not necessary.

### PR DESCRIPTION
**Pull request by MewPurPur**
Fixes #79195

### CODE REVIEW

**Comment by dalexeev** [comment]
I think it makes sense to add test cases for this.

**Comment by MewPurPur** [comment]
Nice idea, doned.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.

**Pull request merged**
