### PR TITLE
Make `SyntaxHighlighter::get_text_edit` a const function

### LINKED ISSUE #75773: Should _get_line_syntax_highlighting(line) in SyntaxHighlighter be a const function while get_text_edit() is not?
### Godot version

4.0

### System information

Linux Mint

### Issue description

`_get_line_syntax_highlighting(line)` is declared as a const function. But when using GDExtension, it needs to call `get_text_edit()` which is not a const function. 
Link with: https://github.com/godotengine/godot-cpp/issues/1084

### Steps to reproduce

Try to use `get_text_edit()` from `_get_line_syntax_highlighting(line)` in a GDExtension.

### Minimal reproduction project

Not needed.

### PR DESCRIPTION
**Pull request by 3deathtoll**
fixes #75773

### CODE REVIEW

**Comment by YuriSizov** [comment]
You also need to update the cpp file.

**Comment by dalexeev** [comment]
> You also need to update the cpp file.

As well as documentation (add a qualifier to xml manually or via `--doctool`).

**Comment by YuriSizov** [comment]
It seems that you've been using the web UI to make the edits. You will have to squash your commits now (you can refer to [this documentation](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase)). For this you will have to use a local version of git.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks, and congrats on your first merged pull-request!

**Pull request merged**
