### PR TITLE
Fix build for Javascript platform

### PR DESCRIPTION
**Pull request by muiroc**
with c2abf1a4e93d2870ddecb2e7e7c80ba3f8be3397 I'm getting this build error:
platform\javascript/os_javascript.h:38:10: fatal error: 'unix/os_unix.h' file not found

Still not finished building (43%) but that should be it!

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks, seems good. Could you order includes alphabetically though? `clang-format` is going to complain :)

**Comment by muiroc** [comment]
@akien-mga done! I always forget...

**Comment by akien-mga** [comment]
You can install the pre-commit hooks to be on the safe side ;) https://github.com/godotengine/godot/tree/master/misc/hooks

**Comment by muiroc** [comment]
perfect! will do, thanks

**Pull request merged**
