### PR TITLE
Fix vertical alignment of editor version `LinkButton` in the bottom panel

### LINKED ISSUE #88196: The editor version `LinkButton` isn't centered vertically
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 14.2.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

When using non-default content margins for `Button` in a custom theme the `LinkButton` with the editor version doesn't stay centered vertically because the alignment of its parent `VBoxContainer` isn't set to "Center". Instead it uses a dummy control for vertical spacing, which doesn't work for arbitrary `VBoxContainer` height:

image

This is easy to fix by setting `VBoxContainer`'s alignment to center and getting rid of unnecessary `Control`:

image

I can open a PR

### Steps to reproduce

Make a custom editor theme with non-default top/bottom content margins for the `Button` node

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by passivestar**
Closes #88196

### CODE REVIEW

**Comment by passivestar** [comment]
Alternatively I can get rid of the `VBoxContainer` altogether and align the `LinkButton` itself, it's one less node:

image

**Comment by passivestar** [comment]
Removed the box container

https://github.com/godotengine/godot/assets/60579014/5088b125-5463-4e65-9fa4-9abc8df4142e

**Comment by passivestar** [comment]
Took another look to make sure this doesn't break anything. Can't find anything trying to reference that box container indirectly, from what I understand it's not common in engine code to do that and it would have been made public if it was of any interest outside of class. Seems safe to remove

So I think this is ready for review

If relevant here's a theme that sets `Button`'s top and bottom margins to abnormally high values for testing (it will make the bottom panel higher):
```
[gd_resource type="Theme" load_steps=2 format=3 uid="uid://dup750ctlh6cd"]

[sub_resource type="StyleBoxEmpty" id="StyleBoxEmpty_s86oa"]
content_margin_top = 40.0
content_margin_bottom = 40.0

[resource]
Button/styles/normal = SubResource("StyleBoxEmpty_s86oa")
```

**Review by akien-mga — APPROVED** [review]
Looks good to me. Needs a rebase.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
