### PR TITLE
Improved and added some icons

### PR DESCRIPTION
**Pull request by djrm**
Also we have a little dilemma and maybe you can help

which icon would you like to see when files cant get imported due to errors?
(❤️ this PR for option 1)
screenshot from 2017-08-29 15-30-57

(👍 this PR for option 2)
screenshot from 2017-08-29 15-31-53

### CODE REVIEW

**Comment by damianday** [comment]
PR1 looks nicer, but I think PR2 is more obvious of the icons intention.

**Comment by reduz** [comment]
lets go with option 2, because people will complain of option 1, even though I really like it

**Comment by karroffel** [comment]
I think the first is still as clear **and about 6000x cuter**. And let's be real, you want some cuteness in your life when the import fails, don't you? **don't you**? 😋

**Comment by djrm** [comment]
@karroffel absolutely true, that icon is something that will make you remember your first import issue.

**Comment by karroffel** [comment]
It would probably make me want to have *more* import error just to see it again. I really like it. 😄

**Comment by toger5** [comment]
REALLY nice.

**Comment by zinkkrysty** [comment]
Will there be a message about the error? If so, then the meaning conveyed in the icon will just be supplementary, both of them convey the meaning that something is broken with the file/page (but no more than that). Like the 1st icon better though.

**Comment by groud** [comment]
We should add a tooltip when hovering over the broken file (especially if we take the first one) :)

**Comment by QbieShay** [comment]
1 please! It's perfectly clear and it looks a lot nicer :>

**Comment by djrm** [comment]
Become patreons and you can vote on a feature called 'use dead file icon' 😋

**Pull request merged**
