### PR TITLE
Separate property translation from editor translation, move sources to separate godot-editor-l10n repo

### PR DESCRIPTION
**Pull request by timothyqiu**
`editor/translations` now contains three subdirectories:

* `editor`: extracted from `TTR*`/`RTR*` macros.
* `property`: property name (path) and (sub)group names.
* `scripts`: Python extraction scripts.

I kept individual commits so it's easier to review.

The `.pot` and `.po` files in `editor/translations/property` are copied from `editor/translations/editor`. All these files should be re-generated.

### CODE REVIEW

**Comment by akien-mga** [comment]
Pushed an update which actually separates the translation strings for the editor and the property in their respective POT and PO files. So instead of just adding 2M duplicate lines, we now also remove about the same amount (though this is the first sync with the 4.0 strings after keeping it in sync with 3.5, which seems to add around 1500 new strings).

I'm not fully done updating the headers of the new PO files to keep the translators credits.

While working on this though, I'm comforted in the idea that we should probably move the source translation files to a separate repository altogether (i.e. a "working" repo for Weblate, which can contain as many near-1% complete languages as users fancy to add), and only copy the "complete enough" translations (without the location comments), to reduce the diff of each update.

I'm starting to be concerned about the size that translations add to the Git repository with each new commit and massive diff of moving strings around / adding location lines for duplicate entries, etc.

**Comment by timothyqiu** [comment]
> We could have the translations tracked in a dedicated `godot-editor-l10n` repo (like we have https://github.com/godotengine/godot-docs-l10n for the docs), which wouldn't need to include all the actual Godot source code. And then write a script that can be run manually to copy the translations above a certain completion ratio to the Godot repo, with location lines stripped.

Weblate also supports [syncing automatially with a GitHub repository](https://docs.weblate.org/en/latest/admin/continuous.html). With a dedicated repository, this process can be performed safely.

**Comment by akien-mga** [comment]
This is now ready for review, together with the new repo: https://github.com/godotengine/godot-editor-l10n

image

We now have the translations split into three resources, based on the work started by @timothyqiu:
- `editor.pot`: editor interface (`TTR`)
- `properties.pot`: property names (`ADD_PROPERTY`, Project Settings, etc.)
- `classes.pot`: class reference (XML)

The .pot files and source translations, together with the extraction scripts, are in https://github.com/godotengine/godot-editor-l10n

In that repo, each subresource has a `Makefile`, and the process to update strings is:
- Copy .po files from Weblate
- Checkout the latest `master` in the `godot` submodule
- `make update` to update the POT file
- `make merge` to merge the PO files with the new POT file
- Commit the new POT and PO files in godot-editor-l10n
- `make export` to copy the PO files with high enough completion threshold to the `godot` submodule, with:
  * Untranslated and fuzzy strings removed
  * Location and translator comments removed
  * Thresholds are 20% complete for editor/properties and 10% for classes, like before

To minimize successive diffs I've also done the big sync from the 3.5 state of the translation resources to 4.0 in this PR and the godot-editor-l10n. It's less atomic that we like usually but since each step is several millions of LOCs, I squashed some steps.

**Review by akien-mga — APPROVED** [review]
Let's go :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
