### PR TITLE
fix: TouchScreenButton should stop propagating action when button is …

### PR DESCRIPTION
**Pull request by MarianoGnu**
…removed from scene

Looks like an unreported issue, i didn0t find anything on issues

### CODE REVIEW

**Comment by reduz** [comment]
oh wow, nice find. I'm not sure but I think the action there uses a
reference counter, so a proper fix would most likely be to remember if the
button is being pressed and only then call that function

**Comment by reduz** [comment]
see:
https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L325
you must only call this function if the button is actually being pressed ad
the time it' s being erased

**Comment by MarianoGnu** [comment]
ah, that's a good point, didn't check so deeptly, there was a boy on irc with trouble because switching the scene in android made his game mad, but not on desktop.
I discovered it was because of touchscreen not releasing on free.

It already looks correct to me, i'm calling DefaultInput::action_release, so counter is being reduced :)

**Comment by MarianoGnu** [comment]
Ah, now i get it, i'll fix it assap

**Comment by MarianoGnu** [comment]
should be fine now, i'll test to confirm

**Comment by MarianoGnu** [comment]
Not working as expected, action counter is not decreasing...

**Comment by ndee85** [comment]
Oh nice.. I think I discovered this bug too.. Even if I returned back to the menu and then back to game my touchscreen buttons were still stuck.

**Pull request merged**
