### PR TITLE
Correct is_reference attribute in api.json for Reference class

### PR DESCRIPTION
**Pull request by touilleMan**

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

Should this be cherry-picked for 3.2?

**Comment by touilleMan** [comment]
Yes, cherry pick would be good

**Comment by touilleMan** [comment]
yes I think cherry-pick would be good
@karroffel would this change impact the Rust binding ? (you may have put a workaround in your code like I did in godot-python ^^)

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Comment by karroffel** [comment]
The Rust bindings are already special casing this, yes. We'll keep it for now as we want to support custom or older API JSON files too.

https://github.com/godot-rust/godot-rust/blob/067a68f623ace7854cc1cc1ac58d575005657b8a/bindings_generator/src/api.rs#L152-L154

**Comment by jkb0o** [comment]
3.2 C++ bindings won't work with this:
```clang++
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o src/core/Variant.o -c -miphoneos-version-min=10.0 -g -std=c++14 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk -Og -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Variant.cpp
In file included from src/core/Variant.cpp:8:
include/gen/Object.hpp:126:2: error: no template named 'Ref'
        Ref<Reference> get_script() const;
        ^
include/gen/Object.hpp:146:24: error: no template named 'Ref'
        void set_script(const Ref<Reference> script);
                              ^
```

Object.hpp before this fix:
```c++
Reference *get_script() const;
```
Object.hpp after this fix:
```c++
Ref<Reference> get_script() const;
```

**Comment by akien-mga** [comment]
Should I revert the cherry-pick then? It seems a bit too compat-breaking for including in 3.2.3.

**Comment by karroffel** [comment]
I would say the behaviour is correct, the `Object.hpp` will need to `#include <Ref.hpp>` however.

**Pull request merged**
