### PR TITLE
Set project manager to editor theme

### LINKED ISSUE #5184: Project manager font can't be changed.
**Operating system or device - Godot version:**
Xubuntu Linux 14.04 64-bit, freshly compiled Godot from Github.

**Issue description** (what happened, and what was expected):
Project manager font does not change according to font settings from Editor Settings/Global/Custom Font. I would expect it to change after setting 'global' font.

My global font is set and looks like this:
godot_project_manager_font_bug2

In the same time font in Project Manager looks like this:
godot_project_manager_font_bug

### PR DESCRIPTION
**Pull request by Geequlim**
Fix #5184

### CODE REVIEW

**Comment by reduz** [comment]
Ah I already did this

**Comment by Geequlim** [comment]
Feel free to close this to replace with your code :)
2016年6月13日 23:26，"Juan Linietsky" <notifications@github.com>写道：

> Ah I already did this

**Comment by reduz** [comment]
ah wait, I don't understand the PR, I can see you cleaned up creating the theme, but what new functionality is added?

**Comment by Geequlim** [comment]
Creating same themes for editor and project manager with the
`editor_create_theme()` function.

**Comment by akien-mga** [comment]
From what I can see the new ``editor_themes.cpp`` file allows to use the same code to initialize the theme in the editor and the project manager, while previously the project manager had a less extensive (and apparently insufficient) implementation. Looks like a nice code cleanup to me.

**Pull request closed without merging**
