### PR TITLE
Linux: add relaxation to conditions in the joystick check routine

### LINKED ISSUE #37239: Joystick is not recognized; "add_joy_mapping" and "SDL_GAMECONTROLLERCONFIG" do not help
**Godot version:**
3.2.1-stable

**OS/device including version:**
Linux 5.5.8-11 x86_64 GNU/Linux w/ GNOME 3.34.3 on x11

**Issue description:**
* "Joystick" is not recognized in Godot
* "Joystick" is working in Unity as well as several applications running on the same machine
* "Joystick" is recognized by tools like "controllermap", "gamepad-tool", "sdl2-jstest", and "sdl-jstest"

**Steps to reproduce:**
1) Create a new project,
2) add a mesh (or just a node) to the scene,
3) attach a GDScript to the mesh,
4) connect signal "joy_connection_changed" to a callback function with a debug message if something happens, and optionally, set the SDL2 mapping of "Joystick" with "add_joy_mapping" in "_ready()"
5) run the scene in Godot,
5) attach "Joystick" to the machine running the Godot scene,
6) no debug message from the callback function is showing up

**Further description:**
* The "Joystick" converts analog stick signals to USB emulating a joystick (with V-USB and some user code running on a AVR microcontroller). It is working very well in other applications on Windows and GNU/Linux.
* I set (and exported) the environment variable "SDL_GAMECONTROLLERCONFIG" with the corresponding SDL2 mapping, which is even used this way in several Unity applications.
* The SDL2 mapping looks like this:
`03000000c0160000dc05000001010000,v-usb-joy,leftx:a3,lefty:a2,rightx:a0,righty:a1,platform:Linux,`

### PR DESCRIPTION
**Pull request by m6c7l**
This closes https://github.com/godotengine/godot/issues/37239.

### CODE REVIEW

**Comment by akien-mga** [comment]
This code is pretty difficult to parse (even before your changes), I wonder if it could be improved somewhat?

BTW regarding the commit log, you can use "Fixes #37239" or "Closes #37239" in the body of the message so that it closes automatically on merge. Similarly, the first line (commit title) should be kept relatively short, e.g.:
```
Linux: Relax conditions to validate detected joysticks

Fixes #37251.
```

**Comment by m6c7l** [comment]
@akien-mga: Thank you for the advices, and regarding ...

> This code is pretty difficult to parse (even before your changes),

I agree, it is hardly readable, even before the changes, but I tried to be as less invasive as possible. Furthermore, I did not try to normalize every bit of the condition which would imho reduce readability.

> I wonder if it could be improved somewhat?

I think there is a trade-off between readability, logical normalization, and code formatting. In that regard, the changes are imho well belanced.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
