### PR TITLE
Fix pausing issues when using Web Audio samples

### PR DESCRIPTION
**Pull request by adamscott**
Fixes an issue identified by @Maran23 when pausing the game when using sample playback on the Web platform (#91382).

> Sorry for the delay. Tested right now with then newest code, I got another error now when unpausing the game (and therefore all audio as well): image image
https://github.com/godotengine/godot/pull/91382#issuecomment-2175917988

Now, the samples should pause and unpause without any issue.

### CODE REVIEW

**Comment by Maran23** [comment]
Thanks for looking into the issue! With this version I do not experience any crashes anymore!
But I get another error sometimes:

image

Maybe related, but the audio is not always resumed after unpausing it.

**Comment by adamscott** [comment]
@Maran23 How about now? I added a check to make sure that `_source` isn't null before removing an event listener on it.

**Comment by Maran23** [comment]
Now I get this:
image

**Comment by Maran23** [comment]
I created a MRP for the other problem, that a sound that is played right before pausing is not played at all after unpausing.
So what I do is: `Play sound -> Pause -> Unpause -> Sound is not played (Only in Web Browser with Samples)`.

If this is not related we may also create a new issue for it.

When running the project on your OS, you will hear a sound on your right ear and after unpausing also a sound on your left ear.
In the Web Browser, you will not hear the second sound at all after unpausing.

[reproducer.zip](https://github.com/user-attachments/files/15912399/reproducer.zip)
Just run the project, there is nothing more you need to do (and there is only one script).

**Comment by adamscott** [comment]
> When running the project on your OS, you will hear a sound on your right ear and after unpausing also a sound on your left ear.
> In the Web Browser, you will not hear the second sound at all after unpausing.

Oh, I skimmed over this. I'll investigate.

**Comment by Maran23** [comment]
With the newest version, I do not get any errors or crashes anymore after unpausing!
Just the issue I mentioned above is left, which is probably another issue?

**Comment by adamscott** [comment]
> Just the issue I mentioned above is left, which is probably another issue?

Fixed!

**Comment by Maran23** [comment]
I can confirm that the issue is fixed! In my other project (not the reproducer) I get another error now, but everything seems to work still:
image

**Comment by adamscott** [comment]
> I can confirm that the issue is fixed! In my other project (not the reproducer) I get another error now, but everything seems to work still: image

Silly me, I forgot to replace the instance of `getIsPaused()` that I removed in favor of the new `isPaused` boolean.

Fixed!

**Comment by Maran23** [comment]
Can confirm, everything looks (and sounds) good now on my end!

**Review by akien-mga — APPROVED** [review]

**Review by Maran23 — APPROVED** [review]
As written before, looks good and fixes the issues. Code looks good too. Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
