### PR TITLE
Fix bug in Body(2D)SW::add_area

### PR DESCRIPTION
**Pull request by Faless**
Since my patch ( #1691 ) to implement AREA_COMBINE mode a bug was introduced in BodySW and Body2DSW add_area function.

The data structure containing the areas the body was in used to be a SET but was converted to an ARRAY to implement priority.

The rest of the engine though did not check if the body was already inside an area when calling body->add_area. This basically causes the _update_shape signal to add the same area multiple times to the same body object. A very quick test for this is to change the shape of an area in combine mode after _ready (even setting it as the same value it used to be).

If you want a very simple demo project to test both the bug and the patch have a look at:
https://github.com/Faless/add_area_bug

### CODE REVIEW

**Comment by Faless** [comment]
Sorry to bump, this is a very nasty bug with a very easy fix (2 lines of code), can someone have a look a it a give an opinion? I remember @reduz merged my previous patch.

**Comment by akien-mga** [comment]
Wouldn't it be more logical to add this check in the places where add_area is called instead of inside the function?

**Comment by Faless** [comment]
> Wouldn't it be more logical to add this check in the places where add_area is called instead of inside the function?

Yes, I thought about that.

I decided to go for this fix because this is how it used to work before #1691 .

See: https://github.com/godotengine/godot/pull/1691/files#diff-49cb8bade42256f0f8868eada7be6b34L100

Specifically the "areas" variable in ***servers/physics_2d/body_2d_sw.h*** used to be a ***VSet*** which internally does exactly the same procedure when calling insert (doing a _find before actually adding the element) (see ***core/vset.h***).

Of course another solution might be possible but might also end up being a more bug-prone fix when modifying shapes behviours.

**Comment by reduz** [comment]
by looking at the code, I think the problem you might have is that multiple shapes of an area can call the add and remove functions multiple times, which is a problem. The way to solve this is most likely using a reference counter (each time add() is called that it exists, it increments the counter, and each time the area is removed, then the reference counter is decreased, and frees when it reaches zero)

**Comment by reduz** [comment]
try changing it to use a VMap<Area*,int> where int is the reference counter

**Comment by Faless** [comment]
Hi @reduz !
Thank you for your suggestions and sorry if it took me a while to reply.

So, I understand what you are saying regarding having multiple shapes in the same area, that is a problem with the current implementation.

Anyway, my ***original problem*** was another one, I only had ***one shape in each area***, but I realized that when ***updating the shape*** (using set_radius), the code was actually ***creating a new one***.
That was due to the function `CollisionObject2D::_update_shapes_from_children` not properly calling `clear_shapes`. This is fixed in my first commit ( e06fae67e5dc6af9e28a60cc8e02da43b89ed0b0 )

The I moved to fixing the ***problem you mentioned*** (having multiple shapes in the same area).
I first tried to use a VMap but I soon remembered that ***I needed the data to be in a sortable array*** based on the priority (which was quite tricky with a VMap). So I decided to ***keep the current data structure*** (Vector) but ***adding a field to the AreaCMP*** data structure to keep the ***reference count***.
This is done in the second commit ( b6da74d89e88296fb2fff40067deeae354445d69 )

***Sorry for the lengthy post***, I hope I explained myself, if you have any doubt don't hesitate to ask

**Comment by Faless** [comment]
***UPDATE***
I slightly changed the first commit to better fit the coding style.

**Pull request merged**
