### PR TITLE
GDScript 2.0 (again)

### PR DESCRIPTION
**Pull request by vnen**
This one includes and complements the other PR: #39093. Most changes are outlined on that description.

All the things marked as "broken" there are now implemented. This includes type checks, code completion, warnings, language server (although I could not test this), and the mentioned optimizations (constant folding and avoiding allocating an array when `range` is used as a `for` loop iterator).

`setget` is now replaced by properties, implemented as outlined in the proposal: https://github.com/godotengine/godot-proposals/issues/844.

I've tried to do a bunch of tests to find potential issues. I solved a lot of crashes and incorrect behavior along the way and this should be mostly stable. However I won't be surprised if someone can find other crash cases, or infinite loops (especially on completion), or wrong behavior. If you do, please report an issue and I'll solve it when possible.

There are still a lot to improve but this should be at the same level of what it was before (although I know completion is not super great yet, I intend to revisit the code and overall improve the detection and listing).

### CODE REVIEW

**Comment by akien-mga** [comment]
This naturally needs extensive testing and possibly some more code review, but let's merge already to get a wide testing coverage from users of the `master` branch.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Anutrix** [comment]
Weren't we going rename this to GDScript 4.0 to better signify that it's for 4.0? Or was it just some suggestion by someone and was rejected?

**Comment by vnen** [comment]
> Weren't we going rename this to GDScript 4.0 to better signify that it's for 4.0? Or was it just some suggestion by someone and was rejected?

This is just a title for this PR, we don't have an explicit GDScript version number (or you can say that it follows the Godot version).

**Comment by Sslaxx** [comment]
> > Weren't we going rename this to GDScript 4.0 to better signify that it's for 4.0? Or was it just some suggestion by someone and was rejected?
> 
> This is just a title for this PR, we don't have an explicit GDScript version number (or you can say that it follows the Godot version).

Yet we have NativeScript 1.1.

**Comment by strank** [comment]
I have two questions/suggestions regarding the expanded use of StringName:

- Regarding the new literal notation for `&"This is StringName"` - I think there are good reasons why python chooses to use characters as the prefixes for string literals such as `b"bytestring"`. It looks less busy compared to a symbol and it avoids clashing with the use of existing operators `something & &"stringname"`. How about `i"interned string"` or `n"named string"`? (And since all the prefix literals are changing, I would suggest the same for `^` and `$`.)

- The interning of strings in python is actually fully transparent to the user of python. Almost all strings known at compile time are interned, based on certain rules, see for example http://guilload.com/python-string-interning/ and there's no separate class at all. Maybe we could consider that approach for its ease of use? Might still be good to specifically mark strings to be (not) interned.

**Comment by gvekan** [comment]
@vnen I'm working on completion for calls and I don't understand the purpose of:
https://github.com/godotengine/godot/blob/494bf38c76d3070c548a104d56d9f7e164226f1c/modules/gdscript/gdscript_parser.h#L1043
It's the completion_context type when the cursor is in this spot `print(|)`, which makes it weird that it should "List available methods in scope". No completion is implemented for `COMPLETION_METHOD` right now. Can you explain?

I hope it's okay that I ask here, I did because of git blame.

**Comment by vnen** [comment]
@gvekan if the comment contradicts the code then trust the code. This was likely an oversight when I added it since I started with the previous code and it might've worked that way before. Feel free to change it (I don't think that listing methods in scope is relevant because those are usually part of the list of identifiers, so there's not really much use for this kind of completion).

Also, you can open issues and mention me to avoid cluttering this merged PR.

**Comment by elenakrittik** [comment]
I'm implementing a GDScript lexer, and for reference looked at Godot's own tokenizer. In `gdscript_tokenizer.cpp` there's two keywords that appear to be totally unusable: `namespace` and `trait`. After digging a bit into commit history i found this PR which actually introduced both of these, and after a bit of additional search i found two GIPs assosiated with them: [#1566](https://github.com/godotengine/godot-proposals/issues/1566) and [#6416](https://github.com/godotengine/godot-proposals/issues/6416). I wonder if they are kind of ["reserved"](https://doc.rust-lang.org/reference/keywords.html#reserved-keywords) in case GIPs will get approved and someone gets around to actually make use of these keywords?

**Comment by vnen** [comment]
> I wonder if they are kind of ["reserved"](https://doc.rust-lang.org/reference/keywords.html#reserved-keywords) in case GIPs will get approved and someone gets around to actually make use of these keywords?

Yes, they were reserved beforehand with the plans of (eventually) implementing them. This just haven't been done yet.

**Pull request merged**
