### PR TITLE
Fix missing clear for some `set_exclude*` query parameter methods

### LINKED ISSUE #82042: PhysicsTestMotionParameters2D doesn't clear existing RIDs when setting excludes
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Windows 10

### Issue description

PhysicsTestMotionParameters2D does not clear the excludes when setting the array unlike PhysicsRayQueryParameters2D which does, meaning PhysicsTestMotionParameters2D can't be reused. This is true for exclude_bodies and exclude_objects.

https://github.com/godotengine/godot/blob/59139df16e7a10c3b9176f697d23b557af46601e/servers/physics_server_2d.cpp#L478-L482

https://github.com/godotengine/godot/blob/59139df16e7a10c3b9176f697d23b557af46601e/servers/physics_server_2d.cpp#L496-L502

https://github.com/godotengine/godot/blob/59139df16e7a10c3b9176f697d23b557af46601e/servers/physics_server_2d.cpp#L163-L168

### Steps to reproduce

Attempt to set a PhysicsTestMotionParameters2D's exclude_bodies or exclude_objects multiple times. Only new entries are inserted and you can never clear the existing entries.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
* Fixes: #82042

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Makes sense to me.

Slightly concerned about cherry-picking for 4.1 as this breaks the behavior of this API, which users might be using currently to append bodies instead of replace.

But since we don't expose a way to clear the `exclude_bodies`, I think it's worth cherry-picking as there's currently no workaround for 4.1 users (while they can reintroduce the existing behavior by appending with `+=` if it works, or manually preparing a bigger array).

**Comment by AThousandShips** [comment]
Was unsure if it should be added, we can leave it to decide later but I agree that without a way to clear it adding it there too makes sense

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.

**Pull request merged**
