### PR TITLE
Enhanced physical device selection #35397

### PR DESCRIPTION
**Pull request by disks86**
Enhanced physical device selection to use device type and available memory in relation to issue #35397.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Use tabs instead of spaces for indentation.

**Comment by disks86** [comment]
@yeldhamdev didn't realize ide was switching to spaces even though tabs were turned on. Should be resolved in my commit from last night.

**Comment by YeldhamDev** [comment]
You should also squash your commits: https://docs.godotengine.org/en/3.2/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by disks86** [comment]
Ok, I'll have to do it when I get off work.

**Pull request closed without merging**
