### PR TITLE
fixed spacing for script editor script list

### PR DESCRIPTION
**Pull request by toger5**
before:
screen shot 2017-06-04 at 17 58 04
after:
screen shot 2017-06-04 at 17 55 02

### CODE REVIEW

**Comment by vnen** [comment]
The screenshots look like HiDPI is on. Is this issue DPI related?

**Comment by toger5** [comment]
@vnen you are right it might be!
I will check and than adapt with EDSCALE if that is the case!

**Comment by toger5** [comment]
Maybe my solution also is tacky than... and it has to be fixed in the ItemList drawing code where * EDSCALE is missing somewhere

**Comment by toger5** [comment]
this is how it looks when using loDpi:
screen shot 2017-06-04 at 18 31 40
DON'T MERGE YET...

**Comment by toger5** [comment]
any ideas how else to fix it?

**Comment by toger5** [comment]
It is also present in other dpi settings: in loDpi it seems to be only one pixel, midDpi about 3
and hiDpi see screenshot I posted

**Comment by groud** [comment]
Well I guess you'll have to look into the `scene/gui/item_list.cpp` file, this is probably where to look.

**Comment by bojidar-bg** [comment]
> It is also present in other dpi settings: in loDpi it seems to be only one pixel, midDpi about 3
and hiDpi see screenshot I posted

Wouldn't it work if you just override ItemList's VSeperation in the editor theme, setting it to 3 * EDSCALE or something like that?

**Comment by toger5** [comment]
@bojidar-bg currently there is no constant set for vSeperation in editor_theme.cpp but this actually might be a solution. But I think with override you mean adding add_constant_overwrite...
I will try that Thank you!

**Comment by groud** [comment]
Looking for the code within the item_list.cpp, it seems that the minimum size of an element does not take into account the margins needed to draw the background / the selected item background. 
Is that normal behaviour ? I dont know if the margin should shrink if there not enough space available.

**Comment by toger5** [comment]
@akien-mga updated,
the temp colors were drawn based on the style box margins. so bigger margins resulted in overlapping. Now the ten colors are independent to the margin. they just take the minimum size and the vseperation into account to size to the proper size.

**Pull request merged**
