### PR TITLE
Uncheck 'Pressed' if toggle_mode is unchecked

### LINKED ISSUE #22169: Editor 2D Button Inspector: Pressed cannot be checked unless Toggle Mode is checked as well
**Godot version:**
3.1 Alpha
Mac OS X, High Sierra

**Issue description:**
Editor Button Inspector: Pressed cannot be checked unless Toggle Mode is checked as well.

**Steps to reproduce:**
Add a Button to the 2D Scene
On Inspector check Pressed. Does not allow
Check Toggle Mode. Try again check Pressed. Now allows.
Uncheck Toggle Mode. Pressed remains checked. If you uncheck it  you cannot recheck it.

pressedbug 2018-09-16 17_27_01

### PR DESCRIPTION
**Pull request by georgikoemdzhiev**
Closes #22169

### CODE REVIEW

**Comment by georgikoemdzhiev** [comment]
I am not sure why Travis complains here, can somebody help me figure out what I need to do in order to fix the formatting? Thanks :)

**Comment by bruvzg** [comment]
> I am not sure why Travis complains here, can somebody help me figure out what I need to do in order to fix the formatting? Thanks :)

It's showing all required changes in the log: https://travis-ci.org/godotengine/godot/jobs/599741283

```
-	if(!p_on){
+	if (!p_on) {
```
Add spaces here, and remove one on the empty line. Also here's [Code style guidelines](https://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html)

**Comment by georgikoemdzhiev** [comment]
@bruvzg Thanks! It's my first PR :P

**Review by groud — APPROVED** [review]

**Comment by groud** [comment]
Hmm, thinking about it I wonder if this can have side effects. It is unlikely to happen, but if you change the toogle_mode (via script) while pressing the button, the button might be unpressed for no appearent reason.

**Comment by MCrafterzz** [comment]
> Hmm, thinking about it I wonder if this can have side effects. It is unlikely to happen, but if you change the toogle_mode (via script) while pressing the button, the button might be unpressed for no appearent reason.

@groud wouldn't the most neat way to solve it to just hide the pressed property in the editor when toggle_mode is false? This way it keeps it's current values without confusing the user.

**Comment by georgikoemdzhiev** [comment]
> > Hmm, thinking about it I wonder if this can have side effects. It is unlikely to happen, but if you change the toogle_mode (via script) while pressing the button, the button might be unpressed for no appearent reason.
> 
> @groud wouldn't the most neat way to solve it to just hide the pressed property in the editor when toggle_mode is false? This way it keeps it's current values without confusing the user.

I think you are right. It does make more sense to hide the "Pressed" property altogether if the button is in "Toggle" mode

**Comment by aaronfranke** [comment]
@georgikoemdzhiev Can you rebase and squash this PR? See this article for more information: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by georgikoemdzhiev** [comment]
Thank you for the helpful link @aaronfranke . I was able to rebase/squash the commits just fine. I saw my mistake by creating all of those unnecessary commits 😅

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
