### PR TITLE
Process _get_minimum_size() override from script in Container impls

### LINKED ISSUE #35909: _get_minimum_size() is not called for non-abstract containers
**Godot version:**
3.2

**Issue description:**
The `Control` virtual method `_get_minimum_size()` is not called on any scripts that inherit from the existing concrete container types (e.g. `ScrollContainer`, `MarginContainer`, `HBoxContainer` etc). It will only be called if the base class is the generic `Container` class, or any of the other `Control` derived classes.

This especially a problem when implementing custom containers that share functionality with the existing types, and hence use them as a base class.

**Steps to reproduce:**
1. Create a script that uses Control as the base class and implements `_get_minimum_size()`. Add a debug print statement (or breakpoint).
2. Create a scene with a control of type `Container`, and another control with one of the more concrete types, such as `MarginContainer`, and add the script to both of these.
3. When run, only the `Container` will trigger the print.

**Minimal reproduction project:**
[Testing-ContainerMinSize.zip](https://github.com/godotengine/godot/files/4155800/Testing-ContainerMinSize.zip)

### PR DESCRIPTION
**Pull request by staddy**
Fixes #35909

### CODE REVIEW

**Comment by groud** [comment]
I don't think this is a good idea, there is no point in overriding the minimum size provided by the base container. Even if you would need a custom behavior that looks like a built-in container, their positioning of children node (and thus their computation of minimum size) is not mean to be overridden.

You should use the base Container node if you need custom positioning or custom minimum size computation.

**Comment by andy-noisyduck** [comment]
Is it the lesser of 2 evils? It's a pretty funky smell to have an override that only _sometimes_ isn't called by the inherited implementation. My view is that we should either be consistent, or perhaps mark the classes as final (though I think GDScript won't support this?).

If consensus is reached we should also update the documentation to reflect the choice. Right now there is nothing to say you shouldn't use concrete Container classes, but also nothing saying the override won't be called.

**Comment by groud** [comment]
> Is it the lesser of 2 evils? It's a pretty funky smell to have an override that only sometimes isn't called by the inherited implementation. 

This is very frequent in the Godot codebase, doing otherwise would really hurt the performances. Checking, at each call, if a function is overridden would make c++ code almost as slow as using GDscript itself, not only mentioning the fact we would have to check arguments everywhere to be sure the engine is not going to crash due to a badly written override.

> If consensus is reached we should also update the documentation to reflect the choice. Right now there is nothing to say you shouldn't use concrete Container classes, but also nothing saying the override won't be called.

I agree, this should likely be precised in the documentation.

**Comment by mhilbrunner** [comment]
Closing due to the reasons discussed and outliend above.
This is now documented by https://github.com/godotengine/godot/pull/55935

Thanks for contributing!

**Pull request closed without merging**
