### PR TITLE
Fix code completion not working with class_name

### LINKED ISSUE #28002: Auto-compeletion not working in GDScript that use class_name.
**Godot version:**
Version that don't work : https://github.com/godotengine/godot/commit/ad1368a62521a31b574acd8c545795d1b64c447e

Version that work : https://github.com/godotengine/godot/commit/f75b9e62468ba65753f2ce49c02f1a129c08b717

**Issue description:**
If you using class_name in your GDScript, auto-compeletion stop working.
When you delete it, it works again.

### PR DESCRIPTION
**Pull request by lupoDharkael**
Fixes https://github.com/godotengine/godot/issues/28002

### CODE REVIEW

**Comment by lupoDharkael** [comment]
I've tested this with built-in scripts and it doesn't work as intended with https://github.com/godotengine/godot/commit/e56f5d5c910f076fd93af71ada7550f441207f45

https://github.com/godotengine/godot/blob/f137166251c4c734e1fd4d682492168483ccad3f/modules/gdscript/gdscript_parser.cpp#L8317
`self_path` is assigned directly from `p_self_path`, how it is supposed to be an empty string when the script is an internal resource of the tscn?

**Comment by lupoDharkael** [comment]
I've pushes a new commit. Now it checks the condition of built-in scripts and class_name correctly.

**Comment by akien-mga** [comment]
CC @bojidar-bg @vnen

**Review by bojidar-bg — APPROVED** [review]
I guess the changes to PluginScript might break a bit of compatibility (not that there are a lot of pluginscript languages that support completion), but otherwise looks fine.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
