### PR TITLE
Select correct animation on creation of a new one

### PR DESCRIPTION
**Pull request by bncastle**
-  Select the correct animation when creating a new one.
- Removed unneeded new_name variable.

### CODE REVIEW

**Comment by groud** [comment]
Well, the "new_name" variable was not useless, it just avoids having the "New Anim" string defined in two different places in the code (it acts like a constant).
Ok for the other change.

**Comment by akien-mga** [comment]
> Ok for the other change.

Ah my bad, I read that as "Ok for the change" and thus merged it :D

**Comment by akien-mga** [comment]
But I don't think it matters much for performance here, so I think it's fine as is, even if keeping `new_name` would have been good too.

**Comment by groud** [comment]
> Ah my bad, I read that as "Ok for the change" and thus merged it :D

Ah ah it's not that bad, it should not introduce any regression. :)

**Comment by bncastle** [comment]
The "New_Anim" string should really be a #define which I would normally put in the corresponding header file, but I was not sure if there was another header file where these things go.

**Comment by akien-mga** [comment]
> The "New_Anim" string should really be a #define which I would normally put in the corresponding header file, but I was not sure if there was another header file for that.

That would be really overkill.

**Comment by groud** [comment]
More reasonably, It should be in a `TTR(...)` to be translated.

**Comment by bncastle** [comment]
@aiken-mga It's not anymore overkill than defining a variable for one string that is actually a constant. The existence of that variable was the source of the bug. It should either be a constant or a simple string that's repeated twice.

**Comment by groud** [comment]
Well:
- We don't use that often #define in Godot. It could be used, but that's not godot's implicit coding style.
- As explained [here](https://stackoverflow.com/questions/10747927/should-i-use-const-for-local-variables-for-better-code-optimization), it's not that useful to declare a variable as constant. It's good to to do so to avoid confusion, but in most cases it's optimized by the compiler.

**Pull request merged**
