### PR TITLE
#24131: fix for PathFollow offset slider overlapping with the inspector

### LINKED ISSUE #24131: Offset dragging point in PathFollow(2D) with value lesser than 1 overlap with Inspector
**Godot version:**
3.1 8dd00ed

**OS/device including version:**
Windows 10

**Issue description:**
When Path node with Curve and PathFollow is created, then changing offset to values lesser than 1, cause change position of dragging point to Inspector area

dddd

### PR DESCRIPTION
**Pull request by mineevgleb**
Fixes #24131

### CODE REVIEW

**Comment by akien-mga** [comment]
That would likely hide the bug by using a different Control, but not fix its root cause, right?

**Comment by mineevgleb** [comment]
Well, that field is the offset in units from the beginning of the path. For me this value feels to be linear in nature, and I don't really understand why currently it uses exponential slider. As for the root cause, it is in the Range class. When the value is less the one and the minimum value of the range is 0, Range::get_as_ratio will be returning negative values, moving slider out of bounds (range.cpp:182). Sliders shouldn't be exponential when they can go down to 0, otherwise they basically stretch infinitely :D

**Comment by akien-mga** [comment]
I agree with making this property use a non-exponential slider as proposed here, but I still think that we should also aim to fix the actual bug that it exposed.

If `EditorPropertyFloat` doesn't support a min below 1 when using exponential mode, it should print an error when wrongly configured. `Range` might also need to be checked for its exponential mode support, currently it shows an editor warning if you a min `<= 0`, but it still seems to support computing with `0` (and just ignores the exponential mode if `< 0`).

But this is maybe out of scope for this PR which is already good enough to merge, so I'll open a dedicated issue for it.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I opened #24191 to go further.

**Pull request merged**
