### PR TITLE
Improved gamepad support on windows and linux

### PR DESCRIPTION
**Pull request by 27thLiz**
Uses SDL2 gamepad mappings, supports hot-swapping on windows and fixes some issues like MS$ keyboards being recognized as joysticks on linux. 
It should now also be easy to add support for force-feedback/rumble .

If your gamepad is not in the built-in list, you can add it's mapping via the env variable "SDL_GAMECONTROLLERCONFIG"
Based of punto- 's work in #1464 , thanks for that ;)

Sorry for unnecessary commits, I'm new to git and didn't know about rebase :/

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks for your work, it looks very promising! :)

As you said there are quite a few unnecessary commits. Rebasing would be somewhat confusing if you are not experienced with git, so I would advise you to create a new branch based on godotengine/master, and then cherry-pick (see ```git cherry-pick```) the commits that are meaningful from your joy_sdl branch. If this sounds confusing to you, I can have a look this evening at listing the exact steps needed to do it.

Also check the diff for d5743d0 on GitHub, it seems the indentation is not correct.

**Comment by Hinsbart** [comment]
Thanks for your input, I'll try to clean it up later today, making a new branch does indeed sound a lot less confusing than rebasing ;)
Will also look at what happened there with the intendation, I made that commit because the formatting was realy messed up, but I guess I still did something wrong.. those stupid windows editors :P

**Comment by Hinsbart** [comment]
Ok, I made a new branch which is clean. However, I still have the issue of intendation... 
It looked just fine inside QtCreator, then I checked it in sublime, saw some bad intendation and fixed those.

but when I wanted to commit it, I noticed that the diff looked wrong again... Do you know what could be the cause of this?

**Comment by akien-mga** [comment]
Your new branch looks way cleaner, thanks!

For the indentation, I think your IDE is configured to use 4 spaces as default indentation, while most of the code base uses tabs. It looks weird in the GitHub diff as GH seems to display tabs with a length of 7, so it doesn't blend well with 4-space-formatted code.

Some IDEs also enforce the configured indentation policy to any line that you edited, or to the whole file, so that might sometimes produce surprising diffs where you only fixed a typo and the indentation on the line was changed, or in the whole file.

**Comment by punto-** [comment]
If you're using qtcreator, it's a bit tricky to configure it to put tabs on
your code, you'd think it's under the "text editor" section of the options
dialog, but it's actually under "C++", and you have to create a copy of the
settings profile, because they don't let you modify the default ones.

**Comment by punto-** [comment]
Is this merged? or was it ever made a pull request from the new branch?

**Comment by akien-mga** [comment]
It has not been merged yet no, I was waiting for @Hinsbart to create a new pull request from the cleaned up branch https://github.com/Hinsbart/godot/tree/remapping
I've had a look to create the PR myself based on this branch, but since there are now merge conflicts, it would be sensible. Worst case scenario I could cherry-pick the relevant commits, resolve merge conflicts and make a PR from my own fork.

**Pull request closed without merging**
