### PR TITLE
[3.2] Add iOS SDK version check.

### PR DESCRIPTION
**Pull request by bruvzg**
See #42584

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
This doesn't seem to work with osxcross for iOS (built with https://github.com/godotengine/build-containers/blob/master/Dockerfile.ios):
```
^[[90mosxcross: ^[[31merror: ^[[39mxcrun: '-sdk': expected macOS SDK
Failed to find SDK version while running xcrun --sdk iphoneos --show-sdk-version.
CalledProcessError: Command '['xcrun', '--sdk', 'iphoneos', '--show-sdk-version']' returned non-zero exit status 1.:
  File "/root/godot/SConstruct", line 43:
    if detect.can_build():
  File "./platform/iphone/detect.py", line 17:
    if get_darwin_sdk_version("iphone") < 13.0:
  File "/root/godot/methods.py", line 717:
    return float(decode_utf8(subprocess.check_output(["xcrun", "--sdk", sdk_name, "--show-sdk-version"]).strip()))
  File "/usr/lib64/python3.8/subprocess.py", line 411:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.8/subprocess.py", line 512:
    raise CalledProcessError(retcode, process.args,
```

**Comment by bruvzg** [comment]
Strange, `detect_darwin_sdk_path` do work and it's almost the same.

**Comment by akien-mga** [comment]
> Strange, `detect_darwin_sdk_path` do work and it's almost the same.

I guess that one works because `env["IPHONESDK"]` is defined.

**Comment by bruvzg** [comment]
Seems like `--show-sdk-path` (`detect_darwin_sdk_path`) it's a dummy function always returning the same path, and `--show-sdk-version` actually do look for SDK, but only macOS SDK are supported.

Probably we should limit the check to build on macOS and skip on osxcross, not sure there's any way to check version on osxcross.

https://github.com/tpoechtrager/osxcross/blob/master/wrapper/programs/xcrun.cpp#L198-L201

**Pull request merged**
