### PR TITLE
Sync and more translation for zh_CN

### PR DESCRIPTION
**Pull request by Geequlim**

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm a bit surprise by the size of the diff. Do you know why so many things were changed? I synced the PO files with the POT yesterday.

**Comment by Geequlim** [comment]
@akien-mga I just synced with `tools/translations/extract.py` and `make`..

**Comment by akien-mga** [comment]
Weird... Is your repo up-to-date with the upstream master branch? When I run ``make`` in the ``tools/translations/`` directory I only get this diff: http://paste.fedoraproject.org/372983/47093281/

**Comment by akien-mga** [comment]
If I apply your commit locally and run ``make``, I also get a huge diff (likely undoing the reordering changes of your own commit): http://paste.fedoraproject.org/372986/47095101/

What OS are you on, and with what gettext version?

**Comment by Geequlim** [comment]
@akien-mga  Yes it is up-to-date with the upstream/master. I always get such a large diff when run `extract.py` and `make`.

The version of gettext is `0.19.7`, I use Arch Linux.

**Comment by akien-mga** [comment]
Here's the "clean" diff if I apply your patch and then sync with ``make``: http://paste.fedoraproject.org/372991/64709682/

**Comment by akien-mga** [comment]
Note that ``make`` runs ``extract.py`` for you already. (but it shouldn't really matter here)

**Comment by Geequlim** [comment]
@akien-mga How can I get the "clean" version?

**Comment by akien-mga** [comment]
I guess you could rebase your commit away and apply my diff instead, if it looks to you like it has all the changes you made: http://paste.fedoraproject.org/372991/64709682/

BTW I notice this you might want to check:
```
 #: tools/editor/io_plugins/editor_texture_import_plugin.cpp
 msgid "Inserting"
-msgstr "插入中"
+msgstr ""
```

Otherwise, we need to investigate this huge diff bug. Apparently @bojidar-bg can reproduce it too on Arch.

**Comment by Geequlim** [comment]
@akien-mga Well... I will do that and make it clean.

Some translations are not appropriate so I removed them.

**Comment by akien-mga** [comment]
Ok we found that the issue is probably that somehow the algorithm used to parse all code files lists them in a different order depending on the system: https://github.com/godotengine/godot/blob/master/tools/translations/extract.py#L24-L33

So I'll add a ``matches.sort()`` to ensure we all have the same order (will produce a huge diff for everything, so I'll do this after I've merged your new file).

**Comment by Geequlim** [comment]
@akien-mga Thanks for your help, I have applied your patch.
And I'm glad to hear that your find the reason :)

**Pull request merged**
