### PR TITLE
Document the lack of localization remapping support in VideoPlayer (reverted)

### PR DESCRIPTION
**Pull request by Calinou**
See #43917.

### CODE REVIEW

**Comment by Riteo** [comment]
Is this intended behaviour or a technical limitation? I don't see why we should document this bug instead of fixing it.

**Comment by Calinou** [comment]
> Is this intended behaviour or a technical limitation? I don't see why we should document this bug instead of fixing it.

I don't know how difficult it would be to solve this.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
