### PR TITLE
Replace copies with constant refs in FBX importer

### PR DESCRIPTION
**Pull request by lufog**
To:
* avoid unnecessary copying;
* avoid unintentional change of value by reference;
* give compiler more context for optimizations.

Sorry for previous pr, I did not notice how I changed thirdparty files :)

### CODE REVIEW

**Comment by fire** [comment]
I'm not able to load many fbx files but I can see this isn't harmful.

There are cases where const has no meanin to optimizations, but that answer need research I don't want to do.

**Comment by Calinou** [comment]
> There are cases where const has no meaning to optimizations, but that answer need research I don't want to do.

Even if it doesn't always improve performance, `const` is still useful to improve readability. It gives you the guarantee that a variable is not reassigned after it's assigned once :slightly_smiling_face:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
