### PR TITLE
Draw an indicator to denote overbright colors in ColorPicker

### PR DESCRIPTION
**Pull request by Calinou**
This makes it faster to distinguish overbright colors from "standard" colors, as clicking and reading the values isn't required anymore.

The design of this feature is inspired by GIMP 2.10's display of overbright colors :slightly_smiling_face:

## Preview

New indicator icon

<details>
<summary>Old indicator icon</summary>

Old indicator icon
</details>

### CODE REVIEW

**Comment by golddotasksquestions** [comment]
Overbright means if raw is above 1 right?

**Comment by CowThing** [comment]
An indicator for over bright colors is useful. But I don't like the bright pink color of the icon. Is there a reason for it to be that color?

**Comment by CptPotato** [comment]
Im not sure if it's confusing for people but you could add simple tonemapping to the color if it is brighter than raw 1.0. that way you can roughly tell what shade it is.

**Comment by Calinou** [comment]
> An indicator for over bright colors is useful. But I don't like the bright pink color of the icon. Is there a reason for it to be that color?

I just went with the same indicator used by GIMP, but if there's no clear standard on how overbright colors are denoted, we can roll our own.

**Comment by CptPotato** [comment]
I think the white triangle looks best out of the proposed options.

**Comment by Calinou** [comment]
I pushed a new version with a new indicator icon:

New indicator

**Comment by CowThing** [comment]
Yeah I didn't think about how it would look scaled down. I do also like the white triangle with the outline.

**Comment by akien-mga** [comment]
Thanks!

**Comment by golddotasksquestions** [comment]
The default color for modulate is white. I am concerned that this triangle won't be identified as triangle but as weird black diagonal line.

The star proposed by @CowThing is a good symbol for something very bright. If combined with a 30% grey with 60% alpha, we end up with an overlay that is visible on top of black, white, bright colors and also very subtle mid tone colors.
To increase further readability on small resolutions the star can be made thicker.
overbright_star
This 256 by 256 pixel png already includes the alpha for the grey.
Here is a mockup where you can see it overlaying different luminosities and hues as well as how it looks in default resolution of the editor:
overbright_star_01

**Comment by Calinou** [comment]
@golddotasksquestions I tried making the star thicker, but it still looked bad after the SVG was rasterized.

**Comment by golddotasksquestions** [comment]
Don't import svg then, just use the png.

**Pull request merged**
