### PR TITLE
Fix release build after c0e4d7e (fixes #22143)

### LINKED ISSUE #22143: Can't build target release on windows
**Godot version:**
5614692a1

**OS/device including version:**
Windows 10

**Issue description:**
Building with:
```
scons -j12 platform=windows target=release tools=no
```
yields:
```
[Initial build] Compiling ==> modules\gridmap\grid_map.cpp
grid_map.cpp
modules\gdscript\gdscript_parser.cpp(4446): error C2027: wykorzystanie niezdefiniowanego przez użytkownika typu "GDScriptWarning"
d:\projects\godot\godot-src\modules\gdscript\gdscript_parser.h(41): note: zobacz deklarację „GDScriptWarning”
modules\gdscript\gdscript_parser.cpp(4446): error C2065: "DEPRECATED_KEYWORD": niezadeklarowany identyfikator
modules\gdscript\gdscript_parser.cpp(4446): error C3861: "_add_warning": identyfikatora nie odnaleziono
scons: *** [modules\gdscript\gdscript_parser.windows.opt.64.obj] Error 2
scons: building terminated because of errors.
```
With either `tools=yes` or `target=debug` build works fine.

**Steps to reproduce:**
```
scons -j12 platform=windows target=release tools=no
```

### PR DESCRIPTION
**Pull request by lekoder**
This reverts commit c0e4d7efca7eb24e91783a0ee15ac0ef0248833c, which caused #22143

### CODE REVIEW

**Comment by groud** [comment]
I would just ask @Faless to check the error before reverting the commit right away. :)

**Comment by lekoder** [comment]
@groud good point, I assumed compileable master is more important, and the functionality, if desired, could be easily re-implemented once we have master compiling again.

Perhaps we could have #22147 in place to safeguard against such problems in future.

**Comment by vnen** [comment]
It just needs a `#ifdef DEBUG_ENABLED` guard when calling the `_add_warning()` function.

**Comment by lekoder** [comment]
@vnen Indeed it does. Adjusted the PR accordingly.

**Pull request merged**
