### PR TITLE
Fix issue where properties couldn't be found by searching with capitalization enabled

### LINKED ISSUE #56840: Can not find member properties name with dash and lower case
### Godot version

3.4.2 Stable

### System information

Windows 11

### Issue description

I have property name is V_b_Paused but can not find this properties with copy that name when I run project
In Godot 3.3 is not has this issue. I think this issue is new feature in Godot 3.4 but I can find what property in setting to turn off this.
I am sorry for my bad english.
image

### Steps to reproduce

1. add new variable
var V_b_Paused : bool = false
2. run project
3. find new variable in filter property

image

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by IgorKordiukiewicz**
Fixes #56840

### CODE REVIEW

**Comment by akien-mga** [comment]
Wouldn't it be better to match on the actual path instead of having to undo the display-only transformation?
https://github.com/godotengine/godot/blob/86acff666e0724c2ed2cd557cabafddca5c74195/editor/editor_inspector.cpp#L2705

This could check `path` instead (and then match also category names and not just the property names).

**Comment by akien-mga** [comment]
> > This could check path instead (and then match also category names and not just the property names).
> 
> Do you mean e.g. in `!filter.is_subsequence_ofn(property_label_string)` changing the `filter` to `path` and also removing this
> 
> ```c++
> if (is_capitalize_paths_enabled()) {
> 	filter = filter.replace("_", " ");
> } else {
> 	filter = filter.replace(" ", "_");
> }
> ```
> 
> ?

Yes for the removal, no for changing `filter` to `path` - `filter` is what the user typed and this shouldn't be ignored. It's `property_label_string` which could be changed to `path` - to know if the user-provided `filter` is a subsequence of the property `path`.

**Comment by IgorKordiukiewicz** [comment]
>  It's `property_label_string` which could be changed to `path` - to know if the user-provided filter is a subsequence of the property  `path`

But there is already a check for that in this `if`:
```cpp
if (!filter.is_subsequence_ofn(path) && !filter.is_subsequence_ofn(property_label_string) && !property_prefix.to_lower().contains(filter.to_lower())) {
	continue;
}
```
So changing `property_label_string` to  `path` would result in duplicate `!filter.is_subsequence_ofn(path)`. And also then the issue isn't fixed.

**Review by timothyqiu — COMMENTED** [review]
I think this is not necessary anymore. #59163 fixed how property filtering works with a more comprehensive approach.

**Comment by akien-mga** [comment]
Superseded by #59163.

**Pull request closed without merging**
