### PR TITLE
Disabled "Escape" button when closing the shortcut window

### LINKED ISSUE #65081: Listen for Input does not work with Escape
### Godot version

889c522

### System information

Windows 10 x64

### Issue description

When you try to assign a shortcut in editor settings using this dialog:
image
Pressing Escape will close the dialog instead of assigning the key.

The dialog should probably handle closing, but not sure if it's possible to differentiate a keyboard close.

### Steps to reproduce

1. Open Editor Settings
2. Open Shortcuts
3. Double click some shortcut
4. Try to use Escape as shortcut when it listens for input

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by requizm**
Fixed #65081

### CODE REVIEW

**Comment by Mickeon** [comment]
Hold on. Is it not desirable and expected to be able to being able to quit any Popup in the editor by pressing ESC? In theory, the problem right now is that ESC priorities quitting the Popup **over** assigning the key. There's got to be a better workaround... What about being able to assign ESC when the mouse is over the input window?

**Comment by requizm** [comment]
> Hold on. Is it not desirable and expected to be able to being able to quit any Popup in the editor by pressing ESC? In theory, the problem right now is that ESC priorities quitting the Popup **over** assigning the key. There's got to be a better workaround... What about being able to assign ESC when the mouse is over the input window?

You are right, fixed.

**Comment by requizm** [comment]
Since I thought the `InputEventConfigurationDialog` class was actually just an input dialog, I had made such an arrangement at first.

**Review by EricEzaM — APPROVED** [review]

**Comment by EricEzaM** [comment]
It would be nice to keep being able to press escape to close the windows but I don't know what the solution is.

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
> It would be nice to keep being able to press escape to close the windows but I don't know what the solution is.

Is calling `set_close_on_escape()` when listening for input is toggled not possible?

**Comment by EricEzaM** [comment]
Yeah that would work but only when you are on the manual input tab I think. As long as you are on the listen for input tab, any key press is listened for there.

I think the way some other engines do it is that they listen for input when a certain control is focused. So when that control is not focused other shortcuts still work, like esc to close window.

**Comment by KoBeWi** [comment]
Ah, I think we could maybe have explicit "Assign" button, which activates "listen for input" mode.

**Comment by EricEzaM** [comment]
When I originally re-wrote the input event editor window I did bring that up as an option but I do recall a discussion where not having to click a button to start listening was better 🤷‍♂️

If we did add a button to start/stop listening, we could then combine the two tabs into one - it wouldn't be necessary to have manual/detect split like that any more.

**Comment by KoBeWi** [comment]
So I guess it's better to try the focus approach you mentioned first.

**Pull request merged**
