### PR TITLE
HTML5 is now using project size for the canvas

### PR DESCRIPTION
**Pull request by AlexHolly**
part of https://github.com/godotengine/godot/issues/10905

### CODE REVIEW

**Review by leonkrause — COMMENTED** [review]
This is adding back two placeholders that I originally removed because they were unnecessary.

The example you gave in https://github.com/godotengine/godot/issues/10905#issuecomment-410304981 shows a weirdly small game size. There's nothing wrong with using a small render size, but usually you'd double the display size so it's not that tiny.

As long as as the display size is above 640x480, the loading screen is never cut off like that. I'm against adding 2 placeholders for such a rare use case.

**Comment by AlexHolly** [comment]
These 2 lines cost almost nothing and fix a bug. Do they break something?

**Comment by eska014** [comment]
The bug is that you forgot to set the `display/window/size/test_width` and `test_height` project settings for your project, to ensure the window (i.e. canvas) starts at a reasonable size.

**Comment by AlexHolly** [comment]
Just tried to set the test_size nothing changes looks still broken.

**Comment by eska014** [comment]
This is on itch.io right? You'll have to enter the `test_width`/`_height` on the itch.io game settings page in *Embed options* → *Viewport dimensions*, at least 640x480.

I agree the names of these Godot project settings are bad, it should be `window_width` and `_height`

**Comment by AlexHolly** [comment]
Yeah it is on itch.io. With this settings it shows borders. I could scale up my game but I don't want to work with a high resolution.

Is this PR creating any issues? With the current state there is no way to use the resolution I want.

**Comment by eska014** [comment]
> Is this PR creating any issues?

Every addition needs documentation and must be maintained until at least the next major version. Adding this patch so our default HTML page supports games with canvas size below 640x480 is not worth it. There's no use case for games at 160x144 in a world of 720p devices.
If you absolutely must have such a tiny canvas, Godot makes it easy to supply your own HTML file in the export options.

If you want pixel-perfect retro graphics (e.g. low rez jam), set `test_width`/`_height` to an integer multiple of `width`/`height` and set `display/window/stretch/mode` to *viewport*. That way you can use whatever render resolution you desire, upscaled at a reasonable size. The relevant tutorial is available here: https://godot.readthedocs.io/en/3.0/tutorials/viewports/multiple_resolutions.html#stretch-settings

**Comment by AlexHolly** [comment]
Is it possible to make the grey panel also black like the actual render area?

peek 2018-08-14 02-35

**Comment by eska014** [comment]
Documentation for the HTML shell is at https://godot.readthedocs.io/en/3.0/getting_started/workflow/export/customizing_html5_shell.html

The grey panel is the document `body`, so change `background-color` in `body`:

    body {
            background-color: black;
    }

**Comment by AlexHolly** [comment]
Thanks I will give it a try.

**Pull request closed without merging**
