### PR TITLE
Several improvements for the Tilemap editor

### PR DESCRIPTION
**Pull request by ghost**
I'm working on some improvements in the built-in Tilemap editor, based on some issues, mainly #843:
- [x] Rectangular drawing and erasing.  
  `Ctrl+Shift+L_DRAG`: Draw.  
  `Ctrl+Shift+R_DRAG`: Erase.
- [x] Line drawing and erasing.  
  Uses the Bresenham's line algorithm.  
  `Shift+L_DRAG`: Draw.  
  `Shift+R_DRAG`: Erase.  
  ~~Brush size.~~
- [x] Bucket fill.  
  It uses a Flood Fill algorithm, and uses the node rect as limit.  
  `Missing shortcut`  
- [x] Search by name on the palette.  
  `Ctrl+F`: Will focus the search box if the 2D editor has the focus.  
  ~~Zoom for the tile palette.~~
- [x] Tilemap menu in the 2D editor toolbar.

And i made some small additions and changes:
- Shift+B for box select.
- Duplicate preview.
- When duplicating the original selection is preserved.
- Removed list display.

Suggestions are welcome.

### CODE REVIEW

**Comment by TheHX** [comment]
I'll not be able to finish all features now, but i'll try later. This pr is basically finished, it only needs testing, especially for changing some last things.

**Comment by akien-mga** [comment]
It looks really cool, I'll try to test it tonight or tomorrow morning.

**Comment by akien-mga** [comment]
How about putting a horizontal separator between the TileMap tools menu and the rest of the menu on the left? Right now it's quite confusing to have all the usual 2D Viewport tools available but not working (select mode, move mode, rotate mode, pan mode, etc.).

In the future it might be nice to hide them when in the TileMap editor plugin (and reuse some of their icons for TileMap specific features like the ones you are adding).

**Comment by TheHX** [comment]
Thanks, i'll work on those issues when i get home.

**Comment by TheHX** [comment]
About the horizontal space, i had this idea, put a space between the TileMap tools and the rest of menu:
toolbar_space
Or with a simple separator:
toolbar_separator

**Comment by akien-mga** [comment]
Putting a space and having the tilemap tools right aligned sounds good :)

**Comment by TheHX** [comment]
Fixed some small inconsistencies, and the toolbar is now right aligned.

**Comment by Zylann** [comment]
Suggestions:
- Select tiles/rect with the mouse and move / copy it, like Tiled does
- Middle click to pick a placed tile instead of having to find it in the tile list
- Ability to define neighboring rules?
- Shortcuts to flip / rotate tiles, individually or the whole selection

**Pull request merged**
