### PR TITLE
Fix #5854 (get_contact_collider_velocity_at_pos() strange behavior)

### LINKED ISSUE #5854: get_contact_collider_velocity_at_pos() strange behavior (3D)
**Operating system or device - Godot version:**
Windows 10 64 bits (built on commit 6072eb8 the commit is just for reference and is unrelated with the issue)

**Issue description** (what happened, and what was expected):
get_contact_collider_velocity_at_pos() returns inconsistent data.
It seems to happen when a RigidBody hits hard something.

**Steps to reproduce:**
- download the example
- open it in the editor
- run it making sure to have collision shapes visible

you will see on the left side, a body that falls from a lower height, it will show (0,0,0).
on the right side, the body will fall from a higher place, and you will see the issue in the vector being printed.

**Link to minimal example project** (optional but very welcome):
https://www.dropbox.com/s/rsd8vd6j8e3t81t/physbug.zip?dl=0

### PR DESCRIPTION
**Pull request by Alex-doc**
Fix for incorrect velocity report due to a typo.
Closes  #5854

### CODE REVIEW

**Comment by TheoXD** [comment]
To me it definitely looks like a typo.

**Comment by TheoXD** [comment]
But shouldn't it be in reverse? I just debugged it, rigid body is B, and if B->can_report_contacts() is true then crA becomes zero vector, which is not what you want.

**Comment by Alex-doc** [comment]
not sure I understand, can you show me an example?

**Comment by TheoXD** [comment]
If I apply your patch, the demo you provided only prints 0,0,0 for both rigid bodies.

**Comment by Alex-doc** [comment]
ah I see. So it is not the correct fix.

**Comment by TheoXD** [comment]
No it is not, on contact velocity can never be zero (because of the gravity), try this instead:

`
		if (A->can_report_contacts()) {
			Vector3 crB = A->get_angular_velocity().cross( c.rA ) + A->get_linear_velocity();
			A->add_contact(global_A,-c.normal,depth,shape_A,global_B,shape_B,B->get_instance_id(),B->get_self(),crB);
		}

		if (B->can_report_contacts()) {
			Vector3 crA = B->get_angular_velocity().cross( c.rB ) + B->get_linear_velocity();
			B->add_contact(global_B,c.normal,depth,shape_B,global_A,shape_A,A->get_instance_id(),A->get_self(),crA);
		}
`

**Comment by Alex-doc** [comment]
your solution looks more consistent, looks like gravity gets somewhat reported too, both now look like the right side one.
The value changes by setting Gravity Scale in the editor but seems to not be affected by the mass

**Comment by TheoXD** [comment]
Yeah that's the weirdest thing about physics, objects with different masses will hit floor at the same time. By the time both objects hit the ground, their acceleration value will be the same, because acceleration is not dependent on the mass.

**Comment by TheoXD** [comment]
feel free to update your PR with the updated code, I'm just here to help :)

**Comment by Alex-doc** [comment]
ah I think I figured out at what the gravity corresponds on the script side:
it's just `state.get_total_gravity() * state.get_step()`

**Comment by akien-mga** [comment]
@Alex-doc Your IDE changed all indentation from tabs to spaces, could you fix that? And once you edit your commit, you can take the chance to edit the log too as we discussed ;)

**Comment by akien-mga** [comment]
For the reference, see how the same feature is implemented in 2D: https://github.com/godotengine/godot/blame/master/servers/physics_2d/body_pair_2d_sw.cpp#L386

**Pull request merged**
