### PR TITLE
GDScript: Perform validated calls with static methods

### LINKED ISSUE #91282: GDExtension: static methods do not use `ptrcall` convention
### Tested versions

Reproducible in 4.3-dev, commit 6118592c6d88350d01f74faff6fd49754f84a7d0

### System information

Linux

### Issue description

When class methods are registered from the extension and GDScript has necessary type information available, then the GDScript -> GDExtension call will use the `ptrcall` convention.

However, this currently only works for instance methods, not for static ones. The latter fall back to the `call` convention (varcall/Variant based marshalling).

Pull request https://github.com/godotengine/godot/pull/91153 was a preparation to enable this, and demonstrates that ptrcalls are currently inactive.

---

This btw is also true as soon as at least one parameter has type `Variant`. This is much less of a problem though and would likely need to be treated separately, but static methods choosing the slow path can be a real performance issue.

### Steps to reproduce

Declare a static method from an extension binding (godot-cpp, godot-rust, ...) with correct signature information, so that the full type of the function, its parameters and return value are known to Godot. Then, call it from GDScript. Observe that only the `call` implementation (not `ptrcall`) is invoked.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by vnen**
When the types are validated at compile time, this type of call runs faster. It is already used for instance methods, this adds this optimization to native static methods as well.

PS: Viewing the diff without whitespace makes it easier to review the changes. The opcodes table increased by one character, so the alignment creates a bigger diff.

### CODE REVIEW

**Comment by dsnopek** [comment]
Thanks!

I'm not really qualified to review the code changes, since I don't know GDScript's internals very well.

However, I did try using this PR with godot-cpp's automated tests, which includes some static method calls that GDScript should do as validated calls. To be sure that a validated call to GDExtension was happening, I added some debug print statements:

```diff
diff --git a/core/extension/gdextension.cpp b/core/extension/gdextension.cpp
index 22a5df9935..a1c4606c80 100644
--- a/core/extension/gdextension.cpp
+++ b/core/extension/gdextension.cpp
@@ -259,6 +259,10 @@ public:
                ERR_FAIL_COND_MSG(vararg, "Vararg methods don't have validated call support. This is most likely an engine bug.");
                GDExtensionClassInstancePtr extension_instance = is_static() ? nullptr : p_object->_get_extension_instance();
 
+               if (is_static()) {
+                       print_line("validated_call: ", name);
+               }
+
                if (validated_call_func) {
                        // This is added here, but it's unlikely to be provided by most extensions.
                        validated_call_func(method_userdata, extension_instance, reinterpret_cast<GDExtensionConstVariantPtr *>(p_args), (GDExtensionVariantPtr)r_ret);
```

And, it printed out the function names I was expecting, as well as passed the tests!

**Review by Bromeon — APPROVED** [review]
I tested this in Rust, and it works, great job!

Interesting discovery: before this PR, static methods _do_ use `ptrcall` _if_ they are called as instance methods (on an object, rather than a type).

**Comment by Bromeon** [comment]
Not directly related to this PR, but is it possible to call static methods via reflection? I wanted to simulate falling back to regular calls (if no type information is available), but found it's only possible via actual instances.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
