### PR TITLE
Update visual script property selector

### PR DESCRIPTION
**Pull request by Gallilus**
# WIP for proposal [#3528](https://github.com/godotengine/godot-proposals/issues/3528)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

1. The search functionality of EditorHelpSearch seems more capable and understandable so I will try to implement this as a new foundation.
2. Implement the filters expected of both property inspectors. These filters are dependant on the input data.
3. Implement filters based on scope. Now only base classes are used to give results, for example when using the input class it's most likely you only want to base results on the Inheritors.
3.1 (Optional) Make filter conditions and presets extendable and overwritable by plugins. To support different programming styles
4. And last, when not enough solutions are provided automatically start ignoring the filters until you find solutions.
5. Then reimplement the creation of nodes based on the selection.
6.  And last provide the possibility to create snippets when creating none base nodes.
6.1. Use Typecast when creating inheriter nodes.
6.2. Use HasFunction when creating unrelated nodes.
6.3. (Optional) Maybe make these sippet conditions and result extendable and overwritable by plugins. Similar to PropertyEditor 

Updated 28-11-2021
Decided to create a DocRunner class first. It is responsible to get all the scripts that are not registered.
- [ ] Only update on reload script.
- [x] Loop true all folders.
- [x] Create ClassDocs on all scripts.
- [x] Create a VisualScriptNode for all CustomNodes. VisualScriptNode is needed for proper analysis in later phases.
The SearchRunner class is almost a copy of the EditorHelpSearch::Runner
- [x] Use the ClassDocs created by Docrunner.
- [ ] Interpret all VisualScriptNodes and options.
- [ ] Provide usable metadata so VisualScriptPropertySelector is able to instantiate selected tree item.

Next.
- [ ] VisualScriptPropertySelector, rework how the nodes get dropped.
- [ ] VisualScriptPropertySelector, rework the starting triggers. So all triggers work again and start with appropriate triggers.

### CODE REVIEW

**Comment by akien-mga** [comment]
Please amend the commit log, there's one typo per word :|

**Comment by fire** [comment]
> Propery selecotor cahnge UI and scope variable
Update VisualScriptPropertySelector user interface.
Issues Icons not showing

Property selector change UI and scope variables
Update the VisualScriptPropertySelector user interface.

Will look into the bug when I've done my tasks and am free.

**Comment by Gallilus** [comment]
Thank you for your correction.
This push has a few errors but I wanted to show how scope is implemented.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/56252.

**Pull request closed without merging**
