### PR TITLE
[3.2] Backport Kotlin support

### PR DESCRIPTION
**Pull request by m4gr3d**

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
You also need `apply plugin: 'kotlin-android'` in `platform/android/java/lib/build.gradle` to be able to compile Kotlin code.

**Comment by m4gr3d** [comment]
> You also need `apply plugin: 'kotlin-android'` in `platform/android/java/lib/build.gradle` to be able to compile Kotlin code.

Thanks for the reminder!

**Comment by akien-mga** [comment]
Thanks!

**Comment by Tooniis** [comment]
So now Kotlin can be used for plugins? Maybe some information about this should be added to the documentation.

**Comment by m4gr3d** [comment]
> So now Kotlin can be used for plugins? Maybe some information about this should be added to the documentation.

@Tooniis because of Android support for jvm languages, any such languages can be used for a Godot Android plugins as long as the correct dependencies are provided. We've just made slightly easier for kotlin by pre-including its standard library.

**Pull request merged**
