### PR TITLE
C#: Update exports only in the editor

### LINKED ISSUE #26915: RC1 C# Autoload double instance
**Godot version:**
The break occurs between Godot Mono 3.1 Beta 11 -> Godot Mono 3.1 RC1 (also present in RC2)

**OS/device including version:**
Manjaro Linux x64 

**Issue description:**
After updating to 3.1 RC1 and above, autoloaded C# scripts are instanced twice.

**Steps to reproduce:**
Attached is a project which shows this. Open in Beta 11 to see the correct output.
image
however in RC1 and RC2
image

**Minimal reproduction project:**
[DoubleInstance.zip](https://github.com/godotengine/godot/files/2952075/DoubleInstance.zip)

### LINKED ISSUE #26996: [Regression] ObjectDisposedException occurs when Node.Connect() is invoked
**Godot version:**
`master` / 4326fd5a7

**OS/device including version:**
Manjaro Linux 18.0.4

**Issue description:**
I wanted to see if there is any last minute regression before 3.1 stable gets released, so I updated from 8b231b9, and now the project fails to launch with the following error:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AlleyCat.Common.NodeStore`1[[AlleyCat.Autowire.AutowireContext, AlleyCat, Version=0.1.7011.21746, Culture=neutral, PublicKeyToken=null]]'.
  at Godot.Object.GetPtr (Godot.Object instance) [0x00011] in /home/fender/.local/share/godot/mono/solutions/14809629407524565018_7_1552443793/GodotSharp/Core/Object.base.cs:37 
  at Godot.Object.Connect (System.String signal, Godot.Object target, System.String method, Godot.Collections.Array binds, System.Int32 flags) [0x0000e] in /home/fender/.local/share/godot/mono/solutions/14809629407524565018_7_1552443793/GodotSharp/ObjectType/Object.cs:439 
  at AlleyCat.Common.NodeStore`1+<>c__DisplayClass3_0[T].<Get>b__0 () [0x00093] in /home/fender/workspace/AlleyCat/Source/AlleyCat/Common/NodeStore.cs:41 
  at LanguageExt.ClassInstances.MOption`1[A].Match[B] (LanguageExt.Option`1[A] opt, System.Func`2[T,TResult] Some, System.Func`1[TResult] None) [0x00025] in <0372748aca1c4e1fb990e7f1c4ef4a90>:0 
  at LanguageExt.Optional.ifNone[OPT,OA,A] (OA opt, System.Func`1[TResult] None) [0x00000] in <0372748aca1c4e1fb990e7f1c4ef4a90>:0 
  at LanguageExt.Option`1[A].IfNone (System.Func`1[TResult] None) [0x00000] in <0372748aca1c4e1fb990e7f1c4ef4a90>:0 
  at AlleyCat.Common.NodeStore`1[T].Get (Godot.Node node, System.Func`2[T,TResult] factory) [0x0001b] in /home/fender/workspace/AlleyCat/Source/AlleyCat/Common/NodeStore.cs:32 
  at AlleyCat.Autowire.AutowireContext.GetOrCreate (Godot.Node node) [0x0000d] in /home/fender/workspace/AlleyCat/Source/AlleyCat/Autowire/AutowireContext.cs:256 
  at AlleyCat.Autowire.NodeExtensions.GetAutowireContext (Godot.Node node) [0x0003e] in /home/fender/workspace/AlleyCat/Source/AlleyCat/Autowire/NodeExtensions.cs:38 
  at AlleyCat.Autowire.NodeExtensions.Autowire (Godot.Node node, LanguageExt.Option`1[A] context, System.Boolean abortOnError) [0x0000e] in /home/fender/workspace/AlleyCat/Source/AlleyCat/Autowire/NodeExtensions.cs:51 
  at AlleyCat.Autowire.NodeExtensions.Autowire (Godot.Node node, System.Boolean abortOnError) [0x00000] in /home/fender/workspace/AlleyCat/Source/AlleyCat/Autowire/NodeExtensions.cs:47 
  at AlleyCat.Autowire.AutowiredNode._Ready () [0x00008] in /home/fender/workspace/AlleyCat/Source/AlleyCat/Autowire/AutowiredNode.cs:12
```

The problematic code is as below: 
```csharp
public T Get(Node node, Func<Node, T> factory) => Find(node).IfNone(() =>
{
    Ensure.That(factory, nameof(factory)).IsNotNull();

    var data = factory(node);

    Debug.Assert(data != null, "data != null");

    // Object.IsInstanceValid(node) returns true, if printed here.
    // And an ObjectDisposedExcetion is thrown at the below line:
    node.Connect("tree_exited", this, nameof(OnNodeExited), new Array {node});

    _store.Add(node.GetInstanceId(), data);

    return data;
});
```

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #26915 and fixes #26996.

### CODE REVIEW

**Comment by mysticfall** [comment]
Thanks much! I'll try this revision now and report if it resolves the problem.

**Comment by mysticfall** [comment]
Yes, I can confirm that this indeed fixes #26996.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Pull request merged**
