### PR TITLE
[Input] Fix Unicode character input with Alt / Ctrl modifiers.

### LINKED ISSUE #6851: Support for [ctrl] + [alt] + special character == [Alt Gr] + special character
**Operating system or device - Godot version:** Windows & non-english keyboard layout - All versions

**Issue description:** When not using english keyboard, writing special chars like '>' and '<' (and many more) must be done with shortcut (right) <kbd>Alt Gr</kbd> + <kbd><</kbd>. Thats normal and fine, but on windows, lots of folks (like me) are used to (left) <kbd>ctrl</kbd> + (left)<kbd>alt</kbd> + <kbd><</kbd> which does not work and is very annoying (you know, you are used to _type_ code one way for 8+ years and then, this one editor does not support it).

Source: [https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute](https://en.wikipedia.org/wiki/AltGr_key#Control_.2B_Alt_as_a_substitute)

**Steps to reproduce:** 
set non english keyboard (czech in my case)
Godot -> script editor
<kbd>Alt gr</kbd> + <kbd>></kbd> = '>'
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>></kbd> = ''

Every native windows app (eh, native... even GIMP support this):
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>></kbd> = '>'

### LINKED ISSUE #54303: You can no longer enter in the editor a character that requires ALT + SHIFT (`[`, `]`, `\`, …)
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 Dev (8c162f4)

### System information

macOS 11.5

### Issue description

On mac some character that we use for programming required to do `ALT` + `SHIFT` + `some key`:
- `[` and `]` =   `ALT` + `SHIFT` + `(` or `)`
- `\` =   `ALT` + `SHIFT` + `/`
- etc.

This worked fine in 3.x:

before

Now is broken:

after

### Steps to reproduce

Open the editor, try to enter a `[` on a mac keyboard.

### Minimal reproduction project

/

### LINKED ISSUE #56319: Unable to type some special characters using the Option Key under macOS
### Godot version

v4.0.dev.custom_build [9f058674a]

### System information

macOS 12.1 arm64/M1 Max

### Issue description

In the latest master build typing all characters which needs the Option key is currently blocked.
That affects the German keyboard especially because key like these are only accessible using the Option key:
```
[
]
{
}
@
```

### Steps to reproduce

1. Use German keyboard layout
2. Try to type the @ sign in the editor (Option + L)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
- Add extra `unhandled_unicode_input` input processing step to process Unicode character input with Alt / Ctrl modifiers, after processing of shortcuts.

Alternative to #52452

This will prevent both shortcut and input to trigger simultaneously, by adding an extra processing step (shortcuts are handled in the `unhandled_key_input`). e.g., By default `Alt + F` won't input `ƒ` in the code editor (since it is a shortcut for Fold Line), but will work in any other Line/TextEdit.

Should not break any other input, since it's not changing existing code, new processing is done only if event is not handed.

Fixes #6851, fixes  #54303, fixes #56319.

### CODE REVIEW

**Comment by reduz** [comment]
Do you think we could do this in a way where we still have one function, even if it requires a boolean or extra field in InputEvent? I am afraid that having an extra function like this may be very confusing when looking at the API.

**Comment by reduz** [comment]
As discussed on IRC. I think if we want shortcuts to happen before, it seems like a cleaner solution to have a `shortcut_input()` call and then do `unhandled_key_input`. This would also help clean up that the later can receive shortcuts, which is pretty hacky.

**Comment by bruvzg** [comment]
Updated as discussed. Now, unhandled input is processed in the following order:

- `shortcut_input` (`Key` or `Shortcut` events, handled shortcuts)
- `unhandled_input` (all events)
- `unhandled_key_input` (`Key` events, handled Unicode input with modifiers)

**Comment by reduz** [comment]
@bruvzg Its a bit difficult to see in the PR to see if all the cases where the callback was replaced were only (or mostly) intended to process shortcuts, it does look OK it to me but just confirming that was your intention.

**Comment by bruvzg** [comment]
> Its a bit difficult to see in the PR to see if all the cases where the callback was replaced were only (or mostly) intended to process shortcuts, it does look OK it to me but just confirming that was your intention.

All `unhandled_input` and `unhandled_key_input` used for the shortcuts or mostly shortcuts are replaced with`shortcut_input`.

**Review by akien-mga — APPROVED** [review]

**Comment by reduz** [comment]
@bruvzg Fantastic work!! Love how much cleaner everything is now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
