### PR TITLE
Update the visibility for the custom templates for all platforms

### PR DESCRIPTION
**Pull request by m4gr3d**
Hide the custom template options behind the `Advanced Options` toggle

### CODE REVIEW

**Comment by dsnopek** [comment]
I think this is overall a good change. The custom templates have been the first thing on all export presets, but it's not a feature most developers use, so making it an "Advanced" setting makes sense.

The main downside in my mind, is that this will probably be a surprising change, since these options have been first for so long and everyone is used to mentally skipping over them. :-) It would also be nice for Godot 4.4 to move more options to "Advanced" on all the platforms, so folks can really see the advantage of having a cleaned up export preset form, rather than just a surprising hiding of the first two fields.

**Comment by akien-mga** [comment]
> It would also be nice for Godot 4.4 to move more options to "Advanced" on all the platforms, so folks can really see the advantage of having a cleaned up export preset form, rather than just a surprising hiding of the first two fields.

Yeah I agree with this. I think it can be valuable to have this split between basic/advanced options, but if this only affects the custom templates (which are still a fairly commonly used feature, compared to a lot of the more niche options some exporters have), users might fail to see why it's a good change.

So it could be worth doing a first pass at reviewing which fields could be made "advanced" options in each exporter.

CC @bruvzg

**Comment by bruvzg** [comment]
> So it could be worth doing a first pass at reviewing which fields could be made "advanced" options in each exporter.

There are a bunch of settings that are likely rarely changed, and can be in "advanced":

- iOS:
	- application/additional_plist_content
	- application/delete_old_export_files_unconditionally
	- application/generate_simulator_library_if_missing
	- application/icon_interpolation
	- application/signature
- macOS:
	- application/additional_plist_content
	- application/export_angle
	- application/icon_interpolation
	- application/signature
	- display/high_res
	- xcode/platform_build
	- xcode/sdk_build
	- xcode/sdk_name
	- xcode/sdk_version
	- xcode/xcode_build
	- xcode/xcode_version
- Windows:
	- application/d3d12_agility_sdk_multiarch
	- application/export_angle
	- application/export_d3d12
	- application/icon_interpolation

Currently, only privacy manifest settings for macOS/iOS are in Advacned.

**Comment by m4gr3d** [comment]
> > So it could be worth doing a first pass at reviewing which fields could be made "advanced" options in each exporter.
> 
> There are a bunch of settings that are likely rarely changed, and can be in "advanced":
> 
> * iOS:
>   
>   * application/additional_plist_content
>   * application/delete_old_export_files_unconditionally
>   * application/generate_simulator_library_if_missing
>   * application/icon_interpolation
>   * application/signature
> * macOS:
>   
>   * application/additional_plist_content
>   * application/export_angle
>   * application/icon_interpolation
>   * application/signature
>   * display/high_res
>   * xcode/platform_build
>   * xcode/sdk_build
>   * xcode/sdk_name
>   * xcode/sdk_version
>   * xcode/xcode_build
>   * xcode/xcode_version
> * Windows:
>   
>   * application/d3d12_agility_sdk_multiarch
>   * application/export_angle
>   * application/export_d3d12
>   * application/icon_interpolation
> 
> Currently, only privacy manifest settings for macOS/iOS are in Advacned.

@bruvzg I moved the settings you listed under `Advanced`.

**Review by bruvzg — APPROVED** [review]

**Review by dsnopek — APPROVED** [review]
LGTM!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
