### PR TITLE
Make links to the online docs show the stable branch

### PR DESCRIPTION
**Pull request by YeldhamDev**
Lots of links to the online docs show the `latest` branch instead of the `stable` one. This is bad because that branch could have things that are not yet available, leaving users confused.

### CODE REVIEW

**Comment by akien-mga** [comment]
Don't merge yet, I kept this pointing to latest on purpose. On phone right now but I'll explain why later.

**Comment by akien-mga** [comment]
So some concerns with this change:
- First of all this is the master branch, so it should link to latest. If new tutorials are added in latest, we need to be able to link to them now.
- "stable" is the current stable release, so the same problem that you're trying to solve now will happen as soon as we get a new stable release (so Godot 3.2 linking to "stable" tutorials would have wrong links once 4.0 is released and "stable" tracks it).
- Sometimes new tutorials are added to latest but relevant for older releases too, but not necessarily backported to the stable docs branch. Most changes done in the master branch are version-agnostic doc improvements (language improvements, more details added). The docs team doesn't have a good workflow to ensure that all those enhancements are cherry-picked to the 3.1/stable branch.
- I was thinking to add a way to substitute `/en/` for localized instances when they exist based on the editor locale. Currently translations are only enabled for "latest", so such localized links should still link to latest.

So overall if we want to make such a change, it should only be made just before releasing a new stable release, by replace `/latest/` by the relevant `/x.y/` (after creating the branch in the docs). And then after branching `x.y` in the engine repo, the links should be switched back to `/latest/` in the master branch.

Alternatively, the links should be kept unchanged and modified by the editor itself to replace `/latest/` by its current `x.y` if `status` is `stable`.

Overall I feel it's more trouble than worth, so I decided not to do it for 3.1. I think I had other reasons but I can't remember now.

**Comment by YeldhamDev** [comment]
I agree that the proper solution would be to link to the current branch version of the editor, but until then, I still think that `stable` is better than `latest`.

**Comment by akien-mga** [comment]
IMO it doesn't make sense for the master branch to link to `stable` docs. As we write new tutorials, we're going to add links to them in the master branch and those will point to `latest`. People who use future alpha and beta builds should also be linked to the `latest` docs.

If we really want to change those links for stable releases, it should be done in relevant stable branches, and point to `3.1` for the 3.1 branch, `3.2` for the 3.2 branch, etc. This change can be done shortly before releasing a new stable release, once the relevant `x.y` docs branch has been created.

**Comment by akien-mga** [comment]
Closing as per the above, while in `dev`, `alpha` or `beta` status, the master branch should definitely link to the `latest` version of the docs. The links could be changed in stable branches to point to their relevant `3.1` or `3.0` subdomains.

**Comment by akien-mga** [comment]
Superseded by #29372 and #29373.

**Pull request closed without merging**
