### PR TITLE
glTF: Fix importing empty objects from Blender

### LINKED ISSUE #40729: Blender Empty Cube not being converted into a collision body
**Godot Version:** _v4.0._

**OS Version: Windows** _10._

I have used the same test blender file shared in https://github.com/godotengine/godot/issues/32678 and added a empty cube with -colonly as the doc said.

**Steps:**
Export blender file as single GLTF2 (.glb) file Add to local Godot project folder to auto import.

**Problem:**
Empty Cube being imported as a node3D

**Desired Effect:**
Empty Cube should be converted to a StaticBody with a collision node child set to BoxShape as the docs have said.

godot windows tools 64_FxlPJjH1b

[32678-respect-import-hints-with-empty.zip](https://github.com/godotengine/godot/files/4977830/32678-respect-import-hints-with-empty.zip)

_Originally posted by @A-Lamia in https://github.com/godotengine/godot/issues/32678#issuecomment-664000245_

### PR DESCRIPTION
**Pull request by ghost**
Handle empty_draw_type from extras while parsing nodes
Fixes #40729

Before:
problem

After:

Empty cube loaded as StaticBody with BoxShape3D child
Works in combine with Blender glTF export add-on extension (https://github.com/valeev-iv/BlenderToGodotGltfExtension)

### CODE REVIEW

**Comment by akien-mga** [comment]
So if I understand correctly this requires adding a non-standard extension to the glTF using your addon for the use case in #40729 to be solved?

If so I'm not sure this is a good solution, as most users wouldn't know about it. It might be better to work directly upstream with the Blender glTF exporter maintainers to provide a solution we can use out of the box.

**Comment by valeev-iv** [comment]
Yes, it is right.
Godot uses GLTFNode class to generate nodes and scene form glTF file.
Then Godot check empty_draw_type in node metadata to generate collision shapes.

First problem is that Godot does not read empty_draw_type property from file to GLTFNode. This PR will fix it.
Second problem is that glTF file does not contain empty_draw_type property at all (while Collada does). 

Addon forces Blender to export empty_draw_type property. You are probably right and Blender exporter should be fixed. Because it looks like Blender itself can't load empty object correctly

**Comment by valeev-iv** [comment]
Actually you don't need any add-ons or extensions at all.
Just add a custom property with a special name and value. Then export glTF with custom properties enabled


And you will get the same result


But I have created a new issue in Blender glTF exporter anyway
(https://github.com/KhronosGroup/glTF-Blender-IO/issues/1259)

**Comment by akien-mga** [comment]
Welp, OP deleted their GitHub account it seems. Marking as `salvageable`.

**Comment by william-lohan** [comment]
I'm still running into this issue with Godot 3.4.4 and Blender 3.1.2

**Comment by Calinou** [comment]
@fire Is this still relevant for the new glTF import code in 4.0?

**Pull request closed without merging**
