### PR TITLE
GDScript: Highlight comment markers (`TODO`, `FIXME`, etc.)

### LINKED ISSUE #4942: Highlight TODO, FIXME and similar keywords in comments in the script editor
### Describe the project you are working on

*Related to https://github.com/godotengine/godot-proposals/issues/602 and https://github.com/godotengine/godot-proposals/issues/3845.*

The Godot editor :slightly_smiling_face:

### Describe the problem or limitation you are having in your project

Not a particular limitation, but a quality of life feature for the script editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Other editors such as Visual Studio Code highlight keywords commonly used for important notes and todos. Here's an example with commonly used keywords in the Python language:

With `:` | Without `:`
-|-
image | image

Some editors will also highlight the entire line, but this is more complex to implement, especially if you want to handle continuation lines like this:

```python
# TODO: This is a thing that should be done for a future version of the game.
#       This line is still highlighted as TODO due to the spacing.
#
# This comment is not highlighted as TODO.
```

<details>
<summary>File contents - Copy-paste this in various editors for testing purposes</summary>

```python
# todo: Example comment.
# TODO: Example comment.
# FIXME: Example comment.
# fixme: Example comment.
# NOTE: Example comment.
# note: Example comment.
# CHANGED: Example comment.
# changed: Example comment.
# HACK: Example comment.
# hack: Example comment.
# XXX: Example comment.
# xxx: Example comment.

# todo Example comment.
# TODO Example comment.
# FIXME Example comment.
# fixme Example comment.
# NOTE Example comment.
# note Example comment.
# CHANGED Example comment.
# changed Example comment.
# HACK Example comment.
# hack Example comment.
# XXX Example comment.
# xxx Example comment.
```
</details>

**Note:** Unlike https://github.com/godotengine/godot-proposals/issues/602, this proposal does *not* suggest adding a bottom panel to track all TODOs/FIXMEs within the project. It only suggests highlighting those keywords in comments in the script editor. Project management tools such as issue trackers or Kanban boards are usually more suited for long-term TODO/FIXME tracking.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Highlight specific keywords *in comments only*, but probably don't bother with highlighting the entire line (as handling multiline comments is difficult).

I'd suggest supporting the following keywords for highlighting: `TODO`, `FIXME`, `NOTE` and `HACK` (all case-sensitive). Like in Visual Studio Code, these do not have to be at the beginning of a comment line, and these do not have to be followed by a `:` symbol.

`XXX` ("dirty hack") is rarely used nowadays, so there's probably not much point in supporting it. I haven't seen it in years myself :slightly_smiling_face: 

From an implementation perspective, I haven't found a way to add a keyword highlight that works within a color region (i.e. comments). Let me know if you can find a way to work around this.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

This is about improving the script editor usability and bringing its functionality on par with popular IDEs.

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes godotengine/godot-proposals#4942.

### CODE REVIEW

**Comment by MewPurPur** [comment]
Does it look good on light theme, where comments appear brighter rather than darker?

**Comment by dalexeev** [comment]
The light theme looks like this:



I didn't choose these colors carefully, in the hope that someone with better taste would suggest other colors.

**Comment by dalexeev** [comment]
_Dark_


_Godot 2_


_Light_

**Comment by MewPurPur** [comment]
Tbh I like them, but I'd like it if a similar result for dark theme could get achieved with something like 0.6 alpha so it's more comment-like in all themes.

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` 6588a4a29af1621086feac0117d5d4d37af957fd), it works as expected.

See this example with the text from the original proposal for reference:

image

I like the use of multiple colors, it makes sense here.

The implementation itself looks good to me from a cursory look. I've also tested scenarios such as comments inside strings, and can confirm no highlighting is applied there (it shouldn't).

Changes to the list of keywords in the editor settings also work correctly without requiring a restart.

**Comment by dalexeev** [comment]
> I'd like it if a similar result for dark theme could get achieved with something like 0.6 alpha so it's more comment-like in all themes

Indeed, the `text_editor/theme/highlighting/comment_color` editor setting has a translucent color.



But I checked the default themes and the colors look good in my opinion. I'm not sure if non-grayscale translucent colors will work for any theme. Let me know if you think it's worth looking into.



Notes:

1. In this implementation, markers must consist of ASCII identifier characters. Should we add support for Unicode markers? To do this, I just need to replace `is_ascii_identifier_char()` with `is_unicode_identifier_continue()`, but I have performance concerns. On the other hand, this only applies to comments and this function will be optimized in the future, see #75846.
2. I see an opportunity to use more than 3 hardcoded levels here. We can use one editor setting of type `Dictionary` "color -> list of markers". This shouldn't affect performance since we have a `HashMap` for marker colors. Is it worth it, or "three levels is enough for everyone"?
3. This PR only implements it for GDScript. In the future, we should add this for C# and the shader language too.

**Comment by Calinou** [comment]
> I see an opportunity to use more than 3 hardcoded levels here. We can use one editor setting of type Dictionary "list of markers -> color". This shouldn't affect performance since we have a HashMap for marker colors. Is it worth it, or "three levels is enough for everyone"?

I would wait until there's significant demand before implementing more settings (likely in a separate proposal once this PR is merged).

**Comment by dalexeev** [comment]
Here is how it might look (https://github.com/dalexeev/godot/commit/46fb4c18da76f871238df527b9575f0ec41cc453):



The disadvantage is that you cannot reset the colors individually.

**Comment by Bromeon** [comment]
Some input on splitting into 3 groups, but that's bikeshedding territory 😬 
* CAUTION and ATTENTION are very similar, but in different levels. They should probably be in critical, also because there's already many on the warning level.
* HACK seems more like FIXME, TODO i.e. something that should be cleaned up, but is not critical
* maybe CRITICAL could be added to the critical list
* maybe INFO could be added to the notice list

**Comment by dalexeev** [comment]
> Some input on splitting into 3 groups

Done.

> 1. Should we add support for Unicode markers?

Done.

I also tweaked the colors a bit so they are brighter/clearer but still dimmer than the keywords. The light theme colors don't seem very good to me, if there are any suggestions I'll fix it.

**Comment by Calinou** [comment]
The new colors look great to me, even on light theme :slightly_smiling_face:

**Review by akien-mga — APPROVED** [review]
Seems fine to me. Didn't review the highlighter code in depth but it's relatively low risk.
The feature proposal seems well appreciated by the community.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
