### PR TITLE
Fix instance uniforms breaking when setting a new mesh.

### LINKED ISSUE #58113: Vulkan: MeshInstance3D looses Shader Instance Uniform Color when loaded with a new mesh
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

Changing the mesh of a MeshInstance3D breaks any colorUniform from the shader assigned with Instance Uniform qualifier. While we can still print it's color value.

ShaderUniformBreakMeshLoad

Editing texturesUniform parameters not instance qualified works fine, but instance uniform colors seems to go black and not respond to any further parameter edits.

### Steps to reproduce

1 Create a shader material and assign a color instance uniform to it.
2 Change the MeshInstance3D by doing load(another_mesh_path)
3 Color instance uniforms are perpetually black.

### Minimal reproduction project

[LoadingMeshBreaksInstanceUniform.zip](https://github.com/godotengine/godot/files/8063723/LoadingMeshBreaksInstanceUniform.zip)

### PR DESCRIPTION
**Pull request by JohanAR**
Fixes #58113

### CODE REVIEW

**Comment by JohanAR** [comment]
I've tested my minimal reproduction project in #66997 and my large project where I discovered the bug initially, and they both work now as I expect them to.

I've also done a little bit of manual testing with set_mesh without override materials and it seems to be working, but I can't say that I really understand the inner workings of RenderSceneCull so it would be nice if someone else could verify that it's not wrong to add this line in this place.

**Comment by GNSS-Stylist** [comment]
Tested this with my MRP in https://github.com/godotengine/godot/issues/58113#issuecomment-1428710184 and the larger project I first stumbled this upon. Seemed to fix the issue in these cases.

Side note: This seems to change the issue https://github.com/godotengine/godot/issues/64057 somehow. Values in inspector seem to zero but colors seems to be reserved in the instance uniforms used by the shader. Floats, however seem to zero also in the shader (in addition to inspector). Didn't investigate this deeper, though.

**Review by clayjohn — APPROVED** [review]
Great work! This is a huge quality of life improvement with a single line of code. Tested locally with MRP from https://github.com/godotengine/godot/issues/58113 and can confirm that it works

**Comment by JohanAR** [comment]
Thanks! It took me a while to track it down but I was relieved that it appeared to be such an easy fix. I've been using a local build with this change while working on various projects, and I haven't found any cases where it seems to cause problems so far. Though I'm a bit unsure if there is something else that needs to be done in addition to this, but I suppose we can keep an eye out for related bug reports if this gets merged. Feel free to @ me if any issue pops up that might be related.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.

**Pull request merged**
