### PR TITLE
Windows MSVC intellisense - sourcetrail fix.

### PR DESCRIPTION
**Pull request by fire**
Fix scons scripts so that sourcetrail / intellisense has the paths of the includes for compiling. This is required for proper scanning of godot source code.

https://www.sourcetrail.com/

@Listwon Can you review this?

sourcetrail_2017-12-29_10-33-17

### CODE REVIEW

**Comment by akien-mga** [comment]
That completely defeats the purpose of having sub-environments in modules... That's a workaround, not a fix.

**Comment by fire** [comment]
Well if the modules is supposed to be linked into the same executable, the main env needs to have module environments added to the main env. If you're not, you're losing the include information..

**Comment by akien-mga** [comment]
No, the module-specific include paths are only relevant for that module. The rest of the engine doesn't need to know about include paths, it just links the libmodules.a.

**Comment by fire** [comment]
That's not how visual studio works and I can see how godot breaks intellisense now.

**Pull request closed without merging**
