### PR TITLE
Revise implementation of C# `Aabb.GetSupport` to match the implementation in `core`

### LINKED ISSUE #88834: GDScript `AABB::get_support` and C# `Aabb.GetSupport` point to opposite corners
### Tested versions

- Reproducible in Godot 4.2.1 .NET

### System information

Godot v4.2.1.stable.mono - Ubuntu 20.04.5 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated AMD RADV POLARIS11 () - AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 Threads)

### Issue description

When you call `Aabb.GetSupport` in C#, the resulting vector is the opposite corner of the AABB from when you call `AABB.get_support` in GDScript. I expect them to agree. Looking at the implementation sources, it seems like the vector added to the center is the opposite in C# from GDScript:

```C#
// ???/Aabb.cs:361
    public readonly Vector3 GetSupport(Vector3 dir)
    {
        Vector3 vector = _size * 0.5f;
        return _position + vector + new Vector3((dir.X > 0f) ? (0f - vector.X) : vector.X, (dir.Y > 0f) ? (0f - vector.Y) : vector.Y, (dir.Z > 0f) ? (0f - vector.Z) : vector.Z);
    }
```

```C++
// core/math/aabb.h:210
Vector3 AABB::get_support(const Vector3 &p_normal) const {
	Vector3 half_extents = size * 0.5f;
	Vector3 ofs = position + half_extents;

	return Vector3(
				   (p_normal.x > 0) ? half_extents.x : -half_extents.x,
				   (p_normal.y > 0) ? half_extents.y : -half_extents.y,
				   (p_normal.z > 0) ? half_extents.z : -half_extents.z) +
			ofs;
}
```

### Steps to reproduce

Open the MRP below and play the only scene. The printed result is:
```
From C#: (-1, -1, -1)
From GDScript: (1, 1, 1)
```

### Minimal reproduction project (MRP)

[Get Support Disagreement.zip](https://github.com/godotengine/godot/files/14397631/Get.Support.Disagreement.zip)

### PR DESCRIPTION
**Pull request by nongvantinh**
fixes: #88834

### CODE REVIEW

**Comment by paulloz** [comment]
We'd be interested in opinions from core contributors here, since we're not entirely sure about the implications.
The C++ implementation changed in #44468, and was not ported to C# before the current PR.

**Comment by nongvantinh** [comment]
I think he might have forgotten to update the C# module because he's too busy. Besides, what benefits could this diversity bring?

**Comment by paulloz** [comment]
> I think he might have forgotten to update the C# module because he's too busy. Besides, what benefits could this diversity bring?

This isn't really the question. We (referring to @raulsntos and I) are simply trying to establish which is less harmful between:
- Keeping the current behaviour.
- Introducing the change, and potentially breaking people's code currently relying on this behaviour.

In essence: pushing aside the difference with GDScript, does the returned value even make sense? Hence, the review from another team, more aware of the implications.

**Review by raulsntos — APPROVED** [review]
What we got from the rendering team on RC is that the current `GetSupport` implementation returns the opposite of the _support_, and this PR fixes that. We also think that it's unlikely there are many users consuming this API, so we think breaking compat here is acceptable. Let's merge this for the 4.3 beta, and see if we get user reports.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
