### PR TITLE
Particle2d randomness

### PR DESCRIPTION
**Pull request by ficoos**
Currently any randomness within the implementation doesn't work properly.
Any randomness would not take effect since the internal working of how seeds are produced for each particle made a too small of a seed for the random function to work properly.

### CODE REVIEW

**Comment by tagcup** [comment]
A few things:

* I don't think that xor is necessary or useful, and typically such constants for shift/multiplication need to be carefully chosen through statistical tests (so things like "0xdeadc0de" tend to be bad idea).
The original code uses multiplication because it scatters bits.
* seed and random have different sizes (64-bit and 32-bit), meaning you'd need two random values to construct a seed.
* pointers can be used as a seed, but again, a point on 32-bit systems is not large enough.

Also I think this PR can be simpler, because just changing the initialization of p.seed should solve this problem.

If you add a get_seed() in math_funcs.h which returns the value of the current seed, you can 1) use it directly for p.seed 2) add a randomize_from_seed(), and derive a new seed from the current seed as the initial value of p.seed.

**Comment by ficoos** [comment]
Update just removes the seed per particle and uses a single seed for the entire system. There is no need for a separate seed per particle. It just uses the clock for initial seed.

**Comment by tagcup** [comment]
`random_seed = OS::get_singleton()->get_unix_time();` doesn't work well PCG64 (it causes issues the initial random value being 0 all the time), so can you please instead add the following function under Math and make use of it rather than using local custom random alhorithms:

```cpp
uint64_t Math::randomize_from_seed(seed) {
	seed(OS::get_singleton()->get_ticks_usec() * seed + PCG_DEFAULT_INC_64);
}
``` 

>  There is no need for a separate seed per particle.

Why?

**Comment by ficoos** [comment]
We don't need a seed per particle since we don't care about reproducing the random sequence.
if the PRNG works it should be indistinguishable to a casual observer from using multiple seeds.
It's a particle system not a sha1 key generator. It needs to be fast and light.

**Comment by tagcup** [comment]
> if the PRNG works it should be indistinguishable to a casual observer from using multiple seeds.

No, that's not how it works. PRNGs are simply long sequences of numbers. The only entropy may come from the seed. If that's shared, there will be correlations.

> It's a particle system not a sha1 key generator.

This is why I'm not talking about hardware RNG or a cryptographic hash functions (of which SHA1 is a bad example anyway).

> It needs to be fast and light.

I don't see how having different *seeds* will realistically cause any performance issues. You're degrading statistical quality for no real gains.

**Comment by tagcup** [comment]
The current code uses `uint64_t rand_seed = p.seed * (i + 1);` to derive the new seed. It doesn't make use of clock but that is still preferable to this PR because this still has more entropy: it feeds some external information that is not a part of the PRNG's internal state (namely, `i`).

**Comment by ficoos** [comment]
[pcg32](http://www.pcg-random.org/) is tested to produce high quality random numbers.
This means that as long as I keep advancing the seed for each call (which I do) I should get statistically random numbers.

Saying that you have to add entropy to the seed every few iterations makes no sense. The job of the PRNG is to produce random numbers. If that trick would make the PRNG produce better random numbers it would just be part of the algorithm.

An 8 byte per particle for a 512 particle is 4k extra data that adds nothing.

Just to make my point stronger I generated two [histograms](https://imgur.com/a/lpEMi) the left one uses a single seed the right one uses 100 different seeds. As you can see using a single seed is a *better* random source. This makes sense as the algorithm wasn't designed to have the different seeds produce statistically random different sequences in relation to each other but only for each sequence to be random within it's own stream.

What the test shows is that not only is the old method slower it produces less random numbers.

Finally, I would just like to repeat that even if the histograms were the other way around, it's were still random enough for the purpose of a particle system. But, as it stands using a single seed produces better random numbers takes less memory and less CPU.

**Comment by tagcup** [comment]
OK, I don't have time to teach you statistics here, what a correlation function, entropy, randomness mean or spend time pin-pointing what's wrong your home-made statistical quality tests.

I don't agree with your PR because:

* You're killing off all the sources of entropy, with will introduce correlations if analyzed with any proper standard randomness test suite.
* The current code, which also uses different seeds for each, is not a performance bottleneck, so your trade-off isn't justified
* Fixing the issue you mention in your original post is just a few lines of change, as I explained above.

**Comment by ficoos** [comment]
You can't just dismiss what I'm saying. I have a CS degree and I know what I'm talking about.

pcg32() already produces strong enough random data by itself for non cryptographic purposes it passes all the tests. The only reason to add entropy to it to reduce it's predictability not distribution. Since we don't care about predictability only distribution there is no need for entropy. As long as the output is uniformly distributed it's good for these purposes.

Particle systems don't need unpredictable numbers, they need a source of uniformly distributed numbers. Correlation doesn't matter and predictability doesn't matter.

This is not optimization or tradeoff, it just removes code that does absolutely nothing that makes a difference. We loose literally nothing and make the code simpler, take less memory and take less CPU.
If I saw a loop calculating digits of PI I would remove it too even tough it's not a performance bottleneck.

**Comment by ficoos** [comment]
In any case, this goes nowhere. Either you address my comments instead of being condescending or, if you are unable to, I'll do whatever @akien-mga, @Hinsbart or @reduz say since they seem to have the authority in the codebase.

I might be wrong, and I'm willing to accept that, but just saying that you are smarter doesn't make it so.

**Comment by tagcup** [comment]
What? I'm not the one who's talking about credentials. But you really don't know what you're talking about, and no, they don't teach that stuff to undergrad or majority of the grad students in CS.

I already gave you an explanation [above](https://github.com/godotengine/godot/pull/9036#issuecomment-306066802). Please read it properly.

I'm not in the mood to prove yet another perpetual engine wrong, so that's all I'll say.

**Comment by karroffel** [comment]
@ficoos reduz is currently working on creating the new Particles2D system, so your changes would be overwritten anyway :( Thanks for the initiative though! 💙

**Pull request closed without merging**
