### PR TITLE
Spread should be in degree (see documentation, and flag_disable_z case)

### PR DESCRIPTION
**Pull request by matrem**
I think particle spread should be taken as degree.
From these points it is :
- the documentation : http://docs.godotengine.org/en/latest/classes/class_particlesmaterial.html?highlight=particles
- the FLAG_DISABLE_Z case : https://github.com/godotengine/godot/blob/8b41ebf7840a3091c2a4ed294bf9159d45fd94cf/scene/3d/particles.cpp#L643
- the default value (45)

So I think this line should be fixed :
https://github.com/godotengine/godot/blob/8b41ebf7840a3091c2a4ed294bf9159d45fd94cf/scene/3d/particles.cpp#L649

### CODE REVIEW

**Comment by reduz** [comment]
can you check this again? I did a few changes to particles recently. Also i may be converting many values to radians wrong from what i see in the code, so checking all usages of 3.14 may be good

**Comment by matrem** [comment]
Ok I can look into this, perhaps I'll ask you some things about the code to understand it  :p
Should I fix this also : 
https://github.com/godotengine/godot/issues/13488
usage of mix in particles.cpp seems a little buggy (random from 1 is a little strange)?

**Comment by matrem** [comment]
- factorize a bit pi usage, and random function between -1,1.
- fix spread and flatness
- it seems pi usage is ok, but as it's mentioned in https://github.com/godotengine/godot/issues/10182 base angle / angular velocity and other things are not well implemented in 3d particles.

**Comment by reduz** [comment]
Seems good

Regarding the suggestions, I think randomness works more or less OK I think for most cases, any alternative I can think of makes it more complicated for the common use cases. Lifetime cant be randomized due to how the shader works, or more likely I suppose It can (can be made shorter I guess) but it wont affect the amount of particles computed simultaneously.

**Comment by matrem** [comment]
Ok personally I can't understand the current randomness behaviour (for example the scale) :
- You set the scale to 5
- Then you set the randomness to full (1)
The scale will be chosen between 1 and 5. Where does the 1 comes from? I never say that my random value should get in the [1, 5] range.
-If you set to middle (0.5), the scale will be chosen in [3,5]

It seems to mee, that it is really much more understandable and practical  to define randomness with a mean value and a variation (absolute or relative) around this mean value.

But perhaps there is something I'm missing.

**Pull request merged**
