### PR TITLE
Fixed bug in `GridContainer` with hidden children

### PR DESCRIPTION
**Pull request by besh81**
Fix a bug that occour when there are hidden children in grid_container.
The visualization isn't correct due to a wrong calculation of max_col and max_row that mistakenly includes hidden children.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Can you provide some minimal project that reproduces the bug? (is there maybe issue open about it?)
Also you need to run `clang-format`.

**Comment by besh81** [comment]
I didn't find any issue in the tracker.

Here a simple project that reproduce the bug: 
[bug_grid_container.zip](https://github.com/godotengine/godot/files/9072459/bug_grid_container.zip)

Screenshot:
Cattura

As you can see in the second grid_container there is an empty space at the bottom due to the hidden children that shouldn't be there.
The second grid_container should be exactly like the first.

**Review by KoBeWi — APPROVED** [review]
Needs squash.

**Comment by YuriSizov** [comment]
@besh81 Please squash commits, so we can merge this approved fix 🙂 
If you need help with squashing, you can refer to [this guide](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase) from the Godot documentation (or any article about squashing in Git, really).

**Comment by besh81** [comment]
After several attempts I think I did my first "squash" correctly or I hope so :smile: 
Please let me know if ok

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
