### PR TITLE
Remove `DDS_INDEXED` from DDSFormat

### PR DESCRIPTION
**Pull request by BlueCube3310**
Edit: MRP [ddsfix.zip](https://github.com/godotengine/godot/files/12359297/ddsfix.zip)

The DDS_INDEXED value within DDSFormat has been redundant since around 3.0. At one point this value used to correspond to an entry in the Format Info array, however, that entry got removed while the enum value remained.

This causes some textures to be imported incorrectly (e.g. L8 as L8A8) due to incorrect array indices.

### CODE REVIEW

**Comment by lyuma** [comment]
Do you have access to any test assets which can help us test if this change is correct? Ideally in the form of a minimal reproduction project (MRP) which is a zip of a new project with the assets in it that reproduce the problem.

Are there any implications of changing the enum: will this break compatibility of any assets already imported into Godot 4.0 or 4.1?

**Comment by BlueCube3310** [comment]
Added a MRP. The file tulips.dds is an l8 grayscale image, which gets imported as l8a8.

**Comment by BlueCube3310** [comment]
As for breaking compatibility, this PR only affects l8 and l8a8 dds importing, however the imported images used to be broken, so it shouldn't matter that much.

**Comment by BlueCube3310** [comment]
Here are the test results from the attached MRP:

result

**Comment by BlueCube3310** [comment]
Additionally, attempting to load grayscale-alpha images such as dice_l8a8.dds (inside of [dice_l8a8.zip](https://github.com/godotengine/godot/files/12388928/dice_l8a8.zip)) fails on v4.2-dev3 due to reaching outside of the Format Info array's boundaries:

resultfail

This PR also fixes that issue:

resultcorr

**Review by clayjohn — APPROVED** [review]
This change makes sense. It is clear that ``DDSFormat`` needs to line up with the entries in ``dds_format_info``

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
