### PR TITLE
Fix nodes being renamed into garbage upon conflict

### PR DESCRIPTION
**Pull request by KoBeWi**
Fresh new regression from #54072
D0zRII1TR9
(well maybe they aren't fresh anymore at this point)

### CODE REVIEW

**Review by akien-mga — DISMISSED** [review]

**Comment by akien-mga** [comment]
Actually taking back my approval, changing `Node::set_name` defeats the whole purpose of having this be optional, no? This will mean that at runtime, costly human readable name conflict resolution will be performed.

**Comment by akien-mga** [comment]
> I checked the `set_name()` usages and they are mostly used for TabContainer tabs, the `add_child()` method itself doesn't use it. Node only internally uses it inside `duplicate()` and the most heavy usage I found is the `instantiate()` method.

That's for the editor usage, but users can't set Node names from script and could write egregiously slow code like #54177 with e.g.:
```gdscript
func _ready():
	for i in range(40000):
		var node = Node.new()
		node.name = "MyNode"
		add_child(node)
```

But let's see what @godotengine/core folks think about it.

**Comment by KoBeWi** [comment]
Well my thinking is that if you use `set_name()`, you most likely want the name to be human-readable.
```GDScript
func _ready():
	for i in range(40000):
		var node = Node.new()
		add_child(node)
```
wouldn't have performance concerns.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
@KoBeWi's reasoning makes sense to me, if you use set_name you most definitely want a human readable conflict resolution.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
