### PR TITLE
Fix onion skinning internals activating audio/method/animation tracks

### LINKED ISSUE #83426: Enabling Onion Skinning breaks Audio in Animation track
### Godot version

4.2.beta.custom_build [51f81e1c8]

### System information

macOS 11.0+

### Issue description

I found another new issue when starting onion skinning while having put any audio into my animation track.

https://github.com/godotengine/godot/assets/1129695/18ebd12e-143d-46c1-b97a-86cb82ffc4b1

### Steps to reproduce

1. Put a "playing = true" key of any MP3 audio into a Animation track
2. Enable onion skinning

https://github.com/godotengine/godot/assets/1129695/60289cb7-d98c-4134-88fe-1c94de93d68c

3. To temporarily dismiss the bugged audio, put a "playing = false" key of the same audio animation track just after the previous key
4. Enable onion skinning

https://github.com/godotengine/godot/assets/1129695/9549a1f7-142e-4d8d-8eec-4a952861a696

### Minimal reproduction project

[gd_anim_unittest_1.zip](https://github.com/godotengine/godot/files/12913927/gd_anim_unittest_1.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
This should fix #83426, but I'd need it to be tested. @VansonLeung, would you give it a try, please?

### CODE REVIEW

**Comment by VansonLeung** [comment]
My re-test failed:

https://github.com/godotengine/godot/assets/1129695/cbbb4c2e-7024-49c2-8797-c83f4477aca0


[gd_anim_unittest_1 2.zip](https://github.com/godotengine/godot/files/12915305/gd_anim_unittest_1.2.zip)

**Comment by VansonLeung** [comment]
FYI - Here is my test on Godot 4.1 stable version:

By considering this - I think the real trigger cause of this issue may not originate from onion skinning, but instead from something else. @RandomShaper 


https://github.com/godotengine/godot/assets/1129695/b78d8f03-05e2-42e4-9d82-8698b91bde46

**Comment by VansonLeung** [comment]
image

Per this it seemed that it was me doing the audio track animation key wrongly. 

Ref: https://github.com/godotengine/godot/issues/83436

I tested your commit success though.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
