### PR TITLE
Fix OpenGL buffer depth for per pixel transparency support (Windows)

### LINKED ISSUE #20203: Per Pixel Transparency black windows [nvidia on Windows]
Not sure what version , it's whatever is the current here > https://hugo.pro/projects/godot-builds/

Windows 10 1703, 1803 (Just updated it and still not working)
Ryzen 5 1600
Nvidia GTX 1060

For some reason I only get black windows, all the objects show up fine, but the transparency never seems to work even across the demos and such even though it works for everybody else

godot_2018-07-16_07-31-59

godot_2018-07-16_07-29-08

[Edit]

I tried compiling the master and the issue still persists

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #20203

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Comment by bruvzg** [comment]
> Cherry-picked for 3.0.7.

This should not be cherry-picked, IIRC per-pixel transparency support itself is not in 3.0 branch.

**Comment by akien-mga** [comment]
Thanks for the quick review, I undid the cherry-pick in my (yet unpushed) local branch.

**Comment by Hector-GameBeast** [comment]
I don't think it got completely fixed in 3.1. Can confirm that per-pixel transparency does not work for integrated Intel HD Graphics in Godot 3.1

Windows 10 Home ( Version 10.0.18363, Build 18363 )
Intel HD Graphics ( Integrated )

**Pull request merged**
