### PR TITLE
4.0

### PR DESCRIPTION
**Pull request by ghost**
When I copy a node(s) in the scene dock that contain an AnimationPlayer node, the animation in the copy remains linked with the original so that when I change the animation in one, it affects the other.  Is there any way to turn this off, or is this a bug ?

### CODE REVIEW

**Comment by AThousandShips** [comment]
You accidentally opened a PR instead of an issue

**Comment by clayjohn** [comment]
Indeed. Please open an issue and fill out the big report template.

**Comment by KoBeWi** [comment]
It's not a bug.

**Comment by KoBeWi** [comment]
Either use "Make Unique Subresources (Recursive)" inspector option or copy AnimationPlayer to another scene and copy back.

**Comment by Zentropic** [comment]
Unfortunately neither idea worked.  There are no sub-resources and copying to another scene still maintains the link.  All I want to do is use the current animation definition in one library as a template base to build upon for another object, eg. platforms that use  different AnimationPlayers to move/rotate them as required.

  The platform is simply a Node2D with both an AnimatableBody2D and an AnimationPlayer as children.  In 3.5 I could simply copy the node and paste and they would be separate entities because I could edit them individually without affecting the other.  I'm guessing DUPLICATE_USE_INSTANTIATION is the issue, but why isn't there both a "paste" and a "paste as unique instance"  or a "duplicate" and "duplicate as unique instance" ?

  I have tried all sorts of making this and that unique and copying in different ways, but the only solution seems to be to rebuild the animation tracks from scratch.  I understand that the bulk of the time, duplicating and making a shared resource makes sense, but in this sort of situation it's a problem.

**Comment by Zentropic** [comment]
I have confirmed this wasn't an issue in 3.5 and furthermore when you copy a track from one AnimationPlayer to another, the reference to the node(s) involved in the tracks refers to the original destination node(s), not the relative node(s) based on the new destination.  Yet another thing that worked properly in 3.5 that doesn't in 4.0

  For example, an animation track is manipulating a node that is a child of its parent.  When I copy that animation track to the AnimationPlayer in a duplicate node structure, the animation track refers to the original node, not the relation in the new structure almost like an absolute path rather than a relative one.

  Object 1 animates a child node called "platform".
  The AnimationPlayer in the duplicated structure using the copied track animates the original "platform" from Object 1 with no way of changing the destination to the "platform" in Object 2 without of course deleting the track and specifying a new destination.

**Comment by YuriSizov** [comment]
Please use one of our [community platforms](https://godotengine.org/community/) for project support. GitHub is not the best place for that, and you're pinging half maintainers by continuing this discussion here, in an invalid PR.

**Pull request closed without merging**
