### PR TITLE
Exposed set_as_minsize to gdscript

### PR DESCRIPTION
**Pull request by supagu**
Exposed set_as_minsize to gdscript to allow popup menus to keep to the minimum size.

### CODE REVIEW

**Comment by akien-mga** [comment]
Can you add the matching documentation, and explain why you want to expose it? :)

**Comment by supagu** [comment]
@akien-mga what and where do I put the matching documentation?
Updated my description to include why I want it exposed.

**Comment by akien-mga** [comment]
You run `godot --doctool .` and it should generate the relevant entry to fill in `doc/classes/Popup.xml`.
Note that you should rebase on current master otherwise you'll also get some unrelated changes (592909db1).

**Comment by supagu** [comment]
Looks like I stuffed this, gonna open a new PR.

**Pull request closed without merging**
