### PR TITLE
Add inherited variables support for script debugger

### LINKED ISSUE #18346: Inherited variables not visible in debugger.
I have a .gd that inherits from another .gd.

The problem is when I am debugging with breakpoints. Inside the debugger the inherited variables are not shown. Only the child variables are shown. This makes it impossible to debug.  

ps, also, is there any work around for now?s

### PR DESCRIPTION
**Pull request by Geequlim**
Fix #18346

### CODE REVIEW

**Comment by reduz** [comment]
Seems very nice, fine to merge by me

**Comment by neikeq** [comment]
I don't get it. What is base.gd and script_base.gd? Which one is the base script?

**Comment by Zireael07** [comment]
script_base  looks to be the base (see BASE_CONST at the bottom)

**Comment by neikeq** [comment]
And what is base.gd? 😄

**Comment by Geequlim** [comment]
@neikeq This class extends base.gd which extends script_base.gd  :p

**Comment by neikeq** [comment]
So if I understand correctly, in the image above we see A (script with the `extend_var` field) which inherits B (base.gd) which inherits C (script_base.gd). Am I right?

If that were the case, I think script_base.gd should be nested inside base.gd, not placed after it. e.g.:

```
extend_var
V base.gd
    base_var
    V script_base.gd
        a
        b
```

instead of

```
extend_var
V base.gd
    base_var
V script_base.gd
    a
    b
```

and maybe the base class should be placed before the other members:

```
V base.gd
    V script_base.gd
        a
        b
    base_var
extend_var
```

**Comment by vnen** [comment]
I don't think it needs to be nested. It's like the regular Inspector: the derived class is shown first then it goes to each the parent classes. Godot doesn't have multiple inheritance, so if you nest them it'll just create a line of nested sections, reducing horizontal space as well.

**Comment by Geequlim** [comment]
@neikeq  Yes. Other debugger inspector like QtCreator use a nested  tree instead of a list to show the base classes.

Why I didn't nested the base classes:
* As mentioned by @vnen  that will take  more horizontal space.
* We have to expand more sections to check the members of the top-level base class.

**Comment by neikeq** [comment]
After thinking about the Inspector example, I think it's fine this way.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
