### PR TITLE
Added rad2vec and deg2vec functions

### PR DESCRIPTION
**Pull request by jxfaith**
Implements #7263

### CODE REVIEW

**Comment by bojidar-bg** [comment]
BTW, you could have used a force-push.. but, no big problem with this approach either :smiley:

**Comment by bojidar-bg** [comment]
Code looks good, but the following code:
```
print(rad2deg(deg2vec(20).angle()))
print(rad2deg(deg2vec(70).angle()))
```
Results in:
```
70
20
```
Which is obviously wrong (values are swapped). Seems like something is wrong with the axes to me, or with Vector2.angle...

**Comment by jxfaith** [comment]
Looks like Vector2.angle is implemented backwards.

`32    real_t Vector2::angle() const {`
`33    `
`34    	return Math::atan2(x,y);`
`35    }`

Math::atan2 is takes the y argument first, and the x argument second. [Documentation.](http://www.cplusplus.com/reference/cmath/atan2/)

**Comment by akien-mga** [comment]
Yes, see #2241 and #6330.

**Comment by Tybobobo** [comment]
Tested this - Works like a charm! :)

**Comment by tagcup** [comment]
Conversion between degrees and a *general* 2D vector doesn't make any sense to me, in mathematical terms: the norm of a 2D vector isn't necessarily equal to 1. You can't convert between two degrees of freedom (Vector2) and one degree of freedom (an angle) in a meaningful way. 

I would rather propose adding functions that converts between [polar](https://en.wikipedia.org/wiki/Polar_coordinate_system) and [cartesian coordinates](https://en.wikipedia.org/wiki/Cartesian_coordinate_system) in 2D: (x,y) <-> (r,θ) where θ is in radians. The API could be something like `cartesian_to_polar(x,y)` and `polar_to_cartesian(r,θ)`, each returning a vector.

**Comment by tagcup** [comment]
The particular use case mentioned in #7263 is `Vector2(1,0).rotated(angle)` BTW.
Issues regarding 2D rotations and atan2 are fixed in the current tip.

**Comment by akien-mga** [comment]
I agree with @tagcup, I prefer we teach people about polar coordinates and introduce proper constructors or converters than to add an implementation-specific rad2vec API (which would be actually angle_to_unit_vector_with_that_angle, which is only one of the many vectors that share that same angle).

**Comment by bojidar-bg** [comment]
Bump. This pull is stuck.

@tagcup ( @akien-mga ) Would it suffice if we rename the functions to 
`cartesian2polar(x,y)`/`polar2cartesian(angle, t = 1)` or 
`unit_vector_with_angle(angle)`/~~`vector.angle()`~~

**Comment by tagcup** [comment]
Sure (assuming the implementation is also changed to be that way). `cartesian_to_polar` and `polar_to_cartesian` reads better to me. I personally don't think using 133t speak in the API is a good idea, I'd be in favor of renaming such functions that already exist.

**Comment by akien-mga** [comment]
Closing based on the above discussion. I repurposed #7263 to be about implementing cartesian to polar conversion functions.

**Pull request closed without merging**
