### PR TITLE
Make RootMotionView use ArrayMesh instead of ImmediateGeometry

### LINKED ISSUE #48389: Vulkan: RootMotionView's grid is not displayed
**Godot version:**
4.0.dev

**OS/device including version:**
MacOS 10, Win 10 with Vulkan

**Issue description:**
`RootMotionView`'s grid is not displayed in 4.0.

But it's working fine in 3.2, so is this a regression?

**Steps to reproduce:**
Add `RootMotionView` to the scene

**Minimal reproduction project:**
[reverse_root_motion.zip](https://github.com/godotengine/godot/files/6411705/reverse_root_motion.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixed #48389

https://user-images.githubusercontent.com/61938263/117557651-5a42ec00-b0b0-11eb-9f2f-ab319cec259b.mov

### CODE REVIEW

**Comment by Calinou** [comment]
If we reach an agreement on this PR, it may be worth opening a similar PR for the `3.x` branch to improve editor performance. ImmediateGeometry is known to be slow in the GLES3 and GLES2 renderers.

**Comment by clayjohn** [comment]
I think we need to wait and see how efficient ImmediateGeometry is in Vulkan before evaluating this PR. Recreating an ArrayMesh each frame will be an unnecessary bottleneck. Ideally ImmediateGeometry will be implemented in a way that is optimized for per-frame updates.

**Comment by TokageItLab** [comment]
Indeed. We are still waiting for the implementation of `ImmidiateGeometry` to be done as soon as possible.

**Comment by TokageItLab** [comment]
If changes to the original implementation are allowed, drawing the grid with shaders may be the most performant.

**Comment by TokageItLab** [comment]
#50014

**Pull request closed without merging**
