### PR TITLE
Small usability improvements to Input Map editor

### PR DESCRIPTION
**Pull request by Nallebeorn**
1) Automatically close the _Press a key_ dialog when releasing the key. This makes adding many key events more streamlined, as you don't need to move the cursor back and forth between the OK button and the add button all the time.
2) Sort actions in reverse order (newest first). This is partly because of the same reason as above; the controls to add new actions are at the top of the window, so putting the new actions near the top too means less superfluous mouse movement (especially when adding many actions and their events at the same time). Additionally, you're generally more interested in editing your newly added actions than the oldest ones or the default ui_* actions, so it makes sense to allow that without having to scroll down.

### CODE REVIEW

**Comment by Nallebeorn** [comment]
Not sure where that review request came from, is that automatic or did I click something by accident? :P

**Comment by akien-mga** [comment]
> Not sure where that review request came from, is that automatic or did I click something by accident? :P

It's automatic because you modified code in `core/`.

The core changes are quite hacky btw, I don't think declaring things in reverse order to then configure reverse order and get them back in natural order is a good change...

**Comment by Nallebeorn** [comment]
> It's automatic because you modified code in core/.

I see.
>The core changes are quite hacky btw, I don't think declaring things in reverse order to then configure reverse order and get them back in natural order is a good change...

True. I was thinking that it would be good the keep the order of the built-in actions, but that's not exactly necessary. It might be better to just leave project_settings.cpp unchanged.

**Comment by akien-mga** [comment]
It might be resistance to change, but I personally like my actions ordered in order of definition. It makes sense for the builtin actions, and I usually define my actions in the order which is most natural to me, so I expect the first defined ones to come first.

It would be good to have more opinions from Godot users on this topic :)

**Comment by isaacremnant** [comment]
I'd rather have a way to reorder the actions myself, like with autoloads. I usually edit the project file to sort them in a way that makes sense for the gameplay, so I really wouldn't like the engine to sort them on its own according to some other arbitrary rule.

**Comment by groud** [comment]
I don't mind for the order. But projects might end up with a lot of actions in the end, so I think it would be better to implement a filter. Also, in that case, I think it's not worth merging if there's no way to change the order afterward (with drag&drop or something like that) 

Also, maybe #19450 should be merged first. There may be some conflicts.

**Comment by guilhermefelipecgs** [comment]
> Also, maybe #19450 should be merged first. There may be some conflicts.

@groud You're referencing an issue not a pull request.

**Comment by groud** [comment]
> @groud You mention an issue not a pull request.

Yeah, edited ^^

**Comment by homer666** [comment]
I think the first change is good. Just putting it out there in case the whole PR gets shot down due to the other change.

**Comment by akien-mga** [comment]
> I think the first change is good. Just putting it out there in case the whole PR gets shot down due to the other change.

Good point and I was about to ask for the removal of the 2nd commit to merge the 1st, but actually I'm not sure the 1st commit is a good change either. When I use the InputMap to assign a new key I like to see how Godot understands my input, and validate manually with OK. If I mispressed, I can fix it with one key press instead of having to recall the dialog. This change will automatically close the dialog when releasing the key, which can be jarring to some (you don't know if it worked or if you just discarded the popup somehow), and makes the "OK" button pointless.

**Comment by Nallebeorn** [comment]
> Good point and I was about to ask for the removal of the 2nd commit to merge the 1st, but actually I'm not sure the 1st commit is a good change either. When I use the InputMap to assign a new key I like to see how Godot understands my input, and validate manually with OK. If I mispressed, I can fix it with one key press instead of having to recall the dialog. This change will automatically close the dialog when releasing the key, which can be jarring to some (you don't know if it worked or if you just discarded the popup somehow), and makes the "OK" button pointless.

Well, if you do mispress, which probably doesn't happen all that often, reopening the dialog is just a matter of clicking the same button again – you won't even have to move the cursor. In my opinion, that's less annoying than how it is now. I don't really think it's confusing either (but admittedly, I would literally be the worst judge of that), it's easy to see that a new event was added to the list and the key is very clearly displayed there. It *does* make the OK button pointless (more or less, you can hold down a key without releasing it and press OK instead, but why would you), which is a bit weird.

**Comment by groud** [comment]
Does it work correctly when you want to use meta keys? Like ctrl and shift + the key.

**Comment by Nallebeorn** [comment]
> Does it work correctly when you want to use meta keys? Like ctrl and shift + the key.

Yes, they work fine. The only problem there is that the dialog closes when you release a modifier key, even if other keys are still pressed, which might not be optimal (but it could be fixed).

**Comment by mhilbrunner** [comment]
Sorry, but IMHO both changes aren't really improvements. You change inputs rarely enough for the extra OK click to not be a hassle, but nice to confirm you really entered what you wanted.

As to sorting, IMHO sorting alphabetically would make more sense. Or allow users to reorder manually, but that is overkill.

**Comment by mhilbrunner** [comment]
Closing this for now, as there doesn't seem to be a consensus on 1.) and 2.) should be implemented as a sorting option dropdown/menu instead.

Thank you for your work, it is still appreciated, and thanks for starting this discussion in the first place :)

**Pull request closed without merging**
