### PR TITLE
Fixed license detection on GitHub

### PR DESCRIPTION
**Pull request by dalexeev**
Just a little cosmetic enhancement:

### CODE REVIEW

**Comment by dalexeev** [comment]
It's a bit strange. When creating a new repository, if you check the "Add MIT License" checkbox, the `LICENSE` file is created with the line. Renaming it to `LICENSE.txt` will keep working. At the same time, in the `godot-proposals` repository, detection works even without the line. Actually, I'm not sure why detection isn't working here.

Currently, all branches only consider the file from the `master` branch. That is, cherry-pick seems to be optional.

**Comment by dalexeev** [comment]
This is probably the reason:

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license

> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your LICENSE file and note the complexity somewhere else, such as your repository's README file.

We can still add the heading "MIT License" to the `LICENSE.txt` file (for clarity), but not necessarily that this will solve the problem of incorrect license detection. The conflict may be caused by the presence of `COPYRIGHT.txt` and/or `LOGO_LICENSE.txt` files in the root directory.

**Comment by akien-mga** [comment]
GitHub's license detection keeps breaking, I'm tired of having to do workaround in our license text or repo structure to match its detection logic. They should give us a way to configure things once and for all.

As I understand it adding "MIT License" will not solve the issue, and it's also not part of the actual MIT/Expat license legal terms: https://opensource.org/licenses/MIT so I prefer not to merge this.

> The conflict may be caused by the presence of COPYRIGHT.txt and/or LOGO_LICENSE.txt files in the root directory. EDIT: Yes, that's the reason.

Did you confirm that they are both problematic, or only one of them?

**Comment by dalexeev** [comment]
> Did you confirm that they are both problematic, or only one of them?

Yes, I tested this. Having one of these two files (or two at once) breaks license detection. Even if these files are empty. Apparently, in the presence of multiple files that may contain a license, GitHub does not take the risk of marking the repository as having a certain license. In order to avoid claims against them.

> they should give us a way to configure things once and for all.

Yes, they should add the "Select main license file" setting to the UI or consider a custom file in the `.github` directory. Does anyone know if there is such a request to the GitHub developers?

Unfortunately, at the moment this issue cannot be solved except by renaming/moving problem files.

It's probably best to wait for GitHub to fix this issue. Incorrect indication is also noticeable in the search:



> it's also not part of the actual MIT/Expat license legal terms

Yes, I suppose you are right. But IMO this is a noticeable omission by the authors of the MIT license.
GNU GPL, by comparison, has the following title:

```
GNU GENERAL PUBLIC LICENSE
Version 3, 29 June 2007
```

The following repos have the same problem:

`godot-docs`
`escoria`
`tps-demo`
`build-containers` (no license)
`godot-docs-l10n`
`.github` (service repo)
`godot-syntax-themes`
`godot-roadmap` (no license)
`godot-3d-platformer-demo` (no license, WIP, last update on 6 Jul 2019)

**Pull request closed without merging**
