### PR TITLE
Fix scripts not reloading when edited externally

### LINKED ISSUE #21956: Auto Reload Scripts on External Change stopped working in 3.1
**Godot version:**
shot_180910_234550

**OS/device including version:**
Windows 10 64

**Issue description:**
Auto Reload Scripts on External Changed stopped working in 3.1. There is also issue #17044, but this is different.

**Steps to reproduce:**
Set Auto Reload Scripts on External Change in editor preferences
Create new project, create a scene with a gd script that is saved in the project folder, open the script in script editor.
Open that file in text editor (VSCode with autosave in this case), change file.
Go back to Godot editor. Now, in 3.0 the editor would display the script with changes, in 3.1 it does not.

### PR DESCRIPTION
**Pull request by scayze**
Fixes #21956

### CODE REVIEW

**Comment by akien-mga** [comment]
Git blame points at 8ff747171f, CC @Paulb23.

**Review by Paulb23 — APPROVED** [review]
LGTM.

**Comment by akien-mga** [comment]
Thanks!

**Comment by avencherus** [comment]
@scayze Hard to say exactly, but the scripts do reload, but here and there it seems at least the editor isn't quite updating.  Like things such as export vars, and aspects of tool script.

Should I open a new issue?

# This works fine.
godot_master_2018-09-15_17-01-09

# However, this doesn't update.

godot_master_2018-09-15_17-00-53

**Comment by scayze** [comment]
@avencherus yeah this is not in the scope of this PR, better open a new issue :)

**Pull request merged**
