### PR TITLE
Added support to scale areas, fixes #23448

### LINKED ISSUE #23448: Scaled physics bodies with offset CollisionShapes not working correctly
**Godot version:**
a3501c0

**OS/device including version:**
Happens on Ubuntu 18 and Windows 7

**Issue description:**
If you create a physics body, give it a collision shape and offset that shape from the physics body's origin, collision is detected in the correct location.

However, if you scale the physics body, the collision no longer works correctly (even though the debug shows where the shape should be). It seems like collision shape transform isn't correctly taken into account when the parent body is scaled.

Probably somewhat related to https://github.com/godotengine/godot/issues/15695

**Steps to reproduce:**

Load the attached project
**Note:** make sure debug collision is turned on so you can see the collision shapes!
Run the scene and you should see a cube travelling left. It will fail to collide with the first area (which has a scaled body + shape offset) but will collide fine with the second area (no scale, offset only)

**Minimal reproduction project:**
[scale_collision_bug.zip](https://github.com/godotengine/godot/files/2542165/scale_collision_bug.zip)

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixes #23448

### CODE REVIEW

**Comment by groud** [comment]
Your first commit has apparently two similar authors, you may want to fix that. :)

**Comment by akien-mga** [comment]
> Your first commit has apparently two similar authors, you may want to fix that. :)

Indeed, it was authored by your root email it seems: https://github.com/godotengine/godot/commit/2bd1e6e92a2931c157f9cffa002540ad9a08a11b.patch

That first commit is also already in #26004, so should probably be removed from this PR?

**Comment by AndreaCatania** [comment]
Done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
