### PR TITLE
Add editor localization support (WIP)

### PR DESCRIPTION
**Pull request by marynate**
Adding editor localization support.
- Specific language in editor setting
  
- Reading translation strings from [editor setting folder]/lang/[locale]/editor.po
  
  pls blame Goolge for bad translation :)

po template generated from xgettext and translated in POEditor

### CODE REVIEW

**Comment by Calinou** [comment]
Bump. How is work on editor localization going (if any)? Is this pull request even mergeable today?

**Comment by reduz** [comment]
Planned for 1.2

**Comment by seadra** [comment]
Just so you know, that Japanese is cavespeak.

**Comment by akien-mga** [comment]
What's the status on this @reduz? You said it was planned for 1.2, do you still intend to get it into 2.0 or will it have to wait for 2.1 or later (as we're now trying to go towards releasing 2.0 final in the coming months)?

**Comment by marynate** [comment]
Rebased on current master.

**Comment by akien-mga** [comment]
Looks like @reduz went for his own implementation in the master branch, so I guess this PR must be closed. Thanks for the work you did though, I do hope it was used as an inspiration for the implemented system :)

**Pull request closed without merging**
