### PR TITLE
Reduce the total size of our SVGs by 15%

### PR DESCRIPTION
**Pull request by MewPurPur**
(if we exclude the icons with the blue robot which are gigantic in SVG terms)

Many more manual optimizations, amounting to over 60 kB. Nothing too intrusive, but a few icons are slightly changed (IMO all of them for the better).

Also addresses all of the remaining ThorVG parsing errors on our set of SVGs as per https://github.com/godotengine/godot/pull/77318#issuecomment-1556406736. I think all remaining exceptions are in the blue robot, which I'll split off to another PR because changing those SVGs is a bit more touchy and important.

### CODE REVIEW

**Review by antimundo — APPROVED** [review]
Looks good to me!

**Comment by MewPurPur** [comment]
Just to be sure, can I also remove `xmlns:xlink="http://www.w3.org/1999/xlink"` form SVGs with gradients? I don't think it's ever used and `xlink:href` is deprecated. It was only used once anyway, where I used href instead and it still looks ok.

**Comment by capnm** [comment]
> Just to be sure, can I also remove `xmlns:xlink="http://www.w3.org/1999/xlink"` form SVGs with gradients? I don't think it's ever used and `xlink:href` is deprecated. It was only used once anyway, where I used href instead and it still looks ok.

[Yes, you can...](https://github.com/thorvg/thorvg/pull/674)

**Comment by MewPurPur** [comment]
Cool, that's another kilobyte :P

**Review by Calinou — APPROVED** [review]
This reduces editor binary size by 62 KB on Linux after stripping (before: `178150216` bytes, after: `178087912` bytes).

I've browsed through the 2D/3D/script editors and various bottom panels, and icons look good to me.

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
