### PR TITLE
add flake8 config and most changes

### PR DESCRIPTION
**Pull request by FrazerClews**
Made changes to .py files to meet pep8 standards, this is important as it makes the code more readable and can give optimisation improvements, furthermore, it makes it easier for people going from one project to another if they used pep8 which is the most likely standard. Another side note is that it will make it less likely to run into issues. Deprecated modules and other small miscellaneous changes are still needed

Next step is to add pylint support and add flake8 and pylint to the CI

### CODE REVIEW

**Comment by asheraryam** [comment]
I'm not a project maintainer so I don't have authority to request this, but they would likely post this or something similar.

> Could you rebase the branch to squash the commits into one (see http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) and edit the commit log to be more descriptive (https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind)?

> Note that you can't do that using GitHub's Web editor, and in general it's not feature-rich enough for contributing to projects beyond editing README files.

**Comment by bruvzg** [comment]
Related discussion: #6980

**Comment by Zireael07** [comment]
Commit log, to put it simply, is the commit message. After rebasing, you will only have one commit, so the message has to be descriptive.

**Comment by FrazerClews** [comment]
Slight mistake sorry with the commit, should be fixed now

**Comment by Anutrix** [comment]
Why was this closed?

**Comment by FrazerClews** [comment]
not too sure myself, maybe because it's set for 4.0, but there's no 4.0 branch yet

**Comment by vnen** [comment]
@FrazerClews you closed the PR because you force-pushed a change that removed your commit. So essentially the PR is now empty thus GitHub auto-closed it. I think you can reopen if you push your changes again to the same branch.

**Comment by FrazerClews** [comment]
@vnen thanks, I didn't realise. I'll fix is ASAP

**Pull request closed without merging**
