### PR TITLE
Mention how to remove TreeItem from a Tree

### LINKED ISSUE #20547: Tree node should have a delete_item() function
As it stands currently, the Tree node doesn't have a way to delete TreeItems. Using free() on a TreeItem doesn't cause any issues with the respective Tree node, besides that Tree.get_selected() isn't updated, plus it's just... odd having to use free(). I haven't tested if it causes any issues with the parent TreeItem, though.

### PR DESCRIPTION
**Pull request by KoBeWi**
Supposed to close #20547

### CODE REVIEW

**Comment by pycbouh** [comment]
Shouldn't you use `remove_child` before freeing it?

Anyway, it would be better from accessibility standpoint to actually introduce a dedicated method, if the process is not straightforward. All other controls with similar behavior provide necessary functions directly. Requiring developers to use `Object.free` here is not user-friendly.

**Comment by KoBeWi** [comment]
> Shouldn't you use remove_child before freeing it?

No, `free()` automatically removes it. `remove_child()` is only for when you want to remove an item and reuse later.

> All other controls with similar behavior provide necessary functions directly. Requiring developers to use Object.free here is not user-friendly.

That's because they are structured differently. `Tree` has access only to its root, it doesn't store all child items in any array. So `remove_item()` would be effectively a wrapper for `free()`, which makes little sense.

**Comment by pycbouh** [comment]
> So `remove_item()` would be effectively a wrapper for `free()`, which makes little sense.

It makes perfect sense. That's an implementation detail. A user of an API should have a safe and agnostic to such detail method to remove items. A method that will continue to work even if Tree is reimplemented in a different manner.

Current approach creates an unnecessary "special case" for `Tree`s where you have to remember to use a generic method that is sufficient here. For now. `ItemList`s, `OptionButton`s and others have easily discoverable methods, but to figure out how to remove a `TreeItem` you need to look for a tip in a `Tree` class description. That's just not good for an average user.

**Comment by KoBeWi** [comment]
> to figure out how to remove a TreeItem you need to look for a tip in a Tree class description

Maybe TreeItem should mention it too somewhere...

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
