### PR TITLE
Added missed limiters for Visual Shader node enums

### PR DESCRIPTION
**Pull request by Chaosus**
Added a bunch of limiters and their checking to almost all enums of visual shader nodes + some minor name fixes for some stuff.

### CODE REVIEW

**Comment by akien-mga** [comment]
Usually those enum values that represent the size of an enum are named `<ENUM_PREFIX>_MAX`. So I think it might be best to follow the same convention here? Or does `_LIMITER` mean something different in this context?

**Comment by Chaosus** [comment]
Some of them have MAX inside as a usable function so I decided to make them all ended by `_LIMITER`. If it's not desired I can return it back and use it only on enums with MAX.

**Comment by akien-mga** [comment]
Yeah I would suggest using `_MAX` where it's possible for consistency, and using `_ENUM_SIZE` for the one(s) where `_MAX` is used for a function.

We might want to change our `_MAX` convention eventually as the ambiguity is a problem, but for now it's best to stay consistent where we can.

**Comment by Chaosus** [comment]
@akien-mga k, done with that

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
