### PR TITLE
Reword "Open Project Data Folder" as "Open User Data Folder"

### PR DESCRIPTION
**Pull request by zacryol**
Clarifies that the button opens the `user://` dir
and for better consistency with certain ProjectSettings values:

"Use Hidden Project Data Directory" is named similarly, but refers to data within `res://`
and two values refer to `user://` as "User Dir"

(**Note:** Translations were not updated)

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Pull requests should not modify `.po` or `.pot` files, as these are updated automatically by Weblate every so often.

**Comment by timothyqiu** [comment]
Does it make sense to change to enum name as well?

**Comment by zacryol** [comment]
> Does it make sense to change the enum name as well?

which enum are you referring to?

**Comment by timothyqiu** [comment]
Oh, I mean the `RUN_PROJECT_DATA_FOLDER` enum, it's also referring to the Project Data Folder.

**Comment by zacryol** [comment]
Ah, yes, that would make sense.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
