### PR TITLE
Editor Android Port

### PR DESCRIPTION
**Pull request by m4gr3d**
`master` version of the Godot Editor Android port based on the work done by @thebestnom in https://github.com/godotengine/godot/pull/36776!

This PR cleans a lot of the logic in https://github.com/godotengine/godot/pull/36776.

There are still a lot of tweaks, UI cleanup and touch-ups needed to be done before the Editor Android port can be considered suitable for public release and usage. Nonetheless, the current logic is stable enough and partitioned away that we can start reviewing and landing this PR and then iterate on top of it.

Addresses https://github.com/godotengine/godot-proposals/issues/3931

https://user-images.githubusercontent.com/914968/154166897-aa4b2bf5-3135-48ff-a957-86772a6dab7c.mp4

### Apk Download (only meant for testing and feedback!)
[Latest master Godot Editor Android build (all architectures except `armv7`)](https://drive.google.com/drive/folders/1xSUfa-LVgM129o5JuIQCQQ6CQNvmtDVg?usp=sharing)

### Generate apk from sources
- Using the regular Godot build process, generate Godot tools android shared libraries for each platform you want the apk to support:
  - e.g: `scons tools=true platform=android target=<build_target> android_arch=<android_arch>`
  - `release_debug` is recommended for the `target` option
  - `android_arch` should be one of `arm64v8`, `x86` or `x86_64`
- Navigate to the `platform/android/java` directory
- Run `./gradlew generateGodotEditor`
  - The command will generate one apk for each available target
  - The generated apk(s) can be found in the `bin` directory.

### CODE REVIEW

**Comment by Calinou** [comment]
I gave the APK a try on my OnePlus 6. It seems to be working, although the Vulkan Clustered backend is selected by default in the new project dialog. It should be changed so the Vulkan Mobile backend is selected by default. The Vulkan Clustered option should be disabled with a "Not supported on mobile platforms" description.

While creating a new project works when using the Vulkan Clustered backend, it's actually automatically falling back to Vulkan Mobile. This can cause issues if you transfer a project from mobile to desktop, as a different rendering backend will be used.

**Comment by m4gr3d** [comment]
@akien-mga Updated the PR with the changes and feedback from the 3.x version; it's ready to merge!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by pranshuthegamer** [comment]
How can i test this apk?

**Comment by arkology** [comment]
@akien-mga Will the editor binaries for Android be available, for example, in the next alpha?
Or this is something that should be done manually? (I don't know anything about this, that's why I'm asking)

**Comment by himaghnam** [comment]
please include this in github build process - Actions

**Comment by Calinou** [comment]
The testing APK linked at the top of this pull request should still work for now (including the one in the `3.x` pull request).

**Comment by NicoleKai** [comment]
THIS IS SOOOOO COOOOLL!!!! HOLY COW I CAN GAME DEV FROM ANYWHERE!

**Comment by Yasserpro312** [comment]
add touch support to the ui 
right now you can't delete nodes or files and can't create folders without mouse and keyboard
so please add touch support with the next update

**Comment by Calinou** [comment]
> add touch support to the ui right now you can't delete nodes or files and can't create folders without mouse and keyboard so please add touch support with the next update

This is already planned, but it'll take a while to happen as there are relatively few contributors interested to work on the Android editor currently.

**Pull request merged**
