### PR TITLE
SpriteRegionEditor

### PR DESCRIPTION
**Pull request by MarianoGnu**
sin titulo

### CODE REVIEW

**Comment by MarianoGnu** [comment]
sin titulo

**Comment by shackra** [comment]
Sorry if the question sounds stupid, but, what is this feature for exactly? It looks awesome but I don't get its purpose.

**Comment by bojidar-bg** [comment]
@shackra I think the idea is to be able to select regions of a sprite without playing around with numbers.
If it is so, :+1:!

**Comment by TeddyDD** [comment]
:+1:

**Comment by vnen** [comment]
This thing is very cool.

**Comment by guilhermefelipecgs** [comment]
Very nice feature, but your diff is so bad, you are using a different EOF.

**Comment by akien-mga** [comment]
> Very nice feature, but your diff is so bad, you are using a different EOF.

Glad I'm not the one to complain about bad commit diffs this time :D

This should indeed not be merged as in IMO, it's just impossible to review the code or track down regressions. You'd have to redo your PR by using unix-like line endings (by the way we should probably enforce that in a .gitattributes).

**Comment by zhagsenkk** [comment]
:+1:

**Comment by okamstudio** [comment]
oh, right check the sprite class, something funky happened there :)

On Fri, Sep 25, 2015 at 11:01 AM, zhagsenkk <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2528#issuecomment-143232088>.
>



-- 

*OkamStudio*

**Comment by MarianoGnu** [comment]
Yes i realized when looking at the PR.
My IDE changes the EOL's and my diff tool doesn't warn me about this. There's only 1 line changed in Sprite.cpp

**Comment by akien-mga** [comment]
> Yes i realized when looking at the PR.

Could you try to rebase and git push -f to clean this up?

**Comment by MarianoGnu** [comment]
I tryed and got lots of errors, ended up messing up my local repository :/ i deleted it and i'm trying to restore it but can't clone this branch, only the master and this one is behind master

**Comment by MarianoGnu** [comment]
Now, this looks better @reduz @okamstudio @akien-mga

**Comment by reduz** [comment]
great, can i merge it?

**Comment by akien-mga** [comment]
Looks good indeed, I'll give it a try asap :) Thanks for rebasing.

**Pull request merged**
