### PR TITLE
ignore __pycache__ directory

### PR DESCRIPTION
**Pull request by xpol**
which is generated during scons.

### CODE REVIEW

**Comment by akien-mga** [comment]
> which is generated during scons.

Is it though? I never saw that one in a git clone.

**Comment by xpol** [comment]
I'm not sure.
Maybe its generated by my vscode and/or its extensions.
As scons files are python scripts.

**Comment by williamd1k0** [comment]
> Maybe it's generated by my vscode and/or its extensions.

Python 2 generates `.pyc` files in the same directory, but Python 3 generates `.pyc` files inside a `__pycache__` folder.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
