### PR TITLE
tinyexr: Sync with upstream 1.0.2

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes a bunch of bugs, notably addressing fuzzer reports (crashes). https://github.com/syoyo/tinyexr/releases/tag/v1.0.2

### CODE REVIEW

**Comment by fire** [comment]
It looks good, typically we don't review deeply the contents of a upstream third party patch.

I wanted to check if a random openexr image works, but wasn't able to at this time.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
