### PR TITLE
[macOS] Hack to force window activation for non-bundled app.

### LINKED ISSUE #8653: Input issues on macOS when running binary directly instead of .app bundle
**Operating system or device - Godot version:**
Godot 3.0
Mac OS X 10.12

**Issue description:**
Single click no longer functions, seem to be ignored. Double clicks still work though
Was working fine in the build from a few days ago, but stopped working after a fresh build of master yesterday.

**Steps to reproduce:**
Click on something :)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #8653.

### CODE REVIEW

**Comment by hpvb** [comment]
0_o

**Comment by akien-mga** [comment]
If it works, that's fine by me. @bruvzg Could you add some comments in the code to explain why this hack is needed though?

**Comment by bruvzg** [comment]
Added some comments.

AFAIK this is only way to fix unbundled apps focus on modern macOS (and unlike older hacks it's not using undocumented APIs), and it won't affect bundled apps at all.

**Comment by akien-mga** [comment]
Thanks!

**Comment by toger5** [comment]
Oh nice this is a great solution!!!
Thank you! so much for looking into it

**Comment by hpvb** [comment]
Cherrypicked into 3.0.3

**Pull request merged**
