### PR TITLE
[Android] Fix the issue causing the logo to not show when using the `compatibility` renderer

### LINKED ISSUE #92966: [Android] Splash screen doesn't render with the `compatibility` renderer
### Tested versions

- Reproducible in Godot 4.3 beta 1

### System information

Windows 11, Android 14

### Issue description

Godot's splash screen does not show when loading a Godot app / game / editor on an Android device with the `compatibility` renderer:
- While launching, the Android editor's project manager (which uses the `compatibility` renderer) does not show the editor splash screen. 
- While launching a Godot app / game with a splash screen, the splash screen does not show with the `compatibility` renderer but shows when the `mobile` renderer is used.

### Steps to reproduce

- Android Editor:
  - Download and launch the Android Editor on an Android device
  - Notice the editor splash screen does not show

- Godot Android app / game:
  - On a desktop platform (Linux, MacOs or Windows), open the MRP
  - Set the renderer to `mobile`
  - Export and launch the MRP to an Android device
  - Validate that the splash screen shows properly
  - Now set the renderer to `compatibility`
  - Export and launch the MRP to an Android device
  - Validate that the splash screen no longer shows

### Minimal reproduction project (MRP)

[Kenney Starter Kit City Builder](https://godotengine.org/asset-library/asset/2174)

### PR DESCRIPTION
**Pull request by m4gr3d**
Delaying showing the logo by 1 frame so that it doesn't run in the same frame as the setup logic resolves the issue.

To do so, the logo logic is moved out of `Main::setup2(...)` into its own `Main::setup_boot_logo()` method. By default, that method is invoked automatically by `Main::setup2(...)`, but on Android platforms, the default behavior is disabled and the `Main::setup_boot_logo()` is invoked in the next frame.

Fixes https://github.com/godotengine/godot/issues/92966

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
The code seems way more comprehensible after this PR. Thanks @m4gr3d !

Otherwise, not to be too much nitpicky, but shouldn't the `static const int` be in an enum instead?

**Comment by m4gr3d** [comment]
> The code seems way more comprehensible after this PR. Thanks @m4gr3d !
> 
> Otherwise, not to be too much nitpicky, but shouldn't the `static const int` be in an enum instead?

@adamscott I switched it to an enum.

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Review by akien-mga — APPROVED** [review]
Seems ok.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
