### PR TITLE
Input default to protected

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
Moved this structure to protected so it can be used on InputDefaults class derivatives. Should be used in case of using InputDefault::iteration

### CODE REVIEW

**Comment by akien-mga** [comment]
PRs should be made against the |master` branch, and can then be cherry picked by release managers. It doesn't make sense to merge anything in 3.1 and not in master and 3.2.

**Comment by Xrayez** [comment]
@jeronimo-schreyer this makes me curious, were you able to override `InputDefault` implementation by yourself seamlessly? If yes, have you done any patching/hacks to make this work or perhaps it was done via modules? I'm not sure whether #35240 is going to be accepted, please share your thoughts if you have a solution, thanks!

**Comment by jeronimo-schreyer** [comment]
@akien-mga Sure thing. Sorry
@Xrayez Actually, right now there's no one using this struct or map. I think its useful for handling vibration inside platform's input handling classes (when they derive from InputDefault). But every platform uses their own implementation to handle vibration instead. I think this is because every platform has it's own limitations, and that's why some platforms don't even implement InputDefault (like iphone) at all. I use it to handle vibration on the Nintendo Switch port and I think Playstation port will use it too

**Comment by Xrayez** [comment]
@jeronimo-schreyer `InputDefault` is removed in 4.0 and merged with `Input` class.

**Comment by aaronfranke** [comment]
Closing because this PR is no longer valid. @jeronimo-schreyer's Godot repository has been deleted, the target branch is wrong as mentioned above, and the input system has been refactored for 4.0 so this would have to be redone anyway.

**Pull request closed without merging**
