### PR TITLE
Update CSG's PhysicsBody's transform when updating CSGShape's transform.

### LINKED ISSUE #41653: CSGShapes created at runtime have unexpected collision behaviour
**Godot version:**
v3.2.2.stable.official

**OS/device including version:**
Windows 10 1909

**Issue description:**
I have a project that is generating prototype levels by creating sets of CSGBoxes and translating/rotating them accordingly, they are created by doing CSGBox.new() and add_child().

When created by code as above, they look visually correct, but collision shapes and invisible walls are all over the show, some part of translation/rotation isn't working correctly, I think, but it's not consistent. If the scene is then saved as a .tscn and recreated, it then works perfectly as expected. Nothing strange shows up when debugging and looking at the remote scene.

**Steps to reproduce:**
Create a 3D scene with a moveable character. Create a script for the top node that in _ready(), creates basic floors/walls with CSGBox.new() and set translations appropriately (and enable use_collision). Invisible walls will stop the character moving around, and the CSGBoxes will likely be collisionless.

For extra proof, save the scene by packing it:

```
var saved_scene = PackedScene.new()
saved_scene.pack(get_tree().get_current_scene())
ResourceSaver.save("res://savedscene.tscn", saved_scene)
```

Then load it from the editor, and watch it suddenly work perfectly.

**Minimal reproduction project:**
[HuntDownTheWall.zip](https://github.com/godotengine/godot/files/5151841/HuntDownTheWall.zip)

runtime_generated_scene.tscn will generate the CSGBoxes at runtime. You will find you cannot run all the way around the box because of invisible walls.

identical_pregenerated_scene.tscn is a perfect replica of the generated scene, you will find this one works perfectly as expected.

### PR DESCRIPTION
**Pull request by madmiraal**
Fixes #41653

### CODE REVIEW

**Comment by hoontee** [comment]
Was `use_collision && is_root_shape()` from https://github.com/godotengine/godot/commit/fc8574fbac1073f4d68197dc8a2b3504bfc8970d  necessary or should I remove them to match this PR?

**Comment by hoontee** [comment]
Forget my last post; #41653 is actually fixed in fc8574fbac1073f4d68197dc8a2b3504bfc8970d so this PR is unnecessary.

**Comment by madmiraal** [comment]
@hoontee #40935 missed the scenario where the local transform is changed. This PR fixes that.

**Comment by hoontee** [comment]
`NOTIFICATION_TRANSFORM_CHANGED` fires when local transform changes from my testing. Did you test the reproduction project from #41653 on `master`? The 3.2 branch doesn't have #40935 yet.

**Comment by madmiraal** [comment]
Closing as fixed in #40935.

**Pull request closed without merging**
