### PR TITLE
Add support for bilinear bars in TextureProgress

### LINKED ISSUE #6746: Support bilinear bars in TextureProgress
Supporting bilinear bars in TextureProgress (bars that extend in both directions, eg. left and right, up and down, clockwise and counter-clockwise) would be handy, so that you can make such bars using only one node (instead of two currently).

### PR DESCRIPTION
**Pull request by Calinou**
These bars will extend from the center to the left and right of the node, or from the center to the top and bottom of the node depending on the option selected.

The Clockwise and Counter Clockwise mode will expand the progress bar both ways in a circular fashion.

This closes #6746.

[**Example on Gfycat**](https://gfycat.com/elegantoldfashionedbovine)

### CODE REVIEW

**Comment by groud** [comment]
I'm not sure this is really desired. An infinite number of transitions could be imagined: spiral, growing circle, growing square, etc...

I don't get why those both-way expand transitions would be more common than those other cases. 
IMHO, this is too corner case for the core.

**Comment by groud** [comment]
Because that how we keep Godot lightweight, easy to use with a not bloated API.
That's Godot phylosophy in general, if something is not a common use case and can easily workarounded, we prefer not adding it to the core.

Don't take it wrong, I'm not strongly against this addition. But to be honest it looks like there are really few use cases for this feature.

**Comment by Zireael07** [comment]
Circular progress bars are actually fairly common in both games and apps, I believe it qualifies as a common use case.

**Comment by groud** [comment]
> Circular progress bars are actually fairly common in both games and apps, I believe it qualifies as a common use case.

This is already implemented. This is not what this PR is about.

**Comment by Chaosus** [comment]
More options not always means bloating, especially for UI. Godot always have a room for growing in this aspect.

**Comment by groud** [comment]
> More options not always means bloating, especially for UI. Godot always have a room for growing in this aspect.

Sure. Bloating happens when we add features for inexistant or very rare use case. That's where the whole question is. ;)

**Comment by akien-mga** [comment]
I think it's good. I agree with @groud that it's quite specific and might not be so much "core" material, but then the same reasoning applies to TextureProgress itself (it's relatively easy to code a TextureProgress from scratch with other nodes), so I think it's fine to add more features to it.

Some fun from IRC:
```
<reduz> image is not loading
<reduz> oh, image not loading IS the image
<reduz> wtf
```

**Comment by akien-mga** [comment]
And kudos for implementing your own proposal 2 years later @Calinou, `dev_skill++;`!

**Pull request merged**
