### PR TITLE
[DOCS] parse_json: Objects do not keep key order

### PR DESCRIPTION
**Pull request by mhilbrunner**
Document JSON not guaranteeing key order.

Closes https://github.com/godotengine/godot/issues/16099.

### CODE REVIEW

**Comment by LikeLakers2** [comment]
We should explicitly specify that arrays keep order. At least that's how it should be.

**Comment by akien-mga** [comment]
> Should this be mentioned in http://docs.godotengine.org/en/latest/classes/class_json.html too?

Would be good yeah, many users seem to be puzzled at how Godot handles JSON because they actually don't really know the JSON spec.

**Comment by mhilbrunner** [comment]
Will update this then.

**Comment by mhilbrunner** [comment]
Added same information to JSON/JSONParseResult class docs.

**Pull request merged**
