### PR TITLE
Add support for unbinding in connection dialog

### LINKED ISSUE #762: Allow to discard excessive arguments in signal connection
This is partially implemented, see this comment: https://github.com/godotengine/godot-proposals/issues/762#issuecomment-706705529
___

**Describe the project you are working on:**
Game using lots of signals.

**Describe the problem or limitation you are having in your project:**
I sometimes want to free an object after finishing animation. I can do it entirely in editor except one thing - I can't connect `animation_finished` signal to `queue_free`, because it emits with one parameter, which makes the call fail. In many cases, I have to add a script just to connect this signal to a method taking unused argument and calling `queue_free`. It's meh. Recently I had my custom signal connected to `queue_free` (without script), but later decided that it needs additional argument in some cases, so the nodes that didn't need this argument are now broken xd (I have to add a script just to work around this limitation now)

Other use examples include methods like
```
func some_callback(whatever):
    ...
```
If I wouldn't have disabled warnings, I would get "unused parameter" here.

Here's an old issue about this proposal: https://github.com/godotengine/godot/issues/21844
Some people already supported it >\_>

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There could be a flag for `connect` called `CONNECT_DISCARD_EXTRA` (or some other name) that makes excessive arguments discarded, so that the method would call instead of throwing "Too many arguments" error.

Alternatively this could be a default behavior, but it might not be a good idea.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
Check this PR: https://github.com/godotengine/godot/pull/38289

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Well, kind of. The thing is that with this feature I wouldn't need some of these scripts.

**Is there a reason why this should be core and not an add-on in the asset library?:**
Because it's about core. It can't be an add-on (although it would be fine for me if it could).

### PR DESCRIPTION
**Pull request by KoBeWi**
Title.
KrwPKzCW4k

I made some changes to PackedScene etc. to make them use CallableCustoms instead of passing binds.
Also did some cleanup in connection dialog (it still needs more cleaning) and removed some useless includes.

Closes https://github.com/godotengine/godot-proposals/issues/762

### CODE REVIEW

**Comment by KoBeWi** [comment]
Ok this is probably ready to review now.

I did modify some Connection-related stuff to make better use of custom Callables, because the plan is to remove `binds` from it completely, so this was necessary to avoid introducing yet another useless variable for `unbinds`. The complete removal of `binds` can be done in another PR to avoid modifying core too much .-.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Built locally after a rebase to make sure there's no recently introduced build issue.

**Comment by akien-mga** [comment]
Thanks!

**Comment by IsotoxalDev** [comment]
Can this be backported to godot 3.x?

**Comment by KoBeWi** [comment]
No, it depends on core changes.

**Pull request merged**
