### PR TITLE
Fix mono enabled build

### PR DESCRIPTION
**Pull request by ghost**
Fix mono enabled builds (broken by 3d87b70).

### CODE REVIEW

**Comment by neikeq** [comment]
Don't set/get still work?

**Comment by NathanWarden** [comment]
Juan changed those names a few commits ago, so this fix is necessary.

**Comment by neikeq** [comment]
Yes, the change is good. I'm just confused by the title because I thought there was a build error or something.

**Comment by tagcup** [comment]
No, there *was* a build error.

**Comment by NathanWarden** [comment]
Exactly, this fixes a build error :)

**Comment by neikeq** [comment]
I don't get it. That commit doesn't remove set/get, how was there a build error?

**Pull request merged**
