### PR TITLE
Add application/config/project_settings_override option to override project settings

### PR DESCRIPTION
**Pull request by marcelofg55**
With this projects can for example save `user://config.dat` and save some settings there that will load next time the project is run. This helps with some settings like fullscreen, that with this way I can make Godot load the last saved setting, instead of starting always with the default setting of the project.

### CODE REVIEW

**Comment by akien-mga** [comment]
You can already save config to `user://override.cfg` to achieve exactly that.

**Comment by marcelofg55** [comment]
> You can already save config to user://override.cfg to achieve exactly that.

Maybe I misunderstood the code but I read it loaded res://override.cfg, not user://override.cfg. I'l re-check it...

**Comment by akien-mga** [comment]
Right, it seems to load either `res://override.cfg` or `exec_or_pack_dir/override.cfg`. The latter seems useful, but the former is a bit pointless, should likely be `user://`.

**Comment by marcelofg55** [comment]
Yeah, just re-checked and currently it doesn't loads any override from user://. But if we remove the loading of res://override.cfg we might break projects that use that (if anybody uses that at all).

**Comment by Calinou** [comment]
This could fix https://github.com/godotengine/godot/issues/18621 by the looks of it :slightly_smiling_face:

**Comment by reduz** [comment]
I am against this for two reasons:

1) you can already control everything from code, and it makes more sense this way (though what @Calinou mentions needs to be resolved), it would be redundant and confusing
2) You can save an override.cfg next to the binary if you really want and it will be opened, but I think this is not worth it.

**Comment by reduz** [comment]
I dont really think this is something worth solving IMO. I really dont see the problem of starting windowed and then going fullscreen or someting of the sort.

**Comment by reduz** [comment]
The PR is simple though, if enough people wants this I don't mind, but otherwise I just feel it makes everything more complex for something that isn't really a problem.

**Comment by akien-mga** [comment]
IMO we could just replace the `res://override.cfg` check for a `user://override.cfg` one, I don't see much use case for the `res://` one as it's typically a read-only filesystem (though, for DLCs maybe?).

I don't think there's much use for a customisable override path, since we already have some hardcoded `override.cfg` logic, we can just expand that to `user://`.

**Comment by akien-mga** [comment]
```
21:48 <reduz> yeah, i am not so against this PR after thinking about it for a while
21:48 <reduz> its simple enough and i can understand the use case
```

**Comment by akien-mga** [comment]
Now we just need to find a consensus on how it should be done exactly :D

**Comment by reduz** [comment]
I dont mind it the way this PR implements it, it makes more sense like this, so you can actually discover this function by looking at the project setting option. Otherwise it will be a cryptic or hidden feature.

**Comment by akien-mga** [comment]
Right, discoverability is a good point. I'd suggest to maybe name it `project_settings_override` instead of `custom_*` though, to make it clear that it will override other values, but you don't need to replicate the whole project settings in it.

**Comment by akien-mga** [comment]
It being a free field string may not make it clear to users that they need to type something like `user://custom_settings.cfg` to make use of it efficiently. Though I guess documentation can handle that.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
