### PR TITLE
Fix grammar mistake in Shortcut documentation

### PR DESCRIPTION
**Pull request by ArjhanToteck**
Apostrophes should not be used to form the plural under most conditions.

### CODE REVIEW

**Review by Mickeon — APPROVED** [review]
Nice, but it would be nice to squash the commits together, too. See [the Pull Request Workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

**Comment by Repiteo** [comment]
As Mickeon mentioned, this will require squashing to a single commit before it can be merged

**Comment by ArjhanToteck** [comment]
Done, they should all be merged

**Review by adamscott — CHANGES_REQUESTED** [review]
Something wrong happened, because this commit/PR is much more than just fixing a grammar mistake. Seemed to have some issues with Git.

**Comment by ArjhanToteck** [comment]
Should be fixed now.

**Review by adamscott — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
