### PR TITLE
Enchancement for tileset sorting

### LINKED ISSUE #34783: Tileset sorting wrong after 9th tile
**Godot version:** 3.2.beta4
**Godot version:** 3.2.rc4.official

**OS/device including version:** (Probably Any) (Found On: GNU\Linux\Manjaro KDE x86_64)

**Issue description:** Godot sorts tiles correct to the 9th tile. After you add 10th tile Godot puts it after 1st tile. For example: 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9.

**Steps to reproduce:** Create a TileMap node. From Inspector menu, select "New TileSet" as Tile Set. Then select an image that includes at least 10 tiles. Add at least 10 tiles using "New Single Tile" button.

**Minimal reproduction project:**
[Sorting.zip](https://github.com/godotengine/godot/files/4019413/Sorting.zip)

**Screenshot.**
Screenshot_20200103_171242

### PR DESCRIPTION
**Pull request by Pleto**
Simple fix for issue https://github.com/godotengine/godot/issues/34783. "Natural no case" comparison should be used to sort the tiles.

*Bugsquad edit:* Fixes #34783.

### CODE REVIEW

**Comment by Calinou** [comment]
There's already an open pull request solving this: #35943

**Comment by Pleto** [comment]
Sorry, it is my fault! Did not receive any notification on the initial issue. 

Normal string comparison checks each character in order and determines which string is larger based on the first "characters are not equals" encounter. => a10a < a2a (1 < 2)
Natural no case comparison will compare each character ignoring the case and when a digit is found it will compare the numbers that starts from the position of that digit. => a2a < a10a (2 < 10)

To sort the tileset in a more convenient way for user (by considering number ordering), natural no case comparison should be used.

**Comment by Calinou** [comment]
@Pleto I mean adding a comment in the code :slightly_frowning_face:

**Comment by Pleto** [comment]
Lol. I am an idiot. Here again overwhelmed by anxiety. I will add a comment in the code.

**Comment by akien-mga** [comment]
Sorry for the late review. The changes look good, but could you squash the commits together? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by aaronfranke** [comment]
@Pleto Is this still desired? If so, you need to address the above feedback and squash the commits, see [this article](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for more information. Also, this could be rebased on the latest master branch while you're at.

**Comment by Pleto** [comment]
Hello! My apologies for my inactivity. I will squash the commits during this day.

**Comment by Pleto** [comment]
I will close this pull request since I cannot merge the commits (I deleted my fork). I will make another pull request with only one "squashed" commit

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/43050.

**Pull request closed without merging**
