### PR TITLE
Make front view to be z+

### PR DESCRIPTION
**Pull request by volzhs**
Currently, Front view is from z-, actually is rear.
made it to be z+ like others, top from y+, right from x+

### CODE REVIEW

**Comment by Calinou** [comment]
See discussion in https://github.com/godotengine/godot-proposals/issues/843.

**Comment by JFonS** [comment]
We recently merged #45669 which does the opposite of this PR. I don't have a strong oppinion on what should be considered front/back, but we can't keep changing between one and the other, we need to come with an agreement :)

**Comment by volzhs** [comment]
this pr has same behavior with blender.
I didn't notice it was swapped before and it confused me that imported mesh looks back.

**Comment by aaronfranke** [comment]
Screenshot from 2021-03-22 18-10-32

For a character facing *forward* (`Vector3.FORWARD`) such that the right hand is in the *right* direction (`Vector3.RIGHT`) and the head is in the *up* direction (`Vector3.UP`), this means that the front of the character is the view from -Z, not +Z.

If you were to spin a character around the Y axis such that its front was facing +Z, then the right hand would be in the *left* direction (`Vector3.LEFT`) and the left hand would be in the *right* direction (`Vector3.RIGHT`). The inevitable conclusion is, if you want the right hand to be in the *right* direction and the left hand to be in the *left* direction, you have to make the player face *forward* (`Vector3.FORWARD`), such that its front is visible from -Z, which is the current behavior, so this shouldn't be merged.

**Comment by volzhs** [comment]
ok then.

**Pull request closed without merging**
