### PR TITLE
Improved New Project and Import project experience

### PR DESCRIPTION
**Pull request by djrm**
Hopefully this will be a better and simpler users.

**edit**: i made some improvements

now you dont have the set default folder in the dialog, maybe it would be better to add a button to open the editor settings from the manager.

you can create a project folder right from the dialog
screenshot from 2017-09-23 22-43-56

also the non error messages are hidden by default, the warnings can be viewed by pressing the status icon.
screenshot from 2017-09-23 22-44-04

screenshot from 2017-09-23 22-44-15

if you cancel the creation, or change the path the manager will get rid of the created folder, so you can create a new one.

and this is how the errors look.
screenshot from 2017-09-23 22-44-29

### CODE REVIEW

**Comment by cryptonaut** [comment]
Minor nitpick but I think the messages should say "will be created **in**" instead of "will be created **on**".

**Comment by hpvb** [comment]
I like the changes! I haven't looked at the commit itself in depth though.

**Comment by groud** [comment]
I like the changes too, but IMO those messages are a little bit too intrusive.

For me the ideal solution would be to have an icon next to the path field or the import button, and the message is displayed when hovering over the icon. We could have two icons, one for warning message and one for errors. This would be like the Eclipse IDE does.

**Comment by toger5** [comment]
Maybe there just could be. One checlbox which allows to choose if godot ahould create a dedicated folder...
This would make it as obvious without forcing the user to read everything.
```
[checkbox] Create folder for project.
```
Checking this box updates the path, so it is obvious, that the project is now created inside the subfolder.
Path before:
`Users/name/Documents/godotProjects/`

Path when the box is checked:
`Users/name/Documents/godotProjects/New Game Project`

Maybe we could wven display the `.project` (or however it is called atm.

Path before:
`Users/name/Documents/godotProjects/New Game Project.project`

Path when the box is checked:
`Users/name/Documents/godotProjects/New Game Project/NewGameProjwct.project`

I think that would make it as obvious than the messages + brings the advantage that ppl who dont know how godot behaves can choose a folder and can adapt there the folder dependent on what they thought godot would do.

If they created a subfolder -> they deactivate `create folder for project` if they didnt vice versa...

**Comment by Sslaxx** [comment]
Why would it by default *not* create a directory for a new project?

**Comment by toger5** [comment]
@Sslaxx whatever you are used to and which software you use.
But you could be right, that creating a folder for the project is the better standard.
(but there definitlt should be the option... I remeber when i was using windows that each installer did it differently and i always ended up with some rpograms on the top lvl and some programs one lvl too deep ;)  )

**Comment by djrm** [comment]
Maybe adding a button next to the Project name to create a folder, also im not that sure about automatic folder creation, i dont know the filesystem restrictions with the characters and since the project name can be anything, im not sure about this (of course we could sanitize the name but it might be confusing).

also icons instead of message would be good too, but i dont know if it is better to be explicit (specially for newcomers)

@cryptonaut yeah will change that

**Comment by akien-mga** [comment]
What's the state here? Do you still want to make changes?

**Comment by djrm** [comment]
@akien-mga yeah i will made some changes

**Comment by akien-mga** [comment]
Ping.

**Comment by djrm** [comment]
@akien-mga still planning to work on this, however the rename PR introduced some conflicts, and the code that was already messy got worse, im thinking about rewriting that dialog.

**Comment by djrm** [comment]
@akien-mga i updated this, i think it can be merged now.

**Comment by drproteus** [comment]
Not sure what happened between this commit and current release, but this behavior is not present in v3.1.1.stable.official. It continues to demand an empty but present directory.

**Comment by nathanfranke** [comment]
> Not sure what happened between this commit and current release, but this behavior is not present in v3.1.1.stable.official. It continues to demand an empty but present directory.

See https://github.com/godotengine/godot/pull/15835 (disallow in `3.x`) and https://github.com/godotengine/godot/pull/42526 (allow in `4.x`). If you want this feature in `3.x`, the latter PR must be backported or cherry-picked.

**Pull request merged**
