### PR TITLE
Fix android debug to use debug and not release_debug

### PR DESCRIPTION
**Pull request by thebestnom**
as asked in https://github.com/godotengine/godot/pull/36776#pullrequestreview-369794378

### CODE REVIEW

**Comment by akien-mga** [comment]
That's incorrect, debug export templates should be built as `release_debug`. Here's the build matrix:
- Editor build, development: `tools=yes target=debug` (default)
- Editor build, release: `tools=yes target=release_debug`
- Template build, debug: `tools=no target=release_debug`
- Template build, release: `tools=no target=release`

**Comment by thebestnom** [comment]
this is not for template build (as I was instructed) and more for debug build built by android studio, am I wrong?

**Comment by thebestnom** [comment]
so how can we make sure that the build is built with symbols?

**Comment by thebestnom** [comment]
@m4gr3d mind adding to the converstion?

**Comment by akien-mga** [comment]
> this is not for template build (as I was instructed) and more for debug build built by android studio, am I wrong?

Well AFAIK until #36776 is finalized and merged, that gradle file is used to build the Android export templates, i.e. `tools=no`. For those the main targets users should care about are `release` and `release_debug`. It is however still useful to do `tools=no target=debug` builds when you want to have full stacktraces for crashes in `adb logcat`, so this should be possible too.

Once `tools=yes` is supported, as mentioned, the two valid targets are `release_debug` and `debug`. The editor can't be built as `release` since that would remove debug options necessary for actual use of the editor.

So all in all the Android Studio integration should offer the same options as SCons' `detect.py`.

**Comment by thebestnom** [comment]
So we should just close this PR and merge it with https://github.com/godotengine/godot/pull/36776 and while doing so adding release_debug to it?

**Comment by m4gr3d** [comment]
@thebestnom There are also additional side effects of `doNotStrip` that make it trickier to use. So yes, for now let's close this PR and I'll look into an alternative option to provide similar functionality while respecting the parameters that @akien-mga mentioned.

I've opened #36863 to track this work.

**Pull request closed without merging**
