### PR TITLE
Added more translatable strings in code. Updated template tools.pot.

### PR DESCRIPTION
**Pull request by DmitriySalnikov**
also improved Russian localization.

### CODE REVIEW

**Comment by DimOkGamer** [comment]
damn

**Comment by akien-mga** [comment]
Yeah sorry I just pushed an update to the .pot and all the .po files :/

**Comment by DimOkGamer** [comment]
I'm trying update my files to the new version....

**Comment by akien-mga** [comment]
Note that to avoid such hard to fix conflicts for a future PR, I'd advise you to do first a commit to change the source code, and only then make a second commit to regenerate the .pot file and update all .po files (using ``make all``).

**Pull request closed without merging**
