### PR TITLE
Subarray patch

### PR DESCRIPTION
**Pull request by gau-veldt**
This is a fresh version of the subarray patch for `DVector` properly put into its own branch.  Please see #5765

### CODE REVIEW

**Comment by gau-veldt** [comment]
Should I by trying to keep the branch recent to upstream in the event something upstream breaks the changes (and I have to fix something) before they are accepted?

**Comment by gau-veldt** [comment]
this is #5765 placed properly into a separate branch of my fork

**Comment by gau-veldt** [comment]
Something was mentioned about the whole point of branches being to prevent merge commits however fetching upstream on the branch would result in that very thing happening which is why I ask about keeping the branch updated while waiting on the PR to be accepted.

**Comment by vnen** [comment]
No need to keep the branch always up-to-date. In the event of merge conflicts, then you'll have to solve them (which will only happen if someone touches the same code you are changing). But until this is reviewed and ready to merge keeping the branch updated would be unneeded work.

**Comment by gau-veldt** [comment]
(Related also to #5701 and possibly #4715 as well)

**Comment by gau-veldt** [comment]
+vnen okay, thanks for that.  I guess the team has other priorities.  I have hacks I can use (that make multiple memory copies of the entire data) in actual games using the current engine until the PR makes it in.

**Comment by akien-mga** [comment]
@gau-veldt When you pull the upstream branch, use ``git pull --rebase`` so that it does not create a merge commit, but instead reapply your changes on top of the upstream master HEAD.

**Comment by gau-veldt** [comment]
@akien-mga Where does that step fit into the process used to update form a fork?  I'm using the steps from [this article](https://help.github.com/articles/syncing-a-fork/) to update a fork with remote changes.

**Comment by vnen** [comment]
@gau-veldt you can replace all steps to just this command: `git pull --rebase upstream master`.

**Comment by gau-veldt** [comment]
@vnen now git is whining that I'm behind when I try to push the local rebase to my fork do I have to force-push with -f?

**Comment by vnen** [comment]
@gau-veldt yes, you need to force push.

**Comment by gau-veldt** [comment]
@vnen from what I can tell the log indicated after your command that it was still on my commit (behind the remote) after the `git pull --rebase upstream master` but when I followed it up with @akien-mga 's `git pull --rebase` the log was up to reduz's last commit which is up-to-date.

So looks like it needs both forms of git pull To Do The Right Thing (TM)

**Comment by akien-mga** [comment]
Didn't work :)
``git pull --rebase`` would likely pull your ``origin/master`` branch, so you need to specify ``git pull --rebase upstream master`` as advised by @vnen. It's normal that after this command your own commits show on top, as it's the purpose of the rebase.

**Comment by gau-veldt** [comment]
I think I'll take @vnen 's original advice - don't touch the branch until the PR is actually accepted.  not sure of any threshold for doing an update, maybe if github starts saying it has a conflict?  Conflict will happen when someone touches core/dvector.h (least likely), core/variant_call.cpp (more likely), or doc/base/classe.xml (extremely likely!!!)

**Comment by gau-veldt** [comment]
@akien-mga As I mentionend when I did just @vnen 's command it downloaded the updates but didn't apply anything; the log was still at my last local commit.  I followed it up with `git pull --rebase` and `git log -n 1` then properly showed the most recent commit locally and my changes were still there as well.  The weirdness comes when this gets pushed back to the branch on the fork.

**Comment by akien-mga** [comment]
That's why I wrote:

> use `git pull --rebase` so that it does not create a merge commit, but instead reapplies your changes **on top** of the upstream master HEAD.

and

> It's normal that after this command your own commits show on top, as it's the purpose of the rebase.

Rebasing means that your branch is reset to that other branch you're rebasing on (here upstream/master), and it reapplies your own commits (the one that are not in that branch) one by one on the branch HEAD. So it *should* show your own commits at the top of the `git log`.

**Comment by akien-mga** [comment]
Of course all of the above supposes that you have a remote named `upstream` that points to this repo.

**Comment by gau-veldt** [comment]
@akien-mga I had added that right back when I cloned the fork

**Comment by gau-veldt** [comment]
@akien-mga  I see in the log that all the commit hashes are altered...  So it's rebasing my changes at every step of the replay of the upstream's commits.

**Comment by akien-mga** [comment]
Well the problem here is that you rebase the upstream branch on top of your own, instead of rebasing your own on top of the upstream one. So it generated 68 new commits with new hashes, instead of generating only 4 of them for your own commits.

To clean your branch now, you should try something like `git rebase -i HEAD~72` and remove the 68 extraneous commits... Or create a new branch for upstream/master and cherry-pick your commits on top of it.

**Comment by gau-veldt** [comment]
@akien-mga That's going to put it back to being behind isn't it?

**Comment by akien-mga** [comment]
Yes, but it will be better than having diverged by 68 commits on both ends :)

**Comment by gau-veldt** [comment]
@akien-mga unless you give me a clear step to make this up-to-date without problems like these I think I'm leaving it behind unless a conflict emerges

**Comment by gau-veldt** [comment]
**PS:** It confuses `git push` slightly too (hence why it needs `-f` since it doesn't know about the rebase) and has to be forced.

**Comment by gau-veldt** [comment]
The reason I want the branch is I have the idea put methods somewhere to expose the zlib functionality to strings and buffers since as it currently stands the compression is only used internally for PNG decoding.  It would be useful (especially networked games) to be able to compress certain network data (bandwidth costs money).  That would be another branch obviously.

**Comment by gau-veldt** [comment]
@vnen @akien-mga By the way thanks for the help with git and it's Dr. Suess-esque confusion-inducin'

**Comment by akien-mga** [comment]
The ``--force`` is necessary because when your commits are rebased on top of the upstream branch, their commit hash necessarily changes (as they don't have the same parent commit anymore). So it means that the four hashes of your remote no longer match the four hashes of your local branch, so you need to force push to overwrite the remote.

**Comment by akien-mga** [comment]
Now if you want to practice your git-fu further, I would suggest that you "squash" your four commits together, in order to have one single commit instead of four.

Here are the steps to do so:
- ``git rebase -i HEAD~4``: will show an editor where you can do action on the four last commits of the branch)
- in the editor, you should see the four commit logs, each on a line, with `pick` in front of each hash.
- replace the `pick` for the 2nd, 3rd and 4th commits with `squash` or `fixup`, and save. It will merge them all into their parent, i.e. here the first commit

The difference between squash and fixup is that the latter will discard the commit logs, while the former will append their commit log to their parent's. Personally I'd use `reword` for the first commit, `fixup` for the three next, and then just edit the log of the first commit to ensure it describes the full changes properly.

If it doesn't work and messes up your branch, don't force push! :D Instead you can always abort the rebase if need be with ``git rebase --abort``, and if changes were done, reset to the remote with ``git reset --hard origin/subarray_patch``.

**Comment by gau-veldt** [comment]
Someone not aware of that (that --rebase is going to require a force-push) may be incorrectly led to think they are doing something wrong that isn't and then try to 'fix' it and actually do cause major damage (as in my case history proves just happened).

**Comment by gau-veldt** [comment]
Before I try that step how do I change history and edit a commit log?

**Comment by akien-mga** [comment]
> Before I try that step how do I change history and edit a commit log?

To edit the log of the last commit, you can do `git commit --amend`. To edit the log of an early commit, the way I do it is via `git rebase -i HEAD~<number of commits>`, and then I replace `pick` for the relevant commit by `reword`.

**Comment by gau-veldt** [comment]
What about just modifying the text of the post-squash commit?

**Comment by akien-mga** [comment]
You'd do that with ``git commit --amend`` then.

**Comment by gau-veldt** [comment]
As usual my ADHD mind is being slow to pick up on things...  the reword in the editor file first rebase is going to do everything I needed (pop up yet another editor for rewording).  I shouldn't need to change it afterward.  I didn't have to ask that last question.  :)

**Comment by RandomShaper** [comment]
@gau-veldt, I can feel your pain as my first PRs for Godot (my first real and intense usage of Git after having used SVN for years) were messy until I got up how merging, rebasing, etc. worked.

You'll get it eventually in no time.

Regarding doing hacks before the PR gets merged I can recommend to you the same I'm doing on this cases: I have a little batch file which fetches the master branch and then applies (`git merge` and or `git cherry-pick`) any branches or commits of mine still pending merging.

You have to build the editor yourself and if your changes also affect the runtime, then you have to build them as well. I'm maintaining that way my local fork of Godot editor and Android export templates and it's not a big pain.

**Pull request merged**
