### PR TITLE
Revert "Implement parallel foreach() for easier multithreading"

### PR DESCRIPTION
**Pull request by RandomShaper**
Reverts https://github.com/godotengine/godot/pull/72784. The WTP changes will be reverted until the topic can be discussed in its entirety, with some possibly coming back when there's a stronger agreement.

(CC @myaaaaaaaaa)

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]

**Comment by myaaaaaaaaa** [comment]
To address @reduz's points from #72784 :

> I really, really think this should not have been merged. You don't need the syntactic sugar for something very seldom used that all it does is make readability worse.
> 

See the following PRs for places where readability is improved:
#78016 ( Relevant commit: https://github.com/godotengine/godot/pull/78016/commits/1048a464c781d6f1ed4574fc98de591a393528d2 )
#79481
#79490

Note that the current signature is due to prioritizing feature parity with `WorkerThreadPool::add_*_group_task()` and `for()`, since most of the work is in the above three PRs that do most of the refactoring. I would recommend renaming it with a cleaner signature in the future.

> This is not a general purpose function, it is meant for large tasks. if you use it in any array all you will achieve is it probably being much slower than just doing a regular for loop and users will not understand why.
> 

This is addressed by #72716 .

**Comment by YuriSizov** [comment]
Thanks! Let's discuss this more thoroughly (on the contributors chat, preferably) and find a good solution that we can implement in one go. I think readability improvements from this change were great, but we need to make sure it doesn't come at a cost of confusion or, worse, performance.

**Comment by myaaaaaaaaa** [comment]
> ...find a good solution that we can implement in one go.

[I generally prefer to approach refactors and changes to core in small commits](https://codingitwrong.com/2021/09/08/small-commits-and-the-power-of-git-bisect.html), since it lets each change be tested in isolation, makes things easier for reviewers,[^refactor] and makes any potential regressions easier to bisect.

But I see that doing things this way created its own problems by making things overly confusing to keep track of.

[^refactor]: Huge squashed commits are generally discouraging to review and get delayed a lot in practice. #49362 is possibly the biggest victim of this.



In that case, would you be willing to accept a PR with multiple commits (obviously with each individual commit passing CI)? This way, reviewability and bisectability are maintained, while making it easier to keep track of the big picture under one PR.

This is assuming of course that `parallel_for()` is still a desired feature, since reduz seemed particularly against it.

**Comment by YuriSizov** [comment]
> But I see that doing things this way created its own problems by making things overly confusing to keep track of.

Well, it's more about the snowballing effect. We merge one change that looks okay-ish, and it breaks stuff, and so we patch it, and it potentially breaks more stuff. And each solution becomes progressively more hacky, making the whole thing much less appropriate and much less likely to pass the quality control for the core.

So to avoid that we need to arrive to a well-vetted solution before implementing it.

**Pull request merged**
