### PR TITLE
Fix unclear `PROPERTY_USAGE_STORAGE`/`EDITOR` description

### PR DESCRIPTION
**Pull request by mickeyordog**
Mentioned in this issue https://github.com/godotengine/godot/issues/93679

### CODE REVIEW

**Comment by Mickeon** [comment]
You forgot the period

**Comment by mickeyordog** [comment]
Done

**Review by Mickeon — APPROVED** [review]
It's the small things that count.

(Commits still would need to be squashed)

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
