### PR TITLE
Optimized execution of _integrated_forces

### PR DESCRIPTION
**Pull request by AndreaCatania**
Optimized execution of _integrated_forces.
@reduz let me know what do you think about it.

### CODE REVIEW

**Comment by NathanWarden** [comment]
Very nice and simple optimization! :) Minor nitpick... shouldn't "has_transform_change" be "has_transform_changed"?

**Comment by AndreaCatania** [comment]
@NathanWarden exactly! :) let me change it

**Comment by reduz** [comment]
This does not make sense to me. If nothing changed, why sending the transform notification in the first place?

**Comment by AndreaCatania** [comment]
The function **_direct_state_changed** differently as its name suggest is called each frame to integrate forces.

This mean that each frame the transformation is sent to the body even if there aren't changes or if the body sleep. This check make sure to send new transform only when there is a change.

Initially I was executing the function "_direct_state_changed" only when there was a position change but I got some audio problems because this function must be executed each frame

**Comment by reduz** [comment]
> This mean that each frame the transformation is sent to the body even if there aren't changes or if the body sleep. 

If the body sleeps you should **not** call the function, that's the whole point of it

**Comment by AndreaCatania** [comment]
@reduz Right

**Pull request closed without merging**
