### PR TITLE
Fix a typo in the Array class documentation

### LINKED ISSUE #4049: Typo in Array, Variant pop_front ( )
Good day,

There is a typo in the Array documentation:
https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-pop-front

Removes and returns the first element of the array. Returns null if the array is empty, **wwithout** printing an error message.

Thank you and have a good day.

### PR DESCRIPTION
**Pull request by Calinou**
This closes https://github.com/godotengine/godot-docs/issues/4049.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Xrayez** [comment]
Perhaps it's time to run the spell check tool on the entire class reference now, or too difficult? I cannot recall.

**Comment by Calinou** [comment]
> Perhaps it's time to run the spell check tool on the entire class reference now, or too difficult? I cannot recall. Aren't typos checked already? Or is it only for godot-docs repository?

I believe We could integrate this into CI using `codespell` eventually :slightly_smiling_face:

**Comment by akien-mga** [comment]
> 
> 
> > Perhaps it's time to run the spell check tool on the entire class reference now, or too difficult? I cannot recall. Aren't typos checked already? Or is it only for godot-docs repository?
> 
> I believe we could integrate this into CI using `codespell` eventually 🙂

I ran `codespell` a couple of days ago, so it seems it didn't catch this one.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
