### PR TITLE
Update mouse location on background scroll and window focus in macOS

### PR DESCRIPTION
**Pull request by ColinKinloch**
This fixes two issues in macOS:
1. Scrolling on an unfocused godot window scrolls the panel at the location the mouse was when the window lost focus.
2. Clicking a godot window into focus, then clicking again activates the UI element at the location the mouse was when the window lost focus. For me, this is usually the play (restart) button.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @bruvzg @marcelofg55 for review (or any other Mac-owning contributor that would like to help review such PRs, let me know :))

**Comment by bruvzg** [comment]
Works OK for me. Both issues are reproducible and fixed by this PR.

**Comment by akien-mga** [comment]
Awesome, thanks! I just merged #23100 which adds a merge conflict, could you rebase @ColinKinloch?

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7. (Also with #23499 as follow-up.)

**Pull request merged**
