### PR TITLE
Add extra unit tests for Geometry2D

### PR DESCRIPTION
**Pull request by kneejuicer**
This PR adds extra unit tests for the `Geometry2D` class.

Using lcov, I checked which paths were not covered yet and wrote some tests based on that.
For the `Geometry2D.h` file, this PR improves the line coverage from 55.7% to 89.1%.

This PR is part of https://github.com/godotengine/godot/issues/43440.

I'd love to get your feedback.

### CODE REVIEW

**Comment by kneejuicer** [comment]
Added the new line at the end of [test_geometry_2d.h](https://github.com/godotengine/godot/pull/59643/files#diff-1d55fb0ed9bd97dd44c5a410d69ccd47d7314e98eb037565afb1a7ec5510064c) to comply with the `.clang-format`.

**Comment by kneejuicer** [comment]
Fixed float/double types in tests for `segment_intersects_circle`.

**Review by akien-mga — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
