### PR TITLE
Fix profiler frame number stops updating when window is minimized

### LINKED ISSUE #37341: Profiler frame number stops updating when game window is minimized
**Godot version:**
Master branch 
a2da99f40cf2123c0906c734a2eb01e9b65a45a2

**OS/device including version:**
Windows 10

**Issue description:**
When profiler is running and game window is minimized, the frame number at the top right of the profiler will stop updating. Meanwhile the profiler will still be running - still outputting graph, statistics.

Additional remark : During this time (when the game window is minimized), if we try to export measures as CSV, the Editor will crash. It doesn't happen _as often_ when the game window is not minimized. Closely related to #34640

**Steps to reproduce:**
1. Create an empty project.
2. Add a 2d Node and attach a script to it. 
3. Run the scene.
4. Start the profiler.
5. Minimize the game window.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/4390132/test.zip)

### PR DESCRIPTION
**Pull request by SkyLucilfer**
Fix #37341

I confirm this issue is happening in 3.2 too, but I'm making the change on master. I don't know if this is the right workflow, I can force push another commit if needed.

### CODE REVIEW

**Comment by SkyLucilfer** [comment]
@Faless I guess it's appropriate to inform you about this pull request. I couldn't tag a reviewer though :(

**Comment by akien-mga** [comment]
I guess the change makes sense. WDYT Fabio?

**Review by Faless — APPROVED** [review]
Yeah, this seems to be the right solution.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
