### PR TITLE
Added primary clipboard for Linux

### LINKED ISSUE #3440: Implement middle-clicking to paste with primary clipboard in X11
### Describe the project you are working on

Any project while on a Linux OS using X Window.

### Describe the problem or limitation you are having in your project

While coding a GDScript in the Godot editor, if I middle-click to paste the primary selection, nothing happens.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It would be useful while coding to use the middle-click paste functionality of Linux system to improve coding.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Not applicable.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No possible workaround, except maybe with external clipboard software.

### Is there a reason why this should be core and not an add-on in the asset library?

Because as a Linux user it feels bad when the middle-click doesn't work, since it's a very useful feature that I normally use in any other program.

### PR DESCRIPTION
**Pull request by ConteZero**
This commit add support for primary clipboard on Linux to handle text paste with middle mouse button.
It should solve [https://github.com/godotengine/godot/issues/3030](https://github.com/godotengine/godot/issues/3030)

This is based on code originally written by @Larpon, I fixed some bugs, added small improvements and updated the code to make it work with current master branch.

*Bugsquad edit:* Fixes https://github.com/godotengine/godot-proposals/issues/3440.

### CODE REVIEW

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Can't comment on `DisplayServer` side, but overall looks okay.

One other thing to note, we should probably move the paste blocks into a method something like `paste_primary_clipboard()`. Then for `TextEdit` allow it to be overridden similar to `paste()`.

**Comment by ConteZero** [comment]
@Paulb23 I've done some changes in how primary clipboard selection is handled to solve a bug in the previous code.

**Review by Paulb23 — CHANGES_REQUESTED** [review]

**Review by Paulb23 — APPROVED** [review]
GUI changes LGTM.

**Review by akien-mga — APPROVED** [review]

**Comment by ConteZero** [comment]
I would like to send a pull request for the 3.x branch to backport this feature, can I do it or should I wait for this one to be merged?

**Pull request merged**
