### PR TITLE
Option to disable Unix Socket for platforms that don't support it

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
squashed commits. Added comment

### CODE REVIEW

**Comment by fire** [comment]
This has no changes to the engine other than the comment? Did you make a mistake?

**Comment by jeronimo-schreyer** [comment]
Remi asked me to add a comment to this line to avoid a future cleanup. This is something I need to disable for some consoles to work. The idea in the future is to make dependencies feature-based rather than OS/System-based

**Comment by aaronfranke** [comment]
If you're going to only add a single comment, you should at least make it end with a period :)

Also, not that it really matters, but it would be nice to rebase this while you're at it.

**Comment by jeronimo-schreyer** [comment]
this is not just a comment. Original commit adds a define to disable unix socket posix for devices that don't support it

**Comment by aaronfranke** [comment]
As with the other PR, the source repository was deleted, so this PR is no longer valid.

Feel free to open a new PR.

**Pull request closed without merging**
