### PR TITLE
Experimental Docker image for godot

### PR DESCRIPTION
**Pull request by mrezai**
Hi.
This is an experimental Docker image that can be used on Linux, Windows and Mac to build custom versions of godot in the same way on all platforms, specially when someone wants to integrate a new godot module.
An initial help provided in README.

### CODE REVIEW

**Comment by akien-mga** [comment]
Tested it on Linux, it works great! I just built the android template in my docker image.

The README is great, the only thing I missed when going through it as a complete docker noob was that I had to add myself to the "docker" group, restart my session so that the group change is taken into account, and then start the docker daemon with ``systemctl start docker``. I guess that's basic docker usage, but it might be handy to have it in our README too for users who are not familiar with docker at all.

**Comment by mrezai** [comment]
@akien-mga README updated.

**Comment by akien-mga** [comment]
Thanks. I'm merging as it's just awesome :D
Do you think you could add a script to initialize the emscripten/html5 build environment?

**Comment by mrezai** [comment]
I have installed emscripten and built godot once but before add it to docker image I should learn and test  more.

**Pull request merged**
