### PR TITLE
enet: Sync with upstream commit c44b7d0

### PR DESCRIPTION
**Pull request by akien-mga**
https://github.com/lsalzman/enet/commit/c44b7d0f7ff21edb702745e4c019d0537928c373

### CODE REVIEW

**Comment by mhilbrunner** [comment]
LGTM, simple enough change (albeit I dislike people mixing ternary operators and pointers in complex networking code :'D)

Not using ye olde approve button as this should probably be rubberstamped by Fabio, but you can take this as my approval.

**Comment by akien-mga** [comment]
> Not using ye olde approve button as this should probably be rubberstamped by Fabio, but you can take this as my approval.

That possibly means condemning this PR to weeks of limbo, Fabio is a busy man :P

**Review by mhilbrunner — APPROVED** [review]
I'll take the blame then. It is harmless enough.

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Pull request merged**
