### PR TITLE
Fix PathFollow3D updating on unit_offset 0

### LINKED ISSUE #35511: PathFollow does not update when unit_offset set to 0
**Godot version:**

3.1.2.stable.custom_build

**OS/device including version:**

Linux 5.4.13-arch1-1

**Issue description:**

My game contains paths that trains follow. Every path has a tunnel at the start and the end.
I'd like to be able to modify the path and have the tunnels always stay at the start and the end.
I'm able to get the end tunnel to update, but not the start, as setting `PathFollow.unit_offset` to `0` does not seem to update the Transform.

**Steps to reproduce:**

1. Create the following script
```
tool
extends PathFollow
class_name PathPin

export(float, 0, 1) var pin := 0.0

onready var path: Path = get_parent()

func _ready():
	path.connect("curve_changed", self, "_on_curve_changed")

func _on_curve_changed():
	unit_offset = pin
```

2. Attach it to a pathfollow that is child to a Path
2a. Ensure `loop=false` otherwise it will [wrap back to the start](https://github.com/godotengine/godot/issues/7665) (probably fixed in 3.2)
3. Drag the first point of the path around
4. Note that the `PathFollow` does not update its transform to match the start of the path
5. Set `pin > 0`
6. Drag the path around
7. Note that the `PathFollow` now _does_ update its transform

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot/files/4108618/example.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #35511

### CODE REVIEW

**Comment by akien-mga** [comment]
Is there a similar issue in 2D?

**Comment by KoBeWi** [comment]
No, `delta_offset` does not exist in 2D. Also I tested to make sure and it's fine.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
