### PR TITLE
Icons for VScript types

### PR DESCRIPTION
**Pull request by djrm**
screenshot from 2016-08-11 19-35-24

### CODE REVIEW

**Comment by reduz** [comment]
seems good, the only one I failed to recognize at first sight was AABB

maybe as
  a  b ?
a  b

**Comment by reduz** [comment]
as in, reads as baba to me :P

**Comment by djrm** [comment]
@reduz 
this is the best i can do:
screenshot from 2016-08-10 17-02-28

the problem is the space, if  only i had 4px more

**Comment by reduz** [comment]
it should be fine, i don't think it's a datatype that appears often anyway

**Comment by djrm** [comment]
okay then i will use the second option

**Pull request merged**
