### PR TITLE
Tweak Signal Documentation

### PR DESCRIPTION
**Pull request by Mickeon**
- Add missing operator and leading description
- Avoid calling "Signal" an object or class. 
- Add more details to `connect` and `disconnect`. There are ported from https://github.com/godotengine/godot/pull/67880.
- Other tweaks all around.

### CODE REVIEW

**Comment by RedMser** [comment]
I feel like the docs are missing two infos along the lines of "you usually don't really want to instantiate this type by hand using the constructors, the engine does that for you with the `signal` keyword in GDScript or `[Signal]` annotation in C#" and "you'll mainly be using this type when working with the `object.signal_name.connect(...)` syntax".

I know the former is mentioned in the linked tutorial, but just reading these class docs doesn't make the internal nature of this type clear enough IMO.

(Disclaimer: not sure if that's how signals still work in today's C# integration!)

**Comment by Mickeon** [comment]
I have to admit I have gotten lazy after the major Object documentation overhaul, and I don't have the time to test every function thoroughly once more. My biggest doubt about Signals right now is that there is both `Object.add_user_signal()` and the Signal constructor, and at this moment in time, I cannot check if they essentially do the same thing. Regarding empty Signal & Callables, I don't see why one would want to manually create them if not as placeholders. So that may need to be noted.


You're right in needing to mention that GDScript does a lot of the work for you. Signals can be defined for the entire custom class with the keyword, and so can Callables with the `func` keyword. Both Signal and Callable  (https://github.com/godotengine/godot/pull/68262)'s documentation need to be carefully looked at.

**Review by akien-mga — APPROVED** [review]

**Comment by Mickeon** [comment]
Going to use the excuse of a merge conflict to elaborate a bit more, since it was going to be done at some point anyhow.

**Review by mhilbrunner — APPROVED** [review]

**Comment by Mickeon** [comment]
Force-pushed again because the Mac build craves to fail whenever it feels like it.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
I noticed we're getting new warnings because a codeblock tag from this PR should actually be codeblocks, plural. 🙃

**Comment by Mickeon** [comment]
https://github.com/godotengine/godot/pull/69107

**Pull request merged**
