### PR TITLE
Remove "TODO" instances in the docs

### PR DESCRIPTION
**Pull request by YeldhamDev**
<s>While those "TODO"s are not done, make them look a little better and consistent with the other "TODO"s in the docs.

I would try to do some of them myself, but I don't know to to put images in the docs, or that this was even possible in the first place.</s>

Remove them instead.

### CODE REVIEW

**Comment by akien-mga** [comment]
I would remove those TODOs altogether. If there are improvements to make, they should be tracked in a godot-docs issue, not in the user docs.

**Comment by akien-mga** [comment]
```
$ rg TODO -il
SpotLight.xml
Font.xml
KinematicBody.xml
KinematicBody2D.xml
```

**Comment by YeldhamDev** [comment]
@akien-mga Done.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
