### PR TITLE
Add/expose VisualServer::get_default_clear_color()

### PR DESCRIPTION
**Pull request by RandomShaper**

### CODE REVIEW

**Comment by vnen** [comment]
Is this worth merging before the renderer update?

**Comment by akien-mga** [comment]
I'd say probably worth merging in the 2.1 branch, but for 3.0 it might indeed conflict with @reduz's existing work.

**Comment by RandomShaper** [comment]
I checked the gles3 branch before submitting this and due to the primitive
status of the new VisualServer I thought it would not be an issue.

So if @reduz doesn't mind, this could be merged as a reminder to include
this facility in the new implementation since I believe since both getting
and setting the clear color is useful for some cheap effects.

Anyway, probably I should not be submitting additional PRs related to
rendering. What do you think?

**Comment by akien-mga** [comment]
I think indeed for now it's best to avoid touching VisualServer in the master branch - @reduz is not a pro when it comes to resolving merge conflicts, so we're trying to keep the gles3 branch easy to merge into master as soon as it's functional.

On the other hand you could push some improvements to the 2.1 branch - and also for the time being keep this PR opened to be reassessed once the gles3 branch is merged (or make a PR on the gles3 branch directly).

**Comment by razvanc-r** [comment]
What about also a `set_default_clear_color` while we're at it?... if it isn't already implemented

**Comment by RandomShaper** [comment]
The setter already exists.

Which is a stronger reason to merge this PR. :-D

**Comment by bojidar-bg** [comment]
I agree with @RandomShaper -- given that the setter is already there, and there is little reason for it changing in gles3, I think this is mergable. If @akien-mga is really scared that it might result in a merge conflict, he might run the merge manually and check if it is so bad :smiley_cat:

**Comment by akien-mga** [comment]
I'm not scared, I just don't want @reduz asking me to revert commits so that he can merge his branch without conflicts :P

**Comment by akien-mga** [comment]
Let's merge, the patch is not too intrusive and I'll do the gles3 branch merging if need be :)

**Pull request merged**
