### PR TITLE
OS X: do not use cached mouse position on mouse down

### PR DESCRIPTION
**Pull request by underdoeg**
Without this fix, godot becomes unusable with an iiyama touchscreen on OS X.

On OS X godot only updates the mouse position on mouse move. But on a touchscreen there is no mouse move preceding a mouse down event. So the old (cached) mouse move position is used to trigger the touch down event. This results in irratical touch down and up behaviours. This PR makes sure the mouse position is updated from the OS before feeding the event into the Input system.

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you squash commits together?

**Comment by underdoeg** [comment]
sorry, made a mistake when I tried to squash them. will create a new PR in a second...

**Comment by akien-mga** [comment]
Also FYI, your current git author details are invalid:
```
From: snm <snm@touchscreen.local>
```

**Comment by underdoeg** [comment]
yes, thanks. one of the reasons. I recreate it. I only use the mac for deployment and did not have it set up correctly.

**Comment by underdoeg** [comment]
https://github.com/godotengine/godot/pull/26696

**Pull request closed without merging**
