### PR TITLE
mono: add IsInstanceValid(), move WeakRef()

### PR DESCRIPTION
**Pull request by KellyThomas**

### CODE REVIEW

**Comment by neikeq** [comment]
Do you think this would be better as a static method in `Godot.Object` instead of `Godot.GD`? This way, the class prefix won't be needed when calling it from `Godot.Object` derived classes, which I think is the majority of the time.

**Comment by aaronfranke** [comment]
If you make an extension to Godot.Object, it may be best to merge [this PR](https://github.com/godotengine/godot/pull/20707) first.

**Comment by KellyThomas** [comment]
@neikeq I agree with that reasoning and have moved it over to the `Object` class.

By the same logic we could consider moving `FuncRef()` and `WeakRef()` as well.  What do you think?

I will be happy enough to rework this to suit #20707 if required.

**Comment by neikeq** [comment]
> By the same logic we could consider moving `FuncRef()` and `WeakRef()` as well.  What do you think?

The reason to have `IsInstanceValid` in `Object` was not only because it makes it less verbose to use, but also that the method is related to this class. `FuncRef()` is not related to `Obect`. `WeakRef()` sounds good.

**Comment by KellyThomas** [comment]
OK, I have moved `WeakRef()` over.

**Comment by neikeq** [comment]
Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
