### PR TITLE
set TextEdit's cursor column to 0 on first draw to prevent h_scroll

### LINKED ISSUE #33865: Previously opened script's horizontal scrollbars are shifted after application restart
**Godot version:**
v3.2.beta.custom_build.28613ab8c

**OS/device including version:**
Windows 10

**Issue description:**
Godot remembers for each script position of a text cursor. And after restart tries to set position of the horizontal scrollbar so that the text cursor is located at the beginning of the editor space.
Scrollbar should always be at position 0 (or as it was before)

scroll_offset_bug

### PR DESCRIPTION
**Pull request by Leleat**
Closes #33865.

Not sure if this should be done in TextEdit since that behaviour mentioned in the issue may be a feature as well.

### CODE REVIEW

**Review by Paulb23 — CHANGES_REQUESTED** [review]
Yeah this is a feature, we set the `column` / `h_scroll` [here](https://github.com/godotengine/godot/blob/master/editor/code_editor.cpp#L1427-L1431), as part of the restore state when the editor launches.

Either we don't restore the `column` / `h_scroll` in the above method, or prevent `TextEdit` from re-calculating the scroll from what we restore it to. Personally, I'm in favour of fixing the latter, but don't mind if the former is more desired.

**Comment by Leleat** [comment]
I am sorry. I don't understand this part. Can you please explain more? 

> prevent TextEdit from re-calculating the scroll from what we restore it to

What is the intended behaviour? We put the cursor at the saved position but don't adjust the scrollbars to that position?

**Comment by Paulb23** [comment]
Sure, I mean that we restore it to the exact state that it was left in, both caret position and scroll values. 

My suspicion is that somewhere after we set the state up in that method, `TextEdit` is recalculating the scroll value causing the issue.

**Comment by Leleat** [comment]
> My suspicion is that somewhere after we set the state up in that method, TextEdit is recalculating the scroll value causing the issue.

It appears `set_text()` is constantly being called (like once per second). This means that cursor_set_line/column() are also constantly being called. This in turn calls adjust_viewport_to_cursor(). I believe this is where the bug comes from.

I just prevented adjust_viewport_to_cursor() from setting the h_scroll before the first draw call. With this PR the v_scroll still won't be restored though. Instead it will still try to set the cur_line as the first/last visible. Initially I thought preventing the entire adjust_viewport_to_cursor() function before the first draw call would fix it. But for some reason these lines seem neccessary 

```
	if (cur_line < first_vis_line || (cur_line == first_vis_line && cur_wrap < first_vis_wrap)) {
		// Cursor is above screen.
		set_line_as_first_visible(cur_line, cur_wrap);
	} else if (cur_line > last_vis_line || (cur_line == last_vis_line && cur_wrap > last_vis_wrap)) {
		// Cursor is below screen.
		set_line_as_last_visible(cur_line, cur_wrap);
	}
```
to adjust the h_scroll properly. Without them the h_scroll always gets set to 0. Honestly I don't understand why...
So this is very bandaid-y. Close this PR, if that isn't good enough because this bug is outside of my current abilities.

**Pull request closed without merging**
