### PR TITLE
[RTL] Fix multithreaded scrollbar visibility update.

### LINKED ISSUE #78434: Editor Output window regression, RichTextLabel does not always update its scrollbar properly
### Godot version

4.1.dev 116f783db73f4bf7e9e96ae54dd3d0a20337cc8a

### System information

Godot v4.1.beta (116f783db) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.1694) - Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 Threads)

### Issue description

Editor Output window RichTextLabel does not always update its scrollbar properly after print() calls. Looks like a regression from https://github.com/godotengine/godot/pull/78241, reverting it fixes this issue (but of course restores the bug it was fixing). CC @bruvzg 

### Steps to reproduce

1) Open the demo project
2) Make the Output window visible in the bottom view, press "Clear Output"
2) Run the project, notice how the output scroll does not follow the actual content added. In fact, the vertical scroll bar is not even visible. However, manually resizing the bottom view updates the layout and the scrollbar becomes visible and "jumps" to the end as expected.

Looks like printing a single line in _process() doesn't always update the scrolling. However, uncommenting the line in _ready() to print many lines in a single frame seems to be enough to update the scrolling and it starts working for the _process() prints, too.

### Minimal reproduction project

[OutputScrollBug.zip](https://github.com/godotengine/godot/files/11786216/OutputScrollBug.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/78434

I do not see any regressions, but issues like #77961 and #77558 can be hard to reproduce, so any extra testing is appreciated.

cc @bitsawer, @KoBeWi

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @groud @Sauermann for testing who seemed to be able to reproduce issues too.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by bitsawer** [comment]
Looks like this was already merged, but I can confirm this fixes the issue both on the MRP test project and with my real project.

**Comment by Sauermann** [comment]
Thanks for resolving this issue!

**Pull request merged**
