### PR TITLE
text-editor: fix Clicking warning doesn't center around line #48639

### LINKED ISSUE #48639: Clicking warning doesn't center around line
**Godot version:**

3.3

**Issue description:**

Another case similar to #47305, #5269 etc. When clicking warning, the view doesn't center around the line.

**Steps to reproduce:**
1. Create a warning, e.g. using
```
var shadow = 1
func _ready():
  var shadow = "hello shadow"
```
2. Click the warning in warning panel
image
image

### PR DESCRIPTION
**Pull request by LLschuster**
*Bugsquad edit:* Fixes #48639

### CODE REVIEW

**Comment by KoBeWi** [comment]
This doesn't look like correct fix. The change should be somewhere in ScriptTextEditor.

**Comment by LLschuster** [comment]
Yes, there was a more appropriate method in the ScriptTextEditor file, I updated the fix.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Could you squash the two commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by LLschuster** [comment]
Sure, i squashed the commits, should be good now

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution 🎉

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
