### PR TITLE
Add motion vector support for GPU 3D Particles

### PR DESCRIPTION
**Pull request by DarioSamo**
Add the capability of resizing the transforms buffer for particles to be double its size and alternate where the current output is written to. Only works for particles that use index as their draw order.

### CODE REVIEW

**Comment by DarioSamo** [comment]
I think this is ready for testing.

**Comment by Calinou** [comment]
> Only works for particles that use index as their draw order.

This should be mentioned in the description of `doc/classes/GPUParticles3D.xml`, as well as in the `use_taa` description in `doc/classes/ProjectSettings.xml`.

**Comment by DarioSamo** [comment]
I'm not entirely sure if it'll need to be documented that much because users don't have a need to edit that setting unless the draw order is important. And draw order is important only when transparent particles are involved, which shouldn't be involved in the motion vectors pass anyway (which is actually a general current bug because any transparent objects can draw to the motion vector buffer right now).

In the case of opaque particles, there should be no need for the user to ever change this setting from the default.

Gonna tag @reduz for some input on this as it's something we discussed.

**Comment by DarioSamo** [comment]
I've added a comment for GPU Particles but don't think it'll be necessary for the `use_taa` setting as it shouldn't cause issues if we fix the transparent particles writing motion vectors properly.

I'll see about addressing that issue in a separate PR before we merge this one.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

**Testing project:** [test_pr_80688.zip](https://github.com/godotengine/godot/files/12456416/test_pr_80688.zip)
*Particles on the left use the default 30 Hz update rate + interpolation. Particles on the right update every rendered frame and have interpolation disabled.
This project is capped to 60 FPS by default to ensure TAA appearance is consistent across displays.*

### Before

https://github.com/godotengine/godot/assets/180032/44590813-0191-47c7-92cf-0750c347f793

### After (this PR)

https://github.com/godotengine/godot/assets/180032/e516d57c-190a-4ee0-b6e0-2b578bb270bb

Performance is pretty much identical before and after this PR.

**Review by clayjohn — APPROVED** [review]
Looks great! I reviewed the code, but I didn't test locally as I have a big refactor on my local and I don't want to recompile from scratch twice. I trust the previous reviews, so let's go ahead with this now

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
