### PR TITLE
Fix Korean input of TextEdit control on android.

### PR DESCRIPTION
**Pull request by bugcaptor**
Related issue: https://github.com/godotengine/godot/issues/7735

### CODE REVIEW

**Comment by akien-mga** [comment]
@volzhs Could you check this PR?

**Comment by volzhs** [comment]
@akien-mga unfortunately i can't right now. i will test it on device in 3 days.

**Comment by volzhs** [comment]
I can type on Android 4.1.2 device, but can not Android 7.1.1 device.
Did I just find another bug? :(

**Comment by bugcaptor** [comment]
Sorry but I think this PR should be rejected.
Regardless of the additional issues that are currently occurring it is not a fundamental solution, and I did not think what would happen to keyboards other than English.

**Comment by akien-mga** [comment]
Thanks for the input, closing it then. Issue #7735 is still there to continue discussing the source of the bug and a better fix.

**Pull request closed without merging**
