### PR TITLE
Web: Fix IME blocking controls

### LINKED ISSUE #93996: Web export ignores clicks under a focused LineEdit
### Tested versions

Reproduces in:
- v4.3.beta2.official [b75f0485b]
- v4.3.beta1.official [a4f2ea91a]

Doesn't reproduce in v4.3.dev6.official [89850d553].

First affected commit is 99d6f32918b8d5b5ca842b5283948dd9c7759f0d.

### System information

Arch Linux <span>#</span>1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 - Tty - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

If there's a focused LineEdit directly above a control, the control can't be clicked.

### Steps to reproduce

Run MRP as a web export. Focus a LineEdit, then try to click the button below it.

### Minimal reproduction project (MRP)

[line_edit_web_focus.zip](https://github.com/user-attachments/files/16115985/line_edit_web_focus.zip)

### PR DESCRIPTION
**Pull request by anniryynanen**
Fixes #93996.

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
40px probably is an overkill, but it should fit font size (which 1px), it's probably better to have a few extra pixels (maybe 5px), also make sure it is tested in both Firefox and Chromium, they have quite different behaviour.

I guess `width` can block controls as well, but I'm not sure what's the best solution, it should be big enough to not break the line (or suggestion window will be misaligned), maybe something like `pointer-events: none;` will work to make it click through.

**Comment by anniryynanen** [comment]
> 40px probably is an overkill, but it should fit font size (which 1px), it's probably better to have a few extra pixels (maybe 5px), also make sure it is tested in both Firefox and Chromium, they have quite different behaviour.

I've tested this in Windows with Firefox and Chrome, and 2 px seems to be enough. I can reproduce the earlier Windows Chrome issue and this didn't make it reappear. I hope 2 px is enough, 5 could make it clip noticeably with the tops of things below. Or maybe I'm just a hitarea perfectionist.

**Comment by anniryynanen** [comment]
Then again, if things are scaled maybe 2 px isn't enough... I'll make it 5 px just to be safe.

**Comment by anniryynanen** [comment]
Setting pointer events to `none` works too, that should be even safer.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
