### PR TITLE
Shortcuts for script switching in script Mode

### LINKED ISSUE #1093: CTRL+TAB should cycle tabs in Script Editor
Pretty much what the title says. If a custom keyboard shortcut can be set, even better!

### PR DESCRIPTION
**Pull request by djrm**
While the user is in Script Mode the shortcuts for switching (CTRL + > and CTRL + SHIFT + > as default) will switch between scripts.
fixes #1093

### CODE REVIEW

**Comment by Paulb23** [comment]
Nice work! Though currently when you are on a help page, it will skip forward or backwards one. Say you're on `Tab 1` it will goto `Tab 3` skipping `Tab 2` and vise versa.

**Comment by djrm** [comment]
@Paulb23 You're right, but if you slightly press the shortcut it doesnt happen, this is weird.

**Comment by Paulb23** [comment]
@djrm Had another look, this is caused by the editor help switching on keypress and keyrelease rather than just keyrelease. To fix add `|| p_event.key.pressed` to `if (!is_visible()) return;`

**Comment by djrm** [comment]
yeah, its solves the problem, thanks @Paulb23

**Comment by akien-mga** [comment]
Works fine.

**Pull request merged**
