### PR TITLE
Disable debug properties of HTTP Request

### PR DESCRIPTION
**Pull request by khairul169**

### CODE REVIEW

**Comment by akien-mga** [comment]
Why?

**Comment by punto-** [comment]
I think the patch is actually commenting them

**Comment by akien-mga** [comment]
> I think the patch is actually commenting them

Hehe nice catch, I had read the commit log and then skimmed through the diff and thought commented lines were being uncommented :P

**Comment by khairul169** [comment]
lol my bad XD

**Comment by Sslaxx** [comment]
Why not have it only print them if using debug binaries (or running within the editor)?

**Comment by vnen** [comment]
Ideally a `DEBUG_PRINT` macro should be created (#7095).

**Pull request merged**
