### PR TITLE
Always soft-reload scripts

### LINKED ISSUE #1659: Require explicit confirmation for reloading plugin scripts
**Describe the project you are working on:**
Godot plugins, also helping others with their plugins

**Describe the problem or limitation you are having in your project:**
In my experience, the most common issue people face when starting to make their own plugins is with hot-reloading scripts. This is especially problematic for the main plugin script.

The issue is that any change, even insignificant or meaningless change (like a new empty line), causes the script to reload and the references the previous instance have had are then lost. For a person inexperienced in plugin development this results in confusing errors about null pointers to objects that are supposed to exist. And it is often very hard to explain the cause of the issue to such users and suggest a workaround approach to avoid those issues. I've tried dozens of times on Discord and people don't quite get it more often than not.

And as an experienced plugin developer you still have to keep in mind the need to disable the plugin before saving scripts. So even if you are familiar with the workaround, it is still annoying.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There are possibly multiple ways this can be solved. Actually keeping and restoring references for example would be ideal, though may not always be possible (see #1012, godotengine/godot#5969). Maybe we need a separate keyword to properly handle those scripts too (see #900). It should also be noted that while the main script is always affected, some other scripts may not be affected by this problem at times, depending on the implementation detail of a particular plugin.

I suggest we track changes to the script files in `res://addons` folder and instead of instantly reloading scripts we notify the user that the scripts were changed and that the plugin must be reloaded. The user must confirm the action and the editor should disable the plugin, apply the changes and then reinstate it. This may be too blunt of an approach, but a more sophisticated solution to any plugin problem seems to take a lot of time to discuss and implement as we don't have a dedicated core dev on the matter. So this may actually address the issue quicker.

As for the usability, debugging editor plugins is hard as it is, so an additional confirmation I can only see as beneficial.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I'm not completely sure what causes the hot-reloading in this case. I assume that for tool scripts the editor just updates the script resource attached to some plugin-related node or some similar approach. In that case I'd postpose that script update and instead cache the updated scripts until the user confirms the update for a plugin. Updates are stacked and grouped by plugin, so many unconfirmed script changes within any plugin must only require one confirmation.

As far as UI goes, a toast would be nice, but a bottom panel may be introduced at the moment. It should be a list of plugins that have changes not yet applied to the live version. There can also be an option to keep the old behavior and hot-reload all scripts as we do now, if someone prefers it.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I guess a plugin can be made to watch `.gd` files in the `res://addons` folder and toggle related plugins, but that's unreasonable in my opinion.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is an issue with the way editor handles plugin scripts, so it should be changed in the editor, but possibly optional.

### LINKED ISSUE #5969: Plugin reload doesn't keeps variables
Tested on Godot 2.1 rc1, Windows 10 64 bits

I make a plugin which has a custom button in the spatial menu. However, as soon as I save my tool as I edit it, Godot reloads it (which is fine), but member variables get reset to their initial state rather than their previous state.
Because of this, my custom button is back to null once reloaded, the plugin is left completely unusable or in a wrong state, and I have to restart the editor as in 2.0.4 old days.

Here is a test project:
[PluginReload.zip](https://github.com/godotengine/godot/files/391639/PluginReload.zip)
It contains a plugin which edits a 3D Terrain custom node. 
- Click on the Terrain: observe a custom button appears in the menu.
- Make it so terrain_plugin.gd is reloaded by editing the script
- Click on another node, then the Terrain again: observe a Nil error in the console. The reference the plugin had on the button has been lost.

### LINKED ISSUE #6276: [TRACKER] Plugin system related issues
This is the tracker for specific issues related to Godot plugin system:

- [ ] Get_local_mouse_pos() offset bug in the editor https://github.com/godotengine/godot/issues/1885 (bug)
- [ ] Error instancing scene as editor tool https://github.com/godotengine/godot/issues/6006 (bug) 
- [ ] Plugin reload doesn't keeps variables https://github.com/godotengine/godot/issues/5969 (bug)
- [ ] Editor not removing name from menu https://github.com/godotengine/godot/issues/5754 (bug)
- [ ] Ability to refresh editor Filesystem tree from plugin https://github.com/godotengine/godot/issues/6219 (enhancement)
- [ ] Ability for plugins to add entry under right mouse click context menu  https://github.com/godotengine/godot/issues/6128 (enhancement)
- [ ] Add a API to add/remove items to the "Tools" menu https://github.com/godotengine/godot/pull/6065 (enhancement)
- [ ] Ability to create plugin that is based on a scene https://github.com/godotengine/godot/issues/3895 (enhancement)
- [ ] No way to edit plugin.cfg in editor https://github.com/godotengine/godot/issues/5096 (enhancement)
- [ ] Plugin API feature request (text editor extensions) https://github.com/godotengine/godot/issues/3869 (enhancement)
- [ ] EditorPlugins for main editors need a way to know the "main screen" parent https://github.com/godotengine/godot/issues/5786 (enhancement)

*Couple others more wide issues*:
- [ ] *TheHX*: Suggestions for the Plugin API  https://github.com/godotengine/godot/issues/4276
- [ ] *Zatherz*: Better custom EditorPlugin nodes https://github.com/godotengine/godot/issues/6067

### LINKED ISSUE #26326: Script editor soft-reload button doesn't seem to do anything
**Godot version:**
3.1 beta8

**Issue description:**
Menu option "Soft reload script" does nothing. At first I though it's an issue with built-in scripts, as when you change scene externally, there's no way to reload a built-in script (there should be IMO), other than reloading whole scene ofc.
But if you disable auto-reload of scripts and change a script externally and return to editor, you get a warning that script got changed. When you cancel the warning, there's no way reload script other than re-focusing editor. The soft reload button does nothing.

**Steps to reproduce:**

0. Disable "Auto Reload Scripts On External Change" in editor settings
1. Open a script in Godot
2. Change it externally
3. Focus on Godot
4. Cancel the external change warning
5. Try to reload the script without unfocusing Godot

Good luck ;)

### PR DESCRIPTION
**Pull request by KoBeWi**
See https://github.com/godotengine/godot/issues/26326#issuecomment-973628224 for context.

This PR makes all scripts soft-reload by default. This prevents script variables from being cleared upon save etc. I didn't find any drawbacks of using soft-reloading. The only case where hard-reload is stil used is when running EditorScript.

The "Soft Reload Script" menu option was renamed to "Soft Reload Tool Script" and only works on tool scripts (technically it always only worked on tool scripts, but now there is a proper error message). I left it out, because apparently we have an editor setting for auto-reloading scripts on save, which can be disabled. If we ever remove this setting, soft-reload menu option will become unnecessary and could be removed too.

Also I considered adding menu option for hard-reloading, but apparently it requires that no script instance exists and the option almost always fails when used. There is a `reload_tool_script` method that could be used, but only GDScript has it.

Resolves #26326
Resolves https://github.com/godotengine/godot-proposals/issues/1659 (fixes the original problem)
Fixes #5969
Closes #6276 (last issue)

2 more related proposals, but not sure if it resolves them:
https://github.com/godotengine/godot-proposals/issues/1012
https://github.com/godotengine/godot-proposals/issues/2365

### CODE REVIEW

**Comment by mhilbrunner** [comment]
cc @vnen @neikeq  This needs your review :)

**Comment by neikeq** [comment]
As far as I remember from a discussion with @reduz long ago, both hard reload and soft reload should keep state; with the only difference being hard reload destroys and recreates instances restoring their state, meanwhile soft reload keeps the existing instances.
I may be wrong about that description but if it's indeed true, it would suggest the issues this PR tries to fix are a bug in hard reload rather than the use of the wrong reload mode.
In any case, C# always reloads by recreating instances and restoring their state (what I described as hard reload above), regardless of what flag is passes, so this PR doesn't affect it.
I can't comment on GDScript and other languages. I think @reduz should give this a quick review.

**Comment by KoBeWi** [comment]
What is the purpose of destroying script instances? The behavior of hard-reload is weird, seems like you actually need to remove the instances yourself, otherwise the reloading will fail, because the script is in use. Also, state preserving is conditionally disabled for hard-reload, so it looks intended. If this is really a bug, then it's at least 5 years old 🙃

btw when discussed during meeting, reduz's concern was that soft-reload will keep variable list, so if you add a new variable or delete one, it won't work properly. I tested this and the script will detect new variables properly, but they will have `null` value, which is somewhat expected. Soft-reloading is about keeping values of variables.

**Comment by neikeq** [comment]
> What is the purpose of destroying script instances? ...

For GDScript, I don't know. For C#, it's the only way.

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting, we're not 100% sure that hard reload is no longer useful (aside from C# needs where it's hardcoded - this PR only impacts the builtin script editor), but it makes sense at least to default to soft reload. We'll see if anyone comes up with a use case for reintroducing hard reload options.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
