### PR TITLE
Unify descriptions of vector methods

### PR DESCRIPTION
**Pull request by timothyqiu**
* is_equal_approx
* normalize
* length_squared
* posmod
* posmodv

Added `cherrypick:4.0` for correct localization.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Huh, this is the third PR recently unifying one of their descriptions. Could you maybe do a pass and see if any other descriptions between these three need unifying?

**Comment by timothyqiu** [comment]
Updated.

Left `Vector4.dot()` different from others as describing the geometric interpretation of the dot product of `Vector4` is not as useful and easy to understand as in 2D or 3D space.

These differences pop up from time to time. So we should consider these when reviewing future PRs.

**Comment by MewPurPur** [comment]
Do the integer counterparts need updating too?

**Comment by timothyqiu** [comment]
Updated `Vector4i.length_squared()` so it's the same across all versions.

Differences kept:

* Float version of `snapped()` additionally mentions using the method to round to an arbitrary number of decimals.
* In `sign()`, constant `1.0` is used in the float version and `1` is used in the integer version. This is a convention used in the classref.

**Review by mhilbrunner — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
