### PR TITLE
Make build scripts Python 3 compatible

### PR DESCRIPTION
**Pull request by hoelzl**
SCons 3.0 alpha supports Python 3. These changes update the build files so that Godot can be built with Python 3 when using the new Scons version. 

I've tested the build process with Python 2.7 and 3.6 on Windows. I'm not sure if there are incompatibilities when building with Python < 2.7.

I haven't updated the build scripts for platforms other than Windows but I can do so if the consensus is that this is the right way to move forward.

### CODE REVIEW

**Comment by hoelzl** [comment]
OK, I've renamed `b` to `encode_utf8` as discussed with Akien on IRC and checked that Godot compiles under Windows and Linux with the current alpha of SCons (v3.0.0.alpha.20170821) built using Python 3. The built-in tests produce the same results as for the Python 2 build, and the example projects I've loaded behave as expected.
Since having multiple Python versions is not problem on Linux (and I presume OSX), the main use case I haven't tested is compiling an Android app on Windows using Python 3. I'll try to set up an environment for this, but since I don't normally develop for Android this might take a while.

**Comment by Zireael07** [comment]
AFAIK multiple Python versions are possible on Windows too.

**Comment by hoelzl** [comment]
Zireael07: Yes, it's possible, but it's a pain. By default both Python version install an executable named `python.exe` only. And a lot of software, in particular Scons, relies on the Python version it expects being the first in the path. Since I regularly use some programs that depend on Python 3 I have it before Python 2, so I cannot build Godot with Scons 2.5.1 without remembering to run a script that changes the environment each time I open a new shell (or manually changing the order of the Python versions in the environment editor). I could of course also patch my copy of Scons with a hard coded path to Python 2, but using the Python 3 version and fixing Godot so that it can be built with Python 2 seems like the cleaner approach.

**Comment by hoelzl** [comment]
I've now tested building with the following configurations:

- Windows
- Android on Windows
- Linux
- UWP

Unless I've messed up my juggling of build environments and git checkouts they all should build and run using both Python 2 and Python 3. I have also fixed the Python 3 issues I spotted when looking over the iOS target (and OSX, but there weren't any that I could see) but I couldn't test them. Travis should at least ensure that I didn't break the Python 2 build for these platforms.

**Comment by hoelzl** [comment]
Since the most important build targets seem to be covered (emscripten uses its own version of Python, so trying to build with another version doesn't make a lot of sense), all CI checks pass, and hacking build systems is No Fun At All (TM) I think I'm done with this PR for the time being.

**Comment by akien-mga** [comment]
@hoelzl Would you mind backporting your work to the *2.1* branch? It looks like users of cutting edge Linux-distros with SCons 3.0.0 using Python 3 are starting to hit some issues there :)

**Comment by hoelzl** [comment]
@akien-mga Sorry for the late reply, I didn't see your comment before now. I've backported #10662 to Godot 2.1. It builds and run on Windows and Linux. 
I am currently looking for the other relevant PRs, since I recall there were some issues with OSX or iOS. I'll submit a PR once I've merged everything.

**Pull request merged**
