### PR TITLE
[2.1]-Add Close All,Close Others Options to script editor

### PR DESCRIPTION
**Pull request by sersoong**
Add 'Close All' 'Close Others' options to script editor menu.
Add Context Menu to script list of script editor. 
c
capture4

### CODE REVIEW

**Comment by akien-mga** [comment]
Do we really need so many options? What's "Others"?

**Comment by sersoong** [comment]
If you open too many files, it will be hard to manage so many files.
You must close files one by one,it's very annoying.
Close Others is in addition to the currently open file.
Sorry for my english.
What should it call it?

**Comment by Geequlim** [comment]
That option `Close All`  should save my life to avoid press too much <kbd>Meta</kbd>+<kbd>W</kbd> to close script files.

**Comment by puppetmaster-** [comment]
What about haveing a [x] (closing button) on the end of doc line? (2.1 and 3.0)
image

**Comment by sersoong** [comment]
You must click that button one by one too.

**Comment by henriiquecampos** [comment]
@sersoong wouldn't `Close Others` be 
> close all scripts except the currently open one

**Comment by sersoong** [comment]
Rename to Close Other Tabs,like firefox or chrome

**Comment by groud** [comment]
@akien-mga Do we still merge improvements to 2.1 ?

**Comment by sersoong** [comment]
Are you going to give up version 2.1?
This stable branch?

**Comment by HummusSamurai** [comment]
@sersoong The 2.1 version will be updated until 3.1 or 3.2 is out (at least another 6 months), so there is no need to worry now.

**Comment by akien-mga** [comment]
> Do we still merge improvements to 2.1 ?

As long as they're implemented in the master branch too when relevant, and don't risk of affecting stability, yes.

**Pull request merged**
