### PR TITLE
Reorganized GUIDs in `is_xinput_device` and added several missing GUIDs, second attempt

### LINKED ISSUE #76724: Xbox bluetooth controller detected as 2 devices, triggering 2 events instead of 1
### Godot version

3.5.2 stable, 3.6 beta 1

### System information

Windows 11, all amd system, GLES3

### Issue description

Printed output says that the controller is in fact two controllers:
```
XInput Gamepad
Bluetooth LE XINPUT compatible input device
```
controllers of other makes only report as a single device (tested with nintendo pro controller, dual sense, steam deck)

Tested controllers:
- xbox elite controller
- xbox one s
- ~~haven't tested with xbox series controller, will report back when i have~~ Xbox series *(pink)* works fine

Effect:
- on a fresh new project it seems that the issue is only that the gamepad is reported as two
- in a project we are working on in godot 3.5.2, the double sent events propagate into the game (skips a button when going up for instance)

I am aware of https://github.com/godotengine/godot/issues/41684 and https://github.com/godotengine/godot/pull/71784 which mentions that a fix had been cherry picked, in my testing however the issue remains.

### Steps to reproduce

- create a simple ui scene with a couple of buttons
- add a script that prints the device name using: `print(Input.get_joy_name(event.device))` when event is InputEventJoypadButton in the _input function
- run the game and press a button on a bluetooth connected xbox gamepad

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by atomicBlaze21**
Re-submission of #89564 to fix issues present upon submission (still new to this)
Fixes #76724
Fills in some gaps that were left in the issue, especially with the Xbox One S controllers that received new GUIDs after a firmware update. Also reorganizes the GUIDs to reflect chronological release of hardware. Basically just a follow-up on pull #78043

### CODE REVIEW

**Comment by hackerTiger21** [comment]
Never mind, I see the problem wasn't that I didn't link an issue, it's that I was trying to fix a CLOSED issue despite the problem in the issue still manifesting. Will create new, updated issue with new PR.

**Comment by kilian-diener** [comment]
Hei sorry to bring up some older PR. This was not merged into Godot as far as I can see. Did you resubmit these changes in another PR? Double Input issues with Xbox 1708 controllers are solved for me with these additional changes and it would be nice to have it in the engine at some point.

**Comment by kilian-diener** [comment]
Do you plan on bringing these changes into the engine at some point? Else I would pick it up and try to get it merged in.

**Comment by atomicBlaze21** [comment]
Unfortunately I am not in a position to do so, especially since I do not have access to any of the affected controllers to test.

**Pull request closed without merging**
