### PR TITLE
Make keyboard shortcuts in tile data editors consistent with tilemap editor.

### PR DESCRIPTION
**Pull request by groud**
Now:
- Ctrl = picks a tiles
- Shift + Ctrl = paint with a rectangle

Also fixes a bug with collision shapes painting, as both rect painting and undo/redo did not work at all.

https://user-images.githubusercontent.com/6093119/212712288-391754e9-8500-47d2-9f3f-abad7610f22b.mp4

### CODE REVIEW

**Comment by akien-mga** [comment]
See #64021, you might have to use `is_command_or_control_pressed()` if we want it to map to Control on macOS. CC @ajreckof.

**Comment by groud** [comment]
> See #64021, you might have to use `is_command_or_control_pressed()` if we want it to map to Control on macOS. CC @ajreckof.

When should I use it ? Only when used with shift or should I use it more consistently ?
There are other places where I used that in the TileMap/Set stuff, so it might need a bigger change.

**Comment by groud** [comment]
Alright, I updated the PR.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
