### PR TITLE
Texture Region: Cache auto-slice information into the texture. Fixes #11503

### LINKED ISSUE #11503: Selecting a sprite with big texture on it is very slow
Godot 2.1.3, Godot 3.0 master
Windows 10 64 bits

I just noticed that selecting a sprite having a big texture on it in the viewport freezes the editor for a second or two. On comparison, selecting a smaller sprite is instant, scaled or not. Selecting in the tree doesn't have this issue.
It's unclear to me why this would be so slow?

Repro:
1) Create a big PNG, like 4000x4000 or above
2) Assign it on a sprite (notice first freeze as you assign it, but it's because of a `load`)
3) Deselect anything
4) Now click on the sprite in the viewport: notice short freeze

### PR DESCRIPTION
**Pull request by MarianoGnu**
This simple check prevents from calculating slice for the same texture several time. This is not 100% perfect, if the texture changes it needs the editor to be reloaded to slice the texture again, i'd appreciate if anyone who has knowledge on the resource pipeline tells me how to detect if the texture has been reloaded to slice it again.

### CODE REVIEW

**Comment by Zylann** [comment]
In the previous PR, I also mentionned the fact the texture got auto-sliced even if the user doesn't even use that tool (it doesn't open automatically). Is it still the case? (though the PR makes it less of an issue).

**Comment by Noshyaar** [comment]
> how to detect if the texture has been reloaded

Could `resource_changed` signal be used?

**Comment by MarianoGnu** [comment]
@Zylann it still happens, but only the first time a texture is selected, if many sprites or different nodes use the same texture it will be sliced only the first time, then it will use that information over and over.

@Noshyaar this signal is emmited when any property on the Resource changes, i'm not sure if it's the right solution or, in any case, how to use it.

**Comment by Zylann** [comment]
@MarianoGnu yeah I asked because conceptually it doesn't make sense to me (and will still cause a freeze on first select for no understandable reason).

**Comment by MarianoGnu** [comment]
@Zylann it will freeze sooner or latter, i can add a check to prevent it if the editor isn't open, and call it if needed, not really a problem, just didn't thought it was really needed if it's not sliced over and over.

**Comment by MarianoGnu** [comment]
@Zylann now it wont slice until it's needed. Please try again, i doesn't have a proper texture to try it, all textures that i tried where sliced fast enough to don't mind recalculation

**Comment by Zylann** [comment]
You can try that one: 
horrendous6b

On a side note, I wonder why it gets sliced this way
image

**Comment by MarianoGnu** [comment]
Minimum separation is 1 pixel, if you exceed this on ANY pixel around the rect the two rects will be merged as one. these big blocks could probably be sliced by smaller parts, but would need more separation for autoslice to split them

**Comment by Zylann** [comment]
@MarianoGnu gotcha, here is one that makes my Godot freeze: some dithered background
horrendous9

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by mhilbrunner** [comment]
Whatis the status of this?

**Comment by MarianoGnu** [comment]
Looks like it needs clang format to be fixed, will try to take a look at some point

**Comment by akien-mga** [comment]
It also needs to be rebased now.

**Comment by akien-mga** [comment]
Closing for now as stale, but feel free to make a new rebased PR if the changes are still relevant.

**Pull request closed without merging**
