### PR TITLE
Add information about how `Engine.time_scale` affects Timers

### LINKED ISSUE #76350: Changing the Timescale of the engine messes with the timer, if the timescale is set too high -> Timer continues to stay at high timescale even if changed back to normal
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10

### Issue description

I have a timer, four buttons and a counter.
One button sets the timescale to 1, the other to 2, 3 and 20.
the timer, upon completion, adds 1 to the counter.

If the timer is above or at 0.3 seconds, the buttons behave as they should, as does the counter.

If the timer is below 0.3 seconds, when the speed of the timescale is set to 20 and back, it takes the timer a couple seconds to update back to the original timescale.

This does not seem to happen when the timescale is set to something more reasonable like 2 or 3.

### Steps to reproduce

Create a counter that counts up.
Create a timer that counts down from 0.2 or fewer.

set the timescale to twenty, and then back to one.

the timer wont update immediatly and will take a few seconds to register the timescale changed back to one.

### Minimal reproduction project

[Demonstration.zip](https://github.com/godotengine/godot/files/11302251/Demonstration.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
Should probably be added for 3.x as well, haven't tested if it can be cherry-picked

Fixes #76350

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
