### PR TITLE
Document using SpriteBase3D's `modulate` property with material override (3.x)

### PR DESCRIPTION
**Pull request by Calinou**
`3.x` version of https://github.com/godotengine/godot/pull/55443.

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this ready to merge now? The `master` version was merged.

**Comment by Calinou** [comment]
> Is this ready to merge now? The `master` version was merged.

I added a note for the `opacity` property (which will be kept in `3.x` for compatibility). This should be good to merge now.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
