### PR TITLE
Expose PopupMenu ScrollContainer to scripting

### LINKED ISSUE #1859: Expose the internal ScrollContainer inside PopupMenu
**Describe the project you are working on:**
I'm working on an application which implements filtering a list of images and uses an OptionButton (which internally uses a PopupMenu) to select a filter.  The project has so far required the limitation of giving focus to only a certain control type.

**Describe the problem or limitation you are having in your project:**
With larger filter lists, I've noticed that OptionButton does not expose it's internal ScrollContainer scroll bars, either visually or via API calls or node hierarchy like most other nodes.  This limits the options of traversing the list to focus neighbors or firing mouse scroll wheel events.  The first situation is something I'm trying to avoid due to the situation in my code (I've already had to implement my own hacky buttons because the basic button implementation doesn't fit the situation, or I don't know how to work off of BaseButton to setup a good custom button that fits).  In the second case - I'm trying to build the application in assumption that people may not be working with a mouse with a scroll wheel (ie: if I were to set this application up for android - obviously you don't have a mouse much less a scroll wheel).

I've been using[ this script](https://github.com/godotengine/godot/issues/21137#issuecomment-474598933) for scrollcontainers that I was hoping to apply to this situation, but have no access to the range from the PopupMenu's internal ScrollContainer to implement it in the slightest (I can't even attempt to share the scrollbar with another one to rig the code up in a custom way).

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Just asking for the ScrollContainer or at the very least access to the scrollbars to hook up the `Range` in some way to to open up more interaction options to work with PopupMenus.  At current - I can't access the bars via code exposing the range nor traverse the node hierarchy to access any of these hidden internal nodes.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
 With access to the ScrollBar hidden inside the internal code of the node, it would be as simple a matter as doing `$OptionButton.get_v_scrollbar().share($MyScrollbar)` to implement my own scrollbar visually, and could implement the code above to the PopupMenu to add the ability to drag the list instead of drag and hope to blindly select an option off-screen somewhere or somehow move the list repeatedly shifting the focus target yet staying inside the PopupMenu (which as I've stated - works against how my application is currently built, but that could be an ignorance on my part on how I'm buliding my application).

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
To implement this myself, I would have to entirely re-implement my own OptionButton from the ground up repeating all of the code necessary to add items, define their metadata, handling the styleboxes, the theme, literally the entire code of the OptionButton / PopupMenu re-written in GDScript just for the scrollbar range property.

**Is there a reason why this should be core and not an add-on in the asset library?:**
I have doubts on this being something necessary to core, but it doesn't sound as if it would be difficult to simply expose access to the scroll range property of the PopupMenu unless my ignorance of C++ is blinding me to the difficulty this poses.

### PR DESCRIPTION
**Pull request by EricEzaM**
Closes https://github.com/godotengine/godot-proposals/issues/1859

```
var popup = PopupMenu.new()
var sc = popup.get_scroll_container()
sc.get_v_scrollbar() # or whetever else...
```

### CODE REVIEW

**Comment by groud** [comment]
Technically, you could already get the internal ScollContainer using `popup_menu.get_child(0).get_child(0)`.
I wonder if it is worth exposing this with a dedicated function then, I don't think we do that often in the codebase, and since this is easy to workaround, I am not sure it is worth a dedicated function.

**Comment by EricEzaM** [comment]
Hmm that's true, I didn't actually think about that.

Not super convenient (and no intellisense in the script editor for ScrollContainer) but still doable.

I'll leave it open for now to see what others think.

**Comment by LikeLakers2** [comment]
> Technically, you could already get the internal ScollContainer using `popup_menu.get_child(0).get_child(0)`.

I mean, sure, but that could easily break. If someone edits PopupMenu's code to add a child node before the ScrollContainer, or something else is wacky and ends up adding a child node before the ScrollContainer, then `.get_child(0)` no longer works. You would need to figure out the new number and start using that -- and then it could be broken again, just as easily.

Really, I would be asking if we want to expose the underlying ScrollContainer at all. If we do, then we want to expose it through the existing reference that we already have to it.

**Comment by groud** [comment]
> Not super convenient (and no intellisense in the script editor for ScrollContainer) but still doable.

Yeah I agree. At some point I wanted to find a way to display in the editor those "Internally created" nodes, so that you could modify their properties directly, instead of requiring a getter like that.

> You would need to figure out the new number and start using that -- and then it could be broken again, just as easily.

We could eventually name the nodes to solve this problem. But yeah, the problems stays documenting those internal nodes.
So either exposing them in the editor or directly displaying them in the documentation may work, I don't know.

**Comment by EricEzaM** [comment]
Probably just do this. 

> `popup_menu.get_child(0).get_child(0)`

No support on linked issue since it was made. Not worth the addition.

**Pull request closed without merging**
