### PR TITLE
Allow constructors with same arg count but different types

### LINKED ISSUE #21113: No Plane constructor that takes point and normal
**Godot version:** 3.1 unofficial

**Issue description:**
The most common case for constructing a plane is, in my experience, when you want to have a plane that passes through a point. There is no way in the current API to do that in a trivial way, since the only similar plane constructor is the one that accepts a distance from the origin. It is trivial for axis aligned planes, but it starts to become more complicated once the planes are not aligned with any of the cardinal planes.

**Suggestion:**
Have a constructor that accepts a point and a normal.

### PR DESCRIPTION
**Pull request by issork**
Currently, only the first found constructor with the same arg count is being checked for matching types, ignoring other constructors that might match instead.

This commit changes that and exposes Plane(point, normal), closes https://github.com/godotengine/godot/issues/21113

Since I'm not experienced in C++, please pay attention to things that could be done better.

### CODE REVIEW

**Comment by MennoMax** [comment]
Don't merge yet, spotted a mistake.

**Comment by MennoMax** [comment]
I'm not sure what would be the best approach for the following situation, imagine having a class Clazz with following constructors;
- Clazz(int, float)
- Clazz(int, String)

Checks are done with "Variant::can_convert".

Since  String can be converted to float, calling this constructor with Clazz(0, "f") would actually call the Clazz(int, float) constructor Clazz(0, 0.0) instead of (what I would expect) the Clazz(int, String) one.

I could prioritize perfect type matches, this would however break compatibility with projects that relied on the String to float conversion, as a different constructor might be called instead.

**Comment by MennoMax** [comment]
This should now work as intended, but needs more testing.
Perfectly matching constructors that don't require conversions will be prioritized. I've also exposed the Plane(point, normal) constructor.

**Comment by aaronfranke** [comment]
Shouldn't this constructor be swapped around to be `(normal, point)`? That way all of the constructors with normal vectors have the normal first.

**Comment by MennoMax** [comment]
Yes, definitely - only the exposed constructor or the internal one as well? For the latter I'd split this PR into 2.

**Comment by aaronfranke** [comment]
Both should be done since otherwise core would be inconsistent with GDScript.

Feel free to make another PR that only has the arg switching changes, which can be merged first.

**Comment by aaronfranke** [comment]
@Calinou Not sure, but #37842 should be merged first. I'll mark this one as a draft, we can ignore it until #37842 is merged.

**Comment by MennoMax** [comment]
No, this is no longer needed. The new binding system supports this already.

**Pull request closed without merging**
