### PR TITLE
Add ability to set "keep screen on" for android & iOS. fixes #2428

### LINKED ISSUE #2428: Some api to be able to go to sleep for mobile device.
Godot forces always on for mobile device.
But some api to be able to go to sleep for mobile device would be great.

### PR DESCRIPTION
**Pull request by volzhs**
Default value of `Keep Screen On` is `true`
Can change `Keep Screen On` at Project settings.

2 methods are added to `OS`.

```
OS::set_keep_screen_on(bool)
bool OS::is_keep_screen_on()
```

### CODE REVIEW

**Comment by volzhs** [comment]
closed by accident

**Comment by reduz** [comment]
looks good from the Android side, punto has give OK from iOS side.
Also, make sure to add a relevant option to project settings using the
GLOBAL_DEF macro somewhere in main.cpp

**Comment by volzhs** [comment]
> make sure to add a relevant option to project settings using the GLOBAL_DEF macro somewhere in main.cpp

I don't know what should I do for this.
I wish godot dev team take care if needed, after merge.

**Comment by akien-mga** [comment]
> Also, make sure to add a relevant option to project settings using the
GLOBAL_DEF macro somewhere in main.cpp

I think that's done already: https://github.com/volzhs/godot/commit/fb2bf78591672362adbb62ea15e7be4ac34a7dee#diff-395c1089ded171b1757742cab9e7297dR710

**Pull request merged**
