### PR TITLE
Make `varray()` variadic

### PR DESCRIPTION
**Pull request by KoBeWi**
Allows to make an array of any size and is probably faster thanks to loop assign instead of appending.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks great!

I'd suggest rebasing as this is a bit old.

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Looks similar to this since we have initializer list support in `Vector`:

```c++
#define varray(...) Vector<Variant>({ __VA_ARGS__ })
```

**Comment by KoBeWi** [comment]
Note that would cause
```C++
Vector<something> v1;
Vector<Variant> v2 = varray(v1);
```
`v2` to be copy of `v1` instead of a containing array. I had this problem with #89782

**Comment by timothyqiu** [comment]
Tested locally and it did not happen. It should not happen either. Constructors with an initializer list argument are preferred over regular ones (the copy constructor in this case).

**Pull request merged**
