### PR TITLE
Workaround for IME and echo events on Linux (fixes #29 #7106 #9381):

### LINKED ISSUE #29: IME support for non-latin Unicode characters (CJK, Arabic, etc.)
Trying to type Chinese, Japanese or Korean in OSX fails in the editor fails. 

In other words, make a Button, click on the text field, try to type ロード. It doesn't work. Copying from somewhere else and trying to paste it in doesn't work either.

### PR DESCRIPTION
**Pull request by sowfelicity**
Check each event in the queue to send echo event even if IME is
    activated.

### CODE REVIEW

**Comment by sowfelicity** [comment]
Tt seems that there is something wrong  with this version. Please wait.

**Comment by reduz** [comment]
oh, nevermind, just read the message.

**Comment by sowfelicity** [comment]
It seems that the state of the pending events will be different when different input method frameworks are used.  I will update the commit when I find new solution. 

On the other hand, the reverted commit may send echo if XMODIFIERS was not set to valid value:
```
$ export XMODIFIERS="@im=none"
$ godot
```

**Comment by sowfelicity** [comment]
I found a new solution. It seemed that I can't reopen this PR?
I create another PR(#9396) for the new solution.

**Pull request closed without merging**
