### PR TITLE
Bottom panel debugger

### PR DESCRIPTION
**Pull request by toger5**
bottom panel fix with the inital implmentation which fixes the borken parts.
 - make it work in combination with the border for tabs
 - fixed updating when changing theme

ping @djrm.

the advantage of the version in this pr is, that the editor_theme.cpp keeps relative simple and it is much harder to break the style.

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by akien-mga** [comment]
Bump.

**Comment by toger5** [comment]
Didn't had time today, but I will rebase.

**Comment by groud** [comment]
So ? Good to merge ?

**Comment by toger5** [comment]
From my side yes.

**Pull request merged**
