### PR TITLE
regression: dictionary key no autocomplete fix

### LINKED ISSUE #38998: Auto-completion for dictionary keys no longer works since 3.2.2beta3 (worked in 3.2.2beta2)
**Godot version:**
3.2.2beta3

**OS/device including version:**
Windows 10

**Issue description:**
Auto-completion for dictionary keys no longer works.

**Working in _3.2.2beta2_**
Beta 2 Autocomplete Working

**Not Working in _3.2.2beta3_**
Beta 3 Autocomplete Not Working

**Steps to reproduce:**
Create a dictionary with string keys.
Write `<dict_name>.` and see that autocompletion is not working in 3.2.2beta3

**Minimal reproduction project:**
[Dict Autocomplete Regression Bug.zip](https://github.com/godotengine/godot/files/4672836/Dict.Autocomplete.Regression.Bug.zip)

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #38998

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, this fixes a regression from #37954. (@vnen Your work on a GDScript testing framework will really be useful in the future :)).

**Comment by vnen** [comment]
Yeah, reviewing these is always tricky because it's hard to see the context at a glance. I guess I need to consider completion in the tests as well.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
