### PR TITLE
Redefine var results in an error

### PR DESCRIPTION
**Pull request by jkb0o**
Error raised if redefine
- function argument
- for-loop argument
- local-scope var

Affects #3730

Well, there is still a dirty hack with `cf_for->body->variables.push_back(id->name);`. It is the only simple way Ive found for protect for-loop var from being redefined.

And I'm pretty sure I've missed something important =/

### CODE REVIEW

**Comment by reduz** [comment]
it makes sense that this would be an error, but it would probably break a lot of people's code to fix
let's fix for 3.0 when compatibility breakage is expected

**Comment by akien-mga** [comment]
Maybe we could merge a version that raises a warning, and only make it a blocking error in 3.0? To let people know about the need to fix their code in 2.1 already.

**Comment by akien-mga** [comment]
We're now working on Godot 3.0, this could be considered for merging again.

**Review by bojidar-bg — APPROVED** [review]
Looks good by me

**Pull request merged**
