### PR TITLE
Packet tracking stats for 3.2

### PR DESCRIPTION
**Pull request by chiguireitor**
This PR adds additional functionality to the ENet module to enabled packet statistics tracking (packets sent/received, bytes sent/received) useful for debugging multiplayer games.

### CODE REVIEW

**Comment by Faless** [comment]
I don't like the idea of making this ENetPeer-specific. Since we need to track this manually, it would be best to have it in MultiplayerAPI.

**Comment by chiguireitor** [comment]
Could be moved upper towards the NetworkPeer? I feel like it's very implementation specific (i.e. there are some client/server configuration messages that aren't taken into account on upper layers) and having it on the lowest level allows for real deep optimizations, but that's just my point of view on my specific need. The code isn't really that complex so moving it to somewhere where it makes more sense/is more broad couldn't harm.

**Comment by Faless** [comment]
Well, it could be peer dependent, but not in the way it's currently implemented. As an example, bytes_sent does not reflect the actual number of payload sent in the network when e.g. compression is enabled, or when the server broadcast a message to all peers,

**Comment by chiguireitor** [comment]
Gotcha, indeed, i wanted to be able to check how much data is being sent and received on the client side mainly to optimize that side, but indeed this could be an issue if the server isn't calculating correctly the amounts. Will do a fix when i finish my other current module.

**Comment by yuraj11** [comment]
@chiguireitor Hi, do you still work on this? It would be useful addition.

**Comment by Calinou** [comment]
@yuraj11 Doesn't https://github.com/godotengine/godot/pull/31870 supersede this?

**Comment by chiguireitor** [comment]
@Calinou although #31870 looks like this, this is for tracking on-the-go, could be implemented for some sort of packed quota for limited networks and so on.

**Comment by chiguireitor** [comment]
@yuraj11 i'm using this on a personal fork of mine for development purposes.... doing an mmorpg needs closely monitoring of the usage on mobile..... it works ok for me, lemme know if you use it

**Comment by yuraj11** [comment]
@Calinou Well it would be also useful to be available as API for in game debug purposes.

**Pull request closed without merging**
