### PR TITLE
Fix missing const in CapsuleShapeSW::get_area

### PR DESCRIPTION
**Pull request by marcelofg55**

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Looks good, merging...

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Comment by bojidar-bg** [comment]
@akien-mga but.. it is a a type mismatch with the base virtual function, and is actually a bug.
Small showcase:
```cpp
#include <iostream>

class A {
public:
    virtual float get_x() const { return 10.0; }
};

class B : public A {
public:
    virtual float get_x() { return 20.0; }
};

int main()
{
    A* test = new B();

    std::cout << test->get_x() << std::endl; // Prints 10, due to missing const

    return 0;
}
```

**Comment by akien-mga** [comment]
You're the one who tagged it "enhancement" ;)

**Pull request merged**
