### PR TITLE
Cryptography for arrays and strings.

### PR DESCRIPTION
**Pull request by Catprog**
Encryption, Decryption for strings and raw arrays.
HMAC for raw_Arrays

```

    var enc = Crypto.new();



    var key = [0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1];

    enc.SetKey(key);

    var encrypted = enc.EncryptString("Test123",true)
    var cnt = 0;
    var buf = "";

    for i in encrypted:
        cnt = cnt + 1;

        buf = buf +  str(i) + " ";

        if(cnt == 16):
            cnt =0;
            buf = buf + "\n"


    print (buf);    

    print ('----');
    print( enc.DecryptString(encrypted,true))

    print ('*****************');    
    var encrypted = enc.EncryptRaw([100,90,80],true)
    var cnt = 0;
    var buf = "";

    for i in encrypted:
        cnt = cnt + 1;

        buf = buf +  str(i) + " ";

        if(cnt == 16):
            cnt =0;
            buf = buf + "\n"


    print (buf);

    print ('----');

    var decrypted = enc.DecryptRaw(encrypted,true)
    var cnt = 0;
    var buf = "";

    for i in decrypted:
        cnt = cnt + 1;

        buf = buf +  str(i) + " ";

        if(cnt == 16):
            cnt =0;
            buf = buf + "\n"


    print (buf);

```

### CODE REVIEW

**Comment by Catprog** [comment]
This is for issue #1969.

**Comment by Catprog** [comment]
Should the useHMAC parameter be moved into it's own method. (Like the setKey and setPassword functions)?

**Comment by bojidar-bg** [comment]
@Catprog Use `snake_case`

**Comment by Catprog** [comment]
@bojidar-bg 
snake case is now used

**Comment by reduz** [comment]
This is cool functionality to have, not exactly sure if I would expose it like this, as it would also be useful to implement properly for files and other stuff

**Comment by Catprog** [comment]
@reduz 
Their already is functionality for files. This is for people who don't want to go through a file. For instance a network communication.

**Comment by reduz** [comment]
for files it's only using AES, it should kinda use SHA too I guess?

**Comment by Catprog** [comment]
Should their be RSA signatures and Diffie Hellman as well?

**Comment by akien-mga** [comment]
So IIUC we're interested in the work in this PR, but not fully happy about the API proposal yet. Any suggestion on what the API should be like, so that we can work on improving the PR to merge it?

**Comment by Catprog** [comment]
The only suggesions I have is the series of steps that are neeeded.

Steps 
1) Set the key
2) Set options( useHMAC, IV)
3) Pass in either a string or a raw array to get the encrypted or decrypted result back in the specified format.

**Comment by Catprog** [comment]
This code is wrong. I am now working on a new set of code. I current have the Hash working. But the encryption is limited to 16 bytes.

**Comment by akien-mga** [comment]
> This code is wrong. I am now working on a new set of code. I current have the Hash working. But the encryption is limited to 16 bytes.

What's the status on this? I see some more recent work in https://github.com/Catprog/godot/tree/crypto2 but it's for Godot 2.1, so won't work for this PR. Both branches would need the code style fixed to match what is now enforced by clang-format.

Closing for now as it can't be merged as is and has grown stale, but I still think there might be interest in the feature you're proposing, so don't hesitate to continue discussing it in #1969 and/or open a new PR with an updated proposal.

**Pull request closed without merging**
