### PR TITLE
Use real_t in physics code

### PR DESCRIPTION
**Pull request by aaronfranke**
This was originally part of #21922, however that PR is taking forever to be reviewed, so I took the physics parts of it and put it into this PR. @AndreaCatania has already given #21922 an approval, so hopefully this PR won't take too long to get in (of course, more eyes are welcome, so I've requested a review from the entire Physics team).

### CODE REVIEW

**Review by AndreaCatania — APPROVED** [review]

**Review by pouleyKetchoupp — COMMENTED** [review]
The changes look good.

Just a couple things I'm wondering:
- There are still references to PACKED_FLOAT32_ARRAY in ConvexPolygonShape2DSW and ConcavePolygonShape2DSW data, I guess they can be changed as well (it's just error messages it seems).
- It might be outside of this PR's scope, but float is still used extensively in scene nodes, including physics 2D and 3D. Should it be changed too to make sure things stay consistent when using double precision?

**Comment by aaronfranke** [comment]
@pouleyKetchoupp I will likely copy more stuff out of #21922 later if it's something that has a good chance of being merged.

**Review by Xrayez — APPROVED** [review]
I'd merge and see what happens!

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
