### PR TITLE
Fix an operator precedence issue in Callable::bind

### LINKED ISSUE #57057: "Can't get method on CallableCustom" when creating signal
### Godot version

4.0.dev (0e2842d)

### System information

5.16.2-arch1-1

### Issue description

When creating a signal with an extra call argument, an error shows up such as
```
Can't get method on CallableCustom "Control(Control.gd)::_on_button_pressed".
```
Though when creating a signal with two extra call arguments, the same error appears, with the extra effect of changing the data type of the second argument without a clear pattern.

When creating a signal with more than two extra call arguments, the engine crashes.

```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (0e2842d5b2f8c06157c1c3b143c00aecc6c2c99a)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /usr/lib/libc.so.6(+0x3cda0) [0x7fc446720da0] (??:0)
[2] Variant::operator=(Variant const&) (??:0)
[3] Callable::bind(Variant const**, int) const (??:0)
[4] ConnectDialog::ConnectionData::get_callable() (??:0)
[5] ConnectionsDock::_connect(ConnectDialog::ConnectionData) (??:0)
[6] ConnectionsDock::_make_or_edit_connection() (??:0)
[7] void call_with_variant_args_helper<ConnectionsDock>(ConnectionsDock*, void (ConnectionsDock::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[8] void call_with_variant_args<ConnectionsDock>(ConnectionsDock*, void (ConnectionsDock::*)(), Variant const**, int, Callable::CallError&) (??:0)
[9] CallableCustomMethodPointer<ConnectionsDock>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[10] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[11] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[12] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[13] ConnectDialog::ok_pressed() (??:0)
[14] AcceptDialog::_ok_pressed() (??:0)
[15] void call_with_variant_args_helper<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[16] void call_with_variant_args<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, int, Callable::CallError&) (??:0)
[17] CallableCustomMethodPointer<AcceptDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[18] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[19] Object::emit_signal(StringName const&, Variant const**, int) (??:0)
[20] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (??:0)
[21] BaseButton::_pressed() (??:0)
[22] BaseButton::on_action_event(Ref<InputEvent>) (??:0)
[23] BaseButton::gui_input(Ref<InputEvent> const&) (??:0)
[24] Control::_call_gui_input(Ref<InputEvent> const&) (??:0)
[25] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (??:0)
[26] Viewport::_gui_input_event(Ref<InputEvent>) (??:0)
[27] Viewport::push_input(Ref<InputEvent> const&, bool) (??:0)
[28] Window::_window_input(Ref<InputEvent> const&) (??:0)
[29] Viewport::_sub_windows_forward_input(Ref<InputEvent> const&) (??:0)
[30] Viewport::push_input(Ref<InputEvent> const&, bool) (??:0)
[31] Window::_window_input(Ref<InputEvent> const&) (??:0)
[32] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[33] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (??:0)
[34] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[35] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[36] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (??:0)
[37] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (??:0)
[38] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:0)
[39] Input::flush_buffered_events() (??:0)
[40] DisplayServerX11::process_events() (??:0)
[41] OS_LinuxBSD::run() (??:0)
[42] /home/gilational/Desktop/godot.linuxbsd.tools.64(main+0x174) [0x557f3af82fad] (??:0)
[43] /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7fc44670bb25] (??:0)
[44] /home/gilational/Desktop/godot.linuxbsd.tools.64(_start+0x2e) [0x557f3af82d6e] (??:0)
-- END OF BACKTRACE --
```

### Steps to reproduce

- Create a signal from a node to any node with a script (can be same node)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by fountainment**
* Fixes https://github.com/godotengine/godot/issues/57057

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks like this PR is exposing a bug:
```
core/variant/binder_common.h:236:25: runtime error: member call on address 0x61e0002f1c90 which does not point to an object of type 'CanvasItem'
0x61e0002f1c90: note: object is of type 'PopupMenu'
 be be be be  48 73 63 c3 a1 55 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  30 06 d7 01
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'PopupMenu'
=================================================================
==9183==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffebce10ac8 at pc 0x55a1b5b555e6 bp 0x7ffebce0f530 sp 0x7ffebce0f520
READ of size 4 at 0x7ffebce10ac8 thread T0
    #0 0x55a1b5b555e5 in Variant::operator=(Variant const&) core/variant/variant.cpp:2592
    #1 0x55a1b5b03375 in Callable::bind(Variant const**, int) const core/variant/callable.cpp:84
    #2 0x55a1b5b15a5f in callable_bind(Callable const&, Variant const&, Variant const&) core/variant/callable_bind.cpp:192
    #3 0x55a1a8376fff in SceneTreeDock::_notification(int) editor/scene_tree_dock.cpp:1254
    #4 0x55a1a8423ba1 in SceneTreeDock::_notificationv(int, bool) (/home/runner/work/godot/godot/bin/godot.linuxbsd.double.tools.64.san+0x3e22cba1)
    #5 0x55a1b649075b in Object::notification(int, bool) core/object/object.cpp:848
    #6 0x55a1ac7eaa3b in Node::_propagate_ready() scene/main/node.cpp:177
    #7 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #8 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #9 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #10 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #11 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #12 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #13 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #14 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #15 0x55a1ac7ea31f in Node::_propagate_ready() scene/main/node.cpp:169
    #16 0x55a1ac83e044 in Node::_set_tree(SceneTree*) scene/main/node.cpp:2450
    #17 0x55a1ac918a7a in SceneTree::initialize() scene/main/scene_tree.cpp:399
    #18 0x55a19e04539c in OS_LinuxBSD::run() platform/linuxbsd/os_linuxbsd.cpp:345
    #19 0x55a19e032cbc in main platform/linuxbsd/godot_linuxbsd.cpp:58
    #20 0x7fae5f58c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #21 0x55a19e0327ed in _start (/home/runner/work/godot/godot/bin/godot.linuxbsd.double.tools.64.san+0x33e3b7ed)

Address 0x7ffebce10ac8 is located in stack of thread T0 at offset 4408 in frame
    #0 0x55a1a836ae9f in SceneTreeDock::_notification(int) editor/scene_tree_dock.cpp:1161
```

See https://github.com/godotengine/godot/runs/5716054884?check_suite_focus=true for details.

----

Also on chat @reduz was suggesting adding private `Variant::operator *` and `Variant::operator->`, which could have prevented the original wrong code from compiling.

**Comment by reduz** [comment]
Can you add to variant a private operator*() and operator->() to Variant to avoid errors like this in the future? It would be good to test without this fix to see if it catches the error.

**Comment by fountainment** [comment]
> 

I'm on it. Still trying to fully understand what's happening in the Linux debug build.

**Comment by akien-mga** [comment]
> I'm on it. Still trying to fully understand what's happening in the Linux debug build.

Note that it's not just a debug build but it uses GCC's Address Sanitizer with `use_asan=yes`.

It then uses this build to open a test project in the editor, and that's where it finds a bug introduced (or exposed) by this PR:
https://github.com/godotengine/godot/blob/master/.github/workflows/linux_builds.yml#L138-L151

**Comment by fountainment** [comment]
@akien-mga @reduz Sorry, I still don't understand why it's suggested to change variant operator, but I did some investigation, and got some valuable results.

The **callable_bind** in **core/variant/callable_bind.cpp** seems to be a legacy function, which is only used in a few places, and it passes a adress of **pointer** array to Callable::bind, which seems to be incorrect, because all other places are using adress of pointer to an **value** array. I did some change, and is going to submit it in this PR to see what happens.

And for preventing future errors, according to my previous investigation (if it's correct), maybe it's good to delete the **callable_bind** in **core/variant/callable_bind.cpp**, I actually did it in the upcoming commit.

**Comment by fountainment** [comment]
Seems the problem in this PR is fixed, so the conclution is that:
Previously, **Callable::bind** is written in a way that accept pointer array (correct way to dereference is [] then *),
https://github.com/godotengine/godot/blob/7fe5bece45123b21a558f1aa445802e6247699c4/core/variant/callable.cpp#L80-L87
and the **callable_bind** in callable_bind.cpp works fine with it.
https://github.com/godotengine/godot/blob/3393b3c8d1b71245b4c4499fb09725e70be94d1f/core/variant/callable_bind.cpp#L190-L193

If I guess it right, at some point, callable binding switched to use Vector<Variant>, and adress of its pointer is passed to **Callable::bind** (correct way to dereference is * then []), which causes the original problem.
https://github.com/godotengine/godot/blob/3393b3c8d1b71245b4c4499fb09725e70be94d1f/editor/connections_dialog.cpp#L92-L101

And these two ways are mixed used, so only changing **Callable::bind** doesn't fixed the whole problem.
I actually did consider the problem too simple, and didn't explain it well, sorry for that.
And also maybe my fix is not appropriate, so feel free to discard it and do a better one.

**Review by KoBeWi — DISMISSED** [review]
The connection dock is fixed.
Code seems ok too.

**Comment by reduz** [comment]
False alarm, this PR actually adds a bug, does not remove it. The original code is good. The problem is in the connections dialog line 96:

```
const Variant *args = binds.ptr();
				return Callable(target, method).bind(&args, binds.size());
```				
The function takes an array of pointers to Variant, what is being sent is a pointer to an array of variants. The fix needs to happen at connection_dialog.h

**Comment by fountainment** [comment]
> False alarm, this PR actually adds a bug, does not remove it. The original code is good. The problem is in the connections dialog line 96:
> 
> ```
> const Variant *args = binds.ptr();
> 				return Callable(target, method).bind(&args, binds.size());
> ```
> 
> The function takes an array of pointers to Variant, what is being sent is a pointer to an array of variants. The fix needs to happen at connection_dialog.h

Thanks for your confirmation! You're right, this PR is fixing the connection dock in a wrong way, and will introduce other problems. I will close this one and send another PR. Sorry for this sloppy one.

**Pull request closed without merging**
