### PR TITLE
Rename SSL certificate bundle setting to clarify the "overriding" aspect

### LINKED ISSUE #2531: How does SSL work exactly with HTTPRequests?
**Issue:**
I'm trying to access a remote API server (website) through HTTPS. 
I do a regular HTTPRequest.request with SSL handshake = true with the websites public key cert pointed to in the project settings, and it fails to connect, returning RESULT_SSL_HANDSHAKE_ERROR.

When I do a request with SSL handshake = false and the cert removed from the project settings, but the URL begins with **https://** it connects fine and I get access to the API (confused).

When I repeat the above experiment with the url beginning with **http://** it gives RESULT_CONNECTION_ERROR. 

How does the remote server register my connection as secure for the second experiment when the SSL handshake has been disabled and the cert removed from project settings, but the API works just fine?

I can't make any sense of this and the documentation about SSL connections is just lacking.

### PR DESCRIPTION
**Pull request by Calinou**
This closes https://github.com/godotengine/godot-docs/issues/2531.

If this is merged, I can make a PR against the `3.2` branch with only the description change.

### CODE REVIEW

**Comment by Faless** [comment]
This is okay, but I don't think we can cherry-pick this in `3.2` . It will be a breaking change for people who use that setting, and might even go unnoticed.

**Comment by Calinou** [comment]
@Faless I said I'll make a separate PR with only the description change, without changing the setting name.

**Comment by akien-mga** [comment]
Thanks!

A 3.2 PR to update the description sounds good.

**Comment by Faless** [comment]
@Calinou sorry, I didn't read carefully. :)

**Pull request merged**
