### PR TITLE
Theme fixes from light

### PR DESCRIPTION
**Pull request by toger5**
@djrm here are the changes for the theme.

I also added the line for the menu buttons top left.
(it was a bug that they were gone. but do you want to keep them?)

### CODE REVIEW

**Comment by djrm** [comment]
@toger5, no i removed that line, i dont see how why that needs to be special, its better to let it behave like the rest of the tool buttons

**Comment by akien-mga** [comment]
So I guess that commit should be edited?

**Comment by toger5** [comment]
@djrm oh I didn't know that was intentional. since there were still style boxes created in the theme.
the only thing that was missing was the set_flat boolean all the style boxes were still there.

so removing them is in everybody's interest? (Go for simplicity!!)

**Comment by toger5** [comment]
I kind of fucked myself over with the last couple of pr's since they all were creating merge conflicts for each other. But I wanted to give the option to only merge some of them.

**Pull request merged**
