### PR TITLE
Use `BLEND_SHAPE_MODE_RELATIVE` for GLTF blend shape

### LINKED ISSUE #55812: Vulkan: When combining blend shapes into a larger positive combined value, shading issues occur (blend shape normalization / normals issue?)
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 10, Nvidia GTX1060 6GB, Studio driver 472.47, Vulkan clustered

### Issue description

I tried to do a search, but couldn't come up with any issues that seemed to describe the exact same phenomenon. Perhaps it is related to what is described in lyuma's comment here: [https://github.com/godotengine/godot/issues/49249#issuecomment-853330681](url)? But I am not knowledgeable enough to understand / determine that.

In Godot 4.0 pre-alpha:
- When only one blend shape is set to positive 1 at a time, the mesh renders normally.
- When multiple blend shapes are set to 1 simultaneously, shading issues occur.
- The shading issues seem to gradually appear, as the combined values of the active shape keys increase.
- The effect seems to be counteracted by setting some of the shape keys to negative values ("subtracting from the combined value")

Setting all the blend shapes to negative values instead does not seem to result in shading errors.

In Godot 3.4 this does not happen.

Godot 4.0: only one blend shape at positive 1:
Blendshapes and normals in Godot 4 - 1 blendshape

Godot 4.0: two blend shapes at positive 1:
Blendshapes and normals in Godot 4 - 2 blendshapes

Godot 4.0: three blend shapes at positive 1:
Blendshapes and normals in Godot 4 - 3 blendshapes

Godot 4.0: two blend shapes at positive 1, one blend shape at negative 1:
Blendshapes and normals in Godot 4 - 2 blend shapes positive - 1 blend shape negative

Godot 3.4: three blend shapes at positive 1:
Blendshapes and normals in Godot 3 - 3 blendshapes

### Steps to reproduce

- Open the included MRP.
- Select the Cube MeshInstance.
- Set only one blend shape to positive 1: observe that the cube is rendered normally.
- Set two, then three, blend shapes to positive 1: observe that the shading changes each time, resulting in a mesh that looks like it has normals errors.
- Set one of the blend shapes to negative 1: observe that the shading returns to normal.

### Minimal reproduction project

[Pre-alpha 4 - multiple blend shapes shading issue.zip](https://github.com/godotengine/godot/files/7696795/Pre-alpha.4.-.multiple.blend.shapes.shading.issue.zip)

### PR DESCRIPTION
**Pull request by WindyDarian**
Effectively undo #24647 (and #20377 it was fixing is no longer an issue since vertex weight in skeleton is now separate) and fixes #55812 where the total weight might not be normalized as expected under `BLEND_SHAPE_MODE_NORMALIZED`.

Note the behavior for blending multiple blend shapes will change from "average" to "additive".

Tested with the models from both #20377 and #55812 and both seems to behave correctly

Note this doesn't fix normal behaving weird when using `BLEND_SHAPE_MODE_NORMALIZED` (which my guess is final total weight not normalized to 1 before sending to renderer?), but instead just use `BLEND_SHAPE_MODE_RELATIVE` that now behaves correctly

### CODE REVIEW

**Comment by WindyDarian** [comment]
(Converted to draft because this doesn't work well with `blend_surface_tool->generate_tangents()`, which expects full data instead of offset)

**Comment by WindyDarian** [comment]
Pushed a new change stores as blend shape as full value before `generate_tangents()` and subtracts base values after tangent space generation. Still work for https://github.com/godotengine/godot/issues/20377 and https://github.com/godotengine/godot/issues/55812 test cases and also mad sure #19346 's test case doesnt regress

**Comment by akien-mga** [comment]
> Effectively undo #24647 (and #20377 it was fixing is no longer an issue since vertex weight in skeleton is now separate) and fixes #55812 where the total weight might not be normalized as expected under `BLEND_SHAPE_MODE_NORMALIZED`.

I see that #24647 added some code which is still present in the current importer, and this new PR is adding more code to do conversions later on. I'm not familiar with that code but just wanted to check that this is intended and not doing conversions twice back and forth.

**Comment by WindyDarian** [comment]
> I see that #24647 added some code which is still present in the current importer, and this new PR is adding more code to do conversions later on. I'm not familiar with that code but just wanted to check that this is intended and not doing conversions twice back and forth.

Yes, it is intended. My previous change actually just undid #24647 , so made the blend shape store delta in the first place again, however, I found this would regress https://github.com/godotengine/godot/issues/19346 , and after a bit debugging i found the mikktspace generation code wants full positions and normals to be able to generate  tangents correctly, otherwise it would get stuck by the mesh in #19346. So I made it store full vertices first, then after generating tangent space, substract original values to get offset again with new generated tangent space. This works for the mesh in #19346. Also had a comment in code about this.

**Comment by reduz** [comment]
I am not sure what is going on here, but I see no reason to store these as relative, since tangent and bitangent would not be stored properly.

**Comment by WindyDarian** [comment]
Hi @reduz , can you elaborate on how tangent and bitangent is wrong?

This change will store the tangent as offset after generating tangent space (and i looked flip component (w) isnt used for blend shape blending in shaders). And bitangent is recalculated from normal and tangent in shader after blending. (Though i know this is not mathematically precise unless we regenerate tangent space after blending, it is good enough imo, and what happened before with storing whole vertices in blend shapes and use `RELATIVE` was not accurate either after blending)

The whole reason I am changing it back to `BLEND_SHAPE_MODE_RELATIVE` (and store relative positions, normals, and tangents since it requires so) is because `BLEND_SHAPE_MODE_NORMALIZED` behavior seems to have changed in 4.0 and caused https://github.com/godotengine/godot/issues/55812 , changing it back to  `BLEND_SHAPE_MODE_RELATIVE` seems lowest impact fix (plus it was my change at https://github.com/godotengine/godot/pull/24647 made it `NORMALIZED` and store whole verts, so i think it should be safe unless there are new thing depending on the behavior after 3.1)`

**Comment by WindyDarian** [comment]
A lightning stroke me in the dream and i suddenly understood the blend shape math. https://github.com/godotengine/godot/pull/61217 is the actual fix.

So @reduz was right, tangent is wrong.

So `BLEND_SHAPE_MODE_NORMALIZED` and `BLEND_SHAPE_MODE_RELATIVE` actually do the same thing when math is fixed, just differ in how blend shape is stored is different

**Pull request closed without merging**
