### PR TITLE
GDExtension docs: Advise bindings to use `uint64_t` for bitfields

### PR DESCRIPTION
**Pull request by Bromeon**
Closes- https://github.com/godotengine/godot/issues/88962, alongside related changes:
- https://github.com/godotengine/godot/pull/94270
- https://github.com/godotengine/godot-cpp/pull/1517

### CODE REVIEW

**Comment by Bromeon** [comment]
I wonder if `@param p_is_bitfield` is really the best place to mention this? Or should I move it up to the description part?

**Comment by dsnopek** [comment]
Thanks!

> I wonder if `@param p_is_bitfield` is really the best place to mention this? Or should I move it up to the description part?

Personally, I think it'd be better up in the description, since it's better suited to longer text.

**Comment by Bromeon** [comment]
Updated.

**Review by dsnopek — APPROVED** [review]
Thanks! Looks good to me :-)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
