### PR TITLE
Fix document not showing for gdscript properties in inspector

### LINKED ISSUE #59270: GDScript 2.0: Documentation comments do not appear in inspector tooltips
### Godot version

v4.0.alpha4.official [f47097973]

### System information

Ubuntu, Nvidia, Vulkan

### Issue description

Looking at the merged PR https://github.com/godotengine/godot/pull/41095, inspector tooltips for `@export` variables should already be implemented. However, I can't get them to show up. They do appear in the documentation (F1) just fine, but the tooltip text remains "No description".

image

A restart of the editor does not help.

### Steps to reproduce

Code used in above example:
```swift
extends Node
class_name MyClass

## My documentation for my_inspector_setting
@export var my_inspector_setting: int
```
Or get the minimal reproduction project,
1. Press F1 and check the docs of MyClass, notice the description of `my_inspector_setting`
2. Open `main.tscn` and hover the property in the inspector, notice "No description"

### Minimal reproduction project

[Godot 4 Inspector tooltip.zip](https://github.com/godotengine/godot/files/8303412/Godot.4.Inspector.tooltip.zip)

### PR DESCRIPTION
**Pull request by Xwdit**
Fix #59270

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by Xwdit** [comment]
> Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

OK, I have squashed it

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by bfeber** [comment]
Is this broken again? Seems to not work anymore.

**Comment by lufog** [comment]
> Is this broken again? Seems to not work anymore.

It seems to work, at least for me. Checked on c81ef51.
image

**Comment by bfeber** [comment]
> @bfeber, will you open an issue, or should I?

Dew it.

**Comment by lufog** [comment]
@Xwdit, could you please take a look at #63997?

**Comment by Xwdit** [comment]
> @Xwdit, could you please take a look at #63997?

I'll take a look

**Pull request merged**
