### PR TITLE
[master] Revert "Properly setup seed in RNG"

### LINKED ISSUE #44031: Can't restore RNG state properly
**Godot version:** 3.2.3 & current master (ba51af7)

**OS/device including version:** not graphics-related.

**Issue description:**

RNG state is not restored after calling `RandomNumberGenerator.set_seed` with a seed saved from `RandomNumberGenerator.get_seed`.

The issue is caused by `get_seed` returning the current RNG state, while `set_seed` takes a seed, not state.

PR #35764 tries to resolve this problem by making the interface more intuitive, but seems inactive.

PR #27171 introduced this behavior.

A workaround is, maybe, [reseeding manually after generating a number](https://twitter.com/miziziziz/status/1333949897612079104), sacrificing randomness.

**Steps to reproduce:**

Run the following script with Godot.

```gdscript
extends SceneTree


func _init():
	var rng = RandomNumberGenerator.new()

	# let the seed change
	rng.randomize()
	rng.randi()
	rng.randi()

	var saved = rng.seed
	print('Current seed: ', saved)

	print('This seed produces:')
	print(rng.randf())
	print(rng.randf())

	rng.seed = saved
	print('Resetting the seed produces:')
	print(rng.randf())
	print(rng.randf())
```

Actual output:

```
Current seed: 8670679328791200068
This seed produces:
0.823806
0.514134
Resetting the seed produces:
0.028601
0.02974
```

Expected output:

```
Current seed: 8670679328791200068
This seed produces:
0.823806
0.514134
Resetting the seed produces:
0.823806
0.514134
```

**Minimal reproduction project:** N/A

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #44031

### CODE REVIEW

**Comment by aaronfranke** [comment]
Some links: This reverts #27171 in `master`. It was previously [reverted in `3.1`](https://github.com/godotengine/godot/commit/b5d9099626c4c180403baf0b75bd286a6b65c981).

**Comment by avencherus** [comment]
If it's to be reverted, should also be done in 3.2.

**Comment by Zireael07** [comment]
@avencherus: Was already reverted IIUC.

**Comment by Chaosus** [comment]
> If it's to be reverted, should also be done in 3.2.

It's already in 3.2 if it's merged for 3.1

**Comment by akien-mga** [comment]
> > If it's to be reverted, should also be done in 3.2.
> 
> It's already in 3.2 if it's merged for 3.1

No, the change was made in the `master` branch before `3.2` was released. It was cherry-picked to `3.1` and found to break compatibility, so it was reverted in the `3.1` branch to avoid breaking compatibility.

The compatibility breakage was deemed good as the change was supposedly positive, so it was kept in `master`, thus in `3.2`.
Now reverting it in `3.2` would break compatibility...

**Comment by Chaosus** [comment]
Ah, thanks I forgot about it a bit - so, this fix is not necessary and this PR should be closed?

**Comment by akien-mga** [comment]
Well as per #44031 some users seem unhappy with the current implementation.

We should make sure once and for all that the RNG API is good for most use cases, including reproducibility of results from a given seed. I don't remember what motivated the change which is being reverted here, but I guess there was a valid reason at the time?

CC @Xrayez who's using RNG in goost too. Whatever we decide, some unit tests will also be needed to make sure that we're happy with the current implementation and won't break compatibility further.

**Comment by avencherus** [comment]
Was it the intention of the PR to also make the seed unable to be restored?  Seems like a bug.  How does the state get restored for when doing replays?

**Comment by Xrayez** [comment]
I've never had to re-seed RNG myself in the middle of the generation chain, if such functionality is desired then a new local instance can be created? I'd be personally fine with either change, as long as it's possible to set initial seed.

**Comment by avencherus** [comment]
> I've never had to re-seed RNG myself in the _middle_ of the generation chain, if such functionality is desired then a new local instance can be created? I'd be personally fine with either change, as long as it's possible to set _starting_ seed and replicate the result.

I haven't had to reseed that way either, but it was the way to restore the iteration / state.  By setting the seed it would restart.  Is there a new way of doing this?  I have situations where save points reload and have set the seed back to where it was so the same random things are generated.

**Comment by Xrayez** [comment]
Yes, I think I've mixed up the concepts too, see my take at fixing this in #44089.

The crux of the issue is that `get_seed()` would return a previous state of RNG rather than the seed. But I've also exposed `state` property as well because there's no way to replicate the sequence of numbers in the middle of the generation, as I said.

**Comment by avencherus** [comment]
> Yes, I think I've mixed up the concepts too, see my take at fixing this in #44089.
> 
> The crux of the issue is that `get_seed()` would return a previous state of RNG rather than the seed. But I've also exposed `state` property as well because `get_seed()` could've been used to retrieve the state instead (bug as a feature?), and there's no way to replicate the sequence of numbers in the middle of the generation, as I said.

Nice.  Yeah that would clarify it.

**Pull request closed without merging**
