### PR TITLE
Fix `InputEventJoypadButton::as_text` crash for invalid button index

### LINKED ISSUE #49534: Executing `as_text` function in `InputEventJoypadButton`  crashes Godot
### Godot version

4.0.dev.custom_build. e82a1113a

### System information

Ubuntu 21.04 - Nvidia GTX 970, Gnome shell 3.38 X11

### Issue description

When executing
```
	var q = InputEventJoypadButton.new()
	q.set_button_index(-473)
	q.as_text()
```

Godot crashes with backtrace
```
core/input/input_event.cpp:1027:65: runtime error: index -473 out of bounds for type 'char *[21]'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x2050562] (/mnt/Miecz/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x41040) [0x7f5eabf81040] (??:0)
[3] String::copy_from(char const*) (/mnt/Miecz/godot/core/string/ustring.cpp:317)
[4] String::String(char const*) (/mnt/Miecz/godot/core/string/ustring.cpp:2136)
[5] Variant::Variant(char const*) (/mnt/Miecz/godot/core/variant/variant.cpp:2444)
[6] InputEventJoypadButton::as_text() const (/mnt/Miecz/godot/core/input/input_event.cpp:1027 (discriminator 2))
[7] void call_with_variant_args_retc_helper<__UnexistingClass, String>(__UnexistingClass*, String (__UnexistingClass::*)() const, Variant const**, Variant&, Callable::CallError&, IndexSequence<>) (/mnt/Miecz/godot/./core/variant/binder_common.h:686 (discriminator 4))
[8] void call_with_variant_args_retc_dv<__UnexistingClass, String>(__UnexistingClass*, String (__UnexistingClass::*)() const, Variant const**, int, Variant&, Callable::CallError&, Vector<Variant> const&) (/mnt/Miecz/godot/./core/variant/binder_common.h:444)
[9] MethodBindTRC<String>::call(Object*, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/./core/object/method_bind.h:543)
[10] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/core/object/object.cpp:816 (discriminator 1))
[11] Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/mnt/Miecz/godot/core/variant/variant_call.cpp:981)
[12] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot/modules/gdscript/gdscript_vm.cpp:1473)
[13] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/modules/gdscript/gdscript.cpp:1487)
[14] ScriptInstance::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot/core/object/script_language.cpp:311)
[15] Node::_notification(int) (/mnt/Miecz/godot/scene/main/node.cpp:147)
[16] Node::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/node.h:45 (discriminator 14))
[17] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/canvas_item.h:164 (discriminator 3))
[18] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/2d/node_2d.h:37 (discriminator 3))
[19] Object::notification(int, bool) (/mnt/Miecz/godot/core/object/object.cpp:827)
[20] Node::_propagate_ready() (/mnt/Miecz/godot/scene/main/node.cpp:189)
[21] Node::_propagate_ready() (/mnt/Miecz/godot/scene/main/node.cpp:179 (discriminator 2))
[22] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot/scene/main/node.cpp:2322)
[23] SceneTree::initialize() (/mnt/Miecz/godot/scene/main/scene_tree.cpp:395)
[24] OS_LinuxBSD::run() (/mnt/Miecz/godot/platform/linuxbsd/os_linuxbsd.cpp:273)
[25] godot4s(main+0x3fc) [0x204e042] (/mnt/Miecz/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[26] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xd5) [0x7f5eabf68565] (??:0)
[27] godot4s(_start+0x2e) [0x204db8e] (??:?)
```
This example was found by fuzzer, so I don't recommend trying understand in what situation such code could be used in real project, because such situation probably doesn't exists.

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by timothyqiu**
Added the missing lower bound check.

Fixes #49534.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by LightningAA** [comment]
Should the check maybe be in `set_button_index()` instead, and maybe it should throw an error, or at least a warning, instead of just silently not working?

**Comment by timothyqiu** [comment]
@LightningAA Nope, the check is for indexing array `_joy_button_descriptions` (0-21), which is a subset of valid `button_index` range (0-36).

https://github.com/godotengine/godot/blob/12e0f10c74e9619262f1edcfdc1840432ada0565/core/input/input_event.h#L84-L85

https://github.com/godotengine/godot/blob/12e0f10c74e9619262f1edcfdc1840432ada0565/core/input/input_event.cpp#L999

The idea is to provide a friendly text description when possible, so no error / warning should be generated.

**Comment by LightningAA** [comment]
@timothyqiu not sure I understand, the issue this closes looked like it was caused by `set_button_index()` accepting negative/non-valid numbers, shouldn't there be an error in `set_button_index` if someone tries to input an invalid index, instead of checking in `as_text()`

**Comment by timothyqiu** [comment]
@LightningAA `set_button_index()` does need a range check if required, but I think these are two different issues.

Although I don't know if anyone make use of it, negative button index works fine in 3.x. Not allowing it breaks compatibility which I think is unnecessay, because no other engine code depends on the range of button index.

`master` crashes because it tries to produce a user-friendly name in this function by indexing an array, but only checked the upper bound.

**Comment by LightningAA** [comment]
Why would anyone want a negative button index? It seems to me like the problem is that `set_button_index()` is accepting invalid inputs and `as_text()` assumes the index has already been validated.

**Comment by timothyqiu** [comment]
Well, again, I don't mean `set_button_index()` should not validate its parameter.

These are two approches to fixing the crash, each has its own pros and cons. And I chose to use one has the minimal impact to existing behavior. The logic is simple: Does it crash before the change in `as_text()`? No, so it's the change that caused the crash, not `set_button_index()`, let's fix `as_text()`. Validating the parameter of `set_button_index()` might be a separate PR.

**Comment by EricEzaM** [comment]
The logic is that if someone comes and adds another method and also forgets to check both bounds of the button index, a crash will occur again. Having this check be in `set_button_index()` would stop that from happening, as the invalid input would be caught upstream.

**Comment by LightningAA** [comment]
It looks like -1 is a valid index, as [it's used to represent invalid indexes](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-joysticklist) (so the `>= 0` check does make sense, but the `< JOY_BUTTON_SDL_MAX` doesn't), but any other input outside that range passed to `set_button_index()` should throw an error.

**Comment by timothyqiu** [comment]
> the `>= 0` check does make sense, but the `< JOY_BUTTON_SDL_MAX` doesn't

As said in https://github.com/godotengine/godot/pull/49556#issuecomment-860331513, it makes sense because it's indexing the `_joy_button_descriptions` array which has a size of `JOY_BUTTON_SDL_MAX`.

https://github.com/godotengine/godot/blob/12e0f10c74e9619262f1edcfdc1840432ada0565/core/input/input_event.cpp#L999

`_joy_button_descriptions` maps a subrange of valid button indices into text descriptions. Using `button_index` to index that array is converting an index of one domain to another implicitly.

**Comment by LightningAA** [comment]
I think I finally understand, thank you for your patience

**Pull request merged**
