### PR TITLE
Disable graceful close feature by default

### LINKED ISSUE #21324: Stopping games started from editor hangs editor for 10 seconds
**Godot version:**
current master 
https://github.com/godotengine/godot/tree/0edb50f629bd878d2b8c98d1a6f50c23316f1ac2

**OS/device including version:**
Windows 10

**Issue description:**
I noticed recent master branch builds now have a pretty annoying delay when 'stopping' the game started from the editor.

It used to be that when you click stop you would be able to continue working on your game instantly. Now when you click stop there is a painful delay where the whole Godot hangs for many seconds.

I believe this negatively affects productivity too much.

Looking at #21236 which I believed to be (and actually is) the cause of the issue, I noticed that I can configure the `editor/stop_max_wait_msec`. I couldn't find it in the project settings, so I added it manually and set its value to 10 (milliseconds). Now it is instant as before.

I just want to say that the default should be set very low as I think this negatively impacts productivity and could create a bad impression to new users. Let people increase the number if they want.

The default in the code is 10 seconds, and it seems that when I hit stop using the defaults I have to wait 10 seconds every time before I can continue working on my project.

### PR DESCRIPTION
**Pull request by dragmz**
This disables the graceful process close feature (introduced with ca1c851dbdc14701695d9589225b44d5681606f0) by default.

Fixes #21324 and keeps the feature so it can be used in case a project loads DLLs that need to cleanup their global state before the process terminates.

### CODE REVIEW

**Comment by akien-mga** [comment]
> Fixes #21324 and keeps the feature so it can be used in case a project loads DLLs that need to cleanup their global state before the process terminates.

Is there an actual use case for which we need the feature for now? If it doesn't close gracefully within 10 s with no DLLs loaded, would it when one loads DLLs? It sounds to me like the feature is buggy if it reaches timeout in normal usage.

**Comment by dragmz** [comment]
@akien-mga Not sure why this causes #21324 because it works fine for me and does not wait 10s. Probably worth asking @chanon how to reproduce.

**Comment by dragmz** [comment]
I have found a case where the graceful close timeouts. It's when a script debugger is in a debug mode (e.g. reached a breakpoint) and I try to stop the process. Fixed this by stopping the debugger first.

**Comment by akien-mga** [comment]
The fix for the script debugger is welcome, but I'm still not convinced by disabling the graceful close feature. If it's off by default, nobody will ever use it, and it's probably best not to have it in the first place and remove the additional argument in `OS::kill`.

**Comment by dragmz** [comment]
@akien-mga the reason why I think it should be disabled by default is to keep the good editor experience but have the feature available for users who have issues with GPU drivers so they can test whether it fixes their problem or not.

However if you know that nobody will use it or if there's a different way of getting it tested as a GPU drivers issues fix then it's probably safer to remove it.

**Comment by chanon** [comment]
Just added the reproduction to #21324

**Comment by dragmz** [comment]
Added fix for graceful close always failing if ``config/auto_accept_quit`` is ``false``

**Comment by akien-mga** [comment]
IMO with this PR we now have a quite well hidden feature whose usefulness is yet to be demonstrated, so I'd tend towards reverting #21236 instead (at least in the short term - a new PR implementing the feature in a more consistent way could be considered again).

If we were to merge this PR (21333), we end up with an `OS::kill` optional argument that:
- Has to be enabled manually to be used in the editor
- Only works on Windows, is ignored on other platforms
- Only works if `TOOLS_ENABLED`, is ignored otherwise

So we've made the API more complex for a corner case which we're not even using by default.

I still recognize that their might be a use case with external DLLs (which encouraged me to merge #21236 in the first place), but I'd prefer to reevaluate that taking our time with a new PR.

**Pull request closed without merging**
