### PR TITLE
Add support for infinite projection matrix

### LINKED ISSUE #10515: Infinite projection matrices support
### Describe the project you are working on

A space settled 3D game where both very far away celestial bodies and closer objects (terrains, spaceships ...) are rendered at the same time.

### Describe the problem or limitation you are having in your project

I need both a normal near plane distance (say 5e-2) and a far plane very far away (say 1e18, or even INF). 
When near and far places are apart from each other of an order of magnitude greater than ~1e7, [an error is raised at culling](https://github.com/godotengine/godot/blob/5ca419e32c58e671284b3b7f91257179657d9114/servers/rendering/rendering_light_culler.cpp#L544) and the scene doesn't render.

Worth noting that now [Reverse z-buffer](https://github.com/godotengine/godot/pull/88328) is a reality, it opens the door in theory to rendering such deep scenes without z-fighting (especially when objects are spaced and sized exponentially, like stars, planets and ground objects), and without having to rely on heavier solutions like rendering in multiple passes or multiple cameras.

In detail, when near and far places are set very far apart, the projection matrix generated rounds to an infinite projection matrix ([see slide 7](https://www.terathon.com/gdc07_lengyel.pdf)) due to numerical precision effects.
At scene culling stage, [the 6 clipping plans are extracted](https://github.com/godotengine/godot/blob/5ca419e32c58e671284b3b7f91257179657d9114/servers/rendering/rendering_light_culler.cpp#L498) from the matrix following the popular [Ggribb's method](https://web.archive.org/web/20061020020112/https://www2.ravensoft.com/users/ggribb/plane%20extraction.pdf) (see [`Projection::get_projection_planes()`](https://github.com/godotengine/godot/blob/5ca419e32c58e671284b3b7f91257179657d9114/core/math/projection.cpp#L509-L515). This yields by construction a zero vector for the far plane normal when the projection matrix is infinite.
This zero vector raises an error later during the [light culling preparation](https://github.com/godotengine/godot/blob/5ca419e32c58e671284b3b7f91257179657d9114/servers/rendering/rendering_light_culler.cpp#L544).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Support infinite far planes on `Camera3D` in `PROJECTION_PERSPECTIVE` and `PROJECTION_FRUSTUM` modes.
This should be supported for both scene culling and geometry projection.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Because the near and far distances are used for both scene culling and geometry projection, they are 2 potential changes to consider :

1. **Default to infinite projection matrix for geometry projection**
There is some litterature on the fact that combining reverse-z and infinite projection helps limiting numerical precision errors overall, even with scenes where geometry is not far away (see this one especially : https://developer.nvidia.com/content/depth-precision-visualized).
In practice, this would mean that for both `PROJECTION_PERSPECTIVE` and `PROJECTION_FRUSTUM`, the far distance value provided by the user is ignored and an infinite projection matrix is generated regardless.

2.  **Allow ignoring far distance for scene culling**
There could be a new boolean attribute on `Camera3D` to allow the user to toggle it on/off.
When toggled on, `Projection::get_projection_planes()` could branch and generate an adequate normal and distance-to-origin for the far plane.
I tested this scrappy implementation and at first sight it seems to work :+1:
```c++
///////--- Far Plane ---///////
if (ignore_far_plane_for_culling) {
/* Take the opposite of the near plane's normal.
    Assumption is made they're parallel.
    As godot currently doesn't allow the user to build the projection matrix from scratch,
    there shouldn't be any edge case */
	new_plane.normal = -planes[0].normal;
	new_plane.d = INFINITY; // distance is infinity
} else {
	new_plane = Plane(matrix[3] - matrix[2],
		matrix[7] - matrix[6],
		matrix[11] - matrix[10],
		matrix[15] - matrix[14]);

	new_plane.normal = -new_plane.normal;
	new_plane.normalize();
}

planes.write[1] = p_transform.xform(new_plane);
```

Alternatively, if we don't want to go down the route of defaulting to infinite projection, there could be an additional projection mode added to `Camera3D`, say `PROJECTION_PERSPECTIVE_INFINITE`, that would trigger both changes above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, it's core

### Is there a reason why this should be core and not an add-on in the asset library?

Culling and projection are core.

### LINKED ISSUE #55070: 3D geometry cull failure and light flickering at particular camera far / near values
### Godot version

3.4 stable

### System information

Xubuntu 20.10 AMD 3020e, Vega3, GLES3

### Issue description

In 3D at extremely low camera near and extremely high camera far values, geometry fails to be culled partially or completely when moving beyond camera far distance from the object. It also makes lights misbehave and flicker depending on the view angle.

Not critical but may be worth squashing. Can be avoided by using reasonable camera clipping planes distances.

[Video demonstration of both effects](https://cdn.discordapp.com/attachments/212250894228652034/909460086093664256/simplescreenrecorder-2021-11-14_17.04.18.mp4)

### Steps to reproduce

Set `camera_near` >0.05, set `camera_far` 1000000 (maximum).
Place large visible object at `camera_far` distance from camera, move camera away. If bug reproduces - the object won't disappear or will flicker.

Place point light source at object location, make light distance >= `camera_far`, move camera away, while also looking at the source or away from it, observe the flickering.

### Minimal reproduction project

Unable to provide a project: my project is not small, the development has moved on since then, no time to make up a new small one.

Suspected culprit for this bug may be a condition check at which fragments should be discarded (shader) or a piece of code the governs camera culling. Also it may be an issue related to floating point precision, or the code check that doesn't take into account `camera_near` that small.

### PR DESCRIPTION
**Pull request by Flarkk**
Closes https://github.com/godotengine/godot-proposals/issues/10515.
Fixes #55070 

## What is it about ?
This PR ensures that :
- class `Projection` returns a well-formed far plane when the matrix has the form of an infinite projection
- the rendering pipeline works as expected when the camera far plane is very far away

Without this PR, when the projection matrix is infinite, `Projection` generate zero vectors for the far plane normal, and 0 as z-far distance. This raise errors at different places in the rendering logic (culling, shadow mapping, GI, fog ...) and ultimately prevents anything to be rendered.

With this PR, `Projection` returns z-far distance as `MAX_REAL_T` and the far plane's normal as `Vector3(0, 0, -1)` when the projection matrix has the form of an infinite projection.

## Why it does matter ?
Godot 4.3 brought [reverse z-buffer](https://github.com/godotengine/godot/pull/88328) which unlocks rendering with very far apart near and far planes, with very limited risks of z-fighting in normal conditions.
However, in practice the usage of very far apart near and far planes is still not supported because it makes rendering fail for the reason described above.

This PR ultimately untaps the potential of natively supporting very deep scenes in Godot, without having to workaround it with multiple nested/layered cameras. This is especially useful for terrain rendering and space simulations.

## Under which conditions is an infinite projection matrix generated ?
The infinite form of a projection matrix is obtained when zfar tends towards infinity.
Due to numerical precision limits, in practice it's enough that znear and zfar values are far apart enough to obtain an infinite projection matrix.
I experienced that beyond a difference of 1e7 ~ 1e8 between the near and far distances, the matrix is generated infinite.

The below collapsed sections show how Perspective, Frustum and Orthogonal projections react to far apart znear and zfar when constructed from camera attributes. In a nutshell :
- For Perspective and Frustum, `columns[2][2] = -1` and `columns[3][2] = -2 * p_z_near`
- For Orthogonal, `columns[3][2] = -1`

<details>

**<summary>Expand details</summary>**

### Perspective projection
From [`Projection::set_perspective()`](https://github.com/godotengine/godot/blob/c5ac5d230822a6a39551487acc52350da450c429/core/math/projection.cpp#L270C1-L275C20):
```c++
deltaZ = p_z_far - p_z_near; // becomes p_z_far
// [...]
columns[0][0] = cotangent / p_aspect;
columns[1][1] = cotangent;
columns[2][2] = -(p_z_far + p_z_near) / deltaZ; // becomes -1
columns[2][3] = -1;
columns[3][2] = -2 * p_z_near * p_z_far / deltaZ; // becomes -2 * p_z_near
```
### Frustum projection
From [`Projection::set_frustum()`](https://github.com/godotengine/godot/blob/c5ac5d230822a6a39551487acc52350da450c429/core/math/projection.cpp#L369C1-L393C13), rewritten for clarity:
```c++
columns[0][0] = 2 * p_near / (p_right - p_left);
columns[1][1] = 2 * p_near / (p_top - p_bottom);
columns[2][0] = (p_right + p_left) / (p_right - p_left);
columns[2][1] = (p_top + p_bottom) / (p_top - p_bottom);
columns[2][2] = -(p_far + p_near) / (p_far - p_near); // becomes -1
columns[2][3] = -1;
columns[3][2] = -2 * p_far * p_near / (p_far - p_near); // becomes -2 * p_z_near
```

### Orthogonal projection
From [`Projection::set_orthogonal()`](https://github.com/godotengine/godot/blob/c5ac5d230822a6a39551487acc52350da450c429/core/math/projection.cpp#L347C2-L353C22)
```c++
columns[0][0] = 2.0 / (p_right - p_left);
columns[1][1] = 2.0 / (p_top - p_bottom);
columns[2][2] = -2.0 / (p_zfar - p_znear); // becomes -2.0 / p_zfar
columns[3][0] = -((p_right + p_left) / (p_right - p_left));
columns[3][1] = -((p_top + p_bottom) / (p_top - p_bottom));
columns[3][2] = -((p_zfar + p_znear) / (p_zfar - p_znear)); // becomes -1
columns[3][3] = 1.0;
```

</details>

## Why an infinite Perspective and Frustum projection matrices breaks zfar and far plane extraction ?
User camera settings are transformed into a projection matrix stored in a `Projection` object.
When needed, the rendering server extracts back the frustum planes and distances from the `Projection` object.
This happens in one of these 4 functions :
- `Projection::get_projection_planes()`
- `Projection::get_projection_plane()`
- `Projection::get_z_far()`
- `Projection::get_far_plane_half_extents()`

When the projection matrix degenerates to its infinite form due to numerical precision effects, it becomes  mathematically impossible to extract the far plane normal and intercept from it. 
When performed by one of those functions, the calculation gives 0 (zero vector as the normal, and 0 intercept).
This is the relevant code excerpt taken from [`Projection::get_projection_plane()`](https://github.com/godotengine/godot/blob/c5ac5d230822a6a39551487acc52350da450c429/core/math/projection.cpp#L186C1-L193C21) and rewritten for clarity (the logic is the same for other functions) :
```c++
// This initializes a plane with a zero vector as its normal (first 3 arguments)
Plane new_plane = Plane(columns[0][3] - columns[0][2], // = 0 in all cases
		columns[1][3] - columns[1][2], // = 0 in all cases
		columns[2][3] - columns[2][2], // = 0 for infinite Perspective and Frustum projection
		columns[3][3] - columns[3][2]);

new_plane.normal = -new_plane.normal;
new_plane.normalize(); // returns a zero plane when the normal is a zero vector
return new_plane;
```
Orthogonal projections aren't affected because `columns[2][2] = -2.0 / (p_zfar - p_znear)` which becomes `-2.0 / p_zfar` when `z_far` is big, which is still a (small) finite value. This is under the assumption that `p_zfar` is not set to `INFINITY` by the user, which is currently not possible through the editor, but possible with code.

## TODOs
- [x]  Detect infinite projections and return correct far plane (normal = `Vector3(0, 0, -1)` and intercept = `MAX_REAL_T`)
- [x]  List usages of extracted zfar value and check whether `MAX_REAL_T` breaks any further logic
  - [x] Forward renderers (clustered and mobile)
  - [x] Compatibility renderer
  - [x] Sky
  - [x] GI
  - [x] Fog
  - [x] SS effects
  - [x] Debug effects
  - [x] Scene renderer
  - [x] Cluster builder
  - [x] Scene culling
  - [x] Raycast occlusion culling
  - [x] Light culler
  - [x] Scene renderer
- [ ] Fix any broken logic with zfar = `MAX_REAL_T`
  - [x] Forward renderers (clustered and mobile)
  - [ ] Compatibility renderer
- [ ] Write unit tests with infinite far planes
  - [ ] Camera3D
  - [ ] XRCamera3D
  - [ ] Plane
- [ ] Add other features using zfar / far plane (like GI and light culling) in the demo project

## Infinite zfar impact analysis

The following collapsed sections document the behaviors of the various impacted steps of the rendering pipeline **when the zfar value extracted from the projection matrix is `MAX_REAL_T`**.

:white_check_mark: means the behaviour is likely fine.
:warning: means there is likely a problem. Further investigation is needed.

Note that for now this assessment is only based code inspection.
Proper testing will be needed in all cases.

<details>

**<summary>Show detailed analysis</summary>**

### `RenderForwardClustered` (+ `RasterizerSceneGLES3`)

`RenderForwardClustered::_fill_render_list()`
`RasterizerSceneGLES3::_fill_render_list()`:
- :white_check_mark: All surfaces are set to [`depth_layer` 0](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L912). OK since `depth_layer` seems [not to be used as a sort key](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.h#L420-L440)

### `RenderForwardClustered` and `RenderForwardClusteredMobile` (+ `RasterizerSceneGLES3`)

`RenderForwardClustered::_render_particle_collider_heightfield()`
`RenderForwardClusteredMobile::_render_particle_collider_heightfield()`
`RasterizerSceneGLES3::render_particle_collider_heightfield()`
- :warning: [`scene_data`](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L2748-L2749) has `z_far` == `MAX_REAL_T` which leads [the ubo](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/storage_rd/render_scene_data_rd.cpp#L117-L118) to have `z_far` = `MAX_REAL_T` too

### `SkyRD` (+ `RasterizerSceneGLES3`)

`SkyRD::setup_sky()`:
- :white_check_mark:The [sky scene UBO](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/environment/sky.cpp#L1202-L1203) has `z_far` = `MAX_REAL_T`, which leads the [sky shader](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/environment/sky.glsl#L90-L91) to have `z_far` = `MAX_REAL_T`. This value is not used anywhere in the glsl file though.

`SkyRD::update_res_buffers()`
`SkyRD::draw_sky()`:
`RasterizerSceneGLES3::_draw_sky()`
- :white_check_mark: If the sky has a custom fov, [build an infinite perspective projection](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/environment/sky.cpp#L1449-L1456) with the custom fov. Otherwise use the camera's projection, which is infinite too

### `GI`

`GI::process_gi()`:
- :warning: GI shader gets `zfar` = `MAX_REAL_T` via the [push constants](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/environment/gi.cpp#L3854). This makes [the glsl function `reconstruct_position()`](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/environment/gi.glsl#L176-L180) return `vec2(NaN)` in all cases, which makes [`process_gi()` run on NaN vertices](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/environment/gi.glsl#L719-L720), which likely gives `NaN` in the end too (not checked)

### `Fog`

`Fog::volumetric_fog_update()` : 
- :white_check_mark: For each fog volume : [Fog shader](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/environment/volumetric_fog.glsl#L51-L52) gets `zfar` = `MAX_REAL_T` [via the UBO](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/environment/fog.cpp#L555-L556) , but this value is not used anywhere in the glsl file

- :warning: The [Fog process shader](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/environment/volumetric_fog_process.glsl#L150-L155) gets `fog_frustum_size_begin` = `fog_frustum_size_end` = `frustum_near_size` as well as `zfar` = `MAX_REAL_T` [via the UBO](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/environment/fog.cpp#L996-L1014). I haven't checked the effets yet but it's lilkely the fog is not rendered correctly

### `SSEffects`

`SSEffects::downsample_depth()` :
- :white_check_mark: The downsampling shader gets `zfar` = `MAX_REAL_T` [via the push constants](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/effects/ss_effects.cpp#L499-L502) only in Orthogonal mode, which is not affected by the infinite matrix issue

`SSEffects::screen_space_indirect_lighting` :
- :warning: The ssil shader gets `zfar` = `MAX_REAL_T` [via push constants](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/effects/ss_effects.cpp#L696-L697) which makes all reprojected samples in last frame's coordinates [lie on the near plane](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/effects/ssil.glsl#L204-L211). I'm not sure what are the impacts for now.

`SSEffects::screen_space_reflection` :
- :warning: The ssr scale shader gets `camera_z_far` = `MAX_REAL_T` [via push constants](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/effects/ss_effects.cpp#L1429) which generates `NaN`s in depth values in two places ([1](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/effects/screen_space_reflection_scale.glsl#L76-L80) [2](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/effects/screen_space_reflection_scale.glsl#L100-L104)). Impacts not checked, but probably not good

- :warning: The ssr shader gets `camera_z_far` = `MAX_REAL_T` [via push constants](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/effects/ss_effects.cpp#L1467-L1468) which generates [infinite ray ends](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/effects/screen_space_reflection.glsl#L105-L106) and [`NaN` depths](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/effects/screen_space_reflection.glsl#L179-L180). Impacts not checked, but probably not good

`SSEffects::sub_surface_scattering` :
- :warning: The sss shader gets `camera_z_far` = `MAX_REAL_T` [via push constants](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/effects/ss_effects.cpp#L1644-L1645) which generates [`NaN`s in depth values](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/effects/subsurface_scattering.glsl#L154-L160). Impacts not checked, but probably not good

### `DebugEffects`

`DebugEffects::draw_shadow_frustum()`:
- :warning: [Projections of all shadow splits](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/effects/debug_effects.cpp#L214-L251) likely have both near and far set as `MAX_REAL_T`. Impacts not checked, but probably not good

### `RendererSceneRenderRD` (+ `RasterizerSceneGLES3`)

`RendererSceneRenderRD::render_scene()`
`RasterizerSceneGLES3::render_scene()`:
- :warning: [`RenderSceneDataRD` UBO](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L1154-L1155) has `zfar` = `MAX_REAL_T` which has several effects in the scene shader : [fog mip level](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1035-L1036) is always 1, [multiview cluster](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L1386-L1387) is always 0, and [interpolated vertex for dual paraboloid](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/forward_clustered/scene_forward_clustered.glsl#L491-L493) always lies on the near plane

`RendererSceneRenderRD::render_scene()`
- :warning: [FSR2](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L2371) might emit warnings as it implements infinite far with the [maximum representable float](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/thirdparty/amd-fsr2/ffx_fsr2.cpp#L324-L328) instead of infinity
- :white_check_mark: [`TAA::process()`](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L2393-L2394) and `TAA::resolve()` take z-depth and z-near as parameters but aren't used in the functions bodies

### `ClusterBuilderRD`

`ClusterBuilderRD::begin()`:
- :white_check_mark: `ClusterBuilderRD::add_box()` and `ClusterBuilderRD::add_light()` : render elements never touch the far plane
- :warning: The [`state_uniform buffer`](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/cluster_builder_rd.cpp#L436-L445) gets `inv_z = 0`, which makes the z cluster be always 0 in the [cluster_render shader](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/cluster_render.glsl#L159-L165)
- :warning: The debug shader gets `zfar` == `MAX_REAL_T` through [push constants](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/cluster_builder_rd.cpp#L539-L540) which generates `NaN` depth calculation and likely make it [output a solid color](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_rd/shaders/cluster_debug.glsl#L83-L114)

### `RendererSceneCull`

`RendererSceneCull::_light_instance_setup_directional_shadow()`:
- :warning: [Projections of all shadow splits](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_scene_cull.cpp#L2288-L2318) but the last one have both near and far set as camera znear. Impacts not checked, but probably not good. Probably what causes #81877 

`RendererSceneCull::_light_instance_update_shadow()`:
- :white_check_mark: [Convex queries](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_scene_cull.cpp#L2671-L2672) should work correctly with infinite far plane

`RendererSceneCull::_scene_cull()`:
- :white_check_mark: [frustum culling](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/servers/rendering/renderer_scene_cull.cpp#L2945-L2946) should work correctly with infinite far plane.

### `RaycastOcclusionCull::RaycastHZBuffer`

`RaycastOcclusionCull::RaycastHZBuffer::update_camera_rays()`:
- :warning: [Camera rays](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/modules/raycast/raycast_occlusion_cull.cpp#L159-L160) get `zfar` = `MAX_REAL_T`. Might have impacts on Embree logic
- :warning: [Mips](https://github.com/godotengine/godot/blob/7e99e939870fc149e42d2a76b764072f550f4b82/modules/raycast/raycast_occlusion_cull.cpp#L184-L194) are all set to `MAX_REAL_T` too

### `RenderingLightCuller`

`RenderingLightCuller::_add_light_camera_planes`
`RenderingLightCuller::add_light_camera_planes_directional`
`RenderingLightCuller::cull_regular_light`:
- :white_check_mark: Far plane has infinite intercept. Light culling should be performed correctly anyway

### `RendererSceneRender::CameraData`

`RendererSceneRender::CameraData::set_multiview_camera()`:
- :white_check_mark: The combined projection matrix should be fine with infinite far

</details>

## Test project
[PR95944.zip](https://github.com/user-attachments/files/16716771/PR95944.zip)

Camera has near = 0.05 and far ~= 1e20, perspective projection.
Pink sphere is at z ~= -1e20
Blue sphere is at z = -1e15
Green sphere is at z = -1e10
Orange sphere is at z = -1e5
Black sphere is at z = -1

**Without this PR :**

image

**With this PR :**

image

### CODE REVIEW

**Comment by tetrapod00** [comment]
Does this introduce another change in behavior when working with clip space in shaders like reverse-z did, like e.g. reconstructing position from depth? Or does the math work out such that shaders are unchanged? I don't see any GLSL in the changed files.

**Review by Flarkk — COMMENTED** [review]
No, there is no impact on shaders.
In fact, the only thing this PR changes is how the frustum planes (and specifically the far plane) are extracted from the projection matrix. The matrix itself is passed through unchanged as before to the rest of the pipeline, including the GPU parts.
Frustum planes are extracted and used in a handful of culling operations, on the CPU, mainly geometry culling and light culling.
You can find them back by searching calls to `Projection::get_projection_planes()` throughout the code.
This is really the only function affected by the PR, speaking of the core computational logic.

**Comment by Flarkk** [comment]
Stumbled upon a few other places in `Perspective` that need the fix on z plane normal calculation (other than `Projection::get_projection_planes()`).

Those functions are not used anywhere in the code (it's the reason why I missed them) but could still be called in user modules or custom builds :
- `Projection::get_projection_plane()`
- `Projection::get_z_far()`
- `Projection::get_far_plane_half_extents()`

**Comment by Flarkk** [comment]
Notes from the rendering weekly meeting : 

is it fine to “detect” infinite matrices from their values right into Projection, instead of passing through a flag set by Camera3D based on far value ? (I’ve seen a “is_orthogonal” flag passed through whereas orthogonality could have been likewise detected from the matrix components themselves)

> Yes, detecting infinite far is fine, but the fact that the projection uses an infinite far should propagate to further steps in rendering (i.e. the construction of the projection matrix + projection for screen space effects)

any further test project needed to bullet proof the fix ? (thinking of light culling, fog rendering, gi, and other stuff that uses far plane extraction)

> Extensive testing will be needed. I don't think we have test coverage over this yet. So probably need to write code tests as well as a graphical demo for comparison

any other changes you may have in mind to fully unlock infinite far planes ? (thinking of 1 minor improvement : remove far distance capping in editor - but there might be more)

> This is a good start, but the support would need to reach through the rendering pipeline to anything that is touched by the far plane. We rely on the far distance in many places in the renderer, all of these need to be checked

**Comment by roalyr** [comment]
I am sorry, I can not help with tests on this one after all. Too much work and life issues now.

**Comment by Flarkk** [comment]
Just rewrote the description of this PR to clarify what it is about exactly. Please refer to it as it may help with the below.

To the points raised during the rendering meeting (assuming @clayjohn you made most of them) :

> Yes, detecting infinite far is fine, but the fact that the projection uses an infinite far should propagate to further steps in rendering (i.e. the construction of the projection matrix + projection for screen space effects)

> This is a good start, but the support would need to reach through the rendering pipeline to anything that is touched by the far plane. We rely on the far distance in many places in the renderer, all of these need to be checked

This propagates already *by design* : the workflow is basically `user camera settings -1-> baked into a matrix in the Projection object -2-> far plane extraction from the matrix`.

The only thing this PR changes is which far plane is returned at step 2. when the matrix is detected infinite, instead of a zero-plane (zero normal and zero intercept) which raise errors for obvious reasons. What it does right now is that it returns `Vector3(0, 0, -1)` as the normal and `INFINITY` as the intercept (zfar value).

I believe what's in question is not the propagation, but rather whether `Vector3(0, 0, -1)` and `INFINITY` are good choices and don't mess things up down the line :
- I'm pretty confident for `Vector3(0, 0, -1)` as the far plane is always perpendicular to Z in all settings (Perspective, Frustum, Orthogonal). This might not be the case anymore with user-provided projection matrices though, but I'm wondering if having non Z-perpendicular infinite far planes is a use case at all.
- `INFINITY` as the intercept raises more questions in my opinion : is there any place this would generate wrong results or raise errors ? My assumption is no, and the attached demo project tends to demonstrate it, but I agree more torough testing is required here

> Extensive testing will be needed. I don't think we have test coverage over this yet. So probably need to write code tests as well as a graphical demo for comparison

I agree it's needed for intercept = `INFINITY` (see above answer). Also, the attached graphical demo covers the culling part, but not all functionalities relying of zfar / far plane, like GI.

I added a todolist in the PR desscription to track those additional steps.

**Comment by Flarkk** [comment]
@clayjohn I've started to document each impact across the rendering pipeline. See section *Infinite zfar impact analysis* in the PR description.
Can you take a quick look and tell me if this is on the right track ?

**Comment by Flarkk** [comment]
Superseded by #99986

**Pull request closed without merging**
