### PR TITLE
Added a background texture to ColorPicker

### PR DESCRIPTION
**Pull request by mrcdk**
So we can see how alpha affects the color.

For this to work the `icon_transparent.svg` needs to be added which I've already done in this other PR https://github.com/djrm/godot-design/pull/6

### CODE REVIEW

**Comment by djrm** [comment]
i would suggest a more MiniCheckerboard as name, since we already have Checkerboard.

**Comment by mrcdk** [comment]
`icon_transparent` comes from Godot 2.1 https://github.com/godotengine/godot/blob/2.1/editor/icons/icon_transparent.png

**Comment by mrcdk** [comment]
I've also added the same functionality to the presets

**Comment by djrm** [comment]
@mrcdk yeah, but we can change the names. also it seems that, there are several indentation issues with your files. and all the commits could be squashed into one.

**Comment by mrcdk** [comment]
I'll close this one and open a new one with more changes

**Pull request closed without merging**
