### PR TITLE
Add namespace generation for C# classes

### LINKED ISSUE #19174: Generated C# script class should be inside project namespace
**Godot version:**
a71b083

**OS/device including version:**
no matter

**Issue description:**
By default C# script generated without namespace, which is not good...

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #19174, other fixes did by clang-format

+Also removes spaces before statements and change them to tabs in generated file

result(in visual studio)
image

### CODE REVIEW

**Comment by neikeq** [comment]
This should the editor settings for indentation.

**Comment by Chaosus** [comment]
@Zylann Suggest your idea how to get the correct solution name.

**Comment by Chaosus** [comment]
I guess most of the users are wise and will not input special character and spaces in project name

**Comment by Zylann** [comment]
@Chaosus I do. Because project name is a name, not a code identifier.

**Comment by Chaosus** [comment]
I think simple check if project name contains non-valid character is not bad, in that case it just will not generate namespace.

**Comment by Chaosus** [comment]
Ok, @Zylann I changed it as you requested - it will not generate namespace by default if any special symbol is included in project name

**Comment by mhilbrunner** [comment]
IMO, doing nothing if the name contains special chars could be a little hard to understand for the users, usability-wise? Suggestions for other options:

- Add a method to get a "path-safe" version of the project name, and use that. Replace spaces with underscores, remove accents (so transform "è"->"e" etc.) and remove all other special chars. *This method could potentially be useful for other use cases too*.

- Add a second property like "Project name" ("Project namespace"?) that needs to be safe, so restrict input.

- Display/log a warning if the name is invalid.

I'd prefer no. 1 - thoughts?

**Comment by Chaosus** [comment]
I better close this now, as it unlikely been merged, instead I prepare patch for indentation and will not touch namespaces next time :)

**Comment by Zylann** [comment]
Oh, too bad... other than the naming thing, I thought it was a good idea to have namespaces.

**Comment by neikeq** [comment]
The default namespace is the `RootNamespace` property in the csproj, not the project name.

**Comment by mhilbrunner** [comment]
Yeah, I also thought this was a good change in general.

**Pull request closed without merging**
