### PR TITLE
Allow Attach and Clear Script on multiple nodes

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/godotengine/godot/issues/17089

Not sure if this makes sense, but an experiment to allow `Attach Script` and `Clear Script` on multi selections:

scripts

I moved the menu items lower than the single selection ones, since I think the multi selection add and clear variants can be dangerous and should not be topmost.

Clearing clears scripts on all selected nodes.

Attaching scripts takes the presets from the first selected script, but if you create or load a script in the create/load dialog, it then gets attached to all selected nodes - you need to know what you're doing obviously (in terms of class hierarchies).

I didn't touch the attach/clear script button, which still only operates on single selections.

### CODE REVIEW

**Comment by poke1024** [comment]
Added undo/redo support, so Clear and Attach Script are now undoable.

**Comment by akien-mga** [comment]
Does this really have a use case? I expect that if you need to add several nodes with the same script, you'll likely make them a scene and instance them, instead of doing it all manually.

The multiedit for clearing scripts might be slightly more useful, but even then, I'm not sure when one would use that.

Adding undoredo is nice though.

**Comment by mhilbrunner** [comment]
From a UX standpoint, couldn't this actually be harmful? If you end up doing this often, it could mean you're not using Godot's node system (and instancing) as it is intended?

I.e. whenever you have *multiple of something* and you want to clear or attach the same script, shouldn't those things really have been instances of a scene where you do so?

**Comment by poke1024** [comment]
@mhilbrunner There are border cases, where having instances is not an option, at least with the current way the editors work; for example, if you want to use and edit various `Polygon2D`s that are all customized using a script, you wouldn't want to hide them in an instance, since you can then no longer edit their vertices. I cannot think of another object type where this would be the case though.

**Comment by mhilbrunner** [comment]
@poke1024 Fair enough, didn't think of that :)

**Comment by akien-mga** [comment]
It doesn't make the code too complex and the added UndoRedo is nice, so why not :)

**Comment by girng** [comment]
@poke1024 but you can still customize their vertices and then just run a script that loops through them in `_ready`

**Comment by poke1024** [comment]
@girng Yes, I had a specific use case with a `tool` script in mind (I have one project where I use a custom polygon workflow in the editor that reshapes polygons into a game asset).

**Pull request merged**
