### PR TITLE
Use get_char_size(' ') to calculate space width.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes regressing form Text Server implementation (`get_char_size('m')` was accidentally used.)

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
Ah, I attempted a different fix here in #45923 which I believe is more correct. Spaces are generally inconsistent between fonts and not a good indication of size, which is why sometimes I used 'x' instead. This is specially a problem with mono-spaced fonts.

This PR also does not fix the scale problem, which I fixed in mine.

**Comment by bruvzg** [comment]
> Spaces are generally inconsistent between fonts and not a good indication of size, which is why sometimes I used 'x' instead.

Feel free to revert in, spaces were used before Text Server (and still used in 3.2) and change was not intentional, but they are quite inconsistent indeed.

I would use capital 'N' or 'M' (En/Em space which are standard typographic units) instead of 'm' or 'x'.

**Comment by reduz** [comment]
@bruvzg Yeah I know, this was an issue before too. I will change it to M then, thanks!

**Comment by reduz** [comment]
@bruvzg your changes for tab size are good though, so keeping those

**Pull request merged**
