### PR TITLE
SCons: Drop ios_sim option forcing x86, simulator needs x86_64

### PR DESCRIPTION
**Pull request by akien-mga**
As reported by @alketii, Xcode seems to want `x86_64` binaries to run a project through the simulator, so the previous `ios_sim` option that enforced `x86` build no longer makes sense.

@hpvb I think we might need to add `x86_64` builds to official templates so that people can use the simulator.

### CODE REVIEW

**Comment by akien-mga** [comment]
```
15:13 <alket> Akien: for future reference, I was trying to run the project on a newer Iphone, but iphone 7 and 8 support x86 but newer ones don't
```
So we likely need to keep providing both `x86` and `x86_64` for now, until we drop support for older models. (Or can we provide only `x86_64` and drop `x86` from the official templates?)

**Comment by bruvzg** [comment]
Xcode 10 dropped support for building 32-bit apps, iOS 11 dropped support for 32-bit apps.

Xcode 9 targeting iOS 10.3.3 (minimum supported iOS version for Godot currently is set to [10.0](https://github.com/godotengine/godot/blob/master/platform/iphone/detect.py#L137)) should still support 32-bit for both real iOS and simulator.

**Comment by akien-mga** [comment]
So eventually we should drop both `x86` and `arm` (armv7) support IIUC?

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7. (Did not drop the option there, but marked as deprecated.)

**Pull request merged**
