### PR TITLE
Fix tooltip content being cut off at some display scales

### LINKED ISSUE #91958: Tooltip is missing info text (Layer values, Node type, Configuration warning)
### Tested versions

Reproducable in: 
v4.2.1.stable.official [b09f793f5], 
v4.2.2.stable.official [15073afe3],  
v4.3.dev6.mono.official [89850d553]

Not reproducable in: 
v4.1.4.stable.official [fe0e8e557]

### System information

Godot v4.3.dev6.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5244) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description

The tooltip is missing all info text like collision layer values, node types and configuration warnings. Basically everything after the headline/title.

The last version I had the tooltip working was v4.1.4.stable.official [fe0e8e557].

Godot 4 2 1 Type
<br><br>
Godot 4 2 1
<br><br>

Things I couldn't reproduce was the tooltip for configuration warnings. 
Sometimes the warning was shown only the first time when hovering it, sometimes it wasn't and sometimes it was shown for the parent node but not for the child node, as seen in the video:

https://github.com/godotengine/godot/assets/35117125/cdad0b40-a60d-4893-8b6a-dd252aeef377

### Steps to reproduce

1. Create new project
2. Create a new node, for example area2d
3. Hover node in scene tree to show tooltip/hover collision layer/mask values

Edit:
4. EditorSettings: Display Scale: Custom. Custom Display Scale 1.4

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aaronp64**
When getting the minimum size for a tooltip, we get the value as a `Vector2`.  `Window::set_size()` takes a `Vector2i`, so this size was getting truncated.  At certain display scales, this could be enough to cut off part of the tooltip.  Updated to call `Vector2::ceil()` to round up before calling `Window::set_size()`

Fixes #91958

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please update the title and commit message with a clearer description that says what it fixes instead of the change

**Review by clayjohn — APPROVED** [review]
Makes sense to me. Seems like a low risk fix, so let's go ahead with it for 4.4

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
