### PR TITLE
GDScript: add builtin repeat()

### PR DESCRIPTION
**Pull request by ghost**
An alternative to https://github.com/godotengine/godot/pull/16272, using `repeat(x, n)` to mean concatenate `x` `n` times. Works for all arrays, pool array, and string types.

### CODE REVIEW

**Comment by letheed** [comment]
Wouldn't this be better as Array / String methods, like @vnen proposed?

**Comment by groud** [comment]
I would make it a method of array too, I think.

**Comment by hubbyist** [comment]
Repeat is a common operation that you may need to use on nearly all types of data so making it a buildin is logical. But a one fits all function may not be good performance wise and seems like a path to a standard library approach which may not be suitable as well.

Adding a distinct **concatenation operator** which will make both `12 & "3"` and `"12" & 3` will result as `123` and removing concatenation usage from `+` operator would be a good language feature IMO. This **concatenation operator** should only work for array like types. When operator doubled it will mean "concatenate to self" so both `"12" && 3` and `12 && 3` will result as `121212`. This would be more consistent I think. But I couldn't find a unused sign on my keyboard so had to use `"&"` as a place holder. This may be the real reason behind usage of `+` as concatenation operator in the first place :laughing: . 

So adding a repeat function to classes as @vnen suggested, in a case by case basis is the only practical approach it seems.

**Comment by poke1024** [comment]
Concerning the concatenation operator discussed by @hubbyist: I've been thinking about allowing an alternative form of function call notation in this context. Being able to write `a concat b` instead of `a.concat(b)` and `a repeat 3` instead of `a.repeat(3)` would remove the bridge to operators while at the same time keeping operator symbols cleans (as operator-like builtin functions can be used in this way without having to invent new operator symbols).

**Comment by hubbyist** [comment]
Thinking `a repeat 3` as an **operator** similar sense to operators like `or`, `and`, etc. rather than a **function call** will make things easier IMO. This will simplify this feature proposal to just adding `concat` and `repeat` operators to gdscript and (optionally) removing concatenation usage from `+` operator.

**Comment by letheed** [comment]
Err, I don't want to have to replace `+` by `concat`. That's fine if you have one, not so much otherwise (too verbose).  
If you want to remove the concatenation overload on `+`, how about we have a proper operator for that. Like `++` or something.

@poke1024 What would be the plan regarding precedence and associativity? And what about declaring new operators?

**Comment by hubbyist** [comment]
`++` is already mostly known as increment operator so it will be extremely confusing I think.

What about `><` like `"Godot" >< " Engine"` as concatenation operator? For repeat `a ><* 3` may be used.

But simply adding repeat as a literal operator as `a repeat 3` and leaving `+` operator as is may be more easy to implement.

**Comment by letheed** [comment]
I don't think `"My name is " ++ "John"` could be misconstrued for anything else than concatenation. Especially since increment is a unary operator whereas concat is binary. I don't really care whether we keep `+` or get a new one, but if we do I'd rather we picked an already [known one](https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(strings)#Common_variants) like `++` or `<>`.

I also do not think `repeat` is common enough that it deserves an official operator of its own.

**Comment by mhilbrunner** [comment]
I think `+` is fine as-is. `repeat` is useful, but I'd prefer it as method on array/string too.

**If** we really need to move concatenation to its own operator, I'd avoid `<>` however. That is **really** annoying and cumbersome to type on some keyboards. E.g. 3 keypresses per concatenation vs 1 for the current `+`. That isn't optimal for such a common operation.

Keeping in mind ease of use, code readability to newcomers and the possible learning barrier, I'd really reommend keeping `+` for concatenation. We already demand users learn a new language only for our application (GDScript), trying to offset it with "But its mostly like python!". Lets not make that unnecessarily harder. :)

**Comment by hubbyist** [comment]
Thinking twice, even for integers `12 ++ "3"` may not be that confusing as @letheed said.

But in #16462 it seems as if adding repeat function properly needs a set of similar but unique functions. So a **concatenation operator** may be more useful when you think about what @vnen said in https://github.com/godotengine/godot/pull/16272#issuecomment-362584929 IMO.

After all gdscript must be more than a python binding when needed.

**Comment by letheed** [comment]
Please no, let's not mix types in concatenation.

**Comment by girng** [comment]
@letheed see my issue #16457 about gdnative motivations. i think we need to implement a more appropriate / complex system that's more powerful than what gdnative is. which would allow modifications like this (that effects the core of the engine and its functionality) to be installed as addons.  this would make people on both of the isle, very happy i think.

**Comment by willnationsdev** [comment]
@girng 

> i think we need to implement a more appropriate / complex system that's more powerful than what gdnative is. which would allow modifications like this PR (that effects the core of the engine and its functionality) to be installed as addons.

Modifications "like this PR" that modify very specific parts of the Godot source code (in this case, adding global functions to the gdscript module) really don't have a "generic" solution that works for them. You have to address these issues on a case-by-case basis, explicitly creating a scripting API hook that would enable users to make the changes desired.

So, for example, here, the most generic solution available would be to create a scripting API method in the EditorPlugin that allows users define new gdscript global functions. In which case, a user could pass in the name of the function, a script file, and the name of a static method on that script to be called when the method is invoked. But the "create a scripting API method to do X" portion isn't something that can then also be generalized so that users can plugin stuff to any part of the source code. That sort of catch-all solution is only possible when you are plugging in completely independent code (which is what GDNative does).

**Comment by mhilbrunner** [comment]
Closing as discussed in todays meeting. Not used often enough to warrant this. It may make sense to add a special constructor for arrays to initialize them with a repeating pattern.

**Pull request closed without merging**
