### PR TITLE
Add shortcuts for New Scene and New Inherited Scene actions

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/57011.

These default to <kbd>Ctrl + N</kbd> and <kbd>Ctrl + Shift + N</kbd> respectively.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by Calinou** [comment]
> Cherry-picked for 3.4.

[I can't see this cherry-pick on `3.x`](https://github.com/godotengine/godot/blame/4075866117413773b99aecbc06b87a0ab1f4c606/editor/editor_node.cpp#L6270-L6271), did you forget to push it?

Anyway, I manually copied this to `3.x`, tested it again and opened a dedicated PR:

**Comment by akien-mga** [comment]
Hm indeed it seems like it was missed. Must have been a series of cherry-picks and I commented on this PR without issuing the cherry-pick command beforehand.

**Pull request merged**
