### PR TITLE
Add ALT NUM+ {hex code} character input support for LineEdit, TextEdit and CodeEdit.

### PR DESCRIPTION
**Pull request by bruvzg**
Implements #2689

To use, press and hold the `ALT` (`Option`) key, press and release the `numpad plus` key, type a hexadecimal Unicode character code, then release the `ALT` key.

### CODE REVIEW

**Comment by Paulb23** [comment]
Shouldn't this be restricted to Windows?

**Comment by Calinou** [comment]
> Shouldn't this be restricted to Windows?

Judging how https://github.com/godotengine/godot/pull/53702 is restricted to X11, it makes sense to restrict this feature to Windows.

On other operating systems, I suppose third-party utilities that implement similar functionality would be configured to be effective in every application anyway.

**Comment by bruvzg** [comment]
> Shouldn't this be restricted to Windows?

Maybe. For example, on macOS, a similar feature is implemented as the special keyboard layout. On the other hand, it was requested in this issue - #55410, which mention Linux. If it's not conflicting with anything, it might be useful anywhere.

**Comment by akien-mga** [comment]
Sorry for the delay. I think the implementation makes sense as is, might need a rebase though to be sure it still builds fine.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by ugothmeex** [comment]
can we also support windows altcodes ALT+NUM
Image
According to the image, Apparently most window users are known using CP437

**Comment by Calinou** [comment]
> can we also support windows altcodes ALT+NUM

There's a PR implementing this: https://github.com/godotengine/godot/pull/93466

**Pull request merged**
