### PR TITLE
glslang: Remove unused revision.template

### LINKED ISSUE #36337: Fix: Replace CRLF to LF from revision.template
**Godot version:** 4.0 master

**OS/device including version:** Ubuntu 16.04 (i tried in two different machines with Ubuntu 16.04)

**Issue description:** ./thirdparty/glslang/glslang/Include/revision.template has CRLF for new lines and makes git modify it automatically, generating unwanted changes

image

I search the entire project with a script (searching for 0x0d0a), and no other file has CLRF.

**Steps to reproduce:** Download the repository on Ubuntu 16.04 with Git 2.7.4 without setting "git config core.autocrlf input" and simple type "git diff"

### PR DESCRIPTION
**Pull request by kuruk-mm**
This PR fix this issue #36337

*Bugsquad edit:* Fixes #36337.

### CODE REVIEW

**Comment by akien-mga** [comment]
Actually it would be better to remove this file, we don't need it.

**Comment by MateoMiccino** [comment]
Done, this is fine? I can rebase and remove the 9c1a358 commit if you want

**Comment by akien-mga** [comment]
>  I can rebase and remove the 9c1a358 commit if you want

That would be perfect yes :)

**Comment by MateoMiccino** [comment]
I make it twice because i didn't see your commit message, thanks

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
