### PR TITLE
Replace color phases with color ramp for Particles2D. (need some review/guidance)

### PR DESCRIPTION
**Pull request by Biliogadafr**
I've tried to replace color phases for particles 2d with more convenient to use color ramp with dedicated editor. I'm completely not sure that I did everything correctly, especially from multithreading point of view, but at least it works. So it would be nice to hear some advices or ways of improvement of this patch.
To do this task I made a copy of existing gradient editor from shader graph editor and do some modifications to it (I decided to try replace original one with modified version later). 
So what was done:
-new resource for color ramp  + editor
-backward compatibility. Old coloring for particles 2d will be converted to color ramp (or to new color property if only one color phase was used before).
-undo/redo support.
colorramp
particlecolorramp

### CODE REVIEW

**Comment by reduz** [comment]
this looks good overall, but I would add a function to the ColorRamp
resource, something like:

Color ColorRamp::get_color_at_offset(offset) const

so Particles2D can use this more efficiently by just calling a function

**Comment by reduz** [comment]
If possible, for performance also, you could try using a VMap , which would
likely make a get_color_at_offset() function faster if you have a lot of
color nodes

**Comment by Biliogadafr** [comment]
Hm.. doesn't seems that it runs faster after this changes (actually the same fps(44) with ~10 particle systems with 1000 particles each and color ramp with 35 points... without color ramp + 3-4 fps). Need to check a bit more. Also not sure that it was a good idea to check and correct sorting in get_color_at_offset(), method. On the other side I'm not sure that it is good idea to assume that editor (or user) will provide correct order..

**Comment by reduz** [comment]
I woldn't count on user providing correct order. Did you try inlining the
function? (get_color_at_offset())

**Comment by reduz** [comment]
I still don't think it will make much a difference, but it's just something
that in the worst case it should be a bit faster

**Comment by Biliogadafr** [comment]
Changed it to be inlined. Indeed works just a bit faster on very large amount of points and particles.

**Comment by Krzycho666** [comment]
Yay! I was wainting for this for so long! Great job! =D

**Comment by Krzycho666** [comment]
I would also love to be able to send this easly to shader program.

**Comment by ThomasMorley-T3D** [comment]
Great addition!

**Comment by Krzycho666** [comment]
I've made some small new features and fixed some bug here: https://github.com/okamstudio/godot/pull/2068

**Comment by ThomasMorley-T3D** [comment]
Can anyone make this available for the 3d particles as well?

**Comment by reduz** [comment]
that is a little more complicated, the 3D particles need to move outside
the visual server first (they are old, deprecated code)

**Comment by ThomasMorley-T3D** [comment]
Well, that's slightly disappointing. Is it true that all work on the 3d engine is on hold for now?

**Comment by reduz** [comment]
It's kind of on hold because there is not really much more that can be done
with GLES2, so still waiting for Vulkan

**Pull request merged**
