### PR TITLE
Fix IPv6 linking for UWP

### LINKED ISSUE #7003: Linking error for UWP
Current master (681575f) fails on the linking phase for UWP build, related to the IPv6 addition. [Q&A post with the error](https://godotengine.org/qa/9507/error-while-trying-to-compile-godot-for-winrt-windows-phone).

```
tcp_server_winsock.winrt.opt.debug.64.x64.obj : error LNK2001: unresolved external symbol in6addr_any
packet_peer_udp_winsock.winrt.opt.debug.64.x64.obj : error LNK2001: unresolved external symbol in6addr_any
bin\godot.winrt.opt.debug.64.x64.exe : fatal error LNK1120: 1 unresolved externals
scons: *** [bin\godot.winrt.opt.debug.64.x64.exe] Error 1120
scons: building terminated because of errors
```

### PR DESCRIPTION
**Pull request by vnen**
Fix #7003.

### CODE REVIEW

**Comment by vnen** [comment]
@Faless @punto- I believe this patch doesn't change behavior but do you guys have some guidelines on how to test if this?

**Comment by punto-** [comment]
I don't have a setup to compile for winrt right now, I do remember not
being able to use that macro on win32 because it only works for
initializing an address, not for assigning, but winrt is c++14 or whatever,
so it might work..

**Comment by punto-** [comment]
that won't compile, that's why there's the lowercase thing too

**Comment by Faless** [comment]
> that won't compile, that's why there's the lowercase thing too

Well, it compiles for me on Linux and cross compiled for Max and Windows.
Also, it seems to be valid constant for:
- Linux: http://man7.org/linux/man-pages/man7/ipv6.7.html
- Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/ms738520(v=vs.85).aspx
- OSX: http://www.manpages.info/macosx/getaddrinfo.3.html
- BSD: https://www.freebsd.org/cgi/man.cgi?query=getaddrinfo&sektion=3

**Comment by punto-** [comment]
I know it's valid, I tried using it too but it didn't compile somewhere, I
think it was windows.. But if it works you can leave it..

**Comment by Faless** [comment]
@vnen if this fixes winrt then it's good to go :+1:

**Comment by vnen** [comment]
Thanks for checking out. I'll merge this to fix the build for `winrt`.

**Comment by Giacom** [comment]
Thanks, I'll try again to compile for WinRT.

**Pull request merged**
