### PR TITLE
16-bit PNG support

### PR DESCRIPTION
**Pull request by supagu**
add 16bit png support

### CODE REVIEW

**Comment by supagu** [comment]
I think ideally there should be an option to be able to determine what the destination format is, sometimes I might want half float, full float or integer format. I did initially attempt to head down that integer path first but got stuck, so I think that is a task for another day!

**Comment by aaronfranke** [comment]
I don't see why it would be useful to have anything in half-precision format if single-precision is already very well supported in programming languages, FPUs, GPUs, and the Godot codebase's color and image math. Wouldn't efficiencies gained by storing the number in less digits be negated by the conversion between half and single precision?

**Comment by Zylann** [comment]
@aaronfranke memory usage and GPU performance.

**Comment by supagu** [comment]
@reduz any chance to get this reviewed and merged in soonish?

**Comment by reduz** [comment]
As-is, this won't be merged. The main problem is, as I explained before, that a lot of software will save to 16bits without the user realizing (I remember having this problem in the past). It will just result in images erroring on import, or not acting as users expect them. This probably needs some re-thinking and redesign based on that.

**Comment by Zylann** [comment]
Should we just remove the loading from PNG but keep the Image format and texture uploading?

**Comment by reduz** [comment]
Closing this

**Pull request closed without merging**
