### PR TITLE
Make documentation sorting use natural order

### LINKED ISSUE #76718: Godot's class reference is not sorted naturally (i.e. a8 appears after a16)
### Godot version

4.0.2

### System information

Ubuntu 22.04.1 LTS

### Issue description

I was reading the class reference of FileAccess and noticed some jank. `get_8()` was positioned after `get_16()`, `get_32()`, and `get_64()`. This shouldn't be the case, as I would expect natural sorting to be used for the strings (`naturalnocasecmp_to`).

### Steps to reproduce

Look at the class reference of FileAccess.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
The reason for using a new comparison is that it otherwise changes the order of methods in a way that I feel is incorrect and breaks with how it seems to usually be done, ordering for example `is_themed` before `is_theme_valid`

Only updates the sorting of elements that were already sorted, and left the comparison of constants, arguments, and classes unchanged

Fixes #76718

### CODE REVIEW

**Comment by AThousandShips** [comment]
Might split off the comparison function into a separate PR to make it cherry-pickable and more convenient, as I think it's a good complement to `naturalnocasecmp_to` function and has relevant uses

**Review by mhilbrunner — APPROVED** [review]

**Comment by MewPurPur** [comment]
Lord, I had a dream about this PR. In the dream there was some documentary youtuber explaining how forgetting to account for underscores when using natural order sorting has lead to multiple critical software bugs. He called the bug "The French [something]".

**Comment by AThousandShips** [comment]
I'm not sure I should be flattered or worried that my code causes *other* people dreams 🤣 thank you for sharing this fact

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Pull request merged**
