### PR TITLE
Display a "broken file" icon for missing images in the asset library

### LINKED ISSUE #31683: AssetLib doesn't handle broken thumbnails properly
**Godot version:**
be99e7b

**Issue description:**
The AssetLib doesn't really know how to handle broken thumbnails:
- If the thumbnail of a video is broken, the "Play" icon is cutout:
Screenshot_20190826_133024
_(Mixing Desk)_

- ~~It's not capable of showing GIFs.~~ The engine as a whole is not capable.
- ~~Switching from and to a broken thumbnail makes the dialog contents change size:~~ Addressed by #31733.
Peek 2019-08-26 13-35
_(Godot Map Loader)_

~~And of course, the fact that it uses the Godot logo instead of a proper specific icon as a placeholder.~~ Addressed by #31719.

### PR DESCRIPTION
**Pull request by Calinou**
This partially addresses #31683.

## Preview

image

### CODE REVIEW

**Comment by YeldhamDev** [comment]
> This closes #31683.

Not really? Just the last point of it.

**Comment by Calinou** [comment]
@YeldhamDev Apologies, I didn't really think about the other points. I changed the PR description and commit message.

**Comment by akien-mga** [comment]
Thanks!

**Comment by ClubEdNZ** [comment]
This icon made me think that a plugin was broken or incompatible with my Godot version. What if the red & ripped/broken icon was replaced with a generic document icon?

doc

**Pull request merged**
