### PR TITLE
Fix `MODEL_NORMAL_MATRIX` in fragment function of spatial shader

### PR DESCRIPTION
**Pull request by Chaosus**

### CODE REVIEW

**Comment by clayjohn** [comment]
This makes me realize that we need to re-evaluate what we are doing with the regular model matrix. Both the model matrix and the model_normal_matrix get adjusted by the multimesh transform (when uses multimeshes) But in the fragment shader the extra transform is not applied so the model_matrix won't match in the fragment and the vertex shaders.

**Comment by Chaosus** [comment]
@clayjohn Should I change something in this PR?

**Comment by clayjohn** [comment]
> @clayjohn Should I change something in this PR?

Not yet no. We need to discuss what we want to do with the regular matrix as right now the model_matrix will be different between the vertex shader and the fragment shader right now which is not good.

**Comment by jsjtxietian** [comment]
Should we delete the fragement `MODEL_NORMAL_MATRIX` part in documentaion for now ? Users will get confused :   https://github.com/godotengine/godot/issues/85586

**Comment by Chaosus** [comment]
I've lost my thoughts about this PR, so I'll close it.

**Pull request closed without merging**
