### PR TITLE
GDScript: Check `get_node()` shorthand in static functions

### LINKED ISSUE #75645: Accessing scene unique nodes in a static function from a different node causes error instead of returning null
### Godot version

ef025711a

### System information

ArchLinux x11

### Issue description

Accessing a scene unique node like this:
```gdscript
class_name Class extends Node
static func get_label() -> Label:
	return %label
```
and then accessing that class later:
```gdscript
func _ready() -> void:
	Main.get_label().text = "hello world"
```
causes a strange error when in the editor, and a normal error when run directly.
image
```c++
ERROR: Node not found: "%label" (relative to "/root/main").
   at: get_node (scene/main/node.cpp:1364)
```
Instead of returning null.
As opposed to when using `get_node`:
```

SCRIPT ERROR: Cannot call method 'get_node' on a null value.
          at: get_label (res://main.gd:5)
SCRIPT ERROR: Invalid set index 'text' (on base: 'Nil') with value of type 'String'.
          at: _ready (res://control.gd:4)
```

### Steps to reproduce

Run mrp or follow outlined steps

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11148287/bug.zip)

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #75645.

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Seems fine to me! Thanks @dalexeev for the PR and the test!

**Comment by dalexeev** [comment]
Perhaps we should move `use_dollar` out of the `DEBUG_ENABLED` (here and elsewhere), I don't think it has a noticeable impact on performance and memory consumption. Especially if we bring back support for bytecode resources (`.gdc`) in the future.

**Comment by adamscott** [comment]
> Perhaps we should move `use_dollar` out of the `DEBUG_ENABLED` (here and elsewhere)

Added the PR to the list of PRs for the discussion about that.

**Comment by vnen** [comment]
> Perhaps we should move `use_dollar` out of the `DEBUG_ENABLED` (here and elsewhere) to simplify the code a bit.

It should be moved out. Especially because error messages should not differ between debug and release, because we can still run the tests with release builds and this difference would create a false negative.

**Comment by dalexeev** [comment]
> It should be moved out. Especially because error messages should not differ between debug and release

Done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.

**Pull request merged**
