### PR TITLE
Fix typos in GodotSharp code docs

### PR DESCRIPTION
**Pull request by mega-bit**
Changes 'tranfomed' to 'transformed' in several places.
Also 'calcualtion' to 'calculation'.

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Thanks for finding these typos. I just yesterday added these to the 3.2 branch, so I'm adding the cherrypick label.

**Comment by akien-mga** [comment]
Are the matching core docs correct?

**Comment by aaronfranke** [comment]
@akien-mga These don't have matching core docs, because they are in the supplementary `<param>` and `<returns>` XML fields.

The core documentation does have `<return>` and `<argument>`, but you can't put anything in them, or else the doctool deletes it.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
