### PR TITLE
Added Crash handler for Android editor. 

### PR DESCRIPTION
**Pull request by raj-extremegamerz**
Added Crash handler for Android editor so that user can get logs and report crash As soon as possible.

### CODE REVIEW

**Review by m4gr3d — CHANGES_REQUESTED** [review]
The logic in the library you're adding looks rather straightforward, so I'd rather it'd be implemented directly in the Godot source code rather than pulling a generic library with more dependencies and logics than we need.

You can notice in the source code that our gradle dependencies are rather small and contained, this is intentional.

**Comment by raj-extremegamerz** [comment]
> The logic in the library you're adding looks rather straightforward, so I'd rather it'd be implemented directly in the Godot source code rather than pulling a generic library with more dependencies and logics than we need.
> 
> You can notice in the source code that our gradle dependencies are rather small and contained, this is intentional.

Ok.

**Comment by raj-extremegamerz** [comment]
> The logic in the library you're adding looks rather straightforward, so I'd rather it'd be implemented directly in the Godot source code rather than pulling a generic library with more dependencies and logics than we need.
> 
> You can notice in the source code that our gradle dependencies are rather small and contained, this is intentional.

Now I have added Crash handler. Without dependencies.

**Comment by raj-extremegamerz** [comment]
i have created new pull request  https://github.com/godotengine/godot/pull/70988#issue-1522334170 see that one.

**Pull request closed without merging**
