### PR TITLE
[WIP] Added tabs with short and full descriptions to node creation dialog.

### PR DESCRIPTION
**Pull request by Chaosus**
image

Watch video demo here -
https://www.youtube.com/watch?v=EoVYMmHxT3o

(I used clang-format but for some reason travis failed to build)

### CODE REVIEW

**Comment by Noshyaar** [comment]
Since brief descriptions are usually not longer than 1-2 lines, I'd put the full description right after brief description so that users don't have to switch tabs.

**Comment by Chaosus** [comment]
`Since brief descriptions are usually not longer than 1-2 lines, I'd put the full description right after brief description so that users don't have to switch tabs.`
I did that already, I just changed "Description" to "Brief Description" and full description to just Description. Or I something misunderstood ?

**Comment by Chaosus** [comment]
> Edit: also I'm thinking about how it'd look if it's placed at the right side. It might give the tree more vertical space while able to show more description.

Thats how it looks(personally I prefer left align)
image

**Comment by Noshyaar** [comment]
screenshot_2018-04-26_19-30-19

**Comment by Chaosus** [comment]
Ah, I understand now, will see what I can do

**Comment by Noshyaar** [comment]
For right side, something like this: 
screenshot_2018-04-26_19-30-19x

**Comment by Chaosus** [comment]
Ok, will work on right Noshyarr's version...

**Pull request closed without merging**
