### PR TITLE
[DOCS] Some content for InterpolatedCamera

### PR DESCRIPTION
**Pull request by romlok**
A little documentation love for InterpolatedCamera.
I tried to keep it simple and follow the guidelines, but let me know if something needs changing.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Looks great! Thank you for your first contribution :)

**Comment by cbscribe** [comment]
A few stray comments for next time (could be appended to another API commit):

* Set -> Sets
* Stray commas after "If it is not [member enabled]," and "If [code]true[/code],"
* "How quickly the camera moves." This strikes me as convoluted way to avoid saying "speed"
* The brief description is missing a period

**Comment by romlok** [comment]
Thanks for the feedback.

> Set -> Sets

I initially used the Camera documentation as a guide for what I needed to do, and that document currently uses "set" for this purpose as well. Guess the fix should be a twofer!

> Stray commas after "If it is not [member enabled]," and "If [code]true[/code],"

Sometimes I think I should just prise the comma key off my keyboard. :)

> "How quickly the camera moves." This strikes me as convoluted way to avoid saying "speed"

Yeah, my original description for this was something like: "How quickly the camera moves toward the target node. Higher values will produce a tighter camera movement." Perhaps my simplification was an over-correction?
Also, I thought about mentioning that it's the *max* speed (because of tweening), and that it's measured in distance-units per second, but (aside from not knowing how to refer to Godot's arbitrary units of distance) I haven't delved into the source code, so those are just my guesses based on experimentation.

> The brief description is missing a period

I blame `git commit` habits for that one! :)

**Comment by romlok** [comment]
I've continued this with #17945

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Pull request merged**
