### PR TITLE
zstd: Update to upstream version 1.5.2

### PR DESCRIPTION
**Pull request by akien-mga**
Release notes:
- https://github.com/facebook/zstd/releases/tag/v1.5.1
- https://github.com/facebook/zstd/releases/tag/v1.5.2

Adds amd64 assembly for Huffman decompression. It appears to be enabled
gracefully by upstream macros on relevant CPUs.

### CODE REVIEW

**Comment by akien-mga** [comment]
Weird, it builds the `.S` fine locally but it skips it on Linux CI, will have to investigate.

**Comment by akien-mga** [comment]
> Weird, it builds the `.S` fine locally on Linux with GCC, but it skips it on Linux CI, will have to investigate.

Turns out I had just forgotten to add the `.S` file to `core/SCsub` so it wasn't compiled, but it's expected to be available on GCC/Clang + Linux/macOS.

**Comment by akien-mga** [comment]
@aaronfranke Are you able to test this on Linux ARM or RISC-V to make sure that it doesn't fail compiling? It should likely compile the `.S` file but not include any of its code as it's x86_64 specific.

**Comment by aaronfranke** [comment]
Yes, it works on both arm64 and rv64. This is what is printed on rv64 (it succeeds and doesn't error):

`[ 93%] clang -DDEBUG_ENABLED -DDEV_ENABLED -DNO_EDITOR_SPLASH -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DJOYDEV_ENABLED -DUDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -D_FILE_OFFSET_BITS=64 -DVULKAN_ENABLED -DGLES3_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZLIB_DEBUG -DZSTD_STATIC_LINKING_ONLY -Ithirdparty/zstd -Ithirdparty/zstd/common -Ithirdparty/zlib -Iplatform/linuxbsd -I. -c -o thirdparty/zstd/decompress/huf_decompress_amd64.linuxbsd.tools.rv64.llvm.o thirdparty/zstd/decompress/huf_decompress_amd64.S`

**Comment by bruvzg** [comment]
This breaks build on M1 mac:

```
ranlib: archive member: core/libcore.osx.opt.tools.arm64.a(huf_decompress_amd64.osx.opt.tools.arm64.o) cputype (16777223) does not match previous archive members cputype (16777228) (all members must match)
scons: *** [core/libcore.osx.opt.tools.arm64.a] Error 1
```

**Comment by akien-mga** [comment]
There was the same issue on iOS ARM64. We could add some logic to exclude compiling this file on ARM64 (as it's only meaningful for x86_64), but given that it has proper preprocessor guards I think it ought to be *compilable* and should just be a no-op on ARM64. So I suspect both the iOS and macOS SCons setup might not properly register the correct ASM compiler?

**Comment by bruvzg** [comment]
It's using `clang` to compile without any arch flags, so I guess it detects architecture from the file contents:

```
clang -DDEBUG_ENABLED -DNO_EDITOR_SPLASH -DOSX_ENABLED -DUNIX_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DGLES_ENABLED -DGLES3_ENABLED -DVULKAN_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -Ithirdparty/zstd -Ithirdparty/zstd/common -Ithirdparty/zlib -Iplatform/osx -I. -c -o thirdparty/zstd/decompress/huf_decompress_amd64.osx.opt.tools.arm64.o thirdparty/zstd/decompress/huf_decompress_amd64.S
```

**Comment by akien-mga** [comment]
Indeed, and with osxcross we use `/root/osxcross/target/bin/arm64-apple-darwin21.4-cc` so it works fine. Maybe we can specify arch flags / a prefixed binary for `S_compiler`?

Otherwise, we can exclude the file on non-x86_64 but our current tracking of which arch we're compiling for in SCons is quite brittle, as seen e.g. here: https://github.com/godotengine/godot/blob/master/modules/denoise/config.py

Should be easier once #55778 is merged.

**Comment by bruvzg** [comment]
There's no separate binaries for the different arch, so I guess the issue is SCons not passing `-arch arm64` from `CCFLAGS` (not sure what's equivalent for S compiler).

**Comment by Faless** [comment]
> so I guess the issue is SCons not passing `-arch arm64` from `CCFLAGS` (not sure what's equivalent for S compiler).

Can you try this?
```
env.Append(ASFLAGS=["-arch", ...])
```

**Comment by bruvzg** [comment]
> Can you try this?

Yes, `ASFLAGS` seems to be the correct one, and fixes the build.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6. (Together with #62587 and #62813.)

**Pull request merged**
