### PR TITLE
added bold font to EditorFonts and made tabs use it

### PR DESCRIPTION
**Pull request by toger5**
This adds bold font to the builtin fonts.
Which than is used for active tabs.

Sadly i had to rush the upload since my pc died. (doing the actual pr on my phone now ...)
And there happend something weired to the formatting ...

I will alos add a screenshot to show the effekt.
But i think bold font can be really desireable for the ui anyways. 

@djrm @vozhs what are your thoughts. Can that be used efficiently in other places too?

Also i was working on a fairly old version of godot... So i need to do some merge effort (as soon as you guys think it should get implemented)

screen shot 2018-03-06 at 11 42 19

### CODE REVIEW

**Comment by Calinou** [comment]
Does this pull request make sections in the Project/Editor Settings bold? It could be a good idea to make them stand out more.

screenshot_20180306_152716

**Comment by toger5** [comment]
@Calinou no it's only the tabs for now

**Comment by toger5** [comment]
@akien-mga was there any recent format change? I just accepted the proposed changes from the git hook..

**Comment by akien-mga** [comment]
What clang-format version do you have? You need 5.0 (6.0 might work too, not tried).

**Comment by toger5** [comment]
```timo$ clang -v
Apple LLVM version 8.1.0 (clang-802.0.41)
Target: x86_64-apple-darwin16.6.0
Thread model: posix```
@akien-mga

**Comment by volzhs** [comment]
too much unnecessary changes. I will have a look after fixing clang-format. :)

**Comment by toger5** [comment]
@volzhs it's actually a pretty small change... except the formatting ...
don't seem to be able to install newer clang with brew.

**Comment by groud** [comment]
I'm not really convinced by the bold font in tabs. It doesn't look very modern to me.

**Comment by toger5** [comment]
I got clang-format version 7 now but it still does this stupid new line for multiparae function thing....

**Comment by toger5** [comment]
@groud would u think it is useful in other places? Or should we just not add bold font as an option to the editor at all?

I honestly kind of like it. Although I'm not that convinced by the Noto-sansUI-Bold

**Comment by groud** [comment]
The bold font is probably useful yes, it's usually used as a notification marker, to notify that something should be reviewed or has changed value. But for highliting tabs its quite rare in modern UI.

**Comment by toger5** [comment]
Okay probabaly ill revert than and just do the changes for adding the bold font in one commit.
The tabs in another and than one for the sections in settings lists...
Than the code style mess should be fixed + its easy to revert the bold tabs. If they are jot desired. (i got the insparatiob from the old UI proposal by @alelpd. I think it looks really good with the font he is using.

**Comment by akien-mga** [comment]
Still needs a rebase.

**Comment by reduz** [comment]
whats the status of this?

**Comment by akien-mga** [comment]
Closing as old.

**Comment by toger5** [comment]
I will do a rewrite on a newer version.
and than do another commit which adds it to places in the editor where it makes sense.
(will rethink where to put it)

**Pull request closed without merging**
