### PR TITLE
Made a few tweaks to the ARVR interface

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Made a few small tweaks to the arvr interface.

I've removed a few functions that have been there since the start but we've never really used them and they didn't really do anything.

I've also added a few things based on the ARKit interface. I'm sure this will grow as time goes on but the more we can capture in the base interface the easier implementing solutions will be.

Obviously once merged I'll need to update all the interface to follow suit.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Added a capabilities function, will be working on some logic to add some automatic behaviour through project settings so an AR or VR interface can be initialised automatically.

@djrm , reduz mentioned I should ask you if you could make icons for the ARVROrigin, ARVRController and ARVRAnchor nodes?

**Comment by BastiaanOlij** [comment]
Not sure how important this is but I've implemented special version of the screen coordinates raycast support functions on the ARVR camera that use the projection matrix given by the ARVR interface.

Note that for stereoscopic rendering raycasting in this fashion will attempt a raycast as if the camera was a normal mono camera. However for stereoscopic HMD it's probably better to use a raycast node anyway. This change is mostly target at AR solutions where you tap on objects on the screen.

**Comment by djrm** [comment]
@BastiaanOlij yeah, im still thinking how to make those, but i will eventually come up with something, dont worry.

**Comment by BastiaanOlij** [comment]
Ok, added some more changes. Polished up the mobile vr module so it adheres to these latest changes and rename the reference frame method to center_on_hmd which is more descriptive I think. Also added a bunch more to the documentation.

I was talking to @reduz the other day about making a few more enhancements to the project settings so Godot automatically initialises part of the ARVR system but I'll do that in a separate PR when I have more time. I want to get started on the GDNative ports. 

So I think this PR is pretty much where I want it to be unless others have more suggestions on the subject.

**Comment by BastiaanOlij** [comment]
@djrm , cool, whenever you have time :)

ARVRController, obviously something that looks like a controller. I guess thats pretty hard to do on a small icon. Something like a nintendo nunchuk from the side could work.

ARVRAnchor, one of those location icons? Thats what it represents, a tracked location in the world.

ARVROrigin, also tricky, no idea what would work well to indicate the center point of something.

**Pull request merged**
