### PR TITLE
Change trackpad hint name

### LINKED ISSUE #5254: Rename "trackpad hint" to something more intuitive like "Enable 3D trackpad"
I recently checked the history for the spatial_editor_plugin class and saw that somebody had made the feature I added optional, however, I wasn't able to easily verify because it was named something that I don't think is intuitive for users: "trackpad hint".

Could we please rename this something much more obvious? "Trackpad hint" doesn't describe the feature in question, in fact, it sounds more like a "help" or "accessibility" thing for the editor. I've suggested an alternative in the title of this ticket, and would be open to discussion about what the new name should be.

### PR DESCRIPTION
**Pull request by sunnystormy**
Had an issue using the term "3D" without the editor creating whitespace between those characters. Used "Enable Trackpad" instead. Closes #5254.

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you redo your commit in a clean branch? Twelve commits for a two lines fix is a bit too much :)

**Comment by sunnystormy** [comment]
Whoops! Don't know how that happened. Will fix.

**Comment by akien-mga** [comment]
It got worse :D You should restart from a clean copy of the upstream master branch I think.

**Comment by sunnystormy** [comment]
Doing that now.

**Pull request closed without merging**
