### PR TITLE
Add signal for notify changing frames in `AnimationPlayer`

### PR DESCRIPTION
**Pull request by robfram**
Add signal for notify changing frames in `AnimationPlayer`

Added signal `frame_changed` to `AnimationPlayer`, with arguments
`anim_name`, `track_name`, `track_index` and `frame`, with the
following meaning:

- `anim_name`: name of the animation inside `AnimationPlayer`
- `track_name`: name of the track (i.e. `Sprite:position`)
- `track_index`: the index of that track inside `anim_name`
- `frame`: the key index inside that track (starting in 0)

Should implement #17623.

### CODE REVIEW

**Comment by Zylann** [comment]
Is there a way to have this feature without penalizing performance for people not using this signal?

**Comment by girng** [comment]
animation func track is so powerful too though. characters with a rigged skeleton animations are going to have massive signals being emitted with that, right? could be dangerous. 

if does it get added, i ask please for option to opt-in (if condition) before signals get emitted

**Comment by robfram** [comment]
Yes, I had the same thoughts while coding it. I sent the PR for a discussion.

It's definitively too much signals in any case. I really don't think a notification in every frame is usefull. I have some ideas but I don't know if the use cases are covered by them. The most useful I see is this:

**You can set the animation keys to emit the signal with an argument.** For example, you can set the walking_anim/Sprite:position key at 2.3s (the 14th key of that track, index 13) to emit the `key_trigger` signal with the String argument `walking_left_foot`. This way, you can choose exactly which keys are the one you are interested in listening. In this example, the received signal could be somehow similar  to the one in the PR: `_on_key_trigger('walking_left_foot', 'walking_anim', 'Sprite:position', 0, 13)`

If a lot of signals are sent at the same time, perhaps the parameters could be converted to arrays or lists, but generating the same signal, or grouped by anim name or the custom String to emit.

**Comment by mysticfall** [comment]
To clarify my use cases in #17623, it is not required to received such signals in per-track basis and I don't even need any parameters (though, maybe timestamp would be nice to have).

Unity provides 'layer index' as the sole parameter of its `OnAnimatorIK` callback, but we don't have such a concept yet, so I guess we won't need it for now.

So, if there to be any significant performance overhead with adding many parameters to such a signal, I'm fine with omitting them since it wouldn't affect such use cases covered by #17523.

**Comment by reduz** [comment]
This is overkill, i suggest looking for a different way to solve the problem

**Comment by robfram** [comment]
Yes, I think this is (as the PR implements it) absurd.

I don't know if a valid solution could be have a "special" track for signals. And adding keys to that track would create the event for emit the signal. Thus, every time a key in that track is reached, the object will emit the signal. Only one signal track per object, one key per frame max, as the rest of tracks.

**Comment by reduz** [comment]
closing as no consense

**Pull request closed without merging**
