### PR TITLE
Add ONE constants to Vector2 and Vector3

### LINKED ISSUE #22806: "ONE" constant for Vector3/Vector2
The only Vector3 constant that's missing compared to Unity is `Vector3.ONE`, which is shorthand for `Vector3(1, 1, 1)`. It's something I didn't push for before #14704 was merged since I thought that PR was on pretty thin ice at the time, but now that it's in it would be nice to have it added once and for all.

The same could also be done for Vector2 (`Vector2.ONE` as a shorthand for `Vector2(1, 1)`)

### PR DESCRIPTION
**Pull request by KellyThomas**
also updates class documentation xml
fixes https://github.com/godotengine/godot/issues/22806

### CODE REVIEW

**Comment by samgreen** [comment]
Haha, well done. You beat me by moments.

**Comment by homer666** [comment]
I think it would also be a good idea to add them to Mono, like you did with the original constants in #20901.

**Comment by akien-mga** [comment]
> zero

> ONE

If that isn't obfuscation :thinking:

**Comment by KellyThomas** [comment]
@homer666 
The mono vectors have had `One` for a while:  

https://github.com/godotengine/godot/blob/master/modules/mono/glue/Managed/Files/Vector3.cs#L294

https://github.com/godotengine/godot/blob/master/modules/mono/glue/Managed/Files/Vector2.cs#L253

**Comment by KellyThomas** [comment]
@akien-mga 
Thanks, the commit message has been fixed

**Comment by aaronfranke** [comment]
This PR is missing the documentation changes. https://github.com/godotengine/godot/blob/master/doc/classes/Vector2.xml Note that the doc for zero vectors is wrong (for some reason it's called "Null vector" instead of "Zero vector") so you could fix that up too while you're at it.

**Comment by KellyThomas** [comment]
@aaronfranke Good idea!  The documentation has been added.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
