### PR TITLE
Rename `button_pressed` default signal binding to avoid shadowing

### PR DESCRIPTION
**Pull request by MewPurPur**
Title says it all :3

### CODE REVIEW

**Comment by akien-mga** [comment]
> Title says it all :3

But commit seems confused :P

**Comment by AThousandShips** [comment]
Documentation for signal hasn't been corrected

**Comment by MewPurPur** [comment]
Oh, the commit seems an issue with my terminal, it often glitches out on newlines... Do I gotta amend it?

**Comment by AThousandShips** [comment]
You have to fix the documentation for the signal, you've only updated the virtual function

**Comment by akien-mga** [comment]
> Oh, my terminal often glitches out on newlines and screws up text... Do I gotta amend it?

Yes, with `git commit --amend`.

**Comment by MewPurPur** [comment]
_pokepoke?_

**Review by akien-mga — APPROVED** [review]
Looks good to me. _Technically_ breaks compat for C# if users were using named arguments... but that's not the first nor the last.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
