### PR TITLE
Label: add auto_height

### LINKED ISSUE #7679: Word wrap makes label unreadable when put in VBoxContainer
Tested on Godot 2.1.1 and 2.1.2, Windows 10 64 bits

What I did:
Create a VBoxContainer, and add a few labels in it, all of them with some text. Enable word wrapping (auto-wrap) on one of them.

What happened:
The label shrunk to a height of 1, making the text unreadable. It can be resized but it overlaps on the following labels.

What was expected:
Be able to see the text, and have the label increase in height if word wrap makes it create visual line breaks so it push next items down (related to https://godotengine.org/qa/11957/how-can-set-label-change-size-according-the-length-of-the-text)

Screenshot:
godot_label_wordwrap_vbox

### PR DESCRIPTION
**Pull request by ghost**
Fixes #7679 if merged.

I've seen #4379 and I'm not sure why width-based height would not work. (Width affects height, not the other way around.)
I have not experienced any issues so far, no noticeable adjustment loops.

ezgif-1-ba8dcc7f9c

More screencast: [VBoxContainer](https://user-images.githubusercontent.com/26753932/28455123-21a0541a-6e28-11e7-9bc5-a6740fea6da4.gif), [HBoxContainer](https://user-images.githubusercontent.com/26753932/28455127-26514d2a-6e28-11e7-9307-7742fc12bd53.gif), [GridContainer](https://user-images.githubusercontent.com/26753932/28461019-f0bac1f2-6e3e-11e7-89b9-44b82ce9ddad.gif)

### CODE REVIEW

**Comment by groud** [comment]
IMHO, this is a good feature. :)

However, it don't this should be optional, but instead linked to both the clip_text and wrap_text option.
Indeed this option is mostly useful if `clip_text==false` and `wrap_text == true`. 

PS: I'm open to counter-example, this is mostly an intuition ^^

**Comment by Noshyaar** [comment]
I make it optional because the minimum height set by this property cannot be overridden by smaller values. (can only be expanded, but not shrunk)

**Comment by groud** [comment]
Yeah, but if you need smaller values for the height, this means that the `clip_text`option should be true. Indeed, if you reduce the label height, part of the text will be not visible, which basically corresponds to text clipping.

**Comment by Noshyaar** [comment]
That makes sense. Will commit soon. :)

**Comment by groud** [comment]
Little edit: the `wrap_text == true` is in fact not necessary. 
The only condition to me is in fact  `clip_text==false`. Indeed, if you have new lines added manually, thi still makes sense.

**Comment by reduz** [comment]
I would make this a separate option. We could have 3 modes:
Fixed
Wrap
Wrap Constrained

or something like that instead of the boolean wrap

**Comment by akien-mga** [comment]
As discussed on IRC, let's try the current API and see how it behaves :)

**Pull request merged**
