### PR TITLE
[3.x] Add binary MO translation file and brotli decoder and WOFF2 support.

### PR DESCRIPTION
**Pull request by bruvzg**
Backport of #59276, #59275, #59483 and #59510

Decreases editor size by about 6.8 MB.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
> Can I use Brotli to decompress data in a PoolByteArray?

The Brotli compressor isn't exposed – it's only used internally for WOFF2 fonts.

I'm not sure how much work it would be to add it as a compression mode in Godot's APIs (File, , high-level multiplayer, etc). cc @bruvzg

**Comment by bruvzg** [comment]
> I'm not sure how much work it would be to add it as a compression mode in Godot's APIs (File, high-level multiplayer, etc). It would make sense to support Brotli compression for transparent decompression of HTTP requests, but we've had numerous issues when trying to implement transparent gzip decompression in the past.

For 4.x, adding it as another mode to the existing `Compression` class (which is used by `FileAccessCompressed`, `ENetConnection` and `PackedByteArray.compress/decompress`) should be easy, I'll take a look tomorrow.

**Comment by skyatgit** [comment]
I have tried using the c # version of Godot, but there is no brotli related decompression algorithm in the .net framework 472. I added a third-party<PackageReference Include=" BrotliSharpLib "Version=" 0.3.3 "/>via NuGet, which can run normally on Windows, but when I export to the Android version, as long as I run to the decompression method, the program will crash.
but I don't have any more technical skills to solve the crash problem

**Pull request merged**
