### PR TITLE
Unfocus LineEdit when pressing Escape

### LINKED ISSUE #7543: Allows SpinBox to drop focus when pressing Escape
### Describe the project you are working on

Various GUI apps.

### Describe the problem or limitation you are having in your project

I'm annoyed by SpinBoxes not being able to easily lose focus. I often run into a situation where I input some number and then try to do something, but can't because SpinBox eats my input. It's especially a problem when there is no other control that you can click to release the focus. Also it doesn't help that the only way to remove focus is using left click, which can sometimes lead to unwanted actions, like painting something in an editor.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

SpinBox should lose focus when pressing Escape.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Here's the implementation:
https://github.com/godotengine/godot/commit/e6aaab06277439e2cc6c2540a5acccfe628652d3
The change actually had to be done in LineEdit, because it's what SpinBox uses internally.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can, but if you need to attach such script to every SpinBox then it probably qualifies as used often.

### Is there a reason why this should be core and not an add-on in the asset library?

See above. There is no global solution that can be an addon.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/7543

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Makes sense to me.

More reviews from @godotengine/gui-nodes welcome.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
Would this make sense to do for TextEdit as well?

**Comment by KoBeWi** [comment]
It could be used for multiline fields in the inspector, so IMO makes sense. (I also have a plugin that would benefit from this)

**Comment by nathanfranke** [comment]
Probably should use `accept_event()`, this stops `_unhandled_input` from also being called for escape.

```gdscript
# gdscript not C++, but this works as expected on LineEdit
func _gui_input(event: InputEvent) -> void:
	if event.is_action(&"ui_cancel"):
		release_focus()
		accept_event()
```

---

Otherwise, if I have escape on unhandled input to reload current scene, I get this (separate bug?),
```
E 0:00:01:0304   release_focus: Condition "!is_inside_tree()" is true.
  <C++ Source>   scene/gui/control.cpp:2018 @ release_focus()
```

MRP:
```gdscript
func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed(&"ui_cancel"):
		get_tree().reload_current_scene()
# plus LineEdit somewhere
```

---

(Also, TextEdit makes sense yes)

**Pull request merged**
