### PR TITLE
remove trailing whitespace

### PR DESCRIPTION
**Pull request by Marqin**
You shouldn't trust such big commits. And to check that it only changes whitespace characters at the end of lines, you can append `?w=` at the end of commit URL ( https://github.com/Marqin/godot/commit/583a802185fe953d495d3d85adf9fb7a1556707b?w=1 ) and Github will hide all non-whitespace changes. Also, there are some [flags](https://git-scm.com/docs/git-show) for `git show` to hide whitespace changes.

### CODE REVIEW

**Comment by Marqin** [comment]
Please, cleanse this repo from whitespace cancer.

**Comment by akien-mga** [comment]
Related to #3916. It's a good change but might break PRs, so... I'll let @reduz have his word on this.

**Comment by Marqin** [comment]
I've only changed `.cpp` and `.h` files, and use this command:

    find . -type f -name "*\.cpp" -o -name "*\.h" -print0 | xargs -0 -I {} sed -i '' -e's/[[:space:]]*$//' "{}"

**Comment by akien-mga** [comment]
Don't trust the email GitHub sent for this PR, it shows many files with a status of ```I``` and no change, but https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/3928.patch shows that there are indeed changes.

However, I think we shouldn't touch the embedded libraries in the ``drivers/``. The less custom changes we make there, the less difficult they will be to update to newer upstream versions.

**Comment by est31** [comment]
Half of the changes of this PR are from directories like `drivers/speex` or `drivers/builtin_openssl2` that get reverted to old state the next time the dependency gets updated, that permanently bloats the repo size for nothing.

**Comment by est31** [comment]
> 400 files changed, 7678 insertions(+), 7678 deletions(-)

Sounds much nicer now :)

**Comment by Marqin** [comment]
Ok, I've redone ( and rebased ) this commit  and ignored `./drivers`. Here's the command:

    find . -type f \( -name "*\.cpp" -o -name "*\.h" \) -a \( ! -path "./drivers/*" \) -print0 | xargs -0 -I {} sed -i '' -e's/[[:space:]]*$//' "{}"

**Comment by akien-mga** [comment]
Looks good. (Wow TextEdit, so many changes!)

**Comment by Marqin** [comment]
Personally I think it's better to pull it now, and then enfore all PR guys to fix their commits to nt have trailing whitespaces. If we say "do it later" then "later" will be Soon™ or even nevermln.

**Comment by Marqin** [comment]
rebased because of conflicts + added GPG signature to commit

**Pull request merged**
