### PR TITLE
Fix toggling a plugin makes its name black

### LINKED ISSUE #88714: Toggling a plugin makes its name black
### Tested versions

Likely regression from #88308
CC @Mickeon 

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/127c7fed-5ab3-4fd8-9eb7-83ab8c35f9e5

### Steps to reproduce

1. Have a plugin
2. Go to Plugins tab in project settings
3. Disable and enable it

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Mickeon**
Fixes https://github.com/godotengine/godot/issues/88714 (not tested)

### CODE REVIEW

**Review by ryevdokimov — APPROVED** [review]
Before: 

https://github.com/godotengine/godot/assets/105675984/1e6ca660-8d97-4dfe-8ced-c6819b96f83c

After:


https://github.com/godotengine/godot/assets/105675984/26266a46-5563-41bb-8bba-dcf78463300b

**Comment by Mickeon** [comment]
Thank you kindly for taking your time and testing this yourself.

Welp. That was annoyingly worse and I cannot compile this for myself at the moment.

**Comment by ryevdokimov** [comment]
Oh, was it supposed to go grey when toggled off? I was comparing it to 4.2 behavior.

**Comment by Mickeon** [comment]
Yes. Correct. That's the intended behavior.

**Comment by ryevdokimov** [comment]
Got it, I'll give it another look after the checks are complete.

**Comment by ryevdokimov** [comment]
Looks good now: 

https://github.com/godotengine/godot/assets/105675984/6025c59c-f59e-491e-a23e-b31055eff10e

**Review by ryevdokimov — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]
LGTM, haven't tested but code makes sense

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
