### PR TITLE
Draw gray blocks into atlas image preview

### PR DESCRIPTION
**Pull request by DmitriySalnikov**
This is a copy of PR #297 adapted to the new version of the engine. Thank you @sanikoyes

godot windows tools 32_2016-06-03_02-32-19

### CODE REVIEW

**Comment by akien-mga** [comment]
@DimOkGamer Could you squash the two commits together?

**Comment by bojidar-bg** [comment]
Copy from @reduz 
> this is nice, but it would probably be best to do it in the preview dialog, in project_export.cpp as another layer by just dawing the blocks in the NOTIFICATION_DRAW callback

**Comment by DimOkGamer** [comment]
@akien-mga done.

**Comment by reduz** [comment]
here's a less hacky way to do the same, simply put a control behind the preview and use this code to draw it:

https://github.com/godotengine/godot/blob/master/tools/editor/plugins/texture_editor_plugin.cpp#L28

**Pull request closed without merging**
