### PR TITLE
Fix CSGPolygon3D in path mode disappearing at runtime

### LINKED ISSUE #72771: CSGCombiner3D is modified when changing scenes with change_scene_to_file
### Godot version

v4.0.beta.custom_build [2bd530270] ; v4.0.beta17.official [c40020513]

### System information

Windows 10, Vulkan

### Issue description

This is a regression since v4.0.beta16.official [518b9e580], though I haven't bisected the commit that caused it.

When using `change_scene_to_file` to load into a new scene, a CSGCombiner3D with a child CSGPolygon3D is modified from how it looks in the editor (or running the scene first).
Observe how the MRP scene looks in the editor:
image

How it looks when using Run Current Scene (F6):
image

How it looks when running the project with a simple script that loads into the same scene:
image

The script:
```gdscript
extends Control

func _ready() -> void:
	get_tree().change_scene_to_file("res://node_3d.tscn") # res://node_3d.scn is the same scene but it wouldn't open in Beta 16 that I used to test (corrupt)
```

The hole is gone. The remote editor seems to show the same values and the nodes are all there.
I don't know if something else broke with `change_scene_to_file`, if someone knows a workaround please share it.

### Steps to reproduce

Run the MRP. Note: the 3d scene .scn binary format won't open in Beta 16, the .tscn is the same scene and it opens, that might be a clue.

### Minimal reproduction project

[csg bug.zip](https://github.com/godotengine/godot/files/10612034/csg.bug.zip)

### PR DESCRIPTION
**Pull request by etodd**
This partially reverts #72427 in order to fix #72771.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @MinusKube

**Comment by etodd** [comment]
I should note that I also tested this with collision turned on and didn't see any errors or crashes, so hopefully that means the original bug is still fixed.

**Comment by akien-mga** [comment]
Tested on a [project of mine](https://github.com/team-godog/NGJ2023_Godog) with heavy CSGPolygon3D with path usage, didn't spot a regression. I haven't tested long enough to make sure that I couldn't reproduce the bug anymore, but I did experience it back when I was making that project for a game jam.

**Review by akien-mga — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Pull request merged**
