### PR TITLE
Use `TypedArray<Vector3i>` for `GridMap::get_used_cells_by_item`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by fire-forge — APPROVED** [review]

**Comment by akien-mga** [comment]
What's the rationale for the change? I'm not against it but since it's not done for the very similar `get_used_cells` it's a bit inconsistent.

**Comment by octetdev2** [comment]
`get_used_cells` was done in https://github.com/godotengine/godot/pull/60053

**Comment by akien-mga** [comment]
They should be done in the same commit and PR, they're closely related and the exact same code change, so they're best reviewed and merged at once.

**Comment by akien-mga** [comment]
Superseded by #64009.

**Pull request closed without merging**
