### PR TITLE
Fixes crash on using `ShaderGlobalsOverride.new()._activate()`

### LINKED ISSUE #45984: Executing ShaderGlobalsOverride.new()._activate() crashes engine
**Godot version:**
4.0.dev.custom_build. f0951537a

**Issue description:**
```
ShaderGlobalsOverride.new()._activate()
```
cause crash with backtrace
```
ERROR: Condition "!data.tree" is true. Returning: nullptr
   at: get_tree (./scene/main/node.h:281)
scene/main/shader_globals_override.cpp:221:32: runtime error: member call on null pointer of type 'struct SceneTree'
scene/main/shader_globals_override.cpp:221:32: runtime error: member access within null pointer of type 'struct SceneTree'
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godot4s() [0x1e21880] (/mnt/Miecz/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f6b00b51210] (??:0)
[3] ShaderGlobalsOverride::_activate() (/mnt/Miecz/godot/scene/main/shader_globals_override.cpp:221 (discriminator 1))
[4] void call_with_ptr_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), void const**, IndexSequence<>) (/mnt/Miecz/godot/./core/variant/binder_common.h:218 (discriminator 4))
[5] void call_with_ptr_args<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), void const**) (/mnt/Miecz/godot/./core/variant/binder_common.h:436)
[6] MethodBindT<>::ptrcall(Object*, void const**, void*) (/mnt/Miecz/godot/./core/object/method_bind.h:293)
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot/modules/gdscript/gdscript_vm.cpp:1707)
[8] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/modules/gdscript/gdscript.cpp:1544)
[9] Object::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/core/object/object.cpp:765 (discriminator 1))
[10] Variant::call(StringName const&, Variant const**, int, Variant&, Callable::CallError&) (/mnt/Miecz/godot/core/variant/variant_call.cpp:611)
[11] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/godot/modules/gdscript/gdscript_vm.cpp:1374)
[12] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/godot/modules/gdscript/gdscript.cpp:1544)
[13] ScriptInstance::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot/core/object/script_language.cpp:303)
[14] Node::_notification(int) (/mnt/Miecz/godot/scene/main/node.cpp:147)
[15] Node::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/node.h:45 (discriminator 14))
[16] CanvasItem::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/main/canvas_item.h:164 (discriminator 3))
[17] Node2D::_notificationv(int, bool) (/mnt/Miecz/godot/./scene/2d/node_2d.h:37 (discriminator 3))
[18] Object::notification(int, bool) (/mnt/Miecz/godot/core/object/object.cpp:795)
[19] Node::_propagate_ready() (/mnt/Miecz/godot/scene/main/node.cpp:189)
[20] Node::_propagate_ready() (/mnt/Miecz/godot/scene/main/node.cpp:179 (discriminator 2))
[21] Node::_set_tree(SceneTree*) (/mnt/Miecz/godot/scene/main/node.cpp:2580)
[22] SceneTree::initialize() (/mnt/Miecz/godot/scene/main/scene_tree.cpp:393)
[23] OS_LinuxBSD::run() (/mnt/Miecz/godot/platform/linuxbsd/os_linuxbsd.cpp:256)
[24] godot4s(main+0x40b) [0x1e1f541] (/mnt/Miecz/godot/platform/linuxbsd/godot_linuxbsd.cpp:60)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f6b00b320b3] (??:0)
[26] godot4s(_start+0x2e) [0x1e1f07e] (??:?)

```

### PR DESCRIPTION
**Pull request by vignesh-j-shetty**
Fixed by adding null checker. As get_tree() just returns pointer. So no need of temporary variable to check for nullptr

<i>Bugsquad edit</i>: Fix #45984

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request!

Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) (`git commit --amend`). This way, people reading the Git log can easily figure out what's going on :slightly_smiling_face:

**Comment by Vignesh1-art** [comment]
> Thanks for opening a pull request!
> 
> Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) (`git commit --amend`). This way, people reading the Git log can easily figure out what's going on 🙂

Should I do changes to this PR. Next time I will keep in mind your advice

**Comment by Vignesh1-art** [comment]
> git commit --amend

I did that. But it is not updating in remote server.

**Comment by Calinou** [comment]
> > git commit --amend
> 
> I did that. But it is not updating in remote server.

You need to force push the amended commit using `git push -f`.

**Comment by Vignesh1-art** [comment]
> > > git commit --amend
> > 
> > 
> > I did that. But it is not updating in remote server.
> 
> You need to force push the amended commit using `git push -f`.

I have updated commit message :
)

**Pull request closed without merging**
