### PR TITLE
Improve documentation for BaseMaterial3D's alpha scissor threshold

### PR DESCRIPTION
**Pull request by Calinou**

### CODE REVIEW

**Comment by akien-mga** [comment]
Might be worth linking to the relevant part of the glTF spec to document why this value is used (in the constructor)?

**Comment by reduz** [comment]
The problem with 0.5 instead of 0.99 is that when filter is used for something like pixel art in 3D, you will see some extra outline that will generally be unintended.

**Comment by reduz** [comment]
But looking at the current value being 0.05 I have no idea. Would be nice to research why the current value is where it is.

**Comment by Calinou** [comment]
> is that when filter is used for something like pixel art in 3D

I think there are other problems if you're using filter with pixel art in 3D :slightly_smiling_face: 

(Unless you're using a shader like [Smooth pixel filtering](https://godotshaders.com/shader/smooth-3d-pixel-filtering/), of course.)

**Comment by clayjohn** [comment]
Just needs a rebase, the actual change was merged already in your other PR https://github.com/godotengine/godot/pull/54028 which (strangely enough was approved by reduz one week before commenting on this PR

For future reference 3.x uses a default of 0.98, it was changed to 0.05 in https://github.com/godotengine/godot/pull/40364 and no comment was made about why it was changed.

**Comment by Calinou** [comment]
Indeed, I forgot I had made a PR about this last year…

> Just needs a rebase

The only thing this PR now does is add a comment about 0.5 being the default in the glTF specification. Should we still merge it?

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
