### PR TITLE
Change function signature from float to double to match type get_doub…

### LINKED ISSUE #16160: StreamPeerBuffer put_double() loss of precision
**Godot version:**
v3.rc1

**Issue description:**
Loss of double precision when call put_double(). 
Possible need fix at https://github.com/godotengine/godot/blob/3.0/core/io/stream_peer.cpp#L313 (replace return value type from float to double)

**Steps to reproduce:**
```gdscript
extends Node
func _ready():
	var d = 12.34
	var sp = StreamPeerBuffer.new()
	sp.put_double(d)
	# Representation:
	# binary: 40 28 AE 14 7A E1 47 AE
	# decimal: 1.2339999999999999857891452848E1
	# precision: double
	print(str_raw_array(sp.get_data_array()))
	sp.seek(0)	
	# Loss of precision when constructing double
	# https://github.com/godotengine/godot/blob/3.0/core/io/stream_peer.cpp#L313
	var d1 = sp.get_double() # In source code returning float, must return double
	print(d1)
	var sp1 = StreamPeerBuffer.new()
	sp1.put_double(d1)
	# Representation:
	# binary: 40 28 AE 14 80 00 00 00
	# decimal: 1.2340000152587890625E1
	# precision: single
	print(str_raw_array(sp1.get_data_array()))
	sp1.seek(0)
	var d2 = sp1.get_double()
	print(d2)
	var sp2 = StreamPeerBuffer.new()
	sp2.put_double(d2)
	print(str_raw_array(sp2.get_data_array()))
	sp2.seek(0)
	var d3 = sp2.get_double()
	print(d3)
	pass
# debug print
static func str_raw_array(arr):
	var res = "<<"
	for i in range(arr.size()):
		if i == (arr.size() - 1):
			res += str(arr[i]) + ">>"
		else:
			res += str(arr[i]) + ","
	return res
```

**Minimal reproduction project:**
[streambuffer.zip](https://github.com/godotengine/godot/files/1672825/streambuffer.zip)

### PR DESCRIPTION
**Pull request by hungrymonkey**
…le Closes #16160

### CODE REVIEW

**Comment by hungrymonkey** [comment]
Ran the test project

before

`<<174,71,225,122,20,174,40,64>>
12.34
<<0,0,0,128,20,174,40,64>>
12.34
<<0,0,0,128,20,174,40,64>>
12.34
`

after

`<<174,71,225,122,20,174,40,64>>
12.34
<<174,71,225,122,20,174,40,64>>
12.34
<<174,71,225,122,20,174,40,64>>
12.34
`

**Comment by hungrymonkey** [comment]
I want to say that the doc explicitly say float

http://docs.godotengine.org/en/latest/classes/class_streampeer.html

**Comment by hungrymonkey** [comment]
Should i change the docs too?

**Comment by vnen** [comment]
You can't really change the docs because in Godot there's not really a `double` type.

**Comment by hungrymonkey** [comment]
@vnen as i thought. After I wrote the commit, I realize the float as a bit deliberate. 

I am not sure what to do with this pull request. Maybe I should close it.

**Comment by vnen** [comment]
I think this PR is okay. Floating point numbers are stored with double precision inside Variant. Even though it's called `float` in the docs, the change here will make a difference.

**Pull request merged**
