### PR TITLE
[WIP] Implement distance fade and transparency

### PR DESCRIPTION
**Pull request by reduz**
* ALPHA in shader comes pre-set with a distance fade. Multiply by it if you want fade to work.
* Added transparency and distance fade for clustered renderer.
(will add support in mobile renderer after it works).

Currently this does nothing, this PR is intended to be continued by @JFonS.

### CODE REVIEW

**Comment by Calinou** [comment]
For the dithering part, remember that interleaved gradient noise could be used to have a cheaper and better-looking effect: https://github.com/godotengine/godot/pull/50297

**Review by JFonS — APPROVED** [review]
Looks good.

**Comment by reduz** [comment]
@Calinou I will add a render mode to make alpha use dithered noise and remain opaque so, if you want objects to fade this way, you can also. Afterwards will remove all the distance fade code from StandardMaterial.

**Comment by Calinou** [comment]
> Afterwards will remove all the distance fade code from StandardMaterial.

Distance fade can still be used to fade objects that are close to the camera (e.g. third-person character), so I'd keep it for that reason.

**Pull request closed without merging**
