### PR TITLE
Improve error message when trying to instantiate a script with `_init(...)`

### LINKED ISSUE #8488: Improve error message when Godot is unable to construct GDScriptInstance
### Describe the project you are working on

I am building an addon to manage RPG data.

### Describe the problem or limitation you are having in your project

For optimal clean code, we addon developers like to use the `_init()` function as a custom constructor for objects, as it forces the user to always initialize an object:
```gdscript
class_name MyNode extends Node

var _value:int

func _init(arg:int):
   _value = arg
```
This works fine, especially for custom data structures that are not utilizing the scene tree. However, when adding a node to a scene tree and attaching the script above, Godot will spit out an error that is very confusing to people who never encountered it before:
```
_create_instance: Error constructing a GDScriptInstance.
```
While the above error is logical and makes sense (as Godot requires an `_init()` constructor to call `.new()`), it is irritating to users.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The error can potentially occur in multiple scenarios:

1. `_init()` function with arguments defined
2. script has a syntax error

This proposal aims to improve the error messages around these two scenarios.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When there are no script errors but a custom `_init(...)` function was defined, show an error like this:
```
Unable to create node /root/path/to/node/in/scene/tree: script does not define _init().
```
and in case of script errors:
```
Unable to create node /root/path/to/node/in/scene/tree: script has errors.
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No workaround sadly, apart from spending potentially hours trying to understand the issue (in larger code bases)

### Is there a reason why this should be core and not an add-on in the asset library?

As the original vague error is in core.

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes godotengine/godot-proposals#8488

### CODE REVIEW

**Comment by AThousandShips** [comment]
See also:
* https://github.com/godotengine/godot/pull/76632

**Comment by Mickeon** [comment]
Is it possible, and could it be nice to explicitly state _how many_ parameters are required?

**Comment by HolonProduction** [comment]
Is possible. But doesn't help in the context of the proposal since no parameters can be passed. But yeah the error contains the expected amount of args so adding it to the message is possible.

**Comment by AThousandShips** [comment]
I'd say that #76632 is more comprehensive as it also adds error information (ignore the accidental inclusion of unrelated code by the OP of that PR, hopefully that'll get fixer or a new branch made)

**Comment by AThousandShips** [comment]
Also this solution prints this message when creating an instance with too few arguments yet not none, as it is called in other situations as well, not just resource initialization, so I think the other PR is better for this

**Comment by HolonProduction** [comment]
Adding the call error is definitely right. (I could probably include the changes into this PR to resolve the rebase mess up). I am just curious whether it is helpful in the context of https://github.com/godotengine/godot-proposals/issues/8488. Or if we need to extend the error message to be helpful in that context. I'll have a look at the specific message.

**Comment by HolonProduction** [comment]
Closing in favor of #76632

**Pull request closed without merging**
