### PR TITLE
Unify PathFollower's h/v offsets to a single Vector2/3

### LINKED ISSUE #5104: Rename some properties of PathFollower3D and PathFollower2D
### Describe the project you are working on

A road traffic game, where roads are described by 2D or 3D curves. Curves are constantly sampled in order to convert the position of cars from linear coordinate to descartes coordinate.

### Describe the problem or limitation you are having in your project

In the process of moving rotation interpolation code from PathFollower to Curve(see PR [#63956,](https://github.com/godotengine/godot/pull/64043) PR [#64043),](https://github.com/godotengine/godot/pull/63956) I feel some naming of properties are not clear.

1. On `PathFollower3D`:
    - `h_offset`: the doc says "The node's offset along the curve". But it is incorrect, it actually represents the offset along the "Sideway"(right hand) direction in the code.
    - `v_offset`: the doc says "The node's offset perpendicular to the curve". The concepts of "vertical" or "perpendicular" make sense for 2D curve but are ambiguous for 3D curve. It actually represents the offset along the "Up" direction in the code.
    - for completeness, there should be an offset along the tangent direction(or "Forward" direction in the code), but it is missing.

2. On both `PathFollower2D/3D`: the `offset` property indicate the distance moving from the beginning along the **curve**, which have different quality as `h_offset` or  `v_offset`, as they move along **straight** vector. Use the same word "offset" could create confusion for new user.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
for `PathFollower3D`
combine `v_offset` ,`h_offset`, `f_offset` into a Vector3 `offset`

for `PathFollower2D`
combine `v_offset`, `h_offset` into a vector3 `offset`,
  
for both `PathFollower3D` and `PathFollower2D`
    - change `offset` to `progress`,
    - change `unit_offset` to `progress_ratio`

The new names feel more consistent and clear.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I can make this change in a separate PR.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

no

### Is there a reason why this should be core and not an add-on in the asset library?

they are part of the engine API

### PR DESCRIPTION
**Pull request by Mickeon**
Closes https://github.com/godotengine/godot-proposals/issues/5104#issue-1331176699.

As brought up in https://github.com/godotengine/godot/issues/54161#issuecomment-1214453639.

If the original name of **PathFollower2D** and **PathFollower3D**'s `offset` is changed, it can be brought back to reunite two properties, as can be argued should've been the case quite some time ago.

And as a bonus, it's now a Vector3 for **PathFollower3D**!

For **PathFollower2D** and :
`h_offset` and `v_offset` -> Vector2 `relative_offset`
**PathFollower3D**
`h_offset` and `v_offset` -> Vector3 `relative_offset` (forward and back included)
image

~Depends on https://github.com/godotengine/godot/pull/64804 to be merged first.~

### CODE REVIEW

**Comment by KoBeWi** [comment]
I think this shouldn't be a Vector2. Vector2 gives an impression that it's an absolute offset, while it is not. It's relative to the curve, so e.g. offset of `Vector2(0, -50)` will be different depending on the orientation.

`h_offset` is the offset parallel to the path.
`v_offset` is the offset perpendicular to the path.
If the current properties don't communicate it properly, we can come up with new names.

**Comment by Mickeon** [comment]
I do agree, to some extent. At the same time, however, it does make Vector math using these properties a little more laborious than it should probably be.

**Comment by Mickeon** [comment]
I would favour a single Vector2/3 so `relative_offset` is a pretty nice. If it's going to be just a rename that is okay and still way better than the current _"h"_ and _"v"_, it's just that I am not sure on what the correct mathematical terms are for each axis is. `offset_parallel`, `offset_perpendicular `and _offset_...?

**Comment by KoBeWi** [comment]
> offset_parallel, offset_perpendicular and offset...?

I mean they would be grouped:
- `offset (group)`
  - `parallel`
  - `perpendicular`
 
This would make the names 100% clear on purpose, but I agree that someone might find the names hard to understand. Especially "perpendicular" is not very often used.

**Comment by Mickeon** [comment]
In the meantime, this PR has been rebased and updated to call it `relative_offset`.

> I mean they would be grouped:

What I did mean is, for PathFollow3D, what would be the name of the third property to go along with the other two?

**Comment by Zireael07** [comment]
+1 for offset_forward and offset_side

**Comment by akien-mga** [comment]
We discussed this in the production team. It's too late for such compat breaking renames for consistency/clarity unless they're motivated by very clear usability issues which many users support. This doesn't seem to the case here, so closing.

**Pull request closed without merging**
