### PR TITLE
Unroll `Basis::operator==`

### PR DESCRIPTION
**Pull request by define-private-public**
Gives a slight performance increase.

### CODE REVIEW

**Comment by define-private-public** [comment]
I used this script to test the changes:
```godot
extends SceneTree


var a := Basis()
var b := Basis()

func doOperation():
    var isSame = a == b
    return isSame

func _init():
    var maxRuns = 10
    var maxMSPerRun = 5000      # milliseconds
    var runs := []
    var avg := 0

    # This would be the best case for old method (the first elements differ)
    a.x.x = 1
    b.x.x = 10

    print('Doing %d runs...' % maxRuns)

    for i in range(maxRuns):
        var start := OS.get_ticks_msec()
        var numOps := 0

        # Do the operations
        while maxMSPerRun > (OS.get_ticks_msec() - start):
            doOperation()
            numOps += 1

        # When done, record the max number of operations
        runs.append(numOps)
        avg += numOps
        print('Run %2d done' % (i + 1))

    avg /= maxRuns

    # Print some info
    print('All Runs:')
    for i in range(maxRuns):
        print('  #%2d: %12d ops' % [i + 1, runs[i]])

    print('Stats:')
    print('  Average # ops: %d    ops' % avg)
    print('  Avg ops/sec:   %.2f ops' % ((1000.0 / maxMSPerRun) * avg))

    quit()
```
Using `target=release_debug`.

First running with no changes to `master`, this was the output:
```
All Runs:
  # 1:      5688613 ops
  # 2:      5687782 ops
  # 3:      5864267 ops
  # 4:      5469710 ops
  # 5:      5087788 ops
  # 6:      5237938 ops
  # 7:      5593419 ops
  # 8:      5640176 ops
  # 9:      5828943 ops
  #10:      5860452 ops
Stats:
  Average # ops: 5595908    ops
  Avg ops/sec:   1119181.60 ops
```

And the changes in the supplied commit:
```
All Runs:
  # 1:      5826571 ops
  # 2:      5833650 ops
  # 3:      5823550 ops
  # 4:      5781122 ops
  # 5:      5679011 ops
  # 6:      5723324 ops
  # 7:      5775280 ops
  # 8:      5772878 ops
  # 9:      5836181 ops
  #10:      5830576 ops
Stats:
  Average # ops: 5788214    ops
  Avg ops/sec:   1157642.80 ops
```

This yielded a +3.4% performance boost.  Very tiny, but is a bit helpful.  If you're wondering why this helps, the previous implementation of the `operator==()` overload would create a bit of branching and jumping assembly instructions (which is kinda slow).  Where as my changes should should not have any (or less).

I've noticed in the godot code that there are a few other places that could reap some benefits of manually unrolling loops like the above.

**Comment by define-private-public** [comment]
I saw that this failed the `clang-format` checks.  I'm not familiar with this tool.  Is there something I can use/run to autofix the formatting?  Or do I need to go and manually do it?

**Comment by asheraryam** [comment]
Might be unrelated but is this operator also used when changing the origin of a transform? 

Setting positions of 3d nodes is surprisingly slow (especially for tweening) so if that could be boosted as well it would be a major gain.

**Comment by aaronfranke** [comment]
@asheraryam I think that's an unrelated issue. Assignment and equality comparison aren't the same.

**Comment by akien-mga** [comment]
> I saw that this failed the `clang-format` checks. I'm not familiar with this tool. Is there something I can use/run to autofix the formatting? Or do I need to go and manually do it?

See http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

**Comment by asheraryam** [comment]
@aaronfranke My bad I had a brain fart and thought I was looking at `Basis=`

**Comment by lawnjelly** [comment]
The kind of questions I'd be asking:
* Is it still faster in release rather than release_debug?
* And is it faster on all platforms?
* And is it actually a bottleneck anywhere?
* Can the compiler not auto-unroll this?
* Maybe unrolling is turned off in release_debug?

Really profiling from gdscript I'm not so sure about, the overheads of calling gdscript will be large (and contain random variation) compared to the actual function itself. You may well find clearer results and more pronounced benefits when profiling from c++, and personally I'd prefer to see things like this rigorously tested on different platforms / configurations, especially when the performance differences are marginal.

Trying to beat the compiler with things like this can be a little controversial, there are a lot of considerations including code clarity (especially as the current policy is to leave auto-vectorization to the compiler, and keeping things simple can in some cases make it easier for the compiler). This is the kind of thing that SIMD might be used for ultimately (comparing all values in 1 op).

_EDIT_
I've now just tested this myself in a little console app with gcc. I prefilled the cache by doing the same run several times.

The results I got showed the old method being slower with no optimization flags (when I compiled with g++ -S on the command line and examined the assembly, the newer version was using SIMD).
_(old) 74500 versus (new) 41300_

However with -O3 flag the older version was faster:
_(old) 12300 versus (new) 17900_

**Comment by define-private-public** [comment]
> Really profiling from gdscript I'm not so sure about, the overheads of calling gdscript will be large (and contain random variation) compared to the actual function itself. You may well find clearer results and more pronounced benefits when profiling from c++, and personally I'd prefer to see things like this rigorously tested on different platforms / configurations, especially when the performance differences are marginal.

I was considering having the test script in C++ instead of writing it in GDScript, but I'm still fairly new to Godot myself.  I'll admit that using the `Timer` isn't probably the best tool to measure performance (e.g. it runs in millseconds and not something like nanoseconds).

I also did consider that the compiler might be doing some loop unrolling itself (since the `for` loop limits are hard constants), but all of the `if` calls could cause branching.

**Comment by lawnjelly** [comment]
The golden rule when optimizing is to make absolutely sure your optimization isn't slower than the original code. In a surprising number of cases it can end up slower, in ways which often leaves me scratching my head! :smile: 

Comparing function timings is something of a black art and it is very easy to make mistakes which will screw up the results. For something like this (comparison of the two self contained functions) there is often no need to compare within godot itself, although profiling within godot is a good idea to identify whether the area is indeed a bottleneck.

Myself I usually find a minimal testbed c++ program within a main() function, much easier to get rid of confounding factors (and for examining the generated assembly). This is often how you would write and compare e.g. SIMD routines with scalar. Take care with the test data, and pay particular attention to whether the cache might be 'warm' on one run versus another which will change the results (as memory access is often the biggest bottleneck).

Do thousands of runs, and either use something like QueryPerformanceCounter / CLOCK_MONOTONIC_RAW to average over these over a period of seconds, or RDTSC as long as you understand multi-core / speedstep issues. I used RDTSC for this test.
https://stackoverflow.com/questions/6030586/calculating-the-speed-of-routines

Also a common gotcha is the compiler is so good at optimizing it will often totally optimize out your test(!), or optimize around repeated data, so you often have to work around this (e.g. by printing a result afterwards).

Also remember the compiler may be inlining and unrolling the test function, so you are not only profiling the function but also the testing code. You can take steps to prevent the test function being inlined on different compilers:
https://stackoverflow.com/questions/1474030/how-can-i-tell-gcc-not-to-inline-a-function

And of course there is the issue that what is faster on one platform / configuration may not be faster on another. The SIMD functionality available may be different, and the CPU characteristics (compare ARM with x86, aligned access, cache etc).

**Comment by define-private-public** [comment]
Okay.  What do you think is the best way to precede forward with this PR?  If it doesn't look like it's giving a perf boost on your end, then maybe it's best to close it.

Does Godot have some built in perf testing framework?

**Comment by lawnjelly** [comment]
Personally I'd close it, but I can't speak for others. These things are normally (eventually!) reviewed by consensus at a PR meeting (and at the moment mostly only bug fixes for 3.2 are being looked at). You could also ask on IRC in #godotengine-devel (see the community section on the godot website).
 
In general with performance optimization there is often a trade off between performance on one side and readability, simplicity and maintainability on the other. Godot policy I would say tends towards the side of readability.

I think in cases like this PR, if one version of a function is clearly significantly faster throughout (in release particularly) and just as accurate, and not illegible then it is more likely to get merged, however the case is much stronger if the function is a proven bottleneck.

There is some built in approximate profiling / debug tools in the debug menu in the godot IDE, however for serious profiling you will want to use an external profiler such as Callgrind, VTune, etc. Also remember the bottlenecks in release can be very different to those in debug.

In general I would say although there are performance boosts to be had in low level functionality (vector, I'm looking at you), a lot of the major boosts to be had are in high level optimization of algorithms and techniques.

For low level optimizations you should be familiar with rigorous testing, which I've tried to give some ideas on earlier here. It's lots of fun so I don't mean to discourage, if one function doesn't work, try others. But just bear in mind any improvements will have to pass peer review.

**Comment by aaronfranke** [comment]
@define-private-public Is this still desired? If so, it needs to be rebased on the latest master branch. If not, you can close this.

**Comment by define-private-public** [comment]
I think it would be best to close it as other pointed out that the optimizations don't seem to be realized.

**Pull request closed without merging**
