### PR TITLE
Fix that the History Dock appears before other Docks in old projects

### LINKED ISSUE #68882: History dock take the first place by default in the control tab bar
### Godot version

beta 5

### System information

Windows 11

### Issue description

I think it's incorrect and distracting, because inspector is more important and should appear first:

image

It seems to be intended to place after the Node tab in the code, but somehow appears first:

https://github.com/godotengine/godot/blob/895428c8058ce97abb02a6a3500e463f72a4f9c9/editor/editor_node.cpp#L7006-L7016

### Steps to reproduce

Run the editor

### Minimal reproduction project

No need

### PR DESCRIPTION
**Pull request by Sauermann**
fix https://github.com/godotengine/godot/issues/68882#issuecomment-1326080366

Newly introduced docks, that are not apparent in old projects should be positioned after the ones in the project-config-file.
This way it seems to be less irritating.

### CODE REVIEW

**Comment by akien-mga** [comment]
It seems a bit wasteful to have to add each dock in reverse order and then move them to the front manually, causing extra notifications of reparenting, etc. But if that's what it takes to solve the issue with unknown docks that may be fine.

**Comment by Sauermann** [comment]
Thanks, I was not aware of this performance problem for repositioning docks.

Could this be a better approach, which doesn't use `dock_slot[i]->move_child(node, 0);`:
``` diff
diff --git a/editor/editor_node.cpp b/editor/editor_node.cpp
index 7c297a39d038..748438b8e912 100644
--- a/editor/editor_node.cpp
+++ b/editor/editor_node.cpp
@@ -4882,6 +4882,7 @@ void EditorNode::_load_docks_from_config(Ref<ConfigFile> p_layout, const String
 		}
 
 		Vector<String> names = String(p_layout->get_value(p_section, "dock_" + itos(i + 1))).split(",");
+		int untouched = dock_slot[i]->get_tab_count();
 
 		for (int j = 0; j < names.size(); j++) {
 			String name = names[j];
@@ -4905,6 +4906,7 @@ void EditorNode::_load_docks_from_config(Ref<ConfigFile> p_layout, const String
 
 			if (atidx == i) {
 				node->move_to_front();
+				untouched--;
 				continue;
 			}
 
@@ -4916,6 +4918,11 @@ void EditorNode::_load_docks_from_config(Ref<ConfigFile> p_layout, const String
 			dock_slot[i]->add_child(node);
 			dock_slot[i]->show();
 		}
+
+		// Tabs mentioned in the layout config should be positioned before any others.
+		for (int j = 0; j < untouched; j++) {
+			dock_slot[i]->get_tab_control(0)->move_to_front();
+		}
 	}
 
 	if (p_layout->has_section_key(p_section, "dock_filesystem_split")) {
```

I also thought about the following method, which would work with any of the approaches but would add complexity:
1. Test, if changes are necessary for a dock by comparing the current positions of Tabs with the intended position.
2. Only adjust positions,  if changes for a dock are necessary.

**Comment by KoBeWi** [comment]
`move_child()` does not cause reparenting.

**Review by KoBeWi — APPROVED** [review]
This will apply to any dock we will add in the future, which means that they will be forced to appear last. I doubt we will add a dock that will appear first (or in the middle) with a default layout, so *probably* not a problem.

**Comment by akien-mga** [comment]
> `move_child()` does not cause reparenting.

Right, I meant `NOTIFICATION_MOVED_IN_PARENT`.

> Thanks, I was not aware of this performance problem for repositioning Docks.

I'm not saying there there would be actual performance problems, just that it adds a few computations which sound like they could be avoidable. But it's likely not a big deal either. If it works, it works :)

**Comment by KoBeWi** [comment]
It would be nice to have a method that adds a child as first child. We can add nodes to literally any other position (thanks to `add_sibling()`).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
