### PR TITLE
Add the ability to play the last-run scene

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a button and shortcut that runs whatever scene you had run last, for convenience. (In the GIF below it runs TestStage, which is open in another tab)

peek 2018-05-10 16-57

-------

It's kind of a weird addition, so let me try to explain a use case. 

I find that I can't really test certain scenes in isolation, such as when a character is affected by gravity:

peek 2018-05-10 16-54

There's no ground to catch it, so it just falls indefinitely. The way to solve this is to instance the character into a test stage scene, and test the character there. This is fine, but what's frustrating is that I either have to switch back to the stage scene tab every time I want to test, or temporarily set the test stage scene as the "main scene"; the latter isn't too bad but it doesn't seem to be intended to be used for that purpose.

I always figured a shortcut just for something like this would be really handy in cases such as this, so I went ahead and implemented one, along with a button for discoverability and clarity.

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't know about this, there are already three different options to run scenes and it's confusing enough, I'm not sure if a fourth option really improves things. It would be good to have some more opinions from users who might/might not see a use case for this option.

**Comment by akien-mga** [comment]
Well I'd like to have some more opinions, maybe it's a wanted feature. Or maybe it will spawn a discussion on how to improve the overall usability of running scenes, as the current three buttons are not the best either IMO.

**Comment by Zireael07** [comment]
Maaaybe merge three buttons into one with a dropdown: "Main, current, latest"?

(Yes, I do see the utility of a "run latest scene")

**Comment by Zylann** [comment]
No... please don't merge the buttons, I don't want one more click for testing scenes :(
Could this at least be doable with a plugin?

**Comment by homer666** [comment]
@mhilbrunner These are good ideas. I prefer the second alternative; discoverability shouldn't be too bad if extra info is added to the tooltip.

I'll look into this soon.........

**Comment by Nallebeorn** [comment]
There is already a _Run custom scene button_, so another option could be to simply make that dialog select the last-run scene by default (I think currently it just chooses the currently opened scene). That would make it two clicks/keypresses instead of one, but that's not too bad.

Personally, I think @mhilbrunner's ideas would be somewhat weird, because 1) No other buttons in Godot work like that afaik, and 2) Which one of the three run buttons should that extra functionality be on? All of them?

**Comment by homer666** [comment]
I couldn't figure out a way to make one button perform two different actions based on a modifier key so I kept putting this off. It's been two months so uhh, I'm just going to close this PR and hope that someone else takes up the mantle.

**Pull request closed without merging**
