### PR TITLE
Add NoiseTexture3D

### LINKED ISSUE #4946: Add NoiseTexture3D
### Describe the project you are working on

Just testing features before release.

### Describe the problem or limitation you are having in your project

Fog volumes could be procedural for nice vfx but lacks an option to do so OOTB (maybe custom material will work but it would be awesome anyway to have built-in). I am talking about using noise in density texture but noise doesn't have 3D output, and isn't even an option to choose (there is a 3D mode in noise but output is projected onto 2D texture).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding support for using noise texture with something like a real 3D mode in a FogVolume's material. This change could greatly increase volume usability and as i stated before, allow to create really nice visual effects easier.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

NoiseTexture with maybe something like "3D" parameter could be used inside FogVolume density texture.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think that it is possible but it is inconvenient.

### Is there a reason why this should be core and not an add-on in the asset library?

i think that it is a basic feature that would be used not only in fog volumes because "NoiseTexture3D" could be used in a variety of shaders

### PR DESCRIPTION
**Pull request by Lasuch69**
Implements NoiseTexture3D resource based on existing NoiseTexture2D implementation scaled to third dimension, and modifies it to support custom depth coordinates when generating noise in 3D.

Supports seamless generation, modulation with gradient, and normalization. Lacks mipmap generation because of a bug in core https://github.com/godotengine/godot/issues/56066

- *Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/4946.*

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on latest `master`), it works for both FogVolume and GPUParticlesAttractorVectorField3D use cases.

Usage notes:

- You may have to increase the fog volume size and volume depth in the advanced Project Settings for noise in fog to be more noticeable. This has a performance impact.
- Remember to use a color ramp with GPUParticlesAttractorVectorField3D, so you can adjust each axis individually. Also increase its strength and increase particles damping, so direction changes are more noticeable on the particles themselves.

**Testing project:** [test_noisetexture3d.zip](https://github.com/godotengine/godot/files/11346129/test_noisetexture3d.zip)

image

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Sosasees** [comment]
sounds like voxel terrain generation will be slightly easier with NoiseTexture3D

related: [my first voxel terrain generation attempt in Godot](https://codeberg.org/sosasees/godot-4-voxel-test/src/commit/7909290b43d3b0468fe14f6fe8c88878d55d7bf9) (4.0 alpha 13)

**Comment by Lasuch69** [comment]
> sounds like voxel terrain generation will be slightly easier with NoiseTexture3D
> 
> related: [my first voxel terrain generation attempt in Godot](https://codeberg.org/sosasees/godot-4-voxel-test/src/commit/7909290b43d3b0468fe14f6fe8c88878d55d7bf9) (4.0 alpha 13)

Using get_noise_3d will be a better option.

**Comment by Sosasees** [comment]
> Using get_noise_3d will be a better option.

i just looked through my voxel project that i mentioned, and i used [Noise.get_noise_3dv()](https://docs.godotengine.org/en/4.0/classes/class_noise.html#class-noise-method-get-noise-3dv) to determine if any coordinate should have a block at startup.

**Pull request merged**
