### PR TITLE
Fix environmental BRDF.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tagcup** [comment]
By the way, from the [source](https://www.unrealengine.com/en-US/blog/physically-based-shading-on-mobile) where the environment BRDF code was probably adapted from

> I made an approximate analytic version based on Dimitar Lazarov's work. The form is similar but adapted to fit our shading model and roughness parameter. 

I'm not sure what this exactly means. Does it fit Godot's shading model? Lazarov did publish his [Mathematica files for his fitting functions](http://blog.selfshadow.com/publications/s2013-shading-course/) however. At some point in the future (and I get more familiar with the models used in Godot's PBR implementation) I'd like to derive a simpler BRDF with assumptions that we actually know.

**Comment by reduz** [comment]
Yep, that's where I adapted it from. In fact, the Unreal paper mentions
they use EnvBRDF on PC, but they actually use the approx too if you check
their source code. In fact, I first adapted the version you submitted in
this PR, but later realized Unreal changed it, so I adapted to their
current version.. this is why differs.

In general, I prefer we stay as close as possible to Unreal for our basing
BRDF simply for the reason that we can use existing tools that export for
it (like Substance Painter) and the result looks similar. It's not like we
have much choice..

**Comment by tagcup** [comment]
Since they never published the derivation or at least what assumption went into it, I don't know what to say...

Another thing, do you remember where the definition of f0 there came from? It's apparently how the specular parameter in Godot (which has been a mystery for me until I saw it) is defined. That definition doesn't make sense to me though, because the relationship between reflectance and albedo is wrong in general (you can see Table 1 in [here](http://blog.selfshadow.com/publications/s2012-shading-course/hoffman/s2012_pbs_physics_math_notes.pdf) for several counter-examples).

**Comment by tagcup** [comment]
Ah, wait, you can make it work if you crank metallic up to 1 and provide F0 as albedo texture. That's probably how things work in Substance Painter etc.

**Comment by reduz** [comment]
Oh, I was comparing and indeed you are right, I screwed up F0, I wonder how I did not realize before

**Comment by tagcup** [comment]
Wait which part? I'm confused? :)

**Comment by tagcup** [comment]
I mean I didn't change the definition of F0 there

**Comment by reduz** [comment]
I meant the naming,  that it was actually specular color. The max() thing was an unreal thing that it was a mistake to adapt.

**Comment by reduz** [comment]
I originally used the BRDF texture, as described in the original unreal paper.. but texture slots are precious, so I found this approximation function later and replaced it to save a slot. It seems the resulting code was not very clean.

**Comment by tagcup** [comment]
I see... It's a bit odd approximation because strictly speaking it changes the meaning of albedo texture depending on the value of metalness

**Comment by tagcup** [comment]
Let me cross reference #11677 here since it's relevant

**Pull request merged**
