### PR TITLE
[3.x] Fix locale fallback selector not appearing in project options.

### PR DESCRIPTION
**Pull request by Ovnuniarchos**
FIXED: Locale fallback selector doesn't appear in project options.

### CODE REVIEW

**Comment by adamscott** [comment]
Is this a 3.x PR? Just to make sure.

**Comment by Ovnuniarchos** [comment]
It is. As far as I know, the problem doesn't happen in 4.

**Comment by akien-mga** [comment]
Fixes up #61878... a stark reminder that 3.6 has been more than 2 years in development /o\

**Comment by akien-mga** [comment]
Rebased to remove the first commit after #88305 was already merged.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
