### PR TITLE
Make VIEW vector available in fragment shader

### PR DESCRIPTION
**Pull request by clayjohn**
This is useful for many effects that can be done in the fragment shader, not just for calculating lighting, as such it should be included in the fragment shader as well.

### CODE REVIEW

**Comment by CptPotato** [comment]
Just out of curiosity: is the vector you provide the camera's "forward"-vector (same for all fragments) or the direction vector from the eye to each fragment?

**Comment by clayjohn** [comment]
@CptPotato It is the direction vector from the eye to each fragment (in view space). It is the exact same as the view vector provided in the light shader.

**Comment by reduz** [comment]
Seems fine, some things missing:
- No changes were done to shader_compiler_gles2/gles3.cpp
- Should be a constant I guess? or is there any value to make it writable?

**Comment by clayjohn** [comment]
I didnt change anything in shader compiler becuase "VIEW" is already set to be renamed "view", so I figured no change was needed. See in [gles3](https://github.com/godotengine/godot/blob/5ff403b3b0a4d19122cebae1329f46444263ae17/drivers/gles3/shader_compiler_gles3.cpp#L882) and in [gles2](https://github.com/godotengine/godot/blob/5ff403b3b0a4d19122cebae1329f46444263ae17/drivers/gles2/shader_compiler_gles2.cpp#L869). If you would like me to move that line up into the fragment shader section I can do that, but I figured it was best left as is. 

I have amended the commit to make "VIEW" a constant. I think that is a good idea. Allowing users to change it will likely lead to more issues than it is worth.

**Comment by akien-mga** [comment]
Right, makes sense. Thanks!

**Pull request merged**
