### PR TITLE
Hide "TileMap" menu properly in CanvasItem view

### PR DESCRIPTION
**Pull request by ghost**
TileMap menu at the right of the Canvas Item toolbar was always visible, and selecting "Fix Invalid Tiles" would lead to a crash if no TileMap was selected. I think it was introduced after the changes in #25510. This might not be the best fix so please review.

### CODE REVIEW

**Comment by guilhermefelipecgs** [comment]
Buttons of `Polygon2D` also changes the alignment.
Captura de tela de 2019-04-23 16-17-01
should be here:
Captura de tela de 2019-04-23 16-19-49

**Comment by guilhermefelipecgs** [comment]
CC @groud

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Note to release maintainers: this is meant to go together with #25510.

**Pull request merged**
