### PR TITLE
Add get_buffered_amount() to WebRTCDataChannel (Godot 3.x)

### PR DESCRIPTION
**Pull request by dsnopek**
Godot 3.x version of PR https://github.com/godotengine/godot/pull/50658

### CODE REVIEW

**Comment by Faless** [comment]
If we want to backport this cleanly to `3.x` (i.e. without breaking GDNative compatibility) we should probably use the `next` field:
https://github.com/godotengine/godot/blob/58ec58d5d0435d52c1a01ffeece35799ba3da533/modules/gdnative/include/net/godot_webrtc.h#L108-L110

And add a new `godot_net_webrtc_peer_connection_ext` struct with the new function, and a `next` pointer.
The plugin will then add the extra struct to the next pointer.

That way the old version of the plugin would still work with the new version of the engine.

**Comment by dsnopek** [comment]
Oh, cool! I didn't realize there was a mechanism in place for this. :-) I'll update this PR and the gdnative one to use that approach.

**Comment by dsnopek** [comment]
PR is now updated to preserve backcompat!

**Review by Faless — APPROVED** [review]
Great job!

**Comment by Faless** [comment]
Thanks!

**Comment by dsnopek** [comment]
Thanks for the review and speedy merge! :-)

I've made a PR to godot-headers that should allow the official GDNative plugin to build:

https://github.com/godotengine/godot-headers/pull/94

**Comment by Faless** [comment]
Yeah, I was actually too hasty :(.
`#define GODOT_NET_WEBRTC_API_MINOR` should have been updated to `4` with this change.

And the `master` one should have been updated to:
`#define GODOT_NET_WEBRTC_API_MAJOR 4`
`#define GODOT_NET_WEBRTC_API_MINOR 0`

**Comment by dsnopek** [comment]
I just created these two PRs to fix those `#define`'s:

- Godot 3.x: https://github.com/godotengine/godot/pull/50706
- Godot 4.x: https://github.com/godotengine/godot/pull/50704

**Pull request merged**
