### PR TITLE
[3.x] LineEdit: Now double click to select a word, and triple click to sele…

### PR DESCRIPTION
**Pull request by kuruk-mm**
…ct all the content

3.2 version of #46524

Related to #46259

### CODE REVIEW

**Comment by asmaloney** [comment]
Any chance this is going to make it into 3.3? It's been sitting here for a while and already been fixed in 4.0.

**Comment by akien-mga** [comment]
No, we're at RC 6 and I don't want to keep adding core changes which might trigger regressions for some users.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
