### PR TITLE
 [3.5] ResourceImporterWAV: Fix support for 64-bit IEEE float

### LINKED ISSUE #61163: ResourceImporterWAV: 64-bit IEEE float is imported, but incorrectly
*Bugsquad edit: See also https://github.com/godotengine/godot/pull/61161.*

### Godot version

3.4.4 and master

### System information

Kubuntu 22.04

### Issue description

Godot's ResourceImporterWAV accepts 64-bit float, but the imported audio is buggy. The expected behavior would be either reject the format by printing an error message or import it correctly.

### Steps to reproduce

- Import a WAV file encoded as 64-bit float
- Play it

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Fixes #61163 for 3.x

Backport of #61168

### CODE REVIEW

**Comment by DeeJayLSP** [comment]
This PR also refactors the code to ensure that, unless someone manages to export some wav at 128-bit IEEE float or beyond, **no unsupported format will be loaded**

**Comment by DeeJayLSP** [comment]
I think this should have been labelled as bug

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
