### PR TITLE
Move self-contained editor in project folder check to export code

### LINKED ISSUE #66408: Cannot start Godot editor in self-contained mode on Windows since #66200 and #66364
### Godot version

v4.0.beta.custom_build.1ac13e562

### System information

Windows 11 22h2

### Issue description

#66200 ~~and #66364~~ broke the CMD workaround to start Godot on Windows 10/11 since the console was disabled a while ago.

Currently, to launch Godot, you need this script:
````
@echo off
godot.windows.opt.tools.x86_64.exe
pause > nul
````

Without it, Godot just closes itself without opening the project manager.

Last working version:
v4.0.beta.custom_build [b3f7796c4]

Error:

ERROR: You are trying to run a self-contained editor at the same location as a project. This is not allowed, since editor files will mix with project files.
   at: Main::setup2 (main\main.cpp:1943)
ERROR: BUG: Unreferenced static string to 0: interface_added
   at: StringName::unref (core\string\string_name.cpp:131)

Screenshot of the error:
image

I have not tested on Windows 10 but i believe it will act the same. Someone else can always confirm.

### Steps to reproduce

Use any Godot version more recent than v4.0.beta.custom_build [b3f7796c4]
Open Godot's executable
Nothing happens
Use a CMD script to launch it:
````
@echo off
godot.windows.opt.tools.x86_64.exe
pause > nul
````
Error

Edit:

You can use my PowerShell script to quickly test the same way i do:

Simple put the code in a .ps1 file next to your Godot.exe or change the first variable to point to the folder where your Godot editor is.

```
$editor_path = $PSScriptRoot

$editor_settings = @"
[gd_resource type="EditorSettings" format=3]

[resource]
filesystem/directories/default_project_path = "$(($editor_path).Replace("\","/"))/Projects"
"@

$start_cmd = @"
@echo off
godot.windows.opt.tools.x86_64.exe
pause > nul
"@

if (Test-Path "$editor_path\Godot*exe" )
{
    New-Item -ItemType "File" -Path "$editor_path\._sc_" -Force
    Get-ChildItem -Directory -Path "$editor_path" -Exclude "Projects" -Force | Remove-Item -Recurse -Force -Confirm:$false
    New-Item -ItemType "Directory" -Path "$editor_path\Projects" -Force
    New-Item -ItemType "Directory" -Path "$editor_path\editor_data" -Force
    New-Item -ItemType "File" -Path "$editor_path\editor_data\editor_settings-4.tres" -Force -Value $editor_settings
    New-Item -ItemType "File" -Path "$editor_path\Start_Godot.cmd" -Force -Value $start_cmd
}
else
{
    Add-Type -AssemblyName "PresentationFramework"
    [System.Windows.MessageBox]::Show("Godot executable not found", "Reset-GodotFolders.ps1", "Ok", "Error")
} 
```

### Minimal reproduction project

No project needed

### PR DESCRIPTION
**Pull request by aaronfranke**
This PR undoes the modifications to #66200 such that the behavior is the same as it was when I first opened the PR.

Should fix #66408.

### CODE REVIEW

**Comment by akien-mga** [comment]
This code path is specific to the command line export option no? So it won't work for exporting from the UI.

And IMO it's bad UX to let users use a workflow that eventually tells them they're not allowed to export (and that they have to clean up their project code to remove editor specific files to fix it).

IMO it should be simpler to actually fix the original issue and make exports work even if the editor is self contained. Wouldn't it be enough to write a `.gdignore` file in `editor_data`?

**Comment by Kemeros** [comment]
I can't comment on what akien-mga said but this PR does indeed fix the issue mentioned in OP.

**Comment by aaronfranke** [comment]
> This code path is specific to the command line export option no? So it won't work for exporting from the UI.

You are correct, but while testing I discovered something strange. Exporting from the UI with an editor running in self-contained mode in the project folder does work. It's only broken when exporting from the command line from self-contained mode in the project folder. I'm not sure why that is the case, it's strange for command line export to not work while the UI export does, but it means that for this PR the error only runs in the specific case it needs to.

> And IMO it's bad UX to let users use a workflow that eventually tells them they're not allowed to export (and that they have to clean up their project code to remove editor specific files to fix it).

I agree, but then I don't know how to solve #66408.

> IMO it should be simpler to actually fix the original issue and make exports work even if the editor is self contained.

I agree, but I don't know how to do this. @Calinou has a proposal here: https://github.com/godotengine/godot-proposals/issues/2474

> Wouldn't it be enough to write a `.gdignore` file in `editor_data`?

I just tested, no.
* Self-contained editor without `.gdignore` in `editor_data/`: Export is broken.
* Self-contained editor with `.gdignore` in `editor_data/`: Export is broken.
* Remove `_sc_` so it's not self-contained: Export is working properly.

**Comment by Kemeros** [comment]
While testing, i noticed that, in self-contained mode, empty folders are created in `C:\Users\%username%\AppData\Roaming\Godot` when you create/open a project in the project manager.

I was under the impression that self contained, meant no overs anywhere outside the editor's folder.

I thought maybe it was due to the recent PRs but previous versions and evebt 3.x act the same.

Should i open an issue or is this intended behavior?

**Comment by Kemeros** [comment]
@aaronfranke @akien-mga 

Please see my last update in #66408

**Comment by aaronfranke** [comment]
@Kemeros I'll close this, at least for now. If it's working as intended, then that's good. It is preferable to show this error more often, for all cases where users try to run self-contained editor in the same folder as a project. Earlier I was very confused seeing your issue, so this PR is basically just me giving up and switching to logic that's even less likely to break things.

**Pull request closed without merging**
