### PR TITLE
Make import preview of blend files visible

### PR DESCRIPTION
**Pull request by Rindbee**
Unlike other scene imports, the import of blend files requires options. Otherwise, the preview may not be visible.

The previous import used empty options, now uses the options read from the configuration (`.import`) file.

Two different projects with the same blend file, the left is the performance in alpha10, the right is the performance in the build with this pr.

Peek 2022-07-03 07-57

Most blend file can be used, the provided blend file has simple animations, however animation previews do not seem to be supported.

[test.blend.zip](https://github.com/godotengine/godot/files/9033869/test.blend.zip)

### CODE REVIEW

**Review by fire — COMMENTED** [review]
I did this in a previous PR that I didn't submit. Thanks for working on this. I think the 15fps should be set to 30 like the other defaults, but opinions wanted.

**Comment by Rindbee** [comment]
> I think the 15fps should be set to 30 like the other defaults.


https://github.com/godotengine/godot/blob/a2459c7d35eeaeea8b1d4fa9ce6c9cbe74f11643/editor/import/resource_importer_scene.cpp#L1616

I found this option, it seems to exist for this purpose and we can use it to avoid hard-coding.

**Comment by fire** [comment]
Looks good.

**Review by fire — APPROVED** [review]
A website review looks good. Will see if I can get to the test cases.

## Resolved issues

1. fps is now either 30 or the defined setting.
2. Api change is consistent across the preview import.

**Comment by fire** [comment]
If you can think of a minimal project that can demonstrate the pr, that'll help. It is not a blocker, but I'd like a test case for peace of mind.

**Comment by Rindbee** [comment]
I provide a gif to see the changes before and after this pr.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
