### PR TITLE
Patch9Sprite Node (70% finished)

### PR DESCRIPTION
**Pull request by MarianoGnu**
This PR is not ocmplete, please do not merge yet. I have it open so everyone can follow the development and make contributions.

Roadmap:
- [x] Create a new Node class as a copy of Sprite.
- [x] Remove unused properties (centered, frames, and region).
- [x] Add Margin and Patch9Policy properties.
- [x] Implement Drawing in all 5 Patch Policies.
- [x] Add a Size property, since using scale looks like a bad way to handle this
- [x] Add icons
- [x] Make sure FlipH, FlipV and negative scales works properly
- [x] Documentation
- [ ] Create EditorPlugins to make development easier (edit size, margins and ~~pivot~~)

### CODE REVIEW

**Comment by n-pigeon** [comment]
Still not sure if removing Centered param is good idea ^^'

**Comment by MarianoGnu** [comment]
why on earth does travis not find the PatchPolicy enum? :/

**Comment by vnen** [comment]
@MarianoGnu IME it's less troublesome to use just `PATCH_NONE` instead of the qualified `PatchPolicy::PATCH_NONE`. Or maybe make it more qualified: `Patch9Sprite::PatchPolicy::PATCH_NONE`.

**Comment by MarianoGnu** [comment]
Okay tests passed now, thx.

**Comment by MarianoGnu** [comment]
Icon

**Comment by MarianoGnu** [comment]
@akien-mga  The node is ready now, only missing stuff is EditorPlugins and documentation, if you wish to merge this now i can get some feedback while working on the rest.

**Comment by MarianoGnu** [comment]
Documentation

**Comment by akien-mga** [comment]
@MarianoGnu Once you're happy with your PR, could you have a look at maybe rebasing to squash some of the commits together? I leave it up to you to see how many commits make the most sense to see how the stuff is implemented :)

**Comment by akien-mga** [comment]
Ping.

**Comment by akien-mga** [comment]
Pretty ping?

**Comment by MarianoGnu** [comment]
i'm sorry, i have been out of home last days and this computer is not setled for development yet 
:disappointed:

**Pull request closed without merging**
