### PR TITLE
Added game module compilation argument

### PR DESCRIPTION
**Pull request by AndreaCatania**
This is the integration of this feature proposal https://github.com/godotengine/godot-proposals/issues/565 

I've already integrated it to see if it could be integrated in a clean way before propose it.

_To keep things in order, please discuss here only technical things and improvements of this code, for any other thing please use the feature proposal page._

### CODE REVIEW

**Comment by Xrayez** [comment]
Does this implementation work with both absolute *and* relative paths supplied to `game_module` argument? I wasn't sure whether Scons could do that, I assumed that everything needs a relative path.

**Comment by Xrayez** [comment]
I just tested this PR, works flawlessly for me.

If you plug in some existing C++ module, the only changes you need to do is defining:
```cpp
void preregister_types();
void register_types();
void unregister_types();
```
And remove module-specific methods like `register_your_specific_module_types()` and family. 🙂

Do you think it would be possible to infer module name from `game_module` path to avoid this?

I'm still not sure whether this is intended to work as a module or as a general-purpose C++ package, so to speak, see my comment at: https://github.com/godotengine/godot-proposals/issues/565#issuecomment-596139878.

**Comment by AndreaCatania** [comment]
> Do you think it would be possible to infer module name from game_module path to avoid this?

This could be possible, but my initial idea were this:
> A general-purpose C++ package, so to speak

Were you can plug anything you want, if you want how you desire.

**Comment by AndreaCatania** [comment]
I'm closing this if favour of this: https://github.com/godotengine/godot/pull/36922

**Pull request closed without merging**
