### PR TITLE
Add a default POINT_SIZE

### LINKED ISSUE #34213: PRIMITIVE_POINTS not visible in HTML5 export (3.1.2 and 3.2beta3)
**Godot version:**
Problem observed in both 3.1.2 and 3.2-beta3(official) **HTML5 exports**, GLES2

**OS/device including version:**
Tested using Chrome, Firefox and MSEdge (HTML5 export from Windows 10)

**Issue description:**
PRIMITIVE_POINTS are not visible in HTML5 export in Godot versions tested (3.1.2 and 3.2-beta3), but are visible in editor runs and Windows 10 exports (all GLES2).

My project uses Mesh.PRIMITIVE_POINTS in an ArrayMesh to display asteroids. Here is what it is supposed to look like. (Yes, I know there are a heck of a lot of points! But the problem is the same if I reduce the number of asteroids to just a few hundred.)
I Voyager asteroids

**Steps to reproduce:**
In any project using PRIMITIVE_POINTS, export to HTML5.

**Minimal reproduction project:**
~This is not a minimal project, but you can download "Planetarium" under Godot Projects on the [I, Voyager Download page](https://ivoyager.dev/download/). Run the project and click "All Asteroids" in the panel on the lower right. Sorry, this will take a while to download & import due to image assets. Please let me know if a smaller project is needed for testing.~ EDIT: That's a terrible MRP. Here's a real one: [test_primitive_points.zip](https://github.com/godotengine/godot/files/3946976/test_primitive_points.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/34213

This was a funny one. I came up with the solution in ten minutes. And then spent two hours wondering why it wasnt working until I realized I was using the beta3 export templates instead of my own custom ones... 🤦‍♂

### CODE REVIEW

**Comment by capnm** [comment]
Can not reproduce with Firefox on Linux.
Setting the POINT_SIZE still works, so the PR seems to be OK.

**Comment by YeldhamDev** [comment]
> I came up with the solution in ten minutes. And then spent two hours wondering why it wasnt working

We all have been there...

**Comment by capnm** [comment]
The exporter should print at least a warning that the sha between the custom templates and the editor doesn't match, would probably save countless hours of development…

**Comment by Calinou** [comment]
@capnm This information isn't available without running the export template binary, so I'm not sure if that's possible. However, we can print such a message when starting the exported binary.

**Comment by capnm** [comment]
It should be easy to made it available. E.g. we do
`git rev-parse HEAD > bin/build.sha`
and include that file in the template zip.

**Comment by Calinou** [comment]
@capnm This would be difficult to get working for people who build their own "bespoke" export templates. Most people would likely forget to copy over the generated file in the same directory as the custom template binary.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
