### PR TITLE
Fix `Skeleton2D.{_set|_get}` always returning true

### LINKED ISSUE #95117: Skeleton2d node seems to know everything
### Tested versions

Reproducible in 4.2 through 4.3-rc2

### System information

Godot v4.3.rc2 - Windows 10.0.19045 - Vulkan (Forward+)

### Issue description

```
func _ready():
	var sk=Skeleton2D.new()
	print('everything' in sk)
	print('balabala' in sk)
```
result: true true

### Steps to reproduce

run the code above

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by kleonc**
Fixes #95117.

Follow-up to #84060.
(@AThousandShips this was simply overlooked? :thinking:)

(not sure what `topic` this should be labelled as)

### CODE REVIEW

**Comment by AThousandShips** [comment]
Mentioned them in https://github.com/godotengine/godot/pull/84054 but left them because I wasn't sure of the exact correct cases and didn't get any feedback on either PR for the correct approach so didn't touch them

**Comment by AThousandShips** [comment]
While we're here I feel the `path.begins_with` is suspicious, it should probably just match against the exact string and might be useful to just use `SNAME` if it's common enough

**Comment by KoBeWi** [comment]
Yeah, looking at the `_get_property_list()`, the `modification_stack` should use exact match with SNAME.

Skeleton 3D has a similar wrong return (it actually works correctly, but the code is awkward).

**Comment by kleonc** [comment]
There's the same problem in Bone2D (same file/author):
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/scene/2d/skeleton_2d.cpp#L41-L99

So for exact properties it can be changed to `p_path == SNAME("prop_name")`. What about editor settings check like `path.begins_with("editor_settings/show_bone_gizmo")`? :thinking:



> Skeleton 3D has a similar wrong return (it actually works correctly, but the code is awkward).

I don't see a "wrong return" there. Unless you mean that it doesn't end with `return false`. It's indeed structured differently but overall looks fine to me.
The checks for `animate_physical_bones` look questionable though, also in case `path.begins_with("animate_physical_bones")` returns `true` then `_get`/`_set` would still return `false`.
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/scene/3d/skeleton_3d.cpp#L71-L82
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/scene/3d/skeleton_3d.cpp#L141-L152

**Comment by KoBeWi** [comment]
> What about editor settings check like path.begins_with("editor_settings/show_bone_gizmo")?

If they check full name, `begins_with()` make no sense. The `_set()`/`_get()` argument is StringName, so using SNAME avoids conversion. It's fine without SNAME too though, for things that aren't accessed often.

> I don't see a "wrong return" there. Unless you mean that it doesn't end with return false.

Yes, it's an unreachable code too. The else should be replaced with proper return.

**Comment by kleonc** [comment]
> Yes, it's an unreachable code too. The else should be replaced with proper return.

I don't see any unreachable code in there so still not sure what you mean. :upside_down_face:

Anyway, I've pushed mentioned changes.

**Comment by KoBeWi** [comment]
I meant the `return` at the end of the method. The code will return at the last `else` at most, so the return below is unreachable.
https://github.com/godotengine/godot/blob/3978628c6cc1227250fc6ed45c8d854d24c30c30/scene/3d/skeleton_3d.cpp#L134-L139

**Comment by AThousandShips** [comment]
> so the return below is unreachable.

Not unreachable, it the other if statements don't return so they join in that

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
