### PR TITLE
Make dialogs exclusive as they should be

### PR DESCRIPTION
**Pull request by Geequlim**

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Not sure if this doesn't break the editor in Project Settings and Editor Settings screens, since they spawn some subdialogs...

**Comment by Geequlim** [comment]
@bojidar-bg I have tested about that like open EditorFileDialog when select custom font.

**Comment by AlexHolly** [comment]
I like it how it currently is. 
It's a feature you don't have to use. Are there any downsides?

**Comment by akien-mga** [comment]
What issue does the patch solve though? The settings popup worked fine so far as non-exclusive.

**Comment by Geequlim** [comment]
As discussed in #7900 
> I might check on that anyway when I implement resizable setting dialogs and storing their positions and sizes. Imagine you want to resize the border and miss it by a few pixels - changes are gone because the window got closed.
> Result is, you trash Godot, kill a kitten and swear to never go to church again.

**Comment by neikeq** [comment]
Wouldn't it be better to increase the weigth of the resize borders? (not visually, just to display the resize cursor)
I like popup dialog being non-exclusive.

**Comment by Geequlim** [comment]
I don't think ConfirmDialog should be closed when user didn't make a choice we provide.

**Comment by neikeq** [comment]
I agree about ConfirmDialog.

**Comment by reduz** [comment]
I'm against implementing this for several different reasons:

1) Godot dialogs are all non-destructive, it's impossible that you lose
work by accidentally closing a dialog.
2) ConfirmationDialog is a generic base class, there are hundreds of
windows that use it as base and inherit it
3) We never had complaints about this in years, so if it's not broken for
most users, I see no reason to fix it.


On Fri, Apr 7, 2017 at 8:25 PM, Ignacio Etcheverry <notifications@github.com

**Comment by Geequlim** [comment]
In my opinion a  `ConfirmDialog` wants user to make a choice or cancel the choice action by provided close button. So it shouldn't be closed by click out of the dialog.
For dialogs to notice something to users which don't require a choice should be a instance of `AcceptDialog`. This kind of dialogs allows to be closed by clicking outside of the dialog.

@reduz We never complaint about this because the dialogs didn't support resize before. The editor settings dialog which is an instance of `ConfirmDialog` with resize supported. It is hard to be resize without closed by click out of it's content.

**Comment by akien-mga** [comment]
> ConfirmationDialog is a generic base class, there are hundreds of
windows that use it as base and inherit it

Actually it's inherited only by EditorFileDialog and FileDialog: http://docs.godotengine.org/en/latest/classes/class_confirmationdialog.html
But indeed those are pretty core components.
I'm not against making them exclusive, though the main question for me is: what happens when a dialog needs a confirmation (accept/cancel) and you discard it by clicking outside the window? Does it auto-accept or auto-cancel?

**Comment by akien-mga** [comment]
Regarding making ProjectSettings and EditorSettingsDialog exclusive, why not. Personally I don't have any issue with them not being exclusive, and AFAIR I do use the feature that I can discard them by clicking outside the dialog when I'm finished making changes.

So maybe for those two it could be implemented as an editor setting, so that one can pick the preferred behaviour.

For ConfirmationDialog, it's a core API change, so it needs a general consensus about the expected default behaviour.

**Comment by reduz** [comment]
I honestly don't see this as an improvement, and don't think it's wrong that dialogs go away by just clicking away. In no place you lose your work or anything due to this.

**Comment by akien-mga** [comment]
No consensus reached, so let's close it for now.

**Pull request closed without merging**
