### PR TITLE
Add animation preview functionality and button to SceneImportSettings dialog

### LINKED ISSUE #6718: Added playback control to animations in the Advanced Import Settings preview
### Describe the project you are working on

A project with many characters and animations, some of which were not properly named by the animator

### Describe the problem or limitation you are having in your project

I'd like to be able to see animations before importing them

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add a small button in the scene viewport to play/pause to the currently selected animation

https://user-images.githubusercontent.com/29764541/232794353-d5ba590b-9366-440a-abc2-bf21a0a0f9c3.mp4

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Advanced Import Settings literally just instances the imported model in the 3D preview/space, so the AnimationPlayer node is just there to be played/paused

### If this enhancement will not be used often, can it be worked around with a few lines of script?

implementation is just adding a button connected to a function that plays/pauses each animation

### Is there a reason why this should be core and not an add-on in the asset library?

I don't think we can implement this on an add-on

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
Added a button to quickly preview animations in the 3D Preview Viewport

On branch add_animation_playback_in_3d_resource_importer
Changes to be committed:
modified: editor/import/scene_import_settings.cpp
modified: editor/import/scene_import_settings.h

- *Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/6718.*

### CODE REVIEW

**Comment by fire** [comment]
Hi, do you know thing this cherry-pickable to 4.0?

Also some errors in the cicd.

[diff.patch](https://github.com/godotengine/godot/files/11304846/diff.patch)

**Comment by jeronimo-schreyer** [comment]
sorry, getting used to the commit workflow. I'm fixing those right now.

The changes are not a big deal, I'll test it in 4.0

**Comment by clayjohn** [comment]
Related https://github.com/godotengine/godot/pull/76367

**Comment by TokageItLab** [comment]
FW from #76367:

I compared #76367 and #76381, both have good and not good points.

#76367 has a seek bar. It is good that you can check the playback position with it. However, the negative is that the loop option is not linked to the import option for the preview. Since users may complain after importing that it is not in the same state as the preview, they should be linked.

image

#76381 does not have a seek bar, but it is preferable that the loop option for preview be linked to the import option.
However, I recommend #76367 for animation because #76367 is more valuable for QOL since it has a seek bar.

BTW, the light settings for preview in #76381 are useful. So it is better to omit the animation feature and brush up #76381 for the preview environment option.

image

**Comment by fire** [comment]
@TokageItLab prefers https://github.com/godotengine/godot/pull/76367 because it has better ux but has some wrong implementations

**Comment by jeronimo-schreyer** [comment]
closing then. If anything, I can help with the implementations

**Pull request closed without merging**
