### PR TITLE
Expose ConeShape from bullet

### PR DESCRIPTION
**Pull request by issork**
Exposed ConeShape from Bullet, as it was once requested in #2138 and #17252.

### CODE REVIEW

**Comment by clayjohn** [comment]
This likely needs a proposal to go along with it. These sorts of PRs are great (thank you!), but it is very unclear whether other users need this. The two PRs you linked are both closed and reading them briefly it looks like they were closed due to lack of demand. 

So could you please open up an issue on https://github.com/godotengine/godot-proposals (note the rules in the README) so that we can gauge interest in this?

**Comment by MennoMax** [comment]
Thanks, I just did that.

Regarding the failed checks; what would be the best way to let them rerun? Push an empty commit or close and reopen the PR? Travis seems to have run into an error and AppVeyor suffered from another issue akien recently opened a PR for.

**Comment by clayjohn** [comment]
Force push nothing. That way you don't add another commit.

**Review by AndreaCatania — APPROVED** [review]
Good job! Thanks for the contribution.

**Comment by akien-mga** [comment]
Will need a rebase eventually to be merged.

But before merging, it also needs to be discussed with @reduz to see how to handle this concern: https://github.com/godotengine/godot/issues/2138#issuecomment-168417544

We did implement CylinderShape as a Bullet-only, but it might be problematic soon when @reduz improved the GodotPhysics3D engine and aims to bring it to par with the Bullet features we use. We need to reassess whether implementing Bullet-only features is future proof.

**Comment by akien-mga** [comment]
I think this is unlikely to be merged as the plans for Godot 4.0 is to make the GodotPhysics engine the default one, and as such adding more Bullet-specific options is likely not the right path. @pouleyKetchoupp recently implemented CylinderShape in GodotPhysics to match Bullet, but ConeShape would also need to be implemented before we can expose Bullet's.

**Comment by pouleyKetchoupp** [comment]
Agreed, adding support for cone shape is welcome but this PR can't be merged as it is.

The Bullet physics server is broken on master at the moment, and the plan is to move it into a gdnative plugin instead. It's probably a matter of weeks before it happens, so the Bullet specific changes from this PR will most likely go into this plugin directly.

Godot Physics needs support for cone as well, and as a first step it can be implemented by just generating a convex polyhedron internally. It will just not roll very smoothly. Proper cone support is a bit more involved but it's possible in the future.

Once all of this is done and tested, cone support could be backported to 3.2 as well (including Bullet physics server changes).

**Comment by mhilbrunner** [comment]
Thanks for your work on this, but as discussed this is currently unlikely to be merged as due to the above - still may be useful for an eventual plugin/extension or if the direction is changed.

**Pull request closed without merging**
