### PR TITLE
SCons: `ruff` SConstruct/SCsub fixes

### PR DESCRIPTION
**Pull request by Repiteo**
Now that `ruff` is properly merged as our linter/formatter of choice, it's now appropriate to fix the previously ignored warnings for SConstruct/SCsub files: `E402` & `F821`. As indicated by this PR changing **177** files, this wasn't exactly suitable for that initial PR. Despite the amount of files changed, the majority of changes were assigning some variation of this to the top of every SCsub:
```python
from typing import TYPE_CHECKING

from SCons.Script.SConscript import SConsEnvironment

if TYPE_CHECKING:
    env = SConsEnvironment()
    Import = SConsEnvironment.Import
```
Remaining changes were ensuring imports at the top level (where applicable) & changing most "native" SCons functions into explicit class calls via `env` to make them typed. With these changes in place, it's now feasible for a followup PR to make the SConstruct/SCsub files support `mypy` checks (currently only applied to `.py` files), as the major typing ambiguities will have been dealt with.

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm not sure solving these warnings actually improves the quality of our code. It's a lot of boilerplate to workaround the design of SCons.

**Comment by adamscott** [comment]
I suggest a lighter way, but as powerful.

We can import variables in python. How about we do this?
```python
# /typed_python.py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from SCons.Script.SConscript import SConsEnvironment
    from SCons.Script import ARGUMENTS, EnsurePythonVersion, EnsureSConsVersion, GetBuildFailures
    from SCons.Variables import BoolVariable, EnumVariable, Variables

    env = SConsEnvironment()
    Import = SConsEnvironment.Import
```

Then, in any SCsub file, we can do:
```
# /platforms/web/SCsub
from typed_scons import *

# ... rest of the SCsub file
```

image

**Comment by Repiteo** [comment]
That's similar to another PR I've setup previously, #86213, but ruff doesn't love the syntax:
24-06-11 14-15-19 Code
…Though, now that I think about it, these star-import warnings could always be excluded for `SConstruct`/`SCsub` files specifically. It'd mean suppressing warnings still, but this time for good reason as they'll be setup with intent. Will play around with this later, albeit most likely in another PR as this one is already pretty shaken up beyond the hints.

**Comment by adamscott** [comment]
Yeah, I kinda forgot about installing ruff on VSCode. Sorry!

**Comment by Repiteo** [comment]
Superseded by #93058

**Pull request closed without merging**
