### PR TITLE
[3.x] SailfishOS port

### LINKED ISSUE #26018: SailfishOS port
I am using sources from two pull request 
 - https://github.com/godotengine/godot/pull/16470
 - https://github.com/godotengine/godot/pull/9435  

and build Godot engine for SaiflsihOS. 

**What is done**
- export from [Godot Editor](https://github.com/savegame/godot/releases/tag/v3.2.1-stable-sailfish) with SaiflishSDK to native for sailfish RPM package.
- touch screen input
- dynamic orientation events 
- dynamic orientation change
- normal application life cycle 
- sound initialization
- joypad (just compile already exists **libudev** implementation of LinuxJoypad, works nice )
 
**What is not done**
- gyroscope/accelerometer events
- disable screen blanking when application is open ( just need use some dbus interfaces from mce)

Sources are here: 
https://github.com/savegame/godot/tree/3.2_sailfish_sdl2

PR [here](https://github.com/godotengine/godot/pull/38642)

### PR DESCRIPTION
**Pull request by savegame**
About [SailfishOS](https://sailfishos.org)

This PR add to Godot Engine 3.2 support for exporting Godot GLES2 games to SailfishOS rpm file with SailfishSDK.  

Fix ~~#26018~~ [#914](https://github.com/godotengine/godot-proposals/issues/914) issue for 3.2 branch

I use this pull request for my work: 
- #16470
- #9435

#### **What is done**:
- add ability export game from Godot Editor to native SailfishOS RPM file
- touch screen input
- dynamic orientation events 
- dynamic orientation change ( just some magic in canvas shader and gles renderer )  
- normal application life cycle  
- sound initialization, pause - when application is "minimized'
- joypad (just compile already exists **libudev** implementation of LinuxJoypad, works nice )

Whan need do next:  
- show native keyboard (maliit keyboard) when use text edit UI items 
- device vibration
- accelerometer, gyroscope events

#### **Known bugs**:
- SailfishOS platform dont support GLES3 for now

#### **Build Instructions**:

For build this branch on SailfishOS, need SailfishSDK (or Sailfish Docker image), all build commands are looks like:
```bash
export SAILFISH_SDK=$HOME/SailfishOS/
export SSH_MER_KEY=${SAILFISH_SDK}/vmshare/ssh/private_keys/engine/mersdk
export MERSSH_PORT=2222
export MERSSH="ssh  -o "IdentitiesOnly=yes" -i \"$SSH_MER_KEY\" -p $MERSSH_PORT"
# GODOT_PATH - path to godot sources inside MerSDK (SailfishSDK) build machine
export GODOT_PATH=/home/mersdk/share/Projects/Sailfish/godot
# version of taget Sailfish platform, should be more than or equal to 3.1.0.12 (becuse of SDL2 version)
export MER_TARGET_VERSION=3.2.1.20
# architecture can be i486 or armv7hl
export MER_TARGET_ARCH=armv7hl
export GODOT_ARCH=`[ "$MER_TARGET_ARCH" == "armv7hl" ] && echo arm || echo x86`
export MER_TARGET=SailfishOS-${MER_TARGET_VERSION}-${MER_TARGET_ARCH}
#first install dependencies
$MERSSH "sb2 -t ${MER_TARGET} -m sdk-install -R zypper in -y SDL2-devel libaudioresource-devel pulseaudio-devel openssl-devel wayland-devel libpng-devel libxkbcommon-devel libudev-devel scons  gcc-c++"
#than build 
$MERSSH "cd $GODOT_PATH && sb2 -t ${MER_TARGET}  scons -j 8 platform=sailfish target=release arch=${GODOT_ARCH} bits=32"
# then optimize binary size if it release (arm or x86)
$MERSSH "cd $GODOT_PATH && sb2 -t ${MER_TARGET}  strip godot.sailfish.opt.${GODOT_ARCH}"
```
latest SailfishSDK can use docker images for build engine.

[Latest build release (Editor and export temaplates based on Godot 3.2.1 stable) ](https://github.com/savegame/godot/releases/tag/v3.2.1-stable-sailfish)
With this export templates already exists few demos and games:
- [Whoosh! in the Dungeon](https://openrepos.net/content/sashikknox/whoosh-dungeon) - Summary it's just another dungeon crawler!
- [Godot Joypad Demo](https://openrepos.net/content/sashikknox/godot-joypad) for testing gamepads support on SailfishOS (little bit modified for touchscreens)
- [Godot Materials Demo](https://openrepos.net/content/sashikknox/godot-materials-tester) - little bit modified for touchscreens
- [Circle Jump](https://openrepos.net/content/nesnomis/circle-jump) - Circle Jump is a small (but kind of addictive) game.

Why 3.2, not 4 branch? 
Because 4 branch is in deep development, and this Sailfish support already work. But port it to 4.0 branch not possible now, because i need GLES2 implementation in 4.0 branch and more time for understanding how to port it to Sailfish. 
But 3.2 already work on SailfishOS, it stable on it, some people already use this export templates for their project.

### CODE REVIEW

**Comment by savegame** [comment]
Hm, build errors ( not **override** on virtual functions ) , but i use **GDCLASS** Godot's standart macro... what i need to do?

**Comment by aaronfranke** [comment]
> But port it to 4.0 branch not possible now, because i need GLES2

New features need to be added to the master branch first before they can be backported, so this PR will have to wait until master gets GLES2 back and this PR can be made for master.

**Comment by fire** [comment]
@akien-mga I am making a case to close this due to the lack of widespread adoption of SailfishOS and the fact that the pr has not been attended to since the start of 2021.

**Comment by lawnjelly** [comment]
As @fire says this is unlikely to be supported in 3.7 / LTS as it doesn't make a lot of sense for the roadmap at this point, and as it says in the proposal it would require a maintainer.

**Comment by savegame** [comment]
I do not has much time to maintenance port for AuroraOS/SailfishOS in Godot's main repo, that is why i was made this port in my own fork of Godot. And i maintenance it there ) 
Last release here:
https://github.com/savegame/godot/releases/tag/3.6-auroraos-1

**Pull request closed without merging**
