### PR TITLE
FBX Importer - CI build test WIP

### PR DESCRIPTION
**Pull request by RevoluPowered**
**Feature set**
- FBX Maya supported
- UV coordinates
- Meshes
- Animations from Maya without requiring Blender middle import step.
- FBX Pivots
- FBX Inherit type (Segment Scale Compensation, Shear handling)

**Features we require for upstreaming:**
- Blend shapes
- Implement fixes to skinning bugs found
- blender skinning support must be re-added
- Look into locator support
- Material slot creation for Blender, Maya, and 3DS max using strings we added to ASSIMP.
- A 4.0 branch
- CM to M / file scale handling

Future possibilities:
- support for 3DS Max FBX files.

### CODE REVIEW

**Comment by fire** [comment]
There's a cicd error, but take your time. Travis is failing.

**Comment by fire** [comment]
```
*** The following differences were found between the code to commit and the clang-format rules:

--- a/modules/fbx_importer/editor_scene_importer_fbx.cpp	2020-05-26 17:31:30.023496893 +0000

+++ b/modules/fbx_importer/editor_scene_importer_fbx.cpp	2020-05-26 17:31:37.179272927 +0000

@@ -1738,7 +1738,7 @@

 

 			Ref<PivotTransform> fbx_transform;

 			fbx_transform.instance();

-			if(parent_node.is_valid()) {

+			if (parent_node.is_valid()) {

 				print_verbose("parent name: " + parent_node->node_name);

 			}

 			fbx_transform->set_parent(parent_transform);

--- a/modules/fbx_importer/tools/import_utils.cpp	2020-05-26 17:31:30.023496893 +0000

+++ b/modules/fbx_importer/tools/import_utils.cpp	2020-05-26 17:31:37.260757689 +0000

@@ -48,8 +48,7 @@

 	}

 

 	print_verbose("[euler->quat] rotation input: " + rotation);

-	if(rotation.x == 0 && rotation.y == 0 && rotation.z == 0)

-	{

+	if (rotation.x == 0 && rotation.y == 0 && rotation.z == 0) {

 		return Quat();

 	}

 

@@ -58,7 +57,6 @@

 	const Quat y = Quat(Vector3(0, Math::deg2rad(rotation.y), 0));

 	const Quat z = Quat(Vector3(0, 0, Math::deg2rad(rotation.z)));

 

-

 	Quat result;

 	// So we can theoretically convert calls

 	switch (mode) {

*** Aborting, please fix your commit(s) with 'git commit --amend' or 'git rebase -i <hash>'
```

**Comment by fire** [comment]
Here's a list of existing on the tracker that relate to fbx import.

https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+fbx+import+label%3Abug

**Comment by fire** [comment]
Still https://travis-ci.org/github/godotengine/godot/builds/691475299 failing cicd.

**Comment by RevoluPowered** [comment]
Yeah sorry been sorting out personal life more than the travis issues, will be sorting these out probably today if I get some spare time.

**Pull request closed without merging**
