### PR TITLE
Fix missing method qualifiers in script doc

### LINKED ISSUE #63097: Qualifiers missed in GDScript documentation
### Godot version

4.0.alpha12

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

Qualifiers missed in GDScript documentation for static functions.

### Steps to reproduce

Define a static function in GDScript and the static qualifier not shown in document.

### Minimal reproduction project

```GDScript
static func fn():
    return
```

### PR DESCRIPTION
**Pull request by Xwdit**
Fix #63097

### CODE REVIEW

**Review by vnen — APPROVED** [review]
Looks good to me

**Comment by akien-mga** [comment]
Maybe you could also refactor `DocTools` (where I assume you found this code originally) to use this method?

https://github.com/godotengine/godot/blob/master/editor/doc_tools.cpp#L500-L547

It's nearly identical, the only difference seems to be:

```
#ifdef DEBUG_METHODS_ENABLED
					DocData::return_doc_from_retinfo(method, E.return_val);
#endif
```
(which is code in a pretty weird way with this `i == -1` hack, it could just be outside the loop)

**Comment by akien-mga** [comment]
Pushed an update to refactor duplicated code as suggested.

**Comment by akien-mga** [comment]
> would need checking if that replacement should be done in `DocData`'s method too, or done after the fact.

Confirmed that it needs to be kept, e.g. if adding a default value to a Dictionary argument (which we don't seem to do currently):
```diff
diff --git a/doc/classes/HTTPClient.xml b/doc/classes/HTTPClient.xml
index 5a9d12d01b..2a958b9f58 100644
--- a/doc/classes/HTTPClient.xml
+++ b/doc/classes/HTTPClient.xml
@@ -96,7 +96,10 @@
                </method>
                <method name="query_string_from_dict">
                        <return type="String" />
-                       <argument index="0" name="fields" type="Dictionary" />
+                       <argument index="0" name="fields" type="Dictionary" default="{
+&quot;answer&quot;: 42,
+&quot;hello&quot;: &quot;world&quot;
+}" />
                        <description>
                                Generates a GET/POST application/x-www-form-urlencoded style query string from a provided dictionary, e.g.:
                                [codeblocks]
```

With the replacement:
```diff
diff --git a/doc/classes/HTTPClient.xml b/doc/classes/HTTPClient.xml
index 5a9d12d01b..10e203e796 100644
--- a/doc/classes/HTTPClient.xml
+++ b/doc/classes/HTTPClient.xml
@@ -96,7 +96,7 @@
                </method>
                <method name="query_string_from_dict">
                        <return type="String" />
-                       <argument index="0" name="fields" type="Dictionary" />
+                       <argument index="0" name="fields" type="Dictionary" default="{&quot;answer&quot;: 42,&quot;hello&quot;: &quot;world&quot;}" />
                        <description>
                                Generates a GET/POST application/x-www-form-urlencoded style query string from a provided dictionary, e.g.:
                                [codeblocks]
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
