### PR TITLE
[WIP] Added tools support for the javascript platform

### PR DESCRIPTION
**Pull request by marcelofg55**
WIP don't merge!

### CODE REVIEW

**Comment by eska014** [comment]
One issue I see in this current state is using the URL query for `main()` arguments. Godot games can be embedded on any HTML page even without iframes. The query may be unrelated to Godot, causing unexpected arguments to be read.

I'd rather change `new Engine().start()` to accept arguments, then rename the current implementation to something like `startGame('game.pck')` (and maybe some more helpers like `startTools('pj/project.godot')`, `startScript('main_script.gd')`, `startTest('shaderlang')`)

I'm also not convinced of implementing `OS::execute` for the HTML5 platform, since this function is bound. I prefer we use an `#ifdef` for the call in the project manager

**Comment by marcelofg55** [comment]
@eska014 I was planning to disable reading the GET arguments if the tools are not built on godot, that should solve the issue, right?

And sure, I could change the OS::execute to and #ifdef on project manager, sounds good to me.

@reduz I'm having some issues with the `ResourceSaver::save` line on `project_manager.cpp:317`, I could trace the problem to the `RasterizerStorageGLES3::texture_get_data` function, `GLES_OVER_GL` is not defined for the javascript platform so the function returns an empty Image and `ResourceSaver::save` fails due to that. Do you think we could implemented `RasterizerStorageGLES3::texture_get_data` using `glReadPixels` when `GLES_OVER_GL` is not defined?

**Comment by SuperGameMaker** [comment]
Hey i'm working on something similar: https://www.godot.online/ I'm working on exporting but I think I have it pretty close to have godot working at 100%, will put a pull request as soon as I fix some minor issues

**Comment by eska014** [comment]
>I was planning to disable reading the GET arguments if the tools are not built on godot, that should solve the issue, right?

I don't think so, we can't make any assumptions about where the editor or Godot games are hosted. The query arguments could be anything

**Comment by marcelofg55** [comment]
@SuperGameMaker Cool, I just tested your link, but running the project doesn't works, does it?
Did you solve the mouse double click issue too?

**Comment by SuperGameMaker** [comment]
@marcelofg55 Yes I got double click working, running the project dosen't work, I have a fix on that and I will try to update it today

**Pull request closed without merging**
