### PR TITLE
Fix shadowing for global constants in shaders

### PR DESCRIPTION
**Pull request by Chaosus**
This should fix (partially, only for constants): https://github.com/godotengine/godot/issues/74817

The following code would successfully been compiled:

```
shader_type spatial;

const float foo = 0.0;

void change(inout float t) {
	t = t + 1.0;
}

void bar(float _foo) { 
	float foo = 0.0; 
	foo = 0.0;
	change(foo);
}     

void bar2(float foo) {
	foo = 0.0;
	change(foo);
}
```

Test project: [Test.zip](https://github.com/godotengine/godot/files/12428163/Test.zip)

### CODE REVIEW

**Comment by hmans** [comment]
Thank you for tackling this. How difficult would it be to also fix this for uniforms, function names and other symbols in the global scope?

**Comment by Chaosus** [comment]
> How difficult would it be to also fix this for uniforms, function names and other symbols in the global scope?

As far as I remember it's not so easy, otherwise I would do it in this PR at the same time.

**Comment by clayjohn** [comment]
The code looks fine, but we should get input from others on whether this behaviour is desired. While GLSL allows you to shadow variables inside a nested scope, that doesn't mean that GDShaders should support it. Shadowing global scope variables can easily lead to bugs (especially if users shadow them in vertex() or fragment()) as there is no way to escape the shadowing once the variable has become shadowed in that scope. 

To me, it seems useful for the code editor to raise an error when the user shadows a global constant. 

Note that global constants are different from function pointers. Functions are used differently from variables, so the confusion for end users doesn't arise as easily.

**Comment by hmans** [comment]
> Shadowing global scope variables can easily lead to bugs (especially if users shadow them in vertex() or fragment()) as there is no way to escape the shadowing once the variable has become shadowed in that scope.

Do you have an example for a bug like the one you're describing here?

`vertex()` and `fragment()` are top-level functions typically under the control of the same author(s) who also control the names of uniforms and other global-scope constants in the shader.

Not being able to shadow these names within functions makes authoring shader include libraries meant for distribution much more difficult because _their_ author has no way of knowing what globals their variable names may clash with. Literally every variable in these, from function arguments to local variables defined within them, now needs to be prefixed with `something_that_hopefully_never_clashes_with_userland_code_*` or similar. Am I missing something obvious?

**Comment by Chaosus** [comment]
Ok, I better close it, because the discussion to accept it seems stuck, and the consensus here is to implement it for everything and not only for the constants or for nothing.

**Pull request closed without merging**
