### PR TITLE
Lol

### PR DESCRIPTION
**Pull request by trashguy**
Forks are hard

### CODE REVIEW

**Comment by trashguy** [comment]
Don't mind me

**Comment by fire** [comment]
Pay no attention, nothing happened.

**Comment by Bioblaze** [comment]
OMFG lol these are the developers of Redot everyone

**Slow Clap**

**Comment by Starkium** [comment]
did they commit to godot? XD

**Comment by SkogiB** [comment]
> did they commit to godot? XD

you see nothing!

**Pull request closed without merging**
