### PR TITLE
[4.2] Add support for reading text resource format 4

### PR DESCRIPTION
**Pull request by timothyqiu**
Follow up to #90889.

Basically #89186 without touching `VariantWriter::write`.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
You'll need to rebase to fix CI after recent macOS runner changes.

**Comment by AThousandShips** [comment]
The CI fixes aren't in 4.2 yet it needs the cherry picks

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
