### PR TITLE
Adds keywords to autocomplete predictions.

### PR DESCRIPTION
**Pull request by zombietype**
Adds keywords to the autocomplete prediction in GDScript so
they are not replaced by irrelevant predictions.

Fixes: #5972

### CODE REVIEW

**Comment by Calinou** [comment]
`preload` is listed but not `load` – is this intended?

**Comment by vnen** [comment]
Why don't you use `GDScriptLanguage::get_singleton()->get_reserved_words()`? Having a separate list like this is prone to get out of sync.

**Comment by KidRigger** [comment]
Should I also remove the GDScriptFunctions::get_func_name from the code (Since will be taken care of by reserved words (Otherwise they are redundantly added into the set) It won't cause problems either way.

**Comment by KidRigger** [comment]
Leaving it in won't cause any difference, but would make it more clear. So I'm leaving it in.

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Comment by breakmt** [comment]
fdg

**Comment by KidRigger** [comment]
I'm on it.

**Pull request merged**
