### PR TITLE
Optimize GodotConvexPolygonShape3D::get_support

### PR DESCRIPTION
**Pull request by Malcolmnixon**
This pull request optimizes the array dereferencing and looping of the following containers in GodotConvexPolygonShape3D::get_support:
 - mesh.vertices: ```LocalVector<Vector3>```
 - extreme_vertices: ```LocalVector<int>```
 - vertex_neighbors: ```LocalVector<LocalVector<int>>```

Specifically the changes involve switching from the ```LocalVector::operator[]``` with built-in bounds-checking to a regular C pointer-array dereference. This can be performed as the vectors were constructed using the _setup() function and are known to index correctly.

### CODE REVIEW

**Comment by lawnjelly** [comment]
An alternative (which would work for other bottlenecks) might be to remove the `CRASH_BAD_UNSIGNED_INDEX(p_index, count);` calls in `LocalVector` in release builds, for instance changing them to `DEV_ASSERT()`, or wrapping in `#ifdef TOOLS_ENABLED`. Or adding a second set of unchecked accessor functions.

See e.g. #58858 which uses `DEV_ASSERT()` for equivalent functionality.

In most cases these unchecked accessors will be fine, although there are cases where raw pointer can generate better assembly.

**Comment by Malcolmnixon** [comment]
This code is eventually going to need to be SSE vectorized in order to approach the performance of the old Bullet routines.

**Comment by lawnjelly** [comment]
> This code is eventually going to need to be SSE vectorized in order to approach the performance of the old Bullet routines.

That may be true, but that is not really relevant for this PR, we'd tend to defer such things to the PR that needed them, as this is making a lot of assumptions about a future implementation. In the case of SSE it would require more significant changes as Godot is multiplatform (and there have so far been no decisions made on the standards for handling SIMD - frameworks / multiple files / ifdefs etc).

Imo using pointers is fine, but it might be an idea to revisit whether the `LocalVector` accessors need bounds checks in release, or whether we should simply add some non-bounds checked functions (like e.g. `get(index)`) as an alternative for bottleneck code.

**Comment by Malcolmnixon** [comment]
The lack of SIMD examples anywhere else in the Godot code-base made me avoid using it for this.

I'll look into an unchecked accessor, and there's also a PR for range-based iteration https://github.com/godotengine/godot/pull/70773 which should bypass checking for the inner loops, but it's probably not as fast as pure pointer dereferencing.

**Comment by lawnjelly** [comment]
> I'll look into an unchecked accessor, and there's also a PR for range-based iteration #70773 which should bypass checking for the inner loops, but it's probably not as fast as pure pointer dereferencing.

It's ideally something we would discuss at a PR meeting but there haven't been many lately.. also would be good to tag @reduz as he might want to decide on a standard approach (which may well just be using pointers, so your PR may be fine as is).

**Review by lawnjelly — APPROVED** [review]
Approving this, as it looks fine for the pointer approach.

As I say it would have been nice to get some feedback on whether we should remove the release checks in `LocalVector`, but maybe that's for another PR. And I don't think that discussion is necessary to hold this up.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
