### PR TITLE
Check the native base of scripts when resolving icons

### LINKED ISSUE #79979: Extended class shows wrong icon
### Godot version

4.1.1

### System information

Linux Mint, Godot 4.1.1

### Issue description

Hi,

I've extended my own class, which extends "Node2D".
Now, in the create node menu, the icon from the "Node" class is displayed instead of the icon from the extended "Node2d"-class.

Here is a screenshot to show how it looks:
Bildschirmfoto vom 2023-07-28 10-18-12

But after you create the node, the correct Icon is picked:

Bildschirmfoto vom 2023-07-28 10-20-07

Regards
abgenullt

### Steps to reproduce

Extend from a custom class and check the icon in the menu.

### Minimal reproduction project

[InheritTest.zip](https://github.com/godotengine/godot/files/12192148/InheritTest.zip)

### PR DESCRIPTION
**Pull request by YuriSizov**
See https://github.com/godotengine/godot/pull/80184#issuecomment-1704673358. This is not a regression from https://github.com/godotengine/godot/pull/80184, though. The issue was present before as well, but it manifested differently:

image

The issue is that we only check the direct base class of script classes. This means that if your class extends another script class, we won't be able to find the fallback icon for it correctly. Before https://github.com/godotengine/godot/pull/80184 we would simply fall back onto the `Node` or `Object`, or whatever else was supplied as the common fallback icon. With https://github.com/godotengine/godot/pull/80184 the common fallback defaults to an empty string, so we end up with no icon whatsoever.

The fix is to find the first native base class instead of the direct base class and use its icon.

image

Fixes https://github.com/godotengine/godot/issues/79979.

-----

PS. This PR touches code around the same lines as https://github.com/godotengine/godot/pull/81130, so it may lead to conflicts when one of them is merged. While this one is small and simple, I'd prefer https://github.com/godotengine/godot/pull/81130 to be merged first, if we're okay with it.

### CODE REVIEW

**Comment by akien-mga** [comment]
> PS. This PR touches code around the same lines as #81130, so it may lead to conflicts when one of them is merged. While this one is small and simple, I'd prefer #81130 to be merged first, if we're okay with it.

This PR seems cherry-pickable, while rebasing on top of #81130 would make it incompatible with 4.1. So it may make more sense to merge the other way around?

**Comment by YuriSizov** [comment]
That's a good reason, yeah. It's just going to be slightly more annoying to rebase a large 3-commit PR, but I can manage :)

**Comment by akien-mga** [comment]
Alright, then I guess the order of merge isn't as important. I'm not sure the bug is problematic enough in 4.1 to warrant going out of our way for a custom backport.

**Comment by YuriSizov** [comment]
> I guess it depends whether we do plan to cherry-pick #79203 or not.

I'd say yes, it's a point of a lot of confusion. Making a custom PR would be an easy option as well, it will take less time than our conversation here has taken so far 😛

**Comment by YuriSizov** [comment]
I need to rebase https://github.com/godotengine/godot/pull/81130 anyway now, so this is safe to merge once approved.

**Review by akien-mga — APPROVED** [review]
Looks fine to me, though I'm not an area expert.

**Review by KoBeWi — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks for reviews!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
