### PR TITLE
Core: Remove unused PoolAllocator

### PR DESCRIPTION
**Pull request by akien-mga**
It was used in `3.x` for `PoolVector` types, but it's not used anymore since 4.0.

If some downstream forks or C++ modules were making use of it, they can still copy the file in their fork/module to keep using it.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
LGTM, internal and unused

**Comment by alvinhochun** [comment]
https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/core_types.html still refers to PoolVector.

**Comment by AThousandShips** [comment]
This is about `PoolAllocator` not `PoolVector`, that type doesn't exist any longer, that page needs a significant update but it's unrelated to this PR

**Review by adamscott — APPROVED** [review]
The builds and tests passed. Looks good to me.

**Pull request merged**
