### PR TITLE
Added descriptions for all Particles2D.xml methods

### PR DESCRIPTION
**Pull request by WorkShoft**
I rewrote my contribution to follow the guidelines and the suggestions made in the former PR.

### CODE REVIEW

**Comment by djrm** [comment]
@WorkShoft thanks for contributing, i have some advice that might help you with this and future contributions. It seems that in most cases you are just stating the same thing as the method name, in some cases this is absolutely fine, since the method name is very clear already, but in others you need to formulate and explain things in more detail, dont forget that the help will be viewed by users that might not know the terminology, having said that, it is also ok to not document the methods you dont know or dont understand, someone more experienced will fill them out.

an example is this
> A material which will be validated and processed.

this description does not tell me much about what that is, you could for example point to other documentation that explain how materials work, or try to explaining it there.

**Comment by WorkShoft** [comment]
Thanks for the insight. Some of my mistakes are probably obvious to some of you since this is the first time I collaborate on a big project like this.

Some of the methods seem to have no use at the moment and some other methods are obscure, like the one you cited. For cases like those I looked through the code with grep and checked briefly what they did, which as you say isn't enough if you can't explain thoroughly what they do.

**Comment by Noshyaar** [comment]
Contents LGTM. Please fix all spaces to tabs and remove trailing newlines, then `git commit --amend`.

**Comment by cbscribe** [comment]
I am currently working on Particles and ParticlesMaterial, so go ahead and merge (after the formatting fixes) and I'll amend with the content that overlaps.

**Comment by cbscribe** [comment]
@WorkShoft I just submitted #11820 - A bunch of the Particles members are the same or similar to Particles2D. If you're still working on your PR, we should standardize them. Please take whatever looks helpful (I know you were stuck on the process_material description), or let me know and I can finish it up.

**Comment by WorkShoft** [comment]
Really busy with work and school lately, please feel free to do any further changes that you consider necessary here.

**Comment by cbscribe** [comment]
Closed and combined with #11820

**Pull request closed without merging**
