### PR TITLE
New editor icons for class members

### PR DESCRIPTION
**Pull request by nobuyukinyuu**
Hi!  First time attempting to PR, so please forgive me if I've made any mistakes.  

This is a small attempt to improve the icons for a few class members.  Right now, I don't believe they're commonly used in the editor, but seeing how they were used in #29744 I felt that it was a bit difficult to tell the difference between common members and thought that could be improved.

image

This PR updates 3 icons:  `MemberProperty`, `MemberMethod`, and `MemberConstant`.  The largest change was to icon_member_method;  in #29744 its proximity to the autocomplete combined with the flat color made it confusing to distinguish the icon from the func name on a glance.  This was changed to a glyph similar to the purple cube seen in other IDEs (eg: vs, vscode) with the florin incorporated into the design using the original 88% gray color.  This not only improves readability, but helps distinguish it as a member from other class members.

The other icons retain a single character but replace the dot with three bars as an "index card" or text mnemonic.  This mnemonic is typically widely understood to mean a property or value member as seen in various icon libraries (including the default shell library on Windows and several 1-bit glyph libraries on the web).

If #29744 is accepted, these icons will further improve autocomplete readability.  Below are the icons at slightly higher resolution for reference.

image

### CODE REVIEW

**Comment by Calinou** [comment]
These icons don't look very readable on a loDPI display. Maybe try using thicker lines?

**Comment by YeldhamDev** [comment]
I personally think the original icons are clearer.

**Comment by akien-mga** [comment]
I also tend to prefer the existing icons that we have, which are also consistent with all other type icons which were designed in the same style by @djrm.

I guess the icons your propose might feel familiar for VSCode users, but as I'm not, they don't really speak to me.

**Comment by nobuyukinyuu** [comment]
Hello,

To respond to the readability of these icons, they are meant to be read as logograms.  The letters themselves are a secondary mnemonic, as I believe making them too prominent combined with their usage of Color(224,224,224) is what makes them appear confusing when placed directly next to other text.  For me, `MemberProperty` is actually the biggest offender for this, and the original reason I tried working on an alternative!  

The glyph confusion issue could theoretically be alleviated by changing their colors, or finding an entirely non-character-based mnemonic.  Despite the arguably similar lack of readability in the intrinsic type icons, I consider them much better than the class member icons merely due to the fact they're not colored the same as default text.  I kept the characters in my alterations as a compromise, but really I think the underlying problem is that the class member icons read too much like editor text when placed next to, well, editor text, and *not* that the text in the icons isn't easy enough to read.

I can change the latin characters in `MemberConstant` and `MemberProperties` to more closely the geometric style used by the type icons.  However, are there any other suggestions to make a merge more likely?  Specifically, I'd like to know if switching some of these icons entirely to logograms would be more useful.

**Comment by nobuyukinyuu** [comment]
@Calinou 

> One way to improve this would be to increase spacing between the icon and the text.
> 
> PS: SVGs committed to this repository should be optimized and minified. You can use [svgcleaner](https://github.com/RazrFalcon/svgcleaner) for this purpose. Make sure to keep the original SVG around, so that it can be committed to [godot-design](https://github.com/godotengine/godot-design) if this PR is merged.

Thank you, I wasn't aware that there was a repo specifically related to the design assets, nor that there was a requirement to minify SVGs.  As for the icon spacing, that is probably a matter to bring up to @Geequlim in his PR #29744.  Should I re-submit this PR to godot-design ?

**Comment by groud** [comment]
I don't mind about the "property" and "constant" icons, but the new "member function" icon does not make any sense.

**Comment by nobuyukinyuu** [comment]
I think you're right, the mnemonic seems to be too vs-specific, so I may redesign it to be more consistent with the other two, though perhaps still trying to keep a color to visually distinguish it.  While I'm at it, I might as well look into restoring the geometric font djrm used in all member icons, with an eye towards bolding the 'f' or turning it into a florin so it doesn't read as much as editor text.

**Comment by LikeLakers2** [comment]
While I understand you're working on changing the icons, I feel I might as well comment on the current ones that you've suggested: Personally, I'm not exactly a fan of them, as they aren't especially readable for me (from a distance, they all look sorta like boxes of the same color, which makes it hard to tell which is which). You could *maybe* solve that by giving them colors, or perhaps by giving the text colors (with either one, perhaps programmatically from the current editor theme), but as it stands I don't think the current icons are that good.

That said, I'm curious to see what your next iteration of the icons will be.

**Comment by akien-mga** [comment]
There's no consensus so far, and personally I still think that these new icons would be out of place among Godot's otherwise relatively coherent icon set, and they don't seem to increase readability for non-VS users, so closing for now.

**Pull request closed without merging**
