### PR TITLE
Gradient: improve interpolation?

### PR DESCRIPTION
**Pull request by ghost**
I asked a question on \#godotengine-devel (which nobody answers yet) about this image
[image](https://user-images.githubusercontent.com/26753932/27966753-9cfacf78-636a-11e7-85fd-779b178ffa15.png)

Top: pow(2) -> lerp -> sqrt
Bottom: current version (just lerp)
At least @karroffel thinks the top one blends better. 😛 

I'm not sure if my code will cause any performance issues. I only aim to bring this to core devs' attention.

(I have to admit I just watched [this](https://www.youtube.com/watch?v=LKnqECcg6Gw) and tried to implement it.)

### CODE REVIEW

**Comment by reduz** [comment]
This has to do with gamma correction, and you have functions to fix in
Color if you need (to_linear and to_srgb) which are better than just using
a single pow(). I would also make it optional.

**Comment by MarianoGnu** [comment]
dont get it, linear interpolation is suposed to be linear, even if it's better for the sight if you pretend to use lerp for other reasons this could lead to unexpected results

**Comment by Noshyaar** [comment]
I should have looked before making a PR. Sorry for the misunderstanding. Closing this.

**Comment by reduz** [comment]
@MarianoGnu The problem is that the monitor adjusts all color to gamma space (sRGB), so the interpolations generated by code look wrong.. this might explain it better - https://en.wikipedia.org/wiki/SRGB

**Pull request closed without merging**
