### PR TITLE
CI: Replace Travis iOS build by GitHub Actions

### PR DESCRIPTION
**Pull request by akien-mga**
Last step of the migration from Travis/AppVeyor to GitHub Actions.

### CODE REVIEW

**Comment by akien-mga** [comment]
It seems like we can't build with `werror=yes` on iOS on the `3.2` branch yet, there are a few warnings that still need to be fixed: https://github.com/akien-mga/godot/runs/911741716?check_suite_focus=true
(CC @bruvzg @naithar)

So disabling `werror=yes` for now.

**Comment by naithar** [comment]
Picking some changes made in `master` for `Vulkan` support into `3.2` to fix deprecation and `@property` warnings might be a way to go.
GitHub CI seems to be still picking `werror=yes`.

**Comment by akien-mga** [comment]
>  GitHub CI seems to be still using `werror=yes`.

Yeah it seems to be pretty bad at picking up config changes on force pushes :|

**Comment by MCrafterzz** [comment]
Quite unrelated but: How is the speed of github actions compared to travis and appveyor?

**Comment by akien-mga** [comment]
It depends on the workload, but GitHub Actions starts all pending builds at the same time regardless of their number, while AppVeyor has only 1 concurrent build, and Travis has 5. GitHub Actions also starts its containers faster, and seems to build overall faster (2 cores available instead of 1, much faster cache retrieval speed).

**Pull request merged**
