### PR TITLE
Fix http response and user directory

### PR DESCRIPTION
**Pull request by sanikoyes**
Fix http read response body size mismatch
Fix user directory does not correct created under windows platform.

HTTPClient::read_response_body_chunk -> set result size to received size
DirAccess::make_dir_recursive -> ignore E_CANT_CREATE error

### CODE REVIEW

**Comment by the-mech** [comment]
+20000 

merge 6ee7b01d7f81fb407bed1423513fa824b110ee99 please, that workaround solves my issue #1240

**Comment by akien-mga** [comment]
Is the issue described in this PR still relevant in the current master branch?

**Comment by vnen** [comment]
About the Windows directory creation, the proposed fix is the same as #1512, which was merged (I really don't understand why there's no merge conflict in this). There's still a bug if you try to create in the `user://` path.

**Comment by akien-mga** [comment]
Duplicate of #1512.

**Pull request closed without merging**
