### PR TITLE
Anchor icon fix

### PR DESCRIPTION
**Pull request by SaracenOne**
Fixes the mismatched icons on anchor editor plugin to be the right order (icon for bottom left was bottom right and vice-versa)

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@drjm Ping :)

**Comment by akien-mga** [comment]
Nice catch :)
Could you just revert the changes made to the SVGs, and rename them instead with `git mv`? Right now the SVGs have names that don't match their function.

**Comment by SaracenOne** [comment]
Does that fix it?

**Comment by akien-mga** [comment]
Hehe, that does the trick yeah :)

**Comment by djrm** [comment]
oops

**Pull request merged**
