### PR TITLE
Improvements and fixes for the default theme.

### PR DESCRIPTION
**Pull request by djrm**
Added missing textures, polished some elements, and created a more consistent look

this is how it looks on default
screenshot from 2017-07-15 12-06-00

you can customize it look this way
screenshot from 2017-07-14 23-45-32

or this way
screenshot from 2017-07-15 12-14-17

### CODE REVIEW

**Comment by reduz** [comment]
It looks much cleaner in general, but as mentioned on irc, the borders and
highlighted tabs feel, in my opinion, as a downgrade.. more unnecesary
visual information.

**Comment by reduz** [comment]
here's for comparison with flat.
image

**Comment by Iniquitatis** [comment]
@reduz, flat design is, maybe, a good thing, but don't go too far with it. Tabs, in my humble opinion, need to be highlighted in one way, or another. This way we clearly see, that it is actually _the_ widget.
(No offense intended.)

**Comment by reduz** [comment]
@Iniquitatis tab highlighting is unrelated to flat design. I can't think of any UI that highlights the tabs this way instead of making them part of the panel. It just feels wrong.

**Comment by HummusSamurai** [comment]
Would it be possible to only add a light border to the tabs instead of highlighting all of it?

A simple underline might even do the trick, but this amount of highlight is visually gruesome.

**Comment by toger5** [comment]
Ty soo much for the grid colour change!
I also like the use of more variables in editor theme.
With the tabs + bkrders, i agree that ghey dont really need to be highlighted. Makes everything look more conveluted.

**Comment by akien-mga** [comment]
Overall I like the change, but I'd mostly side with @reduz on those two points:
- the highlighted tab doesn't look that appealing to me, I prefer the current style: 
spectacle f30902 (I've seen it's opt-in now, so good for me)
- the borders don't add much aesthetic value IMO, and for example on the first screenshot with the viewport highlighted, the highlight border + two other levels of border (see on the bottom or the side) is really too much. The current style is much better in this regard IMO: 
spectacle s30902

**Comment by n-pigeon** [comment]
I also agree that tabs highlighting is overkill and looks old.

Overall looks awesome! :D

**Comment by djrm** [comment]
thats why the first screenshot reflects how the theme looks on default settings the rest of the settings are examples with different settings like highlight_tabs, and border size = 0. of course thats up to you to decide which one you like best, but THE DEFAULT is like the first screenshot ONLY.

**Comment by akien-mga** [comment]
I understand, and I don't like the thick borders of the DEFAULT :)

**Comment by djrm** [comment]
@akien-mga do you mean the current default or my proposed default, just to clarify, because if its the later i dont see thick borders at all.

this is my proposed default
image

**Comment by reduz** [comment]
oh, since i read all this on the mail, i did no realize you edited the original post.
last image looks really good to me

**Comment by djrm** [comment]
@reduz yeah, i think thats the problem with editing the PR. well at least everything is now clarified.

**Comment by akien-mga** [comment]
@djrm Well this looks pretty thick to me: 
spectacle zk5121
Compared to the current style which I prefer: spectacle s30902

**Comment by djrm** [comment]
@akien-mga oh you mean that, yeah, well, the only place where that looks bad is in the viewport, in all other case its better, since the editor does not have the correct spacing, in all elements and that makes it look really bad, so i think i should just add a style override for the viewport

**Comment by akien-mga** [comment]
I don't think it looks bad currently, I like the 1px border, more is unnecessary IMO (especially since we already have a lot of space between containers).

**Comment by toger5** [comment]
@djrm I agree that the no border viewport looks better.
For the same reason akien mentioned: the gap between docks and viewport is already a nice border.

**Comment by djrm** [comment]
yeah, i will change that on my next PR, it will look like this, no it has proper borders when needed, so thinks dont look that close to each other.

screenshot from 2017-07-16 12-25-03
screenshot from 2017-07-16 12-25-16
screenshot from 2017-07-16 12-25-33

**Comment by djrm** [comment]
About the 1px "borders | margins", i know some people prefer the no margins options but you have to think about the engine visual consistency and quality vs a <20px space saving or a "better" looking  panels, if you put 1px margins, then the interface looks really cheap (that can be solved by adding proper internal margins) but thats more work and then we will have the same space just in other places, so please think about the quality, i've never seen a decent site or interface that has those issues, and i really sugest that we take that into consideration, so for me is not about a personal visual preference, is about the visual quality of the engine. I've changed most of the request, because they do not interfere with the quality, but rather what most people find more apealing, but in this particular case i think its a really bad idea to change to 1px.

examples:
screenshot from 2017-07-16 21-12-11
vs
screenshot from 2017-07-16 21-20-14


screenshot from 2017-07-16 21-12-23
vs
screenshot from 2017-07-16 21-20-05

screenshot from 2017-07-16 21-13-35
vs
screenshot from 2017-07-16 21-20-24

screenshot from 2017-07-16 21-12-53
vs
screenshot from 2017-07-16 21-20-35

screenshot from 2017-07-16 21-13-22
screenshot from 2017-07-16 21-21-09

**Comment by n-pigeon** [comment]
I also think that current state of editor widgets where they are touching borders looks horrible and cheap.
Adding borders so it is not **that** noticeable is **okeish** temp solution in my opinion. I prefer that for now.

State of spacing in editor must be fixed badly :< I want to help with that, but currently I'm crunching at work. :<

**Comment by toger5** [comment]
I totally see the issue with no border in the visual script editor and many other places. That ui elements are just too close to the edge of the dock and it looks awkward. Especially if they have a border on the left but none on the right.
But that is already all that affects visual quality.
For docks like the inspector no border looks really good and thanks to colour differences it is really obvious what belongs to what. There is less visual distraction because most dominant lines are horizontal and there is no strong vertical line.
You have strong points to add the border to the visual script and script panel. And I love the changes you made and see the necessity.
But for `Scene`, `Filesystem`, `Inspector`, `Node`, `Import` I only see benefits with no borders. (even though those benefits are small):
 - More modern
 - Less visual distraction (no strong vertical elements)
 - No loss in visual quality (when fixing the margin for some of the elements in the top bar.)
 - In the last discussion more ppl argued for no border. -> The active part of the community would be more satisfied.
 - and (although I feel childish mentioning that...) a tiny bit extra space
 - THE ONLY NEGATIVE POINT: we would need to put in a little extra effort to fix search bar, search icons and some button margins in the top sections of those docks.

**Comment by reduz** [comment]
Testing. It looks much better in general, here's some feedback

1) Separators in Menus, as well as H/V Separators. We need them to exist
and be visible, so users know they can use them
2) I honestly think the black outlines against Tree and ItemList don't look
very good. At least after coming from the previous theme, they feel like a
downgrade. disabling them makes it cleaner imo.
3) The bigger margins definitely are better, agreed on that.

[image: Inline image 2]

**Comment by reduz** [comment]
guess attaching image from email did not work, attaching here
image

**Comment by reduz** [comment]
Actually nevermind, when there is content in the boxes, the dark lines help a lot. I take back comment #2.

**Comment by reduz** [comment]
Also, customizing colors from the project settings is not working.. did you test this function?

**Comment by reduz** [comment]
nevermind again, it's working

**Pull request merged**
