### PR TITLE
Ballhead constraints for FABRIK

### PR DESCRIPTION
**Pull request by KaruroChori**
Not to be merged yet, as I have not been able to really test its functionality.

https://github.com/godotengine/godot-proposals/issues/750#issuecomment-1009796131
The author referenced a solution of ballhead constraint on the inverse kinematic model for FABRIK. I just ported its code and integrated it in the GUI of Godot.

Any external evaluation is very welcome.

### CODE REVIEW

**Comment by KaruroChori** [comment]
It seems to be accurate :/. I guess this is what happens working on two things at the same time and being me :smile: .

I'm not really sure how to address this now, I should have generated a different branch since the very beginning also for the other pull request to avoid any interference. 
I am not very accustomed contributing on public repositories, sorry if miss some aspects of the proper workflow.

**Comment by KaruroChori** [comment]
In theory, I solved it.

**Comment by fire** [comment]
The pr currently has some wrong formatting.

Check https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html

**Comment by KaruroChori** [comment]
It seems like the automatic execution of clang_format.sh is trying to change additional files. Some of those changes make sense, like removing trailing spaces, some others do not, like the newline escape sequence for defines. Was that expected behaviour?

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/62003.

**Pull request closed without merging**
