### PR TITLE
More icon updates on theme change

### PR DESCRIPTION
**Pull request by timothyqiu**
* Profiler buttons
* Debugger buttons
* Shader editor menu item
* Resource Preloader editor button

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
@timothyqiu In the end I left out the ScriptEditorDebugger changes for the `3.x` cherry-pick, as they're non trivial. The constructors does theme updates which trigger a crash when it happens before enter tree.

**Comment by timothyqiu** [comment]
@akien-mga Ah, I see... I'll try to debug that and create a dedicated PR.

**Pull request merged**
