### PR TITLE
Move "Dialog Bounds" from the Editor Settings to project's metadata

### LINKED ISSUE #15810: Dialog bounds don't have default values in the Editor Settings
**Godot version:**
1699978

**Issue description:**
Maybe this is by design, but the dialog bounds inside `Interface > Dialogs` don't have default values.

### PR DESCRIPTION
**Pull request by YeldhamDev**
Closes #15810.

### CODE REVIEW

**Comment by akien-mga** [comment]
IMO it would be better to have some editor metadata instead of using project metadata for that, as it's unlikely that you will want to have different bounds in different projects. Since all those refer to editor tools, their dimensions should not be linked to a given project.

There is no such metadata file for the editor yet, but it could probably be added (e.g. `editor_metadata.cfg` next to `editor_settings-3.tres`).

**Comment by YeldhamDev** [comment]
@akien-mga I think it still fits in project's metadata, as with each new project the editor's layout resets to its default, it would make sense for the dialog's position and sizes to follow suit.

**Comment by akien-mga** [comment]
I'm not convinced, but having it in project metadata is still better than in the editor settings, so I'm fine with merging this solution for now :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
