### PR TITLE
Fix the window pos issue in muffin wm

### LINKED ISSUE #79581: Compatibility mode project windows jump up after they appear on screen
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Fedora Linux 38 (Cinnamon) - Vulkan (Compatibility) - Mesa Intel(R) UHD Graphics 630 (CML GT2) () - Intel(R) Core(TM) i5-10505 CPU @ 3.20GHz (12 Threads)

### Issue description

Compatibility mode project's main window and all windows created and shown from code jump up after they appear on screen. There was no such issue in 4.0.3. There is also no such issue in Forward+/Mobile mode.

### Steps to reproduce

1. Create a new project in Compatibility mode
2. Create main scene with any node in it
3. Run the project

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/12069068/Bug.zip)

### PR DESCRIPTION
**Pull request by n0tank3sh**
Potential fixes #79581
Need Testing anybody with cinnamon desktop environment 
@okla

### CODE REVIEW

**Comment by okla** [comment]
@MightiestGoat Sorry, I couldn't build it. If you can build and attach the binary here, I'll test it.

**Comment by MightiestGoat** [comment]
> @MightiestGoat Sorry, I couldn't build it. If you can build and attach the binary here, I'll test it.

how do I share binary with you?

**Comment by Calinou** [comment]
> @MightiestGoat Sorry, I couldn't build it. If you can build and attach the binary here, I'll test it.

See [Testing pull requests](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) in the documentation :slightly_smiling_face:

**Comment by okla** [comment]
@MightiestGoat Unfortunately, this PR doesn't fix the issue

**Comment by MightiestGoat** [comment]
@okla  That's unfortunate. Thanks for trying my pr tho.

**Pull request closed without merging**
