### PR TITLE
Ask confirmation if closing scene was modified (using close [x] tab)

### PR DESCRIPTION
**Pull request by StraToN**
- SWITCHED THE SCENE TAB CLOSE BUTTON DISPLAY POLICY TO "SHOW_ACTIVE_ONLY" !
- Also added a missing break;  statement

### CODE REVIEW

**Comment by jackmakesthings** [comment]
:+1:  --- I don't know the core code well enough to vouch for it, but assuming this works like it appears to, it's an improvement worth having.

**Comment by reduz** [comment]
can you try to make it mergeable again? seems i made it conflict

**Comment by StraToN** [comment]
@reduz should be ok

**Comment by akien-mga** [comment]
@StraToN The last commit looks kind of weird, did you use ```--rebase```? :)

**Comment by StraToN** [comment]
@akien-mga no :$ I made some ugly copy paste from current master editor_node.cpp and paste missing parts from my commit... I'm not very fluent with git commands :/

**Comment by akien-mga** [comment]
Hm, normally you should run ```git pull --rebase```, fix the conflicts and commit the changes that will get integrated directly in your initial commits (since with --rebase your commits are reapplied on top of the HEAD of the master branch).

**Comment by StraToN** [comment]
@reduz @akien-mga Ok, corrected the commit nicely now with rebase. Thanks to @akien-mga

**Comment by akien-mga** [comment]
You edited the log of the first commit though ;)
To fix it you can run ```git rebase -i HEAD~2``` and replace 'pick' by 'r' on the line of the commit you want to reword.

**Comment by StraToN** [comment]
@akien-mga Is that good now ?

**Comment by akien-mga** [comment]
@StraToN Not really :-/ you added a new merge branch commit and c4f1fc4 still has as only description "correcting conflict for rebase" instead of the previous description of the implemented feature (pas taper ! :P)

**Comment by akien-mga** [comment]
For the reference, the same enhancement was proposed in #2825 based on a cleaner branch.

**Pull request closed without merging**
