### PR TITLE
Fix crash on RigidBody _direct_state_changed (3.x)

### PR DESCRIPTION
**Pull request by rafallus**
Fixes: #46003 for the 3.x branch

### CODE REVIEW

**Comment by rafallus** [comment]
The input is now checked in all classes with `_direct_state_changed` method (including 2D nodes). As @madmiraal pointed out in https://github.com/godotengine/godot/pull/47485#pullrequestreview-623944939 there are other classes than RidigBody using this method

**Review by pouleyKetchoupp — APPROVED** [review]
This looks like the proper fix for 3.x since we can't use a callable to avoid exposing the method on that branch.

**Comment by akien-mga** [comment]
How much of an optimization are we trading off here by removing the "trust it" release path for RigidBodies?

I believe this could also work with just the `ERR_FAIL_COND` added, but maybe the cost of the cast done (so far) in debug is negligible?

**Comment by pouleyKetchoupp** [comment]
@akien-mga I can't find a measurable difference. It looks like it's negligible compared to propagating the transform, and in general the bottleneck will be somewhere else in cases with lots of rigid bodies in the scene, so it should be fine.

It makes sense to be on the safe side, since the function is still exposed to scripts on 3.x.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
