### PR TITLE
Fix gridmap cursor showing the wrong mesh

### LINKED ISSUE #59742: GridMap selection preview isn't cleared when another GridMap node is selected
### Godot version

v4.0.alpha.custom_build [b0df742cb]

### System information

Windows 11, Vulkan Clustered, Nvidia 1650

### Issue description

The `GridMap` selection preview is retained even after selecting another `GridMap` node.

https://user-images.githubusercontent.com/18116695/161081561-834a4a67-5c48-4881-b54f-993afafe8543.mp4

### Steps to reproduce

- Open `main.tscn`
- Select the forest `GridMap` node and place some tiles
- Select the desert `GridMap` node and notice the selection preview hasn't changed

### Minimal reproduction project

[gridmap_bug.zip](https://github.com/godotengine/godot/files/8390496/gridmap_bug.zip)
Assets from the [Kaykit mini game variety pack](https://kaylousberg.itch.io/kay-kit-mini-game-variety-pack)

### PR DESCRIPTION
**Pull request by dzil123**
Fixes #59742

When there are two gridmaps in a scene with their own meshlibraries, switching between them will not update the cursor (mesh preview) when moving the mouse over the grid without placing the tile. Actually placing the tile will place the correct mesh, so it's only the cursor with the incorrect rendering.

This PR fixes this issue by updating the cursor every time a gridmap node is selected.

Here is a screencap demonstrating this problem with the sample project:

https://user-images.githubusercontent.com/5725958/155947155-80fe16a4-9452-49b9-a0b6-38f4e7172a8b.mp4

When the red gridmap is selected, the cursor becomes the red mesh. Switching to the blue gridmap incorrectly keeps the red mesh as the cursor.

Sample project: [godot-gridmap-test.zip](https://github.com/godotengine/godot/files/8151612/godot-gridmap-test.zip)

The sample project is for v3.4.3 but this same behavior is in v4.0-alpha3.

### CODE REVIEW

**Review by fazil47 — COMMENTED** [review]
This file has been moved to `modules/gridmap/editor/grid_map_editor.plugin.cpp` .

**Comment by fazil47** [comment]
Seems to work.

https://user-images.githubusercontent.com/18116695/161382022-f6dd7aea-914b-4812-bc50-2e219b2bbc15.mp4

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
