### PR TITLE
Enhanced 'open' menu

### PR DESCRIPTION
**Pull request by sersoong**
Increase the capability to open the scene in batch.
test

### CODE REVIEW

**Comment by groud** [comment]
We don't need two entries. The "open" menu item should instead do what "open selection" does. :)

**Comment by sersoong** [comment]
Oh,I see.
I will change this.

**Comment by groud** [comment]
You could have kept this PR open and ammend your commit too :)

**Comment by sersoong** [comment]
I reopen it when it ready.

**Comment by groud** [comment]
Ok :)

**Pull request closed without merging**
