### PR TITLE
Do not strip spaces at the end of file names of dropped files

### LINKED ISSUE #67689: Window "files_dropped" signal strips spaces from the end of folder names
### Godot version

4.0.beta2.official

### System information

Ubuntu 20.04.5

### Issue description

When folders are dropped onto the window, godot strips spaces from the end of the folder name (making it unable to find the folder if you then pass the path to `DirAccess`, for example).

### Steps to reproduce

- Create a folder with a space at the end of it's name
- Create a node with a script that attaches a function to the `files_dropped` signal of the root window, for example:
```
extends Control

func _ready():
	get_tree().get_root().files_dropped.connect(
		func(files): 
			for file in files:
				print("Received file \"%s\"" % file)
	)
```
- Run the scene and drop the folder on the window
- Observe missing space before end quotation mark

### Minimal reproduction project

[FolderDropBug.zip](https://github.com/godotengine/godot/files/9834148/FolderDropBug.zip)

- Run Project
- Drag 'example ' folder onto running window

### PR DESCRIPTION
**Pull request by Sauermann**
Fix file name stripping on linuxbsd.

resolve #67689

Updated 2022-11-03: Fix merge conflict

### CODE REVIEW

**Comment by Setadokalo** [comment]
Is this the right solution? As far as I'm aware, file names can end with any ascii character other than NUL. Is the `strip_edges` even necessary? Testing on my machine, it looks like `.trim_suffix("\r")` is all that's needed and should allow (almost?) any weird file name.

**Comment by Sauermann** [comment]
@Setadokalo thanks for the insight.
Some kind of trimming is necessary. When dropping multiple files, they are represented in a combined string, where filenames are separated by newlines. So the newlines have to be removed.
On my Linux the separation is `"\r\n"`. This implementation also handles the case, that the separation is `"\n"`.

There might be edge-cases where the filename contains `"\n"` (this is an allowed character), but name files like that, would surely cause also other problems ;-)

**Comment by volokh0x** [comment]
Returned data from `XGetWindowProperty` in `DisplayServerX11::_read_property` has `\r\n` characters as a newline, which is awkward to do on a Linux system. If it isn't function call misuse, then the returned string of file names should be split by `\r\n` sequence

**Comment by Setadokalo** [comment]
> There might be edge-cases where the filename contains `"\n"` (this is an allowed character), but name files like that, would surely cause also other problems ;-)
With the new method of splitting around `\r\n`, this problem goes away entirely, afaict - file names are URI encoded at the point in code we're splitting them, so the file name itself won't contain any actual carriage returns or newlines.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
