### PR TITLE
Adds open property for retrieve faces to ConcavePolygonShape

### PR DESCRIPTION
**Pull request by Chaosus**
I found its lack of this property, so get_faces/set_faces looks improperly. "data" is not open for the editor. I leave it untouched cuz I think it may break the existed projects if I've removes it.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
This will cause shape data to be saved twice, once as `data` and once as `faces`, no?

You should either give the new "faces" property `PROPERTY_USAGE_EDITOR | NETWORK` (default without storage), or make the old `data` property have just `INTERNAL` (alternatively, move it to a `set()` method)

**Comment by Chaosus** [comment]
Ok, I've changed it to Network. Don't know if it is the right fix.

**Comment by akien-mga** [comment]
It's weird to have two properties for the same methods, with different usage flags which basically amount to it being a "normal" bound property.

Maybe `data` should simply be exposed as a normal property?

**Comment by Chaosus** [comment]
Eh.. it should but for 4.0 (probably) it should be renamed to "faces"

**Comment by Chaosus** [comment]
I think it should be closed for now..

**Pull request closed without merging**
