### PR TITLE
Avoid pow in Burley diffuse.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by reduz** [comment]
Oh did you figure out what was going on with it? I was lost..

**Comment by tagcup** [comment]
Ah, no, this's just a tiny optimization. 

If you're referring to the glitches that appear with Burley, since it's already exactly the same as Burley's diffusion model, I'm guessing the problem is somewhere else?

**Comment by reduz** [comment]
It is, but I just don't understand why the roughness works the way it does on it.

**Comment by tagcup** [comment]
Totally apart from the bug you mentioned: I only recently started looking into the PBR literature and models and there appears to be a room for improvements. Have you seen [Burley's updated diffuse model](http://blog.selfshadow.com/publications/s2015-shading-course/#course_content)?

**Comment by tagcup** [comment]
Quoting his notes, this seems to be his reasoning:

> If we had used FD90 = 0, this would have been the standard Lambertian diffuse with smooth-surface
Fresnel factors (using the Schlick Fresnel approximation here), but as discussed in our 2012 report this produces an unnaturally dark grazing response.  So instead of going to 0 at grazing angles, i.e.  when the light or view direction is 90 degrees from the surface normal, we limit the edge darkening to 0.5, and increase gain at retro-reflection by up to 2.5 times for maximally rough surfaces.  The cos2θd factor smoothly isolates this gain to grazing retro-reflection.  Though ad hoc, this shape and relationship to roughness were chosen based on observations of measured data.

**Comment by tagcup** [comment]
Also for reference, [this](https://git.blender.org/gitweb/gitweb.cgi/blender.git/blob_plain/2de5e14f53e9a439ae87deb16f816ec71445c1ba:/source/blender/gpu/shaders/gpu_shader_material.glsl) is Blender's implementation (see node_bsdf_principled function, which includes sheen)

**Comment by reduz** [comment]
oh, cool then.. I missed that. I thought it was kinda odd. I am used to
generate retro reflections with ambient light, so that feels kinda odd

**Comment by tagcup** [comment]
That won't capture the angular dependence at the intermediate value though, which seems to be his point.

I was planning to submit a few PRs for the PBR after @akien-mga and TheOnlyBouncer decided to viciously attack me on IRC on baseless assumptions (I'm used to @akien-mga, although he was at a new low today) so I'd prefer discussing those privately with you if that sounds fine.

**Comment by reduz** [comment]
Jeez guys, if we have issues with this size of community, it will get worse
later on. Just be more flexible, disagreeing is not the end of the world..

**Comment by groud** [comment]
> I was planning to submit a few PRs for the PBR after @akien-mga and TheOnlyBouncer decided to viciously attack me on IRC on baseless assumptions (I'm used to @akien-mga, although he was at a new low today) so I'd prefer discussing those privately with you if that sounds fine.

Seriously ? Nobody "attacked" you, neither TheOnlyBouncer nor @akien-mga. 
You seriously have a problem... Stop thinking everybody is against you ! This is not because they don't agree with you that they hate you or whatsoever !

Damn, that's crazy you have to make any argument a personal thing...

**Comment by tagcup** [comment]
> Seriously ? Nobody "attacked" you, neither TheOnlyBouncer nor @akien-mga.
You seriously have a problem... Stop thinking everybody is against you ! This is not because they don't agree with you that they hate you or whatsoever !

> Damn, that's crazy you have to make any argument a personal thing...

> You seriously have a problem... Stop thinking everybody is against you !

Really. Tell me straight to my face that you just didn't attack me, that "you seriously have a problem" isn't ad hominem, that this behavior of yours wasn't against me, that this is also not personal.

Read it carefully, I didn't say everyone, I said two people. Now it's apparently three.

**Comment by groud** [comment]
Ok, I give up. You're right, we're attacking you, I hope you'll be able to get over it.
Locking this topic, it's not productive.

**Comment by reduz** [comment]
No one here has any reason to attack another. Please understand we are from different cultures, backgrounds  and parts of the world and it's not always easy to convey intentions and points of view.

I already have a lot of difficulty with this myself as we in Buenos Aires are a lot less polite compared to many other places (like the US). This maked a heated discussion pretty ambiguous to some people.

I will unlock because I feel this is unfair to Tagcup

**Comment by tagcup** [comment]
Thanks @reduz, while I don't have much to add, if that indeed the case the here... well I'm not going to quote those exact words again here (I already did either here or on IRC), but it's then truly appalling (to me) how different the understanding of what ad hominem attack can be between cultures.

**Comment by tagcup** [comment]
> Let's just act professional here and avoid using them to comment IRC dramas.

Here we go again. "Dramas". How about you set a nice example by taking upon your own advice first?

**Comment by reduz** [comment]
Those of us from latin cultures (and mostly here in the south) are very
direct in our words and can even insult or use irony , only for the next
day everything becoming as it never happened. Common insults just dont have
the strength they do in other places and are just ways to express
frustration.

I had a ton of issues due to that when working with Japanese companies. I
joked once that someone from there should be fired for proposing something
stupid and we almost get contract rescinded.

Just stop taking these things personal, no one hates you nor thinks you are
stupid, you are an invaluable contributor.

Heated arguments are fine, just please understand its not always easy to
match points of view, and people is not stupid for nor agreeing.

**Comment by tagcup** [comment]
@reduz I seriously don't know how this is happening but apparently I need to spell this out: I was obviously saying that (meaning my previous comment above) to @groud, not you, because, you know, I quoted him, not you.

**Comment by reduz** [comment]
@tagcup alright, but i insist, you are taking this too personal. There is no need to do that. There is no need to justify yourself because I don't think anyone here believes your purpose here is to insult people. It was just a misunderstanding and we should leave it at it. No one will remain angry with you, and you shouldn't remain angry with anyone.

**Comment by tagcup** [comment]
"This is happening" refers to this remark by akien

> You were taking his "side" in the discussion, and now he's put you on his hit list too for some reason...

Just wow. Way to go.

**Comment by tagcup** [comment]
I mean he just moved past beyond that, I don't even know what he's trying to do by blatantly lying about stuff like that: I did nothing remotely like that, yet he's going behind my back claiming I'm putting you on my "hit list". What??

**Comment by groud** [comment]
@akien-mga was talking to me when he said:

> You were taking his "side" in the discussion, and now he's put you on his hit list too for some reason...

**Comment by reduz** [comment]
@tagcup I still insist that you are worrying way too much about this stuff,  remember when I mentioned earlier that that you shouldn't take phrases or insults literally. You are making too much sense out of words or phrases that might have been just expressions of frustration. Let it go and simply forget about this incident. No one else really cares.

**Comment by tagcup** [comment]
@groud can say that for sure, but if it is indeed the case, then I take those words back.

@reduz Yeah, well you can say that; the frustration of not making "HR people" understand that you can't claim copyrights on mathematical equations while you're trying to do some actual work.

Anyway, I don't actually care about this either (I mean, this tagcup/Ferenc Arn is just an internet persona on github, a fake account with a fake name generated using random name generator, that's how much I care, so I really don't care what people say about "it"), it just turned into an argument that I didn't back down, as a bad habit of mine I guess.

**Comment by reduz** [comment]
@tagcup seriously, if you don't agree with someone, it's fine to tell that person so... but just don't go full intolarence. Keep it at that. Give it time, for most people arguments take time to sink in, and sometimes you may realize yourself you were wrong. Trying to get someone else to agree on the spot no matter what and forcing things rarely ends well. 

If you see you are not having progress, just politely end the discussion and continue another day. That's how arguments work best in my experience.

**Pull request merged**
