### PR TITLE
[3.0] Make drawing polygons work again

### PR DESCRIPTION
**Pull request by ficoos**
The code path for drawing polygons is currently commented out.
I assume @reduz has some plans for that but as it stands anythings that
needs polygon drawing like Line2D just doesn't render.

This proposes a somewhat inefficient solution but one that works and
doesn't drastically change the code.

### CODE REVIEW

**Comment by nunodonato** [comment]
Did you check #8425 ?

**Comment by ficoos** [comment]
This is suggested as a quick fix until a proper fix is implemented. I've been waiting for polygon drawing for months now.

**Comment by nunodonato** [comment]
yes, I was just asking if you checked that proposed fix instead of making another one :)

**Comment by reduz** [comment]
Ah, this needs to be fixed, the problem is we can' t use client arrays in
GLES3

**Comment by akien-mga** [comment]
Superseded by 41c3ca3.

**Pull request closed without merging**
