### PR TITLE
export StreamPeerStream's poll() function and optimize PackedPeerStream's package length with StreamPeer's big_endian

### PR DESCRIPTION
**Pull request by chenjie199234**
poll is useful when write a network program
without poll,we have to spin,and waste cpu
the reason is in this issue
https://github.com/godotengine/godot-proposals/issues/1415

i don't known if these code is ok
i'm not familiary with godot c++ code
please review the code

### CODE REVIEW

**Comment by aaronfranke** [comment]
@chenjie199234 Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) on the latest master branch. While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

**Comment by chenjie199234** [comment]
@aaronfranke this is still desired.i don't known how to rebase.

**Comment by Faless** [comment]
Regarding the `writable`/`readable`, this will need to go through proposal (e.g., with this method you can't poll until you can read **or** write).

For the `PacketPeerStream` change byteswapping the length... what is your use case? `StreamPeer` / `StreamPeerBuffer` have endianess so you can use them to easily create custom packets that expects big_endian to communicate with external protocols,

While `PacketPeerStream` somehow uses a custom protocol anyway to separate the packets, and since we define it, we don't really need to have 2 versions of it (big and little endian)

**Comment by akien-mga** [comment]
No answers to the above questions so closing. This should go through a proposal to discuss what the needs are so we can properly assess the change.

**Pull request closed without merging**
