### PR TITLE
Fix GDScript parser crash on 'dollar mixed with assignment' expression

### LINKED ISSUE #53696: GDScript 2.0: Godot crashes when after typing `$=$` into a GDScript function
### Godot version

4.0 dev (16b27304d90880b0a3a6bfefbb19f2718d5919af)

### System information

OpenSuse Tumbleweed 2021-10-05

### Issue description

Godot crashes when after typing `$=$` into a function in GDScript

Backtrace:
```
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.dev.custom_build (16b27304d90880b0a3a6bfefbb19f2718d5919af)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x427a0) [0x7fed287887a0] (??:0)
[2] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x13f98ed] (/~/godot/modules/gdscript/gdscript_parser.cpp:2323)
[3] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x13f3de1] (/~/godot/modules/gdscript/gdscript_parser.cpp:2007 (discriminator 4))
[4] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x1404273] (/~/godot/modules/gdscript/gdscript_parser.cpp:2030)
[5] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x1405270] (/~/godot/modules/gdscript/gdscript_parser.cpp:1373 (discriminator 6))
[6] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140accf] (/~/godot/./core/templates/cowdata.h:386)
[7] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x1414ab7] (/~/godot/modules/gdscript/gdscript_parser.cpp:704 (discriminator 4))
[8] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140cb4e] (/~/godot/./core/templates/cowdata.h:386)
[9] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140d7c5] (/~/godot/./core/templates/map.h:680)
[10] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x140e213] (/~/godot/modules/gdscript/gdscript_parser.cpp:365)
[11] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x13d6d70] (/~/godot/modules/gdscript/gdscript_editor.cpp:2389)
[12] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x2057f1f] (/~/godot/./core/templates/cowdata.h:386 (discriminator 2))
[13] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x234fd36] (/~/godot/./core/templates/list.h:467)
[14] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe5d73] (/~/godot/core/object/object.cpp:1102)
[15] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe69bb] (/~/godot/core/object/object.cpp:1155)
[16] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x27a7d3e] (/~/godot/./core/variant/variant.h:261)
[17] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe5d73] (/~/godot/core/object/object.cpp:1102)
[18] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fe69bb] (/~/godot/core/object/object.cpp:1155)
[19] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x2726a08] (/~/godot/./core/variant/variant.h:261)
[20] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x3fd7f84] (/~/godot/core/object/object.cpp:843)
[21] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x271128a] (/~/godot/scene/main/scene_tree.cpp:859)
[22] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x27129a7] (/~/godot/scene/main/scene_tree.cpp:453)
[23] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9fd027] (/~/godot/main/main.cpp:2573)
[24] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9d6611] (/~/godot/platform/linuxbsd/os_linuxbsd.cpp:342)
[25] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9c6ff5] (/~/godot/platform/linuxbsd/godot_linuxbsd.cpp:58)
[26] /lib64/libc.so.6(+0x2d540) [0x7fed28773540] (??:0)
[27] /lib64/libc.so.6(__libc_start_main+0x7c) [0x7fed287735ec] (??:0)
[28] /~/godot/bin/godot.linuxbsd.opt.tools.64() [0x9d5015] (/home/abuild/rpmbuild/BUILD/glibc-2.34/csu/../sysdeps/x86_64/start.S:118)
-- END OF BACKTRACE -- 
```

### Steps to reproduce

Type `$=$` into a GDScript function.

### PR DESCRIPTION
**Pull request by Scony**
fixes #53696 - GDScript parser crash on `$=$` expression

### CODE REVIEW

**Comment by Scony** [comment]
@vnen 2min review here

**Comment by akien-mga** [comment]
See #55433 which also aims at fixing this issue but puts the null check somewhere else.

**Comment by SaracenOne** [comment]
This PR is valid, but I believe it makes more sense to put the check where I did since it ends up solving multiple similar nullptr errors

**Comment by SaracenOne** [comment]
Hmm, I don't think I see any harm in that. In fact, it's likely just good practice to have checks whenever possible wherever performance is not meaningfully impacted.

**Comment by lyuma** [comment]
@vnen  Godot is making a big push towards getting 4.0 alpha out. Would it be possible to review this?

**Review by akien-mga — APPROVED** [review]
Approving on behalf of @vnen who's having a major power outage since several days.

> [vnen] In general if those are null checks on the parser/analyzer it should be fine to merge without my review

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
