### PR TITLE
docs: Add TreeItem method descriptions

### PR DESCRIPTION
**Pull request by jameswestman**

### CODE REVIEW

**Comment by flyingpimonster** [comment]
Whoops, it looks like there's already #42541. I added a bit more detail for some of the descriptions, though, so should I keep this open?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Yes my bad for not reviewing #42541 earlier, but your PR definitely has more details on what the methods do.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
