### PR TITLE
Removed default commit message

### LINKED ISSUE #44413: Remove default commit message in VCS commit dock
Current commit message should be a placeholder (instead of default message).

image

like 
image
image

Also without a placeholder, after a commit, the text box of commit message is emptied and unhinted about its use.

Suggested solution:  TextEdit implements placeholder functionnality

### PR DESCRIPTION
**Pull request by Janglee123**
Fixes #44413.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
It would be better if it was changed to a placeholder, as suggested in the issue report.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Anutrix** [comment]
> The commit button should be disabled while there is no content.

This part is still pending.

**Comment by YeldhamDev** [comment]
@Anutrix See this PR: #44549

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
