### PR TITLE
Fix RichTextLabel alignment tags not working properly

### LINKED ISSUE #6982: rich text label: [center] und [right] don't work correct
**Operating system or device - Godot version:**
Mac OS 10.10.5, Godot 2.1

**Issue description** (what happened, and what was expected):

Only the first line is correct aligned. All other lines are left-aligned to the first line:
What I get: https://dl.dropboxusercontent.com/u/13472834/Foren/godot_rich.png
What I expect: https://dl.dropboxusercontent.com/u/13472834/Foren/godot_rich2.png

**Steps to reproduce:**

Add a rich text label and add text:

Godot provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.

[right]Godot provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.[/right]

[center]Godot provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.[/center]

**Link to minimal example project** (optional but very welcome):

### PR DESCRIPTION
**Pull request by eligt**
Also fixes #6982

### CODE REVIEW

**Comment by akien-mga** [comment]
Code looks fine, but could you squash the commits together?

**Comment by eligt** [comment]
Done.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Note to release maintainers: if this gets cherry-picked, #29913 should be cherry-picked too to fix the #29810 regression.

**Pull request merged**
