### PR TITLE
Made use of semicolons after GDCLASS more consistent, added semicolons where I found them missing. 

### PR DESCRIPTION
**Pull request by LightIncorporated**

### CODE REVIEW

**Comment by JohnJLight** [comment]
I had discussed this on the IRC channel earlier and was told I could go for it.

**Comment by karroffel** [comment]
I would've expected it the other way around.

I remember the compiler complaining about the *presence* of the semicolons, not the *absence*.

**Comment by Zylann** [comment]
I always used semicolons for my modules, primarily because QtCreator was underlining them in red, but compiler was ok with it.

**Comment by JohnJLight** [comment]
I don't understand what is causing it to fail the Travis CI build.  Could anyone offer advice?

**Comment by bojidar-bg** [comment]
@JohnJLight It is failing because of missing newlines after each of the new semicolons. Probably faster to just run clang-format on all the changed .h files.

**Comment by akien-mga** [comment]
I think this is good, though I wish there was a way to enforce it with `clang-format`, but it doesn't look like it.

Current stats show a slight predominance of `GDCLASS` statements with trailing semicolon, so this goes in the right direction:
```
$ rg GDCLASS\(.*\)[^\;]$ | wc -l
412
$ rg GDCLASS\(.*\)[\;]$ | wc -l
615
```

Since time passed I guess there might be some new occurrences not covered in this PR, might need a rebase to include them.

**Comment by akien-mga** [comment]
> Since time passed I guess there might be some new occurrences not covered in this PR, might need a rebase to include them.

Indeed, stats with this PR merged locally:
```
$ rg GDCLASS\(.*\)[^\;]$ | wc -l
45
$ rg GDCLASS\(.*\)[\;]$ | wc -l
982
```

The remaining ones are in:
```
$ rg GDCLASS\(.*\)[^\;]$ -l
methods.py
core/object.h
editor/editor_properties.cpp
editor/import_dock.cpp
scene/main/viewport.cpp
scene/resources/dynamic_font.h
scene/resources/visual_shader.h
scene/resources/visual_shader_nodes.h
scene/resources/resource_format_text.h
modules/visual_script/visual_script_editor.cpp
editor/import/resource_importer_texture_atlas.h
editor/plugins/mesh_editor_plugin.h
servers/audio/effects/audio_stream_generator.h
editor/plugins/visual_shader_editor_plugin.cpp
servers/audio/effects/audio_effect_spectrum_analyzer.h
editor/plugins/texture_editor_plugin.h
platform/javascript/export/export.cpp
platform/android/export/export.cpp
```

**Comment by akien-mga** [comment]
Force pushed a rebase addressing above comment.

**Review by akien-mga — APPROVED** [review]
Can be merged when CI passes.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
