### PR TITLE
Allow drag & drop Mesh to create MeshEmitter in visual shaders

### PR DESCRIPTION
**Pull request by Chaosus**
(Continuation of https://github.com/godotengine/godot/pull/54660)

vs_mesh_drag_and_drop

### CODE REVIEW

**Comment by QbieShay** [comment]
Can you show how the mesh presents in the material uniforms?

**Comment by Chaosus** [comment]
> Can you show how the mesh presents in the material uniforms?

I don't understand what do you mean?

**Comment by QbieShay** [comment]
In the parameters of the shader, where you can usually change textures and numbers, can you see the mesh for the mesh emitter?

**Comment by Chaosus** [comment]
Nope, you can't see the mesh in the parameters or uniforms + it doesn't relate to this PR, which is just an enhancement to an already existed feature to just allow drag & drop.

**Comment by QbieShay** [comment]
Ah ok, cool!

I think we should look into making mesh point textures then, in the future ^^

**Review by QbieShay — APPROVED** [review]

**Comment by Chaosus** [comment]
> I think we should look into making mesh point textures then, in the future ^^

Yeah, interesting idea, probably need a proposal for that.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
