### PR TITLE
Improving of the code readability

### PR DESCRIPTION
**Pull request by Yeryomin1**
"goto" constructs have been removed from the code. The changes are designed to improve compactness and reduce code complexity.

### CODE REVIEW

**Comment by akien-mga** [comment]
There are various style issues, both with indentation and with the spacing in parentheses: https://travis-ci.org/godotengine/godot/jobs/507326203

See [Code style guidelines](http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html).

**Review by hpvb — CHANGES_REQUESTED** [review]
I disagree that this improves code readability. Not all gotos are bad!

**Comment by Yeryomin1** [comment]
> I disagree that this improves code readability. Not all gotos are bad!

Quite possible. The question is subjective in its essence.

**Comment by reduz** [comment]
I am good either way and remain completely neutral

**Comment by akien-mga** [comment]
Closing as there's no real gain nor consensus.

**Pull request closed without merging**
