### PR TITLE
Fix various typos in documentation

### PR DESCRIPTION
**Pull request by sepTN**

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good! Did you use a tool to find those?

Could be worth adding those to codespell's dictionary, as it's the main tool we run on the whole codebase. This would prevent re-introducing the same typos in other places.
https://github.com/codespell-project/codespell#sending-pull-requests

*Edit:* Likewise for your previous batch: #86549

**Comment by sepTN** [comment]
> Looks good! Did you use a tool to find those?

I only use "Code Spell Checker" extension in my VSCode, and manually skim through lines that are getting color highlighted. I haven't looked into codespell, I'll check it out during one of these weekends 😆

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
