### PR TITLE
[WIP] Replace AppVeyor with GitHub Actions

### PR DESCRIPTION
**Pull request by RevoluPowered**
This is based on @qarmin's work in #38433

It *only* builds windows at the moment and provides:
- windows editor binaries which you can download.
- pull request building
- cache handling (to be fixed but this should work...)
- explicit python versioning 
- faster builds

It's really meant to just replace AppVeyor right now in a smaller step so Godot can evaluate it internally.

**Example/overview of the actions**
- https://github.com/RevoluPowered/godot/actions

**Windows binaries example**
- https://github.com/RevoluPowered/godot/actions/runs/161976551

**Some build logs to show you how the builds replicate the existing appveyor behavior**
- https://github.com/RevoluPowered/godot/runs/849869572?check_suite_focus=true

### CODE REVIEW

**Comment by akien-mga** [comment]
I see you test build from scratch took 40 min. Did you check how long it then takes with cache:
- For a no-op build
- For a change to a leaf class (e.g. something in `editor`)?

**Comment by RevoluPowered** [comment]
> I see your test build from scratch took 40 min. Did you check how long it then takes with cache:
> 
>     * For a no-op build
> 
>     * For a change to a leaf class (e.g. something in `editor`)?

I can run tests of this and post the results with the cache, I had some troubles with the caching on windows, basically it has a cache directory but it wasn't being used. :/ I tried scons updates and no luck, so will boot windows and look into it there.

IRC for me is down right now IRCCloud is having ISP issues. 

I could use some help debugging why the cache there is not working, I think possibly it's looking in the wrong directory for the cached files.

**Comment by Calinou** [comment]
> IRC for me is down right now IRCCloud is having ISP issues.

Use http://webchat.freenode.net/?channels=#godotengine-devel for now :slightly_smiling_face:

**Comment by akien-mga** [comment]
Superseded by #40282.

**Pull request closed without merging**
