### PR TITLE
Prevent button "Items" from disapearing when editing node

### LINKED ISSUE #28211: OptionButton "Items" button dissapear when other editor is active (e.g. Theme or AtlasTexture)
**Godot version:**
Stable 3.1

**OS/device including version:**
Windows 10, GTX 1060 6gb

**Issue description:**
OptionButton "Items" button dissapear from scene top bar.

**Steps to reproduce:**
Create a new OptionButton node;
Go to Control/Theme on Inspector;
Create a new theme and click to edit it.

### PR DESCRIPTION
**Pull request by Amssat221**
Fixes  #28211

### CODE REVIEW

**Comment by MunWolf** [comment]
This just makes the make_visible method do nothing, this will break more things then it fixes...

**Comment by Amssat221** [comment]
@MunWolf , I'm working on another approach to solve this issue

**Comment by Amssat221** [comment]
@MunWolf 
I believe this should fix the issue. Can I have your opinion on it?

**Comment by YeldhamDev** [comment]
I can't tell for sure, I don't feel this is the right way to fix this.

**Comment by akien-mga** [comment]
Closing then, as it does not fix the issue as per @YeldhamDev's comment.

**Pull request closed without merging**
