### PR TITLE
Push script's theme options from File menu to separate Theme menu

### PR DESCRIPTION
**Pull request by Chaosus**
I reduced a size of File menu a bit.. 

image

### CODE REVIEW

**Comment by volzhs** [comment]
this could make #18078 issue worse, pushing further the right docks.

**Comment by volzhs** [comment]
I thought you would make like this one, under the File menu.
screenshot_20180621_151411

**Comment by Chaosus** [comment]
Yeah, I will make another PR...

**Comment by akien-mga** [comment]
If you can move the "Syntax Highlighter" menu to a submenu too, that would be great :)

**Comment by Chaosus** [comment]
@akien-mga Ok

**Pull request closed without merging**
