### PR TITLE
Replace radion buttons with checkboxes in GDNativeLibrary editor

### LINKED ISSUE #30841: GDNativeLibrary editor should let you filter platforms with checkable entries
**Godot version:**
3.1.1 and 3.2 master (d483a85)

**OS/device including version:**
 Mageia 7 x86_64

**Issue description:**
When you create a `GDNativeLibrary` resource, a specific editor is shown. It has a drop-down list to select platforms which should be visible, but it's all or nothing as it uses exclusive radio buttons:
Screenshot_20190726_163808

This popup menu should use checkboxes so that you can select the platforms you want to see.

**Steps to reproduce:**

- Open project
- On Inspector, click "Create new resource"
- Select GDNativeLibrary
- Uses drop-down list to filter platforms, see that you can only filter "All" or any single platform

### PR DESCRIPTION
**Pull request by NilsIrl**
Fix #30841

### CODE REVIEW

**Comment by NilsIrl** [comment]
output

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I merged a bit fast, but it could be improved further IMO:
- The previous stylebox made it clear that it was a drop down list, it would be nice to restore that.
- Once the stylebox makes things clear, I would replace the redundant "Choose platform" with a comma-separated list of the currently enabled platforms.

**Comment by NilsIrl** [comment]
Should I make another PR with the improvements?

Or should I commit to this branch?

**Comment by akien-mga** [comment]
That PR is merged so you can't update it further, it would have to be in a new PR.

**Pull request merged**
