### PR TITLE
HTML5 start-up overhaul with download progress display

### LINKED ISSUE #9127: Javascript Moving Loading Icon
## Summary

The loading page, while a Godot Javascript game export is downloading, should have a moving loading icon.

## Explanation

Users have a hard time believing that a computer is doing something if there is nothing indicating that it is actually getting somewhere. Granted, Godot does say, "Loading Page...", but as it sits there saying that, the page looks completely frozen. If it is a larger game or is it is downloading over a slower network, the user is likely to kill the page because it looks like it hasn't gotten anywhere. It would be nice to have a rotating circle icon or something like that. Even if the icon is a gif and it doesn't actually indicate progress, I think it would make the user feel a lot better.

### PR DESCRIPTION
**Pull request by leonkrause**
Most obviously, this patch adds a download progress bar. Also comes with a spinner for indeterminate progress (when total size is unknown and during other start-up steps).
Resolves #9127

Also makes it simpler to write your own HTML page, I'll add some example HTML pages later. For now, see `/misc/dist/html/default.html`

All complex logic is hidden away in `engine.js` which is merged into `godot.js` during the build, so that the HTML file is easy to write. `engine.js` adds a simple JavaScript interface `Engine` that hides Emscripten's `Module` interface and implementation details like WebAssembly compilation, start-up memory management or main pack FS integration.

 - Implement promise-based JS interface for custom HTML page integration
 - Add download progress callback
 - Add progress bar and indeterminate spinner to default HTML page
 - Try downloading files multiple times when failing
 - Get rid of `godotfs.js`
 - Separate steps for engine initialization, game initialization and game start
 - Allow multiple games on one HTML page
 - Substitution placeholders only used in `.html` file
 - Placeholders renamed: `$GODOT_BASE` => `$GODOT_BASENAME`, `$GODOT_TMEM` -> `$GODOT_TOTAL_MEMORY`
 - Emscripten `Module` is now `Engine.RuntimeEnvironment`

### CODE REVIEW

**Comment by eska014** [comment]
here's a demonstration with the default HTML page: https://godot.eska.me/temp/load/

**Comment by hpvb** [comment]
Looks great to me. But this is not XHTML though, is it? Is the html xmlns thing actually meaningful.

**Comment by eska014** [comment]
@hpvb Should be valid XML.
It's not a change from this patch though, been like that for a while

**Comment by anissen** [comment]
Safari fails to load the demonstration game with the following error: `Can't find variable: WebAssembly`

**Comment by eska014** [comment]
@anissen Thanks, should be fixed

**Comment by anissen** [comment]
It is indeed. Now I'm getting `WebGL 2 not available` instead ;)

**Comment by eska014** [comment]
@anissen WebKit doesn't support WebGL 2, so I'm afraid you'll have to report that one to Apple =p
It's apparently enabled in preview though: https://webkit.org/status/#specification-webgl-2

**Pull request merged**
