### PR TITLE
Add unique icon to Polygon2D

### LINKED ISSUE #33993: Polygon2D and CollisionPolygon2D have the same icons
**Godot version:**
3.2 beta2

**Issue description:**
image
They should be different.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #33993
image

### CODE REVIEW

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
I just wondered, why this wasn't cherry-picked?

**Comment by akien-mga** [comment]
Because nobody set the `cherrypick:3.2` label :)

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
