### PR TITLE
Show options to build vsproj only if selected platform is windows

### PR DESCRIPTION
**Pull request by ghost**
The description of what PR does and the PR itself are smaller than description how this PR done :joy:

Calling `env["vsproj"]` will result in error if you didn't add the option to variables. I mean if you didn't declare `BoolVariable("vsproj", "Generate a Visual Studio solution", False)` which won't declared on non-windows platforms after this PR

Python has [short circuited bool operators](https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not) so `env["vsproj"]` won't be even evaluated if `"vsproj" in env` returned false

Why not to use just `"vsproj" in env`? :joy: :joy: :joy: Because SCons is very stupidly designed... It was a surprise that `in` operator worked at all. But not as you would expect. :joy: You would expect it to tell you if it contains pair `key, value` with given key. Just like in normal dictionary...

But not it will actually tell you if you added "validator". I mean this declaration `opts.Add(BoolVariable("threads", "Enable threading support", True))`.

P.S: I am now sick and it is hard to think maybe two previous paragraphs are wrong not by itself but a bit unrelated to this PR

### CODE REVIEW

**Comment by fire** [comment]
As far as I know, one of the features was being able to call vsproj from linux or mac. Does this perserve that?

**Comment by dustdfg** [comment]
> As far as I know, one of the features was being able to call vsproj from linux or mac. Does this preserve that?

I am not sure what do you mean. Is there a feature to build godot with vsproj on linux or mac or you are about just generating vsproj file on linux and macos?

If the second so it is preserved. The only difference that now you need to explicitly add that your target platform is windows `scons p="windows" vsproj="yes"` but you can still do it on linux and mac. I have linux and tested it before and after PR. It works. But linux/mac users won't be annoyed by `vsproj` options in their `scons -h` output

If there is actual building from generated file on linux or mac, I know about it only now and don't know maybe it is preserved `¯\_(ツ)_/¯`

**Comment by dustdfg** [comment]
CC @shana (too many cc for one person in several minutes :sweat: )

I think this brakes something intended?

**Comment by shana** [comment]
I don't think this is useful? The option is there in order to generate a VS solution and projects files that can be loaded into IDEs that support the format. You can generate those project files from any platform, not just windows - and technically if an IDE supports the format, it can load them regardless of whether it's on windows or not, the `.sln`/`.vcxproj` formats aren't Windows-specific.

Additionally, having the option only on the Windows platform doesn't make sense - you can generate VS projects for all platforms that you can build on Windows. This includes Android out of the box, but also all console platforms.

**Comment by shana** [comment]
To be clearer, because the word "Windows" and "Platform" are a bit overloaded: on this laptop that is running Windows 11 right now, I can do the following to generate VS project files:

- `scons vsproj=yes` : Generates project files to build the editor, assuming `platform=windows`
- `scons platform=android target=template_debug vsproj=yes` : Generates project files to build the debug template for Android
- `scons platform=gdk target=template_debug vsproj=yes` : Generates project files to build the debug template for the custom GDK platform that I have added to my godot source locally

As you see, that only works because the `vsproj` option is available for all godot target platforms. If it were only defined on the `windows` platform, it would not be possible to generate project files for any other godot target platform.

**Pull request closed without merging**
