### PR TITLE
Fix use of comma instead of semicolon

### PR DESCRIPTION
**Pull request by quentinguidee**
Fix 3 suspicious use of `,` instead of `;`

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
How did this even compile?

**Comment by akien-mga** [comment]
Thanks!

**Comment by quentinguidee** [comment]
> How did this even compile?

I think that's simply because in c++ you can write `a = 1, b = 2;`

**Comment by RandomShaper** [comment]
All expressions evaluate (including side effects), but I don't think anyone is actually using such a syntax unless by mistake. 😃

**Pull request merged**
