### PR TITLE
 Fix crash when using the Tileset Editor when the given shape has no points

### LINKED ISSUE #27360: New TileSet editor crashes Godot when a tile contains RectangleShape2D
**Godot version:**
v3.1.stable.official

**OS/device including version:**
At least Linux

**Issue description:**
If you specify the "Shape" property of a tile as RectangleShape2D, new TileSet editor will not be able to work correctly with this tile.

**Steps to reproduce:**
1. Select TileMap node.
2. Open the "Tile Set" property of the TileMap node.
3. Select img.png in new TileSet editor.
4. Click on the red area of the image.

**Minimal reproduction project:**
[tilesetedit_bug.zip](https://github.com/godotengine/godot/files/2999710/tilesetedit_bug.zip)
[error.log](https://github.com/godotengine/godot/files/2999713/error.log)

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #27360.

### CODE REVIEW

**Comment by MarianoGnu** [comment]
@YeldhamDev whi did you remove the default shape on  scene/resources/convex_polygon_shape_2d.cpp?
i'm not sure if that should be part of this PR

**Comment by YeldhamDev** [comment]
@MarianoGnu As explained in the commit itself, it's for consistency, it's the only shape that starts with predefined points.

**Comment by MarianoGnu** [comment]
@akien-mga @reduz looks good to me

**Review by MarianoGnu — APPROVED** [review]

**Review by MarianoGnu — CHANGES_REQUESTED** [review]
Now that i see the related issue, i dont see why this would prevent the crash. This fix would prevent #27035 but not #27360

**Comment by YeldhamDev** [comment]
@MarianoGnu In the same way as the other fix, by skipping the code that's trying to access the points in a shape without any.

**Comment by MarianoGnu** [comment]
RectShape2D has an extents property, it is not a polygon. The same way as circle shape has a radious.
It shoudn't help to fix the issue. The TileSet editor should ignore non polygon shapes
As fas as i knew it was already the case, but if not, the described changes wont prevent it. This prevents drawing invalid polygons, the same way as #27201 wich is already merged.

**Comment by YeldhamDev** [comment]
@MarianoGnu You can literally grab the reproduction project, and see that it doesn't crash anymore...

**Comment by YeldhamDev** [comment]
I made some edits to the commit so it will skip drawing the polygon if less than 3 points are present, with modifies the recent implementation merged of skipping it if no points are found.

#27360 was already fixed by #27201, as this one would.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

Only cherry-picked commit 9501900 which fixes the crash. Commit c7cfe53 would break compatibility as I understand it.

**Comment by YeldhamDev** [comment]
@akien-mga Not really, as it only affects newly created shapes.

**Comment by akien-mga** [comment]
> Not really, as it only affects newly created shapes.

Yes, but as I understand it, if your 3.1 game is creating shapes from script and you used the default points, this change would break this use case.

**Pull request merged**
