### PR TITLE
Draw relationship lines when its value is higher than 0

### LINKED ISSUE #24579: Relationship Lines are not being drawn in TreeNode despite width and color set
3.1 (I don't have the exact commit, it was the one where Calinou made the different indent lines?)

When using a TreeNode, the relationship lines aren't being drawn despite the size and color being set to non-null values. 

ex

[Example Project](https://github.com/AlexAndDraw/TreeExample)

### PR DESCRIPTION
**Pull request by volzhs**
Fix #24579

### CODE REVIEW

**Comment by akien-mga** [comment]
I think it would be better to make it a boolean, people will still be confused that setting a value to "10" makes no difference to "1" or "65536".

**Comment by volzhs** [comment]
doesn't it break compatibility?
I think we need to add `void add_bool_override(String name, bool enable)` for it.

**Comment by akien-mga** [comment]
> doesn't it break compatibility?

That's not a big deal for a visual editor preference.

>  I think we need to add void add_bool_override(String name, bool enable) for it.

That's more annoying though, it adds some more complexity. So let's go with this fix for now :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
