### PR TITLE
Always center editor dialogs

### PR DESCRIPTION
**Pull request by ghost**
This makes the editor dialog boxes spawn with `popup_centered()` rather than `popup()`, in order to keep them nice and centered each time they're shown. As a result, the dialogs now only save and retrieve their sizes to and from `EditorSettings`, rather than their whole bounds. This will lead to the old bounds settings being left unused, which can be resolved by removing their entries from `editor_settings-3.tres` (I could've sworn there used to be a way to delete them through the editor...)

Here's a video of it in action: https://streamable.com/s2qq0

I realise that it's fairly subjective whether or not this is a good change. If you don't like it, please say so! I promise I won't get mad!!!

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm not sure about this, as it seems to defeat the purpose of saving the size of the dialog when you resize it manually. If there was no logic to remember the last position, then sure defaulting to centered would be good enough, but I think the current system is already better than what this makes it, no? Things should be centered by default, and not centered only if you moved/resized them yourself.

**Comment by homer666** [comment]
@akien-mga The "always-centered" stuff was just to taste, as I'd personally never want it anywhere but dead-center except when I explicitly need it out of the way for a moment. I didn't know what others thought about it so I made the PR to gauge for opinions. It can be removed, it's not a big deal.

I probably should've mentioned this from the start, but the main point of this is just to address the popups' tendency to get moved/squashed when windowing the editor or moving it to another monitor. Right now there's no way to get it centered again without either eyeballing it or editing `editor_settings-3.tres` manually, which bugs me a lot...

My alternative was to do as you mentioned and change the logic behind when the dialog bounds are saved, so it would only happen when they're moved/resized by the user rather than upon opening them. It shouldn't be much harder than moving the code to under a different notification. That + maybe restoring the ability to remove the bounds entries from the Editor Settings would be enough to satisfy my pedantry.

I'll make the changes soon-ish.

**Comment by mhilbrunner** [comment]
Are you going to make that changes in a seperate PR or shall we keep this one around? Whats the status on this? :)

**Comment by homer666** [comment]
Controls don't have a signal/notification for when its position is changed, so there's no easy way for me to do this. I'm just going to close this PR...

**Pull request closed without merging**
