### PR TITLE
Document GradientTexture updates being deferred

### LINKED ISSUE #66627: get_image() gives wrong result on GradientTexture2D
### Godot version

4.0 beta2 (mono version)

### System information

Ubuntu 22

### Issue description

the get_image() command gets an image with both wrong size and wrong general look when called on GradientTexture2D.
It seams the the image is  always 64x64 pixels. It depicts a different gradient with generally the same colors.

### Steps to reproduce

Put the following code on a Sprite2D and put any gradient not 64x64 pixels in size into "gradient_texture"

```gdscript
extends Sprite2D

@export var gradient_texture: GradientTexture2D 

func _ready():
	var img = gradient_texture.get_image()
	prints(img.get_width(), img.get_height())
	texture = ImageTexture.create_from_image(img)
```

### Minimal reproduction project

[GradientTexture2DBug.zip](https://github.com/godotengine/godot/files/9679333/GradientTexture2DBug.zip)

### PR DESCRIPTION
**Pull request by Calinou**
I don't know if a new `force_update()` method could be added, but that's proposal territory.

- This closes https://github.com/godotengine/godot/issues/66627.

### CODE REVIEW

**Comment by KoBeWi** [comment]
#81137 ensured that `get_image()` gives correct results. However the update is still deferred, so unless you force it (which `get_image()` does), the actual update will happen at the end of the frame.

I'm not sure about the "after 2 frames" part. Deferred class still happen in the same frame, just after everything else (see #77688), so the texture might be correct immediately. If that is the case, this PR can be closed.

**Comment by YuriSizov** [comment]
> Deferred class still happen in the same frame, just after everything else

This still means that you need to wait until the next frame to access it (or use a deferred call in a script as well).

**Comment by KoBeWi** [comment]
As I said, `get_image()` doesn't require waiting. The update itself is deferred, but not sure if it affects anything. Maybe the texture displays old data for a single frame.

**Comment by YuriSizov** [comment]
Ah, I see what's going on. `get_image()` specifically forces an update. Then indeed, this shouldn't require you wait for the next frame. It should be available immediately, unless `RenderingServer::texture_replace` is somehow deferred. But it doesn't appear this way.

I'm going to close this PR then. Thanks!

**Pull request closed without merging**
