### PR TITLE
Seperate octree layers for visual instances.

### PR DESCRIPTION
**Pull request by SaracenOne**
This changes the way the VisualServerScene organises instances by actually placing them on separate layers with their own octrees. This is a significant optimization specifically for this PR (https://github.com/godotengine/godot/pull/8215) since you'll want to use this to mask certain objects on certain cameras, but cameras would be forced to traverse one massive octree regardless of what objects are important with the original. Now, a camera will only have to traverse and cull the layers specific to it. As a scenario, imagine you have two cameras for an FPS, one for the player's view (which would require traversing many objects), and one for the gun viewmodel, which only cares about one object. This removes the overhead of the gun camera having to traverse the entire octree. It does however operate under the assumption that the majority of VisualInstance will mostly be confined to one layer at a time, which is what most scenarios should only require.

There may be alternative techniques (and the culling system could probably do with a broader overhaul anyway), but this is the technique I've been using at it seems to work fine.

### CODE REVIEW

**Comment by reduz** [comment]
This is cool! I will probably leave 3.0 render as is for now. For 3.1, as I
mentioned before, I want to change the renderer into a sap+hashgrid
approach.. as at this point, I think it's getting obvious that separating
culling and indexing is desired..

**Comment by SaracenOne** [comment]
Yeah, I think we've thrown around a bunch of ideas for how we could introduce more flexible approaches to occlusion culling. There's lots which could be done. This is just a quick fix for the multi-camera code.

**Comment by mhilbrunner** [comment]
Moving to 3.2 for the Vulkan renderer.

**Comment by Zireael07** [comment]
What's the situation?

**Comment by akien-mga** [comment]
Eventually Vulkan happened and we decided to move all big rendering changes to the 3.2 milestone, so this one too.

**Comment by reduz** [comment]
Closing, as the GLES3 codebase will be removed in 3.2/4.0. Let's discuss better how to do this after 3.1 is out.

**Pull request closed without merging**
