### PR TITLE
Fix crash in PluginScript destructor

### PR DESCRIPTION
**Pull request by ede-krcv**
Cherry picked from https://github.com/godotengine/godot/pull/30187

[EDIT: contains only a subset of above PR]

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks, but this should be done with `git cherry-pick -x 55234d6` to preserve the relationship to the original commit.

For stable branches, our release managers handle cherry-picks themselves after thorough review and testing, to ensure that it both fixes the issue and does not introduce regressions. I marked PR #30187 to cherry-pick for 3.1.x, so I'll have a look before releasing 3.1.2.

**Comment by akien-mga** [comment]
I was wrong, as discussed in https://github.com/godotengine/godot/pull/30187#issuecomment-550057331 this is only a subset of #30187, the rest is not relevant for the 3.1 branch. So it makes sense to just merge those changes as is.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by ktksgit** [comment]
Note for me: I should improve the description next time what I really did in the Pull Request :)

**Pull request merged**
