### PR TITLE
GUI elements ui_action usage, improvements

### LINKED ISSUE #16946: Popupmenu uses KEY_* instead of ui_* actions
**Godot version:**

3.0+

**OS/device including version:**

Linux

**Issue description:**

Popup menus can not be used with e.g. a gamepad. Looking at the source reveals they look for KEY_* inputs instead of ui_* actions.

**Steps to reproduce:**
Create a popup menu.
Navigate with keyboard up and down - Ok.
Try to navigate via ui_up & ui_down mapped keys - Not ok.

**Minimal reproduction project:**

### LINKED ISSUE #17159: Pressing escape to close completion proposals closes the shader editor
Godot 3.0.1

When the shader editor opens completion proposals, pressing Escape usually hides it. Now it also closes the shader editor, which is not expected in that case.

image

Related to https://github.com/godotengine/godot/pull/15862

### PR DESCRIPTION
**Pull request by Faless**
- Popupmenu now uses UI actions instead of key presses
- Tree now uses UI actions instead of key presses
- Line edit up/down focus pass through
  When line edit receive a up/down and the cursor is at beginning/end it will not set the input as handled
- Properly sets input as handled when closing modal
- Scrollbar now uses UI actions instead of key presses
- Add two new default actions `ui_end`, `ui_home`, used by Slider and Scrollbar (I can remove this if found useless)
- Add item_focused signal to OptionButton (and id_focused to PopupMenu)
  This is useful if for example you want to add UI sounds to your game.

Closes #16946 
Closes #17159

### CODE REVIEW

**Comment by vnen** [comment]
This fixes #16946.

**Comment by Faless** [comment]
thanks, added it to the PR description so it should get closed automatically when merged

**Comment by bfloch** [comment]
Awesome. Thanks.

**Review by groud — APPROVED** [review]

**Comment by bfloch** [comment]
I've tested this and it seems to work. 

I still have an issue where a popup panel does not react to any focus events on a keyboard. I try to find out if this is related or a separate issue.

**Comment by Faless** [comment]
As no one seems to find the courage to merge this even though it's been tested and approved by a few, I'll abuse my newly acquired power and do it myself :grin:

**Comment by Faless** [comment]
I'm sure there will be plenty of time to take the blame before `3.1` is out if something breaks :smirk_cat:

**Comment by legione** [comment]
Is there any chance to see these fixes in 3.0.3?
I don't think these changes would break the compatibility and half of them are bugfixes anyway.

**Comment by legione** [comment]
May I also point to #18715 that I think is related?

**Comment by follower** [comment]
Hi @Faless, would you be open to revisiting this code to see if you can fix the issues with keyboard navigation that seemed to occur as a result of the "Tree now uses UI actions instead of key presses" changes?

Assuming my assessment of the situation is correct, the issues have had a significant negative impact on the accessibility & usability of the Tree control both within the editor & third-party games/apps.

There's some further details in #41014 & #36291.

**Pull request merged**
