### PR TITLE
[3.x] Synchronous shaders in editor

### LINKED ISSUE #62244: Starting the editor delay regression
### Godot version

3.x (3.5 RC4?, not present RC3)

### System information

Linux Mint 20.1
Intel Core i5-7500T
8gb RAM
Intel HD Graphics 630

### Issue description

After building the editor after #61995, I noticed that the editor seemed to be taking longer at startup (and the project manager). Switching between "synchronous" and "asynchronous" seems to change the delay.

### Steps to reproduce

Switching from "synchronous" to "asynchronous" seems to create the delay.

Measured startup in debug:
3828 ms (sync)
4278 ms (async)

I haven't thoroughly investigated this, but was worth a mention as any increase in startup time can be problematic for debugging / development.

### Minimal reproduction project

N/A.

### PR DESCRIPTION
**Pull request by lawnjelly**
The old style synchronous shaders allow the project manager and editor to load faster.

Fixes #62244

## Notes
Based on discussions with @akien-mga there seem to be some pros and cons for defaulting asynchronous shaders in the editor which occurred in #61995 :

* pros: enables finding async shader compilation bugs in the editor faster
* cons: on some systems, seems to significantly slow down the editor / project manager, even with caching. Additionally, if there are problems compiling async shaders with some drivers, it could mean the editor not working at all (e.g. #62203 )

In particular it doesn't seem as though compiling all the shaders in a project ahead of time is advantageous in the editor. You may only be editing certain scenes, and the editor startup time is crucial to keep as low as possible for devs.

Some options (not exhaustive):

* Do nothing (deal with the decreased editor performance)
* Fix the performance to be as good as before
* Disable async in the editor / project manager (easy for users, but means no feedback on async shader compilation issues)
* Add a separate editor setting to enable / disable async in the editor, rather than using the project setting (if this defaulted to async, we would still get feedback, but most people's editor would run slower)

### CODE REVIEW

**Comment by RandomShaper** [comment]
Given the evidence, I'm in favor of having separate runtime and editor settings. For some GPUs and projects, async is indeed bad for agility in the editor.

**Comment by akien-mga** [comment]
Something like this might be better implementation wise:
```diff
diff --git a/servers/visual_server.cpp b/servers/visual_server.cpp
index 5baf0ebaff..685e46dc05 100644
--- a/servers/visual_server.cpp
+++ b/servers/visual_server.cpp
@@ -2738,6 +2738,7 @@ VisualServer::VisualServer() {
 	GLOBAL_DEF("rendering/gles3/shaders/shader_compilation_mode", 2);
 	ProjectSettings::get_singleton()->set_custom_property_info("rendering/gles3/shaders/shader_compilation_mode", PropertyInfo(Variant::INT, "rendering/gles3/shaders/shader_compilation_mode", PROPERTY_HINT_ENUM, "Synchronous,Asynchronous,Asynchronous + Cache"));
 	GLOBAL_DEF("rendering/gles3/shaders/shader_compilation_mode.mobile", 0);
+	GLOBAL_DEF("rendering/gles3/shaders/shader_compilation_mode.editor", 0);
 	GLOBAL_DEF("rendering/gles3/shaders/max_simultaneous_compiles", 2);
 	ProjectSettings::get_singleton()->set_custom_property_info("rendering/gles3/shaders/max_simultaneous_compiles", PropertyInfo(Variant::INT, "rendering/gles3/shaders/max_simultaneous_compiles", PROPERTY_HINT_RANGE, "1,8,1"));
 	GLOBAL_DEF("rendering/gles3/shaders/max_simultaneous_compiles.mobile", 1);
```

**Comment by lawnjelly** [comment]
Is there any in-built way of detecting whether we are in the project manager? Or could we simply overwrite this project setting in the `ProjectManager` constructor or something like that? :thinking:

**Comment by akien-mga** [comment]
There's `Main::is_project_manager()` that you can use for this.

BTW I checked and the project setting override I proposed would actually always be active for `TOOLS_ENABLED` builds, so it would also affect running the project from the editor, which might not be wanted. So your approach might be better.

**Comment by lawnjelly** [comment]
I've just tested and it turns out that `is_editor_hint()` is still set in the project manager at the time the setting is queried, so it actually works already as is.

I have however added:
```
if (!Engine::get_singleton()->is_editor_hint() || !Main::is_project_manager()) {
```
As this is clearer and more future proof, as `editor_hint` _is_ set to false later by the `ProjectManager`.

The only thing is the `is_project_manager()` check adds a dependency to `main.h`, although imo clarity of intention is probably more important here, unless we should be avoiding this dependency for chaining reasons.

**Comment by akien-mga** [comment]
> The only thing is the `is_project_manager()` check adds a dependency to `main.h`, although imo clarity of intention is probably more important here, unless we should be avoiding this dependency for chaining reasons.

Yeah that's annoying but it's a pre-existing design issue. We should refactor this to keep better track of what kind of Godot instance we're running and have this easy to query in `Engine` (e.g. `Engine::get_run_mode()` that would return an enum value that can be `PROJECT_MANAGER`, `EDITOR`, `RUNTIME`).

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]
Looks like @RandomShaper is in favour and the implementation looks good to me so lets merge!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
