### PR TITLE
The great ARVR to XR rename!

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR renames all the ARVR classes to XR. I've also changed all the class documentation but none of the internationalized stuff. 

This PR purely handles the rename! It doesn't actually make AR or VR work in Godot 4. I'll start slowly looking into that later.

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs a rebase already after reduz's last PR, and clang-format should be applied to the changed files to fix the include order to stay alphabetical. (Or do changes manually as in https://travis-ci.org/github/godotengine/godot/jobs/672556535)

**Comment by BastiaanOlij** [comment]
Dang, I forgot that after reinstalling my laptop clang format hooks aren't there anymore.. Oops.

And @reduz  stop changing stuff :P

**Comment by BastiaanOlij** [comment]
Hope I didn't miss any of the clang stuff...

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
