### PR TITLE
[3.x] Added primary clipboard for Linux

### PR DESCRIPTION
**Pull request by ConteZero**
This commit add support for primary clipboard on Linux to handle text paste with middle mouse button.
This is a backport of [https://github.com/godotengine/godot/pull/53702](https://github.com/godotengine/godot/pull/53702) to 3.x branch.

### CODE REVIEW

**Comment by akien-mga** [comment]
This should also include changes from follow up PRs (at least https://github.com/godotengine/godot/pull/54045, I didn't check if there was any other), otherwise it will exhibit the same issues.

**Comment by ConteZero** [comment]
3.x branch does not have `DisplayServer` `has_feature` method so I've used some `ifdef` to solve https://github.com/godotengine/godot/pull/54045
I think it's the more safe and less invasive way to solve the problem.

**Comment by akien-mga** [comment]
> 3.x branch does not have `DisplayServer` `has_feature` method so I've used some `ifdef` to solve #54045 I think it's the more safe and less invasive way to solve the problem.

There is `OS::has_feature` which I think would be better for this than yet another define.

The command line is pretty long already :)
```
g++ -o platform/x11/os_x11.x11.tools.64.o -c -std=gnu++14 -Wctor-dtor-privacy -Wnon-virtual-dtor -Wnoexcept -Wplacement-new=1 -g3 -ggdb -Wno-error=return-type -pipe -fpie -Wall -Wextra -Wwrite-strings -Wno-unused-parameter -Wno-misleading-indentation -Wshadow-local -Walloc-zero -Wduplicated-branches -Wduplicated-cond -Wstringop-overflow=4 -Wlogical-op -Wattribute-alias=2 -Werror -DDEBUG_ENABLED -DDEV_ENABLED -DNO_EDITOR_SPLASH -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DJOYDEV_ENABLED -DUDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DOPENGL_ENABLED -DGLES_ENABLED -D_FILE_OFFSET_BITS=64 -DPTRCALL_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DHAVE_MNTENT -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/x11 -I. platform/x11/os_x11.cpp
```

**Comment by ConteZero** [comment]
I've removed the DEFINE

**Comment by akien-mga** [comment]
I'm still not sure why it's Linux specific though, as opposed to X11 specific. The implementation for primary clipboard doesn't make a distinction between GNU/Linux and FreeBSD/OpenBSD/NetBSD.

**Comment by ConteZero** [comment]
> I'm still not sure why it's Linux specific though, as opposed to X11 specific. The implementation for primary clipboard doesn't make a distinction between GNU/Linux and FreeBSD/OpenBSD/NetBSD.
> 
> To clarify, the platform is called `x11` on `3.x` and `linuxbsd` on `master` because it's not only a GNU/Linux platform port. The same code (modulo a handful of defines) can compile on other Unix + Freedesktop platforms that support X11 such as several *BSD distributions.

I can only test on Linux so I really don't know if the primary clipboard code works on *BSD.
We can remove the
`#ifdef __linux__`
if some *BSD user can confirm that it works.

**Comment by ConteZero** [comment]
> Searching "OpenBSD X11 primary clipboard" gives a number of results which seem to infer that it does work. If it doesn't work, the X11 API would return an error and hopefully we already handle it gracefully anyway.

OK, I've removed the #ifdef

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
