### PR TITLE
[3.x] Fixed texture animation speed when using random lifetime

### PR DESCRIPTION
**Pull request by RPicster**
3.x version of #55271

### CODE REVIEW

**Comment by akien-mga** [comment]
What about the `tex_*` parameters in CPUParticles2D? They seem to be initialized to 0 too in `3.x`, that's why I thought it might need a deeper dive in the history (and testing) to make sure that everything is working as expected.

**Comment by RPicster** [comment]
> What about the `tex_*` parameters in CPUParticles2D? They seem to be initialized to 0 too in `3.x`, that's why I thought it might need a deeper dive in the history (and testing) to make sure that everything is working as expected.

Oh right! I will take another look, make everything have one style and test it!

**Comment by RPicster** [comment]
I checked the behaviour of all particle types and the change I did in 4.0 had to be reverted for this PR (changing the tex_* values) because the implementation of the behaviour is different here. Changing those values led to a different default behaviour.

The change was reverted from this PR and now the fix focuses on the animation speed only.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
