### PR TITLE
Update file_access_unix.cpp

### PR DESCRIPTION
**Pull request by noahmartinwilliams**
Modified it to open Unix FIFO files.

### CODE REVIEW

**Comment by akien-mga** [comment]
Please amend the commit log to be more explicit, "Update $filename" is not a good title for a commit when viewed in a changelog. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

Could you also be more explicit about the use case for this change?

**Comment by skynet1** [comment]
I was trying to get it to read data from a Linux FIFO. It worked on some initial tests, but now I realize that the way godot buffers files makes it impossible to read live data from a FIFO.

**Comment by aaronfranke** [comment]
@skynet1 Can you address the above feedback and rebase this PR? See [this article](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for information on PR workflow.

**Comment by akien-mga** [comment]
> I was trying to get it to read data from a Linux FIFO. It worked on some initial tests, but now I realize that the way godot buffers files makes it impossible to read live data from a FIFO.

It sounds like it's not working as expected then, so let's close this for now and re-evaluate if/when this can be made functional. I suggest opening a proposal to document what you're trying to achieve exactly, so that it can possibly be implemented with feedback from contributors who know about Godot file access.

**Pull request closed without merging**
