### PR TITLE
Update ResourceLoaderText::load to not update progress if resources a…

### LINKED ISSUE #41294: Division by 0 in resource_format_text.cpp when opening project
**Godot version:**
4.0.dev.custom_build. 69c81309c

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
When I open project then dividing by float 0(float because there is cast) happens:
```
scene/resources/resource_format_text.cpp:678:33: runtime error: division by zero

```
https://github.com/godotengine/godot/blob/e0ee38b128fa84b8e7db499ead66264ca4ec9c60/scene/resources/resource_format_text.cpp#L677-L679

**Steps to reproduce:**
1. Open minimal project with undefined sanitizer support

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/archive/master.zip

### PR DESCRIPTION
**Pull request by Jlalond**
…re 0

Fixes #41294

### CODE REVIEW

**Comment by akien-mga** [comment]
Search in the file, there's another occurrence.

**Comment by Jlalond** [comment]
@akien-mga sorry about missing those, I blame my lack of coffee (and it being 1 am local). I found two more occurrences and added the check in the if.

**Comment by akien-mga** [comment]
Looks good. Could you squash the commits into one? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).

**Comment by Jlalond** [comment]
@akien-mga squashed

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first contribution :tada:

**Comment by Jlalond** [comment]
Thanks! Looking forward to more

**Pull request merged**
