### PR TITLE
RPCMode refactor, more sync modes

### PR DESCRIPTION
**Pull request by Faless**
All `RPCMode` enums references has been moved to `MultiplayerAPI`.
More RPC mode checks has been moved from `Node` to `MultiplayerAPI`.
Three new `RPCMode`s where added.

As #16733 mentions, some users expected `sync` to behave like `slave` (i.e. only be callable by the network master).
To keep compatibility though, `sync` was left with the current behaviour (like `remote`) and should be deprecated in the future. Three new keywords where added: `remotesync`, `mastersync`, `slavesync`, they behave like their base counterpart (`remote`, `master`, `slave`) but also apply the function/property locally in the caller. @reduz

### CODE REVIEW

**Comment by cart** [comment]
I agree that this new sync behavior is better.  I can see it being much more common than the "remoteSync" case.  Anecdotally, its true for my game.  I've been manually validating senders and its been a pain.

**Comment by mhilbrunner** [comment]
I agree this is an improvement as its the more common (and expected) behaviour.

> I've been manually validating senders

Same. Only remaining question is whether the current behaviour warrants a new keyword (`remotesync`)?
Maybe something more explicit on how it doesn't verify the sender and allows everyone to call it on every peer, both remote and locally? `exposed`?

**Review by mhilbrunner — COMMENTED** [review]
Reviewed it; looks good. Only change I'd make:

Document clearly that `sync` and `slave` are only callable by the node's network master.

I.e., for the `slave` one:
`Used with [method Node.rpc_config] or [method Node.rset_config] to set a method to be called or a property to be changed only on slaves for this node. Analogous to the [code]slave[/code] keyword. Allows calls or property changes only by the node's network master, see [method Node.set_network_master].`

**Comment by cart** [comment]
While I'm guessing its probably less common, there are use cases for "remotesync" (ex: games where the clients + server trust each other).  I think "sync" should be in both terms to help people reason about the behavior.  They are both "send to everyone including myself".  I think it comes down to:
* ```sync``` and ```remotesync```
* ```slavesync``` and ```remotesync```

```slavesync``` and ```remotesync``` has my vote because the behavior is clear.  Especially when compared to their siblings ```slave``` and ```remote```.  Also the symmetry is nice :smile:

**Comment by Faless** [comment]
Probably changing the behaviour of `sync` is not correct actually, as it might unexpectedly break things for people. So using a new keyword is likely better...

**Comment by cart** [comment]
Hmm yeah a breaking change at this point is probably less than ideal.  Maybe deprecate ```sync```, but leave it (with its current behavior) for compatibility.  Then add ```slavesync``` and ```remotesync```?

**Comment by mhilbrunner** [comment]
I would try to not needlessly overcomplicate the GDScript compiler. :P

**Comment by cart** [comment]
yeah i agree that simplicity is important both from an implementation standpoint and a user scenario standpoint.  conceptually i think it makes more sense to have a single label that determines network state.

This has my vote:
```py
remotesync func name(): # runs locally and on all peers
slavesync func name(): # runs locally and on all slaves  (if the caller is master)
mastersync func name(): # runs locally and on master (if the caller is a slave)
sync func name(): # for compatibility. alias for "remotesync" 
# staged for deprecation / not included in learning material. removed next time breaks possible
```

If we leave both sync and remotesync in, I think its important to remove sync as a supported path.  Having multiple ways to do the same thing is confusing for users.

**Comment by mhilbrunner** [comment]
Sounds good. @Faless Thoughts?

**Comment by Faless** [comment]
Updated the PR to keep the old `sync` behaviour for compatibility. New `remotesync` `mastersync` `slavesync` keywords in GDScript (tested), NativeScript and Mono (not tested)

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Reverted due to Mono build issues:
https://i.imgur.com/Hb97mTD.png

**Comment by akien-mga** [comment]
That didn't warrant a revert before opening an issue/giving a chance at fixing the build issue...

**Comment by mhilbrunner** [comment]
sorry, won't be as trigger-happy for revert next time :)

**Comment by Faless** [comment]
Would also be nice to get a text log (why do people make screenshot? Did
they remove the copy button on windows?), I can't read anything due to low
res (at lest on mobile). Will try from desktop ASAP

**Comment by Valentactive** [comment]
> Would also be nice to get a text log (why do people make screenshot? Did
they remove the copy button on windows?), I can't read anything due to low
res (at lest on mobile). Will try from desktop ASAP

@Faless  I was the guy who didn't find that copy button. But what happened to zooming on mobiles? I usually try to open an image in its own tab and then zoom & pan whatever...
Anyway I shared that screenshot on the irc channel while testing the latest commits, I didn't open an issue about it because I know that these things just happen and then are fixed most of the time very fast in Godot. I also didn't expect that your original one got reverted lol

@mhilbrunner You should really consider to act less nervously and maybe just ask people before merging or reverting things. In the last days it's not the first time that you acted too fast. I don't mean to attack you in any way with this, but we could avoid these little situations easily with a little more communication. 

In general I start to believe that when single devs or groups of devs that are known to lead a certain area of the game engine, that we could maybe benefit to have specific branches for bigger changes. And then only merge when things have been tested on the official platform we support here (and in this case also test with Mono support which people can love or hate but it's now official a thing for Godot and people expect it to just work at some point. Sure people already push their changes in their own branch of their fork, but I think having it on the official Godot repo could help for exposure and find testers for those areas. The master branch would of course still be seen as a non stable development branch of course, but maybe less open to weird brakes due to just a new pr that got merged. Smaller changes should of course still be submitted directly for the master branch. It would maybe also help to not lose the overview of the general development of Godot. Just a thought

**Comment by Faless** [comment]
>
> But what happened to zooming on mobiles? I usually try to open an image in
> its own tab and then zoom & pan whatever...
>

It doesn't work on imgur, and it doesn't allow you to (easily) get the
original version.

> In general I start to believe that when single devs or groups of devs that
> are known to lead a certain area of the game engine, that we could maybe
> benefit to have specific branches for bigger changes. And then only merge
> when things have been tested on the official platform we support here
>

People would still not test it, this PR was hanging for a while, but still
remained untested. Why would it be any different if it's on a branch?

> (and in this case also test with Mono support which people can love or
> hate but it's now official a thing for Godot and people expect it to just
> work at some point.
>

It's the master branch, it may occasionally break, but I'll make sure not
to update the mono part at all, and let monoers do it themselves, so I'm
sure not to break anything.

**Comment by Valentactive** [comment]
> It doesn't work on imgur, and it doesn't allow you to (easily) get the
original version.  

Maybe depends on the browser, most of the reddits that I check have people uploading pictures to imgur. It's not really a problem for me to get the original sized picture. :)  
  

> People would still not test it, this PR was hanging for a while, but still
remained untested. Why would it be any different if it's on a branch?  

It's a different way to get exposure and a more clear way of saying that a specific thing is meant to get into master. While PRs are in a state of undefined guarantee if something will get into master or not. Of course people following the discussions on the various channels know those things, but not the ones who come the first time and see only a big list of PRs. The labels help a little, but it's not really a clear picture. Maybe it's just me but I guess the idea to have feature branches might become more attractive with the time, when Godot becomes more complex. We are already leaving that "Godot is only 20 MB" state.  

> It's the master branch, it may occasionally break, but I'll make sure not
to update the mono part at all, and let monoers do it themselves, so I'm
sure not to break anything.  
  
See that's one of those things were I think that a specific branch could help as long as the mono users don't helped out. That's not directly your problem of course, but it would not be that bad if we would merge those bigger changes only after the official platforms (and official scripting languages bindings) have been tested (or at least successfully build). Maybe introduce a policy to create Issues for those branches where general requests can be put like needs testing on language X or platform Y etc. And again for those branches I would only consider the bigger changes like multiplayer architecture, renderer (like for  the initial GLES 3 development) etc. For everything else PRs for master branch would still be the way to go. But again just a thought

**Comment by Faless** [comment]
Most of the official supported platform are tested by CI builds, Mono/C# is
simply not enough stable/easy to build to be included in the continuous
integration.

Before PRing I build for Windows, Linux/X11, Mac, Android, iOS, UWP, HTML5,
server platform and (for library changes) FreeBSD and OpenBSD.

Keep in mind that I do this in my spare time which is very limited because
need a job to pay my bills.

I even tried to get a Mono build, installed the MSBuild spyware, the whole
.Net/Mono bloatware (3+GiB) but couldn't get it to work.

When it becomes stable, and included in CI builds (you are welcome to
contribute in that sense) these breakage will simply go away.

**Comment by vnen** [comment]
> Maybe it's just me but I guess the idea to have feature branches might become more attractive with the time, when Godot becomes more complex. We are already leaving that "Godot is only 20 MB" state.

In the ideal scenario, yes: we would have feature branches and people would test them and it would be merged when ready. In the real world: nobody tests even PRs, things are only discovered to be breaking after they get merged (feature branches would be even more hidden than PRs). Single devs can only test so much. I mean, reduz actually add a lot of bugs alongside the new features, but it's easy to let the community test in the master branch than he alone spend a lot of time testing it.

At least for now it's easy to merge when the PR is complete and if it fails for someone we add follow-up fixes. Especially for regular contributors, we know they stay around to fix potential issues and regressions. Maybe @mhilbrunner was a little to quick to merge some things, but in general we are quite strict about new features anyway.

**Comment by akien-mga** [comment]
The merge was fine, and a compiler error in the master branch for a configuration not tested by the CI (we can't tested everything, there are just too many possible combinations) is fine too. It's just the revert which was unnecessary, @Faless or someone else would have provided a fix within a few hours.

But anyway, what's done is done and the new PR should be good to merge :)

**Comment by Valentactive** [comment]
> Most of the official supported platform are tested by CI builds, Mono/C# is
simply not enough stable/easy to build to be included in the continuous
integration.

> Before PRing I build for Windows, Linux/X11, Mac, Android, iOS, UWP, HTML5,
server platform and (for library changes) FreeBSD and OpenBSD.

> Keep in mind that I do this in my spare time which is very limited because I
need a job to pay my bills.

@Faless I know that you are one of those that really test things, but not everyone does that and I also don't pretend it, so your comment about doing it only in your spare time because you need to pay your bills is not needed here really. People doing things here on their spare time should not be an excuse to not overthink changes in how we can improve the usage of GitHub.   

> I even tried to get a Mono build, installed the MSBuild spyware, the whole
.Net/Mono bloatware (3+GiB) but couldn't get it to work.

> When it becomes stable, and included in CI builds (you are welcome to
contribute in that sense) these breakage will simply go away.

The "spyware" is the only way of building Mono, in general a good advice is to not get too personal about software on GitHub (and also about people not finding a copy button ;) ). Building Mono is problematic on multiple Linux distros that's right and known (I built it on Manjaro/Arch Linux recently though). The problem is that the CI solution has an older Ubuntu version and that Ubuntu version uses an older Mono version (if at all). I don't know what I can do about it if it's just simply not available there. And letting it download and install mono from a PPA should not be an option I guess. 

---

> In the ideal scenario, yes: we would have feature branches and people would test them and it would be merged when ready. In the real world: nobody tests even PRs, things are only discovered to be breaking after they get merged (feature branches would be even more hidden than PRs). Single devs can only test so much. I mean, reduz actually add a lot of bugs alongside the new features, but it's easy to let the community test in the master branch than he alone spend a lot of time testing it.  

@vnen That's why I propose to introduce a rule about creating also an accompanying issue for those kind of PRs that can be predicted to introduce potential breaks on specific platforms (and/or official scripting languages where especially Mono will always be a case for itself when introducing new stuff). One could request testing needed for it etc. Right now the problem is exposure of it. For example so many people don't even knew about bullet physics progress for example, only a few tested when it was still in development. The problem there was that people just don't knew about it. Other projects make use of feature branches and people look more regularly into those bigger topics due to curiosity or general interest in something. Of course I don't say that whenever someone comes with a bigger change or a big new feature that this person should gain merge rights etc. But a little more communication between pr developers and maintainers here could help. It was just a thought at the end, I don't pretend anything I just make my thoughts. I also think about how the user base will grow once for instance the C# support is officially announced "stable" and with export support etc. I think we underestimate here the potential new users that could bring massive amounts of PRs. And then it could become very chaotic (it actually already happens that some PRs are lost completely out of sight at some point). 


> At least for now it's easy to merge when the PR is complete and if it fails for someone we add follow-up fixes. Especially for regular contributors, we know they stay around to fix potential issues and regressions. Maybe @mhilbrunner was a little to quick to merge some things, but in general we are quite strict about new features anyway.  

Just in case you guys got that wrong: I'm not angry at mhilbrunner or by the build error itself (that's why I did not even think about creating an issue because I know how things work here usually don't worry). But well it would be nice if every one with merge rights behaves the same way. I mean why do we have PR Review meetings? Of course small fixes can be merged without having to ask others, but when a new feature is introduced or radically changed a more strict behavior would be appreciated. 

> The merge was fine, and a compiler error in the master branch for a configuration not tested by the CI (we can't tested everything, there are just too many possible combinations) is fine too. It's just the revert which was unnecessary, @Faless or someone else would have provided a fix within a few hours.

> But anyway, what's done is done and the new PR should be good to merge :)  

@akien-mga especially since we actually don't have support for that configuration we should let first people test if it builds or works with Mono too (at least builds, everything else can be debugged or fixed afterwards and I really only mean bigger changes not small PRs). I mean the mono configuration will become popular at some point, as you can imagine a lot of C# devs could come into Godot once we say officially that C# is now stable. I don't know if continuing to treat C# like a second (or third) citizen should continue to be ok in that sense. People could also assume that C# was only introduced to just take away users from other engines who support it. The personal stand of single ones about C# (and Microsoft) should not be an excuse for not thinking about how to improve the situation. If we put C# as an official supported language on the documentation these kind of critique will just be a logic consequence. I just wanted to get this out before people start to get really pissed off about these things.

**Comment by Faless** [comment]
> The "spyware" is the only way of building Mono, in general a good advice is to not get too personal about software on GitHub

I know it's the only way, and sorry but I do get personal on software that spies on me, violates my rights and is forced upon me.

> Building Mono is problematic on multiple Linux distros that's right and known

And that alone shows how much C#/Mono is not a good multi platform choice or at least not ready enough to be considered stable.

> we should let first people test if it builds or works with Mono too

Yeah, but that would mean that there are people that are actually willing to do that. and I'm glad you are.
A good idea might be creating a (public) group of Mono-enabled users, who are willing to test, that can be tagged in PRs (at least the one that touches Mono).
Than again there might be cases where even if not touching the `modules/mono` part other side effects may cause the Mono build to fail.

In the end, I really think the only way of fixing this is by including it in the CI builds, and that C# cannot be considered officially stable until we have that.

**Comment by Valentactive** [comment]
> I know it's the only way, and sorry but I do get personal on software that spies on me, violates my rights and is forced upon me.  

Listen privately I have also my opinion on these things and I share your concern (I am always on Linux and only boot up Windows once every 2-3 month or so privately). But this doesn't matter here as long as it's the only way to use build and use Mono. You are free to completely ignore the existence of Mono but your opinion won't stop people using it.

> And that alone shows how much C#/Mono is not a good multi platform choice or at least not ready enough to be considered stable.  

If you mean specifically for Godot right now in this moment, you're right else everything else I don't agree. On one side there is our actual non stable Mono support, on the other side there's the reality that Mono is considered a very stable thing by a lot of companies around the world (and not only kids creating games but also developers using it in daily business software development). It's ok to not like it, but saying that it's not a good multi platform choice is a little far away from reality. But I will stop the discussion here about C# and Mono itself, I don't need to convince you to get a little more positive view on this. I don't care really...

> Yeah, but that would mean that there are people that are actually willing to do that. and I'm glad you are.
A good idea might be creating a (public) group of Mono-enabled users, who are willing to test, that can be tagged in PRs (at least the one that touches Mono).
Than again there might be cases where even if not touching the modules/mono part other side effects may cause the Mono build to fail.  

I honestly think we could find a few Mono users that would be willing to do that. People have often really a wrong picture about C# users just because they don't work on native level directly. 

> In the end, I really think the only way of fixing this is by including it in the CI builds, and that C# cannot be considered officially stable until we have that.  

Maybe, but would not expect to people share that view, if single ones successfully build and use it, CI should not be taken as an status indicator for the general status of the Mono support in Godot. CI can by nature only be a temporary indication not a general one.

**Comment by mhilbrunner** [comment]
This is getting a little offtopic. :)

@Valentactive In general I agree, so mea culpa. 

My (maybe flawed) reasoning (wall of text):

For merging:
- @Faless and I are basically the networking maintainers. We're doing this in our spare time. We'd both be happy if more people stepped up to help, even if it only was for testing. This is not a breaking change, we agreed on it, CI build fine, I tested it (multiple times, on multiple platforms) and it worked.
- Faless wanted me to wait a few more days to merge this to give people a chance during the weekend to test it. As far as I can tell, nobody did.
- The PR was open for testing nearly 2 weeks. So I merged it after the weekend.

For reverting:
- I read your report that it breaks the Mono build
- I had no time to look into it, as I was right on the go to be away from computers for around 1.5-2 days due to IRL
- I had in the back of my mind that both faless *and* neikeq (for Mono) were quite busy currently IRL, so I was not sure if I could expect a fast fix *or* somebody else would step up to do it
- Note Visual Scripting in master is broken for days now, if not weeks. As C# only has a few contributors too, I wasn't certain this would be fixed any faster if faless didn't do it

I didn't want to be the one responsible for breaking Mono on master for possibly such a long time as VS. So I reverted the change.

I *should* have tested the change on a Mono build, and I *should* have tried to reach faless to see how fast he would be able to fix it. Learned the lesson, will do so the next time, and will be more hesitant to revert something in the future.

Also please keep in mind that yes I'm new, and yes this was the second merge with a problem from me recently, but I also merged *a lot* of PRs. Most were fine. Look at the commit log for the last weeks, I spent a lot of my free time on this to help out Akien.

And I would absolutely prefer everything to be merged in PR meetings, but thats just not gonna happen. We're now at 150+ open PRs for weeks, if not months.

Again: mea culpa!

**Comment by Valentactive** [comment]
> Yes yes, I've been hearing this since ages, C# is multiplatform and many companies use it.
So multiplatform that on Linux (by your own admission) there are many known build problems.
Even getting a simple build or installing the latest SDK is problematic.
So multiplatform that on Unix systems you can't decently handle signals, that companies like Unity decided to make IL2CPP to convert C# code to CPP, that most C# programs can only run on Windows, or only build with MS.Net or only build with Mono (but almost never both) and when you have cross platform tools (e.g. xamarin) they do not work on Linux.
Sounds like a mature multiplatform environment.  

@Faless  I really don't want to waste any time on this topic anymore, it doesn't make much sense...but anyway I answered you because you criticized "C#/Mono" and not just "Mono". 
- Building on Linux is problematic in the same sense like other projects of that sizes. But it also is a problem with single distros and their way to do things. We can't really expect from the guys working on Mono to provide support for all Linux distros that would be insane. Especially since the Linux community has always been very negative about Mono...given that the general market share of Linux is already small on Desktop it's normal that they focus just on a few distros that are known to work.  Then since it's an open source project (and now even more permissive than before) the open source community can help with that if they really want.  
- You are mixing things up in a way that doesn't make much sense. First of all Mono is only one implementation of the C# language and a default set of libraries that one can use.  
- If there are problems with signals on Unix systems that is an implementation problem and not C# as a language. We don't use C# in Godot to write system level applications, we bind it to what it's already there in Godot. For consideration about for or against a programming language to be used as a scripting language, one should also consider the use case. For doing what most of game developer do, C# is not a bad candidate.  
- The fact that Unity decided to develop IL2CPP is none of our business, but I tend to say that they have all the right to do so. They develop a commercial product which makes of C# a very important part in it. It could have come differently they offered also other scripting languages and who know if the bigger part of the community would have used their own JavaScript derivate maybe they would have abandon Mono completely today. But again I don't see anything wrong with it. They try to find ways to get better performance on the platforms they aim to support and if IL2CPP sounds like a solution for them then so be it. The same could be said about the recent work on static typing for GDScript and who knows maybe this will be more attractive for a dev to come up with something similar to compile GDScript to native with the help of LLVM etc. It's ironic how such an open source project can have so many people with a closed mindset.  
- I just woke up of a very weird dream, It seemed like in that dream I used C# for the past 13 years to do exactly what you said was not possible. In this dream I coded so many applications and they seemed to just work when executing on a different OS. Now back to seriousness and sorry but I use C# since 2005 long before I even knew about Unity and I did that from the start on both Windows and Linux. I agree on Linux the experience has not always been the best, but Mono of today is at a very different state. 
You are mixing again things up here. Xamarin was/is a company and offered dedicated stuff for mobile development with C# under the same name. Since it was started by the same guy that originally started Mono (and GNOME btw too, so one that knows a few things about Linux) of course it was totally natural that a part of that development flowed back into the open source Mono stuff. That now even increased since Microsoft bought Xamarin and really a lot of good stuff was put under very permissive open source licenses. 
-  When you start any project in any programming language it's your job to choose wisely which libraries to use if you aim for cross-platform support on the big platforms. Their support for the old "Windows.Forms" for instance was always clearly marked as experimental or not ready or on par with the Windows counterpart. If you start a project in C++ for instance you also choose Qt, GTK+ (or well in that case probably gtkmm) and not MFC.WPF etc. I don't know how much time you used C# (if at all) but I never had big problems to code applications and run them on both Windows and Linux (can't talk about macOS as I never possessed an Apple device). And even less problems when I developed a console applications (yes C# devs do that do).  Maybe a few changes here and there to let it fit better (and make use of some of the Unix specific stuff that one can find in Mono), but honestly what are we talking about? Isn't that the job of a developer to just do some work too in that sense? 
Do we need the Xamarin stuff for Godot?? As a scripting language C# has all one can ask. I don't know what people expect from it seriously. It's not like GDScript adds something that C# would not be capable of except the tight integration that GDScript has by nature with Godot. 

---

@mhilbrunner You did not need to justify anything really. Again I did not even have a problem with the status of not building with Mono support. I just shared a random thought while I was in the IRC channel. I made the mistake of writing about what I think would improve the situation here on GitHub for Godot. It must felt like an attack on you, but that was really not my intention (people who know me from IRC should know that I'm really not that kind of guy), it was just a recurring thought that I have since a longer time and it just happened that this little story here lit it up again for me. Maybe my wording here is not the best, I repeat I don't pretend anything, I just shared a thought. Since I'm almost every day in the IRC channel (also if often very silent) I have seen what you have done. It's amazing to see so much dedication, don't worry :D 

To both of you **Faless** and **mhilbrunner** congrats and thanks for your work you did here, I must have sound really negative so far. Just in case it was not clear I appreciate your work a lot and am happy that Godot has so passionate people in its community. I tend to share from time to time my concerns (and I can't stand when in my opinion something is just not the whole truth) but then I usually turn silent again. And I guess I will be even more silent in future as long as we don't have a clear code of conduct here. One very important aspect for me would also be to not allow public bashing of company x, technology y etc. That's something that belongs in a chatroom not necessary under PRs or Issues on GitHub. It's not very welcoming if popular contributors here feel free to express in certain ways about technologies (or in this case more specifically programming language and its implementation) that is used officially in Godot. And apart from that we should stay on topic (me included to be the first one having failed in it). I initially only wanted to explain why that screenshot was made and shared in the IRC channel and that I did not create an issue on purpose. And later confirm that buiding works again with Mono. My mistake was then to share my general thought about what could be improved here. Lesson learned for me I guess :)

**Comment by mhilbrunner** [comment]
@Valentactive No worries, didn't feel like an attack at all. :) All good.

...I won't get into the C# discussion you both have going. Not going to touch that with a 10ft pole :P

**Pull request merged**
