### PR TITLE
Zoom in and out using mouse scroll wheel

### LINKED ISSUE #6168: Zoom visual script editor via mouse scrolling
Linux Mint 17.3 - Godot version: 2.2 alpha (Aug 14th)

This is a feature request for the visual scripting system: the mouse scroll wheel will increase the zoom level as it is scrolled forward. When scrolled backward it should zoom out at the same rate. Would that not be ideal? It currently does nothing and it's what I expected it to do when I first tried it out. Thanks!

### PR DESCRIPTION
**Pull request by djrm**
it does what the buttons do but using the scroll wheel, closes #6168

### CODE REVIEW

**Comment by reduz** [comment]
I purposedly removed this because it looks awful, until we implement proper
multisampled AA there is no hope of implementing proper zoom.

**Comment by djrm** [comment]
but this is just the same as the buttons so i guess this has no problems, since the functionality is already there. this is just simpler to use, later when the implementation changes it will work for both modes, buttons and scroll wheel

**Comment by reduz** [comment]
buttons are there to discourage zooming unless you really need it :)

**Comment by reduz** [comment]
I think also a minimap should reduce the need for zooming

**Comment by djrm** [comment]
well i agree zoomed graph looks awful, also i posted my suggestion about the minimap on an issue

**Pull request closed without merging**
