### PR TITLE
Fix : jpgd.cpp Added Additional check to `half_image_x_size` and `half_image_y_size` so that it's values wont be Negative[-1].

### LINKED ISSUE #42363: Godot crashes when importing 1x1 pixel JPEG image using YCbCr and 2x2 sampling factor
**Godot version:**
Godot 3.2.3

**OS/device including version:**
- Device: *Acer Aspire A315-33*
- OS: *Windows 10 64-bit*
- CPU: *Intel(R) Celeron(R) N3060 @ 1.60 GHz*
- GPU: *Intel HD Graphics 400*
- RAM: *4GB*

**Issue description:**
I was following an answer on the [Godot forum about making a coloured rectangle](https://godotengine.org/qa/59423/best-way-to-make-a-colored-squares-for-in-game-use), and using Microsoft Paint, I made a white 1x1 pixel JPEG image and placed it in my project's `.\Images\` directory. When I opened Godot to rescan for assets, Godot crashed as it was importing `.\Images\Background.jpg`.

**Steps to reproduce:**
1. Create an empty Godot project.
2. In the small File Explorer view on the bottom left, right-click on `res://` and create a folder called `Scenes`.
3. Open MS Paint.
4. Go to `File -> Preferences` .
5. Change both width and height to 1 pixel.
6. Tap on the white colour in the colour palette.
7. Tap on the single pixel (may need to zoom in).
8. Go to `File -> Save As... -> JPEG image`.
9. Go to the project's directory and make a new folder called `Images`.
10. Save the JPEG image as `Background.jpeg` or `Background.jpg`.
11. Open Godot and let Godot scan the project's assets.
12. The crash occurs when scanning `Background.jpeg`.

**Minimal reproduction project:**
I've added the original project.

[ForEx Simulator.zip](https://github.com/godotengine/godot/files/5288023/ForEx.Simulator.zip)

### PR DESCRIPTION
**Pull request by Bhu1-V**
evidence 1 

as u can see this was the image in MRP which was successfully imported and u can also see the size of the image is 1 x 1.
also tested with other 1x1 jpg images working just fine. I made changes only on [H2V2ConvertFiltered() ](https://github.com/godotengine/godot/blob/30b6db99a99a94c64d906c1b828ff44f79a1bc75/thirdparty/jpeg-compressor/jpgd.cpp#L1888) Function Since the problem was see there only. But i will try to Replicate the problem with different sampling and see whether any more changes are needed.   FIX : #42363

### CODE REVIEW

**Comment by pWNn1sher** [comment]
Just Found out that i need to check value of https://github.com/godotengine/godot/blob/30b6db99a99a94c64d906c1b828ff44f79a1bc75/thirdparty/jpeg-compressor/jpgd.cpp#L1672 in Function   [`H1V2ConvertFiltered()`](https://github.com/godotengine/godot/blob/30b6db99a99a94c64d906c1b828ff44f79a1bc75/thirdparty/jpeg-compressor/jpgd.cpp#L1759) and aslo value of https://github.com/godotengine/godot/blob/30b6db99a99a94c64d906c1b828ff44f79a1bc75/thirdparty/jpeg-compressor/jpgd.cpp#L1765 [`H2V1ConvertFiltered()`](https://github.com/godotengine/godot/blob/30b6db99a99a94c64d906c1b828ff44f79a1bc75/thirdparty/jpeg-compressor/jpgd.cpp#L1666) ,  to be non - negative to not crash.

**Comment by pWNn1sher** [comment]
After the last Commit we can fully use 1 x 1 pixel jpg images of any sub-sampling without Engine crash.

EVIDENCE 💯 
here are some jpg images of different sub-sampling imported into Engine.
H1V1 : 👍 
image
H1V2 : 👍 
image
H2V1 : 👍 
image
H2V2 : 👍 
image

TESTED - PROJECT :
[gdtest.zip](https://github.com/godotengine/godot/files/5505479/gdtest.zip)

**Comment by akien-mga** [comment]
The fix looks fine, but there are a few changes that should be made before it's merged:

- Commits should be squashed into one, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).
- The commit message for the resulting commit should be amended to be clearer about what the commit does. "Update filename" is not a good message as it doesn't say what the update does. See [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) for tips on writing good commit messages.
- The four changed lines use inconsistent style and parentheses, they should be fixed to all be exactly the same. There's no reason for them to differ.

Finally, this is a thirdparty library so it would be best if we can get this patch merged upstream, so that all users of this library can benefit from the fix. This can also lead to writing a better fix with feedback from the original author of this code.

Could you make a PR to https://github.com/richgel999/jpeg-compressor with those fixes?

**Comment by akien-mga** [comment]
Superseded by #43441.

**Pull request closed without merging**
