### PR TITLE
Rename `AStar.get_points()` to `AStar.get_point_ids()` for clarity

### LINKED ISSUE #3515: AStar (& AStar2D) get_points() description inaccurate, needs clarifying text.
**Your Godot version:**
3.2.1

**Issue description:**
AStar docs need to be clarified, current text is misleading.

Under the method: get_points(), description should be changed from:
"Returns an array of all points." to:
"Returns an array of all point IDs."

The reason for the change is that elsewhere in that document a "point" is defined as having: an ID, position and weight.  However, get_points() only returns an array of IDs.

Both AStar and AStar2D documentation for get_points() should be updated with the correct description.

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_astar.html
https://docs.godotengine.org/en/stable/classes/class_astar2d.html

### PR DESCRIPTION
**Pull request by Calinou**
The same has been done for AStar2D as well.

If desired, I could open a PR against the `3.2` branch to update only the method descriptions.

This closes https://github.com/godotengine/godot-docs/issues/3515.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good to me. Needs a rebase, otherwise no objection to merging.

**Review by mhilbrunner — APPROVED** [review]
Approved in todays PR meeting

**Comment by akien-mga** [comment]
Thanks!

**Comment by eltharionx** [comment]
Thank you!

**Pull request merged**
