### PR TITLE
Improve doxygen output

### PR DESCRIPTION
**Pull request by sondredl**
doxygen configuration updates to improve graphical output of doxygen documentation

### CODE REVIEW

**Comment by fire** [comment]
As far as I know Godot Engine doesn't use doxygen?

**Comment by sondredl** [comment]
@fire there is a doxygen configuration file that can be used to generate documentation if you want by
cd doc/ && make doxygen
so it is at least supported. I use it and i value it greatly when trying to get to know a new large codebase.
The changes i propose improves the visual graph output of the doxygen documentation, should you choose to generate it :)

**Comment by sondredl** [comment]
@fire do i need to do anything to get an approval on the pull request?

**Comment by fire** [comment]
I am not familiar with the doxygen workflow but since its non load bearing we can try merging it assuming it works flow you.

Try sending us some photos :D

**Review by fire — APPROVED** [review]
@skyace65 @Repiteo I think it's fine, but thoughts? We use spinx? I think in the godot engine docs website.

**Comment by sondredl** [comment]
it seems i do not have write access to the repository. can i get write access to the repository so i can merge the pr?

**Comment by AThousandShips** [comment]
The production team is on charge of merging PRs, you don't have to worry about it yourself

**Comment by Repiteo** [comment]
Oh wow, that workflow is just outright unused atm. It *seems* to work when I run it locally, but it also outputs a **TON** of warnings so I can't speak for how feature-complete the end result truly is

This PR doesn't do anything *wrong* per se, but it's improving an area that looks untouched since… 2015?? It's kinda wild to that there's been a single Makefile chilling in the repo all this time

**Comment by adamscott** [comment]
Closing following https://github.com/godotengine/godot/pull/98881#issuecomment-2465101229

**Pull request closed without merging**
