### PR TITLE
Convert the logo's text outlines into paths

### PR DESCRIPTION
**Pull request by deralmas**
This avoids rendering issues with ThorVG and other renderers (which
don't support the `paint-order` property) at a slight cost in file size.

This approach has already been used by the main icon.

Note that for whatever reason the property's still there but that shouldn't matter anymore.

# Outdated Editor comparison

same editor instance and version, top is the logo asset before and bottom is after this PR:
comparison image portraying a broken logo on top and a properly rendered one on the bottom

**Update:** the issue around the i's dot in the above photo has been fixed.

### CODE REVIEW

**Comment by YuriSizov** [comment]
To be clear, this logo is not used by the engine anywhere. It's just an image that we add to `README.md`.

**Comment by fire** [comment]
image

I wonder what's the other difference, but it is an improvement.

**Review by fire — APPROVED** [review]
As far as I can tell it looks ok.

Needs a production team signoff.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
