### PR TITLE
Added min/max blending modes

### PR DESCRIPTION
**Pull request by aburg**
Added min/max blending modes to canvas item shaders for advanced shader trickery.

### CODE REVIEW

**Comment by Calinou** [comment]
This sounds nice, can you give some example use cases? :slightly_smiling_face:

**Comment by aburg** [comment]
> This sounds nice, can you give some example use cases? slightly_smiling_face

I am using this for visualization of distance fields. (The render mode "blend_min" can be used to combine/overlay distance fields and "blend_max" can be used to cut holes into them. See also: http://jcgt.org/published/0003/04/01/)

Also I found someone using GL_MIN for an effect where blended colors produce a darkened color:
https://stackoverflow.com/questions/8800100/in-ios-opengl-how-can-one-create-a-blend-mode-similar-to-kcgblendmodedarken

> Also, this will likely have to be reimplemented for the Vulkan renderer once it's rebased into the `master` branch.

Yes, plus I also just realized that GL_MAX und GL_MIN are not supported on Android and iPhone. (That is why the Travis CI build failed for these platforms...)

Perhaps this is the reason why these modes were not supported in the first place?! :-(
I'll look into a workaround or at least a way to have these changes compile on Android/iPhone...

**Comment by Calinou** [comment]
We generally don't add rendering features that can only be used on desktop platforms, as we don't want users to suddenly find out they can't use given features on mobile devices.

**Comment by aburg** [comment]
> Currently, we usually don't add rendering features that can only be used on desktop platforms, as we don't want users to suddenly find out they can't use given features on mobile devices.

Ok, I have no idea how to accomplish this on the embedded systems. Closing, sorry for wasting your time. :-/

**Comment by reduz** [comment]
This would be nice for 4.0 actually

**Comment by Calinou** [comment]
For the record, this has been reopened as a proposal: https://github.com/godotengine/godot-proposals/issues/2621

**Comment by aburg** [comment]
Awesome, I am kind of holding on waiting for 4.0 and hoping I (or someone else) can get this in there.

**Pull request closed without merging**
