### PR TITLE
new assets folder

### PR DESCRIPTION
**Pull request by djrm**
Moved all the svgs to godot/assets, the idea is to make this folder a place to store sources for icons, theme elements and other stuff, and then export them from this folder.

### CODE REVIEW

**Comment by reduz** [comment]
As mentioned before, please don't merge them and leave them in their
respective locations, they need to be built separatedly

**Comment by djrm** [comment]
This does not modify current pngs, only the source svgs which then gets exported to their respective folders, the assets folders is just a centralized place for svgs, in order to provide a common mechanism to export them

**Comment by djrm** [comment]
found a better way

**Comment by akien-mga** [comment]
Yeah the root folder is already pretty cluttered with a ton of folders, I'd prefer not to add yet another one.

**Pull request closed without merging**
