### PR TITLE
Allow FSR to downscale

### LINKED ISSUE #8086: Allow FSR 2 to downscale from a higher internal resolution
### Describe the project you are working on

A 3D game (demo) that uses FSR 2 as its only antialiasing and scaling solution.

### Describe the problem or limitation you are having in your project

Right now, FSR 2 only supports upscaling from a lower internal resolution, or being used as a TAA alternative by setting the render scale to 1.0. If the render scale goes even slightly above 1.0 (i.e. 1.01 and above), Godot turns FSR 2 off and falls back to native TAA + bilinear downscaling.

The problem is that despite the miniscule resolution difference between 1.00 and 1.01, the visual difference caused by FSR 2 being automatically turned off is significant.

https://github.com/godotengine/godot-proposals/assets/39361911/bac1685e-3bd2-41f0-8609-097dd742acaf

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If possible, allow FSR 2 to remain enabled even if the internal resolution scale is set above 1.0. Even if you won't see significant visual improvement by downscaling from a higher internal resolution (due to the nature of FSR 2), and even if the performance cost is significant, the ability to keep the "look and feel" of your game consistent regardless of internal resolution is very useful.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

If the FSR 2 code already has the capability to downscale, simply remove the "above 1.0 not allowed" limitation from the settings, and API.

If FSR 2 cannot downscale, then render the game at the higher internal resolution with native FSR 2 antialiasing, then bilinear downscale the render to the output resolution.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

A workaround for this would be to use NVIDIA DSR or AMD VSR to fake a higher resolution, then set FSR 2 scaling to 1.0 in Godot. The driver then takes care of downscaling to the native monitor resolution.

Obviously this is a very roundabout and not user friendly way of achieving higher than native FSR 2 antialiasing. Not to mention the resolutions available in DSR or VSR tend to be limited.

### Is there a reason why this should be core and not an add-on in the asset library?

It concerns a core rendering feature.

### PR DESCRIPTION
**Pull request by Jamsers**
Closes https://github.com/godotengine/godot-proposals/issues/8086.

Removes the limitation on FSR not being allowed to downscale from higher resolutions.

From my testing:

FSR benefits surprisingly from being allowed to downscale, but that's to be expected perhaps since fundamentally FSR is just a spatial upscaler.

FSR 2 doesn't see as much benefit in static, unmoving scenes. To be expected perhaps due to its temporal superscaler nature. The benefits are primarily in clarity while in motion and the reduction of disocclusion artifacts. (when scale is set to 2.0, disocclusion artifacts are almost completely gone)

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @DarioSamo @Calinou

**Review by Stronkkey — APPROVED** [review]
Looks good but why wasn't downsampling supported previously? Also, [please rebase your commits.](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by Jamsers** [comment]
Rebased my commits.

>why wasn't downsampling supported previously

[Concerns about oversharpening](https://github.com/godotengine/godot-proposals/issues/8086#issuecomment-1760129734). However anyone choosing to downsample will be able reduce or remove FSR sharpening in the project settings, and sometimes maybe a user actually does want the oversharpened look - they should be able to have it.

**Comment by DarioSamo** [comment]
While I did stick to following the behavior FSR1 had in the existing codebase, I'm unsure as to whether this is a valid use case. I noticed it works as a happy accident, but it definitely doesn't in solutions like DLSS or XeSS (causes visible corruption even). While it's true we don't have either of those, this is not going to be true for every upscaler out there, so I'm mostly wary of this due to UX concerns.

That said I feel the resolution scale options above 1.0 aren't exactly working as intended, as I haven't noticed the existence of downsampling passes to properly account for it. It sounds like we'd be better served by doing something like maintaining FSR2 at native resolution when going above 1.0 (e.g. pretend input and display resolution is the same) and using something like [AMD FidelityFX Single Pass Downsampler](https://gpuopen.com/fidelityfx-spd/) to downscale the result.

If we can find anything in FSR2 that showcases this behavior is expected in the API I think we're fine to do it, but I've been unable to find anything about it.

**Comment by Jamsers** [comment]
For me the most important usage of this feature is keeping the look of FSR 2 even when you slightly overshoot the scale.

https://github.com/godotengine/godot-proposals/assets/39361911/bac1685e-3bd2-41f0-8609-097dd742acaf

Honestly, I doubt most people will actually want to use FSR 2 as a downsampler in earnest.

Perhaps I could put the `WARN_PRINT_ONCE` back and replace the warning with `"FSR 3D resolution scaling is not designed for downsampling. Consider using bilinear 3D resolution scaling."`? So that we can keep this as an interim solution until proper FSR downscaling can be added. (In case AMD confirms that downscaling is not supported)

**Comment by DarioSamo** [comment]
> For me the most important usage of this feature is keeping the look of FSR 2 even when you slightly overshoot the scale.

That's a pretty real concern when I saw how it was handled. I think there's two solutions here:
- From GDScript side you can definitely just clamp it to 1.0.
- The comparison in C++ should check with a tolerance (e.g. (1.0 + 1e-6f)) instead of 1.0 directly.

**Comment by Calinou** [comment]
> as I haven't noticed the existence of downsampling passes to properly account for it.

We indeed lack a dedicated downsampling shader. We should eventually have one for better quality for Movie Maker mode recordings. This would allow using resolution scales above 2.0 without graininess, but VRAM utilization is an issue at such high resolution scales anyway (temporal supersampling is preferable to spatial supersampling for this reason).

**Comment by Jamsers** [comment]
>From GDScript side you can definitely just clamp it to 1.0.

This was my first thought as well, but it felt like "lying" to the user in a sense - if the user selects 1440p, they're gonna expect 1440p, even if their monitor is only 1080p. Similar to how people wanting higher quality videos on Youtube will select 1440p even if they only have 1080p monitors.

While native FSR 2 antialiasing is currently very good, there are still artifacts here and there due to its TAA nature (mostly some blurriness while in motion and some disocclusion artifacts), and even with this potentially unintended use case, a higher internal resolution (when setting higher scaling with this PR) does alleviate these artifacts. So I feel there is still validity in allowing this PR as an interim solution, until proper downscale behavior as you've described -

>maintaining FSR2 at native resolution when going above 1.0 (e.g. pretend input and display resolution is the same) and using something like [AMD FidelityFX Single Pass Downsampler](https://gpuopen.com/fidelityfx-spd/) to downscale the result

\- is implemented. Proper downscaling should definitely be implemented eventually though, it's the behavior you'd intuitively expect when downscaling.

>I haven't noticed the existence of downsampling passes to properly account for it

From what I can tell with this PR it is indeed actually not downsampling at all, at least not in the way a user would normally expect. Rather, the extra pixels due to the higher internal resolution seem to be properly used, but the resolve itself is still at native. But this makes sense, because this is exactly how FSR 2 works in the opposite direction - when using lower internal resolutions, the resolve is obviously at native - that's the appeal of this tech in the first place after all.

**Comment by Calinou** [comment]
> Rather, the extra pixels due to the higher internal resolution seem to be properly used, but the resolve itself is still at native.

The hardware is able to do box downsampling up to 2×2 with a smooth result that doesn't exhibit graininess (however, it's not always sharp at non-integer scale factors). At greater scales, mipmap generation or a dedicated downsampling shader is required.

**Comment by Jamsers** [comment]
I meant the FSR 2 resolve itself is at native - I think with the current behavior with this PR, there is no actual downsampling happening when you set the scaling above 1.0. You're just feeding more pixels into the FSR 2 machine than you'd normally be able to. Compared to what happens when you use TAA + bilinear scaling for example: an TAA'd image at 1440p is rendered, then bilinear downscaled to 1080p.

**Comment by Calinou** [comment]
Tested locally, it works as expected. However, the result with FSR2 and a 2.0 scale factor is generally more aliased than TAA with a 2.0 scale factor:

## Bilinear

### Scale 1.0

Screenshot_20231013_231253

### Scale 2.0

Screenshot_20231013_231259

## FSR 2.2 (Sharpness = 2.0, lowest)

### Scale 1.0

Screenshot_20231013_231237

### Scale 2.0

Screenshot_20231013_231244

For high-quality rendering, FSR2 with 8× MSAA is likely preferable if you want to minimize aliasing on moving edges. Alternatively, you could [render more frames than will be saved in the video](https://github.com/godotengine/godot-proposals/issues/6543), which will also improve the quality of other effects that converge over several frames (including motion blur once it's implemented)./

**Pull request closed without merging**
