### PR TITLE
Fix threading issues in resource loading

### LINKED ISSUE #66023: Error threaded_load-ing two scenes that inherit from the same scene
### Godot version

4.0beta1

### System information

Windows 10 Home 19044.2006, AMD Radeon RX 580 Series, Driver Version 22.20.19.09-220819a-383490E-AMD-Software-Adrenalin-Edition, Vulkan Clustered

### Issue description

Let's say I have a base scene `scene1.tscn` and two scenes `scene2.tscn` and `scene3.tscn` that inherit from the first. I load_threaded_request them on the same frame and check if they're finished in `_process()` with `load_threaded_get_status()`. `scene2.tscn` loads fine but `scene3.tscn` gives the following error:

```
ERROR: res://scene3.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://scene1.tscn
   at: load (scene/resources/resource_format_text.cpp:486)
ERROR: Failed loading resource: res://scene3.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   at: (core/io/resource_loader.cpp:221)
```

### Steps to reproduce

Run the minimal example in the editor.

main.gd:

```gdscript
extends Node2D

var x = false
var y = false

func _ready():
	var err = ResourceLoader.load_threaded_request("res://scene2.tscn")
	assert(!err)
	err = ResourceLoader.load_threaded_request("res://scene3.tscn")
	assert(!err)

func _process(delta):
	if !x:
		var status = ResourceLoader.load_threaded_get_status("res://scene2.tscn")
		match status:
			0:
				print("invalid resource res://scene2.tscn")
				x = true
			1:
				pass
			2:
				print("error loading res://scene2.tscn")
				x = true
			3:
				print("finished loading res://scene2.tscn")
				var sc2 = ResourceLoader.load_threaded_get("res://scene2.tscn").instantiate()
				sc2.queue_free()
				x = true
	
	if !y:
		var status = ResourceLoader.load_threaded_get_status("res://scene3.tscn")
		match status:
			0:
				print("invalid resource res://scene3.tscn")
				y = true
			1:
				pass
			2:
				print("error loading res://scene3.tscn")
				y = true
			3:
				print("finished loading res://scene3.tscn")
				var sc3 = ResourceLoader.load_threaded_get("res://scene3.tscn").instantiate()
				sc3.queue_free()
				y = true
```

### Minimal reproduction project

[Resource Load Test.zip](https://github.com/godotengine/godot/files/9592946/Resource.Load.Test.zip)

### LINKED ISSUE #71726: ResourceLoader.load_threaded_request fails when called multiple times with overlapping external resources
### Godot version

4.0 beta13 (also tried beta11 and beta12)

### System information

Windows 10

### Issue description

When `ResourceLoader.load_threaded_request` is called multiple times with different resources that share the same external resource I get errors like the following and the loading fails:
```
E 0:00:00:0682   load: res://Scene2.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://LoadedAsResource.gd
  <C++ Source>   scene/resources/resource_format_text.cpp:494 @ load()
E 0:00:00:0683   _load: Failed loading resource: res://Scene2.tscn. Make sure resources have been imported by opening the project in the editor at least once.
  <C++ Error>    Condition "found" is true. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:214 @ _load()
```
NOTE: the errors are in the Debugger tab under Errors and not in the Output tab.

The resources loaded with `ResourceLoader.load_threaded_request` in the repro project are scenes that only have one Node with the same simple script on them. The errors disappear when every one of those scenes gets their own script (just a copy of the script, but different files).

The errors also disappear when I put a little wait in between the load_threaded_request calls (`await get_tree().create_timer(0.1).timeout`).

I couldn't reproduce the errors in an export of the project.

Weirdly enough I also couldn't reproduce the error when I started the editor via `Godot_v4.0-beta13_win64_console.exe`! Only when started directly via `Godot_v4.0-beta13_win64.exe`. And very rarely the error only occurred on the second run of the scene.

### Steps to reproduce

1. Download and extract the repro project
2. Open the godot editor via `Godot_v4.0-beta13_win64.exe` (not the _console.exe!)
3. Open the repro project
4. Run the project (main.tscn)
5. Errors should appear in the Debugger > Error tab in the Editor
6. (when there are no Errors there, re-run the scene)

### Minimal reproduction project

[ResourceLoaderTest.zip](https://github.com/godotengine/godot/files/10465822/ResourceLoaderTest.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
This PR is an alternative to #73623, aiming to fix the same issues spotted there, but in a different way; namely:
- The race condition where the task semaphore has a chance of being destroyed before the other thread can wait on it is solved here by using the sync primitive that can naturally fix the problem, which is a condition variable. In the current implementation, the problem is that a mutex is unlocked and then a semaphore is awaited. Those operations should make an atomic operation, which is precisely what a condition variable does. Therefore `ConditionVariable` is introduced, together with a new flavor of binary mutex needed to be used with it.
- The problem that a load task has been initiated in a non-thready context (regular resource load or load in thread, but with no subthreads) and then involved in load threads created later is solved here by allowing the condition variable (formerly, a semaphore) needed to await on the task to be created lazily. Such approach keeps the current benefit of having one-threaded cases free of having to create and deal with the condition variable.

This needs testing. And I beg a thorough review of this code, since this is slippery ground.

**NOTE:** Given the complex nature of the changes, I'm keeping them in separate commits.

- Fixes #66023.
- Fixes #71726.

### CODE REVIEW

**Comment by RandomShaper** [comment]
@mrTag, would you please test this approach with your game and tell me the outcome?

**Comment by RandomShaper** [comment]
So isn't this in time for 4.0? This PR fixes serious core issues.

**Comment by akien-mga** [comment]
It's a serious core PR with potential for regression too, minutes before RC3 and one week before stable. Are you confident enough in the implementation and is it worth the risk? Can we get @reduz to approve it right now before RC3?

**Comment by RandomShaper** [comment]
It's indeed a double edge sword, and very sharp in both sides. If @reduz could review the changes and confirm they indeed only but fortify the implementation (i.e., I didn't misinterpret the code), I could do some stress testing. Then I'd be confident enough to move forward with this.

**Comment by akien-mga** [comment]
I discussed this briefly with @reduz, he agrees that this kind of changes is needed but it's part of a much bigger work package on thread safety that he wants to discuss with you. So that's definitely more in scope for 4.1 at this stage.

**Comment by mrTag** [comment]
@RandomShaper I just tested our game with this branch and it worked without problems. With the current master branch loading would fail pretty much every time for us (with the "referenced nonexistent resource" error), so that is a pretty good indicator that your version fixes the problem! And it is definitely a cleaner solution than in my pull request, I didn't know about conditionals and their use for cases like this. I'll be using this branch for our game from now on and I'll get back to you when any problems arise. That includes testing it on linux (I only tested it on Windows for now).

And I agree: it is a pretty serious issue. In my experience with the ResourceLoader, load_threaded_request is currently only usable in the simplest of cases (i.e. only one resource at a time). Which is a valid use case, since it enables asynchronous loading of one scene while showing a loading screen. But I completely understand the need for more testing here.

**Review by akien-mga — APPROVED** [review]
Approved by reduz for 4.0:

> **reduz:** I think #73647 is the way to go, I also need to implement condition variables in the thread worker pool
> **Akien:** Alright, so we merge now for 4.0 RC4 and hope it doesn't wreak havoc? and poke Pedro with a Hellrule burning pitchfork if it does 😛
> **reduz:** I would go with that yeah
> This falls into the category of temporary fix until we rewrite it properly after 4.0 is out

**Comment by Anixias** [comment]
Just thought I'd throw out here that it still occasionally freezes the engine in my case, seemingly failing when starting the loading process. It does work more often than not now, though.

**Comment by mrTag** [comment]
I did some more testing, this time also on my linux machine. The test case is: loading into a level in our game, which triggers lots of parallel load_threaded_requests, with lots of overlapping external resources in the scenes. I tested both use_sub_threads true and false.

On my windows machine I didn't have any problems, ran the test 10 times with sub_threads and 10 times without.

On my linux machine (which is also not the best, hardware wise!), I had 2 different problems: the "referenced nonexistent resource" error and the deadlock, resulting in an endless loading screen (no freeze, though). Here is the tally with 10 runs per category (sub_threads and no sub_threads):
sub_threads:  endless load: 0  error: 8  no problems: 2
no sub_threads:  endless load: 4  error: 0  no problems: 6

Then I remembered, that I changed some if conditions in my PR from `if (load_task.semaphore)` to `if (load_task.thread)` and that still makes sense in this PR: not every `ThreadLoadTask` should mess with the `thread_waiting_count` and `thread_loading_count` variables. The ones that were created in the `load` function didn't increase those numbers and so they shouldn't decrease them. So I changed that (like this: https://github.com/ChasingCarrots/godot/commit/61feb7ca8a91043f94357bfbd088690f9f34de01 ) and ran the tests under linux again:
sub_threads:  endless load: 0  error: 6  no problems: 4
no sub_threads:  endless load: 0  error: 0  no problems: 10
The endless loading screen went away! I didn't have any problems when not using sub threads. The errors when using sub_threads are still there, though.

Does that change make sense to you @RandomShaper ?

**Comment by akien-mga** [comment]
> Then I remembered, that I changed some if conditions in my PR from `if (load_task.semaphore)` to `if (load_task.thread)` and that still makes sense in this PR: not every `ThreadLoadTask` should mess with the `thread_waiting_count` and `thread_loading_count` variables. The ones that were created in the `load` function didn't increase those numbers and so they shouldn't decrease them. So I changed that (like this: [ChasingCarrots@61feb7c](https://github.com/ChasingCarrots/godot/commit/61feb7ca8a91043f94357bfbd088690f9f34de01) ) and ran the tests under linux again:

I bisected #73983 as caused by this PR, so I tried your proposed change in hope that it would solve that issue, but it doesn't seem to. (Doesn't mean that it's not correct, I just checked if by chance it would fix it too.)

**Pull request merged**
