### PR TITLE
Fix 6DOF Physical Bone joint

### PR DESCRIPTION
**Pull request by nthrack-zz**
Adding angular and linear springs param to PhysicalBone joint type JOINT_TYPE_6DOF,
using new 6DOF feautres implemented in sdfgeoff/godot@e149327.

### CODE REVIEW

**Comment by natrim** [comment]
typo in variable name? 

s/lenear_equilibrium_point/linear_equilibrium_point

**Comment by nthrack** [comment]
Yup,
Corrected.

Thanks natrim.

**Comment by AndreaCatania** [comment]
Seems fine to me

**Comment by akien-mga** [comment]
Could you squash the commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
