### PR TITLE
Added splash screen with sponsors

### PR DESCRIPTION
**Pull request by djrm**

### CODE REVIEW

**Comment by hpvb** [comment]
This may actually be a problem for distro packaging and redistribution in general. The license of the sponsor's logo will probably not be freely distributable. Also, will this be included in the export templates? If so I think we're going to get a riot on our hands.

**Comment by Calinou** [comment]
> This may actually be a problem for distro packaging and redistribution in general. The license of the sponsor's logo will probably not be freely distributable.

A compile-time option could perhaps be added to disable the sponsored splash screen.

**Comment by Hinsbart** [comment]
> I think the goal is to make the sponsors display in the default splash screen, including in exported projects.

IIRC, we want the sponsors only to appear in the Editor splash. 
Games remain unaffected.

**Comment by akien-mga** [comment]
It's of course only for the editor:

spectacle m16328

Having a company logo on all exported games by default would cost a lot more than $1500/m :)

**Comment by akien-mga** [comment]
And yes, don't worry, there will be a compile time option to toggle it.

**Comment by hpvb** [comment]
I'd recommend hiding it behind a 'branded_release=yes' scons option so we can use it. I don't think adding the sponsor logo in by default is a good idea.

**Pull request merged**
