### PR TITLE
Remove error raised by curve2d when there is no point in the curve

### PR DESCRIPTION
**Pull request by 8thMage**
removing the error of "no points in curve2d" as mentioned in this error request https://github.com/godotengine/godot/issues/22338 i just removed the error and defaulted to the fault case of returning 0,0 but i don't know if it solves the error in a satisfactory way.

### CODE REVIEW

**Comment by LikeLakers2** [comment]
I think you forgot to rebase... I can't tell what you've changed in curve.cpp because the commit is just showing the whole file as being added.

http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by 8thMage** [comment]
is it better now?

**Comment by akien-mga** [comment]
Nope, the PR contains which is a rebased version of 6cbdeedf.

`git rebase -i upstream/master` should allow you to fix that (provided you have an "upstream" remote pointing to "godotengine/godot").

**Comment by 8thMage** [comment]
any better now? I'm not that good at git but i think the tree looks fine now.

**Comment by LikeLakers2** [comment]
Looks okay to me.

Though, I don't think this solution is a good one. This doesn't solve the source of the issue, which is that the error is thrown when the points are being added through code.

**Comment by 8thMage** [comment]
I also don't think it's a good solution, but i couldn't understand what people asked for.

**Pull request closed without merging**
