### PR TITLE
Fix 'FLAG_RECEIVE_SHADOWS' flag for GeometryInstances.

### PR DESCRIPTION
**Pull request by SaracenOne**
Instances with this flag disabled will now result in it correctly disabling shadows from affecting it.

### CODE REVIEW

**Comment by akien-mga** [comment]
We merged a big pull request that removed all trailing spaces in the code, so it introduced merge conflicts with your PR. Could you have a look at rebasing it to solve the merge conflicts?

**Comment by reduz** [comment]
seems good, though conflicts

**Comment by SaracenOne** [comment]
Okay, should be all sorted now. ;)

**Comment by SaracenOne** [comment]
Resolving this one now too. Again, it missed me because my diff tool wasn't configured to acknowledge differences in whitespace.

**Comment by SaracenOne** [comment]
Okay, whitespace issues should be resolved here too.

**Pull request merged**
