### PR TITLE
Fix OpenSimplexNoise get_image() swap axes

### LINKED ISSUE #30356: Swapped Axes in OpenSimplexNoise Images
**Godot version:**
v3.1.stable.official

**Issue description:**

In a small expirement I created a NoiseTexture using OpenSimplexNoise and added it to the scene as background image. Then I tried to query the noise value at a specific position, but it didn't match with what was shown on the screen.

It took me a while to figure out, that OpenSimplexNoise.get_image() swaps the x- and y-axis:

```cpp
for (int i = 0; i < p_height; i++) {
    for (int j = 0; j < p_width; j++) {
        float v = get_noise_2d(i, j); // this should be get_noise_2d(j, i);
// or maybe use x and y instead of j and i
```

See [open_simplex_noise.cpp](https://github.com/godotengine/godot/blob/87ee2a9239928e2811ce1711bc381f601edd278a/modules/opensimplex/open_simplex_noise.cpp)

**Steps to reproduce:**
```GDScript
var noise = OpenSimplexNoise()
var image = noise.get_image(1024, 1024)
image.lock()

var x = 700
var y = 400
var valueFromNoise = noise.get_noise_2d(x, y)
var pixelColor = image.get_pixel(x, y)
var valueFromNoiseImage = pixelColor.r * 2 - 1 # maps [0,1] to [-1,1]

if abs(valueFromNoise - valueFromNoiseImage) > 0.01:
    print("Reproduced issue: ", valueFromNoise, " vs ", valueFromNoiseImage)
```

**Minimal reproduction project:**

[NoiseImageFlippedAxesDemo.zip](https://github.com/godotengine/godot/files/3364122/NoiseImageFlippedAxesDemo.zip)

**Remarks:**
It is of course easy to work around this issue by just calling `noise.get_noise_2d(y, x)` instead, but that's something one has to figure out first.
What I don't know is, if fixing the order in open_simplex_noise.cpp would cause some side-effects for other projects. Alternatively the docs should just mention this issue, that would be helping too.

### PR DESCRIPTION
**Pull request by Raphael2048**
fix #30356

### CODE REVIEW

**Comment by JFonS** [comment]
I'm not against this change, but I want to note that it breaks compat with 3.1

**Comment by Anutrix** [comment]
We can switch `p_height` and `p_width` instead of i,j in the for loop,right? Because `i,j` looks nicer than `j,i`. Just my opinion.

**Comment by aaronfranke** [comment]
@raphael10241024 Is this still desired? If so, it needs to be rebased on the latest master branch. While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by raphael10241024** [comment]
rebased

**Review by aaronfranke — APPROVED** [review]
This fix is very simple and makes sense, currently `i` is the iterator for the height (Y axis) and `j` is the iterator for the width (X axis), so the order should be `j, i`.

The alternative is @Anutrix's suggestion of swapping width and height. I don't think it actually matters which is which, so I guess this depends on @JFonS's personal preference.

**Comment by akien-mga** [comment]
I also tend to prefer swapping `p_width` and `p_height` in the `for` loops so that we go through (X, Y) instead of (Y, X). But I also don't have a strong opinion either way, it's equivalent.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

Note that this breaks compatibility. Users who want to preserve the behavior of 3.3 and earlier can swap the arguments in their call to `get_image()`.

**Pull request merged**
