### PR TITLE
Bring back Vector2.cross()

### PR DESCRIPTION
**Pull request by ghost**
Not sure why it was ever commented out, as it is in master, but I imagine this might have happened due to the dual definition of `cross` in the current C++ implementation `Vector2`.

Since the analog of a cross product for 2d is indeed a very common definition (see http://mathworld.wolfram.com/CrossProduct.html, https://stackoverflow.com/questions/243945/calculating-a-2d-vectors-cross-product) I suggest we reintroduce it and rename the internal conflicting C++ method `Vector2.cross(real_t)` to `Vector2.perp(real_t)` so there's only one `Vector2.cross(Vector2)`.

### CODE REVIEW

**Comment by Chaosus** [comment]
I thought a cross operation has no meaning in 2d space...

**Comment by vnen** [comment]
> Not sure why it was ever commented out, as it is in master,

There was a long discussion about that: #7054

**Comment by Chaosus** [comment]
And for what purposes Vector2.perp could be used, and what pass as parameter to it ?

**Comment by vnen** [comment]
Also, the bindings are wrong: the C++ function receives a float and returns a Vector2 but in the bindings it receives a Vector2 and returns a float.

**Comment by poke1024** [comment]
@vnen No, they're not. The C++ cross function in this PR returns a float.

@Chaosus Cross is not defined for 2d, but: setting z = 0 and treating thus the 2d vectors as 3d vectors in a plane, you can compute it as if you were in 3 dimensions. This is very useful and common in many algorithms as it gives you a measure of the area of the parallelogram spanned by the two vectors (there's a reason Godot's C++ Vector2 class has it in the first place). This guy has a lengthy demonstration of doing the arithmetic: https://www.youtube.com/watch?v=Tesvs6xCWZA

What should get debated here if whether this should be called `cross` or something else. But the functionality itself is highly useful and Godot should expose it under some name.

A similar discussion on the usefulness of this function has happened in glm recently:
https://github.com/g-truc/glm/issues/621

@Chaosus Note that the renamed function `Vector2.perp` is not exposed but merely a renaming in Godot's internal Vector2 class to resolve the name conflict on `cross`. `perp` is an operation that computes a perpendicular vector. I didn't add it, I just propose to rename it.

**Comment by vnen** [comment]
Sorry, I misread it.

Still, check the discussion at #7054. Summing up, the conclusion is that cross product is not defined for 2D and you can achieve the effects with `tangent` and `angle_to`.

**Comment by DuskKittyIsHotAF** [comment]
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!

**Comment by Xrayez** [comment]
I had one occasion where I needed both dot and cross product when implementing some sophisticated boundary tracing algorithm based on vector algebra. As poke1024 suggested, I used the cross method from Vector3 class with z = 0 to achieve the effect. But I ended up implementing it in C++ for that reason, plus the increased performance of course.

**Comment by akien-mga** [comment]
Since this "cross product analog" is actually the determinant of `u` and `v`, how about just calling it `real_t Vector2::det(Vector2 p_other)`, and also implement and expose `real_t Vector3::det(Vector3 p_other)`?

Then I also agree about renaming the current `Vector2 Vector2::cross(real_t p_other)` to `perp`, as it's indeed a weird and non-standard take on a cross product analog in 2D space. Maybe also rename the scalar argument to `p_scalar`, as it's not an "other" vector like in other definitions.

We should call methods by their real names, and there should not be a `Vector2::cross` at all - if the 2D analog is the determinant, that's what it should be named.

**Comment by akien-mga** [comment]
Actually, let's kill `Vector2::perp` altogether. It's not exposed, not standard, and only used in one place ( `servers/physics_2d/joints_2d_sw.cpp`). I'd just define it there, since it's the only place that needs it.

**Comment by poke1024** [comment]
Followed @akien-mga's proposal and removed `Vector2::perp` from `Vector2`.

**Comment by akien-mga** [comment]
Thanks! I still think it would be better to also rename `real_t Vector2::cross` to `Vector2::det` (both the internal C++ method and the bound one for scripting), as it's what it is as far as math is concerned.

The documentation should make it clear that the determinant can also be used as 2D cross product analog.
image

This way we get both the useful feature and we avoid the endless debate about whether it can be called a "2D cross product" :)
I'd also add `real_t Vector3::det` for consistency.

**Comment by akien-mga** [comment]
Wait, actually `u.det(v)` might be a bit misleading syntax, since `det(u v)` is actually the determinant of a matrix resulting from the matrix product of the two vectors...

Let's just go with the flow and keep the name `cross` then for the operation on two vectors.

**Pull request merged**
