### PR TITLE
Fix fontconfig and dbus loading on Linux

### PR DESCRIPTION
**Pull request by nikitalita**
On default Ubuntu 22.04 installations, when running the current Godot master, `libfontconfig.so` fails to be loaded, despite default Ubuntu 22.04 coming with `fontconfig` installed.

The reason is that `libfontconfig.so` does not get installed by the package `libfontconfig1` by default. It only creates the link `libfontconfg.so.1 --> libfontconfig.so.1.12.0` when installed:

```
nikita@DESKTOP-ROCOTG2:~$ dpkg -L libfontconfig1
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.12.0
/usr/share
/usr/share/doc
/usr/share/doc/libfontconfig1
/usr/share/doc/libfontconfig1/changelog.Debian.gz
/usr/share/doc/libfontconfig1/copyright
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1
nikita@DESKTOP-ROCOTG2:~$ ls -la /usr/lib/x86_64-linux-gnu/libfontconfig.*
lrwxrwxrwx 1 root root     23 Mar 23  2022 /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 -> libfontconfig.so.1.12.0
-rw-r--r-- 1 root root 298120 Mar 23  2022 /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.12.0
```

It's only after installing `libfontconfig1-dev` that it installs that link:

```
nikita@DESKTOP-ROCOTG2:~$ sudo apt install libfontconfig1-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  [...]
Selecting previously unselected package libfreetype-dev:amd64.
Preparing to unpack .../3-libfreetype-dev_2.11.1+dfsg-1ubuntu0.1_amd64.deb ...
Unpacking libfreetype-dev:amd64 (2.11.1+dfsg-1ubuntu0.1) ...
Selecting previously unselected package libfreetype6-dev:amd64.
Preparing to unpack .../4-libfreetype6-dev_2.11.1+dfsg-1ubuntu0.1_amd64.deb ...
Unpacking libfreetype6-dev:amd64 (2.11.1+dfsg-1ubuntu0.1) ...
Selecting previously unselected package libfontconfig-dev:amd64.
Preparing to unpack .../5-libfontconfig-dev_2.13.1-4.2ubuntu5_amd64.deb ...
Unpacking libfontconfig-dev:amd64 (2.13.1-4.2ubuntu5) ...
Selecting previously unselected package libfontconfig1-dev:amd64.
Preparing to unpack .../6-libfontconfig1-dev_2.13.1-4.2ubuntu5_amd64.deb ...
Unpacking libfontconfig1-dev:amd64 (2.13.1-4.2ubuntu5) ...
Selecting previously unselected package libpng-tools.
Preparing to unpack .../7-libpng-tools_1.6.37-3build5_amd64.deb ...
Unpacking libpng-tools (1.6.37-3build5) ...
Setting up libpng-tools (1.6.37-3build5) ...
Setting up libpng-dev:amd64 (1.6.37-3build5) ...
Setting up libfreetype6:amd64 (2.11.1+dfsg-1ubuntu0.1) ...
Setting up libbrotli-dev:amd64 (1.0.9-2build6) ...
Setting up libfreetype-dev:amd64 (2.11.1+dfsg-1ubuntu0.1) ...
Setting up libfontconfig-dev:amd64 (2.13.1-4.2ubuntu5) ...
Setting up libfreetype6-dev:amd64 (2.11.1+dfsg-1ubuntu0.1) ...
Setting up libfontconfig1-dev:amd64 (2.13.1-4.2ubuntu5) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Scanning processes...
Scanning processor microcode...
Scanning linux images...
[...]
nikita@DESKTOP-ROCOTG2:~$ ls -la /usr/lib/x86_64-linux-gnu/libfontconfig.*
-rw-r--r-- 1 root root 516010 Mar 23  2022 /usr/lib/x86_64-linux-gnu/libfontconfig.a
lrwxrwxrwx 1 root root     23 Mar 23  2022 /usr/lib/x86_64-linux-gnu/libfontconfig.so -> libfontconfig.so.1.12.0
lrwxrwxrwx 1 root root     23 Mar 23  2022 /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 -> libfontconfig.so.1.12.0
-rw-r--r-- 1 root root 298120 Mar 23  2022 /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.12.0
```

This PR fixes the issue by checking for the existence of `libfontconfig.so.1` if we can't find `libfontconfig.so`.

I am not sure if Debian or earlier/later versions of Ubuntu are affected by this, but Ubuntu 22.04 is the current LTS.

cc @bruvzg

### CODE REVIEW

**Comment by akien-mga** [comment]
It should only try `libfontconfig.so.1` directly, the `.so` is a development symlink and not installed on any Linux distro (unless it doesn't differentiate dev and runtime components).

**Review by bruvzg — COMMENTED** [review]
This might be the case for the other distros as well, so it's probably OK to change the first `dlopen`.

Also update the comment with a command in the beginning of the file to ensure it's correctly regenerated in future.
```diff
-// flags: ./generate-wrapper.py --include /usr/include/fontconfig/fontconfig.h --sys-include <fontconfig/fontconfig.h> --soname libfontconfig.so --init-name fontconfig --output-header fontconfig-so_wrap.h --output-implementation fontconfig-so_wrap.c --omit-prefix FcCharSetFirst --omit-prefix FcCharSetNext
+// flags: ./generate-wrapper.py --include /usr/include/fontconfig/fontconfig.h --sys-include <fontconfig/fontconfig.h> --soname libfontconfig.so.1 --init-name fontconfig --output-header fontconfig-so_wrap.h --output-implementation fontconfig-so_wrap.c --omit-prefix FcCharSetFirst --omit-prefix FcCharSetNext
```

**Comment by nikitalita** [comment]
Indeed, red hat distros do it this way as well: http://rpm.pbone.net/info_idpl_48420678_distro_fedora17_com_fontconfig-2.8.0-8.fc17.x86_64.rpm.html

Arch seems to install both: 
https://archlinux.org/packages/extra/x86_64/fontconfig/

So I’ll change it to only look for libfontconfig.so.1

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
I notice that we have the same issue for `libdbus-1.so.3`:
```
platform/linuxbsd/dbus-so_wrap.c
728:  handle = dlopen("libdbus-1.so", RTLD_LAZY);
```

Could be worth fixing in this PR too while we're at it.

Other `dlopen` calls seem to use the right SONAME already.

**Comment by akien-mga** [comment]
Looks good! Could you squash the two commits? The two changes are closely related so it's better to have them grouped together.

**Comment by nikitalita** [comment]
squashed.

**Comment by akien-mga** [comment]
Thanks!

Seems like GitHub bugged when I merged and this didn't get closed. It might auto close next time there's a merge/commit on master.

**Pull request merged**
