### PR TITLE
Add emission_finished signal to Particles2D

### LINKED ISSUE #3963: Particles and Particles2D signal when finished
http://godotengine.org/qa/883/how-to-remove-a-particle2d

### PR DESCRIPTION
**Pull request by bojidar-bg**
(Also remove some Particles2D::testee method, which was unused)
Closes #3963

### CODE REVIEW

**Review by 27thLiz — APPROVED** [review]

**Comment by girng** [comment]
my lord this is awesome, can we please get this in 3.0? can't find the signals

**Comment by bojidar-bg** [comment]
Well, it is removed by reduz in 95560e02c5eed3561996ed2b1d1e47e26e8bb81c, when he added GPU particles. Guess someone should redo it :)

**Comment by girng** [comment]
really wish particle attractor  2d node could make a return someday as well. loved the suction (black hole) effect you could create with that stuff. however, the performance with the new particle system is absolutely way better so not complaining there. just trying to think of more ways to make it even better

**Comment by bojidar-bg** [comment]
@girng you can do something similar with a custom particles shader.. not that it is as simple as before..

**Comment by girng** [comment]
@bojidar-bg thanks, will look into it

**Pull request merged**
