### PR TITLE
Add `buffer_copy` method to RenderingDevice

### PR DESCRIPTION
**Pull request by DarioSamo**
Includes a Vulkan implementation.

Direct buffer copies are required to perform certain operations more efficiently, as the only current alternative is to download the buffer to the CPU and upload it again.

As mentioned in https://github.com/godotengine/godot/pull/80414, the only alternative was to download the buffer to the CPU, which induces an extremely inefficient stall when all that is needed is to just copy the buffer directly on the GPU.

This PR should have no current effect in any rendering code whatsoever as nothing calls it yet. Once it is merged I can provide an implementation for multimesh that takes advantage of this new function to handle the resize path more efficiently.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
The implementation looks fine to me. 

Let's wait to merge until we actually have something to test this with though so we can confirm that it is working

**Comment by DarioSamo** [comment]
As https://github.com/godotengine/godot/pull/80414 has been merged, I've now added a change to the affected function in this PR to avoid having to do GPU readback.

Verifying if this works should just involve testing the MRP again on the issue #67287.

**Review by clayjohn — APPROVED** [review]
Code looks good to me and I tested locally and it works fine. 

Since this is a new-ish feature, no need to cherrypick

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
