### PR TITLE
[3.x] Implement Scene Unique Nodes

### PR DESCRIPTION
**Pull request by KoBeWi**
Backport of #60298, including changes from #60511
Introduces small compatibility breakage: `%` is no longer allowed in Node names.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by elvisish** [comment]
Scene unique names cannot be used from autorun scripts as they are in a different scene in the tree, is this intentional?

**Comment by KoBeWi** [comment]
`$"%Node"` is equivalent of `owner.find_node("Node")`. If your unique node belongs to another scene, you need to fetch the scene first, then node, e.g. `$"Scene/%Node"` or `some_scene.get_node("%Node")`.

**Comment by elvisish** [comment]
> `$"%Node"` is functionally equivalent of `owner.find_node("Node")`. If your unique node belongs to another scene, you need to fetch the scene first, then node, e.g. `$"Scene/%Node"` or `some_scene.get_node("%Node")`.

This could be difficult if you're not sure the name of the main scene you're looking for the node in, which slightly defeats the purpose of this I guess? I think for global autorun work, groups are still faster and easier to work with.

**Comment by KoBeWi** [comment]
Well, unique nodes were designed to be used in the same scene. If you want global nodes, groups are indeed better.

**Pull request merged**
