### PR TITLE
Improved Camera Gizmo

### PR DESCRIPTION
**Pull request by SaracenOne**
New camera gizmo which shows the camera's full frustum. Exposes 'get_frustum' to scripting in camera, and also adds a new 'get_endpoints' method which is also exposed to script.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
I really should enhance the ARVRCamera that if we're dealing with a stereo camera it will return a frustum that encompasses the frustums of both eyes. That would allow us to start working on creating render lists once per frame instead of twice per frame as well.

**Comment by SaracenOne** [comment]
@BastiaanOlij Funny you should mention that, as I actually already have some code for per-eye rendering incidentally already since I was experimenting with 2D VR rendering ;)

**Comment by SaracenOne** [comment]
@BastiaanOlij Sorry, I misread what you wrote. But yes, that would make sense to do as a rendering optimization ;)

**Comment by SaracenOne** [comment]
Eh, I think Travis CI is broken :/

**Comment by akien-mga** [comment]
> Eh, I think Travis CI is broken :/

Not broken, but `clang-format` doesn't deal well with comments before preprocessor defines, and often tries to either indent or de-indent them in weird ways. Best is to avoid such situations completely.

**Comment by reduz** [comment]
This is nice, would appreciate some screens or video of the feature

**Comment by SaracenOne** [comment]
@reduz Here we go. With this, the gizmo now covers actual frustum of camera.
camera_gizmo

**Comment by reduz** [comment]
Not quite sure if this is desirable, given editing FOV will become a hassle. Maybe just adding it as an extra layer, with more transparency, showing near and far?

**Comment by akien-mga** [comment]
> Not quite sure if this is desirable, given editing FOV will become a hassle. Maybe just adding it as an extra layer, with more transparency, showing near and far?

WDYT @SaracenOne?

**Comment by SaracenOne** [comment]
I guess. I don't have a particularly strong investment in this particular PR. The reason I wrote it was a specifically working on something which involved being able to visualize the exact dimensions of the camera frustum. I suppose it could be something toggled, but I also wouldn't want to introduce too much design complexity.

**Comment by akien-mga** [comment]
Closing for now then.

**Pull request closed without merging**
