### PR TITLE
Fix `KeyValuePairAt` memory leak

### LINKED ISSUE #56180: [C#] Godot leaks memory when you use foreach with a Godot.Collections.Dictionary
### Godot version

3.4.2.stable.mono (45eaa2daf)

### System information

Windows 10

### Issue description

If you have a Godot.Collections.Dictionary in your code and try to loop trough it with a foreach godot will leak memory, the code can be as simple as:
```
private Dictionary<string, int> _dict = new Dictionary<string, int>()
{
    { "0", 0 },
    { "1", 1 },
    { "2", 2 },
    { "3", 3 },
};

public override void _Process(float delta)
{
    foreach (var item in _dict)
    {
    }
}
```
It will leak memory,
it stops leaking memory if you use System.Collections.Generic.Dictionary, so it's definitelly a problem with Godot.
You can check it by going to the monitors tab on the debugger, static memory won't stop increasing

### Steps to reproduce

Create a new project and add a C# script to a node,
inside of the script create a Godot.Collections.Dictionary with any types for key and value
then try to loop though its entries with a foreach in the _Process function
You can see the memory leak by going to the monitors tab on the debugger, static memory won't stop increasing

### Minimal reproduction project

[Memory Leak.zip](https://github.com/godotengine/godot/files/7765442/Memory.Leak.zip)

### PR DESCRIPTION
**Pull request by raulsntos**
Fixes #56180 (a regression from #51044)

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Haven't tested but this looks good to me.

**Review by kleonc — APPROVED** [review]
Tested and looks good to me.

**Comment by neikeq** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
