### PR TITLE
Fixed StyleBoxFlat border size with aa on

### LINKED ISSUE #34104: Panel with StyleBoxFlat looks different in Godot 3.2
**Godot version:**
3.2 beta 2
**OS/device including version:**
MX Linux 64 bits

**Issue description:**
I'm not sure if this was intended, panels with the same ui style look different between Godot 3.1 and Godot 3.2

This is how a panel looks in 3.2
image
And this is how it looked in 3.1
image

**Steps to reproduce:**
Create ui theme and give panels a StyleBoxFlat style, change the values and compare the results between Godot 3.1 and Godot 3.2

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
The different Rect used to draw rings were wrongly calculated when anti-aliasing was enabled. Also getting rid of some overlapping glitches when using transparent colors for the filling or borders.

No anti-aliasing:

With anti-aliasing, 3.1.1:

With anti-aliasing, 3.2 beta 3:

With anti-aliasing, now fixed:

Fixes #34104

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by Sslaxx** [comment]
Any possibility of cherrypicking for 3.1?

**Comment by Calinou** [comment]
I think it makes sense to have this in 3.1, as it makes antialiased StyleBoxFlats look closer to their non-antialiased counterparts.

**Comment by pouleyKetchoupp** [comment]
It would require PR #26609 to be picked for 3.1 as well though, as the new fixes are dependent on the changes made then.

**Pull request merged**
