### PR TITLE
pcre2: Update to 10.43

### PR DESCRIPTION
**Pull request by Chubercik**
https://github.com/PCRE2Project/pcre2/releases/tag/pcre2-10.43

- Changelog: https://github.com/PCRE2Project/pcre2/blob/pcre2-10.43/ChangeLog
- Updated `thirdparty/README.md` as it seemed to omit mentioning one file

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good! Could you squash the commits?

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I'm running into a build issue for iOS (with osxcross) on our official buildsystem:
```
/root/ioscross/arm64//usr/bin/arm-apple-darwin11-clang -o thirdparty/pcre2/src/pcre2_pattern_info_32.ios.template_debug.arm64.o -c -std=gnu11 -miphoneos-version-min=12.0 -fobjc-arc -arch arm64 -fmessage-length=0 -fno-strict-aliasing -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -fpascal-strings -fblocks -fvisibility=hidden -MMD -MT dependencies -isysroot /root/ioscross/arm64/SDK/iPhoneOS17.2.sdk -Wno-ambiguous-macro -O2 -w -DDEBUG_ENABLED -DNDEBUG -DNO_EDITOR_SPLASH -DNEED_LONG_INT -DIOS_ENABLED -DUNIX_ENABLED -DCOREAUDIO_ENABLED -DVULKAN_ENABLED -DRD_ENABLED -DGLES3_ENABLED -DGLES_SILENCE_DEPRECATION -DMINIZIP_ENABLED -DBROTLI_ENABLED -DTHREADS_ENABLED -DCLIPPER2_ENABLED -DZSTD_STATIC_LINKING_ONLY -DVK_USE_PLATFORM_IOS_MVK -DGODOT_MODULE -DPCRE2_STATIC -DHAVE_CONFIG_H -DSUPPORT_UNICODE -DSUPPORT_JIT -DPCRE2_CODE_UNIT_WIDTH=32 -Ithirdparty/pcre2/src -Ithirdparty/libpng -Ithirdparty/vulkan -Ithirdparty/vulkan/include -Ithirdparty/zstd -Ithirdparty/zlib -Ithirdparty/clipper2/include -Ithirdparty/brotli/include -I/root/ioscross/arm64/SDK/iPhoneOS17.2.sdk/System/Library/Frameworks/OpenGLES.framework/Headers -Iplatform/ios -I/root/ioscross/arm64/SDK/iPhoneOS17.2.sdk/usr/include -I/root/ioscross/arm64/SDK/iPhoneOS17.2.sdk/System/Library/Frameworks/AudioUnit.framework/Headers -I. thirdparty/pcre2/src/pcre2_pattern_info.c
In file included from thirdparty/pcre2/src/pcre2_jit_compile.c:85:
In file included from thirdparty/pcre2/src/sljit/sljitLir.c:317:
thirdparty/pcre2/src/sljit/allocator_src/sljitExecAllocatorApple.c:123:2: error: call to undeclared function 'SLJIT_UPDATE_WX_FLAGS'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration,2]
        SLJIT_UPDATE_WX_FLAGS(retval, (uint8_t *)retval + size, 0);
        ^
```

**Comment by akien-mga** [comment]
I have no clue what I'm doing, but this seems to work it around:
```diff
diff --git a/thirdparty/pcre2/src/sljit/allocator_src/sljitExecAllocatorApple.c b/thirdparty/pcre2/src/sljit/allocator_src/sljitExecAllocatorApple.c
index 95b9842fa9..3fc8091ead 100644
--- a/thirdparty/pcre2/src/sljit/allocator_src/sljitExecAllocatorApple.c
+++ b/thirdparty/pcre2/src/sljit/allocator_src/sljitExecAllocatorApple.c
@@ -104,6 +104,7 @@ static SLJIT_INLINE void apple_update_wx_flags(sljit_s32 enable_exec)
 #else
 #define SLJIT_MAP_JIT	(0)
 #endif
+#define SLJIT_UPDATE_WX_FLAGS(from, to, enable_exec)
 
 #endif /* TARGET_OS_OSX */
 
```

**Comment by akien-mga** [comment]
I think we're also compiling too many files, `src/sljit/sljitExecAllocator.c` no longer exists upstream, it's replaced by this new `allocator_src`. But we compile both.

**Comment by Chubercik** [comment]
> I think we're also compiling too many files, `src/sljit/sljitExecAllocator.c` no longer exists upstream, it's replaced by this new `allocator_src`. But we compile both.

Yeah, that might be on me 😬

Whatever's going on with `sljitExecAllocatorApple.c` seems to be an issue upstream; the patch you propose looks good.

**Pull request merged**
