### PR TITLE
Fix the return type of NativeScript::new in API json

### PR DESCRIPTION
**Pull request by ghost**
`NativeScript::new`'s return type is `Variant`, but was mistakenly labeled as `Object` in the API json for GDNative, causing the returned pointer to be unusable (can't downcast or call script methods, may be pointing to garbage in pre-allocated memory?)

This fixes the generated JSON API, making the return value function normally.

### CODE REVIEW

**Comment by akien-mga** [comment]
`new` is however supposed to return an Object, at least in GDScript. So maybe it's the actual return type that should be fixed and not its hint, if that's possible in GDNative?

**Comment by akien-mga** [comment]
> `new` is however supposed to return an Object, at least in GDScript. So maybe it's the actual return type that should be fixed and not its hint, if that's possible in GDNative?

Actually the GDScript one also returns `Variant`, but is also documented as returning `Object`:

https://github.com/godotengine/godot/blob/57afa90f0c30ca52a46659123c0f6ff1d94137c3/modules/gdscript/gdscript.cpp#L134-L178

https://github.com/godotengine/godot/blob/57afa90f0c30ca52a46659123c0f6ff1d94137c3/modules/gdscript/gdscript.cpp#L713

Looking at the code, it actually returns either `Object`, `Reference` (which is also an Object), or `Variant()`, i.e. `Nil`. So from the documentation point of view "Object (or Nil)" is kind of relevant, but for GDNative this kind of shortcut is likely not wanted indeed.

**Comment by toasteater** [comment]
> GDScript one also returns `Variant`

I'm not very familiar with GDScript's implementation so correct me if I'm wrong, but `Variant::operator==` looks like this:

```cpp
bool Variant::operator==(const Variant &p_variant) const {

	if (type != p_variant.type) //evaluation of operator== needs to be more strict
		return false;
	bool v;
	Variant r;
	evaluate(OP_EQUAL, *this, p_variant, r, v);
	return r;
}
```

... so in GDScript an null Object pointer might be seen as different from a `Nil`, because they have different variant types. This is also seen with #27261, where GDScript nulls can't be assigned to typed variables. If that's the case, then the `Variant` return type is necessary for the function to work as intended when called from GDScript, so it can't be simply changed to `Object *`.

> from the documentation point of view "Object (or Nil)" is kind of relevant, but for GDNative this kind of shortcut is likely not wanted indeed.

Yes. For GDNative, this mismatch is problematic, because where GDScript sees Variants, native libraries see `void *`s. If the C++ function signature and `api.json` don't agree, then all bets are off. If there're other methods that also use this documentation "trick", then something have to be done about them:

1. Remove the trick and have their actual return (or argument) types show up in documentation, or
2. Keep the docs, introduce another set of hints for GDNative API generation only.

**Comment by toasteater** [comment]
So I searched `MethodInfo(Variant::OBJECT` and got these methods that claim to return `Object` but actually return `Variant`s:

- Control::get_drag_data
- CSharpScript::_new
- GDScript::_new
- PluginScript::_new

**Comment by toasteater** [comment]
Pushed changes that will change the return types of other `new` methods to `Variant` in API json. However, `Control::get_drag_data` cannot be fixed in this way, because unlike vararg methods, virtual methods seem to get the return type `void` when they don't have a Variant type hint, and there are already plenty of code depending on this behavior. A fix to that would need more knowledge about the engine's core than what I have.

**Comment by bojidar-bg** [comment]
Use `PROPERTY_USAGE_NIL_IS_VARIANT`, perhaps?

**Comment by neikeq** [comment]
There are two reason why those methods return `Variant`:
- VarArg methods must return `Variant`. That's what the function pointer signature expects.
- They may return a `Reference`, which is not safe to return by pointer, so instead it returns a `Variant` constructed from a `Ref<Reference>`.

In this case, there really is no problem, because tou know VarArg methods always return `Variant`. Ignore what `MethodInfo` tells you. Just assume it returns `Variant`. You can always use the return type from `MethodInfo` in higher level bindings.

This is what the C# bindings do (pseudocode, removed unnecessary noise):

``` C++
MonoObject* godot_icall_for_varargs(MethodBind* method, Object* ptr, MonoArray* args) {
	Object* ret = NULL; // Return value for the high level function (Object*)
	Variant vararg_ret; // Actual return value expected from ptrcall (Variant)
	vararg_ret = method->call(ptr, args, args.length);
	ret = vararg_ret; // Variant to Object*
	return GDMonoUtils::unmanaged_get_managed(ret); // Object* to managed
}
```
And this is how the C# method looks:

``` C#
// As you can see, it returns a Godot.Object (wrapper for Object*)
// params means it's a VarArg argument
public Object New(params object[] args)
{
    return NativeCalls.godot_icall_for_varargs(method_bind_0, Object.GetPtr(this), args);
}
```

**Comment by toasteater** [comment]
> Use `PROPERTY_USAGE_NIL_IS_VARIANT`, perhaps?

Thanks! It worked on `Control::get_drag_data`.

> VarArg methods must return `Variant`
> ...
> Ignore what `MethodInfo` tells you. Just assume it returns `Variant`. You can always use the return type from `MethodInfo` in higher level bindings.

Thanks for the information! I do agree that this is a very pragmatic solution, although I don't think this is quite adequately documented. `godot-rust` is still hit by this problem, despite its (now previous?) maintainer also being a maintainer of GDNative.

That's said, I'm not sure if the `MethodInfo`s should necessarily stay in this current state. All other cases of `bind_vararg_method` found in the codebase don't have `return_val.type` set, so breakage isn't likely, and I do believe there is merit in having consistency. But I'm not someone who can decide.

Meanwhile, `Control::get_drag_data` is not a VarArg method, so its MethodInfo needs to be changed.

**Comment by neikeq** [comment]
Indeed, `Control::get_drag_data` returns `Variant` and there are places that expect the data to be a `Dictionary` for example, so `Object` is wrong there.

**Comment by akien-mga** [comment]
Thanks!

**Comment by neikeq** [comment]
As I commented, the return type of the `new` methods was not a problem and should have been fixed by the bindings generators of rust and other languages instead :sweat_smile:

**Comment by neikeq** [comment]
Also, there are also vararg methods that override the type of arguments, for example:

https://github.com/godotengine/godot/blob/46ad60385b68a8af142108715a12a3363ffb3fea/scene/main/scene_tree.cpp#L1824-L1830

Looking at the `PtrToArg::convert` I think it would have the same problem as for return types.

**Pull request merged**
