### PR TITLE
Remove checks for underscores

### PR DESCRIPTION
**Pull request by ptrojahn**
Pull #26990 makes them obsolete

### CODE REVIEW

**Comment by akien-mga** [comment]
#26990 is not merged yet though, so it's a bit early for such change :)

**Comment by ptrojahn** [comment]
Yes. Should have mentioned that. Just wanted to have have all the code on that topic complete.

**Comment by aaronfranke** [comment]
@ptrojahn Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by neikeq** [comment]
This is more of a cleanup of underscores that won't be necessary after #26990. So whether it's still desired or not depends of that PR. I don't know if @ptrojahn is still interested in working on this though.

**Comment by ptrojahn** [comment]
I won't work on this anymore. Anyone interested is welcome to use it.

**Pull request closed without merging**
