### PR TITLE
use matrix multiplication instead of euler angle rotation in bone transform

### PR DESCRIPTION
**Pull request by karroffel**
Fixup of #17947

### CODE REVIEW

**Review by tagcup — COMMENTED** [review]
The rotation and scale order is wrong

**Comment by tagcup** [comment]
This is exactly why I'm saying add a new constructor. It's error prone an common

**Comment by karroffel** [comment]
@tagcup well the behavior is the same :woman_shrugging:

**Comment by tagcup** [comment]
That constructor is quite common in the source tree, and it's hard-coded every time.
I don't remember how many bugs were fixed to correct the ordering. So please, just add it.

**Comment by karroffel** [comment]
It behaves correctly, I had the order the other way around at first, but that resulted in the same wrong transform visible in #17325. This order fixes it.

**Comment by tagcup** [comment]
If you're referring to the ordering, no, the behavior is different, you can't change the ordering of scale and rotation

**Comment by tagcup** [comment]
It may behave correctly for uniform scale but they don't commute in general

**Comment by tagcup** [comment]
Uniform scale commutes with everything it's proportional to identity matrix

**Comment by tagcup** [comment]
The order you use in #17947 is correct, scale first, then rotate
You're doing the opposite here

**Comment by karroffel** [comment]
I know, I used the order that I expected first but I saw that the issue in #17325 is still there with that. This order has the correct result, I don't know why. Feel free to apply the patch and test the animation given in #17325

**Comment by tagcup** [comment]
The fix for collada is you can either reverse the order of scale and rotation by hand, or preferably you can use rotate_local scale_local instead

https://github.com/godotengine/godot/blob/master/core/math/matrix3.cpp#L327

**Comment by tagcup** [comment]
Of course I mean you can use _local functions in the collada importer code, not the animation code

**Comment by tagcup** [comment]
Oops I realized we have scale_local and rotate_local, but we don't currently have get_scale_local and get_rotation_local which you'd need

You can implement get_rotation_local by copy-pasting get_rotation, just do a transpose before and after orthonormalization. For get_scale_local you can simply to swap the row and column indices in get_scale

**Comment by karroffel** [comment]
I feel like you have more domain knowledge than me, would you mind trying to implement those things?

I just experienced the same problems as in #17325 and wanted it fixed and saw that the transform setup looked weird. I'm not that deep into the whole math topic here. I tried adding the constructor but that just wrecks everything, so I think it would be faster if you (or someone else who knows better what they are actually doing) could tackle this.

**Comment by tagcup** [comment]
and similar for get_rotation_axis_angle_local

**Comment by tagcup** [comment]
Ah OK, can you wait until the weekend then?

**Comment by karroffel** [comment]
Sure, like I said, the current state on master works for me, you and Juan pointed out the issues, so I don't mind

**Comment by reduz** [comment]
any progress with this? Keep in mind Collada importer just loads transforms that were supplied by blender itself. The matrices loaded are converted to loc/rot in the importer, so maybe the problem is the conversion to loc/rot?

**Comment by reduz** [comment]
@tagcup is this the code you say should be modified?

https://github.com/godotengine/godot/blob/master/editor/import/editor_import_collada.cpp#L1788

**Comment by tagcup** [comment]
@reduz it is clear from the video that the scale is applied first and then the elongated cube is rotated. That's also what we do in Godot. Somewhere along the pipeline the ordering is apparently reversed. It could be in the collada exporter or the importer, not 100% sure but if you can wait I'll give it a check

**Comment by tagcup** [comment]
@reduz doing
```
	Vector3 scale = tr.basis.transposed().get_scale(); // get_scale_local()
	tr.basis.transposed().orthonormalized().transposed().set_scale(scale);
```
in `Collada::fix_transform` fixes it but let me do it in a proper way. I want to add local versions of get scane and rotate. Also, I just found out that someone (Odino) changed `get_scale` to return the absolute values such that polar decomposition is broken right now (in the sense that get_scale and get_rotation combined don't always give you the original basis).

I'm going to rename get_scale to get_scale_abs (because that's what it does) and rename get_scale_signed back to get_scale. Taking abs is probably used in bullet bindings so I can either s/get_scale/get_scale_abs in that directory or let Odino deal with the fall out, but either way get_scale shouldn't have been modified

**Comment by tagcup** [comment]
@karroffel I realized that I can't reproduce #17325 on current master at, can you give it another try? Did something change recently?

**Comment by karroffel** [comment]
@tagcup Yes, the PR #17947 got merged and fixes the problem, but and Juan didn't like that it uses `get_euler()`, which is the reason for this PR

**Pull request closed without merging**
