### PR TITLE
[Web] Add feature detection helpers to JS Engine class.

### LINKED ISSUE #48110: Display user friendly error when running an HTML5 Threads export without SharedArrayBuffers
**Godot version:**

3.3

**OS/device including version:**

Windows 10 20h2 (build 19042.928)
Firefox 88

**Issue description:**

When launching a game using the HTML5 template with the Threads export type in an environment without SharedArrayBuffers, an uncaught error occurs and loading halts.

I tracked the error to this statement in index.js: `if(!(wasmMemory.buffer instanceof SharedArrayBuffer)){err("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag");`

I am aware I can't use threads without SharedArrayBuffers. At a bare minimum, Godot shouldn't load and display a proper error message in the console. Optimally, the game should still run without threads. I'd love to contribute a fix, I'm just not sure where this line is or how it is generated (if anyone knows, please tell me).

**Steps to reproduce:**
This should occur with any HTML5 export using the Threads export type in a browser that does not provide the SharedArrayBuffer.

1. Create any web-compatible game (a game with a single scene).
2. Start a static web server (I used `python -m http.server`).
3. Start in Firefox (Firefox supports SharedArrayBuffers, but requires additional cross-origin isolation headers).

Additionally, this should be reproducible with:

- IE
- Chrome 91+ (without additional headers)
- Safari

**Minimal reproduction project:**

[HTML5ThreadsBug.zip](https://github.com/godotengine/godot/files/6360935/HTML5ThreadsBug.zip)

### PR DESCRIPTION
**Pull request by Faless**
Detects:
- WebGL version
- Fetch
- SharedArrayBuffer
- SecureContext
- CrossOriginIsolation
- AudioWorkletNode

Adds a warning to both the editor and export html shell.

Closes #47925.
Closes #48110.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks great to me :+1: 

I'll let @Calinou do a thorougher review/merge.

**Comment by sairam4123** [comment]
It would be nice to know if the web browser is mobile browser or pc browser!

**Comment by Faless** [comment]
> It would be nice to know if the web browser is mobile browser or pc browser!

There's no reliable way to do that, you should probably check for features like touchscreen support, display size, etc.

But none of those should prevent the engine from running when missing, if your game need a specific feature that's not otherwise required by the engine, you can check them either in JS directly, or using the [Godot <-> JavaScript interface](https://godotengine.org/article/godot-web-progress-report-9) (e.g. during startup)

**Comment by dsnopek** [comment]
This looks great! The check for "SharedArrayBuffer" is especially key, now that there isn't an un-threaded build of the web platform anymore.

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
