### PR TITLE
Clarified reason why a resource cannot be preload()'ed

### PR DESCRIPTION
**Pull request by anvilfolk**
_**Issue**_

When attempting to preload a resource file that Godot does not recognize, the error message is that the file does not exist, even if the file does exist.

Untitled

This might lead tiny innocent poor Godot contributor-wannabes on many hours of bug hunting thinking there is a significant issue with their other PR (#67314), when in fact there is simply no resource loader for .txt files ;)

_**To replicate**_

Create new Godot project. Create an empty text file. Create a new script and attempt to preload the text file. You will get the error message above.

_**Proposed fix in this PR**_

To simply change the error message to warn users that the reason they are not able to preload a resource might also be because there is no resource loader capable of handling that file extension. If custom resource loaders are at play, this should help Godot users pinpoint the source of the issue more rapidly (an incorrectly installed/configured resource loader, rather than an issue with the file system).

A better fix would be possible if ResourceLoader::exists() returned an int/enum instead of a boolean. This would make it possible to indicate exactly what type of error had occurred: 1) file not found or 2) extension not supported.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Doesn't load have the same error?
Also you could use `FileAccess::exists()` to check if the file actually exists and further clarify the error (should be done in editor builds only probably).

**Comment by anvilfolk** [comment]
> Doesn't `load()` have the same problem?

Interestingly, no! I believe the main difference is that preload() happens at script parsing time, whereas load() runs once the application is launched? The relevant lines from ResourceLoader::_load():
```
#ifdef TOOLS_ENABLED
	Ref<FileAccess> file_check = FileAccess::create(FileAccess::ACCESS_RESOURCES);
	ERR_FAIL_COND_V_MSG(!file_check->file_exists(p_path), Ref<Resource>(), "Resource file not found: " + p_path + ".");
#endif

ERR_FAIL_V_MSG(Ref<Resource>(), "No loader found for resource: " + p_path + ".");
```

So it correctly identifies the two scenarios! It also doesn't use FileAccess::exists() for figuring out whether the file exists. I don't really understand the subtleties of one method over the other, but I'll add 

> should be done in editor builds only probably

New to contributing to the engine. I believe that's what `#ifdef TOOLS_ENABLED` is doing, correct? I can wrap the error message that way for sure.

**Comment by KoBeWi** [comment]
> It also doesn't use FileAccess::exists() for figuring out whether the file exists. I don't really understand the subtleties of one method over the other.

`FileAccess::exists()` operates on absolute paths, while the approach used in `load()` works with `res://`. So actually it's better to use the latter.

> I believe that's what #ifdef TOOLS_ENABLED is doing, correct?

Yes.

**Comment by anvilfolk** [comment]
Made the messages more specific using the `FileAccess::ACCESS_RESOURCES`.

I didn't add the `TOOLS_ENABLED` directive because this is within the GDScript analyzer. I'm sure it knows how to handle error messages it receives through `push_error`. This makes these error messages consistent with all others within the analyzer.

**Review by KoBeWi — APPROVED** [review]

**Comment by anvilfolk** [comment]
> Thanks! And congrats for your first merged Godot contribution 🎉

Yayyy, and thanks everyone for their patience with me too! :) It's small but feels really lovely - parenting a 2 month old at home is all-consuming, and this makes me feel like an Actual Human™ again ;)

**Pull request merged**
