### PR TITLE
Rename `PRESET_WIDE` to `PRESET_FULL_RECT`

### PR DESCRIPTION
**Pull request by fire-forge**
This PR renames the Control `PRESET_WIDE` enum to `PRESET_FULL_RECT`. This naming better represents its actual behavior, makes it consistent with the Control editor menu (which already uses "Full Rect"), and makes it easier to find in the documentation.

Also renames the `ControlAlignWide` editor icon to `ControlAlignFullRect`.

Part of https://github.com/godotengine/godot/issues/54161#issuecomment-1068431646

### CODE REVIEW

**Comment by fire-forge** [comment]
Rebased, it's up to date now.

**Comment by fire-forge** [comment]
Rebased

**Comment by fire-forge** [comment]
Rebased. It might be good to merge this soon since beta feature freeze is coming within the next month or two, but rebasing is very easy for this PR, so no worries if it takes some time before anyone has a chance to review it :)

**Review by YuriSizov — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks good to me. Grepped the code as of this PR and it seems all properly replaced.

**Pull request merged**
