### PR TITLE
Add reset_smoothing() function to Camera2D

### LINKED ISSUE #5409: Camera2D force_update_scroll() doesn't work if smoothing is enabled
**Operating system or device - Godot version:**
Ubuntu 16.04 64-bit, 2.0.3

**Issue description** (what happened, and what was expected):
When I call `force_update_scroll()` to a Camera2D with smoothing enabled, I expect it to center the followed Node immediately.
For me I have no way to jump with the camera to a specific position without smoothing and enable smoothing right afterwards.

### PR DESCRIPTION
**Pull request by timoschwarzer**
Closes #5409

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@timoschwarzer What about margined "smoothing"?

**Comment by timoschwarzer** [comment]
Oh yes... Thanks!

**Comment by timoschwarzer** [comment]
@bojidar-bg isn't the drag margin already calculated in camera_pos?

**Comment by bojidar-bg** [comment]
@timoschwarzer you seem to have an unrealated commit in the PR, please rebase it out (for other PRs you should probably commit to new branches, you don't have to do it all on `master`).

**Comment by bojidar-bg** [comment]
@timoschwarzer Also, I mean, a function to really center on the position might be nice, since I'm not really sure that this version would center with drag margins. But, if you think this is out of this PR's scope, or that it is already possible, just leave that part alone ^^

**Comment by timoschwarzer** [comment]
So: Yes, I'll rebase tomorrow, this commit did its way into the PR by accident.
And yes, this function just cuts off the smoothing "effect". But I think a function to actually center the camera would also be helpful. I'll make a separate PR for that.

**Comment by bojidar-bg** [comment]
@timoschwarzer since drag margins can't be used with smoothing anyway (as of now), there is no much reason to have two functions. Also note that centering the camera should center it at `position + offset` not at `position` (and if one wants the latter, he should just use `set_offset(Vector2(0,0))` first)

**Comment by timoschwarzer** [comment]
Sorry, didn't had time yet... I'll try to rename on Thursday.

**Pull request closed without merging**
