### PR TITLE
Fixed error with python code that splits libs

### PR DESCRIPTION
**Pull request by gamedevsam**
https://github.com/godotengine/godot/issues/35022

### CODE REVIEW

**Comment by akien-mga** [comment]
Does this fix the build? Your comment in #35022 seems to infer that it's still broken after this change.

**Comment by bhgsbatista** [comment]
It fixes an iteration error in Python, but I ran into another error that doesn't seem related. So yes and no?

**Comment by akien-mga** [comment]
I'm not sure that the error you get afterwards is unrelated.
You can try with this workaround to confirm:
```
diff --git a/platform/windows/detect.py b/platform/windows/detect.py
index 500736bd3f..8fc5d21eca 100644
--- a/platform/windows/detect.py
+++ b/platform/windows/detect.py
@@ -297,7 +297,7 @@ def configure_mingw(env):
         # Force splitting libmodules.a in multiple chunks to work around
         # issues reaching the linker command line size limit, which also
         # seem to induce huge slowdown for 'ar' (GH-30892).
-        env['split_libmodules'] = True
+        env['split_libmodules'] = False
     else:
         env["PROGSUFFIX"] = env["PROGSUFFIX"] + ".exe"  # for linux cross-compilation
 
```

Note that it means that the final linking step might be extremely slow (several hours), but if you reach that stage properly, it would confirm that the `split_libmodules` logic is to blame. If it still fails as you reported in the other issue, it might be indeed that the two errors are unrelated.

**Comment by bhgsbatista** [comment]
Thanks for the info, I will check later when I get home and will report back my findings!

**Comment by gamedevsam** [comment]
Still ran into errors, doesn't seem like that fixed it (although it did do something different), here's the output:

```
$ scons -j6 platform=windows
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\Samuel\Dev\Godot\godot\SConstruct", line 3, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\Users\Samuel\Dev\Godot\godot\SConstruct", line 65, in <module>
Configuring for Windows: target=debug, bits=default
Using MinGW
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.

scons: warning: you do not seem to have the pywin32 extensions installed;
        parallel (-j) builds may not work reliably with open Python files.
File "C:\Users\Samuel\scoop\apps\scons\3.1.2\scons.py", line 204, in <module>
scons: Building targets ...
[Initial build] Compiling ==> platform\windows\godot_windows.cpp
[Initial build] Compiling ==> platform\windows\context_gl_windows.cpp
[Initial build] =====
[Initial build] b'g++.exe: error: /Foplatform\\windows\\godot_windows.windows.tools.64.obj: No such file or directory\ng++.exe: error: /c: No such file or directory\ng++.exe: error: /TP: No such file or 
directory\ng++.exe: error: /nologo: No such file or directory\ng++.exe: error: /DDEBUG_MEMORY_ALLOC: No such file or directory\ng++.exe: error: /DDISABLE_FORCED_INLINE: No such file or directory\ng++.exe: error: /DDEBUG_ENABLED: No such file or directory\ng++.exe: error: /DDEBUG_MEMORY_ENABLED: No such file or directory\ng++.exe: error: /DWINDOWS_ENABLED: No such file or directory\ng++.exe: error: /DOPENGL_ENABLED: No such file or directory\ng++.exe: error: /DWASAPI_ENABLED: No such file or directory\ng++.exe: error: /DWINMIDI_ENABLED: No such file or directory\ng++.exe: error: /DWINVER=0x0601: No such file or directory\ng++.exe: error: /D_WIN32_WINNT=0x0601: No such file or directory\ng++.exe: error: /DMINGW_ENABLED: No such file or directory\ng++.exe: error: /DMINGW_HAS_SECURE_API=1: No such file or directory\ng++.exe: error: /DPTRCALL_ENABLED: No such file or directory\ng++.exe: error: /DTOOLS_ENABLED: No such file or directory\ng++.exe: error: /DGDSCRIPT_ENABLED: No such file or directory\ng++.exe: error: /DMINIZIP_ENABLED: No such file or directory\ng++.exe: error: /DZSTD_STATIC_LINKING_ONLY: No such file or directory\ng++.exe: error: /DGLAD_ENABLED: No such file or directory\ng++.exe: error: /DGLES_OVER_GL: No such file or directory\ng++.exe: error: /DFREETYPE_ENABLED: No such file or directory\ng++.exe: error: /DSVG_ENABLED: No such file or directory\ng++.exe: error: /Ithirdparty\\nanosvg: No such file or directory\ng++.exe: error: /Ithirdparty\\freetype\\include: No such file or directory\ng++.exe: error: /Ithirdparty\\libpng: No such file or directory\ng++.exe: error: /Ithirdparty\\glad: 
No such file or directory\ng++.exe: error: /Ithirdparty\\zstd: No such file or directory\ng++.exe: error: /Ithirdparty\\zlib: No such file or directory\ng++.exe: error: /Iplatform\\windows: No such file 
or directory\ng++.exe: error: /I.: No such file or directory\n'
Compiling ==> platform\windows\crash_handler_windows.cpp
=====
=====
b'g++.exe: error: /Foplatform\\windows\\context_gl_windows.windows.tools.64.obj: No such file or directory\ng++.exe: error: /c: No such file or directory\ng++.exe: error: /TP: No such file or directory\ng++.exe: error: /nologo: No such file or directory\ng++.exe: error: /DDEBUG_MEMORY_ALLOC: No such file or directory\ng++.exe: error: /DDISABLE_FORCED_INLINE: No such file or directory\ng++.exe: error: /DDEBUG_ENABLED: No such file or directory\ng++.exe: error: /DDEBUG_MEMORY_ENABLED: No such file or directory\ng++.exe: error: /DWINDOWS_ENABLED: No such file or directory\ng++.exe: error: /DOPENGL_ENABLED: No such file or directory\ng++.exe: error: /DWASAPI_ENABLED: No such file or directory\ng++.exe: error: /DWINMIDI_ENABLED: No such file or directory\ng++.exe: error: /DWINVER=0x0601: No such file or directory\ng++.exe: error: /D_WIN32_WINNT=0x0601: No such file or directory\ng++.exe: error: /DMINGW_ENABLED: No such file or directory\ng++.exe: error: /DMINGW_HAS_SECURE_API=1: No such file or directory\ng++.exe: error: /DPTRCALL_ENABLED: No such file or directory\ng++.exe: error: /DTOOLS_ENABLED: No such file or directory\ng++.exe: error: /DGDSCRIPT_ENABLED: No such file or directory\ng++.exe: error: /DMINIZIP_ENABLED: No such file or directory\ng++.exe: error: /DZSTD_STATIC_LINKING_ONLY: No such file or directory\ng++.exe: error: /DGLAD_ENABLED: No such file or directory\ng++.exe: error: /DGLES_OVER_GL: No such file or directory\ng++.exe: error: /DFREETYPE_ENABLED: No such file or directory\ng++.exe: error: /DSVG_ENABLED: No such file or directory\ng++.exe: error: /Ithirdparty\\nanosvg: No such file or directory\ng++.exe: error: /Ithirdparty\\freetype\\include: No such file or directory\ng++.exe: error: /Ithirdparty\\libpng: No such file or directory\ng++.exe: error: /Ithirdparty\\glad: No such file or directory\ng++.exe: error: /Ithirdparty\\zstd: No such file or directory\ng++.exe: error: /Ithirdparty\\zlib: No such file or directory\ng++.exe: error: /Iplatform\\windows: No such file or directory\ng++.exe: error: /I.: No such file or directory\n'
=====
=====
b'g++.exe: error: /Foplatform\\windows\\crash_handler_windows.windows.tools.64.obj: No such file or directory\ng++.exe: error: /c: No such file or directory\ng++.exe: error: /TP: No such file or directory\ng++.exe: error: /nologo: No such file or directory\ng++.exe: error: /DDEBUG_MEMORY_ALLOC: No such file or directory\ng++.exe: error: /DDISABLE_FORCED_INLINE: No such file or directory\ng++.exe: error: /DDEBUG_ENABLED: No such file or directory\ng++.exe: error: /DDEBUG_MEMORY_ENABLED: No such file or directory\ng++.exe: error: /DWINDOWS_ENABLED: No such file or directory\ng++.exe: error: /DOPENGL_ENABLED: No such file or directory\ng++.exe: error: /DWASAPI_ENABLED: No such file or directory\ng++.exe: error: /DWINMIDI_ENABLED: No such file or directory\ng++.exe: error: /DWINVER=0x0601: No such file or directory\ng++.exe: error: /D_WIN32_WINNT=0x0601: No such file or directory\ng++.exe: error: /DMINGW_ENABLED: No such file or directory\ng++.exe: error: /DMINGW_HAS_SECURE_API=1: No such file or directory\ng++.exe: error: /DPTRCALL_ENABLED: No such file or directory\ng++.exe: error: /DTOOLS_ENABLED: No such file or directory\ng++.exe: error: /DGDSCRIPT_ENABLED: No such file or directory\ng++.exe: error: /DMINIZIP_ENABLED: No such file or directory\ng++.exe: error: /DZSTD_STATIC_LINKING_ONLY: No such file or directory\ng++.exe: error: /DGLAD_ENABLED: No such file or directory\ng++.exe: error: /DGLES_OVER_GL: No such file or directory\ng++.exe: error: /DFREETYPE_ENABLED: No such file or directory\ng++.exe: error: /DSVG_ENABLED: No such file or directory\ng++.exe: error: /Ithirdparty\\nanosvg: No such file or directory\ng++.exe: error: /Ithirdparty\\freetype\\include: No such file or directory\ng++.exe: error: /Ithirdparty\\libpng: No such file or directory\ng++.exe: error: /Ithirdparty\\glad: No such 
file or directory\ng++.exe: error: /Ithirdparty\\zstd: No such file or directory\ng++.exe: error: /Ithirdparty\\zlib: No such file or directory\ng++.exe: error: /Iplatform\\windows: No such file or directory\ng++.exe: error: /I.: No such file or directory\n'
=====
[Initial build] build_gles3_headers(["drivers\gles3\shaders\scene.glsl.gen.h"], ["drivers\gles3\shaders\scene.glsl"])
[Initial build] build_gles3_headers(["drivers\gles3\shaders\screen_space_reflection.glsl.gen.h"], ["drivers\gles3\shaders\screen_space_reflection.glsl"])
[Initial build] Executing builder function in subprocess: module_path='C:\\Users\\Samuel\\Dev\\Godot\\godot\\gles_builders.py', parameter_file='C:\\Users\\Samuel\\AppData\\Local\\Temp\\43949831c12a42baa0ed03e5883bf494.json', parameter_file_size=15333, target=['C:\\Users\\Samuel\\Dev\\Godot\\godot\\drivers\\gles3\\shaders\\scene.glsl.gen.h'], source=['C:\\Users\\Samuel\\Dev\\Godot\\godot\\drivers\\gles3\\shaders\\scene.glsl']
[Initial build] scons: *** [platform\windows\godot_windows.windows.tools.64.obj] Error 1
build_gles3_headers(["drivers\gles3\shaders\ssao.glsl.gen.h"], ["drivers\gles3\shaders\ssao.glsl"])
scons: *** [platform\windows\context_gl_windows.windows.tools.64.obj] Error 1
scons: *** [platform\windows\crash_handler_windows.windows.tools.64.obj] Error 1
Executing builder function in subprocess: module_path='C:\\Users\\Samuel\\Dev\\Godot\\godot\\gles_builders.py', parameter_file='C:\\Users\\Samuel\\AppData\\Local\\Temp\\6286539c93d743bea4c20227cc42a88f.json', parameter_file_size=15369, target=['C:\\Users\\Samuel\\Dev\\Godot\\godot\\drivers\\gles3\\shaders\\screen_space_reflection.glsl.gen.h'], source=['C:\\Users\\Samuel\\Dev\\Godot\\godot\\drivers\\gles3\\shaders\\screen_space_reflection.glsl']
Executing builder function in subprocess: module_path='C:\\Users\\Samuel\\Dev\\Godot\\godot\\gles_builders.py', parameter_file='C:\\Users\\Samuel\\AppData\\Local\\Temp\\0787d7f9e6544affb6183d8c8618eb7e.json', parameter_file_size=15331, target=['C:\\Users\\Samuel\\Dev\\Godot\\godot\\drivers\\gles3\\shaders\\ssao.glsl.gen.h'], source=['C:\\Users\\Samuel\\Dev\\Godot\\godot\\drivers\\gles3\\shaders\\ssao.glsl']
scons: building terminated because of errors.
```

**Comment by gamedevsam** [comment]
I fixed my problem by installing Microsoft Build Tools according to these instructions (I really didn't want to install the FULL Visual Studio setup since I use VSCode exclusively): https://github.com/ponylang/ponyc/blob/master/INSTALL.md#windows

https://github.com/godotengine/godot/issues/35022

**Pull request closed without merging**
