### PR TITLE
Rename TILE_SHAPE_ISOMETRIC to TILE_SHAPE_DIAMOND

### PR DESCRIPTION
**Pull request by ghost**
Isometric isn't as much a shape as it is a projection, naming it after the actual shape seems more fitting and descriptive.

My intent with this (aside from better naming) is to make the enumeration more agnostic and eventually shared between TileMap and GridMap/TileMap3D.

### CODE REVIEW

**Comment by groud** [comment]
Hmm, I understand that it makes sense to rename it for consistency, but I feel like this new name would be less, let's say, straight to the point than "isometric". Also, maybe I am wrong, but as a French person, I am more familiar with "isometric" (which has a the "isometrique" word equivalent in french) than with "diamond" (in French it's only the stone, not the shape).

But I would not mind that much changing it. After all, I you may want to simply create a diamond-shaped grid without having a vertical axis, and thus nothing in the "isometric" style.

I guess this is the kind of things that a poll could decide.

**Comment by octetdev2** [comment]
Personally, am only familiar with the term isometric because of game development and being familiar with camera projections and perspective.

In simple, non technical plain English I think diamond would be the most common term.
Just to illustrate, if you do an image search for shapes, geometric shapes or shapes for kids it's a diamond shape: 
image

It's also the context the word is used in, these are often found together:
- Triangle (intend to implement)
- Square
- Diamond

Where-as one of these stick out (ignoring half offset square for the time being):
- Triangle
- Square
- Isometric

Anyway I won't bikeshed too much here, your call 🙂

**Comment by MewPurPur** [comment]
Rhombus?

**Comment by YuriSizov** [comment]
Rhombus was proposed on RocketChat as a more precise and broadly known term. Isometric is not a shape, and diamond has different shape associations in different cultures.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting and the consensus was not to change this. "Isometric tile", while not 100% accurate, is a very widespread term in the game industry, and "diamond tile" isn't.

**Pull request closed without merging**
