### PR TITLE
continue in match makes the control flow fallthrough implemented

### LINKED ISSUE #160: Match-Case Fallthrough
**Describe the project you are working on:**
It's an RPG where when a character levels, specific stats are increased for example speed, skills, etc. The problem that this proposal will be addressing isn't specific to ours but moreso a feature that offers a solution to simplify the amount of work required for a situation.

**Describe the problem or limitation you are having in your project:**
Admittedly I wouldn't call it a problem, it's more of a QoL change where a keyword is added such as `fallthrough` where in a `match` statement, if used the next block is executed without the need for an additional check or comparison.
The problem we initially ran into was that if the player is say level 3, then we would like everything that happens to them on lvl 3 to happen, then 2, then 1.
```python
match 3:
    3:
        print("Only this prints.")
    2:
        print("But I want these ")
    1:
        print("to print too!")
```
However due to the way that `continue` currently works where it rechecks the value being matched, only `Only this prints` is put into console. We eventually found a solution (described below) however I still think the feature would be useful.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
I am primarily making this feature proposal because having used `switch case` before in other languages, I assumed that using the keyword `continue` would effectively act as a fallthrough. However it seems that Godot will continue to check for a match instead of just executing the next case as it would in Java for example. From my understanding that Godot attempts to be a very flexible toolkit not beholden to other languages/engines, but I think that adding fallthrough simplifies the problem solving needed for certain logic problems.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Not... entirely sure what to put here, but effectively what I'm proposing would be a keyword `fallthrough` or something along those lines where when used it continues and executes the next block without doing a check on the values. Adding a keyword this way would maintain backwards compatability so no previously written `match` statements would need to be rewritten.

**Describe implementation detail for your proposal (in code), if possible:**
A keyword `fallthrough` where if used in a match, the next code block is executed without the need for a comparison.
```python
match 3:
	case 3:
		print("This will print")
		fallthrough
	case 2:
		print("And so will this.")
		continue
	case 1:
		print("However not this.")
	_:
		print("But this will also print.")
```

Console Output:
```
This will print
And so will this.
But this will also print.
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Using the current `match` you could do this
```python
match 4:
    4:
        print("However this is very long, ")
        continue
    3, 4:
        print("and if I need to implement say 20 levels ")
        continue
    2, 3, 4:
        print("worth of rewards then the list of matches ")
        continue
    1, 2, 3, 4:
        print("gets really long the longer it goes.")
```
However this runs into a space problem where if it goes on to say value 100 it takes up a tone of space and it still has to run a check through the list of values.

Another alternative I thought of would be to start from the lowest level and check climbing up using if statements.

```python
var lvl = 4
if(lvl>=1):
    print("But this runs into a problem where ")
    if(lvl>=2):
        print("the indentation will keep pushing ")
        if(lvl>=3):
            print("the code furth off to the right ")
            if(lvl>=4):
                print("which is inconvenient.")
```
This helps cut back on the number of checks being done, however still runs into a space problem especially with the amount of indentation.
```python
for i in range(1, level + 1):
    match x:
        1:
            print("You're done at level 1!")
        2:
            print("No you fool, level 2!")
        3:
            print("Level 3, actually!")
        4:
            print("No more than level 4!")
```
This is actually the solution that we're using, however it doesn't solve a case where functionally you would like two of the options to be connected, and one to be independent.
```python
var val = 3
match val:
    case 3:
        print("hello")
        val = 2
        continue
    case 2:
        print("howdy")
    case 1:
        print("whoa")
```
This now solves the above problem, but requires the changing of the variable `val`. Alternatively the value could be duplicated to a temp value but that would introduce another variable if `fallthrough` was available this could be simplified to:

```python
var val = 3
match val:
    case 3:
        print("hello")
        fallthrough
    case 2:
        print("howdy")
    case 1:
        print("whoa")
```
No temp variable or value changing needed. It also simplifies a lot of the through process of how to solve the issue (as the above code blocks were in fact how we iterated on the issue).

**Is there a reason why this should be core and not an add-on in the asset library?:**
This could be an asset, however I think there can be situations other than my use case. In general for instance:
```
If option 3 happens, option 2 also happens.
If option 2 happens, option 3 doesn't happen.
And option 1 only occurs if option is picked.
```
It's mostly weird to me that seemingly I fallthrough wasn't implemented when `match` was first created, but of course that's just a personal preference. Though apparently the issue has been raised before so there is precedence.
https://www.reddit.com/r/godot/comments/b8gqli/match_fallthrough_with_continue_gdscript_help/

I apologies if this is way too long and verbose, but hopefully this can get added to Godot's core ~~and if not someone plz make an addon I will use it ty!~~

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: https://github.com/godotengine/godot-proposals/issues/160
continue-match

### CODE REVIEW

**Comment by Calinou** [comment]
Wasn't this implemented in Godot 3.0 already, or was the feature broken?

**Comment by ThakeeNathees** [comment]
@Calinou in 3.0 it doesn't fall through, continue to search for another match instead

**Comment by vnen** [comment]
This changes the meaning of `continue` in match statements. It's probably more useful like this (see godotengine/godot-proposals#160) but it's worth it pointing out, as it will also need a documentation change.

**Comment by ThakeeNathees** [comment]
documentation already states that continue will fall through the execution. (https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#match) 


> Crash-course for people who are familiar with switch statements:
> 1. Replace switch with match.
> 2. Remove case.
> 3. Remove any breaks. If you don’t want to break by default, you can use continue for a fallthrough.
> 4. Change default to a single underscore.

**Comment by swarnimarun** [comment]
WeW I was just writing a state machine and this tripped me up, bad... :3
(Trust me pure coincidence)

Would someone mind marking it a bug-fix pls? (At least it inconsistent with the docs)
@ThakeeNathees is absolutely correct.

Or should I fix it in the docs for now for older versions?

**Comment by vnen** [comment]
> Would someone mind marking it a bug-fix pls? (At least it inconsistent with the docs)
> 
> Or should I fix it in the docs for now for older versions?

That's the thing, I don't know if this is a bug. It's been there for so long now that I'm afraid some people might be relying on this behavior. Even though potentially "relying on a bug" is not safe, changes in behavior in a game engine can completely break the game. so it's usually avoided in a patch release. Maybe if we ever do a 3.3... (definitely will change in 4.0 though).

The reason I don't think it's a bug is because the original pull request mentions this as the implemented behavior:

> A `continue` stops execution in the current block and checks the next pattern instead.

However, the same person wrote the docs and stated that it was the same as a fallthrough in a `switch` statement, maybe missed at the time that a `switch` doesn't check the next case but just run the code in the block. It was probably an afterthought (which is evidenced by the original discussion #6845). Which is natural given that all the languages that provides pattern matching don't have any fallthrough mechanism. The discussion also mentions the implemented behavior as expected (to replace pattern guards in a way).

I would say that the documentation is wrong. When docs don't match code, usually the issue is in the docs. I was surprised by this too (since I've never used the "fallthrough" in a match statement), but that's how it was originally meant to be.

**Comment by swarnimarun** [comment]
@vnen oh didn't know about the discussion but that's the same conclusion I drew from it. The only reason it was a little weird was, that, I was expecting it to work like Python. 

I changed my code to follow a more pattern matching notion. Pretty sure it's something that was inspired from Rust.
My entire code just got a major facelift.  :)

@vnen
Also if we go by pattern matching notion I don't think this change is valid. Or even possible, afaik fall through and pattern matching is incompatible.

For example say,
```
var val = [120, 34]
match val:
    [var x, var y]:
        continue
    var z:
        # do something with z here
        pass
```

@ThakeeNathees How will it be handled by fallthrough.

Without fallthrough it will go from first case to second.

**Comment by ThakeeNathees** [comment]
```gdscript
1. match val:
2.    [var x, var y]:
3.       continue
4.    var z:
5.        # do something with z here
6.        pass
```
once the execution met `continue` it'll not check the pattern again. in the above code after the the line 3 `continue` the execution just jumps to line 5 and since line 6 don't have `continue` it'll jump out of the statement
@swarnimarun

**Comment by swarnimarun** [comment]
@ThakeeNathees exactly my point it is not handled..... :3

There is no definition of `z` which means it will error.

**Comment by groud** [comment]
I believe you misunderstood what fall through means in the documentation, and that the current behavior is perfectly expected.

The initial reseasonning behind the continue statement in match operations was first to avoid the need, as in a lot of other languages, to have a break in every statement. So instead of having this break, you would only have to specify when you want your code to check the next statement too.

So in GDscript, you never need breaks, but if you want the next statement to run too, you can use a continue.


Honesty the documentation has been really clear to me, I understand it' s not the behavior you have in several other languages with the continue keyword, but IMHO, it completely makes sense.

That being said, to avoid confusion with other languages we could maybe rename the "continue" keyword in a context of a match statement, but I don't have any idea of a good alternative.

**Comment by swarnimarun** [comment]
Maybe even worse. (I read the commit code too before mentioning the issue, but I have no idea how runtime issues like these are handled in GDScript but I very much assume the best case would be a perf hit and runtime error or worst case a segfault)...

Also from a pattern matching standpoint, this PR and proposal just don't seem useful.

A rematching case is much more powerful than a fallthrough.

Heck there are causes for concern that go much deeper,
```gdscript
match val:
   [var x, var y]:
       print(x, ", ", y)
       continue
   var x:
       print(x)
       continue
```
@ThakeeNathees 
What about this... \o\\
\o/ This is one fire I don't want to touch.... :3

**Comment by swarnimarun** [comment]
@groud That seems like a sensible solution.

Also, I was only confused because it wasn't clear to me that there was "pattern matching" with match statements. 
I think `rematch` is a good candidate for the change. LoL

On a serious note, I think some change to the docs to mention this behaviour for the older versions of the doc is necessary, and a rename for the `4.0` maybe. Because like me almost everyone, even ones who are used to pattern matching might just assume things about GDScript because of Pythonesque-ness of the language.
Docs being vague doesn't help.

**Comment by ThakeeNathees** [comment]
```gdscript
match val:
   [var x, var y]:
       print(x, ", ", y)
       continue
   var x:
       print(x)
       continue
```
@swarnimarun  if gdscript is an interpreted language we just can't jump from `continue` to `print(x)` because x is not defined. but here `var x` is already compiled so in the `var x:` pattern block x is already defined. 

but the problem is that since the capture val to x line doesn't execute the value of x will be the same as val when just before match block started to execute, I'll fix it if we decided to go with this however since the new parser will implement this and people might be relying on this behavior I'm agree with @vnen

**Comment by swarnimarun** [comment]
Oooof it was sarcasm both the times...
(But I guess it's nice if someone else is reading it)

I know what the issue is and print is an example when it will cause a bug silently, using a function that requires certain type would mean that it will show the error at entirely wrong place. This is something that just can't be fixed.

Because you can't just fall-through to next step here, you will have to match on pattern to get the next value. Which is exactly what it does at the moment...

So I am not sure what you plan to do to fix it but it is already fixed.
If you `continue` it starts matching with the next case pattern.

Only difference is if the match fails it skips the case.

This means it falls through but just doesn't do it without matching.

I am assuming you need a case like,
```gdscript
match month:
    Jan:
    Dec:
    Mar:
    May:
    Jul:
    Aug:
    Oct:
          return 31
```

You can do a clean "or" separated multi pattern match instead which is much more sane.
Which will be much better syntax.

Now if you want conditional fall through, that's IMHO what I like to call code smell.

You have array based matches like,
```gdscript
[var x, ..]
[_, _, var x]
```

If you want more pattern scenarios can be added which wouldn't be bad but I don't see how changing the usage of continue would be useful.

On the contrary now I find that it would make it rather confusing to use, as you won't be able to use any of the patterns with var bindings in the subsequent cases the same way as ones without them if you used continue based non-matching fall through.

Features that require adding exceptional cases without much useful functional enhancement are not something I would like.

At the very least I am against replacing the current functionality.

**Comment by vnen** [comment]
> I believe you misunderstood what fall through means in the documentation,

Honestly the way it's written begs for this misunderstanding. It's a series of steps on how to replace `switch` with `match` and states that if you need a fallthrough, you add `continue`. In a switch-case statement, "fallthrough" means just running the next block without checking for the value. Everyone would assume that's how it works. In fact, the text on how to replace a `switch` is wrong.

It only mentions `continue` once more:
> If you want to have a fallthrough, you can use `continue` to stop execution in the current block and check the ones below it.

 Which again misuses what a "fallthrough" means in this context. The text is now changed to better note it checks the next patterns. But I still think "fallthrough" should be removed (though this should be discussed in docs).

----

@swarnimarun 
> Also if we go by pattern matching notion I don't think this change is valid. Or even possible, afaik fall through and pattern matching is incompatible.
> 
> For example say,
> 
> ```gdscript
> var val = [120, 34]
> match val:
>     [var x, var y]:
>         continue
>     var z:
>         # do something with z here
>         pass
> ```

This is the reason it's not available in other languages as well. For example in Rust:

```rust
match x {
    None => None,
    Some(i) => Some(i + 1),
}
```

If you go from the first branch to the next, what would `i` stand for?

So the current behavior is the best we can do without getting in this conundrum.

However, it's only there to replace guards, so I wonder if we should remove `continue` and add guards... But that's another discussion anyway.

**Comment by swarnimarun** [comment]
@vnen I would like guards as well maybe we can discuss it in a thread or proposal for it. But for now continue is enough.

For 4.0 for sure though guards would be a better solution. But may as well discuss is further at a proper place.

**Comment by akien-mga** [comment]
Given that this is a fairly old PR and that the discussion is mostly about the feature proposal and not the implementation, I suggest we close it and keep the discussion focused in https://github.com/godotengine/godot-proposals/issues/160.

See also https://github.com/godotengine/godot-proposals/issues/4775 for a recent related proposal.

**Pull request closed without merging**
