### PR TITLE
Make softbody completelly stiff to attachment point

### LINKED ISSUE #23482: Softbody position reported wrongly
**Godot version:**
Godot 3.1. alpha 2

**OS/device including version:**
Win 7 x64
Radeon 6630M

**Issue description:**
I parented the softbody to another node (that is moved during gameplay). The softbody doesn't follow the parent node regardless of whether it is set to ignore parent's collision. 
Fine, I thought, I'll just forcibly sync the position to the parent node's... except it doesn't work either, both get_global_transform().origin [that is, global] and get_translation() [local] report 0,0,0 in all cases. 0,0,0 is also displayed in the remote scene tree.

**Steps to reproduce:**
Parent a softbody node to some other node that is moved around.

**Minimal reproduction project:**

Tagging @AndreaCatania

### LINKED ISSUE #23821: soft body move with kinematic body will lag behind
**Godot version:**
3.1 `a16d9c6`

**OS/device including version:**
Windows 7

**Issue description:**
a soft body parent with kinematic body will lag behind parent when parent move

default

You can see idle in left and moving in right. The distance between the cube and the soft body is different

**Steps to reproduce:**
make a soft body as child of a kinematic body.
move the kinematic body

**Minimal reproduction project:**
[test_project.zip](https://github.com/godotengine/godot/files/2594397/test_project.zip)

### PR DESCRIPTION
**Pull request by AndreaCatania**
With this PR, the soft bodies are now completely attached to the body!

ezgif com-video-to-gif(15)

ezgif com-video-to-gif(14)

Fixes #23821
Fixes #23482

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by Yogoda** [comment]
thank you!

**Comment by AndreaCatania** [comment]
@akien-mga do you think this can be cherry picked?

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
