### PR TITLE
Implementing 0-duration tweens

### LINKED ISSUE #29567: Allow 0-Duration Tweens
**Godot version:**
3.1 (Steam Live Version)

**OS/device including version:**
Windows, should be OS agnostic

**Issue description:**
When executing a tween with a 0 duration, an error is thrown and the tween is not executed. This means that you cannot *ever* pass a 0 into the duration of a tween to get an 'instant' tween. This is useful when programatically setting up Tweens and the case of 0 is sent.

The current workaround is to detect a duration of 0, and instead either set the property manually (which is extra, unneccesary code) or to instead send a very short duration, for example 0.001 (obtuse workaround...). Not implementing a workaround means that you don't get correct callback handling, values are not applied, and there is not even an obvious message stating why things are not happening.

Instead, sending a 0 duration to a tween should behave as an instantaneous tween.

**Steps to reproduce:**
Create a tween node and add it to the tree. Call interpolate_property on the node, and give it a duration of 0. Start the tween, and nothing will happen. Call interpolate_property with 0.001 and it will happen 'nearly instantly'.

**Minimal reproduction project:**
[InstantTween.zip](https://github.com/godotengine/godot/files/3264266/InstantTween.zip)
This project has three buttons which rotate a sprite. The 0 duration button fails to rotate the sprite. The 0.01 button rotates the sprite as expected. The 1.0 button rotates the sprite across 1 second. All three buttons should work but the first does not.

Thanks,
-Devin

### PR DESCRIPTION
**Pull request by DevinPentecost**
Some light refactor
Adding comments in functions

Pull request to implement 0-duration tweens and to do some refactoring.
Related to issue #29567

Thanks,
-Devin

*Bugsquad edit:* Fixes #29567.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good, though the added comments (which are very welcome) make it harder to spot the actual logic changes in this diff. I know you were asked to squash commits in the previous PR, but IMO this should could as two separate commits (which can stay in the same PR) adding comments on one end and the logic change on the other end.

As for comment style, I would ask to put a space after `//` to distinguish explanatory comments from commented out code.

**Comment by DevinPentecost** [comment]
Hi,

There are only a few logic changes, most of the changes are (much needed) comments :smile:

I'm surprised the CLang formatter didn't catch the comments - those should probably be included to ensure everyone matches. Personally I prefer no space but I'd rather be consistent.

Regarding commented out code, it really shouldn't be in the codebase in the first place... At least, that's always seemed like a 'best practice' I agree with.
I'll tweak the comments soon, but I probably won't split the commits into logic and comments just because git gives me enough headache as-is. Unless you really want me to...

Thanks,
-Devin

**Comment by akien-mga** [comment]
>  I'll tweak the comments soon, but I probably won't split the commits into logic and comments just because git gives me enough headache as-is. Unless you really want me to...

Fair enough. It does make the logic changes harder to parse though, but I spent some time reviewing them and it seems OK. Could you squash the comment style fixup in the original commit? Then it should be good to merge.

**Comment by DevinPentecost** [comment]
Hello,

Please review the (squashed) update and give me any more feedback.

Thanks!
-Devin

**P.S.** When do the Godot maintainers plan to require *all* PR's add/update descriptive comments for them to be accepted? 😄 😛

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
