### PR TITLE
[3.x] Batching - Add MultiRect command

### PR DESCRIPTION
**Pull request by lawnjelly**
Large groups of similar rects can be processed more efficiently using the `MultiRect` command. Processing common to the group can be done as a one off, instead of per rect.

Adds the new API to VisualServerCanvas, and uses the new functionality from Font, BitmapFont, DynamicFont and TileMap, via the VisualServerCanvasHelper class.

Can be switched on and off with project setting `rendering/batching/options/use_multirect` (defaults to on), just in case of regressions.

## Some measurements from a test benchmark
16 fps - without batching
190 fps - with batching
425 fps - with batching + `MultiRect`

_Test benchmark included below_
(reason these are faster seems to be the smaller font doesn't support all the chinese characters used in the benchmark, to save on the download size)
43 fps - without batching
450 fps - with batching
1000 fps - with batching + `MultiRect`

## Notes
* Increases performance in benchmarks of 2.4x over raw batching (large amounts of text, small fill rate)
* Real world performance increases will probably be a lot more modest, but seems worth doing as the PR is relatively simple, and opens up further avenues for optimization 
* Works through the fonts so will apply to most text using the `Font::draw()` command (passing a string, rather than by char)
* Also works for tilemap quadrants, there is special helper for caching and filling multiple `MultiRect`s within a quadrant.
* As discussed with @clayjohn , could potentially be very interesting to add to 4.x, as 4.x has no batching especially with vulkan. Although the specifics would need to be different - the font access may be different, and it would need a vulkan / GL backend for rendering the new command.

## Test benchmark
[batch_test_text.zip](https://github.com/godotengine/godot/files/10058014/batch_test_text.zip)
Press left button 10 times. Test with batching off / on, and multirect off on.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
Driver code looks fine to me. 

I am unsure about adding the multirect helper class. It seems like it may be pretty prone to issues, especially in a multithreaded context. What would happen if two threads tried to add multirects simultaneously? To me it looks like they would have to flush the multirect buffer each time they added a rect (but since there is no mutex here I'm not sure that would reliably happen) which of course would defeat the purpose of the multirect.

The other piece I am worried about is that it appears that the flush doesn't happen automatically. For example, I don't see a flush at all in dynamic_font.cpp and I worry that could lead to an edge case where the multirect is never submitted. 

Looking deeper I think I understand why its implemented like this. It seems you are avoiding allocating an array in user-space for each of the areas that rely on the multi-rect command. So having the shared helper makes sense. Additionally, ``canvas_item_add_texture_multirect_region()`` takes the whole multirect at once so you need to buffer the rects somewhere before calling ``canvas_item_add_texture_multirect_region()``.

It may be more efficient to just make use of the multirect class in user-space. For example, in tilemap.cpp it would be fairly trivial to buffer the rects and then just make one call to ``canvas_item_add_texture_multirect_region()``. 

Alternatively, perhaps VisualServerCanvasHelper could be implemented to return an allocated-on-demand multirect so you can expose the same easy to use API. Then at the end of a frame, you could flush all the multirects and put them back in the pool for reuse. This would take more memory than the current static approach, but it should be able to use the same easy-to-use API, add warnings for unflushed uses, and avoid threading issues.

**Comment by Calinou** [comment]
OS: Fedora 36
CPU: i7-6700K
GPU: Radeon RX 6900XT

Release build with LTO enabled used for both "Before" and "After (this PR)".

Type | Before | After (this PR)
Small window (empty) | 10353 FPS | 10290 FPS
Small window (full of text) | 1813 FPS | 1786 FPS
4K fullscreen (empty) | 9501 FPS | 9765 FPS
4K fullscreen (full of text) | 93 FPS | 90 FPS

**Comment by lawnjelly** [comment]
Just pushing a version of this with the `FixedArray` moved to a separate file, as I've encountered a number of instances recently where this would be useful for stack based arrays.

Additionally I'm going to try a separate alternative PR with a slightly different approach to the helper, with the idea we can choose which we like best. I'm intending this to use a stack based array for filling the `MultiRect`, rather than the approach in this PR (reusing arrays using a pool). Using the stack should be fine providing we place a limit on the number of rects (so as not to blow the stack), and avoids the dynamic allocations, and also avoids the need to use `Mutex` that is needed with the pool (at least for the non-tilemap case).

**Review by clayjohn — APPROVED** [review]
Looks good to me. I like this new approach to the canvas helper a lot more. 

Tested locally and can confirm that there is a pretty nice speedup with a lot of text in a scene (I tested with a few thousand labels)

**Pull request merged**
