### PR TITLE
Add secondary light to 3D Advanced Import Settings

### LINKED ISSUE #6707: Add a secondary light in the Advanced Import Settings preview
### Describe the project you are working on

a 3D Game with small objects and details

### Describe the problem or limitation you are having in your project

It's not much, but I want to preview the object with a little more detail

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I added a secondary light to the preview renderer and UI buttons to turn both lights on and off, just how its done in the materials viewer in the inspector

Screenshot from 2023-04-16 13-47-22

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I basically grabbed the code from EditorMaterialPreviewPlugin

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think this should be in core

### Is there a reason why this should be core and not an add-on in the asset library?

This improves the 3D importing experience using the editor

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
Added a second light for the 3D Preview Viewport and UI toggle buttons which resemble the ones in the EditorMaterialPreviewPlugin

 On branch add_secondary_light_to_3d_resource_importer
 Changes to be committed:
	modified:   editor/import/scene_import_settings.cpp
	modified:   editor/import/scene_import_settings.h

- *Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/6707.*

### CODE REVIEW

**Comment by aaronfranke** [comment]
Tested. I noticed that the two lights are coming from similar angles, one more on top and one more on the side. However, the material preview has light coming from very different angles, one light in the bottom and one light in the top right. Since one of the goals is to resemble that editor, shouldn't one of the lights be coming from below?

Also, in the material preview, the lights stay fixed relative to the camera. In this PR, the lights are fixed relative to the object. I think it would be better to have lights fixed relative to the camera, so you can view different parts of the model illuminated by the light at different angles relative to the model, instead of having a fixed part of the model lit at the same angle relative to the model.

**Comment by aaronfranke** [comment]
Since the original author was inactive, I sent them an email asking for write access to their repo so I can push to their PRs, which they granted to me. I have taken over this PR in order to bring it to the finish line. Most of the code is still Jeronimo's work, which is itself kept very similar to the mesh and material previewer code, so I have him marked as author.

I made the following changes to this PR:

* Rebase and fix conflicts.
* In a few minor ways, make the code more similar to the mesh and material previewers.
* Introduce a new method to Node3D called `set_as_top_level_keep_local`, which is like `set_as_top_level` but simpler, as it excludes the code that preserves the global transform (instead, it preserves the local transform).
* Implement both points in my comment above.
    * The light directions are now the same as the mesh and material previewers.
    * The lights are now fixed relative to the camera by default, for consistency with the mesh and material previews.
        * However, if you prefer the old behavior for consistency with an orbiting camera in the scene editor, that is also kept. There is now a button in the top-right that will toggle between the rotation modes: 
        Screenshot 2024-04-16 at 9 45 31 AM

This new button uses a new icon called "PreviewRotate", which is the same as "ToolRotate" but with an outline and brighter (thank you to @MewPurPur for making this).

PreviewRotate

**Review by fire — APPROVED** [review]
I am ok with adding the enhancement to add a secondary light. Did not compile the code.

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
