### PR TITLE
Add note that for _gui_input(event) event position is relative to the control origin

### LINKED ISSUE #4433: _gui_input(event) should specify that event position is relative to the Control origin
**Your Godot version:**
v3.2.3.stable.official

**Issue description:**
I've wasted about 10 minutes trying to figure out why my control node wouldn't follow my mouse (which was emulating touch screen). I finally figured out it was because for some reason the event.position was relative to the origin of the Control Node, which wasn't very clear in the documentation shown below

**URL to the documentation page (if already existing):**
[https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-gui-input](https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-gui-input)

### PR DESCRIPTION
**Pull request by skyace65**
Does what the title says. Closes https://github.com/godotengine/godot-docs/issues/4433

### CODE REVIEW

**Comment by mhilbrunner** [comment]
This needs a rebase :)

**Comment by skyace65** [comment]
Rebased.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.4.

**Pull request merged**
