### PR TITLE
Continuation of #27562

### LINKED ISSUE #27703: Skeleton is moving Y up a bit while using Blend2
**Godot version:**

Godot 3.1.1.devel 7f691e8bb

**OS/device including version:**

Kubuntu 19.04 / GTX 1070 Ti (driver version : 418.56)

**Issue description:**

Skelecton is moving Y up a bit while using `Blend2` with `AnimationTree` even though it is the same animations.

**Steps to reproduce:**
anim_tree_blend

**Minimal reproduction project:**

[AnimTree blend.zip](https://github.com/godotengine/godot/files/3048873/AnimTree.blend.zip)

### LINKED ISSUE #28004: Blending animations always bend towards zero and I can't understand why
3.1

when blending between 2 anim , animated nodes will dip into origin first and then blends towards anim 2

https://godotengine.org/qa/43541/blending-animations-always-bend-towards-zero-cant-understand

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
@akien-mga Sorry, I forgot these lines. Without this, the scale interpolation will still be broken.

Fix #27703
*Bugsquad edit:* Fixes #28004.

### CODE REVIEW

**Comment by reduz** [comment]
I always wondered if the way of doing scale interpolation is right, I feel it should be converted to a different scale somehow to be interpolated properly.

**Comment by reduz** [comment]
By logic, for scale to be interpolated properly, it should be in log2 scale instead of substracted to -1 (which is a bad hack), but then if scale is negative, or is interpolated between positive and negative, it will break.
So, in ttruth, not quite sure what to do about this.

**Comment by reduz** [comment]
For AnimationTree, I feel there is not much of a point in interpolating from negative to positive (never really seen this use case), so maybe we should actually store a Vector3 scale in log2 and a separate Vector3 with the sign (by default Vector3(1,1,1)), what do you think?

**Comment by guilhermefelipecgs** [comment]
> so maybe we should actually store a Vector3 scale in log2 and a separate Vector3 with the sign (by default Vector3(1,1,1)), what do you think?

I didn't understand why and how to use log2 for this, but anyway, I've removed the subtraction hack and it looks like it's working properly. I can scale from negative to positive using AnimaitonTree (even if it's not so useful) and I've tested TPS Demo as well.

I didn't see any problem the way it is so I guess we can keep it that way.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
