### PR TITLE
Correct null and boolean values being capitalised by the str command

### LINKED ISSUE #52060: Boolean values use lowercase but print in uppercase
### Godot version

3.4 beta 4

### System information

Windows 10

### Issue description

Boolean values must be specified in lowercase 
```
var my_true_var:bool = true
var my_false_var:bool = false
```
Yet when I print these out for debugging purposes they are printed with an uppercase letter
```
print(my_true_var)
True
print(my_false_var)
False
```
For my save/load functions for my game I need to manually correct the case to be able to feed game variables. I believe the case should be preserved so the keywords are correct.

### Steps to reproduce

```
	var mybool:bool=false
	
	print_debug(mybool)
	printerr(mybool)
	printraw(mybool)
	printt(mybool)
	push_error(str(mybool))
	push_warning(str(mybool))
	prints(mybool)
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by balloonpopper**
Closes https://github.com/godotengine/godot/issues/52060
This is to stop str from capitalising null, true and false values. The uppercase output is not consistent with gdscript's convention.

### CODE REVIEW

**Comment by pycbouh** [comment]
Be sure to build it locally and test that it works. It seems that at least the tests expect the capitalized values (which is to be expected), so they need to be updated as well.

**Review by mhilbrunner — APPROVED** [review]
Built and tested, found no issues running tests or in my various test projects.

**Review by reduz — APPROVED** [review]

**Review by Calinou — CHANGES_REQUESTED** [review]
Thanks!

**Comment by balloonpopper** [comment]
Thanks for the help @mhilbrunner @pycbouh @neikeq @reduz @Calinou

**Pull request merged**
