### PR TITLE
Rename PointLight2D to SpriteLight2D

### PR DESCRIPTION
**Pull request by AaronRecord**
See https://github.com/godotengine/godot/issues/16863#issuecomment-869587241
And https://github.com/godotengine/godot/pull/50066

### CODE REVIEW

**Comment by Yozzaxia1311** [comment]
Looking at [this comment](https://github.com/godotengine/godot/issues/16863#issuecomment-869587241), I'm not sure this isn't a misspelling of "SpotLight".

**Comment by YeldhamDev** [comment]
But doesn't this miss the point of the "2D/3D" suffixes? There isn't any `SpriteLight3D`.

**Comment by LightningAA** [comment]
@YeldhamDev There isn't (currently) a `PointLight3D` either, but it's still `PointLight2D`. There isn't a `CircleShape3D`, but there is a `CircleShape2D`. I think it's better to explicit, especially since there is already a `Sprite3D`.

**Comment by pycbouh** [comment]
> Looking at [this comment](https://github.com/godotengine/godot/issues/16863#issuecomment-869587241), I'm not sure this isn't a misspelling of "SpotLight".

It's not. It's a light based off of a sprite, a texture. But SpotLight would work in this case as well.

**Comment by pycbouh** [comment]
@YeldhamDev Maybe we can keep the suffix to refer to the kind of light our light extends, Light2D or Light3D, even if for the current object itself it doesn't make much difference.

**Comment by LightningAA** [comment]
Rebased.

**Comment by mhilbrunner** [comment]
There was no consensus for this in today's PR meeting; if we're going to rename this, we need to do this via proposal with a clear consensus for a new name.

**Pull request closed without merging**
