### PR TITLE
vulkan: Sync loader, headers and glslang to sdk-1.2.154.0

### PR DESCRIPTION
**Pull request by akien-mga**
Actually sdk-1.2.154.1 for Vulkan-Loader.

glslang is updated to bacaef3237c515e40d1a24722be48c0a0b30f75f which is the
known-good version for Vulkan-ValidationLayers 1.2.154.0.

COPYRIGHT.txt was synced with the current version of the glslang LICENSE.txt,
and `glslang/register_types.cpp` now uses the upstream definition for its
default builtin resource instead of hardcoding it.

---

@bruvzg Could you check that it works fine on macOS?

BTW I saw that VkMemAlloc has some fixes for macOS SDK 11.0 in its `master` branch, but they're not in any tagged release yet. We might want to update to latest `master` for compatibility: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/pull/137.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks like my local build picked up headers from `/usr/include`, I'll have to uninstall build deps and fix it.

**Comment by bruvzg** [comment]
With the dummy `build_info.h` (seems to be used only to print version info, I have defined random values of `GLSLANG_VERSION_...` macros), it is working.

**Comment by akien-mga** [comment]
Added missing `build_info.h` (generated by `cmake . && make`, includes version numbers parsed from `CHANGES.md`).

**Comment by bruvzg** [comment]
Rechecked with the proper `build_info.h` in case it's not just for print, also works fine.

**Comment by bruvzg** [comment]
> BTW I saw that VkMemAlloc has some fixes for macOS SDK 11.0 in its master branch, but they're not in any tagged release yet. We might want to update to latest master for compatibility: GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#137.

Seems like this is relevant only when targeting 10.15 with 10.15 SDK, but we are targeting 10.12 for x86_64 and 11.0 for arm64.

**Pull request merged**
