### PR TITLE
Fix property selector not displaying certain properties/methods

### LINKED ISSUE #28136: Can't access rotation and transform in Node2Ds and call functions on Transform2Ds
In VisualScript you can only get access to members that show up in the inspector, which means that rotation (not rotation_degrees) and transform members of Node2D are inaccessible. Furthermore, you can't call functions on a Transform2D object as you would with others, you have to search for Transform in the node search to get a `Transform Do X` node. This is the same with all basic types.

Why does the `Basic Type` call mode even exist?
image

### LINKED ISSUE #47837: Visual Script property selector
3.3.rc8
WIN 10 
GLES3

The visual script editor provides a limited amount of property's to select from. 
That the VSeditor gives the same options as GDscript

I will give a example using the Timer Node timer.time_left
Timer Node VScript autocompete example
Timer Node GDScript autocompete example
Timer Node propeties sourcecode

I assume this is due to this code difference in propery_selector.cpp vs visual_script_property_selector.cpp
(my understanding of c++ and the Godot project is minimal)

Control drag property
Add visual script try to get any autocomplete hints in the editor

[Projects debug.zip](https://github.com/godotengine/godot/files/6299280/Projects.debug.zip)

Being able to edit the inspector-property in line edit would be a awesome work around

### LINKED ISSUE #49062: Can't select another function for Array in Visual Script. Functions suggestion box is empty
**Godot version:**

3.3

**OS/device including version:**

macOS

**Issue description:**

Tried to change Array.front() to Array.back()
Saw emptiness in the suggestion window

It seems this one affects Array. Other types are not affected for some reason...
But I tried only Object, Node, Node2D.

**Steps to reproduce:**
1) Create node Array.front()
2) Try to change function in the node inspector
3) See empty suggestions, no way to change
изображение

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by briansemrau**
Fixes #47837
Fixes #28136

This pull request fixes several issues where PropertySelector was not showing properties/functions that you would reasonably expect to find.

Should be cherry-pickable for 3.3 and 3.x.

<i>Bugsquad edit</i>: + Fixes #49062

---

Update:
Here are screenshots demonstrating these changes. (Shown in 3.x but should be the same in 4.0/master)

<details>
<summary>Property Selector</summary>
Before:

image

And after:
image
</details>

<details>
<summary>Select method on variant/basic type</summary>
Before:

image

And after:
image
</details>

<details>
<summary>Visual script property selector</summary>
Before:

image

And after:
image
</details>

### CODE REVIEW

**Comment by briansemrau** [comment]
Seems the static check didn't like how I multi-lined an if-condition for clarity. Should I just accept the "proper" formatting even if it means the code will be harder to read?

**Comment by Calinou** [comment]
> Seems the static check didn't like how I multi-lined an if-condition for clarity. Should I just accept the "proper" formatting even if it means the code will be harder to read?

Yes :slightly_smiling_face:

**Comment by DavidCambre** [comment]
Tested set&get Spatial global_transform
Tested set&get Timer time_left
So confirmed that #47837 will be fixed by this PR.
While it arguable that the PropertyInfo needs to be set correctly in the source class.
I do prefer a catch all solution like this.

**Comment by DavidCambre** [comment]
Tested issue #28136 and there I do not jet see change.
Not jet Fixed

**Comment by briansemrau** [comment]
@DavidCambre I wasn't sure what you thought was missing to fix #28136, but I just added one more change that I thought was relevant. If this PR as it now stands doesn't look complete, let me know what you think is missing. I added screenshots for the changes this PR implements.

**Comment by DavidCambre** [comment]
@briansemrau Sorry totally forgot to answer.
If I check VisualScriptFunction Call or Get and specify Basic_type I only get suggestions for Object and not the variants.
I replied in 28136 whit my findings of the last 2 days.
This weekend Ill try to check if there is a better solution to 47837

**Comment by DavidCambre** [comment]
@briansemrau my apologies.
I need to bee more specific.

> Tested issue #28136 and there I do not jet see change.
> Not jet Fixed
You seem to only have fixed Call and not Get or Set Basic Type.
While most, if not all, of the set get basic_type functions are covered by (de)constructors. The workflow suggest this should work.
If there are now Idea's to fix set get basic type we should indeed consider removing basic_type from set get.

> So confirmed that #47837 will be fixed by this PR.
> While it arguable that the PropertyInfo needs to be set correctly in the source class.
I tried checking and setting a few in source class. Did not make a PR for it, think it will have unintended side effects.
So this solution seems the best approach.

Conclusion: Good fix thanx

**Review by Gallilus — APPROVED** [review]

**Comment by fire** [comment]
Superseded by https://github.com/godotengine/godot/pull/56252

**Comment by Gallilus** [comment]
Not jet fixed with https://github.com/godotengine/godot/pull/56252

**Comment by akien-mga** [comment]
Is this still relevant for the current `master` branch? [We just removed VisualScript](https://github.com/godotengine/godot/pull/64822), but this PR also had changes for the main property selector which might still be needed?

**Comment by brianwinterpixel** [comment]
Back when I first created this PR, I was using the property hints within a module I was creating, not VisualScript. 
```	PROPERTY_HINT_PROPERTY_OF_VARIANT_TYPE, ///< a property of a type	PROPERTY_HINT_PROPERTY_OF_BASE_TYPE, ///< a property of a base type	PROPERTY_HINT_PROPERTY_OF_INSTANCE, ///< a property of an instance	PROPERTY_HINT_PROPERTY_OF_SCRIPT, ///< a property of a script & base
```
These hints are a very handy tool for the inspector.

I'm unsure the status of this PR or of the relevant issues, but it may very well still be relevant.

**Comment by KoBeWi** [comment]
This needs to  be remaked for 3.x branch.

**Pull request closed without merging**
