### PR TITLE
Add history dock

### LINKED ISSUE #953: Add a undo/redo history log
**Describe the project you are working on:** This applies to any game or project

**Describe the problem or limitation you are having in your project:**
I don't know which action I can undo and which action I can't undo. Jumping back and forth in the undo history is anything but transparent or user friendly.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A panel with a history log for all undoable steps. Branching undo tree would be amazing, but a linear list would already be a great improvement.
Issue moved here from https://github.com/godotengine/godot/issues/25919

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
undohistory

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
I don't think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a core usability feature.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/953
godot windows tools x86_64_DafEaqmnCw

### CODE REVIEW

**Comment by Calinou** [comment]
In a future PR, I wonder if it could be possible to associate icons to each history actions. This would make it a bit easier to navigate long histories by improving visual grepping :slightly_smiling_face:

**Comment by KoBeWi** [comment]
Actually it could be in EditorUndoRedoManager and shouldn't be difficult to do, but we have to deteine what icons to use. Assign them automatically based on type? Setting icon manually for each action is lots of code.

**Comment by Zireael07** [comment]
Move/scale/rotate, for instance, could reuse the move/scale/rotate toolbar button icons, and yep, assigning automatically by type is probably the way to go.

**Review by akien-mga — APPROVED** [review]
Found out on Reddit that we hadn't merged this yet.

Looks fairly good to me, and it's a popular one, I think it could be merged for beta 5 if there's no outstanding concern.

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
The ability to hide this dock is missing from the editor feature profiles menu:

Screenshot 2022-11-02 at 2 31 11 PM

**Comment by golddotasksquestions** [comment]
Thank you KoBeWi!!

**Pull request merged**
