### PR TITLE
Change return value of Tree.create_item() from Object to TreeItem

### LINKED ISSUE #20343: Tree API doesn't use proper return / argument types in C#
**Godot version:**
`master` / cfcb6e11f25ad

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
In many methods in `Tree` API, like `CreateItem`, `GetItemAreaRect` don't use specific return or argument types but `Object`. To ensure type safety, we better change them to use proper types like `TreeItem` instead.

### PR DESCRIPTION
**Pull request by KellyThomas**
Fixes #20343

### CODE REVIEW

**Comment by akien-mga** [comment]
I wonder what was the original purpose of those "bind helpers" and if they're still needed. They seem to all use `Object` instead of `TreeItem`, relying on casting to then call the right API - seems unneeded if we could have `TreeItem` from the start.

**Comment by KellyThomas** [comment]
That I couldn't say.

To my eye accepting a general type, then casting to a more specialised type without any handling for when the cast fails is asking for problems.

This change stops us from having a similar code smell in the calling code, but if the bind helpers are not needed we may be able to do away with them entirely.

**Comment by Noshyaar** [comment]
Related to #21160 ?

**Comment by KellyThomas** [comment]
@Noshyaar I think so.

If I try to bind directly to `create_item()` I get these errors:
```
godot\core\method_bind.h(68): error C2440: 'return': cannot conver
t from 'const Variant' to 'TreeItem *'
godot\core\method_bind.h(68): note: No user-defined-conversion ope
rator available that can perform this conversion, or the operator cannot be call
ed
godot\core\method_bind.h(66): note: while compiling class template
 member function 'TreeItem *VariantCaster<P1>::cast(const Variant &)'
        with
        [
            P1=TreeItem *
        ]
godot\core\method_bind.gen.inc(1697): note: see reference to funct
ion template instantiation 'TreeItem *VariantCaster<P1>::cast(const Variant &)'
being compiled
        with
        [
            P1=TreeItem *
        ]
godot\core\method_bind.gen.inc(1697): note: see reference to class
 template instantiation 'VariantCaster<P1>' being compiled
        with
        [
            P1=TreeItem *
        ]
godot\core\method_bind.gen.inc(1674): note: while compiling class
template member function 'Variant MethodBind2R<T,R,P1,P2>::call(Object *,const V
ariant **,int,Variant::CallError &)'
        with
        [
            T=Tree,
            R=TreeItem *,
            P1=TreeItem *,
            P2=int
        ]
godot\core\method_bind.gen.inc(1724): note: see reference to class
 template instantiation 'MethodBind2R<T,R,P1,P2>' being compiled
        with
        [
            T=Tree,
            R=TreeItem *,
            P1=TreeItem *,
            P2=int
        ]
godot\core\class_db.h(245): note: see reference to function templa
te instantiation 'MethodBind *create_method_bind<Tree,TreeItem*,TreeItem*,int>(R
 (__cdecl Tree::* )(P1,P2))' being compiled
        with
        [
            R=TreeItem *,
            P1=TreeItem *,
            P2=int
        ]
scene\gui\tree.cpp(3776): note: see reference to function template instantiation
 'MethodBind *ClassDB::bind_method<MethodDefinition,TreeItem*(__cdecl Tree::* )(
TreeItem *,int)>(N,M,const Variant &,const Variant &)' being compiled
        with
        [
            N=MethodDefinition,
            M=TreeItem *(__cdecl Tree::* )(TreeItem *,int)
        ]
scons: *** [scene\gui\tree.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by KellyThomas** [comment]
Just for clarification I will state that resolving the issue with the Object type parameters is beyond my C++ skill level.

I won't be able to extend this PR beyond its current scope of changing to a more specific return type.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
