### PR TITLE
Add more flexibility to 3X3 autotiles

### LINKED ISSUE #16511: Autotile doesn't support uncommon bitmasks
**Godot version:**
Godot 3

**Issue description:**
Uncommon bitmasks do not work.
j8x2wky

### PR DESCRIPTION
**Pull request by ghost**
Removes some conditions that were there to create compatibility of 2X2 conversion to 3X3, but limited a number of possibilities, such as stairs. A runtime conversion of 2X2 to 3X3 bitmasks is a extremely rare, if even that, thing to need (and even so it's still possible), and an editor conversion can be quickly fixed, so it's not a big deal.

Addresses  #16511

### CODE REVIEW

**Comment by reduz** [comment]
@MarianoGnu

**Comment by MarianoGnu** [comment]
yeah, makes sense, but at the same time might cause backward compatibility breackage if omeone expected the previous behabiour, but should be safe, since this wont change already saved maps, unless they are generated randonly using code instead of drawing from the editor. i think a notice on the changelog about this in the next release is enought.

**Comment by MarianoGnu** [comment]
All right, finished reviewing the code, i think it's safe to merge this

**Comment by akien-mga** [comment]
Thanks for the fix and the review!

**Pull request merged**
