### PR TITLE
Fix AudioEffectRecord not working without thread support

### PR DESCRIPTION
**Pull request by marcelofg55**
This allows the AudioEffectRecord to work even without thread support on the platform. Currently on the javascript platform this effect doesn't works, this PR fixes this problem.

### CODE REVIEW

**Comment by reduz** [comment]
I dont kind of like this, because it makes audio effects dependent only from the buses, and I eventually wanted to make it so you can add them in other places. Maybe having a system where you can (with proper mutex) register some sort of generic thread update callback in AudioServer for anything that needs it could be useful? I think Godot 2.1 had something like this..

**Comment by marcelofg55** [comment]
@reduz Just changed the PR to use callbacks.

**Comment by akien-mga** [comment]
@reduz approved now :)
```
21:08 <reduz> looks fine
21:08 <reduz> i thought he wanted an extra thread, but i guess this is good too
```

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
