### PR TITLE
Replaces (and extends) the anchor menu to a Layout one

### LINKED ISSUE #11723: Feature Request: Anchor drop down updates margins
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 2.1.4

**Issue description:**
Changing a node's anchor settings via the dropdown does not move the node.  This seems counter-intuitive and unsatisfying.  For example, selecting "full rect" should expand the node (setting all margins to 0) to fill its parent.

### PR DESCRIPTION
**Pull request by groud**
The presets menus changes both anchors and margins. But it has also two submenus for moving either "Anchors only" or "Margins only"

Not the best gif ever but you can see the changes:
output

Closes #11723.

### CODE REVIEW

**Comment by groud** [comment]
This might need new icons also. @djrm ? ^^

**Comment by hpvb** [comment]
niiiice!

**Comment by djrm** [comment]
maybe alignment is a better name for the menu.

@groud also, whats the use case of preset margins (just wondering).

**Comment by NathanWarden** [comment]
Nice, this will come in very handy, great job!

**Comment by groud** [comment]
> maybe alignment is a better name for the menu.

I don't know. Why not but it's still a little bit unclear. I though about "Layout" or "Layout presets".
"Alignment" is not that bad too. 
It's called "Anchors presets" in unity, but if you have any other examples I'd be happy to hear them. :)

> @groud also, whats the use case of preset margins (just wondering).

Good question, actually I think you are right and this is not that useful. As the function is now available in the API I put it into the menu but it might not be that useful. I'll update the PR and remove it. :)

**Comment by djrm** [comment]
@groud great, i didnt see any use or effect of preset margins, so maybe if you are removing them, we could go back to the old margins menu (that would be simpler).

**Comment by groud** [comment]
@djrm You mean as a name ? But by default this new menu moves both the Margins and Anchors. I can remove the "Margins only" menu but the remaining is useful.

**Comment by groud** [comment]
I updated the PR removing the menu to set the margisn only. I also renamed the menu to "Layout".
That'd be cool if we could have a green icon to understand it's for GUI items.

**Pull request merged**
