### PR TITLE
Buildsystem: Use pkg-config for miniupnpc and mbedtls

### PR DESCRIPTION
**Pull request by ghost**
Miniupnpc added pkg-config files in 2.2.3 but we require 2.2.8 https://github.com/miniupnp/miniupnp/commit/5a398006b90e35942ffd8015a9f792df9ec97fd8

MbedTLS added pkg-config files in 3.6.0 while we require 3.6.1 https://github.com/Mbed-TLS/mbedtls/blob/development/ChangeLog

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Maybe we can do something like this instead to preserve support for mbedtls 2.28 LTS:
```diff
diff --git a/platform/linuxbsd/detect.py b/platform/linuxbsd/detect.py
index 2fd573da75..e8c2f88435 100644
--- a/platform/linuxbsd/detect.py
+++ b/platform/linuxbsd/detect.py
@@ -279,16 +279,18 @@ def configure(env: "SConsEnvironment"):
         env.ParseConfig("pkg-config libwebp --cflags --libs")
 
     if not env["builtin_mbedtls"]:
-        # mbedTLS does not provide a pkgconfig config yet. See https://github.com/ARMmbed/mbedtls/issues/228
-        env.Append(LIBS=["mbedtls", "mbedcrypto", "mbedx509"])
+        # mbedTLS only provides a pkgconfig file since 3.6.0, but we still support 2.28.x,
+        # so fallback to manually specifying LIBS if it fails.
+        try:
+            env.ParseConfig("pkg-config mbedtls mbedcrypto mbedx509 --cflags --libs")
+        except:
+            env.Append(LIBS=["mbedtls", "mbedcrypto", "mbedx509"])
 
     if not env["builtin_wslay"]:
         env.ParseConfig("pkg-config libwslay --cflags --libs")
 
     if not env["builtin_miniupnpc"]:
-        # No pkgconfig file so far, hardcode default paths.
-        env.Prepend(CPPPATH=["/usr/include/miniupnpc"])
-        env.Append(LIBS=["miniupnpc"])
+        env.ParseConfig("pkg-config miniupnpc --cflags --libs")
 
     # On Linux wchar_t should be 32-bits
     # 16-bit library shouldn't be required due to compiler optimizations
```

(Or if SCons provides a version of `ParseConfig` that doesn't raise an exception but just returns an error code, we could use that.)

**Comment by dustdfg** [comment]
Looks reasonable but it didn't throw any exception even on empty command :sweat_smile:
Moreover in the start of the file we check if pkg-config exist by using `pkgconf_error = os.system("pkg-config --version > /dev/null")` so...

**Comment by dustdfg** [comment]
And later check if lib is available with `if os.system("pkg-config --exists xkbcommon") == 0:  # 0 means found`

**Comment by akien-mga** [comment]
It does throw an exception for me if there's no pkg-config file for mbedtls. But indeed `os.system("pkg-config --exists mbedtls") == 0` is a better option, so I suggest this diff, which works fine for me locally (uses the first branch when `mbedtls-devel` is installed, and the `else` branch otherwise).

```diff
diff --git a/platform/linuxbsd/detect.py b/platform/linuxbsd/detect.py
index 2fd573da75..c8202b147d 100644
--- a/platform/linuxbsd/detect.py
+++ b/platform/linuxbsd/detect.py
@@ -279,16 +279,18 @@ def configure(env: "SConsEnvironment"):
         env.ParseConfig("pkg-config libwebp --cflags --libs")
 
     if not env["builtin_mbedtls"]:
-        # mbedTLS does not provide a pkgconfig config yet. See https://github.com/ARMmbed/mbedtls/issues/228
-        env.Append(LIBS=["mbedtls", "mbedcrypto", "mbedx509"])
+        # mbedTLS only provides a pkgconfig file since 3.6.0, but we still support 2.28.x,
+        # so fallback to manually specifying LIBS if it fails.
+        if os.system("pkg-config --exists mbedtls") == 0:  # 0 means found
+            env.ParseConfig("pkg-config mbedtls mbedcrypto mbedx509 --cflags --libs")
+        else:
+            env.Append(LIBS=["mbedtls", "mbedcrypto", "mbedx509"])
 
     if not env["builtin_wslay"]:
         env.ParseConfig("pkg-config libwslay --cflags --libs")
 
     if not env["builtin_miniupnpc"]:
-        # No pkgconfig file so far, hardcode default paths.
-        env.Prepend(CPPPATH=["/usr/include/miniupnpc"])
-        env.Append(LIBS=["miniupnpc"])
+        env.ParseConfig("pkg-config miniupnpc --cflags --libs")
 
     # On Linux wchar_t should be 32-bits
     # 16-bit library shouldn't be required due to compiler optimizations
```

**Review by akien-mga — APPROVED** [review]

**Comment by darksylinc** [comment]
This PR breaks `builtin_miniupnpc=yes`.

See #99196

**Comment by darksylinc** [comment]
Also falling back to using builtin `mbedTLS` is the wrong approach.

If the user specifies to use the builtin, it should error out to point out the built in cannot be used (which can happen if the package is not installed).

**Pull request merged**
