### PR TITLE
Mono: Default to not shipping C# scripts content

### LINKED ISSUE #20053: Mono exporting requires CS files to be exported as well
**Godot version:** e2b7a68db450d0d48d005719731619a49f96b7c8

**OS/device including version:** Win10 x64

**Issue description:**

Exporting a mono-based game requires you to include the cs files in the exported pck file, otherwise the engine fails to load said scripts despite the compiled assembly being present in the pck. This is especially an issue for closed-source/commercial games which probably don't want to ship the source to their game in the pck.

I'm guessing that fixing this will require #15661 unfortunately.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #20053.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Love the branch name.

**Comment by neikeq** [comment]
wow how to unmerge... such disrespec

**Comment by aaronfranke** [comment]
No leave it. It is absolutely proprietary, that's the point isn't it? :smile:

**Comment by hpvb** [comment]
Cherry picked into 3.0.6

**Pull request merged**
