### PR TITLE
Show driver information in verbose mode

### PR DESCRIPTION
**Pull request by techtonik**
This helps to debug graphics crashes (issue #1162)

### CODE REVIEW

**Comment by reduz** [comment]
does it not crash before that?

On Fri, Feb 12, 2016 at 5:30 PM, anatoly techtonik <notifications@github.com

**Comment by techtonik** [comment]
@reduz no - it crashes later at 10808 - https://github.com/godotengine/godot/issues/1162#issuecomment-183172706

**Comment by techtonik** [comment]
Rebased, made info available only in verbose mode and make it show video driver name instead of just GLEW version.

**Comment by techtonik** [comment]
It is better to print info about video driver from the caller who chooses it. Is it possible?

**Comment by akien-mga** [comment]
Not sure if it really provides useful information, but it doesn't hurt much either.

What could be actually interesting is to check with ``glewIsSupported`` if the needed GL API is supported: http://glew.sourceforge.net/basic.html

**Comment by techtonik** [comment]
I may try this. But how to get know what that "needed GL API" consists of?

**Pull request merged**
