### PR TITLE
Update the Android splash screen logic

### LINKED ISSUE #62863: Splash Image on Android not showing
### Godot version

3.5 rc6

### System information

Windows 11

### Issue description

For some reason the splash image has stopped showing on android.  I have included a simple project that should show the Godot Icon at start.  It will on windows and will not on Android.
BTW, The "just show a background color" does work.

I don't know how far back this problem started but it was broken back in 3.4.4 official as well.  Hopefully there is an easy fix.

### Steps to reproduce

Run the included project.  No splash screen image on Android.

### Minimal reproduction project

[SpashAndroid.zip](https://github.com/godotengine/godot/files/9077671/SpashAndroid.zip)

### LINKED ISSUE #69317: Boot Splash scaling is so small on Android
### Godot version

3.5.1 stable

### System information

Android 11 (GLES2)

### Issue description

image

It's scaling so small on phone but it's scalling normally on PCs

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

### LINKED ISSUE #74348: Splash screen transitions to black screen on Android
### Godot version

4.0

### System information

Pixel 5, Adreno 620, Forward Mobile

### Issue description

In exported Android projects, the configured splash screen is only visible for a very brief moment. Immediately afterwards, there is a transition to a black screen which, depending on how many resources are loaded in a project, remains until the first frame is rendered.

In larger projects where more resources are loaded, the black screen is visible for around 3 seconds depending on the device.

The same black screen is also visible when you check "Use Gradle Build".

Release vs. Debug build also makes no difference.

https://user-images.githubusercontent.com/120789048/222893477-b2ec2e8e-05f0-4ed4-948e-33a139b8a71b.mp4

### Steps to reproduce

1. Create new empty project
2. Create an empty main scene with a Control node
3. Check "Import ETC2 ASTC" in Project Settings
4. Configure Export for Android
5. Export to device

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by m4gr3d**
Due to [limitations introduced in Android 12](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate), the Godot splash screen logic has been updated to the same logic as used on other platforms; the splash screen is rendered by the Godot engine instead of the Android runtime.

This PR has been split in two commits for code clarify:
- dd966f5680eac1b068d9492d6dbba572cff54936 updates the splash screen for the Android Editor
- f20e21a6d6b91fee2106be2fea5f794cfed7578f updates the splash screen for the Godot Android app template

Fixes https://github.com/godotengine/godot/issues/69317
Fixes https://github.com/godotengine/godot/issues/62863
Fixes https://github.com/godotengine/godot/issues/74348

### CODE REVIEW

**Comment by Alex2782** [comment]
and https://github.com/godotengine/godot/issues/74348 ?

**Comment by m4gr3d** [comment]
> and #74348 ?

@Alex2782 It should fix that issue as well when using the `mobile` renderer. For the `compatibility` renderer, https://github.com/godotengine/godot/issues/92966 will need to be fixed as well.

**Comment by owlnewworlds** [comment]
Please, make it available in 4.3 final build, a lot of Godot devs desperately need functional splashscreens on mobile! ^^
Thank you for your hard work everyone <3

**Comment by akien-mga** [comment]
Tested on a Pixel 7a, it seems to work ok, but I feel users might not be fully satisfied with the first splash screen shown (managed by the OS I guess?). It just shows the game icon, before moving on to the Godot-managed splash screen.

Here's a test from this PR using https://github.com/KenneyNL/Starter-Kit-3D-Platformer/

https://github.com/godotengine/godot/assets/4701338/db31efb2-1b49-4232-9680-8ef202a59ab4

The screen recording app was a bit confused by the orientation change, so it actually looks better on device, where it transitions smoothly from this:

image

To this:

image

(Don't mind the size differences, I just cropped the wrongly oriented images from the video - on device both of them are properly fullscreen landscape from the start.)

**Comment by akien-mga** [comment]
Tested 4.3-beta1 to compare and I can confirm this is a net improvement, in 4.3-beta1 it would show the same first splash screen with just the app icon, and then a black screen.

**Comment by m4gr3d** [comment]
> Tested on a Pixel 7a, it seems to work ok, but I feel users might not be fully satisfied with the first splash screen shown (managed by the OS I guess?). It just shows the game icon, before moving on to the Godot-managed splash screen.

The first splash screen is indeed provided by the OS; Google has been adding more limitations to it starting with Android 12, so there's not much we can do to customize that unfortunately. Other frameworks have been complaining as well about the imposed limitations :(

**Comment by owlnewworlds** [comment]
As a Godot developer who's developing a mobile game and who's waiting impatiently this fix, I can say that this is a great improvement. Every other game (Godot or not) seems to have inevitably a pre-screen with the app icon (it can be on a white background or black or whatever color - I'm wondering the source of this color...) displayed and then the splashscreen. So if we have the splashscreen displayed instead of the black screen, it sounds perfect to me.

**Comment by akien-mga** [comment]
> Tested 4.3-beta1 to compare and I can confirm this is a net improvement, in 4.3-beta1 it would show the same first splash screen with just the app icon, and then a black screen.

Actually the first splash screen shown by 4.3-beta1 has a different background color. Might be the game's default clear color? Or maybe it's just a coincidence.

Is it intentional that after this PR the background color changed to a dark one? (I do have dark theme on, so that might be why.)

https://github.com/godotengine/godot/assets/4701338/a8df814e-38a1-4871-9b90-8a5ff38d87bc

---

> The first splash screen is indeed provided by the OS; Google has been adding more limitations to it starting with Android 12, so there's not much we can do to customize that unfortunately. Other frameworks have been complaining as well about the imposed limitations :(

I tested a few other non-Godot apps and indeed most seem to have this first splash screen which is just the app icon on a dark background (Marvel Snap, Discord, Babbel), but others still have a custom full screen splash (WhatsApp, Signal, Twitch, Rocket.chat). Might be worth looking into, but for now this seems pretty good.

**Comment by m4gr3d** [comment]
> (it can be on a white background or black or whatever color - I'm wondering the source of this color...) 

@owlnewworlds For Godot, you should be able to customize the source of the background color (after this PR lands) via the `launcher_icons/adaptive_background_432x432` export option.

**Review by akien-mga — APPROVED** [review]
Tested, works as intended (for Godot apps, didn't test the editor).

**Comment by akien-mga** [comment]
Thanks!

We should probably backport this to `3.x` too.

**Comment by piramidamsc** [comment]
Could you tell me how to disable your cool interesting feature?

**Comment by wombatwingdings** [comment]
Yes, please do port this to 3.x. People are getting their apps rejected because of this. I assume this isn't in 3.6 RC1?

**Comment by owlnewworlds** [comment]
> > (it can be on a white background or black or whatever color - I'm wondering the source of this color...)
> 
> @owlnewworlds For Godot, you should be able to customize the source of the background color (after this PR lands) via the `launcher_icons/adaptive_background_432x432` export option.

Just getting back to you to confirm (maybe it wasnt necessary lol) that using the export setting you told me works like a charm to change the background color behind the app icon before the splashscreen is displayed.

**Comment by alexzheng** [comment]
3.6 still has this issue.

**Pull request merged**
