### PR TITLE
use .get_file() instead of basename from libc

### LINKED ISSUE #48938: can't find basename() on OpenBSD
**Godot version:** built from master e773bf56edef87de70c48515cdbe01340ef80b13

**OS/device including version:** OpenBSD-CURRENT

**Issue description:**

The compilation fails because it doesn't find `basename`:

```
platform/linuxbsd/os_linuxbsd.cpp:402:21: error: use of undeclared identifier 'basename'
        String file_name = basename(p_path.utf8().get_data());
```

`#include <libgen.h>` (to bring in [basename(3)](http://man.openbsd.org/basename.3)) doesn't seem to fix it, since then it complains about `char*` vs string.  I ended up with the following, which at least compiles and seems to work, but I don't know how much sense it makes.

```diff
--- os_linuxbsd.cpp.orig        Fri May 21 15:24:54 2021
+++ os_linuxbsd.cpp     Fri May 21 20:58:52 2021
@@ -397,7 +399,7 @@
        // The trash can is successfully created, now we check that we don't exceed our file name length limit.
        // If the file name is too long trim it so we can add the identifying number and ".trashinfo".
        // Assumes that the file name length limit is 255 characters.
-       String file_name = basename(p_path.utf8().get_data());
+       String file_name = p_path.get_basename();
        if (file_name.length() > 240) {
                file_name = file_name.substr(0, file_name.length() - 15);
        }
```

**Steps to reproduce:**

godot doesn't compile as-is from the master branch, it needs [some patches](https://github.com/omar-polo/mystuff/tree/master/games/godot/patches) (in particular for some third parties stuff), but none of those should cause this issue.

### PR DESCRIPTION
**Pull request by omar-polo**
This fixes #48938

### CODE REVIEW

**Review by theraot — COMMENTED** [review]
For what I've found `basename` and `get_basename` are not equivalent:

- `basename` returns the last component of the path, which could be a file name or a folder name. See http://man.openbsd.org/basename.3
- `get_basename` returns the path without the extension. See https://docs.godotengine.org/en/latest/classes/class_string.html#class-string-method-get-basename

Given the name `file_name`, the fact that it will be used like this:

```
	String dest_path = trash_path + "/files/" + file_name;
```

*And as far as I can tell, `move_to_trash` does not work for folders.*

I think you should use `get_file` instead of `get_basename`. See https://docs.godotengine.org/en/latest/classes/class_string.html#class-string-method-get-file

---

The behavior of `get_file` differs from the description of `basename` in that it will return empty string if the input is empty string or consist only of `/`. I quote from http://man.openbsd.org/basename.3:

```
If path consists entirely of ‘/’ characters, a pointer to the string "/" is returned. If path is a null pointer or the empty string, a pointer to the string "." is returned.
```

---

The description of `basename` at https://www.man7.org/linux/man-pages/man3/basename.3.html (which that is not BSD) matches the description at http://man.openbsd.org/basename.3 and also provides some test cases:

```
              path       dirname   basename
              /usr/lib   /usr      lib
              /usr/      /         usr
              usr        .         usr
              /          /         /
              .          .         .
              ..         .         ..
```

Adding `get_basename` and `get_file` there for comparison, looks like this:

```
              path       dirname   basename   get_basename     get_file
              /usr/lib   /usr      lib        /usr/lib         lib
              /usr/      /         usr        /usr/            <empty string>
              usr        .         usr        usr              usr
              /          /         /          /                <empty string>
              .          .         .          <empty string>   .
              ..         .         ..         .                ..
```

Where `<empty string>` denotes the empty string.

You can see that if we assume we have a file path, then `get_file` is what we want.

**Comment by omar-polo** [comment]
I forgot to update the commit message, here's another try

**Review by theraot — CHANGES_REQUESTED** [review]
This is what I suggest:
```
	String file_name = p_path.get_file();
	if (file_name.length() == 0) {
		file_name = p_path.get_base_dir().get_file();
	}
```

That way, if `p_path` points to a file, `p_path.get_file()` gives us the name of the file. Otherwise, we get empty string and enter the conditional, where `p_path.get_base_dir().get_file()` gives us the name of the folder.

**Review by theraot — APPROVED** [review]

**Comment by theraot** [comment]
I, of course, approve this. Because of course.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
