### PR TITLE
Fix inspector plugin

### LINKED ISSUE #24472: Crash on close due to plugin using EditorInspectorPlugin
**Godot version:**
Last nightly built calinou.c6edc43
So it's the master!!

**OS/device including version:**
MacOS Mojave

captura de ecra 2018-12-19 as 12 14 35

**Issue description:**
Upon closing the Godot Editor I get the following message:

captura de ecra 2018-12-19 as 11 47 11

"Godot closed unexpectedly" (it is in Portuguese sorry)
The problem seems to be in the remove_inspector_plugin, if I remove that line of code the editor doesn't crash.

**Steps to reproduce:**
1) have a plugin that handles the inspector (EditorInspectorPlugin) active!
2) the plugin must have a remove_inspector_plugin([your_plugin_here]);
3) close godot!

**Minimal demonstration project**
Just open the project open the Node.tscn and click on the Node then you can close Godot,
and then there's the error.

[InspectorPlugin.zip](https://github.com/godotengine/godot/files/2897524/InspectorPlugin.zip)

### PR DESCRIPTION
**Pull request by willnationsdev**
Closes #24472.

### CODE REVIEW

**Comment by willnationsdev** [comment]
I just noticed that the commits are all messed up for some reason. I'll fix it when I get to a computer again later today.

**Comment by akien-mga** [comment]
Rebased it for you.

**Review by akien-mga — APPROVED** [review]

**Comment by willnationsdev** [comment]
Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
