### PR TITLE
Tweak the default project icon

### LINKED ISSUE #1436: Increase the resolution of the default `icon.png`
**Describe the project you are working on:** I've noticed the lack of resolution in a variety of projects.

**Describe the problem or limitation you are having in your project:**

Many people use `icon.png` as a placeholder, or even a part of their game. It's even [become a meme](https://www.youtube.com/watch?v=VJMb88-d-js).

However, `icon.png` has a fairly low resolution by default, it's only 64x64 pixels:

icon

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

I propose increasing it to 128x128 pixels. Here's a 128x128 version compressed with `oxipng`:

icon

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Godot will place [this](https://user-images.githubusercontent.com/1646875/91680049-0b53b880-eb18-11ea-84f0-656e743e3a1c.png) into the project instead of the existing `icon.png`.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This problem is very easy to work around, but this will be used very often (by anyone who creates a project, nearly 100% of users).

**Is there a reason why this should be core and not an add-on in the asset library?:**

`icon.png` is a core feature.

### PR DESCRIPTION
**Pull request by Calinou**
This only affects newly created projects.

- Use a 128×128 resolution to make the icon look crisp on hiDPI displays.
  - If you need to go back to 64×64, you can set the **Max Size** property to 64 in the Import dock and click **Reimport**.
- Darken the icon's outside area and remove the border, as the contrast rate between the icon and its background is now sufficient.

This different design also allows distinguishing projects that were made with Godot 3.x from projects made with Godot 4.0.

Using the SVG directly in the project is an interesting idea, but I'd prefer to explore it in a future PR as it could potentially break some specific uses of the icon.

This closes https://github.com/godotengine/godot-proposals/issues/1436.

**Testing project:** [test_default_project_icon_2_2.zip](https://github.com/godotengine/godot/files/8074105/test_default_project_icon_2_2.zip)

### 2D scene prototype

[Version with the grayscale icon redesign](https://user-images.githubusercontent.com/180032/153771183-6f6b1eb7-f39e-417a-922e-d05250227d51.png)

### 3D scene prototype

[Version with the grayscale icon redesign](https://user-images.githubusercontent.com/180032/153771187-5b094e35-8d31-47ae-9b7a-f8f3935f9354.png)

### CODE REVIEW

**Comment by Mickeon** [comment]
One minor side effect of this, I persoballu feel, is that it makes new projects look "outdated" on a first glace. Perhaps marking pre-4.0 projects in some way would prevent this oddity.

**Comment by SilencedPerson** [comment]
I agree with Mickeon. Is there any reason why the default Icon couldn't be modulated in the project display if it is not overridden?

**Comment by Calinou** [comment]
> I agree with Mickeon. Is there any reason why the default Icon couldn't be modulated in the project manager if it is not overridden?

Godot copies the default project icon to every new project you create, so the icon is actually always overridden unless you delete `icon.png` from the project.

Distinguishing projects from an old Godot version is already being done, but improving this display is something that should be tackled separately from this PR.

**Comment by agameraaron** [comment]
Solving a problem that doesn't exist. If someone wants the blue to be red or green, they can just as easily use a bucket tool in any graphic application and it will look way better too.

**Comment by Mickeon** [comment]
I wonder if it could be a good idea to keep the icon coloured but the surrounding square is monochrome.

**Comment by SilencedPerson** [comment]
> Solving a problem that doesn't exist. If someone wants the blue to be red or green, they can just as easily use a bucket tool in any graphic application and it will look way better too.

It is a problem worth solving. There is thousands of test projects that use the default Godot Icon as placeholder, in fact, there is so many of them that it is well known meme. The icon sees lot of use it because exactly because people don't need to do precisely what you described.

**Comment by Mickeon** [comment]
Forgive the poor mock-ups, I just thought that returning some of that recognisable blue tint to the logo would be nice, but I understand the argument about modulation, and how these would kind of break [how the logo should be presented](https://godotengine.org/press).

image
image
image

**Comment by pycbouh** [comment]
Maybe instead of trying to make the default project icon good for prototyping, we could introduce a special type of texture that would use a built-in "blocking" texture with a few settings, like modulation, stretch/repeat, etc. Grayscale icon doesn't work well for its main purpose, the project icon. It looks disabled in the list.

A "blocking"/prototyping texture of unit size wouldn't be more than a couple of kilobytes and additional code would not be that much of a burden either. We could even just embed Kenney's prototype pack: https://www.kenney.nl/assets/prototype-textures In vector those amount to about 55 Kb.

**Comment by Zireael07** [comment]
Actually, embedding prototype textures such as Kenney's is a very good idea.

**Comment by kopkako** [comment]
I would advise against this, as well-intended as it is: Grayscale makes the project look 'inactive' or 'outdated', it would be confusing.

**Comment by Calinou** [comment]
I amended this pull request to use the colored design I made instead.

**Review by fire-forge — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]
Approved in editor PR meeting

**Comment by YuriSizov** [comment]
Thanks!

**Comment by golddotasksquestions** [comment]
This totally fucks over all default values we had thus far. Makes it necessary for all those defaults to be reevaluated. TileMap cell size, physics gravity, shape extends ....

64x64 also was at least _kind of_ useable in a pixelart context without having to reimport it.

**Comment by YuriSizov** [comment]
> I'd so much rather Godot would just ship with the svg icon file

That's the plan, but we decided it can be done in a follow-up.

**Comment by Calinou** [comment]
You can set **Max Size** to 64 in the Import dock as mentioned. This works on all textures imported by Godot.

**Pull request merged**
