### PR TITLE
Fix C# Hint NodeType and ResourceType HintString

### LINKED ISSUE #91644: C# Export Hint NodeType and ResourceType HintString Cannot be displayed correctly
### Tested versions

v4.2.2.stable.mono.official

### System information

Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.5123) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

```csharp
public partial class CustomNode : Node
{
   // Only Node HintString
   [Export(PropertyHint.NodeType,     $"{nameof(Node2D)},{nameof(Node3D)}")] 
   public Node        TNode;
   // Only Resource HintString
   [Export(PropertyHint.ResourceType, nameof(Texture2D))]                    
   public Resource    TResource;
   // Work
   [Export(PropertyHint.NodeType,     $"{nameof(Node2D)},{nameof(Node3D)}")]
   public GodotObject GONode;
   // Work
   [Export(PropertyHint.ResourceType, nameof(Texture2D))]                   
   public GodotObject GOResource;
}

```

### Steps to reproduce

HintAndHintString

### Minimal reproduction project (MRP)

[HintAndHintString.zip](https://github.com/godotengine/godot/files/15229389/HintAndHintString.zip)

### PR DESCRIPTION
**Pull request by ZerxZ**
Fix #91644

### CODE REVIEW

**Comment by raulsntos** [comment]
Thanks for contributing to the .NET module! This looks really nice although I feel like it goes against the current behavior.

The way `[Export]` currently works we don't usually override the hint and hint string computed from the property type, the type takes precedence over the attribute. This means if you have an exported property with an enum type, you can't change how the enum members will be displayed even if you specify it in the attribute.

I'm a bit worried that this change will make things a bit confusing to users, because now some times the type will take precedence and others it will be the attribute.

My personal preference would be for the attribute to always override the type, since I believe when the user is being explicit we should respect that. However, this is a behavior change that may be a bit too disruptive for existing users.

And now that I laid out my concerns and personal preferences, I'd love to hear what other .NET contributors think.

**Comment by paulloz** [comment]
> My personal preference would be for the attribute to always override the type, since I believe when the user is being explicit we should respect that.

Same thing, I feel like always respecting the explicit metadata given by the user (if valid) is what we want / what anyone would expect.

> However, this is a behavior change that may be a bit too disruptive for existing users.

Is it disruptive? I'd imagine existing users either
- Don't have hint string specified: no disruption for them.
- Have some hint string specified, but it does nothing[^1]: the behaviour will change, but how likely is it that users leave not working hints in their code?
- Have some hint string specified, and it works[^2]: the behaviour should not change here, no disruption for them.

Or is there something I'm missing/misunderstanding?

[^1]: `[Export(PropertyHint.ResourceType, nameof(Texture2D))] public Resource Resource`
[^2]: `[Export(PropertyHint.ResourceType, nameof(Texture2D))] public GodotObject Resource`

**Review by raulsntos — APPROVED** [review]
> Or is there something I'm missing/misunderstanding?

@paulloz No, I think you got it perfectly. Whenever something changes behavior I get a little nervous, but I think you are completely correct that it won't be disruptive, thank you.

> Should `[Export]` be used consistently with `@export_custom`?

@ZerxZ Yeah, I think the GDScript annotation fulfills the same use cases. Thank you for showing how `@export_custom` works, this was helpful. I think it makes sense to follow the same behavior, and it probably matches user expectations when using the attribute.

---

So it sounds like there's consensus on allowing explicit hints override computed hints, since explicitness indicates intention. We should probably make sure other hints also work like this, but that would be work for a follow-up PR.

This PR goes in that direction and works as expected, so I'm approving.

**Comment by ZerxZ** [comment]
> > Or is there something I'm missing/misunderstanding?
> 
> @paulloz No, I think you got it perfectly. Whenever something changes behavior I get a little nervous, but I think you are completely correct that it won't be disruptive, thank you.
> 
> > Should `[Export]` be used consistently with `@export_custom`?
> 
> @ZerxZ Yeah, I think the GDScript annotation fulfills the same use cases. Thank you for showing how `@export_custom` works, this was helpful. I think it makes sense to follow the same behavior, and it probably matches user expectations when using the attribute.
> 
> ---
> 
> So it sounds like there's consensus on allowing explicit hints override computed hints, since explicitness indicates intention. We should probably make sure other hints also work like this, but that would be work for a follow-up PR.
> 
> This PR goes in that direction and works as expected, so I'm approving.

Thanks! 🎉

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by ZerxZ** [comment]
> Thanks! And congrats for your first merged Godot contribution :tada:

Thanks! 🎉

**Pull request merged**
