### PR TITLE
feat(editor/2d): Add zoom speed setting

### LINKED ISSUE #863: Make the zoom speed configurable in the 2D scene editor
**Describe the project you are working on:**
A regular project involving the creation and editing of 2D tilemaps.

**Describe the problem or limitation you are having in your project:**
When I work on a tilemap (or on any Scene, for that matter), I zoom in and out frequently so that I can quickly evaluate the looks both on a smaller and a larger scale. For that to happen routinely, I use the mousewheel to zoom in and out frequently.

It takes a lot of time, however, feeling slow. While a relatively small feature, my impression is that it has a huge impact in case zooming is prevalent. The Scene Editor has an option to reset Zoom to 100%, but it helps only in case of zooming in, not out.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
A numeric configuration parameter added to Editor Settings called `Zoom speed`, similar to the currently existing `Pan speed`.

The value of this option would be bound to the zooming functions applied in the Scene Editor.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I imagine the perfect location of the new option to be `Editor Settings > Editor > 2D`. Here, a new config added with an integer value.

After some quick research, I found that `editor/plugins/canvas_item_editor_plugin.cpp::CanvasItemEditor::_gui_input_zoom_or_pan` is the function where the main logic is to be changed. Of course, it would mean that zooming with the mousewheel and using the GUI icons by clicking would be equally faster or slower, depending on the configuration.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
As with many configuration settings, chances are many people won't change them in the long run. However, since it depends on the interaction between an input and the response of the interface based on it, I'm not convinced a script solution is feasible.

**Is there a reason why this should be core and not an add-on in the asset library?:**
This is an option in the Editor Settings. Affects every 2D editor ever used in a project.

### PR DESCRIPTION
**Pull request by erictuvesson**
Fixes https://github.com/godotengine/godot-proposals/issues/863

---

Is there somewhere where the settings are documented?
Would be nice to have documentation or tooltips on the different kind of settings.

### CODE REVIEW

**Comment by Calinou** [comment]
> Is there somewhere where the settings are documented?
Would be nice to have documentation or tooltips on the different kind of settings.

Not yet, see https://github.com/godotengine/godot-proposals/issues/1339.

**Comment by erictuvesson** [comment]
I am not sure happy with the results of this, what I would like to see with this update is also:
* Have a min and max setting for the zoom speed
* Setting to enable camera smooth zooming 

All of this is just to improve the UX

**Comment by Calinou** [comment]
@erictuvesson I'd work on one small feature at a time, so we can merge it more easily.

**Comment by ExoidAgent** [comment]
I'm a bit late about commenting, but I've been away for a very long time, and just realized my proposal got a Pull Request.

I see, however, that it stalled a week after the initial commit. What's the current status? If I understood well, so far the only thing happened is to outsource the "zooming scale" to a settings variable - but it's not yet set to any GUI in settings?

Smooth scrolling is I assume a generalization of [godotengine/godot#37073](https://github.com/godotengine/godot/pull/37073) to any zooming scale value, and this is what would give its aforementioned difficulty, right?

The reason I ask is that I may contribute some code to this PR later on, but even if not, some clarification might help for other contributors.

**Comment by erictuvesson** [comment]
> I'm a bit late about commenting, but I've been away for a very long time, and just realized my proposal got a Pull Request.
> 
> I see, however, that it stalled a week after the initial commit. What's the current status? If I understood well, so far the only thing happened is to outsource the "zooming scale" to a settings variable - but it's not yet set to any GUI in settings?

It's a while since I looked at it, it is in the settings where it can be changed.

> Smooth scrolling is I assume a generalization of [godotengine/godot#37073](https://github.com/godotengine/godot/pull/37073) to any zooming scale value, and this is what would give its aforementioned difficulty, right?

I didn't look into that, I do believe it required changes in a lot of places. It would probably be better to be in it's own PR.

> The reason I ask is that I may contribute some code to this PR later on, but even if not, some clarification might help for other contributors.

I think this PR is done, the goal was to add a zoom speed setting in the editor. I was just not happy with how the UX is, which is kinda unrelated to this.

**Comment by MewPurPur** [comment]
Is this PR still alive? If not I might salvage it.

**Comment by erictuvesson** [comment]
It should probaby be recreated since there have been so many changes. Probably a good idea to see if they are willing to merge it this time too.

**Comment by Calinou** [comment]
When redoing this PR, I suggest making the setting a floating-point value with `1.0` as the default value (and `0.01` as step precision).

**Comment by Calinou** [comment]
- Superseded by https://github.com/godotengine/godot/pull/95906. Thanks for the contribution nonetheless!

**Pull request closed without merging**
