### PR TITLE
Fix for not being able to ignore shadowing warnings on class scope

### LINKED ISSUE #75208: Using @warning_ignore to ignore "shadowed_global_identifier" still issues warning(s)
### Godot version

Godot 4.0.1.stable

### System information

Windows 10, Forward+

### Issue description

Example code:

```gdscript
@warning_ignore("shadowed_global_identifier")
static func print_debug(msg: String):
```

the warning is ignored by pressing [ignore] in the warnings panel.

pressing it multiple times results in:
```gdscript
@warning_ignore("shadowed_global_identifier", "shadowed_global_identifier")
```

### Steps to reproduce

Shadowing a global function with a method of script:

```gdscript
@warning_ignore("shadowed_global_identifier")
static func print_debug(msg: String):
```

### Minimal reproduction project

```gdscript
@warning_ignore("shadowed_global_identifier")
static func print_debug(msg: String):
    pass
```

### PR DESCRIPTION
**Pull request by jpcerrone**
Fixes #75208 

Unifies the code for checking both the class scope and local scope shadowing of variables inside the 'is_shadowing' function from the gdscript analyzer. The class scope shadowing was being incorrectly checked during the parsing stage, and thus the annotations to ignore warnings were not being taken into account.

Adds two new scenarios to the shadowing unit test that check for a class level shadow warning. Validating that it correctly appears when there's no annotation present and that it doesn't when there's an annotation that ignores it.

Modifies another test that would start breaking with this change as it contained a variable that was shadowing a global one but wasn't being detected as such.

This is my first PR :) please let me know if I'm missing something!

### CODE REVIEW

**Comment by jpcerrone** [comment]
fixed formatting by running clang-format locally on every file and force pushed the changes into the same commit

**Comment by adamscott** [comment]
Hi @jpcerrone! Sorry for the delay.
Thanks for your "first PR"! I saw that you finally contributed to the Godot game engine, so congratulations.

I set the milestone to 4.2, as we're close of launching 4.1. But I added your PR to the list of PRs that the team will have to review soon.

Thanks again for your contribution. You'll get news soon!

**Comment by jpcerrone** [comment]
> Hi @jpcerrone! Sorry for the delay. Thanks for your "first PR"! I saw that you finally contributed to the Godot game engine, so congratulations.
> 
> I set the milestone to 4.2, as we're close of launching 4.1. But I added your PR to the list of PRs that the team will have to review soon.
> 
> Thanks again for your contribution. You'll get news soon!

Thank you!!

**Review by dalexeev — APPROVED** [review]
Looks good to me! I have tested these changes, works fine. While I've noticed that shadowing warnings are not generated in some cases, that doesn't seem to be relevant to this PR. Note that the PR still needs to be reviewed at the GDScript team meeting. Also, this PR should be rebased so that CI will run tests for all platforms.

**Comment by jpcerrone** [comment]
> Looks good to me! I have tested these changes, works fine. While I've noticed that shadowing warnings are not generated in some cases, that doesn't seem to be relevant to this PR. Note that the PR still needs to be reviewed at the GDScript team meeting. Also, this PR should be rebased so that CI will run tests for all platforms.

Got it, branch rebased

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
