### PR TITLE
[3.x] Make the project data directory customizable

### PR DESCRIPTION
**Pull request by m4gr3d**
This PR makes the default project data directory (`.import`) customizable. 

This is useful on platforms where certain directory patterns are disallowed (e.g: some Android build tools disallow hidden directories in the generated APK).

*Bugsquad edit:* `3.x` version of #52548.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Approved, subject to changes from my review of the `master` PR: https://github.com/godotengine/godot/pull/52548#pullrequestreview-776428441

**Comment by akien-mga** [comment]
Thanks!

**Comment by Listwon** [comment]
@akien-mga sorry for catching right after you merged it, but isn't replacing `==` with `begins_with()` too broad in `EditorFileSystem::_should_skip_directory`, `EditorFileDialog::_item_list_item_rmb_selected` or `FindInFiles::_scan_dir`? If we set our custom path to let's say `imported` without the comma, it will skip (or include) all of the folders starting with `imported`, while previously it ignored those equal to `imported`.

**Comment by Listwon** [comment]
It's not even an optimization in this case but can cause trouble, so I don't know if it's worth to replace `==` in tose places. I'd say we are introducing a bug and gain nothing for that price.

It's not only the case of thirdparty tooling, we can name directories manually and cause problems ourselves unaware of leaky solution above.

**Comment by m4gr3d** [comment]
@akien-mga @Listwon See https://github.com/godotengine/godot/pull/53779 for an implementation of my above suggestions.

**Pull request merged**
