### PR TITLE
Mention the stretching behavior of PopupPanel

### LINKED ISSUE #27555: A button inside PopupPanel always gets stretched to fill the whole panel
**Godot version:** 3.1
**OS/device including version:** Xubuntu 18.10 x86_64
**Issue description:**
A button inside PopupPanel always gets stretched to fill the whole panel. PopupDialog works as expected.

**Steps to reproduce:**
- Create a new project.
- Add a PopupPanel node and a single Button node as its child.
- Manually position and resize the button.
- Call panel's .popup() in root node's _ready() function.
- Play the project.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #27555

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Looks good, thanks! Guess this applies to 3.x too then?

**Comment by KoBeWi** [comment]
Yes, in 3.x the behavior is the same.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
