### PR TITLE
Tweak arguments of list_dir_begin() (skips navigational and hidden files by default)

### LINKED ISSUE #2787: skip_navigational argument of list_dir_begin() should be true by default
### Describe the project you are working on
GDScript stuff.

### Describe the problem or limitation you are having in your project
Every single time I use `list_dir_begin()`, I pass `true` to `skip_navigational`. This method is used to traverse directory files, `.` and `..` are not valid files. Listing them is useless unless you are implementing custom file explorer (aka never, because we have built-in FileDialog).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
`skip_navigational` should be true by default, so I can do `list_dir_begin()` instead of `list_dir_begin(true)` every time.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
See above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Technically passing `true` is a workaround, but this is the problem itself.

### Is there a reason why this should be core and not an add-on in the asset library?
It's core method.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/2787

### CODE REVIEW

**Comment by pycbouh** [comment]
Do users often look for hidden files as well? I feel like I always just pass `true`/`true`. Well, maybe in most cases it doesn't really matter if a file is hidden or not, but still... Is it a sensible default to keep here?

**Comment by KoBeWi** [comment]
Personally I never passed the second argument. The method is usually used to list files in your project's directory, so it doesn't matter if files are hidden or not, because you have control over them.

**Comment by akien-mga** [comment]
I think hidden files could be ignored by default too, yes. But then the two `skip_` arguments should likely be flipped and named `show_` instead. It's more natural to opt-in for showing additional stuff than opt-out of hiding stuff.

**Comment by KoBeWi** [comment]
Ok, changed to `show_`

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
