### PR TITLE
Moved subscene creation from scene menu to an icon on the scene dock

### PR DESCRIPTION
**Pull request by akien-mga**
Based on @Fiona's PR #2220.
The previous "subscene" concept is also renamed to "new scene", as those subscene are just like regular scenes.

I think it's a nice enhancement; there is one issue though: the default width of the scene tree dock is now too small for all the icons to fit, so the padding between icons or the default width of docks should be changed a bit.

### CODE REVIEW

**Comment by akien-mga** [comment]
And this fixes #2214.

**Comment by reduz** [comment]
have a screen of how it looks?

**Comment by akien-mga** [comment]
Here's how it looks like without the PR:
toscene1 toscene1_2

And with the PR:
toscene2 toscene2_2

As you can see the scene tree panel goes a bit out of its dock on the right, because the new icon makes it too wide compared to the default minimal dock width. So either the minimal width would have to be increased by something like 10-20  px,

**Comment by Fiona** [comment]
Oh cool! I had completely forgotten I did this. Thank you very much for updating it @akien-mga :)

It's still a change that needs to be made IMO (at the very least "subscene" needs renaming). I think that reducing the padding on the icons is probably the best bet. There's a lot of padding there! This problem wasn't there when I did the original PR, I guess the layout of those buttons slightly changed in the interim.

**Comment by akien-mga** [comment]
> I just noticed that you commented on the original PR last month requesting a rebase, I'm very sorry, I did not check my Github notifications before now. My mistake.

No problem :) If you know how to reduce the icon padding I'd be glad to add this to this PR :)

**Comment by akien-mga** [comment]
From @TheHX on IRC:
> if you add hbc_bottom->add_constant_override("separation",0), maybe all buttons will fit on the dock

Will try this asap.

**Comment by akien-mga** [comment]
I've removed the padding on the lower HBoxContainer as suggested by @TheHX, it now looks like that:
scenetree

**Comment by akien-mga** [comment]
WDYT about the change @reduz, @godotengine/user-interface?
Compare the first screenshot in https://github.com/godotengine/godot/pull/2928#issuecomment-163138781 with the one directly above.

**Comment by MarianoGnu** [comment]
I like the way it looks and works, but icon is not really meagningfull imo, i'd use the packed scene icon instead of a blank sheet, here's a little mockup

0ef6ec4e974befc5ccd73c29b13b0bef

**Comment by akien-mga** [comment]
Your mockup looks good! Could you send me the icon in png maybe, then I can replace the current one in the PR with yours?

**Comment by MarianoGnu** [comment]
i'm not a designer :/ i did my best but maybe someone can do it better
icon_create_new_scene_from

OFFTOPIC reparent icon looks wrong too, the picture is meaningless...

**Comment by akien-mga** [comment]
>  reparent icon looks wrong too, the picture is meaningless...

It looks fine to me, it shows that you move a node from one level to the the parent level, i.e. you reparent it.

**Comment by akien-mga** [comment]
I replaced the icon with @MarianoGnu's.

**Comment by MarianoGnu** [comment]
reparent icon reminds me to size icon, looks odd to me, but whatever, i'm nor designer :tongue:

**Comment by akien-mga** [comment]
I'll merge as IMO it's an improvement already, but as @reduz already pointed out in some other issues there will be further work done on the menus for 2.1, so we'll maybe change it again :)

**Pull request merged**
