### PR TITLE
Visual Studio Natvis file works for Variant again

### PR DESCRIPTION
**Pull request by derammo**
tiny changes to make the Variant parser in the Visual Studio debugger work again (a union field in Variant was renamed)

### CODE REVIEW

**Comment by derammo** [comment]
https://github.com/godotengine/godot/blob/d6b1dd4854be3b31673e7634d3b88499f3bd2b60/core/variant/variant.h#L212

**Comment by akien-mga** [comment]
Sorry for the delay reviewing. That seems obviously correct, though there's a merge conflict to handle now.

**Review by akien-mga — APPROVED** [review]

**Comment by derammo** [comment]
> Sorry for the delay reviewing. That seems obviously correct, though there's a merge conflict to handle now.

@akien-mga Is that your way of saying I need to rebase or what is the implied action ? :)

**Comment by derammo** [comment]
Also, if you review the merge I just did you will note that @reduz added `Projection` only to one of the two places where different types are handled.   I have no way of knowing if that was oversight or intention.

**Comment by akien-mga** [comment]
Yes a merge conflict requires a rebase to solve it, we don't want merge commits in the PR itself, only for merging PRs in the target branch.

As for the missing Projection, it should likely be added. reduz doesn't use VS afaik.

**Comment by derammo** [comment]
well considering natvis errors out before this PR, I am pretty sure nobody ran his change

**Comment by derammo** [comment]
@akien-mga all done

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
