### PR TITLE
Relaxes Node naming constraints in glTF documents to match the Editor.

### PR DESCRIPTION
**Pull request by abaire**
Dedicated backport as requested by @akien-mga on #45545

### CODE REVIEW

**Comment by pycbouh** [comment]
I think it would be better if the commit message was the same as in the original, so that the gist of it is clear without jumping through referenced issues and PRs.

**Comment by abaire** [comment]
> I think it would be better if the commit message was the same as in the original, so that the gist of it is clear without jumping through referenced issues and PRs.

Excellent point, fixed.

**Comment by fire** [comment]
I'm not able to test, but I approve if it's the same results on 3.2 as master.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by fire** [comment]
There was discussion that this is a breaking change that causes all the node-path referenced by code to possibly change and break everything in a Godot Engine minor release.

Will try to find the extent of this.

**Pull request merged**
