### PR TITLE
 fix interactive loader cache

### PR DESCRIPTION
**Pull request by TheoXD**
As title suggests, interactive_loader() did not return cached resource and returned null object in gdscript. Can be reproduced by loading same scene twice, and this patch seems to work just fine.

### CODE REVIEW

**Comment by punto-** [comment]
Didn't this api used to return a Resource type when it was already loaded?
Or was it always a ResourceLoaderInteractive?

**Comment by TheoXD** [comment]
@punto- , According to the source code, it is supposed to return a resource but all I get is [Object:null], with type 18, practically unusable. What I did was what load_interactive(const String &p_path, Error *r_error) does, creates a ResourceInteractiveLoaderDefault and assings an already preloaded resource.
This way it works perfectly, and I see scene progress bar loading super fast, which means it's not loading the scene twice.

**Comment by punto-** [comment]
Ok that makes sense since the function returns
a Ref<ResourceInteractiveLoader> instead of a resource.

**Comment by akien-mga** [comment]
Could you make a PR with just d8a9055? The merge commits are not useful and the first commit is unrelated and needs discussion in its own PR, if meant to be upstreamed.

**Comment by TheoXD** [comment]
Was easier to make a new fork, so here's the new PR  #4895

**Comment by akien-mga** [comment]
Superseded by #4895.

**Pull request closed without merging**
