### PR TITLE
Disable the blend file import setting support by default

### LINKED ISSUE #7827: Disable the blend file import setting support by default, to prevent the startup warning
### Describe the project you are working on

Any project

### Describe the problem or limitation you are having in your project

It's about a creating of empty project which immediately emit this warning to a console:

изображение

I know it's easily to fix up, but IMO is not good experience for the new users which does not want to deal with it and see this warning.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Disable the feature or prevent this warning from emitting in new projects. Blend file support is not something every user wants in their project anyway.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

N/A

### If this enhancement will not be used often, can it be worked around with a few lines of script?

N/A

### Is there a reason why this should be core and not an add-on in the asset library?

N/A

### PR DESCRIPTION
**Pull request by ywmaa**
Resolves https://github.com/godotengine/godot-proposals/issues/7827

_Edit by the production team: [Added the right keyword for GitHub to link it with the issue.](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)_

### CODE REVIEW

**Review by Chaosus — APPROVED** [review]

**Comment by akien-mga** [comment]
I'm not sure this is the right solution.

The problem is the bad UX of having the import setting enabled by default, but Blender isn't automatically detected.
Disabling the import setting just means that users won't even know that Godot can import Blend files.

What this requires is either:
- Figuring out how to auto-detect where Blender is installed, if it's installed - could be used from `PATH`, though that's unlikely to be suitable on Windows or macOS.
- Make it easier for users to configure the Blender path when a .blend file is first added to the project, like we do for FBX2glTF. That's probably the better solution.

**Comment by aaronfranke** [comment]
Would it be possible to simply hide the warning whenever the project does not contain `.blend` files? We could move the warning so that it is only printed when the importer encounters a `.blend` file.

**Comment by lyuma** [comment]
I think FBX shows a dialog if you attempt to import a .fbx file - I think blend could do the same thing as .fbx.

I do agree with waiting to import a file before warning the user that Blender is not set up. Many users especially those trying the engine might not have Blender and might never hit a use for it in their workflow.

We do need to make sure it re-attempts blend import once Blender is configured in the project, even if through an editor restart.

**Comment by ywmaa** [comment]
> I think FBX shows a dialog if you attempt to import a .fbx file - I think blend could do the same thing as .fbx.

AFAIK .blend importer had it too.

**Comment by Calinou** [comment]
@ywmaa Can you check if this is still an issue as of [4.3.rc2](https://godotengine.org/article/release-candidate-godot-4-3-rc-2/)? See https://github.com/godotengine/godot-proposals/issues/7827#issuecomment-2264942592.

**Comment by ywmaa** [comment]
With 4.3 stable the issue is fixed.

**Pull request closed without merging**
