### PR TITLE
Manually optimize a lot of SVGs

### PR DESCRIPTION
**Pull request by MewPurPur**
Saves 30+ kB.

The optimizations are too vast to go over, but basically, the main goals in descending order of how often I did them:
- Remove pointless transforms (it was a way taller order than I anticipated, so the work only starts here.)
- Replace complex paths with simple strokes when possible (i.e. meshes).
- Merge arcs. We use a lot of quarter arcs for example, which is wasteful having 3 in a row when a three-quarter circle is needed.
- Use arcs. Rounded corners should be using arcs, not Bezier curves.
- Simplify shapes. Things that are attached make more sense to be part of the same SVG path, avoiding inner edges.
- Misc.

Most SVGs are unchanged, and some are changed but the changes are minuscule and unnoticeable (i.e. untangling a clusterfuck of 4 control points does technically change the icon, but... come on).

There are *hundreds* of SVGs that for some reason have a translation by something like (-1034, 0), which SVGCleaner doesn't seem to resolve. Might be good to look for the source of this. **It might also be good idea for someone else who does SVG editing to open some of my SVGs, since my methods are unusual and I don't know if they might be problematic in some editors.**

From a cursory look, nothing appears broken in the editor.

### CODE REVIEW

**Comment by antimundo** [comment]
I saw the changes in Inkscape, and I think they look good 👍 
But I'm not an SVG expert, so take my opinion with a grain of salt.

**Comment by MewPurPur** [comment]
Thanks, so I guess nothing to worry about.

**Review by Calinou — APPROVED** [review]
Tested locally (by opening the editor and looking at various icons in the Create New Node dialog), it works.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
