### PR TITLE
Rename `p_extensions` of `get_recognized_extensions` to `r_extensions`

### PR DESCRIPTION
**Pull request by ghost**
We use `r_*` for return values but this method(s) confused me at first (a month ago) so I am getting revenge and rename it

### CODE REVIEW

**Comment by AThousandShips** [comment]
This might not necessarily be a case for `r_`, the specifics are a bit vague but it is generally used for a returned value, not a modified value, i.e. where the pointer is initialized in the target, take for example `Dictionary::get_key_list`, `Object::get_property_list`, etc.

**Comment by dustdfg** [comment]
> This might not necessarily be a case for `r_`, the specifics are a bit vague but it is generally used for a returned value, not a modified value, i.e. where the pointer is initialized in the target, take for example `Dictionary::get_key_list`, `Object::get_property_list`, etc.

Oh, I see... Now I also understand why there is discussion label instead of bug...

But first of all I am sure I've seen some places where `r_` used in the same way as here. And there is `EditorTranslationParserPlugin::get_recognized_extensions(List<String> *r_extensions)` and some other overrides of the same method in different classes which are already defined with `r_`

**Comment by AThousandShips** [comment]
IMO this is a case where the rule isn't clear enough to justify the noise, and even if it was I'm not sure it's worth the change and the noise inherent in it for just the code style (the `r_` naming is somewhat secondary to the fact that the argument is non-`const`)

**Comment by AThousandShips** [comment]
It's not about `List` or not, it's about the specific use, it has been rejected in review in the past for cases where you just pass data that is modified, as opposed to passing a pointer to create data in

**Pull request closed without merging**
