### PR TITLE
Pr-shader-dot-fix

### PR DESCRIPTION
**Pull request by sanikoyes**
Shader:
Add float op for dot
Add missing use_parent_shader initialize value

### CODE REVIEW

**Comment by reduz** [comment]
what does dot() on float do?

**Comment by sanikoyes** [comment]
Original GLSL language is supported this...

**Comment by romulox-x** [comment]
I know I'm a bit late on this one, but if dot product is:
x[0]⋅y[0]+x[1]⋅y[1]+...
I guess it just multiplies the values?  I guess it's mathematically sound, even if it's basically just a strange way of expressing multiplication.  If GLSL allows it, seems to me like it makes sense to allow it.

**Comment by akien-mga** [comment]
> Add missing use_parent_shader initialize value

Looks like this change is no longer relevant (there is now a use_parent_material parameter instead) and it introduces merge conflicts.

> Add float op for dot

Regarding this change, it would be good to reach a decision to either accept it or discard the PR.

**Comment by akien-mga** [comment]
There are still merge conflicts and no proper consensus, so I'll close this one for now.

**Pull request closed without merging**
