### PR TITLE
Fix Path2D's add new point's UndoRedo bug

### LINKED ISSUE #89781: Adding new points to Path2D and undoing it breaks scene history
### Tested versions

Regression from #86542

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When you add a new Path2D and add points to it and then undo it, the scene history breaks and you can't do anything until you reload the scene.

### Steps to reproduce

1. Create new scene
2. Add Path2D
3. Ctrl + Click somewhere to add points
4. Undo
5. The scene is unusable

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/89781

Tested locally it works fine.

### CODE REVIEW

**Comment by KoBeWi** [comment]
If you click a point without moving, it prints empty message:

https://github.com/godotengine/godot/assets/2223172/49d5e03a-7ba9-4626-bb1d-71268312f645

**Comment by akien-mga** [comment]
@KoBeWi The PR has been updated after your review.

**Review by KoBeWi — APPROVED** [review]
I think I forgot to approve after testing again, sorry.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
