### PR TITLE
Include quotes conditionally for dropped paths

### LINKED ISSUE #33317: Dragging a node into Script Editor always adds quotes to the path
**Godot version:**
3.2 alpha3

**Issue description:**
When you drag and drop a node into Script Editor it automatically inserts the node path, but the path always contains quotes. I found myself always using this feature with $ operator, which doesn't need quotes, so they could probably appear only if necessary.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #33317

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by timothyqiu** [comment]
* Since the dropped code can only be used with `$` now, does it make sense to prepend a `$`?
* When dropping multiple nodes, is something like `Player/AnimationPlayer,Timer,Button` intended?

**Comment by KoBeWi** [comment]
> Since the dropped code can only be used with $ now, does it make sense to prepend a $?

I think it would make sense. `get_node()` only makes sense for relative paths.

> When dropping multiple nodes, is something like Player/AnimationPlayer,Timer,Button intended?

That's how it was originally, not sure why. Should be resolved after adding `$`, then you can have node arrays etc.

**Comment by KoBeWi** [comment]
Done:
godot windows tools 64_ZF9nX569Xw

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
