### PR TITLE
mbedtls: Update to upstream version 2.28.3

### PR DESCRIPTION
**Pull request by akien-mga**
Rediff patch from PR 1453, lstrlenW is no longer used upstream so that part of the patch was dropped:
https://github.com/Mbed-TLS/mbedtls/pull/1453#issuecomment-1512683251

I'll try to assess if we can drop the whole patch with a test UWP build on 3.x.
*Edit:* the `CryptGenRandom` part is still needed, without it linking fails with:
```
modules.uwp.opt.32.x86.lib(entropy_poll.uwp.opt.32.x86.obj) : error LNK2001: unresolved external symbol _CryptAcquireContext
modules.uwp.opt.32.x86.lib(entropy_poll.uwp.opt.32.x86.obj) : error LNK2001: unresolved external symbol _CryptGenRandom
```

Bugfix release: https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.3
There's one security relevant bugfix for MSVC builds specifically.

The diff is noisy as they changed their code style.

*Edit:* I've confirmed that the `3.x` branch builds UWP fine with this PR backported.

### CODE REVIEW

**Comment by akien-mga** [comment]
Note to self: More work needed before cherry-picking for `3.x`, it did break the build for UWP arm32:
```
cl /Fothirdparty\mbedtls\library\hkdf.uwp.opt.32.arm.obj /c thirdparty\mbedtls\library\hkdf.c /std:c++14 /nologo /MD /O2 /GL /utf-8 /FS /MP /GS /Zc:wchar_t /Gm- /fp:precise /errorReport:prompt /Zc:forScope /Gd /
EHsc /nologo /AI "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\\vcpackages" /AI "C:\Program Files (x86)\Windows Kits\10\\References\CommonConfiguration\Neutral" /EHsc
/w /AI "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib/store/references" /AI "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.2702
3\lib/x86/store/references" /DNDEBUG /DNO_EDITOR_SPLASH /DUWP_ENABLED /DWINDOWS_ENABLED /DTYPED_METHOD_BIND /DGLES_ENABLED /DGL_GLEXT_PROTOTYPES /DEGL_EGLEXT_PROTOTYPES /DANGLE_ENABLED /DWINVER=0x0602 /D_WIN32_W
INNT=0x0602 /DWIN32 /D__WRL_NO_DEFAULT_LIB__ /DPNG_ABORT=abort /D_UNICODE /DUNICODE /DWINAPI_FAMILY=WINAPI_FAMILY_APP /DPTRCALL_ENABLED /DMINIZIP_ENABLED /DZSTD_STATIC_LINKING_ONLY /DXAUDIO2_ENABLED /Ithirdparty
\mbedtls\include /Ithirdparty\libpng /Ithirdparty\zstd /Ithirdparty\zlib /Iplatform\uwp /Idrivers\windows /IC:\angle\include /I.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\immintrin.h(17): fatal error C1189: #error:  This header is specific to X86 and X64 targets
```

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
