### PR TITLE
Fix incorrect virtual function in `VideoStream.set_paused`

### LINKED ISSUE #79709: VideoStream calls wrong virtual function on `set_paused`
### Godot version

4.1.dev (latest)

### System information

Arch Linux

### Issue description

cc @kidrigger 

With #62737, the `set_paused` method is not calling the correct virtual function:
https://github.com/godotengine/godot/blob/8a9af36b59b88a8e26fcc4026e6c55ddb41f1390/scene/resources/video_stream.cpp#L77-L79
This ends up not being much of an issue because the video player internally stops processing the playback when paused, but I think this is currently wrong nevertheless.

### Steps to reproduce

- Develop a GDExtension addon adding new video playback options (like https://github.com/kidrigger/godot-video-reference/tree/canon).
- Define your own `_set_paused` method.
- This method is not called by the engine.

### Minimal reproduction project

N/A - Not viable

### PR DESCRIPTION
**Pull request by AThousandShips**
* Fixes: #79709

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by AThousandShips** [comment]
Realized that this error existed in 4.1 as well so marked for cherry picking

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.

**Pull request merged**
