### PR TITLE
[WIP] ability to add multiple child nodes in single click

### PR DESCRIPTION
**Pull request by d-j-a-y**
`Object * CreateDialog::instance_selected ()` 
change to 
`void CreateDialog::instance_selected(List<Object*> *p_list)`

### CODE REVIEW

**Comment by d-j-a-y** [comment]
**Usage**:
When FOCUS on tree node, multiple nodes can be selected using the
[space] key . Hodling [ctrl] on single mouse click add to current
selection. [shift] mouse click also work for grouped selection.

**Nota**:
multiple node selection not active with search node feature.

TODO? : open collapse node on right left arrow

**Comment by hubbyist** [comment]
[space] key for a selection operation seemed unintuitive to me. [alt] key may be a better choice IMO.

**Comment by d-j-a-y** [comment]
@hubbyist 
>[space] key for a selection operation seemed unintuitive to me. [alt] key may be a better choice IMO.

In fact, it is the normal behavior of the multi selection mode of a godot's Tree ui control  :-)

**Comment by d-j-a-y** [comment]
conflicts salved locally.

i'm fixing another commit and push the branch.

**Comment by hubbyist** [comment]
Still unintuitive to me. :smile:

**Comment by d-j-a-y** [comment]
@hubbyist 
> Still unintuitive to me. 

In most (numeric) trees i have ever meet, [space] is used to toggle leaf selection .... maybe you can open an issue on [tree.cpp](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp ) ?

**Comment by akien-mga** [comment]
@d-j-a-y I'll need you to flex your git muscles and try to rebase this branch to squash all commits together (and edit the commit log of the resulting commit to be explicit about all changes). Feel free to drop by on IRC if you need help with the rebase :)

**Comment by d-j-a-y** [comment]
_trying to rebase..._

**Comment by d-j-a-y** [comment]
in fact, i'll chose to easier way : reimplementing in top of master ...

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/issues/7955#issuecomment-284265872 for tips on rebasing.

**Comment by d-j-a-y** [comment]
on top of master : #7999

**Pull request closed without merging**
