### PR TITLE
Makes all Godot API's Methods lower_case

### PR DESCRIPTION
**Pull request by ISylvox**
Should be able to help this https://github.com/godotengine/godot/issues/8830

### CODE REVIEW

**Comment by reduz** [comment]
this is a fine work, @ISylvox , thanks!

for eveyone else, looks good to me, feel free to merge once travis is done

**Comment by ISylvox** [comment]
@reduz Thanks... It was an easy task, but took me around 7 hour. (^_^)

**Comment by akien-mga** [comment]
Wow, that is strong dedication, thanks! Feel free to drop by on IRC (`#godotengine-devel` on Freenode) to discuss with other devs, some could likely give you interesting tips about using regular expressions to do such changes faster.

**Comment by ISylvox** [comment]
Thanks... It could be made faster, yup (probably less than an hour). But, I need to make sure there was no collision between others (e.g Struct with method, variable with method, etc) :-)

**Pull request merged**
