### PR TITLE
Add an hinting mode setting to DynamicFonts

### PR DESCRIPTION
**Pull request by Calinou**
- Editor font hinting can now be tweaked in the Editor Settings.
- DynamicFonts used in projects now have tweakable hinting settings in their DynamicFontData child. Changes will be visible upon reloading the scene in the editor.

### Preview

**Normal font hinting** (the default setting, which was the former hardcoded setting):

editor_font_hinting_normal

**No font hinting** (smoother but less crisp):

editor_font_hinting_none

**Light font hinting** (compromise between **Normal** and **None** modes):

editor_font_hinting_light

### CODE REVIEW

**Comment by hpvb** [comment]
Note to self for 3.0: Check that after applying this nothing bad happens to projects that don't have this set yet made in older versions. (probably OK, but check)

**Comment by Calinou** [comment]
I just added documentation to the PR.

**Comment by akien-mga** [comment]
Great work! :)

**Comment by hpvb** [comment]
Cherrypicked into 3.0.3

**Pull request merged**
