### PR TITLE
[3.x] Improve some argument names for core types

### PR DESCRIPTION
**Pull request by kleonc**
`3.x` version of #44162.
Fixes https://github.com/godotengine/godot-docs/issues/4805.

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Looks good to me.

**Comment by marcotmotta** [comment]
I like the changes! But why not use `p_target `instead of `p_to`? Don't you think it would be a little bit more clear?

**Comment by kleonc** [comment]
@marcotmotta I didn't really think about it, just tried to make a kinda one to one backport of #44162. For me both `p_target` and `p_to` are fine. Maybe @aaronfranke could tell something more about reasoning for change to `p_to`.

**Review by marcotmotta — APPROVED** [review]
Actually, considering that the original description terms are **TO** and **WEIGHT**, I believe you are right and using `p_to` and `p_weight` are probably better. Sorry for the trouble!

**Comment by kleonc** [comment]
Updated, previously I forgot about `Vector2.cs` and `Vector3.cs`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
