### PR TITLE
Array has(var value) function

### PR DESCRIPTION
**Pull request by pkowal1982**
It would be nice and consistent with Dictionary to have **has()** function in Array class.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Note that this is accessible to GDScript via `<value> in <array>` currently.

**Comment by bojidar-bg** [comment]
Please, rebase the last merge commit out of the PR, since it serves no purpose :smile:  (if you have to update your branch, you can use `get pull --rebase` to skip the merge commit)

**Comment by pkowal1982** [comment]
Ok, it's rebased.

**Comment by bojidar-bg** [comment]
@pkowal1982 Thanks!
If you would like to work on other issues, just make sure to create a separate branch for them, since you are currently PR-ing your master branch :smile: (usually done via `checkout -b <branch-name>`)

**Comment by akien-mga** [comment]
Any dev opinions on this added function?

**Comment by pkowal1982** [comment]
It would be nice to have `bool has_value()` and `Array values()` in Dictionary class also.

**Comment by volzhs** [comment]
It would be good as consistent with ``Dictionary.has()``
But I worried about having several ways or methods for the same thing.

**Comment by bojidar-bg** [comment]
BTW, do you think it would be too hard to add to {Raw,String,*}Array types as well? It would be more consistent that way :smile: .

**Comment by pkowal1982** [comment]
If you're still not convinced think why there is `size()` and `empty()` in Array, one can use `size() == 0` just like `find() != -1`

**Comment by volzhs** [comment]
Personally, I don't like ``empty()`` in Array.
I've never used it and even think there is ``empty()`` until you mentioned it.
Also, I should read, remember and remind ``empty()`` is for ``is_empty()`` not for ``make_empty()``

**Comment by volzhs** [comment]
Adding feature is easy. But deprecating is not easy.

**Comment by reduz** [comment]
you have both the "in" operator and you can do array.find("value")!=-1 , but in general I guess why not

**Pull request merged**
