### PR TITLE
Rename Variant Packed*Array constants for consistency

### PR DESCRIPTION
**Pull request by Calinou**
All arrays are now prefixed with `PACKED_` to distinguish them from GDScript's generic typed arrays.

`RAW_ARRAY` is now `PACKED_BYTE_ARRAY` (RawArray was the name of PackedByteArray back in Godot 2.x).

See https://github.com/godotengine/godot/issues/54161#issuecomment-1000779766.

### CODE REVIEW

**Comment by Mickeon** [comment]
Bit of a heads up, this PR also renames `Transform` to `Transform3D`, but that's not mentioned.

**Comment by Calinou** [comment]
> Bit of a heads up, this PR also renames `VARIANT_TRANSFORM` to `VARIANT_TRANSFORM3D`, but that's not mentioned.

Indeed, this is just to make the `VARIANT_` constants follow `TYPE_TRANSFORM3D`.

**Comment by aaronfranke** [comment]
In addition to TRANSFORM, there's also MATRIX3 and MATRIX32 in this file, which should be BASIS and TRANSFORM2D. It'd be best to do these three renames at once, but it would make sense to do this in a separate PR.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
