### PR TITLE
Rename AudioStreamPlayer2D::get_position => get_playing_position

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes the error message `ERROR: bind_methodfi: Class AudioStreamPlayer2D already has a method get_position` since the pos renaming commit.

### CODE REVIEW

**Comment by akien-mga** [comment]
A similar fix should be done for `AudioStreamPlayer3D` (and maybe double check the rest of the audio API to ensure we don't have mixed usage of `get_position` and `get_playing_position`.

BTW I had also thought of `get_playback_position`, not sure which is best.

**Comment by marcelofg55** [comment]
Yeah, you're right, I've just modified the 3d file too. I think "playing" is better that "playback" since we have is_playing too, but I'm open to opinions :).

**Comment by akien-mga** [comment]
There's also `get_position` in `AudioStreamPlayer`: https://github.com/godotengine/godot/blob/master/doc/classes/AudioStreamPlayer.xml#L26

Could you also rename the reference in the docs while at it? There are no descriptions yet so no risk to lose the data, but at least it will be done :)

**Comment by letheed** [comment]
Sorry, that one is on me! :) I didn't think of pos/position doublons...
I think `playback_position` would be proper English here.

**Comment by akien-mga** [comment]
Two other arguments in favour of `get_playback_position`:
- https://docs.unrealengine.com/latest/INT/BlueprintAPI/Game/Cinematic/GetPlaybackPosition/index.html
- apparently it's the name of an iTunes option

**Comment by letheed** [comment]
This will make things a bit inconsistent between playback interfaces though. Most have `get_position` when others will have `get_playback_position`. Maybe all should be renamed to `get_playback_position`?

A quick `rg "float get_position" -l` yields:

```
modules/opus/audio_stream_opus.h
modules/stb_vorbis/audio_stream_ogg_vorbis.h
modules/theora/video_stream_theora.h
modules/vorbis/audio_stream_ogg_vorbis.h
modules/webm/video_stream_webm.h
scene/audio/audio_player.h
scene/2d/audio_stream_player_2d.h
scene/3d/audio_stream_player_3d.h
scene/resources/audio_stream_sample.h
scene/resources/video_stream.h
servers/audio/audio_stream.h
```

**Comment by marcelofg55** [comment]
I think it makes sense to rename them all to `get_playback_position` then, there is also a `seek_pos`, I guess I should rename that one to `seek_playback_position`?

**Comment by letheed** [comment]
Some have `seek()` while others have `seek_pos()`. Naming them all `seek()` might be simpler, though that's just my opinion.

**Comment by marcelofg55** [comment]
Just renamed `seek_pos` to `seek`. After travis says its ok this should be good to merge.

**Comment by akien-mga** [comment]
Merged manually as 46af050e as there was a small doc merge conflict.

**Pull request closed without merging**
