### PR TITLE
Fix BoxOccluder SVG

### PR DESCRIPTION
**Pull request by MewPurPur**
image

Hmm, this seems a bit messed up, what's with the dark outline?

image

Ah, look what's hiding here!

image

Removes the hidden box, also simplifies the path by drawing the arc at once with the large-arc-flag. (total saved 0.4 kB)

### CODE REVIEW

**Comment by akien-mga** [comment]
Undercover Unity logo smuggled in by @lawnjelly? 📦 :p

**Comment by lawnjelly** [comment]
> Undercover Unity logo smuggled in by @lawnjelly?  :p

Not me!! :grin: I didn't create any of the svgs, this is @Calinou I believe.

**Comment by akien-mga** [comment]
Technically, the front shape was occluding a box, so the icon was correct :P

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
