### PR TITLE
Increase versionCode range v3

### PR DESCRIPTION
**Pull request by dlnsk**
Moved form #19155
Should be cherry-picked into 3.0

### CODE REVIEW

**Comment by akien-mga** [comment]
*Actually* (I'm sorry, you will hate me :D), we should reinstate your 3.0 PR as it was, since there is an even better solution for 3.1+ (the master branch). For the master branch, you can instead use `"1,4096,1,or_greater"`, which will show a slider from 1 to 4096 (should be high enough for most use cases), but still let you input any greater int manually.

In the 3.0 branch this `or_greater` feature doesn't exist, so increasing the limit is fine.

**Comment by dlnsk** [comment]
Don't worry :)
You can cherry-pick from 8e1ade0 for 3.0

**Comment by hpvb** [comment]
I'll pull this into 3.0.3 before the next build.

**Comment by akien-mga** [comment]
@hpvb Make sure to pick only 8e1ade0 (or d71d968 which is the same commit but made against the 3.0 branch already in #19237).

**Comment by hpvb** [comment]
Cherry picked into 3.0.3 (the correct one) :)

**Pull request closed without merging**
