### PR TITLE
Cache OS_LinuxBSD::get_system_dir

### LINKED ISSUE #65157: Editor spawns hundreds of processes on startup to call xdg-user-dir
### Godot version

v4.0.alpha.custom_build [f6714581c]

### System information

Linux

### Issue description

Not a bug but a quality-of-life issue and I really don't know if this is worth looking into. I won't be the least bit mad if you reject this issue.

When I start the editor on my Linux machine it spawns 807 processes (in sequence, not in parallel) to run `xdg-user-dir DESKTOP`. If I start the editor with a `--path` it "only" does it 606 times.

I changed `OS_LinuxBSD::get_system_dir()` to instead return early with a hardcoded path and that took startup time from 8.8 to 7.5 seconds (as measured with the new `--startup-benchmark`) on a small scene.

### Steps to reproduce

To see how many times this happens during startup, here are a couple of different, ugly ways I can think of:
Add a `print_line()` to `OS_LinuxBSD::get_system_dir()`
or
Create a shell script called `xdg-user-dir` which does `echo $@ >> ~/xdg.log` and put it somewhere in your PATH before where the proper `xdg-user-dir` lives. Then `wc -l ~/xdg.log`.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dzil123**
Fixes #65157

### CODE REVIEW

**Comment by Faless** [comment]
If we want to cache it, does it it makes more sense to do that during setup/init instead of removing the `const` property of the method?

**Comment by dzil123** [comment]
That makes sense. Would I do this at the bottom of `OS_LinuxBSD::initialize()`?

On my machine, opening a project causes 1300 calls to get_system_dir, all with SYSTEM_DIR_DESKTOP. No other SystemDir is used. Should it cache every SystemDir, or only SYSTEM_DIR_DESKTOP?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> On my machine, opening a project causes 1300 calls to get_system_dir, all with SYSTEM_DIR_DESKTOP. No other SystemDir is used. Should it cache every SystemDir, or only SYSTEM_DIR_DESKTOP?

We could cache all of them, but indeed I don't see much use for the other system dirs so it's probably fine as is. If the need arises, we can extend the cache by using a HashMap or something.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Yeah that makes sense. One issue could be with removable drives though, if you plug in a USB stick while Godot is running and then want to retrieve or save a file there. But maybe there's a way for the OS singleton to be notified of such change and force re-checking.

**Comment by dzil123** [comment]
I have tested 4.0.beta4 on Windows 10 and Linux, and the editor does not refresh the drives list on adding or removing a USB drive, so adding caching here would not change anything.

`DirAccessUnix` calls `_get_drives` in `get_drive` and `get_drive_count`, and even multiple times in `get_current_drive`, which seems like a possible race condition. `DirAccessWindows` appears to load drives once in the constructor, with no way to evict the cache.

In parallel to that, it seems wasteful to me that every `FileDialog` and `EditorFileDialog` has its own DirAccess, loading the drive list multiple times when `set_access` invalidates the DirAccess, all during the `EditorNode` constructor.

**Pull request merged**
