### PR TITLE
Fix MIDI Note Off missing on some devices

### LINKED ISSUE #27199: MIDI Note Off message never fires (on some devices)
**Godot version:**
3.1 stable

**OS/device including version:**
Windows 10 x64;  MIDI Controller:  Keyrig 49

**Issue description:**
`_input()` receives Note Off messages as `MIDI_MESSAGE_NOTE_ON` instead.  This has the effect of doubling any event which filters out any message that isn't NOTE_ON.  

**Steps to reproduce:**
Add an AudioStreamPlayer to a scene and assign a sound.  Then use the following code:
```gdscript
func _ready():
	OS.open_midi_inputs()

func _input(event):	
	if event is InputEventMIDI:
		print (event.message)
		if event.message != MIDI_MESSAGE_NOTE_ON:  return
		
		var pitch 
		if event.pitch >= 48:
			pitch =  (event.pitch-36) / 12.0 
		else:
			pitch = event.pitch / 48.0

		$Sound.volume_db = -(1-(event.velocity/128.0)) * 15
		$Sound.pitch_scale = pitch
		$Sound.play()
```

Sound will play twice when a key is struck, once on note on and once on note off.

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes #27199

### CODE REVIEW

**Comment by nobuyukinyuu** [comment]
It should be noted that this change can theoretically trigger an edge case scenario where a program doesn't expect note off (perhaps a continuous instrument of some kind, like a theremin?) and create unexpected behavior, but under most normal circumstances this solution represents programmer expectations under most far more common scenarios.

If any more edge cases come up, may I suggest here (for any potential future PR that may come up regarding this) an enum with configuration flags to handle the treatment of such scenarios?

That aside, thumbs up from me 👍

**Comment by TailyFair** [comment]
One of my MIDI keyboard (M-Audio Keystation mini 32) doesn't send NOTE_OFF signal, only NOTE_ON with velocity 0, so this is great improvement !

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Pull request merged**
