### PR TITLE
[3.x] Fix `TexturePreview` crashing

### PR DESCRIPTION
**Pull request by AaronRecord**
Fixes https://github.com/godotengine/godot/issues/50702 for `3.x`

### CODE REVIEW

**Comment by pycbouh** [comment]
You should still use `NOTIFICATION_THEME_CHANGED` and check if the font is valid before duplicating and doing anything with it. Just because https://github.com/godotengine/godot/issues/50743 exists doesn't mean we should compromise on user experience when we can easily do the check here.

Font can still be invalid if, for example, someone uses a custom theme resource with that theme item not being set. With a check we can avoid the crash with a graceful behavior.

**Comment by LightningAA** [comment]
> You should still use `NOTIFICATION_THEME_CHANGED` and check if the fetched font is valid before duplicating and doing anything with it. Just because #50743 exists doesn't mean we should compromise on user experience when we can easily do the check here.

For some reason `EditorAbout` [was changed to only update it's theme in `NOTIFICATION_TREE_ENTER`](https://github.com/godotengine/godot/commit/4758057f205a7d2e0d2db2c034705b7afcdf310f#diff-35a6b6fb0e84d2469de9ad1bd4b47405b9e1eb58a74b2529ae404c1f922c649dR53), (which might've been a mistake).

> Font can still be invalid if, for example, someone uses a custom theme resource with that theme item not being set. With a check we can avoid the crash with a graceful behavior.

Hmm, but then how come in the 18 other cases that do something similar (`(\n\s*(case NOTIFICATION_ENTER_TREE:|case NOTIFICATION_THEME_CHANGED:)){2}`), the only one that does a null check is one that uses a non constant string (in `script_create_dialog.cpp`) 🤔.

**Comment by pycbouh** [comment]
> Also I don't think the user changing the editor theme to use a custom theme resource is a very common occurrence, at least in 3.x.

Does it matter if it's common or not if it's a one line fix for a feature we are supposed to support? 🙃 

> For some reason EditorAbout was changed to only update it's theme in NOTIFICATION_TREE_ENTER, (which might've been a mistake). 

It is a mistake, the signal is also send when you change one of the predefined themes, or change configurable properties of the predefined themes. There are some parts of the editor that ignore that fact, and it's a bug every time.

> Hmm, but then how come in the 18 other cases that do something similar (`(\n\s*(case NOTIFICATION_ENTER_TREE:|case NOTIFICATION_THEME_CHANGED:)){2}`), the only one that does a null check is one that uses a non constant string (in `script_create_dialog.cpp`) 🤔.

Most of the time we don't manually copy or touch the items returns and just pass them to the local override/property setter, where invalid values are handled either way. But I haven't checked all the 18 occurrences that you speak of, there may be possible crashes there as well.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
