### PR TITLE
Fix rotation issue with `NODE_POSITION_VIEW` shader built-in

### LINKED ISSUE #75896: NODE_POSITION_VIEW shader built-ins does not work correctly
### Godot version

v4.0.2.stable.official

### System information

Windows 10

### Issue description

Shader built-in NODE_POSITION_VIEW should show the coordinates of the node in the local space of the camera, but if the node has some rotation, it does not work correctly.
In the following video, you can see that when a node is rotated, its position relative to the camera does not change, but the NODE_POSITION_VIEW value (which is passed to ALBEDO) reacts to the rotation, and this is a bug.

https://user-images.githubusercontent.com/130088064/230925447-66b6b5a2-b248-4f42-a81b-d2aad12987b0.mp4

This bug occurs both when using Forward+ and when using mobile rendering.

### Steps to reproduce

1) Create MeshInstance3D and set some mesh
2) Add shader material
3) Create a new shader
4) Set value from NODE_POSITION_VIEW as ALBEDO
5) Rotate the MeshInstance3D node
6) You can see how mesh changes in color, but it shouldn't because its position relative to the camera doesn't change

### Minimal reproduction project

[NodePositionViewBug.zip](https://github.com/godotengine/godot/files/11191396/NodePositionViewBug.zip)

### PR DESCRIPTION
**Pull request by paddy-exe**
Fixes https://github.com/godotengine/godot/issues/75896

Somehow I can't test the compiled editor since the changes do not change anything for me locally... but I used the matrices separately just like in the source code here:

https://user-images.githubusercontent.com/38077837/232257608-f3ffe5bf-1d95-4dd7-bd10-bb3d05ae0904.mov

https://user-images.githubusercontent.com/38077837/232312679-330383d0-cf25-4a89-87ea-29f1bcd20676.mov

### CODE REVIEW

**Comment by MrAndriy804** [comment]
So I compiled the editor and these changes solved the issue. Thanks!

https://user-images.githubusercontent.com/130088064/232324552-deccd6cd-aed7-4b3f-9f2f-3804c956bb40.mp4

**Comment by paddy-exe** [comment]
> So I compiled the editor and these changes solved the issue. Thanks!

Great to hear, thanks for testing!

**Review by clayjohn — APPROVED** [review]

**Comment by paddy-exe** [comment]
Quick rebase for a merge :D

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
