### PR TITLE
Highlight control flow keywords with a different color (3.x)

### PR DESCRIPTION
**Pull request by Calinou**
`3.x` version of #33577.

This makes them easier to distinguish from other keywords.

### CODE REVIEW

**Comment by EricEzaM** [comment]
Maybe add a screenshot to your op?

**Comment by Calinou** [comment]
I updated the control flow keyword color to match the `master` pull request.

**Comment by 244164401** [comment]
I don't like too many colors, it will dazzle me. If you really want to add, you can provide different options of themes.

**Comment by Calinou** [comment]
@244164401 Please keep discussion on the feature on the "main" pull request: https://github.com/godotengine/godot/pull/33577#issuecomment-826283524

**Comment by Calinou** [comment]
Rebased and tested again, it works successfull. Script thumbnails in EditorFileDialog also use the new colors correctly, although you'll have to clear your Godot cache while the editor is closed to update thumbnails.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
