### PR TITLE
Container scales to best utilize space(as per min_size)

### LINKED ISSUE #28818: HBoxContainer doesn't shrink after child controls shrink
**Godot version:**
3.1

**OS/device including version:**
macOS 10.14.4

**Issue description:**
Screen Shot 2019-05-10 at 10 46 31 PM

Setting rect_min_size.x on a button that's in a HBoxContainer to a value larger than the container (and its parent, a PopupPanel) will result in the HBoxContainer keeping that width even after the button is shrunk later on:

```
extends PopupPanel

func _ready():
    connect("minimum_size_changed", self, "_minimum_size_changed")
    connect("resized", self, "_resized")
    
    $HBoxContainer.connect("minimum_size_changed", self, "_box_minimum_size_changed")
    $HBoxContainer.connect("resized", self, "_box_resized")
    
    call_later(self, "_grow", 1)
    call_later(self, "_shrink", 2)
    call_later(self, "_print_sizes", 2.5)

    show()
    
func _grow():
    log_message("growing")
    $HBoxContainer/Button.rect_min_size.x = 800
    
func _shrink():
    log_message("shrinking")
    $HBoxContainer/Button.rect_min_size.x = 200
    
func _minimum_size_changed():
    log_message("PopupPanel.rect_min_size: " + str(rect_min_size))
    
func _resized():
    log_message("PopupPanel.rect_size: " + str(rect_size))
    
func _box_minimum_size_changed():
    log_message("HBoxContainer.rect_min_size: " + str($HBoxContainer.rect_min_size))
    
func _box_resized():
    log_message("HBoxContainer.rect_size: " + str($HBoxContainer.rect_size))
        
func _print_sizes():
    log_message("final sizes:")
    _minimum_size_changed()
    _resized()
    _box_minimum_size_changed()
    _box_resized()
    
func log_message(message):
    print(str(OS.get_ticks_msec() / 1000.0) + "s - " + message)
    
func call_later(call_target, function_name, seconds_as_float):
    var timer = Timer.new()
    timer.connect("timeout", call_target, function_name)
    timer.set_wait_time(seconds_as_float)
    timer.one_shot = true
    timer.start()
    call_target.add_child(timer)
```

The example is contrived in order to be minimal, but having such a larger size can be possible in intermediate states before coming to a final size, especially when there are other child controls in the HBoxContainer and you don't know their size.

**Steps to reproduce:**
Run the attached project and wait for it to finish. The expected behaviour is that the HBoxContainer shrinks eventually.

**Minimal reproduction project:**
[size.zip](https://github.com/godotengine/godot/files/3168083/size.zip)

### PR DESCRIPTION
**Pull request by swarnimarun**
Fixes #28818

I am not sure what would be a better way to solve this problem, I had been thinking about it(for a whole day) as this somehow feels too simple or crude, any suggestions are welcome.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
At first glance, this seems like a hack - adding a special variable to `Control` named `Container`, that is only ever going to be used by `Container`s, which are a specific subclass of `Control`, seems... icky. Classes shouldn't be concerned about the specific concerns of their subclasses.

Furthermore, having that variable effectively just always triggering `_size_changed()` is weird too. It is already checking if the minsize changed, why doesn't that work?

Without running tests, it seems weird that this is needed at all - but if there is no better fix, maybe we should at least use a better name for the variable.

`minsize_dirty`? `dirty` is used in the context of "cached values need to be updated" elsewhere in the codebase.

**This is just some rambling after a first look, please don't change anything yet and wait for more feedback :)**

**Comment by swarnimarun** [comment]
@mhilbrunner 
Those are the exact same thoughts I had, there is solution though it is to make the function virtual and override it in container class. But I am not sure that is allowed?

**Comment by swarnimarun** [comment]
I mean allowed in the sense that is OK to do for a PR.(I know it will work.)

**Comment by swarnimarun** [comment]
Now that I think about it, I don't see a reason why it can't be in a PR... Other than my fear of not adding virtual functions. 

I feel like an idiot now. 😭😭

Will fix it ASAP. (Sorry for the crying and rambling... *sobs*)

**Comment by swarnimarun** [comment]
But is it really ok to do it, cause it would mean changing a lot of things to protected/public includiing the _update_minimum_size() function, data struct, and _size_changed() function.
 
My mood swings are rampant.... *sigh*

**Comment by mhilbrunner** [comment]
Lets wait for some feedback/ideas from the core devs :)

**Comment by mhilbrunner** [comment]
This looks relevant, can you have a look and see if it improves the issue? https://github.com/godotengine/godot/pull/28952

**Comment by groud** [comment]
I am not sure what this PR tries to achieve, but the linked issue is surely not an issue.
Shrinking a child of a container should simply not be allowed (only the minimum size). And if the minimum size goes higher that it'd parent size, the parent can have is size increased but never the other way around.

**Comment by swarnimarun** [comment]
@groud That's a problem in case of containers which are supposed to best fit the min_size rather than change as per the rect_size.
Let me put up a better example, if I scaled something that is a resizable box(inside a container), then the other items around it wouldn't be resized, or repositioned.

**Comment by swarnimarun** [comment]
That is if I scale the box down.

**Comment by groud** [comment]
> That's a problem in case of containers which are supposed to best fit the min_size rather than change as per the rect_size.

A container does not "best fit the min_size", it just expands to allow its children to have the expected size, that's all. If you scale down the minimum size of a child, it's up to the user to reduce the parent's minimum size (likely by setting the size to 0x0 on the container, so that it gets updated).

>I scaled something that is a resizable box(inside a container), then the other items around it wouldn't be resized, or repositioned.

I you mean the parent's container, that's expected behavior. If you mean the others children, that might be a bug. For example in a Hboxcontainer with several buttons inside, reducing the minimum size of one of the button should indeed move the other buttons. I that case, I'd like to see the problem with a gif or a video if you can provide that. :)

**Comment by swarnimarun** [comment]
Oh ok, I understand it then. Closing it.

**Pull request closed without merging**
