### PR TITLE
Change incorrect "lightNing" to "lighTING" in WorldEnvironment.xml

### PR DESCRIPTION
**Pull request by corrigentia**

### CODE REVIEW

**Comment by akien-mga** [comment]
Note: for the godot-docs repo we don't care much about the git history, but for the engine repo please make sure to use explicit commit logs, and not the default "Update $filename" proposed by the GitHub online editor.

I'll merge this one as is though, I only mention it for future PRs.

**Comment by corrigentia** [comment]
> [...] for the engine repo please make sure to use explicit commit logs, and not the default "Update $filename" proposed by the GitHub online editor.

@akien-mga : I don't think I've quite understood the point you were making. Would you please be so kind as to clarify whether you were advising me to 
1) leave out the name of the file to which I'm making the changes
and
2) write an explicit commit message instead of a vague "Change abc.xyz".

Much obliged. :smile:

**Comment by akien-mga** [comment]
I mean that your commit log should be "Change incorrect "lightNing" to "lighTING" in WorldEnvironment.xml", not just the PR's title. (Or "Docs: Fix typo in WorldEnvironment.xml".)

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#be-nice-to-the-git-history and the following section.

**Pull request merged**
