### PR TITLE
Add a getter for the EditorInspector

### LINKED ISSUE #26951: EditorInspector is exposed to the scripting API, but there is no way to get it.
Godot 3.1 RC2

**Issue description:**
We can see [EditorInspector in the scripting API](https://docs.godotengine.org/en/latest/classes/class_editorinspector.html)

But if you run a [search](https://docs.godotengine.org/en/latest/search.html?q=EditorInspector&check_keywords=yes&area=default), you will find no methods that actually return a reference to it, neither in EditorPlugin, EditorInterface, or EditorInspectorPlugin.

We should add a quick getter in EditorInterface that returns a reference to it. Otherwise, if you use an EditorInspectorPlugin to add a GUI to the Inspector, there's nothing you can do to actually refresh the GUI except click away and back on again (which is ridiculously annoying).

### PR DESCRIPTION
**Pull request by willnationsdev**
Closes #26951.

### CODE REVIEW

**Comment by willnationsdev** [comment]
I also noticed a bug where the sub-inspectors weren't updating if you changed the value of a Resource property in a Node. Now, if you tell the Inspector as a whole to refresh, it will also refresh the sub-inspectors.

**Comment by reduz** [comment]
seems good

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Pull request merged**
