### PR TITLE
Add InputEvent icons

### PR DESCRIPTION
**Pull request by MewPurPur**
Possibly finished version:

image

Adds a new color for the "activated" part.

Also does stuff with some other icons I came across as I was copying stuff:

-  CapsuleShape2D: Draw it with a simple stroke instead of a complex path.
- JoyAxis: Remove unnecessary transform. Also, I made the middle circle bigger, I think it looks better that way - feel free to bikeshed it.
- JoyButton: Remove unnecessary transform. Draw masked circles with 2 arcs instead of 4.
- Joypad: Draw masked circles with 2 arcs instead of 4, simplify bezier curves into arcs.
- KeyboardPhysical, Shortcut: Simplify the icon and fix it up (??? it didn't have a viewbox like most other headers idk)

### CODE REVIEW

**Comment by MewPurPur** [comment]
I know nothing about joysticks :V  Well, this sounds like a better way to make the distinction.

**Comment by MewPurPur** [comment]
@Calinou 

How's this? 
image

**Comment by aaronfranke** [comment]
@MewPurPur Wouldn't it make more sense for the motion lines be on the other direction from how it was tilted?

240067664-b4ce4cb7-9084-4743-80f9-af521b6d87ad

For the other ones, here are some icon suggestions:

* InputEventMagnifyGesture: Two fingers with double-sided arrows either above or between them.
* InputEventPanGesture: A finger with lines of motion on one side. (not sure what the difference is between this and InputEventScreenDrag, but maybe the gesture is 2 fingers?)
* InputEventScreenDrag: A finger with lines of motion on one side. (again not sure what the difference is)
* InputEventScreenTouch: A finger with curved lines around it.
* InputEventAction: This is the tricky one. It's quite abstract since it's not connected to any real input device. Part of me wants to commandeer the CharacterBody icon and color it white, since this is closely connected with the code for performing in-game actions. Or, thinking of the code, maybe it should be an ampersand since this is expected to be used with StringNames. Or maybe an arrow pointing to a box, but that might be confused for just an icon for input in general. Maybe an arrow pointing to an ampersand →& ? Or an arrow pointing to a white CharacterBody icon?

**Comment by bruvzg** [comment]
> For the other ones, here are some icon suggestions

Fingers and arrows probably won't be recognizable at this scale, so maybe something similar to Xcode gesture recognizers icons would work better?

Screenshot 2023-05-23 at 03 15 10

**Comment by MewPurPur** [comment]
OK, thanks for showing this stuff! I got some ideas, I'll try to get it done this week. And I agree with you Aaron, I'll tweak the icon to consider this.

**Comment by MewPurPur** [comment]
- Changed InputEventKey's label from A to K, as I thought it might be confused for Action.
- Added InputEventAction as with a gear label to represent its configurability.
- Updated InputEventJoypadMotion icon to a more sensible direction.

I'll do the remaining 4 later, maybe in another PR if this one gets merged.

**Comment by MewPurPur** [comment]
The biggest hurdle is that I don't really know in what context the remaining 4 input events are used, namely:
- InputEventScreenDrag and InputEventScreenTouch: These two have similar names, so I suspect they are used in similar contexts. The names suggest that one is for dragging one or multiple fingers across a touchscreen, while the other seems like it's only for multitouch.
- InputEventMagnifyGesture and InputEventPanGesture: These two also have similar names, so I suspect they are used in similar contexts. The name suggests that one is for pinch-to-zoom gestures, which to my knowledge are only on touchscreens; the other suggests pan gestures on laptop touchpads.

For example, I've got this for InputEventMagnifyGesture, assuming a touchscreen:

image

(The SVG itself in case it's lost, since I've not pushed it yet: `<svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1zm1 0v10.75h8V2z" fill="#e0e0e0"/><path d="M8.9-.2a1.75 1.75 0 1 1 3.3 0l-1 2.1a1.6 1.6 0 0 0 0 1.5l1 2.1a1.75 1.75 0 1 1-3.3 0l1-2.1a1.6 1.6 0 0 0 0-1.5l-1-2.1z"  transform="rotate(28.5)" fill="#69c4d4"/></svg>`)

But InputEventPanGesture seems to be in the same category, yet it doesn't come up in the context of touchscreens. The few people I talked with who seemed to have an idea said it was for laptops touchpads, and claim it has nothing to do with touchscreens. Moreover, InputEventScreenDrag seems similar and for touchscreen. And on my personal laptop, using two fingers is just detected as if I'm using a 4-way scrollwheel, as an InputEventMouseButton (idk how to use my android to test this right now). This would be awkward and confusing if I get it wrong.

I'll keep trying to figure this out, but please, this isn't a WIP and I don't think it *needs* more work. The last icons can be added and tweaked later.

**Comment by MewPurPur** [comment]
OK! Doned, check out the PR description for the updated icons in their context.

**Review by deralmas — APPROVED** [review]
So pretty! Love 'em!

**Comment by MewPurPur** [comment]
Yeldham wasn't happy about motion lines, I want to test out his motion blur proposal first.

**Comment by MewPurPur** [comment]
Motion blur looks better, yup. Updated the description with the new icons.

**Comment by MewPurPur** [comment]
I did motion blur for InputEventMouse**Motion** and InputEventJoypad**Motion**. The other are impact lines and I think their approach is good.

**Comment by YeldhamDev** [comment]
Just putting my other 2 cents, here's a suggestion I did back in the dev chat about the keypress ones:

InputEventKey

**Comment by YeldhamDev** [comment]
> That's also one thing I like about the icons of this PR, they mesh really well with the actually pretty iconic and almost cartoony style of Godot.

I have zero problems with the cartoonish style, it's just that I'm worried about visual pollution on icons so small. Which is why I generally try to simplify those whenever possible.

**Comment by YeldhamDev** [comment]
> lots of node icons are already really complex

Existing stuff being bad doesn't justify ignoring those type of problems. If anything, this means we should start paying double attention for this sort of thing.

**Review by Calinou — APPROVED** [review]
Looks good to me. For reference, this is how icons look with editor scale set to 100%:

### Black (OLED) theme

image

### Light theme

image

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by aidan-j-rhoden** [comment]
What is the InputEventMIDI icon for? I was unable to find such an option in the input settings (which would be really nice, btw)

**Comment by aaronfranke** [comment]
@aidan-j-rhoden It's for MIDI devices, such as a piano or guitar. Musical Instrument Digital Interface.

**Comment by aidan-j-rhoden** [comment]
Yes, I understood that part.  Is the icon simply for documentation, or is it an actual option, like a physical key or joy button in the Input Map?

**Pull request merged**
