### PR TITLE
Exposed almost all the TextEdit's functionality to the scripting languages.

### PR DESCRIPTION
**Pull request by mrcdk**
- Renamed some internal function names like `get_code_comple()` to `get_code_completion()`
- Renamed signal `request_completion` to `completion_requested` (breaking change although it was useless before)
- Added documentation to the new functions and properties.

### CODE REVIEW

**Comment by akien-mga** [comment]
The documentation changes partly overlap with #29743 from @zaksnet, it would be good to cross-review and take the best strings from both PRs.

The API bindings and internal renamings are fine, but we shouldn't break compat in the scripting API for 3.2, so `request_completion` has to stay in some form. It can be kept as a deprecated alias for `completion_requested`, or the renaming can happen for 4.0 via #16863.

**Comment by mrcdk** [comment]
The signal `request_completion` was useless before because you couldn't enable code completion before so it was never emitted that's why I renamed it. The user could manually emit it but I don't see any reason for anyone to do that. If you still want me to revert it to the old name I will.

I'll check the other documentation PR and update this PR if needed.

**Comment by akien-mga** [comment]
> The signal request_completion was useless before because you couldn't enable code completion before so it was never emitted that's why I renamed it. The user could manually emit it but I don't see any reason for anyone to do that.

Ok, that makes sense.

**Comment by akien-mga** [comment]
This can now be rebased on top of #29743 / master.

**Comment by mrcdk** [comment]
Okay, rebased 😄

**Comment by akien-mga** [comment]
For the reference, the code looks fine but I'm just unsure yet if we really want to expose *all* of TextEdit's internal API to scripting languages.

TextEdit has a lot of features added for the editor's own needs, and like most editor features, they might be a bit hacked as they were meant for a single purpose. If this needs to be exposed as a general purpose API for any game or tool's TextEdit uses, I don't know if the current API is good as is (I mean, it was not designed for the general purpose so far).

Exposing it means that we need to maintain compatibility for the future, while we could refactor those unexposed methods all we want if not exposed, so this should only be done if we are confident that the resulting public API is good and future proof.

Note: I haven't done that review yet myself, I'm just writing down the main concern I have. It might be that the exposed API *is* already a good general purpose API.

CC @Paulb23 @reduz

**Comment by Paulb23** [comment]
Yeah, some of these are pretty rough and defiantly not ready for exposing to the API yet. In addition, there are other methods that aren't here but should be fixed up and bound as part of some toggleable features.

**Comment by mrcdk** [comment]
Can you guys give a more detailed answer? Which parts are rough to be exposed? Which parts aren't ready yet? It basically exposes code competion, callhints settings and the content, setting the different gutters and add/remove/list which lines are being marked by those, setting the line guide, some text manipulation (adding lines, removing lines, replacing lines, adding and removing indents,...) I don't really see anything here that's rough or not ready to be exposed (all of this is being used already by the different code editors that Godot has)

**Comment by akien-mga** [comment]
I'd suggest to go with a more use-case focused approach, where you'd expose only what you actually need. We can then review if what you need is among the APIs that we feel are too rough and should thus be refactored before being exposed. That would be easier to review without having the feeling that we're exposing stuff which is potentially not relevant for Godot project or with APIs that we feel are not good enough (and then can't change easily without breaking compat).

You can do it in another PR though and keep this one for general discussion on TextEdit's whole API.

**Comment by akien-mga** [comment]
Closing as per previous comment - a PR focused only exposing the private APIs actually needed for your project would likely be better at this point.

Further discussion on the TextEdit API and how to improve it further on can be done in #31739.

**Pull request closed without merging**
