### PR TITLE
Check swapchain operations are in the right thread

### PR DESCRIPTION
**Pull request by darksylinc**
I am unsure if this is the right approach to do this, so I'm submitting this PR as a draft looking for feedback:

I'm [beginning to suspect](https://github.com/godotengine/godot/issues/81670#issuecomment-1722093886) certain swapchain operations are being called from a thread that shouldn't be.

I don't want to use _THREAD_SAFE_METHOD_ for a few reasons:

1. It's never been used in vulkan_context.cpp but rather always used in rendering_device_vulkan.cpp (thus I'm not sure but this suggests to me that VulkanContext should not have to worry about thread safety).
2. I would have to hunt a lot more calls, e.g. every time VulkanContext::windows is accessed it must be protected by a mutex (it's currently not).
3. On macOS & iOS, Cocoa/UIKit will start screaming if the main thread isn't doing window operations. I don't know how compatible it would be with Apple ecosystem even if using MoltenVK.

I don't know if crashing is the right way to do it, or if this check should only be present in Debug builds; or if the Editor should be notified, etc.

Feedback is appreciated.

### CODE REVIEW

**Comment by sakrel** [comment]
The lack of synchronization also causes crashes when godot is in [Mulit-Threaded](https://docs.godotengine.org/en/stable/tutorials/performance/thread_safe_apis.html#rendering) mode on [x11 and wayland](https://chat.godotengine.org/channel/rendering/thread/FzYTJTSoGnMhmzrfD).

**Comment by darksylinc** [comment]
Oh yeah, that is EXACTLY what I was afraid of.

For this to happen Multi-Threaded must be on?

BTW I believe the most platform-compatible way to do this would be to route the calls to the main thread and process them when they arrive (although the question is how we wait for the result for calls that have return values).

I believe Godot is already doing something like this for other threaded operations thouhg.

**Comment by AllianceDarkSylinc** [comment]
OK yeah, I can confirm these checks trigger when setting the thread model to Multithreaded and running the game in non-editor mode (because the Editor always forces single thread).

Some of those checks would be safe to protect them with a `_THREAD_SAFE_METHOD_` like Sakrel did, but others (like _update_swap_chain/_clean_up_swap_chain) are more dubious.

Additionally, there's a potential chance of a deadlock (if the MT Rendering Thread acceses a window through a VulkanContext at the same time another thread is doing the same and wants to also wait on the MT Rendering Thread)

**Comment by darksylinc** [comment]
OK yeah, I can confirm these checks trigger when setting the thread model to Multithreaded and running the game in non-editor mode (because the Editor always forces single thread).

Some of those checks would be safe to protect them with a `_THREAD_SAFE_METHOD_` like Sakrel did, but others (like _update_swap_chain/_clean_up_swap_chain) are more dubious.

Additionally, there's a potential chance of a deadlock (if the MT Rendering Thread acceses a window through a VulkanContext at the same time another thread is doing the same and wants to also wait on the MT Rendering Thread).

So far they haven't triggered with Single Thread model though.

**Comment by sakrel** [comment]
Maybe it would make sense to wait for the [`RenderingDevice` threading rework](https://github.com/orgs/godotengine/projects/33/views/1?pane=issue&itemId=5163837) to be completed?
 After the threading rework, `RenderingDevice` functions (aside from resource creation) can only be called from the Rendering Thread. I think it would make sense to do the same for `VulkanContext`.

For example, instead of calling `VulkanContext::window_resize` directly in the platform DisplayServer class, we could instead add a `RenderingServer::window_resize` function that then calls `VulkanContext::window_resize` on the Rendering Thread.

**Comment by darksylinc** [comment]
Well, my checks are more because I suspect there is a bug (even in Single Thread) causing infrequent crashes (which need analysis and fixing).

While your encounter was more about being able to run Multi Thread model without crashes.

Of course my checks are related to your work; they just had different goals in mind.

**Comment by darksylinc** [comment]
This PR is obsolete.

**Pull request closed without merging**
