### PR TITLE
Make `ResourceCache::get_cached_resources` thread-safe

### PR DESCRIPTION
**Pull request by voidedWarranties**
Fixes invalid `Ref` and editor crash resulting from a Resource being freed just before this method is called (e.g. when saving or creating a resource).

In my use case, this is triggered by Lua's garbage collector (currently tied to `ScriptLanguage::frame`) collecting and dereferencing the Resource before/during the save.

Mirrors the solution seen in other methods (`has` and `get_ref`).

### CODE REVIEW

**Comment by akien-mga** [comment]
Why keep a vector of entries to remove, instead of not adding them in the first place?

**Comment by voidedWarranties** [comment]
`has` and `get_ref` remove the deleted Resource from the cache (`resources`) whenever detected (I'm not sure why, that's just how it was).
During iteration, I avoid adding the deleted Resource to the list (`p_resources`) then keep a vector of entries to delete from the cache after iteration finishes to match the functionality of `has` and `get_ref`.

**Comment by akien-mga** [comment]
I see, I misread as I was checking the diff on a phone. I'd suggest making the `Vector` a `LocalVector`, which is better suited for this use case.

**Comment by RandomShaper** [comment]
At first, I was thinking the validity of this PR depends a bit on the (sadly unwritten) contract of this function. I mean, it may be expected not to do any validation-and-removal itself to be as fast as possible and so keep the cache locked for as short as possible, leaving the responsibility of checking the validity of the references to the caller.

However, after checking the few uses of this function across the codebase, I'd say it's pretty clear that the caller is expected to get valid references, only, so this looks fine to me. Also, I support the change to `LocalVector`.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
