### PR TITLE
FIX to broken item select list (zoom and RMB)

### PR DESCRIPTION
**Pull request by Ranoller**
FIX to #17346. Compiled and tested.

### CODE REVIEW

**Comment by groud** [comment]
I think I changed button for the selection menu on purpose, since it makes more sense than using the right click for selecting things.

**Comment by Ranoller** [comment]
I don´t think you changed that without discussion. It seems more like an autocomplete mistake or something like that because this file have a lot of BUTTON_LEFT and when you wrote that part probably none BUTTON_RIGHT.

I like too LMB, but for now it needs to be RMB for various reasons: 
  ·3D Editor is RMB
  ·Tool tips helpers indicates RMB
  ·Translations and all docs have RMB
  ·Godot 2 is RMB (well, this is nor really very important, but is a reason)

And the more important...i don´t find any disussion, nor issue or report to change to LMB. So, for now, I think this is the correct way. I´m wrong? But if a discussion/issue is started i vote for this change too, in 2d and 3d. But be prepared to the oposition of some users that use RMB in modeling programs and will fight to death to maintain that (Ok, i´m exaggerating :DDDD )

The second change that i propose is very important, because without that select item list is broken.

I think that for now this commit should be merged like it is, and later discuss LMB change. That´s my opinion, but feel free to do whatever.

And @groud thanks for your work in 2D editor, good job.

**Comment by groud** [comment]
Yes, I did change it on purpose.

> for now it needs to be RMB for various reasons

All reasons you mention are consistency matters. The real question is whether RMB is better than LMB. In that case, the docs and tooltips update can come afterwards, this is usually how we operate. Also, not every change has to be discussed in an issue, I felt like it was more obvious this way so I changed it directly without asking.

That being said, this is probably a mistake, since @reduz told me some linux distribution use alt+LMB as a default shortcut to move windows. So I guess that's a good reason to go back to the RMB shortcut. 

> But be prepared to the oposition of some users that use RMB in modeling programs and will fight to death to maintain that (Ok, i´m exaggerating :DDDD )

Only blender does that actually, and most users don't understand why RMB is used for selection.

I believe we can merge this until I find a better solution for this inconsistency then.

**Review by groud — APPROVED** [review]

**Comment by hpvb** [comment]
This fixes an issue not (yet) present in 3.0.x. Keeping it here for when we merge the pr that caused this issue.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.

**Pull request merged**
