### PR TITLE
Change Place Random Tiles to an icon

### LINKED ISSUE #57483: Tilemap editor width is too big on 1366x768 with 100% scaling, Inspector gets cropped
### Godot version

4.0.alpha1

### System information

Ubuntu 20.04

### Issue description

The new tilemap editor stretches a bit to the sides in my setup with 100% scale and 1366x768 resolution, which causes the inspector dock to be slightly off-screen. 

image

### Steps to reproduce

* Change your resolution to 1366x768 if not default.
* Open the TileMap editor plugin.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
This PR changes "Place Random Tile" button to a single icon without text, in order to resolve #57483
image

Also since this is for random placement, I named the icon RandomNumberGenerator, so it's used for that class.

As for this comment:
> or, if it works, we may replace the HBoxContainer of the toolbar by the brand new FlowContainter. That could help on small screens.

Last time I tried it, it didn't work as expected. HFlowContainer isn't a direct replacement for HBoxContainer, because it expands vertically and makes the whole toolbar look really bad. It requires some reorganization to use it properly.

### CODE REVIEW

**Comment by Mickeon** [comment]
This is a very, _very_ poor mock-up, but perhaps it can look something like this? It's undeniably tricky to make it fit Godot's icon style and render it distinguishable from the others.
image
image
image

**Comment by fire-forge** [comment]
It is hard to fit so much detail into a 16x16 icon. What do you think about showing only one side of the dice like this?

dice

Which would look more like this at 16x16:

dice small

**Comment by KoBeWi** [comment]
Looks ok, but is it clear that it's a dice? Maybe 2 or 3 dots would be better?

**Comment by YeldhamDev** [comment]
Something like this would be the most adequate solution I think:
dice-three-vector-icon

**Comment by groud** [comment]
I believe we kind of need a 3D view to understand it's a dice. Otherwise it is hard to understand IMO.

But aside from that, I believe replacing the checkbox by an icon sounds good.

**Comment by KoBeWi** [comment]
@YeldhamDev Do you have SVG version?

**Comment by YeldhamDev** [comment]
> I believe we kind of need a 3D view to understand it's a dice. Otherwise it is hard to understand IMO.

The problem is that the icons in Godot are generally 16x16, very little space to represent something in 3D, specially with stuff inside of it.

> Do you have SVG version?

Didn't make that icon, just grabbed one to show as an example. :stuck_out_tongue:

**Comment by YeldhamDev** [comment]
@KoBeWi But I can actually go make one if you want.

**Comment by fire-forge** [comment]
dice 2

I tried it with 3 dots and it does make it much clearer that it's a dice.

To whoever makes the icon, the PanelContainer icon image is a good starting point, because the dice icon is basically that but white and with 3 small squares inside. I have no idea how to make SVGs though, so I can't help.

**Comment by KoBeWi** [comment]
Which one?
image
image

**Comment by YeldhamDev** [comment]
@KoBeWi Would be better to have the inside be filled, it gives a little more space to work with.

**Comment by fire-forge** [comment]
@KoBeWi Maybe fill the inside like YeldhamDev said, then space the 3 dots out a little more.

**Comment by KoBeWi** [comment]
Like this?
image

**Review by fire-forge — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
