### PR TITLE
Implement script editor hover hint with description

### LINKED ISSUE #1393: Implement script editor description hint on hover a symbol/word
**Describe the project you are working on:**
Description hint on hover for the text edit(https://github.com/ThakeeNathees/godot/tree/TextEdit-hover-hint)

**Describe the problem or limitation you are having in your project:**
it's one of the essential feature for a fully featured script editor and currently we lack of. Also the implementation of GDScript doc comments (https://github.com/godotengine/godot/pull/41095) it'll improve the user experience.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
when a symbol is hovered by the mouse, the text editor emits a signal to validate the symbol (like when it's being hovered with a ctrl), and when validating for that symbol it'll add some additional data (like description, type, class_name, return_type, arguments, etc.,) and display them at the text edit's draw call.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A working example (this will work with doc comments when it'll be merged)
hint2

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
No, It would be a great usability improvement and can't be worked around with the script.

**Is there a reason why this should be core and not an add-on in the asset library?:**
there is no way to implement this with an add-on

*Bugsquad edit (keywords for easier searching): tooltip*

### PR DESCRIPTION
**Pull request by Spartan322**
Supersedes #41502
Closes  godotengine/godot-proposals#1393

~~Right now this is just a rebase and basic conversion of #41502 to master, (including CodeEdit changes) I tried to ensure it has a bare minimum functionality testing it, it does properly display the hints, but some things are as of now missed, and I seem to have not gotten documentation to work properly, it'll stay a draft until I can clean this up a bit.~~

This is no longer a direct conversion of #41502, there are things I missed in implementing this proposal in full, I'm not entirely confident this is even a totally correct implementation, hence why I left the initial convert commit (despite being somewhat bugged) unchanged for now and the big reason its still a draft, (the initial conversion was still fairly bugged too and sort of re-implemented rich text popup functionality in CodeEdit) however this does implement many more improvements, alongside some few bugs. I committed this to get eyes on it and to improve this beyond what I've been able to do from this point.

### Improvements
* Hover hints appear on the line below the first character of the hovered symbol 
* Supports hover hints for annotations
* Uses editor settings to enable and modify the hint display
* Relies upon RichTextLabel inside a PopupPanel to display hint text
    * The hint can't currently be focused but it does use a duplicate of the `_add_text_to_rt` function from [/editor/editor_help.cpp](https://github.com/godotengine/godot/blob/005a49704c39d5bbc95d6d15eaab85c4b0ad2a86/editor/editor_help.cpp#L1648).
* Local variables should be able to support descriptions
* All inbuilt classes can display hover hints with descriptions
* CodeEdit only has a new `symbol_hovered(symbol : String, symbol_column_line : Vector2)` signal that ScriptTextEditor relies on for hover hints
* Added `get_word_line_column_at_pos(mouse_pos : Vector2) -> Vector2i` to TextEdit
    * Duplicates `get_word_at_pos` but retrieves the line and column of the first character of the word, used by the `symbol_hovered` signal to abstract the need for retrieving the mouse position.

### Known Issues
* The RichTextLabel may overflow the popup in some cases
* Short symbols may erroneously be wrapped by the RichTextLabel inside the popup
* Hovered symbols may feel incorrect since they do not account for the last character, for single character identifiers this can result in a very deceptively tiny region to activate the hint. (this appears to be the fault of `get_word_at_pos`)
* Symbols inside a `$` may be treated as the type they are named after regardless of whether they're actually based on that type (for example if you named a `Popup` as PopupMenu, the symbol hint for `$PopupMenu` will display a hint for `PopupMenu`)

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Tested locally (rebased on top of `master` 851bc640ddf7225a4b52bb15cc50c249df119953), it works. I think this is a good start, and having this feature will improve the script editor's usability a lot.

https://github.com/godotengine/godot/assets/180032/12e8c524-9698-4e3e-8a16-53dbcaf8034b

There are a few usability issues I noticed:

- Script descriptions don't seem to appear for user-provided properties and methods, even if you restart the editor.
- Strings that match a function name (without parentheses after the function name) will display the function popup (see the end of the above video).
- The hover duration seems pretty low – I frequently accidentally make the popup appear when I don't want to. This is annoying, as the popup also blocks mouse input including scrolling (it scrolls the block if possible, instead of the script).
  - In comparison, it takes roughly twice as long for hover tooltips to show up in VS Code.

- Colors are hard to read on a light editor theme, even after restarting the editor:

https://github.com/godotengine/godot/assets/180032/9407ced6-738b-4178-803d-e5c52f75c984

These issues need to be addressed somehow before this PR can be merged.

**Comment by Spartan322** [comment]
All right, I'll see what I can do.

**Comment by dalexeev** [comment]
* @Spartan322 Note that there is another PR #80044.

**Comment by Spartan322** [comment]
Yeah I'm aware, I've gotten busy and haven't had as much time to work on this.

**Pull request closed without merging**
