### PR TITLE
C#: Fix line in OpenInExternalEditor

### LINKED ISSUE #41816: C# Error message point to one line above in Visual Studio Code
**Godot version:**
Godot 3.2.3 RC4

**OS/device including version:**
Win10

**Issue description:**
When double clicked in any error report it point to one line above in code.

Godot_v3 2 3-rc4_mono_win64_OHUQmYBXce
Code_sACDSKXxl6

**Steps to reproduce:**
Write any code that broke. Click on the error report. it will point to the line above. e.g error in line 45 , it will point the line 44 in Visual Studio Code.

### PR DESCRIPTION
**Pull request by raulsntos**
- Fixes https://github.com/godotengine/godot/issues/41816.
- :warning: Only tested this with VSCode, I hope I didn't break other IDEs :warning:
- ~**Note for 3.x cherrypick**: Requires also cherry-picking https://github.com/godotengine/godot/pull/73584~.

### CODE REVIEW

**Review by RedworkDE — CHANGES_REQUESTED** [review]
This also works in VS, but the built-in editor now points to the line above.

**Comment by raulsntos** [comment]
I looked into this and reached the conclusion that `EditorInterface::edit` takes a 1-based line number, and every other API (`ScriptEditor`, `CodeTextEditor` and `TextEditor`) takes a 0-based line number.

The `ScriptEditor::edit` method was subtracting 1 from the line number which seems to be wrong, since every other API in `ScriptEditor` seems to be 0-based. This was causing the double subtract that made this PR break with the built-in editor.

The double subtract should also be happening with GDScript errors, but in there there is a call to `goto_line_centered` after the call to `edit` which essentially resets the line to right one thus hiding the bug.

As a consequence of these changes this is likely no longer cherry-pickable for 3.x and I have removed the label. If this change is desired for 3.x, a backport PR can be made.

**Review by RedworkDE — APPROVED** [review]
Didn't notice any more issues

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.

**Pull request merged**
