### PR TITLE
Port material texture optimization to Vulkan

### PR DESCRIPTION
**Pull request by clayjohn**
Ports the useful parts of https://github.com/godotengine/godot/pull/33097 into Vulkan

This avoids creating sampler2D uniforms for roughness and metallic textures when not used.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@clayjohn What's the status of this PR? It's currently targeting the `vulkan` branch, which has since been deleted since it has been merged into `master`.

**Comment by clayjohn** [comment]
It's in hibernation until we see what happens with the GLES2 renderer. It's only really helpful if we have a GLES2 renderer that uses SpatialMaterials.

**Comment by aaronfranke** [comment]
Closing because 4.x is planned to have GLES 3 instead of GLES 2 (or potentially both), and this PR is only helpful for GLES 2 as stated [here](https://github.com/godotengine/godot/pull/34767#issuecomment-699584801), so this PR is (likely) not useful. If GLES 2 is added later, this PR can just be re-opened in the future. I'm also adding the "salvageable" label because this PR is (potentially) salvageable. It may need to be re-done from scratch though.

**Comment by clayjohn** [comment]
@aaronfranke please don't close PRs without consulting the area owners.

I've kept this PR open for a reason and I will close it or request that it is merged as appropriate. 

We still need to figure out what we are doing with the low-end renderer and particularly WebGL. This PR was necessary in 3.x for many games to run on firefox. We may face similar limitations in 4.x. 

So please, in the future, ask before closing. It does not hurt to be well informed

**Comment by clayjohn** [comment]
No longer needed as we are going with a GLES3 renderer

**Pull request closed without merging**
