### PR TITLE
Use `[codeblock lang=text]` more often in class reference

### PR DESCRIPTION
**Pull request by Mickeon**
Looooook at @dalexeev leaving the dirty work for me, aye? See https://github.com/godotengine/godot/pull/89263 .

### CODE REVIEW

**Comment by dalexeev** [comment]
I've looked at every `[codeblock]` in the `*.xml` files. Here is the file list. Sorry for not marking the lines/method names.

1\. Files in which you missed something. Godot Shader Language, JSON, XML, formulas, pseudographics and other. For some snippets, GDScript highlighting may be suitable, I just noted for completeness, we can discuss each case.

* doc/classes/@GlobalScope.xml
* doc/classes/CanvasGroup.xml
* doc/classes/ConfigFile.xml
* doc/classes/DisplayServer.xml
* doc/classes/EditorPaths.xml
* doc/classes/FileAccess.xml
* doc/classes/InputEventKey.xml
* doc/classes/ResourceImporterCSVTranslation.xml
* doc/classes/SpriteFrames.xml
* doc/classes/StyleBoxFlat.xml
* doc/classes/VisualShaderNodeColorFunc.xml
* doc/classes/VisualShaderNodeColorOp.xml
* modules/webrtc/doc_classes/WebRTCPeerConnection.xml
* platform/ios/doc_classes/EditorExportPlatformIOS.xml
* platform/macos/doc_classes/EditorExportPlatformMacOS.xml

2\. By the way, I noticed a few other problems. Suggestions:

* doc/classes/AStarGrid2D.xml - Replace C-style ternary with GDScript one?
* doc/classes/Basis.xml - Split code and output into two codeblocks.
* doc/classes/Callable.xml - Fix `"hello world "` -> `"hello world"`.
* doc/classes/JSON.xml - Add a trailing comma, replace `##` with `#`, turn off highlighting, image tab stops with `--->`.
* doc/classes/NodePath.xml - Add `^` for consistency.
* doc/classes/PackedDataContainer.xml - Split code and output into two codeblocks.
* doc/classes/PackedDataContainerRef.xml - Split code and output into two codeblocks.
* doc/classes/RenderingServer.xml - Add a trailing comma, fix weird indentation.
* doc/classes/VisualShaderNodeCustom.xml - Swap `extends` with `class_name`according to [style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html).
* doc/classes/XRInterface.xml - Fix weird indentation.

**Comment by Mickeon** [comment]
I mean, I could've solved those problems in a separate PR. I've noticed a few of these myself.

> doc/classes/Basis.xml - Split code and output into two codeblocks.

I actually would've preferred the opposite! That is, merging the codeblock couple in GlobalScope, as it keeps the example more concise and focused. When I see two codeblocks, I think they're entirely unrelated examples (it also avoids the kinda ugly "Prints" in the middle).

> doc/classes/XRInterface.xml - Fix weird indentation.

https://github.com/godotengine/godot/pull/89282

**Comment by Mickeon** [comment]
> doc/classes/@GlobalScope.xml

Where? I can't find any omissions.

> doc/classes/CanvasGroup.xml

I'd be wary. I have seen a few code samples referencing the shader language, but I thought that the GDScript Highlighter handled them fairly nicely. Better than plain text, at least.
Of course the best outcome would be to plug in the GDShader highlighter, but that's for another time.
image


Should we mark them as text anyway, so that they become easier to find later, perhaps?

**Comment by Mickeon** [comment]
Actually, massive addendum to all of this that I forgot to mention. A lot of these `codeblock`s? They probably shouldn't exist. Some of these are poor documentation handling at its finest, in my book.
Take WebRTCPeerConnection:
image

It's why I want to keep this PR focused and avoid other changes, too.

**Comment by dalexeev** [comment]
> > doc/classes/@GlobalScope.xml
> 
> Where? I can't find any omissions.

`ease()`

**Comment by Mickeon** [comment]
Aaah, there you go. Thank you. But you see what I mean? That could easily be reworded another way without the codeblock.

**Review by mhilbrunner — APPROVED** [review]
LGTM. Needs a rebase though :(

**Comment by Mickeon** [comment]
Rebased after minor conflict.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
