### PR TITLE
Set proper icons for FileDialog in editor theme

### LINKED ISSUE #34291: Tiny icons in FileDialog on retina display
**Godot version:** v3.2.beta.custom_build.cd9d51328

**OS/device including version:** macOS Catalina 10.15.1 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

Icons in some of the FileDialogs are small on retina display.

The project path dialog in Project Manager: (top normal display, bottom retina display)

icon-sizes

The find in files dialog:

script-search-find-in-files-folder

But most other dialogs (e.g. the Save Scene dialog) have a normal icon size.

**Steps to reproduce:**

1. Open Godot editor on a retina display
2. In the project manager:
    1. Click "New Project"
    2. Click "Browse" button, tool icons in the dialog is small
3. Open any project:
    1. Switch to the Script Editor
    2. Click "Search" menu, and choose "Find in Files"
    3. Click "..." button, tool icons in the dialog is small

### PR DESCRIPTION
**Pull request by volzhs**
Fix #34291

### CODE REVIEW

**Comment by qarmin** [comment]
This also fix #28339?

**Comment by volzhs** [comment]
not sure, the export window at **Project -> |Choose or create preset| -> Export Project** now looks different.

image

**Comment by volzhs** [comment]
but it fixes the file dialog in project manager which @Calinou mentioned at https://github.com/godotengine/godot/issues/28339#issuecomment-500111089

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
