### PR TITLE
Some small fixes to warnings in python scripts

### PR DESCRIPTION
**Pull request by Anutrix**
Unreachable code ~~, duplicate imports~~ and same variable names in nested loops were removed/replaced.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Anutrix** [comment]
Undid the import removals as it seems Python treats as local.

**Review by aaronfranke — APPROVED** [review]
I wonder who wrote this code in the first place and decided to declare `i` inside of a loop with  `i`...

**Comment by akien-mga** [comment]
Thanks!

**Comment by neikeq** [comment]
@aaronfranke That has happened to me a gazillion times :disappointed_relieved:

**Pull request merged**
