### PR TITLE
Allow Arrays and Dictionaries to be duplicated or made anew via the inspector

### LINKED ISSUE #13971: Regression: It's impossible to modify exported NodePath array content for instanced subscene
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
af27414b1c10173584539186e396668a899e06b2 Ubuntu 17.04

**Issue description:**
This is an issue that reveals quite often since I'm on 3.0 I'm not always able to reproduce it from scratch, but when it happens it's permanent. Also for the issue to happen, user need to close every scene in which given tool subscene is instanced (even if not directly).
I'm quite sure this is 3.0 related issue since I'm using array nodepaths this way since a long time, also this issue is for sure not very fresh, I tried to track it down couple of times already.
***Short video description:*** https://youtu.be/1fjAQXu49TY
(the subscene don't need to be in tool mode for this to happen as it turned out)

**Steps to reproduce:**
You can check video for quick 40s reproduction process with provided sample
1. Download reproduction project.
2. Open "ExportedNodePathArraySave" tscn
3. Add new nodepath item to 'onTest' node and fill it
4. Save the scene
5. Close it
6. Open "ExportedNodePathArraySave" tscn again and see the node path was not saved

**Link to minimal example project:**
[ExportedNodePathArraySave.zip](https://github.com/godotengine/godot/files/1528086/ExportedNodePathArraySave.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Closes #13971

I couldn't make the "Changes may be lost" button appearing when the Array comes from another scene though.

image

### CODE REVIEW

**Comment by Geequlim** [comment]
@bojidar-bg Any idea with #13346 ？

**Comment by kubecz3k** [comment]
I tested the PR and I'm sorry to say, but I'm still able to observe the issue

**Comment by kubecz3k** [comment]
Oh I probably misunderstood how the fix works. I assume I should choose 'new array' after creating the scene, in such case it works fine!

**Comment by kubecz3k** [comment]
But I don't quite understand use-case for those options, are there any cases when I will not want for my array to be separate from the one that is possessed by parent? (pre 3.0 they were automatically cloned I assume)

**Comment by bojidar-bg** [comment]
@Geequlim No, that other issue appears unrelated to the one solved. I don't know how it should be solved.
@kubecz3k Well, you don't want it to be a separate array in case you are not making changes to it.
Pre 3.0 they might have been saved even if not modified, which would lead to some sort of auto-cloning.

**Comment by kubecz3k** [comment]
Is there any way to detect if the array is separated or not? I assume the best work-flow would be to duplicate the array automatically at the time of the first modification since no other inspector element need that kind of additional action. Also as far as I understand it's impossible for user to tell if the array is already 'independent' from parent scene or not (so it's hard to tell when it should be duplicated).

**Comment by bojidar-bg** [comment]
Well, I tried to think of some simple way, but couldn't. Maybe for 3.1.

**Comment by bojidar-bg** [comment]
After [discussion on IRC](http://godot.eska.me/irc-logs/devel/2018-01-08.log), it was decided that we can make a more proper workaround.

```irc
<reduz> bojidar_bg: we could force duplicating the property in PackedScene when instancing for editing
<reduz> bojidar_bg: and also force duplicating the property on editor duplicate
<reduz> bojidar_bg: i think that may fix the problem
<bojidar_bg> yes, it would fix it as well
[..]
<reduz> bojidar_bg: I suggested adding a deep copy argument to duplicate() in Array and Dictionary, we can call that in Node::duplicate and PackedScene::instance (when used from editor)
```

I will open another PR when I implement it, but it is likely to land post-3.0.

**Pull request closed without merging**
