### PR TITLE
Fix various inconsistencies in shortcut naming

### PR DESCRIPTION
**Pull request by greatmomo**
I made the suggested changes from Issue #49299. I think they were all reasonable changes and well explained.

I don't understand the issue mentioned for the search box though. I think the changed tooltip makes just as much sense as before.

### CODE REVIEW

**Comment by pycbouh** [comment]
Note that while we changed the title here to be more to the point, your commit message also needs to be amended.

**Comment by menip** [comment]
Please squash the commits together as it's required by the pipeline: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

**Comment by greatmomo** [comment]
I clearly don't understand how to squash the commits... I'm having trouble following the guide.

**Comment by aaronfranke** [comment]
@greatmomo See this article: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html

You need to do a rebase. If there are conflicts, resolve in favor of master.

**Comment by EricEzaM** [comment]
`git pull - - rebase upstream master`

Assuming you have the 'upstream' remote pointing to the main godot repository. That should  ensure this issie does not happen.

**Comment by aaronfranke** [comment]
@greatmomo What you just pushed says "Merge branch", which is incorrect. We don't want a merge in a merge, we want a rebase.

**Comment by aaronfranke** [comment]
@greatmomo Good job, the Git history is good now!

**Comment by greatmomo** [comment]
Yep, it was the force-push that I was missing. I think I got it now... Whew!

**Comment by greatmomo** [comment]
Thank you for your help and patience.

**Comment by foxydevloper** [comment]
this pr can be closed, btw, the changes in the attached issue were already made in https://github.com/godotengine/godot/pull/49523

**Pull request closed without merging**
