### PR TITLE
Add Thread `completed` signal

### LINKED ISSUE #9339: Thread finished signal
Instead of having to poll a thread to see if it is finished, it would be very handy to have a signal emited when the thread is finished.

### PR DESCRIPTION
**Pull request by Xrayez**
Closes #9339.

## Usage

```gdscript
var thread = Thread.new()

func _ready():
	thread.connect("completed", self, "_on_thread_completed", [thread])

func _on_thread_pressed():
	thread.start(self, "_image_process", "res://mona.png")

func _on_thread_completed(p_result, p_thread):
	# The thread must still be collected and finalized even if already finished.
	p_thread.wait_to_finish()
	$sprite.texture = p_result
```

The only caveat is that signal emission should happen deferred (see `CONNECT_DEFERRED`), but I noticed that it does return the result within the signal callback even without it, but `wait_to_finish` just hangs the thread in that case (which suggests that perhaps it should finalize it automatically in these cases https://github.com/godotengine/godot/issues/7235#issuecomment-437601392:

> The only way to make it go false is to call wait_to_finish(), but it will potentially hang the application if the function was actually still running.

Note: deferring issue is also fixed with https://github.com/godotengine/godot/pull/34862#issuecomment-571744578.

I intentionally named the signal as `completed` because you still have to "formally" finalize the thread with `wait_to_finish` method (which I think does more than what it says on the tin). As you may have noticed, it resembles `GDScriptFunctionState`'s `completed` signal (aka `yield` stuff).

## Test project
[threads.zip](https://github.com/godotengine/godot/files/4032798/threads.zip)

### CODE REVIEW

**Comment by Xrayez** [comment]
I have updated the PR with some deferring mechanics inspired by the existing codebase:
```cpp
t->call_deferred("emit_signal", "completed", t->ret);
```
as in here for instance:
https://github.com/godotengine/godot/blob/a1ab8f889032fbf779b5bd5a08e6bae9e15aafce/editor/editor_resource_preview.cpp#L453-L455

Doing so allows to use yiedling combined with threads:

```gdscript
thread.start(self, "_image_process", "res://mona.png")
var result = yield(thread, "completed") # returns whatever the thread was supposed to return
$sprite.texture = thread.wait_to_finish() # returns the result too, but also finalizes the thread
```

And the user doesn't have to worry about connecting the signal with `CONNECT_DEFERRED`):
```gdscript
thread.connect("completed", self, "_on_thread_completed") # that's it
```

I'm not sure how well this would actually work with mutexes and stuff, but for simple cases works flawlessly with the demo I linked.

**Comment by Xrayez** [comment]
I've figured another way to deal with having to wait for a thread manually:
```cpp
void _Thread::_on_thread_completed(Variant p_result) {
	List<Connection> conns;
	get_signal_connection_list("completed", &conns);
	
	if(conns.size() > 1) {
		// We can safely join the thread now. 
		// Get the result within another signal callback instead.
		wait_to_finish();
	}
}
```
This allows to join the thread upon function completion automatically if there are more than one signal connection to this (the logic can be used to assume that the user also watches for the thread function to complete via script).

I haven't pushed the changes yet because explicit is better than implicit as they say, but this could avoid situations like this:

```gdscript
func _on_thread_completed(p_result, p_thread):
	# Kinda redundant, only result is needed
	p_thread.wait_to_finish()
	$sprite.texture = p_result
```
vs
```gdscript
func _on_thread_completed(p_result):
	# Magic! `wait_to_finish` is called for us under the hood 
	# (but only when signals are used)
	$sprite.texture = p_result
```

The "number of connections to the signal" logic also works with `yield`->signal statements because it actually connects to said signals internally with `CONNECT_ONESHOT` flag:

https://github.com/godotengine/godot/blob/a7f49ac9a107820a62677ee3fb49d38982a25165/modules/gdscript/gdscript_function.cpp#L1314

So with yielding it would boil down to this one-liner:
```gdscript
$sprite.texture = yield(thread, "completed") # yep
```

**Comment by Xrayez** [comment]
This implementation is confirmed to work as in https://github.com/godotengine/godot/pull/28457#issuecomment-598357814.

**Comment by xsellier** [comment]
I tested it on MacOS (catalina), Windows (10) and Linux

**Comment by reduz** [comment]
This is not possible because signals are not thread safe. They eventually may be but not for the time due to the performance cost. If you want this behavior, just use call_deferred from the thread once it is completed, which does work fine from threads.

**Comment by Xrayez** [comment]
@reduz, I've been using this without issues though. Perhaps the limitations of this feature can be documented? Doesn't emitting the signal *deferred* achieves the thread safeness? (note I'm not suggesting that I know how this actually works under the hood). But in any case this is so much intuitive nonetheless.

**Comment by Xrayez** [comment]
I think it's unlikely to be implemented in Godot, but this particular implementation currently works fine in my project, closing due to lack of response and per reduz concern, I can reopen this PR anytime, though.

This likely needs a proposal first, yet I'm not knowledgeable enough to properly convey the problem I'm having with using threads.

See previous proposal at #9339, if someone wants to create one.

For reference, a similar implementation was proposed at #28457 as well.

This would also help the proposal at godotengine/godot-proposals#769.

**Pull request closed without merging**
