### PR TITLE
Fix AudioStream cubic resampling

### LINKED ISSUE #49131: .OGG files are played back with rolled-off high frequencies (low-pass)
**Godot version:** 

3.3 MONO

**OS/device including version:**

MacOS 10.13.4
Windows 10

**Issue description:**

When playing game audio from `.ogg` files, high frequencies (notably above 10kHz) are attenuated. Upon measuring frequency levels for a single track, I found a 10dB difference around 15kHz between the original (`.ogg`) audio and the game playback (see following graphs). This does not happen when using `.wav` files.

In the following graphs I've zoomed in on the high frequency range, 5kHz-22kHz, as the rest of the spectrum appears rather unaltered.

_DAW audio (OGG) maximum frequency levels (average between left and right channels)_
DAW audio avg 5k-22k

_Game audio loopback (OGG) maximum frequency levels (average between left and right channels)_
Game audio avg 5k-22k

The `.ogg` file used in this example has a sample rate of 44.1kHz.
Tests were executed on MacOS 10.13.4 with Reaper DAW; game audio was routed to the DAW with "Loopback" software from [Rogue Amoeba](https://rogueamoeba.com/loopback/) and analysed using Blue Cat's FreqAnalyst VST.
Audio playback with VLC media player was also recorded through "Loopback" and analysed. While there is a difference between VLC loopback and DAW playback, it is mostly after 18 or 20kHz, this may or may not be caused by the "Loopback" software. Frequency levels between 10kHz and 15kHz remain similar to the original audio.

_VLC audio loopback (OGG) maximum frequency levels (average between left and right channels)_
VLC audio avg 5-22

**Steps to reproduce:**
- Open an empty Godot (mono v3.3) project
- Add an *AudioStreamPlayer* node with an OGG audio file set to autoplay.
- Launch the scene to trigger audio playback
- Hear or measure the HF dip

This issue was confirmed by another *Godot Engine* Discord server user on Windows 10.

### PR DESCRIPTION
**Pull request by ellenhp**
Reverts b2264cb48be48f7bcb16dfba126da8073b6e4c3f and fixes Godot's cubic resampling algorithm. Lots of context for this is in #23544 and #49131.

Fixes #49131.

This is implemented with some help from the math on this page: https://www.paulinternet.nl/?page=bicubic

I'm not really a math person. :)

### CODE REVIEW

**Comment by fire** [comment]
Reviewing with Ellen offline.

**Comment by Zylann** [comment]
Comments here https://github.com/godotengine/godot/issues/23544#issuecomment-890290085

**Comment by ellenhp** [comment]
Summarizing discussion, I think the issue Zylann is running into is related to the WASAPI driver, not `AudioStreamPlaybackResampled` bugs. I'll probably try and come up with a testing matrix and use OBS to record what everything sounds like so people can review without trying every possible test case.

**Comment by ellenhp** [comment]
Okay, I have a demo of this now! Took a while fiddling with OBS but I did it.

The audio files I used are in this zip:

[soundfiles.zip](https://github.com/godotengine/godot/files/6912230/soundfiles.zip)

My system's sample rate is 44100, so keep that in mind here. The other thing is that the github video player seems to start muted so turn on the audio for these :)

----------------------------

This is Godot 3.2.3 with the project mix rate set to 44100. Everything sounds fine, nothing is unusual about it.

https://user-images.githubusercontent.com/1936763/127761566-50a868b7-2b2d-4126-abc0-b3dab0044d46.mp4

This is Godot 3.2.3 with the project mix rate set to 48000. There's a fairly audible ringing artifact on the low frequency beat sound. This is what I fixed with #46086

https://user-images.githubusercontent.com/1936763/127761610-c775a94f-1d3c-4a02-843c-ee64a31e3bbe.mp4

Fast-forward to today, with a build from 23bf04ae9acfa5ec74e960564fe91ffe683ec934 (sample rate 44100). Theoretically there's an audible low-pass effect (#49131) from the new resampling algorithm, but I can't hear it with these audio files.

https://user-images.githubusercontent.com/1936763/127761682-bc6cf3d5-1cfe-4416-a967-a803d2dc8499.mp4

And 48000. Should also have a low-pass.

https://user-images.githubusercontent.com/1936763/127761715-56a7c935-d24c-432f-9f47-71e84b7bc5e0.mp4

So what I did in this PR is reverted to the old cubic algorithm and adjusted the coefficients to match a derivation I found online (linked above). Here's how that sounds at 44100 (theoretically a no-op).

https://user-images.githubusercontent.com/1936763/127761765-b5882c4a-a854-4f6c-85fc-472252406f56.mp4

And here's how it sounds at 48000, which caused issues prior to the coefficient adjustment.

https://user-images.githubusercontent.com/1936763/127761801-08232d3c-5265-4682-b7aa-c3d64ce1a476.mp4

No ringing! At least that I can hear.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
I've tested the changes locally with the files provided in https://github.com/godotengine/godot/pull/51082#issuecomment-890462353, and my bad ears and cheap earplugs didn't let me notice much difference. No regression either though, and since cubic resampling seems to be the better option, it definitely makes sense to go back to it with a fixed implementation.

I suggest we merge this, include it in the 3.4 betas, and we'll see if audiophiles find new issues or can confirm that the old issues have been fixed.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4. (Will be included in upcoming 3.4 beta 3.)

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.

**Pull request merged**
