### PR TITLE
Fix file name comparison when new file is added to file system

### LINKED ISSUE #45027: New scripts and resources are not sorted in the file system browser
**Godot version:**
3.2.3

**OS/device including version:**
* macOS 10.15.7
* Windows 10

**Issue description:**
When adding a new script or resource to a folder using right click in the file system browser, the items aren't sorted until Godot is restarted (or the file system browser is refreshed because of some event)

**Steps to reproduce:**
Add an item "c.tres" using right click. After that, add an item "a.tres". It will be put after "c.tres" instead of before it.

### PR DESCRIPTION
**Pull request by fmazan**
Fixes #45027.

It was caused by improper comparison between full file path vs. file name only.

### CODE REVIEW

**Review by KiritoAM — APPROVED** [review]
Looks good to me!
Note that the associated bug is only present if your file list is sorted by name (FILE_SORT_NAME or FILE_SORT_NAME_REVERSE). This is because FileSystemDock::_sort_file_info_list (which is called when the filesystem changes) does not call the relevant sort_custom variant on the file list for these two sorting types; we assume that the list is already sorted by FILE_SORT_NAME when it enters the function; which it wasn't in this case (with this fix, it now is). Not sure if the same issue is occurring elsewhere due to this assumption.
This does mean that the better fix may be to call sort_custom under these two sorting methods; but personally I'm happy with this fix for this particular issue.

**Comment by fmazan** [comment]
> Looks good to me!
> Note that the associated bug is only present if your file list is sorted by name (FILE_SORT_NAME or FILE_SORT_NAME_REVERSE). This is because FileSystemDock::_sort_file_info_list (which is called when the filesystem changes) does not call the relevant sort_custom variant on the file list for these two sorting types; we assume that the list is already sorted by FILE_SORT_NAME when it enters the function; which it wasn't in this case (with this fix, it now is). Not sure if the same issue is occurring elsewhere due to this assumption.
> This does mean that the better fix may be to call sort_custom under these two sorting methods; but personally I'm happy with this fix for this particular issue.

Indeed, my first local fix was to force sorting in case of FILE_SORT_NAME and FILE_SORT_NAME_REVERSE, but that was curing symptom rather than the cause. I have looked around the code, and it seemed to me that the files vector was purposely kept sorted by name at all times.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
