### PR TITLE
miniupnpc: Sync with upstream master (4436632)

### PR DESCRIPTION
**Pull request by CodeforEvolution**
This is necessary primarily for the Haiku port.

### CODE REVIEW

**Comment by CodeforEvolution** [comment]
Well, this should (hopefully) be all good now. :) Either way, for the rest of the Haiku changes, should I be submitting those changes to the master branch too? I know the master branch breaks the API compared to the 3.2 branch, so I wasn't certain about that.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> Either way, for the rest of the Haiku changes, should I be submitting those changes to the master branch too? I know the master branch breaks the API compared to the 3.2 branch, so I wasn't certain about that.

For the Haiku-specific changes, I guess you can PR for 3.2 first. But ideally you can also make a separate PR for the master branch in parallel with the same changes + fixes to match core changes in the master branch. I guess you might not be able to get it to compile/run on master until there's GLES2 support again, but we could merge nevertheless to ensure that all non-rendering related changes are included in 4.0 too.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Pull request merged**
