### PR TITLE
miniupnpc: Update to version 2.2.3

### PR DESCRIPTION
**Pull request by akien-mga**
Library code and public headers are now properly separated, we can fix include paths
to remove the redundant subfolder.

### CODE REVIEW

**Review by Faless — APPROVED** [review]
LGTM :+1:

**Comment by Faless** [comment]
thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.

**Pull request merged**
