### PR TITLE
Fix Camera2D frame delay (port from 3.x)

### LINKED ISSUE #74203: [Godot 4.0] Camera2D renders the position of the previous frame.
### Godot version

4.0.stable.official (92bee43ad)

### System information

Windows 10, Mobile

### Issue description

[Godot 4.0] Camera2D renders the position of the previous frame.
Therefore, when Camera moves, sub-nodes moved on screen.
It is reproducted on Windows and Android.

### Steps to reproduce

# Setting
image
image
# Test 1
``` GDScript
extends Camera2D

func _process(delta):
	position.x += 500
```
image

# Test 2

``` GDScript
extends Camera2D

var b = true
func _process(delta):
	if b :
		position.x += 500
	b = !b
```
녹화_2023_03_02_11_32_07_920

# Test 3
``` GDScript
extends Camera2D

func _ready():
	position.x += 500
```
image

# Test 4
``` GDScript
extends Camera2D

func _ready():
	position.x += 500
	process_mode = Node.PROCESS_MODE_DISABLED
```
image

### Minimal reproduction project

[camera render position issue reproduction project.zip](https://github.com/godotengine/godot/files/10867070/camera.render.position.issue.reproduction.project.zip)

### LINKED ISSUE #77813: Camera2D moves later than it's parent and its siblings when lerping or tweening its parent
### Godot version

4.0.3 stable

### System information

Win 10, rx580 AMD GPU, Intel i5 CPU.

### Issue description

When I lerp or tween the position of the parent node of a Camera2D, the Camera2D will start and stop moving slightly but noticeably later than its parent and its siblings. This behaviour is the same with compatibility mode or forward+ mode, and it's the same on the Godot 4.1 dev 4 version. This doesn't happen in Godot 3.5.3.

### Steps to reproduce

Add a sprite to have a background. Then a node2D to have a parent. Add a camera2D and a sprite as childs of the node2D. Move the Node2D using lerp or tweens. As the camera and its sibling are being moved at the same time by the parent, you shouldn't see the sibling sprite moving at all, only the background, but because the camera will move slightly later than its sibling sprite, the sprite will move a little bit at the beggining and end of the movement.

### Minimal reproduction project

Using the actions: 
"ui_up" will lerp the parent node up. Camera2D moves later than its sibling and its parent.
"ui_down" will tween the parent node down. Camera2D moves later than its sibling and its parent.
"ui_right" will just change the parent node position. Camera 2D moves at the same time as its sibling and its parent.

[tween parent movement lag.zip](https://github.com/godotengine/godot/files/11643374/tween.parent.movement.lag.zip)

### PR DESCRIPTION
**Pull request by KeyboardDanni**
This is a port of https://github.com/godotengine/godot/pull/46697 to the 4.x branch.

Complements https://github.com/godotengine/godot/pull/84380 by further improving the 2D pixel perfect experience.

Test project (to be used in conjunction with PR 84380): [PixelPerfectTestIdle.zip](https://github.com/godotengine/godot/files/13258040/PixelPerfectTestIdle.zip)

Fixes https://github.com/godotengine/godot/issues/74203 and fixes https://github.com/godotengine/godot/issues/77813.

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
Looks good to me!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by KeyboardDanni** [comment]
Technically not my first contribution, but thank you!

**Comment by akien-mga** [comment]
Oops, [my bad indeed](https://github.com/godotengine/godot/commits?author=KeyboardDanni). Well, welcome back! :D

**Comment by akien-mga** [comment]
I guess it's worth a try? I'll cherry-pick it for 4.2.2 RC 2.

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
