### PR TITLE
Allow dropping custom node scripts in VisualScript editor

### PR DESCRIPTION
**Pull request by Gallilus**
Allows to drop custom node scripts directly in VisualScript.

Current order of operations
* RMB
* search and select custom_node
* select that new custom_node
* drag and drop custom script in custom_node/script

new order of operations
* drag and drop custom script to location

drop_CustomNodes

Its a quality of life improvement simple to backported to 3.x

### CODE REVIEW

**Comment by DavidCambre** [comment]
Sorry for the multiple pushes had some whitespaces.

**Review by fire — APPROVED** [review]
Code looks good.

**Comment by akien-mga** [comment]
Thanks!

For future PRs, please make sure to use a normal English sentence for the commit message title (like "Allow dropping custom node scripts in VisualScript editor" as opposed to a list of keywords ("VisualScript-Drop-Custom-Nodes").

**Comment by DavidCambre** [comment]
> Thanks!
> 
> For future PRs, please make sure to use a normal English sentence for the commit message title (like "Allow dropping custom node scripts in VisualScript editor" as opposed to a list of keywords ("VisualScript-Drop-Custom-Nodes").

Ok Thanks for the feedback and the merge.

**Pull request merged**
