### PR TITLE
Added INITIALIZATION_LEVEL_READY for extension setup.

### PR DESCRIPTION
**Pull request by zombietype**
Adding initialization level after the end of setup and deinitialization
before the start of cleanup so extensions can ensure servers singletons
have finished setting up before any extensions requires them.

### CODE REVIEW

**Comment by timothyqiu** [comment]
Does this resolve #60238?

**Comment by Faless** [comment]
As mentioned in chat, this would re-introduce the bug in exported (non-editor) builds (bug fixed in #58629).
IMO all the init and registration should happen before editor (i.e. editor is supposed to be last, since it's basically a godot project itself).
This means re-organizing the `main.cpp` registration order, e.g. (for modules, probably need more work to move more stuff like the server singletons):

```
diff --git a/main/main.cpp b/main/main.cpp
index f20ec94fa558..3b65d91ccfc3 100644
--- a/main/main.cpp
+++ b/main/main.cpp
@@ -1930,6 +1930,14 @@ Error Main::setup2(Thread::ID p_main_tid_override) {
 
 	register_driver_types();
 
+	MAIN_PRINT("Main: Load Platform APIs");
+
+	register_platform_apis();
+
+	MAIN_PRINT("Main: Load Modules");
+
+	register_module_types();
+
 #ifdef TOOLS_ENABLED
 	ClassDB::set_current_api(ClassDB::API_EDITOR);
 	EditorNode::register_editor_types();
@@ -1937,12 +1945,6 @@ Error Main::setup2(Thread::ID p_main_tid_override) {
 	ClassDB::set_current_api(ClassDB::API_CORE);
 
 #endif
-
-	MAIN_PRINT("Main: Load Modules");
-
-	register_platform_apis();
-	register_module_types();
-
 	// Theme needs modules to be initialized so that sub-resources can be loaded.
 	initialize_theme();
```

**Comment by kidrigger** [comment]
@Faless

**Comment by akien-mga** [comment]
Superseded by #60723.

**Pull request closed without merging**
