### PR TITLE
Add additional plugin path checks (3.2)

### LINKED ISSUE #46383: Issue with config file paths for plugins in Godot 3.2.4.rc3
**Godot version:**
Godot 3.2.4.rc3

**OS/device including version:**
Windows 10

**Issue description:**
I'm developing a plugin and also using one by Will Nations (https://github.com/godot-extended-libraries/godot-plugin-refresher) to refresh the plugin when I make big changes to it. Since 3.2.4.rc3 I'm experiencing some minor issues (can't reproduce at the moment all of them) but Will was able to identify the possible origin of one of them: 

> The problem appears to be (to me) that an attempt was made to simplify the logic related to identifying what a plugin inherently was (shifting away from a dependency on the .cfg file), but in the process they messed up the logic for identifying the existence of the addon. You can see in 3.2-stable, here where they fetch the config file and get its base dir:

> res://addons/godot-plugin-refresher/plugin.cfg -> res://adons/godot-plugin-refresher

> ...but then in the latest 3.2 here, they remove the config file path and use just the addon's subdirectory and try to get its base dir:

> godot-plugin-refresher -> ""

> This then results in the addon never being found in any conceivable case, afaict. If that isn't the issue, then I'm not sure what it is since, of all methods among the 7 mentions of the plugin_addons data structure throughout the EditorNode, that is the only line of code that is any different between the two versions of the engine.

(Issue in the plugin repo: https://github.com/godot-extended-libraries/godot-plugin-refresher/issues/13)

I'm not sure if this is the reason why the error is happening but I can't seem to find a solution.

**Steps to reproduce:**
Open the editor, try to reload the plugin pressing on the refresh arrow
image
You will see the error:
` editor/editor_node.cpp:3241 - Addon 'explore-editor-theme' failed to load. No directory found. Removing from enabled plugins`

**Minimal reproduction project:**
[MinimalPluginError.zip](https://github.com/godotengine/godot/files/6036682/MinimalPluginError.zip)

### PR DESCRIPTION
**Pull request by Shatur**
Need for compatibility after #45316.
Fixes #46383.

### CODE REVIEW

**Comment by pycbouh** [comment]
It works as expected now. Would it make sense to introduce a new method that sanitizes the input so that you don't repeat the checks manually everywhere?

**Comment by Shatur95** [comment]
@pycbouh, agree, done.

**Comment by pycbouh** [comment]
I thought `p_addon.begins_with("res://")` check would be a part of that method as well, so it actually sanitizes the value. Otherwise LGTM.

**Comment by Shatur95** [comment]
> I thought p_addon.begins_with("res://") check would be a part of that method as well, so it actually sanitizes the value.

I thought about it, but it would require making an extra copy of the `String` even if the path is the same. I know about COW in `String`, but this will not zero-cost.
Anyway, let me know if I should change it.

**Comment by coppolaemilio** [comment]
Did a build with the most recent changes and I get no error 👍🏻  
Thanks for the quick turnaround!

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
