### PR TITLE
Improve RID_Owner memory usage

### PR DESCRIPTION
**Pull request by reduz**
* Ability to allocate empty objects in RID_Owner, so RID_PtrOwner is not needed in most cases.
* Improves cache usage, as objects are now allocated together
* Minimum block size in RID_Owner incremented to 64k, so more objects can be packed together by default.
* Should improve performance in 2D rendering

### CODE REVIEW

**Comment by RandomShaper** [comment]
I see no issues. However, I'd like to suggest an optimization:

In many cases you need to make or initialize, and then use `getornull()`.

Wouldn't it be better to have something like this to be able to get the pointer in a single call (which would avoid spin-locking a second time)?:
> `RID make_rid(T** r_element_ptr = nullptr);`
> `void initialize_rid(RID p_rid, T** r_element_ptr = nullptr);`

`initialize_rid()` could simply return the pointer, but, given that `make_rid()` can't, I'm suggesting that API design for consistency.

**Comment by reduz** [comment]
@RandomShaper I thought about it, but given RID creation in itself is not critical (and that getornull will be inlined so the initialize code will be compiled out), I preferred to just leave the code that was already there and keep it simple.

**Comment by RandomShaper** [comment]
I still find it a bit wasteful to spin lock twice, but I may be overworrying. In the end, I see your point: if you are allocating many RIDs, you are probably doing a lot of I/O, so the cost is negligible.

**Review by RandomShaper — APPROVED** [review]

**Comment by akien-mga** [comment]
This seems to add memory leaks (at least from `GdNavigationServer`):
https://github.com/godotengine/godot/pull/50000/checks?check_run_id=2942948680

**Comment by reduz** [comment]
@akien-mga seems I messed up when I tried to fix the amend, I just pushed again lets hope it fixes it now.

**Comment by jordo** [comment]
Hrm, wait I thought SpinLock was removed from usage in godot?  They basically work against any scheduler...    and perform worse in contentious cases.  A modern mutex is just as fast in the uncontensted case, because acquiring the lock when uncontensted is just an atomic check which saves a syscall.

Unless you're targeting dedicated hardware & scheduler like a console, I don't think we should be spinlocking anywhere really?

https://matklad.github.io/2020/01/04/mutexes-are-faster-than-spinlocks.html

https://probablydance.com/2019/12/30/measuring-mutexes-spinlocks-and-how-bad-the-linux-scheduler-really-is/

**Comment by reduz** [comment]
@jordo This is something we have pending to check, the thing is that this was implemented before moving Godot to C++17, where mutexes would need to go via pthreads, which sucks for critical code. I _think_ modern C++ non recursive mutexes are basically a spinlock that eventually gives up and acquires a lock, which is much better than what we have now, but we need to confirm that this is the case in all platforms and compilers before moving to it. No one took the effort to do it yet.

**Comment by akien-mga** [comment]
Thanks!

**Comment by jordo** [comment]
>  I _think_ modern C++ non recursive mutexes are basically a spinlock that eventually gives up and acquires a lock, which is much better than what we have now,

Spinning in user-space is always going to be an issue because when the kernel preempts your thread in that critical section.  If your thread is unlucky there, you're contributing to the problem.  There's no way to work with the kernel here.  

pthread mutex is very fast.  Its free to acquire the lock in user-space uncontested.  Basically a CMPXCHG operation on x86.  If locked, it even spins for a bit.  And then a syscall.    This is the same in libpthread in any platform I've looked at.

>  but we need to confirm that this is the case in all platforms and compilers before moving to it.

https://github.com/lattera/glibc/blob/master/nptl/pthread_mutex_lock.c#L168

**Comment by jordo** [comment]
If you are talking about std::mutex in c++17, I guess you would have to check libstdc++ and libc++ implementations i suppose, but I would be surprised if both don't pthread under the hood.

**Pull request merged**
