### PR TITLE
Added editor theme contrast and tint settings.

### PR DESCRIPTION
**Pull request by thomaslynge**
While the theme contrast functionality is very nice, I would like to be able to apply more contrast especially with light themes. I am not sure if this is desired functionality by others, but it would greatly improve my work with a fantastic game engine.

### CODE REVIEW

**Review by volzhs — APPROVED** [review]
seems fine to me

**Comment by djrm** [comment]
im not sure those are a lot of settings

**Comment by volzhs** [comment]
probably, most of users are just using theme preset only.

**Comment by thomaslynge** [comment]
I too was a bit worried about the number of settings. But the ability to have higher contrast is very important to me. I will remove the editor settings, they can be achieved otherwise by overriding the adaptive setting. I guess I also could remove the font_contrasts. That leaves panel_contrast, background_tint and tab_tint. What do you thing about that?

**Comment by thomaslynge** [comment]
Thinking about it, if I could have negative contrast like -2 to 2, then perhaps all I need is the ability to override the panel color. Leaving us with only one setting. The code change would be a little more complex, but perhaps ok. I will look at it later today.

**Comment by thomaslynge** [comment]
I am now down to one setting. I think it is an okay compromise for what I want to achieve.

Current:
01 panel_color

Settings:
02 panel_color

Result:
03 panel_color

What do you think?

**Comment by djrm** [comment]
one problem that i see is that you cant make the icons look good in both the white background and the darker backgrounds at the same time, and to be hones it looks bad, also keep in mind that the current contrast control is kinda broken, so i think it would be better to fix it to provide more constrast but keeping the overall color scheme (no mixed light and dark) or adding a lighness setting so the panel contents can get lighter but only at a maximum level so it stays dark or light but coherent with the rest of the interface that way icons will still look good in both colors.

**Comment by thomaslynge** [comment]
That are some good points. My main issue is actually the brightness of the tabs and the frames around the content, when having a light theme. And if you lower the base color brightness the panels get to grey with the current font color. If I could make a panel brightness settings, constrained with in the dark or light theme, I might get what I want to achieve. Like:

01 panel lightning

Would that be ok?

**Comment by thomaslynge** [comment]
I have added panel brightness. Initial value is 1 which doesn't change the current look. It is constrained to 0.5 to 1.5, which should work fine with dark and light themes. And I can have a grey theme which doesn't hurt the eyes as much:
01 grey

Default theme, where the panel brightness is raised a bit:
02 dark

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Pull request closed without merging**
