### PR TITLE
Allow to add RESET values from existing keys

### LINKED ISSUE #55634: Reset track not created with animation nodes from 3.3.x
### Godot version

3.4 stable

### System information

windows 10

### Issue description

When using animation nodes created with previous godot versions (3.3.x), the RESET track is not created and there is no way to create it in the editor.

### Steps to reproduce

Open any project from a previous Godot version that has an animation player node and an animation.
The minimal reproduction project was created in 3.3.3 and should be suitable for testing.

### Minimal reproduction project

[2021_12_05_TestAnimationPlayer_3.3.3.zip](https://github.com/godotengine/godot/files/7655176/2021_12_05_TestAnimationPlayer_3.3.3.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
This PR adds a way to quickly create RESET values from existing animation keys. It's useful when importing old animations or when you just want to update the RESET value to match another animation.
zibBZvsvCx

If multiple keys are selected, only the first selected key in a track will get a RESET value:
wrjJSw6IWH

Closes #55634

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by securas** [comment]
Nice! Thanks!

**Comment by akien-mga** [comment]
@KoBeWi I did a backport for `3.x` in my local branch, and it seems to work, but it raises an error when adding a reset track this way:

```
 scene/resources/animation.cpp:881 - Index p_track = 0 is out of bounds (tracks.size() = 0).
```
This is the commit in my fork (didn't push to upstream `3.x` yet): https://github.com/akien-mga/godot/commit/10d200c812abd5c6f95ae9afbabe52eaf4c25607

I didn't check if it's reproducible in `master`.

**Comment by KoBeWi** [comment]
I don't know how I missed this error, I'll make a hotfix >_>

**Comment by akien-mga** [comment]
Cherry-picked for 3.5. (Together with #55671.)

**Pull request merged**
