### PR TITLE
Fix ColorPicker's screen pick functionality

### PR DESCRIPTION
**Pull request by MarianoGnu**

### CODE REVIEW

**Comment by reduz** [comment]
why the hide on WM quit request?

**Comment by MarianoGnu** [comment]
when you try to close the window, the control taking the input is still active and above the confirmation dialog, so when you try to click confitm or cancel it first picks the color, aplies it to the property being edited and then you hace to click again to confirm or cancel.
I dont really need to close the color picker, but it just semmed correct to me, since the black screen of the exclusive dialog doesn't cover it, so it looks like you can still pick colors, semmed wrong to me...

**Comment by reduz** [comment]
oh i see, alright it makes sense

**Comment by MarianoGnu** [comment]
btw reduz, there's still something weird on color picker, when you move the mouse, the controls doesn't update until you stop moving, but i have confirmed that the color being selected is actually updating, just not redrawing them even thought i call update every time MouseMotion event is catched. Any idea why?

**Pull request merged**
