### PR TITLE
Make parent folder selectable

### LINKED ISSUE #16253: Click on ".." folder in Godot editor FileSystem dock does not indicate if the folder is clicked.
**Godot version:**
Stable 3.0

**OS/device including version:**
Linux Mint 18.3 Cinnamon 3.6.7 64-bit
4.13.0-21-generic

**Issue description:**
In the Godot editor, clicking on the ".." folder in a subfolder does not highlight the folder, meaning you cannot tell if you clicked on it. In the second screenshot, the ball icon is clickable, but not the folder next to it:

folder1

folder2

**Steps to reproduce:**

1. From the Godot editor, descend into a subfolder from the filesystem dock.
2. Click on the ".." folder.

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fixes #16253

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you amend the commit log to make it more explicit? Something like:
```
Filesystem dock: Make parent folder selectable

Fixes #16253.
```
would be clearer when reading the git logs :)

**Comment by akien-mga** [comment]
Nevermind, you did it already :D

**Comment by guilhermefelipecgs** [comment]
I just did this when a notice.

**Comment by guilhermefelipecgs** [comment]
:+1:

**Comment by Zylann** [comment]
What happens if you press Delete on that selected folder?

**Comment by guilhermefelipecgs** [comment]
Does nothing, indeed, pressing delete doesn't delete any folder or file in the file system dock (using master branch).
And if you try delete using the context menu you'll see this:
2018-02-01-172655_307x100_scrot

**Pull request merged**
