### PR TITLE
Add Color.lighten and Color.darken (like LESS.css or SASS)

### PR DESCRIPTION
**Pull request by kvanbere**
Now you can do this:

```
self.modulate = self.modulate.darken(delta * 0.5) # 0.1 = 10%
```
or
```
self.modulate = self.modulate.lighten(delta * 0.5)
```

It favors performance over accuracy. Please let me know if anything is missing or wrong .. and how to add docs

### CODE REVIEW

**Comment by donkeybonks** [comment]
Maybe 'darkened' and 'lightened' is better as it does not mutate and could be confusing

**Comment by akien-mga** [comment]
We discussed it a bit on IRC, and we think that it would be best to have:
```
void darken()
Color darkened()
```
Similar to `void Vector3::normalize()` and `Vector3 Vector3::normalized()`.

**Comment by donkeybonks** [comment]
Thanks for discussing it, this is what I thought too. My laptop was recently written off ... I'll be back on this as soon as the new one is setup :(

**Comment by akien-mga** [comment]
Something went wrong :)

See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase for details on how to rebase a branch.

**Comment by donkeybonks** [comment]
crap. Why did this happen when I did a rebase with PR open?

**Pull request closed without merging**
