### PR TITLE
Add sprintf

### PR DESCRIPTION
**Pull request by bil-bas**
This isn't ready to pull yet, but I wanted to show you what I had so far to ensure that I'm not going about it the wrong way, as you told me on my last attempt.

Currently supports very simple printf formats:

```
"%s" % any_variant
"%d %f %o %x %x" % [1, 2, 3, 4, 5]
```

I also need to ask where I should put the docs for this in the repo.

Suggested in #1131

### CODE REVIEW

**Comment by reduz** [comment]
the String class has already methods to convert to float, double, int and
specify decimals.
check mainly the static function String::num().

**Comment by Spooner** [comment]
Wow. I missed that well (and the fact that you don't want to even use stdio - one thing to avoid std::, another to avoid even that :D)  I'll see what I can do to sort that out and do it "properly"...

**Comment by reduz** [comment]
also, if you get it working, adding it to gdscript as operator % should be
pretty easy

**Comment by Spooner** [comment]
@reduz I already have it associated with % in GDScript and that side works great ;)

**Comment by Spooner** [comment]
@reduz Took me a while to get some free time to burn again, but I believe I have implemented sprintf completely. There may still be some edge-case errors left in, but I have tested it thoroughly enough, in _bin/tests/string_test.cpp_, I think.

Think I've implemented error handling correctly, but please double check that is what is expected (use ERROR_EXPLAIN("whatever") and then ERROR_V("") to raise the error and return an empty string).

**Comment by Spooner** [comment]
I would have added documentation, but I have no idea where I should be putting that for it to appear in GDScript help (also wasn't sure which docs were generated and which were the hand-written ones).

**Comment by reduz** [comment]
Sorry for the delay, I'm just back from vacation! this looks fantastic!
I was trying to merge this but it says it can't be merged. do you think you could update it to current head?

**Comment by Spooner** [comment]
I did merge it with the latest, but it must have changed... I'll sort it now.

**Comment by Spooner** [comment]
Ha! The problem was one line difference in the .gitignore. Easy to merge, at least!

**Comment by slapin** [comment]
Why not bind some functions like sprintf, regex, etc. directly?
It is cheap, powerful and fully functional.

**Pull request merged**
