### PR TITLE
[WIP] Scene export to FBX with Assimp

### PR DESCRIPTION
**Pull request by fire**
Export scenes to FBX. 

https://github.com/godotengine/godot/issues/14752

https://github.com/godotengine/godot/issues/19232

### CODE REVIEW

**Comment by fire** [comment]
What is wrong with the Linux builds?

**Comment by qarmin** [comment]
```
modules/assimp/convert_scene_gltf.cpp:189:17: error: declaration of 'j' shadows a previous local [-Werror=shadow=local]
    for (int32_t j = 0; j < vertices.size(); j++) {
                 ^
modules/assimp/convert_scene_gltf.cpp:124:16: note: shadowed declaration is here
   for (int32_t j = 0; j < num_surfaces; j++) {
```

**Comment by fire** [comment]
The problem was the unused includes to assimp. The problem should be resolved now.

**Comment by fire** [comment]
Need to make a plugin that crosses into editor boundary :|

**Comment by fire** [comment]
Converted into a full plugin.

**Comment by fire** [comment]
Resolved the linking error with scene to gltf2 module by making it use the plugin api.

Materials and animations are still unimplemented. 

The scene convert to GLTF is put into the tools menu.

Annotation 2019-04-28 073557


Since there's no API for adding to the convert to menu. It's too much effort to add that if there's only one output format.

**Comment by akien-mga** [comment]
The permissions for `thirdparty/assimp/code/FIReader.cpp` were changed, they should be kept `644`.

**Comment by fire** [comment]
@akien-mga How does one.. fix that on Windows.

**Comment by akien-mga** [comment]
As per https://medium.com/@akash1233/change-file-permissions-when-working-with-git-repos-on-windows-ea22e34d5cee, I guess something like `git update-index --chmod=-x thirdparty/assimp/code/FIReader.cpp`

**Comment by fire** [comment]
Changed.

**Comment by reduz** [comment]
Why are you using Assimp for this? It should be much simpler to just write it yourself, so we can also add our own Godot extensions..

**Comment by fire** [comment]
> Why are you using Assimp for this?

1. The initial concept only took 1.5 days. Total time spent is around a week.
1. The scene export interface code is around 300 lines in the .cpp. https://github.com/godotengine/godot/pull/28459/commits/7b831672c6217fc491478b8b9120a53f7c922771#diff-2ed0cc88f82d31932b2d98268648552b
1. Not sure when we'll have time to work on writing our gltf2 exporter.
1. If GLTF2 is modified, bug fixed or upgraded, Assimp will upgrade. This Assimp GLTF2 exporter simplifies maintenance of the code. We discussed a few months ago the lack of maintainers for the Godot internal import and export code.
1. Assimp has a concept of metadata which allows Godot to put metadata per node. Can you list some concrete Godot extensions? They could be done without modifying the third party Assimp library.

**Comment by fire** [comment]
Reminder to self, merge the changes that preserves the spatial node organization.

**Comment by fire** [comment]
Trialing FBX export. There's a scale problem.

The scene has initial work for copying the graph, but it's not perfect. Anything other than meshes are ignored.

image

**Comment by fire** [comment]
Removed GLTF2 support and current changes in master cause the scene to be scaled 0.01.

**Comment by fire** [comment]
Added a workaround for assimp's lack of exporter scaling. Will remove when implemented in assimp. Scales correct now.

**Comment by fire** [comment]
At this point, I'm closing this pull request because https://github.com/godotengine/godot/pull/33904 is so much better featured.

**Pull request closed without merging**
