### PR TITLE
[WIP] Basic Vulkan support on iOS

### PR DESCRIPTION
**Pull request by samgreen**
Building off the work that @bruvzg did for OSX this brings Vulkan support through MoltenVK on iOS. The current state of this PR cleans up the OpenGL compile errors and begins implementing the context methods required to function. 

I'm trying to avoid any clean up or changes outside of `#if defined()` for safety and ease of PR approval.

### CODE REVIEW

**Comment by bruvzg** [comment]
FYI: I was messing with iOS support a bit, it's not finished and I can't test it, since simulator didn't support Metal (last version should have limited support), but in case some code is useful here it is: https://github.com/bruvzg/godot/commit/85307e61efaf96a07028c094eb52ed0e590ca875.

**Comment by nathanwfranke** [comment]
Make sure to merge these comments if you want it to be merged (I don't actually manage the PRs, just a heads up)

**Comment by samgreen** [comment]
@bruvzg huge help thanks!

@nathanwfranke yep definitely still a WIP

**Comment by akien-mga** [comment]
Superseded by #40434 (CC @naithar in case there are changes from this PR worth porting to the new one).

**Pull request closed without merging**
