### PR TITLE
Update of Russian translation (commit 48a7216)

### PR DESCRIPTION
**Pull request by DmitriySalnikov**

### CODE REVIEW

**Comment by akien-mga** [comment]
Did you also upload this to Weblate?

**Comment by DimOkGamer** [comment]
@akien-mga done.
https://hosted.weblate.org/projects/godot-engine/godot/ru/

**Comment by akien-mga** [comment]
It would be easier in the future if you commit directly to Weblate, and let me do the sync every once in a while for all languages, as committed in both locations leads to complications when I try to update Weblate:
```
Auto-merging tools/translations/ru.po
CONFLICT (content): Merge conflict in tools/translations/ru.po
Automatic merge failed; fix conflicts and then commit the result. (1)
```

**Comment by akien-mga** [comment]
Also please see if you can configure Poedit to output Unix line endings instead of DOS line endings; our git repo enforces Unix line endings, but I don't see how to configure the same for Weblate.

**Pull request merged**
