### PR TITLE
Visually line up the selected tab with the underlying panel with borders

### LINKED ISSUE #48552: Tab doesn't have border in new editor theme when using non default theme border size
**Godot version:**
4.0.dev.custom_build. ee44982c4

CC @Calinou 

Ubuntu 20.04

**Issue description:**
Tabs in new editor theme doesn't have left border
Full size

Zoom

### PR DESCRIPTION
**Pull request by Calinou**
It's not perfect due to the lack of per-border colors in StyleBoxFlat, but it looks good enough at a glance.

This closes https://github.com/godotengine/godot/issues/48552.

**Note:** Not cherry-pickable to the `3.x` branch as this only applies to the new editor theme.

## Preview

*Border Size is set to 2 to make the remaining visual discrepancy more noticeable. With Border Size set to 1, the visual discrepancy is hardly visible.*

image

### CODE REVIEW

**Comment by YeldhamDev** [comment]
I'm quite sure this PR isn't relevant anymore.

**Comment by Calinou** [comment]
> I'm quite sure this PR isn't relevant anymore.

I can still reproduce the original issue as of 4.0.alpha 1839cae8a:

image

**Comment by YeldhamDev** [comment]
Oh yeah, I didn't set the border thick enough before, now I can see it. I wonder if the custom border size feature is worthy.

**Review by akien-mga — APPROVED** [review]
Seems fine to me, could use a rebase.

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected:

image

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
