### PR TITLE
Implement NativeExtension pointer arguments

### PR DESCRIPTION
**Pull request by reduz**
* Allows calling into native extensions directly with a pointer
* Makes it easier to implement some APIs more efficiently
* Appears with a "*" in the documentation for the argument.
* Implementing the pointer handling is entirely up to the implementation, although the extension API provides some hint.
* AudioStream has been implemented as an example, allowing to create NativeExtension based AudioStreams.

Example of how it looks:

```C++
GDVIRTUAL3(_mix, GDNativePtr<AudioFrame>, float, int)
```

### CODE REVIEW

**Comment by CedNaru** [comment]
So if I understand we can now directly send pointers to Godot by casting them to regular int64 by using this new hint.
Will that solve this proposal: https://github.com/godotengine/godot-proposals/issues/3037 ?

When it comes to usability, not sure I really get the AudioStream example. 
So in 3.x, this class could only be used/implemented in a module because it was making use of a pointer to an internal structure AudioFrame. But in 4.0, AudioStream is exposed in the API because of the new virtual bind and the _mix method "sees" an int in place of the AudioFrame pointer?

**Comment by reduz** [comment]
@CedNaru This is not a way to send generic pointers to Godot, it's a way for Godot to send generic pointer to native extensions. It's only meant for implementations using compiled languages to receive low level data required in some situations (like mixing audio, writing network data buffers, etc).

**Comment by reduz** [comment]
I also have no idea if it solves the proposal, the author did not make clear what the intention was with it.

**Comment by CedNaru** [comment]
Hum ok, so this PR won't solve it. 
The intent was to send pointers to third-party library structs/classes to Godot and store them in a variant for future use which is kinda the reverse of this PR.

**Comment by reduz** [comment]
@CedNaru as written in that proposal, you can cast to integer and back, its not very difficult and makes little difference.

**Comment by neikeq** [comment]
Are the `AudioFrame` members meant to be accessed by native extensions? If so how can they do this if they don't have the struct declaration?

**Pull request merged**
