### PR TITLE
Added to Sprite3D Documentation

### PR DESCRIPTION
**Pull request by PrinceDeveloperOf**
Updates the docs to reflect the changes discussed in #45782.  
A re push of #64131 because it was to hard for me to find out how to squash the commits 😅

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by skyace65** [comment]
@PrinceDeveloperOf We've got a guide on the docs for updating PR's so you don't need to squash commits later [here](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#modifying-a-pull-request). But if you do need to squash commits the rebase section after that goes over how to do it.

And congrats on your first merged PR for Godot!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
