### PR TITLE
Auto completion enhanced for extends and class level identifier

### LINKED ISSUE #36431: Autocompletion doesn't work for the class name (after the "extends" keyword)
**Godot version:**
3.2

**OS/device including version:**
Fedora 31

**Issue description:**
The auto-complete doesn't suggest classes after the "extends" keyword. It works fine in any other place (of the same file).

**Steps to reproduce:**
Just create a new script and try to change the class.

**Minimal reproduction project:**
-

### LINKED ISSUE #38258: IntelliSense does not respond
**Godot version:**
Steam 3.2.1
**OS/device including version:**
Windows10 pro 1803
**Issue description:**
IntelliSense does not respond
**Steps to reproduce:**
aaa

onready is not displayed before func _ready().
onready is displayed after func _ready().
No IntelliSense will work in front of func.
I asked a question on the Forum and was told that this is not happening.
I'm Japanese, but a friend of mine who is learning Godot with me has the same symptoms.
Is this a bug?
**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #36431
Fix: #38258
auto complete with native classes and gdscript(`"*.gd"`) classes
extends-auto-complete

Fix: identifier auto complete at class level
class-level-auto-complete

### CODE REVIEW

**Comment by hankedan000** [comment]
@ThakeeNathees I tried this branch out. It looks like it works great on Godot 3.2. The only thing it doesn't seem to do is add autocomplete hints for user-defined class names that are specified with the **class_name** keyword.
Any thoughts on how that might get added in?

**Comment by ThakeeNathees** [comment]
@hankedan000 I might missed the global scripts, It can be done by adding this (named script) after adding native classes and local classes (at : https://github.com/godotengine/godot/pull/36950/files#diff-f43bbdc98090d1bbe445c4dcf8a1193aR2588) (code not tested!)
```c++
	// Named Scripts
	List<StringName> named_scripts;
	ScriptServer::get_global_class_list(&named_scripts);
	for (List<StringName>::Element *E = named_scripts.front(); E; E = E->next()) {
		ScriptCodeCompletionOption option(E->get().operator String(), ScriptCodeCompletionOption::KIND_CLASS);
		options.insert(option.display, option);
	}
```

**Comment by hankedan000** [comment]
@ThakeeNathees I tested your named class fix on 3.2 and it seems to work fine.

I was working on rebasing this branch to master when I realized that it looks like master might already have this functionality in it under CompletionType::COMPLETION_INHERIT_TYPE.
https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.h#L1038

I'm compiling master to verify, but it seems like this issue might resolved already.

**Comment by hankedan000** [comment]
Yep! Looks this works great on master as-is. I think this issue can be closed out.

**Comment by vnen** [comment]
This could potentially be ported to 3.2.x, if @akien-mga agrees.

**Comment by akien-mga** [comment]
> This could potentially be ported to 3.2.x, if @akien-mga agrees.

Yeah if the base branch is changed to `3.2` and you approve the implementation, I'm happy to merge for 3.2.4.

**Comment by ThakeeNathees** [comment]
Suppressed by : https://github.com/godotengine/godot/pull/41318

**Pull request closed without merging**
