### PR TITLE
[3.x] Allow checking for exact matches with Action events.

### PR DESCRIPTION
**Pull request by raulsntos**
Backport of #44355
Backport of #51064

### CODE REVIEW

**Comment by EricEzaM** [comment]
May close https://github.com/godotengine/godot-proposals/issues/2464

**Comment by raulsntos** [comment]
Rebased on top of #50788

**Comment by raulsntos** [comment]
Rebased on top of #50985

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
The class reference needs to be updated (make sure to keep the descriptions).

The `master` branch lacks details about what `exact_match` does in the documentation, this should be added for both branches.

**Comment by akien-mga** [comment]
Could you squash the commits? Otherwise we'd been merging an intermediate commit that actually fails CI.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
