### PR TITLE
H5build Fix

### PR DESCRIPTION
**Pull request by vkbsb**
Fixes the Javascript Exporter to work with the latest Emscripten SDK + Latest Codebase.

1) Removed the Usage of .a and .o files (archive and object files that were used by default) This is done to fix the unresolved symbols errors which cause the export to fail.
2) Added a Hack in rg_etc1.cpp file to handle weird behavior on javascript side which is causing "<" operation to give wrong results.

Wiki for getting H5 export working.
https://github.com/vkbsb/godot/wiki/export_html5

### CODE REVIEW

**Comment by punto-** [comment]
this is awesome. can you fix the formatting tho? we use tabs :) especially
on the python file, we can't have tabs and spaces mixed.

**Comment by vkbsb** [comment]
Isn't it safer to use spaces instead of tabs?... I'll change it.

**Comment by vkbsb** [comment]
drivers/etc1 is an optional module now with default enabled. 
platform/javascript disables etc1 build. 
I've made a bash script for creating export template for html from a debug build.. see if this can be incorporated by others  for creating exports easily.
```
cp -v godot.javascript.debug.html godot.html
cp -v godot.javascript.debug.js godot.js
sed -i -- 's/godot.javascript.debug.js/godot.js/g' godot.html
zip Archive.zip godot.html godot.js godot.javascript.debug.html.mem filesystem.js
```

**Comment by reduz** [comment]
Sorry for the delay, will merge this as soon as I can

**Comment by macramole** [comment]
Hi, is great you managed to make a tutorial for compiling with emscripten. I could compile it too and tried to get any sound out of it but with no luck.

any news with these ? I have been studying the possibility of using OpenAL, also SDL will do the trick but I remember reduz was against SDL for some reason.. do you guys think trying to add OpenAL is a good idea ?

I've found this tests and I'm trying to compile them to see how it goes:
https://github.com/kripken/emscripten/blob/master/tests/openal_playback.cpp 
This one uses Cube2 that uses SDL
https://github.com/kripken/BananaBread

I understand that what needs to be done is to code audio_driver_javascript.cpp similar to audio_driver_pulseaudio or audio_driver_alsa, is this it ?

sorry if you consider these offtopic, maybe this should be in the dev mailing list

**Comment by punto-** [comment]
Yeah, it should probably go on the dev mailing list. An audio_driver_openal
should work, at least as a basic implementation (depends on how fast it is
to mix audio with the generated javascript code). And if nothing else it'll
be another driver for PC, you should be able to test it on the PC builds
during development..

**Pull request merged**
