### PR TITLE
Fix GDExtension classes derived from abstract GDExtension classes always being registered as abstract

### PR DESCRIPTION
**Pull request by rburing**
Fixup to https://github.com/godotengine/godot/pull/66979. In particular, this makes concrete GDExtension nodes derived from abstract GDExtension nodes show up in the Create New Node dialog, and allows such nodes to be saved/loaded in scenes.

Thanks to @aaronfranke for pointing out the issue in https://github.com/godotengine/godot-cpp/pull/883#issuecomment-1280052208.

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
I can confirm that this fixes the issue. Here's what it looks like:

Screen Shot 2022-10-17 at 12 16 37 PM

**Comment by groud** [comment]
We reviewed this PR in the GDextension meeting. We think the idea makes sense, but we should probably clear our mind on how to handle abstract and virtual classes in extension vs core.
In in any case, we prefer not to merge the PR right now, as it is causing unwanted crashes for now.

Related PR: https://github.com/godotengine/godot/pull/65542

**Comment by dsnopek** [comment]
What is the problem we're trying to solve here?

If it's just to allow instantiating a GDExtension class that descends from another GDExtension class that is abstract, I think this PR may go a little too far.

```c++
		while (concrete_parent->creation_func == nullptr && concrete_parent->inherits_ptr != nullptr) {
			concrete_parent = concrete_parent->inherits_ptr;
		}
```

This loop will keep going up the inheritance tree until it finds a parent that can be constructed, which could also go up passed a _native_ Godot class that is abstract. I think we want to stop once we get to the native parent, otherwise the GDExtension instance could use a wrapper that doesn't match its class on the engine side, and lead to unexpected/broken behavior.

I think if that were fixed, I'd personally be happy to approve this PR!

On the other hand, if this PR is trying to solve extending abstract _native_ classes in GDExtension (like `CanvasItem`, as mentioned above), I don't personally think this is the right path. In cases where we want to allow GDExtension to extend an abstract native class, I think we should either add an `*Extension` class (ex `ScriptExtension`) or consider making the class virtual rather than abstract (which is what PR #67510 is about for `CanvasItem`).

**Comment by aaronfranke** [comment]
@dsnopek This is about extensions providing abstract classes, for example, CollisionObject1D in my screenshot.

> This loop will keep going up the inheritance tree until it finds a parent that can be constructed, which could also go up passed a native Godot class that is abstract. I think we want to stop once we get to the native parent, otherwise the GDExtension instance could use a wrapper that doesn't match its class on the engine side, and lead to unexpected/broken behavior.

That likely explains why this PR crashes the engine if you try to inherit CanvasItem (while before it just showed an error).

> On the other hand, if this PR is trying to solve extending abstract native classes in GDExtension (like CanvasItem, as mentioned above)

This is a separate topic, for which I have PR #67510. I just mentioned it because that's another related thing I want to solve, and this PR changes the behavior a bit (crash instead of error). But if we have both this PR and #67510 merged then it will work for all of my use cases.

**Review by dsnopek — APPROVED** [review]
Thanks! This is looking great to me now :-)

**Review by aaronfranke — APPROVED** [review]
Tested and confirmed that both of these things are correct:

1. Abstract GDExtension classes (like CollisionObject1D) are allowed to have non-abstract derived classes:

Screenshot 2023-08-22 at 12 56 45 PM

2. If trying to inherit from an engine abstract, it correctly prints an error, and does not crash:

```
ERROR: Extension class Node1D cannot extend native abstract class CanvasItem
   at: register_extension_class (core/object/class_db.cpp:1671)
```

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
