### PR TITLE
Use plain text instead of icons for video driver toggle

### LINKED ISSUE #21660: weird spacing for displaying gl es version
**Godot version:**

3.1 alpha

**OS/device including version:**

nil

**Issue description:**

default
 The is a line in between gl and es , which I guess is to distinguish the version, IMO, the line is unnecessary, using suitable color is enough, if you insist the use of line, please improve the spacing between the line, I feel bad when looking at it... 

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #21660, supersedes and closes #21724.

The community apparently doesn't like your design choices @reduz :/

### CODE REVIEW

**Comment by capnm** [comment]
Let me emphasize that this is a very small, insignificant, almost invisible graphic flaw :)

image

**Comment by capnm** [comment]
> The community apparently doesn't like your design choices ...

… but we obviously like almost all of Juan's source code design choices (^_^)

**Comment by reduz** [comment]
I can understand not liking icons, but the color coding is important to quickly tell which driver is in use.
I added back the feature using regular fonts and color for each driver:
image

**Comment by capnm** [comment]
While you are on it, you could also add a space between the name and number GLES 2 / GLES 3.

**Comment by reduz** [comment]
> While you are on it, you could also add a space between the name and number GLES 2 / GLES 3.

No can do, this uses the actual driver name in the enum. This is why I made an icon in the first place..

**Comment by capnm** [comment]
> No can do, this uses the actual driver name in the enum. This is why I made an icon in the first place..

Yes, it's probably not worth it to add additional table somewhere. I would only let it fat. That would be sufficient in my opinion so that nobody overlooks it and it does not disturb the overall picture so much.

**Comment by aaronfranke** [comment]
@reduz Any particular reason blue and green were chosen as the colors? Will Vulkan be red?

**Pull request merged**
