### PR TITLE
TextEdit Word Wrap

### LINKED ISSUE #3985: TextEdit: wrap is not implementing
**Issue description** (what happened, and what was expected):

_TextEdit_ has method `set_wrap(bool)` which is a setter for the variable [wrap](https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.h#L207). This variable is never used, so I assume this option was never implemented (or was removed).

This should be either implemented or the method should be removed to avoid confusion (like [this one](http://godotengine.org/qa/838/textedit-set_wrap-doesnt-seem-to-do-anything-thoughts)).

### PR DESCRIPTION
**Pull request by kitbdev**
TextEdit Word Wrap
Adds word wrapping to TextEdit
wrap2

Fixes #3985
lines will overflow to next row if they are longer than the text editor width
words will try to be wrapped after a space, so whole words will be preserved
home key will go to start of wrapped row, then the start of the line after indent, then to start of the line
end key has similar behavior but for the end of the row
also allows having the view be partially down a line

### CODE REVIEW

**Comment by blurymind** [comment]
finally!!
Thank you thank you thank you :+1:

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by akien-mga** [comment]
For the reference, it's a great feature and many users have been waiting for it for a long time, but we need to draw the line somewhere, and such a change now might very well introduce regressions which will require 2-3 weeks to get ironed out, which conflicts with the release plans for 3.0.

Let's merge after 3.0 and backport it to stable once it has been thoroughly tested.

**Comment by ianb96** [comment]
Rebased with a few scrolling fixes and improvements

**Comment by ianb96** [comment]
Note: words only wrap at the end of the TextEdit area, 
max_chars still does not do anything. I could implement a set_max_wrap_width function pretty easily since wrapping uses pixels, but max_chars would be more difficult and I'm not sure that functionality is actually wanted.

**Comment by willnationsdev** [comment]
@ianb96 Oh my word, thank you for handling this. I tried doing it myself a while back, but I started getting lost in how to handle all the proper scrolling and repositioning of stuff. XD

**Comment by Fiona** [comment]
Superlative work. Almost a couple of years ago I proposed a $50 bounty to this, it's yours if you want it? :) Paypal?

**Comment by mhilbrunner** [comment]
Can you update it to fix the conflicts? :)

**Comment by ianb96** [comment]
Rebased to fix conflicts.
The syntax highlighting commit changed some things around, but everything should work now.

**Comment by vnen** [comment]
This looks great. I propose to merge this if it's not breaking folding nor highlighting.

**Pull request merged**
