### PR TITLE
[macOS] Use occlusionState instead of isOnActiveSpace to determine when window is drawable.

### LINKED ISSUE #64708: Game consumes 100% CPU if the window is covered by another OS window (macOS)
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

macOS 12.5.1 (21G83), Apple M1 Max MacBook Pro

### Issue description

Simply covering up the game's window with another OS window causes CPU usage to spike to 100%. You can see this in action in the video:

https://user-images.githubusercontent.com/453721/185812416-203ed323-0884-4a5b-950d-c93d099716c9.mov

### Steps to reproduce

Run the attached project (or any project, really - the attached one is essentially empty and has no scripts) on macOS. Drag a window over top of the game's window (it needs to cover it completely). Watch as CPU usage skyrockets.

My uninformed suspicion is that macOS detects when the window is covered and stops sending rendering/v-sync events to the app in an effort to save power. Godot may be waiting for those events in an inefficient polling loop and when they stop coming that loop starts burning up cycles.

Godot now has the distinction of being the first app on my M1 Max that's actually managed to get the fan to run because of this. I noticed it because I have a habit of leaving the game open behind other windows when I switch back to the editor to keep working on it. I don't think this is an uncommon habit, tbh, and this behavior would have caused Godot to very rapidly deplete my laptop's battery if I hadn't happened to be running while plugged in.

### Minimal reproduction project

[Godot 100% CPU Bug.zip](https://github.com/godotengine/godot/files/9389996/Godot.100.CPU.Bug.zip)

### LINKED ISSUE #82769: Godot leaking massive memory just by itself
### Godot version

4.1.1 stable

### System information

macOS Montery 12.5.1, 16GB RAM, Forward+ Renderer

### Issue description

When running a project from godot (pressing the play button), the new window will just keep leaking memory, regardless of project size.

The Tests:
I set up a new project, added a scene and tested the following:
- Just a single Node as the scene root, nothing else
- Just a single Node2D as the scene root, nothing else
- Node as Scene Root, then 20 Node2Ds as children
- Node as scene root, then 20 Node2Ds with processing disabled as children
- Finally another run with just a node, to see if it would yield different results as the first run with a single node (it did)

While running the tests I didn't do anything else, just kept the Godot window open in the background.

The Results:
data

I tested every configuration for at least 2 hours, some longer (except for the last one, ran out of time)

As you can see even just an empty scene in an empty project will keep growing in memory usage, my guess is indefinetly. Notably the last test (with an empty scene, containing just an empty Node) grew the fastest. Likewise the tests with 20 Node2Ds yielded similar resuts, regardless of processing being turned on or of. **This leads me to believe that godot itself is leaking memory, not the nodes.**

I will also attach all screenshots I took during those tests, showing my activity monitor (which is apples task manager). You can see how the memory usage changed over time. I tried to take a screenshot about every 30 minutes.

Single Node:

node-01
node-02
node-03
node-04
node-05
node-06

Single Node2D:

node2d-1
node2d-2
node2d-3
node2d-4
node2d-5
node2d-6
node2d-07
node2d-08
node2d-09
node2d-10

20 Node2Ds:

20node2ds-01
20node2ds-02
20node2ds-03
20node2ds-04
20node2ds-05

20 Node2Ds with processing turned off:

20node2ds-no-processing-01
20node2ds-no-processing-02
20node2ds-no-processing-03
20node2ds-no-processing-04
20node2ds-no-processing-05

Single Node (again after all other tests)

single-node-finale-01
single-node-finale-02
single-node-finale-03
single-node-finale-04

### Steps to reproduce

Create an empty project. Create an empty scene. Run that project. Observe memory usage growing.

### Minimal reproduction project

[empty-game.zip](https://github.com/godotengine/godot/files/12800252/empty-game.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/82769

Might fix this one as well, but I can't reproduce the issue - https://github.com/godotengine/godot/issues/64708
*Bugsquad edit:* Closes #64708

### CODE REVIEW

**Comment by akien-mga** [comment]
Is the empty entitlements file meant to be there?

**Comment by bruvzg** [comment]
> Is the empty entitlements file meant to be there?

No, removed.

**Comment by bitsawer** [comment]
This could possibly also fix https://github.com/godotengine/godot/issues/81953. The SurfaceTool and mesh creation code might in theory be a red herring and the demo could leak even without it, caused by the issues this PR is fixing. I don't have a Mac, so I can't test it. I couldn't repro the leak on Windows 10.

**Comment by bruvzg** [comment]
> This could possibly also fix https://github.com/godotengine/godot/issues/81953.

This seems to be unrelated:
```
_objc_rootAllocWithZone	
-[AGXG13GFamilyCommandQueue commandBufferWithDescriptor:]	
MVKQueue::getMTLCommandBuffer(MVKCommandUse, bool)	
MVKQueue::waitIdle(MVKCommandUse)	
MVKDevice::waitIdle()	
vkDeviceWaitIdle	
VulkanContext::flush(bool, bool)	
RenderingDeviceVulkan::_flush(bool)	
RenderingDeviceVulkan::buffer_get_data(RID, unsigned int, unsigned int)	
RendererRD::MeshStorage::mesh_get_surface(RID, int) const	
RenderingServer::mesh_surface_get_arrays(RID, int) const	
SurfaceTool::_create_list(Ref<Mesh> const&, int, LocalVector<SurfaceTool::Vertex, unsigned int, false, false>*, LocalVector<int, unsigned int, false, false>*, unsigned long long&)	
SurfaceTool::append_from(Ref<Mesh> const&, int, Transform3D const&)	
void call_with_variant_args_helper<__UnexistingClass, Ref<Mesh> const&, int, Transform3D const&, 0ul, 1ul, 2ul>(__UnexistingClass*, void (__UnexistingClass::*)(Ref<Mesh> const&, int, Transform3D const&), Variant const**, Callable::CallError&, IndexSequence<0ul, 1ul, 2ul>)	
void call_with_variant_args_dv<__UnexistingClass, Ref<Mesh> const&, int, Transform3D const&>(__UnexistingClass*, void (__UnexistingClass::*)(Ref<Mesh> const&, int, Transform3D const&), Variant const**, int, Callable::CallError&, Vector<Variant> const&)	
MethodBindT<Ref<Mesh> const&, int, Transform3D const&>::call(Object*, Variant const**, int, Callable::CallError&) const	
Object::callp(StringName const&, Variant const**, int, Callable::CallError&)	
Variant::callp(StringName const&, Variant const**, int, Variant&, Callable::CallError&)	
GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*)	
GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&)	
bool Node::_gdvirtual__process_call<false>(double)	
Node::_notification(int)	
Node::_notificationv(int, bool)	
Object::notification(int, bool)	
SceneTree::_process_group(SceneTree::ProcessGroup*, bool)	
SceneTree::_process(bool)	
SceneTree::process(double)	
Main::iteration()	
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
