### PR TITLE
[WIP] Etcpak integration.

### PR DESCRIPTION
**Pull request by fire**
Key feature is performance.

Please try running with the https://godotengine.org/asset-library/asset/123 and try adding etc1 and etc2 export. Use -v on the editor for timing information.

I don't have a setup for phone so, I appreciate phone testing.

The module etc2comp is disabled in this branch.

### CODE REVIEW

**Comment by fire** [comment]
I'll leave the errors with osx and server for another day.

Have a good weekend.

**Comment by fire** [comment]
There was a question regarding how is etcpak's quality vs etc2comp. I'll try to get a few samples using a lossless source at some point. Currently busy. If anyone wants to try making comparisons, that'll work too.

**Comment by RevoluPowered** [comment]
@fire any ideas when you will be ready to merge this?

**Comment by fire** [comment]
I am back from GDC SF.

Can you do some mobile testing and tell me how it goes.

**Comment by RevoluPowered** [comment]
Unfortunately luck has stranded me with a windows phone / my one plus 3t died last week otherwise I would

**Comment by fire** [comment]
Are you able to test anytime soon, I'd have to buy a phone or a hardware proxy.

**Comment by RevoluPowered** [comment]
I'm in the same boat right now, I'll see what I can do; can't promise to be able to find a modern phone though. 

Any chance you could give me an APK to test? Maybe even just pack a single scene with a few different images then I can send to various people to test it out.

**Comment by RevoluPowered** [comment]
I've got a macbook / can test in the simulators to see what happens too, will also verify android studio simulator works, but will need to test on a real iPhone X & android 8.0, and 7.0.

**Comment by fire** [comment]
Use the material tester.

**Comment by fire** [comment]
https://godotengine.org/asset-library/asset/123

**Comment by fire** [comment]
@akien-mga How does Godot do third party licenses? Is there a guide to doing the documentation?

**Comment by RevoluPowered** [comment]
@fire got a new android 8.0 phone will try and test it this week. Will let you know how it goes.

**Comment by reduz** [comment]
If this supports etc1/2 decompression, we should also add support for it.

**Comment by fire** [comment]
It has a decode mode, so I should be able to get the raw data and convert it to a Godot Image instead of to a png.

**Comment by reduz** [comment]
Can you add decode mode, then?

**Comment by fire** [comment]
Looking into it.

**Comment by fire** [comment]
Still remember about this.

**Comment by RevoluPowered** [comment]
@fire mind sending me an apk, don't have much free time atm

If you don't have it configured I can try to find time on Sunday.

**Comment by fire** [comment]
I looked into KTX and PVR support.

@reduz Only the RGBA and RGB formats in ETCPAK are supported, which causes https://github.com/Ericsson/ETCPACK 's test images to crash the editor.

So I kept the existing PVR support by copying the code.

**Comment by fire** [comment]
If a full KTX (maybe KTX2) / PVR importer is required, that's a separate endeavour. We'll have to start looking for a full format to bitmap / png converter.

**Comment by fire** [comment]
With the existing PVR testure importer I could open none of the test vectors at https://github.com/Ericsson/ETCPACK/tree/master/testing/testvectors_correct/pkm.

**Comment by fire** [comment]
@RevoluPowered I don't use Android devices, so I'm not sure of the workflow. It's probably best if you had the whole toolchain. I can wait.

I can test on the iPhone, but the exact formats is different.

**Comment by RevoluPowered** [comment]
Will try and do this on Saturday then since you don't have the toolchain

**Comment by RevoluPowered** [comment]
Built engine with scons, but having an issue. 

**Where do I get the latest export templates from?**

image

Everything else is configured.

**Comment by fire** [comment]
There's a tutorial on generating them.

**Comment by Calinou** [comment]
@RevoluPowered @fire is referring to [Compiling for Android](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html) :)

**Comment by RevoluPowered** [comment]
Appreciate the link thank you. 

I did google but that article didn't show up in google, not sure why it's not indexed.

**Comment by RevoluPowered** [comment]
Letting you know I'm working on this tonight and tomorrow, but it's taking an age to finish compiling the export templates for android.

**Comment by RevoluPowered** [comment]
Checked it on android and textures 3-10 are broken in the material demo on android. Will post screenshots when I get my phone to run again

**Comment by fire** [comment]
I'll try on an Apple device.

**Comment by fire** [comment]
I can reproduce the problem, but debugging on the Apple device is easy to use, but difficult to setup.

**Comment by RevoluPowered** [comment]
Screenshot_20190505-003830
Screenshot_20190503-115032

**Comment by fire** [comment]
This patch is not quite ready, there's some patches to the third party library because of defines and the inability to get the points of the etc2 buffer.

The debug templates take an exceptional amount of time to link on Windows..

Trying to check if this push fixes the problem.

**Comment by fire** [comment]
Nope it's not working, but there's a workflow to test it via the Android Studio Eemulator.

**Comment by fire** [comment]
Going to leave this unfinished, since I ran out of time.

**Comment by RevoluPowered** [comment]
I'll be free this weekend to help you out with testing this if you are able to? @fire

**Comment by fire** [comment]
Leaving this here as the pull request is salvageable, but I'm not working on it anymore.

**Pull request closed without merging**
