### PR TITLE
Adjust BoneAttachment3D children/meshes during rest fixer

### LINKED ISSUE #76891: BoneMap retarget causes incorrect non-skinned mesh rotation.
### Godot version

4.1.dev 6980b2bf1

### System information

Windows 10

### Issue description

rest fixer does not handle rotation of child bones/meshes of rotated human bones during the retargeting process.

It also prints out this error for every non-skinned mesh:
```
ERROR: Condition "!skin.is_valid()" is true. Continuing.
   at: PostImportPluginSkeletonRestFixer::internal_process (editor\import\post_import_plugin_skeleton_rest_fixer.cpp:117)
```
comparison of FBX, rotated bonemap, original, differently rotated bonemap
From left to right: 1. FBX2glTF conversion; 2. BoneMap applied with different rest rotation. 3. original model with no BoneMap; 4. BoneMap applied with the original rest rotation.

Expected output is the third model in the screenshot at origin. The effect on the child meshes seems to be the same regardless of the original rest pose. It seems scale is somehow also reset to 1,1,1. you can see the leftmost model was an FBX conversion with 100x scale. This causes the child meshes to become 1% as large as they should be (basically invisible)

### Steps to reproduce

1. open the scene.
2. errata: I lost the .import for `_rotated_fbx2gltf.gltf` when zipping the project. To reproduce this model, double click to the advanced importer. Assign a BoneMap. Then open the bonemap and assign a SkeletonProfileHumanoid.
3. Observe the import setting of each gltf file. Normally, there are rings around the neck, arms and tail. After BoneMap is applied, the meshes are positioned and rotated incorrectly.

### Minimal reproduction project

[BoneMap_non_skinned.zip](https://github.com/godotengine/godot/files/11437148/BoneMap_non_skinned.zip)
(Model is permissively licensed and available from https://booth.pm/ja/items/2019040 "2A-7-4 / XXXX Coolk")

### PR DESCRIPTION
**Pull request by lyuma**
Adjust MeshInstance3D nodes to be scaled and rotated properly, when within a skeleton which is not skinned.

The approach I used was to rotate the children of BoneAttachment3D (in other words, any camera, light, mesh, etc. attached to a Skeleton3D). I felt this is safe, and may even suffice for a 4.0.x release in terms of low risk of compatibility breakage.

My reasoning for saying compat breakage is minimal is: currently all children of BoneAttachment3D on a skeleton are meshes, cameras or lights attached to a bone of the same name (whether or not this is good is debatable, but it is how it is). As such, all of these nodes are guaranteed to have identity transform, and are guaranteed not to animate their transform at least at import time.
So it seems like a good place to slip in a rotation/scale correction in a place that a reasonable user probably won't need to notice.

One other approach would have been to rotate all bones back which are not part of the SkeletonProfile. There are two reasons I did not take this approach:
1. This could have severely broken compatibility, since scenes may already be created in which users attach objects to bones other than the human ones... or perhaps used 'make local' on some objects.
2. While I wasn't personally able to reproduce this from Blender, it's possible that a human bone is also a non-skinned mesh. Maya or Unity may be able to export glTF with this property, so it would be best to avoid a solution which would break under some situations.

Fixes #76891
Screenshot showing fix, with mesh LOD disabled. note that the feet facing up is caused by how "Fix Silhouette" works and a mistake in the example armature, not a bug.
picture showing all meshes are correct

### CODE REVIEW

**Comment by TokageItLab** [comment]
I remember the main purpose of the node transform process was to solve the problem of sharing of position animations. We need to test whether root motion and position animation sharing works properly.

**Comment by fire** [comment]
@TokageItLab @lyuma Can you suggest a test plan for how to test the problem of sharing animation?

**Comment by lyuma** [comment]
This change should not change how animations of retargeted models are processed. The transform offset is applied to the child of the BoneAttachment3D, which is a node created by Godot, not in the original glTF file and can not be targeted by glTF animations.

@TokageItLab Would it be possible to explain more?

**Comment by TokageItLab** [comment]
For example, if the Scale as Node of the model is 0.01 it should be converted to apparent animation. I also remember that for cases where the Position does not exist at the origin, the model is considered to be placed in the scene, so the Position is not taken into account.

The way to test if Apply Node Transform is working correctly is to first create an animation of Model A moving forward 1m from the origin in the +Z direction.

Also, create Model A', which is a copy of Model A, and set the Scale of the parent Node to 0.5 and shift the X position by 1m. (The model should now appear to have an animation that moves forward 0.5 m in the +Z direction.)

Then test to see if they share animation with each other correctly with Apply Node Transform option.

**Review by TokageItLab — APPROVED** [review]
I confirmed that it is working correctly.

image
image

[posret.zip](https://github.com/godotengine/godot/files/11562556/posret.zip)

I noticed a problem with Apply Node Transform discarding the position (probably I implemented that in the past), but this is not related to this PR and could be sent as another improvement.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Pull request merged**
