### PR TITLE
Make cmd-R an alternative to F5 (editor/play)

### PR DESCRIPTION
**Pull request by ghost**
Probably this is just me, but I would love having Cmd-R as a "Play" shortcut (in addition to F5).

### CODE REVIEW

**Comment by reduz** [comment]
You can already redefine the F5 shortcut as ctrl-R in the editor settings..

**Comment by anissen** [comment]
I too would like to have sensible defaults as alternatives to the F-key shortcuts. On Macs, especially the new MacBook Pros, and on Apple external keyboards the F-keys are very inconvenient to use. Almost all macOS apps use combinations of Cmd/Alt/Ctrl/Shift and keys instead of the F-keys.

**Comment by icnikerazah** [comment]
additionaly, there is no del key on macbooks. i use fn + backspace for delete a node. i can assign a key but default key must be keyboard spesific.

**Comment by poke1024** [comment]
@anissen Exactly, I'm also on a MacBook Pro and I wouldn't even know how to access function keys. The out-of-box experience of recognizing that the keyboard shortcut for "run" is not on your keyboard is not exactly great :-)

**Comment by vnen** [comment]
The problem with this PR is that the shortcut is hardcoded. You can change the F5 to something else in-editor, but Cmd+R is fixed.

Maybe we can have a different set of defaults for each platform, though that would make porting tutorials more difficult.

**Comment by eon-s** [comment]
Maybe a set of different key bindings/editor settings that can be selected from the project manager like the language selector (including emulated 3 button mouse and other common hardware specific options).

**Comment by reduz** [comment]
The issue with mac defaults being more sensible should be a separate issue.
This could be effectively fixed with an ifdef

**Comment by poke1024** [comment]
OK, I'm closing this specific PR in favor of a new one (to come) focusing on a general solution for alternative Mac shortcuts.

**Pull request closed without merging**
