### PR TITLE
Define uninitialized values for send in subviewport container.

### PR DESCRIPTION
**Pull request by fire**
I was getting compiler errors about the send not being initialized.

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't think that's the right fix. The compiler warning here actually points at a bug IMO: `send` is never written to.

The virtual method is defined as:
```
GDVIRTUAL1RC(bool, _propagate_input_event, Ref<InputEvent>);
```
So there's no `send` boolean argument, this was likely an earlier API design that @Sauermann forgot to change after refactoring.

So the solution is to remove `send`.

**Comment by AThousandShips** [comment]
The last argument to the call method is the return argument, so this is correct

**Comment by Sauermann** [comment]
`send` shouldn't be removed, because setting that variable is the intention of the virtual call.
On which compiler do you experience the problem? It hasn't yet caused any problems within the usual Github checks.

**Comment by KoBeWi** [comment]
This is a common pattern if the variable is used only after virtual call and is used in other places. E.g.
https://github.com/godotengine/godot/blob/e001bc75e8b9395186579e49620764fd05a2f97a/core/math/a_star.cpp#L395-L398
It's odd that you'd get a warning only in one case.

**Comment by fire** [comment]
Close because I can't recreate the bug.

**Pull request closed without merging**
