### PR TITLE
Bug #2241 : atan2() function and Vector2 method inconsistent x,y / y,x parameters fix

### PR DESCRIPTION
**Pull request by StraToN**
- fixed Vector2.atan2()
- fixed atan2(x,y) -> atan2(y,x)
  WARNING : this fix may provoke many atan2(x,y) uses elsewhere to work badly

### CODE REVIEW

**Comment by slapin** [comment]
Could you please explain more on benefits of your patch? Just curiois.

**Comment by StraToN** [comment]
This patch fixes the bug related in #2241. I can't tell you more about any 'benefit', except if one is interested in keeping misfunctioning atan2 methods in Godot :-)

**Comment by slapin** [comment]
Ah, now I understand, thanks!

**Comment by StraToN** [comment]
I join a simple project to test this bug.
https://dl.dropboxusercontent.com/u/24823778/2241_atan2-bug.zip

**Comment by StraToN** [comment]
This commit breaks get_angle_to() method. Please wait until I figured it out.

**Comment by StraToN** [comment]
Figured it out and fixed in d05f293.
However, the fix in get_angle_to() seems ugly to me as 
```cpp
(get_global_transform().affine_reverse().xform(p_pos)) 
```
should directly return the good vector2. Here I had to use a temporary Vector2 to reverse its components... 
Maybe some smarter (thus cuter) solution exists ?

**Comment by StraToN** [comment]
Also,  in Isometric2d + Lighting demo project, cubio.gd:65 line needs to be modified from :
```python
var angle = atan2(abs(speed.x), speed.y)	
```
to :
```python
var angle = atan2(speed.y, abs(speed.x))	
```

Note : the syntax of atan2() function is now atan2(y, x), respectfully to the standard Math function. Documentation needs to be corrected.

**Comment by akien-mga** [comment]
Nice catch. I confirm that without this PR, Vector2.angle_to(Vector2) is bugged, as this example from my game shows:
```
   print("mot ", motion)
   print("dir ", bomb.slide_dir)
   print("angle ", motion.angle_to(bomb.slide_dir))
```
Example output:
```
mot -2.666667,0
dir 0,0
angle 0
```

**Comment by akien-mga** [comment]
I built the current PR, and it does not seem to work right, see this code snippet:
```
	var xplus = Vector2(1,0)
	var xminus = Vector2(-1,0)
	var yplus = Vector2(0,1)
	var yminus = Vector2(0,1)
	var xyplus = Vector2(1,1)
	print(xplus.angle_to(xminus)) # pi
	print(yplus.angle_to(yminus)) # pi
	print(xplus.angle_to(yminus)) # pi/2
	print(xplus.angle_to(xyplus)) # -pi/4 or 7pi/4
	print(xplus.angle_to(xplus))  # 0
```
It gives:
```
-1.570796
1.570796
3.141593
2.356194
1.570796
```
There seems to be some pi/2 offset, unless I'm wrong with my math :)

**Comment by akien-mga** [comment]
It also seems to break games such as e.g. the recent https://github.com/Calinou/libre-pinball (with the PR, the paddles don't work properly anymore)

**Comment by StraToN** [comment]
@akien-mga Thanks for reviewing. I corrected the problem (commit fc93ddf)

**Comment by akien-mga** [comment]
I'll try it asap.

**Comment by akien-mga** [comment]
My test script from above now gives the following, which seems good:
```
-3.141593
0
-1.570796
-0.785398
0
```
I'm still getting a weird behaviour with https://github.com/Calinou/libre-pinball (feel free to test it too to see if it might be related to your PR), but it could be because your branch is not in sync with the current git master. I'll see how it behaves if I apply your PR on top of HEAD.

**Comment by StraToN** [comment]
I too have weird behaviours on collisions between KinematicBodies2D.
I don't think it is related to this branch not being sync (I created a second branch on my repo which is in sync, but the bug is present).
This seems to be related in the collisions resolution that probably uses the wrong version of atan() or angle_to() or even get_angle_to(). I'll check this now.

**Comment by StraToN** [comment]
@akien-mga Ok, I think I corrected the problem for good. Feel free to test again.
However, I feel this fix may also impact other applications, still I tested multiple Godot demos projects and I did't remark any new problem... We'll have to wait for reduz to comment here.

**Comment by akien-mga** [comment]
I've tested this PR again, and it seems to work just fine. I checked the demos in 040c117 and I confirm that they work properly too.

@StraToN To be sure the change introduces no regression, I'd advise you to check all references to "atan2" in the code base. See e.g.:
```
$ ack -l atan2
bin/godot.javascript.opt.js
scene/3d/character_camera.cpp
scene/resources/shader_graph.cpp
scene/2d/node_2d.cpp
scene/2d/path_2d.cpp
scene/2d/ray_cast_2d.cpp
tmp/godot.js
tools/editor/spatial_editor_gizmos.cpp
tools/editor/plugins/editor_preview_plugins.cpp
tools/editor/plugins/canvas_item_editor_plugin.cpp
tools/editor/plugins/baked_light_baker.cpp
tools/editor/plugins/spatial_editor_plugin.cpp
tools/editor/io_plugins/editor_scene_import_plugin.cpp
drivers/mpc/mpcmath.h
drivers/squish/maths.cpp
drivers/gles2/shader_compiler_gles2.cpp
core/variant_call.cpp
core/math/math_funcs.cpp
core/math/matrix3.cpp
core/math/math_2d.h
core/math/math_funcs.h
core/math/geometry.h
core/math/quat.cpp
core/math/math_2d.cpp
a.out.js
servers/physics_2d/body_2d_sw.cpp
servers/visual/shader_language.cpp
servers/physics/joints/generic_6dof_joint_sw.cpp
servers/physics/joints/slider_joint_sw.cpp
servers/physics/joints/hinge_joint_sw.cpp
servers/physics/joints/cone_twist_joint_sw.cpp
modules/gdscript/gd_functions.cpp
demos/3d/platformer/player.gd
demos/2d/isometric_light/cubio.gd
doc/core_classes.xml
doc/squirrel.lyx
doc/base/classes.xml
doc/html/@GDScript.html
doc/html/tutorial01/tutorial.html
```

**Comment by StraToN** [comment]
@akien-mga Very nice.
I already previously checked for other references to atan2, however a certain number do not correspond to the same atan2 definition that was fixed here. Example : drivers/mpc/mpc_types.h

In many other cases, Math::atan2 is directly called, not its override that was fixed here (assuming that Math::atan2 is already correct, of course, I just hope it is, haha)

**Comment by akien-mga** [comment]
> I already previously checked for other references to atan2, however a certain number do not correspond to the same atan2 definition that was fixed here. Example : drivers/mpc/mpc_types.h

Indeed, I just gave the full list quickly because I did not have the time to check it myself, but I expect many of them to indeed refer ton non-Godot implemented atan2.

**Comment by reduz** [comment]
I think Vector2::atant2() needs to be fixed. However, regular atan2() function should be left as is, just swap the argument names.. this way code written other libraries can be ported adequately without unexpected consequences.

**Comment by akien-mga** [comment]
> I think Vector2::atant2() needs to be fixed.

Indeed, that would remove the need for the hack in 31eb2d4.

**Comment by okamstudio** [comment]
angle_to and other functions do not need to be modified IMO.  Even though
atan2() arguments are y,x, it's really up to you to interpret where a
rotation begins from.  In fact, I believe the correct fix would be
something like:

1) Just leave Math::atan2() as is, simply swap the argument names in the
description.
2) Vector2::atan2() should be refactored to Vector2::angle() and replaced
in code and demos
3)  Vector2::atan2() should be then added again (maybe after a month, so we
make sure people making projects will fix them)  with swapped axis passed
as parameters

what do you think?


On Wed, Sep 23, 2015 at 12:08 PM, Juan Linietsky <notifications@github.com>
wrote:

> I think Vector2::atant2() needs to be fixed. However, regular atan2()
> function should be left as is, just swap the argument names.. this way code
> written other libraries can be ported adequately without unexpected
> consequences.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2260#issuecomment-142633307>.
>



-- 

*OkamStudio*

**Comment by StraToN** [comment]
I am confused. You advise at first not fixing anything about the bug, but rename Vector2.atan2() to Vector2.angle() ? So Vector2.angle() will still return a wrong value, right ?
And after 1 month, re-add fixed Vector2.atan2() ? What will Vector2.angle() become then ?

Just another remark : when correcting core/math/math_2d.cpp:34
```cpp
real_t Vector2::atan2() const {
	return Math::atan2(x,y);
}
```
to
```cpp
real_t Vector2::atan2() const {
	return Math::atan2(y,x);
}
```
Vector2.look_at() and Vector2.get_angle_to() return false values, breaking many demos such as the Look At Pointer demo and the Kinematic Collision demo. Read commit messages, this was explained.

**Comment by reduz** [comment]
The value is not "wrong". I just prefer rotations start in the y axis
because it's more straightforward to visualize. What is wrong is just atan2
returning a nonstandard value

**Comment by okamstudio** [comment]
ok, clarifying because you asked on IRC then left :)

using the function as atan2(x,y): Angle zero is in Y-up and goes clockwise
using the function as atan2(y,x): Angle zero is in X-right and goes
counterclockwise

Using atan(x,y) is way easier to visualize because it just goes like a
clock, so all code in Godot assumes it this way, including the function to
get the angle. If you check, all rotations in Godot are standardized as
clockwise, so Vector2::atan2() also returns a clockwise value. The problem
is that, as noted, the function is passing x to y and y to x, and this
shouldn't be expected. So, the proposed solution is to simply use an
angle() or get_rotation() function that passes the swapped axes, and leave
atan2 (which isn't really used anywhere as an atan2() function in Godot and
demos, but just as a means to get rotation) out for a while so everyone
that is using it can change the code and fix it. Otherwise just swapping
the axes will make a lot of code instantly not work without reason.




On Thu, Sep 24, 2015 at 12:01 AM, Juan Linietsky <notifications@github.com>
wrote:

> The value is not "wrong". I just prefer rotations start in the y axis
> because it's more straightforward to visualize. What is wrong is just atan2
> returning a nonstandard value
> On Sep 23, 2015 9:27 PM, "Julian Murgia" <notifications@github.com> wrote:
>
> > I am confused. You advise at first not fixing anything about the bug, but
> > rename Vector2.atan2() to Vector2.angle() ? So Vector2.angle() will still
> > return a wrong value, right ?
> > And after 1 month, re-add fixed Vector2.atan2() ? What will
> > Vector2.angle() become then ?
> >
> > Just another remark : when correcting core/math/math_2d.cpp:34
> >
> > real_t Vector2::atan2() const {
> > return Math::atan2(x,y);
> > }
> >
> > to
> >
> > real_t Vector2::atan2() const {
> > return Math::atan2(y,x);
> > }
> >
> > Vector2.look_at() and Vector2.get_angle_to() return false values,
> breaking
> > many demos such as the Look At Pointer demo and the Kinematic Collision
> > demo. Read commit messages, this was explained.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/pull/2260#issuecomment-142767962>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2260#issuecomment-142790131>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
> Using atan(x,y) is way easier to visualize because it just goes like a clock, so all code in Godot assumes it this way, including the function to get the angle.

This definitely needs to be better documented then. For me it's way more natural when doing mathematical operations on vectors to have angles counted counter-clockwise from Vector2(1,0). I could expect helper functions like "angle" to behave otherwise, but I would expect anything labelled as "Math" to behave like the math we learn in school.

**Comment by StraToN** [comment]
@okamstudio Thanks a LOT for your precisions, it is indeed clearer now. 
I have to agree with @akien-mga . The reason of my confusing was that clockwise way to think. I admit it can be easier to beginners to think that way, but I wonder if even the most beginner of beginners thinks that way. Even him should at least have the minimum mathematical knowledge to understand why counter-clockwise exists. As akien-mga precised, counter-clockwise way is simply what we learn at school.

Or, I propose another solution : both ! Simply consider in one hand angle() in *degrees* from -180° to 180°, clockwise like @reduz and @okamstudio proposed, and in the other hand atan2() in radians, counter-clockwise from -PI to PI. This way, anyone can use the one that fits his own mind.

**Comment by slapin** [comment]
Degrees are not that good for real world math, I'd vote for radians, which
you can
always convert to degrees if you want to.

**Comment by akien-mga** [comment]
> Degrees are not that good for real world math, I'd vote for radians

Indeed, and if there are two different atan2() and angle() functions with different conventions, they should both give radians, else it would add up to the already non-negligible confusion.

More generally, though I agree that going clockwise from (0,1) is easy to conceptualize for anyone that knows how to read a clock, as far as math is concerned (and game dev is a lot of math), I find it highly misleading. And if we were to rename the current atan2() to angle(), to then reintroduce an atan2() than respects math convention... I'm not sure it would make it clearer. What the function does should be self-explanatory just by its name, and "angle" does not give an indication whether it's a trigonometric (counter-clockwise from (0,1)) or "clock" angle.

I'd propose to adopt everywhere the math convention that most game devs should be familiar with (what do other engines or libraries do in this regards btw?), or rename the current atan2() to something self-explanatory like clockwise_angle().

Another issue is e.g. how to understand angle_to? Will it give -pi/2 or +pi/2 for ```Vector2(0,1).angle_to(Vector2(1,0))```? In the math world it should be +pi/2, and I guess that's what most users would expect I guess.

One thing that does speak in favour of the current behaviour is that the viewport base system is "flipped" with regard to typical math conventions (i.e. the Y axis points downwards instead of upwards), so that could justify using a different convention for the angle measurement direction.

**Comment by reduz** [comment]
@StraToN, @akien-mga: That's interesting, I no longer remembered there was a school convention for angles in trigonometry (wonder if it's universal?).  To me it always worked the way I described because it's naturally what you get with [sin(angle), cos(angle)] as the normal way of drawing circles. (Guess it has to do with the fact I learned visual programming before learning trigonometry at school :P)

In any case I suppose it does not change much, the convention in Godot is simply that rotations (from the UI to functions) are clockwise. This is likely not apparent because in the 2D engine the Y axis is flipped anyway so they go counter clockwise :D

In any case, I suppose this then has to be simply documented in the few rotation functions in Matrix32, Matrix3, Transform and Vector2

**Comment by akien-mga** [comment]
> That's interesting, I no longer remembered there was a school convention for angles in trigonometry (wonder if it's universal?).

https://en.wikipedia.org/wiki/Trigonometric_functions#/media/File:Unit_circle_angles_color.svg
Angles start at 0 on (1,0), then go counterclockwise up to 2*pi (modulo 2*pi). If going clockwise from (1,0), then angles are negative down to -2*pi (modulo 2*pi).

And the trigonometric circle is actually described by [cos(angle), sin(angle)] when using the proper definition :) https://en.wikipedia.org/wiki/Unit_circle
cos is on the X axis, sin on the Y axis.

**Comment by reduz** [comment]
Guess it shows how much I used trigonometry before moving to linear
algebra. We can say that Godot is inspired by Le Corbusier and aims to
apply a human scale factor to it's usability, such just like clocks and
knobs.

What I find kind of funny is that no one even noticed this so far. I
checked the code and the 3D classes use the standard convention so they
need no commenting, The only place where clockwise is used is in Matrix32
and Vector2, so I suppose this should be documented and that's it.

**Comment by StraToN** [comment]
I just tried to find out (at a guess, no pen nor paper) values that atan2(x,y) should return according to what @reduz wants, I just failed. 

Will be very difficult for me to use atan2() function in Godot, I can predict. I'll surely define my own atan2() function in my scripts. Until then, I am completely lost between changes to bring or not to these : 
- Math::atan2(x,y)
- Vector2::atan2()
- Vector2::angle_to() --> is broken if Vector::atan2() changes
- Vector2::get_angle_to() --> same

I am far too much used to anti-clockwise, horizontal axis related way to think.

**Comment by reduz** [comment]
> Will be very difficult for me to use atan2() function in Godot, I can predict. I'll surely define my own 

Wait, hold on, you are blowing it our of proportion :P let me be clear on what the changes will be:

1) Math::atan2(y,x) will work as always
2) Vector2::atan2() will work as you intend it to, too
3) angle_to() and get_angle_to() are relative, so just negate the output if you want counter clockwise.

**Comment by reduz** [comment]
You are _also_ still getting counter clockwise rotation already, because of the Y axis is flipped in 2D. That already should be a bigger change of convention to you..

**Comment by StraToN** [comment]
@reduz I reverted the last changes in my local workspace, so that the _only_ change left is : 
```cpp
--- a/core/math/math_2d.cpp
+++ b/core/math/math_2d.cpp
@@ -31,7 +31,7 @@
 
 real_t Vector2::atan2() const {
 
-       return Math::atan2(x,y);
+       return Math::atan2(y,x);
 }
```
Here is what the my test script outputs, it seems correct to me. Could you please confirm ?

```
x,y			Vector2.atan2()			Expected
1,0			0			0
1,1			0.785398			0.785398
0,1			1.570796			1.570796
-1,1			2.356194			2.356194
-1,0			3.141593			3.141593
-1,-1			-2.356194			-2.356194
0,-1			-1.570796			-1.570796
1,-1			-0.785398			-0.785398

x,y			atan2(x,y)			Expected (standard)
1,0			1.570796			0
1,1			0.785398			0.785398
0,1			0				1.570796
-1,1			-0.785398			2.356194
-1,0			-1.570796			3.141593
-1,-1			-2.356194			-2.356194
0,-1			3.141593			-1.570796
1,-1			2.356194			-0.785398

x,y			atan2(y,x) value			Expected (standard)
1,0			1.570796			0
1,1			0.785398			0.785398
0,1			1.570796			1.570796
-1,1			2.356194			2.356194
-1,0			3.141593			3.141593
-1,-1			-2.356194			-2.356194
0,-1			-1.570796			-1.570796
1,-1			-0.785398			-0.785398


xplus	xminus	yplus	yminus	xyplus
1,0			-1,0			0,1			0,-1			1,1

xplus.angle_to(xminus)	-3.141593
yplus.angle_to(yminus)	3.141593
xplus.angle_to(yminus)	1.570796
xplus.angle_to(xyplus)	-0.785398
xplus.angle_to(xminus)	0
```

However now, LookAt demo is broken : 
recorded

**Comment by reduz** [comment]
which is why atan2 will be changed to get_rotation()

**Comment by StraToN** [comment]
@reduz The bug illustrated above is caused by Node2d.get_angle_to() which I give here : 
```cpp
float Node2D::get_angle_to(const Vector2& p_pos) const {
	return (get_global_transform().affine_inverse().xform(p_pos)).atan2();
}
```

The fact is that I changed Vector2.atan2() from this : 
```cpp
real_t Vector2::atan2() const {
	return Math::atan2(x,y);
}
```
to this : 
```cpp
real_t Vector2::atan2() const {
	return Math::atan2(y,x);
}
```
according to Math::atan2() definition (unchanged, I didn't touch it) : 
```cpp
double Math::atan2(double p_y, double p_x) {
	return ::atan2(p_y,p_x);
}
```

Therefore, Node2D::get_angle_to() does not return the same value as before because of (get_global_transform().affine_inverse().xform(p_pos)). In this PR, I tried to inverse the xform vector using some dirty hack (d05f293).

**Comment by reduz** [comment]
@StraToN because godot rotations are clockwise you can't use atan2() in that code. This is why, as said before, atan2() will be wiped from all the engine code and replaced by an angle() function

**Comment by StraToN** [comment]
> @StraToN because godot rotations are clockwise you can't use atan2() in that code. This is why, as said before, Vector2.atan2() will be wiped from all the engine code and demos and replaced by an angle() function

I understood ;) (we just talked about it on IRC). I _don't intend to touch Math::atan2()_ which already works fine to me, _but Vector2.atan2() which doesn't_. 
Renaming Vector2.atan2() to Vector2.angle() is a good idea, it will help us differentiating these 2 methods, as we lost a lot of time misunderstanding each other which method we are talking about :)

**Comment by akien-mga** [comment]
Where do we stand on this PR again? :)

**Pull request closed without merging**
