### PR TITLE
Add shuffle() method to Array

### PR DESCRIPTION
**Pull request by ghost**
Related to https://github.com/godotengine/godot/issues/3327, it might be worth considering adding a `shuffle` method to `Array`.

### CODE REVIEW

**Comment by vnen** [comment]
This would solve the (closed) #2576 issue. Though this was regarded as not needed, I wondered if it might be reconsidered.

**Comment by poke1024** [comment]
My two cents: even though this is just two lines of code, there's a reason Wikipedia has a whole paragraph on "implementation errors": https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

**Comment by reduz** [comment]
a LOT of people asked for it, so i dont mind adding it. Lets do after 3.0
though.

**Comment by raymoo** [comment]
Could you add a way to make it deterministic? Such as passing in an RNG in some way, or a seed?

**Comment by poke1024** [comment]
@raymoo It is deterministic, it uses `Math::rand()` internally which adheres to the Godot's global random seed (the one you control using `seed` and `randomize` in gdscript).

**Comment by raymoo** [comment]
@poke1024 Ok, thanks. Sort of an orthogonal question, but does Godot's RNG behave the same on all platforms?

**Comment by poke1024** [comment]
@raymoo It should indeed. It internally uses http://www.pcg-random.org/, the implementation is minimal and, from what I see, should do exactly the same on all platforms (see `pcg32_random_r`).

**Comment by Zylann** [comment]
Just a note, I don't think the Math::rand() of Godot can be considered deterministic in production though, because it is global (any usage for VFX purpose as wild example would alter results)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
