### PR TITLE
Add help label about creating multiple/big tiles

### PR DESCRIPTION
**Pull request by KoBeWi**
image

### CODE REVIEW

**Review by groud — APPROVED** [review]

**Comment by kleonc** [comment]
Have you tried/considered aligning the hints vertically? Like in the 2D editor:
BT9WSCueaF
Seems easier to skim through them.

**Comment by KoBeWi** [comment]
idk, doesn't it take more space?
image
The editor is more horizontal than vertical.

**Comment by kleonc** [comment]
> idk, doesn't it take more space?

Seems like, but spacing between the lines is way bigger compared to the 2D editor though. Also now looking at it I wonder if dimming these hints in a similar manner would make sense. OTOH I do remember pointing some user at the hints in 2D editor when answering some how-to, and the user mentioned they've never noticed these hints. So not really sure if dimming is good. :upside_down_face:
Horizontally they look strange to me, that's all, wanted to point it out (I don't know GUI design principles or something like though).

**Comment by YuriSizov** [comment]
Thanks! Let's go with what we have for now. Can always move things around later. I agree with kleonc that it does look a bit weird,  just floating in there. But it's not a big deal for now. If we get more hints in the future, then having them vertically would probably be better.

**Pull request merged**
