### PR TITLE
SCons: Only use alias if SCons v4.3 or later

### LINKED ISSUE #91049: Cannot compile Godot due error in SConstruct with SCons 4.0.1
### Tested versions

Works - 7316918a0f546f9fa406fd65b9a70161169426a8
Not works - 7abe0c6014022874378cb64a11b26b0f0f178324

### System information

Ubuntu 22.04 CI

### Issue description

` scons -j2 dev_build=yes target=editor use_asan=yes use_ubsan=yes linker=gold`

cause to show on Github CI this error
```
 KeyError: 'platform':
  File "/home/runner/work/Qarminer/Qarminer/godot/SConstruct", line 287:
    selected_platform = env["platform"]
  File "/usr/lib/python3/dist-packages/SCons/Environment.py", line 405:
    return self._dict[key]
```

Probably regression from - https://github.com/godotengine/godot/pull/90857

CI job - https://github.com/qarmin/Qarminer/actions/runs/8793092362

### Steps to reproduce

Above

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Repiteo**
Fixes #91049

Alias array support was added in 4.3, so earlier versions will require the old syntax. Implemented this via a conditional against `scons_ver`, which is now evaluated at the very beginning of the file.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by nagidev** [comment]
Hi, I'm on Scons v4.0.1 and getting this error on running `scons platform=linuxbsd`:
```
TypeError: SConsEnvironment._get_major_minor_revision() missing 1 required positional argument: 'version_string':
```
Is this unintentional or should I just update my scons to the latest version?

**Comment by Malcolmnixon** [comment]
> Hi, I'm on Scons v4.0.1 and getting this error on running `scons platform=linuxbsd`:

I just got the same thing on Scons v4.4.0 on Windows `scons platform=windows`.

I updated to v4.5.0 using `python -m pip install --upgrade scons==4.5.0` and it worked fine; so it looks like 4.5.0+ is the new requirement.

**Comment by akien-mga** [comment]
This will be fixed by https://github.com/godotengine/godot/pull/91080.

But in general it's advised to use latest scons if you can, it tends to perform better.

**Pull request merged**
