### PR TITLE
Adds fuzzy search for help search dialog

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**

### CODE REVIEW

**Comment by Calinou** [comment]
Does this preserve the behavior where writing `(` makes it possible to narrow down the search?

**Comment by guilhermefelipecgs** [comment]
Typing "(" in the end will restrict the search for methods, but using fuzzy search as well.

**Comment by guilhermefelipecgs** [comment]
I can disable fuzzy search when the string starts with `.` or ends with `(` if desired.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
