### PR TITLE
TileSetEditor: Improvements and fixes

### LINKED ISSUE #22077: Unable to select overlapping tile regions in TileSet Editor
**Godot version:**
909c06ee0f0ab5feced1c9c99a725f7a423ff9f8 compiled with Mono support

**OS/device including version:**
Windows 10 Home 64-bit

**Issue description:**
In a large tile sheet there are situations where I need an auto-tile region to overlap either an individual tile or a tile atlas. Currently, I do not know of a way to specify which one of the overlapping regions I want to select. Clicking twice results in redefining the first region's region (bad wording, sorry).

I think the ability to shift-/control-click to cycle between overlapping regions would help. Or as a simplification, the shift-/control-click could select the closest top-left corner of some region.

**Edit:**
I forgot to mention, this is only a problem when one region completely envelopes another.

### LINKED ISSUE #25203: Selecting Tiles in New Tile Editor is Difficult or Impossible
**Godot version:**
v3.1.beta-1 Official

**OS/device including version:**
Windows 10 Pro

**Issue description:**
There is no easy way to cycle between tiles when using the new tileset editor.  The source seems to suggest that one should use the region tool and click on the tile that one desires to edit, but if two tiles overlap, one is likely to either redefine the region of the tile they're editing (losing work) or not select the tile beneath the selection.

**Steps to reproduce:**
Draw two overlapping regions in the tileset editor.  Attempt to switch from the latter region to the former.  It's not possible without moving the autotile region, selecting the other, then moving the second autotile region back and redoing the work.

**Suggested fix**
Simple fix: If a tile is selected and a click is performed, selecting a new tile should take precedence over moving or defining an autotile area.

Better fix: A spinner or preview of some sort to switch between the active tile.

[GodotIssueTileMapSelect.zip](https://github.com/godotengine/godot/files/2780785/GodotIssueTileMapSelect.zip)

The zip file contains a sample project and a video of me trying to illustrate the problem.

### LINKED ISSUE #26369: Only the First Shape in the Tile Set Editor is Selectable
**Godot Version:** 
Latest 3.1 Master Branch (Commit: a5370b1b1bed3744941c90b4a05d4516aabd4c67)

**OS/device including version:** Windows 10

**Issue description:**
When creating multiple shapes with the new tileset editor the newly created shapes are not selectable. The first shape will be selected all the time. See the gif below.

Got obvious after fixing #24003.

**Steps to reproduce:**
1. Create a new tile set
2. Add any texture to it
3. Create a new tile (doesn't matter which type)
4. Click on collision and create a new poly shape
5. Create another poly shape
6. Try to select the new poly shape to edit it

**Minimal reproduction project:**
[TileSetEditor_ShapeSelectionBug.zip](https://github.com/godotengine/godot/files/2911949/TileSetEditor_ShapeSelectionBug.zip)

### PR DESCRIPTION
**Pull request by MarianoGnu**
- [x] Allow to change selection around all tiles on the texture without clicking on them. Fixes #25203. Fixes #22077. You can use tool buttons or keyboard shortcuts to select across all tiles / subtiles
- [x] Allow to change selection of collision shapes added to the same tile. Fixes #26369.
- [x] Allow to change collision type (convex / concave). Alternative fix to #24003.
more to come... on the next PR

### CODE REVIEW

**Comment by MarianoGnu** [comment]
I had some problems because i installed an old version of clang-format, should be able to work normally from now on.

**Comment by akien-mga** [comment]
CC @YeldhamDev @guilhermefelipecgs for review.

**Comment by akien-mga** [comment]
@MarianoGnu Did you mark this as WIP because the current commits are not ready to merge yet, or because you want to fix other bugs in this PR? I'd prefer to merge fixes as they come, and you can make other PRs for the rest. It's better to get things tested independently, and we're quite late in the release process now (a few days away from stable...) so this needs to be tested ASAP.

**Comment by MarianoGnu** [comment]
@akien-mga  I marked it as WIP because i wanted to make collision toggling before merge. there are more bugs tat i want to tackle, but most important ones here now if you find changed good (note: seccond commit fixed some regresions caused by a bad rebasing on the first commit while dealing with clang-format). you can merge now and i'll open a new PR.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
