### PR TITLE
Add a V-Sync editor setting

### LINKED ISSUE #62821: Stutter on Linux X11 when using multiple monitors
### Godot version

4.0-alpha11

### System information

Linux 5.18.9-arch1-1, NVIDIA driver version 515.57, RTX 2070 Super

### Issue description

I have a 3 monitors setup where two are 240hz and one is 60hz. When I run my project with vsync enabled I see a consistent stutter every 120 frames. 

image

I don't know if this is related but my primary monitor is a 240hz, when I launch my scene, Godot reads my refresh rate as 60hz. It seems that's happening because it thinks my 60hz monitor is the primary one.

image

image

If I disable vsync, the problem goes away.

xrandr info:

```
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 connected 1080x1920+4480+0 right (normal left inverted right x axis y axis) 800mm x 340mm
   1920x1080     60.00 +  59.94*   50.00    29.97
   1680x1050     59.95
   1600x900      60.00
   1280x1024     75.02    60.02
   1280x720      60.00    59.94    50.00
   1152x864      75.00
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x480       59.94
   640x480       75.00    59.94    59.93
HDMI-0 connected (normal left inverted right x axis y axis)
   3840x2160     60.00 +  59.94    50.00    29.97    25.00    23.98
   4096x2160     59.94    50.00    29.97    25.00    24.00    23.98
   2560x1440    120.00
   1920x1080    119.88   100.00    60.00    59.94    50.00    29.97    25.00    23.98
   1280x1024     60.02
   1280x720      59.94    50.00
   1152x864      60.00
   1024x768      60.00
   800x600       60.32
   720x576       50.00
   720x480       59.94
   640x480       59.95    59.94    59.93
DP-2 connected 1920x1080+0+551 (normal left inverted right x axis y axis) 544mm x 303mm
   1920x1080     60.00 + 239.76*  143.98   119.98    59.94    50.00
   1600x900      60.00
   1280x1024     75.02    60.02
   1280x720      59.94    50.00
   1152x864      75.00
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x480       59.94
   640x480       75.00    59.94    59.93
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected primary 2560x1440+1920+371 (normal left inverted right x axis y axis) 1mm x 1mm
   2560x1440    144.00 + 239.96*  120.00    59.95
   1920x1080    239.76   143.98   119.88    60.00    59.94    50.00
   1680x1050     59.95
   1600x900      60.00
   1440x900      59.89
   1280x1024     75.02    60.02
   1280x800      59.81
   1280x720      60.00    59.94    50.00
   1152x864      75.00
   1024x768      75.03    70.07    60.00
   800x600       75.00    72.19    60.32    56.25
   720x576       50.00
   720x480       59.94
   640x480       75.00    72.81    59.94
```

### Steps to reproduce

Not sure how to properly reproduce this but I can help with fixing the issue if you give some ideas about what might be happening.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/48366.

The editor setting makes it possible to tweak V-Sync status independently of the project setting.

Use cases:

- Decrease input lag and increase editor responsiveness when editing a project that has V-Sync enabled.
- Avoid tearing when editing a project that has V-Sync disabled.

Inspired by https://github.com/godotengine/godot/pull/20916, but the default behavior is now to have V-Sync enabled.

- See also https://github.com/godotengine/godot-proposals/issues/1923.
- This closes https://github.com/godotengine/godot/issues/62821.

### CODE REVIEW

**Comment by Chaosus** [comment]
@Calinou Does this look actual after #48622?

**Comment by Calinou** [comment]
> @Calinou Does this look actual after #48622?

Rebased and tested again, it works successfully.

**Comment by bjorn** [comment]
What's holding this up? I just spent a while trying to find a way to turn off V-Sync in the editor, until I found this PR. I'd love to get rid of the annoying input lag on Linux caused by the V-Sync!

After browsing the related issues, I noticed a comment about `--disable-vsync`, which actually does the trick for me. But an option in the Editor Settings would have been much easier to find. :-)

(And after trying this option, I have no idea why one would default vsync to on... the compositor seems to be already taking care of any tearing and the vsync seems to be just adding a huge unnecessary lag. Running X11 without compositor should be rather rare today, but maybe the behavior isn't the same everywhere...)

**Comment by Calinou** [comment]
> What's holding this up?

It needs a review from a contributor who is knowledgeable in the area :slightly_smiling_face: 

> I'd love to get rid of the annoying input lag on Linux caused by the V-Sync!

If you have a variable refresh rate monitor (and VRR is enabled on windowed applications[^1]), remember that you can leave V-Sync enabled and set a framerate cap by changing **Low Processor Mode Sleep Usec** in the editor settings to `1.0 / vrr_fps_cap`, where `vrr_fps_cap` is determined by the formula `refresh_rate - (int(refresh_rate / 60.0) + 1)`. For instance, on a 60 Hz display, this is 58 FPS. On a 120 Hz display, this is 117 FPS, and on a 144 Hz display, this is 141 FPS. This allows you to get the best of both worlds (no tearing, low input lag).

See https://blurbusters.com/howto-low-lag-vsync-on/ for more information, and https://github.com/godotengine/godot-proposals/issues/5451 which provides an automatic VRR-friendly framerate cap that can be selected by the user. (There's unfortunately no standard API to detect whether the user is currently using VRR, so this cannot be enabled automatically.)

> (And after trying this option, I have no idea why one would default vsync to on... 

I'd also prefer to have V-Sync off by default in the editor, but this should be discussed separately. reduz was against it last time I brought this up, since it results in noticeable tearing when panning in the 2D/3D editor viewports.

[^1]: This is always the case on X11, but VRR only affects fullscreen apps by default on Windows.

**Comment by akien-mga** [comment]
Disabling V-Sync in the editor means burning CPU needlessly to render UI and the 2D/3D viewport, so this seems quite wasteful as a default setting. A lot of people use Godot on laptops and don't want to have fans spinning and the battery draining while organizing their scene nodes or writing scripts.

But adding an option to disable V-Sync is fine with me.

**Comment by Calinou** [comment]
> Disabling V-Sync in the editor means burning CPU needlessly to render UI and the 2D/3D viewport,

There's already a FPS cap in place in the form of low-processor mode, although it does not cater to the monitor refresh rate currently (it's roughly 145 FPS). See https://github.com/godotengine/godot-proposals/issues/5451. In the long term, we should unify the low-processor mode sleep duration and max FPS project settings into a single setting, as they're redundant since 3.2 when the low processor mode sleeping was reworked to be smoother.

**Comment by bjorn** [comment]
> Right now, V-Sync in the editor is controlled by the V-Sync project setting.

I had tried changing that setting but it had no effect, so I assumed it would only affect a running game or something. Now I realize the setting just needs a restart to apply.

> Disabling V-Sync in the editor means burning CPU needlessly to render UI and the 2D/3D viewport, so this seems quite wasteful as a default setting.

I just compared CPU usage on my system and it's 1% regardless of V-Sync being on or off. Anyway, I can understand if the behavior is different elsewhere. (though, if we're really worried about CPU usage, then I would expect 0% usage when I'm not doing anything - and no animation is playing)

**Review by akien-mga — APPROVED** [review]
Looks good overall.

How does this handle multiple windows? Do new windows spawned in the editor (e.g. dialogs) respect this setting too?

**Comment by Calinou** [comment]
> How does this handle multiple windows? Do new windows spawned in the editor (e.g. dialogs) respect this setting too?

I'm not sure how to test this, as I don't have a working way of having a FPS overlay on individual Godot windows ([MangoHud doesn't play well with self-compiled builds](https://github.com/godotengine/godot/issues/75409)).

**Pull request merged**
