### PR TITLE
[GraphEdit] Correctly disconnect signal to `connection_layer`

### LINKED ISSUE #94811: [GraphEdit] GraphElement's 'item_rect_changed' signal is not disconnected when leaving tree
### Tested versions

Repoducible on Godot Engine v4.3.rc1.official

### System information

Godot v4.3.rc1.mono - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3090 (NVIDIA; 31.0.15.4592) - 13th Gen Intel(R) Core(TM) i7-13700F (24 Threads)

### Issue description

When a `GraphElement` removed from SceneTree and added back, will throw errors like these.

image

### Steps to reproduce

Open the MRP,
Just press Space or Enter to make a GraphNode in and out, and check the debugger

### Minimal reproduction project (MRP)

[graphedit_signal_mrp.zip](https://github.com/user-attachments/files/16395056/graphedit_signal_mrp.zip)

### PR DESCRIPTION
**Pull request by maidopi-usagi**
Fix #94811

### CODE REVIEW

**Review by Geometror — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Naros** [comment]
@akien-mga and @Geometror are we sure this code change is correct?  

I've built this locally against master, and I'm am noticing that this leads to this error.

```
ERROR: Attempt to disconnect a nonexistent connection from '[Wrapped:0]'. Signal: 'item_rect_changed', callable: 'CanvasItem::queue_redraw'.
   at: (core\object\object.cpp:1529)
```
I see that the signal is not connected when this change is fired:

**Comment by Naros** [comment]
If I wrap the call in the theme notification as:
```cpp
case NOTIFICATION_THEME_CHANGED: 
  if (is_node_ready()) {
    // call my custom synchronize met
    _synchronize_graph_with_script();
  }
  break;
```
Then I don't see the issue, its only if the implementation adds/removes nodes before the node is ready that the calls to the add/remove child notify fails.

**Comment by maidopi-usagi** [comment]
> It's this that creates an issue during theme changed which wasn't an issue in Godot 4.3.stable.
@Naros Thanks for reporting!  I'm wondering if the problem you're encountering might be related to this specific commit, as this PR has already been contained in 4.3.stable build. Would you mind opening a separate issue and provide additional details about your testing environment and reproduction steps?

**Comment by Naros** [comment]
Hmm @maidopi-usagi in that case, I wonder if the issue is some change in Godot 4.4 that breaks this commit.  I nor none of our user community saw this on Godot 4.3.stable 🤔. Let me continue to check and once I know for sure, I'll open another issue.

**Pull request merged**
