### PR TITLE
C#: Add compat overloads

### PR DESCRIPTION
**Pull request by raulsntos**
Adds methods to avoid breaking binary compatibility.

- Extracted from https://github.com/godotengine/godot/pull/77183.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by RedworkDE** [comment]
1. Is there any particular reason for using named parameters for some of the added parameters?
2. The `<inheritdoc>` doesn't seem to work in vs2022 and vscode, so unless there are other editors where that does work I would just remove the docs bit entirely
3. (I would have said to mark these overloads as obsolete, but they are preferred in overload resolution, so that doesn't work)

Didn't actually test if this works at preserving binary compat, LGTM tho.

**Comment by raulsntos** [comment]
> 1. Is there any particular reason for using named parameters for some of the added parameters?

Just to be more clear when the argument is a literal.

> 2. The <inheritdoc> doesn't seem to work in vs2022 and vscode, so unless there are other editors where that does work I would just remove the docs bit entirely

It works for me in VSCode. I haven't tried other IDEs.

> Didn't actually test if this works at preserving binary compat

In my testing, a library that was built referencing the 4.0.x Godot packages and uses one of the methods that were removed would throw a `System.MissingMethodException` when building a project using 4.1. With these methods the exception is not thrown.

**Comment by RedworkDE** [comment]
In that case you missed the parameter name for `CreateMultipleConvexCollisions` and `PushList`

---

For me in vs code the compat overload doesn't have docs:
image
While the primary one does have it:
image
Tho when hovering it does actually show up so IDK, doesn't really matter, it's fine as is.

**Review by RedworkDE — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
