### PR TITLE
Cherry-picks for the 3.2 branch (future 3.2.2) - 6th batch

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by madmiraal** [comment]
I think the C4724 warning is due to these, because `edges.size()` may be 0:
https://github.com/godotengine/godot/blob/8e91d2746d28d1f84f872ef535b55807e1ac3535/scene/3d/navigation.cpp#L255
https://github.com/godotengine/godot/blob/8e91d2746d28d1f84f872ef535b55807e1ac3535/scene/3d/navigation.cpp#L338
https://github.com/godotengine/godot/blob/8e91d2746d28d1f84f872ef535b55807e1ac3535/scene/3d/navigation.cpp#L397
https://github.com/godotengine/godot/blob/8e91d2746d28d1f84f872ef535b55807e1ac3535/scene/3d/navigation.cpp#L460
https://github.com/godotengine/godot/blob/8e91d2746d28d1f84f872ef535b55807e1ac3535/scene/3d/navigation.cpp#L532
https://github.com/godotengine/godot/blob/8e91d2746d28d1f84f872ef535b55807e1ac3535/scene/3d/navigation.cpp#L589
An alternative is to use:
```(i+1) == edges.size() ? 0 : i+1```

**Comment by akien-mga** [comment]
@madmiraal But I'm preventing those to run with `ERR_FAIL` checks in https://github.com/godotengine/godot/pull/38832/commits/f390749439f6317b950b4f14528ef4b38811cd66 already, so it should not be possible for those mods to be called with 0. I guess MSVC is not clever enough to see that the branch has an early return in our macros?

**Comment by akien-mga** [comment]
I changed the AppVeyor commit a520e03730f to use `werror=no` for now. We should be able to see all remaining warnings in the CI log and see how to solve them. Apparently f390749 doesn't suffice to fix C4724.

**Comment by madmiraal** [comment]
It's definitely going to take more work. I've managed to extend f390749 to fix all the warnings in `scene\3d\navigation.cpp`, but now I get the same warnings in `scene\2d\collision_polygon_2d.cpp`:
[https://ci.appveyor.com/project/madmiraal/godot/builds/33002769](https://ci.appveyor.com/project/madmiraal/godot/builds/33002769)

Something else has changed to cause these warnings, but I can't work out what it is. The only thing that has changed in `cowdata.h` is 94f451e0, but I don't see how that causes it, especially if it's not happening in master.

**Pull request merged**
