### PR TITLE
travis: caching Android, iOS, macOS (cross-compile) (master)

### PR DESCRIPTION
**Pull request by rraallvv**
Speeding up travis a bit... (#12887)

### CODE REVIEW

**Comment by akien-mga** [comment]
As I understand it [from the docs](https://docs.travis-ci.com/user/caching/#ccache-cache), Travis should already add the needed wrappers around the CC/CXX stuff, so are you sure we need this additional logic in detect.py?

**Comment by akien-mga** [comment]
It looks great as a whole, nice work!

Given that Travis' OSX workers are always overloaded and with a big backlog, I'd still keep the iphone build commented out for now until they improve their infra, otherwise it will bring build times down too much. And the readded Android/tools=no already covers most of what the iphone build was used for.

When changing that, please also amend the commit log to me more explicit (you're not just "speeding up travis", you're changing the way deps are installed, extending the caching and changing the build matrix).

**Comment by rraallvv** [comment]
@akien-mga `ccache-osx.sh` does install the wrappers in the same place that `brew install ccache` does, so adding the path to the wrappers would be the same on macOS:

	export PATH="/usr/local/opt/ccache/libexec:$PATH"

On linux the path to the wrappers is `/usr/lib/ccache`, and it's already exported, so I removed the one I had added.
 
Caching for Android, iOS, and OS X cross-compile would need to be done by [prepending](https://ccache.samba.org/manual.html#_run_modes) `ccache` to the command used for compilation, like so:

    else: # osxcross build
        ...

        ccache_path = os.environ.get("CCACHE")
        if ccache_path == None:
            env['CC'] = basecmd + "cc"
            env['CXX'] = basecmd + "c++"
        else:
            # there aren't any ccache wrappers available for osxcross,
            # to enable caching we need to prepend the path to ccache
            env['CC'] = ccache_path + ' ' + basecmd + "cc"
            env['CXX'] = ccache_path + ' ' + basecmd + "c++"

The approach I used was to check if `CCACHE` was exported and prepend that as the path to `ccache` only when it's needed (for instance for OS X cross-compile).

Other approach could be to export a flag instead `export USE_CCACHE=1`, and detect the path to the ccache binary from `detect.py`, please let know what approach you think is better.

Also, do I need to disable X11/tools=no in the branch master and 2.1 now that Android/tools=no is enabled? If we turn of the build for iphone (as you mentioned) that would leave us with only four workers occupied (static analysis, android/tools=no, x11/tools=yes and osx/tools=yes)

**Comment by akien-mga** [comment]
Thanks for the detailed checks. It looks good to me now, let's merge. For X11/tools=no, we could indeed disable it, but let's see first how the current matrix runs and if we need to reduce the number of jobs; otherwise it's nice to have a fast linux/clang check.

**Pull request merged**
