### PR TITLE
Fixed box/region/rectangle selection in the 3D view

### PR DESCRIPTION
**Pull request by sketchyfun**
This wasn't working at all, so I had a dig around to see what the issue was. 

I removed ` Vector<Spatial *> selected;` as it was never populated, and the only time it was checked was to see if the item found wasn't in it, which was pointless. 

`if (seg->intersect_frustum(camera, frustum))` also didn't seem to be required, so I removed that too, and then the box selection worked.

However (there's always a however..), the new camera smoothing stuff was throwing off the box selection whenever the camera was orbited, as the linear interpolation left the camera position and the 3d cursor position slightly out of sync. I used the current cursor position instead of the camera position (they should be identical, but aren't quite for the reason explained above) and this fixed the issue. Now box selection works as it should :)

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @SaracenOne who last edited this code.

**Comment by sketchyfun** [comment]
Don't think this affects anything he's worked on?

**Comment by akien-mga** [comment]
`git blame` says otherwise: 3cecd0c6dc

**Comment by sketchyfun** [comment]
Ahh I see it. Hmm, @SaracenOne can you explain the code you added to spatial_editor_plugin.cpp? When I added some print statements to see what was going on, the seg->intersect_frustum part didn't ever return true for me, no matter what I tried to region select. Changing it to the modifications in my pull request allowed me to select without any problems, curious if I've undone something important even though it appears to work?

**Comment by SaracenOne** [comment]
@sketchyfun Hmm...I think what might have happened is box selection was broken at the time at I did my own adhoc fix which might have conflicted with the actual fix. As long as the box selection still works when selected nodes which are part of a subscene, which my older PR was intended to fix, it should be fine. Honestly can't remember otherwise.

**Comment by sketchyfun** [comment]
> As long as the box selection still works when selected nodes which are part of a subscene
Do you mean as long as the box select can select instanced scenes?

**Comment by sketchyfun** [comment]
Actually I think I can see what you're code was trying to do now. The version I've submitted selects instanced scenes correctly, but if editable children is enabled, then it will select child nodes as well, I think this is correct. However, much like the current single click-selection implementation, nodes that don't have a valid collision segment or spatial editor gizmo seem to be skipped. Will try to see if I can find a way around that, but if not, it's no worse than how the other selection implementations work currently.

**Comment by akien-mga** [comment]
Some weird stuff happened with your last push here, you'll need to rebase on the current upstream/master.

**Comment by sketchyfun** [comment]
Yeah, I managed to screw something up the other day, it's probably simpler for me to close this and open a new pull request. Would that be okay?

**Comment by akien-mga** [comment]
Sure, as you prefer.

**Comment by sketchyfun** [comment]
Actually nevermind, I try and fix it tomorrow

**Comment by sketchyfun** [comment]
Okay, I think I've fixed my mess now :D

**Comment by sketchyfun** [comment]
Somehow managed to fudge up a bunch of stuff with this pull request it seems, so I'm gonna create a new one soon. Sorry about that!

**Pull request closed without merging**
