### PR TITLE
added smart searching with preferrence to root node

### PR DESCRIPTION
**Pull request by toger5**

### CODE REVIEW

**Comment by groud** [comment]
Could you explain a little bit what this PR does ? I don't undestand exactly what's happening there.

**Comment by Noshyaar** [comment]
Probably something like: if the scene root is 3D type, search will return 3D variant of the node instead of 2D.

**Comment by toger5** [comment]
Yea @Noshyaar.  Thats what it is doing.

You van check the issue refereneced in the commit msg to real about it.

**Comment by groud** [comment]
As I have said in IRC, I think this might deserve a more generic approach.
Like instead of testing if it is either 2d or 3d, we could use a "family tie" distance function. 

Tomething like: the number of parent to reach the closest common ancestor of both the root node type and another one.

**Pull request merged**
