### PR TITLE
Use default samplers in base uniform set when rendering to reflection probes

### LINKED ISSUE #83962: Vulkan: reflection probe rendering breaks when window gets resized or is maximized
### Godot version

v4.2.beta2.mono.official [f8818f85e]

### System information

Godot v4.2.beta2.mono - Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 570 Series (RADV POLARIS10) () - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

When resizing the window while the reflection probes are being rendered (either at the start for `UPDATE_MODE_ONCE` probes or constantly for `UPDATE_MODE_ALWAYS`), the debugger gets flooded the following messages, in this order in my actual project but seemingly in a random order on the reproduction project:

```
E 0:00:04:0647   draw_list_draw: Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
  <C++ Error>    Method/function failed.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7491 @ draw_list_draw()
E 0:00:10:0103   uniform_set_create: Sampler (binding: 3) should provide one ID referencing a sampler (IDs provided: 0).
  <C++ Error>    Method/function failed. Returning: RID()
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:5496 @ uniform_set_create()
E 0:00:10:0103   draw_list_bind_uniform_set: Parameter "uniform_set" is null.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7336 @ draw_list_bind_uniform_set()
E 0:00:10:0103   draw_list_draw: Uniforms were never supplied for set (0) at the time of drawing, which are required by the pipeline
  <C++ Error>    Method/function failed.
  <C++ Source>   drivers/vulkan/rendering_device_vulkan.cpp:7491 @ draw_list_draw()
```

The reflection will also flicker.

### Steps to reproduce

1. Open the reproduction project
2. Start the project
3. Resize the window
5. Look into the debugger

### Minimal reproduction project

[VkBugRepr.zip](https://github.com/godotengine/godot/files/13169875/VkBugRepr.zip)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/83962

The RenderBuffers used by ReflectionProbes doesn't create and maintain its own set of samplers. So basically what was happening was the Viewport RenderBuffers were invalidating the base_uniform_set (so it would get recreated with the new samplers). But then the ReflectionProbes would get rendered, and they don't have valid samplers, so they would give invalid samplers and the base_uniform_set would be null. Then rendering would fail for a frame. The Viewport would then get rendered and update the base_uniform_set to be valid. Then, in subsequent frames, the ReflectionProbes would just use the updated base_uniform_set.

This PR works, but I think it will bring us back to the state where the sampler gets ignored when changed (due to how the caching works). I need to do a bit more testing before this is ready.

### CODE REVIEW

**Comment by clayjohn** [comment]
It seems that we are going to need to implement a base_uniform_set cache. Right now the first Viewport to set a base_uniform set wins and its settings are used for everything else.

**Comment by clayjohn** [comment]
This iteration fixes https://github.com/godotengine/godot/issues/83962 and an unreported bug whereby the wrong bias is used. 

However, there is still an existing unreported bug that will require more invasive changes. Right now we maintain a ``render_base_uniform_set`` which should only hold data that doesn't change between draw calls. However, since we made the samplers change per viewport/render type, that assumption no longer holds true. ``render_base_uniform_set`` can change depending on the type of rendering going on (shadows, probes, scene draw) and per viewport. 

This PR splits ``render_base_uniform_set`` into two, one for viewports (where bias is not default) and one for everything else (where bias is always default). This fixes the most obvious bug, but it will stop working if multiple viewports are used in a scene and the Viewports do not all have the same bias setting. 

A perfect solution would be one where we either store the samplers in another location (one that is updated more frequently), or we store the ``render_base_uniform_set`` on a per-viewport basis with a default implementation for non-viewport rendering. That, however, would be a much more invasive change than this, so it might be best to hold that off for 4.3

**Comment by Calinou** [comment]
> This iteration fixes https://github.com/godotengine/godot/issues/83962 and an unreported bug whereby the wrong bias is used.

Judging by your description, this may also fix https://github.com/godotengine/godot/issues/65690 :slightly_smiling_face: I'll give it a try.

> This fixes the most obvious bug, but it will stop working if multiple viewports are used in a scene and the Viewports do not all have the same bias setting.

I assume this is connected to https://github.com/godotengine/godot/issues/84083.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

**Comment by clayjohn** [comment]
> > This iteration fixes #83962 and an unreported bug whereby the wrong bias is used.
> 
> Judging by your description, this may also fix #65690 🙂 I'll give it a try. **Edit:** This PR doesn't appear to fix that issue.

That's a different issue, ya.

> > This fixes the most obvious bug, but it will stop working if multiple viewports are used in a scene and the Viewports do not all have the same bias setting.
> 
> I assume this is connected to #84083.

That's right. I hadn't seen https://github.com/godotengine/godot/issues/84083 before. It is exactly what I was describing

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
