### PR TITLE
Added API to read the normal and position of the overlapped body

### PR DESCRIPTION
**Pull request by AndreaCatania**
Added API to read the normal and position of the overlapped body

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs a rebase after #26011. As mentioned there, it seems you authored that commit with the wrong email address, you might want to edit it to fix that.

**Comment by AndreaCatania** [comment]
Done

**Comment by AndreaCatania** [comment]
@akien-mga if you merge this one I can open new merge request that optimize bullet implementation making it faster

**Comment by reduz** [comment]
Sorry, this API is undesired. Areas are meant to use simple collision detection that does not require the computation of a penetration vector. I feel if you need something like this, you can use the direct space APIs to get this information already, so there is no need for further additions to the API.

**Comment by reduz** [comment]
And technically, only Bullet is able to give this information, virtually any other physics engine that uses SAT for collision detection is not able to, so this is really pointless and bullet-spacific. Maybe you can add those functions to the Bullet physics server if you want and use them only there.

**Comment by AndreaCatania** [comment]
It was useful for us know these information, but Ok

**Pull request closed without merging**
