### PR TITLE
Bump mbedTLS to version 2.10.0

### PR DESCRIPTION
**Pull request by Faless**
MbedTLS added a new function `mbedtls_platform_zeroize()` and have scary notice about compiler with aggressive optimizations that may try to remove it.

I have to ask someone with a bit more compiler experience than me (@hpvb ?) to double check that

### CODE REVIEW

**Comment by Faless** [comment]
They actually mention having tests for it, maybe we could include them in Godot build tests, I never really understood how they work, but I'll explore the possibility tomorrow :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> They actually mention having tests for it, maybe we could include them in Godot build tests, I never really understood how they work, but I'll explore the possibility tomorrow :)

Currently we don't really have any tests running. The few tests in `main/tests/` are basically just running some scripts standalone, so they only test some parts of the API and likely wouldn't be suitable to test if a mbedtls function does its job.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
@hpvb Sorry to spam you, but could you take a look at `mbedtls_platform_zeroize()` above?

**Comment by akien-mga** [comment]
Let's Test in Production™ :)

**Comment by mhilbrunner** [comment]
Yeah, but the problem with this is that this won't break anything in a obvious way if there are problems, it will just make the compiler optimize away zeroing out the memory, potentially leaving cryptograhic secrets available in main memory longer than necessary.

Hopefully not quite catastrophic because people rarely build server applications handling in Godot, but still.

**Pull request merged**
