### PR TITLE
Add linear/angular motor support to SliderJoint

### PR DESCRIPTION
**Pull request by Klowner**
This change adds wiring for utilizing `SliderJoint` angular and linear motors

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by akien-mga** [comment]
Ping @AndreaCatania (maybe also @sdfgeoff given #17559 and #23668).

**Comment by Klowner** [comment]
I realize you can pretty much achieve similar effects with a 6DOF joint, I will understand if this is not a welcomed change.

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and release freeze for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

Note: If it's merged after 3.1-stable is released, this change might be considered for cherry-picking into a later 3.1.x release.

**Comment by AndreaCatania** [comment]
Regarding the code it is fine and could be merged.

But the thing is that a "slider joint" name is something that remind me the motion in 1 direction (long a line) and add the possibility to also rotate sound weird.

For this kind of behavior we have the 6dof (that is even more stable), so for these reasons I'm proposing to not merge this PR.

**Comment by Klowner** [comment]
Sounds good to me! Thank you, Andrea.

**Comment by akien-mga** [comment]
Closing then. Thanks for the contribution nevertheless!

**Pull request closed without merging**
