### PR TITLE
Drag and drop audio files into 2D viewport to make `AudioStreamPlayer2D` nodes

### PR DESCRIPTION
**Pull request by foxydevloper**
This adds the ability to drag `AudioStream` resources into 2D viewport to add `AudioStreamPlayer2D` nodes.
This improves usability by making adding spatial 2D audio simpler by simply dragging and dropping an audio, rather than having to create the `AudioStreamPlayer2D` node, drag it's position, and then finally adding the `audio_stream`. This makes dragging and dropping files from the filesystem support more than just textures and scenes.

https://user-images.githubusercontent.com/12120644/129424485-75a95660-2875-4093-bdee-b1ac3f92c77c.mp4

A preview for the AudioStreamPlayer2D is created while dragging, even though it doesn't do anything. It would be nice if in a future PR, AudioStreamPlayer2D nodes could have a gizmo that shows it's location similar to 3D.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Needs rebase.

**Comment by Calinou** [comment]
Note that GitHub doesn't appreciate force-pushes on branches whose name contain emoji, so you may have to open a new PR with only ASCII characters in the branch naml.

**Comment by KoBeWi** [comment]
> Note that GitHub seems to ignore force-pushes on branches whose name contain emoji

Does it? I didn't have such problems. Maybe once, but I don't know if it was related.

**Comment by foxydevloper** [comment]
> Note that GitHub seems to ignore force-pushes on branches whose name contain emoji, so you may have to open a new PR with only ASCII characters in the branch name.

Yeah, this seems to be the case

**Pull request closed without merging**
