### PR TITLE
certs: Sync with Mozilla bundle as of Oct 19, 2024

### LINKED ISSUE #98851: Older unsupported releases are violating the MPL 2.0 due to a broken link
### Tested versions

- Reproducible in commits in the `master` branch that come before d9005912c17ba75e55eca786eb6e46f12a4c85e4.
- Not reproducible in d9005912c17ba75e55eca786eb6e46f12a4c85e4 and commits in the `master` branch that come after that one.

As far as I know, this problem only affects old unsupported versions of Godot. Currently supported versions of Godot are fine. I know that bug reports for old unsupported versions are usually considered invalid, but I think that this bug needs to be an exception for that rule. [We’re still distributing old versions of Godot](https://godotengine.org/download/archive/), so we need to comply with the licenses for all third-party components that are included in those old versions of Godot.

### System information

NixOS 24.05.6122.080166c15633

### Issue description

[We have to comply with version 2.0 of the Mozilla Public License whenever we distribute `thirdparty/certs/ca-certificates.crt`.](https://github.com/godotengine/godot/blob/b00e1cbf743dcb6a2b7f6bd14e348a1a7cf3d403/COPYRIGHT.txt#L182-L185) `ca-certificates.crt` is generated by a tool that converts a `certdata.txt` file into the `ca-certificates.crt` file. In this situation, [`certdata.txt` is the Source Code Form](https://hg.mozilla.org/releases/mozilla-release/raw-file/b8ea2342548b8571e58f9176d9555ccdb5ec199f/security/nss/lib/ckfw/builtins/certdata.txt) and `ca-certificates.crt` is the Executable Form. (The terms “Source Code Form” and “Executable Form” are defined in [section 1 of the MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/#definitions)).

[Section 3.2 of the MPL 2.0 says (emphasis added):](https://www.mozilla.org/en-US/MPL/2.0/#distribution-of-executable-form)

<blockquote><h3 id="distribution-of-executable-form">3.2. Distribution of Executable Form</h3>
<p>If You distribute Covered Software in Executable Form then:</p>
<ol type="a">
<li><p>such Covered Software must also be made available in Source Code Form, as described in Section&nbsp;3.1, and <b>You must inform recipients of the Executable Form how they can obtain a copy of such Source Code Form</b> by reasonable means in a timely manner, at a charge no more than the cost of distribution to the recipient; and[…]</p></li></ol></blockquote>

This means that whenever we distribute a copy of `ca-certificates.crt`, we have to make sure that we tell people how they can get a copy of the corresponding `certdata.txt` file.

At the moment, we do that by [including a link to the ca-bundle repo in `thirdparty/README.md`](https://github.com/godotengine/godot/tree/b00e1cbf743dcb6a2b7f6bd14e348a1a7cf3d403/thirdparty/README.md#certs). The way that we do it at the moment is totally fine.

---

Some old versions of Godot used a different link. Instead of linking to the ca-bundle repo, [some old versions of Godot include this link](https://github.com/godotengine/godot/blob/688228030850005f84d7b51a527bc779d76b905e/thirdparty/README.md#certs):

> - Upstream: Mozilla, via https://apps.fedoraproject.org/packages/ca-certificates

That link 404s at the moment. The correct new link is <https://packages.fedoraproject.org/pkgs/ca-certificates/ca-certificates/>. This means that we’re accidentally violating the MPL 2.0. We’re distributing copies of `ca-certificates.crt` without telling people how they can get the corresponding `certdata.txt`.

### Steps to reproduce

1. Change directory into a clone of the Godot repo:

    ```bash
    cd <path-to-godot-repo>
    ```

2. Switch to a commit that comes before d9005912c17ba75e55eca786eb6e46f12a4c85e4:

    ```bash
    git switch --detach d9005912c17ba75e55eca786eb6e46f12a4c85e4^
    ```

3. Open `thirdparty/README.md`.

4. Find the “certs” heading.

5. Try opening the link to the Fedora ca-certificates package.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by akien-mga**
https://github.com/bagder/ca-bundle/commit/4d3fe6683f651d96be1bbef316b201e9b33b274d

Include `certdata.txt` as the original source for the processed data.

I'll cherry-pick this to all Godot branches, including EOL ones, which should resolve #98851.

### CODE REVIEW

**Comment by dustdfg** [comment]
Am I correctly understand that it will affect only git repo without affecting binary at all?

**Comment by akien-mga** [comment]
> Am I correctly understand that it will affect only git repo without affecting binary at all?

There's two elements in this PR:

- `ca-certificates.crt` is updated to a newer version, this affects binaries by removing outdated CA certificates and adding new valid ones.
- `certdata.txt` is provided for documentation purposes and isn't used anywhere. It's just adding 1.5 MB of diff for the sake of satisfying a license claim I'm doubtful about, but heh /shrug

**Review by AThousandShips — APPROVED** [review]
Making the relevant file local makes sense for future proofing

**Review by Repiteo — APPROVED** [review]
Superfluous, but harmless

**Comment by akien-mga** [comment]
Actually I'll rework this, I'm having second thoughts about including a source file of cryptic data in our repo when we don't need it. Instead, I'll included the hash of the relevant Mozilla commit used by bagder in `thirdparty/README.md`.

**Comment by Jayman2000** [comment]
> Instead, I'll included the hash of the relevant Mozilla commit used by bagder in `thirdparty/README.md`.

Here’s a tip (since I had to find a bunch of these in order to add the table to the ca-bundle README): the most surefire way to find the hash is to go to [here](https://hg.mozilla.org/releases/mozilla-release/pushloghtml) and then find the push that came right before the timestamp that’s in `ca-certificates.crt`. I had originally tried doing this with `hg log` instead of the pushlog, but it didn’t work well because some commits were made on one date but then pushed to the relevant branch on a later date. The pushlog is the way to go.

**Comment by akien-mga** [comment]
Cherry-picked for all Git branches (`4.3`, `4.2`, `4.1`, `4.0`, `3.x`, `3.6`, `3.5`, etc. down to `2.1`, which is the first release with ca certificates).

**Pull request merged**
