### PR TITLE
exposing global_class access via ClassDB

### LINKED ISSUE #28929: Get the list of global classes in scripting language
**Godot version:**
master branch

**OS/device including version:**
Ubuntu 19.04

Just wanted to know how to get the list of global classes registered by `class_name`, My guess is you can only get the list from `ScriptServer` which is not exposed for scripting, Is there a way to expose methods related to global classes,

### PR DESCRIPTION
**Pull request by RameshRavone**
adding `get_global_class_list`, `global_class_exists` and exposing via ClassDB,

Usage:
```
if ClassDB.global_class_exists("CustomAction") and ClassDB.can_instance("CustomAction"):
        ClassDB.instance("CustomAction").Execute()
```

This dosn't do much in GDScript but for GDNative/PluginScript and Mono I think this can help a bit, especially if you are developing a EditorPlugin and want your user to create GlobalScript's this can help a lot,

**Edit:** Fixes #28929

### CODE REVIEW

**Comment by RameshRavone** [comment]
So, I cant force push when travis-ci is running, noted

**Comment by akien-mga** [comment]
The commits needs to be squashed.

I'd like to have @reduz's review of the `instance` changes, as it's pretty core.

**Comment by xDGameStudios** [comment]
> adding `get_global_class_list`, `global_class_exists` and exposing via ClassDB,
> 
> Usage:
> 
> ```
> if ClassDB.global_class_exists("CustomAction") and ClassDB.can_instance("CustomAction"):
>         ClassDB.instance("CustomAction").Execute()
> ```
> 
> This dosn't do much in GDScript but for GDNative/PluginScript and Mono I think this can help a bit, especially if you are developing a EditorPlugin and want your user to create GlobalScript's this can help a lot,
> 
> **Edit:** Fixes #28929

What about some methods for:

`get_children_class_list(p_class: String)` -> returns the list of global classes that extend `p_class`(directly or indirectly)

`is_global_parent_class(p_class: String, p_extends: Strings)`

**Comment by aaronfranke** [comment]
@RameshRavone Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by aaronfranke** [comment]
@RameshRavone If this is still desired, this needs to be rebased again. Also, the last time you rebased you also did a merge, while what's expected is to do a rebase and squash to only one commit. See this article for more information: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by mhilbrunner** [comment]
Similar to https://github.com/godotengine/godot/pull/52571, I think this is a good idea and useful to have. However, this needs to be rebased and squashes. As it's been gathering dust for a long time, I'm going to close it and add the `salvageable` label, because the change _is_ useful.

Sorry this has been getting stale in the backlog!

**Comment by Mickeon** [comment]
One year later, would this addition still be beneficial? 

I don't know enough about the registration internals of the engine, but why say for example, not allowing "global classes" into the `classes` HashMap itself like `ClassDB::register_extension_class()` does?

**Comment by willnationsdev** [comment]
@Mickeon That's true. It used to be that having `ClassDB` store information about stuff outside of the core engine's C++ code was explicitly rejected by reduz. Nowadays though, even the "scripting language" C# is relying on the ClassDB to store its information. On that note, I wonder if reduz or other core devs are thinking of reorganizing the `ScriptServer` into just another API layer of the `ClassDB`. Would certainly cleanup and simplify any logic that needs to differentiate between "core" classes, "extended" classes, and "scripted" classes. And if all that was done, then the only thing left for my type proposal godotengine/godot-proposals#5444 to abstract would be scenes and anonymous scripts.

**Pull request closed without merging**
