### PR TITLE
flesh out ProxyTexture class documentation

### PR DESCRIPTION
**Pull request by MJacred**
adding
* brief description
* description

adding methods
* get_width
* get_height
* get_rid
* has_alpha

adding members
* proxy
* proxy_ph

adding description for member `base`

adding bindings in `ProxyTexture::_bind_methods()`

### CODE REVIEW

**Comment by clayjohn** [comment]
Great job so far! You have done an excellent job describing the class. However, I dont think it is a good idea to expose those additional methods the way you did. ProxyTexture inherits them from Texture. So the proper place to document them is in Texture itself.

**Comment by MJacred** [comment]
> Great job so far! You have done an excellent job describing the class. However, I dont think it is a good idea to expose those additional methods the way you did. ProxyTexture inherits them from Texture. So the proper place to document them is in Texture itself.

thanks :-)
so, should I only remove the second commit?  
If you also mean changing the xml file, then I would rather keep it this way, because the proxy logic does some special things to those inherited methods, which I would like to know as a user later on (like finding out why my texture is suddenly so "small")

**Comment by clayjohn** [comment]
Hmmm. I see. The issue is the docs are auto-generated. So those sections you added will get removed the next time doctool is run. But if the behaviour is distinct, it needs to be documented.

@akien-mga, can you weigh in here? Is it problematic to re-bind those particular methods?

**Comment by MJacred** [comment]
just an idea:  
@Calinou is working on #35679, maybe they have an idea to prevent the deletion...

there's the same issue:
> Don't merge yet, --doctool needs to be modified **to not discard the schema declarations** in each XML file.

**Comment by MJacred** [comment]
As this "overwriting" is not supported yet, shall I put the methods descriptions into the class description tag so we don't lose this information? and then open an issue to enhance the documentation tool, referencing this PR?  
if so, any suggestions on how I should format the methods?  
should I remove some/all bindings (see 2nd commit)?

**Comment by Calinou** [comment]
Does ProxyTexture behave in a similar way in the `master` branch? If not, this pull request should be closed and a new pull request against `3.x` should be opened.

**Comment by clayjohn** [comment]
The only changes to ProxyTexture for 4.0 are internal and won't impact the docs. So the content here is more or less correct. However, I don't think we should be exposing methods to scripting without a good reason to. ProxyTexture is something used internally that shouldn't be used directly by users.

**Comment by Calinou** [comment]
> The only changes to ProxyTexture for 4.0 are internal and won't impact the docs. So the content here is more or less correct. However, I don't think we should be exposing methods to scripting without a good reason to. ProxyTexture is something used internally that shouldn't be used directly by users.

In this case, should we unexpose ProxyTexture entirely from the scripting API in 4.0?

**Comment by mhilbrunner** [comment]
We discussed this in today's PR review meeting. Everyone (especially other members of the rendering team Calinou and reduz) agreed ProxyTexture shouldn't be exposed anymore (and probably be removed completely, as there are now less hacky/better ways to achieve what it does in the few places its still used).

Its only used internally and easy to misuse/crash the engine with.

Thanks for your contribution, and sorry feedback has been slow on this due to the backlog pileup :) I'm going to close this one.

**Comment by MJacred** [comment]
No worries. I understand that there's loads to do

And the documentation currently lives on where there's no place in the official docs:  
https://github.com/MJacred/godot-insight/blob/main/01_internal-classes/textures/proxytexture.md (will delete it, if/once it's deleted in godot)  
Some other (non-internal) info may find its way into e.g. an official written tutorial, once it's become polished.

**Pull request closed without merging**
