### PR TITLE
Change the compiler to clang-cl.exe for MSVC when use_llvm=yes

### PR DESCRIPTION
**Pull request by object71**
clang-cl.exe is compatible with the cl.exe flags so the rest should work as before.

Tested on my own system and it compiled and ran the application. You have to have Clang for Windows installed though through the windows installer [https://llvm.org/builds/](https://llvm.org/builds/) and also add the directory to the ```PATH```. This directory is usually "C:/Program Files/LLVM/bin"

The only needed changes were to detect the clang version and to override the default cl.exe compiler with the clang-cl.exe one.

No linked issue but I hope you still find the PR useful.

### CODE REVIEW

**Comment by object71** [comment]
I think this should be all fixed. I don't know how the first-time I built it worked.

**Comment by object71** [comment]
The produced exe in debug was ~10MB less in size and ran way faster than Visual C++ build.

**Comment by fire** [comment]
Can you check the interactions with llvm and mingw.

1. use_llvm=yes use_mingw=no -> use clang-cl
2. use_llvm=yes use_mingw=yes -> use llvm-mingw
3. use_llvm=no use_mingw=yes -> use regular mingw
4. use_llvm=no use_mingw=no -> use cl

**Comment by object71** [comment]
Based on the checks:

```use_llvm=yes use_mingw=no``` -> correctly uses clang-cl.exe
```use_llvm=yes use_mingw=yes``` -> *depends* on which entry in ```PATH``` is first in the list *if you have both installed*
```use_llvm=no use_mingw=yes``` -> *depends* uses mingw (from TDM-GCC) as above depending on the fact that it is the first in the ```PATH``` between it and llvm-mingw
```use_llvm=no use_mingw=no``` -> correctly uses cl.exe

**Comment by object71** [comment]
@aaronfranke Had some conflicts and I don't have the time to resolve them. If you think it is still important copy the changes from this pull request and just go and install clang windows release from: https://releases.llvm.org/

**Pull request closed without merging**
