### PR TITLE
Provide `find_node_by_type` and `find_nodes_by_type` functions to Node

### PR DESCRIPTION
**Pull request by mateusfccp**
A possible solution for #24193.

I opted for `find_` instead of `get_` to have consistency with the already existent `find_node` function.

`find_node_by_type` has both `recursive` and `owned` parameters, but I opted to remove `recursive` from `find_nodes_by_type` because it would be either a flattened `Array` or a confusing tree-like structure. I think both are not the purpose of the function.

What do you guys think about this solution?

### CODE REVIEW

**Comment by Zylann** [comment]
Does this provide a way to get by custom types too like the issue mentions?
In GDScript you can send a class or script type directly as argument, as if the search would use the `is` keyword.

**Comment by mateusfccp** [comment]
@Zylann thanks for your feedback.

> Does this provide a way to get by custom types too like the issue mentions?

Well, I tested it and apparently not. For some reason, even when setting `class_name`, if you call `Node.get_class()` within a custom scene, it will return the root node. I know that custom scenes are not classes by themselves, as they are `PackedScene`s, but I'm going to investigate it so I can get to a solution to this issue.

> In GDScript you can send a class or script type directly as argument instead of a string, as if the search would use the `is` keyword, rather than a string which can only match engine classes.

I don't think GDScript accepts sending a class directly. The `is` operator, afaik, is a specific operator that deals with these cases, but I didn't see any other "normal" function that accepts a class name without quotes. Even `Node.is_class()`, for example, receives a `String` as param. I think making the parser understand classes without quotes in any situation is not trivial (not for me, at least). I may be wrong, tho.

> Also this does not account for inheritance, so sending `VisualInstance` won't match any derived node type like MeshInstance or ParticleSystem.

For built-in nodes, it won't account for inheritance, and I think it is indeed the desired behaviour. I wouldn't want a `Node2D` to get returned if I'm looking for a `Node`. Maybe I could provide another parameter for dealing with this, but by default I think a strict comparison is better.

> Finally, a flat array is fine because that's what the function gets (same in Unity, though its GetComponentInChildren is always recursive), bothering about hierarchy is a less common use case.

Alright, I reimplemented `find_nodes_by_type` to accept recursiveness as a param.

**Comment by Zylann** [comment]
GDScript actually can accept classes directly, which allows much more flexibility:
```gdscript
const CustomClass = preload("custom_class.gd")

func test():
	var custom_nodes = find_node_by_type(self, VisualInstance)
	var visual_nodes    = find_node_by_type(self, CustomClass)

static func find_node_by_type(parent, klass, result=[]):
	for i in parent.get_child_count():
		var child = parent.get_child(i)
		if child is klass:
			result.append(child)
		find_node_by_type(child, klass, result)
	return result
```
Which would be similar in C# with `typeof`, except interfaces woud be a matter here (like, get all nodes implementing said interface for example). But I agree that the implementation in C++ would be a bit more complex than just a string, see `gdscript_function.cpp` at `OPCODE_EXTENDS_TEST`.

**Comment by mateusfccp** [comment]
@Zylann In this last commit I updated the function based on `OPCODE_EXTENDS_TEST` so it accepts classes instead of strings.

A issue still exists on this implementation when dealing with custom scripts with `class_name`. For example, consider the following script:

```
extends Node
class_name Item

[...]
```

If I insert a `Item` as child of a `Node` and call `find_node_of_type(Node)` it will find the `Item`, as it's an extension of `Node`.

This behavior is the same as when using `is`. For example:
```
print($Item is Item) # will return True
print($Item is Node) #will return True
```
I don't know, however, if this is the best behavior for this function. What do you think about this? Should it be kept this way or should a stricter comparison be made (returning `True` for `Item` but `False` for Node)?

**Comment by Zylann** [comment]
> If I insert a Item as child of a Node and call find_node_of_type(Node) it will find the Item, as it's an extension of Node.

This would be correct because `Item` is a node, and not specific to named classes. I personally think it's a good behavior if you use inheritance or interfaces and want to gather all nodes compatible with a given type (all `GetComponent` flavours in Unity do this because it's a common usage), although I usually build those queries myself anyways because the `is` predicate is just one among a plethora of others less common ones.

Wether this should consider inheritance or not would probably be decided by the community?

**Comment by mateusfccp** [comment]
> Wether this should consider inheritance or not would probably be decided by the community?

Sure, why not? How we do this?

**Comment by akien-mga** [comment]
We discussed this on IRC today, and the consensus was that these methods would encourage bad practices that are not necessary, but also detrimental, to the handling of nodes and scenes.

There are many ways to communicate between nodes with NodePaths, signals or groups, so looking up nodes by their type is not particularly relevant, and is very inefficient.

As such we prefer to reject this PR, and if there are valid use cases which seem not to be covered by the existing best practices and features of the engine, it would be worth discussing further so that the documentation can be improved to cover them.

**Pull request closed without merging**
