### PR TITLE
Add ability to set default 2D ruler state

### LINKED ISSUE #8795: Ability to turn off the 2D Views Ruller guide permanently in Editor Settings
### Describe the project you are working on

This is for 2D projects user experience option

### Describe the problem or limitation you are having in your project

There is no way to permanently turn off the Ruller guide in the 2D view. In other software you can toggle it on or off permanently, for example Photoshop. 

I find it clutters the workspace and rarely have use for it.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I find it clutters the workspace and rarely have use for it as I'm sure many other users would say.

It would still be nice to have the option within the 2D view to toggle it on and off where necassary, but also a permanent one too.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I'm not sure the ideal location in the Editor Settings to place it, perhaps 'Editor' or 'Theme'?

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I would expect it to be straight-forward to change.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a setting location change ;)

### PR DESCRIPTION
**Pull request by timothyqiu**
Closes https://github.com/godotengine/godot-proposals/issues/8795

### CODE REVIEW

**Comment by KoBeWi** [comment]
As I said already in the proposal, adding an editor setting for something you can toggle once per project is rather meh. Especially when we don't really have other setting like that in the 2D section - everything is stored in editor layout (just like the rulers).

**Comment by timothyqiu** [comment]
Ruler state is still stored per scene. This editor setting determines the default value for ruler state.

Ruler state is currently **not** once per project. Whether to show the ruler in a new scene depends on whether the last scene's ruler is shown.

> we don't really have other setting like that in the 2D section

I can make default value for other settings also configurable if you want.

**Comment by KoBeWi** [comment]
> Ruler state is currently not once per project.

Check #74682
We could do the same for rulers.

**Comment by timothyqiu** [comment]
> Check #74682
> We could do the same for rulers.

The original proposal want to be able to set "Editor Default", and this is about implementing an auto-remembering "Project Default".

These two features operate at different levels. They can co-exist.

For an auto-remembering project default. Users still have the problem of not being able to disable auto-remembering. That does not solve the problem of the original proposal. Turning on rulers occasionally for one scene breaks the default.

**Pull request closed without merging**
