### PR TITLE
Fix Color Picker

### PR DESCRIPTION
**Pull request by MarianoGnu**
Replace shaders with procedurally generated controls

### CODE REVIEW

**Comment by akien-mga** [comment]
Only builds on X11: https://travis-ci.org/godotengine/godot/builds/169645775

**Comment by MarianoGnu** [comment]
that's not a general issue?

**Comment by akien-mga** [comment]
Ah I hadn't noticed that you wanted this merged in the gles3 branch. Then it's normal yes.

**Comment by MarianoGnu** [comment]
Just a notice: i can't fix the screen picker until the new API for taking screenshots is finished

**Comment by MarianoGnu** [comment]
@reduz not sure if this still builds, but it's mergeable yet

**Comment by MarianoGnu** [comment]
I supose gles3 branch doesn't need this PR anymore

**Pull request closed without merging**
