### PR TITLE
[Doc] Fix incorrect reference to `input_pickable`

### PR DESCRIPTION
**Pull request by AThousandShips**
Causes sphinx build on `godot-docs` to fail

### CODE REVIEW

**Comment by akien-mga** [comment]
How come there is no warning/error when running `make_rst.py`?

**Comment by AThousandShips** [comment]
Probably because there is an override in `PhysicsBody2D`, will look at the docs data

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
