### PR TITLE
Fix default script templates for non Node-derived nodes

### LINKED ISSUE #36605: Script template should have a type requirement
**Godot version:**

ed0f1940cbdbe470da85f446f315ee12897038a1

**Issue description:**

When creating a new script and selecting a type, it doesn't always match the script template type.

**Steps to reproduce:**

Create a new script and set the type to Object.

### PR DESCRIPTION
**Pull request by shubhamcodez**
I have reimplemented the changes that were initially presented in the PR #36678. 

*Bugsquad edit:* Fixes #36605.

### CODE REVIEW

**Comment by shubhamcodez** [comment]
Kindly direct me how to proceed ahead with this

**Comment by akien-mga** [comment]
The commits should be squashed together and the commit message should be amended to be more explicit about what the commit actually does. "Update $filename" is not a good description.

(Note: You can't do that with the GitHub online editor. You have to use Git locally. See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).)

Additionally, the feedback from @vnen in https://github.com/godotengine/godot/pull/36678#issuecomment-597070880 should be taken into account.

**Comment by shubhamcodez** [comment]
on it

**Comment by Calinou** [comment]
Closing per https://github.com/godotengine/godot/pull/36678#issuecomment-707190652. Please open a proposal to discuss how the template system should be updated for 4.0.

**Pull request closed without merging**
