### PR TITLE
Expose Vector2.cross(Vector2) to script / VariantCall

### LINKED ISSUE #7054: math2d cross product method not accesible
**Operating system or device - Godot version:**
Any. Godot 2.1 stable

**Issue description** (what happened, and what was expected):
Vector2().cross() method is defined in math2d.cpp but not accessible form engine itself.
3D counterpart: Vector3().cross() method works fine.

**Steps to reproduce:**
calling from within gdscript:
Vector2().cross(Vector2())
result in:
method not defined for Vector2

### PR DESCRIPTION
**Pull request by bojidar-bg**
Closes #7054 

Sorry @tagcup...

### CODE REVIEW

**Comment by tagcup** [comment]
No worries, although this might require some additional work.

2D in Godot uses a left handed coordinate system now (Y pointing down, clockwise rotations), but I haven't fixed the definition of cross and tangent to be consistent because physics engine, which is the main user of cross, is oblivious to that.

Long story short, from user's perspective, currently, cross will not do what they may expect it should do when it comes to orienting/rotating stuff on screen.

**Comment by tagcup** [comment]
After considering this, I don't think it's a good idea after all, even from a practical point of view. For users to get this right, they have to embed 2D into the xy-plane in 3D, but in a left-handed coordinate system whereas the 3D engine in Godot is using a right-handed coordinate system. To me, this just sounds confusing.

And I still don't understand why `Vector2::tangent` and `rotate` aren't sufficient.

**Comment by bojidar-bg** [comment]
@tagcup Since I can't see how useful `::tangent` is, can you give an example for how `::tangent` and `::angle_to` can be used to decide in which direction to rotate in order to reach a target vector? (e.g. an enemy turning to face the player)

**Comment by tagcup** [comment]
You don't need tangent for [that](https://github.com/godotengine/godot/issues/7054#issuecomment-261556925), it's just `angle_to_target = (object.get_pos() - self.get_pos()).angle_to(self.direction)`.

`angle_to` gives the angle measured from the first vector to the second, so it's signed.

**Comment by tagcup** [comment]
Ah, I guess we should clarify the documentation for `angle_to` because that isn't clear from the [current docs](http://docs.godotengine.org/en/stable/classes/class_vector2.html):

> float angle_to ( Vector2 to )
> Returns the angle in radians between the two vectors.

This almost sounds like `acos(a.dot(b))`, which of course is not the case. I'm planning to go over the math-related docs before 3.0, so I'll expand the description.

**Comment by bojidar-bg** [comment]
@tagcup Ah, ok, I always assumed angle_to would be only positive, but if it isn't, I would be happy to take back my claims about `::cross` (on a side note, does it _hurt_ to add it, given that work was already done?).

**Comment by tagcup** [comment]
> on a side note, does it hurt to add it, given that work was already done?

Adding stuff in a math library just because it doesn't hurt doesn't sound like a good argument to me either. 

I already made my case against it in #7054 so I'll just refer to it.

**Comment by akien-mga** [comment]
I agree with @tagcup, also "doesn't hurt" is not necessarily true based on the above discussions: math libraries using incorrect definitions *are* hurtful, especially if they hide the right way to achieve the same result.

**Pull request closed without merging**
