### PR TITLE
Add signal support to Godot Android plugin

### LINKED ISSUE #537: Why we don't have emit_signal in java SingletonBase?
**Describe the project you are working on:**
Many godot modules and plugins for godot 3.1/3.2, for iOS, Android and pure C++

**Describe the problem or limitation you are having in your project:**
When I write C++/Obj-C classes I can use emit_signal in order to organize native to gdscript communication. When I get java code the only method I have is to use calldeferred, which not so powerful as emit signals.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add very simple piece of code to GodotLib and SingletonBase. It must not be complicated because JNISingleton already is a child of Object and have ability to emit signals.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
```
public class SomeJavaModule extends Godot.SingletonBase {
  // ...
  private void someInternalMethod() {
    emit_signal("signal_which_can_be_connected_by_gd_script_code");
  }
  // ...
}
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It can be replaced with calldeferred, but it leads to very complicated gd script logic (which becames platform dependent and react by different ways in iOS and Android)

**Is there a reason why this should be core and not an add-on in the asset library?:**
There are no ways to implement this in any external plugin/module/asset.

### PR DESCRIPTION
**Pull request by m4gr3d**
Supports registering and emitting signal from a Godot Android plugin.

Fixes godotengine/godot-proposals#537

[Sample project](https://github.com/m4gr3d/Godot-Android-Plugins/tree/master/hello_signals)

[3.2 backport](https://github.com/godotengine/godot/pull/37305)

### CODE REVIEW

**Comment by m4gr3d** [comment]
cc @DrMoriarty

**Comment by akien-mga** [comment]
Needs a rebase, otherwise seems good to me.

**Comment by m4gr3d** [comment]
> Needs a rebase, otherwise seems good to me.

@akien-mga Done!

The [3.2 backport](https://github.com/godotengine/godot/pull/37305) (needed because of the new `Callable` class in `master`) is also ready to go.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
