### PR TITLE
Change RayCast3D gizmo to arrow

### LINKED ISSUE #19793: Raycast3D is very hard to see in editor
**Godot version:** v3.1 c861756

**Issue description:**
Raycast3D gizmo is almos impossible to view if it overlaps with the axis. It also z-fights with the axis.
My proposal is to have a more visible gizmo for the raycast node.

image
image

### PR DESCRIPTION
**Pull request by Mielek**
Fixed #19793
Changed gizmo to arrow shape as @QbieShay suggested in the issue and @Calinou suggested in #33103.
Arrow looks the same like for directional light. Small ray cast length (less then 1 unit) scale whole gizmo. For gizmos with length greater than 1 unit arrow head is not scaled.

My only concern is if it is still usable for long ray casts (like 50 and more).

It it is ok (or would be after review) maybe would it be a good idea to move this code to EditorNode3DGizmo than we could reuse it for directional light.

### CODE REVIEW

**Comment by mbrlabs** [comment]
@Mielek I don't know about this one. If it's as wide as the arrow for the directional light, people might assume the raycast has some kind of radius. In my opinion a simple line is the best representation for a raycast (it could be a bit thicker tough) because you can see the exact point where it's colliding. Assume for example, that the ray head is inside an object: now you would have to eyeball the center of the arrow body to determite the collision point.

Maybe i'm wrong and it looks fine. Could you post some screenshots in action?

**Comment by Mielek** [comment]
@mbrlabs Thanks for the remarks!

Arrow is not as big as for directional light. Here you have a comparison.  image

I see your point. I think it would be a problem in super-precise cases. Here you have a screen where I ray cast from inside one box to the inside of another. 
image

I have done some resizing and gizmo could look like in the following screens.
image
image

Still, if you zoom into the arrow shaft you will see
image

I have prepared another variant that uses a cylinder mesh but does not contain an arrow tip.
image
image


Please let me know which of these propositions is the best one.

**Comment by Cykyrios** [comment]
I like the thin arrow as it helps see the raycast from afar without making it too large, but I think you should also keep the central line for more precise visualisation. I would avoid the cylinder mesh as its diameter could become a problem depending on the zoom level.

I vote for the thin arrow + the current line (maybe slightly thicker).

**Comment by mbrlabs** [comment]
Very nice, thank you! I prefer the cylinder because it looks cleaner than the arrow variants. If you go for the arrows a would choose a size in between the arrow in your first screenshot and the very thin one.

@Calinou What do you think?

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/46529 (which provides more features). Thanks for the contribution nonetheless!

**Pull request closed without merging**
