### PR TITLE
Fixed exception call in modules/mono/config.py

### PR DESCRIPTION
**Pull request by Teashrock**
Fixed absent variable exception while trying to raise another exception.

### CODE REVIEW

**Comment by akien-mga** [comment]
The fix is good but the commit title should be more explicit than `config.py`. A commit title should be short (that part is fine ;)) but also descriptive, so that we can understand what a commit does when reading it.

I guess you've used the GitHub web editor which encourages such bad commit logs, so I won't bother you with a rebase, I'll merge it manually and edit the log myself.

**Comment by akien-mga** [comment]
Merged as 51a0a381.

**Comment by Teashrock** [comment]
Thank you!

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request closed without merging**
