### PR TITLE
[4.0] [tvOS] Basic tvOS Support

### PR DESCRIPTION
**Pull request by naithar**
Same as #45829 for `master` and basic Metal Support (via MoltenVK)

> 
> Added **basic** tvOS support.  
> Implements already closed but not implemented proposal: https://github.com/godotengine/godot-proposals/issues/224
> 
> Platform code is based on iOS platform code with minor changes (some iOS stuff isn't available on tvOS). 
> Audio interruption was also removed - AppleTV don't seem post interruption notification correctly or in right order, which results in game freezing after application loses focus. 
> Keyboard input backed was changed so keyboard input actually works.
> Input is handled by controllers. Apple/Siri Remote are also considered controller (micro)
> 
> Export code (including plugins) is also based on iOS platform since both of them export into Xcode project. 
> But export is also simpler: 
> * Launch screen is storyboard based (no need for launch images)
> * tvOS project supports empty Apple Team ID
> * Icons, Signatures and certificates are handled by Xcode project
> 
> Core code has been modified to address tvOS unsupported features - no `fork` and `execvp`.
> Rendering code has been modified for tvOS to use same paths/methods as iOS's. 
> 
> Mono haven't been ported.
> GDNative uses same configuration as iOS platform.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Is there an option to change this so the iOS platform can be used or is this a case once again that Apple will flat out reject your bundle if it contains code not applicable to the platform you're deploying on?

It feels very messy to have a complete duplication of the iOS platform just to apply a few minor changes. It will be a nightmare to keep them in sync.

**Comment by naithar** [comment]
> Is there an option to change this so the iOS platform can be used or is this a case once again that Apple will flat out reject your bundle if it contains code not applicable to the platform you're deploying on?
> 
> It feels very messy to have a complete duplication of the iOS platform just to apply a few minor changes. It will be a nightmare to keep them in sync.

We could probably try hiding platform's tvOS/iOS only methods behind `TVOS_ENABLED` flag as well as using objc availability API - this would allow to use same `godot_view` for both platforms. We can probably also use some stuff without changes that's currently are the same between platforms - `joypad` should be among them. But I'm not sure how well it could be supported/scaled if thing become more separate between this platforms. There are also plugin that can only partially be migrated without changes.
Xcode project also should be separate - there are stuff that don't share as well as works differently. We can probably work it out by using targets, but it would really be a mess to support.
And I'm also not sure how App Store will react to it - fighting bitcode stuff is hard already :)

**Comment by paulo-coutinho** [comment]
When i submit a version to apple (Apple TV) i got this problem. Can anyone check it this problem still?

https://github.com/godotengine/godot/issues/46565

**Comment by naithar** [comment]
Coming back to this PR I now think, that keeping single code base might be a better solution after all. 
But would it be possible to have two different exporters for iOS and tvOS in this case?

**Comment by akien-mga** [comment]
> Coming back to this PR I now think, that keeping single code base might be a better solution after all.

If we can keep a single code base that would look much better to me indeed, like we do with Linux/FreeBSD/OpenBSD/NetBSD.

> But would it be possible to have two different exporters for iOS and tvOS in this case?

Depending on how similar the export presets would be, this could be hacked in like it's done for JavaScript's three separate templates (regular, threads, gdnative) to have a checkbox or an enum to select tvOS support while using the common preset.

If the presets need to be fully separate, then some additional work might be needed. That's probably something we want to consider anyway if we ever want to provide some official form of support for *BSD platforms (currently to export for those platforms you have to replace the Linux templates by custom builds made for the BSD platform you want to target), or for Linux embedded (Raspberry Pi, etc.).

**Comment by naithar** [comment]
> If the presets need to be fully separate, then some additional work might be needed. That's probably something we want to consider anyway if we ever want to provide some official form of support for *BSD platforms (currently to export for those platforms you have to replace the Linux templates by custom builds made for the BSD platform you want to target), or for Linux embedded (Raspberry Pi, etc.).

tvOS and iOS export template are completely separate, but I think it should be pretty simple to register both platform-specific exporters. The way `register_exporters.gen.cpp` is generated is pretty descriptive and it shouldn't be hard to do in the end. 

The only problem I see right now is `detect.py` file that is made specifically for iOS export. I don't see any way of changing methods like `can_build`, `get_name` to support both platforms in single configuration.

**Comment by paulo-coutinho** [comment]
Hi,

Any news when it will be available?

**Comment by michael-garofalo** [comment]
> Any news when it will be available?

I stumbled on this thread while researching why someone would pick Godot Engine over other game development software. I think the better question is, "What needs to be done?"

So far, I see a few issues...

> And I'm also not sure how App Store will react to it - fighting bitcode stuff is hard already :)

Heh, that's a constant issue with Apple. 😄

I think that's a testing problem. Someone is going to have to try and get their game through Apple's review process. Actually, probably a few someones, to show that Apple TV games built with Godot Engine are consistently approved.

But, it looks like this Pull Request needs some work first. I'm not quite sure where it's at.

> The only problem I see right now is detect.py file that is made specifically for iOS export. I don't see any way of changing methods like can_build, get_name to support both platforms in single configuration.

So, if I'm understanding this correctly, it looks like there's a debate of a single iOS / tvOS codebase, but there's a blocker with configuration. New to this, I had to figure out what that meant... is this an issue with Swift / Xcode or Godot Engine. Apparently, [after seeing this webpage](https://docs.godotengine.org/en/stable/development/cpp/custom_modules_in_cpp.html#creating-a-new-module), it's the latter.

I don't think I'll be able to help with that problem right now, as I should actually try installing the Godot Engine first. HA HA! 😄

...but this is interesting! It looks like it's a milestone for version 4.0 — nice!

**Comment by paulo-coutinho** [comment]
Hi,

I have two games running on my Apple TV, but godot don't publish support for it.

There is any way to get a recent editor version with tvos support?

Thanks.

**Comment by naithar** [comment]
@paulo-coutinho you should be able to fork and build editor and template using branch from this PR https://github.com/godotengine/godot/pull/45829. 
It might be necessary to rebase from Godot's `3.x` before building to have all newest features and changes.

**Comment by naithar** [comment]
Superseded by https://github.com/godotengine/godot/pull/58976 and https://github.com/godotengine/godot/pull/58977

**Comment by paulocoutinhox** [comment]
Hey,

Nice work.

@rsanchezsaez There is any guy in Apple team to add the AppleTV support? 

Im waiting for AppleTV for years.

I want migrate to Godot but my games runs on AppleTV:
- https://apps.apple.com/app/game-mania-world/id6504422874

**Pull request closed without merging**
