### PR TITLE
Preserving "Sync Scene Changes" & "Sync Script Changes" with Project Settings

### LINKED ISSUE #38739: About sync script change remember
**Godot version:**
3.2
**OS/device including version:**
windows
**Issue description:**
Regarding synchronization script changes, the last setting will not be remembered.
**Steps to reproduce:**
debug setting click sync script change
**Minimal reproduction project:**

I want to disable synchronous script changes, but every time I open the editor, it starts by default

### PR DESCRIPTION
**Pull request by dreamsComeTrue**
Fixes: #38739

### CODE REVIEW

**Comment by Calinou** [comment]
Should this be a project setting or an editor setting? I'm not sure if you'd want the setting to enabled only for certain projects but not for others.

**Comment by dreamsComeTrue** [comment]
Yeah - with how that was developed currently - it's tied to Project actually, maybe we could ask @Faless what was his intention in here?

If that's needed I could try converting that to Editor settings as well :)

**Comment by akien-mga** [comment]
This prevents having them forced on, but doesn't it also make them default to not being enabled? If so that's not a good change, we want them to be enabled by default. But if users decide to override the default, it would be good to remember it indeed (but the same applies for other settings).

**Comment by dreamsComeTrue** [comment]
OK, changed functionality in a way, that - when never selected - always default to 'true' for both properties, but when changed to 'false' or 'true' again - it will persist that state in project's '.cfg' file :smiley:

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
