### PR TITLE
Move display driver functionality from `OS` to new `DisplayDriver` singleton

### PR DESCRIPTION
**Pull request by wmww**
* Rename `x11` platform to `freedesktop` (name negotiable, please please *please* do not bikeshed this name until everything else has been discussed and we are ready to merge).
* Add `DisplayDriver` singleton
* Remove display driver functionality from `OS`
* Add X11 display class to be used with the freedesktop OS
* Adapt other platforms to inherit from both `OS` and `DisplayDriver`

This abstraction is the first step toward mainline Wayland support, compositor projects with Godot. I believe this to be roughly what @hpvb is planning to do. If this is not the right direction, please let me know so I don't sink more time into it. Lets look at this rather quickly if possible, as it is a high maintenance branch to keep updated.

EDIT: please note that this is not ready to merge. I posted the PR so we can discuss the approach and what direction to take it.

### CODE REVIEW

**Comment by fire** [comment]
Will the functionality to disable the display driver for "server" builds be made in this patch?

**Comment by wmww** [comment]
@fire I'm just leaving `OS_Server` basically as is: a separate platform with the display functions stubbed out. This patch should make future improvements to the server system easier, but that's out of scope here.

**Comment by wmww** [comment]
I've now resolve most of the issues and gotten CI passing

**Comment by wmww** [comment]
`LinuxBSD` beat `Freedesktop` by a landslide (https://github.com/godotengine/godot/pull/27266#issuecomment-480278935), so @ddevault updated #27266 to use it (yay democracy!). He also kindly rebased this branch onto that one, which is good because I missed a few things in my original `X11` -> `Freedesktop` rename.

I've now removed the splitting out of `DisplayX11` from `OS_LinuxBSD`. That will come in a later PR, this one is large enough as-is.

I hope someone can take a look at #27266 so we can get both that and this merged.

**Comment by aaronfranke** [comment]
> EDIT: please note that this is not ready to merge. I posted the PR so we can discuss the approach and what direction to take it.

@wmww By the way, GitHub has [draft pull requests](https://github.blog/wp-content/uploads/2019/02/draft-pull-requests.png?w=1354) now.

**Comment by akien-mga** [comment]
Superseded by #37317, but thanks for the contribution nevertheless!

**Pull request closed without merging**
