### PR TITLE
TimeSeek node in AnimationTreePlayer now propagates filters

### PR DESCRIPTION
**Pull request by m4nu3lf**
There was a bug with the TimeSeek node not propagating filters down the tree. Fixed.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@m4nu3lf Please rebase the merge commit out of the PR.

**Comment by m4nu3lf** [comment]
@bojidar-bg Sorry about that, Can you instruct me how to do that on github?

**Comment by slapin** [comment]
you do that locally, not on github.

**Comment by m4nu3lf** [comment]
@slapin I've done that locally, but now how do I reflect that in the pull request?

**Comment by slapin** [comment]
just force push it using
git push origin +branch1:branch2

where origin is remote name
branch1 - local branch name you're pushing
branch2 - remote branch name

You also can do

git push origin +branchname
if your remote and local branches have the same name.

if you don't know your remote name you can use
git remote

to list them.

If you did not add your repository to remotes, then you can use direct
repository specification, like

git push git@github.com:username/repo.git +branchname

(just replace origin with repo spec)

The branch used is the one you specify when made PR, this will update your
PR with new data.

**Comment by m4nu3lf** [comment]
I screwed thigs up, please delete this pull request, I will reopen a new one ( after I learn how properly rebase)

**Comment by vnen** [comment]
Git can be hard to learn but you didn't have to close the PR, much less to delete your fork. I hope you can send another PR soon.

**Pull request closed without merging**
