### PR TITLE
[3.x] Fix Array.Shuffle incorrect mono bindings

### LINKED ISSUE #60840: Array Shuffle() in C# HTML5 fails with no evident error.
### Godot version

3.4.4.stable.mono.official

### System information

Ubuntu 22.04 GTX1060 I58400 16GB-RAM GLES3

### Issue description

The Shuffle() function used to randomize an Array object doesent work with c# on HTML5

### Steps to reproduce

Create a new project, add a script to any node, and test this:

```csharp
public override void _Ready()
{
    Array<int> arr = new Array<int>();
    arr.Add(3);
    arr.Add(1);
    arr.Add(4);
    arr.Shuffle();
    GD.Print(arr);
}
```

Try running it on the browser via export or by clicking "Run in Browser" in Godot.

### Minimal reproduction project

[testing-sandbox.zip](https://github.com/godotengine/godot/files/8644389/testing-sandbox.zip)

### PR DESCRIPTION
**Pull request by dzil123**
Fixes #60840

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Is this need in 4.0 too or are the bindings correct there?

**Comment by dzil123** [comment]
The crash only occurs in 3.x javascript.
4.0 does not have mono for web implemented yet, so I don't know if this same bug would happen there.

I suspect that the `internal static extern` signature mismatch is not causing the crash, but I haven't tested it by itself.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2

**Pull request merged**
