### PR TITLE
Export vulkan instance process address function.

### PR DESCRIPTION
**Pull request by RechieKho**
Hi. I am the creator of [iree.gd](https://github.com/RechieKho/iree.gd), a project that brings [IREE](https://github.com/openxla/iree), another project that makes running AI models natively possible, into Godot through the GDExtension. The runtime uses vulkan to accelerate execution of AI model. In order to use the vulkan device that is running in Godot, Godot's `vkGetInstanceProcAddr` is required. If we are going to create another vulkan device on our own, it is very likely to produce [crash](https://github.com/RechieKho/iree.gd/issues/11).

This is not a very big change, just exporting `vkGetInstanceProcAddr` so it is accessible in GDExtension.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You need to add documentation, see the tests

**Comment by RechieKho** [comment]
I have done adding documentation...

**Comment by RechieKho** [comment]
Poke @clayjohn.

**Review by BastiaanOlij — APPROVED** [review]
Can't think of a better way to share this, would like @clayjohn opinion on this before this gets merged. `get_driver_resource` is the correct place I think.

**Comment by clayjohn** [comment]
I don't think this needs to be exposed to do what you want to do. ``vkGetInstanceProcAddr`` is not a driver resource. It is a driver-defined function that is dynamically loaded by the Volk library. You can get the exact same function through whatever Vulkan loading utility you are using in your extension (or by using dlopen/dlsym/GetProcAddress yourself).

You already have access to the device and the instance in case you want to share those with Godot. ``vkGetInstanceProcAddr`` just allows you short circuit the loader that Godot uses and avoid using a loader yourself

To me, exposing this seems like a hacky workaround that is only really usable from C++ (as I doubt the C++ function pointer is functional when accessing from other languages)

**Pull request closed without merging**
