### PR TITLE
Fix shader tokenizer-parser reporting wrong error location

### PR DESCRIPTION
**Pull request by RandomShaper**
Keeping the commented line, adapted to the new flow, should it be needed sometime.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @reduz for potential manual cherry-pick, as he completely reworked shaders in the gles3 branch.

**Comment by akien-mga** [comment]
Let's keep this one open until the gles3 branch is merged in master, and assess then if it's still needed/how to rebase. In the meantime, do you think you could make another PR with those changes for the 2.1 branch?

**Comment by RandomShaper** [comment]
It's #6988.

**Comment by RandomShaper** [comment]
Why a PR for 2.1 for this specific case? Is sill any hope of seeing Godot 2.x (or 2.1.x) released?

**Comment by akien-mga** [comment]
Well we need a non-master branch if we want a 2.1.1. This branch is named 2.1. Master is for 3.0.

**Comment by akien-mga** [comment]
And yes I'll be releasing 2.1.1 tomorrow.

**Comment by RandomShaper** [comment]
Then shall I submit more 2.1-ready variants of my PRs for master, at least some of them?

**Comment by akien-mga** [comment]
I've already cherry picked some of them, but if you think I omitted some that would benefit the stable branch and can't be easily cherry picked, please do.

**Comment by RandomShaper** [comment]
I think you have cherry-picked everything relevant but this one: fae6dbc7f3dccbf001b03395703979f79c6effd8

**Comment by akien-mga** [comment]
> I think you have cherry-picked everything relevant but this one: fae6dbc

I did not cherry-pick it because it doesn't apply, and looking deep into the details it seemed to not be needed for the 2.1 code chunk.

```diff
godot.git (2.1|CHERRY-PICKING)]$ git diff
diff --cc main/input_default.cpp
index 371bf10,e5d8533..0000000
--- a/main/input_default.cpp
+++ b/main/input_default.cpp
@@@ -451,11 -500,13 +451,21 @@@ void InputDefault::action_press(const S
  
  void InputDefault::action_release(const StringName& p_action){
  
++<<<<<<< HEAD
 +      ERR_FAIL_COND(!custom_action_press.has(p_action));
 +      custom_action_press[p_action]--;
 +      if (custom_action_press[p_action]==0) {
 +              custom_action_press.erase(p_action);
 +      }
++=======
+       Action action;
+ 
+       action.fixed_frame=OS::get_singleton()->get_fixed_frames();
+       action.idle_frame=OS::get_singleton()->get_idle_frames();
+       action.pressed=false;
+ 
+       action_state[p_action]=action;
++>>>>>>> fae6dbc... Fix Input.action_release() marking action as pressed
  }
  
  void InputDefault::set_emulate_touch(bool p_emulate) {
```

**Comment by akien-mga** [comment]
Is this one still relevant now that the GLES3 branch was merged?

**Comment by RandomShaper** [comment]
This only applies now to 2.x.

Do you need me to reopen this for the 2.1 branch or can you merge there directly?

**Comment by akien-mga** [comment]
We merged it in 2.1 already: #6988 ;)

**Comment by RandomShaper** [comment]
Oh, even better! :D

**Pull request closed without merging**
