### PR TITLE
Polyline

### PR DESCRIPTION
**Pull request by Zylann**
Added a Line2D node that draws a polygon-based line.
It supports unlimited width, color gradient, texture and some geometry options for joints and caps. Also transparency without artifacts (provided that line joints aren't too sharp).

~~Points cannot be visually edited yet because I have to figure out how to do that without duplicating too much similar code from existing editors (polygon2d, shape2d...).~~
Some features can be added over time such as variable width (would be nice to provide that through a FloatCurve resource) and more texturing options.

EDIT: points can be edited now :)

The logic that builds the line can be re-used for a future Trail2D node.

### CODE REVIEW

**Comment by akien-mga** [comment]
Any chance you could rebase to group some of those commits together? 22 commits for +396 lines on a single topic are a lot :)

**Comment by akien-mga** [comment]
> Any chance you could rebase to group some of those commits together? 22 commits for +396 lines on a single topic are a lot :)

Ping.

**Comment by Zylann** [comment]
Last time I wanted to update my code for latest but it wasn't compiling.
I'm doing it now, but I had to merge a few things (some of which aren't related to Line2D)

**Comment by mefihl** [comment]
Please add this for Godot 2.1.x

**Pull request merged**
