### PR TITLE
Add resource picker operation "Make Unique (Recursive)"

### PR DESCRIPTION
**Pull request by Geometror**
This PR adds a "Make Unique (Recursive)" option to the context menu of the resource picker.
I often duplicate a resource and use it as a base to make some adjustments (example: StandardMaterial with many different NoiseTextures). But having to click on "Make unique" on every subresource (and the subresources's subresources, ...) feels really inconvenient. Adding a option to recursively duplicate the selected resource aims to significantly improve this workflow.

Detailed changes:
- Add a context menu item "Make Unique (Recursive)" to EditorResourcePicker and EditorResourceConversionPlugin
    [only shown in case the selected resource has subresources]
- Simplify the implementation of "Make Unique" to use the `duplicate()` method

grafik

### CODE REVIEW

**Comment by fire** [comment]
The enhancement is great. I implemented this another place too.

**Comment by fire-forge** [comment]
@Mickeon I agree, that's a good idea. If the resource has no sub-resources then the button could either be disabled or not show up at all.

**Comment by Geometror** [comment]
Implemented the suggestion, now the context menu entry is only shown in case the selected resource has subresources.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Looks ok, but it needs rebase because CustomPropertyEditor is gone.

**Comment by Geometror** [comment]
Rebased. There were some suggestions to replace this functionality with a flexible dialog to choose which subresources should be copied exactly (godotengine/godot-proposals#4503), but I guess that can be added at a later time if desired. The purpose of this PR is to provide a very quick one-click solution to duplicate all subresources (if you wan't to share some of them, you can work "subtractively" from there) and I think that works fine for most cases.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
