### PR TITLE
Add optional snap & global/local coordinates controls in the 3D editor toolbar/viewport

### PR DESCRIPTION
**Pull request by guzzard**
- button to toggle between global and local coordinates
- buttons to enable/disable translation, rotation, scaling snap
- menus to quickly set common snap values
- remove "Use Snap" in Transform menu, and add check button for snap translation, rotation, scaling
- added simple validation of snap configuration window values
- added icons for the new buttons that look different from the tool buttons, to not confuse users
- added sub-menu in Translate menu to show/hide the toolbar controls + choose which side the controls should be shown (so the user can set according to preference)
- state for snap buttons/values are saved/restored in the scene
- state for the transform toolbar control visibility and position (left/right/viewport) is saved in the editor preferences
- default behavior is that the controls are visible and shown to the left with the other menu controls.

3D viewport transform toolbar controls - controls demo video: https://youtu.be/pTm1JnmgFEU
3D viewport transform toolbar controls - Left/right + show/hide demo video: https://youtu.be/mLHFWdGR840

Related issue: https://github.com/godotengine/godot/issues/4850

Please review and let me know the things that need to be corrected or changed. I'm sure there are things I didn't think about since this is the first time I looked into the source code.

The scale and global/local coordinate icons are open source and without attribution. The grid and rotation icons are made by me and can be used without attribution.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@djrm ~ Just to note, if this get merged, you will have to make a few additional icons :smile:

**Comment by djrm** [comment]
No problem, just open an issue in the design repo and i will work on that

**Comment by Hinsbart** [comment]
> state for all the buttons/values are saved/restored in the scene

@guzzard, Does that include the toolbar hidden/left/right information?
I think that wouldn't be so nice to version control systems. Especially after all the work to get meta-information out of scenes :p

**Comment by bojidar-bg** [comment]
If it is just snap values (maybe without on/off), it would be nice to be part of the scene indeed. Otherwise, it is waste of diffs.

**Comment by guzzard** [comment]
@Hinsbart @bojidar-bg state is saved for hidden/visible, left/right, translation snap on/off, translation snap value, rotation snap on/off, rotation snap value, scaling snap on/off, scaling snap value. Please note that the only new states that are saved is for the hidden/visible + left/right. In current version (stable and git master) state is saved for snap on/off, translation snap value, rotation snap value, scaling snap value.

**Comment by Hinsbart** [comment]
Mhh, for me personally it kinda makes sense to have the snap on/off values saved in the scene.
The toolbar positioning however is def. a matter of preference and should, IMO, be moved to the editor settings.

**Comment by vnen** [comment]
BTW, if this is merged, it'd be cool if you add some instructions to the docs (like in the [3D introduction tutorial](http://docs.godotengine.org/en/latest/tutorials/3d/introduction_to_3d.html)).

**Comment by guzzard** [comment]
@Hinsbart changed so that state for visibility and and position is saved in the editor prefs. The settings are stored in global, since the plan is to add these controls to the 2D editor as well. Let me know you rather have two sets of settings in 3d editor + 2d editor and I will change that.

@vnen yes, documentation for this would be very good to have. I can look into adding the documentation after finishing the implementation parts (unless someone else is interested in writing the documentation?).

**Comment by reduz** [comment]
sorry, I'm still not convinced about this, will think more about how it could be eventually added. 
We'll be doing a lot of changes to the 3D viewport after 2.1 and will review this PR again then

**Comment by guzzard** [comment]
@reduz ok, please consider having it as an overlay in the viewport (only one time regardless of 1/2/3/4 viewports) as I initially proposed in issue #4850, similar to how it's done in UE4. It works very well and doesn't take up any space in the toolbar etc.

**Comment by guzzard** [comment]
Added back so that it's possible to choose to have the controls in the viewport as well. @reduz I don't know if this makes you any more inclined to merge the PR, but please have a look and see what you think :smiley:.

deepinscreenshot20160609001035

**Comment by guzzard** [comment]
@akien-mga @reduz let me know if there is any point in my spending time rebasing this pull request, or if I should close it. I rather not spend any more time on it if it won't get merged.

**Comment by guzzard** [comment]
@reduz @akien-mga would you like me to update and rework this so it can be merged into 3.0? If yes, is there anything you want me to change/add/remove regarding the functionality or in the implementation in the code?

**Comment by groud** [comment]
To sum up my point of view on this PR:

> button to toggle between global and local coordinates

This is definitely needed

> buttons to enable/disable translation, rotation, scaling snap
> remove "Use Snap" in Transform menu, and add check button for snap translation, rotation, scaling

I think a single button, activating / deactivating all snap mode should be kept. Having these as separate modes is a little bit heavy and not that useful, I would say.

> menus to quickly set common snap values

Why not for translation / rotation, but I think that for scaling this is not that useful.

>  added sub-menu in Translate menu to show/hide the toolbar controls + choose which side the controls should be shown (so the user can set according to preference)

I'm not ok with that, nothing in the editor has movable buttons. If we start with those we should be able to configure every button position. This is too much work for now.

I think for now only the local / global button should be merged. But it should be split into another commit.

**Comment by guzzard** [comment]
@reduz @akien-mga @bojidar-bg @groud; based on the feedback on IRC, as well as the feedback from groud above, would either of below suggestions be acceptable? It would give the user options what to show, and it would be possible to set the defaults as you like when shipping Godot.

ui_snap_suggestion

**Comment by groud** [comment]
Well, all those are interesting but still. I think this whole configuration is very complicated...
First, we do not want to add buttons to hide/show other buttons. This bloats the gui for nothing. If we would need those that means that the GUI is not well designed.

Regarding those changes: I think we need a precisely configurable grid snapping, but this is pretty useless for rotation or scale, where in most case we are going to need 45° / 22.5° angles or x2/x1.5 snappign for snaling. 
I think we should have:
- A snap button to activate snapping (for all modes),
- A menu or a button to configure the grid,
- Eventually an other menu called somehow like "snapping precision" which may increase/decrease the snapping precision

**Comment by SaracenOne** [comment]
While there is a great deal of complexity behind this PR, I do hope it manages to get merged. I'm particularly interested in the concept of object-relative snapping.

**Comment by n-pigeon** [comment]
Same. It is a bit over the top with some solutions i.e. different settings for button layout placement, but there are many useful features.

**Comment by volzhs** [comment]
@guzzard are you still there?

**Comment by guzzard** [comment]
Hi @volzhs, yes I'm here, but I will not spend anymore time on this pull request. I think you would have a much better chance of getting something pulled since you are a Godot team member. Please feel free to take the code and make something useful out of it, if possible.

**Comment by n-pigeon** [comment]
I forgot about this PR. It is amazing >_>

**Pull request closed without merging**
