### PR TITLE
Calculate gravity based on distance from body to gravity point

### PR DESCRIPTION
**Pull request by Faless**
This patch allows to scale the gravity applied by a gravity-point Area/Area2D based on the distance from the gravity-point to the body, thus simulating the basic law of gravitation.

The formula applied is:
gravity = area_gravity / (distance \* scale_factor + 1)^2
This ensures that the maximum gravity applied cannot be more then the user specified one (and avoid good old divisions by zero).
If scale factor is 0 (default) the usual system (no distance scale) is applied.

You can test the patch with the following demo:
https://github.com/Faless/godot_demo
Notice specifically the differences between demo 1 and 2 and demo 3 and 4

### CODE REVIEW

**Comment by ryanpeach** [comment]
I'm looking for a way to turn this math into standard gravitational form, and unfortunately this +1 really gets in the way...

https://www.wolframalpha.com/input/?i=u+*+m+%2F+r%5E2+%3D+x+*+y+*+m+%2F+%28r+*+s+%2B+1%29%5E2+solve+for+u

**Comment by ryanpeach** [comment]
Notice the distance r in that equation can't be factored out to match the standard gravitational equation. Whereas without the 1 it can be:

https://www.wolframalpha.com/input/?i=u+*+m+%2F+r%5E2+%3D+x+*+y+*+m+%2F+%28r+*+s%29%5E2+solve+for+u

**Comment by ryanpeach** [comment]
I propose this instead to avoid divide by zero

```
	const float vlength = v.length()

	if (p_area->is_gravity_point()) {
		if (p_area->get_gravity_distance_scale() > 0 && vlength > 0) {
			Vector2 v = p_area->get_transform().xform(p_area->get_gravity_vector()) - get_transform().get_origin();
			gravity += v.normalized() * (p_area->get_gravity() / Math::pow(vlength * p_area->get_gravity_distance_scale(), 2));
		} else {
			gravity += (p_area->get_transform().xform(p_area->get_gravity_vector()) - get_transform().get_origin()).normalized() * p_area->get_gravity();
		}
	} else {
		gravity += p_area->get_gravity_vector() * p_area->get_gravity();
	}
```

**Comment by Faless** [comment]
I agree that the math in this patch was wrong (too hacky, since such an
approximation causes precessions in orbits).
Please open a PR with you proposed changes so we can discuss it there.

**Pull request merged**
