### PR TITLE
fix missing < in Info.plist

### PR DESCRIPTION
**Pull request by icnikerazah**
fix https://github.com/godotengine/godot/issues/15293

### CODE REVIEW

**Comment by akien-mga** [comment]
Changes are good, but could you squash the commits together?

**Comment by icnikerazah** [comment]
i forgot line 28 sorry. this is my first pull request. please correct it.

**Comment by akien-mga** [comment]
No problem, I'll fix it manually and add a couple other fixes to the copyright stuff.

**Comment by akien-mga** [comment]
Merged manually as e3c9a7ed4.

If you want to learn about the PR workflow for Godot for future PRs, you can read http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html :)

**Pull request closed without merging**
