### PR TITLE
Monitor: add checkbox to monitor list

### PR DESCRIPTION
**Pull request by ghost**
so that users don't have to hold CTRL to select multiple entries, and it's more obvious what to do to show the graph.

Merge after #12343 as there might be some conflicts, but changes are compatible.

image

### CODE REVIEW

**Comment by karroffel** [comment]
This has a nice PR number.

**Comment by akien-mga** [comment]
Conflicts indeed.

**Comment by akien-mga** [comment]
Oops

**Comment by Noshyaar** [comment]
Conflict resolved

**Pull request merged**
