### PR TITLE
Fix double click selection

### LINKED ISSUE #55588: [4.0] double clicking on a word is broken
### Godot version

v4.0.dev.custom_build [bbff64eee]

### System information

Linux, Vulkan

### Issue description

this happened recently probably related to: https://github.com/godotengine/godot/pull/55294
because my mouse is very sensitive to small movements it probably moves my cursor a little when double-clicking, making godot want to perform a drag-and-drop for the word

(the word does get marked for shot (until i release the click))

### Steps to reproduce

double click on word lol

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ConteZero**
This is an attempt to fix https://github.com/godotengine/godot/issues/55588

### CODE REVIEW

**Comment by CrezyDud** [comment]
worked!

image
so sometimes, (maybe very small mouse movements)
it focuses more than it should

**Comment by ConteZero** [comment]
You double clicked on "typeof" and the result has been the selection of "if typeof" ?

**Comment by ConteZero** [comment]
I've done some changes, @CrezyDud can you try again the new build?

**Comment by CrezyDud** [comment]
you fixed it, but when i click on a comma/dot/quote or bracket
it marks the whole line

**Comment by ConteZero** [comment]
It happens when you do a single or double click?

**Comment by CrezyDud** [comment]
double

**Comment by ConteZero** [comment]
I can't find anything in the new code that could cause this.
Are you sure this behavior wasn't present even before the commit which added drag and drop support?

**Comment by CrezyDud** [comment]
dots qoutes and commas and brackets cause the word selection to stop, because it seperates words
that could be the issue

**Comment by ConteZero** [comment]
It seems that in your system the double click is interpreted as a triple click, why this happens is a mystery to me.

**Comment by CrezyDud** [comment]
well, i'm forced to use cinnamon until wayfire fixes with newest wlroots, and i don't wanna install stable (lezy)
i don't like cinnamon
and it seems to spass out on double lol

**Comment by Calinou** [comment]
This PR may not be necessary anymore given https://github.com/godotengine/godot/issues/55588#issuecomment-1449174086.

**Pull request closed without merging**
