### PR TITLE
Fix get_drag_data not overridable in some Controls

### LINKED ISSUE #75118: RichTextLabel doesn't get _get_drag_data called.
### Godot version

v4.0.1.rc1.official [d23922ffe]

### System information

Ubuntu 22.04

### Issue description

RichTextLabel doesn't get **_get_drag_data** called.

### Steps to reproduce

Just drag the labels, the **Label** one prints drag to output, the **RichTextLabel** doesn't

### Minimal reproduction project

[drag_test.zip](https://github.com/godotengine/godot/files/11012271/drag_test.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #75118

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Comment by YuriSizov** [comment]
This still doesn't make them fully overridable. Does it make sense to enforce the default behavior of the control over the user-defined behavior?

**Comment by bruvzg** [comment]
> This still doesn't make them fully overridable. Does it make sense to enforce the default behavior of the control over the user-defined behavior?

Default `Control` method is calling `Callable` set by `set_drag_forwarding` or script virtual method, so it should be overridable.

**Comment by YuriSizov** [comment]
Yes, but that only happens if the C++ override doesn't return before that. I.e. in RTL if `selection.drag_attempt && selection.enabled`, then user overrides are never reached.

**Comment by KoBeWi** [comment]
Could be something like this I guess
https://github.com/godotengine/godot/blob/161d028ae89acb578cfcd4f29bfe9ac205459e8b/scene/gui/text_edit.cpp#L3049-L3056

**Comment by YuriSizov** [comment]
That makes sense to me. Do you plan to make this change? I'm not insisting on either way, just want it to be a clear decision that we understand. It can also be valid that these internal triggers for dragging should always take priority.

**Comment by KoBeWi** [comment]
Yeah I'll change it.

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.

**Comment by Ohan17** [comment]
Label still not calling `_get_drag_data`.

**Comment by KoBeWi** [comment]
Change `mouse_filter` to something different than `Ignore`.

**Pull request merged**
