### PR TITLE
[WIP] Fixing link to Github doc contribute URL

### PR DESCRIPTION
**Pull request by Lisapple**
This redirects directly to the doc (.rst) file of the opened class, instead of root folder on Github.

I haven't found any issue or PR about it but I'm sure I've already seen one mentioning this problem.

### CODE REVIEW

**Comment by akien-mga** [comment]
> And it doesn't worth to add a field in export doc script to include the local path of the XML file into DocData::ClassDoc?

I think that would be a bit overkill just for this feature.

For the time being, it's probably best to link simply to the `doc/classes` folder and let users pick the class they want, and if missing (i.e. one from a module), figure out where the module docs live by checking the relevant documentation.

Or we just link to the https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html page and make sure that it provides clear instruction on where to find the source XML for a given class.

**Comment by akien-mga** [comment]
Actually reading the current code, it seems to work as expected. This link you are changing is about contributing *tutorials*, i.e. new doc pages which related to features of this class, but are not part of the class reference.

On the other hand, for missing method or member descriptions, you get a link to https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html as expected.

So this PR seems to stem for a misunderstanding and I think the current state is better than what the proposed change would do.

**Comment by Lisapple** [comment]
Exact, I totally mixed up the tutorials and class documentation!

I thought that redirecting to current class documentation page on Github would ease the efforts to fix typo or small errors, but you are right, it is the wrong link to do so.

Still, I think that redirecting to `https://github.com/godotengine/godot-docs` is not the best option for new comers (even the Read Me doesn't contain info about tutorials guidelines, just the technical details to do it).

Maybe it would be better to redirect to Documentation guidelines: `https://docs.godotengine.org/en/lastest/community/contributing/documentation_guidelines.html`, which already link to `godot-docs` repo?
(That would be another PR.)

**Comment by akien-mga** [comment]
Yes that's a good idea :)

**Pull request closed without merging**
