### PR TITLE
Change the unreacheable return value of shape_find_owner()

### PR DESCRIPTION
**Pull request by Kemikal1**
The shape owner id can take the value of 0, which should be an illegal value, the fixes mean either 
-change the indexes of both shapes and shapeOwners (for consistencies sake ,a previous PR) or 
-the illegal value, 
I opted to change the illegal value.

### CODE REVIEW

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Makes sense, returning an invalid value would prevent accessing a valid owner anyway in error cases.

Apart from my comments, could you please make the same changes for 2D to keep it consistent?
https://github.com/godotengine/godot/blob/a4fbb67902f493bff503dafd0ccc6277af85f3a1/scene/2d/collision_object_2d.cpp#L456

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Thanks for making the extra changes.

After changing the two last things, please squash your commits (see [interactive rebase](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase)) and the PR should be good to go.

**Comment by Kemikal1** [comment]
Hope i did it right

**Review by pouleyKetchoupp — COMMENTED** [review]
Code looks good!

@Kemikal1 Commits are still not squashed. Make sure you use `fixup` on the 3 extra commits when you use interactive rebase.

Also, please update the commit message for the first one to be a bit more descriptive ( can be the same as the PR's title).

**Comment by pouleyKetchoupp** [comment]
@Kemikal1 No worries, I know certain commands in git can be difficult to handle when you're not used to them.

Now it looks like you're back with 4 commits. You can just run `git rebase -i upstream/master` again, and in the selection list, set the proper title to the first commit in the list, then set the 3 other ones to `fixup` and it should do the trick.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by pouleyKetchoupp** [comment]
This can't be cherry-picked for 3.x, because one of the file has a different name. So @Kemikal1 if you're up for it, feel free to open a new PR with the same changes on the 3.x branch.

**Comment by akien-mga** [comment]
It's ok, I can figure out the file renaming while cherrypicking in this case (usually, git can figure it out itself if the code is similar).

**Pull request merged**
