### PR TITLE
Pass by reference to const

### PR DESCRIPTION
**Pull request by qarmin**
EDIT: Removed reference to built-in data types like bool and real_t

### CODE REVIEW

**Comment by neikeq** [comment]
What is gained from passing `bool`, `int` and `float` by reference? Isn't it actually worse?

**Comment by KoBeWi** [comment]
Probably related: https://stackoverflow.com/questions/11932614/in-c-is-it-bad-to-pass-a-const-bool-by-reference

**Comment by hbina** [comment]
For anyone interested, here's a simple regex to try to find pass by const but not reference

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
