### PR TITLE
Make enum/constant binds 64-bit.

### PR DESCRIPTION
**Pull request by bruvzg**
- Changes constant / enum data type to be 64-bit int.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I assume the 64bit change is due to running out of space for constants?
There are a few unused constants, so this might be not necessary (see #60458), but could be useful in the future.

**Comment by YuriSizov** [comment]
I see why this needed, and this kind of visibility is needed for more than just fonts on labels. Many controls, containers especially, have very important properties hidden in overrides. But I'm not sure if this is a good way to do it.

First of all, it's not clear to the user that it's a duplicated property. So they may get confused why there are two ways to set something very similar. The only clue would be that the tooltip should show it as `theme_override_fonts/font` instead of just `font`, but that's easy to miss. And the UI for overriding itself is kind of unexpected here. Why other same level properties can just be set and unset to default, but this one has a checkbox next to it? Why do other properties have fallback values, and this one must be set to empty and you don't know what it would fallback to?

Granted, these are existing problems with overrides as well, but as long as they are treated as a special case, it's less severe. Here they would be mixed with the normal properties, and those usability nuances get front and center.

Second, this makes it less obvious for some properties that they are controlled by themes. I specifically renamed the `Custom ...` sections to `Theme Override/...` sections to make sure that users understand that there is a relation. But this goes the opposite way. IMO, this incentivizes to avoid themes and set everything ad-hoc, on per-control basis, and I'd argue we need to incentivize using themes more, unless the opposite is actually needed. Especially now that we have a way to define type variations and thus make themes even more reusable.

-----
So overall, I'm not sure. The way theme properties are presented in the inspector does not respect the inheritance chain, and doesn't respect the importance of those properties for each control. I'm kind of of a mind that there should be another "theme/configuration" tab, or something. But then again, reduz wants to move signals and groups into the inspector instead of having individual tabs, so this kind of solution wouldn't be welcome.

**Comment by bruvzg** [comment]
Superseded by #62139, but make enums / constants 64-bit might be still useful, so keeping it for this purpose only.

**Review by akien-mga — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
