### PR TITLE
Area Enhancement

### LINKED ISSUE #27970: Area not detecting Trimesh Static Bodies
Godot version: 3.1
OS/device including version: Windows 10 Home 1803

Issue description:
I'm trying to create stepping for a kinematic controller. I'm using is_on_wall() to detect if the player is being stopped by a collision and the Area node to detect walls taller than the step height.
The Area node does not detect overlap with generated Trimesh Static Bodies for custom environment models. Both the signals and the get_overlapping_bodies() function do not return anything. It works fine with convex and primitive statics. I've searched and haven't seen any issues addressing this. I can't even really find much information on Trimesh Statics.

Steps to reproduce:
1. Create a MeshInstance and generate a Trimesh Static Body for it
2. Create an Area Node with a script to accept signals, or call overlap methods
3. Move the Area Node into the Trimesh Static Body
4. Weep at the complete lack of activity

-Or-

1. Download my minimal
2. Use Arrow keys or WASD to move the Area into different statics to see results

Things I've tried:
- Changing the shape of the Area
- Making the static trimesh body the parent node
- Using _on_Area_body_shape() signals

Minimal reproduction project:
[AreaTrimeshBug.zip](https://github.com/godotengine/godot/files/3075684/AreaTrimeshBug.zip)

### LINKED ISSUE #28432: Areas do not overlap with CSGs.
**Godot version:**
3.1

**OS/device including version:**
Windows 10, 10.0.17134

**Issue description:**

Areas do not register overlapping with CSGs that have Collision enabled.

**Steps to reproduce:**
Intersect an Area's CollisionShape with a StaticBody. Note that it correctly registers the Static Body as overlapping.

Now do the same thing, but use a CSG with collision enabled instead of a StaticBody. Note that the Area does NOT recognize the CSG as overlapping at all.

This minimal preproduction project has 2 Areas, one overlapping with a StaticBody, and one overlapping with a CSG. Only the one overlapping the StaticBody fires any overlap events, or recognizes that they are overlapping in `get_overlapping_bodies()`.

**Minimal reproduction project:**

[CSG Area Bug.zip](https://github.com/godotengine/godot/files/3119005/CSG.Area.Bug.zip)

### PR DESCRIPTION
**Pull request by Phischermen**
Added a new property to the Area class that can make Areas perceive concave shapes. It is useful for jumping/crouching systems.

Closes #28432 and closes #27970.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Can this be made the default (and maybe the option removed)?

**Comment by Phischermen** [comment]
I assumed the reason why Areas skipped concave collision shapes was optimization. When an Area is used as a trigger, this is optimal because practically all dynamic game objects (characters, enemies, boxes, etc.) use primitive or convex collision shapes. But when used for building character controllers, it can be limiting. For example, I couldn't stay crouched in a tunnel I made with a CSG node, because the Area I used to detect if the space needed to stand was unoccupied could not perceive concave shapes.

I believe Areas will primarily be used for setting up simple triggers, so I think it's better for the default to be off. 

If I were to remove the option "perceive concave", then the only necessary change would be to remove the if statement in space_bullet.cpp from lines 169 - 172. I personally like this small amount of optimization, since convex-concave collisions are more expensive than other collision pairs and triggers are not often used to detect concave shapes in the first place, so why not skip them.

**Comment by Phischermen** [comment]
If you haven't noticed, I'm having trouble figuring out how to rebase this pull request! If anyone can offer some help, that'd be really great!

**Comment by asheraryam** [comment]
@Phischermen The branch seems to be be messy, I would suggest creating a new branch based off latest master and then just cherrypick the commits you need from this branch. Then set the tracking target for the new branch to this one so it can force-push and overwrite it.

**Comment by AndreaCatania** [comment]
Areas are really computationally intensive currently and Add this feature is not so good. Also I wander what a concave volume means. 

Well, sometimes you can see with your eyes that a concave _could_ have a volume, but even in that cases a concave doesn't have a volume.

I think that is better decompose your area with some primitive shapes and the reasons are performance and concept of volume.

**Comment by asheraryam** [comment]
@AndreaCatania I think we can open a separate issue for the performance since it really needs optimizing anyway. I had to do manual distance detection in gdscript because simple sphere areas lagged the game to 5 fps with 2000 moving agents connected to the body_entered signal.

**Comment by Phischermen** [comment]
@AndreaCatania I didn't intend to allow Areas to use concave shapes, if that's what you mean. My intentions were to only allow Areas to detect concave shapes, specifically the walls of a level (for the use of character controllers). 

Admittedly, I haven't properly stress tested my code, so I don't know how much complexity an Area with "perceive concave" turned on can withstand.

I think my next step will be to setup a proper testing scene, that has a moving Area and 1000s of concave shapes and see what happens.

And I also think I'll accept @asheraryam help and clean up this pull request!

**Comment by Phischermen** [comment]
I think I got everything setup correctly now. I'm going to make a new pull request that's not based on my master branch! Sorry for this whole mess.

**Pull request closed without merging**
