### PR TITLE
Change the AudioStreamPlayer icons to be clearer.

### LINKED ISSUE #9688: Use a colored speaker icon for `AudioStreamPlayer`s
### Describe the project you are working on

prototypes

### Describe the problem or limitation you are having in your project

This is the "formal" proposal version of [a discussion](https://github.com/godotengine/godot-proposals/discussions/9655) that I created a few days ago.

image
image
image

Those 3 icons only differ by a tiny color dot and I find them not symbolic enough to be pleasant to read.
As a bonus, the music notation used in the icon is, well, a *music* notation, not something related to sound in general.

Currently, the icon is made up of 2 parts:
1. the multi-colored note, this gradient having the "sound" meaning,
2. a small colored play icon, colored according to the spatialness of the node.

My point of view is the following:
- the gradient is useless. A good icon would convey the audio part much more naturally than the current design.
- the spatial part is way too small to be useful.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

- Use an actual speaker icon instead
- Color it *fully* according to spatiality: either white for `AudioStreamPlayer`, blue for `AudioStreamPlayer2D` or red for `AudioStreamPlayer3D`
- Keep the gradient in `AudioStream`s since there is no common icon for them (some use the note, some don't)

Basically use the same icon as most other software:
blender|ubuntu|unity|godot, in the 3D view
-|-|-|-
image|image|image|image

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

image

a good icon would have to be designed by someone competent.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's used in 99% of godot projects.

### Is there a reason why this should be core and not an add-on in the asset library?

it's core already

### PR DESCRIPTION
**Pull request by radiantgurl**
closes https://github.com/godotengine/godot-proposals/issues/9688

### CODE REVIEW

**Comment by RedMser** [comment]
You should optimize SVGs, use for example [SVGOMG](https://jakearchibald.github.io/svgomg/)

**Comment by AThousandShips** [comment]
See [here](https://docs.godotengine.org/en/latest/contributing/development/editor/creating_icons.html#icon-optimization) for optimization instructions

**Review by Calinou — APPROVED** [review]
Looks good to me. This is how it looks in action:

image

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
