### PR TITLE
Fix `EXIT_SUCCESS` on Android

### LINKED ISSUE #89886: Regression: exit code `EXIT_SUCCESS` causes an infinite loop on Android
### Tested versions

- Reproducible in master https://github.com/godotengine/godot/commit/99ff024f78f65ba0bc54fb409cfeca43ba2008fe
- Not in 4.3 dev5

### System information

N/A

### Issue description

Like error #89842 but on Android

**infinite loop**:
Bildschirmfoto 2024-03-25 um 16 30 27

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes: #89886

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]
Thanks for the fix!

This issue seems to have affected a couple platforms, were you able to trace the root cause and do we need to propagate this fix to other platforms?

**Comment by Alex2782** [comment]
MacOS fixed yesterday. Web, Windows, iOS looks ok.

**Review by fire — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks good.

And my bad, thanks for the fixes. I also confirm that the other uses of `Main::start()` seem fine now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
