### PR TITLE
Remove RESET tracks after removing tracks

### LINKED ISSUE #55489: AnimationPlayer RESET track does not automatically clean up tracks that were removed
*Related to https://github.com/godotengine/godot/issues/55438.*

### Godot version

3.4.stable, 4.0.dev (89a4ab6c1)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

In the editor, the AnimationPlayer RESET track does not automatically clean up tracks that were removed. This can cause old keys to linger and cause errors when opening scenes in the editor: https://godotforums.org/discussion/28172/i-get-bombarded-with-error-messages-does-anyone-knows-what-the-mean-and-how-to-get-rid-of-them

cc @RandomShaper, as they implemented the animation reset track feature.

### Steps to reproduce

- Add an AnimationPlayer node.
- Add another node to animate (such as a Sprite).
- Create a new animation in AnimationPlayer.
- Click on a key icon in the inspector to animate a property. Ensure **Create RESET Track** is checked in the confirmation dialog.
- Remove the track in the animation.
- Notice the RESET animation still has a track for the removed track.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #55489

### CODE REVIEW

**Comment by akien-mga** [comment]
Does this register two separate UndoRedo actions?

**Comment by KoBeWi** [comment]
No, the actions are nested, so they get merged into one.

**Review by RandomShaper — APPROVED** [review]
LGTM. ~Let's get sure about the undo-redo thing, though.~

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
