### PR TITLE
Fixed issue where panels in sprite frames editor couldn't be resized

### LINKED ISSUE #55760: Godot 4: Impossible to resize panels in "SpriteFrames" menu
### Godot version

v4.0.dev.calinou [4f298237b]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

Impossible to resize the SpriteFrames panels while the cursor show this possibility.

image

image

### Steps to reproduce

1. Create a new `AnimatedSprite2D`
2. Create a new `SpriteFrames`
3. Edit it
4. Try to resize panels

### Minimal reproduction project

NA (Editor related)

### PR DESCRIPTION
**Pull request by IgorKordiukiewicz**
Fixes #55760

https://user-images.githubusercontent.com/25117425/156260973-03a9bd9e-4d60-442a-909d-05392a64bbe3.mp4

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
This likely broke after GDVIRTUAL changes, but I didn't check.

**Comment by IgorKordiukiewicz** [comment]
Still works

https://user-images.githubusercontent.com/25117425/165197355-5946576e-e3cf-41ef-b16e-1cc192175526.mp4

**Comment by KoBeWi** [comment]
I know, I wouldn't approve otherwise :v

What I meant in my comment is that I didn't check which commit introduced the regression. It's not that important, but the method was there since the beginning, so it's a bit suspicious that it caused problems just now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
