### PR TITLE
Fix windows compilability

### PR DESCRIPTION
**Pull request by est31**
In #2037 I've made some mistakes, this is an attempt to fix windows compilability. @volzhs, could you try to compile it?

### CODE REVIEW

**Comment by volzhs** [comment]
here's my error logs.

```
platform/windows/godot_win.cpp: In function 'int widechar_main(int, wchar_t**)':
platform/windows/godot_win.cpp:128:13: error: cannot declare variable 'os' to be of abstract type 'OS_Windows'
  OS_Windows os(NULL);
             ^
In file included from platform/windows/godot_win.cpp:29:0:
platform/windows/os_windows.h:62:7: note:   because the following virtual functions are pure within 'OS_Windows':
 class OS_Windows : public OS {
       ^
In file included from platform/windows/os_windows.h:35:0,
                 from platform/windows/godot_win.cpp:29:
core/os/os.h:255:23: note: 	virtual OS::TimeZoneInfo OS::get_time_zone_info() const
  virtual TimeZoneInfo get_time_zone_info() const=0;
                       ^
x86_64-w64-mingw32-g++ -o main/main.windows.opt.tools.64.o -c -O2 -DDEBUG_ENABLED -DFREETYPE_ENABLED -DWINDOWS_ENABLED -mwindows -DGLES2_ENABLED -DGLEW_ENABLED -DRTAUDIO_ENABLED -DMINGW_ENABLED -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/windows -Itools/freetype -Itools/freetype/freetype/include -Idrivers/builtin_openssl2 -Idrivers/builtin_zlib/zlib -Imain/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes main/main.cpp
scons: *** [platform/windows/godot_win.windows.opt.tools.64.o] Error 1
platform/windows/os_windows.cpp:1863:51: error: no 'OS::TimeZoneInfo OS_Windows::get_time_zone_info() const' member function declared in class 'OS_Windows'
 OS::TimeZoneInfo OS_Windows::get_time_zone_info() const {
                                                   ^
scons: *** [platform/windows/os_windows.windows.opt.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by volzhs** [comment]
here's updated error logs.
```
platform/windows/os_windows.cpp: In member function 'virtual OS::TimeZoneInfo OS_Windows::get_time_zone_info() const':
platform/windows/os_windows.cpp:1866:33: error: cannot convert 'TIME_ZONE_INFORMATION {aka _TIME_ZONE_INFORMATION}' to 'LPTIME_ZONE_INFORMATION {aka _TIME_ZONE_INFORMATION*}' for argument '1' to 'DWORD GetTimeZoneInformation(LPTIME_ZONE_INFORMATION)'
  if (GetTimeZoneInformation(info) == TIME_ZONE_ID_DAYLIGHT)
                                 ^
platform/windows/os_windows.cpp:1870:3: error: 'ret' was not declared in this scope
   ret.name = info.DaylightName;
   ^
platform/windows/os_windows.cpp:1872:3: error: 'ret' was not declared in this scope
   ret.name = info.StandardName;
   ^
platform/windows/os_windows.cpp:1875:2: error: 'ret' was not declared in this scope
  ret.bias = info.Bias;
  ^
x86_64-w64-mingw32-g++ -o modules/gridmap/register_types.windows.opt.tools.64.o -c -O2 -DDEBUG_ENABLED -DFREETYPE_ENABLED -DWINDOWS_ENABLED -mwindows -DGLES2_ENABLED -DGLEW_ENABLED -DRTAUDIO_ENABLED -DMINGW_ENABLED -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/windows -Itools/freetype -Itools/freetype/freetype/include -Idrivers/builtin_openssl2 -Idrivers/builtin_zlib/zlib -Imodules/gridmap/vorbis -Idrivers/builtin_openssl2/crypto -Idrivers/builtin_openssl2/openssl -Idrivers/builtin_openssl2/crypto/evp -Idrivers/builtin_openssl2/crypto/asn1 -Idrivers/builtin_openssl2/crypto/modes modules/gridmap/register_types.cpp
scons: *** [platform/windows/os_windows.windows.opt.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Comment by est31** [comment]
@volzhs can you try to add `TimeZoneInfo ret;` before line 1869 of `platform/windows/os_windows.cpp`?

**Comment by volzhs** [comment]
here's error.

```
platform/windows/os_windows.cpp: In member function 'virtual OS::TimeZoneInfo OS_Windows::get_time_zone_info() const':
platform/windows/os_windows.cpp:1866:33: error: cannot convert 'TIME_ZONE_INFORMATION {aka _TIME_ZONE_INFORMATION}' to 'LPTIME_ZONE_INFORMATION {aka _TIME_ZONE_INFORMATION*}' for argument '1' to 'DWORD GetTimeZoneInformation(LPTIME_ZONE_INFORMATION)'
  if (GetTimeZoneInformation(info) == TIME_ZONE_ID_DAYLIGHT)
```

**Comment by est31** [comment]
Ok, what when you replace the `info` with `&info`, as in `if (GetTimeZoneInformation(&info) == TIME_ZONE_ID_DAYLIGHT)`, at the line `1866`?

**Comment by reduz** [comment]
i can give it a try when i get back home tonight, as I'm currently in
ubuntu..

**Comment by est31** [comment]
ok according to @volzhs those two changes made it compile.

**Comment by reduz** [comment]
please send me PR to merge, since i won't be able to do much until I come
back home at night

**Pull request merged**
