### PR TITLE
Add missing Python type hints in doc/tools/make_rst.py

### PR DESCRIPTION
**Pull request by asmaloney**
(This change is compatible with 3.x and can be cherry-picked.)

### CODE REVIEW

**Comment by AaronRecord** [comment]
For now this is probably fine, but doesn't python support first class type annotations now?

**Comment by asmaloney** [comment]
I wasn't sure what version of Python is targetted, but this is just a fix for what's already there.

If the maintainer(s) want(s) to switch them all over to proper type hints (looks like it [requires Python 3.5](https://docs.python.org/3/library/typing.html)?), I'd be happy to do that as well.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
