### PR TITLE
[Windows] Add main executable to the console wrapper dependencies to prevent simultaneous linking.

### PR DESCRIPTION
**Pull request by bruvzg**
Should fix https://github.com/godotengine/godot/pull/80482#issuecomment-1685369408

### CODE REVIEW

**Comment by YuriSizov** [comment]
cc @darksylinc @anvilfolk Could you give it a test and see if this PR resolves your issue?

**Comment by anvilfolk** [comment]
I compiled from scratch twice on the computer that was having trouble pretty regularly and it worked fine! It's not a 100% guarantee, but it is a good indicator that this fix might work! :)

**Comment by anvilfolk** [comment]
Three more successful compilations with no issues whatsoever. I'd say merge :)

**Review by YuriSizov — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
