### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bitnom**
Added new section for extra language bindings.

### CODE REVIEW

**Comment by TensorTom** [comment]
Oops I didn't mean to put it below the build tests.

**Comment by Chaosus** [comment]
Please squash the commits together ^^

**Comment by Calinou** [comment]
Should these be considered important enough for new users to mention in the README? I think community bindings would be better listed in [awesome-godot](https://github.com/Calinou/awesome-godot) instead.

**Comment by Toshiwoz** [comment]
> I think community bindings would be better listed in awesome-godot instead.
I agree.

**Comment by reduz** [comment]
It would be nice to add them, although many people get excited about language bindings but then there are not examples, docs and other stuff for them in that language.. so not quite sure if it's the best in this case.
I don't mind them myself, though i think there are other bindings.

**Comment by Zireael07** [comment]
On the other hand, if people know about the existence of said bindings, examples/docs will start popping up. For instance, I was only aware of Python and Nim.

**Comment by groud** [comment]
I don't think those links are needed in the Readme. If we start adding links to community plug-ins, people are going to ask for any sort of links (advertizing plug-ins, basic charaters controllers, etc...).
I think a page in the documentation better suit this list.

**Comment by akien-mga** [comment]
Agreed, these should be added to a documentation page in godot-docs, not the main engine's readme.

**Comment by akien-mga** [comment]
Or in awesome-godot as mentioned by @Calinou.

**Pull request closed without merging**
