### PR TITLE
Implement C dynamic plug-in interface [WIP]

### PR DESCRIPTION
**Pull request by BeppeInfo**
Based on the discussion and proposed (by @reduz) solution at #3936

I'm still trying to complete implementing all methods declared at original [godot_c.h](https://github.com/godotengine/godot/issues/3936#issuecomment-228582342), but, as I'm not that familiar with the internal C++ API, I would like to ask for some guidance while doing it.

### CODE REVIEW

**Comment by karroffel** [comment]
Oh wow

**Comment by Bitiquinho** [comment]
First, why are there less **GODOT_IMAGE_FORMAT_*** **#defines's** than in **Image::Format enum** ? Should I modify the first to match the second and allow easier conversion (cast) between **int** and **Image::Format** ?

**Comment by Bitiquinho** [comment]
Second, what is the correct way to create and set up a unique **RID** (for **godot_rid_create()** call) ? The default constructor initializes its internal data to NULL.

**Comment by karroffel** [comment]
Okay, this might be a bit surprising...

I'm working on a module, [DLScript](https://github.com/GodotNativeTools/dlscript_module).

The original proposal has some problems, I'll address that in a second.

------

# DLScript

Having these functions isn't enough. You need a way to use the functions from external.
So basically what DLScript does is register a new scripting language that uses shared libraries as the source. This shared library makes use of the C API.

I already wrote a [C++ wrapper](https://github.com/GodotNativeTools/cpp_bindings) for this C API.

**In other words**: what you did already is implemented, more mature and more complete.
I admit, I should've mentioned on the proposal that work is being done.

On the other hand your PR is incomplete and you should've come to the IRC to ask about this stuff instead of opening a merge request. You could've saved time because you would've known that someone's already working on this.

So I'm sorry for your wasted effort. But DLScript is already more mature and even feature complete by now. I'll open a PR in the next week when everything goes well.

--------

The proposal uses `void *` to represent core types. You're using dynamic allocation for that. It's a bad choice because you want to be able to use many core types quickly  without having to worry about many allocations which take some time as well.

Feel free to check out [DLScript](https://github.com/GodotNativeTools/dlscript_module) or the resulting [API](https://github.com/GodotNativeTools/godot_headers) I came up with. Sorry for not communicating my efforts on the original proposal.

**Comment by Bitiquinho** [comment]
After I finish implementing the API, how a C plug-in should register functions to be called from GDScript ? The only thing that comes to my mind is that plug-ins must implement a "**const char *get_method_names()**"-like function that return identifiers for all invokable methods, and all of them receives a list/array of **godot_variant** (**Variant*** cast to **void***) values, to account for different number/type of arguments, and return a **godot_variant** as well.

**Comment by Bitiquinho** [comment]
Wow ! That's great to know, actually, as the main reason I was working on it was because I needed it.

Sorry for not following the correct procedure, I've worked with other projects where is fine to open a WIP PR.

I'll close this one, then. Thanks for your quick reply.

**Comment by karroffel** [comment]
@Bitiquinho Yeah, the plan is to have it in 3.0. It's only a few QoL changes and then it'll be ready for a merge. reduz and many others are excited for this, so it's veeery likely to be in 3.0 😄 

I'll link my work on the original proposal so it doesn't happen again.

WIP are not common here, I guess it would've been okay, but it's not the norm here 😄 

Again, sorry for wasting your time.

**Comment by Bitiquinho** [comment]
Do not worry. I didn't take long and I learned something int the process.

It's really great to have it for next release. Thanks a lot for your work.

**Pull request closed without merging**
