### PR TITLE
Add override keywords.

### LINKED ISSUE #40259: Multiple Winconsistent-missing-override warnings when generating Mono Glue with Clang LLVM
**Godot version:** Current 4.0 master ad9e5ae984

**OS/device including version:** Ubuntu 20.04, Clang LLVM 10.0.0

**Issue description:** Generating Mono glue with Clang LLVM results in multiple warnings as errors beginning with:
``` modules/mono/csharp_script.h|69|error: 'get_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|```
<details><summary>Full list:</summary>

```
modules/mono/csharp_script.h|69|error: 'get_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|260|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|260|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_class_namev' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|263|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|263|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|296|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|296|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class_ptr' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|297|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|297|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_initialize_classv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|327|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|327|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_getv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|333|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|333|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_setv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|344|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|344|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_property_listv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|356|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|356|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_notificationv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|377|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|377|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'get_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|260|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|260|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_class_namev' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|263|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|263|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|296|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|296|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class_ptr' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|297|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|297|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_initialize_classv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|327|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|327|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_getv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|333|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|333|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_setv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|344|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|344|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_property_listv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|356|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|356|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_notificationv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|377|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|377|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'get_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|260|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|260|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_class_namev' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|263|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|263|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|296|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|296|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class_ptr' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|297|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|297|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_initialize_classv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|327|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|327|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_getv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|333|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|333|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_setv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|344|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|344|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_property_listv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|356|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|356|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_notificationv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|377|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|377|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'get_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|260|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|260|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_class_namev' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|263|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|263|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|296|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|296|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class_ptr' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|297|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|297|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_initialize_classv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|327|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|327|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_getv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|333|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|333|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_setv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|344|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|344|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_property_listv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|356|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|356|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_notificationv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|377|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|377|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'get_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|260|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|260|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_class_namev' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|263|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|263|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|296|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|296|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: 'is_class_ptr' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|297|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|297|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_initialize_classv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|327|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|327|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_getv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|333|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|333|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_setv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|344|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|344|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_get_property_listv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|356|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|356|note: expanded from macro 'GDCLASS'|
modules/mono/csharp_script.h|69|error: '_notificationv' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]|
core/object.h|377|note: expanded from macro 'GDCLASS'|
core/script_language.h|115|note: overridden virtual function is here|
core/object.h|377|note: expanded from macro 'GDCLASS'|
||=== Build failed: 45 error(s), 0 warning(s) (0 minute(s), 9 second(s)) ===|
```
</details>

Trying to fix these warnings causes a cascade of new ones.

**Steps to reproduce:**
scons use_llvm=yes use_lld=yes module_mono_enabled=yes mono_glue=no

**Minimal reproduction project:**

N/A

### PR DESCRIPTION
**Pull request by madmiraal**
Adds override keywords to all methods that are overriding a parent's virtual method.

Deletes any pure virtual methods that were "overriding" another method.

Fixes #40259

### CODE REVIEW

**Comment by akien-mga** [comment]
Is there any difference between using `virtual [declaration] override;` and only `[declaration] override;`?
If not, should we pick one style and enforce it for readability? If so, which one?

**Comment by pouleyKetchoupp** [comment]
Great change! It will help alleviate confusion is lots of places in the codebase.

> Is there any difference between using virtual [declaration] override; and only [declaration] override;?

According to this discussion the `virtual` keyword is not needed on inherited classes:
https://stackoverflow.com/questions/4895294/c-virtual-keyword-for-functions-in-derived-classes-is-it-necessary

I would be for using `[declaration] override` everywhere because it makes things perfectly clear and easy to visualize when checking a header (`virtual` on original method and `override` for anything inherited).

**Comment by madmiraal** [comment]
> Is there any difference between using virtual [declaration] override; and only [declaration] override;?

The `virtual` keyword is inherited, so it's not required (except, I've read, if you're using an ARM compiler). Prior to the existence of the `override` keyword, it was recommended to clearly show it was a virtual function, should anyone want to derive from the child without looking at the parent to see if it's virtual.

My personal preference is to keep it i.e. `virtual [declaration] override`, if only to prevent you from needing to look to the end of some very long declarations to find the `override` keyword to know it's virtual.

**Comment by AndreaCatania** [comment]
I prefer 'virtual [declaration] override' too.

**Review by AndreaCatania — APPROVED** [review]
The bullet part seems fine. After this PR is merged we can also add it into the other remaining bullet module functions.

**Comment by madmiraal** [comment]
Fixed Travis build failing issues and rebased following #40244 being merged.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
