### PR TITLE
[3.x] Fix KinematicBody axis lock

### LINKED ISSUE #25798: set_axis_lock not working on KinematicBody 3D
**Godot version:**
3.1 Beta 3

**OS/device including version:**
Kubuntu 18.04

**Issue description:**
The Axis lock is not working.
According to the docs I'd assume to call:

```{r tidy=FALSE}
set_axis_lock(move_lock_z,true) 
print("lock z " , get_axis_lock(move_lock_z))
```

The output on the console is : "lock z False"
And the body still moves on z axis by collision.

I tried some variations:
```{r tidy=FALSE}
self.set_axis_lock(PhysicsServer.BODY_AXIS_LINEAR_Z, true)
self.set_axis_lock(move_lock_z, true)
move_lock_z = true
PhysicsServer.body_set_axis_lock(self.get_rid(), PhysicsServer.BODY_AXIS_LINEAR_Z, true)
```

Neither of them results in a locked z axis.
For a 2.5D platformer z-axis lock would be crucial

the whole axis lock panel that was available in 3.06 in the inspector is gone as well in 3.1
Was the feature discarded?

**Minimal reproduction project:**
[AxisLockBug.zip](https://github.com/godotengine/godot/files/2851690/AxisLockBug.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
This fixes #25798 in 3.x.

### CODE REVIEW

**Comment by AndreaCatania** [comment]
I'm not strongly against this, and for the presented reason it seems a good change. However, the physics server API are generally not so fast especially if compared to `locked_axis & (1 << i)`. So have 3 `PhysicsServer` calls on a function that is called recursively each frame may be bad, especially when you have more than 1 character.

This is not a blocker if the physics team still think worth it.

**Comment by AndreaCatania** [comment]
By the way, just noticed the type of `locked_axis` should not be `uint16_t ` but `uint32_t`. All back-ends supports up to 32 flags.

**Comment by pouleyKetchoupp** [comment]
@AndreaCatania The rest of the `KinematicBody` api is an expensive process anyway, I don't think these calls really make a difference. So I would rather keep things clean and simple.

For info, #25798 is only present on 3.2, since on master `set_axis_lock` is setting both members. It still makes sense to remove this duplicate on both branches anyway.

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Just one thing I'd like to change. In order to clean things completely, let's add a helper method on `KinematicBody3D` instead of calling the physics server directly.

Something like:
```
void KinematicBody::_apply_axis_lock(Vector3 &p_motion) const {
	if (get_axis_lock(PhysicsServer::BODY_AXIS_LINEAR_X)) {
		p_motion.x = 0.0f;
	}
	if (get_axis_lock(PhysicsServer::BODY_AXIS_LINEAR_Y)) {
		p_motion.y = 0.0f;
	}
	if (get_axis_lock(PhysicsServer::BODY_AXIS_LINEAR_Z)) {
		p_motion.z = 0.0f;
	}
}
```

And then:
```
_apply_axis_lock(result.motion);
```

Instead of:

```
	for (int i = 0; i < 3; i++) { {
		if (PhysicsServer3D::get_singleton()->body_is_axis_locked(get_rid(), PhysicsServer3D::BodyAxis(1 << i))) {
			result.motion[i] = 0;
		}
	}
```

So the code in `KinematicBody` won't rely on actual values from the physics server to work properly.

**Comment by aaronfranke** [comment]
@AndreaCatania I considered if we could replace `PhysicsServer::get_singleton()->body_is_axis_locked` with `PhysicsServer::get_singleton()->body_get_axis_lock` or similar and then keep the `locked_axis & (1 << i)`, but [it looks like this API used to exist and you removed it](https://github.com/godotengine/godot/pull/14516/files#diff-a748b6a16a5e460ad14d3f1382a2aad08418018409963763c982be3545a280efL476) so I figured it was for a good reason.

**Comment by aaronfranke** [comment]
@pouleyKetchoupp What if the helper method was located on PhysicsServer3D? This would avoid the repeated calls to `body_is_axis_locked `, assuming we don't implement `body_get_axis_lock` or similar. It somewhat makes sense because `locked_axis` is located in PhysicsServer3D's bodies and `PhysicsServer3D::BodyAxis` is in PhysicsServer3D, though it's not as local of a solution as what you propose.

**Comment by pouleyKetchoupp** [comment]
@aaronfranke It's not a bad idea, but currently I don't think it's worth the extra changes in the Physics Server API, and having to implement it in both Bullet and Godot Physics. I would rather do that later, only if for some reason we need it for optimization purpose.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by madmiraal** [comment]
See https://github.com/godotengine/godot/pull/45175#issuecomment-760773272. #25798 was fixed with #38852, but never backported to 3.2. I think the better approach is a backport of #38852.

**Comment by aaronfranke** [comment]
I updated this PR so that now it's a 3.x backport of #38852. This also includes backporting the renames, but the old names are kept as aliases for compatibility, and this PR also updates the documentation.

**Review by pouleyKetchoupp — APPROVED** [review]
Looks good!

**Pull request merged**
