### PR TITLE
[3.x] Add support for custom debug keystore

### LINKED ISSUE #48096: Debug exports using Android custom build don't have the same certificate fingerprints as the ones in the specified debug keystore.
**Godot version:** 3.3

**OS/device including version:** Manjaro 21.0.2  Linux 5.10.30-1-MANJARO

**Issue description:**

When exporting to Android, if it uses custom build and it is a debug apk, it doesn't seem to get signed with the same debug keystore as specified in the editor settings as the resulting apk doesn't  have the same certificate fingerprints as the ones in the debug keystore. Setting the debug keystore in the export settings under "Keystore" doesn't change anything either. 

However, if it is a release apk and with the release keystore set in the export settings, it works fine as expected. 
If it is a debug apk but it doesn't use custom build, it works as expected too.

**Steps to reproduce:**
1. In a new project that is all set up to run a scene, go to "Project" -> "Install Android Build Template" then click "Install".
2. Go to "Editor" -> "Editor Settings", scroll all the way down to "Export" then go to "Android".
3. Specify the "Debug Keystore", "Debug Keystore User", and "Debug Keystore Pass". Then close the "Editor Settings".
3. Go to "Project" -> "Export" then add "Android". 
4. In "Export" under "Android", under "Custom Template", check "Use Custom Build".
5. Click "Export Project", then check "Export With Debug", then choose a place to save the export.
6. Use `keytool -keystore debug.keystore -list -v` and `keytool -printcert -jarfile exported_file.apk` to compare the certificate fingerprints.

**Minimal reproduction project:**

[keystore.zip](https://github.com/godotengine/godot/files/6359327/keystore.zip)

### PR DESCRIPTION
**Pull request by m4gr3d**
Fix #48096

### CODE REVIEW

**Comment by akien-mga** [comment]
I thought we had this feature already? When you fill the Debug Keystore and related settings in the export preset, don't they get used instead of the editor settings one?

**Comment by m4gr3d** [comment]
@akien-mga There's a bug preventing it from working correctly for custom builds (see #48096)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.

**Pull request merged**
