### PR TITLE
Fix uninitialized data reads in Input

### PR DESCRIPTION
**Pull request by lawnjelly**
Found by Valgrind.

### CODE REVIEW

**Comment by akien-mga** [comment]
There's not much harm to doing this but I don't see how uninitialized data reads would actually happen here.

This pattern is fairly common where optional pointers are passed to methods and they are only assigned if non-null:
```cpp
if (r_pressed != nullptr) {
    r_pressed = pressed;
}
```

And as far as I can see `InputMap::event_get_action_status` would only ever return `true` after actually setting the value passed by reference.

Still if valgrind raises an error the bug must happen, and thus there might be a logic bug deeper in `InputMap::_find_event` or `InputEvent::action_match` that might be worth looking into.

This also seems relevant for `master`.

**Comment by lawnjelly** [comment]
The error raised was possibly as a result of just one of these, but I thought better to fix the whole lot as a caution, as these aren't performance critical, and it's fairly easy for this type of bug to creep in. It might be worth further analysis to which of these was the culprit - there was at least one for keyboard input and one for mouse input I think.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
