### PR TITLE
Fix minimum size of TreeItem

### PR DESCRIPTION
**Pull request by floppyhammer**
This PR is used to discuss #52891. ~~It's not a final fix yet.~~

### CODE REVIEW

**Comment by groud** [comment]
Well, no it's not a fix. This basically disables the size caching optimization I did recently.
If that caused the problem, it's likely because I somewhere forgot to set the cache as dirty,

**Comment by floppyhammer** [comment]
@groud When I want to get the minimum size of one column, I call `get_minimum_size(0)`. Now I want to get that of another column, I call `get_minimum_size(1)`. But the first call already set the cache as not dirty, so it will just skip the calculation and give me the minimum size of column 0. A single flag is insufficient to cache the minimum sizes of all columns of a tree item.

**Comment by groud** [comment]
> @groud When I want to get the minimum size of one column, I call get_minimum_size(0). Now I want to get that of another column, I call get_minimum_size(1). But the first call already set the cache as not dirty, so it will just skip the calculation and give me the minimum size of column 0. A single flag is insufficient to cache the minimum sizes of all columns of a tree item.£

Ah right, I did quite a dumb mistake here. This make it so all columns share the same cache which is not good.
The fix is to make both `cached_minimum_size` and `cached_minimum_size_dirty` part otf the `Cell` structure then, it should be an easy fix.

**Comment by floppyhammer** [comment]
Finished.

**Comment by jmb462** [comment]
Column size seems to be correctly calculated from item min size.
But not from the title colum. (An offset may be missing)

image

**Comment by groud** [comment]
> Column size seems to be correctly calculated from item min size.
But not from the title colum. (An offset may be missing)

I am not sure we should take the title into account to compute the minimum size. In a lot of situations the title might be longer than the column content. While it's possible to extend the column by specifying a custom minimum size, I don't think it is possible to shrink it. So in the current situation the issue could be worked around with a custom column size, while it might not be possible if we take the title length into account for the minimum size.

I am not strictly against it, but this might probably go in another PR.

**Review by groud — APPROVED** [review]
LGTM

**Comment by floppyhammer** [comment]
@jmb462 The width returned here is slightly shorter than the width needed to fit the whole text into the column. As you said, an offset or a margin might be missing in this context.
https://github.com/godotengine/godot/blob/a56e8f8afc2b358ec6e58eed2725bfe85942e5e6/scene/gui/tree.cpp#L4006-L4008

**Comment by jmb462** [comment]
> > Column size seems to be correctly calculated from item min size.
> > But not from the title colum. (An offset may be missing)
> 
> I am not sure we should take the title into account to compute the minimum size. In a lot of situations the title might be longer than the column content. While it's possible to extend the column by specifying a custom minimum size, I don't think it is possible to shrink it. So in the current situation the issue could be worked around with a custom column size, while it might not be possible if we take the title length into account for the minimum size.
> 
> I am not strictly against it, but this might probably go in another PR.

Seems that title is taken into account (if show_column_titles is true). But it's exactly the size of the string. As the title as a left margin, the end of the word will be allways cropped.

**Comment by akien-mga** [comment]
Thanks!

Merging as the cache handling fix is good to go as is, but feel free to open a new PR/issue to discuss better handling of the title width.

**Pull request merged**
