### PR TITLE
Revert invalid PopupMenu breaking change from #61102

### LINKED ISSUE #61179: 3.5rc1 Clear Recent Files returns out of bounds error
### Godot version

3.5rc1

### System information

Windows 11

### Issue description

If you try to _Clear Recent Files_ in the script editor you get an out of bonds error and the list isn't cleared.

grafik

`editor/plugins/script_editor_plugin.cpp:486 - Index p_idx = 1 is out of bounds (rc.size() = 1)`

It doesn't matter how many files are listed. In 3.4.4, 3.5b5 and 4.0a8 it's working as intendet.

### Steps to reproduce

Open any script and click "Clear Recent Files"

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by akien-mga**
See https://github.com/godotengine/godot/issues/61179#issuecomment-1131369230 for rationale.

- Fixes #61179.

CC @okla.

### CODE REVIEW

**Review by timothyqiu — APPROVED** [review]
I also spotted a documentation error.

https://github.com/godotengine/godot/blob/b7523a953f1fca6d8e87ff873290f77ce119a234/doc/classes/OptionButton.xml#L97-L101

The special return value is not changed on `3.x`

https://github.com/godotengine/godot/blob/b7523a953f1fca6d8e87ff873290f77ce119a234/scene/gui/option_button.cpp#L260-L264

**Comment by akien-mga** [comment]
Hm maybe we should actually do that tiny compat breakage for 3.5, it feels more like a bugfix than an arbitrary behavior change. Since currently there would be no way to differentiate between "item 0 selected" and "no item selected".

**Comment by timothyqiu** [comment]
@akien-mga It's the ID of that item, not index.

When using the default ID (passing -1 to the parameter), the auto assigned ID starts from 1. `selected / get_selected()` returns -1 if nothing selected. It's kind of a more suitable way to check if anything is selected.

**Comment by okla** [comment]
> I also spotted a documentation error.
> 
> https://github.com/godotengine/godot/blob/b7523a953f1fca6d8e87ff873290f77ce119a234/doc/classes/OptionButton.xml#L97-L101
> 
> The special return value is not changed on `3.x`
> 
> https://github.com/godotengine/godot/blob/b7523a953f1fca6d8e87ff873290f77ce119a234/scene/gui/option_button.cpp#L260-L264

Looks like I've missed `get_selected_id()` change in backport commit. It should contain only `return get_item_id(current);` now.

**Comment by okla** [comment]
Maybe backport https://github.com/godotengine/godot/pull/54647 instead of reverting?

**Comment by okla** [comment]
> > I also spotted a documentation error.
> > https://github.com/godotengine/godot/blob/b7523a953f1fca6d8e87ff873290f77ce119a234/doc/classes/OptionButton.xml#L97-L101
> > 
> > The special return value is not changed on `3.x`
> > https://github.com/godotengine/godot/blob/b7523a953f1fca6d8e87ff873290f77ce119a234/scene/gui/option_button.cpp#L260-L264
> 
> Looks like I've missed `get_selected_id()` change in backport commit. It should contain only `return get_item_id(current);` now. So the documentation is right, code is wrong.

Corresponding change is here https://github.com/godotengine/godot/pull/61185

**Comment by akien-mga** [comment]
> Maybe backport #54647 instead of reverting?

It seems to build upon #54533... the rabbit hole starts getting deep :) I prefer that we only backport what users actively need in their 3.x projects, not general API consistency improvements done in 4.0 while breaking compat.

**Comment by okla** [comment]
> > Maybe backport #54647 instead of reverting?
> 
> It seems to build upon #54533... the rabbit hole starts getting deep :) I prefer that we only backport what users actively need in their 3.x projects, not general API consistency improvements done in 4.0 while breaking compat.

Yeah, I've already edited my message)

**Pull request merged**
