### PR TITLE
RenderingServer reorganization

### PR DESCRIPTION
**Pull request by reduz**
This PR reorganizes and renames most of RenderingServer classes in hopes that it's easier to understand them. Following diagram shows what each is:

image

### CODE REVIEW

**Comment by Riteo** [comment]
I don't really know how this worked before, but out of curiosity in my ignorance, why is there no RenderingDeviceGLES3?

**Comment by jordo** [comment]
I like the rename.  "raster" -> "render" seems appropriate.

**Review by JFonS — APPROVED** [review]

**Comment by JFonS** [comment]
@Riteo RenderingDevice is an abstraction layer of moder graphics APIs (Vulkan/DX12/etc.) so GLES3 doesn't really fit in. Instead, we will have separate renderer implementation that directly interacts with GLES3.

**Comment by lawnjelly** [comment]
Just to voice a little dissent :smile: I still have a suspicion these new names may prove to be overly long.

Using the word `Render` twice in a classname rings alarm bells imo. In many cases the original two word form (such as RasterizerCanvas) seems preferable in terms of readability, even though it is not really a rasterizer. Maybe just switching to RendererCanvas and RendererScene might be enough.

Namespaces, or prefixes if avoiding namespaces -  like Rs for RenderingServer and Rd for Rendering Device could be an option if wanting to include extra information. I'm not sure adding the word server to the names adds that much useful info to outweigh the verbosity etc.

**Comment by reduz** [comment]
@lawnjelly done, we thought about the same with @JFonS, so changed the names per your suggestion.

**Pull request merged**
