### PR TITLE
Add a test suite for Translation

### PR DESCRIPTION
**Pull request by Calinou**
See https://github.com/godotengine/godot/issues/43440.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
So this passed CI in the PR, but not once merged? We seem to have a bug in our unit testing.
```
 D:\a\godot\godot\tests\test_translation.h(42):
TEST CASE:  [Translation] Messages

D:\a\godot\godot\tests\test_translation.h(63): ERROR: CHECK( messages[0] == "Hello2" ) is NOT correct!
  values: CHECK( @"Hello3" == Hello2 )

D:\a\godot\godot\tests\test_translation.h(64): ERROR: CHECK( messages[1] == "Hello3" ) is NOT correct!
  values: CHECK( @"Hello2" == Hello3 )
```

**Comment by akien-mga** [comment]
I could reproduce the issue once locally, but not on subsequent builds. I suspect that SCons doesn't properly pick up new `.h` files so we get some invalid state somehow.

**Comment by akien-mga** [comment]
Yeah re-running the CI solved it... we'll have to figure this one out eventually.

**Comment by kleonc** [comment]
@akien-mga I think the issue is that this part of the test:
https://github.com/godotengine/godot/blob/2be9b5dec49ffb3122f766e1d4c9cd2088fde272/tests/test_translation.h#L57-L64
assumes that `Translation` preserves insertion order of the messages (and that `get_message_list()` returns messages in the same order) but it's not the case since `Map` is used internally as a storage:
https://github.com/godotengine/godot/blob/2be9b5dec49ffb3122f766e1d4c9cd2088fde272/core/string/translation.h#L42

**Comment by akien-mga** [comment]
Good catch! I guess the test should be changed to use `find()` or similar?

**Comment by kleonc** [comment]
Yeah, size check and `messages.has(...)` for each entry should be sufficient.

**Pull request merged**
