### PR TITLE
Update miniupnpc include paths

### LINKED ISSUE #99196: Cannot build with `builtin_miniupnpc=no`
### Tested versions

Latest master

### System information

Godot v4.4.dev (-) - Ubuntu 24.04.1 LTS 24.04 on X11 - X11 display driver, Multi-window, 2 monitors - Vulkan (Mobile) - dedicated AMD Radeon RX 6800 XT (RADV NAVI21) - AMD Ryzen 9 5900X 12-Core Processor (24 threads)

### Issue description

PR #99171 breaks when `builtin_miniupnpc=yes` on Ubuntu 24.04 LTS

This is because:

```bash
pkg-config miniupnpc --cflags --libs
-lminiupnpc
```

Returns those flags, but Godot does:

```cpp
#include <miniupnpc.h>
#include <upnpcommands.h>
// etc
```

However the official package expects the following:

```cpp
#include <miniupnpc/miniupnpc.h>
#include <miniupnpc/upnpcommands.h>
```

Before the PR, it compiled fine because Godot explicitly added:

```py
env.Prepend(CPPPATH=["/usr/include/miniupnpc"])
```

### Steps to reproduce

Compile with:

```bash
pyston-scons platform=linuxbsd builtin_embree=yes builtin_enet=no builtin_freetype=yes builtin_graphite=yes builtin_harfbuzz=yes builtin_libogg=no builtin_libpng=yes builtin_libtheora=no builtin_libvorbis=no builtin_libwebp=no builtin_mbedtls=no builtin_miniupnpc=no builtin_pcre2=no builtin_zlib=yes builtin_zstd=no linker=mold optimize=none debug_symbols=True tests=False dev_mode=True dev_build=True use_llvm=yes use_lld=yes  opengl3=no openxr=no -j 24
```

### Minimal reproduction project (MRP)

N / A

### PR DESCRIPTION
**Pull request by Sticksman**
Fixes some include since we removed adding the miniupnpc lib to the path.

Fixes #99196

### CODE REVIEW

**Comment by Sticksman** [comment]
Looks like it doesn't build for other platforms, will take a look

**Comment by akien-mga** [comment]
The problem here is that unlike most C/C++ libraries, miniupnpc has a discrepancy between the includes it uses for building from source, and the includes it expects from other applications using its public headers.

The files in `thirdparty/miniupnpc/src/` use includes like `#include "miniupnpcstrings.h"`, and those includes are in `thirdparty/miniupnpc/include/`, which is added to the include path when using the `builtin_miniupnpc=yes` code path (default).

So Godot's own code that uses this builtin copy of miniupnpc also has `thirdparty/miniupnpc/include/` as include path, and includes those headers without a `miniupnpc/` prefix.

But the miniupnpc pkgconfig file forces a use relative to `/usr/include`, and expects the paths to the `miniupnpc/miniupnpcstrings.h`, which can't be true both when using our vendored copy (with no `miniupnpc/` subfolder) and the system one.

We could move `thirdparty/miniupnpc/include/` to `thirdparty/miniupnpc/include/miniupnpc/` and add this as include path for building the miniupnpc C files, but add `thirdparty/miniupnpc/include/` only as include path for building Godot files, but that's pretty messy.

IMO we should just partially revert that change, as miniupnpc's pkgconfig file is IMO incorrect.

**Comment by akien-mga** [comment]
CC @dustdfg

**Comment by Sticksman** [comment]
Thank you for the very detailed explanation! That all sounds incredibly annoying and a splitting headache. We should update the issue with this explanation.

**Pull request closed without merging**
