### PR TITLE
[3.x] Drag multiple resources onto exported array variable at once

### PR DESCRIPTION
**Pull request by AaronRecord**
Backport of https://github.com/godotengine/godot/pull/37965

### CODE REVIEW

**Comment by LightningAA** [comment]
It seems it's possible to drag non-valid resource types (e.g. dragging an audio file onto an array of textures) onto the array and it just creates a new empty element. It's not a big deal, but it seems there's code that's supposed to stop this from happening:
https://github.com/godotengine/godot/pull/50718/files#diff-17781aa265945f5f8988f4d66150a04b73fcdd99f5600b24409d731d24e6fbf1R442-R445, cc @EricEzaM.

**Comment by EricEzaM** [comment]
More issues caused by this damn code snippet:
https://github.com/godotengine/godot/pull/40383#issuecomment-865053866

`allowed_type` was being set to `subtype`, but `subtype` is just `Object` in this case, not, for example, `Texture`. The string value `"Texture"` is stored in `subtype_hint_string`, so when the subtype is `Object`, we should also look to see if there is a `subtype_hint_string`, and make the allowed type that. I will submit a PR for this. 🙃

**Comment by LightningAA** [comment]
https://github.com/godotengine/godot/pull/50805 should probably be merged first, then I can cherry-pick it as part of this PR, but other than that I think this PR is good.

**Comment by akien-mga** [comment]
> #50805 should probably be merged first, then I can cherry-pick it as part of this PR, but other than that I think this PR is good.

It has now been merged :)

**Comment by LightningAA** [comment]
I think this should be good to go

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
