### PR TITLE
Add unit tests for Node2D helper methods

### PR DESCRIPTION
**Pull request by 2nafish117**
Add Unit tests for Node2D helper methods (look_at, get_angle_to, to_local, to_global, get_relative_transform_to_parent)
Link to #43440

### CODE REVIEW

**Comment by 2nafish117** [comment]
When you pass in a sibling into Node2D::get_relative_transform_to_parent, it must return Transform2D() according to the code, but it doesn't seem to do so. Does anyone know why?

`CHECK(test_node3->get_relative_transform_to_parent(test_sibling).is_equal_approx(Transform2D()));`

**Comment by AThousandShips** [comment]
> When you pass in a sibling into Node2D::get_relative_transform_to_parent, it must return Transform2D() according to the code, but it doesn't seem to do so. Does anyone know why?

That's not what happens with the code, it doesn't check for that, it just goes up the tree until it finds a non-2D node or no parent, it errors if the parent isn't a 2D node and *then* returns the empty transform, but it first combines this with the local transform:
https://github.com/godotengine/godot/blob/c4279fe3e0b27d0f40857c00eece7324a967285f/scene/2d/node_2d.cpp#L392-L406

**Comment by AThousandShips** [comment]
No it calls for the steps until the parent is not a `Node2D`:
```cpp
return parent_2d->get_relative_transform_to_parent(p_parent) * get_transform(); 
```

**Comment by 2nafish117** [comment]
@AThousandShips Ah yes, you're right, I somehow seemed to have forgotten about recursion going back down the stack.
Ive fixed the test now.

**Comment by 2nafish117** [comment]
Hello, can someone review this PR, it is ready to merge.

**Review by Calinou — APPROVED** [review]
Code looks good to me.

**Comment by AThousandShips** [comment]
There's been some changes to the unit test system so a rebase to make sure everything still works right would be good

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase), you should remove the merge commit and rebase instead

**Comment by AThousandShips** [comment]
You need to reset your branch to a safe state, and then rebase, do `git reset --hard f359115`

**Comment by 2nafish117** [comment]
Ah, thank you @AThousandShips, I think it looks good now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
