### PR TITLE
HTML5: Handle `GODOT_VERSION_STATUS` env var in `@GODOT_VERSION@`

### PR DESCRIPTION
**Pull request by akien-mga**
Follow-up to #51002.

### CODE REVIEW

**Review by Faless — APPROVED** [review]
Look good! :+1:

**Comment by Faless** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.4.

**Pull request merged**
