### PR TITLE
pcre2: Update to upstream version 10.42 (reverted)

### PR DESCRIPTION
**Pull request by akien-mga**
Changelog: https://github.com/PCRE2Project/pcre2/blob/pcre2-10.42/ChangeLog

This should also fix support for RISC-V architectures, at least in the sljit library.
@aaronfranke Could you test and confirm?

I see that upstream sljit is fairly active still improving riscv support (https://github.com/zherczeg/sljit/commits/master), so it might be that the current snapshot as of pcre2 10.42 doesn't work fully yet. If so we can postpone enabling the lib on RISC-V to a future release (or maybe keep building the regex module, but just disable JIT with `env["builtin_pcre2_with_jit"]`, as we already do for Web).

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
This compiles on RISC-V (`scons use_llvm=yes` on a rv64gc virtual machine / emulator).

**Comment by vonagam** [comment]
This PR caused those lines to appear (repeated multiple times) in test logs at the start.
```
ERROR: Condition "p_ptr == nullptr" is true.
   at: free_static (core/os/memory.cpp:148)
```
While tests do not fail because of that, this does not seem right.

**Comment by akien-mga** [comment]
Backtrace:
```
(gdb) bt
#0  Memory::free_static (p_ptr=0x0, p_pad_align=false) at core/os/memory.cpp:149
#1  0x0000000006c247fb in _regex_free (ptr=0x0, user=0x0) at modules/regex/regex.cpp:43
#2  0x0000000006c1cb84 in pcre2_match_32 (code=0xc9019b0, subject=0xc8a74c0, length=9, start_offset=0, options=0, match_data=0xc830060, mcontext=0xc9863b0) at thirdparty/pcre2/src/pcre2_match.c:6846
#3  0x0000000006c25c85 in RegEx::search (this=0x7fffffffc300, p_subject=..., p_offset=0, p_end=-1) at modules/regex/regex.cpp:219
#4  0x00000000057cfee7 in TestRegEx::DOCTEST_ANON_FUNC_6556 () at ./modules/regex/tests/test_regex.h:81
#5  0x00000000053d282d in doctest::Context::run (this=0x7fffffffd0e0) at ./thirdparty/doctest/doctest.h:6930
#6  0x00000000057d5540 in test_main (argc=2, argv=0x7fffffffd728) at tests/test_main.cpp:174
#7  0x0000000005393ec2 in Main::test_entrypoint (argc=2, argv=0x7fffffffd728, tests_need_run=@0x7fffffffd1bf: true) at main/main.cpp:608
#8  0x0000000005333cc2 in main (argc=2, argv=0x7fffffffd728) at platform/linuxbsd/godot_linuxbsd.cpp:55
```

**Comment by akien-mga** [comment]
I reverted the change for now with d0398f62f08ce0cfba80990b21c6af4181f93fe9. I'll reopen the PR as a draft until we find how to change `modules/regex/regex.cpp` to take the internal memory change into account.

**Pull request merged**
