### PR TITLE
Fix editor setting value is back to default

### LINKED ISSUE #15449: Some editor properties are no longer persistent
**Godot version:**

380169e3efb959cfeaa3884a3cd440ab84bff9ae

**OS/device including version:**

linux

**Issue description:**
The capitalize_properties, disable_inspector_folding, restore_scenes_on_load
and possibly other properties are reset to default after a tool restart.

**Steps to reproduce:**
Set the property in the editor settings, restart the tool.

diff --git a/editor_settings-3.tres b/editor_settings-3.tres

```
-interface/editor/capitalize_properties = false
-interface/editor/disable_inspector_folding = true
+interface/editor/capitalize_properties = true
+interface/editor/disable_inspector_folding = false

-interface/scene_tabs/restore_scenes_on_load = true
+interface/scene_tabs/restore_scenes_on_load = false
```

```
editor/editor_node.cpp:
	property_editor->set_enable_capitalize_paths(bool(EDITOR_DEF("interface/editor/capitalize_properties", true)));
	property_editor->set_use_folding(!bool(EDITOR_DEF("interface/editor/disable_inspector_folding", false)));
```

### PR DESCRIPTION
**Pull request by volzhs**
Fix #15449

### CODE REVIEW

**Comment by capnm** [comment]
LGTM
I can't say anything to the coding style, I just tested the theme switching and the props.
This time everything seems to work, thanks!

I found 4 more properties, they show always after the tool restart for the default values
a changed state (but looks more like a cosmetic problem):
```
docks/scene_tree/relationship_line_color
editors/3d/grid_color
interface/editor/dim_amount
interface/editor/dim_transition_time
```
But, if you want to do it perfectly …

gobot2018-01-07

**Comment by akien-mga** [comment]
CC @djrm

**Comment by volzhs** [comment]
I just tested these option with this PR.
```
docks/scene_tree/relationship_line_color
editors/3d/grid_color
interface/editor/dim_amount
interface/editor/dim_transition_time
```
but it's not back to default value, stays changed after restarting editor.

**Comment by akien-mga** [comment]
@volzhs I think @capnm meant that those four options should the "revert" button even when they were never changed by the user (because they are changed by the theme itself).

**Pull request merged**
