### PR TITLE
tilemap_editor: change move and duplicate tools

### PR DESCRIPTION
**Pull request by paulloz**
This is a proposition regarding #21123.  

 _ | Old behaviour | New behaviour
-- | -------------- | ----------------
Duplicate / Copy |  | 
Move / Cut |  | 

Bests.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good to me :)

CC @MarianoGnu

**Comment by paulloz** [comment]
One thing to note, I could not find any good icon for `cut` so I left the `move` one for now.

**Comment by akien-mga** [comment]
> One thing to note, I could not find any good icon for cut so I left the move one for now.

There's the `ActionCut` icon you could use for that.

**Comment by paulloz** [comment]
Well… I've been scrolling the icon folder for some time looking around for that and didn't see this one at the very top of the list… 🤔  
I feel a bit dumb, let me change this before you can merge.

**Comment by akien-mga** [comment]
```
$ cat editor/editor_icons.gen.h | grep -i cut
        "ActionCut",
        "ShortCut",
```
;)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
