### PR TITLE
Update: Turkish translations.

### PR DESCRIPTION
**Pull request by nuriu**
Translations will be updated in this PR until completely done.

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you submit those directly on our Weblate instance? https://hosted.weblate.org/projects/godot-engine/godot/
The translations in git are then synced every now and then from Weblate, so merging PRs directly would make this workflow a bit harder.

**Comment by akien-mga** [comment]
Also, unless Turkish from Turkey is very different from "global" Turkish, I would advise to drop the `_TR` part and let this be the global Turkish translation. It's a lot of work if different translators have to maintain tr_TR, tr_IR, tr_BG, tr_DE, etc. If those distinctions are important, they could then be created by copying the "global" Turkish one and adapting what needs to be.

**Comment by nuriu** [comment]
I changed it to global within second 10% of all lines. I don't have Weblate account so if it wouldn't be problem, i want to continue translate it within this pr. (10% by 10%)

**Comment by akien-mga** [comment]
Well as you can see on Weblate there's already a work-in-progress Turkish translation, so it would be really best to handle it all here. It's an open source hosted service so you can make an account for free.
I'm not particularly looking forward to having to merge manually conflicts between your translation in git and that of the other translators in Weblate :)

**Pull request closed without merging**
