### PR TITLE
Exposing more of bullets 6DOF spring constraints

### PR DESCRIPTION
**Pull request by sdfgeoff**
I went through and added all the other bullet SpringConstraint parameters to the Generic6DOFJoint node.

I haven't written getters because I can't really see much of a use case there. If you think it's super important, then I can do so.

[PhysicsJointTests.zip](https://github.com/godotengine/godot/files/2572054/PhysicsJointTests.zip)

### CODE REVIEW

**Comment by sdfgeoff** [comment]
I talked to Andrea, I'll add the getters.

**Comment by akien-mga** [comment]
There are some trailing spaces to remove: https://travis-ci.org/godotengine/godot/jobs/453962036

And the added enum values should also be handled in the GodotPhysics backend (even if unimplemented, just do nothing) otherwise we get warnings: https://travis-ci.org/godotengine/godot/jobs/453962037

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by AndreaCatania** [comment]
Yes, can be merged for me

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I'm getting this error when opening the project manager or any project:
```
ERROR: add_property: Object already has property: Generic6DOFJoint
   At: core/class_db.cpp:942.
```
Not sure what would cause it in this PR but the timing makes it a suspect :)

**Comment by sdfgeoff** [comment]
Hmm yes, the timing does make this suspect. I would have assumed that would mean a duplicate "ADD_PROPERTYI" in physics_joint.cpp, but I'm not seeing one at the moment.

I'll investigate more tomorrow.

**Comment by nthrack** [comment]
When creating a Physical Bone for a 3d Skeleton and setting Joint -> Type -> 6DOFJoint,
parameters realative to Angular/Linear Spring for all axis are missing.

image

**Comment by akien-mga** [comment]
The error is fixed in #23835.

**Pull request merged**
