### PR TITLE
Add ord() function to return Unicode code point of a string of length one

### PR DESCRIPTION
**Pull request by deepmax**
This function acts as same as python's `ord()`:

> Given a string of length one, return an integer representing the Unicode code point of the character...

Of course, we can have the Unicode code point of a character using `ord_at` or something else, however by this deterministic function, we can use characters in enums:

```
enum {
  A = ord('A'),
  B = ord('B'),
  STAR = ord('*')
}
```

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Would be cool to have the same function in visual script as well.

**Comment by akien-mga** [comment]
Sorry for the late review. IMO it's fine to add `ord()`, but then we'd also need to inverse method `chr()`.

**Comment by bojidar-bg** [comment]
@akien-mga Something like #6692?

**Comment by akien-mga** [comment]
Indeed :D Then my last nitpick would be to move the definition of the `ord` builtin next to `char`'s in the enums/switch, for consistency. And the VisualScript builtin could be implemented similarly to `char` in #6692.

**Comment by akien-mga** [comment]
Still two things pending for this PR:
- Move the definition of the `ord` builtin next to `char`'s in the enums/switch, for consistency.
- The VisualScript builtin for `ord` should be implemented similarly to `char` in #6692.

**Comment by bojidar-bg** [comment]
>* Move the definition of the ord builtin next to char's in the enums/switch, for consistency.

This will break binary compatibility of compiled scripts, as well as VisualScripts, so it would be better to add it to the end.

**Comment by akien-mga** [comment]
I'm pretty sure binary compatibility is broken already between 3.1 and master, and it's not expected to be kept between minor versions.

For VisualScript, do you mean it would make .vs files unreadable? If so that's a big design problem.

**Comment by bojidar-bg** [comment]
@akien-mga Given that VisualScriptBuiltinFunc-s are serialized as an integer, I guess it would.
https://github.com/godotengine/godot/blob/dd2cd06165670bb0d78bf4aa397935be15716e76/modules/visual_script/visual_script_builtin_funcs.cpp#L1335

I guess it might be worth opening an issue about it.

**Comment by akien-mga** [comment]
Rebased on `master` and implemented this:

> Move the definition of the `ord` builtin next to `char`'s in the enums/switch, for consistency.

I did not add the VisualScript implementation though.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
