### PR TITLE
Add Soft Very Low shadow quality mode for 3D

### PR DESCRIPTION
**Pull request by Calinou**
This can be used to improve 3D shadow rendering quality at little performance cost. Unlike the existing Hard setting which is limited to variable shadow blur only, it works with both fixed blur and variable blur.

### Soft Very Low (new)

*Performs nearly as well as Hard with better quality. It's more grainy than Soft Low, so using lower blur values is recommended.*

### Soft Low

<details>
<summary>Editor comparison</summary>

~~*Performance estimations are included in the top-right corner of every image.*~~
**Edit:** These estimations are inaccurate because the CPU time measurement is also taken into account. In practice, I can get a more significant performance boost with shadow quality set to Soft Very Low.

### DirectionalLight3D (fixed blur)

| Soft Ultra | Soft High | Soft Medium | Soft Low | Soft Very Low | Soft Hard |
|-|-|-|-|-|-|
|  |  |  |  |  |  |

### DirectionalLight3D (variable blur)

| Soft Ultra | Soft High | Soft Medium | Soft Low | Soft Very Low | Soft Hard |
|-|-|-|-|-|-|
|  |  |  |  |  |  |

### SpotLight3D (fixed blur)

| Soft Ultra | Soft High | Soft Medium | Soft Low | Soft Very Low | Soft Hard |
|-|-|-|-|-|-|
|  |  |  |  |  |  |

### OmniLight3D (variable blur)

| Soft Ultra | Soft High | Soft Medium | Soft Low | Soft Very Low | Soft Hard |
|-|-|-|-|-|-|
|  |  |  |  |  |  |
</details>

### CODE REVIEW

**Comment by clayjohn** [comment]
#53961 doesn't produce hard shadows, it just removes the per-pixel rotation of the vogel disk. I'm not really sure what the benefit of doing that would be. Note especially, that the calculations for rotating the vogel disk still take place, so there will be no performance benefit. 

I'm not sure that a global override to produce hard shadows makes sense. In other words, why would we take more than one sample when calculating hard shadows?

**Comment by Calinou** [comment]
> I'm not sure that a global override to produce hard shadows makes sense. In other words, why would we take more than one sample when calculating hard shadows?

Indeed, there is no benefit in doing so.

> I'm not really sure what the benefit of doing that would be. Note especially, that the calculations for rotating the vogel disk still take place, so there will be no performance benefit.

Several people requested a way to disable dithering while still using soft shadows, which is currently not possible in `3.x`. Dithering doesn't always go well with games that use a flat color/lowpoly aesthetic, since you want to avoid having a noisy look.

**Comment by Calinou** [comment]
I reworked this PR to add a Soft Very Low quality setting as requested.

**Review by clayjohn — CHANGES_REQUESTED** [review]

**Review by clayjohn — APPROVED** [review]
Looks great! Thanks for sticking to it and responding to feedback!

**Pull request merged**
