### PR TITLE
Add math operators to Visual Shader node names for easier and simpler searching

### LINKED ISSUE #5663: Allow searching Visual Shader nodes by the math operator symbol instead of just by name (example: * or + instead of "multiply" or "add")
### Describe the project you are working on

3D Games

### Describe the problem or limitation you are having in your project

My 3D game has a lot of custom shaders where I make use of the Visual Shader editor. Everytime I need a operand Node, I have to type the name of the math operation. For example: "sum", "multiply" (or just "mult"), "sub", etc:

image

In big shaders, with lots of nodes, sometimes it gets annoying to always type the names for operator nodes like these.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. **Add a way to add aliases/tags to VS node names** that are picked up when searching nodes. Just like when searching a blog post in a blog, for example.
2. **Or add a way to search by the operator symbol,** not just by name, for example: `*`.

This would be similar to Unreal Engine:

multiply

subtract

divide1

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

My proposal focuses on implementing the enhancement `2` from above, which would be simpler and easier to implement.

I would just update the Node names in the "Create Shader Node" dialog, appended with the operators.

For example, instead of calling the node "Multiply", call it `Multiply (*)`, this way, both the name and the operand are picked up by the search:

image

image

image

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, because it requires changing the names of many existing built-in Visual Shader nodes.

### Is there a reason why this should be core and not an add-on in the asset library?

As far as I know, no, because it requires changing the names of many existing built-in Visual Shader nodes.

### PR DESCRIPTION
**Pull request by alfredbaudisch**
This change makes it easy, in the "Create Shader Node" dialog, to search for VS nodes by just typing the operator. For example, instead of typing "multiply", you can just type "*" and multiply nodes will be listed.

Searching by name still works as you can see in the example video.

This feature is inspired by Unreal Engine node graph editor's UX.

Implements and closes https://github.com/godotengine/godot-proposals/issues/5663

https://user-images.githubusercontent.com/248383/198071434-cb74ba8c-6e20-4965-9b87-5410d0979080.mp4

### CODE REVIEW

**Comment by QbieShay** [comment]
@Chaosus does this break compatibility?

**Comment by alfredbaudisch** [comment]
> @Chaosus does this break compatibility?

@QbieShay what does it affect in this case? Because the original Node names are still preserved in the graph, the names with operators appear only in the "Create Shader Node" dialog and in the search.

**Comment by alfredbaudisch** [comment]
> @Chaosus does this break compatibility?

I figured it out here. From what I test, it doesn't break compat:

- I created a project and a Visual Shader with Godot4-beta3.
- I then opened the project with Godot with this change and it works.
- Then vice-versa.

```
[sub_resource type="VisualShaderNodeFloatOp" id="VisualShaderNodeFloatOp_j0vv5"]
operator = 2
```

The reason is that the Nodes in the graph do not keep the names with the operators.

image
image

**Comment by Chaosus** [comment]
> does this break compatibility?

Nah, it's just a some sort of small UI enhancement. Make sense to me.

**Review by Chaosus — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Looks great, thanks!

**Comment by Calinou** [comment]
Out of curiosity, can this PR be remade for `3.x` as well?

**Comment by alfredbaudisch** [comment]
> Out of curiosity, can this PR be remade for `3.x` as well?

I'm checking it out.

**Pull request merged**
