### PR TITLE
Overridden properties link to definition in Godot Docs

### PR DESCRIPTION
**Pull request by joshdegraw**
This is the in-progress implementation of https://github.com/godotengine/godot-docs/issues/4432

Right now the XML generator has been modified to contain the new data, and I am now in the process of editing makerst.py to format it properly.

### CODE REVIEW

**Comment by joshdegraw** [comment]
I had to take some time due to a house flood, but I am planning on finishing this PR ASAP.

**Comment by joshdegraw** [comment]
I kept the "overridden" property in the PropertyDoc struct in doc_data.h. Everything appears to be working. I looked for other things that utilize the overridden property and couldn't find anything. If we're happy with that being removed, I can go ahead and amend my commit to remove that struct doc, otherwise this PR can be accepted as everything appears to be working.

**Comment by joshdegraw** [comment]
@Calinou Only asking since I've seen your eyes on this PR-- is there anything I need to do in order to get this merged?

**Comment by Calinou** [comment]
> @Calinou Only asking since I've seen your eyes on this PR-- is there anything I need to do in order to get this merged?

You need to rebase it, as the PR now has merge conflicts.

**Comment by mhilbrunner** [comment]
Bump :)

**Comment by pycbouh** [comment]
Superseded by https://github.com/godotengine/godot/pull/55559. Thanks for your contribution nonetheless! You've been attributed in the new PR for your efforts.

**Pull request closed without merging**
