### PR TITLE
Fix shader crashing when attempting to access `length()` at global space

### LINKED ISSUE #59727: Shader code crash when assigning a vec3 `length` to a const.
### Godot version

3.4.4-stable

### System information

Ubuntu 20.04

### Issue description

Uncommenting the line in the script below crashes Godot for me.

```
shader_type spatial;

const vec3 COLORS[] = {
	vec3(1, 1, 1),
	vec3(0, 0, 0)
};

// this one crashes Godot
//const float color_count = float(COLORS.length);
// this is working
const float color_count = 2.0;

void fragment() {
	float z = (CAMERA_MATRIX * vec4(VERTEX, 1.0)).z;
	ALBEDO = COLORS[int(mod(z * color_count, color_count))];
}
```

### Steps to reproduce

Use the project attached or just copy paste script attached and uncomment the marked line.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/8388449/test.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/59727

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
Looking through this section of the code. Are the results ever valid if p_block is null? I'm wondering if we should just check the validity of p_block once, earlier in the function.

**Comment by Chaosus** [comment]
The `p_block` is null when it is in the global space. The check is already exist at [shader_language:5047](https://github.com/godotengine/godot/blob/f3fe2631da1602df9312a4cd64c7b68d2f94f08a/servers/rendering/shader_language.cpp#L5047) line.

**Comment by Chaosus** [comment]
@clayjohn The first condition requires for array completion eg when user enters array + '.' (to suggest `length()` function). The else statement below may accept null blocks to access members in global space as well as in local space.

**Review by clayjohn — APPROVED** [review]
Looks good to me. Thank you for your quick responses!

**Pull request merged**
