### PR TITLE
Make dialogs translatable

### PR DESCRIPTION
**Pull request by Geequlim**
I am not sure dialogs should be translated as it is not located under tools/editor folder. So feel free to drop this PR if it is not necessary.

### CODE REVIEW

**Comment by neikeq** [comment]
In the case they are not translatable, couldn't we just change the name in the editor using the following?:
``` C++
dialog->set_title("");
dialog->get_ok()->set_text("");
dialog->get_cancel()->set_text("");
```

**Comment by Geequlim** [comment]
I'm not really understand with you :(

Is `""` to be replaced with `TTR("default")` ?

**Comment by neikeq** [comment]
@Geequlim `""` is just an example string. Replace it with the actual text, e.g: `TTR("Select a File")`. I said that we could call those methods for each dialog instance in the editor. That's the only solution I can think of right now, supposing you can't translate the strings in `scene/gui` ofc.

**Comment by Geequlim** [comment]
@neikeq Thanks for your fast explaination. I will try to find out dialogs to set titles and buttons instead :)

**Comment by neikeq** [comment]
After having a look at `TTR()`, it is only present with `TOOLS_ENABLED`. So adding some `#ifdef'`s should make this PR work.
@akien-mga Wouldn't it be good to define `TTR()` in non-tool builds too? e.g:
``` C++
String TTR(const String& p_text) {
#ifdef TOOLS_ENABLED
	if (TranslationServer::get_singleton()) {
		return TranslationServer::get_singleton()->tool_translate(p_text);
	}
#endif
	return p_text;
}
```
This way we wouldn't need `#ifdef` blocks.

**Comment by akien-mga** [comment]
@neikeq Yeah, I thought it was done this way already :)

**Comment by neikeq** [comment]
@Geequlim It looks like what we were looking for was `RTR()` :D

**Comment by Geequlim** [comment]
Fixed :)  
Sent from [Nylas N1](https://nylas.com/n1?ref=n1), the extensible, open source
mail client.  

On 5月 30 2016, at 9:29 晚上, Ignacio Etcheverry &lt;notifications@github.com&gt;
wrote:  

> [@Geequlim](https://github.com/Geequlim) It looks like what we were looking
for was RTR() :D

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly, [view it on GitHub](https://github.com/godotengi
ne/godot/pull/4902#issuecomment-222492964), or [mute the thread](https://githu
b.com/notifications/unsubscribe/AGpFTB1wL1oKskdr1WJzM8K8dWKTY_DRks5qGuZBgaJpZM
4IpnuZ).

**Comment by akien-mga** [comment]
I'll have to fix the extract.py script to actually parse ``RTR()`` :P

**Pull request merged**
