### PR TITLE
Fix bug causing `project.godot` to be ignored when `project.binary` is missing

### PR DESCRIPTION
**Pull request by m4gr3d**
Addresses the comment made in https://github.com/godotengine/godot/pull/42980/files/37d515e99c2da449397511cbc9b25fee84dd66fc#diff-d06617966387fb7135d4af8cf52217b94e7a4c658c6ed9f259bbf8cd801e31d5.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I don't understand the problem. The removed `return`s will only execute if the file exists, but can't be loaded, e.g. it's corrupted or not accessible. btw the same piece of code is used by the editor. If `project.godot` wasn't loading, you wouldn't be able to edit the project.

**Comment by m4gr3d** [comment]
> I don't understand the problem. The removed `return`s will only execute if the file exists, but can't be loaded, e.g. it's corrupted or not accessible. btw the same piece of code is used by the editor. If `project.godot` wasn't loading, you wouldn't be able to edit the project.

I described the issue in https://github.com/godotengine/godot/pull/42980#discussion_r594759905_.
For development purposes, we're loading the godot project using the text-based `project.godot` file from the Android apk so the `project.binary` file doesn't exist. With the current logic, this fails with error `19` (`ERR_CANT_OPEN`) which causes the current logic to abort.

Why `ERR_CANT_OPEN` is returned when the file is not present instead of `ERR_FILE_NOT_FOUND` is probably a separate issue, but at the least based on https://github.com/godotengine/godot/pull/42980, the intent was not to abort for other errors besides `ERR_FILE_NOT_FOUND` but just to log it, so this PR addresses that.

**Comment by KoBeWi** [comment]
> Why ERR_CANT_OPEN is returned when the file is not present instead of ERR_FILE_NOT_FOUND is probably a separate issue

And that is a bug that should be fixed. This PR just makes a workaround.

**Comment by m4gr3d** [comment]
> > Why ERR_CANT_OPEN is returned when the file is not present instead of ERR_FILE_NOT_FOUND is probably a separate issue
> 
> And that is a bug that should be fixed. This PR just makes a workaround.

Yes and no. The bug should indeed be investigated and fixed if it's an actual issue. 

PR #42980 however changed the original behavior and thus introduced a regression in behavior; this PR resolves that. There is nothing in the function comment or in PR #42980 that states that the logic should abort early if the error is not `ERR_FILE_NOT_FOUND`.

**Review by akien-mga — APPROVED** [review]
That change is good, but indeed the `ERR_CANT_OPEN` issue is a bug and should also be fixed.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Pull request merged**
