### PR TITLE
polygon path finder demo is now interactive and dynamic

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by reduz** [comment]
oh this class will go away soon, use Navigation2D &  NavigationPolygon

**Comment by lordadamson** [comment]
Goddamn it I spent the whole night doing this haha. okay I guess, looking forward to seeing the actual feature implemented in godot 2.1

**Comment by akien-mga** [comment]
Well I guess it could still be merged as a replacement for the current polygon_path_finder demo (in `demos/3d`). Or should we drop the polygon_path_finder demo before releasing 2.0?

**Comment by lordadamson** [comment]
@akien-mga I think the demo has already been dropped. I discovered now that I was working on demos from an older version of godot.

**Comment by akien-mga** [comment]
Nope it's here: https://github.com/godotengine/godot/tree/master/demos/3d/polygon_path_finder
It uses 3D nodes, so I moved it to the 3d folder.

**Comment by lordadamson** [comment]
oh okay then! yeah, I found it very weird that it was using 3d nodes.

**Pull request closed without merging**
