### PR TITLE
Fix and make Tween node less confusing

### LINKED ISSUE #19779: A few problems with Tween time keeping
87f48e7
There's a few bugs here. It's advertised that `is_active` is about the state of the processing of the tween rather than it being in the middle of tweening which is fine, I'd rather have it called `is_processing` since it's clearer but oh well (that's to say just remove `is_active`)

Then we have `get_runtime()` which should return the total time necessary to complete the queue of tweens which returns 0 if `is_active()` is false. `get_runtime()` should be independent of `is_active`.

Then we have `is_stopped()` that relies on `tell()`, but once the tween runs for the first time `tell()` returns same as `get_runtime()` which is a bug. I haven't played around with changing up tween properties/duration, but it's clear that `tell()` should reset to 0 once all tweens are completed which it isn't, even after the tween is completely stopped with `stop_all()`. Look at the output while pressing "ENTER" multiple times in a row. `tell()` is triggered in `_input`.

[godot-dbg.zip](https://github.com/godotengine/godot/files/2136424/godot-dbg.zip)

*edit*
speaking of which, if we can set tween to process on `idle` or `physics` frames, why does `is_processing` return false even after you `start()` the tween?!

### PR DESCRIPTION
**Pull request by razcore-rad**
I've made the following changes:
- make `is_active` the main way of keeping track of tween
  processing/activity, meaning that `is_active` will now return
  `false` if all tween actions have finished or if it isn't started
  or if it was stopped via `set_active(false)` or any other mode
- removed `is_stopped` because is redundant now
- `tell()` now reports correct values

The above meant that we don't have to keep track of yet another variable
`available` since everything is based on `*processing_internal` so I
removed it, likewise it's own local `processing` variable was removed,
as well as the "double" `_set_process` which it feels more like a hack.

~What wasn't changed:~
~- `tell()` still returns max value (i.e. `== get_runtime()` when all tweens `finish`)~

*More testing is needed*. So far I've tested repeat on/off, delay,
`is_active()` working corretly, `set_active(true), set_active(false)`,
but probably more tests are necessary, all the resets, stops, resume
etc.

_Bugsquad edit: fixes #19779_

### CODE REVIEW

**Comment by RKelln** [comment]
I was having a lot of issues with tweens the other day but I haven't had time to write up the issue. Sorry! It's on my todo list.
@razcore-art  I'll attach my demo so you can use it for testing your new code. 
In the demo when you press the "Demo" button both panels tween alpha to 0. The first time things work, but after that things get weird. Currently, the first/left panel does not repeatedly tween correctly, but the second/right panel does using a workaround ( setting `repeat = true` and `set_active(false)` on `tween_completed`).
[Demo_Tween_Bug.zip](https://github.com/godotengine/godot/files/2149621/Demo_Tween_Bug.zip)

**Comment by razcore-art** [comment]
@RKelln 
I'm not entirely sure I understood exactly from the description so I'd appreciate if you could check this gif out and tell me if it's the expected behavior. Thanks
godot-tween

**Comment by RKelln** [comment]
Thanks razcore, that is actually working better than current code. Here is mp4 of what happens on 3.0.4:

tween bug on godot 3 0 4

**Comment by akien-mga** [comment]
Thanks, looks good!

**Comment by GWRon** [comment]
Wouldn't it make sense to additionally emit a new signal ("tween_completed_all()") so chained tweens still emit the basic "tween_completed()" signal (keeps it backwards compatible)?

Being new to Godot I just fighted this lunch hour with a sequential tween chain and found it odd to have an extra variable which needs to be adjusted to the amount of chain elements (and once it reaches 0, the tween _really_ finished).

**Pull request merged**
