### PR TITLE
Replace C system headers by C++ ones

### PR DESCRIPTION
**Pull request by sondredl**

### CODE REVIEW

**Comment by timothyqiu** [comment]
Any reason why these should be preferred?

Also AFAIK, using headers like `<cstring>` guarantees that symbols exist in the `std` namespace, but not necessarily in the global namespace.

**Comment by sondredl** [comment]
> Any reason why these should be preferred?
> 
> Also AFAIK, using headers like `<cstring>` guarantees that symbols exist in the `std` namespace, but not necessarily in the global namespace.

given that godotengine uses modern c++, the changes proposed comply  better with modern c++ standards. C++ headers provide stricter typing rules.

Like you point out, the changes increase namespace safety, which is desirable.
Additionally the C++ headers are already widely used in the code base, so these changes make the code base more consistent.

**Comment by sondredl** [comment]
does anybody know what causes that one workflow check to fail? I only have linux, so its a bit hard to reproduce the issue

**Comment by fire** [comment]
No idea:

```
x86_64-w64-mingw32-g++ -o platform\windows\os_windows.windows.template_release.x86_64.o -c -std=gnu++17 -fno-exceptions -Wctor-dtor-privacy -Wnon-virtual-dtor -Wplacement-new=1 -msse2 -ffp-contract=off -mwindows -O3 -Wall -Wextra -Wwrite-strings -Wno-unused-parameter -Wshadow -Wno-misleading-indentation -Wno-return-type -Walloc-zero -Wduplicated-branches -Wduplicated-cond -Wstringop-overflow=4 -Wattribute-alias=2 -Wlogical-op -Werror -Wno-unknown-pragmas -isystem thirdparty\glad -DNDEBUG -DSTRICT_CHECKS -DWINDOWS_ENABLED -DWASAPI_ENABLED -DWINMIDI_ENABLED -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DVULKAN_ENABLED -DRD_ENABLED -DD3D12_ENABLED -DGLES3_ENABLED -DEGL_STATIC -DMINGW_ENABLED -DMINGW_HAS_SECURE_API=1 -DMINIZIP_ENABLED -DBROTLI_ENABLED -DTHREADS_ENABLED -DCLIPPER2_ENABLED -DZSTD_STATIC_LINKING_ONLY -DUSE_VOLK -DVK_USE_PLATFORM_WIN32_KHR -DGLAD_ENABLED -DEGL_ENABLED -Ithirdparty\freetype\include -Ithirdparty\libpng -Ithirdparty\directx_headers\include\directx -Ithirdparty\volk -Ithirdparty\vulkan -Ithirdparty\vulkan\include -Ithirdparty\zstd -Ithirdparty\zlib -Ithirdparty\clipper2\include -Ithirdparty\brotli\include -Ithirdparty\angle\include -Iplatform\windows -I. -Ithirdparty\d3d12ma platform\windows\os_windows.cpp
```

This is what says fails.

**Comment by bruvzg** [comment]
There's no clear error in the log, so might be CI runner issue, I have restarted the failed job.

**Comment by adamscott** [comment]
> There's no clear error in the log, so might be CI runner issue, I have restarted the failed job.

It still fails, unfortunately.

**Comment by adamscott** [comment]
I'm closing this PR and related PRs #98905, #98906, and #98908 because [these kind of big changes usually require a proposal first](https://github.com/godotengine/godot-proposals). This is because, there, the community and core Godot maintainers can discuss on the merit of such proposals.

I'm closing #98880 and #98563 too because, like the previous ones, they are are essentially doing _nothing_. By nothing, I mean that they don't seem to solve real problems. I highly suggest you to read the [Best practices for engine contributors](https://docs.godotengine.org/en/stable/contributing/development/best_practices_for_engine_contributors.html) from our docs, especially [the best practices section](https://docs.godotengine.org/en/stable/contributing/development/best_practices_for_engine_contributors.html#best-practices). Number 2 says: "To solve the problem, it has to exist in the first place".

Are you actively using Doxygen and had issues with the current formatting? Did you get actually get problems with C functions clashing with C++ namespaces? If so, please state it in the description.

Talking about descriptions: especially if it's not a simple bug fix, it is vital to describe your PRs. This forces reviewers to checkout your code and try to understand what's the intent.

Don't hesitate to join our [Developers' Chat](https://chat.godotengine.org/) if you have questions or if you need help for your next PRs. We do even have a [\#new-contributors channel](https://chat.godotengine.org/channel/new-contributors)!

See you there!

**Pull request closed without merging**
