### PR TITLE
fix thread_local crash on MSVC

### LINKED ISSUE #40666: Crash with doctest on attempting to debug the editor when compiling with `tests=yes`
**Godot version:**
4.0-dev 5287124b720c860e36d2908283013d0e0e69b577

**OS/device including version:**
Windows 10
target=debug, bits=64
MSVC version 14.2, arch amd64
Happens in both VS2017 and VS2019.

**Issue description:**
Call stack from VS Code:
```
ntdll.dll!00007ffb47c1b810() (Unknown Source:0)
godot.windows.tools.64.4.exe!_malloc_base(unsigned __int64 size) Line 34 (c:\Users\Xrayez\AppData\Local\Programs\Microsoft VS Code\minkernel\crts\ucrt\src\appcrt\heap\malloc_base.cpp:34)
godot.windows.tools.64.4.exe!operator new(unsigned __int64 size) Line 35 (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\heap\new_scalar.cpp:35)
godot.windows.tools.64.4.exe!std::ios_base::_Init() Line 476 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xiosbase:476)
godot.windows.tools.64.4.exe!std::basic_ios<char,std::char_traits<char> >::init(std::basic_streambuf<char,std::char_traits<char> > * _Strbuf, bool _Isstd) Line 148 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\ios:148)
godot.windows.tools.64.4.exe!std::basic_ostream<char,std::char_traits<char> >::basic_ostream<char,std::char_traits<char> >(std::basic_streambuf<char,std::char_traits<char> > * _Strbuf, bool _Isstd) Line 33 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\ostream:33)
godot.windows.tools.64.4.exe!std::basic_ostringstream<char,std::char_traits<char>,std::allocator<char> >::basic_ostringstream<char,std::char_traits<char>,std::allocator<char> >(int _Mode) Line 453 (c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\sstream:453)
godot.windows.tools.64.4.exe!doctest::detail::`dynamic initializer for 'g_oss''() Line 2866 (d:\src\godot\thirdparty\doctest\doctest.h:2866)
godot.windows.tools.64.4.exe!__dyn_tls_init(void * __formal, unsigned long dwReason, void * __formal) Line 99 (d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\tls\tlsdyn.cpp:99)
ntdll.dll!00007ffb47c05021() (Unknown Source:0)
ntdll.dll!00007ffb47c05103() (Unknown Source:0)
ntdll.dll!00007ffb47c02ebc() (Unknown Source:0)
ntdll.dll!00007ffb47c51875() (Unknown Source:0)
ntdll.dll!00007ffb47c517d3() (Unknown Source:0)
ntdll.dll!00007ffb47c5177e() (Unknown Source:0)
```

Screenshot from Visual Studio:

Running the editor or tests without debugger works fine.

**Steps to reproduce:**
Compile the engine with `scons tests=yes`: #40696.

I'm using the [C++ extension for VSCode](https://code.visualstudio.com/docs/languages/cpp) to debug Godot with Visual Studio Windows debugger, with the configuration file similar to this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Godot: Editor",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/godot.windows.tools.64.4.exe",
            "args": ["--editor", "--path", "D:/bin/godot/projects/test"],
            "stopAtEntry": false,
            "environment": [],
            "externalConsole": true,
        },
    ]
}
```

**Minimal reproduction project:**
Happens even on project manager startup.

### PR DESCRIPTION
**Pull request by RevoluPowered**
Fixes #40666

### CODE REVIEW

**Comment by RevoluPowered** [comment]
@Xrayez can you please try this out, I could not get it to crash with this fix.

**Comment by Xrayez** [comment]
Yeah this fixes it, launched like 30 times to be sure. 👍

**Comment by RevoluPowered** [comment]
Reported: https://github.com/onqtam/doctest/issues/401

**Comment by RevoluPowered** [comment]
OK since this fix works, we now need to discuss if MD can be used in production.

It would be a good topic for a proposal, I will leave this open until we get a reply from onqtam / doctest.

**Pull request closed without merging**
