### PR TITLE
Add ability to load additional dynamic libraries for extensions

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR adds the ability to load dependent dynamic libraries for a GD extension similar to how this was implemented in GDNative.

### CODE REVIEW

**Review by vnen — APPROVED** [review]
LGTM

**Comment by mhilbrunner** [comment]
cc @reduz

**Comment by BastiaanOlij** [comment]
On a side note, I'm not sure this is actually needed for my OpenVR plugin. It looks like the plugin will load the dependent DLL automatically. We haven't finish the export code yet so it may be needed there to ensure the dependent DLLs get exported as well.

**Comment by akien-mga** [comment]
Closing for now as discussed with @BastiaanOlij, this can be re-assessed if/when there's a clearer use case for it:

```
<Akien> @mux213 What's the status on #52532 ? Is it still needed for OpenVR, and if not, potentially useful for other plugins?
<mux213> @akien I think we can close it, it doesn't seem to make a difference for me
```

**Pull request closed without merging**
