### PR TITLE
Restore support for minimal 3x3 autotile sets

### LINKED ISSUE #18959: Autotile 3x3 fix breaks compatibility with the common minimal 3x3 tileset
I would like to raise this issue in response to  #16511 and its fix #18619

**Issue description:** The mentioned pull release does allow uncommon tile configurations, but the fix itself completely breaks usability when using common tile configurations. Compare 
aa
 with and without #18619.

I would argue that the most common use case for 3x3 tilesets is found on this [site](http://www.cr31.co.uk/stagecast/wang/blob.html), specifically, the minimal 3x3 tileset with only 48 tiles. The code that #18619 removes was most likely put there to ensure that such tilesets work.

Now I agree that allowing uncommon tile bitmasks is a useful feature but I doubt most projects will make use of it. On the contrary, people will be confused as to why Godot doesn't support the simplest 48 tileset format shown above. As far as I understand, there is no easy way to fix this.

**Suggestion:** Add a bitmask mode such as BITMASK_3X3_MINIMAL that specifically supports the tileset above and runs the code removed by #18619. BITMASK_3X3 can be left as it is.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #18959. This PR adds a bitmask_mode called BITMASK_3X3_MINIMAL that allows support for the common 48 tiles autotiling sets.

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you squash the two commits together?

CC @MarianoGnu for review.

**Comment by MarianoGnu** [comment]
Thx a Lot for the PR, this keeps backward compatibility now (since 3x3_MINIMAL has the 1 index on the Enum) i was thinking if moving this from the tileset to the actual editor, but makes sense to remember the setting on the tile itself.

**Comment by MarianoGnu** [comment]
PR welcome :)

**Comment by mateusak** [comment]
@isaacremnant @MarianoGnu 

The best way to solve this is to address #18134
It'll add even more flexibility, yet making a minimal tileset possible.

**Pull request merged**
