### PR TITLE
[GDScript 2.0] Add `byte` Variable type

### PR DESCRIPTION
**Pull request by nonunknown**
I'm still no experienced contributor, I still need help in the following:

adding `var test:byte` to a script, still generates `No constructor for type byte`
add the key color and icon for byte type.

### CODE REVIEW

**Comment by Calinou** [comment]
Adding a new type to Variant has a significant cost, so it needs to be done carefully.

**Comment by bruvzg** [comment]
What's the purpose of `byte`? `Variant` still gonna use it's full size, so there's no obvious benefits over `int`.

**Comment by fire-forge** [comment]
What is the difference be between `byte` and `int`?

**Comment by fire** [comment]
Since there is no consensus and no proposal, is the pr archivable?

**Comment by akien-mga** [comment]
Closing as there's no proposal attached to this PR and no clear indication that this would have any use.

**Pull request closed without merging**
