### PR TITLE
Improve documentation related to anisotropic filtering

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of #64740.

See https://www.reddit.com/r/godot/comments/wung6z/rant_anisotropic_filtering/.

### CODE REVIEW

**Comment by tinmanjuggernaut** [comment]
> See https://www.reddit.com/r/godot/comments/wung6z/rant_anisotropic_filtering/.

Yes.

I use DDS, so they don't even have import settings. I wrote a script that iterates through every material and texture in my game to enable anisotropic filtering at runtime. If the setting is now in materials, hopefully this script is no longer needed. I haven't tested yet. 

However sometimes textures should have anisotropic filtering, but are not attached to a material. For instance TextureArrays on zylann's terrain. That needs an import setting or one at runtime.

**Review by skyace65 — APPROVED** [review]
Looks good!

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Thanks!

**Comment by FyiurAmron** [comment]
@Calinou a quick question: is there any way to set Linear Mipmap Anisotropic by default for all newly created BaseMaterial3Ds? I'm importing a huge batch of textures (and will probably will have to import more in the future) which all need anisotropy handled (floor/ceiling textures basically), and changing this manually on every material is tedious (to say the least).

**Comment by TokisanGames** [comment]
Don't use the standard material. Convert it to a shader material and use that. Or set all of your standard materials by code; a simple tool script can change them all.

**Comment by Calinou** [comment]
> @Calinou a quick question: is there any way to set Linear Mipmap Anisotropic by default for all newly created BaseMaterial3Ds? I'm importing a huge batch of textures (and will probably will have to import more in the future) which all need anisotropy handled (floor/ceiling textures basically), and changing this manually on every material is tedious (to say the least).

This is being tracked in https://github.com/godotengine/godot-proposals/issues/5228.

**Pull request merged**
