### PR TITLE
Implement p_width in canvas_item_add_polyline

### LINKED ISSUE #40845: canvas_item_add_polyline does not handle width
**Godot version:**
https://github.com/godotengine/godot/commit/00e1175b7dcd01be9b13c8fe852af68a916f45e6

**OS/device including version:**

Nvidia gtx 2080 series

**Issue description:**

Expect being able to draw polylines with width.

A polyline is drawn without width.

**Steps to reproduce:**

Call:

void RenderingServerCanvas::canvas_item_add_polyline(RID p_item, const Vector<Point2> &p_points, const Vector<Color> &p_colors, float p_width)

with a width.

Width is not set.

image

**Minimal reproduction project:**

No reproduction project, but the effect can be seen in this pr. https://github.com/godotengine/godot/pull/40513

### PR DESCRIPTION
**Pull request by lyuma**
Co-authored-by: K. S. Ernest (iFire) Lee <ernest.lee@chibifire.com>

Antialiasing is not implemented. We found two techniques which could be implemented.
- The first technique described at https://github.com/tyt2y3/vaserenderer and http://artgrammer.blogspot.com/2011/05/drawing-nearly-perfect-2d-line-segments.html uses a polygon mesh for the edge pixels with a vertex color gradient to alpha.
- The second technique described at https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc does antialiasing in the fragment shader, but requires a normal vector to be passed to the vertex shader.

Line width is used in pull request #40513 - Below is a screenshot showing the technique in use.
image

*Bugsquad edit:* Fixes #40845.

### CODE REVIEW

**Comment by fire** [comment]
Someone is questioning the supported status.

It is in vulkan but won't be in webgpu.

https://www.reddit.com/r/rust_gamedev/comments/evlwzo/wgpurs_how_to_specify_line_width_when_drawing/

**Comment by lawnjelly** [comment]
I haven't looked at the renderer in 4.x yet, but this looks ok for something basic. The existing GLES2 and GLES3 renderers for TYPE_LINE do something like this (they use GL_LINES for an anti-aliased line around the edge).

What kind of results does this produce? Especially on sharp corners. It would be nice to see some pics. :smile: It might be easy to add a bevel but not sure if it is required.

The lack of anti-aliasing could also be a thing, which might be easier using a shader approach (as detailed in the linked article).

**Comment by erictuvesson** [comment]
_fixes #40845_

**Comment by reduz** [comment]
This is kind of an issue I did not get into yet because Vulkan does not support antialiased lines, and I am not sure which approach is the best we can take to work around this problem. Geometry shaders would work but they are not supported on mobile.

**Comment by Chaosus** [comment]
Superseded by #43828, thanks for attempting to fix it anyway!

**Pull request closed without merging**
