### PR TITLE
Update the Android `fileLastModified` method to return values in seconds instead of milliseconds

### LINKED ISSUE #95576: Incorrect date of project in Android Editor
### Tested versions

- Reproducible in 4.3.stable ,4.3rc2

### System information

Android 11 - godot4.3.stable - redmi 10 2022

### Issue description

The dates of every project looks really wrong
Screenshot_2024-08-15-23-20-24-534_org godotengine editor v4
Screenshot_2024-08-15-23-30-38-383_org godotengine editor v4

### Steps to reproduce

Just create a new project. Quit to project list. See the date.
Another info that I don't know the relevance of, I installed the 4.3.stable as an update.
Meaning i didn't uninstall the previous version before installing 4.3.stable.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by m4gr3d**
Fixes https://github.com/godotengine/godot/issues/95576

### CODE REVIEW

**Review by adamscott — APPROVED** [review]

**Comment by akien-mga** [comment]
So is that the proper fix for https://github.com/godotengine/godot/issues/94416, as we had a hunch that Android file modification implementation might be buggy?

**Comment by m4gr3d** [comment]
> So is that the proper fix for #94416, as we had a hunch that Android file modification implementation might be buggy?

No that logic actually uses the unix version, not the Android one. 
From https://github.com/godotengine/godot/issues/94416#issuecomment-2267172619, the unix version seems to have a bug on Android devices.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
