### PR TITLE
Optimize image channel detection

### PR DESCRIPTION
**Pull request by reduz**
Speeds up compression

### CODE REVIEW

**Review by fire — APPROVED** [review]
For my test 8k image it reduced times by 2 seconds. https://github.com/fire/texture-import-godot-project/blob/main/peacock/japanese_shiny_embroidered_peacock_fabric_basecolor%20-%20Copy%20(10)%20-%20Copy%20-%20Copy.png

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Actually undid cherry-pick as it depends on `_get_color_at_of` which doesn't exist in `3.x`. Should be backported manually if anyone is interested.

**Pull request merged**
