### PR TITLE
Re-architecture of the Godot Android plugin. [3.2]

### PR DESCRIPTION
**Pull request by m4gr3d**
This PR revisits the Godot Android plugins' architecture.
This is done by leveraging the [Android library file format](https://developer.android.com/studio/projects/android-library#aar-contents). A Godot Android plugin is now defined as follow:

>  A Godot Android plugin is a regular Android library packaged as an aar archive file with the following caveats:
>  - The library must have a dependency on the Godot Android library (`godot-lib.aar`). A stable version is made available for each release.
>  - The library must include a `<meta-data>` tag in its manifest file setup as follow:
>  `<meta-data android:name="org.godotengine.plugin.v1.[PluginName]" android:value="[plugin.init.ClassFullName]" />`
>  Where:
>  
> 
> - `PluginName` is the name of the plugin.
> 
> - `plugin.init.ClassFullName` is the full name (package + class name) of the plugin class extending `GodotPlugin`.

At runtime, Godot (via `GodotPluginRegistry`) will parse the Android manifest, and retrieve all components with the specified `<meta-data>` tag. It'll then use reflection to instantiate and load the plugin class defined by `plugin.init.ClassFullName`. From there, the plugins follow the same lifecycle as with the previous architecture.

A nice side-effect of this new architecture is that we can remove all the gradle build and android manifest custom update logic, since we can just rely on the [Android library build and manifest merge mechanism](https://developer.android.com/studio/build/manifest-merge.html).

**Documentation update**: https://github.com/godotengine/godot-docs/pull/2979

**Note**: 
- This is a breaking / non-backward compatible change with the previous (v0) Godot Android plugin architecture. For backward compatibility in the `3.2.x` releases, the new system will work alongside the previous one. The previous one will be fully removed in Godot `4.0`.
- Just like the previous architecture, this requires the use of custom builds.
- This new architecture may be helpful for PR #26221, as the ARCore build dependencies no longer need to be included in Godot `core`. This would however limit ARCore to custom builds only.
- The updated architecture simplifies the process of bundling Android gdnative libraries with Android java libraries. See the updated documentation for details.

Example implementation: 
- Hello World reference plugin: https://github.com/m4gr3d/Godot-Android-Plugins/tree/master/hello_world
- Custom branch of the Godot Oculus mobile plugin: https://github.com/m4gr3d/godot_oculus_mobile/tree/2.0/plugin

### CODE REVIEW

**Comment by akien-mga** [comment]
I gave the PR a try rebased on the current `3.2` branch.

The non-custom build workflow still works as usual, so all good on this front.

When trying a custom build with no plugin and default settings, the build fails:
Screenshot_20200302_144634

I don't see new entries in the preset that I might have omitted to fill, so I assume it's an issue with this PR? I haven't tried a custom build in a while without this PR though, so it might be something that affects 3.2-stable custom builds too.

**Comment by m4gr3d** [comment]
> I gave the PR a try rebased on the current `3.2` branch.
> 
> The non-custom build workflow still works as usual, so all good on this front.
> 
> When trying a custom build with no plugin and default settings, the build fails:
> Screenshot_20200302_144634
> 
> I don't see new entries in the preset that I might have omitted to fill, so I assume it's an issue with this PR? I haven't tried a custom build in a while without this PR though, so it might be something that affects 3.2-stable custom builds too.

Looks like only the release portion of the build failed. Can you validate that the `android_source.zip` contains both debug and release artifacts?
It may be that generation of the release artifacts was omitted.

**Comment by akien-mga** [comment]
Thanks, I had omitted to build the release template as usually I do my tests with `custom_template/debug` only when using the non-custom build workflow, which works fine (unless I explicitly export a release build).

After building both debug and release templates and reinstalling the source archive, it works fine.

I'll now try the Hello World plugin to validate the workflow.

**Comment by akien-mga** [comment]
Thanks a lot!

Once the `3.2` docs are updated and maybe one or two plugins ported, it might be worth writing a blog post about the changes, WDYT?

**Comment by m4gr3d** [comment]
> Thanks a lot!
> 
> Once the `3.2` docs are updated and maybe one or two plugins ported, it might be worth writing a blog post about the changes, WDYT?

Yep, that sounds good!

**Comment by Shin-NiL** [comment]
Hello @m4gr3d 

I'm porting my plugins to use the v1 system, I was able to make my [share plugin](https://github.com/Shin-NiL/Godot-Android-Share-Plugin/tree/plugin-v1) to work as it has no additional dependencies, but I'm having some trouble with AdMob and I think you can help me.

1. Where can I declare the dependencies? I've tried to add:

```
[dependencies]
remote=["com.google.android.gms:play-services-ads:19.1.0"]
```

on the .gdap file, but it's not working.

2. Where can I create the plugin AndroidManifest? The final user needs to add their APP ID using metadata on the manifest file.

Thank you very much for your help.

**Comment by m4gr3d** [comment]
> EDIT 3: Well, after having a look at the exporter code, I've created an AndroidManifest.conf file inside the res://android/plugins directory and worked, is that the correct way to do?

@Shin-NiL The `AndroidManifest.conf` file is a remnant of the old system. While it'll work for `3.2.2+` (we're maintaining backward-compatibility), it's not recommended to mix the two, since it'll be removed in `4.0`.

So I can better understand your issue, prior to the new system, how did you instruct your users to add their APP ID?

**Comment by Shin-NiL** [comment]
@m4gr3d For Godot 3.2.1 the user must edit the AndroidManifest.conf distributed with the plugin. Before that I was using a very old SDK where the APP ID was not required.

**Comment by m4gr3d** [comment]
@Shin-NiL For this scenario, it's probably simpler to ask the user to directly edit the `res://android/build/AndroidManifest.xml` file and add their app id as directed in the [setup instructions](https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml).

You can provide a link to these [setup instructions](https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml) in your own plugin guide.

**Comment by Shin-NiL** [comment]
@m4gr3d It's an option, the only drawback is that this file is overridden when installing a new Android build template from editor.

**Comment by m4gr3d** [comment]
@Shin-NiL yes, although a typical user would rarely have the need to install new Android build templates often unlike us developers, so I see that as less of an issue.
Let's try that approach as a starter and we can iterate on the process based on user feedback.

**Comment by Shin-NiL** [comment]
@m4gr3d I got, let's try it, thank you very much.

**Comment by akien-mga** [comment]
> yes, although a typical user would rarely have the need to install new Android build templates often unlike us developers, so I see that as less of an issue.

In the future we do need to figure out a nice system for users to be able to upgrade their build templates versions without losing their customization. Upgrading from 3.2.2 to 3.2.3, etc. will always be a pain if you have any custom changes to the `build` folder.

**Comment by yalcin-ata** [comment]
Godot 3.2.2 RC1:

Is it on purpose that after installing the Android build template (Menu Project > Install Android Build Template) the created android/ directory is "visible" by Godot? Because for my plugin's res/ directory Godot creates .import files for the icons (.png) and gradle complains: "Resource and asset merger: The file name must end with .xml or .png". That's because of the "nature" of res/drawable/: they should contain only .xml and .png files.

If I remember correctly in previous versions the android/ directory was hidden (correctly).

**Comment by m4gr3d** [comment]
@yalcin-ata yes it's on purpose as the `res://android/plugins` directory can be used to install the new Android v1 plugins and thus need to be accessible by users.

I took a look a some of your instructions, and yes these practices are now disrecommended and highlight why the previous system was an issue.

I'd strongly recommend to move over to the new plugin architecture, but you can always throw a `.gdignore` file in your repo (since you're asking the user to clone the whole thing) as a workaround.
Bear in mind that the old architecture is fully removed for Godot 4.0, and so your plugin as is will no longer work in that version.

**Comment by yalcin-ata** [comment]
I am porting the current plugin (old version) to the new v1 (not public yet), so far it is working fine, but there are still some issues with the build process.

Ideally I would compile the .aar file and provide it as is. As the plugin is for Firebase, to compile the .aar file it needs a project specific google-services.json from the Firebase console.

I will dig in deeper, thank you for your answer.

**Comment by m4gr3d** [comment]
@yalcin-ata can you point to the firebase instructions about the json console file. It's possible you may just need to instruct the user to add that file in their `res://android/build` directory.

**Comment by yalcin-ata** [comment]
Thanks again for your help. I solved my problem.

It was a "special" case in my case because of the google-services the plugin depends on. The key was to remove the google-services.json from the library module (.aar), and also the lines regarding "...google-services..." from the build.gradle, and later add the missing parts to [GODOT-PROJECT]/android/build.
Adding all the library module's dependencies from build.gradle to the module's .gdap was also mandatory.
Hopefully very soon I can publish the Godot Firebase module v1 to the public!

Thank you!

**Comment by yalcin-ata** [comment]
@m4gr3d Is there a possibility - like in the previous version via gradle.conf and AndroidManifest.conf - to add some chunks to build.gradle and AndroidManifest.xml? When I add some stuff to those files manually the build system removes them again.

This is i.e. need for AdMob <meta-data .../> for custom AdMob App Id, or for "apply plugin: 'com...google-services'

**Pull request merged**
