### PR TITLE
Fixed fleeting window white screen on editor/game startup

### PR DESCRIPTION
**Pull request by Krakean**
Fixes small cosmetics issue #13381.
Before: https://i.imgur.com/rHeELJx.gifv
After: https://i.imgur.com/hkUIHld.gifv

### CODE REVIEW

**Comment by RoryMcMaster** [comment]
Fixes #11939 also (although, closed already)

Seems like this was a NVIDIA GPU issue only. I had my friend test it on his 1060 and, 1080, and the fleeting white screen was there. However, they tested it on their RX 470, 480 and Vega cards and the white screen issue never appeared.

This is freaking awesome.

**Comment by rokasv** [comment]
Issue still present across all 3.1 to 3.4.4 versions.

Empty project (boot splash replaced) opening up on Windows 10 
OpenGL ES 2.0 Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2:

**Comment by akien-mga** [comment]
Please open a new issue, this is a PR which was merged in 2017, it's not the proper place to keep track of 2022 issues.

**Comment by Calinou** [comment]
There's already an issue for this: https://github.com/godotengine/godot/issues/58056

**Pull request merged**
