### PR TITLE
Open internal visual script editor while use external editor is on

### LINKED ISSUE #19196: Visual Scripts cannot be edited when 'Use External Editor' is on
**Godot version:**
3.0.2

**OS/device including version:**
Window 7

**Issue description:**
When 'Use External Editor' is on, Visual Scripts are not opened in the internal editor. Instead the Visual Script file is sent to the external editor. 
There should be an option to exclude Visual Scripts from the external editor.

**Steps to reproduce:**
* Open a new project
* In Editor/Editor Settings activate 'Use External Editor'.
* Configure an external editor of your choice
* Open a new scene
* Add a node to the scene and create a Visual Script for that node.
* The script is opened in the external editor.

**Minimal reproduction project:**
n/a

### PR DESCRIPTION
**Pull request by volzhs**
Fix #19196

### CODE REVIEW

**Comment by Geequlim** [comment]
Maybe `Script::has_source_code()` is better for this kind of usage ?

**Comment by akien-mga** [comment]
> Maybe Script::has_source_code() is better for this kind of usage ?

I agree.

**Comment by neikeq** [comment]
> Maybe `Script::has_source_code()` is better for this kind of usage ?

Careful with this. It's not the same as the script not being able to have (textual) source code. It will return true for both GDScript and C# if the script is empty.

**Comment by akien-mga** [comment]
>  It's not the same as the script not being able to have (textual) source code. It will return true for both GDScript and C# if the script is empty.

Isn't it what we want though? It's fine to open an empty script in the external editor, what we need to avoid is to open non-textual "scripts" in the external editor, such as NativeScript and VisualScript.

**Comment by neikeq** [comment]
>>  It's not the same as the script not being able to have (textual) source code. It will return ~~true~~ for both GDScript and C# if the script is empty.
>
>Isn't it what we want though? It's fine to open an empty script in the external editor, what we need to avoid is to open non-textual "scripts" in the external editor, such as NativeScript and VisualScript.

Oops, I meant it will return `false` if the script is empty.

**Comment by akien-mga** [comment]
Hm ok, maybe we need a new `bool is_text_based()` method in `ScriptLanguage`?

**Comment by bojidar-bg** [comment]
That wouldn't handle the case of compiled gdscripts though; they are still part of GDScriptLanguage, but editing them would be a mess.

Maybe `has_source_code` can be changed to return `true` for empty scripts as well? (empty source != no source)

**Comment by volzhs** [comment]
I think it's related to #19225 in somehow.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.

**Pull request merged**
