### PR TITLE
One-directional collision layer check for rigid bodies and soft bodies

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Check for each body individually if it collides with the other one or ignores it.

When a body is being ignored, the other body's mass is considered infinite when applying impulses to avoid extra overlapping.

Implements https://github.com/godotengine/godot-proposals/issues/2775 for RigidBody and SoftBody.
Supersedes #49166.

### CODE REVIEW

**Comment by Calinou** [comment]
I was thinking about whether we should expose this as an opt-in project setting for `3.x`. Since `3.x` will remain around for a while after 4.0 is released, I think we should offer backwards-incompatible features optionally when it doesn't require too much effort.

**Comment by pouleyKetchoupp** [comment]
@Calinou That sounds like a good idea!

It should be relatively easy to do for 2D.

It would require a bit more work for 3D as we would have to make it fully compatible with Bullet as well. It's not the case for rigid body vs. rigid body collision. It should be possible, but hopefully it's not too complicated.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
looks great!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
