### PR TITLE
Use `qoa.c` and custom compress procedure

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Summary:
- `QOA_IMPLEMENTATION` and `QOA_NO_STDIO` defines moved to a separate `qoa.c` file, removing the need of C++-compliant patches;
- Adds a `_compress_qoa` alongside `_compress_ima_adpcm`, which is a safer and faster alternative to `qoa_encode` and is used on `AudioEffectRecord` to allow `FORMAT_QOA` to work.

### CODE REVIEW

**Comment by fire** [comment]
Can you push QOA with AudioEffectCapture to a branch?

**Comment by fire** [comment]
We added capture because we were unable to fix the Record’s crash.

**Comment by DeeJayLSP** [comment]
Optimized further by not allocating the full length to store 16-bit data, just enough for a QOA frame.

**Comment by DeeJayLSP** [comment]
I figured out why the implementation within `AudioEffectRecord` was crashing: the data size needs to be divided by 2 because it's always stereo.

**Comment by DeeJayLSP** [comment]
Addressing changes from https://github.com/godotengine/godot/pull/93831, which moved most of the WAV loading code from ResourceImporterWAV to AudioStreamWAV.

Just like `_compress_ima_adpcm` was moved from ResourceImporterWAV to AudioStreamWAV, I did the same move with `_compress_qoa`.

`AudioEffectRecord::get_recording()` should be able to work properly with FORMAT_QOA in both editor and template builds.

The `qoa.h` file is the same one from #98025, so that gets superseded by this.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
