### PR TITLE
Don't warn for UNUSED_PARAMETER in _process and _physics_process functions regarding delta

### PR DESCRIPTION
**Pull request by Ryan-000**

### CODE REVIEW

**Comment by AdriaandeJongh** [comment]
It is perhaps a logically-unjustifiable exception to not show the warnings in these particular functions, but i will admit this warning shows up so often in my projects that I’m kinda’ _for_ this change.

**Comment by Mickeon** [comment]
Very hacky and overly specific implementation but there's a clear annoyance at display here. Worth examining other, broader options.

**Comment by Mickeon** [comment]
... One could argue this should be a new warning that only applies to overridden methods, since having to match the inherited method's signature would mean that unused parameters are less likely to be accidents.
Not saying this is how we should go about it, this is merely an example.

**Comment by HolonProduction** [comment]
I know that kotlin and pythin linters which don't emit such warnings for overriden (and maybe also open) functions. This seems like a more useful solution to me.

That being said since both those languages allow passing args by name the requirements are different, in gdscript it's totally fine to have a different named arg.

**Comment by AThousandShips** [comment]
I'd say that doing this increases the risk of actual errors forgetting to use this argument 

I generally believe that hiding warnings should be as explicit as possible, and since it's so extremely simple to silence this I'd say it isn't justified to add this level of complexity to "solve" it

Instead I'd suggest:
* Overriden methods are inserted when auto completing them with `_` already prefixed, leaving you to *decide* to use it if you want
* Discuss (as a proposal) making this a general thing for overrides

**Pull request closed without merging**
