### PR TITLE
Added Xbox 360 Controller mapping for HTML5 output, see #3400

### PR DESCRIPTION
**Pull request by wass3r**
Little concerned about UID being the same as the already existing entry, but that's what the tool you linked to gave me.

### CODE REVIEW

**Comment by Hinsbart** [comment]
You're right to be concerned, as that mapping is not needed at all :P
As stated by the uid, that pad is a standard gamepad, according to the HTML5 specs.

This mapping applies to all controllers that have already been remapped by your browser.
(Only chrome does this on linux and both firefox and chrome do it for windows/xinput)
The second entry (the name of the pad) might be different, but we don't use that anyway.
It's just there so that us humans can tell which string belongs to which device ^^ 

When the mapping tool finds the device, it should already say "mapped: Yes", right?

**Comment by wass3r** [comment]
Thanks for the clarification. Actually, initially all the fields including UID were empty. I had to remove and replug the controller to get anything to show up. I don't recall whether it said it was mapped. I thought not, but I'm likely wrong.

In other words, you're looking for non-standard controllers to get added?

**Comment by Hinsbart** [comment]
Yes, we just need mappings that don't have "Default HTML5 Gamepad" as the guid.

And I think you can just set the device to "1" and then back to "0" to refresh gamepad info, instead of  re-plugging it (maybe I should add a button for this) ^^

**Comment by akien-mga** [comment]
Closing as per the above discussion, but feel free to further discuss what is needed to improve the current mappings :)

**Pull request closed without merging**
