### PR TITLE
Rename wonky NodeOneShot methods

### PR DESCRIPTION
**Pull request by TokageItLab**
The word breaks are quite strange and should be fixed.

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't think that's worth doing at this stage, even in 4.1. This kind of minor language improvement in the API is in scope for a major release, but not the kind of compat breakage we should allow ourselves in minor releases: it doesn't solve anything.

**Comment by Iniquitatis** [comment]
@akien-mga Not the easiest situation.
Can't say these changes are _that_ minor of an improvement, as they resolve technical debt and, most importantly, teach new users the proper naming conventions. On the other hand, it is understandable that it is undesirable to make breaking changes at the RC phase.
Still, I believe it would be preferable to break as much compatibility as needed right now (necessary evil), before the actual release, rather than putting it into backlog until the next major release and letting these minor annoyances pile up even more: 4.0 breaks enough compatibility already and we have a 3.0 -> 4.0 converter.

**Comment by YuriSizov** [comment]
> Still, I believe it would be preferable to break as much compatibility as needed right now (necessary evil), before the actual release

We are past this point. Consider RCs the actual release, which they tentatively are.

**Comment by TokageItLab** [comment]
We have decided not to do this, at least in the RC stage, but we think it should be done in minor releases as needed.
Wouldn't it be fine to have something like the 3.x->4.0 project converter for 4.0->4.1 as well?

**Comment by TokageItLab** [comment]
Close once. In any case, NodeOneShot seems to have a problem with the way it manages its state, so we may need to rework it a bit later.

**Pull request closed without merging**
