### PR TITLE
Add `override` mark to ResourceFormat class

### PR DESCRIPTION
**Pull request by ppphp**
Add `override` to class derived from `ResourceFormatSaver` and `ResourceFormatLoader`. It helps me understand codes.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
This is our general preference and isn't too noisy in my opinion, we might want to add this commit, or a more extensive one, to the blame ignore

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> we might want to add this commit, or a more extensive one, to the blame ignore

I wouldn't, I think the blame ignore should only include cosmetic changes, but this one actually has implications on how code is compiled. If a downstream user has their custom code fail compiling because of this change (missing `override` in user code), they need to find it in the blame.

**Comment by AThousandShips** [comment]
Isn't that compile issue only if you mix it in the same class?

**Comment by akien-mga** [comment]
Possibly. Still, it's not a cosmetic change so I wouldn't hide it from blame :)

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
