### PR TITLE
Rename MarginContainer to PaddingContainer (+ theme constants)

### LINKED ISSUE #2334: Switch MarginContainer node name and properties to Padding rather than Margin
### Describe the project you are working on
Not so much a project as something that I've been having to explain to a lot of people due to confusion with more modern UI framework naming conventions. If you check the Godot forums, and various Discord servers, there's a *ton* of confusion over why it's called MarginContainer, when the other containers also contain Margin properties.

### Describe the problem or limitation you are having in your project
Basically, MarginContainer does not truly represent Margins when you update its Custom Constants, but rather Padding, in more modern UI framework terminology. Some older frameworks refer to it as "inner margins" vs "outer margins", but padding vs margins (respectively) is far more common these days, and the container itself is meant to implement padding.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
I think renaming the node to PaddingContainer and changing the properties to Padding Left, Padding Right, etc., would make it a lot clearer that the values you set in Custom Constants set the distance on the inside of the control. Having talked with several beginners about this (I help answer questions all over Discord), they also think Padding would have helped them to understand why you'd want to use a MarginContainer (or, as per my proposal, PaddingContainer).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
This is just a rename of the control node and some of its properties. It would be good if we can utilize something that gives us backward compatibility, such as what's coming in Godot 4.0 with the big node name refactor.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
You'd have to make your own node scene and export new properties that map onto the old ones, I believe, and that would be copy/pasted among many, many projects.

### Is there a reason why this should be core and not an add-on in the asset library?
It's changing a core node, I'd expect it to remain there and not require people to setup an addon every single new project.

### PR DESCRIPTION
**Pull request by Mickeon**
Closes https://github.com/godotengine/godot-proposals/issues/2334.

This PR renames **MarginContainer** to **PaddingContainer**, as an attempt to end the confusion between its theme constants and the `margin` properties present in every **Control** Node.

All of its theme constants are changed accordingly:
- `margin_left` -> `padding_left`
- `margin_top` -> `padding_top`
- `margin_right` -> `padding_right`
- `margin_bottom` -> `padding_bottom`

Also changes every comment, variable name referring to the previous name.
e.g. (`MarginContainer mc -> PaddingContainer pc`, `include_margin -> include_padding`)

Changes the filename as well.

### CODE REVIEW

**Comment by fire-forge** [comment]
The control `margin` properties were already renamed to `offset` in 4.0 for the same reason - to remove confusion between Control margins and MarginContainer.

**Comment by Mickeon** [comment]
Ah, oh well! Then I suppose this wouldn't be nearly as necessary at all?

**Comment by KoBeWi** [comment]
Well, the proposal has some other arguments for renaming it to padding (modern frameworks use this name etc.). For me personally margins are clear, more than padding actually.

**Comment by YuriSizov** [comment]
In CSS margins are external offsets and paddings are internal offsets. I.e. margins shift the rectangle of the node, and paddings inset the children.

With that, the old control properties were indeed margins, and the container here technically creates paddings. Now that the margins were renamed to offsets it probably doesn't matter much, but if we go with a rename, then StyleBox also needs renames, as its margins are often also paddings according to CSS principles.

And we don't really need to follow CSS principles. I'm sure there are other layout systems that use these terms differently.

**Comment by Mickeon** [comment]
Imitating some CSS principles would definitely ease the transition both in and "out" of the Engine for some users. Maybe offsets could return to their original name? 

I could also update StyleBox in this PR if necessary for consistency.

**Comment by KoBeWi** [comment]
> Maybe offsets could return to their original name?

No, IIRC some users were confused that margins could be negative. Offsets are a better name.

**Comment by Mickeon** [comment]
Closing for tidiness, as this has been rejected. If there'll be a next time may be more worth it to remake the PR outright.

**Pull request closed without merging**
