### PR TITLE
Remove unused ofs variable in Tree::_draw

### PR DESCRIPTION
**Pull request by theludovyc**
Hello =) !

### CODE REVIEW

**Review by groud — APPROVED** [review]
lol ^^

**Comment by theludovyc** [comment]
> lol ^^
No shame to have beautiful code =) !

Sorry for close/open ^^'

**Comment by ThakeeNathees** [comment]
the variable `ofs`  was never used in it's scope, it's better removing it

**Comment by groud** [comment]
> the variable ofs was never used in it's scope, it's better removing it

Ah yeah, that's true, the whole block can be removed.

**Comment by theludovyc** [comment]
Hide behind - 1 - 1 ^^

**Comment by theludovyc** [comment]
> 
> 
> > the variable ofs was never used in it's scope, it's better removing it
> 
> Ah yeah, that's true, the whole block can be removed.

Done =)

**Comment by groud** [comment]
Could you [squash the commit together](https://docs.godotengine.org/fr/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) ?

**Comment by theludovyc** [comment]
> 
> 
> Could you [squash the commit together](https://docs.godotengine.org/fr/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) ?

I never do it. I try :) !

**Comment by theludovyc** [comment]
I think I do my first squash =) !

**Comment by groud** [comment]
Ah, sorry, but now you you should likely amend your commit and change the message to something more meaningful. Like "Remove unused ofs variable".

How to amend a commit is also described in the same part of the docs. :)

**Comment by theludovyc** [comment]
I do this, message of commit is "Replace - 1 - 1 => - 2, Finaly remove block (ofs not used)". That's not good ?

**Comment by groud** [comment]
> I do this, message of commit is "Replace - 1 - 1 => - 2, Finaly remove block (ofs not used)". That's not good ?

Well not really, the final commit change is about removing the block of code, you don't even need to talk about the `-1 -1  => -2` replacement

**Comment by theludovyc** [comment]
Fail...

**Comment by theludovyc** [comment]
I do it ! Commit message is "Remove unused ofs variable", like you want =)

**Comment by akien-mga** [comment]
Thanks!

**Comment by theludovyc** [comment]
With pleasure 😊

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
