### PR TITLE
Make the code for units for the editor inspector more generic

### PR DESCRIPTION
**Pull request by aaronfranke**
EDIT 2: I regret making this PR. As of 2024 I am firmly in the camp of "everything must be metric, if you are not using metric you are doing it wrong, and not just metric, standard SI units, use meters not centimeters, etc".

EDIT: Removed the ability to customize the distance unit as per @reduz's feedback. Now this PR just adds the rotation unit setting, uses the units in a few more places, and changes this code more generic such that it would be easy for anyone to add their own units if they fork the engine.

This PR is a continuation of #50009. It adds support for users to switch between various units.

Instead of the editor hint `,suffix:m`, we can write the hint as `,3d_distance`. However, Godot will always use meters. Similarly, there is also a `,2d_distance` meant to be used for 2D nodes (Node2D-derived, not Control). Also, this PR adds support for using these hint strings even when the property hint is something other than `PROPERTY_HINT_RANGE`.

Just like in #50009 with the automatic conversion of degrees and radians, this PR can convert units to display the correct values depending on both which unit the API expects under the hood and what the user's preference is. The conversion is handled by multiplying as needed with a scale factor grabbed from a method in Editor settings. However, in this PR, the only place where conversion actually happens is with angles.

The suffix is also grabbed from a method in Editor settings, but it can still also be hard-coded with `,suffix:` which doesn't use the scaling method, in case the value isn't scalable (like integer types), shouldn't be scaled (like on Control where it's hard-coded to use pixels regardless of the distance unit used for Node2D), or is a non-standard unit (`,suffix:apples` or anything else is valid).

There is 1 editor setting added: Rotation unit. Therefore this solves #50009's goal for a future PR of "Ability to switch radians/degrees in the inspector for angle properties". Other things can be configured in a fork of Godot.

Things to do / consider doing, likely in future PRs:

* Add more types of units (mass, speed, acceleration, force, ratios/percentages, and more).
* Use these units in more places around the engine.
* Should these units be translatable? I think these suffixes are fairly universal.

Old PR description:

<details>

This PR is a continuation of #50009. It adds support for users to switch between various units.

Instead of the editor hint `,suffix:m`, we can write the hint as `,3d_distance`, then Godot will use the user's preferred unit. Similarly, there is also a `,2d_distance` meant to be used for 2D nodes (Node2D-derived, not Control). Also, this PR adds support for using these hint strings even when the property hint is something other than `PROPERTY_HINT_RANGE`.

Just like in #50009 with the automatic conversion of degrees and radians, this PR can convert units to display the correct values depending on both which unit the API expects under the hood and what the user's preference is. The conversion is handled by multiplying as needed with a scale factor grabbed from a method in Editor settings.

The suffix is also grabbed from a method in Editor settings, but it can still also be hard-coded with `,suffix:` which does no scaling, in case the value isn't scalable (like integer types), shouldn't be scaled (like on Control where it's hard-coded to use pixels regardless of the distance unit used for Node2D), or is a non-standard unit (`,suffix:apples` or anything else is valid).

There are 4 total editor settings added: Rotation unit, 2D distance unit, 2D pixels per meter, and 3D distance unit.

Here is what the inspectors for Node2D, Node3D, and Control look like with the default settings:

Here is what the inspectors for Node2D, Node3D, and Control look like with the same positions/rotations/etc, but with the 2D unit changed to millimeters, the 3D unit changed to centimeters, and the rotation unit changed to radians:

Things to do / consider doing, likely in future PRs:

* Add more distance units (does anyone care about feet in Godot?).
* Add more types of units (mass, speed, acceleration, force, ratios/percentages, and more).
* Use these units in more places around the engine.
* Should these units be translatable? I think these suffixes are fairly universal.

### CODE REVIEW

**Comment by pycbouh** [comment]
> Should these units be translatable? I think these suffixes are fairly universal.

Ideally, yes. I would never use translated software, but for people who do it seems necessary to have everything adapted to their locale. So I wouldn't count on it being universal. Maybe this is more important for things like meters and kilograms than it is for pixels, though.

**Comment by Zireael07** [comment]
Meters, kilograms and other SI units are universal. Pixels on the other hand... I haven't used gamedev software in non-Latin languages, so I honestly don't know. In the Latin alphabet, they're almost universally px.

**Comment by akien-mga** [comment]
I would leave out unit localization for now and reassess once we find explicit units which we want to use and which should be localized. I can think of a few in French but none that we'd be using AFAIK (e.g. `dpi` -> `ppp`, or `kB` -> `ko`).

As for allowing the change units beyond switching between degrees and radians (which makes sense), I'm not so convinced. The Godot API itself will still expect things in a single unit, so you'd end up having a discrepancy between the units shown in the inspector and the values you handle in script. That's true already with degrees vs radians, but I'm not sure what gain there would be in having 3D coordinates in `cm` or `in` when the API only understands meters.

What are concrete examples of units which:
- We would use as suffix for existing properties
- Would benefit from being customizable with conversions to other units?

Because if the only real valid use case is degrees vs radians, a single toggle button for that specifically is better than a super flexible approach IMO.

**Comment by pycbouh** [comment]
> Meters, kilograms and other SI units are universal.

Units are universally known, but they are not written in Latin in non-Latin languages. And that can lead to confusion.

**Comment by Zireael07** [comment]
> Units are universally known, but they are not written in Latin in non-Latin languages. And that can lead to confusion.

Battle for Wesnoth had that very discussion recently and they decided not to translate units at all (m and kg are written in Latin alphabet in Japanese and Arabic, unless you want to spell them out, i.e. meter in English, متر in Arabic, メートル in Japanese)

Also: https://en.wikipedia.org/wiki/International_System_of_Units (Scroll down to unit symbols to see that the m, kg etc. are universal.)

**Comment by pycbouh** [comment]
@Zireael07 They are written in Cyrillic in ex-Soviet countries, e.g. кг, м. I'm not talking hypothetically here. 🙃

**Comment by fire** [comment]
As part of the usability team, import team and the animation team, I endorse this.

**Comment by reduz** [comment]
I am not in favor of customizable units, I know it sounds cool, but this is good for 3D modelling software, not a game engine. It would suck majorly if you enter distances in foots but then the engine uses metric internally via code.

**Comment by aaronfranke** [comment]
@reduz Makes sense, being able to customize the unit is not really vital. We should still let users customize this without too many diffs if they fork the engine, but indeed having the ability to configure units inside of the official editor isn't very important.

With your feedback I removed the ability to customize the distance unit. Now this PR is just changes to make this code more generic, and it would be easy for anyone to add their own units if they fork the engine.

**Comment by akien-mga** [comment]
> I am not in favor of customizable units, I know it sounds cool, but this is good for 3D modelling software, not a game engine. It would suck majorly if you enter distances in foots but then the engine uses metric internally via code.

Yes, that's my feeling too. The screenshots look cool but there's a bias in this proposal (and user support thereof) because it serves as a showcase of what has already been implemented in #50009, namely having units shown in the inspector.

I haven't yet seen an actual valid use case (nor proposal) for customizable units. I do see a use case for localizable unit symbols as pointed out by @pycbouh, so a significant portion of this PR will still be useful as a base for that. But customizable units (beside radians/degrees) was not requested by any user so far, and I don't see the use case aside from it being cool.

Changing the base distance unit will also have significant impact on more complex units such as velocities, accelerations, moment of inertia, etc. and I don't think anybody wants to have to mentally deal with converting kg·m² to g·mm² or lb·in²... conversion factors left as an exercise to the reader.

**Comment by aaronfranke** [comment]
> Changing the base distance unit will also have significant impact on more complex units such as velocities, accelerations [...]

It can be done... however, this is probably best left to a fork of the engine.

**Comment by akien-mga** [comment]
> > Changing the base distance unit will also have significant impact on more complex units such as velocities, accelerations [...] conversion factors left as an exercise to the reader.
> 
> It can be done without giving the reader things to think about... however, this is probably best left to a fork of the engine.

Imperial Godot :crown:

**Comment by Calinou** [comment]
This reminds me, is it possible to expose units for import options?

**Comment by aaronfranke** [comment]
@Calinou What do you mean by this? I think that 3D model formats include units usually. [GLTF always uses meters](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units) and IIRC FBX can be configured to any unit but is most commonly centimeters. Godot should detect this setting from the model file if it exists.

**Comment by Calinou** [comment]
> @Calinou What do you mean by this? I think that 3D model formats include units usually. [GLTF always uses meters](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0?rgh-link-date=2021-07-02T18%3A37%3A12Z#coordinate-system-and-units) and IIRC FBX can be configured to any unit but is most commonly centimeters. Godot should detect this setting from the model file if it exists.

I'm referring to the options in the Import dock: 
image


Here, **Max Size** could have a `px` hint.

**Comment by mhilbrunner** [comment]
Closed as discussed in PR meeting; too much complexity without having consensus/large amount of user requests for this

**Pull request closed without merging**
