### PR TITLE
Fix Oren-Nayar diffuse.

### PR DESCRIPTION
**Pull request by ghost**
I found the [source](http://mimosa-pudica.net/improved-oren-nayar.html) for the current approximation  and I fixed the inconsistencies.

I can't say that approximation is that good though because *relative* errors are pretty high (he only shows absolute errors which makes it look at lot better that it actually is), I can submit another PR for an exact implementation without neglecting any terms at all (although that could be a bit slower).

### CODE REVIEW

**Comment by tagcup** [comment]
Oh, and he gives the relation between the sigma in original Oren-Nayar and his sigma that is between [0,1], which was something I brought up in #11663

**Comment by tagcup** [comment]
Actually it appears that his σ is the same as Oren-Nayar's, although he defines σ' which is between [0,1] (something I brought up in #11663). To ensure roughness [0,1] range covers the entire angular range in Oren-Nayar, we can switch to σ' for example,

**Comment by groud** [comment]
From IRC, @reduz seems ok with the PR. 
Can I merge it like that or do you want to wait for an input on using σ' ?

**Comment by tagcup** [comment]
Yes, it's fine. We can keep #11663 open until we work out how to properly relate wedge angle standard deviation to roughness in Burley.

**Comment by groud** [comment]
Ok :) Merging then.

**Pull request merged**
