### PR TITLE
fix RiderPathLocator - searching for toolbox on Mac

### PR DESCRIPTION
**Pull request by van800**

### CODE REVIEW

**Comment by akien-mga** [comment]
In case other paths need to be reviewed:
```
$ rg "Path.*\\\\"
editor/bindings_generator.cpp
3079:   itype.c_out = "\treturn memnew(NodePath(%1));\n";

glue/GodotSharp/GodotSharp/GodotSharp.csproj
91:  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />

glue/GodotSharp/GodotSharpEditor/GodotSharpEditor.csproj
44:  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />

editor/GodotTools/GodotTools.ProjectEditor/DotNetSolution.cs
69:                    name, projectInfo.PathRelativeToSolution.Replace("/", "\\"), projectInfo.Guid);

editor/GodotTools/GodotTools.ProjectEditor/GodotTools.ProjectEditor.csproj
18:    <OutputPath>bin\Debug</OutputPath>
26:    <OutputPath>bin\Release</OutputPath>
35:      <HintPath>$(SolutionDir)\packages\DotNet.Glob.2.1.1\lib\net45\DotNet.Glob.dll</HintPath>
56:  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />

editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs
51:                root.AddItem("Compile", item.RelativeToPath(dir).Replace("/", "\\"));
84:            root.AddItem("Compile", assemblyInfoFile.RelativeToPath(dir).Replace("/", "\\"));
129:            root.AddImport(Path.Combine("$(MSBuildBinPath)", "Microsoft.CSharp.targets").Replace("/", "\\"));

editor/GodotTools/GodotTools.ProjectEditor/ProjectUtils.cs
20:            var normalizedInclude = include.RelativeToPath(dir).Replace("/", "\\");

editor/GodotTools/GodotTools/GodotTools.csproj
20:    <OutputPath>bin\Debug</OutputPath>
28:    <OutputPath>bin\Release</OutputPath>
35:      <HintPath>..\packages\JetBrains.Annotations.2019.1.3\lib\net20\JetBrains.Annotations.dll</HintPath>
39:      <HintPath>..\packages\Newtonsoft.Json.12.0.3\lib\net45\Newtonsoft.Json.dll</HintPath>
106:      <GodotToolsCopy Include="$(OutputPath)\GodotTools*.dll" />
107:      <GodotToolsCopy Include="$(OutputPath)\Newtonsoft.Json.dll" />
108:      <GodotToolsCopy Include="$(OutputPath)\DotNet.Glob.dll" />
111:      <GodotToolsCopy Include="$(OutputPath)\GodotTools*.pdb" />
120:  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />

editor/GodotTools/GodotTools.Core/StringExtensions.cs
14:            if (Path.DirectorySeparatorChar == '\\')

editor/GodotTools/GodotTools.BuildLogger/GodotTools.BuildLogger.csproj
3:  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
21:    <OutputPath>bin\Debug\</OutputPath>
30:    <OutputPath>bin\Release\</OutputPath>
52:  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />

editor/GodotTools/GodotTools.Core/GodotTools.Core.csproj
17:    <OutputPath>bin\Debug</OutputPath>
25:    <OutputPath>bin\Release</OutputPath>
38:  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />

editor/GodotTools/GodotTools.IdeConnection/GodotTools.IdeConnection.csproj
3:  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
21:    <OutputPath>bin\Debug\</OutputPath>
30:    <OutputPath>bin\Release\</OutputPath>
52:  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />

editor/GodotTools/GodotTools/Build/MsBuildFinder.cs
42:                        if (!_msbuildToolsPath.EndsWith("\\"))
43:                            _msbuildToolsPath += "\\";
63:                        return Path.Combine(riderDir.FullName, @"tools\MSBuild\Current\Bin\MSBuild.exe");
144:            vsWherePath += "\\Microsoft Visual Studio\\Installer\\vswhere.exe";
181:                string msbuildDir = Path.Combine(value, "MSBuild\\Current\\Bin");
187:                return Path.Combine(value, "MSBuild\\15.0\\Bin");

editor/GodotTools/GodotTools/Export/ExportPlugin.cs
89:            AddFile(dstPath.Replace("\\", "/"), File.ReadAllBytes(srcPath), remap);

editor/GodotTools/GodotTools/Ides/Rider/RiderPathLocator.cs
165:            var toolboxPath = Path.Combine(localAppData, @"JetBrains\Toolbox");
175:            var toolboxRiderRootPath = Path.Combine(toolboxPath, @"apps\Rider");
241:                    var possiblePath = Path.Combine(folder, @"bin\rider64.exe");

editor/GodotTools/GodotTools/Ides/MonoDevelop/Instance.cs
57:                args.Add("\"" + Path.GetFullPath(solutionFile) + "\"");
```

**Comment by van800** [comment]
backslash (\) is fine in path for windows-only C# code.

**Review by neikeq — APPROVED** [review]

**Comment by van800** [comment]
@neikeq Can we please backport this to 3.2.2?

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
