### PR TITLE
Fix godot macosx

### PR DESCRIPTION
**Pull request by thduynguyen**
small bug fixes to compile on mac

### CODE REVIEW

**Comment by volzhs** [comment]
your last commit on this PR is just fixed by #15330.
it's better to make another PR if it's not quite relevant.

**Comment by thduynguyen** [comment]
Sorry, didn't see the other PR. I've removed the last commit from this PR itself.

**Comment by akien-mga** [comment]
I've merged your PR manually to squash the commits together, fix your email in the commit header and add fixes for all other platforms that had been broken by #15299 (ping @touilleMan, you need to use `ERR_FAIL_COND_V` when you return a value :)).

**Comment by thduynguyen** [comment]
Awesome! Thanks!

**Comment by touilleMan** [comment]
@akien-mga Damned ! Seems like hasty copy/paste on platforms I don't give f... I had no hardware to test on :trollface:

**Pull request closed without merging**
