### PR TITLE
iOS Haptic Feedback

### PR DESCRIPTION
**Pull request by GhostWalker562**
Hello!

**iOS's New Craze**
iOS's app and game development to me has exponentially grew and this new "Haptic Feedback" found in iOS 10 is making its way into daily life. From the menu to Minecraft Earth, Haptic Feedback is a impressively new and modern way to spice up games and apps for iOS. 

**Implementation**
I took the vibration addition as reference and implemented the iOS Haptic Feedback generators, well two of them, the same way. For the impact generator I referenced "Taptic feedback" from unity plugins. I'm not sure if the ways I'm doing this are most efficient but it'd be cool to have this added. If not, perhaps making it a module would be sufficient? I too don't know how to make a module :P.

So there's my little run down on my pull :) Not many iOS stuff out there so I might as well help.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Platform-specific APIs are generally shunned, since they are mostly useless on other platforms. Maybe this could be wired through ProjectSettings?
Alternatively, is there a platform-neutral way to expose the API? :)

**Comment by GhostWalker562** [comment]
@bojidar-bg There’s probably a way for Android to perform the same haptic feedback, like vibrations, but I don’t know the frameworks to implement it as I am more experienced with iOS. If somebody could help that’d be nice. And can you elaborate on the projectsettings? I don’t really know how or what that means

**Comment by aaronfranke** [comment]
@GhostWalker562 Is this still desired? If so, it needs to be rebased on the latest master branch.

This PR contains merge commits, which is not good. See this article to learn how to rebase your PR: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by GhostWalker562** [comment]
@aaronfranke for now no I don’t think people desire this rn. I’m just going to close because I was never able to figure out the Android side of this. I will approach this when its needed some other time.

**Pull request closed without merging**
