### PR TITLE
Update `screen_get_scale` documentation.

### PR DESCRIPTION
**Pull request by syntaxerror247**
It was implemeted for these platforms over two years ago, but for some reason, the documentation was never updated!

https://github.com/godotengine/godot/blob/0c45ace151f25de2ca54fe7a46b6f077be32ba6f/platform/ios/display_server_ios.mm#L541

https://github.com/godotengine/godot/blob/0c45ace151f25de2ca54fe7a46b6f077be32ba6f/platform/web/display_server_web.cpp#L1189

https://github.com/godotengine/godot/blob/0c45ace151f25de2ca54fe7a46b6f077be32ba6f/platform/android/display_server_android.cpp#L280

### CODE REVIEW

**Comment by Mickeon** [comment]
When was this changed? Is it true?

**Comment by syntaxerror247** [comment]
> When was this changed? Is it true?

Yes, I'm not just randomly listing names! 😆

I have updated the PR description with references.

**Review by Mickeon — APPROVED** [review]

**Review by bruvzg — APPROVED** [review]
It seems to be implemented on all mentioned platforms.

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
