### PR TITLE
Adding IPv6 support

### PR DESCRIPTION
**Pull request by akien-mga**
From what I read on IRC it should be more or less ready to merge into master now.

CC @punto- and @Faless for confirmation.

### CODE REVIEW

**Comment by akien-mga** [comment]
@punto- said it should be fine, so let's go. If it runs well in master, we'll also backport this for 2.1 as it's required by Apple.

**Comment by reduz** [comment]
Awesome! Now our new multiplayer is lagging behind :/

**Comment by akien-mga** [comment]
Yeah - we should probably start a review of existing enet forks that add ipv6 support. Upstream is not going anywhere anyway, the project seems mostly dormant, so if we find a well-maintained fork, we could grab their patches and try to keep in sync.

**Comment by reduz** [comment]
+1 to that

**Pull request merged**
