### PR TITLE
Add offset for TextureProgress progress texture

### LINKED ISSUE #823: Add offset for TextureProgress progress texture
**Describe the project you are working on:**
2D mobile game.

**Describe the problem or limitation you are having in your project:**
So, I have 3 textures like this:
previu
I'm using them for TextureProgress node. First and third texture have a size of 544x198, the middle one is 362x70. Here's what it looks like when I put it in the node:
badstuff
As you can see, the `progress` texture is aligned in the corner and there's no way to center it. I can't make it the same size as other textures, because the transparent pixels are counted in progress to, so it would make the bar inaccurate.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
There should be a way to offset the `progress` texture. Other textures can easily be aligned in image editing software, but the progress can't, because it needs to contain solely the part that will show the progress. I've ran into this problem multiple times and it makes it impossible to make fancy TextureProgress nodes. Offset for progress texture would fix this.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
In the `Texture` section of TextureProgress, there could be an additional Vector2 property called `progress_offset`, which would move the progress texture from the corner.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
This can be worked around by using other nodes as over and under textures, but it kills the purpose of TextureProgress. IMO this is a common need for this node.

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's about core node.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/823

### CODE REVIEW

**Review by Calinou — APPROVED** [review]

**Comment by reduz** [comment]
If I have to be entirely honest, I think TextureProgress kind of became far too bloated with functions to the point we will never make everyone happy and eventually an add-on may be  better fit. I understand why this is needed and it makes sense, though, so I would favor merging it.

**Review by reduz — APPROVED** [review]

**Comment by vnen** [comment]
Need to fix the XML doc to pass CI

**Comment by groud** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
