### PR TITLE
Add tile quarter rotations to TileMaps by transpose transform

### PR DESCRIPTION
**Pull request by not-surt**
Adds quarter rotations for tiles to TileMaps by composing flips with new transpose transform.
Adds extra tool button for transpose as well as dedicated buttons for each quarter rotation.

As this touches a lot of files, I ask others do some testing before it's merged to make sure I haven't broken anything.

### CODE REVIEW

**Comment by not-surt** [comment]
Oh and if someone want to make some better icons then please do.

**Comment by reduz** [comment]
this looks generally ok, but you should not modify VARIANT_ARG_MAX.
If you need to bind functions with more than 5 arguments, add:
#include "method_bind_ext.inc"
to the .cpp

**Comment by not-surt** [comment]
The problem is UndoRedo uses VARIANT_ARG_LIST and with the added transpose flag I need and extra variant arg:
undo_redo->add_do_method(node,"set_cell",p_pos.x,p_pos.y,p_value,p_flip_h,p_flip_v,p_transpose);
undo_redo->add_undo_method(node,"set_cell",p_pos.x,p_pos.y,prev_val,prev_flip_h,prev_flip_v,prev_transpose);

What else would you suggest?

**Comment by reduz** [comment]
ah that's right, and that sucks. I suppose for binding the function you can
use the include I mentioned above,
and for the undo/redo code you could make a local function in the tile map
editor that takes position as a Point2, and then calls the proper function
so you are still in the right parameter range

**Comment by not-surt** [comment]
Okay added the wrapper function. Seems to be working fine.

**Comment by not-surt** [comment]
Was there anything else that needs doing for this to be merged?

**Pull request closed without merging**
