### PR TITLE
Travis: Back to latest emsdk, use embedded mode properly

### PR DESCRIPTION
**Pull request by akien-mga**
Reverts and supersedes #39168 and #40563.

### CODE REVIEW

**Comment by sbc100** [comment]
Yup that works, assuming the environment variables from the `install` phase carry over to the `build` phase.

Ideally you wouldn't need to parse the config file at all, since the config format itself kind of an implementation detail.   I'll see if I can come up with PR as a suggestion.

I think the best way to find is just to look in PATH.. emsdk_env.sh should put it there.

It looks like you are also needing to find `"node_modules", ".bin", "google-closure-compiler"` relative to emscripten root...  For this I would just find emcc then assume `node_modules` lives alongside it.

**Comment by sbc100** [comment]
I think it would be best to avoid `exec(f.read(), em_config)` if possible.

**Comment by akien-mga** [comment]
Thanks, that's good feedback! I'll copy this to a dedicated issue as this PR in itself should be good to merge as is, it fixes the Travis CI setup which was previously missing the `emsdk_env.sh` call.

**Comment by akien-mga** [comment]
Copied to #40574.

**Pull request merged**
