### PR TITLE
Add `get_connection_count` method to `GraphEdit`

### LINKED ISSUE #10942: Add function to get number of port connections in GraphNode
### Describe the project you are working on

Plugin based on GraphEdit

### Describe the problem or limitation you are having in your project

I'm trying to limit the number of connections for an input port in a GraphNode node, so that we can only make one connection to one port, and not several, I tried to implement this using is_node_connected(from_node,from_port,to_node,to_port), but we have to enter extra arguments of the first node, without them the function will not work correctly, especially since I would like to know if the port is connected to anything at all, and not to a specific node

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

There is no function that would determine whether a port is connected to something (true/false), or it would be possible to return the number of connections of a certain GraphNode and one of its ports, using a new function

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The new function would return the number of connections of one of the ports:
 `connections_count(node: StringName, port: int)`

### If this enhancement will not be used often, can it be worked around with a few lines of script?

At the moment, to find out the number of connections, we will have to use more complex methods, which is difficult especially for beginners, this function would be very useful

### Is there a reason why this should be core and not an add-on in the asset library?

Same as above

### PR DESCRIPTION
**Pull request by JekSun97**
Closes: [godot-proposals/issues/10942](https://github.com/godotengine/godot-proposals/issues/10942)
Adds a method to GraphEdit to get the number of connections to a given node and port (`get_connection_count(to_node,to_port)`).
With this we can easily limit the number of connections using the condition:
```
if get_connection_count(to_node,to_port)<1:
	connect_node(from_node,from_port,to_node,to_port)
```

This is my first PR for Godot and I'm also pretty new to Git, if there's anything wrong let me know and I'll try to fix it.

Test project:  
[graphedit_test_func.zip](https://github.com/user-attachments/files/17695609/graphedit_test_func.zip)

### CODE REVIEW

**Comment by JekSun97** [comment]
Sorry, I posted two commits at once, is there any way to fix this? 😅

**Comment by v6stXN46WdLBtp** [comment]
You need to squash your commits. Here is a Godot guide about it [Guide](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase).

**Comment by KoBeWi** [comment]
It should be called `get_connections_count()`.

**Comment by AThousandShips** [comment]
It should be `get_connection_count` in fact, to follow English grammar

**Comment by JekSun97** [comment]
> It should be `get_connection_count` in fact, to follow English grammar

Done!

**Comment by JekSun97** [comment]
I noticed one error when checking CI, should I worry about it?

**Comment by akien-mga** [comment]
> I noticed one error when checking CI, should I worry about it?

The CI error is here: https://github.com/godotengine/godot/actions/runs/11797387846/job/32861548434?pr=99045

The problem is that you added the XML template for the documentation of the new method manually, and it's not in the right place. Methods need to be ordered alphabetically so it needs to be moved further up.

Or you can use `<path/to/godot> --doctool` to do it.

**Comment by JekSun97** [comment]
I have prepared a fix, but git gives me an error, I also merged the latest Master branch with mine, what could be the problem?
git

**Pull request closed without merging**
