### PR TITLE
[3.2] Improved Inspector Sub-Resource Editing

### PR DESCRIPTION
**Pull request by hoontee**
Backport of #45907.

### CODE REVIEW

**Comment by hoontee** [comment]
Didn't feel like waiting ¯\\\_(ツ)\_/¯

If any substantial changes occur, I can backport them as well.

CC @Xrayez

**Review by Xrayez — APPROVED** [review]
Works like magic!

image

Configuring tint via `docks/property_editor/subresource_hue_tint` editor setting also works (0.4):

image

**Comment by n-pigeon** [comment]
Thank you for back porting this!

**Comment by rick551a** [comment]
Excited for this, will it be in 3.2.4?

**Comment by hoontee** [comment]
> will it be in 3.2.4?

Unlikely - it's currently in the release candidate phase, so if this PR were to be merged, it would happen in time for 3.2.5.

Disclaimer: I'm not a Godot developer, this PR was created in response to https://github.com/godotengine/godot/pull/45907#issuecomment-778177281.

**Comment by Xrayez** [comment]
Consider rebasing your PR to latest `3.2`, your current branch is still on `3.2.3-rc` which was 7 months ago according to commit history. 🙂

It took me much longer to compile the engine because of that, and other folks might want to test this PR as well.

**Comment by RPicster** [comment]
compare
It may be considered "spam". I just wanted to drop by and let you know how thankful I am for the backport to 3.2

I work a lot with the SmartShape2D Plugin and the resources and sub resources there are a real hell to work with.

Above is a screenshot comparing the two variants and it is obvious how much better the elements are distiguishable 👏

**Comment by akien-mga** [comment]
> Consider rebasing your PR to latest `3.2`, your current branch is still on `3.2.3-rc` which was 7 months ago according to commit history. slightly_smiling_face

Indeed, please rebase. I'm surprised it can even be merged without conflicts, but if the base branch is so old, there's no guarantee that it won't actually break the build once merged on `3.2` (the current CI build ran with the config from the base branch).

**Comment by hoontee** [comment]
Rebased to f30d82744817461ff475d9893d48ecf087ad1b43.

**Review by akien-mga — APPROVED** [review]
YOLO.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
