### PR TITLE
Update opus to 1.3.1 and opusfile to 0.11

### PR DESCRIPTION
**Pull request by jmannanc**

### CODE REVIEW

**Comment by akien-mga** [comment]
I had a quick look at resyncing with opus 1.3.1 and opusfile 0.11 on top of your changes to validate that it's indeed the unmodified upstream code (not that I distrust you, but thirdparty code added by new contributors can indeed be a security risk).

Of course I didn't find any problem, as with the previous two PRs.

I did notice some files that are no longer part of the upstream distribution and that we should remove too. It's not clear in the README.md but usually when syncing I first delete the contents of our own thirdparty folder, re-add the files from the new upstream version, and check the diff. Here's what I have:

```
       deleted:    opus/celt/arm/celt_ne10_fft.c
        deleted:    opus/celt/arm/celt_ne10_mdct.c
        modified:   opus/celt/arm/celt_pitch_xcorr_arm-gnu.S
        deleted:    opus/celt/fixed_c5x.h
        deleted:    opus/celt/fixed_c6x.h
        deleted:    opus/celt/tests/test_unit_cwrs32.c
        deleted:    opus/celt/tests/test_unit_dft.c
        deleted:    opus/celt/tests/test_unit_entropy.c
        deleted:    opus/celt/tests/test_unit_laplace.c
        deleted:    opus/celt/tests/test_unit_mathops.c
        deleted:    opus/celt/tests/test_unit_mdct.c
        deleted:    opus/celt/tests/test_unit_rotation.c
        deleted:    opus/celt/tests/test_unit_types.c
        deleted:    opus/celt/x86/celt_lpc_sse.c
        modified:   opus/config.h
        deleted:    opus/silk/fixed/mips/prefilter_FIX_mipsr1.h
        deleted:    opus/silk/fixed/x86/burg_modified_FIX_sse.c
        deleted:    opus/silk/fixed/x86/prefilter_FIX_sse.c
        deleted:    opus/silk/fixed/x86/vector_ops_FIX_sse.c
```

The files marked "deleted" are actually no longer in the upstream tarball and should be removed. (Apart from the `celt/tests/` folder that I removed myself, as the `silk/tests/` that we don't track currently.)

There's a slight diff to `opus/celt/arm/celt_pitch_xcorr_arm-gnu.S` which had been missed somehow (only comments/formatting).

And finally there's `config.h` which was not listed in the README but also needs to be included and updated to match new upstream settings. That part is a bit trickier, the `config.h` is platform-dependent and generated by `./configure`, so we need to generate it, and then edit it to match Godot's requirements. This is best done by simply comparing with the current `config.h` and make sure to keep the same options as before, plus default values for new options.

Here's the diff for `README.md` to add missing info:
```diff
diff --git a/thirdparty/README.md b/thirdparty/README.md
index 0cbcdc1eb9..9c8bece848 100644
--- a/thirdparty/README.md
+++ b/thirdparty/README.md
@@ -400,12 +400,14 @@ Files extracted from the upstream source:
 
 Files extracted from upstream source:
 
+- Run `opus/configure` and copy/sync changes to `config.h`
+  (note that this file may have Godot-specific options enabled)
 - all .c and .h files in src/ (both opus and opusfile)
 - all .h files in include/ (both opus and opusfile) as opus/
 - remove unused `opus_demo.c`,
 - remove `http.c`, `wincerts.c` and `winerrno.h` (part of
   unused libopusurl)
-- celt/ and silk/ subfolders
+- celt/ and silk/ subfolders (minus tests folders)
 - COPYING
 
```

**Comment by SneakyFish5** [comment]
> I had a quick look at resyncing with opus 1.3.1 and opusfile 0.11 on top of your changes to validate that it's indeed the unmodified upstream code (not that I distrust you, but thirdparty code added by new contributors can indeed be a security risk).
> 
Yea of course, no worries there :)
> I did notice some files that are no longer part of the upstream distribution and that we should remove too. It's not clear in the README.md but usually when syncing I first delete the contents of our own thirdparty folder, re-add the files from the new upstream version, and check the diff. Here's what I have:
> 
This definitely makes much more sense, I will do this from now on

> And finally there's `config.h` which was not listed in the README but also needs to be included and updated to match new upstream settings. That part is a bit trickier, the `config.h` is platform-dependent and generated by `./configure`, so we need to generate it, and then edit it to match Godot's requirements. This is best done by simply comparing with the current `config.h` and make sure to keep the same options as before, plus default values for new options.
> 
I figured out how to setup the config.h and tested through all the options to fix the errors, and I had to comment out these 4 options, but I kept the rest of the new defaults and the original changes to the config.
```
/* Compiler supports X86 AVX Intrinsics */
/* #define OPUS_X86_MAY_HAVE_AVX */

/* Compiler supports X86 SSE Intrinsics */
/* #define OPUS_X86_MAY_HAVE_SSE */

/* Compiler supports X86 SSE2 Intrinsics */
/* #define OPUS_X86_MAY_HAVE_SSE2 */

/* Compiler supports X86 SSE4.1 Intrinsics */
/* #define OPUS_X86_MAY_HAVE_SSE4_1 */
```

> Here's the diff for `README.md` to add missing info:
> 
> ```diff
> diff --git a/thirdparty/README.md b/thirdparty/README.md
> index 0cbcdc1eb9..9c8bece848 100644
> --- a/thirdparty/README.md
> +++ b/thirdparty/README.md
> @@ -400,12 +400,14 @@ Files extracted from the upstream source:
>  
>  Files extracted from upstream source:
>  
> +- Run `opus/configure` and copy/sync changes to `config.h`
> +  (note that this file may have Godot-specific options enabled)
>  - all .c and .h files in src/ (both opus and opusfile)
>  - all .h files in include/ (both opus and opusfile) as opus/
>  - remove unused `opus_demo.c`,
>  - remove `http.c`, `wincerts.c` and `winerrno.h` (part of
>    unused libopusurl)
> -- celt/ and silk/ subfolders
> +- celt/ and silk/ subfolders (minus tests folders)
>  - COPYING
>  
> ```
Added this (forgot parts of it though so sorry for commit spam haha)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Temporarily reverted with #33698 as the update broke `arm64v8` build for Android.

Overall, the flags we currently set in `config.h` don't seem correct and we need to give this more thought. This update added e.g. flags requiring support for SSE4.1, which would impact the portability of binaries on desktop platforms.

**Pull request merged**
