### PR TITLE
Add fog shaders and world-space volumetric fog material

### PR DESCRIPTION
**Pull request by clayjohn**
Implements the first part of: https://github.com/godotengine/godot-proposals/issues/2261

This adds another shader type that is used to alter the density and color of volumetric fog. 

To make things a little simpler I separated the volumetric fog stages into two files. Now the "density" stage is in it's own file and has its own uniforms and everything. The "density" stage runs before the other two stages. It is responsible for setting the color and density of the fog in the camera-froxel map. The internal filter and process steps then run and smooth out the froxels and then accumulate lighting respectively. 

Right now fog shaders can only be used in the world environment and they affect the entire world and operate in world space. In the future, I would like to add fog volumes which can add or remove fog in local areas and I would like to add some sort of fog particles.

Using this we can modify the volumetric fog effect to make things like this:
Screenshot (220)

### CODE REVIEW

**Comment by Chaosus** [comment]
That is pretty interesting and should take time to understand how to use it for me - I need to add it to VisualShader's after all :)

**Comment by clayjohn** [comment]
@Chaosus I hope there isn't too much for you to do! I added hooks to the visual shader where it seemed obvious to me. Luckily fog shaders are much simpler than all the others.

**Comment by clayjohn** [comment]
As discussed on [rocketchat](https://chat.godotengine.org/channel/rendering?msg=ngLQxJQMopinqhy2h) we are going with a different implementation that should work better with Fog Volumes. I am leaving this PR open for reference, or for users who want to start playing with volumetric effects.

**Comment by atirut-w** [comment]
> it will be superseded by a future PR

Can you be sure to comment here when the said PR comes out so I'll get a notification? I want to keep myself updated on this fog volume stuff.

**Comment by clayjohn** [comment]
Superseded by https://github.com/godotengine/godot/pull/53353

**Pull request closed without merging**
