### PR TITLE
Add missing consumePurchase plugin method for GodotPayment

### PR DESCRIPTION
**Pull request by volzhs**

### CODE REVIEW

**Comment by volzhs** [comment]
cc @timoschwarzer

**Comment by timoschwarzer** [comment]
Whoops sorry! I didn't have any consumables to test 😅
Thank you!

**Comment by akien-mga** [comment]
Can you make a PR for master too?

**Comment by volzhs** [comment]
@akien-mga no problem. Will that soon.

**Comment by volzhs** [comment]
@timoschwarzer you don't have to be sorry. I appreciate you for all of your work. I'm just testing your nice work. :smile:

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
