### PR TITLE
Documentation Converter from XML to Open Project wiki markup format

### PR DESCRIPTION
**Pull request by elzorrorebelde**
As posted [here](http://www.godotengine.org/topics/12130?r=12135#message-12135) help was needed with creating a XML converter to Open Project wiki markup format.

So, here is my PR.

The script works a little different than the other there, it takes more arguments. It **requires Python 3.x**. I added the option for the developer to choose a output directory, so the directory where the script is ran don't get cluttered with text files.

You can also specify the XML, by default the script will try to open the file `class_list.xml` that is assumed to be in the same directory. Here is the output of the command `--help`:

```
usage: makedocs.py [-h] [--input XMLFP] --output-dir OUTPUTDIR

Generates documentation from a XML file to different markup languages

optional arguments:
  -h, --help            show this help message and exit
  --input XMLFP         Input XML file, default: /home/jorge/godot/tools/docdump/class_list.xml
  --output-dir OUTPUTDIR
                        Output directory for generated files
```

I'm planning to add later a couple more of output formats, like markdown and dokuwiki (if they are required), and also _internationalization_ because `class_list.xml` will be subject of translations to several languages in the future.

### CODE REVIEW

**Comment by akien-mga** [comment]
Nice work @shackra, I'll give it a try asap :)

**Comment by okamstudio** [comment]
awesome, it would be nice to talk to Theo on how he can add this to the
build generator so every time a new build is done, docs are updated.

One point in case though, is that should this documentation be generated as
wiki for the stable version only, or updated as soon as it's pushed to
github?


On Fri, Oct 2, 2015 at 10:29 AM, Rémi Verschelde <notifications@github.com>
wrote:

> Nice work @shackra <https://github.com/shackra>, I'll give it a try asap
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2549#issuecomment-145020340>.
>



-- 

*OkamStudio*

**Comment by akien-mga** [comment]
> One point in case though, is that should this documentation be generated as
wiki for the stable version only, or updated as soon as it's pushed to
github?

That's a very good question. If we can find a nice way to separate them, I think both would be relevant.

This question is also valid to a lesser extent to the rest of the wiki: should the documentation writer assume the latest master branch/upcoming stable release, write documentation for the latest published release, or both (e.g. write for master, and have a special formatting to pinpoint the differences in the previous stable release).

**Comment by shackra** [comment]
Thank you, @akien-mga and @okamstudio !

One question, thought: Is the script right? It just take **one** xml file as input were the other scripts I saw in `/docdump` takes a **list** of files. Also, `class_list.xml` lacks of few HTML commands, like `[html url]` that are processed by the other scripts in `/docdump`, in my contribution such command is not processed because is non-existent in the xml file (and because building a regular expression was easily than taking care of whatever is between `[html command]` and `[/html]`).

**Comment by reduz** [comment]
Yeah it's a single xml file nowadays

**Comment by shackra** [comment]
Good to know, @reduz !

**Comment by firefly2442** [comment]
Another nice option for the script might be to have it generate the XML file via Godot Tools.  This way you have an up-to-date version and aren't relying on the Github version to be correct.  Basically call: `./godot.x11.tools.64 -doctool latestXML.xml` and then use the output file.

**Comment by akien-mga** [comment]
>  Basically call: ./godot.x11.tools.64 -doctool latestXML.xml and then use the output file.

One should use the existing doc/base/classes.xml which is the file that contains all classes documentation, and is up to date.

**Comment by shackra** [comment]
@reduz if you need anything regarding this code, feel free to add a bug report and assign it to me (I guess that is not possible at all, but anyway xD)

**Pull request merged**
