### PR TITLE
Added new WASAPI driver for Windows

### PR DESCRIPTION
**Pull request by marcelofg55**
This implements a new audio driver using WASAPI (Shared Mode) for Windows.
Needs testing but so far it worked fine for me.
It should give a better latency compared to the RtAudio DirectSound one, again, needs testing.
Also this driver can support surround sound, but needs #10568 before I can support it here.

### CODE REVIEW

**Comment by vnen** [comment]
I would put this under `platform/windows` instead of `drivers`.

**Comment by marcelofg55** [comment]
@vnen Isn't it better to place it in drivers in case we might want to enable this driver as well for uwp?

**Comment by Zireael07** [comment]
No more RTAudio? This then should fix the intermittent RTAudio errors issue, yaay!

**Comment by vnen** [comment]
@marcelofg55 does it work with UWP? If so, then it makes sense leaving at `drivers`.

**Comment by reduz** [comment]
finally, the day to leave RtAudio behind is approaching..

**Comment by marcelofg55** [comment]
@vnen I've read UWP supports WASAPI so it should work, but I didn't test it on UWP though. I don't have a Windows Phone but maybe somebody with one could try it out :).

@Zireael07 Hopefully this driver will work better than the RtAudio one, it should have an improved latency.

**Pull request merged**
