### PR TITLE
CI: List contents of bin/ after build

### PR DESCRIPTION
**Pull request by akien-mga**
This can be used to compare impacts on the generated files
and especially their size in PRs.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]

**Comment by Calinou** [comment]
Would it be useful to run Bloaty on at least one of the binaries in the CI step?

**Comment by akien-mga** [comment]
> On top of that, would it be useful to run Bloaty on at least one of the binaries in the CI step?

Yeah, but we need to figure out what bloaty options make the most sense for us to actually interpret the data.

Might actually be worth making a dedicated GH action that would add this data to a website visualization so we can compare metrics for all builds.

**Comment by bruvzg** [comment]
> on at least one of the binaries in the CI step?

Not very useful for release builds, but it would be nice to have for Linux and macOS debug builds.

**Comment by reduz** [comment]
I would not really bother with bloaty, we can debug builds after we see a size change.

**Pull request merged**
