### PR TITLE
Add persistent states for export with debug, as patch on editor restarts

### LINKED ISSUE #98754: Restarting editor resets "Export With Debug" option
### Tested versions

4.3.stable

### System information

Godot v4.3.stable - macOS 15.0.1 - Vulkan (Mobile) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

The state of the 'Export With Debug' checkbox in the export project window gets reset to default (= on) between editor sessions and it's quite annoying for making release builds of my game because I always have to remember to uncheck it:

https://github.com/user-attachments/assets/ac0c6d8c-9815-410e-bc4e-9c821f11e162

In my humble opinion, this boolean shouldn't even be in the window there, but part of the export options, but that's perhaps more of a proposal than an issue report. Bringing the toggle over to the export settings would, however, solve this issue too.

### Steps to reproduce

1. Export a game to any platform with the Export With Debug unchecked.
2. Restart the editor.
3. Export again but notice that the checkbox is checked again.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Giganzo**
Fixes: https://github.com/godotengine/godot/issues/98754

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
This will finally put an end to a thorn in my side.

**Review by Repiteo — APPROVED** [review]
Not *too* familiar with this part of the code, but the codestyle checks out

**Comment by akien-mga** [comment]
I tend to agree with this statement in the bug report:

> In my humble opinion, this boolean shouldn't even be in the window there, but part of the export options, but that's perhaps more of a proposal than an issue report.

(Also with the fact that it's proposal material and thus not something to handle here.)

So until we do decide to change this, I agree with making the boolean on the export dialog persistent.

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
