### PR TITLE
[3.2] Mono/C#: Add iOS support

### PR DESCRIPTION
**Pull request by neikeq**
Right now, games only work on devices when exported with FullAOT+Interpreter.
There are some issues left that need to addressed for FullAOT alone. Right now,
it's giving issues with the Godot.NativeCalls static constructor.

### CODE REVIEW

**Comment by neikeq** [comment]
This PR is against the 3.2 branch. I'll be opening one against master as soon as I get C# working on it again after all the recent breaking changes.

I will be updating the build docs tomorrow.

**Comment by neikeq** [comment]
Updated the docs: godotengine/godot-docs#3265

**Comment by kruglinski** [comment]
Hope this will be merged to 3.2.x, so we don't have to wait 4.0 to use it

**Comment by neikeq** [comment]
Yes, this PR is against the 3.2 branch.

**Comment by akien-mga** [comment]
Thanks! I merged in a dedicated `3.2-mono-ios` branch for now based off the current `3.2`, so that I can use it to make a test release and get feedback on the new feature + regression testing.

**Pull request merged**
