### PR TITLE
Fix crash when there is no bones to rename when retargeting an imported skeleton

### LINKED ISSUE #88086: Editor crashes when importing a skeleton with bone names that already match the retargeting profile
### Tested versions

v4.3.dev.custom_build [36e943b6b]

### System information

Windows 10.0.22621

### Issue description

When importing a rigged model, the editor crashes if the bone names already match the `BoneMap`'s skeleton profile.

### Steps to reproduce

- Open the MRP, it has a "ybot.gltf" with a skeleton structure whose all bone names match the default SkeletonProfileHumanoid.
- Right-click "ybot.gltf" and reimport. The editor will crash.
- Note that unchecking `Rename bones` (Advanced Import Settings -> Skeleton3D -> Retarget -> Bone Renamer -> Rename bones) and reimporting don't crash the editor.

### Minimal reproduction project (MRP)

[import_crash.zip](https://github.com/godotengine/godot/files/14203846/import_crash.zip)

### PR DESCRIPTION
**Pull request by ydeltastar**
Fixes https://github.com/godotengine/godot/issues/88086

### CODE REVIEW

**Comment by tdaven** [comment]
Wonder if #87905 would also fix this.

**Comment by ydeltastar** [comment]
@tdaven Tested it and it does fix the issue.

**Comment by fire** [comment]
Does the other pr supersede this one?

**Comment by tdaven** [comment]
I think so since this only works when the map is empty where the other PR prevents bad lookups  on a const HashMap with '[]' which purposely crashes but I was going to leave that decision up to a reviewer.

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/87905 supersedes this according to [tdaven](https://github.com/tdaven). Will archive this pull request this in a bit unless there's other opinions.

**Comment by ydeltastar** [comment]
Sounds good to me. Anything as long as retargeting is working.

**Comment by ydeltastar** [comment]
Crash fixed with the merging of https://github.com/godotengine/godot/pull/81746

**Pull request closed without merging**
