### PR TITLE
Improved file/folder drag preview for filesystem dock

### PR DESCRIPTION
**Pull request by ghost**
Fixes & small improvements to the labels shown when dragging files/folders from the file-system dock.

- Fixed folders getting an empty string label (As mentioned in #11428 by Xgor)
- Added icons for files/folders in drag preview
- Improved logic in the labels that appear if you are dragging a large number of files/folders
  - Don't show "1 more file(s)" label, as this row could have been used to list the file.
  - Added check for dragging folders exclusively
- Merged drag_files and drag_files_and_dirs to reduce code duplication.
- Simplified get_drag_data_fw and removed commented out code

Preview of the new drag:
filesystemdragdrop

### CODE REVIEW

**Comment by Zireael07** [comment]
Favorite vs favourite is just American vs British spelling. Which one does Godot use?

**Comment by Cradmon** [comment]
Yep, I usually spell it favourite, but godot seems to use the american version without the 'u'.

**Comment by akien-mga** [comment]
Needs rebasing after #10261.

**Comment by MillionOstrich** [comment]
The misspelling of favorite would have caused a bug and not allowed favorite folder drag events from being accepted, so thanks for catching it @Cradmon . Fixed it now & rebased.

**Pull request merged**
