### PR TITLE
Fix animation editor button callback parameter bug

### PR DESCRIPTION
**Pull request by hakuhan**
It just fix one error when opening window to choose animation clip to animation library.
image

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by hakuhan** [comment]
> Looks good! Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) for instructions.

updated

**Comment by hakuhan** [comment]
>

**Comment by hakuhan** [comment]
> You seem to have _merged_ instead of force pushing after your rebase, so there are now 4 commits instead of 1.

I will merge it into one commit. Sorry for that.

**Comment by akien-mga** [comment]
For the record, this was superseded by #62151.

**Pull request closed without merging**
