### PR TITLE
Bugfix: Fix Anim Tree blending inconsistency

### PR DESCRIPTION
**Pull request by marstaik**
Reduz had done some work on this to make it a "nicer" blend, but the logic is non-linear and non-deterministic.

In the old blending method, there is a rot_blend_accum that gets increased for each blend, and then the blend percentage is divided over the maximum.

This leads to non-linear scaling that is non-deterministic, since the order of the blends makes the blend weights different.

IE:
Blend 1 : 0.4 percent
Blend 2: 0.5 percent
Blend 3: 0.1 percent
-> (0.4/0.4 * rotation) * (0.5 / 0.9 * rotation) * ( 0.1 / 1.0 * rotation)

If you change the order:
Blend 3: 0.1
Blend 1: 0.4
Blend 2: 0.5
-> (0.1/0.1 * rotation) * (0.4 / 0.5 * rotation) * (0.5 / 1.0 * rotation)
...Which is inconsistent for the reasons above

This change also causes the triangles in blend spaces to jump dramatically between two zones, as you would go from blending triangle A into triangle B (where Blend 2 & 3 are the common edge between the triangles):
Blend 1: 0.1
Blend 2: 0.5
Blend 3: 0.4
->
Blend 2: 0.5
Blend 3: 0.4
Blend 4: 0.1

Strangely enough, the root motion code above it actually calculates all of the transforms correctly.

### CODE REVIEW

**Comment by reduz** [comment]
I had to change it because there was also a problem with the previous approach (blending from an empty quaternion) that I can't remember now.. let me grab lunch and I can give a check to this

**Comment by marstaik** [comment]
Updated to master

**Comment by marstaik** [comment]
Updated to master 4.0

**Comment by aaronfranke** [comment]
@marstaik Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by marstaik** [comment]
Yes, it needs to go in still. Ill see if I can rebase it today.

**Comment by fire** [comment]
CC @TokageItLab

**Comment by TokageItLab** [comment]
I agree this change. I also think that the inconsistency in the old blending method is not good. Perhaps if there is a problem, it is incompatibility, especially with the old NodeAdd.

Ref: #37661 or #42302

However, I am still in favor of this change.

**Comment by needleful** [comment]
I've tried cherry-picking this commit for 3.2.4 to fix my own issue (#46038).  This pull request fixes my issue, but it introduces a smaller bug.  For some reason this causes animations to have the wrong transforms for a single frame after calling `AnimationNodeStateMachinePlayback::start`.  It looks like the location, rotation, and scale are default.  Playback works just fine calling `travel`, which has me stumped (though that's a usable workaround for me for the time being).

**Comment by belzecue** [comment]
Does this issue explain this, where I'm blending two identical rotation degrees (0,0,0) at 50% and it's returning a glitchy rotation?

See: https://media4.giphy.com/media/vG6EWD3HUkbqU3Umf0/giphy.gif

**Comment by chipmu** [comment]
I've tried this patch in 3.3 RC7. Adding 2 exact same rotation animations of the same bone together will also add the Scale together, result in an increase in Scale eventhough the scale is unchanged in both animations. 

//scene/animation/animation_tree.cpp line 924
t->scale += scale * blend;

Adding two animations with bone scale of 1 shouldn't result in a scale of 2 because the difference is 0. Changing back to the previous code seems to work as expected.
t->scale = t->scale.linear_interpolate(scale, blend);

**Comment by TokageItLab** [comment]
Note: Maybe we need to remove the implicit normalization as in #51164.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/53903. Thanks for the contribution nonetheless!

**Comment by TokageItLab** [comment]
This is a too late, but I found a hint to fix this correctly in Godot3, so I am leaving this as a reminder.

In Godot4, some of the blend calculation methods have been changed, but as described in https://github.com/godotengine/godot/pull/80813, the correct blending can be calculated by computing the total weights first.

After all, the main problem with Godot3 blending is that it calculates each blend without knowing the total weights, which leads to incorrect final weight for each.

**Pull request closed without merging**
