### PR TITLE
Add color interpolation bar on each channel in ColorPicker

### PR DESCRIPTION
**Pull request by gongpha**
Like the most ColorPicker from several engines. For easy to visualize available colors in the channel.

Only shown in RGB and HSV mode. ( except Alpha )

ภาพ
ภาพ
Default theme :
ภาพ

Edit: issues in pictures
- The checkerboard at the alpha slider will be fixed by #43158 ( if it merged, I may need to resolve a conflict from this PR )
- Spinboxes on the right fixed by #46088

### CODE REVIEW

**Comment by RandomShaper** [comment]
A way to switch between the old and the new visualization would be very welcome. Maybe an editor setting, or, even better, a chefk box there at the color picker itself (it's already quite full, though).

**Comment by pycbouh** [comment]
What’s up with the spinboxes to the right, though?

**Comment by groud** [comment]
> A way to switch between the old and the new visualization would be very welcome. Maybe an editor setting, or, even better, a chefk box there at the color picker itself (it's already quite full, though).

What would be the point of it? This new version is simply better, and I don't believe we need to keep compatibility here.
This is mainly an editor/tools control node, I don't think it is often used in-game as is.

> What’s up with the spinboxes to the right, though?

This issue is likely fixed, there was an issue on master making some LineEdit/SpinBoxes too small. See https://github.com/godotengine/godot/pull/46088

**Comment by RandomShaper** [comment]
> What would be the point of it? This new version is simply better, and I don't believe we need to keep compatibility here.
> This is mainly an editor/tools control node, I don't think it is often used in-game as is.

You're right. I was giving an opinion as if the older sliders were displaying (for RGB) black-to-red, black-to-green and black-to-blue. My memory played a trick on me. That's why I thought the old way should be kept as an option.

Of course, the one this PR implements is far superior than the current flat colored sliders. 😃

**Comment by KoBeWi** [comment]
HSV mode is bugged:
Qw02vDINBx
- Changing Hue doesn't affect other sliders (notice how increasing Saturation changes the color of its slider). 
- Hue doesn't update with Saturation/Value changes.
- Value affects Alpha slider.

**Comment by gongpha** [comment]
> * Changing Hue doesn't affect other sliders (notice how increasing Saturation changes the color of its slider).
> 
> * Hue doesn't update with Saturation/Value changes.
> 
> * Value affects Alpha slider.

This also happened in the above HSV box, and I don't know about the HSV function. I may be to find a way to fix these bugs with another solution.

**Comment by fire** [comment]
I think PR should stand alone without these features, but I was wondering if you were also interested in making alternative mappings like: HSY' and other shapes.

We have to provide HSL, but it's not that great. There are better gradient generators that give better results in perceptual space.

image

image

**Comment by gongpha** [comment]
> 
> 
> I think [this] PR should stand alone without these features, but I was wondering if you were also interested in making alternative mappings like: HSY' and other shapes.
> 
> We have to provide HSV, but it's not that great. There are better gradient generators that give better results in perceptual space.

If someone will tell, This is enough to have only a gradient box. I honestly to leave them.

I know a bit HSY' color model. This would be okay to implement it when it's commonly used in the engine. BTW, I'm really interested.

**Review by KoBeWi — CHANGES_REQUESTED** [review]
Took another look and this is actually good (now after #46230 was merged). The new `bar_arrow` theme icon needs documentation though (you can use [doctool](https://docs.godotengine.org/en/stable/community/contributing/updating_the_class_reference.html#updating-the-documentation-template) to generate blank entry and fill the description).

Also, this is not critical, but I still think it would be nice if the hue bar in HSV was drawn with proper saturation and value. Right now it's not affected by other sliders.

**Comment by pycbouh** [comment]
> Also, this is not critical, but I still think it would be nice if the hue bar in HSV was drawn with proper saturation and value. Right now it's not affected by other sliders.

Wasn't that fixed in #46230 specifically to make it work here?

**Comment by KoBeWi** [comment]
> Wasn't that fixed in #46230 specifically to make it work here?

No, it fixed another thing. See here:
Pickqr
The HSV bar is drawn as texture, but changing saturation and value doesn't update its modulation. As I said, it's not critical and we can merge as is right now if it proves too difficult to do (value should be easy, but not sure about saturation).

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
