### PR TITLE
Animation: Add inspector plugin for key time edit & Change `track_find_key()` argument to find key with approximate

### LINKED ISSUE #69529: `AnimationTrackKeyEdit` time value undo/redo history is not recorded correctly when using grabber/slider
### Godot version

3.x, 4.0.dev

### System information

any

### Issue description

AnimationTrackKeyEdit sets a property to a dummy object and then sets the value again to the actual Animation resource, but the `track_remove_key_at_time()` in it must specify a time.

However, when the time value is set by SpinSlider's grabber/slider, it is updated every frame, and UndoRedo does not correctly record the needed time, and Undo does not correctly remove keys that need to be erased.

https://user-images.githubusercontent.com/61938263/205433351-a140fe5a-e33d-4d17-a1b2-8a2dd8d74f97.mp4

Even if the time is set correctly or the keys are deleted by idx, when the keys overlap during the updating of the frame values by grabbing/sliding in SpinSlider, the overlapped keys are deleted implicitly and cannot be recorded in the history.

In other words, in order to properly implement time editing history in the inspector, it is necessary to commit the action only when the grabber/slider is released, similar to AnimationTimelineEdit, instead of setting the value every frame.

To accomplish this, AnimationTrackKeyEdit would need to be fundamentally redesigned.

---

However, this bug can be avoided by disabling grabber altogether. It is definitely a naive workaround. But actually, most key time editing is done in AnimationTimelineEdit, and the inspector edit is there for direct input of values which should be the use case for 99% of the cases. So, I think it is fine...

### Steps to reproduce

Edit time value in AnimationTrackKeyEdit with grabber/slider

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #69529.

The key time needs to handle the commit timing since duplicate deletion and other processes occur. It should be implemented as InspectorPlugin. For now, other key values, etc. are left as they were in the previous implementation since it is working fine.

image

- Implement InspectorPlugin to edit key times (many of the line changes are due to moving the AnimationTrackKeyEdit declaration from the .cpp to the header)
- `track_find_key()` `bool p_exact` becomes `FindMode p_find_mode` to allows keys to be retrieved by approximate (it is stable to use `APPROX` for editor and `EXACT` for playback)
- The **displayed** precision of animation time in some GUIs has been unified to 0.0001 (but the precision in the .tres file is still 0.000001, might need to follow up somewhere else?)
- Improved FPS mode snapping accuracy
- Added some signals to `EditorSpinSlider`
- EditorPropertyInteger allows hiding buttons by hint
- Fixed a minor key retrieval bug in pingpong looping (still have a problem with key doubling right after playback, but it is a corner case)

### CODE REVIEW

**Review by fire — APPROVED** [review]
Mostly motion and not much change. Some bools were changed to enums.

**Comment by SaracenOne** [comment]
This looks fine and seems fixes the bug. Was approved in the animation code review meeting.

**Comment by TokageItLab** [comment]
As I mentions above, the animation keys in tscn/tres currently have a precision of 0.000001, so I saw no problem with unifying the precision in the editor to 0.0001. And I think if that becomes an issue in the future, we need to consider it from a more fundamental perspective.

**Comment by TokageItLab** [comment]
Rebased by conflicting.

**Review by SaracenOne — APPROVED** [review]
I reviewed this during the animation meeting and everything seemed okay. It indeed fixed the bug and I didn't notice any issues.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
