### PR TITLE
Add save shortcut for text shader editor to prevent it propagating to scene

### LINKED ISSUE #84039: Use ctrl+s in text shader editor to save shader file will save the above scene too
### Godot version

Godot v4.2.beta (ea0ab441c)

### System information

 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

When I write some shader in text shader editor, press Ctrl + S will not only save the shader file, but also save the opened scene.

Without an open scene it will show this :
image

Use File->Save file will not trigger the scene to be saved.

### Steps to reproduce

1. Open a new project, create a new scene and do some changes but don't save it. 
2. Create a test shader and edit it.
3. Press ctrl s when the focus is at shader editor and observe the scene is also saved. 

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #84039

This is a pr for bug fix, I add other shortcuts in #84063

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
Basically the same as https://github.com/godotengine/godot/pull/79337.

**Comment by KoBeWi** [comment]
Not really, that PR changed an existing shortcut, this PR adds a new one. We could add shortcuts to other menu items for consistency.

**Comment by jsjtxietian** [comment]
> We could add shortcuts to other menu items for consistency.

That is partly done in #84063 , I will take a look if there are any more shortcuts can be added.

> we should handle built-in shaders properly. Saving one should save the scene.

Ah yes! That needs some extra work probably in another PR.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
