### PR TITLE
Make Image.get_size() return a Vector2i instead of a Vector2

### LINKED ISSUE #62856: Image.get_size() should return a Vector2i
### Godot version

4.x

### System information

Any

### Issue description

```
Vector2 Image::get_size() const {
	return Vector2(width, height);
}
```
Returning a Vector2i would probably make more sense, since width and height are integers.

### Steps to reproduce

-

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by samdze**
Closes #62856

### CODE REVIEW

**Comment by fire-forge** [comment]
The documentation needs to be updated as well:

**Comment by fire-forge** [comment]
The documentation needs to be updated too:

https://github.com/godotengine/godot/blob/d26442e709f6361af9ac755ec9291bb43f2cd69b/doc/classes/Image.xml#L252-L253

**Comment by samdze** [comment]
Done!

**Review by fire-forge — APPROVED** [review]

**Comment by clayjohn** [comment]
``get_size()`` is used throughout the codebase. This should likely be accompanied by a review of where it is being used and those uses should be updated to Vector2i/Size2i as well

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This is good on its own, but we need to check other simliar places in the codebase that are pre Vector2i

**Comment by akien-mga** [comment]
Thanks!

**Comment by fire-forge** [comment]
> This is good on its own, but we need to check other simliar places in the codebase that are pre Vector2i

@reduz I did the rest of the Image and ImageTexture methods in https://github.com/godotengine/godot/pull/62871. I'm sure there are many other places that need conversion, but I haven't found any yet.

**Pull request merged**
