### PR TITLE
Add Arrange functionality

### PR DESCRIPTION
**Pull request by volzhs**
arrange

Arrange panel is visible when selecting 2 or more `CanvasItem` nodes.
too late for 3.2? :smile: 

_Edit : Arrange tool was moved to Toolbar from Inspector._

### CODE REVIEW

**Comment by volzhs** [comment]
I already tried https://github.com/godotengine/godot-design/tree/master/engine/icons/optimize.py
but it didn't work on my machine.
I hope someone takes care of svgs later.

**Comment by groud** [comment]
Wow, that looks great.
My only concern is the position of the panel, since this place was never used before. But I dont have a better idea.

**Comment by volzhs** [comment]
I made a another dock for it but it wasted too much space. :)
after that, I noticed this is only usable when selecteing multiple nodes.
so I added it on Inspector, only available with "MultiNodeEdit".
it actually does not depend on "MultiNodeEdit" plugin but it works as is.
and changing a position property with arrange tool in Inspector is reasonable for me. :smile:

**Comment by groud** [comment]
Thinking about it, I believe the best position for now is probably within the inspector, being the position property (but still only visible when multiple node are selected). This is likely possible with an Inspector plug-in.

**Comment by volzhs** [comment]
showing a arrange tool at fixed position is also good like other tools i think, not being hidden in somewhere inside Inspector.

**Comment by groud** [comment]
For me it takes too much space as is. When you select multiple 2d nodes and want to edit them via the inspector, you end up with and inspector size significantly shrinked which is not a very convinient solution. 

IMHO, this is not a feature that is going to be used often, so it can be hidden inside the inspector, that's not a problem to me.
But if this solution does not work, it would be better to simply pop up a dock like for the tilemap editor, with those options, outside of the inspector dock.

**Comment by volzhs** [comment]
maybe adding an arrange icon at toolbar then?

**Comment by groud** [comment]
> maybe adding an arrange icon at toolbar then?

With a dropdown menu ? I guess that make sense.

**Comment by Zylann** [comment]
I was thinking of a dropdown menu too, this way it doesn't have to take much space all the time (you could even put it in the menubar but maybe there isnt enough horizontal space)

**Comment by volzhs** [comment]
Arrange tool was moved to Toolbar from Inspector.
Gif is updated in OP.

**Comment by groud** [comment]
If this works fine with point node (like basic Node2Ds or Position2D), and does not screw everything too much with scaled/rotated nodes, tt looks ok to be merged to me. :)

**Comment by volzhs** [comment]
hm... for the rotated nodes, I think, I need to calculate proper bound.

**Comment by Calinou** [comment]
This looks great! We could perhaps use this for 3D as well in 4.0 :slightly_smiling_face:

**Comment by aaronfranke** [comment]
@volzhs Is this still desired? If so, it needs to be rebased on the latest master branch.

Is there any reason this can't be an add-on in the asset library? I know off hand that editor plugins can add menus there, and they are also able to get selected nodes and modify them, so it should be possible to do this in an add-on.

**Comment by fire** [comment]
I would be interested in pushing for a merge into master for this.

Are you still interested to rebase?

**Comment by Anutrix** [comment]
@volzhs Please rebase.

This is a real useful feature especially for new developers trying to design their game UIs. Beginners tend to avoid or often don't know which add-ons to install. This will greatly improve their UI development experience if its supported out of the box.

Also, another usecase is when presenting/demonstrating stuff to/by design team.

**Comment by YuriSizov** [comment]
> This will greatly improve their UI development experience if its supported out of the box.

I'm concerned that this seems to only rearrange controls relative to the default resolution using position (and anchors). It is often more desirable to utilize containers there, box containers specifically. This type of easy arrangement can lead to bad practices when designing UI, and in the end require users to rework UIs with a more scalable solution.

Great for prototyping though. Which is why it may be better as an addon.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting and agreed that:
- While this looks useful for prototyping, there are already better ways to arrange things using anchors and layouts for Controls, or smart snapping to the grid / rulers.
- This could be well suited as a GDScript plugin so that it can be used for prototyping without being recommended as a good way to arrange UI/nodes in space.
- Might warrant further discussion in a proposal (which didn't exist at the time this PR was opened) to see what actual real life use cases users may have for this feature / plugin. We're not strictly opposed to merging something along those lines but as it stands today the need isn't so clear.

**Pull request closed without merging**
