### PR TITLE
Fix IntelliSense

### PR DESCRIPTION
**Pull request by Listwon**
Fix the CPPPATH passed to MSVSProject. Uses SCons Dir() function to convert "#" paths http://www.scons.org/doc/0.97/HTML/scons-user/a3414.html#CV-CPPPATH

### CODE REVIEW

**Comment by fire** [comment]
Woot!

**Comment by fire** [comment]
These includes are also missing:

```
modules/gdnative/include
thirdparty/etc2comp
thirdparty/squish
thirdparty/openssl
thirdparty/libwebp
thirdparty/pcre2/src
thirdparty/pvrtccompressor
thirdparty/enet
thirdparty/jpeg-compressor
```

**Comment by Listwon** [comment]
Hi @fire ! I think it's out of the scope of my PR, because they don't append CPPPATH to env (look at modules/gdnative/SCsub, it appends CPPPATH to gdn_env or modules/jpg/SCsub, it appends to env_jpg which is the copy of env_modules ?! it's pretty weird). I think it'll autofix when they'll be added properly to our scons build chain. I don't even know why it differs in these SCsubs.

**Comment by fire** [comment]
Anyways, this pr is making progress on that include problem, so it looks good. I tried it.

**Comment by fire** [comment]
Is it possible to for each all the difference envs? and add those cpp paths to this?

**Comment by Listwon** [comment]
I think that we need to ask @reduz what is the purpose of not using the global env here.

**Pull request merged**
