### PR TITLE
Improve connected grapheme handling in the RTL CharFX.

### PR DESCRIPTION
**Pull request by bruvzg**
Add `GRAPHEME_IS_CONNECTED` flag to connected grapheme.
Apply RTL displacement FX only to the whole connected grapheme.
Pass more glyph info (flags and number of glyph in grapheme) to the custom RTL FX.

https://user-images.githubusercontent.com/7645683/134147672-778e8277-2d7d-47d7-bb13-3b77920b959b.mov

### CODE REVIEW

**Review by akien-mga — COMMENTED** [review]
Code looks good to me, I'll give it a try locally. (And see if I can still reproduce a possibly related issue where outlines were wrongly displaced by the RichTextEffects.)

**Comment by akien-mga** [comment]
> (And see if I can still reproduce a possibly related issue where outlines were wrongly displaced by the RichTextEffects.)

Yeah I can reproduce it but I think it's an unrelated bug in the implementation of that specific RichTextEffect, I'll open a dedicated issue:
Screenshot_20210921_121025

Here's an updated project with nicer animations now that bbcode+percent visible was fixed. And including Urdu and Arabic:
[TestRTLEffectsArabic.zip](https://github.com/godotengine/godot/files/7202450/TestRTLEffectsArabic.zip)

https://user-images.githubusercontent.com/4701338/134157067-8d6de81a-555e-42f1-9a37-8b1fd54ee6d7.mp4

**Comment by bruvzg** [comment]
> And see if I can still reproduce a possibly related issue where outlines were wrongly displaced by the RichTextEffects.

Fixed, outline was using wrong offset variable as input.

**Comment by bruvzg** [comment]
https://user-images.githubusercontent.com/7645683/134158595-dc4b44ab-bb5d-4b8b-a3d3-9e11b5828b81.mov

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
