### PR TITLE
seek theora in progress

### PR DESCRIPTION
**Pull request by hungrymonkey**
First Ogg Theora Seek Attempt

Ogg Tidbits
Ogg lacks a seek table.
Timestamp exists on the ogg page with the closing packet stream.
Ogg_page_packets can discern which page has a timestamp.
Keyframes exist in pages with ogg_pages_packets(&og) == 1

Proposal
Split the file into BUFFERSIZE segments for binary searching and backtracking.

Algorithm
Binary Search Ogg Page Timestamps
Backtrack to Keyframe
Catch up to Seek

Section 1:
This section is implemented as nested loops. The inner loops finds an unprocessed buffer segment and retrieves the first ogg_page even if it spans across buffer segments.

The outer loop compares the ogg_page into an iterative binary search. Since ogg_page_packets can discern the granulepos or time stamp, no ogg_packet is inspected.

Section 2:
The section is implemented as a buffer sync step to combine all ogg_pages into one ogg_packet.

Section 3:
Submit the frames into the theora decoder and advance the video forward until the buffer catches up to the seek time.

Modified
Implemented Seek
Added BUFFERSIZE and remove the hard coded 4096

Known Bugs

- [x] ~~Seek cannot find subsequent ogg_pages in the buffer segment. When a buffer section has two ogg_pages and the keyframe is encoded in the latter ogg_page. Seek will not find it.~~

- [ ] VideoTheoraStreak is littered with time resets. Currently, seek only works during play mode.

- [x] ~~More audio frames needs to be dropped when videobuf_time > audio_time within the stream~~

- [x] ~~Seek 0 does not work~~

- [x] ~~Small artifacts at the beginning of the video~~

- [x] ~~Crashes godot when using a seeking near the end line: 771~~ https://github.com/godotengine/godot/pull/32539/commits/d4930c9600d266736c9d193f9619014798398edb

Links
https://www.theora.org/doc/libtheora-1.0/group__decfuncs.html
https://xiph.org/oggz/doc/group__basics.html

Issue #14430

Seek works somewhat. I need to fix these three bugs.
https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_stereo.ogg
I managed run big_buck_bunny.ogv

### CODE REVIEW

**Comment by hungrymonkey** [comment]
@akien-mga  Can somebody help review the code? I managed to implement my original goals, but I need some idea on how I should change `play()` behavior, etc. How should I clean up my 200 line seek for better maintenance?

**Comment by hungrymonkey** [comment]
@akien-mga  Should I rebase the onto master?  When will godot 4.0 be released?

**Comment by hungrymonkey** [comment]
Upstream broke Ogv Thoera Player. I have to wait until Issue #36647  is fixed.

**Comment by Calinou** [comment]
- Superseded by https://github.com/godotengine/godot/pull/102360. Thanks for the contribution nonetheless!

**Pull request closed without merging**
