### PR TITLE
Add physics process delta timing to signals.

### PR DESCRIPTION
**Pull request by radiantgurl**
Adds new arguments to the physics and process signals.

### CODE REVIEW

**Comment by RadiantUwU** [comment]
Can break compatibility with methods directly connected to it.

**Comment by timothyqiu** [comment]
These delta times can be easily accessed via a node's `get_process_delta_time()` and `get_physics_process_delta_time()`.

If you want to access these from outside the node system, I think a better option is to expose `SceneTree`'s `get_process_time()` and `get_physics_process_time()`.

**Comment by KoBeWi** [comment]
> If you want to access these from outside the node system, I think a better option is to expose SceneTree's get_process_time() and get_physics_process_time().

You can do `Engine.get_main_loop().root.get_process_delta_time()`.

**Comment by AThousandShips** [comment]
This was attempted and abandoned previously:
* https://github.com/godotengine/godot/pull/86858

See https://github.com/godotengine/godot/pull/86858#issuecomment-1879756929

**Pull request closed without merging**
