### PR TITLE
iphone platform fixes

### PR DESCRIPTION
**Pull request by kurikaesu**
Just getting the iphone platform compiling again.

### CODE REVIEW

**Comment by akien-mga** [comment]
Is commit bf83e31 really needed? As far as I know line endings were already fixed in aad2bbd.
It would be nice if you could rebase to get rid of the first two commits (see ```git rebase -i HEAD~4```). Also a tip for updating your fork: use ```git pull --rebase```, it will avoid the creation of such "Merge branch [...]" commits.

**Comment by kurikaesu** [comment]
That commit probably isn't necessary. I did that on my branch either before or just a little after the original fix was implemented but I hadn't pulled that change in. I can close this pull request and rebase if it'll make things cleaner.

**Comment by akien-mga** [comment]
> I can close this pull request and rebase if it'll make things cleaner.

You should also be able to rebase it without closing the PR, and the PR will get updated automatically.

**Comment by romulox-x** [comment]
Under what circumstances is it not building?  Maybe the timing worked out by coincidence, but I just upgraded to XCode 7, which required some fixes to the code, but not these fixes.  Did something break building in XCode 6, and I upgraded just in time to miss it?  WIth my unrelated changes, I'm building fine in 7 (ignoring some warning based on bugs that 7 apparently introduced).

kurikaesu, do you build in XCode 6?  If so, I'd love it if you could test the changes required for building in 7, to see if they break anything in 6.

**Comment by kurikaesu** [comment]
I'm using xcode 7.1.
I rolled back to just before this commit and tried compiling again.
Errors from one compiled file is visible here: http://pastebin.com/CZgdxwDB

It may be that this could have been fixed and I just haven't updated my repository to the latest code yet.

**Comment by kurikaesu** [comment]
Hmmn, I'd best pull this request as I'm making a mess of my repo. I'll clean it up and re-request once I've set it all right.

**Comment by romulox-x** [comment]
Well, I guess some of these changes are addressing the same problems I faced.  I had to change more extern C stuff than you did to get it to stop complaining about C++ linkage.  Maybe I just got carried away changing it?  I was going to make a PR that only addressed the C++ linkage errors, if I could find out if this works on Xcode 6.  Or should we just not care and require you to update Xcode?

**Comment by punto-** [comment]
What is the latest version, and which one we would have to make the minimum?

**Comment by romulox-x** [comment]
I believe 7.1 is the latest, and that's what I'm on now. I upgraded from 6.? to 7.1.  I don't know what may have been in between.  Does anyone have access to a version earlier than 7.1, to see if the changes in this PR break compilation?  It would help us figure out a minimum required version of Xcode.

**Comment by romulox-x** [comment]
kurikaesu, do you deploy to an iOS device?  I'm curious if you have any thoughts on this: http://www.godotengine.org/topics/12626.  Sorry for the unrelated topic, but there don't seem to be many Godot users deploying to iOS right now, so you have to grab people when you find them!  And I don't see a way to send private messages on GitHub.

**Comment by kurikaesu** [comment]
romulox-x, I'll definitely be deploying primarily to an iOS device.
If anything I'll probably take on fixing up the iOS exporter and maybe switching things over to Swift rather than Objective C.

I'll have a look at that issue you've linked.

**Comment by rssqian** [comment]
@romulox-x 
i use master code base and on mac os 10.10, xcode is 7.1
when compiling, show many Template C++ linages error.

users-MacBook-Pro:godot username$ scons p=iphone
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o platform/iphone/game_center.iphone.debug.o -c -fno-objc-arc -arch armv7 -fmessage-length=0 -fno-strict-aliasing -fdiagnostics-print-source-range-info -fdiagnostics-show-category=id -fdiagnostics-parseable-fixits -Wno-trigraphs -fpascal-strings -Wmissing-prototypes -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk -gdwarf-2 -fvisibility=hidden -Wno-sign-conversion -mthumb "-DIBOutlet=attribute((iboutlet))" "-DIBOutletCollection(ClassName)=attribute((iboutletcollection(ClassName)))" "-DIBAction=void)attribute((ibaction)" -miphoneos-version-min=5.1.1 -MMD -MT dependencies -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/ -D_DEBUG -DDEBUG=1 -gdwarf-2 -Wall -O0 -DDEBUG_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -fblocks -DGAME_CENTER_ENABLED -DSTOREKIT_ENABLED -DICLOUD_ENABLED -DDEBUG_MEMORY_ENABLED -DIPHONE_ENABLED -DUNIX_ENABLED -DGLES2_ENABLED -DMPC_FIXED_POINT -fexceptions -DMUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DOPUS_ENABLED -DTHEORA_ENABLED -DPNG_ENABLED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -DOPENSSL_THREADS -DL_ENDIAN -DGLES2_OVERRIDE -Icore -Icore/math -Itools -Idrivers -I. -Iplatform/iphone -Iplatform/iphone/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/OpenGLES.framework/Headers -
...
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/simd.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/vector.h:46:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/logic.h:226:5:{226:5-226:33}: error: templates must have C++ linkage [2]
template static SIMD_INLINE SIMD_BOOLEAN_TYPE all(const inttypeN predicate) { return ::vector_all(predicate); }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/logic.h:227:5:{227:5-227:33}: error: templates must have C++ linkage [2]
template static SIMD_INLINE SIMD_BOOLEAN_TYPE any(const inttypeN predicate) { return ::vector_any(predicate); }
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
....


Best Wishes,
Fengwei.

**Pull request closed without merging**
