### PR TITLE
Scale light shadow bias by soft_shadow_scale to reduce shadow acne

### LINKED ISSUE #54523: Vulkan: Default DirectionalLight shadow bias/light orientation with the preview environment causes visible acne on a BoxMesh
### Godot version

4.0.dev (fe6c65a1a)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

The default DirectionalLight shadow bias/light orientation with the preview environment causes visible acne on a newly created BoxMesh.
It's subtle, but noticeable:

image

There are two possible fixes to this:

- Rotate the DirectionalLight so the bias is less noticeable by default.
- Increase the default shadow bias for DirectionalLight.

### Steps to reproduce

- Create a MeshInstance and assign a BoxMesh resource to it.
- Notice subtle acne visible on one of the sides.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/54523

Supercedes: https://github.com/godotengine/godot/pull/55758 and partially supercedes https://github.com/godotengine/godot/pull/55757 (this does not affect normal bias)

This PR increases the amount of bias used proportional to the radius of the PCF shadow filter. When using a larger filter radius, we need to use a greater bias. This reduces the shadow acne visible for all quality settings (because ``soft_shadow_scale`` is greater than 1 for all quality settings above ``hard shadows``.

The unfortunate side effect of this change is an increase in peter-panning at high quality levels, but that is a necessary consequence to avoid shadow acne. I.e. without this PR if you tweak ``shadow_bias`` to the point of removing shadow acne you get about the same amount of peter-panning. 

_Before: Low Quality (default)_
Screenshot from 2022-11-06 10-52-04

_After: Low Quality_
Screenshot from 2022-11-06 10-54-00

_Before: Ultra Quality_
Screenshot from 2022-11-06 10-52-17

_After: Ultra Quality_
Screenshot from 2022-11-06 10-53-52

### CODE REVIEW

**Comment by Calinou** [comment]
> The unfortunate side effect of this change is an increase in peter-panning at high quality levels, but that is a necessary consequence to avoid shadow acne.

https://github.com/godotengine/godot/pull/55757 might help here, if we also decrease the default DirectionalLight3D shadow bias in exchange (but keep the doubled shadow normal bias from that PR).

**Comment by clayjohn** [comment]
> > The unfortunate side effect of this change is an increase in peter-panning at high quality levels, but that is a necessary consequence to avoid shadow acne.
> 
> #55757 might help here, if we also decrease the default DirectionalLight3D shadow bias in exchange (but keep the doubled shadow normal bias from that PR).

It is definitely worth looking into. I tried out a few variations of increased normal/decrease bias and wasn't able to reduce peter-panning much, but I think a closer look would be valuable.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
I approved the change in principle but I'm not sure this is the right time to merge such changes, as there's *a lot* more that would need splitting if we decide that this is the new standard. Started a discussion in maintainer channel, we can formalize this in a proposal later on to document the direction we want to go for. For now I'd tend to keep this and similar changes for 4.1.

**Comment by akien-mga** [comment]
Nevermind previous comment, wrong PR :P

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
