### PR TITLE
Fix ARVRAnchor and ARVRController error spam

### LINKED ISSUE #29542: Error spam when adding ARVRAnchor or ARVRController
**Godot version:**
3.2.dev.custom_build.197b65f32

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I add aRVRAnchor, then output is spammed by:
```
ERROR: find_by_type_and_id: Condition ' p_tracker_id == 0 ' is true. returned: __null
   At: servers/arvr_server.cpp:305.
```

### PR DESCRIPTION
**Pull request by qarmin**
Fix #29542

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Can't hurt doing it that way I guess. I'm wondering if the warnings/errors themselves actually serve much of a purpose. It seemed like a good idea at the time :)

**Review by BastiaanOlij — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
