### PR TITLE
Implements walking inwards/outwards the mouse cursor into 3d editor u…

### PR DESCRIPTION
**Pull request by evandropoa**
I´ve implemented a new way to walk the 3d space editor view.

Just put the mouse in the desired place in the 3d space view, hold the CTRL key and scrolls the mouse whell.

### CODE REVIEW

**Comment by akien-mga** [comment]
Sorry for the lack of review so far.

I'm not sure about this change, it sounds like it would conflict with existing hotkeys, as <kbd>Ctrl</kbd>` + mouse wheel is used to zoom in/out by default.

We're quite close to the 3.2 release by now and in feature freeze, so I'll move this to the next milestone. If it's approved by contributors and deemed safe enough to include in 3.2, we can change it back of course.

**Comment by evandropoa** [comment]
Hi,

Sorry for the delay, I may be wrong, but zoon in/out is activated with the mouse wheel regardless of the `CTRL` key, so I consider it available.

I will make some adjustments to compile with the changes that have been made to the camera's project_position function.

**Comment by Zireael07** [comment]
This is a candidate for quitting either way, as someone messed up a rebase.

**Comment by aaronfranke** [comment]
@evandropoa Is this still desired? If so, it needs to be rebased on the latest master branch, and also the above feedback needs to be addressed, including fixing the bad Git history.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by aaronfranke** [comment]
This PR has not received any new commits for over half a year and is abandoned, closing.

**Pull request closed without merging**
