### PR TITLE
CPUParticles emission shape values update dynamically

### LINKED ISSUE #42255: CPUParticles emission shape values do not update dynamically
**Godot version:**
Godot 3.2.3.stable

**OS/device including version:**
macOS Catalina 10.15.5

**Issue description:**
Just added a CPUParticles to my scene and went to change the emission shape, and it left "Points" up as an array after switching to Sphere. I clicked away from the CPUParticles and came back and it correctly updated to have Sphere Radius and so on, so I suspect someone missed a call to update the properties here.

**Steps to reproduce:**
1) Add a CPUParticles to a scene
2) Change the emission shape

Screen Shot 2020-09-22 at 5 11 52 PM

### PR DESCRIPTION
**Pull request by kotelifelif**
Fix #42255

### CODE REVIEW

**Comment by akien-mga** [comment]
I guess the same might be needed for CPUParticles2D?

**Comment by kotelifelif** [comment]
I think "yes".

**Comment by akien-mga** [comment]
Could you add it in this commit?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
