### PR TITLE
Fix box selection being cancelled immediately

### LINKED ISSUE #33948: Box selection doesn't work reliably in the 2D editor
**Godot version:** Git https://github.com/godotengine/godot/commit/aae9e11a1e1857bdaedacabb5a6ed89bcd8c8ca2

**OS/device including version:** Fedora 31, NVIDIA proprietary driver

**Issue description:**

In the 2D editor, box selection won't display a box and select nodes as expected, unless you move the mouse extremely fast on the first frame of selection.

This doesn't occur in the 3D editor. This bug doesn't appear to be related to the low processor usage mode option used by the editor; if you enable **Interface > Editor > Update Continuously** in the Editor Settings, the issue will remain.

This regression appeared between 3.2beta1 and 3.2beta2 (tested with the pre-release Linux binaries).

**Steps to reproduce:**

Move the mouse slowly and try to perform box selection in the 2D editor. Notice how the selection box is very small (or invisible).

Then try again while moving the mouse very quickly. The box should be visible, but small – it will only span the distance your mouse has moved for one rendered frame or so.

**Minimal reproduction project:** Can be reproduced in any project.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #33948

### CODE REVIEW

**Comment by akien-mga** [comment]
Nice branch name :P

Just for clarity, the regression was from #33737 (as you found out already).

**Review by akien-mga — APPROVED** [review]

**Comment by KoBeWi** [comment]
Seems like `selected_from_canvas` should be everywhere where CanvasItem editor changes editor selection. I noticed one more place, but it just slightly changes behavior (previously you could move objects while holding Shift and selecting them, which is weird IMO).

**Comment by akien-mga** [comment]
> I noticed one more place, but it just slightly changes behavior (previously you could move objects while holding Shift and selecting them, which is weird IMO).

Do you want to amend the PR with this change, or are you unsure whether it's correct?

**Comment by KoBeWi** [comment]
> Do you want to amend the PR with this change, or are you unsure whether it's correct?

The change is already done as a side-effect of the previous PR. If it's correct I don't need to do anything xd

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
