### PR TITLE
mbedtls: Update to upstream version 2.16.2

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by fire** [comment]
Breaks on Windows.

**Comment by akien-mga** [comment]
Looks like the new version enabled `MBEDTLS_THREADING_PTHREAD` and `MBEDTLS_THREADING_C` in `config.h`.

@Faless Did we disable those ourselves previously?

**Comment by Faless** [comment]
@akien-mga sorry about the late reply. I think threading was disabled by default. It seems to still be disabled in git: https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.16.2/include/mbedtls/config.h#L1645 . Not sure about the apache tarballs

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by akien-mga** [comment]
> I think threading was disabled by default. It seems to still be disabled in git: https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.16.2/include/mbedtls/config.h#L1645 . Not sure about the apache tarballs

For the reference, threading is again disabled in 2.16.3 apache tarballs (see #33560), so it seems like 2.16.2 had a packaging bug.

**Pull request merged**
