### PR TITLE
Fix loading and exporting of Theora and WebM video streams

### LINKED ISSUE #14954: Videos (used with VideoPlayer) not packaged in .pck of exported game
**Godot version:**

3.0b2

**OS/device including version:**

Win8, GTX1070

**Issue description:**

Videos used with VideoPlayer are not packaged in .pck of exported Windows game. Even with Export all and adding *.webm or *.ogv. This means that they don't play at all when you try to play the game outside of the project folder. 
Expected behavior is for videos to be packaged in the .pck so they play with just the .exe and the .pck. 

**Steps to reproduce:**
- Import a video to the project.
- Add a VideoPlayer node.
- Set the VideoPlayer node to play the video.
- Confirm that it plays when playing the project inside the Godot editor.
- Export the game outside of the project folder.
- Run the game. The video doesn't play.
- Move the game inside of the project folder. The video plays again.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+)
  for potential duplicates.

### PR DESCRIPTION
**Pull request by akien-mga**
Theora and WebM video streams were mistakenly imported with a ResourceImporter,
but those imported ogvstr and webmstr were simply links to the local resource.
While that works fine in the editor, it no longer works when exporting a game
as the "source" ogv and webm files are ommitted and only the ogvstr and webmstr
references were exported.

As discussed with @reduz, it doesn't make sense to import videos, as we only
intend to play them back and not modify them/access their raw data. As such we
use a ResourceFormatLoader instead of an importer, to load the file on the fly.
ogv and webm files linked to this loader are now considered as resources, and
thus exported.

Note: The Theora and WebM loaders lack any kind of validity check beyond the
existence of the target file, but it was already the case with the importer.
Better checks and error reports could be added, but those loaders will eventually
be obsoleted by GDNative plugins anyway.

Fixes #14954.

### CODE REVIEW

**Comment by akien-mga** [comment]
I need to test more but I think this breaks compatibility for existing scenes with `VideoPlayer`s with an attached `VideoStream`.

**Comment by akien-mga** [comment]
Actually it doesn't break compat, a 3.0 scene with a VideoPlayer opens and runs fine with this PR.

**Comment by Khrolon** [comment]
Hello guys! My skills in english and programing are in development. I have this same issue in my project. The ogv video works in game project, but when I export the debug screen show a error and the video don't start.
From what I understand this page show how to fix, but I don't know how to fix alone.
I need to use the ResourcePreloader? Or what? Can explain in more details? Sorry for that!

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
