### PR TITLE
[Net] Rename StreamPeerSSL to StreamPeerTLS.

### PR DESCRIPTION
**Pull request by Faless**
SSL has been deprectated almost 10 years ago.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good.

Some suggestions:
- The `ssl` variables in the changed code (and other related ones like `use_ssl`) could be changed too, but it's not critical (could also be done in the future as a general code quality pass).
- Should there be a compatibility binding like we have in `register_scene_types.cpp` or is that not relevant/possible for core types?

**Comment by akien-mga** [comment]
> * Should there be a compatibility binding like we have in `register_scene_types.cpp` or is that not relevant/possible for core types?

Looks like the only core remapping we have in `register_scene_types.cpp` is for `s/AStar/AStar3D/`.
But I'm not sure it's actually useful, both `AStar3D` and `StreamPeerTLS` are neither `Resource` nor `Node` but extend `RefCounted` directly, so I don't see how the compat remapping would be used (for nodes and resources it's used to allow opening scenes and resource files from `3.x` and remap the types automatically).

**Comment by akien-mga** [comment]
Thanks!

**Comment by Faless** [comment]
> * 
> 
> * Should there be a compatibility binding like we have in `register_scene_types.cpp` or is that not relevant/possible for core types?

I've added the class rename to the converter, I think that should be enough.



> * The `ssl` variables in the changed code (and other related ones like `use_ssl`) could be changed too, but it's not critical (could also be done in the future as a general code quality pass).

Sure, I'll make another PR :)

**Pull request merged**
