### PR TITLE
renamed .*spatial.* to .*node_3d.* for consistency

### PR DESCRIPTION
**Pull request by lahouaridc**
Renamed methods names in EditorPlugins and EditorGizmoPlugins etc... that where still using spatial to use node_3d for consistency with rest of godot 4.0.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I think methods like `forward_spatial_gui_input` are fine, it's consistent with 2D's `forward_canvas_gui_input`.

**Comment by aaronfranke** [comment]
@KoBeWi Maybe, but we already have `Node3DEditorPlugin` and `CanvasItemEditorPlugin`.

**Comment by KoBeWi** [comment]
If we go for consistency, maybe 2D methods should be renamed to `forward_canvas_item_gui_input`? Or just drop the node part and do `forward_2d_gui_input` / `forward_3d_gui_input`?

**Comment by lahouaridc** [comment]
main reason I started this change was this in GDScript:
add_spatial_gizmo_plugin and remove_spatial_gizmo_plugin

rest was just me geting carried away with removing spatial from the code I can see I have not gone through whole project though :) (small steps)

**Comment by mhilbrunner** [comment]
PR meeting: reduz says a lot of these should be fixed, but if not we should fix them for consistency, yes :)

**Comment by Mickeon** [comment]
Oh dear. Whoops.
image

**Comment by Mickeon** [comment]
This has been salvaged by https://github.com/godotengine/godot/pull/65528.

**Pull request closed without merging**
