### PR TITLE
Use ANGLE multisample extensions for UWP

### PR DESCRIPTION
**Pull request by vnen**

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
I swear I had tried something similar a couple months ago and it didn't compile, but I guess I missed something back then :D

**Comment by akien-mga** [comment]
Thanks!

**Comment by GeorgeS2019** [comment]
@vnen @akien-mga Is it possible to have a label on ANGLE so  it is possible to identified issues related to ANGLE from 2D/3D issues related to angle (degree and radian)?

ANGLE issues may be relevant to UWP export, key to Version 4.0

**Comment by vnen** [comment]
@GeorgeS2019 all ANGLE issues are labeled with UWP because it's the only platform directly affected (technically Web too, since Chrome uses ANGLE, but we can't control that one), so specific label is not useful. Also, I tend to always spell it "**ANGLE**" (all caps), so it's not confused with a geometric angle, which also should be clear by context.

ANGLE was a Google effort since the beginning, Microsoft just helped port it to UWP with a fork. What happened now is that they merged, so Microsoft don't maintain a fork anymore.

**Comment by GeorgeS2019** [comment]
@vnen It is not possible to search [ANGLE specific issue](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=ANGLE). The found issues are not labelled as UWP. Perhaps I am wrong?

**Comment by Calinou** [comment]
@GeorgeS2019 You can exclude the label as follows: `angle -label:platform:uwp`

**Pull request merged**
