### PR TITLE
Fix android plugin functions are not called

### PR DESCRIPTION
**Pull request by volzhs**
some functions are not called properly in android plugin after #39855

### CODE REVIEW

**Comment by m4gr3d** [comment]
@volzhs The methods you added should already be automatically invoked based on the `Fragment` lifecycle. Is there an actual bug that's caused by not having them?

**Comment by volzhs** [comment]
@m4gr3d yes. I'm having an issue which is `onMainActivityResult` is not called in android custom plugin.
with this fix, it solved.

**Comment by m4gr3d** [comment]
> @m4gr3d yes. I'm having an issue which is `onMainActivityResult` is not called in android custom plugin.
> with this fix, it solved.

@volzhs Did you call `startActivityForResult` instead of `getActivity().startActivityForResult` as mentioned in this [SO answer](https://stackoverflow.com/a/6147919)?

**Comment by m4gr3d** [comment]
> > @m4gr3d yes. I'm having an issue which is `onMainActivityResult` is not called in android custom plugin.
> > with this fix, it solved.
> 
> @volzhs Did you call `startActivityForResult` instead of `getActivity().startActivityForResult` as mentioned in this [SO answer](https://stackoverflow.com/a/6147919)?

@volzhs From the plugin code, it would be `getGodot().startActivityForResult` instead of `getActivity().startActivityForResult`.

**Comment by volzhs** [comment]
@m4gr3d  `getGodot().startActivityForResult` did fix my issue. :+1: 
I searched everywhere before this PR but couldn't find about this.
need documentation for it.
closing as this PR does not need.

**Comment by m4gr3d** [comment]
@volzhs Glad to hear! What were you using before?

**Comment by volzhs** [comment]
@m4gr3d it was `getActivity().startActivityForResult`

**Pull request closed without merging**
