### PR TITLE
Use disabled icons for CheckBox in DefaultTheme

### PR DESCRIPTION
**Pull request by DarkMessiah**
### CheckBox
| After | Before |
| --- | --- |
| image | image |

### PopupMenu
| After | Before |
| --- | --- |
| image | image |

P.S. I found that PopupMenu modulates the icon color for the disabled state. Is this necessary when using separate icons for each state?

### CODE REVIEW

**Comment by Calinou** [comment]
> P.S. I found that PopupMenu modulates the icon color for the disabled state. Is this necessary when using separate icons for each state?

Technically, we should get rid of either the modulation or the disabled icons, but this would break compatibility with existing custom themes.

**Comment by DarkMessiah** [comment]
If we remove modulation, all custom themes will also be changed. For example, EditorTheme:
| PopupMenu Without Modulation | PopupMenu With Modulation |
|---|---|
| image | image |

**Review by Calinou — APPROVED** [review]

**Comment by Calinou** [comment]
Note: This shouldn't be cherry-picked as it affects default theme appearance.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
