### PR TITLE
Shader Language: Implement read-only mecanism on builtins.

### LINKED ISSUE #14449: Godot Shader Language not reporting an error when trying to assign to a constant
Using latest master
Code example: https://pastebin.com/7X0jcfpt

### PR DESCRIPTION
**Pull request by raskyld**
Fixes #14449.

### CODE REVIEW

**Comment by Krakean** [comment]
@AlmightyScientist nice job! :)

**Comment by AlmightyScientist** [comment]
I updated the PR (squashed) to make clang happy xD.

@Krakean Thanks :)

We should open an enhancement issue so :D 
You mean auto-complete mecanics, or just the visual aspect of it? :)

**Comment by Krakean** [comment]
@AlmightyScientist 
>You mean auto-complete mecanics, or just the visual aspect of it? :)

More likely both. Currently writing shaders in godot shader editor is not very handy due to semi-working auto-complete for constants/builtins & context-aware things :-\
Just write a few yourself, you will feel it that autocompletion requires some attention :)

**Comment by AlmightyScientist** [comment]
@Krakean 

> Just write a few yourself, you will feel it that autocompletion requires some attention :)

You're completely right. I think we should at first enhance Shader Compiler semantics (maybe we could decrease the time between Ctrl+S and effective compilation).

**Comment by reduz** [comment]
Hey, had a fix myself underway for this, so just commited it but thanks a lot for the contribution though. I'm surprised you could figure out how shader compiler works that easily.

**Comment by AlmightyScientist** [comment]
You're welcome :)

**Pull request closed without merging**
