### PR TITLE
Add touchpad pinch zooming support

### PR DESCRIPTION
**Pull request by pixelpicosean**
Designed for touchpad users, make it possible to pinch zoom 2D canvas item editor.

A new button index constant is added to input event: GESTURE_MAGNIFY.

### CODE REVIEW

**Comment by akien-mga** [comment]
The current implementation would only work for OSX, right? Any pointer on what should be done to support it on X11 and Windows?

**Comment by reduz** [comment]
I think we should probably implement a special event for this, instead of using the mouse one. Now that all our events are custom objects this is likely the better approach.

**Comment by vnen** [comment]
`InputEventGesture` would be good indeed, with "tap", "pinch", "swipe", etc.

**Comment by pixelpicosean** [comment]
I am not familiar with X11 and Windows API, but the concept is very simple. While the gesture is recognized, get the magnify difference from that event, and directly set it as the `factor` of button event.

@reduz Timo suggested special events for gestures, and I tried but no luck. I created a new event class and notice that the event is lost after entering input_event script part. What should I do to make it work just like the other events?

**Comment by akien-mga** [comment]
Update on the status:
- The feature is interesting
- This PR only works for OSX, the feature should be implemented for all platforms (possibly by different contributors)
- The API should be reworked to use a new `InputEventGesture` object as suggested above

**Comment by akien-mga** [comment]
Closing as I don't intend to merge it as is for the aforementioned reasons. I'll add a link to it in the more global #1319 issue.

**Pull request closed without merging**
