### PR TITLE
Rename WorldMarginShape3D to InfinitePlaneShape3D

### LINKED ISSUE #816: Rename WorldMarginShape3D to InfinitePlane3D
The name makes absolutely no sence to me, can someone describe why it's named as it is. I could send a pr to change it but want to ask first.

### PR DESCRIPTION
**Pull request by MarcusElg**
**Why?**
- WorldMargin is a super strange name that is unclear what it actually does
- It's super clear to understand what infiniteplane does
- 4.0 is the perfect opportunity to rename stuff, this opportunity won't exist again until 5.0 which will probably be in like 5 years

Just naming it plane makes it unclear that it's infinite which some people pointed out so I think infiniteplane is the perfect name :D But I'm sure people have thoughts about this, so comment below!

Fixes https://github.com/godotengine/godot-proposals/issues/816

### CODE REVIEW

**Comment by MCrafterzz** [comment]
hmm for some reason travis failes. Seams like it still thinks the old file excists 🤔

**Comment by akien-mga** [comment]
`Plane` was renamed to `WorldMargin` to make it clear that its *only* use case is as a world margin. It's not safe to use for precision collision checks, and thus as a "floor" shape as many users try to use it for, and then report bugs about shapes passing through the floor.

Renaming it back to `InfinitePlane` only improves the original issue slightly, by making it clear that `Plane` is infinite, but that still doesn't tell the vast majority of users that it's not meant to be relied on for physics.

**Comment by madmiraal** [comment]
It's worth noting that #39361 fixes the `PlaneShape` problems in Godot physics and #35945 fixes the `PlaneShape` problems in Bullet physics.

**Comment by aaronfranke** [comment]
@MCrafterzz Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch. From the discussion above, it sounds like this might not be desired, if so this can just be closed, but otherwise you need to rebase this before it can be considered.

**Pull request closed without merging**
