### PR TITLE
Android: Fixed problems with memory leaks due to absent ReleaseStringUTFChars calls.

### LINKED ISSUE #26317: Android: Memory leaks, missing ReleaseStringUTFChars JNI calls
**Godot version:**
3.1 beta, ce114e35dda4b3f282abb458f8409db2369b279e

**OS/device including version:**
Android

**Issue description:**
I see a lot of **GetStringUTFChars** calls in Android specific code. All of them look like:
`String ret = String::utf8(env->GetStringUTFChars((jstring)str, NULL));`
At the same time there are no ReleaseStringUTFChars calls which are obligatory.
https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html
This is a definite memory leak, to confirm it you can take a look at source code:
https://android.googlesource.com/platform/art/+/kitkat-dev/runtime/jni_internal.cc
```
static const char* GetStringUTFChars(JNIEnv* env, jstring java_string, jboolean* is_copy) {
--
  | if (java_string == NULL) {
  | return NULL;
  | }
  | if (is_copy != NULL) {
  | *is_copy = JNI_TRUE;
  | }
  | ScopedObjectAccess soa(env);
  | String* s = soa.Decode<String*>(java_string);
  | size_t byte_count = s->GetUtfLength();
  | char* bytes = new char[byte_count + 1];
  | CHECK(bytes != NULL);  // bionic aborts anyway.
  | const uint16_t* chars = s->GetCharArray()->GetData() + s->GetOffset();
  | ConvertUtf16ToModifiedUtf8(bytes, chars, s->GetLength());
  | bytes[byte_count] = '\0';
  | return bytes;
  | }
```
On this Android version a copy of string is done **every time**. And there are no other way to free it, it's not done even if String instance is deleted.

I would propose to make a merge request by myself with a helper function that converts jstring to Godot String.

### PR DESCRIPTION
**Pull request by ivanarh**
I would like this fix to be merged to 3.1.

*Bugsquad edit:* Fixes #26317.

### CODE REVIEW

**Comment by hpvb** [comment]
Style issues:
```diff
--- a/platform/android/dir_access_jandroid.cpp	2019-02-26 22:40:56.812085309 +0000
+++ b/platform/android/dir_access_jandroid.cpp	2019-02-26 22:41:05.121288484 +0000
@@ -31,8 +31,8 @@
 #include "dir_access_jandroid.h"
 #include "core/print_string.h"
 #include "file_access_jandroid.h"
-#include "thread_jandroid.h"
 #include "string_android.h"
+#include "thread_jandroid.h"
 
 jobject DirAccessJAndroid::io = NULL;
 jclass DirAccessJAndroid::cls = NULL;
--- a/platform/android/java_class_wrapper.cpp	2019-02-26 22:40:56.812085309 +0000
+++ b/platform/android/java_class_wrapper.cpp	2019-02-26 22:41:05.145091279 +0000
@@ -29,8 +29,8 @@
 /*************************************************************************/
 
 #include "java_class_wrapper.h"
-#include "thread_jandroid.h"
 #include "string_android.h"
+#include "thread_jandroid.h"
 
 bool JavaClass::_call_method(JavaObject *p_instance, const StringName &p_method, const Variant **p_args, int p_argcount, Variant::CallError &r_error, Variant &ret) {
 
--- a/platform/android/java_glue.cpp	2019-02-26 22:40:56.812085309 +0000
+++ b/platform/android/java_glue.cpp	2019-02-26 22:41:05.193176093 +0000
@@ -41,8 +41,8 @@
 #include "main/input_default.h"
 #include "main/main.h"
 #include "os_android.h"
-#include "thread_jandroid.h"
 #include "string_android.h"
+#include "thread_jandroid.h"
 #include <unistd.h>
 
 static JavaClassWrapper *java_class_wrapper = NULL;
--- a/platform/android/string_android.h	2019-02-26 22:40:56.812085309 +0000
+++ b/platform/android/string_android.h	2019-02-26 22:41:05.266209149 +0000
@@ -30,9 +30,9 @@
 
 #ifndef STRING_ANDROID_H
 #define STRING_ANDROID_H
-#include <jni.h>
 #include "core/ustring.h"
 #include "thread_jandroid.h"
+#include <jni.h>
 
 /**
  * Converts JNI jstring to Godot String.
@@ -46,7 +46,7 @@
 		if (!env) {
 			env = ThreadAndroid::get_env();
 		}
-		const char * const source_utf8 = env->GetStringUTFChars(source, NULL);
+		const char *const source_utf8 = env->GetStringUTFChars(source, NULL);
 		if (source_utf8) {
 			result.parse_utf8(source_utf8);
 			env->ReleaseStringUTFChars(source, source_utf8);

```

**Review by RandomShaper — APPROVED** [review]
Aside from the style issues, looks good to me.

**Comment by akien-mga** [comment]
Could you squash the two commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by akien-mga** [comment]
Also FYI, the email you used to author the second commit is not the same as the one in the first commit (not a problem, but mentioning just in case).

**Comment by ivanarh** [comment]
> Could you squash the two commits together?
Done. Also rebased to actual master branch.

> Also FYI, the email you used to author the second commit is not the same as the one in the first commit (not a problem, but mentioning just in case).
Commits were done from different computers. Fixed.

**Review by akien-mga — APPROVED** [review]

**Review by volzhs — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
