### PR TITLE
CI: Bump version for `actions/checkout@v4` and `actions/setup-dotnet@v3`

### PR DESCRIPTION
**Pull request by akien-mga**
Let's give this a bit before merging, the `actions/checkout@v4` release has just been tagged, and all `@v3` actions seem to have broken: https://github.com/actions/checkout/issues/1448

Let's see if they decide to roll things back or what the resolution will be.

*Edit:* Seems like the incident got resolved, the update should be fine. It's mostly just changing the Node version used, and it doesn't really matter for us.

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
`actions/checkout@v3` is having another set of random failures. So far the reports seem to indicate that `@v4` works better, not clear whether it's just placebo but let's see if it helps.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
