### PR TITLE
Fix that `popup_centered` didn't take the window's size into consideration

### LINKED ISSUE #72949: [4.0-rc1] Visual Shader "Show Generated Code" button broken
### Godot version

4.0.rc1

### System information

macOS 13.1, Apple M1

### Issue description

The "Show Generated Code" button in Visual Shader no longer works (it was working in 4.0.beta17.) It merely changes color when clicked, but the window with the shader code no longer opens.

Screenshot 2023-02-09 at 09 26 38

### Steps to reproduce

1) Create any project with a visual shader (or use the attached MRP)
2) Click the "Show Generated Shader Code" button

### Minimal reproduction project

[MRP-Visual-Shader-Show-Generated-Code.zip](https://github.com/godotengine/godot/files/10694943/MRP-Visual-Shader-Show-Generated-Code.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
resolve #72949 (only tested it on linux)
alternative to #72954
regression from #62179

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Rindbee** [comment]
This PR may reopen #55894.

And why in that case, set the size first and then `popup()`, why not call `popup_centered()` directly with the given size?

**Comment by Sauermann** [comment]
You are correct, that this PR has reopened #55894 on Windows.
So there are two different expectations of how `popup_centered` should work:

#55894: don't take the previous size into consideration
#72949: do take the previous size into consideration

We would need to decide on which variant and adjust the according places, that use `popup_centered`.
Or add an additional parameter like `popup_centered(const Size2i &p_minsize, bool p_consider_previous_size)`.

**Comment by akien-mga** [comment]
I don't see what the use case would be for *not* taking the size into account? This would mean popping up centered with an unknown size, then setting the size, and then it's no longer centered.

**Comment by Rindbee** [comment]
> I don't see what the use case would be for _not_ taking the size into account? This would mean popping up centered with an unknown size, then setting the size, and then it's no longer centered.

Will popup at the smallest size when regardless of size. It is to consider the situation similar to #55894 to reuse the same popup window to display different content. #61982 and #62179 were created around the same time.

**Comment by Sauermann** [comment]
> to reuse the same popup window to display different content

this use-case could be handled by setting the size before the `popup_centered` call.

How about the following approach?
- `popup_centered()` no longer takes any parameter and adjusts only the position and makes the popup visible.

I have the impression, that `popup_centered` does too much in the background. Perhaps it would be better to make this more explicit?

With `Window::get_clamped_minimum_size`, `Window::get_contents_minimum_size`, `Window::get_contents_maximum_size` there are functions available to calculate the desired size.

**Comment by Rindbee** [comment]
Well, I think the problem may be caused by `_get_contents_minimum_size()`. In #62179, as before, `popup_centered()` does not use `size` directly. But, I removed part of code in`AcceptDialog::_get_contents_minimum_size()`.

**Comment by Rindbee** [comment]
I checked #62179. For the situation in #72949, the difference between before and after is mainly in `Window::get_clamped_minimum_size()`, that is, `VisualShaderEditor::preview_window` should enable `wrap_controls`, but in fact it does not, resulting in the use of `min_size` instead of the return value of `Window::_get_contents_minimum_size()`.

It is also a special case that `Window::_get_contents_minimum_size()` of `preview_window` can be changed with `Window::size`.
https://github.com/godotengine/godot/blob/929ee61170ec4d431d6d2cfeddccdec2a59a11b7/editor/plugins/visual_shader_editor_plugin.cpp#L4955-L4957

**Comment by YuriSizov** [comment]
Yes, I think this makes the most sense. If you want the min size, you can pass it explicitly. Which is in fact what we normally do with these popups that are shared between different views.

**Pull request merged**
