### PR TITLE
changes to default C# script template

### PR DESCRIPTION
**Pull request by KellyThomas**
After #19251 the C# template was missing a few line breaks:

```csharp
using Godot;
using System;

public class Demo : Node
{
    // Declare member variables here. Examples:
    // private int a = 2;
    // private string b = "text";

    // Called when the node enters the scene tree for the first time.    public override void _Ready()
    {
            }

//    // Called every frame. 'delta' is the elapsed time since the previous frame.//    public override void _Process(float delta)
//    {
//        //    }
}
```

While I was there I also changed it so it it uses the editor tabs/spaces setting, and the same placeholder tokens as template files.

The output should now look something like:

```csharp
using Godot;
using System;

public class Demo : Node
{
    // Declare member variables here. Examples:
    // private int a = 2;
    // private string b = "text";

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        
    }

//    // Called every frame. 'delta' is the elapsed time since the previous frame.
//    public override void _Process(float delta)
//    {
//        
//    }
}
```

### CODE REVIEW

**Comment by KellyThomas** [comment]
We are definitely using `%TS%` when using the script template files, and it seems to work here during my testing.

**Comment by YeldhamDev** [comment]
I was told by @akien-mga to leave the indentation hard-coded to spaces.

**Comment by akien-mga** [comment]
I don't mind either way, it's up to @neikeq and C# devs. As I understood it in the C# world it's spaces or die, so I guess hardcoded spaces makes sense :)

**Comment by akien-mga** [comment]
BTW, if using spaces, the commented out `_Process` should have the matching number of spaces after `//` to stay aligned as other methods (just like your IDE would do when commenting/uncommenting a code block).

**Comment by neikeq** [comment]
Looks good. Indeed, let's better keep hard-coded spaced for now.

**Pull request merged**
