### PR TITLE
[macOS] Control key + scroll wheel should zoom not pan

### LINKED ISSUE #32520: 3.1.1.  2D Mouse zoom does not behave same as 3D on Mac OS X.
**Godot version:**
3.1.1 stable

**OS/device including version:**
Mac OS X Mojave

**Issue description:**
Magic Mouse zooming does not work in 2D editor at all. However works fine in 3D Editor

Holding down CTRL+Mouse finger slide, zooms properly in 3D. There is even a setting in Editor Settings.

However CTRL+Mouse finger slide in 2D does NOT zoom. Instead it scrolls the viewport up/down left or right instead of zooming.  Also there are no Editor settings for zoom 2D.

**Editor settings available for keyword Zoom**
image

### PR DESCRIPTION
**Pull request by asmaloney**
Together with #39395 for 3.2.x, this fixes #32520

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
I can't reproduce the issue with a normal mouse, but if it works in 3D editor and not in 2D editor, it's probably should be fixed in the 2D editor itself. It might have the same issue with the trackpads on other OSs too.

**Comment by asmaloney** [comment]
Thanks @bruvzg.

When I was debugging, I put breakpoints in `CanvasItemEditor::_gui_input_zoom_or_pan()` which seems to handle the zoom and pan for 2d (?).

Without the change I'm proposing, Godot only generates pan events when trying to scroll with the magic mouse. `scrollWheel` (the function I modified) only sends _InputEventPanGesture_ or _InputEventMouseButton_.

1) Is `CanvasItemEditor::_gui_input_zoom_or_pan()` the correct code location for zooming/panning the 2D editor?
2) If it's only receiving _InputEventPanGesture_, how do I fix it there? The code is all based on  event types.
3) Is `Viewport::_gui_call_input` the place the 3D viewer processes input events? I can trace to there but then get lost to signals.

(I'm brand-new to the code base, so any pointers on where to find things or general design here would be helpful.)

**Comment by Calinou** [comment]
> Is Viewport::_gui_call_input the place the 3D viewer processes input events? I can trace to there but then get lost to signals.

The 3D editor viewport is provided by SpatialEditorPlugin, not Viewport (which is the base Viewport node).

**Comment by asmaloney** [comment]
So, based on the 3D code, what @bruvzg is proposing we do in 2D is:

1) recognize _InputEventPanGesture_ (at the bottom of `CanvasItemEditor::_gui_input_zoom_or_pan()`)
2) check for _control_ key explicitly (since it's not customizable like 3D's "Zoom Modifier")
3) "reinterpret" the gesture as a zoom (instead of pan)

Is that about right?

**Comment by asmaloney** [comment]
I went ahead and made the change that way [on the 3.2 branch](https://github.com/godotengine/godot/pull/39395/files).

If that's what you're looking for, please let me know and I can apply here on master as well.

**Comment by akien-mga** [comment]
Thanks!

**Comment by lukaskrepel** [comment]
(I am sorry if I'm double posting. I also commented at #32520 but am not sure if that's the right place, I'm new to this stuff.)

This issue still exists on v4.1.2
I cannot zoom with the mouse in 2D like in 3D.

**Pull request merged**
