### PR TITLE
Fix roundness of DebugSkipBreakpointsOff icon

### PR DESCRIPTION
**Pull request by pkowal1982**
I think DebugSkipBreakpointsOff icon is not round enough. With some part cut off it's design lacks unity and feels a little bit unreal. As a home brew game maker and humble contributor I think new one will do better in our icon bundle.
icon_change

### CODE REVIEW

**Comment by YuriSizov** [comment]
Also please run it through an optimizer and make sure it's just one line of markup inside (with an extra new line at the end).

**Comment by pkowal1982** [comment]
@adamscott Such a perfect answer! Problem is **it would break compability**, current icon is not a circle, it's slightly wider than higher. We would need to add some scaling also. :) Not sure if distortion was intentional but I will leave it rather round than circular. :)

@YuriSizov done :)

@akien-mga done :)

**Comment by pkowal1982** [comment]
@akien-mga Ok, made it perfectly circular. Just want to mention that also removed:
`fill-opacity=".996078"`
which can be found in few other icons but probably also was not intentional.

**Review by akien-mga — APPROVED** [review]

**Comment by YuriSizov** [comment]
> but probably also was not intentional.

Indeed, most of the icons relying on this should be normalized (and made sure to use the editor's palette).

**Comment by pkowal1982** [comment]
> Indeed, most of the icons relying on this should be normalized (and made sure to use the editor's palette).

I can grep through the other icons and remove this almost 1 fill-opacity in another PR as it will be very easy to review this way even if hits many files.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
