### PR TITLE
Add zstd compression support.

### PR DESCRIPTION
**Pull request by ghost**
zstd has much better compression speed and ratio, and better decompression speeds that currently available method.
Also set zstd as the default compression method for Compression as well as FileAccessCompressed methods.

Supersedes #8736.

### CODE REVIEW

**Comment by tagcup** [comment]
I used a very conservative compression level of 3, which can in principle go up to 21 (see [this plot](https://raw.githubusercontent.com/facebook/zstd/dev/doc/images/DCspeed5.png) for speed vs compression rate at different levels).

**Comment by Calinou** [comment]
How is this going to behave with the high-level multiplayer API? [zstd is said to be inefficient on small files](https://github.com/facebook/zstd#the-case-for-small-data-compression).

**Comment by tagcup** [comment]
This PR doesn't change the ENet default, which is no compression.

**Comment by tagcup** [comment]
So I mainly had files in mind with both zstd and lz4. Network compression is tricky and need careful evaluation of various trade-off based on the used streaming model, so I didn't really touch that part.

**Comment by reduz** [comment]
As I explained many times. ENet uses range coder as default compression (if I remember well). Any other compression method will do worse, due to packets being sent being super little.

**Comment by tagcup** [comment]
@reduz First time for me!
Actually the current default behavior is `COMPRESS_NONE` (see [here](https://github.com/godotengine/godot/blob/master/modules/enet/networked_multiplayer_enet.cpp#L678)) so I guess that needs to be changed then

**Comment by tagcup** [comment]
Ah, OK, this was the relevant issue: #8047

**Pull request merged**
