### PR TITLE
Generalized versions of min, max, clamp, sum for GDScript

### PR DESCRIPTION
**Pull request by ghost**
This is an exploration of various options of how `min`, `max`, `clamp` could be generalized (also see https://github.com/godotengine/godot/issues/13926). Adds `sum`.

## Option A: Multiple parameters

Meaning you can have more than 2 parameters.

```
max(1, 3, 7, 2)
> 7
```

```
sum(8, 2, 1)
> 11
```

For 2 parameters, e.g. `max(x,y)`, the new code (in this and the other options) stays as fast as the old code (about 60 ms for 1 million calls on my machine in release builds).

## Option B: Arrays and array flattening

Meaning you can not only pass in numeric values, but also arrays of values; the min or max computations happen on the flattened (unpacked) form of the input; arrays may contain nested arrays.

```
var x = [1, 2, 7, 1]
max(x)
> 7
```

```
max(3, 1, x, 4, [-1, 1])
> 7
```

For computing the min/max/sum of arrays, builtin code is 6.5 times faster than a pure GDScript implementation.

## Option C: Support Vector2, Vector3, Color

Support non-numeric types by applying the operation component-wise:

```
print(clamp(Color(0, 0.7, 0.3), Color(0.1, 0.1, 0.1), Color(0.5, 0.5, 0.5)))
> 0.1,0.5,0.3,1
```

```
print(min(Vector2(10, 10), Vector2(-5, 20)))	
> (-5, 10)
```

## Code size increase

I've measured the increase in (release build) code size for compiling the different options:

| Arrays	|	Vector2, Vector3, Color	| Code size increase| 
| --------| -------------------------------| ---------------------| 
| -	|			- 	|1K| 
| -	|			&#x2713;	|5K| 
| &#x2713;	|			-	|11K| 
| &#x2713;	|			&#x2713;	|16K| 

The top row is `min`, `max`, `sum` with multiple numeric arguments.

The hit in supporting arrays comes from having to generate code for all the different `PoolVector` variants.

Performance measurement code:

[perf-min-max.txt](https://github.com/godotengine/godot/files/1629243/perf-min-max.txt)

### CODE REVIEW

**Comment by Chtobi** [comment]
@poke1024 , great stuff! How about all() and any() for boolean arrays?

**Comment by mhilbrunner** [comment]
@poke1024 If GDScript had variadic functions (https://github.com/godotengine/godot/issues/16565), you could get Option B together with Option A for free by then doing:

```
var x = [1, 2, 7, 1]
max(x...)
```

**Comment by mhilbrunner** [comment]
Note from todays meeting: generalized clamp() is useful and this PR should be reduced to that, min()/max() should be methods on Arrays instead and move to a seperate PR.

**Comment by akien-mga** [comment]
> Note from todays meeting: generalized clamp() is useful and this PR should be reduced to that, min()/max() should be methods on Arrays instead and move to a seperate PR.

Bump :)

**Comment by poke1024** [comment]
Upon further revisiting this code, I'm not sure I really want to do this, as it makes no sense to me. Let me summarize:

* the remaining `clamp` (that would stay in this PR), only gets an additional `int` case (it currently only handles floats); this would be better handled in a new mini-PR to extend `clamp` to handle ints.
* moving `min`, `max`, `sum` to the arrays and pool arrays means all that code will go into the core. And it will be a lot more code and binary size than currently, since each of the 6 pool array variants will get its `min, max, sum` together with docs. It's just so much redundant bloat then.

**Comment by poke1024** [comment]
This is now changed to add `Array.min()`, `Array.max()`, `Array.sum()`. No changes to GDScript or to `clamp` in this PR (separate PR coming).

Two general notes:

(1) `min`, `max`, `sum` work on integers, reals, vector2, vector3, colors. That's what the code above  `reduce_array` deals with.
(2) Not supporting pool vectors would mean removing `reduce_pool_vector` and the calls inside `reduce_array` to it.
(3) Not supporting recursive evaluation would mean removing the `if (x->is_array())` case inside `reduce_variants`.

Pool vector support is not explicit, there are no methods in the pool vector variants. But you can always do `[anyPoolVector].min()`. 

I think that (2) and (3) are very handy, e.g. for computing a bbox of actors whose coordinates live in poolvectors: `[greenActorPositions, redActorPositions, playerPos, wallPos, globalBounds].min()`.

**Comment by poke1024** [comment]
The generalized implementation of `clamp` (for vectors, colors) relies on the min and max implementations done in this PR.

It doesn't make sense if I do a generalized clamp implementation that keeps all that stuff in GDScript, when this stuff is going to be in `Array` and thus in the core.

We should decide on the future of this PR first before generalizing clamp.

**Comment by reduz** [comment]
This is incredibly complex, just iterate the elements and call Variant::op with less and greater, and print an error if comparison fails..

**Comment by reduz** [comment]
Also there is no need to implement this in PoolVector, so just save some code and don't do it there

**Pull request closed without merging**
