### PR TITLE
 Redesigned the Project manager to waste less space in the UI

### PR DESCRIPTION
**Pull request by LaBlazer**
The old project manager had a lot of empty space so I've made it a bit more compact, made the search bar bigger and left-aligned the tabs because that's what godot uses everywhere by default now...

Here are pictures before and after the change
godot_2018-07-30_14-17-02
godot windows tools 32_2018-07-30_14-18-13

### CODE REVIEW

**Comment by swarnimarun** [comment]
I would recommend to squash commits once you have the changes finalized. Which I think you have now.

**Comment by LaBlazer** [comment]
Oops, this made it even worse...

**Comment by nunodonato** [comment]
my 2cents, I think the whole project manager needs a fresher look. For me, compacting things makes it look even worse. Who is complaining about lack of space in the project manager? :)

**Comment by Zylann** [comment]
Long time user so I might be biased, but I prefer the old one, just because there is "space to breathe" / more room to not misclick. New design feels cramped.

**Comment by LikeLakers2** [comment]
Have to agree with Zylann here, this new design feels a little cramped. I'm not entirely against it, but I'm not really for it either.

Perhaps maybe remove the label "Godot Engine - Project Manager"? That's already in the window title, so there's no reason we should be displaying it twice, and maybe it might make it feel a little less cramped.

**Comment by nunodonato** [comment]
also, take a look at a previous discussion https://github.com/godotengine/godot/issues/8135

**Comment by LaBlazer** [comment]
@LikeLakers2 like this?
godot windows tools 32_2018-07-30_22-13-30
godot windows tools 32_2018-07-30_22-14-50

**Comment by LikeLakers2** [comment]
@LaBlazer Yeah, those feel a bit better. I'm not sure how everyone else feels, but that little bit of extra space makes it feel that much less cramped to me.

I have no opinion on the positioning of the tabs, though. Either looks fine to me.

**Comment by adrianperreault** [comment]
If the space-saving effort were to make room for a more splash-screeny experience (with differing images for new releases), release notes, easy access to news headlines/featured addons... That would be pretty cool.

**Comment by toger5** [comment]
I also agree, that there is no. Need to save space in the project manager. Omyou Don't do actual work (which needs screen realastate) there.

Things that would actually matter:
 - cooler design (splashscreen like) since it is more a welcome screen it is actually worth caring aboht those things.
 - organization features (demos, favorties, featured projects, also a temp project would be really nice which gers deleted after closing the editor. So you can just est without creating a folder)
 - layout options to actually get more projects on screen. (Like a two column one, or a "only thumbnail version)

**Comment by LaBlazer** [comment]
@adrianperreault Maybe something like this? Covers and articles would be loaded from godotengine.org and it would open the website once you click on it...
68747470733a2f2f692e696d6775722e636f6d2f687248797245772e706e67

**Comment by vnen** [comment]
>  Covers and articles would be loaded from godotengine.org and it would open the website once you click on it...

I think *that* is a waste of space. A big picture is pointless, this is not a splash screen. It should be more function and less form. Also, Godot never connects to the internet without the user intent, and IMO it should remain this way.

I agree that the project manager can look better and be more usable. I don't think treating it as splash screen is the solution though.

**Comment by LikeLakers2** [comment]
Instead of a splash screen, I don't think it'd be too bad if a link to the Godot's website were added, personally. It would effectively serve the same purpose as the splash screen, just without using so much space, and only really requiring one or two more clicks. Where you would want to put that, though, I'm unsure.

**Pull request closed without merging**
