### PR TITLE
Clarifying how float(String from) parses partially invalid strings

### PR DESCRIPTION
**Pull request by Dancovich**
Update the description of this method to be in line with [code]int int(String from)[/code] in regards to how it deals with a completely invalid parameter and a partially invalid parameter.

### CODE REVIEW

**Comment by Dancovich** [comment]
Created this PR in response to comments in PR #34105 that pointed out mistakes in my edit.

The fixed problems in this PR are:

- Fixed explanation about invalid characters among valid ones. Thanks to @akien-mga it's now clear the parser stops at the first invalid character instead of just ignoring it, so `float("1a3")` returns 1, not 13. Maybe check if `int(String from)` has the same behavior? If that's the case then the documentation on `int` isn't completely accurate.
- Fixed a type where the text says `int(String from)` instead of `float(String from)`

**Comment by akien-mga** [comment]
Thanks!

I checked for `int()` and confirmed that its documentation is correct, `int("1ad3")` returns `13`, so contrarily to `float()` it does not stop at the first invalid char, but ignores them.

**Comment by aaronfranke** [comment]
@Dancovich For the future, take a look at the [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) article. You can modify an existing pull request with amend and force push, so that you don't have to open a new pull request to make changes.

**Comment by Dancovich** [comment]
Thanks @aaronfranke. I genuinely looked for a way to do this and couldn't find it, next time I'll follow this workflow.

**Pull request merged**
