### PR TITLE
Avoid switch statement in particles shader to workaround shader compiler crash on Apple silicon devices

### PR DESCRIPTION
**Pull request by clayjohn**
Partial cherrypick of https://github.com/godotengine/godot/pull/88816 for 4.2 and 4.1. This is the minimum needed to avoid the crash on Apple silicon devices (https://github.com/godotengine/godot/issues/72469)

I tested and confirmed that the issue is specifically using a switch statement where the first condition does nothing ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Shouldn't there be a comment here (and on `master` as well) informing why it needs to be done this way?

**Comment by clayjohn** [comment]
> Shouldn't there be a comment here (and on `master` as well) informing why it needs to be done this way?

Sure! 

In practice I'm not sure it matters since we would reject any PR that just changes an if statement to a switch

**Review by akien-mga — APPROVED** [review]
Looks good! I was wondering if we should backport those PRs to 4.2 and 4.1 indeed, a minimal pick like this for Apple devices only sounds great.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
