### PR TITLE
Automatically increase Light3D shadow bias when shadow blur is above 1.0

### PR DESCRIPTION
**Pull request by Calinou**
This makes it possible to adjust shadow blur without having to tweak bias to avoid shadow acne. The formula automatically increases shadow bias, normal bias and transmittance bias when shadow blur is above 1.0:

    shadow_blur_bias_factor = max(1, 0.5 + shadow_blur * 0.5);

At the highest shadow blur value allowed in the inspector (8), the shadow bias and normal bias will each be multiplied by 5.5.

Automatic adjustment is not performed for PCSS-style shadow blur (light size > 0) yet.

This partially addresses https://github.com/godotengine/godot/issues/53534.

## TODO

- [ ] Leave shadow bias unaffected when shadow quality is set to **Hard**, since constant blur will not affect the shadow's appearance with this setting.

## Preview

***Note:** The bias values used in the demo below are from https://github.com/godotengine/godot/pull/55757.*

### DirectionalLight3D

*Visible lines between PSSM shadow splits will be attenuated if https://github.com/godotengine/godot/pull/48776 is merged.*

#### Before

https://user-images.githubusercontent.com/180032/145440665-56b1fbfa-4539-4c87-8dd8-b0be664318b2.mp4

#### After

https://user-images.githubusercontent.com/180032/145439974-59419a0b-5e87-4422-9c78-1a2591bd20ae.mp4

#### Before

https://user-images.githubusercontent.com/180032/145440679-76be3e24-5055-4e99-9a81-ff11e63d2591.mp4

#### After

https://user-images.githubusercontent.com/180032/145439999-7db80d66-6266-49e7-92c3-f497fcd9e154.mp4

#### Before

https://user-images.githubusercontent.com/180032/145440692-f805f363-ab41-4d85-9801-f6027c371bf9.mp4

#### After

https://user-images.githubusercontent.com/180032/145440017-6f446e20-6a4d-4fe8-a82a-3eb8a6dc6327.mp4

### CODE REVIEW

**Comment by Ansraer** [comment]
Would be nice if this was somehow displayed in the inspector. Right now user input is just ignored if it is below the min value.

**Comment by mrjustaguy** [comment]
Does this change affect the total shadow blur (so after Quality blur multiplier is applied) or only the setting blur?

It should affect the total because higher quality softness tend to create more shadow acne because of their internal higher blur multipliers.

**Comment by Calinou** [comment]
> Would be nice if this was somehow displayed in the inspector. Right now user input is just ignored if it is below the min value.

This acts as a multiplier, so I don't see how the value can be ignored (regardless of the blur setting you're using). The multiplier itself is an implementation detail (like the shadow Z near/far ranges), so I didn't mention it in the class reference.

> Does this change affect the total shadow blur (so after Quality blur multiplier is applied) or only the setting blur?
> 
> It should affect the total because higher quality softness tend to create more shadow acne because of their internal higher blur multipliers.

Right now, this doesn't take the shadow quality blur factor into account. This should be feasible, but I think the base automatic adjustment will work well enough. I fear that further increasing the shadow bias factor automatically will result in too much peter-panning at high shadow quality settings.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/68339, which is a more robust solution to the original problem.

**Pull request closed without merging**
