### PR TITLE
Draw selected item on top of everything else

### LINKED ISSUE #27315: The selected node Gizmo in 3.1 can be very hard to see
Godot 3.1 stable, Win 10.

In some cases it can be hard to see where the selected node is placed in your scene, especially if you have a large scene with many nodes. In the example below the selected node is hidden behind other nodes. 

In my perfect world it would actually be something similar to 3.0.6 where all nodes are invisible in the scene view except for the selected node.

objectlocation

### PR DESCRIPTION
**Pull request by groud**
Draw the selected 2D node outline on top of everything else. 
Closes #27315

### CODE REVIEW

**Comment by akien-mga** [comment]
Do you have a before/after screenshot on a case where this makes a big difference?

**Comment by groud** [comment]
With same node selected:
before:
before

after:
after

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
