### PR TITLE
Massive improvemnts to shadows quality/flexibility

### PR DESCRIPTION
**Pull request by jay3d**
Significant changes to how PCF shadows work, made them took less samples with higher quality results, also added more flexible control of the filtering radius in the editor.

### CODE REVIEW

**Comment by reduz** [comment]
Nice, will review soon, as this will have to be merged to the gles3 branch

**Comment by ScotFlux** [comment]
Spectacular. You've just got Godot 🏆 Congratulations! 👍

**Comment by khairul169** [comment]
Nice catch! :D

**Comment by akien-mga** [comment]
@jay3d Would you mind redoing this PR against the `2.1` branch? We'd gladly merge it to include this in the future 2.1.3-stable release.

For master/3.0, it would have to be implemented differently, but @reduz would likely use this PR as a reference.

**Comment by Zireael07** [comment]
This would be awesome to see, poke @jay3d

**Comment by n-pigeon** [comment]
This is so cool!

**Comment by akien-mga** [comment]
Bump :) I would still consider merging this in the 2.1 branch if rebased and/or having a new PR for the master branch, if relevant with the gles3 rasterizer.

**Comment by akien-mga** [comment]
Closing as it can't be merged in master at any rate, but if someone wants to try to port this to the 2.1 branch, it would be quite interesting.

**Comment by Calinou** [comment]
I had a try at porting this to the `master` branch with GLES3, but unfortunately, there's a noticeable dithering pattern:

image

I could confirm this by running the branch from this pull request (based on Godot 2.1):

image

Both screenshots were taken with the "High" shadow filter quality; the shadow filter radius was set to 1.5.

**Pull request closed without merging**
