### PR TITLE
Use Filament specular model and parametrization 

### LINKED ISSUE #22637: "Force Blinn over GGX" option not useful anymore
The optimized GGX merged in #22483 is faster than Blinn (which uses exp2 and pow), so this option should be removed, or at least should be disabled by default in GLES2.

An alternative and useful option would be to force low-quality approximation for GGX over the usual one.

### PR DESCRIPTION
**Pull request by clayjohn**
Implements: https://github.com/godotengine/godot-proposals/issues/3117
Closes: https://github.com/godotengine/godot/issues/22637
Supersedes: https://github.com/godotengine/godot/pull/52909 

This PR improves our specular models by using the functions and parametrization from Google's filament renderer. Particularly, this makes the Schlick_GGX specular mode more efficient, it improves the quality and efficiency of both the clear coat model and the anisotropic model. Finally, this PR adds both clearcoat and anisotropy to IBL light sources, and adds anisotropy to Reflection Probes. 
_Before: (Note the lack of sky reflection on the left, and the fact that the sky reflection is isotropic on the right_
Screenshot (263)

_After:_
Screenshot (262)

### CODE REVIEW

**Comment by Chaosus** [comment]
https://github.com/godotengine/godot/blob/3e7a545ecf9194891ef0fd774159ddfa4cebf5f6/servers/rendering/renderer_rd/shaders/scene_forward_mobile.glsl#L500 I think this should be changed SPECULAR_SIMPLE_GGX

**Comment by Chaosus** [comment]
https://github.com/godotengine/godot/blob/3e7a545ecf9194891ef0fd774159ddfa4cebf5f6/servers/rendering/renderer_rd/shaders/scene_forward_mobile.glsl#L498

Ah and the comment line too

**Comment by clayjohn** [comment]
@Chaosus good thinking. This raises another problem we have with the mobile renderer. If we change the default mode to ``Specular_schlick_ggx`` then it will default to simple GGX even if the ``use_simple_ggx`` option is not selected. 

I guess to fix that, ``USE_SIMPLE_GGX`` should be defined in addition to ``SPECULAR_SCHLICK_GGX``. So instead of adding a new specular mode, the project setting will just insert an extra define. 

I will update the PR accordingly.

**Review by reduz — APPROVED** [review]

**Comment by clayjohn** [comment]
Update, this PR has been overhauled and is now ready for review. The original descriptions has been updated with new contents.

**Comment by reduz** [comment]
Looks fantastic!

**Comment by clayjohn** [comment]
Rebased on master! This PR should be good to merge once CI passes.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
