### PR TITLE
Fix changing the import type of multiple files at once

### LINKED ISSUE #36976: Atlas reimport procedure does not create atlas file
**Godot version:**
3.2.1.stable

**OS/device including version:**
Ubuntu 19.10

**Issue description:**
Reproducing the procedure described in the image of @reduz' news post here : https://godotengine.org/article/atlas-support-returns-godot-3-2

Does not seem to create the atlas file.

**Steps to reproduce:**
- Create a project
- Add image files into a folder of the project (eg. Kenney tileset)
- Select images in Filesystem dock
- In Import tab, choose TextureAtlas
- Set a filename and a mode
- Click on Reimport button
- Validate in popup
<editor restarts>
- Confirm that the atlas filename that was supposed to be created is not there

**Minimal reproduction project:**
N/A

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #36976.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by firecloud888** [comment]
I came from here: https://github.com/godotengine/godot/issues/36976
Seems the problem still exist on stable 3.2.1, I don't know why merge and close the problem, the atlas still can not be created
It must be a bug. I try the godot 3.2 beta 6 and it solve my problem
https://godotengine.org/article/dev-snapshot-godot-3-2-beta-6

**Comment by akien-mga** [comment]
As you can read in the previous comment, this fix was merged and cherry-picked (included) in Godot 3.2.2. So it's expected that you still experience the bug in 3.2.1, which predates 3.2.2. Try 3.2.2-beta2: https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-2

**Comment by firecloud888** [comment]
Really Appreciate! That will helps a lot

**Pull request merged**
