### PR TITLE
Added RigidBody and finished Resource class-reference

### PR DESCRIPTION
**Pull request by J08nY**
Added RigidBody and finished Resource class-reference. Also synced with the current git master documentation template.

### CODE REVIEW

**Comment by neikeq** [comment]
Apparently the commit(s) are not being attributed to your Github account. The reason may be that your git configuration uses a different e-mail address to your Github account. [Read this article](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/) for more information.

However, that does not prevent from merging this Pull Request.

**Comment by J08nY** [comment]
Yep, noticed just a few seconds after commiting. Fixed it now :)

**Comment by bojidar-bg** [comment]
Please rebase the merge commit out, since it doesn't add any value.

**Comment by J08nY** [comment]
Ah, as you can see I'm not so natural with git. Lets just nuke this PR, I will do another one tomorrow when I have time to fix my repo/commits.

**Comment by slapin** [comment]
I think you can just remake this PR as many times as necessary, so no need
to create another one.

**Comment by J08nY** [comment]
Commits now fixed.

**Pull request merged**
