### PR TITLE
Rename the editor action "Revert Scene" to "Reload Saved Scene"

### PR DESCRIPTION
**Pull request by Calinou**
This option can be used to workaround various issues with stuff not reloading properly when changes are made (such as #30302).

The option was renamed to clarify the fact that it actually reloads the scene saved on the filesystem.

## Preview

Reload Saved Scene confirmation dialog

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't think it's useful to have a shortcut for this, and making it hard to trigger accidentally also makes it hard to trigger at all (4 keys!). I'd leave it without shortcut, if some users really want one, they can assign it themselves.

**Comment by Calinou** [comment]
@akien-mga I removed the default shortcut binding but kept the action name change.

**Review by akien-mga — APPROVED** [review]

**Comment by Anutrix** [comment]
"Reload scene from disk" is also what I usually see for such action on some softwares.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
