### PR TITLE
baked light baker : improves randomness

### PR DESCRIPTION
**Pull request by SuperUserNameMan**
**edit :** as mentioned into #6682, Reduz said on IRC that he will rewrite the baker for 3.x.
- For the time being, this PR can be merged as is into custom 2.x version to fixes the multi-threaded baking bug and to standardize the baking quality and accuracy among platforms (`rand()` implementation is not standardized and not multi-thread safe).
- Other than that, this PR can also be used to evaluate the actual influence of different PRNG over the quality and the speed of the baking process. If you find that a PRNG gives better or worst results than others, please, share your findings with us.

---

see #6682

replace `rand()` by a thread-safe and thread-seeded RNG.

------ edit ----------

So I've put different algorithms that can be easily changed at compile time by defining one of these preprocessor variable :

```
BAKER_RNG_USE_C_RAND
BAKER_RNG_USE_XONOROSHI128PLUS
BAKER_RNG_USE_XORSHIFT128
BAKER_RNG_USE_XORSHIFTSTAR
BAKER_RNG_USE_XORSHIFTPLUS
BAKER_RNG_USE_MT19937
BAKER_RNG_USE_CXX11_MT19937
BAKER_RNG_USE_XORSHIFT32
```

Some are more optimized for 64bits, some others for 32bits.
Some are more optimized for MSVC, some others for GCC.
Some have relatively low periodicity, some others relatively higher one.

Default is set to BAKER_RNG_USE_MT19937.

note : 
- BAKER_RNG_USE_C_RAND is the default `rand()`.
  It is guaranteed to be multithread-safe only with MSVC.
  It is slightly faster than others RNG, but it has a RAND_MAX of only 0x7FFF, is based on an unknown underlying algorithm with an unknown periodicity.
- BAKER_RNG_USE_CXX11_MT19937 is the standard C++11 std::mt19937.
  It is still experimental on GCC 4.6.3, and is fully supported by MSVC.

### CODE REVIEW

**Comment by SuperUserNameMan** [comment]
so according to Travis, gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3 does not have ``std::mt19937``.
I will have to find an alternative, maybe the [RNG](http://www.pcg-random.org/download.html) that @est31 proposed on IRC.

**Comment by SuperUserNameMan** [comment]
i misread the travis log last time ...
in fact, with gcc 4.6, ``#include <random>`` is still experimental ...

``
In file included from /usr/include/c++/4.6/random:35:0
...
 error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.``

So, the RNG just needs to be replaced.

**Comment by SuperUserNameMan** [comment]
will try with public domain  http://xoroshiro.di.unimi.it/xoroshiro128plus.c

**Comment by djrm** [comment]
@SuperUserNameMan if you are looking for a fast, high quality PRNG you should check the ziggurat method, it is faster than Mersenne Twister and gives similar results

**Comment by SuperUserNameMan** [comment]
So I've put different algorithms that can be easily changed at compile time by defining one of these preprocessor variable :
````
BAKER_RNG_USE_C_RAND
BAKER_RNG_USE_XONOROSHI128PLUS
BAKER_RNG_USE_XORSHIFT128
BAKER_RNG_USE_XORSHIFTSTAR
BAKER_RNG_USE_XORSHIFTPLUS
BAKER_RNG_USE_MT19937
````

Some are more optimized for 64bits, some others for 32bits.
Some are more optimized for MSVC, some others for GCC.
Some have relatively low periodicity, some others relatively higher one.
Default is set to BAKER_RNG_USE_MT19937.

BAKER_RNG_USE_C_RAND is the default ``rand()``.
It is guaranteed to be multithread-safe only with MSVC.
It is slightly faster than others RNG, but it has a RAND_MAX of only 0x7FFF, is based on an unknown underlying algorithm with an unknown periodicity.


@djrm : thanks. I have not test ziggurat yet. I found a public domain implementation, but had too much difficulties trying to integrate it, so I gave up. Maybe I'll try again later.

**Comment by SuperUserNameMan** [comment]
i've added and tested BAKER_RNG_USE_XORSHIFT32

it has a periodicity of 2^32-1, and a RAND_MAX of 32bits


more info about this RNG here : http://excamera.com/sphinx/article-xorshift.html

**Comment by tagcup** [comment]
PCG family RNG fares better than xorshift in many aspects including speed (see [their website](http://www.pcg-random.org/)), and comes with many variants.

**Comment by SuperUserNameMan** [comment]
@tagcup :
``Math::rand_from_seed()`` uses a 32bit seed that also serve as state for the PRNG.

Xorshift32 works the same way with a 32bits seed/state, and allows to keep current Godot's ``Math::rand_from_seed()`` API.

On the other hand, the minimal [PCG C implementation](http://www.pcg-random.org/download.html) requires to store a 128 bits state.
It would require to write a new API for random number generators.

**Comment by tagcup** [comment]
@SuperUserNameMan
Can you clarify what you mean by "list"?
I also forgot to mention this but the period in PCG can be arbitrarily large.

**Comment by SuperUserNameMan** [comment]
@tagcup :

> Can you clarify what you mean by "list"?

I've put different PRNG into this PR so that people can test and benchmark the baked light baker with different PRNG.
Performance and quality of each PRNG can vary depending on platform and compiler.

By default, this is a 32bits MT19937 that is selected.
But it can be replaced at compile time by an other PRNG by defining one of the  ``BAKER_RNG_USE_xxxx``.

So, what i mean, is that i will add PGC to the list of these PRNG, into this PR.

**Comment by tagcup** [comment]
Thanks for the clarification! But I'm confused, why would Godot devs want every PRNG you can get your hands onto in the codebase with an ifdef? Users won't care about such low-level compiler flags. I think having one PRNG with good randomness and statistical properties (something both Mersenne Twister and XorShift and [fail at](http://www.pcg-random.org/statistical-tests.html)) is the better way go. PGC is [well studied](http://www.pcg-random.org/pdf/toms-oneill-pcg-family-v1.02.pdf) and is demonstrably better at every aspect than Mersenne twister and XorShift, and many others in all aspects.

**Comment by SuperUserNameMan** [comment]
Well, 

I forgot to mention that reduz said on IRC that he will rewrite the Baker for 3.x, and that this PR for the 2.x baker is thus mainly experimental.
( However, if you want to use it to fix the multi-thread bug of the current version of the baker, you can use it. the default PRNG will be MT19937 )

And to answer your question about "why so many PRNG etc etc" : 

At the beginning I only wanted to replace the defatul C ``rand()`` by the standard C++11 ``std::mt199937``. but it is not available in gcc 4.6.3 (which is apparently the minimum required to compile godot).

So I've started looking for alternatives, and several other persons told me "try this PRNG ! it is faster than this and that !" .... "no ! try this one instead !! it is faster !" ... 
Then I've started trying them all, and made some benchmarks and visual comparison.

Like I said, some of this PRNG will be more optimized for 64 bits CPU, and some others for 32 bits CPU, and some will be better optimized by MSVC compilers, some other by GCC, some other by MinGW etc....

So, instead of arbitrary picking a single one, I told to myself : _"Maybe, if I put them all, this will allow other curious users to make their own benchmarks on their own OS, with their own compilers, and see by themself which PRNG is actually the best ; and maybe some of them will even share their benchmarks and visual comparison results ; this way, the best PRNG could be automatically selected into scons for each platform and compiler. And if someone popup with a PRNG that we have not yet benchmarked and evaluated and tell me "this one is better !", then I will add it to the PR so that others peoples will be able to test and benchmark it if they want."_

Indeed, as I was not sure that many people would be interested about benchmarking so many PRNG, I've decided to make the MT199937 default, and to keep the others just in case someone would popup with a _"why don't you use this PRNG instead ? it is faster than XXXX !"_.

When reduz will rewrite the 3.x baker, he will decides himself whatever PRNG he want, and if he does not know which one to pick, i will just tell him _"why don't you use this PRND instead ? it is faster than XXXX !"_.

I hope this long blabla helped you to feel less confused. ^^

**Comment by tagcup** [comment]
Ah, I see.

Just for the clarification though, I'm mainly trying to point out that [research](http://www.pcg-random.org/pdf/toms-oneill-pcg-family-v1.02.pdf) shows that PCG has good randomness that pass the standard tests for randomness. Good speed while being a good PRNG is an added bonus with PCG ;)

But then, now that 2.2 is abandoned, doesn't this mean this PR won't make into any stable release?

**Comment by SuperUserNameMan** [comment]
> Just for the clarification though, I'm mainly trying to point out that research shows that PCG has good randomness that pass the standard tests for randomness. Good speed while being a good PRNG is an added bonus with PCG ;)

Yes, so, in the end, maybe PCG will be set to default for the baker.

> But then, now that 2.2 is abandoned, doesn't this mean this PR won't make into any stable release?

You are absolutely correct !

But it can make into any custom build, since it fixes the multi-thread baking bug. ( standard C ``rand()`` is not guaranteed to be multi-thread safe, and on MSVC compiled godot, each threads were throwing the exact same random rays ... )
And also it is a way to leave a trace of my experiments to reduz for when he will rewrite the baker.

**Comment by akien-mga** [comment]
Is this still relevant now that the light baker has been replaced by GI Probes? I guess there might still be some need for good randomness, but I don't know what is being used now.

**Comment by tagcup** [comment]
I'd be happy to submit a PR for PCG to replace the RNG overall.

**Comment by reduz** [comment]
Light baker is gone, so this is not relevant i guess?

**Comment by SuperUserNameMan** [comment]
@reduz : yep it can RIP

**Pull request closed without merging**
