### PR TITLE
clipper2: Update to 1.4.0

### PR DESCRIPTION
**Pull request by Chubercik**
https://github.com/AngusJohnson/Clipper2/releases/tag/Clipper2_1.4.0

- Updated `COPYRIGHT.txt`
- Regenerated `patches`

cc @smix8

### CODE REVIEW

**Comment by Chubercik** [comment]
Uh-oh: https://github.com/llvm/llvm-project/issues/16778

**Review by akien-mga — APPROVED** [review]
Seems good to me, if it works :D 

Needs rebase to remove the merge commit.

**Comment by Chubercik** [comment]
Rebased :)

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
