### PR TITLE
Add more property capitalizations

### PR DESCRIPTION
**Pull request by fire-forge**
Add property name capitalizations for:
- BiDi
- FileSystem
- NavMesh

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs a rebase.

**Comment by fire-forge** [comment]
@akien-mga I rebased it.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
