### PR TITLE
Avoid unnecessary changes in .tscn files when saving AnimationSprite3D/2D with playing property enabled.

### PR DESCRIPTION
**Pull request by oikpanagiotis**
The relevant issue can be found here: #53407 (comment)

This PR changes the animatedsprite2d/3ds frame to 0 when saving the scene with the playing property enabled to avoid creating unnecessary diffs on tscn files.

### CODE REVIEW

**Comment by Goutte** [comment]
Thank you!

Event though this is technically a BC break, it feels more like a bugfix.
I can't fathom a use-case where I want to save a different `frame` every time I `CTRL+S` a scene.

I hope this will get merged and cherry-picked for the  `3.x` branch.

**Comment by ztc0611** [comment]
Any chance of this getting cherrypicked for 3.5?

**Comment by rcorre** [comment]
Would it be simpler to just remove `PROPERTY_HINT_STORAGE` from the `frame` property? The following patch solves https://github.com/godotengine/godot/issues/53407 for me:

```diff
diff --git a/scene/3d/sprite_3d.cpp b/scene/3d/sprite_3d.cpp
index 514bd4aba0..3cc192daf7 100644
--- a/scene/3d/sprite_3d.cpp
+++ b/scene/3d/sprite_3d.cpp
@@ -1230,7 +1230,7 @@ void AnimatedSprite3D::_bind_methods() {
 
 	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "frames", PROPERTY_HINT_RESOURCE_TYPE, "SpriteFrames"), "set_sprite_frames", "get_sprite_frames");
 	ADD_PROPERTY(PropertyInfo(Variant::STRING, "animation"), "set_animation", "get_animation");
-	ADD_PROPERTY(PropertyInfo(Variant::INT, "frame"), "set_frame", "get_frame");
+	ADD_PROPERTY(PropertyInfo(Variant::INT, "frame", PROPERTY_HINT_NONE, "", PROPERTY_USAGE_EDITOR), "set_frame", "get_frame");
 	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "playing"), "_set_playing", "_is_playing");
 }
```

**Comment by ztc0611** [comment]
> Would it be simpler to just remove `PROPERTY_HINT_STORAGE` from the `frame` property? The following patch solves #53407 for me:

Does this stop it from saving frames at all? Because some people would want it to save a specific frame, assuming they didn't have "playing" on.

**Comment by rcorre** [comment]
> Does this stop it from saving frames at all

It would. I wasn't thinking of the case where someone wants to save a nonzero frame

**Comment by KoBeWi** [comment]
I'd go with @rcorre's solution, but do it conditionally, i.e. add `_validate_property()` and check if `playing` is enabled. When enabled, don't store the current frame.

**Comment by YuriSizov** [comment]
@oikpanagiotis Hey, do you plan to work on this? We'd like to have it, but it needs to be updated to follow the suggested solution.

**Comment by akien-mga** [comment]
Superseded by #65720.

**Pull request closed without merging**
