### PR TITLE
Add tile index prefixes in tile map editor plugin

### LINKED ISSUE #5420: Feature Request: Tile Index Visible In Editor
I would like to be able to see the tile index of a tile from the tilemap editor.
By tile index I mean the integer value I would use in the third argument of set_cell.
This should be an easy feature, but one i will find very useful.

### PR DESCRIPTION
**Pull request by samuelgrigolato**
Closes #5420.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Looks good to me :)

**Comment by akien-mga** [comment]
Should it be made optional? (genuine question, I don't have a strong opinion myself)

**Comment by bojidar-bg** [comment]
@akien-mga unless you have very long tile names, it shouldn't bother anybody IMO

**Comment by Hinsbart** [comment]
Most of the time I generate my tilesets by code, so the tiles would have names like "1: Tile 1" .
Making it optional would be neat in this case, but I can also live without it ;)

**Comment by bojidar-bg** [comment]
@Hinsbart ahh -- just change the scripts :P

**Pull request merged**
