### PR TITLE
[3.x] Prevents default values of VSNodeCustom from overriding by a script

### PR DESCRIPTION
**Pull request by Chaosus**
Backport of https://github.com/godotengine/godot/pull/47826

### CODE REVIEW

**Comment by Chaosus** [comment]
Oh, I hope I was not wrong with a branch @akien-mga?

**Comment by akien-mga** [comment]
It should be against the `3.x` branch, the `3.2` branch is read-only and won't get new changes.

**Comment by akien-mga** [comment]
We're at 3.3 RC 8 already so I'll probably hold off merging this for now, we can merge once 3.3 is released, and cherry-pick for 3.3.1. Unless you're 100% confident about this change.

**Comment by Chaosus** [comment]
Alright, it's not a critical bug so left it for 3.3.1

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
