### PR TITLE
Prevent nested packedArray from being casted to generic Arrays

### LINKED ISSUE #76113: nested Packed Arrays serialize as a generic Array once a value inside is edited
### Godot version

4.1.dev (a7276f1ce0)

### System information

MacOS 13.3 M1 Pro

### Issue description

This issue was found by @don-tnowe while testing #76078
When nesting a Packed Array in an Array or a Dictionary and then updating one of the element of the Packed array, the packed Array will be recasted to an untyped Array. 

### Steps to reproduce

1. export an Array or dictionary 
2. create an item in your `Array`/`Dictionary` with a `PackedArray` setup
3. add an item to the `PackedArray` and modify it
4. refresh the `EditorProprety` of your `Array`/`Dict` by closing it and reopening it 
5. see that now your `PackedArray` is an `Array`

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ajreckof**
Fixes #76113

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by YuriSizov** [comment]
Does this still work correctly with regular and typed arrays?

**Comment by ajreckof** [comment]
Yes this change only remove a forced cast from packed arrays to array

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
> Does this still work correctly with regular and typed arrays?

It doesn't work with typed arrays.

**Pull request merged**
