### PR TITLE
StringName: Fix empty hash

### LINKED ISSUE #77894: Invalid get index of type StringName on base Dictionary when key is an empty StringName
### Godot version

4.0.3 stable

### System information

Kubuntu 22.04

### Issue description

I have a dictionary with string keys, and one of the keys is "" (empty string). To get values from dictionary by the key, the StringName parameter is used. So all works fine unless the key is an empty StringName.
Context: dictionary stores some data about input actions, that are type of StringName (and certain Input and InputEvent methods expects StringName arguments), that's why this type is prefered rather than String. And one of the dictionary elements is kinda nil-element, used to eliminate `if _dict.has(key)` checks.

### Steps to reproduce

1) Make *.gd script
2) Add a Dictionary variable, e.g. `var _dict:={}`
3) Add some value with empty key `_dict[&""]=someval` or `_dict[""]=someval`
4) Try to get this value like `print(_dict[&""])`

### Minimal reproduction project

Example declaration:
```gdscript
class_name Something extends Node

var _dict:={&"":"--emptyness--",&"a":"A"}

func get_val_by_strname(key:StringName):
   return _dict[key]

func get_val_by_strname_converted(key:StringName):
   return _dict[key as String]

func get_val_by_str(key:String):
   return _dict[key]
```
Example usage:
```gdscript
print(Something.get_val_by_str("A"))  #Will print "A".
print(Something.get_val_by_strname_converted(&"A"))  #Will print "A".
print(Something.get_val_by_strname(&"A"))  #Will print "A".

print(Something.get_val_by_str(""))  #Will print "--emptyness--".
print(Something.get_val_by_strname_converted(&""))  #Will print "--emptyness--".
print(Something.get_val_by_strname(&""))  #Will throw an error "Invalid get index of type StringName on base Dictionary".

```

### LINKED ISSUE #96553: Animation lost when opening projects created in 4.3
### Tested versions

- Reproducible: master[e2dd56bea7a1aa13fe74fd6eac049e4cbde0434c]
- Not reproducible: 4.4.dev1

### System information

Arch Linux

### Issue description

When opening a project created in 4.3, animations in AnimationPlayers are lost with this error:

```
ERROR: Condition "p_animation_library.is_null()" is true. Returning: ERR_INVALID_PARAMETER
   at: add_animation_library (scene/animation/animation_mixer.cpp:281)
```

Probably an regression from #70096

### Steps to reproduce

- Create a project in 4.3, add an AnimationPlayer in the scene and create a new Animation in it.
- Open the project with an editor built from master.

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/16862562/test.zip)

### PR DESCRIPTION
**Pull request by rune-scape**
fixes https://github.com/godotengine/godot/issues/96553
fixes https://github.com/godotengine/godot/issues/77894

fixes the underlying issue that an empty String hashes different than an empty StringName
and the default animation library is an empty string
so when the String key is converted to a StringName, it hashes differently and misses the entry in the hashmap

possibly solves other unknown bugs related to the new StringName Dictionaries

### CODE REVIEW

**Comment by akien-mga** [comment]
This seems to make the C# glue generation fail for some reason: https://github.com/godotengine/godot/actions/runs/10713374687/job/29705303641?pr=96586

CC @raulsntos

**Comment by AThousandShips** [comment]
I think it breaks the general method hashes for compatibility it's just that the C# check runs before the API check, it probably breaks the hash for methods with `""` default arguments

**Comment by dsnopek** [comment]
> I think it breaks the general method hashes for compatibility it's just that the C# check runs before the API check, it probably breaks the hash for methods with `StringName()` default arguments

That sounds likely.

It'd be great to see how many method hashes this changes. The last time we made a change to hashing, we ended up making `gdextension_compat_hashes.cpp` to avoid adding a ton of compatibility methods, so adding to that is an option, although, if the number is really small doing compatibility methods might be better since that's the normal way to do it (whereas the other was an exceptional case).

**Comment by raulsntos** [comment]
I think you are both correct. The C# bindings generator seems to be getting confused about the method hashes and generating invalid C# that doesn't compile. For example, for the `Object::tr` method, this is what's in the GDExtension API dump:

```json
"name": "tr",
"is_const": true,
"is_vararg": false,
"is_static": false,
"is_virtual": false,
"hash": 1195764410,
"hash_compatibility": [
    1195764410,
    2475554935
],
```

As you can see, the current hash matches one of the compatibility hashes, which is why the C# bindings generator gets confused and tries to generate the method twice.

For your convenience, I'll upload the GDExtension API dump generated from before and after the commit in this PR:

- [extension_api.old.json](https://github.com/user-attachments/files/16901375/extension_api.old.json) (from commit b6223c0df0300ba2db17b5742c349f13c33f8884)
- [extension_api.new.json](https://github.com/user-attachments/files/16901356/extension_api.new.json) (from commit 94631ef648db8fe2baefb55f33b70f6b95ee48b0)

Also, I wonder if the hash for an empty `String` should match the hash for an empty `StringName` since they are different types. I would not necessarily expect the hashes to match. And the linked issue seems to be closed already, so is this change still needed?

**Comment by rune-scape** [comment]
`dict[StringName()]` (and also `dict.get(StringName())` before https://github.com/godotengine/godot/pull/70096 was merged) will use a StringName hash to lookup a String key and not find the equivalent value so this discrepancy affects (in a small way) at least Dictionary for all of 4.0 (and i seemed to have assumed it in e79be6ce07ed8c89011f759ecade070a3bd5a806, oops). it at least seems intuitive that empty String and StringName hash the same given how similar the usage and APIs are and how every other hash is the same

it seems possible to automate detecting empty StringName default parameters and tweaking the compat hashes and such, but im not familiar with how the system works or what those things mean

66 hash changes

**Comment by dsnopek** [comment]
> 66 hash changes

That's probably enough that these should be added to `gdextension_compatibility_hash.cpp`.

It's fairly simple to do, although quite tedious. Here's an example mapping for a class:

```
	mappings.insert("AESContext", {
		{ "start", 3167574919, 3122411423 },
	});
```

So, you give the name of the function, the old hash (before the hashing change) and the new hash.

The only tricky part is if the function is already listed there, you'll need to update the older mapping too. That's because the mappings don't "chain together", like, you can't map from an old hash to another old hash, because Godot won't recursively look them up, you always need to map all the way to a hash that really exists in `ClassDB` (although, that does include hashes for normal compatibility methods, which is why we don't need to constantly update this file).

**Comment by dsnopek** [comment]
@raulsntos:

> Also, I wonder if the hash for an empty `String` should match the hash for an empty `StringName` since they are different types. I would not necessarily expect the hashes to match.

This is a good question!

However, I think in the case of default arguments, it's probably harmless for them to match. So long as the hashing of the argument types is distinct (which I think it still is), we should be good.

That said, I'm only thinking about GDExtension compatibility, I don't know if this could have an effect on other things in the engine where we'd want `String`s and `StringName`s to hash differently?

> As you can see, the current hash matches one of the compatibility hashes, which is why the C# bindings generator gets confused and tries to generate the method twice.

I think `Object::tr()` and `Object::tr_n()` is a special case. In PR https://github.com/godotengine/godot/pull/84906, you fixed these previously having a default of `StringName()` when the argument was really `String` and added compatibility methods. With the changes here, we should probably remove those compatibility methods (then in `gdextension_compatibility_hashes.cpp` add mappings that go in the other direction).

**Comment by rune-scape** [comment]
i had to add an unexpected extra hash for `AnimationPlayer::play` that wasn't there before, but other than that ive carefully added and swapped all the necessary hashes and it seems happy :)

and removed compatibility methods for methods previously having a default arg of String() when the param type was StringName

default parameters of Callable() were also affected btw (because of the hash of empty `method`)

**Review by dsnopek — APPROVED** [review]
From the perspective of GDExtension compatibility, this looks good to me! I didn't evaluate its potential impact on anything else.

**Review by raulsntos — APPROVED** [review]
I found no issues regarding C# compatibility either.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
