### PR TITLE
Fix #18026. Expose TextEdit::set_draw_breakpoint_gutter.

### LINKED ISSUE #18026: TextEdit (Node, not IDE) breakpoints not working, no breakpoint gutter
**Godot version:** 3.0.2 stable

**OS/device including version:** Ubuntu 17.10

**Issue description:**
Acording to http://docs.godotengine.org/en/latest/classes/class_textedit.html?highlight=textedit#signals :
  - **breakpoint_toggled ( int row )**: Emitted when a breakpoint is placed via the breakpoint gutter.

But the textedit node doesn't even seem to have a breakpoint gutter (it's enabled on the IDE but not on the node, or I can't seem to find its toggle). 

**Steps to reproduce:**
 - Create new project, new scene, new TextEdit node with __layout > full rect__ so you can try to place a breakpoint.
 - Add the following script to the node: 
```javascript
extends TextEdit
func _ready():
	show_line_numbers = true
	text = "Lore\nipsum"
	connect("breakpoint_toggled", self, "it_works")
func it_works(row):
	# Never called
	print("It works! Row: %d" % row )
```
 - Run, and try to place a breakpoint.

**Minimal reproduction project:** [issuedemo.zip](https://github.com/godotengine/godot/files/1884485/issuedemo.zip)

### PR DESCRIPTION
**Pull request by gabrii**

### CODE REVIEW

**Comment by Noshyaar** [comment]
Should we rename it to `set_drawing_breakpoint_gutter` so that it's consistent with `is_drawing_...`?

**Comment by gabrii** [comment]
I'm not even fond of "draw" instead of "enabled": **set_breakpoint_gutter_enabled / is_breakpoint_gutter_enabled**, this way there isn't the mess with verbs, and maybe the propery for the IDE could be just "breakpoint_gutter", instead of "draw_breakpoint_gutter".

But I don't have a c++ IDE on hand yet to refactor the methods so it matches the property name in case we want to change it, I might set up the IDE today :crossed_fingers:

**Comment by Noshyaar** [comment]
Agreed. Removing 'draw' would be better, but also a compatibility-breaking change.

**Comment by gabrii** [comment]
Would it? From the godot user (not developer) point of view, it wouldn't break compatibility, as it's a new property rather than renaming an existing one (or am I missing something? I'm new to godot developent, I got into this to overcome the limitations I find while using it).

I'll push it with set_drawing_breakpoint_gutter if we have to consider the c++ compatibility, no problem.

**Comment by gabrii** [comment]
I've renamed it, but now the exposed method is not consistent with the source method. At this point we could rename it to expose it as set_breakpoint_gutter_enabled / is_breakpoint_gutter_enabled / breakpoint_gutter, and leave the refactoring of the source for later if it's a compatibility problem.

Whatever you find more appropiate. Thanks

**Comment by reduz** [comment]
What's the status for this?

**Comment by gabrii** [comment]
The PR is fine, although after developing an application which uses breakpoints I found other problems:
 - No way to get list of all breakpoints
 - No way to remove all breakpoints
 - Signal breakpoint_toggled not triggered when new lines are inserted before a breakpoint and it gets moved to the next line.

I think it's better to not merge this, as it would imply that the breakpoints and its surrounding functionalities work fine, when most of them are missing.

**Comment by mhilbrunner** [comment]
@gabrii That means we should fix those problems too (probably in separate issues/PRs) instead of giving up and not improving the current state, though, doesn't it?

If you'd like to, please open issues for those.

And I'd prefer `set_breakpoint_gutter_enabled / is_breakpoint_gutter_enabled / breakpoint_gutter`. @Noshyaar?

**Comment by Noshyaar** [comment]
For some reason I thought one of the methods was already implemented and it was going to be renamed. Nevermind then.

**Comment by mhilbrunner** [comment]
@gabrii Are you interested in implementing the rest?

**Comment by gabrii** [comment]
@mhilbrunner Yes, I have a WIP. I'll finish it and push sometime this week. (I'll put it on this PR, as it's not testable without being able to enable the breakpoints gutter)

**Comment by gabrii** [comment]
Here is a testing scene, which compares the breakpoints according to _breakpoint_toggled_ signals with the actual breakpoints from _get_breakpoints_: [breakpoint_tests.zip](https://github.com/godotengine/godot/files/2051432/breakpoint_tests.zip)
Open it, place some breakpoints, an verify that after any text insertion or removal the last printed status is "OK":
```    OK  1. Line 1 (False)->(True): [1] ~ SAME
    OK  2. Line 2 (False)->(True): [1, 2] ~ SAME
 WRONG  3. Line 2 (True)->(False): [1, 3] ~ [1]
    OK  4. Line 3 (False)->(True): [1, 3] ~ SAME
 WRONG  5. Line 3 (True)->(False): [1, 4] ~ [1]
    OK  6. Line 4 (False)->(True): [1, 4] ~ SAME
 WRONG  7. Line 1 (True)->(False): [2, 5] ~ [4]
 WRONG  8. Line 2 (False)->(True): [2, 5] ~ [2, 4]
 WRONG  9. Line 4 (True)->(False): [2, 5] ~ [2]
    OK 10. Line 5 (False)->(True): [2, 5] ~ SAME
    OK 11. Line 1 (False)->(True): [1, 2, 5] ~ SAME
```
It seams to work for all the cases I can think of.

**Comment by akien-mga** [comment]
Could you squash the commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase)

**Comment by akien-mga** [comment]
See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind for tips on writing a good commit log. The important part is to keep the first line short and to the point, but descriptive enough at the same time, and keep the details in the main description of the commit log, e.g.:
```
Improve breakpoints and breakpoint gutter API in TextEdit

<Details go here>.
Fixes #18026.
```

**Comment by gabrii** [comment]
@akien-mga Thanks a lot for the version control and C++ lessons, I'll pay back collaborating more.

**Comment by mhilbrunner** [comment]
Thank you :)

**Pull request merged**
