### PR TITLE
Stop popup release timeout on click.

### LINKED ISSUE #95430: Popups don't register mouse click shortly after opening
### Tested versions

Reproducible in: 4.3.rc [86c95d26fcad39b2a97a951237c8183ab2c90f50]
Reproducible in: 4.3.rc [5e7592a342ada6d170c9b5f079b7ac4551c16388]
Not reproducible in: 4.3.rc [031b71f5bc8bd41d1318d81191076fbb696f46d7]

### System information

Windows 11 (10.0.22631)

### Issue description

This seems to be a regression between 4.3-RC2 and 4.3-RC3, stemming from #95232.

When opening pretty much any popup in Godot, like the window top menu, or a context menu, and then releasing the mouse button and clicking somewhere in the popup within a short timeframe (presumably 400 ms) that second mouse click doesn't seem to register.

https://github.com/user-attachments/assets/59f59484-565f-4bfc-a9c0-d1973c568a0e

https://github.com/user-attachments/assets/703bc177-c29a-4497-b7e0-2db1a980535e

Lowering the timeout changed in #95232 back to 150 ms seems to resolve the regression.

### Steps to reproduce

1. Open the editor
2. Click one of the items in the top window menu
3. Quickly click the first item in the menu
4. Note how the click doesn't register

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Should fix https://github.com/godotengine/godot/issues/95430, need to be tested on all desktop platforms.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @mihe

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected on:

Godot v4.3.rc (39fc116c5) - Fedora Linux 40 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 555.58.02) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

Single-window mode is disabled in the editor settings.

On the other hand, I can't reproduce the [original issue](https://github.com/godotengine/godot/issues/95430), but at least there's no regression in behavior.

**Comment by mihe** [comment]
I can confirm that this fixes the issue on Windows. I'll give macOS and Linux a try as well.

**Comment by mihe** [comment]
Interestingly I am/was able to reproduce this issue on both Windows and macOS, but not Linux.

All platforms seemingly work fine with this PR, but I must admit I don't know what kind of regressions to look out for.

**Review by KoBeWi — APPROVED** [review]
I can reproduce the bug and confirm that this fixes it.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
