### PR TITLE
Fix typo bug in convex-convex separating axis test

### LINKED ISSUE #75734: RigidBody3D in Convex Shape will sometimes pass through each other.
### Godot version

4.0.2

### System information

Windows10, Vulkan, amd6700xt

### Issue description

az

### Steps to reproduce

Run the project below.
Keep in mind that I'm using a custom Convex Shape, not Box Shape.

### Minimal reproduction project

[bugs2.zip](https://github.com/godotengine/godot/files/11166484/bugs2.zip)

### PR DESCRIPTION
**Pull request by rburing**
Fix typo introduced by https://github.com/godotengine/godot/pull/51355.

- Fixes https://github.com/godotengine/godot/issues/75734

### CODE REVIEW

**Review by fabriceci — APPROVED** [review]
LGTM, It's not necessary, and not the most useful case, but if you want, you can add a unit test (as a good practice).

**Review by lawnjelly — APPROVED** [review]
Good catch, looks like copypasta bug. I will check whether this is needed in 3.x too. :+1: 

EDIT: Nope, no bug in 3.x, so must have crept in when copying to make the 4.x version. My excuse, I have a cataract in one eye.. :smiley:

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
