### PR TITLE
FBX Importer: Support `Limb` class tag

### PR DESCRIPTION
**Pull request by W4RH4WK**
ref #47184

### CODE REVIEW

**Comment by RevoluPowered** [comment]
I need an example file with the "Limb" data in it, to test this, and make sure the relationships are correct. 

I will convert it to ASCII to be sure this is the correct fix, the data could be unrelated in some ways, or it could be legacy exporters dumping old formats of the file which in that case this fix is correct but right now we don't know for certain.

So let's put a test plan together for any changes for the FBX Importer in future because we merge something it could knock 10 other files out.

**Comment by W4RH4WK** [comment]
> I need an example file with the "Limb" data in it, to test this, and to make sure the relationships are correct.

Example provided by author of #47184.

> So let's put a test plan together for any changes for the FBX Importer in future because we merge something it could knock 10 other files out.

A form of test suit would certainly be helpful.

**Comment by RevoluPowered** [comment]
> > I need an example file with the "Limb" data in it, to test this, and to make sure the relationships are correct.
> 
> Example provided by author of #47184.
> 
> > So let's put a test plan together for any changes for the FBX Importer in future because we merge something it could knock 10 other files out.
> 
> A form of test suit would certainly be helpful.

Cool I will gist/pastebin the file he posted and grab a file without it, so we can compare, see if it's a version thing. I think maybe at some point would be good to write some script to convert them to debug things without having to grab Maya.

I'd honestly like to rewrite a lot of the FBX Parser soon, there are so many problems we inherited with the poor memory management which has also been a burden, I think next week this can be started too.

**Comment by W4RH4WK** [comment]
Doesn't Assimp provide such functionality out of the box. I seem to recall it ships with a command-line utility and a viewer.

**Comment by RevoluPowered** [comment]
> Doesn't Assimp provide such functionality out of the box? I seem to recall it ships with a command-line utility and a viewer.

its not really giving you a JSON dump of an fbx it's a dump of what it believes is in the fbx so it means a parser bug will drop data or crash and still give you nothing, with maya you can just dump the content of the fbx to ascii to make this 10x easier basically

**Comment by W4RH4WK** [comment]
Following [a stackoverflow post](https://stackoverflow.com/a/66319297), I found this, which seems helpful: https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_cpp_ref_import_scene_2main_8cxx_example_html.

**Comment by akien-mga** [comment]
Superseded by #59691 and #59653.

**Pull request closed without merging**
