### PR TITLE
Assorted cherry-picks from the master branch for Godot 3.0.7

### PR DESCRIPTION
**Pull request by akien-mga**
For review by @hpvb to see if any of those commits should not have been cherry-picked (e.g. breaks compat, or could introduce regressions).

### CODE REVIEW

**Comment by akien-mga** [comment]
As a reminder, a tedious but functional way to get back to the original PR for each of those commits for context is:
- Click on the commit in the above list:
Screenshot_20190703_175354
- Click on the original commit hash in the "cherry picked from commit blabla" message:
Screenshot_20190703_175232
- Click on the PR link next to `master`:
Screenshot_20190703_175317

**Comment by akien-mga** [comment]
Another option to review these PRs is to check all PRs updated today or later with the "Cherry-picked for 3.0.7." string (I always use the same.): https://github.com/godotengine/godot/pulls?utf8=%E2%9C%93&q=is%3Apr+%22Cherry-picked+for+3.0.7.%22+is%3Aclosed+updated%3A%3E%3D2019-07-03+

And PRs which had the `cherrypick:3.0` label but which I decided not to backport have a comment starting with "Now that Godot 3.1 has been released,", so: https://github.com/godotengine/godot/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+%22Now+that+Godot+3.1+has+been+released%2C%22+updated%3A%3E%3D2019-07-03+

There are quite a few PRs from @leonkrause adapting the build to recent Emscripten changes, which will need to be backported too. I haven't done it yet but I'll work on it soonish.

**Comment by bruvzg** [comment]
> As a reminder, a tedious but functional way to get back to the original PR for each of those commits for context is:

Just click `...` button alongside the commit in the list and hover over commit hash, direct PR link is in the tooltip pop-up, there's no need to click through 3 extra pages for each commit.

Screenshot 2019-07-03 at 19 45 40

**Comment by akien-mga** [comment]
Neat, thanks for the tip!

**Comment by akien-mga** [comment]
I'll merge now so that it can be tested easily in the `3.0` branch. If any of those commits should not have made it to the branch, we can still revert them prior to 3.0.7.

**Pull request merged**
