### PR TITLE
Improve popup menus usability

### PR DESCRIPTION
**Pull request by RandomShaper**
It seems that popups were intended to "grab" the mouse click that triggered them, but their intent was being lost. This commit does the necessary changes to let it happen and updates items that were trying to get advantage of it, because the semantics of `Control::grab_click_focus()` have changed a bit. Namely, it must be called **before** showing the modal.

**This allows to popup a menu and activate an item in it in a single click-point-release cycle, instead of having to click once to open the menu and once more to pick an item.**

This ability is extended even to context menus activated with the RMB (or any other mouse button, for that matter). The editor benefits from this in the context menu of the tree dock, which has been patched to opt-in for this feature.

This improves UX a bit by saving unnecessary clicks.

~**NOTE:** This changes a bit how `Control::grab_click_focus()` has to be used. Thereby, not sure if this can be safely cherry-picked for 3.0. I don't think it will break many projects, though. Furthermore, `grab_click_focus()` wasn't documented yet so we may afford this little change of behavior.~

**UPDATE:**
- Note:
_Please note this does not change how menu bars work. You still have to dismiss current pop-up and click to open another menu. I'll try to address that as well in a future PR._

- Change in code:
From now on, `PopupMenu` always grabs the click and also invalidates the first button release unless the mouse has moved (that's what `set_invalidate_click_until_motion()` was doing and now it's removed), so there is no longer the need of doing both things at every point a pop-up menu is shown.

### CODE REVIEW

**Comment by Zylann** [comment]
I was surprised to find out QtCreator and Paint.NET menus also behave like this...
Will this also allow us to hover across several menu buttons without having to re-click to make them unroll?

**Comment by RandomShaper** [comment]
I want to do that as well, but I find it harder, so I decided to do this first.

**Comment by RandomShaper** [comment]
Now I'm wondering if popup menus should grab the click unconditionally. For other modals it's always there to decide per particular case.

**Comment by akien-mga** [comment]
Probably won't cherry-pick it for 3.0 as it changes the behaviour of the PopupMenu API, otherwise seems fine for the master branch.

**Comment by akien-mga** [comment]
Is it still WIP or can we merge it and Test In Production™?

**Comment by RandomShaper** [comment]
Still some work to do. I'll leave a comment when it's ready.

**Comment by RandomShaper** [comment]
@akien-mga, this is now ready to merge/test.

**Pull request merged**
