### PR TITLE
Open selected folder when pressing the "Open" option in the menu

### LINKED ISSUE #28798: Open button in file system dock do nothing when folder is selected
**Godot version:**
3.2.dev.custom_build. df18c8c

**OS/device including version:**
Ubuntu 19

**Issue description:**
When I try to open folder with RMB and click open, then nothing happens
Zrzut ekranu z 2019-05-10 09-36-50

### PR DESCRIPTION
**Pull request by bojidar-bg**
An attempt to fix #28798. ~~Probably incorrect, review with care.~~

### CODE REVIEW

**Comment by groud** [comment]
I don't think this is the right solution, because every time you are going to update the tree, the path is going to be unfolded for no reason. I think the solution is to unfold the selected folders when using the "Open" option in the right click menu.

**Comment by bojidar-bg** [comment]
Updated the PR, now it should be better.

**Comment by groud** [comment]
LGTM :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
