### PR TITLE
Add `@observable` annotation to GDScript

### LINKED ISSUE #4867: Add `@observable` annotation for properties in GDScript
### Describe the project you are working on

This would be very useful for my music player since I basically had a signal for every one of my properties which triggered UI updates

### Describe the problem or limitation you are having in your project

https://github.com/godotengine/godot/issues/6491

This is cumbersome:

```gdscript
signal volume_changed(volume)

var volume := 0.5:
	set(value):
		volume = value
		volume_changed.emit(volume)

signal speed_changed(volume)

var speed := 0.5:
	set(value):
		speed = value
		speed_changed.emit(speed)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an annotation that automatically generates a listening signal

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# Implicitly generates volume_changed and speed_changed signals.
@observable(volume_changed) var volume := 0.5
@observable(speed_changed) var speed := 0.5
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Used often, and the workaround is many lines of repeated code

### Is there a reason why this should be core and not an add-on in the asset library?

GDScript is core

---

If you have annotation keyword suggestions, let me know and I will set up a vote.

Currently what needs to be discussed is:

- What is the annotation name?
- Should the signal be automatically generated by name or reference an existing signal? ~~automatically be named _and_ created?~~ _this will not happen as it is not clear at all what the signal is named or its existence_

### PR DESCRIPTION
**Pull request by mihe**
Closes godotengine/godot-proposals#4867.

This adds a new annotation to GDScript called `@observable`, which serves to generate the typical boilerplate when dealing with properties and signals.

This annotation is used like so:

```gdscript
@observable("speed_changed")
var speed: float = 5.0
```

... which roughly expands to this code:

```gdscript
var speed: float = 5.0:
    set(@new_value):
        if is_same(speed, @new_value): return
        var @old_value: float = speed
        speed = @new_value
        speed_changed.emit(speed, @old_value)

signal speed_changed(new_value: float, old_value: float)
```

... which would be used like so:

```gdscript
func _on_speed_changed(new_speed: float, old_speed: float) -> void:
    print("%s -> %s" % [old_speed, new_speed])

func _ready() -> void:
    speed_changed.connect(_on_speed_changed)
    speed = 5.0 # Prints nothing (but is configurable)
    speed = 10.0 # Prints '5 -> 10'
```

You can also use the same signal name for multiple variables, in which case they'll use the same signal, like so:

```gdscript
@observable("speed_changed")
var speed_x: float = 5.0

@observable("speed_changed")
var speed_y: float = 5.0
```

... or you can provide a signal yourself, like so:

```gdscript
signal speed_changed(new_speed: float, old_speed: float)

@observable("speed_changed")
var speed_x: float = 5.0

@observable("speed_changed")
var speed_y: float = 5.0
```

(The signature of the signal is not currently type-checked if you provide it yourself.)

Note that the generated code by default compares the current and new value with `is_same` before emitting the signal. This means the signal won't be emitted if setting the same value again. This also means that **only reference equality applies** in the case of `Array` and `Dictionary`. Using the normal equality operator struck me as needlessly expensive, given that it compares the contents as well.

You can omit this comparison entirely by passing an optional second boolean argument (named `compare_values`) to the annotation, like so:

```gdscript
@observable("speed_changed", false)
var speed: float = 5.0
```

Also note that the signal takes both the new value and the old value as arguments. I figured this would likely be requested sooner or later if not added, and retrofitting it would likely be painful. If you don't care about the old value, you can use `Callable.unbind` (found under the "Advanced" toggle when connecting through the editor), like so:

```gdscript
func _on_speed_changed(new_speed: float) -> void:
    print(new_speed)

func _ready() -> void:
    speed_changed.connect(_on_speed_changed.unbind(1))
```

## Issues/concerns

- Is this method of constructing AST nodes acceptable, or considered too brittle?
- Is there a way to avoid having to use a string literal for the annotation argument?
- Is the naming of `@new_value`/`@old_value` acceptable? I wasn't sure how to name generated stuff so as to avoid shadowing, so I took inspiration from the generated property setter/getter methods.
- Should extents be set on all constructed nodes? I'm currently only setting it on the ones that have happened to generate warnings/errors for me during testing, meaning the signal and `@old_value`
- What kind of tests would be desirable? I don't see a whole lot of them for annotations in general.
- When using type inference on the observed variable the signal parameters will always be of type `Variant`, due to `GDScriptAnalyzer::resolve_class_member` expecting a `datatype_specifier` for each signal parameter, which I can't provide in such a case. I do however have the actual resolved `datatype` already, since annotations are applied after the target variable has been resolved.

### CODE REVIEW

**Comment by RedMser** [comment]
Great work!

Would it be possible to add a `## doc comment` to the generated signal? It would show as a tooltip in the Node sidebar, as well as in the F1 documentation for the script. Something along the lines of `Emitted when the [member PROPERTYNAME] property changes.`

**Comment by mihe** [comment]
Those all sound like great suggestions, @RedMser. I'll look into it.

**Comment by dalexeev** [comment]
I'm not sure about auto-generating a large AST branch, perhaps this should be done in the compiler instead. Note that the signal (which is outside the variable, unlike the setter) may not be resolved properly, since the annotations are applied when analysis has already started.

Also, the proposal itself looks controversial to me. GDScript has some syntactic sugar, but this one seems too big and specific.

**Comment by RedMser** [comment]
> the proposal itself looks controversial to me

I wouldn't call it controversial when the proposal has over 50 positive votes, no negative votes and multiple duplicate proposals having been opened in the past.

**Comment by mihe** [comment]
> I'm not sure about auto-generating a large AST branch, perhaps this should be done in the compiler instead.

Right, yeah, I figured this might get brought up. This was largely a "I wonder if you could" type of implementation. It certainly sticks out in the context of the other annotations, and frankly the parser in general. I could look at pushing it further down the pipeline if needed.

> Note that the signal (which is outside the variable, unlike the setter) may not be resolved properly, since the annotations are applied when analysis has already started.

As far as the signal itself being resolved, that seems to (mostly) work fine, since it just gets appended to the end of `ClassNode::members` and is therefore always resolved after the target variable. There is the issue I mentioned in the list of issues/concerns with regards to the signal signature not being resolved fully when using type inference for the target variable, but that could (I believe) be fixed by allowing `GDScriptAnalyzer::resolve_class_member` to use `param->datatype` instead of `resolve_datatype(param->datatype_specifier)` if `param->datatype` happens to be set/valid already. That might warrant a more pervasive all-encompassing change though, assuming it's not considered too much of a hack to begin with.

I could be overlooking other parts of the analysis that might be important though.

> Also, the proposal itself looks controversial to me. GDScript has some syntactic sugar, but this one seems too big and specific.

That's totally fair. I must admit I don't know what the procedure is for proposals getting rejected. Who would make that call? It was fun getting a chance to mess around with the GDScript internals, but I'd rather see that the proposal (and this PR) gets rejected sooner rather than later if it's inherently never going to be idiomatic to GDScript.

**Comment by dalexeev** [comment]
> I wouldn't call it controversial when the proposal has over 50 positive votes, no negative votes and multiple duplicate proposals having been opened in the past.

Proposals are approved not by voting, but by considering the problem and solution. We need to reach a consensus, take into account not only user reactions, but also the language design, other related proposals, engine limitations, potential problems with implementation and further use of the feature.

Great support of the proposal means that many users have encountered this or similar problems and they liked the proposed solution. But this does not mean that this solution is the best and only possible. For example, the ability to reuse the same setter for multiple properties (#78991) seems like a more flexible solution:

```gdscript
var speed: float = 5.0:
    set = _set_property

var direction: Vector2:
    set = _set_property

signal property_changed(property: StringName, old_value: Variant)

func _set_property(property: StringName, new_value: Variant) -> void:
    if is_same(self[property], new_value):
        return
    var old_value: Variant = self[property]
    self[property] = new_value
    property_changed.emit(property, old_value)
```

**Comment by nlupugla** [comment]
Thanks for the PR, this looks like a great feature!

I don't have time to look at the code yet, but I have some comments on the syntax.

I don't like the fact that this version of the proposal makes it harder to determine at a glance what signals a script defines. In other words, I'd rather the argument to `@observable` be a signal (defined in a seperate line with `signal`) rather than a string. This might also make autocompletion and type checking easier.

Also, I lean against making this an annotation. This isn't documented anywhere explicitly, but the general trend so far is that annotations are for Godot-specific things (e.g. `@export`, `@onready`) and keywords are for generic language features. 

An alternative syntax that might be more idiomatic would be something like `var my_var : signal my_var_changed`, which could sit nicely beside the `set` and `get` syntax.

Finally, I like the idea of being able to customize whether and how comparison is done before emitting the signal. It would be cool to be able to write an expression like `old_val != new_val` or supply a comparison `Callable`.

**Comment by mihe** [comment]
> I don't like the fact that this version of the proposal makes it harder to determine at a glance what signals a script defines. In other words, I'd rather the argument to `@observable` be a signal (defined in a seperate line with `signal`) rather than a string.

I can certainly see this argument. I think it would result in an unfortunate amount of `signal some_property_changed(new_value, old_value)` boilerplate, but again, I can see why one would want that to be explicit.

> This might also make autocompletion and type checking easier.

Auto-completion seems to work fine already (in the built-in editor) as far as I can tell. Same goes for type-checking. `Signal.emit(...)` doesn't seem to be type-checked anyway, so the issue with the signal parameters not being resolved properly for inferred target variables seems to mostly just be a documentation/UX issue at the moment.

> Also, I lean against making this an annotation. This isn't documented anywhere explicitly, but the general trend so far is that annotations are for Godot-specific things (e.g. `@export`, `@onready`) and keywords are for generic language features.
> 
> An alternative syntax that might be more idiomatic would be something like `var my_var : signal my_var_changed`, which could sit nicely beside the `set` and `get` syntax.

That's fair. I have no objections to this being a keyword of some sort instead. I suppose the existing annotations can be thought of more as "imbuing" its target with metadata, rather than acting as syntactic sugar like this one does, which certainly makes this one look out of place.

> Finally, I like the idea of being able to customize whether and how comparison is done before emitting the signal. It would be cool to be able to write an expression like `old_val != new_val` or supply a comparison `Callable`.

While I can see the use for providing your own comparer, I think it's better to focus on reducing the more common boilerplate. In the end this isn't adding any functionality that you can't already achieve by just writing out the signal/property yourself, which I would probably opt for in these (presumably special) cases where you would feel the need to pass a custom expressions/callables.

**Comment by mihe** [comment]
Considering the (much appreciated) feedback here regarding this being too specific of a language feature, or at the very least not an approach idiomatic to GDScript, I'll go ahead and close this.

Thank you!

**Pull request closed without merging**
