### PR TITLE
Clarify identical `hash()` return values due to collisions

### LINKED ISSUE #58027: Class document for Array.hash is incorrect
### Godot version

3.4.2.stable.official

### System information

Windows-11

### Issue description

I don't believe the description for Array.hash is correct: The current text reads:

> Note: Arrays with equal contents can still produce different hashes. Only the exact same arrays will produce the same hashed integer value.

Hashing of the **same** data always results in the same hash value; however hashing of **different** data can sometimes result in the same hash value as you can get hash collisions. Specifically the hash function only returns a 32-bit integer, so there are only 4 billion unique hash codes, so by the pigeonhole principle hash collisions will be unavoidable.

The wording may want to be replaced with:

> Note: Arrays with equal content will produce identical hash values. However the reverse is not true, and identical hash values does not imply the arrays are equal, because different arrays can have identical hash values.

### Steps to reproduce

Read the existing documentation in (https://github.com/godotengine/godot/blob/master/doc/classes/Array.xml) and observe the current wording.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Calinou**
This closes https://github.com/godotengine/godot/issues/58027.

### CODE REVIEW

**Review by Malcolmnixon — APPROVED** [review]
Very nice, I had only looked at Array, but good catch on the rest.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
