### PR TITLE
Refactor shadow attenuation logic in scene shader.

### PR DESCRIPTION
**Pull request by lyuma**
The code for calculating directional shadows repeated roughly the same logic for each shadow split.
This change attempts to merge the duplicate codepaths, and use a macro to access per-split data.

There's no specific bug this addresses. However, the directional shadow code in particular was getting absurdly long just to scroll through, so I decided to crack this as a general code cleanup before making headway on other changes.

This is part of a larger series of changes I am making to allow for more flexibility in user-written shaders and enable NPR toon shading, the woes of which are described in issue #20207.

Performance concerns? Only thing I can think is risk of storing more state in variables using more registers: 8x vec4 are used compared to about 6x vec4 in the innermost if statement with the old code. The unknown is if compilers will fold more code into if statements.

Concerns about using macros? Previously a short macro `BIAS_FUNC` was used. I have made the macro'ed code a much larger percentage. I actually prepared another version of this PR which does not add any new macros: but has a bit more code duplication. If macros are a concern, I can present that version of this change.

I personally find the macro version easier to follow because of the lack of code duplication: it makes it obvious which logic is "analogous" between the branches, but I am open to comments.

### CODE REVIEW

**Comment by Calinou** [comment]
> Performance concerns? Only thing I can think is risk of storing more state in variables using more registers: 8x vec4 are used compared to about 6x vec4 in the innermost if statement with the old code. The unknown is if compilers will fold more code into if statements.

We eventually need to document a way to get the per-shader/total instruction count when running Godot.

**Comment by mijo-gracanin** [comment]
Can macros be replaced with inline functions? Those tend to have better IDE support when it comes to syntax highlighting and detection of errors.

**Comment by Calinou** [comment]
@mijo-gracanin This is GLSL, does it even have a concept of inline functions/lambdas?

**Comment by lyuma** [comment]
Generally, I think all functions in languages such as glsl are considered to be inline, so in that principle, splitting out to a function would be perfectly fine.

The reason I used a macro here, is because there is a series of variables with different names that cannot be dynamically indexed... for example `shadow_matrix1`, `shadow_matrix2`, `3` and `4` and analogously `uv_dir1` `uv_dir2` etc and `shadow_color1` and `shadow_color2` etc.

Similarly, some variables are vec4 with one component per shadow split. I believe swizzles known at compile time (.x, .y, [0], [1]) are easier to do than dot-products to pull out individual components, so that's a reason why I kept these accesses inside the macro: my goal was to avoid making things slower.

**Comment by lyuma** [comment]
This commit was Included in #42599

I will close this PR.

**Pull request closed without merging**
