### PR TITLE
Make drag and drop into viewport add to root node by default

### LINKED ISSUE #2381: Dragged sprites and scenes parented by default to the root node
### Describe the project you are working on.
Teaching high school kids to develop with Godot.

### Describe the problem or constraint you have in your project
When kids drag a sprite from the file system into the main Godot viewer, it gets parented to the selected node in the scene tab, often producing **unwanted parentings**.

### Describe the function/improvement and how it helps to overcome the problem or constraint
Create an option to **always parent the dragged sprite to the root node of the scene**.

### Describe how your proposal will work, with code, pseudo-code, mock-ups and/or diagrams
Captura de pantalla 2021-02-28 a las 17 56 44

### If this enhancement will not be used often, can it be solved with a few lines of script?
I don't know.

### Is there any reason why this should be basic and not an add-on in the asset library?
I think it would be very useful and more secure.

Dragging sprites now has 2 steps: 
1 - Select the parent node
2 - Drag the sprite.

In the new way, this would be 1 or 2 steps:
1 - Drag the sprite from the file system to the viewer.
2 - Drag the sprite to the desired parent, if necessary.

This also applies to dragging packed scenes from the filesystem.

I hope this input will be useful. If it has already been discussed, I apologise.

### PR DESCRIPTION
**Pull request by foxydevloper**
Closes: https://github.com/godotengine/godot-proposals/issues/2381
Implements the behavior suggested in https://github.com/godotengine/godot-proposals/issues/2381#issuecomment-787539659

This PR makes dragging and dropping a texture, mesh, or scene from the FileSystem into the 2D or 3D viewport add the node as a child of the current scene's root node by default. Holding Ctrl when dropping will add the node as a child of the selected node instead.

This also improves the tooltips in the 2D editor that show the modifier keys when dragging in a new node.
It also makes the tooltips appear when dragging in a scene in the 2D editor, not just when dragging in an image.
image

### CODE REVIEW

**Comment by LightningAA** [comment]
> This only changes the 2D editor, the 3D editor still adds node as children of selected node by default.

What was your reasoning for this? This sounds counterintuitive.

**Comment by foxydevloper** [comment]
> > This only changes the 2D editor, the 3D editor still adds node as children of selected node by default.
> 
> What was your reasoning for this? This sounds potentially counterintuitive/inconsistent.

I haven't looked into the code for dragging and dropping in 3D. I was thinking it could be done in a separate PR. I could implement it in this one though if it's better for consistency. 3D doesn't have a tooltip that shows up when dragging and dropping though, so that wouldn't be included if I were to. Also, does 3D have the shift modifier to add node as sibling?

**Comment by KoBeWi** [comment]
> Also, does 3D have the shift modifier to add node as sibling?

It does.

You can update the 3D behavior too, so they are consistent. Adding a label similar to 2D editor could be done in another PR.

**Comment by foxydevloper** [comment]
> You can update the 3D behavior too, so they are consistent. Adding a label similar to 2D editor could be done in another PR.

Alright, I've updated the 3D behavior to drag and drop into the root node by default, and added the ctrl modifier for adding as child.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
