### PR TITLE
Fixed setting node as root showing error and making invisible children visible.

### LINKED ISSUE #22469: Make scene root in Scene Dock show error
**Godot version:**
3.1 8fc92ae

**OS/device including version:**
Windows 10 

**Issue description:**
When I click RMB to child node of root and click at the "Make Scene Root", selected scene change to root but error is occured:

> ERROR: set_owner: Condition ' p_owner == this ' is true.
   At: scene/main/node.cpp:1472

**Steps to reproduce:**
aa

### LINKED ISSUE #22868: Moving a node to root in the Scene Dock reveals its hidden nodes
**Godot version:**
e6cfaa1

**Issue description:**
peek 2018-10-08 19-09

### LINKED ISSUE #22948: Making Instance local will reveal hidden children.
**Godot version:**
Godot 3.1 Alpha

When you make an instance local all hidden children of that node type will be made visible.

**Steps to reproduce:**

Create a LineEdit node. Save it as a scene, instance it in another scene and make it local.

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed setting node as root showing error and making invisible children visible.

Fixes #22469
Fixes #22868
Fixes #22948

### CODE REVIEW

**Comment by DualMatrix** [comment]
So this apparently failed to compile for some platforms, but the error messages don't make a lot of sense. Anyone know what's up with that.

**Comment by YeldhamDev** [comment]
Travis has been failing randomly for a while, it's likely nothing.

**Comment by DualMatrix** [comment]
Turns out this also fixes #22948

**Comment by akien-mga** [comment]
> So this apparently failed to compile for some platforms, but the error messages don't make a lot of sense They just seem to be wrong. Anyone know what's up with that.

The error messages do make sense, this PR adds compilation warnings which are then treated as errors by the CI.

With GCC:
```
editor/scene_tree_dock.cpp: In member function 'void SceneTreeDock::_tool_selected(int, bool)':
editor/scene_tree_dock.cpp:577:70: error: passing NULL to non-pointer argument 1 of 'Variant::Variant(int64_t)' [-Werror=conversion-null]
    editor_data->get_undo_redo().add_do_method(node, "set_owner", NULL);
                                                                      ^
editor/scene_tree_dock.cpp:586:72: error: passing NULL to non-pointer argument 1 of 'Variant::Variant(int64_t)' [-Werror=conversion-null]
    editor_data->get_undo_redo().add_undo_method(root, "set_owner", NULL);
                                                                        ^
```
With Clang:
```
editor/scene_tree_dock.cpp:577:66: error: conversion from 'long' to 'const Variant' is ambiguous
                        editor_data->get_undo_redo().add_do_method(node, "set_owner", NULL);
                                                                                      ^~~~
```

**Comment by akien-mga** [comment]
Casting might help:
```
$ rg add_do_method.*NULL
editor/scene_tree_dock.cpp
386:                    editor_data->get_undo_redo().add_do_method(editor, "push_item", (Script *)NULL);
1546:           editor_data->get_undo_redo().add_do_method(editor, "set_edited_scene", (Object *)NULL);
$ rg add_undo_method.*NULL
editor/scene_tree_dock.cpp
835:                    editor_data->get_undo_redo().add_undo_method(editor, "set_edited_scene", (Object *)NULL);
1675:                   editor_data->get_undo_redo().add_undo_method(editor, "set_edited_scene", (Object *)NULL);

editor/plugins/canvas_item_editor_plugin.cpp
4921:           editor_data->get_undo_redo().add_undo_method(editor, "set_edited_scene", (Object *)NULL);
```

**Comment by DualMatrix** [comment]
Thanks, fixed the compilation warnings.

**Pull request merged**
