### PR TITLE
VS type icons

### PR DESCRIPTION
**Pull request by djrm**
Please review.

screenshot from 2016-08-08 20-24-39

### CODE REVIEW

**Comment by reduz** [comment]
Appreciated, but still feel the current icons are easier to understand

**Comment by reduz** [comment]
There are just too many types to associate to images and remembering them

**Comment by bojidar-bg** [comment]
I think the Color, RID, Matrix* and Object  icons, as well as all the Array icons (as concept) are pretty good.

For Dictionary, maybe you can use <kbd>{}</kbd>?

**Comment by TheoXD** [comment]
The first one says "any"? Almost like letters are of different sizes and different height, unreadable.

**Comment by vnen** [comment]
I agree that many types are quite hard to understand if you don't already know the available types. Some of them I don't really know what they mean, like the `T` or the `in` with an arrow above the `K:V`.

**Comment by djrm** [comment]
I agree with you guys, the icons can be better but the main point to discuss here is the need for the icons, my opinion here is, that in reality the icons mean nothing, i mean most of the time you cant tell what something does by looking at the icon, (for example what is the relation of a happy face and a sprite), icons are meant to be easily distinguishable so after periodical use the icon becomes a reference to the action. the current icons are very understandable for people how is not familiar with the VScript interface, (well some of them since VScript is aimed to designers, who probably dont know what a float or a dictionary is) given that they actually show the type, but they will become irrelevant to more experienced users. experienced users will be basically guided by the colors, since the icons are almost the same and at least for me hard to read.

one solution to this problem is to add tooltips specifying the type for every socket.

**Comment by reduz** [comment]
They key problem here is _how_ the "associativity" happens. The icons for nodes, resources, etc. are easy to remember because when you create a node or resource, it's created via the type. If you stumble into an image you don't know I suppose you can check the type but it will not be that often.

In this case, you don't create these kind of inputs/outputs, they just come with the nodes, so it's a lot more difficult to associate what's going on and what they are. 

I'm not denying that a tooltip can help, I'm just stating that the small text on each port simply works better than any icon, no matter how beautiful it is, will. The icon just makes it worse, even if you put a tooltip.

**Comment by djrm** [comment]
@reduz i know you have pretty good reasons to prefer the text icons over the proposed ones you, as far as i cant tell you have used the VisualScripting more than i do, but just look at the rest of visual scripting out there for example Blueprint seems to do just fine without icon and only with color codes which makes me think that visual script user dont care too much about the types but about the possible connections (compatible sockets), i cant tell about what the users would prefer or what will be better for them, at least for me it has to do with connections an not types, but yeah is perfectly fine if the proposed icons are rejected, im just doing what i think would work.

**Comment by reduz** [comment]
Blueprint has a lot less datatypes than Godot, so it's not that bad, our
problem is that we really have a large amount of them.

**Comment by vnen** [comment]
One thing to have in mind is that you not only make visual scripts, you (or someone else) will have to read it later. Maybe a designer create the script and a programmer (unfamiliar with visual scripting) can review it. Data types as icons (unless they're really recognizable) can be a rock in the path.

I actually like the icons, but I'm concerned that in practice they might get in the way.

**Comment by djrm** [comment]
i gave it another try and made a new set of icons, what do you think?

vs_icons_2

**Comment by reduz** [comment]
Oh wow that looks great!

**Comment by bojidar-bg** [comment]
@djrm Well, all are pretty good (esp. the color coding), except the one right below Plane, and maybe the boolean icon (nobody refers to bools as bulls :wink: )

**Comment by djrm** [comment]
superseded by #6108

**Pull request closed without merging**
