### PR TITLE
Rename Array.invert() to Array.reverse()

### PR DESCRIPTION
**Pull request by madmiraal**
Does the same internally for List and Vector<>, which includes all PackedArray types.

Part of #16863.

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge of #47024.

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Makes sense to me, that's consistent with Python 3's [`array.reverse()`](https://docs.python.org/3/library/array.html#array.array.reverse), and avoids potential confusion with `insert()`.

Anyone *against* the change?

**Review by aaronfranke — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Seems consensual!

**Comment by akien-mga** [comment]
Thanks!

**Comment by MaaaxiKing** [comment]
Does this set an array to inverted/reversed or just return that? I find `invert()` better if it was set but `reverse()` for a **return** method without setting it. Comprehensible?

**Comment by Calinou** [comment]
@MaaaxiKing The return type is unchanged – it's still `void()`.

I think we should make this method return a new Array instead. Since renaming the method is a breaking change already, we might as well do it for 4.0.

**Comment by madmiraal** [comment]
Unlike other ideally immutable types, `Array`s are designed to be manipulated "in-place". It would be expensive to create a new array every time it was changed or assigned, which is also why they are passed by reference. Furthermore, when the user does want a copy, they need to specify whether they just want the `Array` copied or the individual items of the `Array` too, which is why [`duplicate(bool deep=false)`](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-duplicate) has a parameter associated with it.

**Comment by pycbouh** [comment]
@madmiraal Please use doctool with your renaming PRs. This one broke the alphanumeric order which results in unnecessary changes for others.

**Comment by madmiraal** [comment]
We should probably include it in the CI checks somehow.

**Comment by aaronfranke** [comment]
@madmiraal I've been wanting to do this for a long time, but right now doctool has to open a window first, and there's no headless DisplayServer available for Godot as of the DisplayServer split.

**Comment by madmiraal** [comment]
Unless I'm doing something wrong, the `doctool` doesn't warn about items being out of alphanumeric order.

**Comment by akien-mga** [comment]
It doesn't warn but it should fix the order. If there's any diff, then it could fail CI (if we could run it on CI).

**Comment by madmiraal** [comment]
I'm running ed2f51b15fee22a35d2a975fd77a70fc291bd8de (i.e. before #47631) with `--doctool`  and it doesn't fix the alphanumeric order. In `doc/classes/Array.xml`, `<method name="reverse">` is still before `<method name="is_empty" qualifiers="const">` :confused:

**Comment by akien-mga** [comment]
Are you running with `bin/godot --doctool .` (with the `.`)?

**Comment by madmiraal** [comment]
I was not. It works when I include the `.`. :tada: :smiley:

**Pull request merged**
