### PR TITLE
Multipass material support.

### PR DESCRIPTION
**Pull request by SaracenOne**
Okay, this PR retools how materials are handled internally somewhat. Materials now include the concept of having multiple 'passes', which contain all the information originally containined in the root material. This is a concept I've seen in many renderers including Ogre3D and Unity's ShaderLab system (which also both include the concept of a fallback mechanism for unsupported shader features; may be worth considering something similar in the future). What this means is that the renderer can render the same instance multiple times but with different shaders and render parameters. The easiest to describe use-case for something like this is rendering an object with an outline using an inverse hull, without having to do the rather cheap hack of just rendering multiple versions of the same geometry on the editor side of things.

Internally on the renderer side of things, not much has changed besides the fact that things are sorted via passes rather than materials now. More could probably be done to provide greater optimization advantages to a multiple pass material system (for example, it may be worth adding a mechanism of skeletal and morph modifications to be cached between multiple passes using the same material on the same instance), but it shouldn't incur any significant penalities to pre-existing functionality, and should also retain backwards compatibility with pre-existing content.

On the editor side of things, the most notable inclusion is that of the new multi-pass material type which allows you to set the number of passes, and then shaders and params for each pass. FixedMaterials and ShaderMaterials still remain and should work exactly as they did before. The only thing I was not able to keep as backwards compatible was changes to the VisualServer frontend due to needing to add new arguments for creating materials, but I don't imagine many people interacting with the VisualServer directly and it's very trivial to change such code. I also just pushed a PR for a minor fix for the tree gui control, and this is needed due the highly dynamic nature of the multipass material's parameter. On the whole, there are probably a lot more interesting things which can be done with this feature beyond the scope of what I had in mind, but this at least should provide a competent self-explanatory frontend to remove the need for a lot of rather inelegant hacks for certain graphical features.

Again, if there are any questions about this PR, please ask me.

### CODE REVIEW

**Comment by reduz** [comment]
I'll check as soon as I can!

**Comment by SaracenOne** [comment]
Thank you. It seems the build failed because there were some things I missed. I'll sort it out tommorow.

**Comment by akien-mga** [comment]
> I'll check as soon as I can!

Can you now? :D

**Comment by SaracenOne** [comment]
Speaking of which, I'm just about to push some documentation updates to this PR.

**Comment by wkubiak** [comment]
Hi guys, what's the status on this PR? Still in the checking queue? :)

**Comment by SuperUserNameMan** [comment]
I'd be interested too see this PR merged to 2.2 too.

**Comment by SuperUserNameMan** [comment]
I managed to test this MultiPassMaterial with fur-shading rendering.

First thing I want to say is that Multi pass material gives a great boost of performances for fur-shading. **The rendering went from 30 fps to 90 fps.**
Also, with this MultiPassMaterial, you don't have to regenerate the geometry of the Mesh for each layer of fur.
Instead, you simply add as much passes as layers to your material with a different fur_depth paramter for each, and you tell you Vertex shader to regenerate the geometry for each pass in realtime.
This is a gain of 5 to 10 seconds !

Now, the second thing is about the problem I've found with this MultiPassMaterial implementation :

1) it seems that each passes is trying to connect to the same signal 'changed' : 
````
ERROR: Signal 'changed'' already connected to given method '_shader_changed' in
that object.
   At: core/object.cpp:1436
````
2) it seems that the order in which each pass is rendered is not 100% reliable. Maybe related to z-sorting with transparent material.

If you want the multi-pass version of my fur-demo to test more, just tell me.

**Comment by SuperUserNameMan** [comment]
for those willing to test without having to struggle with git and compilers, i've put a Godot 2.1 win32 that includes this PR into here :
https://github.com/SuperUserNameMan/GodotFurShaderDemo/tree/master/with_MultiPassMaterial

You can also find the godot project for multi pass fur-shading at the same palce

**Comment by LeonardMeagher2** [comment]
Will this be a thing someone can do in 3.0 with the new shading language?

**Comment by reduz** [comment]
I was thinking of implementing multipass in a much simpler way for 3.0,
just adding a next_pass property to a Material (which is also of type
Material).

**Comment by Zireael07** [comment]
What's the status of this?

**Comment by akien-mga** [comment]
Archiving as per:

```
<Akien> reduz: Close #4084? Or do you still want it as a reference?
<Akien> reduz: Please also check #5769.
<reduz> Akien: close both, multipass will be implemented different in 3.0, and the morph fixes PR is unusable in 3.0 as it's done also in a different way in 3.0
```

**Pull request closed without merging**
