### PR TITLE
Rename AudioStreamRandomPitch to AudioStreamRandomizer and add additional randomization options

### PR DESCRIPTION
**Pull request by ellenhp**
Implements https://github.com/godotengine/godot-proposals/issues/3281

This kind of logic is necessary for most polished games so it would be nice to have it in core.

https://user-images.githubusercontent.com/1936763/132998298-869634b7-5438-44d1-89b6-21763f4b45e5.mp4

### CODE REVIEW

**Comment by mhilbrunner** [comment]
cc @reduz :)

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Fantastic work! Apologies for my delay in reviewing it, as it went under my radar.

**Comment by akien-mga** [comment]
Needs a rebase and it can be merged.

**Review by mhilbrunner — APPROVED** [review]
Docs look good too!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
