### PR TITLE
network - finish renaming AUTH to AUTHORITY

### PR DESCRIPTION
**Pull request by nathanfranke**

### CODE REVIEW

**Comment by Faless** [comment]
I honestly don't think we need a SERVER rpc mode. What you mention can be achieved with the following tree:
```
- Level
  - Player1 (auth: player1_id)
    - MessageBus (auth: 1)
  - Player2 (auth: player2_id)
    - MessageBus (auth: 1)
```

Having the "SERVER" RPC to `MessageBus`.

Or probably better swapped (i.e. message bus with auth: player_id and player auth: 1) so that the server can retain more control over the players.

**Comment by Faless** [comment]
> Should we move the RPC_MODE_AUTHORITY rename to a different pr?

Yeah, I think we should.

**Comment by nathanfranke** [comment]
I'm probably going to move it to a proposal first. This pr will be for the rename

**Review by Faless — APPROVED** [review]

**Comment by Faless** [comment]
Thanks!

**Pull request merged**
