### PR TITLE
[2.1] Fix text warp in color blocks with CJK

### PR DESCRIPTION
**Pull request by Geequlim**
Before
Before

After
After

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-pick for *master* as 18303cf.

**Comment by volzhs** [comment]
note that this change also affects to all language not only JCK.
image

**Comment by volzhs** [comment]
AFAIK, splitting by character, not word is not good for Latin characters. isn't it?
image

**Comment by Zireael07** [comment]
Latin-based languages overwhelmingly use splitting by word (I can't recall a language that would split by character). CJK split by character.

**Comment by akien-mga** [comment]
Yeah for Latin characters we should split by word.

**Comment by volzhs** [comment]
I guess we need another approach for this.

**Comment by volzhs** [comment]
AFAIK, only Chinese and Japanese has no space between words.
maybe, can we have this approach?

**Comment by volzhs** [comment]
I saw somewhere but I could not find it.
it's better to handle in case of "awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsomeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee" also

**Comment by volzhs** [comment]
as I can see on chrome on previous comment,
we can split word by character if word width is more than it's container width.
than we can solve both what @Geequlim wants and expects and the pretty long latin word case at the same time. :smile: isn't it?

**Comment by akien-mga** [comment]
Yeah, I think that was actually already the previous behaviour, but as @Geequlim's image shows it seemed not to work after colored letters (which would count as a word end apparently).

**Comment by volzhs** [comment]
It seems not about breaking word in case of specific colored word or letters, according to changes.

**Comment by Geequlim** [comment]
Oh，I'm sorry I didn’t noticed that.

**Comment by volzhs** [comment]
@Geequlim I think you don't have to be sorry. you just want to make engine better. :smile:

**Pull request merged**
