### PR TITLE
added bold font to editor (support for coustom bold font)

### PR DESCRIPTION
**Pull request by toger5**
For now only title font uses it.
screen shot 2018-04-10 at 17 23 58
screen shot 2018-04-19 at 22 10 55

But it is available in the editor now and can be as a font override anywhere.

### CODE REVIEW

**Comment by akien-mga** [comment]
It fails building: https://travis-ci.org/godotengine/godot/jobs/364682600

How does it look like? CC @djrm for review

**Comment by toger5** [comment]
@akien Ups I forgot to add the actual font file to the commit...

**Comment by djrm** [comment]
looks nice.

**Comment by akien-mga** [comment]
The main problem I see with this is that it won't work for the glyphs which are not in `NotoSansUI_Bold.ttf`, and for which we have the other `Noto*` variants and `DroidSans*.ttf`. If we want bold for every language, that means likely adding several MBs of font files, and I don't know if it's worth the trouble.

It does look OK, but I'm not sure it's worth it. I would appreciate more opinions on this before merging.

**Comment by toger5** [comment]
Which glyphs exactly are you referring to. of course there is only NotoSansUI_Bold.ttf. But I would look at it as one additional font to choose for the UI. Everything that is in DroidSans just cannot become bold. I think that is totally fine. Bold makes most sense in places where we currently use NotoSansUI anyways.

**Comment by volzhs** [comment]
I guess @akien-mga said about additional Arabic, Hebrew, Thai and CJK fonts for bold.

**Comment by toger5** [comment]
@akien-mga @volzhs I agree that this would make the binary unecassary big.
But I think only having it for the default settings is already really nice.

**Comment by reduz** [comment]
This looks good to me. For the other languages it still works without bold, which is not too terrible. We can add them if more people requests this.

**Comment by capnm** [comment]
@toger5  those warnings at editor start smell like coming from this PR ;)
godot d7d20b70afa53ab3ddb7fc594fb37d5f0c4c5bc4 + new project

EditorSettings::_get - Warning, not found: interface/editor/main_font_bold
EditorSettings::_get - Warning, not found: interface/editor/main_font_bold

**Pull request merged**
