### PR TITLE
Fix shape index in intersect_ray (#14473)

### LINKED ISSUE #14473: IntersectRay always returns shape_idx=0
**Version: Godot 3.0 beta1**
As can be seen [here](https://github.com/godotengine/godot/blob/33a59993945fb313309c8a68fe5d6e48b2bd1874/modules/bullet/space_bullet.cpp#L100), ray casting implementation always sets shape index to 0, yielding incorrect results.

### PR DESCRIPTION
**Pull request by ghost**
An attempt to fix [#14473](https://github.com/godotengine/godot/issues/14473).
Basically I copy-pasted code from [here](https://github.com/godotengine/godot/blob/33a59993945fb313309c8a68fe5d6e48b2bd1874/modules/bullet/godot_result_callbacks.cpp#L80), not sure if it's an ideal solution.
Tested it on my project, seems to work fine.

### CODE REVIEW

**Comment by akien-mga** [comment]
You shouldn't modify the code in `thirdparty/`.

**Comment by RomanAkberov** [comment]
@akien-mga Sorry, that was really stupid.

**Comment by akien-mga** [comment]
Could you squash the commits together? See [PR workflow](docs.godotengine.org/en/latest/community/contributing/pr_workflow.html)

**Comment by akien-mga** [comment]
It looks like @AndreaCatania did not see your PR and wrote almost the same fix in #14498.
I'll merge that one as it has one additional change (initializes `m_shapeId` to 0 in the constructor) and the right form (one commit), but thanks a lot for your contribution, and don't hesitate to do more :)

**Pull request closed without merging**
