### PR TITLE
Android: Remove permissions that have been removed from Android API

### PR DESCRIPTION
**Pull request by melquiadess**
Addresses part 1 of https://github.com/godotengine/godot-proposals/discussions/9492

## Removal of permissions not existing in Android API

Looking at the diffs between Android API levels, we can see that some permissions have been removed. Since not present in the API anymore, they likely don't have a use case for most apps, and are tech debt, so we can remove them too. If there's a rare use case anyway, they can be added in the Custom Permissions array.

### API [23](https://developer.android.com/sdk/api_diff/23/changes/android.Manifest.permission): 

Screenshot 2024-04-11 215841

### API [24](https://developer.android.com/sdk/api_diff/24/changes/android.Manifest.permission)

image

### API [29](https://developer.android.com/sdk/api_diff/29/changes/android.Manifest.permission)

image

## HOW TO TEST
- build the engine
- go to Export for Android
- see that the removed permissions are gone from the list

### CODE REVIEW

**Comment by kus04e4ek** [comment]
I think that all of the permissions supported by Android 6.0 (API 23) and above should be kept, since Android 6.0 is [listed as a minimum requirement](https://docs.godotengine.org/en/stable/about/system_requirements.html#id2). Docs can just say that the permission is deprected in the newer versions

**Comment by m4gr3d** [comment]
> I think that all of the permissions not deprecated in Android 6.0 (API 23) should be kept, since Android 6.0 is [listed as a minimum requirement](https://docs.godotengine.org/en/stable/about/system_requirements.html#id2). Docs can just say that the permission is deprecated in the newer versions

Agree! Our minimum version is actually lower (i.e: [`minSdk = 21`](https://github.com/godotengine/godot/blob/30e71782afd9a1fd35707b89511bcd1aa538f673/platform/android/java/app/config.gradle#L5)), so all permissions from that api should be kept, just marked as deprecated if they have been removed in newer versions.

**Comment by m4gr3d** [comment]
Going the extra mile, you could hide permissions based on the selected `minSdk` when using `gradle build`.

The [`get_export_option_visibility(...)`](https://github.com/godotengine/godot/blob/30e71782afd9a1fd35707b89511bcd1aa538f673/platform/android/export/export_plugin.cpp#L1916) can be used to hide permissions preferences by checking the `gradle_build/use_gradle_build` and the `gradle_build/min_sdk` (or `gradle_build/target_sdk`) preferences.

To simplify the process, the permission entry can be stored into a struct that specified the permission's min and max api level, so you can iterate over the permissions list and automatically hide / show.

**Review by m4gr3d — CHANGES_REQUESTED** [review]
Added some feedback in the comments.

**Comment by melquiadess** [comment]
> > I think that all of the permissions not deprecated in Android 6.0 (API 23) should be kept, since Android 6.0 is [listed as a minimum requirement](https://docs.godotengine.org/en/stable/about/system_requirements.html#id2). Docs can just say that the permission is deprecated in the newer versions
> 
> Agree! Our minimum version is actually lower (i.e: [`minSdk = 21`](https://github.com/godotengine/godot/blob/30e71782afd9a1fd35707b89511bcd1aa538f673/platform/android/java/app/config.gradle#L5)), so all permissions from that api should be kept, just marked as deprecated if they have been removed in newer versions.

Thanks both!

Here's my rationale - there are permissions marked as deprecated (but still present) in the API/docs - **I'd keep them.** 

The ones that were removed from the Android API (majority in API 23) - I don't see a pressing practical need to keep them, for a few reasons: they are available only in API 21/22 (for the sake of argument I'm ignoring the 4 other ones removed in 24&29) that Godot still supports, and they've been removed 9 years ago, so in my view the cost of keeping them in the codebase is slightly bigger (not that it's big anyway, but still...) than the perhaps inconvenience of adding them in the Custom Permissions array, should the developer want them (looking at those permissions, I'm presuming these would be more experienced devs who would want to use them via Custom Permissions array, but for majority it would be a clutter?). Otherwise, we'd keep all the other removed, obsolete, non-existent code long after its expiration date so to speak. I don't believe it makes sense in this case.

Happy to drop this of course, maybe I'm missing the bigger picture in Godot?

**Comment by melquiadess** [comment]
> Going the extra mile, you could hide permissions based on the selected `minSdk` when using `gradle build`.
> 
> The [`get_export_option_visibility(...)`](https://github.com/godotengine/godot/blob/30e71782afd9a1fd35707b89511bcd1aa538f673/platform/android/export/export_plugin.cpp#L1916) can be used to hide permissions preferences by checking the `gradle_build/use_gradle_build` and the `gradle_build/min_sdk` (or `gradle_build/target_sdk`) preferences.
> 
> To simplify the process, the permission entry can be stored into a struct that specifies the permission's min and max api level, so you can iterate over the permissions list and automatically hide / show.

Good idea. I've also been thinking about showing the deprecated, "Not for use by third-party applications."/the ones with protection level signature etc. in a separate section in the export dialog for clarity, eg. 

- `Permissions`
- `Permissions - deprecated`
- `Permissions - Not to be used by 3rd party`

Screenshot 2024-04-12 141404


maybe even on a separate `Android permissions` tab. Would that be useful?

**Comment by m4gr3d** [comment]
> > > I think that all of the permissions not deprecated in Android 6.0 (API 23) should be kept, since Android 6.0 is [listed as a minimum requirement](https://docs.godotengine.org/en/stable/about/system_requirements.html#id2). Docs can just say that the permission is deprecated in the newer versions
> > 
> > 
> > Agree! Our minimum version is actually lower (i.e: [`minSdk = 21`](https://github.com/godotengine/godot/blob/30e71782afd9a1fd35707b89511bcd1aa538f673/platform/android/java/app/config.gradle#L5)), so all permissions from that api should be kept, just marked as deprecated if they have been removed in newer versions.
> 
> Thanks both!
> 
> Here's my rationale - there are permissions marked as deprecated (but still present) in the API/docs - **I'd keep them.**
> 
> The ones that were removed from the Android API (majority in API 23) - I don't see a pressing practical need to keep them, for a few reasons: they are available only in API 21/22 (for the sake of argument I'm ignoring the 4 other ones removed in 24&29) that Godot still supports, and they've been removed 9 years ago, so in my view the cost of keeping them in the codebase is slightly bigger (not that it's big anyway, but still...) than the perhaps inconvenience of adding them in the Custom Permissions array, should the developer want them (looking at those permissions, I'm presuming these would be more experienced devs who would want to use them via Custom Permissions array, but for majority it would be a clutter?). Otherwise, we'd keep all the other removed, obsolete, non-existent code long after its expiration date so to speak. I don't believe it makes sense in this case.
> 
> Happy to drop this of course, maybe I'm missing the bigger picture in Godot?

@melquiadess Thanks for describing your rationale! From your comment I can identify two stated points; I can address them below:

- Cost of keeping the deprecated permissions in the codebase: Here I would take the opposite perspective; our official min sdk is `21` so we should support (as much as possible) all permissions from that api level UNLESS the cost of support is high. Based on previous experiences, I'm not seeing a high cost of keeping those permissions in the codebase.
  - This approach aligns with one of Godot's goals which is to prioritize the user experience. Here this means providing the necessary capabilities for developers choosing to target devices running api `21`. An additional perspective here is that in many parts of the world, people have devices running old versions of Android. [This chart](https://apilevels.com/) shows `~1%` difference in cumulative usage between api `23` and api `21`, which at the scale that Android runs is equivalent to ~20 millions devices.

- Removing clutter from the UI: This can be addressed by the suggestion I made above of hiding the permissions based on their min / max api levels!

**Comment by m4gr3d** [comment]
> > Going the extra mile, you could hide permissions based on the selected `minSdk` when using `gradle build`.
> > The [`get_export_option_visibility(...)`](https://github.com/godotengine/godot/blob/30e71782afd9a1fd35707b89511bcd1aa538f673/platform/android/export/export_plugin.cpp#L1916) can be used to hide permissions preferences by checking the `gradle_build/use_gradle_build` and the `gradle_build/min_sdk` (or `gradle_build/target_sdk`) preferences.
> > To simplify the process, the permission entry can be stored into a struct that specifies the permission's min and max api level, so you can iterate over the permissions list and automatically hide / show.
> 
> Good idea. I've also been thinking about showing the deprecated, "Not for use by third-party applications."/the ones with protection level signature etc. in a separate section in the export dialog for clarity, eg.
> 
> * `Permissions`
> * `Permissions - deprecated`
> * `Permissions - Not to be used by 3rd party`
> 
> Screenshot 2024-04-12 141404

I don't think a separate section is needed since we can provide that information in the permission tooltip (shows when hovering over the permissions).

Deprecated permissions (based on the target sdk level) can also been hidden using my earlier suggestion.

For the permissions that fall under `Not to be used by 3rd party`, we can hide them by default and only show them when `Advanced Options` is enabled.

> 
> maybe even on a separate `Android permissions` tab. Would that be useful?

A separate permissions tab would be really useful in cleaning up the clutter that permissions (even supported ones) add. However that may depart from the current style used in the export window, so that option would need to also scale to other export platform.
An alternative to reduce the visual clutter could be to add the ability to collapse sections in the export window.

**Comment by melquiadess** [comment]
Fair enough! 

Thanks @m4gr3d for taking the time to provide context and the additional information, I appreciate it.

### To summarize:
- we keep all permissions that were/are in the APIs supported by Godot, which as of now, is `minSdk=21`
- we _could_ show/hide certain permissions based on `minSdkVersion`, `maxSdkVersion` and `targetSdkVersion`
- we _could_ show 3rd party/special permissions only when `Advanced mode` is enabled
- we _could_ show extra information about a permission in the tooltip

**Pull request closed without merging**
