### PR TITLE
Add Math::slerp_angle

### PR DESCRIPTION
**Pull request by luis-l**
This adds a new Math utility to spherically interpolate between two angles.

It will allow users to do smooth rotations in 2D without having to deal with Transforms or Quaternions.

`slerp_angle` is reused in `Transform2D::interpolate_with` to avoid duplicate code.

Camera2D's new rotation smoothing feature will also depend on this new method #38277

Example, smoothly aim towards the mouse location
```
extends Sprite
var turn_speed = 5
func _process(delta):
    var mouse_angle = position.direction_to(get_global_mouse_position()).angle()
    rotation = slerp_angle(rotation, mouse_angle, turn_speed * delta)

```

slerpangle_gd_doc
slerpangle_vs

### CODE REVIEW

**Comment by aaronfranke** [comment]
> It will allow users to do smooth rotations in 2D without having to deal with Transforms or Quaternions.

I don't understand the use case, I don't know of any situation where you would be using quaternions in 2D to begin with.

**Comment by luis-l** [comment]
> I don't understand the use case, I don't know of any situation where you would be using quaternions in 2D to begin with.

True. 

But there is no straight forward way to do smooth rotations for 2D. This will new method will be for that use case.

**Comment by aaronfranke** [comment]
I think the documentation needs to mention how it's different from `lerp` and what the use cases are.

**Comment by lawnjelly** [comment]
Slerp is spherical linear interpolation, for the 3d case. In 2d, you don't interpolate a sphere, you interpolate a circle, which is much simpler, and lerp_angle does this. If you check the results of your slerp (if you've done it correctly), it should approximate the same answer as lerp_angle.

**Comment by groud** [comment]
Yes, as @lawnjelly said there is already an exisitng lerp_angle function, which likely work as a circular interpolation. There no need for a duplicate version.

If it is not, lerp_angle could simply be exposed to gdscript.

**Comment by luis-l** [comment]
slerp_angle was taken from Transform2D::interpolate_with. It was made into its own method in Math, so it can be reused in elsewhere. But if lerp_angle does the same thing we can use that instead. 

Should Transform2D::interpolate_with use Math::lerp_angle instead to interpolate is rotation?

**Comment by lawnjelly** [comment]
> Should `Transform2D::interpolate_with` use `Math::lerp_angle` instead to interpolate is rotation?

Quite possibly, but the situation there is a bit more complex coming from a Basis, there might be some non-obvious reason of numerical stability, for instance if r1 or r2 is undefined. I'd ask the author unless you are prepared to spend time rigorously testing it.

**Comment by luis-l** [comment]
The numerical stability reasoning makes sense for Transform2D.

For now, I think Camera2D rotation smoothing is good enough with `Math::lerp_angle`. Further details can be discussed in #38277.

Thanks for everyone's input.

**Pull request closed without merging**
