### PR TITLE
Fix missing parenthesis in the documentation

### PR DESCRIPTION
**Pull request by Iniquitatis**

### CODE REVIEW

**Comment by Chaosus** [comment]
Cosmetic and style PRs such as minor code reorganizations, adding comments, fixing a minor typo, etc. will not be accepted as first contribution (see https://github.com/godotengine/godot/issues/66666)

**Comment by Iniquitatis** [comment]
Um, okay. But can someone, who is not a first-time contributor, fix this typo?

**Comment by Chaosus** [comment]
> Consider grouping such fixes together in a single commit/PR so that it's easier to review and merge

So, in the period of hacktoberfest, you should do several changes (probably in different files) in order such PR to be accepted.

**Comment by Iniquitatis** [comment]
Got it.

(Though I'd like to point out that I'm not participating in any kind of activities—I'm participating in an open source project. Well, even if it means just a single byte fix.)

**Comment by Chaosus** [comment]
Alright, @akien-mga told me that this can be merged cuz it's an actual bugfix as the documentation is wrong. He also said it's preferable if such fixes are grouped together in a single commit, as we want to avoid contributors who open multiple PRs just for a single typo each.

**Review by Chaosus — APPROVED** [review]

**Comment by Chaosus** [comment]
Thanks, congrats with first contribution, and sorry for this little misunderstanding.

**Pull request merged**
