### PR TITLE
iOS: Fix memory leak on touch input

### LINKED ISSUE #66422: iOS memory leak on touch input
### Godot version

3.5 stable, 3.5.1 RC2

### System information

macOS, iOS

### Issue description

On iOS, touch input causes memory to leak, even in an empty scene with just a Node2D root (tested on iPhone 6s and 2020 iPhone SE). The leak seems to occur specifically on touch begin (not hold/release), and repeated multitouch tapping will increase the memory use by several MB within a few minutes. This also seems to degrade the FPS more and more as tapping continues.

Seems the leak was introduced back in 3.2.3 (it's not present in 3.2.2) - perhaps by #40723 somehow?

### Steps to reproduce

Open a fresh project with an empty test scene, export and run on iOS from Xcode. Repeatedly tap the screen (quite a lot), and Xcode should show the app's memory usage increasing permanently.

### Minimal reproduction project

any project should do

### PR DESCRIPTION
**Pull request by tbveralrud**
Fixes #66422 for **master** branch. A fix for 3.x is at #69200.

Replaces gesture recognizer with touch events directly from the view.

Rationale:
Gesture recognizers retain all touch events until their `state` property changes to "cancelled" or "ended."
The custom recognizer in the project fails to implement this requirement.
Setting the state to "ended" in the recognizer resolves the leak but introduces runtime assertions in logic that relied on an unending recognizer.

By forwarding the touch events directly from the view to Godot removes the need for a gesture recognizer.

Furthermore, the motivation for delaying touch inputs looks to be resolved too. (See #39624)
This branch removes the delay from touch events, putting iOS on parity with other platforms.
Project setting `input_devices/pointing/ios/touch_delay` has been removed as a consequence.

### CODE REVIEW

**Comment by djrain** [comment]
Can this get merged for testing? #66422 is a pretty serious issue (makes our small game unplayable on iOS).

**Comment by djrain** [comment]
Tested out 3.x version of this in our game, commented over there but I'll repeat here. It seems to have solved both the memory leak as well as the serious frame drops we were getting as a result of touch input. Wasn't a comprehensive test, but as far as I can tell this fixes a massive issue and should have a high priority imho.

**Review by bruvzg — COMMENTED** [review]
It seems fine overall, gesture recognizer is probably unnecessary, but need to be rebased and updated to account for Apple Pencil pressure/tilt data support.

**Comment by tbveralrud** [comment]
@bruvzg Rebased and updated.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
I rebased the PR to squash the commits into one, as most of the 6 commits were fixups/direct followups to the first one and not necessary to keep standalone.

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

This makes it particularly weird here as since I've rebased the commit (so you're the Git author and I'm the Git committer), only my GH profile is shown which makes it look like I authored the commit.
image

**Comment by tbveralrud** [comment]
@akien-mga Thanks for the nudge. This address has been associated with my account.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
