### PR TITLE
python like string escape implemented

### PR DESCRIPTION
**Pull request by ThakeeNathees**
**EDITED:**
1. escaping new line character, and invalid escapes are errors.
2. and `"\/"` is not a valid escape anymore.

string-newline-escape

### CODE REVIEW

**Comment by bojidar-bg** [comment]
What is the rationale behind this change?

**Comment by ThakeeNathees** [comment]
```gdscript
extends Node

## without escaping new line
var summary= """Summary about how this does a thing.
More information on it doing that thing.
This is injected straight into the XML, i.e. you can use Godot's XML doc features:
Now I'm referencing a Godot class: [Node].
Default implementation can be found in [method MyNode._override_me].
Here's an example of how you should override it...
[codeblock]
extends MyNode
@override # indented @-signs don't impact outer annotation
func _override_me() -> int:
	return 1
[/codeblock]
"""

## with escaping new line
var summary= """\
Summary about how this does a thing.
More information on it doing that thing.
This is injected straight into the XML, i.e. you can use Godot's XML doc features:
Now I'm referencing a Godot class: [Node].
Default implementation can be found in [method MyNode._override_me].
Here's an example of how you should override it...
[codeblock]
extends MyNode
@override # indented @-signs don't impact outer annotation
func _override_me() -> int:
	return 1
[/codeblock]
"""
```
escaping new line may looks better, and in `"x\y"` the `\` not escaping are just inspired from python.

**Comment by bojidar-bg** [comment]
Ah right. I did not notice that there are two changes, one for newlines, the other for invalid sequences.

While I agree that allowing one to escape newlines in strings is probably a good idea, I'm not sure about allowing invalid sequences without at least a warning. Otherwise, one is left to wonder why `"C:\Users\yadayada\hello_world.txt"` works but not `"C:\Users\yadayada\test.txt"` when opening a file under windows.

**Comment by ThakeeNathees** [comment]
Yeah its good idea not to allow invalid escapes. Ill remove it.

**Review by vnen — APPROVED** [review]
I used this as inspiration to add this escape into the new tokenizer. Could be merged in the meantime. Can't really go to 3.2 as it's technically breaking compatibility.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
