### PR TITLE
Hide popups initially

### LINKED ISSUE #24737: Popup nodes visible without calling any popup*() function.
**Godot version:**

3.1 alpha3, alpha4 and alpha5

**OS/device including version:**

Windows 7 Pro SP1

**Issue description:**

Popups with Visible set to true in editor will be visible when game is launched. No need to call any popup*() function.

Editor says Popups should be hidden if Popup's visibility is set to true and calling popup*() function will be required. It works like this in 3.0.6.

**Steps to reproduce:**
Open minimal project
Turn on visibility of all Popups (it isn't needed in 3.0.6 but 3.1 alpha disables visibility of some Popups)
Run the project

**Minimal reproduction project:**

https://github.com/hilfazer/Projects/tree/master/Godot/EngineIssues/PopupVisibleWithoutPopup

### PR DESCRIPTION
**Pull request by timoschwarzer**
Fixes #24737

### CODE REVIEW

**Comment by akien-mga** [comment]
#24737 seems to be a regression (it worked fine in 3.0.x), so it would be good to know *why* such a call would now be needed.

**Comment by timoschwarzer** [comment]
Seems like hiding nodes before adding them to the tree does not work.
https://github.com/godotengine/godot/blob/940392735ecff936898fd3aa25e013eda3569d3a/scene/gui/popup.cpp#L226

I didn't notice this `hide()` call before.

**Comment by akien-mga** [comment]
I found that the regression was caused by  f2e5405.

**Comment by akien-mga** [comment]
Superseded by ed9b2307 (almost the same fix in the end).

**Pull request closed without merging**
