### PR TITLE
Fix `region_filter_clip_enabled` to avoid sprite bleeding for interpolated sprite sheets

### LINKED ISSUE #87847: Godot 4.1.1: Questioning today's usefulness of Sprite2D property "region_filter_clip_enabled"
### Tested versions

Reproducible in (please see screenshots)
image
image

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Compatibility) - Intel(R) HD Graphics 630 (Intel Corporation; 27.20.100.8280) - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 Threads)

### Issue description

I've been testing and studying in detail Sprite2D node, its capabilities, methods and properties. I am questioning the usefulness of the boolean property `region_filter_clip_enabled` because I've been unable so far to make it work how I imagined it should work, despite all my testings. I understand also this subject has to do with the concept of "pixel bleeding". According to the docs:

_If **true,** the outermost pixels get blurred out. `region_enabled` must be **true.**_

By "outermost pixels", I believe we're talking about the pixels at the border of the selected rectangular region, though the thickness of this border is not specified (1 pixel, 2 pixels witdh...?).

I've been discussing the issue in Godot's communities, and I've been taught that spritesheets with tighly grouped sprites could lead to pixel bleeding. With this set up, I could start testing out the functionality of the aforementioned property. When set to **true,** **I expected this property (at least to a certain degree) to mitigate the pixel bleeding** that arises when the CanvasItem `texture_filter` is set to any of its linear variations (linear, linear mipmap, linear mipmap anisotropic), but I see no difference at all, which leads to suspect if this property is working properly, or if its been deprecated long ago and now is rubble.

Meanwhile, when `texture_filter` is set to any of its "nearest" variations, no bleeding occurs regardless of the value of `region_filter_clip_enabled` (the preferred case for pixel art).

### Steps to reproduce

All these screenshots were made in Godot 4.1.1. To test this out, I used this classic Sokoban spritsheet from Kenney's assets, where the boxes sprites have no spacing at all between them:

image

Carefully select the region for this blue box:

image

Try out many combinations of `region_filter_clip_enabled` and `texture_filter` properties. (Not all `texture_filter` are shown in this screenshot because the visual result repeats itsel,f as explained in the issue description above):

image

### Minimal reproduction project (MRP)

[Sprite2D region_filter_clip_enabled test.zip](https://github.com/godotengine/godot/files/14132087/Sprite2D.region_filter_clip_enabled.test.zip)

### PR DESCRIPTION
**Pull request by patowen**
Fixes #87847

This PR modifies the fix done in #12828 to reintroduce the `half_texpixel` offset but fix the bug in the original implementation that led to #11417.

My understanding is that the intent of this code was originally to clamp the UV-coordinates to the centers of the outermost texels, which achieves the desired effect of avoiding any sprite bleeding caused by linear interpolation. I believe this was conceptually correct, but a math error resulted in #11417.

### CODE REVIEW

**Comment by patowen** [comment]
I marked this PR as a draft because I think it might be worthwhile to update the description of `region_filter_clip_enabled` in the same PR, since "the outermost pixels get blurred out" don't seem to accurately describe this attribute, but I haven't decided on the right wording for it yet (and am open to suggestions).

**Review by clayjohn — APPROVED** [review]
Looks great! Thanks for updating the documentation as well. 

I tested on the MRPs from https://github.com/godotengine/godot/issues/87847 and https://github.com/godotengine/godot/issues/11417 and confirm that this fixes the former without re-introducing the issue from the latter.

**Comment by clayjohn** [comment]
The final step before merging is to squash all the commits together so that the whole PR only contains 1 big commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by patowen** [comment]
Makes sense to me. I went ahead and squashed the commits.

**Comment by patowen** [comment]
Based on the latest build error, I believe the Android arm32 check needs to be rerun, as the failure seems intermittent and unrelated to my changes. I don't believe I have permission to do this myself.

**Review by Mickeon — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by MeanRaccoon** [comment]
Cool, it's nice to see people working on the bugs we find eventually. Keep up!

**Pull request merged**
