### PR TITLE
Test godot+thorvg git tip

### PR DESCRIPTION
**Pull request by capnm**
# For svg testing
Issue: https://github.com/godotengine/godot/issues/72478 
Also needs PR https://github.com/godotengine/godot/pull/75034

### CODE REVIEW

**Comment by YuriSizov** [comment]
What's the goal here? Do you want to bump the version of thorvg used by the engine?

**Comment by capnm** [comment]
This is exactly the version I used to test the svg images in Godot. 
If someone can find other issues, they could fix it before making the next thorvg release :)

**Comment by akien-mga** [comment]
I believe this is to help @mgrudzinska (who is a ThorVG developer) test ThorVG/master in Godot to help solve #72478.

**Comment by capnm** [comment]
Obsolete, the ThorVG GitHub tip has been fixed.

**Pull request closed without merging**
