### PR TITLE
Prevent misuse of SafeRefCount

### LINKED ISSUE #64791: RefCounted reference count error
### Godot version

4.0 alpha11

### System information

Linux

### Issue description

Call unreference to a dead refrenece object it will relive.

As the the type of `RefCounted::refcount` is `SafeRefCount`

### Steps to reproduce

Make a `RefCounted` object and call `unreference` twice.
The object will be *dead* after first call and relive after second call.

2022-08-23 23-50-31屏幕截图

Change the reference count from `uint32_t` to `int32_t` to solve the problem ?

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by RandomShaper**
~(As a bonus, I've removed the `val`-suffixed versions, which weren't being used at all and were adding no value.)~ **UPDATE:** Nevermind.

Related to #64791.

**UPDATE:** PR repurposed.

### CODE REVIEW

**Comment by Geequlim** [comment]
Why not consider using signed integer for the reference count?
I think it makes sense that we get a negative number here. Getting `-1` or `-2` instead of `0` helps me find the problem faster when we debug the program (as I am binding the JavaScript language).

**Comment by neikeq** [comment]
My only concern is how much overhead this adds. If it's negligible, then it's fine. Otherwise, maybe it would be better to add a debug-only check to `unreference()` or the `SafeRefCount` methods. Let's keep in mind that manually incrementing and decrementing the refcount is not something the average user should do. And for things like language bindings, it's their responsibility to handle it properly.

**Comment by RandomShaper** [comment]
I was even considering removing the somewhat duplicate functionality; i.e., keep only the (`un`)`ref()` functions in `SafeRefCount` with an optional pointer to get the value if the caller wants it, but that's out of the scope of this PR, which just aims to fix the wraparound of the ref count.

Performance-wise, you can never be sure without measuring, but this shouldn't be noticeable.

**Comment by RandomShaper** [comment]
> Why not consider using signed integer for the reference count? I think it makes sense that we get a negative number here. Getting `-1` or `-2` instead of `0` helps me find the problem faster when we debug the program (as I am binding the JavaScript language).

If I understand your suggestion correctly, decrement would be kept unconditional, but increment would still be there to disallow the count from jumping back from 0 to 1. I think that can work just fine.

However, I'm not very fond of the idea that the negative values reach the caller; in other words, the negatives would be an implementation detail of `SafeRefCount`:
```
	_ALWAYS_INLINE_ uint32_t unrefval() {
		int32_t rc = count.decrement();
		return rc < 0 ? 0 : (uint32_t)rc;
	}
```

So, without disregarding the value of such a potential optimization, the way I see the situation we would pay the cost either of having awkward code to hide the implementation detail or that of exposing it, spilling the optimization into the scope of the caller.

**Comment by RandomShaper** [comment]
Rebased.

**Comment by RandomShaper** [comment]
To update this, based on Godot RC conversation with @reduz, this PR (or the alternative with a signed RC) is not the appropriate way to avoid the issue. It shouldn't happen in the first place, so no code should be attempting to detect and prevent it.

**Comment by akien-mga** [comment]
I guess it might still make sense to add some `ERR_FAIL` checks if these conditions are not meant to happen. With an appropriate error message it should already make it clear to users when they're wrongly using those methods.

**Comment by RandomShaper** [comment]
PR repurposed to warn the misusing developer. Please re-review.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
