### PR TITLE
Import thekla_atlas

### PR DESCRIPTION
**Pull request by hpvb**
As requested by reduz, an import of thekla_atlas into thirdparty/

### CODE REVIEW

**Comment by reduz** [comment]
you are my hero!

**Comment by bruvzg** [comment]
This breaks macOS build with `error: invalid argument '-std=gnu++11' not allowed with 'C/ObjC'`

**Comment by YeldhamDev** [comment]
> This breaks macOS build with error: invalid argument '-std=gnu++11' not allowed with 'C/ObjC', probably on thirdparty/thekla_atlas/poshlib/posh.c

Same on X11.

**Comment by reduz** [comment]
sorry, didnt realize and merged before travis was done

**Comment by bruvzg** [comment]
#14412 fixes macOS build.

But it is still broken on mingw.

Tested on macOS (mingw-w64 5.0.3; gcc 7.2.0-1) and Debian 9 (mingw-w64 5.0.1-1; gcc; 6.3.0-18)). 


```
thirdparty/thekla_atlas/nvcore/Debug.cpp: In function <<void nv::debug::terminate(int)>>:
thirdparty/thekla_atlas/nvcore/Debug.cpp:1002:27: error: <<s_handler_critical_section>> was not declared in this scope
     EnterCriticalSection(&s_handler_critical_section);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/thekla_atlas/nvcore/Debug.cpp:1002:27: note: suggested alternative: <<TryEnterCriticalSection>>
     EnterCriticalSection(&s_handler_critical_section);
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           TryEnterCriticalSection
thirdparty/thekla_atlas/nvcore/Debug.cpp:1004:5: error: <<writeMiniDump>> was not declared in this scope
     writeMiniDump(NULL);
     ^~~~~~~~~~~~~
thirdparty/thekla_atlas/nvcore/Debug.cpp:1009:16: error: <<backtrace>> was not declared in this scope
     int size = backtrace(trace, max_stack_size);
                ^~~~~~~~~
[ 42%] thirdparty/thekla_atlas/nvcore/Debug.cpp:1009:16: note: suggested alternative: <<trace>>
     int size = backtrace(trace, max_stack_size);
                ^~~~~~~~~
                trace
thirdparty/thekla_atlas/nvcore/Debug.cpp:1015:9: error: <<writeStackTrace>> was not declared in this scope
         writeStackTrace(trace, size, 0, lines);
         ^~~~~~~~~~~~~~~
[ 42%] Compiling ==> thirdparty/thekla_atlas/nvmesh/MeshBuilder.cpp
thirdparty/thekla_atlas/nvcore/Debug.cpp: In function <<void initHandlerThread()>>:
thirdparty/thekla_atlas/nvcore/Debug.cpp:1129:32: error: <<s_handler_critical_section>> was not declared in this scope
     InitializeCriticalSection(&s_handler_critical_section);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
[ 42%] Compiling ==> thirdparty/thekla_atlas/nvmesh/TriMesh.cpp
thirdparty/thekla_atlas/nvcore/Debug.cpp:1129:32: note: suggested alternative: <<TryEnterCriticalSection>>
     InitializeCriticalSection(&s_handler_critical_section);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                TryEnterCriticalSection
thirdparty/thekla_atlas/nvcore/Debug.cpp:1131:5: error: <<s_handler_start_semaphore>> was not declared in this scope
     s_handler_start_semaphore = CreateSemaphoreExW(NULL, 0, 1, NULL, 0,
     ^~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/thekla_atlas/nvcore/Debug.cpp:1135:5: error: <<s_handler_finish_semaphore>> was not declared in this scope
     s_handler_finish_semaphore = CreateSemaphoreExW(NULL, 0, 1, NULL, 0,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/thekla_atlas/nvcore/Debug.cpp:1142:9: error: <<s_handler_thread>> was not declared in this scope
         s_handler_thread = CreateThread(NULL,         // lpThreadAttributes
         ^~~~~~~~~~~~~~~~
[ 42%] Compiling ==> thirdparty/thekla_atlas/nvmesh/QuadTriMesh.cpp
thirdparty/thekla_atlas/nvcore/Debug.cpp:1142:9: note: suggested alternative: <<initHandlerThread>>
         s_handler_thread = CreateThread(NULL,         // lpThreadAttributes
         ^~~~~~~~~~~~~~~~
         initHandlerThread
thirdparty/thekla_atlas/nvcore/Debug.cpp:1144:41: error: <<ExceptionHandlerThreadMain>> was not declared in this scope
                                         ExceptionHandlerThreadMain,
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
[ 42%] Compiling ==> thirdparty/thekla_atlas/nvmesh/MeshTopology.cpp
[ 42%] Compiling ==> thirdparty/thekla_atlas/nvmesh/halfedge/Edge.cpp
thirdparty/thekla_atlas/nvcore/Debug.cpp:1144:41: note: suggested alternative: <<initHandlerThread>>
                                         ExceptionHandlerThreadMain,
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                         initHandlerThread
```

**Comment by hpvb** [comment]
I'll try to fix that mingw build error. I won't have time until tomorrow around 11:00 am CET though.

**Comment by hpvb** [comment]
Actually, I have an idea: Could you patch modules/thekla_unwrap/SCsub and change line 65 to look like this:

```python
env_thekla_unwrap.Append(CCFLAGS=["-DNV_OS_WIN32", "-DNV_CC_MSVC"])
```

I'm just guessing based on the error and the surrounding code.

**Comment by bruvzg** [comment]
>Actually, I have an idea: Could you patch modules/thekla_unwrap/SCsub and change line 65 to look like this...

Nop, this will break it even more, but removing `NV_CC_MSVC` checks form lines `17-28`, `97` and `113` of `thirdparty/thekla_atlas/nvcore/Debug.cpp` works.

**Comment by hpvb** [comment]
Alright, that was my second guess :) I'll make a PR based off of this information. Thank you.

**Pull request merged**
