### PR TITLE
fix(editor): TileMap Fill Rectangle icon

### PR DESCRIPTION
**Pull request by erictuvesson**
The default color was blue which is the active color, changed it to be gray by default.

Before:
image

After:
image

After with focus:
image

### CODE REVIEW

**Review by caiotava — APPROVED** [review]

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by groud** [comment]
Arf damn, sorry! This has to be reverted. 
I've just realized this icon is indeed used by the RectangleShape2D node. We used it as a placeholder in the tilemap editor but we need to create another icon for it instead.

**Comment by erictuvesson** [comment]
> Arf damn, sorry! This has to be reverted.
> I've just realized this icon is indeed used by the RectangleShape2D node. We used it as a placeholder in the tilemap editor but we need to create another icon for it instead.

I only found it being used in one place.

**Comment by groud** [comment]
Yes, it's not hardcoded in the code because classes icons are using the icon file with the same name as the class name. See:
2020-10-22-104137_3840x1600_scrot
(In french but you get the idea)

**Comment by erictuvesson** [comment]
@groud do you have any preference for the name of the new icon, then I can make it?

It would be nice if there was something to prevent this for happening again.

**Comment by groud** [comment]
I guess something like Rectangle.svg would be ok, we have no class with that name. 
The bucket fill icon is named Bucket.svg, so I think it's consistent. 

> It would be nice if there was something to prevent this for happening again.

Well, review should have helped there, my bad ^^. But to be honest this does not happen often, it's quite rare (and a bad practice) to reuse an icon as a placeholder.

**Pull request merged**
