### PR TITLE
Really fixes fullscreen mode in OS X, even during startup

### PR DESCRIPTION
**Pull request by ricpelo**
This PR should works even during project startup.

### CODE REVIEW

**Comment by ricpelo** [comment]
Now it should really fix #1811.

**Comment by ricpelo** [comment]
@reduz, do you think this patch could be integrated into the master branch before 1.1 release? That will be great for us the OS X users :). Thanks!

**Comment by punto-** [comment]
Looks good, although it does some weird animation at the start.

**Comment by ricpelo** [comment]
Yes, you're right. I've tried to remove it, without luck. It looks that the window lose the focus and get it back again. Keep investigating...

**Comment by ricpelo** [comment]
Hi, @punto- ! I've a patch that disables the nasty effect at the start. Seems to work OK with all the demos I've tried. Please, can you take it a look? Thanks!

https://github.com/okamstudio/godot/pull/1834

**Comment by punto-** [comment]
Looks good. There's still a bit of a weird effect (the game appears as
fullscreen behind the animation of the window zooming?), but way better
than before. I don't know what's the standard behavior for osx tho. Github
server is down, I'll try to merge later.

**Comment by ricpelo** [comment]
Great! That's all the best I can reach, but I think it's much better than the other patch. Thank you very much, @punto- ! Github is now up again, btw ;).

**Pull request merged**
