### PR TITLE
Fixed ItemList indexing

### PR DESCRIPTION
**Pull request by rlewicki**
Fixing #5772 
Also added functionality for unselecting items in itemlist while clicking in empty space.

### CODE REVIEW

**Comment by akien-mga** [comment]
Nice first PR :)

Several small issues in the form that would be nice to fix by amending the commit (`git commit --amend`):
- Use tabs for indentation and not spaces, like done in the rest of the code
- Don't let your IDE strip trailing whitespace on lines you did not edit, this adds noise to the diff
- Don't keep commented out code, with git it's easy to find out when code was added/removed, so we don't need to keep dead code (even though the current source is ridden with it... it's a long running effort).

**Comment by zgub4** [comment]
Thanks for advices. :)

**Comment by akien-mga** [comment]
Hm, your git client did something weird to the history, there are now 3 commits, the two first one being conflicting and the third one is an empty merge commit. I guess I'll cherry-pick a50377a if the PR is considered good to merge :)

**Comment by akien-mga** [comment]
I cherry-picked the commit manually and pushed it in your name ;)
I also removed the unused `closest_dist` variable as seen in #5857.

**Pull request closed without merging**
