### PR TITLE
Avoid overestimating the cost in AStar heuristics.

### LINKED ISSUE #8584: AStar weight scale applied to whole path during solve?
**Operating system or device - Godot version:**
X11, 64 bits, 2.1.3 and 3.0

**Issue description:**
Trying to make a board game style hex tile map. Connecting points and giving most points a weight of 1, and some points a weight of 2. Expected solution would be to consider moving through 2-weighted cells to cost 2 move points and 1-weighted cells to cost 1 point.  Looks like weight gets multiplied to the whole distance calculation (*= used in line 194 or 222, etc). I saw it avoiding a path of 8 2-weighted cells and choosing instead 22 1-weighted cells.

**Steps to reproduce:**
Create a hex tile map and add only the hexes that have a tile on them as points in A-Star. connect all adjacent hexes. Give some cells a weight of 2 and some a weight of one, making some paths theoretically cost more. When path is solved, the shortest path often doesn't seem to properly factor cost as per cell, but cumulative instead. Pretty hard to explain, but it seems wrong to me.

**Link to minimal example project:**
I'll make a sample project and add it soon...it'll take a little extra time. Wanted to get issue raised first.

### PR DESCRIPTION
**Pull request by ghost**
This is a necessary condition for finding optimal solutions.
This is achieved by simply requiring/ensuring that no weights are smaller than 1.

Fixes #8584.

### CODE REVIEW

**Comment by tagcup** [comment]
This simply implements the fix I [mentioned originally](https://github.com/godotengine/godot/issues/8584#issuecomment-298386446) three weeks ago.

Advantages over #8786:

* A very simply, one liner fix.
* `remove_point` works correctly.
* Adding and removing a point doesn't lead to unexpected side effects.

**Comment by bojidar-bg** [comment]
> Fixes #8584.

No, it doesn't. Check old lines 193 and 293. My PR is just doing two things at once...

The original problem was that the _WHOLE_ path's cost was multiplied by weight_scale, not just the current cost, and also that the estimation was multiplied by the cost of the node it was done from.

I'm fine with merging this PR though. I would just remove the questionable min_weight_scale code, which you seem to dislike from it, and it would fix #8584.
If you remember, I implemented it because of your comment: https://github.com/godotengine/godot/pull/8786#issuecomment-302199096. Guess it is indeed better for another PR.

Sorry for the rage.

**Comment by tagcup** [comment]
Ah, you mean this:

```cpp
	real_t distance = _compute_cost(p->id, e->id) + p->distance;
	distance *= e->weight_scale;
```
which should have been

```cpp
	real_t distance = _compute_cost(p->id, e->id) * e->weight_scale + p->distance;
```
You're right, thanks for pointing that out. I missed that, which is an entirely different kind of bug (or typo I guess) than what I'm talking about here.

**Comment by tagcup** [comment]
No worries; I'd be fine with the renormalization if it's implemented in a proper way that is transparent to the user, without making any assumptions about the added/removed points and with no side effects from internal implementation details.

The trade-off seems to be:

* Pro: minimum weight is changed from >=1 to >0 so that users can use values in the interval (0,1), which would be nice (although it's not essential)
* Con: To ensure that removing a point plays nice, we either need to scan the entire stack for the new minimum which is O(n), or implement and maintain a priority queue based on weight which would take it down to O(log n). The current remove is just O(1).

I just think the cons overweigh the pros here.

**Comment by bojidar-bg** [comment]
@tagcup I would like to apologise for my inability to see your point. I realise I acted as a jerk in maintaining that my point of view was the only one correct, and would like to thank you for awaking me from this egocentric state by opening a your PR. 💯

**Comment by tagcup** [comment]
@bojidar-bg Ah, no, no worries, I could've communicated better in the first place

**Pull request merged**
