### PR TITLE
Add methods to remove theme overrides

### LINKED ISSUE #32110: Impossible to clear Control theme override values
**Godot version:**
4ee8ecd

**Issue description:**
Documentation of e.g. `add_color_override()` states that if color is empty or invalid, the override is cleared. However, it is impossible to assign anything but color due to type checking (`null` is not accepted either), thus you can't clear the override.

### PR DESCRIPTION
**Pull request by KoBeWi**
Resolves #32110

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Aside from `add_theme_color_override`, all other theme property overrides can be cleared by passing a given value (0 or null) as written in the docs.

If we add `remove_theme_*_override` for all of them, then maybe we should also remove the behavior where they clear themselves on specific values.

**Comment by pycbouh** [comment]
I say we remove that behavior in master, but keep it in `3.x` (as this PR can be cherrypicked). It doesn't make sense for a function called `add_override` to have a special case value that removes an override. I feel like it's just a hack for the Inspector, and nothing else (which should be tested if we do remove this trick).

**Comment by KoBeWi** [comment]
> If we add remove_theme_*_override for all of them, then maybe we should also remove the behavior where they clear themselves on specific values.

I tried this. When you set a `null` stylebox it will crash, so I just left it as is.

**Comment by akien-mga** [comment]
> When you set a `null` stylebox it will crash, so I just left it as is.

Sounds like a good reason *not* to leave it as is :) Or at least this needs a bug report as it contradicts the documentation.

**Comment by KoBeWi** [comment]
Maybe it should just throw error on null 🤔
btw by "as is" I mean the current behavior of removing override.

**Comment by KoBeWi** [comment]
Ok altered the old behavior in another commit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
