### PR TITLE
Splitting tonemapper into its own class

### PR DESCRIPTION
**Pull request by BastiaanOlij**
First step in splitting effects class into separate classes. This splits the tonemapper into its own class. Also uses the new global uniform cache.

### CODE REVIEW

**Comment by FancyTextLabel** [comment]
Serious question, why are you guys splitting the classes? These changes will increase performance or it's just a code reorganization?

**Comment by clayjohn** [comment]
> Serious question, why are you guys splitting the classes? These changes will increase performance or it's just a code reorganization?

Reorganization. A few of the rendering classes were getting too long.

**Review by clayjohn — COMMENTED** [review]
Looks fine! We just need to track down what is causing that runtime error that is failing the builds.

**Comment by BastiaanOlij** [comment]
> Looks fine! We just need to track down what is causing that runtime error that is failing the builds.

Oh totally missed that... I'm guessing I'm not cleaning something up on destruction properly

**Comment by BastiaanOlij** [comment]
Ok, seems issues are now fixed and after talking to @clayjohn we've also decided to start moving the shaders into a separate folder. For now just the tonemap shader but we'll add the rest as we split out more effects. 

@FancyTextLabel indeed, its all just about organization, some of these classes were becoming so large it became really hard to maintain them.

However it is also in preparation of some amount of redesign, as we look back on how the clustered and mobile renderers have overlap and are split. Making the storage and effects classes more accessible will make it easier to better organize these renderers.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
