### PR TITLE
Remove cartesian2polar and polar2cartesian

### PR DESCRIPTION
**Pull request by KoBeWi**
See https://github.com/godotengine/godot/pull/48237#issuecomment-908776584
It was discussed on chat.

### CODE REVIEW

**Comment by fire** [comment]
I don't think there is a visual script upgrade system. The enums changed so theoretically the function enum now points to a different method.

**Comment by aaronfranke** [comment]
@fire We should improve VisualScript to not be so brittle. Perhaps we should save StringNames instead of enums. It doesn't make sense for every method in the script to change to another if some methods are added in engine updates. But that's a separate issue that isn't related to this PR.

**Review by aaronfranke — APPROVED** [review]
Looks good to me, I haven't tested this but if it compiles it should be fine.

As discussed on the RocketChat, these methods aren't necessary. Additionally, even if they are useful for people and we later decide we do want them, they should be replaced with instance methods on Vector2, so either way we should remove the existing versions.

**Review by reduz — APPROVED** [review]

**Comment by vnen** [comment]
Thanks!

**Pull request merged**
