### PR TITLE
AnimationPlayerEditor Realtime Update.

### PR DESCRIPTION
**Pull request by fire**
Co-Authored-By TechnoArt Studio <71520126+TechnoArtStudio@users.noreply.github.com>

See https://github.com/godotengine/godot/pull/43292 and its comments.

### CODE REVIEW

**Comment by fire** [comment]
> reduz
> Fire: this is not a problem of animationplayer, this is a problem of the inspector
I am fed up of this, I will fix this properly next :P

Will leave this, but reduz challenged my pr. So I'll wait for his response. 🥊

**Comment by fire** [comment]
Will wait for @reduz to implement. Not sure what to do.

**Comment by TechnoArtStudio** [comment]
What happened to this pull request?
Why is it closed and not merged?

**Comment by akien-mga** [comment]
See the closing comment:

> Will wait for @reduz to implement. Not sure what to do.

**Pull request closed without merging**
