### PR TITLE
Add icons for 3D texture classes

### PR DESCRIPTION
**Pull request by MewPurPur**
image

Oh, and the old Texture3D icon is deleted. Its style clashed with the one I went for here, also it's an abstract class so an icon isn't that important. Texture2D hasn't got one for example

### CODE REVIEW

**Comment by fire** [comment]
I can't visually recognize CompressedTexture3D and NoiseTexture3D.

**Comment by MewPurPur** [comment]
OK, let me revise

**Comment by MewPurPur** [comment]
image

I moved the cube configuration a little so ImageTexture3D has its white in different places. Not a fan of it personally, I kept it as is but I'm ready to push the changes if wanted.

**Comment by timothyqiu** [comment]
I thought the NoiseTexture3D icon was showing something like fog. But it turned out to be 3D cubes when I open the SVG :rofl: 

I think using a flat image would be more easier to read. It does not have to be 3D since the image is like a sticker on a box.

**Comment by WhalesState** [comment]
have a look on this, it may be easier to recognize with a jaggy line
image

**Comment by MewPurPur** [comment]
Squares should be good and familiar from the 2D version. This idea could be used for an icon for the Noise class.

**Comment by WhalesState** [comment]
> Squares should be good and familiar from the 2D version. This idea could be used for an icon for the Noise class.

you can keep the cube and add a jaggy line over it instead of the smaller cubes
image

**Comment by MewPurPur** [comment]
I get you, but that's not what I'm saying. I'm saying I want to remain similar to this:

image

Anyway, next take, what do you think? It's not grid-aligned, that's impossible, but hopefully it's distinct enough to make up for it.

image

**Comment by WhalesState** [comment]
It looks good and clearer than the previous one, the icons size in godot are 16x16px, you can make it looks sharper if you snap the points to grid if possible, like this small edit.
NoiseTexture3D

**Comment by MewPurPur** [comment]
I'm not too strict about the grid, sometimes not making things grid-aligned allows you to make them larger, and therefore clearer. Do you have the SVG of your example? I'm pretty on board with the idea of keeping the 3D-ness, but only as an "easter egg" while the front faces are big enough to look comparable to NoiseTexture2D's squares. I'll test it later though

**Comment by WhalesState** [comment]
> Do you have the SVG of your example?
the points are aligned now, it's fine to ignore the grid snapping to pixels but for such small size it will result in blur even if you slightly move a point, and this blur will make it harder to read when they render in the editor.

Texture3D
NoiseTexture3D

**Comment by MewPurPur** [comment]
Could we merge this as is, anyway? I'm down to do a follow-up PR exploring the Noise-related classes, so I could think of ways to improve this icon in a PR that affects all noise textures.

**Comment by MewPurPur** [comment]
#79722 @WhalesState I used the jaggy line here.

**Comment by WhalesState** [comment]
> #79722 @WhalesState I used the jaggy line here.

the jaggy lines looks cool.

**Comment by MewPurPur** [comment]
Alrighty, seems to be what everyone thinks, so I'll do another take on this one!

**Comment by MewPurPur** [comment]
Haven't important changed anything in this push, I'm still using the initial design. Can't get to anything I like as much.

**Review by Calinou — APPROVED** [review]
Tested locally, looks good to me. The icons are easily recognizable as 3D, which is usually the most important distinction (as you can't use those in places that expect 2D textures and vice versa).

Screenshot_20230805_012047

Screenshot_20230805_012101

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
