### PR TITLE
GUI declares input as handled only if it is really handled

### LINKED ISSUE #54529: Control consumes CollisionObject events for Area2D despite mouse_filter set to "pass"
### Godot version

3.3.4 stable, 3.4rc3, Godot v4.0.dev.20211015.official [f113dc986]

### System information

Win 64, Nvidea 765M

### Issue description

This one has cost me a lot of frustration and debugging time. Tested and confirmed in all current versions: 3.3.4, 3.4, 4.0.

If there is a Control overlapping an Area2D, the Control will consume the input event and mouse_entered and mouse_exited signal, despite mouse_event being set to "pass".

**This makes it impossible to use Area2D nodes and Control nodes in the same project when both overlap and need the mouse events**

https://user-images.githubusercontent.com/47016402/139970970-37d8ca75-53e1-4302-9a17-7787a740ded8.mp4

And  mouse_entered and mouse_exited signals of the Area2D won't fire either when the Area2D is overlapping with the Control:

https://user-images.githubusercontent.com/47016402/139999079-ddfc4d05-cc7e-422e-ac79-401143ad4eb5.mp4

### Steps to reproduce

1. Add a Control node, set it's mouse_filter to "pass" and connect the gui_input(event) signal to a script
2. Add a Area2D node and a CollisonShape2D, and connect the input_event(event) signal to a script
3. Make sure the Area2D is overlapping the Control node
4. Observe the Area input_event(event) signal not firing any more

### Minimal reproduction project

Godot 3.X minimal project: 
[area_over_control_bug_godot3.zip](https://github.com/godotengine/godot/files/7464746/area_over_control_bug_godot3.zip)

Godot 4.0 minimal project:
[area_over_control_bug_godot4.zip](https://github.com/godotengine/godot/files/7464745/area_over_control_bug_godot4.zip)

### PR DESCRIPTION
**Pull request by BimDav**
See https://github.com/godotengine/godot/issues/54529.

Input events were consumed by Control nodes as long as their filter was not set to MOUSE_FILTER_IGNORE. With this change they are consumed only if the Control handles the event or its filter is set to MOUSE_FILTER_STOP. Notably MOUSE_FILTER_PASS will not consume the event. Such unhandled event will then trigger _unhandled_input methods.

### CODE REVIEW

**Comment by golddotasksquestions** [comment]
Thanks you for this fix!!

**Comment by golddotasksquestions** [comment]
@akien-mga 
Would it be possible to cherry-pick this fix for 3.4.1?
Besides https://github.com/godotengine/godot/issues/54529, I'm also having issues with mouse filter "pass" in my Control node only inventory and drag and drop scenes because pass is setting the input as handled.

**Comment by golddotasksquestions** [comment]
@BimDav @YeldhamDev 

Is this issue with Pass behaving like stop possibly related to this:
https://github.com/godotengine/godot/issues/55432

**Comment by BimDav** [comment]
> Is this issue with Pass behaving like stop possibly related to this: #55432

I tested your project and sadly, no, this PR does not fix #55432, which is apparently related to input handling between Control Nodes. I will have a look at it soon.

**Comment by KoBeWi** [comment]
This isn't really a bugfix, because it changes established Control behavior. It breaks compatibility and might break lots of things if it resolves #55432 too.

But seems like the original behavior causes lots of confusion, so I wonder if changing it isn't maybe good.

**Comment by golddotasksquestions** [comment]
The intended use for "Pass" is not to behave like "Stop". Why would it? We already have "Stop" for the stop behaviour.
If "Pass" is expected by users to behave as the name indicates (to pass) and behaves like "Stop" it clearly is a bug. The fact that it is known behaviour to some, does not make it less of a bug.

**Comment by KoBeWi** [comment]
Except it does pass the input, but under different rules than most people think. So the only problem is that it's unexpected. Pretty sure there was a reason for the original behavior.

**Comment by BimDav** [comment]
> Except it does pass the input, but under different rules than most people think. So the only problem is that it's unexpected. Pretty sure there was a reason for the original behavior.

I had the exact same reaction in https://github.com/godotengine/godot/issues/54529, but by looking at the code I was not able to find this reason, except that it was a little easier to do it that way. On the topic of breaking compatibility, I agree that it may cause some problems, so we may want to wait for 3.5 or even 4.0.

**Comment by golddotasksquestions** [comment]
>Except it does pass the input, but under different rules than most people think. 

Except when it does not. Like in https://github.com/godotengine/godot/issues/55432 or https://github.com/godotengine/godot/issues/54529

The definition of a bug is not when something works, but when it does not.

**Comment by groud** [comment]
Closing as superseded by https://github.com/godotengine/godot/pull/61088.
Sorry this was not reviewed in depth before (and I did not see it :/), as the new implementation is quite similar.

**Pull request closed without merging**
