### PR TITLE
fix #22136 JavaClassWrapper.wrap should be ok

### LINKED ISSUE #22136: JavaClassWrapper.wrap() doesn't seem to work
Basically JavaClassWrapper.wrap() has never worked. But it is tempting for people trying to get access to Android Classes. I did manage to the the java classes from the function by returning the correct value a modification I made to Godot code. But even then, it seems that the class deletes too many references which makes the Java Class holo which is still useless.
I think it could work great as the kivy project has something similiar in [pyjinus](https://pyjnius.readthedocs.io/en/latest/).
I would like to get this to work, but I need help because I do not know C++ much at all. 

**Godot version:**
ALL

**OS/device including version:**
Android

**Issue description:**
JavaClassWrapper.wrap() returns [Object:null] 
After patch it returns [JavaClass] but it seems to be holo, no class methods or class variables.

[Some proof that JavaClassWrapper.wrap() is actually getting a class from the JNI](https://gist.github.com/FeralBytes/c3a76dec37208c41798136653c5530e8).

### PR DESCRIPTION
**Pull request by zeze0556**
Class function called also should be ok
Class.new function also should be ok
All of function in plugins also should be visited.

### CODE REVIEW

**Comment by akien-mga** [comment]
Note:

- Once it passed the CI checks, you should squash those commits into one, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase).
- Once approved, a matching PR for the `mastee` branch will be needed, as we don't merge fixes in `3.2` if the bug remains in 4.0+.

**Comment by m4gr3d** [comment]
@zeze0556 Can you clarify what this PR attempts to do.

**Comment by zeze0556** [comment]
> @zeze0556 Can you clarify what this PR attempts to do.

for android platform, the JavaClassWrapper.wrap api not work, the patch will fixed it

**Comment by akien-mga** [comment]
It's difficult to evaluate this PR as it's still not clear what the problem is that it's fixing. It's being describe as that "JavaClassWrapper.wrap does not work" but we would need to know how you're using it and what you expect / what doesn't work to be able to review and test this properly.

**Pull request closed without merging**
