### PR TITLE
GDScript: Fix crash in disassembler

### PR DESCRIPTION
**Pull request by dalexeev**
* Fix crash due to missing `& ADDR_MASK`.
* Add missing `ADDR_TYPE_STATIC_VAR` mode.
* Improve printing of scripts and values.

test.gd:

```gdscript
class A:
    pass

func test():
    var v: Variant
    var a: A = v
```

Before:

```
$ bin/godot.linuxbsd.editor.dev.x86_64 --test gdscript-compiler bin/test.gd 
Could not load project settings.
Disassembling test()
 0: line 5:     var v: Variant
 2: line 6:     var a: A = v

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.dev.custom_build (2210111eb5e8bac6a476227c01205ac44745e21e)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0) [0x7fbdad63c4b0] (??:0)
[2] Variant::reference(Variant const&) (/home/danil/godot-src/core/variant/variant.cpp:1070)
[3] Variant::Variant(Variant const&) (/home/danil/godot-src/core/variant/variant.cpp:2926)
[4] GDScriptFunction::disassemble(Vector<String> const&) const (/home/danil/godot-src/modules/gdscript/gdscript_disassembler.cpp:367)
```

After:

```
$ bin/godot.linuxbsd.editor.dev.x86_64 --test gdscript-compiler bin/test.gd 
Could not load project settings.
Disassembling test()
 0: line 5:     var v: Variant
 2: line 6:     var a: A = v
 4: assign typed script (A) stack(4) = stack(3)
 8: == END ==
```

### CODE REVIEW

**Comment by adamscott** [comment]
@vnen Can you check if this looks good for 4.1?

**Comment by dalexeev** [comment]
Note that after #77129 a small change will be needed. The disassembler is not a critical part of GDScript and is mainly used by us for debugging purposes. So it doesn't really matter when it will be merged.

**Comment by adamscott** [comment]
Let's wait then for #77129 to be merged first.

**Review by akien-mga — APPROVED** [review]
TIWAGOS review, but since the disassembler is a tool for engine developers, I'm fairly confident merging @dalexeev's work after a cursory review.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
