### PR TITLE
Add advanced tag to class, hide visual nodes classes under it

### LINKED ISSUE #55267: The problem with VisualShader/VisualScript nodes count
### Godot version

3.4 / 4.0

### System information

W10

### Issue description

Soo this has bothered me for a while, but we have a huge number of exposed classes for VisualShader/VisualScript. Each visual node has its dedicated resource type, which is overkill.

My main problem with this is that each of these nodes can be documented, but no one really bothers to do it and it impacts doc completion. I once made a PR that documented "all" VisualShader nodes, but before it was merged even more nodes were already added.

With VisualScript it's a bit better, because the nodes are edited in the inspector and you can actually see their documentation. But for VisualShader it's not the case; the docs aren't displayed anywhere and also VisualShader editor has its own description for every function. So documenting everything is pointless, but then we end up with empty docs.

Assuming this is a concern, is it maybe possible to unexpose the nodes? They could be internal classes and the actual node (the one saved in the scene) would only hold information about what type it is and and the property list would depend on that. This way we could have single class for VisualScript/VisualShader, so the class ref isn't so cluttered.

### Steps to reproduce

Just look at this
4mojLMKP2G

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
My attempt to fix https://github.com/godotengine/godot/issues/55267

core_advanced_classes2

### CODE REVIEW

**Comment by KoBeWi** [comment]
The idea is good, but I wonder if it can be done simpler. Right now it modifies every single class.

Also not sure if "Advanced" is a proper name for this. The hidden classes aren't really advanced, they are just not important and cause clutter.

**Comment by Chaosus** [comment]
> The idea is good, but I wonder if it can be done simpler. Right now it modifies every single class.

I can remove the generating doc part and it will not add this extra string to the doc header.

**Comment by fire** [comment]
I like the use of "Advanced", we used this in the settings menu.

**Comment by KoBeWi** [comment]
But it's completely unrelated here.

**Comment by Gallilus** [comment]
First question, what are the criteria for being an advanced Class?
It seems real subjective to me.

**Comment by fire540** [comment]
Since it isn't exactly obvious what "Advanced Items" means, a tooltip should be added to the button with a short explanation of what an advanced item is.

Also, if they aren't already, the "GLTF..." resources should be included in Advanced Items. They don't have any documentation, and if I'm not mistaken, they don't have any use outside of the GLTF importer and exporter.
image

**Comment by KoBeWi** [comment]
> First question, what are the criteria for being an advanced Class?
Since it isn't exactly obvious what "Advanced Items" means

This is why the option was renamed to "Hidden Items". The GIF is outdated.

**Comment by Gallilus** [comment]
I whas tinking of filtering these items insider visualscriptpropertyselector. Not as a marker insider the class itself. 

For visual script and visual shader these will be different.

**Comment by Chaosus** [comment]
Ok, I will remake it using the "hack" inside the document viewer.

**Pull request closed without merging**
