### PR TITLE
Make the Import dock depend on the FileSystem dock for editor feature profiles

### PR DESCRIPTION
**Pull request by aaronfranke**
The Import dock is useless without the FileSystem dock, so the Import dock should be hidden when the FileSystem dock is hidden. We also want to show this visually, so I made the Import dock checkbox TreeItem a child of the FileSystem dock checkbox TreeItem.

This also fixes a bug where previously the "FileSystem Dock" checkbox was named "FileSystem and Import Docks", but the checkbox did not actually control the Import dock.

Old:

Screenshot from 2020-05-08 16-28-16

New:

Screenshot from 2020-05-08 16-25-52

### CODE REVIEW

**Comment by YeldhamDev** [comment]
This is incorrect. Unless something changed in the master branch, the "FileSystem and Import Docks" does control both docks.

**Comment by aaronfranke** [comment]
@YeldhamDev What do you mean? On my end in Godot 3.2.1, disabling "FileSystem and Import Docks" doesn't hide the import dock, it's still there.

**Comment by YeldhamDev** [comment]
@aaronfranke That's odd. Both 3.2.1 and master works correctly here.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
