### PR TITLE
Add more array methods: first_custom, last_custom, count_custom

### PR DESCRIPTION
**Pull request by SlashScreen**
I added 3 new methods to the Array class: 

`first_custom(fn:Callable)` will return the index of the first element of an array where the callable `fn` will return true.
`first_custom(fn:Callable)` will return the index of the last element of an array where the callable `fn` will return true.
`count_custom(fn:Callable)` will return the count of all elements of the array where the callable `fn` will return true.

I added these because I found myself needing them a lot, and was frustrated by having to implement them myself a lot. I thought other people would find them handy.
I attempted to keep them in the same naming style as other functions in the class, although in my ideal world, they would be called `sort_by`, `first_by`, `last_by`, `count_by`. But it's a little late for such a naming convention shift now without making aliases.
Should this PR be accepted, I will write documentation for it on the docs repo.

Also, I kind of borked the whole `git commit --amend` thing and ended up in merge conflict hell and accidentally committing a bunch of other files, and I don't know how to fix it. Only `array.cpp` and `array.h` are changed.

### CODE REVIEW

**Comment by RandomShaper** [comment]
I think this warrants a proposal about the idea of adding predicate-taking utility methods. Maybe that should be solved in GDScript or maybe in the core, as this PR does, but then the API should be discussed further to make it uniform across other types that may be included in the scope of this.

That said, I was a fan of JS's functional style array methods. I only would like this to be thoroughly discussed so we can do it the beat way possible.

**Comment by SlashScreen** [comment]
Fair point, I'll open a suggestion there.

**Comment by dalexeev** [comment]
Instead of `first_custom` and `last_custom`, I would suggest `find_custom` and `rfind_custom`, for consistency with the existing methods.

**Comment by SlashScreen** [comment]
Closing this for now, going to instead discuss in proposals before continuing. And fix the git repo.

**Pull request closed without merging**
