### PR TITLE
Improve grammar in Array documentation

### PR DESCRIPTION
**Pull request by curious-broccoli**

### CODE REVIEW

**Comment by AThousandShips** [comment]
Can you please squash your commits, per our [guidelines](https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase)

**Comment by adamscott** [comment]
@curious-broccoli Hi! Thanks for your first contribution, it's very appreciated. I suggest you follow @AThousandShips's suggestion and review our guidelines. After squashing your commits, we'll be able to merge your PR.

Thank you!

**Comment by curious-broccoli** [comment]
Ignore that ^ , I'm working on it 😆

**Comment by curious-broccoli** [comment]
Done 🙃

**Comment by fire** [comment]
I modified the comment title to be descriptive to your changes.

**Review by Mickeon — COMMENTED** [review]
This has been a-okay for a long while now, but it would be superseded by https://github.com/godotengine/godot/pull/69451 that completely changes the example.

**Pull request closed without merging**
