### PR TITLE
Icon design update to make visual shader toolbar more clear

### PR DESCRIPTION
**Pull request by eobet**
- GridMinimap icon changed to remove the grid and instead add a minimap and make the map marker more clear (the motivation was that I constantly confused the mini map icon with the two grid setting icons in the visual shader editor).
- GridToggle & SnapGrid icons changed to replace the grid lines with dots, which closer reflects the default appearance of the visual shader editor and also makes the actual small corner symbols clearer (and reduces overall visual clutter/business which the lines caused).
- Both icons have had their color emphasis shifted to their corresponding small symbols and had the background elements toned down a bit more than previously using transparency.
Screenshot 2024-05-06 215221

### CODE REVIEW

**Review by Geometror — COMMENTED** [review]
Looks great, there is just one thing:
The new minimap icon definitely goes into the right direction, but it does look a bit out of place IMO. I'm not sure whether the map marker actually improves the recognizability.

**Comment by eobet** [comment]
> The new minimap icon definitely goes into the right direction, but it does look a bit out of place IMO. I'm not sure whether the map marker actually improves the recognizability.

Well, the old minimap icon also had the very same map marker... only so small nobody could make it out! 😉

**Review by Geometror — COMMENTED** [review]
What do you think about using just one color for the icon?
image
IMO that fits a tiny bit better, however I'm fine with it either way, so it's up to you :)

To make this PR mergeable, please squash you commits and rebase.

**Comment by eobet** [comment]
@Geometror I see what you mean with the all white color, but I'm afraid the navigation window will get lost then (I could make the border 1px, but I'm actually hoping that the arrange icon to the right could be updated with all 2px outlines too down the line). How about the one on the left here? (The test on the right got too close to the grid and snap toggle, imo.)

shader-navigation2

Also, I'm sorry but I'm very new at this and so far failed to find how to "squash and rebase" via the github website? Do you have a link to an instruction on how to do this?

**Comment by Calinou** [comment]
> Also, I'm sorry but I'm very new at this and so far failed to find how to "squash and rebase" via the github website? Do you have a link to an instruction on how to do this

See [Pull request workflow: The interactive rebase](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) in the documentation. This needs to be done from a local Git client – you can't do all the required steps from the GitHub website.

**Comment by eobet** [comment]
@Calinou thank you for the link. Unfortunately I'm a designer and not a developer so I did not understand even a fraction of those instructions, so I'm afraid my participation have to end here.

If anyone wants to take my icons and "rebase" themselves, they're free to do so.

@Geometror if Godot ever allows the minimap location to be changed, I really, really hope that can be reflected in the icon as well (using multiple icons, probably).

**Pull request closed without merging**
