### PR TITLE
EditorNode: add floating dock

### PR DESCRIPTION
**Pull request by ghost**
Edit: related to #5473

Enable in `docks/floating_docks/*` (Disabled by default)

Distraction-free mode is great, but I can't quickly reach the docks without turning it off.

Known issues:
1. Toggling `interface/floating_docks` will make editor unusable, must relaunch first.
2. Can't drag dock's edge to resize
3. ~~Docks can't be kept open to signify editor events (i.e. double-click resource to edit)~~
4. ~~Dragging file from one dock to another doesn't work?~~
5. The old `editor_layout.cfg` might have to be deleted first

It's still very rough. I'm not sure if this feature is desired. Please test/review. Thank you.
Also I don't think 'floating' is the right term. I can't think of anything better right now.

Screencast:
https://cdn.discordapp.com/attachments/319449314902671360/333635010286452736/2017-07-09_22-44-42.mp4

### CODE REVIEW

**Comment by kubecz3k** [comment]
woah this is cool :+1:

**Comment by vnen** [comment]
I can't use the editor like that, but it may be useful for people with small screens.

**Comment by Noshyaar** [comment]
It's difficult to know what the users actually want to see implemented, and I'm afraid that people wouldn't want this at all & waste of time so I haven't added much features yet. (Also the current editor node is a bit tricky to work with, some node reparenting must be done first, before adding more options, to smoothen the process.) Per-dock behavior will be implemented in later commits.

**Comment by Noshyaar** [comment]
Latest commit adds more settings, including floating only one side (left or right). Double-click a resource file will force open inspector until mouse is hover above it. Floating docks settings are moved to `docks/floating_docks/*`. This might be the last commit before the PR merge meeting.

TODO:
- floating dock resizing
- make it work without relaunching
- make stylebox/hsplit consistent with godot ui

**Comment by toger5** [comment]
The way it is implemented currently might not be used a lot since ppl can just toggle distraction free mode. which has more or less the same effect.

what use cases are you thinking of where this is better than distraction free toggle?

**Comment by Noshyaar** [comment]
> Distraction-free mode is great, but I can't quickly reach the docks without turning it off.
Also I don't think distraction free mode can do this.
Screencast:
https://cdn.discordapp.com/attachments/319449314902671360/333865608779399168/untitled.mp4

**Comment by toger5** [comment]
@Noshyaar The video you linked is really good. made me understand what exactly it is!
I can see how that can be useful!

**Comment by reduz** [comment]
This PR is a ton of lines of code in a file that is already pretty bloated for a feature that might not be that needed, apologies but I prefer to skip it.
Once we add multiple window support and EditorNode gets refactored, we can see how to do this properly by then in a less hacky fashion.

**Comment by reduz** [comment]
There is Edit -> Expand to Parent 
Your PR is fine and makes more sense there, but just delete the old option in the Edit menu.

**Comment by Noshyaar** [comment]
Closing this for now

**Pull request closed without merging**
