### PR TITLE
Update Bullet physics to commit 126b676

### LINKED ISSUE #24514: Update Bullet physics source
**Godot version:**

3.1

**Issue description:**

I have a problem with the Generic6DOFJoint which is related to a [bug](https://github.com/bulletphysics/bullet3/issues/2000) in Bullet physics that was fixed in [this pull request](https://github.com/bulletphysics/bullet3/pull/1999) (Merged 26 days ago). So I am wondering if there is a possibility to update the Bullet source or at least how can I do it in my own fork.

### PR DESCRIPTION
**Pull request by OBKF**
Update Bullet physics source to the latest commit 126b676 (01/01/2019).

I did some testing and everything looks fine.

_Bugsquad edit:_ fix #24514

### CODE REVIEW

**Comment by OBKF** [comment]
@AndreaCatania Here we go, please review it.

**Review by akien-mga — COMMENTED** [review]
Changes look fine, but you need to update `thirdparty/README.md` with the hash of the commit used to sync.

**Comment by akien-mga** [comment]
> Changes look fine, but you need to update thirdparty/README.md with the hash of the commit used to sync.

I pushed an amend to do this.

**Comment by akien-mga** [comment]
Thanks!

**Comment by OBKF** [comment]
I am glad I could help, and sorry for being late, I was a bit busy.

**Comment by akien-mga** [comment]
@OBKF I hadn't noticed, but this is actually the [2.88](https://github.com/bulletphysics/bullet3/releases/tag/2.88) release? Do we still have any custom changes, or does that mean we can now enable building against system-provided Bullet >= 2.88?

**Comment by OBKF** [comment]
@akien-mga I didn't noticed that too, and I didn't change anything. I just updated the source and tested the build that worked just fine.

**Comment by akien-mga** [comment]
Seems like you just pick the one commit that eventually was tagged as 2.88 :D Pretty cool coincidence, we should stick to it for now so that distros can build against their system's Bullet.

**Comment by OBKF** [comment]
Wow, what a coincidence, I remember that I had to pull a lot of data from github even though I updated my branch 2 days before.

**Pull request merged**
