### PR TITLE
advanced string format

### PR DESCRIPTION
**Pull request by AlexHolly**
see #5649

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Hm, there is a slight inconsistency:
```gdscript
print("{{key}}".format({"key": "pr", "pr": 1070}))
print("{{key1}}".format({"key1": "pr", "pr": 1070}))
```
Results in:
```
1070
{pr}
```
Either both should result in the first, or both in the second, I think (unless it would kill the performance too much).

**Comment by AlexHolly** [comment]
I think it has something to do with the order of the elements in the dictionary/Array.
In Java a HashMap is unordered in godot it looks a bit inconsistent.

This looks ordered
```
print({"key": "pr", "pr": 1070})
print({"key1": "pr", "pr": 1070})

```
Result
```
(key:pr), (pr:1070)
(key1:pr), (pr:1070)
```

But when the iteration is running they are processed in this order
```
print("{{key}}".format({"key": "pr", "pr": 1070}))
print("{{key1}}".format({"key1": "pr", "pr": 1070}))
```

```
key
pr
pr
key1
```


Maybe it has something to do with this?

https://github.com/godotengine/godot/pull/7010/files#diff-42dcdaccb893d2e564614de2467baddcR2953

It works with an Array

```
print("{{key}}".format([["pr", 1070], ["key", "pr"]]))
print("{{key}}".format([["key", "pr"], ["pr", 1070]]))
print("{{key1}}".format([["key1", "pr"], ["pr", 1070]]))
```

Maybe I could add some exhausting mode so that the order doesn't matter.

**Comment by bojidar-bg** [comment]
@AlexHolly Well, no exhausting order can handle this:
```
print("{a}".format({"a": "{b}", "b": "{a}"}))
```

**Comment by bojidar-bg** [comment]
Also, minor issue (or a non-issue, if you say), doing this:
```
var some_var = method("do_stuff", 0)
return "some_var is {0}".format([some_var])
```
would result in `"some_var is {0}` if `some_var` is an array with two elements (for whatever reason).

**Comment by AlexHolly** [comment]
Example for the exhausting idea.

Each key can only be used once.

```
func _ready():
	
	#Test1
	var s = "{{key1}}"
	var values = {"key1": "pr", "pr": 1070}
	
	#Test2
	#var s = "{{key}}"
	#var values = {"key": "pr", "pr": 1070}
	
	#Test3
	#var s = "{a}"
	#var values = {"a": "{b}", "b": "{a}"}
	
	var something_changed = true
	
	while something_changed:
		something_changed = false
		for key in values.keys():
			if(s.find(key,0)>-1):
				s = s.replacen("{"+key+"}", values[key])
				values.erase(key)
				something_changed = true
	print(s)
```

Results

```
Test1
1070

Test2
1070

Test3
{a}
```

**Comment by neikeq** [comment]
Looks like Dictionary now keeps the insertion order (as of 0a59c3c)

**Comment by bojidar-bg** [comment]
Ok, I guess that's mostly mergable anyway :smiley:

**Pull request merged**
