### PR TITLE
[3.2] Add a minimap to the GraphEdit

### PR DESCRIPTION
**Pull request by YuriSizov**
The 3.2 version of #43416. This includes #44469.

As the opacity is working in 3.2, here's how it was supposed to look in the original PR:

image

/cc @akien-mga

### CODE REVIEW

**Comment by pycbouh** [comment]
Sorry for the mass review request, I've picked a wrong branch 🙁

**Comment by akien-mga** [comment]
Might need a force push to pass CI, the branch mixup somehow brought AppVeyor back from the dead.

**Comment by pycbouh** [comment]
> Might need a force push to pass CI, the branch mixup somehow brought AppVeyor back from the dead.

Yep, it helped, no more AppVeyor

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
