### PR TITLE
Check for method in attached scripts for Thread.start

### LINKED ISSUE #67088: Methods registered by GDNative script could not be used in threads
### Godot version

3.5.1.stable

### System information

Linux Devuan testing

### Issue description

I have a code with godot-cpp which defines method and run it in godot `Thread`. In 3.2 and 3.4 it works fine but in 3.5.1 in stopped to work with error:  

```
ERROR: Condition "p_method == StringName() || !p_instance->has_method(p_method)" is true. Returned: ERR_INVALID_PARAMETER
   at: start (core/bind/core_bind.cpp:2745)
```

As I've seen there was introduced check https://github.com/godotengine/godot/pull/56485 which doesn't check if method defined as attached script while `_start_func` checks `has_method` not only on instance but also on scripts.

### Steps to reproduce

Found it when testing my code https://github.com/o01eg/freeorion/commit/9f0292eb50cf3b50653e1d4ed3ec5bba71f57036 in CI.

https://github.com/o01eg/freeorion/actions/runs/3210475149 Ubuntu and Fedora rawhide with 3.2 and 3.4 godot passes test while manjaro with 3.5 godot fails.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by o01eg**
Fix #67088

### CODE REVIEW

**Comment by Chaosus** [comment]
Core changes like that should be made for 4.0 first, can you check whether it can be applied to it?

**Comment by o01eg** [comment]
@Chaosus 4.0 doesn't check method by name here https://github.com/godotengine/godot/pull/56484/

**Comment by o01eg** [comment]
For 4.0 looks like it should be `Callable` changed to accept script methods.

**Comment by o01eg** [comment]
Looks like 3.5.1 also check script instance in `has_method`. I need to dig it deeper.

**Comment by o01eg** [comment]
It's not needed. Issue was related to incompletely initialized objects.

**Pull request closed without merging**
