### PR TITLE
Fixes compile bug for Android template on Windows.

### PR DESCRIPTION
**Pull request by antonyjones67**
Update to compiling Android on Windows.

After much testing these version numbers and file links seemed to work for me.
1. Install Java SDK 6. Can be found at.
   http://download.oracle.com/otn-pub/java/java_ee_sdk/6u4/java_ee_sdk-6u4-jdk-windows-x64.exe?AuthParam=1437511929_e3d8ec6a4c6908ab727d2323a640cf67
2. Install latest Android-SDK.
   https://dl.google.com/android/installer_r24.3.3-windows.exe
   
   Using the SDK Manager.
   Install Android 4.4.2 API & Android 4.0.3 API
   Install Android SDK Build-Tools 19.1
   You may need to prune stuff so all you have is the above.
3. Install Android-NDK 9b.
   https://dl.google.com/android/ndk/android-ndk-r9b-windows-x86_64.zip
4. Install Apache Ant version 1.9.2
   http://archive.apache.org/dist/ant/binaries/

Previous documentation seemed to be accurate for the most part.

Make sure that the CommandPrompt window is Run As Administrator. Or things will crash.

"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" needs to be run so that platforms other than Android can be detected.

Pull request is required for this process to work.

### CODE REVIEW

**Comment by reduz** [comment]
you rock!

**Comment by antonyjones67** [comment]
Thank you, and thank you for Godot. :)

**Comment by jay3d** [comment]
Thanks for the fix!

I have did an internal fix for png neon and it actually compiles, you need to do those modifications:

diff --git a/drivers/png/filter_neon.S b/drivers/png/filter_neon.S
index 63a5d8c..3d1230e 100644
--- a/drivers/png/filter_neon.S
+++ b/drivers/png/filter_neon.S
@@ -24,7 +24,7 @@
 
 .macro  func    name, export=0
     .macro endfunc
-ELF     .size   \name, . - \name
+@     .size   \name, . - \name
         .endfunc
         .purgem endfunc
     .endm
@@ -32,7 +32,7 @@ ELF     .size   \name, . - \name
     .if \export
         .global \name
     .endif
-ELF     .type   \name, STT_FUNC
+@     .type   \name, STT_FUNC
         .func   \name
 \name:
 .endm

It seems like the android pre-processor is not picking up the define for ELF.

**Comment by antonyjones67** [comment]
will do thank you

**Comment by Kermer** [comment]
Windows 7
My android export template compiling looked like this:

- Installing Python, Scons, Android SDK, NDK. Setting up ANDROID_HOME and ANDROID_NDK_ROOT

- ***scons platform=android target=release***
 - After about a minute:
 `scons: *** [drivers\png\filter_neon.android.debug.o] Error 1`
 - **Fixed with this pull**
 - Now I have my `libgodot.android.opt.so` file

- ***ant release***
 - *“ant” is not recognized as an internal or external command, operable program or batch file.* Dang.
 - Searching what do I need to fix it, **downloading Apache Ant**
 - Trying again...
 - *Missing tools.jar in jre folder...* - copying it from jdk
 - Trying again...
 - `Android-SDK\tools\ant\build.xml:538: Unable to resolve project target 'android-19'`
 - Downloading **API19 and API15 SDK with Android SDK Manager**
 - WOW, it finally compiled! And there's my .apk file!
 - using my fresh, new, shiny android template to export my project...
 - AND IT DOESN'T WORK... (app instantly crash on run) \* surrender \* 

Windows is a troll

**Comment by d3v0x** [comment]
Post the output of $ adb logcat
Else it's hard to reproduce.

**Comment by alvin00221** [comment]
I have noticed you have java jdk with 64 bit.. meaning it is only works for 64bit not for 32 bit?  hope i can also compile android template using may windows 7 32 bit.. coz i always encounter error.. im plannning to switch again to unity because of compiling template.. haaay! :(

**Comment by alvin00221** [comment]
still have an error :(

**Comment by alvin00221** [comment]
still have an error :(

**Comment by alvin00221** [comment]
C:\godot-master>scons p=android
scons: Reading SConscript files ...

MSVC not detected, attempting Mingw.

could not detect gcc. Please, make sure a path to a Mingw /bin directory is accessible into the enviro nment PATH.
Godot Android!!!!!
scons: done reading SConscript files.
scons: Building targets ...
C:\android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt//windows-x86_6
4/bin/arm-linux-androideabi-g++ -o platform\android\os_android.os -c -DNO_STATVF
S -MMD -MP -MF -fpic -ffunction-sections -funwind-tables -fstack-protector -fvis
ibility=hidden -D__ARM_ARCH_7__ -D__GLIBC__ -Wno-psabi -march=armv6 -mfpu=neon -
mfloat-abi=softfp -ftree-vectorize -funsafe-math-optimizations -fno-strict-alias
ing -DANDROID -Wa,--noexecstack -DGLES2_ENABLED -D_DEBUG -g1 -Wall -O0 -DDEBUG_E
NABLED -fno-exceptions -DNO_SAFE_CAST -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DDEB
UG_MEMORY_ALLOC -DANDROID_ENABLED -DUNIX_ENABLED -DNO_FCNTL -DMPC_FIXED_POINT -D
MUSEPACK_ENABLED -DOPENSSL_ENABLED -DSQUISH_ENABLED -DVORBIS_ENABLED -DPNG_ENABL
ED -DDDS_ENABLED -DPVR_ENABLED -DJPG_ENABLED -DWEBP_ENABLED -DSPEEX_ENABLED -DGD
SCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DETC1_ENABLED -DOPENSSL_NO_ASM -
DOPENSSL_THREADS -DL_ENDIAN -Icore -Icore\math -Itools -Idrivers -I. -Iplatform\
android -IC:\android-ndk-r10e\platforms\android-15\arch-arm\usr\include -IC:\and
roid-ndk-r10e\sources\cxx-stl\gabi++\include -IC:\android-ndk-r10e\sources\cpufe
atures -Idrivers\builtin_openssl2 -Iplatform\android\vorbis -Idrivers\builtin_op
enssl2\crypto -Idrivers\builtin_openssl2\openssl -Idrivers\builtin_openssl2\cryp
to\evp -Idrivers\builtin_openssl2\crypto\asn1 -Idrivers\builtin_openssl2\crypto\
modes platform\android\os_android.cpp
scons: *** [platform\android\os_android.os] The system cannot find the file spec
ified
scons: building terminated because of errors.

**Pull request merged**
