### PR TITLE
Add button_rmb_pressed signal in Tree

### PR DESCRIPTION
**Pull request by trollodel**
This is necessary to implement #27813.

### CODE REVIEW

**Review by KoBeWi — CHANGES_REQUESTED** [review]
The signal should be called `button_rmb_pressed`, to be consistent with other rmb signals.

**Comment by Calinou** [comment]
As a more scalable solution, shouldn't we keep the existing signal and send the mouse button index as a parameter to the signal?

**Comment by trollodel** [comment]
I have thought the same, but since there are similar signals in Tree and I need only the one exposed here for #27813, I preferred to open this tiny PR.
However, I agree that all the rmb signals should be replaced by a parameter.

**Comment by groud** [comment]
> As a more scalable solution, shouldn't we keep the existing signal and send the mouse button index as a parameter to the signal? This way, the middle mouse button can also be detected.

I agree with this. I would prefer having this added as a parameter.
It's ok if we break compatibility here, it's not a big deal IMHO.

**Comment by trollodel** [comment]
Superseded by #47665.

**Pull request closed without merging**
