### PR TITLE
Fix a typo in `OPCODE_CALL_GDSCRIPT_UTILITY`

### PR DESCRIPTION
**Pull request by CrezyDud**
lol

### CODE REVIEW

**Comment by Xrayez** [comment]
Fixing a typo is easy, but it would be nice to have a cleaner commit history as well. 😉

**Comment by CrezyDud** [comment]
> Fixing a typo is easy

as if not

> but it would be nice to have a cleaner commit history as well.

l o l

> Please be more descriptive when making changes, even for small things like fixing a typo.

i wanted to, but i thought, why when it's so simple


so here:

Fixing a type in OPCODE_CALL_GDSCRIPT_UTILITY

where a string wrongly said call-gscript-utility instead of call-gdscript-utility

**Comment by akien-mga** [comment]
> Fixing a typo in OPCODE_CALL_GDSCRIPT_UTILITY

That would be a great commit message indeed (more detail is not necessary). Could you amend the commit message with `git commit --amend`? See https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

**Comment by pycbouh** [comment]
@CrezyDud You need to squash your commits so that only one is left with the proper message. And please, for everyone's sake, try to submit better phrased and explained pull-requests in future, including the title and the description on GitHub.

**Comment by CrezyDud** [comment]
i wanted to name the pull request like this( Fix a typo in OPCODE_CALL_GDSCRIPT_UTILITY) but i thought it looked clickbaty with caps

**Comment by pycbouh** [comment]
Well, you have to consider if the title and the commit message are factual and descriptive, but not too verbose. Not sure how the word "clickbait" would apply to GitHub issues, but an example of a title named in bad faith would be "Fixed that awful issue in your crap code", or "Finally implemented this feature everyone wanted you to make for years". Stating that you've fixed a bug and where it was is not that, it's safe and correct.

**Comment by pycbouh** [comment]
That's what the variable is called, it's OK.

**Comment by CrezyDud** [comment]
don't know how to do that sublime merge errors, and github desktop
and command line tried out, but nothing fits in my brain right now

**Pull request closed without merging**
