### PR TITLE
Add `FileAccess::get_access_time()`

### PR DESCRIPTION
**Pull request by RandomShaper**
This code is generously donated by IMVU.

### CODE REVIEW

**Comment by akien-mga** [comment]
@RandomShaper It doesn't compile. https://travis-ci.org/godotengine/godot/builds/618547338?utm_source=github_status&utm_medium=notification

**Comment by RandomShaper** [comment]
@Akien, errors fixed.

**Comment by akien-mga** [comment]
Could you describe the use case for this feature?

**Comment by RandomShaper** [comment]
To ne honest, I can't think of any that is of general interest. Closing.

**Pull request closed without merging**
