### PR TITLE
Fix theme editor is opened only once

### LINKED ISSUE #97278: The theme editor is opened only once
### Tested versions

4.3 stable, 4.4 dev2

### System information

Godot v4.4.dev2 - Windows 10.0.19045 - OpenGL 3 (Compatibility) - Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

When we create a new theme for any Control node, clicking on the resource opens the theme editor, then if we close this editor, the theme editor can no longer be opened by clicking on the resource in the inspector.
scr

However, we can open the theme editor if we select the theme in the file manager

### Steps to reproduce

1. Create a new theme for any Control node
2. Select this theme in the inspector to open the theme editor
3. Close the theme editor
4. Repeat step 2 and the theme editor will not open

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by shahriarlabib000**
Doesn't cIose #97278

### CODE REVIEW

**Comment by AThousandShips** [comment]
This isn't a complete solution, this makes *only* the theme editor work like this, and no other resource editor, like shaders, which work the same way

**Comment by shahriarlabib000** [comment]
shader editor doesn't have a close button tho

**Comment by AThousandShips** [comment]
Yes it does? It's a bottom bar editor and all of them can be closed

**Comment by shahriarlabib000** [comment]
could you pls send a video 🥺. Couldn't really figure out how to close it

**Comment by AThousandShips** [comment]
Click the bottom bar where it says "Shader"

**Comment by shahriarlabib000** [comment]
Did you mean "Shader Editor" ? That doesn't really close like the "Theme Editors" close button works because that'll also hide the "theme" button from the bottom panel

**Comment by AThousandShips** [comment]
That's two different issues then, but it wasn't clear in the original thread wat OP meant by closing, so removing the link with that issue to discuss the behavior when closing the bottom bar specifically and keeping this for the close button

**Comment by shahriarlabib000** [comment]
https://github.com/user-attachments/assets/b75e69f3-7ae6-497f-a80f-7535b2ea3b75

Did you mean this? I think that's intentional behavior.  Cause user closed it by themself and they can easily open that.

**Comment by AThousandShips** [comment]
No I mean clicking the "Shader Editor" button on the bar, the way to close any editor in the bottom bar

**Comment by shahriarlabib000** [comment]
Yes I did that before recording.
Also the theme editor respect if the user has closed the editor from bottom bar

https://github.com/user-attachments/assets/75b2c3ae-9e77-4bbd-9564-d7edd03c25be

**Comment by shahriarlabib000** [comment]
I thought op literally meant to hit the close button and close it so I didn't raise any questions either.

**Comment by JekSun97** [comment]
The problem is that if we close the theme editor (using the close button), then when we click on the theme in the inspector, the theme editor will not open again, for this we need to select any other node, and then Control with the theme again, then the theme editor will open again, you must agree, quite strange behavior

**Comment by shahriarlabib000** [comment]
Check out the artifact. One thing to keep in mind tho is if the theme in the editor is unfolded and you close the theme with the button, to open the theme again you'll need to fold and then unfold again to open the theme in the inspector

**Comment by KoBeWi** [comment]
This fix is wrong.
The bug is caused because closing Theme Editor does not remove it from active editors. I'm working on a proper fix.

**Pull request closed without merging**
