### PR TITLE
tinyexr: Update to 1.0.8

### PR DESCRIPTION
**Pull request by Chubercik**
https://github.com/syoyo/tinyexr/releases/tag/v1.0.8

Changelog: https://github.com/syoyo/tinyexr/compare/v1.0.7...v1.0.8

### CODE REVIEW

**Comment by Chubercik** [comment]
Also, not sure what to do with

https://github.com/godotengine/godot/blob/60b927b4cf0e3fb34a0b14ce9b6f9157e69dd549/COPYRIGHT.txt#L491

the copyright hasn't been updated since version 1.0.1, so I'm not touching it for now.

**Comment by akien-mga** [comment]
> Also, not sure what to do with
> 
> https://github.com/godotengine/godot/blob/60b927b4cf0e3fb34a0b14ce9b6f9157e69dd549/COPYRIGHT.txt#L491
> 
> the copyright hasn't been updated since version 1.0.1, so I'm not touching it for now.

Yeah that's correct, we follow whatever the upstream devs are doing with their copyright statements. If they don't update the year, we don't either.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.4.

**Pull request merged**
