### PR TITLE
Ignore null "id" in tile source proxy

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes "a number is required" error.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Is it not needed on the line 996 as well?

**Comment by KoBeWi** [comment]
It's not, but there might be some underlying issue here. The error appears, because the first "id" value is null. Actual numbers don't need explicit casting.

**Comment by KoBeWi** [comment]
I pushed an alternate fix.

**Review by akien-mga — APPROVED** [review]
Seems good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
