### PR TITLE
[3.x] Backport KinematicBody move_and_slide and move_and_collide fixes

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
Backport #49901 and #50063 to 3.x.

These two PRs together make both `move_and_collide` and `move_and_slide` more reliable and after running a lot of tests (see original PRs for details) I'm confident they won't cause major regressions.

Co-authored by @fabriceci 
Supersedes #49902

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Needs a rebase, otherwise seems good to go.

**Comment by pouleyKetchoupp** [comment]
@akien-mga Thanks, it's rebased.

**Comment by akien-mga** [comment]
Thanks!

**Comment by elvisish** [comment]
Would it be possible to consider this for an update to `move_and_slide`? https://github.com/godotengine/godot-proposals/issues/2751

**Comment by crapaam** [comment]
Hi. I have a little platformer game. the player moves with move_and_slide_with_snap. it works fine with godot 3.3.3 and 3.3.2, but got problems with 3.4 b4. The problem is when the player is over a platform that moves from side to side, the platform moves, but the player do not. The platform is made with a tileset. The static body is made with the tileset to and moved with an animation player. Thanks

**Comment by pouleyKetchoupp** [comment]
@crapaam Hi! Please open an issue with a test project so someone can investigate the regression.

**Pull request merged**
