### PR TITLE
Remove viewport restrictions in 2D editor

### LINKED ISSUE #2139: Make viewports/containers usable inside Godot, improve viewport documentation and make it simpler to actually use viewports
### Describe the project you are working on
2D Platform

### Describe the problem or limitation you are having in your project
As soon as you use a viewport you lose any and all abilities to edit and manipulate the contents and in addition there is almost no documentation on how viewport contains and viewports function in order to use them, i.e. add a viewport to your 2D game and you cannot edit properly.

Consider the following simple scene, which is just a tilemap and a couple of sprites
image

Add a viewport as per the documentation and as soon as you do, everything disappears both in the editor and runtime, you have no means of editing, even after the viewport is sized. I appreciate 'viewportcontainer' was created, but the documentation does not say it has to be a parent, simply the viewport will take it's size. 
image

Regardless of this missing documentation, and why a container is actually required, add a viewport container:

image

You still get no ability to view or edit your scene, although it does now show at runtime, i.e. you have no means of editing. In addition, the viewport container seems completely pointless, why is it set as a 40x40 box on the screen when all it does is host viewports and auto sizes?

Anyway, if you create a Scene from the stuff in your viewport, then magically it becomes 'visible', but there is no means of editing unless you go inside the branch, so why is the scene file rendering at all when you weren't allowed to see it before?

image

At this point you're saying, well that's fine, save it as a branch and you can edit it. But what if there are other objects in your viewport? there is no means of editing them, seeing them, moving then or seeing how they work with the other elements, i.e. in this case the tilemap is there but all the sprites are now invisible

image

Now, go back and remove that viewport container and viewport. You can view all the objects, you can see them together and you can move them together.

image

image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
1. Make viewports visible within the editor
2. Allow editing of items within a viewport
3. Add some documentation to state viewports don't work without viewportcontainers
4. Allow viewports to be rendered when the contents are just nodes and not a scene file

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
I don't know, I do not know the internals

### Is there a reason why this should be core and not an add-on in the asset library?
Yes, because as soon as you add a viewport, your ability to create a game is severely hampered.

### LINKED ISSUE #20619: Can't move node inside Viewport
**Godot version:**
3.0/3.1-dev

**Issue description:**
When you place node (e.g. Sprite) inside a Viewport, it can't be moved in the editor - you need to manually change position in inspector. While with select tool this is understandable behavior, because your viewport display node (ViewportContainer in my case) is selected instead of sprite, move tool doesn't work either.

**Steps to reproduce:**
1. Add a ViewportContainer (or any Control node)
2. Add Viewport as a child
3. Add Sprite to the Viewport and make sure it displays
4. Press W to select move tool
5. Try to move the Sprite
6. Spoiler: it won't move

**Minimal reproduction project:**
Contains aforementioned scene setup.
[TestProject.zip](https://github.com/godotengine/godot/files/2243026/TestProject.zip)

### LINKED ISSUE #60088: Layout preset buttons not showing for Window / Popup nodes and their children Control nodes
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Linux Pop!_OS 21.10, Nvidia GT710, Nvida X Server Settings 470.75.01

### Issue description

When we create a Window or a Popup node and we select them in the scene tree in the editor, they don't get the rectangle highlight and red circles to used to resize the nodes. The same happens to any of their children that inherit Control (probably other types too), and the buttons with the presets for anchors and sizing don't appear either, making it almost impossible to layout the GUI inside Window or Popup nodes.  It is possible to layout the GUI via the Inspector tab changing the property `layout_mode` to Anchors (when possible), but that's not very convenient.
The theme for those nodes don't seem to be working properly either.

### Steps to reproduce

Add a Window or any Popup node to the scene tree;
Add a Control as a child and some other node that inherits control as its child
Try to layout the GUI.

### Minimal reproduction project

[popup_test.zip](https://github.com/godotengine/godot/files/8457963/popup_test.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Attempt to solve the long-standing issue of not being able to move nodes inside another viewport.

At first glance it works great:
godot windows tools 64_TsolVuywxr

Things fall apart when the viewport container is moved:
godot windows tools 64_x6XAvVYo5U
Editor gizmos appear relative to the main viewport instead of the sub-viewport.

If the viewport isn't in a container, the offset doesn't appear, but the node doesn't appear either, even though you can edit it...
godot windows tools 64_eji2P9Zq88

And then there is Window, which has a position offset, but doesn't display anything:
godot windows tools 64_dSXtSZpOBw

So with this solution, you can edit nodes inside a sub-viewport without a problem, IF the sub viewport is inside a container, which is located at (0, 0). It works in other cases too, but the node isn't displayed correctly.

The main reason I opened this PR is #60088. Dialogs were changed from Control to Window, so their content can't be edited easily. IMO it's time to do something about the viewport issue. The PR lays some foundation, and we could think of some fix for the new problems. Mainly the offset problem. Edited nodes in sub-viewport should somehow be able to offset their gizmos based on the viewport position. Not sure if this is possible.

Resolves #20619
Fixes #60088 (content doesn't display, but technically you can edit it)
Closes https://github.com/godotengine/godot-proposals/issues/2139 (I think?)

### CODE REVIEW

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Seems good, needs rebase. I would still ask for a review to @groud.

**Comment by KoBeWi** [comment]
> Seems good

Which part xd I attached a few GIFs showing how much it is broken. The editor issues need to be resolved somehow, maybe by adding some helper methods for determining sub-viewport position. Sounds complicated, so I didn't even try yet >_>

**Comment by gaoshan0621** [comment]
Any updates?

**Comment by KoBeWi** [comment]
I opened a PR with alternative approach, which is more promising, but needs to be finished 🙃

**Pull request closed without merging**
