### PR TITLE
Add classes for random number generation (RNG)

### PR DESCRIPTION
**Pull request by lmbarros**
This is perhaps more a request for comments than a real pull request. I still have some doubts about how to do things the Godot way (see my questions below), but overall this is the design I'd personally like to see in the engine.

It is used like this:

```gdscript
var rng = RandPCG32.new()   # Or another RNG class, like Xoroshiro128Plus
rng.seed(1234)  # rng.randomize() also exists

n = rng.uniform_float(-1.0, 2.0) # uniform in interval [-1.0, 2.0]
n = rng.uniform_int(1, 6) # six-sided die
n = rng.boolean(0.1)  # 10% of chance of being true
n = rng.normal(-3.0, 2.0)  # Gaussian, mean = -3, std. deviation = 2.0
n = rng.exponential(2.0) # from exponential distribution with mean = 2.0
```

I believe the current random number generation facilities in Godot are good for simple use cases (and I'd say that they should remain available), but more "interesting" RNG usage needs something new. I had three main goals in mind:

1) Add a few more useful distributions beyond uniform.

2) Let the user create separate instances of the RNG algorithm, in order to generate different independent sequences (pretty useful for procedural generation of content).

3) Allow users to be sure that they can create reproducible pseudorandom sequences even between Godot releases.

The biggest open points and questions I still have are:

* Do you consider this design in general good for Godot?
   * One sub-question here: What about providing multiple RNG algorithms as I did? I think that choosing a RNG is a trade-off, so I like the idea of providing the alternatives and letting the user chose one. Providing one single `Rand` class would be simpler (which is good), but if we ever decide to replace the one algorithm with something else, my point 3 above is not achieved. And I like RNG algorithms, so my opinion *is* biassed :-)
* How to add tests for this? I am currently using a Godot project (https://github.com/lmbarros/GodotRandTest/ -- it is currently quite ugly, BTW) that calls my methods from GDScript and checks if the results are OK. However, in order to be able to make these tests, I was required to expose `Rand::random()` to GDScript, which otherwise I wouldn't.
* Sometimes it is useful to save the RNG state with a saved game (to avoid the save-reload-and-try-again "cheat"). I am a Godot beginner, so I don't know if there is any support or standard way for doing serialization or save games.
* The newer versions of the C++ standard have implementations of various RNG algorithms and random distributions. For some reason that beyond my own understanding I haven't used them here. Is the usage of these newer parts of the C++ standard library allowed or encouraged in Godot?
* I implemented this on Linux and didn't test anywhere else. There is nothing platform-specific here, but we may need to tweak the implementation a bit to make it compile everywhere.
 
----

Six RNG algorithms are provided: PCG32, Xoroshiro128+, two variations of
Mersenne Twister (MT19937 and MT19937-64), SplitMix64 and a simple LCG.
Different random distributions are provided: uniform (for integers and
floats), normal (Gaussian), exponential and Bernoulli (for generating
Booleans).

All algorithms and distributions are usable from GDScript.

The base `Rand` class contains the interface that must be implemented by
all RNG algorithms and the implementation of the different
distributions. Subclasses that implement each of the actual RNG
algorithms inherit the distributions. This way, new algorithms and new
distributions can be easily added, and every algorithm can be used with
every distribution.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Good work!

I think it would be more user-friendly to provide only one `Rand` class with a `set_algorithm()` method. A sensible default would be chosen and the user would be able to switch to another with a constant in the form of `Rand.ALGORITH_???`.

It would be nice as well to have useful overloads like for instance:
- `Rand.uniform_float()` as a shorthand for `Rand.uniform_float(0.0, 1.0)`;
- and `Rand.uniform_float(max)` as a shorthand for `Rand.uniform_float(0.0, max)`.

And maybe rename `uniform_float` to just `uniform` because every method is returning a `float`. Since the only exception is `uniform_int`, that is the only method name needing a suffix.

At last, I'm not sure about the convenience method `boolean()`. It's just syntactic sugar, isn't it? And with my proposal you could just wrtite `rng.uniform() < 0.1`.

I hope you find my suggestions useful.

**Comment by lmbarros** [comment]
Hi! Thanks a lot for the comments! Here are my thoughts:

* Concerning a `set_algorithm()` method: sure, it is doable and I think I agree that this would be more "user friendly" (I actually saw this being suggested in the [issue discussion](https://github.com/godotengine/godot/issues/7199)). I am honestly unsure about this point. I think it is very odd to allow changing the algorithm on the fly and it would increase the coupling between the RNG classes (which is bad). But when I think about the idea as whole, thinking about how to use it, there is a lot to like in it. I wouldn't refuse to implement the change. Let's wait for more opinions...
* `uniform_float()` already works as you suggested. I implemented this via default parameters, instead of different overloads, but the behavior is exactly the same.
* About changing the method names: I like your suggestion, but I think I'll wait for more opinions before changing. I am expecting some bikeshedding here :-)   (BTW, I am not attached o the names I used.)
* About `boolean()`: I think using it expresses the intent more clearly than the alternatives.

Cheers!

**Comment by RandomShaper** [comment]
I've had a look at your code and I've seen what you say about the default args. In fact, you've came up with a solution for it more clever than mine.

Yes, let's wait for more comments to make this a good as possible. This is something I have been missing in Godot.

**Comment by tagcup** [comment]
To me, so far, the generic random class looks good, except you'll need to drop all references to STL (Godot doesn't use STL at all). It opens up the possibility for easily building RNG modules.

However, I don't think providing multiple algorithms is a good idea. Yes, there are trade-offs, but users don't know about these. There is an entire academic field around RNGs (while being in physics, at certain point I was also involved with this at some point, working on quantum RNGs), and having talked to experts who implement RNG hardware, I know for sure this is not easy. 

There are standard randomness test suites, and some of the algorithms included fail them already. I don't see any algorithm in that list, that is qualitatively better than PCG in any regard, so I personally don't really see the point of including a zoo of PRNGs in the core.

I think there should only be two RNG implementations in the core. A good PRNG (PCG, or if you know a better alternative, that), and a good hardware RNG. These are different RNGs qualitatively, and I don't think Godot needs to provide a bunch of implementations for each.

**Comment by bojidar-bg** [comment]
@tagcup I agree that this PR has way too many algos in it, though I guess I would prefer 3 possibilities -- one slow but good PRNG, one bad but fast PRNG, and one hardware-provided (if possible, since I doubt it would be very easy to implement it).

~~@RandomShaper I would prefer to have `uniform_float`, since just `uniform` conficts with the shaders' uniforms.~~ Actaully no, if we go for `uniform_float`, we should also have `normal_float`, etc.

@lmbarros About `boolean`, could you rename it to `uniform_bool` or `rand_bool` or something else of that sort, since it would be more clear (IHMO)?

Also, please use `real_t` instead of `double`, esp. in return variables.
Also, use `ERR_COND[_V]` instead of `assert`, we don't want the whole godot crashing because a dev left an assert there.
I don't think we use `static_cast<double>(..)` in core -- AFAIK we use C-style cast `(double)..` or `double(..)`

Finally, I think it would be better (esp. with the `set_algorithm` method) to rename the class to `Random`, rather than abbreviate it to `Rand`.

**Comment by RandomShaper** [comment]
I will open a discussion about the C++ guidelines for Godot, beyond the
formatting: C++14/17 features, casting style (C-style casts are used but
are discouraged nowadays), RIIA, etc.

**Comment by bojidar-bg** [comment]
Ok, for what I've heard about C++14/17 features, they are currently discouraged in core, since we want to be able to build with quirky ancient compilers for some consoles.
Would you mind moving this discussion to some issue though? :smiley:

**Comment by lmbarros** [comment]
My view on some of the points so far:

* **Nobody seems fond of providing multiple algorithms.** I'll spend the weekend trying to get over my attachment to all those algorithms :-) Maybe this is a good plan: leave the same basic architecture, namely a `BaseRand` class, but with a single `Rand` subclass that is based on PCG32. If anyone ever needs a different algorithm, this someone can implement it as a C++ module and be happy. *If* we ever decide to replace the default algorithm, we can leave the old algorithm as an alternative subclass.
    * I don't think we need "one good and one fast algorithm". PCG32 is very good and very fast.
    * Concerning a "hardware-provided" RNG: I believe it is an overkill. Anyway, the architecture I am proposing would allow someone to create a C++ module implementing one (or add one to the core, whatever).
* **About class and method names:** For what I have seen in other communities, this always generate a lot of noise. Everyone has a different opinion. I think I'll not change anything for now, but if we achieve some consensus I'll be happy to change.
    * `Rand` x `Random`: One more option: `RNG`.
    * `boolean()`: I don't think that `uniform_bool()` is a good name, as the function allows to pass the probability of the value being true; it is not necessarily uniform. `rand_bool()` isn't bad IMO, but doesn't follow the same pattern as the other names. `bernoulli()` would be correct (that's the [distribution name](https://en.wikipedia.org/wiki/Bernoulli_distribution), after all), but I believe not many people will recognize the name.
* **Coding standards:** I'll change the points I think are less open to discussion (`real_t`, `assert()`...) and will wait the discussion go on a bit longer before changing others.
* **Additional features:** I forgot to mention before, but I think there are other useful features I haven't implemented so far. For example, drawing a random element from an array. Feel free to suggest things here.

**Comment by tagcup** [comment]
> I agree that this PR has way too many algos in it, though I guess I would prefer 3 possibilities -- one slow but good PRNG, one bad but fast PRNG.

@bojidar-bg There is at least one PRNG that is both fast and statistically good (PCG). PCG32 is faster than PCG64 for sure though.

@lmbarros Given that GDScript now uses 64-bit ints, I think we can switch to PCG64 with 128-bit state.

I would also suggest renaming `random` to `uint64`, which can use for example PCG64, and maybe provide a `uint32` function that uses PCG32 (aligned with @bojidar-bg suggestion) and remove max_random since the naming makes it clear the maximum for each function, and maybe a `float32` and `float64` to return floating point values between 0 and 1. I personally like Go's simple and descriptive [rand API](https://golang.org/pkg/math/rand/), which is very intuitive to me.

**Comment by tagcup** [comment]
@lmbarros `real_t` isn't the part of a coding standard, but rather controls the internal precision of various calculations (physics, linear algebra). I think you should rather define a different functions for 32-bit and 64-bit floats, and you can maybe add a separate function for `real_t` which wraps either of those, depending on whether `REAL_T_IS_DOUBLE` is defined or not.

**Comment by tagcup** [comment]
@lmbarros Hardware-based RNG could be relevant for networking and crypto (game saves etc) code. I'm not sure the current status of the network security issues, I believe it eventually end up being handled in the core, but nevertheless, making a hardware RNG accessible from GDScript could still be relevant.

On *nix, one can simply read /dev/urandom. For Windows, there is [CryptGenRandom API](https://en.wikipedia.org/wiki/CryptGenRandom).

**Comment by bojidar-bg** [comment]
@tagcup Would you be OK if another PR + issue implements hardware crypto? Asking since I think it would be slightly too much for a single PR, plus the review would delay it a lot...

**Comment by tagcup** [comment]
@bojidar-bg Sure, I mean, I'm just bouncing off ideas, it's not like I'm paying him to work on this PR :D

To me, even getting only the base random class with no implementations in is good.

**Comment by tagcup** [comment]
Just a few more ideas: I noted that Unity has some nice [utility functions](https://docs.unity3d.com/ScriptReference/Random.html) including [picking a random point on the sphere](http://mathworld.wolfram.com/SpherePointPicking.html), which might be nice to include.

**Comment by lmbarros** [comment]
@tagcup The PCG32 x PCG64 question brings some questions for me:

1. If I understand correctly, PCG64 needs 128-bit integers for its implementation. OK, it doesn't really *require* them, we can "emulate" 128-bit integers on the C++ side. I have no idea what would be the actual impact on performance. (I guess performance would be a problem for desktop targets, but might be for mobile. Don't some important mobile targets still use 32-bit processors? Maybe for these platforms, using 64-bit ints is already stretching their capabilities. But I know next to nothing about these platforms, I may be saying nonsense.)
2. GDSCript integers are signed, while the numbers produced by most RNG algorithms are unsigned. This is, in fact, an issue with my current pull request, as most algorithms are producing 64-bit uints and exposing them to GDScript as signed ints. (That's why I mentioned in before that I'd rather not expose the `random()` method to GDScript.) One solution would be to clear the signal bit in the C++ side, thus making the generator to effectively produce 63-bit (non-negative) random integers.

**Comment by bojidar-bg** [comment]
@lmbarros Well, we already use uint_64 around the code, so I'd assume it "just works" (frankly, it is the compiler who should worry about this, not you)

**Comment by tagcup** [comment]
@lmbarros 
1. [PCG code](https://github.com/rkern/pcg64/blob/master/pcg64.h#L90) already has a fallback code for compilers without `__int128` so we don't need to do anything. And it's nothing complicated, they just do multiplication and carry manually. It's "emulated" either way since we're not targeting a CPU with 128-bit registers anyway. But yes, the bottom line is, PCG64 is slower than PCG32. But PCG64 is more than two PCG32s because bits in two PCG32s don't mix, and [is excellent](http://www.pcg-random.org/pdf/toms-oneill-pcg-family-v1.02.pdf) statistical-quality-wise.

2. Yes, for example, the Go API has functions `int63` and `int31`, which can be implemented by simply masking out the sign bit as you said.

**Comment by tagcup** [comment]
There are benchmarks in the [PCG paper](http://www.pcg-random.org/pdf/toms-oneill-pcg-family-v1.02.pdf) on page 35, and I'm not seeing any worrying gaps in speeds between PCG64 and PCG32.

**Comment by lmbarros** [comment]
So, I just committed an update to the PR, based on the discussion so far:

1. Replaced all RNG algorithms with PCG64.
2. The two remaining classes are now named `BaseRandom` and `Random`.
3. Using C-style casts.
4. Not longer using `assert()`s or C++ stuff like `std::swap()`.
5. Using `int64_t`s (the signed ones) on the interface, as this is what
   the scripting interface uses.
6. Renamed `uniform_float()` to `uniform()`.

**Comment by tagcup** [comment]
Thanks! A few points:

* This code can be useful in general, so I would suggest keeping things unsigned. Sign problem is GDScript specific and can be handled in a wrapper function for GDScript. If you define function `int63()` and `int31()`, which you use those there.
* There is an inconsistency in naming: some function names purely refer to the distribution function (`uniform`, `normal`) and some purely refer to the data type (`boolean`)  and some mix those. I'm being repetetive about this, but since I haven't seen anything better so far, can you rather use the naming convention for functions in [Go's rand class](https://golang.org/pkg/math/rand/)? (I don't think you need to mention uniform by name, which corresponds to a distribution with identity kernel anyway).

**Comment by lmbarros** [comment]
@tagcup Good point about the signed x unsigned issue!

With regards to method names, as I mentioned other times, I am OK to change them to anything else, but I still have my preferences :-)

* The name for the distribution that generates Booleans is Bernoulli. I have named methods `bernoulli()` in the past (in other languages), and this would my personal choice. However, I don't think many people will recognize it, that's why I used `boolean()` instead.
* I don't think Go's naming scheme would be that nice for us.
   * Maybe we can use something *based* on Go's scheme, but not exactly the same. We don't need, for example, to mention the float type (`Float32`, `Float64`) in the method name, as in GDScript we have a single floating point type.
   * Still, I don't think we should add a `float` suffix to methods like `normal()` or `exponential()` which are continuous distributions anyway.
* I like being explicit about `uniform()` :-)

So, while I would be OK to change the method names, I actually like my names better than Go's. I think it is pretty consistent (with the exception of `boolean()`, mentioned above) and will lead to nice, clean user code. But, really, in the end of the day this all boils down to personal preferences.

**Comment by tagcup** [comment]
> bI am OK to change them to anything else, but I still have my preferences :-)

I'm not insisting on any kind of bikeshedding; just consistency and clarity. It doesn't have to be Go's naming, it's just an example of a consistent API. Right now, it's totally inconsistent (example: uniform_int returns int64_t which incorrectly reflects the type given that int is also a C++ type, and uniform returns a double which doesn't even mention the type).

> as in GDScript we have a single floating point type.

I'm reiterating this point many times, but let's forget about GDScript. Let's think of this as a class for C++. You can handle GDScript limitations in the wrapper, which can have a has-a relationship with the BaseRandom class.

In C++, we're going to need functions for float, double and real_t (real_t function should use float or double variant depending on whether REAL_T_IS_DOUBLE is defined). So can you please put the type name in all functions including integers? The alternative is removing type names everywhere, but in C++, we can't overload functions based purely on their return type.

> The name for the distribution that generates Booleans is Bernoulli. 

Actually, can you remove that? Adding binomial should be fine, but Bernoulli is way too trivial to be in the API. Providing functions that return values between 0 and 1 (Float64 and Float32) is enough.
(this will also going into extremely large values where floats get less precise as in the current implementation: `return (double)(random()) < (double)(max_random()) * p_p`)

> I like being explicit about uniform() :-)

I think it will confuse people who don't know any real statistics (which is the majority of programmers) and just want a random value.

Also, can you change the implementation of `uniform_int` such that it returns a value in the default interval? You can add an additional function for intervals, but that shouldn't be the default.

**Comment by tagcup** [comment]
Reducing the number of random bits to 63 should also be in the GDScript class only.

**Comment by lmbarros** [comment]
OK, I was indeed focusing on the GDScript side (Godot newbie here, I thought that this is what mattered).

Having a specific class just to wrap the `Random` class to GDScript is a larger change, so please help me to understand what you have in mind a bit better. Currently we have:

* `BaseRandom`: Defines the interface that concrete RNG implementations need to provide and implements the different distributions.
* `Random`: Extends `BaseRandom`, provides the PCG64 implementation and is exported to GDScript. In the current implementation, this would be the class to be used also in the C++ side.

So, if I understood your suggestion, we would have a third class, something like

* `GDScriptRandom`: Wraps a `Random`, exports it to GDScript.

But then, stupid question perhaps, can I export it to Godot named as `Random`? I mean, if I keep doing as I do now (`ClassDB::register_class<GDScriptRandom>();`) we would end up with this weird named class in GDScript.

(A better alternative to this would be to use `Random` to name the GDScript class, and use something like   `RandomPCG64` in the C++ side. But, if possible, using the same name in both C++ and GDScript would be preferable, IMO.)

**Comment by bojidar-bg** [comment]
@lmbarros What is exposed to GDScript is the ClassDB-bound methods, which are based on Variant APIs. C++ need not use them (and it rarely does).

For an example, `Object::get_property_list(List &p_list)` is not exposed to GDScript directly, nor is bound to ClassDB, but it is called directly from all over the editor code. `Array Object::_get_property_list()`, on the other hand is exposed as `get_property_list`, is slower, and is (probably) never called from C++.

Now, you can't really bind `uniform_float` and `uniform_double` methods to ClassDB, since it would have to cast them to `Variant` on the way, which would eventually mean casting into `real_t` (if I remember right). So, in the end, both methods would end up returning `real_t` to GDScript.

What @tagcup is trying to say is that those methods are still going to be useful around `scene/` and `modules/`, since we don't want to keep some calculations in `real_t`, but instead specify doubles and floats (e.g. light baking should work in doubles always, since it has no use of floats when precision matters).

Just my $0.02 (or €0.02)

**Comment by lmbarros** [comment]
Hi,

> What is exposed to GDScript is the ClassDB-bound methods, which are based on Variant APIs

What I I've been following since the beginning is the documentation on [Custom C++ modules](http://docs.godotengine.org/en/stable/reference/custom_modules_in_c++.html). All the examples shown there expose methods using native C++ types, not variants. (What you say about variants makes sense to me, I just don't think it *the* way to do, it is *one* way to do. Or everything exported is converted to variants under the hood?)

> So, in the end, both methods would end up returning real_t to GDScript.

My understanding from the code and from previous discussions is that `real_t` is used only on some specific cases (like in the physics code, IIRC). The variant type used in scripting seems to be [hardcoded to `double`](https://github.com/godotengine/godot/blob/master/core/variant.h#L141). That said, I understand that we want overloads returning `real_t` anyway on the C++ side.

> What @tagcup is trying to say is that those methods are still going to be useful around scene/ and modules/, since we don't want to keep some calculations in real_t, but instead specify doubles and floats (e.g. light baking should work in doubles always, since it has no use of floats when precision matters).

Yes, I understood this after @tagcup's previous reply. I wasn't really thinking about the usage of the `Random` classes from the C++ side.

By the way, I am now in a slightly uncomfortable position. My motivation since the beginning was just to provide nicer random number generation for GDScript. That's what I personally wanted. Now the focus seems to be shifting to better random facilities for Godot's C++ side, which, for the moment at least, does not interest me.

You clearly now have in mind use cases which are different than the ones that matter for me. Whenever I argued that I would prefer to do things differently, it was not because I think that "my way" was inherently better than "yours". I think we are just aiming at slightly different things.

I am not really whining here, this is all perfectly OK. However, I am no longer on the helm of this development for some time: in practice I am just adjusting the code according to the suggestions I get here, which are guided by needs which are not my own and I currently don't actually understand.

I don't intend to abandon this PR, I really want to see better support for RNGs in Godot. But this is probably going to advance slower, both because I am no longer scratching my own itch and because I'll need a lot of advice.

If any of you want to take the implementation I have made so far and personally work to make it like it should be, that's also OK for me. This may be less effort even for you.

**Comment by tagcup** [comment]
> You clearly now have in mind use cases which are different than the ones that matter for me. Whenever I argued that I would prefer to do things differently, it was not because I think that "my way" was inherently better than "yours". I think we are just aiming at slightly different things.

I don't think this is fair; I don't think I've raised any issues in the form of bikeshedding: PCG is quantitatively better than all the PRNG you submitted and naming of the functions in the class isn't coherent. I did mention things like Go's API and PCG, but as I mentioned, those were just examples and if you know any better alternatives, that's also welcome. There're also valid technical reason why STL isn't being used within Godot codebase.

Objective technical criticism, which was my purpose, is different from my way/your way.

> By the way, I am now in a slightly uncomfortable position. My motivation since the beginning was just to provide nicer random number generation for GDScript. That's what I personally wanted. Now the focus seems to be shifting to better random facilities for Godot's C++ side, which, for the moment at least, does not interest me.

> But this is probably going to advance slower, both because I am no longer scratching my own itch and because I'll need a lot of advice.

I really don't understand what's so complicated about making a C++ class and creating a wrapper class for GDScript which has a has-a relationship with it.. But if you're feeling that way, I guess a GDScript-only RNG class is fine for this PR, since we can move it to C++ and add a GDScript wrapper class in another PR. What do you think @bojidar-bg?

**Comment by lmbarros** [comment]
Hi @tagcup,

I am really, really sorry! I didn't mean to criticize your suggestions or accuse you of bikeshedding or anything like this. I think you are doing your part well, and in some aspects, thanks to your input, I believe the PR *is* better than it was originally. Honest. Saying "my way / your way" was probably a bad choice of words.

The point I wanted to make is that I believe we have different goals (to some extent, at least -- we obviously have common goals), and that's why our design/naming decisions we are constantly clashing. For example, I can agree that my API was inconsistent as a C++ API, but I have reasons to like it as a GDScript API. But I don't want to argue about things like these, as they will take us further from our common goals.

Please accept my apologies again. I am a nice guy most of the time :-)

**Comment by lmbarros** [comment]
Oh, and one final addition to my apologies: I also never intended to force "my goals" into Godot. As I said, I quite new to the engine, and therefore I am clueless about what would be "the Godot way" do things, I have no idea what the long-term vision is. I honestly believe you ("you" in plural, I think this includes everyone who joined the discussion) are in a much better position than I am to make such decisions.

**Comment by lmbarros** [comment]
Now, back to the technical discussion:

Technically, there is nothing difficult about "making a C++ class and creating a wrapper class for GDScript which has a has-a relationship with it". My doubts are about how to make this in a way that works well both for C++ and GDScript users.

As I see things, I'd rename the "C++-side" class to something like `RandomPCG64` and use `Random` for the wrapper class. Would this be OK?

As I said, I'd prefer to use the same name both in the C++ and GDScript sides, but I don't see a way to do this.

**Comment by tagcup** [comment]
Oh, OK, I guess my poor communications are showing, so let me just clarify a few things.

First of all, no need for apologies at all, you didn't really do anything wrong. I've just been trying to discuss at a technical level, and so are you.

Second, I'm not a member of the Godot team, so I'm really not in a position to judge what is the one-good-way to do things. What I'm saying is just based on general arguments, like we shouldn't have duplicate functionality/code if possible (like different PRNG implementations for the core and GDScript), internal consistency of API and quality of the PRNG itself. To be clear, I'm not an official reviewer, and I'm not in a position to accept/reject PRs. I'm really little more than a random dude on the net, trying to give technical feedback. And even if I were, we're all doing volunteer work here, so nobody is in any position to dictate anything on you.
 
> As I see things, I'd rename the "C++-side" class to something like RandomPCG64 and use Random for the wrapper class. Would this be OK?

I would say yes. But again, if you want to focus on a GDScript-exclusive PRNG class, I guess that's also fine, somebody else (me, you, or anyone who's interested) can do the rest in a follow up PR.

**Comment by pkowal1982** [comment]
Instead of having many methods for getting different types of data we can use one function with default params and overload it for different param types provided.

API would be much smaller, but maybe not easier to understand.
Only set_seed() and next().

next() will return int from [0, MAX_VALUE (probably 32 bits)]
next(some_int) will return int from [0, some_int - 1]
next(smaller_int, bigger_int) will return int from [smaller_int, bigger_int - 1]
next(some_boolean) will return boolean
**next(array) will return random element of this array**

The same applies for float params, keep in mind that you'll need explicitly pass first float to get one, like:
next(1.0)

I think it would be also nice to have constructor with seed param so you can just initialize class in one line:
var rng = RandPCG32.new(seed)
No arg constructor should probably always start with seed set to 0 or something making sense, like Juan's birth date or so. :)

I don't think that all these distributions are needed in this class. Probably getting uniform value from a range is enough. And if there's some demand for distributions I think they can have some dedicated class or be implemented as gdscript built-in mapping functions.

**Comment by tagcup** [comment]
> And if there's some demand for distributions I think they can have some dedicated class or be implemented as gdscript built-in mapping functions.

That's more or less the point of this PR, the functionality you need already exists now.

I realized distributions haven't explicitly been motivated. Among many things, normal distribution is useful for [generating random rotation matrices](https://en.wikipedia.org/wiki/Rotation_matrix#Uniform_random_rotation_matrices), which is something I think we should have.

Also, having a bunch of functions named the same way, doing different things, doesn't sound simpler to me. It's a personal  opinion, but I think functions which do different things should be named differently. Furthermore, GDScript doesn't support function overloading.

**Comment by Zylann** [comment]
Besides algorithm tweaking, there is something I like about this PR which I think wasn't mentionned... it gives programmers a way to cleanly seed gameplay logic (and by cleanly, I mean with no implicit global variable), and finally have a way to properly isolate seeded and non-seeded logic :)

**Comment by lmbarros** [comment]
In my mind, GDNative made this PR kind of obsolete. I can now (or will be soon able to) do everything I wanted without having to recompile Godot itself. Granted, having this as a "standard" Godot module would be more convenient, but not that much more convenient, I think.

**Comment by Zylann** [comment]
@Imbarros something as basic as this should be in core IMO, and overkill to import a whole shared library to maintain just for one class...

**Comment by cpnielsen** [comment]
What is the status on this? From the milestone + `needs rebase` tags I assume it has been officially endorsed? @lmbarros I hope you would consider completing this (whatever that means in practice).

Having an isolated, instanced generator gives a lot greater control over how random numbers are generated, specifically if you want to make something random but deterministic but still want to use random numbers for "fluff" such as animations, and don't want it to change the potential outcome of game-deciding calculations.

**Comment by lmbarros** [comment]
Hi @cpnielsen! I would consider working again on this PR if I got some feedback from the main Godot developers. I started in one direction then went to a different one (based on comments I got here). But I didn't get any input from the main devs, so I don't really know what they envision as a good design for revamped RNGs.

(That said, see my [comment above about GDNative](https://github.com/godotengine/godot/pull/7989#issuecomment-334939874).)

**Comment by reduz** [comment]
I am not against improving the random functions a bit, but this should be simple, core and not a module.
Still though, as I mentioned before, one of the main problems with randomness is that users don't really understand it and believe they need better RNGs in cases where simpler solutions like shuffle bags are more appropriate.

**Comment by akien-mga** [comment]
I think the API should be a `Random` singleton in `core/math/random.{cpp,h}` that exposes one known efficient and "good" RNG method for each distribution we want to support (normal, Bernoulli, etc.).
No need for a BaseRandom abstraction, we won't implement more than that. If people want different PRNGs, they'll use GDNative plugins for that - but 99% of users just one a simple method that gives them a kind of reliable random number of the chosen distribution.

**Comment by cpnielsen** [comment]
My only plea is that you allow the option of having separate generators - they can use the same algorithm(s), but polling for random numbers (whether integers, floats, etc.) from one should not affect the other. Whether it is done through instances of PRNG classes or some other way is not important.

**Comment by raymoo** [comment]
@akien-mga :-1: to making it a singleton. Maybe there could be one singleton instance that can retrieved that is just a special case of being able to instance a new RNG.

**Comment by lmbarros** [comment]
I agree with @cpnielsen and @raymoo: this shouldn't be a singleton, because one of the top use cases that motivates me is being able to generate independent random sequences. This can be very useful for procedural generation!

(BTW, my second main motivation is having different random distributions supported.)

I got some additional motivation for working on Godot stuff after Ludum Dare 40, but I am really tired and short of time right now. I hope that in a couple of weeks things will be calmer for me, then I'll consider taking a fresh look at this PR (probably rewriting it completely, based on the input form @reduz et alia.)

Let's see how it goes this time. :-)

**Comment by mhilbrunner** [comment]
Please don't make this another singleton. Or at least do as @raymoo suggested.

Being able to instance multiple RNGs at the same time with different seeds is important.
Also IMO this should be in core, not a optional module. Random number generation is needed in a lot of places.

**Comment by akien-mga** [comment]
Yeah I got it, no need to state the same thing three times ;)

**Comment by akien-mga** [comment]
Just `s/singleton/instantiable class like File/` in my previous comment.

**Comment by girng** [comment]
most of your use cases can already be done with `rand_range`

**Comment by cpnielsen** [comment]
@girng There is currently no way to run two or more simultaneous RNGs as the state of the RNG is global. You can do tricks to save the previous number to seed the next, but that does not guarantee uniform distribution.

**Comment by lifelike** [comment]
Is there an advantage over using the C++11 random API (choosing a fast and good enough generator)? And I think it would also be nice if it was possible to instantiate distribution objects (wrapper over the default C++ objects) because I think making many values from the same distribution is by far the most common use case to handle and makes the API easier ti use, not the python way of having a single object with many different methods on (even if that could be included as well if that is not too bloaty).

**Comment by bojidar-bg** [comment]
What's the status of this PR?
@lmbarros I would be glad to help, if possible. :smiley:

**Comment by lmbarros** [comment]
It's effectively on halt :-(  I thought I would have some more time and motivation for it by now, but the PR is basically accumulating dust. :-(

I still think it would be great to have something like this on Godot core, but I often wonder if we shouldn't have a first version using GDNative, to let people use it and give feedback before we are committed to a certain design.

@bojidar-bg  (and everyone else :-) ) I guess the next step would be to rewrite the PR taking into account the latest feedback received (mostly change it from a module to a core feature). If you want to take over the PR from here and beyond, please by all means do that ! I am not sure I can help much here (I don't know the internals of Godot), but let's talk :-)

**Pull request closed without merging**
