### PR TITLE
Sanitize Android debug

### PR DESCRIPTION
**Pull request by RandomShaper**
~~'Remote debug over ADB' seems to be a left-behind of how Android debug worked a long time ago. Now it just breaks debugging.~~

~~What should be checked instead in order to enable remote debug and/or FS is just the fact that the project is deployed with such options toggled. Using ADB is always the case.~~

~~Also removing `DEBUG_FLAG_REMOTE_DEBUG_LOCALHOST`, which was being only used for that old Android scenario.~~

Reworked:
- _Commit 1:_ (the same as formerly but keeping localhost debug, needed for __`adb reverse`__)
'Remote debug over ADB' is removed as that will be always the case.
- _Commit 2:_
Fix Android remote debug not hitting breakpoints
RandomShaper committed an hour ago
A change in `Main`'s API is needed. Please read the comment in the diff for an explanation.

### CODE REVIEW

**Comment by RandomShaper** [comment]
#10530 is the same, but for 2.1, and I've requested reviews there.

**Review by akien-mga — APPROVED** [review]

**Comment by RandomShaper** [comment]
Please don't merge yet.

**Comment by RandomShaper** [comment]
@akien-mga this is ready to merge again. I've updated the description and asked for Juan's opinion in the PR variant for 2.1.

**Comment by hpvb** [comment]
I only see one commit in this PR, it may be an issue with the gh mobile interface though. This commit also appears to *remove* localhost debugging, but maybe I just don't integrand l understand the surrounding code

**Comment by RandomShaper** [comment]
@hpvb, thanks for letting me know. I forgot to re-push.

**Pull request merged**
