### PR TITLE
Remove unused editor icons

### PR DESCRIPTION
**Pull request by Calinou**
This also renames the TextureArray icon to follow its rename to Texture2DArray.

A stripped editor binary is now 22 KB smaller.

I've done a quick check to see if there weren't any missing icons, but I'm not 100% certain there are no missing icons anywhere. Please give this PR a try in your daily editor use if you can :slightly_smiling_face:

This PR can be remade for the `3.x` branch, but it has to be remade from scratch as the list of unused editor icons is different in `3.x`.

### CODE REVIEW

**Comment by akien-mga** [comment]
I made an overview of the removed icons so that we know what we're talking about (and what we can fish back if needed):
Screenshot_20210603_090250

According to ripgrep, `MiniObject` seems used:
```
modules/visual_script/visual_script_editor.cpp
634:            Control::get_theme_icon("MiniObject", "EditorIcons"),
1084:           Control::get_theme_icon("MiniObject", "EditorIcons"),
```

`MultiEdit` was maybe meant to be used in place of the default ~Unity logo~ Object icon for MultiNodeEdit?
Screenshot_20210603_090639

I'm not sure why `ActionCut` is not used anywhere, but we do use `ActionCopy` and `ActionPaste` so I think it might be useful to keep. For example, Cut and Copy could be added here:
Screenshot_20210603_084601

`GizmoCamera` is used in 3.x. Is it just missing in `master` because it wasn't renamed to `GizmoCamera3D`?

`GizmoListener` is not visible in 3.x, but that might be a bug?

The `RotateLeft`/`RotateRight` and `MirrorX`/`MirrorY` icons are used in 3.x for the tilemap editor. @groud should maybe confirm that they're no longer needed.

`KeyHover` is not used in the AnimationPlayer, but maybe it should be? There's no hover effect currently. I don't know if one is wanted/needed.

The `Room*`/`Portal` icons are not particularly good so I guess it's fine to remove, even if @lawnjelly might need new ones for his work.

The `InverseKinematics` icon looks nice but is unused indeed. Poke @TwistedTwigleg @AndreaCatania if you ever need this kind of icon for something :)

**Comment by lawnjelly** [comment]
> The `Room*`/`Portal` icons are not particularly good so I guess it's fine to remove, even if @lawnjelly might need new ones for his work.

Fine to remove by me, my PR does load these 2 as they are defaults but I'll leave it up to someone else to make the icons in a separate PR as I have no SVG skills. :slightly_smiling_face:

**Comment by Calinou** [comment]
I restored the following icons:

- ActionCut
- GizmoListener (see https://github.com/godotengine/godot/pull/49284)
- MiniObject


> GizmoCamera is used in 3.x. Is it just missing in master because it wasn't renamed to GizmoCamera3D?

GizmoCamera is no longer used since https://github.com/godotengine/godot/pull/35784 was merged. The overlaid gizmo icon made it difficult to see the camera rotation.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by lawnjelly** [comment]
Just a heads up, I think I'm using EditorInternalHandle for the sphere Occluder gizmo (maybe since this PR was made)? And the Room and Portal icons. I don't know if we were going to have new ones for 3.4, or reuse.

**Pull request merged**
