### PR TITLE
ResourceImporterWAV: Allow configuring loop mode on import

### LINKED ISSUE #46164: Sound effect is looped although Loop is not checked
**Godot version:**
3.2.3 stable

**OS/device including version:**
Windows 10 20H2, x64, GLES2

**Issue description:**
When I call play() once on a AudioStreamPlayer3D, the sound keeps looping endlessly. I already checked in the sound's import settings that Loop is not enabled.

**Steps to reproduce:**
Create new project
Add .wav file, make sure Loop is not enabled in import settings
Add AudioSteamPlayer3D and assign the .wav to it
Call play() once on the audio stream player
-> Sound is looped endlessly

**Minimal reproduction project:**
[SoundTest.zip](https://github.com/godotengine/godot/files/6001946/SoundTest.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
The new `edit/loop_mode` import options lets user choose to either:
- Detect loop points from the WAV (default, same behavior as before)
- Set the loop mode and loop points manually like in AudioStreamSample

Previously the only options were to import loop points from WAV, or to force a full-length forward loop. There was no easy way to disable looping if it's embedded in the WAV, which confuses many users.

Fixes #46164, at least the most egregious part. The UX around editing loop points on an already imported WAV resource is still awkward.

### Notes

- For a potential `3.x` backport, the compatibility should be preserved with the previous `edit/loop` boolean option. Could possibly be added in this PR too for `master` if wanted.
- "Loop Begin" and "Loop End" import options are only shown when the "Loop Mode" is neither "Detect From WAV" nor "Disabled".
- "Loop Begin" and "Loop End" import options support negative positions, so one can use `-1` to select the end frame (and that's the default value for "Loop End").
- I noticed that the generated spectrum preview in the Inspector actually reflects the loop mode when importing as "Backward" (so it's flipped), but that's not refreshed when reimporting. One needs to reopen the editor for the preview to match the import option at the time of opening.

https://user-images.githubusercontent.com/4701338/158416488-153bd2c6-8e85-4e52-b68a-e820831b1dac.mp4

### CODE REVIEW

**Comment by reduz** [comment]
Now that we allow for advanced UI for some resoucre types, it should be possible to have an editor to show the audio file and edit the loop points.

**Comment by akien-mga** [comment]
We approved this in PR review meeting, though there's room for improvement on the UX as @reduz suggested. He'll write a proposal about it so this can be improved further by any interested contributor.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by EddiePrince** [comment]
Toggling loop on and off should be part of editable settings together with pitch, volume, autoplay and such

**Comment by ellenhp** [comment]
> Toggling loop on and off should be part of editable settings together with pitch, volume, autoplay and such

This is tricky because some AudioStreams cannot loop. AudioStreamMicrophone, AudioStreamGenerator, specifically.

We could *add* a loop property to an AudioStreamPlayer potentially, which would attempt to loop whenever the stream runs out of samples. This could have unintended consequences though because I believe play() is not always allocation-free, especially in the case of ogg/vorbis streams. I agree the current UX could be improved though. I'm just not sure how to do it.

**Comment by ellenhp** [comment]
If you have more thoughts on this though, there's an open proposal for it that we can continue discussion in https://github.com/godotengine/godot-proposals/issues/3120

**Pull request merged**
