### PR TITLE
[3.5+] Overhaul CLI argument forwarding to processes started by the editor

### PR DESCRIPTION
**Pull request by RandomShaper**
Version of #64374 for 3.5+.

### CODE REVIEW

**Review by lawnjelly — APPROVED** [review]
This looks really handy for starting editor projects with the dummy audio driver (for saving CPU), and a more sensible way of passing args.

**Comment by akien-mga** [comment]
I'm not sure this should be backported to 3.5 as this change the behavior of passing arguments in a way that might be seen as compat breaking. It's probably not so critical that it needs to be backported to a released stable branch?

**Comment by Calinou** [comment]
> I'm not sure this should be backported to 3.5 as this change the behavior of passing arguments in a way that might be seen as compat breaking. It's probably not so critical that it needs to be backported to a released stable branch?

From a tech support perspective, I'd like to see this in 3.6 as it makes explaining how to use CLI arguments with the Godot *editor* much easier.

**Comment by akien-mga** [comment]
Yeah I'm happy to have this in 3.6, I was just referring to the `cherrypick:3.5` label.

**Comment by akien-mga** [comment]
Thanks!

**Comment by RandomShaper** [comment]
Removed the 3.5 tag. Let's keep it safe.

**Pull request merged**
