### PR TITLE
Add Z-Index for Autotile

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
captura de tela de 2018-07-02 10-41-54

Demo: https://github.com/guilhermefelipecgs/z-index_demo

### CODE REVIEW

**Comment by mhilbrunner** [comment]
cc @MarianoGnu

**Comment by guilhermefelipecgs** [comment]
I don't mind in rebase my PR if needed, my changes are simple.

**Comment by guilhermefelipecgs** [comment]
Rebased.
captura de tela de 2018-08-13 12-15-17

**Comment by akien-mga** [comment]
@guilhermefelipecgs Is it only for AutoTile? How does it interface with #16771, which added Z index support for TileSets but seems not to be properly exposed now in the new TileSet editor? CC @PJB3005

**Comment by guilhermefelipecgs** [comment]
> Is it only for AutoTile?

Yes.

> How does it interface with #16771, which added Z index support for TileSets but seems not to be properly exposed now in the new TileSet editor?

Should works fine.
I just add the z index of the AutoTile with the `z_index` created by this pr #16771. This way the two z index is considered.
https://github.com/godotengine/godot/blob/6da73b7897851ede7647c265ec53b7f4ee573af2/scene/2d/tile_map.cpp#L332

**Comment by akien-mga** [comment]
Thanks!

**Comment by guilhermefelipecgs** [comment]
I've created a very simple demo showing how to use it if someone is interested.

Demo: https://github.com/guilhermefelipecgs/z-index_demo

peek 07-12-2018 22-11

**Comment by stormi** [comment]
Thanks for the z-index, most useful to avoid having separate tilemaps for foreground and background.

I think something is missing though: I've tried to use it with an Atlas (the new tileset editor allows to create "Atlases" that are groups of tiles), and it seems that the z-index is ignored for those.

**Comment by guilhermefelipecgs** [comment]
@stormi I thought it was working, probably I missed this, I'll take a look at it.

**Comment by stormi** [comment]
Thanks! It's also possible that I used it the wrong way :)

**Comment by guilhermefelipecgs** [comment]
Fixed, I forgot to add some lines.

**Pull request merged**
