### PR TITLE
Added the variable 'backwards' in the documentation.

### PR DESCRIPTION
**Pull request by Acytra**

### CODE REVIEW

**Comment by bojidar-bg** [comment]
That's not how it works. The variable should be bound similar to other variables (and also get a getter and setter): https://github.com/godotengine/godot/blob/master/scene/2d/animated_sprite.cpp#L714

**Comment by Acytra** [comment]
> That's not how it works. The variable should be bound similar to other variables (and also get a getter and setter): https://github.com/godotengine/godot/blob/master/scene/2d/animated_sprite.cpp#L714

Yeah but the getter and setter are not codded yet, so i thought it was a good idea to add the variable in the documentation.

**Comment by Xrayez** [comment]
Note that it's documented as an argument currently:
https://github.com/godotengine/godot/blob/efd55631e2f05141072c26129bdc75d65cd1c53c/doc/classes/AnimatedSprite.xml#L19-L29

If you want to propose to add it as a property instead, you could open an issue about that.

If neither setter nor getter are defined yet, then it wouldn't make sense to expose it in documentation because there would be no way to actually control it from script. Once it's added as a property, the documentation can be then updated with `godot --doctool .` command to generate needed doc strings automatically, and all you'll have to do is fill in the actual text describing what the property does.

**Comment by Acytra** [comment]
> Note that it's documented as an argument currently:
> https://github.com/godotengine/godot/blob/efd55631e2f05141072c26129bdc75d65cd1c53c/doc/classes/AnimatedSprite.xml#L19-L29
> 
> If you want to propose to add it as a property instead, you could open an issue about that.
> 
> If neither setter nor getter are defined yet, then it wouldn't make sense to expose it in documentation because there would be no way to actually control it from script. Once it's added as a property, the documentation can be then updated with `godot --doctool .` command to generate needed doc strings automatically, and all you'll have to do is fill in the actual text describing what the property does.

Thanks for the reply, i will open an issue.

**Pull request closed without merging**
