### PR TITLE
Make it possible to copy engine version text

### PR DESCRIPTION
**Pull request by ghost**
Follow-up to my previous PR on Git hash.

### CODE REVIEW

**Comment by akien-mga** [comment]
Wouldn't it be better to make it possible to select and copy Label text in the editor, instead of turning it to a LineEdit? It's not the only occurrence where it's frustrating that you can't copy e.g. a parser error in the script editor.

**Comment by Noshyaar** [comment]
I assume it would be a lot more difficult to make label texts selectable as it requires most selection-handling code implemented to TextEdit, compared to turning the LineEdit background off. Or maybe popping up a copy menu, or modifying clipboard silently on RMB click?

**Comment by akien-mga** [comment]
As discussed on IRC, we're not fundamentally against the proposed change here, but it might be a good opportunity to attempt to add opt-in selectability to Label. Apparently it's implemented in RichTextLabel already, could likely be ported to Label.

**Comment by Noshyaar** [comment]
Closing as I might make a new one for Label selection. (if I can successfully implement it :P)

**Pull request closed without merging**
