### PR TITLE
[WIP] export var array reduced to const bug fixed

### LINKED ISSUE #20436: Export arrays in singleton end up shared if initialized to same value
**Godot version:**
Godot v3.0.5.stable.official.6a88e22 win64

**OS/device including version:**
Windows 10 Pro v.1803 (on 2 different pc)

**Issue description:**
Loading values in a two-dimensional array has different results if the array is local or global.

On a new project, I added a script (g.gd) as autoload-singleton enabled with the following code:
extends Node
```
extends Node
export var gridTiles = []
export var gridStat = []
```
I create a new scene assigned as main scene on project setting, on the root node added a script with the following code:
```
extends Node
func _ready():
	var x
	var y
	var gridTiles = []
	var gridStat = []

	for y in range(3):
		gridTiles.append([])
		gridStat.append([])
		for x in range(4):
			gridTiles[y].append(null)
			gridStat[y].append(0)

	gridStat[0][0] = 1	
	print(gridStat)
	print(gridStat.size(), " x ", gridStat[0].size())
	print(gridTiles)
	print(gridTiles.size(), " x ", gridTiles[0].size())
	
	for y in range(3):
		g.gridTiles.append([])
		g.gridStat.append([])
		for x in range(4):
			g.gridTiles[y].append(null)
			g.gridStat[y].append(0)

	g.gridStat[0][0] = 2
	print(g.gridStat)
	print(g.gridStat.size(), " x ", g.gridStat[0].size())
	print(g.gridTiles)
	print(g.gridTiles.size(), " x ", g.gridTiles[0].size())
```
The resulting output is:
```
[[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
3 x 4
[[Null, Null, Null, Null], [Null, Null, Null, Null], [Null, Null, Null, Null]]
3 x 4
[[2, 0, Null, 0, Null, 0, Null, 0], [Null, 0, Null, 0, Null, 0, Null, 0], [Null, 0, Null, 0, Null, 0, Null, 0], [], [], []]
6 x 8
[[2, 0, Null, 0, Null, 0, Null, 0], [Null, 0, Null, 0, Null, 0, Null, 0], [Null, 0, Null, 0, Null, 0, Null, 0], [], [], []]
6 x 8
```
Is it a bug or my poor knowledge of gdscript (python)?
Thanks for the attention.

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #20436

```gdscript
## working
export var arr1 = []
export var arr2 = []

export(Array) var arr1 = []
export(Array) var arr2 = []

export(Array) var arr1 := []
export(Array) var arr2 := []

export(Array) var arr1 :Array= []
export(Array) var arr2 :Array= []

export var arr1 :Array= []
export var arr2 :Array= []

export var arr1 :Array= Array()
export var arr2 :Array= Array()

export(Vector2) var arr1 = Vector2i()
export(Vector2) var arr2 = Vector2i()
```
it's working for every scenario above, (seems like only `Array` and `Dictionary` are exportable reference types)

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Doesn't this break default values, e.g.:
```
export var x = [4]
export var y = 91
export var z = Vector3(7,6,4)
```

**Comment by ThakeeNathees** [comment]
@bojidar-bg  even without `reduced to const = true` they reduced to const, so they'll work as old

**Comment by bojidar-bg** [comment]
@ThakeeNathees I would still suggest the same thing as before: call `_reduce_expression(expr, true)` in order to reduce the node to a constant only for the default value (but not to keep the reduced node around in the tree).

**Comment by ThakeeNathees** [comment]
@bojidar-bg there is no regression for `export var x = [5, 4]` or `export var z = CONST + sin(6)` even In that case how about this fix (a simplified version)
```diff
@@ -4926,6 +4926,12 @@ void GDScriptParser::_parse_class(ClassNode *p_class) {

	if (autoexport && !member.data_type.has_type) {
		if (subexpr->type != Node::TYPE_CONSTANT) {
			_set_error("Type-less export needs a constant expression assigned to infer type.");
			return;
		}

		ConstantNode *cn = static_cast<ConstantNode *>(subexpr);
		if (cn->value.get_type() == Variant::NIL) {
			_set_error("Can't accept a null constant expression for inferring export type.");
			return;
		}

		if (!_reduce_export_var_type(cn->value, member.line)) {
			return;
		}

		member._export.type = cn->value.get_type();
		member._export.usage |= PROPERTY_USAGE_SCRIPT_VARIABLE;
		if (cn->value.get_type() == Variant::OBJECT) {
			Object *obj = cn->value;
			Resource *res = Object::cast_to<Resource>(obj);
			if (res == nullptr) {
				_set_error("The exported constant isn't a type or resource.");
				return;
			}
			member._export.hint = PROPERTY_HINT_RESOURCE_TYPE;
			member._export.hint_string = res->get_class();
		}
+
+		if (cn->value.get_type() == Variant::ARRAY) {
+			subexpr = constant_node_to_array_node();
+		} else if (cn->value.get_type() == Variant::DICTIONARY) {
+			subexpr = constant_node_to_dict_node();
+		}
	}
#ifdef TOOLS_ENABLED
```

**Comment by bojidar-bg** [comment]
> there is no regression for `export var x = [5, 4]`

I'm at a loss. How does it work if default value is set only if the node is a ConstantNode:
https://github.com/godotengine/godot/blob/0c43d17545c6d554365a939d504e1e81762981ab/modules/gdscript/gdscript_parser.cpp#L4950

But `subexpr` is an ArrayNode at this point:
https://github.com/godotengine/godot/blob/0c43d17545c6d554365a939d504e1e81762981ab/modules/gdscript/gdscript_parser.cpp#L4879

---

> In that case how about this fix (a simplified version)

Looks patchy to me. Why would we need to generate the `ArrayNode` again, when it already exists before calling `_reduce_expression`?
Are there any problems with my idea of forcibly reducing to constant only when trying to get the default value?

**Comment by ThakeeNathees** [comment]
@bojidar-bg 

1. if `autoexport || member._export.type != Variant::NIL` -> `subexpr` must be constant node, if not error will set. in my pr I'm not trying to reduce it to const but if it's not constant node error will set **unless** if it's an array node or dictionary node -> so except for array and dictionary it'll be the same.

2. >Are there any problems with my idea of forcibly reducing to constant only when trying to get the default value?

- if array node `cn_arr = _reduce_expression(arraynode, p_reduce_const=true);` if `cn_arr` is not constant node set error else `member.default_value = cn_arr => value;` (TODO:)
- else if dictionary node same (TODO:)
- else if constant node nothing new
- else set error


3. (TODO:) if array/dict node after  reduced to constant node I'll check if all elements are exportable using `_reduce_export_var_type()`(#36927) (unless it'll case regression :  #36899)

**Comment by bojidar-bg** [comment]
1. Default values for exported variables are a feature which should continue working if possible. This includes default values for arrays/dictionaries.
2. > if array node cn_arr = _reduce_expression(arraynode, p_reduce_const=true); if cn_arr is not constant node set error else member.default_value = cn_arr => value; [...]
   
    * Note that `_reduce_expression` returns the node itself when called on a ConstantNode. So, there is no need to check for ArrayNode/DictionaryNode/ConstantNode -- it already happens.
    * If the result of `_reduce_expression(.., true)` is not a ConstantNode, you are correct that it shouldn't be used as a default value.

3. I don't think that using `_reduce_expression` that way would cause a regression, but it is a nice thing to keep in mind and check.

**Comment by andrew121410** [comment]
Any information on this?

**Comment by ThakeeNathees** [comment]
@andrew121410 thanks for pointing out. marking this as WIP for now. (https://github.com/godotengine/godot/pull/38976#issuecomment-633192822 TODOs), I'll complete this ASAP (in a couple of days) and It'll ready for reivew.

**Comment by JestemStefan** [comment]
@ThakeeNathees Hi! I saw your PR that fixed this issue for `4.0`. Are you still working on backport for `3.x` or you dropped it and someone can salvage your code?

**Comment by akien-mga** [comment]
Superseded by https://github.com/godotengine/godot/pull/41983.

**Pull request closed without merging**
