### PR TITLE
ThorVG: Update from v0.11.6 to v0.12.0

### LINKED ISSUE #86128: Image.load_svg() breaks gradients bigger than ~2896.309 pixels when a scale argument is passed
### Tested versions

The entire lifespan of Image.load_svg() functions, which were introduced in 4.2

### System information

Godot v4.2.1.stable - Pop!_OS 22.04 LTS - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### Issue description

When a SVG has a gradient bigger than 2896.309 units, any amount of scaling passed when it's loaded will break it. That is, if you upscale the SVG 10 times, you can't have gradients bigger than 289.6309 pixels for example. If you use such a gradient on a shape, it won't display.

### Steps to reproduce

```gdscript
# A SVG of a red gradient on a circle over a white rectangle.
# One uses a 289.63px wide gradient, the other is a 289.64px wide gradient.
const gradient_on_svg := '<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><linearGradient x2="289.63" gradientUnits="userSpaceOnUse" id="a"><stop stop-color="red"/></linearGradient><rect width="16" height="16" fill="#fff"><circle r="16" fill="url(#a)"/></svg>'
const gradient_off_svg := '<svg width="16" height="16" xmlns="http://www.w3.org/2000/svg"><linearGradient x2="289.64" gradientUnits="userSpaceOnUse" id="a"><stop stop-color="red"/></linearGradient><rect width="16" height="16" fill="#fff"><circle r="16" fill="url(#a)"/></svg>'
var gradient_on_texture: ImageTexture
var gradient_off_texture: ImageTexture

func _draw() -> void:
	draw_texture_rect(gradient_on_texture, Rect2(6, 40, 60, 60), false)
	draw_texture_rect(gradient_off_texture, Rect2(76, 40, 60, 60), false)

func _ready() -> void:
	var gradient_on := Image.new()
	var gradient_off := Image.new()
	gradient_on.load_svg_from_string(gradient_on_svg, 10.0)
	gradient_off.load_svg_from_string(gradient_off_svg, 10.0)
	gradient_on_texture = ImageTexture.create_from_image(gradient_on)
	gradient_off_texture = ImageTexture.create_from_image(gradient_off)
	queue_redraw()
```

Here's the result from this (ignore the background noise):

image

### Minimal reproduction project (MRP)

No need to follow project files, just copy the above code inside a Node2D or a Control.

### PR DESCRIPTION
**Pull request by capnm**
https://github.com/thorvg/thorvg/releases/tag/v0.12.0

Godot-related SVG bug fixes:

+ [SwEngine]  thorvg/thorvg#1834
+ [SwEngine]  thorvg/thorvg#1848

Fixes #86128 Gradient issue.

editor_screenshot

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
The copyright year update should also be done in this file:
```diff
diff --git a/COPYRIGHT.txt b/COPYRIGHT.txt
index 4b8a246df0..c549761beb 100644
--- a/COPYRIGHT.txt
+++ b/COPYRIGHT.txt
@@ -483,7 +483,7 @@ License: Expat
 
 Files: ./thirdparty/thorvg/
 Comment: ThorVG
-Copyright: 2020-2023, The ThorVG Project
+Copyright: 2020-2024, The ThorVG Project
 License: Expat
 
 Files: ./thirdparty/tinyexr/
```

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by tokengamedev** [comment]
Can this be pushed to 4.2 branch also.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
