### PR TITLE
Enable raycast nodes by default

### LINKED ISSUE #31637: Why raycasts are disabled by default?
**Godot version:**
89bcfa4

**Steps to reproduce:**
1. Create a RayCast(2D) node
2. Add some code and stuff
3. Try it
4. Oh, it doesn't work. You forgot that the Raycast you just wanted to use isn't enabled by default

**Issue description:**
Why tho? If I add a Raycast, I most likely want to use it. And raycast is supposed to be working all the time to, you know, actually detect something. Couldn't the `enabled` property be ON by default? Is really no one else bothered by this? >_>

### PR DESCRIPTION
**Pull request by Xrayez**
Closes #31637.

### CODE REVIEW

**Comment by Calinou** [comment]
Since we're breaking compatibility, tt makes sense to make the "Disabled" property into an "Enabled" one.

**Comment by KoBeWi** [comment]
> Since we're breaking compatibility, it makes sense to make the "Disabled" property into an "Enabled" one at the same time. 

I think this applies to CollisionShape/Polygon, doesn't it?

**Comment by Calinou** [comment]
@KoBeWi Indeed, I confused CollisionShape and RayCast.

**Comment by Xrayez** [comment]
I think it's fine to break compat now?

Note that the changes are quite simple because the raycasts are actually enabled and disabled on enter/exit callbacks:

https://github.com/godotengine/godot/blob/0ee0fa42e6639b6fa474b7cf6afc6b1a78142185/scene/2d/ray_cast_2d.cpp#L136-L141

**Comment by akien-mga** [comment]
```
16:02 <Akien> reduz: ok with enabling RayCasts by default in 4.0? #36307
16:03 <reduz> Akien: i dont have the slightest clue why they were disabled by default
16:05 <Akien> Hehe
16:05 <Akien> I guess that settles it :P
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by Anutrix** [comment]
Shouldn't initialization be moved from constructors to declaration for these classes?

**Comment by Xrayez** [comment]
@Anutrix kinda yes, but should likely be done as coordinate effort (not all cases got converted), see also Akien response at https://github.com/godotengine/godot/pull/39695#issuecomment-646967961.

**Pull request merged**
