### PR TITLE
Fix error path returned when select '..' from file dialog

### LINKED ISSUE #13203: Unable to select a folder in project manager create dialog
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master 62d86b15887371c59f99bfa37dbe2fcaf80478f7

**Issue description:**

selecting a folder in the project manager create dialog  does not work, i have my default projects folder assigned, and everytime i choose a subfolder of that folder it simply returns to the default folder assigned, if you go to a folder in the default's parent folder it just give you the default's parent folder, if you create a folder in the dialog then the path will be set to its parent location.

**Steps to reproduce:**

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by Geequlim**
Fix #13203

### CODE REVIEW

**Comment by akien-mga** [comment]
That doesn't seem like the right fix to me. The issue is that `..` is selected by default since `.` was removed.

**Comment by Geequlim** [comment]
@akien-mga 
In my opinion select `..` to get the current showing directory is expect.
Of couse the checking for `.` could be removed.

**Comment by akien-mga** [comment]
>  In my opinion select .. to get the current showing directory is expect.

No, `..` means "parent directory". If you select it, it's normal that you end up with the parent directory. That's why `.` was there in the first place. IMO #13121 should be reverted, if we don't like this Unix-style browser and want it more like Windows', we need to rethink it a bit, and that's too late for 3.0.

**Comment by Geequlim** [comment]
We can hide the `..` too. The dialog should never select an item with `.` or `..`.
Then have to add a button to go  to parent directory like Qt does.

**Comment by akien-mga** [comment]
The problem is that unlike most other file dialogs in Qt, GTK, native Windows UI, etc., we need to be able to select *folders* and not only files. And quite often, people will want to select a folder by browsing inside it, instead of browsing to its parent and selecting the folder in the list.

So either we have `.` to be able to select the folder, or we should have support for deselecting so that no selection means "current folder".

**Comment by Krakean** [comment]
@Geequlim fixed in #13252 , take a look please, curious whether fix works fine & as expected for you.

**Comment by akien-mga** [comment]
Superseded by #13252.

**Pull request closed without merging**
