### PR TITLE
Make `Skeleton3D` bone simulator an internal child

### LINKED ISSUE #95238: PhysicalBoneSimulator3D child being added to Skeleton3D by Engine always
### Tested versions

4.3-rc2: bug happens 
4.3-dev-5: does not

### System information

Ubuntu 22.04.2 LTS with Godoto 4.3-rc2

### Issue description

When you instance a scene with a Skeleton3D, the engine automatically adds a PhysicalBoneSimulator3D as a child of the Skeleton3D.

This caused issues in my project because my code was iterating over the Skeleton3D's children, expecting their types to match those shown in the editor scene tree.

image

### Steps to reproduce

1. Add a Skeleton3D to a scene in the editor.
2. Add MeshInstance as a child to the Skeleton3D in the editor.
3. Run the scene

Expected:
- The remote scene tree should show a Skeleton3D with just a MeshInstance as the only child.

Actual:
- The remote scene tree shows there has been a PhysicalBoneSimulator3D added.

### Minimal reproduction project (MRP)

[bug-repo.zip](https://github.com/user-attachments/files/16521386/bug-repo.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
The documentation lists this as internal, and it makes sense to keep this internal

* Fixes: https://github.com/godotengine/godot/issues/95238

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Comment by MajorMcDoom** [comment]
@AThousandShips 
Hi there! I noticed that the auto-added child is still marked as *active* in the inspector when you inspect it in the Remote scene tree. Not sure if that actually means anything, but just thought I'd raise it.
Screenshot 2024-08-13 133249

**Comment by AThousandShips** [comment]
That didn't happen before this? I don't see how that would be affected by this change

**Comment by MajorMcDoom** [comment]
> That didn't happen before this? I don't see how that would be affected by this change

This screenshot is from `4.3rc3`. I don't think it's *caused* by this change, but I wasn't sure if this was a bug or something else, and this was the only place I thought to ask since the code setting the sim's active to false was right above the line changed by this PR and I thought you would be familiar with the code. Sorry about that. Should I open up a new issue?

**Comment by AThousandShips** [comment]
I'd say to open an issue yes, I don't know the general animation area well beyond what I've worked on, and what code I can understand, my knowledge in this case was with internal/non-internal nodes

**Comment by TokageItLab** [comment]
The internal Simulator active should be linked to animate_physical_bones. If it is not linked, it may be a bug. But if not so, no problem. See also https://github.com/godotengine/godot/pull/93504

**Comment by MajorMcDoom** [comment]
> The internal Simulator active should be linked to animate_physical_bones. If it is not linked, it may be a bug. But if not so, no problem. See also #93504

I see, thanks for the clarification! I think my concern now is just that there's an additional internal modifier node that is processing just because of the default value of this "linked active state" being true, despite there being no physical bones present.

If that is not an issue though, I'll just ignore it.

**Comment by TokageItLab** [comment]
The existence of an active modifier will cause the deferred process to be called. So strictly speaking, there a very very small performance loss, so if you are really concerned about it, you should use a build with `disable_deprecated = true` to remove the internal modifier.

However, as I fixed in https://github.com/godotengine/godot/pull/93502, this should not be a big performance problem, since the updating does not actually occur in deferred process unless the physical bone is not in the child.

**Pull request merged**
