### PR TITLE
Add ability to set "keep screen on" for android & iOS. fixes #2428

### LINKED ISSUE #2428: Some api to be able to go to sleep for mobile device.
Godot forces always on for mobile device.
But some api to be able to go to sleep for mobile device would be great.

### PR DESCRIPTION
**Pull request by volzhs**
Can change "Set Keep Screen On" at Project settings.

2 methods are added to `OS`.

```
OS::set_keep_screen_on(bool)
bool OS::is_keep_screen_on()
```

I made another PR instead of #2943

### CODE REVIEW

**Comment by volzhs** [comment]
I tried to resolve conflict with 4b1f0af commit. but I guess I messed up something. :(
should I do something for this PR?

**Comment by akien-mga** [comment]
Hehe, I don't know how you manage to duplicate your own commits, I never got that. But I've had issues sometimes with commits of other people being included in my PRs yes. I'll check tonight if I can find the commands to fix the PR.

**Comment by volzhs** [comment]
I'm not good at git command, so i'm using ``SourceTree``.
I tried to rebase this PR to 4b1f0af, and this happened after resolved conflicts with ``SourceTree``. :(

**Comment by volzhs** [comment]
I will make another PR for this.

**Pull request closed without merging**
