### PR TITLE
Fix compilation of jpgd.cpp on MSVC 2017

### PR DESCRIPTION
**Pull request by RandomShaper**

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by Anutrix** [comment]
@RandomShaper  You fixed this upstream in https://github.com/richgel999/jpeg-compressor/pull/12 so the patch is not required if we sync to upstream.

**Comment by RandomShaper** [comment]
Yes, now they have merged it, I guess it's time to remove the patch from the Godot repo. I'll submit a PR.

**Comment by RandomShaper** [comment]
@akien-mga, I'm not sure if we can already sync with upstream. Shouldn't they mark somehow it's a new version? I don't know how they are handling releases.

**Comment by akien-mga** [comment]
It's not clear from upstream which commit is `2.00` per se, as they pushed various doc fixes after adding the 2.00 line in the header. You can simply update to the latest master commit (which should be the same as the code we currently have, i.e. just an update of `thirdparty/README.md`).

**Pull request merged**
