### PR TITLE
Clean up & improve makerst.py

### PR DESCRIPTION
**Pull request by PJB3005**
Man this file even had some semicolons in it.

I cleaned up the entire file, while it's still pretty ugly it's much better now.
I also added type checks so it passes `mypy --strict`.
`make_type` now throws a warning on unresolved type references, which there are a bunch of. I'm not responsible for fixing those though.
Also some more hardening against crashes. For example XML tags without content won't cause crashes now.
Functionality has not been modified as far as I can tell.

### CODE REVIEW

**Comment by PJB3005** [comment]
It just occured to me that this file used to still work on Python 2 and this PR breaks that. I thought this was Python 3 because it used parenthesized print statements without importing `print_function`, and that the shebang was just horrendously wrong (considering the state this file was in that's reasonable IMO).

So is this fine or should I make it work on Python 2?

**Comment by Zireael07** [comment]
I believe Godot's Python tooling is version-agnostic, i.e. should work on both 2 and 3.

**Comment by akien-mga** [comment]
It's fine with me to make it require Python 3 (note that it *was* written for Python 2, so the shebang was not "horrendously wrong", it was just what the typical shebang was for Python 2 scripts on Unix until most distros finally decided to move from `python` to `python2`).

The `doc/Makefile` needs to be changed too though, it currently calls `python` and not `python3`.

**Comment by PJB3005** [comment]
The source of the order being alphabetical is something that's guaranteed to happen since Python 3.7. In 3.6 they made dictionaries ordered (implementation detail) and in 3.7 they made it official. The code for inheritance was iterating over a dictionary so it was technically arbitrary. I changed the code when I noticed so the order is now consistent in any Python version. Same deal for enums except with a set.

**Pull request merged**
