### PR TITLE
Fixed hardware-accelerated skinning support.

### PR DESCRIPTION
**Pull request by SaracenOne**
I assumed this feature was broken in more in profound ways, but after studying it, attempting to understand how it worked, and what possible stages were broken, in the end it turned out to be a trivial single line fix. So yes, this re-enables GPU skinning on supported hardware, and while I'm still suffering from other performance issues, profiling this with a large number of skinned meshes does make a difference. I also added a check for ARB varient of the texture_float extension, since the OES one it currently checks for does not seem to be supported on most PC hardware.

### CODE REVIEW

**Comment by reduz** [comment]
wow right on time, you are a genius!

**Comment by SaracenOne** [comment]
Thank you. Feels underwhelming considering amount of effort it took to narrow down relative to the triviality of actually fixing it :p

**Comment by romulox-x** [comment]
That was it?  Oh man.  I dug into it a while back, and could never figure out what the problem was.  Nice work!

**Comment by akien-mga** [comment]
I guess that should be merged for 2.0?

**Comment by SaracenOne** [comment]
Hold on, I've discovered a new bug with this feature which must have slipped past me. In the 3D Platformer example, it seems the player's skeleton gets messed up whenever the other skeletons are on screen. This slipped past me because in my project, I'm only using the one rig currently. I'll try to look into this tommorow and get back to you.

**Comment by SaracenOne** [comment]
Okay, the bug I mentioned should be fixed now. The renderer didn't flag the need to update the uniforms between changes to the skeleton, specifically changes to the size of the texture the skinning meshed was using to upload the matrices since there is a uniform which determines the size of individual pixels.

**Comment by SaracenOne** [comment]
One further minor fix has been added: multiple skinned meshes using the same skeleton weren't updating during rebinds (switching shaders, ect.).

**Comment by soloparatolos** [comment]
I have a rigged character with the built in outline and after last changes, the "dark" 3d model is in place but the main model is displaced. I'll create a proper issue for the subject after trying a simple example case.

**Comment by SaracenOne** [comment]
I am aware of an inconsistency between models using the respective CPU and GPU paths for skinning. In a specific test case I have, a head which uses morph animation, has some issues due to meshes with morph keys still using the CPU path for skinning. I could probably fix this by moving morph animated meshes to still rely on the GPU for skeletal skinning, but I'm still looking into the causes and the best universal case to solve this issue. I'm unsure why an inverted hull mesh would have this issue though unless the outline mesh happens to have morph keys, so it probably would be worth me taking a look at your mesh when I next get the chance.

**Comment by soloparatolos** [comment]
Thats probably the case, my character model has shape keys for face animation. The inverted hull is in place, the one displaced is the main one with the shape keys. By the way, thanks for your great work and hope the Galatea Project is going well.

**Pull request merged**
