### PR TITLE
fixed pitch bend value and MIDI running status on the InputEventMIDI.

### PR DESCRIPTION
**Pull request by arlez80**
I fixed setting pitch bend (MIDI message: Ex ll hh) value.
and I implemented MIDI running status.

### CODE REVIEW

**Comment by akien-mga** [comment]
Changes seem good, could you squash the commits into one? See docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by arlez80** [comment]
Thank you for your comment. I squashed some commits into one.

I didn't change it, but I think should rename (or add new member variable) InputEventMIDI.pitch.
Currently, used InputEventMIDI.pitch as following:
MIDI_MESSAGE_NOTE_OFF: as note number
MIDI_MESSAGE_NOTE_ON: as note number
MIDI_MESSAGE_AFTERTOUCH (Polyphonic Key Pressure): as note number
MIDI_MESSAGE_PITCH_BEND: as pitch bend value (center is 0x2000)

**Comment by akien-mga** [comment]
> I didn't change it, but I think should rename (or add new member variable) InputEventMIDI.pitch.
Currently, used InputEventMIDI.pitch as following: [...]

That might make sense indeed, but it would be better to wait for 4.0 for this as it would break compatibility. Hopefully @marcelofg55 can provide some feedback on the proposal :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
