### PR TITLE
Added cache variable for bm and texture to speed up processing

### LINKED ISSUE #11503: Selecting a sprite with big texture on it is very slow
Godot 2.1.3, Godot 3.0 master
Windows 10 64 bits

I just noticed that selecting a sprite having a big texture on it in the viewport freezes the editor for a second or two. On comparison, selecting a smaller sprite is instant, scaled or not. Selecting in the tree doesn't have this issue.
It's unclear to me why this would be so slow?

Repro:
1) Create a big PNG, like 4000x4000 or above
2) Assign it on a sprite (notice first freeze as you assign it, but it's because of a `load`)
3) Deselect anything
4) Now click on the sprite in the viewport: notice short freeze

### PR DESCRIPTION
**Pull request by AlexHolly**
Instead of using load on each selection I added a cache variable for the bitmap.

closes #11503

### CODE REVIEW

**Comment by Zylann** [comment]
I'm trying to understand what the existing code is doing, and I don't get it... Why does the editor needs to download the image feom GPU and access all pixels like that while all I do is to select a sprite?

**Comment by Zylann** [comment]
Reading more, it looks like the slowdown would be caused by the texture region editor... Which does that when set to "auto slice" (which might be the default?), and does it even if that editor isn't shown. Wouldn't it be better to run this slow operation only when really needed?

**Comment by AlexHolly** [comment]
The TextureRegion Editor is always visible when a Sprite is selected. I am not sure how to show it only when the region feature is enabled. I had a short look but didn't find anything easy. This would not solve the  issue anyway.

**Comment by Zylann** [comment]
Really? I have to check but I dont remember this to be the case... Also caching the image is only solving the repro in which you would toggle between the same texture and a non-sprite, right?

**Comment by Zylann** [comment]
Also did you investigate why it's not slow when the node is selected from the tree? Not everyone uses auto-slice texture region everytime they click on sprites, so I believe a better fix would be to think about not calculating this all the time over and over

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by MarianoGnu** [comment]
should be possible to queue slicing to the moment when the editor is shown: on edit(obj) function check if visible, if it is then call the slice function, otherwhise connect the signal "visibility_changed" to the slice function with the ONESHOT flag, that should do, in any case this connection should be discinnected if never called, there are other ways to do the same too.

I'll give it a shoot latter if you doesn't have the time

**Comment by AlexHolly** [comment]
I don't have time until mid next month so feel free.

**Comment by reduz** [comment]
@MarianoGnu ?

**Comment by MarianoGnu** [comment]
i'll fix this this week, i was putting my effort on autotiles before beta.

**Comment by akien-mga** [comment]
Bump.

**Comment by MarianoGnu** [comment]
see #15012

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by mhilbrunner** [comment]
What is the status of this?

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/pull/15012 is a better solution. I think the TextureRegion button should only appear when enabled.

image

**Pull request closed without merging**
