### PR TITLE
Use correct omni light attenuation

### LINKED ISSUE #34683: OmniLight does not fade out towards range end
**Godot version:**  
v3.2.beta.custom_build.318c69351

**OS/device including version:**  
Linux (Solus 4.0)

**Issue description:**  
In the current master branch the `OmniLight` does not fade out towards the range end. Instead the whole lighted area seems to have the same light intensity.
(It can be improved with the attenuation value. However regardless of the settings it does not fade out completely.)

**Steps to reproduce:**  
Add an `OmniLight` above a big enough plane mesh to cover the whole range. Leave everything else on default.

**Minimal reproduction project:**  
Project: [omni_bug.zip](https://github.com/godotengine/godot/files/4008231/omni_bug.zip)  
Image from the project:  
omni_bug

### PR DESCRIPTION
**Pull request by winston-yallow**
This fixes godotengine/godot#34683 however I am not sure if this really is correct. It looks correct to me. I am not really experienced with glsl so please double check.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Great catch!

**Comment by reduz** [comment]
There are so many hacks in attenuation code, that I believe at this point maybe we should probably just use a texture..

**Comment by winston-yallow** [comment]
Hm not sure how to do that. I am not really skilled with glsl/graphics programming so someone else would need to implement this using a texture.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
