### PR TITLE
Fix undo when merging actions

### PR DESCRIPTION
**Pull request by ghost**
The bug usually happens when dragging a spinbox in the Inspector dock, now when undo/redo, the property is set initial value when undo and the last value when redo.

Related to #3416.

### CODE REVIEW

**Comment by reduz** [comment]
i'll give a check to this, as i'm not sure if it s the real reason it's not
working

**Comment by akien-mga** [comment]
What about this PR, is it still needed?

**Comment by reduz** [comment]
there are many cases of mergeable where you want the whole set of undo and redo actions, such as painting data in tilemap. Instead I propse to change the mergeable mode into an enum like
MERGE_DISABLE,
MERGE_ALL,
MERGE_ENDS

and move some cases to MERGE_ENDS

still let's wait for 2.1

**Comment by akien-mga** [comment]
As per the above, I guess this PR should be closed and forked into an issue, so that we remember to rework the merging modes for 2.1?

**Comment by TheHX** [comment]
I agree, UndoRedo class really needs some work.

**Comment by akien-mga** [comment]
I opened #4061 as a follow-up, so closing this PR.

**Pull request closed without merging**
