### PR TITLE
Fix uniform scaling of non-square CanvasItem nodes

### LINKED ISSUE #3224: Uniformly scaling nodes with aspect != 1:1
Scaling nodes using the SHIFT key to scale uniformly (keeping aspect) works right only when the node has an aspect of 1:1

When scaling with another aspect the node stretches in a non uniform way.
This issue is an oldie but I guess nobody reported it yet.

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #3224.
I chose the longest side of the original node (width vs height) as the "guiding direction" to handle the ever changing drag_vector and avoid issues when a component changes sign.

### CODE REVIEW

**Comment by akien-mga** [comment]
I experimented a few things before going for a "guiding direction" based on the aspect ratio only, but trying to be too clever was quite difficult as the components of the drag_vector change direction quite easily and the previous code would lead to singularities when drag_vector.x/drag_vector.y changed sign (which is probably why the code chunk was deactivated by an ```if(false && ...)``` as it was buggy).

**Comment by akien-mga** [comment]
One drawback of my implementation is that if you want to scale e.g. a 5x1000 px sprite, you'll need to drag a lot along the Y axis to manage to e.g. double its dimensions, as it's the Y direction which is taken as reference (and to double 1000px by dragging, it takes more time than if one had to double 5px on the X axis - but then it would be too sensible, so the compromise is fine IMO).

**Comment by FEDE0D** [comment]
It's working!
I tested on controls, sprite and animationSprites both aspect 1:1 and 1!=1 and it works fine.

**Comment by FEDE0D** [comment]
Thanks for fixing this. The bug was there since I can remember I don't know how it passed unnoticed for so long.

**Comment by akien-mga** [comment]
Awesome :)

**Comment by akien-mga** [comment]
It looks like uniform scaling has been added in #436, but only tested on 1:1 textures indeed.

**Pull request merged**
