### PR TITLE
Fix reflection probe

### LINKED ISSUE #45895: Vulkan: ReflectionProbes don't show up and cause clustering artifacts instead
**Godot version:** `master` Git 89a43d9c2
This bug has been around at least since December 2020.

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 460.39)

**Issue description:**

Reflection probes don't display correctly and will exhibit clustering artifacts:

ReflectionProbe clustering artifacts

**Steps to reproduce:**

- Add a ReflectionProbe to a scene.

**Minimal reproduction project:** [test_reflection_probe.zip](https://github.com/godotengine/godot/files/5966428/test_reflection_probe.zip)

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Attempting to fix reflection probes in Godot 4 Vulkan renderer.

Fixed issue where environment wasn't passed and the reflection probe didn't work for exterior.
Fixed issue where the wrong struct type was used to determine the size of the reflection probe buffer.

Todo: rotating the reflection vector is not working properly yet resulting in a weird reflection:
image

Still looking into this.

*Bugsquad edit: This closes https://github.com/godotengine/godot/issues/45895.*

### CODE REVIEW

**Comment by reduz** [comment]
looks good so far!

**Comment by BastiaanOlij** [comment]
> 
> 
> looks good so far!

Not sure yet why the rotation is off though... I can't find fault (yet) with the logic, it must be another hard to spot typo :)

**Comment by BastiaanOlij** [comment]
Turned out a lot of issues where caused by buffer alignment and with the matrix being the last entry in the struct it fell over. Also we needed to reverse the culling, everything was inside out.
image

Note that due to the nature of how this works a sphere object like in the image above will have itself reflected. Don't think anything can be done about that, not really the use case of reflection probes.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
