### PR TITLE
[3.x] Remove deprecated Navigation nodes and backport goodies

### PR DESCRIPTION
**Pull request by smix8**
Removes deprecated `Navigation` / `Navigation2D` nodes and all related functions as announced to users in Godot 3.5.

Backports also many small fixes and convenience functions from current Godot 4 to Godot 3  (e.g. agent default values, navigation layer bitmask handling, functions to change navigation maps, ...).

Does also many internal changes so the codebase between Godot 4 and Godot 3 is not so out of sync for some nodes and objects, it makes backporting stuff a lot easier.

E.g. as a pure internal change splits the source file for `NavigationPolygon` resource from the `NavigationPolygonInstance` file as already done in Godot 4. The NavigationPolygon is not a small helper resource for the NavigationPolygonInstance after all and included in many other nodes and objects so it justifies its own file. This means NavigationPolygon source and include can now be found in `"scene/resources/navigation_polygon.h"` next to the navigation mesh.

### CODE REVIEW

**Comment by NanitesNanites** [comment]
Should this really happen for 3.6? Even when Navigation was deprecated, it is still used quite a bit, so it's a compatibility breaking change. Current 3.x projects will eventually have to upgrade to 3.6 for compatibility (for example it's supposed to target Android SDK 33 which will be required later this year by Google Play Store), and this forces them all to make (rather significant) changes.

As those are already removed in 4 (which is totally fine since it's not directly compatible with 3 anyway), I feel they should stay as deprecated in 3.6 (which as I understand will the the last 3.x branch?) to keep compatibility with existing projects and not force current users to make large changes, for no obvious gain as they don't do any harm.

**Comment by radlotus** [comment]
Yes, please backport this. 
Because of gles2 and export size Godot 3 is going to be the better option for web and mobile projects especially 2d for many years to come. 
Let 3.6 be better than 3.5. 3.5 can keep the old navigation nodes.

**Comment by NanitesNanites** [comment]
@radlotus 

I guess you are not aware that you can already compile the HTML exports yourself, without the modules you don't need?

Add "module_navigation_enabled=no" to the build command and you got yourself a version without nagivation, saving 110kb and not breaking compatibility for everyone else.

**Comment by radlotus** [comment]
@NanitesNanites
Even with all the modules disabled the engine runtime is still bigger in godot 4.
GLES2 and no requirement for SharedArrayBuffer are actually the reasons why i would like for godot 3 to still keep improving and backport the better stuff, because I make web games. 
SharedArrayBuffer is very poorly supported on mobile web browsers. Webview doesn't support it at all, so can't run godot 4 projects.

**Comment by NanitesNanites** [comment]
@radlotus 

I understand why you want to use 3 (I keep using it myself).

But I don't understand your point towards this PR, removing Navigation does not make 3 any better - just smaller. 
And that, as I previously said, you can already easily do yourself by just compiling it without Navigation (and whatever else you don't need. You can reduce the size alot if you only use basic nodes).

**Comment by radlotus** [comment]
@NanitesNanites
Ah, I see your point. I thought this PR was about backporting the new Navigation nodes.

**Comment by smix8** [comment]
Closing as it was decided to keep the status quo with the deprecated navigation stuff around.

Feel free to salvage parts of this pr.

**Pull request closed without merging**
