### PR TITLE
Add size to QuadMesh

### PR DESCRIPTION
**Pull request by Chaosus**
Fix for https://github.com/godotengine/godot/issues/12745

### CODE REVIEW

**Comment by Chaosus** [comment]
@akien-mga review ?

**Comment by akien-mga** [comment]
CC @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Works fine. My only two remarks would be:

1) With size 1,1 it is actually 2 units wide and 2 units high as it goes from -1.0,-1.0,0.0 to 1.0,1.0,0.0
I would change it so it is sized to -0.5,-0.5,0.0 to 0.5,0.5,0.0

2) QuadMesh was mostly kept for backwards compatibility and as its upright its easier to use for billboards with particles. I wonder however if the newer PlaneMesh is enough and whether QuadMesh is really needed?

**Comment by Chaosus** [comment]
So, I change it according (1) and it will be fine ?  Ok

**Pull request merged**
