### PR TITLE
Travis: Update Android NDK to r18

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by volzhs** [comment]
travis result for android would be fine, but problem will be occurred while building an apk with gradle, IIRC.

**Comment by akien-mga** [comment]
I'm only updating to have a more recent compiler and hopefully reduce some of the spam log I'm getting in #22620 (which even makes the build abort).

**Comment by volzhs** [comment]
oh I see.

**Comment by akien-mga** [comment]
No need to cherry-pick for 3.0, we're sticking to NDK r16 for official releases in the 3.0.x branch for now.

**Pull request merged**
