### PR TITLE
Update visuals immediately after resizing `Placeholder*` textures

### LINKED ISSUE #87822: Resizing Placeholder Texture requires reopen scene to take effect
### Tested versions

Godot Engine v4.2.1.stable.official.b09f793f5

### System information

Windows 11 Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3050 Ti Laptop GPU

### Issue description

image

Then resize it to 128x:

image

Reopen the scene:

image

### Steps to reproduce

As above.

### Minimal reproduction project (MRP)

Very easy to reproduce.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/87822

### CODE REVIEW

**Comment by clayjohn** [comment]
Just to confirm, were you able to reproduce the reported issue and confirm that these changes fix the issue?

**Comment by jsjtxietian** [comment]
> Just to confirm

Yes I'm able to reproduce the `PlaceholderTexture2D` case, I haven't test the other two but I IMHO it's may be the saeme.

**Review by akien-mga — APPROVED** [review]
Makes sense to me. I checked the rest of the code and those are the only setters for these textures, so should be the only places where an update needs to be queued.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
