### PR TITLE
Backport CanvasLayer fixes

### PR DESCRIPTION
**Pull request by RandomShaper**
This is a pack of backports from 3.1 also fixing & enhancing `CanvasLayer` **in a compatible way**.

**UPDATE: No longer [tentative], all _master_'s counterparts merged!**

**EDIT:** Rewritten commits summary after updates in the PR. Again, to add commit 6. Once more.

- Commit 1 is the good one from #21245, adding an optimization (the other commit from that PR was reverted in master because it was implementing a wrong approach; see commit 5).
- Commit 2 is a cherry-pick of 9e7cee2ceb1a963c1da2c21013adf7d616412d3c, which removes the own `World2D` that `CanvasLayer`s had (therefore, fixing  #17524, #17523 and #18005). This was not backwards compatible.
- Commit 3 is from #21173, letting `CanvasLayer`s have their own `World2D` (as always in 3.0), but adding a flag to use the default one. That is, this takes the best from the previous cherry-pick but keeps the former behavior as the default to restore compatibility. It warns about its deprecation because 3.1 has the unbroken behavior (not own world).
- Commit 4: just a cherry-pick of a bug fix.
- Commit 5: cherry-picks (with conflicts solved) the only commit from #21386 (**~~still not merged into master~~**), which implements the right approach to the issue about picking inside `CanvasLayer`s.
- Commit 6: adaptation of #23411 & #23734 (a fix the former required) to 3.0 in a back-compat way.

This code is donated by an anonymous contributor.

### CODE REVIEW

**Comment by akien-mga** [comment]
@RandomShaper While you're here (I'll delete that comment, just a direct notification for you), we're discussing one of your PRs on #godotengine-meeting on IRC if you can join :)

**Comment by RandomShaper** [comment]
@hpvb, is OK to you that when I fix a bug on _master_ instead of tagging it for cherry-picking, I comment on its description that cherry-picking is not needed and I submit a PR for 3.0 possibly including a number of related fixes?

**Comment by RandomShaper** [comment]
The build error seems to be a false positive.

**Comment by hpvb** [comment]
Yeah, a comment would be best, thank you!

**Comment by akien-mga** [comment]
Since 3.1 was released, I'd prefer to avoid doing this kind of core changes to the previous stable branch 3.0, unless they are really fixing an issue for 3.0 projects in production.

@RandomShaper Do you still need it for some projects, or did these projects move to 3.1 and no longer require this backport?

**Comment by RandomShaper** [comment]
Precisely yesterday I was thinking about this. I think all my PRs for 3.0 are no longer relevant now we have 3.1 and 3.2 in the works.

I'm going to close all of them. And maybe also remove the cherry pick tag for 3.0 for others.

**Comment by akien-mga** [comment]
Closing as per above comment.

**Pull request closed without merging**
