### PR TITLE
Strip leading/trailing whitespace for project name in the project manager

### PR DESCRIPTION
**Pull request by Calinou**
This affects creating projects and renaming them.

### CODE REVIEW

**Review by fire — APPROVED** [review]
The use case of providing a better experience for when the developer names `project name     ` with extra spaces is a good idea.

**Review by aaronfranke — APPROVED** [review]
Makes sense. This also avoids repeated calls to `get_text()`. Note that project names with leading/trailing whitespace are not valid and the project manager won't let you create a project like that, but we can still make the display nicer if reading an invalid project name.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
