### PR TITLE
Fix possible crash at NativeScript::get_base_script

### LINKED ISSUE #20347: Engine crashes when using nativescript & typed gdscript
**Godot version:**
525384d8cc45a0976e0afb862c8a54244bbd72e7

**OS/device including version:**
ubuntu 16.04

**Issue description:**
When loading nativescript engine crashes with:
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fe2bcc9d4b0] (??:0)
[2] Vector<wchar_t>::_copy_from(Vector<wchar_t> const&) (/home/ville/godot-engine/core/vector.h:378)
[3] Vector<wchar_t>::operator=(Vector<wchar_t> const&) (/home/ville/godot-engine/core/vector.h:396)
[4] String::operator=(String const&) (/home/ville/godot-engine/core/ustring.h:63)
[5] NativeScript::set_class_name(String) (/home/ville/godot-engine/modules/gdnative/nativescript/nativescript.cpp:105)
[6] NativeScript::get_base_script() const (/home/ville/godot-engine/modules/gdnative/nativescript/nativescript.cpp:153 (discriminator 3))
[7] GDScriptParser::_get_function_signature(GDScriptParser::DataType&, StringName const&, GDScriptParser::DataType&, List<GDScriptParser::DataType, DefaultAllocator>&, int&, bool&, bool&) const (/home/ville/godot-engine/modules/gdscript/gdscript_parser.cpp:6227 (discriminator 1))
[8] GDScriptParser::_reduce_function_call_type(GDScriptParser::OperatorNode const*) (/home/ville/godot-engine/modules/gdscript/gdscript_parser.cpp:6476)
[9] GDScriptParser::_reduce_node_type(GDScriptParser::Node*) (/home/ville/godot-engine/modules/gdscript/gdscript_parser.cpp:5742 (discriminator 1))
[10] GDScriptParser::_check_block_types(GDScriptParser::BlockNode*) (/home/ville/godot-engine/modules/gdscript/gdscript_parser.cpp:7258)
[11] GDScriptParser::_check_class_blocks_types(GDScriptParser::ClassNode*) (/home/ville/godot-engine/modules/gdscript/gdscript_parser.cpp:7224)
[12] GDScriptParser::_parse(String const&) (/home/ville/godot-engine/modules/gdscript/gdscript_parser.cpp:7579)
[13] GDScriptParser::parse(String const&, String const&, bool, String const&, bool, Set<int, Comparator<int>, DefaultAllocator>*) (/home/ville/godot-engine/modules/gdscript/gdscript_parser.cpp:7614)
[14] GDScript::reload(bool) (/home/ville/godot-engine/modules/gdscript/gdscript.cpp:573)
[15] GDScript::_set(StringName const&, Variant const&) (/home/ville/godot-engine/modules/gdscript/gdscript.cpp:699 (discriminator 2))
[16] GDScript::_setv(StringName const&, Variant const&) (/home/ville/godot-engine/modules/gdscript/gdscript.h:58 (discriminator 11))
[17] Object::set(StringName const&, Variant const&, bool*) (/home/ville/godot-engine/core/object.cpp:455)
[18] ResourceInteractiveLoaderText::poll() (/home/ville/godot-engine/scene/resources/scene_format_text.cpp:529 (discriminator 3))
[19] ResourceFormatLoader::load(String const&, String const&, Error*) (/home/ville/godot-engine/core/io/resource_loader.cpp:138)
[20] ResourceLoader::_load(String const&, String const&, String const&, bool, Error*) (/home/ville/godot-engine/core/io/resource_loader.cpp:173 (discriminator 7))
[21] ResourceLoader::load(String const&, String const&, bool, Error*) (/home/ville/godot-engine/core/io/resource_loader.cpp:220)
[22] Main::start() (/home/ville/godot-engine/main/main.cpp:1673 (discriminator 2))
[23] godot(main+0xc0) [0x1027e46] (/home/ville/godot-engine/platform/x11/godot_x11.cpp:54)
[24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fe2bcc88830] (??:0)
[25] godot(_start+0x29) [0x1027cb9] (??:?)
-- END OF BACKTRACE --
```
I don't know if relevant, but earlier version printed "Parser bug: Class '_' not found".

**Steps to reproduce:**
Load gdns: preload("res://bin/simple.gdns").new()

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes #20347
I'm still unsure what's the cause of bug but this prevents the crash and adds an error on console.

### CODE REVIEW

**Comment by vnen** [comment]
This might fix #20347.

**Comment by karroffel** [comment]
This is very weird. `NSL->create_script()` only does a `memnew(NativeScript)`, I don't see how that would be `NULL` unless it's OOM.

**Comment by marcelofg55** [comment]
>  This is very weird. NSL->create_script() only does a memnew(NativeScript), I don't see how that would be NULL unless it's OOM.

I've checked and create_script does not return NULL, it returns a valid pointer.

With this PR I'm getting this error:
```
ERROR: get_base_script: Error at get_base_script for base=Node
   At: modules/gdnative/nativescript/nativescript.cpp:155.
```

I was just trying this change as well:
```
	NativeScript *script = (NativeScript*)NSL->create_script();
	Ref<NativeScript> ns = Ref<NativeScript>(script);

```
And with that I don't get the error at get_base_script anymore, I get a new error thought:
```
ERROR: _get_function_signature: Parser bug: Class '_' not found.
   At: modules/gdscript/gdscript_parser.cpp:6239.
```

Any thoughts about this?

**Comment by SaracenOne** [comment]
Just encountered this myself since I'm working with @BastiaanOlij's OpenVR driver. Bizzare.

**Comment by marcelofg55** [comment]
@karroffel Done, I've left an `ERR_FAIL_COND_V` to check for `!ns.is_valid` to prevent future problems.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
