### PR TITLE
Optional `store_compressed` flag for vram textures to reduce disk usage

### LINKED ISSUE #24501: VRAM compressed texture takes a lot of space when imported
I'm using Godot.alpha3 on OSX 10.14

`Video RAM` compressed textures are too big. 4kX4k texture takes 16mb on the drive. This is also affects exported game size.
```
[.]: ls -lah ghost.png
-rw-r--r--  1 jkbo  staff   480K Dec 20 14:16 ghost.png
[.]: ls -lah .import/ghost.png-f343bb4bd35f12f8f631dffe3b7d2891.*
-rw-r--r--  1 jkbo  staff    16M Dec 20 14:17 .import/ghost.png-f343bb4bd35f12f8f631dffe3b7d2891.etc2.stex
-rw-r--r--  1 jkbo  staff    91B Dec 20 14:17 .import/ghost.png-f343bb4bd35f12f8f631dffe3b7d2891.md5
-rw-r--r--  1 jkbo  staff    16M Dec 20 14:17 .import/ghost.png-f343bb4bd35f12f8f631dffe3b7d2891.s3tc.stex
-rw-r--r--  1 jkbo  staff   551K Dec 20 14:16 .import/ghost.png-f343bb4bd35f12f8f631dffe3b7d2891.stex
```
There is my import settings:
screenshot 2018-12-20 at 14 40 06

### PR DESCRIPTION
**Pull request by jkb0o**
This PR introduces `compression/store_compressed` flag for Video RAM textures, so when turned on,  textures got compressed before writing to disc. Also, when turned on, texture loading time increased by x2-2.5 compared to raw VRAM. Fixes #24501

There are average loading times:
```
Loading 4096x4096 texture, run from an editor:
lossless:                    942.0 msec
vram compressed:             380.2 msec
vram raw texture:            170.7 msec

Loading 4096x4096 texture, run from iphone5s:
lossless:                   1178.0 msec
vram compressed:             151.2 msec
vram raw texture:             85.0 msec
```

### CODE REVIEW

**Comment by akien-mga** [comment]
There are some style issues, see https://travis-ci.org/godotengine/godot/jobs/470985299 and http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

**Comment by volzhs** [comment]
isn't it better to have default on for most cases?

**Comment by jjay** [comment]
From my point of view, it is. But it will silently increase loading time. Also, it is easy to set default import options for textures as you want so any new texture will import as compressed.

**Comment by Calinou** [comment]
Is the file size difference noticeable when the project is exported and compressed (e.g. as an APK, a ZIP archive, Windows installer, …)?

**Comment by jjay** [comment]
@Calinou exported project size has almost no difference, only unpacked/installed package affected.

**Comment by volzhs** [comment]
although exported size is almost same, installed size is a matter for mobile.

**Comment by aaronfranke** [comment]
@jkb0o This needs a rebase before anything can be done with it.

**Comment by akien-mga** [comment]
Sorry for the delay reviewing this.

Code seems fine to me, but texture code is changing a lot in the `vulkan` branch which @reduz is working on for 4.0, so merging this for 3.2 would make rebasing a bit tricky. As such it might be better to wait for the 4.0 development cycle to merge this. If anyone wants the feature in the meantime, this PR should be relatively safe to cherry-pick.

@reduz also mentioned that LZMA might be a better compression for this - I'm not sure we support it yet, but you could also check what results ZSTD provides.

**Comment by aaronfranke** [comment]
@jkb0o Is this still desired? If so, it needs to be rebased on the latest master branch. Based on the above feedback, this PR may need significant changes due to Vulkan.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by jkb0o** [comment]
Well, I rebased branch to 3.2. I didn't work with the master for a while, so I need smth about a week to implement this feature for master (if needed). I'll close PR in case of fail.

**Comment by aaronfranke** [comment]
As stated above, this change is not good for the 3.2 branch, so changing the base branch seems rather pointless. I'll close this for now, it can be re-opened or re-created if rebased for master.

> implement this feature for master (if needed).

Pull requests must be made for the master branch first before the 3.2 version. So it is always needed.

**Pull request closed without merging**
