### PR TITLE
GDScript: Properly track extents of constants

### LINKED ISSUE #76054: `Mismatch in extents tracking stack` spam with a hanging `const` keyword
### Godot version

4.0.2.stable

### System information

Windows 10

### Issue description

Engine keeps spamming me this
изображение

### Steps to reproduce

No steps, issue happens from time to time absolutely randomly

### Minimal reproduction project

N/A

### LINKED ISSUE #76564: Parser bug: Mismatch in extents tracking stack.
### Godot version

4.0.2

### System information

Windows 10

### Issue description

EDIT: this was fixed by removing the offending files listed with the MRP and then dragging them back in from my desktop after opening the project~

I was developing my game then suddenly this started happening. I can no longer playtest my game.
I am not 100% sure what caused this but I believe at the time I was making a new inherited scene, saved it, then moved some scenes in the FileSystem tab?

image

### Steps to reproduce

No idea aaa- x-x

### Minimal reproduction project

Since I have no idea what caused it here's my early project :'D
https://drive.google.com/file/d/14JFZ420AelUNjBIth78msHY29rNjB55_/view?usp=share_link

I was working on these when the error occurred:
- Slot_0.tcsn
- Slot_Clickable.tscn
- Slot_Orphan.tscn
- Slot_Orphan.gd

### PR DESCRIPTION
**Pull request by vnen**
Even in the case of errors.

* Fix #76054
* Fix #76564

Note: I did a check across the parser to see if any other of these would be missing and didn't find anything. I won't mind if someone else wants to double check.

_Bugsquad edit:_ Issue linked.

### CODE REVIEW

**Comment by dalexeev** [comment]
> Note: I did a check across the parser to see if any other of these would be missing and didn't find anything. I won't mind if someone else wants to double check.

I found one more:

https://github.com/godotengine/godot/blob/23318e877890029f35856036b9c4e0bfa09cacc6/modules/gdscript/gdscript_parser.cpp#L2148-L2150

```cpp
complete_extents(pattern);
```

**Comment by vnen** [comment]
Updated to include @dalexeev's find. Thanks!

**Review by dalexeev — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
