### PR TITLE
Added Visual Studio 2013 CE project

### PR DESCRIPTION
**Pull request by ex**
note: before opening VS project be sure to run build.bat once

VS project updated for latest version, it still depends on SCons running first once and for now is only on DEBUG mode. It can help to study/modify the  engine directly from VS.

### CODE REVIEW

**Comment by RebelliousX** [comment]
Missing x64 build configuration?

**Comment by ex** [comment]
I'm not sure if godot can be compiled in x64

**Comment by RebelliousX** [comment]
fixnum.org/godot/

It seems it does, but fails for me.

**Comment by reduz** [comment]
I fixed this today

**Comment by akien-mga** [comment]
Could you update your branch with ```git rebase``` and then force push with ```git push --force``` (after checking ```git log``` of course to make sure it worked properly)? It should get rid of all those unnecessary "merge commits" listed above. See also this nice article for more info about merge vs rebase: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by ex** [comment]
I did what you said, Is this correct? If not I can fork again the repo and create a new pull

**Comment by akien-mga** [comment]
It doesn't look right no, it added many commits to this PR that already exist in the repo, it's weird. Did you just use ```git rebase```? Weird... If so yes maybe make another PR, that would be simpler I guess.

**Comment by ex** [comment]
Created a new pull request https://github.com/godotengine/godot/pull/3322

**Comment by akien-mga** [comment]
Thanks! :)

**Pull request closed without merging**
