### PR TITLE
Use checkbox for plugin status instead of option list

### LINKED ISSUE #36181: Plugin status field in Project Settings should be a toggle, not an option list
**Godot version:**
3.2

**OS/device including version:**
Windows 10

**Issue description:**
In Project Settings window the plugin list has a control to change its status. Plugin can only assume 2 statuses: [Active and Inactive](https://github.com/godotengine/godot/blob/master/editor/editor_plugin_settings.cpp#L142).
```swift
item->set_text(3, "Inactive,Active");
```

Therefore the control should be a toggle of some kind rather than an option list. It is not only unnecessary to have a list here, but it also takes a lot of time to toggle plugins when developing them.
image

Furthermore, selecting an already active option causes errors in console:
```
 editor/editor_node.cpp:3018 - Condition "p_enabled && plugin_addons.has(p_addon)" is true.
 editor/editor_node.cpp:3019 - Condition "!p_enabled && !plugin_addons.has(p_addon)" is true.
```

**Steps to reproduce:**
Add a plugin to your project, and try to change its status in settings.

**Minimal reproduction project:**
N/a

### PR DESCRIPTION
**Pull request by volzhs**
Close #36181

Screenshot from 2020-02-14 01-54-52

### CODE REVIEW

**Comment by Calinou** [comment]
I think this should actually be a CheckButton, not a CheckBox. See https://github.com/godotengine/godot/pull/30319.

**Comment by volzhs** [comment]
currently, it matches with others, like autoload, on/off on inspector, etc...

image
image

**Comment by pycbouh** [comment]
@volzhs Is the text on the second screenshot highlighted because the checkbox is "On", or because it's in focus? I ask, because it would benefit to have some color indication for enabled/active plugins, like it has now.

**Comment by volzhs** [comment]
I removed color change to make the same behavior with **Autoload** tab.

**Comment by Calinou** [comment]
@volzhs That makes sense. We can keep using CheckBox and eventually switch them all to CheckButton in the future (no pun intended).

**Comment by volzhs** [comment]
@Calinou that is good to change them all at once. :+1:

**Comment by nathanwfranke** [comment]
If one is disabled and one is enabled why do they both say Enable?

Also, they should say "Enabled" instead of "Enable" but I think that is a different issue

image

**Comment by pycbouh** [comment]
@nathanwfranke I think, volzhs simply made it behave exactly like it does for *Autoload* tab. In there it too is "Enable" and the text does not change with the tick.

**Comment by pycbouh** [comment]
@akien-mga Can this be merged and cherrypicked for 3.2?

**Comment by nathanwfranke** [comment]
I'm assuming since it's not even merged in master it's unlikely to be in 3.2 any time soon

**Comment by pycbouh** [comment]
@nathanwfranke 
> I'm assuming since it's not even merged in master

This is exactly what I'm asking for. For this to be merged into master, and then cherrypicked for 3.2.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
