### PR TITLE
Scons 4.0.0 - use the compile db tool provided by the upstream scons

### PR DESCRIPTION
**Pull request by RevoluPowered**
Scons 4.0.0 introduced compile db support directly.

### CODE REVIEW

**Comment by HaSa1002** [comment]
I guess there is either a bug on how we collect files for MSVC or upstream CompilationDatabase is broken.

**Comment by RevoluPowered** [comment]
> I guess there is either a bug on how we collect files for MSVC or upstream CompilationDatabase is broken.

The bug with MSVC is the way we do it, I discussed it with them previously we are doing something incorrectly basically as someone else from mongodb has it working fine

**Comment by neikeq** [comment]
>The bug with MSVC is the way we do it, I discussed it with them previously we are doing something incorrectly basically as someone else from mongodb has it working fine

I see. I will try to see if I can figure out what's causing it because this one is bugging me on Windows. Can't promise anything though.

Is there any difference between upstream compiledb support and the one we were using before?

**Comment by HaSa1002** [comment]
> Is there any difference between upstream compiledb support and the one we were using before?

Yes. 100 lines of code ... 
https://github.com/SCons/scons/blob/e477504c69f81bee2d96d6ecbe757a296f1d9c83/SCons/Tool/compilation_db.py

**Comment by RevoluPowered** [comment]
> I guess there is either a bug on how we collect files for MSVC or upstream CompilationDatabase is broken.

We have been discussing in IRC add_source_files should be replaced with env.AddLibrary() and properly / explicitly specify dependencies, this will mean there is explicit deps of deps :) and targets will rebuild correctly.

This will also mean we can remove some hacks from the SLN generator. I will look into this when I get some free time this week

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
