### PR TITLE
Allow to keep local transform when reparenting in editor

### LINKED ISSUE #20632: Reparent node in editor keeping local transform
When doing some UI stuff, I sometimes wanted to move some Control to another Control, but wanted the position to change relatively. However, when I reparent something (by drag and drop on node tree), it automatically updates local position, so the node stays in the same place globally.

My proposal would be to allow for keeping the local position when moving nodes in tree from editor, e.g. when you hold CTRL or ALT key.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #20632

Uses ~~Alt~~ Shift to work. I guess there could be an indicator somewhere that this is possible. Any suggestions?

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Keep in mind that certain Linux desktop environments might not interact well with Alt + Drag.

**Comment by groud** [comment]
Looks like a good idea, but we probably need to add and entry in the right click menu for discoverability.

**Comment by KoBeWi** [comment]
> we probably need to add and entry in the right click menu for discoverability

I don't think it belongs to any right-click menu. I though about something more like when you drag an image on the viewport and a label appears in the corner saying that you can change type. But not sure if my option needs its own label or utilize that one.

**Comment by groud** [comment]
Ah indeed, it might make sense to have a popup popping up automatically when dropping the node on it's new parent. 

But what I meant, which is likely a simpler solution for now, is to add it there:
2019-04-24-171635_3840x1600_scrot
An entry like "Reparent keeping transform"

**Comment by KoBeWi** [comment]
Huh, funny how current reparent menu already has this option as one of these hidden checkboxes.

So how to tell inside this popup that you can hold Alt while dragging?

**Comment by groud** [comment]
> So how to tell inside this popup that you can hold Alt while dragging?

Put it in the tooltip of the entry. :)

**Comment by KoBeWi** [comment]
Neat! Pushed. Is this the correct way?

**Comment by groud** [comment]
Well not exactly. I would add another entry, just after the "reparent" one called "reparent keeping global transform" (that indeed would act as the reparent entry but keeping the transform). and on this entry, I would add a tooltip saying "You can reparent nodes while keeping their transform by dragging & dropping them with the ALT key pressed"

**Comment by KoBeWi** [comment]
> I would add another entry

Uh, but by this:

> Huh, funny how current reparent menu already has this option as one of these hidden checkboxes.

I meant this:
image

The option is already there. Sure, I could just hide the checkbox and make another same menu, where it's invisibly unchecked, but... why?

My tooltip is supposed to mimic this text:
image

Maybe the label would really be a better option.

**Comment by groud** [comment]
Ah indeed, I did not see that. I guess it makes sense to have it with a label then. :)

**Comment by KoBeWi** [comment]
So this: https://gfycat.com/SorrowfulEarlyHuemul

Adding a stupid label made 3-line PR into 54 lines .-.

Anyways, it's bugged. When you move node outside tree and drop, the label will reappear when you enter mouse inside tree, even though you are not dragging anything. I have no idea how to fix this, so any advice is welcome ;_;

**Comment by groud** [comment]
> Adding a stupid label made 3-line PR into 54 lines .-.

That happens. ^^ But discoverability is important so they might be worth it.

> Anyways, it's bugged. When you move node outside tree and drop, the label will reappear when you enter mouse inside tree, even though you are not dragging anything. I have no idea how to fix this, so any advice is welcome ;_;

Well, in any case, I don't think the label can be added into the canvas item editor plugin, because it won't appear in the 3D workspace. I think we should likely figure out a more global solution, because that kind of information should likely be given a unique place.

I have two ideas for now on:
- Make the label follow the cursor (the info would appear when about to drop on the potential place)
- Add an info bar somewhere in the editor, where we could push labels (a little bit like what blender does if I am not mistaking)

Until then, I don't think we can keep the PR as is. As making the file system dock depend on the canvas item editor is not a good solution. Probably that adding a discoverability hint can wait, unless you want to implement a more global solution.

**Comment by KoBeWi** [comment]
I totally forgot that CanvasItemEditor is 2D only ;_;

So I'll just revert the label and if the PR gets merged, I'll create issue about discoverability.

**Comment by KoBeWi** [comment]
Ok, label and tooltip reverted.

**Comment by akien-mga** [comment]
> Keep in mind that certain Linux desktop environments might not interact well with Alt + Drag.

Indeed, under KDE/KWin, Alt+Drag grabs the window and moves it around.

**Comment by KoBeWi** [comment]
Guess I'll just change it to Shift then >.> (but IMO Alt makes most sense for this purpose)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
