### PR TITLE
Implement add_directly to animation tree node add2 and add3

### PR DESCRIPTION
**Pull request by TokageItLab**
For [#37661](https://github.com/godotengine/godot/issues/37661)

The current algorithm adds the transformations after the subtraction of the difference.
So, for compatibility, I implemented a checkbox to add the transforms directly.

### CODE REVIEW

**Comment by Zireael07** [comment]
I assume 'directry' in PR title is a typo, right?

**Comment by TokageItLab** [comment]
Ah sorry, it is miss type

**Comment by TokageItLab** [comment]
I cleaned up commits

**Comment by fire** [comment]
Wanted to check for mergability, but the pr needs an update.

**Comment by TokageItLab** [comment]
Superseded #53903.

**Pull request closed without merging**
