### PR TITLE
Allow right click menu anywhere in filesystem dock

### PR DESCRIPTION
**Pull request by ghost**
Fixes the second issue in #12322

Allows right click menu anywhere on the folder tree or files list rather than just ontop of items.

This has been done by setting the mouse filter to pass on the tree & item list controls, rather than using the _rmb_select callbacks as these only fire if an item was actually clicked. There may be a nicer or different way to go about this that i am missing though.

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs rebase after the merge of your previous filesystem PRs, sorry for the delay merging those :)

**Comment by MillionOstrich** [comment]
@akien-mga thanks for merging the other PRs :)

It turns out that using MOUSE_FILTER_PASS interferes with dragging (the drag event gets passed to the parent, which will replace `gui.drag_data` with an empty variant). See:

https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#1838
https://github.com/godotengine/godot/blob/master/scene/gui/control.cpp#L624

As a consequence I would need to implement the virtual drag methods from control rather than using drag forwarding and work out which of the two filesystem controls the event is in (like this PR is doing for right click). This feels like i am missing something and am overcomplicating things a bit, so if you (or anybody else) have a suggestion on a better way to deal with this i would be greatful!

Additionally, is the way MOUSE_FILTER_PASS works with drag currently worth revising? The way it currently works can lead to bugs (it causes a crash in this PR for example). Perhaps it could do one of the following instead?
- Skip child controls with MOUSE_FILTER_PASS, as their drag_data will be overwritten anyway.
  - This wouldn't change the final result of drag_data and would at least mean that a control won't handle the drag event if its result would be ignored.
- Don't overwrite drag_data if the control returns a NIL variant
  - Would mean the parent gets the final say on the drag data, but would still mean the child tries to set up the drag event for it to be overwritten. 
  - Could visit the nodes in reverse order to mitigate this but that would add complexity.
- Stop when a control provides drag_data which isn't NIL
  - The first control to handle the drag event wins, which might not be consistent with how pass works for other mouse events?

**Comment by akien-mga** [comment]
Ah sorry I had forgotten about this PR and just merged #13105; I haven't check the two of them in details, so if you think your PR had a more interesting implementation, feel free to rebase to change the new state.

**Comment by MillionOstrich** [comment]
The merged PR probably does things in a better way than this PR. The only change i would have done is to call into the existing rmb select method (that way we get show in explorer too) but i guess that isn't really a big deal.

**Comment by akien-mga** [comment]
> The only change i would have done is to call into the existing rmb select method (that way we get show in explorer too)

That sounds like a good improvement if you're still up for it :)

**Pull request closed without merging**
