### PR TITLE
Compile on OpenBSD (bad)

### PR DESCRIPTION
**Pull request by a12n**
I was playing with Godot on OpenBSD. A few small changes were neccessary to make it compile.

### CODE REVIEW

**Comment by akien-mga** [comment]
Hi @a12n and sorry for the delay. Could you rebase your branch on the current godotengine/master branch, so that it could be merged?

**Comment by a12n** [comment]
Ugh, looks like I've merged `libao` branch into this one. Is it acceptable to import it that way? Or should I do/redo something?

**Comment by akien-mga** [comment]
It would be better to clean it up to only have the OpenBSD related changes yes, especially as your libao branch is quite big and will likely need more thorough review. I'd advise you to create a new branch for the OpenBSD fixes and cherry-pick the relevant commits there.

**Comment by a12n** [comment]
OK, I've created #2849.

**Comment by akien-mga** [comment]
Thanks! :)

**Pull request merged**
