### PR TITLE
[RichTextLabel] Add support for tab stops.

### PR DESCRIPTION
**Pull request by bruvzg**
Same as https://github.com/godotengine/godot/pull/76129 for RTL.

Tab stops a configurable per paragraph, using `push_paragraph` argument or `[p ... tab_stops=x,x,x]` tag.

### CODE REVIEW

**Comment by MewPurPur** [comment]
Can this be used for our own code samples in the class reference in the editor?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by YuriSizov** [comment]
I think it needs another rebase due to some conflicts with godot-cpp, which failed the CI.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
