### PR TITLE
Fixes 64 bit MSVC builds, disables bits parameter

### PR DESCRIPTION
**Pull request by Griefchief**
Also Enables automatic detection of architecture for the MSVC compilers.
Builds without assembly optimisations for x64
Closes issue #3098

Info: Currently godot cannot be compiled out of the box for 64 bit on MSVC compiler, because until this fix we were not properly seting up the MSVC compiler to compile for different architectures... 

In fact, setting arhitecture in MSVC is somewhat impossible for scons (a wee bit hard manually, and shoudn't be done, because it would clash with attempts of the developer to set it up for the arhitecture he wants to build for...)

So, in light of that, this fix disables the bits parameter in scons for MSVC, but it also enables detection of the compiler and configures scons bits automatically instead (ie based on which dev prompt the user has invoked, or which vcvarsall.bat setting it has invoked...).

I hope the instructions that scons gives on errors are sufficient to allow you to manage to test properly. I tested on MSVS 2015 Community Eddition (cl.exe version 18) prompts and vcvarsall.bat, but this should support a wide range of MSVC versions. Needs testing, of course.

This pull changes how MSVC build parameters work so Travis test should fail if it is setup to test MSVC builds (seems it's not setup).

Best regards.

P.S. sys.exit() used because i saw it used in SConstruct
P.P.S. Please let me know if i need to rebase this properly.

### CODE REVIEW

**Comment by eska014** [comment]
Tested this with VS2013 and it works in amd64 mode

**Comment by akien-mga** [comment]
I'd like to have a couple other Windows users to test the PR before merging, I don't know much about the Windows compilation ecosystem myself :) (e.g. trying to build both 32bit and 64bit binaries with the corresponding MSVC versions, check that MinGW still behaves as expected).

**Comment by vnen** [comment]
I thought this was already merged... Will try later today.

**Comment by vnen** [comment]
Forgot to mention but this patch is indeed working fine and can be merged IMO. The problem is that are problems when compiling for 64-bits on MSVC is not currently working (see #4113).

I can't test with Mingw on Windows (it never worked for me) though I guess this does not interfere, as the code is added only in the MSVC section of `detect.py`. At least in Linux it is working as intended, I guess Mingw on Windows would be the same.

**Comment by akien-mga** [comment]
Thanks, let's merge then.

**Pull request merged**
