### PR TITLE
Added Spawner Timer Node

### PR DESCRIPTION
**Pull request by bitsycore**
-It spawn selected Scene at a certain rate. 
-You can make it endless or with a limited quantity.
-You can stop automatically the timer if it failed to spawn (Scene error or quantity over). 
-You can manually Spawn with ```spawn()``` (it will decrements the spawn quantity by one if it's not endless). It return the node created and add it automatically  as child to the Spawner.
-You can ```spawn_bypass()``` to spawn regardless of the Spawner being endless or quantity=0. It return the node created and add it automatically  as child to the Spawner.

A signal is emitted when one scene is Spawned and it have as a parameter the Node. 
```spawned(node: Node)```
A signal is emitted when you spawned the full quantity
```spawned_all()```

### CODE REVIEW

**Comment by Calinou** [comment]
I don't see much point in having this in core. This can be implemented in GDScript in an hundred lines of code or so.

PS: Large features should be discussed in [godot-proposals](https://github.com/godotengine/godot-proposals) before implementing them, so that we can reach a consensus.

**Comment by Coldragon** [comment]
It was my first try with editing the engine and I though that idea might be usefull.
I will create a  godot-proposals later to discuss about that and i'l explain the main purpose of that and some upgrade I'm not sure how to handle. (Example : Position of the spawned Scene, the node itself is not a Node2D so can't use the node pos)

**Comment by Zireael07** [comment]
I think it's more suited to external addons, such as @willnationsdev's Godot-NEXT repo

**Comment by KoBeWi** [comment]
Eh, so this is basically a standard Timer with "conveniently" supplied PackedScene to spawn.
...
That doesn't sound useful. A standard Timer is actually better, because your Spawner can only instance something as a child of that spawner. It's not Node2D nor Spatial, so the new object won't even have a correct position. So you need to go out of your way and manually reparent the spawned node using the signal. Heh. You can of course add more functionality to make it more flexible, but why would it have to be in core.

This is the GDScript implementation of actually useful part of the spawner:
```
func _on_Timer_timeout():
    var node = preload("MyScene.tscn").instance()
    add_child(node)
```
I highly doubt that creating a formal proposal would help it xd

**Comment by girng** [comment]
Can't this already be done with gds?

**Comment by Xrayez** [comment]
@Coldragon feel free to discuss your proposal at non-official [godot-ideas](https://github.com/godot-extended-libraries/godot-ideas) repository which targets proposals that are nice-to-have to be implemented, because [godot-proposals](https://github.com/godotengine/godot-proposals) mostly targets core development. You do happen to write stuff in C++ so you could as well implement it as a module if you want to get familiar with C++ engine development side.

There are a number of perfomance-critical aspects of spawning which can be solved, for instance how would you go about spawning collision bodies which don't collide with existing level geometry (as well as already-spawned bodies)?

I'd personally implement this in core myself but it really has to be a universal solution which covers a lot of use cases and which is configurable, and for that you need to know what possible behavior people expect from a node spawner to fulfill those needs, which could be a lot of work actually, that's why I think the godot-proposals repository asks you that your feature is proven to be useful in existing projects before opening a proposal.

**Pull request closed without merging**
