### PR TITLE
[3.5] Avoid WebGL shader error on Safari/iOS

### LINKED ISSUE #62377: Safari renders all my 3d models black (GLES3)
### Godot version

Godot_v3.5-rc4

### System information

IOS 15.5, Safari

### Issue description

When making a web build (HTML5) with a few 3d cubes a standard material and a point light, the scene looks correct on a Galaxy tablet with chrome. But on my Iphone 12 (v15.5) using the Safari browser all 3d models are rendered black for some reason.

In the Image: 1. Iphone, 2. Galaxy tablet.

image

### Steps to reproduce

Add a cube or some other model and built it for HTML5. Try running it in the Safari browser on mobile.

### Minimal reproduction project

[MobileTestProjectBlackModels.zip](https://github.com/godotengine/godot/files/8976708/MobileTestProjectBlackModels.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #62377.

### CODE REVIEW

**Comment by RandomShaper** [comment]
Curiously, this avoids the linking error, but the shaders still don't render anything. I've provided more info in the issue thread.

**Comment by akien-mga** [comment]
So there might actually be two different bugs in Safari 15's ANGLE backend?

- Shader compilation for ternary operators (which this works around)
- Something else that breaks shaders further

I guess we should wait for feedback from upstream or for a complete workaround before merging partial changes.

**Comment by RandomShaper** [comment]
They are two things indeed, but very closely related. My gut feeling is that if they fix the deepest bug, the ternary operator won't be a problem by itself.

**Comment by RandomShaper** [comment]
Knowing the problem is deeper, I'm archiving this one. If at some point we decided to do exhaustive investigation for a workaround, I'd create a new PR with the relevant fix.

**Pull request closed without merging**
