### PR TITLE
Fix left aligned integer sign in string formatting

### LINKED ISSUE #60657: Incorrect string formatting when padding a negative integer to the right
### Godot version

3.4.4.stable, 3.5.beta4

### System information

N/A

### Issue description

When string formatting, padding a negative integer to the right using integer placeholders (`d`, `o`, `x`, `X`) is incorrect, see below.

### Steps to reproduce

```
tool
extends EditorScript

func _run() -> void:
	print("|%-10s|%-10s|%-10s|%-10s|%-10s|%-10s|" % ['"%10d"', '"%-10d"', '"%-10o"', '"%-10x"', '"%-10X"', '"%-10.0f"'])
	print("-".repeat(6 * (10 + 1) + 1))
	var x := -1
	for zero_count in 9:
		print("|%10d|%-10d|%-10o|%-10x|%-10X|%-10.0f|" % [x, x, x, x, x, x])
		x *= 10
```
Output:
```
|"%10d"    |"%-10d"   |"%-10o"   |"%-10x"   |"%-10X"   |"%-10.0f" |
-------------------------------------------------------------------
|        -1|1       - |1       - |1       - |1       - |-1        |
|       -10|10     -  |12     -  |a       - |A       - |-10       |
|      -100|100   -   |144   -   |64     -  |64     -  |-100      |
|     -1000|1000 -    |1750 -    |3e8   -   |3E8   -   |-1000     |
|    -10000|1000-0    |2342-0    |2710 -    |2710 -    |-10000    |
|   -100000|100-000   |303-240   |186a-0    |186A-0    |-100000   |
|  -1000000|10-00000  |36-41100  |f424-0    |F424-0    |-1000000  |
| -10000000|1-0000000 |4-6113200 |989-680   |989-680   |-10000000 |
|-100000000|-100000000|-575360400|5f-5e100  |5F-5E100  |-100000000|
```

### Minimal reproduction project

[FormatStringNegativeIntegerRightPadding.zip](https://github.com/godotengine/godot/files/8596884/FormatStringNegativeIntegerRightPadding.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #60657

### CODE REVIEW

**Comment by akien-mga** [comment]
Might be worth adding some tests to cover this.

**Comment by kleonc** [comment]
It's still incorrect, padding with zeros should always add zeros from the left. Try `"%-010d" % -1 `. Something like this should work:
```
// Padding with zeros.
if (pad_with_zeroes) {
	str = str.lpad((value < 0 || show_sign) ? min_chars - 1 : min_chars, String("0"));
}

// Sign.
if (show_sign && value >= 0) {
	str = String("+") + str;
} else if (value < 0) {
	str = String("-") + str;
}

// Padding with spaces.
if (!pad_with_zeroes) {
	if (left_justified) {
		str = str.rpad(min_chars, String(" "));
	} else {
		str = str.lpad(min_chars, String(" "));
	}
}
```

**Comment by timothyqiu** [comment]
It's currently an error trying to use padding with left justification.

> left justification cannot be used with zeros as the padding

But since C/C++ `printf` allows it by ignoring `0` flag when `-` flag exists, I think it's good to allow it in GDScript too. I'll add this along with some unit tests.

**Comment by timothyqiu** [comment]
Ah... I messed up my git branch :( I'll open a new one later...

**Comment by akien-mga** [comment]
> Ah... I messed up my git branch :( I'll open a new one later...

Note that the you can always force push a new branch on top of your existing remote branch, like `git push fork new_branch:left-fmt`.

**Comment by timothyqiu** [comment]
I'm not sure why GitHub auto-closed this PR because my wrong push. But when I later did force push a new branch to the same existing remote branch, the action is not detected any more, and GitHub does not let me reopen this PR ¯\\\_(ツ)\_/¯

**Comment by akien-mga** [comment]
Ah yes if you push the `master` branch to the PR branch, then there's no content for the PR anymore (no difference to `master`) and GitHub will force close it.

**Pull request closed without merging**
