### PR TITLE
Mention `CollisionPolygon2D.polygon` is local to the given CollisionPolygon2D

### PR DESCRIPTION
**Pull request by jsjtxietian**
For https://github.com/godotengine/godot/issues/86942

### CODE REVIEW

**Review by Sauermann — APPROVED** [review]

**Review by AThousandShips — APPROVED** [review]

**Comment by AThousandShips** [comment]
(Making a note to update the description of this class, it's copied from the 3D case and talks about a prism which isn't relevant to 2D geometry)

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4.

**Pull request merged**
