### PR TITLE
Misc. improvements to visual shader's "Add Node" dialog

### PR DESCRIPTION
**Pull request by ghost**
- Right-click to open dialog is more reliable
- Categories can no longer be selected, and a single-click will fold/unfold them
- Dialog will always popup within window bounds
- Search bar is focused upon popup
- First item will be automatically selected when searching for a node
- List of shader nodes can be navigated with keyboard without search bar losing focus

### CODE REVIEW

**Comment by homer666** [comment]
https://github.com/godotengine/godot/blob/0226093122474f45b8e185f69f64241e38742803/editor/plugins/visual_shader_editor_plugin.cpp#L913-L916

I needed to make a special case for the Enter key here because simply passing the input event to `gui_input()` didn't work. I don't really know what I'm doing so I would appreciate if someone could explain what the problem is.

**Comment by Chaosus** [comment]
> Categories can no longer be selected, and a single-click will fold/unfold them

There was a reason I leave it selectable - if the user selects a node and then double-clicks on the category - the node will be created - which is incorrect and irritating.. Does this PR solve this issue ?

**Comment by homer666** [comment]
Nah, I came across that behaviour but just ignored it. I'll try my hand at fixing it though (probably tomorrow)

**Comment by homer666** [comment]
Okay, I refactored the dialog's input code, that issue you mentioned should be fixed now. Do test it though.

**Comment by Chaosus** [comment]
Yeah, seems fine now

**Comment by homer666** [comment]
https://github.com/godotengine/godot/blob/adf0bf6d5777dce6b2ee9fefcde704f471c4213e/editor/plugins/visual_shader_editor_plugin.cpp#L838
https://github.com/godotengine/godot/blob/adf0bf6d5777dce6b2ee9fefcde704f471c4213e/editor/plugins/visual_shader_editor_plugin.cpp#L867
I introduced a lot of redundancy between these two functions. Would it be better if I modified `_show_members_dialog()` to optionally spawn at mouse position (controlled via a parameter)?

**Comment by Chaosus** [comment]
@homer666 Yes, of course

**Comment by homer666** [comment]
Done.

**Review by Chaosus — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
