### PR TITLE
Consolidate JSON, JSONParseResults and JSONParser into JSON

### PR DESCRIPTION
**Pull request by madmiraal**
Following https://github.com/godotengine/godot/pull/44574#issuecomment-751719503.

Supersedes #44574
Part of #16863

Removes `JSONParser` and `JSONParseResults`.

Includes renaming:
- `JSON::parse_string()` to `parse()`
- `JSON::decode_data()` to `stringify()`

Note 1: `stringify()` returns the `String` instead of `Error::Ok`.
Note 2: Adds a `to_json_string()` method to `Variant` for use within the engine.

**Edit:** JSONParser has been renamed to JSON following PR Review meeting ([comment](https://github.com/godotengine/godot/pull/44806#issuecomment-864112026))

### CODE REVIEW

**Comment by dalexeev** [comment]
Maybe rename the JSONParser to JSON?

**Comment by Xrayez** [comment]
> In my opinion, the singleton was more convenient, now you need to create a JSONParser instance every time.

I really think that we need support for defining static functions for scripting as provided by built-in classes, see my comments on this at https://github.com/godotengine/godot-proposals/issues/1101#issuecomment-647784186 which also happens to mention JSON, this would solve the convenience issue...

**Comment by dalexeev** [comment]
On the other hand, a new `JSONParseResult` instance was already created every time `JSON.parse()` was called. So the difference is not very big, but it is consistent with `XMLParser`.

**Comment by madmiraal** [comment]
Rebased following merge of #44859 and #44911.

**Comment by madmiraal** [comment]
Rebased following merge of #44989.

**Comment by madmiraal** [comment]
Rebased following merge of #45737.

**Comment by madmiraal** [comment]
Rebased following merge of  #46200.

**Comment by madmiraal** [comment]
Rebased following merge of #46551.

**Comment by madmiraal** [comment]
Rebased following merge of #46713 and #46728.

**Comment by madmiraal** [comment]
Rebased following merge of #40804.

**Comment by madmiraal** [comment]
Rebased following merge of #48159, #48239, #47386 and #47974.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting today and approved consolidating those APIs in one place (again, I remember this PR followed a discussion in another meeting). The only change we'd suggest is that since the new `JSONParser` class is also used for writing (`stringify`), it should maybe renamed to just `JSON`. The other `*Parser` classes we have like `VariantParser` and `XMLParser` only do parsing, not writing.

**Comment by madmiraal** [comment]
Renamed `JSONParser` to `JSON`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Faless** [comment]
I don't understand why the engine exposed `JSON::stringify` is no longer static.
Having to write in engine every time:

```
JSON json
json.stringify()
```

is quite awful.

**Comment by madmiraal** [comment]
@Faless The PR includes the addition of a `to_json_string()` method to Variant for use within the engine.

> Note 2: Adds a `to_json_string()` method to Variant for use within the engine.

https://github.com/godotengine/godot/blob/56d712686496845cab3bfd6a6ed67e4efc2c39d5/core/variant/variant.cpp#L1842-L1845

Note: If the variable is not a `Variant` but can be converted to one there is also this option: `Variant(my_variable).to_json_string()` for example:
https://github.com/godotengine/godot/blob/56d712686496845cab3bfd6a6ed67e4efc2c39d5/modules/gdscript/language_server/gdscript_language_protocol.cpp#L281-L282

**Comment by Faless** [comment]
@madmiraal thanks for the clarification. I had totally missed it. My apologies.

**Pull request merged**
