### PR TITLE
GDScript: Don't use pool for reference types

### LINKED ISSUE #73889: Godot.RC3 .. RC5: breaks `timer.connect()`, the program is stopped forever
### Godot version

v4.0.rc5.official [6296b4600]

### System information

Windows 19

### Issue description

After upgration to Godot.RC3 .. RC4 .. RC5 my plugin is broken.

I provide a function to wait for a function to provide an expected value.

As example it waits for function 'obj_value' from the instance `TestIterativeValueProvider` is providing null.
```
func test_foo(timeout = 20000) -> void:
	var value_provider := TestIterativeValueProvider.new(RefCounted.new(), 5, null)
	await assert_func(value_provider, "obj_value").is_null()
````
Now the execution stops at await and is not executed further

I have reduced the code as much as possible to find the root of the cause.
The problem occurs when using `timer.connect("timeout", _on_timeout)`.

### Steps to reproduce

run the attached example 

a) if you run `await assert_that().it_works()` the function is continue after the signal `done` is emitted
b) if you run `await assert_that().not_works()` the function is stuck
 --  b1) also strange when using variant (b) and remove the return type from the function `assert_that` it works too

### Minimal reproduction project

[timer_await.zip](https://github.com/godotengine/godot/files/10828504/timer_await.zip)

### LINKED ISSUE #73998: GDScript: `variant_temporary.get_object()` returns `bool` instead of `Object`
### Godot version

v4.0.rc.custom_build [1bd0b296e]

### System information

Kubuntu 22.10

### Issue description

When a method that returns `Object` is called on an `Variant` temporary, `true` or `false` is returned, not the object. The bug does not occur when:

* call on a variable;
* call on a `Object`-derived temporary;
* or the method returns not an `Object`.

See also #70637 (similar but unrelated issue) and #73889 (note that `RefCounted`-derived temporaries have a different bug).

### Steps to reproduce

```gdscript
@tool
extends EditorScript

class TestObject extends Object:
    pass

func _run() -> void:
    var lambda = func (): pass
    var _signal = Signal(property_list_changed)
    var button = OptionButton.new()
    var object = TestObject.new()

    print(lambda.hash()) # 3839645819
    print((func (): pass).hash()) # 606297262

    print(lambda.get_object()) # <GDScript#-9223370338782411611>
    print((func (): pass).get_object()) # true

    print(_signal.get_name()) # property_list_changed
    print(Signal(property_list_changed).get_name()) # property_list_changed

    print(_signal.get_object()) # <EditorScript#-9223369888683202401>
    print(Signal().get_object()) # false
    print(Signal(property_list_changed).get_object()) # true

    print(button.get_popup()) # @@18073:<PopupMenu#2145134916941>
    print(OptionButton.new().get_popup()) # @@18079:<PopupMenu#2145671771020>

    print(object.get_script()) # <GDScript#-9223369888699960432>
    print(TestObject.new().get_script()) # <GDScript#-9223369888699960432>
```

I also noticed that after editing this script, it cannot be reloaded without restarting the editor. It looks like the `Signal()` is causing this error.

```
modules/gdscript/gdscript.cpp:828
Condition "!p_keep_state && has_instances" is true. Returning: ERR_ALREADY_IN_USE
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by vnen**
Since they need to be properly initialized and finalized to adjust the reference counter.

Note that there's an change in indentation level, it's better to hide whitespace changes when reviewing.

Fix #73889
Fix #73998

### CODE REVIEW

**Comment by RandomShaper** [comment]
I don't really understand every implication of this, so my review will come as a question whose answer will help me understand the change better: how this solution compares with the one I was drafting (https://github.com/godotengine/godot/commit/dcf4f382f5df6dd6b1ace5aae78c66e704b4f42c)? (It may not be completely right as of now, but you get the idea.)

**Comment by vnen** [comment]
@RandomShaper I just updated the PR with a new change in one line you added. I changed it check for `Variant::NIL` instead of `OBJECT`, because with this change there'll be no slots of `OBJECT` type.

Essentially this does not use the reference type for pools of temporary stack slots. This are separated by type so at runtime it does not need to change the type in the Variant, only the internal data, which makes it faster (especially for the lack of need to `clear()` the Variant). This is problematic for reference types since they a need a proper clear to update the ref count.

With this change it will always emit a type change, which is a bit slower technically, but avoid issues.

What was happening before is that a slot of type `OBJECT` was being assigned `false` so it changed the type in the actual temporary, but the slot is still set as `OBJECT`, so some needed type changes were being omitted.

**Comment by vnen** [comment]
BTW, maybe it is better to have a clear start/end statement boundary and only clear temporaries at that point. It could even check if the used temporaries is zero, as it should be the case after the statement is over. But for now this here is a less intrusive change and safer to merge quickly.

**Comment by RandomShaper** [comment]
Do you think, then, that there's a point that I put my commit https://github.com/godotengine/godot/commit/dcf4f382f5df6dd6b1ace5aae78c66e704b4f42c into a draft PR for the future?

**Comment by RandomShaper** [comment]
The `await assert_that().not_works()` case in the MRP in #73889 still doesn't work as expected by the OP with this PR merged.

**Comment by vnen** [comment]
> The `await assert_that().not_works()` case in the MRP in #73889 still doesn't work as expected by the OP with this PR merged.

That is odd, I tested and it worked. I'll try again later.

**Comment by RandomShaper** [comment]
Pleae check #74101.

**Comment by vnen** [comment]
Superseded by https://github.com/godotengine/godot/pull/74101.

**Pull request closed without merging**
