### PR TITLE
Navmesh support for GridMaps

### PR DESCRIPTION
**Pull request by Anarchid**
gridnavmesh
This still requires clean-up and possibly fixes. I'm totally unsure how it works wrt baking, etc.

A review of what to fix up would be good.

### CODE REVIEW

**Comment by Anarchid** [comment]
Cleaned up most garbage and squashed into a single commit.

**Comment by kubecz3k** [comment]
Out of curiosity, will this work if I'm building level from couple GridMaps? (like for example room1 is on different Gridmap than room2)

**Comment by Anarchid** [comment]
Yes, as long as both GridMaps are children of the same Navigation node.

**Comment by akien-mga** [comment]
That's great, nice work!
You seem to have an indentation issue though: most of Godot's code uses tabs as indentation, but you used 4 spaces, so your changes are badly indented compared to the rest of the code (see the diff as rendered by GitHub). Could you rebase to use tabs too?

**Comment by Anarchid** [comment]
Sure, i'll try to fix whitespace sometime this week.

**Comment by Anarchid** [comment]
Fixed tab/space issues, removed most of the commented-out prints. Someone else should deal with ones that came before, and replace them with useful comments instead!

**Comment by OliPerraul** [comment]
@Anarchid Hey Im trying to get this working in my game? Do you by any chance have a sample project? Thanks!

**Pull request merged**
