### PR TITLE
GDNative: Fix size mismatch on 32-bit platforms for Signal and Callable

### LINKED ISSUE #48645: GDNative Callable and Signal size mismatch on Android x86
**Godot version:**
`master` (048abb50)

**OS/device including version:**
Fedora 34 compiling for Android x86

**Issue description:**
GDNative build fails for Android x86 in the `master` branch with this error:
```
/root/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -o modules/gdnative/gdnative/callable.android.opt.debug.x86.o -c -std=gnu++17 -frtti -fno-exceptions -O2 -fomit-frame-pointer -ftree-vectorize -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -fvisibility=hidden -fno-strict-aliasing -mstackrealign -target i686-none-linux-android -fno-integrated-as -gcc-toolchain /root/sdk/ndk/21.4.7075529/toolchains/x86-4.9/prebuilt/linux-x86_64 -w -Werror=return-type -isystem /root/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include -isystem /root/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++abi/include --sysroot=/root/sdk/ndk/21.4.7075529/sysroot -isystem /root/sdk/ndk/21.4.7075529/sysroot/usr/include/i686-linux-android -isystem /root/sdk/ndk/21.4.7075529/sources/android/support/include -DNDEBUG -DDEBUG_ENABLED -D__ANDROID_API__=24 -DNO_STATVFS -DGLES_ENABLED -DANDROID_ENABLED -DUNIX_ENABLED -DVULKAN_ENABLED -DNO_FCNTL -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -Imodules/gdnative/include -Ithirdparty/libpng -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src/include -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src/layers -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src/layers/generated -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/android -I. modules/gdnative/gdnative/callable.cpp
/root/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -o modules/gdnative/gdnative/signal.android.opt.debug.x86.o -c -std=gnu++17 -frtti -fno-exceptions -O2 -fomit-frame-pointer -ftree-vectorize -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -fvisibility=hidden -fno-strict-aliasing -mstackrealign -target i686-none-linux-android -fno-integrated-as -gcc-toolchain /root/sdk/ndk/21.4.7075529/toolchains/x86-4.9/prebuilt/linux-x86_64 -w -Werror=return-type -isystem /root/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include -isystem /root/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++abi/include --sysroot=/root/sdk/ndk/21.4.7075529/sysroot -isystem /root/sdk/ndk/21.4.7075529/sysroot/usr/include/i686-linux-android -isystem /root/sdk/ndk/21.4.7075529/sources/android/support/include -DNDEBUG -DDEBUG_ENABLED -D__ANDROID_API__=24 -DNO_STATVFS -DGLES_ENABLED -DANDROID_ENABLED -DUNIX_ENABLED -DVULKAN_ENABLED -DNO_FCNTL -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -Imodules/gdnative/include -Ithirdparty/libpng -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src/include -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src/layers -I/root/sdk/ndk/21.4.7075529/sources/third_party/vulkan/src/layers/generated -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/android -I. modules/gdnative/gdnative/signal.cpp
modules/gdnative/gdnative/callable.cpp:36:1: error: static_assert failed due to requirement 'sizeof(godot_callable) == sizeof(Callable)' "Callable size mismatch"
static_assert(sizeof(godot_callable) == sizeof(Callable), "Callable size mismatch");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [modules/gdnative/gdnative/callable.android.opt.debug.x86.o] Error 1
modules/gdnative/gdnative/signal.cpp:36:1: error: static_assert failed due to requirement 'sizeof(godot_signal) == sizeof(Signal)' "Signal size mismatch"
static_assert(sizeof(godot_signal) == sizeof(Signal), "Signal size mismatch");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [modules/gdnative/gdnative/signal.android.opt.debug.x86.o] Error 1
```

**Steps to reproduce:**
- Build for Android x86 with `scons p=android android_arch=x86 tools=no target=release_debug`

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #48645.

I dehardcoded the size similarly to what was done in #38779 for other types. `Signal` and `Callable` are both a `StringName` (pointer) and `uint64_t`.

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
> Seems to be correct, but failing on 32-bit ARM for some reason.

That's interesting, we're lucky to have CI on armv7 :)

Not sure why it's failing, this compiles fine:
```cpp
#include <stdint.h>

static_assert(sizeof(void *) == 4);
static_assert(sizeof(uint64_t) == 8);
static_assert(sizeof(void *) + sizeof(uint64_t) == 12);

int main() { return 0; }
```
with `ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi30-clang++ -std=c++17 main.cpp`

So the issue might be that Callable is actually not just `void *` + `uint64_t` on armv7.

**Comment by bruvzg** [comment]
> So the issue might be that Callable is actually not just void * + uint64_t on armv7.

`Signal` is just `void*` + `uint64` and is building fine, probably union part of the `Callable` have some strange alignment on armv7.
```c++
	StringName method;
	union {
		uint64_t object = 0;
		CallableCustom *custom;
	};
```

**Comment by hpvb** [comment]
We do need to make sure that the GDNative bindings know about the alignment so the compilers put the padding in the right places. I don't really know how the GDNative api binding generator works, or if they reuse these .h files directly. If they don't use our headers wholesale all the bindings will need to be updated.

**Comment by akien-mga** [comment]
The GDNative headers are the ones that language bindings build upon (via their copy in [godot-headers](https://github.com/godotengine/godot-headers/)), so they interact with those types using the padded `godot_signal` and `godot_callable`. So I guess that should be fine?

Those are new types in 4.0 so I don't think any bindings actually implemented them yet either (maybe @vnen for an upcoming godot-cpp update).

**Pull request merged**
