### PR TITLE
Overhaul GLES3: Add basis for 3D renderer, overhaul materials and textures

### PR DESCRIPTION
**Pull request by clayjohn**
This PR significantly cleans up the GLES3 code. 

I started out working to add the basics for the 3D renderer and got side tracked overhauling things that sorely needed to be overhauled, namely, materials, shaders, render_targets, and textures. 

~There are still a few things to be done before this PR is ready to merge~
~1. Textures need to actually make use of the filtering and repeat flags~
~2. I need to verify that shaderMaterials are actually working.~ 

In terms of 3D rendering. This PR makes it so that you can change the background colour of the 3D viewport and nothing else. 

This PR fixes some of the obvious problems we were having with subViewports in GLES3.

Overall this PR substantially improves the stability of the GLES3 backend. There is plenty more work to be done, but with this I can now move on to meshes and spatial shaders.

### CODE REVIEW

**Comment by clayjohn** [comment]
This PR is ready to review!

**Comment by lawnjelly** [comment]
Just starting to look through. One thing I noticed with a move to singletons I wanted to check:

* Do we still have control over the order of construction and destruction (i.e. scene and canvas might need to be destroyed before storage as they could contain resources stored in storage)
* Need to make sure we aren't allocating static storage space for the singletons when GLES3 isn't being used. I haven't looked in detail at the implementation to be able to see this.

**Comment by clayjohn** [comment]
> * Do we still have control over the order of construction and destruction (i.e. scene and canvas might need to be destroyed before storage as they could contain resources stored in storage)

Yes. In a previous PR I made construction and destruction explicit in the rasterizer class.

> * Need to make sure we aren't allocating static storage space for the singletons when GLES3 isn't being used. I haven't looked in detail at the implementation to be able to see this.

Yes. This already works. Only one backend is allocated. So we only allocate GLES3 stuff if it is the backend of choice.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
As discussed on chat, we're merging this even without a thorough review (@lawnjelly did a cursory review and liked the general state of things) as this is WIP and will only be really reviewable once more of the bits are in place.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
