### PR TITLE
Fix backspace when selection reaches left edge

### LINKED ISSUE #60866: Backspace doesn't delete selection if selected beyond TextEdit
### Godot version

5636903

### System information

Windows 10 x64

### Issue description

When you select text in TextEdit, particularly from right to left, with cursor finishing beyond the TextEdit, Backspace has no effect:
godot windows tools 64_Q0rDBbSbKf

### Steps to reproduce

1. Have TextEdit (Button text in the inspector or script editor)
2. Type any text
3. Select everything by dragging mouse over the text and waaay to the left
4. Press Backspace

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by pfertyk**
Fixes #60866.

### CODE REVIEW

**Comment by Paulb23** [comment]
Any chance you could add a test for this usecase?

**Comment by pfertyk** [comment]
Excellent idea @Paulb23 , I forgot about that! :D Test added, I've also fixed a typo in test variable and one translation ;)

**Comment by KoBeWi** [comment]
`.po` files shouldn't be edited directly. [Weblate](https://hosted.weblate.org/projects/godot-engine/) is used for that.

**Comment by pfertyk** [comment]
Quick question: is there an approval process for translations? I've changed `singal` to `signal` in Weblate and it seems that the change is now in effect, without any extra steps ...

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
