### PR TITLE
Remove `UPDATE_TRIGGER` mode from `ValueTrack::UpdateMode` & Match behaviors between `AnimationTree` and `AnimationPlayer`

### LINKED ISSUE #62491: AnimationPlayer's advance(0) updates property to first key found in track with UPDATE_DISCRETE, while advance(delta) doesn't
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Ubuntu 20.04.3 LTS

### Issue description

When an animation track has its first key at a non-zero time, and the mode is set to UPDATE_DISCRETE, `animationPlayer.advance(0)` will update the property to that key, regardless of the position of said key within the track, this is also the case when an animation is set to autoplay. 
This behavior is contradicted by the behavior AnimationPlayer has when `play()` is called, where the property isn't updated until its position in the animation is reached.

Simply put, for this animation:
image

the code
```
$AnimationPlayer.play("anim")
$AnimationPlayer.advance(0)
```
will instantly update the color to red
while the code
```
$AnimationPlayer.play("anim")
```
will only do so when the animation reaches 0.5 seconds.

### Steps to reproduce

1) Set up a scene like this
image

2) Each AnimationPlayer with these two animations
image
image

(notice the track's update mode is marked as discrete) 

3) Attach this script to the node named "advance_0"
```
extends Node2D

func _ready():
	$AnimationPlayer.play("anim")
	$AnimationPlayer.advance(0)
```

4) Attach this script to the node named "no_advance"
```
extends Node2D

func _ready():
	$AnimationPlayer.play("anim")

```

5) Run the scene
6) Notice one sprite is always red(the child of advance_0) while the other remains blue for the time it takes the animation to reach the key frame of the modulate (one second in this example)
Peek 2022-06-28 14-25

EDIT: this incongruence is also observed when advance(delta) is called, where delta is a non-zero value, meaning the following code, with $AnimationPlayer's playback set to manual, 
```
extends Node2D

func _ready():
	$AnimationPlayer.play("anim")
func _physics_process(delta):
	$AnimationPlayer.advance(delta)
```
won't instantly update the property to the first found key in the track, the way advance(0) will.

### Minimal reproduction project
[advance_0_bug.zip](https://github.com/godotengine/godot/files/9003483/advance_0_bug.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #62491. Supersedes #62714.
~~Prerequisite(contained) #69336.~~ Merged.

Remove `UPDATE_TRIGGER` from the `UpdateMode` of the animation's `ValueTrack` to match and make the `AnimationPlayer` and `AnimationTree` behavior consistent.

Currently, there is almost no difference between `UPDATE_DISCRETE` and `UPDATE_TRIGGER`. In `AnimationPlayer`, the difference is whether it is updated during manual seek or not. However, they perform exactly the same behavior in `AnimationTree`, so there is no distinction in that.

The following is a table of behaviors:

|                      | AnimationPlayer           | AnimationTree             |
| ----                 | ----                      | ----                      |
| Continuous + Nearest | Update Always             | Update Always             |
| Discrete             | Update when Seek/Crossing | Update when Seek/Crossing |
| Trigger              | Update when Crossing      | Update when Seek/Crossing |

Although the description says _"Only update the property on keyframes."_ for `UPDATE_DISCRETE` in class reference, but actually the value update timing during playback is exactly the same as in `UPDATE_TRIGGER`, and the value is never held. To begin with, holding the value is the role of `UPDATE_CONTINUOUS` + `INTERPOLATE_NEAREST`.

Looking at the `AnimationPlayer` code, `UPDATE_DISCRETE` is made to behave the same as `UPDATE_CONTINUOUS` only when seeking to update its value when it is seeked. However, this implementation is hackey. A more correct implementation would be to properly call `track_find_key()` instead of `value_track_interpolate()` when it is seeked. That is what is already done in `AnimationTree`.

This PR provides more consistency in the playback process between `AnimationPlayer` and `AnimationTree`, and simplifies the core code by eliminating unnecessary enums.

However, this breaks compatibility. Since the `.tres` files record the enum as an int value, removing `UPDATE_TRIGGER` will cause old `UPDATE_TRIGGER` mode tracks to be in `UPDATE_CAPTURE` mode, and any `UPDATE_CAPTURE` mode tracks containing animations may cause a crash. Perhaps some addition to the project converter will be necessary later.

### CODE REVIEW

**Review by fire — COMMENTED** [review]
I support the change.

**Comment by reduz** [comment]
Trigger was added to make it less annoying at the time to edit things like sub animations, audio and particles. I am not sure if anyone is using this, but given that sub-animations and audio now have dedicated tracks, there is less of a point in having this.

Eventually, one thing that was discussed is having particles tracks that would let you somehow seek into a particle system lifetime (for VFX) but this is a bit challenging to do. If done, then there would be 100% no point for the trigger mode I guess.

**Comment by reduz** [comment]
So bottom line is I am not sure anyone uses this. Probably no one. If thats the case it should be definitely removed.

**Comment by TokageItLab** [comment]
@reduz Rebased, and I think it is ready to merge.

In the first place, sub-animation by AnimationTrack does not support seek or reverse playback, and it provides the same behavior as Trigger (if I understand correctly how you were expecting to use the Trigger mode).

Even if sub-animation seek is supported in the future, that selection should be implemented as an option mode of AnimationTrack, not ValueTrack.

So there should be no cases that cannot be reproduced without Trigger mode at present. And now is probably the best time to remove this unused mode.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
