### PR TITLE
Add new QtCreator .cxxflags and .cflags files to .gitignore

### LINKED ISSUE #28408: Add new QtCreator .cxxflags and .cflags files to .gitignore
**Godot version:**
latest commit at time of this writing: 11bac340d

**OS/device including version:**
all

**Issue description:**
QtCreator 4.9 now adds .cxxflags and .cflags when importing Godot (in addition to the .config, .files, etc files that are already in the .gitignore so the Qt section of the .gitignore should now read (note: Qt is also mis-capitalized as QT in this section too)

```
# Qt project files
*.config
*.creator
*.creator.*
*.files
*.includes
*.cxxflags
*.cflags
```

**Steps to reproduce:**
1) clone Godot repository
2) floow the steps here: https://docs.godotengine.org/en/3.1/development/cpp/configuring_an_ide.html
3) notice git is finding .cxxflags and .cflags files and git GUIs like Github Desktop try to add them to the commit

### PR DESCRIPTION
**Pull request by LinuxUserGD**
fixes https://github.com/godotengine/godot/issues/28408

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Could also correctly capitalize "QT" as "Qt" while you're at it?

**Comment by LinuxUserGD** [comment]
Is it ok with two commits?

**Comment by YeldhamDev** [comment]
No, they need to be squashed:
https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by LinuxUserGD** [comment]
Done.

**Pull request merged**
