### PR TITLE
Add more documentations and fix AcceptDialog::add_cancel

### PR DESCRIPTION
**Pull request by Geequlim**
Fix the issue that AcceptDialog::add_cancel always create button with title "Cancel" .

### CODE REVIEW

**Comment by akien-mga** [comment]
There are some extraneous commits in this PR due to your branch and master having diverged, see my comment in #4476. Could you rebase to keep only 3f24f7d? It might be a bit tedious, but you'd have to run ``git rebase -i HEAD~5`` and drop the three "Fill in the blank" commits (which are already merged upstream but squashed into one commit, hence the issue here) by removing the corresponding lines. Then, if it worked, you should be able to ``git push --force`` to update this PR.

**Comment by Geequlim** [comment]
I'm sorry about that.
I will do as you said, thank you.

**Comment by akien-mga** [comment]
No problem, I'm currently writing some instructions in the docs on how to keep one's branch in sync with the upstream repo :)

**Comment by akien-mga** [comment]
I added some instructions here on how to always stay up-to-date before working on a new update: http://docs.godotengine.org/en/latest/contributing/updating_the_class_reference.html#keeping-your-local-clone-up-to-date

It doesn't fully apply to your current PR though as the commit is already made, and ``git reset --hard upstream/master`` would discard it. But it should be useful for the next time, if I got the commands right ;)

If fixing the current PR proves too hard, you can grab a patch of your changes (``git format-patch 	3f24f7d`` or download https://github.com/godotengine/godot/commit/3f24f7dffd70e78f7fb30df8cc86e477b78f422b.patch) and reapply it in a new branch with ``git am <name of the patch>``). Sorry for the bureaucracy :P

**Comment by Geequlim** [comment]
I will pull a new request.
Thank you!

**Pull request closed without merging**
