### PR TITLE
Added process input.

### PR DESCRIPTION
**Pull request by PeaceSells50**
(cherry picked from commit e4772227d468b6f1c8d62ff1f4b2b564086e891d)

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you explain the rationale? What motivates this addition?

**Comment by PeaceSells50** [comment]
process input currently exists for gdscript, but not for c++ without it.
input is used frequently in gdscript.

**Comment by reduz** [comment]
just do a function:

void MyClass::_input(InputEvent ev) {

}

and don't forget to

ObjectTypeDB::bind_method("_input",&MyClass::_input);

**Comment by akien-mga** [comment]
So IIUC we don't need this PR, users should use what @reduz described above in their C++ modules?

**Pull request closed without merging**
