### PR TITLE
Make operator= more C++ compliant

### PR DESCRIPTION
**Pull request by ntfshard**
[Copy assignment operator](https://en.cppreference.com/w/cpp/language/copy_assignment) should return reference to object.

### CODE REVIEW

**Comment by ntfshard** [comment]
`apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install gcc-9 g++-9 libasound2-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev mono-devel msbuild nuget" failed and exited with 100 during .
Your build has been stopped.`

**Comment by aaronfranke** [comment]
Ignore the Travis failure for now, that's not related to your PR (it's affecting everyone).

Should this behavior also be exposed to GDScript? Right now attempting an assign inside of another expression just says "Unexpected assign".

**Comment by Anutrix** [comment]
You missed https://github.com/godotengine/godot/blob/f7ca1c805ba2189627b49212ffbfba773f44acc5/editor/editor_audio_buses.h#L236.

**Comment by Anutrix** [comment]
Rebase and squash your commits.

**Comment by ntfshard** [comment]
> Rebase and squash your commits. I don't think 2 commits are needed for this.
> Refer to https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request and mastering-the-pr-workflow-the-rebase section after it.

Ok, now I got it) I'm just curious, why your PR is hang

**Comment by Anutrix** [comment]
> 
> 
> > Rebase and squash your commits. I don't think 2 commits are needed for this.
> > Refer to https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request and mastering-the-pr-workflow-the-rebase section after it.
> 
> Ok, now I got it) I'm just curious, why your PR is hang

If you are talking about #30678, then it's probably got lost between other PRs. There are a lot of PRs now and the core devs are busy. Nothing unusual. Just need to be patient. Also, when I first made that PR, the master branch was 3.2 and still concentrating on bugfixes. Now that it's 4.0, a lot of restrictions are gone.

**Comment by ntfshard** [comment]
Is everything OK or I should fix something in code or commit itself?

**Comment by Calinou** [comment]
@godotengine/core Is this change still needed with the core refactoring that occurred last year in the `master` branch?

**Comment by akien-mga** [comment]
Superseded by #55474.

**Comment by ntfshard** [comment]
Ok =)

**Pull request closed without merging**
