### PR TITLE
[3.2] Revert "Fix Directory" PRs

### LINKED ISSUE #40763: Directory must be open before using remove (3.2.3 rc1)
**Godot version:**
3.2.3 rc1

**OS/device including version:**
macOS 10.15.5

**Issue description:**
As of 3.2.3 rc1 you must open a directory before using `remove`.  Prior to 3.2.3 rc1 you didn't have to open up a directory to delete it, which makes sense.  If you are attempting to delete a directory, then you probably don't care if it doesn't exist.  If you did, you' d check for it first.  The new functionality might be the "right" way but I would argue it is a breaking change and shouldn't be introduced in a patch.

**Steps to reproduce:**
Assuming a directory `user://foo` exists and it is empty.
```
var d = Directory.new()
d.remove('user://foo') # this causes error, the directory is not removed.  this works in 3.2.2
```

**Minimal reproduction project:**
See code. Should be enough.

### PR DESCRIPTION
**Pull request by aaronfranke**
Reverts #40528, #40243, and #40151 in the 3.2 branch, @nathanfranke asked me to do this.

@akien-mga IMO, don't bother re-adding these commits for 3.2.4. It seems that the plan is to redesign these APIs for Godot 4.0, so any work put towards the current API would be solely for 3.2. I don't really think it's worth the effort of putting additional layers of duct tape on the problem if there's a high chance of compatibility breakage and the work would only exist for 3.2. @nathanfranke disagrees with me on this, he wants these changes in 3.2.

Closes #40763.

### CODE REVIEW

**Comment by nathanfranke** [comment]
Fixes #40763

**Comment by akien-mga** [comment]
> @akien-mga IMO, don't bother re-adding these commits for 3.2.4. It seems that the plan is to redesign these APIs for Godot 4.0, so any work put towards the current API would be solely for 3.2. I don't really think it's worth the effort of putting additional layers of duct tape on the problem if there's a high chance of compatibility breakage and the work would only exist for 3.2. @nathanfranke disagrees with me on this, he wants these changes in 3.2.

Let's take the time to re-evaluate this for after 3.2.3. I do think that #40146 showed a fairly bad issue which needs to be addressed properly, but indeed we might need to take more time to understand how the Directory API is being used currently and what can be tightened to protect users without breaking compatibility (or if we have to break compat, then doing it while being quite confident about the change being a net improvement).

I started working on a test project for the whole Directory and File API almost a year ago, I should revive it...

**Comment by akien-mga** [comment]
Thanks!

**Comment by Xrayez** [comment]
> I started working on a test project for the whole Directory and File API almost a year ago, I should revive it...

Tests can be written as unit tests in Godot now to be tested in `master` at least before any major rewrite is done for those fixes to be backported to `3.2`, else the unit testing framework can be backported to `3.2` as well as proposed in godotengine/godot-proposals#1533.

@nathanfranke or anybody else could then write some tests for `Directory` and `File` APIs first to verify the current functionality (even if it's deemed as erroneous currently, talking about stable branches where these issues could be already worked around in existing projects), then do the desired fixes more safely. 🙂

Documentation for unit testing in Godot is in a mergable state now: godotengine/godot-docs#4017, you can read the diff though.

**Comment by nathanfranke** [comment]
> @nathanfranke disagrees with me on this, he wants these changes in 3.2.

Nah, let's not bother with this for 3.2.

**Pull request merged**
