### PR TITLE
New shortcuts for the editor menu items

### PR DESCRIPTION
**Pull request by ZahFox**
This pull request is related to issue #25634 . I spent some time this afternoon figuring out how to add new shortcuts for the editor's menu items. So far I've only added two new shortcuts, but I wanted to submit a pull request as a guide to other people who might be interested in contributing to this issue. Within the next couple of days I could add the rest of the menu items.

As a side note, this is my first pull request for this project and I wasn't sure if I should submit it without completing all of the requirements. I saw that this issue has been open for 16 days and figured my changes could potentially help someone else.

### CODE REVIEW

**Comment by groud** [comment]
You apparently did a bad manipulation with git, as your PR contains older commits. 
You should rebase your PR on the master branch.

**Comment by ZahFox** [comment]
@groud How's it looking now?

**Comment by groud** [comment]
Perfect. :)
I don't know if all of these items are necessary as shortcut (like the like to the Q&A do not seem needed) but the PR is clean now. Thanks!

**Comment by ZahFox** [comment]
The issue said "everything in the editor" so I started with all of the menu items. I figured items such as Q&A would have a really low chance of being used but I was going for completeness. I can remove them if you think it'll make the shortcuts menu too noisy.

**Comment by akien-mga** [comment]
Did you mean to close it?

**Comment by smedelyan** [comment]
@ZahFox why did you close PR?

**Comment by willmccullough** [comment]
@smedelyan I did not mean to close this sorry about that.

**Comment by ZahFox** [comment]
Didn't mean to close this I'll submit a new one.

**Pull request closed without merging**
