### PR TITLE
Autosave modified collections in resource properties

### LINKED ISSUE #33758: Changing collision in external tileset resource isn't visible until resource is saved
**Godot version:**
3.2-beta

**OS/device including version:**
Debian bullseye/sid

**Issue description:**
Could be related to #27833. Changing collisions in a linked tileset doesn't mark it as "dirty" apparently, it's not saved on scene save and the changes are not visible in the game until you save the resource manually. Even worse, after making modifications you can close the editor and it won't warn you about unsaved changes so it's easy to lose your work. The collisions are updated correctly if the resource is embedded into the scene though.

**Steps to reproduce:**
1. Enable "Visible Collision Shapes" in editor.
1. Run the scene and observer the collision shape.
1. Edit the collision in the tileset to become a square.
1. Run the scene again and observe no changes.
1. Open the tileset and save the resource.
1. Upon running the scene you should see the changes applied.
1. Try to edit the collision shape, save the scene and close the editor.
1. Expect a warning about unsaved changes in resource but there's none and after reopening your project the changes to the collision will be lost.
1. You can also trigger the resource autosave by adding more tiles, changing occlusion or navigation shapes.
1. Remove the resource path in inspector thus making it embedded.
1. Try to change the collisions, now they are applied immediately.

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/3868210/bug.zip)

### PR DESCRIPTION
**Pull request by rkfg**
All other shapes except collision are automatically saved with the scene because they're stored as objects. There could be multiple collision shapes so they're stored in an array and this is not handled properly. Fixes #33758.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Doesn't it "conflict" with the `shapes` property defined a few lines down?

**Comment by rkfg** [comment]
I suppose that property is for storing multiple collision shapes for the same tile? I created two collision polygons and they're saved and updated just fine.

**Comment by rkfg** [comment]
Interesting. If I have more than one collision polygon then the second one isn't saved on change. Both are saved when I change the first one though. Will dig deeper then!

**Comment by rkfg** [comment]
Added some thoughts to #33758 and the `shape` property is probably deprecated by now.

**Comment by rkfg** [comment]
Okay, take two. I mostly copied (and removed unrelated bits) the code from the existing function that recursively iterates objects, arrays and dictionaries. Now both collision shapes I added are saved and updated if any of them changed.

**Comment by aaronfranke** [comment]
@rkfg Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by rkfg** [comment]
I'll try to check and fix it this week!

**Comment by rkfg** [comment]
I had a crash using the master build with the following stack trace:
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3b800) [0x7fc6c6c61800] (??:0)
[2] HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::getptr(Variant const&) const (/home/rkfg/soft/svn-soft/
godot/./core/hash_map.h:313)                                                                                                                                                                                        [3] HashMap<Variant, List<Pair<Variant const*, Variant>, DefaultAllocator>::Element*, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::has(Variant const&) const (/home/rkfg/soft/svn-soft/god
ot/./core/hash_map.h:272)                                                                                 
[4] OrderedHashMap<Variant, Variant, VariantHasher, VariantComparator, (unsigned char)3, (unsigned char)8>::has(Variant const&) const (/home/rkfg/soft/svn-soft/godot/./core/ordered_hash_map.h:235)
[5] Dictionary::has(Variant const&) const (/home/rkfg/soft/svn-soft/godot/core/dictionary.cpp:130)
[6] Object::has_meta(String const&) const (/home/rkfg/soft/svn-soft/godot/core/object.cpp:996)
[7] EditorNode::get_object_icon(Object const*, String const&) const (/home/rkfg/soft/svn-soft/godot/editor/editor_node.cpp:3749 (discriminator 1))
[8] SceneTreeEditor::_add_nodes(Node*, TreeItem*) (/home/rkfg/soft/svn-soft/godot/editor/scene_tree_editor.cpp:194)
[9] SceneTreeEditor::_update_tree() (/home/rkfg/soft/svn-soft/godot/editor/scene_tree_editor.cpp:529)
[10] SceneTreeEditor::set_selected(Node*, bool) (/home/rkfg/soft/svn-soft/godot/editor/scene_tree_editor.cpp:695)
[11] SceneTreeDock::set_selected(Node*, bool) (/home/rkfg/soft/svn-soft/godot/editor/scene_tree_dock.cpp:2175)
[12] EditorNode::push_item(Object*, String const&, bool) (/home/rkfg/soft/svn-soft/godot/editor/editor_node.cpp:1786)
[13] SceneTreeDock::_node_selected() (/home/rkfg/soft/svn-soft/godot/editor/scene_tree_dock.cpp:1221 (discriminator 2))
[14] void call_with_variant_args_helper<SceneTreeDock>(SceneTreeDock*, void (SceneTreeDock::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/rkfg/soft/svn-soft/godot/./core/callable_method_poi
nter.h:136 (discriminator 4))                                                                             
[15] void call_with_variant_args<SceneTreeDock>(SceneTreeDock*, void (SceneTreeDock::*)(), Variant const**, int, Callable::CallError&) (/home/rkfg/soft/svn-soft/godot/./core/callable_method_pointer.h:158)        
[16] CallableCustomMethodPointer<SceneTreeDock>::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/rkfg/soft/svn-soft/godot/./core/callable_method_pointer.h:184)                             
[17] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/rkfg/soft/svn-soft/godot/core/callable.cpp:54)
[18] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (/home/rkfg/soft/svn-soft/godot/core/message_queue.cpp:259)
[19] MessageQueue::flush() (/home/rkfg/soft/svn-soft/godot/core/message_queue.cpp:306)
[20] SceneTree::iteration(float) (/home/rkfg/soft/svn-soft/godot/scene/main/scene_tree.cpp:423 (discriminator 2))
[21] Main::iteration() (/home/rkfg/soft/svn-soft/godot/main/main.cpp:2181)
[22] OS_LinuxBSD::run() (/home/rkfg/soft/svn-soft/godot/platform/linuxbsd/os_linuxbsd.cpp:238)
[23] /home/rkfg/soft/svn-soft/godot/bin/godot.linuxbsd.tools.64(main+0xfa) [0x19b084c] (/home/rkfg/soft/svn-soft/godot/platform/linuxbsd/godot_linuxbsd.cpp:57)
[24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fc6c6c4ce0b] (??:0)
[25] /home/rkfg/soft/svn-soft/godot/bin/godot.linuxbsd.tools.64(_start+0x2a) [0x19b069a] (??:?)
```

When I was fiddling with it, the collision shapes were not saved at all, neither explicitly nor implicitly. I couldn't even delete the tileset or create a new one, nothing happened when I tried and in the end Godot crashed. Upon the next launch it seems to save all shapes automatically without any additional actions. So I'm going to close this pull request and consider it fixed somewhere else.

**Pull request closed without merging**
