### PR TITLE
Fix index out of size error on Image

### LINKED ISSUE #18177: 2DEditor: error spam when creating sprite with compressed texture
**Godot/OS version:**

1d15c5d Antergos x86_64

**Issue description:**

`Can't get_pixel() on compressed image, sorry.` prints when mouse over sprite with compressed texture.

```
Godot Engine v3.1.dev.custom_build (c) 2007-2018 Juan Linietsky, Ariel Manzur & Godot Contributors.
Create Node
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
 Can't get_pixel() on compressed image, sorry.
```

**Steps to reproduce:**
1. reimport icon.png as compress_mode: vram
2. drag it on the 2D editor viewport (to create sprite node)
3. move cursor over image, prints error

### LINKED ISSUE #18229: image error keeps occurring when moving mouse around sprite
**Godot version:**

3.1.dev 1d15c5d72

**OS/device including version:**

**Issue description:**

following error keeps occurring when moving mouse around sprite.
sprite uses region_rect.
```
core/image.cpp:1892 - Index p_x=150 out of size (width=128)
```

**Steps to reproduce:**
1. add sprite
2. assgin texture to it
3. turn on Region > Enabled on inspector
4. define rect size larger than texture at Region > Rect
5. move mouse around sprite

image_error

**Minimal reproduction project:**

[Image error.zip](https://github.com/godotengine/godot/files/1914919/Image.error.zip)

### PR DESCRIPTION
**Pull request by volzhs**
Fix #18229 and fix #18177

This PR covers all repeat, mirrored repeat, and no repeat cases.

This error occurs too with 3.0.2 stable official when clicking it.

### CODE REVIEW

**Comment by groud** [comment]
While you're here, maybe you could fix #18177 too ? ^^

**Comment by volzhs** [comment]
@groud 
I saw `Image::get_pixel(int p_x, int p_y)` can not get color from compressed texture.
I think I can't do anything about this method.
is it enough to just check bound for the compressed texture instead exact picking introduced with #15093?

**Comment by groud** [comment]
It just needs a test whether the image is compressed or not (with something like `image->is_compressed()`).
If it's compressed, this function should return something like `dst_rect.has_point(p_point)`

**Comment by volzhs** [comment]
@groud it's fixed now. :)

**Review by groud — APPROVED** [review]

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Pull request merged**
