### PR TITLE
Don't allow built-in scripts to use class_name

### LINKED ISSUE #25579: class_name won't work on built-in scripts
**Godot version:**
Godot 3.1 build 8698876

**OS/device including version:**
Arch Linux

**Issue description:**
When a `Script.gd` has a `class_name`, it will be reckognized by the engine and can be used later. However, if a script built-in on a Scene has a `class_name`, other scripts won't reckognize it.

**Steps to reproduce:**
1. Create a new scene.
2. Attach a script to it, and mark the option "Built-in" to be "On"
3. On the content of the script, name it with `class_name`. Example:

```gdscript
extends Node
class_name Item

func _ready():
    pass
```

4. Create a new script.
5. Extends it with the newly created built-in script.

```gdscript
extends Item
```

6. An error will be thrown: `error(1, 20): Unknown class: 'Item'`

**Minimal reproduction project:**
[Built-In class_name.zip](https://github.com/godotengine/godot/files/2825489/Built-In.class_name.zip)

In this project, there's both a Built-in (`class_name BuiltinItem`) and a not built-in (`class_name NotBuiltinItem`) scripts. Open the `Script.gd` file, you will see the error described above. If you change the extension to `NotBuiltinItem`, the error will disappear.

### PR DESCRIPTION
**Pull request by vnen**
Closes #25579

### CODE REVIEW

**Comment by akien-mga** [comment]
That second commit is not relevant if you rebase on current master, I already committed those changes.

Sounds like you're all running Arch or similar and got clang-format 8.0 landing at once @JFonS @bojidar-bg and @vnen? :)

**Comment by JFonS** [comment]
@akien-mga guilty... :hand:

**Comment by vnen** [comment]
Rebased. I guess I'm too bleeding edge with Arch.

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.

**Comment by akien-mga** [comment]
Reverted cherry-pick for now, there's a regression from this PR in #28002 which needs to be solved first.

To consider again for 3.1.2.

**Comment by akien-mga** [comment]
The regression #28002 was fixed by #28099, which should thus be cherry-picked together with this PR.
For now, opting out of cherry-picking this to stay on the safe side.

**Pull request merged**
