### PR TITLE
fix string capitalization & to_lower

### PR DESCRIPTION
**Pull request by AndreevAndrei**
I've got bug with russian symbols like _'Ё', 'Ф',_ etc that function didn't return correct result (_'ё', 'ф'_, etc.)
I found that **reverse_caps_table** was not sorted right (for example look at lines 968 - 969) and fix it. By the way I set the similar format as in table **caps_table** (0xFFFF - 4 hex symbols in uppercase)

### CODE REVIEW

**Comment by AndreevAndrei** [comment]
In godot I use:
```
var text = "ГЕОМЕТРИЯ"
text = text.to_lower(text)
```
And now text is "геометриЯ" and not "геометрия"
The same problem was found with using **.capitalize()**

**Comment by allkhor** [comment]
Issue  #26744. Also another PR is opened #26760.

**Comment by AndreevAndrei** [comment]
Oh, yea...
By the way in my version **line 787** `// { 0x0049, 0x0131 }, // dotless I`, is in right position at **line 716** - after the `{ 0x0049, 0x0069 }`

**Comment by reduz** [comment]
@akien-mga seems fine to me, no idea which one is best to merge of both. Should we merge this one?

**Comment by akien-mga** [comment]
Superseded by #26760.

**Pull request closed without merging**
