### PR TITLE
Two methods w/ no return value; breaks build.

### PR DESCRIPTION
**Pull request by ghost**
There were two methods in the file `./core/io/stream_peer.cpp` that did not return a value causing my Scons build to terminate. Not sure if it's something unique to my setup but I don't think adding return values would hurt?
pic

### CODE REVIEW

**Comment by vnen** [comment]
There's already #6239 fixing part of this.

**Comment by akien-mga** [comment]
Also note that you had added the file `core/io/.vscode/.BROWSE.VC.DB-wal` to git, which should only stay on your system, so the PR wouldn't have been accepted. Make sure to check `git status` before committing.

**Comment by volzhs** [comment]
@akien-mga I didn't see that file added before. I guess that file was added after close this PR by accidently.

**Comment by akien-mga** [comment]
@volzhs It shows up in the initial email notification:

> Commit Summary
>
>    Two methods w/ no return value; breaks build.
>
> File Changes
>
>    A core/io/.vscode/.BROWSE.VC.DB-wal (0)
>    M core/io/stream_peer.cpp (4)
>
> Patch Links:
>
>    https://github.com/godotengine/godot/pull/6288.patch
>    https://github.com/godotengine/godot/pull/6288.diff

**Comment by volzhs** [comment]
@akien-mga maybe my memory had broken. :)

**Comment by TristanWLB** [comment]
Yup sorry about that, used VSCode to edit that and I guess it created that directory after I saved my changes.

**Pull request closed without merging**
