### PR TITLE
Csharp: Seperate `Mathf` into `Maths` and `Mathd` and use `Mathf` as name for `real_t`

### PR DESCRIPTION
**Pull request by antonWetzel**
Somewhat related to https://github.com/godotengine/godot-proposals/issues/5403

### Overview

- Split the current `Mathf` class into seperate classes for `single` and `double`.
- if `REAL_T_IS_DOUBLE`is double `Mathf` is used as name for `Mathd` else for `Maths`
- Function for `int` are included in `Mathf`

### Notes

- Generic Math (preview feature) would be nice to reduce code (no clue if and when godot wants to update csharp version)
- I used `Mathf` as name to avoid compability break, but I would prefer `MathGD` or something similar
- A global alias in a namespace is not possible

### To-do

- code is alot of ctrl-c + ctrl-v and replace all `real_t` $\to$ `double` / `single`
  - clean up unnecessary casts
  - check if everything is correct

### CODE REVIEW

**Comment by aaronfranke** [comment]
Why? If you need explicitly single or double precision math, you can use C#'s own `Math` and `MathF` classes.

**Comment by antonWetzel** [comment]
> `MathF` classes.

`System.Math`and `System.MathF` do not have `RadToDeg`, `DegToRad`, `MoveToward, `MoveTowardAngle`, `Lerp`, ...

**Comment by aaronfranke** [comment]
> in `Mathf` if the `F` in `System.MathF` means `float`

Due to double-precision support in Godot, `Mathf` can also be seen as a retronym for "Math functions".

**Comment by dpalais** [comment]
Why not keep the double overloads in Mathf? double type is just a double precision float, that is it too is a floating-point value.

**Comment by antonWetzel** [comment]
> Why not keep the double overloads in Mathf? double type is just a double precision float, that is it too is a floating-point value.

Overloads can't be used for constants (`PiF` or `PiD` don't look good) and only a double version must be casted and only a float version loses precision.

**Pull request closed without merging**
