### PR TITLE
Rename `OS` to `Platform`

### PR DESCRIPTION
**Pull request by madmiraal**
As originally identified by @leonkrause [here](https://github.com/godotengine/godot/issues/16863#issuecomment-403253127), not every platform is an OS, but every OS is a platform, and it's how we refer to each of the platforms that inherit from this class too. Therefore, it makes sense to rename `OS` to `Platform`.  To make everything consistent, this PR includes renaming all the inheriting classes too.

Part of #16863.

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge of #41091, #47370, #47701 and #47936.

**Comment by neikeq** [comment]
I don't like this change because `Platform` takes longer to type and takes more horizontal space. IMO consistency is not worth it in this case.
If we look at the members of the `OS` class, many if not most of them don't belong to an OS or Platform class, but rather other concepts like thread, environment, process, system, etc. This class provides too many methods for vastly unrelated things and it would be better for it to be split. That may be hard though without support for static methods (e.g.: `delay_msec/usec` should be static methods of `Thread`).

**Comment by Xrayez** [comment]
> This class provides too many methods for vastly unrelated things and it would be better for it to be split. That may be hard though without support for static methods (e.g.: `delay_msec/usec` should be static methods of `Thread`).

That what I thought as well, there needs to be better separation. There are a number of proposals which also suggest static methods support, like godotengine/godot-proposals#1101.

**Comment by Chaosus** [comment]
> I don't like this change because Platform takes longer to type

I feel similarly, Maybe `PM` or `PF` sounds better?

**Comment by Xrayez** [comment]
> > I don't like this change because Platform takes longer to type
> 
> I feel similarly, Maybe `PM` or `PF` sounds better?

I don't think the verbosity is the major concern for rename. `OS` is recognized by nearly everyone who does programming, shortening the name to `PM` (project manager?) or `PF` will likely be confusing to new contributors.

**Comment by Chaosus** [comment]
> > > I don't like this change because Platform takes longer to type
> > 
> > 
> > I feel similarly, Maybe `PM` or `PF` sounds better?
> 
> I don't think the verbosity is the major concern for rename. `OS` is recognized by nearly everyone who does programming, while shortening the name to `PM` (project manager?) or `PF` will likely be confusing to new contributors.

And what do you think about preserving both `OS` and `Platform` as a reference to the same singleton?

**Comment by aaronfranke** [comment]
On one hand, it makes sense because not every platform is an OS (ex: web), so "Platform" is more technically correct. On the other hand, "OS" is shorter, very recognizable, and it's also unambiguous ("Platform" can also refer to things like Steam vs Itch vs Epic).

**Comment by aaronfranke** [comment]
> @Chaosus: And what do you think about preserving both `OS` and `Platform` as a reference to the same singleton?

To quote reduz on the topic of having two APIs for the same thing:

**Comment by madmiraal** [comment]
Rebased following merge of #47343, #47398, #47448, #47917, #47974, #47990, #48050, #48098, #48185 and #48292.

**Comment by madmiraal** [comment]
Rebased following merge of #47772.

**Comment by nathanfranke** [comment]
> Rebased following merge of #47343, #47398, #47448, #47917, #47974, #47990, #48050, #48098, #48185 and #48292.

You can just re-base it, there's no need to ping every single PR that modifies something `OS`-related.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting today, and the consensus was that this rename doesn't seem like a good idea anymore.

Leon's proposal made sense for the 3.x codebase as the `OS` class did pack a lot of API which is platform-specific more than OS-specific (and the code folders are indeed called `platforms/<name>/`). But since 4.0, the platform-specific APIs are split in two classes, `OS` and `DisplayServer`, with a much cleaner separation of concerns. "Platform" is the union of `OS` and `DisplayServer`, and the "new" `OS` is indeed mostly OS-specific APIs, so the names make sense. Changing `OS` to `Platform` would actually make things more ambiguous now.

**Pull request closed without merging**
