### PR TITLE
General use Variant type icons, plus other icon updates.

### PR DESCRIPTION
**Pull request by djrm**
[ciskip]

### CODE REVIEW

**Comment by akien-mga** [comment]
> [ciskip]

Heh, you thought I'd let this go through even without clang-format checks? ;)
https://github.com/godotengine/godot/pull/14781/commits/45c19c174ae92e0d884e4806a8edb8b41e96de08#diff-bc4de62b8d91eb9cc820c6cce706d8b3R42

**Comment by djrm** [comment]
@akien-mga is that wrongly formated?, i have the hooks, but i guess something happened, now the suggested style is 2 spaces for me.

**Comment by akien-mga** [comment]
You need to use `clang-format` 5.0 from now on, we bumped version a while ago. If you have an older version, it will likely fail to parse the current .clang-format file and default to the LLVM style.

**Comment by djrm** [comment]
@akien-mga sh!t i dont have llvm 5 in my system, why the change?

**Comment by akien-mga** [comment]
Because many users have 5.0 now and it's not compatible, so it was a mess over the last 6 months. And it's usually easier to get people to upgrade than to downgrade (and with 5.0 we get better support for ObjC and various issues of 3.9 fixed).

If your distro doesn't provide it, changes are you can install 5.0 from upstream directly, see #14332.

**Comment by djrm** [comment]
@akien-mga ok fixed.

**Pull request merged**
