### PR TITLE
Allow using built-in names for variables, push warnings instead

### PR DESCRIPTION
**Pull request by Chaosus**
It seems [undesired](https://github.com/godotengine/godot/pull/54676#issuecomment-967974389) if using an error for that, I've added a new warning instead as suggested - https://github.com/godotengine/godot/pull/54676#issuecomment-968076755

### CODE REVIEW

**Comment by aaronfranke** [comment]
I think treating these as errors as in #54676 is better. Even if it's allowed, it can be very confusing.

**Comment by Chaosus** [comment]
Maybe we should leave it for the PR review.

**Review by akien-mga — APPROVED** [review]
Approved in PR reviewing meeting.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
