### PR TITLE
Set procedural sky material to default environment

### PR DESCRIPTION
**Pull request by Chaosus**
I guess the completely dark sky in 3d mode for new projects does not seem good... + it seems like a regression (cuz 3.2 sky have material by default)

### CODE REVIEW

**Comment by akien-mga** [comment]
`3.2` had lots of issues on low end due to ProceduralSky being too heavy for some drivers (leading to crashes). So we should be careful with what we use as default environment in `4.0` to avoid having the same issue.

**Comment by Calinou** [comment]
The question is, should we use ProceduralSky or PhysicalSky by default in 4.0? PhysicalSky looks better and its color changes automatically depending on the sun angle.

**Comment by Chaosus** [comment]
> The question is, should we use ProceduralSky or PhysicalSky by default in 4.0?

PhysicalSky requires at least one directional light to produce a sun, otherwise, it also completely dark.

**Comment by clayjohn** [comment]
Reduz and I discussed having a default sky. In the end we decided not to, instead we will have that editor environment that we discussed at the last proposal meeting. 

There should be a button like the "perspective button" for environment. It will allow users to change the settings of a default editor-only environment and directional sun. It will also have two buttons "add light to scene" which disables the directional light and copies the directionalLight as a node to the scene and "add environment" which disables the default environment and adds it in a world environment node. 

This allows us to have lot scenes and sub scenes, but also avoids the confusion of having environments disappear.

**Comment by Chaosus** [comment]
@clayjohn Thanks for the notice! Closed.

**Pull request closed without merging**
