### PR TITLE
Add surface indices to TriangleMesh

### PR DESCRIPTION
**Pull request by reduz**
Helps unblock #56597

### CODE REVIEW

**Comment by fire** [comment]
I'll try to fit checking this with the material pr into my schedule.

**Review by SaracenOne — APPROVED** [review]
Nice, this looks good! Just the kind of thing we needed

**Review by akien-mga — APPROVED** [review]
Code looks good.

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
Indeed it seems like I forgot this, but I trust @SaracenOne and @fire can amend this when they fix the material PR.

**Comment by fire** [comment]
Fixing issue from https://github.com/godotengine/godot/pull/62321#issuecomment-1164085200

**Pull request merged**
