### PR TITLE
PhysicsServer3D docs: sync phrasing of get_process_info with 2D docs

### PR DESCRIPTION
**Pull request by rburing**

### CODE REVIEW

**Comment by aaronfranke** [comment]
Bullet was removed from the engine recently, so I'm not sure that this information is relevant anymore. The only physics server in the engine (Godot Physics) implements it, and what happens in third-party addons doesn't need to be documented.

**Comment by Calinou** [comment]
This PR should likely be reopened on `3.x` instead.

**Comment by aaronfranke** [comment]
This PR can be kept if it's modified to remove the last sentence.

**Comment by rburing** [comment]
Thanks, updated. The `3.x` version with the comment about Godot Physics is now https://github.com/godotengine/godot/pull/59292.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
