### PR TITLE
Fix "missing dependency resolver" in Windows

### LINKED ISSUE #3794: "Fix Dependencies" dialog opens, but does not work for non-binary scenes types
**Operating system or device:**
Tested on FreeBSD & Win7

**Issue description** (what happened, and what was expected):
The dialog to fix missing dependencies when opening a scene opens for all scene types, but actually setting a new file is only possible for `.scn` files.

Also, there's a `Fix Broken` button at the top of of the `Fix Dependencies` dialog, does this have any use or can it be removed?

**Steps to reproduce:**
1. Create a new project
2. Add a Sprite root node and set `icon.png` as texture
3. Save scene as .tscn 
4. Close scene
5. Rename `icon.png` to e.g. `icon2.png`
6. Reopen scene
7. In the missing dependency dialog, click `Fix Dependencies`
8. try to fix external resource `icon.png` by reassigning it to e.g. `icon2.png`
9. Observe that reassigning does not work (assigned file does not change)
10. Repeat with .scn -> reassigning works

### PR DESCRIPTION
**Pull request by leonkrause**
Fixes #3794

### CODE REVIEW

**Comment by reduz** [comment]
As far as I remember the file is closed when the ResoucreInteractiveLoader
is deleted..

**Comment by reduz** [comment]
ResourceInteractiveLoaderText::~ResourceInteractiveLoaderText() {

    memdelete(f);
}

so something strange is going on. I assume you are on Windows, so you can't
change a file that is opened

**Comment by eska014** [comment]
I think only binary scenes open an InteractiveLoader to rename dependencies, tscn and xml just use FileAccess and modify the raw text

**Comment by eska014** [comment]
The InteractiveLoader that manages `f` is never deleted (within the function), since it's the loader that the function is called on.

In the binary loader, two loaders are created for the broken file and the fixed file, both of which go out of scope before file renaming happens.
But non-binary loaders don't create new loaders at all, they just open per `FileAccess` and modify the raw text.

`FileAccess* f` is a member of the loader that `rename_dependencies` is being called on, so it's never deleted before the function is done. It needs to be closed, or Windows will consider the file to be read-only

**Comment by akien-mga** [comment]
I would merge this before 2.0 if it's fine with you @reduz.

**Comment by reduz** [comment]
ah I misunderstood your fix, sorry, this is perfect

**Pull request merged**
