### PR TITLE
Verify animation is open when changing FPS mode

### PR DESCRIPTION
**Pull request by ghost**
This avoids a crash when no animation is open.

### CODE REVIEW

**Comment by homer666** [comment]
I think I screwed something up with the commit, gonna try to fix it...

**Comment by homer666** [comment]
Actually, I think Git is just confused. Not sure what can be done here.

**Comment by homer666** [comment]
Superseded by 0d41f8f.

**Comment by reduz** [comment]
Did a proper fix (disable controls instead of ignoring input), since i was recently working on this code. Still thanks a lot for finding the issue and contributing a solution.

**Pull request closed without merging**
