### PR TITLE
Only cleanup meta data if GDNative library is reloadable

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Only cleanup meta data if GDNative library is reloadable and we're about to unload it

This is a small change on #46844 and #47623, we only unload the library if it is marked as reloadable (which is the default) and we should thus only do the meta data cleanup if it is marked as reloadable. Else we'll end up with a half initialised library in memory.

Now there is far more to this, the original code for unloading libraries was build with quiting Godot in mind, later on adding logic that would unload all libraries when the editor looses focus, which then was enhanced with the is_reloadable flag to prevent unloading libraries that do more then just GDNativeScript (like VR plugins).

The code we're dealing with now was added later to allow for unloading a single library when no more active scripts were around. I'm not 100% of the use case but it has become default behavior which does result in the weird situation that when you're changing levels, you introduce a whole bunch of potential overhead in unloading and then reloading GDNative libraries but I remember the use case for which it was introduced making sense. 
@akien-mga do you remember the PR that started this whole mess, it would be good to tag that into this PR.

There is a good argument for in the future changing the reloadable setting to an enum: "Do not reload,Reload in editor only,Reload on no active scripts" so we have control over whether we want to use this feature or not.

For now this fix should at least resolve the issue introduced for libraries that shouldn't be unloaded. There is another use case which is when libraries are marked as singletons but generally speaking those libraries will also be marked as not reloadable.
This is a good place to look for the original unload/reload code on editor focus loss keeping in mind this code was written with unloading everything in mind:
https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/nativescript.cpp#L1876
Also note that `_unload_stuff` will yet again check reloadable before it removes anything if appropriate. 

Talking to @vnen about this earlier today we both feel this is in need of a serious cleanup. Because the original code was written with unloading everything in mind we now have various paths to the same logic that has become very unclear and hard to maintain. We believe the library code should be rewritten to have a clear `unload` function to unload a library that unloads a given library and cleans it up properly. That can then be called from all three places where we unload libraries, either for a single library or for all libraries.

Tagging @Bromeon, @geekrelief , @toasteater  and @sash-rc as they have worked on the previous PRs, please evaluate and make sure we don't introduce further issues.

### CODE REVIEW

**Comment by akien-mga** [comment]
@BastiaanOlij That was the original issue: #44617.

After this PR, do we still cleanup metadata for the non-reloadable GDNative libraries? Or are they leaked?

**Comment by BastiaanOlij** [comment]
> 
> 
> @BastiaanOlij That was the original PR: #44617 (and corresponding issue: #42449).
> 
> After this PR, do we still cleanup metadata for the non-reloadable GDNative libraries? Or are they leaked?

As I understand it no. This meta data is constructed when the library is loaded, and should be cleaned up when unloaded. Because we are not unloading the library we should keep the meta data. Freeing the meta data at this point means that we end up with a broken library because it no longer has access to the meta data it needs when constructing new objects.

At least that is how I read the logic and Karoffels version of the code when libraries are unloaded from the editor when focus is lost. Singeton libraries and non-reloadable libraries should be left alone.

**Comment by akien-mga** [comment]
>  This meta data is constructed when the library is loaded, and should be cleaned up when unloaded. 

But isn't this the cleanup code? Won't this (and previous changes) mean that non-reloadable GDNative libraries are never unloaded? Or is there another cleanup method that actually runs in the engine quit/cleanup code?

**Review by akien-mga — APPROVED** [review]
Regardless of the broader discussion about this mess of unloading, this change seems fine :+1:

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Comment by BastiaanOlij** [comment]
> 
> 
> > This meta data is constructed when the library is loaded, and should be cleaned up when unloaded.
> 
> But isn't this the cleanup code? Won't this (and previous changes) mean that non-reloadable GDNative libraries are never unloaded? Or is there another cleanup method that actually runs in the engine quit/cleanup code?

Correct, there are now three places in the code where we cleanup. 
1) The code here, where we clean up just the one library
2) The code when the editor looses focus and all reloadable libraries get unloaded
3) When Godot exits through calling `NativeScriptLanguage::finish()`.

Both 2 and 3 call `NativeScriptLanguage::_unload_stuff` which unloads everything (skipping non-reloadable libraries if a parameter is set)

**Pull request merged**
