### PR TITLE
Implemented terrain raycast acceleration

### LINKED ISSUE #24390: Huge slowdown when raycasting large HeightmapCollider
Godot 3.0.6
Godot 3.1 alpha3

This is a very weird one found by https://github.com/Zylann/godot_heightmap_plugin/issues/57
My terrain plugin uses `PhysicsServer` to build a Bullet HeightmapShape of size 2049x2049, and apparently moving the mouse over it causes a massive slowdown, to 1 fps or lower, even when the shape is set to not be pickable. This makes collision on terrains completely unusable.
It should also be noted that my plugin creates this collider also in the editor, but for some reason, it doesn't cause any slowdown there. Also, I tested collisions just fine in a 513x513 terrain this morning, but perhaps it was small enough to not be noticed?

- Something must be wrong with the way picking actually triggers (only in 3.0.6)
- Something must be making raycasts very slow with HeightmapShapes (and by extent, probably any collision detection)

I made a minimal project showing the issue:
[HeightmapColliderSlowdown.zip](https://github.com/godotengine/godot/files/2683285/HeightmapColliderSlowdown.zip)
It just creates a completely flat HeightmapShape with the origin corner centered at the world origin, and an AABB spanning -1 to 1 in height (so it definitely encloses the heights).

It also reproduces in Godot 3.1 alpha3, but only if actually set to be pickable:
[HeightmapColliderSlowdown31.zip](https://github.com/godotengine/godot/files/2683287/HeightmapColliderSlowdown31.zip)

Play the main scene, and look at the console printing every frame.
Move the mouse above the area with a plane mesh: notice the massive slowdown.

Edit: just in case, I tested with power of two sizes: 2048 has no effect, and 1024 only halves the slowdown, but we are talking about 1 -> 2 fps here.

### PR DESCRIPTION
**Pull request by Zylann**
This is the same PR as the one I made to Bullet, all details are here: https://github.com/bulletphysics/bullet3/pull/2062
There is definitely room for improvements, however because it might not be merged to Bullet before Godot 3.1 is out, I post it here too.

It fixes https://github.com/godotengine/godot/issues/24390

### CODE REVIEW

**Comment by Chaosus** [comment]
@Zylann If you changed third party code - you should place `// -- GODOT -- start` and `// -- GODOT -- end` to changed sections

**Comment by akien-mga** [comment]
In that case it's not needed, provided this PR ends up in upstream Bullet.

**Comment by AndreaCatania** [comment]
Good job!

**Comment by hpvb** [comment]
Thanks! It ended up in bullet upstream so it will get merged with the next update anyway.

**Comment by akien-mga** [comment]
@hpvb Note that it's a different version that ended up in bullet upstream (@Zylann's PR was merged, then reverted, superseded by another).

I prefer not to cherry-pick for 3.1 as it would prevent Linux distros from building against Bullet 2.88.

**Comment by akien-mga** [comment]
This might also prevent building the master branch against system Bullet 2.88 BTW...

**Comment by akien-mga** [comment]
Indeed:
```
modules/bullet/shape_bullet.cpp: In static member function 'static btHeightfieldTerrainShape* ShapeBullet::create_shape_height_field(PoolVector<float>&, int, int, real_t, real_t)':
modules/bullet/shape_bullet.cpp:155:16: error: 'class btHeightfieldTerrainShape' has no member named 'buildAccelerator'
   heightfield->buildAccelerator(16);
                ^~~~~~~~~~~~~~~~
```

**Comment by akien-mga** [comment]
Reverted with #28328.

**Comment by akien-mga** [comment]
> In that case it's not needed, provided this PR ends up in upstream Bullet.

Sorry I should have made things clearer at that time. We track Bullet 2.88 stable, and I don't want to edit it unless we really have to (which means forcing Linux distros to use the bundled version, or letting them build a version with a different feature set, both options being subpar).

**Comment by akien-mga** [comment]
I still understand the need for this feature, so I'm open to a new PR that redoes these changes, but without breaking the possibility for building against distro-provided Bullet 2.88.

So this means:
- Applying https://patch-diff.githubusercontent.com/raw/bulletphysics/bullet3/pull/2204.patch on top of our current 2.88 source, eventually solving conflicts if any. The applied patch should also be `git add`-ed in the `thirdparty/bullet` folder to properly document our changes.
- The code in `modules/bullet` which uses the new API should be enclosed within `-DBUILTIN_BULLET`, which should be defined when compiling the thirdparty code in `modules/bullet/SCsub`.

Alternatively, convince upstream to make a new stable release of Bullet that we can track and encourage distros to upgrade to :)

**Comment by starry-abyss** [comment]
Why allow distro-provided Bullet at all? I understand security things like OpenSSL, but I think everything gameplay-related show be always bundled by developers with the exact version, not random from distro.
Also I though Godot only used a handful of files from Bullet.

**Comment by akien-mga** [comment]
After discussing with @AndreaCatania who also needs specific Bullet changes for fixing Godot issues, we decided to start tracking the bullet master branch and drop compatibility with 2.88 (in Godot master - those changes can't be cherry-picked for the 3.1 branch which should stay compatible with bullet 2.88).

As such I've reverted the revert in #28928, thus reinstating this PR. The bullet changes made in this PR are not a 1:1 match with the ones that were eventually merged upstream, but @AndreaCatania will soon do another PR to update us to latest upstream master.

**Pull request merged**
