### PR TITLE
Optimize and tweak the new Camera icons

### PR DESCRIPTION
**Pull request by MewPurPur**
**Before**

image

**After**

image

The reduction of the top part is a bit arbitrary I guess, but I think it was way too exaggerated, gave me [goose egg](https://www.cartoonmemes.in/tom_and_jerry/shocking/Tom-jerry%20Shocking%20Reactions%20(113).jpg) vibes

### CODE REVIEW

**Comment by YeldhamDev** [comment]
What's the reason of the gizmo one to look different?

**Comment by Calinou** [comment]
The ClippedCamera3D icon can be removed as that node was removed in 4.0.

**Comment by MewPurPur** [comment]
Oh? I thought I've seen it, must've been the CR one

**Comment by MewPurPur** [comment]
Tweaked the camera gizmo for a slightly less massive hole in the middle, and removed ClippedCamera

**Review by Calinou — APPROVED** [review]

**Comment by Mickeon** [comment]
Why have the asterisks on the CameraAttributes switched color between Physical and Practical?

**Comment by MewPurPur** [comment]
Oop, swapped when copy pasting.

This is a new icon in 4.2 though, and blue is more associated with physics anyway (it's the physics shape color) so I'm lazy to change it unless asked P:

**Pull request closed without merging**
