### PR TITLE
Move the deadzone to a column in the input project settings

### PR DESCRIPTION
**Pull request by groud**
From a suggestion from @reduz and @AndreaCatania  :)

2018-04-19-224217_850x342_scrot

### CODE REVIEW

**Comment by aaronfranke** [comment]
Wouldn't it look better to have the up/down arrows to the left of the number?

**Comment by groud** [comment]
> Wouldn't it look better to have the up/down arrows to the left of the number?

Well, I personally believe it's good as is. 
But anyway, that's how it is done everywhere else in the engine. This can't be changed without a big rework of the Spinbox+Tree nodes, which is out of the scope of this PR. :)

**Comment by guilhermefelipecgs** [comment]
Is there a way to set up dead zone globally to all actions?

**Comment by groud** [comment]
@guilhermefelipecgs, no, but it makes no sense.
The deadzone is a threshold determining when a joypad stick is considered as bent enough to be considered as "pressed". Thus for boolean actions (like moving through a door in a platformer for example), it makes sense to have a highdeazone, something like 0.5, while for the basic movements, a deadzone of 0.1 is more appropriate. Since this highly depend on the action, there's no point in making this a global parameter.

**Pull request merged**
