### PR TITLE
Document reproducability of Array.shuffle()

### PR DESCRIPTION
**Pull request by hbina**
Updated description of Array..shuffle to describe that it uses a common seed meaning it is generally reproducible.

P.S. Old PR was messed up with unnecessary files and commits...my bad

### CODE REVIEW

**Comment by aaronfranke** [comment]
In the future, I recommend that you read the [PR workflow](https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html) article. You can squash commits together into one to clean up history, then force push.

**Review by aaronfranke — APPROVED** [review]

**Comment by mhilbrunner** [comment]
For reference, the old PR was https://github.com/godotengine/godot/pull/28699.

Thanks for making the requested changes, and thanks for the PR!

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by akien-mga** [comment]
Not relevant for the 3.0 branch which doesn't have this method.

**Pull request merged**
