### PR TITLE
Fix vsproj generation for custom_modules.

### LINKED ISSUE #91862: Custom module source files are not included in generated Visual Studio project
### Tested versions

Reproducible in: 4.3.dev6 and latest master as of reporting: bdc0316217940a8ccc80ce536547d42e6477adf4

Not Reproducible in: 4.2.2

### System information

Windows 11, Visual Studio 2022, SCons 4.7.0

### Issue description

When configuring/building godot with the below command, source files from `custom_modules` directories are not included in the generated Visual Studio project.

`scons p=windows vsproj=yes custom_modules=../modules`

### Steps to reproduce

1. Create a minimal custom module directory outside of your godot source directory, the following layout works:
```
├─ godot
│  └─ <godot repo here>
└─ modules
   └─ mymodule
      ├─ config.py
      ├─ mymodule.cpp
      ├─ register_types.h
      └─ SCsub
```
config.py:
```
def can_build(env, platform):
    return True
def configure(env):
    pass
```

mymodule.cpp: empty

register_types.h:
```
#pragma once
#include "modules/register_module_types.h"
void initialize_mymodule_module(ModuleInitializationLevel p_level) {}
void uninitialize_mymodule_module(ModuleInitializationLevel p_level) {}
```

SCsub:
```
Import('env')
env.add_source_files(env.modules_sources, "./mymodule.cpp")
```

2. Create the visual studio project by running `scons p=windows vsproj=yes custom_modules=../modules`
3. Observe that with the latest master `mymodule.cpp` is not part of the VS project, but with 4.2.2 it is.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by obhi-d**
Fixes #91862. Path is maintained for custom modules as in 4.2.

### CODE REVIEW

**Comment by fire** [comment]
Are you familiar with the pre-commit workflow? You can use it to update the formatting.

I install precommit with `pip install pre-commit` and then run `pre-commit run -a` at the base of godot engine.

**Comment by obhi-d** [comment]
> Are you familiar with the pre-commit workflow? You can use it to update the formatting.
> 
> I install precommit with `pip install pre-commit` and then run `pre-commit run -a` at the base of godot engine.

I wasn't. I will re-commit.

> Are you familiar with the pre-commit workflow? You can use it to update the formatting.
> 
> I install precommit with `pip install pre-commit` and then run `pre-commit run -a` at the base of godot engine.

Done.

**Comment by jlwitthuhn** [comment]
Original bug reporter here, confirming that this does work and has solved my problem. Thanks for the fix.

**Comment by fire** [comment]
[94099.patch](https://github.com/user-attachments/files/16646725/94099.patch)

**Comment by tomasjanak** [comment]
Hello, the original issue reported as https://github.com/godotengine/godot/issues/91862 seems to still persist - I am not able to include modules from outside of the folder with Godot solution on current master (commit 0fdbf050e0c7fc7e0a9d42c2a41ee3bfdffbd8f1). As far as I can tell, this fix was never merged into master, but I don't see any explanation as to why not, was there some problem with it?

**Comment by fire** [comment]
I think it is salvageable but we need someone to pull request it again.

**Pull request closed without merging**
