### PR TITLE
Fix round preview getting square on "run scene" (issue 16734)

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/godotengine/godot/issues/16734#issuecomment-366445627

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Does this also fixes it smoothing the scene previews in the tabs?

**Comment by poke1024** [comment]
Hi @YeldhamDev, not sure in which tabs the preview will be shown, can you give me a screenshot? It's not the regular editor tabs as below, right?

tabs

**Comment by YeldhamDev** [comment]
@poke1024 Those exactly.

**Comment by poke1024** [comment]
It looks to me as if the tabs are also fixed now (even though the preview's resolution is low, but that's a different issue if any):

tab

**Comment by YeldhamDev** [comment]
@poke1024 My point is about the edges in the tab previews getting smoothed in the first place. But as the preview image being the same from the one in the filesystem, I think there is no way around that, right?

**Comment by poke1024** [comment]
@YeldhamDev That's right, we'd need to either have a separate file or do the rounding as a post processing step that never gets saved to the FS. I'll take another look.

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Pull request merged**
