### PR TITLE
Mct ar requirerments

### PR DESCRIPTION
**Pull request by elmajime**

### CODE REVIEW

**Comment by RedMser** [comment]
Why was this closed without comment? It looks like a revival of #26221 from the commit messages.

I think it just has to be set to merge into `master` branch.

**Comment by AThousandShips** [comment]
My bad, this looked like an accidental merge into the engine, as the OP was a first time contributor and the message was cryptic, without any details in the PR comment

Indeed should target `master`

**Comment by elmajime** [comment]
Sorry if I made a mistake, I was not planning in merging yet, just wanted
to share a diff of my work on 4.2 to get some insight from devs in the chat.

Maxime

Le dim. 21 avr. 2024, 13:22, A Thousand Ships ***@***.***> a
écrit :

**Comment by RedMser** [comment]
For the future, if you don't plan on having it merged in this state, you can open a Pull Request as a "Draft" which makes this clear :+1:

**Comment by AThousandShips** [comment]
Also remember to add a description to your PR to make it clear what's going on

**Pull request closed without merging**
