### PR TITLE
Fix OpenXR initialization - introduce pre server initialization level

### LINKED ISSUE #60977: [Vulkan / OpenXR] Godot 4.0-alpha8. VR does not work: OpenXR: Failed to create session [ XR_ERROR_VALIDATION_FAILURE ]
### Godot version

v4.0.alpha8.official [cc3ed63af]

### System information

Windows 10, Nvidia RTX3060Ti studio driver 512.59, SteamVR 1.22.11, HP Reverb G2

### Issue description

Running the included test project in alpha8 results in a flashing session screen and gives the error "OpenXR: Failed to create session [ XR_ERROR_VALIDATION_FAILURE ]"
billede

The test project runs fine in alpha7.
billede

### Steps to reproduce

1. Run the included test project in Godot 4.0-alpha7: Observe that it runs fine.
2. Run the included test project in Godot 4.0-alpha8: Observe that it produces a flashing screen and the mentioned error.

### Minimal reproduction project

[VR Test.zip](https://github.com/godotengine/godot/files/8681552/VR.Test.zip)

### PR DESCRIPTION
**Pull request by BastiaanOlij**
As mentioned in https://github.com/godotengine/godot/pull/60723#discussion_r864892817 removing the preserver initialization step in the big module initialization refactor PR breaks OpenXR. `MODULE_INITIALIZATION_LEVEL_CORE` is too early, `MODULE_INITIALIZATION_LEVEL_SERVERS` is too late. Totally forgot to test it at the time, my fault :(

So I had to introduce `MODULE_INITIALIZATION_LEVEL_PRE_SERVERS` as an initialization level to re-introduce the correct timing to setup OpenXR correctly. This obviously is a breaking change for any GDExtension module that will have to be recompiled with new headers.

Fixes #60977

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Looks like I'm still missing something on `NativeExtensionManager::deinitialize_extensions`, I'm getting a
```
ERROR: Condition "int32_t(p_level) != level" is true.
   at: NativeExtensionManager::deinitialize_extensions (core\extension\native_extension_manager.cpp:107)
```

**Comment by BastiaanOlij** [comment]
Ok, fixed the issue, looks like I missed part of the GDExtension initialisation.

**Comment by reduz** [comment]
What prevents from initializing this in CORE instead?

**Comment by BastiaanOlij** [comment]
Discussed this on the XR channel with Reduz. 

Just for others reading this:

> What prevents from initializing this in CORE instead?
Core sets up our project settings and other core objects, it's only after CORE that we're parsing our rendering device settings and know the rendering device name (i.e. Vulkan or OpenGL) which OpenXR needs to know about so we can instantiate the correct extensions.

SERVER is too late because at this point in time our `DeviceServer` has already setup our rendering device. Specifically for Vulkan our OpenXR setup needs to be done before this as we're overruling part of the Vulkan initialisation.

The alternative solution we came up with is being implemented in #61072

**Comment by BastiaanOlij** [comment]
Closing this as the other solution has taken over.

**Pull request closed without merging**
