### PR TITLE
Allow class_name scripts to have nested inheritance

### LINKED ISSUE #26714: [Regression since beta 11, bda60bf] Can't add a custom class (class_name) via editor, if it extends another custom class.
**Godot version:**

3.1.11

**OS/device including version:**

Windows 10 64bit

**Issue description:**

Cant add a custom class_name node from the inspector if it extends from another class_name class. It also shows no icon in the editor. Adding a normal node and then adding the script manually works. Error code:
` ERROR: instance: Condition ' !ti ' is true. returned: __null
At: core/class_db.cpp:512
ERROR: _create: Condition ' !c ' is true.
At: editor/scene_tree_dock.cpp:1698`

**Steps to reproduce:**

Try to add "ClassTwo" to the scene via editor

**Minimal reproduction project:**

[Test.zip](https://github.com/godotengine/godot/files/2937245/Test.zip)

### PR DESCRIPTION
**Pull request by vnen**
Fix #26714

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @neikeq in case the new API is relevant/useful for Mono.

**Comment by neikeq** [comment]
What are global script classes?

**Comment by akien-mga** [comment]
> What are global script classes?

Classes identified with `class_name` in GDScript, whose name becomes available as a global and can be instantiated directly in the Add Node dialog.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
