### PR TITLE
move "yield" to functions

### PR DESCRIPTION
**Pull request by ShalokShalom**
Yield is implemented already

This seems compatible with Godot 3 as well

### CODE REVIEW

**Comment by akien-mga** [comment]
Well the "implementation" for `yield` is that it tells you that it has been replaced :)
```
"yield" was removed in Godot 4.0. Use "await" instead.
```
So here `yield` was likely moved at the end to signify that it could be reserved for future re-use. We can move it up but this doesn't really solve anything :)

This is not relevant for `3.x` where `yield` is listed among keywords.

**Comment by ShalokShalom** [comment]
I found another instance, is this correct? https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_tokenizer.h#L130

I assume it can go out, from this?
Considering its not in the language anymore.

**Comment by ShalokShalom** [comment]
Also https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.h#L1418

**Comment by akien-mga** [comment]
It's registered as a keyword/token to be able to raise the helpful error mentioned above.

What are you trying to solve?

**Comment by ShalokShalom** [comment]
Oh, then its fine
I was browsing through the code for other reasons
Thanks a lot
P.S: This code is SO readable, its a joy 👍🏼

**Pull request closed without merging**
