### PR TITLE
Add tool quick-select to tile editor

### PR DESCRIPTION
**Pull request by KoBeWi**
This is a feature I'm really missing from the old editor.

When Paint tool is selected:
- Hold Shift to draw lines
- Hold Shift + Ctrl to draw rectangles

When any drawing tool is selected (Paint, Line, Rect, Bucket):
- Hold Ctrl to pick tile

Also RMB will erase tiles. There was some controversy last time I suggested it (something with panning), so it's added in a second commit. RMB erasing has no preview (most notable with bucket tool).

r9SBvo2rOW

EDIT:
btw the change in BaseButton was required to make `_get_current_tool()` const.

### CODE REVIEW

**Comment by groud** [comment]
> Also RMB will erase tiles. There was some controversy last time I suggested it (something with panning), so it's added in a second commit. RMB erasing has no preview (most notable with bucket tool).

Yeah, this cannot be merged. If I am not mistaking, the problem was that some mice (likely Apple ones), only have 2 buttons (no middle mouse button). So we need to keep panning on right click.

**Comment by KoBeWi** [comment]
Maaybe we could have a setting to disable RMB erasing? It's very handy feature, kinda sad to remove it entirely because of some mice which are probably minority.

**Comment by akien-mga** [comment]
Ctrl+Left click is a common option for planning if there is no MMB I think.

**Comment by KoBeWi** [comment]
Except Ctrl+Left click is already used for tile picking 🙃

**Comment by Zireael07** [comment]
> Except Ctrl+Left click is already used for tile picking 🙃

Change that to Shift or Alt +lmb?

**Comment by KoBeWi** [comment]
idk, isn't Ctrl more common for picking?

**Comment by Zireael07** [comment]
If there's no panning, yes. If there is panning involved, ctrl +lmb is usually pan (by itself or as an alternative to mmb) and picker is some other function key.

**Comment by KoBeWi** [comment]
I noticed that Space can be used for panning, both with LMB and RMB, so the panning concerns are irrelevant. I reverted the pick button change.

There's also a concern of https://github.com/godotengine/godot-proposals/issues/3380, but there seems to be conflicting experiences on what button combination actually changes the locale, so changing/removing the shortcut is pointless. If anything, we could make the quick-tool behavior optional, it's easy to disable conditionally.

Rebased and squashed.

**Review by groud — CHANGES_REQUESTED** [review]
I am kind of confused why you would need so many changes to implement this. I think the addition of `_get_current_tool()` is quite confusing.

The change should only be a matter of checking, when starting a drag, whether the RMB or modifier keys are pressed, and choose the right drag_type according to the different combinations. I think there not a lot of value in moving everything into a dedicated `_get_current_tool()` function anyway, as all the tests for input aren't so difficult to find in the code, and are usually tested once.

**Comment by KoBeWi** [comment]
@groud Changes done.

**Review by groud — APPROVED** [review]

**Pull request merged**
