### PR TITLE
Improve startup benchmarking

### PR DESCRIPTION
**Pull request by m4gr3d**
Update the benchmark measure logic to allow for more flexible usage.

Move the benchmarking measuring methods from `Engine` to `OS` to allow for platform specific overrides. For example this can be used to hook into platform specific benchmarking and tracing capabilities. On Android, this allows to hook into the Android SDK tracing APIs, which can be used with tools like [systrace](https://developer.android.com/topic/performance/tracing/command-line).

*Note*: `breaks compat` tag refers to the change in the command line from `--startup-benchmark[-file]` to `--benchmark[-file]`

E.g: 

- Project manager run using a Godot Android Editor 4 dev build on a Pixel 5:

```
I/GodotBenchmark: BENCHMARK:
    	- Godot::onCreate : 0.125 sec.
    	- core : 0.059 sec.
    	- create_custom_theme : 1.83 sec.
    	- create_editor_theme : 1.83 sec.
    	- editor_register_and_generate_icons_all : 1.102 sec.
    	- editor_register_and_generate_icons_with_only_thumbs : 0.017 sec.
    	- editor_register_fonts : 0.027 sec.
    	- project_manager : 2.324 sec.
    	- register_core_types : 0.036 sec.
    	- register_editor_types : 0.009 sec.
    	- scene : 0.616 sec.
    	- servers : 0.728 sec.
    	- startup_begin : 3.984 sec.
```

- Editor run using a Godot Android Editor 4 dev build on a Pixel 5
```
I/GodotBenchmark: BENCHMARK:
    	- Godot::onCreate : 0.121 sec.
    	- core : 0.064 sec.
    	- create_custom_theme : 2.033 sec.
    	- create_editor_theme : 2.033 sec.
    	- editor : 10.592 sec.
    	- editor_register_and_generate_icons_all : 1.315 sec.
    	- editor_register_and_generate_icons_with_only_thumbs : 0.017 sec.
    	- editor_register_fonts : 0.028 sec.
    	- register_core_types : 0.031 sec.
    	- register_editor_types : 0.008 sec.
    	- scene : 0.582 sec.
    	- servers : 0.314 sec.
    	- startup_begin : 11.765 sec.
```

- Screenshot of the trace data generated with the added system trace hooks

Screenshot 2023-01-16 at 10 52 42 PM

### CODE REVIEW

**Comment by Calinou** [comment]
Could editor/project shutdown times also be measured with this benchmark system? I think there are some optimizations we could do to shutdown time, as Godot is generally one of the apps that feels the slowest to close on my PC.

**Comment by m4gr3d** [comment]
> Could editor/project shutdown times also be measured with this benchmark system? I think there are some optimizations we could do to shutdown time, as Godot is generally one of the apps that feels the slowest to close on my PC.

Yeah, let me add a few benchmark calls to measure general shutdown.

**Comment by m4gr3d** [comment]
@Calinou At least on Android, shutdown doesn't seem to take much time. E.g: project manager shutdown:
```
    	- Main::cleanup : 0.072 sec.
```

**Comment by clayjohn** [comment]
I think there is an overflow somewhere running the project manager with ``--verbose --benchmark`` I get the following:
```
BENCHMARK:
	- servers :  0.227753  sec.
	- scene :  0.209894  sec.
	- editor_register_and_generate_icons_all :  0.378395  sec.
	- editor_register_and_generate_icons_with_only_thumbs :  0.00186  sec.
	- editor_register_fonts :  0.013976  sec.
	- create_editor_theme :  0.637456  sec.
	- create_custom_theme :  0.637475  sec.
	- project_manager :  0.90227  sec.
	- startup_begin :  18446744056198.8  sec.
```
To be clear, it did not take ``18446744056198.8`` seconds to start

**Comment by neikeq** [comment]
I think we should measure `register_core_types` (maybe the one for the editor types as well). Especially since some GDScript related changes are being introduced lately, which could slow things down.
It would be good to know how much startup time is spent registering types, since I think there's room for optimization there if it's actually worth it.

**Comment by m4gr3d** [comment]
> I think there is an overflow somewhere running the project manager with `--verbose --benchmark` I get the following:
> 
> ```
> BENCHMARK:
> 	- servers :  0.227753  sec.
> 	- scene :  0.209894  sec.
> 	- editor_register_and_generate_icons_all :  0.378395  sec.
> 	- editor_register_and_generate_icons_with_only_thumbs :  0.00186  sec.
> 	- editor_register_fonts :  0.013976  sec.
> 	- create_editor_theme :  0.637456  sec.
> 	- create_custom_theme :  0.637475  sec.
> 	- project_manager :  0.90227  sec.
> 	- startup_begin :  18446744056198.8  sec.
> ```
> 
> To be clear, it did not take `18446744056198.8` seconds to start

@clayjohn Were you running on Windows?

**Comment by m4gr3d** [comment]
@clayjohn @Geometror The issue you ran into should be resolved. 

It seems to have occurred because the benchmark call was made before `OS::get_singleton()->initialize`, which (at least on Windows) is necessary to properly setup the ticks time functions.

@neikeq I've added benchmark measurements to `[un]register_core_types` and `[un]register_editor_types`.

**Comment by akien-mga** [comment]
Moving to 4.1 milestone as we're very close to releasing 4.0 RC 1, and it's not critical for the release. It doesn't seem to break compat in the meaning we usually use (doesn't break the GDScript/GDExtension public API).

That will be of great help for all the optimization work planned for 4.1 (and the initial optimizations that can be made via this PR in the current `master` are of course nice to have).

**Review by akien-mga — APPROVED** [review]
Approved in production meeting. Needs a rebase.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
