### PR TITLE
Add 'create_module.py' to streamline module creation process

### PR DESCRIPTION
**Pull request by jordigulley**
Add a python script that creates a barebones custom module in the `modules/` folder.

Example:
`D:\godot> py modules/create_module.py "My Module"`
Creates the following file structure:
image

This build option makes it easier to add modules by allowing you to easily create a barebones module with everything you need to get started.

You can see the full generated code [here](https://github.com/summertimejordi/custom_module_generation_example).

### CODE REVIEW

**Comment by summertimejordi** [comment]
The python formatting issue that caused the Static Checks to fail should be fixed now. Since I'm a first-time contributor I need a maintainer to approve running the workflows, though.

**Comment by Xrayez** [comment]
You may be interested in a specialized tool that I created exactly for this purpose, see [gdgen Python package](https://pypi.org/project/gdgen/) (does not support Godot 4.0 yet, you may as well consider contributing, if you want).

I've also had an idea to make this available in Godot in the past, since module generation should be tied to specific Godot version. But I'm not sure whether this is going to be approved by the core developers.

In any case, there are several considerations to make.

Because this is related to modules development, it may be just enough to make a simple Python scripts which does this directly at `modules/` directory. Something like `modules/create_module.py`. The idea is similar to @Calinou's #48660 to generate tests. This has the following benefits:

1. If you're looking for modules, you'll likely find the right tool to get started when you look at `modules/` directory.
2. SCons is too slow, especially on Windows. It will parse build stuff unnecessarily each time `scons` is invoked. There are certain optimizations which could be done, of course, but as I said, implementing this as a single script should be more convenient in my opinion.
3. `SConstruct` will not be bloated. But if we do decide to make this available as a SCons option, then you'd have to move the code to `methods.py`, which would be more clean.

There's also a task of generating either minimal module functionality, or providing everything needed to build a single class. This is something that Godot members will have to decide, based on how they're willing to maintain the script in the future.

**Comment by summertimejordi** [comment]
> 1. If you're looking for modules, you'll likely find the right tool to get started when you look at `modules/` directory.
That's a good point, it should be relatively easy to just move the existing code to a script. I'll test that soon.

> There's also a task of generating either minimal module functionality, or providing everything needed to build a single class. This is something that Godot members will have to decide, based on how they're willing to maintain the script in the future.

As of now, this PR creates an empty RefCounted class without any ClassDB bindings
```
#include "my_module.h"

void MyModule::_bind_methods() {
}
MyModule::MyModule() {}
```

**Comment by summertimejordi** [comment]
I've moved all the code from this PR from scons to a separate script in the modules folder named `create_module.py`. It takes the name of the module to create as an argument instead of a build option.

**Comment by summertimejordi** [comment]
topic:plugin might be better than topic:buildsystem now that I've separated it from scons.

**Comment by Calinou** [comment]
> topic:plugin might be better than topic:buildsystem now that I've separated it from scons.

`topic:plugin` is for editor plugins, I think `topic:core` is more suited here.

**Comment by summertimejordi** [comment]
I think this is ready for review, I'm new to this process so I'm curious on how I can get this merged?

**Comment by mhilbrunner** [comment]
Thanks for contributing :)

I'm not sure how worthwhile this is compared to the maintenance burden of having to keep it up to date.
When I implemented my first Godot module (and I was completely new to Godot and only a little experienced in C++ back then) I found it fairly easy to copy paste from one of the other modules, and adapt that.
It could also be in a Gist or on a blog somewhere and it wouldn't be much worse if found on a quick "how to create a Godot module" search?

Also, the preferred approach with Godot 4.0 will likely be to use the new extension system.

**Comment by summertimejordi** [comment]
Yeah agreed, I'll close this for now.

**Pull request closed without merging**
