### PR TITLE
Improve/fix packed data API

### PR DESCRIPTION
**Pull request by RandomShaper**
- Enhance directory API
- Fix `FileAccess::exists()` not checking for PackedData being disabled
- Fix moving to the parent directory (`..`)
- Allow absolute paths in existence checks

**NOTE:** Separate PR submitted for 3.2.

---
**This code is generously donated by IMVU.**

### CODE REVIEW

**Comment by akien-mga** [comment]
You added IMVU submodules :)

**Comment by RandomShaper** [comment]
OMG! Fixed.

**Review by bruvzg — APPROVED** [review]
Seems fine.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
