### PR TITLE
Fix non-latin layout scancodes on Linux, adds access to physical scancodes.

### LINKED ISSUE #8039: In game inputs from non english layouts should be treated as their qwerty equivalent (like SDL2 scancodes)
Linux Kubuntu 16.10 Godot 2.1.2 x64 official
Self descriptive. After switching layouts, in game inputs from keyboard are ignored. 

Expected behavior: processing inputs as if they are from english layout.

### PR DESCRIPTION
**Pull request by bruvzg**
**[Linux/X11] Fix non-latin keyboard layout scan-codes. (see #17827 comments).**
Fallback to physical keycode if layout remapping fails.

Fixes #8039

**[Linux/X11, macOS, Windows, UWP] `scancode` renamed to `keycode`, added `physical_keycode` to `InputEventKey`.**
Layout independent keycode, which represent the physical location on keyboard. (e.g. keys in highlighted locations will produce event with `keycode` = `Q, MINUS, K, C` on DVORAK-L layout, and `physical_keycode` = `W, A, S, D` on any keyboard layout.)

dvrk

### CODE REVIEW

**Comment by reduz** [comment]
I would like to know why remapping was changed for OSX only, did we not have remapping in other platforms?

The idea of the scancodes is that they are keyboard dependent, there is no use case IMO for physical (qwerty) keycodes.

**Comment by bruvzg** [comment]
> I would like to know why remapping was changed for OSX only, did we not have remapping in other platforms?

All platforms have remanning, macOS was only one limited to some hardcoded mappings, #17827 changes mapping from hardcoded to generated for current OS keyboard layout.

**Comment by rosshadden** [comment]
Letting you map to the physical keys is a dream come true! This branch is a bit buggy when adding a remapped key or changing existing key mappings (as of `2c9413f`), but the core feature itself works and is SO VERY exciting for me.

I always have things mapped to dvorak keys while developing a game and change them out later once I add configuration. This makes it particularly complicated when sharing prototypes with people before this point, as I have to remap everything just for them, and then back.

**Comment by mhilbrunner** [comment]
Whats the status of this?

**Comment by reduz** [comment]
Let me explain why this should not be merged.

1. All keyboards, no matter the language, whether Japanese, Arabic, Hebrew, etc. have a latin mode. This is what Godot returns as scancode. If it doesn't for some reason, it should be fixed but that's the idea.
2. For the actual symbol, Godot returns Unicode.

Physical scancode (which is pretty much the US keyboard code) is undesired, as it's non standard.

**Comment by reduz** [comment]
The suggested feature to get something like this working, would be to add a function to OS:
```
OS.get_IBM_scancode(scancode)
```
that translates a Godot scancode to the right physical IBM key. This way, common Input functions can still be used like:

```
Input.is_key_pressed( OS.IBM_to_scancode(KEY_A) )

if (ev.scancode == OS.IBM_to_scancode(KEY_A) ):
```
or something similar, a better name needs to be found.

**Comment by bruvzg** [comment]
>The suggested feature to get something like this working, would be to add a function to OS:
OS.get_IBM_scancode(scancode)

38335618-8e60e15a-3867-11e8-99f6-55eb3ddadd67
Lets look at this keyboard layout, currently following scancodes are returned:

* Blue Key -> **KEY_G**
* Red Key -> **KEY_E** (on macOS and Linux with this PR), **KEY_SEMICOLON** (Windows) or **0** (Linux without this PR)
* Green Key -> **KEY_E**

With current scancodes `OS.get_IBM_scancode(scancode)` like function will not work since two keys return same scancode in this layout.

What should be correct scancode for Red Key?

**Comment by bruvzg** [comment]
> Physical scancode (which is pretty much the US keyboard code) is undesired, as it's non standard.

It is standard. X11 and macOS keypress events provide ONLY physical key codes. Windows events have both physical and remapped key codes.

**Comment by moiman100** [comment]
This has currently build errors after rebase, but they are just two lines which aren't used anymore it seems.

I think this is really nice and should be merged, but I have some suggestions.

I don't think all of these are problems of this PR, but it'd be nice if they would be fixed.
My keyboard is 102/105 - ISO using Finnish QWERTY layout.

1. Context menu key is unknown on remapped, but works on hardware. VK_APPS on windows
2. <kbd><</kbd> key is unknown on both. VK_OEM_102 on windows
3. If num lock is off on remapped keypad 5 is unknown.
4. Meta key show "Meta +" on remapped and "Meta" on hardware.
5. Media keys and calc key are unknown on hardware. (Calc is launch1 on remapped)
6. Play/Pause is unknown on remapped. Other media keys work.

Here is a img of different physical layouts to show what might be missing on other layouts.

**Comment by bruvzg** [comment]
> All keyboards, no matter the language, whether Japanese, Arabic, Hebrew, etc. have a latin mode. This is what Godot returns as scan-code. If it doesn't for some reason, it should be fixed but that's the idea.

All keyboards have a way to input latin characters, but not all keys on every keyboard have base latin char associated with it (see `ĞIÜŞÖÇ` key in one of my previous comments), I do not see any reasonable way to assign scan-code for these keys.

Personally I don't think remapped scan-codes have any use at all, menu shortcuts and other staff implying reference to the specific word should be bound to unicode character instead of scan-code.

Everything else should use physical scan-codes, but UI should display character representation for current layout (for this we'll probably need to process OS keyboard layout change event, like `WM_INPUTLANGCHANGE` on Windows and `kTISNotifySelectedKeyboardInputSourceChanged` on macOS).

>Context menu key is unknown on remapped, but works on hardware. VK_APPS on windows
< key is unknown on both. VK_OEM_102 on windows
If num lock is off on remapped keypad 5 is unknown.
Meta key show "Meta +" on remapped and "Meta" on hardware.
Media keys and calc key are unknown on hardware. (Calc is launch1 on remapped)
Play/Pause is unknown on remapped. Other media keys work.

Some scan codes are definitely missing.

On macOS media keys doesn't trigger any keypress event at all and I have unknown `\|` key on both macOS and Windows.

I prefer to wait until we all get to a consensus before fixing anything, otherwise this work'll be in vain.

**Comment by agameraaron** [comment]
To clarify a bit, I am using Linux Mint XFCE and I am using a U.S. QWERTY keyboard to support multiple layouts. I am testing by switching the layout in software. I tend to use Dvorak, so I test with that. It reports the key correctly, but the keys all seem to be tied to a certain keyboard layout when they shouldn't be.

In response to Juan: "Physical scancode (which is pretty much the US keyboard code)"
I thought it applies to all keyboards as a standard because it refers to the placement of keys by number, not the character itself. I want to use them specifically so I can easily set up for the user one of many layouts that are outside of U.S. QWERTY keyboards, but they all give me different codes when I switch to different layouts in.

This is a little program I made to test this and it is how I came to my conclusions: https://github.com/agameraaron/simple-input-observer/releases/tag/v0.1

**Comment by akien-mga** [comment]
Just tested to compile this on the current master branch after a rebase, and this diff needs to be applied:
```diff
diff --git a/editor/project_settings_editor.cpp b/editor/project_settings_editor.cpp
index 4016009cf..ca0b1490c 100644
--- a/editor/project_settings_editor.cpp
+++ b/editor/project_settings_editor.cpp
@@ -473,9 +473,6 @@ void ProjectSettingsEditor::_add_item(int p_item, Ref<InputEvent> p_exiting_even
 			last_wait_for_key = Ref<InputEvent>();
 			press_a_key->popup_centered(Size2(250, 80) * EDSCALE);
 			press_a_key->grab_focus();
-
-			device_special_value_label->hide();
-			device_special_value->hide();
 		} break;
 		case INPUT_MOUSE_BUTTON: {
 
```

**Comment by akien-mga** [comment]
@bruvzg Commit 29595192 doesn't seem to depend on the other two, and would likely be simple to review by itself, so it might be worth splitting in its own PR?

As for the other two, I'm very much in favour of giving a way to access a kind of physical scancodes. I just tried the PR and it works great to bind e.g. `1, 2, 3, 4` (hardware) instead of `&, é, ", '` (remapped) on AZERTY as actions like you would have typically in FPS or RTS games.

Some more discussion might be needed regarding how to name and expose the feature, and @reduz still needs to be convinced fully (but he's not too far from it ;)), which is why I suggest to split the 3rd commit for now.

**Comment by akien-mga** [comment]
Moving to 3.2 milestone, we're very close to beta for 3.1 and there is still discussion and design changes needed for this PR.

**Comment by Yukitty** [comment]
> Let me explain why this should not be merged.
> 
>     1. All keyboards, no matter the language, whether Japanese, Arabic, Hebrew, etc. have a latin mode. This is what Godot returns as scancode. If it doesn't for some reason, it should be fixed but that's the idea.
> 
>     2. For the actual symbol, Godot returns Unicode.
> 
> 
> Physical scancode (which is pretty much the US keyboard code) is undesired.

In other words, Godot returns the _keycode_, which changes entirely based on the keyboard layout, and simply _calls_ it a "scancode".

And also unicode (which is the glyph itself), which is what you _would_ be using if you actually wanted the input to change based on the keyboard layout or cared at all what glyph is on the key that was pressed to begin with. Which is almost never the case, only being useful for taking text input... which is better handled after composition takes place anyway, not generally during individual keypresses.

And never at any point, at the engine level and by design, would Godot allow you to set keybinds based on anything even remotely representative of the _physical location_ of the keys in relation to eachother. Nor does it allow you to detect which keyboard layout is being used so you can remap the keyboard controls programmatically in a script! Meaning that if I want to map some basic, default controls to the Z and X keys, all of my QWERTZ friends are going to immediately throw a fit... and there is literally nothing I can do about it but tell them to go manually remap the keyboard controls themselves.

You're right. This should not be merged in its current state. We don't need "qwerty_scancode" to be a new thing. Instead, the original scancode should just be completely replaced by it. _It should have never worked the way it does currently in the first place._ 😠

This does not deserve to be sitting in pull request limbo for 2 years when it fixes a critical issue preventing games from being properly internationalized.

**Comment by reduz** [comment]
I apologize because we discussed this in the previous Godot Sprint and reached a resolution, then we completely forgot to add comment about it here. Then with the huge amount of tasks we usually do, this was completely forgotten. I found it again when checking notes for things do break compatibility for 4.0 branch.

**Comment by reduz** [comment]
What we discussed is that we should do something similar as this PR, including the Qwerty scancode (we should call it "us" or "hardware", or "physical" keycode, some people have no idea what qwerty is or how it looks like, also what @Yukitty mentions is not really doable due to modifiers and deadkeys).

The idea is that the following should be supported:

* we should probably rename scancode to keycode, as scancode is misleading
* The hardware scancode (physical_keycode property I propose?) should indeed be added to InputEventKey
* Actions that are physical keycodes should be marked as such, but their physical keycode should not be used for the action, it shouldl be saved as an InputEventKey with keycode = 0 , physical_keycode != 0
* The key editor in ProjectSettings does not use InputMap, so it should always treat/display the event as physical keycode when the above condition is met.
* When loaded in InputMap, it should just be converted from physical keycode to regular keycode by calling a function in OS. InputMap does not really need to understand physical keycodes.

Again, apologies for leaving this on StandBy, we did not properly document what we discussed in 2019 so this was lost, we tried to change this in 2020 and now we have a detailed doc for this.

**Comment by bruvzg** [comment]
> When loaded in InputMap, it should just be converted from physical keycode to regular keycode by calling a function in OS. InputMap does not really need to understand physical keycodes.

That's bad idea, keyboard layout is not constant, especially if someone uses non-latin layout, they will probably have at least two layouts "Local" and "English" quickly switchable, and it probably will be switched if app have any text input involved and break input mappings that were loaded with different layout.

**Comment by reduz** [comment]
@bruvzg ah, I did not know that and did not come up in the discussion, clearly a product of our ignorance when we discussed it, i guess it then makes full sense to add support for it in InputMap. If this is the case, what would be remaining in this PR for it to be merged? The only suggestion we had remaining is renaming qwerty to physical.

**Comment by reduz** [comment]
and given we are breaking compat in 4.x, maybe renaming scancode to keycode, if there is agreement for this.

**Comment by Yukitty** [comment]
Thanks for the updates and consideration. I'm glad you're on top of this. :+1:

**Comment by bruvzg** [comment]
- `scancode` renamed to `keycode`, `qwerty_scancode` to `physical_keycode`
- `physical_keycode` is used only if `keycode == 0`
- both are available in Project Settings/Input Map, Editor Shortcuts are left as is.

Screenshot 2020-02-24 at 10 53 04

- `physical_keycode` is implemented and tested on Linux/X11, macOS and Windows, implemented but not tested on Android and UWP, on the other platforms `physical_keycode` is always set to be equal to `keycode`.

**Comment by akien-mga** [comment]
Thanks a lot!

**Pull request merged**
