### PR TITLE
Fix get_window_position / set_window_position on Linux

### LINKED ISSUE #26971: Inconsistent get_window_position() / set_window_position() behaviour on multi-monitor Linux setup
**Issue description:**

`OS.get_window_position()` return window position relative to the current screen (on macOS and Windows same function return absolute position).

Untitled

`OS.set_window_position()` expects absolute window position.

Doing something like `OS.set_window_position(OS.get_window_position() + delta)` results in window jumping all over the screens, instead of moving it by `delta` value.

**Godot version:**
3.1.master

**OS/device including version:**
Ubuntu 18.10, multi-monitor configuration (all displays share same X screen and session)

### PR DESCRIPTION
**Pull request by bruvzg**
Fix `OS.get_window_position` to return absolute coordinates.
Change `OS.set_window_position` to take window decorations into account.

Fixes #26971

### CODE REVIEW

**Comment by reduz** [comment]
seems fine i guess

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Note to release maintainers: if this is cherry-picked, #28557 should go with it.

**Comment by akien-mga** [comment]
Note 2 for release maintainers: a fix for #28781 would also be needed before cherry-picking.

**Pull request merged**
