### PR TITLE
Treat `MenuBar` and `MenuButton` as advanced UI

### PR DESCRIPTION
**Pull request by AThousandShips**
These rely entirely on other advanced UI elements, namely popup menu

Follow-up to:
* https://github.com/godotengine/godot/pull/93780

### CODE REVIEW

**Comment by RedMser** [comment]
As a follow-up PR, this docs page should also be updated: https://docs.godotengine.org/en/stable/contributing/development/compiling/optimizing_for_size.html#disabling-advanced-gui-objects

**Comment by AThousandShips** [comment]
I've been planning to improve some of the descriptions there as they're already somewhat out of sync, will do as well

**Review by akien-mga — APPROVED** [review]

**Comment by AThousandShips** [comment]
Opened a doc PR to handle the new entries as well as improve some of the style there:
* https://github.com/godotengine/godot-docs/pull/9854

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
