### PR TITLE
[4.0] Complete support of callables of static methods

### PR DESCRIPTION
**Pull request by RandomShaper**
Version for 4.1 is #71644.

### CODE REVIEW

**Comment by RandomShaper** [comment]
The counterpart of this one for 4.0 is already merged. Wouldn't it make sense to merge this one, too?

**Comment by akien-mga** [comment]
You mean the one for 4.1.

I'm just unsure if this is a good change for 4.0, and if this should stay as 4.1+ only improvements. I know there are some bugfixes pending on this, but this has potential for bugs in core and seems a bit risky for 4.0 now that we're already at 4.0.2 and well into maintenance mode.

How do you assess the risk merging this and other PRs using it to stable?

**Comment by RandomShaper** [comment]
Since #71670 has been cherry-picked for 4.0, this one needs to be merged.

**Comment by RandomShaper** [comment]
> > Since #71670 has been cherry-picked for 4.0, this one needs to be merged.
> 
> I think we are going to revert the pick instead. I picked it because it seemed safe and localized, but now that it requires a fix in core as well, it's better to rollback for 4.0.x's stability sake.

I support the decision. I'll close this one.

**Pull request closed without merging**
