### PR TITLE
Expose `String::path_to`, and `String::path_to_file` to GDScript

### PR DESCRIPTION
**Pull request by Rubonnek**

### CODE REVIEW

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Sorry, misclicked.

I find it a bit confusing to have both `path_to` (for directories) and `path_to_file` (for files). Can't we just have `path_to` that would work for both?

**Comment by Rubonnek** [comment]
@akien-mga the `String` class is only meant to manipulate strings. The act of probing a block/loop device, as defined in Linux, by inspecting its filesystem to determine whether the path is a directory or a file should be considered to be out of scope for the `String` class. We should stick to a single-responsibility principle and focus on just string manipulation. Adding filesystem inspection to `String.path_to`, in order to merge both functions, is also going to make it a much slower operation, and within the context of just manipulating strings the developer should already know whether the path the string points to is a directory or a file. If a higher level abstraction is needed because the data they are handling requires so, the developer could do so by using the `Directory` or `File` classes as needed within the module they are working on.

Having said that, let's focus on the context at hand for the `String` class which is just manipulating a string. In this context your question boils down to: "Can files have the forward slash (`/`) as the last character in their name and still be considered files and not directories without probing the filesystem?". The answer is no and it's due to a POSIX file naming convention, and that's why both the `String.path_to` and `String.path_to_file` functions exist.

I personally would like to rename `String.path_to` to `String.path_to_directory` since the function name would make the intent clearer. I postponed the renaming until after this PR was merged because it was out of scope.

**Comment by akien-mga** [comment]
I'm not proposing to do filesystem handling, I'm just saying that those two functions do almost exactly the same thing (and one calls the other) and that it might be possible to unify them.

From a quick test, it might not be so trivial though I'd argue that they are inconsistent in a way that looks like a bug:

```gdscript
func _ready():
	var dir1 = "res://some/dir1"
	var dir2 = "res://some/dir2"
	var dir1s = dir1 + "/"
	var dir2s = dir2 + "/"
	var file1 = "res://some/dir1/file1"
	var file2 = "res://some/dir2/file2"

	printt(dir1, dir1s)
	print(dir1.path_to(dir1s))
	print(dir1.path_to_file(dir1s))
	
	printt(dir1, dir2)
	print(dir1.path_to(dir2))
	print(dir1.path_to_file(dir2))
	
	printt(dir1, file1)
	print(dir1.path_to(file1))
	print(dir1.path_to_file(file1))
	
	printt(dir1, file2)
	print(dir1.path_to(file2))
	print(dir1.path_to_file(file2))
	
	printt(dir1s, dir1)
	print(dir1s.path_to(dir1))
	print(dir1s.path_to_file(dir1))
	
	printt(dir1s, dir2)
	print(dir1s.path_to(dir2))
	print(dir1s.path_to_file(dir2))
	
	printt(dir1s, file1)
	print(dir1s.path_to(file1))
	print(dir1s.path_to_file(file1))

	printt(dir1s, file2)
	print(dir1s.path_to(file2))
	print(dir1s.path_to_file(file2))
```

> I personally would like to rename `String.path_to` to `String.path_to_directory` since the function name would make the intent clearer. I postponed the renaming until after this PR was merged because it was out of scope.

I don't think this is out of scope. These functions aren't exposed because they were not intended to be part of the public API for which we can't break compatibility in stable releases. So the names didn't matter much.

As soon as we expose those, the name does matter because it has to be easy to understand and use by many users.

Currently, there's almost no use of these methods in the codebase:
```
$ rg "\.path_to\("
core/string/ustring.cpp
4228:   String rel = src.path_to(dst);
[akien@cauldron godot.git (expose_path_to_master)]$ rg "\.path_to_file\("
scene/resources/resource_format_text.cpp
952:                            path = base_path.path_to_file(path);
1742:                   String path = relative_paths ? local_path.path_to_file(res->get_path()) : res->get_path();

editor/export/editor_export_preset.cpp
126:            export_path = res_path.path_to_file(export_path);

core/io/resource_format_binary.cpp
1345:                   path = local_path.path_to_file(path);
2122:           path = relative_paths ? local_path.path_to_file(path) : path;
```

Which further supports the idea that maybe they're better renamed and/or unified (e.g. `path_to(String dst, bool dst_is_folder)` if they are found to be needed in the public API.

**Comment by Rubonnek** [comment]
> These functions aren't exposed because they were not intended to be part of the public API

By public API I think you meant the scripting API, is that right? These `String.path_to*` functions are not exposed to the scripting API but are currently exposed in the public API in C++ land due to the [access specifier at line 200](https://github.com/godotengine/godot/blob/master/core/string/ustring.h#L200). This means any user-developed C++ module could have called `String::path_to` so we are going to break backwards compatibility with these modules (if any). I personally don't think the function may have been used in any user module given we are just about to enter beta, but it's hard to know.

> Which further supports the idea that maybe they're better renamed and/or unified (e.g. `path_to(String dst, bool dst_is_folder)`

I see now. I agree -- I'll modify it so we have a `String::_path_to(String dst, bool dst_is_folder)` and then two wrapper functions, `String::path_to_directory(String dst)` and  `String::path_to_file(String dst)` similar to how `String::_count` is handled.

**Comment by akien-mga** [comment]
> I see now. I agree -- I'll modify it so we have a `String::_path_to(String dst, bool dst_is_folder)` and then two wrapper functions, `String::path_to_directory(String dst)` and `String::path_to_file(String dst)` similar to how `String::_count` is handled.

My point was more that exposing two methods that do almost exactly the same thing feels a bit overkill. I think this could be a single method with a boolean flag, given how limited use it has.

**Comment by Rubonnek** [comment]
I dislike having one method with a boolean flag like that, but I agree this type of functionality has limited use within and possibly outside of the engine code as well.

On my own personal use-case, I have my own GDScript equivalent implementation of `String.path_to*` functions which I use on a custom dialogue editor to handle certain file paths and I don't use it on any performance-critical scenarios.

For that reason I see no value in committing more time to this patch and I'm closing this pull request since I have no intention to continue working on it.

@akien-mga thank you for being so thorough. I truly appreciate it.

**Pull request closed without merging**
