### PR TITLE
Replace 1024x1024 BoneMapHuman SVGs by 256x256 versions

### PR DESCRIPTION
**Pull request by coppolaemilio**
The images `BoneMapHumanBody.svg`, `BoneMapHumanFace.svg`, `BoneMapHumanLeftHand.svg`, and `BoneMapHumanRightHand.svg` were using a size of 1024 x 1024. That made the rasterization process to be much slower. This PR attempts to reduce the loading time by making the source SVGs smaller.

### CODE REVIEW

**Comment by clayjohn** [comment]
On my device (Windows 10 AMD Ryzen 5 3600) this reduces startup time in the project manager from 2.9 seconds to 2.4 seconds

**Review by akien-mga — APPROVED** [review]
Would be good to look into what makes these so slow to handle, which might still be somewhat slow now with 256x256. But there's no harm in merging this PR already as it's a major improvements and likely solves the most egregious slowdown caused by those four.

**Comment by akien-mga** [comment]
Thanks!

**Comment by TechnoPorg** [comment]
It might improve load times to only lazily load and rasterize editor icons. It probably doesn't take long individually, and they're not all needed simultaneously.

**Comment by YuriSizov** [comment]
Lazy loading would result in constant hitches as the editor theme changes would be propagated throughout the entire UI. We would need to know the exact size of each icon ahead of time, to not emit any "changed" signal when the icon is loaded, and to directly call a redraw on each node using the loaded icon. That's a lot of upkeep and many points of breakage.

**Comment by TechnoPorg** [comment]
That makes sense. Would it mitigate any of those issues if icons were rasterized only once behind the scenes before the first time they were drawn, then cached for later use? I'm not intimately familiar with the editor theme system, so I apologize if that's not possible, or I'm misinterpreting what you're saying.

**Comment by YuriSizov** [comment]
@TechnoPorg Caching of the editor theme, including storing rasterized icons is in my TODO list for 4.1. Though it may turn out that loading them all from disk is slower than regenerating, so it's not a certain fix. But it's definitely in the books.

**Pull request merged**
