### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by m6502**
Proposing fix for https://github.com/godotengine/godot/issues/41176

### CODE REVIEW

**Comment by bruvzg** [comment]
Wrong branch, this should target `3.2`.

**Comment by aaronfranke** [comment]
@m6502 Both of the PRs you opened are commits from the 3.2 branch. You need to re-base or re-create your commit on top of the master branch for it to be merged. Changes are added to the master branch first before they are backported to stable branches.

**Comment by bruvzg** [comment]
> You need to re-base or re-create your commit on top of the master branch for it to be merged. 

Nop. It's a change for `gles3` rendered, which is removed from master and is only relevant for 3.2

**Comment by aaronfranke** [comment]
Yes, you're right. The other PR should be done for master, though.

**Comment by m6502** [comment]
Oh, that's true.

**Comment by m6502** [comment]
Done.

**Comment by m6502** [comment]
@bruvzg 
> 
> > You need to re-base or re-create your commit on top of the master branch for it to be merged.
> 
> Nop. It's a change for `gles3` rendered, which is removed from master and is only relevant for 3.2

Yes, this one is meant for 3.2 only as there's no GLES3 on 4.x.




@aaronfranke 
> 
> Yes, you're right. The other PR should be done for master, though.

You are right too. As I was working with the 3.2 branch I missed that, sorry :-) I created the master branch pull request too.

**Comment by m6502** [comment]
Closing the pull request before creating a new one more in line with the guidelines :-)

**Pull request closed without merging**
