### PR TITLE
Allow project export to be canceled

### LINKED ISSUE #20551: Ability to cancel during project export
Hi. I would like to ask for a new feature. Like the name suggests, cancel during export. Maybe could be secondary, but if done, could save lot of time if accidentally changed mind during project export. Especially on huge projects which take lot of time to export.!

### PR DESCRIPTION
**Pull request by vnen**
Fix #20551

### CODE REVIEW

**Comment by akien-mga** [comment]
Needs a rebase, otherwise looks good to me.

**Comment by mhilbrunner** [comment]
Rebase, pretty please? :)

**Comment by vnen** [comment]
Rebased.

**Comment by mhilbrunner** [comment]
Thank you!

**Pull request merged**
