### PR TITLE
Document that transparent StyleBoxes/textures should be used for UI focus

### PR DESCRIPTION
**Pull request by Calinou**
See https://github.com/godotengine/godot/issues/55146#issuecomment-974675212. The description is fairly lengthy and had to be copy-pasted around, but at least it's exhaustive :slightly_smiling_face:

### CODE REVIEW

**Comment by pycbouh** [comment]
Have you checked how it looks in the built-in help? We show it inline, and that might be too much for such formatting 😬

**Comment by kleonc** [comment]
> We show it inline, and that might be too much for such formatting

If that's the case then maybe the info added in this PR could be added as a note in a separate line/block (e.g. like in [`Node.name`'s description](https://docs.godotengine.org/en/3.4/classes/class_node.html#class-node-property-name)). Many properties have such descriptions and I think they are more readable than if they would be shown in a one big block of text (and it looks fine e.g. in the tooltips).

**Comment by mhilbrunner** [comment]
This needs to be rebased.

**Comment by pycbouh** [comment]
> Have you checked how it looks in the built-in help? We show it inline, and that might be too much for such formatting 😬

btw my concern here is no longer valid, theme item descriptions have been moved to a new line. So should be good.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
