### PR TITLE
Add GCC problem matcher to CI

### PR DESCRIPTION
**Pull request by raulsntos**
Adds the GCC problem matcher action to CI so errors in C++ show inline in the `Files changed` tab of a PR.

gcc-problem-matcher

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Awesome!

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Cherry-picked for 3.6

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2

**Pull request merged**
