### PR TITLE
GUI: Touch screen button click area now is synced with its draw

### LINKED ISSUE #38472: Touchscreen buttons shapes are not centered respect to the texture
**Godot version:** 3.2.1

**OS/device including version:** Windows 10

**Issue description:** Touchscreen buttons shapes are not centered respect to their texture even if the option "Shape centered" is checked. It seems that the shape is shifted on the right bottom side of the texture.

**Steps to reproduce:** 

- Add a touchscreen button node to the scene
- Add "normal" and "pressed" textures to it
- Check the option "Shape centered"
- Add a circle shape with a radius that makes the shape bigger then the texture
- Run the scene and tap/click on the extreme left side of the texture

**Minimal reproduction project:**
[TouchButtonsTest.zip](https://github.com/godotengine/godot/files/4578537/TouchButtonsTest.zip)

### PR DESCRIPTION
**Pull request by kuruk-mm**
Fix #38472

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by kuruk-mm** [comment]
@akien-mga I don't understand why #38472 wasn't closed, i think i put correct keyword with 'fix'

**Comment by akien-mga** [comment]
Because you tricked me and made the PR against the `3.2` branch instead of `master`... So the bug is not fixed in `master`, and thus GitHub doesn't close the issue.

I'll cherry-pick it forward manually, but please make future PRs against `master`.

**Comment by kuruk-mm** [comment]
> Because you tricked me ;) and made the PR against the `3.2` branch instead of `master`... So the bug is not fixed in `master`, and thus GitHub doesn't close the issue.
> 
> I'll cherry-pick it forward manually, but please make future PRs against `master`.

Oh sorry, I didn't know that.
I thought when the bug is from 3.2 you need to put merge on that branch. So now I know that.
Please let me know if you want me to make another PR for master.

**Pull request merged**
