### PR TITLE
Add ConfigFile::parse()

### PR DESCRIPTION
**Pull request by RandomShaper**
**This code is generously donated by IMVU.**

### CODE REVIEW

**Comment by Calinou** [comment]
The class reference should be updated with a description of the method.

**Comment by RandomShaper** [comment]
> The class reference should be updated with a description of the newly added method.

Good point. Done.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Pull request merged**
