### PR TITLE
The ability to move nodes inside a viewport.

### PR DESCRIPTION
**Pull request by 0nepixel**
I don't know why but you can't move the child nodes of a viewport (2D) in the editor, you have to take the node out and change the position, then put it back in the viewport, it's anoying and impractical :/.

### CODE REVIEW

**Comment by akien-mga** [comment]
I guess you wanted to open an issue and not a pull request to pull all of the 3.0 branch into the master branch again?

**Comment by 0nepixel** [comment]
well i don't know if this is an issue, i see this "bug" since Godot 1.xx

**Comment by akien-mga** [comment]
Well, it's definitely not a pull request ;)

**Comment by 0nepixel** [comment]
;) k

**Comment by reduz** [comment]
Just make another scene I guess.. node may not even be visible.

**Comment by girng** [comment]
why does this have 2.3k files changed? if possible, would need a review to cut down a bit of stuff, surely this feature isn't that extensive. however, not sure if reduz and other contributors have enough time

**Pull request closed without merging**
