### PR TITLE
Fix for not picking up locale of some .po translation files

### PR DESCRIPTION
**Pull request by supagu**
See issue #19076

This adds improves the language detection when reading po files

### CODE REVIEW

**Comment by supagu** [comment]
these travis errors seem very unrelated to this change.

**Comment by akien-mga** [comment]
I didn't even know we had support for PO files for translations already... And we got several GSoC proposals for it this year :P
So #9398 is done already?

**Comment by akien-mga** [comment]
@hpvb Should be cherry-picked in 3.0.6 if possible.

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
