### PR TITLE
Expose connection hot zones in `GraphNode`

### PR DESCRIPTION
**Pull request by mechPenSketch**
In my [previous PR](https://github.com/godotengine/godot/pull/51271), I messed up trying to revert an accidental merge resulting in reviewing request in much more unrelated areas.

Hopeful, this gets added to the upcoming version.

Also, in hindsight, I probably should have squashed my commits early rather than until I've finalized all my changes.

### CODE REVIEW

**Comment by fire** [comment]
Do you have a small test project that uses this? Trying to see if there are existing samples for verifying the code works.

**Comment by mechPenSketch** [comment]
^ Well, I have an FSM asset to try on, but its other features might be too distracting.

Attached below is a much simpler project to test on: 
[graphedit_hotzones.zip](https://github.com/godotengine/godot/files/7012972/graphedit_hotzones.zip)

**Comment by fire** [comment]
I tried running your https://github.com/godotengine/godot/files/7013985/graphedit_hotzones.zip and it errors with get_offset.

**Comment by mechPenSketch** [comment]
^ Ah my bad get_offset is called from a child of GraphNode, not the GraphNode itself.

**Comment by mechPenSketch** [comment]
Here is an update of the test:
[graphedit_hotzones.zip](https://github.com/godotengine/godot/files/7019663/graphedit_hotzones.zip)

This time, it accounts for slot index of a GraphNode. I have also added an _input() print statements to assure that mouse position is indeed in the hot zone.

**Comment by fire** [comment]
There are some conflicts that stop this from being merged.

**Comment by mechPenSketch** [comment]
Umm....why didn't I have to option to create new branch?

**Comment by pycbouh** [comment]
Superseded by https://github.com/godotengine/godot/pull/52015.

**Pull request closed without merging**
