### PR TITLE
Improve Mac/UNIX conformance/reliability

### PR DESCRIPTION
**Pull request by RandomShaper**
### Commit 1:  _Make `OS::delay_usec()` more reliable on UNIX_

Implemented with `nanosleep()`. `usleep()` is deprecated.
Also loops to ensure that __at least__ the requested time is waited, accounting for spurious interruptions.

May help in situations like reattempting to connect to the debugger.

### Commit 2 __(UPDATED)__:  _Implement custom thread numbering for POSIX_

For every UNIX-derived (Android, Linux, macOS, iOS) flavor, a global counter is atomically incremented on thread start. That id is kept as thread-local storage.

Therefore, thread ids are sequential numbers, trivially comparable. This improves the previous state of things, in which `pthread_t` were casted to `Thread::ID` and unportabily compared. Also big, ugly thread ids appeared.

### CODE REVIEW

**Comment by hpvb** [comment]
Looks good to me, nice improvement.

**Comment by RandomShaper** [comment]
Hmm... It seems all the affected platforms but Android fail to build. I'll check it.

**Comment by bruvzg** [comment]
@RandomShaper
> On general POSIX, `pthread_getthreadid_np()`.

`_np` means non-portable.

`pthread_getthreadid_np();` is BSD specific.
macOS have `pthread_threadid_np(pthread_t thread, uint64_t *thread_id);`.

**Comment by RandomShaper** [comment]
@bruvzg, thanks! I hope I'll fix MacOS and iOS with that.

**Comment by RandomShaper** [comment]
I've reworked the thread id thing in a portable way. Let's see if Travis approves.

**Comment by RandomShaper** [comment]
@akien-mga, this is relevant for 2.1. Do you plan on cherry-picking it?

**Comment by akien-mga** [comment]
Why not, but not right now. I'll likely have to do a 2.1.4.1 release to fix a regression in libpng, and I'd prefer to avoid adding potential sources of issues just before it.

**Pull request merged**
