### PR TITLE
Update libogg to upstream c8fca6b

### PR DESCRIPTION
**Pull request by jmannanc**
Changelog:
* Faster slice-by-8 CRC32 implementation.
  see https://lwn.net/Articles/453931/ for motivation.
* Add CMake build.
* Deprecate Visual Studio project files in favor of CMake.
* configure --disable-crc option for fuzzing.
* Various build fixes.
* Documentation and example code fixes.

### CODE REVIEW

**Comment by volzhs** [comment]
error while building macOS editor.

https://travis-ci.org/godotengine/godot/jobs/605248836#L953-L961
```
thirdparty/libogg/ogg/os_types.h:75:12: error: unknown type name 'uint16_t'
   typedef uint16_t ogg_uint16_t;
           ^
thirdparty/libogg/ogg/os_types.h:77:12: error: unknown type name 'uint32_t'
   typedef uint32_t ogg_uint32_t;
           ^
thirdparty/libogg/ogg/os_types.h:79:12: error: unknown type name 'uint64_t'
   typedef uint64_t ogg_uint64_t;
           ^
```

**Comment by SneakyFish5** [comment]
Sorry I'm not familiar with macOS, I compiled on my computer (Linux), but if you have any tips to fix this I'd be happy to add it

**Comment by SneakyFish5** [comment]
Actually it seems like this was fixed upstream in https://github.com/xiph/ogg/commit/c8fca6b4a02d695b1ceea39b330d4406001c03ed. Should I update libogg to a specific git commit rather than a version to include this fix?

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2. (Together with #33227.)

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7. (Together with #33227.)

**Pull request merged**
