### PR TITLE
Remove unexpected GDScript aliases for built-in types

### PR DESCRIPTION
**Pull request by leonkrause**
These aliases are undocumented and rather unexpected.
Left in `Rect3` as alias for `AABB` since it is pretty sensible and uses capitalization.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good to me!

**Comment by romulox-x** [comment]
Personally, I like the vec2, mat3, etc style.  If I'd know they were allowed, I'd have been using them. But I understand if the concensus is that they should be removed, since they don't really fit with the style of everything else.

**Comment by bojidar-bg** [comment]
:+1: As they might/will lead to bad code and multiple best coding practices.

@romulox-x ~ BTW, you can still have them after the merge if you add
````coffee
const vec2 = Vector2
#....
````
at the top of each file you plan to use it in.

**Comment by akien-mga** [comment]
I also think they should be removed as they don't fit the style of the other variables, and since nobody knew about them, I think everyone is now used to Vector2, Vector3, Matrix32, etc.

**Comment by akien-mga** [comment]
@reduz @punto- Any objection to removing those aliases that apparently nobody knew about?

**Pull request merged**
