### PR TITLE
Remapped ACTIVE to shader_active, now works

### LINKED ISSUE #18985: Hide particles as output of particle shader
I couldn't find a way to do this, I might have missed it as I only wrote my first particle shader yesterday :)

I'd like an output in the particle shader simply called "VISIBLE". I want to be able to (temporarily) hide a particle without it loosing its positioning.

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Mostly resolves #18985 but the fix as is, is solid :)

It now compiles a particle shader that uses "ACTIVE" correctly.
What doesn't work is that setting ACTIVE to false is ignored the first frame the particle is emitted. That might just be a limitation, don't know.

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this change also needed in GLES2?

**Comment by clayjohn** [comment]
@akien-mga  Yes.

**Comment by akien-mga** [comment]
Ping @BastiaanOlij, should be added to GLES2 too.

**Comment by BastiaanOlij** [comment]
That surprised me, I didn't think GPU particles worked in GLES2, might just be code copied from GLES3 but otherwise defunct.

But changed it anyway:)

**Comment by clayjohn** [comment]
Maybe all if the defines should be removed? Your right, it is kinda odd to have them if there is no hopes of having a particle shader. I guess thats an issue for another day...

**Comment by BastiaanOlij** [comment]
The only reason for keeping them I can imagine is to make sure things don't fall apart when you create a GLES3 game that can fall back on GLES2. I'm not sure how Godot reacts when switched to the GLES2 mode and it encounters shaders it won't end up using but are there for when the game is run with GLES3.

**Comment by clayjohn** [comment]
That makes sense. If that is the reason then it doesn't make any sense to update the gles2 variable name! But its no harm I guess.

**Comment by BastiaanOlij** [comment]
I'm just theorizing here, no idea if there is a point to keeping it :)

**Pull request merged**
