### PR TITLE
Skeleton animates physical bones

### LINKED ISSUE #24359: Collision shapes attached to physical bones don't transform with their bones when animated
**Godot version:**
3.1 Alpha 3 and Alpha 2

**OS/device including version:**
Win 7 x64

**Issue description:**
If the skeleton the bones are tied to is animated the bones will transform, but the shapes do not move from their original position.

**Minimal reproduction project:**
[Here is a test scene with an animated hand model I made.](https://www.dropbox.com/s/xoss7quvlilbr7e/hand%20ok.tscn?dl=0) All you have to do is generate a set of physical bones from the skeleton, set the scene as the root scene, and hit F5. It's already set up to loop the animation.

### LINKED ISSUE #24836: "Create physical bones" yields incorrect collision shapes for bones
**Godot version:**
3.1-alpha5

**OS/device including version:**
Arch Linux rolling + Intel & NVIDIA

**Issue description:**
"Create physical bones" creates all bones with wrong rotation & translation. Scale seems to be correct.

**Steps to reproduce:**
1. Import the provided model
2. Use "Create physical bones" command for skeleton.

**Actual result:**
Screenshot 1
Screenshot 2

**Minimal reproduction project:**
[issue-demo.zip](https://github.com/godotengine/godot/files/2736396/issue-demo.zip)

### LINKED ISSUE #26060: Physical bone joint bug
**Godot version:**
3.1.beta.custom_build. 1174d10e3c8f84e15dd6c5e795b5a6679c64c59c

**OS/device including version:**
Ubuntu 16.04

**Issue description:**
https://godotengine.org/article/godot-ragdoll-system

click bone joint doesn’t work :(

Error ===>
```
modules/bullet/rigid_body_bullet.cpp:463 - A body with a joints is destroyed. Please check the implementation in order to destroy the joint before the body.

scene/3d/skeleton.cpp:627 - Condition ' bones[p_bone].physical_bone ' is true.
core/image.cpp:961 - Condition ' p_width <= 0 ' is true.

modules/bullet/bullet_physics_server.cpp:1224 - Condition ' body_A == body_B ' is true. returned: RID()
modules/bullet/bullet_physics_server.cpp:1234 - Condition ' !joint ' is true.

modules/bullet/bullet_physics_server.cpp:1292 - Condition ' body_A == body_B ' is true. returned: RID()
modules/bullet/bullet_physics_server.cpp:1338 - Condition ' !joint ' is true.
modules/bullet/bullet_physics_server.cpp:1322 - Condition ' !joint ' is true.
modules/bullet/bullet_physics_server.cpp:1460 - Condition ' !joint ' is true.

modules/bullet/bullet_physics_server.cpp:1364 - Condition ' body_A == body_B ' is true. returned: RID()
modules/bullet/bullet_physics_server.cpp:1444 - Condition ' !joint ' is true.

modules/bullet/bullet_physics_server.cpp:1374 - Condition ' !joint ' is true
./core/rid.h:153 - Condition ' !p_rid.is_valid() ' is true. returned: __null
```

**Steps to reproduce:**

joint_type Hingejoint (radius curves bad) ===>

**Minimal reproduction project:**
https://drive.google.com/file/d/12RED80XoMKyM5b1woTieZGW9irYXuNKs (35mb)

### PR DESCRIPTION
**Pull request by AndreaCatania**
Added feature to move physical bones with skeleton when not simulating physics.

So now we have the possibility to:
- Don't simulate physics and don't animate the physical bones
- Don't simulate physics and animate the physical bones
- Simulates the physics

Fixes #24359
Fixes: #26060
Fixes: #24836

ezgif com-video-to-gif(13)

### CODE REVIEW

**Comment by AndreaCatania** [comment]
I've added another commit to fix the Physical Skeleton generation:

Screenshot from 2020-02-09 09-43-38

Fixes: #26060
Fixes: #24836

**Comment by akien-mga** [comment]
Thanks!

**Comment by NHodgesVFX** [comment]
@akien-mga can this be added to 3.2.2 its really tedious to setup a rag doll when all the bones have a incorrect alignment.

**Comment by akien-mga** [comment]
The removal of `is_static_body()` breaks compatibility, and I haven't taken time to think about how to handle this gracefully in the 3.2 branch.

**Comment by jedStevens** [comment]
I did my own cherry pick of this PR, and I'm having some odd issues with it. It seems to only animate using the `AnimationPlayer` because when I use an `AnimationTree`, my character's `PhysicalBones` become frozen on a frame from the `AnimatoinPlayer`.

I wrote a small gdscript file to help fix this issue and I noticed that when not using the new `animate_skeleton` property, the collisions do not occur, however I can give them correct alignment to the skeleton by changing the `process_priority` of the `AnimationTree` to `-1` and the `PhysicalBone`s to `1`. I haven't messed around with the process priority so much so I'm not sure if this is actually what made it work because I was just looking to make this code as safe as possible. I'm also not too sure if doing this incorrectly would result in collisions a frame behind the animation, but I didn't want to risk it.

@NHodgesVFX I found this easy to fix by writing a custom importer for characters, where you could write a script generating the exact ragdoll (and other features) you require. This was probably one of the biggest time saves for me.

**Comment by S-h-0-X** [comment]
Just a quick question, did this change made it through for 3.2.2 beta?. I'm mentioning it because I just downloaded it and I'm still having issues with the bones having an incorrect rotation

**Comment by NHodgesVFX** [comment]
> Just a quick question, did this changes made it through for 3.2.2 beta?. I'm mentioning it because I just downloaded it and I'm still having issues with the bones having an incorrect rotation

I also had issues, so I created a new issue https://github.com/godotengine/godot/issues/38183

**Comment by AndreaCatania** [comment]
@jedStevens Do you have an open issue for that? I could look into if you upload a a sample project. I would prefer a Godot 4 project (if you can).

**Comment by S-h-0-X** [comment]
So I did try Godot 3.2.1 and all the betas available for 3.2.2, and this feature (body physics) looks completely broken to me. Not only with my simple model, I downloaded like 4 different gltf models and 1 fbx model and always it puts the capsules incorrectly (orientation wise). If I try to rotate and move them into place, when I enable simulation from the skeleton script the model just explodes and starts to do crazy stuff, (most of the time looks like is catapulted few meters away from original position). So really I don't know if I'm doing something terribly wrong or what. If I can collaborate in any way to fix this please let me know.

**Comment by AndreaCatania** [comment]
Please open a new issue and upload a sample project, I'll be happy to give it a check.

**Comment by S-h-0-X** [comment]
Hello,
@AndreaCatania , here you have it:
https://github.com/godotengine/godot/issues/39054

Thank you very much. If I can do anything else please let me know.

**Comment by Zireael07** [comment]
Is this in 3.2 or not? I can't find an animate_physical_bone property on Skeleton?

**Comment by chipmu** [comment]
I patched this to 3.3RC8 and run a few tests, it's working great in the editor, but when play the scene the physical bones stop following the bones' animation.

**Comment by tavurth** [comment]
Was this ever cherry picked back to 3.x @akien-mga?

**Comment by Calinou** [comment]
> Was this ever cherry picked back to 3.x @akien-mga?

No, see the above comments. This PR still has a `cherrypick:3.x` label since it hasn't been cherry-picked yet.

**Comment by tavurth** [comment]
@Calinou there are a bunch of issues relating to this in different aspects. 

Since this was two years ago, I guess it has been lost in the shuffle.

**Comment by akien-mga** [comment]
Last I tried it was not easy to cherry-pick and would require a dedicated backport.

**Comment by tavurth** [comment]
Ok if I get some free time over the next weeks I will try to look into it, seems there are some other PRs already made but they may be incomplete.

**Pull request merged**
