### PR TITLE
C#: Fix dictionary keys in Colors

### PR DESCRIPTION
**Pull request by paulloz**
Some colours were broken during #64817.

### CODE REVIEW

**Comment by raulsntos** [comment]
Thanks, I missed that they were renamed. For the reference, they were renamed in https://github.com/godotengine/godot/pull/45144.

**Comment by raulsntos** [comment]
Thanks! I missed that they were named differently in C# than in GDScript.

**Comment by raulsntos** [comment]
Actually, even though the names are consistent with the names in core, the dictionary should not use underscore (`_`) in its keys because we remove it in the `Color.Named` method.

https://github.com/godotengine/godot/blob/390333e822c95081cfbd837699c8c63370b388dc/modules/mono/glue/GodotSharp/GodotSharp/Core/Color.cs#L709-L724

**Comment by paulloz** [comment]
I missed that 😓  
Shouldn't we not remove the `_` for the look-up, though? In order to be able to match the constants in the documentation.

**Comment by raulsntos** [comment]
I guess it's done so that you can get the color whether you spell it `ALICEBLUE` or `ALICE_BLUE`. I'm not sure why that flexibility is needed but that's also how the `find_named_color` method works in GDScript.

**Comment by paulloz** [comment]
I'll just remove all `_` from the keys and accessors then.

**Comment by raulsntos** [comment]
> Shouldn't we not remove the `_` for the look-up, though? In order to be able to match the constants in the documentation.

I would agree if the dictionary was exposed it should use the same naming as the constants in the documentation for the keys, but it's internal.

**Review by raulsntos — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
