### PR TITLE
Add dependency detection improvements to the render graph.

### PR DESCRIPTION
**Pull request by DarioSamo**
### Improvements

* Buffers changing their usage are no longer treated as write usage unless the API requires it. This was originally introduced because textures changing their usage usually implies a layout change, but that is not true for buffers depending on how the API treats them.
  * D3D12 usually requires state transitions, but that is not true if enhanced barriers are used instead.
* Draw lists are not treated as being dependent on each other if their regions do not intersect despite both being write commands.
* `CopyEffects::copy_cubemap_to_dp` was edited to use the viewport and scissor instead of embedding the screen rectangle into the push constant. This allows the render graph to detect whether draw lists overlap or not.

### Results

On the reference scene, [TPS demo from here](https://github.com/godotengine/godot/pull/90284), the render graph goes down from 22 levels to 17 levels, thanks to the shadow passes on cubemaps for omni lights being merged together to be able to draw to all six faces without having to insert a synchronization barrier. Future improvements might be possible by changing the rendering code further.

On my Mali-G78 I've measured a consistent reduction of ~31 ms down to ~30 ms in GPU time (proper profiling is pending until I acquire hardware that is capable of working with the Mali profiler). I've been unable to spot any significant difference on the RTX 3090 Ti on desktop.

image

I haven't seen any errors introduced by this change and tested with the validation layer to make sure of that. That said, testing is appreciated.

---

Contributed by [W4 Games](https://w4games.com/). 🍀

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by Repiteo** [comment]
Thanks!

**Comment by EnlightenedOne** [comment]
Finally traced shadow corruption back to this one. Does not play well either with subviewports and possibly transparency:
image

I will raise a defect for it (issue is only visible when the game is running in the editor the shadows draw correctly).

Before, shadows correctly drawn above and below transparent shapes:
image

After:
badShadowExample

Note that there is no shadow above the transparent water surface and that the orientation of the camera has an impact on what shadow detail is visible below it. If the camera goes below the water the shadow is rendered, if I hide the surface the shadow is drawn (worth noting the water is a mirror with a subviewport and I suspect that is the driver for the trouble.

**Comment by DarioSamo** [comment]
@EnlightenedOne can you point me to the specific demo project and revision you're using?

I'm not against reverting the commit temporarily if it's causing an actual behavior difference on the reordering. It's definitely not intended to do that, but I imagine there's something else that has failed to be detected here as a dependency.

**Comment by EnlightenedOne** [comment]
@DarioSamo you may be right I spent a brief period trying to cook up an MRP, I did throw up transparency and a SubViewport in a new scene without an issue.

Broadening the scope of my MRP checking shader type, shader logic, texture passing approach and nested scenes to see which elements are required to replicate this. Once I have something I will share it, no sense considering a reversion without a handle on the root cause is my view.

**Comment by EnlightenedOne** [comment]
With the MRP just reverting this commit does resolve the issue, it also works on my own branch for the more complex scene. I hope that the optimisation can be salvaged by a change in scope but I am unable to dig into it in depth at this time.

**Pull request merged**
