### PR TITLE
GDNative: Use VariantWriter for the API JSON generator

### PR DESCRIPTION
**Pull request by vnen**
Instead of the String representation, which can be finicky to work with.
VariantWriter is more robust since changes to it affects the whole
system thus it's changed less often and it's never ambiguous.

This will break the existing bindings that depend on this, but it'll be easier to parse in general (and the String representation changed anyway, so it's broken even before this change).

### CODE REVIEW

**Review by BastiaanOlij — APPROVED** [review]
This seems to produce a `api.json` that generates proper header files in GDnative subject to a few small changes in `binding_generator.py`.

**Comment by vnen** [comment]
Added a fix for a binding in VisualScriptFunctionState since the function takes an Array but default value was a Variant (which gets interpreted as `null`).

**Comment by Xrayez** [comment]
See #33241.

The linked PR is not a [local solution](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local) of course, but it would work correctly everywhere it's used. 😛

**Comment by vnen** [comment]
> See #33241.
> 
> The linked PR is not a [local solution](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local) of course, but it would work correctly everywhere it's used.

Well, this does not use the JSON class, it writes a hand-made JSON string instead, so that PR wouldn't solve this in any case. That one needs a different discussion.

**Comment by Xrayez** [comment]
> Well, this does not use the JSON class, it writes a hand-made JSON string instead, so that PR wouldn't solve this in any case. That one needs a different discussion.

Sure, what I mean is that we (probably) wouldn't need to write a hand-made JSON in the first place. It would be wrong not to mention this at least.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
