### PR TITLE
Fix multiplayer replication crash in on_sync_receive.

### PR DESCRIPTION
**Pull request by baptr**
When handling sync data for a node that's been removed (like as the last update from a MultiplayerSynchronizer under a despawned child of a
MultiplayerSpawner), this would previously fail to consume bytes from the message - leaving on_sync_receive in a bad state. On the next loop,
it could read data interior to the update as a large size, and wrap the offset to a negative value, leading to a segfault.

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

**Comment by baptr** [comment]
> Could you squash the commits? See [PR workflow](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for instructions.

Done

**Comment by Faless** [comment]
@baptr the fix looks good, but the current code should not crash the engine.
If you experienced a crash there must be another error that this fix alone does not solve.

> It could read data interior to the update as a large size, and wrap the offset to a negative value, leading to a segfault.

I'll do some tests, because if that's the case, it seems possible to send a packet that crashes the engine even with this fix.

**Comment by baptr** [comment]
I was thinking about trying to add a unit test to exercise this particular failure. I haven't gotten around to it (but would be willing to try), but I think a valid sync packet referencing an invalid node, with `packet_buf[3+4+4+4+4] = uint32(-16)`, for example, would be a fun test.

I probably have the offsets off a little, but from my understanding of the code, that would previously have sat in an infinite loop.

**Comment by Faless** [comment]
I think the segfault issue is due to the size check being done too late:

```diff
diff --git a/modules/multiplayer/scene_replication_interface.cpp b/modules/multiplayer/scene_replication_interface.cpp
index 3466cb10df..efbf6f038c 100644
--- a/modules/multiplayer/scene_replication_interface.cpp
+++ b/modules/multiplayer/scene_replication_interface.cpp
@@ -749,6 +749,7 @@ Error SceneReplicationInterface::on_sync_receive(int p_from, const uint8_t *p_bu
 			const ObjectID &sid = peers_info[p_from].recv_sync_ids[net_id];
 			sync = get_id_as<MultiplayerSynchronizer>(sid);
 		}
+		ERR_FAIL_COND_V(size > uint32_t(p_buffer_len - ofs), ERR_INVALID_DATA);
 		if (!sync) {
 			// Not received yet.
 			ofs += size;
@@ -763,7 +764,6 @@ Error SceneReplicationInterface::on_sync_receive(int p_from, const uint8_t *p_bu
 			ofs += size;
 			continue;
 		}
-		ERR_FAIL_COND_V(size > uint32_t(p_buffer_len - ofs), ERR_BUG);
 		const List<NodePath> props = sync->get_replication_config()->get_sync_properties();
 		Vector<Variant> vars;
 		vars.resize(props.size());
```

> I probably have the offsets off a little, but from my understanding of the code, that would previously have sat in an infinite loop.

Yeah, I think the main issue with the segfault was:
```
 		if (!sync) {
 			// Not received yet.
			ofs += size;
			continue;
		}
```

Which, if done before checking that `size <= uint32_t(p_buffer_len - ofs)` would result in `ofs` becoming negative `if size is > 2^31` and segfault in the next loop. (and as you mention, when `size == -8` i.e. `size == 2^31 + 8` it could result in an endless loop).

**Comment by baptr** [comment]
I put the size check up closer to the decode, but yeah, that's a more complete fix.

Any opinion on whether the missing sync root node case should be an ERROR (vs a silent continue)?

**Comment by baptr** [comment]
Cleaned up the commit message a bit

**Comment by Faless** [comment]
> Any opinion on whether the missing sync root node case should be an ERROR (vs a silent continue)?

That should stay silent for now, since it's possible that the "spawn packet" arrives after the first "sync" (sync is unreliable, unordered, spawn is reliable, ordered).

So, under some network stress I expect for the first "sync" to often arrive before "spawn", and we don't want to spam errors in that case.

**Review by Faless — APPROVED** [review]
LGTM :+1: , great job spotting this :1st_place_medal:

**Comment by baptr** [comment]
> > Any opinion on whether the missing sync root node case should be an ERROR (vs a silent continue)?
> EDIT: Sorry, I misread, the case **sync exists but has no root node** should stay as an ERROR like it is now, since that case is always a coding error, or a malicious packet as far as I can tell.

Sounds good. I'll dig a bit more at how exactly I got in that state. Not sure yet if it's a project bug or another engine bug. But glad to have this one sorted!

Thanks for the guidance and review!

**Comment by Faless** [comment]
Thank you!
And congratulation on your first Godot contribution!

**Pull request merged**
