### PR TITLE
Fixed TabContainer/Tabs constants not working

### LINKED ISSUE #31851: TabContainer ignores top_margin constant
**Godot version:** 979e772

**Issue description:** After briefing through the source code for [`TabContainer`](https://github.com/godotengine/godot/blob/master/scene/gui/tab_container.cpp) I noticed that the `top_margin` is never taken into account. While in the editor I also noticed that the changing the custom constant didn't have any influence on the positioning. 

image
_The selected property_

### PR DESCRIPTION
**Pull request by pixaline**
The TabContainer/Tabs constants seemed to never have been properly reimplemented, so this PR fixes that and adds documentation. I made Hseparation change the tab spacing (as the original tooltip described) and made another constant, label_margin, change the spacing between label, icon and close button. The label_valign constants now work as well.

Fixes #31851

### CODE REVIEW

**Comment by pycbouh** [comment]
You need to make a PR against the `master` branch. And as this change breaks compatibility it is unlikely to be ported to `3.x`.

**Comment by parulina** [comment]
Sorry, how exactly does this break compatability?

**Comment by pycbouh** [comment]
> I made Hseparation change the tab spacing (as the original tooltip described) and made another constant, label_margin, change the spacing between label, icon and close button. 

That's how. 🙂 You've replaced an existing constant with another, which means existing themes won't work as before if this PR is merged. And you still need to make a PR against the `master` branch, regardless of this breaking compatibility.

**Comment by parulina** [comment]
Ah alright, I thought the original tooltip would take priority for its actual function. I see that the master branch has dropped these constants, so I'm not sure what there even is to fix there... What should I do? I can modify this to just fix the non working constants, if it could get in to 3.x, since I plan to keep using it as well as these fixed constants.

**Comment by pycbouh** [comment]
`hseparation` is definitely in use in Tabs on master. As for limiting compat breakage, you can keep existing constants in their place and introduce new ones for the missing features, like, for example, `tab_separation`. And I guess the docs for the existing constants need to be fixed.

**Comment by pycbouh** [comment]
@parulina What's your current plan with this PR? Will you follow my last suggestion?

Also, you seem to have rebased your PR on something else and so a bunch of extra commits were added to it. It's been like this for a week, so... do you plan to address this? 🙃

**Comment by parulina** [comment]
@pycbouh Oh, my bad, I didn't realize this PR was still open. I'd prefer to cancel and close this. Thanks.

**Pull request closed without merging**
