### PR TITLE
[3.x] [macOS] Backport notarytool, provisioning profile and PKG export options.

### PR DESCRIPTION
**Pull request by bruvzg**
Back-port of https://github.com/godotengine/godot/pull/69638 and parts of https://github.com/godotengine/godot/pull/74644

Fixes https://github.com/godotengine/godot/issues/80213

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Had a go at cherry-picking this for `3.5`, it's not trivial, because it depends on other PRs which haven't been cherry-picked: 
- #63110
- #66093

And possibly more which further improved upon that refactoring.

So this seems a bit risky to attempt for 3.5. If we want to provide notarytool for notarization in 3.5.3, this should likely be done specifically for `3.5` with the minimal amount of changes. Or we can just disable notarization by default in 3.5.3 and let users do it after the export manually.

**Comment by sszigeti** [comment]
Just got an email from Apple. I'm quoting the relevant part:

> Notarizing software with altool was deprecated in Xcode 13, and the Apple **notary service will no longer accept uploads from altool as of November 1, 2023**.

Is it possible to get instructions for disabling notarization and doing it manually?

**Comment by akien-mga** [comment]
> Just got an email from Apple. I'm quoting the relevant part:
> 
> > Notarizing software with altool was deprecated in Xcode 13, and the Apple **notary service will no longer accept uploads from altool as of November 1, 2023**.
> 
> Is it possible to get instructions for disabling notarization and doing it manually?

In the export preset configuration, set `notarization/enable` to false. It's actually the default value in 3.5.x.

**Pull request merged**
