### PR TITLE
[Project Manager] Simplify title bar logo.

### PR DESCRIPTION
**Pull request by bruvzg**
Removes inverted face part of the title bar logo:
- It's ugly and distracting (too much contrast).
- It's taking too much space.
- It's inconsistent with other Godot logos style.
- It's duplicating the native title bar icon on Windows (and probably many Linux DEs).

Screenshot 2024-03-28 at 00 07 57
Screenshot 2024-03-28 at 00 08 52

Related proposal https://github.com/godotengine/godot-proposals/issues/9065

### CODE REVIEW

**Review by MewPurPur — APPROVED** [review]

**Review by Geometror — APPROVED** [review]
To me, this looks much cleaner :)

**Comment by groud** [comment]
hmm. While I believe this is step in the right direction, we've never used the logo's text alone before. It looks very out of place to me. 

I'd rather keep the logo and use the usual blue version instead, or completely remove the logo. But  I'd prefer to avoid replacing an inconsistency in our branding by another inconsistency.

**Comment by bruvzg** [comment]
> I'd rather keep the logo and use the usual blue version instead, or completely remove the logo.

- The blue logo is too detailed and will look blurry at this scale.
- Removing the logo will leave an asymmetric hole in the UI, also logo acts as "About" button (so in this case will need to re-add it in some other place).

**Comment by MewPurPur** [comment]
By the way, I toned down the `#fff` color to `#e0e0e0` (standard icon color) in https://github.com/godotengine/godot/pull/89711, so this already has less contrast than it does in the latest dev build.

**Comment by bruvzg** [comment]
> or completely remove the logo

Or maybe we should replace it with something more neutral, like help menu:

https://github.com/godotengine/godot/assets/7645683/ffb84143-c553-4eab-8c24-cd73bb68ac13

**Comment by groud** [comment]
> The blue logo is too detailed and will look blurry at this scale.

I am not sure it would TBH, it just needs the SVG correctly rendered to that scale I believe. At least it seems to work well enough in the windows taskbar.

**Comment by timothyqiu** [comment]
> or completely remove the logo

Clicking the version on the bottom right can summon the about dialog instead of simply coping the version text.

**Comment by bruvzg** [comment]
> I am not sure it would TBH, it just needs the SVG correctly rendered to that scale I believe.

Tested it, and at least on the high DPI screen it seems to be better than I expected (will check on a low DPI later), so it might be an option.

Screenshot 2024-03-29 at 22 58 59

**Comment by bruvzg** [comment]
> Tested it, and at least on the high DPI screen it seems to be better than I expected (will check on a low DPI later), so it might be an option.

Played a bit with a logo alignment and scale, and it seems to be more or less OK (at least less ugly) - https://github.com/godotengine/godot/pull/90080

**Pull request closed without merging**
