### PR TITLE
Change camera default rotation

### PR DESCRIPTION
**Pull request by volzhs**
to look like other 3d program, like blender.

image

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Does that view still qualify as a "Top Perspective" though?

**Comment by volzhs** [comment]
@akien-mga i think i missed that. will look into it.

**Comment by akien-mga** [comment]
Then maybe keep "Top Perspective" as is, but add a new mode that would be the default one.

**Comment by volzhs** [comment]
@akien-mga I think, I should set it to "Perspective", not add new mode.

**Comment by volzhs** [comment]
@akien-mga I set it to "Perspective" by default now.

**Comment by volzhs** [comment]
and I think it was actually "Front" perspective.

**Pull request merged**
