### PR TITLE
Editor Debugger: auto scrolling is activated at every log start.

### PR DESCRIPTION
**Pull request by dankan1890**

### CODE REVIEW

**Comment by Calinou** [comment]
@dankan1890 Is this pull request no longer valid somehow? It would be better to leave it open if it still can be merged.

(Sorry for the delays in reviewing pull requests. The `master` branch is undergoing refactoring as we speak.)

**Comment by dankan1890** [comment]
Sorry, my mistake :(

**Comment by reduz** [comment]
@Faless I think you slept on this one :)

**Comment by Faless** [comment]
> I think you slept on this one :)

I did :) . Is this still relevant? The Editor log now gets cleared every time you press `play`, (and it will restart following if you were not following).
So, I think this behaviour is already the default.

Additionally, I think that now that we have multiple debugger instances it's time to split the output log from sessions in their own tab (I know reduz didn't like this originally, so I guess we'll have to discuss it in a meeting :) ).

**Comment by Faless** [comment]
Closing, as this behaviour should already be the default, but feel free to comment/re-open if you think it's still useful.

**Pull request closed without merging**
