### PR TITLE
[3.x] Added Viewport canvas cull mask / CanvasItem rendering layers.

### PR DESCRIPTION
**Pull request by Macksaur**
A godot3x-ified rewrite and extension of the great work in #31877 targeting 3.x as it's a hard cherry to pick. Please see: #52389 for all the details on what's new and changed. This PR is simply the 3.x flavour/style.

Here's an example of what this PR is intending to make easy:
puddles2

### CODE REVIEW

**Comment by Macksaur** [comment]
Please see the 4.0/parent PR for an explanation of the test scene.

[CanvasLayerMaskTestGithub-3.x.zip](https://github.com/godotengine/godot/files/7109164/CanvasLayerMaskTestGithub-3.x.zip)

**Comment by ZuBsPaCe** [comment]
There's a problem in combination with classes derived from PhysicsBody2D. For example: add a RigidBody2D to your scene, open the visibility drawer and hover over the new layers property:

image

This seems to happen, because physics_body_2d.cpp already binds a "layers" property. Changing the CanvasItem layers in the screenshot above, will change the PhysicsBody2D layer. You will only realize this, after deselecting/reselecting the Rigidbody2D.

Don't know, if this also applies to the 4.x (master) branch. [reduz proposed](https://github.com/godotengine/godot/pull/52389#discussion_r710123428) to change the property name to visibility_layer. I think, this would be a good idea. It's a bit confusing to have 2 different "layers" on physic bodies.

However, this feature is awesome! It opens up Godot to a lot of new shader tricks, which were not easily possible before. Thanks for your work!

**Comment by Macksaur** [comment]
This isn't an issue in 4.0 since a17fdaef09f686f7c61b7f25439061de99a863c0 removed the offending property. But anyway I dislike the confusion and bad interaction here, so rather than add to it I do think renaming is probably the way to go. I just wanted to maintain as much of the original PR as possible before diverging.

If the parent PR is taken, I'll probably rename `layers` to match.

**Comment by BimDav** [comment]
I'm still very excited by this feature, what is next for it?

**Comment by Macksaur** [comment]
It's basically being held up by the 4.0 version which is stuck in review.

What's left here:
- Rename/match the variables and gdscript functions with whatever the 4.0 version wants
- Champion and convince reduz the default `CanvasItem::is_visible_in_tree` logic isn't enough / is broken (I tried deleting one of the helper functions and leaving the "bugfix" for another PR) or...
- If the `CanvasItem::is_visible_in_tree` logic isn't accepted almost all the uses of `CanvasItem::is_visible_in_tree` need replacing with `CanvasItem::is_visible_in_viewport` to allow things like UI to work properly and not allow clicking invisible `CanvasItem`s.
- _(`CanvasItem::_update_callback` is the only place I think where the original logic of `CanvasItem::is_visible_in_tree` applies, since it must build the data to render in \*any\* case)_

Honestly so much time for this has passed I'm sure I've forgotten details...

I really want to see this feature too.

**Pull request closed without merging**
