### PR TITLE
scons: default to cpu_count concurrent jobs

### PR DESCRIPTION
**Pull request by capnm**
The scons -j1 ... -jx option overrides this default setting.

### CODE REVIEW

**Comment by vnen** [comment]
What happens if someone type `-j 1` (separated by a space)?

**Comment by akien-mga** [comment]
I prefer this to stay manual personally, I like it that `scons p=x11` will only use one core, and that I need to specify `jX` to use more. I tend to do other activities next to compiling and most of the time I just compile with one thread in the background.

**Comment by capnm** [comment]
@vnen Thanks, oh I found also SCONSFLAGS='-j4',--jobs, etc.
I hope you can now finally always change the default  :)

@akien-mga I still think that this is very handy for new users,
because in most cases they will like to get the binary quickly
and without reading the manual ;-)

If you already know the software, you can easy set the
options in the environment or cmdl manually. I believe even
the p=x11 would make sense as the default setting on linux.

**Comment by RandomShaper** [comment]
@capnm, when you a considering building something yourself you are expected to read the docs. I don't think there is much possibility on anti-dummy protection at this level.

I don't remember now what the default platform gets set to, but having it set by default to the host platform doesn't look as a bad idea. And only specifying it for cross-compiling.

**Comment by Zireael07** [comment]
How would one opt out of -j completely? On Windows, using any number of -j can lead to errors when compiling so I put up with longer times and don't use -j at all...

**Comment by capnm** [comment]
@RandomShaper Yes, I wasn't entirely serious;) It's not about dummy protection, it's more about having a sane defaults. If you start with a new software, you will expect to type scons, make, cmake, whatever-the-standard-is and get _fast_ a useful result. I think for godot you will in the most cases expect the **tool** version that runs on the current system.  If you need more,  the next step would be typing -h --help -H, hence the PR  #9971 :-)

@Zireael07
* looks like a bug and should be fixed.
* if the concurrent buildig is completely broken, it could/should be disabled on windows
* you can always type ```scons -j1``` or a any variant of ```SCONSFLAGS='-j1' scons```. That disables the concurrency.

**Comment by akien-mga** [comment]
> I don't remember now what the default platform gets set to, but having it set by default to the host platform doesn't look as a bad idea. And only specifying it for cross-compiling.

That's already the case.

> It's not about dummy protection, it's more about having a sane defaults. If you start with a new software, you will expect to type scons, make, cmake, whatever-the-standard-is and get fast a useful result.

I don't agree. I expect `scons`, `make`, `ninja` or any build tool to use the defaults that are common to every single project using those tools. All those tools require that you specify builds jobs manually if you want more than one - by silently changing this behaviour, you will confuse all people who have actual experience with buildsystems.

Building from source is for devs, and devs have to know their tools. It's great that Godot is easy to build for non-devs, but they should still read the docs to see how things are meant to be used.

**Comment by capnm** [comment]
@akien-mga
>>I don't remember now what the default platform gets set to, but having it set by default to the host platform doesn't look as a bad idea. And only specifying it for cross-compiling.

>That's already the case.

Nope. By default it crashes the scons process and prints:
```
No valid target platform selected.
The following were detected:
	windows
	server
	haiku
	x11

Please run scons again with argument: platform=<string>
NameError: name 'env' is not defined:
  File "/media/mc/data/wip/godot-build/godot-git-capnm/SConstruct", line 483:
    node_count_fname = str(env.Dir('#')) + '/.scons_node_count'
```
>… All those tools require that you specify builds jobs manually if you want more than one - by silently changing this behaviour, you will confuse all people who have actual experience with buildsystems. …

That was probably a good default for the single core age, today's modern software and languages are mostly per default multi-threaded and try to utilize the available resources. We have unfortunately basically different views on this topic, but you are the boss :)

I'm still interested in a technical review for my own Godot work, but I don't mind if you close/archive this PR. Thanks.

**Comment by akien-mga** [comment]
> Nope. By default it crashes the scons process and prints:
> ```
> No valid target platform selected.
> The following were detected:
> 	windows
> 	server
> 	haiku
> 	x11
> 
> Please run scons again with argument: platform=<string>
> NameError: name 'env' is not defined:
>   File "/media/mc/data/wip/godot-build/godot-git-capnm/SConstruct", line 483:
>     node_count_fname = str(env.Dir('#')) + '/.scons_node_count'
> ```

Ah, my bad. The traceback is a regression from #9553 by @timoschwarzer and should be fixed. Making the command default to the host platform could be implemented, but actually running `scons` without argument is the most efficient way to audit your build environment to see what platforms you do support, so I'm not sure if it would be an improvement.

> That was probably a good default for the single core age, today's modern software and languages are mostly per default multi-threaded and try to utilize the available resources. 

But then that's something to fix directly upstream in the SCons project, GNU Make, etc. If those projects consider that single-threaded is a better default, I trust their judgement.

> I'm still interested in a technical review for my own Godot work, but I don't mind if you close/archive this PR. Thanks.

Well I don't presume to decide alone, I'd like to know what other contributors think of the proposal. If most are in favour of it, it can be merged.

**Comment by timoschwarzer** [comment]
@akien-mga Whoops! Will fix soon.

**Comment by vnen** [comment]
> On Windows, using any number of -j can lead to errors when compiling so I put up with longer times and don't use -j at all...

This sounds like it's completely broken but it is not. It just has some trouble with the generated files (#5042). Once they're all generated, you can use how many jobs you want and it won't break.

----

I'm against this idea of overriding the number of jobs. If the point is being friendlier to those who know the build tool, they would expect the number of jobs to default to 1. I agree with @akien-mga on that: such thing should be changed upstream if it needs a change.

**Comment by capnm** [comment]
> But then that's something to fix directly upstream in the SCons project, GNU Make, etc. If those projects consider that single-threaded is a better default, I trust their judgement.

@akien-mga  @vnen  They can't change the default for compatibility reasons. That are just external tools, I really don't see any reason to follow that in your own up-to-date projects. But you guys already know my opinion.

> Ah, my bad. The traceback is a regression from #9553 by @timoschwarzer and should be fixed. Making

Um, I think that's also the reason why the --help options doesn't work. 

> Whoops! Will fix soon.

@timoschwarzer if you suppress the 'Platform …' message printing for the ```--help``` and ```-h``` case, then I could close the #9971 PR.

**Comment by capnm** [comment]
Haha, something similar was already 2014 in the tree 12a3989cd7b645f271c8b297a09cb0a4a7d8d2d4 and got lost by the 'Big clean up of SCons' 0fa94a96904a8ff44d1a26fd6b783c2d6a533540 

I see, Godot does not like it ;)

**Comment by timoschwarzer** [comment]
@capnm Uhm, which "Platform…"-message? I'm just responsible for the error here: 
https://github.com/godotengine/godot/pull/9972#issuecomment-318904407

**Comment by capnm** [comment]
@timoschwarzer 
Currently if you type ```scons -h``` or  ```scons --help``` you don't get the options help page because
the scons process crashes. The PR #9971 is a hack that prints the help message manually:
```
arch: Platform-dependent architecture (arm/arm64/x86/x64/mips/etc)
    default: 
    actual: 

bits: Target platform bits (default/32/64/fat)
    default: default
    actual: default
...
```

If you fix the crash issue, it would be great if you could check/make sure that ```scons -h``` prints the help page and isn't spammed by :
```
scons: Reading SConscript files ...
No valid target platform selected.
The following were detected:
	windows
	server
	haiku
	x11

Please run scons again with argument: platform=<string>
```
Thanks.

**Comment by akien-mga** [comment]
Since @vnen agrees with me regarding not defaulting to multithreaded builds, closing. But thanks for the proposal and the discussion at any rate :)

**Comment by akien-mga** [comment]
FYI, I've opened #9998 so that we remember about the stacktrace issue.

**Pull request closed without merging**
