### PR TITLE
Fix near one opacity in editor icons

### PR DESCRIPTION
**Pull request by krazy-j**
Remove occurrences of fill-opacity and stroke-opacity with values near or equal to 1 (all values were greater than 0.988).

### CODE REVIEW

**Comment by clayjohn** [comment]
Does this fix a bug or improve some behaviour? In other words, what is the purpose of this PR?

**Comment by akien-mga** [comment]
I think it's a good quality/consistency cleanup. Might also speed up rasterizing a bit if fully opaque instead of handling near-opaque transparent lines?

Would need a rebase to remove the merge commit though.

**Comment by krazy-j** [comment]
The purpose is to clean up, optimize, and improve the SVGs.

**Comment by krazy-j** [comment]
I have some other things that I'm looking at as well, including unnecessary `transform` values, where the translation applied is just cancelling out the position in the path, making it unnecessarily convoluted.

**Comment by krazy-j** [comment]
> Would need a rebase to remove the merge commit though.

I was wondering about that. I'm not actually sure I understand how to combine/rebase/squash it into one commit. I'll have to look into it later tonight.

**Comment by clayjohn** [comment]
We have a detailed tutorial on squashing commits in the docs
https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by krazy-j** [comment]
Alright, I think I did it? If there's anything I need to fix or redo, let me know.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
