### PR TITLE
unit tests for all public methods in the sprite frame class

### PR DESCRIPTION
**Pull request by im-deepfriedwater**
Open to any feedback! Covered many input cases along with expected behaviors when bad input is provided to functions.

### CODE REVIEW

**Comment by im-deepfriedwater** [comment]
op noticed right after I put this up I accidently removed a test suite entry, removing it and rebasing!

**Comment by im-deepfriedwater** [comment]
ran clang-format locally to fix workflow errors

**Comment by im-deepfriedwater** [comment]
hey sorry I've left this hanging for a while, going back to clean this up and try to get these merged

**Review by akien-mga — APPROVED** [review]
Apologies for the delay reviewing this.

This looks good :+1: 

I force pushed an update to fix some style issues (we use snake case for identifiers, and Godot Objects shouldn't be `new`'ed but `memnew()`'ed (or here `.instantiate()`d).
Also fixed the list getters checks which were not checking their results properly.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by im-deepfriedwater** [comment]
no worries! sorry I missed the merged notification LOL, that's awesome! thanks for the feedback, hope I can make some other contributions as well!

**Pull request merged**
