### PR TITLE
Modified undo_redo.h

### LINKED ISSUE #87101: Using undo shortcut doesn't work on Script Editor.
### Tested versions

Reproducible in : 352434668923978f54f2236f20116fc96ebc9173
not reproducible in : 4.2

### System information

macOS 13.3.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

When pressing the shortcut it shows nothing to Undo even though there is clearly something as shown when doing undo through menu. 

https://github.com/godotengine/godot/assets/66184050/73675e7a-d2a5-4582-be80-94498016175a

### Steps to reproduce

- Open Script Editor
- Write something
- Press Ctrl + Z or whatever your undo shortcut
- it prints Nothing to undo
- go in menu Edit > Undo and it will properly Unod

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by blitzboah**
Fixes #87101

### CODE REVIEW

**Review by AThousandShips — CHANGES_REQUESTED** [review]
I don't believe this is the proper solution, this will affect every use of this, with various possible risks, instead the place that uses it should be fixed instead, [local solutions to local problems](https://docs.godotengine.org/en/stable/contributing/development/best_practices_for_engine_contributors.html#prefer-local-solutions)

Further the script editor uses the editor undo system and it handles the checks afaik

**Comment by victorbstan** [comment]
Undo is available in editor if triggering manually from the editor menu, I think the issue is about which undo queue is called when using the key shortcut, IE: if the script editor is focused it should undo from the script editor queue, if the 3d/2d editor is focused, it should undo from the editor queue.

**Comment by ajreckof** [comment]
as stated in the bug report this bug is a regression first step to solve it should be to find which PR introduced the bug too find out where to start from. I agree with AThousandShips that this solution is very likely to have a lot of unwanted side effects.

**Comment by akien-mga** [comment]
Closing based on the discussion above.

**Pull request closed without merging**
