### PR TITLE
Removed transparency from spatial editor grid.

### LINKED ISSUE #11475: 3D grid divisions should be made more distinct
Godot 3.0 master

The newly added grid divisions aren't easily noticeable because their color is bleeding on regular grid subdivisions:

image

Ideally it should look more like this, as I already proposed in https://github.com/godotengine/godot/pull/11081:

image
(colors are different but you can see lines are distinct)

### LINKED ISSUE #11479: Strange render behavior when using View Grid and shader with alpha
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master branch

**Issue description:**

View Grid enabled:
2017-09-21-212043_880x688_scrot
View Grid Disabled:
2017-09-21-212051_889x639_scrot

### PR DESCRIPTION
**Pull request by djrm**
grid transparency caused some problems, with transparent objects, so it was removed, as a consequence it is not possible to use alpha values for the grid color, disabling the 'fading' grid : (

this is how it looks with this PR

screenshot from 2017-09-24 17-33-05

screenshot from 2017-09-24 17-31-18

also, it is not visible in the screenshots but i removed the blue cursor at the center, @reduz are you okay with this?

closes #11479 
closes #11475

### CODE REVIEW

**Comment by groud** [comment]
Too bad... I liked it :(

**Comment by n-pigeon** [comment]
R.I.P. grid fade :<

**Comment by toger5** [comment]
I also loved the fade grid. can't we keep it optional. I never encountered any problems (also didn't use transparent objects...)

**Comment by djrm** [comment]
@akien-mga, @hpvb. rebased

**Comment by Zylann** [comment]
FYI I'm working on a prototype of Unity-like grid, which has both fading and spans infinitely at multiple zoom levels. If I get to a point it works good, I can PR if people are interested in such a grid ;)

**Comment by Zylann** [comment]
I just noticed that GIProbe grid is actually transparent. Then I remembered this PR/threads about this transparency issue... is it really a problem since GIProbe uses a transparent grid anyways?

**Comment by djrm** [comment]
also grid map has a transparent grid, but it is true, transparency here causes a weird glitch with other transparent objects.

**Pull request merged**
