### PR TITLE
Lunasvg

### LINKED ISSUE #2864: Use LunaSVG instead of NanoSVG for importing SVGs
### Describe the project you are working on
Games that wants to use SVG as game art.

### Describe the problem or limitation you are having in your project

Nanosvg isn't maintained. Nanosvg crashes and is not as robust.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

To import SVGs use Lunasvg instead of nanosvg.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Add Lunasvg as a Godot Engine module. 

We need to modify the SVG with an XML parser to make light theme or dark theme changes.

https://github.com/fire/godot/tree/lunasvg

Links:

* https://github.com/sammycage/lunasvg
* https://github.com/memononen/nanosvg
* https://github.com/godotengine/godot/pull/49601

### If this enhancement will not be used often, can it be worked around with a few lines of script?
SVG rendering is not easy.

### Is there a reason why this should be core and not an add-on in the asset library?
SVG is needed for editor icons too and that is before addons are initialized

### LINKED ISSUE #16180: Workaround for SVG assets when NanoSVG fails
Godot uses [NanoSVG](https://github.com/memononen/nanosvg) which is stupidly simple so it's limited in some way.

If you encounter any problems:
- Use Inkscape to export your SVG assets (in case you use Affinity Designer, not sure about Adobe Illustrator though)
- Convert everything to paths if possible (clipping, texts,...)
- Embedded images are not supported
- Just export to rasterized images if it's not worth it

### PR DESCRIPTION
**Pull request by fire**
A better SVG import that is faster and is maintained.

Fixes: https://github.com/godotengine/godot/issues/16180
Fixes: https://github.com/godotengine/godot-proposals/issues/2864

- [ ] Add third party txt modifcations
- [ ] Code review
- [ ] Restore light and dark theme changes @Calinou

### CODE REVIEW

**Comment by fire** [comment]
Need some assistance with the thirdparty legal documentation.

**Comment by LightningAA** [comment]
Shouldn't nanosvg be removed too if this is replacing it?

**Comment by qarmin** [comment]
Can you make it default for now, to be able to test editor inside CI?

**Comment by fire** [comment]
@qarmin should be testable now.

**Comment by fire** [comment]
`thirdparty/nanosvg/` in the stack is strange. That code has been deleted.

**Comment by fire** [comment]
The ThorVG branch is more active, closing this one.

**Pull request closed without merging**
