### PR TITLE
Add support for Opus audio format

### LINKED ISSUE #1706: Support for Opus audio codec
<http://www.opus-codec.org/>

> Opus is a totally open, royalty-free, highly versatile audio codec. Opus is unmatched for interactive speech and music transmission over the Internet, but is also intended for storage and streaming applications. It is standardized by the Internet Engineering Task Force (IETF) as RFC 6716 which incorporated technology from Skype's SILK codec and Xiph.Org's CELT codec.
>
> Opus can handle a wide range of audio applications, including Voice over IP, videoconferencing, in-game chat, and even remote live music performances. It can scale from low bitrate narrowband speech to very high quality stereo music. Supported features are:
>
> * Bitrates from 6 kb/s to 510 kb/s
> * Sampling rates from 8 kHz (narrowband) to 48 kHz (fullband)
> * Frame sizes from 2.5 ms to 60 ms
> * Support for both constant bitrate (CBR) and variable bitrate (VBR)
> * Audio bandwidth from narrowband to fullband
> * Support for speech and music
> * Support for mono and stereo
> * Support for up to 255 channels (multistream frames)
> * Dynamically adjustable bitrate, audio bandwidth, and frame size
> * Good loss robustness and packet loss concealment (PLC)
> * Floating point and fixed-point implementation

Opus compression performs better than Vorbis compression, which is the main rationale to implement it.

As far as I know, Godot does not support Opus, neither the Opus container (.opus) which is preferred nor Ogg Opus (.ogg). Please correct me if I'm wrong.

### PR DESCRIPTION
**Pull request by vnen**
Tested on Linux, Windows, Android and Javascript. I can't test for other platforms, but I'm able to cross-compile for OS X and iPhone.

Closes #1706.

### CODE REVIEW

**Comment by reduz** [comment]
Wow this is amazing! did you by chance also make sure when compiling on arm
it uses the relevant optimizations?

**Comment by vnen** [comment]
> Did you by chance also make sure when compiling on arm
it uses the relevant optimizations?

Yes, but for iOS arm64 it gave some compiling errors in the inline assembly, so I removed it in that platform. I can try to tweak and test if I can select at least some of them.

**Comment by vnen** [comment]
@reduz, I added the optimizations for arm64 that still allowed it to compile.

**Comment by reduz** [comment]
awesome, thanks!

**Pull request merged**
