### PR TITLE
Force script lookup on all loaded assemblies, not just the main one.

### LINKED ISSUE #75352: Godot 4 .Net - Loading / Assigning a script exported from another project fails with error ("Cannot instance script because the associated class could not be found")
### Godot version

v4.0.1.stable.mono.official [cacf49999]

### System information

Windows 10

### Issue description

Exporting a script from one godot project and loading it in another does not work (following [https://docs.godotengine.org/en/stable/tutorials/export/exporting_pcks.html](https://docs.godotengine.org/en/stable/tutorials/export/exporting_pcks.html)). The ResourceLoader.Load<Script>() call finds the script and succeeds, but when assigning the script to a node, the following error occurs:

```
E 0:00:00:0477   Godot.NativeInterop.NativeFuncs.generated.cs:332 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* ): Cannot instance script because the associated class could not be found. Script: 'res://HelloWorld.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   modules/mono/csharp_script.cpp:2301 @ can_instantiate()
  <Stack Trace>  Godot.NativeInterop.NativeFuncs.generated.cs:332 @ void Godot.NativeInterop.NativeFuncs.godotsharp_method_bind_ptrcall(IntPtr , IntPtr , System.Void** , System.Void* )
                 NativeCalls.cs:5208 @ void Godot.NativeCalls.godot_icall_1_583(IntPtr , IntPtr , Godot.Variant )
                 GodotObject.cs:434 @ void Godot.GodotObject.SetScript(Godot.Variant )
                 ImportScript.cs:24 @ void ImportScript._Ready()
                 Node.cs:1783 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 Node3D.cs:988 @ Boolean Godot.Node3D.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 ImportScript_ScriptMethods.generated.cs:24 @ Boolean ImportScript.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )
```

Loading other resources (e.g. scenes) works. The assembly was also loaded successfully. Might be related to this reported issue: [.NET 6 - Running exported PCK fails to load scripts or fails to load hostfxr #72159](https://github.com/godotengine/godot/issues/72159)

### Steps to reproduce

Note: With the minimal reproduction project, only steps 3-5 and step 8 are required.

1. Create two new Godot Projects (an exporting and an importing project)
2. In the exporting, create a new script "HelloWorld" in res:// that prints "Hello World" on _Ready
3. Export the exporting project (with "Runnable" unchecked) into a .pck file for your platform
4. Copy the exported .pck file and the project's .dll from `.godot\mono\temp\bin\ExportRelease\win-x64`
5. Paste the two files to the res:// folder of the importing project
6. In the importing project, create a 3D scene and add a new script to the root node
7. In the new script, paste the _Ready function below
8. Run the importing project and check the Debugger->Errors list

```
public override void _Ready()
{
	// Prepare empty node
	Node3D node = new Node3D();
	AddChild(node);

	// Load assembly and pck file
	System.Reflection.Assembly.LoadFile(ProjectSettings.GlobalizePath("res://ExportingProject.dll"));
	ProjectSettings.LoadResourcePack("res://ExportingProject.pck");

	// Load script and assign it
	Script script = ResourceLoader.Load<Script>("res://HelloWorld.cs");
	node.SetScript(script);
}
```

### Minimal reproduction project

[MinimalReproductionProjects.zip](https://github.com/godotengine/godot/files/11071232/MinimalReproductionProjects.zip)

### LINKED ISSUE #77675: Scripts cannot be loaded from additional C# projects.
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 10 - Godot 4.0.3.stable

### Issue description

Currently in Godot 4.0.3 you cannot have an additional C# project included in the solution with scripts. It would be nice for organization to allow multiple assemblies. As Godot uses source distribution for addons it would be very beneficial to allow csproj files to be included in this, so the csproj can define nuget/other references.

Assigning a script to a Node from another assembly results in this error at runtime: 

`Cannot instance script because the associated class could not be found. Script: 'res://SecondaryCsproj/ScriptB.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).`

I would expect it to load normally in the same way as other scripts in the project.

This may be related to #75352 but is not the same issue, the issue described by that ticket seems specific to runtime loading of assemblies. 

### Steps to reproduce

In the attached reproduction project I have created a second C# project in the solution and excluded the contents from the main project. It may be beneficial to allow the main csproj to occupy a subfolder instead of being required in the root of the project to avoid the necessity of excluding other csproj's source.

Just open the main scene and run, note that ScriptA executes normally, ScriptB fails to load.

### Minimal reproduction project

[MultipleCsprojBugReport.zip](https://github.com/godotengine/godot/files/11607985/MultipleCsprojBugReport.zip)

### PR DESCRIPTION
**Pull request by preslavnpetrov**
Proposed fix for issues #75352 and #77675 

Currently it is impossible to load a script inside a different csproj into the engine, as the C# glue only looks and registers scripts from the main assembly.

The proposed fix in this PR addresses this by doing the script lookup on all assemblies that get loaded initially, or later on in the runtime.

There are several caveats that can be addressed in future PRs:

1. All script files from the secondary assembly must still be within the godot project's project folder, so they can be assigned valid "res://" filepaths. This can be resolved in the future by moving away from the "res://" filepath for C# scripts and instead pathing to them based on a different path, such as "dotnet://{Assembly.FullTypeName}"
2. The secondary C# project's .csproj file must override `<GodotProjectDir>` to point to the actual project, as it will usually default to `$(MSBuildProjectDirectory)`. For this, it's best to use a relative path and store the project files close together. This step is not required if the .csproj file is in the root directory of the godot project.
3. The runtime must have already loaded the project assembly into the domain before methods such as `GD.Load("res://script.cs")` can be called for scripts in that assembly. This can be done in multitude of ways, but the easiest "hacky" solution is to have a static class in the main project such as `ScriptAssemblyLoader` and in the static constructor of that class, make a trivial reference to any type in the secondary assembly (for example `GD.Print(typeof(ClassInSecondaryAssembly));`

Point 3 is the most annoying part of this process and should be dealt with in the future to ensure there is less friction when using this workflow. One method of doing so would be to use a resource similar to the Unity Assembly configuration, where the user lists all of the script assemblies they need, and they are manually loaded by the engine on boot.

I think this is a good first step in at least supporting this workflow as it makes it viable, but I'm open to any changes proposed and feedback.

* *Bugsquad edit, fixes: #75352*
* *Bugsquad edit, fixes: #77675*

### CODE REVIEW

**Comment by Delsin-Yu** [comment]
I personally also support dropping the `res://` path idea, it also removes the restriction of `one type per script / script filename must match the type name`; using `dotnet://` or `csharp://` virtual path also goes well with C# as it's compiled language nature. However, it is a huge breaking change as it breaks every existing C# script link, and we need to work out some sort of upgrade mechanism.

**Comment by preslavnpetrov** [comment]
Yeah I would assume these sort of things won't even be necessary for 5.x cause that should, hopefully, have the GDExtension version of DotNET done. Also they're just musings, the purpose of this one is just to get a feature from not working at all to functional.

**Comment by raulsntos** [comment]
I think loading scripts from different assemblies is not something we want to support due to the caveats you mentioned. If users are fine with those caveats they should also be able to just invoke `LookupScriptsInAssembly` manually, but I don't think it's something we should encourage[^1].

As @Delsin-Yu mentioned, changing the script paths to a virtual path (e.g.: `dotnet://` or `csharp://`) would be a pretty big breaking change, and I don't really want to make big changes to the scripting API right now. I belive the goal for the scripting API should be to stabilize, so existing users can keep using it without worry and users that are looking for exciting new features can look at the new GDExtension-based bindings.

[^1]: See https://github.com/godotengine/godot-docs/pull/8486#pullrequestreview-1733422308 for more context.

**Comment by preslavnpetrov** [comment]
Hey @raulsntos . The virtual path stuff is definitely irrelevant, didn't even mean to discuss that and I agree that it's a bit too much work for not that much gain.

However I do think loading scripts from different assemblies is quite an important goal to try and support, especially for use with the Asset Library and in future the Asset Store. One of the biggest limitations to posting a plugin/asset with scripts right now would be the fact that you always need to target the lowest supported version of dotnet and be very careful not to introduce namespace clutter into the user's project. It's also difficult to encapsulate pieces of a plugin that should not be used by the user.

Being able to publish plugins as assemblies I think would be useful to everyone. Do you think this is worth pursuing in the script workflow, or are you thinking it's something better handed by the GDExtension workflow as a future feature?

**Comment by raulsntos** [comment]
Addons or plugins shared in the asset library will have to be shared as source code. This means addon authors will have to target .NET 6.0 and C# 10, or if a newer version is required, they'll have to document it to let users know they need to change this in their csproj when using the addon. I know this isn't ideal for a compiled language like C#, but I also think GDExtension would solve this more cleanly.

**Comment by preslavnpetrov** [comment]
That makes sense, we can probably close this one then, I'll see what I can do to convert it to an addon for those interested in this feature. I'd also be interested in helping in contributing to the GDExtension bindings of dotnet in that case. I'll follow up on this in the contributor chat.

**Pull request closed without merging**
