### PR TITLE
Add feature to disable tabs in TabContainer and Tabs control.

### LINKED ISSUE #7436: Option to disable Tabs in TabContainer
_This is an enhancement request to TabContainer._

It would be nice to be able to disable Tabs in a TabContainer like (or at all):

`self.set_tab_disabled(tab_idx)`

or a singal that get fired if you click on the Tab, and only the Tab but not the "area" beneath it.

In case you want to show the Player this tabs exists but you havent yet met the requierements to open it:

- you need to reach lvl 15 to choose super skills
- you need to be a guild member to access the guild options
- you cant open this tab until you finished the tutorial

To name 3 examples. I dont want to remove the tab because i want the player to know its there.
The Tab could be greyed out or something like that and clicking on it would do nothing.

### PR DESCRIPTION
**Pull request by RayKoopa**
`Tabs` and `TabContainer` control can now get their tabs disabled or enabled. Fixes #7436.

- If the currently active tab is disabled, it stays visible, but after a change to another tab it cannot be selected anymore.
- The close button on disabled tabs cannot be clicked.
- Visual design of a disabled tab is the one of a disabled button.

### CODE REVIEW

**Comment by RayKoopa** [comment]
Might aswell add this on top of https://github.com/godotengine/godot/pull/7600 after I overhauled almost everything of `TabContainer` in there...

**Comment by akien-mga** [comment]
> Might aswell add this on top of #7600 after I overhauled almost everything of TabContainer in there...

So you mean best avoid merging this PR for now and let you rebase it once #7600 is merged?

**Comment by RayKoopa** [comment]
Yes, I guess. I think I'll actually just write my changes anew on top of #7600 as most of the drawing and UI code has been rewritten.

**Comment by RayKoopa** [comment]
Updated to most recent master. Hell, the Tabs node partly has the same issues as the ones I fixed in TabContainer...
I will rewrite both of these somewhen so the TabContainer builds up on the Tabs logic, this is ridiculous.

**Comment by akien-mga** [comment]
Yeah, @StraToN and I had already noticed that there was a lot of code duplication between Tabs and TabContainer, but did not get to fix it (yet). I think the historical reason for that is that TabContainer did not exist when Tabs was written for the editor (or is it the other way around? :p)

**Comment by RayKoopa** [comment]
When I find time to rewrite the whole thing from scratch, also because I want to optimize the tab display by allowing "half tabs" to be visible if they don't fit into the scrollable region, I might consider letting TabContainer inherit from Tabs...

**Comment by volzhs** [comment]
there is generated png data here https://github.com/godotengine/godot/pull/7517/files#diff-e4bd3563610135f72e777866dc176495R461
but this commit does not include actual png, so it raises compile error when make fresh [theme_data.h](scene/resources/default_theme/theme_data.h) by [make_header.py](https://github.com/godotengine/godot/blob/master/scene/resources/default_theme/make_header.py)

**Pull request merged**
