### PR TITLE
Prettier str() for some math types

### LINKED ISSUE #5919: Prettier print for array of Vector
```gdscript
var arr = [Vector2(1,2), Vector2(3,4)]
print(arr)
```

This prints ``[1,2, 3,4]``
It would be great if it prints ``[(1,2), (3,4)]``

### PR DESCRIPTION
**Pull request by neikeq**
Closes #5919

### CODE REVIEW

**Comment by neikeq** [comment]
> @alketii See what you've done! :smile:

**Comment by akien-mga** [comment]
It would be nice to make the usage of space after the comma consistent for all math types. Currently Vector3 and Matrix3 seem to use one, but for example Vector2 doesn't.

**Comment by akien-mga** [comment]
Sorry, misclicked :D

**Comment by neikeq** [comment]
Yeah, I noticed that too. We need a consensus on that :P

**Comment by akien-mga** [comment]
I'd say "Let's ask Python":
```
Python 3.5.2 (default, Jul  6 2016, 12:22:48) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> arr = [2, 3, "lol"]
>>> print(arr)
[2, 3, 'lol']
>>> tup = ("hello", {})
>>> print(tup)
('hello', {})
>>> mat = []
>>> mat.append(arr)
>>> mat.append(arr)
>>> print(mat)
[[2, 3, 'lol'], [2, 3, 'lol']]
```

So, spaces spaces spaces :)

**Comment by neikeq** [comment]
Done. Not sure if I am missing any.

**Comment by SuperUserNameMan** [comment]
I guess it's too late to discuss about this, but it changed the bahavior of ``Dictionary.to_json()`` from 2.0.4.1 to 2.1stable.

````
var d = { "vector3_array" : Vector3Array([ Vector3(1,2,3), Vector3(4,5,6) ]) };
var json = d.to_json();
print( json );
````
2.0.4.1 : ``{ "vector3_array":"[1, 2, 3, 4, 5, 6]" }``
2.1stable : ``{ "vector3_array" : "[(1, 2, 3), (4, 5, 6)]" }``

````
var e = {}; e.parse_json( json );
print( str2var( e.vector3_array ) );
````
2.0.4.1 : ``[1, 2, 3, 4, 5, 6]``
2.1stable : ``Error calling built-in function 'str2var': Parse error at line -1143028872: Expected value, got '('.``

**Comment by bojidar-bg** [comment]
@SuperUserNameMan I guess that would be fixed in 2.1.1 if there is such a version.

**Comment by neikeq** [comment]
Wait, shouldn't Dictionary be using VariantWriter?

**Comment by SuperUserNameMan** [comment]
``Dictionary.to_json()`` uses ``JSON::print()`` which uses ``JSON::_print_var()`` which returns ``default: return "\""+String(p_var).json_escape()+"\"";``

https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/core/io/json.cpp#L89

**Pull request merged**
