### PR TITLE
Cleanup function state connections when destroying instance

### LINKED ISSUE #24311: Destroying an object running a coroutine (yield) should interrupt this coroutine properly
Godot 3.0.6

This is one of the things that make me avoid `yield` often: basically, I like to use `yield` to lay down a series of asynchronous tasks in a normal function, which is very easy to follow and maintain. The only problem is, there is no clean way to interrupt such a task. By this, I mean I would expect the function to be stopped as if resuming it and immediately `return`ing. So no "magic" cleaning, you would still have to put `yield` in proper places, but at least that would be something workable.

Currently, If the object running that coroutine gets destroyed (scene change, plugin disabled, enemy death, etc), it will throw the following error in the debugger:
```
ERROR: Resumed after yield, but class instance is gone
   At: modules/gdscript/gdscript_function.cpp:1490
```
[YieldDestroyedObject.zip](https://github.com/godotengine/godot/files/2674270/YieldDestroyedObject.zip)

I thought about putting an `if stop` after each `yield`, but that makes the code really ugly and still doesn't handle interruption properly. So I keep going back to `_process` to handle this, which is frustrating and time consuming.

Is that due to how `yield` was implemented? Is there a way to handle this?

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #24311

It can't be that simple, can it? 🤔

### CODE REVIEW

**Comment by KoBeWi** [comment]
I rebased and the code is not valid anymore :/
It works, but sanitizer is not happy about it.

**Comment by adamscott** [comment]
I suspect that the same `GDScriptInstance::~GDScriptInstance()` is ran twice. Try adding a `destructing` variable, like I did in `GDScript::~GDScript()`.

**Comment by anvilfolk** [comment]
> I suspect that the same `GDScriptInstance::~GDScriptInstance()` is ran twice. Try adding a `destructing` variable, like I did in `GDScript::~GDScript()`.

Curious to know how that would happen. I figured destructors would only ever run once.

**Comment by anvilfolk** [comment]
I just tested adding `destructing` to `GDScriptInstance` but the issues persist unfortunately.

**Comment by adamscott** [comment]
This patch makes the build pass the sanitizer.

```patch
diff --git a/modules/gdscript/gdscript.cpp b/modules/gdscript/gdscript.cpp
index 72d5bb23c5..e6ecbc8393 100644
--- a/modules/gdscript/gdscript.cpp
+++ b/modules/gdscript/gdscript.cpp
@@ -1925,10 +1925,16 @@ GDScriptInstance::~GDScriptInstance() {
 
 	while (SelfList<GDScriptFunctionState> *E = pending_func_states.first()) {
 		// Order matters since clearing the stack may already cause
-		// the GDSCriptFunctionState to be destroyed and thus removed from the list.
+		// the GDScriptFunctionState to be destroyed and thus removed from the list.
 		pending_func_states.remove(E);
-		E->self()->_clear_connections();
-		E->self()->_clear_stack();
+		GDScriptFunctionState *state = E->self();
+		if (state != nullptr) {
+			state->_clear_connections();
+			state = Object::cast_to<GDScriptFunctionState>(state);
+			if (state != nullptr) {
+				state->_clear_stack();
+			}
+		}
 	}
 
 	if (script.is_valid() && owner) {
```

**Comment by adamscott** [comment]
Weird. My local build pass the clang test sanitizers.

**Comment by adamscott** [comment]
My hunch says that this is more sane than casting AND it should fix the macos `SIGSEGV`.

```
diff --git a/modules/gdscript/gdscript.cpp b/modules/gdscript/gdscript.cpp
index df57749f76..fc3d42b1b0 100644
--- a/modules/gdscript/gdscript.cpp
+++ b/modules/gdscript/gdscript.cpp
@@ -1484,9 +1484,9 @@ GDScript::~GDScript() {
 			// the GDScriptFunctionState to be destroyed and thus removed from the list.
 			pending_func_states.remove(E);
 			GDScriptFunctionState *state = E->self();
+			ObjectID state_id = state->get_instance_id();
 			state->_clear_connections();
-			state = Object::cast_to<GDScriptFunctionState>(state);
-			if (state != nullptr) {
+			if (ObjectDB::get_instance(state_id) != nullptr) {
 				state->_clear_stack();
 			}
 		}
@@ -1932,9 +1932,9 @@ GDScriptInstance::~GDScriptInstance() {
 		// the GDSCriptFunctionState to be destroyed and thus removed from the list.
 		pending_func_states.remove(E);
 		GDScriptFunctionState *state = E->self();
+		ObjectID state_id = state->get_instance_id();
 		state->_clear_connections();
-		state = Object::cast_to<GDScriptFunctionState>(state);
-		if (state != nullptr) {
+		if (ObjectDB::get_instance(state_id) != nullptr) {
 			state->_clear_stack();
 		}
 	}

```

**Comment by vpellen** [comment]
I believe this would fix #72629

**Review by adamscott — APPROVED** [review]
Let's merge this!

**Review by vnen — APPROVED** [review]
I think this is okay.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
