### PR TITLE
The ability to choose the BMFont file in BitmapFont properties.

### PR DESCRIPTION
**Pull request by DmitriySalnikov**
<details>
<summary>Demonstration</summary>
<a href="https://user-images.githubusercontent.com/7782218/32399267-b3a10afa-c105-11e7-9be3-a695c7745e37.gif" target="_blank">something</a>
</details>

### CODE REVIEW

**Comment by reduz** [comment]
Instead of this, I would simply make it that .fnt is recognized and loaded as a resource

**Comment by DmitriySalnikov** [comment]
@reduz yeah I thought about it.
I will try to implement.

**Comment by akien-mga** [comment]
Could you squash the two commits together? The second one undos almost everything from the first one, so we need only the final result. See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by DmitriySalnikov** [comment]
@akien-mga done

**Comment by arcanis** [comment]
@DmitriySalnikov I tried this PR and got the following, is it to be expected? Have I missed a step?

image

**Comment by arcanis** [comment]
If anyone has this issue, make sure you're using a 32 bit depth in bmfont's export settings 😃

**Comment by DmitriySalnikov** [comment]
@arcanis what about alpha channel?
the image should be transparent

**Comment by DmitriySalnikov** [comment]
@akien-mga what about this PR?

**Comment by arcanis** [comment]
@DmitriySalnikov yep, I was using the wrong export settings, it's fixed now and works perfectly fine! 👍

**Comment by arcanis** [comment]
Something I noticed that might be missing from Godot 2.1: shadow colors. They seem to always be black (iirc it was an import settings, so since the window disappear it makes sense the settings is hidden as well). But maybe that's something that should be fixed in a separate PR and this one can be merged as is?

**Comment by akien-mga** [comment]
It looks good to me, but I'd like @reduz to check the current status before merging.

**Comment by reduz** [comment]
I don't understand why BitmapFontData is needed and this is not just loaded as a BitmapFont, is there any special setting you can override per BitmapFont?

**Comment by DmitriySalnikov** [comment]
@reduz, BitmapFontData is needed because I did not find another way to register resources.
I don't know that I can override.
It turns out that you can close this PR and then need to wait for the built-in editor fonts.

**Comment by zatherz** [comment]
?

**Comment by mrcdk** [comment]
@reduz I tried to redo this PR without using `BitmapFontData` and I don't think it's possible. If we treat the `*.fnt` file as a resource then we can't save any `BitmapFont` properties to it like the `distance field` or `fallback` properties.

**Comment by mhilbrunner** [comment]
Should we go with the initial PR then? Testing some font things currently and always keeping a Godot 2 build around just for importing fonts to then move to Godot 3 feels bad.

**Pull request closed without merging**
