### PR TITLE
Restore `AudioStreamEditor` class to fix playable sound previews

### LINKED ISSUE #63683: Audio WAV samples can't be previewed anymore
### Godot version

4.0alpha13

### System information

linux

### Issue description

| alpha 12                                                                                                        | alpha 13                                                                                                        |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| image | image |

A new dedicated window for mp3 and ogg files import setup was added in alpha 13, maybe that's the reason.

### Steps to reproduce

Select a wav file in the FileSystem dock.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/63683 by restoring that class.

image

Note: I didn't find the method to push it to the bottom of the inspector (as placed in 3.x).

### CODE REVIEW

**Comment by Mickeon** [comment]
Coincidentally, I feel like it's way better at the top, too? So much closer to the other settings, it's more comfortable.

**Comment by Maran23** [comment]
Any clue why it was removed in the https://github.com/godotengine/godot/pull/63265 PR?

**Comment by Calinou** [comment]
> Note: I didn't find the method to push it to the bottom of the inspector (as placed in 3.x).

I also find it looks better at the top, especially on large/tall displays. This is more consistent with mesh and texture previews as well.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
> Any clue why it was removed in the https://github.com/godotengine/godot/pull/63265 PR?

The class seems to handle any AudioStream (i.e. WAV is not hard-coded or anything), but it doesn't appear for other stream types, because they open the advanced import dialog. Which means that if WAV gets this dialog (which is planned in the future), the inspector plugin will be left unused again. I guess this is way it was removed; it just happened to early.

**Pull request merged**
