### PR TITLE
Fixed Basis -> Quat conversions, added a few safety checks.

### LINKED ISSUE #19027: Importing animations doesn't work correctly after recent changes
**Godot version:**
`master` / b003b7d84

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When I import animations from Collada, a few keyframes in each animation have wrong bone positions, making the character's legs to bend in weird directions or even making them disappear.

If I roll back to 224d5371f revision, and reimport the animations the problem disappears while I can consistently reproduce the issue with b003b7d84 revision.

### PR DESCRIPTION
**Pull request by tagcup**
Fixes #19027.

### CODE REVIEW

**Comment by tagcup** [comment]
We should add a documentation somewhere regarding how the Basis -> Quat or Basis -> Euler angles conversion should be done, because it's very error prone.

get_euler and get_quat aren't exposed to GDScript so couldn't add it there, and I don't want to get involved with godot-docs people anymore (because they are super opinionated about trivial things and focus, ramble and insist on irrelevant adverbs or adjectives rather than 1000s words of actually useful content, see [this PR](https://github.com/godotengine/godot-docs/pull/1436) for example); maybe the error messages could be made more informative rather just err fail condition stuff.

**Comment by tagcup** [comment]
More specifically, an explanation about the polar decomposition of a Basis, and how certain methods are related to that would be very useful.

**Comment by tagcup** [comment]
@reduz Can we remove the Quat() operator from Basis? It simply doesn't work unless the Basis is a proper (meaning no reflection) rotation matrix, and thus can lead to unexpected bugs (also Basis orthonormalize -> Basis to Quat isn't the same as Basis -> Quat -> Quat normalization which is wrong).

Newly added get_rotation_quat() does the right thing (proper polar decomposition), and should be used instead

**Comment by ericstoneking** [comment]
Hi All,

I'm brand new to Godot, but I've been working with Euler angles, quaternions, and direction cosines for a long time.  I would like to contribute a mature and robust set of related functions that I think would be useful to y'all.  I'll need help, though, fitting them into the Godot way of doing things.  Would anyone like to work with me on that?

I am a spacecraft GNC engineer by trade.  I have an open-source simulation in C (see ericstoneking/42 on github).  From my first impression of the Godot transform class, I think you need:

1)  All the Euler sequences (eg. XYZ, ZYX, YXZ, XYX, etc).  Counting "Body sequences" and "Space sequences", there are 24 in all.  I spent some time today trying to reverse-engineer which ones you use, and gave up.  I can set you up with all of them, plus some documentation and references so folks know why the sequence is important (and the difference between "Body" and "Space" sequences, which also matters).

2)  Conversions between Euler angles, direction cosine matrices (DCMs, aka "rotation" matrices), and quaternions.  All of them have their strengths and weaknesses, so I like to be able to convert back and forth easily.  I prefer DCMs as the intermediary, although I do have the transform-a-vector-from-one-coordinate-frame-to-another-using-the-quaternion functions.

3)  Some clarification in notation about what reference frames a rotation is between.  I have my own terse notation that y'all probably wouldn't glom onto, but we ought to be able to come up with something systematic and clear.

So, any takers?  Am I even bringing this up in the right place?

Regards,
-Eric

**Comment by tagcup** [comment]
Hi Eric,

Euler angles have very limited usage in Godot, mainly to set the initial orientation of the objects in the editor, with typically a single, at max two, Euler angle set. For other things, axis-angle parametrization is preferred (in either matrix or quaternion representation). So I'd say there's not much point in supporting different Euler (or Tait-Bryan) angle conventions.

However, the current math library isn't robust in terms on numerical stability w.r.t. floating point errors, and if you think this can be improved without hurting the performance much, that'd be a nice addition.

>  Am I even bringing this up in the right place?

No, I'd open a new issue to discuss it

**Comment by tagcup** [comment]
> although I do have the transform-a-vector-from-one-coordinate-frame-to-another-using-the-quaternion functions.

This is implemented in `Quat::xform(const Vector3 &v)`

**Comment by tagcup** [comment]
> Some clarification in notation about what reference frames a rotation is between. I have my own terse notation that y'all probably wouldn't glom onto, but we ought to be able to come up with something systematic and clear.

Godot has 3 reference frames: global, parent-local, object-local. This is pretty standard in game engines as well as 3D modelling software such as blender, so there's no need to change it.

In Godot, unless somehow specified otherwise, all rotations are in the parent-local frame. Not all functions have object-local versions, so there is room for improvement here.

There is currently no explicit function to convert one frame into another, probably because users presumed to be are familiar enough with it to do it by hand.

**Comment by OvermindDL1** [comment]
> However, the current math library isn't robust in terms on numerical stability w.r.t. floating point errors, and if you think this can be improved without hurting the performance much, that'd be a nice addition.

This please!

**Comment by ericstoneking** [comment]
Hi All,

Thanks for the responses, and the basic orientation.  I'll go open a new issue.

**Comment by reduz** [comment]
As I mentioned before, the problem with the safety checks is that they used to trigger in cases where data already comes imported broken, or data that was saved to text (which made it lose precision). So this may result in errors triggered where the precision error exists, but is small enough to not matter.

I do understand though that those can save some debugging work when something fails, so maybe they could be made to trigger with a considerably broader range?

**Comment by reduz** [comment]
To make it clearer, currently: 

Math::is_equal_approx uses CMP_EPSILON, which is: 0.00001 , which is easy to surpass with small precision error, specially text serializing.  

There is a constant defined but seemingly not used: CMP_NORMALIZE_TOLERANCE, which we could used to test for normalization and use a much broader value, like 0.001 or even 0.01. This would definitely be a much more difficult limit to cross, would still catch errors,  but wont affect the code in practice.

**Comment by reduz** [comment]
maybe it should be CMP_DEBUG_NORMALIZE_EPSILON instead, so its clear that its a higher value due to debug.

**Comment by tagcup** [comment]
> So this may result in errors triggered where the precision error exists, but is small enough to not matter.

As I explained, the error check was *not* spuriously triggered due to precision issues. On the contrary, it revealed a bug, which is fixed here.

**Comment by tagcup** [comment]
To be more explicit. The bug was this line in editor_import_collada.cpp:

```cpp
Quat q = xform.basis;
q.normalize();
```

Quat() constructor only works correctly with a proper scaling matrix whereas here, an arbitrary basis is being passed.

And since this is not such a rare operation, and is error prone (because orthonormalize basis -> convert to quat is also wrong when negative scales / reflections are involved), there are new functions. This PR also fixes those cases such that things won't break with negative scales.

**Comment by tagcup** [comment]
errr I meant a proper *rotation* matrix

**Comment by tagcup** [comment]
@reduz BTW, if you're referring to this:

> //commenting this check because precision issues cause it to fail when it shouldn't

commenting that out was a mistake; again, the reason it failed wasn't because of precision issues but rather because a bad basis was passed to Quat constructor

**Comment by karroffel** [comment]
This fixes some of my animations where things just disappeared after a while or some bones wouldn't move at all. #19281

:+1:

**Comment by reduz** [comment]
OK, Let s do something then. Will merge this, but if another problem related to precision appears, I will change the approx limits to validate normalization to much higher values.

**Comment by tagcup** [comment]
> but if another problem related to precision appears,

I don't know what you mean by "another", there were zero problems related to precision.

Those warnings/error tend to reveal genuine bugs and not the issue on their own.

**Pull request merged**
