### PR TITLE
Do not translate node name when assigned to an exported field

### LINKED ISSUE #77214: Inspector auto-translates assigned NodePath variables
### Godot version

4.1 dev2

### System information

Windows 10 x64

### Issue description

I exported a NodePath and assigned a node called Node and this is the result:
image
It translated the name as a generic "Node" word.

### Steps to reproduce

1. Switch to non-English language that has Node word translated
2. Add Node to scene
3. Add a script with `@export var n: NodePath`
4. Assign the Node

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by hakro**
Fixes #77214

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
That change seems straightforward enough, and likely good by itself.

As the report bug seems to be a regression though, I suspect it might be caused by #74264, so we might want to check if there aren't other areas which are unexpected using editor translations for user-provided strings. CC @timothyqiu 

*Edit:* Technically the bug doesn't happen in 4.0.x but it shouldn't hurt to cherry-pick this change for good measure.

**Comment by timothyqiu** [comment]
This is caused by #75012. It makes `Object.tr()` use editor translation when in the editor so we don't have to translate default dialog button texts everywhere. But yeah, now we have to turn off auto translation for controls that should not be translated. I've fixed a few in #75426.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Pull request merged**
