### PR TITLE
Resolve conflict between shader uniform tooltips `/**` and general annotation `/**/`.

### LINKED ISSUE #91547: Shader documentation syntax fails to terminate with `/**/` causing large editor freezes (regression 4.3-dev6)
### Tested versions

- Reproducible in 4.3-dev6
- Not reproducible in 4.3-dev5

### System information

Godot v4.3.dev6 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.4601) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

After swapping from 4.3-dev5 to 4.3-dev6, existing shader code from my project included the `/**/` substring in various places. When the inspector attempts to process any shader containing this substring, there is a large lagspike (3 seconds with the MRP on my system).

This also causes the documentation syntax highlighting to affect the rest of the script. Perhaps caused by #90161 , related to #91424 by the appearance of the issue:

image

### Steps to reproduce

1. Create a CSGBox3D.
2. Give it a StandardMaterial3D, convert it to ShaderMaterial.
3. Add `/**/` to the top of the code. (The amount of lag is proportional to the amount of code after the `/**/`.)
4. Select and de-select the CSGBox3D. The editor will freeze with a large lagspike as it attempts to load the shader in the inspector.

### Minimal reproduction project (MRP)

[shader-syntax-lag.zip](https://github.com/godotengine/godot/files/15205998/shader-syntax-lag.zip)

### PR DESCRIPTION
**Pull request by magian1127**
see https://github.com/godotengine/godot/issues/91547#issuecomment-2093992570

fix #91547

### CODE REVIEW

**Comment by akien-mga** [comment]
What happens if someone uses:
```
/**
 * Some description.
 */
```
with no space (but only end of line, `$`) on the first line?

**Comment by magian1127** [comment]
This PR has been modified again to solve the following 2 problems.

1 Change the regular to `\*\*\s` start match, to solve the problem of lagging.
2 Add a color_region of `/**/` to solve the region interrupt problem. (Unless _get_line_syntax_highlighting_impl is rewritten, this is still a stopgap measure.)

**Review by akien-mga — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]
I've tested locally and it works fine!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
