### PR TITLE
Renamed navmesh_create to navmesh_add since no navmesh is created.

### PR DESCRIPTION
**Pull request by NathanWarden**
While documenting Navigation I noticed there's navmesh_create, but then there's navmesh_remove. Looking closer at the code, navmesh_create requires an already created navmesh but instead simply adds it to a Map, therefore navmesh_add is an accurate name and navmesh_create is not. It also is more consistent with navmesh_remove.. IE. 'add' and 'remove'.

### CODE REVIEW

**Comment by NathanWarden** [comment]
Technically there is a `NavMesh` struct that gets created internally, but the end user will never see it, so when they see `navmesh_add/create` they will associate that with the `NavigationMesh` resource that gets passed into the method (which is linked in the struct), not with an internal `NavMesh` struct itself.

**Comment by menip** [comment]
Needs to include an updated doc/classes/Navigation.xml in the same commit.

**Comment by NathanWarden** [comment]
@menip Thanks, I had it renamed in my other PR documenting Navigation, but it's a much better idea to rename it in this one :)

**Review by ghost — APPROVED** [review]

**Comment by reduz** [comment]
I am fine with this, but needs to be done on Navigation2D too

**Comment by NathanWarden** [comment]
@reduz Thanks Juan, both Navigation and Navigation2D are changed... and docs updated with the changed property name :)

**Pull request merged**
