### PR TITLE
Added new physics clear_forces API

### PR DESCRIPTION
**Pull request by AndreaCatania**
Used to clear all body forces inside function _integrate_forces.

Related issue: https://github.com/godotengine/godot/issues/12171#issuecomment-337169888

### CODE REVIEW

**Comment by akien-mga** [comment]
I may be missing something but I don't see any implementation of that virtual method?

**Comment by AndreaCatania** [comment]
You are true, I've added it, in order to implement it in Bullet. I don't know how to implement it with regular Godot physics. It may be implemented by Reduz or someone else after

**Comment by reduz** [comment]
I'm not exactly sure what is this useful for.. seems like a hack.
Can you not disable gravity in a body in Bullet?

**Comment by AndreaCatania** [comment]
Yes I can, and it can be done by putting gravity scale to 0. I've added it because @kubecz3k need to have 0 gravity in particular moments, with this API it's possible remove gravity easily and in the same time leave to the server the joy to add gravity force.
In addition this API is usefull to get full control over body forces.

**Comment by reduz** [comment]
The specific problem here is that, in Bullet, it's not possible to omit force integration, right?

**Comment by AndreaCatania** [comment]
Nope, I should use clear_forces directly in the server before _integrate_forces, but this is redoundant if I will add it right after

**Comment by AndreaCatania** [comment]
And not always the developer need to play with gravity

**Comment by reduz** [comment]
The problem with this approach is that, when you call _integrate_forces() they were already integrated because this is done at the end. As such I think the function itself does not really make much sense.

**Comment by AndreaCatania** [comment]
I've checked the code and the "integration" of forces in bullet is done after the _integrate_forces.

The function "_integrate_forces" remain the right place where to put all the checks and where add forces, velocities, inpulse.

The last thing to say is that bullet apply the gravity right before the execution of the function _integrate_forces.

So we have two solution here, clear direclty the gravity of each rigid body in order to allow the developer to apply it directly, or leave the developer the possibility to clear gravity.

The second solution is the one that I prefer because I think that the first solution will add an hack in the server side that force Godot to do two extra steps for each body: clear forces and add gravity (something already done by bullet).

**Comment by hickop** [comment]
#12770 might be fixed by this PR ? Tried this PR as a patch in current master and got errors at compile:
```
In file included from ./core/vector.h:39:0,
                 from ./core/vset.h:34,
                 from modules/bullet/collision_object_bullet.h:36,
                 from modules/bullet/collision_object_bullet.cpp:32:
modules/bullet/rigid_body_bullet.h: In static member function 'static void BulletPhysicsDirectBodyState::initSingleton()':
modules/bullet/rigid_body_bullet.h:61:23: error: invalid new-expression of abstract class type 'BulletPhysicsDirectBodyState'
    singleton = memnew(BulletPhysicsDirectBodyState);
                       ^
./core/os/memory.h:88:51: note: in definition of macro 'memnew'
 #define memnew(m_class) _post_initialize(new ("") m_class)
                                                   ^~~~~~~
In file included from modules/bullet/bullet_physics_server.h:38:0,
                 from modules/bullet/collision_object_bullet.cpp:35:
modules/bullet/rigid_body_bullet.h:52:7: note:   because the following virtual functions are pure within 'BulletPhysicsDirectBodyState':
 class BulletPhysicsDirectBodyState : public PhysicsDirectBodyState {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from modules/bullet/area_bullet.h:37:0,
                 from modules/bullet/collision_object_bullet.cpp:33:
./servers/physics_server.h:86:15: note: 	virtual void PhysicsDirectBodyState::clear_forces()
  virtual void clear_forces() = 0;
               ^~~~~~~~~~~~
```

**Comment by reduz** [comment]
It seems this is not needed for now, so closing. We can discuss better how to do the omit force integration eventually.

**Pull request closed without merging**
