### PR TITLE
[3.x] Add support for repackaging the generated UWP APPX file with `makeappx`

### PR DESCRIPTION
**Pull request by panreyes**
This solves https://github.com/godotengine/godot/issues/79278

This commit makes Godot 3.5 use makeappx.exe to repack the APPX file generated when exporting for UWP platform.

Currently the integrated exporter has some unknown packaging error. I have tried to figure it out without success and, after that, I considered that the fastest and most practical solution is to just use Microsoft's official tool to repackage it.

How to make it work:
- In Editor Settings/UWP, we include the path to makeappx.exe.
- When exporting to the UWP platform, Godot 3.5 will use makeappx.exe to repack the APPX file correctly.

Requiring the use of makeappx.exe is not a big problem, since to sign the packages we also need the signtool.exe tool. Both tools are part of the Windows 10/11 SDK.

With this change, and this one https://github.com/godotengine/godot-build-scripts/issues/80#issuecomment-1628621999 , Godot 3.5 will correctly be able to export to UWP format for XBOX. I have tested it and it works flawlessly for most 2D games at least.

_Production edit: Closes https://github.com/godotengine/godot/issues/30558_

### CODE REVIEW

**Comment by panreyes** [comment]
I just learnt about clang formatting and git reset 😅 Hopefully, checks will pass this time :)

**Review by akien-mga — APPROVED** [review]
I don't really have time to review in depth, but since it's working fine for @panreyes to ship games, I think we can merge.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Comment by dannygaray60** [comment]
I tried @panreyes script with the godot generated appx and I got this error: 

The path (/p) parameter is: "\\?\D:\Godot Exports\toziuha_oota\uwp_free\toziuha_oota.appx"
The content directory (/d) parameter is: "\\?\C:\Users\Danny\AppData\Local\Temp\appx-repack\game"
Enumerating files from directory "\\?\C:\Users\Danny\AppData\Local\Temp\appx-repack\game"
Packing 2539 file(s) in "\\?\C:\Users\Danny\AppData\Local\Temp\appx-repack\game" (content directory) to "\\?\D:\Godot Exports\toziuha_oota\uwp_free\toziuha_oota.appx" (output file name).
Memory limit defaulting to 4235565056 bytes.
MakeAppx : error: You must include a valid app package manifest file named AppxManifest.xml in the source.
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x80080203 - The specified package format is not valid: The file is not a valid app package because it is missing a required footprint file.
Error: Could not repackage the APPX file.

godot version: v3.5.3.stable.official [6c814135b]

**Pull request merged**
