### PR TITLE
Fix Android build

### PR DESCRIPTION
**Pull request by henkz1**
Android builds failed after all the cast_to refactoring

### CODE REVIEW

**Comment by akien-mga** [comment]
The changes look fine, but having two commits with such short names is both overkill on the number of commits and underkill on their explicitness :)

Could you [rebase to squash the two commits](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase), and maybe edit the resulting commit log to something more meaningful like `Fix refactored Object::cast_to in NO_SAFE_CAST branch`?

**Comment by hpvb** [comment]
Commits look good. I *thought* I has build with NO_SAFE_CAST but clearly I don't know how scons works. What's more worrying though: why didn't Travis catch this?

**Comment by akien-mga** [comment]
> What's more worrying though: why didn't Travis catch this?

Travis doesn't build for Android or for Javascript (both required toolchains are completely overkill for CI sadly), which are the two platforms defining `NO_SAFE_CAST`.

**Comment by akien-mga** [comment]
What's more worrying to me: why didn't anyone report the build issue? :p

**Comment by hpvb** [comment]
Uch, yeah, never mind. *sleepytime* 🥇

**Pull request merged**
