### PR TITLE
Use C++ system headers in `editor/`, `drivers/`, and `servers/`

### PR DESCRIPTION
**Pull request by sondredl**

### CODE REVIEW

**Comment by adamscott** [comment]
Please add descriptions to your PRs (#98881, #98906, and #98908). 

We need to understand the intend and the rationale behind the submitted PRs. You need to explain also why should we merge your PR too.

**Comment by adamscott** [comment]
@sondredl Also, are https://github.com/godotengine/godot/pull/98906 and https://github.com/godotengine/godot/pull/98908 superseding https://github.com/godotengine/godot/pull/98881?

**Comment by sondredl** [comment]
> Please add descriptions to your PRs (#98881, #98906, and #98908).
> 
> We need to understand the intend and the rationale behind the submitted PRs. You need to explain also why should we merge your PRs too.

The intent should be discussed #98881, but in sum, code quality improvement is the intent, and why i think they should be merged.

**Comment by sondredl** [comment]
> @sondredl Also, are #98905, #98906, and #98908 superseding #98881?
yes and no. #98881 got a workflow check error that does not make sense, and that i am not  able to reproduce. So I am trying to smoke out the issue. If there is a way to run all the workflow checks locally, please let me know.

**Comment by adamscott** [comment]
> > Please add descriptions to your PRs (#98881, #98906, and #98908).
> > We need to understand the intend and the rationale behind the submitted PRs. You need to explain also why should we merge your PRs too.
> 
> The intent should be discussed #98881, but in sum, code quality improvement is the intent, and why i think they should be merged.

Yes, but you need to repeat the arguments for each PR. When somebody new lands on your PR, they don't have the context of your other PRs.

**Pull request closed without merging**
