### PR TITLE
Replace the AssetLib tab icon with a less confusing design

### LINKED ISSUE #818: Tweak the AssetLib editor icon to not look like a padlock
I've been getting some feedbacks on Twitter about how the AssetLib icon looks like a padlock.
This might make it more difficult for users (it took me a while too) to find the link for AssetLib.
What do you think? :)

https://twitter.com/NebulaBytes/status/976096307629588480

### PR DESCRIPTION
**Pull request by Calinou**
This closes https://github.com/godotengine/godot-proposals/issues/818. Thanks to @aaronfranke for providing a modified icon (not shown on the screenshots below).

### Dark (100% editor scale)

Dark

### Light (200% editor scale)

Light

### CODE REVIEW

**Comment by aaronfranke** [comment]
Most images (and the bottom part of this image) have a 1-pixel border, but the top of the arrow is 2 pixels from the top of the image. I raised it by one pixel and I think it looks better.

Screenshot from 2020-06-19 18-29-45


[AssetLib.zip](https://github.com/godotengine/godot/files/4806897/AssetLib.zip)

**Comment by Calinou** [comment]
@aaronfranke I added your icon edit, thanks!

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
