### PR TITLE
FIX: instance-scene make parent as edited_scene if no parent selected.

### LINKED ISSUE #47605: Instance Scene Here doesn't work without node selected
**Godot version:**

ed2f51b

**Issue description:**

When you **Ctrl + Click** inside 2D editor and use the Instance Scene Here option
image
it won't work when you don't have any node selected in scene tree. After selecting scene you will see an error that a parent node doesn't exist.

When you select the other option (Add Node Here), the node will be added to scene root if nothing is selected. Instancing should do the same.

For reference, this functionality was added in #41437

### PR DESCRIPTION
**Pull request by Bhu1-V**
FIX: #47605

suggest if there are is a better way to check the condition.

### CODE REVIEW

**Comment by KoBeWi** [comment]
While this appears to be working fine, the code could be simplified a lot. I'd do something like
```
if (!parent) {
	parent = scene_tree->get_selected();
}

if (!parent) {
	parent = edited_scene;
}
```
And the `|| !edited_scene` part of the last condition can be removed.

**Review by KoBeWi — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
This is relevant for 3.x too, because it also fixes normal scene instancing.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
