### PR TITLE
Fix FileAccessUnix on OpenBSD where `UF_HIDDEN` isn't supported

### PR DESCRIPTION
**Pull request by omar-polo**
Part of the joint effort with @rfht to port Godot 4 on OpenBSD.

### CODE REVIEW

**Review by deralmas — APPROVED** [review]
I don't know much about OpenBSD.

That said, the reasoning makes sense, the manual indeed does not mention the flag and the patch is concise, so I say LGTM! :D

**Comment by omar-polo** [comment]
@Riteo  yup, there are both Godot 3.x and 4.x packages for OpenBSD.  We maintain some [local patechs](https://github.com/openbsd/ports/tree/master/games/godot4/patches) that when relevant (and time permitting) send individually as PR :)

**Comment by rfht** [comment]
We have a working port on OpenBSD that includes this patch to  actually build it. (read-only GH mirror at: https://github.com/openbsd/ports/tree/master/games/godot4)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
