### PR TITLE
Support for PowerA Xbox One Mini Wired Controller

### PR DESCRIPTION
**Pull request by BuzzBurrowes**
Another joypad for Linux

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request!

The game controller database file comes from the [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) repository., so you should open a pull request there. Otherwise, your changes will be lost when we update the included version to match the upstream version.

**Comment by BuzzBurrowes** [comment]
> **Edit:** It seems this was added upstream already, but we haven't synchronized the mapping file yet: https://github.com/gabomdq/SDL_GameControllerDB/pulls?q=is%3Apr+sort%3Aupdated-desc+PowerA+is%3Aclosed

Slightly different than that one, but I submitted a pull request to SDL_GameConbtrollerDB, and it has been accepted and merged, so we should be all set. Thanks.

**Comment by Calinou** [comment]
Superseded by https://github.com/gabomdq/SDL_GameControllerDB/pull/453. Thanks for the contribution :slightly_smiling_face:

**Comment by akien-mga** [comment]
FYI, I'm syncing the DB with latest upstream `master` in #47683.

**Pull request closed without merging**
