### PR TITLE
Bug Fix: On Windows, the value of `p_flags` used in _create_window is derived from `WindowFlagsBit` instead of `WindowFlags`.

### PR DESCRIPTION
**Pull request by Cliear**
Bug fix, restore the value to bit fields.

### CODE REVIEW

**Comment by akien-mga** [comment]
This seems sensible (pending review from @godotengine/windows), but the commit message should be edited to be made clearer. A commit message should give a clear description of what the commit fixes, not what it does in the code. It should give context on where the bug is being fixed too (Windows window styling).

What's the bug fixed by this change?

**Comment by YuriSizov** [comment]
@Cliear Hey there! Could you get back to us about this question?

> What's the bug fixed by this change?

This should also be clarified in the commit message and the PR title, as explained above.

**Comment by Cliear** [comment]
If I want to create a popup window, the value of `p_flags` looks like this:
`p_flags |= WINDOW_FLAG_POPUP_BIT`, and its value is 32 (0x20). 
When passing it as a parameter to the `_create_window` function, internally it uses `p_flags` to check whether the POPUP flag is set:
`p_flags & WINDOWS_FLAG_POPUP`, and its value is 5. 
Clearly, we cannot correctly identify whether the POPUP style should be used for the window.

**Comment by Malcolmnixon** [comment]
The code looks correct based on the `p_flags` parameter being the bit-wise form of the flags, and on how the `Window::_make_window()` method converts `WindowFlags` (or `Window::Flags`) into `WindowFlagBit` values:
https://github.com/godotengine/godot/blob/fe01776f05b1787b28b4a270d53037a3c25f4ca2/scene/main/window.cpp#L580-L585

With this change I can confirm that:
- A window created with `set_flag(Window.FLAG_POPUP, true)` has `p_no_activate_focus` = true
- A window created without `set_flag(Window.FLAG_POPUP, true)` has `p_no_activate_focus` = false

Conversely without this PR I can confirm that `Window.FLAG_POPUP` incorrectly fails to set `p_no_activate_focus`.

My test project didn't do anything useful with the window, so I can't say what the actual side-effect on a windowed GUI application would be.

**Pull request closed without merging**
