### PR TITLE
miniupnpc: Update to version 2.2.6

### PR DESCRIPTION
**Pull request by Chubercik**
Release files: https://github.com/miniupnp/miniupnp/releases/tag/miniupnpc_2_2_6

Changelog: https://github.com/miniupnp/miniupnp/blob/miniupnpc_2_2_6/miniupnpc/Changelog.txt

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good!

Also needs this change:
```diff
diff --git a/COPYRIGHT.txt b/COPYRIGHT.txt
index b620f67bc9..bb29c88443 100644
--- a/COPYRIGHT.txt
+++ b/COPYRIGHT.txt
@@ -350,7 +350,7 @@ License: CC0-1.0
 
 Files: ./thirdparty/miniupnpc/
 Comment: MiniUPnP Project
-Copyright: 2005-2023, Thomas Bernard
+Copyright: 2005-2024, Thomas Bernard
 License: BSD-3-clause
 
 Files: ./thirdparty/minizip/
```

**Comment by Chubercik** [comment]
My bad, I keep forgetting 😅

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Pull request merged**
