### PR TITLE
Use `Del` key to delete folders and files and `F2` to rename them.

### PR DESCRIPTION
**Pull request by Nufflee**
Git history is a bit messy but I promise I'll get better at branching! :)

### CODE REVIEW

**Comment by reduz** [comment]
This is a terrible idea because there are many controls that use the delete keyword, such as scene tree, graph edits, animation editor, blend space editor, etc. To fix this properly, a system needs to be implemented so there is a global "please deselect your stuff because i am selecting" where everything interacts properly. I have this noted down to do before alpha.

**Comment by Nufflee** [comment]
@reduz  But this only works when FileSystem control is selected but I might be missing what you're saying.

**Comment by reduz** [comment]
Exactly, and this is why it's confusing

**Comment by aaronfranke** [comment]
@Nufflee Run `git rebase -i HEAD~10` and change the most recent commits from "pick" to "fixup" and they will be squashed together.

**Comment by Nufflee** [comment]
@aaronfranke Thanks for the tip!

**Comment by akien-mga** [comment]
This really needs to be rebased before it can be further reviewed, it's not really readable as is.

**Comment by akien-mga** [comment]
Closing for now as it's not in a mergeable state.

If the feature is wanted, either OP or another contributor are welcome to open a new PR with squashed commits.

**Comment by aaronfranke** [comment]
Removing the "salvageable" label because this feature is already implemented in the current version of Godot.

**Pull request closed without merging**
