### PR TITLE
Device Input dialog now uses containers

### LINKED ISSUE #6030: Input Map dialog messed up.  2.1RC2
Mac OSX El Capitan. Godot 2.1 RC2

I wanted to add an input map for a joystick button, but the dialog to do so is compressed.

-Go to Project Settings.
-Go to the "Input Map" tab.
-Press "+" on any input and choose "Joy Button" or "Joy Access".
-The little window that lets you choose which joystick and which button is messed up.

screen shot 2016-08-03 at 23 35 12

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #6030

**Do Not Merge!:** There is still a problem that should be fixed before merging this:

Sometimes the dialog size is not correctly calculated on popup:

After dragging the dialog, the size is adjusted correctly:

### CODE REVIEW

**Comment by neikeq** [comment]
I don't want to sound too pushy, but IMO using containers in WindowDialog, AcceptDialog and ConfirmDialog should fix al these problems.

**Comment by neikeq** [comment]
BTW, the problem mentioned only happens in HiDPI mode so it's already better than it was before. It would still be good if I could find a way to solve it...

**Comment by reduz** [comment]
Yeah I think they should recognize children properly and make them work as
containers without having to use set_child_rect(). It's quite a lot of work
to change everywhere but given most use set_child_rect it should be easier.
I will add an item for 3.0 to make them work more like containers.


On Fri, Aug 5, 2016 at 8:52 AM, Ignacio Etcheverry <notifications@github.com

**Comment by neikeq** [comment]
So are we fine with leaving it as is in this?

**Comment by neikeq** [comment]
I am merging this, since the remaining issue won't be fixed until 3.0 and it's not a big impediment.

@akien-mga It would be great to cherry-pick this for 2.1.1

**Pull request merged**
