### PR TITLE
GDScript: Fix local can be used before declared

### LINKED ISSUE #54944: The Callable obtained is unusable
### Godot version

4.0-dev.20211108

### System information

Ubuntu20.04,headless,HD Graphics 530

### Issue description

I'm using Callable in Godot4.The following code works well:
```
func test():
	print("in test")

func _ready():
	print("_ready:")

	print(test)
	test.call()

```
output:
```
_ready:
Node(Node2D.gd)::test
in test
```

But when I write this:
```
func test():
	print("in test")

func _ready():
	print("_ready:")

	print(test)
	print(typeof(test))

	var test=12
```
Output:
```
_ready:
null
0
```
 **Similarly, when I get a function with the same name before a variable declaration, I get null**
### Is it working properly?
**If my grammar is OK,Why do I get null instead of Callable?**
**Is my grammar wrong? Godot4 doesn't have any reminders!**

### Steps to reproduce

run this in 4.0.dev
```
func test():
	print("in test")

func _ready():
	print("_ready:")

	print(test)
	print(typeof(test))

	var test=12
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dalexeev**
Closes #54944.

### CODE REVIEW

**Comment by akien-mga** [comment]
Intuitively, this makes the behavior unexpected for me. While shadowing a member variable should be avoided (and it raises a warning), _until_ the local variable is defined, I would expect `x` in your example to be the member variable - it hasn't been shadowed by a local yet.
```gdscript
var x = 1

func test():
	print(x)
	@warning_ignore("unused_variable", "shadowed_variable")
	var x = 2
```

I'd expect this to print 1, not raise an error IMO. It can however emit a warning for shadowed variable, which it seems to.

That being said, the behavior implemented here seems consistent with Python 3:
```python3
>>> x = 1
>>> def test():
...     print(x)
...     x = 2
...     print(x)
... 
>>> test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test
UnboundLocalError: local variable 'x' referenced before assignment
```

But it's worth noting that there is greater ambiguity in Python as there's no `var x` syntax to declare a _new_ member/local.
In GDScript, we can access and modify the member variables without shadowing them.

**Comment by dalexeev** [comment]
JavaScript:



> In GDScript, we can access and modify the member variables without shadowing them.

You can use `self.a` to access a shadowed member.

**Comment by kleonc** [comment]
And in C++, C# it works as expected according to [akien's comment](https://github.com/godotengine/godot/pull/73427#issuecomment-1455794985).

I think when making decision what's the most expected behavior in here we should look at the GDScript itself. And here, in case there's no shadowing involved, the local variable (its identifier) is said to be "not declared in the current scope" if it's used before the declaration:
Godot_v4 0-stable_win64_cN5n0rrNd1
Godot_v4 0-stable_win64_ohNkK3RDj9


So conceptually (according to the above) the local variable doesn't exist before the declaration (assuming we treat variable/identifier as one), which means there's no local variable to shadow anything yet. Currently this PR is inconsistent with that.

Either other places should be made consistent with this PR (e.g. the above error should be like `Cannot use identifier "a" before it was declared.`), or it should be made to work [like akien suggested](https://github.com/godotengine/godot/pull/73427#issuecomment-1455794985) (which I'd prefer as it's intuitive for me too).

**Comment by dalexeev** [comment]
> And here, in case there's no shadowing involved, the local variable (its identifier) is said to be "not declared in the current scope"

It's just a wrong error message, this PR fixes that case too.

**Comment by vnen** [comment]
I agree with @akien-mga here, the member should be accessible before declaration of the local. That's the most intuitive and how it works in 3.x. It was broken by the same cause of this bug, so it was an oversight.

Maybe we can merge this as it is to fix the bug, but at some point soon we need to fix the behavior.

**Comment by dalexeev** [comment]
It seems wrong to me that the same identifier within the same scope can have different meanings. Even if it worked in 3.x, I think it should be an error, like in JavaScript and Python. There is no right use case for this behavior, you must either choose a different name for the identifier, or specify `self` to distinguish the member from the local.

**Comment by dalexeev** [comment]
> Bringing this up again. I can accept this since it's more restrictive (and the alternative is already not working anyway). But one thing that we may discuss is what is the "scope".

Done. I added a check for variables declared in the parent block below the current block. The check is not possible in the parser, only in the analyzer.

I think with this additional restriction we shouldn't cherry-pick this to 4.0.

**Comment by capnm** [comment]
> I'd expect this to print 1, not raise an error IMO.

Agree.

See a correct **[go](https://go.dev/play/p/xfvgjsqFL5s)** program (without error or any warnings):
```go
package main
import "fmt"

var a = "Martin!"

func main() {
    fmt.Println("Hi, ", a)
    var a = 2    
    fmt.Println(a)
    if a == 2 {
    	var a = 42
    	fmt.Println(a)
    }
}

Hi,  Martin!
2
42

```

**Comment by adamscott** [comment]
@vnen @dalexeev Is it ready to be merged / stable enough in 4.1?

**Comment by dalexeev** [comment]
@adamscott From the technical side, I think it's ready to be merged. But some people prefer to be able to shadow identifiers and treat scopes differently. Perhaps this should be discussed at the GDScript team meeting?

**Comment by adamscott** [comment]
I put the milestone to 4.2 as this is a pending discussion. Thanks @dalexeev.
I added this PR to [the PRs to team review](https://github.com/orgs/godotengine/projects/55).

**Comment by dalexeev** [comment]
### Summary for future PR review meeting

#### Questions for discussion

1. Scope of local variable/identifier.
2. Identifier shadowing.

#### Common points for both options

1. A local variable can shadow member variable.
3. In one block, several variables with the same name cannot be defined (with shading of the previous one, exists in some programming languages).
4. A local variable cannot shadow a parent block's local variable, this is considered an error.
5. Two blocks, neither of which is a parent of the other (for example, sibling blocks), can have variables with the same name.

#### Current state

The parser/analyzer and the compiler/runtime treat variable scopes differently, which leads to non-obvious behavior and bugs in edge cases related to variable shading and its use before definition.

Also shadowing an identifier is one of the most common and hardly noticeable mistakes. We have a warning when a local variable shadowing a member variable, but as the issue showed, users don't really pay attention to it, as they first notice the bug.

#### Options



_Light background indicates a variable scope._
_Dark background indicates scope before declaration (Option 2 only)._
_Strikethrough text indicates errors._

**Option 1 (mentioned above):** A local variable exists from definition to the end of the block in which it is defined.

**Option 2 (this PR):** A local variable exists in the block in which it is defined, but cannot be used until it is defined. (The same as Option 1, but with an additional restriction.)

Pros of Option 2:

1. Reducing the cases where the same identifier in nearby places means different things.
2. Simple implementation. Minimal changes in the parser/analyzer, no changes in the compiler.

**Comment by nlupugla** [comment]
Re the loop example, I would say option 3 makes the most sense to me, ie: `1 2 2 2 2 2`.

In the same way that the parser is only allowed to look 1 token behind because humans reading the code have a small short-term memory, I think analysis like this should be consistent with what a human with a short memory reading the code would expect.

Similarly, maybe a good principle to follow would be that, to the extent possible, code "in the future" shouldn't raise an error on code "in the past".

**Comment by dalexeev** [comment]
> Re the loop example, I would say option 3 makes the most sense to me, ie: `1 2 2 2 2 2`.

In my opinion, this is non-obvious behavior. I don't think there are many languages that would implement it this way. In addition, this will significantly and unnecessarily complicate the implementation, since we would have to generate different code for the first and subsequent iterations of the loop.

**Comment by kleonc** [comment]
> ```gdscript
> var a = 1
> 
> func _ready():
>     for _i in 3:
>         print(a)
>         var a = 2
>         print(a)
>     
> ```
>
> What should the following code output:
> 
>     1. The error "Cannot use local variable "a" before it was declared.";
> 
>     2. `1 2 1 2 1 2`;
> 
>     3. `1 2 2 2 2 2`?

Poll:
1. :tada:
2. :rocket:
3. :heart:

**Comment by dalexeev** [comment]
I want to clarify: the current behavior is not Option 1 and not Option 2. It's an Option 0 that has a bug due to the fact that the parser/analyzer and compiler/runtime treat scopes differently.

To me, both options seem acceptable, but in this PR I made Option 2 because it's easier to implement and more restrictive. We _can_ choose Option 1 if we decide it's better. It just takes time for me or someone else to implement it.

There is also an "Option Go" (see [comment](https://github.com/godotengine/godot/pull/73427#issuecomment-1594850045)), which suggesting the ability to shadow local variables. But this is not currently possible and is not suggested in either Option 1 or Option 2. Therefore, we do not consider the option in this discussion.

**Comment by nlupugla** [comment]
Out of curiosity, just tested this in Python and its approach seems to be option 1.

image

image

to be clear, I'm not arguing for option 1 necessarily, just presenting this test as some more data to consider.

**Comment by dalexeev** [comment]
> Out of curiosity, just tested this in Python and its approach seems to be option 1.

**1**\. The error "Cannot use local variable "a" before it was declared."; — is **Option 2**.
**2**\. `1 2 1 2 1 2`; — is **Option 1**.

**Comment by AThousandShips** [comment]
Probably because you swapped the order for your "what should it print"

**Comment by nlupugla** [comment]
Oh, I see what I did. When I said option 1, I meant option 1/3 of the poll, not option 1/2 as outlined in the summary. I'll edit my post to clarify.

**Comment by dalexeev** [comment]
Obviously shadowing is a bad practice that we should not encourage. But should we disallow it? We already have a warning (which some users may not notice, but is this a problem?). It's a question of balance between "language allows you to shoot yourself in the foot" and "language is unnecessarily intrusive."

It's funny, but after discussion I leaned towards the intuitive option.

**Comment by nlupugla** [comment]
I think it would be useful to see how more languages handle a similar situation.

Normally, I would advocate for more help from the analyzer over less, but something feels "off" about allowing code "in the future" to affect code "in the past".

**Comment by vnen** [comment]
> Obviously shadowing is a bad practice that we should not encourage. But should we disallow it? We already have a warning (which some users may not notice, but is this a problem?).

I don't think we should disallow shadowing of class variables, but we should still disallow shadowing of outer blocks. But this PR is not really about shadowing in general, it is about a solution to an issue that it made it more restrictive than it was before (hence the generated discussion).

So we if there are concerns about shadowing in general we should go the usual route of proposal and discussion.

This is PR is actually about lifecycle of locals: (1) do they exist only after they're declared or (2) are they present anywhere in the scope no matter where they are declared.

I still think (1) is more intuitive but (2) is more restrictive which is better overall as it allows less mistakes.

> Normally, I would advocate for more help from the analyzer over less, but something feels "off" about allowing code "in the future" to affect code "in the past".

While you are writing a function linearly this might feel odd, but if you think that you may edit the function multiple times in the future then the actual line order become less relevant. Once you start editing it, you may not be aware anymore of what came before so raising an error in this case is more likely to help you than getting in your way.

**Comment by dalexeev** [comment]
**JavaScript**

I'm pretty sure the idea came to me because of JavaScript.

<details>
<summary>Example 1</summary>

```javascript
let a = 1;

function _ready() {
    // Uncaught ReferenceError: can't access lexical declaration 'a' before initialization.
    let a = a + 1;
    console.log(a);
}

_ready();
```

</details>

<details>
<summary>Example 2</summary>

```javascript
let a = 1;

function _ready() {
    for (let i = 0; i < 3; i++) {
        // Uncaught ReferenceError: can't access lexical declaration 'a' before initialization.
        console.log(a);
        let a = 2;
        console.log(a);
    }
}

_ready();
```

</details>

**Python**

To be fair, Python doesn't have a variable declaration keyword (`var`/`let`).

<details>
<summary>Example 1</summary>

```python
a = 1

def _ready():
    # UnboundLocalError: cannot access local variable 'a' where it is not associated with a value
    a = a + 1
    print(a)

_ready()
```

</details>

<details>
<summary>Example 2</summary>

```python
a = 1

def _ready():
    for i in range(3):
        # UnboundLocalError: cannot access local variable 'a' where it is not associated with a value
        print(a)
        a = 2
        print(a)

_ready()
```

</details>

**C++**

<details>
<summary>Example 1</summary>

```c++
#include <stdio.h>

int a = 1;

int main() {
    printf("%d\n", a); // 1
    int a = a + 1; // The right "a" is a local variable, not a global one!
    printf("%d\n", a); // 32745

    return 0;
}

```

</details>

<details>
<summary>Example 2</summary>

```c++
#include <stdio.h>

int a = 1;

int main() {
    for (int i = 0; i < 3; i++) {
        printf("%d\n", a);
        int a = 2;
        printf("%d\n", a);
    }
    // 1 2 1 2 1 2

    return 0;
}
```

</details>

**Comment by dalexeev** [comment]
v3.5.2.stable.official:

<details>
<summary><b>Test 1.</b> Using a variable before the definition when there is a shadowed member</summary>

```gdscript
extends Node

var a = 1

func _ready():
    print(a) # Prints 1.
    var a = 2
    print(a) # Prints 2.
```

</details>

<details>
<summary><b>Test 2.</b> Same as T1 in <code>for</code> loop</summary>

```gdscript
extends Node

var a = 1

func _ready():
    for _i in 3:
        print(a)
        var a = 2
        print(a)
    # Prints 1 2 1 2 1 2.
```

</details>

<details>
<summary><b>Test 3.</b> Definition in nested block before definition in outer block</summary>

```gdscript
extends Node

func _ready():
    if true:
        var a = 1
        print(a) # Prints 1.
    var a = 2
    print(a) # Prints 2.
```

</details>

<details>
<summary><b>Test 4.</b> Definition in nested block after definition in outer block</summary>

```gdscript
extends Node

func _ready():
    var a = 1
    print(a)
    if true:
        var a = 2 # Compile time error: Variable "a" already defined in the scope (at line 4).
        print(a)
```

</details>

<details>
<summary><b>Test 5.</b> Using the same variable in the initializer when there is a shadowed member</summary>

```gdscript
extends Node

var a = 1

func _ready():
    print(a)
    var a = a + 1 # Runtime error: Invalid operands 'Nil' and 'int' in operator '+'.
    print(a)
```

</details>

The behavior corresponds to Option 1 ("intuitive"), except for Test 5.

**Pull request closed without merging**
