### PR TITLE
Rename `hint_albedo`, `hint_white/black` in shaders

### LINKED ISSUE #2323: Rename hint_albedo for sRGB -> Linear color conversion in shaders
### Describe the project you are working on
A landscape visualization using a variety of custom shaders; this is not project-specific though.

### Describe the problem or limitation you are having in your project
As is evident in the comments of the [original issue for this](https://github.com/godotengine/godot/issues/24992#issuecomment-782566666) and other posts such as https://github.com/godotengine/godot/issues/11381 or https://godotdevelopers.org/forum/discussion/19049/custom-splatmap-shader-does-not-work-correctly-in-3-0-solved, many people (myself included) are initially confused by the sRGB -> Linear color space conversion in shaders, which is done as follows:

```
uniform sampler2D tex : hint_albedo;
```

The updated docs do make this clearer, but a `hint_` still isn't where many people would intuitively search for when the 'colors look wrong'. In my experience, throughout the engine, 'hints' are usually something that make development easier, e.g. by providing better autocompletion or by exposing something to the editor in a more convenient way. It's unusual for a hint to be _required_ for producing a correct output.

In order to make shaders slightly more approachable, I propose renaming this to something that is more obvious to newcomers.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename the keyword. Simply `uniform sampler2D tex : albedo;` would already be better in my opinion; something like `uniform sampler2D tex : color_srgb;` may be even more intuitive. This would be easy to do, but it'd break compatibility.

I suppose this could also be handled completely differently, but it's just a minor issue with no need for a big restructure.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```
uniform sampler2D tex : albedo;
// or
uniform sampler2D tex : color_srgb;
```

These are just some of my ideas, maybe someone else can come up with something better.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
The default behavior will still be no conversion.

### Is there a reason why this should be core and not an add-on in the asset library?
The functionality of converting a texture from sRGB to Linear is already in the engine, this is just a rename of that.

### PR DESCRIPTION
**Pull request by Chaosus**
Approved changes from PR meeting (https://github.com/godotengine/godot-proposals/issues/2323#issuecomment-1118732462): 

- hint_albedo/hint_black_albedo/hint_color → source_color
- hint_black/hint_white → hint_default_black/hint_default_white

Closes https://github.com/godotengine/godot-proposals/issues/2323

### CODE REVIEW

**Comment by clayjohn** [comment]
Although not mentioned in the comment, the plan was also to replace ``hint_color`` with ``source_color``.

**Comment by Chaosus** [comment]
@clayjohn `hint_albedo` already has been renamed to `source_color`, to what rename of `hint_color`?

**Comment by clayjohn** [comment]
They should both be renamed to ``source_color``

**Comment by Chaosus** [comment]
@clayjohn Done. Check if you want.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by GiantBlargg** [comment]
The replacement for `hint_black_albedo`, `source_color, hint_default_black` doesn't work, as the uniform only stores the most recent hint.

Hint is overwritten here: https://github.com/Chaosus/godot/blob/a8bbe570caadd0161a8db9c980296b111042a6b8/servers/rendering/shader_language.cpp#L8235-L8262

**Pull request merged**
