### PR TITLE
mono: New Color methods:  Darkened, Lightened and ToRgba32

### PR DESCRIPTION
**Pull request by KellyThomas**

### CODE REVIEW

**Review by neikeq — APPROVED** [review]

**Comment by aaronfranke** [comment]
:thinking: https://github.com/godotengine/godot/pull/18282

I'll rebase this soon...

**Comment by neikeq** [comment]
@aaronfranke Looks like I missed that one... and I forgot the version bump 😐

**Comment by hpvb** [comment]
Cherry picked into 3.0.3

**Comment by aaronfranke** [comment]
Since this PR renames a method (`To32()`) it probably shouldn't be cherrypicked unless https://github.com/godotengine/godot/pull/18282 is also merged and cherrypicked.

**Pull request merged**
