### PR TITLE
New shader feature: change the colour of shadows on a per-material basis

### PR DESCRIPTION
**Pull request by SaracenOne**
This is another tiny extension to the pre-existing custom shader system to allow for setting the colour of shadows per-material. I'm using this because I'm working on some NPR shaders and was able to get much better results having this more fine-grained control of shadowing.

### CODE REVIEW

**Comment by n-pigeon** [comment]
Woo this is awesome!

**Comment by reduz** [comment]
oh ok. I guess it makes sense. Future deferred renderer can detect this and use the forward path. Could you fix the conflicts? this way I can re-merge it

**Comment by SaracenOne** [comment]
Sure thing.

**Comment by SaracenOne** [comment]
Okay, should be resolved now.

**Comment by akien-mga** [comment]
Git tip: Try to use ```git pull --rebase``` instead of just ```git pull``` when syncing your branch, it usually avoids the creation of these useless "Merge branch whatever" commits. I still don't understand why --rebase is not the default git pull behaviour though, but wll, git's CLI is a complete mess :)

**Comment by SaracenOne** [comment]
Yes, I always thought those messages were kind of redundant, didn't know there was a way of avoiding them. I'll try and use it in future.

**Comment by akien-mga** [comment]
Here I put this in my ~/.gitconfig:
```
[alias]
    up = pull --rebase
```
That's pretty convenient :D (especially coming from SVN where I was used to svn up compulsively).

**Comment by SaracenOne** [comment]
Okay, I've set it up. So this presumably edits out merge commits then?

**Comment by akien-mga** [comment]
If you run 'git up' yes.

**Comment by akien-mga** [comment]
Based on this, I guess I can safely merge it:
> Could you fix the conflicts? this way I can re-merge it

**Pull request merged**
