### PR TITLE
[macOS / Windows] Add optional ANGLE support.

### PR DESCRIPTION
**Pull request by bruvzg**
A new version of https://github.com/godotengine/godot/pull/54914

Screenshot 2023-01-31 at 23 55 21

Screenshot_20230202_094624

Pre-build ANGLE libraries are required, build it [from source](https://chromium.googlesource.com/angle/angle/+/HEAD/doc/DevSetup.md) or get from the [CEF minimal distribution](https://cef-builds.spotifycdn.com/index.html). Headers are included.

---

### To test it with upstream ANGLE:

- Build Godot with additional options: 
```
    opengl_implementation=angle extra_suffix=angle
```
- Copy `libEGL.dylib` and `libGLESv2.dylib` to the .app bundle `Frameworks` folder (macOS).
- Copy `libEGL.dll` and `libGLESv2.dll` to the executable folder (Windows).

---

ANGLE platform type can be selected by running Godot with `--angle-platform-type type` command line argument.
- On macOS, valid `type` values are: `metal` (default) and `opengl`.
- On Windows, valid `type` values are: `d3d11` (default), `vulkan`, and `opengl`.

### CODE REVIEW

**Comment by bruvzg** [comment]
> Mh, I'm not sure, but this looks like this works with EGL? I'm not sure if ANGLE magic is changing things up. Couldn't this be based somehow on https://github.com/godotengine/godot/pull/68944? If there's no magic behind the scenes we could avoid having multiple EGL manager implementations floating around when the time comes.

Apart for a few extra attributes for the display creation and two Objective-C lines which can be moved to the DisplayServer, it should be generic EGL, so I guess it can use the same GLManager. I'm not sure about GLAD (it does not support ANGLE platform extensions, but it's probably only a few enums), I'll check it out.

**Comment by bruvzg** [comment]
> Couldn't this be based somehow on https://github.com/godotengine/godot/pull/68944?

Updated to use common EGL manager based on #68944 and GLAD (dylibs are no longer necessary to build Godot, only to run with GL renderer). Since it's using GLES not GL I have added a few extra virtual methods to the EGL manager to configure API type and arguments for display and context.

GL/GLES defines and includes will need a bit of cleanup, it's a mess right now.

**Comment by bruvzg** [comment]
Added `EGL_ANDROID_blob_cache` caching to mitigate slow ANGLE shader conversion, now it starts instantly on the subsequent runs.

**Comment by clayjohn** [comment]
As a note, our original plan for ANGLE was to utilize it as an optional driver (like how you will be able to select between Vulkan and D3D12). How difficult do you think it would be to make angle/non-angle selectable in the project settings instead of making it a compile time option?

https://github.com/godotengine/godot-proposals/issues/4261

**Comment by bruvzg** [comment]
> How difficult do you think it would be to make angle/non-angle selectable in the project settings instead of making it a compile time option?

ANGLE use GLES, native desktop use GL, system GL headers will conflict, normal GLAD headers will also conflict. It's likely will require making a two full independent copies of `RasterizerGLES3` for it to work (or at least making a modified version of GLAD, with the merged API and completely getting rid of all system GL header usage).

**Comment by bruvzg** [comment]
> or at least making a modified version of GLAD, with the merged API and completely getting rid of all system GL header usage

Seems like GLAD 2 have a spacial mode for this, I guess I'll try to modify RasterizerGLES3 to use it (replacing all `GLES_OVER_GL` with the runtime checks and cleaning up includes to use the same built-in one).

**Comment by bruvzg** [comment]
> How difficult do you think it would be to make angle/non-angle selectable in the project settings instead of making it a compile time option?

Got it working on macOS, so it is possible. Need a lot of cleanup, and some extra work to make sure it is working on mobile and web, since these do no use GLAD. Also, I have not touched OpenXR stuff at all. But here's a draft branch:

https://github.com/bruvzg/godot/tree/angle%2B%2B

An `--rendering-driver opengl3_angle` / `--rendering-driver opengl3` argument can be used to select ANGLE or native GL. It's currently not exposed to UI/project settings. Maybe it should use `rendering_method = gl_native / gl_angle` instead of renderer name?

**Comment by bruvzg** [comment]
Superseded by https://github.com/godotengine/godot/pull/72831

**Pull request closed without merging**
