### PR TITLE
Fix Editor crash when vertex count is 65536

### LINKED ISSUE #68923: Crash in editor when using PlaneMesh
### Godot version

4.0.beta5

### System information

Windows 11

### Issue description

The editor crashes when the following settings are made in PlaneMesh.
- Subdivide Width: 254
- Subdivide Depth: 254

Perhaps, it seems to crash when the number of vertices in the mesh is just 65536.

### Steps to reproduce

1. Open reproduction project
2. Select "MeshInstance3D" node
3. In inspector, extend "Mesh" property
4. Set "Subdivide Depth" to 254

### Minimal reproduction project

[PlaneMeshBug.zip](https://github.com/godotengine/godot/files/10050044/PlaneMeshBug.zip)

### PR DESCRIPTION
**Pull request by BharatSahlot**
Fix #68923

Not sure if this is best fix since @ueshita came up with another fix in https://github.com/ueshita/godot/commit/454116716e7934f6bd80d7040a2c06a7c18d4c64.

### CODE REVIEW

**Review by clayjohn — CHANGES_REQUESTED** [review]
This is the correct fix. 

https://github.com/ueshita/godot/commit/454116716e7934f6bd80d7040a2c06a7c18d4c64 makes it so that 16 bit indices will be used when the vertex count is 65536, but 65536 cannot be stored in a 16 bit integer Accordingly, it will overflow and the last index will use vertex 0 instead of vertex 65536.

However, before merging, this fix also needs to be added here: https://github.com/godotengine/godot/blob/11e1c83309e7e7c15018c8b2c6456fa294116244/drivers/gles3/storage/mesh_storage.cpp#L222 
and here:
https://github.com/godotengine/godot/blob/11e1c83309e7e7c15018c8b2c6456fa294116244/drivers/gles3/storage/mesh_storage.h#L363

When you make the change make sure you use ``git commit --amend`` to alter the original commit instead of making a second commit. More details on modifying a PR can be found here: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request

**Comment by BharatSahlot** [comment]
Made the changes, found two more `<= 65536`. Fixed them in the commit.

**Comment by adamscott** [comment]
Not sure if this is the responsibility of this PR, but shouldn't `65536` be a constant? I don't really like the idea of `65536` being compared as a magic number. This should be `<= UINT16_MAX`.

**Comment by souplamp** [comment]
> Not sure if this is the responsibility of this PR, but shouldn't `65536` be a constant?

I found a few other instances of `65536` being used over `UINT16_MAX`. I think that could be another PR altogether.

**Comment by clayjohn** [comment]
After seeing the other places you updated I realized that we are **not** looking at the maximum vertex _index_ we are looking at the vertex array _length_. So my comment above is actually wrong. With an array of length 65536, the largest index is 65535 which **can** fit inside a uint16_t. Which means we need to be updating the places where @ueshita flagged in https://github.com/ueshita/godot/commit/454116716e7934f6bd80d7040a2c06a7c18d4c64 (i.e. the places that are using 32 bits for 65536 length vertex arrays). 

My apologies for this oversight. Unfortunately, now using UINT16_MAX doesn't fit as nicely either. I guess we should be doing ``if (length -1 <= UINT16_MAX)`` Although that may be worse than ``if (length <= (1 << 16))``

**Comment by BharatSahlot** [comment]
Yes my bad. In this case @ueshita makes a PR?

**Pull request closed without merging**
