### PR TITLE
GDScript: Add return type covariance and parameter type contravariance

### LINKED ISSUE #7450: Support covariant return types for overriding functions
### Describe the project you are working on

I am working on an addon that manages RPG data.

### Describe the problem or limitation you are having in your project

It is currently impossible to specify a more 'specific' type of a return value of any overriden function, if that returned value is a subtype of the overriding function. Many common languages like Java and ~C#~ C++ support such feature ([see table](https://github.com/godotengine/godot-proposals/issues/7450#issuecomment-1666951033)), as it unlocks additional functionality for polymorphism.

Currently, Godot 4.1 produces an error like this:

Screenshot 2023-08-05 151230

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Support covariant return types on functions if the return value is a sub-type of the overriding function's return value.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This script does not compile as part of Godot 4.1 but after this proposal was implemented it would work as expected:
```gdscript
class BaseClass extends RefCounted:

	func greetings() -> void:
		print("Hello!")

class SubClass extends BaseClass:
	
	func greetings() -> void:
		print("Hello Sub Class!")

class BaseGreeting extends RefCounted:
	
	func get_obj() -> BaseClass:
		return BaseClass.new()

class SubGreeting extends BaseGreeting:
	
	func get_obj() -> SubClass:
		return SubClass.new()

func _ready():
	var base:BaseGreeting = SubGreeting.new()
	var obj = base.get_obj()
	obj.greetings() # should print 'Hello Sub Class!'
```
Example project of the above:

[Covariant-Example.zip](https://github.com/godotengine/godot-proposals/files/12267448/Covariant-Example.zip)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't since this is a GDScript core language feature that cannot be worked around easily.

### Is there a reason why this should be core and not an add-on in the asset library?

Cannot be done via addons nor GDExtension.

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes godotengine/godot-proposals#7450.
* Supersedes #80457.

CC @bitbrain @adamscott @vonagam

### CODE REVIEW

**Comment by bitbrain** [comment]
@dalexeev thank you so much for this! I remember from our discussion that in the codebase we have several places where we need to know if "something is a covariant of something else":
1. would it make sense to create a dedicated method for it (used by the analyzer) rather than having it baked into the analyzer?
2. are there currently other places in the codebase that could benefit from this method? I remember you mentioned that there are multiple places where we may require to check for "is type X of type Y"

**Comment by dalexeev** [comment]
> would it make sense to create a dedicated method for it

Currently no, we are close to feature freeze and release, this is not the time for unreasonable changes. But I have two draft branches: one is an attempt to [refactor `is_type_compatible()` method](https://github.com/dalexeev/godot/tree/gds-refactor-is-type-compatible) and the other is an attempt to [refactor `DataType` class](https://github.com/dalexeev/godot/tree/gds-refactor-datatype).

**Comment by dalexeev** [comment]
* See also #79765.

**Review by vnen — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
