### PR TITLE
Highlight GLES3 functions in the visual shader member panel

### PR DESCRIPTION
**Pull request by Chaosus**
If the current driver is GLES2 they will be highlighting in red, indicates that if you try to create they will not work in this mode. Otherwise they will be green indicates that even if they are available they are still may be dangerous )

image

I've also removes "(GLES3 only)" text from the description information - now this string will be added to the beginning of the description on fly

### CODE REVIEW

**Comment by Calinou** [comment]
What about using the warning color (which is yellow) when using the GLES3 renderer?

**Comment by Chaosus** [comment]
@Calinou thanks )
image

**Comment by clayjohn** [comment]
Looks good to me!

**Comment by Chaosus** [comment]
I need this enhancement to continue to work on visual shaders + its have an approval + its nothing critical or leading to compatibility breakage => I think nothing wrong if I merge it myself

**Pull request merged**
