### PR TITLE
Implement debug memory marking

### PR DESCRIPTION
**Pull request by RandomShaper**
This consists in marking memory regions with certain specific values when they are (re)allocated or
freed in order to ease debugging of certain bugs, catching them as early as possible, detect
uninitialized variables, etc.

Some C++ implementations may already do this in debug mode, but the idea of this is to make it work
exactly the same regardless the platform/compiler/library.

```
ALLOCATED
+-------------------------+
| F1 F1 F1 F1 F1 F1 F1 F1 |
+-------------------------+

REALLOCATED (new size > old size)

/----------------- new size -----------------/
/------- old size -------/---- size diff ----/

+------------------------+===================+
|   current contents     | F2 F2 F2 F2 F2 F2 |
+------------------------+===================+

REALLOCATED (new size < old size)

/----------------- old size -----------------/
/------- new size -------/---- size diff ----/

+------------------------+···················+
|   kept contents        | F3 F3 F3 F3 F3 F3 :
+------------------------+···················+

FREED
+·························+
: F4 F4 F4 F4 F4 F4 F4 F4 :
+·························+
```

### CODE REVIEW

**Comment by lawnjelly** [comment]
Will this not get overwritten by the OS / runtime on configurations that do memory marking themselves? If that is the case it wouldn't make sense in that situation, although I don't know if this environment can be detected from scons or not.

If we mark the memory with something different from the OS / runtime, anything we write that detects 'our' codes won't work if their codes are different, so there may be an argument for sharing the same codes, although yours may be more helpful for detecting certain errors in e.g. vectors.

Here's some discussion of the microsoft ones:
https://stackoverflow.com/questions/127386/in-visual-studio-c-what-are-the-memory-allocation-representations

Personally I think such things can be very useful (also maybe something for detecting memory leaks), but I myself would like the option to be able to turn on and off irrespective of whether in debug or release build (might not want it slowing down debug builds unless I'm looking for such a bug, and might want it to catch a release build bug).

**Comment by RandomShaper** [comment]
Yes, the idea is having a feature for catching memory bugs when you are working simply (compiler + debugger with no extra tools) and that works the same everywhere. At least, I've found this useful in the past (2.1).

Now, it's certainly true that there are more sophisticated tools, but this shouldn't be a roadblock for using them. The `DEBUG_MEMORY_MARKING` define can be undefined if it somehow conflicts with anything some developer may be using (also it can be enabled for release builds).

Honestly, I'm not sure about which/how compilers/libraries will override this. I've tested it only on MSVC. **If anyone has more insight about this, I'd really be happy to hear**, so we can discuss how (and whether) to disable those and keep only this as the default one.

**Comment by aaronfranke** [comment]
@RandomShaper Is this still desired? If so, it needs to be rebased on the latest master branch (and the base branch needs to be changed to `master` instead of `vulkan`).

**Comment by aaronfranke** [comment]
@RandomShaper  Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by RandomShaper** [comment]
I have in my backlog plans to revive it, since I think it's really useful to catch and understand some memory errors, especially on platforms were you can't easily build with asan.

**Comment by RandomShaper** [comment]
I'm letting this go due to the lack of interest.

**Comment by Calinou** [comment]
If anyone is interested in salvaging this PR, this proposal is also related: https://github.com/godotengine/godot-proposals/issues/674

**Pull request closed without merging**
