### PR TITLE
Fix nodes selectable abnormally when using filter

### LINKED ISSUE #77905: NodePath filter failure after nodes filter used.
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 11

### Issue description

In the "Select a Node" windows, popped up when pressed the "Assign..." button of a `NodePath` property in the inspector.
Input any character in the "Filter Nodes" line, then clear it.

All ancestors of target type nodes become selectable.

I think it's because the correct result is supposed to be like this:
image

but the invalid ancestors, which should be leaved in the dialog but set to unselectable, are in the wrong state.

### Steps to reproduce

- Create a new project.
- Create a new scene like this.
image
- Select `BoneAttachment3D` node, turn on `Use External Skeleton`
image
- Hit the "Assign..." button, open the dialog, it's good at this moment.
image
- Input any character in the "Filter Nodes" line (like `d`).
image

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #77905

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by ajreckof — CHANGES_REQUESTED** [review]
I had worked on it before sleeping and thought I would post my PR when waking up as I was too sleepy and now there is another PR :(. Instead I'll review it 

Your whole block of code should be one line below (after the `set_visible`) this is because without it it gives this : 

https://github.com/godotengine/godot/assets/66184050/1ce57ba9-57ed-4198-81ee-e4379e5c12dd

The other solution is to remove the part in `_add_nodes` and instead call `_update_filter` when changing valid types. This would force consistency but would have different behaviour from what was before ie it would always show what is shown when adding a filter and then removing it. (this part could also be done even with the other solution to avoid duplicating code and ensure consistency)

The rest seems similar to what I did myself just had put a check to verify the node was found but I'm not sure it can happen so I don't think it is important

**Comment by YuriSizov** [comment]
Bump :)

**Comment by akien-mga** [comment]
Needs a rebase to fix CI, the doc checks were broken temporarily yesterday by another PR.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
