### PR TITLE
Focus selected node in scene tree

### PR DESCRIPTION
**Pull request by marynate**
Sometimes you know you have selected something, but just can't find it in scene tree

new "focus" button

Click to focus on selected item

And if it's collapsed

It'll be expanded for you

It also fixed #428 "in help tab node tree moving away when clicking"

### CODE REVIEW

**Comment by mamarilmanson** [comment]
<mamarilmanson> adolson|laptop, " clicking a node in the scene automatically selects it in the tree"
<mamarilmanson> doesn't seem like it... ?
<romulox_x> mamarilmanson, it does.  in 2d anyway, since that's what i've got open
* TonyMac has quit (Quit: TonyMac)
<romulox_x> does it not do that in 3D?  because that would be a bug, i think
* Clean3d has quit (Quit: Leaving.)
<adolson|laptop> I opened the 3D platformer and clicked on the light and it selected it in the tree
<mamarilmanson> yes... I tried it in godot 1.0
<mamarilmanson> adolson|laptop, I think I know what is happening... if it's a child and is in collpased(or is it expanded view) in the node tree it does not show up as expected... 
<romulox_x> oh, so you want the tree to expand so you can see it selected
<adolson|laptop> that doesn't need a whole new button
<romulox_x> that does seem reasonable, though clicking around might expand all your nicely collapsed areas
<adolson|laptop> maybe an Expand tree on focus preference option
<romulox_x> yeah
<adolson|laptop> either way, that PR has a merge conflict so someone would have to fix it, with or without the added button
<adolson|laptop> I think the button is unnecessary, personally, and it should just be automatic, as it mostly already is
<mamarilmanson> yes... agree... *thumbsup*

Just a conversation that might help... :)

**Comment by akien-mga** [comment]
What do the @godotengine/user-interface think about this?

**Comment by MarianoGnu** [comment]
Well this PR has over one year and there are conflicts. I just confirmed the issue is still happening, i want the opinion of someone else on usability team, but maybe adding a button just for this will bloat the UI unnecesarily, instead it could be expanded and selected when clicking on the node in scene.
This can be anoying too, because some of us like the scene tree organized and automatic collapse is not nice when selecting the wrong node. And no 2d/spatial nodes can't be selected from editor.
An option could be to allow show/hide this button in the Editor Settings, but hiden features are not features imo, so it should be enabled by default. Opinions?

**Comment by akien-mga** [comment]
I tend to agree with @MarianoGnu, I'm not sure this would really be a useful feature, and it would clearly make the UI more cluttered.

Maybe a hotkey that does the same job would be a better alternative.

**Comment by vnen** [comment]
Not sure how to handle this, but from a usability perspective you shouldn't add a hotkey without a command via the GUI, even if it's inside a menu. So maybe a menu option + the hotkey?

**Comment by akien-mga** [comment]
Well there are already quite a few hotkeys that do not match a GUI button, especially in the 2D and 3D viewports; IMO, more than trying to add a button for each of them in the UI, we should implement #2745 :)

**Comment by akien-mga** [comment]
But to be honest I don't think the feature discussed here would be very useful anyway.

**Comment by MarianoGnu** [comment]
Maybe pressing the F key both in canvas/3d editor focus the object both in scene tree, and replicate the same use if the f is pressed in the scene tree (currently only focusing if used on editor) if people doesn't like the tree being collapsed it can be remaped to alt+f or added an option to editor settings.

**Comment by akien-mga** [comment]
Based on the above discussion, I think we wouldn't use the current proposal (and it has merge conflicts). If someone wants to add a hotkey to find the currently selected node (e.g. F as proposed by @MarianoGnu), please open a new feature request.

**Pull request closed without merging**
