### PR TITLE
Cleanup of the tools folder

### PR DESCRIPTION
**Pull request by akien-mga**
@punto- @vnen @reduz About the first commit: I put all distribution specific stuff in `tools/dist` to reduce clutter, e.g. the iOS and OSX templates (and the UWP template could go there too).
I also move stuff like the docker file there, and it would also be the place for @djrm's AppImage (PR merge pending). I also thought about putting this `dist` folder directly at the root, feedback welcome.

@punto- also proposed to move the platform-specific templates to their own `platform` dir, which is also a valid alternative I guess. But as there is also some non-platform-specific "helper" stuff like the dockerfile and incoming AppImage, I guess it's ok this way too.

For the other commits, I think they are relatively harmless.

### CODE REVIEW

**Comment by vnen** [comment]
It seems you haven't touched the Xcode project under `platform/iphone`. Will it be kept there?

**Comment by akien-mga** [comment]
> It seems you haven't touched the Xcode project under `platform/iphone`. Will it be kept there?

I had not noticed it. How does it compare to the `ios_xcode_template` folder? I guess I can move it to `tools/dist`, unless we prefer to put everything in the corresponding `platform/*` folders as suggested by @punto-.

**Comment by vnen** [comment]
I don't really use Mac/iOS, but the one in `tools` is very old and never really updated while the the one in `platform/iphone` is from this year, so the latter seems to be the proper one.

Moving to the respective platform folders seems more appropriate to me.

**Comment by akien-mga** [comment]
I've rebased to remove the obsolete xcode template and move the one from `platform/iphone/xcode` to `tools/dist/ios_xcode`. I'm not yet convinced about keeping such things in `platform/*`, as everything else in those folders is never tampered with by users and only used at build time; I feel having all "custom" scripts and templates that users might need to pack their own templates makes more sense in a single location (especially to keep them up-to-date without having to hunt for them).

But if there are more people in favour of putting this stuff in `platform/`, I'll do the change :)

It would be something like that:
```
platform/osx/osx_template.app/
platform/osx/osx_tools.app/
platform/iphone/xcode/
platform/javascript/html_fs/
tools/dist/docker/
tools/dist/appimage/ (PR pending)
tools/dist/flatpak/ (likely coming soon)
tools/dist/snap/ (likely coming soon)
```

**Comment by hubbyist** [comment]
Short of "modified scripts list for template xyz" per project or template like an manifest file may be useful to prevent hunting of user modified scripts maybe.

**Comment by vnen** [comment]
@hubbyist I can't tell what you're talking about. What are those "modified scripts" you're citing?

**Comment by vnen** [comment]
I prefer to leave all in `tools/dist`, making easier to find the export templates in one place. In fact, having the editor export functions under `platform` already seems odd to me (but that's another matter).

**Comment by hubbyist** [comment]
May be I misunderstood "users might need to pack their own templates", sorry.

**Comment by akien-mga** [comment]
Since we agree on the dist stuff path, let's merge. It can always be fine-tuned later on if need be.

**Comment by profelis** [comment]
@akien-mga now all docs has wrong paths. For example here http://docs.godotengine.org/en/latest/reference/compiling_for_osx.html
`user@host:~/godot$ cp -r tools/Godot.app .`
should be changed to `tools/dist/...`

**Comment by akien-mga** [comment]
Thanks for the reminder, will fix that.

**Pull request merged**
