### PR TITLE
Add clarification on `ThreadPool`s threadcount

### PR DESCRIPTION
**Pull request by BrianBHuynh**
https://github.com/godotengine/godot/blob/master/core/os/os.h
https://github.com/godotengine/godot/blob/master/platform/web/os_web.h

Sources here 
https://github.com/godotengine/godot/blob/master/core/os/os.h#L91
https://github.com/godotengine/godot/blob/master/platform/web/os_web.h#319
https://github.com/godotengine/godot/blob/master/core/object/worker_thread_pool.cpp#L752

Note that although web returns 1, the max threads is the returned processors - 1 so no multithreading on web

### CODE REVIEW

**Comment by BrianBHuynh** [comment]
Closes https://github.com/godotengine/godot-docs/issues/8937

**Comment by Mickeon** [comment]
Was the closing unintentional?

**Comment by AThousandShips** [comment]
They deleted their fork

**Comment by BrianBHuynh** [comment]
OH that was unintentional I'm sorry!!! Was having problems with github haha

**Pull request closed without merging**
