### PR TITLE
Fix editor/property_editor.cpp TTR

### PR DESCRIPTION
**Pull request by sersoong**
no more commit，just this.
Independent from #11285.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by Noshyaar** [comment]
Please amend the commit with a more descriptive commit log. Change is okay to merge.

**Comment by Noshyaar** [comment]
You need to push another change to overwrite the commit log. Use `git commit --amend` to fix this:

image

**Comment by sersoong** [comment]
What's mean YOLO?

**Comment by Noshyaar** [comment]
Please don't mind. Just a word people say when they do something risky, in this case: not waiting for error checks to finish and merge instantly.

**Pull request merged**
