### PR TITLE
Add both X and Y scale in the scale editor

### LINKED ISSUE #22272: Scaling nodes in 2D is non-intuitive
**Godot version:**
3.1 a4e4dd3

**OS/device including version:**
Windows 10

**Issue description:**
When I try to scale Sprite(or other 2D node) shown are only 2 lines to scale node in x and y separately, but I miss the possibility of changing the node in two directions(like in 3D view)
2D scale view
ssd
3D scale view(have a small plane to move node in 2 directions
aaaaafsf

This will be good if we choose to scale object by clicking at the scale icon at the top of editor, but when I click at the S key(scale shortcut) I expect editor behaviour like Blender - scale is set via mouse position not clicking and dragging scale line.
aasfasfafasf

### PR DESCRIPTION
**Pull request by groud**
Closes #22272 and fixes a bug with scaling not working fine with rotated nodes.

### CODE REVIEW

**Comment by capnm** [comment]
peek7

**Comment by groud** [comment]
@capnm when does that happen? Can you be a little more revise than just dropping a gif?

**Comment by capnm** [comment]
> when does that happen?

It was late at night, I turned on my Linux computer, while drinking a beer I checked out the godot master branch, checked out your patch, compiled godot. Then i did some basic testing to scale the nodes with a green icon on it. Almost everything my mouse tried felt useless to me.

> Can you be a little more precise than just dropping a gif?

(I didn't know if you wanted to read what I thought;) Basically, playing whack-a-mole with the code usually goes wrong—you need a concept and some testing strategy.

**Comment by groud** [comment]
> Basically, playing whack-a-mole with the code usually goes wrong—you need a concept and some testing strategy.

I don't really need your advices on how to code. If you don't want to help I'll ask you to leave.
And please stop being sarcastic, it does not help, and I don't like that.

**Comment by groud** [comment]
Alright, updated with something that looks more usable.

**Comment by capnm** [comment]
> I don't really need your advices on how to code. If you don't want to help I'll ask you to leave.
And please stop being sarcastic, it does not help, and I don't like that.

I'm sorry. Please do not take it personally. I thought the gif is obvious and needs no comment. I then described as a joke exactly what happened;) and just wrote down my actual feeling, which could be better with Godot development.

> Alright, updated with something that looks more usable.

Yes, now it's perfect, thanks!

**Comment by groud** [comment]
It's okay. I'm over it. :)

> Yes, now it's perfect, thanks!

Alright, should be ready to be merged then.

**Comment by capnm** [comment]
peek10

**Comment by Overblob** [comment]
Your commit adds a weird file "st0XpPFU". Is it on purpose?
I saw recently this kind of file generated at compile time, however I haven't personally looked for its provenance nor its utility yet.

**Comment by avencherus** [comment]
Did a build this morning with this PR on top.  It is looking good so far on my end (Win10 64-bit), and it does seem that the rotation+scaling issue mentioned above is ironed out.  I haven't encountered it.

I will add, this is actually a rather massive improvement.  It responds very smoothly too.

Being able to drag like this makes many things so much easier and faster, while keeping the option to manipulate the handles for isolating X and Y.  A big thanks for this.  X)

**Comment by groud** [comment]
> Your commit adds a weird file "st0XpPFU". Is it on purpose?

No. It's solved now.

**Pull request merged**
