### PR TITLE
Expose brotli decompression to the scripting API.

### PR DESCRIPTION
**Pull request by bruvzg**
Exposes brotli decompression it to the scripting API via new `FileAccess.COMPRESSION_BROTLI` `CompressionMode` constant (usable with any script function, which takes `CompressionMode` argument).

See https://github.com/godotengine/godot/pull/59522#issuecomment-1487141004

### CODE REVIEW

**Comment by bruvzg** [comment]
Encoder is quite slow and big, so not sure if it worth it, might be better to keep it as decode only.

**Comment by Calinou** [comment]
> Encoder is quite slow and big, so not sure if it worth it, might be better to keep it as decode only.

Indeed, I'd make it decode-only as Brotli seems to have fallen out of fashion lately.

**Comment by bruvzg** [comment]
Changed it to decompression only (removed encoder and multiplayer API changes), compression benefits are small and encoder is 10 times slower than ZSTD so not worth it. Adding decompression support is reasonable since we have it for WOFF2 support anyway, so it's free.

**Review by Calinou — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
