### PR TITLE
Add missing BIND_ENUM for SPEAKER_SURROUND_31

### PR DESCRIPTION
**Pull request by marcelofg55**

### CODE REVIEW

**Comment by akien-mga** [comment]
Is there any code that implements 3.1 surround mode though? If not, shouldn't we drop it instead?

**Comment by marcelofg55** [comment]
Surround 3.1 is actually implemented already and shouldn't be dropped

**Comment by akien-mga** [comment]
Ok, thanks. It looks like it was missing from `scene/gui/video_player.cpp`, I added a `FIXME` there if you want to have a look.

**Comment by marcelofg55** [comment]
I'll take a look into that, thanks for the notice

**Pull request merged**
