### PR TITLE
Disable GIProbe emission when disabled on a material

### PR DESCRIPTION
**Pull request by josefkaragoli**
Fixes https://github.com/godotengine/godot/issues/48230

### CODE REVIEW

**Comment by clayjohn** [comment]
Code looks good! I'm just going to test it out locally before approving as I haven't worked with GIProbes much.

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.1.

**Pull request merged**
