### PR TITLE
GDScript: Fix common mismatched external parser errors (second try)

### LINKED ISSUE #94244: 4.3.beta3 GDScript errors on load of Zylann hterrain plugin: Parser bug: Mismatched external parser.
### Tested versions

4.3.BETA3

### System information

WINDOWS 10

### Issue description

this plugin can use on godot4.3.beta2 with no error.and when I update my godot to 4.3.beta3.error occur
https://github.com/Zylann/godot_heightmap_plugin/issues/456

*Bugsquad edit: Copied from other issue.*
```
ERROR: Parser bug: Mismatched external parser.
at: (modules/gdscript/gdscript_analyzer.cpp:909)
SCRIPT ERROR: Parse Error: Cannot infer the type of "i" variable because the value doesn't have a set type.
at: GDScript::reload (res://addons/zylann.hterrain/tools/brush/brush_editor.gd:158)
ERROR: Failed to load script "res://addons/zylann.hterrain/tools/brush/brush_editor.gd" with error "Parse error".
at: load (modules/gdscript/gdscript.cpp:2925)
ERROR: Parser bug: Mismatched external parser.
at: (modules/gdscript/gdscript_analyzer.cpp:909)
ERROR: Parser bug: Mismatched external parser.
at: (modules/gdscript/gdscript_analyzer.cpp:909)
SCRIPT ERROR: Invalid call. Nonexistent function 'set_terrain_painter' in base 'HBoxContainer (brush_editor.gd)'.
at: set_terrain_painter (res://addons/zylann.hterrain/tools/panel.gd:47)
SCRIPT ERROR: Invalid call. Nonexistent function 'setup_dialogs' in base 'HBoxContainer (brush_editor.gd)'.
at: setup_dialogs (res://addons/zylann.hterrain/tools/panel.gd:25)
```

### Steps to reproduce

add plugin, and open project

### Minimal reproduction project (MRP)

add plugin, and open project

### PR DESCRIPTION
**Pull request by rune-scape**
retry of https://github.com/godotengine/godot/pull/94617

i rewrote the part that crashed, as it wasn't very readable or safe

collection of every mrp that exposes an edge case so far: [external-parser-edgecases.zip](https://github.com/user-attachments/files/16446550/external-parser-edgecases.zip)

with these changes, on my machine, the project loads with no errors (after letting godot import everything)

added tests too

fixes https://github.com/godotengine/godot/issues/94244

### CODE REVIEW

**Review by vnen — DISMISSED** [review]
Looks okay to me. Tested with the repro project and it works. Also nice to have some tests.

**Comment by mihe** [comment]
I'm seeing project-breaking regressions with this PR applied, unfortunately, in the form of `Parse Error: Parser bug: Could not find external parser. (Trying to resolve class member "..." of "...")`.

I'll see if I can reduce it down to an MRP, but these ones are likely going to be a lot tougher to untangle than the regression from #94617.

**Comment by mihe** [comment]
Thankfully it wasn't as difficult as I thought to extract this, so here's an MRP that reproduces the error I mentioned above: [external-parser-error.zip](https://github.com/user-attachments/files/16426614/external-parser-error.zip)

The MRP can probably be reduced further, but this mimics the relationships in the actual project. You'll find the error in `script_a.gd`.

**Comment by vnen** [comment]
The error does make sense, as this code is looking for depended parsers, but there's nothing actually adding those scripts to the list.

An inclusion like this on top of this PR would solve this issue in particular:

```diff
diff --git a/modules/gdscript/gdscript_analyzer.cpp b/modules/gdscript/gdscript_analyzer.cpp
index f46e392632..1ca326a891 100644
--- a/modules/gdscript/gdscript_analyzer.cpp
+++ b/modules/gdscript/gdscript_analyzer.cpp
@@ -3704,6 +3704,15 @@ Ref<GDScriptParserRef> GDScriptAnalyzer::ensure_cached_parser_for_class(const GD
                external_class_parser_cache.insert(p_class, E->value);
                parser_ref = E->value;
            }
+       } else {
+           Ref<GDScriptParserRef> temp = parser->get_depended_parser_for(script_path);
+           if (temp.is_valid()) {
+               temp->raise_status(GDScriptParserRef::PARSED);
+               if (temp->get_parser()->has_class(p_class)) {
+                   external_class_parser_cache.insert(p_class, temp);
+                   parser_ref = temp;
+               }
+           }
        }
    }
``` 

Although a proper fix might want to load it the depended parser earlier.

Also, I'm not sure how this would interact with with parser refs being invalidated on reload.

**Comment by mihe** [comment]
I'm not seeing any more errors after applying the patch that @vnen provided above.

**Comment by akien-mga** [comment]
So I'd like to release 4.3.rc2 tomorrow, ideally including this fix. So we have two options:

1. Amend in @vnen's workaround
2. Wait for @rune-scape to amend the PR with their own fix if they'd take a different approach

The second option is obviously preferred but I can't presume of rune's availability on a short notice. If you see this let us know which option you prefer, otherwise I'd go with adding vnen's workaround later today (8-9pm UTC) before starting a build.

**Comment by adamscott** [comment]
> So I'd like to release 4.3.rc2 tomorrow, ideally including this fix. So we have two options:
> 
>     1. Amend in @vnen's workaround
> 
>     2. Wait for @rune-scape to amend the PR with their own fix if they'd take a different approach
> 
> 
> The second option is obviously preferred but I can't presume of rune's availability on a short notice. If you see this let us know which option you prefer, otherwise I'd go with adding vnen's workaround later today (8-9pm UTC) before starting a build.

What about option 3: Another PR that includes @rune-scape's work as co-author?

**Comment by akien-mga** [comment]
> What about option 3: Another PR that includes @rune-scape's work as co-author?

That's the same as (1) with just a formal difference, not really what I'm interested in at this stage. I can force push the PR to amend it with vnen's change and merge in a minute. If we merged another PR we'd close this one so it's the exact same outcome.

**Comment by vnen** [comment]
If we go for (1) let's add this instead, which is essentially the same thing but less verbose:

```diff
diff --git a/modules/gdscript/gdscript_analyzer.cpp b/modules/gdscript/gdscript_analyzer.cpp
index f46e392632..2412d877a8 100644
--- a/modules/gdscript/gdscript_analyzer.cpp
+++ b/modules/gdscript/gdscript_analyzer.cpp
@@ -3697,6 +3697,7 @@ Ref<GDScriptParserRef> GDScriptAnalyzer::ensure_cached_parser_for_class(const GD
            }
        }
    } else {
+       parser->get_depended_parser_for(script_path);
        if (HashMap<String, Ref<GDScriptParserRef>>::Iterator E = parser->depended_parsers.find(script_path)) {
            // Silently ensure it's parsed.
            E->value->raise_status(GDScriptParserRef::PARSED);
```

**Comment by rune-scape** [comment]
i have a fix that seems to work

the issue in my code was that it was not calling `ensure_cached_parser_for_class` in `get_class_node_current_scope_classes`

that method should ideally be dynamically calling `resolve_class_inheritance` as the classes are searched through which would cache the class parsers, but it doesn't right now

**Comment by rune-scape** [comment]
i also fixed a bug where it only pretended to look at base class, which may have also solved it but i didn't test
+added a search through the external dependant parser's class parser cache,
+made the local search for the external parser a fallback option
+added a test case for this

interestingly the test case seems to trigger a runtime error when 1 line is uncommented, but its only testing the analyzer, so it should be fine for now

**Comment by mihe** [comment]
@rune-scape This latest iteration (rune-scape/godot@f8a066b0c) results in:

```
Parse Error: Parser bug: Could not find external parser. (Trying to fetch classes in the current scope: base class of "...")
```

Do you want me to try to reduce that down to an MRP as well?

**Comment by rune-scape** [comment]
ach! yes please, thank you so much for the MRPs :heart:

**Comment by mihe** [comment]
@rune-scape Here's an MRP for this latest error: [external-parser-error-f8a066b0c.zip](https://github.com/user-attachments/files/16445666/external-parser-error-f8a066b0c.zip)

**Comment by monxa** [comment]
I've tested it with @vnen second patch applied. It works on my main project now. Thank you guys!

**Comment by rune-scape** [comment]
@mihe thank you, that MRP pointed out that my function wasn't searching everywhere it needed to

+updated collection of mrp, and updated tests

**Comment by mihe** [comment]
@rune-scape The latest iteration (rune-scape/godot@6e8fa6dd5) seems to work without errors, at least in this particular (large) project that I'm working with.

**Review by akien-mga — APPROVED** [review]
Thanks @rune-scape for the quick turnaround and everyone involved in testing!

Let's give this another spin for 4.3.rc2 :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by riazey** [comment]
Just a heads up the plugin Kanban Tasks -Todo Manager 2.0 by HolonProductions also throws a parser mismatch error (available on the assetLib) as of 4.3.beta3 & RC1- Was gonna wait until rc2 to check but wanted to let ya know in case!

**Comment by rune-scape** [comment]
@riazey :3 i no longer get that error after this pr when downloading from the asset library  and enabling it then restarting the editor :]

**Pull request merged**
