### PR TITLE
Build the engine with custom modules in Visual Studio

### LINKED ISSUE #1232: Integrate the `custom_modules` SCons parameter with Visual Studio project generation
**Describe the project you are working on:**
setup where multiple games are started from a selection "game"

**Describe the problem or limitation you are having in your project:**
when building with the "vsproj" parameter, the "custom_modules" parameter is not integrated with the vs project, so the visual studio build does include the "custom_modules" path and will therefore differ from the command line build.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
if "custom_modules" is used with "vsproj=yes", the "custom_modules" parameter is also included with the scons commands emitted by visual studio.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
methods.py -> generate_vs_project could check for the existence of the "custom_modules" parameter and include it if found:
```python
        custom_modules_flag = ""
        if env["custom_modules"]:
            custom_modules_flag = 'custom_modules="%s"' % env["custom_modules"]
        env["MSVSBUILDCOM"] = build_commandline(
            "scons --directory=\"$(ProjectDir.TrimEnd('\\'))\" platform=windows progress=no target=$(Configuration) tools=!tools! %s -j%d" % (custom_modules_flag, num_jobs)
        )
```

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
anytime there is a custom modules location, it will have to be passed to compile successfully and VS would be expected to give the same result as the command line, so it would be used everytime. It can be worked around by adding the path by hand in VS, however it would be expected behaviour and be less confusing if the VS project contained the path as well.
Especially when overriding an existing module in this fashion, a potential error would not be easy to track as it would still use the unmodified code.

**Is there a reason why this should be core and not an add-on in the asset library?:**
it is a compile enhancement, code is not affected

### PR DESCRIPTION
**Pull request by Xrayez**
Follow-up to #36922.
Closes godotengine/godot-proposals#1232.

First, compile the engine with `custom_modules` and `vsproj=yes`:
```
scons custom_modules="path/to/your/modules" vsproj=yes
```
Run the Visual Studio project. You can now rebuild the engine if you need to make changes to custom modules directly within IDE.

Annotation 2020-08-22 182422

---

**This feature is requested by IMVU members.**

### CODE REVIEW

**Comment by fire** [comment]
Changing the custom folder doesn't seem to sync the visual studio project, and I'll try again.

**Comment by Xrayez** [comment]
@fire make sure you do compile with `scons custom_modules="/path/to/modules" vsproj=yes`. You can also try deleting the generated Visual Studio project files entirely, I think I've had problems of not all `custom_modules` sources appearing in the IDE as well that way, maybe that's an existing bug in Godot's Visual Studio project generator.

In any case, this works on my machine on a clean Godot source state.

**Comment by Xrayez** [comment]
@GoDino or anyone else, could you test this as well? If someone else manages to succeed with this, then perhaps there's something which users may need to be aware of, so would be worth documenting this.

I may fail to understand what exactly a user may expect from this feature, please describe reproduction steps in detail so I can better understand what you're doing. 🙂

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
