### PR TITLE
Timer class clarification

### PR DESCRIPTION
**Pull request by menip**
The current [Timer](http://docs.godotengine.org/en/latest/classes/class_timer.html#member-variables) variable naming is not very clear. Specifically:
- "one_shot" is not immediately intuitive. This has been renamed to "repeat".
- "wait_time" has been updated to "time_interval", to be more consistent with it's function.

Logic, class doc, and code using Timer class have been updated accordingly. 

Pros: Class is now more intuitive to work with
Downside: This changes the API. Docs and tutorials would need to be updated.

### CODE REVIEW

**Comment by LikeLakers2** [comment]
Not sure I personally understand or agree with either of these changes. I mean, I get the intent behind them, but... The idea of opting into making it a one-shot timer makes more sense to me than opting out of a repeat. Additionally, I can only imagine new people going "what is this time interval *for?*" when it comes to the wait_time->time_interval change.

Also, with the docs, "Timer interval in seconds" seems more confusing than "wait time in seconds" (again, "what is this time interval *for?*"), though to be fair, neither specify what this interval/wait time is for.

**Comment by menip** [comment]
@LikeLakers2 Yes, it is mostly a wording issue. I agree that the wait_time->time_interval change may not make things much clearer. 
I'll wait for further discussion, especially about one_shot. The goal here is to make using the class more intuitive.

**Comment by reduz** [comment]
Qt uses "single shot" and "interval" instead of "one shot" and "wait_time"

**Comment by eon-s** [comment]
one shot is consistent with other nodes like particles, but interval sounds better to me.

**Comment by akien-mga** [comment]
I have no strong opinion either way... What do others think about it?

**Comment by poke1024** [comment]
I like the QT terminology.

**Comment by mhilbrunner** [comment]
Personally, I think its fine as is.

**Comment by akien-mga** [comment]
There is no real consensus on the proposed change, so I think the best approach for now is "keep it as is".

**Pull request closed without merging**
