### PR TITLE
[GDnative] pass api as struct of function pointers to loaded gdnative modules

### PR DESCRIPTION
**Pull request by touilleMan**
this is for @karroffel  ^^

### CODE REVIEW

**Comment by karroffel** [comment]
Ohhh that's awesome!!

We should probably remove/change the `GDAPI` macro then as windows doesn't need to export those symbols anymore. We could do the same for all other OSs too, then GDNative wouldn't depend on `-rdynamic` anymore.

I'm waiting for Travis, then this is good to go, great work, thanks :)

**Comment by bojidar-bg** [comment]
Can't we use an [X macro](https://en.wikipedia.org/wiki/X_Macro) to list all the functions in just one place?

**Comment by touilleMan** [comment]
@bojidar-bg not sure this would work give each function pointer has a different signature, however if you know how to do this, I can modify mode code easily (I'm using a script to generate it)

**Comment by karroffel** [comment]
Maybe `#define GDAPI_FUNC(name, ret_type, ...) ret_type (*name)(__VA_ARGS__)` or something like that for the struct definition, the values could be set by just using the name?

**Comment by karroffel** [comment]
Thinking about it, X Macros would be really cool for this, could even be used for the wrapper functions

```c
#define GDAPI_FUNC(name, ret_type, ...) \
    inline ret_type name(__VA_ARGS__) { \
        return global_struct->name(__VA_ARGS__); \
    }
```

This wouldn't work for `void` functions, (void is so weird....), we could have a special macro for functions that return void.

```c
#define GDAPI_VOID_FUNC(name, ...) \
    inline void name(__VA_ARGS__) { \
        global_struct->name(__VA_ARGS__); \
    }
```

**Comment by akien-mga** [comment]
Build fails for both commits with GCC 4.8:
```
g++ -o modules/gdnative/gdnative/dictionary.x11.tools.64.o -c -g2 -DDEBUG_ENABLED -DDEBUG_MEMORY_ENABLED -pipe -w -DFREETYPE_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE -DALSA_ENABLED -DJOYDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DOPENGL_ENABLED -DGLES2_ENABLED -DGLES_OVER_GL -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DGLAD_ENABLED -DGLES_OVER_GL -DGDAPI_BUILT_IN -Icore -Icore/math -Ieditor -Idrivers -I. -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/alsa -Iplatform/x11 -Ithirdparty/zstd -Ithirdparty/zstd/common -Ithirdparty/glad -Imodules/gdnative/include modules/gdnative/gdnative/dictionary.cpp
modules/gdnative/gdnative.cpp:711:1: sorry, unimplemented: non-trivial designated initializers not supported
 };
 ^
modules/gdnative/gdnative.cpp:711:1: sorry, unimplemented: non-trivial designated initializers not supported
```

**Comment by touilleMan** [comment]
I've fix the compilation error, then change my implementation to use X macros, which save us from one huge list ;-)
As @karroffel said, this is especially a great idea to generate wrapper functions. So easy in fact I wonder if we shouldn't just add this code snippet somewhere in the gdnative doc (like "if you want to have a regular function-based api to work with, just use this code with the header to generate it in your codebase") and voila !

**Comment by karroffel** [comment]
@touilleMan it looks like usually those things are in a separate file with a `.def` extension when is then included (instead of a macro containing the text).

Also one thing I didn't think about is that you can do `global_struct->name(__VA_ARGS__);` because those `__VA_ARGS__` are the types, not argument names. We might need to think about that... but that's stuff that can be done later I think, this PR looks pretty good now, maybe move those things to a `.def` file which can be distributed with the headers.

**Comment by touilleMan** [comment]
Finally a green build ^^

@karroffel tell me if you want me to move the struct to a `.def` file

**Comment by karroffel** [comment]
I mean if you have it as a macro inside a header then it's just as accessible, so you don't need to I'd say.

**Pull request merged**
