### PR TITLE
Rename AudioStreamSample to AudioStreamWAV

### PR DESCRIPTION
**Pull request by DeeJayLSP**
I see all audio formats have their streams as "OGGVorbis" and "MP3" so I think WAV needs to have its name on it too. I was going to rename it to "AudioStreamWAVE", but opted for "AudioStreamWAV" due to some existing classes pointing it out as WAV.

Everything has been tested and seems to work correctly, although WAV files on existing projects will need to get reimported by deleting the import file.
~~Since this is my first attempt to change a class name I kinda panicked when I couldn't open an already imported WAV.~~

Edit: Implements godotengine/godot-proposals#4532

### CODE REVIEW

**Comment by lyuma** [comment]
If renaming is desired, I think a better name would be AudioStreamPCM, since that more closely matches the in-memory format.

AudioStreamOGGVorbis and AudioStreamMP3 are named as such, because they store their data in those respective formats in memory (Vorbis / MP3 streams) and perform streaming decompression during playback.

However, AudioStreamWAV doesn't store the in-memory samples in the WAV file format (with header), but rather store raw PCM data. Furthermore, it is useful to generate audio data as raw PCM samples and assign it to the AudioStream using .set_data()

Just as an ImageTexture can be losslessly saved and loaded as a .png, an AudioStreamSample can be losslessly saved and loaded as a .wav (or even .flac)

I'll follow what you all decide, if the popular perception is that ".wav" is a better way to refer to the concept of raw PCM streams, and others agree with this PR. I just wanted to voice my logic for why .wav is named differently from other formats.

**Comment by DeeJayLSP** [comment]
Why should it be named AudioStreamWAV:

- It's used primarily for storing data loaded from WAVs;

Why should it be named AudioStreamPCM:

- The class stores the samples in raw PCM data;

Why it **shouldn't** be named AudioStreamSample:

- When people see the word Sample in this class, their first guess may be not explicitly a WAV/PCMt;

I'm honestly fine with either WAV or PCM, but not with Sample. If there's popular consensus that it should be named AudioStreamPCM, I will be redoing this PR.

**Comment by fire** [comment]
The most specific name is `AudioStreamPCM` so I'm leaning towards that. @ellenhp is there anything I missed?

**Comment by DeeJayLSP** [comment]
I made an alternate branch with changes to AudioStreamPCM ready if needed.

**Comment by ellenhp** [comment]
I actually had the same thought as @lyuma but I was at work. Either way though, this needs a proposal to give the community a chance to weigh in. I support a rename to AudioStreamPCM.

**Comment by aaronfranke** [comment]
Just to weigh in, I know a bit about audio formats but I've never heard of PCM before. I'm wondering if AudioStreamPCM would lead to confusion or a lack of discoverability. WAV files are typically used for short audio snippets/samples, so the old name isn't all that bad IMO but I agree it's sub-optimal and I think either proposed name is better.

**Comment by DeeJayLSP** [comment]
> I'm wondering if AudioStreamPCM would lead to confusion or a lack of discoverability.

I think leaving it as AudioStreamSample may be a worse misleading.

Just think: 
- Someone looking to import an audio file, regardless of the format, probably won't even look for the corresponding AudioStream class, just if Godot supports it or not.

- Someone that looks at AudioStreamSample may not think about its true meaning at first.

**Comment by ellenhp** [comment]
Discussion on renames generally happens in proposals. Would you mind [creating a proposal](https://github.com/godotengine/godot-proposals/issues/new?assignees=&labels=&template=feature_proposal.yml) for this?

**Comment by DeeJayLSP** [comment]
Drafted for discussion, please check godotengine/godot-proposals#4532

**Comment by DeeJayLSP** [comment]
Superseded by #60957

**Pull request closed without merging**
