### PR TITLE
Let languages init & finish run without locks held

### LINKED ISSUE #84728: Godot v4.2.beta.mono editor freezes when quitting.
### Godot version

v4.2.beta.mono.custom_build

### System information

Windows 10 - Godot v4.2.beta.mono.custom_build - Vulkan (Forward+)

### Issue description

Godot editor freezes everytime I close it. So I have to terminate its process from task manager.

### Steps to reproduce

Open any project and close Godot editor.

### Minimal reproduction project

Any project, even empty project.

### LINKED ISSUE #84735: GDExtension project doesn't open properly with linux-editor-mono artifact after language bookkeeping thread-safety PR
### Godot version

4.2.beta (e38686f85b768a451dc06324fe2471adc8665448)

### System information

Mageia 9 - Vulkan (Forward+) - dedicated AMD Radeon RX Vega M GL Graphics (RADV VEGAM) () - Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 Threads)

### Issue description

I'm reporting an issue seen on the godot-cpp CI here: https://github.com/godotengine/godot-cpp/actions/runs/6823772322/job/18558325939

The "Run tests" job seems to timeout after many hours, and this started happening on Thursday 9 Nov in the afternoon (UTC).

To reproduce the issue, you need to follow the same steps as the godot-cpp CI.

First build the library and test code:
https://github.com/godotengine/godot-cpp/blob/73757e3a9fe652fa800f72f727faa8107aa1e736/.github/workflows/ci.yml#L134-L146

Then download the latest `linux-editor-mono` artifact from the Godot CI, and try to run the tests with it:
https://github.com/godotengine/godot-cpp/blob/73757e3a9fe652fa800f72f727faa8107aa1e736/.github/workflows/ci.yml#L168-L176

This line seems to never finish:
```
(cd project && (../../godot-artifacts/godot.linuxbsd.editor.x86_64.mono --editor --headless --quit >/dev/null 2>&1 || true))
```

Removing the `>/dev/null 2>&1 || true` part, we can see this:
```
$ (cd project && (../../linux-editor-mono\(3\)/godot.linuxbsd.editor.x86_64.mono --editor --headless --quit || true))
Godot Engine v4.2.beta.mono.custom_build.aa513a52b - https://godotengine.org
 
WARNING: Custom cursor shape not supported by this display server.
     at: cursor_set_custom_image (servers/display_server.cpp:505)
ERROR: GDScript bug: Native class "Example" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:121)
ERROR: GDScript bug: Native class "Example" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:121)
ERROR: GDScript bug: Native class "ExampleRef" not found.
   at: _gdtype_from_datatype (modules/gdscript/gdscript_compiler.cpp:121)
SCRIPT ERROR: Compile Error: Identifier not found: ExampleRef
          at: GDScript::reload (res://main.gd:42)
ERROR: Failed to load script "res://main.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2703)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (editor/editor_settings.cpp:1140)
```

And it continues with printing one more error every couple seconds or so.

The first errors before the EditorSettings ones are normal, they also happen on a successful run.

This seems to be caused by #84657 - CC @RandomShaper.

I tested the following artifacts to confirm that hunch:
- Artifact from that PR triggers the bug: https://github.com/godotengine/godot/actions/runs/6815038650/job/18533284910?pr=84657
- Artifact from the last CI built master commit before merging that PR doesn't trigger the bug: https://github.com/godotengine/godot/actions/runs/6810730049
- Artifact from the first CI built master commit after merging that PR triggers the bug: https://github.com/godotengine/godot/actions/runs/6815230311

Those artifacts don't have debug symbols, so I couldn't get a useful stacktrace to see what it's stuck on.

I tried to run the same steps as the godot-cpp CI using a self-compiled dev build (non-Mono), but it seems to work fine. And I tried with a self-compiled Mono build, which seems to outright crash with `free(): invalid pointer`... might be related, or not.

*Edit:* I can reproduce the above recurring errors with a .NET build made from our official buildsystem: https://downloads.tuxfamily.org/godotengine/testing/Godot_v4.2-beta_20231111_linux_mono_x86_64.zip
So the crash I have with my local build must be a me issue, we can ignore it here. I'll make a build with debug symbols on the official buildsystem.

For context, the reason we use a .NET build on the godot-cpp CI is simply because that's the one available as artifact from the Godot CI.

### Steps to reproduce

See above.

### Minimal reproduction project

godot-cpp test project, with the above steps.

### PR DESCRIPTION
**Pull request by RandomShaper**
These changes are still not perfect against race conditions, but that was already the case before the recent batch of changes here.

- Fixes #84728.
- Fixes #84735.

### CODE REVIEW

**Comment by akien-mga** [comment]
It should also fix #84728 (the problem is with the C# bindings btw, not GDExtension - but GDExtension script bindings may also be affected).

**Review by akien-mga — APPROVED** [review]
I tested this today, and confirm this fixes https://github.com/godotengine/godot/issues/84728.

Didn't spot any obvious regression on a couple GDScript and C#.
Didn't test any GDExtension ScriptLanguage.

I still get this one error when closing the .NET editor, but it's no longer blocking:
```
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true. Returning: Variant()
   at: _EDITOR_GET (./editor/editor_settings.cpp:1140)
```
The same error happens in 4.2-beta5 so it's not related to your original PR, and thus not needed to fix here.
*Edit:* This error even happens in 4.1-stable on my test project.

**Comment by YuriSizov** [comment]
> The same error happens in 4.2-beta5 so it's not related to your original PR, and thus not needed to fix here.
> _Edit:_ This error even happens in 4.1-stable on my test project.

It is probably related to this report https://github.com/godotengine/godot/issues/84839.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Bound2bCoding** [comment]
This is still happening to me in 4.4.1 stable.  I was working in my game and when I exited, Godot crashed.  Visual Studio did not crash though.

Faulting application name: Godot_v4.4.1-stable_mono_win64.exe, version: 4.4.1.0, time stamp: 0x67e3400c
Faulting module name: nvoglv64.dll, version: 32.0.15.7216, time stamp: 0x6795db05
Exception code: 0xc0000005
Fault offset: 0x0000000000e4bcf1
Faulting process id: 0x8360
Faulting application start time: 0x1DBBC8F43D280A4
Faulting application path: I:\Godot_v4.4.1-stable_mono_win64\Godot_v4.4.1-stable_mono_win64.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1e8724cced6e93d4\nvoglv64.dll
Report Id: a221a496-9dd8-4d2c-915a-73bb0f04e948
Faulting package full name: 
Faulting package-relative application ID: 

[-](https://github.com/godotengine/godot/pull/84847#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/godotengine/godot/pull/84847#) <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2025-05-04T01:18:27.8522342Z" /> 
  <EventRecordID>74937</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="33264" ThreadID="31156" /> 
  <Channel>Application</Channel> 
  <Computer>RobertPC</Computer> 
  <Security UserID="S[-](https://github.com/godotengine/godot/pull/84847#)1-5-21-3395998073-2436982047-224187108-1001" /> 
  </System>
- <EventData>
  <Data Name="AppName">Godot_v4.4.1-stable_mono_win64.exe</Data> 
  <Data Name="AppVersion">4.4.1.0</Data> 
  <Data Name="AppTimeStamp">67e3400c</Data> 
  <Data Name="ModuleName">nvoglv64.dll</Data> 
  <Data Name="ModuleVersion">32.0.15.7216</Data> 
  <Data Name="ModuleTimeStamp">6795db05</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">0000000000e4bcf1</Data> 
  <Data Name="ProcessId">0x8360</Data> 
  <Data Name="ProcessCreationTime">0x1dbbc8f43d280a4</Data> 
  <Data Name="AppPath">I:\Godot_v4.4.1-stable_mono_win64\Godot_v4.4.1-stable_mono_win64.exe</Data> 
  <Data Name="ModulePath">C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_1e8724cced6e93d4\nvoglv64.dll</Data> 
  <Data Name="IntegratorReportId">a221a496-9dd8-4d2c-915a-73bb0f04e948</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>

Godot System Info:
Godot v4.4.1.stable.mono - Windows 11 (build 26100) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 32.0.15.7216) - AMD Ryzen 7 3800XT 8-Core Processor (16 threads)

**Pull request merged**
