### PR TITLE
Make the CenterView icon clearer

### PR DESCRIPTION
**Pull request by MewPurPur**
Addresses https://github.com/godotengine/godot/pull/57252#issuecomment-1022276340

| Before | After |
| --- | --- |
| image | image |

Optimized a few unrelated icons for a ~3 kB save because I've got an addiction.

### CODE REVIEW

**Comment by groud** [comment]
hmm, it's looks good, but I am not sure it's super clearer. It looks a bit like a clover now :thinking:

**Comment by MewPurPur** [comment]
I think I would've personally figured it out faster if it were like this, but it's impossible to be empirical with these things.

**Comment by YeldhamDev** [comment]
I think it's still an improvement compared to the original. The arrows barely looked like it because of the size before.

**Comment by Calinou** [comment]
The icon looks a bit like a "shrink" icon to me, but I think this is better than what we have right now.

Maybe we could use an icon with 4 corners and nothing on the sides and in the middle, but that would be more fitting for "Frame View" more specifically.

**Comment by akien-mga** [comment]
How about making the arrows thinner (1.5 instead of 2) so there's less chance for them to look like hearts / clover leaves at this small scale?

image

**Comment by MewPurPur** [comment]
Excellent! Doned.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
