### PR TITLE
Fix for SkeletonIK not working correctly with 0 interpolation and incorrectly rotating with animation

### LINKED ISSUE #47381: Skeleton IK breaks root bone position in rc5 and rc6
**Godot version:**
3.3.rc6

**OS/device including version:**
Zorin OS 15

**Issue description:**
In 3.2.4.rc5 and 3.3.rc6 the root bone of an SkeletonIK gets its position corrupted. Even if it has an animation.
The bug is introduced in 3.2.4.rc5

This is working as expected in rc4.
legrc4

This is how it works in rc5 and rc6.
legrc5

**Steps to reproduce:**
I use this setup
https://www.youtube.com/watch?v=68ypH04teuw

**Minimal reproduction project:**

Can't share the model.

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
Should close #47381

I know for sure this PR closes the issue with `0` interpolation not working correctly. I'm fairly confident that it will also fix the animation issue, as I removed a function that I thought was unnecessary but I think its removal was causing the issue.

### CODE REVIEW

**Comment by TwistedTwigleg** [comment]
Hmm, now there's an issue with Bone attachment nodes not being in sync, the same issue as #39893.

I will investigate, but I'm wondering if the issue is more on the BoneAttachment side than the SkeletonIK side...

**Comment by TwistedTwigleg** [comment]
I haven't found the issue, but I have narrowed it down a bit. The issue seems to be in lines `273` to `285` in `skeleton_ik_3d.cpp`. It seems that either removing the lines that reset the global pose overrides (`273` to `281`) fixes the issue or removing `_update_chain` on line `285`, but then the rotation doesn't work.
In other words, in my testing and debugging I have found a way to fix either the BoneAttachment issue (#39893) or the rotation issue (#47381), but not both.

From my testing, the BoneAttachment issue does not appear to be specific to the BoneAttachment node itself. Changing how the BoneAttachment node to get the pose itself (instead of having the Skeleton update its pose) didn't fix the issue in my testing. The global pose does truly seem to be incorrectly reset by the SkeletonIK node.

@AndreaCatania - do you maybe know what would be causing the issue? Looking at the code, I do not see anything in the lines mentioned above that would necessarily cause it.

I don't have anymore time to look this issue, but I will try to look at it further next weekend.

**Comment by AndreaCatania** [comment]
Hmmm looking at the code everything seems fine, and there is not an obvious explanation. The best to do in these cases is to re-create the issue with an extremely simple skeleton (3, max 4 bones, or really the least amount) and use the C++ debugger to walk the entire logic. While you do this, it's necessary check if the output transformations are as expected. Usually this is the most effective way that allow me to spot issues, because you truly see what's going on and find what's broken.

Let me know, or if I can help you.

**Comment by AndreaCatania** [comment]
If you manage to create the sample project, please update it here.

**Comment by yanorax** [comment]
I hope this helps. I have combined both phenomenon into this one test project.
[Skeleton Ik Test.zip](https://github.com/godotengine/godot/files/6227129/Skeleton.Ik.Test.zip)


Godot 3.3 RC6 produces this result. Left side is correct.

3 3rc6

Godot 3.2.4 RC4 produces this result. Right side is correct.
3 2 4rc4

**Comment by TwistedTwigleg** [comment]
Thanks @AndreaCatania and @yanorax - I'll look further into this issue as soon as I can! I'm hoping that I can find a fix by the end of this upcoming weekend.

**Comment by TwistedTwigleg** [comment]
It should probably be tested to confirm, but I believe both issues are fixed now! I couldn't check using the example project @yanorax made because its for Godot 3.x, but I tested using some Godot 4 projects and everything seems to work now.

**Comment by TwistedTwigleg** [comment]
@akien-mga - Can this be merged soon so it makes it into Godot 3.3? In my testing it fixes the SkeletonIK issues mentioned above.

**Comment by akien-mga** [comment]
Ah yes, sorry I missed than in the previous build.

**Review by akien-mga — APPROVED** [review]

**Comment by TwistedTwigleg** [comment]
No worries! I just figure since the release of Godot 3.3 is soon, it couldn't hurt to ask so hopefully it's fixed moving forward.

Thanks for merging and the quick reply! :)

**Comment by TwistedTwigleg** [comment]
> Thanks! Could you make a backport for 3.x?
> There are a few conflicts which don't seem too hard to solve, but I'd prefer if it's done and tested by someone who understands this code.

Sure! I'll try to backport it soon, likely this weekend at the latest. :+1:

**Comment by Janders1800** [comment]
I can test it on 3.3 once the backport its done

**Comment by TwistedTwigleg** [comment]
@akien-mga - I ported the code to Godot 3.x, checked the code to make sure it works, and made a pull request: #47738.

**Pull request merged**
