### PR TITLE
Adds realtime updates to polygon 2d editing

### PR DESCRIPTION
**Pull request by ghost**
**UPDATE**

The new behavior implemented here (see discussion under #10639) is to display a (contrasted) outline while changing the polygon in realtime. Example:

outline

There's also a new editor setting that allows for disabling the display of this outline:

bildschirmfoto 2017-08-26 um 12 09 16

**ORIGINAL**

This is a very small change that adds realtime updates to polygon 2d editing. I'm not sure if this is desirable for all users of Godot. If not, I'd suggest adding an option to enable this. I personally find this much more usable than the current editing. I'm wondering if this is something other users find useful too.

Here's a comparison of the current vs the modified behavior.

Current:

current

Modified:

realtime

### CODE REVIEW

**Comment by hpvb** [comment]
I like it 👍

**Comment by RandomShaper** [comment]
Very small yet very nice.

**Comment by toger5** [comment]
I was alway under the impression that the delay is a feature giving me the option to compare new to old?
Was that only me?

**Comment by volzhs** [comment]
@toger5 yeap. I think there are pros and cons for this. but I prefer this PR.

**Comment by toger5** [comment]
good to hear.

**Comment by RandomShaper** [comment]
That makes sense. Then it'd be good to render also the old outline while moving points, with less opacity or another color.

**Comment by hpvb** [comment]
Put it behind a preference maybe? The compare use case actually sounds useful too. Or, even better, put it behind a keyboard modifier? Hold some key for the non-preview mode maybe? 

We could then do that for the other things that now move/resize immediately maybe?

**Comment by akien-mga** [comment]
I think @RandomShaper's suggestion gives us the best of both worlds, without having to add a setting to toggle the behaviour (the more settings we have, the more we hide actual features that most users will never bother trying by themselves).

**Comment by hpvb** [comment]
@akien-mga Yeah, @RandomShaper's design is better.

**Comment by volzhs** [comment]
I love what @RandomShaper suggested.

**Comment by RandomShaper** [comment]
You're making me blush. :)

**Comment by toger5** [comment]
@n-pigeon there is actually soo much love ;)

**Comment by poke1024** [comment]
Based on @RandomShaper's proposal, I've added #10639 (also contains a lengthy rationale why I personally would prefer this current solution better).

**Comment by poke1024** [comment]
I closed #10639 and force pushed the new outline implementation to this PR. Also updates the main description to avoid confusion of what this is actually implementing right now.

**Comment by RandomShaper** [comment]
This looks good!

**Comment by Zireael07** [comment]
Is the option really spelled "**A**n"?

**Comment by Noshyaar** [comment]
@Zireael07 https://github.com/godotengine/godot/blob/d9e94fa0c308f8f157e71fb03bab5834308b56ee/editor/translations/de.po#L6532

**Comment by poke1024** [comment]
@Zireael07 just the German translation I'm using, it's "On" in English.

**Pull request merged**
