### PR TITLE
Drop old-fashioned hand-made memory functions

### PR DESCRIPTION
**Pull request by RandomShaper**
Compilers these days are pretty good at providing optimized `memcpy()` and the like. They also have intrinsics (inlined) and even may have architecture-specific versions for greater performance.

So there is no point in keeping the **copymem.h/.cpp** stuff. It would be this way even if that _TODO_ had ever been realized.

Just use the standard library routines for this and you'll be safe.

### CODE REVIEW

**Comment by vnen** [comment]
Pinging @punto- since I have a feeling that this might be related to consoles.

**Comment by reduz** [comment]
this is in the TODO list for 3.0 and will likely have to be applied after
the merge with the gles 3.0 branch

**Comment by reduz** [comment]
also yes, it's related to consoles, should no longer be necesary even on
modern ones

**Comment by reduz** [comment]
No, this is more like very old code that was placed in there from the
Wii/NDS times.

There is nothing hidden officially, just punto mantains ports to consoles
on his own. The code you are removing is very old and should be removed
anyway, so that's fine

**Comment by punto-** [comment]
why don't we implement copymem and zeromem as memcpy and memset? I don't
need the hand made functions, but I might need a mechanism to replace all
those calls with something else

**Comment by bojidar-bg** [comment]
@punto- Does `sed` count as a "mechanism"?

**Comment by punto-** [comment]
without having to maintain a patch like this :p the original idea of these
functions was to be able to replace them, but the default implementation
should be memcpy and memset, there's no reason for the hand made versions..

**Comment by punto-** [comment]
How about this in copymem.h

#ifndef COPYMEM_H
#define COPYMEM_H

#include "typedefs.h"

#ifdef PLATFORM_COPYMEM

#include "platform_copymem.h" // included from
platform/<current_platform>/platform_copymem.h"

#else

#define copymem(to,from,count) memcpy(to,from,count)
#define zeromem(to, count) memset(to, 0, count)
#define movemem(to, from, count) memmove(to, from, count)

#endif

So you have the OS functions by default, and if the platform wants in can
define PLATFORM_COPYMEM and provide a "platform_copymem.h" in the platform
directory, and implement the functions there, similar to how we do with the
atomic stuff, and I think the gles includes. Then if you *really* want the
duff device memcpy, etc, they can be in a helper file somewhere, called
from the platform_copymem.h file, but not directly by copymem.h.

**Comment by reduz** [comment]
@punto-  It's pointless, it's not needed anymore, it should be removed

**Comment by reduz** [comment]
In any case, this change makes no sense right now, will wait until 3.0 is in dropping compatibility mode to evaluate again what to do.

**Comment by RandomShaper** [comment]
Master is for 3.0, isn't it?

**Comment by reduz** [comment]
yeah, but this needs to be done after the gles-3 branch is merged

On Sat, Nov 5, 2016 at 6:46 PM, Pedro J. Estébanez <notifications@github.com

**Comment by RandomShaper** [comment]
What if I drop this PR altogether and send one for 2.1 about the same?

It would not break anything and would be good for it.

**Comment by punto-** [comment]
On the stable branch I'm actually using the replacement functions for
copymem on some platforms, but I wouldn't mind if they defaulted to the
system functions everywhere else.. if it gets enough testing it should be
fine

**Comment by RandomShaper** [comment]
Well, I think I'll drop this by now and open one for 2.1 if I have time for it.

**Pull request closed without merging**
