### PR TITLE
Update nanosvg to GIT (2022.11)

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Simple update but unsure if some function broke. It does build without errors, however.

### CODE REVIEW

**Review by fire — APPROVED** [review]
Test plan:

Import a few svg and see if anything breaks. The code says changes to arc.

**Comment by DeeJayLSP** [comment]
Seems to work fine.

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2

**Pull request merged**
