### PR TITLE
Make LineEdits in create plugin dialog expand horizontally

### LINKED ISSUE #70746: Create a Plugin dialog's text fields do not expand to fit the whole dialog window
### Godot version

4.0b10

### System information

Linux/Manjaro

### Issue description

Most dialogs in the editor scale their text field Controls to fit the whole window when it's resized, but the plugin creation dialog does not: 
image

### Steps to reproduce

1. Go to Project Settings -> Plugins -> Create New Plugin
2. Resize the new dialog

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by jamesmintram**
Makes the line edits expand when resizing the create plugin window.

Fixes: https://github.com/godotengine/godot/issues/70746

create-plugin-window-2

### CODE REVIEW

**Comment by Yagich** [comment]
If you want to make the whole dialog fit both horizontally and vertically, you might also want to add the vertical size flags to expand on the description field, since it is the largest.

**Review by Maran23 — APPROVED** [review]
I can confirm the dialog is now responsible.
LGTM

**Review by Chaosus — APPROVED** [review]

**Comment by Chaosus** [comment]
Thanks!

**Comment by Chaosus** [comment]
Ah, next time please squash the commits, I didn't make the attention to that here (my bad).

**Comment by Maran23** [comment]
> Ah, next time please squash the commits, I didn't make the attention to that here (my bad).

Ahh damn didn't noticed as well. :/

**Pull request merged**
