### PR TITLE
Fix generating POT for multiline messages

### LINKED ISSUE #70617: `Generate POT` generates incorrect multiline message.
### Godot version

master

### System information

Win11

### Issue description

When use `Generate POT` for multiline texts, it drops `\n` and generates single line message.

- **Label text in Main.tscn:**
image

- **tr() text in Main.gd:**
```gdscript
func _ready():
	print(tr("MULTILINE text\nfrom\nMain.gd"))
```

- **Generated .pot:**
```pot
#: Main.tscn
#: Main.gd
msgid "MULTILINE text"
"from"
"Main.gd"
msgstr ""

#: Main.tscn
msgid "This is"
"MULTILINE text"
"from Main.tscn"
msgstr ""
```
This is actually single line like `This isMULTILINE textfrom Main.tscn`

- **Expected:**

```pot
#: Main.tscn Main.gd
msgid ""
"MULTILINE text\n"
"from\n"
"Main.gd"
msgstr ""

#: Main.tscn
msgid ""
"This is\n"
"MULTILINE text\n"
"from Main.tscn"
msgstr ""
```

### Steps to reproduce

Generate pot file for multiline texts.

### Minimal reproduction project

[generate_pot_newline.zip](https://github.com/godotengine/godot/files/10306460/generate_pot_newline.zip)

### PR DESCRIPTION
**Pull request by ZangEldor**
Now each non-last message's line is suceeded by a \n.
Fixes #70617

### CODE REVIEW

**Comment by ZangEldor** [comment]
BTW, as a testing project, the minimal reproduction project from issue #70617 can be used for testing this PR

**Comment by AThousandShips** [comment]
To link this with the issue you need to write "Fixes #70617"

**Comment by ZangEldor** [comment]
> To link this with the issue you need to write "Fixes #70617"

Thanks, didn't know it

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
It seems like your Git identity is configured without a valid email (see the header of https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/70675.patch). So your commits won't be attributed to your GitHub account and you will always be handled as a "First-time contributor" with manual approval for CI builds.

To solve this, I would recommend changing your Git identity locally to a valid email address, and amending the commit of this PR with `git commit --amend --reset-author` to fix the commit (and then `git push --force`) to update the PR.

If you left the email blank because you want to stay anonymous, note that GitHub provides you with a "no-reply" email address that is linked to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

**Comment by ZangEldor** [comment]
> It seems like your Git identity is configured without a valid email (see the header of https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/70675.patch). So your commits won't be attributed to your GitHub account and you will always be handled as a "First-time contributor" with manual approval for CI builds.
> 
> To solve this, I would recommend changing your Git identity locally to a valid email address, and amending the commit of this PR with `git commit --amend --reset-author` to fix the commit (and then `git push --force`) to update the PR.
> 
> If you left the email blank because you want to stay anonymous, note that GitHub provides you with a "no-reply" email address that is linked to your GitHub account: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

Thanks for the full explanation, now the email appears but the workflow approval was reset

**Comment by akien-mga** [comment]
Looks good. Once merged, you should now appear as "Contributor" and future PRs will run the CI workflows automatically.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
