### PR TITLE
Better 2D Snapping

### PR DESCRIPTION
**Pull request by not-surt**
Consolidated duplicate snapping functions into CanvasItemEditor.
Allow non-square grids.
Add grid origin offsets.
Allow separate toggling of grid display.
Add rotation snapping.
Add offset snapping.

### CODE REVIEW

**Comment by reduz** [comment]
oh sorry, it seems i also at some point wrote some of this functionality, but your seems more complete. Do you think you could update the PR?

**Comment by not-surt** [comment]
Updated. I simply replaced your changes to canvas_item_editor_plugin.cpp with mine, looked like yours just added separate x/y grid sizes which mine already does.

One thing to note about this is that snap relative doesn't yet have any effect for polygon vertices. I found that code a bit daunting and didn't want to invest too much time into this if it wasn't going to be merged.

**Comment by not-surt** [comment]
Oops, my git repo seems to have gotten borked. Need to fix first.

**Comment by not-surt** [comment]
Okay repo fixed and merge is building.

**Pull request merged**
