### PR TITLE
Fix `bool` type appearing in GDExtension header

### PR DESCRIPTION
**Pull request by Bromeon**
Repetition of the exercise in https://github.com/godotengine/godot/pull/71696 and https://github.com/godotengine/godot/pull/81247.

Since 3 is a good number of times to start automating, I'll look into preventing this.

### CODE REVIEW

**Comment by dsnopek** [comment]
Eep, sorry! This could be helped by the idea for generating the header from JSON/XML, because we could have a list of allowed types. I'm going to try to explore that in the 4.4 dev cycle if I find the time, although, it's not super high priority.

Anyway, this change looks good! Thanks!

**Review by dsnopek — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by Bromeon** [comment]
> This could be helped by the idea for generating the header from JSON/XML, because we could have a list of allowed types. I'm going to try to explore that in the 4.4 dev cycle if I find the time, although, it's not super high priority.

Just running the header through a C compiler already catches most of these issues, which is what I did in https://github.com/godotengine/godot/pull/96408. Would be nice to have some validation like this soon, because incorrect headers keep breaking downstream projects 😉

**Comment by fire** [comment]
Ok to merge?

**Comment by akien-mga** [comment]
> Ok to merge?

Yes, but also ok to have a weekend :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
