### PR TITLE
Fix AnimationPlayer method track call oneself with IMMEDIATE mode

### LINKED ISSUE #69681: AnimationPlayer's method track to change oneself with method call mode `IMMEDIATE` is strange
### Godot version

4.0 dev

### System information

Windows 11

### Issue description

AnimationPlayer is ignoring function call tracks, especially when they are used to change the animation. 

The behavior is inconsistent, with certain keys and their functions being called. Keys at the end of the animation are usually not being called, or called sometimes. 

I did a git bisect and the offending commit is this:
https://github.com/godotengine/godot/commit/1fc38336171b775c9cd9a6a33277829fd920d7a2?diff=split

I have uploaded an MRP that at least highlights one such scenario. 

### Steps to reproduce

1. Play the player scene.
2. You should see "reached middle" and "reached end"
3. You only see "reached middle"
4. Try pulling the key back in the "jump_post" animation, you will see "reached end" at certain values

### Minimal reproduction project

[Energy_MRP.zip](https://github.com/godotengine/godot/files/10170080/Energy_MRP.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixes #69681.

If AnimationPlayer method track calls oneself with Immediate mode, the process is interrupted and the state is not updated, so it is safer to update the state before the process.

### CODE REVIEW

**Comment by LakshayaG73** [comment]
Hi, I can confirm that this fixes one scenario. 

However, there are others. There is another where the animation is played again if you try to exit via a method call towards the end, but in the second round, the call method tracks are ignored.

**Comment by TokageItLab** [comment]
@LakshayaG73 Do you mean that you want to restart animation? That is not supported behavior currently, so I think it needs to be a proposal. See also this comment https://github.com/godotengine/godot/issues/64644#issuecomment-1336405961.

**Comment by TokageItLab** [comment]
@LakshayaG73 The behavior is not clear, so PLEASE SEND MRP. Also it is going to be another issue.

**Comment by LakshayaG73** [comment]
So. I didn't need a new MRP. 
[Energy_MRP.zip](https://github.com/godotengine/godot/files/10173437/Energy_MRP.zip)

In this modified version of the same MRP, with your fix applied, both messages are not printed. 

The only difference is that I have pushed the key in 'jump_post' to the end of the animation.

**Comment by TokageItLab** [comment]
@LakshayaG73 I think it is a designed behavior, not a bug.

It seems that the animation player is stopped by the fact that the animation was played to the end after the play was called first in IMMEDIATE mode and then in the same thread.

It is dangerous to update oneself by IMMEDIATE mode in the first place. If there is no reason, you should use DEFERRED mode.

**Comment by TokageItLab** [comment]
@LakshayaG73 If you are really concerned about the delay, use IMMEDIATE mode and extend the end of the animation slightly.

Alternatively, you can send a proposal to set the  method call mode "for each key". This way, you can use the DEFFERED mode only if you want to place the key at the end of the animation.

**Comment by TokageItLab** [comment]
@LakshayaG73 Okay, I changed the location of the exit determination process. I think this solved your problem in Immediate mode, but we need to do a little testing to see if it affects other areas.

**Comment by LakshayaG73** [comment]
So there is one more issue. 

Seems like if the next animation being played is a 'looping' animation, then it loops the current one once as well. 

Uploading an MRP.

**Comment by LakshayaG73** [comment]
[energy - Copy.zip](https://github.com/godotengine/godot/files/10173976/energy.-.Copy.zip)

**Comment by TokageItLab** [comment]
@LakshayaG73 Added a check that if an animation is changed in the middle of a process, it will abort the process that could rewrite the next animation. Please test it.

**Comment by LakshayaG73** [comment]
So after the most recent test, here are the findings:

1: This fixes the issue with non_looped animations looping. 
2: This does not seem to fix the issue with function calls at the end of the animation, and the culprit seems to be this: 

image

I cannot place the key where it needs to be. It only goes a bit forward, or behind. Never at the exact time needed.

**Comment by akien-mga** [comment]
Note that you might be able to force the value by typing it in the Inspector:
- Select the key
- Set its `Time` property in the AnimationTrackKeyEdit inspector

**Review by akien-mga — APPROVED** [review]

**Comment by TokageItLab** [comment]
> Note that you might be able to force the value by typing it in the Inspector:

I think it is not stable workaround at the moment (it seems that very small values, such as 0.0001, can be shifted...). I will look into it more later.

**Comment by LakshayaG73** [comment]
So, this latest version seems to have broken a basic scenario where the method is not being called at all, in the second animation, regardless of the time. 

Can we go back a version?

**Comment by TokageItLab** [comment]
@LakshayaG73 Which case is it? Can you send MRP again?

**Comment by TokageItLab** [comment]
@LakshayaG73 Sorry, the queue may not have been functioning properly because the exit decision was corrupted. I believe this has now been fixed.

**Comment by LakshayaG73** [comment]
Still seeing the same thing with your latest commit. 

The call function track gets completely defunct of the second animation. 

The flow goes like this animation 1 -> transition via method call -> animation 2 -> transition via method call -> animation 3

For each of these, I was calling advance(0) after play(). Removing this advance(0) seems to get rid of the issue.

**Comment by TokageItLab** [comment]
@LakshayaG73 That old commit was dangerous because the flag end_reached = true remained after the animation changed. advance(0) certainly removes that flag, but is probably hackey. If you remove advance(0), is there any more problem? If you still have problems, please send MRP.

**Comment by LakshayaG73** [comment]
Ok. I understand that we can't use that old commit. But there is some other issue here. 

I'm saying that if I have the following: 

```
func end_pre_jump():
	player.animationPlayer.play(animations[1])
	player.animationPlayer.advance(0)
```

This advance call does not go through, and essentially makes the played animation's tracks defunct.

**Comment by TokageItLab** [comment]
@LakshayaG73 As far as using Immediate mode, that advance() is very dangerous.

Let me explain the flow.

1. The old animation's method track calls play().
2. play() rewrites the animation state to the new animation.
3. advance() processes and caches the new animation.
4. The old animation's method track is finished and the cache is deleted.

The problem is that the cache of the new animation is deleted at the time of 4. So advance() should not be called in such a case Immediate mode.

If deleting advance(0) solves the problem, I think this can be merged.

**Comment by LakshayaG73** [comment]
Ok, I think I understand... 

Deleting advance() works well. Calling play() once more after advance() also solves the problem. Is that a viable fix?

**Comment by TokageItLab** [comment]
The method track changing oneself in Immediate mode is quite dangerous, and essentially, it is not recommended to do so except in Differed mode. So I think there is nothing more that can be care on the core side.

**Comment by TokageItLab** [comment]
Oh, the flow is a bit different: advanced() sets is_just_played() to false, so it seems that the old animation stop flag is revived. In any case, advanced() in Immediate mode is dangerous.

**Comment by LakshayaG73** [comment]
> Oh, the flow is a bit different: advanced() sets is_just_played() to false, so it seems that the old animation stop flag is revived. In any case, advanced() in Immediate mode is dangerous.

Can this be fixed? : )

**Comment by TokageItLab** [comment]
I'll take a look at it a little, but I think it's hard. If possible, I will send a follow up PR later. But just don't expect too much.

**Comment by akien-mga** [comment]
Thanks!

**Comment by TypeOverride** [comment]
Seems that this change has broken my implementation now.

Case:
I have on timeline a function track with a function that is set to sec 0.8. In this function in code i do seek(0.2, true) on the timeline. So he repeats non stop the area on the timeline, until i say in code somewhere he should stop doing it, by jumping over the function (marker) that is for repating the part. With seek(0.85, true) for example

But it seems that this is not working any longer. He repeats and repeats regardless.

**Comment by TokageItLab** [comment]
@TypeOverride The `update` option of seek() explicitly means to process that frame, so if there is a MethodTrack or AudioTrack on that frame, it will play it correctly. This is an intentional implementation, not a bug.

To avoid continuous firing, it is straightforward to implement seek on only one frame, or fire `advance()` on only one frame with `update(0.2, false)`.

**Comment by TypeOverride** [comment]
> @TypeOverride Your problem is caused by your implementation approach and is not related to this PR. The `update` option of `seek()` means to process that frame in animation explicitly, so if there is a MethodTrack or AudioTrack on that frame, it will process those accurately. This is an intentional implementation, not a bug.
> 
> To avoid continuous firing, it is straightforward to fire `seek(0.2, true)` on only one frame, or fire `advance(0)` on only one frame after `update(0.2, false)`.

no clue, but it not works anymore. So the Godot version before had a bug. But this "bug" was very natural then. 
Calling a method on method track and jumping to certrain position. Not working anymore. For me it looks more like a bug now. Because i guess much people will try to do something like this, because its very logical to do.

**Pull request merged**
