### PR TITLE
Add a line break to error messages in the script editor

### LINKED ISSUE #71002: Error messages copied without line breaks
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 22H2, Compatibility, GeForce GTX 550 Ti

### Issue description

Multiple lines of error messages are copied without line breaks:
The script editor's error panel shows:
```
Line 6:Expected parameter name.
Line 6:Expected closing ")" after function parameters.
Line 6:Expected ":" after function declaration.
```
But selecting and copying them `ctrl c`, copies them without line breaks:
```
Line 6:Expected parameter name.Line 6:Expected closing ")" after function parameters.Line 6:Expected ":" after function declaration.
```

### Steps to reproduce

- start Godot
- open the attached project
- open the script `Node2D.gd`
The status bar shows an error message.
- click on the red circle with an x in it, and the number 3 to the right of the circle.
The script editor's error panel shows three messages:
>Line 6:Expected parameter name.
Line 6:Expected closing ")" after function parameters.
Line 6:Expected ":" after function declaration.

- select all three lines, and copy them `ctrl c`
- in the script editor, click on the empty line 12 to place the cursor there.
- paste `ctrl v`

### Expected
The copied lines should be pasted on three lines, as they appeared in the error panel.

### Observed
There are no line breaks, they appear on the same line:
```
Line 6:Expected parameter name.Line 6:Expected closing ")" after function parameters.Line 6:Expected ":" after function declaration.
```

### Minimal reproduction project

[issue, error messages copied without line breaks.zip](https://github.com/godotengine/godot/files/10361376/issue.error.messages.copied.without.line.breaks.zip)

### PR DESCRIPTION
**Pull request by 44zb**
Fixes #71002

### CODE REVIEW

**Comment by duianto** [comment]
I just noticed that the script editor's error/warning panel seems to line wrap in two columns.
That might also have to be taken into consideration with this fix.

To see this message:
- create a new script 
- click on the yellow triangle on the right side of the script editors status bar
- and reduce the Godot window's width

Godot_v4 0-beta10_win64_KmBenuiyzG

**Comment by ZangEldor** [comment]
> Fix for #71002 
> 

Please change the description to: "Fixes #71002" (without quotes) so github will link this PR to the issue page correctly.

**Comment by 44zb** [comment]
Hi @akien-mga, done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
