### PR TITLE
Gdextension declarative property

### PR DESCRIPTION
**Pull request by touilleMan**
See https://github.com/godot-rust/gdextension/issues/19#issuecomment-1308038369

ping @Bromeon 

On top of that, I've reverted the change on `GDNativeExtensionScriptInstanceInfo` I made in https://github.com/godotengine/godot/pull/67750, I thought it would be simpler to have a similar interface between GDExtension and GDNativeExtensionScriptInstanceInfo, but after deeper investigation it turns out it is much better to have `GDNativeExtensionScriptInstanceInfo` being just a proxy over Godot's internal `ScriptInstance`

### CODE REVIEW

**Comment by Bromeon** [comment]
For my understanding, was it possible to add/remove/rename properties for extensions at runtime before this PR (i.e. dynamic list)?
Or was the implicit assumption that the data returned via callback would be never-changing?

Also, in light of future extension reloading (https://github.com/godotengine/godot/issues/66231), reloading would likely be done on a per-class level, requiring re-registration of the entire class including methods and properties?

**Comment by touilleMan** [comment]
> For my understanding, was it possible to add/remove/rename properties for extensions at runtime before this PR (i.e. dynamic list)?

[In theory yes](https://github.com/godotengine/godot/blob/140f0395470975f1c20648ffd8807be113a9e373/core/object/object.cpp#L488-L497) given extension's `get_property_list` is called each time `Object::get_property_list` is called.

However I'm pretty sure this is not a feature but an implementation detail: having dynamic property is going to make things much more complex (think of the property view in the editor :/), on top of that all Godot internal classes don't have dynamic property and hence nobody is going to think about correctly handling that (e.g. avoiding querying the property list once and keeping it in cache).

So I think this API given the wrong kind of assumption and should be corrected ;-)

>  Or was the implicit assumption that the data returned via callback would be never-changing?

So far

**Comment by raulsntos** [comment]
> on top of that all Godot internal classes don't have dynamic property

If I understand correctly what you mean by dynamic properties, doesn't Curve do that? And I'm sure I've been seen other Godot classes where the properties returned by `get_property_list` change during runtime.

https://github.com/godotengine/godot/blob/140f0395470975f1c20648ffd8807be113a9e373/scene/resources/curve.cpp#L561-L587

**Comment by Bromeon** [comment]
How does Godot even know that the property/method list has changed? For this dynamic-ness to be remotely useful, it needs to call those callbacks prohibitively often -- meaning the extension library code has to do smart caching (aka duplication) or will waste performance just copying the same data over and over.

Wouldn't a better design be GDExtension library **notifying** Godot about a change in properties, for example simply by providing the new properties through a `set_property_list(class, properties, ...)` call?

**Comment by raulsntos** [comment]
> How does Godot even know that the property/method list has changed?

You call `notify_property_list_changed`.

**Comment by touilleMan** [comment]
Wow thanks for pointing this out @raulsntos !

I didn't know about this `notify_property_list_changed` signal and the need for it from `Curve`.
(to be honest this seems like a horribly complicated and error prone mechanism, but I'm pretty sure this is there for a reason :smile: )

So of course this PR is pointless if property can be updated dynamically !

(I'll create a new PR with only the revert of the change on GDNativeExtensionScriptInstanceInfo then)

**Comment by groud** [comment]
According to the PR review meeting, this seems not needed anymore. Closing.

**Pull request closed without merging**
