### PR TITLE
Rename KEY_RETURN to KEY_ENTER and KEY_ENTER to KEY_KP_ENTER

### LINKED ISSUE #7695: Better document the difference between KEY_ENTER and KEY_RETURN
**Operating system or device - Godot version:**
Ubuntu, Godot  2.1.2

**Issue description:**

The scan codes for the Enter keys don't work.

**Steps to reproduce:**
```
func _ready():
	set_process_input(true);

func _input(ie):
	if ie.type == InputEvent.KEY:
		if ie.pressed && ie.scancode == KEY_ENTER:
			get_tree().call_deferred("quit");
```
Hitting enter and nothing happens.

**Link to minimal example project:**
:

### PR DESCRIPTION
**Pull request by bojidar-bg**
Closes #7695

### CODE REVIEW

**Comment by akien-mga** [comment]
Wait, why? "Return" is the canonical name of the main "insert a carriage return and/or validate entry" key, and "Enter" is typically written on the Enter key of the keypad (while the Return key typically shows a return symbol).

**Comment by bojidar-bg** [comment]
@akien-mga ~ Quoting @reduz on https://github.com/godotengine/godot/issues/7695#issuecomment-320502308:
> despite the proper name, I also think it's less confusing to rename to KEY_ENTER and KEY_KP_ENTER . We are still in time if you want to change this before 3.0. Any volunteers?

**Comment by akien-mga** [comment]
Well I don't agree, but if you guys prefer it this way, I won't fight :)

**Comment by RandomShaper** [comment]
What do you think about KEY_RETURN and KEY_KP_ENTER as a fully explicit,
everyone-happy solution?

Or even prefixing all numpad keys with KEY_KP_. By the way, does 'KP' stand
for 'key pad'?

English is not my primary language, but if that's the meaning, maybe NUMPAD
(or the shorter, and uglier, NP) would be better. To me, num-pad is not an
explicit reference to the numeric pad/keyboard.

**Comment by Zireael07** [comment]
KEY_KP is a more-or-less universal way that engines refer to numpad keys (UE4, pygame, libtcod, bearlibterminal, unsure about Unity) so I'm +1 for prefixing all numpad keys with KEY_KP.

**Comment by RandomShaper** [comment]
If KP is universal, then following the trend is something good. Nothing against.

**Comment by reduz** [comment]
@akien-mga to me the key name is "return" too, but for the new generations it's "enter". A lot of people got confused by this, and this change (for bad or good), makes Godot more user friendly

**Comment by reduz** [comment]
IBM Labelled it "Enter" since their first IBM PC models, it's their fault..

**Comment by reduz** [comment]
https://ux.stackexchange.com/questions/54461/should-i-use-the-name-enter-or-return-key

**Comment by reduz** [comment]
image

**Comment by akien-mga** [comment]
Wow, I don't feel that old, I was born in 1991 :P
Let's go with what pleases the millennials then ;)

**Pull request merged**
