### PR TITLE
Initial .psd support implementation

### PR DESCRIPTION
**Pull request by anunknowperson**
Implements: https://github.com/godotengine/godot-proposals/issues/2758

**Why is it necessary?**

Recently, I've been working on skeleton 2D animation, and I've found that transferring a layered picture from my graphics editor (SAI) to Godot is a time-consuming process that doesn't yield good results. For example, if my image has 50 moving parts, I would need to manually export 50 pictures to jpg and then set each picture to the right position in the editor. This process is not only time-consuming, but it can also create clutter in the file system of the project.
This same issue also applies to Cutout animation.

There are also examples of using images with layers, such as in some Valve games where PSD layers with different color themes are used to show which team a character belongs to.

**Why is PSD the preferred format over other formats that also support layers like .kra?**

It's important to note that, in this context, PSD shouldn't be associated solely with the proprietary software, Photoshop.
PSD has become an industry standard over the years, and all advanced image editors now support exporting to it. Additionally, PSD is the only format that all editors can export to, including Photoshop, SAI, Krita, GIMP, and others.

Considering user-friendliness, supporting PSD could significantly improve the workflow for artists and animators.

**Why is it implemented as a module and not as a GDNative plugin or something else?**

The reason for implementing it as a module is that it's a feature that will be beneficial, for example, to people who create 2D animations
In addition, it's essential that the feature is supported on all platforms.

There is no platform-dependent code in the module.

**Is this PR completed or still in progress?**

This is just one example of how the implementation could look, and I'm not entirely sure of the technical details. I'd appreciate the team's feedback on how to best implement this feature and rewrite the module accordingly.

Perhaps it would be best to create an abstraction for textures that can support layers, and then convert all PSD files to this format, similar to how regular image formats are handled.

**Test project**
[psd-test.zip](https://github.com/godotengine/godot/files/10753346/psd-test.zip)

**Demonstration**
https://youtu.be/HhiW25nzqLk

### CODE REVIEW

**Comment by anunknowperson** [comment]
@fire

**Comment by aaronfranke** [comment]
> The reason for implementing it as a module is that it's a feature that will be beneficial to everyone.

It's not a feature that's beneficial to everyone. For example, it's not beneficial to me. I also have not encountered many people who have asked for PSD support in Godot.

**Comment by anunknowperson** [comment]
> It's not a feature that's beneficial to everyone.

At a minimum, it is a feature that will be useful for people who do animation (and since Godot is used more for 2D projects, this is a large number of people).

I will say this, the usefulness of psd is equal in usefulness to many other features that are implemented as modules.

**Comment by anunknowperson** [comment]
> GDExtension can be used on all platforms (if it can't that's a bug). 
Even on HTML5 and Android? I don't know, there's just not much documentation on the Internet yet.

**Comment by anunknowperson** [comment]
> > It's not a feature that's beneficial to everyone.
> 
> At a minimum, it is a feature that will be very useful for people who do animation (and since Godot is used more for 2D projects, this is a large number of people).
> 
> > For example, it's not beneficial to me.
> 
> You can say that about absolutely any PR. Do you work with 2D cutout/skeletal animation? I mean that it will be useful for those who work with the already existing functionality of the engine.
> 
> I will say this, the usefulness of psd is equal in usefulness to many other features that are implemented as modules.
> 
> And I do not know why there is a tendency to put everything in plugins, including basic functionality.

**Comment by anunknowperson** [comment]
> I will review the code and check it for errors. There is a disagreement with aaron that we won't be able to merge, but we can still keep the feature as an out of engine tree and at some point convert to godot engine gdextension.

I don't think in its current state it can be merged into the main branch at all, but for GDExtension I think this level is acceptable.

**Comment by fire** [comment]
1. The psd sdk is an opensource bsd license
2. https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html has some sections related to "Some checks were not successful.

**Comment by anunknowperson** [comment]
Perhaps one way to implement this properly is to make an interface for images with layers in the core and create importers for different formats using GDExtension.

However, since this is the only standardized format among all image editors,  I d'not think it is necessary to take it into a plugin.

**Comment by anunknowperson** [comment]
> 4\. I can try removing the errors in a branch. Will let you know

Do you know how to fix this?
Error: thirdparty\psd_sdk\PsdPlatform.h(43): error C2220: the following warning is treated as an error
Warning: thirdparty\psd_sdk\PsdPlatform.h(43): warning C4005: 'NOMINMAX': macro redefinition

The rest of the warnings I can now fix myself and improve the code style and variable names a bit.

**Comment by YuriSizov** [comment]
Since the proposal was not met with interest or support, this is very unlikely to be merged. You can follow the path of GodotSteam and release your module and provide custom builds as releases for those who require it. Though a GDExtension would be more appropriate for something like that for Godot 4.

**Comment by anunknowperson** [comment]
> Since the proposal was not met with interest or support, this is very unlikely to be merged. You can follow the path of GodotSteam and release your module and provide custom builds as releases for those who require it. Though a GDExtension would be more appropriate for something like that for Godot 4.

Basically, I was expecting something like this. I think that whoever needs it can take the code from this PR and build the engine himself.

**Comment by fire** [comment]
I believe that psd is a more popular format and is used more than for example krita or gimp's internal format. So I'll try to find some statistical evidence.

I am reviewing the guidance from https://www.loc.gov/preservation/digital/formats/fdd/fdd000523.shtml

**Comment by anunknowperson** [comment]
> I believe that psd is a more popular format and is used more than for example krita or gimp's internal format. So I'll try to find some statistical evidence.

At least PSD is the most popular format for exporting.

Most programs only have export to their own format or to PSD.

(if we consider only formats that support layers)

**Comment by fire** [comment]
My branch is here https://github.com/V-Sekai/godot/tree/psd.

Significant notes:

1. Uses stream peer instead of native file.
2. Code style changes
3. mingw changes

**Comment by YuriSizov** [comment]
@fire Nobody is trying to implement Krita's or Gimp's internal format support... In general, supporting proprietary formats where there is no standardization or overwhelming industry adoption (cough FBX cough) is not a task for the core of the engine.

**Comment by fire** [comment]
As noted in the the govment report there is overwhelming industry adoption of psd.

> As stated in [Wikipedia](https://en.wikipedia.org/wiki/Adobe_Photoshop), Photoshop has "...become the industry standard not only in raster graphics editing, but in digital art as a whole." [Market data](https://www.datanyze.com/market-share/graphics--462) showcases that Adobe Photoshop comprises a significant share of the graphics industry, bolstering the claim that it is one of the most popular and widely used graphics editing software applications out there. Photoshop has become a tool for a wide variety of users including; web developers and designers, graphic artists, photographers, and other creative professionals. This has led to a wide range of support for PSD files. There is substantive support to convert PSD or PSB files to other traditional formats including: [TIFF](https://www.loc.gov/preservation/digital/formats/fdd/fdd000022.shtml), [JPEG](https://www.loc.gov/preservation/digital/formats/fdd/fdd000017.shtml), [PNG](https://www.loc.gov/preservation/digital/formats/fdd/fdd000153.shtml), [EPS](https://www.loc.gov/preservation/digital/formats/fdd/fdd000246.shtml), [GIF](https://www.loc.gov/preservation/digital/formats/fdd/fdd000133.shtml) using Photoshop as well as a variety of free web conversion applications. Compared to other commonly used raster formats, the PSD format keeps layers separate so converting to other image formats flattens the image into a single layer. Both Windows and Mac operating systems support a variety of applications both open source and proprietary.

**Comment by anunknowperson** [comment]
> where there is no standardization or overwhelming industry adoption
But all advanced graphics editors support PSD, isn't that overwhelming industry adoption?

**Comment by YuriSizov** [comment]
Yes, but nobody is importing those documents into game engines, layers are exported as sheets or individual files. And your proposal didn't show any interest among Godot users in this feature.

**Comment by fire** [comment]
I don't believe that Aaron is representative of the class of people who use psd. Please try a poll.

**Comment by anunknowperson** [comment]
> Yes, but nobody is importing those documents into game engines, layers are exported as sheets or individual files.
I originally said that there is, for example, Valve, which uses PSD in its projects.

Also in the context of skeletal animation, any program like Spine or Creature2D supports PSD import. If we want to make 2D animation in Godot handy, we also need to add support for this.

> And your proposal didn't show any interest among Godot users in this feature.

First of all, a lot of people put a Hooray emotion on original post, secondly, this PR created less than a day ago, and thirdly we really need to conduct a survey, not just the opinion of three people

**Comment by YuriSizov** [comment]
@anunknowperson I am talking about game engines. Yes, digital art is often created in Adobe Suite, and as there is a long history of adoption for their tools, other tools have to accommodate some form of compatibility. But PSD is not used as a game engine asset, instead rasterized files and sheets are used.

@fire You have already tried a poll. Feel free to open a new proposal or reopen the old one, if you think there is enough demand now. But as it stands, there is no benefit in this for the engine's official distribution. Please avoid flame wars in place of discussions.

**Comment by anunknowperson** [comment]
> I am talking about game engines.

But I'm also talking about engines, and I've already given some examples of how they are used in the engine and not outside of it. A format that supports layers can be very useful.

And the survey should not be conducted among the developers of the core, but among the people who use 2D tools and create animations, etc..

**Comment by YuriSizov** [comment]
@anunknowperson Please open a proposal and make sure that users who need this feature show their support. This discussion should happen before making changes, and it is not suitable for a PR.

All I'm saying is that there was already a proposal and it didn't show any support. And in general this is not something we would include in the engine, unless absolutely necessary (so requirements for relevance are even higher). An extension is a perfectly suitable solution if there is only limited interest.

**Comment by Zireael07** [comment]
@YuriSizov the linked proposal has five hearts and 4 hoorays to one confused frown and two down thumbs. I wouldn't say that's 'no support'

**Comment by neikeq** [comment]
Is PSD desired only as an intermediate format or are there other use cases? As an intermediate format, I think it could be an editor-only importer, converted to a different format on export.

**Comment by anunknowperson** [comment]
> Is PSD desired only as an intermediate format or are there other use cases? As an intermediate format, I think it could be an editor-only importer, converted to a different format on export.

Yes, in theory we could create an abstraction, something like LayeredTexture, and create editor-only PSD importer, an importer for it.

**Comment by Calinou** [comment]
> Yes, in theory we could create an abstraction, something like LayeredTexture, and create editor-only PSD importer for it.
>
> And if the engine will have LayeredTexture abstraction, the PSD import can be moved into the plugin.

There's already a TextureLayered class an abstract class for Texture3D and TextureArray (and more), so I'd choose another name.

**Comment by dsnopek** [comment]
I'm not so sure about the idea of a "layered texture" resource, where we can access the individual layers by name - it just seems out of place.

How would this actually be used in the editor? Let's say I want to make a `Sprite2D` using one of the layers: how would I actually do that? I can't drag the .psd file from the file explorer into the "Texture" property because it refers to multiple images. How would I pick one? Same goes for making a `TileSet` or adding frames to `SpriteFrames` - it seems like this concept would have big implications to the UI all over the editor.

I could sort of see the editor generating new `Texture2D` resources (not sure what that'd be - *.res files?) into the project's filesystem, similar to how importing a GLTF can lead to `Material` resources (as *.material files) getting generated, which you can then address individually. Then you could drag those generated .res files into the various places expecting a `Texture`.

Also, on a non-technical (and very subjective) note, as others have commented here and on the proposal, adding support for PSD seems like it'd be better as a GDExtension. When comparing to XR, we have the open standard XR APIs in the core engine (WebXR and OpenXR), and the proprietary APIs in GDExtensions. While I don't know if we stick to that for other formats (probably not ;-)), it's a pattern that I personally quite like, considering Godot's tendency towards open standards.

**Comment by lyuma** [comment]
PSD support is quite common across a variety of tools and engines, including Unity and Unreal Engine. Even Blender supports PSD files as textures, despite being open source.

I'm a little confused why the original proposal was closed when the only two negative comments came from one person. Not every feature is beneficial to every user: that doesn't mean it is without merit.

Is there a way you could open a new proposal, or is it forever locked away because three people gave thumbs down to the original proposal? A PR really isn't the right place to have this discussion.

From a technical perspective, it has several challenges that need to be discussed, such as how to handle multiple layers, and what to do with the wide breadth of PSD files some of which certainly aren't 100% supported by MolecularMatters/psd_sdk.

I could see arguments for implementing as extension, but it would be nice to see a proper discussion, perhaps analyzing the amount of code added in psd_sdk, and the maintainability impact, since Godot core developers will be forced to keep this thing working, contrasted with the benefit to users by having the same PSD files they use in Blender and Unreal also work in Godot.

**Comment by dame-ng** [comment]
Just wanted to add that I'm surprised there is such reluctance in adding this feature, in fact I'm surprised that it is still not added.
It is a VERY common workflow that allows artists to skip the export process altogether by just editing and saving the .psd file directly and having it updated in the engine.
As much as I dislike Photoshop and the format itself, PSD is the only universally supported one,  and can be seamlessly used in actually good software like Clip Studio Paint or the aforementioned Paint Tool SAI.

**Comment by zedrun00** [comment]
hi， I in windows sys building this branch.
psd_sdk not work， import .psd file anyway print err.

@anunknowperson

**Comment by anunknowperson** [comment]
> Hi， I in windows sys use mingw building this branch.
> psd_sdk not work， import .psd file anyway print err.
> **_**ERROR**_ [PsdExtract] File seems to be corrupt, signature does not match "8BPS"**
> @anunknowperson

Does this happen with all files or just one? Try another file. Also make sure that you compiled not the latest version of this PR, but the first commit: 3f84964ad3be64d665d1150897dfb983471a48d5.

**Comment by zedrun00** [comment]
> > Hi， I in windows sys use mingw building this branch.
> > psd_sdk not work， import .psd file anyway print err.
> > **_**ERROR**_ [PsdExtract] File seems to be corrupt, signature does not match "8BPS"**
> > @anunknowperson
> 
> Does this happen with all files or just one? Try another file. Also make sure that you compiled not the latest version of this PR, but the first commit: [3f84964](https://github.com/godotengine/godot/commit/3f84964ad3be64d665d1150897dfb983471a48d5).

I tried [3f84964]. The commit building failed.
This Error:
error_1

**Comment by anunknowperson** [comment]
> I tried [[3f84964](https://github.com/godotengine/godot/commit/3f84964ad3be64d665d1150897dfb983471a48d5)]. The commit building failed.
> This Error:

I'll try to check back later. Maybe the problem is mingw instead of msvc

**Comment by zedrun00** [comment]
> > 我尝试过[ [3f84964](https://github.com/godotengine/godot/commit/3f84964ad3be64d665d1150897dfb983471a48d5) ]。提交构建失败。
> > 这个错误：
> 
> 我稍后会尝试回来查看。也许问题是 mingw 而不是 msvc

thank for you :)

**Comment by Lykdraft** [comment]
Because no game engine has a psd importer, because it doesn't matter..!?

>>> Unity (v5.x) .psd importer...

https://docs.unity.cn/Packages/com.unity.2d.psdimporter@5.0/manual/index.html

**Comment by RCThales** [comment]
Why are people saying no engine supports PSD? Unity supports it and it is extremely useful as you don't have to keep overwriting ur art a billion times. You can modify it on the psd editor and it reflects right away in the engine. This is a very useful feature for anyone who will use sprites.

**Comment by fire** [comment]
The clearest argument for not supporting PSD is it's a closed standard.. except it's not true.

https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/

Other arguments regarding binary bloat (might be due compared to demand.) and lack of use (I don't believe this one is valid).

**Comment by Odaimoko** [comment]
I guess psd is so complicated and every studio can end up with different standards. Some want to use blend mode, some want only the raw images.

It is better to write your psd exporter in any language you like (python, js, csharp etc), generate intermediate files and data structures, and import them into Godot with png or some other image formats.

**Comment by aaronfranke** [comment]
Closing for the following reasons:

1. This does not need to be in core, it can be done in GDExtension. A reason cited for having this feature is to support this "on all platforms". GDExtension can already do this, it is available on all platforms.
2. A reason cited for having this feature is that it "will be beneficial to everyone". This is a baseless claim. Most game devs use PNG and JPEG for images, not PSD. This is not commonly needed, therefore it should be in an extension.
3. It's huge. If it's huge and it does not need to be in core, then that is a further reason it must be in an extension.
4. This is implementing support for a proprietary file format specific to one company's proprietary software. This is a huge slippery slope. Should we also implement GIMP's XCF format? Where does it end? In general, we would prefer to only support open formats designed to be interoperable.

In my comment from over a year ago where I used myself as a counterexample to "everyone", I was not claiming that my experiences represent the industry. The point is that you can't just claim "everyone" will benefit without providing any sources whatsoever. The burden of justification for PSD support is on the people proposing to add PSD support, not on engine maintainers. The fact is that the amount of people who will benefit from this is far from "everyone". If the need for PSD was actually important, somebody would've made a GDExtension for it. Since such an extension does not exist, this tells me that the demand for PSD is actually very very low, or else people would make an extension.

To clarify, I am not against people using PSD in their projects. If you want to use PSD, all the power to you, go ahead and use PSD by installing an extension! I like it when people add support for more file formats to Godot, I just did this myself recently with implementing [glTFX](https://github.com/aaronfranke/godot-gltfx-reference-format). But this needs to be done in an extension first, and can only be considered to be a part of the engine if such an extension had many thousands of users.

**Comment by fire** [comment]
I moved the code here https://github.com/V-Sekai/godot_psd.git if anyone wants to make it a gdextension on 4.4.

```
ERROR: PSD document initialization failed.
   at: parse (modules/psd/psd_texture.cpp:154)
```

Currently failing at PSD document initialization failed.

**Pull request closed without merging**
