### PR TITLE
GDScript: Fix POT generator skips some nodes

### LINKED ISSUE #85848: POT generation ignores subscripts
### Tested versions

See "System information" below.

### System information

Godot v4.1.4.rc (2d3b2abcf) - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce GTX 970 (NVIDIA; 31.0.15.2698) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

POT generation ignores tr() expression in dictionaries:
```python
var strDeclarer = { 'N':tr("North"), 'E':tr("East"), 'S':tr("South"), 'W':tr("West") }[declarer]
var strVulnerable = { 0:tr("none"), 1:tr("both"), 2:tr("NS"), 3:tr("EW") }[vulnerable]
```
Strings as tr() parameters do not show up in the POT file.

### Steps to reproduce

FYI: [Creating the PO template - Automatic generation using the editor](https://docs.godotengine.org/en/stable/tutorials/i18n/localization_using_gettext.html#automatic-generation-using-the-editor)

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dalexeev**
* Fixes #85848.

### CODE REVIEW

**Review by vnen — APPROVED** [review]
LGTM

**Review by adamscott — APPROVED** [review]
Looks good for me too!

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
