### PR TITLE
Remove duplicated filter, Fix #1795

### LINKED ISSUE #1795: Duplicated filter
captura de tela de 2015-05-03 12 10 38

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Its okay if I remove this line?

### CODE REVIEW

**Comment by reduz** [comment]
I think this is needed... the reason .scn was forced on top was so it's the default extension when a file chooser is created.

**Comment by guilhermefelipecgs** [comment]
Well, I don't know how this exactly works, I don't have much skill with godot yet.
 
I tested with "Open Scene", "Open File", "Save Scene As" and in this cases works fine, but I see now that "Quick Open Scene" no. This was the cases you referred to?

In the cases that works fine, the filters always appear in this order: *.scn, *.res, *.xscn, *.xml.

Are you worried that this order can change?

I will try to better understand this logic.

**Comment by guilhermefelipecgs** [comment]
Correction, Quick Open Scene with this commit works at the same way that v1.1.rc2.
Maybe I don't understand where is the problem.

**Comment by guilhermefelipecgs** [comment]
This line that I removed don't remove the first occurrence of the .scn, only the duplicated, like this:
Now:
*.scn, *.res, *.xscn, *.scn, *.xml
---------------------------^
With FIx:
*.scn, *.res, *.xscn, *.xml

**Comment by guilhermefelipecgs** [comment]
And others formats like .sgp and .shd continues appearing in first option if you are opening the corresponding format. Only when you will open GDScript the .gd not appears in first, but the branch master behaves like this as well.

**Comment by reduz** [comment]
the reason .scn appears first is because it's harcoded, so when you try to save, it offers that extension by default

**Comment by guilhermefelipecgs** [comment]
Well, it's working like you said.
When you have time try remove this line in your project to see.

**Comment by akien-mga** [comment]
I can confirm the bug in the current master branch, i.e. a duplicate "*.scn" in the filters when loading a scene file.
```
*.scn, *.res, *.xscn, *.scn, *.xml
---------------------------^
```
There is no duplicate when _saving_ a scene file, but it likely uses a different logic as it also proposed *.tscn and *.tres nowadays.


I've tested the PR, the fix works just fine, good to merge IMO.

**Pull request merged**
