### PR TITLE
Fix inertial scroll, add smooth scroll +more

### LINKED ISSUE #12965: Add smooth scrolling to all scrollable controls
All kinds of controls that feature scrolling (like TextEdit or ScrollContainer) should feature optional smooth scrolling, both in the editor and games. The script editor already features "smooth" scrolling, but it doesn't really feel good to use (I personally disable it, as I find it hinders me more than anything).

Here's a lengthy, well-written article on the subject (and why it's important): [Scrolling with pleasure](https://pavelfatin.com/scrolling-with-pleasure/)

### LINKED ISSUE #45402: ScrollContainer with a deadzone suddenly snaps/flickers on touch
**Godot version:** 
Tested on 3.2.3, 3.2.4, and a build of 'latest' (4.0) made today.

**OS/device including version:** 
Issue is only present on mobile. Device tested was a Samsung Galaxy S8 US with a Snapdragon 835 SOC. Tested with GLES3 for 3.2.3, 3.2.4 and Vulkan for 4.0/'latest'

**Issue description:**
Issue occurs on actual touch screens only, when interacting with a ScrollContainer node that has a deadzone.
_Expected behavior:_
When passing the deadzone, the container will scroll starting from its current position and continuing smoothly from there. The expected behavior can be observed when using a mouse and enabling 'Emulate touch from mouse' in the project's settings.
_Problematic behavior:_
When passing the deadzone, the container will instantly scroll a large and unpredictable amount for one frame. If the drag motion continues, the scroll will typically snap back to the expected position. However, with slow finger movement, it will flicker between scroll positions.

**Steps to reproduce:**

1. Create a ScrollContainer node, and give it content that is large enough to allow scrolling.
2. Set the deadzone of the ScrollContainer to a value above zero. (The snapping behavior is more noticeable with large values, while the flickering is more noticeable with smaller values)
3. Run the project on a touch screen device and attempt to scroll the container with your finger. (Slower movement cause more noticeable effects) (This _does not_ occur with emulated touch, only on an actual touch screen)

**Minimal reproduction project:**

[ScrollTest.zip](https://github.com/godotengine/godot/files/5861387/ScrollTest.zip)

**_I have already found the cause of this issue and will submit a pull request fixing it shortly!_**

### PR DESCRIPTION
**Pull request by threethan**
## Summary
I made quite a few changes, however all are interlocked so they can't really be split to multiple branches.
I tried to be as thorough as possible with the description below, however, in short: 
- Scroll behaves much nicer on mobile
- A bunch of options have been added

## List of Changes
- New options have been added to project settings under a new gui>scroll section
- Completely rewrote inertial scrolling on touch. This fixes various issues, and make things far more consistent.
     - Various issues involving scroll_deadzone are now fixed. (Resolves godotengine/godot#45402)
     - Inertial scroll now decelerates quadratically instead of linear. This is more accurate to real-life friction, more consistent with other mobile applications, and subjectively feels better. It also fixes an issue where deceleration would be far too much on scaled nodes or windows.
     - The amount of inertia can be configured in project settings  (gui>scroll>intertial_scroll_duration_touch)
- Added a scroll_step parameter. When scrolling with the mouse wheel, each notch will scroll by one page * scroll_step. The default is 1/8, which is the same as the previously hard-coded behavior.
     - The default value of scroll_step can be set in project settings (gui>scroll>default_scroll_step)
- When focus is within a scroll container, ui_page_up and ui_page_down input actions will now work as expected. (Previously they did nothing)
- Added a scroll_smooth parameter. This will enable Windows 10 - style smooth scrolling when scrolling using the mouse wheel, page up & down, or with follow_focus
     - The default value of scroll_smooth can be set in project settings (gui>scroll>default_scroll_smoothed)
     - The duration of the smooth scrolling animation can be set in project settings (gui>scroll>smooth_scroll_duration_button)

## Changes to default behavior
I have done my best to make these changes without breaking compatibility or changing default behavior. By default only the following are changed:
- The default focus mode of a scroll_container is not CLICK instead of NONE. This is required for page up & down to work. It can manually be changed back to NONE, which revert page up & down to doing nothing, unless a child element is focused.
- Inertial scrolling will always use the new, fixed physics.
- The default_scroll_deadzone project setting is now under gui>scroll instead of gui>common
All other new functionality requires settings to be manually changed by the user.

## Context
Tested with:
 - 3.2.3:
     - Windows (in editor, exported debug, exported release)
     - Android (debug, release, custom build)
 - 4.0.dev:
     - Windows (in editor, debug)
     - Android (debug)

I previously submitted a similar pull request that only fixed bugs, however I closed it in favor of this one. This pull fixes all of the bugs fixed by the first one and more, by fixing the underlying issues.
This pull request *does not* include documentation for the new options. If/once it is merged to master, I will submit a second pull with new documentation added.
I have a 3.2 compatible version ready if desired, see [threethan/godot#3.2](https://github.com/threethan/godot/tree/3.2)

*Bugsquad edit: This closes https://github.com/godotengine/godot/issues/12965.*

### CODE REVIEW

**Comment by threethan** [comment]
I would also like to note that I believe sudden, transitionless changes are bad UX design, and as such I am of the opinion that smooth scrolling should be on by default.
If have tested this, and the smooth scrolling looks and works great in the editor.

To reiterate, smooth scrolling is *disabled* by default, in the interest of keeping default behavior unchanged.
I think, in the interest of good design, it *should* be enabled by default.

This is, of course, open to discussion, and I am opting to keep it off unless manually enabled so that it can be decided on independently of this pull, which is focused on fixing bugs and adding options.

**Comment by YeldhamDev** [comment]
Please squash your commits: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by threethan** [comment]
> Please squash your commits: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

Done!

**Comment by YeldhamDev** [comment]
It seems you added another commit by accident.

**Comment by threethan** [comment]
will try to resubmit another time. rebase didn't do what I expected and it seems there is no way to fix.

**Comment by Calinou** [comment]
@threethan Do you still have the original changes somewhere (even locally on your PC)? The commits listed in this pull request are unrelated to your changes, which makes it impossible for someone else to salvage your work and rebase it on the latest `master` branch. (Which is fine, if you don't have time to finish working on this feature.)

**Comment by threethan** [comment]
Thanks for reaching out! I had a lot going on and totally forgot about this. I've made a new PR: #47931

**Pull request closed without merging**
