### PR TITLE
Mono: Add CPPPATH only to env_mono and cleanup build scripts

### PR DESCRIPTION
**Pull request by neikeq**
Moved all our configuration from `config.py` to a script called by SCSub, which is something I wanted to do for some time (`config.py`'s `configure` didn't seem like the right place to do all that as it's also called on cleanup).
Moved all build scripts to `modules/mono/build_scripts/`.

All compiler flags are now added only to `env_mono`. This way we avoid possible conflicts with other modules. Fixes #26453

### CODE REVIEW

**Comment by akien-mga** [comment]
```
  File "/home/travis/build/godotengine/godot/modules/mono/build_scripts/godotsharptools_build.py", line 99, in find_msbuild_unix
    hint_path = os.path.join(hint_dir, filename)
NameError: global name 'filename' is not defined
```
https://travis-ci.org/godotengine/godot/jobs/500545683

**Comment by akien-mga** [comment]
```
In file included from modules/mono/csharp_script.h:39,
                 from modules/mono/csharp_script.cpp:31:
modules/mono/mono_gc_handle.h:34:10: fatal error: mono/jit/jit.h: No such file or directory
 #include <mono/jit/jit.h>
          ^~~~~~~~~~~~~~~~
```

**Comment by neikeq** [comment]
Fixed!

**Comment by akien-mga** [comment]
Thanks. Looks good to me, but I'd suggest to let @hpvb give it a spin on MinGW to ensure that everything still builds as expected for official releases.

**Comment by neikeq** [comment]
Oh, great...

**Comment by neikeq** [comment]
Should be ready to merge now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
