### PR TITLE
Revert "Unify http- and percent- encode/decode"

### PR DESCRIPTION
**Pull request by RandomShaper**
This reverts commit b76ee30917c63211ac9e94a21bebbddf518d169f.

The reverted commit is the one from #17583 that has caused some trouble.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@RandomShaper @akien-mga Can the removal of the `percent_` methods be re-evaluated for 4.0? I can't reproduce any issues with this, the only difference that I can see is that one uses uppercase letters and the other uses lowercase letters.

```gdscript
	print("Ж Godot Engine:'docs'".percent_encode())
	print("Ж Godot Engine:'docs'".http_escape())
	print("Ж Godot Engine:'docs'".percent_encode().percent_decode())
	print("Ж Godot Engine:'docs'".http_escape().http_unescape())
	var http = HTTPClient.new()
	var dic = { 'arg1' : 'Ж', 'arg2' : 'foo' }
	print(http.query_string_from_dict(dic))
```

Output:

```
%d0%96%20Godot%20Engine%f0%9f%99%82%3a%27docs%27
%D0%96%20Godot%20Engine%F0%9F%99%82%3A%27docs%27
Ж Godot Engine:'docs'
Ж Godot Engine:'docs'
arg1=%D0%96&arg2=foo
```

For #17583, it seems that the only reason these were kept is because of GDNative compatibility. If that was the concern, then a wrapper method should've been kept instead of keeping a duplicate method in core. However, we have the opportunity to break compatibility with GDNative for Godot 4.0.

**Comment by akien-mga** [comment]
This could be redone yes, or even back to the original implementation which unified those as `uri_encode`.

**Comment by aaronfranke** [comment]
Yeah. I think `url` is more common than `uri`, and `url` is more specific to web links: https://danielmiessler.com/images/url-uri-url-miessler-2020.png

Also, I noticed this comment: https://github.com/godotengine/godot/blob/master/tests/test_string.h#L1166

**Comment by RandomShaper** [comment]
I'd take some inspiration from the JS URI encode API: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

Maybe we even would better have separate full and component-wise encoding methods. If I remember correctly, when I worked on that, I considered the possibility, but I can't remember the reason now.

**Pull request merged**
