### PR TITLE
Fixed Pos/Rot/Scl 3D Tracks insertion in `SkeletonEditor`

### PR DESCRIPTION
**Pull request by TokageItLab**
Fixed Pos/Rot/Scl 3D Tracks insertion in `SkeletonEditor` to be adopt #53689. Also, implemented to pop up a dialog when inserting multiple tracks with `SkeletonEditor`.

スクリーンショット 2021-10-17 0 56 11

I also added `Animation::find_tracks()`, since we now have multiple (Pos/Rot/Scl) tracks with the same path name. However, now it coexists with `Animation::find_track()`, so if we are not considering performance, we may as well unify `Animation::find_track()` into `Animation::find_tracks()` for maintainability.

By the way, anyone mentioned about the recording-mode in the 2D animation feature, but I think it can be added as another enhancement PR to apply it to 3D later.

### CODE REVIEW

**Comment by TokageItLab** [comment]
@lyuma want to get rid the popup, so I'm working on changing UI to popup's toggle into the button above and moving rest option.

**Comment by TokageItLab** [comment]
Added some shortcuts. Key insertion defaults to the "Insert" key which same as in 2D, but no default shortcuts are assigned for Init-Pose and Pose-to-Rest others due to consider to conflicts.

**Review by lyuma — APPROVED** [review]
Seems good overall to me.
```
Vector<int> Animation::find_tracks(const NodePath &p_path) const {
```
The only place I see this used is to search for a specific track by type (e.g. `TYPE_ROTATION_3D`). Is there ever a case where you have multiple tracks with the same path *and* the same type?

Maybe `find_track_with_type()` would be better?

**Comment by TokageItLab** [comment]
@lyuma Make sense. The previous `find_track()` is now unsafe and we should to replace it.

**Review by reduz — APPROVED** [review]

**Pull request merged**
