### PR TITLE
Implement `Auto width` behavior for ItemList to complement the existing `Auto height`

### LINKED ISSUE #31504: ItemList doesn't expand for text elements
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
macOS Mojave 10.14.2
NVIDIA GeForce GT 650M 1024 MB
Intel HD Graphics 4000 1536 MB

**Issue description:**
I'm using an ItemList node to display some text. 
I expect the displayed box to automatically expand horizontally to fit all the elements. It is not doing that.

test-itemlist-bug-game

**Steps to reproduce:**
Open the below project.
OR
1) Create a new empty project. Create a new scene with just an ItemList node.
2) Set the min size of the ItemList node to 0
3) Add an item to the ItemList (with the inspector editor or in code with `add_item()`

**Minimal reproduction project:**
[test-itemlist-bug.zip](https://github.com/godotengine/godot/files/3521629/test-itemlist-bug.zip)

### PR DESCRIPTION
**Pull request by Althar93**
_Re-created from the previously closed pull request #33774 ; now up to date with the main branch & changes merged ready for integration_

I have implemented the 'Auto width' in ItemList. This is also in response to #31504

The behaviour in this pull request should be identical to the existing 'Auto height', i.e. : expands the container & parent containers with the content but does not shrink the container or any parent container.

This change is a minimal change that serves to complement the existing 'Auto height' but perhaps both options should be updated to both shrink & expand with the contents?

*Bugsquard edit:* Closes #31504

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Ran into this issue, definitely would like this merged!

**Comment by qaptoR** [comment]
This is awesome! Cherry-picked it for my custom-compiled 3.4 editor and it works great!

**Comment by animentork** [comment]
Great! I would love to see it in 4.1!

**Comment by Calinou** [comment]
> Great! I would love to see it in 4.1!

New features will only be merged in 4.2 at the earliest, as per the [release policy](https://docs.godotengine.org/en/latest/about/release_policy.html).

**Comment by Gamemap** [comment]
> Also, this pull request needs to be [rebased](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase) as ItemList has received significant changes since this PR was created.

@Althar93 Ping
_(I would need this for my projects, so it would be nice if it could be merged for 4.3)_

**Comment by Anutrix** [comment]
@Althar93 Can you please rebase? Thx.

**Comment by AThousandShips** [comment]
@Althar93 are you still able or interested in working on this?

**Comment by KoBeWi** [comment]
Superseded by #93270

**Pull request closed without merging**
