### PR TITLE
Rename `ADD_GROUP()` macros to `BEGIN_GROUP()` and `END_GROUP()`

### PR DESCRIPTION
**Pull request by Calinou**
This better highlights the stateful nature of inspector categories defined using the `ADD_GROUP()` macro. [I discussed this with Zylann on the Godot contributors chat.](https://chat.godotengine.org/channel/devel?msg=TEKci49pCprBzZbSo)

This also adds comments above each macro, which will appear in many IDEs when hovering the macro names.

Third-party C++ modules that use the `ADD_GROUP()` macro will have to be updated to use the new macros.

### CODE REVIEW

**Comment by EricEzaM** [comment]
If you are adding comments to document what it is, could you also explain what the `name` and `prefix` params do? That's why this was brought up in the Godot chat originally, because it was documented and lawnjelly was not clear on the usage of the second param

**Comment by lawnjelly** [comment]
Yes for my own experience, I didn't have any problem with `ADD_GROUP` - it seemed pretty obvious it was a state. Just having some comments on the macro describing what the prefix is used for would have been enough I think.

**Comment by LightningAA** [comment]
Is prefix even useful? It seems kind of unnecessary to me.

**Comment by pycbouh** [comment]
> Is `prefix` even useful? It seems kind of unnecessary to me.

It is, because it allows us to cut off the same prefix from all the grouped properties, if we group properties which are named with the same prefix. But we can also group properties that don't have a common prefix and there cutting anything off is likely undesirable.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting.

We'd prefer to keep `ADD_GROUP` as is, and you can just add `END_GROUP` (or `CLOSE_GROUP`) as sugar for the current `ADD_GROUP("", "")` so that in the very few locations where it's used, it makes things a bit nicer.
There could likely also be `END_SUBGROUP`.

**Pull request closed without merging**
