### PR TITLE
Child process connected message is now green.

### PR DESCRIPTION
**Pull request by djrm**
This hopefully will avoid misunderstandings about the message's origin.

### CODE REVIEW

**Review by RandomShaper — CHANGES_REQUESTED** [review]
Nice, but I think that adding a `set_reason_text(const String &p_reason, bool p_is_success)` and using that instead would make this more explicit and less prone to overlook in case of future need of changing the message from other places.

**Comment by djrm** [comment]
@RandomShaper yeah, that makes sense

**Comment by djrm** [comment]
@RandomShaper i updated this pr to include such method.

**Review by RandomShaper — APPROVED** [review]
Beautiful! And much better than with a bool.

¡Buen trabajo!

**Pull request merged**
