### PR TITLE
Implemented better way to map inputs in godot

### PR DESCRIPTION
**Pull request by AndreaCatania**
With this commit I've added a way to map stick (axis) input inside Godot actions.

Basically now is possible to map together axis and buttons in order to simplify the life of developer and allow to change bindings at runtime easily.

Please check this video to see it in action: https://youtu.be/tKd7rEfwpIo

### CODE REVIEW

**Comment by vnen** [comment]
Related to #14482 and #14641.

**Comment by groud** [comment]
I don't understand why people want dealing with axis instead of actions. 
To make this simple I would just define a get_action_value() that returns a value between 0 and 1 telling how "strong" is the action pressed. So that you can map a single action both to a single key and a single axis+direction.

**Comment by leoddd** [comment]
This is really useful. Would simplify a lot of my personal input handling code!

**Comment by AndreaCatania** [comment]
@groud I like `get_action_value` so if others like it too, I will rename it

**Comment by groud** [comment]
It's a little bit more than a renaming, it's just avoiding replacing the (axis+direction) way of mapping by an axis (without direction) mapping. While it work pretty well by now. 
Also that would make it compatible with analog buttons or analog keyboard key.

**Comment by AndreaCatania** [comment]
Oh.. in this case I've already did it, check this Screen Shot
screenshot from 2018-02-18 22-26-42

**Comment by BastiaanOlij** [comment]
I also like Grouds idea for the name.

Love this change @AndreaCatania

**Comment by groud** [comment]
> Oh.. in this case I've already did it, check this Screen Shot

Precisely, this is what I don't want, but the contrary. The previous system allowed to bind both an axis and a key to the same action with no more complex stuff.

**Comment by AndreaCatania** [comment]
With this PR you can bind key and axis to the same action, you can know the action axis and also if it's pressed or released.

Can you please give me an example in order to understand exactly what you mean?

**Comment by groud** [comment]
Well, by now we have this:
2018-02-18-225637_389x243_scrot
Which works fine but just requires something to retreive how "strong" is the action. So what i suggest is adding a get_action_value() telling how "strong" is the action when pressed.

So in code you would do:

```
if (is_action_pressed("my_action")):
   velocity += get_action_value("my_action") * SPEED
```
Where get_action_value returns something between 0 and 1 depending on how strong is the action.
(and always 1 when the action is used with the key).

If you bind the action to a negative axes, the value from get_action_value is still between 0 and 1 by getting the absolute value of the axis.

**Comment by BastiaanOlij** [comment]
@Groud the downside of that approach is that you'd need to do:

```
motion.y -= get_action_value("move_up")
motion.y += get_action_value("move_down")
```

While @AndreaCatania solution would allow you to do:
```
motion.y = get_action_value("move_y")
```

That said, I don't mind the extra line of code to combine them and it would fit well in the current input mapping making the change far less impactful. For a lot of already made games you can leave everything as is but just changing get_action_pressed for get_action_value where you need analogue precision.

With for instance the car simulation I'm working on throttle and brake could be one joystick axis (gamepad play) or two trigger axis (steering wheel and peddles) so the breakup into a separate throttle and breaking action makes far more sense.

So yeah, I think Grouds suggestion would work out well.

**Comment by mysticfall** [comment]
It looks nice and seems to be just what I want for my project.

By the way, does it also support using mouse motion or wheels as an axis, or do we need another issue/PR to implement that?

And does an axis input repeats its value when it's in the 'neutral' position, or does it work the same way as a trigger type input (emits events only when it's 'pressed')?

**Comment by groud** [comment]
Sure, it leads to more lines of code, but it's more consistent in the binding as a key cannot have a negative value. Else it would mean that you would have actions that can go into negative values and other that can't. Even if it's a little bit counter-intuitive at the beginning, it means any action can be binded to any type of input, which is, IMHO, easier to manage at the end :)

**Comment by BastiaanOlij** [comment]
@groud thing is, the current solution does not have a direction for key (pressed is always 1) but you have a direction for axis which is why every axis appears twice. Its not just taking the absolute of the axis, it is "for a positive axis, return the value as if when positive else 0" and "for a negative axis, return the values negated if negative else 0". Andrea just reversed that, returning the axis value as is, but allowing keys to return either 1 or -1 or assumably any value which can be handy.

But don't get me wrong, the more I think of it, the more I believe your suggestion is the better one. Right now we have a separate implementation for action pressed and action value. Your suggestion might require an extra line of code, it offers more flexibility and its simpler to understand. It also prevents confusion between people who want to use actions for normal key pressed actions and for axis input.

That all said, I had a quick look through the code and this change could take a bit of work. I would suggest adding a value to the Action structure and then enhancing this loop:
https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L332

To not just set action.pressed to true but also action.value to the value we want. It'll mean enhancing the event class to return the value for that event, which for a key event would be 0 or 1, for a joystick event would be between 0.0 and 1.0 and for mouse event i guess based on the relative mouse movement?

It also means adding a 2nd parameter for the value to:
https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L469
And making sure that defaults to 1.0 for backwards compatibility

And making sure:
https://github.com/godotengine/godot/blob/master/main/input_default.cpp#L480
Sets it to 0.

All in all it does feel like an elegant solution if done right.

**Comment by AndreaCatania** [comment]
I don't understand what is the benefit to have a value between 0 and 1, since with the approach that you said you have to create always an action for each axis direction and also you have to bind keys to these.

Also you have to check for each axis direction if the action occurs, and this is useless for most of the times. 

I don't know, but I don't see a lot of situation where split the two axis in four other make sense, or makes life easier, even because in order to support it I've to add more checks to it, and I don't like it.

I think that at the end the most of the times you will end with a GDScript like this:

motion.y -= get_action_value("move_up")
motion.y += get_action_value("move_down")
motion.x -= get_action_value("move_right")
motion.x += get_action_value("move_left")

plus all code to split these in the engine.

It add useless complexity, so for me it doesn't worth and doesn't make the life easy

**Comment by BastiaanOlij** [comment]
@AndreaCatania When you look at character movement in a top down map, you are absolutely right. But in many other use cases you'll fine your self doing this:

```
if get_action_value("move_y") >= 0.0:
  do_crouch(false) # make sure character stands up
  do_jump(get_action_value("move_y")) # jump with input relating to strength of jump
elif get_action_Value("move_y") < 0.0:
  do_crouch(true) #make sure character is crouched
```
Instead I can do:
```
do_crouch(get_action_pressed("crouch"))
do_jump(get_action_value("jump"))
```

For my brake example it gets even worse. I would have to do something like:
```
if i_have_a_gamepad:
  if get_action_value("throttle") >= 0.0:
    accelerate(get_action_value("throttle"))
  else:
    brake(-get_action_value("throttle"))
else:
  accelerate(get_action_value("throttle"))
  brake(get_action_value("break"))
```
It may seem weird to handle both accelerate and brake actions at the same time if you have separate axis for them but anyone who has driven go-karts knows how much fun using them at the same time can be :) You can even see these are separate properties in the physics engine

The code simplifies to:
```
  accelerate(get_action_value("throttle"))
  brake(get_action_value("break"))
```

So yes, I fully agree with you, for normal top down games where you just need a value between -1.0 and 0.0 for character movement, you need two lines of code where one will do. But at the added price of far more setup in the input mapping.

There is no right or wrong here imho. Both have pro's and con's. What I like about Grouds suggestion is that it doesn't change anything in the input mapping, it just adds to the information you can gather about the state of controllers. I also feel it makes it easier to setup more complex control situation such as my acceleration/braking scenario where it is more likely you're dealing with two separate axis.

**Comment by groud** [comment]
Yeah, but this solution complexifies the mapping system by introducing actions that can have two different directions. In you case, if you want to map a key to a double-direction action, you have to map two keys under the action.  As an example, for your move_x action you would have to map the left key as negative and the right key as positive, while both are under the same action. It makes the input mapping confuse just for removing 2 lines of code. While, let's be honest, you usually have those lines only once in your code. 
Thus I don't think the gain in code lines worth the (relative) complexity it adds to the input mapping. To be honest, I found the current system a little bit weird at the beginning, but I find it a lot more consistent and finally easy to understand.

**Comment by BastiaanOlij** [comment]
btw
```
motion.y = get_action_value("move_down") - get_action_value("move_up") # in 2D, other way around in 3D ;)
motion.x = get_action_value("move_right") - get_action_value("move_left")
```
= win :)

**Comment by reduz** [comment]
Did not look much at this as I have no connectivity (will hopefully do
tomorrow)..

If this is just for axis, api should be get_axis_value and we should have a
different category for naming and remaping axes, instead of trying to fit
it to the action system IMO

**Comment by groud** [comment]
> If this is just for axis, api should be get_axis_value and we should have a different category for naming and remaping axes, instead of trying to fit it to the action system IMO

We already have something to retreive an axis but it does not solves the initial problem of having to deal with code for actions (=keys pressed or not) and joysticks into different parts of the code. I think my solution solve the problem pretty well, but well, I'm not unbiased. ^^

**Comment by BastiaanOlij** [comment]
@reduz having just added both keyboard support and axis support to my demo racing game (and it being indirectly responsible for @AndreaCatania to spend time on this I think) I would beg to differ. I think enhancing the action system is worth considering as it would simplify a lot of coding. I do like @groud suggested approach most so far :)

**Comment by reduz** [comment]
But an action is an action, it's something that happened at a given time.
This is not an action, so it's confusing. I prefer it's named according to
what it really is.

**Comment by reduz** [comment]
But this was never a purely action based system, it's part of the Input
system.

**Comment by BastiaanOlij** [comment]
@reduz note btw, that this is not just for axis, the whole goal here is to map an action like "move forward" to a key (W), an axis (axis 1 positive) and maybe even mouse movement, exactly like the current mapping already does, but instead of getting a true/false, we get a value between 0.0 and 1.0. When the key is pressed it will return 1.0, if the joystick is used, the value is between 0.0 and 1.0

**Comment by AndreaCatania** [comment]
Too much messages to reply: 000
so:

First thing is that I never said that I've removed the old actions APIs (that would be a stupid thing to do IMO since the actions APIs are fine) So this is the list of supported API in this moment with this PR 

- is_action_just_pressed
- is_action_just_released
- is_action_pressed
- is_action_released
- **is_action_just_changed**
- **get_action_axis_value**

As you can see I've only added two APIs this mean that all old approach still valid and correct to use, but in addition you will have (if required) the possibility to get value of the axis.

For example now is possible to have a Joypad where the buttons has a pressure, now we can map it easily.

> @AndreaCatania When you look at character movement in a top down map, you are absolutely right. But in many other use cases you'll fine your self doing this:
[ETC......]

@BastiaanOlij As I've said above you can and you MUST continue to use this approach:

```
do_crouch(get_action_pressed("crouch"))
do_jump(get_action_value("jump"))
```

This PR has the only objective to add a way to map Sticks inside the current actions in order to have the same mapping for all kind of devices.
With this you will have the benefit to centralize all the code to handle inputs inside one function
You can change button binding at runtime without care about device type
You have less actions to handle.

> @AndreaCatania Yeah, but this solution complexifies the mapping system by introducing actions that can have two different directions. In you case, if you want to map a key to a double-direction action, you have to map two keys under the action. As an example, for your move_x action you would have to map the left key as negative and the right key as positive, while both are under the same action. It makes the input mapping confuse just for removing 2 lines of code. While, let's be honest, you usually have those lines only once in your code.
Thus I don't think the gain in code lines worth the (relative) complexity it adds to the input mapping. To be honest, I found the current system a little bit weird at the beginning, but I find it a lot more consistent and finally easy to understand.

@groud You are saying that this solution makes things confusing and less consistent, but I never saw a single post that complain this approach to UE4, and also people seems happy for this implementation on YouTube and also Twitter. I think that this approach makes things a lot easier.

Doesn't exists a single game, or at least very few, where you get a benefit to separate the two axis of joystick in other four. The sticks are always used to move the camera position or orientation and the range -1 to 1 is perfect for this scenario.

Also I want to talk about range of inputs, with this PR you will get a different range according to the input, for example as discussed before if you have a Stick the axis range will be -1 to 1 but if you have a shoulder trigger (for example L2) the range will be 0 to 1. So the function get_action_axis_value will return always the natural value that you expect, or 0 if the button doesn't simulate the axis.

> But an action is an action, it's something that happened at a given time. This is not an action, so it's confusing. I prefer it's named according to what it really is.

@reduz I thing that move a stick is also an action, and you can use **is_action_just_changed** to know if this action is just triggered or not. 

----

However I would be glad if you compile the code and you test it with your current project and then would bring to me the problems that you have found, so I can try to figure out how I can improve it

**Comment by BastiaanOlij** [comment]
Just a few more cents from my side after talking somewhat more in depth with Odino to kick ideas around and understand his reasoning better.

I think Odino's approach does make more sense to me now but I see the sense in a number of the things raised especially in it potentially being confusing in the action system.

I think Reduz probably highlighted this best when we discussed if this should be part of the action system. While there is overlap in this all being about input, in the long run this is about what makes sense for building a game that uses analogue input with a fallback to a keyboard.

So here is my suggestion for making this better:
1) split the interface, make it clear that the action mapping is different from axis mapping even though they are similar. Either a separate tab or two sections on the input tab.
Actions are about singular events. The user presses W, the user presses Spacebar, and mapping that to equivalent joystick actions.
Axis mapping is about getting named access to axis on a joystick with the ability for the user to change that mapping if they have different controllers and with a fallback to keyboard input that simulates axis. These are not event driven actions but purely state driven.
2) call the field in which you put -1.0 or 1.0 scale to indicate you apply a scale to this input. I liked this about the screenshot I was shown about UE4. I see sense in being able to put other values in here. D could be mapped to 0.5 instead of 1.0. Pushing your stick all the way to the right means the character moves at its fastest which may not be what you want with keyboard input because you don't have the control over speed.
3) don't use action in the names of the new functions. Call them has_axis_changed and get_axis_value. They are not action based.

Just my take on it at this point in time :)

**Comment by groud** [comment]
I completely disagree, I already had to deal with Inputs for games and always faced the problem of "should I define an action or use an axis", this happens every time with other engine and is a pain to work with.

The current system is fine, but just need a way to retrieve analog values. I think my solution is quite elegant in solving this problem while requiring no even a single more line of code, as shown by @BastiaanOlij. The axis system, with negative and positive values, introduce a new concept where the border between actions and axis is too fuzzy and thus confusing. 
As an example I'll take a crouch system in a platformer, you might want either to bind it to the down direction (using an axis value) or a button. In the current system, you create a crouch action, and you can bind it to either the negative y axis or a button. Thus the following code works in both situations:
```
if (is_action_pressed("crouch")):
   //crouch can be binded to either negative vertical axis or a button
```
While in your system, you would have to change your code depending on whether you use the button or an axis. 
```
if (is_action_pressed("crouch")):
    if (get_axis_value("crouch") < 0):
      // crouch for value < 0, but it does not work for buttons as the value is 1
or
if (is_action_pressed("crouch")):
   // crouch for a button, but it does not work with an axis as you have to check if the value is negative
```
And yes, even if you keep the old system, you introduce a new possibility that might confuse people in whether they should use an axis or two different actions.
I strongly believe the current system limits the confusion and provides you with a single and consistent way of dealing with Inputs. 
And it's not because people are not complaining about it with UE4 that it's good.

**Comment by groud** [comment]
Also, to support what I'm saying:
https://answers.unrealengine.com/questions/445561/when-to-use-action-mapping-and-when-to-use-axis-ma.html

**Comment by AndreaCatania** [comment]
Basically here you are mixing two completely different things since you never want to use an axis to crouch your character, since it has no sense.

I never saw a game where you use the stick to make an action like crunch, and also if it exist it's a very near corner case.

```
if (is_action_pressed("crouch")):
    if (get_axis_value("crouch") < 0):
      // crouch for value < 0, but it does not work for buttons as the value is 1
```

However I don't understand the above code since, if you want to crouch with button you just need to set a button and not to simulate an axis.
So I really don't understand your worries, I didn't changed how action works, I've only added the possibility for a button to simulate an axis if you want.

Also if you set a button to simulate an axis is_action_pressed will works anyway even if you set a value of -1001292

As I explained to @BastiaanOlij if you support the splitting of the axis the main problem is this:

You will always use the stick to move something: camera rotation, camera position, character, vehicles, something... and for each of these you will need a range that go from -1 to 1 so in the GDScript you'll write something to combine the splitted axis to one axis.

In addition to this problem you have to create more actions, this mean that the engine for each input event of each tick it has to execute the code to split the axis and also have to check the event through more actions.

All this useless code has no sense since we are splitting the axis in the backside (not for free) but then we will combine it in the GDScript (not for free).

Also remember that if you need to execute an action like crouch you don't need axis values so you don't have to simulate it.

**Comment by groud** [comment]
>  I never saw a game where you use the stick to make an action like crunch

Almost all platformers actually. So no, it's not a corner case.

> Also if you set a button to simulate an axis is_action_pressed will works anyway even if you set a value of -1001292

Sorry but this "a button simulates an axis" is completely unintuitive, and I think bad UX.

> so in the GDScript you'll write something to combine the splitted axis to one axis.

Yeah, but you're using this only once in the code, and instead of a "button simulating an axis" you have a perfectly distinguished "go left" and "go right" actions, that can be bound to either a key or an axis+direction. So while your system replaces `get_action_value("move_down") - get_action_value("move_up")` by a `get_action_value("move_x")` it induces complexity in the input mapping system for very little gain.

I'm sorry, but I'm strongly against merging this PR as is, as it would break what I think is a great idea with Godot Input's management: any action can be bound either to a button, a key, or an axis+direction, that's it. No "actions can be axis, or not. And a key can be mapped to a signel action or mapped to a value on a given axis".
The current solution is perfectly straightforward and works fine in all situations, even if it requires you to write a little bit more code. And it does not bring the confusion between what should be handled with actions and what should be handled with axis, which, depending on the game, might be hard to choose.

**Comment by puppetmaster-** [comment]
Please don't forget that when working with values, the players move at different speeds depending on whether they are moved with a joystick or with the keyboard. 

**Questions**
When does is_pressed() return true? get_action_value() > 0?
How dead zone get handled? Does it need to be configured first?
Does get_action_value() from a key press does also return a value **between** 0.0 and 1.0?

**Comment by AndreaCatania** [comment]
I've added new tab inside project settings in order to make more clear that you are defining different thing, here how it looks like: https://youtu.be/J3UCXsTIDtU

@puppetmaster- yes it will move depending how much you push the axis

> When does is_pressed() return true? get_action_value() > 0?

If you use get_action_value on a simple action it always return 0 even it it's pressed

> How dead zone get handled? Does it need to be configured first?

The dead zone for axis to be catched as a pressure is the same as before 50% of its total way, there's no dead zone if you want to know axis value.

> Does get_action_value() from a key press does also return a value between 0.0 and 1.0?
It returns 0 or 1 or a different thing depending on the axis factor that you set.

**Comment by raymoo** [comment]
If there has been any mention of defining thresholds for axis -> action mapping, I've missed it. Turning an axis into an action should require a threshold value.

**Comment by NathanWarden** [comment]
I like using an axis based system like this and being able to have keys with -1 to 1 values. There are very few times I've ever needed to check if the value is positive or negative (IE. a few times there's been forward to accelerate and back to brake) and when I have it isn't a big issue. However, having to check each key and then the joysticks separately is very annoying and makes the code much more confusing and error prone (which this fixes). However, even with Andrea's change (and unless I'm missing something) I don't see why a person couldn't still use the current approach if they really want to. So, this update actually allows for both approaches whereas before it only allowed for one.

**Comment by AndreaCatania** [comment]
> If there has been any mention of defining thresholds for axis -> action mapping, I've missed it. Turning an axis into an action should require a threshold value.
>
>EDIT: This is relevant if groud's system or both systems are added.

@raymoo True, but the possibility to use an axis as an action is currently in the system and the threshold is 0.5

Here we are doing the opposite simulate an axis using the buttons

**Comment by raymoo** [comment]
Oh, I see. I wasn't aware you could already do that. I feel though that axes mapping should be a separate system from the action system, since that's what seems to be causing the conflict.

**Comment by AndreaCatania** [comment]
@raymoo I already did it, check this: https://github.com/godotengine/godot/pull/16797#issuecomment-366673543

**Comment by groud** [comment]
If we have to merge such an axis system, I figured out that an older PR does it too: #14641.
It looks a little bit cleaner.

**Comment by thismarty** [comment]
Will this be implemented in G3.1?

**Comment by LeonardMeagher2** [comment]
I hope so.

**Comment by aaronfranke** [comment]
How does this PR compare to https://github.com/godotengine/godot/pull/14641 ?

@groud Actions and Axis values are completely separate things. Getting booleans is useful for many things, and getting floats is useful for many things. Names like `get_action_value` are confusing.

To further explain why this feature is useful and what features it could have, here's a screenshot and explanation of the Input axis system in Unity:

inputaxis

Unlike Godot's inputs, which are true or false, Unity's Input axis system returns a float between -1 and 1, allowing one variable for in-game axis behavior (instead of moving left or right depending on booleans, you can move horizontally and multiply by the axis variable). 

The behavior of an axis can also be adjusted with options such as gravity. An input can be set to either instantly jump between 0 and 1, for a behavior similar to booleans, or spend some time in-between. For simple character movement, where you can define moving forward/backward and left/right, a gradual transition between 0 and 1 or -1 makes the character movement VASTLY smoother. In real life, there is no instantaneous acceleration. 

Furthermore, I currently can't use the Input class to get mouse movement. Input can currently only bind mouse buttons, and mouse movement can't be translated to simple booleans. This is a serious oversight for any games that wish to get input from the mouse movement.

**Comment by groud** [comment]
> @groud Actions and Axis values are completely separate things. Getting booleans is useful for many things, and getting floats is useful for many things. Names like get_action_value are confusing.

No they are not, you're just seeing it like Unity's and other game engines see this this. But the only difference between them is that Axes handle float values and Actions handle boolean ones.
 So what I propose is just to give actions a "strenght" value, so that you can use `get_action_value("go_left")` to ponderate how strong you want to go to the left. It's easier that choosing between creating an Axis or two Actions when you're not sure if your gameplay is going to be boolean or not. Everything you mention is also possible with my solution. Basically, my point is that I prefer having to remap action whenever I'm not sure about whether to use an Axes or and Action. Input mapping is a tedious task.

Regarding #14641 it also adds Axes support but is cleaner in terms of both UI and API. Also it does not introduce this confusing "Simulate Axis" value, since it separates completely Axes from Actions and does not try to make a link between them.

**Comment by aaronfranke** [comment]
@groud A strength of "go_left" between 0 and 1 would still require me to write two pieces of code, one for moving left and one for moving right, for every place where I need two opposite directions. An axis system of allowing -1 to 1 is much better as I only need to write code for each axis I need. I already know to start off that my inputs are not going to be boolean.

Another idea occured to me, we could have everything be axis values internally, but have a boolean method that returns true if > 0.5. Maybe even a "neg direction" check if < -0.5. This would allow you to map inputs one way but still easily pull out booleans.

**Comment by groud** [comment]
Well yeah, having to write something like `motion.y = get_action_value("move_down") - get_action_value("move_up")` is one of the flaws we mentioned. However, I believe it worth it since: 
- You usually handle inputs only in a single place in your game
- It avoids confusing people when then have to choose between Axes and Action, if they are not sure about the gameplay they want.
- It avoid creating a new way of handling Inputs in general, while still providing the exact same features.

But yeah, finally the question is whether if we want users to write a little bit more code, or if we want them to spend more time in the Axes/Actions menu. I personnaly hate having to remap inputs when my gameplay changes, that's why I prefer my solution.

**Comment by aaronfranke** [comment]
I guess I am overstating the benefits of a -1 to 1 range, something like "up minus down" does seem simple enough to program. Anyway, anything is better than booleans for my use case.

I would still like to state that, for keyboards, a `get_action_value` is only useful if we can control the "gravity" etc of values (rate to go towards 1 when pressed, rate to drop back to 0 when released)

**Comment by groud** [comment]
> I would still like to state that, for keyboards, a get_action_value is only useful if we can control the "gravity" etc of values (rate to go towards 1 when pressed, rate to drop back to 0 when released)

Sure, that kind of things could be modified in the InputMap menu.

Anyway, to be honest this seems to be something quite controversial. I believe we should organize a vote or something like that, to see what people think about both idea.

**Comment by AndreaCatania** [comment]
@aaronfranke 
 
> Another idea occured to me, we could have everything be axis values internally, but have a boolean method that returns true if > 0.1. Maybe even a "neg direction" check if < -0.1. But 0.1 could be anything, maybe 0.5 is better? This would allow you to map inputs one way but still easily pull out booleans.

Currently this implementation does it

**Comment by HummusSamurai** [comment]
I strongly prefer the solution in https://github.com/godotengine/godot/pull/16902 by @groud to this one.

**Comment by johannesgunnar** [comment]
Just wanted to say that this is exactly what I need and would save me a lot of work with my game Vegg. Both implementation concepts of @AndreaCatania and @groud seem to be good and even though one would fit better for my current game the other one would require just minimal workarounds. And for other games it would be the other way around.  

Might even port my game from Godot 2 to Godot 3 if this gets merged.

**Comment by AndreaCatania** [comment]
In the last commit I've improved input mapping for multiplayer games by adding per controller mapping. Check this video and let me know what do you think about: https://youtu.be/vCBu6CSsnjo

**Comment by akien-mga** [comment]
Why was it closed? (Superseded by another PR I guess? But it would be good to mention here for clarity)

**Comment by AndreaCatania** [comment]
Akien ye correct, I closed it because reduz like more the approach of splitting joy axis, so this pr will be merged: #16902

**Comment by QbieShay** [comment]
For what's worth it, i prefer having axis mapped from -1 to 1. I don't see the use case for [0,1]. I actually think it would be annoying to work with.

**Comment by raymoo** [comment]
[0,1] makes sense for throttle or trigger inputs, but of course [0,1] fits within [-1,1]

**Comment by Dudemanjude** [comment]
What about the multiplayer controller mapping? I like the per controller mapping, it would be very useful for making local multiplayer games.

**Comment by groud** [comment]
> What about the multiplayer controller mapping? I like the per controller mapping, it would be very useful for making local multiplayer games.

Actually, you can map and define per-player actions by doing something like that:
- You create a set of actions to be mapped for each player
- You duplicate the action for each player via code, while renaming them by using something like "jump_PlayerID", "shoot_PlayerID"... (you change the player ID)
- You check each action using something like `Input.is_action_pressed("jump_"+player_id)`

**Comment by Dudemanjude** [comment]
I know you can do that, but it still would be nice to have it done semi-automatically like it does in this PR. I've done that sort of mapping before whenever I've tried to implement local multiplayer. It seemed like a pretty nice addition, without having to manually type in all of the names, but it's not that hard to work around it.

**Comment by Xrayez** [comment]
Regarding multiplayer controller mapping per player thing...

> > What about the multiplayer controller mapping? I like the per controller mapping, it would be very useful for making local multiplayer games.
> 
> Actually, you can map and define per-player actions by doing something like that:
> 
> * You create a set of actions to be mapped for each player
> * You duplicate the action for each player via code, while renaming them by using something like "jump_PlayerID", "shoot_PlayerID"... (you change the player ID)
> * You check each action using something like `Input.is_action_pressed("jump_"+player_id)`

I've proposed a somewhat refactored approach regarding how input states can be decoupled from input polling system here: godotengine/godot-proposals#104.

The proposal is centered around having an easier way to control multiple *characters* within a game session, not necessarily multiple *players* per session, but there may be some connections which I can't see for myself being useful what was proposed here.

Talking specifically, my proposal aims to provide some encapsulated input state which can basically reflect the global input state the same way you'd use an `Input` singleton, but also having an `InputState` resource which can be synced and/or shared between player/character instances. What I imagine could be useful is assigning some special controller mapping identifier within each state so that the input polling system can retrieve only those states which are actually relevant/matches the identifier.

My current implementation #35240 only has a master instance of an `InputState`. What could possibly be useful is actually dynamically allocating the necessary input states whenever you have more than one controller being connected. Compare:

```gdscript
# Local single-player
var state = Input.state as InputState
var player = state.get_id()
# ... input handling code for the player goes here ...
if state.is_action_pressed("shoot"):
    pass
```
vs
```gdscript
# Local multi-player
for i in Input.get_local_state_count():
    var state = Input.get_local_state(i) as InputState
    var player = state.get_id()
    # ... input handling code for EACH player/controller goes here ...
    match player:
        0:
            if state.is_action_pressed("shoot"):
                shoot_apples()
        1:
            if state.is_action_pressed("shoot"):
                spam_eggs()
     # etc.
```

Thoughts?

**Pull request closed without merging**
