### PR TITLE
Fix broken tangents in vulkan rendering server on godot 4

### PR DESCRIPTION
**Pull request by sboron**
Fix an issue with broken tangents on rendering server since redux can't copy and paste his own code rightly.

https://github.com/godotengine/godot/blob/70f5972905a5ea6916e9aab909f9a34b963f67b1/servers/rendering_server.cpp#L423

Related issue:
https://github.com/godotengine/godot/issues/48279#issuecomment-828833771

This PR is part of a larger PR which deals with the issues of tangent and normal generations up to the representation in the shader. This is part 2. Each part is an independent part and solves an independent problem.
https://github.com/godotengine/godot/pull/48340

### CODE REVIEW

**Comment by JulienVanelian** [comment]
> since redux can't copy and paste his own code rightly.

I hope you're not so serious about this, otherwise you're a bit too harsh 🤨

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by sboron** [comment]
> > since redux can't copy and paste his own code rightly.
> 
> I hope you're not so serious about this, otherwise you're a bit too harsh 🤨

Relax dude. Was just a joke...

**Comment by JulienVanelian** [comment]
> > > since redux can't copy and paste his own code rightly.
> > 
> > 
> > I hope you're not so serious about this, otherwise you're a bit too harsh 🤨
> 
> Relax dude. Was just a joke...

Good then, was just making sure 😁

**Pull request merged**
