### PR TITLE
Updated nrex with new features

### PR DESCRIPTION
**Pull request by leezh**
More updates incoming from https://github.com/leezh/nrex
- Added support for POSIX character classes `[[:alnum:]]`
- Added lookahead `(?=)(?!)` and lookbehind `(?<=)(?<!)` support
- Added ASCII `\xFF` and Unicode `\uFFFF` code points (in a style similar to Python)
- Added word boundary support `\b\B`
- Limited capture groups and back-references to 9 by default (for backwards compatibility)
- Quantifiers now use recursive functions. nrex::match() is now pure stack memory.
- Remembered to update the license in README.md to the newer zlib license

I've only tested the lib against the spec, so please do **double check this with proper real-world scenarios**.

Continues discussion from https://github.com/okamstudio/godot/pull/2300

### CODE REVIEW

**Comment by reduz** [comment]
awesome!

**Comment by Ovnuniarchos** [comment]
Time to update the Regex docs…

**Comment by santiagopf** [comment]
Hello leezh,

When I try to run this regex my application crashes:

	var regex = RegEx.new()
	regex.compile("{.*}")
	regex.find("configuration : config[{variable=26}]")
	var captures = regex.get_captures()
	
	print("regex captures : ", captures)

**Comment by leezh** [comment]
@santiagopf Are you using the nightly builds? They haven't been updated in a while.

**Comment by reduz** [comment]
he is using up to date builds as far as i know

**Comment by leezh** [comment]
Odd. Commit 26b977c96795172b1e095c06222eb30cfc6f4cb7 should've fixed it.

It does work when I compile from git, but it segfauts when I use the latest one from the godot website.

**Pull request merged**
