### PR TITLE
[CTL] Do not break line on the span (e.g. RTL BBCode tag) edges.

### LINKED ISSUE #31089: RichTextLabel - BBcode separates words for purpose of text-wrapping
**Godot version:**
Godot 3.1.1 64-bit, both Standard and Mono

**OS/device including version:**
Windows 10 Home 64-bit, build 18362

**Issue description:**
While working on a solution for the gradual reveal of GUI text ([an example](https://www.gamasutra.com/blogs/MiguelSantirso/20180129/313803/Better_text_reveals_Unity_code_inside.php)), it's become apparent that the RichTextLabel node treats bbcode tags as white space when it comes to text wrapping.

TextReveal

In the above example, a color tag is programmatically moved forward within the text string. The text should not be shifting around at all.

**Steps to reproduce:**
Create a RichTextLabel node, enable BBCode, and insert some text, with bbcode tags in the middle of words. Play with the width of the control rect, and the issue should become apparent. Alternately, download the repro project, which was used to produce the above gif.

**Minimal reproduction project:**
[Text Reveal Bug.zip](https://github.com/godotengine/godot/files/3465735/Text.Reveal.Bug.zip)

### LINKED ISSUE #41963: BBcode in RichtTextLabel is not ignored by wrap
**Godot version:**

beb9ebc

**Issue description:**

image
The text is `test, [color=red]test[/color],`

When I change it to `test, [color=red]test,[/color]` the second test gets wrapped correctly.
image

The BBcode should be ignored when wrapping, right now seems like it's treated like whitespace.

**Minimal reproduction project:**
[Node2D.tscn.txt](https://github.com/godotengine/godot/files/5204958/Node2D.tscn.txt)

### PR DESCRIPTION
**Pull request by bruvzg**
Do not break line on the span (e.g. RTL BBCode tag) edges (except "language" tags which implies line breaking rules change).

Fixes #41963, fixes #31089

https://user-images.githubusercontent.com/7645683/105675163-55876d00-5ef1-11eb-9d65-c37bbf65787b.mov

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by ibe-denaux** [comment]
Is this fix planned to be implemented into v3.x?

**Comment by LemonadeFlashbang** [comment]
Just commenting support for a 3.x compatible fix- I use color to highlight items/skills/etc., and this issue will punt the following punctuation down to a new line which is a fairly large polish hit.

**Comment by Calinou** [comment]
> Just commenting support for a 3.x compatible fix- I use color to highlight items/skills/etc., and this issue will punt the following punctuation down to a new line which is a fairly large polish hit.

`3.x` does not use the Complex Text Layouts system (which is backwards-incompatible), so this fix needs to be reimplemented from scratch in `3.x`.

**Comment by LemonadeFlashbang** [comment]
I figured as much. For my use case it's a priority fix so worst case I'll learn how to make the change myself or I'll hire a more knowledgeable dev, but I wanted to flag this issue as still impactful in the shorter term.

**Pull request merged**
