### PR TITLE
Makes an overridable _disabled method for BaseButton so the button ca…

### PR DESCRIPTION
**Pull request by MuffinManKen**
…n react to its state change.  For example, animating to get the user's attention.

I couldn't find a good way to do this via gdscript.  The code and performance impact should be minimal and I think others could benefit from this.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
I think it would be better to implement this with a signal, and that only if the feature is actually needed. There is no way to change the disabled state of a button except via your own code, so why not just call the function there?

**Comment by MuffinManKen** [comment]
Coupling. I don't want random bits of code know how my buttons work.  

Or are you saying I should override set_disabled?  I tried that and it doesn't get called on buttons that are set to be disabled initially.

Also, when a parent object sets disabled via the property (button.disabled = true) it does not call my set_disabled. I would have expected set_disabled to not get called from within the button's own script, but not otherwise.

**Comment by akien-mga** [comment]
First of all, pull requests should be made against the `master` branch, not stable branches. Release maintainers are in charge of cherry-picking changes to stable branches when relevant.

As @bojidar-bg mentioned, this breaks Godot's design philosophy to notify users only of changes from the engine itself, not about actions that you triggered yourself. If you call `set_disabled(true)`, you can as well emit a custom signal or call a specific method that should handle the logic you want to have when disabling. There are many ways to do it, but added a custom callback in the engine for this purpose seems unnecessary.

You might think that it's more elegant this way, but think about the bigger picture: should we add such callbacks for every single method that users can call from script? What's the overhead of calling all those virtual methods all the time?

**Comment by akien-mga** [comment]
> Also, when a parent object sets disabled via the property (button.disabled = true) it does not call my set_disabled. I would have expected set_disabled to not get called from within the button's own script, but not otherwise.

I'd add a `set_disabled_and_more()` method in the Button script that sets it disabled and does the extra logic you need. You can then call that method from parent nodes instead of accessing the `disabled` property directly. If you have different buttons with distinct scripts that would all need this logic, you can put it in a base script and inherit that script for each Button script.

**Pull request closed without merging**
