### PR TITLE
Fix GridMap Bug#16524 -unable to delete MeshTile on MacBook using TouchPad

### LINKED ISSUE #16524: Unable to delete MeshTile in GridMap on MacBook using Touchpad
**Godot version:**
3.0 Stable Official

**OS/device including version:**
macOS High Sierra 10.13.3
MacBook Pro using trackpad

**Issue description:**
Unable to delete/remove a mesh tile using:  Shift + Right Click (2 fingered push on trackpad).

**Steps to reproduce:**
When trying to remove a tile in the GridMap, holding down Shift and placing 2 fingers on trackpad and barely moving makes the "floor" go positive and negative.

**Minimal reproduction project:**
Demo: 3D Platformer

### PR DESCRIPTION
**Pull request by Douglas-W-Williams**
Fixes #16524

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't know if outright remove the feature is the right fix (if it is, the code should be deleted, not commented out).

CC @poke1024 who implemented this in #12573.

**Comment by ordigdug** [comment]
It's not much of a feature in my opinion, not only does it break ability to delete a MeshTile, when you press shift and move touchpad the floor jumps up and down in large unpredictable amounts. I only have a MacBook so can't test other os'.

**Comment by poke1024** [comment]
@ordigdug  You're right, it's really broken.

We could indeed remove this functionality, I'm not sure how often you want to move that grid in that way. If not, I've prepared an alternative fix in https://github.com/godotengine/godot/pull/17111:

* only trigger the grid mesh move functionality with alt+shift or alt+command (was: shift or command) so no interference with other functionality happens
*  fix the unpredictable movements of the panning in this case, so if you now press alt+shift and pan, you can move the grid vertically in a predictable way

**Comment by ordigdug** [comment]
@poke1024 Your alternative fix works well. 

@akien-mga Can you please reject my pull request and merge #17111 ?

**Pull request closed without merging**
