### PR TITLE
[3.2] Test collision mask before creating constraint pair in Godot physics broadphase 2D and 3D.

### PR DESCRIPTION
**Pull request by madmiraal**
This is a the 3.2 branch version of PR #39399.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
@madmiraal This PR breaks this test project: [Get_colliding_bodies_misbehavior_regression_test.zip](https://github.com/godotengine/godot/files/4876727/Get_colliding_bodies_misbehavior_regression_test.zip)

It works in 3.2.1 and doesn't work in 3.2.2. I did a git bisect to find this PR.

**Comment by agameraaron** [comment]
As Aaron mentions, this change unfortunately caused a regression that heavily affected my team's project! 

Area2D's get_overlapping_bodies no longer works if the body inside the area is enabled after already entering the area. It might be safe to assume this problem affects get_overlapping_areas and may have affected 3D as well. 

I made the minimal project to exemplify the problem so we could perform a bisect to deduct that the problem was here. If it outputs 'True' then it is good. If it outputs 'False' then it is no longer working. You will notice that between 3.2.1 and 3.2.2 this regression occurs & the bisect pointed us to here.

```
$ git bisect bad
5794a4e11e7a8ade3916622c030af6cc1a553a37 is the first bad commit
commit 5794a4e11e7a8ade3916622c030af6cc1a553a37
Author: Marcel Admiraal <madmiraal@users.noreply.github.com>
Date:   Mon Jun 8 17:18:23 2020 +0100

    Test collision mask before creating constraint pair in Godot physics
    broadphase 2D and 3D.

 servers/physics/broad_phase_basic.cpp           | 7 +++++--
 servers/physics/space_sw.cpp                    | 6 ++++++
 servers/physics_2d/broad_phase_2d_basic.cpp     | 7 +++++--
 servers/physics_2d/broad_phase_2d_hash_grid.cpp | 5 ++++-
 servers/physics_2d/space_2d_sw.cpp              | 6 ++++++
 5 files changed, 26 insertions(+), 5 deletions(-)
```

**Comment by akien-mga** [comment]
This is #39487 referenced above, which was since fixed with #39505 (`master`) and #39504 (`3.2`). Can you confirm?

**Comment by aaronfranke** [comment]
Ah, yes, it's fixed in the 3.2 branch. I should've tested the head, but I only tested 3.2.1 and 3.2.2 and the commits between them.

**Comment by agameraaron** [comment]
No, there is zero crashing experienced with this bug in 3.2.2 . The triggers simply do not show the body in get_overlapping_bodies if the body enables the relevant collision layer. Once the body leaves the overlaps and then enters it again, it will show up in get_overlapping_bodies. I will compile master tonight to see if the bug still exists.

**Comment by akien-mga** [comment]
@agameraaron You should compile the `3.2` branch. `master` is 4.0, and might not be compatible with your project, or lead to different issues.

**Comment by agameraaron** [comment]
Okay, thank you. I am including an update to the minimal test. It includes the ability to move around so you can see the project does not freeze & that in versions with the regression it is only when you fully exit the area and re-enter it does it see include the body in the get_overlapping_bodies function. Otherwise it normally will say "Good" (true) without having to move.

[Get colliding bodies misbehavior regression test v0-2.zip](https://github.com/godotengine/godot/files/4877755/Get.colliding.bodies.misbehavior.regression.test.v0-2.zip)

**Comment by madmiraal** [comment]
@agameraaron your example project is working on the current 9890189155 3.2 branch, which includes #39895 and #40114.

**Comment by agameraaron** [comment]
Yep! Came back to report it's working with the latest compiled 3.2.3.beta as of last night. :partying_face:

**Pull request merged**
