### PR TITLE
Makes all 32-bits of all physics, rendering, and navigation layers available in editor.

### LINKED ISSUE #2770: Render/Physics layer editor with up to 32 values
### Describe the project you are working on
Godot Editor

### Describe the problem or limitation you are having in your project
Users have recurring issues with seeing only 20 editable layers in the editor, while up to 32 layers are used in the engine and can be set by script.
See https://github.com/godotengine/godot/issues/45536

On top of that, a 3.2 bug has caused scenes to be saved with extra collision layer bits in the hidden range, which added to the confusion.
See https://github.com/godotengine/godot/issues/41281

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The proposed solution is to allow the editor to show the whole range of usable layers, as an option to avoid cluttering the inspector UI.

Instead of the current 10x2 grid, it would show a 8x2 grid by default, extendable to 8x4.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

**Mockup for layer grid in the inspector**
*Note:* this is just a quick mockup, the layout can be improved.

Default:
image
Expanded:
image
Clicking on the `...` icon for each section would show a popup with the corresponding layer names (1-16 or 17-32).

**Project settings**

All the sections in `Layer Names` would also show all the 32 available layers.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It can, but this change can improve editor usability.

### Is there a reason why this should be core and not an add-on in the asset library?
Layers editor and project settings are part of the core editor.

### PR DESCRIPTION
**Pull request by rune-scape**
Resolves https://github.com/godotengine/godot-proposals/issues/2770
Please let me know if I missed anything.

### CODE REVIEW

**Comment by qarmin** [comment]
Can you make a print screen how it looks in editor?

**Comment by EricEzaM** [comment]
Appears to just be a 4x8 grid...

image

There was some good discussion about the UX of various grid sizes and implementations in that proposal, not sure why you would jump straight into a PR, rather than discussing there first.

**Comment by bowling-allie** [comment]
My bad, I had the code lying around and I failed to read the contributing guidelines. What should happen to this PR?

**Comment by EricEzaM** [comment]
Once some sort of conclusion is reached in the proposals discussion thread, you can update this PR if that is something you want to do. Otherwise, you can close it if you don't have interest in updating it or would prefer someone else to implement the changes.

**Comment by dalexeev** [comment]
Please close this as the proposal was implemented in #51039 and #51040.

**Comment by akien-mga** [comment]
Superseded by #51039. Thanks for the contribution nonetheless!

**Pull request closed without merging**
