### PR TITLE
Add "View FPS" in 3D->Perspective's popup.

### PR DESCRIPTION
**Pull request by Krakean**
Very simple addition to avoid flooding Output window.
https://i.imgur.com/JjJNjBs.png

### CODE REVIEW

**Comment by Calinou** [comment]
Looks good! I like how the mspf (milliseconds per frame) is also mentioned.

**Comment by akien-mga** [comment]
Looks good, but please squash the two commits together: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by Krakean** [comment]
@akien-mga Done

**Comment by akien-mga** [comment]
Something must have gone wrong as you now have 4 commits. Once you've rebased locally and have one commit on top of the master branch, you should force push to update your PR, not pull again.

**Comment by Krakean** [comment]
@akien-mga Yes, my bad. Hopefully now it's fine.

**Comment by groud** [comment]
LoL, I was confused, I though you wanted to add a something related to a First Person Shooter view... XD
Anyway, LGTM :)

**Comment by groud** [comment]
(sorry for the close, I missclicked)

**Pull request merged**
