### PR TITLE
[doc] Use "param" instead of "code" to refer to parameters (4)

### PR DESCRIPTION
**Pull request by asmaloney**
One of several commits to fix all of the class XML docs (see #64134, #64164, #64196).

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
Gotta say, I enjoy very much seeing how the new tag does its job and helps to identify misnamed parameters! Too bad there are definitely descriptions that didn't use `[code]` to begin with.

I'm thinking, once we're done, I can modify make_rst to do a run and check how many methods/signals/annotations don't mention all of their parameters. With that we can open a tracker issue for contributors to help improve docs further. But I assume there are exceptions where documenting every parameter is not too helpful. Well, we'll see.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by asmaloney** [comment]
> I can modify make_rst to do a run and check how many methods/signals/annotations don't mention all of their parameters

I was just thinking the same thing!

And, after they are all converted, maybe a check where they use `[code]param[/code]` for a `param`?

**Comment by YuriSizov** [comment]
Yeah, we can double-check that too, but I'm sure you'll catch most of it, if not all, in these PRs 🙃

**Comment by asmaloney** [comment]
I've been trying to follow current commits that change the docs "behind me" as I work through this, but there are probably cases I've missed...

**Comment by YuriSizov** [comment]
Ah, that's true, that can happen. I check for this in the new PRs though. And I've seen people author new commits using this feature too. But yeah, we should probably double-check afterwards.

**Pull request merged**
