### PR TITLE
iOS: Fix memory leak on touch input [3.x]

### LINKED ISSUE #66422: iOS memory leak on touch input
### Godot version

3.5 stable, 3.5.1 RC2

### System information

macOS, iOS

### Issue description

On iOS, touch input causes memory to leak, even in an empty scene with just a Node2D root (tested on iPhone 6s and 2020 iPhone SE). The leak seems to occur specifically on touch begin (not hold/release), and repeated multitouch tapping will increase the memory use by several MB within a few minutes. This also seems to degrade the FPS more and more as tapping continues.

Seems the leak was introduced back in 3.2.3 (it's not present in 3.2.2) - perhaps by #40723 somehow?

### Steps to reproduce

Open a fresh project with an empty test scene, export and run on iOS from Xcode. Repeatedly tap the screen (quite a lot), and Xcode should show the app's memory usage increasing permanently.

### Minimal reproduction project

any project should do

### PR DESCRIPTION
**Pull request by tbveralrud**
Fixes #66422 for **3.x** branch. A fix for master is at #69201.

Replaces gesture recognizer with touch events directly from the view.

Rationale:
Gesture recognizers retain all touch events until their `state` property changes to "cancelled" or "ended."
The custom recognizer in the project fails to implement this requirement.
Setting the state to "ended" in the recognizer resolves the leak but introduces runtime assertions in logic that relied on an unending recognizer.

By forwarding the touch events directly from the view to Godot removes the need for a gesture recognizer.

Furthermore, the motivation for delaying touch inputs looks to be resolved too. (See #39624)
This branch removes the delay from touch events, putting iOS on parity with other platforms.
Project setting `input_devices/pointing/ios/touch_delay` has been removed as a consequence.

### CODE REVIEW

**Comment by djrain** [comment]
Just tested this in our game that uses fast tapping input. It indeed resolved the memory leak, and even more importantly, it eliminated the horrible input stutters / frame drops that were making the game unplayable even on new iPhones. Very much looking forward to seeing this merged, great work!

**Comment by tbveralrud** [comment]
@bruvzg This has been rebased.

**Comment by tbveralrud** [comment]
...and once more with a squash.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by oeleo1** [comment]
Good stuff! Thanks all.

Maybe the problem was hidden for us since the touch_delay was set to 0.01, but will definitely give it a try on the next RC,

**Pull request merged**
