### PR TITLE
Remove unused interpolate camera icon

### PR DESCRIPTION
**Pull request by MarcusElg**
As interpolated camera is removed in 4.0 I see no reason to keep it's unused icon. If there are plans to bring it back then this pr should obviously be closed.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by saneery** [comment]
@MCrafterzz But why InterpolatedCamera is removed in 4.0?

**Comment by Calinou** [comment]
@saneery InterpolatedCamera was removed as implementing your own interpolated camera just requires a few lines of code. Moreover, you will often require more advanced behaviors in a real-world project, making a node with some basic built-in behaviors not very useful.

ClippedCamera however remains available.

**Comment by saneery** [comment]
@Calinou Got it, thank you for the clarification!

**Pull request merged**
