### PR TITLE
Reduce default orbit inertia value

### PR DESCRIPTION
**Pull request by ghost**
The old default (`0.15`) caused the freelook camera to drift for way too long when rotated (over a second before coming to a stop...) The new value (`0.05`) is a lot more sober.

### CODE REVIEW

**Comment by akien-mga** [comment]
cc @Zylann @toger5 @n-pigeon etc. :)

**Comment by Zylann** [comment]
I'm ok with that, note that it's a shared setting across freelook and orbit though

**Comment by homer666** [comment]
@Zylann Yeah, it impacts all non-middle-mouse orbiting, such as switching between Top/Side/etc. views. In that case I think it's a change for the better, as it suffered from the same problem as freelook. The interpolation when switching between scene tabs got a little worse, but that's the only negative repercussion I've seen.

This isn't a perfect solution, but it seems to benefit everything but the inter-scene interpolation, which I've always been really skeptical about. I may have missed something though...

**Comment by n-pigeon** [comment]
I'm also ok with this.

**Pull request merged**
