### PR TITLE
Docs methods grouping by prefix

### PR DESCRIPTION
**Pull request by ghost**
Like https://github.com/godotengine/godot/pull/14688, but completely different :flushed:

No vertical layout, only a grouping by prefix that looks like this:

|class|image|
|---|---|
|Vector2|img1|
|RigidBody2D|img2|
|PhysicsBody2D|img3|
|Object|img4|
|Node2D|img5||

### CODE REVIEW

**Comment by Zireael07** [comment]
The grouping looks really nice! 👍

**Comment by groud** [comment]
I don't think this is useful, in most cases it does group things that are unrelated one to another. Such as all the getters.

**Comment by leoddd** [comment]
That's exactly the point @groud.
It looks good and as any UI designer will tell you, having places for your eyes to hook onto, especially while scrolling, helps readability just like that.
Additionally, you'll know whether something you're looking for is a better, setter, flag check etc. so being able to skip past all unrelated sections immediately using the whitespace between will be really convenient.

**Comment by groud** [comment]
then group them alphabetically and it's ok, no need to create groups that has no logical meaning.

**Comment by leoddd** [comment]
Grouping them by the proposed groups feels a lot more logical than an arbitrary gap between every letter to me.

**Comment by groud** [comment]
Well, no. Dividing according to the function prefix is even more arbitrary. Grouping "get_rotation" and "set_rotation" is meaningful, grouping "get_class" and "get_incoming_connections" is not.

So if the question is to add space to enhance the readability, I'd prefer having alphabetical separations.

**Comment by groud** [comment]
But to be honest, I've never seen any reference that does that.

**Comment by reduz** [comment]
This looks good to me, but I think it would be nice to group virtuals together, probably on top of the list.

**Comment by leoddd** [comment]
Oh yeah, before this gets merged, I think it'd be worth it to slightly reduce the space inbetween the sections, I think a full line isn't entirely necessary, half a line would probably work just as well without taking up as much space.
If it's something you can test quickly, it might be worth taking a look.

**Comment by poke1024** [comment]
Virtuals are now grouped at the top:

virtuals

Having less space between the sections would be nice, but AFAIK cannot be done with the current table/cell features in RichTextLabel. We'd need cell styles to specify sub-100% height.

**Pull request merged**
