### PR TITLE
Add compatibility with old mesh formats

### PR DESCRIPTION
**Pull request by reduz**
* Can load 2.x meshes
* Can load 3.x meshes

### CODE REVIEW

**Comment by Calinou** [comment]
Does this handle Mesh2D/MeshInstance2Ds?

**Comment by reduz** [comment]
@Calinou yes, it should.

**Comment by BastiaanOlij** [comment]
Looks good, probably overdone but the futureproofer in me wonders if instead of calling this `oldArrayType` and `oldArrayFormat` shouldn't we name it `ArrayTypeV1` and `ArrayFormatV1` or some other versioned naming? And similar for the convert and fix functions?
I can imagine that at one point in the future we'll have more changes that require another version of these structures. While it is unlikely someone will try and import a Godot 2 game into say Godot 5, it could become an issue.

**Review by BastiaanOlij — APPROVED** [review]
Looks good to me, I haven't tested it, but seems pretty straight forward. My only remark as already given in a comment is whether we should name things in a way thats more future proof but that is probably overkill and just leads to harder to read code.

**Comment by reduz** [comment]
@BastiaanOlij To be honest I don't even remember which version is which. I think the very old format (just arrays) is pre Godot 1.x, since there were no packed arrays, while the OLD version is just the only version of packed arrays there ever was.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
