### PR TITLE
iOS simulator: merge into iphone detect.py

### LINKED ISSUE #4489: Platforms: merge isim options in the main iphone platform
The iSIM platorm (``platform/isim``) is an iOS simulator, which is basically the iOS platform (``platform/iphone``) for x86. It would be nice to try to merge it into the main iOS platform, so that we don't have to register it as a separate platform but could just enable it with a command line switch (e.g. ``isim=yes`` or ``x86=yes``).

### PR DESCRIPTION
**Pull request by akien-mga**
**Please test,** as I did not. It should now be possible to build the iOS simulator with `scons p=iphone ios_sim=yes`. It should enforce the right flags.

As the main iphone detect.py and the isim one had diverged a bit in some points, there might be further work needed to get the simulator to build. A notable difference is that the simulator defaulted to building in tools mode, while after this commit it would default to template mode; should I force tools mode for the simulator?

CC @punto- and anyone with an Xcode/OSXCross environment.

Fixes #4489

### CODE REVIEW

**Comment by punto-** [comment]
no need for tools on simulator..

**Comment by akien-mga** [comment]
> no need for tools on simulator..

Good, that's what I thought too. So it was a bug in the `isim/detect.py`.

**Comment by akien-mga** [comment]
Add a commit by @punto- to add an `arch` parameter for more clarity in the targets the iphone platform can be built for.
Would be nice to get an OSX user to test the new buildsystem :)

**Comment by akien-mga** [comment]
Oops... I pushed another commit from my local master branch which happened to have the above two commits, so I ended up manually merging this PR by mistake.
So to everyone, please test the master branch :)

**Pull request closed without merging**
