### PR TITLE
[4.0] Platform export refactoring

### PR DESCRIPTION
**Pull request by naithar**
Another approach at export refactoring proposal: https://github.com/godotengine/godot-proposals/issues/2929 that was suggested there.

Allows to use `cpp` files other than `export.cpp` for platform's export template. It can be done by prefixing `cpp` files inside `export` folder with platform name. This change should allow to simplify support and future modification of export templates.
Keeps current structure where `export` folder and it's code is kept with platform.

`export.cpp` files for each platform are also separated into more files for initial refactoring.
Future PRs could bring more changes to exports to cleanup the code and make it easier to navigate.

### CODE REVIEW

**Comment by naithar** [comment]
@m4gr3d I don't think more changes should be done to Android's export template right now. Separating APK and ABB export can probably be done in future PRs.

**Comment by m4gr3d** [comment]
> @m4gr3d I don't think more changes should be done to Android's export template right now. Separating APK and ABB export can probably be done in future PRs.

Yeah I agree, thanks for the PR!

**Review by m4gr3d — APPROVED** [review]
The Android section looks good!

**Comment by Faless** [comment]
> t can be done by prefixing `cpp` files inside `export` folder with platform name.

The PR looks really good, but can I ask why this extra step instead of just including everything in the `export` folder? (just being curious)

**Comment by naithar** [comment]
> The PR looks really good, but can I ask why this extra step instead of just including everything in the `export` folder? (just being curious)

I've done it mostly to be on a safe side if `export` folder already contained some `cpp` files for some reason. It's not the case for official templates of course but could be the case for some third-party export templates or platforms.
Now that I think about it, I'm not sure we should take this into account. 

This condition can be removed if it's not really needed

**Comment by akien-mga** [comment]
Yeah I think you can glob the whole folder. The reason only `export.cpp` was included is just that we never thought that more could be needed, there's no architectural limitation here.

**Comment by naithar** [comment]
Should I remake this PR for `3.x` branch once this one is merged?

**Comment by akien-mga** [comment]
> Should I remake this PR for `3.x` branch once this one is merged?

Yeah once we agree on the design I think doing the same changes in `3.x` for 3.4 would be useful.

**Comment by naithar** [comment]
Rebased the wrong branch, will fix and reopen PR.

**Pull request closed without merging**
