### PR TITLE
Fix unshaded debug draw mode for LightmapGI

### LINKED ISSUE #88341: Unshaded debug draw mode still draws lightmaps on meshes
- *Related to https://github.com/godotengine/godot/issues/62758.*

### Tested versions

- Reproducible in: 4.3.dev cae759949

### System information

Godot v4.3.dev (cae759949) - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

The unshaded debug draw mode still draws lightmaps on meshes, which means these meshes no longer look unshaded. This occurs with all rendering methods.

The scene below uses a DirectionalLight with Dynamic bake mode, but this occurs with the Static bake mode too. Since dynamic bake mode only bakes indirect lighting, only indirect light remains visible on the static mesh:

Normal | Unshaded
-|-
Screenshot_20240214_221949 webp | Screenshot_20240214_221954 webp

### Steps to reproduce

- Create a scene with LightmapGI and some nodes, then bake lightmaps.
- Use the **Perspective** menu in the top-left corner of the 3D editor viewport to switch to the **Display Unshaded** debug draw mode.

### Minimal reproduction project (MRP)

[test_shadowmask.zip](https://github.com/godotengine/godot/files/14288709/test_shadowmask.zip)

### PR DESCRIPTION
**Pull request by oxi-dev0**
Fixes #88341

### CODE REVIEW

**Review by jsjtxietian — COMMENTED** [review]
See https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#modifying-a-pull-request , "we will prefer a single commit in a given PR (unless there's a good reason to keep the changes separate)" , don't forget to squash your pr 😄

**Comment by Calinou** [comment]
I just realized objects with the Dynamic GI mode have the same issue:

image

Object on the left uses Disabled GI mode, object on the right uses the Dynamic GI mode.

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected in all rendering methods.

However, when using Forward+ or Mobile, dynamic objects are still shaded as seen in the comment above. Could you look into resolving this as well? Thanks in advance :slightly_smiling_face:

**Comment by oxi-dev0** [comment]
yes i will look into fixing dynamic objects, and squash the pr 😁

**Comment by oxi-dev0** [comment]
Looking at that dynamic bug, it fixes itself if you bake the lightmap while the mesh is dynamic. It just seems like a general lightmapper issue

**Comment by Calinou** [comment]
> Looking at that dynamic bug, it fixes itself if you bake the lightmap while the mesh is dynamic. It just seems like a general lightmapper issue

This is due to https://github.com/godotengine/godot/issues/77167. The object with Dynamic GI mode is considered to use the Disabled GI mode until it's moved after baking lightmaps.

**Comment by oxi-dev0** [comment]
Right ok, I'll take a look at it anyway

**Review by Calinou — APPROVED** [review]
This PR now seems to work correctly for dynamic objects with all rendering methods. I'd appreciate a second look just in case as I don't know if it's a fluke with my testing project.

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
@oxi-dev0 Could you rebase to resolve the merge conflicts?

**Comment by oxi-dev0** [comment]
why has that pulled in a bunch of reviewers? i just rebased it

**Comment by AThousandShips** [comment]
You performed an invalid merge so you added a bunch of commits (see the 3000 changed files)

**Comment by oxi-dev0** [comment]
Ah i see. How do I resolve this?

**Comment by AThousandShips** [comment]
You need to restore your branch with `git reset --hard d09bd34` and then use a rebase to update and fix, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by oxi-dev0** [comment]
Thanks for the help!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
