### PR TITLE
Fix `input_event` signal on Android

### LINKED ISSUE #89683: Area2D's input_event signal doesn't work on Android in v4.3.dev5.official [89f70e98d] and master [fe01776]
### Tested versions

- Reproducible in v4.3.dev5.official [89f70e98d] and master [fe01776f05b1787b28b4a270d53037a3c25f4ca2]
- Not reproducible in v4.2.1.stable.official [b09f793f5]

### System information

Windows 10 - Godot 4.3.dev5/master - Forward+ (Vulkan)

### Issue description

Area2D's input_event signal doesn't work on Android in v4.3.dev5.official [89f70e98d] and master.
Works fine in 4.2.1.

### Steps to reproduce

1. Create a new project in latest master or 4.3.dev5.
2. Add a Node2D as root node.
3. Add a simple Label for debugging.
4. Add Area2D with CollisionShape2D. Set it's size.
5. Add script to Area2D and connect `input_event` signal to a new function.
6. Set text of Debug Label in this new function.
7. Install and setup Android templates.
8. Test locally and see it work.
9. One-click deploy to an Android phone.
10. No inputs are detected.

### Minimal reproduction project (MRP)

- Reproducible MRPs:
	- v4.3.dev5.official [89f70e98d] - [Area2DInputTestAndroid-4.3-dev5.zip](https://github.com/godotengine/godot/files/14654874/Area2DInputTestAndroid-4.3-dev5.zip)
	- master [fe01776f05b1787b28b4a270d53037a3c25f4ca2] - [Area2DInputTestAndroid-4.3-master.zip](https://github.com/godotengine/godot/files/14654884/Area2DInputTestAndroid-4.3-master.zip)
- Not reproducible MRPs:
	- v4.2.1.stable.official [b09f793f5] - [Area2DInputTestAndroid.zip](https://github.com/godotengine/godot/files/14654891/Area2DInputTestAndroid.zip)

### PR DESCRIPTION
**Pull request by Alex2782**
Fixes: #89683

**Test**: [Area2DInputTestAndroid-4.3-dev5.zip](https://github.com/godotengine/godot/files/14654874/Area2DInputTestAndroid-4.3-dev5.zip)

https://github.com/godotengine/godot/assets/41921395/bb50725c-8153-437b-bbb1-fd3a5eb94b6c

### CODE REVIEW

**Comment by Sauermann** [comment]
I believe, that the PR in its current form will introduce for focused `Windows` the following problem:

Windows could now receive delayed input events from the OS after the mouse has left the window, leading to `mouse_in_window = true` even though the mouse is not inside the Window.

**Comment by Alex2782** [comment]
Everything seems to be ok on **MacOS**, or how should I test?

`mouse_in_window` is always `false` when the mouse leaves the window. (video below, `print_line` outputs)

```cpp
void Window::_update_mouse_over(Vector2 p_pos) {

	print_line("void Window::_update_mouse_over: mouse_in_window:", mouse_in_window, "focused:", focused);

	if (!mouse_in_window) {
		if (is_embedded()) {
			mouse_in_window = true;
			_propagate_window_notification(this, NOTIFICATION_WM_MOUSE_ENTER);
		} else if (!focused) {
			// Prevent update based on delayed InputEvents from DisplayServer.
			// Also check whether the window is not focused.
			// Android and iOS do not send 'WINDOW_EVENT_MOUSE_*' events, 'mouse_in_window' is always false.
			return;
		}
	}
```


https://github.com/godotengine/godot/assets/41921395/bc15cf81-3a49-47ad-a212-20d307308f25

**Comment by Sauermann** [comment]
I have tested the PR (rebased on 7d151c83811f8ac8873439826c16d88c83aba12f) on Linux X11 and can confirm my previously mentioned problematic behavior.

MRP: [area2d-oob.zip](https://github.com/godotengine/godot/files/14763329/area2d-oob.zip)

Move the mouse from inside the Window to outside the window. Afterwards (not always, but in about 25% of my tests) one of the labels tells "in vp", indicating, that the mouse is over the viewport, contradicting the fact, that the mouse is outside of the window.

**Review by Sauermann — CHANGES_REQUESTED** [review]
The PR needs to address the above mentioned problem.

**Comment by Alex2782** [comment]
I could not reproduce `delayed InputEvents from DisplayServer` on MacOs and I do not currently have Linux X11. 

The new solution now forces `WINDOW_EVENT_MOUSE` events on the Android side. Another solution would be to check if it is an Android device, I always try to avoid such solutions.

**Review by Sauermann — APPROVED** [review]
While I'm not familiar with Android loop callbacks, the usage of `WINDOW_EVENT_MOUSE_*` looks correct: It takes care of setting mouse-over states.
Haven't tested the PR though.

I agree, that revisiting these events will become necessary, if multi window support gets implemented.

For reference: #89920 approaches the problem from a different side, that is more aligned with the initial implementation of this PR.

**Review by m4gr3d — CHANGES_REQUESTED** [review]
> I think if [multi-window-support](https://developer.android.com/guide/topics/large-screens/multi-window-support) is introduced at some point, the events will have to be revised again.

Multi-window support is on the roadmap (Godot 4.4), and we are already experimenting with it for the Godot XR Editor, so this PR will need to be revised to account for it.

If I'm reading right, in a multi-window world each window will fire the `WINDOW_EVENT_MOUSE_ENTER` event causing input focus to randomly switch back and forth between each window; is that correct?

**Comment by Sauermann** [comment]
@m4gr3d While setting `mouse_in_viewport = true` for android (and introducing an inconsistent state) would solve this problem, I believe that it would be better to fix the underlying problem.
And that underlying problem is that the order of input events and window events from the `DisplayServer` can get mixed up. #89920 is my attempt to fix this underlying problem for all platforms.

**Comment by Alex2782** [comment]
This PR is no longer necessary if `return` is removed again.

https://github.com/godotengine/godot/pull/89920/files
image

**Pull request closed without merging**
