### PR TITLE
Make it clearer that `range` allocates in the docs

### PR DESCRIPTION
**Pull request by ghost**
Despite `range` being the idiomatic way to loop in GDScript, it does have the undesirable behavior of allocating an entire array. This is not a big problem when the iteration count is small, but occasionally people will run long loops with it and encounter problems (e.g. trying to benchmark code in #30606). Thus, it's worth the repetition to make the behavior clearer in the docs, and show an example of it done right.

### CODE REVIEW

**Comment by hunte922** [comment]
I'm getting worse performance with your while loop than I am with range().

image
image

**Comment by toasteater** [comment]
...I have to admit I did make the mistake of making the PR without properly benchmarking first. It's so unthinkable that allocating a huge array can actually be faster, but I do confirm that it is.

It does show how slow GDScript is compared to C++.

Closing the PR.

<details>
<summary>Script used to benchmark and results</summary>  

## Script

```gdscript
const ITERATIONS = 10000000

func _ready():
	_range_loop()
	_range_loop_sep()
	_while_loop()

func _while_loop():
	var i = 0
	var start = OS.get_ticks_msec()
	var sum = 0
	while i < ITERATIONS:
		sum += 1
		i += 1
	print("while_loop: ", OS.get_ticks_msec() - start, " (sum = ", sum, ")")

func _range_loop():
	var start = OS.get_ticks_msec()
	var sum = 0
	for i in range(ITERATIONS):
		sum += 1
	print("range_loop: ", OS.get_ticks_msec() - start, " (sum = ", sum, ")")

func _range_loop_sep():
	var start = OS.get_ticks_msec()
	var x = range(ITERATIONS)
	var sum = 0
	for i in x:
		sum += 1
	print("range_loop_sep: ", OS.get_ticks_msec() - start, " (sum = ", sum, ")")
```

## Results

```
range_loop: 806 (sum = 10000000)
range_loop_sep: 1055 (sum = 10000000)
while_loop: 1495 (sum = 10000000)
```
</details>

**Comment by hbina** [comment]
Pretty sure it is always better to allocate as much memory, if you know you are going to need them. The larger the array, the more the cost of getting wrong (because you have to reallocate). Hence, the result.

**Comment by toasteater** [comment]
@hbina This is not about pushing data into a vector, but allocating an array of size N *just* for iterating N times.

**Comment by bojidar-bg** [comment]
@toasteater bfef8de1bc4f7a7b9617a7b181881129033a0b0e made it so that `for i in range(x):` is converted to `for i in int(x):`, which is then used to iterate over the range without allocating elements.

**Comment by hbina** [comment]
@bojidar-bg wouldn't `while i < size(x)` be isomorphic to that? Why the perf difference.

**Comment by bojidar-bg** [comment]
@hbina `while i < size(x)` or even just `while i < x` are both slower due to using more GDScript opcodes instead of native C++ code.

**Comment by toasteater** [comment]
@bojidar-bg I see then. Would it be possible to make this an API-level guarantee, by changing `range`'s signature, or introducing another function that's specified to do this? It'd be better if users could rest assured that their loops will be fast, instead of having to rely on faith in magic.

**Comment by bojidar-bg** [comment]
@toasteater That's worthy of a discussion issue on its own, I think, due to potential compatibility breakage and consistency of GDScript code.

**Pull request closed without merging**
