### PR TITLE
Fix shadow filter pcf5 implemented as pcf7

### LINKED ISSUE #10621: PCF5 variant of the Light2D shadow filter changes light
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04, Godot 3.0 alpha1, AMD HD7950

**Issue description:**
I'm getting a strange change in light when using the PCF5 variant of the Light2D Shadow Filter.

It feels like a bug to me, but I'm no expert.

### PR DESCRIPTION
**Pull request by letheed**
Fixes #10621

### CODE REVIEW

**Comment by reduz** [comment]
maybe should be renamed to pcf7 then :P

**Comment by letheed** [comment]
Do you want me to do that and add a PCF5 proper? Not having anything between 3 and a 7 color gradient seems silly.

Also: I'm not very familiar with the low level graphic stack; is there a reason shadow_filter is a list of select variants and not just an int for the number of steps in the filter gradient?

**Comment by reduz** [comment]
yeah feel free to do it

**Comment by akien-mga** [comment]
Merging the current bugfix already, but noting that adding a proper PCF7 mode would be welcome.

**Pull request merged**
