### PR TITLE
Fix custom resources often missing from Quick Load dialog

### LINKED ISSUE #93813: Custom resources often missing from `Quick Load` dialog.
### Tested versions

Reproducible in 4.3.beta2

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.5599) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Custom resources often don't show up when you try to browse them through the `Quick Load` on an exported property of that type.

The exact rules of whether each resource shows up or not are unpredictable. Sometimes only one will show up, sometimes all will, and sometimes none. Sometimes a simple inspection will cause them to show up from then on, but sometimes that won't work. However there is at least a reliable repro to observe the problem in some form, in a fresh project (no cache).

https://github.com/godotengine/godot/assets/13228932/8c430e98-c18e-41b7-bcb2-049da06c37d1

### Steps to reproduce

- Open the attached project (make sure this is the first time by deleting the `.godot` folder).
- Create three custom resources in the project of type `BlobData`.
- Select the root node in the test scene, and use `Quick Load` to browse for a `BlobData` for the exported property.
- Note that only _the last_ resource shows up (though sometimes all three do).
- Reload the project.
- Select the root node again and browse for a `BlobData` again.
- Note that now the browser dialog is entirely empty. No resource shows up.
- Try dragging the resources manually into the property field.
- Browse for a `BlobData` again.
- The browser dialog will probably be empty still (but maybe not).

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/16053343/bug-report.zip)

### PR DESCRIPTION
**Pull request by JustVicctor**
Fixes #93813 

Fixed the assignment to ```fc.resource_script_class``` and ```fc.type```

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
Makes sense, haven't tested yet though but makes sense

**Comment by akien-mga** [comment]
Rebased to edit the commit message. Please make sure to use a meaningful commit message for future PRs, see https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

**Review by akien-mga — APPROVED** [review]
Seems to fix the bug from a quick test, though the bug's apparent randomness is hard to correlate with how it's being fixed.

The code could maybe be made slightly cleaner but the only ideas I have may actually be more confusing that the current one, e.g.:
```cpp
FileCache fc;
fc.type = split[1].get_slice("/", 0);
fc.resource_script_class = split[1].get_slice("/", 1); // Empty string if there's no separator.
```
I think I prefer the `has` check which makes it clear it's not always present.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
