### PR TITLE
Add a revert menu item

### PR DESCRIPTION
**Pull request by erbridge**
This adds a menu item to revert the scene to the saved version.

This is my first look at the source, so please let me know if I've missed something.

### CODE REVIEW

**Comment by TheoXD** [comment]
I usually do File -> Open Recent -> ... and select first item on the list, because it is always the current scene. Also there might be a chance that someone clicks the button by accident, with no way to Redo the reversion (it's right in between Redo and Run Script) . And it makes the list longer.

**Comment by erbridge** [comment]
A side effect of using `open_request` seems to be that the "Current scene not saved. Open anyway?" dialog pops up, so there is a confirmation. Agreed it would be better to be more intentional about it. I'll have a look at doing that.

**Comment by erbridge** [comment]
Oh, that was pretty painless. "Revert Scene" is now better positioned and has its own confirmation.

**Comment by TheoXD** [comment]
Completely forgotten about that dialog, regular "Open Scene" bypasses it, so I assumed that would be the case here. But I'm ok now with positioning and open_request() :)

**Comment by erbridge** [comment]
Better to be explicit, I think, rather than relying on side effects.

**Comment by erbridge** [comment]
This would help with #1278.

**Pull request merged**
