### PR TITLE
Fixes variable/signal nodes not renaming in visualscript editor

### PR DESCRIPTION
**Pull request by theoway**
**Fixes** #55265 

**Bug**: Variable/singal nodes would not get renamed after their names were changed in the panel. Only the function nodes worked right.

**In the patch:** This PR fixes this issue by updating the `VisualSript` nodes and `Graph` nodes, when their resepctive member from the panel is edited.

_After the fix:_

https://user-images.githubusercontent.com/41969735/143295302-6663a518-dd07-4ced-a872-4da343b42b0a.mp4

### CODE REVIEW

**Review by fire — APPROVED** [review]
The video seems to do what the description says. The code makes sense.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Comment by akien-mga** [comment]
Undid my cherry-picks as the code changes in `master`, `get_node` and `get_node_list` used to require a func argument too. A dedicated PR for `3.x` would be welcome :)

**Comment by theoway** [comment]
@akien-mga Sure, I can do that! 😄

**Pull request merged**
