### PR TITLE
Itemlist make first selected item as default

### PR DESCRIPTION
**Pull request by AlexHolly**
added one example for idx=selected as default

part of #16217

To make this consistent all `(s/g)et_item_*(idx(,..))` and `remove_item(idx)`, (maybe more) functions would need this behavior.

```
extends Node

func _ready():
	var item_list = ItemList.new()
		
	item_list.add_item("A")
	item_list.add_item("B")
	item_list.add_item("C")
	item_list.select() # C
	print(item_list.get_item_text()) # C
	
	item_list.select(0) # A
	print(item_list.get_item_text()) # A
	item_list.remove_item() # A removed
	
```

### CODE REVIEW

**Comment by akien-mga** [comment]
It does not respect the style guide, see the Travis output for the static check, and http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html

**Review by AlexHolly — COMMENTED** [review]
https://github.com/AlexHolly/godot/blob/b173498ecef25fa38fca84525a1e4fa3546ee777/scene/gui/item_list.h#L176

Is the default value in .h needed? Looks like it works without it.

**Comment by bojidar-bg** [comment]
Well, the default value isn't required, but would be nice to have there as well for consistency.

**Comment by AlexHolly** [comment]
I am not able to add this feature to the setter since the second parameters have no default value.
My use case was only about the getter anyway.

**Pull request closed without merging**
