### PR TITLE
Add math/script expression evaluation in editor (rebase of #453)

### PR DESCRIPTION
**Pull request by francogarcia**
This pull request rebases #453 to the master branch and fixes a return value in `PropertyEditor::_might_be_in_instance()`.

Steps performed:

```
git remote add  marynate https://github.com/marynate/godot.git
git fetch marynate PR-property-expression
git cherry-pick 5e46258 0d4a7a4
# Fixed conflicts, then applied 5e46258.
git cherry-pick --continue
# Applied 0d4a7a4.
git cherry-pick --continue
```

It follows @marynate implementation; therefore, it currently supports numeric (double) return values.

It is possible to further improve the implementation by supporting other data types using the same strategy (see https://github.com/francogarcia/GD-REPL).

Currently, I managed to run single line expressions and simple code blocks, converting the results to strings. Returning a variant would be more appropriate, I think. Advices are welcome.

Before, however, I would like to know if GDScript has an `eval`/`evaluation` statement, as I could not find one. Actually, looking for it was how I found @marynate's pull request. :)

Thanks in advance. Best regards.

### CODE REVIEW

**Comment by vnen** [comment]
Copying relevant comment from @LeonardMeagher2:

> Should "this" be changed to "self" since that's the keyword in gdscript?

**Comment by francogarcia** [comment]
Hello, @vnen,

This is a good question. I should had addressed it in the post.

`self` does not work in this situation. `this` does not reffer to the script
`self`: rather, it references the scene's item that is currently being edited.

It becomes clearer if we examine the implementation details:

```
void PropertyEditor::edit(Object* p_object) {


	if (obj==p_object)
		return;
	if (obj) {

		obj->remove_change_receptor(this);
	}

	obj=p_object;

	evaluator->edit(p_object);

    // Code continues...
```

Keep note of the last line (`evaluator->edit(p_object)`). Next, let us examine
`edit()`:

```
void PropertyValueEvaluator::edit(Object *p_obj) {
	obj = p_obj;
}
```

Now, let us advance to the evaluation call:

```
double PropertyValueEvaluator::eval(const String& p_text) {

	 // Fall back to the original value itself.
	if (!obj)
		return _default_eval(p_text);

	// Some code...

	ScriptInstance *script_instance = script->instance_create(this);

	Variant::CallError call_err;
	script_instance->call("set_this",obj);

	// Code continues
```

`obj` here actually references the editor node inspector, as the can see by the
snippets.

The `this` reference points to the editor's scene spector attributes, not to the
`self` object itself --- the instance of the script. Thus, in @marynate's third
image, `this.get_pos().x` returns the value 0, which is the X coordinate of the
position the Node2D transform.

`self.get_pos()`, instead, would call the expression's `get_pos()` method, which
does not exist in this context (as `Node` does not have a position).

As `self` is a keyword, I believe I cannot change its value --- at least I
expect so! :)

However, I can change the variable name, should you wish. I tried to minimize
changing the original code, as I was not the creator.

Hope it helped! Otherwise, just ask!

Best regards,
Franco

**Comment by akien-mga** [comment]
OK let's merge. I'm still not 100% sure about creating this new ``core/helper`` folder just for that, but it can always be removed around in master if need be.

**Comment by akien-mga** [comment]
Well, I took a bet that by squashing the three commits into one they would appear as made by @marynate (as the third one by @francogarcia is just a fixup), but it didn't turn out like that. Silly GitHub. So, sorry about the lost attribution, hopefully the issues link in the commit log make things clear.

**Pull request merged**
