### PR TITLE
Document CollisionObject2D pickable requires collision_layer

### PR DESCRIPTION
**Pull request by lopho**
Document CollisionObject2D signals ```mouse_entered```, ```mouse_exited``` and ```input_event``` require at least one ```collision_layer``` to be set.

Sadly, ```collision_layer``` is implemented, and thus documented in the child classes ```Area2D``` and ```PhysicsBody2D``` (why not in the parent class?), so this might be a source of confusion.

Clarifies #11159

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Thank you!

`[\code]` should be `[/code]` instead.

**Review by mhilbrunner — CHANGES_REQUESTED** [review]
Change `[\code]` to `[/code]`

**Comment by lopho** [comment]
Sorry, stupid typo + copy paste. Fixed.

**Comment by mhilbrunner** [comment]
No worries, thanks for the fix! Can you squash your commits into one?

**Comment by lopho** [comment]
Sheesh, I'm seem to be not up to par today, sorry. I messed that squash up as well. oh boy...

**Comment by mhilbrunner** [comment]
Again, no worries! I had to get used to the GitHub workflow too :) 

Maybe this can help:
https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request

If it doesn't, if you want you can also close this PR and submit the changes as a new PR :)

**Comment by lopho** [comment]
Yeah, I'm not used to squashing. I'll open a new PR, messing around with this PR for 3 lines is wasted time.

**Comment by lopho** [comment]
new PR: #28608

**Pull request closed without merging**
