### PR TITLE
Fix pluginscript editor preview

### PR DESCRIPTION
**Pull request by touilleMan**
/!\ this PR also contains #15535 (given they modify the same file...)

### CODE REVIEW

**Comment by akien-mga** [comment]
> /!\ this PR also contains #15535 (given they modify the same file...)

Well you can modify the same file in two different PRs :)
They don't modify the same code chunk so they won't conflict.

**Comment by akien-mga** [comment]
#15535 is merged so this one needs a rebase, otherwise the first commit will appear twice in the history (I think).

**Comment by touilleMan** [comment]
@akien-mga rebased

**Review by karroffel — APPROVED** [review]
Looks good (untested TM)

**Pull request merged**
