### PR TITLE
[3.x] Add `global_translation` and `global_rotation` to `Spatial`

### PR DESCRIPTION
**Pull request by AaronRecord**
Cherry-picks 8b16a4131fa1073c098a6ac1c987cfd7d6bb5408

### CODE REVIEW

**Comment by foxydevloper** [comment]
It should be `global_translation` over `global_position`, as the position property is `translation` in 3.x

**Comment by AaronRecord** [comment]
> It should be `global_translation` over `global_position`, as the position property is `translation` in 3.x

Okay should be all good now

**Review by akien-mga — APPROVED** [review]
It's purely new code so should be safe to merge now for 3.5.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
