### PR TITLE
Fix crash with consecutive commas in Dictionary

### LINKED ISSUE #52038: GDScript 2.0: Crash when writing a dictionary with Lua-style syntax and consecutive commas
### Godot version

4.0.dev (0df9895eb)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.57.02)

### Issue description

This syntax is invalid, but it should not crash the editor or engine:

```gdscript
extends Node

func _ready():
	# Note the two commas (instead of just one).
	var dictionary = { hello = "world",, }
```

This bug doesn't occur with Python-style dictionary syntax (`{ "hello": "world", }`).

I found this crash while working on https://github.com/godotengine/godot/pull/48029.

#### Backtrace

```
[1] /lib64/libc.so.6(+0x3d320) [0x7fc7278c4320] (??:0)
[2] GDScriptParser::parse_dictionary(GDScriptParser::ExpressionNode*, bool) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:2459)
[3] GDScriptParser::parse_precedence(GDScriptParser::Precedence, bool, bool) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:1973)
[4] GDScriptParser::parse_expression(bool, bool) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:1998)
[5] GDScriptParser::parse_variable(bool) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:826)
[6] GDScriptParser::parse_variable() (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:783)
[7] GDScriptParser::parse_statement() (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:1418)
[8] GDScriptParser::parse_suite(String const&, GDScriptParser::SuiteNode*, bool) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:1344)
[9] GDScriptParser::parse_function() (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:1240)
[10] void GDScriptParser::parse_class_member<GDScriptParser::FunctionNode>(GDScriptParser::FunctionNode* (GDScriptParser::*)(), GDScriptParser::AnnotationInfo::TargetKind, String const&) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:684)
[11] GDScriptParser::parse_class_body() (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:748)
[12] GDScriptParser::parse_program() (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:565)
[13] GDScriptParser::parse(String const&, String const&, bool) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_parser.cpp:347)
[14] GDScript::reload(bool) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript.cpp:817)
[15] GDScriptCache::get_full_script(String const&, Error&, String const&) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript_cache.cpp:213)
[16] ResourceFormatLoaderGDScript::load(String const&, String const&, Error*, bool, float*, ResourceFormatLoader::CacheMode) (/home/hugo/Documents/Git/godotengine/godot/modules/gdscript/gdscript.cpp:2242)
[17] ResourceLoader::_load(String const&, String const&, String const&, ResourceFormatLoader::CacheMode, Error*, bool, float*) (/home/hugo/Documents/Git/godotengine/godot/core/io/resource_loader.cpp:197)
[18] ResourceLoader::_thread_load_function(void*) (/home/hugo/Documents/Git/godotengine/godot/core/io/resource_loader.cpp:224)
[19] ResourceLoader::load(String const&, String const&, ResourceFormatLoader::CacheMode, Error*) (/home/hugo/Documents/Git/godotengine/godot/core/io/resource_loader.cpp:569)
[20] ResourceLoaderText::load() (/home/hugo/Documents/Git/godotengine/godot/scene/resources/resource_format_text.cpp:455)
[21] ResourceFormatLoaderText::load(String const&, String const&, Error*, bool, float*, ResourceFormatLoader::CacheMode) (/home/hugo/Documents/Git/godotengine/godot/scene/resources/resource_format_text.cpp:1360)
[22] ResourceLoader::_load(String const&, String const&, String const&, ResourceFormatLoader::CacheMode, Error*, bool, float*) (/home/hugo/Documents/Git/godotengine/godot/core/io/resource_loader.cpp:197)
[23] ResourceLoader::_thread_load_function(void*) (/home/hugo/Documents/Git/godotengine/godot/core/io/resource_loader.cpp:224)
[24] ResourceLoader::load(String const&, String const&, ResourceFormatLoader::CacheMode, Error*) (/home/hugo/Documents/Git/godotengine/godot/core/io/resource_loader.cpp:569)
[25] Main::start() (/home/hugo/Documents/Git/godotengine/godot/main/main.cpp:2363)
[26] bin/godot.linuxbsd.tools.64.llvm(main+0x19f) [0x4bd85cf] (/home/hugo/Documents/Git/godotengine/godot/platform/linuxbsd/godot_linuxbsd.cpp:57)
[27] /lib64/libc.so.6(__libc_start_main+0xd5) [0x7fc7278aeb75] (??:0)
[28] bin/godot.linuxbsd.tools.64.llvm(_start+0x2e) [0x4bd836e] (??:?)
-- END OF BACKTRACE --
```

### Steps to reproduce

- Paste the above script in the script editor.
- Wait a few seconds or save. The editor will crash.

### Minimal reproduction project

[gdscript_dictionary_consecutive_comma_crash.zip](https://github.com/godotengine/godot/files/7034658/gdscript_dictionary_consecutive_comma_crash.zip)
**Note:** The above project will crash when opened in the editor or run from the project manager.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #52038

### CODE REVIEW

**Review by Ansraer — CHANGES_REQUESTED** [review]
According to the report this syntax is invalid. So in addition to not crashing we should probably also display an error message for the user. Something like: "Cannot add empty element to dict."

**Comment by vnen** [comment]
> According to the report this syntax is invalid. So in addition to not crashing we should probably also display an error message for the user. Something like: "Cannot add empty element to dict."

There's already an error message if the key is empty.

**Comment by vnen** [comment]
This looks good to me, if you could add a test case for this it would be great.

**Comment by KoBeWi** [comment]
@vnen Test added.

**Review by vnen — APPROVED** [review]

**Comment by vnen** [comment]
Thanks!

**Pull request merged**
