### PR TITLE
Add Graph Illustrations to Doc

### PR DESCRIPTION
**Pull request by mechPenSketch**
Continuing off from https://github.com/godotengine/godot/pull/46407, this time replacing the img tags with url, as instructed by @Calinou.

### CODE REVIEW

**Comment by fire** [comment]
Approved the workflows to test if the pr is acceptable.

**Comment by pycbouh** [comment]
I think it's supposed to be `[url=link]text[/url]` or `[url=link][/url]`. You can probably wrap the added text into the link here.

**Comment by Calinou** [comment]
Bare URLs work, but they don't look great. I would recommend doing something like this instead (taken from https://github.com/godotengine/godot/blob/c7455d9d4284958d3ffed716ae4c7e192fb1a573/doc/classes/Tween.xml):

`[url=https://raw.githubusercontent.com/godotengine/godot-docs/master/img/tween_cheatsheet.png]Tween easing and transition types cheatsheet[/url]`

**Review by mhilbrunner — APPROVED** [review]
Looks good to me

**Comment by mhilbrunner** [comment]
Thanks, and congrats on your first contribution! 🎉

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
