### PR TITLE
Support colored font

### LINKED ISSUE #10873: Emoji support
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows, Godot 2.1.4

**Issue description:**
Godot does not render many emojis.  I attempted to use a RichTextLabel containing the text:

`te😊x🌐t🔼ᴥ♻🚀❂☮☯🚀🎡🚢🍭💦🔻`

And instead what renders is:

image

I did this using a dynamic font for the node and I tried loading EmojiOneColor-SVGinOT.ttf, OpenSansEmoji.ttf, and unifont-10.0.06.ttf all with very limited success.  The EmojiOneColor comes with a demo which, when opened in Chrome, renders just fine in B&W including many of the symbols I'm looking to use.  Finding an adequate demo of the other fonts is a bit more difficult than I imagined.

### PR DESCRIPTION
**Pull request by volzhs**
This PR supports colored font with CBDT format.
Closes #10873

screenshot from 2018-01-16 22-21-19

### CODE REVIEW

**Comment by reduz** [comment]
Wow, awesome.. 3.1 feature :D

**Comment by volzhs** [comment]
I think there's something left I need to take care.
I guess colored font should be only affected by alpha.
screenshot from 2018-01-16 22-28-58
then we can change color for normal(?) font but not emoji.

**Comment by volzhs** [comment]
screenshot from 2018-01-16 22-36-48
Colored font is affected only alpha channel by font color.

**Comment by Dillybob1992** [comment]
Godot's in-game chats are about to become lit 💯

**Comment by akien-mga** [comment]
Great job!

**Comment by eon-s** [comment]
Cherry pick it! :D (if possible)

**Comment by fire** [comment]
What free type version do I need? It broke my build again :( 

```
scene/resources/dynamic_font.cpp: In member function 'Error DynamicFontAtSize::_load()':
scene/resources/dynamic_font.cpp:189:23: error: 'FT_HAS_COLOR' was not declared in this scope
  if (FT_HAS_COLOR(face)) {
                       ^
scene/resources/dynamic_font.cpp: In member function 'float DynamicFontAtSize::draw_char(RID, const Point2&, CharType, CharType, const Color&, const Vector<Ref<DynamicFontAtSize> >&) const':
scene/resources/dynamic_font.cpp:352:30: error: 'FT_HAS_COLOR' was not declared in this scope
     if (FT_HAS_COLOR(fb->face)) {
                              ^
scene/resources/dynamic_font.cpp:379:25: error: 'FT_HAS_COLOR' was not declared in this scope
    if (FT_HAS_COLOR(face)) {
                         ^
scene/resources/dynamic_font.cpp: In member function 'void DynamicFontAtSize::_update_char(CharType)':
scene/resources/dynamic_font.cpp:457:58: error: 'FT_HAS_COLOR' was not declared in this scope
  int error = FT_Load_Char(face, p_char, FT_HAS_COLOR(face) ? FT_LOAD_COLOR : FT_LOAD_DEFAULT | (font->force_autohinter ? FT_LOAD_FORCE_AUTOHINT : 0));
                                                          ^
scene/resources/dynamic_font.cpp:457:62: error: 'FT_LOAD_COLOR' was not declared in this scope
  int error = FT_Load_Char(face, p_char, FT_HAS_COLOR(face) ? FT_LOAD_COLOR : FT_LOAD_DEFAULT | (font->force_autohinter ? FT_LOAD_FORCE_AUTOHINT : 0));
                                                              ^
scene/resources/dynamic_font.cpp:496:46: error: 'FT_PIXEL_MODE_BGRA' was not declared in this scope
  int color_size = slot->bitmap.pixel_mode == FT_PIXEL_MODE_BGRA ? 4 : 2;
                                              ^
scene/resources/dynamic_font.cpp:599:11: error: the value of 'FT_PIXEL_MODE_BGRA' is not usable in a constant expression
      case FT_PIXEL_MODE_BGRA: {
           ^
scene/resources/dynamic_font.cpp:496:46: note: 'FT_PIXEL_MODE_BGRA' does not have integral or enumeration type
  int color_size = slot->bitmap.pixel_mode == FT_PIXEL_MODE_BGRA ? 4 : 2;
                                              ^
scons: *** [scene/resources/dynamic_font.x11.opt.tools.64.o] Error 1
```

**Comment by akien-mga** [comment]
> What free type version do I need? It broke my build again :(

I guess 2.5.1 or later (Nov 2013), as the feature was added in freetype mid 2013: https://lists.nongnu.org/archive/html/freetype-devel/2013-07/msg00036.html
What's your system?

**Comment by fire** [comment]
Centos 7.4 is the system I'm using to build. However, I thought you included freetype in the source.

**Comment by akien-mga** [comment]
Use `builtin_freetype=yes` then.

**Comment by fire** [comment]
Works. Thanks!

**Pull request merged**
