### PR TITLE
Fix mismatch between String and StringName in dictionary keys

### LINKED ISSUE #44241: Dictionary element are not available by index
**Godot version:**
custom d0f1c03b4

**OS/device including version:**
Windows 10

**Issue description:**
Cannot find existing key in Dictionary

**Steps to reproduce:**
Empty project
Create node
Add script 
`func _ready():
	var dict: Dictionary = {
		"elem1": 1,
		"elem2": 2,
	}
	print(dict)
	print(dict["elem1"])`

Output:
{elem1:1, elem2:2}

Debug:
Invalid get index 'elem1' (on base: 'Dictionary').

**Minimal reproduction project:**
[bugreport.zip](https://github.com/godotengine/godot/files/5668913/bugreport.zip)

### PR DESCRIPTION
**Pull request by vnen**
Fixes the problems mixing String and StringName types when used as dictionary keys. This means users will have to be more careful of what they use as keys.

For reference, this is the expected behavior:

```gdscript
var dict = {"a": 1, &"b": 2}
print(dict["a"]) # should work
print(dict[&"a"]) # should NOT work
print(dict["b"]) # should NOT work
print(dict[&"b"]) # should work
print(dict.a) # should NOT work
print(dict.b) # should work
```

Note that shorthand notation (`dict.a`) assumes the key is a StringName). Also the new StringName literal notation: `&"name"`.

This PR also makes sure the Lua-style dictionary literal uses StringName as keys, so the shorthand works too:

```gdscript
var dict = {a = 1, b = 2}
print(dict["a"]) # should NOt work
print(dict[&"a"]) # should work
print(dict["b"]) # should NOT work
print(dict[&"b"]) # should work
print(dict.a) # should work
print(dict.b) # should work
```

Fixes #44241
Supersedes #47899

### CODE REVIEW

**Comment by akien-mga** [comment]
Also supersedes #44310?

**Comment by vnen** [comment]
> Also supersedes #44310?

That one does a different thing, which allows String and StringName to be the same. I believe we want to keep the idea that different types are always different, so that one probably shouldn't be merged, but it can be evaluated in its own merit (though I don't think it's the proper fix for this).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AndreaCatania** [comment]
Thanks!!

**Pull request merged**
