### PR TITLE
Rename OptionButton to DropDownList

### LINKED ISSUE #1998: Rename OptionButton to DropDownList
### Describe the project you are working on
Godot engine

### Describe the problem or limitation you are having in your project
As originally mentioned in https://github.com/godotengine/godot/issues/6558, the [`OptionButton`](https://docs.godotengine.org/en/stable/classes/class_optionbutton.html) is actually a [Drop-down List](https://en.wikipedia.org/wiki/Drop-down_list).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Rename `OptionButton` to `DropDownList`.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
As above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
N/A

### Is there a reason why this should be core and not an add-on in the asset library?
N/A

### PR DESCRIPTION
**Pull request by madmiraal**
As originally mentioned in #6558, the [`OptionButton`](https://docs.godotengine.org/en/stable/classes/class_optionbutton.html) is actually a [`Drop-Down List`](https://en.wikipedia.org/wiki/Drop-down_list).

This PR renames `OptionButton` to `DropDownList`.

Closes https://github.com/godotengine/godot-proposals/issues/1998

### CODE REVIEW

**Comment by aaronfranke** [comment]
Can we just call it DropDown? I don't think the "List" suffix is ideal for a node type.

**Comment by groud** [comment]
> Can we just call it DropDown (or similar)? I don't think the "List" suffix is ideal for a node type.

I was thinking maybe we should go for DropDownButton, since it inherits from Button.

**Comment by madmiraal** [comment]
> I don't think the "List" suffix is ideal for a node type.

We already have [`ItemList`](https://docs.godotengine.org/en/stable/classes/class_itemlist.html)

> I was thinking maybe we should go for DropDownButton, since it inherits from Button.

It's only a `Button`, because, within the engine, it inherits `Button`, but it's a Drop-Down List. Note: `Checkbox` also inherits `Button`, but it's not called `CheckboxButton`. I think it should be called what it is.

**Comment by MaaaxiKing** [comment]
A bit long, but `DropDownListButton` would be the most correct and detailed one.

**Comment by aaronfranke** [comment]
> It's only a `Button`, because, within the engine, it inherits `Button`, but it's a Drop-Down List.

Isn't it a button that creates a drop-down list when clicked?

**Comment by MaaaxiKing** [comment]
Strictly speaking, yes.

**Comment by reduz** [comment]
Is not the most common name for this to be ComboBox ? We have CheckBox already.

**Comment by madmiraal** [comment]
A [`Combobox`](https://en.wikipedia.org/wiki/Combo_box) is something different. A [`Combobox`](https://en.wikipedia.org/wiki/Combo_box) is a [`DropDownList`](https://en.wikipedia.org/wiki/Drop-down_list) with a single line, editable text box that we call a [`LineEdit`](https://docs.godotengine.org/en/stable/classes/class_lineedit.html) that allows the user to either select one of the `DropDownList` items or enter their own value.

**Pull request closed without merging**
