### PR TITLE
Fix #4588 (crash in Control::_set_anchor)

### LINKED ISSUE #4588: Anchor value other than Begin crashes game when run
**Operating system or device - Godot version:**
Arch Linux 64 bit - Godot master branch (8a45936)
git bisect reveals that the issue should effect everything after (and including) 0e8a8d2, which is only in the master branch (was added in #3997, is not in 2.0/Steam).

**Issue description**:
When changing any Control to have an Anchor on anything other than "Begin," the game crashes when run.

I expect the game to run with the Anchor in the new position.

**Steps to reproduce:**
With a Control in the scene tree, change any Anchor from "Begin" to any other value and attempt to run the game.

Alternately, attempt to run a game which uses anchors other than "Begin," which should crash, but should run after changing those values to "Begin."

**Link to minimal example project**:
The official [drag and drop demo](https://github.com/godotengine/godot/tree/master/demos/gui/drag_and_drop) has the root Control node with Anchors set to "End," so it will not run, but will after changing them to "Begin."

### PR DESCRIPTION
**Pull request by bojidar-bg**
@vnen @her001 ~ You might want to test this PR :smile:

### CODE REVIEW

**Comment by vnen** [comment]
Still segfaults in release mode, though it's not really related to your code. Gives me the same problem without this patch even after I revert 0e8a8d2 and bac875b. I'll try to bisect this.

```
(gdb) where
#0  0x0000000000594937 in DVector<String>::resize(int) ()
#1  0x00000000011fdd8c in ResourceInteractiveLoaderBinary::parse_variant(Variant&) ()
#2  0x00000000011fc669 in ResourceInteractiveLoaderBinary::parse_variant(Variant&) ()
#3  0x00000000011ff94b in ResourceInteractiveLoaderBinary::poll() ()
#4  0x000000000122692a in ResourceFormatLoader::load(String const&, String const&, Error*)
    ()
#5  0x00000000012260b9 in ResourceLoader::load(String const&, String const&, bool, Error*)
    ()
#6  0x0000000000429ff3 in Main::start() ()
#7  0x000000000040d0ed in main ()
```

**Comment by vnen** [comment]
Still getting segfault at 37af8b4. How come nobody ever got this bug? Or is it just me?

**Comment by akien-mga** [comment]
@bojidar-bg Should we merge this patch as a general code quality improvement even if it doesn't fix #4588? (if so maybe you could amend the commit log, or alternatively I could do a "squash and merge" and rewrite the log).

**Comment by vnen** [comment]
@akien-mga technically, this *does* fix #4588. But it seems there's another bug with something else that gives segfaults in the GUI demos in release builds. Such bug seems not to be related to this patch or with this feature in general. I will open another issue about it.

**Comment by bojidar-bg** [comment]
@akien-mga ~ well, feel free to rewrite and merge, though it probably does fix the issue (since master without that feature still segfaluts on release).

**Comment by akien-mga** [comment]
Thanks, let's merge then.

**Comment by vnen** [comment]
Opened #4623 about the problem.

**Pull request merged**
