### PR TITLE
Fix regression with GDScript enum descriptions now showing up in documentation

### PR DESCRIPTION
**Pull request by anvilfolk**
Didn't show up before, does now :)

### CODE REVIEW

**Review by dalexeev — APPROVED** [review]
Looks good and works right, it was just an oversight. Thank you for the quick response and fix!

**Review by akien-mga — APPROVED** [review]

**Comment by anvilfolk** [comment]
> Looks good and works right, it was just an oversight. Thank you for the quick response and fix!

Thanks for finding it! :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.

**Pull request merged**
