### PR TITLE
Improve toggle comment function in script editor

### LINKED ISSUE #22214: Commenting with CTRL+K leaves out of the selection the last character of the last line
**Godot version:**
Master, on Ubuntu

**Issue description:**
Using the CTRL+K feature of the script editor to comment some lines, leaves out of the selection the last character of the last line.

### PR DESCRIPTION
**Pull request by akerudesu**
Improved the toggle comment feature to automatically adjust the selection area & cursor position when toggling comments on a section of code.

Should close #22214.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @Paulb23

**Review by Paulb23 — COMMENTED** [review]
Looks good, nice improvement!

One minor issue, If you have the entire `from_line` selected, it doesn't adjust the selection over the comment delimiter.

**Comment by akerudesu** [comment]
I tweaked the behaviour slightly to include the delimiter on the first line in the selection, if the selection starts from column 0. Also updated cursor accordingly. Let me know if anything else should be changed.

**Review by Paulb23 — APPROVED** [review]
Looks Good.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
