### PR TITLE
Filesystem drag & drop moving fixes

### PR DESCRIPTION
**Pull request by ghost**
Fixes to drag & drop functionality regarding dragging items / resources around the filesystem dock.

- Disallow dragging a folder into itself from being a valid move (One issue in #12322)
- Fix dragging a file/folder onto the "Favourites:" item starting an invalid move (Mentioned in #11428)
- Fix the save as functionality when dragging a resource onto the filesystem. 
This used to fail on clicking save with the error:
 `ERROR: EditorNode::_dialog_action: Condition ' !Object::cast_to<Resource>(current_obj) ' is true.
   At: editor\editor_node.cpp:1189`
- Allow dragging folders/files onto of files / empty space in the files list. This will just use the currently open folder.
- Don't show moving a file to the location it currently is in as invalid.
- Pulled some common code out into a helper method.

### CODE REVIEW

**Comment by akien-mga** [comment]
@MillionOstrich This PR and the yet unmerged #10261 will surely conflict as there must be a lot of overlap. Could you help review that one to speed up the process? cc @Cradmon

**Comment by MillionOstrich** [comment]
As a heads up #12390 may also conflict with that PR but from a quick scan through in both cases the conflict should be straight forward to fix if you want to merge #10261 first. I can have a closer look at that PR in more detail this evening.

**Comment by Cradmon** [comment]
After reviewing the mentioned PRs. The changes I made that are overlapping are minor refactoring only, so should be relatively easy to merge.

**Comment by akien-mga** [comment]
Needs rebasing after #10261.

**Pull request merged**
