### PR TITLE
Fix custom modules in Visual Studio

### LINKED ISSUE #42152: Error trying to build godot with Visual Studio
**Godot version:** 2d9b409

**OS/device including version:** Windows 10 

**Issue description:**

When trying to build godot with visual studio after generating sln file with `scons p=windows vsproj=yes`, pressing build solution raises an error with build output with the following: `Build option 'custom_modules' must point to an existing directory.`. I tried commenting out lines 192-199 of the custom_modules code in SConscript in the root directory and it builds and runs.

**Steps to reproduce:**
* generate VS soln file with `vsproj=yes`
* try to build the solution

### PR DESCRIPTION
**Pull request by Listwon**
Without `custom_modules` (empty string by default) scons command in VS project was broken
(fixes regression from commit 6122a504eeb4f8678a012d08a0a8fcc5e661c69e)
Fixes #42152
scons

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @Xrayez

**Comment by Xrayez** [comment]
I'm able to build with and without `custom_modules` option while generating the VS project with `vsproj=yes`. 😮

Tested on Visual Studio 2019, with Python version 3.6.4.

Makes me wonder what Python version do you use which could make it different for you?

Have you used `custom_modules` build option in the past?

To be honest, the way I wrote it is likely error-prone anyway, if this fixes the issue (tested this PR, works), then ok, sorry for introducing regression, was likely a bad idea to add such a feature for something which I don't extensively use myself (`custom_modules` in VS).

**Comment by Xrayez** [comment]
As Akien said, was also too fast to merge #41453, as the build system could be improved to support including other build options (like `module_mono_enabled=yes`, which is disabled by default), but then again requires more work for which I'm not confident to do without introducing yet another regression like this. 🙂

**Comment by Listwon** [comment]
@Xrayez Isn't it handled already in custom.py? We can think of it in another PR. I'll check the issue again on completely separate machine, but it was 100% reproducible if I didn't pass custom_modules creating vsproj with scons - I couldn't build any target inside VS, getting errors as on the attached screenshot.

**Comment by Listwon** [comment]
Scons 3.1.1
Python 3.7.0
It works without any changes. 

Scons 4.0.1
Python 3.8.5
It requires the fix.

Sorry @Xrayez I didn't mention my stack earlier.
I've just fixed code formatting in methods.py.

**Comment by Xrayez** [comment]
@Listwon I've just upgraded to SCons 4.0.1 now (without upgrading Python), I get the same error:
```
1>scons: Reading SConscript files ...
1>Build option 'custom_modules' must point to an existing directory.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "echo Starting SCons && cmd /V /C set "plat=x64" ^& (if "x64"=="x64" (set "plat=x86_amd64")) ^& set "tools=yes" ^& (if "debug"=="release" (set "tools=no")) ^& set "custom_modules=" ^& call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" !plat! ^& scons --directory="D:\src\godot\3" platform=windows progress=no target=debug tools=!tools! custom_modules=!custom_modules! -j6" exited with code 255.
1>Done building project "godot.vcxproj" -- FAILED.
```

It would seem like a regression from SCons in fact, but it's difficult to blame the SCons fellows because of compatibility breakage with 4.0.1.

When printing `env_base["custom_modules"]` from within `SConstruct` the value is: `!custom_modules!`, because somehow it gets undefined. Perhaps there was some breaking changes which return `None` vs "" (empty string) for a construction environment (`env`) which doesn't exists.

> Isn't it handled already in custom.py?

That's certainly an option, and I'd recommend using that if you need to configure more advanced build options currently, it's just that it wouldn't be intuitive for the rest of the people I guess, and I feel like `custom_modules` is essential to prosperity of C++ development outside of Godot, for Godot.

VS still needs to define `PlatformTarget` for the target architecture, the rest can be configured outside of VS.

In any case, like I said, the current implementation is error-prone anyway, by now I've tested your implementation with and without `custom_modules`, both on SCons 3.1.1 and 4.0.1, so feel free to make the same changes on `master` first. Unless @akien-mga has some other ideas about this.

**Comment by Listwon** [comment]
@Xrayez Oh, it wasn't clear. In "Isn't it handled already in custom.py?" what I meant was that `module_mono_enabled=yes` probably works with it and custom.py is properly handled even in VS. But yeah it would be convenient to pass it through the command line as well.

> In any case, like I said, the current implementation is error-prone anyway, by now I've tested your implementation with and without custom_modules, both on SCons 3.1.1 and 4.0.1, so feel free to make the same changes on master first. Unless @akien-mga has some other ideas about this.

Sure.

**Comment by Xrayez** [comment]
Yeah I'm not completely sure about this, building `scons module_mono_enabled=yes vsproj=yes` would work but when you rebuild the solution in VS, `module_mono_enabled=yes` wouldn't be included in VS anymore because that's an option which has to be enabled explicitly every time, not to mention you then need to generate mono glue etc. VS generation could be improved so that it takes all SCons `ARGUMENTS` and pass that to the build prefix, but that's certainly out of scope for this.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
