### PR TITLE
[GDNative] use feature tags, added load once option

### PR DESCRIPTION
**Pull request by karroffel**

### CODE REVIEW

**Comment by endragor** [comment]
I wonder if we actually need "static_linking" as an option. Maybe just treat internally iOS as static, and the rest as dynamic? Ideally we shouldn't bother library creators with this, because they may not be aware about such specifics.

Also, perhaps the name prefix should be made mandatory? Otherwise asset creators may forget to set it and then we have assets that are not compatible between each other (for iOS or wherever static linking is used).

**Comment by karroffel** [comment]
@endragor it's an optional setting. You can leave it out and it's false by default. We can make the iOS OS class just not do the dynamic loading, but I think it's not much work to have it work on other platforms too, it might be useful in other situations (but maybe not 🤔 ).

I can remove those settings, but ideally it's as easy as 
  1. not dynamically load the library
  2. use NULL (or the current module handle) as the handle to look up symbols.

**Comment by endragor** [comment]
I know it's optional, and I was saying that it's likely unnecessary, because people will forget to set it, ending up with libraries incompatible with iOS. So it's better if we take care of it rather than leave it on users. At the moment only iOS requires special treatment.

**Comment by karroffel** [comment]
The iOS `OS` implementation can just treat it all as static linked libraries, but it could still be a runtime option since it's all completely optional, like I said. If you don't put it in the .gdnlib then that's not an error, it would be mandatory for iOS without configuring something and optional (opt-in) for all other platforms

**Comment by endragor** [comment]
Alright, so what do you think about making the name prefix mandatory? Otherwise we can easily get incompatible libraries when someone decides to build an iOS game and use multiple GDNative modules.

**Comment by karroffel** [comment]
Currently they default to `godot_`, but as a library author, if you provide iOS static libraries then it should have a unique prefix. I don't think we can enforce uniqueness, but I can definitely make it not default to `godot_` so people are more likely to pick their own prefixes.

**Comment by karroffel** [comment]
I will merge this now so I can work on exporting, I can make the prefix field mandatory with an error message later on, but I need this PR to continue other things.

**Pull request merged**
