### PR TITLE
Fix AnimationNodeStateMachinePlayback::is_playing

### LINKED ISSUE #24790: Sub state machines always report true after first play.
**Godot version:**
5e6c6f3bb745f8d9be4df938f6cf49dfb552b761

**OS/device including version:**
4.20.0-arch1-1-ARCH

**Issue description:**
`is_playing` for sub state machines always report true after first play, even if it's not playing.

**Steps to reproduce:**
- Press space to travel to sub state machine;
peek 05-01-2019 13-50
- After that, sub state machine always returns `playing` equal `true`.

**Minimal reproduction project:**
[FSM.zip](https://github.com/godotengine/godot/files/2729629/FSM.zip)

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #24790

before:

https://user-images.githubusercontent.com/1387165/182738176-6aefab6e-75bc-405e-a92c-dff61135c37d.mp4

after:

https://user-images.githubusercontent.com/1387165/182738040-bd6696da-7bb0-4ea7-9a8d-ff59af8aeae8.mp4

### CODE REVIEW

**Review by SaracenOne — DISMISSED** [review]
~~Would you mind double-checking this fix? I tested it myself with a modified/updated version of the MRP linked in the original issue, and the bug with the SubStateMachine's Playback's 'is_playing' flag still showing up as true still appears to be present even after leaving the SubStateMachine. I'll link my version of the MRP in the comments.~~ 

Apologizes for the mistaken review; some recent changes to the Godot build system led to accidentally testing this with the wrong binary name. I will test this PR again soon and confirm.

**Comment by SaracenOne** [comment]
[FSMSubStateBug.zip](https://github.com/godotengine/godot/files/9429663/FSMSubStateBug.zip)
Start the project, press space to enter the SubStateMachine, and then any other key to leave it.

**Review by SaracenOne — APPROVED** [review]
As far as I can tell, I think this is okay and contrary to my initial review, does appear to actually fix the issue at hand. I might appreciate some extra comments, particularly at the beginning of AnimationNodeStateMachine::process to explain what is actually going on, but I'm not going halt merging this if anyone wishes to do so.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
