### PR TITLE
Document DirectionalLight2D not supporting cull masks

### PR DESCRIPTION
**Pull request by Calinou**
- See https://github.com/godotengine/godot/issues/48757.

### CODE REVIEW

**Comment by clayjohn** [comment]
Shadow cull masks are supported by DirectionalLight2D and PointLight2D. But DirectionalLight3Ds don't support item cull masks

**Comment by Calinou** [comment]
> But DirectionalLight3Ds don't support item cull masks

Do you mean DirectionalLight2D?

**Comment by clayjohn** [comment]
> > But DirectionalLight3Ds don't support item cull masks
> 
> Do you mean DirectionalLight2D?

Yes! Sorry, updated

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
