### PR TITLE
Core: Fix recursion level check for array stringification

### LINKED ISSUE #55256: Crash when printing array that contains itself
### Godot version

3.4 / 4.0

### System information

W10

### Issue description

When you do do
```GDScript
var a = []
a.append(a)
print(a)
```
Godot will crash.

I checked how Python handles it and it prints `[[...]]`.

### Steps to reproduce

See above.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #55256.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Doesn't cherry-pick easily to `3.x`, could use a dedicated PR.

**Comment by dalexeev** [comment]
In 3.x, printing a recursive array does not crash, this has been fixed by #28217 (using a stack instead of `recursion_count`). However, `var2str` still crashes. This is a `VariantWriter` bug, not `Variant::stringify()`.

```gdscript
var a = []
a.append(a)
print(var2str(a))
```

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
