### PR TITLE
Style: Format `.yaml`/`.yml` files

### PR DESCRIPTION
**Pull request by Repiteo**
Updates the formatting across all of our `.yaml`/`.yml` files. The changes were entirely syntactic/stylistic, with one exception: `runner.yml` only needed the `vars.DISABLE_GODOT_CI` conditional once, so the others have been removed.

### CODE REVIEW

**Comment by Calinou** [comment]
Did you use a tool to format YAML files?

**Comment by Repiteo** [comment]
A basic one in the form of a VSCode extension, plus some manual refactoring. There's likely a relevant pre-commit hook out there, would probably be a good fit alongside these changes.

**Comment by Repiteo** [comment]
Nevermind, won't add any new pre-commit hooks for now. Everything I've looked into seems to need some radical new syntax or other weird caveats, which is beyond the scope of this PR. I think Biome is set to have yaml support in the near-ish future, so it'll make sense to revisit whenever #92439 is merged.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
