### PR TITLE
Rename Geometry2D "point_is_inside_triangle" to "is_point_in_triangle" for consistency

### PR DESCRIPTION
**Pull request by DevPoodle**
I renamed the Geometry2D function "point_is_inside_triangle" to "is_point_in_triangle" for consistency with "is_point_in_polygon" and "is_point_in_circle".

### CODE REVIEW

**Comment by MewPurPur** [comment]
Good rename but this would break existing projects (on top of things like tutorials) without any functional gain. So we can't do it.

**Comment by AThousandShips** [comment]
This does indeed break compatibility, in a major way

**Comment by YuriSizov** [comment]
Thanks for opening a PR! As mentioned above, we can't rename API members in stable releases because we must preserve compatibility. Some exceptions are allowed but for a very good reason. A small inconsistency, while unfortunate, is not that good of a reason to break compatibility. So we have to live with the current name.

I'm going to close this, but I hope you'll find something to contribute in the future! Do check open issues if you're looking for ideas, especially the list of [good first issues](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) which is a great place to start as a new contributor.

**Comment by Volutar** [comment]
Such renaming _is_ possible, but would require either IDE suggestions and perhaps autofixes/normalizations of alternative namings, which going to be not so nice. Legacy is such a legacy... in any case, search and replace through source code wouldn't deal lot of problems, even if renamed. But renaming itself is more of an esthetics, which is not too practical.

**Pull request closed without merging**
