### PR TITLE
Reference the online documentation in collision layer/mask properties

### PR DESCRIPTION
**Pull request by Calinou**
See https://github.com/godotengine/godot-docs/pull/3863.

### CODE REVIEW

**Review by NathanLovato — CHANGES_REQUESTED** [review]
Shouldn't the urls link to the stable version of the documentation? If linking to latest, people may get information that is only valid for an unreleased version of Godot.

**Comment by Calinou** [comment]
> Shouldn't the urls link to the stable version of the documentation? If linking to latest, people may get information that is only valid for an unreleased version of Godot.

We've took the habit of always linking to the `latest` branch of the documentation in other classes. The same is done for tutorials in the `<tutorials>` tag.

**Comment by NathanLovato** [comment]
Alright then, if that's the convention in the reference, that's fine by me. There's just a risk users could stumble upon changes that are for an unreleased version of Godot.

Although I can understand that until now and until the docs are complete, latest can have new information missing in stable.

**Review by NathanLovato — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
About which docs versions to target, for the `master` branch, the docs should target `latest`, which is the corresponding docs. That's especially relevant when documenting new features for the next Godot version, or renamed classes, etc.

Then we could switch to e.g. https://docs.godotengine.org/en/3.2 in the `3.2` branch after it has been branched off, so that 3.2.x releases link to their version of the docs. In practice I never did it as I don't see a big need for it yet, but eventually this might be relevant (especially when we refactor docs for 4.0+).

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
