### PR TITLE
Fixing Vehicle-Wheels getting a random engine_force at start

### LINKED ISSUE #35879: Vehicle-Wheels gets a random engine_force at start
**Godot version:**
3.2 stable
**OS/device including version:**
win8
**Issue description:**
everytime i start the game, every wheel (of every vehicle) gets a different random engine_force applied out of nowhere.
It just happens as long as i dont apply a engine_force to the wheels or vehicle-body.
Surly has to do with the new per-wheel engine_force options.
worked in Version 3.1.2 (same project)
**Steps to reproduce:**
open the project-file an press F5
**Minimal reproduction project:**
[Vehicle_Bug_Demo1.zip](https://github.com/godotengine/godot/files/4148449/Vehicle_Bug_Demo1.zip)
no settings, no script, just a standard vehicle that goes crazy :)

### PR DESCRIPTION
**Pull request by Janglee123**
Fixes #35879.

### CODE REVIEW

**Comment by clayjohn** [comment]
Looks like this is already fixed in Master as well 
https://github.com/godotengine/godot/blob/7724b842f61e570fcfb1254b12df8c9dc30375c6/scene/3d/vehicle_body.cpp#L368

Fixed in commit https://github.com/godotengine/godot/commit/6deffa62fbd1e91873afa663630b788b9ffabee3 for some reason

**Comment by Janglee123** [comment]
In more detail, the code was five years old, but it works perfectly in 3.1, so It might have some reason to comment out it.

**Comment by akien-mga** [comment]
Could you amend the commit message to be clearer? Our commit messages should be a proper English sentence (yet short) that describes what is being fixed. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
