### PR TITLE
WebSocket profiler for HTML5 platform [4.0]

### PR DESCRIPTION
**Pull request by Faless**
Closes #33925 . Much cleaner after the refactor.

In this PR:

-  Remove WebSocket defaults from project settings.
   Can already be manually set, let's not pollute them further (and it was giving troubles with this PR due to the fact that modules project settings are inited too late).
- Platforms can now register additional URI/protocol handlers for debugging. (see `EngineDebugger::register_uri_handler` and `EditorDebuggerServer::register_protocol_handler`)
- `EditorExportPlatform` can now specify the debug protocol (so both the editor and the exported game can match the desired protocol).
- Add new `RemoteDebuggerPeerWebSocket` and `EditorDebuggerServerWebsocket` implementation for debugging (a bit less performant than the regular one as it does not use threads but can be used in HTML5).
- HTML5 exports now support additional flags (command line) to be passed via `startGame`.

@punto- this should allow to create an implementation for `iOS` as we discussed at GodotCon, let me know if you see there are still limitations.

Note: to enable debug for HTML5 native run, check the `deploy with remote debug` option in the `debug` menu.

### CODE REVIEW

**Comment by triptych** [comment]
Can't wait for this!

**Comment by Faless** [comment]
Rebased on current master

**Comment by akien-mga** [comment]
Thanks!

**Comment by Faless** [comment]
Getting the following error after this merge:
```
[ 98%] scons: done building targets.
TypeError: changed_since_last_build_node() missing 1 required positional argument: 'node':
  File "/usr/lib/scons/SCons/Script/Main.py", line 1376:
    _exec_main(parser, values)
  File "/usr/lib/scons/SCons/Script/Main.py", line 1339:
    _main(parser)
  File "/usr/lib/scons/SCons/Script/Main.py", line 1103:
    nodes = _build_targets(fs, options, targets, target_top)
  File "/usr/lib/scons/SCons/Script/Main.py", line 1313:
    jobs.run(postfunc = jobs_postfunc)
  File "/usr/lib/scons/SCons/Job.py", line 111:
    self.job.start()
  File "/usr/lib/scons/SCons/Job.py", line 423:
    task.executed()
  File "/usr/lib/scons/SCons/Script/Main.py", line 237:
    SCons.Taskmaster.OutOfDateTask.executed(self)
  File "/usr/lib/scons/SCons/Taskmaster.py", line 317:
    t.release_target_info()
  File "/usr/lib/scons/SCons/Node/FS.py", line 2980:
    self.changed(allowcache=True)
  File "/usr/lib/scons/SCons/Node/FS.py", line 3223:
    has_changed = SCons.Node.Node.changed(self, node)
  File "/usr/lib/scons/SCons/Node/__init__.py", line 1455:
    if _decider_map[child.changed_since_last_build](child, self, prev_ni):
```

Tested with both pip version:
```
SCons by Steven Knight et al.:
	script: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
	engine: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
```

and distro version:
```
SCons by Steven Knight et al.:
	script: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:16:53, by bdbaddog on hpmicrodog
	engine: v3.0.1.74b2c53bc42290e911b334a6b44f187da698a668, 2017/11/14 13:16:53, by bdbaddog on hpmicrodog

```

**Comment by akien-mga** [comment]
@Faless The backtrace is from your distro version (`/usr/lib/scons`), so make sure that the pip version is not using the wrong SCons lib from the distro.

**Pull request merged**
