### PR TITLE
Add shader_cache folder to .gitignore

### PR DESCRIPTION
**Pull request by madmiraal**
#49050 added shader caching, which creates a `shader_cache` folder, which is not being ignored by git.

This PR adds `shader_cache/` to `.gitignore`.

### CODE REVIEW

**Comment by Calinou** [comment]
Isn't this folder supposed to be created in `.godot/`? Additionally, shader cache writing could be disabled when running `--doctool`.

**Comment by akien-mga** [comment]
Yeah I confirm that this folder being created in the working directory is a bug, `.gitignore`-ing it is not the proper fix.

**Comment by akien-mga** [comment]
I opened #49392 for the bug.

**Comment by madmiraal** [comment]
It may not be the right solution, but since we already have `.import/` and `logs/` in `.gitignore`, it provides a good workaround until #49392 is fixed.
https://github.com/godotengine/godot/blob/6f8d5cff66416993856bdb01c83b999b84425fb0/.gitignore#L3
https://github.com/godotengine/godot/blob/6f8d5cff66416993856bdb01c83b999b84425fb0/.gitignore#L84

**Comment by akien-mga** [comment]
Fair enough :)

**Pull request closed without merging**
