### PR TITLE
CSGPolygon fix: fixes extra connection errors being thrown

### LINKED ISSUE #30229: CSGPolygon following a path throws errors if adding or removing points in path
Godot 3.1 

If you make a CSGPolygon follow Path and add points to the path after _ready() function it keeps throwing the following errors. 
Signal 'tree_exited' is already connected to given method '_path_exited' in that object.
  <C Source>     core/object.cpp:1488 @ connect()
and
Signal 'curve_changed' is already connected to given method '_path_changed' in that object.
  <C Source>     core/object.cpp:1488 @ connect()

Is there any reason for the signal to reconnect on path update?

To reproduce you can create the following scene:
image

### PR DESCRIPTION
**Pull request by Plopsiskopsis**
Should fix #30229.

### CODE REVIEW

**Comment by akien-mga** [comment]
The fix looks good, but could you amend the commit log to be more explicit? "CSGPolygon fix" doesn't tell us much about what is actually fixed in CSGPolygon.

**Comment by akien-mga** [comment]
It seems like you `git pull`-ed your remote branch after amending, so you now have 3 commits instead of 1. You should rebase to keep only the commit with the edited log, see [PR workflow](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by Plopsiskopsis** [comment]
@akien-mga I will check those things. Just swamped with other stuff for now.

**Comment by jitspoe** [comment]
CL looks like it got a little messed up.  Did you just remove the path_cache = NULL;?  I tried this, and it fixed a number of the errors, but I'm still getting the !is_inside_tree() error.

**Comment by Plopsiskopsis** [comment]
Yeah that was the only change I made. Just tested with my own original issue. Seems like there are still other issues related.

**Comment by jitspoe** [comment]
Cool.  Certainly seems like the correct change to make, and it fixes most of the errors.

**Comment by calumk** [comment]
This issue is still here in 3.2.4 rc3, seems like this should have been fixed a while back,
Is there at least a way to suppress these?

**Comment by Plopsiskopsis** [comment]
> 
> 
> This issue is still here in 3.2.4 rc3, seems like this should have been fixed a while back,
> Is there at least a way to suppress these?

Yeah I actually totally forgot this and havent gotten around to check the issues @jitspoe mentioned.

**Comment by akien-mga** [comment]
Superseded by #48232.

**Pull request closed without merging**
