### PR TITLE
Fix sphere-capsule collision logic

### LINKED ISSUE #70615: Physics 3D SAT solver produces incorrect collision normals between large sphere and capsule
### Godot version

4.0 beta 10

### System information

Windows 10, NVidia 2070, Vulkan Mobile

### Issue description

A human-sized (0.4 x 1.8 x 0.4) CapsuleShape3D on top of a large (50 x 50 x 50) SphereShape3D produces unstable normals when performing a move_and_collide down.

In discussions on the physics channel of the Godot Contributors Chat, the SAT solver isn't a good choice when the exact collision information can be solved analytically.

The problem with the SAT solver is that it ends up producing two collision points A and B on the two colliding shapes, and then the vector between them is used to build the normal. The problem is that A and B end up being extremely close (1e-4 distance), so normalizing the vector results in a large amplification of any numeric errors.

The current API for the ```_collision_<shape1>_<shape2>()``` functions can only report their findings via the ```_CollectorCallback``` API, and that only allows for providing the A and B points. Instead the collision functions should also have a means of providing exact analytic collision information if available.

### Steps to reproduce

Construct a scene consisting of a large 50m sphere with a capsule shape resting on top of it. Then perform a move_and_collide down and print the collision normal vector. 

### Minimal reproduction project

[SphereCapsuleCollision.zip](https://github.com/godotengine/godot/files/10306031/SphereCapsuleCollision.zip)

This demo walks a capsule around the top of a large sphere drawing the normal vector. The vector flickers between the correct normal and weird unstable normals:
image

### PR DESCRIPTION
**Pull request by Malcolmnixon**
This pull request fixes #70615 by only testing the one "correct" axis.

The original logic could end up testing 3 to 4 different separating axes; but only one of these would actually be the axis equivalent to the surface-normal. The SeparatorAxisTest class is not guaranteed to pick the axis corresponding to the  surface-normal. When the incorrect axis (not corresponding to the surface-normal) is used to build the contact information, the generated support points are not aligned and result in an inaccurate normal being presented to the user.

This pull request uses the capsule and sphere geometry information to generate a single separating axis - one that corresponds to the surface-normal, and guaranteed to separate the objects if they are separable. This one axis is tested, and so if a collision is detected the corresponding contact information and support points result in an accurate normal being reported to the user.

Note: The issue was originally reported on just sphere and capsule; however later comments indicated further shapes having collision issues. These will be tracked and resolved in different issues and pull requests.

### CODE REVIEW

**Comment by Malcolmnixon** [comment]
The collision test application (https://github.com/Malcolmnixon/PhysicsCollisionTest) was used to test sphere/capsule collisions in different orientations, and swapping which was static and which was the character. No issues were observed.
image

**Comment by Malcolmnixon** [comment]
I applied the same fix to capsule/capsule collisions - solve for the one correct collision axis analytically and perform a single SAT test on it.

**Comment by peastman** [comment]
It looks like we were both working on the same thing.  Here's my version of the sphere-capsule test.  It skips the axis test altogether and solves for the collision point directly.

```c++
template <bool withMargin>
static void _collision_sphere_capsule(const GodotShape3D *p_a, const Transform3D &p_transform_a, const GodotShape3D *p_b, const Transform3D &p_transform_b, _CollectorCallback *p_collector, real_t p_margin_a, real_t p_margin_b) {
	const GodotSphereShape3D *sphere_A = static_cast<const GodotSphereShape3D *>(p_a);
	const GodotCapsuleShape3D *capsule_B = static_cast<const GodotCapsuleShape3D *>(p_b);

	// Find the point on the internal part of the axis nearest to the center of the sphere.

	Vector3 center = p_transform_b.xform_inv(p_transform_a.origin);
	real_t half_height = (capsule_B->get_height() - capsule_B->get_radius()) / 2;
	Vector3 nearest(0, MIN(MAX(center.y, -half_height), half_height), 0);
	nearest = p_transform_b.xform(nearest);

	// See if it is inside the sphere.

	Vector3 delta = nearest - p_transform_a.origin;
	real_t length = delta.length();
	if (length > sphere_A->get_radius() + capsule_B->get_radius() + p_margin_a + p_margin_b) {
		return;
	}
	p_collector->collided = true;
	Vector3 axis;
	if (length == 0) {
		// If the sphere center is on the axis, choose an arbitrary direction away from the axis.
		axis = p_transform_b.basis.xform(Vector3(1, 0, 0));
	}
	else {
		axis = delta / length;
	}
	if (p_collector->callback) {
		Vector3 point_a = p_transform_a.origin + sphere_A->get_radius()*axis;
		Vector3 point_b = nearest - capsule_B->get_radius()*axis;
		p_collector->call(point_a, point_b);
	}
}
```

**Comment by Malcolmnixon** [comment]
My original attempt was along those lines, but I was unsure how the withMargin changes the detection and point offsets.

**Comment by peastman** [comment]
That's one of the reasons I preferred the direct approach.  If the collision handler invokes the callback directly, it can easily pass in the normal it has already calculated.  If the contacts get created indirectly through SeparatorAxisTest, I'm not sure how the normal would get communicated.

(Also, are you sure he's working on it?  From his post to the physics channel, I though he was suggesting that one of us add it.)

**Comment by Malcolmnixon** [comment]
Whups, sorry - it had collapsed your comment on his. 

The SeparatorAxisTest.test_axis() could use the axis given to it for the normal; but directly calling the callback would be more efficient than running the SAT projection code.

What is the intended behavior of the withMargin flag? 
 1. In SeparatorAxisTest.test_axis() it enables expanding the shadow margins so objects would appear to collide if their margins overlap.
 2. In SeparatorAxisTest.generate_contacts() it backs off the support points along the vector. I *think* its pushing the support points into their objects.

It seems like the support-point offsetting would ensure the points don't sit on top of each other, so a normal could be calculated.

**Comment by peastman** [comment]
I assumed it was to provide a safety margin to account for round-off error in identifying collisions.  But that was just a guess.  A related issue is these lines in the callback function:

https://github.com/godotengine/godot/blob/a75493091823020d858fabadbfa5994da0d658cb/servers/physics_3d/godot_space_3d.cpp#L451-L455

I found that even for the pairs that mostly work correctly, it still will occasionally miss an intersection because of those lines.  The collision function will correctly identify that the objects overlap, but the callback rejects them because the overlap depth is too small.

I'm not sure what the purpose of that test is.  Perhaps to ensure a normal can be computed like you suggested?  If so, that check could be skipped when a normal is provided.

**Comment by Malcolmnixon** [comment]
That min_allowed_depth appears to be 0.05 x margin (usually 0.001) or 0.00005. As such it seems like your p_point_A and p_point_B values are essentially identical.

One of the side-effects of SeparatorAxisTest.generate_contacts() offsetting p_point_A and p_point_B along the axis would be to move them apart. Unfortunately without further information about withMargin I'm not sure what else is expected/intended to happen with this offsetting.

Certainly if you're providing your own normal don't need to do the "contact_rel / len" calculation, but there just aren't enough comments in the code to explain the intended use of margin and its side-effects through the code.

**Comment by Malcolmnixon** [comment]
Ah, the withMargin is only set when margin_A or margin_B is non-zero. Specifically it lets the compiler build optimized versions of the collision functions. As such the developer can use ```if (withMargin)``` rather than ```if (margin_A != 0 && margin_B != 0)``` with zero cost because it's compiler deduced.

That still doesn't explain exactly what it's expected behavior is in these cases.

**Comment by peastman** [comment]
So that suggests the contact points should be computed like this?

```c++
Vector3 point_a = p_transform_a.origin + (sphere_A->get_radius()+p_margin_a) * axis;
Vector3 point_b = nearest - (capsule_B->get_radius()+p_margin_b) * axis;
```

**Comment by Malcolmnixon** [comment]
I believe you may need to flip the orientation if you want the outputs to match the existing behavior. Consider the existing code below...

This piece of code is from the sphere/sphere collider, and calculates the axis so it points in the direction from A to B:
https://github.com/godotengine/godot/blob/0daa86d70e7338506c37bee6b6e0c4aba7255d68/servers/physics_3d/godot_collision_solver_3d_sat.cpp#L774-L776

This piece of code offsets the A support-point in the "negative" direction - or pushes it closer towards A:
https://github.com/godotengine/godot/blob/0daa86d70e7338506c37bee6b6e0c4aba7255d68/servers/physics_3d/godot_collision_solver_3d_sat.cpp#L717-L721

This piece of code offsets the B support-point in the "positive" direction - or pushes it closer towards B:
https://github.com/godotengine/godot/blob/0daa86d70e7338506c37bee6b6e0c4aba7255d68/servers/physics_3d/godot_collision_solver_3d_sat.cpp#L731-L735

Your code pushes the collision points outside the objects, where-as the existing code pushes the collision points inside the objects. Embedding the points slightly inside the objects will result in the normal being calculated correctly, but unless it's corrected later it would result in collision points being offset.

**Comment by peastman** [comment]
I think it's the other way around.  `p_transform_a.origin - p_transform_b.origin` points from B to A, not from A to B.  So the offsets move the B point toward A and the A point toward B.

**Comment by Malcolmnixon** [comment]
Yup, you're right, I flipped that around. Given that your offset logic is correct; and I'm surprised the normal logic works at all. 
So the margin is just that. It inflates the objects slightly for collision testing, and the reported collision points are also pushed out by the same amount.

**Comment by Malcolmnixon** [comment]
Haha, I did an audit of the collision functions, and the axis being passed in to SeparatorAxisTest.test_axis() was about a 50/50 mix of A-to-B and B-to-A. I then found the magic in the test_axis function:
https://github.com/godotengine/godot/blob/0daa86d70e7338506c37bee6b6e0c4aba7255d68/servers/physics_3d/godot_collision_solver_3d_sat.cpp#L666-L676
So it's flipping it if necessary.

**Comment by Malcolmnixon** [comment]
I just pushed an update based on our discussions and tested with the https://github.com/Malcolmnixon/PhysicsCollisionTest project.

It creates a new analytic_sphere_collision function which performs the single sphere-sphere collision including margin calculations, handling coincident spheres, and calling the collector function. This one collision function can be used in _collision_sphere_sphere, _collision_sphere_capsule, and _collision_capsule_capsule. 

It doesn't have your changes to report the collision-normal, but it may be useful to review the approach.

**Comment by peastman** [comment]
Nice!  I wouldn't have thought to handle the capsule-capsule case that way.

**Comment by Malcolmnixon** [comment]
Once the machinery is in place to report analytic collisions correctly (including normals) we'll have to switch over to some of the other more interesting shapes. For example cylinder/cylinder and cylinder/capsule has some pretty big problems.

**Comment by peastman** [comment]
I'm working on debugging the cylinder-cylinder case right now.

**Comment by Malcolmnixon** [comment]
So we'll get this PR in as it improves the situation, then build on it to finish the analytic collisions.

**Review by rburing — APPROVED** [review]

**Comment by rburing** [comment]
Very nice approach! Let's continue with the remaining cases :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by peastman** [comment]
Thanks!

I think the next step is to add support for collision routines to provide accurate normals.  @Malcolmnixon shall I start on that or do you want to do it?

**Pull request merged**
