### PR TITLE
Updated "gamecontrollerdb.txt" to Include Mappings for New Gamepads

### LINKED ISSUE #65308: Xbox One Gamepad Incorrect Mapping on Linux using xone driver
### Godot version

v3.5.stable.official [991bb6ac7]
v4.0.alpha15.official [432b25d36]

### System information

Ubuntu 22.04, Xbox One Gamepad w/ Microsoft Wireless Receiver

### Issue description

The input map for the Xbox One wireless controller (using the Microsoft official wireless adapter and xone driver) is incorrect on Godot 3.5 / 4.0 Alpha 15 and Ubuntu 22.04 Linux.

https://github.com/medusalix/xone

For example, pressing the left trigger is detected as the right analog stick. You can see the image from Godot 4.0, where I have pressed the Right stick left/right, but it is shown as Right stick up/down (but in actuality, the real physical button is the Left trigger).

Godot4_Xbox

The gamepad is correctly detected and mapped normally on this site, Steam games also work fine:

https://gamepad-tester.com/

XboxOnePad

Though the xpadneo driver did work previously (at least with Godot 3.4), it doesn't properly support the new Microsoft wireless dongle or the newer firmware for the controller (which I already updated to). Also, I have many wireless devices, and I cannot use Bluetooth due to interference. Wired also does not work with the xone driver, so the issue does not appear to be related to wireless. The bug is specific to using the Xbox gamepad with the xone driver via the MS dongle.

### Steps to reproduce

Uninstall any other Xbox drivers you have on Linux and install this one:

https://github.com/medusalix/xone

Use any standard Xbox One gamepad controller and the newer model of the Microsoft wireless dongle.

https://www.amazon.com/Microsoft-Xbox-Wireless-Adapter-Windows-one/dp/B00ZB7W4QU

Load up Godot 3.5 or 4.0 Alpha 15 and set mappings for Right Analog Left and Right Analog Right to the name "left" and "right".

~~~
func _process(_delta):
	print(Input.get_axis("left", "right"))
~~~

See that they don't work when printing the axis from the project.

### Minimal reproduction project

[XboxMap.zip](https://github.com/godotengine/godot/files/9483652/XboxMap.zip)

### PR DESCRIPTION
**Pull request by cybereality**
Updated "gamecontrollerdb.txt" from https://github.com/gabomdq/SDL_GameControllerDB to latest to include mappings for newer gamepads, including Xbox One / Series X, Nintendo Switch / Pro, Steam Deck, and 8BitDo.

*Bugsquad edit:*
- Fixes #65308

### CODE REVIEW

**Comment by akien-mga** [comment]
Does this fix #65308?

**Comment by cybereality** [comment]
Yes, I should have mentioned, this fixes https://github.com/godotengine/godot/issues/65308 and I verified it works. This PR is needed on both Godot 4.0 and 3.5. Originally I thought it was a Linux issue exclusively, but the updated database should be useful on all platforms.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
