### PR TITLE
Use get_base_dir() instead of substr()

### PR DESCRIPTION
**Pull request by NilsIrl**

### CODE REVIEW

**Comment by akien-mga** [comment]
The code change looks good, though I wonder why we're getting the base dir of the base dir when duplicating a directory.

If `to_duplicate` is a directory, shouldn't `to_duplicate.path` point to a directory and thus `base_dir` point to its parent directory? If so I'd expect `base_dir.plus_file(new_name)` to be sufficient.
Note that it's not an issue with your code change, I'm just writing down my thoughts from checking this code snippet.

**Comment by NilsIrl** [comment]
> The code change looks good, though I wonder why we're getting the base dir of the base dir when duplicating a directory.
> 
> If `to_duplicate` is a directory, shouldn't `to_duplicate.path` point to a directory and thus `base_dir` point to its parent directory? If so I'd expect `base_dir.plus_file(new_name)` to be sufficient.
> Note that it's not an issue with your code change, I'm just writing down my thoughts from checking this code snippet.

I'm a ~~bit~~ very confused as well.

**Comment by groud** [comment]
Yeah, this check looks pretty pointless. It's apparently a quite old code.
Could you try replacing the test case by something like `String new_path = base_path.plus_file(new_name)` ?

**Comment by akien-mga** [comment]
Actually the check is useful, because `get_base_dir()` is arguably broken when the path ends with a `/` (which seems to be the same here).
```
print("hello/world/".get_base_dir())  # hello/world
print("hello/world".get_base_dir())  # hello
```
IMO it should return `hello/world` in both cases, but fixing that might be a compat breakage and outside the scope of this issue.

This code here is wonky though, as if the `new_path` happened not to have a trailing `/`, it wouldn't work. So it's properly better to strip the trailing slash if any before getting the `get_base_dir()`, and then use that.

**Comment by akien-mga** [comment]
There's a lot of hacky code to workaround this feature of `get_base_dir()` in the filesystem dock BTW, like:
```
                        if (!fpath.ends_with("/")) {
                                fpath = fpath.get_base_dir();
                        }
```

**Comment by groud** [comment]
> There's a lot of hacky code to workaround this feature of get_base_dir() in the filesystem dock BTW

Yeah, I have seen that when implementing support for favorites files in the filesystem dock. The thing is that there are no easy way to know if a file is a folder or not, so I used a `/` at the end to figure that out.
But maybe all of this should be reworked to use a `File` instead (it has to stay compatible with Variants though).

**Comment by akien-mga** [comment]
Superseded by #30312.

**Pull request closed without merging**
