### PR TITLE
Fix type of `notification_func`

### PR DESCRIPTION
**Pull request by Sauermann**
fix comment https://github.com/godotengine/godot/pull/78634#discussion_r1335673625
cc @dsnopek

### CODE REVIEW

**Review by Gallilus — APPROVED** [review]

**Comment by Gallilus** [comment]
Pulled the Gun too early with my approval. My issue seems solved by initializing to `nullptr`.

```
struct {
		GDExtensionScriptInstanceNotification notification_func = nullptr;
	} deprecated_native_info;
```

**Comment by dsnopek** [comment]
@Gallilus Ack, I think you're right! We're only initializing that value if you call `script_instance_create`, but not if you call `script_instance_create2`. Good catch!

@Sauermann If you don't mind adding the `= nullptr`, we can fix two problems at once :-)

**Comment by Sauermann** [comment]
Of course. done.

**Review by akien-mga — APPROVED** [review]

**Review by dsnopek — APPROVED** [review]
Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
