### PR TITLE
new version does not overwrite editor_settings

### PR DESCRIPTION
**Pull request by SuperUserNameMan**
Each new version of godot will have its own editor_settings.xml file.

Advantages :
- customized script editor colors won't be lost at each new version
- allow users to manage different projects with different versions of 
  godot (each version has its own project list)
- make comparing different version of godot to track bugs easier

### CODE REVIEW

**Comment by TheoXD** [comment]
doesn't seem like a good idea to me, so I have to recreate the old settings all over again when switching to a new version? If you make it fetch settings from previous versions it could find - that would be fine.

**Comment by NateWardawg** [comment]
I like this change except that I agree with Theo, it really should import the old settings first.

As a side note, most software packages only do this per major version, but since this is an Open Source software version 2.0 may not be too radically different from the 1.x before it, and/or it may take longer than the typical 18-24 month before it is released. In that light this change does seem to make sense overall.

Of course, that's just my 2 cents.

**Comment by SuperUserNameMan** [comment]
@TheoXD : anyway, and so far, the `editor_settings.xml` was purely and simply overwritten by newer versions. You've already lost your settings many times before.
And each time you'll run an ancient version to track bugs, you'll lose everything again and again.

With this simple patch, instead of losing everything, you still have a backup of the ancient version.

Indeed, I agree with both of you that importing older setting would be a lot better. But before I or someone else implement it, this simple patch could be helpful. (more especially if you customized the script editor colors !!!!!!!!!)
As for

**Comment by akien-mga** [comment]
I think this change would make sense indeed, I often find myself losing all my imported projects listing when switching from 1.1 to 2.0. So splitting the settings by version would indeed be a meaningful change, and it can later on be improved so that the settings from the previous versions are imported if there are no existing settings for the current version.

**Comment by DriNeo** [comment]
To avoid this issue I tried to set the "editor setting.xml" path into the editor settings, but it doesn't work for me. I'm on Windows.
An interesting solution could be to make this possible. What's your opinion about that ?

**Comment by akien-mga** [comment]
Would fix #1689.

**Comment by akien-mga** [comment]
The main question is how compatible are editor settings of version N with version N+1. Apparently between 1.1 and 2.0 there is no real compatibility, you always have to reconfigure from scratch after having opened the other version.

Will it be the same between 2.0 and 2.1? Or can we expect some compatibility?

**Comment by akien-mga** [comment]
@reduz It would be nice to have this implemented somehow for 2.0.


The current PR is quite simple, as it will just hardcode the version in the filename:
- it means that the 2.0 editor would ignore the existing editor_settings.xml that people might have from 1.1 and just create an empty config. It's actually not an issue as the 1.1 settings are in any case not compatible with 2.0, so currently loading 2.0-beta over the 1.1 settings will override them anyway.
- it makes it possible to continue using 1.1 next to 2.0 while porting one's game for example, without losing all the config each time. More interesting maybe, it makes it possible to keep 2.0 around as stable version while playing with 2.1-alpha, each using its own config file so one won't hesitate to test new stuff in 2.1-alpha.
- it however means that one would not keep the 2.0 config when moving to 2.1, unless we implement a system to copy the 2.0 config file as the 2.1 config file if it exists. But that means somehow hardcoding which earlier versions should be considered for this. Another possibility would be to make 2.0 and future versions write both editor_settings.2.0.stable.xml *and* editor_settings.xml, and if the version-specific file is not available, it would be copied over from editor_settings.xml.

**Comment by akien-mga** [comment]
Ping. @reduz Any idea on this topic?

**Comment by nunodonato** [comment]
If I am not mistaken thats how Blender does it. When a new version is released the config is a new file, but it allows you to import from the previous version.

we could also do that, if a previous config file exists, copy it to the new one.

I guess what would be missing is a way to know how versioning of Godot would work regarding the editor settings compatibility. does 2.1 break 2.0? or just major versions? what happens if some change in 2.1 breaks it?

**Comment by akien-mga** [comment]
I think this won't be merged as is, and actually new versions of Godot are meant to stay compatible with the config of previous versions AFAIK, so keep the same filename is sensible. Compatibility was broken between 1.1 and 2.0, but it should not be broken further in the 2.x branch.

As for keeping different versions with their own config for test purposes, since 2.0.1 you can use Godot in self-contained mode by adding a ``._sc_`` file in the folder of the executable, see http://docs.godotengine.org/en/latest/reference/packaging_godot.html#self-contained-mode

**Pull request closed without merging**
