### PR TITLE
[3.x] Fix various GCC 13 warnings

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes occurrences of `-Wtype-limits`, `-Wmaybe-uninitialized`, `-Wduplicated-branches`.

Includes `3.x` version of #85500.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
LGTM, makes sense

**Comment by akien-mga** [comment]
Added some more warning fixes.

This doesn't yet allow building `3.x` with GCC 13.2.0 warning free, as I ran into this more complex one:
```
In file included from drivers/gles2/rasterizer_canvas_gles2.h:34,
                 from drivers/gles2/rasterizer_canvas_gles2.cpp:31:
In member function 'RasterizerCanvasBatcher<T, T_STORAGE>::Batch* RasterizerCanvasBatcher<T, T_STORAGE>::_batch_request_new(bool) [with T = RasterizerCanvasGLES2; T_STORAGE = RasterizerStorageGLES2]',
    inlined from 'void RasterizerCanvasBatcher<T, T_STORAGE>::_prefill_default_batch(FillState&, int, const RasterizerCanvas::Item&) [with T = RasterizerCanvasGLES2; T_STORAGE = RasterizerStorageGLES2]' at ./drivers/gles_common/rasterizer_canvas_batcher.h:891:48,
    inlined from 'void RasterizerCanvasBatcher<T, T_STORAGE>::_prefill_default_batch(FillState&, int, const RasterizerCanvas::Item&) [with T = RasterizerCanvasGLES2; T_STORAGE = RasterizerStorageGLES2]' at ./drivers/gles_common/rasterizer_canvas_batcher.h:844:1:
./drivers/gles_common/rasterizer_canvas_batcher.h:689:31: error: 'void* memset(void*, int, size_t)' offset [0, 29] is out of the bounds [0, 0] [-Werror=array-bounds=]
  689 |                         memset(batch, 0, sizeof(Batch));
      |                         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In member function 'RasterizerCanvasBatcher<T, T_STORAGE>::Batch* RasterizerCanvasBatcher<T, T_STORAGE>::_batch_request_new(bool) [with T = RasterizerCanvasGLES2; T_STORAGE = RasterizerStorageGLES2]',
    inlined from 'void RasterizerCanvasBatcher<T, T_STORAGE>::_prefill_default_batch(FillState&, int, const RasterizerCanvas::Item&) [with T = RasterizerCanvasGLES2; T_STORAGE = RasterizerStorageGLES2]' at ./drivers/gles_common/rasterizer_canvas_batcher.h:917:47,
    inlined from 'void RasterizerCanvasBatcher<T, T_STORAGE>::_prefill_default_batch(FillState&, int, const RasterizerCanvas::Item&) [with T = RasterizerCanvasGLES2; T_STORAGE = RasterizerStorageGLES2]' at ./drivers/gles_common/rasterizer_canvas_batcher.h:844:1:
./drivers/gles_common/rasterizer_canvas_batcher.h:689:31: error: 'void* memset(void*, int, size_t)' offset [0, 29] is out of the bounds [0, 0] [-Werror=array-bounds=]
  689 |                         memset(batch, 0, sizeof(Batch));
      |                         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

GCC seems to disagree with @lawnjelly's comment:
```
			// this should always succeed after growing
			batch = bdata.batches.request();
			RAST_DEBUG_ASSERT(batch);
```
(that `RAST_DEBUG_ASSERT` is a no-op in release builds, and `batch` is used later without checking if it's nullptr)

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Ok, done. Aside from the warning in `RasterizerCanvasBatcher`, the `3.x` branch now compiles warning free with both `tools=yes target=release_debug dev=yes` and `tools=no target=release dev=yes`.

Might be some other warnings in some other tools/target/optimization configs but that's a good pass already.

**Comment by lawnjelly** [comment]
> GCC seems to disagree with @lawnjelly's comment:
> // this should always succeed after growing

My comment should probably more accurately be:
`// this  should always succeed after growing UNLESS OUT OF MEMORY AND WORLD IS ENDING`

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.4.

**Pull request merged**
