### PR TITLE
Fix broken variant call of Vector3.snapped

### PR DESCRIPTION
**Pull request by clktmr**

### CODE REVIEW

**Comment by vnen** [comment]
This is broken since the [beginning of time](https://github.com/godotengine/godot/blame/45438e9918d421b244bfd7776a30e67dc7f2d3e3/core/variant_call.cpp#L1488)...

**Comment by hpvb** [comment]
Is there any way that the previous behavior did something sensible (if undocumented?) this makes me a little nervous for cherry picking into 3.0

**Comment by vnen** [comment]
@hpvb in my tests it just returned the same vector.

**Comment by akien-mga** [comment]
> This is broken since the beginning of time...

Actually no, only since June 2017: 44ecfb02

**Comment by hpvb** [comment]
As this changes api/abi I don't think this should go into 3.0, it may break existing gdnative modules

**Pull request merged**
