### PR TITLE
[3.x] Show tooltips even when paused or time_scale is 0

### PR DESCRIPTION
**Pull request by KoBeWi**
Backport of #43693

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Comment by golddotasksquestions** [comment]
I just tested this and it does not work as I would expect.

Even if the whole scene tree is paused, including the control, the tool tip still shows up. I would expect the tooltip to only show up on the Control nodes which are processed (pause mode: Process), or inherit the pause mode from a processing Node (pause mode: Inherit).

However currently the tooltip shows up regardless of any pause setting. 
This gives the user the same lack of control as hiding all tooltips by default.

image

Imagine you have a pause menu and you spawn it on top of your game with your game UI. The game and it's UI should be paused, but the pause menu should be processed. With this current implementation, the tooltips of the game UI would still show up. Even though all the user only would want the processed Controls to have tooltips.

Another issue I just noticed is how the tooltips appear at some offset location if there is a translated Camera2D in the scene. Not sure if this is a new issue or not since it is the first time I notice it:

https://user-images.githubusercontent.com/47016402/143624207-d49dd5e2-5ab3-4100-a4bd-3a481f518463.mp4

**Comment by KoBeWi** [comment]
@golddotasksquestions 
You can open an issue about tooltip pause. For pass/stop too if there isn't one already. The camera bug is fixed in 4.0 (#11732)

**Comment by golddotasksquestions** [comment]
@KoBeWi 
I opened separate issues here:
https://github.com/godotengine/godot/issues/55428
https://github.com/godotengine/godot/issues/55430

**Pull request merged**
