### PR TITLE
Added the smart word wrap property to preview label in batch rename dialog

### LINKED ISSUE #52074: [3.x] Batch rename window size not updating correctly
### Godot version

3.4 5ce734c073

### System information

Linux

### Issue description

When in batch rename window preview text doesn't fit in the window, the window background doesn't scale properly. 
Moving the window updates it.

Same thing on 3.3.3, but on master it's fine (because it's a separate window there?).

image

### Steps to reproduce

Open batch rename window.
Make so the preview text is so long that it doesn't fit.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by nsrCodes**
closes #52074

https://user-images.githubusercontent.com/57226514/133397837-c9bff3f6-6c46-4f8d-b426-dd7aaa584bec.mp4

### CODE REVIEW

**Comment by nsrCodes** [comment]
The mentioned bug is fixed but this raises another problem that the height of the label does not shrink after the label is resized (*when each new line is added*). 
I was expecting this to be covered in another issue because it has to do with the `minimum_size_changed` function in [control.cpp](https://github.com/godotengine/godot/blob/173c0f8737ff60c433303e3023a0852faa3cb352/scene/gui/control.cpp#L2382-L2385). *AFAIU*, it does not resize the node if its children are still inside, which leaves the empty gaps

**Demo of the new issue:**

https://user-images.githubusercontent.com/57226514/133399222-62697ad6-6bc4-41d8-ad2d-a811131656d2.mp4

**Comment by nsrCodes** [comment]
> The mentioned bug is fixed but this raises another problem that the height of the label does not shrink after the label is resized (when each new line is added).
This bug already exists in master. You can check the same by just toggling the advanced options, it does not resize correctly.

**Comment by LoipesMas** [comment]
Here's how it looks on current master:

https://user-images.githubusercontent.com/46327403/133820087-ae0d9284-8070-4405-ad7a-37fb3306c278.mp4

The original issue (text getting out of the window) isn't there. It's only on 3.x branch.
I'm not sure if cherry-picking this PR for 3.x would fix that.

Maybe make a separate PR for 3.x to fix size not updating and another one for master to set the autowrap (or just use this PR for that, just changing the title).

**Comment by nsrCodes** [comment]
I have found the reason of the bug in master but currently can't find a way to fix it.
Before #37317 the dialog was implemented using `control` and there if we set the value of `size.y` to 0 (which is done while toggling the advanced option button), the size computed for the re-render was equal to the minimum size required to fit the children of that dialog (*follow the `get_combined_minimum_size` function in [`_update_minimum_size`](https://github.com/godotengine/godot/blob/ed3742c4a7e5819399ac92a0e312723b23fc1d9d/scene/gui/control.cpp#L290)*).

But after that PR, dialogs are now implemented using `window` where the [`_update_window_size`](https://github.com/godotengine/godot/blob/051c2c8a3a96dd094a7c585b79bb90a2c81bd0f6/scene/main/window.cpp#L520-L528) does not let the window shrink back. This is because along with the minimum size of the window, it also tracks the dynamically updated window size and always chooses the max of the two.

**Review by bruvzg — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
