### PR TITLE
Improved FileSystem dock "Instance" option

### LINKED ISSUE #5795: Instancing with right-click instances all the scenes
Tested on Godot 2.1 beta, Windows 10 64 bits

Repro:
[InstanceDoingMultiple.zip](https://github.com/godotengine/godot/files/370461/InstanceDoingMultiple.zip)
right-click any of the available scenes in the FileExplorer, and select "instance". Notice the editor will instance all the scenes in the current folder at once (including the opened scene itself, which causes an error).

Expected:
Instance only the selected scene under the selected parent.

### PR DESCRIPTION
**Pull request by ghost**
Now the instance operation create just one `UndoRedo` action, instead of creating one for every scene.
- For this i had created a new private function to instance scenes, `SceneTreeDock::_perform_instance_scene`. And the behavior of `SceneTreeDock::instance_scenes`(The old code is now in `_perform_instance_scene`) to work like the `SceneTreeDock::instance` function, but you can provide the parent node.

### CODE REVIEW

**Comment by akien-mga** [comment]
@TheHX Looks like @reduz missed your PR and he pushed a fix for #5795 himself (the exact same one as yours). Could you rebase the first commit away, as the second one is still relevant?

**Comment by reduz** [comment]
sorry, missed this PR. I also for reference renamed the file to filesystem_dock, since it has been a long time from the time it used to be only for scenes.

**Comment by reduz** [comment]
Ah Akien made me note that you implemented instancing into a single action, I'll reopen this but can you fix it to the new filename? (it's now in filesystem_dock.cpp)

**Comment by TheHX** [comment]
@reduz @akien-mga, removed the first commit and rebased the second.

**Pull request merged**
