### PR TITLE
Button focus hovering

### PR DESCRIPTION
**Pull request by bvbfan**
Signed-off-by: Anthony Fieroni bvbfan@abv.bg

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you squash the two commits together? In the PR workflow we prefer merging commits that work by themselves, the fixups done by the contributors before merging should be squashed unless particularly relevant for the git history.

**Comment by akien-mga** [comment]
Looks like something fishy happened during rebase, you now have 4 commits instead of 1 :)
A `git rebase` might help.

**Comment by bvbfan** [comment]
git rebase -i HEAD~2
pick (main)
squash (correction)
git pull
git push
https://github.com/bvbfan/godot/commit/d55127396c970448e685c417a615169582ae4a66
2 parents f3bea0d + 4c0fb9f commit d55127396c970448e685c417a615169582ae4a66
How can be done without merging?

**Comment by akien-mga** [comment]
You should have used instead of:
```
git pull
git push
```
the history-rewriting variant:
```
git pull --rebase
git push --force
```
This is of course not to do in a main public branch, but for a PR-intended branch it's a fine workflow.

**Comment by bvbfan** [comment]
Yes, i mean for the branch. So it's can be correct?

**Comment by bvbfan** [comment]
Fixed.

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
