### PR TITLE
Added support of Python 3 in make_header.py

### LINKED ISSUE #19043: Script make_header.py run with error in Python 3.
**Godot 3.0.2
OS: Windows 7 x64, Ubuntu Linux 18.10 (x64)**

Script make_header.py for making theme_data.h file run with error in Python 3 
and support only Python 2.x.

Steps to reproduce:

**Python 2.x**
1. Change directory to {godot_source_folder}/scene/resources/default_theme
2. Delete file "theme_data.h"
3. Run 
`python make_header.py` in console
4. Success

**Python 3.x**
1. Change directory to {godot_source_folder}/scene/resources/default_theme
2. Delete file "theme_data.h"
3. Run 
`python3 make_header.py` in console
3. Error
pybug

### PR DESCRIPTION
**Pull request by Mintormo**
Script make_header.py run with error in Python 3.
I modified a code to support Python 2.x and Python 3.x
Fix #19043

### CODE REVIEW

**Comment by Mintormo** [comment]
I think yes. It says that both versions of Python are supported. Hm, maybe to make two version of this file? For Python 2 and 3 separately?

**Comment by Mintormo** [comment]
While it is supported.. http://docs.godotengine.org/en/3.0/development/compiling/compiling_for_windows.html

**Comment by aaronfranke** [comment]
@mhilbrunner On most systems `python` is hard-coded to `python2`. Arch is an exception to this.

**Comment by mhilbrunner** [comment]
Which should still work, as this should still be compatible with Python 2, right?

**Pull request merged**
