### PR TITLE
do not return zero with minus-sign within range value, fixes #3221

### LINKED ISSUE #3221: Range subclasses (Slider, Spinbox...) can return -0
As mentioned in #3091, apparently due to a rounding error, nodes like ?Slider and SpinBox can return -0 if the min value is negative and rounded values is enabled.
This is a minor issue, since Godot recognizes (0 == -0) as true, but when converting to string, the sign will be preserved, which can lead to some minor awkwardness that would have to be addressed manually.

### PR DESCRIPTION
**Pull request by cozybuild**

### CODE REVIEW

**Comment by reduz** [comment]
looks good, I would add a simple comment of why this line exists like
"//avoid returning -0

**Comment by akien-mga** [comment]
> looks good, I would add a simple comment of why this line exists like
"//avoid returning -0

+1

**Comment by akien-mga** [comment]
Looks good. Could you try merging the two commits into one? Using the git command-line, it would be:
- ```git rebase -i HEAD~2```
- in the editor that shows up, replace the word "pick" before commit 3b11dc8 by "fixup", save and close the editor
- it should then merge commit 3b11dc8 into its parent commit, ```git log``` should show only one commit
- if the log is fine, ```git push -f origin 3221_range-minus-zero-fix``` to update this PR.

**Comment by d3v0x** [comment]
Thank you for the nice tutorial @akien-mga :wink: :yellow_heart: 

Updated.

**Comment by akien-mga** [comment]
Perfect :)

**Comment by rayosdev** [comment]
This is still a problem in 2.14 stable when using float( )

**Pull request merged**
