### PR TITLE
Fix lambda parsing continuing on subsequent lines

### LINKED ISSUE #73273: Parser error with lambda assignment after if statement
### Godot version

4.0.rc1

### System information

windows 10

### Issue description

When assigning a lambda to a variable right after an if statement, the parser seems to understand that a ternary expression is happening when in fact it is not.

image

### Steps to reproduce

Put the code bellow on a script on an empty project
```gdscript
func test():
	var v
	if true: v = (func(): test())
	if true: v = (func(): test())
	if true: v = (func(): test())

	if true: v = func(): test()
	if true: v = func(): test()
```

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by kinami-imai**
This PR fixes #73273.

The issue in #73273 was related to the fact that the statement in the lambda expression gets parsed and calls `end_statement`. This leads to an issue, because the `end_statement` function consumes all new line tokens, which means the assignment statement will not get to consume these new lines, and thus will continue parsing the line.

The fix I introduce changes the `parse_precedence` function, to not only return if the lambda has ended _and_ the previous statement was a lambda, but return in any case. This means the assignment statement would also terminate its parsing even without the new line.  Once the statement is parsed, `lambda_ended` will be set back to false, so this should not have any effects further than the scope of the lambda and the assignment.

I have written a couple of integration tests, to ensure that this method does not break in a couple of cases I could think of where lambdas could be used.

Shortcomings: One case I discovered during my testing I was not able to find a fix for. If a lambda is declared, statementd can be appended to the line, and they will be executed as if they had a new line between them and the lambda. I think this is a lower priority, as this is invalid code that is interpreted as correct. I would wait with fixing this until the tokenizer changes in #76211 are merged.

Example code:
```
var v
v=func(): print(1) print(2)  # Should have thrown a parser error! Instead gets executed and prints 2
v.call()
```
Output:
```
2
1
```

### CODE REVIEW

**Comment by dalexeev** [comment]
These tests should be in the parser folder.

**Comment by kinami-imai** [comment]
> These tests should be in the parser folder.

Good point! I force-pushed the tests to the correct place!

**Comment by akien-mga** [comment]
We'd typically add the tests in the same commit that fixes the bug, so could you squash the commits together? And possibly amend the commit to be a bit more detailed, like this PR's title is.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
