### PR TITLE
Fix for error 1088

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TheoXD** [comment]
Wait, what? PR request to a stable branch? If I understand the idea with stable releases is that stable must never be updated, people must count on that functionality and not encounter more bugs (like for example 645a038 broke compiling for VisualStudio users)

**Comment by Murii** [comment]
No,no! I`m sorry! Yesterday I wanted to submit something but since I`m not that good using Github I made this...And now I dont know how to delete it :))

**Comment by adolson** [comment]
Click the Close Pull Request button.

**Comment by MannyC** [comment]
@Murii watch out for backquotes ( \` ) in your comments too as they get interpreted as markdown.  Use apostrophes instead ( ' ).  

Also, you can refer to issues in comments, commit notes and subject lines by using a # with a number afterwards( eg: #1088 ).  They automatically get linked an a back reference is put in the target issue.

**Pull request closed without merging**
