### PR TITLE
Add external texture support

### PR DESCRIPTION
**Pull request by m4gr3d**
Starting a draft to discuss the proper way to integrate support for external texture in Godot 4.x.

This is feature that's [forward-ported from Godot 3.x](https://github.com/godotengine/godot/pull/36342) and is key to enable support for texture that can be _painted_ by the target platform (see the original PR for target use-cases).

As mentioned in https://github.com/godotengine/godot/pull/36342#pullrequestreview-369375100, this was punted for the 4.x release due to GLES reimplementation and the need to figure out how this applies to Vulkan.

This draft aims to restart the conversation in order to properly integrate it in Godot 4.x 

Addresses https://github.com/godotengine/godot/issues/65778
Addresses https://github.com/godotengine/godot-proposals/discussions/4902

### CODE REVIEW

**Comment by m4gr3d** [comment]
cc @maunvz

**Comment by m4gr3d** [comment]
@paddy-exe FYI, this is required to support ARCore in Godot

**Comment by dsnopek** [comment]
How does this relate to textures created via `TextureStorage::texture_create_external()` (in the OpenGL renderer)? That function is being used for OpenXR (on OpenGL) and WebXR.

Or, if this doesn't relate to that (like, if it's a totally different thing) then we should probably rename one of them, because having two unrelated types of textures both called "external" is going to be confusing :-)

**Comment by m4gr3d** [comment]
> How does this relate to textures created via `TextureStorage::texture_create_external()` (in the OpenGL renderer)? That function is being used for OpenXR (on OpenGL) and WebXR.
> 
> Or, if this doesn't relate to that (like, if it's a totally different thing) then we should probably rename one of them, because having two unrelated types of textures both called "external" is going to be confusing :-)

@dsnopek they're indeed different things; see this comment that goes on the difference between the two: https://github.com/godotengine/godot/issues/65778#issuecomment-1249351066

Renaming is made complex by the fact the one I'm referring to is [part of the OpenGL spec](https://registry.khronos.org/OpenGL/extensions/OES/OES_EGL_image_external.txt), so arguably the current Godot one should be renamed to be consistent with external references, but I don't have a strong preferences either way so long as it's clear which one we're referring to.

**Comment by m4gr3d** [comment]
As mentioned in this [StackOverlfow thread](https://stackoverflow.com/a/43550804), this may be supported in Vulkan using the [VK_ANDROID_external_memory_android_hardware_buffer extension](https://registry.khronos.org/vulkan/specs/1.1-extensions/html/vkspec.html#VK_ANDROID_external_memory_android_hardware_buffer).

**Comment by dsnopek** [comment]
> they're indeed different things; see this comment that goes on the difference between the two: [#65778 (comment)](https://github.com/godotengine/godot/issues/65778#issuecomment-1249351066)
> 
> Renaming is made complex by the fact the one I'm referring to is [part of the OpenGL spec](https://registry.khronos.org/OpenGL/extensions/OES/OES_EGL_image_external.txt), so arguably the current Godot one should be renamed to be consistent with external references, but I don't have a strong preferences either way so long as it's clear which one we're referring to.

I think it'd be fine to rename the existing `TextureStorage::texture_create_external()` to something else - it's not exposed publicly anywhere, and only used in those two places. I don't have any brilliant naming ideas, though. :-)

Maybe:

- `TextureStorage::texture_create_foreign()`
- `TextureStorage::texture_create_reference()` -- the idea being it "references" a texture created elsewhere
- `TextureStorage::texture_create_remote()`
- `TextureStorage::texture_create_third_party()`
- `TextureStorage::texture_create_independent()`

Naming is hard :-)

**Comment by BastiaanOlij** [comment]
cc @clayjohn , you should have a look at this too.

**Comment by pritish-thub** [comment]
Is this android specific or will it work on iOS as well?

**Comment by m4gr3d** [comment]
> Is this android specific or will it work on iOS as well?

It's not Android specific in theory, but it uses OpenGLES and Vulkan extensions which iOS doesn't (officially) support, so there would need to be investigation on whether this is available to iOS through the available compatibility APIs.

cc @BastiaanOlij @clayjohn

**Comment by dsnopek** [comment]
Superseded by https://github.com/godotengine/godot/pull/96982

**Pull request closed without merging**
