### PR TITLE
Make gdscripts support Unicode identifiers

### LINKED ISSUE #24785: Add support for Unicode characters in GDScript identifiers
**Godot version:**

3.0.6

**OS/device including version:**

windows

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by zj1d**
Make gdscripts support Unicode identifiers
e.g. Chinese Japanese Korean emoji
This is friendly for multilingual developers
Fixes: #24785, https://github.com/godotengine/godot-proposals/issues/916
#916

### CODE REVIEW

**Comment by fire** [comment]
Is there a proposal for this? Why would we want this?

https://github.com/godotengine/godot-proposals/

**Comment by nobodxbodon** [comment]
@fire the proposal is [Allow Unicode characters in GDScript identifiers](https://github.com/godotengine/godot-proposals/issues/916)

**Comment by fire** [comment]
The proposal mentions following UAX#31 standard as path for adding Unicode identitiers. Will need to read more on it.

**Comment by Calinou** [comment]
@zj1d Out of curiosity, why did you add a new workflow to GitHub Actions?

**Comment by zj1d** [comment]
Sorry, I made a mistake. I don't know how to cancel it

**Comment by vnen** [comment]
I already voiced my concerns about this on https://github.com/godotengine/godot-proposals/issues/916#issuecomment-795765777.

I would like to hear more opinions on this. While this solution is the easy way out, I'm not convinced it won't cause troubles for users which can be quite hard to find in some circumstances. People already have trouble with indentation when copy-pasting code, this would lead to worse issues, I believe.

But if more people are on board with the "let me use anything I want, users can deal with potential problems" solution, then fine.

**Comment by vnen** [comment]
Superseded by #71676

**Pull request closed without merging**
