### PR TITLE
Fix missing whitepoint for ACES tonemapping

### LINKED ISSUE #19163: ACES Tonemapping does not use whitepoint
Godot version: **3.0.2**

The ACES tonemapping operator **does not utilize the whitepoint value** (property "White" in editor). [Here's the part from the combine-shader's source code including a corrected version](https://gist.github.com/CptPotato/c5ec4b773659274afbab629e048d3b20).

In addition to that, I want to point out that the different tonemapping operators are not implemented very consistently (ACES applies clamping to [0-1] range, the others don't), aswell as the **whitepoint limit being too low** for all tonemapping functions as hinted in issue #18181 (the editor limits the value to 16.0 maximum).

There are a few additional things that I think could/should be changed at this shader but I decided to create separate issues for each of them.

### PR DESCRIPTION
**Pull request by CptPotato**
Adds the missing use of the whitepoint value in the ACES tonemapping operator (fixes #19163).

I initially intended to combine this with a PR regarding #19361 but decided to do it separately since it's a really quick change and part of the 3.1 milestone. ~I also did not touch the formatting of the file, though I think it needs to be made more consistent and readable/structured (I might do this when I give the issue above a shot).~

Lastly, note that this is my first PR so let me know if I did anything wrong.

### CODE REVIEW

**Comment by CptPotato** [comment]
Not sure why there is a duplicate commit in there 😕

**Comment by reduz** [comment]
Thanks a ton for taking the time to submit a PR for this, I am covered by other tasks right now and we are still short on contributors who can work on the rendering area. Code seems fine, if @akien-mga approves style it should be fine to merge.

**Comment by Calinou** [comment]
> Not sure why there is a duplicate commit in there confused

Look into [rebasing](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) the latest commits so that you can meld all three into a single commit.

**Comment by CptPotato** [comment]
ugh, let me try and fix this commit stuff first
sorry for the trouble

**Comment by mhilbrunner** [comment]
Happy to see another rendering contributor! Welcome :) And thanks.

Would you mind inserting spaces between the arguments?

I.e. change `tonemap_aces(color.rgb,white)` to `tonemap_aces(color.rgb, white)` (as well as the other instance). Just a minor nitpick :)

**Comment by CptPotato** [comment]
I wanted to give #19361 a shot in the next few weeks and implement two additional, physically based modes for glow. So I planned to reformat the whole file in a consistent way (spacing, casing, {}, etc.) aswell as restructure some things into separate functions when I get to that.

But if you wan't to I can do the formatting of the file in this PR. I might need a couple of days, though.

**Comment by CptPotato** [comment]
So I did reformat the whole file today. So far it looks like everything still works as it should.

**Comment by mhilbrunner** [comment]
Wow, thanks, thats way more than what I expected :) Yeah, we're better keeping this in two seperate commits for the formatting messyness - but way better now, thank you.

Looking forward to your next PR, thanks for doing this!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.

**Pull request merged**
