### PR TITLE
Remove unavailable property binding `reset_on_save` from Skeleton3D

### LINKED ISSUE #90224: Skeleton3D `modifier_reset_on_save` has invalid setter/getter bindings
### Tested versions

- Reproducible in: 4.3.dev 79de2eaae
- Not reproducible in: 4.2.1.stable

### System information

Godot v4.3.dev (79de2eaae) - Fedora Linux 39 (KDE Plasma) - Wayland - GLES3 (Compatibility) - NVIDIA GeForce RTX 4090 (nvidia; 545.29.06) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

https://github.com/godotengine/godot/commit/04dd299cbac614c0ff2306b8d3cd60dcd86abd8e introduced a property with setter/getter methods that don't exist anywhere:

https://github.com/godotengine/godot/blob/79de2eaae7fb3bb8f13031ac2ec9b19128b6f471/scene/3d/skeleton_3d.cpp#L1058

This causes an error on startup:

```
ERROR: Invalid setter 'Skeleton3D::set_modifier_reset_on_save_enabled' for property 'modifier_reset_on_save'.
   at: add_property (./core/object/class_db.cpp:1310)
```

cc @TokageItLab 

### Steps to reproduce

- Open the editor or project manager and look at the console output.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by TokageItLab**
Sorry, Fixes #90224.

### CODE REVIEW

**Review by fire — APPROVED** [review]
Tested

**Comment by catboy-catfish** [comment]
Do you know if reset_on_save is used anywhere in Skeleton3D?

**Comment by TokageItLab** [comment]
As noted in the issue in the description, it just forgot to remove it during the final adjustment of the SkeletonModifier implementation PR, and it was never availed in practice on master.

**Comment by catboy-catfish** [comment]
I'm gonna test out this PR now. Fire tested it but didn't say anything about it being successful or not. I might report back to do that

**Comment by akien-mga** [comment]
Thanks!

**Comment by catboy-catfish** [comment]
Given how it was just now merged into master this looks pretty good

**Pull request merged**
