### PR TITLE
Fixed loading from pck

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
Moved the code to have a correct exec_path when loading data from the pck

### CODE REVIEW

**Comment by akien-mga** [comment]
That will also override the existing logic that runs when you do have a correct `exec_path`.

Could you be more explicit on what the actual problem is? This has been working for all supported platforms for 5 years, so while I know you're working on console ports, we do need some transparency on the motives for changing code which will impact all the currently working platforms.

**Comment by jeronimo-schreyer** [comment]
I'll fix the condition flow. Currently, there are some cases where exec_path is requested before it is set. Some platforms address this issue by implementing their own get_executable_path (like Windows)

**Comment by aaronfranke** [comment]
@jeronimo-schreyer Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by aaronfranke** [comment]
This PR has been abandoned by its author, no response for over 2 months. Closing.

**Pull request closed without merging**
