### PR TITLE
Fix Vector3 slerp method by normalizing cross product

### LINKED ISSUE #27825: Vector3.slerp gives error in many situations and returns 0,0,0
**Godot version:** 3.1

**OS/device including version:** Win 10

**Issue description:**

When trying to use slerp in some (most?) circumstances, the console shows the error:

`Condition ' !p_axis.is_normalized() ' is true`

The function returns Vector3(0,0,0)

As far as I can tell, the implementation assumes that the cross-product of two normalized vectors is normalized, but that doesn't seem to be the case.

**Steps to reproduce:**

```
	var v1 = Vector3(0.5, 1, 0.5).normalized()
	var v2 = Vector3.DOWN
	var s = v1.slerp(v2, 0.5)
	print(s)
```

**Notes:** I admit I'm not a vector expert. If I have some fundamental misunderstanding of how slerp works, let me know.

### PR DESCRIPTION
**Pull request by Toshiwoz**
This pull request is to solve issue https://github.com/godotengine/godot/issues/27825.

*Bugsquad edit:* Fixes #27825.

### CODE REVIEW

**Comment by Chaosus** [comment]
May it break compatibility ? If so its better to be tagged for 4.0 version

**Comment by Toshiwoz** [comment]
No, I don't think so.
This PR just fix an issue with normalization of the cross product of 2 unit vectors, I think that it was implied that the result is always a unit vector, but it isn't (apart from when they are perpedicular).

This is the function changed:
https://github.com/godotengine/godot/blob/93845572d576133401d4f29b9bda1c90d261d577/core/math/vector3.h#L221-L228

That, on the last line calls the rotated function, the definition of rotated is here:
https://github.com/godotengine/godot/blob/93845572d576133401d4f29b9bda1c90d261d577/core/math/vector3.cpp#L35-L45

Then rotated uses Basis, and basis at a certain point does this check:
https://github.com/godotengine/godot/blob/93845572d576133401d4f29b9bda1c90d261d577/core/math/basis.cpp#L810-L815

But, as the axis is the cross product of 2 unit vectors, the check fails and return this error:
`core/math/basis.cpp:813 - Condition ' !p_axis.is_normalized() ' is true.`

**Comment by akien-mga** [comment]
Thanks!

**Comment by Toshiwoz** [comment]
May I suggest to cherry pick this one for an eventual 3.1.2 release?
This very simple code change is only a fix. 99% of users is not even using this function.

My project (and most likely only mine) relies quite a bit on this function (I had to implement it in GDSCript meanwhile, most likely reducing performance).

**Comment by Toshiwoz** [comment]
Dang, I realized that there is another change needed:
https://github.com/godotengine/godot/blob/93845572d576133401d4f29b9bda1c90d261d577/core/math/vector3.h#L222-L224

The math check is not needed anymore, please someone correct me if I'm wrong, but this checks that the current vector is normalized before performing the slerp, but this is not needed (rather unwanted), as far as I understand how this works.

So, in order to fix this, should I create another pull request?

**Comment by Toshiwoz** [comment]
Thanks for the cherrypick @akien-mga !

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
