### PR TITLE
Option to rename input actions

### LINKED ISSUE #517: Renaming actions in the InputMap
All I want is to not have to delete and remake inputs if I want them to be called something different...please?

### PR DESCRIPTION
**Pull request by neikeq**
Closes #517

Since it used the same dialog as editor layouts, I renamed it to EditorNameDialog to make it more generic.

Screenshot

### CODE REVIEW

**Comment by neikeq** [comment]
Rebased to fix an undo error.

**Comment by akien-mga** [comment]
It's working great, apart from the default input (ui_accept, etc.). Those can be renamed but they are not written to engine.cfg, so the changes are not kept after closing the editor (and likely the change is only cosmetic, the built-in names are probably still used in-game).

It might not be trivial to make it possible to override those though.

**Comment by neikeq** [comment]
Is there currently a clean way to check that? These are added on the fly here: https://github.com/godotengine/godot/blob/master/core/globals.cpp#L1408
I could put them in a list or vector after these lines, if you give me green light.

**Comment by neikeq** [comment]
Just did what I mentioned in the last comment. Is it fine?

**Comment by akien-mga** [comment]
It's working great :)

Regarding the input presets, apparently when you change their default settings, the values are properly saved in engine.cfg, e.g.:
```
ui_accept=[key(Return), key(Enter), jbutton(0, 0), key(R)]
```
On the other hand deleting preset input actions does not work, as they will be automatically recreated. So now that there is a List of input presets, maybe their delete button (for the main action, not for the bindings) could be disabled too?

**Comment by akien-mga** [comment]
Regarding what I wrote above, it would just be a further enhancement, so let's already merge this once, I'm sure @neikeq will make another PR if my suggestion was good :)

**Pull request merged**
