### PR TITLE
Make NavigationAgent `target_location` a property

### PR DESCRIPTION
**Pull request by timothyqiu**
This PR turns the existing `set_target_location()` and `get_target_location()` into a property.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Seems fine to me.

CC @smix8

**Comment by lawnjelly** [comment]
Seems fine, but I'm not clear on what the advantages / intention are of making this a property?

There is no need to save it. Perhaps showing it in the inspector when remote debugging is potentially useful. What does the `PROPERTY_USAGE_NO_EDITOR` flag do BTW?

**Comment by timothyqiu** [comment]
> I'm not clear on what the advantages / intention are of making this a property?

When I was converting a project from the old navigation to NavigationAgent, I changed my old `target_location = xxx` to `navigation_agent.target_location = xxx` and it turned out to be an error. So I wondered why it's not available as a property.

I think we've been using properties in preference to getters/setters, and have only chosen not to provide them when one or the other is missing, or when the behavior is too complex to use like a property.

`target_location` is simply accessing an internal variable and triggering a pathfinding on update (like clearing a cache).

So my intention is... why not :P

> What does the `PROPERTY_USAGE_NO_EDITOR` flag do BTW?

It makes the Inspector ignore the property. I think it's always set it in code.

**Comment by lawnjelly** [comment]
Agree with @smix8 I'm not sure this is a good idea.

> I think we've been using properties in preference to getters/setters

This is imo an example of the misnaming often used in Godot and chinese whispers (or whatever the politically correct term for this is :slightly_smiling_face: ).

In other codebases, the function names `set` and `get` are often reserved for cheap operations, that are literally wrappers to setting and getting a variable. In Godot we often end up using these names for functions that really are not cheap. This might be referred to as a "code smell".

Case in point, `set_target_location`also triggers a pathfind, which is an expensive operation. The function name starting with `set` makes it easy to assume it is cheap, therefore suitable for a property.

But we now have a situation where editor code might change this property during loading / saving / undoing etc code, where it is now triggering a boat load of pathfinding calculations which may or may not be appropriate, and may cause bugs for things being accessed outside of the normal lifecycle.

**Comment by timothyqiu** [comment]
IIUC, calling `set_target_location()` itself won't trigger/block anything. The update only happens when the path is needed, i.e. calls like `get_next_location()` and `is_navigation_finished()`. So I think it's cheap and works like updating `Label.text` which also triggers a redraw and min size update.

https://github.com/godotengine/godot/blob/fffdbb38e390a11d0dc0672ce1755148deee3e90/scene/3d/navigation_agent_3d.cpp#L322-L325

https://github.com/godotengine/godot/blob/fffdbb38e390a11d0dc0672ce1755148deee3e90/scene/3d/navigation_agent_3d.cpp#L464-L469

**Comment by smix8** [comment]
We should remove the pathfinding trigger from the `set_target_location()` and other functions and replace them with dirty flags as the user needs to call `get_next_location()` anyway for the navigationagent to work correctly. This is also a constant source of user errors when users e.g. forget to use `get_next_location()` because after `set_target_location()` the navigationagent already has a path so users think they can now use it and wonder why the path index is not updating correctly. This way we could also remove the blocking as users can change their properties as many times as they want and it does not trigger any sideeffects.

**Comment by timothyqiu** [comment]
@smix8 I think it's already working like this, the only difference is it's currently using an empty navigation path as the dirty flag.

**Comment by timothyqiu** [comment]
I mean, `set_target_location()` is only updating its member varibles. How would this block? 

https://github.com/godotengine/godot/blob/fffdbb38e390a11d0dc0672ce1755148deee3e90/scene/3d/navigation_agent_3d.cpp#L322-L325

https://github.com/godotengine/godot/blob/fffdbb38e390a11d0dc0672ce1755148deee3e90/scene/3d/navigation_agent_3d.cpp#L464-L469

**Comment by smix8** [comment]
@timothyqiu You are correct, I was mixing things with get_final_location() that has the problem.

**Comment by timothyqiu** [comment]
@smix8 :grin: So I guess it's okay to make `target_location` a property?

**Comment by smix8** [comment]
> Not sure how this works as a property. Is this property visible to users in the doc or inspector? It shouldn't.

Also what jelly mentioned, how does this property work with all the other godot stuff that comes with properties? E.g. node storage, save/load or editor script resets with a runtime scene. I want to avoid another potential hard to debug bug case added to the endless list of bug cases of the navigationagent.

**Comment by timothyqiu** [comment]
`PROPERTY_USAGE_NO_EDITOR` hides the property in the Inspector. But changes made by editor scripts/plugins will be stored in the tscn file.

I can change it to `PROPERTY_USAGE_NONE` if you think it's better to not save any changes.

**Comment by lawnjelly** [comment]
The other point is that by creating a property we are implicitly placing some limitations on how it can be used internally, should the internal design change, we may end up having to work around this decision. It is all well and good to say "it works ok at the moment", but anything like this concerning the API places potential future limitations.

That's not to say it might be a bad thing eventually, but given how new the navigation is, and how many changes are in the pipeline imminently, it might not be a bad idea to stick to the minimum amount of API (at least for a few months).

**Comment by timothyqiu** [comment]
FYI, I recently saw that `CharacterBody3D` also uses `PROPERTY_USAGE_NO_EDITOR` for its `velocity` property. I think the usage is equivalent.

https://github.com/godotengine/godot/blob/61021c08f80856f8d99dfbe9fd3d338ef5f41999/scene/3d/physics_body_3d.cpp#L1996

**Review by smix8 — APPROVED** [review]

**Comment by smix8** [comment]
Maybe move it under the "Pathfinding" Group to make it clear it is a pathfinding property even if it only cosmetic with the no-editor flag.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
