### PR TITLE
Fix Render Info

### PR DESCRIPTION
**Pull request by reduz**
* Fixed and redone the process to obtain render information from a Viewport
* Some stats, such as material changes are too difficult to guess on Vulkan, were removed.
* Separated visible and shadow stats, which causes confusion.
* Texture, buffer and general video memory can be queried now.
* Fixed the performance metrics too.

image

Feedback welcome on how to display the above info better ^

### CODE REVIEW

**Comment by Calinou** [comment]
On the screenshot, the number of vertices drawn *in shadow* is greater than the general vertex count. If this actually is the case, I suggest displaying it as "(+15956446 in shadow)" instead.

**Comment by BastiaanOlij** [comment]
The `in shadow` I read as counts within that other count which makes it weird they are higher numbers. I think this should be `in shadowpass`.

**Comment by lyuma** [comment]
I would like to request that the current vertex count be renamed to "index count" (if index is confusing, it could be divided by 3 and named "triangle count"):
This disparity is evidenced in the code, where it assigns indices to the "vertices in frame" render info.
```
p_render_data->render_info->info[RS::VIEWPORT_RENDER_INFO_TYPE_VISIBLE][RS::VIEWPORT_RENDER_INFO_VERTICES_IN_FRAME] += indices;
```

I would also like to request that, if know, the true vertex count be measured by summing up the vertices of each object rendered. The true vertex count can be helpful for optimizing vertex shader invocation, skinning passes or other per-vertex overhead.

**Comment by lawnjelly** [comment]
Also wish to support @lyuma 's suggestion (beyond an uptick). This has caused misunderstandings many times.

**Comment by Mobs1024** [comment]
LOD generation is good

https://user-images.githubusercontent.com/17591539/124349236-d5c7a200-dbf6-11eb-9585-72579f20304f.mp4

shadows are too very expensive draw calls `93` bad optimization need optimization in `LightmapGI`

https://user-images.githubusercontent.com/17591539/124349272-f2fc7080-dbf6-11eb-9824-f8eb91775c44.mp4

configure global illumination Baked / Dynamic
image

the result is nothing diminishing the shadow in the draw calls

https://user-images.githubusercontent.com/17591539/124349457-be3ce900-dbf7-11eb-96a3-4e46b6fbbfd3.mp4

**Comment by Zireael07** [comment]
GI has nothing to do with shadows @Mobs1024

**Comment by Mobs1024** [comment]
@reduz `OmniLight3D` and `SpotLight3D` shadow are zero if movement shows in shadows

https://user-images.githubusercontent.com/17591539/124351600-fba77380-dc03-11eb-9057-7c3ebfecf5c9.mp4

**Comment by reduz** [comment]
"Indices" is probably confusing, so maybe I should change the counter to be "primitives"?

**Comment by reduz** [comment]
> @reduz OmniLight3D and SpotLight3D shadow are zero if movement shows in shadows

@Mobs1024 This is a feature, not a bug, if the shadow does not change it's not redrawn hence you see 0.

I have the feeling this information may be too confusing to users, who may think this ia bug, so maybe showing stuff in shadows should be avoided.

**Comment by lawnjelly** [comment]
> I have the feeling this information may be too confusing to users, who may think this ia bug, so maybe showing stuff in shadows should be avoided.

You mean not show shadow statistics at all? If we lump them all together, users will be more confused, and if we don't include shadow statistics, the information becomes much more limited in value as we are only telling half the story. Another option is a beginner / advanced selector in the editor options which controls such options (as we have for the project settings), if the concern is overwhelming beginners.

**Comment by reduz** [comment]
@lawnjelly to be honest I don't think shadow information is that useful. If you really want to see it, maybe an add-on could show it (I did not remove the API to obtain it). You can already see in the new GPU profiler how much it takes to render shadows anyway so if you have a bottleneck there it will be obvious.

**Comment by reduz** [comment]
I changed it to look like this:
image

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
