### PR TITLE
Fix JSON parsing issue with trailing content.

### LINKED ISSUE #19611: JsonParseResult return error=0 in some invalid JSON strings
**Godot version:**

3.1 dev compiled last week

**OS/device including version:**

Win 7,8 10 and probably all systems

**Issue description:**

**Using JSON class to import JSON from invalid JSON file can return a valid JSON text.**
Example:

**File:**   test.json
**Content:**   true, false, [1,2,3],

In every JSON validator the mistake is finded behind first "true"  (is expected to reach EOF after true and not ","):

https://codebeautify.org/jsonvalidator

Code to test in Godot:

```
var JsonText = "true, false, [1,2,3],"
var JsonError = JSON.parse(JsonText).error
if JsonError == 0:
  print ("This should be an error", but Json is imported in this way:")
  print (JSON.parse(JsonText).result)
 #This print´s "true", Godot ignores that there is text after true.
```

### PR DESCRIPTION
**Pull request by pbrunet**
Fix #19611

### CODE REVIEW

**Comment by akien-mga** [comment]
It's not related to this PR, just a side note: the email you currently use to author your commits is not linked to your GitHub accounnt, which is why your commits don't appear attributed to @pbrunet. It's fine, but if you want to fix that, you can add your git email as secondary email in your GitHub profile.

**Comment by pbrunet** [comment]
Thanks for the report, I added this email as secondary email.

**Comment by akien-mga** [comment]
See @reduz's comment on https://github.com/godotengine/godot/issues/19611#issuecomment-465570341

**Comment by akien-mga** [comment]
Could you squash the commits together?

**Comment by pbrunet** [comment]
Ok, It is done

**Comment by reduz** [comment]
Please check my approach on #19611, actual code is fine and your PR will most likely cause a crash if it runs short of the expression.

**Comment by pbrunet** [comment]
I think it is what I did here : https://github.com/godotengine/godot/pull/25977/files#diff-8af5ca245defe71d8cbfbaf99eead7aeR475

Did I missed something?

**Comment by aaronfranke** [comment]
Is this still desired? This PR might be superseded by #37238

**Comment by aaronfranke** [comment]
This PR has not received any new commits for over a year, and may be superseded, so closing.

**Pull request closed without merging**
