### PR TITLE
BasisU: Update to 1.50.0 and add HDR support

### PR DESCRIPTION
**Pull request by BlueCube3310**
Updates BasisUniversal to 1.50.0 and adds support for transcoding to BC6/ASTC HDR 4x4 RGB.
If neither format is supported, the image gets decompressed to RGB9E5.

TODO:
- [x] Apply previous patches,
- [x] Use Godot's tinyexr,
- [x] Remove unused dependencies (qoi, tinydds)
- [x] Tune the settings to minimize the compression time,
- [x] Clean up the code,
- [x] Make the multiples-of-4 padding code account for RGBAF,
- [x] Do quality comparisons

Quality:
Image: https://polyhaven.com/a/empty_play_room

| BasisU vs. Betsy (diff) | Basisu vs. Original (diff) |
|----------------------|-------------------------|
| vsbetsy | basisu |

### CODE REVIEW

**Comment by BlueCube3310** [comment]
I think this is more or less complete, on an optimized Windows editor build it adds ~250kb, this should be minimized by #85321. 

The only big issue are the compression times, on an optimized build it takes ~17s to compress an 8k HDRi without mipmaps with the default settings. The latest push uses the 'fastest' preset which I haven't tested yet, so that may have improved a bit.

**Comment by fire** [comment]
17 seconds sounds like our previous times without gpu compute, not sure how much we can squeeze to make it faster.

**Comment by BlueCube3310** [comment]
CVTT would take about 60-70s for the same task, so this is about 3x faster (though obviously still not desired)

**Comment by fire** [comment]
There are three missing items on the list left to go!

- [ ] Remove unused dependencies (qoi, tinydds)
- [ ] Tune the settings to minimize the compression time,
- [ ] Do quality comparisons

**Comment by BlueCube3310** [comment]
I don't think the performance can get any better (without SSE4/AVX), since the lowest settings are already used. 
Quality-wise, it's comparable to Betsy. 
Transcoding to ASTC should be nearly instant (BasisU HDR is just ASTC), so slowdowns are not expected on mobile. BC6 is slightly slower, though not really noticeable on Desktop hardware.

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

Optimized, stripped Linux x86_64 editor binary size is about 300 KB larger (this is with https://github.com/godotengine/godot/pull/85321 taken into account). Release export template is 86 KB larger.

## Benchmark

Performance on LDR texture imports seems to be roughly identical. Here's an exercept on a [few 4K textures](https://polyhaven.com/a/blue_metal_plate):

### Before

```
EditorFileSystem: "res://blue_metal_plate_disp_4k.jpg" import took 439 ms.
EditorFileSystem: "res://blue_metal_plate_diff_4k.jpg" import took 1094 ms.
EditorFileSystem: "res://blue_metal_plate_arm_4k.jpg" import took 1438 ms.
EditorFileSystem: "res://blue_metal_plate_nor_gl_4k.jpg" import took 1495 ms.
```

### After

```
BasisU: Encoding a 4096x4096 image with 12 mipmaps took 371 ms.
EditorFileSystem: "res://blue_metal_plate_disp_4k.jpg" import took 449 ms.

BasisU: Encoding a 4096x4096 image with 12 mipmaps took 776 ms.
EditorFileSystem: "res://blue_metal_plate_diff_4k.jpg" import took 1157 ms.

BasisU: Encoding a 4096x4096 image with 12 mipmaps took 828 ms.
EditorFileSystem: "res://blue_metal_plate_arm_4k.jpg" import took 1256 ms.

BasisU: Encoding a 4096x4096 image with 12 mipmaps took 1193 ms.
EditorFileSystem: "res://blue_metal_plate_nor_gl_4k.jpg" import took 1503 ms.
```

### Quality

*Click to view at full size. Texture size was limited to 1024 on import to make the difference more noticeable.*

Lossless | VRAM Compressed Low Quality
-|-
Screenshot_20241004_203403 png webp | Screenshot_20241004_203409 png webp

VRAM Compressed High Quality | Basis Universal
-|-
Screenshot_20241004_203416 png webp | Screenshot_20241004_203423 png webp

**Review by akien-mga — APPROVED** [review]
Looks good to me, just missing this diff for vendoring instructions:
```diff
diff --git a/thirdparty/README.md b/thirdparty/README.md
index c9a0cefb05..bbf4bcecb7 100644
--- a/thirdparty/README.md
+++ b/thirdparty/README.md
@@ -64,7 +64,8 @@ Files extracted from upstream source:
 
 Files extracted from upstream source:
 
-- `encoder/` and `transcoder/` folders, minus `jpgd.{cpp,h}`
+- `encoder/` and `transcoder/` folders, with the following files removed from `encoder`:
+  `jpgd.{cpp,h}`, `3rdparty/{qoi.h,tinydds.h,tinyexr.cpp,tinyexr.h}`
 - `LICENSE`
 
 Applied upstream PR https://github.com/BinomialLLC/basis_universal/pull/344 to
```

Regarding QOI support, we have #91263 so if it gets approved we could consider re-enabling support for that, if it's deemed useful.

**Comment by BlueCube3310** [comment]
> Regarding QOI support, we have #91263 so if it gets approved we could consider re-enabling support for that, if it's deemed useful.

BasisU's image loaders are never used anyway, nor are they exposed to the user; this would only simplify the patches.

**Review by clayjohn — APPROVED** [review]
Changes to modules/basis_universal look good to me!

**Review by fire — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
