### PR TITLE
Added async and await as C# keywords.

### PR DESCRIPTION
**Pull request by NathanWarden**

### CODE REVIEW

**Comment by neikeq** [comment]
These are not reserved keywords, so better add the comment `// Contextual keywords` at the end, followed by [the list](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/#contextual-keywords) of contextual keywords.

**Comment by NathanWarden** [comment]
Ahhh, yep, missed that :) Do you want me to go ahead and go through the list and make sure the rest are all in there?

Actually, I'll go ahead and add them and if you think we should remove any I'll go ahead and remove them.

**Comment by neikeq** [comment]
I've compared both and found the following:
- `forech` typo. Should be `foreach`.
- `void` should go before `volatile` (not like that really matters, but it does 😝 )
- Missing the following contextual keywords: `alias`, `when`, `nameof`
- These contextual keyword shouldn't be there?: `by`, `equals`, `in`, `on`. This is weird, these are not in the contextual keywords list, but they are [listed here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/query-keywords). Maybe we should add another category. `in` is already a reserved keyword though.

Sorry for annoying you.

**Comment by NathanWarden** [comment]
@neikeq Thanks for going through those. For that last section I believe those particular contextual keywords `by`, `equals`, etc are typically for linq queries.

If you take a look at Query #3 you'll see the `by` keyword.
https://docs.microsoft.com/en-us/dotnet/csharp/linq/write-linq-queries

I could break those out into their own section in the array, but the only words that are unique are `on`,  `equals`, `by` and the rest of the query words are used in other contexts. IE. `where` is used in queries and also in Generics constraints.

Let me know if you think this warrants a new section (and might come across as slightly confusing), so for now I'll just keep them in the regular array. Let me know :)

**Review by neikeq — APPROVED** [review]
It's fine to include those as well because this is only for syntax highlighting. Not obligatory though.

**Comment by hpvb** [comment]
Is this safe to go into 3.0? Does this affect current uses of those words as non-keywords in potentially existing C# code?

**Comment by vnen** [comment]
@hpvb AFAIK this is only used by the editor for highlighting, it doesn't do anything special. We can't control what's a keyword or not in C#.

**Comment by neikeq** [comment]
Yep, this is just for syntax highlighting in the built-in editor.

**Comment by hpvb** [comment]
ok, going in 3.0.1!

**Pull request merged**
