### PR TITLE
Fixes for some issues with enums in GDScript

### LINKED ISSUE #53835: GDScript test suite build failure with `tools=no target=release tests=yes`
### Godot version

4.0.dev (e2bfb27)

### System information

Linux, Mageia 9 x86_64

### Issue description

When building with `tools=no target=release tests=yes`, the GDScript test suite fails building:

```
modules/gdscript/tests/gdscript_test_runner.cpp: In constructor 'GDScriptTests::GDScriptTestRunner::GDScriptTestRunner(const String&, bool)':
modules/gdscript/tests/gdscript_test_runner.cpp:139:34: error: 'GDScriptWarning' has not been declared
  139 |         for (int i = 0; i < (int)GDScriptWarning::WARNING_MAX; i++) {
      |                                  ^~~~~~~~~~~~~~~
modules/gdscript/tests/gdscript_test_runner.cpp:140:34: error: 'GDScriptWarning' has not been declared
  140 |                 String warning = GDScriptWarning::get_name_from_code((GDScriptWarning::Code)i).to_lower();
      |                                  ^~~~~~~~~~~~~~~
modules/gdscript/tests/gdscript_test_runner.cpp:140:71: error: 'GDScriptWarning' has not been declared
  140 |                 String warning = GDScriptWarning::get_name_from_code((GDScriptWarning::Code)i).to_lower();
      |                                                                       ^~~~~~~~~~~~~~~
modules/gdscript/tests/gdscript_test_runner.cpp: In member function 'GDScriptTests::GDScriptTest::TestResult GDScriptTests::GDScriptTest::execute_test_code(bool)':
modules/gdscript/tests/gdscript_test_runner.cpp:473:20: error: 'GDScriptWarning' does not name a type; did you mean 'GDScriptParser'?
  473 |         for (const GDScriptWarning &E : parser.get_warnings()) {
      |                    ^~~~~~~~~~~~~~~
      |                    GDScriptParser
modules/gdscript/tests/gdscript_test_runner.cpp:483:10: error: expected ';' before 'result'
  483 |         }
      |          ^
      |          ;
  484 |         result.output += warning_string.as_string();
      |         ~~~~~~
modules/gdscript/tests/gdscript_test_runner.cpp:484:23: error: could not convert 'result.GDScriptTests::GDScriptTest::TestResult::output.String::operator+=(StringBuilder::as_string() const())' from 'String' to 'bool'
  484 |         result.output += warning_string.as_string();
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       |
      |                       String
modules/gdscript/tests/gdscript_test_runner.cpp:487:26: error: expected primary-expression before 'compiler'
  487 |         GDScriptCompiler compiler;
      |                          ^~~~~~~~
modules/gdscript/tests/gdscript_test_runner.cpp:487:25: error: expected ')' before 'compiler'
  487 |         GDScriptCompiler compiler;
      |                         ^~~~~~~~~
      |                         )
modules/gdscript/tests/gdscript_test_runner.cpp:473:13: note: to match this '('
  473 |         for (const GDScriptWarning &E : parser.get_warnings()) {
      |             ^
modules/gdscript/tests/gdscript_test_runner.cpp:487:26: error: 'compiler' was not declared in this scope
  487 |         GDScriptCompiler compiler;
      |                          ^~~~~~~~
modules/gdscript/tests/gdscript_test_runner.cpp:488:15: error: 'compiler' was not declared in this scope
  488 |         err = compiler.compile(&parser, script.ptr(), false);
      |               ^~~~~~~~
```

That's not surprising as the tests are mostly intended for the editor build (`tools=yes target=release_debug/debug`), but it could make sense to keep supporting building tests for release templates too since some can be affected by optimizations.

So we likely just need to sprinkle some `TOOLS_ENABLED` and/or `DEBUG_ENABLED` in the relevant test code, or outright disable the GDScript test runner if it can't be used in a template.

### Steps to reproduce

- `scons p=linux tools=no target=release tests=yes`

### Minimal reproduction project

_No response_

### LINKED ISSUE #54877: Calling methods on Enum types in gdscript results in debugger errors
### Godot version

v4.0.dev.20211108.official.596865366

### System information

Win 10 x64

### Issue description

When calling underlying dictionary methods like **.keys()** or **.size()** on enum types, the debugger reports error on scene launch:
```
get_function_signature: Native class res://NodeWithEnum.gd.MyEnum used in script doesn't exist or isn't exposed.
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   modules/gdscript/gdscript_analyzer.cpp:3601 @ get_function_signature()
```
image
image

### Steps to reproduce

1. Create an enum type
2. Call a method like .size() or .keys() on the type
3. Observe debugger reporting numerous errors

### Minimal reproduction project

[4.0_EnumMethodErrors.zip](https://github.com/godotengine/godot/files/7520312/4.0_EnumMethodErrors.zip)

### LINKED ISSUE #55491: When iterating over `enum` goes to infinite loop
### Godot version

v4.0.dev.custom_build [125c5eabc]

### System information

Linux, x11, nvidia

### Issue description

```gdscript
extends Node2D

enum Enum {
  ONE,
  TWO
}

func _ready():
  for each in Enum:
    print(each)
```

```txt
--- Debugging process started ---
Godot Engine v4.0.dev.custom_build.125c5eabc - https://godotengine.org
Vulkan API 1.2.200 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2070 SUPER
 
0
1
2
3
4
5
6
7
8
...
257357
257358
257359
257360
257361
257362
257363
25[...]
  [output overflow, print less text!]
--- Debugging process stopped ---
```
Causes infinite loop and iterates over integers (previously printed `KEY` and not `VALUE`, I prefer this but there should be way to say what is iterated over `ENUM.keys()` and `ENUM.values()`)

On Godot 3.4 same script would print out:
```txt
ONE
TWO
```

### Steps to reproduce

- Create any scene
- Put script to root
- Copy example script to *.gd
- Run 

### Minimal reproduction project

[EnumLoopInfinity.zip](https://github.com/godotengine/godot/files/7628164/EnumLoopInfinity.zip)

### LINKED ISSUE #56878: GDScript 2.0: Enum comparison causes `Invalid operands` error when function is using the enum as type hint
### Godot version

v4.0.dev.custom_build [846c14eee]

### System information

Linux Mint - Vulkan API 1.2.131 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Comparing a value against an enum-value only works if the function does not use that enum as a type hint.

See the example code-snippet for a better understanding of the issue.

Error message:
```
Parser Error: Invalid operands "Test (enum)" and "One (enum value)" for "==" operator.
```

This bug must have been introduced in the last one or two days, because this code was working before.

### Steps to reproduce

Copy this script into any project and see that you can't run it.
If you use the line above the non-working function instead, everything works as expected

```gdscript
extends Node

enum Test {
	One,
	Two
}

# func do(value): # Does work
func do(value : Test):  # Does NOT work
	if value == Test.One:
		print(value)
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by vnen**
This solves some inconsistencies when using enum as a type in GDScript. With this they'll be recognized as integers or Dictionaries when appropriate.

This also allows tests to run in release builds. A special comment `#debug-only` can be used as the first line of tests that shouldn't run on release builds (mostly those that test or depend on debug checks). Warnings will be ignored on comparisons since they aren't available on release.

Fix #53835
Fix #54877
Fix #55491
Fix #56878

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @cdemirer @Piet-G @trollodel @SaracenOne who have been debugging and fixing GDScript issues lately.

**Comment by trollodel** [comment]
I didn't debug enums specifically, but I think it would be nice to test specifically for the case described in #56878 where you have a typed variable (or parameter) compared to an enum value. I found them several times in my tests. 
I see that enum values are now gone from the parser (IIUC), but just in case.

**Comment by Piet-G** [comment]
This sounds great, indeed Enums inconsistently being treated as INT and sometimes as DICT was a cause of a bunch of engine issues. 

This should supercede. #57464

**Comment by vnen** [comment]
> I didn't debug enums specifically, but I think it would be nice to test specifically for the case described in #56878 where you have a typed variable (or parameter) compared to an enum value

I've tested that particular case and it works as intended with this patch. We can also add cases in the test suite to make sure they are (and remain) correct.

**Review by akien-mga — APPROVED** [review]

**Comment by trollodel** [comment]
> > I didn't debug enums specifically, but I think it would be nice to test specifically for the case described in #56878 where you have a typed variable (or parameter) compared to an enum value
> 
> I've tested that particular case and it works as intended with this patch. We can also add cases in the test suite to make sure they are (and remain) correct.

Yeah, I intended automated test in the GDScript test suite, not manual testing (my bad for not specifying it). I imagine that you tested that specific scenario, giving that you have marked that issue as fixed.

**Comment by nabfrew** [comment]
This script used to work in alpha 1, now in alpha 2 complains that return_enum is returning an int where it should be a dict:

```
extends Node2D

enum MY_ENUM {ONE, TWO, THREE}

func _ready() -> void:
    var a = return_enum()

func return_enum() -> MY_ENUM:
    return MY_ENUM.ONE
```

Is this intended or a regression?

**Comment by Piet-G** [comment]
> This script used to work in alpha 1, now in alpha 2 complains that return_enum is returning an int where it should be a dict:
> 
> ```gdscript
> extends Node2D
> 
> enum MY_ENUM {ONE, TWO, THREE}
> 
> func _ready() -> void:
>     var a = return_enum()
> 
> func return_enum() -> MY_ENUM:
>     return MY_ENUM.ONE
> ```
> 
> @vnen Is this intended or a regression?

I'n my mind this should work as you wrote it. Maybe not all issues of int <-> dictionary were solved in this PR?

**Pull request merged**
