### PR TITLE
Add separate program case for Godot Resources

### PR DESCRIPTION
**Pull request by KoBeWi**
Open in External program option in FileSystem Dock currently checks only for file types, which might yield some wrong results in case of tres files (like opening AudioStreamGenerator in audio editor). Since they are always text, the dock will now always open them with the external text editor, or a default program for tres files. The PR also includes some small refactor.

### CODE REVIEW

**Review by Mickeon — APPROVED** [review]
I don't know if this counts for anything but have a cookie

**Comment by akien-mga** [comment]
Should the same logic be applied to `tscn` files?

**Comment by KoBeWi** [comment]
tscn uses default program, and you probably have it configured to VS Code. I can add an explicit case.

**Comment by Calinou** [comment]
Should binary `.scn`/`.res` files be handled here as well?

**Comment by Mickeon** [comment]
If you open those in a text editor you may recognise a few words but it otherwise would look like a garbled mess

**Comment by KoBeWi** [comment]
Maybe, but how? Should they fallback to the default program?

**Comment by Mickeon** [comment]
Whatever program one would use it'd still display as gibberish, with maybe a few words somewhere in there, so maybe yes.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
