### PR TITLE
Enable Ctrl+MouseWheel zooming in VisualShaderEditor and VisualScrptingEditor.

### PR DESCRIPTION
**Pull request by BuzzBurrowes**

### CODE REVIEW

**Comment by KoBeWi** [comment]
Isn't this the same as #47173?

**Comment by aaronfranke** [comment]
@KoBeWi I think @BuzzBurrowes attempted to open this one for master, but the change is on top of the 3.x branch, so @bruvzg changed the base branch in the PR to reflect that. @BuzzBurrowes should change this PR to actually be based on master.

**Comment by pycbouh** [comment]
But it's already implemented on master, and #47173 is a backport of all of the related changes.

**Comment by BuzzBurrowes** [comment]
Sorry for making the mess here. I was going to submit the change based on the 3.2 branch, but I listened to GitHub when it told me I should submit it to master :-( I should have stuck with my intuition. Also sorry if this has already been addressed someplace. I needed mouse wheel zooming and more zooming depth as I work on a small screen laptop, and even with the map view, I still find it tough to navigate around the graph without being able to zoom out more.

**Comment by pycbouh** [comment]
Generally all changes need to first happen in master, and only then can be backported to `3.x`. So GitHub didn't lie to you. But indeed, we already have this fixed in master, and there is a pending backport for `3.x`. Since your implementation is original, I'll close it in favor of #47173, which is a direct backport.

If you think that your implementation is still better than the one that is already in master, feel free to open a new PR against it.

**Comment by BuzzBurrowes** [comment]
Looking at #47173 I can see that it does add mouse wheel zoom, but doesn't add greater zoom depth. My approach is a little more intrusive, but I think by switching to tracking a zoom factor instead of a scale directly it makes for cleaner zooming and less floating-point degradation when zooming in and out a bunch. Also, I see in that pull request the next issue I was going to look at which is related to clicking connection points when zoomed. 

So... yeah... I will switch to 3.x locally. Wait for the backport to be committed, and then maybe reapply some of my changes that increase the max zoom factor.

**Pull request closed without merging**
