### PR TITLE
[HTML5] Experimental (opt-in) virtual keyboard support.

### LINKED ISSUE #32680: Text/LineEdit not taking input on mobile browsers
**Godot version:**
3.1.1 (but also previous)

**OS/device including version:**
Ubuntu 18.04 LTS / any Android phone (Android Chrome/FF tested)

**Issue description:**
TextEdit/LineEdit in mobile browser don't pop up keyboard or don't have any other way of interacting.

Nb. I'm aware of workarounds involving use of HTML input boxes and passing their content to Godot side, but that requires the creator to edit the main site (and supposedly we're not able to reuse the HTML site, so I'd have to edit it every time???)

**Steps to reproduce:**
Open https://zireael07.github.io/Veins-of-the-Earth-Godot in a mobile browser, attempt to enter player name.

**Minimal reproduction project:**
See above.

### PR DESCRIPTION
**Pull request by Faless**
In this PR:
- Add IME support check in LineEdit/TextEdit (avoid spamming "IME is unsupported" when the DisplayServer report it as such)
- Opt-in virtual keyboard support for the HTML5 platfform.

Added as an export option "Experimental Virtual Keyboard".

Experimental Virtual Keyboard

There is no zoom, so text/line edit must be in the top part of the screen, or it will get hidden by the virtual keyboard.
UTF8/Latin-1 only (I think regular UTF-8 should work out of the box in 4.0 but I can't test it).

It uses an hidden textarea or input, based on the multiline variable, and only gets activated if the device has a touchscreen.

This could cause problems on devices with both touchscreen and a real keyboard (although input should still work in general with some minor focus issues). I'm thinking of a system to detect the first physical keystroke and disable it in case, but it might do more harm then good, so it must be well thought.

Closes #41097
Fixes #32680

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by T3chnoT00l5** [comment]
hello, how can i implement this in godot 3.2?

i need this because i need to implementing in a webview and the 3.3 uses fetch api, and i needed in xhr, thanks

**Comment by Calinou** [comment]
> hello, how can i implement this in godot 3.2?

You can try to backport the [patch](https://github.com/godotengine/godot/pull/46913.patch) manually to the `3.2` branch, but there may be merge conflicts you have to solve before it can compile.

**Comment by schweigert** [comment]
This saved my life. Thank you very much @Faless

**Comment by jet-amp** [comment]
Hi, if you use this on iPhone it will automatically zoom into a LineEdit and left user with no option to zoom out (even pinch to zoom out is not working). Also they will be a misplace typing cursor appear on the screen.

**Comment by Calinou** [comment]
> Hi, if you use this on iPhone it will automatically zoom into a LineEdit and left user with no option to zoom out (even pinch to zoom out is not working). Also they will be a misplace typing cursor appear on the screen.

Please open a new issue with a minimal reproduction project attached.

**Comment by panda666x** [comment]
> LineEdit



> Hi, if you use this on iPhone it will automatically zoom into a LineEdit and left user with no option to zoom out (even pinch to zoom out is not working). Also they will be a misplace typing cursor appear on the screen.


{
    font-size:16px; 
}

in the header (in the style tag) of the output HTML file.

**Comment by ElvisVilla** [comment]
> Hi, if you use this on iPhone it will automatically zoom into a LineEdit and left user with no option to zoom out (even pinch to zoom out is not working). Also they will be a misplace typing cursor appear on the screen.

Im having exacly the same, issue, with Godot 3.5, did you found a solution for this, is there at least a way that we can zoom out after the virtual_keyword went hide? I would appreciate the help, this bug makes the app unsuable.

**Comment by Calinou** [comment]
@ElvisVilla Please open a new issue with a minimal reproduction project attached.

**Pull request merged**
