### PR TITLE
Fix animated tile time-slice calculation accumulating float errors

### LINKED ISSUE #82286: Tilemap: Animated tiles sometimes vanish between repeats of the loop
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Windows 10

### Issue description

Animated tiles will occasionally vanish for one frame when looping back from the last frame to the first frame. 

Here's a video, you can see the animated grass vanish at ~4 seconds and again right before the end

https://github.com/godotengine/godot/assets/89282845/fed761d4-6db8-485b-96c3-440a385ebe87

### Steps to reproduce

 I am unsure exactly what triggers this, but it appears high cpu load makes it more likely, as does alt-tabbing back and forth. 
 That said, it happens without my CPU being slammed and without alt-tabbing, and running a bunch of CPU-heavy other processes and furiously alt-tabbing couldn't get it to reproduce in a minimal project with an animated tileset and nothing else.

From messing around with the animated tiles rendering code, when working on the pingpong, my guess is that this segment of tile_map.cpp might be the culprit.

```gd
//starting at line 3123
			real_t speed = atlas_source->get_tile_animation_speed(p_atlas_coords);
			real_t animation_duration = atlas_source->get_tile_animation_total_duration(p_atlas_coords) / speed;
			real_t time = 0.0;
			for (int frame = 0; frame < atlas_source->get_tile_animation_frames_count(p_atlas_coords); frame++) {
				real_t frame_duration = atlas_source->get_tile_animation_frame_duration(p_atlas_coords, frame) / speed;
				RenderingServer::get_singleton()->canvas_item_add_animation_slice(p_canvas_item, animation_duration, time, time + frame_duration, p_animation_offset);

				Rect2i source_rect = atlas_source->get_runtime_tile_texture_region(p_atlas_coords, frame);
				tex->draw_rect_region(p_canvas_item, dest_rect, source_rect, modulate, transpose, p_tile_set->is_uv_clipping());

				time += frame_duration;
			}
			RenderingServer::get_singleton()->canvas_item_add_animation_slice(p_canvas_item, 1.0, 0.0, 1.0, 0.0);
```

The way it currently works, if send too few frames to the renderingserver to occupy the entirety of animation_duration, the animated tile vanishes when it runs out (rather than keeping the previous frame onscreen)

I believe that's basically happening here; with the right level of slowdown, it's possible for the game to skip a frame or something right when the tile animation loops, and since the new frames don't immediately get sent to the renderingserver, in the next frame the animated tile vanishes, then godot catches up and sends all the frames properly, restoring the animated tile.

If that's the case, there's an easy (if dumb) fix: send the first frame to the rendering server twice, once at the beginning and once at the end.  (Or in a similar vein, give the last frame a duration of a million years)

When working on pingpong I added the new frames before changing animation_duration, and noticed that at start of a new cycle, any frame data that extended past the animation_duration period seems to get discarded harmlessly.

### Minimal reproduction project

I don't have a minimal project at the moment, it looks like I'm going to have to chop down the project that I'm seeing the glitch in rather than building a tiny one from scratch.  As a random bug that can't be triggered on demand I can't say whether or not my speculative fix would actually address the real issue, and I want to ask other people who know the tile system if they can reproduce and maybe come up with a better explanation.

### PR DESCRIPTION
**Pull request by kleonc**
TileMap's tile animation time slice starts/ends were calculated like:
`((6.0f / 6.0f) + (1.0f / 6.0f) + (1.0f / 6.0f) + (1.0f / 6.0f))` -> `1.49999988079071044922`
instead of:
`((6.0f + 1.0f + 1.0f + 1.0f) / 6.0f)` -> `1.50000000000000000000`
but the total animation duration were calculated like the latter and hence there was potentially a small time gap between the last frame's end and the end of the whole animation.

Should fix #82286, @Proggle please test if you can.

### CODE REVIEW

**Comment by groud** [comment]
This seems a bit complicated tbh. IMO, the simplest solution is to set the end frame equal to `animation_duration` when you are at the last frame. Something like:
```c++
real_t slice_end = frame == atlas_source->get_tile_animation_frames_count(p_atlas_coords)-1 ? animation_duration : time + frame_duration;
RenderingServer::get_singleton()->canvas_item_add_animation_slice(p_canvas_item, animation_duration, time, slice_end, p_animation_offset);

```

**Comment by kleonc** [comment]
> This seems a bit complicated tbh. IMO, the simplest solution is to set the end frame equal to `animation_duration` when you are at the last frame.

It's barely more complicated. I disagree we should be picking a little simpler solution over a more correct one (assuming there are no performance reasons etc.). And calculating things like I've done in here seems more correct to me (for the intermediate frames it's `i * addition_error + division_error` vs ``i * addition_error + i * division_error``).

In the usual use cases it should indeed not matter and both solutions should be unnoticeably different. But if for some reason e.g. `speed` would be very small then the discrepancies could get significant.
Is it theoretization? Yes.
Does this matter in practice? Likely no.
But I still see no reason to not handle such potential edge cases properly if it's not computationally costlier, the code isn't much more complicated, or something like that. And AFAICT that's the case in here.
(if anything I'd say the most complicated is the comment I've added for clarifying things :smile:; for me the code seems self-explanatory and that comment is not needed, still added it so no one would refactor it back)

I can go with your suggested solution if that's what's really preferred. Just wanted to point out that in general I advocate for correctness over a barely simpler code. :upside_down_face: Decision up to you, you're the maintainer here.

**Comment by groud** [comment]
I don't mind either way to be honest, merging as is would be fine.
 
TBH I don't really understand why the CanvasItem API does need both a frame start, a frame end and a duration. Either the frame duration or the total duration should be "ignorable".

**Review by akien-mga — APPROVED** [review]
This solution makes sense to me.

**Comment by kleonc** [comment]
>I don't mind either way to be honest, merging as is would be fine.

:slightly_smiling_face:

> TBH I don't really understand why the CanvasItem API does need both a frame start, a frame end and a duration. Either the frame duration or the total duration should be "ignorable".

AFAICT it could be as you're saying if it would be limited to a typical looped frame by frame animations (like the ones in the TileMap). But it's not like that, the API allows full flexibility. Animation slices can potentially overlap each other time-wise, there can be periods with nothing  to draw,you could even issue at once all commands to draw some layered animation with each layer having its own "fps", etc.

Each animation slice rendering command is an independent command, it doesn't know/assume anything about other such commands, hence it seems to need all that info:

https://github.com/godotengine/godot/blob/008b08b5fb559f896ea3a6b3b9a8de41824c5ad4/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L948-L955

**Review by groud — APPROVED** [review]

**Comment by Proggle** [comment]
> TileMap's tile animation time slice starts/ends were calculated like: `((6.0f / 6.0f) + (1.0f / 6.0f) + (1.0f / 6.0f) + (1.0f / 6.0f))` -> `1.49999988079071044922` instead of: `((6.0f + 1.0f + 1.0f + 1.0f) / 6.0f)` -> `1.50000000000000000000` but the total animation duration were calculated like the latter and hence there was potentially a small time gap between the last frame's end and the end of the whole animation.
> 
> Should fix #82286, @Proggle please test if you can.

Thanks!  I'll check this weekend when I have time.  

If I'm understanding properly this particular glitch would cause a tile rendering failure only if the frame rendering fell exactly in the 0.0000001192 second window between timespans, so it's possible that I'm seeing animation failures for multiple reason beyond this one

**Comment by kleonc** [comment]
> I'll check this weekend when I have time.

@Proggle Thanks! Note you don't need to build it yourself to test, you could download an artifact from the CI checks down below ("Show all checks" -> "Details" (any of them) -> "Summary" -> "Artifacts"). E.g. [this one for windows](https://github.com/godotengine/godot/suites/16570127075/artifacts/946700605) (artifacts are available only for some time after the CI action is run so the link is temporary).

> If I'm understanding properly this particular glitch would cause a tile rendering failure only if the frame rendering fell exactly in the 0.0000001192 second window between timespans,

Indeed.

>so it's possible that I'm seeing animation failures for multiple reason beyond this one

If you're talking about that specific glitch from #82286 then AFAICT it's unlikely there's a different cause (e.g. a different reason could be `Math::fposmod` not working correctly). But sure, there could be some different problem I haven't noticed looking at the relevant code. :upside_down_face:

**Comment by akien-mga** [comment]
Thanks!

**Comment by Proggle** [comment]
> > I'll check this weekend when I have time.
> 
> @Proggle Thanks! Note you don't need to build it yourself to test, you could download an artifact from the CI checks down below ("Show all checks" -> "Details" (any of them) -> "Summary" -> "Artifacts"). E.g. [this one for windows](https://github.com/godotengine/godot/suites/16570127075/artifacts/946700605) (artifacts are available only for some time after the CI action is run so the link is temporary).
> 
> > If I'm understanding properly this particular glitch would cause a tile rendering failure only if the frame rendering fell exactly in the 0.0000001192 second window between timespans,
> 
> Indeed.
> 
> > so it's possible that I'm seeing animation failures for multiple reason beyond this one
> 
> If you're talking about that specific glitch from #82286 then AFAICT it's unlikely there's a different cause (e.g. a different reason could be `Math::fposmod` not working correctly). But sure, there could be some different problem I haven't noticed looking at the relevant code. 🙃

Oh, that's handy, trying to compile on my laptop takes forever.

Anyway, running both the original and patched versions side by side, I managed to catch 4 framedrops on the old version and 0 on the new one, so tentatively looks like it's patched.  I'm going to keep working on this project more and I'll yell if I see any more vanishing tiles.

Mathematically seems weird that this'd be the cause, if it were some kind of uniform distribution it seemed super unlikely a frame would fall into the crack between floats as often as I was seeing it (about a 0.0007% chance per loop, so about 3% chance of seeing a single frame drop if I was watching it a whole hour).  I guess the distribution isn't actually that random and when my computer is at the right cpu load it consistently takes exactly 1.49999988079071044922 seconds to do 90 frames.  

Weird, but I'll take the win.  Thanks for the fix :)

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3.

**Pull request merged**
