### PR TITLE
Add subsequence search to tools

### LINKED ISSUE #5109: Search letter-wise instead of word-wise
This is a usability improvement.

It is better to show search results that contain the typed "letters" instead of correctly spelled words. The working is similar to sublime text autocomplete where you don't have to type a method/property in the correct word.

For eg: 
In Godot Create Node Popup window, we can start typing "kin" to get Nodes that starts with letters "kin". It includes both KinematicBody and KinematicBody2D including their parents.
But I want to select the KinematicBody2D in the list. According to my proposal, if we type "kin2" the resulting nodes will be that contains the letters "k","i","n" and "2". So I can quickly select the node without moving my hand from keyboard to mouse.

### PR DESCRIPTION
**Pull request by vnen**
Adds it to the following searches:
- Create node.
- Scene tree.
- Inspector properties.
- Classes list in help.
- Quick open.

Also adds `String.is_subsequence_of(text)` and `String.is_subsequence_ofi(text)` (case-insensitive version).

Closes #5109.

### CODE REVIEW

**Comment by reduz** [comment]
ooh is this what I think it is? :)

**Comment by vnen** [comment]
@reduz illustrating with the same image I posted on #5109:

screenshot from 2016-06-12 00-51-45

**Comment by reduz** [comment]
can't wait to see this for code completion :)

**Comment by vnen** [comment]
I still have to understand how code completion works. But I guess it eventually does some string comparison which could be replaced with this subsequence search.

**Comment by neikeq** [comment]
@vnen I think this is the relevant part: https://github.com/godotengine/godot/blob/master/scene/gui/text_edit.cpp#L4101-L4106

**Comment by vnen** [comment]
@neikeq thanks. I was going to ask if the script editor is a regular TextEdit, but this answers my question :)

**Comment by vnen** [comment]
@reduz can this be merged? I found a neat way to improve the completion, but it depends on this one and might require another discussion 😉

**Comment by akien-mga** [comment]
Wouldn't it be better to have an optional boolean argument for ``is_subsequence_of`` instead of making it a different function? (My main concern is that ``is_subsequence_of**i**`` might not be that user-friendly as a function name)

**Comment by vnen** [comment]
@akien-mga it's like that internally (I did so to avoid duplicating the function), but I'm not really a fan of boolean parameters. If I read `is_subsequence_of("text", true)`, I can't really tell what's going on with a glance. Even if I know it's about case, this `true` means case-sensitive or the opposite? Since you write the code once but read multiple times I'd rather have something easier to read.

I agree that `is_subsequence_ofi` might not be the better name, I just think it's better to rename it than to use a boolean parameter.

Another solution could be the use of constants. So `is_subsequence_of("text", String.CASE_INSENSITIVE)`, which is very readable.

**Pull request merged**
