### PR TITLE
Add option to paste animation as duplicate

### LINKED ISSUE #24950: Copy/Paste Animation is a reference, not a copy.
**Godot version:**

3652442

**OS/device including version:**

Win10 64bit

**Issue description:**

I understand this is likely by design, and addressed and closed multiple times already.  However, this terminology is confusing and keeps catching me off guard still to date.  I'm in the mindset that a Copy will produce a copy, not a reference.

Is the primary use case really a reference?  It is hard to track these things as well since there isn't any obvious indicator what else it is linked with inside the project.  It is sensible and desirable when saving Animations as resources to be reused, though they're still hard to know the reach of it.

We mainly use this feature to copy an animation to quickly move tracks into other AnimationPlayers to save efforts.  Then after some modification, and potentially saving, the damage is discovered.

Not the worst if your project is version controlled, but just messing about in small projects, you can quite easily do some destructive work.

The current work flow to do this is:
1. Copy Animation
2. Paste Animation
3. Remember to Duplicate it.
4. Delete the first.
5. Rename the duplicate.

I'm not sure what language would be preferred, but perhaps it would be a usability improvement (especially for newcomers) to have two copy or two paste options.  Each with explicit language about the outcome.

Copy Animation
Copy Animation Resource
Paste

or 

Paste
Paste Animation Resource

Maybe someone else has better ideas.

**Steps to reproduce:**

Copy and Paste animation into another AnimationPlayer and modify the tracks.

image

### PR DESCRIPTION
**Pull request by KoBeWi**
Might resolve #24950
image
(this image is outdated, see below for new one)

@avencherus 
@golddotasksquestions

EDIT:
Added another commit that alternatively makes Paste duplicate by default and adds "Paste As Reference" option for current behavior.
image

### CODE REVIEW

**Comment by avencherus** [comment]
Great, I'll check it out, and very likely start using it immediately.  It certainly should resolve the issue, as no option even exists.  Much appreciation for this.

Though I don't know if the UI presentation side of things were ever settled.

I will just add that there are non-programmers that end up working with the AnimationPlayer, and in my experience when I have tried to explain the whole Animations are a Resource business, eyes get glassy.  Later they're just paranoid about using the tool, and duplicating and double checking everything.

I don't animate a lot, so almost always when I return to it, I make this mistake myself of copy / paste, start editing... uh oh.

I think the major problem first is that the word Copy is already implying a Duplicate.

It's my feeling that for a tool like this, copying and pasting resource references is a secondary operation.  Duplication seems to be the most intended, as copy and pasting in this workflow context is more like templating.  Reaching for something similar and reworking it.

IE - Take enemy A's floating animation into enemy B, and tweak it a little.

So to add to any following discussions (if any).

I would say it probably might even be best to start with the implications of the word Copy.

Copy
Copy (As Resource)
Paste

Leaving that option there for those who know what is what regarding Resource behavior.

As others have mentioned as well, there is still some ambigiouty about in the AnimationPlayer about when things are being done to a shared resource or a unique one.

The tools seems to be trying to hide the back end implementation (Animations as Resources), for user friendliness, but then has these behaviors that are invisible and baffling to non-programmers.

**Comment by asheraryam** [comment]
@avencherus Why should there be two Copy actions?

One Copy is fine, with Paste and Paste as Reference instead.

Implementation-wise it would copy a reference first, and then if Paste is selected it would perform a deep duplicate after navigation to the reference pointer, or if Paste as Reference is used it will put the reference as-is.

**Comment by avencherus** [comment]
@asheraryam Great points.

The initial thinking was to express the intention of the action with the first choice.  If having referential copying at all.  It is currently a bit of a dangerous feature, since there are no accompanying indicators or persisting expectations of which is which.  One might have 1 shared Animation among a list of 20 Animations, and return to editing them a week later.

I stopped short of Paste / Paste as Resource in my post, but reflecting on it, I think from a user perspective (implementation aside) it should be better.  One is probably traveling to another location in the editor to do this, and it may not be entirely clear what is on the clipboard if these two options exist.  (The Paste option would have to contextually change.)  The Paste is the ending action and there it seems most clarifying.

With maintaining both, Paste / Paste as Reference sounds better to me at least.

I was thinking about that naming too, Paste as Resource Reference seems like the most clear, but wow that poor box is already being stretched out quite awkwardly since everything else is very terse.   X)

**Comment by KoBeWi** [comment]
Added another commit that does this in alternative way (see OP).

**Comment by golddotasksquestions** [comment]
> Added another commit that alternatively makes Paste duplicate by default and adds "Paste As Reference" option for current behavior.

Thank you!

**Comment by aaronfranke** [comment]
@KoBeWi Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by KoBeWi** [comment]
Rebased refactored and squashed.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
