### PR TITLE
Add CarouselButton Node

### PR DESCRIPTION
**Pull request by AlaraBread**
implements [godotengine/godot-proposals#5139](https://github.com/godotengine/godot-proposals/issues/5139)

edit

opened a new pr because this one was on my master branch: #64535

### CODE REVIEW

**Comment by YuriSizov** [comment]
You shouldn't use your `master` branch for PRs. You should start a new branch from your `master` and work there. You now have unrelated changes in your submission.

**Comment by jul2040** [comment]
> You shouldn't use your `master` branch for PRs. You should start a new branch from your `master` and work there. You now have unrelated changes in your submission.

should i make a new pr? or is there a way I can change this one? sorry, im new to this.

**Comment by YuriSizov** [comment]
> should i make a new pr? or is there a way I can change this one? sorry, im new to this.

I'm not sure what is wrong with your current branch and why another commit is appended to it. You can probably still fix it with a correct rebase, but it would be harder to do on your fork's `master`.

At the very least, consider that in future PRs. But for now, you have to fix the commits to only include your changes. If you want to open a new PR for that, go ahead, we'll just close this one.

**Comment by jul2040** [comment]
okay, i fixed some errors that i was getting, and removed your commit.

**Comment by jul2040** [comment]
fixed a few edge cases

**Comment by jul2040** [comment]
here's a video of the CarouselButton

https://user-images.githubusercontent.com/59781761/185006138-e931666d-e400-4d60-be16-3bb4bbe26bde.mp4

**Comment by YuriSizov** [comment]
For the record, this was NOT merged. The user just restored their master to a pristine state, so this PR no longer contained any commits.

**Pull request merged**
