### PR TITLE
Rename TouchScreenButton's textures

### PR DESCRIPTION
**Pull request by KoBeWi**
Part of #38937
New names taken from TextureButton.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Closing for the same reason as #54430

**Comment by akien-mga** [comment]
Well I think it's still worth fixing until it's actually removed.

**Comment by KoBeWi** [comment]
Ok, doesn't look like it's going to be removed anytime soon.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
