### PR TITLE
Add "Show Origin" and "Show Viewport" options to 2D Editor Viewport

### LINKED ISSUE #17119: Add possibility to show/hide Origin in 2D View
**Godot version:**
Godot 2 and Godot 3

**OS/device including version:**
Windows 7 64bit

**Issue description:**
I like to have the possibility to hide the origin in 2D view. It is already possible in 3D view.
image

**Use case:**
Clean screenshots for advertising. (twitter, facebook. etc.)

### PR DESCRIPTION
**Pull request by bfloch**
Fixes https://github.com/godotengine/godot/issues/17119

show_origin_show_window

BTW I noticed 3D and 2D is a bit inconsistent.
In 3D the menu says "View Grid" etc. while it is "Show Grid" in 2D. Note sure if you want to fix this.

### CODE REVIEW

**Comment by groud** [comment]
Nice addition ! :)
My only remarks are for the words used. "Show Window" is definitely not right, I believe "Show viewport" should be more accurate.
I'm not sure  about "Show origin" too, I would personnaly go for "Show axes", but if people prefer origin I'm ok with that.

Als oit would be good to add keyboard shortcuts for them.

**Comment by bfloch** [comment]
Thank you for the feedback. I had similar thoughts, all you say is appropriate.
I can live with any of them, here my initial reasoning:
- Show Origin (just to be consistent with 3D Viewport)
- Show Window (I'm ok with Viewport, but I thought that might be misleading as the whole thing is the viewport somehow. Also the source setting setting lives under "Display -> Window -> Size")
- I too felt keyboard short cut are too precious to be wasted on something that minimal.

How about I'll change this to:
- Show Origin
- Show Viewport
- Leave no shortcuts

**Comment by groud** [comment]
I guess it makes sense :)

**Comment by akien-mga** [comment]
Thanks, looks good.

**Comment by hpvb** [comment]
Cherrypicked into 3.0.3

**Pull request merged**
