### PR TITLE
More function/class renames in converter

### LINKED ISSUE #62434: `apply_force` and `apply_impulse` functions not handled by covnerter tools
### Godot version

4.0 alpha 10

### System information

Win10 64bit

### Issue description

4.0 converter tools do not properly convert 3.x `apply_force` and `apply_impulse` functions, which both had their arguments reordered (3.x is (position, force), 4.0 is (force, position)).

### Steps to reproduce

Convert 3.x project with `apply_force` or `apply_impulse` functions to 4.0

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by qarmin**
Closes https://github.com/godotengine/godot/issues/62434

also fixes this one rename `"RenderingServer" -----> "get_tab_alignment"`

### CODE REVIEW

**Comment by Zireael07** [comment]
One more thing: I think it doesn't handle the recent shader change, hint_albedo to hint_color etc...

**Comment by qarmin** [comment]
Is there any way to get list of shader keywords/functions from GDScript?

Finding them one by one by searching source code/PR's is time consuming,

**Review by akien-mga — APPROVED** [review]
Great work!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
