### PR TITLE
Remove the 3D camera gizmo icon

### LINKED ISSUE #425: Implement camera icon as 3D model facing the correct direction
**Describe the project you are working on:**
Any project.

**Describe the problem or limitation you are having in your project:**
When zooming the scene far away,and looking at  the camera in the scene, it can be confusing to think that the camera _icon_ is showing which way the camera is looking at in the scene. 

For example, here looking at the camera from far away where the camera detail is not shown, I see this, and might think that the camera is facing outwards from the center of the scene:

image

Now when I zoom in on the scene, actually the camera is facing the other way

image

I notice myself being constantly confused by this fact that the icon is facing whatever direction that is not related to the actual camera looking at direction in 3D space.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**

Would suggest implementing the camera icon as an actual 3D model of a camera, that is always facing in the correct orientation. Would help to see better anyway where the model is looking at.

Or possibly replacing the icon with a direction neutral one. 

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:*

Unreal engine seems to do this already:

image

Or as an easier solution, use a direction neutral camera icon like this:

image

**Describe implementation detail for your proposal (in code), if possible:**
Figure out a 3D model for the camera, replace the icon with this 3D model. 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Dont think so.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Part of the core mechanics. Would make it more user friendly.

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/49644.

The gizmo icon obstructed the line-based camera gizmo, which made it difficult to see the actual camera orientation.

This also removes the unused SpatialStreamPlayer gizmo icon.

This closes https://github.com/godotengine/godot-proposals/issues/425.

### Before

Hidden

### After

Not hidden

### CODE REVIEW

**Comment by Zireael07** [comment]
I don't think it's a move in the right direction. The gizmo should rotate to show the correct direction and/or have a direction arrow added. The pink camera extents gizmo can get very small for small fov cameras and/or zoomed out view.

**Comment by Calinou** [comment]
@Zireael07 The gizmo icon can't be made to rotate in all situations. For instance, if you're right in front or behind the camera, it would spazz out in various directions.

**Comment by aaronfranke** [comment]
What about if the gizmo icon behaved like a two-sided `Sprite3D`?

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
I'm also slightly concerned about readability, we might end up with situations where the camera is hard to locate.

But I agree that removing the billboarded icon is good, further improvements should be made on the 3D gizmo itself to make it more readable (e.g. changing scale, colors, or adding a triangle showing the up direction as done in Blender).

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
> adding a triangle showing the up direction as done in Blender).

There's already one (you can see it on the screenshot), but maybe it needs to be drawn differently to be easier to notice.

**Pull request merged**
