### PR TITLE
Offset and length parameter for send_bytes method (3.2)

### PR DESCRIPTION
**Pull request by SaracenOne**
Allows specifying a length and offset for the MultiplayerAPI's send_bytes method.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Is there a particular reason that this PR (and your other two PRs) weren't done for the `master` branch? Most changes need to be done there first before they can be cherry-picked to stable branches.

**Comment by SaracenOne** [comment]
The only reason is really that we're working on the 3.2 branch at the moment. Migrating this to master should be very trivial though, so I'll likely open up new PRs for that.

**Comment by Faless** [comment]
PRs should always be done on the master branch.
Regarding the change, I'm not really convinced. This seems to just make it more complicated for a limited(?) use case.

**Comment by SaracenOne** [comment]
This essentially was born out of performance concerns for our networking stack, specifically in trying to prevent as many memory allocations as possible by preallocated big pages of writable state data which we could reuse, but there are limitations in the old Godot 3 PoolArray classes for doing this effectively. Now, as far as I understand, 4.0's replacement for PoolArrays is going some ways to prevent unnessecary memory allocations. I'm not sure yet, but if it's possible to simply reference subarrays of memory without redundant allocations, then yeah, I'd probably consider this to be redundant.

**Comment by akien-mga** [comment]
This was merged by mistake and the `3.2` branch force pushed back to the previous state. A new PR will be needed as this one can't be reopened.

**Pull request merged**
