### PR TITLE
Cyclic BlendSpaces [1D/2D] for Animation

### PR DESCRIPTION
**Pull request by marstaik**
*Note*: Depends on https://github.com/godotengine/godot/pull/34134, as the blends are even more broken without it.

This PR aims to do some bugfixing for blendspaces as well as introduce the concept of *Cyclic* BlendSpaces.

There was some previous discussion of this here: https://github.com/godotengine/godot/issues/23414

Coming from other game engines, this is really a crucial and useful component for animation.

These cyclic BlendSpaces are very important for blending in animations whose timescale is supposed to match, such as movement animations, look-at animations, breathing animations, etc...

Currently they only support AnimationNodeAnimation's, since its currently the only way to reliably obtain an AnimationNodes runtime length, which is a hard requirement.

If AnimationNode's had a common interface where each node could return its computed runtime length, then any node could be used in the future, but that is a ton of work and maybe not as crucial for Cyclic BlendSpaces anyways.

Here is a Demo:
https://f.staik.net/f/2de.mp4

### CODE REVIEW

**Comment by marstaik** [comment]
Updated for current master branch

**Comment by marstaik** [comment]
Updated for 4.0

**Comment by SuperDIMMaX** [comment]
Probality not working with `get_root_motion_transform()` - tested on 3.2.3 this -  https://github.com/godotengine/godot/commit/c30eb284f02e9025d7c7ddad1dccbe008b911fe6

**Comment by marstaik** [comment]
@SuperDIMMaX do you have a sample project I can check?

**Comment by SuperDIMMaX** [comment]
> @SuperDIMMaX do you have a sample project I can check?
@marstaik
[Test_cb.zip](https://github.com/godotengine/godot/files/5004597/Test_cb.zip)

**Comment by fire** [comment]
@marstaik Are you ok with me taking this over? You can keep the pr open and I can modify your branch.

**Comment by marstaik** [comment]
> 
> 
> @marstaik Are you ok with me taking this over? You can keep the pr open and I can modify your branch.

Yeah, that's fine. :)

**Comment by fire** [comment]
@TokageItLab Is this still valid?

**Comment by TokageItLab** [comment]
As superseded by #62424, I think it can be closed. However, #62424 still seems problematic and should be sent off to 4.x or later.

**Comment by akien-mga** [comment]
Closing based on above comment.

**Pull request closed without merging**
