### PR TITLE
Re-write SignalAwaiter implementation

### PR DESCRIPTION
**Pull request by neikeq**
Old implementation had issues where you could only await on the same signal of the same source once.

### CODE REVIEW

**Comment by tagcup** [comment]
After this change, a working code started to crash instantly on launch...

The only message I'm getting is

```
shit?: Connection reset by peer
ERROR: read: Server disconnected!
```

so not sure why yet

**Comment by neikeq** [comment]
@tagcup What is the backtrace? Can you share an example project?

**Comment by tagcup** [comment]
This is what I got from gdb, which doesn't look very useful

```
Thread 9 "Debugger agent" received signal SIG35, Real-time event 35.
[Switching to Thread 0x7fffcdc55700 (LWP 6105)]
0x00007ffff4d41c7b in accept () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff4d41c7b in accept () from /usr/lib/libpthread.so.0
#1  0x00007ffff5799ab5 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#2  0x00007ffff57aace5 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#3  0x00007ffff59523e9 in ?? () from /usr/lib/libmonosgen-2.0.so.1
#4  0x00007ffff4d3808a in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff44d224f in clone () from /usr/lib/libc.so.6
```

Sure I'll try to isolate the issue tomorrow and submit an example project if I can

**Comment by tagcup** [comment]
There's also a chance that this may be related to another recent commit so I'll to try to do a bisect

**Comment by neikeq** [comment]
There are a few signals that mono uses internally that you will have to tell gdb to ignore. This is my .gdbinit:

`handle SIGXCPU SIG33 SIG35 SIG36 SIG37 SIG39 SIGPWR nostop noprint`

**Comment by tagcup** [comment]
Thanks for the tip, I'm seen the actual SIGSEGV now, looks a bit more informative:

```
Thread 1 "godot.x11.opt.t" received signal SIGSEGV, Segmentation fault.
0x00007ffff595875e in ?? () from /usr/lib/libmonosgen-2.0.so.1
(gdb) bt
#0  0x00007ffff595875e in ?? () from /usr/lib/libmonosgen-2.0.so.1
#1  0x00007ffff5813c3e in mono_bounded_array_class_get () from /usr/lib/libmonosgen-2.0.so.1
#2  0x00007ffff58d3e9d in ?? () from /usr/lib/libmonosgen-2.0.so.1
#3  0x00007ffff58d3f21 in mono_array_new () from /usr/lib/libmonosgen-2.0.so.1
#4  0x0000555555f9637b in Array_to_mono_array () at modules/mono/mono_gd/gd_mono_marshal.cpp:585
#5  0x0000555555fd7ac1 in godot_icall_0_24(MethodBind*, Object*) () at modules/mono/glue/mono_glue.gen.cpp:234
#6  0x0000000040054d12 in ?? ()
#7  0x0000000000000000 in ?? ()
```

**Comment by neikeq** [comment]
Can you open an issue? (with an example project, if possible)

**Comment by tagcup** [comment]
Never mind, I can't reproduce this anymore

**Pull request merged**
