### PR TITLE
Fix array overflow when saving scene preview

### LINKED ISSUE #29339: Array overflows when saving scene
**Godot version:**
3.2.dev.custom_build. 1f91de4

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I saved scene, Godot generate scene preview image, which have inside array with overflows, this errors shows in Valgrind:
```
Invalid write of size 4
   at 0x3651E6D: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:764)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)
   by 0x2A54A5E: PopupMenu::activate_item(int) (popup_menu.cpp:1117)
   by 0x2A54472: PopupMenu::activate_item_by_event(Ref<InputEvent> const&, bool) (popup_menu.cpp:1050)
   by 0x2A3856F: MenuButton::_unhandled_key_input(Ref<InputEvent>) (menu_button.cpp:47)
 Address 0x2c10b94c is 0 bytes after a block of size 108 alloc'd
   at 0x582F74F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37B15EB: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x1E80C02: float* memnew_arr_template<float>(unsigned long, char const*) (memory.h:152)
   by 0x3651D6D: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:752)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)

Invalid read of size 4
   at 0x3651EEB: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:773)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)
   by 0x2A54A5E: PopupMenu::activate_item(int) (popup_menu.cpp:1117)
   by 0x2A54472: PopupMenu::activate_item_by_event(Ref<InputEvent> const&, bool) (popup_menu.cpp:1050)
   by 0x2A3856F: MenuButton::_unhandled_key_input(Ref<InputEvent>) (menu_button.cpp:47)
 Address 0x2c10b94c is 0 bytes after a block of size 108 alloc'd
   at 0x582F74F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37B15EB: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x1E80C02: float* memnew_arr_template<float>(unsigned long, char const*) (memory.h:152)
   by 0x3651D6D: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:752)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)

Invalid write of size 4
   at 0x36521AE: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:814)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)
   by 0x2A54A5E: PopupMenu::activate_item(int) (popup_menu.cpp:1117)
   by 0x2A54472: PopupMenu::activate_item_by_event(Ref<InputEvent> const&, bool) (popup_menu.cpp:1050)
   by 0x2A3856F: MenuButton::_unhandled_key_input(Ref<InputEvent>) (menu_button.cpp:47)
 Address 0x28cdbb2c is 0 bytes after a block of size 108 alloc'd
   at 0x582F74F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37B15EB: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x1E80C02: float* memnew_arr_template<float>(unsigned long, char const*) (memory.h:152)
   by 0x36520BD: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:803)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)

Invalid read of size 4
   at 0x3652223: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:823)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)
   by 0x2A54A5E: PopupMenu::activate_item(int) (popup_menu.cpp:1117)
   by 0x2A54472: PopupMenu::activate_item_by_event(Ref<InputEvent> const&, bool) (popup_menu.cpp:1050)
   by 0x2A3856F: MenuButton::_unhandled_key_input(Ref<InputEvent>) (menu_button.cpp:47)
 Address 0x28cdbb2c is 0 bytes after a block of size 108 alloc'd
   at 0x582F74F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x37B15EB: Memory::alloc_static(unsigned long, bool) (memory.cpp:85)
   by 0x1E80C02: float* memnew_arr_template<float>(unsigned long, char const*) (memory.h:152)
   by 0x36520BD: void _scale_lanczos<4, unsigned char>(unsigned char const*, unsigned char*, unsigned int, unsigned int, unsigned int, unsigned int) (image.cpp:803)
   by 0x3631AE1: Image::resize(int, int, Image::Interpolation) (image.cpp:1074)
   by 0x1FF8349: EditorNode::_save_scene_with_preview(String, int) (editor_node.cpp:1028)
   by 0x1FFFE28: EditorNode::_menu_option_confirm(int, bool) (editor_node.cpp:2009)
   by 0x1FF548A: EditorNode::_menu_option(int) (editor_node.cpp:739)
   by 0x1435327: MethodBind1<int>::call(Object*, Variant const**, int, Variant::CallError&) (method_bind.gen.inc:775)
   by 0x36770A0: Object::call(StringName const&, Variant const**, int, Variant::CallError&) (object.cpp:940)
   by 0x3678DBC: Object::emit_signal(StringName const&, Variant const**, int) (object.cpp:1240)
   by 0x367947B: Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (object.cpp:1296)

```
**Steps to reproduce:**
1. Open minimal project
2. Save this project

**Minimal reproduction project:**
[FaultyMap01.zip](https://github.com/godotengine/godot/files/3241037/FaultyMap01.zip)

### PR DESCRIPTION
**Pull request by qarmin**
Fix #29339

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @Daw11

**Comment by Daw11** [comment]
The size of the array was correct.
The problem is in the two variables `end_x` and `end_y`. They are one position too much.

The two lines should be like this:

`int32_t end_y = MIN(src_height - 1, buffer_y + half_kernel - 1);`

and

`int32_t end_x = MIN(src_width - 1, src_x + half_kernel - 1);`

So if for example the point is at `10` and `half_kernel` is `3`, it will go from point `8` to `12` and they can all stay inside the array with size `5` ( `3 * 2 - 1` ).

**Comment by Daw11** [comment]
Since now there's no need to have both the variables inside the MIN with a `-1` you could just remove it:
`int32_t end_y = MIN(src_height, buffer_y + half_kernel);`

and have the 4 loops inside the function use a `<` instead of a `<=`.

**Comment by Daw11** [comment]
The fix is correct. The array was on position to small.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
