### PR TITLE
Updated default values in SpatialMaterial and Environment

### LINKED ISSUE #10160: Better default values for default environment and default material metallic
**Operating system or device - Godot version:**

Win10 current Godot3 build

**Issue description:**
ISSUE1 - The default world environment that is loaded into each new scene (default_env.tres) has the ambient_light_sky_contribution = 0.0 value. This means that any meshes that are added to the scene with high roughness values will be seen as black. This value should be default at 1. I am fairly sure that this changed not too long ago!

This is particularly problematic when using separate scenes for objects that will be instanced into a master scene. In these separate scenes, you currently have to add a new environment just to setup a material, then hide it when it is instanced into a master scene

This is currently what we get:

default_env

This what it should be:

fixed_env

ISSUE2: The default metallic value for a spatial material is currently 0.1. Most materials will be either a metal (1) or dielectric (0), so having 0.1 is confusing for someone new to the engine, as they may think it is a good default value. 

The default should be either 0 or 1. The advantage of having it at 0 is that materials are more likely to be non-metallic (dielectric) than metallic, so may serve as a better starting point. Also having both metallic and roughness at default 0 gives a pleasing result for a material, as seen below:

material0

The advantage to having it at 1 as default is that when adding maps, this value needs to be changed to 1 anyway. However the same would apply to the roughness value and if both of these were at a default of 1, then the default material shows as all black and is not a good starting point, as seen below:

material1

**Steps to reproduce:**

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by Keetz**
Fixes #10160

I updated the default values as discussed in above issue.

### CODE REVIEW

**Comment by tagcup** [comment]
How about setting the specular to 0 (or 1)?

**Comment by Keetz** [comment]
@tagcup i thought it would be best to leave it at 0.5 due to what @fracteed wrote:

> "The F0 for common dielectric materials is typically set to 0.04 (linear) 4% reflective. In the metal/ roughness workflow, this value is hardcoded in the shader at this 4% value. Some metal/roughness implementations such as those found in the Substance toolset and Unreal Engine 4 have a specular control, which allows the artist to change the constant F0 value for dielectrics. In Substance, this output is labeled as "specularLevel" and is supplied by a texture sampler in the metal/ roughness PBR shader. It represents the range of 0.0 - 0.08 as shown in figure 05. This range is remapped in the shader to 0.0-1.0 where 0.5 represents 4% reflective"

Did i misunderstand this or?

**Comment by tagcup** [comment]
So we're sure that Godot is working like Substance or Unreal in this regard? I mean I don't really know, I was just asking to be sure.

**Comment by Keetz** [comment]
@tagcup I am not sure, no :) I guess i thought it was a "standard" for specular to work like that.

**Comment by tagcup** [comment]
Could be, no idea :)

**Pull request merged**
