### PR TITLE
 Take CanvasLayer transform into account for 2D physics 

### LINKED ISSUE #18073: CollisionObject2D nodes inside CanvasLayer are not affected by layer offset or rotation
**Godot version: 3.1dev 34e3675**

**Issue description:**
`CollisionObject2D`s inside a `CanvasLayer` do not take the layer offset or rotation into account for their (state?) position.

It would be desirable if they respect the layer positioning, at least Area2D nodes (may be too complex for PhysicsBody).

**Steps to reproduce:**
Create any `CollisionObject` and add it to a layer, put an offset on the layer and watch the interaction with objects outside the layers or input like mouse.

**Minimal reproduction project:**
[CanvasLayerAndCollisionObjects.zip](https://github.com/godotengine/godot/files/1888009/CanvasLayerAndCollisionObjects.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #18073.

**EDIT:** No cherry-pick needed, a separate PR for 3.0 will contain this.

This code is donated by an anonymous contributor.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by reduz** [comment]
This is clearly generating problems, but I am not sure why

**Comment by RandomShaper** [comment]
Me neither. But since the main problem to address was picking, I'm taking a different route:

Areas and bodies will have a canvas_instance_id in the Physics2DServer, the same way they have the object id of their corresponding nodes.

With that, intersection queries filtered by canvas id will be possible.

Viewport will have a list of every descendant canvas and it will be able to do filtered queries for picking transforming the touch/mouse position correctly in every case with the canvas transforms.

I'll submit a PR reverting the current broken approach and implementing this new idea. Less overhead, fixes the real issue and is also compatible with 3.0.

Sounds good to you?

**Comment by akien-mga** [comment]
Sounds good to me. I'll push the revert of 4839e5f for now to fix issues users are experiencing, then we can review and test your new proposal. (20dc630 seems to be ok according to #21289).

**Comment by akien-mga** [comment]
Or do you advise to revert both/the whole PR? (i.e. does 20dc630 makes sense by itself, or should it be used only if 4839e5f is included too?)

**Comment by RandomShaper** [comment]
OK!

They are independent. Only 4839e5f is bad.

**Comment by akien-mga** [comment]
Alright, 4839e5f is reverted as ab3716bd4.

**Pull request merged**
