### PR TITLE
[Windows] Add quotes only to the command line arguments with special characters.

### LINKED ISSUE #38803: OS.execute is broken
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
The example 
`OS.execute("CMD.exe", ["/C", "cd %TEMP% && dir"], true, output)`
does not produce the expected result, but instead an empty array.
When exported with debug, the debug window produces:
`The filename, directory name, or volume label syntax is incorrect.`

**Steps to reproduce:**
Export a test project with debugging enabled, where the example expression gets executed.

**Minimal reproduction project:**
Any test project where the example expression gets executed.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #38803

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference, we do a similar quoting of all arguments in `OS_Unix` that also creates some restrictions: #37440 #37291.

**Comment by bruvzg** [comment]
> Might use a similar fix, but it doesn't necessarily have to be in this PR as the issues are different on each OS.

It's highly unlikely that list of the special character and quoting rules are the same on Linux (it might be different for each shell). This fix definitely should not be reused as is, without prior investigation.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
