### PR TITLE
Fix ogg edge cases

### LINKED ISSUE #55848: Playing of ogg streams fails to stop if mixing the stream ends with less than 4 frames mixed.
### Godot version

092a2861277e7df87aec10516d713d0bf4adba79

### System information

Arch Linux 5.14.16-arch1-1, Intel 3570K, Radeon 580

### Issue description

Playing of ogg streams fails to stop if mixing the stream ends with less than 4 frames mixed.
This is because the following if statement requires "internal_buffer_end" to be equals to "idx", but this is impossible in some cases since "idx" is never less than 4.

servers/audio/audio_stream.cpp
AudioStreamPlaybackResampled::mix
```cpp
if (idx <= internal_buffer_end && idx >= internal_buffer_end && mixed_frames_total == p_frames) {
	// The internal buffer ends somewhere in this range, and we haven't yet recorded the number of good frames we have.
	mixed_frames_total = i;
}
```

A draft #55846 has been created for fixing this issue.

### Steps to reproduce

You can reproduce the issue with the included miniminal reproduction, which includes an ogg file that ends with 3 frames mixed.

### Minimal reproduction project

[cstaavetti_minimal_reproduction2.zip](https://github.com/godotengine/godot/files/7698226/cstaavetti_minimal_reproduction2.zip)

### LINKED ISSUE #55849: Playing of ogg streams fails to stop if mixing the stream ends with exactly 256 frames mixed.
### Godot version

092a2861277e7df87aec10516d713d0bf4adba79

### System information

Arch Linux 5.14.16-arch1-1, Intel 3570K, Radeon 580

### Issue description

Playing of ogg streams fails to stop if mixing the stream ends with exactly 256 frames mixed.
This is because if "_mix_internal" returns the value of 256 frames mixed, "internal_buffer_end" will not be altered and it is impossible for it to be equals to "idx". Similar to #55848
INTERNAL_BUFFER_LEN is 256

AudioStreamPlaybackResampled::mix
```cpp
int mixed_frames = _mix_internal(internal_buffer + 4, INTERNAL_BUFFER_LEN);
if (mixed_frames != INTERNAL_BUFFER_LEN) {
	// internal_buffer[mixed_frames] is the first frame of silence.
	internal_buffer_end = mixed_frames;
}
```

A draft #55846 has been created for fixing this issue.

### Steps to reproduce

I have included a minimal reproduction with an ogg file that ends with exactly 256 frames mixed.

### Minimal reproduction project

[cstaavetti_minimal_reproduction3.zip](https://github.com/godotengine/godot/files/7698239/cstaavetti_minimal_reproduction3.zip)

### PR DESCRIPTION
**Pull request by ellenhp**
This should fix the edge cases described in the comments of #55820. This PR needs testing and issues tracking each edge case to be created and linked before review/merging.

In its current state, this PR is just an attempt at simplifying some of the logic in the AudioStreamPlaybackResampled class and its Ogg implementation. A few things I was doing before that were error-prone have been removed. It's not perfect but I think it's a step in the right direction.

<i>Bugsquad edit</i>: Fix #55849, Fix #55848

### CODE REVIEW

**Comment by cstaavetti** [comment]
From just simply testing the code I can tell that it does indeed seem correctly play all the ogg files that previously failed to stop.
However I did notice that playing some mp3 files such as the included one do cause an error message

ERROR: Condition "!active" is true. Returning: 0
   at: _mix_internal (modules/minimp3/audio_stream_mp3.cpp:41)

It still sounds correct and stops.
[mp3error.zip](https://github.com/godotengine/godot/files/7698295/mp3error.zip)

**Comment by ellenhp** [comment]
Oh good catch, I should make the same change to the MP3 stream. This change brings things more in line with the way I envisioned everything working when I did the audio server rewrite. The audio server attempts to mix a certain number of samples, and the stream playback can simply refuse to do the mix, if it's unable, which will cause the audio server to fade-out the playback to silence and then stop it completely.

**Comment by cstaavetti** [comment]
Ok, I see what you mean now, audio_stream_mp3.cpp should also return 0 when !active.
I read the current changes and in my opinion this PR does improve code quality and it does fix the related issues.
Once mp3's are fixed it should be ok, unless there is also some other format that needs updating.

**Comment by ellenhp** [comment]
Thanks! I'll update MP3 streams sometime today then get an official maintainer review after that. There does seem to be one last issue that I can only reproduce by selecting an ogg stream in the editor then clicking on the play/pause button as fast as I can. It's a crashing bug related to exhausting the ogg packet stream, then pausing, then playing. I'll make a new issue for it.

**Comment by fire** [comment]
When you're ready, post your pr for review. I'll try to gather the relevant parties.

**Comment by ellenhp** [comment]
I think this is ready now.

**Review by reduz — APPROVED** [review]

**Comment by bluenote10** [comment]
@ellenhp It looks like the change here (specifically to the `AudioStreamPlaybackResampled::mix` function) has broken the audio stream generator, which is a bit of a showstopper currently for moving to Godot 4. I did a small investigation and have a rough understanding why it is happening, but I lack the knowledge of the audio system and the idea behind this PR. If you are still around, it would be great to hear your opinion on some of the ideas I've laid out to fix it in https://github.com/godotengine/godot/issues/65155#issuecomment-1427003967!

**Pull request merged**
