### PR TITLE
Add done port to typecast visualscript node

### PR DESCRIPTION
**Pull request by swarnimarun**
Typecast visualscript node is similar to a conditional node thus requiring a done port to have unconditional sequence flow.
image

**Problem it should fix:**
Without a done port there would be no way to move the computation forward unconditional to the TypeCast check. Which means we could not replicate,
```
if condtion:
    do_something()
do_something_unconditionally()  # we could not reach it
```

### CODE REVIEW

**Comment by fire** [comment]
Why not chain a sequence node though?

**Comment by fire** [comment]
Sorry if I'm picky, this is probably the most used node in Godot visual script... So I don't want unnecessary things added to it.

**Comment by swarnimarun** [comment]
@fire we could do that but very honestly I believe that all nodes should be same or similar when managing a similar feature. That is conditionals...

Other condition nodes provide a done port for unconditional flow.

**Comment by swarnimarun** [comment]
So it's more about overall consistency rather than adding a new feature.

**Comment by swarnimarun** [comment]
Closing as maybe needs more discussion before, being rebased.

**Pull request closed without merging**
