### PR TITLE
Replace `sanity` with `safety` for checks

### PR DESCRIPTION
**Pull request by AThousandShips**
More inclusive language and something that has bothered me personally.

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Comment by RandomShaper** [comment]
Wouldn't this warrant a proposal? Well, unless it has already been discussed somewhere.

**Comment by AThousandShips** [comment]
It has been discussed in chat, and it is a common industry practice

**Review by akien-mga — APPROVED** [review]
I agree with the change, there's no loss of meaning and it's less problematic.

**Comment by RandomShaper** [comment]
Well, it it's been decided, it's been decided. I'll just abide by it. I don't think my opinion will matter much at this point.

Now, if this is the route we want to take, I'd like to have some sort of style guide with banned terms, etc.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Pull request merged**
