### PR TITLE
SCons: Make ktx module require basis_universal

### LINKED ISSUE #80786: Cannot compile minimal Godot build after #76572
### Godot version

5444afae63f37cb4b890c781e5679a3b7ee5a392

### System information

Ubuntu 22.04 CI

### Issue description

After #76572, cannot compile Godot with this command

```
scons -j2 dev_build=yes target=editor use_asan=yes use_ubsan=yes linker=gold module_basis_universal_enabled=no module_bmp_enabled=no module_camera_enabled=no module_csg_enabled=no module_cvtt_enabled=no module_dds_enabled=no module_denoise_enabled=no module_enet_enabled=no module_etcpak_enabled=no brotli=no module_gltf_enabled=no module_gridmap_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_jsonrpc_enabled=no module_lightmapper_rd_enabled=no module_mbedtls_enabled=no module_meshoptimizer_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_msdfgen_enabled=no module_multiplayer_enabled=no module_noise_enabled=no module_ogg_enabled=no module_openxr_enabled=no module_raycast_enabled=no module_regex_enabled=no module_squish_enabled=no graphite=no module_text_server_adv_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_vorbis_enabled=no module_webp_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no
```
show error
```
 modules/ktx/texture_loader_ktx.cpp:318: error: undefined reference to 'ktxTexture2_TranscodeBasis'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.linuxbsd.editor.dev.x86_64.san] Error 1
```

### Steps to reproduce

Above

### Minimal reproduction project

Above

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #80786.

I gave wrong advice in #76572, ktx depends on basisu's transcoder (at least in our use of it). CC @acazuc

### CODE REVIEW

**Comment by fire** [comment]
Some build errors.

**Comment by akien-mga** [comment]
> Some build errors.

Could you detail further?

**Review by aaronfranke — APPROVED** [review]
Makes sense to me.

**Comment by fire** [comment]
I think it is ready to go, and I don't need to double approve.

**Pull request merged**
