### PR TITLE
Simplify core/array.h and core/array.cpp

### PR DESCRIPTION
**Pull request by Cradmon**
**Changes:**
- Update and add more descriptive comments,
- Format spacing for readability,
- Change variable names to be more explicit,
- Performance improvements in for and while loops.

### CODE REVIEW

**Comment by ibrahn** [comment]
Moving local variables out of loops is not an optimisation

**Comment by Cradmon** [comment]
I thought that taking a variable outside a loop would mean less memory allocations, initialisations and destructors being called. So a minimal performance increase.

**Comment by ibrahn** [comment]
> I thought that taking a variable outside a loop would mean less memory allocations, initialisations and destructors being called. So a minimal performance increase.

The short answer is: no

It does depend on the type you're dealing with, but like the vast majority of optimisation, without a concrete example and measurements, it's not a good idea.

Generally a variable should be declared in the scope that uses it, making code clearer and less open to mistakes,

**Comment by Cradmon** [comment]
I've reverted those particular changes, as they were based on untested assumptions.

**Comment by akien-mga** [comment]
As mentioned in https://github.com/godotengine/godot/pull/22997#issuecomment-494148821, we decided in today's PR review meeting ([logs](http://godot.eska.me/irc-logs/meeting/2019-05-20.log)) not to merge those changes in their current form for the time being. Thanks for the contribution nevertheless!

**Pull request closed without merging**
