### PR TITLE
Use `ui_cancel` instead of a hardcoded key in Popups

### LINKED ISSUE #75431: Popups close when hitting the Esc key, regardless of the input map
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

Currently, popups can be closed by using the Esc key. But this completely ignores the game's input map. IIRC popups used to have this closing behavior tied to the `ui_cancel` action, which I think made more sense. I'm guessing it's because of [this line](https://github.com/godotengine/godot/blob/1222d35cdd832b3d4dfd96722d746d312e69a9bb/scene/gui/popup.cpp#L39), as the Esc key is hardcoded there.

### Steps to reproduce

Create a Popup and open it. Even if the input map never references the Esc key, the popup can be closed by pressing the Esc key.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by ghost**
Fixed a bug where popups closed using the Escape key, instead of whatever keybind is mapped to "ui_cancel".

- Original Issue: #75431
- Files Changes: scene/gui/popup.cpp, line 39

_Production edit: Fixes #75431_

### CODE REVIEW

**Review by bruvzg — COMMENTED** [review]
Changes look fine. There are other types of dialog that are using hard-coded ESC to close, these should be changed as well:

[void AcceptDialog::_input_from_window(const Ref<InputEvent> &p_event)](https://github.com/godotengine/godot/blob/db77702177ba259d375dae3fb88473a8711c4faa/scene/gui/dialogs.cpp#L40)
[void Tree::_text_editor_modal_close()](https://github.com/godotengine/godot/blob/db77702177ba259d375dae3fb88473a8711c4faa/scene/gui/tree.cpp#L2964)

**Comment by AThousandShips** [comment]
You've added a "scons" file, that shouldn't be included

**Comment by AThousandShips** [comment]
Mixing `is_pressed` and `is_action_pressed` seems unnecessary

**Comment by KoBeWi** [comment]
Also use SNAME() with action name.

**Comment by YuriSizov** [comment]
As you will be making changes to this PR, make sure to amend the commit message. It should be short but descriptive and follow the same pattern other commit messages use. E.g. something like "Use `ui_cancel` instead of a hardcoded key in Popups" would be good. You can still reference the original issue in commit message's body, if you want.

**Comment by YuriSizov** [comment]
Superseded by https://github.com/godotengine/godot/pull/75538.

**Pull request closed without merging**
