### PR TITLE
Add HTTPClient unit tests

### PR DESCRIPTION
**Pull request by angel-721**
Fixes part of #43440

Tests:
- HTTPClient Instantiation
- query_string_from_dict
- verify_headers
- connect_to_host

Test has been compiled and run on my device. 
Device runs on Linux: Pop! OS 22.04

I hope to expand this with more features of HTTPClient but this checks the basic functionality to start with. Please let me know if there is any way I can improve or add on to this test.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks for the contribution!

I amended the PR directly to squash the commits and fix remaining style issues.

**Comment by Calinou** [comment]
I get some errors when running the tests locally:

```
❯ bin/godot.linuxbsd.editor.x86_64 --test -sf="*http*"  
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
ERROR: Invalid HTTP header at index 0: empty.
   at: verify_headers (./core/io/http_client.cpp:103)
ERROR: Invalid HTTP header at index 0: String must contain header-value pair, delimited by ':', but was: InvalidHeader
   at: verify_headers (./core/io/http_client.cpp:104)
ERROR: Invalid HTTP header at index 0: String must contain header-value pair, delimited by ':', but was: :
   at: verify_headers (./core/io/http_client.cpp:104)
===============================================================================
[doctest] test cases: 4 | 4 passed | 0 failed | 776 skipped
[doctest] assertions: 9 | 9 passed | 0 failed |
[doctest] Status: SUCCESS!
```

When calling methods with values that you *know* are invalid, I suggest surrounding those calls with `ERR_PRINT_OFF;` and `ERR_PRINT_ON;`.

**Review by akien-mga — APPROVED** [review]
Seems good to me as a start.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
