### PR TITLE
BPTC support

### PR DESCRIPTION
**Pull request by elasota**
Adds BPTC import and enables it on PC.  Because BPTC's use cases are a bit unusual compared to existing formats, adds some options:

Renames the "Compress" HDR mode to "LDR Fallback" and adds a new option, "RGBE Fallback", which uses RGBE9995 on platforms without compressed HDR texture support instead of compressed LDR formats, which basically means "always use the most compact supported HDR format."

(Better option for mobile and sub-D3D11 PC is usually RGBA ETC2/DXT5 with bias in the alpha channel, but doing that requires a shim in the pixel shader, so it's non-trivial to port.)

Introduces the concept of a "fallback" pseudo-feature that's always available (which seems like a less-messy alternative to adding an "rgbe" feature or something), and exporter feature priorities, so exporters can exclude export items if it thinks one is the best for the platform.  This is used by the "no BPTC fallbacks" option, which prevents S3TC and RGBE fallbacks from being included when there is a BPTC texture, essentially requiring the feature in exchange for reducing build size.

Adds mipmapping support for HDR textures.

Adds "no BPTC if RGB" flag to import options, which makes it use S3TC if the texture has no alpha (VRAM/quality tradeoff).

Fixes a crash bug where RasterizerStorageGLES3::texture_get_data on PC requests bad write offsets if the texture is decompressed, caused by computing data size using the texture format (which is still the compressed type) instead of the decompressed format, which causes a massive OOB write.  (Repro: Force bptc_available to false and assign a BPTC texture to a sprite, the editor will probably crash.)

BPTC HDR formats still decompress to RGBA8 when it's unsupported, which is also not ideal.  I'd rather fix that in a followup though (plus there's the question of whether it should decompress to RGBE9995 or RGBHalf, and whether that should be platform-specific).

### CODE REVIEW

**Comment by elasota** [comment]
I can break off the crash fix and mipmapping changes if that makes things easier, but adding BPTC is really dependent on both, and I don't think the workflow for it is good without the config additions.

**Comment by akien-mga** [comment]
@reduz said on IRC "that PR is actually very good" and that he'd merge it, so we're almost there :)

I just have a few nitpicks:
- Please squash the commits together, formatting fixes should be included directly in the original commit
- Please add the relevant license file to `thirdparty/cvtt/` and please document origin, version, license and integration process in `thirdparty/README.md` (see how it's done for other thirdparty projects - entries ordered alphabetically).
- Please also add relevant copyright notice to `COPYRIGHT.txt` following the same style and alphabetical ordering of file paths.

**Comment by elasota** [comment]
Yeah was trying to get the checks green before squashing.  Will fix that and the rest in a sec.

**Comment by elasota** [comment]
Updated legal notices, squashed, fixed a minor oversight: `shrink_x2` RGBE9995 support was missing, added it.

**Comment by akien-mga** [comment]
Awesome, thanks!

**Pull request merged**
