### PR TITLE
Fix key mapping for `XK_KP_Delete` key

### LINKED ISSUE #86156: Wrong key mapping for XK_KP_Delete key
### Tested versions

Reproducible in all Godot 4.x.y versions.

### System information

Linux - All Godot 4.x.y versions

### Issue description

Numeric keypad `XK_KP_Delete` key is wrongly mapped to `KP_PERIOD` instead of `KEY_DELETE` in source code file [`./godot/platform/linuxbsd/x11/key_mapping_x11.cpp` @ line 91](https://github.com/godotengine/godot/blob/aa5b6ed13e4644633baf2a8a1384c82e91c533a1/platform/linuxbsd/x11/key_mapping_x11.cpp#L91C39-L91C39). That block of code corresponds to the key mapping of numeric keys when numlock is on, and so only `XK_KP_Decimal` is correct (and it is present [@ line 90](https://github.com/godotengine/godot/blob/aa5b6ed13e4644633baf2a8a1384c82e91c533a1/platform/linuxbsd/x11/key_mapping_x11.cpp#L90C4-L90C4), one line above the problematic one).

`XK_KP_Delete` mapping from line 91 should be moved a few lines down (under [XK_KP_INSERT mapping @ line 107](https://github.com/godotengine/godot/blob/aa5b6ed13e4644633baf2a8a1384c82e91c533a1/platform/linuxbsd/x11/key_mapping_x11.cpp#L107C2-L107C42)), where the numeric keypad keys are mapped for the case when numlock is off (see [comment @ line 106](https://github.com/godotengine/godot/blob/aa5b6ed13e4644633baf2a8a1384c82e91c533a1/platform/linuxbsd/x11/key_mapping_x11.cpp#L106)) and it should look like this: `xkeysym_map[XK_KP_Delete] = Key::KEY_DELETE;`.

This bug affects all X11 based systems and it breaks the code editing workflow for programmers used to move cursor / insert / delete with the numeric keypad control keys (arrows, home / end, page up / down, insert / delete).

### Steps to reproduce

* Ensure NumLock is off
* Write something in the code editor and try to delete using DEL key from numeric keypad
* DEL from numeric keypad doesn't work, character under cursor is not delete as expected

### Minimal reproduction project (MRP)

No MRP required, the issue manifests itself all the time when using the code editor.

### PR DESCRIPTION
**Pull request by gregdebonis**
Fixes #86156

### CODE REVIEW

**Review by deralmas — APPROVED** [review]
Seems pretty trivial to me.

**Comment by AThousandShips** [comment]
Didn't apply a cherry pick to this as I'm unsure if we should keep the current behavior or not in past versions, but if safe do feel free to add it, just wasn't sure

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
