### PR TITLE
Mono: Added generic methods for ResourceLoader.Load

### PR DESCRIPTION
**Pull request by exts**
Added a few QoL generic methods to PackedScene and ResourceLoader (as well as the GD.Load alias). Now you can do the following:

```
var pc = ResourceLoader.Load<PackedScene>("path/to/resource");
//var pc = GD.Load<PackedScene>("path/to/resource");
var pcInstance = pc.Instance<CustomNodeType>();
```

These are used a lot and it's much cleaner with generics instead of type casting everything. Inline with GetNode\<T>() and those other methods.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Is it necessary to create a `SomethingExtensions.cs` file for each of these small things?

For small things where we're only adding one function, I would vote for placing these classes next to each other in one file, perhaps called `Extensions.cs`.

**Comment by neikeq** [comment]
>``` C#
>var pc = ResourceLoader.Load<PackedScene>("path/to/resource");
>//var pc = GD.Load<PackedScene>("path/to/resource");
>var pcInstance = pc.Instance<CustomNodeType>();
>```

I don't really see the benefit here. How is this better than:

``` C#
var pc = ResourceLoader.Load("path/to/resource") as PackedScene;
//var pc = GD.Load("path/to/resource") as PackedScene;
var pcInstance = pc.Instance() as CustomNodeType;
```

or:


``` C#
var pc = (PackedScene)ResourceLoader.Load("path/to/resource");
//var pc = (PackedScene)GD.Load("path/to/resource");
var pcInstance = (CustomNodeType)pc.Instance();
```

The reason for adding it to common methods in Node was that they were commonly used in one-liners. I don't think that's the case here, am I wrong?

**Comment by exts** [comment]
> The reason for adding generic alternatives for common Node methods was that they were commonly used in one-liners.

Those are very common in one liners as well.

**Comment by exts** [comment]
I'd say an RPG (or any game that uses some form of item spawner) would be a good example of when you'd see an increase of single liners for Load<T> and Instance<T>. Personally I'm all for generic methods on most methods that make sense and this is on par with GetNode<T> in how frequent I use it in projects. With that said, if you don't find it useful that's fine, but I don't see any downsides to adding it either.

**Comment by neikeq** [comment]
> Those are very common in one liners as well. Here's an [example](https://github.com/exts/godotsharp-shooter/blob/master/Application/GameScene.cs) from a recent game I've wrote.

Could you paste an example? I cannot find any one-liner in that file. To clarify, I mean code like `GetNode<Type>("...").DoSomething()` or `GetNodeOrNull<Type>("...")?.DoSomething()`. I don't see anything similar.

Thanks for letting me know about Tenacious. I was looking for Godot C# videos/streams. It's useful to see how people use it to find out what can be improved.

**Comment by exts** [comment]
@neikeq oh to that extent, no I don't have any examples that I could show you right now.

**Comment by neikeq** [comment]
But what's is the use case for this? What do these methods better than a cast?

In the case of `GetNode`, it's common to access a member directly on the returned value, like `GetNode(...).AddChild(...)`. When the member is declared in a derived class, a cast is necessary, which is annoying and not very readable because you have to surround with parenthesis: `((Node2D)GetNode(...)).Position` or `(GetNode(...) as Node2D).Position`. That's why the generic methods were added, to simplify it: `GetNode<Node2D>(...).Position`.

I've never seen any code that access a member on the returned value of instance, because that would mean you are not added it as child to any other node, which will cause a leak.

In the case of load, I'm not so sure, but it must be very uncommon at best, because loading resources has its overhead.

What's the problem that these generic methods solve?

**Comment by LaBlazer** [comment]
@neikeq Here's an example https://github.com/LaBlazer/stylized-planet-generator/blob/csharp/main.cs#L111

**Comment by neikeq** [comment]
@LaBlazer There is a leak in that line. Like I mentioned before, you're instancing a node but you're not controlling its lifetime, either by adding it as a child of another node, or freeing it manually.

That being said, I can understand now that it can be useful for `ResourceLoader.Load` to have a generic alternative that does the cast, so I'm fine with adding this one. However, I still don't see the purpose of doing the same with `PackedScene.Instance`.

**Comment by exts** [comment]
Alright, going to close this PR then and stick w/ c# extensions.

**Comment by neikeq** [comment]
In my last comment I said I'm fine with doing this for `ResourceLoader.Load`. You can re-open the PR with those changes if you want.

**Comment by exts** [comment]
Alright, it's saying I force-pushed or recreated the repo (after rebasing) how do I fix it with https://github.com/exts/godot/commit/cdb4ae471b6aeb0f1afacae3dd42774660d8f133

**Comment by exts** [comment]
Aha, fixed it.

**Pull request merged**
