### PR TITLE
Fix GPUParticles2D emission offset in global coords

### PR DESCRIPTION
**Pull request by floppyhammer**
Fixing https://github.com/godotengine/godot/issues/56892.

### CODE REVIEW

**Comment by reduz** [comment]
This looks OK but it needs to be rebased, as 2D mode is now a bool.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This looks OK but it needs to be rebased, as 2D mode is now a bool.

**Comment by floppyhammer** [comment]
@reduz Done.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
