### PR TITLE
Remove quotes in string autocompletes from language server

### PR DESCRIPTION
**Pull request by DylanMurphey**
Potential fix for #48436 

This may go too far or not far enough, but it is a fix for a long-standing issue with the language server's handling of string autocompletes.

https://user-images.githubusercontent.com/58610593/234543656-bc25e419-edc7-40d7-9a96-a824664d114a.mp4

### CODE REVIEW

**Comment by akien-mga** [comment]
Won't this break the GDScript editor?

**Comment by DylanMurphey** [comment]
Hey, I'm sorry to be annoying! Two notes:
1. Upon testing, my original pull request actually doesn't break the original functionality, I am not sure why.
2. I have committed an additional check to handle both cases of internal/external editor to remain in line with the original intent of the code.

If this is still no bueno somehow, that's fine, but I figured it's worth trying to get a fix in for this issue.

**Comment by DylanMurphey** [comment]
Hi, the clang formatting issue has been fixed, can I get this approved again? Thanks.

**Comment by adamscott** [comment]
Hi @DylanMurphey! Thanks for your first PR! And thanks for the interest in the Godot project.

Sorry if it has been a long time without a comment of our part. The GDScript team is in reorganization and I only saw your PR today, as we are in a 4.1 release bugfixing rush.

Your fix would work. But your fix would be the first time in the codebase that the entered code would be influenced by the fact that the used checked the "use external editor" parameter. The parameter makes sense for opening or not files, but it may happen that users open quotes in the editor even if they checked the "use external editor" box. Then, there wouldn't be any quotes and the string would be broken.

I agree that a fix would be better than no fix, but your fix would introduce another issue.

I think the fix must be made instead in the LSP part of the code, and to force the unquoting there. But it's easier said than done.

Thank you again for your time. Don't hesitate to come chat with us in [the developer chat](https://chat.godotengine.org/) (there's a [GDScript channel](https://chat.godotengine.org/channel/gdscript) too!) if you have any questions. We could try to find a solution there.

**Pull request closed without merging**
