### PR TITLE
Export shape settings to CollisionShape and CollisionShape2D

### LINKED ISSUE #416: Exporting Shape Settings to CollisionShape2D
Hey there,
I have created a mockup for a simple ui enhancement. At the moment the shape settings are very hidden in the shape resource itself. You need to open the shaperesource to adjust the shape settings. It took me about 3 month to discover this. Before I always adjusted the shape via the nodes scale values, which resulted in very bad physics behavior.

In this screenshot I show how this can be exported to the main CollisionShape2D node. Depending on which shape is selected the appropriate shape values are shown.
I also thought if maybe removing the scale vector from that node, but I don't know if that should be done, or to just set it inactive or something like that.

collisionshape_ui_enhancement

### PR DESCRIPTION
**Pull request by ghost**
And those lines, are a workaround to make possible edit range properties by dragging.
- [collision_shape_2d.cpp](https://github.com/godotengine/godot/blob/7999b07e4f01e6e247fa10f39d04ebdbe121c415/scene/2d/collision_shape_2d.cpp#L49-L51)
- [body_shape.cpp](https://github.com/godotengine/godot/blob/7999b07e4f01e6e247fa10f39d04ebdbe121c415/scene/3d/body_shape.cpp#L53-L55)

Closes #416.

### CODE REVIEW

**Comment by akien-mga** [comment]
For the reference:

> \<reduz\> Akien, will most likely merge that after changing how data is stored
\<reduz\> Akien, need to move shape storage from CollisionObject to the shape nodes

**Comment by TheHX** [comment]
I'm a bit confused. This PR just make the `CollisionShape` and `CollisionShape2D` show a copy of the shape properties in the Inspector, and the copied properties usages are set to `PROPERTY_USAGE_EDITOR`, this way the exposed settings aren't saved with the node properties, only in the shape resource.

**Comment by reduz** [comment]
I'm still not exactly sure why this is an improvement, is it really that bad to go into the shape to check the parameters?

**Comment by akien-mga** [comment]
Discussed it again with @reduz, he's still not convinced about the UI change, so I guess it won't be merged.

**Pull request closed without merging**
