### PR TITLE
Remove blending features from AnimationPlayer

### LINKED ISSUE #5952: Remove blending feature `Default Blend Time` from AnimationPlayer
### Describe the project you are working on

Stabilization for Godot animation features

### Describe the problem or limitation you are having in your project

See also
- https://github.com/godotengine/godot/issues/70207

image

I have tried to apply the same blending algorithm as AnimationTree to AnimationPlayer, but have encountered some problems. 

First, the new AnimationTree blending algorithm has a reference value as "rest" or "reset" in case the blend value does not exist. However, for example, if you set a BlendTime of 0.5s for the AnimationPlayer and play a new animation, the animation will start from the reference value. If this BlendTime is intended for something like a crossfade, it is necessary to make a special case for the first animation or make some other method.

Another problem is that this AnimationPlayer blending has the potential to blend animation with itself. **Not only is it the same animation, but it is also the same animation "cache".** This causes confusion about playback position and direction. Currently, this is manifesting as a problem with the animation playback button not working correctly when spamming it with BlendTime set.

https://user-images.githubusercontent.com/61938263/208279090-9165c9ca-683e-4eb9-b344-ce16fe52fa53.mp4

Moreover, AnimationPlayer blending is causing code duplication with AnimationTree (currently, the old blending algorithm remains).

For the above reasons, I propose to remove blending feature from AnimationPlayer. By the way, Capture mode is not an issue here, so it can remain.

**If this functionality is removed, it should not be a problem because there are already features that cover it as AnimationTree and AnimationStateMachine. And that is what should generally be used.**

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It removes duplicated code and makes the behavior more stable.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

To begin with, Godot 3 and 4 animations are already incompatible.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

AnimationPlayer is in the core

### LINKED ISSUE #70207: AnimationPlayer blending and AnimationTree blending are inconsistent
### Godot version

4.0.dev

### System information

any

### Issue description

The AnimationTree is now blending tracks based on Rest or RESET value by #57675. However, I missed that the AnimationPlayer also has a blending, so currently which is not consistent with the AnimationTree. This can cause penetration in the transitions of the 3D model posing.

https://user-images.githubusercontent.com/61938263/208256319-84aec80a-7dd3-40b2-8254-791aa1785dfc.mp4

### Steps to reproduce

Use default blend time in AnimationPlayer

### Minimal reproduction project

[anim_player_blending.zip](https://github.com/godotengine/godot/files/10252447/anim_player_blending.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
See also
- #70207
- https://github.com/godotengine/godot-proposals/issues/5952

AnimationPlayer has a blending feature, but it is difficult to make it consistent with AnimationTree's new blending algorithm. Also, there is a lot of code duplication between AnimationPlayer and AnimationTree, which reduces maintainability and stability.

By removing them, AnimationPlayer will have a simple and straightforward implementation, and advanced use cases such as blending can be handled by AnimationTree and AnimationStateMachine, which make us to be able to separate use cases clearly. And we should focus on stabilizing behevior and improving the usability of StateMachine.

I guess the code could be simplified further than this PR, but for now I will keep the changes to a minimum. We will be able to refactor it later if necessary.

**If this feature is removed, it should not be a problem because there are already features that cover it as AnimationTree and AnimationStateMachine. And that is what should generally be used.**

By the way, Capture Mode is not a problem here, so it will remain. No worries.

Closes #70207
Closes https://github.com/godotengine/godot-proposals/issues/5952

### CODE REVIEW

**Comment by fire** [comment]
I support removing the duplicated blending code. There are two sets of blending and the animation tree is the main one. So it makes sense to remove the animation player duplicate.

**Comment by reduz** [comment]
There is no chance on this happening, way too many users use this workflow. Once something major is there, you cause a lot of pain to users if you want to remove it. Either some code deduplication is done to reuse it between nodes or this has to be left as is.

**Comment by TokageItLab** [comment]
I assume that some few users are using this, but obviously it is a territory invasion to have this feature in AnimationPlayer.

The Transform3D tracks do not blend well and the AudioTrack blending is inconsistent. I tried to make the blending consistent between AnimationPlayer and AnimationTree with the duplication, but the accumulator was not working properly and I gave up. Also, it requires many hacks in many places to avoid blending with itself or with void, so I am not very inclined to keep this up.

It may be possible to keep this feature as is, but no one can maintain it and it is a deprecated feature in my opinion.

**Comment by fire** [comment]
@reduz if you wish, it can be marked deprecated for godot 4, but I am not sure we are able to restore the animation player blending workflow to 100% working. @TokageItLab's opinion is written in this discussion.

**Comment by smix8** [comment]
I personally use the AnimationPlayer blending all the time in plenty of projects for simple stuff that does not justify using a complex AnimationTree or would add so much unnecessary complexity that comes with working with scripts and AnimationTree that it becomes a nuisance. I am fine with using an AnimationTree for more complex stuff but I would prefer if at least simple blending would stay as an option in AnimationPlayer.

**Comment by TokageItLab** [comment]
Will be superseded by https://github.com/godotengine/godot-proposals/issues/5972

**Pull request closed without merging**
