### PR TITLE
Readd CanvasLayer::get_world_2d as deprecated

### PR DESCRIPTION
**Pull request by RandomShaper**
introduced on 9e7cee2ceb1a963c1da2c21013adf7d616412d3c

~~No need to cherry-pick. A dedicated PR for 3.0 will contain the original fix + this compat keeper (edit: #21114 ).~~

This code is donated by an anonymous party,

### CODE REVIEW

**Comment by akien-mga** [comment]
Even with this change, compatibility is still broken though. If you have a Godot 3.0.x project that uses `get_world_2d()`, you get an error and the intended logic no longer works. I doubt @hpvb would let this through.

The compat breakage is ok for the master branch (as keeping compatibility would be quite a hassle, and there are other similar breakages already), but for 3.0 it's going to be difficult.

CC @hpvb

**Comment by RandomShaper** [comment]
Anyway, I'll keep searching for a workaround/fix for 3.0 that doesn't involve a shared `World2D` for `CanvasLayers`. In the end, that behavior change may be too unexpected.

**Comment by akien-mga** [comment]
Note that I'm not saying this / #21114 should not be done, just raising some reservations. I'd like to have @hpvb's opinion on this, who ultimately decides what gets into 3.0 or not, and is the Keeper of Stability for that branch (and does it much better - but then also much stricter - than I did with 2.1 :P).

**Comment by hpvb** [comment]
Nice! Thanks guys.

**Pull request closed without merging**
