### PR TITLE
Fix theming of doc background

### PR DESCRIPTION
**Pull request by Chaosus**
bug

### CODE REVIEW

**Comment by bruvzg** [comment]
This essentially makes all #57111 changes completely useless and will cause full RTL context recreation on each resize.  #57111 was more of a workaround, not a proper fix, I still plan to add one optimization to the `TextServer`, but to do it properly we should have some way to detect what was changed in the theme, instead of always sending `NOTIFICATION_THEME_CHANGED`.

Anyway, it's probably better to do this in the `EditorHelp::_notification -> NOTIFICATION_THEME_CHANGED` instead.

**Comment by akien-mga** [comment]
Maybe the `project_settings_changed` signal can be used to react to actual theme configuration changes and not GUI updates due to resize/minsize change.

**Comment by bruvzg** [comment]
> Maybe the project_settings_changed signal can be used to react to actual theme configuration changes and not GUI updates due to resize/minsize change.

Margin update should be done on resize, since it depends on the control size, but the same function is used for both margin and generic theme changes.

> but to do it properly we should have some way to detect what was changed in the theme, instead of always sending NOTIFICATION_THEME_CHANGED

For some reason, I was thinking doing it will require a lot of changes, but seems like it's really easy to do by adding a few lines of code. So I probably will add this, and additional `TextServer` methods to change font and font size without recreating text buffer on a next Monday/Tuesday. And revert #57111, since it won't be necessary anymore (this should fix this issue as well).

**Comment by Chaosus** [comment]
@bruvzg Thanks for pointing that out, I've fixed it by adding an additional parameter to force updating a theme that activates only at `NOTIFICATION_THEME_CHANGED`.

**Review by bruvzg — APPROVED** [review]

**Pull request merged**
