### PR TITLE
Use asynchronous shader compilation and cache in the editor if requested

### PR DESCRIPTION
**Pull request by Calinou**
This provides more consistent behavior between the editor and running project. Documentation for the project setting was also improved.

This closes https://github.com/godotengine/godot-proposals/issues/3594.

### CODE REVIEW

**Comment by clayjohn** [comment]
cc @RandomShaper

**Review by RandomShaper — APPROVED** [review]
Somehow I'm still not super sure this is the right thing to do, but, let's be honest, I'm still not able to give a strong reason why or suggest a robust alternative. So, maybe this is just fine in the end. In case someone needs further control or something, the requirement will arise and we'll be able to act upon it.

**Comment by akien-mga** [comment]
Thanks!

**Comment by tinmanjuggernaut** [comment]
@Calinou My hero!

**Pull request merged**
