### PR TITLE
Fix gizmo on top material option having no effect

### LINKED ISSUE #44077: The "on_top" parameter of EditorSpatialGizmoPlugin.create_material has no effect
Godot 3.2.3
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

I'm making a plugin where I show a custom wireframe gizmo with `EditorSpatialGizmoPlugin`. I need it to be shown on top, so I set the `on_top` parameter to `true` in `create_material`. However it does not have any effect.

image

With wireframe mode turned on, you can see where the gizmo is supposed to be:
image

MRP:
[GizmoOnTop.zip](https://github.com/godotengine/godot/files/5639077/GizmoOnTop.zip)
Check the plugin is enabled in ProjectSettings, open `main.tscn`, select the `MeshInstance`.

### PR DESCRIPTION
**Pull request by stevenjt**
This fixes https://github.com/godotengine/godot/issues/44077

I found that the `get_material` function in EditorNode3DGizmoPlugin is changing the gizmo materials directly to add and remove the disable depth test flag to enable/disable them for the 'x-ray' visibility state before returning them. This is causing the original state of the disable depth test flag to be lost so materials that were created with the on_top parameter are never returned with the disable depth test flag enabled when in the regular 'visible' visibility state.

To fix this I have updated `get_material` to change the disable depth test flag on duplicate versions of the gizmo
materials when the gizmo is set to use the 'x-ray' / `ON_TOP` visibility state if the flag is not already set or otherwise return the stored materials without change.

(Since StandardMaterial3D is RefCounted these duplicates should be freed automatically when later unreferenced when the gizmo is redrawn.)

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/b2f425fe680d1ed5d5b5fa9ae289ae93fd294607), it works as expected on https://github.com/godotengine/godot/issues/44077#issuecomment-2035477110. Code looks good to me.

Toggling x-ray visibility on default gizmos still works.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by donn-xx** [comment]
Trying this in my plugin: `create_material("small_cursor_shape", Color.RED, false, true)` 
Not sure what it's meant to do, but my expectation is to see the red (sphere) *through* the geometry in the way. However it's hidden.

Zylann's workaround still better:
```
func create_on_top_material(name: String, color := Color.WHITE,
		bmode := StandardMaterial3D.BLEND_MODE_ADD):
	var material := StandardMaterial3D.new()
	material.set_blend_mode(bmode)
	material.set_shading_mode(StandardMaterial3D.SHADING_MODE_PER_VERTEX)
	material.set_flag(StandardMaterial3D.FLAG_DISABLE_DEPTH_TEST, true)
	material.set_albedo(color)
	material.render_priority = 100
	add_material(name, material)
```

Godot v4.4.dev (61598c5c8) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

**Comment by stevenjt** [comment]
@donn-xx in your `create_material` example does it work when the node using the gizmo is selected? Gizmos have different material instances created for selected and unselected states. The on top effect is only applied to the selected material instance: https://github.com/godotengine/godot/blob/61598c5c88d95b96811d386cb20d714c35f4c6d7/editor/plugins/node_3d_editor_gizmos.cpp#L928

**Comment by donn-xx** [comment]
> he selected material instanc
Selected and unselected. The billboard simply changes (in some way) how it appears.

How do we setup the selected and unselected materials?

Also, imo, I need the "icon material" (at least) to be visible always, so that it's visible in the scene (in the editor). It would be great to be able to select the node by clicking on the billboard/icon too. (Otherwise, why bother with it all? May as well select the node in the tree.)

**Pull request merged**
