### PR TITLE
Add missing parameters to documentation for `EditorProperty.property_changed` signal

### LINKED ISSUE #65059: `property_changed` signal on `EditorProperty` has wrong signature in documentation.
### Godot version

3.5.mono.stable

### System information

Windows 10

### Issue description

Source code emits four arguments (String, Variant, String, boolean)

https://github.com/godotengine/godot/blob/b0ab7ac446100d490a5ce14c538e2bc88ade65cf/editor/editor_inspector.cpp#L106-L111

Documentation says only two arguments

https://docs.godotengine.org/en/stable/classes/class_editorproperty.html

image

### Steps to reproduce

See above.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Atlinx**
Fixes #65059

### CODE REVIEW

**Comment by YuriSizov** [comment]
You need to squash your commits.

**Comment by Atlinx** [comment]
> You need to squash your commits.

Done! :D

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
