### PR TITLE
Add HTC Vive focus XR manifest metadata

### LINKED ISSUE #25: Khronos Library on Vive Focus 3
Hi. Good news is that I've been able to confirm that the new Khronos library does work on the Vive Focus 3, but only after adding the following line to the android manifest and only with the renderer  set to gl_compatibility.

`<category android:name="com.htc.intent.category.VRAPP" />`

Without the manifest line, the headset starts the application in 2D and upside down.
I added the line under the current one for Oculus in the template and it works.

I've noticed a few issues with the current XR Tools Demo such as the skybox not rendering in 3D and the gravity demo going mental, but I'll raise those issues under that project.

Great work getting it going though!
Thanks

### PR DESCRIPTION
**Pull request by m4gr3d**
Fixes https://github.com/GodotVR/godot_openxr_loaders/issues/25

### CODE REVIEW

**Review by BastiaanOlij — APPROVED** [review]
I think we need to look at an alternative solution that allows us to more easily add entries to this, maybe as export settings. We won't be able to keep up as more headsets come out.

But for now this will at least solve the immediate issue.

**Comment by m4gr3d** [comment]
@BastiaanOlij Prior to submitting this change, can we get confirmation from HTC that this is the correct tag?
With the addition of the KHR tag, I'm wondering if they may consider deprecating their tag in favor of the KHR one.

**Comment by BastiaanOlij** [comment]
> @BastiaanOlij Prior to submitting this change, can we get confirmation from HTC that this is the correct tag? With the addition of the KHR tag, I'm wondering if they may consider deprecating their tag in favor of the KHR one.

I've sent a message to my contact over at HTC, we'll see what comes back.

**Comment by m4gr3d** [comment]
@BastiaanOlij Any updates from the HTC contact?

**Comment by BastiaanOlij** [comment]
> @BastiaanOlij Any updates from the HTC contact?

Sadly no reaction.

**Comment by m4gr3d** [comment]
> > @BastiaanOlij Any updates from the HTC contact?
> 
> Sadly no reaction.

Let's proceed with the update then.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
