### PR TITLE
Filter groups and categories from autocompletion

### LINKED ISSUE #76919: Weird things appear in autocomplete
### Godot version

4.0.2

### System information

Ubuntu 22.04.1 LTS

### Issue description

So far I've found these ones:

Screenshot from 2023-05-10 17-56-42
Screenshot from 2023-05-10 18-01-02

But there are likely more like them. They are invalid, at least in the context I encountered them here (at the beginning of a regular line of script)

### Steps to reproduce

Type `Anchor` in the code editor.

### Minimal reproduction project

N/A

### LINKED ISSUE #82785: Built-in script section appears in autocompletion
### Godot version

4.2 f5696c3

### System information

Windows 10 x64

### Issue description

image

### Steps to reproduce

1. Add node
2. Attach a built-in script
3. Add child node
4. Add script to the child node
5. In some method write `get_parent().bui`

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by HolonProduction**
Fixes #82785
Fixes #76919

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]
Makes sense to me.

We should probably pre-define `PROPERTY_USAGE_SUBGROUP | PROPERTY_USAGE_GROUP | PROPERTY_USAGE_CATEGORY` at some point. I think we use it everywhere now.

**Comment by YuriSizov** [comment]
Oh, I didn't mean in this PR and not even in GDScript module. We use it everywhere in the codebase. It should be added as a pre-defined constant in the enumeration itself, I think. But not here, not in this PR.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.1.

**Pull request merged**
