### PR TITLE
Store Object signals in a HashMap rather than a VMap

### LINKED ISSUE #69874: Godot freezes after reloading scenes with many deeply nested nodes
### Godot version

v4.0.beta8.official.45cac42c0

### System information

Linux, Vulkan API 1.3.224 - Using Vulkan Device #0: Intel - Intel(R) Iris(R) Plus Graphics 655 (CFL GT3)

### Issue description

After creating a scene with many deeply nested nodes, Godot takes longer and longer to unload and recreate the scene every time it is reloaded.

The scene in question consists of an 8-deep tree with 4 children per node (80,000+ nodes), although the issue starts becoming noticeable with 7-deep trees.

### Steps to reproduce

Clone the below PR and run the HLOD benchmarks from the root directory via:
`godot-4.0beta8-binary-name -- --run-benchmarks --include-benchmarks=rendering/hlod/*`

### Minimal reproduction project

https://github.com/godotengine/godot-benchmarks/pull/23

### PR DESCRIPTION
**Pull request by myaaaaaaaaa**
Fixes #69874

### CODE REVIEW

**Comment by akien-mga** [comment]
Can you share benchmark results to assess the gain?

**Comment by myaaaaaaaaa** [comment]
Sure, with the caveat that these numbers are from a debug build

Code:
```
extends Benchmark

func build_node(num_signals: int) -> Node3D:
	var mesh := ArrayMesh.new()
	var rt := MeshInstance3D.new()
	for i in num_signals:
		var n := MeshInstance3D.new()
		rt.add_child(n)

		# Implicitly connects a changed signal
		n.mesh = mesh

	return rt

func benchmark_signals():
	for i in [2,20,200,2000]:
		print()
		print("num_signals: ", i)
		var m := Time.get_ticks_usec()
		for j in 10: #More reliable timing
			build_node(i).free()
		print("%.3f ms" % ((Time.get_ticks_usec() - m) / 10 / 1e3))
```

Before: ( Using #72346 for consistent behavior, see that for details )
```
num_signals: 2
0.223 ms

num_signals: 20
1.612 ms

num_signals: 200
25.631 ms

num_signals: 2000
1421.480 ms
```

After: ( Note that scaling is now linear )
```
num_signals: 2
0.221 ms

num_signals: 20
1.368 ms

num_signals: 200
13.461 ms

num_signals: 2000
124.343 ms
```

**Review by Calinou — APPROVED** [review]
Tested locally (rebased against latest `master`), it works. I ran a few projects of mine without issue.

**Comment by reduz** [comment]
The only problem with this approach is that emission could be slower. It would be nice to benchmark this in exchange.

**Comment by akien-mga** [comment]
> The only problem with this approach is that emission (which is more critical than connection time) could be slower. It would be nice to benchmark this in exchange.

@myaaaaaaaaa Would you have time to do a quick test for this?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
