### PR TITLE
Implement inherits_script() for NativeScript and PluginScript

### PR DESCRIPTION
**Pull request by RandomShaper**
Just that. ~Now only `PluginScript` is missing an implementation.~

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @touilleMan to help with PluginScript.

Note that neither NativeScript nor PluginScript are likely usable in the `master` branch (and IIRC they'll likely both be removed once the extensions system is ready to replace them). But this implementation is needed for #51166 in the `3.x` branch so it can be developed for `3.x` and just merged in `master` to future proof.

**Comment by touilleMan** [comment]
regarding `NativeScript::inherits_script()` implementation, it seems `a.inherits_script(b)` means `Does script b inherits script a ?` which seems weird (given you read the method `a inherits script b`).

(my 2 cents: this method should be renamed or at least have some comments near it definition to explain in which order it is supposed to work... I the current state I personally can't say if it implementation is expected or not 😄 )

Regarding PluginScript implementation, base script information is provided during Script creation:
https://github.com/godotengine/godot/blob/b9d544b404bfcfbaf797b97b540961510595cd29/modules/gdnative/pluginscript/pluginscript_script.cpp#L286-L300

So I think we should be able to implement `inherits_script` by using the `PluginScript._ref_base_parent` field in a similar fashion `NativeScript::inherits_scripts` is implemented.

However I wonder why this need to be implemented on in each Script, it feels much simpler to have one default implementation in `Script` relying on `Script::get_base_script` (we would need to introduce a  `Script::get_script_class_name` which already exists in `NativeScript`, `PluginScript` and `GDScript`). Of course this would mean script names must be unique but I guess it's already the case given we register them in ClassDB anyway.

**Comment by RandomShaper** [comment]
Thank you very much, @touilleMan. I've fixed the inverted logic and implemented the function for PluginScript, both being based on the GDScript implementation.

Now, regarding the approach of doing it by name without having to have an implementation per type of script, I believe that makes sense and would also allow to do checks in hierarchies mixing different scripting languages, as long as that can happen.

However, maybe that would be better separately discussed. If the implementations I've added here are good, that would already be unblocking my current work.

**Review by touilleMan — APPROVED** [review]
lgtm

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
