### PR TITLE
Editor canvas item api rework

### PR DESCRIPTION
**Pull request by groud**
Rework of the Editor/CanvasItem API, this is a first step before a refactoring of the canvas item editor code. That should allow a customization of the way the editor "Gizmos" impact each node.
For example, it could disable the rect drawn it for nodes that do not need to be scaled, disable the rotation, etc...

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by reduz** [comment]
I personally dont like at all that these funtions are exposed to Control, CanvasItem, etc. When they are only used by the editor. Makes pretty confusing for users looking into the doc. 

I was going to suggest: 
1)  not binding them
2) If they definitely need to be bound (for undo/redo), then make them begin with _ so they are not exposed.

**Comment by groud** [comment]
I think they are needed for Undo/Redo, but they definity need to be hidden :)
I'll add the "_" before.

**Comment by groud** [comment]
Done.

**Comment by reduz** [comment]
this seems ok to me, but i think @akien-mga will want squash or something..

**Comment by Noshyaar** [comment]
This can be merged after squashing. :)

**Comment by groud** [comment]
Squashed ! :)

**Pull request merged**
