### PR TITLE
Avoid string allocations in AlphCompare

### PR DESCRIPTION
**Pull request by ghost**
Related to https://github.com/godotengine/godot/issues/13199, https://github.com/godotengine/godot/pull/14717

Without PR, one call of `ClassDB::get_api_hash` takes 24 ms on my machine, with the PR this goes down to 11 ms.

Details: the sort using `AlphCompare` is the main hit in `ClassDB::get_api_hash`:

pre-pr

`sort` is slow due to the string management in `AlphCompare::operator()`:

details

With PR, `sort` no longer rules the profiling:

with-pr

### CODE REVIEW

**Comment by reduz** [comment]
@akien-mga I don't remember why why didn't merge this one

**Comment by HummusSamurai** [comment]
IIRC from irc talks, remi said he didn't want it in beta2.

**Comment by reduz** [comment]
Ah yeah we were supposed to merge afterwards

**Comment by reduz** [comment]
OK guys, test and make sure nothing breaks

**Pull request merged**
