### PR TITLE
Update embree to 3.13.5

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Another library update. This one was kinda hard to do.

Some patches are removed, since those changes are already present in the current release.
Exceptions patches were reapplied. However, I'm kinda concerned about indexes in the patch file, since it may be not the accepted format.

I also have not tested it, despite the build process going well.

### CODE REVIEW

**Comment by fire** [comment]
Wow, I remember this was a bit hard to do.

**Comment by DeeJayLSP** [comment]
The only hard part IMO is generating the patch file.

**Comment by fire** [comment]
https://github.com/godotengine/godot/tree/master/thirdparty/oidn Oops I meant OIDN. The code needed to bake lightmaps.

**Review by akien-mga — COMMENTED** [review]
Looks pretty good! You also need to update `thirdparty/README.md` with the version and commit.

I'll test an official build with that PR to make sure it still builds on all x86_64 and arm64 targets.

**Comment by akien-mga** [comment]
BTW I see references upstream of embree now compiling with Emscripten (wasm32), and being supported on 32-bit Windows too. We might want to give those platforms a try to see if they can be made to work. (I think by default we'd probably still want to build Web templates without Embree because it's a big dependency for something most Web games won't be able to use, especially without the OIDN denoising, but having the possibility is nice.)

**Comment by DeeJayLSP** [comment]
> You also need to update `thirdparty/README.md` with the version and commit.

I was so focused on the patch file that I forgot about it, will do a force push ASAP.

**Comment by akien-mga** [comment]
I pushed an update to make sure that the `modules/raycast/godot_update_embree.py` script works:
- Changed it to checkout a specific Git tag - the tag is hardcoded in the file and should be updated whenever we push a new version.
- Updated some dates in generated files to match upstream.
- Applying the patch re-enabled `#define EMBREE_GEOMETRY_TRIANGLE` which was set explicitly in the `config.h`. I don't know if this is a default value that changed upstream, or if this is indeed something that is not defined by default but that we want defined in Godot (@JFonS).
- Remade the patch as it didn't apply properly for two files, notably due to wrongly having trailing whitespace removed.

**Comment by akien-mga** [comment]
I could build this PR on all platforms with x86_64 or arm64 targets so it seems good to go.
We'll see in the coming days or the next beta if there's no functionality regression.

I had a go at building for Emscripten, with this diff:
```diff
diff --git a/modules/raycast/SCsub b/modules/raycast/SCsub
index 20b05816e1..2a0b745234 100644
--- a/modules/raycast/SCsub
+++ b/modules/raycast/SCsub
@@ -87,7 +87,7 @@ if env["builtin_embree"]:
     env_thirdparty.disable_warnings()
     env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
 
-    if env["arch"] == "arm64" or env.msvc:
+    if env["arch"] != "x86_64" or env.msvc:
         # Embree needs those, it will automatically use SSE2NEON in ARM
         env_thirdparty.Append(CPPDEFINES=["__SSE2__", "__SSE__"])
 
diff --git a/modules/raycast/config.py b/modules/raycast/config.py
index 833ad50018..22fb278764 100644
--- a/modules/raycast/config.py
+++ b/modules/raycast/config.py
@@ -1,9 +1,9 @@
 def can_build(env, platform):
-    # Depends on Embree library, which only supports x86_64 and arm64.
+    # Depends on Embree library, which only supports x86_64, arm64, and wasm.
     if platform == "windows":
         return env["arch"] == "x86_64"  # TODO build for Windows on ARM
 
-    return env["arch"] in ["x86_64", "arm64"]
+    return env["arch"] in ["x86_64", "arm64", "wasm32"]
 
 
 def configure(env):
```

It builds fine for a number of files but eventually fails with:
```
In file included from thirdparty/embree/common/simd/sse.cpp:4:
In file included from thirdparty/embree/common/simd/sse.h:7:
In file included from thirdparty/embree/common/simd/../sys/intrinsics.h:15:
In file included from /home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/cache/sysroot/include/compat/immintrin.h:31:
/home/akien/Projects/godot/emscripten/emsdk/upstream/emscripten/cache/sysroot/include/compat/emmintrin.h:1141:19: error: always_inline function 'wasm_i32x4_make' requires target feature 'simd128', but would be inlined into function '_mm_set_epi32' that is compiled without support for 'simd128'
  return (__m128i)wasm_i32x4_make(i0, i1, i2, i3);
                  ^
1 error generated.
```

On the other hand I'm able to build Embree with Emscripten using their CMake config and these build commands:
https://github.com/embree/embree/blob/devel3/.gitlab-ci.yml#L48-L52

So we must be missing some defines for Emscripten. (Shouldn't be `__EMSCRIPTEN__`, this one is defined by the compiler.)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by aaronfranke** [comment]
This PR breaks compiling on Ubuntu 22.04 arm64. Compiling the latest master or the commit in this PR 5e4158eb4869427ac13a0fe57e9b688ea4c3b0f1 will fail with the below errors. Compiling with `scons module_raycast_enabled=no` works, and compiling the previous commit f16c5b564b569497d04deb965a4fd63b3ea2ab2f also works.

```
[ 28%] Compiling thirdparty/embree/common/sys/sysinfo.cpp ...
In file included from thirdparty/embree/common/sys/../simd/arm/emulation.h:12,
                 from thirdparty/embree/common/sys/intrinsics.h:13,
                 from thirdparty/embree/common/sys/sysinfo.cpp:5:
thirdparty/embree/common/sys/../simd/arm/sse2neon.h: In function '__m128i _mm_hadds_epi16(__m128i, __m128i)':
thirdparty/embree/common/sys/../simd/arm/sse2neon.h:6749:55: note: use '-flax-vector-conversions' to permit conversions between vectors with differing element types or numbers of subparts
 6749 |         vqaddq_s16(vuzp1q_s16(a, b), vuzp2q_s16(a, b)));
      |                                                       ^
thirdparty/embree/common/sys/../simd/arm/sse2neon.h:6748:33: error: cannot convert 'int64x2_t' to '__m128i' {aka 'int32x4_t'} in return
 6748 |     return vreinterpretq_s64_s16(
      |            ~~~~~~~~~~~~~~~~~~~~~^
      |                                 |
      |                                 int64x2_t
 6749 |         vqaddq_s16(vuzp1q_s16(a, b), vuzp2q_s16(a, b)));
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
thirdparty/embree/common/sys/../simd/arm/sse2neon.h: In function '__m128i _mm_hsubs_epi16(__m128i, __m128i)':
thirdparty/embree/common/sys/../simd/arm/sse2neon.h:6846:33: error: cannot convert 'int64x2_t' to '__m128i' {aka 'int32x4_t'} in return
 6846 |     return vreinterpretq_s64_s16(
      |            ~~~~~~~~~~~~~~~~~~~~~^
      |                                 |
      |                                 int64x2_t
 6847 |         vqsubq_s16(vuzp1q_s16(a, b), vuzp2q_s16(a, b)));
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by akien-mga** [comment]
It might need #70108, though it makes the build fail on Android and iOS ARM64...

It was ported from https://github.com/embree/embree/commit/82ca6b5ccb7abe0403a658a0e079926478f04cb1, and they don't seem to test/support Android, so their `EMBREE_ARM` define can likely be inferred to be only Linux aarch64 and macOS ARM64.

**Pull request merged**
