### PR TITLE
Upgrade Embree and enable ray packets

### PR DESCRIPTION
**Pull request by JFonS**
Minor patch upgrade. Enabling ray packets results in faster processing of ray streams (i.e. occlusion culling buffer updates) at the cost of slightly larger binary sizes.

The Embree library was originally only used in the CPU lightmapper, so we prioritized binary size over performance. Now that we rely on it for some performance-critical tasks, I think we can justify enabling ray packets.
 
On a purposefully heavy scene (Bistro exterior,  ~2.8M tris) and with 2048 rays per thread (default is 512),  enabling packet rays brings the occlusion update time from ~2.5ms to ~1.9ms, which is significant enough.

I'm not sure about official builds, but in my local `release_debug` builds (using clang and after stripping) I only see a ~2KB increase in size, which doesn't seem too bad.

In a similar note, we should take a look at building Embree for supported SIMD instruction sets, maybe by default or as a build option, depending on the performance gains and the binary size differences.

### CODE REVIEW

**Comment by jcostello** [comment]
Is this only for occlusion culling or for lightmaps too?

**Review by akien-mga — APPROVED** [review]
Buildsystem changes look good to me, feel free to merge if/when ready.

**Comment by Calinou** [comment]
> In a similar note, we should take a look at building Embree for supported SIMD instruction sets, maybe by default or as a build option, depending on the performance gains and the binary size differences.

I've [looked around a bit](https://github.com/embree/embree#readme). To me, it seems the ideal course of action would be to enable SSE4, AVX and AVX2 with run-time selection of the optimal ISA (only requiring SSE as a baseline). AVX512 requires using the Intel compiler and is only present on a handful of CPUs, so I wouldn't bother about it.

**Comment by JFonS** [comment]
Yes, that what a typical build of Embree does, but that will likely increase binary sizes a lot. Builds will include multiple versions of the BVH building and traversal code, one for each ISA.

This is not high priority, but something that would be nice to look into before 4.0 stable release. Depending on the binary size increase it might be a better idea to add an "Embree with all ISAs" build option and

**Comment by Calinou** [comment]
We could enable all possible ISAs for editor builds, and enable only the most compatible choices for export templates on desktop platforms. (I don't think small binary sizes are *that* important on desktop platforms nowadays.)

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Pull request merged**
