### PR TITLE
Fix Layout Restoration Issue by Moving Layout Properties Restoration Above Script Loading Check

### LINKED ISSUE #96381: Disabling `restore_scripts_on_load` will skip loading whole script editor layout
### Tested versions

4.3 and older

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Script editor has this condition at the beginning:
https://github.com/godotengine/godot/blob/61598c5c88d95b96811d386cb20d714c35f4c6d7/editor/plugins/script_editor_plugin.cpp#L3371-L3373
While it's supposed to stop scripts from being load at launch, it prevents restoring any layout property, like split offset or zoom (they are further down in the same function, e.g. https://github.com/godotengine/godot/blob/61598c5c88d95b96811d386cb20d714c35f4c6d7/editor/plugins/script_editor_plugin.cpp#L3447-L3449)

Settings unrelated to scripts themselves should be likely moved above the first condition.

### Steps to reproduce

1. Disable `text_editor/behavior/files/restore_scripts_on_load` editor setting
2. Open script editor
3. Change size of script list
4. Reload editor
5. Notice list size is reset

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by amanreddy77**
"Fix Layout Restoration Issue by Moving Layout Properties Restoration Above Script Loading Check"

This title highlights that the PR addresses the issue with layout restoration by modifying the order of operations in the set_window_layout function.

* *Bugsquad edit, fixes: #96381*

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please update the PR title to describe what this does

**Comment by amanreddy77** [comment]
> Please update the PR title to describe what this does

ok

**Comment by AThousandShips** [comment]
You first need to fix the style, and I can see if I can review this but it's not my area, but I will go over it tomorrow

For the style please see [here](https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html#using-clang-format-locally)

**Comment by amanreddy77** [comment]
> You first need to fix the style, and I can see if I can review this but it's not my area, but I will go over it tomorrow (to be clear it wasn't a "first you need to fix this" instruction, it was just part of the general way PRs are done and what they need to fulfill, and a bit of "hey this is advice for the future how we do things")
> 
> For the style please see [here](https://docs.godotengine.org/en/stable/contributing/development/code_style_guidelines.html#using-clang-format-locally)

Yeah I will follow and sorry I am still learning about this so......

**Pull request closed without merging**
