### PR TITLE
Added overloads of vector parameters for shader Trig functions.

### PR DESCRIPTION
**Pull request by RaXaR**
Affects issue #10562

### CODE REVIEW

**Comment by Noshyaar** [comment]
Would you mind removing whitespace characters in blank lines?

Also please use `git commit --amend` and `git push -f` to push further changes. Thanks for contributing! 
([PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#modifying-a-pull-request))

**Comment by RaXaR** [comment]
Not a problem, I removed the whitespace from the blank lines as requested.
Then ran ```git commit --amend``` and ```git push -f RaXaR master``` to send it to my fork.

Do I need to do this PR again?

**Comment by Noshyaar** [comment]
Thank you. That's fine. You don't have to redo the PR.

However, I've just noticed about double spaces in those lines you use for alignment. They cause clang-format errors.

**Comment by RaXaR** [comment]
Remove double-spaces, let's hope Clang's panties don't get in a knot again. :)

**Pull request merged**
