### PR TITLE
Added a new MIDIDriver class

### PR DESCRIPTION
**Pull request by marcelofg55**
New MIDIDriver class to handle MIDI hardware.
Also implements a new Input event class, InputEventMIDI.

Works with:
OS X using CoreMidi
Linux using ALSA
Windows using WinMM

MIDI events can be used on `_input(event):`, for example this is me playing two notes on my midi keyboard (printing the pitch and velocity):
screen shot 2018-07-14 at 12 18 00 pm

PD: This is only for receiving events from MIDI hardware, sending events to MIDI hardware is not implemented in this PR.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Should the InputEvent have different casing from the class name? `MIDI` vs `Midi`.

**Comment by Calinou** [comment]
We already have class names like HTTPRequest, so it should be MIDIPlayer.

**Comment by reduz** [comment]
As I mentioned many times, I don't think MIDI has any use case as engine core. 
The situations where something like this would be needed are so few, if any, that it makes more sense to support something like this ad a GDNative add-on than in the core engine.

**Comment by marcelofg55** [comment]
@aaronfranke @Calinou I've just renamed it to MIDIDriver

@reduz This doesn't implements any MIDI playback code though. This adds support for MIDI hardware such as MIDI controllers, MIDI guitars, etc. This code in my opinion belongs to the core.

**Comment by marcelofg55** [comment]
Code is completed now, can be reviewed.

Note: If anybody tests this on Linux only one application can be actively connected to the rawmidi ALSA driver.

**Comment by reduz** [comment]
After thinking about it, i guess this makes sense for the whole music games genre, like rock band instruments (which are MIDI), games that teach you to play piano, and that kind of stuff. PR does not seem too big either, so it may be OK to merge if anyone else think it's ok.

**Comment by akien-mga** [comment]
Great work, thanks a lot!

**Comment by Imerion** [comment]
Does this support Android currently?

**Pull request merged**
