### PR TITLE
OpenXR: Enable access to the Valve Index grip force sensors

### PR DESCRIPTION
**Pull request by luzader**
This is a trivial addition which fixes my #74023. See there for a tiny test project. I made a bit of a mess of the commit history but hopefully that doesn't matter.

_Production edit: Fixes https://github.com/godotengine/godot/pull/74787_

### CODE REVIEW

**Comment by fire** [comment]
We tend to require a small number of commits like 1. https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html

**Comment by luzader** [comment]
Squash attempt number 2?

**Comment by BastiaanOlij** [comment]
Not sure if we should add force to the default action map seeing its very specific to the index controller, I actually want to slim down the default map and have people design their own action maps to the needs of their game.

That said I think it's fine for now until we make a decision on where to go with the default map, the change to the meta data class is needed.

**Review by BastiaanOlij — APPROVED** [review]

**Comment by luzader** [comment]
I agree its superfluous in the default. I thought I had mentioned that in my PR but its gone missing. Thanks.

**Comment by YuriSizov** [comment]
Thanks! And congrats on your first merged pull request!

**Pull request merged**
