### PR TITLE
Fix completion for `new` arguments

### LINKED ISSUE #92245: `_init()` arguments are not suggested when using `new()`
### Tested versions

v4.2.stable.official [46dc27791]
v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

I created the following script:

````
extends Resource
class_name Test

func _init(a: int, b: int) -> void:
	pass

func foo(a: int, b: int) -> void:
	pass
````

When initializing an object with this class using ``new()``, the editor does not show the available arguments:
image

It does work, however, with other functions in the script:
image

### Steps to reproduce

1. Create a script class that inherits from Resource
2. Add an ``_init()`` method with some arguments to that class
3. Try to initialize the class anywhere

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/godotengine/godot/files/15400434/mrp.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
- Fix #92245

Works both for separated and inner classes:

изображение
изображение

### CODE REVIEW

**Comment by HolonProduction** [comment]
Would be nice to handle inheritance as well:
image

**Comment by Chaosus** [comment]
@HolonProduction Done, check again

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

**Testing project:** [test_pr_92251.zip](https://github.com/godotengine/godot/files/15448335/test_pr_92251.zip)

image

**Review by akien-mga — APPROVED** [review]
Not an expert, but looks ok to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
