### PR TITLE
[WIP] iOS one click deploy using ios-deploy

### LINKED ISSUE #2703: One click deploy for iOS
I saw somewhere @reduz tried to find a way to implement `one click deploy for ios`.
But, it is not done yet and I leave it here for future task.

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes #2703.
Needs testing. Any iOS dev who could help me test this?
Uses ios-deploy (https://github.com/phonegap/ios-deploy).

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Not today but I'll definitely give this a swing during the week!

**Comment by endragor** [comment]
Have you considered using [libimobiledevice](https://github.com/libimobiledevice/libimobiledevice/) ? That could allow to free user from having to install additional tools.

**Comment by marcelofg55** [comment]
@endragor I didn't know about that library, looks cool, but maybe it will require a lot more effort to implement it? I will definitely check it out anyways.

**Comment by reduz** [comment]
This is seriously good. I agree with @endragor that if we can make it built-in it would be great, but i don't know how feasible is this given Apple may change API. What do you think?

Also, Is there a way to make port forwarding via the cable? If so, we could enable remoteFS to work properly over cable on iOS like we do on Android.

**Comment by marcelofg55** [comment]
I also agree about that making this built-in would be great, but I think that it may require a lot more effort to make it work with the libraries that @endragor pointed, and ios-deploy is really easy to use.

Not sure about that port forwarding thing, I'll check it out.

**Comment by reduz** [comment]
@marcelofg55 That sucks.. makes it really difficult to use remoteFS, which is very very helpful on large projects. Wifi has too much latency to use RemoteFS. I guess in the worst case, one can still get an ethernet adapter for iOS.

**Comment by akien-mga** [comment]
> Have you considered using libimobiledevice ? That could allow to free user from having to install additional tools.

Note that it's dual-licensed GPLv2 and LGPLv2.1, the former is a no-go for us and I don't think the latter fits us either unless it provides a static linking exception (which it doesn't in this case).

**Comment by marcelofg55** [comment]
@BastiaanOlij Did you had a chance to test this out? Thanks :)

**Comment by reduz** [comment]
@endragor given your recent changes, what do you think of this one?

**Comment by endragor** [comment]
Is this related to my changes? :) I think the feature is useful, but I haven't tested it.

**Comment by rraallvv** [comment]
There is also [peertalk](https://github.com/rsms/peertalk).

**Comment by akien-mga** [comment]
What's the status on this PR? Does it still build/work against the current master branch, and did any iOS dev get to test it?

> Have you considered using libimobiledevice ? That could allow to free user from having to install additional tools.

I see two issues with libimobiledevice though:
- It's under LGPLv2.1 without static linking exception, so it's an annoying library to depend upon for a permissively licensed engine (and we'd have to make sure none of its code is included in export templates, I think LGPLv2.1 is not allowed on the Apple Store).
- It depends on either OpenSSL or GnuTLS, while we switched to mbedTLS

> There is also peertalk.

Seems worth looking at too.

**Comment by akien-mga** [comment]
Moving to the 3.2 milestone as we're nearing feature freeze and this is still WIP.

**Comment by samgreen** [comment]
I'll give this a shot and report back!

**Comment by rraallvv** [comment]
@samgreen , are you giving [peertalk](
https://github.com/rsms/peertalk) a try?

**Comment by samgreen** [comment]
I was using this PR and `ios-deploy`. I was not able to get the deploy on export to function with this PR.

**Comment by rraallvv** [comment]
@samgreen Thanks for looking into it.

About peertalk, sadly I don't have any iOS device at hand, so I can give it a try. peertalk seems like the right choice to me. It has a permissive license, and seems to have some support for [port forwarding](https://github.com/dguillamot/PFMacOSClient).

**Comment by akien-mga** [comment]
Moving to the next milestone as this is still WIP, so it's unlikely to be merged for 3.2 which is about to enter release freeze.

**Comment by aaronfranke** [comment]
@marcelofg55 Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by akien-mga** [comment]
This was promising but as it's still a draft after two years, it's probably best to close.

A new PR reviving this would be welcome, as iOS one click deploy would be a very good addition.

**Pull request closed without merging**
