### PR TITLE
Add clip container

### PR DESCRIPTION
**Pull request by sanikoyes**
useful for ui display cliped childrens

### CODE REVIEW

**Comment by reduz** [comment]
I would probably instead expose the clip api propery to all controls instead

**Comment by sanikoyes** [comment]
@reduz  this would conflict with many controls like ScrollContainer/Label/RichText/Label/Tree etc...

**Comment by reduz** [comment]
I was thinking of adding clip as a property in control instead, since many controls might want to clip children, like box containers, windows, etc.

**Comment by akien-mga** [comment]
Maybe something to add to #5696 then.

**Comment by reduz** [comment]
will add the clip property to controls I think for Godot3

**Comment by akien-mga** [comment]
The clipping property has been implemented in Control for Godot 3.0, so closing this PR as obsolete.

**Pull request closed without merging**
