### PR TITLE
Use bake method for NavigationMeshGenerator in Runtime

### PR DESCRIPTION
**Pull request by thoced**
Hello

The use of the Bake in NavigationMeshGenerator method did not work in runtime (because of EditorProgress which wants to display a message in runtime) but only in the editor (hint_editor). This fix allows you to generate navigationmesh directly in the runtime. This is very useful, in particular, when creating procedural or random level.

Now, NavigationMeshGenerator can be used in the editor and in the Runtime for Plateform Windows and Android
(with and without flag tool=no or tool=yes)

Thanks

### CODE REVIEW

**Comment by lexferreira89** [comment]
First of all, I'd like to thank Thoced for all the work he's put on this feature. Second, I'd like to ask if someone could review Thoced's code so this feature can finally be added to Godot?

**Comment by thoced** [comment]
> 
> 
> First of all, I'd like to thank Thoced for all the work he's put on this feature. Second, I'd like to ask if someone could review Thoced's code so this feature can finally be added to Godot?

I deleted the #endif too many in the code. My current problem is that I do a rebase to remove the text from shallow commits. For some reason I always get error messages when I use the git rebase -i HEAD ~ x command.

**Comment by Calinou** [comment]
@thoced Do you have a demo project we can use to check whether the functionality works as intended? This would help getting this PR merged.

**Comment by thoced** [comment]
> 
> 
> @thoced Do you have a demo project we can use to check whether the added functionality works as intended? Having a demo project available would help getting this PR merged.

Hello, here is a repository containing a small godot application which initializes a NavigationMesh from the code (without using the generation editor):

https://github.com/thoced/testNavigationMeshGenerator

**Comment by lexferreira89** [comment]
Sorry for bothering you guys, but is there any news about this?

**Pull request closed without merging**
