### PR TITLE
Prevent label width from flickering rapidly in editor frametime panel

### LINKED ISSUE #91586: Frame time widget won't stay still when using a custom editor font
### Tested versions

v4.3.dev6.official [89850d553]

### System information

Godot v4.3.dev6 - macOS 14.4.1 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

https://github.com/godotengine/godot/assets/60579014/ebcf85b4-2dd8-42ff-b7a2-02eaff3954b2

Doesn't look great because it's flickering even though the number of digits doesn't change. Maybe it needs a minimum width or something like that (Or it could use the monospace font)

### Steps to reproduce

Use the [Inter](https://fonts.google.com/specimen/Inter) font

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by Calinou**
- This closes https://github.com/godotengine/godot/issues/91586.

## Preview

*Using the [Inter](https://rsms.me/inter/) font.*

### Before

https://github.com/godotengine/godot/assets/180032/0a234bfb-9579-473b-a7d2-3ddd55ad19c4

### After

https://github.com/godotengine/godot/assets/180032/2e1e007b-a06b-498e-ac28-53146807bebe

### CODE REVIEW

**Comment by timothyqiu** [comment]
A fixed width might not work for localized version of the text.

```
GPU Time: 10.25 ms

// Portuguese
Tempo de GPU: %s ms

// Arabic
وقت بطاقة الشاشة: %s جزء ثانية
```

**Comment by Calinou** [comment]
> A fixed width might not work for localized version of the text.

Should I calculate the field's width using the Font class to determine the text width (assuming a frametime of 999.99 mspf)?

**Comment by passivestar** [comment]
A bit off-topic but what do you think of reparenting those stats to a common container to get rid of these?

image

**Comment by Calinou** [comment]
> A fixed width might not work for localized version of the text.

Current editor language is now taken into account:

Screenshot_20240523_204853


> A bit off-topic but what do you think of reparenting those stats to a common container to get rid of these?

Fixed:

Screenshot_20240523_204248

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
