### PR TITLE
Fix default values not being read correctly in VS, take two

### LINKED ISSUE #25889: Parameter are visible but internaly empty, and when restart, all the values are empty
**Godot version:**
beta 4

**OS/device including version:**
Win10 64bit

**Issue description:**
In visual script :
parameter of functions and properties are not created (the value is visible but internaly empty) even if values are visible when play values considered as empty.
and when save and restart godot and load the project again the values of all nodes are clearly empty.

image

**Steps to reproduce:**
create project >> add sprite >> add visual script >> add animation player >> create animation >> add func _physics_process >> add play animation node and enter animation name >> add position and lookat nodes and enter values >> play (it will consider parameter as empty) >> save project >> exit >> reopen godot >> load the project and check parameters (it will be empty)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #25889.

Note that I made `validate_scheduled` to start as `true`, since it is going to be called in `NOTIFICATION_POSTINITIALIZE`.

### CODE REVIEW

**Comment by fire** [comment]
[VS Test 28606.zip](https://github.com/godotengine/godot/files/3138370/VS.Test.28606.zip)

I did some blackbox testing and this example project fails to run even though the construct vector 3 clearly says it's Vec3(0,0,0). When you change it to Vect3(10,0,0) 3 floats it works.

**Comment by bojidar-bg** [comment]
More like "take three" now, made it not wait for postinitialize to validate the default values, but instead the VisualScript would call validate on the fully-loaded instance.
Additionally, removed the call to validate from `notify_ports_changed` and put it uncoditional in `_node_ports_changed` of the VisualScript.

Hope no regressions were introduced with the changes.

**Comment by mhilbrunner** [comment]
@fire Can you test this?

**Comment by fire** [comment]
@mhilbrunner If you can use the test project above and play with https://github.com/godotengine/godot/pull/28606#issuecomment-488687843. I'm a bit swamped with things.

**Comment by mhilbrunner** [comment]
I tried to reproduce the bug locally but couldn't, even with the project mentioned above. Current master and this PR seem to behave the same. What are the exact steps?

**Comment by fire** [comment]
When the developer creates a construct node. When you only change the y value to 0, it won't save on 3.1 Godot.

Screen Shot 2019-05-17 at 12 36 05 PM

This patch attempts to solve it.

**Comment by fire** [comment]
This patch appears to resolve the issue.

**Comment by fire** [comment]
Nevermind:

The developer and the interface should directly change the number. The requirement of adding enter to confirm is causing the "bug".

**Comment by fire** [comment]
Screen Shot 2019-05-17 at 12 56 39 PM

Choaosus was able to change the interface to directly modify the Output Port name.

**Comment by fire** [comment]
@Chaosus When you're around, can you describe how the ability to directly edit the textbox works?

**Comment by Chaosus** [comment]
LineEdit emits text_changed signal when you entered a symbol and text_entered when you entered a text and press enter. I just started a timer inside text_changed. If user entered symbol before the timer timeout - the timer is resetted and started again. When timer is timeout - the shader will be rebuilded.

Please test rename for crash again - I've changed the timeout procedures a bit..

**Comment by bojidar-bg** [comment]
Sorry, I cannot understand how the last few comments are related to the pull request. Is there a bug or no? Does it come from the pull request? Is it the issue it is trying to fix? How can I confirm it as well?

**Comment by Chaosus** [comment]
Good question.. look like a time-space anomaly )

**Comment by fire** [comment]
Let me give context.

Vec3

The x, y, z inputs need to allow direct editing on the node instead of giving a confirm dialog.

The developer and the interface should directly change the number. The requirement of adding enter to confirm is causing the "bug" because when you type in the number and move away the number isn't being saved. You have to "confirm" by typing enter.

@Chaosus was able to do this for the expression node, now we have to do this for vec3, anything that displays the cells with floats we can edit.

**Comment by fire** [comment]
https://youtu.be/zQoaHOgHFk4

https://youtu.be/gm0trehxkd4

**Comment by Chaosus** [comment]
@fire Do you want it in initial release ? I'm unable to code for today, but I can try afterwards

**Comment by fire** [comment]
@Chaosus Look at the title, this is a different issue.

**Comment by Chaosus** [comment]
Ah.. I thinked that you want me to implement it in expressions nodes

**Comment by fire** [comment]
I was discussing implementing the expression node like input for vec3, vec2, plane, etc.

**Comment by bojidar-bg** [comment]
@fire Feel free to open another (tagged usability) to allow for setting a default input without pressing Enter. This PR is unrelated to the usability issue you are talking about, instead it is about default values of Contruct nodes not being saved or read properly, as before they were saved as "null" instead of "0".

I'll not add changes unrelated to the original issue here. Instead, a separate issue and PR is going to be better.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
