### PR TITLE
Fix size error in `BitMap.opaque_to_polygons`

### LINKED ISSUE #76531: BitMap.opaque_to_polygons() fails on 1+2 pixel width/height
### Godot version

4.0.2.stable

### System information

Linux Mint 20.3

### Issue description

In _march_square() ([line 357](https://github.com/godotengine/godot/blob/master/scene/resources/bit_map.cpp#L357)) the assertion:

`ERR_FAIL_COND_V((int)count > width * height, Vector<Vector<Vector2>>());`

is not met when one of the bitmaps extents is 1 and opaque_to_polygons() is executed. I tested this with an 1x18 and 18x1 bitmap.

Mentioning @AThousandShips who recently did great work improving the _march_square() part.

### Steps to reproduce

Create an 1xn or nx1 BitMap and run opaque_to_polygons().

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by AThousandShips**
Previous estimate of upper limit on size was incorrect

I am not sure if the check is still needed based on my previous additions, but keeping it in case there is some edge case that causes getting stuck in an infinite loop, this shouldn't introduce any errors as the condition is there to detect if the list of vertices grows unbounded in that case, the exact value of the limit shouldn't matter as long as it's not too low, only matters in how fast it fails.

3.x version: #76544

Fixes #76531

### CODE REVIEW

**Comment by AThousandShips** [comment]
Thank you, will investigate the check but `2 * (W * H + 1)` sounds like a good safe limit

**Comment by AThousandShips** [comment]
The reasoning looks sound to me, thank you for your feedback!

**Review by kleonc — APPROVED** [review]
Well, LGTM. :upside_down_face:

**Review by Geometror — APPROVED** [review]

**Comment by AThousandShips** [comment]
Did some more analysis and my approach for a lower upper limit on the size is to assume that each interior pixel corner can hold two vertices and the rest one (interior here meaning not on the edge of the bitmap)

This gives `2(W-1)(H-1)` for the interior and `2(W+1) + 2(H+1) - 4` for the rest. Which conveniently simplifies to `2(W*H + 1)`

**Comment by AThousandShips** [comment]
Alsp analysed it in terms of interior and exterior pixel corners, a lower limit for the size would be one vertex for each of the edge pixels and two for the rest, or `2*(W+1) + 2*(H+1) - 4 + 2*(W-1)*(H-1)` which simplifies to `2*(W*H+1)`

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
