### PR TITLE
doc: Fix typo in ConcavePolygonShape2D/3D description

### PR DESCRIPTION
**Pull request by EgeYildir**
Fix a typo that said ConvexPolygonShape2D instead of ConcavePolygonShape2D. ConcavePolygonShape2D is hollow and both this page and ConvexPolygonShape2D page confirms it.

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]

**Comment by AThousandShips** [comment]
The same error is present in the 3D shape, can you fix that as well? Please update your code with `git commit --amend` to not create an additional commit

**Comment by akien-mga** [comment]
> The same error is present in the 3D shape, can you fix that as well? Please update your code with `git commit --amend` to not create an additional commit

Please also amend the commit message to be more explicit. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind. Here it could be "doc: Fix typo in ConcavePolygonShape2D/3D description"

**Comment by AThousandShips** [comment]
Please squash your commits into one, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase), and use `git push --force` to not add a merge commit

**Comment by EgeYildir** [comment]
Sorry for inconvenience. This should be all good now.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.4. While the change is minor and will affect translations, this was blatantly and misleadingly wrong before. So I concluded that it was worth it.

**Pull request merged**
