### PR TITLE
Implement tabs to filter by texture in the tilemap editor.

### PR DESCRIPTION
**Pull request by abueide**
Often times developers group related tiles into a single texture, so this PR just offers a way to utilize that organization by adding tabs to filter tiles by texture.

This is my first PR, I'm new to Godot & c++. This took me a lot of time, but I'm getting much more familiar with c++ & the tilemap/tileset editor code, so hopefully I can make useful contributions to improve it. Anyways I know the code is pretty bad, so even if the proposal doesn't get accepted I'd really appreciate feedback so I can get better at contributing faster.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Any screenshots/GIFs?

**Comment by abueide** [comment]
@KoBeWi sure, here is the gif. I have more plans for the tileset/tilemap improvements & how to implement them, this is just the first because it was simpler. I'll make a comment in your thread that I'll update regularly with links to my PRs when they're done.

Q2Qu77JTHv

**Comment by abueide** [comment]
Also I need to fix the manual palette still, should be an easy fix.

**Comment by abueide** [comment]
Okay this PR is fully tested and cleaned up, just waiting for feedback.

**Comment by Wavesonics** [comment]
They will want you to squash the commits before merging

**Comment by aaronfranke** [comment]
@abueide Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch.

This PR may have to be redone after groud's TileMap rework, but the feature itself may still be desired, so we may as well rebase it now and then it can also be rebased later.

**Comment by KoBeWi** [comment]
This is actually already done in the reworked TileMap #45278 (see the atlas list on the left, it's basically the same thing), so closing.

Thanks for the contribution nevertheless..

**Comment by abueide** [comment]
Awesome to see the new progress on the tilemap stuff! Thanks for letting me know

**Pull request closed without merging**
