### PR TITLE
[NEEDS REVIEW] Better find in documentation

### LINKED ISSUE #14410: Better find in documentation
The current find function in the documentation is not convenient. It's a popup, it hides part of the doc, and the doc is hard to read because it's darkened, there's no Find next/Find previous shortcut.

If possible the find function should be the same as when editing scripts, which has a much better design.

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
# Please, someone review before merge.
Fix #14410, #14925 

I've changed "search dialog" in the documentation for "search bar", as in the script editor, with options for searching next and previous text.

2017-12-22-164704_1113x374_scrot

### CODE REVIEW

**Comment by volzhs** [comment]
I like this feature, don't know why you closed this though.

**Comment by guilhermefelipecgs** [comment]
sry, I deleted my branch unintentionally, I will reopen.

**Comment by volzhs** [comment]
it's good to hear that. :)

**Comment by guilhermefelipecgs** [comment]
I coldn't reopen this PR, then I created a new one.

**Pull request closed without merging**
