### PR TITLE
Rename `Listener2D`/`Listener3D` to `AudioListener2D`/`AudioListener3D`

### PR DESCRIPTION
**Pull request by Rubonnek**
Closes:
-  https://github.com/godotengine/godot-proposals/issues/3299

This PR was achieved by running the following shell script in Linux at the root of the repository:

```shell
# Rename Class
rg -l Listener2D | xargs sed -e 's/Listener2D/AudioListener2D/g' -i
rg -l Listener3D | xargs sed -e 's/Listener3D/AudioListener3D/g' -i

# Rename variables and functions
rg -l listener_3d | xargs sed -e 's/listener_3d/audio_listener_3d/g' -i
rg -l listener_2d | xargs sed -e 's/listener_2d/audio_listener_2d/g' -i

# Fix the viewport boolean variables for clarity (and avoid duplicate definitions after the last substitution)
sed -e 's/\<audio_audio_listener_2d\>/is_audio_listener_2d_enabled/g' -i scene/main/viewport.h scene/main/viewport.cpp
sed -e 's/\<audio_audio_listener_3d\>/is_audio_listener_3d_enabled/g' -i scene/main/viewport.h scene/main/viewport.cpp

# Rename files
git mv scene/2d/listener_2d.h scene/2d/audio_listener_2d.h
git mv scene/2d/listener_2d.cpp scene/2d/audio_listener_2d.cpp

git mv scene/3d/listener_3d.h scene/3d/audio_listener_3d.h
git mv scene/3d/listener_3d.cpp scene/3d/audio_listener_3d.cpp

git mv doc/classes/Listener2D.xml doc/classes/AudioListener2D.xml
git mv doc/classes/Listener3D.xml doc/classes/AudioListener3D.xml

git mv editor/icons/GizmoListener3D.svg editor/icons/GizmoAudioListener3D.svg
git mv editor/icons/Listener2D.svg editor/icons/AudioListener2D.svg
git mv editor/icons/Listener3D.svg editor/icons/AudioListener3D.svg

# Clear the remaining duplicated audio keywords
rg -l audio_audio | xargs sed -e 's/audio_audio/audio/g' -i

# Drop changes to translations
git checkout doc/translations/
```

and `clang-format` should take care of the rest.

~I'm not sure if I missed anything else that needed renaming, but that doesn't seem to be the case.~

### CODE REVIEW

**Comment by LightningAA** [comment]
Do the translation files need to be updated?

**Comment by Rubonnek** [comment]
Looks like there's only one `msgid` that contains references to `Listener2D` and `Listener3D` that needs to be updated.
Here it is:
```po
msgid ""
"Returns [code]true[/code] if the listener was made current using [method "
"make_current], [code]false[/code] otherwise.\n"
"[b]Note:[/b] There may be more than one AudioListener3D marked as \"current\" in "
"the scene tree, but only the one that was made current last will be used."
```

Outside of that, the rest of the references are located within comments:
```shell
#: doc/classes/AudioListener3D.xml
```

Are any of these changes undesired?

**Comment by akien-mga** [comment]
It's better not to update the translations, I do that myself.

**Comment by Rubonnek** [comment]
Changes to translations dropped.

**Review by mhilbrunner — APPROVED** [review]

**Review by AaronRecord — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
