### PR TITLE
VideoPlayer: Added started,paused,stopped,finished signals

### LINKED ISSUE #5377: Emit a signal when VideoPlayer stops?
**Operating system or device - Godot version:**
Any OS - Godot 2.X

**Issue description** (what happened, and what was expected):

I'm trying to get the best performance out of a scene of mine that plays a video and adds subtitles (thanks to a custom GDScript I wrote).  
The video is played via a VideoStreamTheora and handled by a VideoPlayer Node.

Now, my scene constantly checks if the video is still playing so that it can move on when it stops. I've been looking around in godot's code and I can't find out the source of the `is_playing()` since it points to a `playback->is_playing()` (I think it checks for a bool value?), but anyways, I believe a signal would lay off a little bit — if not more — stress out of CPU (on a side note, I see that Theora drops many frames).

So, I looked at the signals singleton but found out (remembered, actually) that "finished" is already a signal that exists for animation, so I'm not sure if the signal can conflict with the video if we were to point both towards it. If this is the case, it's best to make a signal entirely for streaming.  
If this is not feasible, what can be an alternative?

### PR DESCRIPTION
**Pull request by J08nY**
- fixes #5377
- started is emitted on play()
- paused is emitted when going from not paused state to paused state
- stopped is emitted when the stream was playing on a call to stop
- finished is emitted when the stream naturally stops(runs out)
- also cleaned up the files a bit, removed some unnecessary prints, changed some `fprintf(stderr` prints into `ERR_PRINT`

### CODE REVIEW

**Comment by akien-mga** [comment]
Nice cleanup, though I'd prefer if the cleanup had been done in its own commit (i.e. no new signal in the first commit), and the new features added in a second commit.

Also, what is the reason for the various bits you commented out? If they're unneeded code, it's best to just drop them instead of commenting them out. If they might be needed, then it would be good to add comments in the code to explain why this stuff is commented out.

**Comment by J08nY** [comment]
The commented out stuff was unused(there was already a large block of commented out code that caused these unused variable warnings so I just commented them out too to silence them). So I cant comment why that stuff is commented out, it just was.
I also commented out some unnecessary prints, but sure I can split it into two commits, basically the signals were added in one file and the cleanup was in another file.

**Comment by akien-mga** [comment]
That's better, thanks :)

We should really get rid of all this commented code and unused variables :)

**Comment by akien-mga** [comment]
It needs to be rebased, but the idea should probably be validated by @reduz first to check that he's fine with the new API.

**Comment by reduz** [comment]
closing this one, as mentioned in other similar issues, I don't think signals that are emitted when the user calls functions are needed.  By rule, signals are generally emitted when something not directly under the control of the user happens.

**Comment by Keyaku** [comment]
True, but the `finished` is the only one that's relevant in here. Shall I make a PR with just that signal?

**Comment by vnen** [comment]
I think the cleanup commit is still relevant, besides the `finished` signal. Better open a new PR with that.

**Comment by wkubiak** [comment]
@Keyaku Hi, do you still plan to do that PR?

**Pull request closed without merging**
