### PR TITLE
Add a new decomposition to Basis.

### PR DESCRIPTION
**Pull request by ghost**
This new decomposition splits the basis into a rotation-reflection matrix and a positive scaling matrix, which is required for physics calculations.

### CODE REVIEW

**Comment by tagcup** [comment]
I fixed this, but this function may not be needed at all

**Comment by tagcup** [comment]
I'm closing this because this decomposition works with local transforms, and won't work with global decompositions in general, which is what the bullet PR apparently needs.

This function is arguably useful on its own, but I don't think this warrant it to be a part of the core.

**Comment by tagcup** [comment]
I'm reopening this because we're apparently OK with non-uniform scalings in physics

**Comment by akien-mga** [comment]
It needs rebasing after #10778.

**Comment by tagcup** [comment]
Ah, that's interesting. I've rebased it

**Pull request merged**
