### PR TITLE
Rename `range_lerp` to `remap`

### LINKED ISSUE #5335: Rename `range_lerp` to `lerp_range`
### Describe the project you are working on

having fun with 4.0

### Describe the problem or limitation you are having in your project

`range_lerp` is alone in the docs next to totally unrelated methods :disappointed: 

image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename `range_lerp` to `lerp_range` for consistency and bring it back next to its friends:

image

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

its about renaming a function

### Is there a reason why this should be core and not an add-on in the asset library?

its about something core already

### PR DESCRIPTION
**Pull request by Mickeon**
Closes https://github.com/godotengine/godot-proposals/issues/5335 (?).

~This PR was renaming it to lerp_range~
~Should the favour go to `remap()` this PR can easily be changed to match (or closed outright if rejected).~

### CODE REVIEW

**Comment by Mickeon** [comment]
I don't understand the Linux Error anymore:
```
WARNING: Property not found: dotnet/project/assembly_name
     at: _get (core/config/project_settings.cpp:3[24](https://github.com/godotengine/godot/runs/8189890271?check_suite_focus=true#step:13:25))
Starting checking if project conversion can be done.
ERROR: Missing gdscript function in pair (range_lerp - ===> lerp_range <===)
   at: test_array_names (editor/project_converter_3_to_4.cpp:[26](https://github.com/godotengine/godot/runs/8189890271?check_suite_focus=true#step:13:27)32)
ERROR: Found function which is used in converter, but cannot be found in Godot 4. Rename this element to new name or remove entire rule about it if is obsolete.
   at: test_array_names (editor/project_converter_3_to_4.cpp:2639)
ERROR: Cannot start converting due to problems with data in arrays.
   at: validate_conversion (editor/project_converter_3_to_4.cpp:2051)
```
It's no property, it's a global scope function...!

**Comment by kleonc** [comment]
> I don't understand the Linux Error anymore:
> 
> ```
> WARNING: Property not found: dotnet/project/assembly_name
>      at: _get (core/config/project_settings.cpp:3[24](https://github.com/godotengine/godot/runs/8189890271?check_suite_focus=true#step:13:25))
> Starting checking if project conversion can be done.
> ERROR: Missing gdscript function in pair (range_lerp - ===> lerp_range <===)
>    at: test_array_names (editor/project_converter_3_to_4.cpp:[26](https://github.com/godotengine/godot/runs/8189890271?check_suite_focus=true#step:13:27)32)
> ERROR: Found function which is used in converter, but cannot be found in Godot 4. Rename this element to new name or remove entire rule about it if is obsolete.
>    at: test_array_names (editor/project_converter_3_to_4.cpp:2639)
> ERROR: Cannot start converting due to problems with data in arrays.
>    at: validate_conversion (editor/project_converter_3_to_4.cpp:2051)
> ```
> 
> It's no property, it's a global scope function...! And it does exist in this PR!

The errors point directly to the code you should inspect. :wink:
Seems like the new global namespace functions need to be listed here:
https://github.com/godotengine/godot/blob/69479c6e6b6019d0238922068cbb672b492faf12/editor/project_converter_3_to_4.cpp#L2600-L2602
(so to get rid of the errors you'd need to add `lerp_range` to that array).

**Comment by Mickeon** [comment]
Thank you!

**Review by kleonc — COMMENTED** [review]
You've left `LerpRange` in C#.

**Review by aaronfranke — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
