### PR TITLE
Respect cache mode when loading external dependencies.

### PR DESCRIPTION
**Pull request by HolonProduction**
This line is part of #86960, but this seems to have quite a way ahead of it and I need it to fix the CI for #86973.

Also this might fix
https://github.com/godotengine/godot/issues/82830

### CODE REVIEW

**Comment by AThousandShips** [comment]
This should also be done in the binary format if done here, the same code is used there with the reuse mode

**Comment by HolonProduction** [comment]
Done

**Comment by RandomShaper** [comment]
I think this change makes sense. I'd like more people looking into it, though.

One thing I'd like to point out is that, maybe, the editor is relying on the current behavior not to have to reload external resources when loading a scene:
https://github.com/godotengine/godot/blob/fb10e67fefb85af3b8f5abd30db561588d8456c6/editor/editor_node.cpp#L3857

If that were the case, we may need to add a mode, such as `CACHE_MODE_REPLACE_ROOT_REUSE_OTHERS`, but with a more compact name.

**Comment by RandomShaper** [comment]
> One thing I'd like to point out is that, maybe, the editor is relying on the current behavior not to have to reload external resources when loading a scene:
> 
> https://github.com/godotengine/godot/blob/fb10e67fefb85af3b8f5abd30db561588d8456c6/editor/editor_node.cpp#L3857
> 
> If that were the case, we may need to add a mode, such as `CACHE_MODE_REPLACE_ROOT_REUSE_OTHERS`, but with a more compact name.

On an _n_-th thought, if _replace_ is meant to change the way subresources are loaded, I does make sense that the mode is jsut propagated.

**Comment by HolonProduction** [comment]
The change seems to be far more critical than I thought it would be. Closing in favor of #88664.

**Pull request closed without merging**
