### PR TITLE
[3.1][cherry-pick] Add apply method to SpinBox

### PR DESCRIPTION
**Pull request by xsellier**
Cherry-pick https://github.com/godotengine/godot/pull/34960

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't necessarily plan to make feature updates for 3.1.x at this stage, mostly bugfixes. Do you have a strong reason not to upgrade to 3.2?

**Comment by DisDoh** [comment]
IOS and Android Module are the reasons.

**Comment by DisDoh** [comment]
And i've asked for this cherry pick because the spinBox doesn't signal the focus or mouse entered elsewhere than the incrementation buttons.

**Comment by akien-mga** [comment]
Well, I'll merge, but I don't have a 3.1.x release planned for now so it won't make much difference.

**Comment by DisDoh** [comment]
Thanks!

**Pull request merged**
