### PR TITLE
Add format loader for ImageTexture to load supported images directly.

### PR DESCRIPTION
**Pull request by Geequlim**
Sometimes we really need to load images without import them(such as a gui tool to open and show images in the disk) so I made this.

### CODE REVIEW

**Comment by cjmxp** [comment]
There is a great need for other applications such as developing map editors from loaded resources

**Comment by reduz** [comment]
sorry guys, but this is an intended design decision. Changing this screws up the import system.
You can still load images manually with Image.load() and then set it to an ImageTexture

**Comment by reduz** [comment]
To clarify a bit more. Most resource types now (audio, images, scenes) etc are no longer native on purpose. They are imported so they can be delivered to each platform on export as efficiently as possile.

If you download images or audio via code, you can still use the relevant classes (ImageTexture, AudioStreamOGG or Sample, etc) to load the resource manually

**Comment by Geequlim** [comment]
@reduz Yes we can load images with `Image.load` and I did that before like this

```gdscript
static func load_external_image_texture(path):
    var img = Image.new()
    if OK == img.load(path):
        var tex = ImageTexture.new()
        tex.create_from_image(img)
        return tex
    return null
```

Why I decide to pull this PR is because I have to load a spine animation with the [Spine module](https://github.com/GodotExplorer/spine) the module it load required images with `ResourceLoader::load` it tries to load images at same folder of the animation resource. While I load an animation resource out of the `res://` folder textures of the animation will failed to show. For this situation we have no way to load images to then attach them to the correct place from script. Maybe we can change the implementation of the spine module to load external images but I don't think it is a good idea.
I think the problem may puzzle more and more people when GDNative become more popular in the future.

The resources in the project folder will keep using StreamTexture and follow the import workflow but why not give other resources a chance to be loaded with traditional way. I hope you can have a consider of that.

**Comment by reduz** [comment]
@Geequlim Then this is a problem of the Spine module. The images should load fine once imported

**Comment by reduz** [comment]
It's not about considering it, it's that with the new system it's not possible. Your PR breaks the import system in a way that can't be fixed or worked around. 

A lot of hack would be needed to get what you want to work properly, and it's not worth it given the use cases you propose are not used often at all. 

Just do a workaround for your use case

**Comment by Geequlim** [comment]
@reduz Yes images can be load fine after imported and animation will shown correctly.
I just want to make a tool with godot for artists to preview animation combinations in game that shouldn't require us to import images into `res://` right?

**Comment by Geequlim** [comment]
I'd like to know how it breaks the new resource system.

**Comment by reduz** [comment]
It breaks because it makes ResourceFormatImporter and ResoucreFormatTexture fight for the same resource type

**Comment by alugarius** [comment]
@reduz

How are you able to do so much stuff at once?

**Comment by reduz** [comment]
@alugarius I don't, and please don't be offtopic

**Comment by Geequlim** [comment]
@reduz Did you mean the `ResourceFormatImporter` won't import images in the project folder correctly as the registered `ResourceFormatLoader`  handle that first ?

**Comment by reduz** [comment]
@Geequlim ResourceFormatImporter is the resource format provider for everything that is imported. a .dae or .png are still considered resources by Godot via this format. 

When you try to load them, ResourceFormatImporter looks at the right asset in the .import folder and loads this. When the project is exported, the .png files and other files which were imported ad discarded and only the .import/ versions are kept.

If you provide a format loader with the same extension as one imported, then all this mechanism breaks. Always one will override the other depending on the order they were registered. there is no fix for this.

**Comment by reduz** [comment]
And in case you are thinking of doing a workaround or hack to support your specific use case, I will insist that this is not desired. You can solve this by fixing the Spine module or importing what you need manually.

**Comment by Geequlim** [comment]
@reduz In my opinion we don't need to care about the exporting of the resources out of the `res://` folder as they are not a party of the project. 

I'm going to make the resource fromate load into a module to solve the problem.

Thanks for your answer.

**Pull request closed without merging**
