### PR TITLE
Glow/HDR improvements

### PR DESCRIPTION
**Pull request by CptPotato**
A few improvements and changes around glow and HDR.

These are the changes I made (for myself) that improve or restructure some parts of godots HDR. I figured some of it might be helpful so I decided to make this PR. You can use parts of it or just use this as reference for future changes. If you wish to merge the PR but want some things changed or removed, let me know. Note that these changes do "break" existing projects.

Here's a quick screenshot (I don't have any better test scenes right now).

newglow

Here's a list of things I chaged or added:
- added "filmic saturation" option to tonemapper (6c6bdf8)
- added two new glow blend modes "linear add" and "linear mix" (4d7cc8b)
- switched to a new, more adjustable way of applying the glow highpass/threshold (4e8c122, including the following 2)
- added glow per-level-weight (was previously called "strength")
- made glow energy conserving (always on at the moment)
- switched to a different soft-light algorithm which is less complex (30a0b73)
- fixed reinhard tonemapping whitepoint (along with misspelling of it's name "reinhard" across different files) (186a17e, 133bf16)
- "fixed" filmic tonemapping (this one is debatable) (d9aa07a)
- added 2 tonemappers: the widely used Uncharted 2 algorithm and a simplified filmic one (both from an Uncharted 2 paper) (8c85e3c)

For more detailed explanations with screenshots: https://imgur.com/a/7DjwWM7
The names of the properties are maybe not optimal, so I'm open for suggestions. 

I will keep the commits separated until I know if this PR is okay and if there is anything I should change or remove.

### CODE REVIEW

**Comment by CptPotato** [comment]
Some properties of "Environment" where changed. So if you open an old project with this version you'll get errors for the properties that were renamed or deleted and you'll have to make adjustments to make use of those new properties.

**Comment by swarnimarun** [comment]
This needs a Breaks Comptability Label too. @volzhs 

Finally something I for the renderer.

**Comment by CptPotato** [comment]
@reduz could you or someone who's familiar with this topic/part of the engine give some feedback for those changes? I'm still unsure on whether or not I should change parts of this PR.

**Comment by reduz** [comment]
The PR is fine, but I am not sure how to integrate most of these changes without breaking compatibility.
Unless you can only provide a PR with changes that do not break compatibility for now, I think it will probably better to keep it on hold, and then implement most of these in the upcoming Vulkan Back-end.

**Comment by CptPotato** [comment]
Thanks for the feedback. I understand that it probably changes too much so I'm okay with the decision to hold it for now. Feel free to notify me once the Vulkan is in the works if you want me to help with some of the implementation (there's also another thing or two I might like to add for the rendering).

Besides that, I can also make a new PR with only these selected changes, which should be ok compatibility-wise:
- correct spelling of "Reinhard" (there are multiple instances of "Rein**d**har**t**" and "Reinhard**t**")
- fix Reinhard tonemapping whitepoint (it's currently not used as linear value)
- fix Filmic tonemapping (it looks like the operator has gamma correction baked, so SRGB conversion should be skipped here)
- [ add "Uncharted 2" tonemapper (is it okay to call it like that?) ]

**Comment by akien-mga** [comment]
Moving to the 3.2 milestone (might end up as 4.0 / Vulkan though) as per the above discussion.

**Comment by akien-mga** [comment]
Maybe we could have an issue instead that links this PR as reference? One less PR in the backlog is definitely a big win for me :D

**Comment by CptPotato** [comment]
Will do that.

I'll close this one and link the PR (or the branch on my fork) in a new issue at some point.

**Comment by akien-mga** [comment]
Thanks!

**Pull request closed without merging**
