### PR TITLE
Update @GDScript.xml

### PR DESCRIPTION
**Pull request by Koyper**
Adds a better way to iterate backwards over a range that avoids the [i - 1] index.

### CODE REVIEW

**Comment by MewPurPur** [comment]
I agree, this is better.

Since you didn't amend your second commit, please squash your commits. https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase explains how.

**Comment by Koyper** [comment]
> I agree, this is better as it skips some subtractions. I'd add a comment that it prints 9, then 6, then 3 (or something like that)
> 
> Since you didn't amend your second commit, please squash your commits. https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase explains how.

Thanks. There's an existing code block that follows that shows the results.

I've found that the easy way to contribute to the docs is starting an edit right on GitHub, which is how I added this - is there a way to squash commits here? Is there a way to amend when then subsequently revising the file with `edit`?

**Comment by dalexeev** [comment]
No, this cannot be done in the GitHub web interface as far as I know. You need to use local git.

**Comment by Koyper** [comment]
> No, this cannot be done in the GitHub web interface as far as I know. You need to use local git.

Well, that rather defeats the value of starting with the web interface. It will be easier to just close this and resubmit.

**Comment by dalexeev** [comment]
New PR: #76650.

**Comment by kleonc** [comment]
> > No, this cannot be done in the GitHub web interface as far as I know. You need to use local git.
> 
> Well, that rather defeats the value of starting with the web interface. It will be easier to just close this and resubmit.

@Koyper Just in case, for the future: if opening PR using the web interface means you won't be able to update it according to the comments / reviews / change requests, then please don't open PRs this way. Closing PR only to resubmit updated one does pollute the backlog, there are more just-noise-PRs to filter through etc. When opening a PR you should expect that changing/updating it might be needed.

**Pull request closed without merging**
