### PR TITLE
Replace pixel rounding with `floor(x + 0.5)`

### LINKED ISSUE #93731: Snap 2D Transforms to Pixel for subpixel value of 0.5 is inconsistent between positive and negative coordinates
### Tested versions

- Reproducible on Godot v4.3.beta2
- Not reproducible on Godot v4.2.2 (due to not having #87297. I guess you can call this a regression?)

### System information

Godot v4.3.beta2 - Windows 10.0.19045

### Issue description

https://github.com/godotengine/godot/pull/87297#issuecomment-2197619761:

> [...] instead of rounding, it should have been floor(x + 0.5) instead. This is because rounding to nearest has different behaviour for positive and negative values when the fractional part is 0.5.
> 
> Consider this: We position a sprite at x=0.5, which is snapped to x=1 on screen. We move it to the left by 1px. Where should the sprite be at on screen?
> 
> The expectation should be x=0. However, since the subpixel position is now x=-0.5, the sprite is actually snapped to x=-1 on screen thanks to rounding. Which means the supposedly 1px move becomes a 2px move on screen.

Fixing this may affect the behaviour of #93712.

CC @markdibarry

### Steps to reproduce

- Run MRP
- The 5 squares are 16 px apart, all having a subpixel x position of 0.5
- Label shows the coordinates of the centre red square
- Arrow key moves the squares by 0.125 px, Ctrl + arrow key moves by 1 px
    - Hold Shift to move one step at a time
- Use Ctrl + arrow keys to move: Observe that there is a 1px gap between the squares crossing the origin (centre of screen)
- Use arrow keys to move: Observe that the movement is inconsistent when the subpixel position changes from/to 0.5

### Minimal reproduction project (MRP)

[pixel-snapping-negative-bug.zip](https://github.com/user-attachments/files/16039332/pixel-snapping-negative-bug.zip)

### PR DESCRIPTION
**Pull request by markdibarry**
Fixes: #93731

We should do some more testing to be sure this has no side effects in pixel perfect art projects.

### CODE REVIEW

**Comment by alvinhochun** [comment]
Thanks for making the PR. I was also looking at this more in-depth locally, and noticed https://github.com/godotengine/godot/blob/25de53e147a04ba15afc461b3ad4aa1884ff927d/scene/gui/rich_text_label.cpp#L1252 might also need the same rounding change, since it checks `snap_2d_transforms_to_pixel`.

I do also have to note that, I realized there is a very specific edge case: the value `0.49999997` will be rounded incorrectly because `0.49999997f + 0.5f == 1.0f`. But I think it is acceptable to ignore this edge case, because it is very rare to end up with this value, compared to multiples of `-0.5`. (For `double` the problematic value is `0.49999999999999994`.)
 
Finally, there is the question whether we should do the same for GUI `snap_controls_to_pixels`, but that should be a separate PR.

**Comment by markdibarry** [comment]
Ah, yeah. I think that has always been rounded, which is why we never changed it.

**Comment by adamscott** [comment]
Did you try if it works with @KeyboardDanni's test scene found in #84380?

**Comment by markdibarry** [comment]
@adamscott Yep. Same result.

**Review by adamscott — APPROVED** [review]
Testing some games, all seems right. Tested out the issue MRP and it fixes it as well. Let's go, then?

**Comment by akien-mga** [comment]
Thanks!

**Comment by Gnumaru** [comment]
Instead of replacing round(x) with floor(x + 0.5), wouldn't it be better to replace round(x) with round(x + FLOAT_EPSILON)? (being FLOAT_EPSILON std::numeric_limits<float>::epsilon() or any equivalent constant). This way rounding -0.1 and +0.1 would both result 0 and the code would be more explict about the intention of rounding the value.

(I don't know it if is allowed to comment pull requests or issues. If it is not allowed, please forgive me.)

**Comment by KeyboardDanni** [comment]
I'm not quite sure what epsilon would do for us here. Epsilon is generally used when comparing equality between two floating point numbers, not flooring or rounding. Even there, epsilon is a bit of a flawed concept, because the "minimum distance between two numbers" is different based on the current exponent.

Besides, `round(x)` and `floor(x + 0.5)` already let us round -0.1 and +0.1 to 0.

**Comment by Chaosus** [comment]
Seems like it's cause a serious regression: https://github.com/godotengine/godot/issues/94298

**Pull request merged**
