### PR TITLE
Call `add_child` after `set_rect` to fix size bug

### LINKED ISSUE #80234: Alternative Tile 'Plus' Icon incorrectly sized for small tile sizes
### Godot version

v4.1.stable.mono.official [970459615]

### System information

Godot v4.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated GeForce GTX 1660 () - AMD Ryzen 7 2700 Eight-Core Processor (16 Threads)

### Issue description

In the TileSet module, the 'plus' icon to add an alternative tiles resizes when *interacting anywhere in the Tileset module* and obscures other alternative tiles, making them hard/impossible to select for tile sizes smaller than the default 16x16 (in my case, 8x8).

I have tried adjusting TileMap values in the inspector (and elsewhere) to see if this changes the behaviour, but it seems like the icon reverts to a 16x16 size if the TileSet Atlas' texture region is smaller than that, as sizes of 15x15, 14x14... demonstrate the overlapping issue. Larger tile sizes (e.g. 20x20, 32x32, etc.) are handled fine and the icon resizes accordingly.

It is possible to get around this by reopening the TileSet module (e.g. switching to TileMap and back) where the icon resizes correctly (even for smaller sizes), but breaks again when interacting with the module.

https://github.com/godotengine/godot/assets/1772788/01d6a942-b5fb-4a6b-8dbb-4a70280dc1ca

### Steps to reproduce

1. Navigate away from the TileSet module (so that it loses focus).
2. Navigate to the TileSet module.
3. Interact with any element that _forces the module to redraw_ (select a tile/tab, or change a property on a tile)
4. (Optional) Adjust the Tile Atlas `Texture Region Size` to a size smaller than 16x16 and repeat Steps 1-3.

### Minimal reproduction project

[AlternativeTileBugProject.zip](https://github.com/godotengine/godot/files/12256488/AlternativeTileBugProject.zip)

### PR DESCRIPTION
**Pull request by rakkarage**
closes: https://github.com/godotengine/godot/issues/80234

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
There is some odd preference for adding a child first and then initializing its properties (I tend to use it myself .-.), but recently I noticed that it affects sizing. I think we should re-evaluate this "convention". Even if the sizing problems are a bug, initializing stuff after adding it to tree is kinda backwards tbh (and in some cases probably less efficient).

**Comment by YuriSizov** [comment]
> Even if the sizing problems are a bug, initializing stuff after adding it to tree is kinda backwards tbh

Well, it is possible that the context of the parent would affect how some things are resolved when it comes to sizing. Probably not with containers, but with anchors when setting a preset it may work differently, I think.

In this case, btw, I'm not even sure it makes sense to have a button control. We could just draw an icon and detect clicks over specific areas with a bit of lower-level code. That should avoid messing with control sizing all together. But that's not important for this PR.

**Comment by YuriSizov** [comment]
Could you please amend your commit message to follow the project's preferred style? The title of the PR is a good option.

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
