### PR TITLE
OpenAL implementation for HTML5 sound

### PR DESCRIPTION
**Pull request by macramole**
Code is messy at this point, this is a very basic implementation, just trying things out.. 
Sound works but crackle
Here is an export of platformer-2d demo: http://www.parleboo.com/tests/platformer_js/ (no optimizations)
Tested on Firefox 38 @ Arch Linux 

reduz suggested to write a custom AudioServer for javascript export to avoid performance issues

I'd like to continue trying to make sound work with current AudioServer, I prefer low performance with sound than no sound at all for now.. maybe it will be ok for short games

### CODE REVIEW

**Comment by punto-** [comment]
That's awesome. Did you try loading this driver on a PC OS, like windows or
linux? It doesn't look like the crackle is a performance issue, more like
the wrong sample size or buffer size or frequency size somewhere..

**Comment by reduz** [comment]
My fear is that merging this will make others lose the motivation of
actually solving this problem properly, so apologies about it but will not
merge it for now.

**Comment by reduz** [comment]
For reference, the way to implement this properly is reimplementing AudioServer on the HTML5 backend

**Comment by macramole** [comment]
punto-: haven't tried, but yes, I think there is something wrong about the buffer size.. incrementing latency does not result in a delayed but working audio stream ( does GLOBAL_DEF("audio/output_latency",25); adjust latency on AudioServer too ?  I don't think so )

reduz: It's ok, I just wanted to share this little advance in case someone else is interested in contributing and I think its a good starting point although it does not reimplement AudioServer. I don't see "fixing html5 export" in the roadmap so I guess is not a priority.. I do think is important so I'll try..
Also, I think reimplementing AudioServer with OpenAL will also make it available for all OS, I mean, OpenAL is not only for the web, it could be the main AudioServer if its performance is acceptable

**Comment by reduz** [comment]
No worries, the reason it's not on the roadmap is because I honestly have
no idea about html5+js, so I was waiting for either punto having time to do
it in some point of the future (which is uncertain), or someone else with
experience to give it a try.

AudioServer in general has more features than OpenAL (and will have even
more in the future), so it's not really desirable to use OpenAL as a
backend for other platforms. It would be a simple implementation of it for
the HTML5 backend

**Comment by macramole** [comment]
What if we can get enough performance this way ? We won't be mantaining two AudioServers and endusers will get all features

**Comment by reduz** [comment]
the problem is that any glitch in the javascript or small delay will cause
audio corruption unless you use a bigger buffer size, and if you use a
bigger buffer size the audio will be considerably delayed..  this is why
games run audio in a thread

**Comment by okamstudio** [comment]
We were checking with Ariel today, and probably the best (and by far the
simplest) way to implement this is not with OpenAL but using the native
WebAudio API and inline javascript as an AudioServer implementation. The
native WebAudio api is extremely powerful and supports pretty much
everything Godot AudioServer supports, including loops and filters:

https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer

And Inline javascript seems pretty simple too:

http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-call-javascript-from-native




On Tue, May 26, 2015 at 2:01 PM, Juan Linietsky <notifications@github.com>
wrote:

> the problem is that any glitch in the javascript or small delay will cause
> audio corruption unless you use a bigger buffer size, and if you use a
> bigger buffer size the audio will be considerably delayed.. this is why
> games run audio in a thread
>
>
> On Tue, May 26, 2015 at 1:58 PM, macramole <notifications@github.com>
> wrote:
>
> > What if we can get enough performance this way ? We won't be mantaining
> > two AudioServers and endusers will get all features
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/pull/1989#issuecomment-105602151>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/1989#issuecomment-105602887>.
>



-- 

*OkamStudio*

**Comment by macramole** [comment]
Using WebAudio directly sounds like a good idea (no pun intended), according to [can i use](http://caniuse.com/#feat=audio-api) will work crossbrowser, I wonder if there are (or will be) differences between implementations.. that would be a bummer

I also wonder if it isn't possible to use a webworker to play the audio using WebAudio and keep using current AudioServer

Sorry I'm being so stubborn about keep using current AudioServer, but I don't see how maintaining two of those is a good idea

**Comment by reduz** [comment]
A webworker might work, and we considered this, but in this case I think
using WebAudio is the safest bet. Audio needs to be processed properly and
realtime, and even Javascript itself is jut not good at this.

AudioServer is also not a big class (compared to other severs such as
Physics or Visual, which are huge) so reimplementing the API should not
take long.

**Comment by okamstudio** [comment]
This should explain better why mixing audio directly in a worker thread is
still not a good solution to the problem:

http://www.cs.cmu.edu/~rbd/papers/latency98/latency98.htm

In short, to mix audio at relatively low latency you need a thread with
certain priority (generally managed by the driver), that does not perform
system calls. This probably is impossible to do in Javascript and
implementation dependent at best.  Using WebAudio, the browser will ensure
that Audio is being handled properly from it's side.


On Wed, May 27, 2015 at 2:06 PM, Juan Linietsky <notifications@github.com>
wrote:

> A webworker might work, and we considered this, but in this case I think
> using WebAudio is the safest bet. Audio needs to be processed properly and
> realtime, and even Javascript itself is jut not good at this.
>
> AudioServer is also not a big class (compared to other severs such as
> Physics or Visual, which are huge) so reimplementing the API should not
> take long.
>
>
>
> On Wed, May 27, 2015 at 1:59 PM, macramole <notifications@github.com>
> wrote:
>
> > Using WebAudio directly sounds like a good idea (no pun intended),
> > according to can i use <http://caniuse.com/#feat=audio-api> will work
> > crossbrowser, I wonder if there are (or will be) differences between
> > implementations.. that would be a bummer
> >
> > I also wonder if it isn't possible to use a webworker to play the audio
> > using WebAudio and keep using current AudioServer
> >
> > Sorry I'm being so stubborn about keep using current AudioServer, but I
> > don't see how maintaining two of those is a good idea
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/pull/1989#issuecomment-105994332>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/1989#issuecomment-105998408>.
>



-- 

*OkamStudio*

**Comment by macramole** [comment]
Ok then, will check this out next week, will post here if I arrive
somewhere. Godspeed.

2015-05-28 9:58 GMT-03:00 Okam Studio <notifications@github.com>:

**Comment by macramole** [comment]
Ok then, I've been studying audio_server and audio_server_sw closely and I think I'm starting to understand what have to be done.  I made a couple of tests using only js and loading an audio file and play it using Web Audio API, as well as doing the same in emscripten.

I've seen that sounds arrive at audio_server like a buffer, an array of decoded (or "raw") audio data. I think I can fill a Web Audio buffer using this data and then play it. Is that what you guys were thinking ? Or should I decode audio files directly from the WebAudioAPI and bypass libraries like Theora ?

Cheers !

**Comment by okamstudio** [comment]
The sample API is as you describe, you get audio buffer data from C++ and
you have to convert it to Javascript.

For OGG and other formats what you get is an AudioStream, you can get those
mixed in the main thread because they are high latency (high buffering).
You can use the same code in AudioServerSW to mix them and just push them
using a queue or streaming interface (I remember reading abot that). This
is probably much eaier than the voice API.

I suggest you first try to get the sample/voice API working, since this is
what will be the most work, then adding the AudioStream API


On Mon, Jun 1, 2015 at 1:38 PM, macramole <notifications@github.com> wrote:

> Ok then, I've been studying audio_server and audio_server_sw closely and I
> think I'm starting to understand what have to be done. I made a couple of
> tests using only js and loading an audio file and play it using Web Audio
> API, as well as doing the same in emscripten.
>
> I've seen that sounds arrive at audio_server like a buffer, an array of
> decoded (or "raw") audio data. I think I can fill a Web Audio buffer using
> this data and then play it. Is that what you guys were thinking ? Or should
> I decode audio files directly from the WebAudioAPI and bypass libraries
> like Theora ?
>
> Cheers !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/1989#issuecomment-107629873>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
Well guys, closing this as it was commited to github a proper [AudioServer using WebAudio](
https://github.com/okamstudio/godot/blob/master/platform/javascript/audio_server_javascript.cpp)

**Pull request closed without merging**
