### PR TITLE
Reworked Particle Turbulence

### PR DESCRIPTION
**Pull request by RPicster**
This is a rebase of #64606 

@QbieShay asked me if I could rebase the original PR and have a final look over it as @KdotJPG was not responding and 4.1 comes closer ;)

Everthing works, looks good and I adjusted some mismatches between default values and values in the docs.
I also changed the default value for the `turbulence_noise_speed_random` as it made no sense to have no movement by default - And it also had default movement in the old version of the turbulence.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Review by Calinou — APPROVED** [review]
See https://github.com/godotengine/godot/pull/64606#issuecomment-1528896306 for performance figures.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Lippanon** [comment]
Does this break compatibility for existing projects that use particle turbulence? Thanks.

**Comment by clayjohn** [comment]
> Does this break compatibility for existing projects that use particle turbulence? Thanks.

Nope

**Comment by QbieShay** [comment]
@KdotJPG thanks to you for all the back and forth before!

**Pull request merged**
