### PR TITLE
Workaround for IME on Linux.

### LINKED ISSUE #29: IME support for non-latin Unicode characters (CJK, Arabic, etc.)
Trying to type Chinese, Japanese or Korean in OSX fails in the editor fails. 

In other words, make a Button, click on the text field, try to type ロード. It doesn't work. Copying from somewhere else and trying to paste it in doesn't work either.

### PR DESCRIPTION
**Pull request by sowfelicity**
X11(fixes #29):
    
        Workaround for supporting input method frameworks like SCIM,
        IBus, Fcitx, etc.
    
        The locale is set when the application starts.
    
        Workaround for input when the input context within the specified
        input method is not available.
godot-xim

### CODE REVIEW

**Comment by vnen** [comment]
Wow, that seems awesome! Though the commit title is not descriptive and the clang-format is not happy. Can you fix the issues and amend the commit? Check [the PR workflow doc](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html) for help if needed.

**Comment by sowfelicity** [comment]
Thanks. I have just amended the commit with the commands in [that page](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by Geequlim** [comment]
Wow, this is awesome!
I'm doing the same thing yesterday but you g0t it and better progress then mine.

**Comment by Geequlim** [comment]
screen 5
Tested with fcitx, it works fine.

**Comment by reduz** [comment]
Apologies, I had to revert this. It seems to not be sending echo in the inputkey events properly. 
X11 is pretty complex and i'm not sure how the IME stuff works, so would be glad if you can give a check to this and attempt PR again when fixed.

**Comment by reduz** [comment]
for more clarification, echo events are being sent, but are absent the echo property

**Comment by sowfelicity** [comment]
Sorry, I hadn't check the old code sending echo. It seemed that the old implementation didn't check the type of the event after KeyRelease. The next event may not be KeyPress when the IME is activated. I will try to fix it and attempt PR again.

**Comment by Geequlim** [comment]
@sowfelicity If you fix that please tell me as #9366 is base on this functionality.

**Comment by sowfelicity** [comment]
No problem.

**Pull request merged**
