### PR TITLE
Rename queue_delete => queue_free

### PR DESCRIPTION
**Pull request by Zylann**
To match C++ and API names

### CODE REVIEW

**Comment by kleonc** [comment]
`Node::queue_delete` was already binded as `queue_free` so the rename done shouldn't break anything.

---

Some thoughts about potential further changes:
- there's still `SceneTree::queue_delete(Object)` but it's exposed as `queue_delete` so renaming it to `queue_free` would be a breaking change,
- the fact that `SceneTree::queue_delete` takes in an `Object` makes me think whether there should be `Object::queue_free` added (which `Node::queue_free` could be overloading).

**Comment by Zylann** [comment]
> the fact that SceneTree::queue_delete takes in an Object makes me think whether there should be Object::queue_free added (which Node::queue_free could be overloading).

That's not possible because Objects don't sit inside a scene tree. It would assume that there is only one SceneTree globally accessible somehow, which is pretty bad practice.

**Comment by kleonc** [comment]
> That's not possible because Objects don't sit inside a scene tree. It would assume that there is only one SceneTree globally accessible somehow, which is pretty bad practice.

Indeed. Just a note that exactly such bad practice is already being practised for the nodes not in the scene tree (so the "bad practice" itself would probably be nonblocker):
https://github.com/godotengine/godot/blob/dc4b6165962536b53c4c1471fcf0be43c70e2335/scene/main/node.cpp#L2572-L2578

Anyway, by any means I'm not saying `Object::queue_free` should be added. It just went through my mind and I shared the thought. Same as you I can't see an actual use case for it.

**Comment by KoBeWi** [comment]
> there's still SceneTree::queue_delete(Object) but it's exposed as queue_delete so renaming it to queue_free would be a breaking change,

I think this is fine, because it does a different thing than `queue_free()`.

**Review by KoBeWi — APPROVED** [review]
Makes sense, needs rebase.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
