### PR TITLE
Adjust orthographic camera gizmo with respect to `keep_aspect` setting

### LINKED ISSUE #90589: Orthographic camera gizmo does not respect "keep_aspect" setting
### Tested versions

Reproducible in 4.2

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5161) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

The gizmo for orthographic cameras does not respect the `Keep Aspect` setting, and always behaves as though it is set to `Keep Width`. This does not affect the runtime behaviour, although it does mean the gizmo is inconsistent with the runtime behaviour.

### Steps to reproduce

- Make an orthographic camera with `Keep Aspect` property set to `Keep Height`.
- Adjust its `Size` property, preferrably with a visible grid.
- Notice how the gizmo's width, and not its height, will match the size that was set.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/90589

### CODE REVIEW

**Comment by MajorMcDoom** [comment]
Thanks for tackling this!

A couple of issues:
- When using `Keep Height`, the aspect ratio is no longer maintained. Instead, it's always a square.
- When using `Keep Height`, the handle is still placed on the right side of the gizmo, instead of on the top. This means it's visually reflecting the width, and using that resulting value to set a value that will become the height, which is wrong.
CameraAspectBug

**Comment by MajorMcDoom** [comment]
I've attached an image of the expected behaviour when the size is set to `2.0`. Hope this helps!
CorrectBehaviour

**Comment by jsjtxietian** [comment]
I see, thanks for your help! The handle should be a easy fix, I will dig a little more about the aspect ratio issue.

**Comment by MajorMcDoom** [comment]
> I see, thanks for your help!
> 
> It should feel more correct now.

Works correctly now as far as I can tell! Just waiting for a review now. Thanks again. :)

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected. Both Keep Height and Keep Width orthgographic gizmos render correctly now, even if the base aspect ratio is changed in the project settings (when changing the window width/height project settings).

Code looks good to me.

Before | After
-|-
Before | After

Example of the sizes being correct now:

Screenshot_20240807_015230 png webp

Screenshot_20240807_015240 png webp

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
