### PR TITLE
Added Fresnel and OneMinus to visual shaders

### PR DESCRIPTION
**Pull request by Chaosus**
@ilyafuu is terrorized me with the ask to implementing these functions, so I've decided to stop this..

The Fresnel effect (placed in Special tab)

image

OneMinus is just (1 - value) - Function exist in UE4 so why not.. Placed in Scalar->Functions and Vector->Functions

### CODE REVIEW

**Comment by Zireael07** [comment]
Fresnel is great, one minus is seriously... unneeded bloat?

**Comment by Chaosus** [comment]
for the same reason the Reciprocal is exist (which is 1 / value)

**Comment by Chaosus** [comment]
If the stars are lit, then someone needs it, I think its ok to merge..

**Comment by groud** [comment]
I would not have added OneMinus personally, I think this is bloat too.

But please, do not merge your own PRs, that's really not how things should be done. Unless a change is pretty urgent or it has been discussed in a PR review...

**Comment by groud** [comment]
> then someone needs it, I think its ok to merge..

And no, seriously not. If we added a feature every time only one person asked for it, the engine would be a pile of bloat.

**Comment by Chaosus** [comment]
Really sorry, @groud, should I remove this feature ?

**Comment by groud** [comment]
> Really sorry, @groud, should I remove this feature ?

No problem. I don't know, I will let @akien-mga decide what to do.

**Pull request merged**
