### PR TITLE
Fix performance issue reimport file reload scene

### LINKED ISSUE #95104: Severe regression in asset import speeds
### Tested versions

- Reproducible in: v4.3.rc2
- Not reproducible in: v4.2.2.stable

### System information

Godot v4.3.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6070) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

First off, I will say that it feels like pretty much *everything* is slower in 4.3. Even simple things like changing project settings. But this one is the most egregious - it completely annihilates iteration speed.

4.2 import times:

https://github.com/user-attachments/assets/fd566595-1e3f-426a-b07f-d63618c941ab

4.3 import times:

https://github.com/user-attachments/assets/c84fd29b-e299-4774-8214-62e40d83ae88

It applies to all kinds of assets - so even something like creating a new material involves wait times of up to a minute.

### Steps to reproduce

I have not confirmed yet, but the issue seems to only show up on large projects.

On [Crater-Province-Level](https://github.com/Jamsers/Crater-Province-Level), to reproduce the video example:

- Open project in Godot
- Open `Asset Sources/Model/Tunnel_All.blend` in Blender
- Export as glTF to `Models/Tunnel_All.glb`
- Switch back to Godot window and wait until scene window is responsive again

### Minimal reproduction project (MRP)

Crater-Province-Level:
[`test-4.2`](https://github.com/Jamsers/Crater-Province-Level/tree/test-4.2) branch

### PR DESCRIPTION
**Pull request by Hilderin**
- Fixes #95104

This PR should significantly improve performance when reimporting assets with the auto-reload of scenes.

### What has been done:
- **Addition and removal of the reloaded scene in `EditorNode::preload_reimporting_with_path_in_edited_scenes`**: It takes 7-8 seconds on my PC just to remove and re-add the scene. This part should not require the scene to be in the tree to load the modified properties and nodes to reimport. I had to modify `EditorNode::get_preload_scene_modification_table` to use `get_transform` instead of `get_relative_transform`. I don't know why `get_relative_transform` was used, but in my tests, it works fine with `get_transform`. Additionally, when the transform is restored, it uses `set_transform`.
- **Adjustment in `EditorNode::reload_instances_with_path_in_edited_scenes`**: The addition and removal of the reloaded scene have been minimized. The current edited scene should almost never be removed unless another scene that needs to be reloaded has the same name.
- **Modification in `EditorNode::_set_current_scene_nocheck`**: The addition and removal of the reloaded scene have been removed if the same scene is reloaded.
- **Replacement of `EditorNode::update_node_reference_modification_table_for_node`**: This method has been replaced by `EditorNode::get_preload_modifications_reference_to_nodes`, which now runs in the preload and loads only modified properties that reference reimported nodes. Previously, it loaded every property modification in the scene, taking about 10 seconds. Now, it takes around 7 seconds in debug mode. The main issue was the call to `p_node->get_property_list` for each node in the scene. I have not found a better solution to optimize this.
- **Added progress popups**: These display visual feedback to the user before and during the reloading process.

### Tested
- I retested with the MRP (https://github.com/Jamsers/Crater-Province-Level/tree/test-4.2).
- I retested with the test project from #90531 with some minor modifications: [test-godot-blender-reimport-missing-node-v5.zip](https://github.com/user-attachments/files/16517581/test-godot-blender-reimport-missing-node-v5.zip).

### Known issues
- On my PC, opening Godot on startup with the MRP is very slow. Commenting out the method `Node3DEditor::_request_gizmo` removes 15 seconds from the startup time.
- I created issue #95221 for signals that never disconnect and accumulate on nodes.
- Adding and removing scenes with many nodes is slow. Just switching scene tabs can take 5-6 seconds. Most of the time is spent in `add_child` and `remove_child`.

I will not work on these issues for now, as I think the current performance of this PR is acceptable.

### Time
Reloading an asset in the MRP (debug dev build):
- Before: 5 min. +
- Now: 10-12 sec.

Reloading an asset in the MRP (prod build):
- Before (4.3 rc2): 3 min. +
- Now (artifact from the PR): 4-6 sec.

With the artifact from the PR:

https://github.com/user-attachments/assets/9ac6be44-3607-4269-b8b2-67ef4942ff1d

### CODE REVIEW

**Comment by Calinou** [comment]
> On my PC, opening Godot on startup with the MRP is very slow. Commenting out the method Node3DEditor::_request_gizmo removes 15 seconds from the startup time.

See https://github.com/godotengine/godot/issues/94648.

**Comment by akien-mga** [comment]
Thanks so much for working on this @Hilderin, you're once again saving the 4.3 release :1st_place_medal: 
This regression is the main release blocker left IMO, so once we have this merged we should hopefully be good to go :crossed_fingers: 

I'll try to give this a quick test and superficial review, and aim to merge it today so I can release `4.3.rc3` tomorrow as hopefully the "final FINAL v3 final.psd" RC!

**Comment by akien-mga** [comment]
- Test with https://github.com/Nodragem/twin-stick-shooter-starter-kit which I had laying around (I'm on 5G now so can't download big MRPs).

Modifying all `.gltf` files to add a space at the end and thus trigger a reimport (`for file in $(find -name "*.gltf"); do echo " " >> $file; done`):

Current `master`: 13 s 870 ms (dev build), 5 s 380 ms (optimized build)
This PR: 5 s 410 ms (dev build), 3 s 870 ms (optimized build)

- Test with (private, for now) W4 demo Project Genesis, modifying the massive `FortifiedCastleTown.gltf` file to add an empty space and trigger a reimport.

Current `master`: More than 8 min, I gave up (optimized build)
This PR: 1 min 34 s (optimized build)

Seems pretty drastic!

I've also done a cursory review of the code, looks fine to me overall, but I'm no expert in this part of the engine.

**Comment by clayjohn** [comment]
I have tested this PR and confirm that it fixes the performance and brings things in line with expectations (3+ minutes down to 7 seconds). 

On my device, initial import of the entire project is about 45 seconds (25 seconds to import + 20 seconds to open the scene). 

On master re-importing a single mesh took 3+ minutes and with this PR the one i tested took 7 seconds.

**Review by akien-mga — APPROVED** [review]
Approving based on my above test and quick review.

Clay also mentioned having very good results with the MRP and an optimized build.

**Comment by akien-mga** [comment]
Thanks! Amazing work once again :tada:

**Comment by Hilderin** [comment]
Thanks!! Unfortunately, I found a problem in this PR when multiple file are reimported at the same time. I created a small PR to fix that: #95264

**Pull request merged**
