### PR TITLE
[4.2] Fix shader cache with transform feedback on some Android devices

### PR DESCRIPTION
**Pull request by Arthas92t**
Fix issue #82419 tested on vivo 1907, vsmart active 3, samsung a12

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks for contributing and welcome!

The rendering team will have to address the code change specifically, but there's a few form issues with this PR that also needs to be addressed:
- PRs should be made against the `master` branch. The production team will then cherry-pick relevant fixes to actively maintained stable branches once they are fixed in `master`. If we only merged this in `4.2`, it means the bug would still exist when 4.3 is released.
  * The simplest way to fix this would be for you to make a new PR from another branch based off `master`. It's recommended to make commits from a dedicated branch for each PR, instead of making it from your fork's `master` branch (which would make it tricky for you to make other PRs until the first one has been merged).
- Your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by Arthas92t** [comment]
Sorry, it's the first time i contribute something to github. Most time i work with local and private git. I will change this in the next PR

**Comment by Mickeon** [comment]
image
You may have accidentally changed the branch, it should still be `master`

**Comment by Arthas92t** [comment]
Yep, i think i misunderstood the meaning of that button, i was trying to change this PR to master. This commit should work on both master and 4.2 branch

**Comment by akien-mga** [comment]
If you change the target branch to `master`, you need to force push your fork's `4.2` branch (used for this PR) with the commit rebased on top of `master`. That's why I suggested making a new PR instead.

The PR might show just 1 commit, but in actually it's asking to merge a **branch** into another branch. We can't merge your `4.2` branch into `master`, it contains hundreds of commits which are not in `master`.

**Comment by Arthas92t** [comment]
closed this one and move to #88573

**Pull request closed without merging**
