### PR TITLE
[NET] Multiplayer replication interface, spawner and sync nodes.

### PR DESCRIPTION
**Pull request by Faless**
Tentative implementation of godotengine/godot-proposals#3459

Summary
---

Overall, the PR should bring all the features that are in the current prototype (i.e. the `MultiplayerReplicator` in master), plus:
- the ability to configure it via nodes (`MultiplayerSynchronizer`/`MultiplayerSpawner`).
- syncing scenes without spawning them (i.e. `MultiplayerSynchronizer`'s that are not "spawned" but present in both peers).
- Much better control over what and where you spawn (via the `MultiplayerSpawner`).

Internally, the biggest difference (beside refactoring), is that each replicated object is assigned an ID by the authority, so:
- each "sync" is now composed per-peer, and contains a variable number of objects.
- we can control the size of each sync packet, and know when is the last sync that contained a given object (which should give us capabilities in terms of interest management and bandwidth control).

It is still not a fully featured version, but after 2 months of "undercover work" I really need to get this out :).

Details
---

- Initial implementation of the MultiplayerReplicationInterface and its default implementation (SceneReplicationInterface)
  - Note: The GDVirtual part (i.e. overriding its methods) is not yet bound, but will be once the PR is finalized.
- `MultiplayerSpawner`: supports both custom spawns via the `_spawn_custom` virtual function, and optional auto-spawn of known scenes
  - `_spawn_custom` takes a variant parameter that will be passed along to the remote peer (I didn't use variable arguments, because GDScript does not support it, use an array for multiple parameters).
  - Auto-spawned scenes are handled via a TypedArray<PackedScenes> property of the spawner node (and a auto_spawning boolean).
- `MultiplayerSynchronizer`: supports both sync and spawn properties (the latter, only sent/applied when spawned via a MultiplayerSpawner).
  - Configured via a `SceneReplicationConfig` resource, it can also sync via path (i.e. without spawn if both peers has it in tree), but will not send the spawn state in that case, only the sync state.
- `ReplicationEditorPlugin`: Editor plugin to allow configuring the `MultiplayerSynchornizer` in a way similar to `AnimationPlayer`.
  - Will need some help from a Editor/UI/UX contributor.
  - Uses inspector `keying` functionalities, which has been slightly refactored.
  - I'm quite bad a UX, but I guess this is a start. Nice things to add would be:
    - Moving properties up/down in the list.
    - Adding custom proprties not visible from the editor (i.e. not exported, so not available via keying).

Notable design changes from the interface compared to the proposal (godotengine/godot-proposals#3459):

- The `_on_*_send` functions has been renamed to:
  - on_spawn -> When the spawner spawns a node (either via custom spawn, or via )
  - on_despawn -> When the spawner detects a spawned node has been deleted, and should be despawned remotely.
  - on_replication_start -> When a synchronizer enters tree.
  - on_replication_stop -> When a synchronizer exits tree.

Those functions takes 2 paramers, the node, and a second "config" parameter (which is, in fact, either the MultiplayerSpawner or the MultiplayerSynchronizer).
The `_on_receive_*` functions will likely not be needed, like the `send_*` functions.
Sending/receiving custom messages should instead be better supported by the MultiplayerAPI (already possible via "send_bytes" but a bit tricky to route on receive).

Known limitations (which I plan to fix)
---

- The tick rate for syncing is fixed, and is currently done during idle time (i.e. at your FPS rate).
  - This should be of course configurable, for now, synchronizers can specify the update frequency in milliseconds (still subject to FPS limit).
- `MultiplayerReplicationInterface` is not yet extensible. Mainly because it's still not finalized, ideally, all virtual functions will be overridable.
- Spawn and sync always happens to all peers.
  - This is mostly a matter of designing the interface for it, because the underlying implementation can support it (since it manage spawn/sync per peer).
  - Will likely need a dedicated proposal on how we want to deal with it. I.e. groups, layers, custom functions, etc.

Special considerations
---

There are a few behaviours that might warrant extra discussions.
The most pressing for me, is what to do with **spawned nodes** after a disconnection.
The system currently queue_free them if they were spawned by a remote, since they are not relevant to the disconnected state, but one could argue it could be useful to keep them for cases where you have a single player failover.
The system, on the other hand, does not queue_free nodes that where spawned locally (as they are part of the local session).
Again, I am conflicted regarding this behaviour, because on one hand it saves the end user some bookkeeping, but on the other it might actually feel like an "unexpected behaviour".

### CODE REVIEW

**Comment by Faless** [comment]
I have ported the multiplayer bomber demo to use the new spawn/replication system.
It showcases both auto spawn (players) and custom spawn (bombs).

[multiplayer_bomber.zip](https://github.com/godotengine/godot/files/7717057/multiplayer_bomber.zip)

**Comment by Faless** [comment]
Added `replication_interval` to specify the update interval in milliseconds in each synchronizer.
This could potentially be done better (but less intuitively) via a `sync_period` where `1` means every tick, `2` every 2 ticks, etc...

**Comment by Calinou** [comment]
> Added `replication_interval` to specify the update interval in milliseconds in each synchronizer.

Should the interval be defined in seconds with a float instead?

**Comment by Faless** [comment]
> Should the interval be defined in seconds with a float instead?

I don't see any good reason to.

**Comment by Faless** [comment]
> So the user might set:
> `$sync.replication_interval = 0.0005` and that's not going to be representable in milliseconds, thus:
> `print($sync.replication_interval)` will then either return `0` or `0.001`.

Note that if this is fine from a usability point of view, I don't mind changing it.

I still find it weird to express in seconds a quantity that you 99% of the time will be less than a second, but I guess that's more like a personal view.

**Comment by Calinou** [comment]
> Do people more often says "it should take 0.016 seconds to render a frame`, or "it should take 16 milliseconds to render a frame"? Because it seems to me, that in this topic, no one reason in seconds, but I might be biased.

It's true that people (myself included) think in milliseconds more often for short durations. However, I personally value API consistency over using intuitive durations. There is no perfect choice here, but I feel that using durations in seconds in some places and durations in milliseconds in others is error-prone.

**Comment by Faless** [comment]
> However, I personally value API consistency over using intuitive duration units.

Well, the fact is that that value is used in conjunction with `OS::get_ticks_msec()`, which uses an integer, and it really should not be converted to `double OS::get_ticks_sec()` (and in fact is not). So, consistency for the sake of consistency at the cost of both usability and performance is just bad.

> If you still want to use an integer value, I guess you could let users define a frequency in Hz instead. This is what we do for the **Force Fps** and **Physics Fps** project settings after all

Yeah, this is probably the way to go.

**Comment by Faless** [comment]
I converted the value to double (seconds), and added an extra method for performance.
I don't want this PR to stall for such a thing, and using Hz is still a bit tricky.

**Comment by Faless** [comment]
I think this is now in a good spot for a review.
Some things are still missing (mainly exposing the interface to GDExtension, and interest management).
Assuming this is approved I can add the GDExtension as a final commit, and we can start working on interest management in a separate PR

**Review by mhilbrunner — APPROVED** [review]
Finally got some time yesterday to play around with this and review the code. Good work! Docs need to be added once this is merged :)

**Comment by Faless** [comment]
Updated to use #57541 .
I think this is pretty much ready.
It's still missing the GDExtension part (I'll open another PR, since I'll take the chance to also refactor the MultiplayerAPI source a bit more to also address #53295).
On the topic of interest management I'll make a proposal to summarize to the discussion in the `#networking` channel (and in preparation of (finally) a new meeting later this month).

**Review by akien-mga — APPROVED** [review]

**Comment by Faless** [comment]
See the attached demo for a bomber version using path-only synchronizer to also synchronize client controls:
[multiplayer_bomber_spawn_node.zip](https://github.com/godotengine/godot/files/8005765/multiplayer_bomber_spawn_node.zip)

**Comment by Norrox** [comment]
Nice! thanks! will try this asap!

**Comment by feetuh** [comment]
> See the attached demo for a bomber version using path-only synchronizer to also synchronize client controls: [multiplayer_bomber_spawn_node.zip](https://github.com/godotengine/godot/files/8005765/multiplayer_bomber_spawn_node.zip)

I tried this demo on Godot_v4-alpha2 and things seem to work well when running the project from the editor. However, I exported the project to a Windows build and the rock-breaking logic seems to malfunction when running the exported version. Rocks will no longer break from bombs. I also tried a combination of running 1 instance from the editor and the other as the exported executable. In this scenario, the bomb breaks the rock on the editor instance but not on the executable. Neither player can walk past where the rock is/was and seem to collide with it.

Is this likely to be an issue with the bomber demo or with the Godot_v4-alpha2?

**Comment by aaronfranke** [comment]
> @Faless I have ported the multiplayer bomber demo to use the new spawn/replication system.
> It showcases both auto spawn (players) and custom spawn (bombs).

Can you PR this to the `4.0-dev` branch of the Godot demo projects repo?

**Comment by Faless** [comment]
> Can you PR this to the `4.0-dev` branch of the Godot demo projects repo?

Sure thing :) https://github.com/godotengine/godot-demo-projects/pull/717

**Comment by far** [comment]
@Faless 
Thank you for your Bomber example, I have some questions about it.
You set **auto-spawn:true** for PlayerSpawner with binding to its scene in UI (inspector) and custom spawning by explicite call .spawn() for BombSpawner.
But you dont use **PlayerSpawner** for Players in code - you instantiate its scene ( in gamestate.begin_game() ) and add it as childs to main scene.
Why auto_spawn:true is needed and PlayerSpawner by itself if you do it by code?
May be you would like to show different ways to spawn?
How auto spawning works?
I found in docs that syncing **SPAWN** parameters (in replication config) syncs only via Spawner instance. So in your case they will be not synced? 
Or there is some magic under the hood?
It might be not critical for this game because they starts to sync after spawning.

**Comment by Faless** [comment]
@far the demo code might be outdated, the updated demo is here: https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/networking/multiplayer_bomber

**Comment by far** [comment]
@Faless I used this last version you mentioned.
spawning players without PlayerSpawner:
https://github.com/godotengine/godot-demo-projects/blob/4.0-dev/networking/multiplayer_bomber/gamestate.gd#L128

**Comment by Faless** [comment]
`MultiplayerSpawner` supports both custom spawns via the `_spawn_custom` virtual function, and optional auto-spawn of known scenes.

- ` _spawn_custom` takes a variant parameter that will be passed along to the remote peer.
- Auto-spawned scenes are handled via a `TypedArray` property of the spawner node (and a `auto_spawning` boolean).

In both cases, SPAWN variables in the replication config will be sent remotely.

>  It might be not critical for this game because they starts to sync after spawning.

Spawn and sync will reach the client at different times, so you will end up with the first few frames in the client not having those properties set.

**Comment by far** [comment]
BTW it doesnt work with last version (alpha 9) but I didnt see any updates with Network, may be some core changes affects.

**Comment by ottovw** [comment]
@Faless thanks for your work! Is there any documentation for usage available? Besides the bomber demo.

**Comment by greenfox1505** [comment]
Is there any plan for this tool to offer interpolation instead of direct sync at framerate?

**Comment by Faless** [comment]
> Is there any plan for this tool to offer interpolation instead of direct sync at framerate?

Not as an "instead of" but likely a per-property option to interpolate between the current and received value (which you now have to do manually).

**Comment by greenfox1505** [comment]
Sure. "Instead of" was the wrong phrasing. I built a tool for arbitrary property replication for Godot3 and I abandoned it when I saw some of these features. I thought I saw a mock-up of set vs interpolation properties but maybe I was mistaken.

In the meantime, I have a concern that it's hard to write an interpolation system based on this without some sort of signal from the node that a property was set. Sure, I could just detect differences and then interpolate between, if an object stops moving it's going to look exactly the same as if I was dropping packets. Maybe I could use a setter to reset the interpolation timer? Seems like a ugly work around for what should just be part of it.

**Comment by Faless** [comment]
> I have a concern that it's hard to write an interpolation system based on this without some sort of signal from the node that a property was set.

We can probably add a `sync_received` signal to the synchornizer.

> Maybe I could use a setter

Yes, you can use setters to detect syncs. but you probably want to be notified once per sync (when it finishes), so right now you can do that by adding a setter to the last property in the sync properties list.

Adding a signal to MultiplayerSynchronizer is probably the best course of actions.

**Comment by noverd** [comment]
I use Multiplayer Synchronizer to synchronize variables with my classes, but Multiplayer Synchronizer doesn't work with them, what should I do? I definitely need these classes, I implement ss13 in godot

**Pull request merged**
