### PR TITLE
Optimize String.humanize_size()

### PR DESCRIPTION
**Pull request by MewPurPur**
Might seem like grasping, but this function is surprisingly hefty for a String method.

Using this method 1000 times used to take ~3 ms in production builds and ~7.6 ms in unoptimized development builds. Now it's ~1.8 ms in unoptimized development builds.

So this PR makes String.humanize_size() 4 times faster.

### CODE REVIEW

**Comment by AThousandShips** [comment]
You included your icons PR

**Comment by MewPurPur** [comment]
Again? I don't know why this is happening, let me find how to fix it

**Comment by AThousandShips** [comment]
You were probably working on your other PR and forgot to `git checkout master`, you can fix it by doing `git rebase -i master` and `drop` that commit :)

**Comment by AThousandShips** [comment]
Superseded by:
* #84462

**Pull request closed without merging**
