### PR TITLE
Refactor Font configuration and import UI, and Font resources.

### PR DESCRIPTION
**Pull request by bruvzg**
Supersede #61406, Supersede #61473, Supersede #62065

- Merges all import time properties of `Font` and `FontData` into single Font resource. Including fallback font list and pre-rendered glyphs (different sets of pre-rendered glyphs can be selected for different sizes/variations).
- Adds `FontVariation` subclass to access OpenType variations, embolden/slant, font collection face index, OpenType features, and extra spacing and allow fallback override in runtime.

New font resources structure:
Screenshot 2022-07-06 at 14 04 28

`FontVariation` screenshot:
Screenshot 2022-06-16 at 16 27 58

### CODE REVIEW

**Comment by sairam4123** [comment]
Can font size be changed for per control node?

**Comment by bruvzg** [comment]
> Can font size be changed for per control node?

It's already possible with the Theme properties and not changed by this PR.

**Review by reduz — DISMISSED** [review]
It looks good to me, but I have the feeling that using FontBase all across the codebase probably is a bit unnecesary since we don't do this with other resource types (like Texture2D, AudioStream, Mesh, etc).

Maybe we should do 

FontBase -> Font (abstract)
Font -> FontFile or VectorFont or maybe just ScalableFont (which is the technical name for OTF/TTF/etc).

**Comment by bruvzg** [comment]
> FontBase -> Font (abstract)
> Font -> FontFile or VectorFont or maybe just ScalableFont (which is the technical name for OTF/TTF/etc).

OK, I'll change it to `Font` and `FontFile` (the same class is used for bitmap fonts, so it's not always scalable).

**Comment by reduz** [comment]
@bruvzg Alright, sorry for the change request and great job!, realized we were no longer using resources with "Base" naming in 4.0 too late so my mistake.

**Comment by bruvzg** [comment]
> I'll change it to `Font` and `FontFile`

Done.

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
