### PR TITLE
Use libyuv library for YUV->RGB conversion

### PR DESCRIPTION
**Pull request by zaps166**
Add only necessary files and SCsub file. Remove `yuv2rgb.h` and use `libyuv` in Theora.

This improves performance and will be also used in the WebM driver.

### CODE REVIEW

**Comment by zaps166** [comment]
Btw. it could be done in GLSL, see: https://github.com/zaps166/QMPlay2/blob/master/src/modules/OpenGL2/GLSL/YCbCr.frag, but it needs additional shader for it and probably a lot of GLES changes.

**Comment by zaps166** [comment]
@reduz Is it difficult to do YUV->RGB conversion in Godot using GLSL instead of doing it on CPU (the conversion shader is very simple)?

**Comment by zaps166** [comment]
Hmm, `libyuv` can be applied anytime later, so WebM module can now use old `yuv2rgb.h` code - e.g. it simplifies code rebase. Anyway I think that using GLSL for this is much better idea that using `libyuv` :)

**Comment by akien-mga** [comment]
So I'm a bit lost here, is this PR still relevant, or should it be replaced by a GLSL implementation? If the latter, it's maybe best to close this PR and open an issue instead detailing what needs to be done, and what is the potential gain from doing it?

**Comment by zaps166** [comment]
IMHO GLSL is better :)

**Comment by akien-mga** [comment]
Could you open an issue about it so that it can be investigated and implemented? Will close this PR, but feel free to reference it from that new issue.

**Pull request closed without merging**
