### PR TITLE
Remove extra margin in the top of the debugger

### PR DESCRIPTION
**Pull request by YeldhamDev**
Present since a very long time.

### CODE REVIEW

**Comment by reduz** [comment]
pics or didn't happen

**Comment by YeldhamDev** [comment]
Fair enough, here's 3.2:
Screenshot_20200222_185618

And here's master with my commit:
Screenshot_20200222_185844

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Pull request merged**
