### PR TITLE
Fix iOS safe area insets to use pixels and not points

### PR DESCRIPTION
**Pull request by endragor**

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @samgreen

**Comment by endragor** [comment]
It's more of a bugfix rather than an enhancement - previously returned safe areas were incorrect.

**Comment by samgreen** [comment]
Looks great to me

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.0.7.

**Pull request merged**
