### PR TITLE
Add barycentric_coordinate function to Geometry

### PR DESCRIPTION
**Pull request by jknightdoeswork**
I added a new function to Geometry that returns the barycentric coordinate for a point within a triangle, and added documentation for the new function.

This algorithm uses the area of a triangle, so I exposed that inside Geometry as well (and documented it).

I used the pure mathematical definition of barycentric coordinates rather than a more optimized algorithm as this implementation has more defined behavior, specifically for points that do not intersect with the triangle, in that scenario, the barycentric coordinate returned will contain a negative number, or the sum will exceed 1. Most optimized versions of this algorithm only return sensical data for the case where the point is on the triangle.

It's a useful little function for lots of rendering stuff - namely getting the UV coordinate for any point on a triangle.

We could theoretically use this calculation to refactor `ray_intersects_triangle` and `is_point_in_triangle`, but there is no real need to do that - and we'd likely want to compare the performance between the two implementations.

EDIT:
Note that some other documentation changed in this PR due to running godot --doctool .

Let me know if you need me to make a PR without those changes.

doctool caused changes in this commit:
https://github.com/godotengine/godot/pull/39553/commits/2b867251e13828bedba9a661a38fd712cd617ef7

### CODE REVIEW

**Comment by clayjohn** [comment]
You'll need to revert the accidental documentation changes. 

Most IDEs let you just right-click the line and revert them.

**Comment by jknightdoeswork** [comment]
I just pushed a revert commit to undo those doc changes. Is this PR good now clayjohn? Or would you like to rebase this so it doesnt a commit docs/revert docs?

**Comment by clayjohn** [comment]
You'll still need to rebase it. We generally want 1 commit per PR unless it is a large change that can logically be broken up into distinct commits.

Here is a helpful doc explaining how to do so.
https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by jknightdoeswork** [comment]
Thanks, @clayjohn 

I rebased it and submitted another PR: https://github.com/godotengine/godot/pull/39554

**Comment by clayjohn** [comment]
In the future, it's better to amend a commit rather than close and reopen a pull request. See https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#modifying-a-pull-request

I highly recommend reading through the entire doc as well when you have time.

**Comment by jknightdoeswork** [comment]
Ok. I'll force push the rebase should this happen again next time :)

**Pull request closed without merging**
