### PR TITLE
Add Stretch Mode description to ProjectSettings.xml

### PR DESCRIPTION
**Pull request by ghost**
image

Very well!

### CODE REVIEW

**Comment by BWPanda** [comment]
I mainly copied the description from https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html Though I note there that it still says '2D' whereas the latest version of Godot says 'canvas_items'... I assume they're the same.

**Review by MewPurPur — APPROVED** [review]
The writing is good, and I tested to confirm everything is correct.

**Review by Calinou — COMMENTED** [review]
The descriptions could be expanded upon to describe potential use cases. I'll submit suggestions once I get home, so please hold on merging this for now.

**Comment by BWPanda** [comment]
Thanks @Calinou!

**Comment by AThousandShips** [comment]
Great! Thank you I didn't feel confident in documenting this when I exposed this setting to documentation, happy to see it documented

**Comment by mhilbrunner** [comment]
The two commits need to be squashed into one and this PR needs to be amended before it can be merged :)

**Comment by BWPanda** [comment]
You can't just squash the commits when merging this PR? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits

What amendment is needed?

**Comment by MewPurPur** [comment]
https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase

This is a tutorial for how to do it.

Rebasing can be tricky if you're new to it, so please save the description before doing this.

**Comment by Calinou** [comment]
> You can't just squash the commits when merging this PR? [docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)

We don't use GitHub's squash and merge feature on the main Godot repository, since it loses the merge commit in the process. We prefer keeping the merge commit to make the Git history more self-documented (even if that makes it longer when not using the `--no-merges` option).

**Review by mhilbrunner — APPROVED** [review]

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.4.

**Pull request merged**
