### PR TITLE
Add boot splash for the Godot Android Editor

### PR DESCRIPTION
**Pull request by m4gr3d**
https://user-images.githubusercontent.com/914968/208168268-a06c79ee-8567-4d89-b14c-c13833036d8d.mp4

[3.x version](https://github.com/godotengine/godot/pull/70156)

### CODE REVIEW

**Comment by m4gr3d** [comment]
@clayjohn While testing, I noticed that the boot splash doesn't render when using the opengl3 driver. Is that a known issue?

**Comment by clayjohn** [comment]
> @clayjohn While testing, I noticed that the boot splash doesn't render when using the opengl3 driver. Is that a known issue?

I don't remember seeing a report for it, but trying it out on my device I'm definitely not seeing a splash screen

**Comment by m4gr3d** [comment]
> > @clayjohn While testing, I noticed that the boot splash doesn't render when using the opengl3 driver. Is that a known issue?
> 
> I don't remember seeing a report for it, but trying it out on my device I'm definitely not seeing a splash screen

The splash screen doesn't show for the `opengl3` driver, so it doesn't show when opening the project manager since it uses that driver by default.
If you create and edit a vulkan mobile project, then you'll be able to see the splash screen when the project is loading.

**Comment by clayjohn** [comment]
https://github.com/godotengine/godot/pull/70169 here you go should be working now

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
