### PR TITLE
Add font LCD sub-pixel anti-aliasing support.

### PR DESCRIPTION
**Pull request by bruvzg**
Implements support for FreeType sub-pixel anti-aliasing.

### Notes / Limitations:
- Display sub-pixel arrangement is not automatically detected and should be manually set using `gui/theme/lcd_subpixel_layout` project setting.
- LCD sub-pixel AA will not work correctly with scaled, rotated or otherwise transformed text (`Label3D` will it automatically, but this should be taken into account when designing 2D UI).
- Sub-pixel AA require special blending mode, therefore this PR includes some changes to the rendering pipelines to implement this mode. I have not found any issues with adding it, but it might need additional review from rendering team to ensure it's done properly.

### Demo project:

https://user-images.githubusercontent.com/7645683/185058723-aba5bccf-15e8-4960-999c-b41a320728c3.mov

[lcd-aa-test.zip](https://github.com/godotengine/godot/files/9357351/lcd-aa-test.zip)

Implements https://github.com/godotengine/godot-proposals/issues/1258

### CODE REVIEW

**Comment by Calinou** [comment]
> Display sub-pixel arrangement is not automatically detected and should be manually set on font import.

I think LCD font subpixel arrangement should be set as a project setting (including a Grayscale option which disables it for all fonts). The font import option should only be a toggle to *allow* the use of LCD subpixel hinting on a given font.

**Comment by bruvzg** [comment]
> I think LCD font subpixel arrangement should be set as a project setting (including a Grayscale option which disables it for all fonts). The font import option should only be a toggle to allow the use of LCD subpixel hinting on a given font.

Moved sub-pixel layout to the `gui/theme/lcd_subpixel_layout` project setting.

**Comment by okla** [comment]
Can `Font` size be made fractional to cope with situations like this?
CEA4ADB2-DB40-43E9-B7D9-D6F3FD795A69
https://twitter.com/nikitonsky/status/1560002022518280194

**Comment by bruvzg** [comment]
> Can Font size be made fractional to cope with situations like this?

It should be possible to use 26.6 fractional points for the font size, but that's outside the scope of this PR. I'll take a look if it works, and will make separate PR.

**Comment by okla** [comment]
> I'll take a look if it works, and will make separate PR.

Great, thanks!

**Review by akien-mga — APPROVED** [review]
Looks good!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
