### PR TITLE
Fix one-way collision for moving objects

### LINKED ISSUE #7920: Bad collision against StaticBody2D with LineShape2D
**Ubuntu 16.10 - Godot 2.1.2 stable**

**Issue description:**
A StaticBody2D with a LineShape2D get incorrect collision against other bodies (or bodies against the static line).

It was expected to get collisions checked against full shapes, not just the "lower" part.

**Steps to reproduce:**

 - Create a StaticBody2D with a horizontal LineShape2D, like a floor.
 - Create a RigidBody2D with a CircleShape2D over the line, rotate it a bit. 
 - Look how the RigidBody2D hangs below the line.

Happens with other shapes against a line.

lineshapebug

**Link to minimal example project:**
[StaticLineBug.zip](https://github.com/godotengine/godot/files/812469/StaticLineBug.zip)

### LINKED ISSUE #9332: Bad separation of KinematicBody2D move against LineShape2D
**Godot version: 2.1.3**

**Issue description:**
Moving a KinematicBody2D (as in `move`) against a solid body with a LineShape2D, seems to not separate the body correctly leading to continuous collisions.
badkb-line

**Steps to reproduce:**
Move a KinematicBody2D against a line and try to move it again in the opposite direction.
Forcing a separation (with `set_pos`) lead to the correct behaviour.

**Link to minimal example project:**
[kb2dbadlineseparation.zip](https://github.com/godotengine/godot/files/1097690/kb2dbadlineseparation.zip)

Probably related to this #7920 ?

### LINKED ISSUE #25732: CollisionPolygon2D fall through with One Way Collision enabled
**Godot version:** Godot 3.1 Beta 3

**OS/device including version:** Windows 10

**Issue description:**

polygoncollision

**Steps to reproduce:**
Seems to happen only when the body with polygon is moving upwards

**Minimal reproduction project:**

[OneWayPolygonCollision.zip](https://github.com/godotengine/godot/files/2847633/OneWayPolygonCollision.zip)

### LINKED ISSUE #27593: RigidBody2D not colliding properly with CollisionShape2D (set to one_way_collision: on)
**Godot version:**

Godot Engine 3.1.stable.official

**OS/device including version:**

macOs Mojave 10.14.3
Intel Iris Pro 1536 MB

**Issue description:**

I'm using GLES2.

Scene tree:

```
Node2D
├── TileMap
├── KinematicBody2D
├── RigidBodyBody2D
└── Node2D
    ├── StaticBody2D
    ├── StaticBody2D
    ├── etc
```

The `TileMap` has a `tileset.tres` **Tile Set** with a **Single Tile** with `selected_collision_one_way` set to `on`. If I turned if `off` it seems to work.

I've also tried using a bunch of `StaticBody2D` with `CollisionShape2D` and I get the same behaviour. When `one_way_collision` is `on` the `RigidBodyBody2D`  doesn't collide properly. But when it's `off` it seems to work fine.

The `RigidBodyBody2D` is set to `Mode: Rigid`. If I change it to `Mode: Character` seems to work fine with either `one_way_collision` on and off.

rigidbody2d-collisions

**Steps to reproduce:**

Download the zip and try to play with the `TileMap` and the `StaticBody2D` changing `one_way_collision` to `on/off`. Also try playing with the `RigidBodyBody2D` modes.

**Minimal reproduction project:**

[test-rigidbody2d-collisions-one-way.zip](https://github.com/godotengine/godot/files/3033408/test-rigidbody2d-collisions-one-way.zip)

**UPDATE**

Version with the body's center of mass fixed.

[test-rigidbody2d-collisions-one-way-fixed-body-center-mass.zip](https://github.com/godotengine/godot/files/3058057/test-rigidbody2d-collisions-one-way-fixed-body-center-mass.zip)

### LINKED ISSUE #27652: RigidBody2D passes through walls/objects when pushed by a KinematicBody2D
**Godot version:**
3.1

**Issue description:**
Rigid Bodies pass through walls when pushed by Kinematic Bodies. This doesn't happen in 3.0.6.

In 3.0.6: https://i.imgur.com/k7vJdoM.mp4

In 3.1: https://i.imgur.com/BhkKt0G.mp4

It doesn't just happen in the platformer demo, I noticed this problem in other projects as well.

### LINKED ISSUE #27689: KinematicBody2D and RayCastShape2D doesn't work on One Way Collision
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
When I set character with KinematicBody2D and RayCastShapes2D as in this [post](https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody) from news section character is stuck on the bottom side of one way platform (snap vector is not set),

if I then press jump one more time he is in postition it is supposed to be (snap vector is not set).

If I set snap vector according to the news post then this hapens. On first jump player is stuck like this:

I can move player thru platform but if I go to the edge player starts to jumps up and down:

If I jumo one more time player is above platform but RayCastShape2D does not register collision only KinematicBody's collision shape registers collision:

It seems to me that when player is inside the platform it stops when RayCastShape2D detects botom of platform so that player is stuck inside the platform (bottom edge of platform). Desired behavior is for RayCastShape2D not to detect one way platform when player is passing thru it, wich is not true unfortunatly. Is this behaviour a bug? I can disable RayCastShapes2D when characeter is jumpig, but thats have its one issues. I am interested to know is this a wonted behavior or bug?

Maybe it is related to issue #26402

**Minimal reproduction project:**
[PlatformerTutorial.zip](https://github.com/godotengine/godot/files/3045551/PlatformerTutorial.zip)

### LINKED ISSUE #28794: CapsuleShape2D falls through vertically moving one way KinematicBody2D platforms
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
Windows 10 and Android (OnePlus 6T)

**Issue description:**
I created vertically moving platforms with `RigidBody2D` and a `RigidBody2D` player. 

With `CapsuleShape2D` Player falls through the Vertically (didn't notice this issue with Horizontally moving platforms) moving platforms when the platform moves up, but the player falls down (at least it visually seems so). With `RectangleShape2D` it seems to work better, I haven't encountered this problem with that shape yet. Here are some example GIFs:
*CapsuleShape2D:*
terrene1
*RectangleShape2D:*
terrene2

**Steps to reproduce:**
With player jump on a vertically moving platform at an interval (not constantly, let the player land on platform).

**Minimal reproduction project:**

The platforms are One Way Collision enabled and move using a tween (I basically followed a YT tutorial on moving platforms, and modified a code a little to meet my needs), here's relevant code and screens (everything else is default) the move_to is a `Position2D` node I use in Level chunks:
```
const IDLE_DURATION = 0.5

export (NodePath) var move_to = null
export (float) var speed = 300.0

onready var tween = $MoveTween

func _ready():
	_init_tween()

func _init_tween():
	if move_to != null:
		move_to = get_node(move_to).position
		var duration = move_to.length() / speed
		tween.interpolate_property(self, "position", position, position + move_to, duration, Tween.TRANS_LINEAR, Tween.EASE_OUT_IN, IDLE_DURATION)
		tween.interpolate_property(self, "position", position + move_to, position, duration, Tween.TRANS_LINEAR, Tween.EASE_OUT_IN, duration + IDLE_DURATION * 2)
		tween.start()
```
platform_inspector
platform_node_tree

Player is a KinematicBody2D with CapsuleShape2D with a standard movement code (except it's controlled with virtual joystick, which shouldn't really be an issue.. the `analog_position.x` value is `float from -1.0 to 1.0` and `is_analog_pressed` is a `boolean`), here's the relevant code and node-tree (everything else is default):
```
func _physics_process(delta):
	velocity.x = speed * analog_position.x
	var snap = Vector2.DOWN * 32
	
	if is_on_floor() && is_analog_pressed:
		snap = Vector2.ZERO
		velocity.y = jump_str
	
	velocity.y += gravity * delta
	velocity = move_and_slide_with_snap(velocity, snap, Vector2.UP)
	
	if position.x < 0:
		position.x = 720
	elif position.x > 720:
		position.x = 0
```
player_inspector
player_node_tree
**ZIP archive of the minimal project:**
[issue_28794.zip](https://github.com/godotengine/godot/files/3166434/issue_28794.zip)

### LINKED ISSUE #28895: One way platforms don't have consistent collision on edge
**Godot version:**
3.1

**OS/device:**
Windows 8, Toshiba Satellite

**Issue description:**
This is a rehash of closed issue #14724.

One-way `StaticBody2Ds` with rectangular `CollisionShape2Ds` do not consistently detect collision with a `KinematicBody2D` player when the player is on the edge of the platform.

Here is a video demonstrating the issue:
Untitled1

Even at low velocity, sometimes the player falls through the platform.

The player's movement is done by `move_and_slide()`, but the issue is also present when using `move_and_slide_with_snap()`.

**Steps to reproduce:**
1. Create a basic platformer with a rectangular player and a rectangular one-way platform.
2. Position the player atop the one-way platform on an edge.
3. Jump repeatedly until the player falls through.
4. Adjust nearness to edge if you can't reproduce immediately.

**Minimal reproduction project:**
[test_project.zip](https://github.com/godotengine/godot/files/3180551/test_project.zip)

### LINKED ISSUE #32138: Incorrect bounce angle of RididBody2d
**Godot version:**
v3.1.1.stable.official
**OS/device including version:**
Mac OS X and Linux Ubuntu
**Issue description:**
RigidBody2d collides with flat StaticBody2d and bounces with random angle. Often, with the same it came from. Happens on relatively high speed of RigidBody2d
**Steps to reproduce:**
1. Run the project
2. Bump the RigidBody2d with KinematicBody2d so it's speed increases
3. Observe the bug.

Here are the description with video and screenshots attached:
https://www.reddit.com/r/godot/comments/d4455z/bug_i_godot_physics_system/
**Minimal reproduction project:**
https://github.com/GaidamakUA/GodotExperiments/tree/master/arcanoid

### LINKED ISSUE #34215: 2D Physics Collision is 'Squishy'
**Godot version:**
3.1.2.stable.official

**OS/device including version:**
Windows 10

**Issue description:**
When two a `RigidBody2D` collides with a `StaticBody2D`, they 'squish' into each other and then the `RigidBody2D` slowly returns to the edge of the collision over a few frames. This makes the collision not feel quite so 'rigid' but instead like the `StaticBody2D` is squishy and allows other bodies to enter it temporarily. I have not checked to see if this behavior presents in 3D Nodes as well.

collision

**Steps to reproduce:**
Create a 2D scene with a `RigidBody2D` and a `StaticBody2D`. Have the `RigidBody2D` collide into the other body with some velocity. You'll observe the `RigidBody2D` enter the `StaticBody2D`.

**Minimal reproduction project:**
Zipped Project, open at run the scene.
[Bouncy.zip](https://github.com/godotengine/godot/files/3937910/Bouncy.zip)

### LINKED ISSUE #40006: Two or more KinematicBody2D on top of another KinematicBody2D makes the below one to move
**Godot version:**

Godot 3.2.2.stable

**OS/device including version:**

Windows 8.1

**Issue description:**

Two or more KinematicBody2D on top of another KinematicBody2D causes the one below to move and knock down the others.

What I found is that the size of the KinematicBody2D influences this.

movingKinematicBody2Dx

**Maybe related:**

https://github.com/godotengine/godot/issues/27652
--> I tried to put infinite inertia = false in the move_and_slide_with_snap, although this argument is only for the RigidBody2D.

https://github.com/godotengine/godot/pull/36280

**Steps to reproduce:**
Place a KinematicBody2D on the floor with move_and_slide (or move_and_slide_with_snap) idle or moving, and make two others KinematicBody2D jump on top of the first one and keep moving at least one of them.

**Minimal reproduction project:**

[KinematicMoving.zip](https://github.com/godotengine/godot/files/5419081/KinematicMoving.zip)

### PR DESCRIPTION
**Pull request by bemyak**
There are several bugs with one-way collisions:
Fixes https://github.com/godotengine/godot/issues/25732
Fixes https://github.com/godotengine/godot/issues/27593
Fixes https://github.com/godotengine/godot/issues/28794
Fixes https://github.com/godotengine/godot/issues/35776
Fixes https://github.com/godotengine/godot/issues/34242
Fixes https://github.com/godotengine/godot/issues/34215
Fixes https://github.com/godotengine/godot/issues/32138
Fixes https://github.com/godotengine/godot/issues/27689
Fixes https://github.com/godotengine/godot/issues/27652
Fixes https://github.com/godotengine/godot/issues/7920
Fixes https://github.com/godotengine/godot/issues/9332
*Bugsquad edit:* Fixes #40006
(probably few more, too lazy to find all of them)

Removing [this check](https://github.com/godotengine/godot/pull/36280/files#diff-6c47c53691e42eac4273e709791caa37L301) seems to fix them ~~or at least occur less frequently~~. I can't come up with a reason why that check was there before.

~~There are still problems when a body is being pushed through one-way collision, I'm trying to figure out how to fix it.~~

UPDATE: Some (lots of, actually) debugging  lead me to several issues in `servers/physics_2d/space_2d_sw.cpp`:
1. We're setting `invalid_by_dir` at the beginning of do...while loop, no reason to set it again and again
2. When we are calculating `cbk.valid_depth` we need take the motion of current body into account as well as platform's motion
3. When applying `recover_motion` we used to multiply it by magic `0.4`. Thus the entire do...while loop could end **only** when run out of `recover_attempts`.

UPDATE2: Looks like I fixed all one-way collision bugs except mine :smile: 
So, the reason to "weaken" [this condition](https://github.com/godotengine/godot/pull/36280/files#diff-2690fb5a19c73f3f0f4a434e992a8d8dR177) in `servers/physics_2d/physics_2d_server_sw.cpp` is how TileMaps work. If your body is moving along TileMap line, there will be a moment when it'll step on a new tile. In that case it's movement will not match the condition and it will fall through that new tile.

UPDATE3: The last commit also fixes https://github.com/godotengine/godot/issues/28895
UPDATE4: I uploaded 3.2 builds with this patch included here so it'll be easier to test it: https://pepya.tk/nextcloud/index.php/s/3Bqbfe7EMsrE9px

Before merging this, I highly recommend merging https://github.com/godotengine/godot/pull/38471 first, it fixes most of the bugs in a proper and clean way.

### CODE REVIEW

**Comment by fabriceci** [comment]
@bemyak for #35550, the expected behaviour is: the body should not move (and follow the platform). Is one of the setups works with this patch?

**Comment by bemyak** [comment]
It looks like this now:
Peek 2020-03-09 16-31
(sorry for low fps, my setup is not quiet good for screen recording :) )

**Comment by fabriceci** [comment]
Unfortunately that does not fix the issue: the green block should follow the platform (basic moving platform), I expected only the first or the last row to work properly (setup 1 & 4). The first not working (the block not follow the platform), the last, I suppose like in the current version, follow but you would not be able to jump when the platform move up, and the horizontal speed when moving will be cumulated.

Anyway thanks for your works!

**Comment by bemyak** [comment]
@fabriceci , I'm not an expert, but I don't think it is supported configuration.
In 1st and 4th setup, the platform's KinematicBody2D complains (shows :warning: sign next to it) about not having shape attached, such as `CollisionShape2D` or `CollisionPligon2D`.

Setup 2 and 3 looks good, since collision area is part of the TIleSet.

Usually, Kinematic Bodies are used to gradually control how body moves, despite physics. If you want to implement proper "jump on moving platform", you'll need to get platform's velocity and apply it when calculating velocity for Kinematic Body.

If you want to have proper physics, maybe you consider switching to RigidBody2D instead of KinematicBody2d. Here is a [great video](https://www.youtube.com/watch?v=pnBioV2HkS8) that explains the difference and how to use them both.

As for the vertical movement, it works as expected, since it is a part of "bodies should not stuck in each other" logic. Which was a bit broken, and this PR aims to fix it :)
 So, at least this point from your original issue seems to be fixed:
> * vertical movement : the body "enter" in the platform

**Comment by fabriceci** [comment]
> you'll need to get platform's velocity and apply it when calculating velocity for Kinematic Body.

That's not the behavior with standard shapes, but anyway it's out of purpose. (but thanks :) )

> As for the vertical movement, it works as expected, since it is a part of "bodies should not stuck in each other" logic. Which was a bit broken, and this PR aims to fix it :)

Great news and maybe even better, maybe you are correcting another of my issues  : #34242

**Comment by bemyak** [comment]
Yes, it fixes that one also. Added it to the description and removed https://github.com/godotengine/godot/issues/35550 from it.

**Comment by AndreaCatania** [comment]
Sorry, but I'm not the best person to check this. @reduz may know more about it.

**Comment by bemyak** [comment]
@aaronfranke , I just rebased it, you can remove the tag now :)

**Comment by bemyak** [comment]
@aaronfranke @akien-mga , Since 4.0 is in unstable state, maybe we can merge this PR and see if anything get broken? It is pretty small, so there should be no problem rolling it back. I can't see how else we can have a proper testing for it.

**Comment by jtaart** [comment]
It seems to fix all the ones I've tested so far.

before(v3.2) and after gifs

### **[gifs]**
#25732
[#25732_before](https://i.imgur.com/mxyBma1.gifv)
[#25732_after](https://i.imgur.com/6RjTnt6.gifv)

#35776
[#35776_before](https://i.imgur.com/7W6J8VL.gifv)
[#35776_after](https://i.imgur.com/7VAyfXO.gifv)

#34242
[#34242_before](https://i.imgur.com/OA7CnQ3.gifv)
[#34242_after](https://i.imgur.com/VWc137S.gifv)

#27593
[#27593_before](https://i.imgur.com/PrsgHZu.gifv)
[#27593_after](https://i.imgur.com/c6eJWpz.gifv)

#28794
[#28794_before](https://i.imgur.com/jfgiTNO.gifv)
[#28794_after](https://i.imgur.com/ke7Agh9.gifv)

**Comment by ZingBlue** [comment]
You are my hero. My project will no longer have broken platforms and random drops in velocity.

**Comment by bemyak** [comment]
@jtaart , thanks a lot for testing!

Regarding #7920, the left RigidBody doesn't go through the line:

Not sure what's wrong with the round one, I'll try to figure that out.

#2092: It worked on my machine until I tried to record the video. The FPS dropped and the bug popped up :sweat_smile: 

#32138: Looks fine?

**Comment by jtaart** [comment]
@bemyak 
#7920
3.2 already did this. So that part was probably fixed earlier.
[#7920_3.2](https://i.imgur.com/EyJJdTO.gifv)
[#7920_pull_request](https://i.imgur.com/G2ZYSqN.gifv)

#32138
You need to use: https://github.com/GaidamakUA/GodotExperiments/tree/master/arcanoid_tileset_collision
Also turn on Cast Ray Continuous Cd mode.
[#32138_3.2](https://i.imgur.com/ImTVxfH.gifv)
[#32138_pull_request](https://i.imgur.com/pjWuWfV.gifv)

I think I found whats wrong with #32138, but I'm to scared to try and fix it.
> 
> 
> The contact seems to be flipped. Don't exactly know whats going on with the function, but it seems a little off.
> 
> https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/servers/physics_2d/body_pair_2d_sw.cpp#L214-L217
> 
> [flipped gif](https://imgur.com/a/UsgoR5z)
> [unflipped gif](https://imgur.com/a/fuN2RIX)
> [temp fix gif](https://imgur.com/a/hEq0tXg)

**Comment by Rhathe** [comment]
I think this actually introduces a bug at least in 3.2. The bottom sprite is a Kinematic2DBody and the static body it passes through has one way collision on its top.

This is the original:
original

This is the fix:
fix

[test_move_one_way.zip](https://github.com/godotengine/godot/files/4569491/test_move_one_way.zip)

**Comment by kutetapolu** [comment]
Will this be accepted for 4.0? Pretty please, @reduz @akien-mga

**Comment by ZingBlue** [comment]
This would fix so many issues with my game. Some of which make it hard to justify shipping the game (it's physics based, so it really needs these bugs fixed).

**Comment by ZingBlue** [comment]
Is there anything I can do to help increase the likelyhood this will be merged? I'm a Python programmer but I could probably catch on to C++ quickly.

**Comment by AttackButton** [comment]
> UPDATE4: I uploaded 3.2 builds with this patch included here so it'll be easier to test it: https://pepya.tk/nextcloud/index.php/s/3Bqbfe7EMsrE9px

Wow! It solved one of my issues https://github.com/godotengine/godot/issues/40006. Thank you man. I will wait for the merge to test more.

I tested the other issue, but it didn't fix it. I even tested the minimal project of this issue https://github.com/godotengine/godot/issues/34345 of securas that is identical to mine and it also didn't work.

**Comment by ZingBlue** [comment]
I tested the build you included with my game. The two issues I originally had #27593 and #34215 were 100% fixed. My game played 10x better than before. I encountered no new issues. Thank you for fixing these issues.

**Comment by AttackButton** [comment]
> 
> 
> > UPDATE4: I uploaded 3.2 builds with this patch included here so it'll be easier to test it: https://pepya.tk/nextcloud/index.php/s/3Bqbfe7EMsrE9px
> 
> Wow! It solved one of my issues #40006. Thank you man. I will wait for the merge to test it more.
> 
> I tested the other issue, but it didn't fix it. I even tested the minimal project of this issue #34345 of securas that is identical to mine and it also didn't work.

Ok. this fixed it very well, makes the CollisionShape2D act like a solid instead of a gelatin xD. However, I was checking that the KinematicBody2D became a little easier to be pushed when it shouldn't be, something that didn't happen before. Maybe it's a new bug related to https://github.com/godotengine/godot/issues/34345?

**Comment by ShraddhaDevaiya** [comment]
hello @akien-mga and @reduz , can you please review this PR? so that they can make necessary changes if needed.

**Comment by bemyak** [comment]
I noticed the conflict and tried to resolved it. It turned out that currently master branch (without my commits) looks like this:
Peek 2020-07-23 22-21
(this is a test project from [here](https://github.com/godotengine/godot/issues/25732#issuecomment-466669002))

I guess I'll close this PR and open a new one for 3.2 branch only, I don't think I'll be able to fix the current state.

**Comment by bemyak** [comment]
Okay, I created https://github.com/godotengine/godot/pull/40645 to make it easier to maintain both 3.2 and 4.0 versions.

I also updated builds available in the first post to the latest 3.2. Enjoy =)

**Comment by epoblaguev** [comment]
No solution to contribute, but maybe one more datapoint for #32138.

Example: https://imgur.com/a/otCrzpx

It looks like the issue occurs when the ball (RigidBody2d) collides with tiles, but not with static bodies.

Continuous collision settings don't seem to have an effect on the issue.

**Comment by jtaart** [comment]
> 
> 
> No solution to contribute, but maybe one more datapoint for #32138.
> 
> Example: https://imgur.com/a/otCrzpx
> 
> It looks like the issue occurs when the ball (RigidBody2d) collides with tiles, but not with static bodies.
> 
> Continuous collision settings don't seem to have an effect on the issue.

Are you sure? Turning continuous cd fixes it for me.

[gif](https://imgur.com/a/hEq0tXg)

**Comment by bemyak** [comment]
Closing this in favor of https://github.com/godotengine/godot/pull/38471

**Comment by madmiraal** [comment]
#38471 is made against the 3.2 branch not the master branch.

**Comment by bemyak** [comment]
@madmiraal , this doesn't actually works on the `master` branch, see my comment above: https://github.com/godotengine/godot/pull/36280#issuecomment-663190860
And since the issue affects 3.2, I think it should first be merged into 3.2 and then cherry-picked into master.

**Pull request closed without merging**
