### PR TITLE
Fix window decoration size on Windows

### PR DESCRIPTION
**Pull request by floppyhammer**
Before
Screenshot 2021-08-23 102502

After
Screenshot 2021-08-23 102945

### CODE REVIEW

**Review by mhilbrunner — APPROVED** [review]
Looks good, built and tested locally, seems to work fine.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Note for others: on Windows, before this patch, if you un-maximize a maximized editor Windows, the calculation for the un-maximized size is incorrect and a bit on the right of the editor is cut off. This fixes that.

**Comment by mhilbrunner** [comment]
Thank you!

**Comment by akien-mga** [comment]
If this is relevant for `3.x`, this would need a dedicated PR as it's not trivially cherry-pickable.

**Comment by floppyhammer** [comment]
@akien-mga Decoration size is correctly calculated in `3.x`. So, not relevant.

**Pull request merged**
