### PR TITLE
Resolve relative icon paths for GDExtensions

### PR DESCRIPTION
**Pull request by YuriSizov**
See https://github.com/godotengine/godot/issues/82810. This is the same thing we do for libraries, so it should just work, I think.

cc @mihe for testing :)

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Tested successfully with https://github.com/akien-mga/threen.

**Review by dsnopek — APPROVED** [review]
I haven't tested, but the code looks good to me! (And this is definitely a feature I've wanted for my own GDExtensions :-))

**Review by mihe — APPROVED** [review]
I just gave this a try and it seems to work, as best I can tell. Thank you!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
