### PR TITLE
[Core,Drivers,Main] Improve checks using De Morgan's laws

### PR DESCRIPTION
**Pull request by AThousandShips**
Reduces cognitive load and improves readability, and avoids potential errors when expanding or rewording these. Doing the inverse of the expression, especially for longer expressions, can be difficult and the inverse might not be obvious if someone doesn't know the laws

Done in parts for ease of review and will open PRs for other parts of the codebase if this gets approved 

The laws in question are:
* `!(a && b) <=> (!a || !b)`
* `!(a || b) <=> (!a && !b)`

Also applied comparison inversions:
* `!(a < b) <=> (a >= b)` and `!(a <= b) <=> (a > b)`
* `!(a > b) <=> (a <= b)` and `!(a >= b) <=> (a < b)`

### CODE REVIEW

**Comment by adamscott** [comment]
> Reduces cognitive load and improves readability

Funnily enough, for me, it's the complete opposite.

**Comment by AThousandShips** [comment]
Are you sure you'd think the same without having the replacement clear? What makes `!from_point->enabled || !to_point->enabled` unclear for you for example? Or `p_material->shader_data->depth_draw != GLES3::SceneShaderData::DEPTH_DRAW_DISABLED && p_material->shader_data->depth_test != GLES3::SceneShaderData::DEPTH_TEST_DISABLED`?

**Comment by RandomShaper** [comment]
I've checked some of the changes to code I wrote myself and they are harder to parse with this PR. For instance, if I write `DEV_ASSERT(!(X))`, the intent is to say _I don't want X to happen_. If it's rewritten so the outermost expression is positive, the check seems less natural.

As a maintainer, I obtain a lot of info about the intent of the original authors of something from the expressivity or the code. And so I purposely write code in a way that I convey intent. (That's why I also tend to dislike PRs that workaround linting issues in ways that disregard the human and only please the compiler. They wash away those nuances that help understand what's going on in the code and why.)

**Comment by AThousandShips** [comment]
Those are good points, will leave open for some more opinions

**Pull request closed without merging**
