### PR TITLE
New shortcuts for the editor menu items

### PR DESCRIPTION
**Pull request by ZahFox**
I accidentally closed my last PR so this is the same as #26109 (related to issue #25634).

### CODE REVIEW

**Comment by reduz** [comment]
I'm not sure, you can add them yourself if you need.. default shortcuts are onlt meant for the most common ones.

**Comment by smedelyan** [comment]
@reduz 
You mean you don't think that's a necessary feature?

**Comment by akien-mga** [comment]
I think it's fine to add the possibility to set shortcuts for all entries.

@reduz To be clear, this only makes those shortcuts, but without any assigned hotkey. So there's no practical change apart from the fact that they will now appear unassigned in the Editor Shortcuts dialog.

**Comment by akien-mga** [comment]
Discussed with @reduz, he indeed thought this was adding default hotkeys for those options. It's fine as is.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
