### PR TITLE
XOR operator '^' for bools

### LINKED ISSUE #18816: Missing Bool XOR from GDscript
**Godot version: 3.0.2**

**Issue description:**
GDscript is missing bool xor. 

**Steps to reproduce:**
If you try:

var one = true
var two = false
var three = one^two

You get an error

### PR DESCRIPTION
**Pull request by DavidSichma**
closes #18816

The bitwise xor operator (^) has been extended to also work as an logical operation.

### CODE REVIEW

**Comment by aaronfranke** [comment]
How is this different from `!`?

**Comment by akien-mga** [comment]
The code could be simplified with `p_a._data._bool != p_b._data._bool` since that's the same as XOR for booleans.

I don't mind adding this, but I also don't see much use case since `!=` is the same. Opinions welcome.

**Comment by bojidar-bg** [comment]
Given that the other bitwise operators don't work on booleans, I would prefer to have a special boolean-xor operator than that (e.g. `x ^^ y`?).

**Comment by akien-mga** [comment]
> Given that the other bitwise operators don't work on booleans, I would prefer to have a special boolean-xor operator than that (e.g. x ^^ y?).

Well then I'd prefer none at all if it's the same as `!=`... We don't need to create another operator/another token for a feature that is not needed.

**Comment by DavidSichma** [comment]
I made this PR merely for training c++. The addition of this little feature seemed like a good task to me.

I know that this is not a necessary feature. `!=` is pretty much the same, not many folks use xor and with optional typing this won't even add type safety. The only people profiting would be those expecting `^` to work out of the box.

If you don't want to add `^` then don't. I got my bit of training so I am happy either way.

**Comment by avencherus** [comment]
Even though logically it is the same as !=, at least in my case sometimes conceptually they seem different or are recognized more immediately in certain context.  Not equal and one or the other.

Check if these are not equal.  `A != B`
Allow only one of the options.  `option_1 xor option_2`

Though redundant I wouldn't mind `xor` and `^^` for the sake of readability and preferences.  There were one or two occasions in months past where I would've reached for it, because in the context it would've been easier for me when reading it later down the road.

Something like:  `(A and B) xor not C` against `(A and B) != not C`

**Comment by vnen** [comment]
If this is really needed we could add `^^` and `xor` operators for booleans. But I'm against using `^` for booleans, to be consistent with `&` and `|` being bitwise operators that only works with integers.

**Comment by DavidSichma** [comment]
Most languages don't have an logical xor operation and just use the bitwise xor. The ones that actually have an logical xor usually just overload `^`. Java and C# do it this way. I don't think adding a new `^^` operator just for GDScript would be a good idea.

And I wouldn't go through the hassle of adding a new 'xor' operator, token and all unless there were a decent amount of people requesting the feature.
I think I will just close this PR if it does not pick up some interest in the next days.

**Pull request closed without merging**
