### PR TITLE
Fix crash in `NavigationAgent3D`

### LINKED ISSUE #78910: Crash in scene inheriting from `NavigationAgent3D`
### Godot version

4.1rc2

### System information

Linux Manjaro

### Issue description

Editor crashes whenever a scene inheriting from `NavigationAgent3D` is being opened:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.rc.custom_build (46424488edc341b65467ee7fd3ac423e4d49ad34)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x38f50) [0x7ff969664f50] (??:0)
[2] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x3541ea5) [0x5580ee733ea5] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/3d/node_3d.cpp:324)
[3] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x351e9c1) [0x5580ee7109c1] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/3d/navigation_agent_3d.cpp:224)
[4] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x5014e94) [0x5580f0206e94] (/home/scony/Gamedev/godot-engine/godot/godot-master/core/object/object.cpp:798)
[5] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x2f9ca7a) [0x5580ee18ea7a] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/main/node.cpp:228)
[6] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x2fa0177) [0x5580ee192177] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/main/node.cpp:2907)
[7] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x2fb485b) [0x5580ee1a685b] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/main/node.cpp:1381)
[8] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x1ef73fd) [0x5580ed0e93fd] (/home/scony/Gamedev/godot-engine/godot/godot-master/editor/editor_node.cpp:3445)
[9] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x1f20aae) [0x5580ed112aae] (/home/scony/Gamedev/godot-engine/godot/godot-master/editor/editor_node.cpp:3746)
[10] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x1f218c7) [0x5580ed1138c7] (/home/scony/Gamedev/godot-engine/godot/godot-master/editor/editor_node.cpp:3948)
[11] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x211ca04) [0x5580ed30ea04] (/home/scony/Gamedev/godot-engine/godot/godot-master/editor/filesystem_dock.cpp:1148)
[12] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x211cf32) [0x5580ed30ef32] (/home/scony/Gamedev/godot-engine/godot/godot-master/./core/templates/cowdata.h:412)
[13] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x5021575) [0x5580f0213575] (/home/scony/Gamedev/godot-engine/godot/godot-master/core/object/object.cpp:1069)
[14] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x338af73) [0x5580ee57cf73] (/home/scony/Gamedev/godot-engine/godot/godot-master/./core/variant/variant.h:301)
[15] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x33a7848) [0x5580ee599848] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/gui/tree.cpp:3866 (discriminator 4))
[16] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x3024c21) [0x5580ee216c21] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/main/viewport.cpp:1545)
[17] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x302be0b) [0x5580ee21de0b] (/home/scony/Gamedev/godot-engine/godot/godot-master/scene/main/viewport.cpp:1776)
[18] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x30427d8) [0x5580ee2347d8] (/home/scony/Gamedev/godot-engine/godot/godot-master/./core/object/ref_counted.h:209)
[19] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x308ac36) [0x5580ee27cc36] (/home/scony/Gamedev/godot-engine/godot/godot-master/./core/object/ref_counted.h:209)
[20] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0xc0c76b) [0x5580ebdfe76b] (/home/scony/Gamedev/godot-engine/godot/godot-master/platform/linuxbsd/x11/display_server_x11.cpp:3723)
[21] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x4cefba3) [0x5580efee1ba3] (/usr/include/c++/12.2.1/x86_64-pc-linux-gnu/bits/gthr-default.h:749)
[22] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0x4cf2758) [0x5580efee4758] (/home/scony/Gamedev/godot-engine/godot/godot-master/./core/object/ref_counted.h:209)
[23] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0xc0dd99) [0x5580ebdffd99] (/home/scony/Gamedev/godot-engine/godot/godot-master/./core/templates/local_vector.h:319)
[24] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0xbe5970) [0x5580ebdd7970] (/home/scony/Gamedev/godot-engine/godot/godot-master/platform/linuxbsd/os_linuxbsd.cpp:910)
[25] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0xbd6c09) [0x5580ebdc8c09] (/home/scony/Gamedev/godot-engine/godot/godot-master/platform/linuxbsd/godot_linuxbsd.cpp:76)
[26] /usr/lib/libc.so.6(+0x23790) [0x7ff96964f790] (??:0)
[27] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7ff96964f84a] (??:0)
[28] /home/scony/Gamedev/godot-engine/godot/godot-master/bin/godot.linuxbsd.editor.x86_64(+0xbe3b65) [0x5580ebdd5b65] (??:?)
-- END OF BACKTRACE --
================================================================
```

### Steps to reproduce

1. Clone https://github.com/lampe-games/godot-open-rts/tree/8b5f3c99d28b56d59591f3ea3d8657586b5ac48a
2. Open the project in editor
3. Open `source/match/units/traits/Movement.tscn`
4. Observe crash

### Minimal reproduction project

See above

### PR DESCRIPTION
**Pull request by Scony**
* *Bugsquad edit, fixes: #78910*

### CODE REVIEW

**Comment by AThousandShips** [comment]
I suspect it would be sufficient to update the if statement to check the parent, as if it is empty navigation will be disabled anyway so setting the position shouldn't matter

Also the condition to trigger this is when the parent of the agent isn't a `Node3D`, assuming this fix is correct

**Comment by Scony** [comment]
> I suspect it would be sufficient to update the if statement to check the parent, as if it is empty navigation will be disabled anyway so setting the position shouldn't matter
> 
> Also the condition to trigger this is when the parent of the agent isn't a `Node3D`, assuming this fix is correct
> 
> Edit: Confirmed, this is how it is in the 2D version, so instead:
> 
> ```c++
> if (agent_parent && avoidance_enabled) {
> 	NavigationServer3D::get_singleton()->agent_set_position(agent, agent_parent->get_global_transform().origin);
> }
> ```

done

**Review by AThousandShips — APPROVED** [review]
LGTM, matches the 2D version, but not my area of expertise so TIWAGOS[^1]

[^1]: Take It With A Grain Of Salt

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
