### PR TITLE
Fix return type on EditorNode3DGizmoPlugin::get_priority.

### PR DESCRIPTION
**Pull request by rcorre**
It would be nice to have an explanation of what get_priority does, but I
actually don't know.

### CODE REVIEW

**Comment by Calinou** [comment]
Won't this get overwritten when `--doctool` is run again? This should probably be fixed in the C++ code somehow.

**Comment by pouleyKetchoupp** [comment]
@rcorre If you want to make the proper fix @Calinou mentioned, you can add a fix here in your PR:
https://github.com/godotengine/godot/blob/9e34ba48556b71f1f672b5be47d12b0e3f679b86/editor/plugins/node_3d_editor_plugin.cpp#L6696

**Comment by akien-mga** [comment]
Can you squash commits into one?

**Comment by akien-mga** [comment]
Needs another rebase to solve a merge conflict and fix CI again (this time emscripten that failed overnight). Otherwise it should be good to merge :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
