### PR TITLE
Update search function in project settings

### LINKED ISSUE #37424: Project/Editor settings shows empty search results
**Godot version:**
3.2.1

**Issue description:**
bug

### PR DESCRIPTION
**Pull request by kotelifelif**
Fixes #37424 issue.

### CODE REVIEW

**Comment by akien-mga** [comment]
Please amend the commit log to use a more explicit message, which should describe in words what the issue is about: https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

**Comment by kotelifelif** [comment]
Is it possible commit message?

**Comment by akien-mga** [comment]
No, "change if condition" is also not a good message. See it in this context:
```
d773de6d244116c3ad26f0506a10038cc11019ff (HEAD -> 3.2-cherrypicks, origin/3.2) Document how renaming the project affects the user data path
be126bfd5555f5f4eab3738755aea3a2b47a7357 Document RigidBodies in character mode never sleeping automatically
b0a6439df9ba0b1b8e5fe168001d11f99aea873e doc/FileDialog: warn about access limitations in sandboxed apps
ef7675a05330b0643a5021e47f1591b9d0368b1b Document support for normal and specular maps in AnimatedSprite2D
138eba15619df0cab9cc9a5aa975c41e51ce3e49 Fix invalid CSV in SDL2 controller mappings DB
8a66ea7cb05fe666155f51e0cb5a9e817226c527 Revert "Updated LineEdit to address #41278"
9be924c454e699da74e4c366d453114ae98d3825 Sync controller mappings DB with SDL2 community repo
fad1feb3ad2ae65b25734160902e83dd1f69f416 Merge pull request #41649 from akien-mga/3.2-cherrypicks
cc3b69cf7b2a7eac1e7bb1966831e340f5a5ca16 (akien/3.2-cherrypicks, 3.2) Reference the online documentation in collision layer/mask properties
1b6d116dfbf5c93a5bf60b725075e7893bc97dfb Updated LineEdit to address #41278
63b2f69c7f5f3c885796e5ee4642acc6e40c4077 [funexpected] clear missed remaps on deinitialization, fixes godotengine/godot#34221
727bce727bd3fa082799d8836556e8513dc4b2a2 OptionButton.xml word order fix
57810f851cea9084e3e05372eadf284b035f5b25 Explain editor usage of current_animation
fdb5561e55d492b6c585ae7f39f948fd886706a0 Updated cursor positioning description for File open()
1f7f28a1eb1c93abed0332d8bcdef4c85d0d751f Document HTTPRequest not supporting request data with GET method
6eee52e49bf68d6be192047bfd6d90d799e5625b Improve the documentation related to overriding GUI theme items
92a1c168ea410471475fd038f77649df2b770edd Clarify get_data texture method
7493bc5530d109500412cad05a826902eae2710e Make `AnimatedTexture.MAX_FRAMES` public
dd057d36dc5656bb7eceb88e2de94c858ede780c Document the GDScript debugger not supporting Thread yet
a23c0aca87c89a753e4e1691bc6f52aa3cfbd650 Clarify that `KEY_BACK` is unrelated to the Back button on Android
afef89014bab216b6f660153745bec7708432cef Cross-reference GDScript built-in rounding methods to ease discovery
dea530d5ca93db88b85e357c21e1e36c4e2f4b37 Add information to get thread id
14e1c833505c71bd29103afe0ee18531d34b853e Improve touch screen button description
45e596e02ff763f35d227f2a3de1d44875372816 Document where the center of mass is for RigidBody nodes
d0b0dc633374d43633e10bf9ed87220f4dda24f1 Remove community health files from this repository
636fe1bab993e71d99c8f561e9ee715de28b6db4 Gives the theme editor a horizontal scrollbar
96ad9dc4c665379aec76b7095d76c17ca80efacb Document supported platforms for `Input.get_accelerometer()` and related
```

What would "change if condition" be about? Impossible to know from reading the commit message, there are tens of thousands of if conditions in the Godot source code.

Instead, you should describe what the change *does*, not what it *is*. So something like:
```
Fix filtering of search results in SectionedInspector

Fixes #41702.
```

**Review by KoBeWi — APPROVED** [review]
So we have 3 PRs for this issue and this is the only one that fully solves it. I checked other PRs and they still leave some wrong results. The reason why this happens is that apparently `is_subsequence_ofi()` uses fuzzy search. Replacing it with `findn()` will remove the fuzzy search, but IMO it's not important in project settings where everything is sectioned. I'd merge this one and close the others.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
