### PR TITLE
fixes android double tap regression

### LINKED ISSUE #35049: 3.2 BETA 6 - Android Crash - No implementation found for double_tap(int, int) exception.
**Godot version:**
3.2 BETA 6

**OS/device including version:**
Windows 10 Pro  64 bit 1909

**Issue description:**
Since updating to BETA 6, my Android app now crashes when the screen is touched too rapidly. Same app worked fine in BETA 5. This issue is present when using regular Android deployment, as well as a custom build. Logcat output points to:

`java.lang.UnsatisfiedLinkError: No implementation found for void org.godotengine.godot.GodotLib.double_tap(int, int) (tried Java_org_godotengine_godot_GodotLib_double_1tap and Java_org_godotengine_godot_GodotLib_double_1tap__II)`

**Steps to reproduce:**
Deploy an app to Android and tap the screen rapidly

If you need any more information, please let me know. Thanks.

### PR DESCRIPTION
**Pull request by AlexHolly**
closes https://github.com/godotengine/godot/issues/35049

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't understand why the bug happens in the first place though, everything was properly using `double_tap` in #33630 AFAICT.

**Comment by AlexHolly** [comment]
https://github.com/godotengine/godot/blob/dd2fd4e8535b4b04d28d0911e8a1aa9fd4544f22/platform/android/java_godot_lib_jni.h

I should have looked at the other functions to see how the function name is formed, the mapping probably splits at "_" and the last one is supposed to be the function name

This shows how to use the syntax properly
https://stackoverflow.com/questions/32470463/is-the-naming-convention-for-java-native-interface-method-and-module-name/32473938

**Comment by akien-mga** [comment]
Ah indeed. And the last chunk does use `camelCase` naming for this reason, so I was wrong to suggest changing `doubleTap` to `double_tap`.

**Review by akien-mga — APPROVED** [review]

**Comment by AlexHolly** [comment]
Most of the functions don't use `camelCase` (`doubletap` is now one of them) which could be cleaned up in the future.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
