### PR TITLE
Moved cube_to_dp and cubemap logic into CopyEffects

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR is part of our cleanup work, moves all the cubemap related effects into CopyEffects.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by and-rad** [comment]
Do we need to update our projects somehow? All my shadows are pitch black now.

**Comment by clayjohn** [comment]
> Do we need to update our projects somehow? All my shadows are pitch black now.

You shouldn't need to update anything. This must have broken something in the radiance cubemaps generation. Are you getting any errors printed in the inspector?

**Comment by and-rad** [comment]
```
 D:\Godot\servers/rendering/renderer_rd/shader_rd.h:140 - Condition "!version" is true. Returning: RID()
  servers\rendering\renderer_rd\effects\copy_effects.cpp:1033 - Condition "shader.is_null()" is true.
```
Get spammed a couple of times when a scene is opened. It's a Win 10 System with an nVidia RTX 2060.

**Comment by BastiaanOlij** [comment]
> ```
>  D:\Godot\servers/rendering/renderer_rd/shader_rd.h:140 - Condition "!version" is true. Returning: RID()
>   servers\rendering\renderer_rd\effects\copy_effects.cpp:1033 - Condition "shader.is_null()" is true.
> ```
> 
> These lines get spammed a couple of times when a scene is opened. It's a Win 10 System with an nVidia RTX 2060.

Looks like an issue in the order in which we initialise things, do we have an issue raised for this? Not a good idea to have this discussion on a merged PR :)

**Comment by BastiaanOlij** [comment]
@and-rad can you try this: https://github.com/godotengine/godot/pull/62420

**Pull request merged**
