### PR TITLE
new default theme

### PR DESCRIPTION
**Pull request by marynate**
- Make pr #704 merge friendly

### CODE REVIEW

**Comment by shackra** [comment]
is there any screenshot of this new default theme?

**Comment by mamarilmanson** [comment]
http://minus.com/i/byUHbrOUsx4QK

**Comment by adolson** [comment]
I think this should be merged for 1.1 instead of after, otherwise it's likely to wind up with a bunch more conflicts again. especially since many were expecting it for 1.0 originally. marynate fixed the scrollbar bug too, so that shouldn't be a concern anymore. just my opinion.

**Comment by shackra** [comment]
I think the same way, so if any bug exists with the new theme, we can spot it sooner than later

**Comment by mamarilmanson** [comment]
+1 to being merged on Godot 1.1... :))

**Comment by okamstudio** [comment]
allright

On Fri, Jan 16, 2015 at 11:24 AM, Manson Mamaril <notifications@github.com>
wrote:

> +1 to being merged on Godot 1.1... :))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/1204#issuecomment-70260018>.
>



-- 

*OkamStudio*

**Comment by mamarilmanson** [comment]
^ yey!

**Pull request merged**
