### PR TITLE
[WIP] Implement InputAxes (#14482)

### PR DESCRIPTION
**Pull request by sturnclaw**
**This PR is *almost ready* for merging.**

Implement #14482. Still some issues left, see latest comments.

Tasks:
- [x] Implement `InputMap::Axis` and related functions.
- [x] Implement `InputEventAxis`.
- [x] Implement the `Input::x` functions for dealing with axes.
- [x] Hook it up to engine code.
- [x] Implement binding axes in editor.
    - [ ] Change axis display to show full axes.

Questions, comments, reviews, code contributions, etc. welcome. I'm nowhere near as fluent in C++ as I am in Lua, so I may be committing some grave errors somewhere.

As a parting note, I would like to thank the core architects of the Godot Engine; this is _the_ easiest and nicest engine to hack on I have ever had the pleasure of working with.

### CODE REVIEW

**Comment by Web-eWorks** [comment]
@reduz (or whoever is most knowledgeable about this), is `InputEventAction` ever actually used or generated by the engine? I went looking, but aside from a cursory mention in one class, I can't see anywhere it's actually generated.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by Web-eWorks** [comment]
This PR does change several core user-facing APIs, so it will need to be postponed to 3.1. Right now, the API side of it is finished and I am waiting on 3.0 to stabilize to add the editor functionality. I would appreciate any feedback on the API side of things while I am waiting.

**Comment by Web-eWorks** [comment]
Some minor issues:

* Due to the way joystick input is implemented by the engine, a JoypadMotion event for returning to 0 is not generated, leaving axes in incorrect states (something like `0.000978`, so I suspect the filter in `input_default.cpp` needs some special casing.) If someone could fix that in a PR, that would be great.

* I am considering having a 'canonical' InputEventAxis be generated once per frame for all axes that have changed - this would provide a central point to catch, and would simplify dealing with multiple-device axis event spam. Feedback is appreciated.

* The way the multiplier for an event is edited (with a menu hidden behind a button) is slightly less than ideal. I've done what I can, so I'm turning the UX responsibility for that over to someone who knows that part of the engine better.

Other than that, it's almost done!

**Comment by Web-eWorks** [comment]
Comments and critique are appreciated; everything compiles and runs just fine, but I am

**Comment by karroffel** [comment]
I'd like to test this PR, but neither the branch on the fork works nor can I apply the patch. This needs a rebase, so: ping @Web-eWorks  :)

**Comment by reduz** [comment]
Closing, as superseded by #16902

**Pull request closed without merging**
