### PR TITLE
Trying to create API for reporting driver info for rasterizer

### PR DESCRIPTION
**Pull request by techtonik**
I am trying to make info about renderer output universally, but I don't know how to override class member in C++ (I am coming from Python). It still shows `Video driver: ???`. Any hints?

### CODE REVIEW

**Comment by neikeq** [comment]
Make a virtual getter and override it.

**Comment by techtonik** [comment]
@neikeq tried different combination, this still fails with:
```
.../visual/rasterizer.cpp:606: undefined reference to `Rasterizer::get_driver_name() const'
```

**Comment by neikeq** [comment]
If you want to call it from the base class, don't make it a pure virtual function (_= 0_). But I guess the right way would be to call it from the derived classes.

**Comment by techtonik** [comment]
The point is that if people forget to define name of derived class driver, it should bail out with an error.

**Comment by techtonik** [comment]
And it should be called in parent class consructor, because it is universal information for debug mode.

**Comment by techtonik** [comment]
When I leave out `= 0` it fails with
```
drivers\libdrivers1.windows.tools.32.a(rasterizer_gles2.windows.tools.32.o): In function `ZN10RasterizerD2Ev':
./servers/visual/rasterizer.h:1049: undefined reference to `vtable for Rasterizer'
servers\libservers.windows.tools.32.a(rasterizer.windows.tools.32.o): In function `ZN10RasterizerC2Ev':
servers/visual/rasterizer.cpp:603: undefined reference to `vtable for Rasterizer'
servers/visual/rasterizer.cpp:606: undefined reference to `Rasterizer::get_driver_name() const'
```
And when I add stub, the string returned from child class is that stub. See commit.

**Comment by techtonik** [comment]
@akien-mga can you take a look at this problem? I want to experiment with ANGLE backend after this is merged for debugging.

**Comment by techtonik** [comment]
http://stackoverflow.com/questions/36807653/call-child-method-from-parent-constructor

**Comment by techtonik** [comment]
Looks like there should be some obligatory parent driver_init() call for every driver.

**Pull request closed without merging**
