### PR TITLE
Lambda expressions in GDScript

### PR DESCRIPTION
**Pull request by dbsGen**

### CODE REVIEW

**Comment by Noshyaar** [comment]
pretty_print copyright headers are outdated (without contributors / year 2016 / outdated website link)?

**Comment by groud** [comment]
This is not a good solution. I think there are a lot of good ideas in this PR but you should create different PR for the several enhancements you are doing.
From what I can read, this PR:
- Adds a LEN operator to gdscript
- Adds inverse_lerp and range_lerp to gdscript
- Replaces OP_EXTENDS by OP_IS
- Implements Lambda expressions.

**Comment by dbsGen** [comment]
@Noshyaar I missed this, and it is fixed.
@groud This brach(PR) is only for the lambda expression, make you can write this:
      
      extends Node

      func _ready():
        var val = "1"
        var prin = func():
          print("s" + val);
        prin();
        hello(
        func():
          print("woqu")
        ,3)
      func hello(f, z):
        f()

**Comment by Hinsbart** [comment]
The lambda branch is waay old (based on 2.1, that's why there are all these unrelated changes @groud  mentioned).
Please rebase this on the master branch.

**Comment by groud** [comment]
> The lambda branch is waay old (based on 2.1, that's why there are all these unrelated changes @groud mentioned).

Oh ok, I didn't check the branch this PR was supposed to be merged.

**Comment by dbsGen** [comment]
@Hinsbart Already rebased.

**Comment by groud** [comment]
> @Hinsbart Already rebased.

You need to rebase it on master (not the lambda branch), and probably open a new PR asking for merging into master.

**Comment by Hinsbart** [comment]
> Edit: this second part is not needed anymore, Hinsbart changed the destination branch :)

Yes I changed the base branch to master, but it seems like it wasn't rebased to master correctly.
A look at [OP's branch](`https://github.com/dbsGen/godot/tree/lambda`) confirms this, it's 3 commits ahead of godotengine/lambda. (should be `godotengine/master`).

**Comment by groud** [comment]
> Yes I changed the base branch to master, but it seems like it wasn't rebased to master correctly.

Yes, the first part of my message "You need to rebase it on master" is still valid. ^^

**Comment by akien-mga** [comment]
To problem update your lambda branch, you need to do:
```
git checkout lambda
git reset --hard upstream/lambda   # assuming "upstream" is your godotengine/godot remote
git checkout -b lambda2    # better work in a new branch as we're rewriting history
git pull --rebase upstream/master    # then have fun fixing the many merge conflicts that will happen
git push origin lambda2
```

**Comment by LeonardMeagher2** [comment]
will this allow:
```
func something():
    pass

func hello(f):
    f()

func _ready():
    hello(something)
```
?

or will I have to do
```
var something = func():
    pass
```

**Comment by dbsGen** [comment]
@LeonardMeagher2 Yes, It is allowed.

**Comment by dbsGen** [comment]
@akien-mga I am very confused. Is this branch ok?(https://github.com/dbsGen/godot/tree/lambda2) And should I open a new PR?

**Comment by Hinsbart** [comment]
@dbsGen No, unfortunately it's still not ok. It seems you rebased master on top of the lambda branch, not the other way round.

**Comment by dbsGen** [comment]
@Hinsbart  How about this branch https://github.com/dbsGen/godot/tree/lambda3?

**Comment by dbsGen** [comment]
@Hinsbart I tried many, is this ok? (https://github.com/dbsGen/godot/tree/l2 )

**Comment by akien-mga** [comment]
For the record, there is no plan to add lambdas to GDScript for 3.0 as this stage of development. On the other hand, there are many improvements planned for GDScript in 3.1, and discussing and implementing lambda support might be part of them.

**Comment by girng** [comment]
what's the use case for this? why would a game developer need to utilize lambdas?

**Comment by vnen** [comment]
@girng I think you lost a bit of history because this is a Godot 3.0 remake of an old PR (see #2704). And there's a lot of places where lambdas could be useful and make the code cleaner.

**Comment by girng** [comment]
@vnen thx, i personally havn't used them but i can see the need now, with that code sample in 2704.

**Comment by aaronfranke** [comment]
@dbsGen You will need to learn how to use Git in order to submit code to Godot. Here's how I'd do it:

1. Download and install [GitKraken](https://www.gitkraken.com/), then sign in.

2. Clone your repository and check out your branch.

3. Add Godot as an upstream remote, use the link https://github.com/godotengine/godot and the name `upstream`, then fetch it.

4. Drag and drop your branch onto Godot's `master` branch to rebase it. You will have to resolve any conflicts.

5. Force push back to GitHub.

**Comment by akien-mga** [comment]
First of all, a huge thanks @dbsGen for your work on this feature, and the several iterations it went through as Godot moved on and the feature proposal didn't get merged.

Lambda expressions are a popular feature request for GDScript and definitely something we want to add, but we want do things right™ and our implementation ideas have matured a lot over the years, for this and related features.

The current plan is outlined in godotengine/godot-roadmap#23, and is lead mainly by @vnen who implemented optional typing recently and will go on to other GDScript improvements. Lambdas are currently planned for Godot 3.2.

As such I'll close this PR, since it won't be merged as is and the lambdas syntax will likely be reimplemented on top of the new features @vnen is working on. He will likely use your work as a reference, and you'll be very welcome to contribute to it when the time comes (or potentially do the implementation after discussing it with @vnen).

**Pull request closed without merging**
