### PR TITLE
Implement global and per instance shader uniforms.

### LINKED ISSUE #257: Add the possibility to pass unique parameters per instance to a shader
**Describe the project you are working on:**
A Spatial shader whose attributes (ALBEDO, ROUGHNESS...) would be influenced by the position of the instance in the 3D world.

**Describe the problem or limitation you are having in your project:**
It is impossible to pass a parameter related to the instance of a mesh.
If two instances of a mesh share the same shader, all instances will have as parameter value the last one passed to the shader.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
The possibility to pass (one or more) unique parameter for each instance would allow to use a single shader for several meshes while keeping the possibility to modify their aspect.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
godotVertexColor

The two cubes above are instances of the same resource.
They share the same shader, mesh and script.
The color of the vertices of each cube is given by its position in the 3D world.
Unfortunately, currently the shader uses as a parameter the color of the last mesh drawn: both cubes have the same color.

BlenderColor

The ability for the shader to retrieve one or more parameters unique to each instance would allow, as in Blender, to influence the rendering of instances of a mesh sharing the same attributes.

**Describe implementation detail for your proposal (in code), if possible:**

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

**Is there a reason why this should be core and not an add-on in the asset library?:**

### LINKED ISSUE #18848: Have a way to render the scene in another viewport with global shader overrides
Godot 3.x

I've been thinking about a feature that could help implement interesting rendering techniques:
Have the ability to create a viewport on which we can render the scene, but from a different viewpoint, different environment and different shaders for all the objects, *without* having to necessarily change (or even touch) all nodes of that scene, which makes it easier to setup.

The use cases for this are:
- Minimap with lighter materials (less overhead due to being a separate render with lighter shaders)
- Realtime top-down mapping, or depth map for use in other materials (ex: a grass painting system based on the height of the depth map)
- Debug drawing (like the unshaded, overdraw and wireframe modes we know, but could also be UV, normal, or other displays)

I thought https://github.com/godotengine/godot/pull/18795 would provide this feature, but this implementation is intrusive and a bit different from what I'm seeking for.

### LINKED ISSUE #30375: Set shader uniform per object without duplicating the material
Having a spatial shader with a custom uniform parameter, currently it is not possible to set it to a different value per object. To do so, you have to duplicate the material for each object using it.

For example, Godot sets the `WORLD_MATRIX` uniform to a different value for each object, even if multiple objects share the same material. Something similar could be done for custom uniforms.

A use case would be to render several different meshes with a transparent material, but with the `ALPHA` value set by the pixel shader to be defined per mesh. Setting the `ALBEDO` alpha channel in the material works, but affects all other meshes using the same material.

Duplicating the material for each object and then changing the custom uniform value has some drawbacks:
- After duplicating the material you can no longer change a material property and have an effect on all objects using it (you have to apply the same change on all the duplicates)
- Having many objects with their own material copy might affect performance (it might not, depends on how godot handles this internally).

### PR DESCRIPTION
**Pull request by reduz**
image
image

Adds two keywords to shader language for uniforms:
-'global'
-'instance'

This allows them to reference values outside the material.

*Bugsquad edit: closes https://github.com/godotengine/godot-proposals/issues/257, closes #18848, closes #30375*

### CODE REVIEW

**Review by Chaosus — COMMENTED** [review]
Some Travis error messages about fallthrough should be fixed (its easy), otherwise looks ok...

**Comment by Schroedi** [comment]
Per instance uniforms sound like instance parameters for MultiMeshInstances:  https://docs.godotengine.org/en/3.2/tutorials/3d/using_multi_mesh_instance.html

I guess this is not what they are meant for, or can they be used there as well?

**Comment by reduz** [comment]
Oh just as a side note, per instance uniforms are not working for 2D (CanvasItems) because I could not find a way to implement them. I am planning to eventually rewrite the 2D rendering code to make it more efficient before 4.0 is out, now that I am more proficient with Vulkan so I will properly implement those there.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
