### PR TITLE
Document how to use logarithm of base 10 with `log()`

### LINKED ISSUE #75299: Log function working wrong
### Godot version

4.1

### System information

Windows 10

### Issue description

image
I printed log(9) but it result seems like 2.192

### Steps to reproduce

var digitCount : int = int(log(9))
print(digitCount) 

### Minimal reproduction project

I don't have a .godot file for this

### PR DESCRIPTION
**Pull request by Calinou**
- This closes https://github.com/godotengine/godot/issues/75299.

### CODE REVIEW

**Review by kleonc — APPROVED** [review]
LGTM. Potentially a link to https://en.wikipedia.org/wiki/Natural_logarithm could also be added.

**Comment by YuriSizov** [comment]
Yeah, I agree. This link is probably even more useful than to the article about E.

**Comment by Calinou** [comment]
> Yeah, I agree. This link is probably even more useful than to the article about E.

Done :slightly_smiling_face:

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Pull request merged**
