### PR TITLE
fix(ios): Clipboard get/set missing implement

### PR DESCRIPTION
**Pull request by kyoz**
This should fix the get/set clipboard not working on iphone mentioned in https://github.com/godotengine/godot/issues/52228

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
There's extra space before the `;` in the function declaration. Everything else is OK, it's the same code used in `4.x`.

```diff
diff --git a/platform/iphone/os_iphone.h b/platform/iphone/os_iphone.h
index f0112a7..ad9a8ee 100644
--- a/platform/iphone/os_iphone.h
+++ b/platform/iphone/os_iphone.h
@@ -109,7 +109,7 @@ public:
 	virtual String get_name() const;
 	virtual String get_model_name() const;
 
-	virtual void set_clipboard(const String &p_text) ;
+	virtual void set_clipboard(const String &p_text);
 	virtual String get_clipboard() const;
 
 	Error shell_open(String p_uri);
```

**Comment by kyoz** [comment]
> There's extra space before the `;` in the function declaration. Everything else is OK, it's the same code used in `4.x`.
> 
> ```diff
> diff --git a/platform/iphone/os_iphone.h b/platform/iphone/os_iphone.h
> index f0112a7..ad9a8ee 100644
> --- a/platform/iphone/os_iphone.h
> +++ b/platform/iphone/os_iphone.h
> @@ -109,7 +109,7 @@ public:
>  	virtual String get_name() const;
>  	virtual String get_model_name() const;
>  
> -	virtual void set_clipboard(const String &p_text) ;
> +	virtual void set_clipboard(const String &p_text);
>  	virtual String get_clipboard() const;
>  
>  	Error shell_open(String p_uri);
> ```

Thank @bruvzg , i have updated

**Comment by mhilbrunner** [comment]
Looks good. Can you squash the commits into one, please? :) Then it can be merged.

**Comment by kyoz** [comment]
Hi @mhilbrunner , i'v squashed but maybe i'm doing something wrong :D, should i open a pr again or reopen it will auto get change from my branch @@

**Comment by mhilbrunner** [comment]
Somewhere along the line, you've ended up deleting the branches. :)
You'll need to either fix those or submit a new PR, referring to this one in the description. Feel free to ping me if you do.
We can't reopen a PR with a deleted branch.

If you need help with this, feel free to reach out to us on chat.godotengine.org

**Pull request closed without merging**
