### PR TITLE
Implemented start and end offset for AnimationTrack (like AudioTrack has)

### PR DESCRIPTION
**Pull request by TypeOverride2**
Implemented start and end offset for AnimationTrack (like AudioTrack has). Several bugfixes on Animation playback included.

[](https://www.youtube.com/watch?v=0t3_yYInLuY)

- setting a start and end offset like AudioTrack has is now possible on AnimationTracks
- live-preview of animations are now possible in AnimationPlayer via Editor
- the correct last animation frame is now showing when going in AnimationPlayer on a empty area with the cursor
- backward playing of animations is now possible in AnimationPlayer
- overlapping areas ( < 0 and > length) of animations are now playing correctly in AnimationPlayer
- AnimationPlayer is now stopping on the correct time when AnimationTrack length is reached (loop off)
- serveral other fixes are made on AnimationTrack playback logic

### CODE REVIEW

**Comment by Calinou** [comment]
@Lefl1 Out of curiosity, why did you react with :-1:?

**Comment by Lefl1** [comment]
I just noticed the image in the PR is a video 🤦 and for some reason read over the AnimationTrack and assumed he meant normal animations for which most of the stuff already exists/can easily be done by code.

Aside from that I've discussed with OP on the Discord how he should have squashed his commits (I'm unsure if that's possible in GitHub now).

Retracted the -1 due to my inability to comprehend stuff, sorry.

**Comment by TypeOverride2** [comment]
Sorry had to close it. Git stuff is so complicated to me. I saw that i cant work on other stuff because i didnt use a branch. So i have now to see how to changes in branches. And make on master something like a hard reset!?

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/41168.

**Pull request closed without merging**
