### PR TITLE
meshoptimizer: Sync with upstream commit 4a287848f

### PR DESCRIPTION
**Pull request by akien-mga**
https://github.com/zeux/meshoptimizer/commit/4a287848fd664ae1c3fc8e5e008560534ceeb526

Untested, so I'll merge after beta 10 to avoid introducing regressions.

### CODE REVIEW

**Comment by akien-mga** [comment]
Now it should build, but still untested. There's an API change in `simplify` and `simplifyWithAttributes` with the new `unsigned int options` added in https://github.com/zeux/meshoptimizer/commit/66040c7d7595490620d92f9a757e03354a1e206c.

**Comment by fire** [comment]
@Zylann I think the option to lock the topological border should be on? Not sure.

**Comment by fire** [comment]
Nudge. I think the lock should be 1 instead of 0and we should test the change with the community.

**Comment by lyuma** [comment]
Fixed conflicts and applied @fire's suggestion to use the `meshopt_SimplifyLockBorder` option.

**Comment by lyuma** [comment]
We tested and confirmed that the new SurfaceTool::SIMPLIFY_LOCK_BORDER option fixes #59024

Before:
image
After:
image

I tested a mario model with lots of meshes that historically showed LOD artifacts when high pixel ratio is used, and the model did not regress from the previous implementation.
Before:
image
After:
image
slightly more of the torso is gone but the model seems overall better preserved.

**Review by fire — APPROVED** [review]
We tested with the new locked borders option.

**Comment by akien-mga** [comment]
Thanks for testing and improving it!

As a next step for after 4.0 is released, we could look at moving to this upstream branch and provide feedback: https://github.com/zeux/meshoptimizer/pull/524

**Pull request merged**
