### PR TITLE
[3.x] Make GLTF module togglable when compiling release templates

### PR DESCRIPTION
**Pull request by you-win**
The GLTF module is excluded from release templates by default. This PR adds a build flag to enable/disable the GLTF when compiling Godot and release templates.

This change was needed for my project on 3.x [openseeface-gd](https://github.com/you-win/openseeface-gd), which loads in `gltf`/`glb` models at runtime.

Associated PRs:
- master
  - [godot](https://github.com/godotengine/godot/pull/51383)
  - [godot-docs](https://github.com/godotengine/godot-docs/pull/5161)
- 3.4
  - [godot](https://github.com/godotengine/godot/pull/51382)
  - [godot-docs](https://github.com/godotengine/godot-docs/pull/5160)

### CODE REVIEW

**Comment by pycbouh** [comment]
Making it possible to import resources at runtime is not as simple as enabling the module during the build.

See https://github.com/godotengine/godot-proposals/issues/2509 and https://github.com/godotengine/godot-proposals/issues/1632

**Comment by you-win** [comment]
Fortunately, importing `glb` files does not rely on any Importer. The code to import `glb` files is self-contained within the gltf module. I'm confident this works, at least for the 3.x branch, because this is how [openseeface-gd](https://github.com/you-win/openseeface-gd) works.

**Comment by pycbouh** [comment]
Well even in this PR you've inadvertently made a module that can be exported but relies on an editor include with `#include "editor/import/resource_importer_scene.h"`. Now, `resource_importer_scene.h` itself doesn't presently rely on other editor code from what I can see, but it's still in the editor namespace, so it can rely on editor-specific classes if we need it to and that would translate into them becoming a part of the exported code. Which is problematic.

**Comment by you-win** [comment]
If the ask is to wrap all editor-specific code in preprocessor checks, that's doable. I have made a change to `modules/gltf/editor_scene_importer_gltf.h` that wraps the aformentioned `#include "editor/import/resource_importer_scene.h"` in a `#ifdef TOOLS_ENABLED` check.

Again, I have tested the release template by compiling with the following options:
- `scons platform=windows target=release tools=no -j6`
  - runtime loading works
- `scons platform=windows target=release tools=no j6 module_gltf_enabled=no`
  - program crashes on start as expected

**Comment by you-win** [comment]
Updated to wrap all editor includes behind an `#ifdef TOOLS_ENABLED` check in the GLTF module.

Everything seems to work fine when recompiling and using the new release template.

**Comment by fire** [comment]
@you-win I'm consolidating this work into a proposal https://github.com/godotengine/godot-proposals/issues/3273

Not sure what to do on the 3.x branch. Probably backport?

**Comment by Calinou** [comment]
@you-win It looks like you rebased incorrectly, which means lots of unrelated commits are now included.

**Comment by you-win** [comment]
Closing as this is being worked on by fire, i guess. I'll just maintain my own template

**Pull request closed without merging**
