### PR TITLE
Minor code improvements

### PR DESCRIPTION
**Pull request by KoBeWi**
- remove redundant disconnections in tile code (objects are automatically disconnected on destruction)
- simplify `PROPERTY_USAGE_DEFAULT_INTL` definition

### CODE REVIEW

**Review by groud — APPROVED** [review]
I think the TileMap/TileSetEditor are fine if we are 100% sure signals are removed correctly if the target object is destroyed.

For the object.h part, I am not sure it's better. I think the current version is clearer on which bits are set. Though I get why you would prefer this to be defined as "this is default flags plus one additional bit".

**Comment by KoBeWi** [comment]
The constant is named *PROPERTY_USAGE_DEFAULT*_INTL, so it makes sense to be based on the other one.

**Comment by groud** [comment]
> The constant is named PROPERTY_USAGE_DEFAULT_INTL, so it makes sense to be based on the other one.

Sure, but it still makes it less readable when you need to debug things and know which bits are enabled. It is not so bad but well, I am not sure it is a clear improvement.

**Comment by akien-mga** [comment]
Seems fine to me, it does sound like the intended use is "default + intl" which this change conveys fine.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
