### PR TITLE
openxr: Sync with upstream 1.0.28

### PR DESCRIPTION
**Pull request by akien-mga**
I didn't test whether it works, I just updated the files with the upstream ~1.0.27~ 1.0.28 tarball.

### CODE REVIEW

**Review by BastiaanOlij — APPROVED** [review]
lgtm

**Comment by BastiaanOlij** [comment]
@akien-mga 1.0.28 should be released any day now, so we might want to wait until thats available and update this to 1.0.28

**Review by BastiaanOlij — APPROVED** [review]
Works fine with my Index :)

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
