### PR TITLE
Improve error message in Node::get_path()

### PR DESCRIPTION
**Pull request by mitchcurtis**
Same approach as in https://github.com/godotengine/godot/pull/31182.

### CODE REVIEW

**Comment by mitchcurtis** [comment]
Is there a const-friendly way of identifying the node (i.e. similar to to_string())?

**Comment by KoBeWi** [comment]
You can use `Node.name()`.

**Comment by mitchcurtis** [comment]
> You can use `Node.get_name()`.

Thanks!

**Comment by mitchcurtis** [comment]
> You can use `Node.get_name()`.

Hmm, it seems that default-named nodes have some weird names:

> @@2

**Comment by akien-mga** [comment]
> Hmm, it seems that default-named nodes have some weird names:

That's normal, but it's also their names in the remote scene tree so if you get an error on a default-named node, you can still find out which one it is.

**Comment by mitchcurtis** [comment]
> 
> 
> > Hmm, it seems that default-named nodes have some weird names:
> 
> That's normal, but it's also their names in the remote scene tree so if you get an error on a default-named node, you can still find out which one it is.

Oh... then I just need to find out how to access the remote scene tree through the editor UI. :D

**Comment by akien-mga** [comment]
> Oh... then I just need to find out how to access the remote scene tree through the editor UI. :D

Click "Remote" on the scene tree dock when the game is running.

**Comment by mitchcurtis** [comment]
By the way, I'm happy with the patch as-is. I will leave the name thing for another day.

**Comment by akien-mga** [comment]
Thanks!

**Review by wisewoman547 — COMMENTED** [review]
I'm confused

**Pull request merged**
