### PR TITLE
Inform the vulkan driver about the engine version and the application version.

### PR DESCRIPTION
**Pull request by lucbf**
The engine version is passed by hashing VERSION_NUMBER from _core/version.h_

I plan the applicationVersion to be passed by making the VCS api save the version string of a game at the project settings on export.

### CODE REVIEW

**Comment by Calinou** [comment]
For passing the project version setting, this may be a better option: https://github.com/godotengine/godot/pull/35555

**Comment by M4gma** [comment]
I will wait it to be merged. I guess then I'll integrate the VCS with the project settings in another PR

**Comment by Calinou** [comment]
@lucbf This PR looks useful in its current state nonetheless, since it still signals the engine version to Vulkan. Could you rebase it against the latest `master` branch? Thanks in advance :slightly_smiling_face:

**Comment by 1ace** [comment]
> My only concern is the version encoding – `String::hash()` is being used here, which likely doesn't translate to human-readable values unless you know the hash in advance. How do other Vulkan applications handle this? Do they use a number like `30104` to signal `3.1.4`?

How the version is encoded is up to the engine, but I believe there is an expectation that `version_A > version_B` should yield `true` if and only if version A comes indeed after version B, which isn't true when using a hash.

I think Godot should either use its [`VERSION_HEX`](https://github.com/godotengine/godot/blob/master/core/version.h#L55) define here, or `VK_MAKE_VERSION(VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)`; @Calinou do you have a preference between the two?

Since @lucbf hasn't been active in a couple of years, I'll make a superseding PR against current `master`, with only the relevant line updated :slightly_smiling_face:

**Comment by Calinou** [comment]
> @Calinou do you have a preference between the two?

Not really, feel free to use whichever approach is simpler for Vulkan applications to handle.

**Comment by 1ace** [comment]
I don't think it actually matters, but using the `VK_*` macro felt more right ^^

See https://github.com/godotengine/godot/pull/56202

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/56202. Thanks for the contribution nonetheless!

**Pull request closed without merging**
