### PR TITLE
Change cursor consistently when panning in the 2D Editor

### LINKED ISSUE #75871: Strange cursor icon behavior when panning in the 2D view
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I noticed there are two strange cursor interactions when panning in the 2D view via holding the spacebar and click+dragging. (I suspect they're directly related, which is why I only opened one issue.)

1. If you hold the spacebar in the 2D view, your mouse cursor does not change to the "panning" icon until you move your mouse. I expected the cursor icon would change as soon as the spacebar press was detected.
2. If you hold the spacebar, click and drag in the 2D view, and then release the mouse button, the cursor icon remains as the "panning" icon whenever it is hovering over the 2D view. It only returns to normal once you click somewhere in the 2D view. I expected the cursor to return to normal as soon as the spacebar was released.

These issues are fairly minor but they confused me as a new user trying to understand how panning works in the editor.

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by hakro**
Fixes https://github.com/godotengine/godot/issues/75871
Supersedes #75910
Includes @Sauermann 's suggestion https://github.com/godotengine/godot/pull/75910#discussion_r1163923838

Cheers

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
Funny, because it was @Sauermann who removed that line: https://github.com/godotengine/godot/pull/59081/files#diff-eb4ce61def40bf37d0fba218d92fa230c11f78e3a56f2849cdfe0045512acc3bL1231

**Comment by Sauermann** [comment]
@KoBeWi Right, looks like I made a mistake in that PR. Thanks for this bugfix!

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
