### PR TITLE
CI: Add workflows to check if Godot compiles without modules enabled

### PR DESCRIPTION
**Pull request by totlmstr**
In line with https://github.com/godotengine/godot/issues/41710#issuecomment-685864557 (note that that issue is for Godot 3.2, **not** for 4.0 master), this PR adds two new workflows for Github Actions which compiles Godot with the new `modules_enabled_by_default` option I previously introduced from #41091. These new workflows are otherwise copies of `linux-template` and `linux-editor` from `linux_builds.yml` but trimmed.

Also note that `linux-minimal-tools` currently has `module_freetype_enabled=yes` because that is issue #28650 (which I am currently looking to fix).

Finally, if this PR is merged, then it closes #41091, since this branch is a rebase of that PR to master with additional edits.

---

Addendum: This code compiles, but the minimal implementations _can and will crash_ unexpectedly when interacting or using projects with fonts.

### CODE REVIEW

**Comment by aaronfranke** [comment]
Why did you move the static checks into a file shared with builds? They are completely unrelated, these should not be in the same file. Also, the name is incorrect anyway - it says "PR Checks", but these checks also run on builds of non-PR commits. I think you should just revert the changes to `static_checks.yml`, and put the minimal Linux builds in `linux_builds.yml`.

> Finally, if this PR is merged, then it closes #41091, since this branch is a rebase of that PR to master with additional edits.

Ideally, #41091 should be merged first before this one is merged, then this can be rebased on top of #41091. It's a good practice to keep each major change in its own PR.

**Comment by Xrayez** [comment]
I'd go as far as disabling everything which can be disabled currently (`disable_3d=yes`, `disable_andvanced_gui=yes` etc), and yeah I think adding 1-2 jobs won't hurt much because disabling most modules should speed up compilation by 10-20 minutes in CI on average, in my experience. One should be aware of [GitHub concurrent jobs limitations](https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits), which is 20 jobs.

**Comment by Calinou** [comment]
@Xrayez SCons doesn't allow declaring a build variable named `3d_enabled`:

```
scons: Reading SConscript files ...

scons: *** Illegal construction variable `3d_enabled'
File "/home/hugo/Documents/Git/godotengine/godot/SConstruct", line 188, in <module>
The terminal process terminated with exit code: 2
```

**Comment by Xrayez** [comment]
Ah indeed, then we could probably establish some convention for "components" in Godot. Something like `component_3d_enabled`, `component_advanced_gui_enabled` etc. I'm just saying that since the engine is moving towards renaming `disabled` to `enabled` for properties, perhaps it would make sense to do the same for the build system.

We even have a section for that:
https://github.com/godotengine/godot/blob/9568bcf1662b0feeaaf6c67ff7d0d25072f7860d/SConstruct#L123-L127

**Comment by akien-mga** [comment]
Superseded by https://github.com/godotengine/godot/pull/51048.

**Pull request closed without merging**
