### PR TITLE
Bugfix on RenderingDevice::shader_compile_spirv_from_source() trying to compile empty stages

### PR DESCRIPTION
**Pull request by ChristopheClaustre**
Hi fellow devs,

### Why ?
I noticed that when one compiles a shader from source using `RenderingDevice::_shader_compile_spirv_from_source()` ([here](https://github.com/godotengine/godot/blob/master/servers/rendering/rendering_device.cpp#L179)) it has to fulfill every stage in order to have its `RDShaderSource` accepted.
As each `RDShaderSPIRV::compile_error[stage]` for empty `RDShaderSPIRV::source[stage]` will be filled with errors about language version, making it unusable when given to the pipeline.

The error stored in `RDShaderSPIRV::compile_error[stage]`:
> Failed pre-process:
> ERROR: #version: ES shaders for SPIR-V require version 310 or higher
> ERROR: 1 compilation errors.  No code generated.

Later when giving the resulted `RDShaderSPIRV` in `RenderingDevice::_shader_create_from_spirv()` ([here](https://github.com/godotengine/godot/blob/master/servers/rendering/rendering_device.cpp#L215)):
> _ready: Can't create a shader from an errored bytecode. Check errors in source bytecode.

### Modifications:
This bugfix only had a check before trying to compile a stage. In order to avoid the mess later.

### Workaround:
Without these PR, one have to modify the resulted `RDShaderSPIRV` and empty each error attribute of empty stages and then It will be usable again.

### More ?
I already discussed about this bug 2-3 months ago on the contributor chat (notably with @reduz) and they validated that it was a bug.
_(Because of personal matters, I didn't had time to work on godot recently but here am I.)_

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good to me. Will need @reduz to take a quick look to verify.

**Comment by Nordup** [comment]
It helped me! Thanks a lot :+1:

**Comment by ChristopheClaustre** [comment]
> It helped me! Thanks a lot 👍

Glad you liked it @Nordup ! Hope my correction will be merged one day ^^"

**Comment by akien-mga** [comment]
Couldn't get said quick look from @reduz, so let's merge, and he'll complain in 6 months if that was wrong ;)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Ah I missed that there was a merge commit in this PR... too late. Please use `rebase` (or `pull --rebase`) to update your PRs in the future instead of `merge`: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by ChristopheClaustre** [comment]
Thanks you very much @akien-mga.
Sorry for the merge commit, it was a mistake.

**Pull request merged**
