### PR TITLE
GDScript Documentation-System UI implementations

### PR DESCRIPTION
**Pull request by ThakeeNathees**
This PR is the UI implementation part of <s>#39359</s> #41095 (my GSoC project) I split the pr into core and UI.
Note: this pr depend on #41095 (yet it needs some changes to work with #41095 after merged. I've marked TODOs for dependencies )

Images
------

Capture

doc-ui

### CODE REVIEW

**Comment by SIsilicon** [comment]
I wonder what's the status of this? I'm currently making an add-on in 3.2 that displays GDScript documentation along with the other built-in classes.

**Comment by ThakeeNathees** [comment]
@SIsilicon there are some improvements and implementation to do (I haven't tested this after the documentation system merged). and need some review from the core devs. If you have any suggestions let me know. However, it's not compatible with Godot 3.x. And it possibly will be included in 4.0 or later. Meanwhile, I'll try to polish this.

**Comment by Xwdit** [comment]
Hi, is there any progress recently? Can’t wait for this pr to be merged :laughing:

**Comment by YuriSizov** [comment]
This needs some work to bring up to date, but it's also not a compat breaking change which can be resolved in any future 4.x version. So I'm kicking it to the `4.x` milestone.

Another reason is that the API part of this PR has an up to date version in https://github.com/godotengine/godot/pull/62928, while the user interface may be an overkill and better left for users to implement to their spec.

**Comment by YuriSizov** [comment]
The feature itself is now implemented in https://github.com/godotengine/godot/pull/76490. If there is a demand for a GUI version, then I guess a new PR is needed at this point. Thanks for your work nonetheless!

**Pull request closed without merging**
