### PR TITLE
Add FastNoise

### LINKED ISSUE #22337: FastNoise Implementation
Now that issue #21569 has been added we can think about adding more noise modules. This will give users the option to select what type of noise they would like to 

I suggest we look into adding [FastNoise](https://github.com/Auburns/FastNoise), it is super fast plus it includes many types of noise (cellular, value, simplex, perlin, white). If possible, we could even take advantage of SIMD with FastNoiseSIMD, which is significantly faster than any of the other options out there.

### PR DESCRIPTION
**Pull request by TokisanGames**
* Builds on 4.0
* Adds abstract Noise class to define interface
* Provides a default implementation of get_seamless_image() (swap quadrants, alpha blend over seams)
* Reorganizes OpenSimplexNoise, NoiseTexture classes and folders
* Implements FastNoise
* Fixes #22337
 
FastNoise [4.0 branch](https://github.com/tinmanjuggernaut/godot/tree/add_fastnoise) (this PR)
FastNoise [3.2 branch](https://github.com/tinmanjuggernaut/godot/tree/add_fastnoise3.2) (I can make a PR for backporting anytime)

FastNoiseSIMD has been moved to a [separate repository](https://github.com/tinmanjuggernaut/godot_fastnoise_simd) due to cross-compiling w/ mingw-w64 being unsupported. It supports both 3.2 and 4.0.

Binaries with both FastNoise and FastNoiseSIMD:
http://tokisan.com/godot-binaries/

### CODE REVIEW

**Comment by Xrayez** [comment]
> Adds abstract Noise class

This alone deserves more attention, currently I'm not so keen to reinventing different types of `Noise`/`NoiseTexture2D/3D` for each type of noise providers. Making those `get_image/get_seamless_image` virtual is good imo. 

The only issue I have is with this method:

```cpp
virtual Ref<Image> get_seamless_image(int p_size) { return Ref<Image>(); }
```

It accepts a single `p_size` while [there are](https://github.com/Xrayez/godot-anl/blob/35116ea4f3a2418fae360ed58d214202a0752c2b/noise.h#L270-L277) implementations which can generate seamless textures of any aspect ratio.

**Comment by tinmanjuggernaut** [comment]
> The only issue I have is with this method:
> `virtual Ref<Image> get_seamless_image(int p_size) { return Ref<Image>(); }`

Yeah, I agree. Thanks for the feedback. I just moved the current implementation without even looking at it. How about matching the get_image parameters?
```
virtual Ref<Image> get_seamless_image(int p_width, int p_height) { return Ref<Image>(); }
```
-----

Also for all watchers, I asked for some guidance on the issue #22337. Thanks

**Comment by bojidar-bg** [comment]
Quick note: You could have `get_seamless_image(width, height = -1)` with a default argument, so that it is automatically backwards-compatible, with implementers just having to add `if (height == -1) height = width`.

**Comment by tinmanjuggernaut** [comment]
Fastnoise updates. Just last three commits above, had to force push.

* Abstract Noise::get_seamless_image is now (x,y) explicit. Only OSN supports default y=-1, and has to check for it for backward compatibility.
* Moved invert to NoiseTexture, now works for OSN
* Disabled Simplex (Uncomment in thirdparty/noise/FastNoise.h to reenable)
* Replace all floats w/ real_t in FN/OSN. FN library supports doubles via define. OSN uses doubles by default
* Various minor updates/renames

I haven't touched FN/seamless. I've been working on wrapping FN_SIMD.

**Comment by tinmanjuggernaut** [comment]
### Updates:
* Add FastNoiseSIMD
* Hardware specific compiler flags in scons
* Many other tweaks

FastNoiseSIMD is has nearly all the features of FastNoise, except these:
1. Lookups of singular values (e.g. f = get_noise_3d(x,y,z) ) doesn't exist natively. All lookups are done in sets. I've added singular lookup functions, however they are 3x slower than the regular FastNoise
1. No 4D simplex (disabled anyway) or whitenoise. 
1. Recursive cellular lookups aren't as featureful. On FN, you get a whole secondary FN object and can control all settings. On SIMD, you can only specify the secondary type and a few other things. So there's no way to achieve this look directly in SIMD:
image

### Benchmarks
I chose Perlin Fractal as the default values look most like OpenSimplexNoise. Metrics are ms needed to generate and normalize a 2D image within Godot. SIMD are using AVX2 on a Core i7-8570H.

|   | 1k | 2k | 4k |
---|---|---|---
OpenSimplexNoise | 107 | 435 | 1730 |
FN Perlin Fractal | 104 | 400 | 1600 |
SIMD Perlin Fractal (singular) | 304 | 1210 | 4800 | 
SIMD Perlin Fractal | 28 | 107 | 430 | 
---|---|---|---
FN Value | 74 | 294 | 
SIMD Value | 13 | 44 |
---|---|---|---
FN Heavily tweaked Cellular |  | 2284 |
SIMD Heavily tweaked Cellular |  | 229 |

FastNoiseSIMD generating basic 2D textures is 4-6x faster than FastNoise, and gets even faster as the algorithms gets more complex, even into 3D. Generating large blocks of noise can be split up into multiple threads becoming *another* 3-7x faster or (up to 40x faster than FastNoise)! [pyFastNoiseSIMD benchmarks](https://github.com/robbmcleod/pyfastnoisesimd)

On #22337 @Calinou asked if the performance as good on hardware that can't take advantage of it. All new intel 64-bit processors have SSE2 built in, so I can't turn it off, but I can compare regular, SSE2 and AVX2. I'd guess the SIMD sets w/o SIMD is as good regular FN. Maybe better because the algorithm is working in one set, rather than being called for every individual pixel/voxel. This is generating a 1k image using the author's [demo app](https://github.com/Auburns/FastNoiseSIMD/releases/tag/0.7):

|   | FN | SIMD SSE2 | SIMD AVX2 
---|---|---|---
Value | 66| 23 | 6 
Perlin Fractal | 108 | 94 | 43
Cellular Noise Lookup to Simplex | 96 | 117 | 61
Cellular Distance2 Sub | 209 | 75 | 30 



### Questions

#### 1. Both classes or combined or...?
SIMD singular lookups are a waste of time. We could:
* Keep both classes and provide only sets in SIMD and only singular in FN. 
* I could maybe combine them into one class. The features are almost the same, but there are some differences. That means some combination of features won't return anything, and definitely the noise pattern from the singular version will not match the set version. Least preferred option.
* SIMD could be considered too fringe use and be a separate module not in core. But the use case is definitely needed for @Zylann and me in Voxel Tools as OSN is a bottleneck.

#### 2. Memory, Pointers, & References
FastNoiseSIMD GetNoiseSet() returns a pointer to a float array allocated with _aligned_malloc, posix_memalign, (or new if no SIMD avail). 

* Is there a way to add this memory into a Ref or some other mechanism so Godot can manage it?

* I wrote in some basic memory management ([here](https://github.com/tinmanjuggernaut/godot/blob/dc11b20990d7f5ea7446f7cf90d13b4c1503f4fc/modules/noise/fast_noise_simd.cpp#L63) and [here](https://github.com/tinmanjuggernaut/godot/blob/dc11b20990d7f5ea7446f7cf90d13b4c1503f4fc/modules/noise/fast_noise_simd.cpp#L164)) that keeps a linked list of all sets that have been allocated and deletes them upon request or upon the destructor (FastNoiseSIMD.cpp). Is this sufficient?

* Am I correct in thinking that there is no way to pass by reference in GDScript? I was thinking I could leave the function returning float* for C++ use. Then for GDSCript provide a separate function that returns a PoolRealArray and copy all of the elements into it. Seems kinda clunky.

* Is there a way to override functions so I can do the above and use the same names for C++ and GDScript? The macros complain about the same names. Is the convention to use _function for public C++ use?

#### 3. Namespace
* How do I properly namespace `FastNoiseSIMD`? FN had its own namespace, so a simple `typedef fastnoise::FastNoise _FastNoise;` allowed us to use `FastNoise`. SIMD has an internal namespace, but it's public class does not. When trying to add a namespace in the same way as FN I ran into too many name scope issues from the internal class, so I just ended up renaming the public class. Is there a better way?


#### 4. Crashes
So far what I've been doing has been stable aside from obvious bugs. But only just today, when changing noise values, Godot has hung with this repeating in the console. I don't think I'm causing this. Anyone know what this could be? 
```
ERROR: RichTextLabel::_process_line: Index line=0 out of size (l.offset_caches.size()=0)
   At: scene\gui\rich_text_label.cpp:170
```

**Comment by tinmanjuggernaut** [comment]
Updated the PR. Currently, this branch builds against 3.2. I will update it to 4 and submit after the PR apocalypse.

Notes:
* I've figured out how to get the noise sets into GDScript. GDScript can now retrieve a Value noise set in a PoolRealArray of 4M floats in 25ms. On my benchmarks above, generating that same amount and applying it to a 2k image texture occurred in 44ms, so there's no slowdown in making the data available to GDScript.

* I've been extensively testing and adjusting FastNoise and FastNoiseSIMD while adding support for it in @Zylann's VoxelTools. Noise generation from all of these algorithms has been pretty fun and so far both libraries are quite usable and stable.

* There is no seamless texture option built into either library. Pulling continuously offset 2D/3D data (e.g. moving a player through a 3D voxel world generated from 3D noise) is completely seamless because as your position changes the noise offset smoothly changes the noise data as expected.

The issue is when requesting a fixed noise set (e.g. a 2k texture) and having the edges of that set blend into each other. I might be able to hack one or two algorithms to achieve it, such as plain perlin noise. However, there are an incredible amount of options, including cellular, gradient and fractal perturbation of any algorithm, recursive cellular lookups using different algorithms, etc that make supporting this feature a herculean task that is beyond me. And that's just for FastNoise. Then doing it again in FastNoiseSIMD that was developed in macro hell in order to detect SIMD level and maintaining aligned memory, and with different algorithm options, OMG.

So my current intention is to return a black image when NoiseTexture::seamless is enabled and note in the documentation that it's unsupported. Or maybe it could return null and there could be an editor flag that says this option isn't supported with FN/FNSIMD. Thoughts?

For example, how is one going to make noise textures with large features like these seamless? Maybe some ugly blending of 100px width on the borders?

image
image
image


* FastNoiseSIMD doesn't build with all platforms according to the appveyor test. I need to hack it to see if I can fix it for my next task.

* I'm planning on updating the prebuilt binaries on my website with Godot 3.2, VoxelTools, along with FastNoise, and FastNoiseSIMD in the next couple of weeks if you guys want to check them out.

**Comment by bojidar-bg** [comment]
For seamless, the current code samples points on a 4D sphere using `get_noise_4d(sin(i), cos(j), sin(j), cos(i))`.

An alternative idea might be to do something similar to GIMP's "Make seamless" function. It basically blends the pixel at `x, y` with `(x + width / 2) % width, (y + height / 2) % height`.

**Comment by tinmanjuggernaut** [comment]
FastNoise only provides one 4D function: simplex which is disabled. FastNoiseSIMD doesn't provide any 4D options currently.

I could do blending. I suppose ugly is better then black. In fact, I could put this in Noise as the default seamless option if not overriden. 👍

**Comment by tinmanjuggernaut** [comment]
I've implemented a default Noise::get_seamless_image(). It gets a 10% larger source image, swaps the quadrants, then alpha blends the 10% overlap over the middle seams. Noise algorithms that do not implement their own seamless function can use this (e.g. FastNoise and SIMD).

The results are ok in some cases. Here is a grid of four planes, one selected:

image

image

image


And much more obvious or ugly in others:
image

image

My next step is to try to get SIMD compiling on all platforms, making 3.2 binaries available on my website, and then submitting for 4.0.

I used to be able to get travis and appveyor build reports, but I can't see that anymore. How can I get those reports so I can fix the build issues?

**Comment by Zireael07** [comment]
I absolutely love that seamless noise trick already <3

**Comment by tinmanjuggernaut** [comment]
FastNoiseSIMD compiles fine with windows/msvc or linux/gcc. However, it won't compile with mingw-w64 which is used in the official dockers to cross-compile for windows from Linux. 

The issue is that it won't properly preprocess a statement like this and produces thousands of errors.
```
FastNoiseSIMD_internal.cpp:43:22: error: expected initializer before 'L3_FUNC_Lerp'
 #define L_VAR2(x, l) L##l##_##x
                      ^
FastNoiseSIMD_internal.cpp:44:21: note: in expansion of macro 'L_VAR2'
 #define L_VAR(x, l) L_VAR2(x, l)
                     ^~~~~~
FastNoiseSIMD_internal.cpp:45:16: note: in expansion of macro 'L_VAR'
 #define VAR(x) L_VAR(x, SIMD_LEVEL)
                ^~~~~
FastNoiseSIMD_internal.cpp:46:17: note: in expansion of macro 'VAR'
 #define FUNC(x) VAR(FUNC_##x)
                 ^~~
FastNoiseSIMD_internal.cpp:682:25: note: in expansion of macro 'FUNC'
 static SIMDf VECTORCALL FUNC(Lerp)(SIMDf a, SIMDf b, SIMDf t)
                         ^~~~
```

I've been able to work around that by having gcc/linux preprocess it, then passing that to mingw, but there are other compiling issues I haven't been able to resolve. 

However, even if I were to nail those down, the other problem is that mingw-w64 doesn't support AVX byte alignment and allegedly will crash even if it does compile. This issue has persisted for years. Apparently cygwin/gcc, llvm, linux/gcc, and msvc don't share this issue.

So, my thinking is that this PR will be limited to just FastNoise and Noise, and I can package up my FastNoiseSIMD work as a separate module so people can build it themselves. At least until Godot moves off of mingw for official builds, or mingw fixes the issue; though both are unlikely.

Unless there are other suggestions?

Reference:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54412
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49001
* https://sourceforge.net/p/mingw-w64/mailman/message/34453497/
* https://github.com/msys2/MSYS2-packages/issues/1209
* https://stackoverflow.com/questions/30928265/mingw64-is-incapable-of-32-byte-stack-alignment-required-for-avx-on-windows-x64
* https://stackoverflow.com/questions/5983389/how-to-align-stack-at-32-byte-boundary-in-gcc
* https://github.com/shibatch/sleef/issues/172#issuecomment-367338219
* https://stackoverflow.com/questions/30926241/wrapper-for-m256-producing-segmentation-fault-with-constructor-windows-64
* https://stackoverflow.com/questions/5983389/how-to-align-stack-at-32-byte-boundary-in-gcc

**Comment by Calinou** [comment]
> However, even if I were to nail those down, the other problem is that mingw-w64 doesn't support AVX byte alignment and allegedly will crash even if it does compile. This issue has persisted for years. Apparently cygwin/gcc, llvm, linux/gcc, and msvc don't share this issue.

Requiring AVX support would make it impossible to run Godot on older systems (let alone AVX2), so it might not be a good idea anyway. (I heard it can be made optional still, at the cost of larger binaries.)

**Comment by tinmanjuggernaut** [comment]
FastNoiseSIMD auto detects simd level at runtime, and does not require running on an AVX system. It does require a compiler capable of building AVX instructions, which modern ones do, except mingw apparently.

**Comment by tinmanjuggernaut** [comment]
FastNoiseSIMD has been moved to a separate repository due to cross-compiling w/ mingw-w64 being unsupported. It supports Godot 3.2 and 4.0 with separate branches: 
https://github.com/tinmanjuggernaut/godot_fastnoise_simd 

This PR has been updated for Godot 4.0.

FastNoise 3.2 branch: https://github.com/tinmanjuggernaut/godot/tree/add_fastnoise3.2
FastNoise 4.0 branch (this): https://github.com/tinmanjuggernaut/godot/tree/add_fastnoise

Next to do: documentation, and presumably set FastNoise to be the default noise algorithm as it provides many more noise algorithms and the one that provides essentially the same look as OpenSimplexNoise (FastNoise Perlin Fractal) is about the same speed.

**Comment by tinmanjuggernaut** [comment]
New updates
* Added documentation
* Noise::get_seamless_image now smoothsteps the alpha blend for a considerably smoother blend. See images below
* OpenSimplexNoise::get_seamless_image now returns Noise::get_seamless_image if width/height aren't equal (without this, either the results aren't usable or it crashes)
* Added coordinate offset to FastNoise
* Minor rearrangement, formatting, fixes

3.2 is working, master won't build at the moment so can't test 4.0.

This PR is basically done. Just needs a test on 4.0 once master is fixed and I can submit.

smoothstepped_alpha

**Comment by tinmanjuggernaut** [comment]
I finally fixed travis' errors. Clang didn't like the use of `override`. This builds against 4.0 and is ready for review anytime. I also have a separate 3.2 branch ready to go.

**Comment by tinmanjuggernaut** [comment]
Binaries compiled with FastNoise, FastNoiseSIMD, and Voxel Tools are at the link below if you want to try it out. A video will come in the next week or two to show them off.
http://tokisan.com/godot-binaries/

**Comment by clayjohn** [comment]
From a quick look this appears to be shaping up very nicely! I haven't had a chance to dig into the details of the new Noise API, but I will take a look.

A few notes in the meantime. First, it is unlikely this will be cherrypicked for 3.2 as it is a new feature entirely. Second, the server renames appear to conflict with changes you made in noise_texture.cpp so you will need to rebase and resolve the conflicts.

**Comment by tinmanjuggernaut** [comment]
Rebased and force-pushed. No conflicts.

**Comment by JFonS** [comment]
I tested the PR and looked over the code. It looks great and really flexible, but I have a couple of things I would change.

If I'm not mistaken FastNoise implementation already includes a Simplex-like (value) noise, so I don't know if we should keep them both. @akien-mga is there a way to keep OpenSimplexNoise as a resource type for compatibility but mark it as deprecated? The resource should load fine if it is found in an existing scene but it should not appear as an option when creating new resources.

My other problem is with the FastNoise inspector properties. Right now you get a lot of properties at the same time and it's hard to see what does what:
Screenshot from 2020-04-06 13-11-59

Also, some properties only have a meaning when a certain type of noise is used. I wonder if it makes sense to split the FastNoise class type into separate classes, for example ValueNoise, PerlinNoise, CellularNoise, WhiteNoise and CubicNoise. This would reduce the amount of properties you see at once but it would also bloat the number of resource types in the engine. Maybe there is a better way to split the classes, I don't know :)

Another option would be to use `_validate_property` to hide the properties that are currently not in use (see particles_material.cpp for an example). So only the properties that makes sens to change are visible.

Finally, regardless of the other two options, the properties should be split into groups. I can see three clear groups: Perturbation, Fractal and Cellular. Again, this helps reduce clutter and gives user a better idea of what each property is supposed to do.

Sorry for the long rant and please don't take it as harsh criticism. I think the new noise types are great and will bring lots of flexibility, I just don't want to scare new users with a ton of properties unknown to them :)

**Comment by Zylann** [comment]
Would be really nice to have a preview of the noise pattern in 2D even if the resource is not specifically a texture?

**Comment by tinmanjuggernaut** [comment]
@JFonS 
> If I'm not mistaken FastNoise implementation already includes a Simplex-like (value) noise, 

FastNoise's Perlin Fractal is very similar in look and performance to OpenSimplexNoise, but has even more options. OSN does have true seamless noise for 2D images, whereas I've provided a fake workaround, that looks reasonable. The only other need for OSN is backward compatibility, but once the new version of OSN has 4D+ it would be worth replacing with OSNv2 and it's other variations. Maybe that could be done in Godot 4.5 or 5.0. So deprecating OSN wouldn't be needed, but that future version would break the consistency of OSN values across versions.

> My other problem is with the FastNoise inspector properties. Right now you get a lot of properties at the same time and it's hard to see what does what:
> Also, some properties only have a meaning when a certain type of noise is used. 

Yes, the fractal options only work if you are using a fractal noise type, or fractal perturbation. Cellular options only work with cellular noise. Perturbation works with everything. I and the library author have prefaced every variable so that cellular variables start with cellular_ and fractal modifiers begin with fractal_.

> I wonder if it makes sense to split the FastNoise class type into separate classes, for example ValueNoise, PerlinNoise, CellularNoise, WhiteNoise and CubicNoise. This would reduce the amount of properties you see at once but it would also bloat the number of resource types in the engine. 

Hmm, if ValueNoise, PerlinNoise, et al inherited from FastNoise that could be pretty easy to implement, I think. But we are talking about another 5 additional classes, plus one when the Simplex patent expires. And if they have the FastNoiseSIMD module also, there's another six, so their noise dropdown now has a ton of options. I don't think this solves the problem. It just moves it to another window.

FN/FNSIMD just has a lot of options, which means a user has to learn what they all do by one of the following:
* Messing with the options
* Reading the documentation and messing with the options
* Watching my tutorial video (that I'm working on now), then messing with the options

There's just no getting around messing with the options to get an intuitive sense of what does what. However, it's all visual so it's not really that difficult for someone to get a sense of what does what after a few minutes of playing with it. 


> Another option would be to use `_validate_property` to hide the properties that are currently not in use (see particles_material.cpp for an example). So only the properties that makes sens to change are visible.

This sounds reasonable. I see particle material also has expandable groups. I can look into hiding options and using expandable groups.

> Sorry for the long rant and please don't take it as harsh criticism. 

No problem, no sweat. Actually I was expecting a harsher code review, but that may still come.


@Zylann 
> Would be really nice to have a preview of the noise pattern in 2D even if the resource is not specifically a texture?

Noise are saveable objects. So you can put a 2D texture on screen and use the same noise object in a voxel generator. Then you can adjust the noise settings in either place and it will change the 2D preview, and set what will be used for the 3D landscape. This works really well for visualizing the voxel landscape and I'll show it in my video. Otherwise, I don't know what else can be done to provide a preview, if not through a noise texture.

**Comment by Zylann** [comment]
> Noise are saveable objects. So you can put a 2D texture on screen and use the same noise object in a voxel generator. Then you can adjust the noise settings in either place and it will change the 2D preview, and set what will be used for the 3D landscape. This works really well for visualizing the voxel landscape and I'll show it in my video. Otherwise, I don't know what else can be done to provide a preview, if not through a noise texture.

I meant it so users don't have to do all this setup systematically just to have an idea of how the noise looks like. It can be done in another PR though.

**Comment by tinmanjuggernaut** [comment]
Got caught up in a gamejam. I've now added property groups and hide them when not relevant to the currently selected options. I've also rebased and passed checks.

**Comment by arkology** [comment]
Any chance it will be in 3.2?

**Comment by tinmanjuggernaut** [comment]
Unlikely, as it's a new feature, but you can build it yourself with my 3.2 branch linked at top or use my binaries.

http://tokisan.com/godot-binaries/

**Comment by Zylann** [comment]
When reading this post: https://godotforums.org/discussion/22949/hterrain-generating-a-seamless-random-heightmap
I've been thinking of your comment: https://github.com/godotengine/godot/pull/35144#issuecomment-593099623
And I wonder if we could just get a `make_seamless` function in `Image`, so that anyone can take an image and make it loop quickly?

**Comment by tinmanjuggernaut** [comment]
The method could be used, though only 90% of the heightmap would be used. The last 10% is needed for the overlap. The number is arbitrary. 

Of course, if this is an offline generated heightmap, it could be made seamless offline as well, in photoshop or gimp. 

If it's procedurally generated, then he has inner access to the algorithm and can directly blend his edge values procedurally without needing to poorly blend the edges on the rendered Image after the fact. 

Adapting my function for Image is overkill for what the guy is trying to do, and will produce a mediocre result.

All he has to do is: when generating values within the last 5-10% of the bottom or right edges, linear interpolate between the new generated value and the one with the same offset from the opposite edge, based on the % of distance from the margin to the edge. That's a linear blend. 

It will look smoother mixing with a 0.1,0.9 smoothstep instead of lerp/mix. 

https://github.com/tinmanjuggernaut/godot/blob/808037eabb4f020f888871edc59df3c2cc0bf576/modules/noise/noise.cpp#L99

**Comment by tinmanjuggernaut** [comment]
It was finished months

**Comment by tinmanjuggernaut** [comment]
It was finished months ago. It's just waiting on the devs to review and merge. But you can use it now by building yourself or using my binaries.

**Comment by Calinou** [comment]
@tinmanjuggernaut There are several merge conflicts that need to be resolved before this can be merged.

**Comment by tinmanjuggernaut** [comment]
It had its initial review and the issues brought up were fixed months ago. I also monitored it for a while. It was ready to go, the devs were not ready to look at it.

If the devs are ready to review and merge, I'll gladly update it. But if it's still going to be months, then I'll wait.

**Comment by 3top1a** [comment]
Any chance it will be in 4.0?
I need it for my project and i don't want people downloading a custom version of Godot.

**Comment by Calinou** [comment]
@3top1a We can't be certain this will be merged for 4.0 (if at all), sorry.

**Comment by tinmanjuggernaut** [comment]
@Calinou Since @clayjohn added this PR to the PR meeting, I updated it. Now it's ready to go again.

**Comment by ChristianB84** [comment]
Looks like the author of the FastNoise and FastNoiseSIMD libraries is now working on FastNoise2: https://github.com/Auburn/FastNoise2

Since it uses SIMD expressions, it will also lead to the same issues as FastNoiseSIMD with AVX when compiling with mingw. But maybe it'd be easier to optionally disable AVX for compiling with that compiler.

**Comment by tinmanjuggernaut** [comment]
This PR does not include FastNoise SIMD. That is provided as a separate module which won't be integrated in core. When you build Godot with that other module, building for your own system works fine. Only cross compiling has the issue.

I also won't be wrapping the new library version. Even though it includes a few new algorithms, the original two versions are adequate.

**Comment by Zylann** [comment]
In case anyone is curious I integrated `FastNoiseLite` in my module today: https://github.com/Zylann/godot_voxel/commit/c8dcbc55e3ebdec54c16373b3536c99408b381b2

It is slightly different but overall has the same features, although using the latest version of the library which might have some improvements.

image

**Comment by tinmanjuggernaut** [comment]
@Chaosus What specific work does this need? The only review has been from jfons and his comments were addressed.

**Comment by Chaosus** [comment]
@tinmanjuggernaut The `need works` usually means that the author should rebase PR to prevent conflicts.

**Comment by tinmanjuggernaut** [comment]
@Chaosus Has it gone through its review at the PR meeting? Has it been decided that it is wanted? I'll gladly rebase it once the decision has been made. It's already been rebased and updated multiple times, and has been tagged for the meeting for months, without any movement. So this PR doesn't "need work", it "needs a decision". Unfortunately, this tag probably means the death of this PR.

**Comment by Chaosus** [comment]
Indeed, no meetings were held in the past several months (mainly due to @reduz busyness), but this doesn't mean they will not be in the future (alpha is targeted to be released in middle 2021). Keep patience and continue to rebase PR - otherwise, there is no chance for it to be accepted.

**Comment by akien-mga** [comment]
I disagree here, it's not necessarily to endlessly rebase a PR if it's ready and simply awaiting code review. A rebase can always happen once reviewed/approved.

**Comment by Chaosus** [comment]
Ah, yeah, but there is one problem: if the PR is complex and there a lot of conflicting files the other tester will require to manually fix all conflicts in order to check correctness before merging. (But we could trust a contributor of course).

**Comment by tinmanjuggernaut** [comment]
Thank you @akien-mga. It's unreasonable to request contributors to endlessly rebase for months or years, especially when the PR may not even be wanted. I'm happy to do so one the decision has been made. I've also provided binaries if the devs want to try it.

**Comment by akien-mga** [comment]
> Ah, yeah, but there is one problem: if the PR is complex and there a lot of conflicting files the other tester will require to manually fix all conflicts in order to check correctness before approving. (But we could trust a contributor of course).

You can test by compiling the PR branch without rebasing (which is effectively an older version of the engine, but it can be expected that it was working at the time of the last commit). It should of course be rebased and re-tested by the author before merging if the feature and implementation are approved (and a new review might be needed after rebase if it's substantial like it might be here).

**Comment by Chaosus** [comment]
@akien-mga Ok, there is still a lot of undiscovered things with the version control systems for me, I will not bother the respected @tinmanjuggernaut - if he feels better to be without that label on his PR than so be it :)

**Comment by tinmanjuggernaut** [comment]
I wouldn't call myself so respected, but thanks. In this case this PR has already been reviewed by Jfons, so I don't expect it needs much final work, just a decision and rebase.

**Comment by tavurth** [comment]
> It had its initial review and the issues brought up were fixed months ago. I also monitored it for a while. 

Just wanted to chime in and say your work & updates here have been super professional, it's great to see contributors like you working on Godot engine improvements, thank you!

Really looking forward to seeing this progress further, as Godot is missing a good Voronoi implementation.

**Comment by Gamemap** [comment]
Is a simple cave generation with FastNoise possible? (see https://github.com/Auburn/FastNoiseSIMD#features)

**Comment by Zylann** [comment]
@Gamemap you can make cave noise even with today's old OpenSimplexNoise, it's a composition with a bit of math. I don't know what FastNoiseSIMD uses but it's no longer in FastNoise2 (it's rather a composition of simpler operations as well).

**Comment by Gamemap** [comment]
Thank you @Zylann.
Unfortunately I don't know enough in math to create a code for cave generation.
I'll take a look at the documentation and search the internet so I can learn how to create this code. 
If someone has already created a cave generation in 3d it would be nice if I could get the code to learn and use it

**Comment by aaronfranke** [comment]
I am wondering if it would be better if the "Noise" interface was split into its own PR. Even if FastNoise isn't implemented in the core engine, this interface could be used by third-party modules or GDExtension plugins.

Also, this needs to be rebased. As Akien said, endless rebasing isn't necessary, but it has been a year since the last rebase, so I would highly recommend doing so since it shows you're still interested in working on this feature.

**Comment by tinmanjuggernaut** [comment]
The PR could be split. However, I'm not investing any more time unless
there is clear direction that one or the other is desired and likely to be
merged.

**Comment by akien-mga** [comment]
Superseded by #56718. Thanks for the contribution :)

**Pull request closed without merging**
