### PR TITLE
Rename `String.IsAbsPath()` to `String.IsAbsolutePath()`

### PR DESCRIPTION
**Pull request by raulsntos**
**breaks compat**

Follow up to #49279 in C#

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Assuming this builds, this is good.

**Comment by neikeq** [comment]
Did you make sure this doesn't break GodotTools builds? (It may be used there).

Also any reason we renamed `is_abs_path` to `is_absolute_path` but kept `is_rel_path`?

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
> Also any reason we renamed `is_abs_path` to `is_absolute_path` but kept `is_rel_path`?

Seems like an oversight in the original PR

**Comment by raulsntos** [comment]
> Did you make sure this doesn't break GodotTools builds? (It may be used there).

It's not used in `GodotTools`, that project has its own `StringExtensions` with a method named `IsAbsolutePath` already:

https://github.com/godotengine/godot/blob/c3378d56505cfb8e282ed4e542fe170d213371f6/modules/mono/editor/GodotTools/GodotTools.Core/StringExtensions.cs#L54

I also could not find any more references to `IsAbsPath`:

image

**Review by neikeq — APPROVED** [review]

**Comment by mhilbrunner** [comment]
I couldn't find any other references either. Let's see. :)

Thanks for your PR!

**Pull request merged**
