### PR TITLE
GDScript instances lock(Thread Safe)

### PR DESCRIPTION
**Pull request by sanikoyes**

### CODE REVIEW

**Comment by reduz** [comment]
ah this is a good one, I totally missed it. I'll review this one properly and merge as soon as I can.

**Comment by akien-mga** [comment]
There seem to be merge conflicts, could you have a look @sanikoyes?

**Comment by reduz** [comment]
problem with this is that i don't think it will work with containers, or might trigger an infinite loop given size keeps changing

**Comment by akien-mga** [comment]
Adding for review for 3.0 then.

**Comment by bojidar-bg** [comment]
@reduz I think you meant to comment on some other PR/issue, right?

**Pull request closed without merging**
