### PR TITLE
[Core] [Mono] [GDNative] Rename "linear_interpolate" methods to "lerp"

### PR DESCRIPTION
**Pull request by aaronfranke**
`Lerp` is a much better name, it's shorter, more familiar, and it's consistent with `lerp`, `inverse_lerp`, and `slerp` in `math_funcs.h`, and with Mono's `Mathf.Lerp` and `Slerp` methods. 

I made the changes for C#, C++, GDScript, and GDNative, ~~but I kept the old "linear_interpolate" methods as well to maintain backwards compatibility.~~

### CODE REVIEW

**Comment by aaronfranke** [comment]
If desired, I could add `lerp` without removing `linear_interpolate` just by copying the code, and we could remove `linear_interpolate` in 4.0?

**Comment by karroffel** [comment]
Thanks for the GDNative implementation! Unfortunately, breaking compatibility of the core struct is a NO-GO, so I will have to create a new GDNative  core extension for any new changes.

**Comment by aaronfranke** [comment]
@karroffel I kept the existing methods, what else can be done to preserve compatibility?

**Review by neikeq — APPROVED** [review]
The C# changes look good to me.

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and release freeze for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

Note: If it's merged after 3.1-stable is released, this change might be considered for cherry-picking into a later 3.1.x release.

**Comment by akien-mga** [comment]
We discussed this on IRC today, and overall the renaming is OK, but we want to avoid breaking compatibility, which this does for C# and to some extent GDNative (breaks ABI).

What we discussed that we should first ensure to have a proper interface for registering deprecated aliases for renamed methods/properties/etc. (via #23023 and maybe some more changes), which could then be used for this PR to rename `linear_interpolate` to `lerp` while adding a compatibility aliases for all bindings. We'd then merge this for 4.0 together with many other planned renamings (#16863).

**Comment by aaronfranke** [comment]
I'm adding the breaks compat label since this does break C# compatibility, which wasn't important back when this PR was created, but I think we care about C# compat now. For GDScript/etc there are still wrapper methods for `linear_interpolate` but these are easy to remove if desired.

**Comment by neikeq** [comment]
C# compat matters if this is going to be cherry-picked. For 4.0 I plan to do a lot of breaking changes though, if I have the time.

**Comment by akien-mga** [comment]
You can fully break compatibility, the aim is to make the API more consistent in 4.0 so we don't need to drag around compat methods forever.

**Comment by aaronfranke** [comment]
@akien-mga Done, but note that because the old aliases are removed, each commit is no longer valid on its own - all three of the non-Mono commits are required for the engine to compile. This breaks the ["from one working state to another working state"](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) philosophy, but maybe there's also value in keeping these changes separate for ease of reviewing. I can always squash if desired.

**Comment by akien-mga** [comment]
Will need yet another rebase. We can now break compat for GDNative too in 4.0, we'll want the API to match Core anyway so there's no way to presence compatibility without tons of outdated bindings.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
