### PR TITLE
New Shape2D* icons.

### PR DESCRIPTION
**Pull request by Ovnuniarchos**
All sons of old go… of Shape2D now have editor icons. I tried to keep the style consistent with the new icons.

### CODE REVIEW

**Comment by djrm** [comment]
Can you also contribute the svgs [here](https://github.com/djrm/godot-design)

**Comment by reduz** [comment]
nice, please don't forget to add the 32x32 icons in the icons/2x folder :)

**Comment by djrm** [comment]
This may sound pendantic but some of the icons are not pixel perfect, for instance capsule shape, if you want we can work on the design repo, to fix those problems

**Comment by djrm** [comment]
Also the workflow is the following


1. you can work on the godot-design repo
2. once you have the svgs paste them in the tools/editor/icons/source folder in the godot repo
3. then from the icons folder do `python svgs_2_pngs.py` and `python svgs_2_pngs.py 2`, this will create the 2x and 1x versions

**Comment by djrm** [comment]
The only one that is not pixel perfect is the capsule shape, the rest are good

you can add this version to your PR:


[icon_capsule_shape_2d.svg.zip](https://github.com/godotengine/godot/files/312740/icon_capsule_shape_2d.svg.zip)

**Comment by Ovnuniarchos** [comment]
Oops! I forgot your corrected capsule icon. Correcting...

**Comment by Ovnuniarchos** [comment]
By the way, I can't upload directly to Godot repo. I should keep on making PRs, right?

**Pull request merged**
