### PR TITLE
Converts an if-else to switch

### PR DESCRIPTION
**Pull request by hbina**
These stack of if-elses are really a switch.
Its also a TODO..

### CODE REVIEW

**Comment by volzhs** [comment]
I think code changes don't have the same logic.

**Comment by aaronfranke** [comment]
This could indeed work as a switch statement, but not like how it's done in this PR. We would need to reverse the order and make all cases fallthrough.

**Comment by hbina** [comment]
omg i thought its an if-else...god

**Comment by Anutrix** [comment]
@aaronfranke I thought the same thing as you but didn't do it because I wasn't sure what to put in default case. Nothing?

**Pull request closed without merging**
