### PR TITLE
[GL] Explicitly set OpenGL 3.3 profile to Core (X11, Windows) and enable GLES2 on Windows.

### PR DESCRIPTION
**Pull request by bruvzg**
1. Explicitly set OpenGL profile to Core (X11, Windows, on macOS it's already Core).
For some unknown reasons RenderDoc was reporting Godot to use Compatibility profile (RenderDoc bug?), while there was no profile flag set and default value should be Core: [GLX_ARB_create_context](https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_create_context.txt), [WGL_ARB_create_context](https://www.khronos.org/registry/OpenGL/extensions/ARB/WGL_ARB_create_context.txt).

2. Enable GLES2 on Windows.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
Should probably pull the core profile bits into 3.0.z

**Comment by akien-mga** [comment]
@bruvzg BTW, shouldn't we bump this to `3_3`? https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L1144

**Comment by akien-mga** [comment]
>  BTW, shouldn't we bump this to 3_3? https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L1144

Yeah, checked the git blame and it has been like that since the opensourcing. It likely dates back to older proprietary Godot versions which used to support OpenGL 3.
https://github.com/godotengine/godot/blame/55d425807f6f1784d6ffd84586ae7efd77c1b352/platform/osx/os_osx.mm#L1028

**Comment by bruvzg** [comment]
@akien-mga there is no such thing, macOS only support `NSOpenGLProfileVersionLegacy` (2.1) , `NSOpenGLProfileVersion3_2Core` (3.2 core forward compat.) and `NSOpenGLProfileVersion4_1Core` (4.1 core forward compat.) and nothing in between.

https://developer.apple.com/documentation/appkit/enumerations/1436146-opengl_profiles

**Comment by akien-mga** [comment]
Thanks for checking. It would be good to update the comment at some point, but it's not urgent :)

**Comment by hpvb** [comment]
Core profile bits have been cherry picked into 3.0.3

**Pull request merged**
