### PR TITLE
Optimize and tweak some SVGs, improve consistency between icons, and fix broken masks in light mode

### PR DESCRIPTION
**Pull request by MewPurPur**
Removes the 2D dark color. Adds a forced black color (similar to forced white) to use for shades, and replaces the uses of 2D dark with that. This is a more flexible solution, as it allows a shade effect to be used everywhere (our icons already extensively use transparency tricks to achieve the coloring they need)

Aside from this, I fixed some icons. The biggest are these few:

image

Which broke because I was using an `#ffffff` mask, but this gets converted into a dark color on light theme.

But also others, and some tweaks too, like optimizations and standardizing viewport icons' widths.

Also, Helps with #82579

### CODE REVIEW

**Comment by Calinou** [comment]
Unfortunately, this doesn't fix the issue for 3D gizmo icons for me:

image

**Comment by MewPurPur** [comment]
OK I see, this isn't a complete fix, it only helps with the black border.

**Comment by capnm** [comment]
In the 2D view, it looks now perfect.

image

**Comment by capnm** [comment]
Sprite3D ...
image

**Comment by capnm** [comment]
I recompiled the current [tip](0ca8542329888e8dccba89d59d3b728090c29991) + this PR + cleared all Godot settings & caches - that solved the issues for me.
grafik

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` 5ee983188de97ae027f9b9c1443438063f708a7e), it works as expected.

**Comment by YuriSizov** [comment]
> Fixes #84309

@MewPurPur I would really appreciate if you didn't do that. These are completely different issues. I can't even be sure @Calinou tested this other part, since it was added last minute.

**Comment by MewPurPur** [comment]
Do you want me to split off the negative space Panel icons? I think the rest don't warrant discussion. Cali also suggested the hollow icons, so I doubt he missed this in his review.

**Comment by YuriSizov** [comment]
> Should I split off the negative space Panel icons?

Yes, I think so.

**Comment by MewPurPur** [comment]
Yessir!

**Comment by YuriSizov** [comment]
Could you also amend the commit message?

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
