### PR TITLE
Add a unit test suite for GDScript

### PR DESCRIPTION
**Pull request by Calinou**
This tests run-time script loading and is a complement to the existing integration tests.

### CODE REVIEW

**Comment by akien-mga** [comment]
Shouldn't this go in `modules/gdscript/tests/` together with other GDScript tests? And then might need a more explicit name as `test_gdscript.h` already exists.

**Comment by Xrayez** [comment]
> Shouldn't this go in `modules/gdscript/tests/` together with other GDScript tests? And then might need a more explicit name as `test_gdscript.h` already exists.

Yes, but I'm not sure if this will work, but should likely work... Yet maybe Calinou has other motivations for doing so. But yeah, I'd prefer to have all GDScript related tests to be under `modules/`.

**Comment by Calinou** [comment]
> Shouldn't this go in `modules/gdscript/tests/` together with other GDScript tests? And then might need a more explicit name as `test_gdscript.h` already exists.

Done. I ended up just moving the test case into the existing GDScript test suite.

**Review by vnen — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by vnen** [comment]
Hm, this is actually crashing for me because the language has not been initialized.

**Pull request merged**
