### PR TITLE
Update classes.xml to master version, add a small feature to doc_status

### PR DESCRIPTION
**Pull request by bojidar-bg**
Hopefully I destroyed no docs in the process, but here is a before and after doc_status comparison:

| Name              |  Methods  | Constants |  Members  | Signals | Overall |
| ----------------- |:---------:|:---------:|:---------:|:-------:|:-------:|
| Before N = 431    | 2902/5030 |  708/1880 |  137/152  | 121/179 |   53%   |
| After  N = 436    | 2613/4951 |  642/1633 |  126/1284 | 120/179 |   43%   |
| Delta  N = +5     |  **-271**/-79 |  **-66**/-247 | **-11**/+1132 |  **-1**/±0  |   -10%  |

### CODE REVIEW

**Comment by akien-mga** [comment]
Some quirks I noticed:
```
+               <method name="to_json">
+                       <return type="String">
+                       </return>
+                       <argument index="0" name="var:Variant" type="Variant">
+                       </argument>
+                       <description>
+                               Convert a Variant to json text.
+                       </description>
+               </method>
```
```
+		<method name="back">
+			<description>
+				Returns the last element of the array if the array is not empty (size&gt;0).
+			</description>
+		</method>
...
+		<method name="front">
+			<description>
+				Returns the first element of the array if the array is not empty (size&gt;0).
+			</description>
+		</method>
```

**Comment by akien-mga** [comment]
I tried reviewing the diff but git gets really confused about all those changes and it's basically unreadable (the additions to the AudioServer API just make it compare totally unrelated classes by matching their `<description>` tags...).

So let's merge and hope nothing important was lost in the process - I trust @bojidar-bg to have done a great job on it :)

**Comment by akien-mga** [comment]
Actually an easier way to review the changes is to compare the rst output (`make rst` in `doc`, after fixing a typo in the HEAD~2 commit) before and after the merge: [classes_rst_changes.diff.xz.txt](https://github.com/godotengine/godot/files/880348/classes_rst_changes.diff.xz.txt) (XZ compressed as it's several MB otherwise - rename to .xz instead of .txt before uncompressing / parsing with `xzless`).

**Comment by bojidar-bg** [comment]
BTW, if there was something important, we can rescue it -- so, feel free to go around and check if something went south. I would really appreciate it if someone can see if any of those things can be done easily:
* Maybe some of the removed Audio classes documentation can be rescued.
* I'm not sure if everything in Viewport was saved... (but, then, it was me who documented the Viewport class, so, who cares)
* Every method which takes or returns a StringArray or a RealArray, and also all links to StringArray or RealArray might have been lost or corrupted, due to me missing them in my automated replacement, and noticing only after I finished half of the manual work.

**Pull request merged**
