### PR TITLE
Preserve vector ratio when dragging through 0

### LINKED ISSUE #77687: Linked vector properties break their ratio when going through zero
### Godot version

4.0+

### System information

Windows 11 22H2

### Issue description

The new feature to link components of a vector value in the inspector, so changing them individually maintains a ratio, has a flaw when it comes to zero values. Since you can't use 0 to build a sensible ratio (what's the ratio of 0 / 20 or 12 / 0 / 5?), having any component reach this value results in values not being updated in a sensible manner anymore.

In plain terms, if you set up some ratio, enable linking, and then drag one of the components in the inspector through the value of 0 multiple times, eventually every component will have the same value (sometimes they will have different signs, depending on the exact starting values). It looks like this:

https://github.com/godotengine/godot/assets/11782833/b5c9b04e-0895-465d-8976-0ba2872149c6

https://github.com/godotengine/godot/assets/11782833/35b9d12a-2994-4d53-b297-f1721036d6e0

https://github.com/godotengine/godot/assets/11782833/09de4cce-5012-4f4c-9aeb-bf48f2bf019f

https://github.com/godotengine/godot/assets/11782833/ee5940b9-c2bd-4b3b-a7d7-b86984bc4250

### Steps to reproduce

You can reproduce it with any engine property with linking available, such as position of spatial (2D, 3D) nodes. Here's a short script I used to test all Vector2/3/4 types (relies on changes from https://github.com/godotengine/godot/pull/77135):

```gdscript

@tool
extends Node3D

var my_vector2 : Vector2
var his_vector2i : Vector2i
var your_vector3 : Vector3
var her_vector3i : Vector3i
var their_vector4 : Vector4
var our_vector4i : Vector4i

func _get_property_list() -> Array:
	return [
		{
			"name": "my_vector2",
			"type": TYPE_VECTOR2,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "his_vector2i",
			"type": TYPE_VECTOR2I,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "your_vector3",
			"type": TYPE_VECTOR3,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "her_vector3i",
			"type": TYPE_VECTOR3I,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "their_vector4",
			"type": TYPE_VECTOR4,
			"hint": PROPERTY_HINT_LINK,
		},
		{
			"name": "our_vector4i",
			"type": TYPE_VECTOR4I,
			"hint": PROPERTY_HINT_LINK,
		},
	]

```

### Minimal reproduction project

See above.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #77687

### CODE REVIEW

**Comment by YuriSizov** [comment]
> core\object\object.cpp:1080 - Error calling from signal 'ungrabbed' to callable: 'EditorPropertyVector3::EditorPropertyVectorN::_value_changed': Method expected 0 arguments, but called with 1.

This fix works for going over 0, but it doesn't handle the case when one of your components starts at 0. Having any component at 0 makes the ratio 1:1(:1(:1)), even between non-zero components.

I think we should handle it as such:

- If you drag a 0 component with linking on, you only change the 0 component's value.
- If you drag another component with linking on, you don't change any 0 components' values.

**Comment by KoBeWi** [comment]
I tried fixing what you said and got lost in indices 😬
I have *some* idea how to unconvolute the logic, I'll try to open a PR soon.

**Comment by KoBeWi** [comment]
Ok I wrote a fix. It requires #77771 though, so I'll change this PR into draft for now.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
