### PR TITLE
[3.x] Fix SceneTreeDock::_selection_changed

### LINKED ISSUE #49451: Inspector shows MultiNodeEdit when only one node is selected after deselecting
### Godot version

3.3.stable 3.x(f3d931410) master(090e4c4abd)

### System information

macOS 11.4

### Issue description

I selected two nodes in the editor and then decided to only change one of them, so I deselected the other one. But changing properties in the Inspector changes both nodes.

The inspector still shows `MultiNodeEdit` after the deselection.

Instead of CTRL-clicking to deselect one node, you can also click one of the nodes in the Scene dock. In this case, clicking the second node works fine, but clicking the first node still shows `MultiNodeEdit`.

### Steps to reproduce

1. Create an empty scene
2. Add two nodes (e.g. drag two icon.png into the scene)
3. Select both of them
4. Select only one of them by CTRL/CMD click the other one
5. Now the Inspector should still say `MultiNodeEdit`, and changing any property would affect both the nodes

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Now handles properly selecting one single node after select multiple nodes (`MultiNodeEditor`)

Fixes #49451

Cherry-pick from #49482

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
The `master` version caused a regression #49627, but the `3.x` might still be fine according to https://github.com/godotengine/godot/issues/49627#issuecomment-861789212. But we should watch out for regressions in `3.x`, I'm wary that this might not be the correct approach given the effect it had in `master`.

**Comment by akien-mga** [comment]
Nope, same regression in `3.x`:
Screenshot_20210616_023358
https://github.com/godotengine/godot/issues/49627#issuecomment-861789212

**Comment by aaronfranke** [comment]
Reverted by #49635.

**Pull request merged**
