### PR TITLE
Version control system improvements

### PR DESCRIPTION
**Pull request by Janglee123**
This is port for 4.0 branch of #39255. I have not tested hooks with GDnative plugin for this port but GUI is working without crashing.

### CODE REVIEW

**Comment by aaronfranke** [comment]
@Janglee123 You accidentally based your commits on the 3.2 branch. You need to base them on the master branch.

**Comment by Janglee123** [comment]
@aaronfranke Thanks. Yes, by mistake I pulled from the origin instead of the upstream.

**Comment by aaronfranke** [comment]
@Janglee123 Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch.

**Comment by Janglee123** [comment]
cross-posting https://github.com/godotengine/godot/pull/39255#issuecomment-787115572

**Pull request closed without merging**
