### PR TITLE
GDScript: typed VM

### PR DESCRIPTION
**Pull request by vnen**
This adds many instructions to the GDScript VM with type specifiers. This allows typed code to be faster since it can make some assumptions instead of checking at runtime. In my tests the typed instructions are always faster (with varying degrees of performance gain).

Naturally this includes the changes in the compiler to make use of the new instructions. There's also a change in VariantInternal to properly initialize Variants and get pointers when the type is unknown (which is used in function arguments, since adding instructions for each combination of argument types is not practical).

I threw in a bug fix at the end that I found when writing benchmarks, since it's only a single line change (and I expect this to be merged soon).

This change should not break anything, it's mostly adding new instructions. Typed code should just work faster and untyped code will not have any performance loss.

*Bugsquad edit: This partially addresses #36060.*

### CODE REVIEW

**Comment by qarmin** [comment]
Since variables with type will be faster, I would add configurable warning which would report every single usage of dynamic typed variable.
It would help users to improve performance by adding type to variables without needing to check manually usage of every single script.

**Comment by Calinou** [comment]
@qarmin There are already warnings for this in the Project Settings ("unsafe" category), but they're disabled by default.

**Comment by akien-mga** [comment]
Compiler seems to run out of heap space :O

Windows MSVC:
```
D:\a\godot\godot\servers/rendering/rendering_device.h(1089): fatal error C1060: compiler is out of heap space
scons: *** [scene\resources\circle_shape_2d.windows.opt.tools.64.obj] Error 2
D:\a\godot\godot\modules\gdscript\gdscript_function.cpp(584) : fatal error C1002: compiler is out of heap space in pass 2
scons: *** [modules\gdscript\gdscript_function.windows.opt.tools.64.obj] Error 1
```

Linux GCC:
```
{standard input}: Assembler messages:
{standard input}:170579: Warning: end of file not at end of a line; newline inserted
{standard input}:171546: Error: unknown pseudo-op: `.'
g++: fatal error: Killed signal terminated program cc1plus
```

**Comment by vnen** [comment]
> @qarmin There are already warnings for this in the Project Settings ("unsafe" category), but they're disabled by default.

Yes, and also the green lines in the editor tell you what are the optimized paths. I do want to improve the tooling to help you make more informed decisions about optimization, but this can be done later.

**Comment by qarmin** [comment]
https://github.com/qarmin/RegressionTestProject/

crashes with this backtrace:
```
[1] /mnt/Miecz/qq/godot-gdscript-typed-vm/bin/godot.linuxbsd.tools.64.llvms() [0x2f55e5b] (/mnt/Miecz/qq/godot-gdscript-typed-vm/platform/linuxbsd/crash_handler_linuxbsd.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f40ab83f210] (??:0)
[3] CowData<Variant>::_unref(void*) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./core/safe_refcount.h:114)
[4] CowData<Variant>::_ref(CowData<Variant> const&) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./core/cowdata.h:355)
[5] Vector<Variant>::operator=(Vector<Variant> const&) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./core/vector.h:126)
[6] Array::_assign(Array const&) (/mnt/Miecz/qq/godot-gdscript-typed-vm/core/array.cpp:116)
[7] Array::operator=(Array const&) (/mnt/Miecz/qq/godot-gdscript-typed-vm/core/array.cpp:157)
[8] PtrToArg<TypedArray<Node> >::encode(TypedArray<Node>, void*) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./core/typed_array.h:133)
[9] void call_with_ptr_args_retc_helper<Node, TypedArray<Node>>(Node*, TypedArray<Node> (Node::*)() const, void const**, void*, IndexSequence<>) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./core/binder_common.h:250)
[10] void call_with_ptr_args_retc<Node, TypedArray<Node>>(Node*, TypedArray<Node> (Node::*)() const, void const**, void*) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./core/binder_common.h:472)
[11] MethodBindTRC<Node, TypedArray<Node>>::ptrcall(Object*, void const**, void*) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./core/method_bind.h:562)
[12] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_function.cpp:3113)
[13] GDScriptInstance::call(StringName const&, Variant const**, int, Callable::CallError&) (/mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript.cpp:1321)
[14] ScriptInstance::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/qq/godot-gdscript-typed-vm/core/script_language.cpp:314)
[15] Node::_notification(int) (/mnt/Miecz/qq/godot-gdscript-typed-vm/scene/main/node.cpp:58)
[16] Node::_notificationv(int, bool) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./scene/main/node.h:45)
[17] Node3D::_notificationv(int, bool) (/mnt/Miecz/qq/godot-gdscript-typed-vm/./scene/3d/node_3d.h:?)
[18] Object::notification(int, bool) (/mnt/Miecz/qq/godot-gdscript-typed-vm/core/object.cpp:806)
[19] SceneTree::_notify_group_pause(StringName const&, int) (/mnt/Miecz/qq/godot-gdscript-typed-vm/scene/main/scene_tree.cpp:818)
[20] SceneTree::idle(float) (/mnt/Miecz/qq/godot-gdscript-typed-vm/scene/main/scene_tree.cpp:447)
[21] Main::iteration() (/mnt/Miecz/qq/godot-gdscript-typed-vm/main/main.cpp:2426)
[22] OS_LinuxBSD::run() (/mnt/Miecz/qq/godot-gdscript-typed-vm/platform/linuxbsd/os_linuxbsd.cpp:240)
[23] /mnt/Miecz/qq/godot-gdscript-typed-vm/bin/godot.linuxbsd.tools.64.llvms(main+0x6bf) [0x2f5460f] (/mnt/Miecz/qq/godot-gdscript-typed-vm/platform/linuxbsd/godot_linuxbsd.cpp:58)
[24] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f40ab8200b3] (??:0)
[25] /mnt/Miecz/qq/godot-gdscript-typed-vm/bin/godot.linuxbsd.tools.64.llvms(_start+0x2e) [0x2ea97be] (??:?)

```

**Comment by qarmin** [comment]
Also when opening in editor and closing project https://github.com/qarmin/The-worst-Godot-test-project/ then I got this memory leaks
```
Indirect leak of 207648 byte(s) in 721 object(s) allocated from:
    #0 0x2f21efd in malloc (/mnt/Miecz/qq/godot-gdscript-typed-vm/bin/godot.linuxbsd.tools.64.llvms+0x2f21efd)
    #1 0x1972be8a in Memory::alloc_static(unsigned long, bool) /mnt/Miecz/qq/godot-gdscript-typed-vm/core/os/memory.cpp:76:14
    #2 0x1972bc84 in operator new(unsigned long, char const*) /mnt/Miecz/qq/godot-gdscript-typed-vm/core/os/memory.cpp:41:9
    #3 0x7946b2f in GDScriptParser::BinaryOpNode* GDScriptParser::alloc_node<GDScriptParser::BinaryOpNode>() /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.h:1166:13
    #4 0x78a0966 in GDScriptParser::parse_binary_operator(GDScriptParser::ExpressionNode*, bool) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:2030:28
    #5 0x789a911 in GDScriptParser::parse_precedence(GDScriptParser::Precedence, bool, bool) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:1890:22
    #6 0x7879410 in GDScriptParser::parse_expression(bool, bool) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:1897:9
    #7 0x7888f0c in GDScriptParser::parse_if(String const&) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:1526:20
    #8 0x7885d66 in GDScriptParser::parse_statement() /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:1340:13
    #9 0x787bde8 in GDScriptParser::parse_suite(String const&, GDScriptParser::SuiteNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:1272:21
    #10 0x78727fb in GDScriptParser::parse_function() /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:1168:19
    #11 0x7920123 in void GDScriptParser::parse_class_member<GDScriptParser::FunctionNode>(GDScriptParser::FunctionNode* (GDScriptParser::*)(), GDScriptParser::AnnotationInfo::TargetKind, String const&) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:665:14
    #12 0x786b8a0 in GDScriptParser::parse_class_body() /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:708:5
    #13 0x7864792 in GDScriptParser::parse_program() /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:557:2
    #14 0x78622e0 in GDScriptParser::parse(String const&, String const&, bool) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_parser.cpp:359:2
    #15 0x7308cd8 in GDScriptParserRef::raise_status(GDScriptParserRef::Status) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_cache.cpp:59:22
    #16 0x72b8bde in GDScriptAnalyzer::reduce_identifier(GDScriptParser::IdentifierNode*, bool) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:2314:26
    #17 0x724c2d6 in GDScriptAnalyzer::reduce_expression(GDScriptParser::ExpressionNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:1387:4
    #18 0x72a8b84 in GDScriptAnalyzer::reduce_call(GDScriptParser::CallNode*, bool) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:1878:3
    #19 0x724bebc in GDScriptAnalyzer::reduce_expression(GDScriptParser::ExpressionNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:1375:4
    #20 0x725d49d in GDScriptAnalyzer::resolve_node(GDScriptParser::Node*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:830:4
    #21 0x7269d6e in GDScriptAnalyzer::resolve_suite(GDScriptParser::SuiteNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:938:3
    #22 0x7268f55 in GDScriptAnalyzer::resolve_if(GDScriptParser::IfNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:946:2
    #23 0x725c870 in GDScriptAnalyzer::resolve_node(GDScriptParser::Node*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:779:4
    #24 0x7269d6e in GDScriptAnalyzer::resolve_suite(GDScriptParser::SuiteNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:938:3
    #25 0x7259d5c in GDScriptAnalyzer::resolve_function_body(GDScriptParser::FunctionNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:891:2
    #26 0x725792f in GDScriptAnalyzer::resolve_class_body(GDScriptParser::ClassNode*) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:729:3
    #27 0x72e4ac0 in GDScriptAnalyzer::resolve_body() /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:3340:2
    #28 0x730971c in GDScriptParserRef::raise_status(GDScriptParserRef::Status) /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_cache.cpp:78:35
    #29 0x72e5321 in GDScriptAnalyzer::resolve_program() /mnt/Miecz/qq/godot-gdscript-typed-vm/modules/gdscript/gdscript_analyzer.cpp:3354:31
```
Full log - [Leak.txt](https://github.com/godotengine/godot/files/5424115/Leak.txt)

**Comment by SecretPanda420** [comment]
A small newbie question, will this performance work on exporting as well? Or does it work only when run inside the editor? I'm guessing the performance will be the same after all after exporting?
Correct me if I'm wrong.

**Comment by Byteron** [comment]
> A small newbie question, will this performance work on exporting as well? Or does it work only when run inside the editor? I'm guessing the performance will be the same after exporting?
> Correct me if I'm wrong.

It should be even faster after exporting.

**Comment by duane-r** [comment]
Right off the bat, I'm getting an error assigning the result of get_children to an array:

`var bun = $Trail.get_children()`

`ERROR: Assignment of arrays of incompatible types.`
`at: _assign (core/array.cpp:151)`

I also get bizarre results from converting get_child_count to a string. I guess I shouldn't open issues yet, since this hasn't been merged yet?

**Comment by vnen** [comment]
> I also get bizarre results from converting get_child_count to a string. I guess I shouldn't open issues yet, since this hasn't been merged yet?

Does this only happen after you merge this or before too? If it happens on current master just open a new issue.

**Comment by duane-r** [comment]
> Does this only happen after you merge this or before too? If it happens on current master just open a new issue.

Only after merging this pull. The same project works fine on master.

**Comment by vnen** [comment]
I solved the issues reported here, except for the leak. This will need some investigation (I think the last commit is the culprit, but if I remove that I get crashes instead, which is worse).

**Comment by duane-r** [comment]
I'm still getting a crash on opening a project (just with this pull).

https://dpaste.com/BM8VLAN7A

**Comment by vnen** [comment]
@duane-r 
> I'm still getting a crash on opening a project (just with this pull).
> 
> https://dpaste.com/BM8VLAN7A

This is hard for me to debug without a reproduction project.

**Comment by duane-r** [comment]
> > https://dpaste.com/BM8VLAN7A
> 
> This is hard for me to debug without a reproduction project.

I've trimmed it down quite a bit, but it's still not ideal. This will crash on opening with the pull, but open normally with master.

[crash-01.zip](https://github.com/godotengine/godot/files/5436073/crash-01.zip)

**Comment by vnen** [comment]
@duane-r thanks. This was actually a pre-existing bug, this PR just exposed it. I included a fix anyway.

----

Regarding the leak I'm still not sure what's the issue. I've had some trouble with lsan build not reporting the proper source location. I think I'll leave it like this for now and check it again later, since I'm a bit burned out by this code and I want to focus on other tasks.

**Comment by qarmin** [comment]
I tried to create minimal project with leak, but each time when I modify script, then editor crash(this crash is also present in master #43031)

**Comment by akien-mga** [comment]
> I also have no idea how to fix the CI issue.

The compiler is running out of heap memory, so we need to either get access to more memory, or reduce our memory usage.

Some tips from MSDN: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1060?view=vs-2019

For GCC we could try without `-pipe` on CI, but that would slow down builds. Or with `-j1` instead of `-j2`, but same issue.

One promising option from the MSDN tips is to try to split the file into several files, that might be worth considering? If a single file makes us run out of heap memory on CI it's definitely a flag that this file is a resource hog (and even if we work it around for CI builds it might fail for users with lower end setups / their own CI).

**Comment by vnen** [comment]
> One promising option from the MSDN tips is to try to split the file into several files, that might be worth considering?

The problem is that the file is pretty much a single jump table, I'm not sure if it can be split. I could try to move the rest of the code to another file, if that could accomplish something.

Given that, I added a commit splitting it in 3 files to test with the CI

**Comment by akien-mga** [comment]
It seems like it might not just be the CI's hardware resources ([2 cores, 7 GB RAM](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources)) to blame, as I seem to hit a similar issue when compiling locally on an i7-8705G with 16 GB RAM.

It builds just with `target=debug`, but when using `target=release_debug` (the one which fails on CI for GCC and MSVC), the linking step seems to take ages (still going locally after 20 min) and uses 5 GB of RAM.

**Comment by akien-mga** [comment]
I can confirm that the current `master` branch (a4f70d7e6cb2b83f152717a69c9c042dd9424fc9) builds and links fine with `target=release_debug`, so the issue is triggered by this PR.

**Comment by vnen** [comment]
So I did a quite big change here to improve the compilation. Essentially I'm moving code that was inlined multiple times inside every instruction to a single place before every instruction. This decreases the work that the compiler needs to do by a good margin. It also reduces binary size a bit.

This should not have any significant impact in performance, but it also allow us to optimize the addressing modes in the future.

**Comment by akien-mga** [comment]
So the latest iteration seems to work for all platforms but MSVC for `tools=no target=release`.
This build takes 4 hours (!) to generate the obj file for `gdscript_vm.cpp` on GitHub Actions, and I can reproduce this same issue locally with VS 2019 (didn't wait to see how long it would take on my own machine, but more than 40 min in any case).

**Comment by reduz** [comment]
There are two problems with this PR
1. I don't see any situation where you want buffering and not accumulation, or where you would want to turn off accumulation in an OS.
2. the regular input_event function that was separate from accumulate exists because users often submit custom input events that they expect to take place immediately. Merging both breaks this.

**Comment by vnen** [comment]
So unfortunately I'll be leaving this here for a while. I'm not sure what's causing the compilation issue and I have no idea how to investigate that (tried some tools like vcperf but couldn't figure it out).

reduz will make a change in Variant that will allow me to reduce this code by a good amount, by removing the need of specific operator instructions (which are almost half of instructions currently). That will hopefully bring the build time down to something manageable.

I also need to change the disassembler to follow my latest changes.

Since this is not good to merge as is, I'll keep it as a draft for now.

**Comment by SaberToothObject** [comment]
Would be better to have some form of JIT compilation?

**Comment by SaberToothObject** [comment]
Wouldn't it be better to have some form of JIT compilation? Even though the performance gain is ok(ish) it can be better. Performance is a major problem for GDScript.

**Comment by Two-Tone** [comment]
Because JIT isn't allowed on ios devices

**Comment by SaberToothObject** [comment]
What about those who have no intention of developing for IOS? For me, I strictly develop games for PC because I hate the mobile platform in general.

**Comment by akien-mga** [comment]
Please stay on topic, this PR is not about JIT.

**Comment by vnen** [comment]
Closing in favor of #43725.

**Pull request closed without merging**
