### PR TITLE
Add icon for godot editor in windows.

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
I discovered how to do this :)
I used the logo_small.png to create the godot.ico

Edit:
~~Games compiled for windows will have the godot icon~~ (Fixed)

### CODE REVIEW

**Comment by punto-** [comment]
What does this do exactly? Can we do it as part of the windows export
process, without interfering with the inclusion of data.pck in the .exe?

**Comment by guilhermefelipecgs** [comment]
Well, SCons will compile icon.rc to icon.res and then it will embed icon.res with the .exe of godot. Windows will recognize this automatically.

About the exporter, I think this can be done with this approach but I ever seen how export works.

**Comment by guilhermefelipecgs** [comment]
Here [reference](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380599%28v=vs.85%29.aspx) explain better this process.

**Comment by guilhermefelipecgs** [comment]
IMPORTANT!

I created the export template for test to know if this will affect the compiled game and... well, it works but all them now will have the godot icon.

This is not what I was trying to do, I dunno why this affect the export behaviour.

**Comment by guilhermefelipecgs** [comment]
Maybe I put icon.res in the wrong file, I am newbie in SCons.

**Comment by punto-** [comment]
The problem is that scons will generate the .exe that we use later to
export, so when we export it'll have the godot icon.. We want the exported
package to have the icon configured in the project, so we need to figure
out what is actually happening to the .exe when they change the icon, and
it needs to happen after the .exe is already compiled. Ideally we'd only
add the godot icon through scons when you're compiling the editor,
otherwise no icon, or some placeholder that gets replaced by the game icon
when the export happens..

**Comment by guilhermefelipecgs** [comment]
I understood now. For now I'll try change this for add icon only for the
editor. ok?
and later I'll see if I can create the custom icon defined in the project.

2015-07-02 22:00 GMT-03:00 punto- <notifications@github.com>:

**Comment by punto-** [comment]
sounds good

**Comment by guilhermefelipecgs** [comment]
I think this PR now is complete.

**Comment by lorenzobeccaro** [comment]
Nice!! :)

**Comment by akien-mga** [comment]
Hi @guilhermefelipecgs, sorry for the delay. Your PR looks good, it should hopefully be merged for 2.0. It would be cleaner though if you could merge all three commits into one, e.g. with:
```
git rebase -i HEAD~3
```
and then replace the "pick" keyword with "reword" or "fixup", then validate your changes. You should then have only one commit (potentially with reworded log if you chose this option) that you can force push to your fork:
```
git push -f origin add_icon_for_windows
```
(assuming your fork is on the "origin" remote).

**Comment by guilhermefelipecgs** [comment]
Hello @akien-mga.
Unnecessary 'if' removed, commits merged and tested.

**Comment by akien-mga** [comment]
Nice! This looks fine to merge as far as I'm concerned.

**Comment by akien-mga** [comment]
I believe this was obsoleted by #2518, could you confirm that the editor now has a Godot icon?

**Comment by reduz** [comment]
this PR looks great, can you make it work again? I will merge it asap

**Comment by reduz** [comment]
It was not obsoleted by the other PR, they should complement nicely

**Comment by akien-mga** [comment]
> It was not obsoleted by the other PR, they should complement nicely

I do think it might have been made obsolete, see https://github.com/godotengine/godot/blob/24f3f43/platform/windows/SCsub

```
env.RES('godot_res.rc')
if env["is_mingw"]:
	common_win.append("godot_res.o")
else:
	common_win.append("godot_res.res")
```

It kind of does what this PR used to do, but for both the tools and the templates (whereas this PR only concerned the tools), and differentiates between mingw and msvc.

**Comment by reduz** [comment]
oh you are right, i didn't notice this patch added an icon. Well, if it works it works. I don't mind it also happens on release, as exported binaries will get the icon replaced anyway. Should be just like Unity then.

**Pull request closed without merging**
