### PR TITLE
Prevent recursive Main::iteration() calls

### LINKED ISSUE #24969: Crash on do `OS::set_window_size(Vector2(1024, 680))` when changing scene
**Godot version:**

3.0

**OS/device including version:**

OpenGL ES 3.0 Renderer: Intel(R) Iris(TM) Graphics 6100

**Issue description:**

I'm in GDNative cpp.
Program crash on `OS::set_window_size` when changing to another scene with `owner->get_tree()->change_scene("res://LibViewerScene.tscn");`.
The target scene's base node code exmaple:
```
void LVBase::_ready()
{
	OS::set_window_size(Vector2(1024, 680));
}
```

**Steps to reproduce:**
Given a GDNative base node of a Scene, a `Node2D` 
```
#ifndef _LSBASE_H
#define _LSBASE_H

#include <Godot.hpp>
#include <Node2D.hpp>
#include <String.hpp>

using namespace godot;

class LSBase : public GodotScript<Node2D>
{
    GODOT_CLASS(LSBase);
public:
    LSBase() { }

    void _ready()
    {
        OS::set_window_size(Vector2(640, 438));
        OS::center_window();
    }

    void _process(float delta);

    static void _register_methods() {
        register_method("_ready", &LSBase::_ready);
        register_method("_process", &LSBase::_process);
    }
};

#endif
```

And another base node of another scene:
```
#ifndef _LVBASE_H
#define _LVBASE_H

#include <Godot.hpp>
#include <Node2D.hpp>
#include <String.hpp>

#include "WilDataLibrary.h"

using namespace godot;

class LVBase : public GodotScript<Node2D>
{
    GODOT_CLASS(LVBase);
public:
    LVBase() { }

    WilDataLibrary* WilDataLib = nullptr;

	void _ready()
    {
        OS::set_window_size(Vector2(1024, 680));
    }
    void _process(float delta);


    static void _register_methods() {
        register_method("_ready", &LVBase::_ready);
        register_method("_process", &LVBase::_process);
    }
};

#endif

```
change scene from one to another like:
```
    owner->get_tree()->change_scene("res://AnotherScene.tscn");
```

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by bruvzg**
Same as patch in https://github.com/godotengine/godot/issues/24969#issuecomment-454140904

Fixes #24969, #23572 and maybe other related issues #24672, #23086. I'm unsure this is proper solution.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
What about nuking the line in ProgressDialog::task_step which causes the issue?
https://github.com/godotengine/godot/blob/4bb0080b3df28a3003bfffd6285602664a4279c9/editor/progress_dialog.cpp#L223 
Or does the line have some special things to do if called from, e.g., another thread?

**Comment by bruvzg** [comment]
> What about nuking the line in ProgressDialog::task_step which causes the issue?

It's not used only in `ProgressDialog`. This line is used to redraw UI outside of main loop:
- By `ProgressDialog`
- In some other editor parts (`make_mesh_previews`, mono build)
- Window move on Windows
- Window resize on macOS.

AFAIK it is called only from main thread. Removing this lines should fix crashes too, but will break UI redraw.

**Comment by akien-mga** [comment]
Ideally we should never call `Main::iteration()` manually IMO. Isn't it sufficient to let the next idle frame take care of redraw? Can we mark things as dirty to ensure that the next iteration will redraw what needs to be?

**Comment by bojidar-bg** [comment]
I think the problem is that the main thread might be blocked by that point, and thus waiting for next frame would lead to just waiting for the end of the task.

**Comment by akien-mga** [comment]
A priori this should no longer be needed after @reduz's 4bb0080b3df28a3003bfffd6285602664a4279c9, and the fix to the FileSystem dock in #25076. Can you confirm?

**Pull request closed without merging**
