### PR TITLE
Change OS::initialize signature to return Error (fix segfault on x11)

### PR DESCRIPTION
**Pull request by touilleMan**
See #15052 

This fix change code in all platforms, but CI doesn't check iphone and osx targets, so better be careful there...

### CODE REVIEW

**Comment by akien-mga** [comment]
Build fails on MSVC:
```
platform\windows\os_windows.cpp(1048): error C2561: 'OS_Windows::initialize': function must return a value
```

**Comment by akien-mga** [comment]
I like the change. Might be good to do the same for `Rasterizer::initialize` so that we can properly exit here: https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_gles3.cpp#L155

**Comment by touilleMan** [comment]
>  Might be good to do the same for Rasterizer::initialize so that we can properly exit here

Ok I'll add this too then

**Comment by akien-mga** [comment]
I've merged it manually for now as e315c9490 with the needed Windows return value.

We can handle Rasterizer stuff in a later PR/issue.

**Comment by touilleMan** [comment]
@akien-mga you can open a new issue with assigned to me to track the `Rasterizer::initialize` stuff if you want

**Comment by thankjura** [comment]
Segfault on linux after this patch

> No touch devices found
> OpenGL ES 3.0 Renderer: GeForce GTX 1070/PCIe/SSE2
> GLES3: max ubo light: 409
> GLES3: max ubo reflections: 455, ubo size: 144
> handle_crash: Program crashed with signal 4
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [1] /lib64/libc.so.6(+0x35fe0) [0x7f48f5724fe0] (??:0)
> [2] OS_X11::initialize(OS::VideoMode const&, int, int) (??:?)
> [3] Main::setup2(unsigned long) (??:?)
> [4] Main::setup(char const*, int, char**, bool) (??:?)
> [5] godot(main+0xaa) [0xffd66a] (??:?)
> [6] /lib64/libc.so.6(__libc_start_main+0xea) [0x7f48f570ff0a] (??:0)
> [7] godot(_start+0x2a) [0xffd50a] (??:?)
> -- END OF BACKTRACE --
> zsh: abort      godot

**Comment by touilleMan** [comment]
@thankjura What compilation options did you use ? Your stacktrace logs lack debug informations which makes it pretty hard to read :/

Beside do you have steps to reproduce this ?
Can you provide your OS and compiler name/version ?

**Comment by thankjura** [comment]
@touilleMan 
os: gentoo linux
git clone https://github.com/godotengine/godot godot-engine
cd godot-engine
scons . platform=x11 tools=yes use_llvm=yes
./bin/godot.x11.tools.64.llvm

> No touch devices found
> OpenGL ES 3.0 Renderer: GeForce GTX 1070/PCIe/SSE2
> GLES3: max ubo light: 409
> GLES3: max ubo reflections: 455, ubo size: 144
> handle_crash: Program crashed with signal 4
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [1] /lib64/libc.so.6(+0x35fe0) [0x7f082efe0fe0] (??:0)
> [2] OS_X11::initialize(OS::VideoMode const&, int, int) (/home/GrandMaster/Development/games/godot-engine/platform/x11/os_x11.cpp:519)
> [3] Main::setup2(unsigned long) (/home/GrandMaster/Development/games/godot-engine/main/main.cpp:986)
> [4] Main::setup(char const*, int, char**, bool) (/home/GrandMaster/Development/games/godot-engine/main/main.cpp:925)
> [5] ./bin/godot.x11.tools.64.llvm(main+0xaa) [0xffd41a] (/home/GrandMaster/Development/games/godot-engine/platform/x11/godot_x11.cpp:47)
> [6] /lib64/libc.so.6(__libc_start_main+0xea) [0x7f082efcbf0a] (??:0)
> [7] ./bin/godot.x11.tools.64.llvm(_start+0x2a) [0xffd2ba] (??:?)
> -- END OF BACKTRACE --
> zsh: abort      ./bin/godot.x11.tools.64.llvm
>

**Comment by touilleMan** [comment]
I'm looking at this :+1:

**Comment by oisincar** [comment]
Also getting this, seems to be fine with gcc, but fails with clang.

**Comment by thankjura** [comment]
I confitm. Build with gcc work

**Comment by akien-mga** [comment]
@bruvzg found the bug:
> clang generate UD2 instructions to indicate undefined behavior, in this case value-returning function ends without return value (OS_X11::initialize has no return OK; after last while loop)

**Comment by thankjura** [comment]
fixed in last commit 
https://github.com/godotengine/godot/commit/fab0d53f7ef94e0eaf8ad4f1dbe1f8746b0cfdd4

**Comment by touilleMan** [comment]
@akien-mga you rock :smile:

**Pull request closed without merging**
