### PR TITLE
Add a segfault handler to dump the backtrace on Windows, Linux and OS X

### PR DESCRIPTION
**Pull request by marcelofg55**
Same as #10124 but for 3.0

### CODE REVIEW

**Comment by hpvb** [comment]
This should probably default to on in SCons with an option to turn it off. Some of the issues I've fixed for people on IRC would've been so much faster if we didn't first have to teach them to use gdb.

**Comment by marcelofg55** [comment]
@hpvb Yeah, this will help reporting crashes for people that don't know gdb. Also I think it can be handy for random crashes too.
The option on SCons was discussed over #10124, @akien-mga decided it was better to have a --disable-backtrace on this instead of a SCons option, since anyways gdb has priority over this handler when debugging.

**Comment by hpvb** [comment]
This looks great, one thing: Could you add documentation for --disable-backtrace to the --help documentation in main/main.cpp?

**Comment by marcelofg55** [comment]
I've changed the --disable-backtrace to --disable-crash-handler and moved the crash handler code to its own .cpp/.h on each platform.

**Comment by hpvb** [comment]
Just some small clang-format errors now, and it seems that the iPhone platform won't build now. Maybe check to see if similar issues now exist for html5?

**Comment by marcelofg55** [comment]
Rebased and fixed that iPhone platform compile error, should be good on html5 as well.

**Pull request merged**
