### PR TITLE
Add link titles for all links in the class reference

### PR DESCRIPTION
**Pull request by Calinou**
This makes them display in a nicer way in the editor help. (The title will display instead of the full URL.)

**Note:** Technically cherry-pickable to the `3.2` branch, but probably not worth doing so in practice due to the effort required.

### CODE REVIEW

**Review by NathanLovato — APPROVED** [review]
Seems you used some regex to write them? I went through all titles, they are all good.

I tried to checkout to your PR and build to test the result, but can't at the moment (build error). From the markup and text it looks good to merge though.

**Comment by Calinou** [comment]
> Seems you used some regex to write them? I went through all titles, they are all good.

I wrote them by hand based on the page titles (with occasional modifications when relevant).

**Comment by NathanLovato** [comment]
You've got to use sed for things like these! Would've saved you some busywork. In any case it's looking good.

**Comment by Calinou** [comment]
> You've got to use sed for things like these! Would've saved you some busywork. 

Well, as always, this chart applies :stuck_out_tongue:

[](https://xkcd.com/1205/)

**Comment by NathanLovato** [comment]
Yes, it's all good.

**Comment by akien-mga** [comment]
Needs a rebase.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
