### PR TITLE
Clarify that the `Mesh.ARRAY_NORMAL` array will normalize its contents internally

### LINKED ISSUE #93693: Normal values gets changed even when using `skip_vertex_transform` render_mode
### Tested versions

4.3.beta2

### System information

Godot v4.3.beta2 - Windows 10.0.22631 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 31.0.101.2125) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

When creating an ArrayMesh with custom values in the normal channel, these values get changed even with the ```skip_vertex_transform``` render_mode. This happens with all three renderers.

image

### Steps to reproduce

Create two array meshes
one with uv's in the color channel that should appear correct.
and one with uv's in the normal channel that should appear distorted.

The bug reproduction scene below contains this setup.

### Minimal reproduction project (MRP)

Here is the scene reproducing the bug with all resources built-in.

[BugRepro.zip](https://github.com/user-attachments/files/16026222/BugRepro.zip)

### PR DESCRIPTION
**Pull request by MikeXYZW**
Added a note to the ARRAY_NORMAL's description in accordance with issue #93693 .
Please double-check my phrasing. Thanks in advance.

*Bugsquad edit:*
- Fixes #93693.

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please update the PR title to reflect what is actually done

**Comment by MikhailY0U** [comment]
Sure thing

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by MikhailY0U** [comment]
Yay! Thank you :)

**Pull request merged**
