### PR TITLE
AStar: implementation of get_point_connections

### LINKED ISSUE #12567: AStar: Get a list of connected points
Please add the ability to list points that were connected with the current point.
`[p_index, ...] <- get_point_conections(p_index)`
For example:
```
var astar = AStar.new()
astar.add_point(1, Vector3(30, 30, 3))
astar.add_point(2, Vector3(23, 30, 0))
astar.add_point(3, Vector3(41, 32, 3))

astar.connect_points(1, 2)
astar.connect_points(1, 3)

print (astar.get_point_connections( 1 ))
# [2, 3]
```

### PR DESCRIPTION
**Pull request by lmcdd**
Add set_point_connections methods to AStar.

Fixes #12567.

### CODE REVIEW

**Comment by groud** [comment]
Your PR does not pass the static checks of the continuous integration. Please **apply** `clang-format` **to the modified files** and **amend** your commit :)
See [here](http://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html#manual-usage).

**Comment by DmDerbin** [comment]
@groud, 
Сorrected.

**Comment by Noshyaar** [comment]
Would you mind adding the documentation for the method?

https://github.com/godotengine/godot/blob/master/doc/classes/AStar.xml

**Comment by DmDerbin** [comment]
@Noshyaar,
added.

**Comment by Noshyaar** [comment]
Thank you for contributing!

**Pull request merged**
