### PR TITLE
Toward 3.1 - physics fixes

### LINKED ISSUE #20438: RayShape fails on the seems when "active_soft_world" is enabled.
**Godot version:**

f8e8ac2c664a12f3af2b9bb545da193d86c75503

**Issue description:**

When a rigidbody with a rayshape falls or move on a seem of a staticobject the collision fails and the rayshape pass through the static object.

**Steps to reproduce:**
Use the minimal project to test.
By disabling the physics/3d/active_soft_world the normal behaviour returns.
In the minimal project is enabled, to present the problem.

**Minimal reproduction project:**

[rayshape.zip](https://github.com/godotengine/godot/files/2226942/rayshape.zip)

### LINKED ISSUE #21212: PhysicsDirectSpaceState.cast_motion() has different behaviour between Bullet and GodotPhysics
**Godot version:**
3.1-dev faa49c1

**OS/device including version:**
Windows 10 x64

**Issue description:**
`PhysicsDirectSpaceState.cast_motion()` is used to check how far a shape can travel to a point both with and without triggering a collision. It returns an array containing two values.

With GodotPhysics:
* The first value is how far it can move with no collision, while the second is how far it needs to move for a collision to be detected. The values are usually very slightly different.
* If no collision is detected, both values will be 1.
* If no movement can occur (a collision occurs without any movement), the returned array will be empty.

However, with Bullet:
* The first and second values are always identical, both representing how far it needs to move for a collision to be detected.
* If no collision is detected, the returned array will be empty.
* If no movement can occur, both values will be 0.

The documentation only reflects the GodotPhysics behaviour, and I haven't seen any dscussion regarding this, so the discrepancy seems like a bug...

**Minimal reproduction project:**
[cast motion test.zip](https://github.com/godotengine/godot/files/2301492/cast.motion.test.zip)
Change between "Bullet" and "GodotPhysics" in the Project Settings (under `physics` > `3d`) to observe the differences in behaviour. Move around with the arrow keys and press Space to perform a new query. The results will be displayed in a Label.

@AndreaCatania

### LINKED ISSUE #22086: PhysicalBoneEditor is not properly freed
**Godot version:**
Master branch, 9b97c74f

**OS/device including version:**
Mageia 6 x86_64.

**Issue description:**
When closing the editor, the following warning is printed (in verbose mode):
```
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2081.
Leaked instance: PhysicalBoneEditor:15428
Orphan StringName: PhysicalBoneEditor
StringName: 1 unclaimed string names at exit
```

Might be related to https://github.com/godotengine/godot/blob/9eb4d4ab2d65c7e29b07308c7f18f40b6530f5a2/editor/plugins/physical_bone_plugin.cpp#L73

CC @AndreaCatania 

**Steps to reproduce:**
- Open any project in the editor, in verbose mode
- Close it

**Minimal reproduction project:**
Not necessary.

### LINKED ISSUE #22249: Low RayShape precission
**Godot version:**
197a3b292487b57f5de4ae49ea2d61f2a6da7c7a

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
Accuracy of the RayShape in current main (3.1) is very low, most of objects in my game are floating above the ground or are pushed into the ground. To tell truth already in 3.0 accuracy of RayShape was significantly lower than in 2.1, but now the problem is much worse. 

The same scene in 3 scenarios:
_current main (bullet):_
zrzut ekranu z 2018-09-19 14-58-37

_stable 3.0.6 (bullet):_
zrzut ekranu z 2018-09-19 14-58-30

_stable 3.0.6  (godot physics engine):_
zrzut ekranu z 2018-09-19 15-01-14

**Steps to reproduce:**
Short version:
1. Download sample project.
2. Run `ConcaveCollisionShape.tscn` scene

Long version:
1. Create new scene
2. Create static body and its representation (in my sample/reproduction I'm using ConcavePolygonShape imported from Blender)
3. Create RigidBody with representation in character mode (above the static body)
4. Attach Ray Collision shape to the RigidBody
5. Run the simulation and observe the distance between rigid body and static body

**Minimal reproduction project:**
[RayShapePrecission.zip](https://github.com/godotengine/godot/files/2397160/RayShapePrecission.zip)

### LINKED ISSUE #22281: Bodies with RayShape are sliding off the slopes
**Godot version:**
197a3b292487b57f5de4ae49ea2d61f2a6da7c7a

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
Rigid bodies that are using a Ray collision shape are sliding from the slopes in current main. This problem was introduced between 3.0 and current main (it's working fine in 3.0).

_Current (bad)_
rayshape_slopes_bug

_Godot physic Engine or 3.0 (good)_
rayshape_slopes_right

**Steps to reproduce:**

_Short version_
1. Download sample project 
2. Run RayShapeSlopes.tscn 

_Long version:_
1. Create new scene
2. Create static body with a slope (and its visual representation - in my sample/reproduction I'm using ConcavePolygonShape imported from Blender)
3. Create RigidBody with representation in character mode 
4. Attach Ray Collision shape to the RigidBody
5. Put the RigidBody above the slope of the StaticBody
6. Run the simulation and observe that the body is sliding off the slope

**Minimal reproduction project:**
[RayShapeSlopes.zip](https://github.com/godotengine/godot/files/2401031/RayShapeSlopes.zip)

### LINKED ISSUE #22283: Bodies with RayShape are unable to travel through obstacles
**Godot version:**
197a3b292487b57f5de4ae49ea2d61f2a6da7c7a

**OS/device including version:**
Ubuntu 18.04, GTX1060

**Issue description:**
Rigid bodies that are using a Ray collision shape are unable to travel through small obstacles. This problem was introduced between 3.0 and current main (it's working fine in 3.0).

_Current (Bad)_
rayshape_edges_bug

_Godot physics engine (good)_
rayshape_edges_right

**Steps to reproduce:**
Short version:
1. Download sample project.
2. Open RayShapeEdges.tscn
3. Run it
4. Press left arrow key on the keyboard to push the body towards obstacle
5. Observe that the body is unable to move on the obstacle

Long version:
1. Create new scene
2. Create static body with a box shaped obstacle (and its visual representation - in my sample/reproduction I'm using ConcavePolygonShape imported from Blender)
3. Create RigidBody with representation in character mode
4. Attach Ray Collision shape to the RigidBody
5. Ensure collision shape is longer/higher than the obstacle height
6. Put the RigidBody near the obstacle 
7. Add a small script that will apply force to Rigid body towards the obstacle
8. Run the simulation and observe that the body is unable to move on the obstacle

**Minimal reproduction project:**
[RayShapeEdgeObstacles.zip](https://github.com/godotengine/godot/files/2401102/RayShapeEdgeObstacles.zip)

### PR DESCRIPTION
**Pull request by AndreaCatania**
fixes #22283
fixes #22249
fixes #22281
fixes #20438
fixes #21212
fixes #22086

### CODE REVIEW

**Comment by AndreaCatania** [comment]
@akien-mga can be merged

**Comment by mhilbrunner** [comment]
Yay, lots of fixes - M-M-Monster Fix? :D

**Comment by AndreaCatania** [comment]
Hehe yes, this period is a mess for me so I use spare time to fix things :D

**Comment by kubecz3k** [comment]
@AndreaCatania Thank you for the fixes!

**Pull request merged**
