### PR TITLE
Image trilinear scaling + Optimization

### PR DESCRIPTION
**Pull request by RandomShaper**
- First commit adds `Image.INTERPOLATE_TRILINEAR` mode for scaling.
- Second commit adds a bit of `restrict` pointer magic to aid the compiler in optimizing the code at those assembler-like-code routines.

This code is donated by [AdPodnet](https://www.adpodnet.com/).

### CODE REVIEW

**Comment by RandomShaper** [comment]
Here's a little demo project on which you can see the difference in quality (trilinear-filter-scaled images are smoother, with no aliasing artifacts):
[trilinear_demo.zip](https://github.com/godotengine/godot/files/2064290/trilinear_demo.zip)

**Comment by Calinou** [comment]
I tested this locally with the attached demo, it seems to work fine.

**Comment by mhilbrunner** [comment]
@hpvb can you look at the use of the `__restrict` keyword here? :)

**Comment by RandomShaper** [comment]
@hpvbv, mind you having a look at this for cherry-picking into 3.0.6?

It would be very convenient for AdPodnet (the donors of the code) to have this in the next official release.

**Comment by hpvb** [comment]
I'll look at it for 3.0.6

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
