### PR TITLE
adds a property to disable virtual keyboard for LineEdit

### PR DESCRIPTION
**Pull request by AlexHolly**

### CODE REVIEW

**Comment by akien-mga** [comment]
Can you describe the use case?

**Comment by Zireael07** [comment]
Use case here: #32680 (TLDR: No input on Android web browsers currently)

**Comment by akien-mga** [comment]
> Use case here: #32680 (TLDR: No input on Android web browsers currently, this would allow me to play the game on mobile)

That's not what this PR does. It adds a property to *disable* virtual keyboard.

**Comment by Zireael07** [comment]
In that case, the PR is misnamed (**Adds** optional virtual keyboard)

**Comment by AlexHolly** [comment]
In my case the LineEdit is used to remap a key with an external keyboard, clicking the field is always showing the virtual keyboard which hides the LineEdit. 

It could also be used to have a custom virtual keyboard.

**Comment by akien-mga** [comment]
CC @pouleyKetchoupp @MadEqua @SkyLucilfer who have been working with LineEdit virtual keyboard on Android lately.

**Comment by pouleyKetchoupp** [comment]
Seems fine to me. Afaik there's currently no way to make a custom virtual keyboard on mobile while using some of the functionalities of `LineEdit` so I think it's a desired feature.

**Comment by MadEqua** [comment]
It does seem like a useful feature. Also the code looks OK, pretty straightforward.

**Pull request closed without merging**
