### PR TITLE
Implement animation clips for any animation name and multiple animations

### PR DESCRIPTION
**Pull request by Juankz**
Fixes #25599

The clips method only worked if the imported model had one animation named "default".

This commit makes it work with any animation name and also implements it for any number of default animations the model imports, eg. facial animations and body animations each on their own timeline but must be split at the same frames (which is my use case).

### CODE REVIEW

**Comment by fire** [comment]
I'll close my pr for this if there's no comments. https://github.com/godotengine/godot/pull/28362

**Comment by fire** [comment]
Your commit does a lot more things though. I wonder...

**Comment by Juankz** [comment]
@fire All I did was:
1. Get a list of animations in AnimationPlayer. Those I named default_animations
2. Iterate over said list to create the clips. No change in that logic except for
2.1 Make animation name = default_animation_name + clip_name
3. Remove the default_animations

I guess git diff made it a little harder to see because all the pre-existing logic is now inside a loop and it counts the extra tab as a change.

**Comment by Juankz** [comment]
Removed some code duplication

**Comment by fire** [comment]
Do you have a test project that makes it easy to verify that it works?

**Comment by Juankz** [comment]
Sure
[ClipsImportTest.zip](https://github.com/godotengine/godot/files/4277057/ClipsImportTest.zip)

**Comment by Juankz** [comment]
@akien-mga How about this PR for the next 3.2 launch

**Comment by akien-mga** [comment]
PRs should be made against the `master` branch, not `3.2`. I'm the one to cherrypick merged and tested changes from `master` to stable branches, when relevant.

**Comment by atari83** [comment]
> Fixes #25599
> 
> The clips method only worked if the imported model had one animation named "default".
> 
> This commit makes it work with any animation name and also implements it for any number of default animations the model imports, eg. facial animations and body animations each on their own timeline but must be split at the same frames (which is my use case).

I faced same issue, Is it going to be fixed any soon in release/maintenance version ?

**Comment by Juankz** [comment]
I will try to port this to master, but I think I'll break it in two parts, one to clip one animation with any animation name and other with clipping mutiple animations, I believe the last one should go to feature proposal first and see if its a requested feature

**Comment by noidexe** [comment]
@Juankz wow man thanks for mentioning that the animation needed to be called "default". I managed to clip my animations with the current stable and can let the animator keep his workflow. 
I'll open an issue in the docs repo since I think it should be mentioned till this lands on stable.

**Comment by Juankz** [comment]
Close in favor of #40274

**Pull request closed without merging**
