### PR TITLE
Allow TileMap physics/navigation to still work when hidden

### LINKED ISSUE #83499: Tilemap collision is disabled when not visible
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

Windows 11 22H2

### Issue description

Expected: 
Tilemap still has collision when invisible.
This is how it works in 4.1.2

Actual:
Tilemap has no collision if set visible to false.

### Steps to reproduce

1. Add a tilemap to your level
2. Add a tileset and add collision
3. Add something that reacts upon the collison layer of said tilemap.
4. Set the tilemap to be invisible (via code)
5. See the "something" noclips at the invisible tilemap

### Minimal reproduction project

[Tilemap Collision MRP.zip](https://github.com/godotengine/godot/files/12929391/Tilemap.Collision.MRP.zip)

### PR DESCRIPTION
**Pull request by groud**
Fixes https://github.com/godotengine/godot/issues/83499

### CODE REVIEW

**Comment by ChloePrime** [comment]
What about navigation?

**Comment by groud** [comment]
> Should we apply this to navigation too?

I don't know. I didn't check if navigation nodes were disabled when hidden. 
But it should be easy to implement too.

**Comment by KoBeWi** [comment]
It has the same condition, so likely should be changed too:
https://github.com/godotengine/godot/blob/f8818f85e6c43cdf1277e8ae85eba19ca0a003b0/scene/2d/tile_map.cpp#L905

**Review by akien-mga — APPROVED** [review]
Seems fine, just waiting to see if this should be done for navigation too.

**Comment by AThousandShips** [comment]
Can't find anything in the `NavigationRegion2D` code that is controlled by visibility in the tree, but haven't tested the behavior

**Comment by groud** [comment]
Done, I've just pushed an update to make navigation work too.

**Comment by smix8** [comment]
Yes navigation still works when not visible. Visibility has no use in navigation apart from debug rendering. Most navigation related nodes have a dedicated `enabled` property to enable/disable them.

As mentioned in dev chat I also wonder why it should be even any other way, visibility has clearly to do with visible things, aka rendering / occlusion. It has no bearing on logic and imo should not.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
