### PR TITLE
Drop RtAudio driver on Windows

### LINKED ISSUE #25503: Godot crashes immediately when opening a project with "RtAudio-DirectSound" set as audio driver
**Godot version:**
3.1 beta 3 (though it started to crash around 3.1 alpha 4 too I think)

**OS/device including version:**
Windows 10

**Issue description:**
Check minimal project. Engine crashes without any warning messages.
My game with "RtAudio-DirectSound" set as audio driver started crashing since 3.1 alpha 4 I think, but I'm not sure if that was the initial cause back then. I've just discovered that audio driver is the cause in 3.1 beta 3.

**Steps to reproduce:**
Start new project. Set audio driver to "RtAudio-DirectSound" in project settings. Save and try to open the project afterwards.

**Minimal reproduction project:**
[RtAudio-DirectSound crash.zip](https://github.com/godotengine/godot/files/2816285/RtAudio-DirectSound.crash.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
We've been defaulting to WASAPI since 3.0 and it's superior to RtAudio
in all aspects.

Obsoletes and closes #25503.

---

As discussed with @marcelofg55, the only reason to keep RtAudio around would be if we decide to implement #24274, but this feature request has not been approved yet and we're not even exposing any RtAudio backend on Linux, so it's a stretch anyway.

I leave it up to @marcelofg55 to decide if it's the right move or not.

It does break compat a bit for projects that would have selected it as the audio backend, so it should be documented appropriately in the changelog if merged (cc @Calinou).

### CODE REVIEW

**Comment by akien-mga** [comment]
@marcelofg55 BTW, I've noticed that `WINMIDI_ENABLED` is only defined when compiling with MSVC, is that intended?

**Review by marcelofg55 — APPROVED** [review]

**Comment by akien-mga** [comment]
No idea why AppVeyor failed, will have to dig a bit.

**Comment by marcelofg55** [comment]
Sounds fine to me. Regarding #24274 I think that if we ever add a Jack driver it should be a proper driver like the PulseAudio or ALSA ones, and not a RtAudio-Jack like one.

About the `WINMIDI_ENABLED`, I think I just missed it on the MinGW declarations, I usually compile with MSVC myself.

**Comment by akien-mga** [comment]
> Regarding #24274 I think that if we ever add a Jack driver it should be a proper driver like the PulseAudio or ALSA ones, and not a RtAudio-Jack like one.

Agreed. I'll edit that request accordingly.

> About the `WINMIDI_ENABLED`, I think I just missed it on the MinGW declarations, I usually compile with MSVC myself.

Thanks, I'll add it.

**Comment by Calinou** [comment]
@akien-mga I updated the changelog :slightly_smiling_face:

**Pull request merged**
