### PR TITLE
Remove ContextGL

### PR DESCRIPTION
**Pull request by shartte**
The abstraction is unused, and each platform only uses the concrete subclass of it.
The singleton in GLContext is also currently unused.
This makes it easier to understand that ContextGL can actually not be relied upon by platform independent code since not all platforms have one.

### CODE REVIEW

**Comment by fire** [comment]
This makes Vulkan implementation easier.

**Comment by fire** [comment]
Tested on Windows and appears to work. Not tested on Linux, but should be...

**Comment by hpvb** [comment]
There's a lot of code duplication between the various os specific contextgl's that I'd like to address. Probably by starting to actually use the contextgl abstraction. I don't think it should be removed but rather we should start to actually use it.

**Comment by hpvb** [comment]
After some discussion it seems that deleting it now and adding a new more suitable abstraction later is better. 

+1

**Comment by reduz** [comment]
this is good

**Comment by akien-mga** [comment]
Needs a rebase, then I'll merge it.

**Comment by shartte** [comment]
Will do

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
