### PR TITLE
[X11] Use motion event button state instead of async state.

### LINKED ISSUE #94077: Code Editor — when dragging the mini-map it also selects code.
### Tested versions

v4.3.beta.custom_build [6a13fdcae]

### System information

Godot v4.3.beta (6a13fdcae) - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.183.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

When you use the mini-map in the code editor, dragging it up/down will often start selecting the code instead.

image

### Steps to reproduce

Fiddle about in the code editor.

### Minimal reproduction project (MRP)

NA

### LINKED ISSUE #94211: Selecting text with drag sometimes instantly select all text to previous caret position
### Tested versions

Godot v4.3.beta2
Godot v4.3.beta3 

### System information

Godot v4.3.beta3 - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - nvidia; 555.58.02

### Issue description

Selecting text with drag sometimes instantly select all text to previous caret position.

First thought my mouse button was going bad, but don't seem to happen in 4.2.2 

Also don't think I have seen this on windows.

Could it be related to?: https://github.com/godotengine/godot/issues/94077

### Steps to reproduce

Place your caret somewhere in the code.
Then try to select some text at another place.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Should fix https://github.com/godotengine/godot/issues/94211 (I can't consistently reproduce the issue).

*Bugsquad edit:*
- Should also fix #94077

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @Giganzo @kitbdev if you can reproduce the issue and confirm the fix.

**Comment by Giganzo** [comment]
> Can reproduce the issue and confirm the fix.

Yes this looks to fix the issue. :) 
Thanks!

**Review by akien-mga — APPROVED** [review]

**Comment by kitbdev** [comment]
Can't test but code looks good.
https://github.com/godotengine/godot/issues/94077 should also be fixed, since it has the same cause.

**Comment by akien-mga** [comment]
Thanks!

**Comment by donn-xx** [comment]
Compiling now to test! Magic. Seems much better! Thank you!

**Pull request merged**
