### PR TITLE
Make Create New Node dialog resizable and burninate old dialog

### PR DESCRIPTION
**Pull request by RayKoopa**
- "Create New (Node)" dialog is now resizable and stores its bounds (like the other dialogs I previously did). Renamed the `popup` method to be like in the other dialogs (distuingishable from the default `popup`).
- Trashed the commented out code of the old Create New dialog as the new one works fine since many months now.

### CODE REVIEW

**Review by 27thLiz — APPROVED** [review]

**Comment by akien-mga** [comment]
> In case you wonder about the weird Line 1 differences, some changed files weren't stored as UTF-8 previously. According to .editorconfig, my IDE stored it as UTF-8 now.

Hm I'll have to check it, if it changed line 1 it sounds like it added a byte-order mark, and I don't think we need those.

**Review by akien-mga — CHANGES_REQUESTED** [review]
Confirmed that your IDE added a BOM to the modified files. Please remove it, no other file in the project uses BOMs and it's not recommended to use them in such a context.

**Comment by RayKoopa** [comment]
I hope the other files are not stored in ANSI yet, cuz I'd get annoyed of removing the BOM in a hex editor lol.

**Comment by RayKoopa** [comment]
They should be all gone now.

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
