### PR TITLE
Unnecessary reassignments

### PR DESCRIPTION
**Pull request by Muller-Castro**
Sorry, I'm very newbie at GitHub yet... I hope this fix the double commits ;) @aaronfranke

### CODE REVIEW

**Comment by aaronfranke** [comment]
@Muller-Castro Your PR is good now, but in the future you should squash and force-push, rather than opening a 2nd PR. Also, don't worry about breaking things, the absolute worst case scenario is that you break your own copy (so make backups if you aren't sure!).

**Comment by KoBeWi** [comment]
> the absolute worst case scenario is that you break your own copy

The worst scenario is when you try to resolve conflicts and accidentally include lots of unnecessary commits, which results in your PR suddenly having 80k+ lines of diff and 14 people being automatically requested for review :/

**Comment by akien-mga** [comment]
> Your PR is good now, but in the future you should squash and force-push, rather than opening a 2nd PR.

I'd still ask you to amend and force push here, as the commit log is not descriptive at all. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
