### PR TITLE
Mono: Make Godot provide its own WASM m2n trampolines

### LINKED ISSUE #36858: GD.Seed C# Black Screen HTML5
**Godot version:**
Mono 3.2, 3.2.1 rc, 3.2.2 rc (I tested it with all of them as they were getting released to make sure it's not fixed) 

**OS/device including version:**
Linux (pop-os), HTML5 in Google Chrome

**Issue description:**
C#/F# GD.Seed(1UL);  (same for GD.Seed(1);) 
produce black screen of death in HTML build.
The black screen does not get produced when doing a Linux build. 
Only when it is in the browser.
Moreover, the issues does not occur if you call seed from GDScript.

**Steps to reproduce:**
1. Create scene
2. Add C# script to the scene
3. Inside ready call GD.Seed(1); or GD.Seed(1UL);
4. 
Test in Browser => Black Screen
Test Normally => Works fine
5. (Optional) Try same thing with GDScript => works fine both in browser and normally 
Project zip at the bottom after pics.

**Minimal reproduction project:**
image
image
[seed_bug.zip](https://github.com/godotengine/godot/files/4298993/seed_bug.zip)

### PR DESCRIPTION
**Pull request by neikeq**
This depends on a custom Mono patch from this commit: godotengine/godot-mono-builds@0e312939bd0dc4b807cc15dbe76a7b65456ab928

Also fixes #36858

### CODE REVIEW

**Comment by neikeq** [comment]
Not sure whether to label this `topic:html5` as this benefits all platforms, not only wasm, because we no longer need to pass long, float and double by pointer in internal calls.

**Comment by neikeq** [comment]
@akien-mga Is this file format static check something apart from clang format? Can I add it as a commit hook?

**Comment by akien-mga** [comment]
It's separate because it parses the whole codebase and is extremely slow. It should be changed to parse only changed files like the existing precommit hooks, and made compatible with macOS utils.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
