### PR TITLE
Added tabs with short and full descriptions to node creation dialog.

### PR DESCRIPTION
**Pull request by Chaosus**
I recreated #18437 (Im bit confused with git)..
@Noshyaar now looks good ?

image

Minimal size

image

### CODE REVIEW

**Comment by groud** [comment]
To me that's too much, it bloats a lot the interface for something that's going to be useful only for beginners. A simple right click entry (or a button somewhere on the bottom) with a link to the documentation should be enough, in the common use case you don't need all this information. 
I like better the way it is now, the brief description at the bottom is enough.

**Comment by Chaosus** [comment]
> A simple right click entry (or a button somewhere on the bottom) with a link to the documentation should be enough

The problem with this approach, that if you click on that button the creation window will close, and you need close doc first, and than call this dialog again

**Comment by groud** [comment]
It's not really a problem, we can add the node to the "recently used" list. Or maybe add a default filter for the next time you open the add node window. There are plenty of solutions to this.

**Comment by Noshyaar** [comment]
It looks okay for me. Also kinda agree with Groud that the info is mostly useless for experienced devs. I still think that without this PR, the space on the right has no use. I think we can put something that is useful for both beginners and experienced devs. For example, methods/properties/signals list etc.

This still needs to be discussed a lot as users use this dialog very often. Let's hear some more opinions before implementing so there's no wasted effort. :)

**Comment by Zylann** [comment]
What about a tooltip with the short description?

**Comment by Noshyaar** [comment]
>What about a tooltip with the short description?

It's already there? Or did I misunderstand?

**Comment by Zylann** [comment]
Ah right, it's already there indeed.

**Comment by groud** [comment]
Speaking for myself, I would just keep the dialog box as minimalistic as possible. Even with the current design, it already feels bloated. I personally ever use the "favorite" nodes (which is something that makes no sense in my opinion) and the "recently used" nodes list feel useless to me too. There are not a lot of reason why you would like to use the same node again. And when you do, it's usually because you want have several chidren of a same node, but in that case duplicating is simpler.

> What about a tooltip with the short description?

I think it's already there, but the description is also written at the bottom of the node.

Honestly, I believe a better UX would just be to make this a lot simpler, with only the list of nodes and a search field. More or less how unity does it.

**Comment by mhilbrunner** [comment]
>Honestly, I believe a better UX would just be to make this a lot simpler, with only the list of nodes and a search field. 

I agree. Also, selecting a node in the list should expand its children automatically.

**Comment by mhilbrunner** [comment]
Also, Unity only nests them one layer deep: Category, then a list. No children. No multiple subcategories to expand.

Compare Unity:
unity

Godot:
godot

**Comment by reduz** [comment]
My take on this would be adding a read more clickable link at the end of the description:
image

**Comment by Chaosus** [comment]
Ok, I close this then.. maybe in other day I do as reduz said

**Pull request closed without merging**
