### PR TITLE
Enable the `copy_mono_root` SCons option by default

### LINKED ISSUE #41652: The assembly mscorlib.dll was not found or could not be loaded
**Godot version:**
Godot Engine v3.2.3.rc4.mono.custom_build.fad1feb3a

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
Build godot with scons and run it normally cause it to close immediately with this log

```
The assembly mscorlib.dll was not found or could not be loaded.
It should have been installed in the `C:\Users\Thaina\Documents\Git\godot\bin/GodotSharp/Mono/lib\mono\4.5\mscorlib.dll' directory.
```

I suspect that the problem came from `scons` build creating this file

`godot\bin\GodotSharp\Mono\lib\mono\v4.0\MSBuild.exe`

When this file exist, maybe because it has `Mono` folder structure, it then try to find `mscorlib.dll` from here (when actually my Mono folder exist in `C:\Program Files\Mono`)

Deleting that generated folder than let me open godot IDE normally

**Steps to reproduce:**
- using vscode, pull source code from branch 3.2
- Using vscode terminal to build godot from source for mono as state in this (https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html)
  - I use command `scons tools=yes module_mono_enabled=yes mono_glue=no` without specified platform, let it just assume to be windows
- Then just run `bin\\godot.windows.tools.64.mono.exe`

I think this problem never occur to me around last week so it seem a new version around less than 5 days cause it

### PR DESCRIPTION
**Pull request by Calinou**
This closes #41652.

### CODE REVIEW

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by akien-mga** [comment]
I don't get why the `black` format check passed in the PR but not once merged...

**Comment by akien-mga** [comment]
Actually there was no CI build for this PR :|

**Pull request merged**
