### PR TITLE
thorvg: Update to 0.10.7

### LINKED ISSUE #81618: Build failing on MSVC 2017
### Godot version

Applicable since #80095

### System information

MSVC 2017

### Issue description

The use of `min` and `max` macros breaks due to them being explicitly undefined (to prevent collision with Godot's `min` and `max` templates. This causes errors like this:
```
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(366): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(367): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(368): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(375): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(376): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(377): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(405): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(406): error C3861: 'min': identifier not found
c:\docs\programs\godotengine\thirdparty\thorvg\src\lib\sw_engine\tvgSwCommon.h(407): error C3861: 'min': identifier not found
```

Only this one file (`thirdparty/thorvg/src/lib/sw_engine/tvgSwCommon.h`) is affected. Manually defining `min` and `max` functions for this file makes the problem go away.

### Steps to reproduce

Get MSVC 2017
Build Godot

### Minimal reproduction project

Not applicable

### PR DESCRIPTION
**Pull request by akien-mga**
Release notes:

- https://github.com/thorvg/thorvg/releases/tag/v0.10.7
- https://github.com/thorvg/thorvg/releases/tag/v0.10.6
- https://github.com/thorvg/thorvg/releases/tag/v0.10.5
- https://github.com/thorvg/thorvg/releases/tag/v0.10.4
- https://github.com/thorvg/thorvg/releases/tag/v0.10.3
- https://github.com/thorvg/thorvg/releases/tag/v0.10.2
- https://github.com/thorvg/thorvg/releases/tag/v0.10.1

Add patch to fix build on VS 2017 with NOMINMAX.
    
Fixes #81618.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @capnm

**Comment by capnm** [comment]
@akien-mga  Could you please add the fix to v0.10.0?
The other minor 0.10.x releases have deadlock (already fixed in main).

Thanks!

**Comment by capnm** [comment]
[ThorVG v0.10.7](https://github.com/thorvg/thorvg/releases/tag/v0.10.7):

+ [Renderer] Fixed a regression deadlock issue related to thread scheduling. https://github.com/thorvg/thorvg/issues/1636
+ [Portability] Fixed compilation issues related to min() and max() for VS2017. https://github.com/thorvg/thorvg/issues/1661
...

**Comment by SlugFiller** [comment]
So.... 0.10.7 PR and merge when? Because it's really hard to make/maintain my own PRs on top of a master that doesn't compile.

**Comment by akien-mga** [comment]
Here's 0.10.7.

**Comment by capnm** [comment]
> So.... 0.10.7 PR and merge when? Because it's really hard to make/maintain my own PRs on top of a master that doesn't compile.
> Here's 0.10.7.

@SlugFiller  could you check if it fixes your issue?
I am currently trying  to help by making a 0.11 release PR 
https://github.com/thorvg/thorvg/pull/1680#issuecomment-1736973542
and don't know what @akien-mga  decides to do with this PR.

**Comment by akien-mga** [comment]
We can merge that one if it's fine, or wait for 0.11 if it's imminent, I'm fine either way.

**Comment by SlugFiller** [comment]
Confirmed the editor builds if I cherry pick this. (And combine with a fix for #82322, but that's a different topic)

**Pull request merged**
