### PR TITLE
Previous value of time_left is added to wait_time before assigning to time_left

### LINKED ISSUE #7530: A repeating Timer accumulates a precision error over time.
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 2.2 alpha

**Issue description** (what happened, and what was expected):
A repeating Timer will take longer than expected to execute x number of times. For example a timer with a wait time of 0.125 should run 80 times in 10 seconds, but for me it takes about 10.5 seconds. And 480 times should take 60 seconds, however it takes about 64 seconds. This happens with both idle and fixed time.

**Link to minimal example project** (optional but very welcome):
A script to illustrate this:
```GDScript
extends Timer

var start_time
var end_time

var count = 0
var count_max = 80

func _ready():
	connect("timeout", self, "_on_timeout")
	set_wait_time(0.125)
	set_one_shot(false)
	set_timer_process_mode(TIMER_PROCESS_FIXED)
	start()
	start_time = OS.get_ticks_msec()

func _on_timeout():
	count += 1
	if count >= count_max:
		stop()
		end_time = OS.get_ticks_msec()
		print("time to complete: ", end_time - start_time)
```

### PR DESCRIPTION
**Pull request by nikhilshagri**
Fixes #7530
This is my first contribution to the project, so I'm not sure whether I understood the issue correctly or not.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by bojidar-bg** [comment]
Actually, you might have done `time_left += wait_time`, but already looks good as-is.

**Comment by Hinsbart** [comment]
What about _internal_process? Is this only needed for fixed_process? https://github.com/cynicaldevil/godot/blob/ea4fbee8f2778bc864cb930c69016cb175812da7/scene/main/timer.cpp#L54

**Comment by akien-mga** [comment]
> What about _internal_process? Is this only needed for fixed_process? https://github.com/cynicaldevil/godot/blob/ea4fbee8f2778bc864cb930c69016cb175812da7/scene/main/timer.cpp#L54

It should be done for both IMO.

**Comment by akien-mga** [comment]
Done with 5b5a825.

**Pull request merged**
