### PR TITLE
[iOS export] Add export options for performance capabilities and min. iOS version.

### PR DESCRIPTION
**Pull request by bruvzg**
Implements https://github.com/godotengine/godot-proposals/issues/8289

### CODE REVIEW

**Comment by lostminds** [comment]
Also implements https://github.com/godotengine/godot-proposals/issues/7134 with the addition of the iOS version. 

As for the app category property in that proposal I'm not sure how much work that would be, and I'm actually not sure how it's used now since you can also set the category in the AppStore connect interface. So maybe not a priority unless you feel differently.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
