### PR TITLE
Optional camera iOS

### PR DESCRIPTION
**Pull request by ealataur**
Made camera iOS capture optional because a lot of games not used camera but application will request grant access without really uses

### CODE REVIEW

**Comment by ealataur** [comment]
This is very important!
If user decline an access and your build without arkit or real use a camera then app is crashed

**Comment by bruvzg** [comment]
You have all changes for the quit request and camera build option in both this PR and #33401.

**Comment by aaronfranke** [comment]
@ealataur Is this still desired? If so, it needs to be rebased on the latest master branch, and squashed.

What you did above is merging, and it's not good to have merges inside of a PR. See this article for information on how to rebase: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by aaronfranke** [comment]
Closing as abandoned by the author. If this is still desired, feel free to open a new PR based on the latest master branch.

**Pull request closed without merging**
