### PR TITLE
Proposal for modified Polygon2D editor controls

### PR DESCRIPTION
**Pull request by ghost**
This is probably highly controversial, still I hope this might be useful in some way.

This is an experiment that tries to add editing to Polygon2d that should be more familiar to people coming from Illustrator or Affinity Designer. Changes are: selectable nodes, deleting nodes by pressing the "del" key (deletes currently selected node or the last node while creating the polygon), adding nodes by simply clicking into the edge. Right click to delete still works.

Demo gifs:

create

editing

### CODE REVIEW

**Comment by akien-mga** [comment]
@poke1024 BTW, unrelated to the feature here but you apparently author your commits with an email address which is not affiliated to your GitHub account, so it doesn't recognize you as the commit "author" as far as your GitHub profile is concerned.

If you want to fix that (you don't need to, it's mostly cosmetic), you can add the email you use for your git commit as secondary email of your GitHub account.

**Comment by poke1024** [comment]
@akien-mga Thanks for nothing this! Fixed now.

**Comment by groud** [comment]
Don't forget to format (with `clang-format`) your files according to the coding style:
http://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html?highlight=clang

Can you ammend te commit with those changes ? :)

This updates looks really cool. :+1:

**Comment by reduz** [comment]
i think at some point, Polygon2D, NavigationPolygon and CollisionPolygon2D
editors should be somehow merged using a base polygon editing editor
class...

**Comment by groud** [comment]
> i think at some point, Polygon2D, NavigationPolygon and CollisionPolygon2D editors should be somehow merged using a base polygon editing editor class...

Look like a work for me XD. But not yet...

**Comment by groud** [comment]
Also, NavigationPolygon and CollisionPolygon could inherit from Polygon2D...

**Comment by poke1024** [comment]
@groud Yes, I'll try to amend this.

**Comment by akien-mga** [comment]
As discussed today in our PR review meeting, the feature looks cool and the implementation seems fine, but to avoid having editors behaving differently or too much code duplication, we'd really need to unify the Polygon2D, NavigationPolygon and CollisionPolygon2D editors first (maybe having them all inherit a BasePolygonEditorPlugin or similar).

So we propose to keep this PR around as reference until this happens (either by you or another motivated contributor, @groud mentioned interest in it but he's busy with other things currently).

**Comment by poke1024** [comment]
@akien-mga OK, I'm working on this refactoring now, PR with a proposal coming soon.

**Comment by poke1024** [comment]
@akien-mga @groud I've reapplied this to the refactored code base and added some additional cleanups. Can someone take a look if this is ready to land now?

**Comment by groud** [comment]
Well, I think there are some issues with the "code style". Like creating a class for handling only a Vector2.
But anyway, I am working on the 2D plugins by now, so I should be able to change all this if needed. 
If it works I think the remaining is good to merge.

**Comment by poke1024** [comment]
`PosVertex` represents a compound state of polygon index, polygon vertex number and a Vector2 that improves code clarity by encapsulating what used to be three separate attributes. I cannot comment on code style, this is just unspecific. I hope a decision can be reached if and when this will be merged. I will rebase again once a decision is reached.

**Comment by groud** [comment]
>  PosVertex represents a compound state of polygon index, polygon vertex number and a Vector2 that improves code clarity by encapsulating what used to be three separate attributes.

I know, but usually in Godot's code it seems like we use Vectors (or sometimes Maps) and use the position index in the vector as an id. 
Still, if it works like that it's ok to merge. Once I'm done implementing guides, I plan to clean up and make consistent the code of the CanvasItemEditor and it's plugins, so if I end up with a better solution I'll change that. :)

**Comment by akien-mga** [comment]
I'm fine with merging it once rebased.

**Comment by poke1024** [comment]
Hm... testing shows that keyboard input got broken (key events don't make it to `forward_canvas_gui_input`); maybe I can figure out what changed...

**Comment by poke1024** [comment]
This is ready to merge AFAIC. The keyboard input is broken due to a global regression that breaks all keyboard inputs to plugins - still not fixed, though I thought I clearly named the problem in #12482.

**Comment by poke1024** [comment]
@groud I believe this is working (apart from the keyboard issues), though the longer it stays unmerged the more shortcomings I detect with it:

(1) this should really have buttons like the line editor that is very nice, with "edit", "add" and "remove" buttons. I guess the auto add in the segments should only be active in the "add" mode, so you don't accidentally add nodes in the "edit" mode all the time
(2) the line editor should be refactored to use this code

**Comment by groud** [comment]
Ok, as it works by now it is ok to merge then.

**Comment by girng** [comment]
wow, these PRs by poke are just getting better and better. appreciate them so much

one thing i have is it would be awesome if you could edit the polygons in a `NavigationPolygonInstance` node. like drag and select **closed** polygons (like in a RTS game) move/duplicate them around. this would allow the ability to edit huge maps so much more easier. re-using polygons, etc.

however, i think you could add a node to where you want to cut an outline from, and then just use `add_polygon` in gdscript, so it will dynamically create the polygon

can probably do this using `tool` as well. just throwing ideas out there. with that said, i might have a whack at it too.

**Pull request merged**
