### PR TITLE
Add swap_scene() method for easier changing of instanced scenes

### LINKED ISSUE #24795: Change scene to instance
There are 2 "proper" ways of changing scenes right now.
`get_tree().change_scene("path_to_scene")`
and
`get_tree().change_scene_to(load("path_to_scene"))`

However, often you want to change the scene without discarding the current one or do some setup before changing scene. And this is done in really obscure and hacky way (IMO):
```
var menu = preload("res://Menu.tscn").instance()
menu.game = self
get_node("/root").add_child(menu)
get_tree().current_scene = menu 
get_node("/root").remove_child(self)
```
You need to manually add/remove from root and change the current scene. 

Compare it to this:
```
var menu = preload("res://Menu.tscn").instance()
menu.game = self
get_tree().change_scene_to_instance(menu)
```
The method I'm proposing, `change_scene_to_instance`, would change the current scene to already instanced scene, automatically adding it to root and removing the old one. Unlike the current two methods, it shouldn't free the current scene automatically. This sounds inconsistent, so maybe the name could be different.

Another possibility is a `swap_scene()` method, which would do the same, but also return the current scene. This would change above code into:
```
var menu = preload("res://Menu.tscn").instance()
menu.game = get_tree().swap_scene(menu)
```
That's pretty clean and doesn't seem inconsistent.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes #24795

Works as described in the linked issue.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I noticed that you are supposed to add docs manually to any new method, so I pushed some documentation for `swap_scene()`.

**Comment by reduz** [comment]
This seems like a rare use case, and the function name does not make much sense for the context

**Comment by KoBeWi** [comment]
Rare use case? It's useful anytime you need to change scene temporarily, e.g. for in-game menu or cut-scenes. Or when you need to do external setup for new scene (and scenes don't have constructors).

**Comment by Clean3d** [comment]
I think this method would be useful for games that involve procedural generation (as mine does/will) or that need to dynamically load content before being switched to. For instance, a Minecraft-clone that loads chunks during a loading-progress-bar instead of starting you off in an empty world and streaming the chunks in afterwards.

**Comment by bojidar-bg** [comment]
@Clean3d Note that this is just a shortcut; you can already do what the proposed function does.

**Comment by eon-s** [comment]
It looks confusing, there are already 2 methods to change `current_scene`, also nodes have `replace_by`, which may be possible to modify to not free the replaced node and may work with `current_scene`.

**Comment by KoBeWi** [comment]
^
Still, replacing `current_scene` wouldn't set the reference to new scene.

Right now swapping scenes without freeing is non-intuitive and... awkward. This method is supposed to make it as simple as possible.

**Comment by akien-mga** [comment]
For the reference, this was discussed extensively on IRC a few weeks ago, see logs in http://godot.eska.me/irc-logs/meeting/2019-05-31.log from 16:08.

There's no clear consensus on what should be done exactly, but there's agreement that the current API is unclear and should be improved. This PR might not be the right way to do it but it raises the right questions.

What should be done exactly likely needs further discussion in a formal proposal for 4.0 (as a good change would likely mean breaking compatibility).

**Comment by aaronfranke** [comment]
As stated in the above comment, this needs further discussion in a [proposal](https://github.com/godotengine/godot-proposals/) which includes real-world use cases and an explanation how such an API helps. Such a proposal should summarize the discussions here and in #24795. Also, this PR needs a rebase.

**Comment by KoBeWi** [comment]
I'm not rebasing until there's a consensus that it would get merged (which there isn't xd).

tbh, most of my current projects either don't change scene too often or they pass data through a singleton, so personally I don't have much need for this anymore. Let's just close it for now .-.
(I might still create a proposal later, because there was agreement that current system needs to change)

**Pull request closed without merging**
