### PR TITLE
Add NoiseTexture3D and rename NoiseTexture to NoiseTexture2D.

### LINKED ISSUE #4946: Add NoiseTexture3D
### Describe the project you are working on

Just testing features before release.

### Describe the problem or limitation you are having in your project

Fog volumes could be procedural for nice vfx but lacks an option to do so OOTB (maybe custom material will work but it would be awesome anyway to have built-in). I am talking about using noise in density texture but noise doesn't have 3D output, and isn't even an option to choose (there is a 3D mode in noise but output is projected onto 2D texture).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding support for using noise texture with something like a real 3D mode in a FogVolume's material. This change could greatly increase volume usability and as i stated before, allow to create really nice visual effects easier.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

NoiseTexture with maybe something like "3D" parameter could be used inside FogVolume density texture.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I think that it is possible but it is inconvenient.

### Is there a reason why this should be core and not an add-on in the asset library?

i think that it is a basic feature that would be used not only in fog volumes because "NoiseTexture3D" could be used in a variety of shaders

### PR DESCRIPTION
**Pull request by Lasuch69**
Add NoiseTexture3D and rename NoiseTexture to NoiseTexture2D.

This commit implements new resource NoiseTexture3D. Unfortunately it doesn't support seamless generation.
Note: Mipmaps are buggy as some resolutions (only lower than default) break format required size and can't intialize. Also if you change resolution too fast you get a size mismatch error.
As for Noise resource modification i only changed arguments for generation to support custom depth allowing for 3D coordinates to be used.

	modified:   modules/noise/config.py
	modified:   modules/noise/doc_classes/Noise.xml
	renamed:    modules/noise/doc_classes/NoiseTexture.xml -> modules/noise/doc_classes/NoiseTexture2D.xml
	new file:   modules/noise/doc_classes/NoiseTexture3D.xml
	modified:   modules/noise/editor/noise_editor_plugin.cpp
	modified:   modules/noise/noise.cpp
	modified:   modules/noise/noise.h
	renamed:    modules/noise/noise_texture.cpp -> modules/noise/noise_texture_2d.cpp
	renamed:    modules/noise/noise_texture.h -> modules/noise/noise_texture_2d.h
	new file:   modules/noise/noise_texture_3d.cpp
	new file:   modules/noise/noise_texture_3d.h
	modified:   modules/noise/register_types.cpp

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/4946.*

### CODE REVIEW

**Comment by Geometror** [comment]
Thanks for your work on this :)
First things first: It is recommended that you never use your master branch for pull requests. While it essentially works for now, you can quickly run into problems this way.
Your pull request description contains information about which files were modified/added/removed, which is redundant since the GitHub UI already shows this. It would be more helpful to provide a short summary about what your PR does (although more detailed than the title)/what remains to do or which problems you faced.
On a first glance the implementation looks quite good to me, but I need to review it more thoroughly.

**Comment by Lasuch69** [comment]
> Thanks for your work on this :) First things first: It is recommended that you never use your master branch for pull requests. While it essentially works for now, you can quickly run into problems this way. Your pull request description contains information about which files were modified/added/removed, which is redundant since the GitHub UI already shows this. It would be more helpful to provide a short summary about what your PR does (although more detailed than the title)/what remains to do or which problems you faced. On a first glance the implementation looks quite good to me, but I need to review it more thoroughly.

I will try to improve on that. Thanks for advice!

**Comment by Lasuch69** [comment]
Okay how does the file got 3 more spaces in the comments.
I'm making it a draft.

**Comment by Geometror** [comment]
In addition to my comment before, 
https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html provides a very helpful and detailed explanation of the Godot pull request workflow.

**Comment by Lasuch69** [comment]
Out of curiosity i need to test one thing and then i will make it finally work

**Comment by Lasuch69** [comment]
I needed to fix a couple of typos and add comments

**Comment by Lasuch69** [comment]
updated fork

**Comment by Lasuch69** [comment]
i hate my life

**Comment by Calinou** [comment]
> i hate my life
> 
> rebase conflict defeated me
> 
> i will try to improve it as much as possible and i give up for now with PR's

Do you still have the code somewhere? This PR no longer includes any code, which makes it impossible for other people to salvage your work (if you no longer have time to work on it).

**Comment by Lasuch69** [comment]
> Do you still have the code somewhere? This PR no longer includes any code, which makes it impossible for other people to salvage your work (if you no longer have time to work on it).

I do. Here: https://github.com/Lasuch69/add_noisetexture3d/tree/add-noisetexture3d The problem is that this function: https://github.com/Lasuch69/add_noisetexture3d/blob/cdf5a02c276165c27ad7a97d716b14d7a4106c47/drivers/vulkan/rendering_device_vulkan.cpp#L1147 on "for" loop iterates on mipmap levels (u_int) and sometimes it doesn't take into account lowest layers for example 1x1x4 is 7 pixels in total with mipmaps and this function iterates only through first one because layers are recognized by width and height only and depth isn't taken into account. Tbh i don't know what to do so feel free to do anything with this code you want.

**Pull request merged**
