### PR TITLE
Enable toggle behaviour for buttons that trigger popups

### PR DESCRIPTION
**Pull request by YeldhamDev**
So they actually highlight when their popups are open:
peek 2018-09-21 02-42

### CODE REVIEW

**Comment by akien-mga** [comment]
While this looks cool to me, this breaks compatibility for `ColorPicker`, `OptionButton` and `MenuButton` IINM, so it can't really be considered for 3.1 at this stage.

We can see if it can be adapted for 3.2 so that it doesn't break compat, otherwise it would have to wait for 4.0.

**Comment by YeldhamDev** [comment]
@akien-mga How so? Unless someone really depends on these buttons to not be in toggle mode, I don't see how this breaks compatibility.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
@Calinou Could you mention in the changelog that ColorPicker, OptionButton and MenuButton now have a toggle mode with is enabled by default (thus a behaviour change compared to 3.1).

**Comment by Calinou** [comment]
@akien-mga Done :slightly_smiling_face:

**Pull request merged**
