### PR TITLE
Preparation to fix memory leak when using Ref in NativeScript

### LINKED ISSUE #215: Custom type Ref<T> leaks
Ref<T> of custom type T leaks if it is created from gdnative module.
```c++
Ref<A> a;
a.instance(); //leaks
```
Ref<T> of Godot type T is freed correctly.
```c++
Ref<File> f;
f.instance(); //ok
```
Custom type instances created from gdscript are freed correctly as well.
```gdscript
var a = load('res://a.gdns').new() #ok
```

*Update:*
As a workaround I'm currently using `a = Ref<A>::__internal_constructor(A::_new());` instead of `a.instance` which seems to work fine.

### PR DESCRIPTION
**Pull request by PhilWun**
Preparation to fix https://github.com/GodotNativeTools/godot-cpp/issues/215.

### CODE REVIEW

**Comment by Zylann** [comment]
Currently discussing that issue with @sheepandshepherd and the thing is, that fix is a workaround to "undo" an unwanted reference initialization.

In C++ bindings, we instanciate new classes with `T::_new()`, which returns a pointer.
With a Godot class, it works fine as we just invoke the constructor, giving us a `godot_object*` directly, just like in engine.

The problem arises when we want to instance custom classes, *from our C++ library*. First, we need to get a hand on the `NativeScript` resource... which is a file that our framework has no idea where it is. And it's a file because in Godot, scripts are resources, and resources must be files. So we work around that by creating a new instance of the `NativeScript` resource (not clean, but worked so far), just so we could call its `new_()` function. But this returns us a `Variant` **with an already-initialized `refcount_init`**. Because of that, when that temporary `Variant` goes out of scope to become a pointer in our API, that sole reference is lost and the object is deleted. So initially we thought of "undoing" that by adding an extra reference here: https://github.com/GodotNativeTools/godot-cpp/pull/401/files
However that means we create a leak specifically on custom classes due to that extra reference. Which then, led to the present PR, to keep "undoing" the mess.

So in my opinion, those PRs solve the problem in the wrong way. They rely on the existence of complicated *workarounds*, which should not have been there in the first place.
What we should have instead, is a way to setup the object and its script instance without involving a `Variant` wrapper. This way, we could continue treating custom classes the same as any other class.

**Comment by toasteater** [comment]
It's possible to setup the script instance of an `Object` using `Object::set_script`. No `Variant`s are involved that way.

**Comment by Zylann** [comment]
@toasteater interesting... but then how do you get a hand on your custom class instance pointer?

**Comment by toasteater** [comment]
@Zylann Call `godot_nativescript_get_userdata`?

**Comment by Zylann** [comment]
@toasteater like so?
```cpp
template <class T>
inline T *create_custom_class_instance(const char *class_name) {
	godot::NativeScript *script = godot::NativeScript::_new();
	script->set_library(get_wrapper<godot::GDNativeLibrary>((godot_object *)godot::gdnlib));
	script->set_class_name(class_name);

	// This makes Godot create the custom class instance and attach it to a new instance of the base class
	Object *base_obj = T::___new_godot_base();
	base_obj->set_script(script);
	T *instance = get_custom_class_instance(base_obj);

	return instance;
}
```
I need to check if it works properly

**Comment by toasteater** [comment]
@Zylann Yes. The Rust bindings [do something like that](https://github.com/GodotNativeTools/godot-rust/blob/master/gdnative-core/src/class.rs#L86) and it seems to work.

I don't think you want to free `base_obj`. Freeing a object will also free the script instance attached to it, so you'll end up with a dangling pointer.

**Comment by Zylann** [comment]
@toasteater what I mean is the fact that like I explained earlier, `Base` is a wrapper around the real Godot object. I wonder if that wrapper specifically is going to leak or if it's actually needed.

**Comment by toasteater** [comment]
@Zylann The wrapper itself is probably not needed, since whatever magic in your `godot_instance_create_func` won't be able to see it at all. You just need to find a way to deallocate it without running its deconstructor, in case it frees `_owner` or decrements the reference count there.

**Comment by aaronfranke** [comment]
@PhilWun Is this still desired? If so, it needs to be rebased on the latest master branch.

The commits you pushed are merge commits, which are not good to have in a PR. See this article to learn how to rebase: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by Zylann** [comment]
The bug that led to this PR has been fixed, so it's probably no longer necessary.

**Comment by akien-mga** [comment]
Closing then. Please comment if it's still necessary and we can reopen it.

**Pull request closed without merging**
