### PR TITLE
Fix compie error in TileMap::_fix_cell_transform(...)

### PR DESCRIPTION
**Pull request by marynate**
- offset should be constant reference
- update naming of parameters to follow "p_" naming convention

### CODE REVIEW

**Comment by akien-mga** [comment]
I confirm that this fixes the build error.

**Comment by theuserbl** [comment]
Worked for me. Thanks marynate.
The primary fix of the bug is, that you says the compiler, that "offset" is constant.
I don't think, that the errror outputs of the gcc/g++ are helpful to find the bug.
So congrats for the fix. Hopefully it will be merged soon.

**Comment by akien-mga** [comment]
> The primary fix of the bug is, that you says the compiler, that "offset" is constant.
I don't think, that the errror outputs of the gcc/g++ are helpful to find the bug.

As far as I understand the error output is helpful, if you take it together with the preceding note:
- ```note: no known conversion for argument 3 from 'Vector2' to 'Vector2&'``` i.e. a Vector2& argument is expected, but the one that is passed is Vector2 and can't be converted.
- ```error: no matching function for call to 'TileMap::_fix_cell_transform(Matrix32&, TileMap::Cell&, Vector2, Size2&)'```: it makes sense with the above, there is no function that uses a Vector2 argument, the actual TileMap::_fix_cell_transform function expects a Vector2& (one has to check the code to see that though).

Now, I think one needs some experience with C++ to understand this kind of errors. As a C++ beginner I've made my own interpretation, and it took me a little while, but in the end I found a working solution by passing a tmp_ofs Vector2 variable as argument instead of an addition of two Vector2s. But @marynate's fix shows that the proper solution is to make the reference const (and to see that, one needs experience with C++ to know that the sum of two objects can be made into a const& but not a simple reference).

**Comment by reduz** [comment]
Damn it, this is a typical error when writing code using MSVC compiler, which for some reason does not mind a reference to a temporary variable. GCC complains instead.

**Pull request merged**
