### PR TITLE
[3.x] [Net/ENet] Better handle truncated socket messages

### PR DESCRIPTION
**Pull request by Faless**
Update ENet to latest upstream master branch (`ea4607a90dbfbcf4da2669ea998585253d8e70b1` at the time of the PR), plus https://github.com/lsalzman/enet/commit/2a85cd64459f6ba038d233a634d9440490dbba12 , which fixes a DoS vulnerability in ENet library code originally discovered by @Facundo15 and reported to the Godot Security Team.

The fix is included in [4.0.4](https://godotengine.org/article/maintenance-release-godot-4-0-4/), [3.5.3](https://godotengine.org/article/maintenance-release-godot-3-5-3/), and [4.1.2](https://godotengine.org/article/maintenance-release-godot-4-1-2/), and all 4.2 beta releases.

See #79699 for the 4.x version.

### CODE REVIEW

**Review by YuriSizov — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Comment by jasonwinterpixel** [comment]
I review the changelog before we merge upstream. I request that a description is _always_ written for a pull request like this. If it's written in the master branch version, then that should be linked. I put a lot of effort into my pull requests so that they are understandable by the community, core members need to lead by example.

**Comment by AThousandShips** [comment]
You are free to *ask* that, but this is not a polite, or constructive, way of providing feedback or criticism, please read the [code of conduct](https://godotengine.org/code-of-conduct/).

**Comment by aaronfranke** [comment]
@jasonwinterpixel This PR's description was intentionally vague because it fixes a security vulnerability, and we want to make it look uninteresting to potential malicious actors. I'm only mentioning that this is a security fix now because a release containing this fix (3.5.3) has been out for a month.

**Comment by jasonwinterpixel** [comment]
Serious question, how would you write it to be more polite?

**Comment by AThousandShips** [comment]
First of all I first saw your very first message, before you edited it, which I think we can all agree was neither productive nor polite

But as I said, and though I understand your position, the way the message reads do me is demanding, so I'd suggest to approach it with a tone like "I'd like it if" or "I'd appreciate it if", as opposed to putting demands on the work of others, but language is complicated and perhaps the original intent does not always carry through in text, which I understand.

Have a nice day

**Comment by Faless** [comment]
@jasonwinterpixel the two PRs were originally under embargo, waiting to be applied in an official release, I have correctly updated the description now.

**Comment by jasonwinterpixel** [comment]
Thank you for updating the description. I will commence investigating to see if we are affected by any relevant security issues.

**Pull request merged**
