### PR TITLE
Clear specular buffer if sky mode is canvas and screen space effects are used

### LINKED ISSUE #76044: Enabling SSR with a Canvas Sky creates ghosting on any element in the environment (but not on macOS)
### Godot version

v4.0.2.stable.custom_build [285ca4637]

### System information

Windows 10, Forward+

### Issue description

Spent a few days working on macOS and in that time, re-did my skybox to use canvas layers, all was well. Returned to my windows machine to find ghost artifacts everywhere. 

Isolated it to the SSR setting on the global world environment. Seems some combination of Canvas BG and SSR is the culprit.

Tested on a double precision custom build as well as 4.0 - 4.02 official builds. 

anim

### Steps to reproduce

Create a background CanvasLayer
Set world environment background to Canvas, ensure layer it set to include previous step
Add something to the scene (MeshInstance3D)
Add Camera
Move the camera

### Minimal reproduction project

[canvas-ghost.zip](https://github.com/godotengine/godot/files/11228426/canvas-ghost.zip)

### PR DESCRIPTION
**Pull request by puchik**
Canvas background mode does not clear the color buffer, but copies over it. If screen-space specular effects are enabled and the background is blank, this would result in ghosting due to the separate specular buffer copy. Need to explicitly clear the specular buffer once we're done with it to fix it.

Closes #76044 

Animation

(Note, this fixes the artifacting when resizing the window mentioned in that issue, too, but only once resizing is stopped. Previously, the flashing and artifacts would remain after resizing was finished. Now at least it's cleared once the window stops moving. Still, this PR does fix the original issue and logically makes sense. That other bug should probably be a separate issue and PR as the cause seems to be different.)

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
It is kind of a pain to have to open a draw list to do this. But we don't have an easy way to clear one texture in a framebuffer when opening a render pass, so this is the best solution for now.

**Comment by YuriSizov** [comment]
@clayjohn Should we cherry-pick this to 4.1?

**Comment by clayjohn** [comment]
> @clayjohn Should we cherry-pick this to 4.1?

Sure!

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.1.

**Pull request merged**
