### PR TITLE
Fix ParticlesMaterial spread.

### LINKED ISSUE #47145: ParticlesMaterial's emission direction is wrong if direction.z != 0 and direction.y != 0
**Godot version:**
v3.2.4-rc5

**OS/device including version:**
Windows 10. GLES3.

**Issue description:**
If the direction property of a ParticlesMaterial is changed, it often behaves completely unpredictable.
This is especially apparent, if the values are close to zero.

**Minimal reproduction project:**
The example has two particle systems, which are identical, save for the emission direction.
One of them has the vector (1.0, 0.0, 0.0), the other (1.0, 0.01, 0.01).
They should visually emit in almost the same direction, they are almost 45° off.

[particle_spread_test.zip](https://github.com/godotengine/godot/files/6167382/particle_spread_test.zip)

### PR DESCRIPTION
**Pull request by mortarroad**
Fixes #47145
For 3.x:  #47310

Instead of doing some butchery with atan and then manipulating angles, we simply rotate the vector.

### CODE REVIEW

**Comment by QbieShay** [comment]
I don't think "up" is a good name: people will most likely will assign the y vector and expect it to work.

I'm trying to think of something different, but I'd also like to do some research in math first to determine if there is a mathematical way to pick a random vec2 in a plane that doesn't have defined axes, so that we don't need to expose this variable at all.

**Comment by mortarroad** [comment]
Well, setting _up_ to be the y axis will always work, in the sense that it will still be emitting in the chosen _direction_.

Also, we need an _up_ axis, because we have the _flatness_ property, and the _up_ axis determines along which axis it should get flatter.

But I agree, the distribution could be better, currently it is quite rectangular.

**Comment by QbieShay** [comment]
@mortarroad after some brainstorming with a friend we came up with picking the vector like this:

(x, y, z) -> (-y, z, x)

Can you try if this looks better?

**Comment by QbieShay** [comment]
Actually, something better from [here](https://www.mathworks.com/matlabcentral/answers/72631-create-orthonormal-basis-from-a-given-vector#answer_82725)

```
So, given vector
 v = [a;b;c];
in R^3, it follows that any point (x,y,z) that satisifies a*x + b*y + c*z = 0 (i.e. a point that lives on plane whos normal vector is v) will define components of a vector that is orthogonal to v.
One such vector is
u = [0;-c;b];
or, for example,
u = [-c,0,a];
(you can choose whatever you prefer, but it cannot be [0;0;0])
... Now, given u and v, compute the third vector that is orthogonal to both u and v with
w = cross(u,v);
To make an orthonormla basis use
u1 = u/norm(u);
v1 = v/norm(v);
w1 = w/norm(w);

```

**Comment by mortarroad** [comment]
@QbieShay Is that a formula for deriving the _up_ vector from the _direction_?
If so, it won't work either:
Let _direction_ = (1, 1, -1).
Then _up_ = (-1, -1, 1), which is parallel to _direction_.

**Comment by QbieShay** [comment]
aw :( I'm still not sure about this. I suppose in this case we can restore the singularity, but instead place it on the X axis?

Alternatively I think we can call this property "basis vector" and give it a meaningful description such as "used to calculate the angles for particles. please don't make it the same direction as the direction vector. Orthogonal to the direction vector would be best."

**Comment by mortarroad** [comment]
Emitting either happens in the XZ plane, in which Y is a good choice for _up_, or mostly along Y, in which X or Z is a good choice for _up_.
There's no good solution here.
Maybe we can automatically set _up_ to be Z, if the user chooses Y as the _direction_ in the editor.

I still think "up" is the right name. Everything else would be confusing.

A fitting description could be:
"A vector perpendicular to _direction_, along which _spread_ is applied. The second implicit vector for applying the spread is orthogonal to both _up_ and _direction_."

**Comment by QbieShay** [comment]
I disagree with "up" being a good choice. It's confusing: it's not necessarily pointing up. What about `spread normal`?

**Comment by mortarroad** [comment]
Renamed _up_ to _spread_normal_.
Added docs for _spread_normal_.

**Review by clayjohn — APPROVED** [review]
Looks good to me! Let's just get @QbieShay's approval before merging. This will be a nice addition to 3.4 as well

**Comment by QbieShay** [comment]
Hey @mortarroad. First of all, thanks for all the time you spent on this. I'm super sorry, but upon reviewing this code, and the addition to a user facing variable, I'm under the impression that your original implementation was the best one. I have given it more thought, and I don't believe that there are many cases for people smoothly rotating the direction of the particle shader to justify adding a user facing parameters.

Sorry again for changing my mind, and thanks for your time!

**Comment by mortarroad** [comment]
Are you sure?
I mean, the user can just leave the variable at its default value without having to care about it.

But if you're sure, I'll just remove it and have it pick either Y or X at the up vector automatically as in the original patch.

**Comment by QbieShay** [comment]
Yes I think that would be best. Thanks for your patience :pray:

**Review by QbieShay — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
