### PR TITLE
Fix warning: Property not found: mono/editor/editor_path_optional 

### LINKED ISSUE #36995: Warning on project initialization: Property not found: mono/editor/editor_path_optional
**Godot version:** 3.2.1-stable_mono_win64

**OS/device including version:** Win10 1909

**Issue description:** Godot is trying to find a property, but it is failing to do so

**Steps to reproduce:** Just edit a project
```
editor/editor_settings.cpp:151 - EditorSettings::_get - Property not found: mono/editor/editor_path_optional
```

**Minimal reproduction project:** Sorry, I didn't get this field's gist

### PR DESCRIPTION
**Pull request by van800**
fix https://github.com/godotengine/godot/issues/36995

### CODE REVIEW

**Comment by akien-mga** [comment]
Please amend the commit message to describe what bug is fixed (not just the GitHub issue number, but what the bug *is* in English).

**Comment by van800** [comment]
done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
