### PR TITLE
Fix C# array null handling

### LINKED ISSUE #82362: Exporting NodePath as a C# array don't work
### Godot version

4.1.1 & 4.2-dev5

### System information

win10

### Issue description

The docs says it is possible to export NodePath in a native c# array, but in reality is not.
https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_exports.html#exporting-c-arrays

### Steps to reproduce

```cs
[Export] public NodePath[] NodePaths { get; set; }
```

And try to build you will receive a similar error message:
```
  modules/mono/glue/runtime_interop.cpp:1324 - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.ArgumentNullException: Value cannot be null. (Parameter 'array')
     at Godot.Collections.Array..ctor(Span`1 array) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Array.cs:line 90
     at Godot.NativeInterop.VariantUtils.CreateFromSystemArrayOfNodePath(Span`1 from) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/VariantUtils.cs:line 238
     at Project.Test.GetGodotPropertyDefaultValues() in ProjectPath\Godot.SourceGenerators\Godot.SourceGenerators.ScriptPropertyDefValGenerator\Project.Test_ScriptPropertyDefVal.generated.cs:line 11
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
     --- End of inner exception stack trace ---
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at Godot.Bridge.ScriptManagerBridge.GetPropertyDefaultValuesForType(Type type, IntPtr scriptPtr, IntPtr addDefValFunc) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/ScriptManagerBridge.cs:line 992
```

### Minimal reproduction project

easily reproducible

### PR DESCRIPTION
**Pull request by SaNeOr**
close #82362

### CODE REVIEW

**Review by RedworkDE — COMMENTED** [review]
I do not think that this is the correct fix as there isn't really a null Span, instead null equals to an empty span, thus I'd argue that the throw from the Array constructor as currently there is no way to create a Godot.Array from an empty array. If the behavior of converting a null `StringName[]` to a nil variant is desired such a check has to be added at a different point.

**Comment by SaNeOr** [comment]
> I do not think that this is the correct fix as there isn't really a null Span, instead null equals to an empty span, thus I'd argue that the throw from the Array constructor as currently there is no way to create a Godot.Array from an empty array. If the behavior of converting a null `StringName[]` to a nil variant is desired such a check has to be added at a different point.

But the way it actually works at the moment is that if you pass null directly to CreateFromArray, it still returns default(godot_variant).

**Comment by SaNeOr** [comment]
@RedworkDE  Wouldn't it make more sense to refer to a new array when span is empty?

**Comment by akien-mga** [comment]
Superseded by #89756. Thanks for the contribution!

**Pull request closed without merging**
