### PR TITLE
Store lock view rotation whether its on or off

### LINKED ISSUE #43593: Perspective view window reverts to Lock View Rotation
**Godot version:** 3.2.3

**OS/device including version:** 
Manjaro Linux
KDE Plasma 5.20.2
Kernel: 5.9.3-1
64-bit
NVIDIA GeForce GTX 1070 Ti, proprietary drivers
12 x Intel Core i7-8700K CPU @ 3.70GHz
32 gb RAM
Editor is set to GLES3, with fallback to GLES2 enabled because I export to Quest, in addition to desktop.

**Issue description:**
I set any 3D scene window that's in Perspective mode to free rotation, and lock any in Orthogonal to locked rotation. It retained these settings for a while, now it defaults to all of my Perspective windows as locked rotation, and often even reverts back to locked when I return to a tabbed scene, not just when I open it for the first time.

This problem started to happen after I created a window layout as such: View -> 3 Viewports (alt), with the largest being Perspective with unlocked rotation, and the smaller being Orthogonal with locked rotation. It never seemed to cause a problem when I had regular 3 Viewports (not alt), with the largest, unlocked Perspective being the first view, the one on top. This makes me wonder if it numbers the windows, and now that my first windows is locked in that view, it locks all the other first windows.

If I open my project, and set my first scene to unlocked, which is just one big Perspective window, other panels that open subsequently work just fine. But as soon as I open a scene that has 3 Viewports (alt), it locks all the open Perspective window scenes.

**Steps to reproduce:**
[ViewPort_problem.zip](https://github.com/godotengine/godot/files/5547373/ViewPort_problem.zip)

1. Open a new scene, set its view to 3 Viewports (alt). Lock the rotation for the two smaller and unlock rotation for the largest.
2. Open another scene, set its view to 1 Viewport, unlock the rotation.
3. Switch back to the first, then again to the second.
4. Notice that the view is now again locked.

**Minimal reproduction project:** 
[ViewPort_problem.zip](https://github.com/godotengine/godot/files/5547375/ViewPort_problem.zip)

### PR DESCRIPTION
**Pull request by sygi**
Currently, lock view rotation information is only stored when it is on, what propagates the locked view to the scenes which shouldn't have the rotation locked.

This stores the information in both cases, and extracts the setter for the field to properly set the label at the bottom of the Viewport.

Fixes #43593.

### CODE REVIEW

**Comment by sygi** [comment]
Out of curiosity, do you have some automatic linter style that could fix the issues that I'm fixing now manually?

**Comment by akien-mga** [comment]
> Out of curiosity, do you have some automatic linter style that could fix the issues that I'm fixing now manually?

Yes: https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#using-clang-format-locally

**Review by YuriSizov — APPROVED** [review]
Makes sense to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
