### PR TITLE
Replace setting by reference with ties

### PR DESCRIPTION
**Pull request by tygyh**
Shortens the method signature and make the code smaller. Pure positives!

### CODE REVIEW

**Comment by arkology** [comment]
https://docs.godotengine.org/en/stable/contributing/development/cpp_usage_guidelines.html#auto-keyword

**Comment by RedMser** [comment]
@arkology You probably wanted to refer to the "Standard Template Library" headline, not the one regarding the "auto" keyword? ^^

But yeah, Godot codebase does not accept `std::tuple`, so this change will likely not be accepted.

**Comment by arkology** [comment]
@RedMser previous the author also used `auto` keyword)

**Comment by tygyh** [comment]
> if the author wanted to contribute something useful with their PR, they would have read the entire page

I don't see any mentions of tuples in the rules. I can update the docs to include an explanation of why they aren't allowed if you explain the reason to me.

**Comment by arkology** [comment]
I'm really sorry if it sounds offensive. You are right, the docs don't mention it. Feel free to open an issue on the Godot Docs repo.

**Comment by tygyh** [comment]
> I'm really sorry if it sounds offensive.

No offense taken. You were explaining the spirit of the rules and it simply didn't match the letter of the rules. Easy fix!

**Comment by tygyh** [comment]
I've made an [issue](https://github.com/godotengine/godot-docs/issues/10415) mentioning this. Since this change isn't allowed I'll close this PR.

**Pull request closed without merging**
