### PR TITLE
TAA Improvements

### LINKED ISSUE #81709: TAA Bad Quality
### Godot version

4.1.1 Stable

### System information

Windows 11- 4.1.1 Stable - intel 6200U nvidia 940M - Vulkan Forward +

### Issue description

I don't know why, but I couldn't get good results from TAA like other engines (unreal and unity)
The movement completely destroys TAA !

If I only use TAA (not using MSAA as an aid) the anti-aliasing disappears completely during camera movement.
This picture was taken while I was moving the camera, you can clearly see that anti-aliasing is not working well.

image

### Steps to reproduce

image

### Minimal reproduction project

https://github.com/LegionGames/FirstPersonController

### PR DESCRIPTION
**Pull request by mrjustaguy**
Resolves https://github.com/godotengine/godot/issues/81709#issuecomment-1722183283 points 2,3 and 5, very slightly 4. and point 1 is significantly improved

The video is too big for github, so there's a video on rocket chat that showcases me playing with the Improved TAA:

https://chat.godotengine.org/channel/rendering?msg=jLP3FxSt5joaNdvNq

The old Disocclusion Logic was totally removed as it was just broken. For instance, a Pixel cannot be half way disoccluded. it either is or isn't, something the logic doesn't realize. Further more, the get closest velocity gave straight up broken results, and the deviation calculation was trying to be smart, giving very hard to debug results, without actually benefiting the image.

In the end I've figured out a much better way of reducing ghosting that doesn't need to even take the disocclusion information into account for ghostless results, as the history clipping deals with that, though at the cost of having to choose between a slight jitter or ghosting. the default shouldn't have any noticable ghosting, and jitter only on highly aliased samples.

### CODE REVIEW

**Comment by Alex2782** [comment]
Godot v4.2.rc (17677a577) - macOS 13.6.1 - Vulkan (Forward+) - integrated Apple M1 - Apple M1 (8 Threads)

 **Demo:** [3d/antialiasing](https://github.com/godotengine/godot-demo-projects/tree/master/3d/antialiasing)


**master branch**

https://github.com/godotengine/godot/assets/41921395/404d7ddb-c072-4e8f-b55d-f6cb4abae57d

**this PR** (it's too blurry, and the ropes flicker on the ship )

https://github.com/godotengine/godot/assets/41921395/fdf4c675-f32f-4f9b-b48c-c009cb7e962c

**Comment by mrjustaguy** [comment]
This is expected, The old implementation worked great when everything is static, but the moment you start moving, all hell breaks loose....

**Comment by AThousandShips** [comment]
Even areas far from things that are moving? As far as I can see from the video the ropes aren't moving (there's nothing animating them)

**Comment by mrjustaguy** [comment]
In the 1st one you can see clear aliasing on the cubes in motion, which isn't there with this PR, though this PR is slightly more jittery and blurrier, but again this is to be expected.. The results are more akin to FSR2 in terms of AA quality, as that jitters a bit too, though it isn't as blurry due to sharpening that it does.

**Comment by Alex2782** [comment]
oh ok, it's about the performance. There is a significantly longer delay in the master branch as soon as "taa" is activated. (approx. 5 seconds). This PR is significantly faster under 1 second.

**Comment by mrjustaguy** [comment]
In the meantime during testing while trying to further improve stability by reworking the disocclusion logic (that has been removed for this PR due to how broken it currently is and is the reason behind half the issues TAA currently suffers from) I've found that this implementation suffers from super ghosts in high contrast areas, very much like FSR2, just much, MUCH worse, and I've been unable to work out a solution for fixing them... 

Everything resulted in one of two outcomes:
1) Super Ghosting Issue persisted
2) ALL of the Old issues persisted to a high degree

Given that when this PR works fine it looks like a slightly worse FSR2 implementation, at half the cost, but has cases where it breaks much more significantly and doesn't have the benefit of being an upscaler, and I'm out of ideas how to fix the introduced breakages, I'm closing this PR as the current TAA behavior atleast acts significantly differently to FSR2 visually, and half a dozen minor issues are better vs a couple of moderate visual issues, as they stand out more when they occur, IMO.

**Pull request closed without merging**
