### PR TITLE
Issue 46188: fix get unix from datetime when empty dict

### LINKED ISSUE #46188: Godot freeze when executing OS.get_unix_time_from_datetime({})
**Godot version:**
Godot 3.2.4 rc 2

**Issue description:**
Executing
```
OS.get_unix_time_from_datetime({})
```
freeze entire project, until I kill them

### PR DESCRIPTION
**Pull request by ghost**
Fixes #46188

Simply gets a new datetime which is the current execution moment in UTC.

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request :slightly_smiling_face: 

Pull requests (especially ones that break backwards compatibility) should be opened against the `master` branch instead of `3.2`. This is because feature development occurs in the `master` branch. We can then cherry-pick specific PRs to the `3.2` branch if they don't break backwards compatibility.

**Comment by unsignedFoo** [comment]
Makes sense. 
Sorry for opening to the wrong branch.
I'll fix it asap (or tomorrow early morning).

**Comment by Calinou** [comment]
> Technically the data passed as Param is correct, even being an empty dict.

I think it's very likely that passing an empty dictionary isn't expected behavior, so I'd print an error and return a documented invalid value in that case (such as `0`).

**Comment by Faless** [comment]
> @Faless What do you think?

This seems like hiding the issue instead of fixing it

**Comment by unsignedFoo** [comment]
I'll proceed to PR to `master` and close this ticket.

**Pull request closed without merging**
