### PR TITLE
Fixes some retina problems on multi monitor setups

### PR DESCRIPTION
**Pull request by ghost**
This is a small OS X retina display code overhaul to fix several problems with wrong hidpi scaling on setups on OS X involving multiple monitors, when some of them retina and some of them are non-retina.

With the current code, scaling basically only works if you start on the retina screen if it also has the menu bar.

With this PR, what works now in a setup with one retina and one non-retina screen, is:

- starting on the retina screen, if the retina screen has the menu bar
- starting on the retina screen, if the non-retina screen has the menu bar
- starting on the non-retina screen, if the retina screen has the menu bar
- starting on the non-retina screen, if the non-retina screen has the menu bar

The PR also changes two cross-platform assumptions in `EditorNode` and `ProjectManager` that are currently hard coded to the dpi of screen `0`, which was one cause of the problems and which seems plain wrong to me on all platforms.

### CODE REVIEW

**Comment by cbscribe** [comment]
I will try this PR tonight. Retina + multimonitor issues are something I've had a lot of issues with.

**Comment by poke1024** [comment]
@cbscribe Did you find time to test? I'm aware that moving windows across retina to non-retina screens and vice versa is still broken, but apart from that, I believe things should work now.

**Comment by cbscribe** [comment]
Sorry, I was having trouble getting it to build, but I suspect the problem is on my end.

**Comment by BastiaanOlij** [comment]
@poke1024 can you rebase this? Then I can give it a try

**Comment by poke1024** [comment]
@BastiaanOlij done.

**Comment by cbscribe** [comment]
Seems to be working. I tried the 4 possibilities in your bulleted list, and the scaling was correct. Still can't move the window from one screen to the other, but that's another issue. :)

**Comment by BastiaanOlij** [comment]
Very strange. It kinda works.

It seems to open up just fine, I can move the project selecter fine from one monitor to the other and it seems ok. 

But after opening a project, the first time I move the editor from one screen to the other I just get a blank screen. The second time I move it around it works perfectly though everything does get a bit large on the non-retina window, it does resize all the panels to fit correctly.

I'm at work now so i can't test extensively

**Comment by cbscribe** [comment]
@BastiaanOlij I have that problem with the current master as well. Especially if I launch on the non-retina display and move the window to the retina one: I get a solid magenta window.

**Pull request merged**
