### PR TITLE
[3.2] Disconnect item_rect_changed removing a child of GraphEdit

### PR DESCRIPTION
**Pull request by Rubonnek**
3.2 version of #41995

### CODE REVIEW

**Comment by capnm** [comment]
I can confirm, fixes the
```
ERROR: Signal 'item_rect_changed' is already connected to given method 'update' in that object.
   at: connect (core/object.cpp:1515)
```
for me :+1:

**Comment by Chaosus** [comment]
No need to create a separate version of #41995 since it can be easily cherry-picked.

**Comment by capnm** [comment]
> No need to create a separate version of #41995 since it can be easily cherry-picked.

Well, now it is even easier to commit ;)

**Comment by Chaosus** [comment]
Yeah, it was just a note for the future commits ^^

**Comment by Rubonnek** [comment]
Alright, I'll keep that in mind.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
