### PR TITLE
Generate controller mapping class from one or more SDL2 database files

### PR DESCRIPTION
**Pull request by cart**
Godot currently gets its mappings from the [SDL Game Controller DB](https://github.com/gabomdq/SDL_GameControllerDB).  They make their database available in the form of a txt file, but godot needs to consume the mappings statically in code.  It looks like we currently manually integrate updates from SDL Game Controller DB and transform them into a C++ array format.  It gets the job done, but:
1) it's toilsome
2) it's error prone
3) it makes it hard to distinguish our own custom mappings from the community db

These changes remove the manually generated mappings from input_default.cpp and create a new autogenerated class file at build time.  It reads from one or more database files and records mappings in order.  Any controller GUID collisions are resolved by writing the newer/higher indexed database entry on top of the older one.  When this occurs a "WARNING" comment is added to the generated class file.

I included the following database files (they are written in this order, so the custom godot mappings take precedence):
1) gamecontrollerdb.txt
    * current SDL Game Controller DB
    * SDL 2.0.6
2) gamecontrollerdb_205.txt
    * last version of SDL Game Controller DB
    * SDL 2.0.5
3) godotcontrollerdb.txt
    * Any mappings currently in Godot not in the above two files.  This is a combination of custom godot mappings and some mappings from the SDL 2.0.4 community db

Updating our mappings is now as simple as copying the updated db.txt file from the community db.  If we find other databases worth integrating, we can easily do that too.

Caveats:
1) It assumes all database files are in the community database format (two lines for the header, each OS mapping section starts with ```# OS_NAME```).  I couldn't find a standard so it seemed ok to lock on to this one.
2) It looks like godot doesn't currently know how to interpret the range / inversion modifiers (+,-,~) introduced in SDL 2.0.6.  The newest version of the community database uses them in some cases.  These entries are discarded and a "WARNING" comment is added to the autogenerated file.
3) Starting with SDL 2.0.5 the GUID format changed for some platforms.  I'm guessing godot doesn't use this format but I'm unsure.  I can say with certainty that the latest version of the SDL Game Controller DB added useful mappings for me on linux, so that format is probably the same.
4) When we add new Platforms/OSes that need controller mappings, we need to add a new mapping to the "platform_variables" dictionary
    * ex: ```"Linux": "#if X11_ENABLED",```

Future Work:
* I opted for safety here (preserve existing mappings but add as many new ones as possible).  If godot supported the changes to the mapping format since 2.0.4 (new guid format, modifiers), we should be able to remove gamecontrollerdb_205 and remove the 2.0.4 community mappings from godotcontrollerdb.txt
* Even if the above isn't done for awhile, I should probably break out the 2.0.4 community db from the godot custom mappings.  I might do that over the next day or two

@Hinsbart

### CODE REVIEW

**Comment by cart** [comment]
Hmm I'm having some build issues that I wasn't before (apart from the style validation, which I also failed :smile: ).  I'm looking now

**Comment by cart** [comment]
Its an order of operations problem.  The .cpp file is generated correctly on the first build, but it isn't compiled.  It is picked up on the second build.  I'll try to sort it out but this is my first time working on an SCsub file.

**Comment by cart** [comment]
Success! (Travis failed during an update)

**Comment by groud** [comment]
I don't get why this is less prone to error that writing C++ code. I don't know here, but usually you have compilation errors that prevent you from doing bad things. Also, I don't get why we could not move custom actions in a separated area of the code.

I'm not fundamentally against this, but apart from the "it's easy to copy-paste the file" I don't really see the advantages  in having a dedicated file preprocessed at build time.

**Comment by cart** [comment]
Thats a valid critique.  Compile time checks are always good, but we still get them with this automation.  The main benefit I see here is a clean way to perform updates.  Currently you need to download the update, visually diff the changes (or write automation to do it for you), format the changes as a cpp, and insert them.  If it was my day job to do that I would automate it the first time I was asked to do it.

The community db is an external dependency that has no reason to be merged with code (or configuration) here.  It adds upkeep work for no benefit.

I'm curious about what you mean by moving custom actions to a separated area of code.  Are custom actions an scons concept or are you talking about input actions?

**Comment by cart** [comment]
Also I just pushed changes that separate the godot mappings from the 2.0.4 community mappings

**Comment by cart** [comment]
If you're worried about slowing down the build we could always make it a separate utility that we run once when a db is updated, then check in the outputted class file.

**Comment by groud** [comment]
Not really, the impact on compilation time is probably neglictible.
Anyway, I'd better let @akien-mga decide whether if this is a better workflow or not :)

**Comment by cart** [comment]
We should definitely do what everyone thinks is best.  This wasn't a huge time investment so I'll happily go along with the crowd on this one.

**Comment by akien-mga** [comment]
That's a good change IMO, splitting thirdparty stuff out of Godot code is always better IMO. I'll let @Hinsbart have a look and merge if happy :)

**Comment by Hinsbart** [comment]
Looks great at a first glance, thanks :)
Should be fine to merge but I'll take a deeper look at it soon to confirm.

Also thanks for noticing that the GUID format changed upstream, this should definitely be investigated and implemented.

**Comment by hpvb** [comment]
Love this! I also think it's better to generate from unchanged upstream files.

**Pull request merged**
