### PR TITLE
Match file dialog drive with the current folder.

### LINKED ISSUE #11835: The default new project path doesn't match the default drive in Windows
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64bit, Godot ef08228 (tools.32)

**Issue description:**
By default, when I'm creating a project, I see this:
default

The default path is on C:\ drive, but the drive selected is D: (Godot executable is on D:\).
If I want to browse D:\ then, I need to first select C: in the right drop-down menu, and then D: again

**Steps to reproduce:**
Start Godot, choose "New Project"

### PR DESCRIPTION
**Pull request by djrm**
closes #11835

### CODE REVIEW

**Comment by groud** [comment]
LTGM

**Comment by Noshyaar** [comment]
>LTGM

Look Too Good (for) Me? 🤔

**Comment by groud** [comment]
This is more like a :

> Little Thing Getting Merged

 :p

**Comment by reduz** [comment]
Lets Test, Go Men!

**Pull request merged**
