### PR TITLE
Improve platform selection in the GDNativeLibrary dock

### PR DESCRIPTION
**Pull request by NilsIrl**
Follow up to #30869

* Replace button text with currently selected platforms
* Expand button size horizontally

This still needs a few improvements before it can be merged:
* Add a drop-down icon to the right of the button
* Add a box around the button

out

### CODE REVIEW

**Comment by akien-mga** [comment]
Maybe you can retrieve the stylebox of `OptionButton` and apply it to the `MenuButton`?

Though maybe it's better to leave it as is, the fact that `MenuButton` doesn't make its expandable menu discoverable is a more general issue that should likely be handled for the whole editor.

**Comment by NilsIrl** [comment]
Maybe `OptionButton` should be changed so it accepts checkboxes.

Adding functions such as
* `use_radio(bool)`
* `get_selected_ids()`

By default the mode would be set to "radio"/exclusive selection so that it doesn't break compatibility.

**Comment by NilsIrl** [comment]
A better solution would be to create another class that's derived from `OptionMenu` and supports checkboxes.

Or make `OptionMenu` be derived from this class.

**Comment by akien-mga** [comment]
I think your improvements are good as is for now, let's open a new issue to discuss improving the editor theme or features around drop-down checkbox lists?

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
