### PR TITLE
Added possibility to override or add target basis to tip bone

### PR DESCRIPTION
**Pull request by AndreaCatania**
With this PR I've added the possibility to change the behavior of tip bone. Now is possible to add the target basis to tip bone or completely replace it

### CODE REVIEW

**Comment by akien-mga** [comment]
Would need a rebase (and review by @reduz eventually...).

**Comment by AndreaCatania** [comment]
Ok I'll do it

**Comment by akien-mga** [comment]
Sorry for the delay - @reduz says this is good to merge, so we'll just need another rebase.

**Comment by akien-mga** [comment]
I solved the conflict and merged as a837c33.

**Pull request closed without merging**
