### PR TITLE
Add fix for TAA passes rendering black meshes on XR

### PR DESCRIPTION
**Pull request by beiller**
Meshes were rendered all black when TAA is enabled with XR.
Error in console:

```
ERROR: Invalid color pass flag combination 13
   at: _render_list (servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:550)
ERROR: Invalid color pass flag combination 14
   at: _render_list (servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:550)
```
   
Adding the missing flags resolved it for me.

### CODE REVIEW

**Comment by beiller** [comment]
Based on @clayjohn previous patch 🤗

**Comment by BastiaanOlij** [comment]
Is this still an issue? I ran into this as well and I was under the impression @DarioSamo already fixed this issue?

**Comment by BastiaanOlij** [comment]
(other than that, I guess this fix looks sensible)

**Comment by beiller** [comment]
Yeah I'm using it in a 4.2 build. I also thought it was fixed earlier or seems to have got lost somehow? Unsure.

**Comment by BastiaanOlij** [comment]
Or it may have been something similar. Anyway I think the fix itself makes sense.

**Review by BastiaanOlij — APPROVED** [review]

**Comment by beiller** [comment]
Thanks Ya'll!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
