### PR TITLE
[Windows] Use CCD API to get fractional screen refresh rates.

### PR DESCRIPTION
**Pull request by bruvzg**
See https://github.com/godotengine/godot/issues/84137#issuecomment-1785443166

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Tested locally on Linux + WINE-Staging 8.18 with [test_refresh_rate_query_4.x.zip](https://github.com/godotengine/godot/files/10774934/test_refresh_rate_query_4.x.zip).

This project works in `master` (reports `120.0` Hz) but reports `-1.0` Hz when run with this PR rebased against `master`.

xrandr output:

```
Screen 0: minimum 8 x 8, current 3840 x 2160, maximum 32767 x 32767
HDMI-0 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 1600mm x 900mm
   3840x2160     60.00 + 119.88*  100.00    59.94    50.00    29.97    25.00    23.98  
   4096x2160    119.88   100.00    59.94    50.00    29.97    25.00    24.00    23.98  
   2560x1440    120.00  
   1920x1080    119.88   100.00    60.00    59.94    50.00    29.97    25.00    23.98  
   1280x1024     60.02  
   1280x720      59.94    50.00  
   1152x864      60.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.95    59.94  
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
```

Logically, `119.88` should be reported on my display.

**Comment by bruvzg** [comment]
Should work now, but on WINE it will not return fractional value (denominator is hardcoded to 1).

**Review by Calinou — APPROVED** [review]
Tested again in WINE, it works as expected.

**Edit:** Also tested on Windows 11 22H2, it works as expected (reports 119 Hz in `master`, 119.88 Hz with this PR).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
