### PR TITLE
Fix bindings project-settings godot exporter

### PR DESCRIPTION
**Pull request by Ranoller**
Bad binded names and missings ones

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Great work, thanks!

**Comment by hpvb** [comment]
Should this be pulled into 3.0? I have to admit I'm not entirely sure what these renames are for.

**Comment by vnen** [comment]
@hpvb this is only relevant for 2.1, it's about the project converter from Godot 2 to 3.

**Comment by hpvb** [comment]
@vnen right, sorry for the noise. Shouldn't be trying to read PRs while ill.

**Pull request merged**
