### PR TITLE
OpenGL : Refact half to float and float to half conversion

### LINKED ISSUE #66459: OpenGL: Fog color is incorrect if one of the components is exactly 0
### Godot version

4.0.beta (53d2a9acd)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.65.01)

### Issue description

This hints at a division by zero, as fog rendering gets strange colors in general (especially in the sky, despite https://github.com/godotengine/godot/issues/66456).

Notice how the fog color suddenly changes as I hit 0 on the red, green and blue channels respectively:

https://user-images.githubusercontent.com/180032/192350728-dd5729a6-6779-463f-b13b-1a4b1fac4cd1.mp4

### Steps to reproduce

- Switch to the OpenGL driver in the Project Settings.
  - Make sure to start the editor with single-window mode enabled afterwards. This can be done by enabling **Single Window Mode** in the Editor Settings before changing the driver, or by opening the project in the editor directly with the `--single-window` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html).
- Add a WorldEnvironment node, a Camera3D node and a MeshInstance3D in front of the camera.
- Enable fog. Change the color using the color picker slowly towards pure black, by adjusting each channel individually with the sliders.

### Minimal reproduction project

[test_opengl_fog_sky_affect.zip](https://github.com/godotengine/godot/files/9648583/test_opengl_fog_sky_affect.zip)

### LINKED ISSUE #66462: OpenGL: Fog color is inverted if density is exactly 0
*Related to #66456 and #66459.*

### Godot version

4.0.beta (53d2a9acd)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.65.01)

### Issue description

Fog color is inverted if density is exactly 0. This doesn't occur when using the Vulkan Clustered renderer.

The black sky in the screenshots below is an unrelated issue. It likely comes from a division by zero or NaN being produced by the shader – see #66459.

### Steps to reproduce

- Switch to the OpenGL driver in the Project Settings.
  - Make sure to start the editor with single-window mode enabled afterwards. This can be done by enabling **Single Window Mode** in the Editor Settings before changing the driver, or by opening the project in the editor directly with the `--single-window` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html).
- Add a WorldEnvironment node, a Camera3D node and a MeshInstance3D in front of the camera.
- Enable fog. Decrease density to 0 using the slider.

### Minimal reproduction project

[test_opengl_fog_sky_affect.zip](https://github.com/godotengine/godot/files/9648583/test_opengl_fog_sky_affect.zip)

### LINKED ISSUE #72882: OpenGL: GPUParticles2D with Color alpha set to 0 are not transparent
### Godot version

4.0.dev (8843d9ad347e5c3be5130153aeecdf48e4fe5a14)

### System information

Windows 10

### Issue description

#72853 fixed #72847
But with the same setup and setting the alpha to 0, particles are still visible.

### Steps to reproduce

Reproduce #72847
Set alpha to 0

### Minimal reproduction project

MRP from #72847

### PR DESCRIPTION
**Pull request by JonqsGames**
Fixes: #72882

Based on : https://stackoverflow.com/a/60047308

I think this solution is more robust than the previous one, still has some edge case for not normalized float but i don't think this is an issue since all float come from the same source.

_Bugsquad edit 
Also fixes: https://github.com/godotengine/godot/issues/66462
Fixes: https://github.com/godotengine/godot/issues/66459
Supersedes: https://github.com/godotengine/godot/pull/72329_

### CODE REVIEW

**Comment by JonqsGames** [comment]
@Riteo sorry didn't knew that. Not sure how to handle that. Since i understand it, i could refactor to make it less like the original answer but i feel like it's cheating.

**Comment by bitsawer** [comment]
He [links his research paper](https://www.researchgate.net/publication/362275548_Accuracy_and_performance_of_the_lattice_Boltzmann_method_with_64-bit_32-bit_and_customized_16-bit_number_formats) which his SO post is based on, but it's hard to say what kind of copyright it has. Some educational institutions can have pretty liberal licenses for their research data, but you'd have to dig a bit. Or maybe even ask the person directly if they or any of the co-authors are allowed to re-license the code snippets.

Howerver, he also seems to run this project: https://github.com/ProjectPhysX/FluidX3D, which has this licencse: https://github.com/ProjectPhysX/FluidX3D/blob/master/LICENSE.md. Seems there is similar code in this file: https://github.com/ProjectPhysX/FluidX3D/blob/master/src/kernel.cpp

**Comment by clayjohn** [comment]
We could always do a direct port of ``make_half_float()`` and ``half_to_float()``
https://github.com/godotengine/godot/blob/0daeb377042700c4e8b59d34dca150b2c32524e0/core/math/math_funcs.h#L634

https://github.com/godotengine/godot/blob/0daeb377042700c4e8b59d34dca150b2c32524e0/core/math/math_funcs.h#L620-L632

**Comment by JonqsGames** [comment]
@clayjohn i agree.
Having second thoughts, maybe could even simplify and only check the case of `exponent == 0`, the rest may be overengineering for that case since the half float limitation is explicit for Compatibility renderer.

**Comment by clayjohn** [comment]
> @clayjohn i agree. Having second thoughts, maybe could even simplify and only check the case of `exponent == 0`, the rest may be overengineering for that case since the half float limitation is explicit for Compatibility renderer.

Indeed, there may be an easy workaround here

**Comment by clayjohn** [comment]
Superseded by https://github.com/godotengine/godot/pull/72914

**Pull request closed without merging**
