### PR TITLE
modify default param names in couple of signals

### PR DESCRIPTION
**Pull request by kubecz3k**
'name' default param should not be used since there is problem with name shadowing

### CODE REVIEW

**Comment by kubecz3k** [comment]
Hmm something has changed with our clang format? There is a lot of unintended 'white characters' changes in my pr...

**Comment by akien-mga** [comment]
Looks like your clang-format is not configured properly to use the `.clang-format` file, so it defaults to LLVM style. Also remember that you need clang-format 5.0+.

**Comment by NathanWarden** [comment]
This might be the same problem I was having. If you're using Ubuntu I believe the .clang-format file is for a newer version than what's on Ubuntu 16.04.

**Comment by kubecz3k** [comment]
@NathanWarden yes it seems it's the case.. I was looking for 5.0 clang package for 17.04 but haven't found, its easier to find it for 16.04... for now I disabled clang checking, will look into it later

**Comment by akien-mga** [comment]
@kubecz3k See http://apt.llvm.org/

**Pull request merged**
