### PR TITLE
Position nodes added from the generic search to the position the cursor was when opening the search

### PR DESCRIPTION
**Pull request by Jummit**

### CODE REVIEW

**Comment by fire** [comment]
Whoo thanks, I couldn't get this to work. Thanks. I'll try it.

**Comment by Jummit** [comment]
@fire I don't mean to brag, but it surprisingly only took me a few minutes to implemented this. It worked the first time! If you look what I did, it's pretty simple.

**Comment by fire** [comment]
It works pretty well.

**Review by fire — APPROVED** [review]
Looks good.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
