### PR TITLE
Fixing conversion between int->float 

### PR DESCRIPTION
**Pull request by kzerot**
Fixes issue #68093 and probably #62650, problem with conversion

### CODE REVIEW

**Comment by kleonc** [comment]
> Fixes issue #68093 and probably #62650

Just tested this PR and it doesn't fix neither of these issues.

Actually I don't think this PR changes anything, AFAIK all the added conversions were already done automatically.

**Comment by kzerot** [comment]
It's a little strange because it fixed range issue for me perfectly, but sure :)

**Comment by kleonc** [comment]
> It's a little strange because it fixed range issue for me perfectly, but sure :)

I think it didn't, check out: https://github.com/godotengine/godot/issues/68093#issuecomment-1298764392.

Nontheless, thanks for the contribution / trying to fix this! :slightly_smiling_face:

**Comment by kzerot** [comment]
Yep, I see. Thanks!

**Pull request closed without merging**
