### PR TITLE
[Web, 3.x] Add IME input support.

### PR DESCRIPTION
**Pull request by bruvzg**
Backport of https://github.com/godotengine/godot/pull/79362 (also include #91695 fixes).

### CODE REVIEW

**Comment by jtakakura** [comment]
It seems to work fine on Firefox.

https://github.com/godotengine/godot/assets/640587/e9e0da5b-ee17-41a1-96df-aa65da9e8b8a

However, upon confirming the Japanese input with the Enter key, a new line is inserted simultaneously on Safari on macOS.

https://github.com/godotengine/godot/assets/640587/96ef22f6-f341-48b2-bc9f-5d57a2c6f658

This could be caused by Safari or Godot; it's not clear which one.

**Comment by bruvzg** [comment]
> This could be caused by Safari or Godot; it's not clear which one.

Seems to be something Safari specific, I can't reproduce it in Chrome or Firefox.

**Comment by JunShiozawa** [comment]
How can I check if it works?

**Comment by jtakakura** [comment]
@JunShiozawa First, you need to check out this PR.
After that, build Godot and its web template.
See the following documents for more details.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally?platform=windows
https://docs.godotengine.org/en/3.6/development/compiling/introduction_to_the_buildsystem.html
https://docs.godotengine.org/en/3.6/development/compiling/compiling_for_web.html

**Comment by JunShiozawa** [comment]
@akien-mga
Why don't you review this PR?

**Comment by akien-mga** [comment]
> @akien-mga Why don't you review this PR?

I would kindly ask you to stop lobbying maintainers to work on your personal priorities. We are all busy and doing what we can with the time we have.

If you absolutely need this PR today, you can merge it in your own branch and use it, following the documentation that was linked to you above.

If you want to help getting this merged, actually testing it and reporting whether it works on all your target browsers would be very helpful.

**Comment by JunShiozawa** [comment]
@akien-mga
I am sorry.

**Comment by jtakakura** [comment]
@JunShiozawa Did you check if it works?
I already explained how to check it.
If this PR is merged as it is, will the result meet your expectations?

**Comment by JunShiozawa** [comment]
Where is Export templates?
I can not export HTML5.

**Comment by JunShiozawa** [comment]
This for Godot 4.x Version is
Chrome for Android Japanese input OK.
Firefox for Android Japanese input OK.
Safari for iPhone Japanese input OK.
Firefox for Linux Japanese input OK.
Firefox for Windows Japanese input OK.
Probably it will work.

**Comment by akien-mga** [comment]
@JunShiozawa Thanks for testing and confirming it works on multiple platforms and browsers.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
