### PR TITLE
WIP: Fix wrong editor hint for string values in visual script editor

### LINKED ISSUE #49231: Visual Script Rich Text Label Value Box opens to Create New Object
**Godot version:**

3.3.2

**OS/device including version:**

Ubuntu 20.10/Atermiter dual Xeon motherboard, gtx 970 nvidia package 460

**Issue description:**

Attempted to put text in a value box;  opened to create new object screen. I expected to  type text in box.

**Steps to reproduce:**
Add a rich text label to scene, drag in a set text( label or BBCode), click on value box. Similar to issue #44336. 

rich_text_label_bug

**Minimal reproduction project:**

Will create if requested.

### PR DESCRIPTION
**Pull request by NoFr1ends**
Fixes #49231

---

Still work in progress as the PropertyEditor for Multi Line Text in master is currently not displayed correctly.

### CODE REVIEW

**Review by phocodes — APPROVED** [review]

**Comment by DavidCambre** [comment]
@NoFr1ends, Heads up
Quick test on daily build resulted in a edit field with only a close button.
image

**Comment by fire** [comment]
Gentle nudge.

**Comment by NoFr1ends** [comment]
@fire I'm still struggling with UI in C++ directly... I initially thought it's only the missing type hint but the ``CustomPropertyEditor`` for Multiline has issues too which I wasn't able to fix yet. But I'll try to get back to this PR this week, sorry for the delay.

**Comment by Gallilus** [comment]
This may be closed by #5219

**Comment by akien-mga** [comment]
Superseded by #52222 (which seems to be a subset of this PR).

**Pull request closed without merging**
