### PR TITLE
Respect window/handheld/orientation setting in iOS

### PR DESCRIPTION
**Pull request by jkb0o**
This PR
- removes `video_mode/allow_*` properties (which are even no presented in my project settings)
- replaces deprecated UIViewController.shouldAutorotateToInterfaceOrientation with supportedInterfaceOrientations + shouldAutorotate
- it also now possible to have custom UIViewControllers to have own autorotate logic witch is very useful when implementing third-party integrations or custom plugins (my game is landscape for example, but ZendeskSupport plugin is hundred times more useful when it is portrait)

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @BastiaanOlij @endragor

**Comment by mhilbrunner** [comment]
LGTM.

Note that there are some gotchas because of interactions with the `Split view` features on iOS9+ (which is enabled by default on certain iPad models) when declaring all orientations as supported in the *.plist*, but those shouldn't apply for Godot fullscreen apps ([see more](https://stackoverflow.com/a/38260535)).

**Comment by jjay** [comment]
@mhilbrunner, the presence of the `UIRequiresFullScreen` in `info.plsit` eliminates the problems with the `Split view`.

**Comment by mhilbrunner** [comment]
Yeah, sorry if that wasn't clear, thats why I said *Looks Good To Me*. IMO, this can be merged, but we'll wait a little for input by other contributors who know iOS :)

**Comment by akien-mga** [comment]
@hpvb This should be cherry-picked into 3.0.6 if possible.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
