### PR TITLE
Make GLTF module togglable when compiling release templates

### PR DESCRIPTION
**Pull request by you-win**
The GLTF module is excluded from release templates by default. This PR adds a build flag to enable/disable the GLTF when compiling Godot and release templates.

This change was needed for my project on 3.x [openseeface-gd](https://github.com/you-win/openseeface-gd), which loads in `gltf`/`glb` models at runtime.

Associated PRs:
- master
  - [godot](https://github.com/godotengine/godot/pull/51383)
  - [godot-docs](https://github.com/godotengine/godot-docs/pull/5161)
- 3.4
  - [godot](https://github.com/godotengine/godot/pull/51382)
  - [godot-docs](https://github.com/godotengine/godot-docs/pull/5160)

### CODE REVIEW

**Comment by fire** [comment]
I and @lyuma 's stance is that runtime support is achievable and wanted.

The Godot Engine maintainers consensus from a few months ago is that runtime asset import is not desired and runtime templates should use the internal formats.

Since Godot Engine is consensus driven, we took the consensus to not have runtime asset. @reduz and @BastiaanOlij were the last to have the runtime asset debate in my recollection.

**Comment by BastiaanOlij** [comment]
Just to add a bit more context as I understand it.

There are two things at play here that underline the _current_ implementation:
- the current import logic is targeted at the editor converting imported data to Godots internal formats (cached in .import) which are then used when running the game. The runtime thus never uses the original imported files and the logic in general (looking broader at DAE and FBX here too) is not suitable as a runtime implementation and a separate implementation is needed
- as Godot has a large following of users who wish to keep the runtime executable as small as possible for mobile deployment where size still matters, especially as some of the import libraries can be fairly large (FBX was, not sure if it still is). It is preferable to look for alternative solutions.

The consensus so far has been that optional logic such as this should be a (potential 1st party) plugin so it becomes an easy to add-on optional module that doesn't require special builds of the engine nor knowledge of the build system by a potential user.

That all said, there is an ongoing discussion whether we should add core GLTF import support seeing there are more and more use cases popping up that warrant this but we would likely limit this to GLTF.

**Comment by aaronfranke** [comment]
Does this depend on #52501? If so, what is the fate of the 3.x version of this PR?

**Comment by you-win** [comment]
@aaronfranke This does not depend on any other PR. It will need to be modified/might not be needed depending on how GLTF importing is handled in the future (i.e. is GLTF import disabled in release builds)

I have been using the 3.x version of this PR to compile export templates.

**Comment by fire** [comment]
@you-win I'm consolidating this work into a proposal https://github.com/godotengine/godot-proposals/issues/3273

Superseded by: https://github.com/godotengine/godot-proposals/issues/3273

**Comment by you-win** [comment]
Closing as fire is working on a better implementation for godot master

**Pull request closed without merging**
