### PR TITLE
Document seamless noise having a lower contrast than non-seamless noise

### PR DESCRIPTION
**Pull request by Calinou**
See #41787.

### CODE REVIEW

**Comment by Xrayez** [comment]
I'd add at least some rationale as to *why*, as elaborated in https://github.com/godotengine/godot/issues/41787#issuecomment-687672044. Mentioning that "due to the way noise uses higher dimensions for generating seamless noise" would be good enough.

**Comment by nathanfranke** [comment]
I think this documentation change should be merged for 3.2 only, there must be a better solution for 4.0.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs a rebase.

> I think this documentation change should be merged for 3.2 only, there must be a better solution for 4.0.

Until the bug is actually fixed in `master`, this is also relevant to merge in `master`. Otherwise if the bug is not fixed we'll be lacking useful documentation.

**Comment by Calinou** [comment]
Rebased and applied @Xrayez's suggestion.

**Review by Xrayez — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
