### PR TITLE
changed color of script editor selection

### PR DESCRIPTION
**Pull request by toger5**
- this is a tiny pr but ... the color.. I had to
screen shot 2017-06-25 at 18 50 53

### CODE REVIEW

**Comment by kubecz3k** [comment]
Looks nice, but I think brightness could be a tiny bit smaller, since I think it has a little to much contrast

**Comment by kubecz3k** [comment]
Current color for the comparison:
spectacle b27969

**Comment by toger5** [comment]
I wanted to get a lot of contrast. But of course this is open to discussion.
You can post your preferred color too. I just update the pr.

I also will make it darker because I think a little darker is good.

**Comment by groud** [comment]
For now I prefer the old version, it is less agressive.

**Comment by akien-mga** [comment]
How about this? `#609eb8`

spectacle f18334

**Comment by groud** [comment]
Way better for me ! :)

**Comment by nhydock** [comment]
Is this just for the script editor or is it anywhere text can be selected?

Can the highlight color just be configurable with the theme settings?

**Comment by vnen** [comment]
I prefer `#6ca9c2`, but all three are better than the OP.

@nhydock this is only for the script editor and it can already be changed in Editor Settings. This PR is just about the *default* value.

**Pull request closed without merging**
