### PR TITLE
Enforce Unicode encoding in MSVC

### LINKED ISSUE #28824: Compilation error in file test_string.cpp with japanese locale
**Godot version:**
Reproduced on 3.1, 3.1.1, 3.1-stable and 3.1.1-stable

**OS/device including version:**
Windows 10, japanese locale, Python 3.7.3, Visual Studio Express 2019

**Issue description:**
Compilation error in file test_string.cpp

E:\godot>scons -j4 p=windows vsproj=yes
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Found MSVC compiler: amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] [94mCompiling [95m==> [93mmain\tests\test_string.cpp[0m
[Initial build] test_string.cpp
[Initial build] main\tests\test_string.cpp(951): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
[Initial build] main\tests\test_string.cpp(1060): error C2001: newline in constant
[Initial build] string.cpp(1062): error C2146: syntax error: missing ';' before identifier 'String'
[Initial build] Compiling ==> thirdparty\libvpx\vp9\common\vp9_scale.c
[Initial build] Compiling ==> thirdparty\libvpx\vp9\common\vp9_scan.c
[Initial build] scons: *** [main\tests\test_string.windows.tools.64.obj] Error 2
Compiling ==> thirdparty\libvpx\vp9\common\vp9_seg_common.c
vp9_scale.c
vp9_scan.c
vp9_seg_common.c
scons: building terminated because of errors.

**Steps to reproduce:**
Follow instructions from official docs on compilation with japanese locale

**Minimal reproduction project:**
Follow instructions from official docs on compilation with japanese locale

### PR DESCRIPTION
**Pull request by Xrayez**
Should hopefully fix #28824 as it's difficult for me to test this. 
All tests pass (34/34) with `godot --test string`

@RicardRC would be nice if you could check this out.

### CODE REVIEW

**Comment by RicardRC** [comment]
It would be nice to also add the lower case as comment, for maximum clarity. (lines 1072~)
// абвгдеёжзийклмнопрстуфхцчшщъыьэюя

I'll test and report tonight.

**Comment by RicardRC** [comment]
Sadly, it does not solve it. I'll post details in the bug report (#28824) to keep it all together.

**Comment by Xrayez** [comment]
I'm obviously shooting into the air but I added MSVC flag to allegedly force compilation to use `/utf8` encoding, not sure if this would help. 😄

**Comment by RicardRC** [comment]
Not into the air,

The two commits by themselves solve nothing, just change the error wording.
BUT your last commit AND the UTF-8-BOM encoding on the file test_string.cpp gets rid of ALL the errors and warnings.

**Comment by akien-mga** [comment]
I'm confused, how many ways does MSVC have to set the encoding to UTF-8? This was already done by @WindyDarian for the same issue in #27915 (and then further refined as this flag fails on MSVC 2013).

**Comment by RicardRC** [comment]
I'll try again tonight from a clean clone. I hope it was just some loose derived file lingering around.

**Comment by WindyDarian** [comment]
@RicardRC You said you were using Visual Studio 2019 in #28824 which concerns me. I am not sure if Scons recognize it thus I am _guessing_ the line `if int(env['MSVC_VERSION'].split('.')[0]) >= 14: #vs2015 and later` in `platform/windows/detect.py` added in #28051 may fail (may worth locally printing the version number before it to check?). Will grab VS 2019 and check tonight.

**Comment by RicardRC** [comment]
The commit to SConstruct alone was enough on clean engine download to solve the problem. No more UTF-8-BOM required, no errors, no warnings. Happiliy pecking to make the game now. I'd consider it solved.

**Comment by Xrayez** [comment]
I guess this PR could be closed, but a proper fix would be required for VS2019 then. Perhaps setting `MSVC_FLAGS=['/utf8']` is a more portable way to define it across multiple Visual Studio versions? I think it would still fail on VS2013 though. 🤔

**Comment by WindyDarian** [comment]
Just wanted to give an update. Installed Visual Studio Community 2019, from the current master branch when I run `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 && cd %cd% && scons p=windows vsproj=yes -j6`, it still builds with MSVC 14.1 and generates vs2017 project files (may because I also have VS2017 installed), and build still succeeds with win10 set to Japanese locale. Guess different things can happen with vs2019 based on the environment. So I think I have no opinion on what's best here without being able to repro the issue.

**Comment by Xrayez** [comment]
O

**Comment by akien-mga** [comment]
> This may be closed anyway as it solves only the symptoms of the problem, here's the line that seems to solve the issue #28824: https://github.com/godotengine/godot/pull/28906/files#diff-cc8093822b396591a5530a463c87d048R313

If that's the only thing needed to fix the issue, maybe we should not do the rest of the changes? Actual unicode characters are a lot more readable.

**Comment by Xrayez** [comment]
Yes, I amended the changes, but left some clarification comments. Also noticed that the usage of `String::utf8()` might also help the issue in some way, at least for consistency.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
