### PR TITLE
Assorted fixes for GDScript bugs

### LINKED ISSUE #23843: Can't initialize enum values from other non-constant values within enum
**Godot version:**
3.1, 3.2, 4.0.

**Issue description:**

This is how I used to initialize some enum values before #23648 (this is actually possible in C++):
```gdscript
enum TimeFormat {
	FORMAT_HOURS   = 1 << 0,
	FORMAT_MINUTES = 1 << 1,
	FORMAT_SECONDS = 1 << 2,
	FORMAT_DEFAULT = FORMAT_HOURS | FORMAT_MINUTES | FORMAT_SECONDS
}
```

Now I can't initialize `FORMAT_DEFAULT` value:
```gdscript
FORMAT_DEFAULT = FORMAT_HOURS | FORMAT_MINUTES | FORMAT_SECONDS # error: Expected constant expression.
```

A workaround would be to initialize enum constants with numeric literals:
```gdscript
enum TimeFormat {
	FORMAT_HOURS   = 1,
	FORMAT_MINUTES = 2,
	FORMAT_SECONDS = 4,
	FORMAT_DEFAULT = 7
}
```

But I find it error prone... If this what breakscompat implies than close the issue, I can live with that :)

### LINKED ISSUE #40650: Embedded GDScript crashes player
**Godot version:** 3811fb919e

**OS/device including version:** Manjaro Linux

**Issue description:**
Playing a scene containing an embedded GDScript causes a crash: 
```
Godot Engine v4.0.dev.custom_build.3811fb919 - https://godotengine.org
DisplayServer::_create_window 0 want rect: 448, 240, 1024, 600 got rect 0, 0, 1024, 600
DisplayServer::_window_changed: 0 rect: 1920, 450, 1024, 600
 
ERROR: Condition "err" is true. Returning: err
   at: load_source_code (modules/gdscript/gdscript.cpp:825)
ERROR: res://Node.tscn:23 - Parse Error: Can't load cached sub-resource: res://Node.tscn::1
   at: _parse_node_tag (scene/resources/resource_format_text.cpp:282)
ERROR: Failed loading resource: res://Node.tscn.
   at: _load (core/io/resource_loader.cpp:198)
ERROR: Failed loading scene: res://Node.tscn
   at: start (main/main.cpp:2030)
ERROR: 1 RID allocations of type 'P11SpaceBullet' were leaked at exit.
ERROR: 1 RID allocations of type 'P8Area2DSW' were leaked at exit.
ERROR: 1 RID allocations of type 'P9Space2DSW' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RasterizerSceneRD11EnvironmentE' were leaked at exit.
ERROR: 2 RID allocations of type 'N17RasterizerSceneRD11ShadowAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RasterizerSceneRD15ReflectionAtlasE' were leaked at exit.
ERROR: 1 RID allocations of type 'N17RasterizerSceneRD3SkyE' were leaked at exit.
ERROR: 1 RID allocations of type 'N19RasterizerStorageRD12RenderTargetE' were leaked at exit.
ERROR: 2 RID allocations of type 'N19RasterizerStorageRD7TextureE' were leaked at exit.
ERROR: 1 RID allocations of type 'PN21RenderingServerCanvas6CanvasE' were leaked at exit.
ERROR: 1 RID allocations of type 'PN23RenderingServerViewport8ViewportE' were leaked at exit.
ERROR: 1 RID allocations of type 'PN20RenderingServerScene8ScenarioE' were leaked at exit.
WARNING: 6 RIDs of type 'Texture' were leaked.
     at: finalize (drivers/vulkan/rendering_device_vulkan.cpp:7486)
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2041)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:435)
```
This only happens with GDScript and not other embedded resources.

Likely introduced with #40598

**Minimal reproduction project:**
[Embedded GDScript.zip](https://github.com/godotengine/godot/files/4970045/Embedded.GDScript.zip)

### LINKED ISSUE #40702: Editor crash on copy-pasting entire `GDScript`s in the script editor
**Godot version:**
4.0-dev 6f292f906e749f30ceb7f922df5639add61a5f88

**OS/device including version:**
Windows 10.

**Issue description:**
Call stack:
```
godot.windows.tools.64.exe!GDScriptParser::DataType::is_set() Line 134 (d:\src\godot\modules\gdscript\gdscript_parser.h:134)
godot.windows.tools.64.exe!GDScriptAnalyzer::resolve_inheritance(GDScriptParser::ClassNode * p_class, bool p_recursive) Line 135 (d:\src\godot\modules\gdscript\gdscript_analyzer.cpp:135)
godot.windows.tools.64.exe!GDScriptAnalyzer::analyze() Line 3053 (d:\src\godot\modules\gdscript\gdscript_analyzer.cpp:3053)
godot.windows.tools.64.exe!GDScriptLanguage::lookup_code(const String & p_code, const String & p_symbol, const String & p_path, Object * p_owner, ScriptLanguage::LookupResult & r_result) Line 2945 (d:\src\godot\modules\gdscript\gdscript_editor.cpp:2945)
godot.windows.tools.64.exe!ScriptTextEditor::_validate_symbol(const String & p_symbol) Line 870 (d:\src\godot\editor\plugins\script_text_editor.cpp:870)
godot.windows.tools.64.exe!call_with_variant_args_helper<ScriptTextEditor,String const &,0>(ScriptTextEditor * p_instance, void(ScriptTextEditor::*)(const String &) p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<0> __formal) Line 132 (d:\src\godot\core\callable_method_pointer.h:132)
godot.windows.tools.64.exe!call_with_variant_args<ScriptTextEditor,String const &>(ScriptTextEditor * p_instance, void(ScriptTextEditor::*)(const String &) p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 158 (d:\src\godot\core\callable_method_pointer.h:158)
godot.windows.tools.64.exe!CallableCustomMethodPointer<ScriptTextEditor,String const &>::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 185 (d:\src\godot\core\callable_method_pointer.h:185)
godot.windows.tools.64.exe!Callable::call(const Variant * * p_arguments, int p_argcount, Variant & r_return_value, Callable::CallError & r_call_error) Line 50 (d:\src\godot\core\callable.cpp:50)
godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1170 (d:\src\godot\core\object.cpp:1170)
godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1225 (d:\src\godot\core\object.cpp:1225)
godot.windows.tools.64.exe!TextEdit::_gui_input(const Ref<InputEvent> & p_gui_input) Line 2429 (d:\src\godot\scene\gui\text_edit.cpp:2429)
godot.windows.tools.64.exe!MethodBind1<TextEdit,Ref<InputEvent> const &>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Callable::CallError & r_error) Line 867 (d:\src\godot\core\method_bind.gen.inc:867)
godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_method, const Variant * * p_args, int p_argcount) Line 737 (d:\src\godot\core\object.cpp:737)
godot.windows.tools.64.exe!Object::call_multilevel(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 836 (d:\src\godot\core\object.cpp:836)
godot.windows.tools.64.exe!Viewport::_gui_input_event(Ref<InputEvent> p_event) Line 2309 (d:\src\godot\scene\main\viewport.cpp:2309)
godot.windows.tools.64.exe!Viewport::input(const Ref<InputEvent> & p_event, bool p_local_coords) Line 2969 (d:\src\godot\scene\main\viewport.cpp:2969)
godot.windows.tools.64.exe!Window::_window_input(const Ref<InputEvent> & p_ev) Line 911 (d:\src\godot\scene\main\window.cpp:911)
godot.windows.tools.64.exe!call_with_variant_args_helper<Window,Ref<InputEvent> const &,0>(Window * p_instance, void(Window::*)(const Ref<InputEvent> &) p_method, const Variant * * p_args, Callable::CallError & r_error, IndexSequence<0> __formal) Line 132 (d:\src\godot\core\callable_method_pointer.h:132)
godot.windows.tools.64.exe!call_with_variant_args<Window,Ref<InputEvent> const &>(Window * p_instance, void(Window::*)(const Ref<InputEvent> &) p_method, const Variant * * p_args, int p_argcount, Callable::CallError & r_error) Line 158 (d:\src\godot\core\callable_method_pointer.h:158)
```

**Steps to reproduce:**
1. Create new `GDScript` with the default template.
2. <kbd>Ctrl + A</kbd> to select all text in the script editor.
3. <kbd>Ctrl + X</kbd> to cut all text.
4. Wait for `error(1,1): Source file is empty.` parse error to appear.
5. <kbd>Ctrl + V</kbd> to paste previous script, should crash now.

**Minimal reproduction project:**
Not needed.

### LINKED ISSUE #40740: Can't use match function in string
**Godot version:**

4.0.dev.custom_build. 6de86946e

**Issue description:**

```
var q_String : String = ""

if randi() % 2 == 1:
	q_String.match("")
```
shows error
```
 res://ResourcesALL/String.gd:153 - Parse Error: Expected identifier after "." for attribute access.
 modules/gdscript/gdscript.cpp:608 - Method/function failed. Returning: ERR_PARSE_ERROR
```

### LINKED ISSUE #40793: Errors in gdscript when creating a Callable from self
**Godot version:**
Master cf03f90fa8d8e0fadcf22741ab75220665578371

**OS/device including version:**
Windows 10

**Issue description:**
Callables with self cause parsing errors in gdscript, which makes it impossible to connect signals by script.

This script line produces gdscript errors:
```
var callable = Callable(self, "my_function")
```

Log:
```
SCRIPT ERROR: Parse Error: No constructor of "Callable" matches the signature "Callable(res://Control.gd, String".
          at: GDScript::reload (res://Control.gd:5)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: GDScript::reload (modules\gdscript\gdscript.cpp:620)
Loading resource: res://Control.tscn
ERROR: Condition "!s->is_valid()" is true.
   at: EditorInspector::_update_script_class_properties (editor\editor_inspector.cpp:2451)
```

This workaround used to work but now it produces the same error:
```
var self_var = self
var callable = Callable(self_var, "my_function")
```

**Steps to reproduce:**
Add this line to any script:
```
var callable = Callable(self, "my_function")
```
And check for gdscript errors.

**Minimal reproduction project:**
Can be reproduced in any project.

### LINKED ISSUE #40826: 4.0: GDScript crash with anonymous enum
**Godot version:**
v4.0.dev.custom_build.c1bb45fcd

**OS/device including version:**
Windows 10.0.18362.959 ; NVIDIA / 445.87

**Issue description:**

The crash occurs in `ExtendGDScriptParser::parse_class_symbol` for enum types.
The unusual thing here is it checks the type of this tagged-union-type `ClassNode::Member`, but accesses the incorrect member.

You will see the CONSTANT case consistently accesses `m.constant`.

However, the ENUM_VALUE case sometimes access `m.constant` but other times accesses `m.enum_value`. I believe the usage of m.constant in this case to be in error.

```
			case ClassNode::Member::CONSTANT: {
				lsp::DocumentSymbol symbol;

				symbol.name = m.constant->identifier->name;
				symbol.kind = lsp::SymbolKind::Constant;
...
			case ClassNode::Member::ENUM_VALUE: {
				lsp::DocumentSymbol symbol;

				symbol.name = m.constant->identifier->name;
				symbol.kind = lsp::SymbolKind::EnumMember;
```

enum_value_crash

**Steps to reproduce:**
Here's a small part of player_camera_controller.gd containing the enum declaration in question
```
@tool
extends Node3D

var origin : Node3D = null
var camera : Camera3D = null

@export var is_active : bool : bool = true

enum {CAMERA_FIRST_PERSON, CAMERA_THIRD_PERSON}

func _enter_tree() -> void:
	add_to_group("camera_controllers")

func _exit_tree() -> void:
	camera = null
	if origin:
		origin.queue_free()
		origin.get_parent().remove_child(origin)
	if is_in_group("camera_controllers"):
		remove_from_group("camera_controllers")
```

Not really steps to reproduce, but here's what happened:
1. Loaded a large project with that .gd file, as well as several others.
2. Godot doesn't crash immediately. Lots of .gd files have syntax errors because the port is incomplete.
3. Touch an unrelated script file outside the editor.
4. Wait a bit.
5. It crashes here on this enum declaration.

**Minimal reproduction project:**

### LINKED ISSUE #40855: GDScript: crash when typing string path as extends script
**Godot version:** v4.0.dev.custom_build 5ba46ddf8

**OS/device including version:** windows 10

**Issue description:**
the following line crash the editor (copy and paste it in to a script and save it)
```gdscript
extends "res://No"
```
backtrace
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] GDScriptParser::DataType::is_set (C:\dev\__test_env\godot\modules\gdscript\gdscript_parser.h:134)
[1] GDScriptParser::DataType::is_set (C:\dev\__test_env\godot\modules\gdscript\gdscript_parser.h:134)
[2] GDScriptAnalyzer::resolve_inheritance (C:\dev\__test_env\godot\modules\gdscript\gdscript_analyzer.cpp:135)
[3] GDScriptAnalyzer::resolve_inheritance (C:\dev\__test_env\godot\modules\gdscript\gdscript_analyzer.cpp:3084)
[4] GDScriptParserRef::raise_status (C:\dev\__test_env\godot\modules\gdscript\gdscript_cache.cpp:64)
[5] GDScriptAnalyzer::resolve_inheritance (C:\dev\__test_env\godot\modules\gdscript\gdscript_analyzer.cpp:180)
[6] GDScriptAnalyzer::analyze (C:\dev\__test_env\godot\modules\gdscript\gdscript_analyzer.cpp:3111)
[7] GDScriptLanguage::lookup_code (C:\dev\__test_env\godot\modules\gdscript\gdscript_editor.cpp:2945)
[8] ScriptTextEditor::_validate_symbol (C:\dev\__test_env\godot\editor\plugins\script_text_editor.cpp:864)
[9] call_with_variant_args_helper<ScriptTextEditor,String const &,0> (C:\dev\__test_env\godot\core\callable_method_pointer.h:132)
[10] call_with_variant_args<ScriptTextEditor,String const &> (C:\dev\__test_env\godot\core\callable_method_pointer.h:158)
[11] CallableCustomMethodPointer<ScriptTextEditor,String const &>::call (C:\dev\__test_env\godot\core\callable_method_pointer.h:185)
[12] Callable::call (C:\dev\__test_env\godot\core\callable.cpp:50)
[13] Object::emit_signal (C:\dev\__test_env\godot\core\object.cpp:1170)
[14] Object::emit_signal (C:\dev\__test_env\godot\core\object.cpp:1225)
[15] TextEdit::_gui_input (C:\dev\__test_env\godot\scene\gui\text_edit.cpp:2429)
[16] MethodBind1<TextEdit,Ref<InputEvent> const &>::call (C:\dev\__test_env\godot\core\method_bind.gen.inc:867)
[17] Object::call_multilevel (C:\dev\__test_env\godot\core\object.cpp:737)
[18] Object::call_multilevel (C:\dev\__test_env\godot\core\object.cpp:836)
[19] Viewport::_gui_input_event (C:\dev\__test_env\godot\scene\main\viewport.cpp:2309)
[20] Viewport::input (C:\dev\__test_env\godot\scene\main\viewport.cpp:2969)
[21] Window::_window_input (C:\dev\__test_env\godot\scene\main\window.cpp:911)
[22] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\dev\__test_env\godot\core\callable_method_pointer.h:132)
[23] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\dev\__test_env\godot\core\callable_method_pointer.h:158)
[24] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\dev\__test_env\godot\core\callable_method_pointer.h:185)
[25] Callable::call (C:\dev\__test_env\godot\core\callable.cpp:50)
[26] DisplayServerWindows::_dispatch_input_event (C:\dev\__test_env\godot\platform\windows\display_server_windows.cpp:1752)
[27] DisplayServerWindows::_dispatch_input_events (C:\dev\__test_env\godot\platform\windows\display_server_windows.cpp:1729)
[28] Input::_parse_input_event_impl (C:\dev\__test_env\godot\core\input\input.cpp:614)
[29] Input::parse_input_event (C:\dev\__test_env\godot\core\input\input.cpp:440)
[30] Input::flush_accumulated_events (C:\dev\__test_env\godot\core\input\input.cpp:830)
[31] DisplayServerWindows::process_events (C:\dev\__test_env\godot\platform\windows\display_server_windows.cpp:1491)
[32] OS_Windows::run (C:\dev\__test_env\godot\platform\windows\os_windows.cpp:627)
[33] widechar_main (C:\dev\__test_env\godot\platform\windows\godot_windows.cpp:163)
[34] _main (C:\dev\__test_env\godot\platform\windows\godot_windows.cpp:185)
[35] main (C:\dev\__test_env\godot\platform\windows\godot_windows.cpp:199)
[36] __scrt_common_main_seh (d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[37] BaseThreadInitThunk
-- END OF BACKTRACE --

```

### LINKED ISSUE #40985: get_node() with typed variables give Parse Error in neo-GDScript
**Godot version:**

Godot 4.0 master https://github.com/godotengine/godot/commit/ec9302ceccb75f44038db3695d2f9e7c82cfe951

**OS/device including version:**

Windows 10 1809

**Issue description:**

When using `get_node()` or its `$` syntax with typed variables we get ` Parse Error: Value of type "Node" cannot be assigned to variable of type "<any-type-name>"`.

**Steps to reproduce:**
1. Under a root node, add an `ItemList` node.
2. Then use this line in the script for the root node:
```
var item_list : ItemList = $ItemList
```
3. Observe:
```
res://Node2D.gd:90 - Parse Error: Value of type "Node" cannot be assigned to variable of type "ItemList".
modules\gdscript\gdscript.cpp:620 - Method/function failed. Returning: ERR_PARSE_ERROR
```

### LINKED ISSUE #41017: GDScript: can't use constexpr as enum value, but integer literal only
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**

```gdscript
const C = 1
enum E1 { VAL = 1 }

enum E2 {
	VAL1 = C, ## <--- invalid
	VAL2 = E1.VAL, ## <--- invalid
}
```

### LINKED ISSUE #41053: [6831da6] Crash to desktop when waiting for code completion
**Godot version:**
ec678c5e9 _compiled with:_ `$ scons p=x11 CC=gcc-10 CXX=g++-10 AR=gcc-ar-10 RANLIB=gcc-ranlib-10 LINK=g++-10 use_llvm=yes -j8`

**OS/device including version:**
* OS: Arch Linux x86_64
* Kernel: 5.7.8-arch1-1
* Shell: zsh
* Resolution: 1920x1080
* CPU: AMD Ryzen 3 3300X 4- Processor (8) @ 3.8GHz
* Memory: 32040MiB
* GPU: Pulse Radeon RX 5600 XT 6Gio NAVI 10
* Driver: AMD Radeon RX 5600 XT (NAVI10, DRM 3.37.0, 5.7.12-arch1-1, LLVM 10.0.1)
* OpenGL: 4.6 (Compatibility Profile) Mesa 20.1.4

**Issue description:**
Crash to desktop when waiting for code completion under Arch.

**Steps to reproduce:**
1. Open a new project
2. Create and edit a GDScript
3. Enter `@` then wait for the Code Completion
4. Crash to Desktop with stderr: https://gist.github.com/kane-thornwyrd/4aeadd839cd0b0e04e4c9a4e00437251 

**Minimal reproduction project:**
[kane-ui-nav.tar.gz](https://github.com/godotengine/godot/files/5029798/kane-ui-nav.tar.gz)

### LINKED ISSUE #41070: GDScript: crash when typing unary operator at the beginning of a statement
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
```gdscript
func _ready():
    not ## <-- this line crash
```
backtrace
```
[0] GDScriptAnalyzer::reduce_unary_op (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:2529)
[1] GDScriptAnalyzer::reduce_unary_op (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:2529)
[2] GDScriptAnalyzer::reduce_expression (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:1302)
[3] GDScriptAnalyzer::resolve_node (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:755)
[4] GDScriptAnalyzer::resolve_suite (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:852)
[5] GDScriptAnalyzer::resolve_function_body (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:807)
[6] GDScriptAnalyzer::resolve_class_body (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:644)
[7] GDScriptAnalyzer::resolve_program (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:3106)
[8] GDScriptAnalyzer::analyze (C:\dev\godot\modules\gdscript\gdscript_analyzer.cpp:3122)
[9] GDScriptLanguage::complete_code (C:\dev\godot\modules\gdscript\gdscript_editor.cpp:2364)
[10] ScriptTextEditor::_code_complete_script (C:\dev\godot\editor\plugins\script_text_editor.cpp:705)
[11] ScriptTextEditor::_code_complete_scripts (C:\dev\godot\editor\plugins\script_text_editor.cpp:694)
[12] CodeTextEditor::_complete_request (C:\dev\godot\editor\code_editor.cpp:835)
[13] call_with_variant_args_helper<CodeTextEditor> (C:\dev\godot\core\callable_method_pointer.h:136)
[14] call_with_variant_args<CodeTextEditor> (C:\dev\godot\core\callable_method_pointer.h:158)
[15] CallableCustomMethodPointer<CodeTextEditor>::call (C:\dev\godot\core\callable_method_pointer.h:185)
[16] Callable::call (C:\dev\godot\core\callable.cpp:50)
[17] Object::emit_signal (C:\dev\godot\core\object.cpp:1077)
[18] Object::emit_signal (C:\dev\godot\core\object.cpp:1132)
[19] TextEdit::query_code_comple (C:\dev\godot\scene\gui\text_edit.cpp:6416)
[20] CodeTextEditor::_code_complete_timer_timeout (C:\dev\godot\editor\code_editor.cpp:825)
[21] call_with_variant_args_helper<CodeTextEditor> (C:\dev\godot\core\callable_method_pointer.h:136)
[22] call_with_variant_args<CodeTextEditor> (C:\dev\godot\core\callable_method_pointer.h:158)
[23] CallableCustomMethodPointer<CodeTextEditor>::call (C:\dev\godot\core\callable_method_pointer.h:185)
[24] Callable::call (C:\dev\godot\core\callable.cpp:50)
[25] Object::emit_signal (C:\dev\godot\core\object.cpp:1077)
[26] Object::emit_signal (C:\dev\godot\core\object.cpp:1132)
[27] Timer::_notification (C:\dev\godot\scene\main\timer.cpp:61)
[28] Timer::_notificationv (C:\dev\godot\scene\main\timer.h:37)
[29] Object::notification (C:\dev\godot\core\object.cpp:808)
[30] SceneTree::_notify_group_pause (C:\dev\godot\scene\main\scene_tree.cpp:820)
[31] SceneTree::idle (C:\dev\godot\scene\main\scene_tree.cpp:446)
[32] Main::iteration (C:\dev\godot\main\main.cpp:2333)
[33] OS_Windows::run (C:\dev\godot\platform\windows\os_windows.cpp:627)
[34] widechar_main (C:\dev\godot\platform\windows\godot_windows.cpp:163)
[35] _main (C:\dev\godot\platform\windows\godot_windows.cpp:185)
[36] main (C:\dev\godot\platform\windows\godot_windows.cpp:199)
[37] __scrt_common_main_seh (d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[38] BaseThreadInitThunk
-- END OF BACKTRACE --
```

### LINKED ISSUE #41161: Cannot use operator '%' for string formatting if the string is a variable
**Godot version:**
f2149fe763a5678237b417fb9fefec5a5c74ae9d

**OS/device including version:**
Linux Mint 20

**Issue description:**
```py
var format = "%s%s%s"
print(format % ["a", "b", "c"]) # Error
```
```py
print("%s".repeat(3) % ["a", "b", "c"]) # Error
```

**Steps to reproduce:**
Put this code in any script, or test out the MRP

**Minimal reproduction project:**
[Test.zip](https://github.com/godotengine/godot/files/5049115/Test.zip)

### PR DESCRIPTION
**Pull request by vnen**
This fixes some of the reported with the new GDScript code, in particular crashes and regressions (though still not all of them).

Fix #41161
Fix #40740
Fix #41070
Fix #41053
Fix #40826
Fix #40702
Fix #40855
Fix #40650
Fix #40793
Fix #40985
Fix #41017
Fix #23843 (still an issue in 3.2)

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @ThakeeNathees

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by ThakeeNathees** [comment]
seems like `end_statement` is called twice for extending a script path which makes impossible to extend a script path:
https://github.com/godotengine/godot/blob/f568cede8d8a4a3f7051afd2ae8502deb09bc157/modules/gdscript/gdscript_parser.cpp#L529
https://github.com/godotengine/godot/blob/f568cede8d8a4a3f7051afd2ae8502deb09bc157/modules/gdscript/gdscript_parser.cpp#L634

Capture

also if the extends script path is valid and an end of file after that, saving the script cause a crash
(backtrace)
```
[1] GDScriptCompiler::_parse_class_level (C:\dev\godot\modules\gdscript\gdscript_compiler.cpp:2601)
[2] GDScriptCompiler::_parse_class_level (C:\dev\godot\modules\gdscript\gdscript_compiler.cpp:2618)
[3] GDScriptCompiler::compile (C:\dev\godot\modules\gdscript\gdscript_compiler.cpp:2982)
[4] GDScript::reload (C:\dev\godot\modules\gdscript\gdscript.cpp:641)
[5] GDScriptLanguage::reload_tool_script (C:\dev\godot\modules\gdscript\gdscript.cpp:1758)
[6] ResourceFormatSaverGDScript::save (C:\dev\godot\modules\gdscript\gdscript.cpp:2144)
[7] ResourceSaver::save (C:\dev\godot\core\io\resource_saver.cpp:116)
[8] EditorNode::save_resource_in_path (C:\dev\godot\editor\editor_node.cpp:919)
[9] EditorNode::save_resource (C:\dev\godot\editor\editor_node.cpp:937)
[10] ScriptEditor::save_all_scripts (C:\dev\godot\editor\plugins\script_editor_plugin.cpp:2320)
[11] ScriptEditorPlugin::save_external_data (C:\dev\godot\editor\plugins\script_editor_plugin.cpp:3550)
[12] EditorData::save_editor_external_data (C:\dev\godot\editor\editor_data.cpp:391)
[13] EditorNode::_save_scene (C:\dev\godot\editor\editor_node.cpp:1447)
[14] EditorNode::_save_scene_with_preview (C:\dev\godot\editor\editor_node.cpp:1302)
[15] EditorNode::_menu_option_confirm (C:\dev\godot\editor\editor_node.cpp:2265)
[16] EditorNode::_menu_option (C:\dev\godot\editor\editor_node.cpp:1007)
[17] call_with_variant_args_helper<EditorNode,int,0> (C:\dev\godot\core\callable_method_pointer.h:136)
[18] call_with_variant_args<EditorNode,int> (C:\dev\godot\core\callable_method_pointer.h:157)
[19] CallableCustomMethodPointer<EditorNode,int>::call (C:\dev\godot\core\callable_method_pointer.h:184)
[20] Callable::call (C:\dev\godot\core\callable.cpp:50)
[21] Object::emit_signal (C:\dev\godot\core\object.cpp:1077)
[22] Object::emit_signal (C:\dev\godot\core\object.cpp:1132)
[23] PopupMenu::activate_item (C:\dev\godot\scene\gui\popup_menu.cpp:1128)
[24] PopupMenu::activate_item_by_event (C:\dev\godot\scene\gui\popup_menu.cpp:1055)
[25] MenuButton::_unhandled_key_input (C:\dev\godot\scene\gui\menu_button.cpp:49)
[26] MethodBind1<MenuButton,Ref<InputEvent> >::call (C:\dev\godot\core\method_bind.gen.inc:867)
[27] SceneTree::_call_input_pause (C:\dev\godot\scene\main\scene_tree.cpp:885)
[28] Viewport::unhandled_input (C:\dev\godot\scene\main\viewport.cpp:3003)
[29] Window::_window_input (C:\dev\godot\scene\main\window.cpp:915)
[30] call_with_variant_args_helper<Window,Ref<InputEvent> const &,0> (C:\dev\godot\core\callable_method_pointer.h:132)
[31] call_with_variant_args<Window,Ref<InputEvent> const &> (C:\dev\godot\core\callable_method_pointer.h:157)
[32] CallableCustomMethodPointer<Window,Ref<InputEvent> const &>::call (C:\dev\godot\core\callable_method_pointer.h:184)
[33] Callable::call (C:\dev\godot\core\callable.cpp:50)
[34] DisplayServerWindows::_dispatch_input_event (C:\dev\godot\platform\windows\display_server_windows.cpp:1764)
[35] DisplayServerWindows::_dispatch_input_events (C:\dev\godot\platform\windows\display_server_windows.cpp:1740)
[36] Input::_parse_input_event_impl (C:\dev\godot\core\input\input.cpp:614)
[37] Input::parse_input_event (C:\dev\godot\core\input\input.cpp:440)
[38] Input::flush_accumulated_events (C:\dev\godot\core\input\input.cpp:830)
[39] DisplayServerWindows::process_events (C:\dev\godot\platform\windows\display_server_windows.cpp:1504)
[40] OS_Windows::run (C:\dev\godot\platform\windows\os_windows.cpp:627)
[41] widechar_main (C:\dev\godot\platform\windows\godot_windows.cpp:163)
[42] _main (C:\dev\godot\platform\windows\godot_windows.cpp:185)
[43] main (C:\dev\godot\platform\windows\godot_windows.cpp:199)
[44] WinMain (C:\dev\godot\platform\windows\godot_windows.cpp:212)
[45] __scrt_common_main_seh (D:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[46] BaseThreadInitThunk
[47] RtlGetAppContainerNamedObjectPath
-- END OF BACKTRACE --
```

@vnen

**Comment by vnen** [comment]
@ThakeeNathees for one second I thought this was introduced in this PR, but it was already there before. I'll check that later.

**Pull request merged**
