### PR TITLE
Invalid color picker values fixed

### LINKED ISSUE #19652: Color picker wrong hex value
**Godot version:** 3.0 and 3.0.1 and commit ff01fd57bc19d9f4cb3929dbee87cdd9eda578e1

**Issue description:**
Color picker color has wrong hex value of the color 

**Steps to reproduce:**
1.Select color using color picker
2.Use "to_html" function in gdscript
3.Some colors return wrong value

**Minimal reproduction project:**
[ColorBug.zip](https://github.com/godotengine/godot/files/2116295/ColorBug.zip)

### PR DESCRIPTION
**Pull request by maksloboda**
This fixes #19652 
Now test project(included in the issue) shows correct values for hex, rgba32, argb32 and abgr32

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks, the fix seems fine. Could you squash the two commits together? (and maybe edit the commit log to be a bit more specific, e.g. "Fix float Color conversions to int types")

**Comment by maksloboda** [comment]
Squashed and renamed

**Review by akien-mga — APPROVED** [review]

**Comment by maksloboda** [comment]
I think i know what the issue is

**Comment by akien-mga** [comment]
I think the error is a false positive, I'll clean up the cache.

**Comment by maksloboda** [comment]
Everything looks good

**Comment by akien-mga** [comment]
Thanks!

**Comment by aaronfranke** [comment]
I've added the rounding fixes to the C# math in my over-two-month-old C# Color math fix PR: https://github.com/godotengine/godot/pull/18282

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.

**Comment by aaronfranke** [comment]
Related: #4960

**Pull request merged**
