### PR TITLE
Allow creating .gitignore and .gitattributes when creating a new project

### LINKED ISSUE #1813: Allow creating `.gitignore` and `.gitattributes` files when creating a new project
**Describe the project you are working on:**

This is relevant for any project that uses Git for version control. It would be nice for myself to have these automatically created, however I am also concerned about other people's projects (see next point).

**Describe the problem or limitation you are having in your project:**

`.gitignore` files are (practically but not technically) necessary for Git repositories if you want to prevent Git from tracking and committing generated files. Also, `.gitattributes` is nice to have since we can tell Git to handle line endings properly. I always remember to add these files in my own projects, but it would be nice if it wasn't necessary.

I am a maintainer on the Godot Asset Library. I often see people forgetting to put proper gitignore files in their projects when posting their projects on GitHub and accidentally committing files they shouldn't like the `.import/` folder. Also, I occasionally see people accidentally having carriage returns in their projects, which is a mistake caused by having Git configured incorrectly.

There was also [some concern about possible confusion](https://github.com/godotengine/godot-proposals/issues/1521#issuecomment-697575796) with the `.godot/` folder.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

We can solve all of the above issues by having Godot automatically create these files when creating new projects. It will be easier for users who know about these files since Godot will handle it for you and you don't need to copy anything manually, it will make it harder for users who don't know about these files to forget them since (again) Godot will handle it for you, and it will avoid confusion of what should and shouldn't be ignored because (yet again) Godot will handle it for you.

For people who aren't using Git, these files are useless, but also they are harmless and extremely small (total 116 bytes) and of course it's super easy to delete them. We can also allow disabling their creation (as the below PR does).

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Branch: https://github.com/aaronfranke/godot/tree/gitignore-create

PR: https://github.com/godotengine/godot/pull/42447

3.2 backport (may or may not actually end up in 3.2): https://github.com/aaronfranke/godot/tree/3.2-gitignore-create

The PR makes the creation of these files be optional in the project creation dialog. You can also create them from inside an existing project using the new "Create Version Control Metadata" button.

I also threw in the ability to disabling the creation of the default environment, since it was in mostly the same part of the code.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This can be easily worked around by copying the appropriate files into your project.

**Is there a reason why this should be core and not an add-on in the asset library?:**

Since this ideally would happen in every project when creating new projects, it would be best to do in core. Of course, it can be worked around easily for each individual project, but some users will forget to do this.

### PR DESCRIPTION
**Pull request by aaronfranke**
Implements and closes https://github.com/godotengine/godot-proposals/issues/1813.

Many people either forget to make `.gitignore` files, or make them incorrectly, or make them correctly but not until after they committed files that shouldn't be committed. There was also [some concern about possible confusion](https://github.com/godotengine/godot-proposals/issues/1521#issuecomment-697575796) with the `.godot/` folder. We can solve all of these problems by having Godot automatically create a `.gitignore` file.

This PR also has Godot automatically create a `.gitattributes` file. It's a subset of [the one in the main repo](https://github.com/godotengine/godot/blob/master/.gitattributes). This doesn't include any manual definitions for binary files, but I think it's safe to assume Git >2.10 now (2.11 came out in 2016).

For people who aren't using Git, these files are useless, but also they are harmless and extremely small (total 116 bytes), and there is a dropdown menu where you can disable their creation. In the future, this dropdown menu could be expanded to have more types of metadata for different version control systems.

Note: This gitignore doesn't include `.translation`, so this PR expects that #42392 will be merged (but the PRs shouldn't conflict).

This can be [cherry-picked to 3.x if desired](https://github.com/aaronfranke/godot/tree/3.2-gitignore-create), but we will have to include [the rest of the 3.x ignores](https://github.com/aaronfranke/gitignore/blob/godot/Godot.gitignore) too.

```
$ cat .gitignore
# Godot 4+ specific ignores
.godot/
$ cat .gitattributes
# Normalize EOL for all files that Git considers text files.
* text=auto eol=lf
```

EDIT: The files are now optional, they can be disabled in the project creation dialog:

Screenshot from 2020-11-13 03-58-54

### CODE REVIEW

**Comment by timothyqiu** [comment]
AFAIK, it's a bit strange to require `eol=lf` on Windows.

`text=auto` alone can make sure that line endings are normalized to LF in the repository. `eol=lf` makes all text files in the working directory to use LF line endings, which is unnatural on Windows.

**Comment by artism90** [comment]
I'm opposed to having possibly useless files as a default in each single project directory, no matter the size. On the other hand, the majority probably uses git anyway or doesn't care that much about some clutter. But still, Godot is open to be used with different VCS and I find it bothersome of an application to assume for me, what I might need.

I'd rather like to see this as a part of an optional "project template" setup to pre-create most common project structures with VCS integration or not.

**Comment by Calinou** [comment]
I'm in favor of this, since these files will be hidden by default on macOS and Linux. On Windows, we might be able to set the "hidden" attribute ourselves in the future.

While it is possible to use other version control systems with Godot, the overwhelming majority of users I know of use Git. This goes from gamejam developers to medium-sized indie studios :slightly_smiling_face:

**Comment by Xrayez** [comment]
I have a Python package [`gdgen`](https://github.com/Xrayez/gdgen) which allows you to generate C++ modules with `git` initialized, but that's only because it's something which is not provided by Godot *officially* (I cannot recall whether it's possible to override this in `gdgen` currently, if not, then that should be a bug).

On the other hand, we have plugins like https://github.com/godotengine/godot-git-plugin semi-officially maintained:

> Git implementation of the Godot Engine VCS interface in Godot.

Godot seems to have the API for implementing various VCS providers. So Godot can decide to officially support `git` on that level.

> I'd rather like to see this as a part of an optional "project template" setup to pre-create most common project structures with VCS integration or not.

Semi-related proposal: godotengine/godot-proposals#1481. I mean, this could be potentially made configurable via the project manager checkboxes:

- Project name: `Godot`
- Project path: `/home/godot/projects/new_project`
- [ ] Initialize with `git`.

**Comment by aaronfranke** [comment]
@timothyqiu As discussed [here](https://github.com/godotengine/godot-proposals/issues/897), it's best to use LF everywhere with Godot.

@artism90 I forgot to mention that it is extremely trivial to delete these files if you don't want them.

**Comment by akien-mga** [comment]
> I'd rather like to see this as a part of an optional "project template" setup to pre-create most common project structures with VCS integration or not.

I agree. There should be a possibility to initiate an actual Git repo with those files (like e.g. `cargo new` would do for a Rust project), and possibly adding support for other popular VCS systems with their own relevant configuration files.

**Comment by aaronfranke** [comment]
Maybe there should be a checkbox in editor settings for this?

Also, this reminds me, it would be nice if there was a way to access editor settings in the project manager.

**Comment by timothyqiu** [comment]
> As discussed here, it's best to use LF everywhere with Godot.

I think what config Godot uses and what config a godot project uses are two different things.

Unlike using LF in the repository, using CRLF line ending in the working directory won't cause any trouble. It's just a matter of the repository owner's taste.

The Godot team is Linux native. It's reasonable for the team to choose forcing LF everywhere to minimize the trouble in its own repository, even though the choice is kind of an anti-pattern, allowing to copy the directory directly between Linux and Windows instead of using Git to fetch the source code.

Rust also uses `* text=auto eol=lf` in the Rust repository itself, and `cargo new` generates .gitignore but not .gitattributes, leaving the option to the user.

**Comment by aaronfranke** [comment]
I updated this PR so that these files are now optional, and it's easy to disable their creation in the editor settings. I also took the opportunity to allow disabling the creation of `default_env.tres`, since developers who work primarily in 2D usually don't need an environment in their projects (see [this PR](https://github.com/godotengine/godot-demo-projects/pull/488)).

Screenshot from 2020-10-02 02-28-08

With everything disabled, an empty project only has `project.godot` (required), `icon.png`, `icon.png.import`, and the `.godot/` folder. If desired, I guess we can also allow disabling the creation of `icon.png` too, and then an empty project would be just this:

```properties
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=4

_global_script_classes=[  ]
_global_script_class_icons={
}

[application]

config/name="Empty"
```

**Comment by aaronfranke** [comment]
I discussed this with some people on Discord and it seems that there are indeed some people who would find this annoying, so I changed this PR to have these new settings **disabled by default**.

In the future if it's decided that we should have this setting enabled by default, it would be easy to make a follow-up PR for that, but in the meantime this PR in its current state can only benefit people since the default behavior is the same.

**Comment by asheraryam** [comment]
I am really happy about this PR, but I would like to argue against having it Off by default.

It doesn't matter if there are *some* people who find it annoying, the majority of people use git for version control and it makes more sense to provide sensible defaults that cater to most users, not the outliers.

Are there other scenarios reasons against a .gitignore file? (Other than "we don't use git for version control").

Also not that the Cocos Creator engine also provides a .gitignore by default on project creation (and its very widely popular), so there is precedent.

**Comment by pycbouh** [comment]
> It sucks for those "some people" but that's what sensible defaults mean.

It is not sensible, though, that this option is hidden in the editor settings, in an unrelated to VCS section. This should be a project creation step with an optional editor top menu item to recreate those files after the initial project creation if they have been omitted (or if it is an existing project).

Which VCS somebody uses is very situational and personal thing, and just because there is a trend in OSS community doesn’t mean we should make this harder to configure. More than that, this setting may vary per project inside of the same team.

So unless this is an option like “Create git repository” available at project creation, then this is an unwelcome change. With a room to introduce other popular VCSs later, if course. The default state can be made configurable in the editor settings, if needs be.

**Comment by asheraryam** [comment]
@pycbouh I'm fine with making it an option during project creation (and remembering the choice per-user locally for future projects). As long as I can make it init git by default I don't really care how visible the option is.

**Comment by aaronfranke** [comment]
@pycbouh Adding these options absolutely does not make any VCS system harder to configure. With non-Git VCS systems, even if these checkboxes were enabled by default, the files are harmless and super easy to delete.

I disagree that this change is unwelcome if there isn't also a way to initialize a Git repository, I think these are separate issues. I made this PR to try and solve real world problems people have, where people put a Godot project on GitHub and they are missing these important files. On the other hand, it is impossible for people to put a project in a GitHub repository without a Git repository, so people needing Godot to create a Git repository is not the real world problem I'm trying to solve with this PR, and is a separate issue.

**Comment by pycbouh** [comment]
@aaronfranke You've misunderstood me completely...

My point was about making this new addition configurable at the project creation screen instead of hiding it somewhere in the editor settings, and in a section that has nothing to do with VCS at that. It was suggested by 3 other people before me that we should be able to tick this as we are making a new project, and putting this setting into a menu inaccessible unless you open a project is making it harder to configure than it needs to be. I am not against adding these options, if you make them easy to disable for a particular project.

Which is why I suggest adding a toggle saying something like "Create/Initialize git repository" to the project creation window, as well as adding this as an action to the top editor menu (say, below the "Project" item) so people can initialize the repository for existing projects as well. And of course this should be implemented in a way that would allow adding other VCSs in the future. So it's not so much "Init git" but "Init a VCS" with git as the only currently available option. Also that option as well as whether or not do it by default at all should be remembered and configured for future projects as asheraryam says.

And I wasn't saying that me must initialize the repo for this PR to be welcome. I wasn't making any distinctions between simply creating those two files and fully initializing the repo. If you'd like to just create two files in the first iteration of this, do that. I was saying that this PR is in my opinion unwelcome if you don't provide an option to prevent this action from happening from the project creation screen, that's it.

**Comment by aaronfranke** [comment]
@pycbouh I'm concerned that this is a slippery slope that could lead to the project creation popup having tons of checkboxes, as it is now your idea would add four of them (init git repo, create gitignore, create gitattributes, create default environment). I think a better idea would be to allow [editing the editor settings from inside the project manager](https://github.com/godotengine/godot-proposals/issues/1602), so that you can enable/disable the creation of these files without first opening a project (and maybe later also allow creating a Git repo).

**Comment by pycbouh** [comment]
First of all, everything Git related should be under one checkbox here. There is almost no need for such granularity as you describe. In fact it's that granularity that can be put into the editor settings, but the action should be toggled from the creation screen with just one checkbox. And when we add more VCSs, it will be just a drop list alongside that checkbox.

Secondly, no need fear-mongering with the slippery slope, we are fully capable of making a judgement on what settings should or shouldn't go there. They can even exist in a collapsible section, so that they don't take space unless you know you want to configure them.

Ultimately, this is a setting that differs for each individual project, it makes sense to make a call the moment you create them, not fiddle with the whole set of editor settings just to create a single project. That's an unnecessary complicated way to handle a forced feature that has nothing to do with Godot. It's very presumptuous to assume that because a lot of people use Git, others must be inconvenienced and required to seek out a hidden setting or to remove files afterwards. I don't want to say that there are bad intentions, but many comments here assume that it's an okay approach because it aligns with their behavior when using this software. I don't think that ignoring the needs of so called "some people" is a correct way to handle this feature.

**Comment by nathanfranke** [comment]
Version control should not be an option in "Create Project" since it adds unnecessary complexity for new users. However, this functionality is still extremely important so what about an entry in Project Settings?

What do we think about this?
image

As for specific edge cases, switching from "Git" to "None" could put a warning that says "All custom Git configuration will be deleted"

**Comment by pycbouh** [comment]
> What do we think about this?

This was the initial implementation by Aaron, and the one I commented on and am against of for the reasons stated above.

**Comment by nathanfranke** [comment]
> > What do we think about this?
> 
> This was the initial implementation by Aaron, and the one I commented on and am against of for the reasons stated above.
> 
> As for superficial complexity for new users, I suggested adding them under a fold, so they are not overwhelming to those who don't seek them.

I agree that this should not be in Editor Settings, but I am proposing it should be in *Project* Settings. Therefore, the concern of multiple projects with different settings is not valid.

**Comment by nathanfranke** [comment]
> Edit: Oh wait, you mean project settings instead of editor settings? But the problem at hand is that people need to be able to create those files with the project. So if it is on by default, my argument against it still stands same as it was for editor settings. If it is off by default, then the problem at hand is not really solved.

People don't need to create them with the project. It's possible that someone wants to start using version control weeks after they originally created the project.

I don't think it should be on by default. If it is off by default then the user can just enable it.

**Comment by pycbouh** [comment]
> People don't need to create them with the project.

As far as I understand, this is exactly the problem @aaronfranke is trying to solve, though. This PR does support creating VCS files after the fact as well, by the way.

An option is added to this menu (not shown):
image

that pops up this window, that does the same thing:
image

**Comment by nathanfranke** [comment]
In that case, I agree that this change is mostly redundant, since one can simply do Project->Version Control. However, I think that the functionality in Project->Version Control should be moved to Project Settings.

**Comment by aaronfranke** [comment]
@nathanfranke It doesn't make sense to put this in project settings. It's not a setting you toggle on or off, it's not something that gets put in `project.godot`, the only way that you would need to check the state of this is by checking if the files exist and what their contents are.

The purpose of the setting in the project creation popup is that it's important for users to create these files when the project, and we don't want users to forget about them, since many people do. If we had to remove one, I would prefer to remove the one in the editor, but we can have both, and it's a neat feature to have.

If there is a strong concern about keeping this window simple (I was initially concerned about this), we could make it hidden under "advanced" or something, but as it is now it's actually pretty simple since @pycbouh suggested that we don't need the granularity of toggling each of the files (which makes sense in retrospect).

**Review by nathanfranke — APPROVED** [review]
Looking back at this, definitely a good idea! Let's merge it for 4.0 so Aaron can stop rebasing :smiley:

**Review by Calinou — APPROVED** [review]
Wasn't `default_env.tres` removed in the `master` branch recently? Other than that, this looks good to me (not tested locally yet).

**Comment by aaronfranke** [comment]
@Calinou It still exists (might not be intentional?). Here's what a new project created on the latest master looks like:

Screenshot from 2021-03-19 20-26-10

**Comment by ChronicallySerious** [comment]
One of the reasons why https://github.com/godotengine/godot-git-plugin was made into a different plugin was that the editor was supposed to be kept as VCS agnostic as possible.

However, it is true that most users use Git, so the initial implementation of the VCS interface was done for Git. The Git plugin actually takes care of creating a `.gitignore` and a `.gitattributes` file with contents as mentioned [here](https://github.com/godotengine/godot-git-plugin/blob/master/godot-git-plugin/src/git_api.cpp#L97) if those are not already present, as well as takes care of initialising the file system with a `.git` folder (akin to running `git init`). 

So should this functionality just be implemented by the VCS interface implementations (plugins) or is it fine if the editor implements the same thing again? Because using Git specific terms in the plugin implementation is expected but using them in the editor break that kind of VCS agnosticism built in it.

**Comment by aaronfranke** [comment]
@ChronicallySerious If you take a closer look, there is a dropdown menu that allows selecting either Git or None. Any other metadata files for other version control systems can easily be added. However, I haven't used anything other than Git.

Someone who uses Git with Godot may use a separate client and therefore not want full blown support in the editor, but they still need these metadata files, and it can't be expected that third-party clients create them. This means that either Godot does it, or users have to hunt them down manually, or they forget.

Another possibility is that users start with command-line Git and only install the Godot Git plugin later. In which case, it's too late for the plugin to create these files - some gitignored files may have already been committed and have to be deleted manually.

**Comment by reduz** [comment]
What is the resolution on this one? do we have full consensus to merge? Also devault_env.tres and related should be removed, it's no longer needed in Godot 4.

**Comment by aaronfranke** [comment]
@reduz Some people are against it but most are in favor.

As for removing `default_env.tres`, if we are doing that, then we should do that first. We can keep this PR on hold for now until that's done and then I can rebase this PR later.

**Comment by Calinou** [comment]
> EDIT: No, default_env.tres is still required. It's not necessary in the editor due to the preview environment, but for running a project without a default environment with only a Camera3D in it just displays a gray sky. So we still need this. I think having a checkbox for it in the project creation popup (as in this PR) is better than leaving that space empty in the project creation popup.

This should be resolved differently (such as by printing a warning message by scanning the scene tree for a WorldEnvironment node).

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
