### PR TITLE
Add memo property for line_edit

### PR DESCRIPTION
**Pull request by sanikoyes**
Add memo property for line_edit
this useful for user input tip

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Note that this is called placeholder in HTML.

@sanikoyes Also, can you make the memo color configurable?

**Comment by vnen** [comment]
> Note that this is called placeholder in HTML.

And I think it should be called the same in Godot too. I don't know what "memo" means.

**Comment by sanikoyes** [comment]
ok, i renamed memo to placeholder

**Comment by akien-mga** [comment]
Could you squash the three commits together?

**Comment by sanikoyes** [comment]
close, new pr: https://github.com/godotengine/godot/pull/5449

**Pull request closed without merging**
