### PR TITLE
Fix infinite loop when calling `Control.popup_centered_minsize()`

### LINKED ISSUE #60326: Freeze when running `AcceptDialog.popup_centered_minsize`
### Godot version

3.5.beta.custom_build. 20b08185f

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

```
	var temp_variable207 = AcceptDialog.new()
	add_child(temp_variable207)
	temp_variable207.popup_centered_minsize(Vector2(-NAN, -NAN))
	temp_variable207.queue_free()
```
cause freeze here
```
#0  0x0000000004aaa53f in Variant::operator int (this=0x7fffffffccc0) at core/variant.cpp:1095
#1  0x0000000003a80e68 in Control::get_theme_item_in_types<int> (p_theme_owner=0x0, p_data_type=Theme::DATA_TYPE_CONSTANT, p_name=..., p_theme_types=...)
    at scene/gui/control.cpp:836
#2  0x0000000003a63dbb in Control::get_constant (this=0xce37050, p_name=..., p_theme_type=...) at scene/gui/control.cpp:1000
#3  0x0000000003a9c65d in AcceptDialog::get_minimum_size (this=0xce37050) at scene/gui/dialogs.cpp:469
#4  0x0000000003a5d458 in Control::_update_minimum_size_cache (this=0xce37050) at scene/gui/control.cpp:184
#5  0x0000000003a5d563 in Control::get_combined_minimum_size (this=0xce37050) at scene/gui/control.cpp:203
#6  0x0000000003a650c0 in Control::_size_changed (this=0xce37050) at scene/gui/control.cpp:1194
#7  0x0000000003a5e0d3 in Control::_update_minimum_size (this=0xce37050) at scene/gui/control.cpp:282
#8  0x000000000190d4c0 in MethodBind0::call (this=0x9dc5790, p_object=0xce37050, p_args=0x0, p_arg_count=0, r_error=...) at ./core/method_bind.gen.inc:59
#9  0x0000000004a25250 in Object::call (this=0xce37050, p_method=..., p_args=0x0, p_argcount=0, r_error=...) at core/object.cpp:918
#10 0x0000000004a1b6fe in MessageQueue::_call_function (this=0x7133570, p_target=0xce37050, p_func=..., p_args=0x7fffe6e39350, p_argcount=0, 
    p_show_error=false) at core/message_queue.cpp:241
#11 0x0000000004a1b9ff in MessageQueue::flush (this=0x7133570) at core/message_queue.cpp:284
#12 0x00000000039c2009 in SceneTree::idle (this=0xa437ab0, p_time=0.0666666701) at scene/main/scene_tree.cpp:616
#13 0x000000000188d72c in Main::iteration () at main/main.cpp:2271
#14 0x000000000184df5a in OS_X11::run (this=0x7fffffffd5a0) at platform/x11/os_x11.cpp:3842
#15 0x0000000001839b0b in main (argc=2, argv=0x7fffffffded8) at platform/x11/godot_x11.cpp:55

```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### LINKED ISSUE #60376: `BaseButton.set_custom_minimum_size`cause freeze and crashes app
### Godot version

4.0.alpha.custom_build. 5974e1432

### System information

Ubuntu 21.10 - Nvidia GTX 970, Gnome shell 40.4 X11

### Issue description

```
	var temp_variable2521 = BaseButton.new()
	add_child(temp_variable2521)
	temp_variable2521.set_custom_minimum_size(Vector2(-NAN, -NAN))
```

```
Failed method: BaseButton::_update_minimum_size

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.custom_build (690fefe43ee74c0ae3ed5642f3aefbeb711f9d1c)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f22dd63d520] (??:0)
[2] Callable::get_object() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/callable.cpp:100)
[3] MessageQueue::statistics() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:154)
[4] MessageQueue::push_callablep(Callable const&, Variant const**, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:122)
[5] MessageQueue::push_callp(ObjectID, StringName const&, Variant const**, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:45)
[6] MessageQueue::push_callp(Object*, StringName const&, Variant const**, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:104)
[7] Error MessageQueue::push_call<>(Object*, StringName const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/message_queue.h:112)
[8] Control::update_minimum_size() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:2923 (discriminator 2))
[9] Control::_update_minimum_size_cache() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:233)
[10] Control::get_combined_minimum_size() const (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:239)
[11] Control::_size_changed() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:1453)
[12] Control::_update_minimum_size() (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/gui/control.cpp:332)
[13] void call_with_variant_args_helper<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:241 (discriminator 4))
[14] void call_with_variant_args_dv<__UnexistingClass>(__UnexistingClass*, void (__UnexistingClass::*)(), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:384)
[15] MethodBindT<>::call(Object*, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:334)
[16] Object::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:839 (discriminator 1))
[17] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/variant/callable.cpp:62)
[18] MessageQueue::_call_function(Callable const&, Variant const*, int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:230)
[19] MessageQueue::flush() (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/message_queue.cpp:277)
[20] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:454)
[21] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:2722)
[22] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:356)
[23] godot4(main+0x16c) [0x2378ab2] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:70)
[24] /lib/x86_64-linux-gnu/libc.so.6(+0x29fd0) [0x7f22dd624fd0] (??:0)
[25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x7d) [0x7f22dd62507d] (??:0)
[26] godot4(_start+0x2e) [0x237888e] (??:?)
-- END OF BACKTRACE --
================================================================

```

### Steps to reproduce

Above

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Calinou**
This salvages https://github.com/godotengine/godot/pull/60340. Thanks @sriramun for the original fix :slightly_smiling_face:

*Bugsquad edit:*
- Fixes #60326
- Fixes #60376

### CODE REVIEW

**Comment by AaronRecord** [comment]
Seconding timothyqiu's comment, wouldn't it be better to have this be checked in the setter instead?

**Comment by AaronRecord** [comment]
Seconding timothyqiu's comment, wouldn't it be better to have this be checked in the setter instead?

**Comment by KoBeWi** [comment]
Seems like the original issue is not relevant for master, because the method was removed and I can't reproduce the issue with other methods (popups aren't even controls anymore).

**Comment by akien-mga** [comment]
> Seconding timothyqiu's comment, wouldn't it be better to have this be checked in the setter instead?

That's what the current commit does. Which setter do you mean if not `set_custom_minimum_size()`?

> Seems like the original issue is not relevant for master, because the method was removed and I can't reproduce the issue with other methods (popups aren't even controls anymore).

The 3.x bug report is the same bug as #60376 for 4.0, and this is still reproducible:
```gdscript
var b = Button.new()
add_child(b)
b.custom_minimum_size = Vector2(NAN, NAN)
```
crashes.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.

**Pull request merged**
