### PR TITLE
Add an editor setting to import resources while unfocused

### LINKED ISSUE #3252: Add an editor setting to import resources even when the editor window isn't focused
### Describe the project you are working on

The Godot editor :slightly_smiling_face: 

### Describe the problem or limitation you are having in your project

Import times can be slow in complex 3D projects, especially on slower machines.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add an editor setting to (re)import resources in the editor as soon as possible, without waiting for the user to focus the editor window again.

**Upsides:**

- Reimporting is done sooner, which leads to faster iteration times. In many cases, reimporting will be finished before you even refocus on the editor window.

**Downsides:**

- Increased CPU usage, which may decrease battery life and steal CPU time from other (potentially demanding) applications. This is why it should be disabled by default :slightly_smiling_face: 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Checking for files to reimport is currently handled here: https://github.com/godotengine/godot/blob/18c0f0b3ba46caf3f6dda401362bc5993eaf7f8d/editor/editor_node.cpp#L630-L636

When the **Import Resources When Unfocused** editor setting is enabled, the editor should still attempt to import resources when focusing the editor window, but it should also have a timer that scans for file modifications every few seconds. (If there's already a pending import operation, it will continue to run.)

The scanning needs to be done relatively frequently to actually improve iteration times, but it shouldn't be done too often to avoid unnecessarily increasing CPU usage. Popular polling frequencies for this purpose are between 1 and 3 seconds.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No, as triggering the reimport on filesystem changes needs to be done by the editor itself.

### Is there a reason why this should be core and not an add-on in the asset library?

This is core editor functionality.

### PR DESCRIPTION
**Pull request by Calinou**
This can be used to speed up iteration by starting the import process earlier when saving files in the project folder. This also allows getting visual feedback on changes without having to click the editor window, which is useful with multi-monitor setups.

The downside is that this increases idle CPU usage and may steal CPU time from other applications when importing resources, so this is disabled by default.

This needs testing in various workflows, especially 3D ones with large scenes that can take a while to export. We need to make sure Godot doesn't try to import partially written files.

- This closes https://github.com/godotengine/godot-proposals/issues/3252.

### CODE REVIEW

**Comment by akien-mga** [comment]
How will this behave when resources depend on each other? For example a .gltf with external textures. If it starts importing as soon as it sees the first file being added, it will likely fail.

**Comment by Calinou** [comment]
> How will this behave when resources depend on each other? For example a .gltf with external textures. If it starts importing as soon as it sees the first file being added, it will likely fail.

I could see this being an issue already with the current import system (if you focus the editor while a large glTF scene with separate textures is being written by a 3D DCC), but this will indeed be a more common occurrence with this setting enabled.

We should probably have a way to reject an import as "postponed" in this case if it doesn't fulfill certainc onditions.

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected. I've changed the reimport timer from 1.0s to 0.5s to make reimporting quicker too.

**Review by passivestar — APPROVED** [review]
Works as expected on my end. Tested on a file with a bunch of beefy 4k textures

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Is it intended that the periodic scan is also performed when the editor is still in focus?

**Comment by Calinou** [comment]
> Is it intended that the periodic scan is also performed when the editor is still in focus?

I don't know. It *is* possible for an external app to update a resource in the Godot project while the editor is focused. Does this work correctly when the editor is focused currently (when the new setting is disabled)? Ideally, this should always work regardless of this setting.

**Comment by lyuma** [comment]
I am particularly concerned about instances where godot reads an incomplete file while it is being written. A classic example is exporting a large fbx or gltf from blender and then switching to godot before it is finished writing. Except now it could happen at any time.

in godot this can be very dangerous because it could refresh the scene while importing the broken file and lose data

**Pull request merged**
