### PR TITLE
Add Show In FileManager to project manager

### PR DESCRIPTION
**Pull request by sersoong**
You can get to the project directory quickly.
test

### CODE REVIEW

**Comment by Noshyaar** [comment]
Related #14952

**Comment by poke1024** [comment]
Exactly, so I'm not the only one :-)

**Comment by sersoong** [comment]
Easy to manager projects.
@poke1024

**Comment by akien-mga** [comment]
That makes the buttons too wide.

**Comment by sersoong** [comment]
"Show In File Manager" has translation po.
It can be used in other languages.

**Comment by sersoong** [comment]
Maybe the button can be designed as a autowarp mode.
This is just a suggestion.

**Comment by akien-mga** [comment]
I think "Show Files" or "Show Folder" would be better.

**Comment by sersoong** [comment]
Then use 'Show Folder' for it.

**Comment by sersoong** [comment]
Fixed!

**Comment by akien-mga** [comment]
I think the last proposal in #14952 might be nicer, WDYT?

**Comment by sersoong** [comment]
I agree.Then use it in his way.
All I need is this feature.
No matter how it is done.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by akien-mga** [comment]
Closing this one as we'll merge #14952 instead for 3.1 (and likely backport it for 3.0.x), but thanks for the contribution!

**Pull request closed without merging**
