### PR TITLE
[3.x] Add ability to pick random value from array

### PR DESCRIPTION
**Pull request by BleedingXiko**
Backport of https://github.com/godotengine/godot/pull/67444.

### CODE REVIEW

**Comment by akien-mga** [comment]
The best would even be to have used `git cherry-pick -x 9f4dbf415da6d150788915cb35a9c3dc7f04c547` to do a proper cherry-pick commit of #67444, keeping @nonunknown as the author. There would be a few conflicts to resolve as done in this PR, which can be amended into the cherry-pick commit. Then you can also give yourself some credit for the backporting work by adding `Co-authored-by: Your name <your email>` at the end of the backported commit's message.

**Comment by BleedingXiko** [comment]
alright I squashed the commits, I tried doing the cherry pick to have @nonunknown as the author but it wouldn't stay when I would squash again.

**Comment by akien-mga** [comment]
Thanks! Yeah doing a cherry-pick after the fact in the branch where you already have the backport would be tricky. I went ahead and applied some Git magic to restore the author/date from the original PR, and added you as co-author :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by BleedingXiko** [comment]
Sweet! 😁

**Comment by oeleo1** [comment]
This is nice. Thanks! Lots of code with the pattern `array[randi() % array.size()]` will get replaced by this.

**Comment by oeleo1** [comment]
@BleedingXiko @akien @Calinou Can we have the same for dicts too? Or is it too much asking?

**Comment by oeleo1** [comment]
Sorry @akien, I meant @akien-mga. Mea culpa.

**Comment by YuriSizov** [comment]
@oeleo1 Dictionaries have a less clear use-case, since they are a collection of key-value pairs, not an indexed list of values. It probably needs a new proposal, or at least a PR implementing it to start a new discussion.

Also, please don't leave multiple comments in the row, this creates multiple notification for maintainers and anyone else subscribed to this repository. Use the edit button instead.

**Comment by oeleo1** [comment]
Thanks for your response. I see your point, but in my mind, and in practical terms, the use case is clear had the method been called `get_random` instead of `pick_random`. It's a shortcut of the pattern `array/dict.get(randi() % array/dict.size())`.

Consequently, for dictionaries, this method would be a shortcut of the `dict[randi() % dict.keys().size()]. This is obviously an optimization we have lived without for years, but since the `pick_random` for arrays has made it to the core, it is appreciated, and deemed quite useful. Experience shows that the same pattern for dicts is a common use case.

**Comment by oeleo1** [comment]
> It probably needs a new proposal, or at least a PR implementing it to start a new discussion.

Agreed, but we focus on game making and deliberately refrain from entering the PR business, so all I can offer is an opinion from our experience at face value. Up to the dev team / volunteers to pick up on that or not. We won't complain either way as it's not our territory :-)

**Pull request merged**
