### PR TITLE
Adds Engine::is_editor_hint() method

### PR DESCRIPTION
**Pull request by neikeq**
It's sometimes desired to check this before the main loop is initialized. In my case, I need to check this somewhere in `ScriptLanguage::init()`, in order to know which assemblies to load.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Well, we might remove SceneTree::is_editor_hint() then, no?

**Comment by neikeq** [comment]
This is actually wrong. It will return false for the project manager, or when using commands like `-export` and `-import`. I will discuss this on IRC to see if we can find a proper solution.

**Comment by reduz** [comment]
this is cool, but I would replace all usages of get_tree().is_editor_hint() for this..

**Comment by neikeq** [comment]
All right, should be fine now.

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
