### PR TITLE
[3.x] SkeletonEditorPlugin backport

### LINKED ISSUE #3562: Deleting a node deletes all animation tracks referencing that node.
I noticed this while working on a game for Global Game Jam this past weekend. Say you have an animation set up in the animation player, and you are referencing a node that exists in the current scene file; If you then delete that node, any tracks that reference it will also be deleted.

I can see how this might make sense, but I found myself in a situation where I lost a good chunk of work:

I had a item–a sword specifically–attached to the player, and was animating it from the player scene. I later decided that it should be a pickup and removed it from the player, deleting several animations. Since you can create animations that reference a node path that doesn't exist, and then add the node via script at run time, I had assumed this would work, but instead wound up having to redo my work.

Given that we can create an animation with an invalid path, and that the engine will provide a helpful error if the path isn't valid at runtime, should Godot not keep the animation tracks? Or ask before deleting them?

### LINKED ISSUE #35652: Editor freeze when clicking Skeleton node of a glTF scene with 500+ bones
**Godot version:**
3.2 rc 4

**OS/device including version:**
macos 10.15.2
*Issue description:**
[New Game Project.zip](https://github.com/godotengine/godot/files/4121086/New.Game.Project.zip)

**Steps to reproduce:**
open BAQIR-RIG.glb  click armature_baq node,editor freeze

**Minimal reproduction project:**

*Bugsquad edit (keywords for easier searching): select, selecting, crash*

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
This PR is a backport of the SkeletonEditorPlugin that @fire created, with the modifications I added for Godot 4.0. I tested and everything seems to be working like it does in the Godot 4.0/master version.

Closes #35652 and supersedes #39090
Edit: Fixed the linked issue. I accidentally had the wrong one.

### CODE REVIEW

**Comment by fire** [comment]
```	// Create Top Menu Bar
	options = memnew(MenuButton);
	SpatialEditor::get_singleton()->add_control_to_menu_panel(options);

	options->set_text(TTR("Skeleton"));
	options->set_icon(EditorNode::get_singleton()->get_gui_base()->get_icon("Skeleton", "EditorIcons"));

	options->get_popup()->add_item(TTR("Create physical skeleton"), MENU_OPTION_CREATE_PHYSICAL_SKELETON);

	options->get_popup()->connect("id_pressed", this, "_on_click_option");
	options->hide();```

Removing the hide was patched in https://github.com/godotengine/godot/pull/39543

**Comment by TwistedTwigleg** [comment]
> Removing the hide was patched in #39543

Fixed!

**Comment by mbrlabs** [comment]
What's the status on this? Now that 3.2.3 is out can this be merged now?

**Comment by akien-mga** [comment]
If any of the skeleton-involved coredevs can have a look at this before Halloween, that's be great ;)

@TwistedTwigleg Needs a rebase to solve merge conflicts.
I'd also suggest amending the last commit's message to use a more impersonal style (instead of "Backported the improvements to the SkeletonInspector that I made in my Godot 4.0 PR", it should be something like "Backport SkeletonInspector improvements from #39353" (if that's the one). That's more concise and more informative. It's still fine to say "I" in commit logs but this pertains more to in-depth explanations in the body of the commit message than its title.

**Comment by fire** [comment]
Reviewing the code:

> `emit_signal("skeleton_updated");`

Should be done like

>			emit_signal(SceneStringNames::get_singleton()->pose_updated);

But it's not this pr.

**Comment by fire** [comment]
Re-based and merged in the upstream `emit_signal("skeleton_updated");` change.

Renamed commit to  `Backport SkeletonInspector improvements from 39353`.

Waiting on cicd.

**Comment by TwistedTwigleg** [comment]
Thanks @fire for rebasing (and renaming) this PR! I am currently working through the rest of my PRs and rebasing them with master :+1:

**Comment by RevoluPowered** [comment]
Can you please make sure to co-author @marstaik?

I needed this plugin today while working, I will ask in IRC if this can be prioritised

**Comment by TwistedTwigleg** [comment]
Sure, though I have no idea how to add authors or co-authors... :sweat_smile:

**Comment by Zireael07** [comment]
*poke* I just realized this hasn't made it into 3.4, when will it be in?

**Comment by TwistedTwigleg** [comment]
I'm not sure, I honestly forgot I had this PR.

One thing with this PR that I'm not sure on, and may be an issue with merging it, is how old the code is compared to the skeleton inspector code in Godot 4.0. This PR is based on what is now pretty old code, since the PR was made during GSOC 2020. I'm not sure how many improvements have been made to the skeleton inspector since, but I imagine this code has several bugs that have been fixed in Godot 4.0. This makes me hesitant to recommend merging this PR. It may be easier and better to see if how difficult it would be to port the Godot 4.0 skeleton inspector to Godot 3.x, so it has the latest fixes and improvements.
(Though I have no idea how much effort or time it would take)

This PR also has some merge conflicts currently, though I took a quick glance and they don't seem too major.

**Comment by Zireael07** [comment]
Whatever the implementation/form this finally takes, I am very much in need of moving some bones around in a 3.x project... it doesn't need to be perfect at first attempt, in fact I'd happily test with the project I have in mind.

**Comment by TwistedTwigleg** [comment]
This PR only adds the inspector for the bones, I do not think it adds anything for modifying them. I think it *might* allow for editing the bone child-parent order by drag-and-dropping the bones, but otherwise I believe it's just a different way to visualize the bones from list that is displayed when selecting a Skeleton.

How do you need to move the bones around? Depending on the use case, you might be able to use [Twisted IK 2](https://twistedtwigleg.itch.io/twistedik2)'s Twisted_Bone3D node to modify the positions of the bones. It applies the position using the global pose override, but it should be modifiable to adjust the `rest`, `pose`, or `custom_pose` depending on what you need.

**Pull request closed without merging**
