### PR TITLE
Use `constexpr` in the conditions with template parameters and `sizeof`s to suppress C4127 warnings.

### PR DESCRIPTION
**Pull request by bruvzg**
Part of https://github.com/godotengine/godot/issues/66537

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by rburing — APPROVED** [review]

**Comment by akien-mga** [comment]
Seems like this fix is uncovering other warnings:
```
core/io/image.cpp: In instantiation of 'void _scale_cubic(const uint8_t*, uint8_t*, uint32_t, uint32_t, uint32_t, uint32_t) [with int CC = 1; T = short unsigned int; uint8_t = unsigned char; uint32_t = unsigned int]':
core/io/image.cpp:1213:79:   required from here
core/io/image.cpp:643:29: error: variable 'k2' set but not used [-Werror=unused-but-set-variable]
  643 |  double ox, oy, dx, dy, k1, k2;
      |                             ^~
```

**Comment by bruvzg** [comment]
> Seems like this fix is uncovering other warnings

It's probably being only used in some of `constepr` branches and should be either move into it or marked as `[[maybe_unused]]`.

**Comment by akien-mga** [comment]
Thanks!

**Comment by lawnjelly** [comment]
I have to say I find myself wondering, does this warning have any actual valid use? As in does it help identify bugs?

It seems a bit like a "captain obvious" warning here. :grinning: 

And I guess we need to balance between adding too much superfluous c++ BS in the code, making it more difficult to read. I mean, of course template parameters and sizeof are constants. That's pretty much in their definition?

**Comment by lawnjelly** [comment]
Yeah that would seem more valid .. but flagging template parameters and sizeof seems like a problem with the warning. Apparently it used to flag up `while (true)` as problematic and they changed it because so many people complained.

They should really separate it into a warning for irrelevant stuff that people can turn off, and possibly relevant stuff that people can turn on.

Just trying to voice some complaint! :grin:

**Pull request merged**
