### PR TITLE
Add option to convert project from Project Manager

### LINKED ISSUE #4801: Add option to convert 3.x projects to 4.0 from Project Manager
### Describe the project you are working on

Godot etc

### Describe the problem or limitation you are having in your project

Godot 4.0 has lots of compatibility-breaking changes. If you open your old Godot 3 project in 4.0, it will be immediately rendered unusable in the old version and saving any scene will potentially cause data loss.

We already have some code here and there that tries to keep some compatibility with the old projects, but adding more such code (like https://github.com/godotengine/godot/issues/44820 suggests for example) is not worth it in the long run.

Instead we have an official built-in project converter that does really good job in upgrading the old scenes and code to make them more usable and prevent data loss from incompatible properties. It's great, because it's self-contained and doesn't require redundant code code all over the codebase. The only problem is that the converter can only run from CLI. Most non-advanced users might not be aware about the magnitude of changes; they will just randomly open their small project and possibly break it. We should make converting more convenient, so that anyone can easily run the converter if they are upgrading the project.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Godot already detects when a Godot 3 project is opened in 4.0 - it will display a warning. My proposal is to point to the converter in that warning and offer an option to automatically convert the old project.

The converter option could also be a button in Project Manager's sidebar, although that's less useful when you don't have Godot 3 projects on the list.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The warning we have now already mention converting, but it doesn't use the converter - it just updates `project.godot` to a new format. We could either make it use the converter or add a button to run full project conversion:
image

### If this enhancement will not be used often, can it be worked around with a few lines of script?

You'd need a custom project manager.

### Is there a reason why this should be core and not an add-on in the asset library?

Must be core as it helps migrating projects.

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/4801

This is rather bare-bones implementation. It just opens a new dialog with a warning and runs the converter in the background. But IMO it's still better than hiding this option behind CLI.

https://user-images.githubusercontent.com/2223172/186914420-6fca21e0-fb47-4f53-8123-e3ba54e129bd.mp4

### CODE REVIEW

**Comment by jgillich** [comment]
Useful feature, but the initial dialog is confusing, it's not clear what the difference between "OK" and "Perform Full Project Conversion" is.

**Comment by qarmin** [comment]
https://github.com/godotengine/godot/pull/64396 will add two optional arguments - maximum file size and maximum line length, so I think that would be add them also here to be able to easily configure converter.

Since progress is visible command line, maybe better is to run converter with `headless` argument to not show new Godot window.

**Comment by bend-n** [comment]
What if there is a visual progress bar too?

**Comment by Calinou** [comment]
> What if there is a visual progress bar too?

Drawing the progress bar may be more trouble than it's worth, but I suppose the window title could be changed to indicate progress.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
