### PR TITLE
Replace use of `OS::set_exit_code()` by `SceneTree::quit()` in `EditorNode`

### PR DESCRIPTION
**Pull request by touilleMan**
see https://github.com/godotengine/godot/pull/56877#issuecomment-1015254892

### CODE REVIEW

**Comment by akien-mga** [comment]
I think you meant to reference `OS::get_singleton()->set_exit_code()` in the commit log and not `quit()`?

**Comment by touilleMan** [comment]
@akien-mga I've updated the PR

**Comment by akien-mga** [comment]
Thanks! I think the two commits could be squashed as the latter is a clarification of why the former was needed (and we tend to favor somewhat bigger commits over extremely atomic ones).

**Comment by touilleMan** [comment]
@akien-mga squashed !

**Comment by mhilbrunner** [comment]
Looks good! Undecided on whether having `EXIT_SUCCESS` be the default would be cleaner instead of having it be explicit everywhere. Lets see what Akien thinks.

**Comment by akien-mga** [comment]
> Looks good! Undecided on whether having `EXIT_SUCCESS` be the default would be cleaner instead of having it be explicit everywhere. Lets see what Akien thinks.

I think "fail by default" is good, as there's more ways for the engine to exit with a failed state than to exit cleanly.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
