### PR TITLE
Fixed Z-axis logic since -Z is forward

### LINKED ISSUE #48832: ViewportRotationControl focuses on opposite view when clicking the Z axis (front instead of rear and vice versa)
**Godot version:**

3.3.1

**OS/device including version:**

Windows 10

**Issue description:**

The compass visible in 3D, called ViewportRotationControl in source, has an incorrect behavior when the Z axis is clicked to focus on front/rear view. After single press it focuses the view in opposite direction, (front instead of rear and vice versa). Second click on Z axis does nothing. X and Y axes are working correctly.

**Steps to reproduce:**
1. Open any scene in 3D in which front, rear, left, right directions can be easily distinguish.
2. Position the camera to face front
3. Press Z axis on the compass, notice it focused on rear instead
4. Press Z axis again, notice nothing happened
5. Press X axis and compare the behavior.

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by greatmomo**
Should fix #48832 

The FRONT and REAR behavior was flipped because -Z is forward

### CODE REVIEW

**Comment by aaronfranke** [comment]
This was already fixed in #45669, the current behavior in master is correct.

**Comment by akien-mga** [comment]
> This was already fixed in #45669, the current behavior in master is correct.

This PR wants to change it back it seems. Nobody seems to agree on what Front and Rear view means.

**Comment by JFonS** [comment]
The issue was not in the way the front and rear views were applied, but in the fact that the Z "buttons" in the rotation gizmo triggered the wrong view. I opened #48895 with another fix for the issue.

**Comment by akien-mga** [comment]
Superseded by #48895. Thanks for the contribution nevertheless!

**Pull request closed without merging**
