### PR TITLE
add `project` method to Vector2/3

### LINKED ISSUE #17199: Add API to project Vector3 to a plane or another vector
**Godot version:**
`master` / 3d03bcd0636aacfe530c52fc1cdc32c2edffea04

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
It is often needed when creating a 3D game, to find out a projection of a vector on a plane (represented by its normal) or on another vector:
 * http://www.euclideanspace.com/maths/geometry/elements/plane/lineOnPlane/index.htm

Some other engines provides a method to easily calculate a projection to either on another vector or on a plane, so it'd be nice if Godot also supported such a feature:

_Example_: Unity's API

 ```c#
public static Vector3 Project(Vector3 vector, Vector3 onNormal);
```
```c#
public static Vector3 ProjectOnPlane(Vector3 vector, Vector3 planeNormal);
```

### PR DESCRIPTION
**Pull request by karroffel**
closes #17199

### CODE REVIEW

**Comment by reduz** [comment]
I would use Plane instead, seems a lot less confusing than adding a function to Vector3. I don't like the idea that we should implement the API in a certain way because Unity does.

**Comment by karroffel** [comment]
@reduz for `Vector2` the code already existed, also this should be a lot cheaper than going through a plane conversion.

I made this PR because this functionality is required in a project and it seems a bit unfit for a GDScript implementation and seems like it should be there.

**Comment by reduz** [comment]
If you guys really want it, i dont mind, but just name it project, not project_onto.

**Comment by akien-mga** [comment]
You'll have to rebase, it's trying to readd the whole math_2d which was split into more files.

**Pull request merged**
