### PR TITLE
Ctrl+Clicking a enum now scrolls down to it in the docs.

### PR DESCRIPTION
**Pull request by Outrider0x400**
Origin Issue [#17396](https://github.com/godotengine/godot/issues/17396)

The original issue actually described at least three bugs that I know of.

1. The first example provided by @Zylann 
Clicking `NOTIFICATION_ENTER_WORLD` simply does not trigger the whole docs functionality, which I believe is a bug within the keyword detection part.

2. The second and third examples provided by @Zylann
These enums are detected and relevant pages are opened. But they do not scroll down to the relevant position.

3. Sometimes the wrong page is opened.
If you Ctrl+Click `PI` the page `@GlobalScope` would be opened while `PI` is not part of that scope, according to the docs.

This PR fixes the second issue.

### CODE REVIEW

**Comment by Falke117** [comment]
A little bit [demo](https://www.youtube.com/watch?v=73Zb6x1LYPw&feature=youtu.be)

**Comment by Falke117** [comment]
I reworked the fix today, because I thought the previous solution is a bit workaround. (Have the `EditorHelp::_help_callback` search through the enum list if the search in the constant list fails)

So apprently Juan have already wrote functions to search through the enum fields of the class in `class_db`, but is only compiled if `DEBUG_METHODS_ENABLED` is true, and not currently used when identifying the nature of an identifier.

So by invoking these functions in `GDScriptLanguage::lookup_code`, it now can distinguish enum from constants. But, another issue remains that these functions don't work for "@GlobalScope". So the previous workaround is kept and that routine is only used when the indentifer belongs to the global scope.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Might be worth closing #17396 and opening new issues for the use cases that still don't work after this fix?

**Comment by Falke117** [comment]
> Might be worth closing #17396 and opening new issues for the use cases that still don't work after this fix?

I agree. Since I believe the other two use cases are caused by different reasons. I can create two new issues for these two cases tomorrow if needed?

**Pull request merged**
