### PR TITLE
Update TextEdit select and select_all method descriptions

### PR DESCRIPTION
**Pull request by slofy**

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Note: please try to group related documentation changes in the same commit if you plan to make several in a row, it's simpler to review and merge a bulk of changes at once than individual ones (especially since CI checks take hours right now due to a huge number of PRs being updated in recent days).

**Comment by slooths** [comment]
Will do, sorry about that.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
