### PR TITLE
Fix antialiasing for beginning/end of line in `canvas_item_add_polyline`

### PR DESCRIPTION
**Pull request by Chaosus**
This PR adds AA to the beginning/end (horizontal) border on the line + adds corners to prevent artifacts:

image

image

This would fix (partially): https://github.com/godotengine/godot/issues/57882 (I didn't touch Line2D since it uses a different method to draw, maybe later I would fix it too in another PR)

### CODE REVIEW

**Comment by maiself** [comment]
Could `border_size` be set to `1.0`?

`2.0` looks a bit blurry to me and `1.0` matches 3.x better.

**Comment by Calinou** [comment]
> 2.0 looks a bit blurry to me and 1.0 matches 3.x better.

You may want to consider setting it to `0.625` by default, which (empirically) results in good antialiasing while keeping lines sharp.

**Comment by Chaosus** [comment]
@maiself, @Calinou Maybe adding an extra parameter would be better? - then the user will control the size of the border of AA.

**Comment by Chaosus** [comment]
> Could border_size be set to 1.0?

Done

**Comment by Calinou** [comment]
> @maiself, @Calinou Maybe adding an extra parameter would be better? - then the user will control the size of the border of AA.

That would be nice to support, but I still think the default should be more conservative to look more crisp :slightly_smiling_face:

**Review by Calinou — APPROVED** [review]

**Pull request merged**
