### PR TITLE
New icons for Gradient and GradientTexture resources

### PR DESCRIPTION
**Pull request by gongpha**
These new icons will look consistent with another icon.

### Old
ภาพ
ภาพ
### New
ภาพ
ภาพ

Edit : Wait for #42855 to be merged first.

### CODE REVIEW

**Comment by akien-mga** [comment]
The GradientTexture icon looks good, but the Gradient icon is too similar to GradientTexture with the rectangular outline which only differs by a few pixels.

**Comment by Calinou** [comment]
Maybe GradientTexture's gradient could be flipped to be in the opposite direction?

**Comment by gongpha** [comment]
Sounds good, Or should Gradient's icon rotate like an old one ?

**Comment by gongpha** [comment]
Modified.

ภาพ
ภาพ

**Comment by Xrayez** [comment]
I'm not sure whether `GradientTexture2D` is going to be merged at all in Godot: #42855, but then I'm not sure what should be the icon for 2D texture, perhaps the old icon of `GradientTexture` should be the new icon for `GradientTexture2D`? 😃

In any case, that's something I'd like to implement in either case (in [Goost](https://github.com/goostengine/goost)), so worth to discuss the design in relation to 2D texture.

**Comment by gongpha** [comment]
@Xrayez When will the #42855 be merged ?

**Comment by Xrayez** [comment]
@gongpha godotengine/godot-proposals#1677 has to be officially approved first, technically could be merged right now, but there are other limitations which would be good to resolve to make it robust: #43015.

**Comment by gongpha** [comment]
@Xrayez Meanwhile, I made a local commit with `GradientTexture2D`'s icon. I designed it to look different from `GradientTexture`. But I still use grey as an icon color like the original one. Because it doesn't associate with Node2D nodes.

However, I will sit here for #42855. When it ready, I will push them here. 🙂

**Comment by Xrayez** [comment]
@gongpha just letting you know that I've added `GradientTexture2D` in [Goost](https://github.com/goostengine/goost) with goostengine/goost#43, for now I'm just using the same `GradientTexture` icon in [`editor/icon_gradient_texture_2d.svg`](https://github.com/goostengine/goost/blob/gd3/editor/icons/icon_gradient_texture_2d.svg), so feel free to contribute there as well. 🙂

Of course I'd still prefer #42855 to get merged too.

**Comment by gongpha** [comment]
@Xrayez I'm currently working on these icons. I read your commits in [goostengine/goost#43](https://github.com/goostengine/goost/pull/43). I saw that your changes include radial gradient and I'm still hesitating with these icons. You can help me pick one with the best fit for its purpose !

ภาพ

**Comment by Xrayez** [comment]
@gongpha thanks, I think the diagonal one is a good fit, this signifies that linear gradient can have arbitrary direction in 2D. The linear gradient is the default one so it's not necessary to have a radial icon displayed (many other types could be implemented in the future as well...)

image

**Comment by gongpha** [comment]
Current :

ภาพ
ภาพ

**Comment by Calinou** [comment]
What I'd do is the following:

- Keep the proposed GradientTexture icon as-is.
- Remove the border around Gradient entirely, keeping only the filled and dithered area.

**Review by Calinou — APPROVED** [review]

**Comment by Calinou** [comment]
The new icons look easy enough to distinguish to me.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
