### PR TITLE
Fix shader crash if non-boolean expression inserted into "if"

### LINKED ISSUE #33118: if (float) doesn't cause error in gd shader
**Godot version:** v3.2.alpha0.official

**OS/device including version:** Ubuntu 18.04.3

**Issue description:** If you write code in godot's shading language that looks like this:

```
if (100.0) {
   
}
```

Then, the code will appear to save without any errors in the godot editor. Upon actually running the game, the resulting glsl will fail to compile. This should be an error in the godot editor upon saving the file.

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #33118

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
So `if (1)` is not valid in GLSL?

**Comment by Chaosus** [comment]
Yeah, it leads to crash - you can test this on shadertoy

**Comment by Chaosus** [comment]
image

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
