### PR TITLE
Added VS2013 CE solution

### PR DESCRIPTION
**Pull request by ex**
NOTE: run build.bat at least once before building.
It needs manual updating of the project and right now is only configured for DEBUG mode.

### CODE REVIEW

**Comment by akien-mga** [comment]
I'm not a VS user myself so I might be mistaken, but I get the feeling that it's a bit overkill to add IDE-specific projects files in the main source tree that will only cater to 32bit build in debug mode, for VS 2013 CE and not other versions, and need to be updated manually. From my experience in other projects, this is typically the kind of files that slowly become unusable as the main buildsystem evolves and the main devs don't take care of updating those IDE specific-files.

IIRC, there is a "vsproj" option in the scons buildsystem that could be used to generate project files for VS that would be in sync with the current buildsystem. It might not be working properly judging by recent bug reports, but maybe it would be better to fix it than workaround the issue by providing project files for every VS version currently in use?

**Comment by ex** [comment]
Well, I find debugging form VS very useful, I'll add the missing RELEASE config and can maintain this project updated as long as I'm testing the engine. Others can do it also, is not that hard.
The SCons autogenerated project seemed to have some limitations as far as I read. Never get it to work though (when it worked)

**Comment by akien-mga** [comment]
As per the above arguments, I'll close this one as I don't think that it would be a good addition. We don't want to start maintaining custom project files for every possible IDE, so either we can generate them using scons, or we won't.

**Comment by Griefchief** [comment]
I know this is archived, i just want to note that i might be able to get a vsproj=yes to generate a good nmake config for scons (basically vsvarsall.bat x86 && scons etc in nmake build settings)... but will need to check.

It's the next on my to do list. It's just some info.

I'll definitely take a look at this work here and see if can get debug link stuff going properly as well, so that debuging works through the vsproj as well, so thank you for your work @ex, i think it might prove very usefull indeed after all :)  (as I'm not a debuger expert in VS yet) :)

**Pull request closed without merging**
