### PR TITLE
Add String support for GDScript Enums

### LINKED ISSUE #20988: Add String-based Enum support to GDScript
**Godot version:**
Godot 3.1

**Issue description:**
1. GDScript enums are not allowed to be string values.
2. You can have exported string values with the PROPERTY_HINT_ENUM flag that are string values.

ergo, if strings are types that support enum representation in the editor, then GDScript should logically support me creating enums of that type.

**Steps to reproduce:**

    enum Types {
        # This line currently creates an error because enums must be integers
        TYPE_FIRE = "Fire",
        TYPE_ICE = "Ice",
    }
    var type
    func _get_property_list():
        return [
            {
                "name": "type",
                "type": TYPE_STRING,
                "hint": PROPERTY_HINT_ENUM,
                # Rather than re-iterating the list or creating an explicit mapping const dictionary,
                # I should be able to just directly use the values array of a string enum
                "hint_string": PoolStringArray(Types.values()).join(",")
            }
        ]

What do you guys think?

### PR DESCRIPTION
**Pull request by willnationsdev**
Fixes #20988.

This PR also makes it possible to create enum value assignment using a colon (Dictionary syntax) in addition to the equals sign (original enum syntax). Since these effectively create Dictionaries anyway, it makes sense to allow either syntax for this purpose rather than arbitrarily erroring on the Dictionary syntax.

### CODE REVIEW

**Comment by willnationsdev** [comment]
Just tested this on my machine with both "=" and ":". Seems like it's all working, and I just fixed all of the syntax check errors (some weren't even made by me, so I'm not sure how they managed to get into my build).

**Comment by akien-mga** [comment]
@vnen Could you have a look at this PR?

Will need a rebase eventually.

**Comment by akien-mga** [comment]
We discussed this on IRC with @vnen and @bojidar-bg, and agreed that this proposal and the related issue are likely not the right approach to solve a valid issue (getting a string from an (int) enum value). Logs:
```
15:07 <Akien> Next: #21014
15:07 <IssueBot> #21014: Add String support for GDScript Enums | https://git.io/fNNKC
15:07 <bojidar_bg> NB: I'm biased towards close here
15:07 <Akien> I'm not sure we should have this feature in the first place either.
15:08 <bojidar_bg> it might make enum-typed parameters harder to implement
15:09 <vnen> I don't think it's needed. I see it as a solution to a lack in the language somewhere else
15:10 <bojidar_bg> Also, it will break with export(Enum)
15:10 <vnen> for instance, it should be easier to get the name from an enum value
15:10 <bojidar_bg> (ah, nevermind my last message)
15:11 <Akien> Yeah, being able to get the enum identifier as a string would be quite nice.
15:11 <Akien> It seems like this PR only means to address the inconsistency between having enum String hints in exports, which map to int values
15:12 <vnen> I do: `MY_ENUM.keys()[enum_value]`, but that doesn't work with custom assignments
15:13 <bojidar_bg> Maybe something like Dictionary.reverse() which builds a dictionary by swapping the key and value in each entry?
15:14 <bojidar_bg> or, something like what I've done in the asset library: enums which have both the string key -> integer value mapping and the integer value -> string key; this would allow for doing `MY_ENUM[enum_value]` directly
15:15 <Akien> Note that it would also be useful to retrieve string names from built-in enums and constants, like converting Error codes to something user readable.
15:16 <bojidar_bg> Well, another option would be to have a Variant::Enum type which contains an integer and enum name/dictionary/?
15:17 <bojidar_bg> ... which would basically be a Symbol/StringName-like type with a custom lookup table..
15:18 <vnen> I guess we agree to close the PR, we can discuss a solution later
15:18 <bojidar_bg> we should probably close the issue as well, and find another one for the discussion
```

@bojidar-bg Can I let you open the follow-up issue?

**Comment by Razzlegames** [comment]
Just curious if there has been any follow up issue created for this? @akien-mga @bojidar-bg  ?  Thanks

**Comment by Razzlegames** [comment]
Nevermind.  Found it and linking here for easier reference: https://github.com/godotengine/godot/issues/31896

**Pull request closed without merging**
