### PR TITLE
Fixed argument names having wrong order for atan2

### PR DESCRIPTION
**Pull request by Piet-G**
The arguments of atan2() should be y,x instead of x,y This was just wrong since the internal atan2 already had y,x as parameters, so if you followed the autocomplete your result would just be wrong.

### CODE REVIEW

**Comment by akien-mga** [comment]
Oh no, not this one again :D

@StraToN Can I let you dig up the relevant discussion issues/PRs? :)

**Comment by akien-mga** [comment]
Well if it's just about auto-complete / documentation this change might be correct though.

**Comment by DualMatrix** [comment]
Yeah this PR doesn't change functionality. Just fixes the visible parameter names

**Comment by akien-mga** [comment]
Thanks, looks fine then.

**Pull request merged**
