### PR TITLE
Add export_resource_uid annotation

### LINKED ISSUE #9216: Add ResourcePath to refer to a resource without preloading it
### Describe the project you are working on

N/A

### Describe the problem or limitation you are having in your project

There's no project-friendly way to reference resources without preloading them. There's a plain string with `@export_file` tag, but that's fragile and ineffective.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

A new type called ResourcePath that the editor will track as if it were tracking an actual Resource.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
# declare it manually and the editor could list as a dependency for the script
const res_1: ResourcePath = "res://thing.res"
const res_2: ResourcePath[Mesh] = "uid://..."

# or set the path from the inspector
@export var my_scene: ResourcePath[PackedScene]

func load_my_scene_on_demand():
  ResourceLoader.load_threaded_request(my_scene)
  # ...
  var s: PackedScene = ResourceLoader.get_threaded_request(my_scene)
  add_child(s.instantiate())
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a simple and obvious way to manage resource loading. It should be a core feature.

### LINKED ISSUE #9552: Add a Resource to handle project files/directories references
References my open discussion https://github.com/godotengine/godot-proposals/discussions/9545#discussion-6524297

### Describe the project you are working on

An RPG game, where any of the adjacent rooms are loaded at runtime

### Describe the problem or limitation you are having in your project

Each of the rooms needs to keep the reference to the adjacent rooms as a string path, but the only way assign file paths to a property is by passing a string representing it. You can use an attribute hint to make it easier:

```c#
[Export(PropertyHint.File)] // or [Export(PropertyHint.Dir)]
public string pathToResource; //or pathToPackedScene, or pathToDir
```
but it's still not possible to keep track of files/directories which get renamed or moved.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

If you use a resource directly, the engine is able to keep track of it even when renamed or moved inside the editor, i'd like to implement something similar but limiting this feature to keep track of a (project) resource path (or directory), to give the developer a way to manually handle each resource (when load/unload them, and how to do it, for example using other threads to load some scenes and resources) 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

- This functionality should be added as a new resource type (something like `Path`), which only takes a string as its member fields.

- The user should be able to pass a file/directory into this resource from the editor, and the latter should be tracked by the editor and updated whether it gets moved or renamed from inside the editor.

- The user should be able to access the file path as a string with a method

- It should be possible to view the preview of the resource (such as the image thumbnail or similar)

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can't be worked around. The only way to achieve the same result is by manually changing each of the references to a certain file/directory when moved/renamed (which is not convenient at all, in particular when you are moving a large amount of file into a new location, and might lead to some of the references to be null if you forget to manually update them)

### Is there a reason why this should be core and not an add-on in the asset library?

It should improve the editor usability, as it's a missing core funcionality

### PR DESCRIPTION
**Pull request by huwpascoe**
Resource UIDs can now be selected from the inspector in the same way a Resource would be selected.

EditorResourcePicker has new path_only property to facilitate the annotation that hides menu items unrelated to UID selection.

Example usage:
```
@export_resource_uid("ResourceTypeName") var item : int

func load_item() -> ResourceTypeName:
	return load(ResourceUID.get_id_path(item))
```

Closes https://github.com/godotengine/godot-proposals/issues/9216
Closes https://github.com/godotengine/godot-proposals/issues/9552

### CODE REVIEW

**Comment by AThousandShips** [comment]
You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

**Comment by huwpascoe** [comment]
> You used a merge commit to update your branch, please use rebase in the future instead, see [here](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase)

Oh how I am trying. I managed to rebase and then ended up 300 commits behind master because I have no idea. I'll get it eventually.

**Comment by huwpascoe** [comment]
Okay it just keeps getting worse. I can reset back to the fixup commit, and then rebase from there, and on the local, it looks completely fine.
```
f990b0850d (HEAD) HEAD@{0}: rebase (fixup): Added export_resource_uid annotation
d6c1efb23b HEAD@{1}: rebase (start): checkout HEAD~2
```
See no problem.


But then when I push it... Yeah. It's broken, it's completely broken
```
remote: Resolving deltas: 100% (1263/1263), completed with 352 local objects.
```

*shrug* Git's gonna git I guess. I'll have to fall back to ol' reliable:  Recreate the entire commit manually and start a new pull request.

**Comment by huwpascoe** [comment]
https://github.com/godotengine/godot/pull/91815

**Pull request closed without merging**
