### PR TITLE
Specify description of `Array.slice`s end parameter

### PR DESCRIPTION
**Pull request by HaSa1002**
I was looking for that info and had none.
So, I did what you do when no info is available. You test behaviour 😅 
```gdscript
func _ready():
	var arr := ["y", "y", "e", "s"]
	for letter in arr.slice(1,-1):
		printraw(letter) # prints yes
```

### CODE REVIEW

**Comment by LightningAA** [comment]
> I was looking for that info and had none.
> So, I did what you do when no info is available. You test behaviour 😅
 
Or you read the source code: https://github.com/godotengine/godot/blob/master/core/variant/array.cpp#L322

I wonder if `slice()` should print a warning if `sign(end - start) != sign(step)`

**Comment by HaSa1002** [comment]
> Or you read the source code: master/core/variant/array.cpp#L322

Yeah that would have been an option, but testing was faster.

**Comment by LightningAA** [comment]
> > Or you read the source code: master/core/variant/array.cpp#L322
> 
> Yeah that would have been an option, but testing was faster.

Reading the source code is nice though because it shows you if there are any nuances with how it works

**Comment by HaSa1002** [comment]
Yes, I know and thanks for the link btw. I may shouldn't have opend the PR in the first place as I am in the middle of work on a project and just wanted to quickly note, my findings. I will rephrase the end description and include a note on both step and deep as well. But I don't know if I will do that today. So if you are bored feel free to do the work and I will close this PR.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
This is okay as is, thanks - its an improvement :)
Feel free to submit a PR for `deep` as well, but `step is already described`.

Thanks again - and no worries, don't stress yourself out. :)

**Comment by kleonc** [comment]
> This is okay as is, thanks - its an improvement :)

Actually added information:
> If [code]end[/code] is an invalid value, the end of the array is used.

is incorrect. For example:
```
var arr := ["y", "y", "e", "s"]
print(arr.slice(1, -5))
```
prints `[]`, not `[y, e, s]` as that added sentence suggests. @HaSa1002 tested some specific case and wrote an incorrectly generalized conclusion based on it. As @LightningAA suggested, looking into the source code is the way to properly determine the actual behavior of that method.

**Comment by mhilbrunner** [comment]
@kleonc Thanks for the ping, you're right, looking at the code this isn't exactly right - will do a PR to change the docs.

Seems slice should indeed have more checks.

**Pull request merged**
