### PR TITLE
Increase checkerboard texture contrast

### LINKED ISSUE #57891: Make ColorPicker/ColorPickerButton alpha checkerboard use the same contrast as the gradient editor's
### Godot version

v3.4.2.stable.official [45eaa2daf]

### System information

Windows 10

### Issue description

When make a transparent gradient the colors items do not match the preview at the top? The last item in the list is fully transparent and invisible... yet is is displayed as "fully" white with the transparent check pattern virtually invisible, and items higher on list are shown with more transparency though they have less?

The items in this list should basically match the preview at the top?

Thanks.

[](https://postimg.cc/xkD4pPx5)

### Steps to reproduce

-  create new Gradient, set Color 1 to transparent, and refresh by selecting a differnt node then the Gradient again (https://github.com/godotengine/godot/issues/33265)
-  add a bunch of new points, and refresh
-  note that last item in list does not appear fully transparent, and items further up list appear more so?

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Geometror**
Increases the contrast of the checkerboard background used at several places in the editor (restores it to the value used some time ago). Also removed the unused color_picker_sample icon and cleaned up redundant linecap attributes in the SVGs.

This makes it easier to distinguish small transparency gradations:

Closes #57891.

Current master:
grafik

This PR:
grafik

### CODE REVIEW

**Comment by akien-mga** [comment]
You should also remove the theme property's entry from the docs.

**Comment by pycbouh** [comment]
Should probably add `GuiMiniCheckerboard` to the list of color exceptions so that it doesn't get converted. Also may be worth to still use a similar color from the palette, `#808080`, instead of a custom color.

**Comment by Geometror** [comment]
@pycbouh Implemented the suggested changes.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
