### PR TITLE
Fixed bullet area vs Trimesh shape overlap

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixes: #16392

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by EzraT** [comment]
Thank you!

**Comment by NewNodeGames** [comment]
Areas with concave shapes are not detected by bodies connecting signals.

**Comment by AndreaCatania** [comment]
it's fine, because the area can't use a concave shape. A solution is to create it using more primitive and convex shape together

**Pull request merged**
