### PR TITLE
fix auto-generated GDN API header for C compilers

### PR DESCRIPTION
**Pull request by Evrey**
The new GDNative API structs have a little C semantic error. This struct does not compile, unless you are using a C++ compiler:

```C
typedef struct godot_gdnative_api_struct { // [1]
	unsigned int type;
	godot_gdnative_api_version version;
	const godot_gdnative_api_struct *next; // [2]
} godot_gdnative_api_struct; // [3]
```

The problem is that for C, every variable of type `struct S` has to be written out as `struct S`, unless re-defined using a `typedef`. Now, the declaration of `godot_gdnative_api_struct` is at line `[1]`, a variable of that type is declared at line `[2]`, and finally, the actual `typedef` happens at line `[3]`. As C and C++ must have forward declarations for historical reasons, line `[2]` does not compile in C.

In Rust, the automatic binding generator for C headers uses `clang` as a C compiler by default, resulting in that compilation error when trying to generate bindings for the new `gdnative_api_struct.gen.h`:

```txt
   Compiling gdn_api v0.1.0 (file:///.../gdn_api)
error: failed to run custom build command for `gdn_api v0.1.0 (file:///.../gdn_api)`
process didn't exit successfully: `/.../gdn_api/target/debug/build/gdn_api-b922c00fd671dcdf/build-script-build` (exit code: 101)
--- stderr
/.../godot/modules/gdnative/include/gdnative_api_struct.gen.h:24:8: error: must use 'struct' tag to refer to type 'godot_gdnative_api_struct'
/.../godot/modules/gdnative/include/gdnative_api_struct.gen.h:24:8: error: must use 'struct' tag to refer to type 'godot_gdnative_api_struct', err: true
thread 'main' panicked at 'Unable to generate GDNative API bindings: ()', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This tiny PR fixes that error.

### CODE REVIEW

**Comment by karroffel** [comment]
Wouldn't it be enough to just add a forward declaration? It's already typedef'd so using `struct` seems a little off

**Comment by Evrey** [comment]
Might do the job as well. I just thought that adding `struct` would be much simpler.

**Comment by Evrey** [comment]
So, tests ran and passed. What's the next step?

- Merge this?
- Let me change the fix into using a forward-declaration? This will take some hours, as I'm currently not at home.
- Some of you guys make the forward-declaration change and close this?

**Comment by karroffel** [comment]
I think it should be done using a forward declaration. 👍

**Comment by Evrey** [comment]
Good, will do as soon as I'm home. =)

**Comment by Evrey** [comment]
I did a thing. °^°

**Comment by akien-mga** [comment]
Looks fine, could you squash the commits together?

**Comment by Evrey** [comment]
Wtf, now it is one commit in my working directory even when cloning and 4 on GitHub? Probably forgot a step, never had to squash commits before. Know a way to fix this? Otherwise, apparently, you guys can [auto-squash commits on merging](https://github.com/blog/2141-squash-your-commits) with a click of a button.

**Comment by akien-mga** [comment]
See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

@karroffel We don't use this feature..

**Comment by karroffel** [comment]
We usually don't use that GitHub feature because it's a bit limiting and ugly 😄 

I did it anyway to get it done. In the meantime you could read about *interactive rebase* and force push so you can do it properly next time.

**Comment by Evrey** [comment]
Did, thanks for the read. =)

I used `git reset --soft HEAD~2` for the squashing, guess I found the culprit.

**Pull request merged**
