### PR TITLE
DDS: Add support for loading layered textures

### PR DESCRIPTION
**Pull request by BlueCube3310**
Adds support for loading layered DDS texture files.

Progress:
- [x] 2D Arrays,
- [x] Cubemaps,
- [x] Cubemap arrays,
- [x] 3D textures,
- [x] Testing project.

MRP: [ddslayered.zip](https://github.com/user-attachments/files/17561982/ddslayered.zip)

### CODE REVIEW

**Comment by fire** [comment]
There are some unused variables.

```

modules/dds/texture_loader_dds.cpp:648:14: error: unused variable 'dimension' [-Werror,-Wunused-variable]
                                uint32_t dimension = f->get_32();
                                         ^
modules/dds/texture_loader_dds.cpp:649:14: error: unused variable 'misc_flags_1' [-Werror,-Wunused-variable]
                                uint32_t misc_flags_1 = f->get_32();
                                         ^
modules/dds/texture_loader_dds.cpp:651:14: error: unused variable 'misc_flags_2' [-Werror,-Wunused-variable]
                                uint32_t misc_flags_2 = f->get_32();
                                         ^
Retrieved `modules/gdscript/gdscript_lambda_callable.android.editor.arm64.o' from cache
modules/dds/texture_loader_dds.cpp:579:11: error: unused variable 'caps_1' [-Werror,-Wunused-variable]
        uint32_t caps_1 = f->get_32();
```

**Comment by BlueCube3310** [comment]
There's an issue with the quick load menu where the dds files don't show up, since it narrows down the search range to a specific resource class (like Texture2D), and doesn't recognize them by their parent type (Texture in this case)

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

**Testing project:** [test_dds_cubemap.zip](https://github.com/user-attachments/files/17545637/test_dds_cubemap.zip)

### Before

*Notice the resource type icon at the top. Here, it's loaded as a Texture2D. Only one face is imported.*

Uncompressed | DXT5
-|-
image | image

### After

*The DDS file is now loaded as a Cubemap automatically. Memory usage is multiplied by 6 because it's now importing all faces, not just one.*

Uncompressed | DXT5
-|-
image | image

PS: We should improve the Cubemap preview to allow choosing a face to view, or even have an interactive view like the material preview (except you'd be *inside* the box and the box would be unshaded, and with flipped faces).

**Comment by BlueCube3310** [comment]
> PS: We should improve the Cubemap preview to allow choosing a face to view, or even have an interactive view like the material preview (except you'd be _inside_ the box and the box would be unshaded, and with flipped faces).

This system is already in place, though it's not well-documented: left-click the cubemap preview and drag the cursor :)

**Comment by BlueCube3310** [comment]
I've added a testing project for every texture type. It seems to work correctly, though now thumbnails are not generated and the aforementioned issue with the quick search menu persists

**Review by AThousandShips — APPROVED** [review]

**Comment by clayjohn** [comment]
Thank you!

**Pull request merged**
