### PR TITLE
[macOS] Always execute editor instances using NSWorkspace to ensure app window is registered and activated correctly.

### LINKED ISSUE #54306: Menu dropdowns/Tabs only show up if double clicked in macOS Monterey
### Godot version

3.4 RC2 Standard Build

### System information

macOS Montery 12.0.1

### Issue description

**There are several issues:**

1. The menu bar dropdowns (i.e., Project, Editor, Help etc.) only show if the user double clicks on them, a single click won't work.

2. In the "About Godot" window, you need to double click on the tabs to switch between them, a single click won't work.

3. Any of the menu items, options within any boxes etc. only work if double clicked on.

These issues do not exist in version 3.3.4 under macOS or even in the Windows version of 3.4 RC2. Please refer to video down below.

### Steps to reproduce

As in the issue description above.

### Minimal reproduction project

N/A

### LINKED ISSUE #54458: Mouse button input events are not picked up consistently on macOS
### Godot version

3.3.4

### System information

macOS Monterey 12.0.1

### Issue description

input events are not picking up consistently for left click events on apple silicon / Monterey

### Steps to reproduce

create a brand new project and create an action that maps to any key and the left mouse button. 

```gdscript
func _input(event):
	if event.is_action_pressed("spawn"):
		print("spawn")
```

the print line will fire when pressing the key but will only fire when double clicking or rapidly clicking the left mouse button. Every few times it will actually work as expected so you may have to restart the game once or twice if it appears to be working. 

tested on x86 under manjaro and the issue does not exist.

tested under rosetta x86_64-apple-darwin and native aarch-apple-darwin on m1 MacBook issues occurs for both.

### Minimal reproduction project

any brand new project on 3.3.4 on apple silicon and Monterey 12.0.1

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #54306
Fixes #54458

Precompiled .app bundle to test (ad-hoc signed so `xattr -dr com.apple.quarantine /path/to/GodotTest.app` before running): https://mega.nz/file/IhAXVKBR#NDtx9atZNdSQBmbHDFfi9_aemlLmJ5-qBC2sSw82iSQ

*Edit: changed the link to a new one, without unrelated custom modules.*

### CODE REVIEW

**Comment by bruvzg** [comment]
For `master` we probably want to do it in the less hacky way, like change `get_executable_path()` to return app bundle path, and `create_process` to check if provided path is bundle and use `NSWorkspace` in this case.

**Comment by NoFr1ends** [comment]
Tested your changes and it seems to have solved the issue. The editor is now correctly focused and doesn't require the workaround anymore.

**Comment by bruvzg** [comment]
So far I have not found any issues with this, should be good to go. It should not affect any other platforms and running anything else except new instances of the editor.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
