### PR TITLE
renamed 'draw_center' -> 'filled'

### PR DESCRIPTION
**Pull request by toger5**
Since the 'better flat stylebox' got merged it wanted to propose to rename all draw_center to filled.
the advantage is when using the new property style syntax in gd script it makes more sense:
```gdscript
myStylebox.filled = false
```

 -  it is shorter and confirms to how it is called now in style box flat.
 - the flat style box uses it and one or the other has to be changed anyways for consistency
 - I  would guess a beginner probably ask auto complete for `fill` than `draw` or `center`.

### CODE REVIEW

**Comment by toger5** [comment]
@akien-mga what are opinions and thoughts on this one? if it is desired it should be merged soon.
otherwise there might be merge conflicts...

**Comment by akien-mga** [comment]
I have no opinion at all on that one, but we'll discuss it in tonight's PR review meeting.

**Comment by toger5** [comment]
I might not be up.
my arguments are all listed above. So I wouldn't be much help anyways.

**Comment by akien-mga** [comment]
As mentioned by @reduz on IRC:

> i think draw center makes a bit more sense than filled, given its a nine patch
> so i prefer status quo

But if there are occurrences of "filled" being used in the same context, maybe it should be changed to "draw_center" for consistency.

**Comment by toger5** [comment]
@akien-mga in the new style box flat implementation I called it filled...
so Will rename it to draw center

**Pull request closed without merging**
