### PR TITLE
Change bone mapper background model silhouette

### PR DESCRIPTION
**Pull request by TokageItLab**
- Made face smaller
- Made hips smaller and pumping the shoulders and chest muscles
- Lifted pelvis and thicker inner thighs

### CODE REVIEW

**Comment by fabriceci** [comment]
Here is a more adult proposal (if it helps)
BoneMapHumanBody2

**Comment by jcostello** [comment]
@fabriceci I like that one

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/66310#issuecomment-1256469872 was edited and I changed my downvote to a +1. 

Originally, it was a plus masculine silhouette.

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting to go with a less "realistic" silhouette so it fits to both stylized and realistic characters.

**Pull request merged**
