### PR TITLE
Update ThorVG to v0.9.0

### LINKED ISSUE #72478: ImageLoaderSVG: Couldn't set target on ThorVG canvas.
### Godot version

4.0.beta16

### System information

Windows 10, Vulkan, NVIDIA GeForce GTX 1050

### Issue description

Importing SVG's from Kenney.NL fails with the following message:
```
  ImageLoaderSVG: Couldn't set target on ThorVG canvas.
  core/io/image_loader.cpp:101 - Error loading image: res://assets/icons/skull.svg
  editor/editor_file_system.cpp:2004 - Error importing 'res://assets/icons/skull.svg'.
```

### Steps to reproduce

1. Grab icons from Kenney.NL here: https://www.kenney.nl/assets/board-game-icons
2. Try importing an .svg from it
3. The process will fail:
image

### Minimal reproduction project

N/A

### LINKED ISSUE #76175: Godot 4(master and 4.0 branch) does not open svg files that do not contains size properties in root node
### Godot version

4.0 stable and dev

### System information

Manjaro LInux

### Issue description

Godot does not open svg files here.I got this errors
ERROR: ImageLoaderSVG: Couldn't set target on ThorVG canvas.
   at: create_image_from_utf8_buffer (modules/svg/image_loader_svg.cpp:103)
ERROR: Error loading image: res://UIpack_vector.svg
   at: load_image (core/io/image_loader.cpp:101)
ERROR: Error importing 'res://UIpack_vector.svg'.
   at: _reimport_file (editor/editor_file_system.cpp:2031)
ERROR: Resource file not found: res://.import/UIpack_vector.svg-101d3c20e536126791fcca89da4a8955.stex.
   at: _load (core/io/resource_loader.cpp:227)
ERROR: Failed loading resource: res://UIpack_vector.svg. Make sure resources have been imported by opening the project in the editor at least once.

And if I put the properties of weight and height inside the SVG it can open but it is different from the way the version 3.x open it translates it and I need to redo all mapipngs

### Steps to reproduce

Download kenny ui pack and try to open it in godot 4
https://www.kenney.nl/assets/ui-pack

### Minimal reproduction project

[testbed.zip](https://github.com/godotengine/godot/files/11252825/testbed.zip)

### PR DESCRIPTION
**Pull request by capnm**
https://github.com/thorvg/thorvg/releases/tag/v0.9.0

Fixes #72478 
Fixes #76175

Mainly ThorVG now supports  SVGs without viewBox and width&height.
I briefly tested the Godot Linux development version and didn't found regression in the Godot icons.

grafik

### CODE REVIEW

**Comment by capnm** [comment]
Windows linking issue... :thinking: 
https://github.com/godotengine/godot/blob/master/modules/svg/SCsub
https://github.com/godotengine/godot/blob/fd4a06c51555904104b18494d0224f450d74fe2a/modules/svg/register_types.cpp#L45
```
Creating library bin\godot.windows.editor.x86_64.lib and object bin\godot.windows.editor.x86_64.exp
module_svg.windows.editor.x86_64.lib(register_types.windows.editor.x86_64.obj) :
error LNK2019: unresolved external symbol "__declspec(dllimport)
public: static enum tvg::Result __cdecl tvg::Initializer::init(enum tvg::CanvasEngine,unsigned int)"
```

**Comment by akien-mga** [comment]
You might need to define `TVG_EXPORT=0` so it doesn't try to export symbols for a DLL.

**Review by fire — APPROVED** [review]
I tested https://github.com/godotengine/godot/issues/72478#issuecomment-1411549711 with this pr and it seemed to work.

image

The changes in the pr seem to be upstream code. So we may have to wait for godot engine user-developers to respond.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
