### PR TITLE
Revert "Refactored `rotation_mode` in Node3D"

### PR DESCRIPTION
**Pull request by reduz**
Reverts godotengine/godot#62227

### CODE REVIEW

**Comment by reduz** [comment]
I am very sorry, I approved this PR by mistake, it was not ready to go.

**Comment by akien-mga** [comment]
You should describe what's wrong with it.

**Comment by reduz** [comment]
Pretty much everything, so I am not able to give proper feedback this time. I misunderstood the problem so I need to take a good look at the whole thing to understand better what is going on.

**Comment by reduz** [comment]
Again, this is my fault for not understanding the underlying issue properly and giving the wrong feedback, still appreciate @TokageItLab's effort on it.

**Pull request merged**
