### PR TITLE
Changed "Syntax Menu" into radio Menu

### PR DESCRIPTION
**Pull request by Grula**
Before: 
image
After:
after

Issue:
https://github.com/godotengine/godot/issues/18779

### CODE REVIEW

**Comment by YeldhamDev** [comment]
This doesn't appear to have any logic to make them work as radios.

**Comment by Grula** [comment]
I've misread documentation. I am adding logic asap.

**Comment by akien-mga** [comment]
Note that as I mentioned on #18779, this would be better suited as a submenu in the Edit menu, instead of its own first-level menu.
You can see the code for the Convert Case submenu to see how it's done:
screenshot_20180526_100416
I think it's also possible to use radio buttons even in submenus.

**Comment by Grula** [comment]
Moved Syntax menu, and will be adding logic shortly
after

**Comment by toger5** [comment]
What is the difference between standard and GCScript

**Comment by guilhermefelipecgs** [comment]
@Grula You need to squash your commits too, see here: http://docs.godotengine.org/en/3.0/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by guilhermefelipecgs** [comment]
Try reset you branch and create a new commit (This way you don't need to create a new issue):
```
git checkout issue-18779
git reset --hard origin/master # this will erase your local branch issue-18779

# Make your changes and commit

git push -f origin issue-18779
```
If you can't fix it then open a new issue.

**Comment by Grula** [comment]
@guilhermefelipecgs  Thanks a million! :)

**Comment by mhilbrunner** [comment]
Thanks, and congrats on your first contribution :)

**Pull request merged**
