### PR TITLE
Improve ColorPicker sliders in OKHSL mode

### LINKED ISSUE #62120: HSL luminance slider isn't showing the color correctly
### Godot version

f5deed4

### System information

Windows 10 x64

### Issue description

L slider here:
image
It doesn't show the current color. It would be better like this:
image
Luminance 1 is full-white, so the slider should be split into 2 parts: 0 to 0.5 luminance, 0.5 to 1 luminance.

### Steps to reproduce

1. Open ColorPicker with OKHSL color mode

### Minimal reproduction project

_No response_

### LINKED ISSUE #67528: Interacting with saturation in OKHSL color picker makes it white
### Godot version

v4.0.beta.custom_build [0d28820c8]

### System information

Fedora, RX 590

### Issue description

Interacting with saturation in HSV mode turns the color picker white.

### Steps to reproduce

1. make a color property
2. open the color picker
3. with the OKHSL mode, go in HSV and interact with saturation

https://user-images.githubusercontent.com/7917475/196142092-a49d6424-e2c8-4394-bfa8-87ca262831b6.mp4

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #62120
Fixes sliders using wrong color space and showing wrong color (see the first GIF).

*Bugsquad edit:*
- Likely fixes #67528

Before
KT0RMBoA97

After
zD3smBk3Oz

### CODE REVIEW

**Review by fire — APPROVED** [review]
Reviewing the video. Did not do a code check.

This appears to be correct.

The bar next to the circle is a lightness slider. I'm confused now. For the sake of usability do you prefer the black to white or dark to lighter (colours)?

**Comment by KoBeWi** [comment]
I updated the vertical slider
image
It was just an oversight 😅

**Comment by fire** [comment]
@QbieShay You filed a bug about this. Can you take a look?

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
