### PR TITLE
Pause AudioStreamPlayer when SceneTree pauses

### LINKED ISSUE #14009: AudioStreamPlayer does not pause
I have an AudioStreamPlayer in a Singleton and it will not pause. Setting pause_mode to inherit or stop makes no difference. Other nodes in the singleton do pause.

Godot 3.0 beta1

### PR DESCRIPTION
**Pull request by marcelofg55**
Fixes #14009.
Also implemented the suggestion by @mrcdk and exposed the `stream_pause` state, can be toggled on scripts to pause/resume the stream.

### CODE REVIEW

**Comment by mrcdk** [comment]
It may be a good idea to expose the `pause` state too so you can pause/unpause the player without having to pause the whole game. Something like `$player.paused = true`

**Comment by marcelofg55** [comment]
All the streams are done now, code can be reviewed.

**Comment by letheed** [comment]
I think nodes use `paused`, `set_paused` and `is_paused` in GDScript.

**Comment by marcelofg55** [comment]
> I think nodes use paused, set_paused and is_paused in GDScript.

I've just renamed the `pause` var here to `stream_pause` to avoid possible confusions with `paused`.

**Comment by letheed** [comment]
No I meant the opposite, that it should be consistent with the rest of the API.

A few questions (not sure I understand everything here):

* Does this need to be backward compatible or should streams pause by default? Otherwise I think it needs `pause_mode` to `PAUSE_MODE_PROCESS`.
* Is there a reason for having a fadeout?
* Is there a reason paused nodes don't set physics_process_internal to false?
* Should `_mix_audio` just return when we're paused (like when `!active`)?

**Comment by marcelofg55** [comment]
> No I meant the opposite, that it should be consistent with the rest of the API.

Sounds okay to me, I'll add the missing `d`.

> A few questions (not sure I understand everything here):

> - Does this need to be backward compatible or should streams pause by default? Otherwise I think it needs pause_mode to PAUSE_MODE_PROCESS.

I asked @reduz about that and he told me to keep it as it is.

> - Is there a reason for having a fadeout?

Yeah, to avoid audio pops/cracks.

> - Is there a reason paused nodes don't set physics_process_internal to false?

Not sure about that, maybe there is some internal process that for some reason should be still going even if paused.

> - Should _mix_audio just return when we're paused (like when !active)?

Should be possible, but only if `stream_pause_fade == 0.f`.

**Comment by homer666** [comment]
I think the fade-out thing is completely unnecessary; it assumes a lot about how the developer will use `stream_pause`, despite the fact that there are plenty of cases where a fade-out isn't wanted. I think engine functionality should largely step out of the way of design choices like that. If the purpose is to snuff out the 'click' that happens when pausing a stream, couldn't the fade-out duration be dramatically shortened to the point where the effect is imperceptible?

**Comment by vnen** [comment]
> Adding to homer666's comment, why not just fix the audio pop/crack?

It's not something to fix, it's a normal consequence of digital audio.

The thing is that you can't really control when the audio gonna be paused, you don't have proper time to decide which sample you will stop the audio to avoid the pop (you need to do it when the wave hits zero or close to it). I agree that the fade should be very short to not be noticed, but I don't think it can be removed.

**Comment by marcelofg55** [comment]
As @vnen said the fade out is needed here, anyways I'll check that the duration of the fade is not longer than necessary.

**Pull request merged**
