### PR TITLE
Implement pipe API for executed processes IO redirection.

### PR DESCRIPTION
**Pull request by bruvzg**
- Implement `OS.execute_with_pipe` method to run process with redirected stdio.
  - Allow reading process output incrementally (from a thread, since pipes are blocking).
  - Allow independently reading `stdout` and `stderr`.
  - Allow writing to process `stdin`.
  - IO use `FileAccess` API, instead of limiting it to the `String`.
- Implement `pipe://*` path handling for creation of named pipes.
  - Mostly side product of the API, but can be useful for something.

Implemented on Windows and Unix (tested on macOS, but should work on Linux/Android as well).

<details>
  <summary>Samples - click to expand</summary>

### Process redirect:
```gdscript
var pipe
var thread


func _ready():
	# start terminal and open pipes
	var info
	if OS.get_name() == "Windows":
		info = OS.execute_with_pipe("cmd.exe", [])
	else:
		info = OS.execute_with_pipe("/bin/zsh", [])
	pipe = ret["stdio"]
	print(ret)
	thread = Thread.new()
	thread.start(_thread_func)
	get_window().close_requested.connect(clean_func)


func _thread_func():
	# read stdin and add to TextEdit.
	while pipe.is_open() and pipe.get_error() == OK:
		_add_char.call_deferred(char(pipe.get_8()))


func _add_char(c):
	$TextEdit.text += c
	$TextEdit.scroll_vertical = $TextEdit.get_v_scroll_bar().max_value


func _on_line_edit_text_submitted(new_text: String) -> void:
	# send command to stdin.
	var cmd = new_text + "\n"
	var buffer = cmd.to_utf8_buffer()
	pipe.store_buffer(buffer)
	$LineEdit.text = ""


func clean_func():
	# close pipe and cleanup.
	pipe.close()
	thread.wait_to_finish()
```

### Named pipe (server):
```gdscript
	var pipe_nw = FileAccess.open("pipe://test_pipe_3425r72347hjkv", FileAccess.WRITE)
	pipe_nw.store_64(234334); # depending on platform, might block until client connected
```

### Named pipe (client):
```gdscript
	var pipe_nr = FileAccess.open("pipe://test_pipe_3425r72347hjkv", FileAccess.READ)
	var r = pipe_nr.get_64();
	print(r)
```

</details>

- *Production edit: See https://github.com/godotengine/godot-proposals/issues/216.*

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
Tested on Windows and it works great.

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by silverkorn** [comment]
> Unless I'm missing something, there is no way to get the result code from finished process 🤔

Maybe check [tiny-process-library](https://gitlab.com/eidheim/tiny-process-library/) techniques?
- https://gitlab.com/eidheim/tiny-process-library/-/blob/master/process_win.cpp
- https://gitlab.com/eidheim/tiny-process-library/-/blob/master/process_unix.cpp

**Comment by time-killer-games** [comment]
Thank you so very much for this! Life saver!!! :D

**Comment by wyattbiker** [comment]
Hi I am testing on Linux : Kubuntu 23.10, KDE Plasma Version: 5.27.8

Using the samples, I can get the named pipes to work.  However I cannot get the Process Redirect to work. 
(Also in the sample array `ret["stdio"]` should be` info["stdio"]`)

I changed the execute command to `/usr/bin/bash -c uname` for Linux. It does transfer the output to TextEdit when I run it. However when I type something in LineEdit and press Enter, the `_on_line_edit_text_submitted(new_text: String)  `  executes, but then the application just terminates does not even go to clean_func.  No message. Any ideas?

Here is the code I run:
```gdscript
extends Control

var pipe
var thread

func _ready():
	$TextEdit.text = "Textedit "
	$LineEdit.text = "Lineedit "
	# start terminal and open pipes
	var info
	if OS.get_name() == "Windows":
		info = OS.execute_with_pipe("cmd.exe", [])
	else:
		var args = ["-c","uname"]
		info = OS.execute_with_pipe("/usr/bin/bash", args)
		pass
	pipe = info["stdio"]
	print(info)
	thread = Thread.new()
	thread.start(_thread_func)
	get_window().close_requested.connect(clean_func)

func _thread_func():
	# read stdin and add to TextEdit.
	while pipe.is_open() and pipe.get_error() == OK:
		_add_char.call_deferred(char(pipe.get_8()))

func _add_char(c):
	print(c)
	$TextEdit.text += c
	$TextEdit.scroll_vertical = $TextEdit.get_v_scroll_bar().max_value

func _on_line_edit_text_submitted(new_text: String) -> void:
	# send command to stdin.
	var cmd = new_text + "\n"
	var buffer = cmd.to_utf8_buffer()
	pipe.store_buffer(buffer)
	$LineEdit.text = ""

func clean_func():
	# close pipe and cleanup.
	pipe.close()
	thread.wait_to_finish()


```




image

**Comment by agorangetek** [comment]
Is there a reason why

`var pipe_nr = FileAccess.open("pipe://test_pipe_3425r72347hjkv", FileAccess.READ)`

works and returns a FileAccess object even when a pipe server is not running?

**Comment by bruvzg** [comment]
> Is there a reason why

It will open a new pipe.

`FileAccess.READ` means nothing for a named pipe, pipes are always bidirectional. So the first `open` call creates the pipe, and the next call with the same name connects to it.

**Comment by agorangetek** [comment]
I have another named pipe in a different process that listens for a godot pipe client connection. In gdscript, how do i know if the other end is ready and listening?

**Comment by agorangetek** [comment]
If try to read from the pipe in gdscript while the server side is not initialized, get an error

E 0:00:01:128   control.gd:12 @ named_pipe(): Condition "!PeekNamedPipe(fd[0], nullptr, 0, nullptr, &buf_rem, nullptr)" is true. Returning: 0
  <C++ Source>  drivers/windows/file_access_windows_pipe.cpp:109 @ get_length()
  <Stack Trace> control.gd:12 @ named_pipe()

**Pull request merged**
