### PR TITLE
Fix `max_collisions` not being passed in `PhysicsBody3D::test_move`

### LINKED ISSUE #87900: test_move() ignores the max_collisions parameter.
### Tested versions

4.2.1 stable, reproducible in older versions since i can remember.

### System information

Fedora workstation

### Issue description

I'm working in my own implementation of the collide and slide algorithm. After a lot of testing and study i had something that works using move_and_collide as a core for it, however, to keep improving the algorithm and fix the common stutter issues associated with it i need to check for more than one contact point. Here is were move and collided showed it's problems for my uses case, such as continuous collision detection and better contact reporting (Move_and_collide reports a lot of coplanar planes, and the accuracy of the reported information is not enough, often reporting planes that it would not have touched if using CCD). I started re implementing it with test_move (Because a get_rest_info only provides the nearest contact normal and collide_shape only provide points, not normals.) 

The problem is that test_move will return one collision independently of the max_collisions parameter.

### Steps to reproduce

I created a reproduction project with two identical scenes. They consist on a sphere that moves down towards a 4 sided cone, both perfectly centred to make sure that once the sphere touches one point, is touching all of them.

The move_and_collide scene will print 4 collisions as expected.

The test_move scene will print one collision, whatever the actual maximum number of collisions is.

### Minimal reproduction project (MRP)

[test_move bug.zip](https://github.com/godotengine/godot/files/14151854/test_move.bug.zip)

### PR DESCRIPTION
**Pull request by AThousandShips**
* Fixes: https://github.com/godotengine/godot/issues/87900

### CODE REVIEW

**Comment by yosoyfreeman** [comment]
Working as intended, thanks!

**Review by kleonc — APPROVED** [review]
The change seems trivial, likely it was overlooked when copy-pasting from 2D counterpart which has no `p_max_collisions` parameter (no idea why the discrepancy but that's irrelevant here).

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
