### PR TITLE
Changed type to make it work on x32 architecture.

### LINKED ISSUE #44924: Test case "[GDNative String] humanize_size" fails on win32 build
**Godot version:**

0b49e5de129bb33f60e861e82ec05070126e03f9

**OS/device including version:**
Windows 10

**Issue description:**

Attempt to run tests for win32 binary results in one test failing:

```
PS E:\repos\godot> .\bin\godot.windows.tools.32.exe --test
[doctest] doctest version is "2.4.1"
[doctest] run with "--help" for options
===============================================================================
E:\repos\godot\modules\gdnative\tests\test_string.h(1954):
TEST CASE:  [GDNative String] humanize_size

E:\repos\godot\modules\gdnative\tests\test_string.h(1974): ERROR: CHECK( u32scmp(godot_string_get_data(&s), U"4.97 GiB") == 0 ) is NOT correct!
  values: CHECK( -3 == 0 )

===============================================================================
E:\repos\godot\tests\test_class_db.h(814):
TEST SUITE: [ClassDB]
TEST CASE:  [ClassDB] Add exposed classes, builtin types, and global enums

E:\repos\godot\tests\test_class_db.h(706): WARNING: WARN_FALSE( (method_conflict || exposed_class.find_method_by_name(signal.name)) ) is NOT correct!
  values: WARN_FALSE( true )
  logged: Signal name conflicts with method: 'BaseButton.pressed.

E:\repos\godot\tests\test_class_db.h(706): WARNING: WARN_FALSE( (method_conflict || exposed_class.find_method_by_name(signal.name)) ) is NOT correct!
  values: WARN_FALSE( true )
  logged: Signal name conflicts with property: 'Control.minimum_size_changed.

E:\repos\godot\tests\test_class_db.h(473): MESSAGE: Ignoring class 'GDScriptEditorTranslationParserPlugin' because it's not exposed.
E:\repos\godot\tests\test_class_db.h(473): MESSAGE: Ignoring class 'IP_Unix' because it's not exposed.

E:\repos\godot\tests\test_class_db.h(706): WARNING: WARN_FALSE( (method_conflict || exposed_class.find_method_by_name(signal.name)) ) is NOT correct!
  values: WARN_FALSE( true )
  logged: Signal name conflicts with property: 'Input.joy_connection_changed.

E:\repos\godot\tests\test_class_db.h(706): WARNING: WARN_FALSE( (method_conflict || exposed_class.find_method_by_name(signal.name)) ) is NOT correct!
  values: WARN_FALSE( true )
  logged: Signal name conflicts with property: 'ProximityGroup3D.broadcast.

E:\repos\godot\tests\test_class_db.h(479): MESSAGE: Ignoring class 'RootMotionView' because it's not enabled.

E:\repos\godot\tests\test_class_db.h(706): WARNING: WARN_FALSE( (method_conflict || exposed_class.find_method_by_name(signal.name)) ) is NOT correct!
  values: WARN_FALSE( true )
  logged: Signal name conflicts with method: 'TouchScreenButton.pressed.

testing method bind
===============================================================================
[doctest] test cases:    313 |    312 passed | 1 failed | 1 skipped
[doctest] assertions: 202861 | 202860 passed | 1 failed |
[doctest] Status: FAILURE!
```

**Steps to reproduce:**

* compile for win32 platform with tests enabled
* run tests ` .\bin\godot.windows.tools.32.exe --test`

---

All does work for x64 platform and I guess it is the target architecture for CI so the issue wasn't automatically picked up.

It looks like because `godot_string_humanize_size` function accepts `size_t` and the value provided in test - `5,345,555,000` exceeds the allowed range `4,294,967,295` so instead the function attempts to humanize `1,050,587,704`.

Probably, the solution would be to change the type of the parameter to `uint64_t` (the same as `String::humanize_size`) and it should just work 🤔 but at the same time, I guess, not too many people care about x32. If you think it would make sense to fix - I could give it a shot, otherwise, feel free close the issue.

Thank you.

### PR DESCRIPTION
**Pull request by zerc**
Fixes https://github.com/godotengine/godot/issues/44924

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada: 

@vnen @touilleMan Can this be cherry-picked or would it break compat for `3.2` GDNative?

**Comment by touilleMan** [comment]
@akien-mga given GDNative exposed API is obviously wrong for 32bits in Godot 3, I'd say it's ok to cherry-pick this fix (no one ever complain for an api breakage on a segfaulting interface :trollface: )

**Comment by akien-mga** [comment]
What I'm unsure about is if this would break binary compatibility, so e.g. GDNative modules compiled for 3.2.x < 3.2.4 would start crashing when using with 3.2.4. If not, then I agree that it's a reasonable compat breaking in the API that can be backported.

**Comment by touilleMan** [comment]
The fix doesn't change the structures definitions so compiling with the old GDNatvie header or the patched ones changes nothing as long a `godot_string_humanize_size` is not used in the 3rd party module.
When `godot_string_humanize_size` is used:
- on 32 bits the whole application crashes, so changing the API is an improvement here ;-)
- on 64 bits, `sizeof(usize_t) == sizeof(uint64_t)` and they are both unsigned so the two types are equivalent

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
