### PR TITLE
Nintendo Switch port (devkitpro) port from godot-switch

### PR DESCRIPTION
**Pull request by vrince**
This is a port of the godot-switch projet to godot 4.x.
This is based on 4.1.3-stable for now, and the status is game can be exported, display works, and input works.

The goal is to be as less invasive as possible, ideally, only a new switch platform + export is required.

Nevertheless, as os_switch is based on os_linux inevitably there is some dirty ifdef to introduce, please advise so it's done in the godot way.

Progress:

* [x] make it build with devkitpro (arm64)
* [x] add new switch platform
* [x] add new switch export-plugin (use external tools for now)
* [x] figure out opengl and display manager
* [x] port multi-controller personal version of the switch joypad input
* [x] add `switch-tool as third party
* [x] add support for the multi-touch screen (port from godot-switch)
* [ ] add audio driver (port from godot-switch)
* [ ] make sure it works for windows/mac editor
* [ ] add support for remote debugger using nxlink
* [ ] use switch tools instead of external process
* [ ] clean-up reduce change in godot core file as much as possible
* [ ] rebase on latest 4.x
* [ ] deploy exporter
* [ ] documentation

Port from:
* https://github.com/Stary2001/godot

### CODE REVIEW

**Comment by Saul2022** [comment]
So this is more a homebrew port right?

**Comment by AThousandShips** [comment]
Thank you for your contribution!

However this is not something we can support, for a few reasons:
Legally reverse engineering, and generally accessing proprietary hardware and software, is a legally messy area, especially if we are going to provide official export templates for Switch (without that this feature would be quite pointless), and it would mean risking legal actions from Nintendo, or expose users of Godot to that risk using official content.
This, being a homebrew solution, only works on simulators or rooted/hacked hardware, not only does this mean this couldn't be used for publishing games with generally, and mean the target audience would be very small, but also again is a messy area since Nintendo treats such solutions harshly.
The Switch, while a popular platform, is aging, and even with the delays in releasing the replacement console the Switch is soon going to be last generation hardware, limiting the market.

While I can't recommend doing any of this on your own either with the involved risks, this would be better served as an extension, not officially managed by us, which would better fit the target audience and scope.

We are aware of the interest in porting to consoles, but this isn't a sustainable solution to that desire. You might be interested in [this](https://www.rawrlab.com/godot_nintendo_switch_free_port.html) instead.

Thank you again, but I will close this for the reasons listed above.

**Comment by vrince** [comment]
Was expecting this to be honest, I am fine with this not being ever merged or maintained by the Godot team. Everything you said is true, legal sketchiness, niche (as in it will reach very few people, etc ... ). Was just looking for comments and advice on how to "mess" with the core part of Godot to make it maintainable in the long term. But I guess I am on my own! Thanks for taking the time to get back to me.

**Comment by Faless** [comment]
@vrince some general suggestions to implement a new platform.

If `OS_Unix` doesn't work for you, and you need to do a lot of modifications, you might want to extend `OS` directly, like Windows does.

If you find most of the `OS_Unix` is correct, copy it, rename it to `OS_MyPlatform` into your platform folder and do your edits there.

Similarly, you can implement your own NetSockets/FileAccess/DirAccess (see the `windows` or `android` platforms as an example).

The only real change you need from core seems to be in `rasterizer_storage.cpp` and around `glFramebufferTextureMultiviewOVR`. We might change that to an actual feature flag maybe (something like `HAS_GL_FRAMEBUFFER_TEXTURE_MULTIVIEW_OVR`), but, judging by the parameters of the function, you might also be able to abuse your `platform_config.h` and declare that function, then make an implementation like:

```
void glFramebufferTextureMultiviewOVR(target, attachment, texture, level, baseViewIndex, numViews) {
    glFramebufferTexture2D(target, attachment, GL_TEXTURE_2D, texture, level);
}
```

Note I'm pretty useless when it comes to rendering, so this last part is mostly me guessing what the code does looking at the parameters (and could absolutely be wrong :sweat_smile: ).

**Comment by vrince** [comment]
@Faless thanks, it "sounds like" this is exactly what I did, at least ish ...

So far I have done: 
* `OS_Switch that inherits OS_Unix (minor ifdef in OS_Unix really similar to what the web platform skips too) 
* dedicated  RenderingServer that creates / owns the EGL/OpenGL context and native windows
* minor changes in rasterizer_gles3 to skip multi view (whatever this is was not happy, and it's skipped on iOS sooo)
* dedicate joypad + input mapping, nothing fancy

With this, I can compile and get exported games running ...

Now what confuses me is the export mechanism, what I did so far is the same stuff other projects have done, which is embedding the pck on top of a prebuilt version of Godot, tweaking the project_settings file so it unpacks and reads the pck once running on the switch. Easy enough but quite lame especially if the end the export plugin is not supported by Godot. (this is maybe where I do not understand or miss the point). And every change in your game requires 80Mo of Godot to be sent to the switch etc ...

From there I can do two things:

1) publish the exporter, and make it work with the official Godot version (it's a plugin right?), and live the fact Godot binary needs to be uploaded on every change
2) Use Godot itself to load pck dynamically on the switch, that way it needs to be sent only once (as a static precompile .nro) and people just have to send their pck to a dedicated location in the sd card ...

Probably gonna do both, anyway :) 

Thanks again for the pointers keep them coming if by any chance you have time to look at the changes ...

**Pull request closed without merging**
