### PR TITLE
vulkan: Update all components to Vulkan SDK 1.3.231.1

### PR DESCRIPTION
**Pull request by akien-mga**
Updates to volk, vulkan headers, `vk_enum_string_helper.h`, glslang, spirv-reflect.

No update to VMA which still has 3.0.1 as it's last tagged release.
@RandomShaper We should assess if it would be relevant for us to track a Git commit instead (e.g. by checking what they include in the Vulkan SDK tarball).

TODO:
- [x] Update MoltenVK version used on official buildsystem (currently 1.3.216).

I plan to merge this after 4.0 beta 4 so we have time to find potential regressions before beta 5.

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Seems to be working fine with MoltenVK 1.3.231.1 on macOS.

**Comment by akien-mga** [comment]
I'm having a linking failure with MoltenVK 1.3.231.1 with osxcross on our official buildsystem:
```
/root/osxcross/target/bin/arm64-apple-darwin21.4-ranlib core/libcore.macos.editor.arm64.a
/root/osxcross/target/bin/arm64-apple-darwin21.4-c++ -o bin/godot.macos.editor.arm64 -arch arm64 -mmacosx-version-min=11.0 -framework Cocoa -framework Carbon -framework AudioUnit -framework CoreAudio -framework CoreMIDI -framework IOKit -framework ForceFeedback -framework CoreVideo -framework AVFoundation -framework CoreMedia -framework QuartzCore -framework OpenGL -rpath @executable_path/../Frameworks -rpath @executable_path -framework Metal -framework IOSurface -lMoltenVK -L/root/vulkansdk/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64/ platform/macos/os_macos.macos.editor.arm64.o platform/macos/godot_application.macos.editor.arm64.o platform/macos/godot_application_delegate.macos.editor.arm64.o platform/macos/crash_handler_macos.macos.editor.arm64.o platform/macos/macos_terminal_logger.macos.editor.arm64.o platform/macos/display_server_macos.macos.editor.arm64.o platform/macos/godot_button_view.macos.editor.arm64.o platform/macos/godot_content_view.macos.editor.arm64.o platform/macos/godot_window_delegate.macos.editor.arm64.o platform/macos/godot_window.macos.editor.arm64.o platform/macos/key_mapping_macos.macos.editor.arm64.o platform/macos/godot_main_macos.macos.editor.arm64.o platform/macos/godot_menu_delegate.macos.editor.arm64.o platform/macos/godot_menu_item.macos.editor.arm64.o platform/macos/dir_access_macos.macos.editor.arm64.o platform/macos/tts_macos.macos.editor.arm64.o platform/macos/joypad_macos.macos.editor.arm64.o platform/macos/vulkan_context_macos.macos.editor.arm64.o platform/macos/gl_manager_macos_legacy.macos.editor.arm64.o main/libmain.macos.editor.arm64.a modules/libmodules.macos.editor.arm64.a modules/libmodule_msdfgen.macos.editor.arm64.a modules/libmodule_theora.macos.editor.arm64.a modules/libmodule_vorbis.macos.editor.arm64.a modules/libmodule_basis_universal.macos.editor.arm64.a modules/libmodule_bmp.macos.editor.arm64.a modules/libmodule_camera.macos.editor.arm64.a modules/libmodule_csg.macos.editor.arm64.a modules/libmodule_cvtt.macos.editor.arm64.a modules/libmodule_dds.macos.editor.arm64.a modules/libmodule_enet.macos.editor.arm64.a modules/libmodule_etcpak.macos.editor.arm64.a modules/libmodule_freetype.macos.editor.arm64.a modules/libmodule_gdscript.macos.editor.arm64.a modules/libmodule_glslang.macos.editor.arm64.a modules/libmodule_gltf.macos.editor.arm64.a modules/libmodule_gridmap.macos.editor.arm64.a modules/libmodule_hdr.macos.editor.arm64.a modules/libmodule_jpg.macos.editor.arm64.a modules/libmodule_jsonrpc.macos.editor.arm64.a modules/libmodule_lightmapper_rd.macos.editor.arm64.a modules/libmodule_mbedtls.macos.editor.arm64.a modules/libmodule_meshoptimizer.macos.editor.arm64.a modules/libmodule_minimp3.macos.editor.arm64.a modules/libmodule_mobile_vr.macos.editor.arm64.a modules/libmodule_multiplayer.macos.editor.arm64.a modules/libmodule_navigation.macos.editor.arm64.a modules/libmodule_noise.macos.editor.arm64.a modules/libmodule_ogg.macos.editor.arm64.a modules/libmodule_raycast.macos.editor.arm64.a modules/libmodule_regex.macos.editor.arm64.a modules/libmodule_squish.macos.editor.arm64.a modules/libmodule_svg.macos.editor.arm64.a modules/libmodule_text_server_adv.macos.editor.arm64.a modules/libmodule_tga.macos.editor.arm64.a modules/libmodule_tinyexr.macos.editor.arm64.a modules/libmodule_upnp.macos.editor.arm64.a modules/libmodule_vhacd.macos.editor.arm64.a modules/libmodule_webp.macos.editor.arm64.a modules/libmodule_webrtc.macos.editor.arm64.a modules/libmodule_websocket.macos.editor.arm64.a modules/libmodule_webxr.macos.editor.arm64.a modules/libmodule_xatlas_unwrap.macos.editor.arm64.a modules/libmodule_zip.macos.editor.arm64.a platform/libplatform.macos.editor.arm64.a drivers/libdrivers.macos.editor.arm64.a editor/libeditor.macos.editor.arm64.a scene/libscene.macos.editor.arm64.a servers/libservers.macos.editor.arm64.a core/libcore.macos.editor.arm64.a modules/text_server_adv/libharfbuzz_builtin.macos.editor.arm64.a modules/text_server_adv/libgraphite_builtin.macos.editor.arm64.a modules/text_server_adv/libicu_builtin.macos.editor.arm64.a modules/freetype/libfreetype_builtin.macos.editor.arm64.a modules/msdfgen/libmsdfgen_builtin.macos.editor.arm64.a -lpthread -lz
Undefined symbols for architecture arm64:
  "_objc_msgSend$HDR10MetadataWithDisplayInfo:contentInfo:opticalOutputScale:", referenced from:
      MVKSwapchain::setHDRMetadataEXT(VkHdrMetadataEXT const&) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
  "_objc_msgSend$UTF8String", referenced from:
      MVKCommandResourceFactory::newMTLFunction(NSString*, NSString*) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKCommandResourceFactory::initMTLLibrary() in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKWatermark::newRenderPipelineState() in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKWatermark::initShaders(char const*) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKGPUCounterQueryPool::initMTLCounterSampleBuffer(VkQueryPoolCreateInfo const*, objc_object objcproto13MTLCounterSet*, char const*) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKInstance::debugReportMessage(MVKVulkanAPIObject*, MVKConfigLogLevel, char const*) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKBuffer::propagateDebugName() in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      ...
  "_objc_msgSend$UUIDString", referenced from:
      MVKPhysicalDevice::logGPUInfo() in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
  "_objc_msgSend$addCompletedHandler:", referenced from:
      MVKImagePlane::applyImageMemoryBarrier(unsigned int, unsigned int, MVKPipelineBarrier&, MVKCommandEncoder*, MVKCommandUse) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKImagePlane::pullFromDeviceOnCompletion(MVKCommandEncoder*, MVKImageSubresource&, MVKMappedMemoryRange const&) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKPresentableSwapchainImage::presentCAMetalDrawable(objc_object objcproto16MTLCommandBuffer*, MVKPresentTimingInfo) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKCommandBuffer::flushImmediateCmdEncoder() in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKCommandEncoder::endEncoding() in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKCommandEncoder::encode(objc_object objcproto16MTLCommandBuffer*, MVKCommandEncodingContext*) in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      MVKCommandEncoder::endCurrentMetalEncoding() in libMoltenVK.a(libMoltenVK.a-arm64-master.o)
      ...
```
and plenty more like this.

Full link failure log: [macos-osxcross-moltenvk-linking-failure.log](https://github.com/godotengine/godot/files/9905204/macos-osxcross-moltenvk-linking-failure.log)

**Comment by bruvzg** [comment]
Seems like MoltenVK is built with Xcode 14, which is using a new optimization for Objective-C selectors (can be disabled with `-fno-objc-msgsend-selector-stubs`, see https://reviews.llvm.org/D128108), probably OSXCross is using older clang version without support for it.

Not sure if it's possible to update OSCross clang. If not, we'll probably need a custom MoltenVK build.

**Comment by akien-mga** [comment]
I'm currently building osxcross explicitly with Clang 13.0.1 (actually building Clang from source as Fedora 36 ships Clang 14):
https://github.com/godotengine/build-containers/blob/main/Dockerfile.osx#L11-L12

This is because we're using Xcode 13.3.1 and apparently building it with Clang 14 was leading to crashing binaries.

I'll have a go at updating our build containers to Xcode 14.1 when it releases (should be soon, it's at 14.1 RC 2 currently).

**Comment by akien-mga** [comment]
> I'll have a go at updating our build containers to Xcode 14.1 when it releases (should be soon, it's at 14.1 RC 2 currently).

As discussed on chat, I did this (https://github.com/godotengine/build-containers/pull/116) but sadly that doesn't fix the issue. https://reviews.llvm.org/D128108 was merged recently and is only present in llvm-project's LLVM in the `main` branch, i.e. the future 16.0 release.

So to get it to work we would need either to:
- Build against llvm-project LLVM 16-dev, with the potential instability it would bring. This is also not the version Apple is testing against since Xcode 14.1 is based on Apple LLVM 14.
- Build a custom llvm-project LLVM 14.0.6 with that patch backported. It doesn't seem too trivial though and I'm not confident that I could do this without introducing regressions.
- Build osxcross with Apple LLVM 14, if that's possible.
- Build MoltenVK from source:
  * Doesn't seem possible to build with osxcross as it requires the use of `xcodebuild`, which is not implemented in osxcross (also tried the deprecated https://github.com/facebookarchive/xcbuild but it doesn't work either).
  * Would need to be built on macOS with Xcode 13 or earlier, or Xcode 14 with `-fno-objc-msgsend-selector-stubs`.

I'll suggest the last point upstream, and see which options we should try ourselves in the meantime.

**Comment by akien-mga** [comment]
> - Build MoltenVK from source:
>  * Would need to be built on macOS with Xcode 13 or earlier, or Xcode 14 with `-fno-objc-msgsend-selector-stubs`.

@bruvzg did this (Xcode 14 with `-fno-objc-msgsend-selector-stubs`) so I was able to link MoltenVK when using upstream LLVM 14 to build osxcross and Godot.

Here's a test build of this PR for macOS (editor) and with macOS and iOS export templates:

https://downloads.tuxfamily.org/godotengine/testing/4.0-beta-vk-1.3.231.1/

Would be great if some users could test it and make sure it's working as expected. Notably testing 2D and 3D rendering features when comparing with their behavior in 4.0-beta4 (which uses an earlier Vulkan SDK and MoltenVK version).

**Comment by paddy-exe** [comment]
This works great for me with MacOS 13.0 and the same as in beta 4:
Running my [StylizedSkyShader project](https://github.com/paddy-exe/GodotStylizedSkyShader):

https://user-images.githubusercontent.com/38077837/199769200-b1cf9a9a-3beb-445c-9ffb-6d777670141d.mov

**Comment by tcmug** [comment]
Does not to fix the [issues](https://github.com/godotengine/godot/issues/45661#issuecomment-1232432505) with a non M1 Mac (omni lights are broken, only directional works).

```
Godot Engine v4.0.beta-vk-1.3.231.1.official.95e280177 - https://godotengine.org
Vulkan API 1.2.231 - Using Vulkan Device #0: AMD - AMD Radeon Pro 5500M
```
image
image

**Comment by SonnyBonds** [comment]
Wanted to double check if this by chance fixed #62322 (which it did not), but also for some reason this build defaulted to OpenGL rendering driver instead of Vulkan. (And showed a totally blank UI.)

**Comment by akien-mga** [comment]
> but also for some reason this build defaulted to OpenGL rendering driver instead of Vulkan. (And showed a totally blank UI.)

That's intentional for the project manager: #67593.

But it being blank is not what we expect of course, please file a bug report about it :)

**Comment by SonnyBonds** [comment]
> That's intentional for the project manager: #67593.
Ah, got it.
 
> But it being blank is not what we expect of course, please file a bug report about it :)
Seems someone already did: #67595

**Pull request merged**
