### PR TITLE
Fix crash in code completion

### LINKED ISSUE #4641: _on_resize or No completion weird crash
**Operating system or device - Godot version:**
Arch Linux 64bit - Godot built from source 48dc4d92a8f3c9eb42456eda2433c6fcaff0c723
I run Godot via ```primusrun``` (Nvidia Optimis Laptop :-1: )

**Issue description** 
I'm working on my project - pseudo [terminal emulator for Godot](https://github.com/TeddyDD/gtern). It's basicly rewrite of my old project using new Godot features. Every time I try to add line 
```if x <= size.x:``` to `transfer_to()` method in [buffer.gd](https://github.com/TeddyDD/gtern/blob/master/addons/terminal/buffer.gd) Godot crashes.

It should looks like this
```gdscript
func transfer_to(buffer):
	for y in buffer.size.y:
		if y <= size.y:
``` 
```size``` is Vector2D 

**Steps to reproduce:**
1. Open my project in Godot
2. Open buffer.gd
3. Try to add ```if y <= y.size:``` line in ```transfer_to(buffer):``` method at the beggining of first loop (```for y in buffer.size.y```) 
**Note** I know that that line of code wouldn't work and I shoud use ```range()``` but I suppose that does not matter for now.
Project itself works, you can run it, works as expected.

I captured little video to show the issue:  https://www.youtube.com/watch?v=z-6zQ851g7g&feature=youtu.be

Godot output: https://gist.github.com/TeddyDD/842a54a7fd045b202af1a0ccb0541297

This line might be relevant (or not?): https://github.com/TeddyDD/gtern/blob/master/addons/terminal/terminal.gd#L45 It was called by signal before _ready() (font was null) I'm talking about this because of this line from Godot output

```
ERROR: emit_signal: Error calling method from signal 'resized': 'Control(terminal.gd)::_on_resize': Method not found.
   At: core/object.cpp:1210.
```

**Link to minimal example project** 
Here is my project https://github.com/TeddyDD/gtern

Sorry if this not very precise issue description but this is pretty weird :confused:

### PR DESCRIPTION
**Pull request by vnen**
Fix #4641.

### CODE REVIEW

**Comment by vnen** [comment]
Calling @reduz to review this.

What I did is only skipping the completion guess if the assignment is on the same line of the completion that it's trying to make. So this stops the recursion loop that was happening in this case.

This also won't guess the completions if the assignment is made later on the same function. It still guesses if the assignment is made earlier but in another function.

**Comment by vnen** [comment]
Actually, this still crashes in one case:

```GDscript
var x
var z

func _init():
	x=z
func _ready():
	z=x
func _enter_tree():
	z. # crash after pressing the dot. Also crashes with x.
```

**Comment by vnen** [comment]
I guess that keeping a list of tested functions might be the solution to avoid an infinite loop. While this case is unlikely to happen in real life, crashing is always a bad thing.

**Comment by reduz** [comment]
i would probably have used >= for the comparison, as empty lines not always store a line statement

**Comment by reduz** [comment]
just added that myself

**Comment by vnen** [comment]
@reduz this gives a bit of problems: it can't guess the type if the assignment is in the line just above, such as this (this works if the variable is local to the function though):

```gdscript
var x
func _ready():
	x = get_node("Label")
	x. # no complete here
	x. # here it completes

	var y = get_node("Label")
	y. # here it completes
```

Also, it won't guess the type if the assignment is below, even if in another function. So this won't complete, unless you reverse the order of the functions in the code:

```gdscript
var x
func _ready():
	x. # no complete here, even though it was defined earlier in the lifecycle (but later in this file)
func _init():
	x = Label.new()
```

This is why I didn't use `>=`. But it does fix the crash I mentioned earlier: https://github.com/godotengine/godot/pull/5204#issuecomment-225966064

**Comment by reduz** [comment]
ah that's right.. well, in theory i think all lines are being generated, so
if this keeps failing we'll just have to fix it

**Pull request merged**
