### PR TITLE
[RFC] MultiplayerAPI refactor

### PR DESCRIPTION
**Pull request by Faless**
This PR moves all the Multiplayer API related stuff to a dedicated MultiplayerAPI class which is exposed via script and can also be extended.

It allows to access the API via the `multiplayer_api` property of `Node` and `SceneTree` and allows one to specify overrides for specific nodes actively allowing you to run both client and server in the same scene.

When no override is specified `Node.multiplayer_api` becomes a shortcut for `get_tree().multiplayer_api` scene to provide compatibility with the two systems.

All the network related functions and signals in `SceneTree` are left for compatibility, but I suggest we deprecate/remove the functions and asks our users to replace all the `get_tree().[network related stuff]` with `multiplayer_api.[network related stuff]` which is guaranteed to work as `MultiplayerAPI` has the same interface of SceneTree with regards to networking.

I believe this is an important milestone for many MultiplayerAPI related stuff, like allowing customization via GDNative, implementing a `NETWORK_COMMAND_PING` to allow latency detection without relying on library specific code, and implementing `rpc_ordered` (again, without any library specific code).

I would greatly appreciate a comment from @reduz (this is mostly what discussed at `GodotCon`).

You can test it with this: [multiplayer_demo.zip](https://github.com/godotengine/godot/files/1777657/multiplayer_demo.zip) (if you run `combo.tscn` it will use custom multiplayer API on each `main.tscn`, otherwise it will use plain old singleton system in SceneTree)
As said, the demo uses the new `multiplayer_api` property but you can still use `get_tree()` **i.e. old networking demos will work out-of-the-box** (unless we decide to remove the functions from `get_tree()`, which again, I suggest we do).

Any question or comment is appreciated.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Not reduz, obviously, but looking forward to this or something like it.

Besides making it easier to implement some stuff I was looking into, it is just plain cleaner IMO to not couple this stuff so tightly with SceneTree & friends.

That said: I'm not a fan of the property name, multiplayer_api is fairly long and clunky. Also "api" is fairly devoid of meaning. Maybe just "multiplayer"? Not sure, but this is a fairly small quibble. :)

**Comment by Faless** [comment]
> That said: I'm not a fan of the property name, multiplayer_api is fairly long and clunky. Also "api" is fairly devoid of meaning. Maybe just "multiplayer"? Not sure, but this is a fairly small quibble. :)

yes `multiplayer` is probably better, an alternative might be `mp_api`.

**Comment by hpvb** [comment]
Could you clean up the commit history for this PR a little bit? Probably 2 or 3 commits where you add the new multiplayer api object and one commit where you remove the old code and point it to the new object would be the best I think.

I agree with the above about the naming a 'Multiplayer' or 'MultiplayerServer' or something along those lines would probably be better than 'api', or maybe even

**Comment by Faless** [comment]
@hpvb done.

**Comment by mhilbrunner** [comment]
Thinking about it some more, I think simply naming it `multiplayer` is best: thats the shortest it can be while still being descriptive enough to be self-explaining when you first encounter it.

I'd prefer it over `mp_api` or `multiplayer_server`. I don't think `api` or `server` add much information, but shortening to `mp` is probably too much: at that point you have to know what it is, look at the docs or guess.

**Comment by Faless** [comment]
agreed, also iit is not a server, as it can be a client, and `MultiplayerServer` might be the name to be used in an internal sense for an (hypothetical) class in `server/` if we want to allow interfacing with GDNative.

**Comment by Faless** [comment]
I will need to add some documentation for it when we reach an agreement on naming and functions.

@hpvb how do you feel about eventually removing the relay functions in `SceneTree` and breaking compatibility (asking users to replace `get_tree().[netstuff]` with `multiiplayer_api.[netstuff]`)?

**Comment by hpvb** [comment]
@Faless we'll have to go through at least one release were we mark the old method as deprecated. If this doesn't add any backwards incompatibility that release were we show deprecation warnings could be 3.0.z as far as I'm concerned. Basically just add:

```c++
WARN_PRINT("This method is deprecated and will be removed in 3.1. Use `multiplayer.<thing>` instead.");
```
And the documentation XML for the deprecated functions should then say something like
```xml
+                       <description>
+                       This method is deprecated. Please use `multiplayer.thing()` instead.
+                       </description>
```

**Comment by aaronfranke** [comment]
I haven't done networking in Godot yet but I can say that the ability to extend multiplayer and networking classes is a very useful feature which I've used in Unity before. +1 if this patch meets Godot's standards.

**Comment by Malkverbena** [comment]
Will this refactor implement some encrypt method for network?

Maybe something like:
host.set_encrypt_mode(key, settings)
get_tree().set_network_peer(host)

**Comment by mhilbrunner** [comment]
@Malkverbena No, this has nothing to do with encryption. Please open a new issue for that as a feature request. Even better, add both your proposed example and why somebody would want/need encryption :)

**Pull request merged**
