### PR TITLE
`CanvasItem` Fix `ENTER_CANVAS` / `VISIBILITY_CHANGED` notifications order when entering tree

### LINKED ISSUE #63666: CanvasModulate changes sprite tint outside of canvas element
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 10, Vulkan

### Issue description

See image below

image

### Steps to reproduce

Not entirely sure, but if you reproduce the node structure in the screenshot and move around the nodes a bit, the issue will start to appear. Note that the issue persists if I leave and re-open the project.

### Minimal reproduction project

[test_a_13.zip](https://github.com/godotengine/godot/files/9225511/test_a_13.zip)

### PR DESCRIPTION
**Pull request by kleonc**
When a visible-in-tree CanvasItem enters the tree it sends `NOTIFICATION_VISIBILITY_CHANGED`, however it was being done before handling entering the canvas by such CanvasItem. This resulted in possibly out-of-sync state during handling such `NOTIFICATION_VISIBILITY_CHANGED`, as e.g. `CanvasItem::get_canvas()` could be not yet aware the CanvasItem is in a custom canvas layer (as `CanvasItem::_enter_canvas` was not yet called), and hence it would incorrectly return the viewport's default canvas:
https://github.com/godotengine/godot/blob/0291fcd7b66bcb315a49c44de8031e5596de4216/scene/main/canvas_item.cpp#L813-L821

This PR makes the CanvasItem handle entering the canvas before sending `NOTIFICATION_VISIBILITY_CHANGED` (so the current canvas info is already properly updated when such notification is being handled).

For reference it was done like that in #63248. cc @Rindbee to confirm it wasn't anyhow intentional.

---

The mentioned issue affected e.g. CanvasModulate which were updating incorrect canvas when handling `NOTIFICATION_VISIBILITY_CHANGED`:
|Before|After|
|-|-|
|LI9JriTeXu|nXHPFaoyyM|
|Godot_v4 0 1-stable_win64_k3FpO5SrQN|godot windows editor dev x86_64_G2EHjOeONd|

Fixes #63666.

### CODE REVIEW

**Comment by Rindbee** [comment]
> For reference it was done like that in https://github.com/godotengine/godot/pull/63248. cc @Rindbee to confirm it wasn't anyhow intentional.

Putting it here is to make sure that `NOTIFICATION_VISIBILITY_CHANGED` is sent before `NOTIFICATION_DRAW`.

**Review by YuriSizov — APPROVED** [review]
Makes sense to me.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.2.

**Pull request merged**
