### PR TITLE
Tidy Joints 3D

### PR DESCRIPTION
**Pull request by madmiraal**
Currently, Joints 3D is spread across multiple files that don't fit with the general Godot file structure and the structure is significantly different from Joints 2D. Specifically:
- Joints3D is in a file called `scene/3d/physics_joint_3d`; instead of `scene/2d/joints_3d`
- Each of the `Joints3DSW` joints and its utility class `JacobianEntry3DSW` are in a separate file in a folder called `joints`, instead of together as is done in 2D.

This PR renames `scene/3d/physics_joint_3d` to `scene/3d/joints_3d` and moves all the 3D_SW Joints into `joints_3d_sw`, removes duplicate code, and makes it consistent with Joints 2D.

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge or #44164.

**Comment by madmiraal** [comment]
Rebased following merge of  #44391.

**Comment by madmiraal** [comment]
Rebased following merge of #44859.

**Comment by madmiraal** [comment]
Rebased following merge of #45136 and  #45167.

**Comment by madmiraal** [comment]
Rebased following merge of #37547 and #45564.

**Comment by madmiraal** [comment]
Rebased following merge of #45852.

**Comment by madmiraal** [comment]
Rebased following merge of #46578.

**Comment by madmiraal** [comment]
Rebased following merge of #47942.

**Comment by madmiraal** [comment]
Rebased following merge of #48050.

**Comment by TechnoPorg** [comment]
If you need someone to test whether joints still work, I can do it after a rebase! If it's just waiting for someone's approval, this does seems like a cleaner and more consistent structure to me (Although I'll be the first one to say that I don't know much about Godot physics, so count that as approval at your peril 🙂).

**Comment by akien-mga** [comment]
> Joints3D is in a file called `scene/3d/physics_joint_3d`; instead of `scene/2d/joints_3d`

That part seems to have been fixed already in `master`, it's now `scene/3d/joint_3d.h`.

> Each of the Joints3DSW joints and its utility class JacobianEntry3DSW are in a separate file in a folder called joints, instead of together as is done in 2D.

After discussion in a PR review meeting, we decided not to go in that direction. While it's true that Godot tends to have big files with multiple related classes, we tend to go away from that trend and often split files when they become too unwieldy to work with. Here for 2D the "megafile" is fairly short (less than 200 loc header and 500 loc cpp) so this is not a big issue, while in 3D each file in itself is big enough to be standalone. Moreover, the 3D joints are derived from bullet so it's kind of a library in itself.

**Comment by madmiraal** [comment]
> This PR renames scene/3d/physics_joint_3d to scene/3d/joints_3d and moves all the 3D_SW Joints into joints_3d_sw, **removes duplicate code**, and makes it consistent with Joints 2D.

This PR also removed a lot of duplicated code for example:
https://github.com/godotengine/godot/blob/20dfa0c60b0bd98d6c4c82aa76b9ab76c873e1ae/servers/physics_3d/joints/godot_cone_twist_joint_3d.cpp#L54-L70
https://github.com/godotengine/godot/blob/20dfa0c60b0bd98d6c4c82aa76b9ab76c873e1ae/servers/physics_3d/joints/godot_hinge_joint_3d.cpp#L52-L68
and
https://github.com/godotengine/godot/blob/20dfa0c60b0bd98d6c4c82aa76b9ab76c873e1ae/servers/physics_3d/joints/godot_cone_twist_joint_3d.cpp#L72-L85
https://github.com/godotengine/godot/blob/20dfa0c60b0bd98d6c4c82aa76b9ab76c873e1ae/servers/physics_3d/joints/godot_slider_joint_3d.cpp#L60-L73

> While it's true that Godot tends to have big files with multiple related classes, we tend to go away from that trend and often split files when they become too unwieldy to work with. Here for 2D the "megafile" is fairly short (less than 200 loc header and 500 loc cpp) so this is not a big issue, while in 3D each file in itself is big enough to be standalone.

The combined file in this PR is only [1946](https://github.com/godotengine/godot/pull/44146/files#diff-488cca1ff468328bbdff2a56754f6776dbfa654c5dead8f63322e9ec991427f3) lines long. If the reverse were true, would there be justification for splitting the 1946 long file into 5 or 6 files?

> Moreover, the 3D joints are derived from bullet so it's kind of a library in itself.

Arguing to keep the files separate because the origin had them is separate files is a weak argument. Godot has copied the algorithms (and hence the attribution) not the code (e.g. `git diff --no-index servers/physics_3d/joints/godot_cone_twist_joint_3d.cpp thirdparty/bullet/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp`) i.e. it's not a library. Note: The original files are much larger (e.g. [1116](https://github.com/godotengine/godot/blob/master/thirdparty/bullet/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp) vs [359](https://github.com/godotengine/godot/blob/master/servers/physics_3d/joints/godot_cone_twist_joint_3d.cpp)) i.e. justifiably kept in separate files.

**Pull request closed without merging**
