### PR TITLE
etcpak: We only need the compression code, remove rest of etcpak app

### PR DESCRIPTION
**Pull request by akien-mga**
We do our own image loading, threading, and memory management in Godot already,
so the only components we need from etcpak (at least as of now) are the
`Compress*` methods defined in `ProcessDxtc.cpp` and `ProcessRGB.cpp`.

So we don't need to compile or vendor the rest.

Follow-up to #47370 thanks to advice from @wolfpld in https://github.com/wolfpld/etcpak/pull/14.

---

Relevant code where the library is used:

https://github.com/godotengine/godot/blob/8ce0fb0a946455ed6a7bc8a54fcf90a9d5a9ae4d/modules/etcpak/image_etcpak.cpp#L93-L170

### CODE REVIEW

**Review by fire — APPROVED** [review]
There was no code changes, only build system changes it appears.

**Comment by akien-mga** [comment]
> There was no code changes, only build system changes it appears.

Yeah that's expected, all the code removed was unused. (So needlessly compiled, though likely optimized out by the linker.)

**Comment by nikitalita** [comment]
Revert this please, we need the decompression code.

**Comment by Calinou** [comment]
> Revert this please, we need the decompression code.

What do you need the decompression code for? Please open a [proposal](https://github.com/godotengine/godot-proposals) with example use cases.

**Comment by nikitalita** [comment]
> > Revert this please, we need the decompression code.
> 
> What do you need the decompression code for? Please open a [proposal](https://github.com/godotengine/godot-proposals) with example use cases.

it's already an open issue and added to the 4.0 milestone:
https://github.com/godotengine/godot/issues/25595

**Pull request merged**
