### PR TITLE
Add VideoStream icon

### PR DESCRIPTION
**Pull request by MewPurPur**
image

(A new gradient for video resources - maybe a little over the top? :thinking:)

### CODE REVIEW

**Review by deralmas — APPROVED** [review]
Looks great!

IMO the gradient is worth it, there's definitely room for new `VideoStream`s, even as an addon.

**Comment by MewPurPur** [comment]
You mean as a module? I think other types of VideoStreams would be using the same icon, just like AudioStreamWAV, AudioStreamOGG, and AudioStreamMP3 use the same icon. What could use a different icon would be classes with visibly different functionality; for audio, that'd for example be AudioStreamGenerator, AudioStreamPolyphonic, and AudioStreamRandomizer. But I don't think video will ever have things like these or anything else that builds on its behavior.

**Review by Calinou — APPROVED** [review]
Looks great and modern 🙂

**Comment by MewPurPur** [comment]
p.s. Another thing is that I didn't add any conversion rules, mostly because I saw AudioStream's gradient also didn't have them. Maybe I've misunderstood something about `editor_themes.cpp`?

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
