### PR TITLE
Add documentation examples for RegEx class

### PR DESCRIPTION
**Pull request by brandonlamb**
Provide more documentation examples for the RegEx class showing more
complete usage.

### CODE REVIEW

**Comment by brandonlamb** [comment]
Weird, not sure why this would fail but my other 2 PRs (all 3 of these are docs only) passed...

**Comment by bojidar-bg** [comment]
Most likely conflicts with #6887

**Comment by leezh** [comment]
Looking at the diff, yeah, there's definitely going to be some conflicts. That said, with the API changes, it'd be better if this patch gets merged first, and then I'll do a `git pull --rebase` on mine with the conflicts fixed and examples updated.

Also, perfectly fine for a 2.1 cherry-pick.

**Comment by akien-mga** [comment]
No, the code examples here are much more useful IMO than the ones you gave for LineEdit. The indentation is off though, if you could fix it to use tabs instead of spaces, that would be great; here the parser will choke on the XML.
You should also use `[codeblock]` instead of `[code]`, and avoid inserting empty newlines, as the parser considers each one as a new paragraph (empty newlines in codeblocks are fine though). There's also a missing closing tag in `find` example.

All in all, I think that having a complete example in the class description is enough though, otherwise there's a lot of repeat since each method corresponds to one step in the regex workflow (compile, find, get_capture{,s}).

**Comment by brandonlamb** [comment]
Okay, as long as it's actually useful. I'll make these updates and just move to a single example in description.

**Pull request closed without merging**
