### PR TITLE
Keep crash handler status on editor restart

### PR DESCRIPTION
**Pull request by RandomShaper**
I've added some blank lines now we have > 2 logically grouped command line switches to setup, for readability.

### CODE REVIEW

**Comment by akien-mga** [comment]
Why not, but I'm not fond of this solution. The real problem is that none of the original args passed are properly passed along to running the editor from pnthe project manager or restarting the editor from itself. We can add more special cases like this for all of them (e.g. verbose, windowed, etc.) but IMO the better fix would be to have a way to record `main.cpp` arguments in an array or similar and find a way to pass it along to relevant new processes.

Still not against merging this but I see these hacks keep piling and it calls for a more systemic solution IMO. See also https://github.com/godotengine/godot/pull/42099

**Comment by RandomShaper** [comment]
I agree. In fact, I even considered doing some refactor to capture the kind of arguments that should survive runs, but I'm sadly (or happily, depending on how you look at it) too busy with other stuff.

That said, this PR is not making the current situation any worse. We can merge and, now I'm aware of the overall problem, I may be able to provide a more comprehensive solution some Saturday morning.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
