### PR TITLE
Copy track update mode when adding reset key

### PR DESCRIPTION
**Pull request by KoBeWi**
When adding a reset key (by right-clicking a key in animation track), the value is copied over to RESET animation, but not the update mode, and always created continuous track. After AnimationMixer changes this can result in a warning spam if the update mode does not match.

This PR ensures that when creating a reset key from an existing animation track, the track's update mode is copied to the RESET track (even if it already existed).

### CODE REVIEW

**Review by TokageItLab — APPROVED** [review]

**Comment by KoBeWi** [comment]
> InterpolationType and LoopWrap should be copied in the same way

Should I do it in the same PR?

**Comment by TokageItLab** [comment]
I think should be done if possible.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
