### PR TITLE
Display Message if Caching is Disabled for Compilation

### PR DESCRIPTION
**Pull request by Andrettin**
If the SCONS_CACHE environment variable is not set, then caching will not occur during compilation - resulting in a rebuild being done every time, without any notification that caching is disabled. This can bewilder users, who may then not understand why a rebuild keeps happening.

This pull request makes it so a message is printed informing the user if SCONS_CACHE is not set, so that they may know why a full rebuild is happening.

### CODE REVIEW

**Comment by Calinou** [comment]
Could we set `SCONS_CACHE` to a directory inside the Godot source tree which would be added to `.gitignore`? This way, users don't have to do it themselves.

**Comment by akien-mga** [comment]
I'm not sure it's worth printing this each time people compile, SCons cache is a useful feature but definitely not a requirement.

I don't use any SCons cache here, that doesn't prevent using incremental builds. The cache is mostly useful for CI, as we start from a fresh clone each time so the cache allows to fetch previous build artifacts. When building locally, all the build artifacts are usually still in your git clone, so next build will pick them up.

**Comment by akien-mga** [comment]
> Could we set SCONS_CACHE to a directory inside the Godot source tree which would be added to .gitignore? This way, users don't have to do it themselves.

Without any cache, my Godot build directory is already 8.8G big, and that's only for the master branch. I have separate git clones for 2.1 and 3.0 which take each ~2.5G (only Linux tools build).

Forcing a cache would mean doubling this size, and I for one can't afford this on my small `/home` partition. I'm sure many others can't either.

And as mentioned, incremental builds work already so I yet to see a gain with using `SCONS_CACHE` for local builds.

**Comment by Andrettin** [comment]
> 
> 
> I'm not sure it's worth printing this each time people compile, SCons cache is a useful feature but definitely not a requirement.
> 
> I don't use any SCons cache here, that doesn't prevent using incremental builds. The cache is mostly useful for CI, as we start from a fresh clone each time so the cache allows to fetch previous build artifacts. When building locally, all the build artifacts are usually still in your git clone, so next build will pick them up.

I understand what you mean, but IMO since a message is already printed when caching is enabled, it would also make sense to print it when caching is disabled, specially since the user might expect caching to be active by default.

Before I set the SCONS_CACHE variable here, it was rebuilding every time for me, even when I didn't make any changes. Despite the .lib and .obj files being present after compilation, it generated new ones each time. When I discovered that a caching feature existed for Scons, I was quite relieved, and it was indeed a huge time saver for me.

By the way Akien, thanks for all your good work on this great engine! :)

**Comment by akien-mga** [comment]
> Before I set the SCONS_CACHE variable here, it was rebuilding every time for me, even when I didn't make any changes. Despite the .lib and .obj files being present after compilation, it generated new ones each time. When I discovered that a caching feature existed for Scons, I was quite relieved, and it was indeed a huge time saver for me.

It's not normal that it recompiles every time, it should reuse your existing build objects.

[As per the documentation](https://scons.org/doc/3.0.3/HTML/scons-user.html#chap-caching), the SCons cache is for:
>  On multi-developer software projects, you can sometimes speed up every developer's builds a lot by allowing them to share the derived files that they build. SCons makes this easy, as well as reliable. 

It's for sharing build artifacts, and in your case you're sharing them with yourself, but it should not make a difference compared to simply running SCons with cache and without cleaning artifacts beforehand.

Note that, cache or not, SCons will rebuild most of the projects if some `core/` files are modifies, as they are included some way or another in most files of the engine. I suspect that it's what happened, you thought that incremental builds did not work, set up caching, and then next update did not change `core/` so it was indeed fast.

**Comment by Andrettin** [comment]
> 
> It's not normal that it recompiles every time, it should reuse your existing build objects.
> 
> [As per the documentation](https://scons.org/doc/3.0.3/HTML/scons-user.html#chap-caching), the SCons cache is for:
> 
> > On multi-developer software projects, you can sometimes speed up every developer's builds a lot by allowing them to share the derived files that they build. SCons makes this easy, as well as reliable.
> 
> It's for sharing build artifacts, and in your case you're sharing them with yourself, but it should not make a difference compared to simply running SCons with cache and without cleaning artifacts beforehand.
> 
> Note that, cache or not, SCons will rebuild most of the projects if some `core/` files are modifies, as they are included some way or another in most files of the engine. I suspect that it's what happened, you thought that incremental builds did not work, set up caching, and then next update did not change `core/` so it was indeed fast.

It's good to know that it is supposed to not rebuild even without the cache environment variable, thanks for the information!

I'm afraid, however, that the cause must be something else: I even tried building twice in a row, and still it rebuilt everything in the second compilation. Maybe there is something amiss with my Scons setup?

**Comment by Andrettin** [comment]
I'm closing this, as since the env. variable isn't necessary for incremental builds, it is not so important to print that it is not set.

**Pull request closed without merging**
