### PR TITLE
Fix `@GlobalScope` and `@GDScript` at the bottom of the list

### LINKED ISSUE #63799: Documentation: @GDScript and @GlobalScope are at the bottom of the list
### Godot version

v4.0.alpha.custom_build [98c1fb396]

### System information

Windows 10

### Issue description

The `@GDScript` and `@GlobalScope` items are at the bottom of the list in the documentation search window. They used to be at the top.

image

### Steps to reproduce

* Press F1
* Look at the top and see that `@GDScript` and `@GlobalScope` are not there
* Scroll to the bottom to find them

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Mickeon**
Fix #63799

Shuffles the documentation generation around so that `@GlobalScope` and script language built-ins are  generated before anything else.

### CODE REVIEW

**Comment by Mickeon** [comment]
Honestly a personal peeve that I could've also done, in retrospective, is the fact that the function is one giant block instead of being split into multiple helper functions, which makes much more difficult to read.

**Comment by YuriSizov** [comment]
> although I wonder if the order of generation should be what decides this at all.

Indeed, it shouldn't. So as a solution to the problem presented, this is not a proper one. Beyond that I can't say at the moment what it'd affect, as I am not available.

**Comment by YuriSizov** [comment]
For the record, I'm working on these sorting improvements, but it's not so trivial and there are a few additional changes required to implement it proper, so no PR yet.

**Comment by AThousandShips** [comment]
Superseded by:
* https://github.com/godotengine/godot/pull/77554

Thank you nonetheless!

**Comment by Mickeon** [comment]
I will never financially recover from this burden

**Pull request closed without merging**
