### PR TITLE
implement 'OS::shell_show_in_explore()' for FilesystemDock and expose…

### PR DESCRIPTION
**Pull request by Daylily-Zeleen**
Implement 'OS::shell_show_in_explore()' for FilesystemDock and expose to GDScript.

Currently only implement for Windows, because I only have a windows device.
On other platforms, it will fallback to origin action.

I hope someone can implement for other platforms.

https://user-images.githubusercontent.com/61624558/190620562-66997ebe-1ba5-4b18-81f0-7f796c02d838.mp4

### CODE REVIEW

**Comment by YuriSizov** [comment]
What would be the benefit of this instead of using it as we currently do and let the system handle the file protocol scheme as it sees fit?

**Comment by Daylily-Zeleen** [comment]
> 

This only effective for the popop mune's item `Show in file manager`.
If a folder has many files, this can help you find target file more quickly.

**Comment by Daylily-Zeleen** [comment]
> 

Oh ....my garbage English....
Let me fix it

**Comment by akien-mga** [comment]
> Seems like it closes [godotengine/godot-proposals#3251](https://github.com/godotengine/godot-proposals/issues/3251) You made a typo in the method name though, it should be "explorer" not "explore".

I think if that's the use case for it, something like this is better than adding a whole new method:
https://github.com/godotengine/godot-proposals/issues/3251#issuecomment-922565182

**Comment by bruvzg** [comment]
> On other platforms, it will fallback to origin action.

On macOS, you can use the following code, no idea if there's a universal equivalent for Linux:

```obj-c++
NSArray* urls = [NSArray arrayWithObjects:[NSString stringWithUTF8String:p_uri.utf8().get_data()], nullptr];
[[NSWorkspace sharedWorkspace] activateFileViewerSelectingURLs:urls];
```

**Comment by Daylily-Zeleen** [comment]
> > On other platforms, it will fallback to origin action.
> 
> On macOS, you can use the following code, no idea if there's a universal equivalent for Linux:
> 
> ```objc++
> NSArray* urls = [NSArray arrayWithObjects:[NSString stringWithUTF8String:p_uri.utf8().get_data()], nullptr];
> [[NSWorkspace sharedWorkspace] activateFileViewerSelectingURLs:urls];
> ```
I can't debug on macos so I can't be responsible for this

**Comment by Daylily-Zeleen** [comment]
> > Seems like it closes [godotengine/godot-proposals#3251](https://github.com/godotengine/godot-proposals/issues/3251)
> 
> I think if that's the use case for it, something like this is better than adding a whole new method: [godotengine/godot-proposals#3251 (comment)](https://github.com/godotengine/godot-proposals/issues/3251#issuecomment-922565182)

I think this new method is a util for Plugin developer.

**Comment by Daylily-Zeleen** [comment]
I still can't squash commts, so I will close this one and open a new pr.

**Comment by Daylily-Zeleen** [comment]
Repalced by [#65906](https://github.com/godotengine/godot/pull/65906)

**Pull request closed without merging**
