### PR TITLE
migrate to container-based Travis CI

### PR DESCRIPTION
**Pull request by Marqin**
It will make Travis CI builds faster ( and prevent problems when non-container-based gets deprecated ).

### CODE REVIEW

**Comment by akien-mga** [comment]
If you feel like porting https://github.com/GodotBuilder/godot-builds/blob/master/.travis.yml next :P (probably harder, though apparently for osx we can still use brew install, so only the multilib stuff needs to be added I guess).

**Comment by Marqin** [comment]
W dniu poniedziałek, 7 marca 2016 Rémi Verschelde <notifications@github.com>
napisał(a):

> If you feel like porting
> https://github.com/GodotBuilder/godot-builds/blob/master/.travis.yml next
>

What do you think about breakin that into two branches? One for 64 and one
for 32 bits. It could be easier to maintain.

**Comment by akien-mga** [comment]
The problem is that for some platforms we need to build both arches in one build job, e.g. for iphone (as then we produce a universal binary for both arches using ``lipo``). Also the deploy happens only when pushing a git tag, so we'd have to push two tags each time to get all builds.

**Comment by Marqin** [comment]
iPhone is not a problem. The only platform I see that could be problematic
is X11 for 32/64 ( because of apt ). We will see.

W dniu poniedziałek, 7 marca 2016 Rémi Verschelde <notifications@github.com>
napisał(a):

**Pull request merged**
