### PR TITLE
fixes #2046 for custom themed buttons not working with pressed/focused action.

### LINKED ISSUE #2046: custom theme button decoration does not work. Font becomes erased upon pressing and in focused mode.
Following https://github.com/okamstudio/godot/wiki/tutorial_gui_skinning, I noticed that custom themed button does not properly display pressed/focused mode. Hover works.

### PR DESCRIPTION
**Pull request by choikwa**
+Fixes #2046 
+Added DRAW_FOCUSED and related necessary changes.
+Some formatting clean-ups.
+Tested working on x11 x84-64 Linux Mint 17 Qiana 14.04.2 LTS. 
  AMD R280 Open source driver

### CODE REVIEW

**Comment by reduz** [comment]
There should not be a need for DRAW_FOCUSED, use has_focus() instead. Many button types just draw focus as an overlay but need to know the current state of the button.

**Comment by choikwa** [comment]
I think the problem was that has_focused() with draw call was placed at the end of the Button::_notification, drawing over top of everything. I can remove DRAW_FOCUSED, draw as overlay as requested. (calling draw twice I assume). By overlay, I take it that people could draw translucent focused texture. Would you accept this?

**Comment by okamstudio** [comment]
yes, the problem is that the focus state is parallel to the other states
(pressed, hover), it is also drawn over the existing button, most commonly
transparent. I'm not exactly sure what else you want to change though



On Mon, Jun 8, 2015 at 10:18 AM, Kevin Choi <notifications@github.com>
wrote:

> I think the problem was that has_focused() with draw call was placed at
> the end of the Button::_notification, drawing over top of everything. I can
> remove DRAW_FOCUSED, draw as overlay as requested. (calling draw twice I
> assume). By overlay, I take it that people could draw translucent focused
> texture. Would you accept this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2047#issuecomment-109993161>.
>



-- 

*OkamStudio*

**Comment by choikwa** [comment]
Pretty much just moving focus draw call right after other stylebox draw so focus style doesn't clobber everything if it's opaque.

**Comment by reduz** [comment]
ok, let me check if this works and doesn't cause issues and will push a fix

**Pull request closed without merging**
