### PR TITLE
Fix crash on importing meshes without a material

### LINKED ISSUE #61665: Editor crashes when importing meshes without a material
### Godot version

4.0 alpha 9

### System information

Windows 10, Vulkan, NVIDIA GTX 850M

### Issue description

Importing a GLTF scene containing a mesh without a material consistently crashes the editor when clicking the material in the Material tab or trying to extract materials.

### Steps to reproduce

Bring the attached GLB to the file system (it is just a simple scene with a box mesh and no material assigned to it, exported from Blender 3.1), double click it to open the advanced import menu, go to the Material tab and click the empty material slot (or go to Actions... > Extract Materials and choose any folder)

The editor should crash.

### Minimal reproduction project

GLB Scene: [box.zip](https://github.com/godotengine/godot/files/8834482/box.zip)

### PR DESCRIPTION
**Pull request by Step-an**
Fix #61665.

The default material will not be added to a mesh when he is imported from a gltf scene with no material.

### CODE REVIEW

**Comment by fire** [comment]
Need to look into this. The existing design was made to fix vertex colors. so those test cases must still pass.

**Comment by cow-neaz** [comment]
The problem was fixed.

**Comment by lyuma** [comment]
As fire says, it is important to handle the default material. Note that in Godot, a missing material renders differently from a white albedo standard materails.

@cow-neaz I did not understand your comment. If the underlying issue was fixed and this PR is no longer needed, would it be possible for you to close this pull request?

**Comment by lyuma** [comment]
Sorry I missed that the PR was updated. Now it sets a property on the material, and then looks for it on the scene import dialog?

I'm still extremely confused why this change is needed. If certain materials are causing the scene importer dialog to crash, I think we should solve that issue directly, rather than add a flimsy special case like this.

**Comment by lyuma** [comment]
The editor should not crash if a material has empty name, so that seems good to fix.

I'd also be in favor of giving the default material a name, such as "Default".

I think either or both of these would be preferable to adding a special case tag like `"ignore_import_material"`

**Comment by cow-neaz** [comment]
Ok I solved both problems.

**Comment by fire** [comment]
@lyuma I think the material can be left to the default name. Thoughts?

**Comment by trollodel** [comment]
See also #59834. The fix done here is very similar to the one done in the other PR.

**Comment by akien-mga** [comment]
Superseded by #59834.

**Pull request closed without merging**
