### PR TITLE
Remap roughness to [0.5,1] to prevent extreme gain with shiny surface…

### PR DESCRIPTION
**Pull request by ghost**
…s in GGX.

As described by Burley (2012), and also Karis (2013).

### CODE REVIEW

**Comment by groud** [comment]
cc @reduz

**Comment by tagcup** [comment]
This is a bit ad hoc (like many things in the literature I'm afraid), but, furthermore, according to Burley's 2015 notes, they replaced this with something else from another paper, which I'll check sometime next week

**Comment by Hinsbart** [comment]
@tagcup: There seem to be conflicts now.

**Comment by Zireael07** [comment]
Why close?

**Comment by tagcup** [comment]
Like I mentioned above, this mapping has been abandoned in practice.

**Comment by tagcup** [comment]
Forgot to mention, #11818, which is based on Burley's talk in SIGGRAPH 2015, supersedes this.

**Pull request closed without merging**
