### PR TITLE
Ambiguous Filenames in Editor

### LINKED ISSUE #20029: Two files of the same name should be desambiguified in the editor tabs
Godot 3.0.4

In a project, when two scripts or two scenes from different locations have the same name, tabs are listing them with the same name, however it makes it hard to tell which is which:

image

image

In that case, it would be better if the scene or script editors could desambiguify what tabs are showing, by including the parent folder in the name until all tabs have a different title.

For example:
image

### PR DESCRIPTION
**Pull request by rileylyman**
This fixes #20029. Whenever there are two or more tabs or scripts open in the editor, this will append the file path of scripts or scenes to the end of their names so that you can easily differentiate between them. 
disambig_example

With "test.gd", the ones that aren't in the root directory have their paths attached to the end, the same thing happens with "dungeon.tcsd". If there is only one file open with the name "dungeon" or "test.gd", however, then their names will stay the same. 

As for the style, I tried to mimick the example given in #20029. 

**Edit:**
I changed the style of the disambiguation as per @groud 's comment, and I have made it so it now only includes the parent folder of each file until they are no longer ambiguous. 

disambig_example_update

### CODE REVIEW

**Comment by rileylyman** [comment]
You’re right, it could get pretty complicated. I’ll go change that.

**Comment by groud** [comment]
> I'm not sure how difficult it is, but I would prefer to show only the parent folder if that is unambiguous. Then if the parent folder happen to be the same name, add another level and keep doing that until it disambiguate.

I such case, I think we can move the folder path to the left of the file. This list would look somehow like:
```
another/test.gd
test.gd
```

**Comment by rileylyman** [comment]
Groud, I will implement that as well.

**Comment by rileylyman** [comment]
I implemented the suggestions above in my latest commit.

**Comment by groud** [comment]
> a tooltip could still show the full path :)

This is a really good idea :)

**Comment by blurymind** [comment]
Why thank you :) 
Godot can take advantage of tooltips in so many other areas too.
They are a great way to add useful information

**Comment by akien-mga** [comment]
Could you squash the commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by rileylyman** [comment]
@akien-mga Done. @blurymind For me, a tooltip does show the full path already for script files, is this what you meant?

**Comment by blurymind** [comment]
@rileylyman yeah :D Excellent

**Comment by Paulb23** [comment]
Tried this one out locally, It seems to get caught in an infinite loop as `duplicates_exist` is never false when there are multiple duplicated file names e.g:
```
"res://test.gd"
"res://another_test.gd"

"res://folder/test.gd"
"res://folder/another_test.gd"
```

**Comment by rileylyman** [comment]
@Paulb23 You're right, I need to append the name of the file when checking if duplicates exist. Thanks for the catch!

**Comment by aaronfranke** [comment]
@rileylyman Once you address the above feedback please change the title of this PR to be less ambiguous :) Something like "Conditionally append folder names to distinguish files".

**Comment by akien-mga** [comment]
Any update on fixing the reported infinite loop?

**Comment by rileylyman** [comment]
I have a solution but want to make sure it is optimal. Will push soon.

**Comment by akien-mga** [comment]
> I have a solution but want to make sure it is optimal. Will push soon.

Any update? :)

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and release freeze for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

Note: If it's merged after 3.1-stable is released, this change might be considered for cherry-picking into a later 3.1.x release.

**Comment by akien-mga** [comment]
I'd like to merge this, but it's still pending a fix for this bug: https://github.com/godotengine/godot/pull/20930#issuecomment-412990154

Would you have any time to handle that @rileylyman, or should we ask other contributors to pick it up from there?

**Comment by akien-mga** [comment]
Since it's not getting updated, I have no solution but to close this PR.

I marked it as salvageable, so any interested contributor is welcome to make a new PR based on this and fixing the outstanding issues (if you do, be sure to keep the original author credits if you reuse this code, and add yourself as `Co-authored-by:`.

**Pull request closed without merging**
