### PR TITLE
Improve String.format() documentation

### PR DESCRIPTION
**Pull request by timothyqiu**
I tried to documentation its behavior and added some code examples.

Any correction is welcome :)

### CODE REVIEW

**Comment by akien-mga** [comment]
See also #59323 which aims at improving the same docs. I wasn't convinced yet by the wording but not sure what to comment exactly, might be worth cross-reviewing and merge the best bits of both.

Overall I'm confused by the talk about placeholders and `_` but there are no examples that seem to make use of this?

**Comment by timothyqiu** [comment]
Ah, I didn't know there's an existing PR...

`format()` does not work like regular format functions such as `printf()` and Python `str.format()`. It works by going through `values` and do a replace-all for each element:

```python
result = current_string

match typeof(values):
    Dictionary:
        # This is the most straight forward case.
        # For format({id=42, name="Godot"}, "{_}"), it:
        # 1. Replace all occurrences of "{id}" with 42
        # 2. Replace all occurrences of "{name}" with "Godot"
        for key, value in values:
            result = result.replace_all(placeholder.replace_all("_", key), value)

    Array:
        for index, element in values:
            if element is Array:
                assert(element.size() == 2)
                # So that a nested array is handled as a key-value pair.
                result = result.replace_all(placeholder.replace_all("_", element[0]), element[1])
            else:
                if "_" in placeholder:
                    # Works like Dictionary case, use array index as key.
                    result = result.replace_all(placeholder.replace_all("_", index), element)
                else:
                    # This allows you to omit indices.
                    result = result.replace_first(placeholder, element)

return result
```

In most use cases, `placeholder` is either `{_}` or `{}`.

Each underscore will be replaced by the key, so the following snippet works. But I don't think there's any valid use cases for it.

```gdscript
print("{0000} {1111}".format(["Hello", "World"], "{____}"))  # Hello World
print("{ididid}".format({id=42}, "{___}"))  # 42
```

**Review by akien-mga — APPROVED** [review]
Seems fine, but heck is it convoluted... I feel this was really overengineered, and should likely be simplified in the future.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
