### PR TITLE
Remove dead function win32_spawn from methods.py

### PR DESCRIPTION
**Pull request by Anutrix**
Remove dead function win32_spawn from methods.py.

### CODE REVIEW

**Comment by akien-mga** [comment]
For context, this was used back when Godot was open sourced for the `android`, `bb10` and (WIP, abandoned) `flash` platforms.

Its use was disabled for `android` in 9983ceecf25a4110793aeeae0378b2b50316f34d and both `bb10` and `flash` ports were dropped in 2016.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Actually, please amend the commit log to be written in English and not as snake_case. A commit log is a readable message for other contributors, not a branch name/code identifier. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by Anutrix** [comment]
> 
> 
> Actually, please amend the commit log to be written in English and not as snake_case. A commit log is a readable message for other contributors, not a branch name/code identifier. See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

Done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
