### PR TITLE
Improve demos code formatting and update to 2.0

### LINKED ISSUE #2712: Update all demo resources to 2.0 format
As the title says. Currently some demos are still using pre-1.0 formats (see e.g. #451).

### PR DESCRIPTION
**Pull request by akien-mga**
Fixes #2712.

The scripts were streamlined using more or less the following conventions:
- space after a comma in lists of arguments
- spaces around weak operators (+, -), no spaces around strong operators (*, /)
- spaces around comparison operators and compound assignment operators
- space after a comment start (#)
- removed trailing spaces or tabs, apart from those that delimit the function indentation level (those could be removed too but since they are added automatically by the editor when typing code, keeping them for now)
- function blocks separate by two newlines
- comment sentences start with an upper-case letter

The scene files were resaved with the (current) 2.0 format, and some scenes that were in XML format were converted to SCN, to be consistent across all demos.

### CODE REVIEW

**Comment by akien-mga** [comment]
I haven't done the demos/2d folder, as it took some time already for the rest and I'd like to check that the code formatting I chose is relatively consensual :)

**Comment by reduz** [comment]
branch has conflicts, can you check it out?

**Comment by akien-mga** [comment]
I'll have a look tomorrow, conflicts on binary files are a pain to handle :/

**Comment by akien-mga** [comment]
Alright I managed to rebase :)

**Comment by akien-mga** [comment]
I'll merge it now to prevent further conflicts ;)

**Pull request merged**
