### PR TITLE
Implemented DirAccess get_drive and get_drive_count for OS X

### PR DESCRIPTION
**Pull request by marcelofg55**
File dialog will now show the volumes on OS X.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Congrats for the nice PR number :smiley:

**Comment by marcelofg55** [comment]
Haha thanks!

**Comment by hpvb** [comment]
I don't really know what MacOS users expect to see or if it's common for a MacOS user to have permanently mounted separate partitions. 

Assuming that this is idiomatic for MacOS users: LGTM 😄

**Comment by marcelofg55** [comment]
This is an example of the file dialog with this PR:
screen shot 2017-09-11 at 11 46 00 pm

I believe this is what's expected on Mac. At least it's what I would expect :).

**Comment by hpvb** [comment]
I know nothing about MacOS so this is probably a dumb question: but what is '/net'? Is that a useful thing where you may want to save/load data from as a Godot user?

**Comment by marcelofg55** [comment]
I've never used /net myself but it seems to be useful if you have a NFS server (ref: https://apple.stackexchange.com/questions/72762/what-are-the-home-and-net-folders-i-see-within-finder)

**Comment by hpvb** [comment]
This seems like it could do with some field-testing regardless. If MacOS users complain in a2 we can change it, but we'll never know if we don't try 👍

**Pull request merged**
