### PR TITLE
Updated getters and setters names for toplevel

### PR DESCRIPTION
**Pull request by Duroxxigar**
Fixed some missed text renames. Refactor missed the string parts. My mistake.

*Bugsquad edit:* Follow-up to #42451

### CODE REVIEW

**Comment by bruvzg** [comment]
Missed some more:

https://github.com/godotengine/godot/blob/19f72beebbf1d233eb2dd345ed70a5ac143e2353/scene/3d/soft_body_3d.cpp#L428

https://github.com/godotengine/godot/blob/8de57bde13cf48c6d5c54c717ab5c7b973915939/modules/bullet/space_bullet.cpp#L962-L963

https://github.com/godotengine/godot/blob/19f72beebbf1d233eb2dd345ed70a5ac143e2353/scene/main/canvas_item.cpp#L1139-L1140

There's also `is_toplevel_control` in the `Control` and `_toplevel_raise_self`, in the `CanvasItem` probably should be changed too for consistency.

**Comment by akien-mga** [comment]
And I saw some `p_toplevel` parameters which should likely also be changed.

**Comment by Duroxxigar** [comment]
There were some other ones, but they were topLevel, so I believe they are not used for the same purposes.

**Review by AndreaCatania — APPROVED** [review]
Approved, though `is_set_as_top_level` should be `is_top_level` to adhere to Godot standards.
Also `set_as_top_level` could just be `set_top_level`, not need of extra verbosity.

**Comment by bruvzg** [comment]
Translations are done on [Weblate](https://hosted.weblate.org/projects/godot-engine/godot-class-reference/), changing text in any of the `.po` or `.pot` files is pointless, all changes will be overwritten when it is synced with Weblate.

> There were some other ones, but they were topLevel

It's in `thirdparty` and should not be touched anyway.

**Comment by Duroxxigar** [comment]
@bruvzg I thought something like that honestly - but I didn't want to risk it. Good to know for future PR's.

**Comment by akien-mga** [comment]
I'll merge as is as it improves on the previous PR and fixes some errors.

This comment is still worth discussing and possibly implementing as a follow-up if we agree:

> Approved, though `is_set_as_top_level` should be `is_top_level` to adhere to Godot standards.
> Also `set_as_top_level` could just be `set_top_level`, not need of extra verbosity.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
