### PR TITLE
Fix highlighting of hex numbers with separators

### PR DESCRIPTION
**Pull request by MewPurPur**
image

^ Fix this

### CODE REVIEW

**Review by adamscott — APPROVED** [review]
image

It works!

**Comment by dalexeev** [comment]
I noticed this in #73203 but forgot to fix it, thank you. Can you please edit line 330 by the way:

```diff
-    !(str[j] == '.' && (prev_is_digit || (!prev_is_binary_op && (j > 0 && (str[j - 1] == '-' || str[j - 1] == '+' || str[j - 1] == '~'))))) &&
+    !(str[j] == '.' && (prev_is_digit || (!prev_is_binary_op && (j > 0 && (str[j - 1] == '_' || str[j - 1] == '-' || str[j - 1] == '+' || str[j - 1] == '~'))))) &&
```

This is for `.` after `_` (for example `1_.2`) is highlighted in number color.

**Comment by MewPurPur** [comment]
Doned

**Review by dalexeev — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
