### PR TITLE
Load binaryname.pck

### PR DESCRIPTION
**Pull request by masoudbh3**
in linux and windows if not found data.pck , search for binaryname.pck and load that.

### CODE REVIEW

**Comment by punto-** [comment]
You could also search for binaryname.pcz

**Comment by akien-mga** [comment]
> You could also search for binaryname.pcz

The commit does it :)

**Comment by punto-** [comment]
Writing zips would be great, I've needed to create and debug my own pcks
many times.

For the extension I don't mind either way, zips have many names nowadays,
starting from the first Quake packages (that's actually where I found out
about minizip, the library we use to read zips, the original Quake source),
but also IPA, APK, etc. I suspect their reasoning is just to stop the
operating system (and random users on some cases) from handling them, and
to possibly associate the extension with their own program, which I'm not
sure it's worth it for us.. We did have to rename the templates package for
similar reasons a while ago..

**Comment by reduz** [comment]
I will probably need to add some changes (noting down)
-writing and reading zips
-deprecating expecting data.pck and only use the code provided by this patch

**Comment by akien-mga** [comment]
> -writing and reading zips

For this part I've opened #2879.

**Comment by akien-mga** [comment]
> -deprecating expecting data.pck and only use the code provided by this patch

I opened #3313 for this one, so that it can be further discussed/implemented.

**Pull request merged**
