### PR TITLE
[RTL] Add `pop_all`, `push_context` and `pop_context` methods, and use it for `print_rich` to avoid unclosed tags.

### LINKED ISSUE #78520: Printing with print_rich a lot of colored text breaks formating after output overflow.
### Godot version

4.1 

### System information

Win 10

### Issue description

image

When causing _"output oveflow"_ by printing a lot of text, formating breaks. Possible because enclosing tag get flushed.

Suggested solution: clear text formating after _output oveflow_ warning.

### Steps to reproduce

Print a lot of text with different text tags (like [color] or [bgcolor]) to console. For example in _process function.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/78520

| Before | After |
| -- | -- |
| Screenshot 2023-07-04 at 09 50 44 | Screenshot 2023-07-04 at 09 51 06 |

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]

**Comment by MewPurPur** [comment]
Are there any benefits to doing this other than less code? Just curious if I should still do things the old way unless necessary.

**Comment by bruvzg** [comment]
> Are there any benefits to doing this other than less code?

`pop_all` should be faster, but in real use cases it's probably won't have any visible effect. The only real advantage, there's no need to count `push_` calls to match with the same number of `pop`s.

**Comment by YuriSizov** [comment]
> The only real advantage, there's no need to count `push_` calls to match with the same number of `pop`s.

I believe in our built-in documentation we have plenty of cases where we need to pop N levels from the stack, but not all of it. Would something like a scope or a context make sense as well?

```
push_context(); // Start counting pushes.
push_...();
push_...();
push_...();
push_...();
pop_context(); // Pops 4 stack levels and removes context.
```

**Comment by bruvzg** [comment]
Added `push_context` / `pop_context` as well.

**Review by YuriSizov — APPROVED** [review]
Lovin' it!

**Comment by YuriSizov** [comment]
Thanks! Now someone could do a pass simplifying calls in the built-in help :)

**Comment by MewPurPur** [comment]
Code simplification with new methods? I'm in.

**Pull request merged**
