### PR TITLE
KinematicBody2D api most friendlier

### PR DESCRIPTION
**Pull request by aroncds**
Hello Guys,

I did a copy and pastes of the commit #6d233c651b21ecaef78fbb20d0365a22919b72b1 @reduz, for the KinematicBody2D, to mantent a default.

And fix an error of the index on the _get_slide_collision, when i have a element on the position 0 and o size of slide_colliders was 0, he no resize the vector.

I don't know, if you has others plan for the KinematicBody2D, but it's here, if need.

Sorry my english!

### CODE REVIEW

**Comment by aroncds** [comment]
I fix the code pattern

**Review by akien-mga — APPROVED** [review]

**Comment by toger5** [comment]
Another question about the physics body code.

Why is the move function called _move??

**Comment by aroncds** [comment]
I agree with you! Is a bit confused! If nobody change, saturday i do some improvements!

**Comment by toger5** [comment]
@aroncds I recently did a pr for it.

**Comment by aroncds** [comment]
ahh ok!

**Pull request merged**
