### PR TITLE
Make get_node return NULL for empty NodePaths

### LINKED ISSUE #25292: Empty exported NodePath points to self
**Godot version:**
Godot 3.1 beta 2 

**OS/device including version:**
Ubuntu 18.04 64bit

**Issue description:**
In Godot 3.1 when you create exported NodePath it will for some reason act like it's containing "." path. `NodePath.is_empty()` method will return false and  `has_node()` and `get_node()` will act like NodePath is containing "."

**Steps to reproduce:**
Short way:
1. Download reproduction project and run EmptyNodePathLinks2Self scene

Manual way:
1. Create new scene and attach following script to root node:
```
extends Node

export (NodePath) var path = NodePath();

func _ready():
	if(has_node(path)):
		print(get_node(path))
		print("I have nodepath to: ", get_node(path).get_name())
		assert false

```
2. Run the scene

**Minimal reproduction project:**
[EmptyNodePathLinks2Self.zip](https://github.com/godotengine/godot/files/2793056/EmptyNodePathLinks2Self.zip)

### PR DESCRIPTION
**Pull request by ptrojahn**
Fixes #25292

### CODE REVIEW

**Comment by reduz** [comment]
Makes sense, but may break compatibility?

**Comment by akien-mga** [comment]
Slight compat breakage yes, but of the kind that we allow for minor releases (cc @Calinou to mention it in upcoming 3.2 changelog). Can't be cherry-picked for 3.1.x though.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
@akien-mga Added to changelog.

**Pull request merged**
