### PR TITLE
[3.x] Use Bullet's convex hull computer in place of QuickHull when available.

### LINKED ISSUE #45946: QuickHull generates bad hull sometimes when multiple triangles share the same plane.
**Godot version:**
3.2.3
3.2.4.rc2

**OS/device including version:**
Windows 10

**Issue description:**
QuickHull fails to merge edges sometimes and results in generating multiple of the same plane and wrong geometry.  Errors printed to the log include things like:
 core\math\quick_hull.cpp:402 - Condition "O == 0" is true. Continuing.
 core\math\quick_hull.cpp:399 - Condition "!F" is true. Continuing.
 core\math\quick_hull.cpp:428 - Condition "!F2" is true. Continuing.

Example:
image
Edit: Just tried in 3.2.4.rc2, and the result was slightly different, but still broken:
image
(Should just be an octagon)

**Steps to reproduce:**
Generate a convex collision from something like a cylinder or another object that has many triangles on the same face, preferably at some odd angle.  Doesn't always reproduce.

**Notes:**
I've stepped through the QuickHull::build() function, and the problem seems to reside in the logic to merge faces and remove edges on a single plane.  It makes some assumptions about the structure/order of vertices.  If things overlap instead of being next to each other, the algorithm falls apart.  When the errors happen, extra planes are left in the hull that shouldn't be there.

It might be better to just generate the the planes, ignoring edges and verts, then generate the edges and verts at the end based on plane intersections.  It would also be nice if the edge generation was optional, because it's only necessary when displaying the hull, not when using it for collision purposes.

**Minimal reproduction project:**
[test_quickull.zip](https://github.com/godotengine/godot/files/5975048/test_quickull.zip)

### PR DESCRIPTION
**Pull request by mortarroad**
Fixes #45946, maybe more.

### CODE REVIEW

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
This is a good idea and it seems to work well!

There are just two things I would like to address before approving:
- This change adds a dependency to VHACD module in Godot Physics, so given that the old QuickHull code is very small, I'd like to keep it as an alternative in case the engine is compiled with VHACD disabled (see my review comment).
- Another PR needs to be opened on master to keep the codebase in sync. The usual process is to open a PR on master first, and then the changes can be cherry-picked on 3.x when possible. In this case the file names have changed on master, so it makes sense to keep this separate 3.x PR.

**Comment by mortarroad** [comment]
Superseded by #47332

**Comment by pouleyKetchoupp** [comment]
This PR can stay open, since it would still be nice to have this fixed on 3.4 as well and the file names have changed.
Sorry for the confusion, in my previous comment I just meant that it would need an extra PR on master.

**Comment by lawnjelly** [comment]
And just to note I'm using quick hull in several modules (and I presume others are too) and also in the rooms / portals PR. So keeping the old version available would be very useful (any replacement would have to be a drop in replacement, and always available).

**Comment by mortarroad** [comment]
> And just to note I'm using quick hull in several modules (and I presume others are too) and also in the rooms / portals PR. So keeping the old version available would be very useful (any replacement would have to be a drop in replacement, and always available).

That's the plan. QuickHull will remain available. 
And it should be possible to simply replace any call to `QuickHull::build`  with `Geometry::build_convex_hull`.
Take a look at the PR against master for reference.

**Comment by jitspoe** [comment]
Does this VHACD have the same issue that the Mesh::convex_decompose() did?  If I recall correctly, that also used the VHACD algorithm, and when "convcolonly" for mesh imports was updated to use that instead of quickhull, it would result in incorrect collision (ex: a simple box would have the verts slightly off).

**Comment by mortarroad** [comment]
@jitspoe I have not done much testing, but I assume that this algorithm is precise.
As you mentioned, this does not actually use VHACD; it simply uses what's provided by Bullet, which happens to be included in that module.
The reason is to allow compilation with Bullet disabled, as mentioned here: https://github.com/godotengine/godot/issues/41522#issuecomment-803033167

**Comment by pouleyKetchoupp** [comment]
@jitspoe From what I've tested with basic primitives, the Bullet convex hull algorithm itself doesn't introduce the problem you mentioned (https://github.com/godotengine/godot/issues/29971).

**Comment by akien-mga** [comment]
Superseded by #48533.

**Pull request closed without merging**
