### PR TITLE
Removed ParamDef and ParamHint structs

### PR DESCRIPTION
**Pull request by Rubonnek**

### CODE REVIEW

**Comment by volzhs** [comment]
this pr makes compile error from https://github.com/godotengine/godot/blob/master/core/class_db.cpp#L49
why should this be removed?

**Comment by neikeq** [comment]
It's not used anywhere.

**Comment by volzhs** [comment]
oh, then core/class_db.cpp should be updated too.

**Comment by Rubonnek** [comment]
Updated `core/class_db.cpp`.

**Pull request merged**
