### PR TITLE
Fix Animation Playback Track not Seeking Properly

### PR DESCRIPTION
**Pull request by BruceLiCong**
Reapply bugfix https://github.com/godotengine/godot/pull/38107

### CODE REVIEW

**Comment by BruceLiCong** [comment]
Hi @akien-mga, my project is blocked by the issue. Could you help to review the PR as soon as possible, thanks

**Comment by Zireael07** [comment]
@BruceLiCong Please don't ping Akien (you did it on both your PRs)

**Review by TokageItLab — APPROVED** [review]
It seems that the regression was caused by https://github.com/godotengine/godot/pull/80813 because the fix in https://github.com/godotengine/godot/pull/38107 was applied to AnimationPlayer but not to AnimationTree since the AnimationMixer was implemented based on the AnimationTree.

However, there are many other potential problems with the AnimationPlaybackTrack, so we are planning to rework the playback process of AnimationPlaybackTrack in the future as https://github.com/godotengine/godot-proposals/issues/8783.

Well, this fix might fine for 4.3.

**Comment by BruceLiCong** [comment]
> It seems that the regression was caused by #80813 because the fix in #38107 was applied to AnimationPlayer but not to AnimationTree since the AnimationMixer was implemented based on the AnimationTree.
> 
> However, there are many other potential problems with the AnimationPlaybackTrack, so we are planning to rework the playback process of AnimationPlaybackTrack in the future as [godotengine/godot-proposals#8783](https://github.com/godotengine/godot-proposals/issues/8783).
> 
> Well, this fix might fine for 4.3.

Thanks for the updates!

**Comment by akien-mga** [comment]
Superseded by #89794. Thanks for the contribution!

**Pull request closed without merging**
