### PR TITLE
Add secondary alignment for BoxContainer

### LINKED ISSUE #9504: Add secondary alignment to BoxContainer
**Operating system or device - Godot version:**

The parameter `alignment` of BoxContainer works perfectly in the GUI layout.  But we still hard to control the *secondary* alignment of child nodes in BoxContainers. Like the picture shows

BoxContainer for now

Neither the horizental alignment of nodes in VBoxContaoner nor the vertical alignment of nodes in HBoxContainer could be changed. The secondary alignment is always be `center`.

So I hope we can have another parameter to control this layout behavior like `align-items` in flexbox

image

### PR DESCRIPTION
**Pull request by Geequlim**
*(bugsquad edit)* Fixes #9504.

### CODE REVIEW

**Comment by ObaniGemini** [comment]
Surely more user friendly.

**Comment by Geequlim** [comment]
@akien-mga @reduz 
Are you going to mege the feature with commit #7c679dd830 into 2.1?

**Comment by akien-mga** [comment]
@Geequlim I guess we could try, to keep a similar API in 2.1 and 3.0, but doesn't 7c679dd break compat?

**Comment by reduz** [comment]
On 3.0 this was already implememted in a different way

**Comment by akien-mga** [comment]
Closing as I'd prefer not to add diverging APIs in 2.1 now as 3.0 is going to be released. But I'd be ready to consider a PR that backports 7c679dd to 2.1 while ensuring that it doesn't break compatibility with existing projects.

**Pull request closed without merging**
