### PR TITLE
Add "-rigid" postfix import feature to create rigid bodies

### PR DESCRIPTION
**Pull request by jay3d**
For the third time.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks like your git GUI is really playing you tricks, you must be using the wrong feature to update your branch :/

**Comment by jay3d** [comment]
I think it's fixed now, those Git GUIs are so confusing :/

**Comment by TheoXD** [comment]
Wait, it's just going to create a rigidbody with BoxShape? Doesn't seem like a generic solution to me. Once we get convex-convex and trimesh-trimesh collision, it would make sense to generate those rather than a box collider.

**Comment by jay3d** [comment]
TheoXD - I think something better than nothing, and this will provide some boost for high number of physical objects, say something like a brick wall.

**Comment by slapin** [comment]
@TheoXD convex-convex works for me as long as convex-trimesh, Sometimes it is stuck,
but still.
In generic case BoxShape is enough, but elaborating to convex would be great.
I think adding convex support can be done later, it is useful as it is now.
@jay3d Thanks for good work!

**Comment by jay3d** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/phg6KQQVNtQ" frameborder="0" allowfullscreen></iframe>

**Pull request merged**
