### PR TITLE
Fix unwanted restarting

### LINKED ISSUE #20294: Godot always restarts when closed.
Regression caused by c69de2ba46463adeadf90f38660d6b6e034d7e0b.

### PR DESCRIPTION
**Pull request by volzhs**
Fix #20294

### CODE REVIEW

**Comment by volzhs** [comment]
@akien-mga @mhilbrunner it's pretty annoying and I think this PR doesn't break anything, so I'll merge it.

**Comment by aaronfranke** [comment]
I think this is probably a good change but in the future I'd recommend leaving the PR up for comments for awhile before merging it. Perhaps a day.

**Comment by volzhs** [comment]
yeah. 99% of my PR was left to be merged by @akien-mga or @mhilbrunner or others.

**Comment by mhilbrunner** [comment]
I think such decisions are always all nuance and there isn't an objective right way.

Generally, waiting for a day or such is of course better, you're right; but its a tradeoff; the simpler the change and the more annoying the quirk it fixes, the more reasonable it is to merge and ask for forgiveness. ;)

In this case it was fine, I think.

**Comment by akien-mga** [comment]
This was fine merging right away, the fix is obviously correct.

**Pull request merged**
