### PR TITLE
fix: emit target_reached signal after updating state

### PR DESCRIPTION
**Pull request by sambriels**
Backport to 3.x for the fix in #67939, as discussed in that PR

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase to fix iOS build issue (since fixed in `3.x`).

**Comment by sambriels** [comment]
✅  @akien-mga

**Comment by akien-mga** [comment]
Thanks!

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2

**Pull request merged**
