### PR TITLE
Add constant to avoid the use of arbitrary-looking values in websockets

### PR DESCRIPTION
**Pull request by AinaSG**
Been trying WebSockets (cool stuff there BTW) and noting some stuff that as a user feels weird, been playing around to improve usability and readability (the user does not see a seemingly, from user's point of view, arbitrary value), please tell me if I step on somebody toes of I use non-standard Godot style.

This adds the possibility to use:
client.get_peer(WebsocketPeer.SERVER)
instead of
client.get_peer(1)

I don't know if SERVER is the best name for it. I guess it's the first one that comes to your mind when programming , but I think is not 100% technically accurate or know if it follows Godot's naming conventions.

### CODE REVIEW

**Comment by akien-mga** [comment]
That's actually not specific to WebSockets though, it's the same in all the high level multiplayer API: http://docs.godotengine.org/en/latest/tutorials/networking/high_level_multiplayer.html#managing-connections

**Comment by akien-mga** [comment]
But I agree that making it a constant wouldn't hurt.

**Comment by AinaSG** [comment]
Oh right! Still haven tried hlmpAPI. So you thing it's good Idea to move it to a higher Level? Or better add another constant in the other side to keep readibility? (As PacketPeer.SERVER might feel unrelated to the user in Websocket space)?

**Comment by Faless** [comment]
As cryptic as it can be, it's basically `NetworkedMultiplayerPeer.TARGET_PEER_SERVER`
https://github.com/godotengine/godot/blob/master/core/io/networked_multiplayer_peer.cpp#L61

But I agree, even if we update the docs it would look funky to use that constant in a non himpa context.
So It think this PR is fine, maybe, just for clarity define the enum as:

```
enum {
    SERVER = TARGET_PEER_SERVER
};
```

**Comment by AinaSG** [comment]
Haven't seen this constant. This makes more sense and allows for different implementations

**Comment by AinaSG** [comment]
Haven't seen this constant. This makes more sense and allows for different implementations.
Seeing now how it is defined in NetworkMultiplayerPeer, I understand now how it works, but the constant is defined in a different implementation of PacketPeer, so I do not think is good praxis to reference this from the WebsocketPeer sibling class, it's a weird situation I see...  Maybe move it up to the superclass? or maybe or redefine it in each subclass? I don't know if this would break

**Comment by AinaSG** [comment]
Hey, moved the constants up but kept the bindings as both compatibility and programming helpers (For example, i don't know if the broadcast makes sense in the websocket case, so it's not binded). I think this is cleaner than referencing a sibling class.... But I don't know if those constants are inherent of it, so maybe it needs to be defined in both.

**Comment by Faless** [comment]
I don't think moving it to packet_peer is okay though, in many cases it has no meaning there.

Either create brand new constants in `WebSocketPeer` like you did before, or, we could just tell users to use:
`client.get_peer(WebSocketClient.TARGET_PEER_SERVER)` (which we could alias as `SERVER_PEER`).
As

**Comment by AinaSG** [comment]
You are right hahah, I thing I'm just messing everything up a lot.

**Comment by akien-mga** [comment]
So what should be done in the end?

**Comment by Faless** [comment]
@AinaSG , in the end, I think your original proposal of just adding a value `WebSocketPeer.SERVER_ID` is the best solution. Could you update your PR?
Sorry for the mess :-(

**Comment by AinaSG** [comment]
Yes! I think having separate constants us the way2go. Will fix tomorrow
morning when having a computer. Thank you everyone! ^^

El dg., 3 març, 2019 16:01, Fabio Alessandrelli <notifications@github.com>
va escriure:

**Comment by bojidar-bg** [comment]
(Pretty bump, hope you found your computer)

**Comment by akien-mga** [comment]
Ping :)

**Comment by akien-mga** [comment]
Closing for now as this PR is stale.

**Pull request closed without merging**
