### PR TITLE
Remove the unused error code

### LINKED ISSUE #69420: Godot was supposed to have no jokes
### Godot version

All versions

### System information

All systems

### Issue description

When I found out that my printer can't throw `ERR_PRINTER_ON_FIRE` I was going to report it, however, I was told that the error message is just a joke. But in [this twitter thread](https://twitter.com/reduzio/status/1557418984034766849), lead developer Reduz said that no jokes is best, so I don't think it's intentional.

### Steps to reproduce

1. Set a printer on fire
2. Try to access the printer and notice that `ERR_PRINTER_ON_FIRE` is not thrown.

</parody> (I don't want Elon Musk to ban me)

### Minimal reproduction project

the steps are trivial

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/69420 (hope nobody will be too sad or angry about the removing the unfunny easter egg).

### CODE REVIEW

**Comment by Chaosus** [comment]
WDYT about just leaving the comment instead? - It's still be an Easter egg, but nobody will complain about it?

**Comment by Chaosus** [comment]
like:

	ERR_SKIP, // (45)
	ERR_HELP, ///< user requested help!!
	ERR_BUG, ///< a bug in the software certainly happened, due to a double check failing or unexpected behavior.
	// ERR_PRINTER_ON_FIRE, /// the parallel port printer is engulfed in flames
	ERR_MAX, // Not being returned, value represents the number of errors
};

**Comment by MewPurPur** [comment]
This makes the executable 69 bytes smaller, which aligns with Godot's philosophies. Go for it, I would say.

**Comment by MewPurPur** [comment]
Nah, fr though, I don't have an opinion on this.

**Comment by Chaosus** [comment]
Lets the @akien-mga, @Calinou to decide. Or leave it for PR-meeting.

**Comment by akien-mga** [comment]
I can't read into the various degrees of irony or seriousness from comments here and on the original joke issue, but honestly I don't have time for this :)

**Comment by mhilbrunner** [comment]
Agree with Akien. Please lets focus on fixing actual bugs for now instead of bikeshedding harmless easter eggs.
Let me note that I agree with this change actually, but this is not the right time to discuss it - we're in feature freeze, this is a (small) change to API thats not really vital right now IMO.

Let's focus on getting the engine RC ready.

**Pull request closed without merging**
