### PR TITLE
Add icon for the Decal node

### PR DESCRIPTION
**Pull request by YeldhamDev**
Very simple design, but I think it gets the point across.

Depends on #37861 being merged first, of course.

### CODE REVIEW

**Comment by clayjohn** [comment]
Oooh, I really like it! Something like this would be really nice for the new ``*SkyMaterials``. If you are interested in making icons, ``PanoramaSkyMaterial`` ``ProceduralSkyMaterial`` and ``PhysicalSkyMaterial`` all need some.

**Review by Calinou — APPROVED** [review]

**Comment by reduz** [comment]
I have to admit its nice, but it took me a while to figure out what it is... I was thinking a stamp might be more obvious.
image

**Comment by akien-mga** [comment]
I like the "sticker" design.

The stamp is also nice, but my first thought was that it was a chess pawn, so I'm not sure it will be clear for everyone.

Before seeing any proposal, my idea was an icon that would be like paint splatter/splash, but it might not work well in our small icon size.

**Comment by YeldhamDev** [comment]
Just reminding that icons node are presented very small, so the less detail they have, the better.

**Comment by RibalGZ** [comment]
I think the stamp is not a good idea, it's the common icon of cloning tools.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
