### PR TITLE
Improve editor panning and remove RMB panning

### PR DESCRIPTION
**Pull request by KoBeWi**
This PR does a couple of things:
- Improves cursor refreshing. Now `_update_cursor()` will automatically refresh the cursor shape if it's different from previous one (also fixes a regression from #37336 where cursor would change even if not over 2D viewport)
- Pan View shortcut (Space by default) will automatically change cursor to CURSOR_DRAG while being pressed
  - Updated the panning mode tooltip to mention this shortcut
- Removes RMB panning, as it got in a way of properly using RMB in the editor (see #51695 for example). We had 3 ways to pan view anyways

### CODE REVIEW

**Review by groud — APPROVED** [review]
I am in favor of this PR. I think having the right click available in the editor should allow several interesting thing, such as popping a context menu or do specific actions with some editors.

We need to pay attention to whether or not we have any complain about that though, I would not be surprised if it would annoy some users.

**Comment by sairam4123** [comment]
I am not favour of removing the RMB because it's difficult for me to pan around in the the 2D editor without it.

**Comment by KoBeWi** [comment]
@sairam4123 And what about Space panning? You can change it to any other key if preferred, there's also a setting called "Simple Panning" that allows to use this shortcut without LMB (like in GIMP for example).

**Comment by sairam4123** [comment]
That's pretty good then. LMB panning would really help.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
