### PR TITLE
Fix related editor panel not opening after creating resource

### LINKED ISSUE #32895: Adding New SpriteFrames to AnimatedSprite doesn't automatically open the SpriteFrames panel
**Godot version:**
3.2.alpha.custom_build.119bf2372

**OS/device including version:**
5.3.6.arch1-1

**Issue description:**
The [docs](https://docs.godotengine.org/en/latest/getting_started/step_by_step/your_first_game.html#sprite-animation) say that adding a "New SpriteFrames" to the Frames property of AnimatedSprite should automatically open the SpriteFrames panel but this doesn't happen. You need to click on the Frames "SpriteFrames" property for the panel to open.

Selecting another node in the Scene and then returning to the AnimatedSprite node automatically opens the SpriteFrames panel so I'm assuming the panel is still intended to open and that it not opening automatically isn't an intentional change in 3.2

update: removing the SpriteFrames property and re-adding it opens the SpriteFrames panel as described in the docs https://streamable.com/oc5jm

**Steps to reproduce:**
1. In the Scene panel select the AnimatedSprite node
2. In the Inspect panel find the Frames property and click "[empty]" -> "New SpriteFrames"

**Minimal reproduction project:**
[YourFirstGame.zip](https://github.com/godotengine/godot/files/3740451/YourFirstGame.zip)

### PR DESCRIPTION
**Pull request by thiagoamendola**
When creating a new resource inside an editor node, its related editor panel
should open automatically but it was opening only after selecting the resource.
Just like in **_resource_selected** method from `editor_properties` class,
adding a section unfold call in **_menu_option** method fixes this issue.

Fix #32895

### CODE REVIEW

**Comment by aaronfranke** [comment]
@thiagoamendola Is this still desired? If so, it needs to be rebased on the latest master branch. While there are no conflicts, rebasing is important so that reviewers can easily test the PR.

**Comment by thiagoamendola** [comment]
Thanks for the ping. Just rebased the branch.

**Comment by aaronfranke** [comment]
@thiagoamendola If you rebased, you did not push that rebase. https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html

**Review by KoBeWi — CHANGES_REQUESTED** [review]
When you create sprite frames again, the section gets folded. I think you should just call the unfold with `true`. (question is whether it's a desired behavior for everything)

**Comment by akien-mga** [comment]
This is not needed, the current behavior is intended and the docs were inaccurate.

**Pull request closed without merging**
