### PR TITLE
Project manager improvements

### LINKED ISSUE #26233: The ProjectManager takes a long time to open due to loading project icons
Godot 3.0.6
Godot 3.1 beta6

Over time I accumulated a lot of projects and test projects, so the list in my project manager has become very big. It also became very slow to open, and given some errors appearing in the console while it loads, I suspect this is due to parsing all project files and icons.
Would it be possible to run this filesystem walk asynchronously?

### PR DESCRIPTION
**Pull request by Zylann**
The project manager was reloading all files and formatting their icons every time it started or any change was made to the list. So when you have 100 projects, it takes a long time and causes lag, especially when the OS didn't cache those files yet.

This PR loads files once on startup, and further operations are done on information which is already loaded instead. This makes sorting, fav'ing, filtering much faster.

Also, icons are now loaded iteratively in a coroutine, which allows a faster start time.

In order to accomplish this, I refactored the project list to have its own class. Structuring it more explicitely made my work easier and I believe it's easier to understand what the code aims to do now, which may help for future changes.

I also changed this icon:
image

Closes https://github.com/godotengine/godot/issues/26233

Note 1:
the way we save registered projects and their favorite status complicates things a bit.
They are mixed with other editor settings and it looks like this:
```
...
projects/D:::PROJETS::INFO::GODOT::Plugins::HTerrain::hterrain = "D:/PROJETS/INFO/GODOT/Plugins/HTerrain/hterrain"
favorite_projects/D:::PROJETS::INFO::GODOT::Plugins::HTerrain::hterrain = "D:/PROJETS/INFO/GODOT/Plugins/HTerrain/hterrain"
projects/D:::PROJETS::INFO::GODOT::TESTS::Godot31::DrawCalls = "D:/PROJETS/INFO/GODOT/TESTS/Godot31/DrawCalls"
...
```
I would like to change it to be a simple dictionary like this:
```
projects: {
    "D:/PROJETS/INFO/GODOT/Plugins/HTerrain/hterrain": { "favorite": true },
    "D:/PROJETS/INFO/GODOT/TESTS/Godot31/DrawCalls": { }
}
```
And eventually move those to their own file. However it would break compatibility, unless some migration code is added. It's not hard to do, but I preferred to not do it in this PR as it's just improvements, not features.

Note 2:
The .cpp diff is hard to read, so I'd suggest to just focus on lines from 925 to 2576, which is where I did the changes. Some of the code remained the same, just moved elsewhere.

### CODE REVIEW

**Comment by Calinou** [comment]
> I would like to change it to be a simple dictionary like this:

The favorite projects dictionary could be saved to a separate file using ConfigFile. It'd probably look a bit different, but the idea is the same :wink:

**Comment by Zylann** [comment]
@Calinou I actually meant putting `favorite` in the same dictionary as one attribute of a project, because it maps better to how the list works currently. Also no need to repeat the same path somewhere else ;)

**Comment by Calinou** [comment]
@Zylann Good point. This could also be reused for future features like tags :slightly_smiling_face:

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
