### PR TITLE
Add ability to set "keep screen on" for android & iOS. fixes #2428

### LINKED ISSUE #2428: Some api to be able to go to sleep for mobile device.
Godot forces always on for mobile device.
But some api to be able to go to sleep for mobile device would be great.

### PR DESCRIPTION
**Pull request by volzhs**
Can change "Set Keep Screen On" at Project settings.

2 methods are added to `OS`.

```
OS::set_keep_screen_on(bool)
bool OS::is_keep_screen_on()
```

### CODE REVIEW

**Comment by volzhs** [comment]
I hope this PR will be merged soon. :)

**Comment by reduz** [comment]
let me understand this.. by default as far as I remember screen is forced on all the time
so this PR makes it optional?

**Comment by volzhs** [comment]
@reduz yes.

**Comment by akien-mga** [comment]
This seems to start being a popular request: https://www.facebook.com/groups/godotengine/permalink/704400419696555/ :)

**Comment by akien-mga** [comment]
This should be fine to merge I guess, maybe @punto- can have a look?

**Comment by volzhs** [comment]
shit. I knew this would happen. I will create another PR for this. :(

**Comment by volzhs** [comment]
I am embarrassed this time. I don't know what should I do...

**Comment by punto-** [comment]
what happened?

**Comment by volzhs** [comment]
so many commits and changes after I created this PR.
I'm trying to find to create new one but it's really confusing for me. :(

**Comment by volzhs** [comment]
I can't figure out how to do it.
@punto- can you do it with this ``diff`` file?

https://drive.google.com/file/d/0ByuhCIzeus36bTFiaUNmZXd5Y00/view?usp=sharing

**Comment by volzhs** [comment]
I have this one.
how can I clear commits?
https://github.com/godotengine/godot/compare/master...volzhs:set-keep-screen-on

**Comment by volzhs** [comment]
@punto- I successfully made another PR for this. #3359

**Pull request closed without merging**
