### PR TITLE
Add missing NULL checks on CanvasItemEditor

### LINKED ISSUE #11444: Editor crashes under some conditions
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
cd2ffdc6725aa6f7a9a4af6fd5abcc4cafae61b4

**Issue description:**

the editor crashes under certains conditions, it has happened to me when creating a new scene, or moving to 2D tab when im in a Script.

heres the backtrace

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x36720) [0x7f0d278d6720] (??:0)
[2] Vector<Node*>::_get_size() const (/home/------/Projects/godot/core/vector.h:60)
[3] Vector<Node*>::size() const (/home/------/Projects/godot/core/vector.h:112)
[4] Node::get_child_count() const (/home/------/Projects/godot/scene/main/node.cpp:1427)
[5] CanvasItemEditor::_draw_locks_and_groups(Node*, Transform2D const&) (/home/------/Projects/godot/editor/plugins/canvas_item_editor_plugin.cpp:2591)
[6] CanvasItemEditor::_draw_viewport() (/home/------/Projects/godot/editor/plugins/canvas_item_editor_plugin.cpp:2692)
[7] MethodBind0<CanvasItemEditor>::call(Object*, Variant const**, int, Variant::CallError&) (/home/------/Projects/godot/core/method_bind.gen.inc:139)
[8] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/------/Projects/godot/core/object.cpp:839)
[9] Object::emit_signal(StringName const&, Variant const**, int) (/home/------/Projects/godot/core/object.cpp:1120)
[10] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/home/------/Projects/godot/core/object.cpp:1165)
[11] CanvasItem::_update_callback() (/home/------/Projects/godot/scene/2d/canvas_item.cpp:339 (discriminator 4))
[12] MethodBind0<CanvasItem>::call(Object*, Variant const**, int, Variant::CallError&) (/home/------/Projects/godot/core/method_bind.gen.inc:139)
[13] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/------/Projects/godot/core/object.cpp:839)
[14] MessageQueue::_call_function(Object*, StringName const&, Variant const*, int, bool) (/home/------/Projects/godot/core/message_queue.cpp:?)
[15] MessageQueue::flush() (/home/------/Projects/godot/core/message_queue.cpp:306)
[16] SceneTree::iteration(float) (/home/------/Projects/godot/scene/main/scene_tree.cpp:457)
[17] Main::iteration() (/home/------/Projects/godot/main/main.cpp:1606)
[18] OS_X11::run() (/home/------/Projects/godot/platform/x11/os_x11.cpp:2105)
[19] /home/------/Projects/godot/bin/godot.x11.tools.64.llvm(main+0x13f) [0xefd50f] (/home/------/Projects/godot/platform/x11/godot_x11.cpp:54)
[20] /lib64/libc.so.6(__libc_start_main+0xea) [0x7f0d278c050a] (??:0)
[21] /home/------/Projects/godot/bin/godot.x11.tools.64.llvm(_start+0x2a) [0xefd31a] (??:?)
-- END OF BACKTRACE --
```

**Steps to reproduce:**

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by marcelofg55**
Might fix #11444.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @groud

**Comment by groud** [comment]
I haven't touched those function but the changes make sense. LGTM.

**Comment by akien-mga** [comment]
Ah sorry I thought they might be related to your changes :)

**Comment by groud** [comment]
> Ah sorry I thought they might be related to your changes :)

Actually I think you are right, I think I splitted them. Maybe I forgot to re-add the NULL check ?
Anyway that's not important ^^

**Pull request merged**
