### PR TITLE
Fix to prevent disappearing icons in the Material Preview.

### LINKED ISSUE #57088: Material preview sphere icon has wrong inactive modulation
### Godot version

4.0 (#eb5aa32)

### System information

Windows 10

### Issue description

The icon used to switch to a sphere model for material preview goes completely invisible (or black) when it gets into the inactive state. Cube's icon handles that state correctly and only gets slightly dimmer.

https://user-images.githubusercontent.com/11782833/150687914-de0826b3-2854-4858-8828-505e28829cb9.mp4

### Steps to reproduce

Add a 3d node and create a material for it. Open the material resource and play around with the material preview.

### Minimal reproduction project

N/a

### PR DESCRIPTION
**Pull request by Josephblt**
The Sphere and Lighting 1 icons disappeared when toggled off due to problems in the .svg files. The icons are now similar to other working ones and are shown with a slightly darker hue when toggled off.

**Toggle On**
Material Preview (Toggle On)

**Toggle Off**
Material Preview (Toggle Off)

_bugsquad edit: fixes #57088_

### CODE REVIEW

**Comment by fire** [comment]
Test Plan:

1. find time for steps
1. download the windows executable from the checks
2. Verify that the mesh preview works as expected
3. Compare against master version for A-B testing.
4. Write test log.

I was able to write a test plan, but I'm not able to fully test.

**Review by akien-mga — APPROVED** [review]
Looks good to me, I'll let icon experts confirm/validate.

**Review by YuriSizov — APPROVED** [review]
It fixes the issue, but we may want to revisit those icons entirely, because good luck figuring out right now which I have on and which I have off:

image

We also use the same light icons for mesh preview, but we use a mid-gray background there which is even worse:

image

**Comment by Josephblt** [comment]
If you guys have any suggestions on how I can improve this or any other issues you'd like taken care of, I'd be happy to help. Thanks.

**Comment by pycbouh** [comment]
It's okay, can be done in another PR.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by Josephblt** [comment]
Thanks, @akien-mga. Again, if you guys can point out another issue that needs attention, I'd be glad to help.

**Pull request merged**
