### PR TITLE
-

### PR DESCRIPTION
**Pull request by ghost**
-

### CODE REVIEW

**Comment by puthre** [comment]
> 2. There aren't checks for division by zero in operators (/, /=). Why?

I think it's for performance reasons. Let the user decide if he really needs to check for those.

**Comment by Klesomik** [comment]
But there is a check for division by zero in method normalize in vector2.h [48; 57].
And also we can't compare real_t numbers by operators (==, !=)
```cpp
real_t l = x * x + y * y;
if (l != 0) {
```
So I think it is not for performance reasons.

**Comment by puthre** [comment]
> But there is a check for division by zero in method normalize in `vector2.h` [48; 57].
On a value computed by itself
> And also we can't compare real_t numbers by operators (==, !=).
You can with 0, it's a special case.

**Comment by Klesomik** [comment]
> 
> You can with 0, it's a special case.

Do you have any proves?
I think 0 is not special case. [Prove](https://stackoverflow.com/questions/485175/is-it-safe-to-check-floating-point-values-for-equality-to-0)

> > But there is a check for division by zero in method normalize in vector2.h [48; 57].

> On a value computed by itself

So let user decide if he really want to check this.

**Comment by puthre** [comment]
> > You can with 0, it's a special case.
> 
> Do you have any proves?
IEEE 754 standard specifies that -0 = +0 and  that 1/+0 = +Inf and 1/-0 = -Inf and that -0 = + 0
You only have to check for the EXACT 0 because that's when you get the exception.

**Comment by Klesomik** [comment]
I don't understand why travis-ci is not successful.
How to fix it?

**Comment by puthre** [comment]
> I don't understand why travis-ci is not successful.
> How to fix it?

You have a space at the end of that line.

**Comment by Klesomik** [comment]
> > I don't understand why travis-ci is not successful.
> > How to fix it?
> 
> You have a space at the end of that line.

Thank you! What I need to do for merge my branch with godot/master?
Can somebody make a review for my code?

**Comment by puthre** [comment]
> > > I don't understand why travis-ci is not successful.
> > > How to fix it?
> > 
> > 
> > You have a space at the end of that line.
> 
> Thank you! What I need to do for a merge my branch with godot/master?
> Can somebody make a review of my code?

They will if they consider they need your improvements.

**Comment by Klesomik** [comment]
@puthre can you tell me something about creating good pull requests?
I'm beginner and I don't know much about it.
I heard for each pull request you should create special branch with your improvements.
Do I need to merge my branch with my master or it is not necessary for merging a pull request?

**Comment by puthre** [comment]
> @puthre can you tell me something about creating good pull requests?
> I'm beginner and I don't know much about it.
> I heard for each pull request you should create special branch with your improvements.
> Do I need to merge my branch with my master or it is not necessary for merging a pull request?

No, just keep only your modifications for that pull request on that branch and nothing else.

**Comment by Chaosus** [comment]
@Klesomik You need to squash the commits together (as described in http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase). Also this branch needs to be rebased on the latest master branch.

**Comment by Klesomik** [comment]
@Chaosus So, what I need to do next?

**Comment by Chaosus** [comment]
This branch still has conflicts with a master - you need to rebase and resolve conflicts

**Comment by Klesomik** [comment]
@Chaosus Is it all?

**Comment by Chaosus** [comment]
Yeah, seems ok - now wait till other contributors review it.

**Comment by aaronfranke** [comment]
@Klesomik Is this still desired? If so, it needs to be rebased on the latest master branch.

What you did above is a merge, which is different. Please see this article to learn how to rebase: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by aaronfranke** [comment]
Closing as abandoned by the PR author. If this is still desired, it needs to be discussed with the Godot developers in a proposal first, including benchmarks and example use cases. Many of the things in this PR are straight up not desired, others are stylistic changes where it's not clear which is better, and some of these changes may affect performance.

**Pull request closed without merging**
