### PR TITLE
Incorrect format specifiers used to display some type data in the Visual Studio debugger

### PR DESCRIPTION
**Pull request by KiritoAM**

### CODE REVIEW

**Comment by akien-mga** [comment]
It doesn't necessarily need to be handled in this PR, but there are more issues with this `.natvis` file being outdated for the Godot 4.0 API (`Pool*Array` -> `Packed*Array`, etc.).

**Comment by andrew-softdev** [comment]
@akien-mga thanks for noticing that. I have fixed the issues relating to Variant, and am looking through to see if there are any other issues I can find. I can append to this pull request or create another one later. Unless someone tells me otherwise, I will add it to this pull request.

**Comment by pouleyKetchoupp** [comment]
@andrew-softdev It's fine to add more to this PR. You can just amend your previous commit with the extra changes as described in https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#modifying-a-pull-request

**Review by pouleyKetchoupp — APPROVED** [review]
Works fine! Tested on VS 2019 v16.8.3.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
