### PR TITLE
Add spine animation format support

### PR DESCRIPTION
**Pull request by sanikoyes**
Add spine animation format support for godot engine
A surprise present :D

### CODE REVIEW

**Comment by reduz** [comment]
I will be trying to add support for the spine format in 1.2 so it imports using Godot built-in animation features. If it proves to be too difficult, this can be merged instead

**Comment by sanikoyes** [comment]
The use of the official spine export format, for artist is more easy to use

**Comment by alabd14313** [comment]
Please use free softwares:
https://www.youtube.com/watch?v=uoQZV1f_J1s

**Comment by reduz** [comment]
I want to be able to import Spine animations

**Comment by blurymind** [comment]
Does this commit really support spine animation data? Godot lacks sprite deformation, which spine uses. Does this add that feature to godot's animation system?

**Comment by akien-mga** [comment]
> I will be trying to add support for the spine format in 1.2 so it imports using Godot built-in animation features. If it proves to be too difficult, this can be merged instead

@reduz What's the status on this?

**Comment by jjay** [comment]
There is importer for spine animations: https://github.com/jjay/godot-spine-importer. It import spine as 3d scene with viewport and viewportsprite. Mesh deformation supported for either weighted meshes attached to multiply bones or deform meshes attached to single bone.

**Comment by akien-mga** [comment]
IMO @jjay's plugin is a great way to implement this feature. @reduz Do you still want to consider including spine animation support in core, or are you happy with a third party plugin on the assetlib?

**Comment by blurymind** [comment]
I think godot should have this feature built into it's animation system.
The implementation here seems like a hack in a way imo and is useful only
to people who own a spine license (300$)

**Comment by reduz** [comment]
I will soon be implementing 2D meshes in Godot, including skeletons. That
should allow importing from any animation software

**Comment by akien-mga** [comment]
As per the above, Spine importing will be done for 3.0 but with a different implementation, so closing this one. Thanks for the (long lived!) proposal though!

**Pull request closed without merging**
