### PR TITLE
Backport gltf2 module from master.

### PR DESCRIPTION
**Pull request by fire**
This is the 3.2 back-port of the glTF 2.0 module.

@Calinou @aaronfranke

### CODE REVIEW

**Comment by aaronfranke** [comment]
Exporting works perfectly in my testing in this PR (and isn't available without this PR). This backport is really important for the sake of adding export support, as Godot's internal mesh format isn't compatible between 3.2 and 4.0, so if a project only has a Godot mesh saved without a `.glb` or `.blend` or similar, the only way to bring that mesh from 3.2 to 4.0 is with the GLTF export.

However, there is a weird regression with importing. When opening the TPS demo from a clean slate (after a git clean or just manually deleting `.import/`) with this PR it creates these mysterious files with no name and just an extension. I also tested with this PR rebased on the latest 3.2 and it's the same behavior, but the problem doesn't exist on the current 3.2 branch.

Screenshot from 2021-03-08 23-37-53

**Comment by fire** [comment]
Can you make a reduced sample?

**Comment by fire** [comment]
@aaronfranke I can't reproduce your bug report.

**Comment by aaronfranke** [comment]
Here is a minimal reproduction project: [PR46783.zip](https://github.com/godotengine/godot/files/6113240/PR46783.zip) It happens with meshes set to be stored externally.

On 3.2.4 rc4 and current head of the 3.2 branch: Creates a `BlastMesh.mesh` file.

On this PR: Creates a `.mesh` file with no name before the extension.

**Comment by fire** [comment]
I noted in the Godot blog post that skeleton attachments aren't in, but if we're to get 3.2 assets to 4, we need that feature.

**Comment by aaronfranke** [comment]
Better, but still not good. The files now have names, but they're not the names as within the `.glb` files, they're just simple names. This might conflict for files with multiple meshes (they might overwrite each other). Here is what it looks like with this PR:

Screenshot from 2021-03-10 18-53-32

Here is what the minimal reproduction project looks like on 3.2.4 rc4:

Screenshot from 2021-03-10 18-54-18

This is what diffs I get with a fresh import of the TPS demo with this PR:

Screenshot from 2021-03-10 19-14-16

**Review by aaronfranke — APPROVED** [review]
This is what the behavior is in the current version of this PR:

Screenshot from 2021-03-19 20-12-42

The behavior is not the same as in current 3.x, but it's vastly better than when this PR was opened. One could argue that this is even better, or one could argue that it's worse. Anyway, the ability to export GLTF scenes from 3.x is a vast improvement, and since this PR doesn't have any obvious downsides and works fine for me, I'll give this an approval.

**Comment by fire** [comment]
Working out how to get this updated to latest Godot Engine Master.

Today's master is https://github.com/godotengine/godot/commit/c340ed63943aa7c02064e536ff302de300a02ec2.

**Comment by fire** [comment]
We finished the backport but we're sleeping on it before making a submission.

**Comment by fire** [comment]
Super-seceded by https://github.com/godotengine/godot/pull/49120.

**Pull request closed without merging**
