### PR TITLE
Bring selected script in view of open scripts list

### LINKED ISSUE #29721: Bring selected script file's name into view
**Godot version:**
3.1.1

**OS/device including version:**
mac OS 10.14.5

**Issue description:**
When .gd script files get selected automatically in the script editor for whatever reason (e.g. breakpoint/error during debugging, changing scene tabs, etc.), the displayed script file's name gets selected in the "Scripts Panel" (left pane of the script editor), but the selection isn't brought into view. So when a larger number of scripts are open than fits onscreen, which is a common occurrence on laptop screens, there's no visible indication of what script you're looking at in the script editor, without scrolling the file list to see what's highlighted every time.

**Steps to reproduce:**
Open a number scenes with scripts attached to them. Either open a large number of them or reduce Godot's window size so there's a larger number of open scripts than fits the screen.  Then change scene tabs, which will automatically display the scene's script but won't bring the selection in left pane into view if it's outside of the view.

**Solution:**
1. Please bring the selected script file's name into view (i.e. scroll the list as needed)
2. In addition to 1 above, consider adding the script file's name somewhere else. For example, the selected scene's name is displayed in two locations right now: the tabs above the script editor, and Godot's window title. Consider doing the same for script file names, i.e. append the open script's name to the window title: e.g. "Godot Engine - MyProject - MyScene.tscn - MyScript.gd"

### PR DESCRIPTION
**Pull request by codecustard**
Resolves #29721

### CODE REVIEW

**Comment by volzhs** [comment]
demo

I'm not sure it's a regression or not but script list ensure to show current script at every update with this PR

**Comment by Zireael07** [comment]
I think it's by design?

**Comment by akien-mga** [comment]
> I'm not sure it's a regression or not but script list ensure to show current script at every update with this PR

Looks like it could be annoying indeed. I think the current script should be focused on external events, but probably not re-focused each time you input any character in the script.

**Review by volzhs — APPROVED** [review]
looks ok for me

**Review by volzhs — APPROVED** [review]
looks ok for me

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
