### PR TITLE
Backport HTTPRequest gzip decompression

### PR DESCRIPTION
**Pull request by tavurth**
Sorry if creating incomplete PRs is not allowed! I can remove this if needed.

I was trying to handle the backport of [this PR](https://github.com/godotengine/godot/pull/38944).

Most of the work seems to be done, however I've run into a few issues, and I'm not familiar enough with the Godot source to understand what's happening here.

I'm currently running into the following errors:

```c++
[ 78%] scene/main/http_request.cpp:352:70: error: no viable conversion from 'Vector<uint8_t>' (aka 'Vector<unsigned char>') to 'const PoolVector<uint8_t>' (aka 'const PoolVector<unsigned char>')
                                Error err = client->request_raw(method, request_string, headers, request_data);
                                                                                                 ^~~~~~~~~~~~
./core/pool_vector.h:466:2: note: candidate constructor not viable: no known conversion from 'Vector<uint8_t>' (aka 'Vector<unsigned char>') to 'const PoolVector<unsigned char> &' for 1st argument
        PoolVector(const PoolVector &p_pool_vector) {
        ^
./core/io/http_client.h:205:118: note: passing argument to parameter 'p_body' here
        Error request_raw(Method p_method, const String &p_url, const Vector<String> &p_headers, const PoolVector<uint8_t> &p_body);
                                                                                                                            ^
[ 78%] scene/main/http_request.cpp:476:86: error: no member named 'ptr' in 'PoolVector<unsigned char>'
                int result = Compression::decompress_dynamic(decompressed, body_size_limit, p_data.ptr(), p_data.size(), mode);
                                                                                            ~~~~~~ ^
[ 79%] 2 errors generated.
[ 80%] scons: *** [scene/main/http_request.osx.tools.x86_64.o] Error 1
core/io/compression.cpp:222:7: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
        p_dst->resize(0);
        ~~~~~^ ~~~~~~
core/io/compression.cpp:228:8: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
                p_dst->resize(p_dst->size() + gzip_chunk);
                ~~~~~^ ~~~~~~
core/io/compression.cpp:228:22: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
                p_dst->resize(p_dst->size() + gzip_chunk);
                              ~~~~~^ ~~~~
core/io/compression.cpp:230:14: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
                dst = p_dst->ptrw();
                      ~~~~~^ ~~~~
core/io/compression.cpp:251:11: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
                                        p_dst->resize(0);
                                        ~~~~~^ ~~~~~~
core/io/compression.cpp:261:9: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
                        p_dst->resize(0);
                        ~~~~~^ ~~~~~~
core/io/compression.cpp:267:49: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
        if (ret == Z_STREAM_END && (unsigned long)p_dst->size() > strm.total_out) {
                                                  ~~~~~^ ~~~~
core/io/compression.cpp:268:8: error: member reference base type 'uint8_t' (aka 'unsigned char') is not a structure or union
                p_dst->resize(strm.total_out);
                ~~~~~^ ~~~~~~
8 errors generated.
scons: *** [core/io/compression.osx.tools.x86_64.o] Error 1
scons: building terminated because of errors.
```

Does anyone have any idea how to bypass this issue?

```c++
[ 78%] scene/main/http_request.cpp:352:70: error: no viable conversion from 'Vector<uint8_t>' (aka 'Vector<unsigned char>') to 'const PoolVector<uint8_t>' (aka 'const PoolVector<unsigned char>')
                                Error err = client->request_raw(method, request_string, headers, request_data);
```

### CODE REVIEW

**Comment by Calinou** [comment]
> Sorry if creating incomplete PRs is not allowed! I can remove this if needed.

It's OK :slightly_smiling_face: I marked the PR as a draft to prevent accidental merging.

**Comment by tavurth** [comment]
It works! Thank you for the help :)

I've tested this on my local machine and the fetching is much faster 🎉

**Comment by tavurth** [comment]
Hmm, seems there's some problem building on certain versions.

```c++
core/io/compression.h:56:32: error: 'PoolVector' has not been declared
   56 |  static int decompress_dynamic(PoolVector<uint8_t> *p_dst, int p_max_dst_size, const uint8_t *p_src, int p_src_size, Mode p_mode);
```

I had this issue on OSX and fixed it by `#include "core/variant.h"` is there some more correct way to include the `PoolVector` type?

**Comment by tavurth** [comment]
Looks like only the Windows build is failing now 🤔 

```c++
core\io\compression.cpp(245): error C2220: the following warning is treated as an error
core\io\compression.cpp(245): warning C5051: attribute 'fallthrough' requires at least '/std:c++17'; ignored
core\io\compression.cpp(245): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
```

**Comment by tavurth** [comment]
Tests are finally passing 🎉 

Screenshot 2021-05-09 at 21 53 23

😅

**Comment by aaronfranke** [comment]
@tavurth That's what 3.x is for. You had it right before you changed it!

**Comment by tavurth** [comment]
Ok thank you @aaronfranke!

I've opened a new PR with the 3.x branch.

https://github.com/godotengine/godot/pull/48651

**Pull request closed without merging**
