### PR TITLE
Fix visual shader's `screen_uv` input preview uses position of node rather than a sample area like uv

### LINKED ISSUE #84311: VisualShader editor input screen_uv preview uses visual position of node in editor rather than a sample area
### Godot version

v4.1.2.stable.mono.official [399c9dc39], v4.2.beta4.mono.official [93cdacbb0]

### System information

Godot v4.2.beta4.mono - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3713) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

Use the output section as positional reference:
image
image

Rather than using a sample range (0 to 1 in both x and y directions) such as for uv, screen_uv uses the visual position of the node in the editor. This has no effect on the shader in-game, but makes it more difficult to make a shader as this forces you to swap between uv while building a shader and screen_uv while testing it ingame.

### Steps to reproduce

1. Create new VisualShader.
2. Add a new input, set the type to be screen_uv, enable preview.
3. Drag the node around and observe that it changes colour.
Drag it to the top left and it starts going dark, drag it to the right to make it red, drag it to the bottom right to make it yellow and finally drag it to the bottom left to make it green.

### Minimal reproduction project

Reproduction is trivial, visual of bug has been provided.

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes #84311

### CODE REVIEW

**Review by Chaosus — APPROVED** [review]

**Comment by Chaosus** [comment]
@jsjtxietian I think this is incorrect place for doing this code, the correct place is https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/scene/resources/visual_shader.cpp#L3141

**Comment by jsjtxietian** [comment]
Ah, yes, that's a more elegant approach, thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
