### PR TITLE
Fix Viewport mouse enter+exit notifications

### LINKED ISSUE #57762: Notification problem at SubViewportContainer border
### Godot version

v4.0.alpha.custom_build [be1adf491]

### System information

Debian 11, Vulkan

### Issue description

I have the following setup:
- SubViewportContainer (Clip Content)
- - Sub Viewport
- - - Label

The following pictures show where `mouse_enter` and `mouse_exit` notifications happen and where I would expect them to happen. For comparison there is a label within a label on the right side.

BugViewportBorder1
BugViewportBorder2

### Steps to reproduce

1. Load and run MRP
2. Watch console while moving the mouse

### Minimal reproduction project

[BugViewportBorder.zip](https://github.com/godotengine/godot/files/8016647/BugViewportBorder.zip)

### PR DESCRIPTION
**Pull request by Sauermann**
resolve #57762

Viewports of a Window receive the notifications `NOTIFICATION_WM_MOUSE_ENTER`, `NOTIFICATION_WM_MOUSE_EXIT`, and `NOTIFICATION_WM_WINDOW_FOCUS_OUT` directly from their window:
https://github.com/godotengine/godot/blob/aa069a4d31c3eda2a5e194d825e2da795f2cca60/scene/main/window.cpp#L326-L327
Since SubViewports, that are child-nodes of a SubViewportContainer, do not have a Window, they do not receive these events, which leads to the mentioned bug.
This pull request solves this problem by propagating the notifications of SubViewportContainer to their SubViewports.

### CODE REVIEW

**Comment by reduz** [comment]
Looks quite good. @KoBeWi what do you think of it?

**Comment by KoBeWi** [comment]
This fixes the entered signals, but exit signals seem to be the same. Is this expected?

**Comment by Sauermann** [comment]
@KoBeWi yes, this is expected. This is a different bug and it is tracked in #28833.
Regarding exit events, this pull request fixes, that they no longer get dropped.

**Comment by KoBeWi** [comment]
And what about `NOTIFICATION_WM_WINDOW_FOCUS_IN`? If out is received, so should in, no?

**Comment by Sauermann** [comment]
`Viewport::_notification` does not act on `NOTIFICATION_WM_WINDOW_FOCUS_IN` so I thought, there is no need to forward it.

**Comment by KoBeWi** [comment]
It doesn't act, but the notification is still received and can be used in scripts etc. So it should be forwarded too.

**Comment by KoBeWi** [comment]
> Are there any additional notifications, that should be forwarded? For windows, I found the following notifications:
NOTIFICATION_WM_CLOSE_REQUEST
NOTIFICATION_WM_GO_BACK_REQUEST
NOTIFICATION_WM_DPI_CHANGE

I don't think these need to be forwarded.

But now that I look at this PR, it sends window-related notifications based on different notifications. I wonder if this should be documented, as users might find it unexpected.

**Comment by Sauermann** [comment]
> it sends window-related notifications based on different notifications

I find it confusing, that `NOTIFICATION_WM_MOUSE_ENTER` is considered a window-related notification. It doesn't trigger, when the mouse enters the window (which can have a title-bar), but when the mouse enters the viewport of the window. To me it would make more sense, if this notification was considered a viewport-related notification.

I see a problem with the current patch. I believe, that `NOTIFICATION_FOCUS_EXIT` should not be forwarded as `NOTIFICATION_WM_WINDOW_FOCUS_OUT`.

`NOTIFICATION_WM_WINDOW_FOCUS_OUT` means that the window has no longer focus.
`NOTIFICATION_FOCUS_EXIT` means that a Control has no longer key_focus.
These are two different things and seem to be incompatible.

**Comment by Sauermann** [comment]
My updated pull request separates notifications for two concepts:
- mouse being over the window (global state)
- mouse being over a viewport (viewport-local state)

Otherwise the global state would interfere with subviewports.

**Comment by reduz** [comment]
Some notes of concern here that I was thinking, the WM focus in and out notifications are propagated through the whole tree to all nodes. I have my doubts whether this is really useful, maybe they should be signals of SceneTree. The problem though is that here the sub-viewport will receive them now.

The problem here is that the WM notifications will be received twice by the sub-viewport.

**Comment by Sauermann** [comment]
When I noticed, that WM-mouse-enter+exit is distributed to all Nodes, I became aware, that my initial solution would not work. In the most recent patch, I created new notifications, that trigger when the mouse enters a viewport.
For the root-viewport, this notification comes from the Window.
For other sub-viewports, this notification comes from their parent SubViewportContainer.

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This makes sense, I am still unhappy to have it in Node, but Viewport has no notifications so not much we can do for the time being.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
