### PR TITLE
Hooked up RigidBody2D torque methods

### PR DESCRIPTION
**Pull request by JoshuaGrams**
Hooked up `set_applied_torque` and `get_applied_torque`, which existed in the physics server but weren't wrapped with `RigidBody2D` methods nor bound in GDScript.

Added a `get_inertia` method which returns the value, since they're probably much bigger than most people would expect. I didn't add a setter since the inertia appears to be automatically computed from the mass and the shapes. The inverse inertia is cached, so you _might_ be able to set it and it would stay until you changed a shape or the mass, but that's...probably not very useful, so I didn't add a setter function.

I also documented the read-only nature of `get_inertia` and added the obvious (probably redundant) minimal description of the other two methods.

### CODE REVIEW

**Comment by akien-mga** [comment]
Would fix #1058 I believe.

**Comment by JoshuaGrams** [comment]
Nice. So someone wrote one of these patches 16 months ago and posted it, but never made a pull request so it never made it in to the repository. Way to go, guys.

And...this only addresses half of #1058: there's still no function to apply force at a point. `apply_impulse` takes a point, but `set_applied_force` doesn't. So...I guess I should write `set_applied_force_at` or something? Naming suggestions welcome. Actually, that's easy to write. The only question is whether it should override the torque setting or add to it. No, it should definitely add to it.

OK, I'll see about adding another commit so that this fully closes #1058.

**Comment by JoshuaGrams** [comment]
Hrm...maybe I won't. At first glance, `apply_impulse` seems to be broken: it uses a global force vector and a sort-of-but-not-really-local position vector? I'm not sure that's a can-of-worms I want to open...more thought required...maybe I should just create a `set_force_at` which works correctly, and leave `apply_impulse` broken...? Although really you might want both the position and force to be local? Probably sometimes you want it one way and sometimes you want it the other way:

- If you're simulating a rocket engine attached to a body at a point, you both position and force to be vectors in the local coordinate system.
- If you're simulating an external force, say a tractor beam, you almost certainly want a global force vector. And...the position should probably still be in local coordinates, i.e. a spot on the body where the tractor beam is grabbing.

Hmm...

**Comment by slapin** [comment]
I think both force and impulse can be made to be behave like in 3d, which is intuitive.
One can convert local-global as they wish in their code. Another variant is to have both local
and global versions.

**Comment by JoshuaGrams** [comment]
Yeah, that's the conclusion I had come to. Just have to find time to write and check it. Probably tomorrow.

**Comment by JoshuaGrams** [comment]
OK, I added `add_force(Vector2 offset, Vector2 force)` and `set_inertia(float inertia)` methods.

I believe this closes Issue #4439. Here's a modified example for that.

[RigidBodyInertia.zip](https://github.com/godotengine/godot/files/236535/RigidBodyInertia.zip)

I documented the new methods, so I think this is ready to be merged.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
