### PR TITLE
Array::sort/invert now return reference to Array

### PR DESCRIPTION
**Pull request by Toizi**
From issue [#5193](https://github.com/godotengine/godot/issues/5193)

The issue only stated Array::sort, but I figured for consistency invert should be included as well

### CODE REVIEW

**Comment by saltares** [comment]
Could you please also update the docs?

**Comment by Toizi** [comment]
I am not sure whether there is a way to specify that the return type is a reference in the XML but from looking at other examples it seems people tend to put that information into the description.
Let me know if there is a better way of doing that

**Comment by akien-mga** [comment]
Could you have a look at squashing the commits together as described in http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase ?

**Comment by Toizi** [comment]
Commits are squashed now

**Review by ghost — APPROVED** [review]

**Comment by reduz** [comment]
seems ok

**Comment by Erawpalassalg** [comment]
I have no idea why, but this seems to not work, as of 3.0 (Windows 7, x64) (Or I really missed the point of this PR)

```
var a = [50, 16, 8, 50].sort()
print(a)
```
Will print Null. Same with sort_custom() and invert().

Also, the docs are confusing. They explain that invert(), sort() and sort_custom() should "return reference to the array", but they also state that their return type is void.

**Comment by akien-mga** [comment]
I guess this PR might have lacked the necessary Variant changes for this to work.

**Comment by rpsrosario** [comment]
Wondering if there is any update on this? Noticed on v3.0.2.stable.official (Windows 10, x64) that `.invert()` still has return type `void` in the documentation although it states "and return reference to the array."

**Pull request merged**
