### PR TITLE
--gap

### PR DESCRIPTION
**Pull request by keshavgbpecdelhi**

### CODE REVIEW

**Comment by akien-mga** [comment]
Please don't modify third-party code, and this change is pointless.

**Comment by keshavgbpecdelhi** [comment]
There were unusual gaps or we can say double tap spacebar. So, I tried to remove that *gap* to make the content indentations to match with others.

**Comment by akien-mga** [comment]
But it's not indentation, it's spaces after a dot in a comment, following a common American English convention.

Since this is thirdparty code (i.e. written by non-Godot authors, this code comes from https://github.com/lsalzman/enet), we don't want to make unnecessary alterations that make it harder to keep in sync with the upstream project. And in this case, it doesn't provide any value to change their sentence spacing style.

**Comment by akien-mga** [comment]
For future contributions, please describe your changes in English both in the commit log (`--gap` doesn't mean anything) and in the PR.

In this case the change is not wanted, but for future, valid changes, we require clear commits that state their purpose.

**Comment by keshavgbpecdelhi** [comment]
OK! And  sorry for this --gap commit disturbance.

**Pull request closed without merging**
