### PR TITLE
mbedtls: Update to version 2.28.5

### PR DESCRIPTION
**Pull request by Faless**
Reapplied the patch in `thirdparty/mbedtls/patches/windows-arm64-hardclock.diff`, removed the patch `thirdparty/mbedtls/patches/aesni-no-arm-intrinsics.patch` as it's no longer needed (see https://github.com/Mbed-TLS/mbedtls/issues/8168)

See https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-2.28.5 for release notes (the security advisory does not affect Godot anyway since the proper flags were already in place, see [here](https://mbed-tls.readthedocs.io/en/latest/security-advisories/mbedtls-security-advisory-2023-10-1/) for details).

### CODE REVIEW

**Comment by akien-mga** [comment]
Our patch `aesni-no-arm-intrinsics.patch` shouldn't be needed anymore (and thus can be reversed), they fixed the bug properly in `aesni.h` from what I can see. For context: https://github.com/Mbed-TLS/mbedtls/issues/8168

**Comment by Faless** [comment]
Thanks, reverted the patch, and removed it from tree.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.4.

**Pull request merged**
