### PR TITLE
Fix max FPS initialization

### PR DESCRIPTION
**Pull request by mrsaturnsan**
Max FPS needs to be initially set after the DisplayServer is created. Otherwise the Renderer will not get the max FPS value propagated to it.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
Looks good to me. I think this is a safe change because max_fps is only ever read in two places:
1. The main loop (which doesn't start until well after this)
2. The initialization of the Vulkan RDD

With this change we don't need to grab the `max_fps` from engine when initializing Vulkan because we can trust that it will be updated later.

Accordingly, we could remove the calculation of `max_fps` and `max_time` here:

https://github.com/godotengine/godot/blob/cb411fa960f0b7fdbd97dcdb4c90f9346360ee0e/drivers/vulkan/rendering_device_driver_vulkan.cpp#L3035-L3036

And just set the swap interval to `swap_chain->refresh_duration`

**Review by clayjohn — APPROVED** [review]
Looks great to me! The commits just need to be squashed

**Review by clayjohn — APPROVED** [review]
Looks good to me!

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉

**Pull request merged**
