### PR TITLE
Removed useless check

### PR DESCRIPTION
**Pull request by AndreaCatania**
Coverity issue
https://scan4.coverity.com/reports.htm#v36036/p14459/fileInstanceId=39888463&defectInstanceId=7346242&mergedDefectId=269745
https://scan4.coverity.com/reports.htm#v36036/p14459/fileInstanceId=39888463&defectInstanceId=7346104&mergedDefectId=269827

### CODE REVIEW

**Comment by nikibobi** [comment]
This isn't an useless check. If `colObj` is null then calling `colObj->get_instance_id();` would break cause you try to dereference null pointer.

**Comment by AndreaCatania** [comment]
It Can't be null

**Comment by aaronfranke** [comment]
If it can't ever be `null` then why doesn't it compile?

**Comment by EIREXE** [comment]
@aaronfranke I think the compilation failure is unrelated:

{standard input}: Fatal error: can't write scene/3d/arvr_nodes.x11.tools.64.o: No space left on device

**Comment by volzhs** [comment]
@aaronfranke did you compile with this PR yourself or said it with just looking at the travis result?

as what @EIREXE said, for the travis
https://travis-ci.org/godotengine/godot/jobs/365526314#L1800-L1801

**Pull request merged**
