### PR TITLE
Fix segfault on editor close up

### PR DESCRIPTION
**Pull request by Chaosus**
Fix segfault in #23215

### CODE REVIEW

**Comment by groud** [comment]
I think using NOTIFICATION_THEME_CHANGED made sense, but it probably needs a check before running _update_display_mode().
Could you try something like that ? :
```
if (is_in_tree()) {
 _update_display_mode(true).
} 
```

**Comment by Chaosus** [comment]
True, its works ! How I didnt guess it myself...

**Comment by groud** [comment]
Awesome, thanks ! :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
