### PR TITLE
Add support for left and right shift and alt

### PR DESCRIPTION
**Pull request by skyace65**
Adds the ability to map left or right shift key instead of just shift. Most of what I changed I got from PR #7972 and from some help from Discord. I don't usually work with C++ so I apologize if there are any obvious mistakes.

This at least partially resolves issue #3347

### CODE REVIEW

**Comment by nathansmith339** [comment]
It may be helpful to add support for the other left/right keys like Ctrl and Alt

**Comment by reduz** [comment]
This is not bad, but should be for Godot 4.0, as it breaks compatibility. The same should be applied for alt, ctrl and meta. Masking may work with this, needs to be checked.

**Comment by Anutrix** [comment]
Wouldn't https://github.com/godotengine/godot/issues/3347#issuecomment-171949635 preserve compatibility?

**Review by Anutrix — COMMENTED** [review]
Wouldn't https://github.com/godotengine/godot/issues/3347#issuecomment-171949635 preserve compatibility?

**Comment by aaronfranke** [comment]
@skyace65 Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by skyace65** [comment]
@aaronfranke this is still desired and I just rebased it.

**Comment by skyace65** [comment]
I just built this branch and I don't think I have the skill to get this fully working so I'm closing this PR.

**Pull request closed without merging**
