### PR TITLE
Add .csv ImportOption to not parse for translation by default.

### LINKED ISSUE #19627: Godot should be able to import a CSV without forcing it to be used for translation
**Godot version:**

3.0.3

**OS/device including version:**

N/A (all)

**Issue description:**

Importing a CSV appears to only be possible if it's used for translation, I think most people coming to Godot from other engines would assume they could import a CSV as just a container for simple data by default (especially as there [appears to be functions for working with CSV files](http://docs.godotengine.org/en/latest/classes/class_file.html#class-file-get-csv-line)! importing as another extension just seems like a hack, not a solution) - with an option in the import menu to mark it to be used for translations if that's the actual purpose

import menu

**Steps to reproduce:**
Add csv to project
Click it, go to import menu
Expected an option to import it as a normal CSV, but can only be used for translation 

**Minimal reproduction project:**

N/A (blank project with an added csv file)

### PR DESCRIPTION
**Pull request by willnationsdev**
Closes #19627.

### CODE REVIEW

**Comment by willnationsdev** [comment]
This solution is more of a hack for now. I'll get to work on a more legitimate solution (as decribed in the related Issue). If I finish it before this is merged, then we can just close this. Otherwise, I'll just rebase the future updated solution and have it undo the work of this PR.

**Comment by akien-mga** [comment]
That's not the right solution, it doesn't make sense to have an opt-in option in the translation importer to basically defeat the purpose of the import... And this will break games that actually use CSV for translations.

The simplest clean option for now would be to add a "No Import" importer, which doesn't import the file. It would be an option in the drop-down list which currently includes only "CSV Translation".

A medium term solution would then be to have the editor ask you how you want to handle CSV files ("CSV Translation" or "No Import") each time you add a new CSV file, with an option to define the default import mode for the project.

**Comment by willnationsdev** [comment]
The first correct solution you suggested is the "more legit" solution I came up with in the related Issue. I can update this PR then to use that solution if the existing one would break things anyway.

**Comment by akien-mga** [comment]
> The first correct solution you suggested is the "more legit" solution I came up with in the related Issue. I can update this PR then to use that solution if the existing one would break things anyway.

That would be good, yes.

**Comment by akien-mga** [comment]
Closing for now as discussed above.

**Pull request closed without merging**
