### PR TITLE
Fix intersect_point ignoring collision_layer

### LINKED ISSUE #40705: intersect_point ignores collision_layer argument
**Godot version:**

3.2.3 RC 1 win64

**OS/device including version**
Windows 10

**Issue description:**

Physics2DDirectSpaceState.intersect_point ignores the collision_layer argument and returns any intersecting area or body regardless of the layer it is on. Works fine in version 3.2.2 Stable win64

**Steps to reproduce:**
Use the reproduction project to check for collisions with the mouse pointer, notice how intersect_ray works correctly compared to intersect_point

**Minimal reproduction project:**

[IntersectPointCollisionLayerIgnored.zip](https://github.com/godotengine/godot/files/4976271/IntersectPointCollisionLayerIgnored.zip)

### PR DESCRIPTION
**Pull request by bpopp93**
Fixes #40705.

### CODE REVIEW

**Comment by akien-mga** [comment]
Regression from #40193.

**Review by KoBeWi — COMMENTED** [review]
I checked and it doesn't seem to re-introduce #11159, but I have no idea why 🙃

**Comment by bpopp93** [comment]
It seems to me that the newly added last parameter of _can_collide_with is being misused with 2d and possibly 3d physics in the fix for #40193. The arguments being passed in to potentially disable collision layer checking don't make sense to me (though I admit I'm quite new to all this).

**Review by madmiraal — CHANGES_REQUESTED** [review]
This PR is made against the 3.2 branch, and it does reintroduce #11159, because it does effectively revert #40280 without removing the scaffolding required to make it work.

As I have suggested in the issue ([#40705](https://github.com/godotengine/godot/issues/40705#issuecomment-664554271)), I think a better solution is to fully revert #40193 and its 3.2 counterpart #40280 and find an alternative solution for #11159.

**Comment by KoBeWi** [comment]
> it does reintroduce #11159

Eh, I messed up testing again :I

**Comment by akien-mga** [comment]
Superseded by #40776.

**Pull request closed without merging**
