### PR TITLE
Fixed kinematic movement stuck, Changed how shape scale works.

### LINKED ISSUE #13210: move_and_collide dont work properly in 3D KinematicBody
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
debian 9, f2d07d5aeb9c591c5b361a3d346f049e003948d3

**Issue description:**
In 3D Plaformer Demo, KinematicBody stuck at on_wall state, when its between wall and floor. It only happens with BulletEngine.
You can see pr related to this : #13192 

**Steps to reproduce:**
1 - Open 3D Plaformer demo
2 - Change physics to bullet
3 - Go to position that shown by image(its first block in game)

bulletstuck

### PR DESCRIPTION
**Pull request by AndreaCatania**
Optimized test_body_motion.

Fixes #13210
Closes #13192

### CODE REVIEW

**Comment by akien-mga** [comment]
There's a merge conflict to solve now. Then, I guess it can be merged.

**Comment by akien-mga** [comment]
Bump.

**Comment by AndreaCatania** [comment]
I didn't it because I have to fix a thing inside this PR

**Comment by AndreaCatania** [comment]
@akien-mga I did the changes, Now it can be merged.

**Comment by reduz** [comment]
if you didn't already, please don't forget to restore test_motion to how it works in Godot physics

**Comment by AndreaCatania** [comment]
@reduz I didn't touch godot test_motion, I've just improved it in bullet side so it's fine

**Pull request merged**
