### PR TITLE
Add *.jpg to default icon file filters

### LINKED ISSUE #16446: [UX] Icon in project settings should display *.jpg by default
**Godot version: 3**

**Issue description:**
When you open the select icon dialog it only has `*.png` and `*.webp` filters. I tried choosing a `.jpg` file and it seems to work just fine. No error message, I can clearly see it in the project list and as an Icon on the window. Is there any reason why the `*.jpg` filter is not on by default? If it works I think it should be added to the standard options.
iconpicker

### PR DESCRIPTION
**Pull request by awaitlink**
Fixes #16446.
Adds `*.jpg` to default icon and mouse cursor file filters.

### CODE REVIEW

**Comment by volzhs** [comment]
is it acceptable for all platform? like ios and android?

**Comment by sudoio** [comment]
Do you mean `.jpg` support on iOS and Android?

**Comment by volzhs** [comment]
https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/

for ios, it seems to allow only png format for icon.

**Comment by vnen** [comment]
The thing is that the icon is loaded before the ResourceLoaders are ready, so only core types should be used there. And I think JPG is not a core type, so it might fail in all platforms.

**Comment by akien-mga** [comment]
Yeah, I'm not sure why webp is currently proposed as shown in #16446, I'd expect that only png should be supported for the icon as it's the only core driver (other formats are loaded as modules after core).

**Comment by sudoio** [comment]
Should we then remove `webp` from the file filter?
Also, what about the mouse cursor icon?

**Comment by sudoio** [comment]
@akien-mga Should I then remove `webp` from the file filter?
Also, what about the mouse cursor icon?

**Comment by sudoio** [comment]
I'm closing this because the file filters should be discussed more in e.g. #16446 before making any changes to them.

**Pull request closed without merging**
