### PR TITLE
Expose minizip API to allow creating zips using scripts

### LINKED ISSUE #3701: Zip packing/unpacking with GDScript
I'm looking for a way to zip files/folders and unzip .zip files in GDScript.

### PR DESCRIPTION
**Pull request by marcelofg55**
Partially fixes #3701, still no unzipping yet.

Can be used like this:
```
var z = Zip.new()
z.open("test.zip", Zip.APPEND_CREATE)

z.open_new_file_in_zip("test.txt")
z.write_in_file_in_zip("this is a test".to_utf8())
z.close_file_in_zip()

z.open_new_file_in_zip("test/test.txt")
z.write_in_file_in_zip("this is a test inside a dir".to_utf8())
z.close_file_in_zip()

z.close()
```

### CODE REVIEW

**Comment by akien-mga** [comment]
IMO this is an interesting addition, but I'd prefer to wait for unzipping support before merging this. Having a `Zip` API that can only create zips but not unzip them would have a fairly limited use case, as most people will typically want to unzip external content.

**Comment by flyingpimonster** [comment]
Unzip support would be really helpful for my current project. Would anyone mind if I finish this PR?

**Comment by akien-mga** [comment]
Go ahead, I don't think Marcelo would mind (they're not very active of the past few months so I don't expect an update on this PR anytime soon).

**Comment by aaronfranke** [comment]
Closing as superseded by #34444 as per the above comments.

**Pull request closed without merging**
