### PR TITLE
[WIP] Fixing trimesh precision

### PR DESCRIPTION
**Pull request by AndreaCatania**
Don't merge please

Related to #21341

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Just added WIP to the title for clarity, feel free to remove that once it's ready :)

**Comment by cosmicchipsocket** [comment]
Thanks for this! Will it work on the primitive shapes as well? It'd be nice to construct levels out of prefabs - the initial reason for me trying trimesh collisions was due to the popping when crossing seams between adjacent cube shapes, for example.

I should probably make an updated test project that includes this.

**Comment by AndreaCatania** [comment]
You should not have this problem with primitives

**Comment by AndreaCatania** [comment]
superseded by #21808

**Pull request closed without merging**
