### PR TITLE
Avoid color flash on window creation and resizing

### PR DESCRIPTION
**Pull request by RandomShaper**
On Windows (and maybe in some other windowing systems), when Godot creates a window, it's painted in white before the renderer has a chance to setup a swap chain or context. Windows being stretched also get the newly added region painted in that striking white for the brief time Godot can render something meaningful there.

This PR adds a little framework to let platform display managers to use a more suitable color in those early moments of the new pixels, plus it leverages it for Windows, where the flash of white is annoying.

All orbits around the concept of _early clear color override_:
- The very startup of the engine sets the color to the same of the splash screen.
- The editor and project manager use the theme background for that.
- In any other situation, as long as the rendering server has already been created, the default clear color is used.

I'm making this PR with the expectation that X11 and MacOS maintainers assess whether those platforms would benefit from this.

## BEFORE 🤮
https://user-images.githubusercontent.com/11797174/212178934-83538d63-974f-476a-b780-f9d09129b0d5.mp4

## AFTER 😍
https://user-images.githubusercontent.com/11797174/212178951-3f50fbee-2bce-473f-9722-5794b21be44f.mp4

### CODE REVIEW

**Comment by bruvzg** [comment]
On macOS, it's transition to the splash screen too fast to see background, but a few pixels of it can be visible if you resize the window really fast, so it will be useful.

**Review by bruvzg — APPROVED** [review]

**Review by clayjohn — APPROVED** [review]
Looks good to me too

**Comment by Kemeros** [comment]
Thank you SO MUCH! ❤️❤️❤️

**Comment by RandomShaper** [comment]
Good to know. And how does resizing look there?

**Pull request merged**
