### PR TITLE
[3.2] Restrict `GL_TEXTURE_EXTERNAL_OES` to Android platforms

### LINKED ISSUE #37990: GL_INVALID_ENUM error generated.  Regression from 3.2.1
**Godot version:**
50582446ad13a7ce034bdd8695409bf26c1abac3 3.2.2-beta

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
Was running the editor in verbose mode, and have been seeing the following error messages.  Not sure what it may be regarding, but reporting it, since it is noted as high severity.

godot windows tools 64_fTGSskE8NO

Haven't noticed this in the 3.2.1 stable build.

**Steps to reproduce:**

Set a project to verbose  output, and restart it, or use the project below.

**Minimal reproduction project:**
[GL Enum Errors.zip](https://github.com/godotengine/godot/files/4496776/GL.Enum.Errors.zip)

### PR DESCRIPTION
**Pull request by m4gr3d**
Fixes #37990.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by avencherus** [comment]
Confirmed that the errors have gone away on my end.

**Comment by akien-mga** [comment]
What does it imply for the user of `ExternalTexture` on non-Android? Will it silently behave like a normal `StreamTexture`, or will it lead to errors? Either way, this likely needs to be made explicit in `doc/classes/ExternalTexture.xml`.

**Comment by akien-mga** [comment]
I'll merge as is for now to fix the bug in the next beta, but a documentation update would still be good.

**Comment by akien-mga** [comment]
Thanks!

**Comment by m4gr3d** [comment]
> I'll merge as is for now to fix the bug in the next beta, but a documentation update would still be good.

@akien-mga I've updated the documentation in PR #38299

**Pull request merged**
