### PR TITLE
Fix to parsing some Collada files with extra vertex semantics  [3.x]

### PR DESCRIPTION
**Pull request by SaracenOne**
Backport of fixing for parsing for some Collada files from #48560

### CODE REVIEW

**Comment by akien-mga** [comment]
Remember to squash commits (or use `git commit --amend` instead of `git commit`) when doing style fixes.

**Comment by SaracenOne** [comment]
Will fix it now

**Comment by SaracenOne** [comment]
Should be sorted now

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
