### PR TITLE
Moves a video file from res:// directories to user:// directories in …

### PR DESCRIPTION
**Pull request by kurikaesu**
…order for the native iOS video player to be able to read them. Native video player won't work with packed files as far as I know.

### CODE REVIEW

**Comment by punto-** [comment]
wouldn't it be better to just add the video files on xcode?

**Comment by kurikaesu** [comment]
Whether it's better or not, it adds an option for the end user to either do it via xcode, or just have it packed into the data.pck file as well.

**Comment by punto-** [comment]
And maybe reporting the error better when you try to play a video that is
in the pck, you should be able to detect if the file is actually on the
filesystem or no.. I don't like copying potentially huge files to the user
documents space due to a developer error..

**Comment by kurikaesu** [comment]
What do you suggest the error should be, and should it just not allow it?

**Comment by punto-** [comment]
Something like "Native video player can't play a file from the pck, add it
to the filesystem directly", or something.. It shouldn't copy it, just
print that error on the console. Also if the file starts with res:// that
doesn't mean it's on the pck, it can also be directly on the filesystem,
either alongside the pck, or because the whole game is added using the
"godot_path" method (but usually you'll have a pck). Either way you can
access it from res://. The way to detect it's on the pack is probably:

if ( !PackedData::get_singleton()->is_disabled()
&& PackedData::get_singleton()->has_path(path) ) {
   // print error
   return ERR_INVALID_PARAMETER;
};

**Pull request closed without merging**
