### PR TITLE
Ensure EditorNode exists before accessing it

### LINKED ISSUE #80704: Executing `EditorInterface.restart_editor` function crashes Godot
### Godot version

4.2.dev.custom_build. a278c1b98

### System information

Ubuntu 22.04 CI

### Issue description

When executing
```
extends Node2D
func _process(delta):

	var temp_variable_f120 = true
	EditorInterface.restart_editor(temp_variable_f120)
```
Godot crashes:
```
editor/editor_interface.cpp:53:47: runtime error: member call on null pointer of type 'struct EditorNode'
editor/editor_interface.cpp:53:47: runtime error: member access within null pointer of type 'struct EditorNode'

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev.custom_build (a278c1b98a81738a35b96a933a6e6cf771f9ab2d)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /home/rafal/Downloads/Untitled Folder/godot.linuxbsd.editor.dev.x86_64.san() [0x2ab1482] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/crash_handler_linuxbsd.cpp:57)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x3c4b0) [0x7f4f73c3c4b0] (??:0)
[3] EditorInterface::restart_editor(bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/editor/editor_interface.cpp:53)
[4] void call_with_variant_args_helper<__UnexistingClass, bool, 0ul>(__UnexistingClass*, void (__UnexistingClass::*)(bool), Variant const**, Callable::CallError&, IndexSequence<0ul>) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:308 (discriminator 4))
[5] void call_with_variant_args_dv<__UnexistingClass, bool>(__UnexistingClass*, void (__UnexistingClass::*)(bool), Variant const**, int, Callable::CallError&, Vector<Variant> const&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/variant/binder_common.h:421)
[6] MethodBindT<bool>::call(Object*, Variant const**, int, Callable::CallError&) const (/home/runner/work/GodotBuilds/GodotBuilds/godot/./core/object/method_bind.h:331)
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Callable::CallError&, GDScriptFunction::CallState*) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript_vm.cpp:1825)
[8] GDScriptInstance::callp(StringName const&, Variant const**, int, Callable::CallError&) (/home/runner/work/GodotBuilds/GodotBuilds/godot/modules/gdscript/gdscript.cpp:1892)
[9] bool Node::_gdvirtual__process_call<false>(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.h:318 (discriminator 1))
[10] Node::_notification(int) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/node.cpp:57)
[11] Node::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/node.h:49 (discriminator 14))
[12] CanvasItem::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/main/canvas_item.h:45 (discriminator 3))
[13] Node2D::_notificationv(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/./scene/2d/node_2d.h:37 (discriminator 3))
[14] Object::notification(int, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/core/object/object.cpp:800)
[15] SceneTree::_process_group(SceneTree::ProcessGroup*, bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:948)
[16] SceneTree::_process(bool) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:1020 (discriminator 2))
[17] SceneTree::process(double) (/home/runner/work/GodotBuilds/GodotBuilds/godot/scene/main/scene_tree.cpp:510)
[18] Main::iteration() (/home/runner/work/GodotBuilds/GodotBuilds/godot/main/main.cpp:3467)
[19] OS_LinuxBSD::run() (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/os_linuxbsd.cpp:912)
[20] /home/rafal/Downloads/Untitled Folder/godot.linuxbsd.editor.dev.x86_64.san(main+0x58f) [0x2ab0f15] (/home/runner/work/GodotBuilds/GodotBuilds/godot/platform/linuxbsd/godot_linuxbsd.cpp:76)
[21] /lib/x86_64-linux-gnu/libc.so.6(+0x23a90) [0x7f4f73c23a90] (??:0)
[22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7f4f73c23b49] (??:0)
[23] /home/rafal/Downloads/Untitled Folder/godot.linuxbsd.editor.dev.x86_64.san(_start+0x25) [0x2ab08c5] (??:?)
-- END OF BACKTRACE --
```

This example was found by Godot fuzzer - [Qarminer](https://github.com/qarmin/Qarminer), so it is quite unlikelly that this code could be used in real project, but still this should be handled gracefully.

Memory leaks or asan backtraces are visibe when using Godot build with sanitizers support - https://github.com/qarmin/GodotBuilds/actions (linux -> linux-editor-sanitizers)

### Steps to reproduce

Above

### Minimal reproduction project

Above

### PR DESCRIPTION
**Pull request by garychia**
Fixes #80704

### CODE REVIEW

**Review by akien-mga — COMMENTED** [review]
That works, but I think the whole class needs a review at many of its functions access objects which may or may not exist. E.g. `get_selection()` can likely crash the same way, or `edit_node()`.

**Comment by garychia** [comment]
Sure. Will inspect the issue more carefully and see if I can discover something more.

**Comment by garychia** [comment]
One question - is there a mechanism that prevents the user from accessing `EditorInterface` if the editor is not available? (E.g. accessing the `EditorInterface` singleton and checking if it is valid instead of directly accessing the class.)
Currently, the only solution I came up with is to check if `EditorNode` is valid before accessing it.

**Comment by YuriSizov** [comment]
> One question - is there a mechanism that prevents the user from accessing `EditorInterface` if the editor is not available?

That's the first editor-only singleton that we have, so unfortunately we don't have a mechanism. So I created a PR that address the issue at its core: https://github.com/godotengine/godot/pull/80962

I think we shouldn't fix this by adding extra checks everywhere. Thanks for your work nonetheless!

**Comment by akien-mga** [comment]
Superseded by #80962.

**Pull request closed without merging**
