### PR TITLE
Drag open scan window if engine.cfg not found

### PR DESCRIPTION
**Pull request by profelis**

### CODE REVIEW

**Comment by akien-mga** [comment]
Just tested post-merge, the idea is good but I think the behaviour could be further improved.

E.g. if I drag and drop two folders (each containing an engine.cfg), I get this:
spectacle b30778

The name of the popup is a bit misleading (but it's the same as when clicking the "Scan" button, so it should probably be improved there), but mostly it only allows me to scan the first folder, and not the second one.

The current change itself is fine, just adding some thoughts for further improvements :)

**Comment by profelis** [comment]
Thanks, for review!

I thought about autoscan all dropped sub folders (maybe recursively), but
stopped on scan dialog.

**Comment by akien-mga** [comment]
Regarding the above, I improved the title of the FileDialog: 0b595f9

**Comment by akien-mga** [comment]
When dragging several folders, I think what could be better instead of showing the FileDialog would be to show a custom popup asking the user to confirm the scan of `p_files.size()` entries. What do you think? If the user confirms the dialog, then it would run `_scan_begin` on all paths directly.

**Pull request merged**
