### PR TITLE
Use the vertex colors by default in gltf.

### LINKED ISSUE #21087: glTF: Use the vertex colors when available
**Godot version:**

tip de0fb0798ed1c8d16633da9b4d29ce4114f25540

**Issue description:**

image

After the import you have to change each material manually:

image

### PR DESCRIPTION
**Pull request by fire**
Fixes #21087

### CODE REVIEW

**Comment by fire** [comment]
image

**Comment by akien-mga** [comment]
```
17:01 <Akien> reduz: ok with #41007 ?
17:11 <reduz> that makes the shader more complex if you are not using the vertex colors
17:11 <reduz> so no
```

**Comment by fire** [comment]
The GLTF spec says vertex colors need to be mixed with materials, so I don't know how to solve this.

**Comment by capnm** [comment]
> 17:12 <reduz> also I have seen many times models that have vertex colors
> but they are not used, so when you load them the model looks wrong

The **model** is then exported incorrectly, it shouldn't contain any vertex colors ... 
you can then fix that in the material-settings manually.

**Comment by fire** [comment]
> iFire> reduz: So for clarity is the decision still to not to have vertex colors default to mix with the material for glTF2? It's ok to say no, but being in decision limbo is worse.
10:35 AM 
<reduz> Juan Linietsky iFire: to be honest, gltf2 probably is ok
10:35 AM for collada and fbx i am less sure
10:36 AM 
<iFire> that's a good reason
10:36 AM 
<reduz> Juan Linietsky the problem is that we will need to detect this and turn it on in the material

**Comment by akien-mga** [comment]
Well I thought that there was an import option for this, but obviously I must have been mistaken. Not sure what @reduz was referring to then.
Screenshot_20200903_195251

Let's reopen and assess further.

**Comment by fire** [comment]
> reduz> Juan Linietsky iFire: probably but the commits are kind of a mess, needs to be rebased

Will rebase when I have a free moment.

**Comment by akien-mga** [comment]
Thanks!

**Comment by capnm** [comment]
3.2 PR: https://github.com/godotengine/godot/pull/41149

(Sorry for the spam here, github keeps referencing old rebased commits and and doesn't have a `[Garbage Collection]` button)

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
