### PR TITLE
Remove WebGL 2 support, default to to GLES2 for UWP

### PR DESCRIPTION
**Pull request by leonkrause**
The WebGL 2 rasterizer has too many issues for use in production. Considering it'll be removed once the Vulkan rasterizer hits, it's unreasonable to work further on it.

With this patch only the WebGL 1 rasterizer is available for web export. This also saves about half a MB.

### CODE REVIEW

**Comment by eska014** [comment]
GPU particles and other GLES3-dependent features will not work in HTML5 export with these changes, it's essentially GLES2 only.

**Comment by starry-abyss** [comment]
Makes sense, but isn't it... unfair?
> Godot is to receive a $20,000 USD grant to fund support for Web Sockets, WebAssembly and **WebGL 2.0**.

**Comment by akien-mga** [comment]
@starry-abyss Implementing WebGL 2.0 support meant implementing an OpenGL ES 3.0 renderer, which is what we have. Then WebGL 2.0 itself is just a toggle, you can imagine that we didn't use 20k USD to implement the few lines that @eska014 proposes to revert.

**Comment by eska014** [comment]
Added a commit to default to GLES2 for UWP.
Also added a debug warning when a requested video driver is not available.

**Comment by jmo7** [comment]
Now that Chromium-based Microsoft Edge is almost upon us and Google has ported Angle to Mac and so WebGL 2 in Safari has resumed, what are the plan s for Godot and WebGL2? While it previously looked like it might die, it's now coming back in full force. 
(Of course someday WebGPU will be great, but it's not even close to being a done spec and it has very limited implementation so it's still at least a couple years away from being consistently usable)

**Comment by Calinou** [comment]
@jmo7 Graphics drivers (and ANGLE usage) remain problematic for this, so I'm afraid WebGL 2.0 won't be considered again.

**Comment by eon-s** [comment]
And Chrome still has a lot of problems with WebGL 2 too...

**Pull request closed without merging**
