### PR TITLE
Fix blend-file import when using custom color management in blender

### LINKED ISSUE #74439: OCIO Environment variable breaks Blender version detection
### Godot version

4.0 Stable

### System information

Windows 10

### Issue description

If using OCIO colour management, Blender outputs the default configuration file as part of the first line of its `--version` output. This breaks the version detection used by the automatic .blend file import, preventing you from importing .blend files directly.

As an example:
```
C:\Users\Mitch>"C:/Program Files/Blender Foundation/Blender 3.4/blender.exe" --version
Color management: Using C:\Users\Mitch\Documents\OCIO\config.ocio as a configuration file
Blender 3.4.1
    build date: 2022-12-20
    build time: 01:51:19
    build commit date: 2022-12-19
    build commit time: 17:00
    build hash: 55485cb379f7
    build platform: Windows
    build type: release
    build c flags: /W3 /w34062 /w34115 /w34189 /w35038 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /wd4848 /we4013 /we4133 /we4431 /we4033 /DWIN32 /D_WINDOWS /W3 /nologo /J /Gd /MP /bigobj /Zc:inline -openmp
    build c++ flags: /W3 /w34062 /w34115 /w34189 /w35038 /wd4018 /wd4146 /wd4065 /wd4127 /wd4181 /wd4200 /wd4244 /wd4267 /wd4305 /wd4800 /wd4828 /wd4996 /wd4661 /wd4848 /we4013 /we4133 /we4431 /we4033 /DWIN32 /D_WINDOWS /W3  /EHsc /nologo /J /Gd /MP /EHsc /bigobj /Zc:inline /permissive- /Zc:twoPhase- -openmp /Zc:__cplusplus
    build link flags: /MACHINE:X64  /SUBSYSTEM:CONSOLE /STACK:2097152 /ignore:4049 /ignore:4217 /ignore:4221
    build system: CMake```

### Steps to reproduce

1. Create an environment variable to set the OCIO configuration file. See https://docs.blender.org/manual/en/latest/render/color_management.html#opencolorio-configuration for extra info.
2. Add any `.blend` file to your project.
3. See the .blend auto-import fail

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by juliuse98**
Fixes #74439

### CODE REVIEW

**Comment by akien-mga** [comment]
The fix looks correct, but the form of the PR needs a bit more work:
- The commit message should state in English what it does, not just "Fix #number". See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind
- The branch should be rebased so that there's only one commit, no merge commit. See https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase
- It's fine as is for this PR, but for future PRs, it's recommended to create a dedicated branch for each PR, instead of using your `master` branch. If you use your `master` branch for a PR, it's trickier to make new PRs in parallel without including the same commit again.

**Comment by juliuse98** [comment]
ok I am really struggling to follow what I am supposed to do here. I just seem to get more commits instead of less. help

**Comment by akien-mga** [comment]
I force pushed an update to your branch to fix it up :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.

**Pull request merged**
