### PR TITLE
Document performing local rotation with Transform2D and Transform3D

### PR DESCRIPTION
**Pull request by Calinou**
This salvages https://github.com/godotengine/godot/pull/43694 and also applies it to Transform2D in the process. (Please double-check the Transform2D part as I'm not sure if it's actually correct.)

Thanks @AlexanderPruss for the original PR :slightly_smiling_face:

### CODE REVIEW

**Comment by kleonc** [comment]
> Please double-check the Transform2D part as I'm not sure if it's actually correct.

Looks correct to me but the suggestions are kinda meh as "_consider calling `rotated` on ... instead_" doesn't really tell how the results and the original transform should be combined to obtain mentioned transform (original rotated "in place"). And I think what's being suggested is:
```
var t: Transform2D = ...
t.x = t.x.rotated(angle)
t.y = t.y.rotated(angle)
# Now `t` is rotated as desired.
```
```
var t: Transform3D = ...
t.basis = t.basis.rotated(axis, angle)
# Now `t` is rotated as desired.
```
So again, not sure if such suggestions are clear for someone who needs such hints in the first place.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
IMO it is an improvement :) I'm fine with merging it.

**Comment by akien-mga** [comment]
Isn't the original proposal that prompted this (https://github.com/godotengine/godot-proposals/issues/1788) kind of superseded by https://github.com/godotengine/godot-proposals/issues/1336 / https://github.com/godotengine/godot/pull/55923? So if this doc change doesn't really make things clearer it's maybe best left as is for now?

**Comment by akien-mga** [comment]
Superseded by https://github.com/godotengine/godot/pull/55923 AFAIU.

**Pull request closed without merging**
