### PR TITLE
Add parse_json/to_json support for Array

### PR DESCRIPTION
**Pull request by sanikoyes**
Add parse_json/to_json support for Array

### CODE REVIEW

**Comment by akien-mga** [comment]
JSON makes sense for a Dictionary, but what would be the use case with an Array?

**Comment by punto-** [comment]
A few people had this problem, where they get an array from the network
instead of a dictionary. The array usually has dictionaries inside of it. A
lot of standard REST apis use this. The workaround is to wrap your data
with something like "{ \"_payload\": "+your_json_string+" }" and then
access the _payload key, but if this is a standard json feature, I don't
see why not support it.. Maybe in Marshalls, so you don't have to actually
know the type of object you need to instance to call parse_json on it?

**Comment by akien-mga** [comment]
Could we have a decision on this old PR? Do we want to add JSON parsing support to Array, and if so, should @sanikoyes or someone else try to rebase this PR?

**Comment by punto-** [comment]
I'd rather have a method in Marshalls or somewhere like that which returns
the correct structure (array or dictionary), otherwise you'd have to do
some string hacking to determine if you're supposed to feed your string to
an array or a dictionary to get it parsed. Let the parser do that.

**Comment by akien-mga** [comment]
Would you implement it? We miss your commits in the recent git history ;)

**Comment by vnen** [comment]
This would be great to have for 2.1.

**Comment by reduz** [comment]
marshalls is for marshalling, this has nothing to do with marshalling

What actually has to be done is to move parse_json() to String, and a
to_json() in Array()

as this would break compatibility, let's do it for 3.0

**Comment by neikeq** [comment]
@reduz We could always keep Dictionary.parse_json() as a deprecated method until 3.0.

**Comment by akien-mga** [comment]
Yeah IMO we don't have to wait for 3.0 for every API change that would break compatibility, we just have to keep the deprecate methods around until 3.0, with a proper warning so that users know beforehand about it. Then most users would have a painless migration to 3.0 if they were using 2.1 and 2.2 before.

**Comment by hubbyist** [comment]
This feature will be very usefull for keeping row order intact when comminicating with REST API's to query tabular data.

**Comment by akien-mga** [comment]
The PR as is won't be merged, but the good points it raised are now tracked in various issues (especially #5696), so let's close and reduce the PR backlog.

**Comment by akien-mga** [comment]
Fixed in 62273e5.

**Pull request closed without merging**
