### PR TITLE
Fix scrollbar issues in `ScrollContainer`

### PR DESCRIPTION
**Pull request by YeldhamDev**
- Fix scrollbars ignoring panel margins.
- Fix scrollbars and children not updating immediately on theme/RTL changes.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
This is more due to the bigger issue that clipping can only happen at the edge of Controls, and the borders can still be useful if only one scroll is active.

Besides, the current state is even worse:
image

**Comment by KoBeWi** [comment]
The current state is that the panel margin appears nicely around the contents:

https://github.com/godotengine/godot/assets/2223172/a44a57e6-e405-4a71-abda-28c8c75ca26c

idk what happened in your screenshot.

**Comment by YeldhamDev** [comment]
Have one of the sides just expand instead of giving it a large minimum size and you will see.

**Comment by KoBeWi** [comment]
I'm still getting the same results. Can you share the scene?

**Comment by YeldhamDev** [comment]
[scroll-bug.zip](https://github.com/godotengine/godot/files/15461633/scroll-bug.zip)

**Comment by KoBeWi** [comment]
Ah, so it's because of the borders. If you remove the borders and instead give it a margin, it looks good.
Well, what I posted initially still looks weird, so hard to say which one is better.

**Comment by YeldhamDev** [comment]
It's only weird if both scrolls are active, and besides, using this buggy behavior the create separation between the scrolls and content is hacky, and should be substituted which proper theme constants.

Also, fixing this allows to create a separation between the scrolls and the borders, which will be handy for themes that have scrolls with shadows that get clipped by the container.

**Comment by KoBeWi** [comment]
By "weird" I mean the space between scrollbar and border. It makes the scroll float above the content.

> using this buggy behavior the create separation between the scrolls and content is hacky, and should be substituted which proper theme constants.

Not sure what do you mean here. The gap is caused by your changes. I just added a content margin to the StyleBox.

I checked how your scene looks with this PR and scrollbars look better with the border, but... eh. I think perfectly the contents should be clipped inside the middle part, so it doesn't go under scrollbars and margins. That's not really possible though.

**Comment by YeldhamDev** [comment]
> By "weird" I mean the space between scrollbar and border. It makes the scroll float above the content.

That also happens without a border, so I don't know what you're getting at?

> Not sure what do you mean here. The gap is caused by your changes. I just added a content margin to the StyleBox.

Talking about your previous statement:
_"Panel margins are more useful for the ScrollContainer's contents, not the scrollbars. If you want margins around scrollbars, you can wrap it in a PanelContainer."_

**Comment by KoBeWi** [comment]
Here the scrollbar is at the border. The dark gray area is stylebox margin. It nicely wraps around the content.
image

With your changes, the margin appears behind the scrollbar, creating an ugly gap:


With border, the former case looks worse, while the latter is a bit better.
Also, looking at it again, it's not something you can achieve with a PanelContainer like I thought before.

Anyway, it's not like either case is perfect, so whatever. I'll just do a code review later.

**Review by KoBeWi — APPROVED** [review]
Code looks ok.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
