### PR TITLE
Replace `find` with `contains/has` where applicable

### PR DESCRIPTION
**Pull request by AThousandShips**
* Replaces `find(...) != -1`, `find(...) > -1`, `find(...) >= 0` with `contains` for `String`
* Replaces `find(...) == -1`, `find(...) < 0` with `!contains` for `String`
* Replaces `find(...) != -1`, `find(...) > -1`, `find(...) >= 0` with `has` for containers
* Replaces `find(...) == -1`, `find(...) < 0` with `!has` for containers

Split into four commits for review to make it easier to compare each type, to check the replacements are appropriate

### CODE REVIEW

**Comment by Chaosus** [comment]
Guess this line could be changed too (after https://github.com/godotengine/godot/commit/d8aa2c65a9f857e86d0c1fc1cc6b95b8ccf23099): https://github.com/godotengine/godot/blob/d8aa2c65a9f857e86d0c1fc1cc6b95b8ccf23099/editor/connections_dialog.cpp#L285

**Comment by AThousandShips** [comment]
That's `findn` that's different, that's covered here:
* https://github.com/godotengine/godot/pull/91611

**Review by deralmas — APPROVED** [review]
The diff looks fine and I really appreciate this change!

Thanks for splitting the patch, it really helped with reviewing as I could go in full pattern-matching mode with the word diff.

**Review by akien-mga — APPROVED** [review]
Also looks good to me. I guess we can squash before merge now that it's been reviewed.

**Review by mhilbrunner — APPROVED** [review]
Thank you so much! Spotted nothing.

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
