### PR TITLE
[3.x] Backport `FlowContainer`

### PR DESCRIPTION
**Pull request by timothyqiu**
Backports #56104

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Seems to be working fine.

**Comment by akien-mga** [comment]
Thanks!

**Comment by mackatap** [comment]
This is really difficult to work with. Is there any plan to allow this work inside of a center container or margin container? There is no way to control where stuff shows up on the screen. For it to work, it must be the parent control node so that the anchors can be set to full rect. Placing objects inside of it in centercontainers also does not seem to work.

**Comment by KoBeWi** [comment]
> Is there any plan to allow this to work inside of a center container or margin container?

It does already work in these. The FlowContainer will shrink to minimal size. If you don't want it wrap too much, use minimum size or expand size flags.

**Pull request merged**
