### PR TITLE
Document the RenderingServer and RenderingDevice classes

### PR DESCRIPTION
**Pull request by Calinou**
Feel free to review existing descriptions, but consider this to be in its early stages for now as it's not quite 100% complete.

I'll need help for barrier/draw list/command-related functions of RenderingDevice as I don't have experience with those parts of Vulkan.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
This is a good start. Lets go ahead and merge this as I would like to get started filling in the rest

**Comment by akien-mga** [comment]
```
ERROR: RenderingServer.xml: Unresolved method reference "draw_msdf_texture_rect_region" in method "canvas_item_add_msdf_texture_rect_region" description.
ERROR: RenderingServer.xml: Unresolved method reference "CanvasItem.draw_nine_patch" in method "canvas_item_add_nine_patch" description.
ERROR: RenderingServer.xml: Unresolved method reference "CanvasItem.draw_particles" in method "canvas_item_add_particles" description.
```

**Comment by clayjohn** [comment]
> ```
> ERROR: RenderingServer.xml: Unresolved method reference "draw_msdf_texture_rect_region" in method "canvas_item_add_msdf_texture_rect_region" description.
> ERROR: RenderingServer.xml: Unresolved method reference "CanvasItem.draw_nine_patch" in method "canvas_item_add_nine_patch" description.
> ERROR: RenderingServer.xml: Unresolved method reference "CanvasItem.draw_particles" in method "canvas_item_add_particles" description.
> ```

Ah, I fixed those locally while working on docs last night.

I'll just make a PR with my commit and Calinou's commit and we can merge them both together.

**Comment by clayjohn** [comment]
Superseded by https://github.com/godotengine/godot/pull/71991 which includes this commit, some fixes, and some more changes

**Pull request closed without merging**
