### PR TITLE
Fix infinite loop in CSG `Build2DFaces::_find_edge_intersections`

### LINKED ISSUE #73927: Editor freezes and crashes when editing CSG blocks (CSGCombiner issue)
### Godot version

4.0 rc4/rc5

### System information

Windows 10 Pro, 16G RAM Build 19045 AMD Ryzen 5 1600 - NVIDA Geforce GTX 1070

### Issue description

I was working with csg blocks. I created a csgCombiner, then another block. Duplicated the block, renamed it then moved it to another location. I tried to adjust the Transform of the block and Godot goes unresponsive. I don't see a log to send.
I tried this on RC5 then went back to RC4, crashes in the same spot.

### Steps to reproduce

I was working with csg blocks. I created a csgCombiner, then another block. Duplicated the block, renamed it then moved it to another location. I tried to adjust the Transform of the block and Godot goes unresponsive. I don't see a log to send.
I tried this on RC5 then went back to RC4, crashes in the same spot.
With the uploaded project, try and duplicate the large csg wall, then move it to the opposite side of the floor, then fine adjust it to fit the edge. Godot will go unresponsive.

EDIT: I have been playing around with the csg blocks and haven't had another crash yet. I believe the cause is the csg combiner if that helps any. 

### Minimal reproduction project

[Godot4FPCWorld.zip](https://github.com/godotengine/godot/files/10831620/Godot4FPCWorld.zip)

### PR DESCRIPTION
**Pull request by justinwash**
Remaking this PR since I destroyed the last one doing git things... Sorry!

This PR solves issue https://github.com/godotengine/godot/issues/73927 in which _find_edge_intersections could loop infinitely while creating new faces from edge intersections by keeping track of which edges we have already processed and skipping edges with the same points and uvs that come up in subsequent loops.

Had some concern about the glitchy faces that appear in subtract mode, but that appears to also occur in the most recent master post- https://github.com/godotengine/godot/pull/74771 so I'm not sure they really need to be covered in this fix, or if its even related.

This branch working:
https://user-images.githubusercontent.com/6236852/234983317-df6c0734-25f3-4790-80c6-24844062dde8.mp4

Most recent Master branch crashing, also exhibiting similar geometry wonkiness:
https://user-images.githubusercontent.com/6236852/234984769-620a2f24-968e-4a08-9a56-f4cc383c6d27.mp4

This also includes the suggested edit of using LocalVector instead of Vector to hold the processed edges. More context here https://github.com/godotengine/godot/pull/76520#discussion_r1179708726

_Production edit: Fixes https://github.com/godotengine/godot/issues/73927_

### CODE REVIEW

**Comment by justinwash** [comment]
Looks like I missed an initialization. Fixing now.

**Review by fire — APPROVED** [review]
I saw the videos of the fix for the infinite loop and it seems to resolve the error.

The video also didn't seem laggy, don't have a performance test. Wanted to check the run-time complexity of the arrays (Vectors) but it's probably fine.

Looks good to me.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by justinwash** [comment]
Thank you!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
