### PR TITLE
update PCRE2 to version 10.31, fixes #15662

### LINKED ISSUE #15662: Update PCRE2 to 10.30+
**Godot version:**
Current master branch (c01575b)

**OS/device including version:**
All.

**Issue description:**
We currently ship with PCRE2 10.23, but version 10.30 was released in 2017: https://www.pcre.org/news.txt

We should sync with this version, but only after 3.0 as this could introduce unwanted regressions.

### PR DESCRIPTION
**Pull request by firefly2442**
Steps to replicate upgrade:

* Download version 10.31 (ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.31.tar.gz)
* Copied over `AUTHORS` and `LICENCE` files.  Some minor changes.
* Copy `src` folder over.
* Rename `src/config.h.generic` to `src/config.h` (as recommended in the comments at the top of the file)
* Rename `src/pcre2.h.generic` to `src/pcre2.h` (as recommended in the comments at the top of the file)
* Rename `src/pcre2_chartables.c.dist` to `src/pcre2_chartables.c`
* Remove `src/config.h.in` (presumably this is taken care of by the generic header?)
* Remove `src/pcre2.h.in` (presumably this is taken care of by the generic header?)

Are there any files that don't need to be included?  Perhaps `src/pcre2test.c`?

I was able to compile godot but I'm unsure about bugs or regression as mentioned in the original issue request [15662](https://github.com/godotengine/godot/issues/15662).  If others can review this I would be grateful.

Also, please `git squash` during merge or let me know and I can rebase.

### CODE REVIEW

**Comment by akien-mga** [comment]
None of the new files are compiled in `modules/regex/SCsub`, so either they are not needed, or they should be added to the SCsub. Some of those are arch-specific though and should only be compiled on the relevant arch.

CC @leezh for review/advice.

> Also, please git squash during merge or let me know and I can rebase.

We prefer not to use squash on merge on this repo, so it's better if you can do the squash in your branch directly.

**Comment by firefly2442** [comment]
I git squashed and made some updates.  I tried to reconcile the files in the current build system in Scons.  In some cases there were files in the git repo that are not listed in the build system.  Thanks for the help/comments.  Here are some notes:

`src/dftables.c`
Removed
This is a freestanding support program to generate a file containing
character tables for PCRE2. 

`src/pcre2_extuni.c`
Added, unicode is built by default so I added this
https://www.pcre.org/current/doc/html/pcre2unicode.html
https://www.pcre.org/current/doc/html/pcre2build.html
"_This module contains an internal function that is used to match a Unicode
extended grapheme sequence. It is used by both pcre2_match() and
pcre2_def_match(). However, it is called only when Unicode support is being
compiled._"


`src/pcre2_fuzzsupport.c`
Removed
standalone program

`src/pcre2posix.c`
`src/pcre2posix.h`
"_This module is a wrapper that provides a POSIX API to the underlying PCRE2
functions._"

`src/pcre2demo.c`
Demo not needed

`src/pcre2grep.c`
Seems to be standalone and not used in current build system

`src/pcre2_jit_test.c`
Not in current build system

`src/pcre2_printint.c`
For debugging, not in build system

`src/pcre2test.c`
For testing, not in build system

**Comment by leezh** [comment]
I have been busy the past few months and totally missed the update. Thanks for doing it for me. They look good but with the added steps in replicating the upgrade you ought to add in a README file with the instructions.

**Comment by akien-mga** [comment]
The README file exists already, so instructions should be updated here: https://github.com/godotengine/godot/blob/master/thirdparty/README.md#pcre2 (together with the version number).

**Comment by firefly2442** [comment]
Updated `thirdparty/README` per suggestions.

**Pull request merged**
