### PR TITLE
Fix #7011 ScrollContainer takes into account child's EXPAND flag when scrolling is enabled

### LINKED ISSUE #7011: ScrollContainer expand flag regression
**Operating system or device - Godot version:**
Ubuntu 16.04 64b - Godot 2.1.1 rc2

**Issue description** (what happened, and what was expected):
#6473 caused the regression, ScrollContainer won't expand it's child if scrolling is enabled.

**Steps to reproduce:**
`if (!(scroll_h || h_scroll->is_visible())) { expand if child's flag is set }`
There is no chance to get into this block of code if scroll_h is set. The same for scroll_v.

**Link to minimal example project** (optional but very welcome):

### PR DESCRIPTION
**Pull request by pkowal1982**
Should be fine now.

### CODE REVIEW

**Comment by akien-mga** [comment]
It would be great if you could use more explicit commit logs :)
See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-logs-with-readability-in-mind

**Comment by pkowal1982** [comment]
Sorry, in github this #7011 is automatically linked to the issue with full description, but in other tools it could be less decriptive. I can close this and create another PR if you think it'll be better.

**Comment by akien-mga** [comment]
You can update the commit log with `git commit --amend` and update the PR with `git push --force` :)

**Comment by pkowal1982** [comment]
OK, done :)

**Pull request merged**
