### PR TITLE
embree: Build on ARM64 with -flax-vector-conversions

### PR DESCRIPTION
**Pull request by akien-mga**
This is a changed done upstream in the `devel3` branch for 3.13.6.

### CODE REVIEW

**Comment by akien-mga** [comment]
Confirmed needed by https://github.com/godotengine/godot/pull/69144#issuecomment-1358971952, I restricted it to only Linux and macOS like upstream's own CMake code.

Might be needed on Windows ARM64 (notably with MinGW GCC/Clang), but I can't test to confirm or not.

**Comment by aaronfranke** [comment]
This PR fixes compiling on Ubuntu 22.04 arm64, but breaks compiling on macOS 13.0.1 arm64:

```
[ 43%] Compiling thirdparty/embree/common/sys/sysinfo.cpp ...
In file included from thirdparty/embree/common/sys/sysinfo.cpp:5:
In file included from thirdparty/embree/common/sys/intrinsics.h:13:
In file included from thirdparty/embree/common/sys/../simd/arm/emulation.h:12:
thirdparty/embree/common/sys/../simd/arm/sse2neon.h:5957:33: error: cannot initialize a parameter of type 'float32x4_t' (vector of 4 'float32_t' values) with an lvalue of type '__m128d' (aka 'float64x2_t')
    __builtin_nontemporal_store(a, (float32x4_t *) p);
                                ^
```

It seems really strange that this configuration is required on Linux but breaks everywhere else...

**Comment by akien-mga** [comment]
Oh well, let's keep it surgical then. Upstream also seems to just be randomly switching stuff on and off until it compiles so we can do the same.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Pull request merged**
