### PR TITLE
Fixed CPU Lightmapper BakedLightmap crash

### LINKED ISSUE #49881: CPU Lightmapper BakedLightmap always crash on bake when atlas_generate enabled and/or generate_lightmap
### Godot version

3.3 3.3.1 3.3.2 Stable official

### System information

Linux

### Issue description

Crash:

Enabling any of this make Godot 3.3.2 crash (same in previous)

1. BakedLightmap - Atlas - generate
2. on MeshInstance - generate_lightmap (with Use in Baked)

log

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3d520) [0x7f8e7c6b3520] (??:0)
[2] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x2c631c8] (??:?)
[3] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x2c749dc] (??:?)
[4] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1a716ba] (??:0)
[5] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x2180a85] (??:0)
[6] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x3071d4d] (??:?)
[7] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe3b596] (??:0)
[8] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe40d66] (??:0)
[9] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe41c2c] (??:0)
[10] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x260ec20] (??:0)
[11] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x3029839] (??:?)
[12] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe3b596] (??:0)
[13] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe40d66] (??:0)
[14] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe41c2c] (??:0)
[15] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1c0a210] (??:0)
[16] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x3029839] (??:?)
[17] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe3b596] (??:0)
[18] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe40d66] (??:0)
[19] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe41c2c] (??:0)
[20] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1c7e3a3] (??:0)
[21] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1c7e915] (??:0)
[22] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1c7ec41] (??:0)
[23] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x23fc86f] (??:0)
[24] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe3b94e] (??:0)
[25] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe01f7d] (??:0)
[26] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1c9e245] (??:0)
[27] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1ca6ee7] (??:0)
[28] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1ca8eb5] (??:0)
[29] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1ca9006] (??:0)
[30] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x2e565ff] (??:?)
[31] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe3b596] (??:0)
[32] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0xe02005] (??:0)
[33] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1cd31a7] (??:0)
[34] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x1cd5fb0] (??:0)
[35] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x311c283] (??:?)
[36] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x30b92ac] (??:?)
[37] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x311f727] (??:?)
[38] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x98e9cc] (??:0)
[39] /lib64/libc.so.6(__libc_start_main+0xd5) [0x7f8e7c69db25] (??:0)
[40] /home/danil/bin/godot_3.3/Godot_v3.3.2-stable_x11.64() [0x99d1be] (??:0)
-- END OF BACKTRACE --
```

Can we have some actually working tutorial/project for BakedLightmap? (with working project)

And this https://docs.godotengine.org/en/stable/tutorials/3d/baked_lightmaps.html its outdated.

### Steps to reproduce

1. download my [bake_test.zip](https://github.com/godotengine/godot/files/6707929/bake_test.zip) and open in Godot
2. Scene bake.tscn click Bake Lightmap on BakedLightmap node - crash.
3. Scene bake_crash.tscn to test "_on MeshInstance - generate_lightmap_" same click Bake Lightmap on BakedLightmap - crash.

### Minimal reproduction project

[bake_test.zip](https://github.com/godotengine/godot/files/6707929/bake_test.zip)

### PR DESCRIPTION
**Pull request by Valeryn4**
Fix CPU Lightmapper baked [#49881](https://github.com/godotengine/godot/issues/49881)

*Bugsquad edit:* Fixes #49881.

### CODE REVIEW

**Comment by JFonS** [comment]
The fix regarding `bake_textures` looks good, nice catch :)

The other fix is also correct, but I would handle it a bit differently. Since the crash is caused by `max < 0`, and this can only happen if none of the meshes is set to genretate a lightmap, I would add a check for it and show a proper error message. Something similar to this:
```
diff --git a/editor/plugins/baked_lightmap_editor_plugin.cpp b/editor/plugins/baked_lightmap_editor_plugin.cpp
index 262524d73e..cf47d5b6d5 100644
--- a/editor/plugins/baked_lightmap_editor_plugin.cpp
+++ b/editor/plugins/baked_lightmap_editor_plugin.cpp
@@ -59,7 +59,7 @@ void BakedLightmapEditorPlugin::_bake_select_file(const String &p_file) {
 
                        } break;
                        case BakedLightmap::BAKE_ERROR_NO_MESHES:
-                               EditorNode::get_singleton()->show_warning(TTR("No meshes to bake. Make sure they contain an UV2 channel and that the 'Bake Light' flag is on."));
+                               EditorNode::get_singleton()->show_warning(TTR("No meshes to bake. Make sure they contain an UV2 channel and that the 'Use In Baked Light' and 'Generate Lightmap' flags are on."));
                                break;
                        case BakedLightmap::BAKE_ERROR_CANT_CREATE_IMAGE:
                                EditorNode::get_singleton()->show_warning(TTR("Failed creating lightmap images, make sure path is writable."));
diff --git a/modules/lightmapper_cpu/lightmapper_cpu.cpp b/modules/lightmapper_cpu/lightmapper_cpu.cpp
index 79515d04a6..28fd2f5a38 100644
--- a/modules/lightmapper_cpu/lightmapper_cpu.cpp
+++ b/modules/lightmapper_cpu/lightmapper_cpu.cpp
@@ -1303,9 +1303,18 @@ LightmapperCPU::BakeError LightmapperCPU::bake(BakeQuality p_quality, bool p_use
                }
        }
 
+       bool has_baked_mesh = false;
        for (unsigned int i = 0; i < mesh_instances.size(); i++) {
+               if (mesh_instances[i].generate_lightmap) {
+                       has_baked_mesh = true;
+               }
                raycaster->add_mesh(mesh_instances[i].data.points, mesh_instances[i].data.normal, mesh_instances[i].data.uv2, i);
        }
+
+       if (!has_baked_mesh) {
+               return BAKE_ERROR_NO_MESHES;
+       }
+
        raycaster->commit();
 
        scene_lightmaps.resize(mesh_instances.size());
```

This way the editor won't crash and users will have a better idea of what is actually happening.

**Comment by Valeryn4** [comment]
> Something similar to this:

What is required of me?

**Comment by JFonS** [comment]
> What is required of me?

You can update this pull request to include the changes I mentioned instead of `|| max <= 0`. Then it will be ready to merge :)

**Comment by Valeryn4** [comment]
update

**Comment by JFonS** [comment]
Awesome! 

In order to keep the git history clean, we require commits to be squashed together whenever possible.

You can check this documentation page on how to do it: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html (there are translated versions of the page in the bottom left corner menu).

**Comment by Valeryn4** [comment]
rebased

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.

**Pull request merged**
