### PR TITLE
Add alert in anim trees if resource load fails

### PR DESCRIPTION
**Pull request by kingoftheconnors**
Add_menu_type implements a resource loading, but only when the resource is initially valid. No alert message is shown if the resource isn't valid, leaving the user without feedback.

silentfail

This PR adds an else clause to the is_valid command to give feedback to the user when loading an animationPlaybackNode into an animation tree fails.

Implements proposal godotengine/godot-proposals#1624

### CODE REVIEW

**Comment by kingoftheconnors** [comment]
@Calinou Any chance of this getting reviewed?

**Comment by reduz** [comment]
This is good, but the error message should be changed from 'root nodes' to 'animation nodes'.

**Comment by kingoftheconnors** [comment]
> This is good, but the error message should be changed from 'root nodes' to 'animation nodes'.

Done!

**Review by KoBeWi — APPROVED** [review]
Looks ok on the editor side, but should be checked if it handles all cases.
Also maybe the error could be a constant, to avoid repeating it in multiple files?

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
