### PR TITLE
[UWP] [Export] added additional checks for blank values 

### PR DESCRIPTION
**Pull request by piratesephiroth**
`Short Name` and `Publisher Display Name` are mandatory.
You can't even sign the app package without them in the manifest.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Please squash your commits: https://docs.godotengine.org/en/3.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by piratesephiroth** [comment]
I'll just make a new pull request. I'm not wasting more time trying to figure this cryptic system out just for adding a few lines to a single file 🤣

**Comment by YeldhamDev** [comment]
It really isn't that hard once you get the hang of it.

**Comment by piratesephiroth** [comment]
it only added more commits everytime I tried to squash

**Comment by akien-mga** [comment]
> it only added more commits every time I tried to squash

That's because you pulled the original branch again after squashing, forcing it to apply the squashed commit on top of the existing history. You should use `git push --force` instead. See http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Pull request closed without merging**
