### PR TITLE
Fix inheriting from class_name messing up constants

### LINKED ISSUE #20008: Class cannot inherit enum
**Godot version:**

3.0.4

**Issue description:**

I created two classes: Class A and Class B. B extends from A. A has an enum. I tried calling the enum in class B, but an error message "Expected a constant expression" pops up. Does that mean that B cannot inherit enum from A?

**Steps to reproduce:**
So in Class A, I have typed the following:

`enum NUMBER{`
`    ONE,`
`    TWO,`
`    THREE`
`}`

`export(NUMBER) number_a`

No issue so far. In Class B, it has the following code:

`extends "res://Class_A.gd"'
'export(NUMBER) number_b`

At the "export(NUMBER) number_b" line, the error message "Expected a constant expression" pops up.

### LINKED ISSUE #29586: Inherited class does not load properly if used with `tool`
I see multiple issues related to class_name, but nothing obviously related to this one.

Godot 3.1.1 Stable
Windows 10

**Issue description:**
Adding `tool` before `extends` works if you use it like this:
 `extends "res://BaseClass.gd"`
but not like this:
`extends BaseClass`
obraz

**Steps to reproduce:**

```
#base class at res://BaseClass.gd
extends Node2D
class_name BaseClass

enum GameResourceType{ GRAIN, WOOD, STONE }
```
obraz
 (the base class is properly registered in Godot)

**This does not work:**
```
tool
extends BaseClass

export(GameResourceType) var resource_type:int = 0 setget _set_resource_type

func _set_resource_type(value):
	resource_type = value

```
**And this works:**
```
tool
extends "res://BaseClass.gd"

export(GameResourceType) var resource_type:int = 0 setget _set_resource_type

func _set_resource_type(value):
	resource_type = value
```

**Minimal project**
[class_name_and_tool.zip](https://github.com/godotengine/godot/files/3267377/class_name_and_tool.zip)

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fixes #20008.
Fixes #29586.

The fix felt somewhat too easy, but I think it is proper. If someone wants to give it a check on a larger GDScript-heavy project, feel welcome.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by CJCarns** [comment]
I think this problem has reemerged in the latest version, after relaunching my editor today my entire game is broken by "expecting constant expressions" where enums are used. I can't be the only one to have this problem after reloading the editor.

**Comment by bojidar-bg** [comment]
@CJCarns would be nice if you can provide a minimal reproduction project of that.

**Comment by CJCarns** [comment]
Sorry I eventually got it to work, looks like it was a weird mix of loading issues and unclear error reporting. By moving one of my enums around and making a couple small tweaks I got the error to stop in my project.

**Pull request merged**
