### PR TITLE
Scenetree Nodes drag and drop visual representation

### LINKED ISSUE #4684: Scenetree Nodes drag and drop visual representation
Currently when selecting many nodes in the scene tree and dragging them creates a list with all selected items which can result in a very long list that is displayed at the cursor position which is imho not needed. You probably read not more than the first 5 items, if even. Why not display the first few items and then fade them out.
Here is a mockup of how it could look like. 
dnd

### PR DESCRIPTION
**Pull request by volzhs**
fixes #4684

### CODE REVIEW

**Comment by reduz** [comment]
Awesome! :D Can you do the same for EditorNode::drag_files
and EditorNode::drag_files_and_dirs? :)
I think they are somewhere there

**Comment by volzhs** [comment]
@reduz I will see. :)

**Comment by volzhs** [comment]
I did the same thing for EditorNode::drag_files.
I think It is not good (left one), so I made another version (right one).
@reduz What do you think?

drag_files

**Comment by bojidar-bg** [comment]
@volzhs ~ Right looks way better to me, since it doesn't blend with the background.

**Comment by ndee85** [comment]
I like the left one more. Even if it is not that good to read as the right one. I don't think it is important to read what is dragged. You know it anyway. The right one feels somehow to clunky for my taste.

**Pull request merged**
