### PR TITLE
Integrated Collision Avoidance [WIP]

### PR DESCRIPTION
**Pull request by AndreaCatania**
This integration of the collision avoidance, which use RVO 2, is integrated with two idea in mind:
- Usability
- Cooperation with the actual Navigation mesh

#### Collision Avoidance OFF
CAOFF

#### Collision Avoidance ON
CAON

To show how to use it, I've created this short video, where you can see how easy is add Collision Avoidance to a Character that is moving using a normal Navigation Mesh: https://youtu.be/flPhAu9DpGU

### CODE REVIEW

**Comment by AndreaCatania** [comment]
Hey @reduz I would need to know if this implementation of Collision Avoidance make sense for you, and I can finish it.
The reason why I've created a server for this is to integrate better with the physics engine and allows the user to easily use CA and the current navigation mesh.

**Comment by groud** [comment]
Note, there is already a PR for that: #32557

**Comment by AndreaCatania** [comment]
@groud https://github.com/godotengine/godot/pull/32557#issuecomment-567853283

**Comment by AndreaCatania** [comment]
Replaced by: #34776

**Pull request closed without merging**
