### PR TITLE
Fix TabContainer not setting layout immediately

### LINKED ISSUE #23570: TabContainer doesn't layout its children when first added
Godot 3.1 alpha 2

Reproduction steps:
1) Create a TabContainer, give it some default size
2) Add a TextEdit as child in order to have one page: notice the page is created, but the TextEdit is not occupying that page properly.
image
Note: if you launch the game at this point, the page will be laid out properly, so it seems the issue only exists in the editor.
3) Try to resize the TabContainer: notice the content of the page resizes in weird ways, even disappearing sometimes
image
4) Now add another page by adding another control child
5) In the TabContainer properties, switch from page 0 to page 1
6) Switch back to page 0: notice the TextEdit now fits the page correctly
image

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #23570
The code I removed is done in `_repaint()`.

### CODE REVIEW

**Review by YeldhamDev — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!

**Comment by OverloadedOrama** [comment]
Any chance this bugfix will get cherrypicked for 3.4.3 as well?

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
