### PR TITLE
C#: Use SymbolEqualityComparer

### PR DESCRIPTION
**Pull request by raulsntos**
Use `SymbolEqualityComparer` to compare symbols and fix `RS1024` warning.

- Extracted from #65532
- Should fix CI for #87253

### CODE REVIEW

**Review by paulloz — APPROVED** [review]
Looks fine. Ran tests locally, and no issue to report.

**Comment by van800** [comment]
Sorry to bother, I am waiting for this pull request.

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
