### PR TITLE
Implement Ref<T>::operator=(T*)

### PR DESCRIPTION
**Pull request by lupoDharkael**
There are 4 ways to create a Ref:
```

Ref<T> myref;
my_ref.instance()

```
`Ref<T> my_ref(memnew(T));`

`Ref<T> my_ref = memnew(T);`

`Ref<T> my_ref = Ref<T>(memnew(T));`

All 4 are used in the source code but they do different things.
The first straight forward but requires 2 lines.
The 4th one is verbose and requires extra ref and unref.
The 3rd one is shorter than the 4th but is not as efficent as
we don't define operator=(T *from) so it tries to cast the pointer.

This PR creates that operator and changes the 4th from to th 3rd
in order to have a more compact Ref definition without unneeded
casting.

### CODE REVIEW

**Comment by lupoDharkael** [comment]
As additional info, there are around 260 occurrences of the 3rd type (the one this PR optimizes) not counting the additions presented here.
image

**Comment by Xrayez** [comment]
I think the source of these diverse usages come from both following the existing codebase and poor documentation, and likely the [`References`](http://docs.godotengine.org/en/3.2/development/cpp/object_class.html#id2) doc section needs an update too.

**Comment by sheepandshepherd** [comment]
Are you sure the middle two forms don't call the existing conversion constructor for these initializations?
```cpp
	Ref(T *p_reference)
```
That's what the documentation on [converting constructors](https://en.cppreference.com/w/cpp/language/converting_constructor) suggests should happen, instead of `operator=` being called.

The 4th form should also perform [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision) for initializations. They seem to fall under mandatory copy elision even. The less verbose forms are nicer though, for sure.

It might still be useful to have this operator, of course - are there are non-initialization `T*` assignments in the existing code that would call it? Should it call `init_ref()` like the converting constructor does? Newly-created References need to be initialized with that one rather than `ref()` so that `refcount_init` is set to 0.

**Comment by TechnoPorg** [comment]
The operator part of this PR seems to have been superseded by #36189, but there are still cases of usage number 4 in the code.

**Comment by reduz** [comment]
I prefer not to have this, you currently dont need to do this often so its better for readibility and avoiding mistakes that stays as-is.

**Comment by YuriSizov** [comment]
Closing as rejected (and severely outdated).

**Pull request closed without merging**
