### PR TITLE
Remove padding in line and column text

### PR DESCRIPTION
**Pull request by aryan-11825114**
| Master | This PR |
|--------|--------|
|Screenshot from 2024-08-22 13-30-44 | Screenshot from 2024-08-22 13-27-05 |

### CODE REVIEW

**Comment by AThousandShips** [comment]
Please explain the reason for changing this

**Comment by aryan-11825114** [comment]
The padding looks really odd here, this removes it for better visual consistency

**Comment by AThousandShips** [comment]
To me this padding looks better and improves readability, and avoids the interface jumping in size a lot when moving in small files, this will make the interface change when moving from low lines to high lines

The padding makes the length of the label stay stable, until files grow very large (over 10000 lines, or 1000 columns), now it'll shift when moving from line 1-9 to line 10-99, and again to 100-999, and again to 1000-9999, when before it would only do so when moving to lines over 9999

**Comment by aryan-11825114** [comment]
I see, I didn't consider that, you're right it would be better for the label to remain consistent in size.

**Pull request closed without merging**
