### PR TITLE
Fix outdated link to translation docs in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by shubhalgupta**

### CODE REVIEW

**Comment by akien-mga** [comment]
No that's the correct page for translation documentation. But the sentence needs to be reworked, it's not a "translation readme" anymore, it's a full localization documentation for contributors.

**Comment by shubhalgupta** [comment]
@Riteo, @akien-mga please review!

**Comment by akien-mga** [comment]
You misunderstood my comment, I was pointing out that https://docs.godotengine.org/en/stable/contributing/documentation/editor_and_docs_localization.html is the right page we should link to. But it's not a readme, it's a documentation page.

**Comment by shubhalgupta** [comment]
Sp, only the path needs to be changed or "translation readme" should also
be changed?

**Comment by Chaosus** [comment]
Commits needs to be squashed (see [docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#modifying-a-pull-request))

**Comment by akien-mga** [comment]
Please don't update multiple PRs for the same change. This is a duplicate of #83090.

**Pull request closed without merging**
