### PR TITLE
Improve the display of missing projects in the Project Manager

### PR DESCRIPTION
**Pull request by Calinou**
- Use a "broken file" icon instead of a "folder" icon for missing projects
- Fade out the project icon for missing projects
- Use transparent modulate for grayed out projects as it results in better-looking text
- Disable the "Edit", "Run" and "Rename" buttons if at least one missing project is selected
- Make double-clicking or pressing Enter do nothing when a missing project is selected
- Change the "Open in FileSystem" tooltip accordingly for missing projects
- Don't connect the "Open in FileSystem" pressed signal to make the button ineffective for missing projects
- Name missing projects as "Missing Project" instead of "Unnamed Project"

## Preview

image

### CODE REVIEW

**Comment by MarioLiebisch** [comment]
Looks good, although I guess one could argue that `Missing Project` might fit even better (it could have been moved or renamed after all).

As for icon, I'd use a new one, combining `icon_folder` with `icon_file_dead` as `icon_folder_dead`. I've [attached a quick edit](https://github.com/godotengine/godot/files/3527501/icon_folder_dead.zip), but can't figure out how to get a minified/simple SVG like the others.

**Comment by Calinou** [comment]
@MarioLiebisch Thanks for providing an icon!

Unfortunately, it doesn't really scale down well. The "dead" icons were designed to be displayed at largere sizes, but at small sizes, details in the icon become hard to see:

folder_broken_dark

folder_broken_light

I've still amended the pull request to use "Missing Project" instead of "Deleted Project". Thanks again for your feedback :slightly_smiling_face:

**Comment by MarioLiebisch** [comment]
Yeah, true. Might need a different icon group/style showing it's actually missing.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
