### PR TITLE
Fix: JAR files signed with the MD5 algorithm as unsigned (godot 3)

### PR DESCRIPTION
**Pull request by RameshRavone**
**Bugsquad edit**: Fixes https://github.com/godotengine/godot/issues/8758

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Context: **Starting in April (2017), if a JAR file is signed with MD5, Oracle will treat it as unsigned** (https://www.infoworld.com/article/3159186/security/oracle-to-java-devs-stop-signing-jar-files-with-md5.html)

**Comment by mhilbrunner** [comment]
It seems **SHA-1** is going to be deprecated too and this should use **SHA256withRSA**? (https://stackoverflow.com/questions/41878258/java-9-deprecating-sha1-certificates-or-another-issue-at-work)

**Comment by reduz** [comment]
What's the status of this?

**Comment by volzhs** [comment]
I can see it's updated to use SHA256 now.

**Comment by RameshRavone** [comment]
Sorry, guys I been having problems with the apk installation because of a file named `x2Icon.png`, renamed it to `Iconx2.png` now everything works.

**Comment by mhilbrunner** [comment]
Thank you!

**Comment by aaronfranke** [comment]
This should probably be cherrypicked, since otherwise Android export would lose signage capabilities.

**Comment by volzhs** [comment]
should it be cherrypicked on 2.1 branch also?

**Comment by mhilbrunner** [comment]
Yeah, this should be cherrypicked for 3.0.x

@volzhs There is https://github.com/godotengine/godot/pull/18626 for 2.1. See comment there.

**Comment by akien-mga** [comment]
Cherry-picked into 3.0.3.

**Pull request merged**
