### PR TITLE
[3.x] Fix alpha scissor shadow casting support

### PR DESCRIPTION
**Pull request by Ansraer**
3.x version of #58954, should fix https://github.com/godotengine/godot/issues/58924.

### CODE REVIEW

**Comment by clayjohn** [comment]
> should fix https://github.com/godotengine/godot/issues/58924.

Did you test the MRP in #58924?

**Comment by Ansraer** [comment]
Yes, appears to work the way it should:

<details>
<summary>Screenshot</summary>
image
</details>

Just noticed that my one-line change managed to break the mono build. No clue how that happened...

**Comment by Ansraer** [comment]
Huh, just forcing it to run again fixed it.

**Comment by Calinou** [comment]
> Yes, appears to work the way it should:

PS: You need to add a blank line after `<details>` (or `<summary>`) for Markdown to work inside the collapsed block. I edited your comment accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by Ansraer** [comment]
Fair enough, I will look into it again tomorrow.

**Comment by Ansraer** [comment]
Had some spare time to look into this again. You were right, there was a significantly cleaner solution to this than to just assume that everything with alpha scissors was either fully transparent or opaque.

**Review by clayjohn — APPROVED** [review]
Great work!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.4.

**Pull request merged**
