### PR TITLE
RegEx class documentation updated to reflect latest changes.

### PR DESCRIPTION
**Pull request by Ovnuniarchos**

### CODE REVIEW

**Comment by vnen** [comment]
This looks good, except for those merge commits. You can use `git rebase` to avoid adding unnecessary merge commits.

**Comment by akien-mga** [comment]
Indeed, there should be only one commit here that changes the doc/base/classes.xml files, not four.

**Comment by Ovnuniarchos** [comment]
Should I push the rebase I just did, or it's best that I leave it alone, and let this be advice for future commits?

**Comment by akien-mga** [comment]
Please push, if it's looking fine in your git log, it should be good to go. We already have plenty of examples of us nit-picking about merge commits :P You'll have to push with ```--force``` to override your branch.

**Comment by Ovnuniarchos** [comment]
As seen above, I made a small mess. Now it's nicely rebased.

**Comment by akien-mga** [comment]
Perfect, thanks!

**Pull request merged**
