### PR TITLE
Meta Interactive Feature

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds a public method `set_meta_interactive(true)` that enables a `meta_mouse_hovering` signal that can be used. (For RichTextLabels)
Default value is false.

For example, we have the `meta_click` signal already. This pull request enables an optional signal for when the mouse is hovering.  This can be used to create interactive text within the RichTextLabel.

One example: http://i.imgur.com/mL9spc8.png

### CODE REVIEW

**Comment by akien-mga** [comment]
As you can see on the PR page, the three commits you added all have the very unhelpful "Add files via upload" log. Could you rebase your master branch to squash those commits together, and edit the resulting commit log to be more descriptive?

A good commit log should have a descriptive commit title of around ~50-60 chars, and the details should go in the commit description, e.g.:
```
RichTextLabel: Add meta interactive feature

Adds a public method set_meta_interactive(true) that enables a meta_mouse_hovering
signal that can be used. Default value is false.
```

**Comment by akien-mga** [comment]
To be honest, I would advise you to avoid GitHub's "dropbox" mode. GitHub is a frontend to git and tries to hide its complexity (but also flexibility and efficiency) behind easy to use but very limited features like drag'n'drop upload... but it leads to very bad git history and unusable git logs :/

**Comment by Dillybob92** [comment]
I'm very new the entire 'git' thing, still grasping the ropes. I will do that now (or try :P)

**Comment by akien-mga** [comment]
Don't hesitate to ask for help on the #godotengine IRC channel on Freenode, we have some git gurus there ;)

**Comment by Dillybob92** [comment]
Alrighty, well this is not good. I got to remove the commits from my first post, but then they added them underneath your post. And now it says 12 files modified instead of 4 (by other users who I have never collaborated with). Not sure what is happening but I am sorry.

I will not use the web based upload in the future. I will submit  my branch with just 1 commit

**Comment by akien-mga** [comment]
No problem, it takes some time to master git :)

A quick hack that you could try:
1. Copy the files you changed to a safe location
2. Fetch the upstream repository with ``git remote add upstream https://github.com/godotengine/godot && git fetch upstream``
3. Reset your branch to the upstream repo with ``git reset --hard origin master`` (that will nuke all your commits, hence step 1 ;)) Check that it's clean with ``git log`` and ``git status``
4. Copy your files back into the new clean branch, add them to the staged changes ``git add path/to/file(s)`` (see ``git status`` again to check that they're properly staged), and commit ``git commit`` (it should open a text editor where you can write a commit log similar to the one I proposed earlier)
5. Force push your changes to fix the PR: ``git push --force origin master``

Hope this helps :) I know it can seem a bit daunting, it takes time to master, but once you do it's an awesome tool ;)

**Comment by Dillybob92** [comment]
Wow, this is brutal. Just did all the steps, took me forever, and then I get:

```
$ git push --force origin master
Username for 'https://github.com': dillybob92
remote: Permission to godotengine/godot.git denied to Dillybob92.
fatal: unable to access 'https://github.com/godotengine/godot.git/': The requested URL returned error: 403
```

I read about 20 different answers on StackOverflow too.  None are helping, changed and used ssh keys and everything.  Reinstalled git, did the entire process over again just to make sure but still cannot connect. I'm really getting frustrated because all I want to do it help contribute and git is making this process extremely difficult

**Comment by bojidar-bg** [comment]
@Dillybob92 Nono, you should push to your fork, not to godotengine/godot

**Comment by akien-mga** [comment]
Alright, the error in itself is fine. In my howto, I had assumed that you had a git clone of your own fork (https://github.com/Dillybob92/godot) but apparently you have a clone of the main godotengine repo.

So you should add your own fork as a remote, and then push to it:
```
git remote add myfork https://github.com/Dillybob92/godot
git push --force myfork master
```

**Comment by Dillybob92** [comment]
I think I got it now. This is very cool. But, when I am doing `git push myfork` it's pushing commits to this pull request. I don't want that, I just want to update my main fork without pushing. So then I create a new pull request with a different topic.

Or, is everyone only allowed 1 pull request thread?

This is cool now though, I really appreciate the help so far =]

**Comment by akien-mga** [comment]
Yeah, once you do a pull request, it's linked to your branch, so if you push new commits it will update the pull request (which is useful when you are asked to change things in your PR).

To be able to do multiple pull requests at once, you should use different branches. For example, assuming that your master branch is the same as the upstream one (which is not the case right now as you made this PR from your master branch):
```
git checkout -b pr-meta-interactive // creates a new branch named 'pr-meta-interactive' based on the current one (master), and moves in it
// do your changes and commit
git push myfork pr-meta-interactive // this will create a remote branch of the same name on your fork, and push your commits in it
git checkout master // return to the clean master branch, and maybe repeat the process with another branch name for another changeset
```

**Comment by Dillybob92** [comment]
Oh, so just have separate  branches for different "projects" or features to work on. I've saved all the github commands you gave too ^^. Will come in handy later :) Got it all now hopefully! ~

**Comment by akien-mga** [comment]
Another useful command: to cleanup your master branch which now has unwanted test commits and merge commits, you can use the ``git rebase`` command. It takes a ``-i`` argument to run it in interactive mode, and a commit hash indicating the oldest commit you want to handle in the rebase. You can use a commit hash, or ``HEAD~<nb>`` where `<nb>` is the number of commits you want to go up, on top of ``HEAD``, the latest commit.

So here, since you have 5 commits, and only the 1st one should be kept, you would do:
```
git rebase -i HEAD~5
```
It should then show you a text editor with instructions about what you can do. Basically you'd remove the lines corresponding to the commits you want to drop, and they will be rebased away.

Then check the status with ``git log``, and push to update your master branch with ``git push myfork master``.

**Comment by akien-mga** [comment]
So, you branch is even more messed up, it now contains 16 commits ;)
No worry, it's normal when learning to mess around with git. I'd advise you to retry https://github.com/godotengine/godot/pull/4804#issuecomment-221580312 (without the step about adding the upstream remote, since it's done already in your local clone) and by replacing step 5 with ``git push --force myfork master``

**Comment by Dillybob92** [comment]
You should of told me it was going to close this after `git push --force myfork master`, It freaked me out and I started to write why, then I figured.. It's part of the process :) Thanks for all your help @akien-mga!

**Comment by akien-mga** [comment]
Ah well it closed it because you made the force push with no commit in the branch :) In my original instructions on step 4 I was advising you to then make your new clean commit, before the freeze push. But it's just as well this way :)

**Comment by Dillybob92** [comment]
Oh oops, yeah I did that afterwords >_< . Bookmarking this pr though, will look back when I f-up again :)

**Pull request closed without merging**
