### PR TITLE
Fix Curve2D incorrect sample range description

### LINKED ISSUE #95881: Curve2D Documentation: sample() says range "0.0 >= t <=1" (should be "0.0 <= t <=1.0")
### Tested versions

stable + latest docs

### System information

N/A

### Issue description

[in Curve2D's documentation](https://docs.godotengine.org/en/latest/classes/class_curve2d.html#class-curve2d-method-sample), "0.0 >= t <=1" should be "0.0 <= t <=1.0"

The range is meant to be **t** between 0.0 and 1.0. And **t** is a float.

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/95881

### CODE REVIEW

**Comment by OffsetMOSFET** [comment]
Is there a reason to use 1 instead of 1.0? It's a float range.

**Comment by kleonc** [comment]
> Is there a reason to use 1 instead of 1.0? It's a float range.

Indeed it should be `0.0 <= t <= 1.0`.

**Review by kleonc — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
