### PR TITLE
Fix Variant to Vector<Variant> conversion operator

### PR DESCRIPTION
**Pull request by rxlecky**

### CODE REVIEW

**Comment by rxlecky** [comment]
```
/Users/travis/.travis/functions: line 109: scons: command not found
The command "scons --version" failed and exited with 127 during .
```
Is CI going bananas or did I miss something here? :D

**Comment by akien-mga** [comment]
Yeah that's a Travis issue: https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296

I've worked it around today so if you rebase on current `master` it should fix it.

**Comment by rxlecky** [comment]
Rebased :)

**Review by akien-mga — APPROVED** [review]

**Comment by rxlecky** [comment]
@akien-mga is this ready to be merged? Or does it need further approval?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
