### PR TITLE
More options for draw_circle and draw_rect

### PR DESCRIPTION
**Pull request by ghost**
To do this:

demo

i.e.:

rects
rects, antialiased
rects of different width
filled circles of different precision
filled circles of different precision, antialiased
circles of different precision
circles of different precision, antialiased
circles of different width and precision
circles of different width and precision, antialiased

Demo project:

[CircleTest.zip](https://github.com/godotengine/godot/files/1543349/CircleTest.zip)

Strange left bottom point anomaly in rect is also in master:

master

### CODE REVIEW

**Comment by reduz** [comment]
I like it, the draw first rect that looks like 70s op-art is probably unnecesary (I would not add it as i dont think users will use it often), but in genral it's ok.

We'll be merging this after 3.0 as we are in feature freeze

**Comment by Zylann** [comment]
Does it work with camera zoom?

**Comment by poke1024** [comment]
I'm still wondering if instead of

`draw_circle(const Point2 &p_pos, float p_radius, const Color &p_color, bool p_filled, float p_width, bool p_antialiased, int p_n_points)`

`p_antialiased` should be last, so it would be

`draw_circle(const Point2 &p_pos, float p_radius, const Color &p_color, bool p_filled, float p_width, int p_n_points, bool p_antialiased)`

I imagine as MSAA gets more common, `p_antialiased` might become more redundant, but I'm not sure.

**Comment by mhilbrunner** [comment]
@poke1024 Can you fix the conflict?

**Comment by poke1024** [comment]
Rebased, not sure what I need to do for the new GLES2 renderer though. Setting it on macOS currently crashes Godot?

**Comment by reduz** [comment]
@karroffel can you review and see how to add this to GLES2?

**Comment by karroffel** [comment]
@reduz the code for this is pretty much 1:1 the same, so copy-pasting should do 95% of the work already, shouldn't be any problem.

**Comment by Xrayez** [comment]
While it's not too late, could you add an option to specify accuracy via maximum imprecision instead of number of points? Or perhaps leave both options... Here's the formula taken from [Clipper](https://sourceforge.net/p/polyclipping/code/HEAD/tree/sandbox/Clipper2/offset_triginometry2.svg) repo:
circle_gen

That way you don't have to worry about your circle looking edgy when drawing large circles.

**Comment by poke1024** [comment]
@Xrayez I changed `n_points` to a `maxerror` according to the formula you give. Internally, the value is rescaled by `1/4` (i.e. `1 -> 0.25`) as a value of 1 still looked jaggy and only `0.25` looked smooth - at the same time I think it's nice to have a default value of `1.0` for this parameter. With this default setting, I did some experiments with the number of points generated, and for normally sized (e.g. small to half screen) circles it's between `10` and `60`, which is great.

Updated example code is here:
[CircleTest.zip](https://github.com/godotengine/godot/files/2250900/CircleTest.zip)

I also copied over the current GLES3 implementation to GLES2, I haven't tested though, since GLES2 currently crashes under macOS.

**Comment by aaronfranke** [comment]
This should probably be bumped to the 3.2 milestone, assuming that the status of "salvageable" is still accurate. If it isn't, it should be reviewed.

Also, the "bottom left point anomaly" mentioned in the OP should probably be looked at and fixed first.

**Comment by reduz** [comment]
After discussion, further improvements to vector like primitives are kind of useless until proper MSAA can be implemented for 2D. Currently, the status of that is:
- In GLES3 implementing it now is pointless, as this back-end will go away
- In GLES2 implementing MSAA is very difficult as there are different mobile extensions to do it depnding on the hardware, and it's also different on desktop too. Quite a lot of work.

If anyone wants to work on adding MSAA support to GLES2, then we can rediscuss the value of improving vector like primitives.

**Comment by akien-mga** [comment]
Closing for now then. This PR can still be used as a reference for implementing such things after MSAA.

**Comment by Zylann** [comment]
So until MSAA is implemented, we still have to write helpers to draw outline primitives like `stroke_rect` or `stroke_circle`?

**Comment by Xrayez** [comment]
This PR has *salvageable* label, but is this something that makes sense to implement in 4.0?

Note that quite a lot of this would be useful for godotengine/godot-proposals#112.

However, I've also recently implemented various draw helpers in Goost via `Debug2D` singleton: goostengine/goost#162, so there's no absolute need in those feature being implemented in core I guess.

**Pull request closed without merging**
