### PR TITLE
Make visual shader's `DefaultTextureParam` use `Texture` instead of `Texture2D`

### LINKED ISSUE #93051: Texture3D node in shader editor creates a Shader Parameter
### Tested versions

- Reproductible in: v4.2.2.stable.official [15073afe3]

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Laptop GPU (NVIDIA; 31.0.15.5212) - 13th Gen Intel(R) Core(TM) i7-13650HX (20 Threads)

### Issue description

Texture3D node in shader editor, when affecting the final shader output will create a parameter for materials using that shader that have to be set manually. This behavior is not consistent with the Texture2D node of the shader editor.

### Steps to reproduce

Create a visual shader and open the shader editor.
Create a Texture3D node in the shader editor and assign it a texture (the texture doesn't matter).
Connect the Texture3D node to the albedo output.
Create a ShaderMaterial resource and assign it the shader.
Under Shader Parameters will be a parameter named something similar to say "Tex 3d Frg 2" that is unset by default despite the shader editor's values.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/93051

There might be other reasons to use `Texture2D`, feel free to correct me.

### CODE REVIEW

**Comment by Chaosus** [comment]
CI needs to be fixed, use doctool next time (https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html#updating-class-reference-when-working-on-the-engine). Don't forget to squash the commits after the change.

**Comment by jsjtxietian** [comment]
Well looks like it breaks the compatibility...

**Comment by AThousandShips** [comment]
It breaks API compatibility which requires updating the API files (see hlthe ci for instructions) but it shouldn't break functional compatibility as it's an argument and takes a more general type so any calls are still safe

You also need to register a compatibility method

**Comment by jsjtxietian** [comment]
Is there any document on how to do this?  I'm a little confused on what to do 😢

**Comment by AThousandShips** [comment]
There's one in the works!
* https://github.com/godotengine/godot-docs/pull/9158

**Comment by Chaosus** [comment]
https://github.com/godotengine/godot/pull/95126 supersede this PR

**Comment by Chaosus** [comment]
Closed since it's superseded by https://github.com/godotengine/godot/pull/95126

**Pull request closed without merging**
