### PR TITLE
Style: Purge `.compat.inc` files

### PR DESCRIPTION
**Pull request by Repiteo**
I very, *very* strongly dislike the use of `.compat.inc` files. They exist as files dedicated to a handful of function implementations that aren't even wholly separated because they have to be initially declared in header files. From where I sit, it makes **much** more sense to handle these functions in their respective implementation file, as we're already doing in their headers. I don't have any concrete or objective resources to back this up, it's really as simple as me not liking them to the extent that I made a PR entirely out of spite

### CODE REVIEW

**Comment by KoBeWi** [comment]
These files allow for clearer separation of compatibility code.
I'd actually go in opposite direction and do more of that, e.g. for editor-only methods in `scene/` (e.g. #86743).

> it makes much more sense to handle these functions in their respective implementation file, as we're already doing in their headers.

They are in the headers only because it's the only way.

**Comment by Repiteo** [comment]
> They are in the headers only because it's the only way.

Ehh, not entirely. We've seen other headers use `.inc` files to define logic as if they were in headers; the most obvious example being [bvh_tree.h](https://github.com/godotengine/godot/blob/master/core/math/bvh_tree.h). I'd be MUCH more open to the idea of these files if the headers got the same treatment. Hell, you could probably make dedicated `#ifdef <HEADER_NAME_H>` defines to have that *same file* handle header **and** implementation logic

...Shit, I might've talked myself into this

**Comment by akien-mga** [comment]
> ...Shit, I might've talked myself into this

Let me put a blocker here. This needs to be discussed with maintainers before doing more significant work there.

This kind of change shouldn't be done on a whim for personal taste reasons. There's a reason why we designed a system with separate files for compat code.
You have to look up that reason before unilaterally deciding to yank it.

**Review by akien-mga — CHANGES_REQUESTED** [review]
This goes against our agreed guidelines with no good objective reason.

**Comment by Repiteo** [comment]
You know what, that's entirely reasonable. I might not entirely *agree*, but their reason for existing being laid out makes a lot of things "click". Closing.

**Pull request closed without merging**
