### PR TITLE
Some TextEdit selection improvements

### LINKED ISSUE #1190: Using the mouse wheel while selecting text ends the selection process
It would be nice to be able to use the scroll wheel while selecting text with the mouse in the editor.  Currently, if I'm highlighting text and use the scroll wheel, the text highlighting stops.  The only way to select a block of text that spans more than one page is to use the shift key.

### PR DESCRIPTION
**Pull request by neikeq**
One of the improvements is that it allows using pointer and shift selection together. Scrolling with mouse wheel does not longer end the selection process (closes #1190)

Changed the way shift+click selection works when changing from forward to backwards (and vice versa). It works similarly to shift selection (this is how most editors work).

[This video](https://www.youtube.com/watch?v=Qn5Lu8t498I) shows the main differences (before,  after).

### CODE REVIEW

**Comment by neikeq** [comment]
I am not sure if I used `selection.shiftclick_left` as it was intended. I see it was set to false if the click+shift selection was backwards and true if it was forward. Did I misinterpret it?
Also `selection.selecting_text` is no longer being read. I deleted the only condition that was using it.

**Comment by jackmakesthings** [comment]
Nice! :+1:

**Comment by neikeq** [comment]
The last commit fixes vertical scroll when dragging the mouse, as requested in #2739. The sensitivity may be a bit too high, but I guess that can be changed if needed.
The only missing part is that it won't scroll if the mouse is idle, unlike most editors. Nothing annoying, but may be good to introduce.

**Comment by akien-mga** [comment]
The PR is working quite fine, thanks!
As you said having scrolling also on idle could be a nice addition, but the current PR is already a great enhancement.

The only little issue left IMO is that it starts scrolling down when you approach the last line of the TextEdit, but does not scroll up when you approach the first line of the TextEdit. To get it scrolling up, you actually have to go a bit further up, something like 20-30 px above the TextEdit area.

**Comment by neikeq** [comment]
Top margin was being truncated, should be fine now.

**Comment by akien-mga** [comment]
Works great :)

**Pull request merged**
