### PR TITLE
Improved view modes

### PR DESCRIPTION
**Pull request by nunodonato**
- Added a clay render mode to the viewport
- Changed the wireframe mode to unshaded and disabled rendering the environment

This is a followup to #11392, but I cant say it "fixes" it completely :)

Menu:
menu

Clay render mode:
clay

Wireframe without shading and environment:
wire

### CODE REVIEW

**Comment by nunodonato** [comment]
I had a slightly different version of the wireframe mode, without textures, but I guess it doesn't really harm to have those as well

**Comment by Calinou** [comment]
What about "Display Untextured"? "Display Clay Mode" sounds strange to me.

**Comment by nunodonato** [comment]
@Calinou untextured(no texture, but can have different colors) is different than "clay"(same plain material). I don't know what other name could fit better, I'm used to the concept of "clay renders" from 3d software. Let's see if anyone else has other suggestions

**Comment by Zephilinox** [comment]
Could always just call it Display Clay Textures

**Comment by CowThing** [comment]
The clay mode uses the default material, but doesn't that have a roughness of 0? Shouldn't the roughness be 1 so it's less shiny and easier to see the lighting?

Also in Viewport.xml the name DEBUG_DRAW_WIREFRAME was duplicated instead of being DEBUG_DRAW_CLAY.

**Comment by WiggleWizard** [comment]
I would definitely prefer to have the menu item to be called `Display Lighting`. Although there must be a difference between what you have in mind (clay textures) and showing just lighting?

**Comment by mhilbrunner** [comment]
Formatting needs to be fixed for this one :)

**Comment by nunodonato** [comment]
@mhilbrunner I'll fix formatting and whatever else is needed after there is consensus on what to call the "Clay" mode and that this is getting approved. otherwise will be wasting time ;)

**Comment by fire** [comment]
What is blocking this issue?

**Comment by fire** [comment]
I had an idea, what do you think about calling it "Display Clay Material"?

**Comment by akien-mga** [comment]
@reduz says he's OK with the feature, but would do the implementation differently and will likely work on it himself (so I'll assign #11392 to him and the 3.2 milestone). As such, closing this PR since it likely won't be merged, but it's linked in #11392 to use as a reference/starting point.

**Pull request closed without merging**
