### PR TITLE
Show C++ error condition in script editor debugger

### PR DESCRIPTION
**Pull request by akien-mga**
This was removed by @RyanStein in #21884 in the case where an error
message is provided, but this is actually useful information to have
even when there is a custom error message.

This PR makes it so that the "C++ Error" is shown whenever there is
a custom error message provided.

Also adds method name to the error item title, and re-adds the most
relevant info in the tooltip for quick error checks without expanding.

Renames C Error/Source to C++ Error/Source, since that's what it is.
And fix untranslatable entry due to misuse of TTR().

And some more cleanup for readability.

Cf. https://github.com/godotengine/godot/issues/32276#issuecomment-534119914

CC @profan

### CODE REVIEW

**Comment by akien-mga** [comment]
Screenshot_20190925_105345
Screenshot_20190925_105409

**Comment by akien-mga** [comment]
BTW, the index error shown above is supposed to have a custom error message, but it's not used at all in `ERR_FAIL_*INDEX_MSG` macros, as the method it calls ignores it:
https://github.com/godotengine/godot/blob/master/core/error_macros.cpp#L102-L107

Which could also mean that it currently creates a situation where an `ERR_FAIL_COND` following an `ERR_FAIL_INDEX_MSG` would likely print the error message of the `ERR_FAIL_INDEX_MSG`.

**Comment by profan** [comment]
@akien-mga Actually went back to look at this to see if the actual root cause could be fixed and your rationale for why the index specific method would ignore the error message but I can't really see it, because `_err_print_index_error` just calls the above `_err_print_error(...)` anyways and that one does exactly the same thing as the normal error setup.

Like literally the only thing it does special is set up the error message to be passed in, it doesn't override the error message set with `OS::set_last_error`

So it shouldn't be that, or rather at least I can't see how it would be.

**Comment by akien-mga** [comment]
@profan Ah my bad, I read the code too quickly and didn't really notice that it called into `_err_print_error`, only that there was no specific error message handling in that function itself.

**Comment by akien-mga** [comment]
I'll check if #32282 would have fixed that occurrence.

**Comment by akien-mga** [comment]
> I'll check if #32282 would have fixed that occurrence.

I confirm that #32282 did fix the missing error message for `ERR_FAIL_*INDEX_MSG`. But it also breaks the display of the C++ error condition, as expected.

**Comment by profan** [comment]
@akien-mga No problem really, I still think this was the better approach (and I read the code too quickly at first as well) as we still need to figure out what's actually wrong with the error handling setup, so I'll continue digging around a bit 👍 

Either way having the C++ error back in there is nice and should stay :P

**Pull request merged**
