### PR TITLE
Fix GLES3 multimesh rendering when using colors or custom data

### LINKED ISSUE #71897: OpenGL: The last instance of `MultiMesh` incorrectly sets the color
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Windows 10, OpenGL

### Issue description

Vulkan and Mobile:
Godot_v4 0-beta14_win64_kEcRNiMfNJ

OpenGL:
Godot_v4 0-beta14_win64_MQ233TZuPq

At first I thought it was related to `set_buffer()`, but it turned out that `set_instance_*` also work incorrectly.
Probably the custom information is also set incorrectly, but I haven't checked it yet.

### Steps to reproduce

* Open MRP
* In the editor, select `MeshInstance3D` node and change the `Count` property
* -- or --
* Start the project and move the slider

You can also switch the renderer to Vulkan and compare.

### Minimal reproduction project

[set_buffer().zip](https://github.com/godotengine/godot/files/10476834/set_buffer.zip)

### PR DESCRIPTION
**Pull request by bitsawer**
* Fixes https://github.com/godotengine/godot/issues/71897

OpenGL compatibility renderer compresses the 4-float instance color and instance custom data into 2 floats each, which means that if you only use color OR custom data the component count given to glVertexAttribIPointer() will be wrong. This causes the last rendered element to access data outside the instance buffer and the value it will try to read will be invalid (or it might crash your driver if you're unlucky).

This PR adjusts the component count to use 2 if only color or custom data are used. If both are used, the count will be 4.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
I think this won't work in the case where only a custom value is sent. The color is always in .xy and the custom is always in .zw. If only a custom value is used, the .zw values will be ignored and the user will get garbage

**Comment by bitsawer** [comment]
Good catch, the demo project didn't test that scenario so I missed that. I think the additional fix should be pretty simple, but I'll test this some more.

**Review by clayjohn — APPROVED** [review]
I agree with your reasoning. Its not ideal to always include padding, but realistically, the driver is likely going to add padding when we give it an attribute with only 2 components anyway.

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
