### PR TITLE
make GraphNode inherit VBoxContainer

### PR DESCRIPTION
**Pull request by leezh**
This allows children in GraphNode to use the EXPAND size flags, making its sizing behaviour more consistent.

Side effect is that BoxContainer now reads the frame stylebox for margins.

### CODE REVIEW

**Comment by reduz** [comment]
wait, why would you want this?

**Comment by leezh** [comment]
Oh, sorry, should've explained why.

I've been trying to build a dialouge-tree editor and getting the sizing of the TextEdit has been difficult. The only way I found was to manually set the minimum size. Looking at the code I found that it behaved similar to the VBoxContainer, but didn't respect the EXPAND flag.

I tried copying over bits of code from box_container.cpp, but I wasn't happy with how there was now two copies of the same code, so I changed it to inherit that class instead. I'm not entirely sure if I like how I implemented it, but it is the sort of behaviour I want. I was hoping that someone might help me there.

Oh, I've also tested it and it doesn't seem to make any difference to existing SceneGraphNodes.

v1.1-stable
Before

My git pull version
After

**Comment by okamstudio** [comment]
The problem IMO is that in this case graph nodes will always be collapsed,
they don't "expand". Setting the minimum size is the most natural way to
make a specific element within the node bigger. Many users also like to
change the editor theme, and setting a fixed size for the node may break
it.

On Tue, Jun 23, 2015 at 3:26 AM, Lee Zher Huei <notifications@github.com>
wrote:

> Oh, sorry, should've explained why.
>
> I've been trying to build a dialouge-tree editor and getting the sizing of
> the TextEdit has been difficult. The only way I found was to manually set
> the minimum size. Looking at the code I found that it behaved similar to
> the VBoxContainer, but didn't respect the EXPAND flag.
>
> I tried copying over bits of code from box_container.cpp, but I wasn't
> happy with how there was now two copies of the same code, so I changed it
> to inherit that class instead. I'm not entirely sure if I like how I
> implemented it, but it is the sort of behaviour I want. I was hoping that
> someone might help me there.
>
> Oh, I've also tested it and it doesn't seem to make any difference to
> existing SceneGraphNodes.
>
> v1.1-stable
> [image: Before]
> <https://camo.githubusercontent.com/94ad66733e4ee3bfacae64f2c2180ba8df6ed63f/687474703a2f2f692e696d6775722e636f6d2f45705a445273762e706e67>
>
> My git pull version
> [image: After]
> <https://camo.githubusercontent.com/f6c6346dc551c5833053c63611fa6a371f167de4/687474703a2f2f692e696d6775722e636f6d2f6d366c6f3264412e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/pull/2106#issuecomment-114376231>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
the best way to do this is to take the font size as reference and make your
control as many lines long as you need

**Comment by leezh** [comment]
Closed since it may lead to breakages with custom themes, and setting the minimum was the better option.

**Pull request closed without merging**
