### PR TITLE
Enhance game export, re-add embedded PCK option

### PR DESCRIPTION
**Pull request by RandomShaper**
~~**UPDATE:** Marked as WIP since the appended PCK approach has issues and a better way has to be implemented.~~
**UPDATE 2:** The better way is implemented now. It may still have some issues but I has worked flawlessly in my tests.

Two commits:
### Add embedded PCK option to PC platforms
The basic point is as in 2.1 (appending the PCK into the executable), but this implementation also patches a dedicated section in the ELF/PE executable so that it matches the appended data perfectly.

This way, the runtime code can find the PCK very easily by just looking at the end of the file, not having to parse the executable headers to find the special section. That's only needed during export.

The usage of integer types is simplified in existing code; namely, using plain `int` for small quantities.

### Skip export of non-project libraries
That is, any library referred to in GDNative library resources, won't be copied to the export target path unless its path begins with `res://`.

The case use for this is a bit advanced: having a GDN library that will be deployed separately from the project; for instance, to a path in the system (like `/opt/...`).

Currently the GDN library editor doesn't allow to pick dynamic libraries outside the project, but that can be done by editing the `.gdnlib` file manually.

------
**This code is donated by [AdPodnet](https://www.adpodnet.com/).**

------

~~Note for @hpvb: no cherry-picking needed. Dedicated PR for 3.0 is #24087.~~ **UPDATE:** 3.0-specific PR won't be worked on.

### CODE REVIEW

**Comment by akien-mga** [comment]
There are build issues on Linux and macOS: https://travis-ci.org/godotengine/godot/jobs/463024864
And a style issue: https://travis-ci.org/godotengine/godot/jobs/463024863

**Comment by RandomShaper** [comment]
I have yet to fix issues with cross-compilation and add CI checks for the special section. I'll do that ASAP.

**Comment by RandomShaper** [comment]
@akien-mga, I've updated the PR supporting MinGW as well.

Now, regarding what I told you about CI checks, could you lend me a hand?

What needs to be checked is this:

- for MSVC compilation, the command `dumpbin <template_executable> /SECTION:pck` prints at least something like this:
```
     pck name
       8 virtual size
```
- for MinGW compilation (Windows) and GCC/Clang compilation (X11), the output of the command `objdump -h <template_executable>` includes something like this:
```
  3 pck           00000008  0000000001db7000  0000000001db7000  019b4600  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
```

For all the cases, it really only matters that the `pck` section appears (first line in both cases). Other data can change and by having its presence checked we get enough peace of mind.

If you can help, feel free to commit to this branch.

**Comment by RandomShaper** [comment]
I don't really think you can commit to this branch. XD

Well, you can always add a commit later if this is merged. We can consider the CI checks something extra.

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and *release freeze* for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

**Comment by akien-mga** [comment]
Sorry for the late review. The first commit is a pretty simple and could be merged right away.

For the second commit, code changes seem fine, but I'd like it discussed with @reduz (to ensure he accepts to bring back the "embed PCK" feature) and @hpvb (regarding the extra linker stuff on X11).

**Comment by akien-mga** [comment]
@reduz said "if it works properly per platform, I think it's fine, the main problem is that the way I did it back then was way too hacked, and sometimes the binary would be detected as invalid".

I see you added a PCK section for Windows and X11, but what about macOS? Doesn't it need special handling too?

**Comment by RandomShaper** [comment]
The option is not available for Mac.
It's for the `ExportPlatformPC`, which includes Windows and X11.
For Mac, its export platform class is aside and I didn't see a clear path for it.
I may revisit it in a future, but this is how far I was able to get.
Aside, the CI checks would be interesting to add, but I need help for those.

**Comment by RandomShaper** [comment]
In my tests it worked properly and there were no false positives from AVs I tried.
Nonetheless, it would be good to have this for alphas and betas so people can try it.
I'll try to fix any issues that arise.

**Comment by akien-mga** [comment]
Thanks for the clarification, let's give it a spin then :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
