### PR TITLE
Expose loading TGA images in Image.

### PR DESCRIPTION
**Pull request by paulherman**
Part of godotengine/godot-proposals#676

### CODE REVIEW

**Comment by paulherman** [comment]
Is there some process I am missing to get the PR reviewed and merged? It's been 1m so I assume I missed a step :)

**Comment by Calinou** [comment]
@paulherman I don't think you missed a step; it's just that the PR backlog is very large.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by paulherman** [comment]
Thanks both! Perhaps a graph explaining the backload / burndown rate might help provide transparency (if Github has it). FTR, that's why I was asking about unit tests while referencing this PR - it's much easier than to provide a project.

**Comment by Calinou** [comment]
@paulherman We don't have a formal unit test process yet, see https://github.com/godotengine/godot-proposals/issues/871.

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Comment by Calinou** [comment]
@paulherman The [Pulse graph](https://github.com/godotengine/godot/pulse) should have this information.

**Pull request merged**
