### PR TITLE
Bump the java version to version 17

### PR DESCRIPTION
**Pull request by m4gr3d**
Follow up to https://github.com/godotengine/godot-docs/pull/7968

### CODE REVIEW

**Comment by m4gr3d** [comment]
Looks like we need to update the CI to Java 17 as well for the checks to pass.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
The CI build seems to fail.

**Comment by m4gr3d** [comment]
> The CI build seems to fail.

Yeah, it needs to be updated to Java 17 as well

**Comment by akien-mga** [comment]
You could try this:
```diff
diff --git a/.github/workflows/android_builds.yml b/.github/workflows/android_builds.yml
index ea97ef023d..495f643e56 100644
--- a/.github/workflows/android_builds.yml
+++ b/.github/workflows/android_builds.yml
@@ -20,11 +20,11 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Set up Java 11
+      - name: Set up Java 17
         uses: actions/setup-java@v3
         with:
           distribution: temurin
-          java-version: 11
+          java-version: 17
 
       - name: Setup Godot build cache
         uses: ./.github/actions/godot-cache
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Included in #87588.

**Pull request merged**
