### PR TITLE
Fix Network Profiler not disabling buttons

### LINKED ISSUE #96804: Network Profiler does not disable buttons
### Tested versions

4.4 dev 97ef3c8

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Unlike other profilers
image
image

The Network Profiler does not disable buttons when the project is not running
image
They just do nothing

On a side note, I think the Network Profiler button should be moved next to other profilers.

### Steps to reproduce

1. Open Debugger bottom pannel
2. Open Network Profiler
3. Press Start

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by aryan-11825114**
Fixes #96804

### CODE REVIEW

**Review by Geometror — APPROVED** [review]
Works as expected, code looks fine (although I have a planned to refactor some parts of the profiler code soon, so it's not that important)
Most likely it was just an oversight from 3.x where this was the behavior of all profilers, but maybe it had a specific reason to be startable before running a scene/the project, so @Faless should give this a look too.

**Comment by Faless** [comment]
> Most likely it was just an oversight from 3.x where this was the behavior of all profilers, but maybe it had a specific reason to be startable before running a scene/the project, so @Faless should give this a look too.

Before we had the autostart button (#96759) this was the only way to catch all the traffic, including the one at startup.

Now that we have autostart, we don't need to be able to start it manually while disconnected.

**Review by Faless — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
