### PR TITLE
chdir line was removed in pull request #8144 which breaks some things...

### PR DESCRIPTION
**Pull request by NathanWarden**
such as C# support.

	- This commit adds the original line of code back in which fixes it.

The original line has been in there since the second commit in the repo.

Thanks!

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't see the link with #10393? Don't you mean #8144?

**Comment by akien-mga** [comment]
CC @supagu.

**Comment by NathanWarden** [comment]
Oops, sorry about that. Yes, #8144. :)

**Comment by NathanWarden** [comment]
Yes, it would be very nice to get @supagu to chime in since they probably know more about what's going on in this code than I do. All I know is that not having the original line of code causes the problem and putting it back in fixes.

Of course, I don't want my "fix" to break symlinks either. :)

Thanks @supagu !

**Comment by supagu** [comment]
the chdir is there in my code:
bool worked = (chdir(current_dir.utf8().get_data()) == 0); // we can only give this utf8

I am wondering how your code actually ends up changing the dir, causing it to work for you, as you are changing back to the previous dir, which is what you are trying to change out from?

Do you have a simple test case/project I can use to test on this code?

**Comment by NathanWarden** [comment]
Thanks for the reply supagu,

I was wondering the same thing myself because, yes, it looks like it just changes back to the previous directory, however that code has been in there since the second commit of Godot (Feb 2014) and was there until this change. That doesn't make it correct code, of course, but it does seem odd that nobody saw it as buggy.

Unfortunately, I don't really have a simple test case. My test case includes C# support, so If you're on Linux I can send you a test case of your code vs the other code via Google Drive or whatever might work for you. One loads and runs (the previous code), one doesn't (this new code).

Maybe first, I'll dig into it a bit deeper tonight to see what's really going on with it and report back. :)

**Comment by NathanWarden** [comment]
@supagu It looks like you've fixed a bug that's been there for three and a half years! Pretty cool :)

@akien-mga Rémi, I think I found and fixed the cause of the C# not loading bug. I'll make a new pull request and will do a screen recording explaining what I did to make sure I'm not doing the wrong thing. If I am you guys can at least get an idea of it. It links against GodotSharp, so it's not easy to make a simple reproducible case. If you have any issues with that then please let me know.

Thanks!

**Pull request closed without merging**
