### PR TITLE
[3.2] Update Camera 2D to fix and remove some notifications

### PR DESCRIPTION
**Pull request by ghost**
Check #43995 For more info.

### CODE REVIEW

**Comment by Chaosus** [comment]
In order to accept your PR - you need to merge all commits together as described here: https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by TechnoArtStudio** [comment]
@Chaosus 
I didn't quite understand how to do that.
Which resulted on me doing mess in the master version of this PR.
Could you explain in steps?, so not to repeat the mistake.

**Comment by Chaosus** [comment]
I suggest to use the GitKraken app - select commits - press Right Mouse button - and choose Squash commit - then force push them to the origin branch

**Comment by TechnoArtStudio** [comment]
Now this is very bad.
As I fixed the other #43995 I deleted the repository as it is the base for this PR as well.
There for this also need to be close and open again.
Sorry for the mess.

**Pull request closed without merging**
