### PR TITLE
autocomplete for disconnect implemented

### LINKED ISSUE #37789: Disconnect doesn't support autocompletion
**Godot version:**
3.2.1

**Issue description:**
You disconnect the same signals that you would connect, so it makes sense that both methods should suggest the same signals (and methods) in autocompletion. This can be probably copy-pasted.

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #37789
disconnect

### CODE REVIEW

**Comment by akien-mga** [comment]
There's also `is_connected`.

**Comment by ThakeeNathees** [comment]
@akien-mga  done 👍

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by ThakeeNathees** [comment]
@akien-mga  could you have a look at these auto completions
#36879
#36759
#37232
#36950

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
