### PR TITLE
Add exrwav export to Godot Engine for movie making.

### LINKED ISSUE #6390: Movie Maker Mode EXR Output
### Describe the project you are working on

I would like to generate 16 bit and 32 bit EXR float images when using the movie maker mode.

### Describe the problem or limitation you are having in your project

The movie maker mode only exports to 8 bit formats, so if I want to use Godot as a render engine, then I will lose out on a ton of information that the view buffer has access to. Especially if I want to do some post processing on the renders.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

1. Add an option to render to OpenEXR for the movie maker.
2. Add support for 16 or 32 bit float outputs.
3. Add support for the different compression algorithms.
4. (Optional) Support for arbitrary metadata.
5. (Optional) Support for AOVs, or extra layers/channels with more information (such as AO, render passes, etc).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

When the user goes to the movie maker settings under the project settings, they can select EXR as an output, and set the EXR settings.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

If this isn't used, then it will likely have to be exported via GDExtensions, if GDExtensions supports arbitrary outputs from the movie mode.

### Is there a reason why this should be core and not an add-on in the asset library?

EXRs are used a lot in the animation/VFX industry, and it provides a ton of data that can be used in post production. Having support for exporting to EXR seems to make a ton of sense. Also, not sure how well this would be supported outside of the core.

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot-proposals/issues/6390

### CODE REVIEW

**Comment by fire** [comment]
Commentary said that it should be in srgb-linear instead of srgb-gamma.

**Comment by fire** [comment]
[Uploading fox exr.zip…]()

**Comment by Calinou** [comment]
Should this be a new writer, or should we refactor MovieWriterPNGWAV into MovieWaterImageWAV instead and allow it to use any image format that Godot can save (PNG, EXR, JPEG, WebP)?

**Comment by fire** [comment]
I have a prefered to have a refactor of MovieWriterPNGWAV into MovieWriterImageWAV, but this was a fun 1 hour change. Feel free to improve.

**Comment by fire** [comment]
This is salvageable but I don't have consensus this should be in godot engine.

**Pull request closed without merging**
