### PR TITLE
Use Roslyn to extract names of script classes from C# files

### PR DESCRIPTION
**Pull request by shartte**
Moved GodotSharpTools managed project and added tests. Migrated projects to new .NET SDK style and added code scanning based on the C# Roslyn compiler.

This will fix the various issues we have had with parsing C# properly since this actually makes us use the official C# compiler to parse the source code.

This should also address #27285 and supersedes the previous PR #27274 

Due to moving to SDK-style MSBuild project, we no longer need to invoke nuget separately, since `msbuild -restore` will take care of it. Removed the use of Mono's MSBuild since I had endless issues with it building this project. This means on Windows a system-provided MSBuild is required. How well it'll work on Linux/Mac, we'll have to see.

### CODE REVIEW

**Comment by shartte** [comment]
FYI, this will add a lot of dependencies to the GodotSharp\Tools folder since we now have to ship Roslyn with the Godot tools.

**Comment by cart** [comment]
This is 100% the right approach. The current parser is basically guaranteed to be imperfect and even if it was perfect we would constantly be playing catchup as the language evolves. I suggested something similar to these changes in this bandaid pr: #23515

**Comment by shartte** [comment]
IF Godot scripts were not file-based resources, we would not have to parse C# at all :-P
But that is something to discuss in #15661, and this PR just tries to fix the current situation.

**Comment by neikeq** [comment]
I tried the `Microsoft.Build` package in the past and it wasn't working properly with Mono, but I didn't think about trying it in a .NET Standard project. It seems to be working well.
There is still an issue that prevents us from using this package though. INAL but I'm pretty sure we can't use a package with [this  license](https://dotnet.microsoft.com/dotnet_library_license.htm) in Godot. I guess we need to build `Microsoft.Build` from source if we want the MIT license.

**Comment by neikeq** [comment]
We're in the process of figuring out how to build MSBuild from source to bundle it with Godot, but it will take some time. AFAIK you only need `Microsoft.CodeAnalysis.CSharp` for this PR. Is there a reason for changing the `Microsoft.Build` dependency?

**Comment by shartte** [comment]
@neikeq I switched to References instead of PackageReferences and travis still seems to be fine. Would this be okay?

**Comment by shartte** [comment]
@neikeq Yeah, this fails on Linux with:
```
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2130,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Build". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/travis/build/godotengine/godot/modules/mono/editor/Managed/GodotSharpTools/GodotSharpTools.csproj]
  /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2130,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.Build.Framework". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/home/travis/build/godotengine/godot/modules/mono/editor/Managed/GodotSharpTools/GodotSharpTools.csproj]
```

**Comment by akien-mga** [comment]
What's the status on this PR?

**Comment by neikeq** [comment]
This PR is severely outdated since a lot of things have changed. @shartte, are you still interested in getting this merged? Right after 3.2 stable is released there's green card for these changes and I can get it merged quickly once everything is good.

**Pull request closed without merging**
