### PR TITLE
Fix shader compilation with render_mode: `specular_phong`

### PR DESCRIPTION
**Pull request by Chaosus**

### CODE REVIEW

**Review by phocodes — COMMENTED** [review]
I still don't get the point of these changes.

**Review by clayjohn — CHANGES_REQUESTED** [review]
``A`` is still passed in here
https://github.com/godotengine/godot/blob/090e4c4abdd406a7ed7fc33d0a4670bba69a4c0a/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L716-L718
and here
https://github.com/godotengine/godot/blob/090e4c4abdd406a7ed7fc33d0a4670bba69a4c0a/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L910-L912

We need to use A when using soft shadows. A proper fix will be to replace line 241 with:
```
#ifdef USE_SOFT_SHADOWS
float cRdotV = clamp(A + dot(R, V), 0.0, 1.0);
#else
float cRdotV = clamp(dot(R, V), 0.0, 1.0);
#endif 
```

**Comment by Chaosus** [comment]
> I still don't get the point of these changes.

Create a shader in 4.0 and paste render_mode specular_phong to it and you will see.

@clayjohn Ah, ok. It's reserved for the future - since `A` is not assigned

**Comment by clayjohn** [comment]
@Chaosus ``A`` is assigned when ``USE_SOFT_SHADOWS`` is defined

**Review by clayjohn — APPROVED** [review]

**Comment by Chaosus** [comment]
Ah, right it's a function parameter (I confused it with a simple variable due to #define).

**Pull request merged**
