### PR TITLE
Add option to apply an offset to obj mesh import

### PR DESCRIPTION
**Pull request by BastiaanOlij**
I was playing around with one of kenney.nl 3d object packs and trying to turn it into a meshlib so it can be used with a gridmap.  

The problem I ran into was that a lot of the objects in the assetpack were offset incorrectly.

This PR adds a simple offset parameter to the import settings:
image

### CODE REVIEW

**Comment by Zireael07** [comment]
Kenney's packs are known for having offsets when imported into game engines, so thanks for having a workaround!

**Comment by akien-mga** [comment]
Is this only relevant for OBJ or should it be added for all Mesh import formats?

**Comment by BastiaanOlij** [comment]
I think only for obj, the other formats import objects in structures so you would have to set an offset for each object or something to make it meaningful

**Comment by akien-mga** [comment]
Thanks!

**Comment by Shadowblitz16** [comment]
This doesn't solve the issue with built in godot mesh shapes

**Pull request merged**
