### PR TITLE
Add string trim_prefix, trim_suffix, lstrip and rstrip methods

### PR DESCRIPTION
**Pull request by nikibobi**
~~`trim_start`/`trim_end`~~ `trim_prefix`/`trim_suffix` - removes a given string from the start/end if it starts/ends with it or leaves the string unchanged

Also adds `lstrip` and `rstrip` that remove any of the chars from the left/right of the string.

### CODE REVIEW

**Comment by vnen** [comment]
How often do you use this to need it in core?

**Comment by nikibobi** [comment]
It is a prety standard method for string in many languages.

**Comment by damianday** [comment]
I use it a lot in c# especially when reading input from text documents, I can see it being just as beneficial for gdscript though.

**Comment by vnen** [comment]
The `trim_start/end` proposed here is not the same as C#'s `TrimStart/End` though. That's why I asked: I don't really see the behavior here in any other language. Is there any examples of that?

Instead I would prefer Python's `strip()` function, in particular `lstrip()` and `rstrip()`. Makes more sense since GDScript is often compared to Python.

**Comment by vnen** [comment]
@nikibobi I mean removing arbitrary characters, not only whitespace. Your proposal remove a fixed string and only once.

For instance:
```
"    /// Comment".lstrip([" "],["/"]) == "Comment"
```

To which I can see some usefulness (and is truly standard). While this proposal for `trim_start` would need the specific substring at the beginning, like:

```
"   /// Comment".trim_start("   /// ") == "Comment"
```

But then you need to know beforehand exactly what the prefix is, otherwise it won't do anything. That seems pointless to me, since if you know that already you can easily strip out in your script.

**Comment by mhilbrunner** [comment]
@vnen Golang has string.TrimPrefix()/string.TrimSuffix() to remove arbitrary substrings and I used it quite often in some applications. I think it would be a nice addition, even if it isn't the most important thing.

**Comment by nikibobi** [comment]
Maybe I should rename the functions to `trim_prefix` and `trim_suffix`. To not cause any confussion and to leave the `trim_start` and `trim_end` to be for trimming from a list of chars.

**Comment by nikibobi** [comment]
I renamed the functions to `trim_prefix` and `trim_suffix`. I also implemented `lstrip` and `rstrip`.
Here is a small example:
```GDScript
var s = "+-*123456"
print(s.lstrip("-*+"))
print(s.lstrip("123"))
print(s.rstrip("+-*"))
print(s.rstrip("65"))
print(s.trim_prefix("+-*"))
print(s.trim_prefix("-+*"))
print(s.trim_suffix("456"))
print(s.trim_suffix("+-*"))
```
Output:
```
123456
+-*123456
+-*123456
+-*1234
123456
+-*123456
+-*123
+-*123456
```
What do you think @vnen ?

**Comment by blurymind** [comment]
This is very useful! Thank you very much for merging it!! :)

**Pull request merged**
