### PR TITLE
Add the ability to reload the current project

### LINKED ISSUE #2773: Add a menu option to restart the editor quickly
### Describe the project you are working on
2D narrative adventure.

### Describe the problem or limitation you are having in your project
I have to frequently restart the editor, as I work with custom resources that are not automatically updated in the inspector when I modify their script.  I also need to restart every time I create a new custom class or put a new icon.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Put a quick editor restart option in the project menu.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
`Reload Project`, below last option.

Captura de pantalla 2021-05-25 a las 23 30 13

### If this enhancement will not be used often, can it be worked around with a few lines of script?
I don't know.

### Is there a reason why this should be core and not an add-on in the asset library?
I think it could be useful in a lot of cases.

### PR DESCRIPTION
**Pull request by AaronRecord**
Adds the ability to reload the current project from the project menu:

Closes https://github.com/godotengine/godot-proposals/issues/2773

Should be easily cherry-pickable

### CODE REVIEW

**Comment by Zireael07** [comment]
Export has three dots because a) it opens another window and b) you can export to various platforms.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by WarrenMarshall** [comment]
I have a problem now as my project grows where the parser will report bogus errors that won't go away until I reload the project.  This is in 4.1.1 ...

While this restart functionality does tend to fix the bogus parser errors, is there a larger ticket in play to fix the parser itself?  This feels like a (admittedly useful) band-aid over a larger problem.

**Comment by YuriSizov** [comment]
@WarrenMarshall This is completely unrelated to this PR. Please open an issue with a more detailed description and a reproduction project if you can.

**Pull request merged**
