### PR TITLE
Cast dragged file name extension to lowercase

### LINKED ISSUE #68104: Drag and drop picture editor can't recognize JPG in uppercase
### Godot version

4.0-beta3

### System information

win10

### Issue description

Drag and drop picture editor can't recognize JPG in uppercase

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by alfredbaudisch**
Fixes and closes #68104

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good. There's the same bug in `editor/plugins/node_3d_editor_plugin.cpp` which would be good to fix at the same time.

**Comment by alfredbaudisch** [comment]
> editor/plugins/node_3d_editor_plugin.cpp

Pushed. And also `editor\editor_node.cpp`.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Pull request merged**
