### PR TITLE
certs: Sync with Mozilla bundle as of Dec 13, 2023

### PR DESCRIPTION
**Pull request by akien-mga**
https://github.com/bagder/ca-bundle/commit/bef37a977ccb45fb4c1b213b79dd6ba438077561

### CODE REVIEW

**Review by Faless — APPROVED** [review]
LGTM

**Review by YuriSizov — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.
Cherry-picked for 3.5.4.

**Comment by akien-mga** [comment]
Cherry-picked for 4.1.4.

**Pull request merged**
