### PR TITLE
Move Sky and move Fog

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This PR does two things:

1) it moves our sky class into the environment subfolder
2) it moves (nearly) all logic around (Volumetric) Fog that was in RenderingSceneRenderRD into the Fog class.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good to me! You may want to update the header guards so this doesnt conflict with https://github.com/godotengine/godot/pull/63368

**Comment by akien-mga** [comment]
Needs another rebase, sorry :D

**Comment by BastiaanOlij** [comment]
> Needs another rebase, sorry :D

I was just commenting that to clayjohn, I think this is no 4 in a day:)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
