### PR TITLE
Expose editor viewports by TokisanGames

### PR DESCRIPTION
**Pull request by wayhoowang**
Rebased version of https://github.com/godotengine/godot/pull/68696

### CODE REVIEW

**Comment by AThousandShips** [comment]
Have you talked to the OP and confirmed that they have abandoned this PR? Or that they are unable to update it?

Unless a PR is marked as `salvageable` or the OP has abandoned the PR there's no reason to assume they aren't still able to and willing to complete it

Please communicate, communication is everything in a community driven project like this

**Comment by yslking** [comment]
@AThousandShips Thank you. I have left a comment on the original PR. I posted this PR in case that [TokisanGames](https://github.com/TokisanGames) is busy on something else.

**Comment by AThousandShips** [comment]
I understand, but in the future check *first*

**Comment by yslking** [comment]
There was no ceremony to my first PR. I just needed this feature and saw that the original PR wasn't active for a long time.

It should also be noted that I do not expect this PR to be merged. I'm just worried that the response cycle may be relatively long. Submitting a new PR can reduce the number of response rounds. Of course, the response cycle from the author and maintainer was very short, and there were no problems as I expected.

Thanks again for introducing me to the rules of the Godot community.

**Comment by AThousandShips** [comment]
> It should also be noted that I do not expect this PR to be merged

There's no reason to expect that it won't be merged, and there's nothing unusual about how long the PR has been open for, it varies

**Pull request closed without merging**
