### PR TITLE
Rename *_surface_override_material to *_surface_material_override

### LINKED ISSUE #70233: property name inconsistency - surface_material_override
### Godot version

v4.0.beta.custom_build [d44d0cc0f]

### System information

windows 10

### Issue description

I didn't see anything mentioned about this anywhere and maybe this should just be closed but I thought it should be brought up

MeshInstance has a property called 
`surface_material_override`
but all the functions refer to it with material and override swapped like..
`get_surface_override_material()`

a bunch of the code in mesh_instance_3d is just there to deal with the issue.

### Steps to reproduce

image

image

### Minimal reproduction project

NA

### PR DESCRIPTION
**Pull request by MarcusElg**
Fixes #70233 

Material override sounds better than override material imo, and this is also what is currently visible in the inspector.

This breaks compat however it might be worth it? 4.0 still hasn't released and it will be a while until compat can be broken again.

### CODE REVIEW

**Comment by clayjohn** [comment]
We could probably avoid breaking compatibility by renaming the editor string instead of renaming the function.

**Comment by MarcusElg** [comment]
> We could probably avoid breaking compatibility by renaming the editor string instead of renaming the function.

Would that be better? The godot 3 to 4 converter already renames these methods anyways so the only breakage would be with earlier beta versions, and they are well beta..

**Comment by akien-mga** [comment]
> We could probably avoid breaking compatibility by renaming the editor string instead of renaming the function.

The editor string derives from the generated property name, so the latter would need to be renamed, which breaks compatibility with scene files too. This breaks compatibility with scripts instead - might be easier to handle as it's a compile error instead of data loss?

That being said, if we were to rename the property instead, you could do more clever compatibility code than the current one as you could handle the old name to convert pre-beta9 scenes... but I think the rename made here is more correct language-wise ("an override for a surface material" instead of "a material for a surface override").

**Comment by MarcusElg** [comment]
> > We could probably avoid breaking compatibility by renaming the editor string instead of renaming the function.
> 
> The editor string derives from the generated property name, so the latter would need to be renamed, which breaks compatibility with scene files too. This breaks compatibility with scripts instead - might be easier to handle as it's a compile error instead of data loss?
> 
> That being said, if we were to rename the property instead, you could do more clever compatibility code than the current one as you could handle the old name to convert pre-beta9 scenes... but I think the rename made here is more correct language-wise ("an override for a surface material" instead of "a material for a surface override").

I could add a few more lines to the project converter however it isn't intuitive for people to run the godot 3 to 4 converter when converting between godot 4 betas. So should I place it somewhere else instead?

**Comment by YuriSizov** [comment]
> So should I place it somewhere else instead?

Yes, the proper way would be to add a new property with the old name which is not exposed to the inspector with the help of the PROPERTY_USAGE flags. You can do it in `_bind_methods`, just like any other property.

**Comment by akien-mga** [comment]
> > So should I place it somewhere else instead?
> 
> Yes, the proper way would be to add a new property with the old name which is not exposed to the inspector with the help of the PROPERTY_USAGE flags. You can do it in `_bind_methods`, just like any other property. You would use the same setter and getter.
> 
> You can also handle it with `_get` and `_set` (and possibly `_get_property_list`).

After discussion, we confirmed that the `_get`/`_set` approach should be preferred (see https://github.com/godotengine/godot/pull/70244 for an example).

But actually it doesn't really apply here, this is for properties. This PR changes methods, for which we don't usually provide compatibility aliases - it's easy enough to fix script errors when notified about missing/unknown methods.

**Comment by akien-mga** [comment]
We've discussed this in the production team and while we agree that this inconsistency is annoying and would be nice to fix, we're now too close to the stable release of 4.0 for such a mostly cosmetic compat breakage, which would impact a lot of users (whether we rename the property, or the methods).

So this is 5.0 material :)

**Pull request closed without merging**
