### PR TITLE
Rename Label to TextLabel

### LINKED ISSUE #1815: Rename Label to TextLabel
**Describe the project you are working on:** This applies to pretty much any project with UI.

**Describe the problem or limitation you are having in your project:**

It's not necessarily a problem or limitation, but it is something that IMO could be improved. Currently if you want to put a piece of text on the screen, you would typically use a `Label` node. This name is accurate and fine, but it's not super discoverable if you are new to UI systems and don't know what it's called, or are coming from Unity. It's also a bit inconsistent with `RichTextLabel`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The name `TextLabel` would:

* Be more consistent with `RichTextLabel` since it's still text but without the rich.

* Have improved search results when searching for "Text", which is:

  * More familiar for Unity users, in Unity it's called `TextMesh`, so this way both names contain "Text".

  * Helpful for people who haven't used Godot before or haven't used any UI system where it's called "Label".

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Renaming `Label` to `TextLabel` would solve this problem.

Branch: https://github.com/aaronfranke/godot/tree/text-label-rename

PR: https://github.com/godotengine/godot/pull/40124 (gets conflicts often, very important to rebase right before merging)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This enhancement will be used often. The workaround is to learn the name "Label".

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is about the name of a core node type, so it can't be an add-on.

### PR DESCRIPTION
**Pull request by aaronfranke**
Implements https://github.com/godotengine/godot/issues/16863#issuecomment-502517425, implements and closes https://github.com/godotengine/godot-proposals/issues/1815.

This is a huge change and probably conflicts with tons of other PRs.

### CODE REVIEW

**Comment by Malkverbena** [comment]
What exactly the reason for change the name of this node?
I mean, "Label" is totally self explanatory. A change like this will really help?

**Comment by avencherus** [comment]
> What exactly the reason for change the name of this node?
> I mean, "Label" is totally self explanatory. A change like this will really help?

For better search results.  Allows for typing text or label when filtering nodes.

**Comment by aaronfranke** [comment]
In addition to better search results:

* More consistent with `RichTextLabel` since it's still text but without the rich.

* More familiar for users of other engines (in Unity it's called `TextMesh`, so this way both names contain "Text")

**Comment by Chaosus** [comment]
I don't like it - Label is a simple explanatory term in many GUI API's, the gain of adding "Text" is very little in my opinion

**Comment by Xrayez** [comment]
I'd much prefer a general purpose `Text`/`TextBlock` node or similar, something like godotengine/godot-proposals#826 suggests, people could then make a global script to make a default `Label`/`TextLabel` implementation if we go the "barebones" Godot route, but yeah if the logic is to make it consistent with `RichTextLabel`, no big evil. 🙂

Also, how often do we actually need to use something like `ImageLabel` which would justify the rename? Those kind of stuff can be represented as texture icons I think.

> For better search results.

The poor searching might be already addressed by #39990. Perhaps the searching could also be improved to seek within method descriptions to suggest better results.

**Comment by Xrayez** [comment]
What about `LineEdit`? I find this one more difficult to find in the documentation compared to `Label` personally.

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting today, and decided to reject the proposal (and the PR). `Label` is a very common term in UI libraries and the addition of a `Text` prefix doesn't seem particularly beneficial (Qt uses `QLabel`, GTK uses `GtkLabel`).

> What about `LineEdit`? I find this one more difficult to find in the documentation compared to `Label` personally. I forget about the name and type something like `TextField` or `InputField`. smile

That's a more valid point in my opinion (also was @Faless' opinion). Godot uses `LineEdit` probably because Qt uses `QLineEdit` too, so it's also a common UI term. And it goes together with `TextEdit` which is the multiline / free form version, so `LineEdit` makes it clear that it's only a single line of text. But I'm not sure I'm convinced by any change proposal, and it doesn't seem to be a big deal to me, so I'd err on the side of the status quo personally (but if anyone feels strongly about `LineEdit`, feel free to open a proposal for further discussion).

**Pull request closed without merging**
