### PR TITLE
GDScript: Replace `assert()` with `Utils.check()` in tests

### PR DESCRIPTION
**Pull request by dalexeev**
`assert()` is not evaluated in non-debug build, so some conditions in our GDScript tests are currently not checked in non-debug builds. Please do not use `assert()` for anything other than testing the `assert()` itself. Thanks to @kleonc.

### CODE REVIEW

**Review by kleonc — APPROVED** [review]
LGTM! :+1: The changes look trivial.

The only potential concerns:
- Any reason why `const Utils = preload("../../utils.notest.gd")` was used before over `class_name Utils`?
- Any reason why `push_error` was used before over `printerr`?

**Comment by dalexeev** [comment]
> * Any reason why `const Utils = preload("../../utils.notest.gd")` was used before over `class_name Utils`?

I wasn't sure previously if `class_name` is supported in the testing system. I probably confused it with the `--test gdscript-{tokenizer,parser,compiler}` commands.

> * Any reason why `push_error` was used before over `printerr`?

`push_error()` and `push_warning()` are handled in a special. `>>` lines are added to the beginning of `.out` files. These lines are removed in non-debug builds, since GDScript warnings are not produced in non-debug builds.

There is also an issue with the fact that an active debugger is required to get the GDScript call stack. For this reason `Utils.check()` is less convenient than `assert()` when analyzing failed tests. But I have not figured out how to get around this, except to add the required parameter `message` to `Utils.check()`.

**Comment by kleonc** [comment]
> There is also an issue with the fact that an active debugger is required to get the GDScript call stack. For this reason `Utils.check()` is less convenient than `assert()` when analyzing failed tests. But I have not figured out how to get around this, except to add the required parameter `message` to `Utils.check()`.

Hmm, kinda hacky but wouldn't adding `assert(condition)` into `Utils.check` do the thing? I mean it shouldn't print on its own anyway when everything is fine, and if the condition fails it would output the stack trace in the debug builds for easy finding the failing line, no? :thinking:

**Comment by dalexeev** [comment]
> wouldn't adding `assert(condition)` into `Utils.check` do the thing?

No, `assert()` in `Utils.check()` will only point to its location in `utils.notest.gd`, backtrace will not be available even in debug builds, it requires an active debugger. But if #91006 is merged, we will be able to improve `Utils.check()`, as in the current implementation the PR [removes](https://github.com/godotengine/godot/pull/91006/files#diff-3ea6a9ac995f49c433a039e5f1918b00127ce445df983647cbdd9625acd05a5aL3562-R3561) the requirement for an active debugger.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
