### PR TITLE
Add <Select All>(Ctrl+A) shortcut to LineEdit. Fixes #1094

### LINKED ISSUE #1094: CTRL+A doesn't "highlight all" when typing in a text field
For example, if I'm creating a new script for a current node, a dialog pops up where I need to type out various path names and such. If I make a mistake, I typically use CTRL+A to highlight all of the text so I can start over. In Godot, however, the CTRL+A shortcut doesn't have any kind of text-highlighting functionality. Instead, it's bound to "Add New Node" and causes the new node dialog to show up.

### PR DESCRIPTION
**Pull request by MarianoGnu**
Fixes #1094

### CODE REVIEW

**Comment by akien-mga** [comment]
Works great :)

**Comment by MarianoGnu** [comment]
fixed tab indentation

**Comment by akien-mga** [comment]
> fixed tab indentation

Thanks. Good to merge as far as I'm concerned.

**Comment by jackmakesthings** [comment]
:+1:

**Pull request merged**
