### PR TITLE
Rename theme properties to include underscores between words

### PR DESCRIPTION
**Pull request by fire-forge**
See https://github.com/godotengine/godot/issues/54161#issuecomment-1086010102

Renames several theme properties to include an underscore between words and changes "ofs" to "offset" in a few other theme properties.

| Before | After |
---|---
| check_vadjust | check_v_adjust |
| close_h_ofs | close_h_offset |
| close_v_ofs | close_v_offset |
| commentfocus | comment_focus |
| hseparation | h_separation |
| ofs | offset |
| selectedframe | selected_frame |
| state_machine_selectedframe | state_machine_selected_frame |
| table_hseparation | table_h_separation |
| table_vseparation | table_v_separation |
| vseparation | v_separation |

### CODE REVIEW

**Review by KoBeWi — APPROVED** [review]
Looks good, but we could also consider expanding h/v to horizontal/vertical, as we already did with a few names. The lone h/v look weird with the underscores.

**Comment by fire-forge** [comment]
@KoBeWi Thanks!

> we could also consider expanding h/v to horizontal/vertical, as we already did with a few names. The lone h/v look weird with the underscores.

I agree. This could use a proposal for more discussion. There are also several properties and functions that use h/v instead of horizontal/vertical, so maybe they should all be changed in another PR.

**Comment by fire** [comment]
The feature look great. Wasn't able to review the technical details. Like the design of separating the words.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
