### PR TITLE
[Net] Move multiplayer classes to own subfolder. Split RPC from MultiplayerAPI.

### PR DESCRIPTION
**Pull request by Faless**
In this PR, another attempt at decoupling the MultiplayerAPI and Script (different approach from #52188):
- Move the multiplayer classes to `core/multiplayer` subdir.
- Move the `RPCConfig` and enums (`TransferMode`, `RPCMode`) to a separate file, and bind it to the global namespace (as suggested by @reduz ).
- Split the RPC part to its own class (not exposed to scripting yet).
- Also renames `rpc_sender_id` to `remote_sender_id` (I would like this to be usable in the various submodules, e.g. the replicator instead of relying on parameters).

Does not include the packetpeer binding in #52188 (I would rather do that in a separate PR).

Note: ~This PR is left unsquashed in case it helps reviewers, but **should be squashed before merging**~. Now squashed.

### CODE REVIEW

**Comment by fire** [comment]
@Gallilus Can you double check Visual Script changes too?

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
Looks all great to me!

**Review by mhilbrunner — APPROVED** [review]
Looks good and seems a lot cleaner. :)

**Comment by mhilbrunner** [comment]
DId a more in-depth review, found nothing in the code, tests run fine with this, as do my multiplayer test projects.

**Comment by mhilbrunner** [comment]
Thanks!

**Pull request merged**
