### PR TITLE
Use `static const int` instead of `#define` for OpenSimplexNoise octaves

### LINKED ISSUE #44860: OpenSimplexNoise should not define its MAX_OCTAVES using a macro
**Godot version:**
Godot 3.2.x
Godot 4.0

**OS/device including version:**
All

**Issue description:**
This:
https://github.com/godotengine/godot/blob/a6b869988f4427fe2eb746f3f3776697258f3dd5/modules/opensimplex/open_simplex_noise.h#L43
Defines a global macro occupying the sequence of characters `MAX_OCTAVES`.
My module defines a constant of the same name in one of its classes, and it can't compile because it gets turned into a `9`.

-------

More generally, please *never* add macros like this in headers.
Prefer using `static const` inside the relevant class, or use a prefix.

### PR DESCRIPTION
**Pull request by Calinou**
This closes #44860.

### CODE REVIEW

**Comment by Calinou** [comment]
@Zylann Note that this may not be enough, should I "namespace" the variable by adding a prefix to it?

**Comment by Zylann** [comment]
I think you should just put it inside the class

**Comment by Calinou** [comment]
> I think you should just put it inside the class

Done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
