### PR TITLE
Update Camera2D scroll using NOTIFICATION_INTERNAL_PROCESS

### PR DESCRIPTION
**Pull request by ghost**
See https://github.com/godotengine/godot/issues/15044

Currently `Camera2D` updates its position using `NOTIFICATION_PHYSICS_PROCESS`. The problem with this is that the physics process does not run in every `Main::iteration()` (only if the accumulated time reaches a certain limit), whereas the idle processes (e.g. `_process` in scripts) run in every iteration. This can lead to an idle process running twice and changing position, without the camera updating (which results in random visual jerkiness).

This does not happen if the object tracked by `Camera2D` gets updated by a physics body (since that update again only happens in `NOTIFICATION_PHYSICS_PROCESS `), but if it's updated manually, there will be random losses of sync.

I suggest changing the update to `NOTIFICATION_INTERNAL_PROCESS`, which is the idle process that runs in every iteration that thus guarantees sync with any changes. Also, it always runs once after the physics process so it will pick up any changes produced by physics bodies.

### CODE REVIEW

**Comment by akien-mga** [comment]
It makes sense to me, I'd just like to have a quick check from @reduz too.

**Review by bojidar-bg — COMMENTED** [review]
You should change references to `set_physics_process` and `is_physics_processing`. Note that physics process was used only for smoothing, and transform changed is used otherwise.

**Comment by akien-mga** [comment]
> You should change references to set_physics_process and is_physics_processing. Note that physics process was used only for smoothing, and transform changed is used otherwise.

Indeed. And smoothing uses `get_physics_process_delta_time()`, it should probably be changed to `get_process_delta_time()` (or is there a delta time exposed for internal process?).

**Comment by bojidar-bg** [comment]
Well, internal process and process use the same delta time. Internal process is there just so scripts can't break things by calling, e.g. `set_process(false)`

**Comment by akien-mga** [comment]
Ping.

**Comment by poke1024** [comment]
This is now a minimal change that changes `physics` to `internal_process`.

Issues of #15044 are gone.

Smooth scrolling still works:

scroll

**Comment by poke1024** [comment]
...and clang has an `apt-get` problem...

**Comment by girng** [comment]
most underrated changes i've seen. this should help with a lot of jittering people are experiencing. thank you to @poke1024 for your continued efforts in this repo, light shines boldly on you, sir.

**Comment by poke1024** [comment]
@girng Thank you.

**Comment by Norrox** [comment]
#17823

**Pull request merged**
