### PR TITLE
Add option to enable autowrapping for label inside 'AcceptDialog'

### PR DESCRIPTION
**Pull request by YeldhamDev**

### CODE REVIEW

**Comment by volzhs** [comment]
would you describe in detail why this change is needed?
it looks breaking something.

**Comment by YeldhamDev** [comment]
@volzhs Having autowrapped dialogs in good when dealing with translated strings, as you don't have to manually manage breaking up lines. Otherwise you will need to give it another `Label` with autowrap enabled.

This was originally disabled by @reduz in [this commit](c5f509f238576dba39ffcce74ab2066f24e67b58), and I have no idea why, as I don't see any reason for them to not be autowrapped.

**Comment by reduz** [comment]
Autowrapping is pretty broken imo, I would not do this unless we have a proper height4width implementation.

**Comment by YeldhamDev** [comment]
@reduz How about making it an option then?

**Comment by volzhs** [comment]
what option did you mean?
it seems workaround a bug temporally.

**Comment by YeldhamDev** [comment]
@volzhs Of enabling autowrapping for labels inside dialogs.

**Comment by YeldhamDev** [comment]
Modified the commit so it adds a option to enable autowrapping.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
