### PR TITLE
Unit Tests for all Primitive Meshes.

### PR DESCRIPTION
**Pull request by jbcolli2**
Unit tests for all PrimitiveMesh derived classes from issue #43440:

- CapsuleMesh
- BoxMesh
- CylinderMesh
- PlaneMesh
- QuadMesh
- PrismMesh
- SphereMesh
- TorusMesh
- TubeTrailMesh
- RibbonTrailMesh
- TextMesh

---

Tests are broken into two types.
1. Initialization and setter/getter testing
2. Testing that the mesh is created correctly.  Mostly just testing that the position and normals are correct.  I tried to keep it general in case the implementation of the mesh changed, the tests would still work as long as the basic geometric shape stayed the same, i.e. a box has 6 and only 6 distinct normals.

Some objects do not give access to the mesh, so their mesh is not tested for correctness.

---

### Note!!!

For the CylinderMesh, when the top and bottom radii are different (which is allowed by the constructor), the normals are not calculated correctly.  They are calculated as if the top and bottom radii are the same.  A test for this exists and currently fails in this PR.

Edit: This error has been corrected with PR #67336.

### CODE REVIEW

**Comment by Calinou** [comment]
> For the CylinderMesh, when the top and bottom radii are different (which is allowed by the constructor), the normals are not calculated correctly. They are calculated as if the top and bottom radii are the same. A test for this exists and currently fails in this PR.

That's interesting to know – I never noticed it before :slightly_smiling_face: 

Feel free to open a separate PR to fix this.

**Comment by Calinou** [comment]
>  What order should things happen in? Should I fix the CylinderMesh code so that all the tests of this PR pass, or can this PR still be merged even with a failing test?

I think we should try to get the fix PR merged first, then you can rebase this test PR to make all tests pass.

**Comment by jbcolli2** [comment]
The error in the `CylinderMesh` was corrected with PR #67336.  All tests in this PR should now pass.

**Review by akien-mga — APPROVED** [review]
Looks pretty good! Thanks a lot :)

**Pull request merged**
