### PR TITLE
Force update AnimationTree player cache when AnimationPlayer changes.

### PR DESCRIPTION
**Pull request by SaracenOne**
Updates the cache if the AnimationTree node's AnimationPlayer changes to another, which should address a bug of the AnimationTree not playing animations.

May fix this issue, but not sure
#53357

### CODE REVIEW

**Comment by TokageItLab** [comment]
@SaracenOne Shouldn't this be added at the end of `AnimationTree::set_animation_player()`?

**Comment by SaracenOne** [comment]
Yeah, let me look at this again later today.

**Comment by SaracenOne** [comment]
Okay, I've moved the cache invalidation flag to the _setup_animation_player method.

**Review by TokageItLab — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
