### PR TITLE
Fix AnimationTree state machine start()

### LINKED ISSUE #41475: AnimationPlayerStateMachinePlayback: start() does not work when current_node is ""
**Godot version:**
Godot 3.2.2 Standard

**OS/device including version:**
Windows 10 Pro, Version 1909, OS build 18363.1016

**Issue description:**
when an AnimationPlayerStateMachinePlayback has no node selected, start() function has no effect but travel() does.
start() should make current_node the specified node after an AnimationPlayerStateMachine process step regardless of the state of current_node

**Steps to reproduce:**
Given an AnimationTree with 2 connected Animations: Idle(start animation) and move:
in AnimationTree.Ready():
    get("parameters/playback").start("Move")

**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/5114537/Bug.zip)

### PR DESCRIPTION
**Pull request by rafallus**
Fixes #41475

### CODE REVIEW

**Comment by rafallus** [comment]
Another side effect of this PR is that the state of the State Machine is preserved even when it becomes inactive. Meaning on "restart" the initial state is not played (as the hint in the "Toggle autoplay..." button suggests). I think this behavior is more convenient, at least I wouldn't expect the State Machine to restart each time it becomes active. Please let me know what your thoughts are about this so I can make changes accordingly.

**Comment by fire** [comment]
@TokageItLab Can you review this?

**Comment by TokageItLab** [comment]
@fire Since I am not very familiar with StateMachine, I believe that @SaracenOne can provide a more appropriate review.

**Comment by SaracenOne** [comment]
While the bug described in the linked issue still appears to be present, in what I assume is due to internal changes with how 'start' works in AnimationTrees now, this fix no-longer works in the 4.x branch (it may still be salvagable for fixing it in 3.x though). I will close this for now, but hope an updated fix can be found for this issue since I believe it severely limits the ability to serialize AnimationTrees for savegames.

**Comment by SaracenOne** [comment]
Mistake on my behalf, a recent update in the build system caused my to accidentally test this with the wrong binary; I'm re-reviewing it now.

**Review by SaracenOne — APPROVED** [review]
Tested and seems good!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
