### PR TITLE
[Core] [Mono] Fix Color missing int export methods, added 64-bit

### PR DESCRIPTION
**Pull request by aaronfranke**
EDIT: [Another PR](https://github.com/godotengine/godot/pull/18975) has modified this file. Post edited to reflect changes after merging that.

EDIT 2: Added `Math.Round` in the methods as per https://github.com/godotengine/godot/pull/19654 and https://github.com/godotengine/godot/issues/19652. I used System.Math instead of Godot's Mathf to avoid double casting (Mathf casts to `real_t`, Math works with `double` only, better to go "`double` to `byte`" than "`double` to `real_t` to `byte`")

Without this fix, the only method available ~~are Argb but the constructors expect Rgba~~ is ToRgba32. The C++ files for Godot can export either Rgba, Argb, or Abgr to `int`. This PR adds these to C#, ~~and makes Rgba the default for `To32()` and `To64()` as this is what the constructors expect.~~ CC @neikeq 

Without this fix, the following code ~~produces incorrect results~~ does not compile:

    Color c = new Color(0.4f, 0.5f, 0.6f, 0.7f);
    int colorint = c.ToAbgr32();

I also added 64-bit `long` methods, for high-precision color math & high-color displays, to C++ as well.

### CODE REVIEW

**Comment by KellyThomas** [comment]
Should `To32()` and `To64()`  have internal calls `ToRgba32()` and `ToRgba64()` respectively.

It would help make it easier for a reader to know what they output without having to follow the bit twiddling.

**Comment by aaronfranke** [comment]
@KellyThomas That's a good idea, I've went ahead and made that change in a fixup.

**Comment by aaronfranke** [comment]
@neikeq You mentioned that you "missed th[is] one...", so here's a reminder so that you don't miss it.

**Review by neikeq — APPROVED** [review]
Changes look good to me.
I would prefer to get rid of to32 and to64 though. The naming is not intuitive IMO.

**Comment by aaronfranke** [comment]
Any alternative name suggestions? The main thing that I like about those methods is that they help programmers who aren't sure whether the standard format is Rgba, Argb, or Abgr.

**Comment by neikeq** [comment]
I just don't think it's a good idea to hide this from the programmer. I consider it better to explicitly specify the desired format.

**Comment by akien-mga** [comment]
It's not clear to me what's the use case for those additions. The added `Color` methods in core are not exposed to the scripting API, so they can only be used from C++ (so nothing uses them currently).

I also think `to_32` and `to_64` should not be added, they're confusing when we support 3 kinds of 32-bit and 64-bit conversions. Let users use the explicit ones.

**Comment by aaronfranke** [comment]
Alright, so:

* I removed `to_32` and `to_64` from both C++ and C#.

* I exposed the new methods to GDScript and updated the doc.

* Interestingly, the existing `to_abgr32` method wasn't exposed before, and the existing docs for the methods were very wrong. Both of them already referenced a non-existent `to_32()`. Both of these issues have been fixed.

**Review by neikeq — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by vnen** [comment]
> However I'm not completely sure if `<return type="int">` is the correct doc for 64-bit ints?

I don't think there's any problem. There's no distinct types in GDScript, and Variant stores 64-bit ints anyway.

**Comment by akien-mga** [comment]
Thanks!

**Comment by neikeq** [comment]
@aaronfranke That file is automatically generated from `Color.xml`.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.

**Pull request merged**
