### PR TITLE
Fixed false positives in the culling system.

### PR DESCRIPTION
**Pull request by ExpiredPopsicle**
This fixes numerous false positives coming out of the culling system.

AABB checks are now a full separating-axis check against the frustum, with the points of the frustum being compared to the planes of the box just as the points of the box were being compared to the planes of the frustum. This fixes large objects behind the camera not being culled correctly.

A new class, ConvexShape, was added to provide a full set of planes+points for arbitrary convex meshes, and also because passing around only planes was no longer sufficient for culling operations. This class will calculate intersection points for planes and store them.

A lot of the culling interface has been given a ConvexShape version to use instead of taking an array of planes. The remaining functions in the old interface now create a ConvexShape internally based on the planes given.

Some systems that used frustums that were (sometimes mistakenly?) unbounded on one or more side have been modified to be fully enclosed. This change fixed unbounded culling by the omni light dual paraboloid shadowmap culling.

I've uploaded some repro cases here:
https://nc2.expiredpopsicle.com/s/9k9SyJYr2SMSM3W

The "CullingBug.tscn" scene demonstrates false positives in the culling system for large objects behind a camera. With the camera preview active for the camera in the scene (and an appropriately sized window), the object behind it is not visible, but it will show up as un-culled in the results of https://github.com/godotengine/godot/blob/c2f0d58/servers/rendering/rendering_server_scene.cpp#L2019 (if some logging is added).

The "DualParaboloidRegressionTest2.tscn" scene demonstrates false positives by the dual paraboloid shadowmap culling, causing it to mistakenly account for a large row of objects that are far outside of its range. This can be demonstrated with the high number of objects output from this culling call: https://github.com/godotengine/godot/blob/c2f0d58/servers/rendering/rendering_server_scene.cpp#L1742 .

### CODE REVIEW

**Comment by ExpiredPopsicle** [comment]
One of the Travis CI builds seems to keep stalling with this change. It's happened at different points in the build now. I'm not sure what's going on with that, but I can't tell if it's actually a result of my code or just a builder issue.

**Comment by clayjohn** [comment]
I ran the test project and I wasn't able to reproduce your false positives. When running the scenes, the culled number of objects seemed appropriate. Keep in mind, while running in the editor, gizmos account for a large number of objects that are culled. Most telling is "CullingBug.tscn" which reports no objects rendered.

Is there anything else I should do to reproduce the issue you have discovered?

**Comment by ExpiredPopsicle** [comment]
Hi. I'm sorry, due to the complexity of reproducing the bug, I don't think I explained it well, so I went ahead and created a video showing the process instead. I hope this helps!

In the video I don't actually use the camera I placed in the scene, but just demonstrate it with the editor camera.

I have reproduced it outside of the editor, too.

I've uploaded it to youtube right here:
https://www.youtube.com/watch?v=tBSDkXNoPeQ

I can make a video of the dual paraboloid shadow map culling issue, too, if needed.

**Comment by clayjohn** [comment]
Thanks for the helpful video. It did indeed help illustrate the problem. Trying the example scene again I was able to reproduce the problem by running the scene with the camera at the right angle. 

I am going to push back on adding an entire new class to solve this bug. I think it is unnecessary to add an entire class to do something that is already being done. Please see [Best Practices for Engine Contributors #7](http://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local) "All solutions must be local". What this means, is that when a bug arises in a certain piece of code, we prefer to fix it by fixing that piece of code, instead of designing a new complex system to replace it. In this case, you are replacing the culling planes with a new class which internally is not much different than an array of planes. In fact, your code ends up casting from our current array of planes into your custom class. This adds complexity and overhead into a part of the engine that needs to be as fast as possible for little to no benefit. 

For this to be accepted, you will need to trim it down to the bare essentials needed to fix the bug. Which from my reading of the code, could very likely be just within ``AABB::intersects_convex_shape``, even then, I am skeptical that so much code is needed. Keep in mind this function needs to run for every object, every frame. So even a small loop (or in the case two) can add significant overhead.

**Comment by ExpiredPopsicle** [comment]
Here's a video explaining the dual daraboloid shadow map bug, but the video is still processing as I write this. https://youtu.be/6xxeK2EwfHw

**Comment by ExpiredPopsicle** [comment]
> Thanks for the helpful video. It did indeed help illustrate the problem. Trying the example scene again I was able to reproduce the problem by running the scene with the camera at the right angle.
> 
> I am going to push back on adding an entire new class to solve this bug. I think it is unnecessary to add an entire class to do something that is already being done. Please see [Best Practices for Engine Contributors #7](http://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local) "All solutions must be local". What this means, is that when a bug arises in a certain piece of code, we prefer to fix it by fixing that piece of code, instead of designing a new complex system to replace it. In this case, you are replacing the culling planes with a new class which internally is not much different than an array of planes. In fact, your code ends up casting from our current array of planes into your custom class. This adds complexity and overhead into a part of the engine that needs to be as fast as possible for little to no benefit.
> 
> For this to be accepted, you will need to trim it down to the bare essentials needed to fix the bug. Which from my reading of the code, could very likely be just within `AABB::intersects_convex_shape`, even then, I am skeptical that so much code is needed. Keep in mind this function needs to run for every object, every frame. So even a small loop (or in the case two) can add significant overhead.

I initially wanted to do the changes locally within AABB::intersects_convex_shape, but - as you pointed out - this function needs to run for every object, every frame, meaning that redundantly recalculating the convex shape's intersection points could be potentially very expensive.

The important part of the new ConvexShape class is that it lets that calculation occur once, and then carry through for the entire tree cull_convex of calls, saving redundant recalculation for every octree octant recursion and object AABB test. I'm afraid that the performance overhead of making the changes local to AABB::intersects_convex_shape could be worse than the effect of the bug that's being fixed.

I could also move the point calculation into an individual function rather than a class and then carry that data through all the convex tests as additional function arguments, if that would be better.

**Comment by ExpiredPopsicle** [comment]
The branch has been moved back to 3.2, and the ConvexShape class has been removed, as @clayjohn recommended.

**Comment by akien-mga** [comment]
Reviewed on IRC, should be good to merge once squashed (into one or two commits, depending on whether the dual paraboloid shadow map culling fix would be better as its standalone commit for readability). A matching PR should be made for `master` too.

**Comment by ExpiredPopsicle** [comment]
Squashed it down to two commits. One for the dual-paraboloid fix, and one for everything else.

This one is ready to go, and I'm going to port it over to master branch as a separate PR.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
