### PR TITLE
[TextServer] Cleanup text server interlocking.

### PR DESCRIPTION
**Pull request by bruvzg**
- Removes global text server locks in favor of locking individual internal objects.
- Makes some text server internal objects ref. counted.

### CODE REVIEW

**Comment by akien-mga** [comment]
> Fixes GDExtenaion text server build after recent changes (some argument type inconsistencies).

Feel free to extract this to a separate PR for 4.0 (not critical but shouldn't hurt to have it compile properly).

**Comment by bruvzg** [comment]
> Feel free to extract this to a separate PR for 4.0 (not critical but shouldn't hurt to have it compile properly).

Done - https://github.com/godotengine/godot/pull/73990

**Comment by myaaaaaaaaa** [comment]
FYI, ThreadSanitizer in CI has been merged. Warnings for `TextServer` are currently being suppressed since it has some potential deadlock issues, but they can be re-enabled if this PR fixes them.

See [`misc/error_suppressions/tsan.txt`](https://github.com/godotengine/godot/blob/master/misc/error_suppressions/tsan.txt) for the suppression list.

**Comment by bruvzg** [comment]
Superseded by https://github.com/godotengine/godot/pull/88241

**Pull request closed without merging**
