### PR TITLE
Add missing shader built-in overloads

### PR DESCRIPTION
**Pull request by Chaosus**

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
I dont think all of the overloads you added are supported. 

Here is what the spec has to say:

> When the built-in functions are specified below, where the input arguments (and corresponding output) can be float, vec2, vec3, or vec4, genType is used as the argument. Where the input arguments (and corresponding output) can be int, ivec2, ivec3, or ivec4, genIType is used as the argument. Where the input arguments (and corresponding output) can be uint, uvec2, uvec3, or uvec4, genUType is used as the argument. Where the input arguments (or corresponding output) can be bool, bvec2, bvec3, or bvec4, genBType is used as the argument. For any specific use of a function, the actual types substituted for genType, genIType, genUType, or genBType have to have the same number of components for all arguments and for the return type. Similarly for mat, which can be any matrix basic type.
(pg 80 https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.3.30.pdf)

``step()`` for example has two overloads:

> genType step (genType edge, genType x)
genType step (float edge, genType x)

So I don't think that the overloads added are valid.

**Comment by Chaosus** [comment]
@clayjohn  Strange, they are working when testing with SHADERed and the Godot itself, this seems like a non-standard extension then? Ok, I would clean up this PR then, and add some missing stuff like texture functions with Offset which GLES3 is supported.

**Comment by Chaosus** [comment]
I see, then I will remove that conversion overload stuff and for the future, I should probably implement that conversion implicitly.

**Comment by Chaosus** [comment]
Added packing/unpacking functions (supersedes https://github.com/godotengine/godot/pull/52767) and added functions described in https://www.khronos.org/registry/OpenGL/specs/es/3.1/GLSL_ES_Specification_3.10.withchanges.pdf (bitfieldExtract, bitfieldInsert, bitfieldReverse, bitCount, findLSB, findMSB, uaddCarry, usubBorrow)

**Review by clayjohn — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
