### PR TITLE
Renamed fixed_process to physics_process

### PR DESCRIPTION
**Pull request by AndreaCatania**
The method "_fixed_process" does not describe correctly its behaviour. It's executed right before each physics step so this name "_physics_process" is more accurate.

### CODE REVIEW

**Comment by Zireael07** [comment]
While the name might be better, I'm on the fence about the change itself - the 3.0 exporter won't be able to handle this (yet) and this is a function that is surely used A TON across people's projects.

**Comment by groud** [comment]
> While the name might be better, I'm on the fence about the change itself - the 3.0 exporter won't be able to handle this (yet) and this is a function that is surely used A TON across people's projects.

Well I guess in any case scripts won't be made compatible from 2.0 to 3.0, as the API widely changed. So I guess it's not that important as user will have to go through all scripts anyway.

**Comment by Zireael07** [comment]
> as user will have to go through all scripts anyway.

I've been exporting my car game (what is in the repo) to 3.0 as a test and it's definitely not a case of ALL scripts currently, while the change would require people to go through ALL scripts indeed.

**Comment by groud** [comment]
Anyway that's the time to make that kind of changes, this has been discussed in IRC, and the new naming was said to be more explicit.

**Comment by Zireael07** [comment]
That's a good point @groud, if the change is to be made, now is the time.

**Comment by toger5** [comment]
fixed process made no sense. So I'm happy for the change.
what happened to the idea of:
`_prephysics_process` 
was it just to long? and better to explain the `pre` part in the docs?
I also liked it. But I guess sine you renamed there was a good intention behind it.
Just curious.

**Comment by groud** [comment]
> what happened to the idea of: _prephysics_process

The point to is that Godot tries to keep its function name as simple as possible to the user. As @reduz said, Godot is not Unreal. ;p

Thus, as we don't have a postphysics_process, the 'pre' is not bringing anymore information to the user. `physics_process` is good: you now it's for physics stuff, an that's all you actually need to know :)

**Comment by Noshyaar** [comment]
What about `ANIMATION_PROCESS_FIXED`?

**Comment by AndreaCatania** [comment]
@Noshyaar You are right, I miss that. Let me fix it

**Comment by AndreaCatania** [comment]
@Noshyaar  I did it

**Comment by Noshyaar** [comment]
I just notice `TIMER_PROCESS_FIXED`. Could you also check other enums as I might've missed some.

**Comment by AndreaCatania** [comment]
@Noshyaar I've checked all enums and all functions again and I've found others word "fixed" not changed. Now all should be changed.

**Comment by davarrcal** [comment]
Not agreed with new denomination.  Fixed is more descriptive word, physics_process seems like work directly on physics. Maybe _fixed_to_physics_process. There will be confusions in constants or other parts of the engine with using the word physics to refer the fixed_process. Fixed is too more common denomination in other engines (Fixedupdate()) Anyway my opinion is that the word fixed there will be present in the function and asociated methods/constants.

**Comment by AndreaCatania** [comment]
@davarrcal Indeed physics is the main reason for this method.

Initially I called this method pre physics process to mark the fact that this is executed before the physics step and must be used for physics purpose or for all processes that must occure before each physics step. But at the end we decided to drop the word "pre" that give too information since the fact that remain is that this callback exist for the most part for physics management purpose.

**Comment by davarrcal** [comment]
What I mean is that this name seems to work directly in Physics Server, to processing things from that, no for execute code fixed with physics frames. If later will be a costant or method that need a difference from processing from fixed_processing, call that "physics" could not help to the constant or method denomination(Ex: do_fun_thing_in_this_method(Vector2 InitialPosition, const processing.... and in the constant you have: PROCESSING_PROCESS= 0 PROCESSING_PHYSICS= 1... probably bad example, but I think that the idea is understood) . I like more _fixed_to_physics_process and i think that the word "fixed" is very descriptive, in this _fixed_process callback and in properties and methods of the entire API. But is my opinion, i don´t want to boycott your work, I'm just talking about the first impression that gave me the name change, but I am in the minority by the above comments.

One question.... The word "fixed" in the context of this conversation is going to be changed throughout the entire code (All properties, constants and methods)?,

**Comment by AndreaCatania** [comment]
I think that the problem that you are telling is due to the name "fixed" because this name give you the "wrong" idea that this function was created for all things that must have a fixed delta time.
As I said the main reason why this function exists is to controll physics behaviours, and not to process something other (that it still valid and there isn't any problems to do that, but this is not its main objective of this callback).

>  I like more _fixed_to_physics_process and i think that the word "fixed" is very descriptive, in this _fixed_process callback and in properties and methods of the entire API

This function has fixed delta time but it's not its main objective so this is not descriptive and could be mislead (like in this case).

> But is my opinion, i don´t want to boycott your work, I'm just talking about the first impression that gave me the name change, but I am in the minority by the above comments.

This is your opinion, and say our opinions it's very important, and talk about something to improve it is always a good thing. However we are talking I'm not feel boycotted :D

> One question.... The word "fixed" in the context of this conversation is going to be changed throughout the entire code (All properties, constants and methods)?,

Yes

**Pull request merged**
