### PR TITLE
Add Godot iOS Plugin System

### PR DESCRIPTION
**Pull request by cagdasc**
Mobile developers need to be 3rd-party libraries for improve their apps. Some of them are ads libraries, Facebook integration, game services etc. With this integration Android and iOS apps can be same.

At Godot, we can only create plugin for Android after 3.2.x, now with this proposal we can create plugin for iPhone and our games will run same features.

This is a draft PR. I will add signal feature.

Related with this [proposal](https://github.com/godotengine/godot-proposals/issues/1364)

### CODE REVIEW

**Comment by cagdasc** [comment]
@akien-mga @m4gr3d can you review?

**Comment by naithar** [comment]
Running `clang-format -i <source-file>` should help you fix source formatting issues :)

**Comment by cagdasc** [comment]
@naithar yes I will do it with last commit.

**Comment by jkb0o** [comment]
Actually, I do not see any problem to implement any third-party integrations using gdnative c++ API. It is possible since https://github.com/godotengine/godot-cpp/pull/353. I've already use Appsflyer, Facebook, Firebase, Onesignal, Zendesk.

**Comment by naithar** [comment]
> Looks like a solid piece of work, but... Actually, I do not see any problem to implement any third-party integrations using gdnative c++ API. It is possible since [godotengine/godot-cpp#353](https://github.com/godotengine/godot-cpp/pull/353). I've already use Appsflyer, Facebook, Firebase, Onesignal, Zendesk. Is this really needed?
> 
> Andoid modules look like a legacy as well, so `we have android modules` is not best argumentation.

Well, GDNative doesn't give access to `AppDelegate` or any other platform specific code for iOS. Plugins should solve this (the other plugin system PR solved it by being actually modules that could be built separately from engine itself).

**Comment by jkb0o** [comment]
> Well, GDNative doesn't give access to AppDelegate or any other platform specific code for iOS. Plugins should solve this (the other plugin system PR solved it by being actually modules that could be built separately from engine).

Addons can use [Method Swizzling](https://spin.atomicobject.com/2014/12/30/method-swizzling-objective-c/) to overwrite AppDelegate methods. When you write a plugin using ObjectiveCPP there is no single point in iOS you couldn't access (I didn't meet any developing those addons).

**Comment by naithar** [comment]
> When you write a plugin using ObjectiveCPP there is no single point in iOS you couldn't access (I didn't meet any developing those addons). 

This https://github.com/godotengine/godot/pull/41230 allows plugin to directly use Godot's iOS platform code.
Method Swizzling is not really a good option and shouldn't be used lightly.

**Comment by cagdasc** [comment]
I have added custom variable types for type check and tomorrow I will add `MethodInfo` like `SignalInfo` for type safety.

**Comment by cagdasc** [comment]
End of the development.

**Comment by paytonrules** [comment]
Why was this abruptly closed? It doesn't seem like the issue was settled, and this functionality would be useful for 3.2 users?

**Comment by akien-mga** [comment]
It's superseded by #41230 and #41340.

**Pull request closed without merging**
