### PR TITLE
Correct PackedInt64Array comparison in description

### PR DESCRIPTION
**Pull request by mechalynx**
All Packed classes that have the same paragraph will compare the currently viewed Packed array type with the equivalent typed Array but here the comparison was with the Int32 version instead of the Int64 version.

PackedArrays that have a type not represented directly in base types do not have this paragraph but at least mention that if one wants the 64bit equivalent, they should look into the appropriate PackedArray.

### CODE REVIEW

**Review by tetrapod00 — APPROVED** [review]
This change makes sense - as noted, for the most part each `Packed*Array` with a corresponding GDScript type has this note about differences, which directly compares the `Packed*Array` with the equivalent typed array.

---

It does seem that `PackedVector4Array` is missing such a note. I believe `PackedVector4Array` is missing the note because the PR adding the `PackedVector4Array` type (https://github.com/godotengine/godot/pull/85474) was added after the PR adding these notes (https://github.com/godotengine/godot/pull/78257). I'm not entirely sure why only some `Packed*Array` types were documented in 78257 and some like `PackedInt32Array` were left out.

I should also point out that these kind of subtly different copy-pasted notes are inherently a little problematic (there was already one followup copy-paste typo correction PR made: https://github.com/godotengine/godot/pull/97835). But that's a larger problem and not specific to these notes.

**Comment by tetrapod00** [comment]
Personally, I don't think that *this PR* needs to do anything more than the two changes you've done here, since now there is a consistent rule that `Packed*Array` types with an exact corresponding GDScript type have this note, and the others do not.

@Mickeon is a lot more familiar with the standards for the class reference, so they will have some insight if they see this PR.

**Comment by Mickeon** [comment]
The PR is completely fine as is. Do not change it, it's okay for now.

These... admittedly huge notes were added by @Calinou to mitigate confusion as much as possible. I personally loathe these kind of notes for many reasons. Hard to maintain, irritating to localize, exhausting to read, prone to become inconsistent.
There are ideas thrown around to implement "macros" of some kind, which would copy and paste repetitive information wherever it is desired. Nothing much discussed about it though.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Pull request merged**
