### PR TITLE
Remove GodotPayment android plugin (3.2)

### PR DESCRIPTION
**Pull request by timoschwarzer**
This is now available in a separate repository
at https://github.com/godotengine/godot-google-play-billing

### CODE REVIEW

**Comment by akien-mga** [comment]
Seems like you missed some of it:
```
platform/android/export/export.cpp: In member function 'virtual bool EditorExportPlatformAndroid::can_export(const Ref<EditorExportPreset>&, String&, bool&) const':
platform/android/export/export.cpp:1918:60: error: 'GODOT_PAYMENT' was not declared in this scope
 1918 |    bool godot_payment_enabled = p_preset->get("plugins/" + GODOT_PAYMENT.name);
      |
```

**Comment by timoschwarzer** [comment]
@akien-mga oops, yeah I only checked `p=android tools=no` :sweat_smile:

**Comment by timoschwarzer** [comment]
@akien-mga fixed.

**Comment by akien-mga** [comment]
Thanks!

One last thing needed for 3.2.2-stable: the IAP demo should be updated again.
https://github.com/godotengine/godot-demo-projects/tree/master/misc/android_iap

**Comment by timoschwarzer** [comment]
@akien-mga I already made a PR for that 2 days ago :)

**Comment by timoschwarzer** [comment]
https://github.com/godotengine/godot-demo-projects/pull/482

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
