### PR TITLE
Fix button click detection when `Tree` is rotated

### LINKED ISSUE #99954: `TreeItem` Button willl not press on a scaled `Tree`
### Tested versions

v4.3.stable.mono.official [77dcf97d8]

### System information

Tested on Windows 11 and Linux

### Issue description

If a `Tree` or its Parent is scaled, the tree item button would not press.

### Steps to reproduce

1. Create a `Tree`
2. Add a `TreeItem`
3. Add a button to that `TreeItem`
4. Set the Tree scale to 2

If we listen to the button firing signals before scaling the tree, they fire. If after, they dont fire.
Note: the problem arises even if we scale the container

### Minimal reproduction project (MRP)

You can attach this script to a CanvasLayer totest

```csharp
public partial class TreeTest : Node
{
	[Export] private Control _container;
	
	[Export] private Texture2D _texPlus;
	[Export] private Texture2D _texMinus;

	private Tree _tree;

	public override void _Ready()
	{
		_container.Scale = Vector2.One * 2;

		_tree = new Tree();

		_tree.CustomMinimumSize = new Vector2(200, 200);

		var root = _tree.CreateItem();
		root.SetText(0, "root");

		var item1 = _tree.CreateItem(root);
		item1.SetText(0, "itm 1");
		item1.AddButton(0, _texMinus);
		item1.AddButton(0, _texPlus);

		var item2 = _tree.CreateItem(root);
		item2.AddButton(0, _texMinus);
		item2.AddButton(0, _texPlus);
		item2.SetText(0, "itm 2");

		_tree.ButtonClicked += ButtonClicked;

		_container.AddChild(_tree);
	}

	private void ButtonClicked(TreeItem item, long column, long id, long mouseButtonIndex)
	{
		GD.Print($"ButtonClicked: {item.GetText(0)} col:{column} id:{id}");
	}

}
```

### PR DESCRIPTION
**Pull request by timothyqiu**
Transform coordinate properly instead of trying to calculate that manually.

MRP: [test-4.zip](https://github.com/user-attachments/files/17437313/test-4.zip)

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/99954

### CODE REVIEW

**Review by Sauermann — APPROVED** [review]
Implementation and code style looks correct.
I have tested the PR rebased on 58a7f9b4d and it fixes the bug.

**Comment by thygrrr** [comment]
LGTM! An important fix, I had wondered what was wrong with rotated controls / trees.

**Comment by Repiteo** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
