### PR TITLE
support horizontal mouse wheel

### LINKED ISSUE #3565: Unable to scroll script editor horizontally with mouse horizontal scrolling feature
When editor ends up being scrolled horizontally ( when editing a very long line in smaller window, for example ), horizontal scroll bar does not appear on the bottom of the window, nor is it possible to use horizontal scrolling mousewheel to scroll back to the beginning ( or a Magic Mouse touch-scrolling on a Mac ).

### PR DESCRIPTION
**Pull request by 27thLiz**
fixes #3565. Only tested this on linux as I could not figure out how to emulate a horizontal wheel on windows.

### CODE REVIEW

**Comment by reduz** [comment]
are the H values standard? if so then it' s fine

**Comment by Hinsbart** [comment]
yeah according to the [docs](https://msdn.microsoft.com/en-us/library/windows/desktop/ms645614(v=vs.85).aspx) a negative value for `HIWORD(wParam)` is left, a positive one right.

**Comment by akien-mga** [comment]
Awesome work!

**Comment by akien-mga** [comment]
Will it work on X11 just by adding the new enum constants, or did you forget to commit changes to `platform/x11`?

**Comment by Hinsbart** [comment]
x11 had already sent mouse events with indices 6 and 7 even before this, yes ^^

**Comment by akien-mga** [comment]
Ah nice :)

**Comment by toger5** [comment]
the horizontal scrolling works really good with Mac mousepads.
the speed is right.
can you somehow use the same logic for vertical scrolling?

**Pull request merged**
