### PR TITLE
Fixed graphic artifact caused by anisotropic filter

### PR DESCRIPTION
**Pull request by AndreaCatania**
Fixes: #15557

The artifact was caused by division by 0

### CODE REVIEW

**Comment by groud** [comment]
We divided by zero and earth did not explode? Wow.

**Comment by AndreaCatania** [comment]
@groud yes was strange, but the OpenGL 3.3 spec say:

> Similarly, treatment of conditions such as divide by 0 may lead to an unspecified result, but in no case should such a condition lead to the interruption or termination of processing.

**Comment by tagcup** [comment]
Assuming anisoropy doesn't go beyond 1, the only way that can happen is when roughness is 0, which is already checked for [here](https://github.com/godotengine/godot/blob/252344f706452c36e579118a07bccd2d91afc710/drivers/gles3/shaders/scene.glsl#L1035).

Skipping it with that `if` entirely makes sense for GGX because if you take limit for the D and G functions you'l get 0 for specular BRDF, didn't check the other non-physical ones though

**Comment by tagcup** [comment]
Might be a precision issue in which case the proper fix would be to replace the 0.0 in `if (roughness > 0.0)`  with a reasonably small epsilon value.

Anyway this fix/hack is for sure wrong because when rougness is 0, taking limit gives 0 for GGX D function whereas with this fix, you get 1000.

**Comment by AndreaCatania** [comment]
@tagcup It's fine for me if you fix it properly

**Pull request merged**
