### PR TITLE
GDScript: OP_NOT priority set to 1

### LINKED ISSUE #39401: bool_var = true == !false causes error
**Godot version:**

3.2.1 stable

**OS/device including version:**

WIndows 10

**Issue description:**

bool_var = true == !false causes error "unexpected two consecutive operators" Also is produced when replacing true and false with boolean variables or methods. Can be overcome by using != false instead of == !false. You can also do (!false) and that works. This specific issue is very low priority but it could be the case that the source of this issue is causing greater issues in other contexts. 

**Steps to reproduce:**
unzip file Error should be on display

**Minimal reproduction project:**

[boolError.zip](https://github.com/godotengine/godot/files/4748122/boolError.zip)

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #39401

### CODE REVIEW

**Comment by volzhs** [comment]
I'm just curious, does this not affecting this source code?
```gdscript
if not a in array_var:
    pass
```

**Comment by akien-mga** [comment]
@volzhs You're likely right, this would break `not a in array_var`, as `OP_IN` has priority 10.

**Comment by ThakeeNathees** [comment]
according to c++ operator precedence table (https://en.cppreference.com/w/cpp/language/operator_precedence) operator not (unary) have a higher priority than any other binary operator, but in python it has a complete different order (https://docs.python.org/3/reference/expressions.html#operator-precedence) which makes 
`a = b != !c` is invalid syntax. 
since GDScript is closer to python we could consider `a = b != !c` is not a bug but an invalid syntax and leave it there.

(sorry for the confusion)

**Comment by bojidar-bg** [comment]
Note, due to how precedence is currently implemented, fixing that to parse as `not (a in array_var)` would also result in `a in not array_var` erroneously parsing as `a (in) not array_var`

**Comment by vnen** [comment]
I commented in the issue but will also add here: the new parser solves the issue. The case `a = b != !c` is also valid.

**Comment by ThakeeNathees** [comment]
> I would want to write it as
> `a not in array` to ask the in function to return the opposite

@vnen how about `OP_NOT_IN` and `OP_IS_NOT` ??

**Comment by lukostello** [comment]
Wouldn't OP_NOT_IN just return the same thing as OP_NOT OP_IN?

**Pull request closed without merging**
