### PR TITLE
Cherry-picks for the 4.0 branch (future 4.0.3) - 5th batch

### PR DESCRIPTION
**Pull request by YuriSizov**
Final batch before building 4.0.3-stable. 

- Two previous cherry-pick have been reverted.
  - https://github.com/godotengine/godot/pull/71670 required further changes, which aren't safe for a patch release.
  - https://github.com/godotengine/godot/pull/64388 causes a regression which needs to be fixed, so it's better to err on the side of caution and give it a bit more time to be tested in `master`.
- Several documentation changes and very safe fixes (including crashes) added.
- Changelog should be up to date.
- Still needs a version bump ahead of starting the build 🙃

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by AThousandShips** [comment]
Godot-cpp was updated to match #76406

**Comment by akien-mga** [comment]
We probably need this change in the `4.0` branch:
```diff
diff --git a/.github/workflows/linux_builds.yml b/.github/workflows/linux_builds.yml
index 44765ee32e..9ef0e731c9 100644
--- a/.github/workflows/linux_builds.yml
+++ b/.github/workflows/linux_builds.yml
@@ -5,7 +5,7 @@ on:
 # Global Settings
 env:
   # Only used for the cache key. Increment version to force clean build.
-  GODOT_BASE_BRANCH: master
+  GODOT_BASE_BRANCH: 4.0
   SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes
   DOTNET_NOLOGO: true
   DOTNET_CLI_TELEMETRY_OPTOUT: true
@@ -182,6 +182,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: godotengine/godot-cpp
+          ref: ${{ env.GODOT_BASE_BRANCH }}
           submodules: 'recursive'
           path: 'godot-cpp'
 
```

And only the second part in the `master` branch, for consistency.

**Comment by YuriSizov** [comment]
Yeah, I just arrived to the same conclusion. Will add a commit.

**Comment by akien-mga** [comment]
I made a PR as other files needed a fix too: #77204. But feel free to include that commit directly in this PR and supersede mine.

**Comment by YuriSizov** [comment]
Ah, then I'll just merge and rebase 👍 Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
