### PR TITLE
Add TextFile support across the editor

### LINKED ISSUE #21787: TextFiles have no ResourceFormatLoader and other related Inspector difficulties.
**Godot version:**
Godot 3.1

**Issue description:**
I wanted to use TextFile to create a script for CSVs (with file extension .csv.txt or .csv.tres or something to avoid the translation assumption). However, there is no way to treat a TextFile as a Resource in the Inspector without creating an error. There are a variety of problems that occur.

1. Can't open it via the inspector (no loader found for resource).
2. Can't create one from within the Inspector and then save it (if you save a *.txt, you get an "error saving resource!" alert and it fails).

If I can't load it into the Inspector, edit a Resource-compatible property (like the script property), and then save it from the Inspector, it doesn't really "work" right as a Resource type.

**Steps to reproduce:**
1. Create a data.csv.txt file in your file system.
2. Click the "open" button in the Inspector.
3. No option for text files exists in the available file types for filtering visibility (issue).
4. If you select All Files and then open the *.txt file, you'll get a `No loader found for resource: res://data.csv.txt` error.

OR

1. Click new file in Inspector.
2. Select TextFile.
3. Select "Save" or "Save As..." from the tools dropdown in the Inspector.
4. Save with a *.txt extension.
5. An alert pops up saying it failed.

### LINKED ISSUE #24187: Improve UX for editing non-script text files in the script editor
**Godot version:**
Master (a7bd9f0)

**OS/device including version:**
Any.

**Issue description:**
@Paulb23 added long-requested support for opening arbitrary text files in the script editor in #19225, and it works well.

The UX could be improved in several ways, though:
- File > Open in the script editor has the filter "All Recognized" which does not include non-Godot text extensions, so those files are not listed as valid targets. You can change the filter to "All Files (*)" to see them. IMO it's ok that the default excludes non-script text files as it would be difficult to whitelist all possible extensions (.txt, .log, .godot, .import, .cfg, .json, .yaml, etc.). But maybe we can at least rename the default filter to "All Script Formats" to make it clear that it only includes though.
- Non-script/resource text files are not shown in the FileSystem dock, so you can't double click them to open them in the text editor. So the only workflow to actually edit them is to use File > Open, change the default filter, and then select the file.

Ideas welcome on how to improve things, without introducing worse issues such as having the FileSystem dock cluttered with text-based `.import` files.

### PR DESCRIPTION
**Pull request by Paulb23**
Starting to look at improving `TextFile` support in the editor.

This PR adds a new editor setting `docks/filesystem/textfile_extensions` that accepts a csv list of extensions e.g `txt,cfg,json`. 

Any file with those extensions will be visible in the `FileSystem` dock with the `TextFile` icon, all normal operations work i.e open, delete, rename etc. Right clicking the `FileSystem` dock will allow you to create a `TextFile`. Similarly, the inspector can now handle `TextFiles`

The main file dialogs will have the extensions listed in `docks/filesystem/textfile_extensions` as filters. On top of this, `TextFiles` will now appear the in the general `QuickOpen` menu.

The system favours the `ResourceLoader`, so if `tscn` is in the extension list, it will have no affect. In addition, `TextFiles` will not appear in the exporting process or be exported, so will have to use the export filters as usual.

Finally, they are not classed as `import_extensions`, so will not litter the project with `.import` files.

Related godotengine/godot-proposals/issues/677

closes #21787
closes #24187

----

Unsure where the setting belongs, did think about moving to `ProjectSettings` as each project may use different file types?

### CODE REVIEW

**Comment by Calinou** [comment]
Should we add a default list of TextFile extensions? This would improve the FileSystem dock usability out of the box.

**Comment by akien-mga** [comment]
I'm not so fond of having to special case `TextFile` everywhere so that it's not handled like other resources. Couldn't we find a way to allow editing text files without the need for a proxy `TextFile` resource which we actually don't want to be treated as a resource?

**Comment by Paulb23** [comment]
The short answer is not really.

The longer answer is, if we did remove `TextFiles` as a resource, we'd have more edge cases, as everything is expecting a resource and assumes it to be handled by the `Resource[Loader|Saver]`. E.g Currently, with this the `QuickOpen` menu works without any changes.

Given that, the other solution is to modify `Resource[Loader|Saver]`. This will mean touching core which reduz was originally against. And by doing so it would become re-exposed to users, which has caused enough issues during 3.x.

**Comment by reduz** [comment]
Aditionally, you maay want to treat JSON as a special case because it can be parsed and throw errors too (Godot JSON object supports this, if parsing is broken it tells you where exactly)

**Comment by Paulb23** [comment]
I think for now, we keep JSON as a plain text file. Then for `4.1-4.2` we can add improved support for editing JSON, as `ScriptEditorPlugin / ScriptEditorBase` is due a refactor (in part for adding multi-window support).

**Comment by reduz** [comment]
@Paulb23 sounds good, as long as its nothing that will require large compat break we can kick to 4.1 or other minor versions.
We would likely need to then fix the export settings so it uses a different extension, like gdcfg

**Comment by Paulb23** [comment]
Updated to change `export_presets.cfg` to `export_presets.gdcfg`, included some renaming code, so should not break compatibility.

**Comment by akien-mga** [comment]
> We would likely need to then fix the export settings so it uses a different extension, like gdcfg

Personally I don't think that's necessary. It's yet another unique extension for a single file, for a supposed problem which I'm not sure will actually be a problem.

It's not particularly useful to open `export_presets.cfg` in the script editor, but it doesn't hurt either. As pointed out, it can be done anyway from the File menu.

If we want to hide it from the FS dock, I'd special case it there, but in general I'd prefer to merge this PR first, and then we can assess if there's any text file that we don't want to expose for easy opening as TextFile.

So I'd leave out da35bc3 (can be kept in case it's wanted later on) to merge this PR otherwise as is.

**Comment by Paulb23** [comment]
> If we want to hide it from the FS dock, I'd special case it there, but in general I'd prefer to merge this PR first, and then we can assess if there's any text file that we don't want to expose for easy opening as TextFile.
>
> So I'd leave out da35bc3 (can be kept in case it's wanted later on) to merge this PR otherwise as is.

Sounds like a plan, removed the commit.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
