### PR TITLE
Add an `Array.pop_at()` method to pop an element at an arbitrary index

### LINKED ISSUE #562: Add an Array.pop() method to Array.
**Describe the project you are working on:**
A visual novel game.

**Describe the problem or limitation you are having in your project:**
I'm working on the underlying machinery to get the game's guts running. It involves working with a lot of text data and the solution I found to handle that is by utilizing arrays. I'm using Array's `pop_back()` and `pop_front()` a lot to extract values from the array and delete them in one go. However, I've found myself needing to write a custom function for popping and returning values from arbitrary positions in an array. It has to take in the array reference and the position to pop from. While the solution works, I still yearn for a built-in array method to pop from any position.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Add a `pop()` method to the Array class that allows to pop and return a value from an array at arbitrary positions. It would take a position argument that will be used to pop and return a value from an array at that position. It directly solves the limitation I've described in the paragraph above.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
I haven't worked with Godot's sources in any way nor I speak C++ but from a quick look at the array code in core, it seems trivial to add by copying and slightly modifying the front and back popping methods.

`Array.pop(position: int)`:
1. Store a value from the array at the provided index `position `in a variable.
2. Delete the value at index `position `in the array.
3. Return the stored value.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
The improvement I'm describing is, I believe, a basic and common functionality in array-type collections. One can (I did) work around the issue by writing a custom pop method but since the proposed functionality is common among a wide variety of languages and is basic for an array-like type, I think that it should be shipped with the Array class.

For:
- Present in many languages' array-like collection type.
    - Lua's `table.remove (list [, pos])`. **Removes** from list the element **at position pos**, **returning the value** of the removed element.
    - Dart's `E removeAt(int index)`;. **Removes the object at position** index from this list. **Returns the removed object**.
    - Rust VecDeque's `pub fn remove(&mut self, index: usize) -> Option<T>`. **Removes and returns the element at index** from the VecDeque.
    - Python's `list.pop([i])`. **Remove the item at the given position** in the list, **and return it**.
    - Ruby's `delete_at(index) → obj or nil`. **Deletes the element at the specified index, returning that element**, or nil if the index is out of range.
- Requires minimal effort to add.
- Very unlikely to cause bugs.
- It's common functionality for an array type as evidenced above.
- GDScript's Array already has `pop_front()` and `pop_back()`; `pop()` would complement it nicely.
- The main scope of the change is contained within the Array class.
- A custom method is cumbersome to use if it's needed in multiple scripts. Adding it to some Utils class adds the overhead of referring to that class every time.

Against:
- The change requires adding a method to Godot's core.
- Someone has to do it :)

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's impossible to modify GDScript with an add-on.

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/52143.

Negative indices are supported to pop an element relative from the end.

## Example

```gdscript
func _ready():
	var array = [2, 4, 6, 8, 10]
	print("Original array: ", array)
	print(array.pop_at(2), ". Array is now ", array)
	print(array.pop_at(2), ". Array is now ", array)
	# Pop the last element.
	print(array.pop_at(-1), ". Array is now ", array)	
	# This is invalid since the array only has 3 elements at this point.
	# This will print an error and return `null`.
	print(array.pop_at(-15), ". Array is now ", array)
	print(array.pop_at(0), ". Array is now ", array)
	print(array.pop_at(0), ". Array is now ", array)
	# This will return `null` without printing an error.
	print("Trying to pop empty array. ", array.pop_at(24), ". Array is now ", array)
```

```text
Original array: [2, 4, 6, 8, 10]
6. Array is now [2, 4, 8, 10]
8. Array is now [2, 4, 10]
10. Array is now [2, 4]
Null. Array is now [2, 4]
2. Array is now [4]
4. Array is now []
Trying to pop empty array. Null. Array is now []
```

This closes https://github.com/godotengine/godot-proposals/issues/562.

~~PS: Should we print an error when trying to pop an empty array, or is the current behavior fine?~~

**Edit:** Not displaying an error is fine, for consistency with `pop_back()` and `pop_front()`'s behavior.

### CODE REVIEW

**Comment by asheraryam** [comment]
I don't think we need an error when popping an empty array, it's not dangerous and makes a lot of sense to get a null element.

Imo errors should be for consequences that are either unsafe, suboptimal (performance wise), broken, or dangerous. This scenario is probably a Warning in the worse case :b

I like the idea of having a helper method instead of using `splice()` every time, but `pop()` has a well known and specific meaning already (removes and returns the last element) so not sure if it'll cause confusion.

**Comment by vnen** [comment]
I understand the appeal but I find the name confusing. `array.pop(2)` sounds like you are popping 2 elements.

Since we have `pop_back` and `pop_front` this could be `pop_middle` or `pop_index`.

Alternatively, we could make `Array.remove()` return the value.

**Comment by asheraryam** [comment]
I prefer `pop_index` over `Array.remove()` but both are great ideas.

**Comment by Calinou** [comment]
> I don't think we need an error when popping an empty array, it's not dangerous and makes a lot of sense to get a null element.

Indeed, it makes sense to follow `pop_back()`/`pop_front()`'s behavior here.

**Comment by katoneko** [comment]
How about `pop_at()`?

**Comment by Calinou** [comment]
I updated the pull request to use `pop_at()` instead of `pop()`. I also improved the documentation in the process.

**Review by reduz — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Needs to be rebased, otherwise looks good to go.

**Pull request merged**
