### PR TITLE
Clarify `Tween.set_parallel()`

### PR DESCRIPTION
**Pull request by KoBeWi**
Addresses https://github.com/godotengine/godot/issues/74608#issuecomment-1645430419

### CODE REVIEW

**Comment by Mickeon** [comment]
I fell under the same "trap" right now, so it would be nice to have this one looked at.

**Comment by YuriSizov** [comment]
Yeah, I don't get it. It makes everything after, _and one before_ to run in parallel? I can see the logic behind it now, but without knowing that this is the case I'd be very surprised by this behavior.

**Comment by Mickeon** [comment]
It's plainly unorthodox, as others have brought up in the issue page. It feels buggy, but would be too late to somehow change now.

**Comment by Mickeon** [comment]
How do we feel about this? I still believe this behavior is unorthodox, but it's better to document it than not doing anything.

**Review by Mickeon — APPROVED** [review]
You're right, Micky from 3 weeks ago: it **is** better to document it than not doing anything.

Although the current behavior is not exactly pretty.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
