### PR TITLE
Fixes to the DDS loader

### PR DESCRIPTION
**Pull request by aqnuep**
* Added missing format info entries for ATI1 and ATI2 formats
* Added missing A2XY format

### CODE REVIEW

**Comment by aqnuep** [comment]
I accidentally also came across that this originally wasn't broken, but got broken about 2 years ago due to the commit that introduced clang-format: 5dbf1809c6e3e905b94b8764e99491e608122261 :confused:

**Comment by akien-mga** [comment]
> I accidentally also came across that this originally wasn't broken, but got broken about 2 years ago due to the commit that introduced clang-format: 5dbf180

How exactly? I don't think any other change than formatting changes in this commit for this file. As far as I can tell the values before and after in `ResourceFormatDDS::load` are the same.

**Comment by aqnuep** [comment]
I used TortoiseGit's blame tool, maybe it showed the changes incorrectly.

**Comment by aqnuep** [comment]
Just verified, indeed something must be wrong with the way the blame tool works here. Maybe it just doesn't show changes that only removed lines.

Anyway, what's for sure is that two years ago the 2 entries for ATI1 and ATI2 were there, but somehow got deleted.

**Comment by mhilbrunner** [comment]
This commit modified them:
https://github.com/godotengine/godot/commit/f89641907f8b45941f5e67891936ee8050a3ef92

And it seems like this commit removed them:
https://github.com/godotengine/godot/commit/a134f58fb3e072a3453bd5e9286f90b4694c9766

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
