### PR TITLE
[Mono] Vector2/3 Project methods

### PR DESCRIPTION
**Pull request by aaronfranke**
C# implementation of https://github.com/godotengine/godot/pull/20804 ~~except also compare with Epsilon first.~~

### CODE REVIEW

**Comment by akien-mga** [comment]
> except also compare with Epsilon first.

Would be good to change in the original too, no? If this is relevant for C#, it's likely also for C++.

**Review by akien-mga — APPROVED** [review]

**Comment by aaronfranke** [comment]
The main reason I chose to compare with Epsilon is not because of divide by zero errors, but because you get strange behavior when working with near-zero or ultra-large numbers. This is just an unavoidable fact when working with finite precision.

Test code:

    Vector3 thing = new Vector3(1234.5678f, 20, 30);
    Vector3 onNormal = new Vector3(1234.5678f, 20, 30);

    public override void _Process(float delta)
    {
        GD.Print(onNormal.x + " " + thing.Project(onNormal).x);
        onNormal /= 2;
    }

Output:

    1.307149E-19 1234.568
    6.535747E-20 1234.568
    3.267874E-20 1234.567
    1.633937E-20 1234.569
    8.169684E-21 1234.582
    4.084842E-21 1234.634
    2.042421E-21 1234.323
    1.021211E-21 1235.982
    5.106053E-22 1235.982
    2.553026E-22 1222.833
    1.276513E-22 1197.358
    6.382566E-23 1197.358
    3.191283E-23 898.0182
    1.595641E-23 Infinity
    7.978207E-24 Infinity
    /// etc...
    1.401298E-44 Infinity
    7.006492E-45 Infinity
    2.802597E-45 Infinity
    1.401298E-45 Infinity
    0 NaN
    0 NaN

Problems started occuring at about 10^-20 , overflowed to Infinity at about 10^-23 , and overflowed to NaN at about 10^-45 . The test case here is fairly simple (projecting a Vector3 onto itself), for more advanced cases problems may occur at values farther from zero than this.

I think it's best to avoid these cases rather than let them happen. But I am willing to remove the Epsilon comparison code if you still think that's best (I've already done so on my local branch to test this).

**Comment by akien-mga** [comment]
It's expected that it goes to INF in small values and NaN at exact 0 though, that's the behaviour of the multiplicative inverse:
screenshot_20180822_094947

On the other hand, having it go towards high numbers on low length values (e.g. 0.003) but 0 when passed 0 as input would be an unexpected singularity, as 1/x never passes by 0.

**Comment by aaronfranke** [comment]
@akien-mga Done. I did change the "self-dot" part to `length_squared` as `length_squared` is a more specific function that's best to use here. Output is the same but might run slightly faster.

**Comment by akien-mga** [comment]
Thanks!

**Comment by karroffel** [comment]
`this->length_squared()` shouldn't run any faster than `this->dot(*this)` as it evaluates the exact same code.

It doesn't really make a difference since both things express the exact same thing, just wanted to note it here that there's actually no specific reason to prefer one over the other :smiley:

**Pull request merged**
