### PR TITLE
Add incremental update mode to sky

### PR DESCRIPTION
**Pull request by clayjohn**
This adds two new ``process_modes`` to ``Sky``. 

**Automatic** - selects the appropriate process mode based on shader usage. This is the new default. Ideally, users will be able to leave it on automatic and never select a difference mode. 

**High Quality Incremental** - This is the same as High Quality, except it updates over 8 frames (by default). It processes each roughness layer in a frame to smooth out the cost of importance sampling all the layers. On high-end devices 8 frames will feel almost instant. Most importantly, this mode is used by ``AUTOMATIC`` when a light is used in the sky shader. So adding this mode will fix users have hiccups as they rotate the sun in the editor.

I experimented with only updating 1 face per frame (updates over 48 frames). But the update delay was way more noticeable and the frame time reduction was not worth it.

This issue hasn't been reported in the bug tracker, but I have seen it mentioned a few times on IRC, Discord and [Twitter](https://twitter.com/HungryProton/status/1280838619608080388)

### CODE REVIEW

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Calinou** [comment]
Is the High Quality mode still relevant when we have High Quality Incremental? I can't see any upsides to it.

**Comment by clayjohn** [comment]
@Calinou High Quality incremental needs several frames to converge. High Quality mode is preferable when you want the reflections to be immediately available on load.

**Comment by Calinou** [comment]
> High Quality mode is preferable when you want the reflections to be immediately available on load.

There is a special case to ensure that the sky is available as soon as possible when using the High Quality Incremental update mode, doesn't that suffice?

https://github.com/Calinou/godot/blob/b6caa0587a8e16f77b0029c5bb7a70577afb0ec7/servers/rendering/renderer_rd/renderer_scene_sky_rd.cpp#L1247-L1251

**Comment by clayjohn** [comment]
> There is a special case to ensure that the sky is available as soon as possible when using the High Quality Incremental update mode. Doesn't that suffice?

Not really, that code only runs when the sky resource has been recreated from scratch. It doesn't apply when, for example, the user changes the sky material during a scene transition or loading screen etc. 

> When updating the sky at run-time, I'm don't think having a really low framerate is a better experience over having parts of the sky being slightly out of date.

I tend to agree with that. But that doesn't convince me that we should get rid of the Update once mode.

**Comment by Calinou** [comment]
> Not really, that code only runs when the sky resource has been recreated from scratch. It doesn't apply when, for example, the user changes the sky material during a scene transition or loading screen etc.

When I tested https://github.com/godotengine/godot/pull/55933, I noticed that swapping the sky resource for a new one forced the sky to update. So I think it _does_ work when you clear or reassign the sky resource entirely – but it won't trigger when you change a property *within* the sky resource.

**Pull request merged**
