### PR TITLE
Fix member assignment with operation

### LINKED ISSUE #50523: Addition assignment operator causes the assigned variable to change in gdscript
### Godot version

4.0.dev (60add98a4cff0d27c6aa2f52042555eccb86ed70)

### System information

Windows 10

### Issue description

Using `+=` operator between a property and a local variable can cause the local variable to take the value of the property.

It doesn't occur in 3.x versions.

### Steps to reproduce

In this example script:

```
extends Node2D

func _process(delta):
	var motion = Vector2(10.0, 0.0)
	position += motion
	print(motion)
```

The local variable `motion` ends up with its value being equal to `position` after the assignment, as observed in the printed value which increases every frame.

### Minimal reproduction project

[assignment-bug-gdscript.zip](https://github.com/godotengine/godot/files/6832875/assignment-bug-gdscript.zip)

### PR DESCRIPTION
**Pull request by vnen**
It was wrongly updating the assigned value with the result of the operation.

Fix #50523

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
One test seems to trigger a segfault.

**Comment by vnen** [comment]
I guess I can't use a `Node2D` in the test since that requires the Rendering Server to be active.

**Comment by akien-mga** [comment]
> I guess I can't use a `Node2D` in the test since that requires the Rendering Server to be active.

Can this be worked around by tweaking the test so that we can merge the bugfix anyway?

**Comment by vnen** [comment]
I'll try to come up with something, but this is somewhat a bigger issue. I get that using a minimal context with tests is better since it's faster, but if we can't instance the majority of nodes then there are many things we can't actually test.

**Comment by akien-mga** [comment]
> I'll try to come up with something, but this is somewhat a bigger issue. I get that using a minimal context with tests is better since it's faster, but if we can't instance the majority of nodes then there are many things we can't actually test.

AFAIK this was done this way not by design, but for practical reasons. We did not have headless rendering support so contributors had to hack things around to still be able to run a minimal version of Godot with rendering server.

This could and should likely be revisited now that we can run stuff headless, so we should be able to use a testing context which is equivalent to the normal runtime.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
