### PR TITLE
Removed GDScript "function" keyword

### PR DESCRIPTION
**Pull request by ghost**
Removed the "function" keyword from GDScript, it's a alias for "func".

### CODE REVIEW

**Comment by akien-mga** [comment]
Would be fine by me, @reduz, @punto-, any objection?

**Comment by oscarcp** [comment]
I would consider a deprecation warning on the console log before removing completely the alias, but that's just my opinion.

**Comment by akien-mga** [comment]
> I would consider a deprecation warning on the console log before removing completely the alias, but that's just my opinion.

That's a good point, but as we added no such warning for the other undocumented keywords that were deprecated for 2.0, nor for the blunt API changes where we renamed functions, I don't think it would be worth doing it now just for this alias.

It should of course be documented in the release changelog though, see #3355.

**Comment by oscarcp** [comment]
Yeah, I realized after writing it that other names were deprecated. To be honest, Godot is still in a pretty early stage (the community of it, although big, doesn't expect retrocompatibility or consistency through versions) and it's affordable to do this kind of movements, but as the software grows, a deprecation plan should be put in place :)

**Comment by akien-mga** [comment]
I completely agree :)

**Pull request merged**
