### PR TITLE
Fixed renaming/reparenting/duplicating a node disabling editable_children

### LINKED ISSUE #6455: Instance loses it's "Editable children" flag after renaming. Affects saved edits too
Godot 2.2 alpha latest build, linux x86
Renaming an instance with "Editable children" makes it lose the flag.

### LINKED ISSUE #20409: Rename an "Instanced Scene as Node" disables "Editable Children"
https://github.com/godotengine/godot/commit/89e1b302b504feb1cea218adcc6fac77c8ae0052
x11

It only happen if it's a name that the node never had before.

peek 2018-07-24 15-22

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed renaming/reparenting/duplicating a node disabling editable_children.

This should fix #20409 & fix #6455 and probably some others I missed.

### CODE REVIEW

**Comment by reduz** [comment]
This is a really difficult issue to fix without introducing many hacks, and we are too close to 3.1 alpha to risk breaking more things.
Eventually plan is for next version to re-evaluate how all this data is stored in hopes of simplifying the system.

**Comment by DualMatrix** [comment]
Yeah currently it seems almost impossible to solve this problem without a bunch of hacks with the current way the editable_children data is stored.

**Comment by akien-mga** [comment]
Sorry for the lack of update in over a year :|

I'm unsure on how to proceed with this PR. There are various issues with the approach uses, especially the fact that it adds many new methods and signals to the public node API which have no real reason to be in the public API. As @reduz mentioned, the approach used is a bit hacky, but a non-hacky solution is likely difficult to use right now.

I think this PR should likely be closed, but we need to have some pointers on how the two referenced bugs should be fixed in a clearer manner. Especially whether any fix should wait on:

>  Eventually plan is for next version to re-evaluate how all this data is stored in hopes of simplifying the system.

And when would this happen in the roadmap.

**Comment by aaronfranke** [comment]
@Piet-G Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by aaronfranke** [comment]
This PR has not received any new commits for almost 2 years and is abandoned, closing.

The "salvageable" tag applies, anyone is welcome to take this PR and update/finish it.

**Pull request closed without merging**
