### PR TITLE
Add the `[param foo]` syntax to reference parameters with a validity check

### LINKED ISSUE #4880: Add a syntax for documenting method parameters
Reference to existing documentation comments: https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_documentation_comments.html

### Describe the project you are working on

Writing documented code for sharing with others

### Describe the problem or limitation you are having in your project

Right now everyone uses `[code][/code]` for documenting parameters, but it's a pretty tedious string to type, and it doesn't differentiate from other code snippets.

`[code]` is even used for parameters in the engine itself. Using something like `[parameter foo]` would at least be future proof if for example we make parameters URL linkable.

image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Make `[parameter foo]` valid in documentation.

Alternative syntax:

- `[parameter foo]`
- `[param foo]`
- `[argument foo]`
- `[arg foo]`

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
## Says hello to [parameter who].
func hello(who):
	print("Hello, ", who)
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This will be used all over Godot's official documentation

### Is there a reason why this should be core and not an add-on in the asset library?

Documentation is part of the editor

### PR DESCRIPTION
**Pull request by YuriSizov**
Closes https://github.com/godotengine/godot-proposals/issues/4880.
~~This is based on https://github.com/godotengine/godot/pull/64004 so marking as draft for the time being.~~

This PR adds a new BBCode tag, `[param foo]` that can be used instead of the old `[code]foo[/code]` strings to refer to method, signal, and annotation parameters. Using them improperly, messing up names, etc. would result in CI failure in Static Check.

This should also help translators to identify that the inline code bit is a reference to a parameter instead of being a random piece of code or a reference to something else. This should hopefully let us avoid situations where we use identifiers as parts of the sentence in English and confuse translators who don't have this full context.

Neither online docs nor the built-in help have any special formatting for these new tags. They are simply displayed as code blocks. This can be adjusted with future PRs. For parity with the rest of the tag-handling code in RST generation the empty tags are stripped (both `[param]` and `[param ]`), and in built-in docs the `[param]` option is not handled and printed as is.

For consistency the `<argument>` tag in XMLs has been renamed to `<param>`. Note, that the engine refers to these things as arguments throughout all of its systems. But as identified by https://github.com/godotengine/godot-proposals/issues/4880, this is likely a misnomer. Doing a huge core refactor for this didn't like a good idea, but the XMLs themselves, being public-facing, should had been updated. So I did that.

Incidentally, `make_rst.py` already called those "params" internally, so there is that.

-----

This PR doesn't include any usages of `[param foo]` yet. I'll leave to for future PR and maybe other contributors. Let's focus on the technical side here.

It's also pretty huge because of the XML changes as it is. That's why I've split it into two commits.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Mickeon** [comment]
Is the old [argument] syntax still compatible now? I feel like a lot of PRs that add new methods would have to be updated either before merging or afterwards

**Comment by akien-mga** [comment]
Any PR adding documentation for methods will need to be rebased yes.

**Comment by YuriSizov** [comment]
Should be an easy rebase, doctool would just replace the existing tags without disturbing anything else in the doc. Also easy to replace by hand if needs be.

**Pull request merged**
