### PR TITLE
add NativeScript extension 1

### PR DESCRIPTION
**Pull request by karroffel**
This pull request modifies the API struct code generation and adds new functionality to NativeScript, namely:

 - ability to set and get documentation for classes, methods,
   signals and properties

 - ability to set names and type information to method arguments

 - ability to set and get type tags for nativescripts

 - ability to register instance binding data management functions

 - ability to use instance binding data

### CODE REVIEW

**Comment by karroffel** [comment]
cc @touilleMan @endragor @Zylann @sheepandshepherd @BastiaanOlij 

This PR doesn't break any existing code but it could be interesting for you to take a look anyway :)

**Comment by touilleMan** [comment]
@karroffel I'm not sure why the documentation set/get system is restrained to naviescript. I would say it's more of a core feature that should be present as a part of the Godot `Script` class (and hence available to gdscript and gdnative api)...

**Comment by karroffel** [comment]
Yes maybe, I was thinking that adding that stuff to MethodInfo and PropertyInfo etc would be the better way to go about this, but this works for now. Feel free to open an issue/feature proposal to see if it's wanted.

**Comment by hpvb** [comment]
How does this affect 3.0 ABI and existing gdnative projects?

**Comment by karroffel** [comment]
@hpvb it doesn't break existing projects at all.

The extension adds a `next` pointer of a struct that wasn't used before, so it's al fine.

**Comment by endragor** [comment]
By the way, having documentation for classes/methods/properties in api.json would also be quite useful - binding authors could include the documentation into generated wrappers.

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
