### PR TITLE
New Script Theme, and export(String, MULTILINE) support.

### PR DESCRIPTION
**Pull request by WatIsDeze**
Changed the scripting IDE Theme to match the Dark theme more. Added supp...ort for export(String, "Multiline") var some_string = ""

### CODE REVIEW

**Comment by WatIsDeze** [comment]
Any chances of this being submitted any time soon? I am actually relying on this with my project, and I recall people wishing for this feature to be added asap as well.

**Comment by TheoXD** [comment]
In my opinion, scripting theme does not match, it's unreadable.

**Comment by slapin** [comment]
Could you please split this pull-request? And clean-up crap with tabs?

Thanks a lot!

**Comment by reduz** [comment]
actually yeah, splitting is appreciated, the multiline patch i can merge right away, theme not for now as ndee and other guys are working on a new one, so the current black one is not final yet

**Comment by WatIsDeze** [comment]
Hey all, sorry for the late reply. My emails, I rarely check. As for why most things went wrong, it's a sad fact that I was working with a new setup etc, no need to explain.

I'll just make a separate pull request for the multiline since I take it you haven't merged it yet because my pull request wasn't split. As such I'll let the theme be as is, no need to bother with that anymore given your information @reduz :)

**Pull request closed without merging**
