### PR TITLE
Fix casing of the "to" stop word in editor strings

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/50419.

This also fixes a C# documentation example that had one of its strings incorrectly converted.

Regex used to find occurrences: `[a-zA-Z] To ` (with a trailing space)

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by LightningAA** [comment]
Should this be cherry-picked?

**Comment by Calinou** [comment]
> Should this be cherry-picked?

Done here: https://github.com/godotengine/godot/pull/50419

**Comment by LightningAA** [comment]
Whoops, sorry I missed that, I got confused because you never corrected it in https://github.com/godotengine/godot/pull/50490/.

**Pull request merged**
