### PR TITLE
Fix minor drawing order glitch in polygon 2D editor

### PR DESCRIPTION
**Pull request by ghost**
Fixes a minor glitch, where the handle gets partially overdrawn by the polygon line:

https://user-images.githubusercontent.com/11859538/32533960-b750e87c-c453-11e7-8fce-028721c4a631.jpg

Partial follow up of https://github.com/godotengine/godot/pull/12740.

### CODE REVIEW

**Comment by groud** [comment]
Hum, seems a quite a complex workaround... Why not just run a first loop drawing the lines and a second one to draw the textures ?

**Comment by poke1024** [comment]
@groud I didn't want to duplicate the code calculating the vertex position. I also disliked transforming the points twice. Anyway, just pushed another variant using a loop that doesn't duplicate code.

**Comment by groud** [comment]
> @groud I didn't want to duplicate the code calculating the vertex position

It's ok duplicating this code, especially because it's not at all performance critical.
You're doing premature optimization. Writing a code that is easy to understand and to maintain is **a lot** more important in this situation. :) 

Just do a first pass drawing the lines, then a second one drawing the handles, even if it needs to duplicate two lines. It's a lot simpler to understand even if not optimal.

**Comment by poke1024** [comment]
We surely have very different ideas of maintainable code, but here you are :)

**Pull request merged**
