### PR TITLE
Tilemap editor: Bucket tool - allow deleting and replacing of tiles

### PR DESCRIPTION
**Pull request by Garmelon**

### CODE REVIEW

**Comment by vnen** [comment]
@Garmelon, the email you used to commit is not registered on GitHub, so it won't be associated with your account. You can add it as a secondary address to your account if you with to have such association.

**Comment by Garmelon** [comment]
Thank you, I didn't know that. Added that email address to my account now.

**Comment by henriquelalves** [comment]
Well, I think this closes issue #6320, doesn't it?

**Comment by akien-mga** [comment]
Indeed.

**Pull request merged**
