### PR TITLE
Add astcenc compression and decompression.

### PR DESCRIPTION
**Pull request by fire**
Keep mingw compatibility by modifying astcenc_platform_isa_detection.cpp to use all lowercase for Windows includes.

@reduz 

Done as part of the https://github.com/v-sekai/v-sekai-game work for opensource Social VR.

### CODE REVIEW

**Comment by fire** [comment]
- [ ] Needs licensing details

**Review by reduz — APPROVED** [review]

**Comment by reduz** [comment]
This looks good to me, but @akien-mga has to check

**Comment by fire** [comment]
https://github.com/ARM-software/astc-encoder/issues/389 was backported to older versions

**Comment by akien-mga** [comment]
I reviewed and cleaned up the code directly (currently as separate commits for review, I'll squash when approved).
I can't push to `V-Sekai/astcenc-standalone` to update this PR so I had to push to my own fork: https://github.com/akien-mga/godot/commits/astcenc-standalone

Once reviewed and rebased, either you'll need to push to your PR branch or give me access.

**Comment by akien-mga** [comment]
For the record, the email address used to credit @RevoluPowered as co-author doesn't match his GitHub account.

Do you want me/fire to change it to the name and email from https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/67915.patch @RevoluPowered?

**Comment by akien-mga** [comment]
@fire gave me access to the repo so I could update this PR.

I force push directly my squashed versions with all the changes I made, but to review properly you can still check the individual commits in https://github.com/akien-mga/godot/commits/astcenc-standalone

I haven't tested much, so it would be good to make sure it's still working as intended.

I noticed that we're not handling `p_lossy_quality` even though astcenc provides quality options. We currently default to "medium" quality. For now I put a TODO, is this something we want to handle in the future?

**Comment by fire** [comment]
> I noticed that we're not handling p_lossy_quality even though astcenc provides quality options. We currently default to "medium" quality. For now I put a TODO, is this something we want to handle in the future?

I think for now defaulting to the less quality astc is probably prudent until we can make the speed usable.

This is trying to unblock reduz's astc contributions.

**Comment by akien-mga** [comment]
> > I noticed that we're not handling p_lossy_quality even though astcenc provides quality options. We currently default to "medium" quality. For now I put a TODO, is this something we want to handle in the future?
> 
> I think for now defaulting to the less quality astc is probably prudent until we can make the speed usable.

@reduz always says he plans to remove per-texture lossy quality in the future because most encoders don't really care. So using a good default value (medium seems fine to me) is good. We can add more quality options in the future (maybe a project setting instead of per-texture).

**Review by akien-mga — APPROVED** [review]
I'm happy with this PR with regard to the general code quality and integration of the thirdparty library. Great work, notably on stripping down the unnecessary CLI bits of astcenc!

I just need a confirmation that it still works properly in your tests as I did some cleanup in the compress and decompress methods and, while it should behave like before, I may have inadvertently broken something.

I also updated astcenc from 4.2.0 to 4.3.0 (released yesterday) btw.

**Comment by fire** [comment]
The test I did write an import decode function, it's quite hard to test, waiting for reduz's changes.

**Comment by akien-mga** [comment]
So we merge as is and let reduz check if it's actually working when implementing the remaining bits, and fix it if it doesn't?

**Comment by fire** [comment]
Yes, that sounds like a plan.

**Comment by akien-mga** [comment]
Thanks!

**Comment by realkotob** [comment]
Just read through the ASTC [format overview](https://github.com/ARM-software/astc-encoder/blob/main/Docs/FormatOverview.md), exciting stuff!

Are there plans to use this as the default compressor on some platforms? I saw some changes to the etcpack module but it's mostly housekeeping.

**Comment by Calinou** [comment]
> Was looking at the [hardware support matrix](https://en.wikipedia.org/wiki/Adaptive_scalable_texture_compression) for the extensions and it seems ubiquitous.

ASTC support was removed on Intel Arc GPUs, which makes it a no-go as a default.

**Comment by realkotob** [comment]
@Calinou Thank you for answering my question and pointing out nuances I hadn't considered.

Looking forward to get to test this and see how well it's supported. (I've used ASTC within other engines but platform selection had good defaults so I didn't have to worry about it)

**Pull request merged**
