### PR TITLE
OpenXR: Add Pico controller profile

### PR DESCRIPTION
**Pull request by rsjtdrjgfuzkfg**
This PR adds a mechanism to filter interaction profiles and top-level paths by system name, and adds the Pico controller using that feature to ensure its non-standard paths are only suggested on Pico headsets.

Things to consider when reviewing:

* <strike>I added a new mechanism to filter interaction profiles, as Pico deprecated its extensions. I assume there will be official extensions replacing the old ones in the future, but not sure if they will be Pico-specific enough to filter on them. I thus introduced filtering by system name, using an exclamation mark as prefix which should ensure we're not colliding with extension names.
  Instead of that filter, we can alternatively use an deprecated extension for filtering purposes (might stop working at some point) or unconditionally add the interaction profile (might become a more reasonable option if Pico updates the OpenXR spec to include their controllers...).</strike> This feature was removed from the PR, opting to use an undocumented (but working!) extension name instead.

* I included both system keys and the screenshot key. They are not really practical, as system functions of the HMD are bound to them. Future extensions might permit to unbind some or all system features to use these keys normally.
  Instead of including them, we can alternatively keep them unbound in the default map or not include them altogether.

* <strike>How to map default actions. I tried to follow the touch controller, but I feel that the default actions are a bit all over the place. More consistency might be reasonable, with default actions not following controller things ("trigger_click") but functions ("select", which is currently an obscure thing but seems to more commonly refer to the "main" action, which would fit the trigger). Making default actions consistent could be a separate PR, though – we should just get it merged before 4.0 drops, as that likely fixes our naming conventions for some time.</strike> Tracked in https://github.com/godotengine/godot-proposals/issues/5951

### CODE REVIEW

**Comment by rsjtdrjgfuzkfg** [comment]
(tagging @BastiaanOlij for reviewing purposes)

**Comment by BastiaanOlij** [comment]
Hey Dirk,

Let's not get ahead of ourselves, there will be a vendor extension for this, that is the way OpenXR is meant to work and PICO isn't going to get their stuff in if they don't confirm to the standard because it will break all the other runtimes.
We just need to wait until it's officially accepted by the OpenXR Working Group.

This is why I changed the whole way the meta data is registered, so we can extend it and filter it based on vendor extensions (needs a change from @konczg so we can put things into an extension wrapper, I might add that in this week as konczg is currently on holidays).

Sadly we're playing a waiting game at the moment in order to complete Pico support. I'd keep your PR on draft for now, most of it will be salvageable once the vendor extension is officially added to the OpenXR spec, and it's solid for people who want to play around with the PICO already (though I'd already remove the system check for now and just add the PICO bindings in with the footnote that it will potentially give a warning in the logs an unsupported device was found).

**Comment by BastiaanOlij** [comment]
Just to add based on some private discussions I'm having with Dirk. We'll probably need to discuss the default action map separate from this PR, the default action map was designed as a vehicle to make conversion from Godot 3 to Godot 4 easier.

The action map system is designed so games can define actions that makes sense to the game being build, we may wish to consider a much simpler default action map that only has a few basic functions.

Equally so, the official stance of the OpenXR Working Group is that developers only supply bindings to interaction profiles for devices they actually have access too when developing, and leave it up to the XR runtime implementation to generate bindings to other hardware. There is a solid argument that we should not be providing default bindings to all interaction profiles.

Practically there are a lot of con's to this that need to be worked out.

All in all, I don't think that is a discussion for this PR but one that needs to be had separately.

**Comment by rsjtdrjgfuzkfg** [comment]
I opened https://github.com/godotengine/godot-proposals/issues/5951 for the discussion of the default action maps.

**Comment by BastiaanOlij** [comment]
Ok, registering the meta data and enabling the extension should now move into an extension wrapper. Have a look at how the extension wrapper is done for the Huewei controller (`OpenXRHuaweiControllerExtension`), we need one for PICO just like it.

As long as PICO isn't in the official OpenXR spec we can just add a:
```
#ifndef XR_PICO_CONTROLLER_INTERACTION_EXTENSION_NAME
#define XR_PICO_CONTROLLER_INTERACTION_EXTENSION_NAME "XR_PICO_controller_interaction"
#endif
```
At the top of the cpp file.

Then we can change it once the extension is official.

The default action map logic can remain as it is, we'll deal with that once we know what we're doing with the action map.

**Comment by BastiaanOlij** [comment]
Hey @rsjtdrjgfuzkfg ,

COOL! Happy for this to be changed to ready for review if it's all working for you (seems I might be getting a PICO myself so soon I can test too), PICO might change the name of the extension but hopefully they will keep the old name for backwards compatibility with games already made. We can then just remove the `ifndef` code and update the constant when it's all official.

**Comment by BastiaanOlij** [comment]
> I left the typo correction in but can remove it if you would prefer this PR not to touch openxr_api.cpp.

It's fine to be in here if we end up merging it relatively soon but else I'd just submit it as a separate PR. Typo fixes like that I can approve and merge pretty quickly :)

**Comment by rsjtdrjgfuzkfg** [comment]
@BastiaanOlij my main concern are interaction profile paths, not extension names. From the email thread with Pico we know that they plan to change those as well, and they are written to the action map in each project. Changing them in godot afterwards will likely cause problems with existing projects, unless we take explicit measures to migrate or duplicate the controller (renaming the old one to "Legacy" or something).

That said, I'll mark it as ready for review as we can keep both paths around and/or add migration code later on. The code itself is stable and works with the current Pico OS. I just wanted to point this out before anyone decides to merge it.

**Comment by BastiaanOlij** [comment]
That is a really good point Dirk, yes if they change the interaction profile name it simply won't work anymore. Bit of a pain that it will still take some time before this is made official.

**Review by BastiaanOlij — APPROVED** [review]
These changes are sound and in theory can be merged.

We should probably wait until we receive feedback from PICO about any changes to the interaction profile as a result of it becoming an official part of the OpenXR specification.

Alternatively, as it is possible that renames of profile paths and extensions is something we could run into in the future one option would be to add logic to the extension wrappers to keep a map of old names with their new name. That could be a part of the PR changing the names if this indeed eventuates.

**Comment by BastiaanOlij** [comment]
@rsjtdrjgfuzkfg ok feedback from PICO is that they plan to have old and new interaction profile paths and extension names operating side by side for a little while.

I suggest we merge this as is and when the time comes that PICO has final names for these, I'll add something that allows us to convert old names to new names in existing action maps and we can just change everything over to the new names.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
