### PR TITLE
Miscellaneous cleanup for the Android codebase

### PR DESCRIPTION
**Pull request by m4gr3d**
Miscellaneous cleanup for the Android codebase:
- update gradle plugins versions
- add formatting rules for AndroidManifest and gradle build files
- cleanup java_godot_lib_jni

Note: logic was mostly moved around and no new logic/functionality was added.

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by m4gr3d** [comment]
@akien-mga Should I provide a separate version of this PR against the 3.2 branch?

**Comment by akien-mga** [comment]
No the `cherrypick:3.2` already means that I'll cherrypick this for the 3.2 branch when I come to it.

**Comment by akien-mga** [comment]
Actually this can't be cherry-picked easily for `3.2` currently. Maybe I missed an intermediate PR that should also be cherry-picked? Otherwise I guess a dedicated PR for 3.2 would make sense indeed.

**Comment by m4gr3d** [comment]
> Actually this can't be cherry-picked easily for `3.2` currently. Maybe I missed an intermediate PR that should also be cherry-picked? Otherwise I guess a dedicated PR for 3.2 would make sense indeed.

@akien-mga I've added PR #37300 as a dedicated PR for 3.2.

**Pull request merged**
