### PR TITLE
Add "-rigid" postfix import feature to create rigid bodies

### PR DESCRIPTION
**Pull request by jay3d**
I'm adding this pull request again after I cleaned up my fork

### CODE REVIEW

**Comment by akien-mga** [comment]
Could anyone test this feature?

**Comment by akien-mga** [comment]
@jay3d Thanks for keeping this branch up to date, but could you please use ``git pull --rebase`` to update your branch instead of simply ``git pull``? It would get rid of the 12 merge commits that were added so far :)

**Comment by jay3d** [comment]
Can it be merged now?

**Comment by akien-mga** [comment]
I fear not... Did you use ``git pull --rebase`` as I suggested? It should not have produced such a huge mess :/

**Comment by jay3d** [comment]
I used it but that what it produced, I'm not that keen on Git, I use TortoiseGit, any advises?

**Comment by akien-mga** [comment]
The simplest now would be for you to download your patch directly: https://github.com/godotengine/godot/commit/2e3ade22ff2ef155140b4fd3d70cfe29b89a06a9.patch
And reapply it in a clean git branch to make a new pull request.

**Pull request closed without merging**
