### PR TITLE
Remove COLLADA importer

### PR DESCRIPTION
**Pull request by fire**
The results of the Twitter poll largely support dropping Collada (DAE).

image

https://twitter.com/reduzio/status/1445083876729180169

If a proposal is needed, please reference removing the Collada addon proposal. https://github.com/godotengine/godot-proposals/issues/2130

### CODE REVIEW

**Comment by akien-mga** [comment]
I'll note that 3.6% of 2000 respondents (current count) is 70 users. Factoring in that most people who follow @reduz may not actively work on 3D games in Godot (and thus the 70%+ of users who voted to nuke COLLADA may not actually have confirmed personally that glTF works perfectly for their needs, because they may not have any such needs). So it's not negligible.

Still a good indicator that this may be a way forward, but we need to work with those users to ensure that the workflows for which they feel that they still need COLLADA can fully be replaced by glTF.

**Comment by fire** [comment]
I think the next steps to removing the collada importer would be on day one also have a gdextension importer for collada.

**Comment by Ansraer** [comment]
The last time I tried to export a 3D model from blender 2.8 with gltf I had some major problems. Modifiers were not always applied in the correct order, some materials were not exported properly. Even when reimporting the file with the same blender version that was used to create it things looked noticeably different.
I haven't used Blender in 2-3 months, so things might have changed, but I am not convinved that gltf on Blenders side is stable enough for production use. I would like to hear some feedback from actual blender artists before we move forward with this.

**Comment by Zireael07** [comment]
Echoing @Ansraer  - I tried gltf export from blender and it was a pain. Collada... just works.

**Comment by fire** [comment]
@Ansraer @Zireael07 If you can describe your current workflows, I can investigate the difficulties

Please describe the Blender version, the Collada versions and if possible the source art.

**Comment by aaronfranke** [comment]
If Collada is kept, perhaps it should be moved to a module?

**Comment by Zireael07** [comment]
My experience was with Blender 2.8 (I think it's 2.81), no idea how to check the Collada version. Note that the mesh I had trouble with was rigged and scaled.

**Comment by Xrayez** [comment]
> If Collada is kept, perhaps it should be moved to a module?

If this is removed and considered corner case, then I'd say it should be ok to port this to [Goost](https://goostengine.github.io/).

**Comment by fire** [comment]
PR meeting notes:

1. We can revisit dropping Collada until Godot 4.0+. We can get a better idea of the use of gltf2 and any other pipelines Godot Engine develops.
2. Delay until Collada is less used. A specific 2.79 collada pipeline using better Collada on Blender was mentioned.
3. Artists prefer having more formats in their existing workflows. For example, without Blender or (visible) gltf2 export.
4. Consensus was not had during the pr meeting and there were objections.
5. Some future looking plans for Godot asset import were discussed.

**Pull request closed without merging**
