### PR TITLE
Fix validation error when resizing window

### LINKED ISSUE #80570: Vulkan Validation Error when resizing
### Godot version

master [4714e95896c8db02616ea6ec7f9aff92dec1cae4]

### System information

Godot v4.2.dev (4714e9589) - Ubuntu 20.04.6 LTS (Focal Fossa) - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 6800 XT - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Sometimes when resizing the window on Linux X11 we may get the following validation error:

```
ERROR: VALIDATION - Message Id Number: -370888023 | Message Id Name: VUID-vkAcquireNextImageKHR-semaphore-01286
	Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01286 ] Object 0: handle = 0xdcc8fd0000000012, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0xe9e4b2a9 | vkAcquireNextImageKHR: Semaphore must not be currently signaled or in a wait state. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must be unsignaled (https://vulkan.lunarg.com/doc/view/1.2.198.1/linux/1.2-extensions/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01286)
```

I nailed down the problem. In `VulkanContext::prepare_buffers` we have the following loop (I simplified to highlight the problem):

```cpp
do {

err = fpAcquireNextImageKHR(device, w->swapchain, UINT64_MAX,
							w->image_acquired_semaphores[frame_index], VK_NULL_HANDLE, &w->current_buffer);

if (err == VK_SUBOPTIMAL_KHR) {
	// Swapchain is not as optimal as it could be, but the platform's
	// presentation engine will still present the image correctly.
	print_verbose("Vulkan: Early suboptimal swapchain, recreating.");
	Error swap_chain_err = _update_swap_chain(w);
	if (swap_chain_err == ERR_SKIP) {
		break;
	}
} while (err != VK_SUCCESS);
```

The problem is that vkAcquireNextImageKHR returned VK_SUBOPTIMAL_KHR but it already signaled the semaphore (because it is possible to continue normally with a VK_SUBOPTIMAL_KHR result).

Then we recreate the swapchain and reuse the w->image_acquired_semaphores[frame_index] which is in an inconsistent state.

I will handle this bug.

### Steps to reproduce

1. Open the Editor on any project
2. Resize the project until it happens

Reproducibility is much more frequent after applying PR #80566

### Minimal reproduction project

Any.

### PR DESCRIPTION
**Pull request by darksylinc**
Sometimes when resizing the window we may get the following validation error:

```
ERROR: VALIDATION - Message Id Number: -370888023 | Message Id Name: VUID-vkAcquireNextImageKHR-semaphore-01286
	Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01286 ]
Object 0: handle = 0xdcc8fd0000000012, type = VK_OBJECT_TYPE_SEMAPHORE; | MessageID = 0xe9e4b2a9 | vkAcquireNextImageKHR: Semaphore must not be currently signaled or in a wait state. The Vulkan spec states: If semaphore is not VK_NULL_HANDLE it must be unsignaled (https://vulkan.lunarg.com/doc/view/1.2.198.1/linux/1.2-extensions/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01286)
```

In VulkanContext::prepare_buffers the problem was that vkAcquireNextImageKHR returned VK_SUBOPTIMAL_KHR but it already signaled the semaphore (because it is possible to continue normally with a VK_SUBOPTIMAL_KHR result).

Then we recreate the swapchain and reuse the
w->image_acquired_semaphores[frame_index] which is in an inconsistent state.

Fixed by recreating the semamphores along the swapchain.

Fix #80570

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
I'm not sure how to judge this as I've not dived deep enough into this part of the Vulkan API so I'm not sure if there is a better way to do this, but I'm happy for this to be merged.

I would add a remark in the code why we're recreating the semaphores because someone looking at this code later on isn't going to get the why and might break this again.

**Comment by darksylinc** [comment]
Good point.

Done. I've updated the code with a comment explaining why we destroy the semaphore.

**Review by clayjohn — APPROVED** [review]
The change makes sense to me. I've wondered for awhile if we needed more careful handling of the swapchain semaphore upon recreating the swap chain. This just confirms my suspicions

**Comment by akien-mga** [comment]
Looks good! Could you squash the commits? We usually keep tightly related changes in the same commit, such as here adding context to the change in the first commit (and we don't use the Squash on Merge strategy for a number of reasons, we prefer the history to be final in the PR itself).

**Comment by darksylinc** [comment]
> Looks good! Could you squash the commits? 

Done.

**Pull request merged**
