### PR TITLE
Add unit tests for CryptoKey

### PR DESCRIPTION
**Pull request by atlas-wheatear**
Further to #43440, this Pull Request adds three unit tests for `CryptoKey`.

> CryptoKey Load and save a .key file.

These concern a `CryptoKey` instance that has loaded in the attached private key, namely `tests/data/crypto/in.key`:

- `load()` a private key implies **not** `is_public_only()`
- default `save()` leads to identical file contents as `tests/data/crypto/in.key`, since they are the same private key
- `save()` with `public_only` set to `true` leads to identical contents as the separately prepared public key, namely `tests/data/crypto/in.pub`

### CODE REVIEW

**Comment by atlas-wheatear** [comment]
My apologies, there was a careless error in 78193af , involving a file being compared to itself.

**Comment by wheatear-dev** [comment]
Sorry - I'm managed to lock myself out of the [original account](https://github.com/atlas-wheatear) 😓 

This is it's successor, on the same email address as before.

If that's too complex, please close this PR, and I will gladly open another in the new account's name.

**Comment by Faless** [comment]
Since CryptoKey is implemented by the mbedTLS module (core come with the interface, but no implementation), we might want to move the tests there, since they would all fail when `module_mbedtls_enabled=no`

**Comment by wheatear-dev** [comment]
@Calinou please could you close this PR?

I can't do it myself, because it was created by my irrecoverable account, nor can I implement the suggestions.

I will open a duplicated one at the weekend, in this new accounts name, and link it to this one.

@AThousandShips @Faless - sorry, you both gave really helpful comments - they won't be in vain!

**Pull request closed without merging**
