### PR TITLE
Don't show progress bar for "save scene" < 1s

### PR DESCRIPTION
**Pull request by ghost**
`EditorNode::_save_scene_with_preview` currently takes about 500 ms on my iMac (optimized build).

About 40% of that time is spent in ui code (displaying the progress bar and handling other ui events in `Main::iteration()`). If I disable the progress bar display during save, the time goes down to about 320 ms.

So I suggest hiding the progress bar if the save takes less than 1s, since:

(a) on many systems, the save progress bar is merely a flicker (like 100 ms) and a bit annoying IMHO
(b) showing the progress bar substantially increases the save scene time, and as such the time to start the runner during game development
(c) the save progress bar cannot be cancelled and so there is nothing lost if the ui gets unresponsive during save for up to 1s

Here are some concrete measurements of `EditorNode::_save_scene_with_preview` in milliseconds. Before the change:

```
_save_scene_with_preview 549
_save_scene_with_preview 514
_save_scene_with_preview 485
_save_scene_with_preview 481
_save_scene_with_preview 538
_save_scene_with_preview 474
_save_scene_with_preview 470
_save_scene_with_preview 456
_save_scene_with_preview 538
```

After the change:

```
_save_scene_with_preview 353
_save_scene_with_preview 324
_save_scene_with_preview 308
_save_scene_with_preview 345
_save_scene_with_preview 321
_save_scene_with_preview 306
_save_scene_with_preview 332
```

This PR checks on each progress step if 1s has passed; if not, the progress bar is not yet shown. It's only affecting scene save. All other progress bars still default to "show immediately" (current behavior).

### CODE REVIEW

**Comment by reduz** [comment]
Not going to remove the progress bar for just 100ms...

**Comment by poke1024** [comment]
Changed the PR's title as its original wording only talks about performance and is thus missing the main point.

Should a progress indicator be shown for a save operation needing < 1 s? I think no. The common UI/UX lore is to show progress bars for operations >= 1 s:

- https://msdn.microsoft.com/en-us/library/windows/desktop/dn742481(v=vs.85).aspx: "Use an activity indicator when an action can't be performed within a second"
- Jakob Nielsen: https://www.nngroup.com/articles/response-times-3-important-limits/: "Normally, no special feedback is necessary during delays of more than 0.1 but less than 1.0 second"

**Comment by hpvb** [comment]
This makes sense to me, with the new explanation.

**Comment by letheed** [comment]
Personally, I like having the visual feedback when I save.

**Comment by mhilbrunner** [comment]
Having a progress bar for sub-second actions seems not useful, IMO.

**Comment by codingHahn** [comment]
@reduz What do you think about it now with the new explanation?

**Comment by reduz** [comment]
You can't tell in advance how long a scene will take to save, and for a few milliseconds this is not worth it.  If many of you for some bizarre option don't like this dialog, we could make it optionally disabled but it won't go away.

**Comment by star-tek-mb** [comment]
No need for this hack. Keep code simplier.

**Comment by poke1024** [comment]
Changed this into an editor setting currently called "Show Progress Bar For Longer Tasks Only". It's disabled by default. If you enable it, the progress bar will only show after 1s; we might have to fine tune this for some operations that call the progress update/main iteration very seldom.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by akien-mga** [comment]
For the reference, I don't think this should be an editor setting. The answer to a lack of consensus should not always be "let's make it an option".

**Comment by reduz** [comment]
Closing, because I don't think this will work as intended in practice.

**Pull request closed without merging**
