### PR TITLE
Add editor icons for X509Certificate and CryptoKey

### PR DESCRIPTION
**Pull request by Calinou**
The X509Certificate icon is slightly rounded and rotated for better rendering on loDPI displays. I tried embedding it into a document icon, but it simply looked too small for the "spikes" to be recognizable.

cc @Faless

## Preview

Icons

<details>
<summary>Old version</summary>

icon_crypto_key

icon_x509_certificate
</details>

### CODE REVIEW

**Comment by bruvzg** [comment]
Most certificate icons are'n that spiky. This one looks more like a star not like a seal.

cert

Icon with a document and more round seal would be more recognizable.

Maybe something like this: cert2

**Comment by bruvzg** [comment]
> Alternatively, we can make the icons solid and use a mask to separate solid objects, as is already done with some icons.

We can add extra colour (like font resource icons do), make seal read/blue for example:

cert4

```svg
<svg xmlns="http://www.w3.org/2000/svg" height="16" viewBox="0 0 4.233 4.233" width="16"><path d="M3.967.263L.263.264V2.91H1.69a.993.993 0 0 1-.022-.096.993.993 0 0 1-.012-.099.993.993 0 0 1-.002-.07.993.993 0 0 1 .005-.1.993.993 0 0 1 .014-.097.993.993 0 0 1 .025-.096.993.993 0 0 1 .034-.093.993.993 0 0 1 .043-.09.993.993 0 0 1 .052-.085.993.993 0 0 1 .06-.079.993.993 0 0 1 .068-.072.993.993 0 0 1 .074-.066.993.993 0 0 1 .08-.057.993.993 0 0 1 .087-.05.993.993 0 0 1 .09-.04.993.993 0 0 1 .095-.031.993.993 0 0 1 .096-.022.993.993 0 0 1 .099-.012.993.993 0 0 1 .07-.003.993.993 0 0 1 .099.006.993.993 0 0 1 .098.014.993.993 0 0 1 .096.025.993.993 0 0 1 .094.034.993.993 0 0 1 .089.043.993.993 0 0 1 .084.052.993.993 0 0 1 .08.06.993.993 0 0 1 .072.068.993.993 0 0 1 .065.074.993.993 0 0 1 .058.08.993.993 0 0 1 .05.087.993.993 0 0 1 .04.09.993.993 0 0 1 .031.095.993.993 0 0 1 .022.096.993.993 0 0 1 .012.099.993.993 0 0 1 .002.07.993.993 0 0 1-.004.1.993.993 0 0 1-.015.097.993.993 0 0 1-.017.068h.365V.263z" fill="#e0e0e0"/><path d="M2.116 3.175v.793l.53-.253.529.253v-.793z" fill="#ff8484"/><circle cx="2.646" cy="2.645" r=".794" fill="#ff8484"/></svg>
```

Or maybe keep just a bigger seal but add coloured ribbon under it.

**Comment by Calinou** [comment]
These look great! Could you include both SVGs in your post, please? I'll add you as a co-author :slightly_smiling_face:

**Comment by bruvzg** [comment]
> These look great! Could you include both SVGs in your post, please?
 
Done, both are in the previous comment.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
