### PR TITLE
Add symlink API support for Windows, expose symlink methods.

### PR DESCRIPTION
**Pull request by bruvzg**
Note: `create_link` require evelated privilegies or [Developer Mode](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development) enabled.

### CODE REVIEW

**Comment by Calinou** [comment]
> Adding create_link is possible, but in most cases it required admin privileges, so it won't be useful for most apps.

I thought this wasn't required anymore since Windows 10 when using actual symlinks (as opposed to junctions).

**Comment by bruvzg** [comment]
Maybe I'm wrong and was confused by the two-panel manager (FAR) I usually use on Windows, which still asks for admin permissions when creating symlinks. I'll check it and make a follow up if it's no longer required.

**Comment by bruvzg** [comment]
> I thought this wasn't required anymore since Windows 10 when using actual symlinks (as opposed to junctions).

No, seems like on Windows 10 and 11 it works if without elevation only if Developer mode is enabled. But will add it anyway.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
