### PR TITLE
implement individual mesh transform for meshlibrary items

### LINKED ISSUE #1716: Allow offsetting built in mesh types
**Describe the project you are working on:**
3D Roguelike

**Describe the problem or limitation you are having in your project:**
I need to offset cubes by half a unit for gridmaps

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
I was wondering of a offset parameter could be added to meshes so that we can offset the vertices for gridmaps

this issue covered it but was closed due to a fix that didn't fix the issue  [#24602](https://github.com/godotengine/godot/issues/24602)

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
something like size which is a vector3 under the mesh properties but for vertices offsets 

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
it would mostly be used for gridmaps and yes through a script but we shouldn't need to attach a script to every mesh just to offset it because gridmaps don't respect position

**Is there a reason why this should be core and not an add-on in the asset library
its useful to easily be able to create block based 3d maps

### LINKED ISSUE #35860: Gridmap doesn't import meshlib item transform and doesn't allow edit
**Godot version:**
3.2

**OS/device including version:**
Win10

**Issue description:**
I make a brand new meshlib, 1 single item. When editing meshlib.tscn, I set item scale to 10,10,10, then export to meshlib.meshlib
Now I create new gridmap node, where I link meshlib.meshlib.: item scale has been lost.
I try to set manually, the inspector always reset to default.

[mrpMeshlib.zip](https://github.com/godotengine/godot/files/4145279/mrpMeshlib.zip)

**Steps to reproduce:**

open mrpMeshlib.zip in godot, open spatial.tscn, select gridmap, select meshlib, select item 1, try to change transform.

### PR DESCRIPTION
**Pull request by DeleteSystem32**
This change implements the existing "Mesh Transform" property for the MeshLibrary resource, adressing issue #35860

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/1716.*
Closes #35860.

EDIT: In addition to manual editing, this PR now also includes options to apply the transforms when converting from a scene.

### CODE REVIEW

**Comment by akien-mga** [comment]
I've tested this on `3.x` (cherry-picked to my fork here: https://github.com/akien-mga/godot/tree/3.x-meshlib-transform), it seems to work well :+1: 

I'm pretty new to using GridMaps but I ran into this limitation right away so I'm glad we're improving this.

Workflow wise, I'm not sure I'm fully happy with what we have even after this PR though, as there's still a lot of manual work needed to edit the MeshLibrary after conversion, unless I missed something obvious. For example, the MeshInstance transforms from my source scene are not included in the MeshLibrary resource; I need to redefine them manually in the resource.

Also (not related to this PR but it's another similar workflow issue), some material properties seem not to be properly included in the MeshLibrary resource (in my case, disabled Cull Mode).

This might warrant a dedicated proposal though, I'm just documented this here so that other GridMap users can confirm that as of this PR, manual edition of the MeshLibrary would still be required.

**Review by akien-mga — APPROVED** [review]
Tested via a `3.x` cherry-pick, works well :+1:

**Comment by akien-mga** [comment]
> Also (not related to this PR but it's another similar workflow issue), some material properties seem not to be properly included in the MeshLibrary resource (in my case, disabled Cull Mode).

Actually this is a different issue, it seems the Cull Mode does get included properly when converting to MeshLibrary. It's just an issue with edited MeshLibrary resources not properly getting reloaded in the editor, one needs to restart the editor to see the changes (another bug to file).

So it does seem that it could be expected for the "Convert to MeshLibrary" action to also bake the MeshInstance's transform into the MeshLibrary, so that it doesn't need to be redone manually. WDYT?

**Comment by DeleteSystem32** [comment]
> It's worth noting that users might be changing the _position_ of their MeshInstances in the source scene for cosmetic purposes, to avoid having everything crammed on origin. If we bake the position in the MeshLibrary, this might be problematic for some. But at the same time, one can use Spatial/Node3D nodes for this cosmetic positioning, and keep the MeshInstance transform strictly for things which should be included in the MeshLibrary. Both workflows can be seen as valid so if implemented, this could be made into a checkbox in the "Convert to MeshLibrary" dialog.

I 100% agree, but wasn't entirely sure how best to implement it. Looking at the code of the importer now, it is already setup to allow each MeshInstance to have a different parent - so I'd agree that using that as a cosmetic intermediate could work well. I'll get on that ASAP.

**Comment by akien-mga** [comment]
> I 100% agree, but wasn't entirely sure how best to implement it. Looking at the code of the importer now, it is already setup to allow each MeshInstance to have a different parent - so I'd agree that using that as a cosmetic intermediate could work well. I'll get on that ASAP.

That sounds great! For compatibility's sake, I would suggest adding a checkbox in the convert dialog (next to "Merge With Existing") to allow toggling off this new behavior. I can imagine that some users might have pretty big mesh libraries where they don't want the transform baked into the MeshLibrary. I'd make it opt-out (enabled by default) though as it's the better workflow for new users IMO.

**Comment by DeleteSystem32** [comment]
> That sounds great! For compatibility's sake, I would suggest adding a checkbox in the convert dialog (next to "Merge With Existing") to allow toggling off this new behavior.

Yep, that's how I'm handling it. However, this menu here is currently causing me some headache 
image

I'm making it so that, if you chose "Import from Scene (Apply Transforms)" for that MeshLibrary, then "Update from Scene" will always automatically include the transforms, but I'm not entirely sure that's the right approach.

**Comment by akien-mga** [comment]
> I'm making it so that, if you chose "Import from Scene (Apply Transforms)" for that MeshLibrary, then "Update from Scene" will always automatically include the transforms, but I'm not entirely sure that's the right approach.

Ah I never used that menu, I usually use the "Convert to MeshLibrary" option instead of doing it the other way around.

Maybe the "Update from Scene" dialog could have two OK buttons, one to apply with and one without transforms:

Screenshot_20210907_121256

**Comment by DeleteSystem32** [comment]
> Or a checkbox in the dialog. Leaving it as a decision on update might be simpler than saving in some project metadata that the original import was done with or without transforms -- though this seems to already rely on saving some information on what the source scene was, so that could be saved alongside it.

I went with the metadata approach in the latest commit. It works, but I think I'll add a checkbox to the Update dialog anyway to make things clearer.

**Review by akien-mga — APPROVED** [review]
Tested the new version, works great!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by DeleteSystem32** [comment]
> 
> 
> Cherry-picked for 3.4.

I actually have a 3.x branch of this that should be about ready to go, should I just go ahead and put in a seperate PR?

**Comment by elvisish** [comment]
Does this offset the child collision shape transforms too? I'm using built-in MeshInstances and need these shorter blocks to be aligned to the floor:
image
Also, is there a way to do this in the MeshLibrary export? Cause when I re-save the transforms are all lost.

**Pull request merged**
