### PR TITLE
TextureRegion improvements

### PR DESCRIPTION
**Pull request by MarianoGnu**
- Edit region and patch9/skylebox margins at the same time.
- Add Separation field to grid options.
- Smart Auto-Slice sprites in usefull frames.
- Move editor to BottomSplit
- **Note:** Adds "texture_changed" signal to Sprite, Patch9Frame and StyleBoxImage

**Showcase video:**
https://www.youtube.com/watch?v=A_bRJPLZHYs

### CODE REVIEW

**Comment by djrm** [comment]
this is very cool

**Comment by MarianoGnu** [comment]
Looks like there's conflics regarded to AtlasTexture editiong, since the Edition method has changed i propose resolve the conflict removing this implementation and add it again latter...

**Comment by MarianoGnu** [comment]
@reduz This needs some discussion before merging i supose.

**Comment by akien-mga** [comment]
@MarianoGnu I would prefer if you could rebase your two commits on top of the current master branch instead of partially reverting @Geequlim's additions to solve the merge conflicts.

**Comment by MarianoGnu** [comment]
Mmm problem is that i never used AtlaTexture and have not idea of how to use/edit it. Also not good at rebasing, might freak up my branch. Help is welcome if you can gide me on IRC

**Comment by akien-mga** [comment]
- Starting by making a copy of your commits in case you freak up your branch ;) `git format-patch -1 HEAD~3` (or make a clone of your branch)
- Drop your bad merge commit (the third one) with `git rebase -i HEAD~3` (remove the 3rd line)
- Rebase your branch on top of the upstream master branch:
```
git remote add upstream https://github.com/godotengine/godot
git pull --rebase upstream master
```
- Git will yell at you due to merge conflicts. Don't panic :)
- Check the `git status` and `git diff`, it will show you which files are conflicting with your changes in your first commit. Open those files in your text editor, and edit them to solve the conflict properly: you should thus keep the code present in HEAD, and add it to your own changes. Make sure to remove the `<<<<<<<<<<<<` and `>>>>>>>>>>>>` lines which delimit the conflicting snippets.
- Once you're done, check `git diff` to be sure, and then run `git commit` to commit the resolved conflict (it will be integrated directly in your own commit)
- Continue the rebase with ``git rebase --continue``.
- Repeat the above steps for the 2nd commit if it's also conflicting.
- Check the `git log`, `git show` your commits, and bask in glory before doing a force push.

**Comment by Geequlim** [comment]
Pretty good!
As you moved the region editor to the bottom split. How to preview the StyleBoxTexture when selecting regions?

**Comment by MarianoGnu** [comment]
Right now, switching controls or moving around a control in the scene as i did in the video. A preview could be added to the same editor since there's plenty of space...

@Geequlim any hint about how AtlasTextures work?

**Comment by Geequlim** [comment]
I don't think there are more differences between AtlasTexture and Sprit here.
Maybe you can take look at #5138

**Comment by MarianoGnu** [comment]
@akien-mga whenever i make a pull rebase lots of my code desapears, like in a previous version :/

**Comment by vnen** [comment]
@MarianoGnu if you are rebasing many commits, it will replay the deltas one by one, so if it finds a conflict it will stop before the commit and let you resolve it manually. So you just need to fix the conflicts, `git add` the file and `git rebase --continue` so it can replay the next commits. (@akien-mga said to `git commit` the file, but you really just need to `git add` to resolve the conflict)

**Comment by MarianoGnu** [comment]
I finished merging changes and trayiung to make it work again...

**Comment by MarianoGnu** [comment]
@akien-mga everything should work now, take a look...

**Comment by akien-mga** [comment]
I haven't reviewed thoroughly, but I trust you to fix any potential issue before 2.1 anyway :D

**Pull request merged**
