### PR TITLE
Popup fixes for X11 display server

### LINKED ISSUE #37674: Tooltip renders under window
**Godot version:** 4.0 branch, commit 1222541c95

**OS/device including version:**
Linux Mint 19.3, kernel 5.3.0-45, Cinnamon

**Issue description:**
As title says. I just thought they weren't showing up at all until I unmaximized the screen. Happens with both system tooltips and Godot-styled ones.

**Steps to reproduce:**
Just compile and run a new project. Didn't make any changes to the default settings.

### LINKED ISSUE #41578: Editor Menus and Text Entry Boxes Appear at Origin
**Godot version:**
master v4.0.dev.custom_build.1ff139cb2

**OS/device including version:**
OS: Archlinux, AMD ryzen integrated graphics, mesa driver
Window manager: Openbox (only)

**Issue description:**

All of the editor's popups appear at origin (upper left), though they tile, to make room for more. The first screenshot shows tabbing through the rectangle entries in a textrectangle. The second just shows the help menu opening in the wrong place. Submenus will open up below the menu.

2020-08-28-051924_1920x1080_scrot

2020-08-28-052000_1920x1080_scrot

2020-08-28-053518_1920x1080_scrot

**Steps to reproduce:**

**Minimal reproduction project:**

Edited for form.

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
This PR fixes some issues with popups showing with a delay on linux, and also does a few general changes in how Popup nodes are handling focus changes.

Also fixes #37674, fixes #41578

**Re-apply "Fixes for windows in X11 tiling WMs"**
From PR #38727 by @Riteo which was reverted in #41373 because of regressions in Ubuntu with Gnome.
Regressions are now fixed with the other popup changes in this PR.

**Fix popup closed when an ancestor window is focused**
This is a general change for `Popup` which fixes issues that affect all platforms.

Previously, only the direct parent were taken into account.

Popups like contextual menus could stay open if an ancestor which is not a direct parent was focused.

Reproduction steps (any platform):
- Select a node in the scene tree
- Left click the node to start renaming
- Right click to open the copy/paste contextual menu
- Left click in the scene tree to deselect the node

Also closing popup when focusing out of the application, without waiting for the parent to get focus to do so.

**Fix menu popups delay and focus in X11 display server**
This is a fix for a linux specific issue with popups. Contextual menus, top bar menus and editable properties were showing with a delay due to some extra time to be initialized in the windows manager.

Now using `override_redirect` for all utility popups to prevent the WM from interfering with them, so we have more control over focus management and avoid a delay before they show up.

**Fix WINDOW_EVENT_FOCUS_IN for popups on Windows**
This is a fix for Windows, needed because of the changes in `Popup` in this PR.
On Windows, `WINDOW_EVENT_FOCUS_IN` was never sent by the display server for popups, because `WM_ACTIVATE` events are received during the call to `_update_window_style`, which happened before the callbacks were set.

This was causing some issues with the way `Popup` is now handling closing on parent focus.

Now `_update_window_style` is only called during show_window, after Window initialized callbacks.

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
Pushed some modifications in X11 display server to solve some focus issues with XFCE, along with code cleaning and extra comments.

**Comment by pouleyKetchoupp** [comment]
Extra tests with a tiling WM:
Tested with i3, popups are still on the right position and size (fix from #38727) and focus works correctly.
With i3 it also freezes for a few seconds for me when any window opens, or when switching the focus from and to the editor. I'm not sure what is causing it, but it seems unrelated to this PR since I experience the same thing on latest master.

**Comment by Riteo** [comment]
I can confirm freezing on i3 too.

**Comment by pouleyKetchoupp** [comment]
@Riteo Thanks for checking. Were you experiencing it before? I can reproduce it on latest master, but I'm not sure if it's a recent issue.

**Comment by Riteo** [comment]
Why not bisecting this issue? Soon I should be able to do that.

**Comment by Riteo** [comment]
After a lot of tests, I couldn't pinpoint the exact reason of the freeze.
Bisecting doesn't seem to work, as even commit d670a49612(from PR #38727, which I used a lot) freezes now.

As of now I tried on Arch Linux with i3 running a build of commit d670a49612 to:
 - Turn on the debugging log on i3, which gave some strange output(even though I could not find a pattern behind it at first glance) on which I'll probably investigate later on.
But it worked before and thus, since the only big factor that I could think of would be a system update, something must have changed somewhere else(Maybe some unwanted behaviour change in some X related package after an update?).
 - Roll back `i3-wm` to 4.18.1-1, `xorg-server-*` to 1.20.8-2 and `libx11` to 1.6.9-7, which are the oldest versions of those packages which i could find in my pacman cache.
 - Compile Godot with both target `debug` and `release_debug`

Other things to try would be running Godot on other tiling WMs, rolling back any other possibly related package and maybe debugging any weird output on i3's debug log(thing which I'll try to do as soon as I can, but lately I'm getting very slowed down due to personal reasons).

Still, I'm reading a lot of X11 documentation and questioning some choices done in the X11 DisplayServer implementation, thing which I would like to discuss eventually on IRC with @reduz and whoever worked on it(I really don't want to sound rude, there is surely some technical reason behind those choices and I would like to know why some things are made in a certain way in order to contribute with code that doesn't go against them).

It's 4 AM here and I'm very tired so I think that I'll stop for now.

**Comment by pouleyKetchoupp** [comment]
Thanks for all the info.

I'm currently contracting to work on the X11 display server, so I'm responsible for this topic. We can talk about your concerns directly, either here or on IRC.

About the freezing issues with i3, I've added it to my list but it's on a lower priority for me since the goal is to first make the display server work correctly with standard WMs.

**Comment by Meriipu** [comment]
https://github.com/godotengine/godot/issues/40024 this is an issue on ctwm (and probably twm too), although it has not been introduced by this PR. It may still be related since it was introduced with the 4.0 changes to popups.

Godot either
* does not properly make exclusive windows always on top, impossible to lower, and the parent uninteractible (like thunar does with `Help>About`)
* annoyingly raises the child window a few split seconds after the parent has been raised, instead of not doing anything to change window stacking beyond possibly disallowing input to the parent while the child is open.

**Comment by Riteo** [comment]
I think we should make a separate issue for this freezing, as it doesn't seem related to this PR.
I'm still investigating about it though, with some very interesting results.

>I'm currently contracting to work on the X11 display server, so I'm responsible for this topic. We can talk about your concerns directly, either here or on IRC.

@pouleyKetchoupp I would like to not go too much off topic on this PR page, but this weekend i should be a little more free, maybe we could talk about it then on IRC?

> It may still be related since it was introduced with the 4.0 changes to popups.

@Meriipu I don't think so, since this freezing issue started arising only very recently, at least only on i3.

**Comment by pouleyKetchoupp** [comment]
@Riteo I've just opened a separate issue for the freezing in i3.
Unfortunately, I personally won't be available on IRC this weekend but I'll be available the next one or anytime during the week. You can still talk about it with other devs if you want to of course and I can check the logs later.

**Comment by duane-r** [comment]
This seems to work perfectly on openbox (archlinux).

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
