### PR TITLE
Rename Input::warp_mouse_pos() to set_mouse_position()

### PR DESCRIPTION
**Pull request by RandomShaper**
- `pos` -> `position` to meet the new naming conventions;
- `warp` -> `set` because `warp` can be confused with that from `warp_mouse_motion`, with a different meaning; also this name is clearer.

Also `Viewport:warp_mouse()` to `set_mouse_position()`; a bit more verbose but for coherency.

### CODE REVIEW

**Comment by RandomShaper** [comment]
No, this is not right.

There is a conflict now because there are two methods named the same. If we could find a way of getting rid of the current `set_mouse_position()` or `warp_mouse_pos()`, that'd be great.

The API would be clearer. Maybe one may (and even should) call the other one in turn. Opinions?

**Comment by karroffel** [comment]
Looks good, but iron out the build errors first 😉

**Comment by akien-mga** [comment]
What are the two `set_mouse_position`s?

**Comment by RandomShaper** [comment]
The original Input::set_mouse_position() changes the mouse position Godot
is aware of in terms of input handling and also relocates the custom mouse
cursor in the rasterizer, in case one is set.

The other method is Input::warp_mouse_pos() and that one just calls the
homonimous method in OS.

The latter could be removed, but set_mouse_position() would still be
something different from the OS's warp_mouse_pos(). Therefore, unless it
makes sense to mix them somehow, I no longer see reasons for renaming
beyond 'pos' -> 'position'.

But that would keep the possible confusion between warp_mouse_motion() and
set_mouse_position(). Or isn't there actually any confusion potential and I
am overthinking this?

**Comment by Hinsbart** [comment]
Mhh, iirc the current custom mouse cursor implementation will be deprecated, in favor of changing the os hardware-cursor image. When that's done I guess we can just keep `warp_mouse_pos`, and then the renaming makes sense ^^

**Comment by reduz** [comment]
Need volunteers for this :P It's quite some work

**Comment by akien-mga** [comment]
> Therefore, unless it makes sense to mix them somehow, I no longer see reasons for renaming beyond 'pos' -> 'position'.

Let's go with this for now maybe, plus making sure the documentation for the two Input methods is clear on their difference?

**Comment by RandomShaper** [comment]
Yes, let's keep this as it is now until true changes are introduced.

**Pull request closed without merging**
