### PR TITLE
Removed unnecessary assignments

### PR DESCRIPTION
**Pull request by Rubonnek**
After scanning the `master` branch again with `cppcheck` I noticed a couple of unnecessary assignments.

This pull request definitely needs a couple more eyes. I'm not familiar with all the code I've modified.

```
# Fixed
[core/math/aabb.cpp:248]: (style) Variable 'max_size' is assigned a value that is never used.
[core/math/aabb.cpp:265]: (style) Variable 'max_size' is assigned a value that is never used.
[core/math/aabb.cpp:283]: (style) Variable 'max_size' is assigned a value that is never used.
[core/math/aabb.cpp:300]: (style) Variable 'max_size' is assigned a value that is never used.
[core/math/bsp_tree.cpp:247]: (style) Variable 'plane_count' is assigned a value that is never used.
[core/math/bsp_tree.cpp:276]: (style) Variable 'steps' is modified but its new value is never used.
[core/math/bsp_tree.cpp:262]: (style) Variable 'plane' is assigned a value that is never used.
[drivers/gles2/rasterizer_canvas_gles2.cpp:198]: (style) Variable 'buffer_ofs' is assigned a value that is never used.
[drivers/gles3/rasterizer_canvas_gles3.cpp:330]: (style) Variable 'buffer_ofs' is assigned a value that is never used.
[drivers/gles3/rasterizer_canvas_gles3.cpp:382]: (style) Variable 'buffer_ofs' is assigned a value that is never used.
[drivers/gles3/rasterizer_scene_gles3.cpp:2970]: (style) Variable 'contrib' is assigned a value that is never used.
[drivers/gles3/shader_gles3.cpp:253]: (style) Variable 'define_line_ofs' is modified but its new value is never used.
[drivers/pulseaudio/audio_driver_pulseaudio.cpp:81]: (style) Variable 'state' is assigned a value that is never used.
[drivers/xaudio2/audio_driver_xaudio2.cpp:100]: (style) Variable 'usdelay' is assigned a value that is never used.
[editor/editor_node.cpp:150]: (style) Variable 'current' is assigned a value that is never used.
[editor/editor_settings.cpp:1375]: (style) struct member 'ShortCutMapping::path' is never used.
[editor/editor_settings.cpp:1376]: (style) struct member 'ShortCutMapping::keycode' is never used.
[editor/plugins/script_editor_plugin.cpp:2214]: (style) Variable 'eh' is assigned a value that is never used.
[modules/gdnative/nativescript/api_generator.cpp:113]: (style) struct member 'ClassAPI::is_creatable' is never used.
[modules/mono/editor/bindings_generator.cpp:1494]: (style) Variable 'tools_sequence' is assigned a value that is never used.
[modules/mono/editor/godotsharp_builds.cpp:81]: (style) Variable 'build_tool' is assigned a value that is never used.
[modules/websocket/emws_client.cpp:67]: (style) Variable 'i' is assigned a value that is never used.
[platform/android/audio_driver_opensl.cpp:192]: (style) Variable 'required' is assigned a value that is never used.
[platform/android/audio_driver_opensl.cpp:193]: (style) Variable 'iidArray' is assigned a value that is never used.
[platform/android/dir_access_jandroid.cpp:156]: (style) Variable 'env' is assigned a value that is never used.
[platform/android/export/export.cpp:535]: (style) Variable 'start_pos' is assigned a value that is never used.
[platform/android/java_glue.cpp:891]: (style) Variable 'use_apk_expansion' is assigned a value that is never used.
[platform/android/thread_jandroid.cpp:135]: (style) Variable 'status' is assigned a value that is never used.
[platform/iphone/export/export.cpp:814]: (style) Variable 'is_execute' is assigned a value that is never used.
[platform/javascript/os_javascript.cpp:191]: (style) Variable 'os' is assigned a value that is never used.
[scene/2d/line_builder.cpp:293]: (style) Variable 'uvx0' is assigned a value that is never used.
[scene/2d/parallax_layer.cpp:123]: (style) Variable 'before' is assigned a value that is never used.
[scene/3d/light.cpp:171]: (style) Variable 'editor_ok' is assigned a value that is never used.
[scene/3d/light.cpp:166]: (style) Variable 'editor_ok' is assigned a value that is never used.
[scene/3d/vehicle_body.cpp:677]: (style) Variable 'numWheelsOnGround' is modified but its new value is never used.
[scene/3d/voxel_light_baker.cpp:2354]: (style) Variable 'vtx_idx' is modified but its new value is never used.
[scene/gui/split_container.cpp:38]: (style) struct member '_MinSizeCache::min_size' is never used.
[scene/gui/split_container.cpp:39]: (style) struct member '_MinSizeCache::will_stretch' is never used.
[scene/gui/split_container.cpp:40]: (style) struct member '_MinSizeCache::final_size' is never used.
[scene/gui/text_edit.cpp:303]: (style) Variable 'num_rows' is assigned a value that is never used.
[scene/resources/mesh.cpp:1190]: (style) Variable 'vertex_idx' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:105]: (style) Variable 'v2' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:106]: (style) Variable 'v3' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:107]: (style) Variable 'v4' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:108]: (style) Variable 'v5' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:109]: (style) Variable 'v0n' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:110]: (style) Variable 'v1n' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:111]: (style) Variable 'v2n' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:112]: (style) Variable 'v3n' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:113]: (style) Variable 'v4n' is assigned a value that is never used.
[servers/audio/audio_rb_resampler.cpp:114]: (style) Variable 'v5n' is assigned a value that is never used.
[servers/physics/collision_solver_sat.cpp:236]: (style) Variable 'added' is modified but its new value is never used.
[servers/physics/step_sw.cpp:289]: (style) Variable 'profile_begtime' is assigned a value that is never used.
[servers/visual_server.cpp:232]: (style) Variable 'vtx_idx' is modified but its new value is never used.

# Possible False Positives -- these prompted changes member variables that would likely end up in bugs. These were not touched:
[editor/editor_settings.cpp:1077]: (style) Variable 'hints' is assigned a value that is never used.
[editor/file_type_cache.cpp:53]: (style) Variable 'file_type_map' is assigned a value that is never used.
[editor/progress_dialog.cpp:126]: (style) Variable 'updates' is assigned a value that is never used.
[modules/dds/texture_loader_dds.cpp:68]: (style) struct member 'DDSFormatInfo::name' is never used.
[scene/resources/dynamic_font.cpp:212]: (style) Variable 'error' is assigned a value that is never used.
```

### CODE REVIEW

**Comment by donkeybonks** [comment]
Can you setup some kind of lint pass in CI so that these are caught automatically?

**Comment by Rubonnek** [comment]
I already installed the `git` [pre-commit hook](http://docs.godotengine.org/en/3.0/community/contributing/code_style_guidelines.html#pre-commit-hook) in my machine.

Not sure why this one wasn't caught. I'll apply it manually.

**Comment by Rubonnek** [comment]
Seems clang-format version 6.0.0 differs from the one used by Travis:

I'm getting the following patch by the pre-commit hook after I applied what Travis showed in its log:

```
Running hook: pre-commit-clang-format

The following differences were found between the code to commit and the clang-format rules:

--- a/scene/3d/voxel_light_baker.cpp    2018-03-25 20:40:13.299942808 -0400
+++ b/scene/3d/voxel_light_baker.cpp    2018-03-25 20:40:21.413001314 -0400
@@ -113,7 +113,7 @@
        rad = fa * boxhalfsize.x + fb * boxhalfsize.z; \
        if (min > rad || max < -rad) return false;
 
-       /*======================== Z-tests ========================*/
+/*======================== Z-tests ========================*/
 
 #define AXISTEST_Z12(a, b, fa, fb)                 \
        p1 = a * v1.x - b * v1.y;                      \
@@ -1961,7 +1961,7 @@
 #endif
                        for (int i = 0; i < height; i++) {
 
-                       //print_line("bake line " + itos(i) + " / " + itos(height));
+                               //print_line("bake line " + itos(i) + " / " + itos(height));
 #ifdef _OPENMP
 #pragma omp parallel for schedule(dynamic, 1)
 #endif

Do you want to apply that patch (Y - Apply, N - Do not apply, S - Apply and stage files)? [Y/N/S] 
```

**Comment by Rubonnek** [comment]
@donkeybonks did you mean a lint pass to check for these unnecessary assignments?

If that's what you meant, I don't think it should be done. False-positives will keep popping up, plus all these unnecessary assignments do not really affect the final outcome and are not that common anyway. The last time I submitted a pull request like this one was on #10340 and there weren't that many.

I'd say the performance gained is negligible, but it's worth doing this since it may prompt for unforeseen changes.

**Comment by Rubonnek** [comment]
I won't have time to work on this, I'm closing this down. I'll probably resubmit a similar pull request later.

**Pull request closed without merging**
