### PR TITLE
Organize TextEdit's inspector

### PR DESCRIPTION
**Pull request by MewPurPur**
image

### CODE REVIEW

**Comment by seppoday** [comment]
I know hidding stuff under subcategories is not ideal but... there is a lot of elements on that screen. 

Maybe it would be good idea to drop them under subcategory?

**Comment by MewPurPur** [comment]
This is the best I came up with. Do you have any ideas for better organization?

**Comment by seppoday** [comment]
> This is the best I came up with. Do you have any ideas for better organization?

I think I've read screenshot wrong. After this PR all Highlight stuff will be under "Highlight" category that I need to unfold? If yes then ignore my comment... :D

**Comment by MewPurPur** [comment]
Oh yeah sorry I didn't compile the PR, just showed which things are now groups under a section like the "Scroll" or the "Caret" one.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
