### PR TITLE
No longer save all scripts automatically when closing the editor.

### LINKED ISSUE #18010: Modified GDScript code gets saved to disk without a prompt
**Godot version:**
`master` branch commit eaa5dfbdbd1217d62902f966496658770638c3d1

**Steps to reproduce:**
1. Save all the changes to a scene.
2. Open a GDScript with the built-in editor and write some text to it and do not save those changes.
3. Go to Scene->Quit to exit the editor, and click on Quit.
4. The GDScript that was being modified gets saved to disk

I've also noticed that when editing a GDScript that was just saved, it is not getting marked as modified in the editor as soon as you start typing.

**Minimal reproduction project:**
[saved_without_asking.zip](https://github.com/godotengine/godot/files/1881884/saved_without_asking.zip)

### PR DESCRIPTION
**Pull request by Piet-G**
This fixes #18010.

### CODE REVIEW

**Comment by KellyThomas** [comment]
Will this show a "would you like to save changes?" prompt?

**Comment by DualMatrix** [comment]
@KellyThomas No, but it will only not save when you disable the save_each_scene_on_quit property in the editor settings. Previously that setying was just ignored for scripts.

**Comment by akien-mga** [comment]
CC @Noshyaar

**Comment by Noshyaar** [comment]
`save_each_scene_on_quit` was introduced here: https://github.com/godotengine/godot/pull/9304#issuecomment-311164552

There are two styles of save dialog depending on `save_each_scene_on_quit`. If `true` (default behavior), it will go through each unsaved scenes and ask whether you want it to be saved or not. If `false`, you can either save all scenes already on the disk, discard all or cancel. It was added because
1. it's how other applications do it (GIMP afaik.)
2. it's a faster flow if you save constantly. You can just discard all and quit the editor quickly.
3. I kinda want the feedback whether this mode should be default or not.

(tbh I kinda regret adding it a bit since I don't think anyone would config it anyway and it bloats the editor settings.)

The logic when 'save all' is the same as clicking 'save all scenes' from the menu. The `save_each_scene_on_quit` property is not directly related to the script editor.

**Comment by akien-mga** [comment]
IMO we should drop the `save_each_scene_on_quit` option, I agree that most users hardly know about it so it's probably not worth having.

Instead, maybe the two behaviours could be merged into one? i.e. have in the dialog:
- Save current scene --> then moves on to next scene
- Save all scenes
- Discard current scene --> then moves on to next scene
- Discard all scenes
- Cancel

And same for scripts.

Of course 5 buttons would be too much, but maybe it could be done with 3 buttons + a checkbox "Apply to all scenes". Or if anyone has a better proposal :D

**Pull request closed without merging**
