### PR TITLE
Fix inability to set TextureLayeredRD as `TEXTURE_TYPE_CUBE` or `TEXTURE_TYPE_CUBE_ARRAY`

### LINKED ISSUE #93915: TextureCubemapRD can't be sampled as a cubemap
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3]

### System information

Windows 10 - Godot v4.2.2.stable - Vulkan (Forward+) - dedicated

### Issue description

Assigning a TextureCubemapRD to a samplerCube shader uniform and reading from it always returns black. Reading it as a sampler2DArray works fine, but requires the user to manually convert the cubemap direction vector to texture space (uv and face index).

### Steps to reproduce

Run the MRP and observe that the center object is indeed black:
- There is a menu to switch cubemap generation to use a standard Cubemap instead. This is slow but a good reference of what it should look like.
- You can also toggle between accessing the TextureCubemapRD as either a samplerCube or a sampler2DArray. The latter works and is a viable workaround until the issue is fixed.

### Minimal reproduction project (MRP)

[TextureCubemapRDSamplingTest.zip](https://github.com/user-attachments/files/16091060/TextureCubemapRDSamplingTest.zip)

### PR DESCRIPTION
**Pull request by jadeharley2**
…_TYPE_CUBE_ARRAY

Should resolve #93915

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great! Thank you for turning this into a PR

**Comment by Repiteo** [comment]
Please squash your commits into one, see [the interactive rebase](https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase) for details

**Comment by jadeharley2** [comment]
Redone changes (with pre-commit checks) on updated repository. (github was stuck on processing updates after rebase)

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉

**Pull request merged**
