### PR TITLE
Lambda for godot 3.0

### PR DESCRIPTION
**Pull request by dbsGen**

### CODE REVIEW

**Comment by cbscribe** [comment]
Looks like your history has some issues. You should probably apply your changes to a fresh branch.

Also, you didn't post a description - what is this PR supposed to do?

**Comment by dbsGen** [comment]
@cbscribe I thought I should pull it to the lambda branch.

**Comment by cbscribe** [comment]
I see - what's this branch for? It looks to be quite old.

**Comment by akien-mga** [comment]
You should use `git pull --rebase origin/master` if you want to rebase the lambda branch on the current master.

**Comment by dbsGen** [comment]
@akien-mga Oh,I close first, repull it later.

**Pull request closed without merging**
