### PR TITLE
Fix for SkeletonModification3Ds to work with the new bone pose changes.

### LINKED ISSUE #53794: Regression on master on Godot ik.
### Godot version

d956904091b620bea5ee6eec9bd1413a97bba69a

### System information

Win11, RTX 3000 series

### Issue description

Master regressed on SkeletonModifierStack3D.

The arms are not taking rest pose in the calculation. (Animation now have to include rest pose).

https://github.com/godotengine/godot/pull/53765

@TwistedTwigleg 

### Steps to reproduce

This character broken when IK is enabled. res://skeleton_modification/scenes/skeleton_test_08_character_full/Skeleton_Test_08.tscn

### Minimal reproduction project

https://github.com/TwistedTwigleg/Godot_GSOC_2020_Project

### LINKED ISSUE #53895: global_pose_to_local_pose function in Skeleton3D node not working properly
### Godot version

4.0 (#53821)

### System information

Ubuntu Linux, Vulkan

### Issue description

The `global_pose_to_local_pose` function in the Skeleton3D no longer works correctly. Previously, if you passed a valid global position it would convert and give you a usable pose for `set_local_pose_override`, however this is no longer the case. Something in the recent skeletons changes (I think in #53765) seems to have broken the function and it's conversion.

It seems to be mostly an issue with local overrides on top of local overrides, as the effect gets more and more compounded.

This was discovered in #53821 while working on getting the IK system to work with the skeleton changes.

### Steps to reproduce

* Get a Spatial node
* Convert the spatial node global transform to a global pose using `world_transform_to_global_pose`
* Convert the global pose to a local pose using `global_pose_to_local_pose`
* Set it to the bone using `set_bone_local_pose_override` (seems to work as expected)
* Get another spatial node
* Convert the second spatial node's global transform to a global pose using `world_transform_to_global_pose`
* Convert the second global pose to a local pose using `global_pose_to_local_pose`
* Set it to the second bone using `set_bone_local_pose_override`
* Notice it doesn't place the bone at the expected position, despite the conversion functions being called.
* To confirm the global poses are valid, use `set_global_pose_override` and use the global poses. You get the expected result.

Based on my recent testing, it seems multiplying the by the affine inverse of the `local_pose` fixes the issue. However, this shouldn't be needed as the `global_pose_to_local_pose` should handle any conversions necessary to convert a valid global pose to a valid local pose, without the user needing to perform additional steps or know to multiply by the inverse of the local pose of the parent bone.

* To fix, multiply the local pose returned by the `global_pose_to_local_pose` function by `get_bone_global_pose(parent_bone_id_here).affine_inverse()`.

### Minimal reproduction project

[LocalPose_Bug.zip](https://github.com/godotengine/godot/files/7358222/LocalPose_Bug.zip)

### PR DESCRIPTION
**Pull request by TwistedTwigleg**
Closes #53794
Edit: Closes #53895 as well, see comments below

Most of the fixes were pretty easy and the majority of the IK modifications work now without any issues. However, FABRIK is providing difficult due to changes involving bone positions, which is causing it not to work.

It seems that the previous method of setting the `local_pose_override` position to `Vector3(0, 0, 0)` no longer works for setting the bone at its default local position, which was causing it not work. Using the global pose without overrides as the position sort of works, but it's not ideal nor fully working right now.
I have some ideas on what might work to solve it, but haven't had the time to investigate yet. I'll try to look at this further soon though.

### CODE REVIEW

**Comment by TokageItLab** [comment]
@TwistedTwigleg The default position of the pose has been changed to "rest" instead of `Transform()`. One problem is that we decided on the concept that to set up a pose, it needs to go through the TRS(position, rotation, scale) channel, so instead of applying the rest directly to the pose, it needs to be decomposed sequentially into the TRS track.

**Comment by TwistedTwigleg** [comment]
> @TwistedTwigleg The default transform of the pose has been changed to "rest" instead of `Transform()`. For example, in the case of default position, it is `rest.origin` instead of `Vector3(0, 0, 0)`. One problem is that we decided on the concept that to set up a pose, it needs to go through the TRS(position, rotation, scale) channel, so instead of applying the rest or any `Transform3D` value directly to the pose, it needs to be decomposed into the TRS channel as needed.

Oh okay! I'll quickly give `rest.origin` a try and mess around with that and see if that fixes it. Thanks for letting me know how it works now, I appreciate it :+1:

**Comment by TwistedTwigleg** [comment]
Okay, FABRIK is fixed now! I had to change how it works so that it uses global poses instead of local ones, as well as making it save the transforms internally. This does have some benefits though, as now the code is much more compact, less conversions are needed (more performance), and it's easier to understand.
For reasons mentioned in more detail below, I also added some code to the modification stack so the global pose override is reset when the modification is disabled.

With these changes done, I'm confident that the IK modifications in 3D should be back to fully working and have removed the draft status on this PR.

___________

However, while working on this I found what I believe was the actual culprit: **the `global_pose_to_local_pose` function is broken!** The changes in #53765 seems to have altered the function where it no longer works, at least with positions.

For example, the following line of code is how this PR applies the global pose to the skeleton (line `288`):

~~~
stack->skeleton->set_bone_global_pose_override(current_bone_idx, current_trans, stack->strength, true);
~~~

The transform passed, `current_trans`, is a valid global pose transform and it works completely as expected when passed to `set_bone_global_pose_override`.

However, the follow line of code doesn't work, even though it would have worked prior to the changes in #53765

~~~
stack->skeleton->set_bone_local_pose_override(current_bone_idx, stack->skeleton->global_pose_to_local_pose(current_bone_idx, current_trans), stack->strength, true);
~~~

Which is a problem, because it means that valid global poses are not being correctly converted to local poses, meaning the `global_pose_to_local_pose` function is broken. I took a look at the function in Skeleton.cpp to try and fix it, but my experiments didn't yield proper behavior.

While it's not a blocking issue for this PR and the skeleton modification system currently, I just changed the FABRIK code to work entirely in global pose space and to cache the transforms it needs, it needs to be fixed. I can make a new issue for this if needed though.

**Comment by fire** [comment]
> I can make a new issue for this if needed though.

Please do!

**Comment by TwistedTwigleg** [comment]
Will do! I’ll get a quick replication project and issue made this weekend 👍

**Comment by TwistedTwigleg** [comment]
I fixed the issue with the `global_pose_to_local_pose` function, so now it works as expected again! I also reset the stack modification disable code, so it only disables the local poses. Should fully close #53895 and everything IK related should be working as expected again!

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
