### PR TITLE
Document incremental search support in ItemList, PopupMenu and Tree

### PR DESCRIPTION
**Pull request by Calinou**
See https://github.com/godotengine/godot-proposals/issues/4682.

If the description is too hard to understand, it might be worth adding a video (with visible keystrokes) to the godot-docs repository.

### CODE REVIEW

**Comment by skyace65** [comment]
I didn't know anything about incremental search before reviewing this PR, the description makes sense and is clear to me.

**Comment by AaronRecord** [comment]
Do I understand correctly that this means you can't directly search for items that start with 2 of the same letter, e.g. llama? 🦙

**Comment by Calinou** [comment]
> Do I understand correctly that this means you can't directly search for items that start with 2 of the same letter, e.g. llama? llama

I think it works in this case, but I haven't tested in Godot. In other applications like KDE's Dolphin file manager, `llama` will take priority over other items that start with `l` in the list as soon as you enter the third letter (`lla`).

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
