### PR TITLE
Removing duplicate Batch Rename from scene-tree menu

### PR DESCRIPTION
**Pull request by swarnimarun**
I, while working on something came across a this duplicate so thought why not remove it.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by swarnimarun** [comment]
@bfloch Thanks for pointing it out let me quickly fix it...

**Comment by swarnimarun** [comment]
@bfloch What's the problem? Cause I am not able to see how it is causing a problem, the place it now makes more sense as the comment says.

**Comment by akien-mga** [comment]
I also don't see what's the problem.
screenshot_20190123_103428

@Calinou Apparently the Batch Rename scene tree tool is not listed in the changelog yet, see #15928.

**Comment by Calinou** [comment]
@akien-mga I just added it to the changelog.

**Comment by bfloch** [comment]
I think I know where my confusion comes from.
If you have child nodes selected it only shows "Rename".

batch_rename

Batch Rename works well for hierarchies, has per level Options etc.
Now I am not sure if that's me messing up since it was so long ago, but I thought it worked at some point.

@Calinou Thanks for the update.

**Pull request merged**
