### PR TITLE
String: Parse fragment from URL

### LINKED ISSUE #92229: HTTPRequests do not correctly handle URL fragments
### Tested versions

- Reproducible in v4.3.dev6.official [89850d553], v4.2.1.stable.official [b09f793f5]

### System information

Windows 10

### Issue description

If you make an HTTP request in Godot using a URL that contains a [URI Fragment](https://en.wikipedia.org/wiki/URI_fragment), Godot does not give any error messages and creates an HTTP request that *includes* the URI fragment, which is not supposed to be sent to the server. Many servers will not accept requests sent to paths that include a fragment and will return a 400 or 404 response. The correct behavior should be to *strip* the fragment out of the URL, which is what tools like cURL do.

### Steps to reproduce

1. Call `HTTPRequest.request(url)` with a URL that has `#whatever` at the end.
2. The HTTP request that gets sent includes the fragment when it should not.

To verify this locally, I ran netcat (`nc -lk 12345`) and made a request to `$HTTPRequest.request("http://127.0.0.1:12345/page#fragment")`. The netcat output was:
```
GET /page#fragment HTTP/1.1
Host: 127.0.0.1:12345
User-Agent: GodotEngine/4.3.dev6.official (Windows)
Accept: */*
```
For comparison, HTTP requests sent by curl do not include the fragment: `curl 'http://127.0.0.1:12345/page#fragment`
```
GET /page HTTP/1.1
Host: 127.0.0.1:12345
User-Agent: curl/7.68.0
Accept: */*
```

### Minimal reproduction project (MRP)

[HTTPFragmentIssue.zip](https://github.com/godotengine/godot/files/15396044/HTTPFragmentIssue.zip)

### PR DESCRIPTION
**Pull request by timothyqiu**
Fixes #92229

### CODE REVIEW

**Review by Faless — COMMENTED** [review]
This looks good, but I wonder if we should parse the fragment before the scheme.

As far as I understand RFC 3986 [section 3.5](https://www.rfc-editor.org/rfc/rfc3986#section-3.5) and [Appendix A](https://www.rfc-editor.org/rfc/rfc3986#appendix-A) specify that the URL fragment can contain both `:` and `/` characters.

This means that the following URI is valid:

```
google.com/#goto=http://redirect_url/
```

But our current implementation will take the scheme as `google.com/#goto=http://`.

**Comment by timothyqiu** [comment]
`http_://example.com` is currently considered valid, which is not the case according to RFC 3986. Adding scheme validation seems to solve both problems.

Also added some tests for `parse_url()`.

**Review by Faless — APPROVED** [review]
LGTM, nice work! :rocket:

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
