### PR TITLE
Add autocomplete for filter/repeat hints on uniform arrays

### PR DESCRIPTION
**Pull request by Haydoggo**
Adds autocomplete support for the hints added in #79100

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]
LGTM. TIWAGOS, IAC*.

*: In any case.

**Review by clayjohn — APPROVED** [review]

**Comment by clayjohn** [comment]
Note for cherrypicking, this should not be cherrypicked before https://github.com/godotengine/godot/pull/79100

**Comment by clayjohn** [comment]
Thanks for the contribution!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
