### PR TITLE
[3.2] Fix splash screen loading on Android

### PR DESCRIPTION
**Pull request by m4gr3d**
Fix issue #21824

This is done by leveraging the Android theme to setup the app splash screen ([reference](https://medium.com/@vatani.ahmad/android-optimal-splash-screen-without-extra-activity-or-fragment-b60fea45a0cc)).

**Note:** 
- The splash screen `fullsize` and `use filter` parameters are not supported due to limitations of the Android theme api
- The PR is made against the `3.2-android-app-bundle` branch since that branch includes numerous updates to the Android build process.
- The feature targets the Godot **3.2.4** release.

[master PR](https://github.com/godotengine/godot/pull/41385)

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by NightBreather** [comment]
I have a problem with it unfortunately sometimes the splashscreen doesn't look like it should. Sometimes it shows twice

**Comment by akien-mga** [comment]
Please file a dedicated bug report.

**Comment by NightBreather** [comment]
> Please file a dedicated bug report.

I couldn't understand very much what kind of error report you are talking about. It is not a recurring situation but when opening the application, sometimes my png file appears again after it has appeared once.

**Comment by akien-mga** [comment]
I mean that it's more convenient for us if you create a new issue with all the information asked for in the issue template: https://github.com/godotengine/godot/issues/new?assignees=&labels=&template=bug_report.md&title=

Having one issue for each bug enables us to focus on debugging each issue separately, and eventually fixing them. This here is a merged Pull Request, and while it might be related to your issue (as it aimed to fix a similar problem), it may also not be.
So an actual bug report (issue) would be better (but you can reference this PR by its name: #42389 for additional context).

**Comment by NightBreather** [comment]
> I mean that it's more convenient for us if you create a new issue with all the information asked for in the issue template: https://github.com/godotengine/godot/issues/new?assignees=&labels=&template=bug_report.md&title=
> 
> Having one issue for each bug enables us to focus on debugging each issue separately, and eventually fixing them. This here is a merged Pull Request, and while it might be related to your issue (as it aimed to fix a similar problem), it may also not be.
> So an actual bug report (issue) would be better (but you can reference this PR by its name: #42389 for additional context).

thanks for information

**Pull request merged**
