### PR TITLE
Fix 38745: Importing FBX of a non-Unicode encoded path causes Assimp throws error

### LINKED ISSUE #38745: Importing FBX of a non-Unicode encoded path causes Assimp throws error
**Godot version: 3.2.1**

**OS/device including version: Windows 10**

**Issue description:**
I'm using a non-English Windows system whose default encoding is not Unicode. However it turns out Assimp assumes the input path is in UTF8 encoding which causes a error when I importing a FBX of a non-Unicode encoded path.

see `/thirdparty/assimp/code/Common/DefaultIOSystem.cpp, line 86`, where `Utf8ToWide` is applied to the input path:
```CPP
bool DefaultIOSystem::Exists(const char* pFile) const
{
#ifdef _WIN32
    struct __stat64 filestat;
    if (_wstat64(Utf8ToWide(pFile).c_str(), &filestat) != 0) {
        return false;
    }
#else
    FILE* file = ::fopen(pFile, "rb");
    if (!file)
        return false;

    ::fclose(file);
#endif
    return true;
}
```

One solution was to convert the path to UTF8 encoding before call the Assimp API, where I found `String::utf8()` is very handy. I just need to change `/modules/assimp/editor_scene_importer_assimp.cpp, line 150` to:
```CPP
String g_path = ProjectSettings::get_singleton()->globalize_path(p_path);
aiScene *scene = (aiScene *)importer.ReadFile(g_path.utf8().ptr(), post_process_Steps);
```
and the problem is solved.

### PR DESCRIPTION
**Pull request by MarcusElg**
Fixes #38745 by converting the path to utf8

### CODE REVIEW

**Comment by RevoluPowered** [comment]
Thanks for this fix, can you please update the commit message to be "import" there is a spelling error as you've written "inport".

**Review by RevoluPowered — APPROVED** [review]
Looks good to me. Commit message needs updated

**Comment by MCrafterzz** [comment]
@RevoluPowered fixed

**Comment by akien-mga** [comment]
Thanks!

**Comment by MCrafterzz** [comment]
@akien-mga this was my eleventh commit (source: https://github.com/godotengine/godot/commits?author=MCrafterzz) so will I be added to the contributors list?

**Comment by akien-mga** [comment]
Yes, in my next update commit (at the start of July). Which name would like you me to put?

**Comment by MCrafterzz** [comment]
> Yes, in my next update commit (at the start of July). Which name would like you me to put?

Marcus

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
