### PR TITLE
Don't attempt to re-import broken files if they didn't change

### LINKED ISSUE #62271: Broken imports result in endless reimports making the editor unusable
### Godot version

4.0 alpha 10 

### System information

Windows 10, amd 6900xt, vulkan clustered

### Issue description

Having broken gltf files in your project folder causes the editor to get stuck in an endless re-import loop, causing everything to freeze up.
In the end, I had to kill the editor with the task manager and remove the gltf files from the project folder with the windows file explorer while Godot wasn't running to fix this problem.

### Steps to reproduce

I encountered this by trying to import animation libraries from a bunch of split gltf models (each had SomeFile.gltf + data.bin) in the same folder. All the bin files overwrote each other, and all but one of the gltf files thus became broken.

### Minimal reproduction project

Can't share my assets, but if necessary it should be possible to reproduce this with any other split gltf files.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #62271

`_reimport_file()` had code that was able to handle invalid imports (it even explicitly writes `valid=false` to file), but that code was unused, because the method failed early in case of error. This PR moves the fail line to the bottom of the method, so user is notified about failed import, but the `.import` file and modified times are written normally.

Moreover, I removed code that attempts to re-import when `.import` file is invalid. This is no longer necessary after #84974. Reimport will be automatically attempted if `.import` file has changed, so no reason to force it when the file will stay invalid anyway (see above case).

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Nice! This has been such a pain point for years.

**Comment by akien-mga** [comment]
Thanks!

**Comment by ttencate** [comment]
Does this also fix #90980?

**Comment by akien-mga** [comment]
> Does this also fix #90980?

Tested, seems so.

**Pull request merged**
