### PR TITLE
Implement access modifiers, private and protected, to GDScript to protect a class member from being accessed externally.

### PR DESCRIPTION
**Pull request by Lazy-Rabbit-2001**
This is my first contribution to godot, also the first try sending a pull request. So if there is any mistake, please let me know and I'm here to hear that. :)  
  
**Trying implementing [godot-proposal-#641](https://github.com/godotengine/godot-proposals/issues/641).**  
  
This pr provides GDScript users a way to protect their members accessibility, and prevent any illegal access from external classes.
We will have `@private` and `@protected` annotations in GDScript soon:  

# Introduction of new annotations

## `@private`

`@private` annotation allows a member (currently a constant, a variable or a method) to be accessible only within the current class scope:
```GDScript
# In Class A:
@private static var a = 1
# In Class B:
var b = A.a # Error: Could not access external class member "a" because it is private.
# In Class C that inherits from A:
var c = A.a # Error: Could not access external class member "a" because it is private.
```

## `@protected`

`@protected` annotation allows a member (currently a constant, a variable or a method) to be accessible only within the current class scope, or the scope of derived classes:
```GDScript
# In Class A:
@protected static var a = 1
# In Class B:
var b = A.a # Error: Could not access external class member "a" because it is protected but accessed from a class that is not derived from "A".
# In Class C that inherits from A:
var c = A.a # OK
```

## Common features:

~~* A member modified with `@private` or `@protected` cannot be modified with `@export_*` annotations, and vice versa.~~(This will be obsolescent and check [this](https://github.com/godotengine/godot/pull/98136#issuecomment-2409857495) to know why)
* A member modified with `@private` or `@protected` will hide its documentation from auto-generated doc API, even if you use `##` to document it.
* These two annotations CANNOT modify local members.

# How these are done?

As is known, this two are trying to restrict the access to the member, so we have to modify `gdscript_parser.cpp`, `gdscript_parser.h` and `gdscript_analyzer.cpp`.
In the head file of the parser, since a `Node` there refers to a lingual element of GDScript, I added an enum `AccessRestriction` and an enum-ed variable `access_restriction` under it to control the member's accessibility. When `@private` or `@protected` modifies a member, its `access_restriction` will be modified to other values than `AccessRestriction::ACCESS_RESTRICTION_PUBLIC`.
Once analyzer starts analyzing external access, we detect the access of the member's `access_restriction` and figure out the relationship between the accessor class and the accessee class.

# Remaining WIP

- [x] Support protection for signals. (GDScript)
- [x] Move protection in static analyzer into `reduce_identifier()` and `reduce_call()`. (GDScriptAnalyzer)
- [x] ~~Discussion about if `@private` and `@protected` should be keywords or annotations. Allow `@export_*` work with `@private` and `@protected`~~
- [x] ~~Hide GDScript intelliguess from providing hint of private and protected members.~~
- [x] ~~Test if `Set()` and `Get()` in C# can get access to the access-restricted members in GDScript. (Cross-language programming)~~
- [x] ~~Compiler, codegen and runtime stuff. (The most difficult part)~~
- [x] ~~Not sure whether an invalid access should pop an error or a warning. (Warning / error system)~~
- [x] ~~Unit tests in `.gd` and `.out` files. (Unit test)~~

# Tracking after this PR gets merged:

* More optimizations (Such as speeding up, which needs other contributors' help as I'm just a freshman in C++ programming)

### CODE REVIEW

**Comment by FireCatMagic** [comment]
would `@public` for readability be a bad idea, even if its the default and wouldn't actually change anything?

**Comment by tetrapod00** [comment]
I'm not sure it makes sense to tie export functionality to access functionality.

In C#, you can currently do all of the following, and they all have their uses:[^1]
`[Export] public int PublicExport;` is an exported public variable, accessible from both the editor and from other scripts. Useful for most export cases.
`[Export] private int PrivateExport;` is an exported private variable. Useful if you want to expose a value to editor configuration, but not to changes from scripting.
`public int PublicVar;`  is an public variable. Used for values that are exposed to API access, but not to editor configuration.
`private int PrivateVar;` is an private variable. Used for internal state that don't need to be exposed to configuration *or* API access.

GDScript is its own specialized language, and it doesn't necessarily need to follow this example. But be aware that tying exporting and access together does not match the current C# implementation, and would prevent one of these four use cases.

[^1]: Using variables instead of properties for simpler example syntax.

**Comment by Dynamic-Pistol** [comment]
personal nitpick, make it `@privacy(PRIVATE|PROTECTED|INTERNAL|PUBLIC)` incase other privacy modifiers are added, this also lowers amount of annotations needed

**Comment by kroketio** [comment]
I prefer the Python way of prefixing with `_` to mark private members, while not enforcing that at runtime. In addition, these annotations don't help with the overall readability of GDScript.

**Comment by dalexeev** [comment]
Hi @Lazy-Rabbit-2001, thanks for your effort! I haven't reviewed this PR in detail, but I'd like to point out a few things:

1. GDScript is a gradually typed language, we support both dynamic and static language features. This means that the feature can't be implemented on the static analyzer side alone. It should at least involve the compiler/codegen and probably also the VM to remove unnecessary runtime checks for public properties.
2. I'm not sure that the current implementation of static checks is correct. I think you should use `reduce_identifier()` and `reduce_call()` instead of `resolve_class_member()`.
3. There are some conceptual problems with implementing access modifiers with dynamic typing.
   * It's easy to determine _what_ we are accessing, but hard to determine where _from_. In many programming languages, you can access private members not only from the current instance, but also from other instances of the same class (and its descendants, in case of `protected`). This is difficult when you access another instance with dynamic typing.
   * Another problem is that sometimes we still want to access private fields from the outside, for example from the debugger. Also the problem with private export variables was mentioned above.
   * It might be simpler to have only private members that are effectively protected. For example, this is how Haxe does it.
   * See also https://github.com/godotengine/godot-proposals/issues/641#issuecomment-1604787082.
4. Maybe private/protected should be keywords, not annotations. See [Scripting development - Annotation guidelines](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/scripting_development.html#annotation-guidelines). Note that annotations are resolved and applied relatively late, so we should take this into account to avoid bugs.

> This makes sense for constants, variables and signals, but not for functions. According to the discussion in the proposal, the single underline prefix may be confusing whether it means private or protected or virtual for a function.

I don't think there is any confusion between private and virtual methods. It's just that all built-in virtual methods are private (or protected), you are not supposed to call `_ready()` from the outside. Some of them have a "public final" counterpart, like `_get()` and `get()`. As for custom methods, I believe that you should not name your public virtual methods with an underscore, it should only be a sign of private methods that may or may not be virtual. For more details, see https://github.com/godotengine/godot-proposals/issues/10500#issuecomment-2298614390 and https://github.com/godotengine/godot-proposals/discussions/10342#discussioncomment-10223801.

I have nothing against access modifiers and consider them a useful language feature that provides more reliability. I would like to have them in GDScript, but we also need to consider the complexity of the implementation and maintainability of the feature.

In my opinion, Python's underscore approach solves the problem of distinguishing between external and internal interfaces quite well and cheaply, requiring only a little discipline and adherence to common conventions from the user. I don't recall ever encountering the problem of accidentally accessing the internals of a class, unlike the problems of the type system, null safety, etc.

**Comment by Zireael07** [comment]
Why close?

**Pull request closed without merging**
