### PR TITLE
Emit signal when animation ends by seek

### LINKED ISSUE #22210: AnimationPlayer animation_finished signal not firing when started at end position.
___

***Note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**v3.1 alpha e10ca7b82**

This is probably minor, but it seems like it was undefined.

If you play a non-looping animation at the end point of the timeline (by seeking) , it will:

1. Signal that it started.
2. The animation will stop.
3. It will report as not playing.
4. _But the `animation_finished` signal does not fire._

Example project (**Updated Project**): 
~~[3.1 No Anim Finish Signal.zip](https://github.com/godotengine/godot/files/2391879/3.1.No.Anim.Finish.Signal.zip)~~
[3.2 No Anim Finish Signal.zip](https://github.com/godotengine/godot/files/4496223/3.2.No.Anim.Finish.Signal.zip)

### PR DESCRIPTION
**Pull request by volzhs**
Fix #22210

### CODE REVIEW

**Comment by avencherus** [comment]
Thanks, it appears to be working just fine now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Comment by RandomShaper** [comment]
I can understand some people expect the signal to be emitted even when the end is reached via seeking. To me, it's not the case: the signal is emitted when you are letting the animation player do its job as a way for it to notify you because that will happen at a later time. If you a controlling the play head manually and you put it at the end of the animation, you know the consequences of that.

But, moreover, this is in my opinion a **breaking change**. OK for _master_ if there's agreement on that behavior, but for 3.x it's too late. My game is an example of a project that gets impacted by this. I was running into weird problems and found the cherry-pick of this via bisection.

**Comment by avencherus** [comment]
@RandomShaper I'm not sure I understand.  When the animation is playing, and is set to 50%, then completes playing, it signals as finished.  Why should this be different in the one case where it is set to the end position while playing?  It still is playing, and it is "seeked" to the last position, and the animation does end on it's own accord.  I think it would only be a question of does it signal at that moment seek is called, or during the processing when it checks its counter.

I imagine if an animation is not playing and then is seeked to either the beginning or end and then fires start/finished signals if it is on first and last position, that seems like a bug that needs to be fixed.

But if it's playing and you seek to the end, and the animation then ends and signals so, in my mind at least that is consistent behavior.

**Comment by RandomShaper** [comment]
The case where it's already playing and you just push the head so it gets to the end is indeed a matter of opinion.

In the way you understand the purpose of the signal, emitting it in such cases is what makes it consistent.

In the way I understand it, where it's useful only if you are letting it play and you need to be notified when it's done, the fact the signal is emitted also if you have provoked the completion makes it less useful.

So my point is that it should be emitted only if the internal processing of the player has "crossed" the end itself, if you know what I mean.

However, I still think neither you or I are more right than the other. Both perspectives make sense depending on how you understand it.

Let me suggest this: adding to `AnimationPlayer.seek()` a new parameter to pick between both. For 3.2 I still think the default should be the one that keeps it working as it does now, to avoid the breaking change. For 4.0 it may be either: keep the same as 3.2 to avoid a surprising behavior change between versions or the revised behavior you suggest.

**Comment by akien-mga** [comment]
I'll revert for now as I agree that it needs more discussion / a better design to cover all use cases, and the cherry-pick in 3.2 breaks compat.

**Comment by akien-mga** [comment]
Reverted with 69f36cea8c5e706125ab419f8e845d3aa657f373 and f629df647d3a8fc138c2b5c37fde5445d476ce2f.

**Pull request merged**
