### PR TITLE
AST builder

### PR DESCRIPTION
**Pull request by hedin-hiervard**
I've added the ability of the command line `godot` command to output AST (Abstract Syntax Tree) in the JSON format. 
It's used like this: `godot --script /path/to/script.gd --output-ast /path/to/ast.json`
It correctly adds the singleton objects specified in the `project.godot` file.
The change is unintrusive as it totally relies on the existing gdscript parser (had to fix a few minor bugs in it though). 
The purpose of it is to allow external tools to analyze gdscript code (i.e. to build a linter which is independent of godot executable).

### CODE REVIEW

**Comment by reduz** [comment]
I can't tell if this feature is wanted or not. 

If you want to win points with me, drop rapidjson and use godot's built-in JSON tools.

**Comment by hedin-hiervard** [comment]
> drop rapidjson and use godot's built-in JSON tools.
Couldn't find a stream JSON writer. Can you pinpoint the location?

**Comment by reduz** [comment]
https://github.com/godotengine/godot/blob/master/core/io/json.h

It does not need to be stream, it won't change anything if you create it on memory and then save.

**Comment by hedin-hiervard** [comment]
> https://github.com/godotengine/godot/blob/master/core/io/json.h
> 
> It does not need to be stream, it won't change anything if you create it on memory and then save.

Ok, I will try to use it instead of rapidson. The output file is relatively large (15000 lines for a 300-lines source file), so I was concerned about the memory footprint.

**Comment by reduz** [comment]
I don't think that will ever be a problem, so no need to prematurely optimize

**Comment by hedin-hiervard** [comment]
> I don't think that will ever be a problem, so no need to prematurely optimize

I agree. This is just a small technical issue. I can certainly do it. But I need to get an approval of the overall idea to continue the work on it.

**Comment by hedin-hiervard** [comment]
I noticed a lack of linters for gdscript, and think building one would be a great help for the community.

**Comment by reduz** [comment]
It would also be interesting to provide a list of real-life use cases for this, together witrh users that need this functionality. Just having it for the sake of having it does not make it worth it, in my opinon.

**Comment by hedin-hiervard** [comment]
Linters help avoid many common mistakes in writing code, enforcing code style, increase code quality, readability and general culture. 
I think implementing a linter is a must for any modern programming language. It is especially important for a dynamically-typed language like gdscript, because lack of proper typing adds more field for errors.

**Comment by reduz** [comment]
I suggest we should wait and see if anyone has a real life use case for this before considering a merge. There are currently internal tools that do what you mention within the editor, where a linter is not necesary.

**Comment by hedin-hiervard** [comment]
> I suggest we should wait and see if anyone has a real life use case for this before considering a merge. There are currently internal tools that do what you mention within the editor, where a linter is not necesary.

What tools are those?

**Comment by fire** [comment]
I agree, we should wait unless someone develops a use for this.

I can think of automatically formatting the code to a style.

Another use to handle get_node renames. It's currently difficult to rename get_node absolute paths when the developer moves the node.

**Comment by vnen** [comment]
> The change is unintrusive

**Comment by Zylann** [comment]
I might need this to extract `tr` calls for localization, although my tool is currently made itself in GDScript and uses a bunch of regex-ish code for now (which I know has edge cases)

**Comment by hedin-hiervard** [comment]
Ok, *someone* is building a linter:
screen shot 2018-11-19 at 21 49 13

**Comment by neikeq** [comment]
Wouldn't it be more useful to have something like a server? Running Godot to generate the AST sounds too slow for these kind of tools. Specially if you have to run it once for each script.

**Comment by hedin-hiervard** [comment]
> Wouldn't it be more useful to have something like a server? Running Godot to generate the AST sounds too slow for these kind of tools. Specially if you have to run it once for each script.

Yes, I totally agree, it's slow.
I think godot's cli needs refactoring (at least, separating gdscript-related features from the engine features, allowing quick executing). 
While it's not done, I suggest using the gdscript parser & AST builder capabilities to improve the code quality during commit phase / in CI environment.
Please meet `gdlint`: the first linter for GDscript:  https://github.com/hedin-hiervard/gdlint

**Pull request closed without merging**
