### PR TITLE
Consider a thread done if current_work is null

### LINKED ISSUE #48257: Infinite loop in reimport_files, Condition "current_work == nullptr" is true.
**Godot version:**
4.0.dev 1c2766e

**OS/device including version:**
Windows 10.0.19041.928

**Issue description:**

I have a tool script which writes files into the project and subsequently calls
.get_resource_filesystem().scan()
The calls to scan() are done repeatedly on a timer until the new resources are successfully imported.
The lack of a proper API exposed to GDScript, and the lack of feedback ((get_scanning_progress and is_scanning are historically unreliable)) do not allow for a more reliable testing mechanism.

However, this crash does not appear to involve GDScript as it happens purely in engine code.

```
ERROR: Task 'reimport' already exists.
   at: (editor\progress_dialog.cpp:159)
ERROR: Condition "current_work != nullptr" is true.
   at: ThreadWorkPool::begin_work (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:84)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "!tasks.has(p_task)" is true. Returning: cancelled
   at: ProgressDialog::task_step (editor\progress_dialog.cpp:188)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
   at: ThreadWorkPool::is_done_dispatching (S:\repo\godot-pr-pr\core/templates/thread_work_pool.h:108)
ERROR: Condition "current_work == nullptr" is true. Returning: false
```

```
>	godot.windows.opt.tools.64.exe!EditorFileSystem::reimport_files(const Vector<String> & p_files) Line 2004	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_update_scan_actions() Line 582	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_notification(int p_what) Line 1141	C++
 	godot.windows.opt.tools.64.exe!EditorFileSystem::_notificationv(int p_notification, bool p_reversed) Line 110	C++
 	godot.windows.opt.tools.64.exe!Object::notification(int p_notification, bool p_reversed) Line 795	C++
 	godot.windows.opt.tools.64.exe!SceneTree::_notify_group_pause(const StringName & p_group, int p_notification) Line 796	C++
 	godot.windows.opt.tools.64.exe!SceneTree::process(float p_time) Line 443	C++
 	godot.windows.opt.tools.64.exe!Main::iteration() Line 2505	C++
 	godot.windows.opt.tools.64.exe!OS_Windows::run() Line 622	C++
 	godot.windows.opt.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 163	C++
 	godot.windows.opt.tools.64.exe!_main() Line 187	C++
 	godot.windows.opt.tools.64.exe!main(int argc, char * * argv) Line 199	C++
 	[Inline Frame] godot.windows.opt.tools.64.exe!invoke_main() Line 78	C++
```

The loop in reimport_files appears as follows:
```
					do {
						if (current_index < data.max_index) {
							current_index = data.max_index;
							pr.step(reimport_files[current_index].path.get_file(), current_index);
						}
						OS::get_singleton()->delay_usec(1);
					} while (!import_threads.is_done_dispatching());
```
The error message is printed from `is_done_dispatching()` causing it to return `false`.
As a workaround, perhaps it should return `true` when current_work is null.

**Steps to reproduce:**
Happens randomly when I apply my custom importer to complex assets. I do not have sufficient redistributable assets to reproduce this, yet.

**Minimal reproduction project:**
Sorry, I do not currently have a reproduction project, and this crash happens 25% of the time so it's not reliably reproducible.

### PR DESCRIPTION
**Pull request by lyuma**
Fixes #48257
Addresses one of the causes of #49324

I forgot to make a PR for this fix, so here it is finally. I was hoping someone with more knowledge of the threaded importer would make a comment, but it seems to work well for me so far.

Read #48257 for more detail

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Makes sense to me. Let's get it validated by @reduz but I can see how returning `false` here would lead to troubles.

**Comment by lyuma** [comment]
I would also ask that you check the theory in this comment by @fasterthansound:
https://github.com/godotengine/godot/issues/48257#issuecomment-830876782

There could be an underlying issue that causes current_work to be null.

**Comment by akien-mga** [comment]
> There could be an underlying issue that causes current_work to be null.

Definitely, but this change doesn't hide, it will still throw an error message. So this will need to be fixed anyway eventually, but at least it shouldn't freeze anymore (but there might still be non-working functionality due to this error).

**Comment by akien-mga** [comment]
Approved by @reduz on RC.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
