### PR TITLE
Additional indentation for word wrap on line break

### LINKED ISSUE #26984: Implement additional indentation for line breaking when word wrap is on
**Godot version:**
3.1 rc2

**OS/device including version:**
Windows 10 x64

**Issue description:**
When word wrap option in on, the line breaking put the broken part left aligned with the starting line:
image

This is not aesthetically good and can lead to confusion in reading the code.
It would be best to insert an additional indentation for the broken parts, thus differentiating them from the first line:
image

### PR DESCRIPTION
**Pull request by Chinmaygoyal**
Closes #26984.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
The issue also [suggests](https://github.com/godotengine/godot/issues/26984#issuecomment-484198955) this being configurable via a `TextEdit` properties.

**Comment by Chinmaygoyal** [comment]
Should I work on fixing this through TextEdit properties?

**Review by Paulb23 — COMMENTED** [review]
This is a bit ticker then at first glance as the extra indent ought to be applied only to code files, and not plain text, which `TextEdit` currently does not differentiate. In addition to this, for scripts it should not add the indent to comments.

**Comment by aaronfranke** [comment]
@Chinmaygoyal Is this still desired? If so, it needs to be rebased on the latest master branch, and the above feedback should be addressed.

**Comment by Chinmaygoyal** [comment]
Seeing the above comment regarding the fact that TextEdit does not differentiate between text file and code file, I did not go ahead with any further changes.

**Comment by aaronfranke** [comment]
@Paulb23 @Chinmaygoyal Any update? This PR should either be improved or closed.

**Comment by Chinmaygoyal** [comment]
@aaronfranke I did not make any further changes regarding this PR.

**Comment by aaronfranke** [comment]
Alright. I also noticed that the repository this PR comes from has been deleted, so this PR is no longer valid as no more changes can be made to it. Closing, but anyone is welcome to salvage this.

**Pull request closed without merging**
