### PR TITLE
Rename remaining "*_enable" to "*_enabled"

### PR DESCRIPTION
**Pull request by Mickeon**
#### Material
- `proximity_fade_enable` -> `proximity_fade_enabled`
- `set_proximity_fade()` -> `set_proximity_fade_enabled()`
(`is_proximity_fade_enabled()` is unchanged)
#### Area3D
- `reverb_bus_enable` -> `reverb_bus_enabled` 
(`set_use_reverb_bus()` & `is_using_reverb_bus()` are unchanged)

#### RDPipelineRasterizationState
- `depth_bias_enable` -> `depth_bias_enabled`
- `set_depth_bias_enable()` -> `set_depth_bias_enabled()`
- `get_depth_bias_enable()` -> `get_depth_bias_enabled()`

#### Area3D
- `set_reverb_bus()` -> `set_reverb_bus_name()`
- `get_reverb_bus()` -> `get_reverb_bus_name()`
Their property is called `reverb_bus_name`.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

**Comment by akien-mga** [comment]
Thanks!

**Comment by CsloudX** [comment]
IMO，`*is_enable` should be used as property and `*_enabled` should be used as signal，for example a `Button`, it has a `is_enable` property and a `enabled` signal.

**Comment by Mickeon** [comment]
Please open a [Proposal ](https://github.com/godotengine/godot-proposals)to discuss about this. This is not the right place. The current API for Godot 4 aims to suffix many of the boolean properties to "_enabled" for consistency. This PR only complements that goal.

**Pull request merged**
