### PR TITLE
RegEx class documented.

### PR DESCRIPTION
**Pull request by Ovnuniarchos**
RegEx class has been documented. In the future I'd like to alter (again) the help viewer to show descriptions for the methd's parameters.

### CODE REVIEW

**Comment by vnen** [comment]
I recall that @reduz said to don't bother writing documentation for arguments for they don't show in the editor help. I'm not sure if he has some plans regarding this issue.

**Comment by Ovnuniarchos** [comment]
I'd say so! It shouldn't be much trouble to make parameters appear in the
editor help. Maybe I should implement it (along with other enhancements).

**Comment by leezh** [comment]
Nice! I should add that there is an update to the regex that hasn't been merged yet. https://github.com/godotengine/godot/pull/2642

**Comment by Ovnuniarchos** [comment]
Well, I'll have to update the docs when it gets merged. I hope it gets merged, it adds a ton of sexy functionality to the regex.

**Comment by akien-mga** [comment]
Changes look good, I'm not sure either if the argument documentation will be kept by the parser or it will be discarded, we'll see.

**Comment by akien-mga** [comment]
@Ovnuniarchos As I feared, Godot's doctool discards the return and argument descriptions when they exist, i.e.: ```./bin/godot.x11.tools.64 -doctool doc/base/classes.xml``` currently generates this diff: http://hastebin.com/ugumodoxuj.xml

So I guess for the time being it's best that we stick to documenting the necessary argument ranges in the main function description. Same for the return value (though there is often little interest to documenting the return value specifically, as it's usually exactly what the main function description does).

**Comment by Ovnuniarchos** [comment]
It's time to correct these docs, then.

**Pull request merged**
