### PR TITLE
Force ANGLE on all pre GCN 4th gen. AMD/ATI GPUs.

### LINKED ISSUE #78888: Can't run Godot OpenGL 3 on ATI Radeon HD 3650 since shader cache addition
### Godot version

4.1 (many ver.)

### System information

Windows 10 - 4.1 (many ver.) - OpenGL 3.3 compatibility

### Issue description

I installed several versions of godot to test, **_as I have a very old computer_**.
i don't know if this is a BUG, or just my OLD Hardware be incompatible.

**HARDWARE:**
intel q6600 quadcore, 4gb ram, windows 10(last update), ATI Radeon HD 3650 - 512mb VRAM.

**OpenGL Extensions Viewer 6.4.1.1:**
OpenGL Version 3.3 (3.3.11672 core profile forward-compatible context)
Driver Version: 8.970.100.9001 (13-jan-15)
DirectX: 10.1, 9
Shader model: 4.1
Vulkan: N/A

VERSIONS TESTED and **WORK** fine:
**3.5.2stable**_win64 -> OK _(NO extra cmds prompt needed)_
**3.6beta2**_win64 -> OK _(NO extra cmds prompt needed)_
**4.0.3stable**_win64 -> OK with some errors but work
**4.1-dev1**_win64 -> OK with some error but work _(see image TOP)_

VERSIONS TESTED and **ALL THAT NOT WORK**:
4.1-beta1_win64 -> don't launch
4.1-beta2_win64 -> don't launch
4.1-beta3_win64 -> don't launch
4.1-dev2_win64 -> don't launch
4.1-dev3_win64 -> don't launch
4.1-dev4-win64 -> don't launch
4.1-rc1_win64 -> don't launch
4.1-rc2_win64 -> don't launch _(see image Bottom)_

* ALL 4.x i have used (**--rendering-driver opengl3 --rendering-method gl_compatibility**)

I would really like to use the latest version (4.1rc2) and later/future the 4.1 stable , but I couldn't get last version it to work at all, not even loading a project directly into the editor.

i have a screenshot showing the las lines of prompt (top is working "4.1_dev1", botton don't work "4.1_rc2)
Screenshot-1

if you need any LOG or other file with details, please let me know which one, and how preferably.

### Steps to reproduce

I don't know what to put here, I explained the best way possible in the description of the problem.

### Minimal reproduction project

N/A

### LINKED ISSUE #85804: AMD R5 M330 graphic issues
### Tested versions

- Reproducible: all godot 4 versions - Godot_v4.2-stable_win64 (last version I tested)
- Not reproducible: before godot 4 versions - I'm currently working on Godot_v3.5.3-stable_win64, and there is no issue

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon (TM) R5 M330 () - AMD A8-7410 APU with AMD Radeon R5 Graphics (4 Threads)

### Issue description

The bug appears as soon as I start godot, all the interface is not properly shown, when I move over any option on the interface with the mouse the interface start to blink and the options are not shown, and I've already tested other godot 4 versions and the problem persist, only on the godot 3 versions the problem is not happening.

### Steps to reproduce

There are not steps, the problem can be noticed on the interface where we create a new project or select an exiting one, any clickeable option triggers this problem.

### Minimal reproduction project (MRP)

https://youtu.be/VTGknO_ML-o

_Production edit: updated the system info_

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/78888
Fixes https://github.com/godotengine/godot/issues/85804

_Production edit: added fix for #85804_

### CODE REVIEW

**Comment by adamscott** [comment]
Cherry-picking for 4.2, as it could fix #85804

**Review by adamscott — APPROVED** [review]
Seems more robust than previously.

**Review by akien-mga — APPROVED** [review]
As discussed on chat, it would be nice to find a place outside `main.cpp` to set all this Windows and GL Compatibility specific metadata. But this creates some architecture questions of where to put it exactly.

Should be fine as is for the time being.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
