### PR TITLE
Make the texture import prompts output point to res:// by default

### PR DESCRIPTION
**Pull request by EIREXE**

### CODE REVIEW

**Comment by akien-mga** [comment]
Isn't it on purpose that it doesn't point to res://, as most of the time one imports stuff from outside the project folder?

**Comment by volzhs** [comment]
@akien-mga yes, right, I do.
this doesn't make sense to me.

**Comment by EIREXE** [comment]
My b on my wording, I meant the output folder, that's what point to res:// by default.

**Comment by reduz** [comment]
I'm not sure what to do about it.. users would originally import files and they would all end up at res:// and then realize too late they should assign a destination folder, so it was removed to avoid users from making this mistake and having to delete files.

The idea is to eventually be able to drop external files into the filesystem dock, ala Unity, which will make the import process easier..

**Comment by volzhs** [comment]
> they would all end up at res:// and then realize too late they should assign a destination folder

I agree with @reduz

**Comment by EIREXE** [comment]
I agree too, since drag an drop will become a thing eventually, closing this.

**Pull request closed without merging**
