### PR TITLE
Fix the grainy sky while using debanding.

### LINKED ISSUE #74140: PhysicalSkyMaterial and ProceduralSkyMaterial debanding doesn't take auto exposure into account
### Godot version

4.0.rc6

### System information

Fedora 37, GeForce RTX 4090 (NVIDIA 525.85.05)

### Issue description

PhysicalSkyMaterial and ProceduralSkyMaterial debanding doesn't take autoexposure into account (to adjust the debanding filter). This causes the sky to become visibly grainy when autoexposure decreases its exposure for dark scenes:

Screenshot_20230301_024322

Viewport debanding doesn't have this issue in comparison.

This occurs both with CameraAttributesPractical and CameraAttributesPhysical, with and without physical light units.

### Steps to reproduce

- Create a new project with a WorldEnvironment copied from the default environment.
- Add a CameraAttributesPractical to the WorldEnvironment. Enable **Auto Exposure** in this CameraAttributesPractical resource.
- Decrease **Background > Energy Multiplier** to `0.01` in the Environment resource.
- Notice the dithering pattern becoming visible on the sky.

### Minimal reproduction project

[physical_light_camera_units_auto_exposure.zip](https://github.com/godotengine/godot/files/10856315/physical_light_camera_units_auto_exposure.zip)

### PR DESCRIPTION
**Pull request by n0tank3sh**
Fixes: #74140

### CODE REVIEW

**Comment by clayjohn** [comment]
Have you tested on the mobile renderer as well? The mobile renderer has a different luminance multiplier than the forward+ renderer as it uses it to increase the usable range of color

**Comment by MightiestGoat** [comment]
@clayjohn  your concerns were right. It doesn't work in mobile mode. I think of two options either we declare a macro in the shader to check which renderer we are using or push `bg_energy_multiplier` to the ubo.  What should I do?

**Review by clayjohn — APPROVED** [review]
Looks good. Indeed on mobile things are bit messed up anyway from having such an underexposed image. The results are still an improvement though

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
