### PR TITLE
Allow plugin name in `is_plugin_enabled`

### LINKED ISSUE #61604: `is_plugin_enabled()` not working as stated in the docs
### Godot version

4.0 0810b0d / 3.5

### System information

Windows 10 x64

### Issue description

Regression from #43734

`is_plugin_enabled()` description says:
```
Returns true if the specified plugin is enabled. The plugin name is the same as its directory name.
```
but in fact it takes full path to cfg file, i.e. `res://addons/myplugin/plugin.cfg` instead of `myplugin`.

Either the docs need update or the method should be changed to use plugin dirs (which might be difficult).

### Steps to reproduce

1. Enable addon
2. Try calling `is_plugin_enabled()` following the description in the docs
3. It will return false

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by pfertyk**
Fixes #61604.

### CODE REVIEW

**Comment by akien-mga** [comment]
There's also `set_plugin_enabled` which likely has the same issue. And the documentation is still incorrect as it now mentions only one of the supported formats, but not both.

IMO, it would be better if only the plugin name was supported, the fully qualified path is not a useful format for this API.

**Comment by pfertyk** [comment]
I've changed the other method as well ;) For now, both support path and name. Let me know if I should change it to name only, or change the docs :)

I'm traveling now, but next week I'll have more time to take a look at #43734 to see if I've missed something ;)

**Review by akien-mga — APPROVED** [review]
This is fine to fix the regression for now but I think this still needs more work, it's a super weird API that requires passing a fully qualified path to the `plugin.cfg`, and the docs are not reflecting this well.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
This doesn't seem relevant for `3.x` which already had this issue fixed in #46389. For some reason this was not forward ported to `master`. @KoBeWi you mentioned the bug affected 3.5, can you check again?

**Comment by KoBeWi** [comment]
Indeed, the issue doesn't happen in 3.5. I incorrectly assumed that it's relevant for this version, because I forgot it was fixed .-.

**Pull request merged**
