### PR TITLE
Fix toggle mode of BaseButton.

### PR DESCRIPTION
**Pull request by ghost**
..which got broken with #11480.

I'd appreciate if someone familiar with UI can take a look at this

### CODE REVIEW

**Comment by Faless** [comment]
@tagcup I'm afraid it needs a bit more work than that.
We might need to properly define the behavior of the new ButtonGroup resource.
I think buttongroup was originally meant to always be radio buttons.
We might need to rearrange when `_unpress_group` is called if we expect `get_pressed_button` to work properly

**Comment by tagcup** [comment]
Can you be a bit more specific?
At least within base_button.cpp, it does seem that pressed state is properly modified before _unpress_group is called, although I'm not sure about the classes that derive from it.

**Comment by tagcup** [comment]
Can you take another look again, this might be a quick solution.

**Comment by tagcup** [comment]
Did a quick test and it appears to be working fine with buttons not in toggle mode. For toggle mode buttons, this restores the old behavior, so should be fine.

**Pull request merged**
