### PR TITLE
Fix swapped front/rear view (reverted)

### LINKED ISSUE #45668: Viewport front/rear view swapped
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
Front/rear view in the viewport is swapped.

In this scene
grafik
selecting
grafik
leads to
grafik

**Steps to reproduce:**
1. open the provided demo
2. open the Demo.tscn
3. click on "Perspective"
4. click on "Front View"
5. observe the blue marker disappear
6. click on "Rear View"
7. observe the blue marker appear

**Minimal reproduction project:**
[WrongCamera.zip](https://github.com/godotengine/godot/files/5913674/WrongCamera.zip)

### PR DESCRIPTION
**Pull request by MrMinimal**
Fixes #45668

### CODE REVIEW

**Comment by akien-mga** [comment]
Given the orientation of Left and Right views, I guess it makes sense for Front and Back to be swapped yeah.

Works well for a character set up this way to face forward (Z-):
Screenshot_20210202_230141

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Comment by jitspoe** [comment]
So this does appear to be technically correct, but it's the opposite of how blender behaves.  I guess blender is technically wrong, since "front" views the back.  My expectation is that hitting 1 on the numpad will result in X being to the right.  I wonder if we keep the correct naming but swap the key binds so that numpad 1 becomes the rear view?

**Pull request merged**
