### PR TITLE
Removed unnecessary semicolons

### PR DESCRIPTION
**Pull request by Muller-Castro**
from **core/ustring.cpp:String::is_valid_ip_address**

### CODE REVIEW

**Comment by ThakeeNathees** [comment]
is this semi colon clang formatted or ? 
https://github.com/godotengine/godot/blob/7579a792bed9881a6afd73c058dfd57441fb5c7a/modules/gdscript/gdscript_parser.cpp#L2248

**Comment by akien-mga** [comment]
I'd prefer not having pull requests removing only a few extra semicolons in a single file, when such occurrences can be found all over the codebase. At this rate we'd need 1000 PRs to remove them all, which seems overkill.

It would be better to rely on tools such as Clang's `-Wextra-semi` warning to locate and remove extraneous semicolons.

**Comment by Muller-Castro** [comment]
Nice! I didn't know about that flag.

Fixing.... !

**Comment by pycbouh** [comment]
It seems you've never got to fixing it. Closing per Akien's comment. Feel free to do a run on the codebase with the flag and fix those codestyle issues in one big PR.

**Pull request closed without merging**
