### PR TITLE
Cherry-picks for the 4.2 branch (future 4.2.2) - 4th batch

### PR DESCRIPTION
**Pull request by akien-mga**
Final(?) batch for 4.2.2 after GDC and Easter holidays which brought another crop of nice-to-have's.
Since I got greedy with cherry-picking this will warrant a RC3 build, but stable can come shortly after that, I'm around to release it this time :)

~TODO: Update changelog.~ Done.

### CODE REVIEW

**Comment by warriormaster12** [comment]
Any chance to get these in?

https://github.com/godotengine/godot/pull/87387
https://github.com/godotengine/godot/pull/89957

**Review by Sauermann — APPROVED** [review]
I had a look at the Input-doc changes. They are good to go.

**Comment by akien-mga** [comment]
> Any chance to get these in?
> 
> #87387 #89957

Probably not for 4.2.2, those are Node changes and thus the potential for breakage is big. There's still this regression report open #89824 (though it's not clear whether the remaining issue is related to your PR).

Could be considered for 4.2.3 with ample testing done in 4.3 dev/beta.

**Comment by tokengamedev** [comment]
IMHO it is time to release the 4.2.2 and 4.1.4. It has been around 3 months in this state. Any additional fixes may go into subsequent releases.

**Comment by akien-mga** [comment]
That's the plan.

**Pull request merged**
