### PR TITLE
Add integer posmod and rename default arg names

### PR DESCRIPTION
**Pull request by aaronfranke**
"posmod" is the integer version of "fposmod". We do not need a "mod" because of the % operator.

I also changed the default arg names from "x" and "y" to "a" and "b" because they are not coordinates. I also changed pow's arg names to "base" and "exp".

### CODE REVIEW

**Comment by fire** [comment]
What is the status of this?

**Comment by aaronfranke** [comment]
I just re-tested and re-based, still works great, should be ready to merge.

**Comment by akien-mga** [comment]
We discussed this on IRC today, and the changes are overall fine, but VisualScript is a bit brittle and serializes its functions as integers, so the new value should be added at the end of the enum, otherwise we'd break compatibility with existing `.vs` files.

**Comment by aaronfranke** [comment]
@akien-mga I made the enum change as discussed on IRC, and also tested the visual script demos. Circle pop is broken on master, the other two work fine on master and this PR, and posmod works.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
