### PR TITLE
DLScript module

### PR DESCRIPTION
**Pull request by karroffel**
This is a first version of the DLScript module. It's fully usable, a few things need to be worked on though.

Most notably the editor integration is disabled by default because it's not that useful without in-editor reloading of libraries. I'll create a patch for that soon.
(If you want to use the editor features without reloading, you have to uncomment line 42 in module/dlscript/dlscript.h)

Some parts of the wrapper API are incomplete, adding those is a very easy task (junior-job maybe?).

### CODE REVIEW

**Comment by punto-** [comment]
that's awesome. how hard would it be to compile for 2.2? does the "api
generator" have to run?

**Comment by karroffel** [comment]
For 2.2 a few ClassDB related things have to be changed, otherwise it should work fine.

The API generator is only important for creating bindings. So no, you don't need to run it.

The API generator generates a JSON file that other programs can use to create bindings for different languages. For example this [Rust program](https://github.com/GodotNativeTools/cpp_bindings/tree/master/binding_generator) that generates a C++ API

**Comment by toger5** [comment]
A little off topic. Do you want to do a short low effort youtube video. Showing how to use it from creating the library to writing a little script.

**Comment by karroffel** [comment]
@toger5 I wanted to write a blog post when it's merged. I don't like videos that much

**Pull request merged**
