### PR TITLE
Fix GLES3 GPUParticles3D not working in HTML export

### LINKED ISSUE #75270: GPUParticles2D not emitted in web export
### Godot version

4.0.1.stable

### System information

Windows 10, NVIDIA GeForce GTX 960M (31.0.15.3141), GLES3

### Issue description

GPUParticles2D are not displayed when exporting for web. CPUParticles2D appear to work as expected but the GPUParticles2D displays nothing upon playing the exported project in a browser. 

I've tested in Chrome and Firefox using both Forward+ and Compatibility renderers which all produce the same result for me. Additionally, I've tested a similar project exported using Godot 3.5.2 GLES3 and found that both particles are displayed and emitting correctly in that version.

### Steps to reproduce

1. Create a new project using either Forward+ or Compatibility renderer
2. Create a main scene with Node2D as the root node
3. Set up a CPUParticles2D node and a GPUParticles2D node as child nodes
4. Export for web with default settings
5. Deploy a dev server to play/debug the exported web project

### Minimal reproduction project

[Web Particle Test.zip](https://github.com/godotengine/godot/files/11055295/Web.Particle.Test.zip)

### PR DESCRIPTION
**Pull request by cody82**
This fixes issue #75270

I replaced switch with if and it works for me.

For 3.x this fix is not needed. I only encountered this on the 4.0 branch.

_Production edit: Fixes #75270_

### CODE REVIEW

**Comment by AThousandShips** [comment]
The `else if` should be placed on the same line as the closing bracket like so `} else if`

**Comment by cody82** [comment]
Fixed

**Review by clayjohn — APPROVED** [review]
Great work!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
