### PR TITLE
String: Add contains().

### PR DESCRIPTION
**Pull request by AnilBK**
Add and use `contains()` instead of  `find(p_str) != -1`.

The functionality is similar to `has()` of other godot containers.
https://github.com/godotengine/godot/blob/ca42bfb2a5c91a52ea14302aa3bbf7292e387b9b/core/templates/vector.h#L98

Many languages have `contains()` to find if string contains a sub-string. Or, [C++23](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1679r0.html) is also supposed to have that, so left as contains() instead of has().

### CODE REVIEW

**Comment by aaronfranke** [comment]
`contains` was briefly discussed in this PR: https://github.com/godotengine/godot/pull/32144#issuecomment-531587582

I think it's a better name, but it seemed unpopular compared to just keeping `has`.

**Comment by akien-mga** [comment]
> Not exposed to GDScript as `in` operator is suggested for that.
> [docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-find](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-find)

I think it should still be exposed since it's available, and it's needed to make it available for other language bindings via GDExtension.

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

**Comment by AnilBK** [comment]
> > Not exposed to GDScript as `in` operator is suggested for that.
> > [docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-find](https://docs.godotengine.org/en/stable/classes/class_string.html#class-string-method-find)
> 
> I think it should still be exposed since it's available, and it's needed to make it available for other language bindings via GDExtension.

I added another commit to expose it, docs and tests. Once that's reviewed and OK, I can merge both the commits.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
