### PR TITLE
Fix editor progress dialog theme update.

### LINKED ISSUE #71351: Godot 4 beta12: "Building project" window is using a separate theme from the rest of the editor.
### Godot version

Godot 4 beta 12

### System information

Windows 10

### Issue description

tttttt

### Steps to reproduce

Run a project in Godot 4 beta 12

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixed https://github.com/godotengine/godot/issues/71351

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good to me. Tested locally and it fixes the issue for me

**Comment by YuriSizov** [comment]
Well, that's not what I meant. We should assign the theme to the main window instead. `get_window()->set_theme(theme)` from the `EditorNode`. We shouldn't assign the editor theme to individual nodes.

**Comment by bruvzg** [comment]
> `get_window()->set_theme(theme)` from the `EditorNode`

This also works, updated PR.

Note: it's not possible to set from constructor, there's no window at this point, so added it to `NOTIFICATION_ENTER_TREE`.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
