### PR TITLE
Refactoring: Erase for (int i = 0; i < 1; i++)

### PR DESCRIPTION
**Pull request by theludovyc**
Hello =) !

I work on https://github.com/theludovyc/Godot_STL and I found this ^^ !

### CODE REVIEW

**Comment by groud** [comment]
Hmm, I think this code was there because `real_t scales[] = { 1.0 };` is supposed to have more elements. Hence the TODO.

I believe it might be better to leave the code this way until the TODO is solved.

**Comment by theludovyc** [comment]
So we can erase scales and have :
int w = ceil(p_width);
int h = ceil(p_height);

Or for (int i = 0; i < scales.width() ; i++ )

?

**Comment by groud** [comment]
> So we can erase scales and have

If you read the TODO, different scales should be usable. So no.

@vnen I see you wrote this code, WDYT ?

**Comment by vnen** [comment]
I don't mind simplifying the code, since only one scale is supported, but the TODO comment needs to remain. TBH It's been a long time since I wrote this and I'm not sure what I had in mind back then.

**Pull request closed without merging**
