### PR TITLE
Partial revert "Fix two signal errors"

### PR DESCRIPTION
**Pull request by nathanfranke**
This partially reverts commit a31bc1b0ba608ef340068676f6709621a37f2140.
From this PR: #36340

Possible compatibility issues with #35864 that I am not sure about.

~~Also, do I need to change "connect" to "connect_compat"? (#36368)~~

### CODE REVIEW

**Comment by akien-mga** [comment]
This is only a partial revert so it would be good to make it clear in the commit log.

You should use `connect_compat` yes.

**Comment by nathanwfranke** [comment]
Sorry for the delay, forgot about your message!

**Comment by akien-mga** [comment]
> EDIT: Also shouldn't I use `connect` because I use `Callable`?

Right, I misread. It's good as is.

Could you amend the commit message too?

**Comment by nathanwfranke** [comment]
Done

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by nathanwfranke** [comment]
@rxlecky now that this is merged it should be ready for any fixes you want

**Comment by rxlecky** [comment]
Cheers! Just poked Rémi to have a look at my submitted fix. And thanks for bringing up this issue as well. It turned out to be an issue in the core Variant code that would go unnoticed for a while. And the camera override code would malfunction too. :)

**Pull request merged**
