### PR TITLE
Improve area/body_shape_entered/exited signals parameter names and doc

### PR DESCRIPTION
**Pull request by MaxLap**
This is improving the documentation (and, I believe, the signal templates) for these signals:
* area_shape_entered
* area_shape_exited
* body_shape_entered
* body_shape_exited

Here are the improvements, I made a separate commit per improvement:
* Some doc used `body_id` or `area_id` instead of the `_rid` that is written elsewhere
* I added a `_index` suffix to the  `body_shape`, `area_shape` and `local_shape` parameters. This has 2 benefits:
  * More intuitive when reading the name
  * Allows to then use `var body_shape: Node = body.shape_owner_get_owner(body_shape_index)`. Before, `body_shape` would have been taken by the `int` parameter.
* Added code to get the actual node from those `_index` arguments.  
  It took me a while to find it when I needed it, and when I did, I wasn't sure if that was valid for more recent Godot versions until I tried it.

All of those changes would also be great improvements for Godot 3.3 documentation (and maybe farther back, but I am not familiar with older versions)

### CODE REVIEW

**Comment by MaxLap** [comment]
Sure, squashing is done.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Thanks for the squash and fixup!

> All of those changes would also be great improvements for Godot 3.3 documentation (and maybe farther back, but I am not familiar with older versions)

It is IMO unlikely to be backported to 3.x as all these changes break compatability by changing method signatures, which we generally try to avoid in minor releases AFAIK.

(This PR is somewhat relevant to https://github.com/godotengine/godot/issues/16863)

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Looks great, thanks!

Just left a comment for a minor improvement in the documentation, otherwise it should be good to go.

**Comment by MaxLap** [comment]
Added the change and squashed everything together

**Review by pouleyKetchoupp — COMMENTED** [review]
No worries :) I've added comments on a few last things to fix before merging.

**Review by pouleyKetchoupp — APPROVED** [review]
Looks all good!

**Comment by pouleyKetchoupp** [comment]
Congrats on your first merged PR.

Please let me know if you're up for doing the 3.x version, otherwise I can take care of it.

**Comment by pouleyKetchoupp** [comment]
Thanks! Some file names are also different, but I think that should be it.

**Pull request merged**
