### PR TITLE
Fix  `Label` and `RichTextLabel` `visible_characters` and `percent_visible` methods.

### LINKED ISSUE #49189: Label/RichTextLabel doesn't respond to visible_characters/percent_visible
**Godot version:**
364ea7f280a3f074795e542b16b1d0ec76cf6ce2
Godot Engine v4.0.dev.custom_build.364ea7f28

**OS/device including version:**
Windows 10 Pro 10.0.19042
Vulkan API 1.2.162
Using Vulkan Device #0: NVIDIA - GeForce RTX 2060 SUPER

**Issue description:**
image
Displayed text won't respond to visible_characters and barely responds to percent_visible. Gif demonstrating it:
pls fix
This happens no matter the text length and/or font.

**Steps to reproduce:**
1. Add a RichTextLabel to your scene
2. Enable BBCode and write some text in the BBCode section.
3. Toy with visible_characters/percent_visible

**Minimal reproduction project:**
Can be done in the editor.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #49189 and #51614
Supersedes #51884
*Bugsquad edit:* Fixes https://github.com/godotengine/godot/pull/51884#issuecomment-922341357

Note: Now both `Label` and `RichTextLabel` apply `visible_characters` before shaping, therefore text will be displayed in the same way as it looks when you input/delete it (last character is not connected to invisible next), this seems logical to me, but it's possible that cutting it after shaping is more desired in some cases (this can be done using trimming added #50086, but probably should be done as a separate property, if it is requested).

https://user-images.githubusercontent.com/7645683/133964234-15bd9bcd-d6b7-4699-850f-aadc3db4db95.mov

https://user-images.githubusercontent.com/7645683/133965291-4653a9ec-c6f9-4586-a7e4-a890e6d9a51b.mov

### CODE REVIEW

**Comment by akien-mga** [comment]
> Note: Now both `Label` and `RichTextLabel` apply `visible_characters` before shaping, therefore text will be displayed in the same way as it looks when you input/delete it (last character is not connected to invisible next), this seems logical to me, but it's possible that cutting it after shaping is more desired in some cases (this can be done using trimming added #50086, but probably should be done as a separate property, if it is requested).

I asked about this on Twitter and got two users confirming that was you implemented is what they would expect: https://twitter.com/Akien/status/1439260643434053633

I could also see a use case for shaping before trimming, e.g. if one wants to achieve a look of "someone is hand-writing" instead of "someone is typing", but indeed this would likely need to be added as a separate property. We can wait for the need to be confirmed by actual users making games in Arabic or Indic scripts instead of anticipating the need I think.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Tested locally, works great :)

https://user-images.githubusercontent.com/4701338/133972551-d5b95351-5c89-4f18-8f5d-5c1fcec95eca.mp4

**Comment by akien-mga** [comment]
Thanks!

**Comment by pombomakesstuff** [comment]
If the connected graphemes are being animated as a whole (#52890), it's more consistent to display them as a whole (apply `visible_characters` _after_ shaping), instead of displaying them as they're typed.

(I'm not a RTL script user, but the implemented behavior seems inconsistent compared to Latin script)

**Comment by akien-mga** [comment]
@pombomakesstuff See https://github.com/godotengine/godot/pull/52860#issuecomment-922681598, I did ask RTL script users and they said that the implemented behavior is what they would expect. Might need more opinions for sure but I'd wait for RTL script users to actual request the other option before considering it.

**Comment by bruvzg** [comment]
> If the connected graphemes are being animated as a whole

Only for the default position shift effects (`wave`, `shake`, `tornado`). Color changes as well as any custom effects are still applied to the individual glyphs.

Applying `visible_characters` after shaping will leave a sharp cut of the connected grapheme, while it might be useful as a part of a more complex effect, the default `fade` effect is probably more suitable for this.

Screenshot 2021-09-22 at 10 03 13

**Pull request merged**
