### PR TITLE
[Core] Add `LocalVector::has` for convenience

### PR DESCRIPTION
**Pull request by AThousandShips**
Not too many cases but useful for parity and clarity

Came across the discrepancy when working on:
* https://github.com/godotengine/godot/pull/91619

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by AThousandShips** [comment]
Will open a godot-cpp PR as well

**Review by smix8 — APPROVED** [review]
Yes please.

The navigation module NavMap also has a lot of uses of the LocalVector find() that you could likely replace if you feel like it.

**Comment by AThousandShips** [comment]
Couldn't find any in there but will add any I find and squash

**Comment by akien-mga** [comment]
Thanks!

**Comment by rburing** [comment]
Shouldn't this have `_FORCE_INLINE_`?

**Comment by AThousandShips** [comment]
It is missing from several short methods here, and should happen with any decent compiler, would be worth going over cases generally though here

**Pull request merged**
