### PR TITLE
Fix clang performance problem in PoolVector

### PR DESCRIPTION
**Pull request by ghost**
At least under clang, there seems to be a performance problem with `PoolVector` due to the initialization and destruction of fundamental types.

I detected this while profiling saving a scene (using an optimized `target=release_debug` build):

without-pr

Further analysis shows that inside a `PoolVector<uint8>::resize()` heavy looping goes on:

loop

Eliminating the initialization loops for fundamental types in `PoolVector` (this PR) drops the impact of `PoolVector::resize` inside `ViewportTexture::get_data()` to < 1%:

with-pr

### CODE REVIEW

**Comment by reduz** [comment]
We're not using C++11 in Godot, so a macro like this will probably need to be made manually.
Also, I think the right fix is to just inline the placement operators, not sure why they are not.

**Comment by poke1024** [comment]
Don't know why clang does what it does. Even if I define

```
class Write : public Access {
	public:
		_ALWAYS_INLINE_ T &operator[](int p_index) const { return this->mem[p_index]; }
```

and build with

`scons platform=osx target=release_debug`

I still get

profile

`_ALWAYS_INLINE_` `_post_initialize` shouldn't be there either of course.

If anyone's wondering, I'm on

```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
```

Changed the PR to add a minimal `typetraits.h` loosely adapted from https://github.com/boostorg/type_traits/blob/develop/include/boost/type_traits/is_scalar.hpp. No enums, no member pointers, but good enough to fix the problem for ints, floats, pointers.

**Comment by hpvb** [comment]
LGTM (after the changes)

**Comment by poke1024** [comment]
Re-checking this today, I found out I messed up my builds - sorry for not seeing this. With proper `release_debug` building, there's no problem here and clang's optimizer inlines everything. Can be closed.

**Pull request closed without merging**
