### PR TITLE
Fix cursor stuck on HSplit in Advanced Importer

### LINKED ISSUE #84002: HSplit cursor gets stuck in Advanced Scene Importer when hovering 3D preview
### Godot version

06d51891678e3abf360d6fcd2e8bd1ba96704fcc

### System information

Windows 11

### Issue description

When highlight the split container, the cursor will change the HSplit cursor, but will not return back to normal if the cursor then moves over into the 3D preview until the cursor is taken completely out of it.

### Steps to reproduce

Open advanced scene importer.
Highlight draggable left or right edge of 3D preview.
Move cursor into 3D preview.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by SaracenOne**
Very minor cosmetic bug fix.
Closes https://github.com/godotengine/godot/issues/84002

### CODE REVIEW

**Comment by YuriSizov** [comment]
Doesn't look like a minor or cosmetic bug. Seems like a bug with input handling in subviewports. I'm not sure this is a good solution, or indeed a good workaround.

**Comment by SaracenOne** [comment]
Hmm...I can try and investigate this a bit deeper later on. The root cause seems to be that SubViewportContainer has special handling in _gui_input_event where it doesn't update the cursor if it's over one. I assume what it's meant to do is derive a cursor from the contents of the viewport, but since the viewport doesn't have an Control elements inside it, it may not be updating:
```
		if (DisplayServer::get_singleton()->has_feature(DisplayServer::FEATURE_CURSOR_SHAPE) && !Object::cast_to<SubViewportContainer>(over)) {
			DisplayServer::get_singleton()->cursor_set_shape(ds_cursor_shape);
		}
```

**Comment by akien-mga** [comment]
CC @Sauermann

**Comment by akien-mga** [comment]
Superseded by #84661.

**Pull request closed without merging**
