### PR TITLE
Fix GridContainer's children visibility breaking the layout

### LINKED ISSUE #18339: GridContainer child visibility inconsistenties/bugs.
**Godot version:**
Happens in both a build of 7d6f210ccb5de9ef414f94ad42f9f3dea14c0493 *and* 3.0.1. 

**OS/device including version:**
macOS 10.13.4, but also happens on Windows.

**Issue description:**
`GridContainer` handles setting visibility of its children rather poorly. It *seems* to want to ignore them but it just hates it.

Here's a simple grid with 3 columns and 4 rows:

image

When you hide a panel, instead of putting a gaping hole there, `GridContainer` shifts up everything on the row to the left:

image

This already seems highly useless because it only shifts the *row*, not every grid element.

It gets worse! When you hide the first element of any row past the first, it renders the row *on the previous row*:

image

This is obviously a glitch.

So the question is, what should `GridContainer` do? I can think of two things. Either it completely ignored the visibility, just leaving a hole for invisibles:

image

Or it should completely skip them, so it'd look more like this:

image

Personally I'd say making it an option on `GridContainer` (between full skip and gaping hole, NOT the old behavior).

**Minimal reproduction project:**
[grids?.scn.zip](https://github.com/godotengine/godot/files/1934766/grids.scn.zip)

### PR DESCRIPTION
**Pull request by groud**
Fixes #18339

### CODE REVIEW

**Comment by PJB3005** [comment]
May I suggest an option that toggles it between leaving holes and this behavior? Both code be useful.

**Comment by groud** [comment]
Why not, but it's out of the scope of this PR.
It's also easily workaroundable by replacing hidden nodes by basic Control. So not sure if it is worth.

**Comment by akien-mga** [comment]
I assume that it can't be cherry-picked into `3.0` as it would break compat for people relying on the (wrong) behaviour?

**Comment by groud** [comment]
Hmm. I'm not sure à lot of people rely on the wrong behavior. It seems pretty unpredictable to me (like the number of items on a row changing).
I'd say it's worth cherry picking but I might be wrong

**Comment by groud** [comment]
On the other hand what's the point of 3.0.x if we don't fix bugs. ^^
But I fully understand, if you think it's not worth breaking the API, then it's better not to cherry-pick. I can't tell what's the best solution.

**Pull request merged**
