### PR TITLE
Remove Transform2/3D,AABB,Basis from Variant destructors given they are POD structs

### PR DESCRIPTION
**Pull request by touilleMan**
This is useful in `extension_api.json` to avoid having `"has_destructor": true`  for those types where it's clearly not the case

### CODE REVIEW

**Comment by lawnjelly** [comment]
Just to note that although these types don't have a destructor, the Variant that holds them definitely _does_ need to be destructed to avoid a memory leak, as they are held as pointers from the Variant. No idea which this PR is referring to (I know nothing about extensions etc) but wanted to point this out just in case.

**Comment by aaronfranke** [comment]
Building on what @lawnjelly said, if we need destructors for all types that store pointers in Variant, then the new `Projection` type should be added to the list of types here.

**Comment by touilleMan** [comment]
> Just to note that although these types don't have a destructor, the Variant that holds them definitely does need to be destructed 

`extension_api.json` expose an API to create the builtins types outside of the `Variant`, this useful when calling builtin/classes methods with ptrcall (i.e. C function pointer with parameters provided as pointer on the concrete type instead of variant with dynamic type check)
For this reason there is a difference between the "C struct" style builtins (`Vector2` for instance) that are only a bunch of scalars and more complex builtins (e.g. String, Dictionary) that use heap allocation and hence require a destructor

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
