### PR TITLE
Incomplete Traditional Chinese translation(zh_HK)

### PR DESCRIPTION
**Pull request by ZX-WT**
probably can be used as zh_TW translation

### CODE REVIEW

**Comment by akien-mga** [comment]
Nice! How similar/different are zh_HK and zh_TW, and do you know if systems using a zh_TW locale would fallback to zh_HK automatically? In most projects where I work on translations it's typical to see both zh_CN and zh_TW, but I more rarely see zh_HK.

**Comment by ZX-WT** [comment]
In terms of language, I think zh_HK and zh_TW are almost the same, maybe they have different preference of words for translation. I would verify this later. The main difference should be things like unit and currency, which will not appear in Godot. Maybe we can unify them into Traditional Chinese which is the common way in other software. We have no rush, for now, just separate it.

**Comment by Geequlim** [comment]
@ZX-WT I don't think these are too many differences in zh_HK, zh_TW and zh_CN.

**Comment by ZX-WT** [comment]
@akien-mga Are we planning to add auto detection for the future? If so, this might be the reason to keep it separated. I just separate them because the doc stated that godot uses the Linux locale for handling translation. But, for the editor, do we have to follow that? I suggest we just use zh_TW, people know that is traditional Chinese. I need to wait for someone that will contributed to zh_TW for further discussion.

**Comment by akien-mga** [comment]
On Linux it detects the system locale automatically.

**Pull request merged**
