### PR TITLE
[Windows] Cleanup COM library initialization/uninitialization.

### LINKED ISSUE #73039: Godot 4 beta versions after 7 does not launch
### Godot version

4.0 RC1

### System information

windows 11, nvidia gtx 970m

### Issue description

The last version i could launch is godot 4.0 beta 7. After that, no version of godot is launching. I tried;

- clean install windows 11
- upgrade graphic driver
- downgrade graphic driver
- C sharp version of godot

nothing works. I used console, lauched godot from command prompt etc. no error message shows up. I believe, some feature that is introduced at 4.0 beta 8 introduced a bug that prevents godot from running on certain systems. Maybe, related to vulkan i don't know.

### Steps to reproduce

launch godot on specific system

### Minimal reproduction project

launch godot on specific system

### PR DESCRIPTION
**Pull request by bruvzg**
Should fix https://github.com/godotengine/godot/issues/73039

### CODE REVIEW

**Comment by Ranoller** [comment]
I will try tonight and put here the results. Thanks for the work.

**Comment by Ranoller** [comment]
It works, godot doesn´t crash on startup. Well done.
I don´t know if this can break anything, but if not, this commit is a good new to master branch. (Needed in 4+ branches but not in 3+ branches)

This should fix:
https://github.com/godotengine/godot/issues/74288
https://github.com/godotengine/godot/issues/73039
https://github.com/godotengine/godot/issues/74396
https://github.com/godotengine/godot/issues/71835 (archived but not really fixed)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
