### PR TITLE
Fix GPUParticles are not rendered for older AMD GPUs with OpenGL+Angle (reverted)

### LINKED ISSUE #95797: `GPUParticles` not rendered in Web Export or Windows ANGLE with `AMD Radeon RX Vega 6-7` GPU
### Tested versions

- Reproducable in Godot 4.3.dev6 -> Godot 4.3

### System information

Windows 10, AMD Ryzen 5 4500U (GPU: AMD Radeon RX Vega 6 (Ryzen 4000/5000))

### Issue description

**EDIT:**
**Solution 1**
-
I found a settings in Chrome that actually fixes the `GPUParticles`: (chrome://flags/)
image
This is set to `Default`,- if it is set to `OpenGL`, everything works. If it is set to `D3D11` or `D3D11on12`, it doesn't for the below mentioned AMD hardware combinations.

As also written in the description, `D3D11` seems to be used as the default for most Windows machines, but it will break `GPUParticles` for some hardware combinations.

**Solution 2**
-
Turning off `graphic acceleration` in Google Chrome fixes the issue as well (although `GPUParticles` will lag now)
image

---

- After testing my game on different Hardware, there seems to be a problem with AMD GPUs when rendering `GPUParticles` on a Web Build.
- The Browser doesn't matter, it doesn't work with every Browser (Edge, Chrome, Firefox)
- There are no errors in the console
- There is still the typical particle render lag the first time it should be shown, but nothing is rendered

`GPUParticles` are not rendered in a Web Build for the following Hardware:

```
CPU: AMD Ryzen 5 4500U
Integrated GPU: AMD Radeon RX Vega 6
```

```
CPU: AMD Ryzen 5 5600U
Integrated GPU: AMD Radeon RX Vega 7
```

```
CPU: AMD Ryzen 7 5825U
Integrated GPU: AMD Radeon RX Vega 8 
```

This combination however works:

```
CPU: AMD Ryzen 7 5700U
Integrated GPU: AMD Radeon RX Vega 8
```

The native binary works and renders the `GPUParticles` (which uses Forward+ (Vulkan)).

It seems that every other Hardware works as of now.
Tested with Intel (iGPU) and Nvidia GPU.

If there is anything I can try, let me know.

### Steps to reproduce

- Open the project, particles should not visible in the editor, also when running

OR

- Run in your Browser: https://maran23.itch.io/space-heist - Start a level, compare with the screenshots

### Minimal reproduction project (MRP)

[ParticleBug.zip](https://github.com/user-attachments/files/16789243/ParticleBug.zip)
OR
Open and run in your Browser: https://maran23.itch.io/space-heist

### PR DESCRIPTION
**Pull request by Maran23**
Fixes: https://github.com/godotengine/godot/issues/95797

Using the algorithm (bottom of the paper) as proposed by @clayjohn: https://www.researchgate.net/publication/362275548_Accuracy_and_performance_of_the_lattice_Boltzmann_method_with_64-bit_32-bit_and_customized_16-bit_number_formats

Made sure that my fix does not cause any regressions (see project below):
- https://github.com/godotengine/godot/issues/72882
- https://github.com/godotengine/godot/issues/71731
- https://github.com/godotengine/godot/issues/66462
- https://github.com/godotengine/godot/issues/66459
- https://github.com/godotengine/godot/issues/73320

This should be reviewed by someone much more familiar than me.

`GPUParticles` now work fine for older AMD GPUs as specified in the issue, as well as e.g. my much newer GPU, that did not suffer from this problem (works before, works after).
I plan to test this on other GPUs as well soon.

---

cc @Alex2782 - testing on an Adreno 3xx device would be nice as well :)
cc @JonqsGames - since you did the initial change that caused this 'regression' in https://github.com/godotengine/godot/pull/72914
cc @clayjohn - as you wrote and reviewed most of the OpenGL stuff :D

---

Project for testing, that contains all issues we once had regarding the conversion:
[ParticleBug.zip](https://github.com/user-attachments/files/16830007/ParticleBug.zip)

Everything is named like to GH issue and it is 'linked' in the description so you can check everything fast.
| image | image |

---

Tested project above on:
- AMD Ryzen 5 4500U with integrated AMD Radeon RX Vega 6 (broken before)
- Intel(R) Core(TM) i5-4670 CPU with dedicated AMD Radeon RX 580 Series (broken before)
- AMD Ryzen 9 5900X with dedicated AMD Radeon RX 6900 XT
- AMD Ryzen 7 5800X3D with dedicated NVIDIA GeForce RTX 4070 Ti

### CODE REVIEW

**Comment by Alex2782** [comment]
OK on LG Nexus 7 - `Adreno 320`  (MRP #88815 and "2D Platformer Demo")

**Comment by Maran23** [comment]
> I have commented out all “renames”, 2D Platformer also looked normal, should other MRP be tested?

Particles and Shader are most important here.

Maybe your Adreno device is fine? I'm not really into the 'Adreno problems', but checking the git history:
- https://github.com/godotengine/godot/pull/69521 Added some redefines of the `un/pack` method due to wrong Adreno exposure of ES310 methods
- https://github.com/godotengine/godot/pull/88816 Added some redefines of the `un/pack` method due to buggy Adreno implementations of that methods

If you are lucky, you do not suffer from any of those problems of that wrong exposure or buggy implementation of the `un/pack` methods.
In any case, if everything still works (completely the same WITH and WITHOUT the `un/pack methods`), we are actually very good to go here!
A device with the correct implementation of the `un/pack` methods (without redefines) should behave the same as with our redefined `un/pack` methods.

**Comment by clayjohn** [comment]
Hmmm, this section of code created a lot of problems for us (as you can see in the history). The old `if (h_e == uint(0x0000)) {` actually was broken on certain AMD devices (https://github.com/godotengine/godot/issues/73320). It was fixed by making the code branchless in https://github.com/godotengine/godot/pull/73332. I suspect that this change will reintroduce https://github.com/godotengine/godot/issues/73320. 

We should introduce the same logic in a branchless manner like in https://github.com/godotengine/godot/pull/73332

Or perhaps we should do something more robust and use the "ultrafast method" from https://www.researchgate.net/publication/362275548_Accuracy_and_performance_of_the_lattice_Boltzmann_method_with_64-bit_32-bit_and_customized_16-bit_number_formats (described here: https://stackoverflow.com/a/60047308)

**Comment by clayjohn** [comment]
Given that https://github.com/godotengine/godot/issues/95797 only happens with ANGLE, I suspect it is more likely a precision issue rather than a problem with the actual conversion. Its likely that inserting the branch just forces different codegen by the driver. 

I would see if using high precision helps before committing to changing the conversion code.

**Comment by Maran23** [comment]
> The old `if (h_e == uint(0x0000)) {` actually was broken on certain AMD devices (#73320).

Funny enough, the lines did not appear still on all the older AMD devices I tested. And also fixed by this PR.
I will check the "ultrafast method" (which is very similar to what we do already).

> I would see if using high precision helps before committing to changing the conversion code.

Is this something you will check? I can help with testing if needed!

**Comment by clayjohn** [comment]
> Is this something you will check? I can help with testing if needed!

I don't have a device that can reproduce your issue, so I can't really check. 

I am just skeptical about this solution as it removes the check for 0 exponent and replaces it with a check for infinity. Both might be needed, but its clear the root of the problem is bad code gen by the driver. Since OpenGL works fine on the same hardware I suspect the issue comes from the different between OpenGL and OpenGL ES. The most likely culprit is floating point precision as desktop GL drivers almost always ignore precision.

**Comment by Maran23** [comment]
Tested the new fast algorithm solution and it works! Works for my system where everything was good before, and also worked for the broken system. Can check with other GPUs in the next days as well (e.g. Intel and Nvidia). Adreno device would be nice as well.

Checked that the following issues do not reappear (as in the project attached on this PR):
- https://github.com/godotengine/godot/issues/72882
- https://github.com/godotengine/godot/issues/71731
- https://github.com/godotengine/godot/issues/66462
- https://github.com/godotengine/godot/issues/66459
- https://github.com/godotengine/godot/issues/73320

**Review by clayjohn — APPROVED** [review]
Oh well. This approach is a few more instructions than we had before which is not ideal, but it is more correct and handles more edge cases.

I looked into my precision theory deeper and I am not sure, in theory all unspecified floats and ints should be high precision. So it may be something else in the driver code gen causing the issue. 

Since you have confirmed that this works using many of the prior bug reports I think it makes sense to go with this.

The final thing is the licensing issue. There were concerns expressed about the licence previously. Since the code is basically a one-liner, I don't think a licence can be attached to it. The FSF considers any chunk of code fewer than 15 lines to be too trivial to copyright.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
