### PR TITLE
Make `EditorPropertyNameProcessor` check `EditorSettings` validity

### PR DESCRIPTION
**Pull request by AThousandShips**
`EditorSettings` is not guaranteed to be initialized at this point, the above access to editor settings uses a check, added a missing check here as well, was causing non-destructive errors on running the editor

Regression from #74264

### CODE REVIEW

**Comment by akien-mga** [comment]
Doesn't that mean that this code will never run, if EditorInspector is instantiated too early in the normal editor startup?

The previous check mentions specifically that it's when generating docs (`godot --doctool`) that this case can happen, not at normal runtime. If this error happens at runtime then it hints at a bigger issue, and this setup should likely be moved to `NOTIFICATION_READY` or similar.

**Comment by AThousandShips** [comment]
Doing that removes the error as well, would have to confirm that it still does what it is supposed to do as I'm not sure what it does

**Comment by timothyqiu** [comment]
`use_settings_name_style` makes the `property_name_style` property track what the editor setting is set to. Moving the code into `READY` will leave the property unsynced before entering the tree.

`EditorPropertyNameProcessor` assumes `EditorSettings` is always available. The problem still exists as long as you access `EditorPropertyNameProcessor` helper methods before `EditorSettings` is initialized. I think the three `EDITOR_GET`s there should get a default value when `EditorSettings` is not initialized.

https://github.com/godotengine/godot/blob/74c34aed38cecf502c257938d268d5f522557a0e/editor/editor_property_name_processor.cpp#L38-L58

Something like:

```c++
EditorPropertyNameProcessor::Style EditorPropertyNameProcessor::get_default_inspector_style() {
	if (!EditorSettings::get_singleton()) {
		return STYLE_CAPITALIZED;
	}
	const Style style = (Style)EDITOR_GET("interface/inspector/default_property_name_style").operator int(); 
	if (style == STYLE_LOCALIZED && !is_localization_available()) { 
		return STYLE_CAPITALIZED; 
	} 
	return style; 
} 

EditorPropertyNameProcessor::Style EditorPropertyNameProcessor::get_settings_style() {
	if (!EditorSettings::get_singleton()) {
		return STYLE_LOCALIZED;
	}
	const bool translate = EDITOR_GET("interface/editor/localize_settings"); 
	return translate ? STYLE_LOCALIZED : STYLE_CAPITALIZED; 
}

bool EditorPropertyNameProcessor::is_localization_available() {
	if (!EditorSettings::get_singleton()) {
		return false;
	}
	const Vector<String> forbidden = String("en").split(","); 
	return forbidden.find(EDITOR_GET("interface/editor/editor_language")) == -1; 
} 
```

**Comment by AThousandShips** [comment]
Will test out!

**Review by timothyqiu — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Pull request merged**
