### PR TITLE
Move most "drivers" as toggleable "modules" and split their thirdparty libraries in an own tree

### PR DESCRIPTION
**Pull request by akien-mga**
Should address most of #6157.

While working on this, I got a bit more scons experience and could isolate most modules (and some of the remaining drivers) in their own environment, which means that their necessary defines and include paths can now be passed without polluting the global env. It means we could drop some dirty hacks we put in several thirdparty sources to hardcode include paths so that they match our repo, etc. There is also no more risk of confusion between headers of different projects that share the same name.

Most libraries that are typically available on a Linux distribution can be unbundled (i.e. you can just delete their `thirdparty/$libname` folder and build with `libname=system`). Some more work will be needed to put some order in the scons options as it's a bit messy now, but I'll do all this in a later PR. Currently only `platform/x11` has instructions to link against system libraries when `system` options are chosen, but it could be extended for other relevant platforms.

To disable a module, the syntax is now automatic: `module_$module_enable=yes|no` (see `scons --help`). We might have to document this a bit better in the official compilation docs, and also rename the current arguments I used to specify the use of builtin or system libraries for more clarity (e.g. `openssl=system` could become `system_openssl=yes` or `builtin_openssl=no`.

All in all, this was quite a lot of work and I might have made a few mistakes along the road. Therefore I'd appreciate:
- extensive testing on all supported platforms and whenever possible also with some exotic options (e.g. disabling an important module and check that the rest of the engine still builds and runs ok).
- code review especially of the various SCsub files.

That should be a first step towards making it **much** easier to maintain our thirdparty code, and also to get Godot packaged in Linux distributions.

### CODE REVIEW

**Comment by akien-mga** [comment]
Alright, as expected it doesn't build out of the box :) Should have try to remove some system headers to ensure built-in libraries are ok. It looks like having made the ogg module build in its own env hid it for theora/vorbis/opus which need it, will fix.

**Comment by akien-mga** [comment]
Rebase to fix a few things:
- png: "png" option renamed to "libpng", can't be disabled anymore (only "system" or "builtin", no "no", as it makes little sense to use Godot without png support)
- ogg/vorbis/opus/theora: fixed including ogg headers for vorbis/opus/theora and vorbis headers for theora when those are builtin
- theora: fixed thirdparty/libtheora where headers were placed in the wrong folder which did not match system wide includes (also added missing description of the thirdparty folder in thirdparty/README.md)
- rtaudio: undid changes to isolate the env as platform/windows includes this driver and therefore needs the include path to the thirdparty header
- squish: tried a new trick to disable the module in config.py when not building tools (it seems to failed building on iphone due to a half-initialized module, let's see how it goes)

**Comment by akien-mga** [comment]
After a few hours of trial and error, it seems like it now builds fine for all platforms on our travis tests. I'd love to have people testing the PR on Windows though, both using MSVC and MinGW.

**Comment by akien-mga** [comment]
Fixed a wrong include path for winrt. According to @vnen it now builds fine with MSVC for both windows and winrt.

**Comment by akien-mga** [comment]
I'm testing a build of all templates using this PR: https://travis-ci.org/GodotBuilder/godot-builds/builds/167937894 https://ci.appveyor.com/project/GodotBuilder/godot-builds/build/1.0.90
In parallel, I'm also building the current master branch for comparison: https://travis-ci.org/GodotBuilder/godot-builds/builds/167937619 https://ci.appveyor.com/project/GodotBuilder/godot-builds/build/1.0.89

**Comment by akien-mga** [comment]
It built properly on all platforms (apart from javascript which is timing out, but same for current master, and OSX which has timed out while master managed to build in timeout - 2 min :D).

I'd propose to merge now that we know that it doesn't introduce big buildsystem regressions, and then fix issues as they come (as there should probably be a couple ones along the way).

**Comment by akien-mga** [comment]
(Actually I finally got the javascript build to fail, but it looks like emscripten is going crazy: https://travis-ci.org/GodotBuilder/godot-builds/jobs/167937903)

**Comment by zaps166** [comment]
@akien-mga 

- `armv7_opt_gcc` is not used, other `*_opt_gcc` are only for libtheora, so maybe rename it `*_theora_opt_gcc` (and the same for `*_opt_vc`)?

- isn't better to add `SCsub` files for every thirdparty library (or only for shared thirdparty libs like `libogg` and `libvorbis`) for static build (if not `system` is specified)? E.g. both `theroa` and `vorbis` modules use `libogg` and `libvorbis`. Currently compiling `theora` module without `vorbis` module (`module_vorbis_enabled=no`) is not possible.
Is `ogg` module necessary? `theora` and `vorbis` modules can notify SCons that they want to use `libogg` thirdparty or system library/ Currently `ogg` module exists only for building `libogg` builtin dependency.

**Comment by akien-mga** [comment]
@zaps166 Yes to both. For the former I have no clue about it, but please make a PR :). For the latter, I also thought about it and had no strong opinion for either way, but yes I think it would likely be best to put the `SCsub`s in thirdparty and have the modules that need them include them. Not sure yet how it would best be done, so I went for what I knew was working for a first step :)

**Comment by zaps166** [comment]
@akien-mga Ok, so maybe I'll try later :)

**Pull request merged**
