### PR TITLE
New default project icon

### PR DESCRIPTION
**Pull request by djrm**
Please comment and if most of the people like this new icon, we can merge.

godot_icon
icon_default_project_icon

screenshot from 2017-07-19 01-38-01

### CODE REVIEW

**Comment by Noshyaar** [comment]
Looks really nice!

The current one for reference
image

**Comment by TeddyDD** [comment]
Looks better than the current icon 🎨 I'm not sure about bevel, it looks old and does not fit the flat style of editor.

**Comment by eon-s** [comment]
I like the idea but is like too much white.

**Comment by fracteed** [comment]
Sorry, I much prefer the original blue on black one.

**Comment by CowThing** [comment]
I would like it more if the icon filled the whole image, right up to the edges. I often use the default icon as a placeholder, so having it be exactly 64x64 pixels is helpful.

**Comment by Noshyaar** [comment]
IMHO, I think it's better to have 'Godot logo on blueprint' icon representing projects created with Godot instead of using original Godot Engine logo which should represent the editor. I have to admit it might take a while to get used to the new icon, but I don't think it would look out of place in the long run.

**Review by ghost — APPROVED** [review]

**Comment by hubbyist** [comment]
White logo make me feel like looking at a lifeless zombie (honestly). Blue logo is friendly and more elegant for me. White on blue as project logo is a good idea but it must give the feeling of a pen drawing and hand labour.

**Comment by MrMaidx** [comment]
I like it and I agree with Noshyaar. But the Godot head could be little bigger.

**Comment by groud** [comment]
I like this new icon, but as @hubbyist says, it feels a little bit like a zombie.
Maybe make the head a little bit less bright, and add the eye pupil with the background blue color.

I any case I'm ok with the idea. As @Noshyaar said, having a project icon different from the editor's one is good to me.

**Comment by Srogozins** [comment]
I prefer the old one. New one is too white.

**Comment by capnm** [comment]
Please keep the old one. IMO it is also much better from the graphic design point of view.

**Comment by groud** [comment]
Here is another sketch with a background for the head (which creates a sort of outline)
28383713-c50cb7d0-6c87-11e7-8fd3-e4f2831e8838
I think something like that would look good.

**Comment by akien-mga** [comment]
White logo with white eyes looks super creepy guys. Keep in mind this is the main placeholder people use in their tests, it should not look lifeless :)

**Comment by puppetmaster-** [comment]
Please do not forget, the logo will also be used in the wild for:
- showing a bug
- little tutorials
- feature presentation
- demo
- prototyping

**Comment by volzhs** [comment]
@puppetmaster- I think it about project icon, not about changing logo.

**Comment by puppetmaster-** [comment]
@volzhs I'm confused. I thought it would be the icon.png file inside a new created project.

**Comment by groud** [comment]
@puppetmaster- Yes it is. This is the same file, which is used as the default icon for each project.

**Comment by kubecz3k** [comment]
We were talking on irc, there is no consensus for now. There was a proposition that maybe we should have some kind of icon templates for new projects. Reduz seems to like new icon but he thinks idea from @groud seems to be a little less creepy.

**Comment by djrm** [comment]
@kubecz3k thats fine, i was just testing if people like it, i might try a few other variations, also that idea about different project types sound really good, there could be some preloaded templates, like platformer 2d and 3d, or first person shooter, like UE4.

**Comment by vnen** [comment]
> there could be some preloaded templates

The idea is to have all demos in the asset lib, along with community-contributed templates so the user can download via the project manager (which is already possible). So the "preloaded templates" will actually come from the asset lib.

**Comment by n-pigeon** [comment]
Ehhh icons with face never work... :<

**Comment by aggsol** [comment]
If you leave out the eyes complete it will look like a skull. As every game in the begining is a mere skeleton I find it fitting as default icon in the beginning :skull:

**Comment by tebz** [comment]
From a technical point of view.. I would like the Editor to have a Icon that identify that it's the editor and the version.

**Comment by akien-mga** [comment]
Superseded by #10433 I believe.

I like the new icon :)
spectacle lh3453

**Pull request closed without merging**
