### PR TITLE
Allow nodes to be made unselectable in the editor

### PR DESCRIPTION
**Pull request by shartte**
Added the ability to lock selection in the 3D viewport for nodes and their children, making them 'click-through'. 

The use case for this is mostly to exclude background art assets from the selection tool so that the region select / click select are more user friendly when doing level editing. Currently they would constantly select MeshInstance nodes from the background, rather than the nodes representing characters and such in the foreground. Having this feature allows me to simply exclude the entire node that contains all background art from being selected.

*Note*: This lacks a proper icon currently, as I just reused the lock transform icon. If this feature is even something that would potentially be merged, I'll have to figure out a good icon for it :)

### CODE REVIEW

**Comment by reduz** [comment]
Does this work the same as in 2D? The idea was to make it the same as 2D

**Comment by reduz** [comment]
Closing, as superseded by @JFonS PR (I can't find it, help).

**Comment by starry-abyss** [comment]
https://github.com/godotengine/godot/pull/28130 ?

**Comment by shartte** [comment]
These PRs are not equivalent. But okay.

**Comment by starry-abyss** [comment]
@shartte So it's not possible to click-through with the button in the other PR? Never used it, but from the name it sounds like it will focus the parent instead of click-through?

**Comment by shartte** [comment]
> 
> 
> @shartte So it's not possible to click-through with the button in the other PR? Never used it, but from the name it sounds like it will focus the parent instead of click-through?

Jup, it replaces selecting a node with selecting the group instead

**Comment by starry-abyss** [comment]
Then this one is not really superceded, @reduz @akien-mga ?

**Comment by akien-mga** [comment]
So there has been some confusing here as the feature partly exists already for children of a locked nodes, which are not selectable.

What should be changed is to make things behave like in 2D, where locking also makes the locked node unselectable. The tooltips in 2D and 3D should be adjusted to mention that they lock the position and prevent selection in the viewport.

In a later PR, it could be interesting to implement a picking mode for 2D and 3D which bypasses the selection restriction, so e.g. Ctrl+Click would let you select locked nodes (to ease finding them in the scene tree/viewing their properties/unlocking them).

**Comment by akien-mga** [comment]
I opened an issue to outline what should be done as described above: #29903.

**Pull request closed without merging**
