### PR TITLE
Fix crash when using OpenXR extension wrappers from GDExtension

### LINKED ISSUE #88613: Crash on exit when using OpenXRExtensionWrapperExtension
### Tested versions

- Reproducible in 4.3-dev [fb10e67fefb85af3b8f5abd30db561588d8456c6]

### System information

Windows 11, gl_compatibility, NVidia RTX 3070 TI

### Issue description

When terminating a Godot application which uses any OpenXRExtensionWrapperExtension objects, the application terminates in a call of `memdelete(extension_wrapper)` with a pointer that isn't a valid block of heap memory.

The problem is caused by the inheritance structure of OpenXRExtensionWrapperExtension:
https://github.com/godotengine/godot/blob/652438a3952ae13e12dd4fd40756311fde81a791/modules/openxr/extensions/openxr_extension_wrapper_extension.h#L42

The problem occurs when `OpenXRExtensionWrapperExtension::register_extension_wrapper()` registers this class with `OpenXRAPI::register_extension_wrapper()` **AS AN OpenXRExtensionWrapper**:
https://github.com/godotengine/godot/blob/652438a3952ae13e12dd4fd40756311fde81a791/modules/openxr/extensions/openxr_extension_wrapper_extension.cpp#L233-L235

The OpenXRAPI extension wrappers saves OpenXRExtensionWrapper instances in a `Vector<OpenXRExtensionWrapper *>` and later deletes them using `memdelete`.

The problem is that the memory layout of OpenXRExtensionWrapperExtension is as follows (sizes specific to Windows/X64):
- Object base: 408 bytes
- OpenXRExtensionWrapper base: 8 bytes
- OpenXRCompositionLayerProvider base: 8 bytes
- OpenXRExtensionWrapperExtension members: 688 bytes
- Total size = 1112 bytes

When the `OpenXRExtensionWrapperExtension::register_extension_wrapper()` registers itself, it has to cast its `this` pointer to an `OpenXRExtensionWrapper*` which involves adding 408 to the pointer value to jump over the `Object`. When `memdelete()` is called on this pointer, it fails because the pointer isn't a block of allocated memory.

This pattern is fully supported in C++ using the normal new/delete, as the compiler will generate a "virtual deleting destructor" in the objects VTABLE, so a delete by any class type will correctly call the real destructor, then adjust the pointer to the start of the object and delete the memory.

Godot's use of memdelete() appears to bypass this machinery preventing safe deletion of multiple-inheritance classes.

### Steps to reproduce

Run Godot with the [godot_openxr_vendors](https://github.com/GodotVR/godot_openxr_vendors) extension (or any extension providing OpenXR extensions) and then terminate the application.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by dsnopek**
Fixes https://github.com/godotengine/godot/issues/88613

This is an alternative to PR https://github.com/godotengine/godot/pull/88688 which tries to fix the pattern generally, whereas this PR is just a targeted fix for issue https://github.com/godotengine/godot/issues/88613

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]
Thanks for the fix!

Looks like it should also fix https://github.com/GodotVR/godot_openxr_vendors/issues/67?

**Review by akien-mga — APPROVED** [review]
As written in https://github.com/godotengine/godot/pull/88688, I suggest we merge this safe ad hoc fix for now to fix the bug, and keep discussing in the core PR to see if we want to go with that approach in the long run.

**Comment by akien-mga** [comment]
Thanks!

**Comment by dsnopek** [comment]
> Looks like it should also fix [GodotVR/godot_openxr_vendors#67](https://github.com/GodotVR/godot_openxr_vendors/issues/67)?

Yes, it fixed this issue in my testing!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
