### PR TITLE
Betsy: Add BC3 and BC5 support

### PR DESCRIPTION
**Pull request by BlueCube3310**
Adds support for compressing textures as BC3 and BC5 with the Betsy compressor.

### CODE REVIEW

**Comment by jcostello** [comment]
Sorry to ask, but this one wasn't already done?

**Comment by Calinou** [comment]
> Sorry to ask, but this one wasn't already done?

Other compression modes were implemented, but not BC3 and BC5 yet:

- https://github.com/godotengine/godot/pull/95915
- https://github.com/godotengine/godot/pull/96377
- https://github.com/godotengine/godot/pull/97295

**Comment by clayjohn** [comment]
> Sorry to ask, but this one wasn't already done?

To add to Calinou's comment. The current supported version only support:
1. Single channel LDR textures
2. RGB LDR textures
3. HDR textures

RGBA LDR textures (most textures) aren't supported yet, but support is added in this PR

**Comment by fire** [comment]
Horray! This will be quite well once complete for the import process.

**Comment by clayjohn** [comment]
@BlueCube3310 You mentioned that you wanted to clean this up a bit, but weren't sure how. Here is a patch that cleans up how the shaders are initialized and managed to make things a bit simpler. Please let me know what you think


[betsy-patch.patch](https://github.com/user-attachments/files/17927669/betsy-patch.patch)

**Review by clayjohn — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
