### PR TITLE
fix gd_parser(check from constants) bugs

### PR DESCRIPTION
**Pull request by sanikoyes**
this problem can reproduce when autoload an gdscript
reproduce project at:
https://github.com/sanikoyes/godot_bugs/tree/master/gdscript-constant-node

### CODE REVIEW

**Comment by vnen** [comment]
Uh, I believe this is about the problem in #5264 which was recently fixed by cf0fbe493ff8e2dd80859d75a9794d364a03551c.

**Comment by sanikoyes** [comment]
@vnen , no, this problem is still exists, i was upload reproduce project at:
https://github.com/sanikoyes/godot_bugs/tree/master/gdscript-constant-node

**Comment by ScotFlux** [comment]
I guess cf0fbe4 generate a new bug. I compiled from this commit (very recent commit, the last one as of this writing) and load a project, but failed at a point where console saying about constant and gdparser.

So, I endup re-compiling Godot using one commit behind that commit. And now, works as usual.

**Comment by akien-mga** [comment]
I can confirm the regression with cf0fbe4, which I guess this PR tries to fix. @reduz Can you have a look?

**Comment by vnen** [comment]
Ah, if there's a regression it should've been stated from the start. When I saw this first there was single commit with no description at all in the OP.

**Comment by reduz** [comment]
ah shit I forgot autoload, I think this needs to be fixed properly though,
give me a bit

**Comment by reduz** [comment]
These kind of constant lookups should only happen when using const assignments, so changed the code  for this situation

**Pull request closed without merging**
