### PR TITLE
Implement 3D textures as import and resource format.

### PR DESCRIPTION
**Pull request by reduz**
To import a 3D texture, select import type Texture3D and the slicing:
image
New resource types have been added, Texture3D( base), ImageTexture3D, and StreamTexture3D.
image
And a previewer:
image

### CODE REVIEW

**Comment by menip** [comment]
Could someone tell me what this is used for? I'm not getting it yet

**Comment by clayjohn** [comment]
@menip 3D textures have many uses, I personally use them to store noise data for volumetric clouds.

**Comment by Calinou** [comment]
3D textures are also often used as LUTs (look-up textures) for color correction.

**Comment by vitorbalbio** [comment]
This is great. Can it be backported to Godot 3 ?

**Comment by Calinou** [comment]
@vitorbalbio Godot 3.x already supports 3D textures, but the import options are different.

**Pull request merged**
