### PR TITLE
Add a wireframe mode to `BaseMaterial3D`

### PR DESCRIPTION
**Pull request by Chaosus**
Adds a boolean flag, so user may enable it on Base/StandardMaterial3D now.
sphere

### CODE REVIEW

**Comment by AThousandShips** [comment]
The new flag constant wasn't registered

**Comment by Chaosus** [comment]
> The new flag constant wasn't registered, all previous ones have

Fixed

**Comment by akien-mga** [comment]
This looks interesting, but can you clarify the use case? Are there related proposals showing why users need this as a material property?

**Comment by Chaosus** [comment]
I think it may be useful for debugging + it's supported in common shaders, so this just a step for completion between the material and shader material functionality.

**Comment by clayjohn** [comment]
I don't think the wireframe mode is implemented in the GL_Compatibility renderer. We should probably hold off on merging this until it works with all backends.

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/pull/74387.

**Comment by Chaosus** [comment]
> I don't think the wireframe mode is implemented in the GL_Compatibility renderer. We should probably hold off on merging this until it works with all backends.

https://github.com/godotengine/godot/pull/85621 got merged, so this PR may be accepted too now?

**Comment by clayjohn** [comment]
> > I don't think the wireframe mode is implemented in the GL_Compatibility renderer. We should probably hold off on merging this until it works with all backends.
> 
> #85621 got merged, so this PR may be accepted too now?

Something we didn't think about before is that the Compatibility backend requires us to generate a different index array for wireframes. Therefore, its only enabled when requested by [`set_debug_generate_wireframes`](https://docs.godotengine.org/en/stable/classes/class_renderingserver.html#class-renderingserver-method-set-debug-generate-wireframes). So this toggle would appear to work in editor (because `set_debug_generate_wireframes` is called by EditorNode) and not at export time. 

So I guess for this to work on the compatibility renderer we would need some additional flag to force generating the wireframe arrays when the mesh is used with a material that has wireframes force enabled.

**Comment by Chaosus** [comment]
> So I guess for this to work on the compatibility renderer we would need some additional flag to force generating the wireframe arrays when the mesh is used with a material that has wireframes force enabled.

Okay, then I close it since it seems to be a far perspective..

**Pull request closed without merging**
