### PR TITLE
Update xatlas to latest upstream commit (b7d7bb9).

### PR DESCRIPTION
**Pull request by fire**
Update xatlas to 1681e63

### CODE REVIEW

**Comment by fire** [comment]
Needs testing, not sure if we require the per triangle code.

**Comment by fire** [comment]
Reminder to remove patch files when close to done.

**Comment by fire** [comment]
This is confusing.

```thirdparty\xatlas\xatlas.cpp(2379): error C2327: 'xatlas::internal::task::ObjectPool<xatlas::internal::task::Scheduler::Counter>::D::state': is not a type name, static, or enumerator
thirdparty\xatlas\xatlas.cpp(2338): note: see reference to class template instantiation 'xatlas::internal::task::ObjectPool<xatlas::internal::task::Scheduler::Counter>::D' being compiled
thirdparty\xatlas\xatlas.cpp(2331): note: while compiling class template member function 'bool xatlas::internal::task::ObjectPool<xatlas::internal::task::Scheduler::Counter>::ref(uint32_t) const'
thirdparty\xatlas\xatlas.cpp(2470): note: see reference to function template instantiation 'bool xatlas::internal::task::ObjectPool<xatlas::internal::task::Scheduler::Counter>::ref(uint32_t) const' being compiled
thirdparty\xatlas\xatlas.cpp(2673): note: see reference to class template instantiation 'xatlas::internal::task::ObjectPool<xatlas::internal::task::Scheduler::Counter>' being compiled
thirdparty\xatlas\xatlas.cpp(2379): error C2065: 'state': undeclared identifier
thirdparty\xatlas\xatlas.cpp(2379): error C2327: 'xatlas::internal::task::ObjectPool<xatlas::internal::task::Scheduler::Counter>::D::version': is not a type name, static, or enumerator
thirdparty\xatlas\xatlas.cpp(2379): error C2065: 'version': undeclared identifier
thirdparty\xatlas\xatlas.cpp(2379): error C2327: 'xatlas::internal::task::ObjectPool<xatlas::internal::task::Scheduler::Counter>::D::element': is not a type name, static, or enumerator
thirdparty\xatlas\xatlas.cpp(2379): error C2065: 'element': undeclared identifier
scons: *** [thirdparty\xatlas\xatlas.windows.opt.tools.64.obj] Error 2
scons: building terminated because of errors.
```

**Comment by fire** [comment]
What that means is that msvc 2017 is required and msvc 2015 isn't supported?

**Comment by akien-mga** [comment]
I'd prefer that we keep supporting MSVC 2015 for the time being, even though using 2017 or later is definitely recommended.

**Comment by jpcy** [comment]
`xatlas::MeshDecl` data fields don't need to be allocated, you could assign them to `p_indices`, `p_vertices` etc. directly instead.

**Comment by fire** [comment]
@jpcy Can you see why the system is limited to one core?

**Comment by jpcy** [comment]
Multithreaded tasks aren't very finely grained at this point. A single mesh where all faces are connected will only use one core. I should be able to improve that soon, but I need to swap out the current task scheduler with one that can create sub tasks from any thread first.

**Comment by fire** [comment]
Will test https://github.com/jpcy/xatlas/commit/b7d7bb95773f3d92dabb1b63e38385d9cfaaffaf for performance changes.

**Review by JFonS — APPROVED** [review]
LGTM

**Comment by fire** [comment]
Regarding performance improvements, there are still changes in https://github.com/jpcy/xatlas/issues/22 and the repository.

However, at this very moment, there is no difference in performance between the master and this pull request. Both are still single core locked. So we should be ok to merge and when xatlas has the performance improvement, we can pull request again.

**Comment by akien-mga** [comment]
Sounds good to me, let's merge :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
