### PR TITLE
[Windows, 3.x] Open a new console window for the editor instances.

### LINKED ISSUE #54076: Godot will not startup from project manager if the default terminal application is set to Windows Terminal in Windows 11
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0.dev(fad7034e8b)

### System information

Windows 11

### Issue description

Godot will not startup from project manager if set the default terminal software to Windows Terminal in Windows 11, it will close immediately

### Steps to reproduce

1. Change the default terminal application from cmd to Windows Terminal in Windows Terminal Settings.
2. Try to open a project in Godot's project manager
3. Godot window close immediately like a crash

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #54076 for 3.x, same as #55924

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Comment by Structed** [comment]
Is there a way I can avoid opening a new CMD?

I am using Windows Terminal on Windows 10 and would love to keep output in the current terminal window.

**Comment by Calinou** [comment]
> Is there a way I can avoid opening a new CMD?
> 
> I am using Windows Terminal on Windows 10 and would love to keep output in the current terminal window.

This should be fixed in 3.5beta2 thanks to https://github.com/godotengine/godot/pull/55987.

**Pull request merged**
