### PR TITLE
clarify OS.execute usage

### PR DESCRIPTION
**Pull request by brainsick**
in response to #15912 and #5708

### CODE REVIEW

**Comment by brainsick** [comment]
Actually, would two examples be okay?

```
[codeblock]
var output = []
var pid = OS.execute('ls', [], true, output)
[/codeblock]
[codeblock]
var output = []
var pid = OS.execute('CMD.exe', ['/C', 'cd %TEMP% && cd'], true, output)
[/codeblock]
```

**Comment by brainsick** [comment]
I guessed on encoding the & in the [codeblock].  It's an XML shell so XML rules apply, right?

**Comment by mhilbrunner** [comment]
Looks good to me. I'd maybe use the example from the last comment in https://github.com/godotengine/godot/issues/5708 as an additional example? Shows how you can invoke built-ins and how to set a path. And you then have a Windows example too. :)

**Comment by brainsick** [comment]
My initial submission only included the ls example. At the time of your review though, there should have been two examples, including the one you mentioned. I omitted the echo and resulting print though as that felt redundant. Are you asking me to add that specifically?

**Review by mhilbrunner — APPROVED** [review]

**Comment by mojoyup** [comment]
Im trying to extract a jar file (or at least some of it using java arguments), and So I tried this code:

`cd C:/Users/mojoyup1528/Desktop && jar  xf C:\Users\mojoyup1528\AppData\Roaming\.minecraft\versions\1.12.2\1.12.2.jar`

in Godot 3.4.4 and it freezes up. If I try to utilize the "/C" to use the internal command line tool, it doesnt have the administrative rights to create the folders. Not sure what to do with this yet. 

If I do this with cmd outside of Godot, it works.

**Comment by Calinou** [comment]
>  If I try to utilize the "/C" to use the internal command line tool, it doesnt have the administrative rights to create the folders. Not sure what to do with this yet.

The folder paths you mentioned can be written to by the current user; it shouldn't require administrator elevation, unless you are modifying *another user*'s files.

**Comment by mojoyup** [comment]
That's exactly what I was thinking also. I can access them otherwise just fine. SO yeah it's confusing :/. But I would think then that because AppData is normally a hidden folder, that would have been a reason, but we have the option in FileDialog to show/hide that. I have my cmd program also set to run as admin normally anyhow but I think that what's happening is, the OS.execute is not properly executing the command. 

I know it has something to do with Godot but not sure whether its an API thing or just that I may just not be able to extract a jar with Godot. Either way, just wanted to know if anyone had any ideas otherwise, so thank you for the response. :)

**Pull request merged**
