### PR TITLE
Document alternatives to some static Color methods

### PR DESCRIPTION
**Pull request by KoBeWi**
See https://github.com/godotengine/godot-proposals/issues/10294

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]

**Comment by AThousandShips** [comment]
We should probably see about how to document this constructor properly, as it's overlooked due to some conversion details, but this is good as an initial step IMO

**Comment by KoBeWi** [comment]
Another thing is that there is no way to link to a constructor, like to methods and members.

**Comment by Mickeon** [comment]
There is, but it's not coded properly because it's not standard (it needs more parameters than just the constructor's name)

Both `[constructor Color]` and `[operator Color] work partially. They only point to the first one in the list if I recall correctly, and fail the check on Github.

**Comment by KoBeWi** [comment]
Yeah I noticed the constructors have `name` field, but each one is named the same. Hence it's effectively not possible to utilize it in a useful way.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
