### PR TITLE
Fix newly baked lightmap can't override previously baked at same path

### LINKED ISSUE #94214: Lightmap bake fails when trying to bake for the second time to the same path
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

Godot v4.3.beta3 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

image<br>

Baking for the first time succeeds, but when trying to bake for the second time to the same file it fails with
```
Another resource is loaded from path 'res://node_3d.lmbake' (possible cyclic resource inclusion).
```

Restarting the editor solves the problem

### Steps to reproduce

1. Open the MRP
2. Delete LightmapGI node
3. Add a new LightmapGI node
4. Click bake, choose the same `lmbake` path and agree to overwrite

Note: sometimes it also fails without deleting the node and just clicking bake on the same node twice is enough, but steps above reproduce it more reliably

### Minimal reproduction project (MRP)

[MRP_another_resource_loaded.zip](https://github.com/user-attachments/files/16177561/MRP_another_resource_loaded.zip)

### PR DESCRIPTION
**Pull request by jsjtxietian**
Fixes https://github.com/godotengine/godot/issues/94214

### CODE REVIEW

**Comment by jcostello** [comment]
Finally, I thought it was a problem in my PC

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by jcostello** [comment]
I still get this error

image

**Comment by jsjtxietian** [comment]
I tested on master it no longer existed, maybe it's because OS? I'm using win

**Comment by jcostello** [comment]
I still have this issue in Linux. I test it on several projects and happens only on big scenes

**Comment by jcostello** [comment]
@jsjtxietian Debugin the issue I found it has to be with the final texture being greater than the allowed max size. Still the error displayed is the same. We should allow to show more error types @akien-mga

**Comment by akien-mga** [comment]
Could you open a new issue for this case?

**Pull request merged**
