### PR TITLE
Clarify that some `ParticleProcessMaterial` properties have effect over the lifetime

### LINKED ISSUE #83603: Change the tooltip for scale_curve in ParticleProcessMaterial to better indicate that it scales over lifetime
### Godot version

v4.2.beta1.mono.official [b1371806a]

### System information

Godot v4.2.beta1.mono - Fedora Linux 39 (Workstation Edition) - Wayland - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i3-1215U (8 Threads)

### Issue description

When hovering over the `scale_curve` field in ParticleProcessMaterial, the tooltip that shows up implies that it's some sort of remap curve to randomize the particles' scale at spawn. However, the property actually affects the particles' scale over their lifetime.

image

A better tooltip would be "Each particle's scale will vary along this `CurveTexture` *over its lifetime*..." similar to `*_velocity_curve` properties.

image

### Steps to reproduce

1. Open the project
2. Select the GPUParticles3D
3. Go to Process Material and open the process material
4. Go to Display - Scale and hover over the Scale Curve property
5. Compare the tooltip to Animated Velocity - Angular Velocity - Velocity Curve

### Minimal reproduction project

[ParticleScaleCurveTooltipReproductionProject.zip](https://github.com/godotengine/godot/files/13038928/ParticleScaleCurveTooltipReproductionProject.zip)

### PR DESCRIPTION
**Pull request by k0T0z**
Fixes #83603

### CODE REVIEW

**Comment by akien-mga** [comment]
Why remove the additional documentation about how it works with a CurveXYZTexture?

**Comment by k0T0z** [comment]
@akien-mga Hmmm, I forgot I am working on the scale, right, I will fix it

**Comment by ArtyIF** [comment]
I think it needs to apply to other properties like damping as well, but it needs to be double-checked first

**Comment by Mickeon** [comment]
This PR should probably be updated to include more properties other than `scale_curve`. If it can't, I mean... It is good by itself but it could be more meaningful.

**Comment by k0T0z** [comment]
Hmmmm, sure I mean why not, is there any other properties needed, I see we need the damping as well, is there anything else I am not aware of?

**Comment by Mickeon** [comment]
I looked at the whole list and it seems like the following properties seem to forget to mention the "over its lifetime" part.

- `anim_offset_curve`
- `anim_speed_curve`
- `damping_curve`
- `hue_variation_curve`
- `linear_accel_curve`
- `orbit_velocity_curve`
- `radial_accel_curve`
- `tangential_accel_curve`

`color_initial_ramp` may seem to be part of them at first, but it is _initial_, so I am not sure if it counts here.

**Review by Mickeon — APPROVED** [review]
The PR itself is completely fine. As I said before, I just wish it tackled more properties (which can be done later).

I had no "qualification" to approve it previously, but I can now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
