### PR TITLE
Expose methods for adding and removing ResourceFormatLoaders and -Savers

### PR DESCRIPTION
**Pull request by leogeier**
Implements godotengine/godot-proposals#4548 according to the first solution.

### CODE REVIEW

**Comment by fire** [comment]
Are you familiar with the pr and how the cicd system does testing on the code.

https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html

**Comment by leogeier** [comment]
I believe I am, did I miss something?

**Comment by fire** [comment]
I'll add a tag to bring this to the next pr meeting.

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting. Would need a rebase, which should incidentally fix the godot-cpp build error on CI which was just bad timing.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by and3rson** [comment]
Can we backport this into 3.5? This would be such a great piece of functionality. I could do a PR for this.

**Comment by YuriSizov** [comment]
@and3rson `3.5` is released already, so this can only be considered for `3.6 LTS`. If there are no dependencies on other `master` changes here and you are willing to backport this PR, you can go ahead and make a `3.x` PR.

**Pull request merged**
