### PR TITLE
Enabled transform animations of skeleton bones by index NodePaths 

### PR DESCRIPTION
**Pull request by rminderhoud**
Transform animation tracks paths can now use the bones property of Skeleton in addition to using the bone name.

E.g. `Skeleton:bones/0`

### CODE REVIEW

**Comment by hpvb** [comment]
Looks reasonable, would this need some changes to the animation editor to make this easier to discover?

**Comment by rminderhoud** [comment]
I don't believe so, the animation player already recognizes `skeleton:bones/<index>` as a valid property to be used in a transform track, it just wouldn't do anything.

**Comment by reduz** [comment]
What is the reasoning for this? I mean just by the PR alone it's difficult
to understand the motivation for this change..

**Comment by rminderhoud** [comment]
I ran into the limitations of name-only animation when I was writing an importer for a file format that stored the skeleton in a separate file from the animations and bones were referenced by index rather than by name. This change allowed me to import the animation as a resource without requiring a reference to the skeleton at import time or having to rename tracks. I confess this a weird edge case as I can't even come up with a good reason why anyone would not use named bones but alas, these fools did. 

I noticed initially that when creating a key by selecting the icon next to the pose of the bone it generated a nodepath such as `skeleton:bones/0/pose` for the track. It's not possible to animate a bone this way but it's how I got the idea for this pull request.

**Comment by rminderhoud** [comment]
After thinking about it more I think this pull request should be rejected. An animation resource format that does not use named bones appears to be very atypical. If a developer is working with a weird format then I think it's safe to assume that the developer can also do some pre-processing to the file to make it simpler to import. Creating two paths to do the same thing (skeleton:<bone_name> & skeleton:bones/<idx>) to support a rare edge-case doesn't seem like a good idea.

**Pull request closed without merging**
