### PR TITLE
[WIP] Allow for constants other than integers

### PR DESCRIPTION
**Pull request by groud**
I wanted to have constants that were not Integers, so I replaced the integer hashmap in ClassDB by a Variant hashmap.
Can someone tell me if this is a good idea ? Or how it should be done instead ?

It still haven't checked what those modifications imply into the code, **don't merge yet** as I have to check if some occurences are not systematically casted to an int.

### CODE REVIEW

**Comment by reduz** [comment]
I´m sorry, I think this does not really make any sense. ClassDB is meant to
be a binding to C++, and the C++ API does not need or use this. Adding this
functionality is definitely undesired.

**Comment by groud** [comment]
@reduz Well what is precisely undesired ? I mean, being able to define Float or String constants seems a good idea to me isn't it ?

**Comment by reduz** [comment]
It's not about being a good idea, it's about it being needed or uneeded. In this case, there is no argument that justifies a need for it. Everything added to Godot, specially to the core/ needs to have a very good reason to exist, including actual use cases that happen often.

**Comment by groud** [comment]
Well, I was thinking making available to gdscript the values of ANCHOR_BEGIN, ANCHOR_CENTER and ANCHOR_END (in my other PR). And also maybe Math::PI.

**Comment by reduz** [comment]
just use a separate function like set_anchor_preset() or something like
that.

**Comment by groud** [comment]
Ok, I'll do that.
I still find this weird to have Integer constants in the class database, and not Float or String, but I can get over it. ^^

**Comment by reduz** [comment]
alternatively, just use begin and end if you want, and ignore center. We
are breaking compat with 2.x anyway

**Pull request closed without merging**
