### PR TITLE
Add categories to GDScript exported variables

### LINKED ISSUE #4378: Add a way to add categories to the script variables section from GDScript
(Inspired by [a question on QA](http://godotengine.org/qa/3196/how-add-subcategories-inspector-script-variables-section))

When doing scripts with a lot of configurable variables, it is nice to be able to group them in the inspector. 

So, instead of having:

```
> Script Variables
| - Not totally unrelated var = false
| - Unrotate children = true
| - Rotate speed = 60
| - Rotate timeout = 100
| - ...
```

We can have

```
> Script Variables
| - Not totally unrelated var = false
| > Rotate
| | - Unrotate children = true
| | - Rotate speed = 60
| | - Rotate timeout = 100
| - ...
```

---

With @kubecz3k we discussed on IRC about how might we do the syntax, and we ended up with the following:
- (1) A new keyword that starts a category
  - Pros: Allows for this issue to be closed
  - Cons: Impossible to end a category, no nesting

``` gd
category rotate
export var unrotate_children = false
```
- (2) An addition to export hints
  - Pros: Not much additional code to be written
  - Cons: You have to retype the name of the category for each variable

``` gd
export("rotate") var unrotate_children = false
export("rotate", float) var rotate_speed = 60
```
- (3) Allow variables with non-identifier names
  - Pros: Stuff like CJK support comes naturally
  - Cons: You have to retype the name of the category for each variable, doesn't look good at all

``` gd
export var "rotate/unrotate_children" = false
```
- (4) Add a keyword that starts a "category block"
  - Pros: Which variable is where is evident from afar, nesting of categories is supported
  - Cons: Raises suspicion on how to get that variable... should it be via `category_name.variable_name`, or just `variable_name`

``` gd
category rotate:
    export var unrotate_children = false
```

@reduz ~ Which one of the four proposals above do you like the most?

### PR DESCRIPTION
**Pull request by bojidar-bg**
Closes #4378 via the 4th proposal, as it is easiest to implement
Supports:
```gdscript
category xyz:
    export var x = 2
category "xyz/test":
    export var y = 5
category(test):
    export var z = 6
category("test/xyz"):
    export var w = 8
export var a = 7 # Would appear before the categorised variables because of limitations
func _ready():
    print(x + y + z + w)
```
Does not yet support:
```gdscript
category a:
    category b:
        export var c = 2
# can be faked using `category "a/b":`
```

But, most of all, needs some extra testing, as I might have broken things.

### CODE REVIEW

**Comment by Geequlim** [comment]
New keyword

**Comment by neikeq** [comment]
I seriously consider GDScript would benefit from attributes to avoid so many new keywords.

**Comment by juan-garcia-m** [comment]
@neikeq exactly, that could had been a good use for annotations.

@bojidar-bj this is cool, thanks!

**Comment by kubecz3k** [comment]
Well we don't have attributes in gdscript, but this pr (ability to create exported var categories) is still cool. 
@reduz could you give us a hint on how you see this?

**Comment by akien-mga** [comment]
Needs rebase after #12969, sorry :D

**Comment by Geequlim** [comment]
Please stop adding new keywords to GDScript!

**Comment by bojidar-bg** [comment]
I think I will not be rebasing this, since the community doesn't seem to like having more keywords in GDScript.

What might get implemented is the proposal in https://github.com/godotengine/godot/issues/10799#issuecomment-344567315, which is to have the script's name instead of "Script Variables", thus splitting variables from extended scripts.

You might react with :+1: if this proposal sounds better to you, with :-1: if you think it won't be any better than current master, and with 😕 if you think this proposal is worse than the one currently implemented in this PR (you might want to also write a comment with why you think so).

**Comment by Zireael07** [comment]
Derived scripts being separate is fine and dandy but I often find myself with so many variables in a single script that I need categories within this single script. (Mostly a consequence of the fact that I use tool scripts A LOT)

**Comment by bojidar-bg** [comment]
@Zylann Somewhat related to #12837, one day we would be able to separate tool scripts away.

Note that this PR is not required for making categories via GDScript, since you can just use `_get_property_list` to populate them.

**Comment by reduz** [comment]
I agree, too many keywords, we should have annotation support at this point.

**Comment by reduz** [comment]
Afte thinking about it, i would do

export_category <string>

so only text like

export_category "hello" would be good, and that's it.

**Comment by reduz** [comment]
also do not accept indentifiers in there, it's really confusing

**Comment by bojidar-bg** [comment]
I think I will close this PR for now, maybe to be reopened some time after 3.1 starts. Sorry to everyone who needs it now, but, seems like more GDScript enchancements would come later 😃

**Comment by neikeq** [comment]
@juan-garcia-m's PR was perfect for this IMO. The only thing I would add to it is to optionally use parenthesis for the parameters, this way the attribute can be in the same line as the declaration.

**Comment by juan-garcia-m** [comment]
@neikeq I did indeed added parenthesis at first, but I removed them as it seem more in the style of GDScript.
Sadly, I deleted the repo for the PR... Not sure I have the code somewhere in local, but it should be outdated by now.
I am now implementing Java support for Godot externally, and all the ideas I had for the annotations I will do them in Java instead.
But if the community is still interested on having GDScript annotations I could help though.

**Comment by kubecz3k** [comment]
@juan-garcia-m you are implementing java externally? That is interesting. What VM will you use?

**Comment by neikeq** [comment]
@juan-garcia-m Your commits are still available in #9469 :)

**Comment by juan-garcia-m** [comment]
@neikeq Oh! I see :)

@kubecz3k IKVM.NET, abusing the fact that we have official Mono support. You will still need to have Mono installed (and a JDK of course), but even Godot itself will be downloaded by the Gradle plugin I am writing. Having addons as dependencies, automatic typed scenes and Eclipse support is on the way. Hopefully I will publish an Alpha in the coming weeks.

**Comment by Xrayez** [comment]
> @Zylann Somewhat related to #12837, one day we would be able to separate tool scripts away.
> 
> Note that this PR is not required for making categories via GDScript, since you can just use `_get_property_list` to populate them.

@bojidar-bg I confirm the ability to create both categories and groups with this method:

Annotation 2020-04-24 152130

Those prefixes are still visible though, not sure how to hide them to make less verbose in the inspector this way. Here's how I do it:

```gdscript
func _get_property_list():
	var props = []
	add_category("Arms", props)
	add_group("Left", props)
	add_property("left_layer_ofs_1", TYPE_REAL, 1 / 3.0, props)
	add_property("left_layer_ofs_2", TYPE_REAL, 2 / 3.0, props)
	add_group("Right", props)
	add_property("right_layer_ofs_1", TYPE_REAL, 1 / 3.0, props)
	add_property("right_layer_ofs_2", TYPE_REAL, 2 / 3.0, props)
	return props


func add_group(p_name, r_properties: Array):
	r_properties.push_back({
			name = p_name,
			type = TYPE_NIL,
			hint = PROPERTY_HINT_NONE,
			usage = PROPERTY_USAGE_GROUP | PROPERTY_USAGE_SCRIPT_VARIABLE,
		}
	)


func add_category(p_name, r_properties: Array):
	r_properties.push_back({
			name = p_name,
			type = TYPE_NIL,
			hint = PROPERTY_HINT_NONE,
			usage = PROPERTY_USAGE_CATEGORY | PROPERTY_USAGE_SCRIPT_VARIABLE,
		}
	)


func add_property(p_name, p_type, p_value, r_properties: Array):
	r_properties.push_back({
			name = p_name,
			type = p_type,
			value = p_value
		}
	)
```

**Comment by bojidar-bg** [comment]
@Xrayez In `ClassDB::add_property_group`, it is done by passing the prefix for the variables inside the group as the hint string of the group.
https://github.com/godotengine/godot/blob/26ecd924cc15c69362cc921235a0e81b5d0c88fd/core/class_db.cpp#L924-L931

So, something like this will work:
```gdscript
func _get_property_list():
	…
	add_group("Left", "left_", props)
	…
	add_group("Right", "right_", props)
…
func add_group(p_name, p_prefix, r_properties: Array):
	r_properties.push_back({
			…
			hint_string = p_prefix,
			…
		}
	)
…
```

**Comment by Zireael07** [comment]
This is lovely, can one of the snippets go somewhere in documentation? At last, my exported variables won't be a total mess in debugger <3 <3

**Comment by Xrayez** [comment]
Yep, works like a ch**arm**!

Annotation 2020-04-24 160742

@Zireael07 `_get_property_list` method certainly lacks documentation in the built-in docs. There are also related `_set` and `_get` virtual methods which need to be overridden in some cases combined with `_get_property_list`.

For instance, those `hint` and `hint_string` act depending on the context, including `usage` enum constants... Like float ranges for the slider which is wrapped in `export(float, 0, 100)` syntax on the script level. So those need to be documented per each `Variant` compatible type.

**Comment by Zylann** [comment]
It would be really nice if groups were not something embedded inside `_get_property_list` (and then affecting loading times and reflection calls when executed in exported games)

**Comment by 3top1a** [comment]
@Xrayez This works, but how do you access the variables?

**Comment by Shadowblitz16** [comment]
why hasn't this been merged in 4 years?
the only problem was what? too many keywords?
we still don't have this feature and annotations still haven't been released.

**Comment by SirPigeonz** [comment]
> 
> 
> why hasn't this been merged in 4 years?
> the only problem was what? too many keywords?
> we still don't have this feature and annotations still haven't been released.

Check mentions above it was implemented differently and is merged and used for GDScript 2.0

**Comment by Zylann** [comment]
I had a look at the PR linked from this issue to the GDScript 2.0 docs, and it seems it doesnt mention category annotations anywhere: https://github.com/godotengine/godot-docs/pull/4247/files
Was it added later or is it still not implemented?

**Comment by Xrayez** [comment]
See https://github.com/godotengine/godot-docs/pull/3623#issuecomment-675156770, perhaps there might be a thing like dynamic annotations? Who knows, there's no GDScript 2.0 specification out there publicly available... 😛

> @Xrayez This works, but how do you access the variables?

Late to respond but usually dynamically created variables can be accessed with `set()` and `get()` methods explicitly. But GDScript seems to handle even dynamically created properties via plain `.` operator (if those properties are not declared with `var`).

**Comment by nathanfranke** [comment]
Proposal: https://github.com/godotengine/godot-proposals/issues/1255
Superseding PR: https://github.com/godotengine/godot/pull/62707

**Pull request closed without merging**
