### PR TITLE
Editor: Fix AssetLib is not updating size and stuck

### PR DESCRIPTION
**Pull request by GrammAcc**
This is an enhancement to the fix originally provided in #80555.

When I submitted the original PR I did not account for resizing the editor window at runtime, so the number of columns for asset lib search results was recalculating on resize, but the asset title truncation threshold was not being recalculated, so columns were not spacing correctly after resizing the editor.

I added a simple for loop to the NOTIFICATION_RESIZE event of the EditorAssetLibrary class that loops through the currently displayed assets and recalculates their title truncation length. I just used a for loop over the `asset_items->get_child_count` and fetched each EditorAssetLibraryItem with `asset_items->get_child` since I wanted to avoid explicit memory allocation inside the notification handler.

Please let me know if this is not a good solution or if the use of `static_cast` is discouraged.

I tested this solution locally, and it fixes the problems I mentioned in https://github.com/godotengine/godot/issues/84471#issuecomment-1832182508.

I think this will fix the scaling problem as reported in https://github.com/godotengine/godot/issues/84471#issuecomment-1793725120 since it forces recalculation of the asset titles, but I am unable to confirm for sure since I can't test this on Windows.

This PR doesn't resolve the TODO:

https://github.com/godotengine/godot/blob/15a03ed98e63590c85dac62405d785e1b7ca7fed/editor/plugins/asset_library_editor_plugin.cpp#L67C1-L67C53

I haven't figured out exactly how to get the font size with TextServer yet, so I will submit a separate PR for that small refactor eventually. I wanted to submit this fix now though since this fixes an actual flaw in the original.

### CODE REVIEW

**Comment by GrammAcc** [comment]
Forgot to run clang-format. :man_facepalming: Just amended with formatting fixed.

**Comment by GrammAcc** [comment]
Okay, this should be ready for review now. The problem was that the `clamp_width` method was originally written with the assumption that it would be called on object initialization, so it was overriding the tooltip with the truncated version of the title text and wasn't handling the case of resizing to a larger size and un-truncating. I got this fixed and amended my commit.

I also updated the commit message with the details of the edits I made to the `clamp_width` method.

Please let me know if you have any questions about the implementation. Thanks!

**Comment by ckdarby** [comment]
@GrammAcc, It looks like it'll fix my issue on Linux using a tile manager. I'll keep you posted when it gets merged and 4.3 comes out. Thanks for putting in the work.

**Comment by GrammAcc** [comment]
I realized this morning that there is a better way to ensure that we don't overwrite the tooltip text with the truncated text. I currently have an if check for it in the `clamp_width` method, but I think it would be best to just set it in the `configure` method where the title text is set and then not worry about it, so I will update this PR over my lunch break today with a better design.

Also, I am working through the Accelerated C++ book in order to improve my contribution efficiency and quality, so hopefully my future PRs will be easier to review. :)

**Comment by GrammAcc** [comment]
I updated the PR with a better implementation. Details are in the commit message. I removed the full_title_text private member of the EditorAssetLibraryItem and used the tooltip text as the full text instead. By moving the `set_tooltip_text` call into the `configure` method, I don't have to worry about the tooltip accidentally getting updated during the `clamp_width` call, so this works fine as an invariant. Let me know if there are any problems with this approach. Thanks!

**Comment by GrammAcc** [comment]
CI is failing on the MacOS template_export job for some reason. I have no idea why, but I'm working on this.

**Comment by GrammAcc** [comment]
I'm closing this since #88761 was merged and seems to solve the same problem.

**Pull request closed without merging**
