### PR TITLE
Add object context menu on alt.

### PR DESCRIPTION
**Pull request by fire**
image

Pressing control-right will show the context menu. Only selected objects will be used by the menu. No object will be pick selected while pressing control-right.

Sponsored by IMVU.

### CODE REVIEW

**Comment by Calinou** [comment]
Isn't <kbd>Alt + Left mouse button</kbd> used for orbiting when using one of the alternative navigation modes?

**Comment by fire** [comment]
If you can suggest any other combination that is free, I'm happy to change.

**Comment by capnm** [comment]
> If you can suggest any other combination that is free, I'm happy to change.

Ctrl + RMB? If you're even cooler, make it configurable;)

**Comment by Calinou** [comment]
I'd suggest using <kbd>Alt + Left mouse button</kbd> when not using a navigation mode that conflicts with it. Otherwise, use <kbd>Alt + Right mouse button</kbd>.

**Comment by fire** [comment]
I changed it to control-right.

**Comment by capnm** [comment]
You should watch out for all possible bad side effects (press or hold the MB and/or modal keys).
Currently, the most reliable code for 3.2 that I've found experimentally on Linux is:
```c++
case BUTTON_RIGHT: {

				if (b->is_pressed()) {
					if (b->get_control()) {
						_edit.mode = TRANSFORM_CONTEXT;
					}
					if (_edit.mode == TRANSFORM_CONTEXT) {
						_edit.mode = TRANSFORM_NONE;
						editor->get_scene_tree_dock()->get_tree_editor()->emit_signal("rmb_pressed",
								get_global_transform_with_canvas().xform(b->get_position()));
						break;
					}
				}
...
```

**Comment by fire** [comment]
Thanks for the adjustment. It was difficult trying all the possible cases.

**Comment by fire** [comment]
Do you know if minimized windows positioning the menu incorrectly is a this patch's reponsibility?

**Comment by capnm** [comment]
> Do you know if minimized windows positioning the menu incorrectly is this patch's responsibility?

That isn't an issue in 3.2. 4.0 is currently unusable and beyond the scope of my work, sorry...

**Comment by groud** [comment]
To be honest I don't really like this idea. A lot of option there have nothing to do with positioning in the 3D editor, but more about node management in general, which is what the scene tree dock is for. Also, the 2D editor does not have this as it uses the shortcut for something else (if I am not mistaking). And as a future goal is to make the UX consistent between the two editors, I would avoid adding new features that are not supported on both editors.

**Comment by fire** [comment]
So are you saying:

1. we should define our own object context menu?
2. make a separate context menu that has similar things for 2d 
3. Choose a different menu shortcut

These reasons are not exactly rejecting the context menu. Just this implementation.

**Comment by capnm** [comment]
Hi @groud, I am happy that you are working on the user interface :-)
I implemented this menu in 3.2 and am (currently) satisfied with the 'functionality'. I would rather make the 2d editor consistent with that.
Honestly;) you should take a closer look at the Blender 2.9x UI. I miss the flexibility and the ergonomically "right" decisions in the Godot's UI. The new window features in 4.0 were abused immediately, the UI is a step backwards for me. I know they did it by default in Blender 2.8+ too, but you can easily turn it off in the configuration...
The 3D editor has many fundamental issues. After selecting object(s) with a pen, you always also move them and have to immediately hit "Undo". Try the same in Blender, where it works fine. Or it's almost impossible to visually change objects, when the center is far away or ... Sorry for the side-note, I rather stop now to spam this PR.

**Comment by groud** [comment]
> So are you saying:
    we should define our own object context menu for each node type?
    make a separate context menu that has similar things for 2d
    Choose a different menu shortcut
These reasons are not exactly rejecting the context menu. Just this implementation.

Point by point: 
1) Not really, I'd say that the menu should have options that makes sense in a 3D view. The 3D view is to manage your nodes positioning in the 3D view, so options like "duplicate", "delete" make sense in the list (eventually it could have more options like "snap to grid", "snap to floor" etc... which would be options related to positioning nodes). Here, options like "merge from scene" or "make scene root" are purely scene management actions, so they should not appear here as they are unrelated to organizing nodes in the 3D space.

2) Yes, the context menu should be different from 3D, as the actions would not be exactly the same as in a 3D world.

3) not necessarily, if the action is the same, the shortcut can be kept the same.

> These reasons are not exactly rejecting the context menu. Just this implementation.

I'd say yes. But this needs a proposal to see what shortcut we drop in the 2D editor to make things consistent. Because shortcuts are quite crowded in this area.

> Honestly;) you should take a closer look at the Blender 2.9x UI. I miss the flexibility and the ergonomically "right" decisions in the Godot's UI. The new window features in 4.0 were abused immediately, the UI is a step backwards for me. I know they did it by default in Blender 2.8+ too, but you can easily turn it off in the configuration...

I am not sure what you mean here, the multiple windows system is not here by default in 4.0.

> The 3D editor has many fundamental issues. After selecting object(s) with a pen, you always also move them and have to immediately hit "Undo". Try the same in Blender, where it works fine. Or it's almost impossible to visually change objects, when the center is far away or ... Sorry for the side-note, I rather stop now to spam this PR.

Yes, indeed the 3D editor needs a similar rework as I did in 3.x for the 2D one. But that will have to wait a little bit I guess.

**Comment by capnm** [comment]
> I am not sure what you mean here, the multiple windows system is not here by default in 4.0.

last time (a month ago?) I tried 4.0, the open scene, project-settings, etc. entries opened a new OS window.

**Comment by Calinou** [comment]
> last time (a month ago?) I tried 4.0, the open scene, project-settings, etc. entries opened a new OS window.

This is done by design, so you can move the window outside the main editor area.

**Comment by capnm** [comment]
> enable single-window mode in the Editor Settings 

Thanks, this is good news for me :)

> We've had several complaints in the past about not using OS windows for Godot-spawned windows. Therefore, single-window mode will remain disabled by default.

The same (endless) discussion spawned in the Blender 2.7->2.8 development. At the end they made it configurable :-)

**Comment by capnm** [comment]
> I don't think there's much point in having a dedicated editor setting for this ...

Personally, for example I don't think it's important to be able to configure hundreds of colors. Two sensitively composed sets for light and dark were completely sufficient. However, it is very important to be able to configure the keyboard shortcuts and the pointing-device buttons. If you need to work quickly with different apps every day, you need to change the configurations of the apps to behave similarly. Otherwise, as far as I can tell, most users "automatically" make many (sometimes fatal) mistakes.

**Comment by fire** [comment]
Closing due to lack of consensus.

**Pull request closed without merging**
