### PR TITLE
Rename WinRT platform to UWP

### PR DESCRIPTION
**Pull request by vnen**
Using the legacy name usually causes confusion, Universal Windows Platform is now the official name for it.

Note: rename the `winrt` tag here in GitHub when this is merged.

### CODE REVIEW

**Comment by punto-** [comment]
I like the legacy names so I vote no (but it's just a vote, I'm fine if
everyone else prefers the new name)

**Comment by vnen** [comment]
Well, I've seen some people making the confusion, thinking "WinRT" is just the old capped Windows 8 for tablets. I know that "Windows Runtime" is still used under the hood by Microsoft, but in Godot's case we specifically make UWP apps.

I'm not married to this change either, if others prefer the legacy name we can keep it.

**Comment by reduz** [comment]
I vote for rename

**Comment by bojidar-bg** [comment]
I would say, rename, so we can distinguish platforms better (`win` and `winrt` are pretty close as names).

**Comment by akien-mga** [comment]
I'd be for renaming too, though I don't have a strong opinion either way. Looks like other engines are trying to make the distinction between WinRT of Win8.1 and UWP clearer: http://xenko.com/blog/toward-a-better-dotnet/

**Pull request merged**
