### PR TITLE
Restructure environment in render implementation

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Giving environment the same treatment as I did geometry instance, we already kind of had done this for the Render Device based renderer and then duplicated implementation for GLES3. I brought the structure somewhat forward so `RenderingSceneRender` has the outward facing API with RIDs, but then expects a subclass of `RenderEnvironment` to be created by the implementation and interacts with that. The implementation subclasses `RenderEnvironment`s virtual functions to actually implement the environment class.

Work left to do is to simplify a bunch of things in the implementation itself as it no longer needs access methods to get to data and probably just pushing a pointer to the environment around instead of always going through the RID which is not efficient nor needed inside of the render.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
After discussing this at length with Reduz in the rendering channel we've decided to simplify this a whole lot more. Environment information is pretty much just storage for data. We'll move the implementation into storage and create an `RenderEnvironmentStorage` class that keeps track of all the `RenderEnvironment` instances. Then embed the storage class into `RendererSceneRender`.

There will be no need to inherit the environment class (might even bring it back to a struct).

**Comment by reduz** [comment]
I think accessing the internal Environment pointer and structure members should be a no go. We _will_ need to expose this to GDExtension, for which the getters have to be made anyway.

**Review by reduz — APPROVED** [review]

**Comment by BastiaanOlij** [comment]
I'll hook up access calls to `RendererScene` in tomorrow morning and then this should be ready for merge.

This will need to be tested well as this touches a lot of code.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
