### PR TITLE
Open visual editor when "open editor" button in the inspector is pressed

### LINKED ISSUE #20111: "Open in Editor" button doesn't work with visual scripts
Godot Master, Linux

In the inspector, the "Open Editor" under the "scripts" sections works fine for a gdscript, but doesn't do anything if the script is a Visual Script. The icon in the scene tree dock works as it should.

Steps to reproduce:
- create a visual script for a node in the tree
- go back to the scene, and check the inspector for that node
- scroll to the script section and open it if necessary
- click the "open in editor" button, nothing happens

### PR DESCRIPTION
**Pull request by nunodonato**
Open visual editor for visual scripts when "open editor" button in the inspector is pressed.
Fixes #20111

### CODE REVIEW

**Comment by akien-mga** [comment]
Reverted as it caused #20501.

**Comment by reduz** [comment]
This is now fixed properly, please dont merge stuff like this before asking

**Comment by MarianoGnu** [comment]
@akien-mga shoudn't you remove the cherry pick label?

**Comment by akien-mga** [comment]
Yes, thanks.

**Pull request merged**
