### PR TITLE
Remove unused `force_quit` variable from many OS abstractions

### PR DESCRIPTION
**Pull request by RandomShaper**

### CODE REVIEW

**Comment by aaronfranke** [comment]
There's also `force_quit = false;` in the constructor.

**Comment by akien-mga** [comment]
It's not just Windows :)
```
$ rg force_quit
platform/linuxbsd/os_linuxbsd.h
46:     bool force_quit;

platform/linuxbsd/os_linuxbsd.cpp
522:    force_quit = false;
535:    while (!force_quit) {
733:    force_quit = false;

platform/windows/os_windows.h
113:    bool force_quit;

platform/uwp/os_uwp.cpp
784:    while (!force_quit) {
814:    force_quit = false;

platform/windows/os_windows.cpp
905:    while (!force_quit) {
1135:   force_quit = false;

platform/macos/os_macos.mm
515:    force_quit = false;
524:    while (!force_quit && !quit) {
544:    force_quit = false;

platform/uwp/os_uwp.h
109:    bool force_quit;

platform/macos/os_macos.h
43:     bool force_quit = false;

platform/android/java_godot_wrapper.h
90:     void force_quit(JNIEnv *p_env = nullptr);

platform/android/java_godot_wrapper.cpp
167:void GodotJavaWrapper::force_quit(JNIEnv *p_env) {

platform/android/java_godot_lib_jni.cpp
251:            godot_java->force_quit(env);
```
(the Android one seems valid, the rest is always `false`)

**Comment by RandomShaper** [comment]
Updated to remove it from all the OSs where it's no longer used.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
