### PR TITLE
Fix exporting with export template binaries over 2.0 GiB

### LINKED ISSUE #67572: Godot produce 0 bytes binary if template binary is bigger than 2GB
### Godot version

4.0.beta.custom_build. 28a4eec9a

### System information

Ubuntu 22.04 - Nvidia GTX 970, Gnome shell 42 X11

### Issue description

When trying to use as export template file bigger than 2GB, then Godot export app with empty binary and not empty pck file

### Steps to reproduce

- Create random files
- Smaller that 2GB - `dd if=/dev/zero of=a.img bs=1 count=1 seek=1800M`
- Bigger that 2GB - `dd if=/dev/zero of=a.img bs=1 count=1 seek=2200M`
- Try to choose them as export templates
- Export project

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by qarmin**
Fixes https://github.com/godotengine/godot/issues/67572

Also silences some overflows/undeflows which are visible under llvm sanitizers

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Export fix looks good.

But I'm not sure about all these casts, aren't the best thing for the code readability, and not doing anything.

**Comment by qarmin** [comment]
Removed part with changes to silence LLVM(except one which looked strange before) because I found that this could be automatically found by adding `-Wsign-conversion`.
I think that Godot should add to CI `-Wsign-conversion` or even `-Wconversion`(which contains `-Wsign-conversion` and few more flags) to catch this earlier just like rust does(even if this will decrease little code redability)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by timothyqiu** [comment]
Cherry-picked for 3.5.2

**Pull request merged**
