### PR TITLE
New load icon, removed unused open icon

### PR DESCRIPTION
**Pull request by pkowal1982**
In my opinion current load icon is not good enough, sometimes at first glance I mistake it with save, as it is solid and has right top corner cut off (especially when save icon is grayed out).

Also I've removed open icon as it was only copy of load icon and was unused.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @djrm.

**Comment by djrm** [comment]
seems good, but i don't know how it will look in the editor

**Comment by pkowal1982** [comment]
@djrm Hi and low DPI versions:

hdpi
ldpi

**Comment by djrm** [comment]
looks good

**Pull request merged**
