### PR TITLE
Performance improvements for GLES2 CPU blendshapes

### PR DESCRIPTION
**Pull request by pixaline**
Improvement of my GLES2 CPU blendshape implementation. (#48480)
Instead of calculating the shape buffer data every frame, it only does so when the blend values change, leading to much better idle performance. However, converting the vertex data is still somewhat slow, which becomes apparent when frequently changing the blend shape values. But at the very least it should happen outside of the rendering function.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks great! Thanks for PRing this. 

As a side effect this PR also fixes a bug that arises when 2 MeshInstances share a Mesh that uses blendshapes.

**Comment by akien-mga** [comment]
Could you squash the commits?

**Comment by parulina** [comment]
@akien-mga There!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
