### PR TITLE
Update .clang-tidy

### PR DESCRIPTION
**Pull request by AndersonMartins1**
Main changes:

Organization and Spacing:

I adopted consistent formatting, aligning keys and values to improve readability. Removing Redundant Quotes:

I removed the redundant quotes around the keys and values to simplify the code. Standardization of Single Quotes:

I used single quotes for key values, maintaining consistency in formatting. Indentation Adjustment:

I adjusted the indentation to ensure a clearer, easier-to-follow structure. These changes aim to improve the readability and maintenance of YAML code. If you have any further questions or need further clarification, I am at your disposal!

### CODE REVIEW

**Comment by AThousandShips** [comment]
This makes the readability of this file worse, and serves no other purpose

**Comment by AndersonMartins1** [comment]
ok

**Comment by AThousandShips** [comment]
If you are looking to contribute, please try solve a bug or improve some code :)

**Comment by AndersonMartins1** [comment]
Can you tell me the bugs?

**Comment by AndersonMartins1** [comment]
I want to help

**Comment by AndersonMartins1** [comment]
I didn't find a folder with the name of errors or bugs

**Comment by AThousandShips** [comment]
This is where you find bugs :)
https://github.com/godotengine/godot/issues

**Comment by RedMser** [comment]
@AndersonMartins1 You can search for issues in this repository to find open bugs. In particular, ones marked as [good first issue](https://github.com/godotengine/godot/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) can be a great way to get started.

**Comment by AndersonMartins1** [comment]
thank you for the tips

**Comment by AThousandShips** [comment]
See also [here](https://docs.godotengine.org/en/stable/contributing/ways_to_contribute.html) for guides about contributing :) And welcome!

**Comment by akien-mga** [comment]
This doesn't seem to be an improvement. This indentation comes from `clang-tidy`'s own config dump, there's no reason to undo it.

**Pull request closed without merging**
