### PR TITLE
Add the ability to pause the AnimationTree inside editor.

### PR DESCRIPTION
**Pull request by CrayolaEater**
Proposal: https://github.com/godotengine/godot-proposals/issues/9072
Inside the editor now the AnimationTree can be paused.
image

### CODE REVIEW

**Comment by TokageItLab** [comment]
Does this implementation solve any problems, is there aproposal?

I don't see why this is needed at all and the implementation approach is too bad. I would not put behavior in core that only affects the editor.

**Comment by CrayolaEater** [comment]
> Does this implementation solve any problems, is there any proposal? If you want to add a feature, send the issue to https://github.com/godotengine/godot-proposals first and follow the legal steps.
> 
> I don't see why this is needed at all and the implementation approach is too bad. You should not add the behavior in runtime that only affects the editor.

Yes, this solves the issue of constantly playing animations inside the editor. There is no purpose in that, only to preview the animation when needed, thats why the value can be changed at will. Also there is an issue with animations playing inside the editor: When saving the bones of current position is saved inside the scene resource so this PR aims to also take care of that.

Regarding the implementation, instead of saying that's bad please come with suggestions that could be improved, this is my 2nd PR ever to the godotengine and its pretty hard to get used with the codebase.

**Comment by TokageItLab** [comment]
> When saving, the bone transforms of current animation play position is saved inside the scene resource so this PR aims to also take care of that.

After Godot 4.2, AnimationTree Have "Reset on Save" option and there is no issue. If it is not working, send the issue.

> Regarding the implementation, instead of saying that's bad please come with suggestions that could be used improve it, this is my 2nd PR ever to the godotengine and its pretty hard to get used with the codebase.

We cannot know what to point out if there is no issue or proposal and we do not know what the purpose of the implementation is.

Usually we do not close PRs this way. However, if there is no explanation, then the code appears to be a clearly unnecessary implementation and should never have been merged, that is an exception. We need to close duplicate PRs, and I did that.

**Comment by CrayolaEater** [comment]
> I don't see what is insufficient in the normal "Active" option. If you want to do that, just leave Active off and only activate the Tree in Script when the scene is run. Only one line code can do it.

What if I have multiple animations ? It's pretty annoying to do that for every one. Also, what if I already have logic in my game to handle Active property of the AnimationTree? This will interfere with that logic.

**Comment by TokageItLab** [comment]
> It's pretty annoying to do that for every one.

Conversely, if all nested AnimationTrees are off, previewing in the editor becomes difficult. It makes no sense at all to implement that as an option. If it is really necessary, you can make an add-on to add such a default code.

Just do it with `_ready()` or `_on_enter_tree()`. If you can't do that, then there is something wrong with your architectural design.

**Comment by TokageItLab** [comment]
As I wrote in https://github.com/godotengine/godot/pull/88212#issuecomment-1937814536. Either way, that PR approach is wrong.

I wrote all about it here. Either way, that PR approach is wrong.

On the off chance that you do implement a way to manage a scene-wide AnimationTree in the editor, it must be in `animation_tree_editor.cpp`, not in `animation_tee.cpp`.

**Comment by CrayolaEater** [comment]
Either way, there is no reason to close the PR. I understand that there need to be modifications, so request changes. Now there is even a linked proposal.

**Comment by TokageItLab** [comment]
You can send a new PR. It will not be closed unless the approach is so wrong.

**Comment by Mickeon** [comment]
No need to get aggressive, @TokageItLab . Do rethink your words. If we expect people to follow [Code of Conduct](https://godotengine.org/code-of-conduct/) we need to be the first ones to follow them.

I do trust your judgement but I cannot dismiss this not being an actual issue just yet, even if the solution in this PR is... not that good. It's hard to judge, admittedly. Multiple AnimationTree nodes at once is not a common scenario.

**Comment by TokageItLab** [comment]
I apologize if I have offended. I must be a bit frustrated right now, especially during this busy review period.

So as I said more above, we usually don't close PRs if I know their purpose, even if it is the not good way. Now that I somewhat understand the purpose with the proposal and additional information, but this PR seemed at first to be a complete duplicate function with no issue and no proposal. While we are happy about sending you a PR, please understand that you may not feel very comfortable if you don't follow the proper steps, so issue and proposal are important.

Now, the reason why we still should not open this PR is not that I am being offensive. The implementation that should be done is not to add to this PR, but to rewrite all the code in this PR, so there is no point in keeping this PR.

If you are implementing it in the editor, we should be less sensitive, but PRs that affect runtime can be broken for many projects and workflows, so we have to be cautious. In any case, you should first try to see if you can work around it with an add-on as I described in your proposal https://github.com/godotengine/godot-proposals/issues/9072#issuecomment-1937820542. We can consider PRs that expose some methods to the editor because of a missing API, if we know the reason for it as issue or proposal.

**Pull request closed without merging**
