### PR TITLE
[make_rst] Remove (fake) return types on annotations

### PR DESCRIPTION
**Pull request by asmaloney**
Based on discussion in #63561, @YuriSizov mentioned that the return types are not necessary here, so remove the fake "void" return types on annotations.

~~(Can be cherry picked to 3.x, but probably not worth it/necessary?)~~

### CODE REVIEW

**Comment by YuriSizov** [comment]
> (Can be cherry picked to 3.x, but probably not worth it/necessary?)

No annotations in 3.x, I'm afraid :)

**Comment by asmaloney** [comment]
> No annotations in 3.x, I'm afraid :)

Ah - yeah. I had thought the code was the same between the two anyways, but I see that it isn't. Onward to 4.0! 😄

**Review by YuriSizov — CHANGES_REQUESTED** [review]
The bit around line 820 should probably also be adjusted to remove an unnecessary empty space. We don't need to use the return type here as it's empty anyway.

```python
                ret_type, signature = make_method_signature(class_def, m, "", state)
                f.write("- {} {}\n\n".format(ret_type, signature))
```

Otherwise, it's good!

**Comment by YuriSizov** [comment]
Can you please squash your commits? We ask this of contributors to have a clean commit history.

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
