### PR TITLE
Properly handle empty CSGShapes

### LINKED ISSUE #44713: "Cannot get CSGBrush" and other errors when creating a CSGMesh
**Godot version:**
Godot 3.2.4 dev 279f4fbb5f83c2df6e8499799a2aa0c14f85aa2d
Might happen too in Godot 4.0

**OS/device including version:**

**Issue description:**
An error occurred when I created a `CSGMesh`. I had a C++ debugger attached with a breakpoint in the error callback to catch my own stuff initially, but I got several unexpected errors like this one.
```
RROR: Cannot get CSGBrush.
   At: modules\csg\csg_shape.cpp:280
ERROR: VisualServer::mesh_add_surface_from_arrays: Condition "array_len == 0" is true.
   At: servers\visual_server.cpp:965
ERROR: ArrayMesh::add_surface_from_arrays: Condition "len == 0" is true.
   At: scene\resources\mesh.cpp:849
```
More of this happens when deleting the node.

**Steps to reproduce:**
I created a new scene, created a Node root node, then a MeshInstance with a PlaneMesh inside, then a CSGMesh. Then my C++ debugger I had attached broke into the error callback (originally to catch my own stuff):
image

It is then followed by this:
image

**Minimal reproduction project:**
None, sorry

### PR DESCRIPTION
**Pull request by hoontee**
Fixes "Cannot get CSGBrush" error spam.
Fixes #44713.

### CODE REVIEW

**Comment by hoontee** [comment]
This is the same fix applied to empty CSGCombiners in #40919.

**Review by madmiraal — CHANGES_REQUESTED** [review]
The same change should be made for the other shapes. `CSGTorus` and `CSGPolygon` also return `nullptr`s instead of an empty `CSGBrush`, when they can't build a shape.

**Comment by hoontee** [comment]
> 
> 
> The same change should be made for the other shapes. `CSGTorus` and `CSGPolygon` also return `nullptr`s instead of an empty `CSGBrush`, when they can't build a shape.

Done!

**Review by madmiraal — APPROVED** [review]

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
