### PR TITLE
Add NOTIFICATION_OWNER_CHANGED

### LINKED ISSUE #26399: Duplicating a editor_only Light turns it dark
**Godot version:** f2003b1a7e5d3fce6448bd578a15bbf8f9462183

**OS/device including version:** Linux/X11 Intel graphics

**Issue description:**

When a light with the `editor_only` property set is duplicated, then the duplicate light will not work in the editor (which is unexpected. It should shine). Unsetting the `editor_only`-property on that duplicate will turn it back on, and setting the property again will keep it on in the editor (which is expected).

**Steps to reproduce:**
1. Create a scene with only a Cube MeshInstance
2. Create an OmniLight or a DirectionalLight (or probably a SpotLight, not tested) and position it such that one face of the cube is lit.
3. Turn on its `editor_only` option. It will still light the cube in the editor.
3. Right-click the light in the` scene tree and choose "duplicate".
4. Move the newly created light so that it should light a different face of the cube. Notice that it does not light the face.
5. Uncheck and re-check `editor_only` on that second light. Now it will lights the face.

### PR DESCRIPTION
**Pull request by Windfisch**
Lights now update their visibility when the owner changes.

Fixes #26399

### CODE REVIEW

**Comment by Windfisch** [comment]
A way that does not involve a new notification, but at the price of being hacky, is implemented at https://github.com/Windfisch/godot/commit/d4b4e0472cb130093ab4301c7b954327219ffe9a.
That alternative way works by using `call_deferred("set_editor_only",...` on a ENTER_TREE notification, causing the light visibility to be updated one frame later.

Since #26399 is caused by `get_owner()` not being set yet at the point of the ENTER_TREE notification, this can also resolve the original issue. But that would be a hack.

**Comment by reduz** [comment]
Sorry, I dont really understand the meaning of this and how it is related to visibility/light, it should have nothing to do.

**Comment by Windfisch** [comment]
@reduz: When a Light is duplicated or reparented, it *first* checks whether it should be drawn. When said light is set to `editor_only`, it wrongly comes to the conclusion "nope, don't draw me, since my owner is not an editor window". Only *after* that, its owner is changed from `NULL` to the editor window.

This leaves duplicated `editor_only` lights undrawn in the editor, which is unexpected to the user.

One possible resolution is to react on changes of the `owner` pointer, which is what this PR implements.

Please see also https://github.com/godotengine/godot/issues/26399, where the actual bug is explained.

Note that there is another possible workaround to this, that I have implemented in https://github.com/Windfisch/godot/commit/d4b4e0472cb130093ab4301c7b954327219ffe9a. However, this feels like a dirty hack to me.

**Comment by akien-mga** [comment]
Sorry for the lack of update the past months. I've been looking at this PR every now and then and I'm still not happy with having to add a whole new Object notification just for this purpose.

Usually we very strongly favor ad hoc changes (possibly like the hack you implemented in https://github.com/Windfisch/godot/commit/d4b4e0472cb130093ab4301c7b954327219ffe9a) over extending the core (especially Object) API for a corner case.

I'll close this for now as I don't think this would be merged, but we can reference it and discuss further in #26399.

**Pull request closed without merging**
