### PR TITLE
Stop crash when a scene has the tool keyword and _exit_tree() method

### PR DESCRIPTION
**Pull request by fire**
Fix for https://github.com/godotengine/godot/issues/34959

### CODE REVIEW

**Comment by fire** [comment]
Not sure how to handle this. Closing the tab will now memory leak.

**Comment by fire** [comment]
@vnen Can you look into this. I don't like this patch, but maybe you can fix this another way.

**Comment by akien-mga** [comment]
That's too Jacky, Node should not have any code from `editor/`.

**Comment by akien-mga** [comment]
As mentioned in the issue, the problem is not a bug per se, it's a normal limitation of `tool` scripts. There are many ways to crash the editor using `tool` scripts thanks to the full access they give you over the scene tree of the currently edited scene. It's normal and OK, but users need to be careful when writing scripts.

This would prevent one type of crashes, but not many others that are still possible with `tool` scripts. Preventing them would mean adding a lot of hacky code like this all over the Node and SceneTree APIs, making things slow for little gain.

**Pull request closed without merging**
