### PR TITLE
Project setting to control node name casing

### PR DESCRIPTION
**Pull request by RayKoopa**
As discussed in https://github.com/godotengine/godot/pull/7501, I modified my changes to make this a project setting.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Perfect :)

**Comment by akien-mga** [comment]
Just noticed that you had made this PR against the 2.2 branch - this one is not meant for development, it's just a legacy branch for people that need its features without the current brokenness of the master branch, but new developments should be done first in master, and then cherry-picked to other branches if relevant. I'll cherry-pick this one for master, but please keep this in mind for your next PR ;)

**Comment by RayKoopa** [comment]
I will, I was kinda confused myself. I could not get the master branch to run well on my Windows system, always crashed right after the project list, so I had to stick with this... =(

**Comment by akien-mga** [comment]
True, it's not optimal for development right now, it should settle in a couple of weeks.

**Pull request merged**
