### PR TITLE
Fix LOD generation for meshes with tangents & mirrored UVs

### LINKED ISSUE #67891: Visible LOD artifacts in Basketball
### Godot version

4.0beta3 (also exists on 4.0alpha17, so not a new issue)

### System information

Windows 10, Nvidia

### Issue description

LODs on this basketball causes visible artifacts such as the black line disappearing.

View showing no artifacts when zoomed in:
close-up of basketball

View showing LOD artifacts when zoomed out:
Display Normal, basketball with artifacts

View showing artifacts are gone when LODs are disabled.
Display Disable Mesh LOD, distant basketball with no artifacts

Closeup view of the artifacts, made by @fire :
Closeup of LOD artifacts

(unrelated to this issue, but this model's texture also has visible aliasing artifacts due to .glb, but that's a different bug. These texture artifacts do not happen if converted to .gltf + .jpg. please ignore texture artifacts for the purpose of this issue)

### Steps to reproduce

1. Import the zipped .glb below into a project.
2. Right click the .glb and choose New Inherited Scene
3. Leave the editor in the default orientation and zoom out.
4. You should see some black lines flicker or disappear

### Minimal reproduction project

[basketball.zip](https://github.com/godotengine/godot/files/9865899/basketball.zip)

### PR DESCRIPTION
**Pull request by zeux**
When UVs are mirrored in a mesh, collapsing vertices across the mirroring seam can significantly reduce quality in a way that is not apparent to the simplifier. Even if simplifier was given access to UV data, the coordinates would need to be weighted very highly to prevent these collapses, which would penalize overall quality of reasonable models.

Normally, well behaved models with mirrored UVs have tangent data that is correctly mirrored, which results in duplicate vertices along the seam. The simplifier automatically recognizes that seam and preserves its structure; typically models have few edge loops where UV winding is flipped so this does not affect simplification quality much.

However, pre-processing for LOD data welds vertices when UVs and normals were close, which welds these seams and breaks simplification, creating triangles with distorted UVs.

We now take tangent frame sign into account when the input model has tangent data, and only weld vertices when the sign is the same.

Fixes #67891.

### CODE REVIEW

**Comment by zeux** [comment]
Before:

image


After:

image

Notes:

The mesh on the left is from #67891; the mesh on the right is the same GLB file with explicitly generated tangents via gltf-transform. This PR relies on *correctly* generated tangents: when UVs are mirrored, the vertices on the mirror seam need to be duplicated and have two tangents, one pointing one way and the other pointing the other way (with TBN winding flipped between the two).

The reason I mention this is that the way Godot generates new tangents is actually incorrect: it does this using the current geometry indexing, instead of doing unindex/reindex. This prevents tangent generation from creating new vertices. This was changed ~6 years ago to make morph targets work, and since nobody noticed in 6 years it's probably fine (?), but this happens to work properly because the model in question has the seam in the index data in GLB whether or not tangents are generated, so things work out "magically". If you instead optimize the basketball GLB, welding the vertices in the file itself, then this PR does not fix the UV mapping issue because tangent generation is incapable of "unwelding" the vertices back.

So in that respect this is a partial fix, since the model needs to either carry tangent data or not result in incorrect tangents generated during import; otherwise the LODs may still result in significant texture distortion along the mirror seams. But it does fully fix the referenced issue.

**Comment by zeux** [comment]
Oh, for completeness, wireframe:

Before:

image

After:

image

You can see the simplifier preserving the tangent seams automatically which leads to correct texturing - these are the black lines. Note that the silhouette of these lines *is* getting simplified, it's just that vertices can't move away from that edge loop.

**Review by fire — COMMENTED** [review]
Wow thanks for looking into this bug from so many years ago!

**Review by fire — APPROVED** [review]

**Comment by fire** [comment]
Do you think we should also do a unindex index operation for tangents in a separate pr?

**Comment by akien-mga** [comment]
Thanks!

**Comment by Saul2022** [comment]
Off topic, but taking about auto lod issues, would you know why lods don't get generated on mesh like this that are composed of multiple planes?  Like this mesh https://drive.google.com/file/d/1czYZfTO44jrIHldhUIBgEbucKBzLZpev/view

**Comment by zeux** [comment]
> Do you think we should also do a unindex index operation for tangents in a separate pr?

This is a little delicate: the original change I referred to from 6 years ago is https://github.com/godotengine/godot/pull/23991, which was explicitly fixing tangent generation disrupting indexing for morph targets. Properly handling this requires tracking indexing and remapping target arrays, maybe using something similar to `ImporterMesh::Surface::split_normals`. I'm also not sure whether unindex/reindex affects tangent generation time meaningfully, that would need to be tested. So overall ideally I do think Godot should generate the tangents correctly when UVs are mirrored regardless of the input indexing, but this is delicate enough that maybe it's fine to wait for somebody to run into this problem in a visible manner.

**Pull request merged**
