### PR TITLE
[3.x] Fix crash in AudioServer when switching audio devices with different audio channels count

### PR DESCRIPTION
**Pull request by Listwon**
Fixes https://github.com/godotengine/godot/issues/52275 

Switching audio devices with different audio channels count caused crashes in `AudioServer::_mix_step()` because it tried to access non-existent effects instances in `bus->channels[k].effect_instances`. `AudioServer::init_channels_and_buffers()` is called if there is change in `get_channel_count()`. The update of effects (creating new effects instances) on new channels was missing here.

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this only relevant for `3.x`, or is there the same bug in `master`?

**Comment by Listwon** [comment]
@akien-mga I've just tried to reproduce it in `master` build and it's the same bug (easy reproduction with PS5 controller connected/disconnected via USB cable), the same fix works on `master` too. Should I prepare separate PR for `master` or you'll apply it yourself when it's tested and merged on `3.x`?

**Comment by akien-mga** [comment]
A separate PR for `master` would be great. We usually only cherry-pick from newer to older branches, so we don't have a pipeline to keep track of changes the other way around.

**Comment by ellenhp** [comment]
What happens if the audio thread is actively mixing when this happens? I could imagine we might need to lock the AudioServer in this method before messing with the buffers? LGTM though, because this should fix it most of the time.

**Review by ellenhp — APPROVED** [review]

**Comment by Listwon** [comment]
@ellenhp I thought the same initially, but if I'm not mistaken `init_channels_and_buffers()` is called synchronously before the `_mix_step()`. Both in the same audio thread, where AudioDriver is already locked before those calls.
obraz

**Comment by ellenhp** [comment]
@akien-mga I've approved both of these and I'll let you either merge both or merge into master and cherry-pick or whatever we want to do.

@Listwon Thanks for figuring this out and fixing it!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.5.

**Pull request merged**
