### PR TITLE
3.0 restore config file name

### PR DESCRIPTION
**Pull request by sersoong**

### CODE REVIEW

**Comment by rminderhoud** [comment]
Might need to refactored if #13053 gets merged.

**Comment by sersoong** [comment]
I got it.

**Comment by akien-mga** [comment]
I'll do the change myself as it should use `itos` instead of `_MKSTR` after #13053, and we don't need 3 commits to change one line ;)

**Comment by sersoong** [comment]
good

**Comment by akien-mga** [comment]
Superseded by d3889ad1b.

**Pull request closed without merging**
