### PR TITLE
[WIP] Add basic import shader support

### PR DESCRIPTION
**Pull request by fire**
Implements https://github.com/godotengine/godot-proposals/issues/944. Also see https://github.com/godotengine/godot/issues/17303. This salvages https://github.com/godotengine/godot/pull/17797.

The syntax is `import "res://new_shader.shader";`

image

### CODE REVIEW

**Comment by fire** [comment]
[Import Shader Project.zip](https://github.com/godotengine/godot/files/5143463/Import.Shader.Project.zip)

Example project.

Remaining problems:

1. Caching is incorrect.
2. Nested includes needs a better method.

**Comment by fire** [comment]
@clayjohn mentioned a proposal to make a new shader type called "include".

`shader_type include;`

<ClayJohn> [It] can only be included by other shaders. It wouldn't be allowed to have render modes or processor functions.

**Comment by Ansraer** [comment]
Since you have mentioned #17303 and #17797, do you have any intentions to add preprocessor directives to this PR?

**Comment by fire** [comment]
No.

You can use uniforms and variables for #define and if else statements are already in the language.

**Comment by fire** [comment]
This needs to be ported to the latest master. It is salvageable, but I am currently lacking effort on it.

The last tasks are to make sure the include detection handles multiple layers correctly.

**Comment by MagdielM** [comment]
I am interested in salvaging this. As of right now, I've managed to port the changes to c0d01dcf6185e9090d6b6a1cd7682404d411b72b and at least gotten around `import` not being recognized as a shader type. I'll admit I'm not too familiar with how the parser works as of yet, but I care enough about this feature to put in the time.

**Comment by CsloudX** [comment]
I need this feature too.

**Comment by fire** [comment]
@MagdielM did you post your work anywhere?

**Comment by MagdielM** [comment]
> @MagdielM did you post your work anywhere?

Oh sorry, after three-or-so weeks of trying to get multiple nesting levels to work and not getting very far, other responsibilities started piling up and I had to put this in the backburner for the time being. I apologize for not mentioning this earlier.

**Comment by Calinou** [comment]
> > @MagdielM did you post your work anywhere?
> 
> Oh sorry, after three-or-so weeks of trying to get multiple nesting levels to work and not getting very far, other responsibilities started piling up and I had to put this in the backburner for the time being. I apologize for not mentioning this earlier.

Could you push your code to a branch and link it here? It would likely be helpful if someone is willing to continue this.

Also, I'd argue that even supporting a single level of `#include` is much better than supporting zero :slightly_smiling_face:

**Comment by MagdielM** [comment]
My work includes a small dependency graph that is supposed to update all included shaders, but I couldn't quite figure out why the parser fails to nest the `#include`s, so ultimately it doesn't do much.
cd198c27a1e9bbdc4fa60d5ae07be3b88ff8f599

**Pull request closed without merging**
