### PR TITLE
Better buffering for WebSocket

### LINKED ISSUE #22496: Buffer full while polling websocket
**Godot version:**
v.3.1.alpha.custom_build. a2b6be2

**OS/device including version:**
Windows 10 Home v1803 (April 2018 update) x64

**Issue description:**
When polling the websocket and receiving a payload that in total would be bigger than 65535 bytes over all packets it takes to construct it, the following message prints out in the console:

```
ERROR: Buffer full! Dropping data
   At: modules\websocket\lws_peer.cpp:69
```

While I understand this seems to be intentional after digging into the code, this has two main issues:

1. It seems to corrupt the payload that the developer's code will get when checking for payloads. If I have a JSON payload where I receive, let's say `{"data":{"name":"Help","age":42}}`, imagine only getting `:{"name":"Help","age":42` -- that's basically what's happening here.

2. A websocket payload can be bigger than 65535 bytes, so why does it seem like this websocket implementation is limiting that size?

**Steps to reproduce:**
Receive a single websocket payload that would be more than 65535 bytes (including the 5-byte header) total.

**Minimal reproduction project:**
N/A (Without giving out a token my project uses for a service, I can't really provide a reproduction project, so you may have to set up a websocket server that will send out a payload that big)

### PR DESCRIPTION
**Pull request by Faless**
After a lots of thoughts, I still can't help myself thinking changing PacketPeerUDP and adding PacketBuffer to core was too excessive, so unless more things come up that needs it, it will stay in the websocket module instead.

In this PR:
- Added `RingBuffer::decrease_write` to allow "discarding" the latest written bytes.
- Add new `PacketBuffer` class, in websocket module, to simplify buffer handling (originally, this was moved to `core/` and `PacketPeerUDP` used it too, but maybe that's a matter for another PR if this proves to be the right decision).
- Add ProjectSettings options to define input and output buffer sizes, and packets limits for WebSocketClient and WebSocketServer (note, `WebSocketClient` output buffer is unused in HTML5, and fully depend on the browser implementation, which is usually up to 2gb).
  Defaults: `packets = 1024` `buffer = 64 KiB`. Server buffers are intended *per peer*.

buffers2

Fixes #22496

### CODE REVIEW

**Comment by LikeLakers2** [comment]
`Allow setting buffer size & max packets WebSocket` a84c22fe231c218a5877abf7c6abbc62ab0c0cb3

Yessss. Thank you, Faless. That would solve #22496. Thank you. 👍

**Comment by Faless** [comment]
Updated PR, removed core changes (`PacketPeerUDP`), will do that another PR in case

**Comment by Faless** [comment]
> Time for an update now I think ;)

@akien-mga indeed it was :)

**Comment by Faless** [comment]
Update PR to use KiB directly for buffers (and actual number for packets).
Sadly, due to the way we capitalize, they look like kilo-bits. Also, maybe I should write `kib` instead? Should really be `KiB` to be correct.

**Comment by akien-mga** [comment]
>  Sadly, due to the way we capitalize, they look like kilo-bits. Also, maybe I should write kib instead? Should really be KiB to be correct.

I think it's good enough to use `KB`, in a computing environment most people understand that it's for 1024/kibi and not the SI kilo.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
