### PR TITLE
Improve behaviour of clip_children by clipping to parent alpha value but still retaining parent color

### LINKED ISSUE #49198: Vulkan: Clip Children has wrong blend mode and a rendering issue
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:** Master branch, b63f9b5

**OS/device including version:** Linux, 1050Ti (w/proprietary drivers). I also had someone who said they have an RX 580 confirm. Vulkan.

**Issue description:** I *expect* this feature to work like the clip content option that nodes in the Control family have, where visuals outside of the parent disappear. And that is all that should happen (at least by default).

Clip children causes blending that shouldn't happen (pure white is rendered as *seemingly* transparent, other colors mix with the parent). 

The opaque parts of the parent that aren't covered by children are darkened (except for pure white, which it turned into transparent due to the blending). 

There is also a rendering error where already-rendered stuff (the buffer?) is repeated. This will cause the seemingly-transparent parts to actually render the background (or any other details) over other content (rather than simply showing what is behind it).

**Steps to reproduce:** Have a visual node (label, sprite, polygon) with another visual child node, enable clip children in the inspector (canvas item>visibility>clip children). For the rendering issue, see notes at the bottom (but in general, you need other visual things to see it).

**Minimal reproduction project:** [clip_children_rendering_issues.zip](https://github.com/godotengine/godot/files/6565404/clip_children_rendering_issues.zip)

**Demonstration of project**: 
Left is unclipped.
The icon.png in the label, the 2nd icon.png on the right (and the matching triangle) are the rendering issue.
clip_children_rendering_issues

--------------------------

Other notes:

- the rendering issue depends on the draw-order of the scene tree
- it also depends on the view itself, even editor pan and zoom
- a parent with clipped children enabled but no children will have incredibly odd rendering
- the clipped pieces can in certain instances show on other parents that clip. For instance when zooming in close: 
clipped_showing

------------------

A checklist with more technical/shortened descriptions:

- [ ] Backbuffer ghosting and seemingly related dark overlay on parent (note: either 1 line fix OR issue pointed out? see my comment that mentions line 1382 EDIT: I've tested with an FXAA screen shader and it seems to screw up the backbuffer with the line edit, so it's likely not the proper fix...)
- [ ] Parent node, in areas not covered by clipped child, renders white as transparent (same note as above)
- [ ] Child nodes have ugly color blend and have brightness turn to alpha (full white, fully transparent) rather than keeping their unclipped appearance (seems to be caused by multiply mode)
- [ ] Enabling clipping for nodes that have no visible children causes rendering issues, seemingly an unhandled condition.
- [ ] In some cases (like the item above), areas erased from clipping can render onto other nodes that have clipping enabled
- [ ] Recursive clipping renders in the wrong order (grandchild renders behind its parent, properly clipped by grandparent but not parent. Changing z-index only breaks clipping further)
- [ ]  Clipping does not work with the Vulkan Mobile renderer (instead it glitches, likely because it's an unhandled status)

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/49198

This PR turns ``clip_children`` into an enum that allows for 3 distinct behaviours

**CLIP DISABLED**

Child draws over parent and is not clipped

Screenshot from 2022-10-12 12-51-32

**CLIP ONLY**

Parent is used for the purposes of clipping only. Child is clipped to the parent's visible area, parent is not drawn.

Screenshot from 2022-10-12 12-51-35

**CLIP AND DRAW**

Parent is used for clipping child, but parent is also drawn underneath child as normal before clipping child to its visible area.

Screenshot from 2022-10-12 12-51-38

I have two points for discussion:
1. Are we happy with these two modes? In the comments to this and the linked issue I have seen demand for both
2. Are we okay breaking compatibility? Right now compatibility isn't totally broken, if ``clip_children`` was enabled in the inspector it turns into CLIP_ONLY which is fine, but scripts accessing the setter and getter will break. I can easily adapt this to not break compatibility either by reverting the second commit or by leaving the ``clip_children`` bool in place and having a seperate enum that only appears when ``clip_children`` is ``true``

<details>
  <summary>Original Description (applies to commit 1)</summary>

This brings the behaviour of ``clip_children`` more in line with that of ``Control.clip_contents`` except the alpha value of the parent node is respected.

Opening as a draft so we can discuss if this is the behaviour we actually want out of ``clip_children``. 

An important difference between this and the current master is that in the current master if the parent object is plain white (like a default Label) then the parent disappears in places where the child does not overlap. 

_Example from [blog post](https://godotengine.org/article/godots-2d-engine-gets-several-improvements-upcoming-40)_
5fc29d9142907447129624

For colored parents they are both visible in master and after applying this PR. 

_Before:_

194419109-e00c164e-1b9a-40c2-ac53-e66a8d4f19cf

_After:_

194429803-3e88468b-fb68-4c19-9020-a4ee69d57ab5

</details>

### CODE REVIEW

**Comment by markdibarry** [comment]
Mentioned on the linked issue, but I like "Clip based on parent alpha only" and "Clip children but keep parent". I can see use-cases for both, but if I had to only pick one, I'd go with "Clip based on parent alpha only". That seems the intended way, most intuitive, and probably most used.

**Comment by insomniacUNDERSCORElemon** [comment]
> I'd go with "Clip based on parent alpha only". That seems the intended way, most intuitive, and probably most used.

A node you've created is now invisible and the created shape/data is lost unless covered by other nodes, why? 

I see 2 scenarios where it makes sense, either you're looking to create transparent fadeoff somewhere OR you're trying to make a container of some kind (be it a potion, gummybears... or something like an aquarium or ant-farm where you want more transparency). I expect users will most commonly not want those exact 2 things and will instead need to use a work-around.

OTOH, the method shown in this draft (that I support) is the choice for adding details to characters or to create general art (face, belts/chain, stains/stickers/bandages, shadows/highlights, dirt or some other texture etc on-top-of your original node) that has endless use, including dynamic ones (like an eye, effects like an elevator into the ground, or something screen-like).

Repeat from elsewhere, but relevant:

Testing materials with beta2 and noticed something: the material happens *after* clipping....  modifying the nodes rendered before-but-not-after it. Thus you can intuitively choose (via render order) what nodes have their alpha changed. For instance, line with 0 alpha and multiply blend: 

ArcoLinux_2022-10-06_20-10-12

Via this method, it seems `Clip based on parent alpha only` makes even less sense. Though I'll admit blend modes are still clunky (the simple addition of `subtract_alpha` would go a long way IMO). I am not sure how much blend modes are altered by beta2's clip rendering though.

Also: a `mask` blend mode, though I'm not sure how you'd resolve something like pure white that has 50% alpha. Maybe more blend stuff (like darken-only), especially if it didn't need canvasgroup/clipping to function properly.

**Comment by markdibarry** [comment]
@insomniacUNDERSCORElemon Now that you mention it, I was thinking more based on what the original proposal was advertising, but I think you're right and most of the use cases would be closer to "Clip children but keep parent".

I think adding separate blend modes to recreate the old Light2D features would also be a nice feature, but that's probably outside the scope of this draft, but would be very beneficial as a proposal if one wasn't already made.

**Comment by insomniacUNDERSCORElemon** [comment]
I just tested this and it works as expected except for one thing: 

the multiply blending mentioned in my previous comment doesn't work (nor can I find a blending configuration that deletes alpha). Purely for investigation if it can be had, the trick still works in a canvasgroup. Related to canvas group mode?

Though I suspect blend modes just need to be rethought/redone so they are actually useful.

Sidenote, it's still an issue if you enable clipping on a node that does not have a (visible) child. In this version it will render as black, although unfortunately this can also make *other* clip-related nodes render as black (it seems to do this to the node that rendered before it/above it in scene tree).

**Comment by clayjohn** [comment]
> I just tested this and it works as expected except for one thing:
> 
> the multiply blending mentioned in my previous comment doesn't work (nor can I find a blending configuration that deletes alpha). Purely for investigation if it can be had, the trick still works in a canvasgroup. Related to canvas group mode?

CanvasGroup has a few differences from clip_children. Notably, CanvasGroup renders to a transparent backbuffer before copying to the front buffer. When rendering to a transparent buffer alpha blending can behave a little differently. So it's expected that tricks you can pull with the multiply blend mode may work in CanvasGroup but may not work with clip_children. At any rate, that is way beyond the scope of this PR 

> Though I suspect blend modes just need to be rethought/redone so they are actually useful.
> 
> Sidenote, it's still an issue if you enable clipping on a node that does not have a (visible) child. In this version it will render as black, although unfortunately this can also make _other_ clip-related nodes render as black (it seems to do this to the node that rendered before it/above it in scene tree).

I think I fixed that issue in https://github.com/godotengine/godot/pull/67051

**Comment by insomniacUNDERSCORElemon** [comment]
> So it's expected that tricks you can pull with the multiply blend mode may work in CanvasGroup but may not work with clip_children. At any rate, that is way beyond the scope of this PR

I brought it up because it is relevant to the implementation and because it's possible with clip_children in beta2 and before (see screenshot I posted above, though I do expect it was a side-effect of the problem). If you cannot re-add the capability then I definitely think there should be an option for `Clip based on parent alpha only` as otherwise I am not aware of how you would get that capability other unless the user can write a shader for it.

That aside... the ability to also work subtractively (even if it were restricted to full transparency) is really powerful and fast on its own (and there aren't good work-arounds).

**Comment by DrCanvas** [comment]
I'm not sure how this feature was meant to be used. But the current state is useless for me:
gdexm0xx02

I personally would use it for animated revealing masks. Something like this:
gdexm0xx

Unfortunately, this is not possible right now. For that we need to change behavior from "clip children" to "clip parent".

**Comment by Zireael07** [comment]
@DrCanvas I think there's a proposal already open for what you want?

**Comment by insomniacUNDERSCORElemon** [comment]
The top one is beta2 or sooner, not the changed version.

> Unfortunately, this is not possible right now. For that we need to change behavior from "clip children" to "clip parent".

> I think there's a proposal already open for what you want?

This is what I was exactly talking about in my 3 comments above, it **was** possible with blending modes before (canvasgroup--that still works--in image, but it worked with clipping too): 

wrmpear

Hopefully it is viable to have clipping do this while also working for art. More flexibility would be nice too, but I'm not sure how much is possible with the current method.


> I'm not sure how this feature was meant to be used.

Similar to clip_contents of control nodes, but via pixels instead of bounding box.

With this pull, icon is parent (yes, the green bit can be animated):

ArcoLinux_2022-10-08_08-34-07

**Comment by markdibarry** [comment]
Since we can only pick one for the moment, I think the best solution would be to fix the bugs associated with this, and merge the feature as proposed in this draft. Then open up a new PR to expand this as a "clip_mode" dropdown that we can continuously add to, to accommodate other modes. The benefit, as I see it, is we'd have a better chance of getting new features in smaller releases.

**Comment by insomniacUNDERSCORElemon** [comment]
I've done some percussive coding and have a partial solution that fixes some of the issues I've talked about.

Code (in `renderer_canvas_render_rd.cpp`):

```
void fragment() {
	vec4 c = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0);
	COLOR.rgb = c.rgb;
	
	if (COLOR.a != 0.0 && c.a != 0.0 && c.a >= COLOR.a) { //child restores parent opacity.
		COLOR.a = c.a;
	} else if (COLOR.a != 0.0 && c.a == 0.0) { //transparent pixels of child can erase parent via blend modes
		COLOR.a = c.a;
	}
	
}
```

Examples:

ArcoLinux_2022-10-10_03-49-11

Description: So if it isn't clear, this is `Clip children but keep parent` except:

* if you set parent to lowest non-zero alpha value for color (polygons/lines) or selfmodulate (any canvasitem), it will act as an invisible container (like `Clip based on parent alpha only`)
* children with blend modes work like they did in older versions, multiply mode allows deleting pixels if the child has transparent areas/colors

Problems:

* using an invisible container isn't great yet as it still has backbuffer ghosting (still less ugly than with blending removed though)
* as said, alpha 0 for parent transparency does not work, as I couldn't get that without it restore pixels where it isn't intended
* labels don't really work with this, font rendering and/or SDF screw it up with blending modes (though it's not entirely a problem as it can have a typewriter aesthetic)
* blend modes still.

Maybe someone else can be improve it even more? Especially as I don't *entirely* understand how I did this.

**Comment by reduz** [comment]
Given there is no 100% agreement on how this should work, would clipping being an enum (as in, disable, behavior1, behavior2) make more sense?

If so, what would be the desired possible behaviors?

**Comment by clayjohn** [comment]
> Given there is no 100% agreement on how this should work, would clipping being an enum (as in, disable, behavior1, behavior2) make more sense?
> 
> If so, what would be the desired possible behaviors?

Sounds like there are two different behaviours that users would find useful:

**1. Clip children based on parent alpha (do not draw parent)**

194419118-72e2d721-72cd-4f7c-adcb-43bd9abfec97

**2. Clip children based on parent alpha (still draw parent)**

194429803-3e88468b-fb68-4c19-9020-a4ee69d57ab5

**Comment by insomniacUNDERSCORElemon** [comment]
@clayjohn have you looked at my code above? Here is a better demonstration of it:

clipping_enhanced_w_selfmodulate

I think it's an intuitive setup, though I could see if some shortcuts were added for usability (for instance if the shader/clipping could internally override a node to use multiply mode if it were needed, such as in this case with 0.0 selfmodulate). Also, does need some documentation (maybe even right in the clip_children tooltip).

The biggest problem is with multiply mode and textures. Users like @golddotasksquestions do not like the workflow of white textures and working directly w/alpha. Sort of like @reduz was saying: if you could add a clip variable `alpha_type` (normal, subtract, add, and mask\*) I imagine that'd make it easy (enough for me if I were there already) to add to my version of the shader. And that would improve the workflow.

\*=brightness directly sets alpha (white being full opacity), 0.0 alpha leaves alpha alone

**Comment by clayjohn** [comment]
@insomniacUNDERSCORElemon I did look at your code above. It sounds like a pretty neat suggestion. I suggest you make a proposal outlining exactly what you would like to see implemented including what options you would like exposed to the user. As it stands now, substantially changing the behaviour of clip_children is well beyond the scope of this PR and the discussion of your new features will get lost once this PR is finalized and merged.

**Comment by insomniacUNDERSCORElemon** [comment]
@clayjohn at the very minimum you could use the shader I've written, as AFAICT it's just better than not having it. If you agree, I encourage you to add it to this PR.

The changes I've discussed I feel are a natural extension of `clip_children`, it's the same idea except you're removing pixels instead of adding them. Especially as I've said before, even the my version of the shader now works shockingly smoothly when it comes to render order. I am not sure what else there is to be said, especially if workflow can be made intuitive.

Again, if I am given me a setup for the combobox of options (even if it's just `a` and `b` if easy to change) with an example of how to reference it in the shader, I will try to make the improvements. (and I could make my own PR if you've already merged this one)

**Comment by Zireael07** [comment]
@insomniacUNDERSCORElemon This PR is already large enough without adding a new shader. The bigger a PR, the longer it takes to be merged. Improvements should be made in follow-up PRs generally speaking

**Comment by insomniacUNDERSCORElemon** [comment]
> Like in your proposed example above. It's like cutting a whole _with_ empty space. Like shielding off sunlight with the open space of a window,

What is wrong with that? You're creating the hole exactly as you want it to appear. It multiplies the alpha and leaves the RGB alone. 

I was assuming that you didn't like working directly with alpha as it's harder to work with (like 25% alpha is harder to see than 25% gray, so you need to add a dark layer behind it). Disliking the workflow makes more sense than disliking how multiplication works.

That's totally irrelevant though as I brought that up in context of *me* wanting to add other methods (similar to what I've already done, if someone can get me started) to make it more intuitive, including the masking that you want (also subtract/add will allow using *normal* sprites of any color rather than needing specifically-made-mask).

**Comment by golddotasksquestions** [comment]
> Are we happy with these two modes?

Imho this now seem to do what it was originally advertised for, and more. I'd be totally happy to finally being able to use this in the upcoming beta builds.

> Are we okay breaking compatibility? 

Functionality wise, noting is broken. It still works with White-to-transparent textures. Yes, maybe scripts need to be adjusted due to it being an enum, but that's a small price to pay for finally have this feature fully working. Due to it's state, I doubt it was used by many people for any production purpose so far.

**Comment by insomniacUNDERSCORElemon** [comment]
The new commit does not fix the issue: `clip_only` has ghosting in un-covered areas, as you are not properly handling the transparency. And changing the parent to multiply mode no longer works (and multiply-blend children render transparent as black still)

I am also not convinced 2 shaders are needed here, as aside from the initial condition (parent visibility) the workflow should be exactly the same. My shader could be used for *both* modes (because it *does*, the `clip_only` setup just needs to be done manually), assuming clipping is properly configured to allow transparency.

**Comment by clayjohn** [comment]
> The new commit does not fix the issue: `clip_only` has ghosting in un-covered areas, as you are not properly handling the transparency. And changing the parent to multiply mode no longer works (and multiply-blend children render transparent as black still)

I'm not sure what you mean by uncovered areas, could you provide an example that highlights the issues you are describing?

> I am also not convinced 2 shaders are needed here, as aside from the initial condition (parent visibility) the workflow should be exactly the same. My shader could be used for _both_ modes (because it _does_, the `clip_only` setup just needs to be done manually), assuming clipping is properly configured to allow transparency.

2 shaders are needed to avoid forcing the multiply blend mode that the current implementation uses. The shader you have proposed requires users to be aware of the difference between texture alpha, modulate alpha, and color alpha and to utilize each of those in order to get the desired effect. In my opinion, that is way too complex, users should be able to get the appropriate clipping behaviour out of the box. At any rate, if you want more advanced behaviour, you can override the default shader by supplying your own shader. So you can really achieve anything you want with this implementation.

**Comment by insomniacUNDERSCORElemon** [comment]
> I'm not sure what you mean by uncovered areas, could you provide an example that highlights the issues you are describing?

Compare to my [previous screenshot](https://user-images.githubusercontent.com/4397725/195219710-e785e80b-9251-4fd1-b11a-be6e02ea5277.png), this is after adjusting to your commit:

ghosting_nomultiply

Ghosting is on the top-right example (text is not updated, I did remove the material from this example).

> 2 shaders are needed to avoid forcing the multiply blend mode that the current implementation uses. 

Multiply is needed in both cases to handle transparency, and in either case does not cause a blending issue when it's doing so (because in that exact case RGB is not modified). Without multiply,  `clip_only` will immediately look wrong as shown above.

> The shader you have proposed requires users to be aware of <complexities>, users should be able to get the appropriate clipping behavior out of the box

Exactly as I implemented it, yes. But I am suggesting that the above situation is handled *automatically* outside of the shader (thanks to the enum) so the user does not need to do that.

**Comment by clayjohn** [comment]
@insomniacUNDERSCORElemon Again, I am not supportive of making this feature so complex that users have to carefully manage transparency and blend modes in order to get the basic functionality. This should be something that users can turn on have it just work.

Something I should have noted above, when you assign a custom material it replaces the ``default_canvas_group_material`` and you become responsible for blending the backbuffer yourself in the shader. It appears that in your images you have replaced the default shader with your own, so you aren't even testing the shader in this PR. If you post the text of your shader I can offer tips on how to handle blending to help you achieve what you are trying to do. But again, that is advanced usage of this feature, what we are concerned with right now is whether the basic behaviour is correct and will work for the typical use case. 

> Also: @clayjohn I would like to make a slightly different setup than yours and have the enum working (image below), is there an easy way that I can <reference it in the shader> or <use it in the code instead of CANVAS_GROUP_MODE>?

It needs to be a property of the CanvasItem as the renderer needs to change the order it renders objects in so that this works (children have to be rendered before their parent).

As for the additional modes you propose in your image, again, please make a proposal with a detailed explanation of what additional modes you want, how you expect them to work, and why you need them for your project. Considering new modes is way beyond the scope of this PR.

**Comment by insomniacUNDERSCORElemon** [comment]
> I am not supportive of making this feature so complex that users have to carefully manage transparency and blend modes in order to get the basic functionality. This should be something that users can turn on have it just work.

I am not sure why you keep saying this when I am trying to make it clear that it should be handled by the engine. 

If I could figure out how to fix the backbuffer ghosting issue automatically the basic functionality of what my first image shows would already be there. And yes, good enough for basic usage.

>  It appears that in your images you have replaced the default shader with your own, so you aren't even testing the shader in this PR.

The newer image was your 2nd commit of this PR. Ghosting can be easy to miss if you don't have enough other nodes to show up.

Redownloaded, recompiled, new project that had it just 2 nodes and clip only (plus a background to make it obvious):

ArcoLinux_2022-10-13_19-40-42

MRP: [ghost_mrp.zip](https://github.com/godotengine/godot/files/9781297/ghost_mrp.zip)

**Comment by clayjohn** [comment]
> Redownloaded, recompiled, new project that has just 2 nodes with clip only (plus a background to make it obvious):

Thanks for the MRP! I was able to reproduce your issue when running on the RenderingDevice renderer, but not in the OpenGL3 renderer. I tracked down the issue to an existing bug with our CopyEffects class and I have pushed a fix to this PR!

**Comment by insomniacUNDERSCORElemon** [comment]
> I tracked down the issue to an existing bug with our CopyEffects class and I have pushed a fix to this PR!

Thank you, this fixed my issues with this almost entirely!

Multiply is still broken, but can be fixed by in the clip shader, add after setting rgb:  `COLOR.a *= c.a;`

But that makes me ask again, is there actually a need for an opaque and transparent version of the shader? Is multiplying just the alpha not enough to work in both cases? Manually editing the shader I am not seeing a difference.

-------------------

Sidenote: I am still getting the pop-outs (or shaded black w/o fix above) w/clipping when zooming in the editor. Or has that not been pushed yet?

**Review by mhilbrunner — APPROVED** [review]
PR meeting: Approved, feature is nice, the 2 modes make sense and are useful, and breaking compat. a bit at this point is better than the uglier alternative.

Still needs a final review + approval by reduz.

**Review by reduz — APPROVED** [review]

**Comment by clayjohn** [comment]
Two approvals and reviewed in the PR review meeting, so I will go ahead and merge this.

**Pull request merged**
