### PR TITLE
Revert #41164, add subsystem build option.

### LINKED ISSUE #1341: Add a SCons option to control whether Godot is built as a console or GUI application on Windows
**Describe the project you are working on:**

The Godot editor :slightly_smiling_face: 

**Describe the problem or limitation you are having in your project:**

When compiling Godot for Windows with the `debug` or `release_debug` target, it's compiled as a *console* application (even though it spawns a window on top of that). This means it's able to print to standard output/error. This also allows redirecting its output to a file.

However, when compiling Godot for Windows with the `release` target, it's compiled as a GUI application. This makes it impossible to see its standard output or error since no console window is visible. Even when running the executable from a command prompt, nothing will be printed. This makes it effectively impossible to redirect its output to a file.

This is a Windows limitation. Running the program in WINE *may* be able to overcome this limitation, but running WINE on Windows is usually impractical and requires a fair amount of setup.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Add a `windows_build_mode=console|gui` SCons option that overrides the build mode regardless of the target used. (Feel free to suggest a better name for this option.)

This could help resolve https://github.com/godotengine/godot/issues/24701 while making https://github.com/godotengine/godot/issues/28922 significantly easier to troubleshoot.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This can probably be done with some well-placed `#ifdef`s in the Windows platform code.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

This needs to be decided at build-time, so no.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This needs to be decided at build-time, so this can't be changed by an add-on.

___

See also #1342.

### LINKED ISSUE #41307: The output of doctest is not visible when running tests on Windows
**Godot version:**
Tested on 87ae509905e6a4388588472b4edddb791aec56a4.
Likely related to #41164 (CC @bruvzg).

**OS/device including version:**
Windows 10.

**Issue description:**
When running tests with `--test` option, the output is hidden/not visible.

On VSCode integrated terminal, it's spawned via another terminal:

Annotation 2020-08-16 155201

If you switch to `Debug Console`, the output is printed there.

When running via plain `cmd`:

Annotation 2020-08-16 155645

So my question whether that's a bug or the tests themselves should be able to disable this behavior manually?

**Steps to reproduce:**
1. Compile the engine with `scons tests=yes`
2. Run tests with:
```
.\bin\godot.windows.tools.64.exe --test
```

### LINKED ISSUE #41328: Flickering editor window focus due to system console
**Godot version:**

a17fba3

**OS/device including version:**

Windows 10

**Issue description:**

When you open a project, the editor window will lose focus every second for a brief moment. A console window appears stealing the focus, but it disappears immediately and editor is focused again. It can be fixed after toggling System Console option twice, but after restarting it happens again.

### PR DESCRIPTION
**Pull request by bruvzg**
- Revert #41164 (console output redirection), seems like it's causing more issues.
- Add `windows_subsystem` build option (defaults to "gui", always set to "console" when tests are enabled.

Fixes: #41328 and fixes #41307

*Bugsquad edit: Also fixes https://github.com/godotengine/godot-proposals/issues/1341.*

### CODE REVIEW

**Review by Xrayez — APPROVED** [review]
I confirm this fixes #41307. 🙂

**Comment by akien-mga** [comment]
That's too bad, this was a great way to handle console output in a Unix-like way. Does this bring us back to not having any output when starting Godot template builds from a terminal on Windows? That's a big issue for debugging.

**Comment by bruvzg** [comment]
> Does this bring us back to not having any output when starting Godot template builds from a terminal on Windows?

> That's a big issue for debugging.

**Comment by akien-mga** [comment]
> > That's a big issue for debugging.
> 
> It's not, manual redirection still works with GUI app, (e.g `godot.exe | more`).

Well let's say it's a big issue for the majority of users who don't know they'll get different output when redirecting than they're getting on stdout ;) I didn't knowing directing to `more` would make a difference.

**Comment by akien-mga** [comment]
Thanks! But sad, I liked this solution 😿

**Pull request merged**
