### PR TITLE
Add --no-header to the project settings (based on: #79179)

### PR DESCRIPTION
**Pull request by ghost**
this pull request is based on : #79179 
it just adds the parameter to enable or disable --no-header in : application/run/quit_header

### CODE REVIEW

**Comment by AThousandShips** [comment]
What's the reason of this PR? It's mostly the same code as the other one, why not suggest these additions in that PR?

**Comment by kaissouDev** [comment]
You're right, I didn't think of that just now.

**Comment by AThousandShips** [comment]
Sorry this didn't end up working out, hope to see your contributions elsewhere!

**Comment by kaissouDev** [comment]
@AThousandShips I can't do a review in a file that hasn't been modified - example (Project_Settings.cpp)

**Comment by AThousandShips** [comment]
Review of what?

**Comment by kaissouDev** [comment]
the code review for pull request #79179

**Comment by AThousandShips** [comment]
I would suggest just adding your own code for the project settings and not building on top of any other PR, there's no code you depend on there

**Comment by AThousandShips** [comment]
> the code review for pull request #79179

Just add a normal comment

**Comment by kaissouDev** [comment]
ok I think I'll do that or else I'll wait for the pull request (#79179) to be merged

**Comment by kaissouDev** [comment]
in case I keep the branch in my fork

**Pull request closed without merging**
