### PR TITLE
Show instantiating or inherit message when using drag to instantiate in 2D

### PR DESCRIPTION
**Pull request by ryevdokimov**
Related to: #88774 and #87621

See bottom left corner of editor viewport. 

https://github.com/godotengine/godot/assets/105675984/7211deda-940a-436b-b934-247d4fcdff4a

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
Tested locally, it works as expected.

However, there's an issue: if you drag-and-drop onto an empty scene, a new inherited scene is created. This is intended engine behavior which only currently applies to the 2D editor. This operation doesn't care about the position you drag-and-dropped the scene in, so it shouldn't display the position and should display a message of this form instead:

> Creating inherited scene from: filename.tscn

**Comment by ryevdokimov** [comment]
Like this?

https://github.com/godotengine/godot/assets/105675984/199f33c6-d2d1-4e96-970c-0b7b3cfb43d1

I think it's better to use the full path, because you can have multiple scenes with the same name in different folders. Also, if you just drag and sprite into an empty scene that will just become the root.

**Comment by Calinou** [comment]
Looks great!

> I think it's better to use the full path, because you can have multiple scenes with the same name in different folders. Also, if you just drag a sprite into an empty scene that will become the root.

That makes sense :slightly_smiling_face:

**Review by Calinou — APPROVED** [review]

**Comment by ryevdokimov** [comment]
Code in video after feedback applied, and PR and commit renamed.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
