### PR TITLE
Rename Transform to Transform3D

### LINKED ISSUE #1814: Rename Transform to Transform3D for Godot 4.0
**Describe the project you are working on:** This applies to any 3D game in Godot 4.0+.

**Describe the problem or limitation you are having in your project:**

We currently have this situation in the master branch (which will eventually become Godot 4.0):

* `Node2D` has a `Transform2D`

* `Node3D` has a `Transform`

To me, this seems inconsistent.

When talking about transforms, there is some confusion caused by the word "Transform" being simultaneously:

* A data structure (https://docs.godotengine.org/en/latest/classes/class_transform.html).

* A property (in GDScript it's `transform` but in C# it's `Transform`, so we have both `Transform` and `Transform` in C#).

* An action ("to transform", "transforming", etc).

* A generic word for transformations (including Transform2D).

Also, there is an inconsistency with `RemoteTransform3D` being a remote `Transform` instead of a remote `Transform3D`.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

If we renamed `Transform` to `Transform3D`, then we would have this situation:

* `Node2D` has a `Transform2D`

* `Node3D` has a `Transform3D`

There would be less confusion when discussing transforms, because then "Transform" by itself has one fewer possible meaning, and if you say "Transform3D" then you know it has to be referring to the data structure `Transform3D`. The C# code wouldn't have the problem of `Transform` vs `Transform` anymore, and `RemoteTransform3D` would be a remote `Transform3D`.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This proposal can be implemented by renaming `Transform` to `Transform3D`.

Branch: https://github.com/aaronfranke/godot/tree/transform3d

PR: https://github.com/godotengine/godot/pull/38430 (gets conflicts often, very important to rebase right before merging)

Another name to consider brought up by @AndreaCatania is `Transform3` (and then making `Transform2D` be `Transform2`). However, I personally would prefer `Transform3D`. This is of course up for discussion.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

The enhancement will be used often, as Transform(3D) is used by every 3D project.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This can't be an add-on in the asset library, Transform(3D) is a core data structure.

### PR DESCRIPTION
**Pull request by aaronfranke**
Continuation of #37340 and #30736. Implements and closes https://github.com/godotengine/godot-proposals/issues/1814.

This gets conflicts on a daily basis, this must be rebased and tested right before merging.

This rename needs to be done to be consistent with the other 3D renames, especially `RemoteTransform3D`. In general it makes things more clear, and is consistent with `Node2D` having `Transform2D`. It also removes the confusion between `Transform` and `Transform` in C# (property vs struct). I might have missed something, but this PR seems to work great in my testing.

Side note: Should `Basis` be renamed to `Basis3D`, or should we leave that as `Basis`?

### CODE REVIEW

**Comment by akien-mga** [comment]
I suggest seeking approval from @reduz before doing all this work, if it's rejected that would be a lot of time wasted.

I asked about this on March 30 on #godotengine-devel: http://godot.eska.me/irc-logs/devel/2020-03-30.log
```
[18:24:55] <Akien> reduz: Should Transform become Transform3D, since we have Transform2D?
[18:36:16] <reduz> Akien: no. for math I would probably leave these as they are because they are the correct term, Transform2D is kind of the only exception
[18:36:48] <reduz> Akien: 2D games very rarely use transform2D also
[18:36:54] <reduz> Akien: but 3D games use Transform a lot
```

**Comment by aaronfranke** [comment]
I mentioned Transform3D in both #37340 and #30736, no objection was raised, and there are actual problems with inconsistency that this solves, such as `RemoteTransform3D` being a remote `Transform3D`, and the problem of `Transform` vs `Transform` in C#.

If we have Node2D and Transform2D, and Spatial is Node3D, then Transform should be Transform3D.

**Comment by Xrayez** [comment]
> 2D games very rarely use transform2D also

I personally use `Transform2D` on a daily basis. Especially for UI development with transform matrix being used to convert between the world and view coordinates.

> I asked about this on March 30

That was like a month ago, perhaps the opinion has changed? Especially given previous renamings such as godotengine/godot-proposals#639.

**Comment by AndreaCatania** [comment]
I see what reduz is saing though, and I agree with him; for maths things nor `Transform3D` nor `Transform2D` are good names.
At the same time I see the naming problem you are trying to solve.

Some "math" like names that come me in mind are:
- 3D: `Transform3`, 2D: `Transform2` _<- I prefer this because more immediate._
- 3D: `Matrix3x4`, 2D: `Matrix2x3`.

**Comment by aaronfranke** [comment]
I think Transform3D is better than Transform3. The latter would imply that the structure has 3 elements, while it actually has 12, so the "3D" indicates its intended usage in 3D. On the other hand, Vector3 has 3 elements, and can be used outside of 3D, so it doesn't need the "D" IMO.

The thing is, obviously the "math term" is "transform", but I don't see why that makes "Transform3D" a bad name. It's just a mathematical transform... in 3D. The same as how Transform2D is a "transform", but in 2D.

Actually, in math, the term "transform" can mean a variety of things, see [here](https://en.wikipedia.org/wiki/Transformation_(function)) and [here](https://en.wikipedia.org/wiki/List_of_transforms). In fact, the example given in the first link is a 2D transform. So I don't see why 3D transforms should be given special treatment such that they lack a "3D" suffix if all other 3D things have "3D".

**Comment by AndreaCatania** [comment]
You may want to use a `Transform2D` for calculations into a 3D game, where its final meaning is not to be meant in 2D but in 3D.
For this reason I don't particularly like the postfix `D` in the name.

**Comment by aaronfranke** [comment]
If Transform2D is used for calculations in a 3D game, those would still be 2D calculations. You can also [use Node3D for calculations and convert the final meaning to 2D](https://godotengine.org/asset-library/asset/583), but we still call it Node3D... because it's for 3D. Similarly, Transform2D is for 2D and Transform(3D) is for 3D.

**Review by madmiraal — APPROVED** [review]

**Comment by akien-mga** [comment]
We discussed this in a PR review meeting today, and finally reached consensus that this is a good change. `Transform` is used a lot more than `Transform2D` and thus the compat breakage is a bit annoying, but at the same time making the type consistent with other 2D/3D classes definitely makes things clearer (especially for users starting with 2D or going from 2D to 3D).

The properties themselves should stay `transform` of course, only the type name gets a suffix.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
