### PR TITLE
Prevent shader crash in the editor when passing invalid array index

### PR DESCRIPTION
**Pull request by Chaosus**
As @Calinou suggested, its better to have a check in the editor to prevent shader crashes. I used clamp instruction to achieve this result - its works perfectly

### CODE REVIEW

**Comment by Calinou** [comment]
Shouldn't we also print an error message in this case?

**Comment by Chaosus** [comment]
I dont think its possible - its not a static checking - its shader runtime where the output of expression is unpredictable

**Comment by akien-mga** [comment]
If it prevents a crash but does not tell the user that their shader code is modified behind the scene, that doesn't sound good IMO.

AFAIK there are many other ways to get things to crash when using wrong code in shaders, no? So I don't think a custom case should be done here where it will not fail but produce wrong results.

**Comment by Chaosus** [comment]
Okay )

**Pull request closed without merging**
