### PR TITLE
Update webp driver to 0.5.1

### PR DESCRIPTION
**Pull request by volzhs**
updates: #5248

### CODE REVIEW

**Comment by akien-mga** [comment]
There seems to be one new `.c` files that should probably be added in the `SCsub`: `A drivers/webp/dsp/dec_msa.c (172)`

**Comment by reduz** [comment]
Wait, webp has custom fixes to work in html5. Punto knows more about this

**Comment by akien-mga** [comment]
See the various successive patches made to `drivers/webp` for reference: https://github.com/godotengine/godot/commits/master/drivers/webp

**Comment by akien-mga** [comment]
@volzhs For the reference, is this the pristine/unmodified upstream code, or did you already do some changes to it to take into account own patches that we might have made? To clarify, the former is the best way, as we can then (if need be) apply our own changes in a new commit, and make it clear where we diverge from upstream.

**Comment by volzhs** [comment]
@akien-mga I made some changes according to drivers/webp history.
But not about the custom fix for html5 as @reduz mentioned.
Should I add some codes based on https://github.com/godotengine/godot/commit/83f2084cb82d1dc006e7a9c0f23ca66e03736c2b?

**Comment by reduz** [comment]
I am not sure, I think it was @punto- who added the fixes

**Comment by akien-mga** [comment]
@volzhs Would you mind splitting your PR into two commits then? The first one would be the unmodified upstream files, and the second commit would apply the changes we need (or think we need, we can also work later on reducing our diff with upstream like I did for GLEW) based on the history.

**Comment by volzhs** [comment]
@akien-mga OK. got it.

**Comment by volzhs** [comment]
This time, I added custom fix codes based on 83f2084cb82d1dc006e7a9c0f23ca66e03736c2b

**Comment by punto-** [comment]
Yeah, the commit is the correct one (maybe check for any later commits by me, in case I tested it and it didn't work :p ), it has to do with unaligned reads on emscripten, it doesn't support 3 byte alignment

**Comment by reduz** [comment]
Please test this with the html5 exporter,  will merge if it works

**Comment by akien-mga** [comment]
As the HTML5 exporter is a pain to build, I've started a custom build on our godot-builds repo for this PR: https://github.com/GodotBuilder/godot-builds/releases/tag/test_pr_webp_0.5.1 (binaries will show up there little by little, including the javascript ones)

**Comment by akien-mga** [comment]
Hm my test build failed, looks like patching a git submodule like this doesn't work :)

I'll merge and trigger a build then, and test from there. If anything is off with the html5 exporter, we'll ensure to fix it for 2.1.

**Comment by akien-mga** [comment]
Here are some binaries to test: https://github.com/GodotBuilder/godot-builds/tree/master_20160714

**Pull request merged**
