### PR TITLE
Fix .tscn not raising dependency error

### LINKED ISSUE #3426: "Fix Dependencies" dialog doesn't open for tscn scenes
When moving a dependency of a `tscn` scene file, then opening the scene, the only message is:

> **Alert!**
> Error loading scene.

For the same scene as a `scn` or `xscn` file, the "Fix Dependencies" dialog is opened instead.

### PR DESCRIPTION
**Pull request by ghost**
Closes #3426.

### CODE REVIEW

**Comment by reduz** [comment]
not sure what you were trying to do, but the lines you removed were useful

**Comment by reduz** [comment]
oh no sorry nevermind i read it backwards, it' s fine

**Comment by reduz** [comment]
no, wait.. I'll give it a better check later today

**Comment by TheHX** [comment]
After a better investigation, i think, i found the problem.

Because of this line:
https://github.com/godotengine/godot/blob/master/scene/resources/scene_format_text.cpp#L89
The load will fail and will trigger this:
https://github.com/godotengine/godot/blob/master/tools/editor/editor_node.cpp#L3457
Before calling the dependency dialog.

I submitted another fix, that check for broken dependencies before setting the scene as invalid.

**Comment by reduz** [comment]
if it works as reference, this is how the binary format handles it
https://github.com/godotengine/godot/blob/master/core/io/resource_format_binary.cpp#L672

**Comment by reduz** [comment]
i think your original fix was better, just make sure I guess it does the same as binary.
The resource loader should be able to load a scene with broken dependencies, in case you ask it to, so no need to change that

**Comment by TheHX** [comment]
@reduz, i changed because i noticed this:
https://github.com/godotengine/godot/blob/master/scene/resources/scene_format_text.cpp#L148

**Comment by reduz** [comment]
yeah that is the right way, if an error ocurs only abort if abort on
missing resources is set..  otherwise just report it

On Sun, Jan 24, 2016 at 6:52 PM, Franklin Sobrinho <notifications@github.com

**Comment by TheHX** [comment]
Those lines should be replaced by a warning, like in binary and xml format?
https://github.com/godotengine/godot/blob/master/scene/resources/scene_format_text.cpp#L88-L89

**Comment by reduz** [comment]
yes, i think so

On Sun, Jan 24, 2016 at 6:59 PM, Franklin Sobrinho <notifications@github.com

**Comment by TheHX** [comment]
Pushed the new fix.

**Pull request merged**
