### PR TITLE
Fixed underlines and strikethrough not respecting visible character

### LINKED ISSUE #21637: RichTextLabel  underlining does not respect visible character
**Godot version:** 3.1alpha 02490db

**Issue description:** BBcode underlines are always shown even if the character is hidden. For example, with visible_characters += 1 in step,
ezgif-5-d15294f8f4

### PR DESCRIPTION
**Pull request by Janglee123**
Fixes #21637

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by Anutrix** [comment]
Requesting removal of the cherrypick tag as this causes a regression bug(#37746).

**Comment by Janglee123** [comment]
This can be fixed by replacing `w` with `fw` in the loop and `ENSURE_WIDTH`.

**Comment by Anutrix** [comment]
@Janglee123 Do test it and make a PR. Thx.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Pull request merged**
