### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by Geequlim**
Fill about 80% translation.

Rest part may finished by others or another day :)

### CODE REVIEW

**Comment by Geequlim** [comment]
DO NOT MERGE NOW
--------------------------------

Something still unfinished.

**Comment by akien-mga** [comment]
Awesome :D We'll be able to test @reduz's new font :)

**Comment by akien-mga** [comment]
Should we still wait to merge? You're starting to get compe-tributors ;)

**Comment by Geequlim** [comment]
@akien-mga Yes. I'm checking for some errors in the translation now, just wait a minuter :)
And I'm glad to contact the guy for cooperations.

**Comment by reduz** [comment]
by the way, this is offtopic, but how do you manage IME on Godot? we haven't added any IME supports, but many users seem to be able to still use it in Chinese and Japanese, not sure how

**Comment by Geequlim** [comment]
@reduz We copy Chinese sentences into godot from other editors....

**Comment by Geequlim** [comment]
@akien-mga I think it's time to merge it :)

**Pull request merged**
