### PR TITLE
Fixed parents export vars not appearing in inspector if parent is class_name.

### LINKED ISSUE #21076: Script which inherits from a class defined by `class_name` keyword does not feature the parent's attributes in the inspector
**Godot version:**

image

**Related PR**
https://github.com/godotengine/godot/pull/20233

**Steps to reproduce:**
1. Create a gdscript with global scope, using the the `class_name` keyword
2. Declare a an `export(..) var` inside the gdscript
3. Inherit from the declared class from anohter gdscript.
4. Attach the gdscript to a node in the inspector.
5. Notice the the parent node's export attributes are not featured in the inspector. (I tried restarting godot too)

### PR DESCRIPTION
**Pull request by Piet-G**
Fixed parents export vars not appearing in inspector if parent is class_name.

Fixes #21076

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @vnen

**Comment by xDGameStudios** [comment]
@akien-mga @vnen will this get merged anytime soon?!
Just wanted to know so I can set the direction on how will have to organize code inside my project can I or can't I rely on class_name for now!?

**Comment by akien-mga** [comment]
Well I wanted it reviewed, but I guess it's fine to merge if it works.

You don't need to double all your punctuation though :)

**Comment by xDGameStudios** [comment]
Thank you for the merge! :) 

Sorry for the punctuation.. part of me was admired and part of me was questioned xD

**Comment by JeffPack** [comment]
Any idea when this fix will make it to the stable version? I'm running 3.0.6

**Comment by akien-mga** [comment]
This fix doesn't make sense in the current stable version, it does not include the `class_name` feature.

**Comment by DOGEIGHT** [comment]
I'm using 3.1 beta and having same issue.

**Comment by MayQuo** [comment]
still not working stable 3.3

**Pull request merged**
