### PR TITLE
[3.x] Expose the `TextEdit` control of the script editor

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
Refactor ScriptEditor and ScriptTextEditor with added method to retrieve the script editor's TextEdit control.

Update
script_editor_plugin.cpp
script_editor_plugin.h
script_text_editor.cpp
script_text_editor.h

_Bugsquad edit:_ This PR is a 3.x version of 4.x's `get_base_editor()`.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
The new function needs to be documented, run the editor in the root directory with `--doctool`.

**Review by YeldhamDev — APPROVED** [review]

**Comment by akien-mga** [comment]
> _Bugsquad edit:_ This PR is a 3.x version of 4.x's `get_base_editor()`.

I see the 4.x version returns `Control`, do you know why there's this difference?

**Comment by jeronimo-schreyer** [comment]
> > _Bugsquad edit:_ This PR is a 3.x version of 4.x's `get_base_editor()`.
> 
> I see the 4.x version returns `Control`, do you know why there's this difference?

I can change that to keep coherence

**Comment by akien-mga** [comment]
Well TextEdit is better if that's accurate. I just wonder why in 4.x it's only Control.

**Comment by jeronimo-schreyer** [comment]
Well, from what I can tell, version 4 has ScriptEditor.get_current_editor() which is a ScriptEditorBase (CodeTextEditor actually). I can't see the documentation for that class in version 3, so I assume its not exposed. But they look that they're more or less the same class. So I returned TextEdit

**Comment by Paulb23** [comment]
> I just wonder why in 4.x it's only Control.

IIRC It was to return the `GraphEdit` for visual scripting, which also extends `ScriptEditorBase`. 

I expect there may be other types when it's opened up more for plugins, considering we also changed to `CodeEdit` rather then `TextEdit`.

**Comment by jeronimo-schreyer** [comment]
so, I should expose ScriptEditorBase instead?

**Comment by akien-mga** [comment]
Bump :) And you might be able to expose the VisualScript editor too using the same method.

**Comment by jeronimo-schreyer** [comment]
I synced this branch with master by mistake. Closing and opening a new PR. Sorry

**Pull request closed without merging**
