### PR TITLE
[macOS] Bump min. version to 10.15, and remove deprecated code.

### LINKED ISSUE #124: macOS 13.0 SDK does not support 10.12 as a deployment target
It seems that the [latest macOS build containers use the macOS `13.0` SDK](https://github.com/godotengine/build-containers/blob/06cc72f615af8aa042797bdc35ef859c8f19e2cb/Dockerfile.osx#L10). However, according to [Xcode support](https://developer.apple.com/support/xcode), the `13.0` SDK does not support setting the deployment target to `10.12` (`10.13` is the minimum).

The latest Godot version [hard-codes the macOS deployment target to `10.12`](https://github.com/godotengine/godot/blob/24cb43a8741c7b10abbbbc77bb6e2bc188662ce0/platform/macos/detect.py#L117-L124), which seems to be unsupported.

Can the macOS build container be "downgraded" to use an older SDK, `12.3`, which is the latest version that supports `10.12` deployment targets? Alternatively, can Godot drop support for `10.12`?

I'm not sure whether this is actually a problem in practice, as I don't have any real experience building macOS/iOS applications. I'm happy to open a PR to help, but I'm wondering what the preferred solution, if any, would be.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/build-containers/issues/124

Alternative to #76394.

### CODE REVIEW

**Comment by akien-mga** [comment]
I don't know how trustworthy those market usage stats are (they seem to have a problem tracking macOS versions since the bump to 11): https://gs.statcounter.com/macos-version-market-share/desktop/worldwide/#monthly-202203-202303-bar

image

But they show that dropping support for macOS 10.13 and 10.14 would cut off 8% of the market, which might be a bit too big if we don't have a strong technical requirement to drop support for them.

Valve has just dropped support for macOS 10.11 and 10.12, so I think it makes sense for us to also keep 10.13 as our minimal supported version: https://help.steampowered.com/en/faqs/view/0972-74BD-D8DE-662E

I tried using the Steam Hardware Survey to get a feel for what percentage of users still use < 10.15, but it has too much granularity in the 10.x.y patch releases so the useful data is all lumped together in a huge 40% "Other" category. https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=mac

**Comment by bruvzg** [comment]
Some people might keep 10.13 or 10.14 since 10.15+ dropped support for 32-bit software (including 32-bit Windows apps via Wine).

**Comment by akien-mga** [comment]
That, plus I think a lot of people have older Macs they still want to use, but for which Apple doesn't provide an upgrade path to 10.15, right? So they're effectively stuck on EOL versions, or need to throw out the hardware.

**Comment by bruvzg** [comment]
> Apple doesn't provide an upgrade path to 10.15, right?

I think they only drop support for 2010 Mac Pro in 10.15, the rest of hardware requirements should be the same as 10.14. But in case 10.13 to 10.14, yes, a lot of old (2009-2010) macs were dropper.

**Pull request closed without merging**
