### PR TITLE
Add unit tests for Shortcut

### PR DESCRIPTION
**Pull request by rocketman1243**
This PR adds unit tests for the Shortcut module.
I added tests for all the main functions and tried to test both happy paths and failure paths.
All the tests run fine and should give no problems.

This PR is part of #43440.

If you have any suggestions or remarks, please let me know!

### CODE REVIEW

**Comment by UltraTimon** [comment]
I fixed the formatting with `clang-format`, and now the pipeline should succeed!

**Comment by UltraTimon** [comment]
The include statements are now ordered alphabetically as well, so we should be good to go! (fingers crossed)

**Review by akien-mga — APPROVED** [review]
Apologies for the late review.

I force pushed an update to fix style issues (wrong name for test, usage of camelCase or PascalCase instead of snake_case). Should be good to merge now if it passes CI.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
