### PR TITLE
[DOCS] Added Documentation of the rest of the AudioStream files

### PR DESCRIPTION
**Pull request by Grosskopf**
my previous PR somehow got closed :/ now another try with new and better changes, this was the old one https://github.com/godotengine/godot/pull/11337

### CODE REVIEW

**Comment by Grosskopf** [comment]
by the way, manipulated the wording a bit so it doesn't give conflicts anymore

**Comment by akien-mga** [comment]
Please squash the two commits together: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase

**Comment by Grosskopf** [comment]
i have absolutely no idea what i'm doing :/

**Comment by Grosskopf** [comment]
yay :) thanks @Noshyaar :)

**Pull request merged**
