### PR TITLE
Fix Geometry3D::get_closest_points_between_segments() returns NaN

### LINKED ISSUE #55384: Geometry::get_closest_points_between_segments() returns `NaN` when segments are parallel or either is a point
### Godot version

3.4

### System information

Windows 10 64 bits GLES3 GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

`Geometry.get_closest_points_between_segments` has undocumented/unexpected behavior in some cases.

```
     A------B
C---------------D
```

- If the two segments are parallel and "facing" each other, it returns 2 NaN vectors. A return different than two valid points is probably expected because this case has a potentially infinite set of solutions. We could pick any and make the function return them otherwise, not sure if that covers a use. The use case of finding closest *distance* is a known use case though.

```
     A------B
                             C---------------D
```

- If the two segments are parallel but not "facing" each other, it returns 2 NaN vectors. But this is incorrect: there is one solution in this case, which is the closest pair of segment endpoints.

- When the first segment is a point, it returns 2 NaN vectors. We could consider this is incorrect because there is a solution to this, which is to fallback to `get_closest_point_to_segment`. If we don't consider this correct behavior, then it needs to be documented.

- When the second segment is a point, the same happens.

- When both segments are points, it returns 2 NaN vectors. We could consider this is incorrect because the result is obviously the two points. If we don't consider this correct behavior, then it needs to be documented.

In every case, checking for NaN is a bit counter-intuitive. Also, it is not documented.

As a result, I ended up re-implementing a more "convenient" version for my own needs, in which the function returns `null` only in the case where there are infinite solutions (haven't figured something proper for the parallel non-facing case tho):
```gdscript
static func closest_segment_points(p1: Vector3, p2: Vector3, p3: Vector3, p4: Vector3):
	# Started from http://paulbourke.net/geometry/pointlineplane/lineline.c
	# Ported and refined to include parallel and point cases
	
	var p21 := p2 - p1
	if abs(p21.x) < EPSILON && abs(p21.y) < EPSILON && abs(p21.z) < EPSILON:
		# First segment is a point
		return [p1, closest_point_on_segment(p1, p3, p4)]

	var p43 := p4 - p3
	if abs(p43.x) < EPSILON && abs(p43.y) < EPSILON && abs(p43.z) < EPSILON:
		# Second segment is a point
		return [p3, closest_point_on_segment(p3, p1, p2)]

	var p13 := p1 - p3
	
	var d1343 := p13.dot(p43)
	var d4321 := p43.dot(p21)
	var d1321 := p13.dot(p21)
	var d4343 := p43.length_squared()
	var d2121 := p21.length_squared()

	var denom := d2121 * d4343 - d4321 * d4321
	if abs(denom) < EPSILON:
		# Segments are parallel. There are infinite solutions.
		# TODO Unless the two segments are not "facing" each other within the plane they describe.
		# TODO If we only want to know the closest distance, this is non-ambiguous.
		return null
		
	var numer := d1343 * d4321 - d1321 * d4343

	var mua := clamp(numer / denom, 0.0, 1.0)
	var mub := clamp((d1343 + d4321 * mua) / d4343, 0.0, 1.0)
	
	var pa := p1 + mua * p21
	var pb := p3 + mub * p43

	return [pa, pb]
```

To figure out the parallel-non-facing case, I included it in a fallback to the case where they are parallel. I'm still experimenting with this so this is certainly optimizable, I found that the code presented in https://wickedengine.net/2020/04/26/capsule-collision-detection/ was able to deal with these cases (Capsule-Capsule section):

```gdscript
		var v0 := p3 - p1
		var v1 := p4 - p1
		var v2 := p3 - p2
		var v3 := p4 - p2

		var d0 := v0.length_squared()
		var d1 := v1.length_squared()
		var d2 := v2.length_squared()
		var d3 := v3.length_squared()
		
		var best1
		if d1 < 0 or d2 < d1 or d3 < d0 or d3 < d1:
			best1 = p2
		else:
			best1 = p1

		# These are our two hits
		var best2 = closest_point_on_segment(best1, p3, p4)
		best1 = closest_point_on_segment(best2, p1, p2)
```

### Steps to reproduce

[ClosestPointBetweenSegments2.zip](https://github.com/godotengine/godot/files/7611996/ClosestPointBetweenSegments2.zip)

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by madmiraal**
As pointed out by @Zylann in #55384, currently, the `Geometry3D::get_closest_points_between_segments()` algorithm fails when the segments are parallel or a point. Furthermore, when I tried to use the `Geometry3D::get_closest_distance_between_segments()` algorithm, which is more robust, I found it returns incorrect results and even the current test is testing for an incorrect value!
https://github.com/godotengine/godot/blob/4f298237bf887c8540eadd47672158c04e2300dd/tests/core/math/test_geometry_3d.h#L57-L72
P0 = <1, -2, 0>
P1 = <1, 2, 0>
Q0 = <-1, 2, 0>
Q1 = <-1, -2, 0>
The test points are in the plane z=0; so it can be visualised in 2D. Segment P is a vertical line with x=0, and segment Q is a vertical line with x = -1:
```
  Q0     │     P1
   o     │     o
   │     │     |
   │     |     |
─────────┼─────────
   │     │     |
   │     |     |
   o     │     o
  Q1     │     P0
```
The shortest distance is clearly 2.0 not 0.0!

This PR fixes the test and replaces the `Geometry3D::get_closest_points_between_segments()` and the `Geometry3D::get_closest_distance_between_segments()` with a version of David Eberly's Computation of Distance Between Line Segements algorithm: https://www.geometrictools.com/Documentation/DistanceLine3Line3.pdf.

Tested with an updated 4.0 version of @Zylann's MRP that tests both 2D (which works unchanged) and 3D, and checks for more corner cases: [55384-4.0.zip](https://github.com/godotengine/godot/files/7653464/55384-4.0.zip)

Fixes #55384

### CODE REVIEW

**Comment by kleonc** [comment]
> This PR fixes the test and replaces the `Geometry3D::get_closest_points_between_segments()` and the `Geometry3D::get_closest_distance_between_segments()` with a version of David Eberly's Computation of Distance Between Line Segements algorithm: https://www.geometrictools.com/Documentation/DistanceLine3Line3.pdf.

@madmiraal Any reasoning why you went for the non-robust approach from that paper over the robust one? Is it cheaper performance-wise or something like that? (I haven't read these.)
Also shouldn't [the license linked at the beginning of that file](https://www.geometrictools.com/GTE/Mathematics/DistSegmentSegment.h) be included somewhere in here? Or is [the current mention in the comment](https://github.com/godotengine/godot/blob/d7b21b53944efe5597250e2036053c4fecdd71ee/core/math/geometry_3d.cpp#L39) enough?

And do you have any opinion on this PR vs approach taken in #64224?

**Comment by madmiraal** [comment]
> @madmiraal Any reasoning why you went for the non-robust approach from that paper over the robust one? Is it cheaper performance-wise or something like that? (I haven't read these thoroughly.)

The robust approach attempts to provide a solution even when the determinant is close to zero. The non-robust approach simply assumes the lines are parallel and selects an arbitrary point in the overlapping section.

> Also shouldn't [the license linked at the beginning of that file](https://www.geometrictools.com/GTE/Mathematics/DistSegmentSegment.h) be included somewhere in here? Or is [the current mention in the comment](https://github.com/godotengine/godot/blob/d7b21b53944efe5597250e2036053c4fecdd71ee/core/math/geometry_3d.cpp#L39) enough?

The Creative Commons license is for the document itself, which we've not copied. Furthermore, as stated in the document, the algorithm I've used is based on a previous version i.e. not the author's new robust version. Nevertheless, I've attributed the author in the comment, which I believe is sufficient.

> And do you have any opinion on this PR vs approach taken in https://github.com/godotengine/godot/pull/64224?

The changes in #64224 are difficult to review, but the author suggests it's basically the same as this one, which makes it a duplicate.

**Review by kleonc — APPROVED** [review]
I've read the paper, checked the code against it and all looks good.

@madmiraal Needs a rebase though. I guess you could also add some more test cases from #64224 in here too.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
