### PR TITLE
Added Curve resource

### PR DESCRIPTION
**Pull request by Zylann**
- New resource for curves in y(x) form
- CurveTexture now has a Curve
- Curve and CurveTexture share the same editor

For #7296, can also be used for #8504, or more wherever curves are a thing

### CODE REVIEW

**Comment by Zylann** [comment]
I'm trying to continue on this by re-using the same editor for CurveTexture, however that resource also plots its own points both in the editor and in the resource with `set_points()`. 
If I were to re-use the Curve algorithm completely, it would make even more sense to have `CurveTexture` reference a `Curve`. But if @reduz prefers it to work without that step, I'll have to do more than just have a backing `Curve` resource in `CurveTextureEditorPlugin`, and also extract the algorithm so that it is consistently used in the `CurveTexture` resource...

**Comment by reduz** [comment]
Wait, need to change how curve works first...

**Comment by Zylann** [comment]
`Curve` or `CurveTexture`?

**Comment by Zylann** [comment]
Updated the PR: now CurveTexture shares the same editor as Curve.

**Comment by axelorca** [comment]
Why do Curves not allow for weighted tangents? It's weird that it's implemented in Bezier Animation Tracks but not in the normal Curve construct...

**Comment by Zireael07** [comment]
@axelorca  please open a proposal instead of commenting on a long ago closed PR

**Pull request merged**
