### PR TITLE
Add method bind for `Geometry2D.decompose_polygon_in_convex`

### LINKED ISSUE #2668: Expose `Geometry2D::decompose_polygon_in_convex()` to GDScript
### Describe the project you are working on
A game using polygons as terrain, where I custom draw borders on the polygons (similar to Unity SpriteShape).

### Describe the problem or limitation you are having in your project
In order to render these borders on the polygons I need some triangulation of the border shape. Unfortunately regular triangulation does not give a satisfactory result, I need some kind of "nice" triangulation. Delaunay looks much better, but my shapes are concave and delaunay triangulates the convex hull. So my idea is to first convex decompose my concave shape, and then delaunay triangulate each convex shape and combine the results. Actually, just getting the convex shapes themselves might be enough to work with. But convex decomposition isn't available from GDScript. I could try to implement the algorithm myself, but I think this would be a very slow thing to run fully in GDScript.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Expose Geometry2D::decompose_polygon_in_convex() to GDScript, so I can simply call the function and have it run fast. 

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
Self explanatory.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not a few lines of script, the convex decomposition is rather complex, and besides it would run slow in GDScript.

### Is there a reason why this should be core and not an add-on in the asset library?
It's already a core function, so might as well just expose it, especially considering there are already a lot of similar geometry functions available.

### PR DESCRIPTION
**Pull request by 4d49**
This adds a small function wrapper for an already existing function. 

*Bugsquad edit:*
- Fixes https://github.com/godotengine/godot-proposals/issues/2668

### CODE REVIEW

**Comment by akien-mga** [comment]
You also need to update and write the documentation for the exposed method: https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html

**Comment by 4d49** [comment]
> You also need to update and write the documentation for the exposed method: https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html

Done.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by 4d49** [comment]
> Thanks! And congrats for your first merged Godot contribution

Thank you, glad to help the community!

**Pull request merged**
