### PR TITLE
Sync minizip with closest upstream version (zlib 1.2.4 contrib) and document Godot-specific changes

### PR DESCRIPTION
**Pull request by akien-mga**
Next step is to update to the contrib/minizip from zlib 1.2.11, but I want to make sure the synced 1.2.4 version works fine on all platforms before that.

### CODE REVIEW

**Comment by AandersonL** [comment]
i`m having a problem to compile in my Gentoo.
Initial build] Compiling ==> main/main.cpp In file included from ./thirdparty/minizip/unzip.h:55:0, from ./core/io/file_access_zip.h:38, from main/main.cpp:68: ./thirdparty/minizip/ioapi.h:127:51: error: expected initializer before 'OF' typedef voidpf (ZCALLBACK open_file_func) OF((voidpf opaque, const char filename, int mode)); .....

Complet log: https://ghostbin.com/paste/2kh96

I also tried "minizip=no" but still don't work.
Thanks

**Comment by Zatsuwar** [comment]
I`m getting errors to compile in my Gentoo,  this fallowing errors:

[Initial build] Compiling ==> main/main.cpp In file included from ./thirdparty/minizip/unzip.h:55:0, from ./core/io/file_access_zip.h:38, from main/main.cpp:68: ./thirdparty/minizip/ioapi.h:127:51: error: expected initializer before 'OF' typedef voidpf (ZCALLBACK open_file_func) OF((voidpf opaque, const char filename, int mode)); .....

Complete log: https://ghostbin.com/paste/2kh96

I also tried "minizip=no" but still don't work.

**Compilers and version:** 
GCC - gcc (Gentoo 4.9.4 p1.0, pie-0.6.4) 4.9.4
Clan - clang version 3.9.1

Both clang and gcc give-me error.

**I am running:**
```
scons platform=x11  
```
and
```
scons platform=x11 bits=64 tools=no target=release_debug -j 9 use_llvm=yes
```

**Comment by akien-mga** [comment]
Please open a new issue for this, to debug and fix it it's best to have a proper issue and not a merged PR.

**Comment by akien-mga** [comment]
Opened it for you: #10539

**Pull request merged**
