### PR TITLE
Cool new functions for camera: fade,flash,shake

### PR DESCRIPTION
**Pull request by ghost**
usage : 

a color for your fade,a position for fade,how fast the fade should apply
fade(Color(255,255,255),Vector2(-200,-150),.3)

a color for your flash,a position for flash,how fast the flash should apply
flash(Color(255,255,255),Vector2(-200,-150),.3)

### CODE REVIEW

**Comment by TheoXD** [comment]
Yes they're cool, but I personally think this should be done by script, at the same time keeping API more generic.

**Comment by adolson** [comment]
I'm all for this. A few generic effects built-in will only make things easier, and they're very unobtrusive. People can still script whatever they want, if the built-ins aren't good enough.

**Comment by akien-mga** [comment]
It looks like @Murii deleted his Godot fork, so there is no chance to see this PR rebased against the current master branch.

If there is still interest in adding those functions, feel free to open a new PR; if you do it based on the above commit, please try to improve the coding style to match the rest of the codebase, currently there is no real visible convention, many parameters are misspelled, etc..

**Comment by akien-mga** [comment]
And actually the above change was probably broken as the header is not updated (it is then partly done in #1103, but that wouldn't compile either).

**Comment by Murii** [comment]
@akien-mga  Back then I wasn't such a good C/C++ coder so that's why I did not respect Godot's style. Anyway I don't have any more the repository so I can't help.

**Pull request closed without merging**
