### PR TITLE
Fix inspector preview

### LINKED ISSUE #18983: New property inspector:  Scripts don't show filename
**Godot version:**
ba134d4

**Issue description:**
This is more of a personal nitpick.  While I find the script thumb preview *marginally* useful, seeing a filename at a glance would be much more useful, or in a tooltip if must be.  I'm assuming this is simply a feature in testing (for supporting property field previews which weren't feasible before?), but nevertheless it seems to be an issue.

### LINKED ISSUE #22721: Inspector doesn't show resource previews
**Godot version:**
 8068d02

**Issue description:**
It has been like that for a little while now:
screenshot at 2018-10-04 13-14-17

### PR DESCRIPTION
**Pull request by guilhermefelipecgs**
Fix #22721. Fix #18983.

### CODE REVIEW

**Comment by guilhermefelipecgs** [comment]
PR updated to also fix #18983.

**Comment by akien-mga** [comment]
This should also be fixed in:
```
modules/visual_script/visual_script_editor.cpp
1943:void VisualScriptEditor::_button_resource_previewed(const String &p_path, const Ref<Texture> &p_preview, Variant p_ud) {

modules/visual_script/visual_script_editor.h
240:    void _button_resource_previewed(const String &p_path, const Ref<Texture> &p_preview, Variant p_ud);
```

Those are regressions from b2633a97b9 (ping @groud).

There's also this bug caused by the same commit: https://github.com/godotengine/godot/pull/22618/commits/c026e3957a815199ee301cdcbaa94698ee4a3705#r221904359

We should be more careful when adding new parameters to virtual methods used all over the engine. In this case, I'm not sure if the `p_small_preview` addition is good, couldn't it use its own method? It looks like it's only used in https://github.com/godotengine/godot/commit/b2633a97b9efa7b926d6682342480c5ccb482369#diff-437a2597f8c2e9b25f7b975bbfd73b2eR515, so it seems overkill to allocate two textures in all those calls when none of them need both in parallel.

**Comment by guilhermefelipecgs** [comment]
> This should also be fixed in:

PR updated.

> I'm not sure if the `p_small_preview` addition is good, couldn't it use its own method?

I don't saw a simple way of doing that then if anyone knows how to do it help will be welcome.

**Comment by groud** [comment]
> We should be more careful when adding new parameters to virtual methods used all over the engine.

I agree, sorry. ^^

> so it seems overkill to allocate two textures in all those calls when none of them need both in parallel.

It's only allocated once, that's the point of References, so we only a reference to the texture. Also, their generation is cached and they are only generated for textures and materials. 

> In this case, I'm not sure if the p_small_preview addition is good, couldn't it use its own method?

The thing is that both thumbnails are generated at the same time, so it made sense to send both version at the same time. Also, the function to ask for a thumbnail generation requires giving
a callback function. Splitting it would have needed to add another callback function argument.
I went for the approach that looked the simplest to me.

**Comment by akien-mga** [comment]
Alright, this should be good to go then :)

**Pull request merged**
