### PR TITLE
Allow exporting of 64 bit version without needing 32 bit template installed

### PR DESCRIPTION
**Pull request by firefly2442**
Fixes: #1404

### CODE REVIEW

**Comment by LeonardMeagher2** [comment]
+1

**Comment by firefly2442** [comment]
Also related is PR #2292

**Comment by firefly2442** [comment]
As was pointed out on IRC, this does not fix the issue of having only the debug template or only the release template setup for export.  I'm not sure if further down the line in the export process, godot is assuming that both debug and release are setup and working properly.

**Comment by akien-mga** [comment]
This works fine and I definitely want it implemented for 2.0 :)

Some remarks though:
* The first check that gives "No 32 or 64 bit export templates found." seems redundant with the other two. Is there a use case where it would effectively be displayed?
* The error message and export button active/inactive status are not refreshed when ticking/unticking the 64bit, e.g.:
** I have Linux 64 templates, no Linux 32
** I open the export popup with 64bit unticked, it will rightfully complain about missing 32bit templates
** I tick 64bit, it still complains about 32bit templates and the export button is still greyed out
** I need to click on another platform and then back on Linux X11 so that the error message disappears and the export button gets activated.

**Comment by akien-mga** [comment]
As stated above, PR #2292 also addresses the same issue and IMO in a more thorough way. It also takes into account the two bullet points I wrote above.

@firefly2442 Would you agree that we close this PR to the profit of PR #2292?

**Comment by firefly2442** [comment]
Sure, that one looks better.

**Pull request closed without merging**
