### PR TITLE
Visual shader ports are expandable by default for vector types

### PR DESCRIPTION
**Pull request by QbieShay**
Addresses https://github.com/godotengine/godot-proposals/discussions/6182#discussioncomment-4805308

### CODE REVIEW

**Comment by paddy-exe** [comment]
Works as expected: 
image

**Comment by Norrox** [comment]
Are we sure we want red green blue? we take in x y z? they are the same sure, but why not name them r(x) g(y) b(z) or red(x) green(y), something like that? :)

**Comment by QbieShay** [comment]
I think that could be done in a future PR

**Review by fire — DISMISSED** [review]
People tested the changes and the code is decent

**Review by Geometror — COMMENTED** [review]
Looks good, however these expand buttons (which are toggleable, but do nothing) shouldn't be there, should they?
grafik
The ColorConstant node on the right does not have them.

Edit: Also I just noticed in @paddy-exe's screenshot that there seems to be some weird thing happening with the component ports of Vector3Parameter (also reproducible with Vector2/4Parameter):
grafik

**Comment by QbieShay** [comment]
that's really strange, it shouldnt show for them

**Review by Chaosus — DISMISSED** [review]

**Comment by Chaosus** [comment]
Ah, as far as I remember I did not make this change in original PR, cuz I did not manage it to work correctly with nodes with multiple vector ports.

**Comment by YuriSizov** [comment]
So despite the two approvals, this still needs some work, correct?

**Comment by QbieShay** [comment]
Yeah i haven't gotten back to this yet. Anybody that wants to pick up this work is welcome, i won't have time for a bit.

**Comment by DennisManaa** [comment]
Hey there, I'd like to pick up this PR, if still possible :)

**Comment by QbieShay** [comment]
Sure go ahead! I haven't had the energy to continue on this so that'd be very welcome :+1:

**Comment by DennisManaa** [comment]
Hey again, just would like to mention the new PR, where I finished the work on this issue :)

#82088

**Comment by QbieShay** [comment]
Superseded by https://github.com/godotengine/godot/pull/82088

**Pull request closed without merging**
