### PR TITLE
Provide compatibility api functions for `Object::connect` and `Object::disconnect`

### PR DESCRIPTION
**Pull request by tasgon**
Many modules heavily rely on the API of the `connect` and `disconnect` functions as they were in Godot 3, so I think adding compatibility functions for these is worth the effort in maintaining (which I would be willing to put in if you'd like).

### CODE REVIEW

**Comment by tasgon** [comment]
Sorry, just noticed my commit message was broken, let me fix that.

**Comment by Calinou** [comment]
I think it's better to provide only one way to do things. If you need to update an existing script or module, the conversion can likely be (semi-)automated using a regular expression.

**Comment by tasgon** [comment]
> I think it's better to provide only one way to do things in 4.0 and later.

While I generally agree with this sentiment, one can see these two API methods called hundreds of times in module code. While this PR does add a bit of legacy cruft, I think the advantages by adding it and making it easier for module devs to get started on Godot 4 is worth the effort.

Personally, I'd say these functions should be marked as [`[[deprecated]]`](https://en.cppreference.com/w/cpp/language/attributes/deprecated) with clear intent that they will likely be removed at a later time.

**Comment by pycbouh** [comment]
Hundreds of times is less than what we had to change in the engine 🙃 Module developers would have to change a lot of things for 4.0, internals are even less compatible than public API. There is no point restoring outdated ways, it’s better to properly migrate your work. Besides, there are months before the release to do that.

**Comment by tasgon** [comment]
Alright then, in that case I'll close this.

**Pull request closed without merging**
