### PR TITLE
Update miniupnpc to 2.2.4

### PR DESCRIPTION
**Pull request by DeeJayLSP**
The 2.2.4 update on miniupnpc is just an update on licenses and source code comments, but I think it's important to keep it updated.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good, just needs a copyright year update here:
```diff
diff --git a/COPYRIGHT.txt b/COPYRIGHT.txt
index 2dc58158ef..02cd733c92 100644
--- a/COPYRIGHT.txt
+++ b/COPYRIGHT.txt
@@ -293,7 +293,7 @@ License: CC0-1.0
 
 Files: ./thirdparty/miniupnpc/
 Comment: MiniUPnP Project
-Copyright: 2005-2021, Thomas Bernard
+Copyright: 2005-2022, Thomas Bernard
 License: BSD-3-clause
 
 Files: ./thirdparty/minizip/

```

**Comment by DeeJayLSP** [comment]
Done

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.2.

**Pull request merged**
