### PR TITLE
Fix for the sprite display position jumps when placed at subpixel locations and moving the camera (3.2)

### LINKED ISSUE #35606: 2D Sprite "jittering", very noticeable when using camera smoothing
**Godot version:**
3.1.2 stable, GitHub master (3.2), Vulkan branch (4.0)

**OS/device including version:**
Windows 10 x64 v1909

**Issue description:**
Pretty much as soon as I made my test level larger than a single screen, I noticed something was off. After a bit of testing, I've found out what it is. It seems like any time the camera moves, there is some sort of inconsistency in the positions sprites are being rendered at, causing them to "jitter" back and forth by one pixel even though the camera is only moving in one direction.

Example gifs showing the issue:
A5aCVeO
EhPwu5N

How noticeable it is depends on circumstances. Generally, from what I've found, it's most noticeable if you have camera smoothing turned on and the smoothing speed set to a very low value, but the problem isn't related to the camera smoothing. It's also present with camera smoothing turned off, just harder to notice.

In case it was a bug that had already been fixed, I tried compiling Godot myself from both the master (presumably what will become 3.2) and vulkan (4.0?) branches to try them out, but unfortunately the problem still seems to be present in both of those. It looks a bit different in the Vulkan branch, due to what I assume is some sort of smoothing/blur filter being applied (there may be a way to turn that off, but I couldn't find it) to the background, but it is definitely still there.

**Steps to reproduce:**

1. Start minimal reproduction project
2. Run far enough to the right that the camera starts scrolling and stop.
3. Watch the vertical lines of the background brick wall or the ground near the player to see the sprite jittering back and forth by one pixel until the camera fully stops

**Minimal reproduction project:**
[godot-jitter-repro-project.zip](https://github.com/godotengine/godot/files/4115122/godot-jitter-repro-project.zip)

### LINKED ISSUE #41491: Sprites with subpixel world positions are displayed with unexpected and uneven displacements
I tried finding this issue reported but I've come empty handed.

**Godot version:**

3.2.2 official build.

**OS/device including version:**

Windows, happens both with GLES2 and GLES3.

**Issue description:**

Creating a small test level I dragged many (parallax) map objects together without caring about perfect positioning of anything, so about all of them ended up in non integer (X, Y) positions.

When moving the camera the elements display at slightly unexpected positions, separating ones from the others even though all of them have equal parallax parameters, thus destroying the illusion of cohesion of the elements. If I erase the subpixel amounts of the coordinates everything displays as expected.

Further tests showed this behavior is not limited to parallax elements but is a more general issue that happens with regular 2D sprites too. If sprites have non integer positions the final display positions get jumpy, like if the final position is sometimes rounded up and sometimes down, depending on the relative position to the camera.

I think it's important to remark that the Pixel Snap option does nothing to prevent this behavior.

**Steps to reproduce:**

Draw a bunch of 2D sprites at non integer coordinates and scroll slowly to experience the issue.

**Minimal reproduction project:**

I'm including a small project with two cameras in split screen that slowly move in circles over a bunch of sprites. At the left the sprites have subpixel positions and experience this issue. At the right the sprites are at integer positions and all can be seem displaying as a solid block. I think it's reasonable to expect the left camera to display the static sprites always at the same positions relative to each other.

GIF 24-Aug-20 16-00-08

[spritepositions.zip](https://github.com/godotengine/godot/files/5118245/spritepositions.zip)

### PR DESCRIPTION
**Pull request by m6502**
Fixes the 2D canvas display positions jumping pseudo randomly when the are located at fractional coordinates and the camera changes location. Fixes #41491, fixes #35606 etc. Godot 3.2 branch.

### CODE REVIEW

**Comment by lawnjelly** [comment]
I had a little look and I agree this looks promising. :+1: :smiley:

It applies the snap (floor) to the positions before scaling is applied (which is in the basis). The existing shader approach applies it after the basis is applied. To some extent this may be able to be done in the shader too, but on first impressions I think doing it on CPU (for the position only) avoids issues with snapping vertices independently.

_Something I didn't quite catch on from your issue #41491 from the terminology, it is really about scaled pixels, rather than on screen pixels and screen sub pixels (I was assuming these were zoomed gifs), which is probably the reason for the misunderstanding with @Zireael07 and myself._

In the example case project that forbjok provided it does seem to cure the scaled zoomed pixel jiggle. I double checked and screen pixel level jiggle can still occur with differing scales:

2d_snapping

_This is 2 scrolling frames superimposed on each other, zoomed to 300% showing the edges shifting, notice the edge to the right of the left leg._

However screen pixel jiggle is less objectionable than the zoomed pixel jiggle (and screen pixel jiggle may not be possible to solve in all situations).

This will probably need a fair bit of testing (especially with different scales superimposed and rotations), and may well need to be a project settings option or similar, in case there are knock on effects in other parts of the rendering (a lot of the 2d items may go through that path), but on first impressions it looks good so fingers crossed. :+1:

**Comment by m6502** [comment]
@lawnjelly what did you do? Can you upload the project?

**Comment by lawnjelly** [comment]
> @lawnjelly what did you do? Can you upload the project?

[Forbjok2.zip](https://github.com/godotengine/godot/files/5134530/Forbjok2.zip)

I did this yesterday and have since recompiled the engine with different fork so I can't absolutely confirm the project is the same but hopefully is. 

Basically I just scaled the character and the background to different scales, if I remember right. Yes looking at the project I used the original project but set the tilemap to 3, 3 scale and the player to 2,2 scale. Then I recorded with a screen recorder, stepped through the frames, then superimposed 2 on each other to line up. I was also playing with the viewport scaling mode in the project settings, you might want to double check that is the same.

**Comment by m6502** [comment]
Thanks for testing it @lawnjelly  I downloaded your project, ensured the map and player scales and also added an extra idle sprite to the player separated by -0.11 pixels in X and Y. You were right, there was still some jumping creeping up.

Anyway I may have fixed it for good now, and will add the commit to the pull request in a few hours :-) 

Here's my modified version of the project. If you want to try again, just wait for the character to reach the floor, take small steps and see if you see jumping there. This is working perfectly for me now:

[Forbjok3.zip](https://github.com/godotengine/godot/files/5135766/Forbjok3.zip)

**Comment by m6502** [comment]
GIF 27-Aug-20 12-33-07

**Comment by m6502** [comment]
(The extra sprite is not animating or mirroring when going left, so take the steps only to the right or it'll seem like something went terribly wrong there).

**Comment by m6502** [comment]
Improved the fix by cleaning the fractional part sooner. This time the fix seemingly fixes everything. I tested rotations too. Works as expected here. Does anyone dare to give it a try? :-)

**Comment by m6502** [comment]
Improved the fix for 4.0 too. More info at the 3.2 pull request: #41535

**Comment by jkb0o** [comment]
I can't say if this fix actually something, but my parallax scenes with a lot of inaccurate positions, rotations, etc look pretty good.

**Comment by m6502** [comment]
@jkb0o This fixes the final display position calculation of sprites placed at non integer positions like x = 1.31 etc. Take a look at these two captures I did for you. This scene has many sprites placed by hand with no one ending in a nice rounded position. The camera is barely moving at all as I increment it by super small steps to make the problem even more apparent. Just watch how everything wobbles before applying the fix, with the 3.2.2 official build, you can't even tell what the camera is really doing:

3 2 2 official

And this is what happens when you apply the fix. Everything moves at the same time and the relative distances between sprites are preserved so you can't tell if it's a big sprite or a lot of objects placed together. The super slow and small camera movement is recognizable (the small jump is due to the gif looping):

fixed

**Comment by Ranoller** [comment]
This is great, it allow me to delete a lot of round() in the game code, with all the overload that it cost. Thanks!

**Comment by jkb0o** [comment]
I've checked one more time for a big project and with this PR I have a lot of objects inside ParallaxBackground misplaced, most of them inherits Control (TextureRect, etc). I have `gui/common/snap_controls_ti_pixels` turned off in project settings.

**Comment by m6502** [comment]
@jkb0o is there a way you can share a sample of that or make a small test project?

**Comment by jkb0o** [comment]
@m6502 there is a small test project:
[iceberg.zip](https://github.com/godotengine/godot/files/5176178/iceberg.zip)
This is how it is rendered **without** fix:
Screenshot 2020-09-04 at 20 31 35
This is how it is rendered **with** fix:
Screenshot 2020-09-04 at 20 32 30

**Comment by m6502** [comment]
I can't check with the fix right now, but why is the left part of the iceberg one pixel taller if all the sections have the same size? I think fixing the bug is maybe uncovering another bug elsewhere. Note how with the fix the vertical size is right.

**Comment by jkb0o** [comment]
@m6502 this iceberg builded using HBoxContainer, it has something about 12 parts. These pictures show the difference between the engine with the PR (bottom picture, mispositioned) and the engine version without the PR (top picture, rendered nicely). I just run the same project with different versions of the engine. This shows the PR is not ready or at least is not back-compatible and can break existent projects.

**Comment by Ranoller** [comment]
This PR sounds to me like a candidate to a "Project setting", the same that "pixel snap" or "nvidia rect flicker workaround". Making this optional doesn't have collateral damages. I think is a good setting for a pixel art game, but lossing the "natural antialiasing" of floating positions can be bad for other kinds of projects.

**Comment by m6502** [comment]
@Ranoller this PR doesn't have anything at all to have with natural antialiasing but with incorrect display positions of 2D sprites. There's nothing desirable about the current behavior, it's just a bug.

**Comment by m6502** [comment]
@jkb0o I'll investigate your project more carefully very soon. My theory is that the iceberg part positions are "wrong".  I'm not saying you did anything wrong, but as you created it with a version of the engine that displayed the parts at the wrong positions now it's displaying incorrectly when the calculation is different. This doesn't mean the bug has to be mandatory for all future games created with Godot. In any case your iceberg isn't displaying properly in Godot 3.22 anyway, as you can verify in your poject if you just color the parts differently. You can see how they are jumping all the time, the iceberg doesn't look like a unitary solid block. This tells me they are being positioned at different subpixel relative locations from each other, maybe due to the alignment of the containers and / or the textures. I'll investigate this further very soon. Also there's the odd vertical length of the first segment of the iceberg. There's nothing in your project indicating this part shouldn't be the same size as the others, so why is it displaying in that way if not because there's a bug in it's display position calculation?

**Comment by m6502** [comment]
Here's the clearer iceberb test project I'm going to use to further investigate the issue:

[iceberg.zip](https://github.com/godotengine/godot/files/5180440/iceberg.zip)

**Comment by timothyqiu** [comment]
The pattern of iceberg spacing reminds me of something I encountered when trying to layout `TextureRect`s manually in 3.2.2:

spacing

The icons have a width of 50.29, and the X positions are set manually: 10, 60.29, 110.58, 160.87... A gap appears every three or four icons.

**Comment by m6502** [comment]
Would you mind to upload the project please? It would be of help.

**Comment by timothyqiu** [comment]
@m6502 Here you go: [Gap.zip](https://github.com/godotengine/godot/files/5194930/Gap.zip)

**Comment by m6502** [comment]
@Timofffee Thank you very much, I'll take a look tonight, probably.

**Comment by Ranoller** [comment]
I compiled godot with this commit and test:

**Resolves some rendering problems:**
   · No more transparent lines between tiles in tilemap because not integer positioning in camera zooms other than Vector2(1,1), Vector2(2,2) etc.... This is completely fixed.
   · No more statics sprites dancing one each other in slow camera movements.

**But has a collateral effect:**
    · Overload in rendering. I´m lost over 100 pfs and i think is because .floor() operation in visual server canvas. I can´t ensure that this is not because some type of optimization in official builds, i compile with platform=windows target=release_debug tools=yes. I don´t care about this fps lost, because if i can delete all the ".round()" that are in my game, probably I can win a lot of performance anyway. If i find the time i will continue testing a build without the commit to discard performance differences between my build and the official build.

**And effects that are not good or bad per se:**
    · No more blurry slowly camera panings. More clear image but more camera sickness in any fps slow down, flickering or stuttering (I´m very sensitive to that, believe me).

Probably i´m going to use that in my game. For pixel art this commit achieves critical problems. And losing 100 fps in a game that executes at 500 fps in a bad computer is not a problem at all.

I still think that this is perfect for a **project setting**, or a visual server direct property that could be toogled in runtime (more overload i know), this resolves issues for some kinds of games and leaves options for users that don´t want this rounding.

I really want to see Godot 3.2.3 stable with a project setting like this, because i´m going to use that only because the "_tilemap empty lines fixing_", but using official templates offers advantages to me that i don´t want to lost...

Anyway, thanks for the commit.

**Comment by Calinou** [comment]
> Overload in rendering. I´m lost over 100 pfs and I think is because .floor() operation in visual server canvas. I can´t ensure that this is not because some type of optimization in official builds, I compile with platform=windows target=release_debug tools=yes.

Please make a fair comparison by compiling the `3.2` branch *without this PR* with the same build flags and compiler.

**Comment by m6502** [comment]
@Ranoller To be honest my own compiled versions (with or without this PR) are always slower than the official build. Not sure why but I haven't had time to investigate it further.

In any case (and for the same time reasons) I haven't said anything about it, but I MAY (only may) have a faster version of this PR incoming, pending some tests :-)

**Comment by Calinou** [comment]
@m6502 Did you enable link-time optimization using `use_lto=yes`?

**Comment by akien-mga** [comment]
The only good way to compare performance for a PR is to do before/after builds with the same configuration. So if you don't have access to the official build system to do an "after" build with the PR, you should do both locally ;)

**Comment by m6502** [comment]
@Calinou  No, I didn't. Here's how I compile it:

`scons -j10 platform=windows target=release_debug`

Now I'll use:

`scons -j10 platform=windows target=release_debug use_lto=yes
`

**Comment by Ranoller** [comment]
I did the test of compiling with and without modification:

 · FPS issue:
    **There is not perceptible fps slow down.**

 · Tilemap issue:
I made test with a lot of different camera zoom rates. The problem with the transparent lines between tiles is not completely gone. Is more "deterministic". I explain: Without the commit, with a zoom rate of Vector2(0.7, 0.7) I have this empty lines in different places depending of the place on the camera stops, and once panning, the lines appears and dissapears randomly. With the commit, i have the empty lines always in the same tile. With a zoom rate of 0.8, 0.9 I have no lines with the commit, without that, I have that deppending of the camera position. At a zoom rate of Vector2 (1.0,1.0) or Vector2 (2.0,2.0) i have no lines no matter the commit, if the size of the screen is 1px -> 1px with the game size.

**I feel that this is not easely fixable with a rounding**, because if the screen if resized and not render 1px -> 1px or power of 2 or some other not problematic sizes, the problem returns, so the only fix is making a tile texture that exceed 1 px in every side of the tile. **Not problem about that, it´s a manageable problem and was not the objetive of this fix.** But the problem is alleviate, there is less tiles that shows that lines.

 · Sprite positioning issue:
    **This is completely fixed with this commit.** No more sprite dancing.

My opinion, if it matters, is: Worth it!

**Comment by m6502** [comment]
Thanks for checking Ranoller. I have an intuition about these lines but I think that is going to be a different pull request. I may try to dig on it but right now I'm busy with work :-)

**Comment by m6502** [comment]
Asking the same question in #41534. What is required to get the review required to unblock this pull request? I would really like to see it merged for the next RC :-) We are fixing a bunch of open issues with this.

**Comment by akien-mga** [comment]
This needs a rebase to squash commits and improve the commit message.

**Comment by lawnjelly** [comment]
I'll try and comment fully when I have some more time in next few days to examine this. But irrespective of any changes, it will need to have a project setting to turn on / off.

**Comment by m6502** [comment]
As far as I've been able to check, the iceberg scene breaking is related to another bug that is not noticeable without fixing this first. These past weeks I've been a bit busy with work/family so I haven't been able to try to fix that case, so right now having a project setting as fail-safe / compatibility option seems like a good idea to me. 

Thanks for your comments.

**Comment by reduz** [comment]
I created a PR that works a bit different, seems to solve these issues. Also the iceberg scene does not seem to break with it.
https://github.com/godotengine/godot/pull/43194

**Comment by jwunderlin** [comment]
Is there a way to test this PR without compiling Godot? I see this pixel sprite jitter in my own project and was wondering if this PR would fix it. :)

**Comment by Calinou** [comment]
@jwunderlin Which operating system are you on? I can give you a compiled editor binary.

**Comment by RPicster** [comment]
I would piggy back here. (I am on win 10).

I have the problem in a really brutal matter on my player and would love to see if this pr would fix it.

**Comment by lawnjelly** [comment]
This probably needs reduz PR backporting to 3.2, which uses a similar technique and contains some extra stuff. If no one else is doing it I'll have a look once I've sorted the skinning.

**Comment by Calinou** [comment]
Here's a 64-bit Windows editor build of this PR: https://0x0.st/i5zC.zip (link expires in March 2021)

Keep in mind it was compiled directly, which means it's somewhere in between 3.2.2 and 3.2.3 in terms of functionality and bug fixes. Make a backup of your project before opening it.

**Comment by RPicster** [comment]
So, my character is still blurring around while moving. Is there a setting I need to activate (except the standard pixel snap)?

It also leads me to the conclusion that maybe something else in my project is causing the blurriness

**Comment by m6502** [comment]
Do you really need the pixel snap? I mean, imagine you zoom the image and move 0.1 pixels. Should your character change position or remain at the pixel margin jumping to the next when it reaches it's position? Pixel snapping and smoothnes do not really mix :-)

**Comment by RPicster** [comment]
> Do you really need the pixel snap? I mean, imagine you zoom the image and move 0.1 pixels. Should your character change position or remain at the pixel margin jumping to the next when it reaches it's position? Pixel snapping and smoothness do not really mix :-)

Is this ironic? If you don't have anything to contribute to this problem other than that, maybe it would be better to keep away from a issue.

**Comment by jwunderlin** [comment]
This worked for me! Thank you so much! I had to switch the Window settings to 2D instead of Viewport and its way better. I also tried it with camera smoothing too and it works but isn't quite as nice. The camera fixed on the player looks best. There's a bit of a motion blur like effect when the camera is moving but there isn't any sprite jittering that I was seeing before. I think the motion blur is just what pixel art does in high res with a moving camera? Turning on or off Pixel Snap didn't make a difference in my project from what I could tell.

**Comment by Calinou** [comment]
> Is this ironic? If you don't have anything to contribute to this problem other than that, maybe it would be better to keep away from a issue.

I don't think they were ironic here. When you have a pixel art style and want to keep your pixels crisp, you have to accept that you'll have to give up on smoothness to an extent.

> There's a bit of a motion blur like effect when the camera is moving but there isn't any sprite jittering that I was seeing before.

This is likely due to monitor ghosting, which is an hardware issue. The game engine can't do anything about it :slightly_smiling_face:

**Comment by RPicster** [comment]
> > Is this ironic? If you don't have anything to contribute to this problem other than that, maybe it would be better to keep away from a issue.
> 
> I don't think they were ironic here. When you have a pixel art style and want to keep your pixels crisp, you have to accept that you'll have to give up on smoothness to an extent.
> 

I don't think this is true. You can achieve sub pixel smoothness while having pixel grid snapped assets.

https://code-disaster.com/2016/02/subpixel-perfect-smooth-scrolling.html

I implemented this technique and it works nicely.
> > There's a bit of a motion blur like effect when the camera is moving but there isn't any sprite jittering that I was seeing before.
> 
> This is likely due to monitor ghosting, which is an hardware issue. It usually becomes less noticeable as you make your game more polished with more art and effects. The game engine can't do anything about it 🙂

I have the exact same problem on a 144hz screen with gsync. So a hardware effect is basically almost ruled out. Never had the effect on any other pixel game

**Comment by Calinou** [comment]
> I have the exact same problem on a 144hz screen with gsync. So a hardware effect is basically almost ruled out. Never had the effect on any other pixel game

Using a 144 Hz monitor with G-Sync doesn't remove ghosting, especially if you've left overdrive on a low value.

**Comment by RPicster** [comment]
> mind

I don't think it makes sense to argue about my monitor which is absolutely high end with 1ms gtg.

It only on the player and it's not just a little bit. There is definitely a problem. I don't say it's necessarily an engine bug. It could also be in my code. But it's not my monitor.

**Comment by jwunderlin** [comment]
I think my motion blur issue is my monitor. I checked with another pixel art game (Wizards of Legend) and it has a similar motion blur to what I'm seeing so for now I'm going to keep moving forward with development. Thank you everyone for all your insights and help. I was so excited to finally be putting some art into my game and was really disappointed to see how bad the rendering was. So thank you for such a quick response!

**Comment by m6502** [comment]
> 
> 
> > Do you really need the pixel snap? I mean, imagine you zoom the image and move 0.1 pixels. Should your character change position or remain at the pixel margin jumping to the next when it reaches it's position? Pixel snapping and smoothness do not really mix :-)
> 
> Is this ironic? If you don't have anything to contribute to this problem other than that, maybe it would be better to keep away from a issue.

Wow, what are you talking about? I have spent many hours contributing to this issue, have you noticed I'm the person making this pull request?

**Comment by RPicster** [comment]
> > > Do you really need the pixel snap? I mean, imagine you zoom the image and move 0.1 pixels. Should your character change position or remain at the pixel margin jumping to the next when it reaches it's position? Pixel snapping and smoothness do not really mix :-)
> > 
> > 
> > Is this ironic? If you don't have anything to contribute to this problem other than that, maybe it would be better to keep away from a issue.
> 
> Wow, what are you talking about? I have spent many hours contributing to this issue, have you noticed I'm the person making this pull request?

No sorry I haven't.
I am just extremely annoyed by the issue that I spent countless hours trying to fix. Sorry if I chose the wrong tone.

I have a pixel art game, so pixel snapping is a must have. Otherwise I have all the problems that probably made you submit the PR.

Sorry again and thanks for your work.

**Comment by Calinou** [comment]
@RPicster You may have to add physics interpolation to your project by using the [smoothing-addon](https://github.com/lawnjelly/smoothing-addon). The effect is especially noticeable on monitors with a refresh rate above 60 Hz.

**Comment by akien-mga** [comment]
@lawnjelly is this fully superseded by #43554 or are there still relevant changes here to include as an option?

**Comment by lawnjelly** [comment]
> @lawnjelly is this fully superseded by #43554 or are there still relevant changes here to include as an option?

Yup this is superseded, it contains m6502's changes and others. :+1:

**Comment by akien-mga** [comment]
Closing as superseded by #43554 (for 3.2.4) and #41491 (`master`).

Thanks a lot to @m6502 and all testers who helped come with the right solution.

**Comment by m6502** [comment]
You are welcome!

**Comment by securas** [comment]
@m6502 I'm afraid that this feature is going to be hard to use in 2D pixel art platformers. I tried a few of my old games with it and the outcome is always the same... The kinematic bodies stay 1px above the floor.
flying_bunny_eats

**Comment by m6502** [comment]
Doesn't that look like a bug somewhere else that has been revealed now that sprites stay where they are supposed to be? What is the floor position, and what's the character position?

**Comment by securas** [comment]
> Doesn't that look like a bug somewhere else that has been revealed now that sprites stay where they are supposed to be? What is the floor position, and what's the character position?

It only happens when activating transform snap regardless of the camera setting.
The kinematic body is reporting somewhere around 0.1px above the floor and the corresponding sprite anchor is zero with respect to the kinematic body.
If the flooring rule is applied would it not lead to this 1px offset?

**Comment by m6502** [comment]
What you are experiencing sounds more to me like you have Pixel Snap activated. Take into account that this fix is not related to that, quite the opposite: It's indeed intended to allow sprites to be positioned at subpixel coordinates. What does happen if you disable Pixel Snap and leave Transform Snap activated?

If floor is, for example, at Y = 32.0, where does the body stay? Can you check that please? :-)

**Comment by securas** [comment]
I did indeed have pixel snapping on. But I turned it off and got the same result. Here's a gif along with the positions of the KB and the KB collider (floor). I think this corresponds to your check.
flying_bunny_eats_2

**Comment by lawnjelly** [comment]
This is likely the same as seen in:
https://github.com/godotengine/godot/pull/43554#issuecomment-732392410
see the discussion following (it doesn't have its own issue at the moment afaik).

Also see my rounding PR (#43813) which wasn't merged, and the discussion in there.

**Comment by Zireael07** [comment]
Seeing those issues, I think the rounding PR should be reopened?

**Comment by lawnjelly** [comment]
> Seeing those issues, I think the rounding PR should be reopened?

Yup, I will, I'm just rebasing it.

**Comment by m6502** [comment]
Watching that capture I see floor at Y = 136 and character at Y = 135. I would say that is technically correct. But the character seems to be drawn at Y = 134. Are you really sure your pixel snap is disabled? Try to add a 0.5 offset to the Y drawing position of the character and see if it's half a pixel up. It should be. As I said, this fix was intended to allow objects positioned at subpixel coordinates to have a stable drawing position as it was pseudo random before and that opened gaps between adjacent objects etc.

I'm wondering, where is the character's local Y=0? Where is the character's sprite pivot? Is it centered? Does it have an even or an odd Y size?

**Comment by securas** [comment]
The floor number is not its position. It is the coordinate of the collision reported by the kinematicbody. So, with the collision at 136, the character should be at 136 or slightly less like 135.99, which is the case. As far as I can see, the character is never at 135.

**Comment by securas** [comment]
> Judging by the moving objects and the character it's still snapping to world pixels and not using sub pixel coordinates
I have disabled snap to pixel. But given your persistence, I will send a capture later with the collision shapes.

**Comment by m6502** [comment]
Thanks, just trying to help and understand what's happening. What does happen if you draw something at the same coordinates of your character + 0.1 in X or Y (or both)?

**Comment by m6502** [comment]
Or 0.5 to make it more evident (maybe). Something like this where the right character is being drawn at half a world pixel difference in Y:

image

**Comment by m6502** [comment]
Pixel snap would draw both at the same Y position, or stick the right character to the floor, depending on what is used for rounding. Disabling pixel snap should allow you to draw the second image at any sub pixel offset you wanted.

To me it looks like for some reason the game is still using pixel snapping for some reason (are you rounding at the code maybe?). Also I would check if the bottom of the character collision is below the feet, even for a fractional part, or it's "inside" the feet last pixel in Y.

**Comment by m6502** [comment]
Also what is the collision margin of the character collider.

**Comment by securas** [comment]
The game is on viewport mode. I will never draw images on sub Pixel positions.

**Comment by securas** [comment]
Ok... Trying to address all your questions. I duplicated the main sprite on my character and offset the right side sprite by 0.5px:
(Editor View)
image
The KinematicBody2D has default safe margin
image
Here are the project settings regarding snapping
image
And here are the window settings
image
The camera code has no function for snapping at all. Here are the settings
image
And this is a snapshot in game
image

**Comment by m6502** [comment]
Thanks for taking your time.

**Comment by m6502** [comment]
The floor col Y = 136 on your previous GIF is the reported collision point, isn't it?  Wondering if making your character.position.y = reported collision makes it stick to the floor?

There's definitely something fishy going on here on overall... And I may have found a new bug by trying to replicate the steps I told you on another project becase my character is moving a whole pixel while on the editor... On the OTHER axis 🙄

**Comment by securas** [comment]
If its a KinematicBody, it should make little sense to change its position
manually. Also, that should be done anyways when using
move_and_slide_with_snap... No?

**Comment by m6502** [comment]
I meant just as a test or temporary workaround.

**Pull request closed without merging**
