### PR TITLE
Let ClassDB::add_property use getter/setters with optional params

### LINKED ISSUE #43821: ClassDB::add_property does not support setters with optional secondary arguments
**Godot version:**

Latest on both branches
3.2.3 279f4fbb5f83c2df6e8499799a2aa0c14f85aa2d
4.0 32b31a5

**OS/device including version:**

N/A

**Issue description:**

I'm creating a C++ module that adds new nodes with properties.

One of my setters has a signature with an optional second parameter, e.g.
```cpp
void set_somevalue(int p_value, bool p_force_update = true);
```
However, `ClassDB::add_property` (with `DEBUG_METHODS_ENABLED` defined) enters a fail condition and spits out "Invalid function for setter ..." because the expected number of arguments is one (or two for indexed setters).

Optional second parameters in GDScript are supported, but not in core. If possible, core should allow this.

**Steps to reproduce:**
In a custom module, create/register a new Node derived class. In `_bind_methods`, add a property:
```cpp
ClassDB::bind_method(D_METHOD("set_somevalue", "somevalue", "force_update"), &MyNode::set_somevalue, DEFVAL(true));
ClassDB::bind_method(D_METHOD("get_somevalue"), &MyNode::get_somevalue);
ADD_PROPERTY(PropertyInfo(Variant::somevariant, "somevalue"), "set_somevalue", "get_somevalue");
```

**Minimal reproduction project:**

N/A

### PR DESCRIPTION
**Pull request by briansemrau**
Fixes https://github.com/godotengine/godot/issues/43821

I referenced https://github.com/godotengine/godot/pull/25018 to determine what changes to make.

### CODE REVIEW

**Comment by briansemrau** [comment]
I'd like to cherrypick this into 3.2 so I can use it in my project, so if this gets approved I will submit a PR for that.

**Comment by reduz** [comment]
This unfortunately makes language binding more complicated as languages can no longer expect the setter/getter functions to always have one way of calling. As this is not that much of an useful feature and makes binders more difficult, I am against merging it.

**Comment by briansemrau** [comment]
> 
> 
> This unfortunately makes language binding more complicated as languages can no longer expect the setter/getter functions to always have the same form. As this is not that much of an useful feature and makes binders more difficult, I am against merging it.

Okay, that makes sense. I originally thought that these changes were a self-contained fix for this limitation. Seeing how this is infrequently used (and has an easy enough workaround https://github.com/godotengine/godot/issues/43821#issuecomment-733850750), I'll close this.

**Comment by reduz** [comment]
No problem, still thanks for taking the time to do the contribution!

**Pull request closed without merging**
