### PR TITLE
Update documentation for the new ProcessMode

### LINKED ISSUE #1011: Refactor the pause system to allow pausing arbitrary parts of the scene tree
**Describe the project you are working on:**

See the discussion in https://github.com/godotengine/godot/issues/15993, there are already many users desiring this feature and giving example use cases. In fact, most of the users in the thread seem to be confused and thought it was a bug at first, since how they expected pausing to work is how this proposal works.

**Describe the problem or limitation you are having in your project:**

The current pause enum looks [like this](https://docs.godotengine.org/en/latest/classes/class_node.html#enumerations):

> * **PAUSE_MODE_INHERIT = 0** — Inherits pause mode from the node’s parent. For the root node, it is equivalent to PAUSE_MODE_STOP. Default.
> * **PAUSE_MODE_STOP = 1** — Stops processing when the SceneTree is paused.
> * **PAUSE_MODE_PROCESS = 2** — Continue to process regardless of the SceneTree pause state.

The SceneTree pause state referenced above is [a boolean in SceneTree](https://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-property-paused).

Changing the pause mode for any node has no effect except for when the `paused` boolean is true. This means that the only purpose of changing the pause mode is to force specific nodes to be **un**paused, and the only purpose of `PAUSE_MODE_STOP` is to force pausing of a node under an unpaused one. This also means that there is no way to pause just some parts of the scene tree.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The proposal is to refactor the pause system to allow pausing arbitrary parts of the scene tree. I propose to simplify the system such that the only thing that determines the pause state is the pause mode enum (renamed to `PauseState` to reflect this). This means that SceneTree's `paused` boolean will be removed. Then, the enum would behave like this:

* **PAUSE_STATE_INHERIT = 0** — Inherits pause state from the node’s parent. For the root node, it is equivalent to PAUSE_STATE_PROCESS. Default.
* **PAUSE_STATE_STOP = 1** — Stop processing always.
* **PAUSE_STATE_PROCESS = 2** — Continue processing always.

This means that if you wanted to pause the whole scene tree, instead of `get_tree().paused = true`, you would instead use `get_tree().root.pause_state = PAUSE_STATE_STOP`. Unlike the current system, this proposed system can be used to pause or unpause any node in the scene tree. You can simply replace `get_tree().root` with a reference to the node you want to pause or unpause. Unlike the current system, the ability to pause any node is not dependent on the SceneTree's (or root node's) pause state.

I would appreciate it if anyone can share use cases that can't work with the above system. I can't think of any, the system seems to work really well in my head considering how simple it is.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

The behavior is explained above, and it would behave like that. I could implement it if desired. EDIT: https://github.com/godotengine/godot/pull/39606

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

No, not really. However, this new system is a lot more flexible if users did want to have a lot more manual control over how their game is paused.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This is about refactoring a core feature, so it is already in core.

### PR DESCRIPTION
**Pull request by aaronfranke**
EDIT: Reduz has another PR that replaces this, #46191. Since this PR is similar and already has documentation written, I will rebase this on top of #46191 with the documentation additions from here.

Implements and closes https://github.com/godotengine/godot-proposals/issues/1011. This was easier than I expected, it seems to work perfectly.

Minimal test project: [pause-testing.zip](https://github.com/godotengine/godot/files/4789462/pause-testing.zip), but this needs more thorough testing.

### CODE REVIEW

**Comment by KoBeWi** [comment]
I think you did a full replace and modified `.pot` files accidentally.

**Comment by aaronfranke** [comment]
Yes. I don't actually know what the `.pot` files are for, so I just replaced everywhere.

**Comment by KoBeWi** [comment]
They are translated strings from Weblate. They shouldn't be changed manually.

**Comment by aaronfranke** [comment]
Thanks for the information, I reverted the changes to them and [added a README](https://github.com/aaronfranke/godot/tree/pause/doc/translations).

**Comment by dalexeev** [comment]
The only question is: why do we need the `pause_state_process` parameter in the `SceneTree.create_timer` function? After all, now `SceneTree` can not be paused.

**Comment by aaronfranke** [comment]
@dalexeev Now it depends on the root node's pause state. I forgot to update the documenation for this earlier, but now it's updated.

**Comment by emmetoneillpdx** [comment]
Hey there, Aaron. 

I commented in the original proposal what seems like forever ago now and, having tested this patch a little bit, I still think this is a solid improvement to the way that pausing is handled in Godot. The ability to simply pause any subtree of nodes is, in my opinion, really convenient, intuitive and a good fit for Godot's node tree design. 

My testing wasn't super thorough because master is still a bit buggy right now for me, but playing around with and adding things to your test project worked exactly as expected. Although this doesn't really make anything possible that wasn't before, I think it's still a big improvement with a lot of practical uses.

My only [admittedly super minor] nitpick is that I think the terminology could be better. 

The old "pause mode" terminology made sense because it was describing the behavior of a node when the tree was paused. But, I think "pause state" is a little bit awkward especially in the case of "PAUSE_STATE_PROCESS", which is self-contradictory and potentially confusing. Here's how I'd personally reword things:

`Node::PauseState` => `Node::ProcessingState`, or maybe even `Node::Processing`
`PAUSE_STATE_PROCESS` => `PROCESSING_STATE_RUNNING`
`PAUSE_STATE_STOP` => `PROCESSING_STATE_PAUSED`
`PAUSE_STATE_INHERIT` => `PROCESSING_STATE_INHERITED`
Inspector's `Pause` submenu => `Processing` submenu.

Yes, these names a little bit longer if that bothers some people (not me!), but I think that they better reflect the fact that we are really changing the state of how a particular node is *processing*; it's running, it's paused, or its behavior is inherited from its parent (default).

At any rate, I think this is a solid patch and I hope it gets merged! Thanks for making it. :100:

**Comment by aaronfranke** [comment]
I don't find `PAUSE_STATE_PROCESS` to be self-contradictory, it's similar to how `paused = false` semantically makes sense, or `active = false`. It's saying that the paused state is to process, which means its pause state is not paused.

That being said, I'm not against renaming these too, and your proposed names are very sensible, so I would like to get community feedback first.

**Comment by lightspot21** [comment]
IMHO, the proposed naming changes (at least for `PAUSE_STATE_PROCESS` => `PROCESSING_STATE_RUNNING`) are clearer than what we already have. On top of that, I'd suggest also `PROCESSING_STATE` be renamed to `UPDATE_STATE`, like so:

`PAUSE_STATE_PROCESS` => `UPDATE_STATE_RUNNING`
`PAUSE_STATE_STOP` => `UPDATE_STATE_PAUSED`
`PAUSE_STATE_INHERIT` => `UPDATE_STATE_INHERITED`

for brevity. CC @aaronfranke

**Comment by tavurth** [comment]
Perhaps `PauseBehavior`?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
