### PR TITLE
mono: convert unicode mono root path to ascii string

### LINKED ISSUE #19739: Build error: environment can only contain strings
**Godot version:**
25275de with mono

**OS/device including version:**
Windows 7
Python 2.7.14
Mono 5.12

**Issue description:**
When I execute:
```
call scons.bat -j2 platform=windows module_mono_enabled=yes tools=yes  mono_glue=no
```
The build fails with this message:
```
MSBuild path: C:\Program Files\Mono\bin\msbuild.bat
scons: *** [bin\GodotSharpTools.dll] TypeError : environment can only contain st
rings
Traceback (most recent call last):
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-3.0.0\SCons\Action.py", l
ine 1197, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "C:\Apps\godot\engine-repo\modules\mono\SCsub", line 206, in mono_build_s
olution
    subprocess.check_call(msbuild_args, env=msbuild_env)
  File "C:\Python27\lib\subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
scons: building terminated because of errors.
```

This error does not occur when building 80f7eac with mono

### PR DESCRIPTION
**Pull request by KellyThomas**
Fixes #19739

scons was choking when the environment variables where unicode strings, this will convert compatible paths to ascii or throw an exception.

### CODE REVIEW

**Comment by akien-mga** [comment]
> I added the fix I forgot to push as part of #16987: https://github.com/godotengine/godot/pull/16987/files#diff-654ea5945e2faa32f3a0611a7abd1c8dL138

Both proposed fixes are hacky, but I prefer your hack :)

**Comment by KellyThomas** [comment]
> Do you think this change is better? I don't think it's possible for the mono root to contain non-ascii characters, since we get it from the environment variables or the registry.

I'll be honest the direct cast looks much more elegant. (Is it required for `msbuild_tools_path` as well?)

However it is possible for windows file systems to use unicode paths, and the registry will store and return them if required. I don't know how the python libraries handle this.

https://docs.microsoft.com/en-gb/windows/desktop/Intl/character-sets-used-in-file-names
https://docs.microsoft.com/en-gb/windows/desktop/SysInfo/registry-value-types

**Comment by neikeq** [comment]
@KellyThomas Is this problem only caused because of the return value from `find_mono_root_dir`? If that's the case, it may be better to add the fix there instead (surround the return with `str`).

To clarify, this error is only present in Python 2.7. I could not reproduce it with Python 3.

**Comment by neikeq** [comment]
I don't think so. `msbuild_tools_path` is not used anywhere in environment variables.

**Comment by KellyThomas** [comment]
OK, I've modified this to cast before return from `find_mono_root_dir()`

Testing shows if mono is installed at a location containing unicode characters the build fails with a message like this:

```
RuntimeError: Could not find mono library in: C:\Program Files\Mono?\lib
```

**Comment by neikeq** [comment]
Thanks!

**Comment by hpvb** [comment]
Cherry picked into 3.0.6

**Pull request merged**
