### PR TITLE
Add shader cache to GLES3

### PR DESCRIPTION
**Pull request by ChibiDenDen**
Implement shader cache read/write in the gles3 rendering pipeline

This is only supported on mobile platforms as desktop platforms are using gles over gl version 3.3, and 4.1 is needed.
Upgrading glad to 4.1 could be done in a separate PR.

### CODE REVIEW

**Comment by Calinou** [comment]
Note that the program binary extension is poorly supported on HTML5, so this will likely have to be disabled there.

**Comment by ChibiDenDen** [comment]
Thanks for the reference.

As far as I can see, async shader compilation is not supported for gles3 on godot 4 right now.

**Comment by clayjohn** [comment]
We don't need to implement async shader compilation right away. 

We don't actually need OpenGL 4.1 on Desktop, we just need support for the [``ARB_get_program_binary``](https://registry.khronos.org/OpenGL/extensions/ARB/ARB_get_program_binary.txt) extension (which was elevated to core in OpenGL 4.1). What you should do is use GLAD to load the extension and then check if it is supported
https://github.com/godotengine/godot/blob/17e0a0205df7bafa822d15e65ff39e03a0608cc6/drivers/gles3/rasterizer_storage_gles3.cpp#L8111

We need to do this anyway for Web support as you can't cache shader binaries in WebGL2.

The extension is very well supported on Desktop. GPUInfo only has 24 reports of OpenGL 3.3 capable devices not supporting it and in all those cases it looks like out of date drivers are responsible (they are all on Windows 7, Windows XP, or using Parellels to run Windows 10 on macOS).

**Comment by clayjohn** [comment]
I think this is still going to fail on Web exports as the GLES_OVER_GL section won't be included but glGetProgramBinary will still be null.

**Comment by ChibiDenDen** [comment]
I removed the ifdef GLES_OVER_GL hoping this would solve the WebGL issue.
Did not test the WebGL version myself yet as i'm having some trouble compiling for web locally.

**Review by clayjohn — APPROVED** [review]
Seems good to me now! 

I tested locally on my linux device with an intel integrated GPU and on my Android phone. On the phone the improvement is substantial with my test scene (which has a couple of really heavy shaders loaded at the same time). On Desktop it compiles so fast in either case that you can't really notice any improvement.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
