### PR TITLE
vkQueueSubmit needs pWaitDstStageMask sized to waitSemaphoreCount

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Ran into this by accident while working on VRS with validation layers on. 

```
ERROR: VALIDATION - Message Id Number: -1711571459 | Message Id Name: UNASSIGNED-GeneralParameterError-RequiredParameter
        Validation Error: [ UNASSIGNED-GeneralParameterError-RequiredParameter ] Object 0: handle = 0x1b997f7c070, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x99fb7dfd | vkQueueSubmit: value of pSubmits[0].pWaitDstStageMask[1] must not be 0
        Objects - 1
                Object[0] - VK_OBJECT_TYPE_DEVICE, Handle 1896630173808
```

I'm not sure in what condition `semaphores_to_acquire_count` becomes bigger then 1, seems it may be related to when you have more then 1 window, however `pWaitDstStageMask` needs to have entries for each one.

See: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSubmitInfo.html - `pWaitDstStageMask is a pointer to an array of pipeline stages at which each corresponding semaphore wait will occur.`

The fix here makes sure that each semaphore has a corresponding pipeline stage.

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]
I already fixed this in #55954, so it's a matter of deciding which one to merge. 😀

**Comment by BastiaanOlij** [comment]
> I already fixed this in #55954, so it's a matter of deciding which one to merge. 😀

Thats funny, even looks like you fixed it identically to what I did :) Sounds to me it's best if @reduz can check your PR and merge it as it contains many more fixes.

**Comment by akien-mga** [comment]
Let's merge this one as a doubly confirmed fix, while we wait for reduz to review the other fixed in Pedro's PR.

**Comment by akien-mga** [comment]
Thanks to you two :)

**Pull request merged**
