### PR TITLE
Add spaces to macros in memory.h to make C++11 compilers happy

### PR DESCRIPTION
**Pull request by Geequlim**

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@Geequlim Does the new version work in old compilers, and if so, wouldn't it be better to drop the `#if`?

**Comment by Geequlim** [comment]
@bojidar-bg I just tested with this code
```c++
#define __STR "ABC"
#include <iostream>
int main() {
  std::cout << "C++ version:" << __cplusplus << std::endl;
  std::cout << __STR "DEF" << std::endl;
  return 0;
}
```

And can be compiled with both GCC 6.1.1 and Clang 3.8.0 with `--std=c++98` option

I'm not sure it could works with old version compilers so I didn't drop the old version.

**Comment by bojidar-bg** [comment]
@Geequlim ~ Well, C++ shouldn't require no spaces for operations I think...

**Comment by Geequlim** [comment]
@bojidar-bg I think so. 
Should I remove the `#if` then?

**Comment by akien-mga** [comment]
I think you can remove the ``#if`` yeah, we'll have Travis testing the PR on a likely older GCC version anyway. But as @bojidar-bg mentioned, I don't expect compilers to break on it.

**Comment by Geequlim** [comment]
@akien-mga I have removed `#if` and pushed :)

**Comment by akien-mga** [comment]
Could you squash the two commits together? :)

**Comment by Geequlim** [comment]
@akien-mga Squashed.

**Comment by akien-mga** [comment]
Thanks :)

**Pull request merged**
