### PR TITLE
Reload kinematic shapes when changing PhysicsBody mode to Kinematic

### LINKED ISSUE #53125: [Bullet] body_test_motion causes crash when used with a Rigidbody in Kinematic mode and Bullet
### Godot version

3.3.stable

### System information

Windows 10

### Issue description

The issue is the same as in https://github.com/godotengine/godot/issues/51847, which was fixed in https://github.com/godotengine/godot/pull/50103, but for a RigidBody in Kinematic mode. This case is not fixed by https://github.com/godotengine/godot/pull/50103.

The same crash happens when calling kinematic methods of KinematicBody, when this body's mode has been changed to Rigid and back to Kinematic using the PhysicsServer.

### Steps to reproduce

Run the attached project

### Minimal reproduction project

[PhysicsBody_to_kinematic.zip](https://github.com/godotengine/godot/files/7236070/PhysicsBody_to_kinematic.zip)

### PR DESCRIPTION
**Pull request by BimDav**
This complements the PR https://github.com/godotengine/godot/pull/51857, as there is still a crash when changing the mode to Kinematic.

Reload kinematic shapes when changing PhysicsBody mode to Kinematic to prevent a crash when calling test_body_motion. 
Call reload_kinematic_shapes from init_kinematic_utilities as they are always called together.

*Bugsquad edit:* Fixes #53125.

### CODE REVIEW

**Comment by BimDav** [comment]
Fixes https://github.com/godotengine/godot/issues/53125

**Review by pouleyKetchoupp — COMMENTED** [review]
Thanks for finding the issue and fixing it!

It looks great. I was just wondering, why did you decide to revert the change to avoid calling `init_kinematic_utilities()` directly when switching to Kinematic mode? Was it causing issues in some cases?

**Comment by BimDav** [comment]
> It looks great. I was just wondering, why did you decide to revert the change to avoid calling init_kinematic_utilities() directly when switching to Kinematic mode? Was it causing issues in some cases?

It don't think it causes issues either way but I think that the majority of cases for a PhysicsBody in Kinematic mode may be the KinematicBody nodes. So in that case, I think it makes more sense to initialize everything needed by kinematic methods at the body's initialization, not at the first call of a kinematic method. It was also one less change so I thought it was less risky. But either way is OK with me!

**Comment by pouleyKetchoupp** [comment]
> 
> 
> > It looks great. I was just wondering, why did you decide to revert the change to avoid calling init_kinematic_utilities() directly when switching to Kinematic mode? Was it causing issues in some cases?
> 
> It don't think it causes issues either way but I think that the majority of cases for a PhysicsBody in Kinematic mode may be the KinematicBody nodes. So in that case, I think it makes more sense to initialize everything needed by kinematic methods at the body's initialization, not at the first call of a kinematic method. It was also one less change so I thought it was less risky. But either way is OK with me!

Alright, sounds good to me then :) It does make sense to just focus on fixing the crash in this PR.

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by pouleyKetchoupp** [comment]
Congrats on your first merged PR!

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Pull request merged**
