### PR TITLE
 Moved Local Space Mode and Transform Snap settings to Top Bar ...

### PR DESCRIPTION
**Pull request by SirPigeonz**
...buttons for easier access.

selection_049

### CODE REVIEW

**Comment by ZX-WT** [comment]
just wondering about the icon for local space mode, I think the meaning of icon is not obvious enough but I cannot think of a better icon, maybe it is just me, frequent user will know the function sooner or later, maybe I am just thinking too much.

**Comment by n-pigeon** [comment]
@ZX-WT 
New Icon is probably needed for now I borrowed ones that were OK from our rich icon library :D

**Comment by akien-mga** [comment]
CC @djrm

**Comment by djrm** [comment]
i dont think a icon for this is a good idea, i would put the "3D" icon and the word Global or Local, that would be clearer, the snap one is ok i think it is clear and used in the rest of the editor.

**Comment by n-pigeon** [comment]
I would stick to icon. No need for using a text. User will learn this icon very fast and icons are easier to distinguish that text.

**Comment by eon-s** [comment]
I also think that an icon is better for a workflow that is more visual (not in the rest of the universe).
The icon can be like the translation gizmo, rotated (or in 2 positions for local/global)

**Comment by djrm** [comment]
I wasnt saying just text i said icon + text, the reason for text is to be more discoverable, at least when it was in a menu you could read what it does, now you have to check the tooltip, of course users will learn it super fast, but the problem is first impression and how discoverable this is, but if you guy want to keep just the icon thats fine, im not sure if i would be able to do a local transform icon right now, but i will suggest using the environment one (the one that is like a world) to express the global coordinates on or off,

**Comment by eon-s** [comment]
Yes, can be nearly as cryptic as the "children lock" but can be solved with good documentation.

An icon is considered a "feature" for beta? Because there will be no other option than text only if this is going to be added now.

**Comment by djrm** [comment]
In any case icon wise i dont think its a good thing to add more icons, would be simpler to use the cube, and the globe one for object coords and global coords respectively, and not highlight it just toggling the icon.

**Comment by n-pigeon** [comment]
I've tried to resolve this but I had problems...
Will make clean patch soon. Sorry :(

**Comment by djrm** [comment]
also, apparently the current convention from such toggles is to show the action that will be performed, for example in the case of lock, it shows the lock icon meaning that if pressed it will lock the object, i think this has to be similar, show a globe to disable local_coords and show a box to enable them.

**Comment by n-pigeon** [comment]
OK I will redo this but unfortunately I will be available next week. :<

**Comment by groud** [comment]
For the lock, having the icon showing the action that is going to be executed as sometimes you might have a selection that includes locked and unlocked node (thus showing the current state would have needed a third icon, which might be a good idea).
For local/global I think it makes more sense to have the icon display the actual state.

**Comment by groud** [comment]
Also I think two different icons would be better: one for global, with a world or something like that, and one for local, with maybe a 3axis gizmo-like icon?

**Comment by djrm** [comment]
@groud, i agree it would be better to show the current state, but it might be confusing because other stuff shows the next state (example the list view or grid view in file system), currently is a bit inconsistent, also as i mentioned before it would be better to just use the object icon and the environment icon (a box and a globe) unreal does something like that, the local coords are also called object space so it makes sense.

**Comment by akien-mga** [comment]
So what should we do in the end? Discussion has stalled and this isn't merged yet :)

**Comment by akien-mga** [comment]
Merged manually as b3575b516 to solve merge conflict.

**Pull request closed without merging**
