### PR TITLE
Add outline to ruler tool

### LINKED ISSUE #33523: Ruler's text colour option does not exist in Editor Settings
**Godot version:**

_3.2 beta 1_

**OS/device including version:**

All

**Issue description:**

In the Editor Settings, there lacks an option to set the ruler's text colour.

**Steps to reproduce:**

Open the Editor Settings, look for an option to change the ruler's text colour.

### LINKED ISSUE #42988: Default color for ruler text with light theme to dark
**Godot version:**
v3.2.3.stable

**OS/device including version:**
Windows 10

**Issue description:**
The text for the ruler position with light theme is nearly invisible. It needs an other default color.

**Steps to reproduce:**
Switch to light theme, open a new empty scene, move the ruler and  look at the ruler text. 
Zwischenablage01

related to #33523?

### PR DESCRIPTION
**Pull request by KoBeWi**
Not sure about this tbh, but at least it solves an issue. It seriously triggered me.

Before:
image
After:
image

Probably resolves #33523 and resolves #42988

### CODE REVIEW

**Comment by Calinou** [comment]
Try adding a 1-pixel offset on each side of the backdrop so the text doesn't "touch" any of its edges. This may look a bit better.

**Comment by YeldhamDev** [comment]
Wouldn't be better for the text to just have a stronger outline?

**Comment by KoBeWi** [comment]
Ok, increased the rect by 1 pixel
image
but I can't push changes right now for some reason.

**Review by marcotmotta — APPROVED** [review]
I like the feature. Also good code formatting.

**Review by groud — APPROVED** [review]

**Comment by YeldhamDev** [comment]
Gonna sound like a broken record, but would be nice to have it be an outline instead. Would be subtler, and be consistent with #42995.

**Comment by groud** [comment]
Ah damn, sorry I didn't see your comment. Indeed, a simple oultine might be better IMHO.
It seems quite easy to implement too, so guess it makes sense.

**Comment by KoBeWi** [comment]
ytoghVmGOp
Is this alright?

**Comment by groud** [comment]
Could you maybe try with a slightly larger outline? It seems that in some cases the outline ends up not rendered.

**Comment by Calinou** [comment]
If you use an outline, consider using the bold font so that the "white" part of the font is more visible. Right now, the text isn't easy to read.

**Comment by KoBeWi** [comment]
0kcu9k9Pdp
It already uses the bold font.

**Comment by groud** [comment]
It's weird that the outline get such a a weird rendering. But anyway, I believe it's legible enough so that's fine to me.

**Comment by Ev1lbl0w** [comment]
I noticed this happening with the zoom label too some time ago. Apparently, the outline is "desync-ed" and is slightly smaller than the original text:
image
 *(top is the zoom label, the bottom is a label from a scene with the same font and outline settings)*

I have no clue why this is happening, I inspected some variables in the debugger, and the outline's size matched the font's size.

However, with the new [font rewrite](https://github.com/godotengine/godot/pull/41100), this was fixed, by changing to this:

```
zoom_reset->add_theme_constant_override("outline_size", 1);
zoom_reset->add_theme_color_override("font_outline_modulate", Color(0, 0, 0));
```

**Comment by KoBeWi** [comment]
Rebased. The new font changes made the code even bigger :/ but at least it looks much better now
image

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by GTcreyon** [comment]
Any chance of this being present in the next version? Perhaps I'm missing something, but it's definitely not here right now.

**Comment by KoBeWi** [comment]
This was never backported to 3.x, because it uses some functionality that doesn't exist there. It would need a separate PR.

**Pull request merged**
