### PR TITLE
Add PhysicsMaterial icon

### PR DESCRIPTION
**Pull request by MewPurPur**
image

It's the class that determines the friction and bounciness of surfaces.

### CODE REVIEW

**Comment by Calinou** [comment]
Should the 3 lines at the top be blue, similar to other physics-related classes?

Other than that, this looks great to me :slightly_smiling_face:

**Comment by MewPurPur** [comment]
Might be a good idea, I'm thinking maybe the whole top surface should be blue too, to highlight the relevant part.

**Comment by Calinou** [comment]
> Might be a good idea, I'm thinking maybe the whole top surface should be blue too, to highlight the relevant part.

Sounds good.

**Comment by MewPurPur** [comment]
image

**Comment by MewPurPur** [comment]
I pushed the bluish version.

I know it changes all surfaces, but the idea of the icon isn't to be descriptive. The whole thing can't be blue because that's reserved for Shape2D and Shapre3D resources, which this shouldn't look similar to.

**Comment by MewPurPur** [comment]
image

Changed it to this because the blue is meant to be a highlight and looked bad in light theme.

**Review by Geometror — APPROVED** [review]
Looks nice!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
