### PR TITLE
Moved OS::set_cmdline

### PR DESCRIPTION
**Pull request by jeronimo-schreyer**
OS::set_cmdline sets executable path, which is then used in ProjectSettings::_setup (which is called by ProjectSettings::setup)

in project_settings.cpp:350
`String exec_path = OS::get_singleton()->get_executable_path();`
In such case get_executable_path() always returns ""

### CODE REVIEW

**Comment by akien-mga** [comment]
Doesn't that break the editor? https://github.com/godotengine/godot/pull/33802/files#diff-395c1089ded171b1757742cab9e7297dR912

**Comment by jeronimo-schreyer** [comment]
argument --editor will be added if tools=yes

**Comment by aaronfranke** [comment]
@jeronimo-schreyer Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by aaronfranke** [comment]
This PR has been abandoned by its author, no response for over 2 months. Closing.

**Pull request closed without merging**
