### PR TITLE
Fix incorrect HTC action map entries

### LINKED ISSUE #74929: Unsupported paths being reported in OpenXR
### Godot version

4.0.stable

### System information

Windows

### Issue description

Using SteamVR the following errors are logged due to mismatches in the default action map

image

### Steps to reproduce

Run an OpenXR project on SteamVR

### Minimal reproduction project

Any basic OpenXR project will do, but easy to test with https://github.com/GodotVR/godot-xr-tools

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Fixes #74929

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Note for testing, you will need to recreate the action map!

**Comment by BastiaanOlij** [comment]
Obtained feedback on Discord that this is working as advertised, should be fine to merge.

**Comment by BastiaanOlij** [comment]
@akien-mga I think we can safely merge this one

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
