### PR TITLE
Fix setting the space of a RigidBody.

### LINKED ISSUE #22823: Bullet warning when PhysicalBone is deleted
**Godot version:**

3.1 master -> f12cb82

**OS/device including version:**

Windows 10 Home

**Issue description:**

When a PhysicalBone is deleted, a warning appears:

```
WARNING: RigidBodyBullet::assert_no_constraints: A body with a joints is destroyed. Please check the implementation in order to destroy the joint before the body.
At: modules\bullet\rigid_body_bullet.cpp:442   
```

**Steps to reproduce:**
`queue_free` a `PhysicalBone` node (or any of its parents) that is attached to a skeleton.

**Minimal reproduction project:**

[physical-bones-crash.zip](https://github.com/godotengine/godot/files/2430780/physical-bones-crash.zip)

Same project as #22538 - the warnings happen, but currently the editor crashes afterwards for me.

### PR DESCRIPTION
**Pull request by J08nY**
Fixes #22823 crash, which SEGVed because it was dereferencing NULL.
Furthermore, should fix the warning, as now the constraints are moved from one space to the other.

### CODE REVIEW

**Comment by akien-mga** [comment]
Nice to see you around again @J08nY :)

Some style fixes needed: https://travis-ci.org/godotengine/godot/jobs/438383778
(You'll need `clang-format` 6+ for the current style guide.)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by akien-mga** [comment]
Looks like we hadn't properly identified that this PR fixed #22538, which @AndreaCatania just fixed with #23430, so the first commit is no longer needed.

@AndreaCatania Could you review the second commit?

**Comment by akien-mga** [comment]
@J08nY Does the second commit actually fix #22823 (the warning part)?

**Comment by J08nY** [comment]
> @J08nY Does the second commit actually fix #22823 (the warning part)?

The warning is definitely not displayed then, the commit removes it and attempts to do the sensible thing instead of failing and warning. However I am not sure if what it does is actually a good solution to the problem as I don't understand the code that well. @AndreaCatania may comment?

**Comment by AndreaCatania** [comment]
I set that warning because I was unsure if Godot was managing the joint addition and removal.

This code doesn't solve the problem at 100%, because it's not possible restore joints in this way.
A bit more work is required.

I can be more detailed if you plan to work on it

**Comment by akien-mga** [comment]
Based on @AndreaCatania's comment, it seems this fix is incomplete, so closing. Further discussion should be in #22823.

Note that the crash fix mentioned in this PR has already been done separately as #23430.

**Pull request closed without merging**
