### PR TITLE
Improved default colors for the new theme 

### PR DESCRIPTION
**Pull request by nunodonato**
Improved default colors for the new theme as requested by @volzhs (inspiration from solarized themes)

### CODE REVIEW

**Comment by akien-mga** [comment]
You can't make such a PR without showing before/after screenshots :)

**Comment by nunodonato** [comment]
before

screenshot from 2017-05-24 17-24-17

after

screenshot from 2017-05-24 17-23-13

it's really not a matter of better or worse, but of personal preference. Perhaps we can ship a few predefined themes like some code editors usually do ;)

**Comment by akien-mga** [comment]
I like it personally, it's refreshing. We can always rechange it later on if we think something different is better.
Having several presets would be pretty nice indeed, so that it's easy to pick known good-looking configs.

CC @djrm @volzhs @toger5 for opinions :)

**Comment by volzhs** [comment]
@nunodonato color feels like auto level applied on photoshop.
I like a little desaturated but it's fine with me. we can now change it to whatever (but not too bright) :smile:

**Comment by nunodonato** [comment]
Update: Also moved the theme settings to the Interface category.

**Review by akien-mga — APPROVED** [review]

**Comment by toger5** [comment]
I think this as the default color is amazing. there were a lot of ppl out there who liked the blueish look. I think it blue is also good for branding.
I know those are small points, but since it is soo easy to change they still might be the best choice.

ever tried the colors from alelepd ?

**Comment by nunodonato** [comment]
I worked on adding a few presets. Not adding it to this PR because I dont know if this is desired or not. feel free to comment

preset

**Comment by toger5** [comment]
@nunodonato nice I love it.
I this is amazing. I don't like the current godot 3 color set. Preferred what you posted before. (or maybe actually use the colors form UI Concept thread) But I think thats not the point you are trying to make. having presets is great!

**Comment by toger5** [comment]
what happenes If I change the color for one of the presets?

**Comment by nunodonato** [comment]
@toger5 I dont think I changed the colors.. perhaps is due to the GIF?

Ideally it would automatically switch to custom, but it doesnt do that and I'm not sure if thats possible. So the colors are only used when custom is selected, the presets are hardcoded.
Perhaps it could be better to rename the labels to "Custom Base Color", etc...?

**Comment by HummusSamurai** [comment]
@nunodonato Indeed I think it's due to the GIF changing the colors, and the blue theme is pretty amazing.

I think "Custom" is fine since the drop-down menu is already labelled "Color Preset".

**Comment by nunodonato** [comment]
@volzhs as you can see by the GIF above, there is a "Theme" field in the Theme category, which takes an INT. I have no idea where that thing comes from... I didn't notice if it was after your PR or mine. Can you check how it ends up there? :)

**Comment by volzhs** [comment]
@nunodonato did you try to remove `~/.godot/editor_settings-3.tres`?

**Comment by nunodonato** [comment]
@volzhs that solved it. funny enough, my godot is back to a grey theme...

**Comment by volzhs** [comment]
@nunodonato hm... the default color is not grey as this pr merged.
it should be your color after deleting `~/.godot/editor_settings-3.tres`...

**Comment by nunodonato** [comment]
@volzhs it worked after I changed it in editor_settings.cpp it still had the grey colors there

**Pull request merged**
