### PR TITLE
Improve the `File.store_{8,16,32,64}()` documentation

### PR DESCRIPTION
**Pull request by dalexeev**
Added information about the intervals of values that the functions
`store_{8,16,32,64}()` can correctly write to the file.

### CODE REVIEW

**Comment by Calinou** [comment]
Does the current implementation print errors when trying to write values outside the allowed range? If not, we should probably add error messages in a separate PR.

**Comment by dalexeev** [comment]
No, it just overflows without any warnings.

```gdscript
func _run():
    var f = File.new()
    f.open('user://test', f.WRITE)
    f.store_8(-5)
    f.store_16(-5)
    f.store_32(-5)
    f.close()
    f.open('user://test', f.READ)
    print(f.get_8())
    print(f.get_16())
    print(f.get_32())
    f.close()

# 251
# 65531
# 4294967291
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
