### PR TITLE
Implement animation compression

### PR DESCRIPTION
**Pull request by reduz**
Roughly based on https://github.com/godotengine/godot-proposals/issues/3375 (used format is slightly different).

* Implement bitwidth (compression of octahedral mapped rotation deltas) and page based animation compression (see animation.h for format).
* Can compress imported animations up to 15-20% of their original size.
* Compression format opens the door to streaming.
* Works transparently (happens all inside animation.h)

Algorithm is described in the comments of animation.h

**Why bitwidth over curve fitting?**
* Simpler
* Faster compression
* Faster decompression
* Better all rounder, and better suited for mocap (jittery data makes curve fitting inefficient).
* More easily allows paging, for better cache coherency and ability to stream.

I experimented with octahedral and spherical mapping. While spherical mapping has the advantage of less discontinuity when wrapping around, the compressor does a good job of isolating the transients (border crossings), so it matters little in practice, as they don't happen as often.

**NOTE** Seems to work in everything I tested, but try at your own risk.

### CODE REVIEW

**Comment by jordo** [comment]
Thanks for documenting the compression format.  I would put a version byte (or uint32_t) header at the start of the encoding (you could start with 0x1).  If someone changes or updates the encoding format in the future (maybe you need a few extra bytes of precision sometime in the future), there is an easy check and migration path for any data stored in a previous encoding version to a newer one.

**Comment by reduz** [comment]
@jordo 
>  I would put a version byte (or uint32_t) header at the start of the encoding (you could start with 0x1). 

Makes sense, but I suppose I can just put it in the Compression dictionary that gets serialized. Will add it before getting the PR out of draft.

**Comment by fire** [comment]
I saw that the compressed track is not on by default. Does this means https://github.com/godotengine/godot/pull/51341 needs work?

**Comment by reduz** [comment]
@fire It would be nice to do some performance measurements on how fast the compressed track is vs the regular one, if the performance is not affected as much we could make it default, but I think this is likely better in a subsequent PR.

**Comment by fire** [comment]
1. The option can be difficult to find in menus to turn on compression. so it should be defaulted to off for the sake of people animating.
2. We should be able to default compress on in the default settings. 
3. With this pr merged we can default to 30fps. 🦖

**Review by lyuma — APPROVED** [review]
Reviewed together with @fire 

I don't think there is anything we should do about this right now, since it's not called at runtime.... but `_fetch_compressed_by_index` appears to be linear time complexity.

It may be good to note that fetching all indices using a function like `position_track_get_key` in a loop on a compressed track would take O(N^2) time total.

Had a discussion in rocket chat that we should document how to calculate the tolerance and when to use uncompressed.

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
