### PR TITLE
Fix renderer sometimes not applying "unshaded" flag (2.1)

### PR DESCRIPTION
**Pull request by elasota**
Fixes shading conditionals not being updated when 2 consecutive objects have the same receive shadow flag and light type, but different unshaded flags (example: a Sprite3D and a TestCube in a scene with no lights).

### CODE REVIEW

**Comment by bojidar-bg** [comment]
LGTM, but I would like @RandomShaper or some other person knowledgeable of the gles2 renderer give it a look.

**Comment by RandomShaper** [comment]
LGTM too.

**Comment by akien-mga** [comment]
Is that fix relevant for the master branch too?

**Comment by elasota** [comment]
The same code exists in master's gles2 renderer (but not gles3), so I'd imagine so, but I haven't tested it there.

**Comment by RandomShaper** [comment]
I think all the stuff in the 'gles2' dir in the 'master' branch will never
get into the build.

I'm not sure why it's being kept. Maybe for using it as a reference for the
time when Godot 3.x supports GL ES 2.0.

It would be good to know that for sure so people still contributing to the
2.1 renderer knows whether they should change that code as well. Or maybe
instead, when that time comes, the whole 'gles2' dir can be picked from the
'2.1' branch with everything that has changed in the meantime.

**Pull request merged**
