### PR TITLE
Move all logos from the root directory to a separate folder

### PR DESCRIPTION
**Pull request by C-BJ**

### CODE REVIEW

**Comment by C-BJ** [comment]
I'm a novice in Godot source code, so I can only try the only possibility I think to fix CI errors

**Comment by akien-mga** [comment]
What's the motivation / proposal for this change?

The organization of files and folders in the repository is something that the maintainers take care of, so a first-time contributor proposing to move files around without justification is a bit difficult to review.

**Comment by C-BJ** [comment]
> What's the motivation / proposal for this change?
> 
> The organization of files and folders in the repository is something that the maintainers take care of, so a first-time contributor proposing to move files around without justification is a bit difficult to review.

Sorry, I thought at first that the logo in the root directory was not used in src

**Comment by C-BJ** [comment]
maybe, close it?

**Comment by akien-mga** [comment]
I would close it for now yes.

For the record, we did discuss a while ago that some of the files in the root folder could be moved around to reduce the number of folders+files in the root, but that includes not only the logos but also some of the python files (and the LOGO license file I guess). I'll work on this at some point probably.

**Pull request closed without merging**
