### PR TITLE
Fix project icon align (2.1).

### PR DESCRIPTION
**Pull request by dkrutskikh**
Now project icon vertically centered

### CODE REVIEW

**Comment by groud** [comment]
Looks like your commit is not authored with the email address you use with github.

**Comment by DmitryKrutskikh** [comment]
@groud fixed

**Comment by akien-mga** [comment]
Is this relevant for the master branch too?

**Comment by groud** [comment]
> Is this relevant for the master branch too?

It probably should be added in 3.0 at line 1040 of project_manager.cpp.

**Pull request merged**
