### PR TITLE
fixed margin beeing squared

### PR DESCRIPTION
**Pull request by toger5**
screen shot 2017-09-12 at 23 23 52

looks like this on hiDpi before.
ping @djrm (just you know I did a pr for it)

### CODE REVIEW

**Comment by toger5** [comment]
by the way. what is causing the border at the right of the viewport?

**Review by djrm — APPROVED** [review]

**Comment by djrm** [comment]
that border is something, havent seen it before.

**Comment by toger5** [comment]
probably has something to do with how the vieport size gets generated...

**Comment by djrm** [comment]
@toger5 it has a problem even on standard DPI

**Comment by toger5** [comment]
the border on the right of the viewport?

**Comment by toger5** [comment]
true...
screen shot 2017-09-13 at 00 12 53
looks interesting and wanted to share it anyways... but the important part is the border on the right.

**Comment by toger5** [comment]
found it !
```
	style_content_panel_vp->set_default_margin(MARGIN_LEFT /*look here */, border_width);
	style_content_panel_vp->set_default_margin(MARGIN_TOP, default_margin_size);
	style_content_panel_vp->set_default_margin(MARGIN_LEFT /*and here*/, border_width);
	style_content_panel_vp->set_default_margin(MARGIN_BOTTOM, border_width);
```

**Pull request merged**
