### PR TITLE
Implement shadow to opacity

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Seeing @bzztbomb is busy I've taken PR #25686 and added the suggestions from Reduz in. I did have to invert the logic or else using a spotlight or omni light would result in mostly shadows even if there is a directional light.

This works pretty nicely, there are a few small issues still to resolve:
- for some reason changing the new flag on SpatialMaterials does not trigger a recompile of the shader. I can't find out why now. Change any of the others and it triggers it just fine
- if you create a ShaderMaterial you must assign ALPHA in the fragment shader or it won't trigger transparency
- for omni and spot lights ignore energy so using a brighter light does not change opacity

But as an approximation for use in AR, this works really well. 

Also I couldn't test this for GLES2, for some reason shadow buffers are broken on Mac.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
From IRC:
> reduz
> Akien: I really wonder if there is no other way to do this
> like rendering to a magenta texture :P but hard as I try I can't think of a workaround
> this is only and purely useful for AR and nothing else
> and AR is kind of big use case, so it may be better to merge
> i dont like the alpha_  variable, wonder if it could be renamed
> Akien
> Yeah `alpha_` seems awkward. Mux213: feedback for you above ^

alpha_ was simply chosen because naming the variable we're parsing in alpha makes more sense, the existing variable needed to be renamed. I am totally for suggestions for another name, it was late and I was tired :P

**Comment by BastiaanOlij** [comment]
alpha_ was renamed to alpha_ggx

Anything else we feel needs to change here?

**Comment by clayjohn** [comment]
Were you able to trigger transparency even when ALPHA was written to in the light shader?

**Comment by BastiaanOlij** [comment]
> Were you able to trigger transparency even when ALPHA was written to in the light shader?

If you write your own light shader (so don't use the new render mode) then yes, it will trigger the logic. But if you use the new render mode it doesn't find ALPHA in the shader text and thus does not trigger Godot treating the material as a transparent material and not setting blend mode

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
