### PR TITLE
Fix PackedScenes created with PackedScene.pack() have their exported nodes become null

### LINKED ISSUE #73315: PackedScenes created with `PackedScene.pack()` have their exported nodes become `null`
### Godot version

4.0.rc2

### System information

Ubuntu 22.04.1 LTS

### Issue description

Like the title says. I expect the nodes to be converted to node paths after packing, and then swiftly restored.

### Steps to reproduce

Add exported node variables to a node. Then pack that node into a PackedScene and instantiate it again.

Or just download the MRP, read `Shrek.gd`, and run it and see what's printed.

### Minimal reproduction project

[pack() bug.zip](https://github.com/godotengine/godot/files/10737654/pack.bug.zip)

### PR DESCRIPTION
**Pull request by MewPurPur**
Fixes #73315 as per KoBeWi's comment. I have no idea what I'm doing here, so I hope this is the exact proper solution, I'll not be able to make major modifications if request arises.

Tested it on my game and I didn't encounter any regressions. But tbh I don't exactly know what kinds of regressions I should be looking for...

### CODE REVIEW

**Comment by MewPurPur** [comment]
Looked at the blame and saw it's Juan's code. Since KoBeWi was confused on why it'd be implemented like this, maybe Juan should be the one to take a look?

**Review by KoBeWi — APPROVED** [review]
Doesn't seem to have any adverse effects (or at least nothing obvious xd).

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Yeah I think if we want #73256 in 4.0.x eventually, it would likely require a dedicated PR with all the relevant cherry-picks. There have been a lot of intertwined changes to PackedScene like this one.

**Comment by YuriSizov** [comment]
Regarding the cherry-pick, see my comment here: https://github.com/godotengine/godot/pull/76378#issuecomment-1594812425. We recommend updating to 4.1 if this issue greatly affects you.

**Pull request merged**
