### PR TITLE
Fix npot(not power of two) dds texture loading bug

### PR DESCRIPTION
**Pull request by sanikoyes**
Fix npot(not power of two) dds texture loading bug
Use squish::DecompressImage to decompress BC1/BC2/BC3 image

### CODE REVIEW

**Comment by sanikoyes** [comment]
@akien-mga ok,i was removed commented code

**Comment by akien-mga** [comment]
It looks like it still fails building on android: https://travis-ci.org/godotengine/godot/jobs/115798795

Could you also merge all commits into one?

**Comment by akien-mga** [comment]
Could you merge all commits into one for clarity? Hotfixes for compilation issues are not needed to keep in the history, they can be squashed in the original commit.

I'll let @reduz review this one though, as it adds squish to all non-tools build, and seems to use and embed ``<algorithm>`` from the STL.

**Comment by sanikoyes** [comment]
Ok, close this pull request
merged to https://github.com/godotengine/godot/pull/4078

**Pull request closed without merging**
