### PR TITLE
Fix HSV Rectangle Wheel not allowing to set 255

### PR DESCRIPTION
**Pull request by sriramun**
Solves #60303 
Removed margin that caused miscalculations in brightness (HSV).

### CODE REVIEW

**Comment by sriramun** [comment]
I don't think I've understood what the original margins were intended for. This fixes the issue in particular, but maybe I'm missing something else?

**Comment by KoBeWi** [comment]
The margin is visible here:
image

When you remove it, the wheel is closer to the color bar and no longer centered.
image

Also the `wheel_margin` node is useless without the margin.

Perfectly we should find a way to keep the margin and fix the input.

**Comment by akien-mga** [comment]
The linked issue seems fixed in 4.0 RC 1, so this is likely not needed anymore.

**Comment by KoBeWi** [comment]
The issue is not fixed, but the PR wasn't correct anyway and stale.

**Pull request closed without merging**
