### PR TITLE
Make VisualScript check inheritance for port info

### LINKED ISSUE #32656: Visual Script Variable issue
**Godot version:**
Godot 3.2 Alpha official release

**OS/device including version:**
Windows 10

**Issue description:**
Some nodes when created pick "Any" as their type, instead of the types they should be (vector3 for translations, rotations etc) which limit the options when dragging the output to make new nodes in case of getter nodes, and in case of setter nodes force the use of variables even if you want to set a fixed value for that node

**Steps to reproduce:**
1. Create a Visual Script
2. Create a Getter or a Setter node (Some recognize type just fine, some don't, like most under spatial don't)
The result:
Godot VS variable bug
(The Deconstruction node was made via standard node creation, not via output creator for the get rotation node)

**Minimal reproduction project:**
[Project.zip](https://github.com/godotengine/godot/files/3704106/Project.zip)

### PR DESCRIPTION
**Pull request by aaronfranke**
Fixes #32656, I don't think it breaks anything, it works fine on the Visual Pong demo.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @swarnimarun @fire

**Comment by fire** [comment]
This usage in https://github.com/godotengine/godot/blob/784595fda1ab1c933888da688a6debcf785e3fec/modules/visual_script/visual_script_property_selector.cpp#L142-L151 looks suspicious too.

I compiled and the pr does what it says.

**Comment by fire** [comment]
The visual_script_property_selector.cpp change is a different position and probably a different bug so, this patch solves the original problem. Looks good.

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
