### PR TITLE
Fix stringification of Projection

### PR DESCRIPTION
**Pull request by akien-mga**
Draft because I'd like #99545 to be merged first (with only the Vector4 fix), and I'll rebase so the GDScript test properly has the `.0`s.

Before:
```

1.0, 0.0, 0.0, 0.0
0.0, 1.0, 0.0, 0.0
0.0, 0.0, 1.0, 0.0
0.0, 0.0, 0.0, 1.0
```

After (draft):
```
[X: (1, 0, 0, 0), Y: (0, 1, 0, 0), Z: (0, 0, 1, 0), W: (0, 0, 0, 1)]
```

After (once #99545 will be merged):
```
[X: (1.0, 0.0, 0.0, 0.0), Y: (0.0, 1.0, 0.0, 0.0), Z: (0.0, 0.0, 1.0, 0.0), W: (0.0, 0.0, 0.0, 1.0)]
```

### CODE REVIEW

**Comment by Mickeon** [comment]
Doesn't changing the way Variants are converted to string, to a certain extent, break compatibility?

**Comment by AThousandShips** [comment]
I'd say there's a significant difference between `var_to_str` and just stringification, though the visual stringification does matter to users to some degree I think it's something you should handle formatting wise if you are interested in a particular format

**Comment by akien-mga** [comment]
Rebased on top of #99545.

> Doesn't changing the way Variants are converted to string, to a certain extent, break compatibility?

Yeah this could be considered a breaking change to some extent, but the change to stringification of floats already broke the format for Projection in 4.4, so we might as well go all the way.

**Review by KoBeWi — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
