### PR TITLE
[Linux/BSD] Include headers for dynamically loaded libraries to simplify build dependencies.

### LINKED ISSUE #67863: DisplayServer.tts_get_voices() returns empty on Linux with official binaries
### Godot version

4.0.beta3

### System information

Linux Xubuntu 22.04.01

### Issue description

DisplayServer.tts_get_voices() returns empty. For example, print(DisplayServer.tts_get_voices()) prints "[]".

Speech Dispatcher is installed (spd-say 0.11.1), spd-say -L returns a long list of voices, spd-say "hi" says hi as expected.

### Steps to reproduce

print(DisplayServer.tts_get_voices())

### Minimal reproduction project

[TTSexample.zip](https://github.com/godotengine/godot/files/9858039/TTSexample.zip)

### PR DESCRIPTION
**Pull request by bruvzg**
Includes headers and licensing information for the libraries wrapped by https://github.com/hpvb/dynload-wrapper and dynamically loaded.
- Simplify build dependencies, since libs are loaded dynamically, there's no reason to have the full library (and all of its dependencies) on the system used to build.
- Ensures that wrappers and headers have the same version, Ubuntu 18.04 LTS (bionic) versions are used.
- Adds missing licensing and version information for dynamically loaded libraries.

Fixes https://github.com/godotengine/godot/issues/67863 (and similar issues with build environment setup).

### CODE REVIEW

**Comment by hpvb** [comment]
This is a good idea! I like it.

**Comment by akien-mga** [comment]
I think this is great!

The only thing I'm unsure of is the whole license/copyright documentation situation. If we're vendoring the headers it definitely makes sense to include a license file next to the headers to make it clear what terms this specific code is under.

But I don't see how using library headers from a vendored copy, or the ones provided on the build environment, would differ in practice - the same header code gets included in the Godot binary. So if we weren't documenting the license terms of all dlopen'ed libraries or system headers used by Godot code in `COPYRIGHT.txt` before, I don't think we ought to document them now.

It does make me doubt whether we should actually have been documenting these licenses all along, and that's something I'll try to get clarified with open source licensing experts. If we have to, I've basically never seen a project do this _ever_, whether open source or proprietary, so this would be an interesting situation.

So for this PR I'd suggest:
- Move all Linux library headers in the same folder to avoid adding too many folders in `thirdparty`. Maybe `thirdparty/linuxbsd_headers/`.
- Document the versions etc. of those libraries in `thirdparty/README.md` all together under the `## linuxbsd_headers` section. Can be kept simple like for the `## misc` section since the update instructions are trivial and don't need to be mentioned.
- Don't list them in `COPYRIGHT.txt`.

As a side note, would be worth checking if we really needed to include the full set of headers or if we can get away with only a subset (i.e. the ones we include directly + their dependencies, if that's not the whole set).

**Comment by bruvzg** [comment]
Added X11 headers, moved headers to `thirdparty/linuxbsd_headers/` alongside with own README file to list versions, and removed from COPYRIGHT.txt.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
