### PR TITLE
Replace usleep with nanosleep

### PR DESCRIPTION
**Pull request by Rubonnek**

### CODE REVIEW

**Comment by reduz** [comment]
I don't really see the point of doing this, what's the logic behind?

**Comment by Rubonnek** [comment]
At first I did it simply because `nanosleep` responds faster to signal handlers, but I should not have touched none of this code. I don't want to mess with the joystick nor the sound.

I shouldn't code this early in the morning.

**Comment by reduz** [comment]
Oh don't worry. In general what I meant is that for most OSs, you actually
want to use at much usleep (or windows Sleep). The more they can usually
sleep is their internal
kernel tick size (I think 1ms on Linux and OSX and 10ms on Windows), so
using less does not make much sense in general.

**Comment by Rubonnek** [comment]
I see. That's good to know. Thanks a lot.

**Pull request closed without merging**
