### PR TITLE
[C#] Fix `Encloses` failing on shared upper bound for `AABB` and `Rect2(I)`

### PR DESCRIPTION
**Pull request by AThousandShips**
C# version of:
* https://github.com/godotengine/godot/pull/87118
* https://github.com/godotengine/godot/pull/32478
* https://github.com/godotengine/godot/pull/57469

3.x version:
* #87265

### CODE REVIEW

**Review by raulsntos — APPROVED** [review]
LGTM. Thanks!

**Comment by YuriSizov** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank you!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
