### PR TITLE
Add android export error on invalid package name

### PR DESCRIPTION
**Pull request by lethiandev**
Fix for https://github.com/godotengine/godot/issues/7877

These changes provide package name validation. Shows an error on unacceptable package name that causes a package parsing problem. The validation pattern base on https://developer.android.com/studio/build/application-id

Some example screenshots:
image
image

### CODE REVIEW

**Comment by LikeLakers2** [comment]
Perhaps the error message could be a little more descriptive? It'd be nice if the user had some indication of what to fix about the package name. Even if that involved just linking them to https://developer.android.com/studio/build/application-id (but I don't think that's a good idea)

**Comment by akien-mga** [comment]
That also fixes part of #23172, we should probably list all other properties that need to be validated.

**Comment by lethiandev** [comment]
@LikeLakers2 Ok, I've added more informative error messages, Android Studio users should be familiar with those errors.
androidexport001

@akien-mga Yeah, it'd be nice to see a robust export form for each platform, thanks for linking the related issue.

**Comment by LikeLakers2** [comment]
@lethiandev Looking through the changes, those error messages seem fairly reasonable. I approve. :) That should make it a lot easier to know what's wrong with the package name.

That said, I noticed you used `$genname` in the gif, and the error about the `$` disappeared. Does `$genname` get replaced with something else?

**Comment by lethiandev** [comment]
@LikeLakers2 Yes, $genname is replaced by the `get_package_name` function, it's just stripped version of the _Name_'s field under the _Unique Name_ one. If the field is empty, it's "noname" instead.

I copied messages direct from the Android Studio IDE, someone familiar with AS can feel like at home.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we don't plan to cherry-pick new features and enhancements to the 3.0 branch, unless there is very strong support in favor of it. Removing cherrypick label for 3.0.

**Pull request merged**
