### PR TITLE
Add clipboard image data get/set methods

### LINKED ISSUE #2949: Better Clipboard Support
### Describe the project you are working on
My project's user inputs are images. The planned ways to accept said images are:
1: Dragging an image into the application,
2: Clicking the image well to open a `FileDialog`, and
3: Pasting from the Clipboard

### Describe the problem or limitation you are having in your project
Currently, you can only grab `String`s from the Clipboard. Image data, files, or really anything else? Nope!

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Updating Clipboard support to include additional formats (image data, sounds, videos, etc.) would help people a lot.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
```gdscript
var clipboardImage = OS.get_clipboard()
if clipboardImage is Image:
    #do image things
else:
    #hey wait this isn't an image
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Currently, no, because you can only grab `String`s from the Clipboard.

### Is there a reason why this should be core and not an add-on in the asset library?
In my honest opinion, features that use/require system data should be core. Something as simple and useful as, for example, `OS.get_screen_size()`, shouldn't be separate from the rest of the OS functions

### PR DESCRIPTION
**Pull request by radzo73**
Closes https://github.com/godotengine/godot-proposals/issues/2949.

Explanation of implementations:
 - Windows (get): First checks if there is a PNG in the clipboard, then if there is a DIBv5 in the clipboard, and then if there is a DIB in the clipboard.
 - Windows (set): Loads as a PNG to the clipboard, and as a DIBv5.
 - Mac (get): Converts to a PNG and returns it.
 - Mac (set): Loads the Image (thank you `_convert_to_nsimg()`, very cool) to the clipboard.
 - iOS (get): Converts to a PNG and returns it.
 - iOS (set): N/A (wish you were here, `_convert_to_nsimg()`)
 
Unsupported (because I don't know how to):
 - Web
 - Android
 - X11
 - Wayland (cc @Riteo how's it going)
 - UWP

### CODE REVIEW

**Comment by KoBeWi** [comment]
How is this PR related to #63826? (aside from implementing `set` method)

**Comment by radzo73** [comment]
Main difference is that my PR has the `set_clipboard_image()` method.
My initial PR was #76603 (which I started because #63826 hadn't had any progress since August 2022), which didn't end out working.
(I actually had no idea @deakcor was still working on their branch)

**Comment by deakcor** [comment]
> This PR adds a set method but the other one was much more reviewed and approved... Perhaps the two could be merged together, implementing a set method there?
Yes this PR seems an improvement of mine, there is similar base for a lot of code I think (?). All the checks passed mine and it was validated so maybe we could merge then rebase this one to get rid of duplicated code. If you have an other idea which require me to do an action let me know.

**Comment by YuriSizov** [comment]
https://github.com/godotengine/godot/pull/63826 was merged. This can now be rebased.

**Comment by radzo73** [comment]
#63826 got merged, which means it's time for me to rebase
gonna re-add the set methods
Also, what are the thoughts on merging `String clipboard_get_text()` and `Image clipboard_get_image()` into `Variant clipboard_get()`? (and, likewise, the `set`methods)

**Comment by YuriSizov** [comment]
> Also, what are the thoughts on merging `String clipboard_get_text()` and `Image clipboard_get_image()` into `Variant clipboard_get()`? (and, likewise, the `set`methods)

I don't think merging them would be extremely useful. If there is a demand, we can add a generic method in addition to these more specific ones, but there is no good reason to replace them.

**Comment by Zireael07** [comment]
Is this merged or not? The site seems to be confused...

**Comment by KoBeWi** [comment]
Another similar PR was merged.

**Comment by lostminds** [comment]
> Also, what are the thoughts on merging `String clipboard_get_text()` and `Image clipboard_get_image()` into `Variant clipboard_get()`? (and, likewise, the `set`methods)

@radzo73 If you're interested in further improving pasteboard support in Godot perhaps you have some thoughts on this proposal https://github.com/godotengine/godot-proposals/issues/7899 . In short basically proposing to instead move the access of clipboard data into a new separate global Clipboard object, to enable more general access of multiple parallell data types on the clipboard. Basically to have it work more like macOS NSPasteboard and Windows system Clipboard class.

On a more specific note regarding the macOS implementation, I think it would be worth moving away from the specific data formats specified now like `[pasteboard availableTypeFromArray:[NSArray arrayWithObjects:NSPasteboardTypeTIFF, NSPasteboardTypePNG, nil]];` etc. And instead use the NSImage method `[NSImage canInitWithPasteboard:[NSPasteboard generalPasteboard]]` to check if it's possible to create an NSImage from whatever data or formats are available on clipboard and then create it with `nsImage = [[NSImage alloc] initWithPasteboard:[NSPasteboard generalPasteboard]]`.

This would mean it'll support all image formats the system can handle. However it also means the NSImage might not be a bitmap format, so it might not have a NSBitmapImageRep. However, all NSImages can be converted to tiff bitmap data using `tiffData = [nsImage TIFFRepresentation]` (sadly not png directly), and then you can use that to create a NSBitmapImageRep with `nsbitmapImageRep = [NSBitmapImageRep imageRepWithData: tiffData]`. And then finally get the png data from that just like the current implementation using `[nsbitmapImageRep representationUsingType:NSPNGFileType]`

For setting image data to the pasteboard on macOS (and iOS) you shouldn't need to do a conversion to an NSImage (as the _convert_to_nsimg above implies). Just using `NSPasteboard setData:data forType:NSPasteboardTypePNG` or the corresponding `UIPasteboard setData:forPasteboardType:` method for iOS should let you set the raw PNG data directly to the pasteboard. This is assuming you can get the png data you can get from Godots `Image.save_png_to_buffer` into an NSData object, but that might be done somewhere else in the codebase.

**Comment by radzo73** [comment]
Closing this in favor of a new PR inspired by https://github.com/godotengine/godot-proposals/issues/7899 whenever I get around to working on it.

**Comment by lostminds** [comment]
> Closing this in favor of a new PR inspired by [godotengine/godot-proposals#7899](https://github.com/godotengine/godot-proposals/issues/7899) whenever I get around to working on it.

Hello @radzo73 have you had time to do any work on this? There is a new PR https://github.com/godotengine/godot/pull/86021 aiming to implement this, but the contributor behind that seems to have run into some issues I think on the linux implementation and it seems work on it has stopped. Perhaps you could take a look if you're familiar with this area?

**Pull request closed without merging**
