### PR TITLE
Make editor's shortcut names translated on-site

### PR DESCRIPTION
**Pull request by timothyqiu**
When it's necessary to translate the name of a shortcut, the in-game solution is to automatically translate it when it's displayed (e.g. when the shortcut's name is displayed in a button's tooltip).

The editor code takes advantage of the fact that changing the editor language requires a restart. It translates the name once when the shortcut object is created.

Doing so leads to possible redundant double translations in the editor. It also creates inconsistencies in the way translations are done in the editor and in the game, which is not conducive to improving the translation system.

In this PR:

- Use `TTRC()` instead of `TTR()` to mark a shortcut's name. `TTRC()` is just a marker and does not translate.
- Modified the Shortcuts tab in the Editor Settings dialog so that the names of shortcuts are translated when displayed.
- If a button with a shortcut key also has a tooltip text set, the string is changed from using `TTR()` to `TTRC()`. This allows the button to avoid duplicate text automatically, as well as double translations. 

---

Note that the disadvantage of changing to `TTRC()` is that it does not support translation contexts. In theory, you still need to manually translate and change the name in `NOTIFICATION_TRANSLATION_CHANGED` in such case.

In editor codebase, the only place this happens is the tiles editor where we added context for `Line`. The shortcut is for drawing straight lines and needs to be distinguished from representing a line of text.

https://github.com/godotengine/godot/blob/cb411fa960f0b7fdbd97dcdb4c90f9346360ee0e/editor/plugins/tiles/tiles_editor_plugin.cpp#L313-L316

The translation context here could actually be eliminated if the name itself was more precise. Therefore, I took the liberty of suffixing these shortcuts' names with "Tool".

https://github.com/godotengine/godot/blob/4d20b21acd8387abfcbc01e50b6de293bc259479/editor/plugins/tiles/tiles_editor_plugin.cpp#L313-L316

### CODE REVIEW

**Comment by KoBeWi** [comment]
Looks like it doesn't work well with Shortcut tooltips:
image
Expected:
image
The tooltip text uses TTR, so the text does not match.

**Comment by timothyqiu** [comment]
> The tooltip text uses TTR, so it does not match with shortcut name. The tooltip seems to be important in case the button has no shortcut assigned.

Updated the PR to change related tooltip texts to use `TTRC`.

Technically most button's tooltip text can be changed to use `TTRC`, which also has the benefit of avoiding redundant double translations. But here I've only touched those related to shortcuts, let's keep the PR small :stuck_out_tongue:

**Comment by KoBeWi** [comment]
You missed this one (and possibly more?):
https://github.com/godotengine/godot/blob/38775731e8494a28deddc3febda895679f49fd6e/editor/plugins/node_3d_editor_plugin.cpp#L8895

Which exposed another problem, though not directly related. When you search for a shortcut in settings dialog, it will only match original English name. Before this PR the dialog only matched the translated name. I think it should match both. We can improve it later.

**Review by KoBeWi — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
Needs rebase, otherwise seems fine.

**Pull request merged**
