### PR TITLE
Added wakeup to 2D and 3D body impulse and force functions.

### PR DESCRIPTION
**Pull request by danger-dan**
Wake sleeping bodies on apply force and impulse functions. 

*Bugsquad edit: `3.x` version of https://github.com/godotengine/godot/pull/52967.*

### CODE REVIEW

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Thanks for porting this fix to 3.x!

These calls  should be in `PhysicsDirectBodyStateSW` class instead of `BodySW`

I know it's a bit confusing, but the direct body state is what users call directly, while BodySW API is used internally in the physics engine, so it would be overkill to activate the body in this API.

Here's where the direct body state calls for forces and impulses are in 2D for example:
https://github.com/godotengine/godot/blob/29b1d39c51af75e192d11a03893932aeaff6616a/servers/physics_2d/body_2d_sw.h#L368-L373

**Comment by pouleyKetchoupp** [comment]
As a note, I'm also removing the 3.3 cherry-pick. This change is generally safe for 3.x, but since it might introduce minor changes in behavior in specific cases, better go through a slower validation process so we can make sure there's no regression.

**Comment by danger-dan** [comment]
Ahh my bad! lots to learn.

**Comment by danger-dan** [comment]
Have amended to wakeup on exposed API functions instead.

**Comment by danger-dan** [comment]
Also I realised I didn't use the wakeup() functions on the equivalent master branch PR. instead I directly used set_active(). Should I change that to also use wakeup()?

**Comment by pouleyKetchoupp** [comment]
> Also I realised I didn't use the wakeup() functions on the equivalent master branch PR. instead I directly used set_active(). Should I change that to also use wakeup()?

Oh, good point, I missed that on the master version. It looks like `wakeup()` is safer, would be great to change it.

**Review by pouleyKetchoupp — APPROVED** [review]
Looks great!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
