### PR TITLE
Fix popup and dialog scaling problem

### LINKED ISSUE #23127: Scaled popup dialog not centered when popup_centered is called
**Godot version:**
Alpha 3.1 official

**OS/device including version:**
Windows 10, Intel Integrated

**Issue description:**
If popup dialog scale is other than (1,1) it's not centered when calling popup_centered function

**Steps to reproduce:**
a) Add a popup dialog (AcceptDialog in the sample project)
b) Change rect scale (0.1, 0.1 in the sample project)
c) Call popup_centered to display the dialog

**Minimal reproduction project:**
[Popup.zip](https://github.com/godotengine/godot/files/2493746/Popup.zip)

### PR DESCRIPTION
**Pull request by buresu**
fix #23127

Test Project
[Popup.zip](https://github.com/godotengine/godot/files/2559057/Popup.zip)

### CODE REVIEW

**Comment by akien-mga** [comment]
Sorry for the lack of review so far :|

The changes seem good, but it's quite sensitive code used everywhere in the editor and in many games, so it needs a thorough review. @reduz planned to have a closer look at it but didn't have the opportunity it seems.

I'd welcome more users testing and confirming that it works well, or reviewing the code :)

Moving to the 4.0 milestone as I wouldn't be confident merging it so close to the 3.2 release.

**Comment by aaronfranke** [comment]
@buresu Is this fix still relevant after the DisplayServer split?

**Comment by buresu** [comment]
@aaronfranke I updated a test projet for 4.0.
[PopupTest.zip](https://github.com/godotengine/godot/files/4466205/PopupTest.zip)
The popup positon is still a bit wrong.
But, since the scaling parameter has been removed in 4.0, I think we can close this PR.

**Comment by that-richard** [comment]
> @aaronfranke I updated a test projet for 4.0.
> [PopupTest.zip](https://github.com/godotengine/godot/files/4466205/PopupTest.zip)
> The popup positon is still a bit wrong.
> But, since the scaling parameter has been removed in 4.0, I think we can close this PR.

I'm currently doing work on UI scaling in my game, how is scaling gonna be changed? If you could tell me I'll be glad!

**Pull request closed without merging**
