### PR TITLE
ClassDB: Provide the enum name of integer constants

### PR DESCRIPTION
**Pull request by neikeq**
- `BIND_CONSTANT` can only be used with constants of anonymous enums or constant variables.
- `BIND_ENUM_CONSTANT` is used for constants of named enums.

The API is:
- `get_integer_constant_enum(class, constant)`, `get_enum_list(class, out enums)` and `get_enum_constants(class, enum, out constants)` for ClassDB.
- `get_global_constant_enum(index)` for global constants.

The name of the enums is `enum.Class::Enum`, or `enum.Enum` for global enums.

To check if a type is an enum:

``` C++
if (type == Variant::INT && type_name.begins_with("enum."))
```

Then you just split the name to get the class and enum name.

### CODE REVIEW

**Comment by neikeq** [comment]
Wait, I forgot to update DocData.

**Comment by reduz** [comment]
you rock!

**Comment by neikeq** [comment]
I'll leave this aside temporarily until I make the PR with the Mono stuff.

**Comment by reduz** [comment]
i was planning on merging it, so i can work on the doc side, anything avoiding it?

**Comment by neikeq** [comment]
Yes, this is incomplete and won't work correctly. If you really need this to work on the docs side, then I can try finishing it today.

**Comment by neikeq** [comment]
This is what I got:

Apart from `VARIANT_ENUM_CAST`, which declares the `GetTypeInfo` specialization for the enum (and variant cast templates), an extra macro is required to expose an enum constant:
- `BIND_ENUM`: Fills the type info of the enum with the correct data. Must be placed before `BIND_ENUM_CONSTANT`.

Now `BIND_CONSTANT` can only be used with constants of anonymous enums or constant variables. Use `BIND_ENUM_CONSTANT` for constants in named enums.

The good thing is that you will either get a compiler error or a runtime error message if you did any of the previously stated points wrong.

The API is:
- `get_integer_constant_enum(class, constant)`, `get_enum_list(class, out enums)` and `get_enum_constants(class, enum, out constants)` for ClassDB.
- `get_global_constant_enum(index)` for global constants.

The name of the enums is `enum.Class.Enum`, or `enum.Enum` for global enums.

To check if a type is an enum:
``` C++
if (type == Variant::INT && type_name.begins_with("enum."))
```
Then you just split the name to get the class (unless it's global) and the enum name.

**Comment by neikeq** [comment]
What should I do with `VARIANT_ENUM_CAST(wchar_t)`. `wchar_t` is clearly not an enum :)

**Comment by neikeq** [comment]
This is ready now.

**Comment by reduz** [comment]
question, is it really needed that we do BIND_ENUM() before BIND_ENUM_CONSTANT() ?
can't the enum name be inferred from the argument?

**Comment by neikeq** [comment]
Updated, `BIND_ENUM` isn't needed anymore.

**Pull request merged**
