### PR TITLE
[Docs] Clarify `Array.fill` behavior when reference type is passed in

### LINKED ISSUE #68032: Using fill() in an Array[Array] will fill the Array with reference to a single Array
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

When using fill() on an Array[Array], it will fill the Array with reference to a single Array.

Thus when changing a single item, it will change all of the other items.

### Steps to reproduce

See code and minimal project included below

### Minimal reproduction project

```
extends Node

var my_array: Array[Array]

func _ready() -> void:
    my_array.resize(4)
    my_array.fill([0, 1, 2, 3])
	
    my_array[0][0] = 5 
    print(my_array)
```
Result
will change all 1st item of all arrays
[[**5**, 1, 2, 3], [**5**, 1, 2, 3], [**5**, 1, 2, 3], [**5**, 1, 2, 3]]
             
Expected
change the 1st item of the 1st array only
[[**5**, 1, 2, 3], [**0**, 1, 2, 3], [**0**, 1, 2, 3], [**0**, 1, 2, 3]]

	
[Array[Array].zip](https://github.com/godotengine/godot/files/9894461/Array.Array.zip)

### PR DESCRIPTION
**Pull request by kleonc**
Resolves #68032.

### CODE REVIEW

**Comment by KoBeWi** [comment]
Wouldn't it be better to modify the method instead? Might be not that difficult.

**Comment by mhilbrunner** [comment]
The question is if the behaviour is intended, as per the discussion in the issue, it seems to be somewhat expected.

**Comment by KoBeWi** [comment]
It's not very useful though. Why would you want an array full of the same object?

**Comment by Mickeon** [comment]
I'd change the method and note the special behavior for **Arrays**/**Dictionaries**, instead. Duplicating Objects may be its own can of worms, however.

**Comment by kleonc** [comment]
> It's not very useful though. Why would you want an array full of the same object?

@KoBeWi Not really sure (I don't think I've ever used this method with reference types) but probably an example could be filling an array with some dummy guard-like instance of an object. But yeah, I've just made this up, that's pure theoretization.

Nonetheless, it feels like changing the behavior should be a subject of a proposal. Modifying this method to auto-duplicate would be a breaking change. Also it's not the only available option, and alternative would be to just add a bool parameter telling whether it should duplicate. Or maybe something else (e.g. @Mickeon's comment), I don't know. So yeah, I don't mind potential changes but firstly it should be discussed in a proposal I think.

**Comment by Pizza-Script** [comment]
Hi, just to try and add to this, and to give a sample use case,
I was using fill() to give a default value to an Array of Array (2D Array?)

```
var my_array: Array[Array]

func _ready() -> void:
    my_array.resize(4)
    my_array.fill([-1, -1])
```

That's where I discovered this weird result.
Thank you.

**Review by akien-mga — APPROVED** [review]
Looks good. I agree with only documenting this caveat, I don't think changing the behavior would actually solve a significant use case. Either way I agree that we should wait for a proposal to assess that further.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
