### PR TITLE
Use current locale as the default in get_tool_locale()

### LINKED ISSUE #79585: Running a project with a RTL language set to internationalization/locale/test does not flip GUI to RTL
### Godot version

v4.1.stable.official [970459615]

### System information

Ubuntu 20.04 LTS

### Issue description

See title.
This is a regression since v4.0.1.stable.official [cacf49999]
Similar to https://github.com/godotengine/godot/issues/63961, though I don't think they're the same since it doesn't mention RTL.

### Steps to reproduce

1. Create a new GUI scene
2. Add a `Button`, it should be in the top left corner
3. Under Project -> Project Settings... -> Internationalization -> Locale, change `Test` to `ar`
4. Run project, notice the Button stayed in the top left corner.  It should've moved to the top right corner

### Minimal reproduction project

[godot4rtl.zip](https://github.com/godotengine/godot/files/12070047/godot4rtl.zip)

### PR DESCRIPTION
**Pull request by dhoverml**
Fixes #79585
I wasn't sure if line 709 should have a similar change.

### CODE REVIEW

**Comment by AThousandShips** [comment]
This assumes that a translation for the loaded locale exists though, which is always true for "en", but isn't guaranteed otherwise

**Review by bruvzg — CHANGES_REQUESTED** [review]
Doesn't look like a bug to me. If there's no translation loaded, locale should not be applied. Default (untranslated) text is expected to be English, and setting RTL layout for English is wrong.

**Comment by AThousandShips** [comment]
Note that the documentation for `TrsnslationServer` could do with an update, as it says `get_tool_locale` returns the same as `get_locale` when not in tool mode: https://docs.godotengine.org/en/stable/classes/class_translationserver.html#class-translationserver-method-get-tool-locale

**Comment by bruvzg** [comment]
> Note that the documentation for TrsnslationServer could do with an update, as it says get_tool_locale returns the same as get_locale when not in tool mode

Indeed, docs are outdated. It was the same as `get_locale`, but behavior was changed in https://github.com/godotengine/godot/pull/73716 to fix https://github.com/godotengine/godot/issues/73710.

**Comment by AThousandShips** [comment]
> Also, in the editor I tried setting internationalization/rendering/root_node_layout_direction

It should be set to 2, but the setting is incorrectly configured, will open a fix for that

**Comment by dhoverml** [comment]
Thanks @AThousandShips and @bruvzg 
I took a closer look at how get_tool_locale() works in code, and managed to get something simple to work.  Apologies for the confusion; I'll go ahead and close this pull request.

**Pull request closed without merging**
