### PR TITLE
Refactored code on GDScript files

### PR DESCRIPTION
**Pull request by Keyaku**
Some switch cases are used unnecessarily. There are alternatives that bring the same results, and add on top of it all a better code organization.

All that's left is refactoring GDFunctions::get_info().

Changes:
- Swapped switch case in GDFunctions::call() with an array of constant function pointers
- Swapped switch case in GDFunctions::is_deterministic() with comparisons

### CODE REVIEW

**Comment by Keyaku** [comment]
I'm getting weird behavior: the GDTokenizer is giving a SIGSEGV even though I haven't touched that file.

I'm going to check out what's going on.

**Comment by reduz** [comment]
Array of function pointers is slower than current implementation, as the
switch statements are consecutive compilers will generate a jump table.

**Comment by Keyaku** [comment]
> Array of function pointers is slower than current implementation, as the
switch statements are consecutive compilers will generate a jump table.

Array of constant function pointers *actually maintains* the jump table you're looking for if function-inlining is turned on. I wouldn't present this solution otherwise. since it brings the same results with better code presentation.

There's also the change for `is_deterministic()` which uses comparisons that follow the order of the `Function` enum values.

**Comment by reduz** [comment]
never tried that approach :) In any case is_deterministic is only for the
compiler, so it has no impact in runtime.

If you want GDScript to run faster, I would appreciate benchmarks more than
optimizations.. I'm not a fan of optimizing in the dark

**Comment by Keyaku** [comment]
All righty! Will work on that and show the differences as soon as I can (will take me while).

**Comment by reduz** [comment]
I don't mean show the diferences for that specific function but in General.
GDScript is not that slow and runs about at the same speed as Python,  but
it was never really profiled to improve the performance (which means it has
a lot of room to work). Any work in general purpose benchmarks is
appreciated.

**Pull request closed without merging**
