### PR TITLE
support emacs-like shortcuts

### PR DESCRIPTION
**Pull request by chromied**
For non-MacOS, the default shortcuts is empty.
For MacOS user, it will re-enable the system cursor shortcuts in Godot Editor.

- Move cursor forward: `Ctrl + F`
- Move cursor backward: `Ctrl + B`
- Move cursor up: `Ctrl + P`
- Move cursor down: `Ctrl + N`
- Delete char: `Ctrl + D`

Thanks [DrMoriarty](https://github.com/DrMoriarty/godot)

### CODE REVIEW

**Comment by fire** [comment]
There are some style issues with clang format.

**Comment by mrbig033** [comment]
I also wish for this feature... using CUA keys is unbearable for an Emacs user. Vim-like keys would also be nice, but if that is not possible I'd be happy with the ability to use Godot in an Emacs fashion.

**Comment by mrbig033** [comment]
I also wish for this feature... using CUA keys is unbearable for an Emacs user. Vim-like keys would also be nice, but if that is not possible I'd be happy with the ability to use Godot in an Emacs fashion.

**Comment by novemberist** [comment]
I also can't wait for this to be merged. However, currently if you press and hold e.g. 'ctrl + f', the cursor only moves down one line and stops. I think it should move further continuously until you release the buttons. Is this intened? Because this is not how the arrow keys behave (or how these shortcuts behave in emacs)

**Comment by Howardw3** [comment]
> I also wish for this feature... using CUA keys is unbearable for an Emacs user. Vim-like keys would also be nice, but if that is not possible I'd be happy with the ability to use Godot in an Emacs fashion.

I'd like to help but I'm not a Vim user. But you can customize the shortcuts to Vim-like keys:)

**Comment by mrbig033** [comment]
> > I also wish for this feature... using CUA keys is unbearable for an Emacs user. Vim-like keys would also be nice, but if that is not possible I'd be happy with the ability to use Godot in an Emacs fashion.
> 
> I'd like to help but I'm not a Vim user. But you can customize the shortcuts to Vim-like keys:)

Vim is a modal text editor, so this is not simply a matter of customizing keybindings. It's an entirely different text editing paradigm. Besides, the Godot Script Editor has very few customization options available - at least in the GUI interface. Does Godot have a configuration file where I can access further options?

**Comment by Howardw3** [comment]
> I also can't wait for this to be merged. However, currently if you press and hold e.g. 'ctrl + n', the cursor only moves down one line and stops. I think it should move further continuously until you release the buttons. Is this intened? Because this is not how the arrow keys behave (or how these shortcuts behave in emacs)

Thanks for reporting this issue. I didn't intent to make it. In my understanding, I think it's because Godot editor cannot trigger/run some shortcuts by some reasons... `Shift+Cmd+K` Delete Line also have the same behavior.
I will dive into the source code to find if I can fix it.

**Comment by Howardw3** [comment]
> > > I also wish for this feature... using CUA keys is unbearable for an Emacs user. Vim-like keys would also be nice, but if that is not possible I'd be happy with the ability to use Godot in an Emacs fashion.
> > 
> > 
> > I'd like to help but I'm not a Vim user. But you can customize the shortcuts to Vim-like keys:)
> 
> Vim is a modal text editor, so this is not simply a matter of customizing keybindings. It's an entirely different text editing paradigm. Besides, the Godot Script Editor has very few customization options available - at least in the GUI interface. Does Godot have a configuration file where I can access further options?

I think what you can do is read the editor source code and find all low-level text edit APIs that you need for making Vim modes. Then, you can either make it as a Addons or add a shortcut or button in the editor to switch between Vim mode and Godot native text edit.
You may want to check `editor/plugins/script_text_editor.cpp`.
But I think, in your case, just use the visual studio code as external editor. That will be much easier...

**Comment by mrbig033** [comment]
> > > > I also wish for this feature... using CUA keys is unbearable for an Emacs user. Vim-like keys would also be nice, but if that is not possible I'd be happy with the ability to use Godot in an Emacs fashion.
> > > 
> > > 
> > > I'd like to help but I'm not a Vim user. But you can customize the shortcuts to Vim-like keys:)
> > 
> > 
> > Vim is a modal text editor, so this is not simply a matter of customizing keybindings. It's an entirely different text editing paradigm. Besides, the Godot Script Editor has very few customization options available - at least in the GUI interface. Does Godot have a configuration file where I can access further options?
> 
> I think what you can do is read the editor source code and find all low-level text edit APIs that you need for making Vim modes. Then, you can either make it as a Addons or add a shortcut or button in the editor to switch between Vim mode and Godot native text edit.
> You may want to check `editor/plugins/script_text_editor.cpp`.
> But I think, in your case, just use the visual studio code as external editor. That will be much easier...

That's cool but I'm a noobie! In the time it would take me to learn how to do that someone would end doing first. I plan to contribute on the documentation.

**Comment by akien-mga** [comment]
I'm confused, what's the link between Emacs and macOS? Emacs is a cross platform editor so why enable hotkeys that emulates its features only for macOS?

IMO Emacs and vim modes should be opt-in (not enabled by default), and not platform-specific.

**Comment by Howardw3** [comment]
> I'm confused, what's the link between Emacs and macOS? Emacs is a cross platform editor so why enable hotkeys that emulates its features only for macOS?
> 
> IMO Emacs and vim modes should be opt-in (not enabled by default), and not platform-specific.

Hi Akien,

Sorry to the name make you confused. These shortcuts are actually the native and common shortcuts in MacOS(Unix based), they are same in Emacs. And most of the modern text editor in macOS are using them except Vim users. Considering Vim user may want to create their own shortcuts or Vim mode. That's why it's called emacs-like, not macOS shortcuts.

**Comment by aaronfranke** [comment]
@Howardw3 Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by novemberist** [comment]
I'd still very much like to have the option to use emacs-like shortcuts in godot's code editors and put my muscle memory to good use. Almost every code editor has this option.

**Comment by mrbig033** [comment]
> @Howardw3 Is this still desired? If so, it needs to be rebased on the latest master branch.

Yes very much so. Thanks.

**Comment by Howardw3** [comment]
@aaronfranke Hey. I'm not working on Godot project for a year. Maybe other users need this feature. But I don't have the ability to rebuild and test it, since the original repo has been destroyed. Sorry guys. You can still copy the code from diff.

**Comment by mrbig033** [comment]
> @aaronfranke Hey. I'm not working on Godot project for a year. Maybe other users need this feature. But I don't have the ability to rebuild and test it, since the original repo has been destroyed. Sorry guys. You can still copy the code from diff.

I'm not sure what you mean. Copy what from diff? Thanks.

**Comment by akien-mga** [comment]
@mrbig033 Add `.patch` or `.diff` to the PR URL to have the raw patch that can be applied on the Godot codebase (might need `git am -3 26107.patch` and then solving merge conflicts).
https://patch-diff.githubusercontent.com/raw/godotengine/godot/pull/26107.patch

**Pull request closed without merging**
