### PR TITLE
Fix editor saving blank scenes (for real)

### LINKED ISSUE #54425: "Save all Scenes" gives unclear prompt for [unsaved](*)
### Godot version

6b0b1a4c042175190381737e3000027ef912e6cb

### System information

Windows 10

### Issue description

image
I would guess this has to do with #53705.
Outstanding changes to scenes that had been saved earlier are saved correctly.

This is different form Godot 3.3, where in the same conditions the prompt from the screenshot isn't shown, and the Editor, as far as I can tell, silently does nothing with "[unsaved](*)" scenes.

### Steps to reproduce

Create a new project or open an existing one.
Create a new Scene.
Try to use the "Save all Scenes" functionality.
image

Outstanding changes to scenes that had been saved earlier are saved correctly.

### Minimal reproduction project

Any project.

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #54425

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by briansemrau** [comment]
Noticed an issue since this was merged. When closing a scene with a contained built-in script open in the script editor, I get one of two popups:

If the editor switches to a different scene tab:
image

If it was the last scene tab open:
image

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.1.

**Pull request merged**
