### PR TITLE
Workaround for clang 6.0.0 / Xcode 9.3 release (-O3) build bug.

### LINKED ISSUE #18023: [Compiler bug] clang 6.0.0/Xcode 9.3 clang hangs on compiling optimised `servers/physics/collision_solver_sat.cpp`
**Godot version:**
master ec110076c - e3590a252

**OS/device including version:**
* macOS 10.13.4 (17E199)
* Debian GNU/Linux 9 (stretch) (4.9.0-6-amd64)

**clang versions:**
* macOS, Apple LLVM version 9.1.0 (clang-902.0.39.1), Xcode 9.3 (9E145)
* macOS, clang version 6.0.0 (tags/RELEASE_600/final), installed from MacPorts.
* Debian, clang version 6.0.0-1~bpo9+1 (tags/RELEASE_600/final), installed from OS repo.

**Last knows good clang versions:**
* macOS, Apple LLVM version 9.0.0 (clang-900.0.39.2), Xcode 9.2 (9C40B)
* macOS, clang version 5.0.1 (tags/RELEASE_501/final), installed from MacPorts.
* Debian, clang version 5.0.1-2~bpo9+1 (tags/RELEASE_501/final), installed from OS repo.

Fixed in clang version 7.0.0 (trunk 329027), installed from MacPorts.
**NOT** fixed in Xcode 9.4 beta (9Q1004A)

**Steps to reproduce:**
Build optimised (release or release_debug) Godot on macOS using specified compiler versions.

If you have problems compiling Godot release versions on mac, downgrade Xcode command line tools to 9.2 or use clang-5.0/clang-devel from MacPorts (add `macports_clang=5.0`/`macports_clang=devel` to build command).

*Update (Apr 14):* Same problem affects Linux builds too, so it's clearly compiler bug.

*Update (Apr 22):* Some additional information: clang seems to have problem optimising multiple inlined instances of [`test_axis`](https://github.com/godotengine/godot/blob/master/servers/physics/collision_solver_sat.cpp#L318), in [`_collision_capsule_capsule`](https://github.com/godotengine/godot/blob/master/servers/physics/collision_solver_sat.cpp#L1076) function.

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #18023.

### CODE REVIEW

**Comment by bruvzg** [comment]
Logic is unchanged. Bug is already fixed in clang-7 trunk.

**Comment by sanja-sa** [comment]
Please, add this commit to 2.1. Thanks, it's works.

**Comment by akien-mga** [comment]
Cherry-picked for the 2.1 branch as d1869b37a. Should likely be cherry-picked for the 3.0 branch too.

**Comment by hpvb** [comment]
Cherry picked into 3.0.6 with an additional check:
```c++
if (min_B < 0.0) {
  min_B = -min_B;
}
```
to make sure that in the case of min_B being exactly 0 the sign does not get flipped. This is likely not going to affect users but I want to be sure these sorts of things don't affect currently running projects.

**Pull request merged**
