### PR TITLE
Add renderer selection to New Project dialog

### PR DESCRIPTION
**Pull request by leonkrause**
Gives a choice between GLES 2.0 and 3.0 at project creation with bullet points for comparison.

pjmgr-renderselect

### CODE REVIEW

**Comment by groud** [comment]
I think this settings takes too much space, it bloats the UI.
Also, I am not sure why having this settings there, an no other interesting options (regarding quality & all) is worth it, considering the setting is already available to change in the editor (that might be removed though).

If having this choice on the new project popup is to be accepted, I would prefer it to be less intrusive, probably with a popup list, and the text as tooltips on each options.

**Comment by williamd1k0** [comment]
>Probably it would be much cleaner to have some sort of preset/template selection dialog (like most IDEs have) with more specific pros and cons of the renderer for selected type of project.

Hey, this suggestion is really interesting. It would be great to have something like "2D Pixel Art template" (since Godot is perfect for pixel art games, but the default import settings push users away because of texture filters).

*I know that in this case it's not related only to the renderer setting, but I found it relevant to comment anyway.*

**Comment by groud** [comment]
> This renderer setting could be misleading for new users since it looks like a some super important, permanent choice (even with the note that it can be changed) instead of mere preset.

I completely agree. 

> Probably it would be much cleaner to have some sort of preset/template selection dialog (like most IDEs have)

I completely agree too.

> It would be great to have something like "2D Pixel Art template" (since Godot is perfect for pixel art games, but the default import settings push users away because of texture filters).

I think we discussed something like that a while ago, and people tend to agree that having such template was a good idea.

**Comment by starry-abyss** [comment]
Well, there is already some template selector, but it's not very visible, I discovered it by accident. Also templates are downloaded from internet and the "official" filter wasn't easy to find either (why it's not the default?).
I like @bruvzg suggestion to unite project creation and templates, but in the mockup renderer mode is in section titles and still "looks like a some super important" choice IMHO.

**Comment by eska014** [comment]
Choice of renderer determines how one will build one's scenes, e.g. GPU vs CPU particles, usage of GI probes, etc., so users do need to be aware of their options when they start. This patch is more about documentation than convenience.

More project creation settings are an interesting improvement for the future.

Updated the changeset to import etc1 instead of etc2 with GLES2.

@volzhs
Newcomers' expectation is that all features are available no matter the renderer. If it's not clear that the GLES2 renderer is missing features, this will cause confusion. Same for hardware compatibility in GLES3.

**Comment by akien-mga** [comment]
IMO this is a good addition. I agree that more could be done and that a full project creation wizard as exemplified by @bruvzg would be great, but we're running out of time for such changes to 3.1, so @eska014's proposals takes care of the most urgent matters.

We can always refine/replace it for 3.2.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Oranjoose** [comment]
Speaking for beginners, I think this is quite a poor choice of addition. Beginners want to get up and running as quickly as possible, with the least amount of noise possible. Consider any modern game design. I've taught many game engines in my classes over the years, and Godot is by far the most cumbersome (out of all the game engines with a visual editor) to get the class on the same page with creating a new project. This GLES addition just makes things even worse on this front (and imo looks unpolished, and tacked on).

If you really _must_ have this up front, then I sincerely recommend tucking it in an "Advanced Settings" drawer. Or introduce this up-front setting once you get a New Project dialog that has a template up front that asks "Blank 2D project", "Blank 3D project", and so on.

**Comment by volzhs** [comment]
after I read what @Oranjoose said,
It reminded me that some games force me to select something before I really play the game.
it's actually a barrier to start.

**Pull request merged**
