### PR TITLE
Fix resource_name not set for gdscripts (issue 13358)

### LINKED ISSUE #13358: Script.resource_name always contains blank string
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
a26b36bec2e99a128b7a61ff9fa1e2e46148f547

**Issue description:**
Whenever you try to .get_script().resource_name, the variable only contains blank string. However resource_path always return valid path.

**Steps to reproduce:**
1. Attach script with this line code
`print(get_script().resource_name)`
2. See on the console, doesn't print anything

### PR DESCRIPTION
**Pull request by ghost**
Don't merge, there is probably a good reason why this line is commented out in the current master (git annotate shows reduz) so probably this should be postponed to 3.1 - maybe it has to do with compiled scripts not having a name.

Just opening this PR to document the bug's reason.

PR fixes https://github.com/godotengine/godot/issues/13358.

### CODE REVIEW

**Comment by vnen** [comment]
GDScript files contain only code, the `resource_name` will never be saved.

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by vnen** [comment]
I wonder how well this works in a release build.

**Comment by akien-mga** [comment]
Discussed it with @reduz today, he doesn't really remember why this is commented out nor whether it should be changed, but the plan is to get rid of `resource_name` eventually. It's not used much currently and this unset `resource_name` for GDScript doesn't seem problematic.
```
$ rg resource_name
editor/editor_sectioned_inspector.cpp
53:                     if (pi.name == "resource_path" || pi.name == "resource_name" || pi.name == "resource_local_to_scene" || pi.name.begins_with("script/")) //skip resource stuff
206:            if (pi.name.find(":") != -1 || pi.name == "script" || pi.name == "resource_name" || pi.name == "resource_path" || pi.name == "resource_local_to_scene")

editor/property_editor.cpp
4456:                   if (pi.name == "resource_path" || pi.name == "resource_name" || pi.name == "resource_local_to_scene" || pi.name.begins_with("script/")) //skip resource stuff
4606:           if (pi.name.find(":") != -1 || pi.name == "script" || pi.name == "resource_name" || pi.name == "resource_path" || pi.name == "resource_local_to_scene")

core/resource.cpp
112:    _change_notify("resource_name");
381:    ADD_PROPERTYNZ(PropertyInfo(Variant::STRING, "resource_name"), "set_name", "get_name");

doc/classes/Resource.xml
60:             <member name="resource_name" type="String" setter="set_name" getter="get_name">

platform/uwp/export/export.cpp
661:    bool _valid_resource_name(const String &p_name) const {
1168:           if (!_valid_resource_name(p_preset->get("package/unique_name"))) {
```

**Pull request closed without merging**
