### PR TITLE
Changed the comment where reduz yells at the X11 API to a less explicitive one

### PR DESCRIPTION
**Pull request by LikeLakers2**
As much as this comment is funny, I don't think we need it in the source code. Plus it's the last occurrence of the f-word in the source code.

P.S. This totally isn't for the t-shirt. Nope, not at all.

### CODE REVIEW

**Comment by groud** [comment]
> Plus it's the last occurrence of the f-word in the source code

That's true, but note that X11 deserves it. ^^

**Comment by eska014** [comment]
Leaving aside PC, documentation about filtering mouse motion events is being deleted with this patch. Rewrite the comment instead.

**Comment by LikeLakers2** [comment]
@eska014 How's that comment look?

**Comment by akien-mga** [comment]
A bit saddened to let go another one of the Easter Eggs, but I know that many don't share the weird core devs sense of humour and might be put off by such crude language, so fine to merge. Rewritten comment is good :+1:

**Comment by LikeLakers2** [comment]
Heh, no worries, I won't be removing any of the other easter eggs[.](https://github.com/godotengine/godot/blob/4f5a7ebaecfcf00cf1e5c4af4b20034f0dcecd29/thirdparty/libwebsockets/roles/http/server/access-log.c#L156)

**Comment by akien-mga** [comment]
I see what you did there, but even if we wanted to, we couldn't, that's not our code.

**Comment by LikeLakers2** [comment]
Well then, let's just hope they like it as much as we do. :)

**Comment by neikeq** [comment]
I find this PR to be grossly offensive for those who have had to deal with the X11 API in the past and for those who will have to deal with it in the future. Please, have some empathy.

**Pull request merged**
