### PR TITLE
Detect plugins recursively (3.2)

### PR DESCRIPTION
**Pull request by Shatur**
A cherry-pick of #43734.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
Due to this change, Godot now expects full plugin path in the enabled plugin list in project settings. Which means that opening a project older than RC3 will disable all plugins, because previously only names were stored. Not a big deal, but we should probably warn about this in the patch notes or something (you just need to re-enable plugins in the new version).

**Comment by Shatur95** [comment]
> Which means that opening a project older than RC3 will disable all plugins, because previously only names were stored.

Correct. Sorry, I knew about it, but forgot to mention :(

> Not a big deal, but we should probably warn about this in the patch notes or something (you just need to re-enable plugins in the new version).

Agree!

**Comment by Xrayez** [comment]
I stumbled upon this too today while trying to run GUT tests.

Perhaps it may be possible to convert relative paths to absolute, or treat plugin names as top-level `res://addons`.

**Comment by Shatur95** [comment]
> Perhaps it may be possible to convert relative paths to absolute, or treat plugin names as top-level res://addons.

I would just report it in the changelog. But yes, it can be done. I can send a PR for it if you wish.

**Comment by Xrayez** [comment]
It depends on how many users are going to be negatively affected by this (at most this is minor annoyance), but yeah making this backward compatible would be nice if you have the time to do this. 🙂

**Comment by KoBeWi** [comment]
Well, adding some backward-compatibility wouldn't hurt, but it's relevant only for 3.2 branch.

**Comment by Shatur95** [comment]
Okay, I will send a PR for it!

**Pull request merged**
