### PR TITLE
Add `texture_changed` signal to `Sprite3D`

### LINKED ISSUE #53285: Sprite3D: Attempt to connect nonexistent signal 'texture_changed'.
### Godot version

v4.0.dev.custom_build [b1237b5ca]

### System information

Windows 10, Nvidia, Vulkan

### Issue description

Adding Sprite3D will output following errors.
Sprite2D works fine,though.

image

### Steps to reproduce

1. Create A New Scene.
2. Add a Sprite3D Node.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #53285

### CODE REVIEW

**Comment by akien-mga** [comment]
I think it's important to check why it was removed before adding it back, as it might have been on purpose.

It seems like it was removed in 85cf99f28e93556f1298a5136254253f9da82b9a (found with `git log -S texture_changed`), and looking at the diff, I'd say it was intentional.

Existing signal connections seem to have been replaced by connections to `_queue_update`:
```diff
-               texture->connect(CoreStringNames::get_singleton()->changed, callable_mp(this, &Sprite3D::_texture_changed));
+               texture->connect(CoreStringNames::get_singleton()->changed, Callable(this, "_queue_update"));
```

So maybe the connection that fails in #53285 was just missed.

**Comment by Chaosus** [comment]
@akien-mga Sorry, I've looked at Sprite2D & NinePatchRect where that signal still has presence and forgot to look at the reason why it's removed. So this is an incorrect fix and there should be another signal? In the `texture_region_editor_plugin.cpp` it's expected connection to `texture_changed` for the Sprite3D currently.

**Comment by akien-mga** [comment]
Ah yeah, I see. I suggest we ask @reduz what he intended with the removal of that signal, to see what should be done for `TextureRegionEditorPlugin`. Maybe this PR is correct in the end.

**Review by mhilbrunner — APPROVED** [review]
PR meeting: Approved, but we should investigate overhauling the editors, we probably shouldn't need these signals and could remove them. (We should open a proposal to track this)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
