### PR TITLE
Add a Pause button to the 2D and 3D editor

### LINKED ISSUE #942: Add ability to pause all animated content within the editor
**Describe the project you are working on:**
3d open world game

**Describe the problem or limitation you are having in your project:**
I have many particle emitters in the world. They have a noticeable effect on the in-editor FPS.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
Pausing particle simulation in editor lets me work without FPS drops.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**
A button/switch in project/editor settings that pauses ALL animated content in editor.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
While this is possible by setting emitting to false on particles, it requires attaching a tool script to EVERY particle emitter. The bigger the project, the less feasible this gets.

**Is there a reason why this should be core and not an add-on in the asset library?:**
How would an asset know what and when to pause? IIRC it needs core changes, plus assets can't add to project settings AFAIK.

Original issue: https://github.com/godotengine/godot/issues/16397

ETA: It seems that the animated sprites and tiles suffer from the same problem, and especially for tiles, the workaround would be very involved.

### PR DESCRIPTION
**Pull request by Calinou**
Salvaged from https://github.com/godotengine/godot/pull/31070. Thanks @Chaosus :slightly_smiling_face: 

This can be used to decrease CPU/GPU usage if particles or shaders are being displayed in the editor.

**Note:** Since [low-processor usage mode hasn't been reimplemented yet in `master`](https://github.com/godotengine/godot/issues/39511), this won't decrease CPU/GPU usage significantly in the `master` branch, only in `3.2` if it's backported there.

**Don't merge yet** as pausing will break freelook in the 3D editor and scrolling in the script editor if smooth scrolling is enabled (related to https://github.com/godotengine/godot/issues/28385, partially addressed by https://github.com/godotengine/godot/pull/42704).

I can make a 3.2 version of this PR once it's ready.

This closes https://github.com/godotengine/godot-proposals/issues/942.

## Preview

*Freeze* icon is at the bottom.

image

### CODE REVIEW

**Comment by Chaosus** [comment]
> Salvaged from #31070.

Yeah, as I remember the pretensions for that PR in IRC was: "it was not customizable enough and better to be placed in the menu" and "it takes a valuable place". Perhaps the views are changed from that time...

**Comment by Calinou** [comment]
> Perhaps the views are changed from that time...

I think the [current problem at hand](https://github.com/godotengine/godot/issues/39758) is more important than saving a bit of space in the menu. It's making people not use Godot when they could.

**Comment by molevision** [comment]
> Yeah, as I remember the pretensions for that PR in IRC was: "it was not customizable enough and better to be placed in the menu" and "it takes a valuable space". Perhaps the views are changed from that time...

At this point I'd take that pause button over most others, haha. To maybe prevent confusion with the pause scene button on the top right, I'd suggest changing the tool name to "Freeze." I've made a 14x14 icon here: [ToolFreeze.zip](https://github.com/godotengine/godot/files/5425824/ToolFreeze.zip)

**Comment by Calinou** [comment]
@molevision I amended my PR to use the icon you provided, thanks :slightly_smiling_face:

**Comment by lawnjelly** [comment]
Just a note that I think although pausing might be useful for timelines, a more suitable fix for the problem of constant editor updates might be to have a slight modification to the system for requesting updates.

At the moment it is very broad, you request an update in the editor no matter whether this is caused by an animating texture, or something that *really* needs updating (like an update to the UI). Most of the time speaking for myself on a fanless PC, I don't want these constant updates the moment I use TIME in a shader or somesuch.

I'm wondering whether we can change the request_update function to have an argument such as a bool (perhaps with a default) to indicate whether the update is an essential update or not. Then we could have a switch in the UI to turn the non essential updating on and off.

I've been meaning to have a look at this but it might be something you might be interested in @Calinou.

**Comment by molevision** [comment]
Is this likely to make it to 3.2.4?

**Comment by Calinou** [comment]
> Is this likely to make it to 3.2.4?

Probably not, since 3.2.4 is nearing release.

**Comment by molevision** [comment]
> Probably not, since 3.2.4 is nearing release. You can still cherry-pick this pull request and build it locally if you need it.

I haven't ever been able to get Vulkan Godot to work properly on my machine, the viewport is always completely black. Is there some way to build this PR with 3.3?

**Comment by Calinou** [comment]
> Is there some way to build this PR with 3.3?

You can cherry-pick the PR's commit to the `3.3` branch, but you'll have to resolve merge conflicts in the way.

You can also apply the [`.patch` file](https://github.com/godotengine/godot/pull/43011) using `git am`, but I don't know how to resolve conflicts in an interactive manner with `git am`.

**Comment by Calinou** [comment]
Rebased and tested again, it works successfully.

**Comment by molevision** [comment]
Congratulations on the 3.3 release! Can this please make it in to 3.3.1? 😅
This PR was intended as a stopgap awaiting specific fixes to a lot of people's technical problems with the viewport updating. I can't add animations to my characters or use post-processing without it, the editor load is just too high. I have not been able to use Godot for about a year because of this. It would make a big difference to everyone in #39758 to have this merged.

(Plus, Vulkan in 4.0 using the MoltenVK backend to access Metal might just make the problem go away, for Mac users at least.)

**Comment by molevision** [comment]
This can be closed, functionality implemented by #53463.

**Pull request closed without merging**
