### PR TITLE
Fix #41798 And #41799

### LINKED ISSUE #41798: CTRL+Left click on a selected graph node sends a selected signal, and then a deselected signal
**Godot version:**
godot mono 3.2.3_RC5

**OS/device including version:**
Windows 10

**Issue description:**
CTRL click selects and deselects GraphEdit Graph Nodes correctly as far as user visualization, however, the signals fired send an extra select.

Expected behavior :
deselecting a node with CTRL left click will only throw a 'node_unselected' signal

**Steps to reproduce:**
1 If I left click on an unselected node, or CTRL left click on a node 'node_selected' is fired.
2 If I then CTRL left click on the same node it fires 'node_selected' then fires 'node_unselected'

Notes :
This behavior might not be new in 3.2.3, but since that version added 'node_unselected' as a signal it may just now be noticeable.

### PR DESCRIPTION
**Pull request by HeadCrab654**
Fixes [#41798](https://github.com/godotengine/godot/issues/41798) and [#41799](https://github.com/godotengine/godot/issues/41799)

### CODE REVIEW

**Comment by KoBeWi** [comment]
Please amend the commit message to be more descriptive.

**Comment by EricEzaM** [comment]
You have mixed up some commit's here and added changes to the animation player and the readme. They need to be removed, and only changes to graph edit kept. And, as above, the commit message amended.

**Comment by IlTrain** [comment]
Sorry, these are the first times I've ever used git and GitHub, so I still have to get the hang of it and understand how they work.

**Comment by IlTrain** [comment]
> 
> 
> You have mixed up some commit's here and added changes to the animation player and the readme. They need to be removed, and only changes to graph edit kept, if that is what you are changing with this PR (the linked issues are both about graphedit). And, as above, the commit message amended.

Sorry, these are the first times I've ever used git and GitHub, so I still have to get the hang of it and understand how they work.

**Comment by akien-mga** [comment]
This needs to be redone as the commit history is messy, and it removes the README.md and includes changes unrelated to the issues it aims to solve.

**Pull request closed without merging**
