### PR TITLE
Make Nodes with disabled processing appear selectable if their type matches in the exported node menu

### LINKED ISSUE #82631: Nodes with disabled processing appear unclickable when selecting exported node
### Godot version

4.2 dev5

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

image
Control can be selected, but doesn't look like.

### Steps to reproduce

1. ```
extends Node
@export var test: Control
```
2. Add a Control to the scene
3. Set its `process_mode` to disabled

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by Stronkkey**
Fixes #82631

### CODE REVIEW

**Comment by KoBeWi** [comment]
That doesn't work. Only the base node is colored white, but child nodes that inherit disabled mode are still grayed.
I think the condition is not necessary at all, just use plain `else`.

**Comment by Stronkkey** [comment]
Didn't think of that. Should now be fixed.

**Comment by KoBeWi** [comment]
It seems to work correctly now, but I found another problem and not sure how to solve it .-.
If you export a NodePath instead of Node, the nodes will still have wrong color. That's because `valid_types` Vector is empty. I think it might need some new flag to disable coloring or something.

**Comment by Stronkkey** [comment]
A flag would just make the constructor even bigger for no reason. I think a better way of doing it is by creating a function that colors the nodes. But this would be out of the scope for this pull.

**Comment by KoBeWi** [comment]
It doesn't need to be in the constructor. It can be a simple setter:
```C++
bool node_colors_enabled = true;

void set_node_colors_enabled(bool p_enabled) {
	node_colors_enabled = p_enabled
}
```

**Comment by Stronkkey** [comment]
I was talking about code separation previously, the current code isn't really separated. The `_add_nodes` function is 300+ lines long and is very hard to read because it uses up to 5 indents with no functions. 

Example of what I am talking about:
`void do_thing() {
    if (thing1) {
        // Do thing1
    }
    if (thing2) {
        // Do thing2
    }
    if (thing3) {
        // Do thing3
    }
}`
A better way to write this:
`void do_thing() {
    if (thing1) {
        do_thing1();
    }
    if (thing2) {
        do_thing2();
    }
    if (thing3) {
        do_thing3();
    }
}`

**Comment by Stronkkey** [comment]
Also, are you going to review this?

**Comment by KoBeWi** [comment]
This is a half-solution. I initially missed the NodePath issue, but it needs fixing too.
You can do a quick fix now like I suggested and make a refactor in another PR. A quick fix would be adding this on top of coloring code:
```C++
if (!node_colors_enabled) {
	// Do nothing.
} else if (connect_to_script_mode) {
...
```
> But this would be out of scope for this pull.

You could rework this PR into a refactoring one that also fixes a bug, but it'd take longer to get merged (we are too close to release for something that isn't a bugfix).

**Comment by Stronkkey** [comment]
Superseded by #84851

**Pull request closed without merging**
