### PR TITLE
Rename empty() to is_empty()

### LINKED ISSUE #1989: Rename "empty" function to "is_empty" on Array and Dictionary in GDScript
### Describe the project you are working on
Generic projects

### Describe the problem or limitation you are having in your project
Spent some hours debugging my project trying to figure out why my array wasn't "emptying". I am not fluent in English and I used the "empty" function found in autocomplete instead of "clear" thinking it would empty the array. My fault, I should have read the documentation! 😇 

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Renaming the "empty" function to "is_empty" would help to understand the purpose of the function on the fly and avoid misunderstandings

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
🤔 

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Yes, using the correct "clear" function 😄 

### Is there a reason why this should be core and not an add-on in the asset library?
🤔

### PR DESCRIPTION
**Pull request by madmiraal**
Most of Godot's data structures have the method `empty()` which returns a `bool`, and is used to determine whether or not the data structure is empty. This can be confused with the action to empty the data structure (for which most of the data structures use `clear()`). Therefore, to avoid confusion, this method should be renamed `is_empty()`.

This PR renames `empty()` to `is_empty()` in all of Godot's data structures.

Part of #16863 

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/1989.*

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]

**Comment by madmiraal** [comment]
Rebased following merge of #34193, #42013, #44436, #44472, #44499, #44531, #44605 and #44699.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by bruvzg** [comment]
Missing renames:
https://github.com/godotengine/godot/blob/8f4c4bb6106e11d4c6fe1d37e5ad294474f6bb0d/modules/text_server_fb/dynamic_font_fb.cpp#L57
https://github.com/godotengine/godot/blob/8f4c4bb6106e11d4c6fe1d37e5ad294474f6bb0d/modules/text_server_fb/text_server_fb.cpp#L553
https://github.com/godotengine/godot/blob/8f4c4bb6106e11d4c6fe1d37e5ad294474f6bb0d/modules/text_server_fb/text_server_fb.cpp#L576

**Comment by akien-mga** [comment]
Here's the full list of code locations which still refer to `.empty()`. Not sure why CI didn't fail as some of those should be included in current CI builds.
```
$ rg "\.empty\(\)" -g'!thirdparty' -g'!*.po' -g'!*.pot'
platform/javascript/http_client_javascript.cpp
81:     ERR_FAIL_COND_V(host.empty(), ERR_UNCONFIGURED);
88:                     username.empty() ? nullptr : username.utf8().get_data(),
89:                     password.empty() ? nullptr : password.utf8().get_data());
135:    return !polled_response_header.empty();
148:    if (polled_response_header.empty())

modules/mono/utils/mono_reg_utils.cpp
191:                                    ERR_BREAK(val.empty());

modules/mono/mono_gd/support/android_support.cpp
137:    if (app_native_lib_dir_cache.empty())

modules/text_server_fb/text_server_fb.cpp
553:    if (p_text.empty()) {
576:    ERR_FAIL_COND_V(span.fonts.empty(), false);

modules/text_server_fb/dynamic_font_fb.cpp
57:                     if (!font_mem_cache.empty()) {

doc/classes/TextEdit.xml
407:                            if !result.empty():

modules/fbx/fbx_parser/FBXAnimation.cpp
169:    if (curves.empty()) {

modules/fbx/fbx_parser/FBXMaterial.cpp
330:    if (Content && !Content->Tokens().empty()) {

modules/fbx/fbx_parser/FBXDocument.cpp
398:            if (tok.empty()) {
467:            if (tok.empty()) {
484:                    if (tok_2.empty()) {
552:    if (!animationStacksResolved.empty() || animationStacks.empty()) {

modules/fbx/fbx_parser/FBXParser.cpp
605:    if (tok.empty()) {
693:    if (tok.empty()) {
770:    if (tok.empty()) {
844:    if (tok.empty()) {
901:    if (tok.empty()) {
964:    if (tok.empty()) {
1030:   if (tok.empty()) {
1089:   if (tok.empty()) {

modules/fbx/fbx_parser/FBXMeshGeometry.cpp
143:    ERR_FAIL_COND_MSG(m_vertices.empty(), "mesh with no vertexes in FBX file, did you mean to delete it?");
144:    ERR_FAIL_COND_MSG(m_face_indices.empty(), "mesh has no faces, was this intended?");

modules/fbx/data/fbx_material.cpp
283:            if (name.empty()) {

platform/javascript/display_server_javascript.cpp
96:     if (target_id.empty() || target_id == String::utf8(display->canvas_id)) {

platform/javascript/api/javascript_tools_editor_plugin.cpp
111:    while (!cur.empty()) {

editor/debugger/editor_visual_profiler.cpp
669:    if (frame_metrics.empty()) {

scene/animation/animation_player.cpp
785:                    if (!backwards && cd.pos <= len && next_pos == len /*&& playback.blend.empty()*/) {
791:                    if (backwards && cd.pos >= 0 && next_pos == 0 /*&& playback.blend.empty()*/) {
```

**Comment by madmiraal** [comment]
> the .empty() in the FBX module might be a different method specific to that module.

These are from the modified Assimp library, which uses the C++ standard library container classes including `std::map`, `std::string` that use `empty()`.

**Pull request merged**
