### PR TITLE
Made some small updates to classes.xml

### PR DESCRIPTION
**Pull request by Brickcaster**
I wanted to add a some of my notes on matrix32, array, color, and sprite/set_modulate()

I goofed on the tilemap_cpp updates and submitted those as an independent pull request but I reverted them so there's a lot of commits here.  So this should only update classes.xml

### CODE REVIEW

**Comment by akien-mga** [comment]
It would be better to cleanup your fork to keep only the relevant commits. The rest add unnecessary clutter, and since it's in a fork, you can edit it as much as you want so that only relevant stuff gets pushed upstream.

You can e.g. rewrite your commit history with:
```git rebase -i HEAD~8```
It will open an editor that will list the 8 last commits of your branch (i.e. the seven listed above and the one before, just so you know where you stand in the history).

Then you can edit each line to define what you want to do with the related commit. You could then remove the lines that correspond to irrelevant changes, and keep only the three commits about classes.xml.

**Comment by Brickcaster** [comment]
@akien-mga Akien-mga, I tried to update it using the command you gave me and it seems to have created even more commits instead!  I really suck at this git management thing.

**Comment by akien-mga** [comment]
Hm, then I would suggest that you close this PR, and then create a new clean branch from okamstudio/godot and cherry-pick the relevant commits there.

Once in the new branch, you should be able to cherry-pick them with "git cherry-pick".

**Comment by Brickcaster** [comment]
I'm gonna resubmit this and hopefully do it properly.

**Pull request closed without merging**
