### PR TITLE
Fix Node arrays appear as Object arrays in the inspector

### LINKED ISSUE #75982: Node arrays appear as Object arrays in the inspector
### Godot version

4.1 cd03028

### System information

Windows 10 x64

### Issue description

image
Exported node arrays display Object instead of the node type. This does not happen with Resources.

### Steps to reproduce

1.
```GDScript
@export var nodes: Array[Node2D]
```
2. Check the inspector

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by nongvantinh**
Fixes: #75982

### CODE REVIEW

**Comment by nongvantinh** [comment]
Hi @kleonc, could you please explain the purpose of the label `cherrypick:4.0` that I have noticed on my PR on occasion? I checked the documentation, and it appears to describe a feature that can be incorporated into a stable branch after being merged into the master branch. Should I create a Pull Request to backport this feature to the current 4.0 branch, or is it best to leave this task to the team members?

**Comment by kleonc** [comment]
> Hi @kleonc, could you please explain the purpose of the label `cherrypick:4.0` that I have noticed on my PR on occasion? I checked the documentation, and it appears to describe a feature that can be incorporated into a stable branch after being merged into the master branch. Should I create a Pull Request to backport this feature to the current 4.0 branch, or is it best to leave this task to the team members?

@nongvantinh It means that after merging this PR to the `master` branch (which currently is for 4.x (as of now future 4.1)) the changes should also be applied to the 4.0 branch (for the future 4.0.x version). From time to time a maintainer will look at such marked PRs and batch them together in a single PR, e.g. like in #76476.
If the code is the same between the branches then the commit can be cherry-picked as is, the same changes can be applied, and the maintainer will include such changes. If the differences are trivial then they will also likely apply them. Otherwise they'd write in the relevant PR that the PR/commit is not easily cherry-pickable and hence a separate dedicated PR is needed against the 4.0 branch.
So no further action is needed from you, unless you'll be asked for it. :slightly_smiling_face:

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
