### PR TITLE
Improve EditorSpinSlider dragging with more precision on demand

### LINKED ISSUE #1506: Godot 4.0 UI/UX - Dragging Float Number Input Fields
**Describe the project you are working on:**
Space Tactical RPG https://twitter.com/ZeroPointGame

**Describe the problem or limitation you are having in your project:**
This proposal is part of a much more complete UI/UX overhaul and should be considered with this view about Godot Editor problems and Suggestions: https://github.com/godotengine/godot-proposals/issues/1503

### Dragging Float Number Input Fields

69Z6iIRMB5

When dragging a number input field in inspector the values seems normalized by type. What it means is that if a field has float values they are always normalized in -1 to 1 and Integer in -1000 to 1000 (Don't know the right values but this is the amplitude of a mouse movement approximately). There's a modifier to allow to decrease the rate of change and it's useful to integers but for float values with large numbers like used in Transform Inspector it is useless. Is currently impracticable to handle float fields that use values > 1 without a tendinitis.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**
**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Normalize the float values the same high numbers it's done with Integers but add a proporcional mouse movement in a way that slow mouse movements will change by 0.1, mid will change by 1.0 and fast will change to 10. That way you can keep the same amplitude of values you have in int number fields and keep the resolution if the user want to change small values. This can also be applied to int unifying the behavior but with another scale 1/10/100 e.g

Keeping the SHIFT modifier also could force the lower change rate independent of the mouse velocity. Also if something is normalized only in small values like 0~1 it would use the slider component anyway. It would fix manipulation in all Transform inspector parameters and exported float fields.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Will be used often

**Is there a reason why this should be core and not an add-on in the asset library?:**
It's a core editor feature.

### PR DESCRIPTION
**Pull request by gongpha**
Related [godotengine/godot-proposals#1506](https://github.com/godotengine/godot-proposals/issues/1506)

Inspired from Garry's Mod. This made default inspector sliders to have more control of precision and scale.

Depend on each slider option. If they allowed value to be greater and lesser, Steps and using rounded value.

ภาพ

ภาพ
ภาพ

*Bugsquad edit: This closes https://github.com/godotengine/godot-proposals/issues/1506.*

### CODE REVIEW

**Comment by Calinou** [comment]
I don't understand the need for the visual scale, can you explain? It's quite large.

**Comment by Zireael07** [comment]
IMHO the visual scale is really cool (and useful) but it could indeed be smaller to better fit with other editor elements.

**Comment by gongpha** [comment]
> I don't understand the need for the visual scale, can you explain what it's useful for? It's quite large.

Sorry for less explanation. Its purpose is not just visualizing a scale. We can also drag the mouse forward to zoom in on the dial and drag it back to zoom out the dial. This allows us to get the value in the desired precision. But I think this will more useful when zooming out and move to get more step. The old one is just moving on its step constantly. But not satisfied if want more/less value. As a problem like [godotengine/godot-proposals#1506](https://github.com/godotengine/godot-proposals/issues/1506).

> IMHO the visual scale is really cool (and useful) but it could indeed be smaller to better fit with other editor elements.

I think the same. And maybe my current font in the screenshot is too big too. (And I used this for the test.)

**Comment by gongpha** [comment]
Current looks :
a

**Comment by gongpha** [comment]
Superseded by #107645

**Pull request closed without merging**
