### PR TITLE
Create a new option `disable_xr` for disbling xr nodes and server

### PR DESCRIPTION
**Pull request by ghost**
### Supposed usage

For 3d game that doesn't use xr (its almost all 3d games)

### Structure of the PR

1. First two commits introduce `disable_xr` option. These are 99,99% safe because they only shuffle some files (files on which no one depends)
2. One commit about removing `openxr` options which effectively is the same as `module_openxr_enabled`.  I think it doesn't need any dedicated solution which just mirrors behavior of existing systematic feature. So it even could be standalone PR. The only problem here that it breaks backward compatibility
3. Disabling XR checks inside `servers/rendering/renderer_rd` and `drivers/gles3` which are essentially checks for additional settings necessary for xr which are useless if you doesn't want to have xr. I am almost sure these are harmless
4. Finally disabling xr server and all the places which depend on it. A messy bunch of defines. The code wasn't designed for these defines so they look really weird. I am sure there are plenty of bugs and problems but I can't see them

It works but with the simplest project. It compiled and I even could normally export and run minimal 3d project with one model, light and camera

### Results

Linux binary size comparison (scons target=template_release production=yes use_llvm=yes):

1. Without disabling anything: **71.409 MiB (74878304 bytes)**
6. Disabling all xr modules: **70.163 MiB (73571648 bytes)**
7. Disabling all xr modules, nodes and server: **69.487 MiB (72863040 bytes)**

Previously you could achieve the results of disabling all xr modules so this PR will let you to save **0.675 MiB (708608 bytes)**. Which is much less than any normal 3d model and even less than it's texture... So it didn't have any sense... There are archived and not planned labels so I think this PR is perfect for them.

P.S Yeah, I read best practices for contributors in docs. And yeah I violated two of them, so sorry...

### CODE REVIEW

**Comment by Calinou** [comment]
> 2. One commit about removing openxr options which effectively is the same as module_openxr_enabled. I think it doesn't need any dedicated solution which just mirrors behavior of existing systematic feature. So it even could be standalone PR. The only problem here that it breaks backward compatibility

I would keep `openxr=no` as an alias for `disable_xr=yes` (with a message printed to tell the user that the `openxr` option is deprecated). This way, we avoid breaking people's build scripts.

Something like this: https://github.com/godotengine/godot/blob/506d6e427a4eecfc1e5e5ee1180019a876119701/SConstruct#L365-L370

**Comment by BastiaanOlij** [comment]
I don't think this should replace the openxr switch. OpenXR is but one implementation that uses the XR system.

If the XR nodes are removed (which is very little code, the bulk is in the modules) then yes, any core XR module should be removed with it (e.g. WebXR, OpenXR, MobileVR etc), but people targeting "Cardboardish" VR or WebXR, or use any of the external XR interfaces such as TiltFive or OpenVR, may wish to remove just the parts they are not using.

WebXR is a bit of an exception here seeing web already selectively excludes the other modules but the principle stands.

**Comment by dustdfg** [comment]
> I would keep `openxr=no` as an alias for `disable_xr=yes` (with a message printed to tell the user that the `openxr` option is deprecated). This way, we avoid breaking people's build scripts.

I understand what you mean but like already was said these options aren't equal. And `openxr=no` is the same as `module_openxr_enabled` so creating an alias isn't difficult but will require two modifications:

1. As you proposed to check it with if if `env["openxr"]`
2. Mention it in definition of the property itself so `scons -h` will warn you too
https://github.com/godotengine/godot/blob/506d6e427a4eecfc1e5e5ee1180019a876119701/SConstruct#L227-L227

**Comment by dsnopek** [comment]
I agree with Bastiaan. If we add a `disable_xr` option, setting `disable_xr=yes` should imply `openxr=no` and `webxr=no`, but we still need to have the `openxr` and `webxr` options, since someone may want to keep XR enabled, but disable `openxr`, if, for example, they wanted to build an app for Tilt5 and were going to use the [Tilt5Godot4](https://github.com/GodotVR/TiltFiveGodot4) extension.

**Comment by dustdfg** [comment]
> I agree with Bastiaan. If we add a `disable_xr` option, setting `disable_xr=yes` should imply `openxr=no` and `webxr=no`, but we still need to have the `openxr` and `webxr` options, since someone may want to keep XR enabled, but disable `openxr`, if, for example, they wanted to build an app for Tilt5 and were going to use the [Tilt5Godot4](https://github.com/GodotVR/TiltFiveGodot4) extension.

But it they already exist. I just add option to disable xr nodes and xr server.

Currently we have 3 xr modules each of them can be disabled:

* `module_openxr_enabled="no"`
* `module_webxr_enabled="no"`
* `module_mobile_vr_enabled="no"`

And we have option `openxr="no"` which is absolutely the same as `module_openxr_enabled="no"`. What my PR does is removes unnecessary `openxr="no"` which because it is just a module and should be disabled via `module_openxr_enabled="no"`. And this PR introduces `disable_xr` which is an alias for all 3 module disabling + disables xr nodes and servers. If you doesn't use xr you just use `disable_xr` to disable whole xr. If you use any xr, you disable modules you doesn't need. Before this pr you could disable 3 modules and still you can disable 3 modules without disabling server and nodes but this pr lets you to disable them if you want. 

What about `openxr` option it just doesn't have sense to have two options for disabling one module. `openxr` doesn't do anything except disabling one openxr module. We have `module_openxr_enabled` which is "auto-generated" option it is much better...

**Comment by dustdfg** [comment]
There is `disable_3d` option. Which disables all 3d modules + disables 3d nodes and servers. But if you need 3d but doesn't need some modules you can disable them without fully disabling nodes and using `disable_3d`. Here is the same thing...

**Comment by dsnopek** [comment]
> And we have option `openxr="no"` which is absolutely the same as `module_openxr_enabled="no"`. What my PR does is removes unnecessary `openxr="no"` which because it is just a module and should be disabled via `module_openxr_enabled="no"`.

Ah, ok, I didn't realize that the `openxr` option was _extra_. I guess then it's just a question of whether we want to keep it as an alias (so we don't break folks build scripts) or remove it completely.

**Comment by dustdfg** [comment]
Not mergeable anymore. I don't want to update it and it didn't got any testing. It will also become less actual if I or someone else will start enhancing the builtin editor which can disable nodes. Though `openxr` option is useless and not well. Users don't suffer so...

**Comment by dustdfg** [comment]
Superseded by #103267 👀

**Pull request closed without merging**
