### PR TITLE
Fix crash when setting Material's next pass to itself

### LINKED ISSUE #19672: Editor crashes when setting a Shader Material's next pass to itself.
**Godot version:**
Godot v3.1.dev.calinou.5c5aafa

**OS/device including version:**
Windows 10 Professional 64 bit

**Issue description:**
Editor Crashed when setting a shader's next pass to it self.
I expected and error message tbh.

**Steps to reproduce:**

1. Create a shader material and save it.
2. Edit shader by giving it a next pass.
3. Select the shader as it's own next pass.
4. Crash.

**Minimal reproduction project:**
Can't save the project as it crashes the editor :/.

**Note**
It was an accident, I swear!

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #19672

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by JFonS** [comment]
Maybe it would be nice to add some sort of warning to this situation. So that users know something weird is going on.

**Comment by Chaosus** [comment]
Please suggest what text will be in that message(I guess it should be message box)

**Comment by Chaosus** [comment]
Ah.. @JFonS  AcceptDialog is editor thing which should not be linked to such low level thing like Material. I could push it to ERR_FAIL_COND instead. What do you think ?

**Comment by Chaosus** [comment]
Ok, I guess ERR_FAIL_COND is enough for understand

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
