### PR TITLE
Added partial German translation.

### PR DESCRIPTION
**Pull request by paviro**

### CODE REVIEW

**Comment by akien-mga** [comment]
Nice work! Could you however try to rebase to remove the `de.mo` file? It's a binary file that Godot won't have use for (it parses the PO directly), so we shouldn't introduce it in the first place.

You should be able to get rid of it with (in your git branch):
```
git rm tools/translations/de.mo
git commit --amend  // that will edit the previous commit
git push --force origin master   // force push needed as the previous command changed the history
```

**Comment by paviro** [comment]
What exactly is its use then? Does the translation program need it?

**Comment by vnen** [comment]
The translation program does not need it. Usually programs use the `.mo` binary file as source for translation (because binary usually is faster). Godot does not need because we compile it together with the engine.

**Comment by paviro** [comment]
Ah I see thanks for the explanation! Will remove it when I am back at my computer :)

**Comment by paviro** [comment]
Done :)

**Pull request merged**
