### PR TITLE
Update KinematicBody2D.xml

### PR DESCRIPTION
**Pull request by Vlad-Zumer**
added test_only doc

### CODE REVIEW

**Comment by 2DemiGods** [comment]
will this appear in Docs for 3.1 as well?

**Comment by groud** [comment]
Close top be the first one, this is a duplicate of #30810 then. ^^

**Comment by Xrayez** [comment]
Ninja'd indeed.

In that case you could rebase your contribution towards 3.1 branch instead of master?

@akien-mga feel free to close my PR.

**Comment by groud** [comment]
> In that case you could rebase your contribution towards 3.1 branch instead of master?

Not, that's not how we do things. Commits are cherry-picked from master.

**Comment by Xrayez** [comment]
@2DemiGods I added you as a co-author in my PR (#30810) so that it will count as your contribution as well, this could be closed instead I think.

**Comment by akien-mga** [comment]
I'll merge #30810 as the commit message is more explicit.

Thanks for the contribution nevertheless :)

**Pull request closed without merging**
