### PR TITLE
Fix to some operators in shaders are not compiled properly

### LINKED ISSUE #75351: Unary minus does not work in gdshaders
### Godot version

v4.1.dev.custom_build [6ef2f358c]

### System information

Fedora 37 KDE, RTX 3080

### Issue description

Godot's shader compiler removes spaces and parentheses from expression, causing unary minus (and probably the less common unary plus) to merge with adjacent operator tokens.

Addtionally, the only error logged in the editor is:
> servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:171 - Condition "!shader_singleton->shader.version_is_valid(version)" is true.

If running the editor from a console, it prints the compiled shader, the error message from the glsl compiler, and then it prints the compiled shader again.

### Steps to reproduce

```
void fragment() {
	float a = 0.5;
	float b = 1.0 - -a;
	float c = 1.0 - -0.5;
	float d = 1.0 - (-0.5);
	float e = 1.0 - -(0.5);
}
```

```
2145 |  {
2146 |          float m_a=0.5;
2147 |          float m_b=(1.0--m_a);
2148 |          float m_c=(1.0--0.5);
2149 |          float m_d=(1.0--0.5);
2150 |          float m_e=(1.0--0.5);
2151 |  }
```

### Minimal reproduction project

Trivial. Just copy one of the expressions into a new shader.

### PR DESCRIPTION
**Pull request by Chaosus**
Fix https://github.com/godotengine/godot/issues/75351

### CODE REVIEW

**Comment by JohanAR** [comment]
I applied this fix to commit work branch, which admittedly contains a few other changes, but it seems like it fixes the unary minus examples I had in my issue.

However, I've discovered a new case which it seems like it doesn't solve:
`float a = - -1.0;`

Which probably isn't very common in shaders, but I'm working on a couple of unit tests for the shader preprocessor, and it could occur from something like:
```
#define A -1.0
float a = -A;
```

I also tried this commit with my current large project, and it did not seem to break anything.

**Review by clayjohn — APPROVED** [review]
Seems fine to merge for now. JohanAR's comment is beyond the scope of this PR and is likely something that needs to be fixed on the macro preprocessor side of things

**Comment by JohanAR** [comment]
@clayjohn that error happens without macros. I only meant it as an example of what might lead expression like that, so it doesn't get dismissed as an unlikely edge case :)

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
