### PR TITLE
Fix godot project extension not recognized (again)

### PR DESCRIPTION
**Pull request by melix99**
This fixes that playing a godot project opens the project manager.

### CODE REVIEW

**Review by bojidar-bg — APPROVED** [review]

**Comment by bojidar-bg** [comment]
Note: this reverts #8447, which is needed since #8375 was reverted in #8579...

**Comment by akien-mga** [comment]
Let's merge a new version of #8375 instead, it shouldn't have been reverted in the first place, but that was a misunderstanding from @reduz. We just need it redone with hardcoded `project.godot` instead of allowing any filename as long as the extension is good.

**Comment by reduz** [comment]
Apologies, I misunderstood what it was. I think together with this we
should probably add functionality in os.h to register extensions

**Comment by akien-mga** [comment]
@reduz Actually looking at the code again, I think it was fine to revert, since 80% of the code was about allowing a custom filename with ".godot" extension. I'm about to push a PR which just changes the hardcoded filename.

**Comment by akien-mga** [comment]
Superseded by #8610.

**Pull request closed without merging**
