### PR TITLE
miniupnpc: Update to version 2.2.2

### PR DESCRIPTION
**Pull request by akien-mga**
Things to review:

- I didn't reapply the patch from #35953 as upstream code around it seems to have been updated, so it *might* have fixed the bug we were experiencing. Needs to be checked by @Faless (BTW you mentioned you'd report it upstream, was it done?)
- I reordered the files in the `SCsub` to match the `CMakeLists.txt` and include the new one in this update (`addr_is_reserved.c`). I noticed that two of the lib's files are not being built currently (commented out), is this intended?

Changelog: http://miniupnp.free.fr/files/changelog.php?file=miniupnpc-2.2.2.tar.gz

### CODE REVIEW

**Comment by akien-mga** [comment]
Updated to 2.2.2 released last week.

**Comment by Faless** [comment]
>     * I noticed that two of the lib's files are not being built currently (commented out), is this intended?

Yeah, those either contain a `main` (i.e. are programs) or are helper `c` files for those programs.
I think they should move them out to a program/example folder.

>     * I didn't reapply the patch from #35953 as upstream code around it seems to have been updated, so it _might_ have fixed the bug we were experiencing. Needs to be checked by @Faless (BTW you mentioned you'd report it upstream, was it done?)

Well, I don't remember, but I don't think I did. I'll be testing it on windows though, and let you know.

**Comment by Faless** [comment]
> Well, I don't remember, but I don't think I did. I'll be testing it on windows though, and let you know.

Still broken :( .

**Comment by akien-mga** [comment]
We might need a new patch then as the code changed significantly so I'm not sure how to adapt it (nor how to test that it works).

**Comment by Faless** [comment]
> We might need a new patch then as the code changed significantly so I'm not sure how to adapt it (nor how to test that it works).

I'm on it, it's really weird that it's still not fixed upstream. So it's either something we do, or, I suspect, the fact that the flag they are checking is not active in their cmake builds (maybe it overrides the buildver).

**Comment by akien-mga** [comment]
> Yeah, those either contain a `main` (i.e. are programs) or are helper `c` files for those programs.
> I think they should move them out to a program/example folder.

Thanks, I updated the PR to remove those files (and listed them in `thirdparty/README.md`).

Might be worth suggesting to upstream to make a better separation between the C lib code and the samples, standalone tools, tests, and python module.

**Review by Faless — APPROVED** [review]
Looks good :+1:

**Comment by Faless** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Pull request merged**
