### PR TITLE
Allow concurrent buffering and dispatch of input events

### LINKED ISSUE #75893: Android [split_config.arm64_v8a.apk!libc++_shared.so] std::__ndk1::recursive_mutex::lock() ANR
### Godot version

3.6.1.beta

### System information

Android, GLES2

### Issue description

Multiple ANRs.

```
"main" tid=1 Native
  #00  pc 0x000000000001ed2c  /system/lib64/libc.so (syscall+28)
  #01  pc 0x000000000002202c  /system/lib64/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+140)
  #02  pc 0x00000000000840f0  /system/lib64/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+632)
  #03  pc 0x00000000000c2d30  /data/app/com.mygame-8MPfiTRLHD8Ji_TFwFmX5g==/split_config.arm64_v8a.apk (std::__ndk1::recursive_mutex::lock()+12)
  at org.godotengine.godot.GodotLib.touch (Native method)
  at org.godotengine.godot.input.GodotInputHandler.onTouchEvent (GodotInputHandler.java:175)
  at org.godotengine.godot.GodotView.onTouchEvent (GodotView.java:108)
  at android.view.View.dispatchTouchEvent (View.java:12555)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3083)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2741)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3083)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2741)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3083)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2741)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3083)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2741)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3083)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2741)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:474)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1830)
  at android.app.Activity.dispatchTouchEvent (Activity.java:3400)
  at com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:432)
  at android.view.View.dispatchPointerEvent (View.java:12799)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:5314)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5108)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4621)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4674)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4640)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:4780)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4648)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:4837)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4621)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:4674)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:4640)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:4648)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:4621)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:7394)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:7346)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:7297)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:7551)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:186)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.app.ActivityThread.main (ActivityThread.java:6760)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)

"Signal Catcher" tid=3 Runnable
  #00  pc 0x00000000003c7ac4  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+220)
  #01  pc 0x0000000000496520  /system/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+352)
  #02  pc 0x00000000004b0564  /system/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+996)
  #03  pc 0x00000000004a9208  /system/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+488)
  #04  pc 0x00000000004a864c  /system/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+1036)
  #05  pc 0x00000000004a8154  /system/lib64/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+884)
  #06  pc 0x0000000000478004  /system/lib64/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+188)
  #07  pc 0x0000000000483ecc  /system/lib64/libart.so (art::SignalCatcher::HandleSigQuit()+1372)
  #08  pc 0x0000000000482bc0  /system/lib64/libart.so (art::SignalCatcher::Run(void*)+256)
  #09  pc 0x0000000000083134  /system/lib64/libc.so (__pthread_start(void*)+36)
  #10  pc 0x00000000000233bc  /system/lib64/libc.so (__start_thread+68)

"Jit thread pool worker thread 0" tid=2 Native
  #00  pc 0x000000000001ed2c  /system/lib64/libc.so (syscall+28)
  #01  pc 0x00000000000d7424  /system/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
  #02  pc 0x00000000004b1ddc  /system/lib64/libart.so (art::ThreadPool::GetTask(art::Thread*)+260)
  #03  pc 0x00000000004b1334  /system/lib64/libart.so (art::ThreadPoolWorker::Run()+124)
  #04  pc 0x00000000004b0de4  /system/lib64/libart.so (art::ThreadPoolWorker::Callback(void*)+148)
  #05  pc 0x0000000000083134  /system/lib64/libc.so (__pthread_start(void*)+36)
  #06  pc 0x00000000000233bc  /system/lib64/libc.so (__start_thread+68)

"ReferenceQueueDaemon" tid=4 Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Daemons$ReferenceQueueDaemon.runInternal (Daemons.java:178)
  at java.lang.Daemons$Daemon.run (Daemons.java:103)
  at java.lang.Thread.run (Thread.java:764)

"FinalizerDaemon" tid=5 Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Object.wait (Object.java:422)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:188)
  at java.lang.ref.ReferenceQueue.remove (ReferenceQueue.java:209)
  at java.lang.Daemons$FinalizerDaemon.runInternal (Daemons.java:232)
  at java.lang.Daemons$Daemon.run (Daemons.java:103)
  at java.lang.Thread.run (Thread.java:764)

"FinalizerWatchdogDaemon" tid=6 Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded (Daemons.java:297)
  at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal (Daemons.java:277)
  at java.lang.Daemons$Daemon.run (Daemons.java:103)
  at java.lang.Thread.run (Thread.java:764)

"HeapTaskDaemon" tid=7 Waiting
  #00  pc 0x000000000001ed2c  /system/lib64/libc.so (syscall+28)
  #01  pc 0x00000000000d7424  /system/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
  #02  pc 0x000000000022f7d8  /system/lib64/libart.so (art::gc::TaskProcessor::GetTask(art::Thread*)+504)
  #03  pc 0x0000000000230050  /system/lib64/libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*)+96)
  at dalvik.system.VMRuntime.runHeapTasks (Native method)
  at java.lang.Daemons$HeapTaskDaemon.runInternal (Daemons.java:475)
  at java.lang.Daemons$Daemon.run (Daemons.java:103)
  at java.lang.Thread.run (Thread.java:764)

"Binder:18496_1" tid=8 Native
  #00  pc 0x000000000006f6ec  /system/lib64/libc.so (__ioctl+4)
  #01  pc 0x0000000000029168  /system/lib64/libc.so (ioctl+136)
  #02  pc 0x000000000005a844  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+260)
  #03  pc 0x000000000005aa20  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+24)
  #04  pc 0x000000000005b174  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+60)
  #05  pc 0x000000000007bc4c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+28)
  #06  pc 0x000000000000fc08  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
  #07  pc 0x00000000000b6634  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
  #08  pc 0x0000000000083134  /system/lib64/libc.so (__pthread_start(void*)+36)
  #09  pc 0x00000000000233bc  /system/lib64/libc.so (__start_thread+68)

"Binder:18496_2" tid=9 Native
  #00  pc 0x000000000006f6ec  /system/lib64/libc.so (__ioctl+4)
  #01  pc 0x0000000000029168  /system/lib64/libc.so (ioctl+136)
  #02  pc 0x000000000005a844  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+260)
  #03  pc 0x000000000005aa20  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+24)
  #04  pc 0x000000000005b174  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+60)
  #05  pc 0x000000000007bc4c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+28)
  #06  pc 0x000000000000fc08  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
  #07  pc 0x00000000000b6634  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
  #08  pc 0x0000000000083134  /system/lib64/libc.so (__pthread_start(void*)+36)
  #09  pc 0x00000000000233bc  /system/lib64/libc.so (__start_thread+68)

"Profile Saver" tid=10 Native
  #00  pc 0x000000000001ed2c  /system/lib64/libc.so (syscall+28)
  #01  pc 0x00000000000d7424  /system/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
  #02  pc 0x00000000003261a0  /system/lib64/libart.so (art::ProfileSaver::Run()+384)
  #03  pc 0x00000000003295ac  /system/lib64/libart.so (art::ProfileSaver::RunProfileSaverThread(void*)+92)
  #04  pc 0x0000000000083134  /system/lib64/libc.so (__pthread_start(void*)+36)
  #05  pc 0x00000000000233bc  /system/lib64/libc.so (__start_thread+68)

"ScionFrontendApi" tid=12 Timed Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Thread.parkFor$ (Thread.java:2137)
  at sun.misc.Unsafe.park (Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2101)
  at java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:467)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1091)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

"GmsDynamite" tid=14 Waiting
  at java.lang.Object.wait (Native method)
  at com.google.android.gms.dynamite.zza.run (com.google.android.gms:play-services-basement@@18.1.0:2)

"WM.task-1" tid=15 Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Thread.parkFor$ (Thread.java:2137)
  at sun.misc.Unsafe.park (Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2059)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:442)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

"WM.task-2" tid=16 Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Thread.parkFor$ (Thread.java:2137)
  at sun.misc.Unsafe.park (Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.park (LockSupport.java:190)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await (AbstractQueuedSynchronizer.java:2059)
  at java.util.concurrent.LinkedBlockingQueue.take (LinkedBlockingQueue.java:442)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

"GoogleApiHandler" tid=17 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 0x0000000000014114  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 0x00000000001231e4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.os.HandlerThread.run (HandlerThread.java:65)

"magnifier pixel copy result handler" tid=18 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 0x0000000000014114  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 0x00000000001231e4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.os.HandlerThread.run (HandlerThread.java:65)

"GLThread 1442" tid=19 Native
  #00  pc 0x0000000000070124  /system/lib64/libc.so (read+4)
  #01  pc 0x000000000007b55c  /system/lib64/libc.so (__sread+44)
  #02  pc 0x000000000007b4bc  /system/lib64/libc.so (__srefill+268)
  #03  pc 0x000000000007f1f8  /system/lib64/libc.so (fread_unlocked+200)
  #04  pc 0x000000000007f0e8  /system/lib64/libc.so (fread+72)
  #05  pc 0x0000000000037dd4  /system/lib64/libc.so (android_getaddrinfofornetcontext+2388)
  #06  pc 0x0000000000037458  /system/lib64/libc.so (android_getaddrinfofornet+56)
  #07  pc 0x000000000002acd8  /system/lib64/libjavacore.so (Linux_android_getaddrinfo(_JNIEnv*, _jobject*, _jstring*, _jobject*, int)+336)
  at libcore.io.Linux.android_getaddrinfo (Native method)
  at libcore.io.BlockGuardOs.android_getaddrinfo (BlockGuardOs.java:172)
  at java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:137)
  at java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:105)
  at java.net.InetAddress.getAllByName (InetAddress.java:1154)
  at com.android.okhttp.Dns$1.lookup (Dns.java:39)
  at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:175)
  at com.android.okhttp.internal.http.RouteSelector.nextProxy (RouteSelector.java:141)
  at com.android.okhttp.internal.http.RouteSelector.next (RouteSelector.java:83)
  at com.android.okhttp.internal.http.StreamAllocation.findConnection (StreamAllocation.java:174)
  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection (StreamAllocation.java:126)
  at com.android.okhttp.internal.http.StreamAllocation.newStream (StreamAllocation.java:95)
  at com.android.okhttp.internal.http.HttpEngine.connect (HttpEngine.java:299)
  at com.android.okhttp.internal.http.HttpEngine.sendRequest (HttpEngine.java:237)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute (HttpURLConnectionImpl.java:472)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse (HttpURLConnectionImpl.java:418)
  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode (HttpURLConnectionImpl.java:549)
  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode (DelegatingHttpsURLConnection.java:105)
  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode (HttpsURLConnectionImpl.java:26)
  at com.mygame.GPack.isConnectedToInternet (GPack.java:395)
  at com.mygame.GPack.askForReview (GPack.java:125)
  at org.godotengine.godot.GodotLib.step (Native method)
  at org.godotengine.godot.GodotRenderer.onDrawFrame (GodotRenderer.java:57)
  at org.godotengine.godot.gl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1576)
  at org.godotengine.godot.gl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1278)

"queued-work-looper" tid=22 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 0x0000000000014114  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 0x00000000001231e4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.os.HandlerThread.run (HandlerThread.java:65)

"ConnectivityThread" tid=11 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 0x0000000000014114  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 0x00000000001231e4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.os.HandlerThread.run (HandlerThread.java:65)

"GoogleApiHandler" tid=25 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 0x0000000000014114  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 0x00000000001231e4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.os.HandlerThread.run (HandlerThread.java:65)

"AdWorker(NG) #1" tid=26 Timed Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Thread.parkFor$ (Thread.java:2137)
  at sun.misc.Unsafe.park (Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2101)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:1132)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:849)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

"pool-4-thread-1" tid=28 Timed Waiting
  at java.lang.Object.wait (Native method)
  at java.lang.Thread.parkFor$ (Thread.java:2137)
  at sun.misc.Unsafe.park (Unsafe.java:358)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2101)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:1132)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take (ScheduledThreadPoolExecutor.java:849)
  at java.util.concurrent.ThreadPoolExecutor.getTask (ThreadPoolExecutor.java:1092)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

"Chrome_ProcessLauncherThread" tid=30 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 0x0000000000014114  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 0x00000000001231e4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.os.HandlerThread.run (HandlerThread.java:65)

"GoogleApiHandler" tid=33 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 0x0000000000014114  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 0x00000000001231e4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:327)
  at android.os.Looper.loop (Looper.java:196)
  at android.os.HandlerThread.run (HandlerThread.java:65)

"Chrome_IOThread" tid=34 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x00000000045144c0  /data/app/com.android.chrome-5y1WJhCX8DHAFFN7LHLdNw==/base.apk

"ThreadPoolForeg" tid=35 Native
  #00  pc 0x000000000001ed30  /system/lib64/libc.so (syscall+32)
  #01  pc 0x000000000002202c  /system/lib64/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+140)
  #02  pc 0x00000000000826e0  /system/lib64/libc.so (pthread_cond_timedwait+120)
  #03  pc 0x00000000022aa348  /data/app/com.android.chrome-5y1WJhCX8DHAFFN7LHLdNw==/base.apk

"Binder:18496_3" tid=36 Native
  #00  pc 0x000000000006f6ec  /system/lib64/libc.so (__ioctl+4)
  #01  pc 0x0000000000029168  /system/lib64/libc.so (ioctl+136)
  #02  pc 0x000000000005a844  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+260)
  #03  pc 0x000000000005aa20  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+24)
  #04  pc 0x000000000005b174  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+60)
  #05  pc 0x000000000007bc4c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+28)
  #06  pc 0x000000000000fc08  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
  #07  pc 0x00000000000b6634  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
  #08  pc 0x0000000000083134  /system/lib64/libc.so (__pthread_start(void*)+36)
  #09  pc 0x00000000000233bc  /system/lib64/libc.so (__start_thread+68)

"PlatformServiceBridgeHandlerThread" tid=37 Native
  #00  pc 0x000000000006f600  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 0x0000000000014248  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
```
  
  
 In Google Play Dashboard there is extra message about the ANR:
 **This native synchronization routine is blocking the main thread, causing an ANR**
 
 I'm using quite a few Android plugins (I put the all in one plugin):
 
 ```
    implementation 'com.google.firebase:firebase-analytics:21.2.0'
    implementation 'com.google.android.gms:play-services-ads:21.3.0'
    implementation 'com.google.android.ump:user-messaging-platform:2.0.0'
    implementation "com.google.android.gms:play-services-games-v2:17.0.0"
    implementation 'com.google.android.play:review:2.0.1'
```
I use also GodotGooglePlayBilling

I'm not sure if it is bug or misuse of the engine - but I cannot provide you the steps to reproduce or MRP.

### Steps to reproduce

I cannot provide this.

### Minimal reproduction project

I cannot provide this.

### PR DESCRIPTION
**Pull request by RandomShaper**
Fixes #75893.

Tagged as _platform_android_, but it really affects any hypothetical platform where Godot's main thread is not the app main/UI thread.

@m4gr3d, @lawnjelly, in the end I've taken a simpler route than double buffering or flushing a copy of the list.

Sadly, I have no time at the moment to test this. Tagging as such.

Counterpart for 3.x is #76400.

**UPDATE:** Let me give an explanation of what this PR does:
- `_parse_input_event_impl()` is the "backend" of input event handling, the function that dispatches the events to the engine and user code. It holds a lock because it can still read/write some common data,
- On Android we have a special threading situation: Android main/UI thread _is not_ Godot's main thread; Android's GL thread _is_ Godot's main thread. Therefore, input events are received in the Android UI thread and buffered there; later, they are flushed on the GL thread (Godot's main thread). Without this PR, a lock can be held for too long during the flush/dispatch stage, depending on what user code does (like loading a level), preventing the Android UI thread from buffering subsequent input events for loo long (causing the ANR).

### CODE REVIEW

**Review by lawnjelly — APPROVED** [review]

**Comment by lawnjelly** [comment]
```
lawnjelly
RandomShaper Ok it seems worth a try, will approve. I'm not totally sure is thread safe but am happy to trust you on that.


RandomShaper
7:41 AM
Thanks!
_parse_input_event_impl() will always be run on Godot's main thread.
I will add an assertion about that so that's clearer for readers of the code and also enforced at the machine level.

lawnjelly
lawnjelly
7:42 AM
Well it can be called directly if no buffering or accumulation I think?
So if any other platforms call from not the main thread in that situation?


m4gr3d
7:43 AM
I'll take a look.
I'm trying to see if I can repro the state that causes the ANR with the current code.
I want to test the PR with that repro project and see if that resolves the issue.

RandomShaper
[7:35 AM](https://chat.godotengine.org/channel/android?msg=NHwixWTAh6A9SRpcz)
@m4gr3d, would you take a look?
👍 1 


RandomShaper
7:44 AM
Yes. And in that case it's still Godot's main thread.

lawnjelly
[7:42 AM](https://chat.godotengine.org/channel/android?msg=rjz4Z6avbfQhYrbuL)
Well it can be called directly if no buffering or accumulation I think?
Any platform having split threads has to enable input buffering (that's an engine internal thing, orthogonal to input accumulation).

lawnjelly
[7:43 AM](https://chat.godotengine.org/channel/android?msg=puvQdeS5vtv7fTLDi)
So if any other platforms call from not the main thread in that situation?

lawnjelly
lawnjelly
7:48 AM
RandomShaper The main danger is that if an incoming event added to the buffer and mucked up the list iteration while flush_buffers() was still running on the main thread.
So am trusting that you have worked out this can't happen.


RandomShaper
7:52 AM
I changed the code that iterates the list, but now you mention it I should at least add a comment about it.

lawnjelly
lawnjelly
7:54 AM
It looks like (in 4.x at least) it just pops the front each time in flush_buffered_events() so it should be ok I think.
It would be very easy to inadvertently break in future though so perhaps a comment would be good to this effect.
Within the flush routine, that the list can be altered during the routine.


RandomShaper
7:59 AM
Done!
```

**Review by m4gr3d — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by SirTodd** [comment]
Any chance this could be cherrypicked before 4.1?

**Comment by Calinou** [comment]
> Any chance this could be cherrypicked before 4.1?

This PR already has the `cherrypick:4.0` label, but given 4.0.3 RC 1 was already released, I think this will most likely have to wait for 4.0.4.

**Comment by akien-mga** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
