### PR TITLE
Fix android wrapper comments

### PR DESCRIPTION
**Pull request by Alex2782**
Only two comments adjusted, new files:
- [GodotRenderView.java](https://github.com/godotengine/godot/blob/master/platform/android/java/lib/src/org/godotengine/godot/GodotRenderView.java)
- [Godot.kt](https://github.com/godotengine/godot/blob/master/platform/android/java/lib/src/org/godotengine/godot/Godot.kt)

### CODE REVIEW

**Review by m4gr3d — APPROVED** [review]
Thanks for the cleanup!

**Comment by Alex2782** [comment]
I'm not sure about **GodotRenderView.java**, only `Vulkan` and `GL`?

image

**Comment by Alex2782** [comment]
ok 👍

**Comment by akien-mga** [comment]
Thanks for the fix! I merged this together with a few other recent PRs fixing other comments, to avoid merging 4 PRs for 4 typos :)

Superseded by fa259a77cd9ea725f22ccfd52d5c228e10358e1d.

**Pull request closed without merging**
