### PR TITLE
Adds Copy button to output panel

### LINKED ISSUE #27543: Add a context menu to Console for copying text
**Godot version:**
3.1

**Issue description:**
The current Console window in the editor only supports copying text after selection with the shortcut ctrl+c,it would be nice to be able to right-click and have a context menu with a 'copy' option as shown in the image so you can also copy the text using the mouse only.

*Example demonstrating what is requested* 

Console-context-menu

### PR DESCRIPTION
**Pull request by kbake**
Fixes #27543. Adds a context menu to the Editor Log with "Copy" as an option. Could potentially add more, both "Clear" and "Select All" would be relevant (and simple to add on). Will update this PR if we decide to go that path.

### CODE REVIEW

**Comment by reduz** [comment]
I would just put a "Copy" button to the left of "Clear", there is no point in a context menu here.

**Comment by kbake** [comment]
Done! Removed the context menu and just added a "Copy" button next to "Clear".

**Comment by akien-mga** [comment]
Could you amend the commit log to reflect what it does now?

**Comment by kbake** [comment]
Updated the commit message, should be more accurate now!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by kielse** [comment]
Not clear to me if we will have a "select all" option here.

**Comment by Calinou** [comment]
@kielse The "select all" button hasn't been added yet, work is welcome in that area :slightly_smiling_face:

**Pull request merged**
