### PR TITLE
[DOCS] Animation methods desc 100%

### PR DESCRIPTION
**Pull request by willnationsdev**

### CODE REVIEW

**Comment by leoddd** [comment]
How can a getter have a default value?

**Comment by willnationsdev** [comment]
Excellent question. Well, the underlying data is an array of `Track` structs. The `track_get` and `track_set` modify a variable associated with a single `Track` (the `loop_wrap` property in the struct) which, when the track is created, does have a default value. The `Track` typename isn't exposed to the scripting API though. I need to put the default value of the property somewhere, so to be on the safe side, I placed it within both the getter and the setter.

**Comment by leoddd** [comment]
I figured it'd be that, but getters usually don't include the default value for the associated property because the getter is supposed to return the current state, not what things are initialized as, so I think putting it on the setter only would be fine so as to not confuse anyone into thinking that the method has some kind of logic that would make it return something that isn't the property's current value.

I might be reading too much into it, though. Just doesn't feel right in that place to me personally.

**Comment by willnationsdev** [comment]
Ok then. Well, I'll go ahead and remove it then.

**Pull request merged**
