### PR TITLE
[Project Manager] Replace title bar logo with color variant.

### LINKED ISSUE #9065: Change the logo in the new Project Manager to one of the official versions
### Describe the project you are working on

-

### Describe the problem or limitation you are having in your project

The new Project Manager in 4.3 is a great update, however the logo in the upper left corner is not good.
1. An outlined logo is never used under any other circumstances, meaning the first logo shown in the product is not official.
3. The small size of the logo makes it look messy to the point where it distorts the visual features of the official logo, especially the eyes where the pupils are missing.
4. There is no reason to use a new version of the logo when there is already an official black/white version that can be used here.

Current version
image

Suggested update
image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

See image above

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

-

### If this enhancement will not be used often, can it be worked around with a few lines of script?

-

### Is there a reason why this should be core and not an add-on in the asset library?

-

### PR DESCRIPTION
**Pull request by bruvzg**
Alternative to https://github.com/godotengine/godot/pull/89969, uses default color logo instead of outline one.

HiDPI:

LowDPI:

It looks fine at 200% scale, a bit blurry at lower scales, but with logo aligned to pixel grid it's not completely broken even an 75% scale.

100% UI scale (zoom):
Screenshot 2024-03-31 at 21 30 07

75% UI scale (zoom):
Screenshot 2024-03-31 at 21 30 45

*Bugsquad edit:*
- Closes https://github.com/godotengine/godot-proposals/issues/9065

### CODE REVIEW

**Comment by ajreckof** [comment]
I feel like this is the best of all propositions given for replacing the logo here.

**Review by Calinou — APPROVED** [review]
Looks good to me.

We could consider drawing special pixel art versions of the logo for smaller scales (to be swapped in depending on editor scale), but this should be left for a future PR.

**Review by AThousandShips — APPROVED** [review]

**Review by coppolaemilio — APPROVED** [review]

**Comment by coppolaemilio** [comment]
Looking sharp! How does this look in Windows?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
