### PR TITLE
Added body mode property for TileMap as kinematic body

### PR DESCRIPTION
**Pull request by not-surt**
Added body mode property to TileMap to select between static and kinematic physics bodies. Kinematic allow use of TileMaps for moving platforms for example.
Updated 2D Platformer demo to use kinematic TileMaps for moving platforms, in doing so discovered that the tileset_edit.xml scene was messed up and not converting properly, so fixed that too.
And in order to fix the tileset without too much pain I needed to activate snapping for collision polygon vertices.

Rigid bodies for TileMaps would be cool to add too but I'm not sure how to go about making the separate bodies for each quadrant act as one object.

### CODE REVIEW

**Comment by reduz** [comment]
Maybe I don't understand how it works, but why would you want to have something like this in the tilemap? What is the advantage over doing it manually?

**Comment by not-surt** [comment]
So you can use the same tiles that make up the rest of the level is made out of. And don't need to create a new image for every platform variation.

**Comment by reduz** [comment]
also having a large tilemap using kinematic will destroy performance at no gain, due to it needing to check collision and processing every frame. You can still do this and have some polygon added as collision from the outside if you wish, on the downside if a user changes body mode to kinematic on a large map, the game will freeze without any apparent reason, so I really don't like this.

**Comment by reduz** [comment]
on second thought, it will probably not freeze because the map uses octants so it will not be much of a hit. However, RigidBody or CharacterBody modes do not really make much sense and is not expected to work. Maybe just a flag "use kinematic collision" ? I would also not change the platformer demo, as I think the current way moving platforms is implemented is more straightforward to learn.

**Comment by not-surt** [comment]
Rigid could be really cool for destructible levels. Destroy the base of a tower, move tiles of now disconnected top to a new tilemap with rigid body physics and let it fall and roll.

I'm happy enough to change kinematic selection to a flag.

The platformer demo is a tile-based game. It makes more sense to me that it be all tile-based, rather than some sections using large bespoke sprites.
The platforms should still work identically, still controlled by the same script. Just the visuals and collisions are described by one tilemap object with kinematic physics rather than a sprite object and a kinematic body object.

Still the original tileset_edit.xml scene is broken and needs to be fixed if nothing else.

**Comment by reduz** [comment]
I guess the flag is ok, but I still wouldn't change the moving platforms,
as (from the projects I saw so far) it is not the most common case to do it
this way, even though it makes sense from the homogeous point of view.

**Comment by not-surt** [comment]
Okay, changed to flag and changed the demo's moving platforms back to how they were before.

**Pull request merged**
