### PR TITLE
Github Action for Android Template

### PR DESCRIPTION
**Pull request by thebestnom**
not sure if needed but I had time anyway

### CODE REVIEW

**Comment by akien-mga** [comment]
> not sure if needed but I had time anyway

It's welcome, yes, we plan to move all CI to GitHub Actions, so Android and Javascript were the last ones.

**Comment by akien-mga** [comment]
CC @RevoluPowered

**Comment by thebestnom** [comment]
@akien-mga working on fixing this after rebase, sorry for bombing the CI

**Comment by thebestnom** [comment]
Looks like I fix that, any comment is welcomed

**Comment by thebestnom** [comment]
Updated commit message to be normal

**Comment by akien-mga** [comment]
This should now be moved to its own file following #40351.

Is it ready to merge otherwise?

**Comment by thebestnom** [comment]
From my testing, yes

**Comment by thebestnom** [comment]
I can't say I understand how https://github.com/godotengine/godot/pull/40351 is related though

**Comment by akien-mga** [comment]
Sorry, GitHub autocompletion did something weird here. I meant to reference #40556.

(Yeah, this happens when you put a dot after an issue number, and it tries to include it in the search string...
Screenshot_20200723_181828)

**Comment by thebestnom** [comment]
when Android Builds work it should be completly fine

**Comment by thebestnom** [comment]
scons seems to work so it should be ready once Ill fix lint

**Comment by thebestnom** [comment]
@akien-mga working

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
