### PR TITLE
Added toggle for loop interpolation based on adolson's code

### LINKED ISSUE #959: looped animations give unexpected results
If you loop an animation and use the continuous interpolation mode, after the last keyframe in a track, things get wonky. If you have a keyframe at the very end of the animation's length, the value will loop back to 0 immediately. If you have a keyframe earlier, it'll count down from that keyframe back to the first keyframe in the track.

I've never seen a loop behave like this before. I tested this in v0.99.3653-pre-beta from January 3rd, and get the same behavior, so this isn't a regression, by the look of it.

Here's a video showing how to reproduce this, in case it's not clear what I'm saying: http://youtu.be/Ti0OBfWR4a8

I can't see why anyone in their right mind would WANT this behavior to happen automatically, since they could simply keyframe back down at the end of the animation. But those of us who don't want this behavior don't have any option unless we want to insert keyframes for EVERY value... Which is simply making things far more tedious than need be. Even extending the animation a bit, inserting a duplicate keyframe there, then setting the length back to the desired value doesn't prevent this from happening (keyframe past length is just ignored, as would logically be expected).

### PR DESCRIPTION
**Pull request by Cybolic**
This adds a "loop interpolation" toggle button next to the "loop" button in the Animation Editor.
It defaults to being on, so there shouldn't be any incompatibilities with existing projects.
This should fix #959 in a way that's agreeable to everyone.

### CODE REVIEW

**Comment by adolson** [comment]
I HEARTILY APPROVE

**Comment by punto-** [comment]
Wasn't this fixed by commit 433de90?

**Comment by Cybolic** [comment]
punto-, I still see the perceived broken behaviour, even after commit 433de90.

**Comment by Dillybob92** [comment]
@Cybolic can confirm the same respective behavior as well

**Comment by punto-** [comment]
do you have the frames that you're using for the animation?

**Comment by Dillybob92** [comment]
@punto-  Yeah, try this:

loader

0.8 seconds length, 20 frames

image

image

**Comment by Dillybob92** [comment]
@punto- 

Here:
fireball

Set continuous mode for 8 frames in the animation player. Still happening on after commit, not sure why, but you definitely tell the distortion, hope that helps

**Comment by akien-mga** [comment]
As far as I'm concerned this could be merged, as it seems to preserve compatibility and solve an annoying issue for various users. I'd like @punto- to confirm he approves of the addition though :)

**Comment by akien-mga** [comment]
Here's an example that reproduces the bug (IIUC), using the frames from the above comment: 
[anim_loop.zip](https://github.com/godotengine/godot/files/322239/anim_loop.zip)

Without the mode introduced by this PR, when going from frame 7 (the last one) to frame 0 (the first one) to loop, the AnimationPlayer will interpolate all the values between the two. If the key for frame 7 is move to the end of the animation, the weird looping-back behaviour does not happen, but the 7th frame is skipped.

After applying this PR, and having disabled the default "enable loop interpolation" (i.e. current default behaviour), it works perfectly. The 8 frames are played 0.5s each, and after frame 7 is played, it loops without interpolation to frame 0. As the PR does not have any negative impact on the existing behaviour, I'll merge it, it's a very good feature to have.

**Comment by akien-mga** [comment]
@djrm We'll need a new SVG icon for the toggle added in this PR :)

**Comment by akien-mga** [comment]
(Namely `tools/editor/icons/icon_loop_interpolation.png`)

**Comment by Cybolic** [comment]
I hope this will do. It's an optimised SVG, but I can upload the full layered Inkscape SVG as well, if that' wanted :)
https://drive.google.com/file/d/0B2mB5cFTxznfSU5jc3lxLTdsb00/view

**Comment by punto-** [comment]
But what happens if you put a keyframe with value 8 (1 more than the last
frame of the sprite) at the end and let it interpolate? (I'm ok with this
option, I'm just wondering because I still don't understand the bug)

**Comment by akien-mga** [comment]
> But what happens if you put a keyframe with value 8 (1 more than the last frame of the sprite) at the end and let it interpolate? 

That works, but it's not necessarily easy to think about such a workaround. The editor won't let you keyframe a frame that does not exist, so you need to keyframe the frame 7 again, and then edit the keyframe in the animation player to change its value to 8.

**Comment by punto-** [comment]
I know.. it's an interface problem. I was just wondering if there's an
interpolation bug when the last and first keyframe are at the same time
(after "moduling" the time of the keyframe they should both be at 0)

**Comment by lonesurvivor** [comment]
This setting doesn't work for me. Its state doesn't get saved properly in the scene file (it is always set to 1)

**Pull request merged**
