### PR TITLE
Scons: Small improvements to build script

### PR DESCRIPTION
**Pull request by mhilbrunner**
The first commit (7b6b4a7):
 1. Adds utf-8 coding at top of SCons build script
 2. Checks if the script is run via Python, not with SCons, and exits cleanly
 3. Exits cleanly if environment is not defined or no platform is given, instead of printing exception/stacktrace

The second commit (9058e70) puts the whole buildscript inside a function that is called. This allows us to exit by returning from the function. Why? Because `Exit()`/`sys.exit()` not only exit the build script, but end the whole Python process. This has the following consequences:

Currently, if you want to display the help (`scons -h`) that we already generate, you only get the error about defining a platform but no help output, because Python (and thus Scons) exits and never prints the help.

After this commit, `scons -h` works as it should.

I can squash those commits or if the latter is not wanted, I can remove the changes and only leave the first. I wanted to seperate them so they can be reviewed seperately. However, `scons -h` should probably work instead of not printing the help :)

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks a lot for your contribution!
We are now entering a strict release freeze for Godot 3.0 and will only consider major bug fixes. We won't merge new features and enhancements anymore until 3.0 is released.

Moving this PR to the 3.1 milestone, to be reviewed once the release freeze is lifted. It could eventually be cherry-picked for a future 3.0.1 maintenance release if it doesn't change the user-facing APIs and doesn't compromise the engine's stability.

**Comment by mhilbrunner** [comment]
Should I resolve the conflicts or close this one? IMO, `scons -h` shouldn't spit out stack traces, and having clean error messages instead of stack traces for things like missing `platform=` is nicer, but your opinions may vary :)

**Comment by akien-mga** [comment]
Well I have mixed feelings about this one, I agree that `scons -h` should work, but I don't like the idea to move basically the whole script in a method and make it a "normal" python script. It's not a `.py` file, so I don't think anyone should try to run it directly without running `scons` -- if they do and it gives an error, that's fine. You can also do `sh Makefile` and get it explode :)

**Comment by mhilbrunner** [comment]
I'll close this, then, and see if I can just fix the `scons -h` in some more minimal way. :)

**Pull request closed without merging**
