### PR TITLE
Show override icon in script editor gutter

### PR DESCRIPTION
**Pull request by RedMser**
Part of https://github.com/godotengine/godot-proposals/issues/5369

Includes two new icons for the script editor gutter, one for overridden method and a second for combining with the "connected signal" icon:

image

The icon can be clicked to jump to the method declaration (or in case of a built-in class, it opens the corresponding documentation page).

I also snuck another commit in to optimize an icon from a previous PR :eyes:

### CODE REVIEW

**Comment by MewPurPur** [comment]
For completeness, #64693 implements the same as a highlighting color

**Comment by MewPurPur** [comment]
Anyway, I like this! I think an icon along the lines of an arrow forking out would be more intuitive. Not a svg extraordinaire, so here's a pixel art version of what I have in mind:

image

**Comment by YeldhamDev** [comment]
The override color shouldn't be the same as the connection one, so they can clearly stand out from each other. The combo one can have the arrow be one color and the box another.

**Comment by RedMser** [comment]
Thanks for the icon templates @MewPurPur, I went ahead and created SVG versions based on these.

**Review by Paulb23 — COMMENTED** [review]
This looks good!

In other IDE's clicking the "override" icon will take you to the parent method would be cool to do that here. In which case might be worth changing the metadata from a string to a dictionary?

**Comment by RedMser** [comment]
@Paulb23 Good point.
I added the feature, so it jumps to the method declaration when clicking on the icon. For built-in classes, it jumps to the corresponding documentation page instead. Uses dictionaries like suggested.

For the "combined" signal+override case, I think it would be nice to somehow show both icon's information (e.g. open a PopupMenu which allows choosing whether to show the dialog or the declaration). But I think it's a rare enough case that we can ignore this for now. Until more gutter icons get added and a real system needs to be in place for them.

**Review by Paulb23 — APPROVED** [review]
LGTM.

The otherway around it would be to have `ctrl+click` goto the method similar to normal lookup. While, a normal click brings up the connection popup.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

Initial response to this PR seems to be positive, I'm not 100% sure all users will love the change as it's quite intrusive, but this kind of UX might be best tested in production to get feedback in 4.0 beta 2.

**Comment by akien-mga** [comment]
Thanks! And congrats for snatching PR `0xFFFF`!

**Comment by fracteed** [comment]
Is there any way of hiding these new icons? It seems that I can hide the whole info gutter, but I would still like to have the signal icons visible.

**Comment by RedMser** [comment]
@fracteed There currently is no way, but I don't see anything that speaks against adding some more fine-grained editor settings to choose which gutter icons should show.

**Comment by fracteed** [comment]
@RedMser thanks for your reply. Yes, it would be great to have per icon toggles for the gutter in the same way that we have per item gizmo visibility in the viewport. Especially if more icons end up being added over time.

Ideally this would be a menu in the text editor itself rather than having to dive into preferences.  I can certainly see their usefulness, but they are not something that I need to see all the time.

**Pull request merged**
