### PR TITLE
Add "Open in External Program" option

### LINKED ISSUE #328: Allow opening sprites and other files in external editor/default program
**Describe the project you are working on:**
Project with many sprites
**Describe the problem or limitation you are having in your project:**
To edit sprites, I have to leave Godot and locate them on my computer
**Describe how this feature / enhancement will help you overcome this problem or limitation:**
It will basically make me stay close to the 'Godot environment'
**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
See below
**Describe implementation detail for your proposal (in code), if possible:**
Basically, it will be an option in editor settings. User has to point the application.
All textures resources will have an Edit in Image Editor button in inspector
**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
Plugins are per project. It will be tedious to set image editor in each project
**Is there a reason why this should be core and not an add-on in the asset library?:**
Same as above

### PR DESCRIPTION
**Pull request by KoBeWi**
This PR adds "Open in External Program" option to filesystem dock. By default it opens the file in the system's default program, but the program can be configured with editor settings for some file types:
`filesystem/external_programs/raster_image_editor` - for textures and images
`filesystem/external_programs/vector_image_editor` - same as above, but with svg/z extension
`filesystem/external_programs/audio_editor` - for audio streams
`filesystem/external_programs/3d_model_editor`  - for 3D model scenes
`text_editor/external/exec_path` - for script files

https://user-images.githubusercontent.com/2223172/201209760-1f33403f-dfe7-40d8-b443-c93e85537be4.mp4

Closes https://github.com/godotengine/godot-proposals/issues/328
Partially addresses https://github.com/godotengine/godot-proposals/issues/5759
Can be used as workaround for #63683

EDIT:
There is some issue when using the console mode editor on Windows. The opened program will be closed when console is closed.

### CODE REVIEW

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by geowarin** [comment]
This is great!
Having a customizable keyboard shortcut for this action would be really nice too.

**Comment by KoBeWi** [comment]
Feel free to open a PR with the shortcut.

**Comment by gomaproi** [comment]
I don't know if this is intentional, but the buttons open the Directory picker instead of a File picker.

**Pull request merged**
