### PR TITLE
Change how editable children data is stored

### LINKED ISSUE #20409: Rename an "Instanced Scene as Node" disables "Editable Children"
https://github.com/godotengine/godot/commit/89e1b302b504feb1cea218adcc6fac77c8ae0052
x11

It only happen if it's a name that the node never had before.

peek 2018-07-24 15-22

### LINKED ISSUE #23979: Data in editable children lost without warning when moving node in tree
**Godot version:**
3.1.aplha. c025f52

**OS/device including version:**
Windows 10

**Issue description:**
When moving an instanced scene with editable children, the "editable children" flag is lost. Moving the scene back re-enables the flag. If scene is saved when instanced scene is in new location, all children data is lost without warning.

**Expected behaviour:**
When moving an instanced scene with editable children, all modifications are preserved.

**Actual behaviour:**
When moving an instanced scene with editable children, editable flag is lost. Child modification data is lost as soon as scene is saved to disk.

**Steps to reproduce:**
1. Instance a scene with editable children.
1. Make modification to the children. 
1. Move the instanced scene in scene tree. 
1. Save and reopen.

Probably related to #20409 and #6455.

### LINKED ISSUE #27023: Editable Children doesn't overwrite properties some times
**Godot version:** 3.1.stable

**OS/device including version:** Solus 3.9999

**Issue description:**

When merging or instantiating, but especially merging, after you enable `Editable Children` and try to modify some properties of the children, when the game loads it doesn't override them.

merging_issue

**Steps to reproduce:**
1. Create a scene with some Sprites
2. Save it
3. Instance it on another scene
4. Turn on `Editable Children`
5. Change its `position`
6. Create a new scene
7. Merge the instanciated scene from step 3
8. Test the scene

### LINKED ISSUE #27064: Editable Children Flag Turns Off Due to Node Path Change
**Godot version:**
3.1

**OS/device including version:**
OSX Latest

**Issue description:**
I changed the node path of a node that has `Editable Children` enabled, and it disabled `Editable Children`. The edits made to the children do not change, but the child nodes are not accessible anymore. If I turn `Editable Children` back on, everything seems to go back to normal since the children node states are somehow preserved.

For example, if I enable `Editable Children` on a node, and I edit one of the children, the edit is preserved despite `Editable Children` being disabled from changing the path.

**Steps to reproduce:**
1. Open a Godot file
2. Make a new scene, say `Scene A`
3. Make new scene, say `Scene B`, and instance A in it
4. Enable `Editable Children` for the `Instance A` in `Scene B`
5. Change the name of `Instance A` in `Scene B`.
6. (Alternative to 5) Change the name of a parent node for the `Instance A` in `Scene B`

Expected: The name changes and that's it
Actual: The name changes, but `Editable Children` gets disabled

Edit:
As a side note, I'm having a hard time finding documentation for what `Editable Children` actually does. The inspector properties are all red, I don't know what that means. I don't know the limitations to `Editable Children` either.

### LINKED ISSUE #28861: Editable children property persists after node deletion
**Godot version:**
3.1.1

**Issue description:**
Editable children property is stored as NodePaths in scene root and they aren't removed/updated on node move/update, which leads to unexpected results (like #20409).

**Steps to reproduce:**

1. Create a scene (e.g. SceneA.tscn)
2. Create another scene (e.g. SceneB)
3. Create a main scene
4. Instance SceneA
5. Toggle editable children of SceneA
6. Delete SceneA
7. Instance SceneB
8. Rename SceneB to SceneA
9. SceneB will get editable children upon rename

**Minimal reproduction project:**
[ReproductionProject.zip](https://github.com/godotengine/godot/files/3175254/ReproductionProject.zip)
Initial setup for point 3 in steps to reproduce.

### PR DESCRIPTION
**Pull request by KoBeWi**
Master version of #39533

Added @hilfazer as co-author.

Fixes #28861
Fixes #27064
Fixes #23979
Fixes #20409
Fixes #27023

### CODE REVIEW

**Comment by akien-mga** [comment]
Does it fix all the issues referenced in #39533 too in the `master` branch?

**Comment by KoBeWi** [comment]
Yes. Do theu need to be referenced in this PR too?

**Comment by akien-mga** [comment]
Yes, so that they can be closed by GitHub. PRs merged in non-`master` don't close linked issues.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
