### PR TITLE
Added LZ4/LZ4HC support.

### PR DESCRIPTION
**Pull request by ghost**
LZ4 decompression speed is far superior than FASTLZ and ZLIB, and LZ4 compressor is as fast as FASTLZ.
Also set LZ4 compression as default, which was FASTLZ.

### CODE REVIEW

**Comment by tagcup** [comment]
LZ4 library can also be used for streaming compressed data such as meshes later on.

**Comment by tagcup** [comment]
Actually, since we can still break compatibility, I think FASTLZ can be dropped completely.

**Comment by tagcup** [comment]
Clarification: with this PR, new compressed files with be saved using the new default (which is LZ4, although we can also use LZ4HC which corresponds to still-not-so-slow `LZ4HC_CLEVEL_OPT_MIN`, what do you think?). FASTLZ is kept (for now) such that old files compressed with FASTLZ can still be opened.

**Comment by tagcup** [comment]
I'm looking at the numbers for zstd:

https://github.com/lz4/lz4
https://github.com/facebook/zstd

 While it can't beat LZ4 in decompression speed (although it's still good, around 1GB/s), the compression ratio and speed is really good. So I think it would be better to switch to zstd instead.

**Comment by n-pigeon** [comment]
Question is do we need smaller files or faster compression/decompression? Files are a bit smaller with zstd but lz4 is much faster especially at decompression.

**Comment by tagcup** [comment]
zstd decompression is fast enough to me, and looks more balanced. So I'd like to close this PR

**Pull request closed without merging**
