### PR TITLE
Roll back libwebsockets to version 3.0.1

### LINKED ISSUE #27560: WebSocketClient closes connection soon after handshake with some server implementations
**Godot version:**
3.1 stable

**OS/device including version:**
Ubuntu 18.04 LTS

**Issue description:**
When connecting to _some_ weboscket servers, the client disconnects immediately after the handshake is complete (i.e. as soon as the server responds to our upgrade request). This, I suspect, is cause by the fact that a `Connection: close, Upgrade` header is sent in the upgrade request. I also suspect that this is caused by libwebsocket. Below shows the handshake as seen in wireshark.

> GET / HTTP/1.1
> Pragma: no-cache
> Cache-Control: no-cache
> Host: echo.websocket.org
> Upgrade: websocket
> Connection: close, Upgrade
> Sec-WebSocket-Key: HKWU1xOVV6PP6HXjcIWMDQ==
> Sec-WebSocket-Version: 13
> 
> HTTP/1.1 101 Web Socket Protocol Handshake
> Connection: Upgrade
> Date: Sun, 31 Mar 2019 19:09:01 GMT
> Sec-WebSocket-Accept: 0IHc3riAKJz52YmkLVcWrDHvaYs=
> Server: Kaazing Gateway
> Upgrade: websocket

**Steps to reproduce:**
Use a WebSocketClient object to connect to one of the following websocket servers:

- ws://demos.kaazing.com/echo
- ws://echo.websocket.org

Note that some websocket servers appear to ignore the `close` field in the connection header. Below is a list of websocket servers that ignore the `close` field:

- wss://libwebsockets.org  (using protocol: "dumb-increment-protocol")
- [This websocket server daemon](http://websocketd.com/)

**Minimal reproduction project:**

The following script could be attached to a root node to reproduced the issue, however I have also included a full project setup which can be tested.

```
extends Node2D

var _client = WebSocketClient.new()

func _ready():
	print("connecting...")
	_client.connect("connection_closed", self, "ws_closed")
	_client.connect("connection_error", self, "ws_connection_error")
	_client.connect("connection_established", self, "ws_connection_established")
	_client.connect("server_close_request", self, "ws_close_request")
	_client.connect_to_url("ws://echo.websocket.org")

func ws_closed(clean):
	if !clean:
		print("websocket closed")
	else:
		print("websocket closed cleanly")

func ws_connection_error():
	print("websocket connection failed")

func ws_connection_established(protocol):
	print("we're connected using protocol: ", protocol)

func ws_close_request(code, reason):
	print("closed with code: ", code, " and reason: ", reason)

func _process(delta):
	if _client.get_connection_status() == WebSocketClient.CONNECTION_DISCONNECTED:
		return
	
	_client.poll()
```
[ws_test.zip](https://github.com/godotengine/godot/files/3027046/ws_test.zip)

### PR DESCRIPTION
**Pull request by Faless**
This reverts commit 90210c48627692d281554d6185b5db17a86c852a.

Fixes #27560 while we transition to `wslay` (a potential cherry pick for godot `3.1.2`).

I would like interested parties to test this a bit before we decide what to do (@AshfordN , @RyanJEC, ...).

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Fine with me as currently we can't build distro packages against system libwebsockets anyway due to the messy openssl-to-mbedtls wrapper.

**Comment by AshfordN** [comment]
I've tested this and as far as I can see, it seems to be working perfectly.

**Comment by RyanJEC** [comment]
Tested, confirmed wss://echo.websocket.org is no longer disconnecting along with my custom websocket server. 

However still getting immediate disconnect using wss://irc-ws.chat.twitch.tv Hopefully this will be fixed further after wslay transition.

All in all good patch/revert.

**Comment by AshfordN** [comment]
@RyanJEC are you certain your twitch disconnect is actually caused by the `connection: close` header? Websocket connections are also dropped due to incorrect protocol(s) as well. I'm assuming a service like twitch might define its own protocol, so it might be useful to double check.

**Comment by RyanJEC** [comment]
@AshfordN Honestly I don't know what is going on with twitch ws server. All I know is it connects no problem with browser implementation. I'll probably just use TCP or godot twitch plugin.
 
This patch works most servers now. That's all that matters.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
