### PR TITLE
The help page now show the entire object hierarchy

### LINKED ISSUE #807: Making object hierarchy more explicit in help pages.
By this, I mean having something like (for example) "Object > Node > Control > Panel" at the top of the help page for panel, so you can click on any of the others to be taken to the relevant help page.

### PR DESCRIPTION
**Pull request by ghost**
object_hierarchy

Fixes #807

### CODE REVIEW

**Comment by reduz** [comment]
fantastic! do you want to add objects that are inherited by it to? like an
Inherited By:

**Comment by reduz** [comment]
(direct inheritance)

**Comment by TheHX** [comment]
@reduz, ok! But in this case there's any problems on using ObjectTypeDB instead of DocData?

**Comment by reduz** [comment]
i think both should work, just iterate through all the types to see which
inherits the current one

**Comment by TheHX** [comment]
Another thing, for example the Object will have a lot of inheritors, i can put a limit of the maximum classes displayed, or simply don't display nothing if the limit is crossed.

**Comment by reduz** [comment]
There shouldn't be thaaat many direct inheritors I think.. should still
work.

**Comment by TheHX** [comment]
With the first implementation i got this result

captura de tela de 2016-03-05 14-37-37

**Comment by akien-mga** [comment]
That's similar to what we have on the online docs, that's fine IMO: http://docs.godotengine.org/en/latest/classes/class_resource.html

**Comment by akien-mga** [comment]
Very cool new feature btw :D

**Pull request merged**
