### PR TITLE
Fix cubic slerp.

### LINKED ISSUE #57951: `cubic_slerp()` may take a rotation path that is not the shortest
### Godot version

4.0.dev, 3.4

### System information

Any

### Issue description

#40592 split and resend. There is a problem with the implementation of `cubic_slerp()`, it may mix non-shortest paths in the calculation.

### Steps to reproduce

https://user-images.githubusercontent.com/61938263/180647818-b7c9550f-462b-430a-8966-96ccde165ea6.mp4

### Minimal reproduction project

[cubic_slerp_test.zip](https://github.com/godotengine/godot/files/9175808/cubic_slerp_test.zip)

### PR DESCRIPTION
**Pull request by fire**
Fixes: https://github.com/godotengine/godot/issues/57951

@GNSS-Stylist Can you try? I couldn't get it to work with slerp :(.

### CODE REVIEW

**Comment by GNSS-Stylist** [comment]
Tried to open the project I used for testing before, but failed, probably due to renamings of things. So answer to the question "can you try" is apparently "no", at least for now. :) But looking at the code you seem to perform component-wise cubic interpolation for basis' X- and Y-axes and calculating Z-axis from those(?) Are you sure this is the right approach?

Personally I have been using cubic interpolation on quaternion components and been happy with this solution for now (haven't used this very much yet, though). Added my sources if you want to take a look. I remember rewriting some helper functions (like inverse) also, but not sure if that makes any difference. Be warned though that there is also some dead code, all kinds of ugly hacks (and "arbitrary interval" cubic hermite interpolation added since I wanted to use smooth interpolation with sparsely and non-uniformly spaced keys)
[quaternion_component_wise_cubic_interpolation.zip](https://github.com/godotengine/godot/files/8386485/quaternion_component_wise_cubic_interpolation.zip)
.

**Comment by fire** [comment]
It is incomplete. I need to implement exp map for transform3d https://www.geometrictools.com/Documentation/InterpolationRigidMotions.pdf

**Comment by fire** [comment]
@GNSS-Stylist Are you able to salvage this work and make a Godot Engine 4 pull request before the feature freeze is locked?

**Comment by GNSS-Stylist** [comment]
Made a pull request for the salvaged test project: https://github.com/fire/godot-40592/pull/2

I haven't been following discussions related to this for a while. Do you think that the component-wise cubic interpolation with renormalization would be sufficient?

**Comment by fire** [comment]
@TokageItLab has demonstrated problems that

**Comment by TokageItLab** [comment]
https://github.com/godotengine/godot/issues/57951#issuecomment-1046425597 This is all. We must cache the signs so that it do not flip during animation.

**Comment by GNSS-Stylist** [comment]
Made a pull request of component-wise cubic interpolation:
https://github.com/godotengine/godot/pull/63287

**Comment by fire** [comment]
Closing because https://github.com/godotengine/godot/pull/63380 is significantly better.

**Pull request closed without merging**
