### PR TITLE
[Export docs] Move docs to platform folders.

### PR DESCRIPTION
**Pull request by bruvzg**
Follow up to https://github.com/godotengine/godot/pull/74644, moves platform specific XML to the platform sub-folders.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good!

Also needs these changes for rst doc generation:
```diff
diff --git a/doc/Makefile b/doc/Makefile
index cc2ebf9881..53c5c7dcb0 100644
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -1,5 +1,5 @@
 BASEDIR = .
-CLASSES = "$(BASEDIR)/classes/" "$(BASEDIR)/../modules/"
+CLASSES = "$(BASEDIR)/classes/" "$(BASEDIR)/../modules/" "$(BASEDIR)/../platform/"
 OUTPUTDIR = $(BASEDIR)/_build
 TOOLSDIR = $(BASEDIR)/tools
 JSDIR = "$(BASEDIR)/../platform/web"
diff --git a/doc/tools/make_rst.py b/doc/tools/make_rst.py
index 1f71b77cbd..3655a60c35 100755
--- a/doc/tools/make_rst.py
+++ b/doc/tools/make_rst.py
@@ -567,7 +567,7 @@ def main() -> None:
         if path.endswith("/") or path.endswith("\\"):
             path = path[:-1]
 
-        if os.path.basename(path) == "modules":
+        if os.path.basename(path) in ["modules", "platform"]:
             for subdir, dirs, _ in os.walk(path):
                 if "doc_classes" in dirs:
                     doc_dir = os.path.join(subdir, "doc_classes")
```

And this tweak for the docs l10n extractor: https://github.com/godotengine/godot-editor-l10n/pull/4

**Comment by YuriSizov** [comment]
Would need to make some changes to the docs repo too, and probably create a new subsection in make rst, but I can do it myself later.

**Comment by akien-mga** [comment]
Another diff needed in this repo:
```diff
diff --git a/.github/workflows/static_checks.yml b/.github/workflows/static_checks.yml
index 2d4736e1dd..bf3ee49315 100644
--- a/.github/workflows/static_checks.yml
+++ b/.github/workflows/static_checks.yml
@@ -71,11 +71,11 @@ jobs:
 
       - name: Class reference schema checks
         run: |
-          xmllint --noout --schema doc/class.xsd doc/classes/*.xml modules/*/doc_classes/*.xml
+          xmllint --noout --schema doc/class.xsd doc/classes/*.xml modules/*/doc_classes/*.xml platform/*/doc_classes/*.xml
 
       - name: Documentation checks
         run: |
-          doc/tools/make_rst.py --dry-run --color doc/classes modules
+          doc/tools/make_rst.py --dry-run --color doc/classes modules platforms
 
       - name: Style checks via clang-format (clang_format.sh)
         run: |
```

**Comment by bruvzg** [comment]
> Another diff needed in this repo

Done. 

> Would need to make some changes to the docs repo too, probably create a new subsection in make rst

I guess all editor related classes probably should be in the own subsection.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
