### PR TITLE
SpriteFramesEditor Minor fixes

### PR DESCRIPTION
**Pull request by kleonc**
To match minor fixes from #48977.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by kleonc** [comment]
@akien-mga Don't merge yet.

**Comment by aaronfranke** [comment]
@kleonc Indeed that would make sense. EDSCALE returns a float, and these fields are float, so it's better to use it consistently rather than casting to double and back to float. I checked if there are other places around the engine to fix, this is the only file with the exact text `MAX(1.0, EDSCALE)`, so I think it's worth making that change in this PR (make them `MAX(1.0f, EDSCALE)`).

**Comment by kleonc** [comment]
@aaronfranke Ok, I've changed these.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
