### PR TITLE
GDScript: Fix POT generator crash on assignee with index

### LINKED ISSUE #79697: Crash on 'Generate POT' when Dictionary-modifying Method is Present
### Godot version

4.0 -> latest

**I've tested all this versions:**
4.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4
4.1, 4.1.1
4.2 dev 4

in all this versions problem exists.

### System information

Fedora 38, macOS

### Issue description

I have found a very strange bug while generating translations. The presence of a method modifying the dictionary's content causes the editor to crash during the generation of the translation template.

The mere presence of an uninvoked method causes a crash.

**Edit: The issue occurs not only with singletons. Any script containing a method that modifies any dictionary leads to a crash.**

### Steps to reproduce

**Project -> Project Settings -> Localizations -> Generate POT -> Add (Add your singleton)**

```
extends Node

var session_data = {
	"coins" : 0,
	"power": 0
}

var shop_items = [
	{
		"id": "max_hp",
		"name": tr("First Shop Item"),
		"desc": tr("Great tool."),
	}
]

func add_power(val: int):
	session_data["power"] += val
```

_⚠️ Problem is in add_power method, not in shop_items._

**Project -> Project Settings -> Localizations -> Generate POT -> Generate**

And... Crash.

[Nagranie ekranu z 2023-09-14 13-10-42.webm](https://github.com/godotengine/godot/assets/5132385/6a00805a-34c8-408e-9b00-eb5875301312)

### Minimal reproduction project

[translation_gm_crash.zip](https://github.com/godotengine/godot/files/12104763/translation_gm_crash.zip)

_Just open project and go to: Project -> Project Settings -> Localizations -> Generate POT -> Generate_

### PR DESCRIPTION
**Pull request by dalexeev**
* Closes #79697.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Not too familiar with this logic, but the changes seem innocuous / making things more reliable.

**Review by anvilfolk — APPROVED** [review]
This is also how I was looking at the fix, and I can confirm from my own testing that the approach does work.

Like we discussed there are probably some further improvements possible with making the subscripts check recursive, in case we have something like `base.index1.index2["index3"]` or something like it... but this way it won't crash :)

**Comment by dalexeev** [comment]
Note: This may be a non-trivial to cherry-pick for 4.1, since #80020 was merged into 4.2 (not into 4.1 as I thought).

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Can't cherry-pick cleanly because it depends on https://github.com/godotengine/godot/pull/80020. I would appreciate a dedicated PR for 4.1.

**Pull request merged**
