### PR TITLE
Fix Parenthesis Removal on Autocomplete

### LINKED ISSUE #60744: text editor - autocompleting method inside another method removes one of the parentheses
### Godot version

1b2992799b324479b3fba9e05ae6226a46cb4143
Not reproducible on 3.4.4

### System information

Arch on 5.15.37-1-lts

### Issue description

issue reproduction gif

```diff
- print(Vector2.from_angle()
+ print(Vector2.from_angle())
```

### Steps to reproduce

1) Type something like `print(Vector2.from` and let it autocomplete.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by veryprofessionaldodo**
Original Issue: https://github.com/godotengine/godot/issues/60744

There was a small bug in which parenthesis were not closed if a new function was invoked inside another function. This PR fixes that, with a small video below highlighting the fix.

https://user-images.githubusercontent.com/22790704/170866084-5e60730b-dd24-47b0-bbe8-9396edfb22a7.mov

 *Bugsquad edit:*
- Fixes https://github.com/godotengine/godot/issues/60744

### CODE REVIEW

**Review by Paulb23 — CHANGES_REQUESTED** [review]
This breaks the following case `$"|"` results in `$"."|"` rather then `$"."|`.

Should probably expand the tests around this.

**Comment by veryprofessionaldodo** [comment]
Interesting. I'll look into it later today, currently at work. Thanks for the quick review!

**Comment by veryprofessionaldodo** [comment]
@Paulb23 Sorry, I'm testing it out, and I'm not understanding what is the expected behaviour. What's the input sequence that results in an issue, and what is the expected result?

**Comment by veryprofessionaldodo** [comment]
@Paulb23 Looking into this more closely, by default there's a bit of a weird behaviour in the `$"."` case:
- If I type `$"`, and then enter the suggestion, it correctly auto-completes to `$"."`;
- If I type `$".` and then enter the suggestion, it incorrectly auto-completes to `$".""`;

With the changes in this PR, it also weirdly inverts the order of the incorrect occurrence. Now in the first scenario there's an error, but in the second on, it is fine. 

I'll look into a way of fixing both errors at once.

**Comment by veryprofessionaldodo** [comment]
Ok, so I tested out some new changes, that seemingly don't break compatibility, while also fixing the weird behaviour I described that would happen with either `"` or `'`. Currently in master, this is how code completion is working at the time of writing this: 

https://user-images.githubusercontent.com/22790704/170866061-31d060ad-75a0-4132-9e74-d63142573758.mov

And here's how it works, with the changes applied in this patch:

https://user-images.githubusercontent.com/22790704/170866084-5e60730b-dd24-47b0-bbe8-9396edfb22a7.mov

**Comment by nathanfranke** [comment]
I don't think this is the right change. Why is this change for parentheses in particular? What happens if we have an autocomplete with brackets or something?

**Comment by veryprofessionaldodo** [comment]
@nathanfranke I totally get what you're saying, and yeah, something does feel a bit icky with the solution I gave. However, is there any case in which this approach wouldn't work? Asking so I can genuinely test and improve :D 

This still works in case of opening brackets, and things like that, but for example, if we use auto-completion for an array, would the brackets appear? I don't recall this ever being a feature, or anything. 

Still, I went with this approach, because changes in other places could have much larger ramifications. For example, if I did a change on the `_get_auto_brace_pair_close_at_pos` there could be wider implications on other sections of the code, whereas with this small change in this specific spot, nothing else would be affected. But if you have any other approach ideas, I'll gladly test them out!

**Comment by akien-mga** [comment]
Superseded by #70297.

**Pull request closed without merging**
