### PR TITLE
Store ArrayMesh path in RenderingServer for use in error messages

### LINKED ISSUE #84875: Obscure warning "Attempting to use a shader that requires tangents with a mesh that doesn't contain tangents." is spammed.
### Godot version

4.2beta6

### System information

Windows 10

### Issue description

In all my 4.2beta6 3D projects I get this warning spammed:
`servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:3725 - Attempting to use a shader that requires tangents with a mesh that doesn't contain tangents. Ensure that meshes are imported with the 'ensure_tangents' option. If creating your own meshes, add an `ARRAY_TANGENT` array (when using ArrayMesh) or call `generate_tangents()` (when using SurfaceTool). (User)`

This is absolutely not helping me as I don't know which mesh this is refering to.
The only way that I can get rid of it right now is by basically "drilling down" into individual scenes where this error occures and then find the mesh that is refered by the warning.

This is not a process that is in any way straight forward in a larger project.

The error should have a reference to the mesh in any way (name of the mesh instance, name of the mesh file, name of the scene etc.)

### Steps to reproduce

Can't tell exactly.

### Minimal reproduction project

-

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/84875

This only works for ArrayMeshes and not for custom meshes created through the RenderingServer API (unless the uses sets the path manually). 

Its the same approach we have used for textures and shaders, so it is nice to keep the API consistent.

### CODE REVIEW

**Review by BastiaanOlij — APPROVED** [review]
I like this!

I wonder that if no file path is available, we could also check if the user has set a resource name. I know its not common for users to set that, but in case they do, it'll atleast give them a hint?

**Comment by YuriSizov** [comment]
Thanks!

> I wonder that if no file path is available, we could also check if the user has set a resource name. I know its not common for users to set that, but in case they do, it'll atleast give them a hint?

That makes sense to me, but I assume it also needs to be done to textures and shaders, so I think we can do this as a follow-up.

**Comment by alfredbaudisch** [comment]
As of 4.2.2 RC 1, the issue of "Attempting to use a shader that requires tangents with a mesh that doesn't contain tangents." being  spammed is still presently HEAVILY. Literally 1000s of these warning messages.

**Comment by akien-mga** [comment]
That's expected, this PR was merged two weeks ago in the `master` branch (4.3.dev) and hasn't been cherrypicked for the `4.2` branch yet.

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
