### PR TITLE
Add flag to keep billboard material rotation

### LINKED ISSUE #18296: Ability to rotate Sprite3D / Mesh instances in billboard mode
**Godot version:**
3.0.2

**OS/device including version:**
Ubuntu 17.04 Gtx1060

**Issue description:**
It seems there is no way to rotate Sprite3D in billboard mode. Rotation X/Y/Z don't do anything in such case. Not sure how implementation should work, but I see two ways: 
 - new property inside Sprite 3D
 - just take rotation x into account (in such case it probably would be good if it could work with any billboard mesh)

It's quite basic feature that can be used in many  graphical effects, it would be great to have such ability.

### PR DESCRIPTION
**Pull request by Sogomn**
Fixes #18296

### CODE REVIEW

**Comment by Calinou** [comment]
Does it work correctly if you enable both "Keep Rotation" and "Keep Scale"?

**Comment by Sogomn** [comment]
Worked for all my tests.
At first I thought there was a problem when using y-billboard mode but that's just because generally rotation plus y-billboard makes things look a bit off; it seemed visually correct tho. Would be great if somebody could double check it.

**Comment by aaronfranke** [comment]
@Sogomn Is this still desired? If so, it needs to be rebased on the latest master branch.

**Comment by Sogomn** [comment]
I'm currently not working with Godot but if I find time I can rebase it.

**Comment by aaronfranke** [comment]
@Sogomn Is this still desired? If so, it needs to be rebased on the latest master branch. If not, this PR will be closed (and it will be marked as salvage in case someone else wants to continue this work).

**Comment by Sogomn** [comment]
Sorry don't really have the time to look into it right now, I'll close the issue.

**Pull request closed without merging**
