### PR TITLE
Fix rotation of 2D lights

### LINKED ISSUE #3772: Bug: rotating Light2D affects LIGHT_VEC
Windows 10 64bit.
Normal mapping works fine when all lights are omni. It's not that easy when trying to achieve spotlights.

Figure 1
As the light rotates, the bricks begin to be lit from the wrong side.

The LIGHT_VEC constant in light shader gets altered on light rotation. If my understanding is correct, it should remain the same.

[example_scene.zip](https://github.com/godotengine/godot/files/137664/example_scene.zip)

### PR DESCRIPTION
**Pull request by JFonS**
Fixes #3772.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @karroffel, might become relevant in your gles2 code at some point if you copy that part from the 2.1 branch.

**Comment by JFonS** [comment]
Yeah, lately I did some other changes to rendering stuff and I guess they should all be ported to GLES2 too, to keep compatibility.

**Comment by fracteed** [comment]
Awesome, this will make a lot of people happy!

**Comment by akien-mga** [comment]
Thanks!

**Comment by lekoder** [comment]
While it's great to have rotating lights fixed, it seems to introduce another issue:

lighting bug introduced by the issue

This is the very same scene opened with this MR applied (right) and previous version.

**Comment by JFonS** [comment]
Only from the image I can't tell what's hqppening. Are you using occluders? rotated lights?

A minimal reproduction project showing what changes would be very welcome.

**Comment by lekoder** [comment]
@JFonS [minimal reproduction project](https://github.com/lekoder/godot-bug-z-of-light2d).

**Comment by JFonS** [comment]
@lekoder Awesome, I will take a look.

**Comment by JFonS** [comment]
Ok, I found a solution for this, but it doesn't look pretty. 

In canvas.glsl:
```
mat3 inverse_light_matrix = mat3(inverse(light_matrix));
inverse_light_matrix [0] = normalize(inverse_light_matrix [0]);
inverse_light_matrix [1] = normalize(inverse_light_matrix [1]);
inverse_light_matrix [2] = normalize(inverse_light_matrix [2]);
vec2 light_vec = (inverse_light_matrix * vec3(light_uv_interp.zw,0.0)).xy; //for normal mapping
```

This should probably be better done in CPU but I'm not familiar enough with the 2D rasterizer to do it myself.

**Comment by lekoder** [comment]
```
mat3 inverse_light_matrix = mat3(inverse(light_matrix));
vec2 light_vec = (mat3(normalize(inverse_light_matrix[0]),normalize(inverse_light_matrix[1]),normalize(inverse_light_matrix[2])) * vec3(light_uv_interp.zw,0.0)).xy;
```
Works for me. @JFonS will you set up new MR for this?

**Comment by akien-mga** [comment]
Now that Godot 3.1 has been released, we only plan to cherry-pick critical bug fixes to the 3.0 branch, unless there is very strong support in favor of a specific non-critical issue. Removing cherrypick label for 3.0.

**Pull request merged**
