### PR TITLE
Replace subpass textures with color in sky shader

### PR DESCRIPTION
**Pull request by clayjohn**
This changes the API of the Sky Shader a bit as discussed with reduz on IRC. Instead of giving the user access to the ``HALF_RES_TEXTURE`` and ``QUARTER_RES_TEXTURE`` directly. We perform the read for them and only allow them to access the output of the texture read. The reason for doing this is that it is the only way (that we can think of) to properly user cubemap texture lookups when doing the cubemap pass (this is needed for accurate blending across cubemap faces).

We can think about re-exposing the textures in the future if there is a need for it. As it stands, neither reduz or I could come up with a good reason to expose the subpass textures directly. Pretty much any use-case would be better served by passing in a ViewportTexture using a uniform.

I will update the blog post accordingly once this is merged.
@akien-mga Please ping reduz about this once he becomes active so we can merge ASAP and update the blog post before users start experimenting with the current API.

### CODE REVIEW

**Comment by akien-mga** [comment]
BTW, not directly related to this new PR but it seems the shader cleanup does not work properly:
```
ERROR: 1 shaders of type SkyShaderRD were never freed
   at: ~ShaderRD (servers/visual/rasterizer_rd/shader_rd.cpp:489)
```

**Comment by akien-mga** [comment]
@clayjohn When closing the editor. You can see it with `godot --doctool .` too.

**Comment by clayjohn** [comment]
@akien-mga Thanks, I was able to confirm it. It stems from a problem with all materials right now. When a material is freed, its corresponding shader isn't. This makes sense as shaders can be used by multiple materials. However, I'm not sure how reduz wants to handle it.

**Review by reduz — APPROVED** [review]

**Comment by clayjohn** [comment]
@akien-mga force push just adds the code to free the shader in ProceduralSkyMaterial. That will fix the memory leak you are seeing. :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
