### PR TITLE
Assign the min values in gltf accessors [3.x]

### PR DESCRIPTION
**Pull request by SaracenOne**
Make sure min is assigned to GLTF Accessor. Thanks @lyuma

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this needed for `master` too?

**Comment by fire** [comment]
Yes. Trying to think how to verify the fix.

**Comment by SaracenOne** [comment]
Okay, was miscommunication. Will push a PR for master too

**Comment by SaracenOne** [comment]
Actually, just checked and no, I think this is only needed for the 3.x branch.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
