### PR TITLE
Fix close button in FindReplaceBar

### LINKED ISSUE #83456: Cannot close search bar in script editor
### Godot version

4.2.beta.3bc1c9b5e

### System information

Arch Linux

### Issue description

When attempting to close the search bar in script editor the error
```
core/object/object.cpp:1139 - Error calling from signal 'pressed' to callable: 'FindReplaceBar::FindReplaceBar::_hide_bar': Method expected 1 arguments, but called with 0.
```
will appear, and the bar will not close when clicking the X

### Steps to reproduce

open up godot, go into script editor.
press Ctrl + F.
attempt to close the search bar by clicking the X to the right.

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #83456

### CODE REVIEW

**Comment by k0T0z** [comment]
@KoBeWi Sorry but I looked into this issue and I am very curious to know how this solves it? I thought that ` p_force_focus` is an optional parameter!

**Comment by KoBeWi** [comment]
`callable_mp()` doesn't support optional parameters. It's some method pointer limitation, AFAIK it can't be solved.

**Review by akien-mga — APPROVED** [review]

**Comment by k0T0z** [comment]
@KoBeWi hmm, I guess now I am sure that godot has its own GUI framework

**Comment by AThousandShips** [comment]
Default arguments aren't supported for pointers like this AFAIK, they are a compiler side thing, don't even know if C++ introspection can even detect them at all

**Review by Calinou — APPROVED** [review]

**Comment by Calinou** [comment]
Note: No cherry-picking is needed as https://github.com/godotengine/godot/issues/83456 only affects `master`.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
