### PR TITLE
Bump `Rider.PathLocator` nuget version, which provides a fix for detecting Rider installations

### PR DESCRIPTION
**Pull request by van800**
Corresponding change in the RiderPathLocator sources https://github.com/JetBrains/resharper-unity/commit/cc2a0e8b4b9cecdf583bcd9ca8daa7a2d7fe63e5

### CODE REVIEW

**Review by raulsntos — APPROVED** [review]
I can confirm it fixes the issue. Thanks!

**Comment by akien-mga** [comment]
Could you amend the commit message to have the title state what the bug is that's being fixed? E.g. copy the title of this PR. We don't really know what the RIDER bug number corresponds to in Godot ;)

**Comment by van800** [comment]
> Could you amend the commit message to have the title state what the bug is that's being fixed? E.g. copy the title of this PR. We don't really know what the RIDER bug number corresponds to in Godot ;)

Done!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
