### PR TITLE
Created a fallback from the "Save Theme" button to "Save Theme As" when a default theme is in use.

### LINKED ISSUE #18126: Theme with text editor
**Godot version:**

3.1.dev cb7fe2c79

**OS/device including version:**

**Issue description:**

are those menu still functional and needed?
image

I got `Error while saving theme` when save theme from this menu.

**Steps to reproduce:**

**Minimal reproduction project:**

### LINKED ISSUE #22695: Can't save script editor themes
**Godot version:**
Godot custom build caa141a1ac630144e441f89689baa1a74bb3bae5

**OS/device including version:**
Manjaro 64bit 

**Issue description:**
Can't save theme.
image

**Steps to reproduce:**
Try to save the theme.

### PR DESCRIPTION
**Pull request by kis3lori**
Fixes #18126

*Bugsquad edit:* Fixes #22695

### CODE REVIEW

**Comment by akien-mga** [comment]
Seems fine. Another option could be to keep the "Save Theme" option but fallthrough to "Save Theme As" when using a default theme.

**Comment by kis3lori** [comment]
That is a very good idea I haven't considered. 
I was a bit worried that not finding a menu option that you know should be there would be confusing.

Will update,
Thanks

**Comment by Calinou** [comment]
This will also fix https://github.com/godotengine/godot/issues/22695 if it's merged :slightly_smiling_face:

**Comment by kis3lori** [comment]
Thanks for the link. 
Will check that issue as well and update it tomorrow.

**Comment by kis3lori** [comment]
Updated. Now the "Save Theme" button will fallback to "Save Theme As" if one of the default themes is selected. 
It also fixes #22695

**Comment by kis3lori** [comment]
Fixes #22695

**Comment by akien-mga** [comment]
The changes look good, could you squash the two commits together?

**Comment by kis3lori** [comment]
Sure, done :)

**Comment by akien-mga** [comment]
Sorry, I should have mentioned that the commit log should also be amended to reflect the current state, as we're not longer removing the Save Theme option, just re-routing it to Save Theme As.

**Comment by kis3lori** [comment]
Don't worry. Since this is my first open source project I'm still learning the workflow.
Done

**Review by akien-mga — APPROVED** [review]
Looks good to merge.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
