### PR TITLE
implemented scrolling factor for precision trackpads

### LINKED ISSUE #492: Scroll speed too fast on macbook
Scrolling on mac is way too fast. Scrolling 1cm on the touchpad brings you to the bottom of the page. I haven't tested this with a mouse or on windows so the problem might happen there too.

I am using a macbook air 2012 (mavericks)

### PR DESCRIPTION
**Pull request by toger5**
for now its only used in platform: osx and windows
support for almost all ui elements
This solves basically the same issue than #7559 and fixes #492 and #3913 
the difference is, that it sends a new property (factor) with each mouse button event. this factor is 1 by default and any action taken with the scroll even will be multiplied with the factor.
With the macOS trackpads I now can sent hundreds of scroll events and the scrolling is smooth.
#7559 solves the issue of fast scrolling by waiting for enough events that a total scroll offset of one is reached and than sends the event. which is less impact for the rest of the code but it makes the scrolling less smooth.

https://youtu.be/HPSmZnp9gCs

### CODE REVIEW

**Comment by toger5** [comment]
would be amazing if someone also could find out how to access precise scroll values on windows machines. so win laptop with precise trackpads also can benefit from that.

**Comment by toger5** [comment]
okay I have done windows was super easy. so x11 is left...

**Comment by toger5** [comment]
Wouldn't it be cool when we implement a middle mouse button pressed drag also as a scroll up/down event?
This would be really nice because than we could use the scroll events for orbiting in 3d view and for panning in 2d view and we would get immediate and free touchpad support + scrolling with middle moused pressed. without changing any code in the editor node.
only changes which would be needed is: for each platform also send a MOUS_BUTTON.MOUSE_WHEEL event when sending the MOUSE_MOTION event with a little check if the middle mouse button is also pressed.
we even could do the same for touch dragged event. just also send a mouse scroll up event and we have pan support and scroll support.

**Comment by toger5** [comment]
I'm pretty sure the build error on iOS is based on the thing introduced in de0045cf1b0a5e20fbf74da192039d344ee8d0c7

but I'm not sure what I did wrong in the windows build. would be nice if someone could check if he finds something.

**Comment by bojidar-bg** [comment]
@toger5 iOS build error was fixed by #7880.

**Comment by akien-mga** [comment]
CC @FuzzyRhombus and @BastiaanOlij who worked on a similar feature in #7559. Looks like it's a wanted change with 2 PRs in one month for a 3 year old bug report :)

**Comment by toger5** [comment]
I think you have to decide which implementation to use.
The approaches are different. I did this one because when you have an amazing trackpad you want it to be really Smooth (trust me ;) )
the other pr is solving the fast scrolling by waiting for a specific amount of scroll events, than accumulationg the values and as soon as there are enough events to exceed 1 one event gets sended.

My approach is that all events are sense, and there is a new property to the event which tells how much it was scrolled (`factor`).

**Comment by FuzzyRhombus** [comment]
This is exactly what I wanted to do when I got more time to work on https://github.com/godotengine/godot/pull/7559. Going to give it a try in a bit!

**Comment by toger5** [comment]
@FuzzyRhombus Oh thats nice. It would be amazing if you check my code since you are also familiar with the topic!
Can u also take the time to think about the idea I posted in the docs? And share your thoughts?

**Comment by FuzzyRhombus** [comment]
I still have issues with **master** so I applied your commits to updated an **2.1** branch. It's sooooo smoooooth 👍  Only issues I've noticed:
1. **ONLY** in the Project List view, scrolling down is extra fast - scrolling up is fine and everywhere else it is fine
2. Scrolling in the animation editor does not work at all, but after testing a previous build, it still didn't work so I don't think there is a breaking change here

Your code looks good and the changes are consistent so I'm quite baffled by the first issue. Do you know what GUI element the project list view is built from? `item_list`?

----

The only things I needed to do to get this working on **2.1** is I just stubbed `get_value` and `set_value` in `scene/gui/range.h`:
```cpp
void set_val(double p_val);
inline void set_value(double p_val) { set_val(p_val); }

double get_val() const;
inline double get_value() const { return get_val(); }
```
and `is_visible_in_tree` in `scene/2d/canvas_item.h`
```cpp
bool is_visible() const;
inline bool is_visible_in_tree() const { return is_visible(); }
```
I have updated these changes in my fork, though I have not yet pushed the changes because I cleaned up the branching and it will break my PR. That said, @BastiaanOlij I think this is a more complete solution than https://github.com/godotengine/godot/pull/7559 - can you take a look and give it a try both on **master** and **2.1** when you have a chance?

----
@toger5 I took a look through the the doc you posted and I can see what you're getting at, though it is  a little confusing. =/ Moving forward I think it is a good idea to separate mouse button and mouse scroll events as their own input types. However, I think supporting other gestures should also remain their own event types as well. Instead of converting event types I think internally multiple types of events should be supported for a given control. As an example, `scroll_bar` should be able to respond to different event types (scroll wheel, scroll wheel with factor/momentum, touch drag, etc) rather than internally convert them all to a scroll wheel event first. This way there is no issue with data loss/conversion and later changes to one event type will not break control from other types. I think others should chime in though - I'm not sure what's currently planned for v3

**Comment by toger5** [comment]
@akien-mg squashed.

**Comment by FuzzyRhombus** [comment]
@toger5 I just pushed my changes to to the branch **osx-scroll-factor**. However you think is best is fine. I did a rebase on the official 2.1 first (already behind haha) and `cherry-pick`ed your commits. My changes shouldn't be applied to **master** because it for older compatibility. If you can give it try on 2.1 please let me know if you encounter the same issues I mentioned. Otherwise all I've done thus far is stub some functions that had name changes

**Comment by toger5** [comment]
@FuzzyRhombus sorry I still had no time testing your 2.1 branch...
For anybody else who can test would be amazing to try the branch of FuzzyRhombus.
Maybe I can do it tonight...

**Comment by toger5** [comment]
tried the branch of @FuzzyRhombus 
Works for me!

Although it says different in the commit message windows trackpads also should be supported. so if someone could try with a windows trackpad would be great. And maybe fix the windows implementation if I did something wrong

@FuzzyRhombus about the issues you mentioned.
I also have fast down scrolling in the project list. But can't find the issue.

some time passes...

Found the issue:
It uses the ScrollContainer class. And for scrolling down the factor actually was missing. Wondering why the editor almost doesn't use ScrollContainer? Why do things like ItemList not inherit from it?
maybe someone can explain that to me. I would be really interested!

This also was missing in my version so ill update both.
Updated my pr (still squashed to one commit) and created a pr for @FuzzyRhombus so you can use the changes in you 2.1 branch.

Than we can merge!

**Comment by toger5** [comment]
Who is going to fix the conflicts? do I have to merge? How would I than keep a decent history since my commit would be somewhere a month ago?

**Comment by akien-mga** [comment]
> Who is going to fix the conflicts? do I have to merge? How would I than keep a decent history since my commit would be somewhere a month ago?

You have to fix the conflicts by rebasing on top of the master branch. The rebase will keep a decent history as the commit will be reapplied on top of the master branch, and thus the commit date will be that of the rebase. The authorship date will stay 21 Feb though, which is why in the GitHub view it will appear in the right place (next to early April commits) but with the 21 Feb date.

**Comment by akien-mga** [comment]
Also make sure to run your code changes through clang-format, our code styling tool, otherwise Travis' format check will fail (I see a couple lines with trailing whitespace, or braces with a different style than ours).

Documentation on how to use Travis coming soon(tm), but if you're on Linux (or potentially macOS, untested) you can check our pre-commit hook in `misc/hooks`. Otherwise you can configure your IDE to run clang-format (ideally version 3.9.x) automatically on your modified files. And finally you can also run it manually: `clang-format -i -style=file <path/to/files>`.

**Comment by toger5** [comment]
I'm struggling with the rebase since the editor got moved to editor/ from tools/editor.
Git has my changes in new files in tools/editor now instead of merging them with editor/

If someone has a smart idea how to deal with that, any advice is welcome.

**Comment by toger5** [comment]
Okay it was not as confusing as a though as soon as I started looking into it...
did the merge. so lets see what travis says and than we can close the pr.

**Comment by toger5** [comment]
tested and works great with 3.0 (at least on my computer)

**Comment by akien-mga** [comment]
Some comments:
- There are two commits with the same name, the second one should be squashed in the first one (see `git rebase -i HEAD~2`)
- The commit log should be edited to reflect the final state of this commit, not the original one. It still mentions that the feature only works on OSX although you later added Windows support.
- There are still various style issues so travis will complain about those, see https://github.com/godotengine/godot/pull/7864#issuecomment-291068400

**Comment by toger5** [comment]
Oh didnt saw the second commit. Yea need to look into the formatting.
Ty for the list. I will write when i fixed it

**Comment by toger5** [comment]
seems like the clang format for .mm files is a little off? it uses spaces (no tabs). Is that intended? check the commit to have a look at it

**Comment by akien-mga** [comment]
Hm yes sorry, I think we're not running clang-format on .mm files for now. The tool has kind of support for it, but it's not configured yet (and I'm not sure it would work properly).

Hm, undoing the changes to the .mm file is going to be fun... @bojidar-bg Remember how to get back the state from a previously rebased commit?

**Comment by akien-mga** [comment]
I'll open an issue about it, we need to either include them in the clang-format rules and find out how to do it properly, or protect them with `/* clang-format off */` comments to avoid such problems.

**Comment by akien-mga** [comment]
@toger5 I think you may be able to get back the previous state for the .mm file with:
```
git reset 024ef9d platform/osx/os_osx.mm
```
and then amend the previous commit to get back your non-clang-formatted changes to the .mm file. Then it should be good to go, we don't apply our style guide to the .mm files (yet).

**Comment by bojidar-bg** [comment]
@toger5 @akien-mga You can get the commit ID for something rebased with `git reflog` (assuming it hasn't been garbage-collected), then `git checkout <ID> -- <file paths>` to get them back (or `git reset --hard`, but I think I like checkout more for this).

**Comment by toger5** [comment]
The problem is that i rebased, so there is only one commit which has all the changes: style, and trackpad implementation in the os_osx file

I can run the xcode indentation tool which does a good jub for indentations,because thats the biggest issue atm. Than it would look pretry good. But it would mess up the blame view...

So if i can just format with xcode would make things much easier for me. Is that fine or should i try my luck with git?

**Comment by pixelpicosean** [comment]
Is it possible to merge this PR into 2.1 branch which is used by most developers?

**Comment by toger5** [comment]
As far as i know @FuzzyRhombus has done that in another pr. So if he updates it also should be in 2.1

**Comment by FuzzyRhombus** [comment]
@pixelpicosean check out [this commit](https://github.com/FuzzyRhombus/godot/commit/4948b20a85f1611baca7eb9e286d68466d8c11f5) for 2.1 compatibility - only changes that were necessary. I'm using it for a stable build so I'm unsure if this will still be needed with the 2.1.3 release but I'll check it out

**Comment by toger5** [comment]
I just tried to merge with master since this is still not merged because of conflicts.
It Seems like the .gitignore is missing .import files. 
Check the changed files.

**Comment by toger5** [comment]
what Is the issue with the clang formatting this time?

**Comment by bojidar-bg** [comment]
Trailing spaces and tabs.

**Comment by toger5** [comment]
I don't want to fix it by hand. I set up the got hook.
The resulting style has spaces instead of tabs.

**Comment by toger5** [comment]
@akien-mga This pr is now pending for a long time. I think most of that is a result of me not getting the clan formatting right. For me the .mm don't format to tabs...
Also: as I supposed to squash the two commits into one?
if so how would I approach squashing the old one into the newst although there are so many commits in-between.

**Comment by akien-mga** [comment]
I did the rebase myself locally, this way non-trivial as your branch is quite old and lacked many formatting changes made subsequently to the os_osx.mm file... so I ended up syncing your changes manually based on https://github.com/godotengine/godot/pull/7864/files?w=1.

Will push my rebased commit if it builds locally.

**Comment by akien-mga** [comment]
Merged as 304a1f5.

**Comment by toger5** [comment]
@akien-mga thank you so much !

**Comment by FuzzyRhombus** [comment]
Happy to see this merged! Will this be included in the next 2.1 release as well?

**Comment by pixelpicosean** [comment]
@FuzzyRhombus I've port this PR into 2.1 branch, currently been waiting for merge. It works pretty the same like v3, hope you like it.

**Pull request closed without merging**
