### PR TITLE
Fix RayCast not updating when debugging collissions

### LINKED ISSUE #4224: Visible Collision Shape won't draw new cast_to of raycast2d
Hi. I have a raycast2d node and enabling Visible Collision Shape draws the raycast2d as an arrow as  spectated. But if I set the cast_to property to a new one on runtime, the arrow remains the same position, even though the cast_to is different (and I'm 100% sure it is). Now, it does draw it correctly when I set the cast_to on _ready() and _fixed_update but I'm setting it on other methos that is being call in _fixed_update, weird....

### PR DESCRIPTION
**Pull request by neikeq**
Fixes #4224

### CODE REVIEW

**Comment by akien-mga** [comment]
What about the other collision shapes that you mentioned in https://github.com/godotengine/godot/issues/4224#issuecomment-205447885 ?

**Comment by neikeq** [comment]
@akien-mga That was beyond my level when I checked. I will try again next week.

**Comment by akien-mga** [comment]
Thanks. Should we open an issue about it then?

**Comment by neikeq** [comment]
Yes. I just opened it: #4260

**Pull request merged**
