### PR TITLE
Fix UID string generation

### LINKED ISSUE #83843: ResourceUID doesn't use `z` and `9`
### Godot version

c21c2706ad33c59295f6a3ac1e128db6fa7cce69

### System information

n/a

### Issue description

These lines have an off-by-one error:

https://github.com/godotengine/godot/blob/master/core/io/resource_uid.cpp#L38-L39

No big deal, but it makes encoded RIDs potentially longer than they need to be.

If fixing the bug would cause trouble reading older files, then at least it should be commented.

### Steps to reproduce

n/a

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by k0T0z**
Fixes #83843

### CODE REVIEW

**Comment by AThousandShips** [comment]
For example, what was previously encoded as `uid://sxovua31m8wi (0x1234567812345678)`, will now be decoded to `0x221113bad5dbc940`, which now will be encoded as `uid://j82hebx39tsa`

**Comment by AThousandShips** [comment]
As there's no current way to indicate what version a UID is from, there's no way to ensure compatibility

Also the mistake in the code only restricts the base from base 36 to base 34, which is a minor difference, it won't reduce the total size of any ID I'd say

**Comment by k0T0z** [comment]
@AThousandShips I expected that ofc as it's working that way. I am gonna look into it again later tonight

**Comment by k0T0z** [comment]
> This change can be considered only if it preserves the existing UIDs.

@KoBeWi @AThousandShips No way for preserving current UIDs?

**Comment by AThousandShips** [comment]
How would there be? How would you look at an existing UID and detect that it is in fact the old system?

**Comment by k0T0z** [comment]
I may need to get more familiar with the resources system before any more discussions but to answer your question I guess we can update every usage of the ``char_count`` variable inside ``resource_uid.cpp`` as from what I can see is that this variable doesn't have any usage outside this file. Please correct for me if I am getting it wrong.

**Comment by AThousandShips** [comment]
> You mean we can't get old UIDs to ensure that they are the same?

I mean that if you open an existing file the UID it contains will be broken, as not all UIDs are stored in text, but some are stored in binary, it would simply be broken in general, existing UIDs must still be valid

**Comment by KoBeWi** [comment]
AFAIK UIDs are integers (or some other type), what is saved in scene is just its string representation. Keeping strings for old IDs might be impossible without over-engineered compatibility code. Which makes it even worse xd

>  it won't reduce the total size of any ID I'd say

It does save one character per few IDs.

**Comment by AThousandShips** [comment]
> I thought that you were handling this bug inside the generation code 

Handling what bug?

**Comment by AThousandShips** [comment]
To clarify, there's *no* broken behaviour currently, nothing that is broken that needs fixing, I'm quite confused as to what you are talking about with this and what you are assuming about the current code

**Comment by k0T0z** [comment]
I have a problem explaining stuff to others but I am working on it 😅. Anyway, I mean this fix in the PR (which you said it's not a bug)  is already handled inside the code generation of the UID. I mean that before using the ``char_count``, you increment it by 1, and when I provided the fix in this PR, I thought that I would just go to all places where ``char_count`` is used and just remove that incremented 1 because I have already added it. But I understand now that there's handling to it happening, you already use the ``char_count`` as-is inside the UID generation code which means by modifying it (the modification in this PR), everything blew up.

**Comment by k0T0z** [comment]
@AThousandShips I suppose that this should be archived?

**Comment by AThousandShips** [comment]
I think this can't be added until far in the future so I'd say so, but it's up to you, I don't think is an impossibility, only that it isn't possible right now due to the compatibility

**Comment by akien-mga** [comment]
Yeah it's better to keep things unchanged for compatibility's sake.

**Comment by k0T0z** [comment]
@AThousandShips @akien-mga Very cool, I was going to close it after you gave me the final decision. Maybe, after working here and understanding more about Godot architecture, I can find a solution for it in the future.

**Pull request closed without merging**
