### PR TITLE
Improve docs for KinematicBody linear_velocity, fixes #23927

### LINKED ISSUE #23927: KinematicBody doc talks about pixels per second, which does not apply in 3D
https://github.com/godotengine/godot/blob/c48027af922a7203dc53bc41435a9d9021ba3291/doc/classes/KinematicBody.xml#L92

### PR DESCRIPTION
**Pull request by aaronfranke**
This is hardly vital but also doesn't break anything, may as well put it on the 3.1 milestone.

Fixes https://github.com/godotengine/godot/issues/23927 Discussion here: https://github.com/godotengine/godot/issues/23927

### CODE REVIEW

**Comment by cbscribe** [comment]
Good catch on the pixels mention in 3D.  I have two problems with this PR:

1) "speed" and "velocity" are two separate concepts. One is a scalar and one is a vector. So it's inaccurate to say that "linear velocity is a value of speed". It's a velocity, it's there in the name. These extra words muddle the meaning.

2) " this is done by the method." - agreed this could be better written, but how does "the physics engine handles applying the velocity" explain why you don't need to multiply by `delta` in this method? Perhaps something more like "delta is applied automatically by the method."

**Comment by aaronfranke** [comment]
As I noted [here](https://github.com/godotengine/godot/issues/23927#issuecomment-441350365):

> "Speed" isn't technically accurate but "linear_velocity" already contains "velocity" so using that word again would be redundant and potentially less clear.

Also, it should be pretty obvious that this is a vector value since it will either be Vector2 or Vector3.

My main concern is redundancy, but if it's desired to change it, we can do that.

**Comment by cbscribe** [comment]
We're on the same page, then - I'm concerned with redundancy, too. It already has "velocity" in it, so nothing more is needed.

Plus,l "value of speed" just sounds awkward. It's like when you hear people talking about a car moving "at a high rate of speed" instead of just "at a high speed". I would appeal to the [docs writing guidelines](https://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html#rules-for-a-clear-english):

>A technical writer’s job is to pack as much information as possible into the smallest and clearest sentences possible.

"linear_velocity is a value in pixels per second" is concise and descriptive, which results in less misunderstanding and easier translation. It describes the parameter in the same way other parameters are defined in the rest of the docs.

**Comment by cbscribe** [comment]
What is your objection to the word "velocity", which we already have?

**Comment by aaronfranke** [comment]
If someone needs a description of what `linear_velocity` is, then "velocity" doesn't help them.

**Comment by cbscribe** [comment]
But this is the technical class reference. This is not the place to be defining terms like "velocity". As a developer, I want to come to these docs to find out what a particular method does and what its parameters are. I don't want to have to wade through introductory material. If an inexperienced reader doesn't understand the fundamentals, I want them to be directed to a tutorial.

**Comment by cbscribe** [comment]
Alright, I think we're good. Thanks for the spirited discussion! :)

**Pull request merged**
