### PR TITLE
New shake function

### PR DESCRIPTION
**Pull request by ghost**
This function is used for shaking the screen.Usage :  camera.shake(rand_range(-2,2.3),rand_range(-1,1)) 

Also I`d love to add the possibility to fade and flash the screen but I cant find anything related to color in camera_2d.cpp.Any help please?

### CODE REVIEW

**Comment by reduz** [comment]
i think for shake, it's better to to use the x and y offset parameters and
then simply do an animation that animates those. In 2D this works very
well, but I guess this could be added to 3D too.

**Comment by Murii** [comment]
Ok boss.What if I want to make a function in camera_2d.cpp which is suppose to draw rectangles on the screen how can I do that?I`ve been struggeling for some hours and cant find the answer.I`m asking this because I want to make a rectangle and baseed on it`s color make some fade/flash effects!

**Comment by reduz** [comment]
you probably can't do this in Camera2D, but you can create a CanvasLayer
and put as a children a fullscreen quad (TexureFrame maybe, or a control
you draw yourself) that you can hide/show to make flashing effects.

Camera in 2D does not do any drawing, it just controls the screen offset in
the root viewport

**Comment by akien-mga** [comment]
Already implemented in cef3bd0 apparently.

**Pull request closed without merging**
