### PR TITLE
made tabs visible in debugger fixes: #11212

### PR DESCRIPTION
**Pull request by toger5**
- the stylebox is changed so the top part is transparent when the
   debugger is selected

the implementation is pretty damn hacky... so I don't know if it is even worth.
pseudocode how it's done
```
func switch tab:
...
    if tab is Debugger:
        sb = load and copy normal style box
        sb -> make the top expand margin negative so it fits the theme, font height...
        override bg panel style box with sb
    else:
        load stylbox from theme
...
```

### CODE REVIEW

**Comment by djrm** [comment]
screenshot

**Comment by toger5** [comment]
in the other discussion
wait let me also post it here

**Comment by djrm** [comment]
@toger5 now that i see it im not that sure, now its hard to tell which are the top level tabs, i kinda like it, but im not sure about it.

**Comment by toger5** [comment]
oh you mean the differentiation between Output/Dbugger... and  Debugger/Errors/remote Inspector ...
I think it is still pretty obvious since the editor always starts with the bottom panel closed. So everyone sees them as the main tabs.
I think without the tabs it's just really hard to identify those buttons as tabs...

**Comment by djrm** [comment]
@toger5 i think you are right, in that case maybe you can also remove the extra margin from the debug panel, to match the rest of the element (like console)

**Comment by toger5** [comment]
@djrm I'm not sure which extra margin you mean?
the one on the left + right of the debug panel/output/audio...

**Comment by djrm** [comment]
@toger5 this is a double maring, since we have the margin from the tab container, plus the panel margin
screenshot from 2017-09-13 22-23-24

**Comment by toger5** [comment]
removing the extra margin is hard. I had no idea how to solve it properly...
the issue: if I remove the margin from the bottom panel container sb than the Output/Debugger... buttons move too since they are also part inside that container.
And I can't add additional margins to the tabContainer control since they get overridden by the box container...
Only solution I can think of is removing the margin from the bottom panel container entirely, and adding manual additional panel containers to all the tabs that don't have a margin on the left + right... (output/animation/audio).
but that would force all the plugin created bottom panels to also add the container to look good which is bad... so not a solution...

**Comment by toger5** [comment]
Oh just had a idea..

I could try adding a control into the vboxContainer and than I can use margins for the tabContainer inside of the control.

**Comment by djrm** [comment]
@toger5 i think this has a simpler solution, just add a custom style for the debuger tabs container, that has 0 margin.

**Comment by toger5** [comment]
than there still would be an offset for the most left tab. since it would not be moved by changing the panel style box...
but maybe that is the best solution... at least nothing overkill

**Comment by toger5** [comment]
Damn it...
the double border took me forever to figure out.
I did so many different approaches... to find something really simple.
the worst part was that I thought, the tabContainer is parented to the box container. but there is a control node parented to the vBox and the abContainer to it. (obviously)

**Comment by toger5** [comment]
it's fixed now though!!

**Comment by akien-mga** [comment]
What's the status here?

**Comment by toger5** [comment]
It works and looks great. It is a little Code but a little hackt compromise though.
Every other approach I can think of would need bigger changes in core classes which are usually unnecessary except in this case.
But definitly ready to merge

**Comment by akien-mga** [comment]
@djrm Happy with it too?

**Comment by djrm** [comment]
@akien-mga yeah why not.

**Pull request merged**
