### PR TITLE
Fix AnimationPlayer editor length and step synchronization

### PR DESCRIPTION
**Pull request by timoschwarzer**
## Before
peek 2019-01-03 18-29
peek 2019-01-04 20-13

## After
peek 2019-01-04 21-01

### CODE REVIEW

**Comment by timoschwarzer** [comment]
I removed the `_update_length` (and related) methods because they weren't in use since the animation length currently can't be changed inside the animation editor.

**Comment by akien-mga** [comment]
Needs a rebase after recent changes to the AnimationPlayer (if the bug is still relevant).

**Comment by timoschwarzer** [comment]
@akien-mga Rebased.

**Comment by akien-mga** [comment]
Seems like you did a merge/pull and not a rebase, so there's an extra merge commit. `git rebase upstream master` (if you have `upstream` tracking `godotengine/godot`) should fix it.

**Comment by timoschwarzer** [comment]
Oops, yeah, I did it through the GitHub UI, will do a manual rebase later today

**Comment by timoschwarzer** [comment]
@akien-mga should be rebased now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by volzhs** [comment]
> I removed the _update_length (and related) methods because they weren't in use since the animation length currently can't be changed inside the animation editor.

I guess there was a misunderstanding for changing animation length in animation editor.

anim_editor

**Comment by akien-mga** [comment]
For the reference, this was reverted in #29329, with the feature redone differently in its second commit.

**Pull request merged**
