### PR TITLE
Implement more atomic ops

### PR DESCRIPTION
**Pull request by RandomShaper**
**(Commits are meant to be squashed before merge.) Kept them to show the process better.**

Commit 1:
- The public API looks the same but with added overloads.
- The implementation uses templates or overloads depending on the context to avoid code duplication.

Commit 2:
- Implement add & subtract atomics.

The most error-prone things are the new add/sub functions for MSVC-Windows.

### CODE REVIEW

**Comment by RandomShaper** [comment]
I need some feedback on this.

One thing to consider: before Windows 7 (IIRC) there were no proper atomic subtraction functions so I've implemented them as signed addition of the operand negated.

They should be safe as long as the unsigned operand stays in the representable range of the signed.


As an alternative, the 32-bit version could be implemented in terms of 64-bit operations to avoid that, but I guess it's better to leave them as "natural" as possible.

For the 64-bit versions there is no simple workaround. But it's not a big issue, is it?

Anyway, if Godot started requiring a higher version of Windows, the proper unsigned subtraction primitives would become available.

**Comment by RandomShaper** [comment]
Furthermore, as these new operations are intended currently only for tracking the total allocated size, they wouldn't break anything and we could fix them as required if they had issues.

What do you think?

**Comment by reduz** [comment]
they look fine, but so just you know, in general we are now doing PR
Mondays on IRC, which is when we discuss and merge most PRs, feel free to
drop by!

**Comment by RandomShaper** [comment]
I wasn't aware. Good to know!

**Comment by reduz** [comment]
Yeah, aplogies if you didn't know about it!
if you could join us it would be great, we do Merge Mondays at around 8pm.

**Comment by vnen** [comment]
> we do Merge Mondays at around 8pm.

8pm in UTC, to make it clear.

**Comment by akien-mga** [comment]
@reduz said on IRC it should be good to merge; do you still want to squash the commits together? IMO it's fine to keep them as is.

**Comment by RandomShaper** [comment]
I'll let you as an experienced mantainer decide what's the best option for the commit history.

By the way, in case you wonder why I've just pushed, it's been because of a little mistake with search and replace by which I ended up with `_WIN64_WINNT`.

**Comment by akien-mga** [comment]
For such changes I don't mind a bit of verbosity in the commit history, so it's good :) I'll merge once Travis is happy.

**Pull request merged**
