### PR TITLE
Fix wait for thread not started

### LINKED ISSUE #76456: "Attempt of waiting to finish on a thread that was never started" error when Godot exits
### Godot version

e0e93ce09

### System information

ArchLinux x11

### Issue description

```c++
> godot4 --help
...
ERROR: Attempt of waiting to finish on a thread that was never started.
   at: wait_to_finish (core/os/thread.cpp:81)
```

Actually using the editor also produces this error often.

### Steps to reproduce

`godot-binary --version`

### Minimal reproduction project

n/a

### PR DESCRIPTION
**Pull request by spanzeri**
At least the one I could find. Noise and AudioDriverDummy was happening for me on Win11, a couple where reported and iOS didn't match the android counterpart.

Fix https://github.com/godotengine/godot/issues/76456

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]

**Comment by RedworkDE** [comment]
The CI still has a few (not sure how many are actually duplicates):
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334013?pr=76511#step:9:30
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334013?pr=76511#step:9:901
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334013?pr=76511#step:12:24
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334013?pr=76511#step:13:29
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334133?pr=76511#step:11:207
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334133?pr=76511#step:15:53
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334133?pr=76511#step:15:143
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334133?pr=76511#step:16:123
- https://github.com/godotengine/godot/actions/runs/4822242570/jobs/8589334133?pr=76511#step:17:32957

**Comment by spanzeri** [comment]
Found a few more. Audio driver and a couple of manager that have a finish function that could potentially be called without a init (which happens in a few tests). I can't run all the same configs as the CI, so we'll see if I missed some more :)

**Review by RedworkDE — APPROVED** [review]
Changes LGTM and the CI doesn't find any further issues, so this is probably most of them fixed.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
