### PR TITLE
Expose the optimize method of the Animation class to gdscript.

### PR DESCRIPTION
**Pull request by Malcolmnixon**
This PR exposes the Animation optimize method so it can be accessed from scripts.

This is to support optimization of dynamically-generated animations such as when developing Mocap recording extensions.

### CODE REVIEW

**Comment by fire** [comment]
In messages we discussed the two systems godot has for reducing memory usage of animation clips.

1. compress
2. optimize

**Comment by Malcolmnixon** [comment]
> In messages we discussed the two systems godot has for reducing memory usage of animation clips.
> 
> 1. compress (in theory bitcrunched so quantized but keeps keyframes)
> 2. optimize (corruptable)

Currently the scene importer has optimize enabled by default and compress disabled by default.
https://github.com/godotengine/godot/blob/4788f54d9767425bf5435b1cc940885d357795c5/editor/import/3d/resource_importer_scene.cpp#L2073-L2077

Additionally while I haven't seen any issues with optimized animations, compressed animations sometimes cause the skeletons arms to glitch out.

I'm trying to give my Mocap recording addon the same sort of capabilities as the importer - it's already got the compress exposed, but the optimize is currently inaccessible.

**Comment by fire** [comment]
We also discussed how the import property means we cannot not improve the code under the scenes.

I think we should expose both compress and optimize for runtime usage outside of the import/export system.

Will need to file two bugs relating to compression and a crash with @Malcolmnixon 's test case, but they're not directly related to this pull request.

**Review by radiantgurl — APPROVED** [review]
Static analysis of the code looking great!

**Review by TokageItLab — APPROVED** [review]
It's fine IMO. I don't see any particular reason to hide it from gdscript.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
