### PR TITLE
Add syntax highlighter icons

### PR DESCRIPTION
**Pull request by MewPurPur**
Feel free to bikeshed. (this one below is slightly outdated, see comments)

image

### CODE REVIEW

**Comment by YeldhamDev** [comment]
The bucket's handle will be basically invisible at the normal icon size.

**Comment by MewPurPur** [comment]
This is 125%, so not that much more, but yeah you're right. Any suggestions for uncluttering this? It's hard to call it a bucket without a handle.

**Comment by YeldhamDev** [comment]
@MewPurPur Maybe just remove the bucket and make the paint droplet bigger?

**Comment by akien-mga** [comment]
How about just colored code silhouette, without the paint / bucket? Similar to the minimap preview / GDScript thumbnails in the FS dock.

**Comment by MewPurPur** [comment]
I'm on it. Shaders already use this pattern in their icons, but maybe it's not that big a problem.

**Comment by YuriSizov** [comment]
The shaders one could be changed, I don't particularly see why that would be a representation of text shaders out of all things. But I would argue that the icon for the highlighter should not look like that either. It makes me think of a code resource, not a code highlighter resource, you know?

Perhaps you can be clever with it, and show half blocks as colored and half as plain gray, and without a "file" shape around it?

**Comment by MewPurPur** [comment]
Updated the PR description, tell me what you think of the new ones.

**Comment by MewPurPur** [comment]
Oops, I slipped a few small optimizations from my next SVG optimization PR into this branch. Nothing too important.

**Comment by MewPurPur** [comment]
Fair point, but I think it's optimal. If I make the caret taller, it looks silly because it's taller than the text lines. If I increase the distance between text lines, I have to add a full pixel as the text looks bad when not pixel-aligned. But then there's not enough space to increase the height of the caret.

**Comment by YuriSizov** [comment]
> If I make the caret taller, it looks silly because it's taller than the text lines.

It's an abstract thing. I think you can allow it to be two-lines tall. It's an important bit that's very hard to read making icons for all intents and purposes identical. Otherwise, I love the new design!

**Review by YuriSizov — APPROVED** [review]
If the latest suggestions don't work out, it's still fine as is (and other random improvements are welcome).

**Comment by MewPurPur** [comment]
I agree with you totally, but I *did* try this already. I made the caret taller at first, but found it silly and distracting in practice, so I shrunk it back to 4px.

**Comment by YuriSizov** [comment]
Can you show how it looks?

**Comment by MewPurPur** [comment]
One ~~sec~~ hour, I want to finish my current PR before switching branches

**Comment by MewPurPur** [comment]
@YuriSizov 

TBH it's not as bad as I remember :thinking: 

image

I don't know which one I prefer, maybe this one.

**Review by deralmas — APPROVED** [review]
So pretty!

This is a really nice PR, optimizations and everything.

**Comment by MewPurPur** [comment]
The optimizations were an oopsie, they were supposed to be in my next huge SVG optimization PR

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
