### PR TITLE
Prevent Editor from hang when importing stl as mesh

### PR DESCRIPTION
**Pull request by aswinmohanme**
When Importing an stl file into Godot from the import mesh menu, the
editor hangs indefinitely. Since only Obj files are supported, the data
remains unparsed and hence the editor enters an infinte loop.

This commit fixes this issue by exiting the loop when godot has finished
parsing the file, irrespective of whether any meaningful data was
extracted out.

Fixes: #9200

### CODE REVIEW

**Comment by bojidar-bg** [comment]
@aswinmohanme Can you run the following commands to remove the `authors.h` file from your commit? :
```bash
# Assuming you are in the repo root:
git rm editor/authors.h --cached
  # --cached is so it won't remove the file itself
git commit --amend
  # --amend to edit the last commit, instead of creating a new one
git push --force # [myorigin] [mybranch]
  # --force to overwrite the commit in your fork (since we edited it)
  # This is needed since git does not allow overwriting of already-pushed commits by default
```

@akien-mga Isn't it supposed to be `.gitignore`-ed? 😕

**Comment by akien-mga** [comment]
> Isn't it supposed to be .gitignore-ed? 😕

Not yet in the 2.1 branch apparently.

**Comment by reduz** [comment]
I don't even know what a stl file is :\

**Comment by akien-mga** [comment]
Merged manually as 945f40303.

**Pull request closed without merging**
