### PR TITLE
Add Save option to resource property menu

### PR DESCRIPTION
**Pull request by JFonS**
Add a convenience option to save resources directly from the inspector, without having to first edit the resource itself.
 
save

### CODE REVIEW

**Comment by Zylann** [comment]
Related https://github.com/godotengine/godot/issues/21158

**Comment by fracteed** [comment]
Looks like an excellent idea. Will this also work for saving .mesh files out from a Meshinstance? There doesn't seem to be a way to do this in 3.1 like you could in 3.0

**Comment by JFonS** [comment]
@fracteed I haven't tested, but it should work. If you can select "Edit", click on the tools icon in the inspector, and then save the resource (in current master) it will probably work with this new button.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
