### PR TITLE
Fixed antialiased option for Polygon2D

### LINKED ISSUE #26823: Polygon2D node not configured for AA as of 3.1
EDIT 2: I've discovered this issue is caused by changes to `scene/2d/polygon_2d.cpp`, changes introduced in a 2018 May commit by reduz ([skeleton for 2D WIP](https://github.com/godotengine/godot/commit/b3e4bc562c07142d48907278f9cc496791ff7b33)).

Before (line 200): 

    VS::get_singleton()->canvas_item_add_polygon(get_canvas_item(), points, colors, uvs, texture.is_valid() ? texture->get_rid() : RID(), RID(), antialiased);

After (line 277): 

    VS::get_singleton()->canvas_item_add_triangle_array(get_canvas_item(), indices, points, colors, uvs, bones, weights, texture.is_valid() ? texture->get_rid() : RID());

Aside from the obvious lack of the `antialiased` option in the newer line, it's also using `canvas_item_add_triangle_array` which was also used before 3.0, and there are 3 of the `get_singleton` lines that look like they should have all options.

Tacking `antialiased` to the existing lines doesn't work (it will actually break them in 2 of the 3, even if set to `false` instead). Just replacing all 3 lines with the older line **does** bring AA back, but obviously that breaks the 3.1 changes.

I suspect that reduz configured the 3.1 polygon2D node specifically for character animation (skeletons and internal vertices) whilst thinking 3.0's AA was flat broken (like I've said elsewhere, it works with disabled HDR and/or setting 2D framebuffer allocation), so it's not exactly a regression and I'm guessing things would need to be at least slightly reworked for AA to work with reduz' changes.

----------------------------

EDIT: Still present as of 3.2 alpha 3. AA enabled via gdscript drawing works fine, so it seems to be just the checkbox in the editor that is broken.

---------------------------------

(below is the original issue info, which is less correct/relevant than the above)

It just doesn't work anymore. Tested on Linux+nVidia and W10+AMD (different hardware), so I don't think this is a compatibility issue. Also happens both with GLES3 and GLES2 renderers.

This is a regression present even in 3.1 alpha 1, so the change that resulted in this was likely made in the master branch between 3.0.6 and alpha 1. This directly relates to issue #10241 in that this issue is a regression on the progress to fulfill it... although after this issue is fixed AA will still need to be implemented on line2D for 10241 to be fulfilled.

This still affects 3.1 RC 1.

Notes:

- AA in 3.0.6 conflicted with HDR (which was on by default). Turning HDR off in the project settings was needed for AA to work, aside from on nVidia hardware where HDR could be on if the framebuffer was explicitly set to 2D. That might be related or might need to be a separate issue (I'll make it if it still occurs after AA comes back). Inner AA seemed to still work with partially transparent shapes, so the issue with HDR and/or 3D framebuffer was likely an issue with passes.

- AA for HTML5 in 3.0.6 didn't work at all, and I have no idea about MacOS, iPhone, Android, Blackberry etc.

-----------

Hopefully this is an accidental breakage, but I can understand if this cannot be fixed until the renderer is adapted to use Vulkan. And it's somewhat made better by the fact that 3.0.6 can still be used, albeit while missing features/fixes.

This issue is also related to (less important) issue #25120 in that both related to polygonal art.

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
The property wasn't used anymore after switching from `canvas_item_add_polygon()` to `canvas_item_add_triangle_array()` for drawing.

I've just added an argument to `canvas_item_add_triangle_array()` to enable antialiasing (still disabled by default), everything is already working fine with GLES3 on the render side.

Also had to change `ClassDB::bind_method` to support 7 default values.

Fixes #26823

### CODE REVIEW

**Comment by akien-mga** [comment]
Might be worth reviewing the other uses of `canvas_item_add_triangle_array` to see if we want to enable antialiasing by default:
```
scene/2d/line_2d.cpp
302:    VS::get_singleton()->canvas_item_add_triangle_array(

scene/2d/navigation_polygon.cpp
454:                            VS::get_singleton()->canvas_item_add_triangle_array(get_canvas_item(), indices, vertices, colors);

scene/2d/tile_map.cpp
665:                                                            vs->canvas_item_add_triangle_array(debug_navigation_item, indices, vertices, colors);

scene/resources/style_box.cpp
836:    vs->canvas_item_add_triangle_array(p_canvas_item, indices, verts, colors, uvs);
```

**Comment by akien-mga** [comment]
Should also fix #10241 I guess if enabled for Line2D?

**Comment by pouleyKetchoupp** [comment]
@akien-mga For some reason, the antialiasing still doesn't work for Line2D even when forcing `antialiased` to true in `canvas_item_add_triangle_array()`.

**Comment by insomniacUNDERSCORElemon** [comment]
There's still an issue of AA conflicting with HDR (or alternatively 3D framebuffer, at least for nVidia), I don't suppose you could investigate that @pouleyKetchoupp ? If not, I could write up an issue for that as well (makes more sense when AA is actually test-able though).

I mean even if you can get AA working on Line2D, it seems a bit odd to close 10241 if you need workarounds to have AA working (either explicitly drop HDR or 3D).

There are also minor rendering issues (eg AA creating an outline on partially transparent polygons), that I could see possibly being fixed on accident if 2D rendering were overhauled/completely re-written in the future. Although stuff like that isn't a blocker and is quite low priority (in fact, I think the outline looks cool... and would likely not be super easy to implement properly).

**Comment by pouleyKetchoupp** [comment]
@insomniacUNDERSCORElemon I think the AA conflicting with HDR should be considered a separate issue. I've checked a little bit and I haven't found any obvious reason for that to happen. Maybe someone who knows more about rendering will be more lucky, but since it's a GLES3 specific issue and it has a workaround, my guess is that it's going to be addressed only for 4.0 if it's still relevant with Vulkan.

**Comment by pouleyKetchoupp** [comment]
I've just pushed some additional changes to make AA work for Line2D:
- New property `antialiased` as in Polygon2D
- Fixed polygon AA drawing in GLES2 & GLES3 to use indices correctly

**Comment by reduz** [comment]
Seems OK, for 4.x 2D viewports will have MSAA directly, but I guess this is fine as is for 3.x.

**Comment by akien-mga** [comment]
Thanks!

**Comment by insomniacUNDERSCORElemon** [comment]
@RyanJEC , if you're not seeing ANY AA, please try disabling HDR in the project settings (and it likely will not work with an Intel iGPU OR on a web export). 

However I've have seen some polygons that lack AA on certain sides. A simple triangle with 1 side lacking AA seems to be easily reproducible, and it will also happen to a square that has had the polygons (in the UV editor area) set to 2 triangles (rather than 1 quad or no specific polygons set).

Also there seems to be the issue of PolygonAA being applied to the internal sides of triangles... which causes oddities (like new strings on the outside of complex shapes and inside of inverted polygons) and one of the old issues (AA on partially transparent polygons being more opaque) more apparent.

So @pouleyKetchoupp likely needs to take another look at this.

Example image: https://i.imgur.com/9l1ueQR.png

**Comment by pouleyKetchoupp** [comment]
@insomniacUNDERSCORElemon Could you open a specific ticket with these issues, including a repro project? Also it's not very clear to me if they are caused by my changes or were already present before.

**Comment by golddotasksquestions** [comment]
Disabling HDR or setting frame buffer allocation to 2D, works for AA, but does remove Glow at the same time completely. So that's no viable solution for me.

(Godot 3.2. stable, Windows + Nvidia)

**Comment by insomniacUNDERSCORElemon** [comment]
@pouleyKetchoupp there seems to still be an issue with convex shapes and AA, but only when it comes to internal vertices and custom polygons. The AA can still choose the wrong path, going from one internal vertex to another in the shortest path despite the fact that it has to cross other edges to do so.

The simplest test to see this:

- create a sharp V (4 points)
- turn AA on
- add a gradient texture (no assigning needed, this is just to get the uv menu)
- add 3 internal vertices also in a V shape
- add a single custom polygon anywhere 

After doing that you wills see all AA connections, including one that travels outside of where it should. Even if you fully fill up your polygon with custom faces it will still be there.

Seen even in 3.2.3.

Example image: https://i.imgur.com/GnaUPQ2.png

Left is simplest test described. Right is polygon with fully custom faces (was trying to do a test with vertex colors, so internal vertices is needed for that). also note that both polygons have 1 edge with missing AA.

**Comment by pouleyKetchoupp** [comment]
@insomniacUNDERSCORElemon Could you please open an issue with a minimal reproduction project? If we're able to find a simple solution for this case it might get fixed for the next 3.2 maintenance release, otherwise AA for 2D will be handled in a better way in Godot 4.0.

**Pull request merged**
