### PR TITLE
Stop Particles3D to use ressources when not emitting (fixes #19507)

### LINKED ISSUE #19507: Not emitted particles affects performance
**Godot version:**
257d3c3f39fd144d202f112c9cb08a82c174afbc

**OS/device including version:**
nvidia gtx 1060, Ubuntu 18.04

**Issue description:**
I recently tried to find out why I have such performance problems in my game and I have found an interesting thing. Particle 3D node seems to be processing/rendering even if it's not emitting any particles. It can affect performance heavily especially in the scenario when you have a lot of nodes on the screen which are holding some 'visibly rich' particle effects, that are meant to be used rarely (like hit/death effect)

**Steps to reproduce:**
Full:
1. Create new scene, add Particle node and camera
2. Add cylinder as a particle model in `Draw Passes`
3. Add `Particles material` as `process material`
4. Turn off  `Emitting` property
5. Set amount of particles to 100000
6. Run scene and check number of fps
7. Hide Particle node
8. Run scene again and notice a lot higher number of fps

Quick:
1. Download project with reproduction scene
2. Run it, notice number of fps
3. Hide particle node
4.  Run scene again, notice number of fps

**Minimal reproduction project:**
[NonEmittedParticlesPerformance.zip](https://github.com/godotengine/godot/files/2090447/NonEmittedParticlesPerformance.zip)

### PR DESCRIPTION
**Pull request by malbach**
This PR prevents Particles3D to use resources when not emitting (issue #19507).

For the record, this does the same as my last PR #19764, but this time internally.

### CODE REVIEW

**Comment by malbach** [comment]
@akien-mga done (sorry, forgot to branch-away :confounded:)

**Comment by malbach** [comment]
@reduz or anyone else who can answer:
I have made another modification for Particles3D (stop redrawing viewport when inactive) but I prefer to RFC before PR :blush: 
Here's the diff : [godot.diff.txt](https://github.com/godotengine/godot/files/2216570/godot.diff.txt)

What do you think ?

**Comment by vnen** [comment]
> I prefer to RFC before PR

Well, PR *is* RFC. Also much easier to review using GitHub interface.

**Comment by malbach** [comment]
@vnen ok :+1:

**Review by reduz — DISMISSED** [review]

**Comment by malbach** [comment]
Made some changes, in fact I went back to my first modification but at the time I thought it was too simple, and looked for something... "better"
This PR also reverts #19682, as it is not needed anymore

**Comment by malbach** [comment]
Hi,
After seeing [this](https://github.com/godotengine/godot/commit/328679fddd426040a9af4891e937cbadb03371dd) I think my PR isn't needed anymore :)

**Comment by malbach** [comment]
Hi,
After seeing [this](https://github.com/godotengine/godot/commit/328679fddd426040a9af4891e937cbadb03371dd) I think my PR isn't needed anymore :)

**Comment by malbach** [comment]
Hi,
After seeing [this](https://github.com/godotengine/godot/commit/328679fddd426040a9af4891e937cbadb03371dd) I think my PR isn't needed anymore :)

**Pull request closed without merging**
