### PR TITLE
Change order of Visual Script Search and Misc VS UX

### PR DESCRIPTION
**Pull request by fire**
Make using Visual Script take less steps.

Give priority to the Context-based functions.

Merge properties and functions of the same category.

Put functions that belong to the current node type, not it's parent first.

Previously:

* vs nodes
* properties
* methods

Now:

* properties
* methods
* vs nodes

Also, reset the scroll to the first item / category.

### CODE REVIEW

**Comment by fire** [comment]
The methods isn't reversed yet.

**Comment by turtletooth** [comment]
This is awesome.  I was looking at doing some improvements to search as well.  I was thinking of trying to also search based on the item description of some keywords.  What are your thoughts?

**Comment by YeldhamDev** [comment]
> Also, reset the scroll to the first item / category.

To be honest, I think it would be better if it worked like the documentation search: not resetting the text each time it's closed, and remembering where the scroll position was.

**Comment by fire** [comment]
Working on merging functions and variables:

**Comment by fire** [comment]
Updated:

Please check the various uses of the generic search.

* new function
* shortcut key
* drag from value
* drag from sequence
* create node

**Comment by fire** [comment]
> 
> 
> > Also, reset the scroll to the first item / category.
> 
> To be honest, I think it would be better if it worked like the documentation search: not resetting the text each time it's closed, and remembering where the scroll position was.

Sometimes one opens the search again and didn't realize to scroll to the start. How do you resolve that problem?

**Comment by fire** [comment]
> 
> 
> This is awesome. I was looking at doing some improvements to search as well. I was thinking of trying to also search based on the item description of some keywords. What are your thoughts?

I thought it already did that... Uh

**Comment by fire** [comment]
Noticed two problems:

* Variables output Obj and not the variable output
* Obj problem. Should it create a typecast node if it's an obj?

**Comment by YeldhamDev** [comment]
@fire I mean not resetting the search once the dialog closes. In the doc search, once the dialog is reopened, it restores the current search before it was closed.

**Comment by fire** [comment]
@YeldhamDev That is the current behaviour.. It was noted to be confusing from one person.

**Comment by YeldhamDev** [comment]
No it isn't:
Peek 26-04-2019 13-59

**Comment by fire** [comment]
Try not triggering the search.

**Comment by YeldhamDev** [comment]
Yes, it remembers the scroll position, but not the search.

**Comment by fire** [comment]
My guess is that the document help is never closed. So the state is never reset.

**Comment by YeldhamDev** [comment]
It is, it just keeps the current search and restores it once reopened.

**Comment by fire** [comment]
Will look into it later.

**Comment by fire** [comment]
@YeldhamDev Can you make an issue regarding remembering the scroll position, but not the search?

**Review by Chaosus — APPROVED** [review]
Make sense I think..

**Comment by fire** [comment]
Testing the various function

* Create a function
Visual nodes are still there. This is a bug. Will put a bugfix.
* Create a sequence
Looks good
* Pull from a output port
Looks good
* Generic search
Looks good.

**Comment by fire** [comment]
Fixed a bug in the generic visual search. Now it knows what type the script is and is able to give the properties and the methods on control - f. This was the original intention.

T7rJV2V

**Comment by fire** [comment]
There's another bug with generic's search's properties not automatically having a self node, but that's for another pull request.

**Comment by akien-mga** [comment]
Thanks!

**Comment by Jummit** [comment]
This is currently not a perfect system, as the nodes added by the search are instance calls and do not work without a `self` node. This could be easily fixed by making the nodes a self call.

Secondly, I think these search features should also be added to the search when dragging out from a sequence port, which makes the workflow faster, as you don't have to hit ctrl+f and connect the node manually.

Should I open a separate issue for this?

**Comment by fire** [comment]
Go ahead.

**Comment by Jummit** [comment]
> Go ahead.

#28614, but the fix being that the function type is a self call.

**Pull request merged**
