### PR TITLE
Update list of `clang-tidy` checks

### PR DESCRIPTION
**Pull request by sondredl**

### CODE REVIEW

**Comment by AThousandShips** [comment]
I don't think it makes sense to make the list *exclude* what we don't want instead of including what we want, it would break with any newly added check we don't want, please elaborate on why this would be useful

**Comment by sondredl** [comment]
what new checks are  added and how do they break by adding this change?

It is useful to show any and all checks that currently need to be ignored to have the code pass. This approach makes it much easier to improve static analysis going forward, simply by deleting checks to be removed.

**Comment by AThousandShips** [comment]
By updating our version of clang-tidy

But the question still stands:
Why not just explicitly list the checks we want, there aren't *that* many checks that it's impossible to list the ones we want, and listing them explicitly helps knowing what we do want to check

Clarity is always good, so other than some form of convenience, what is the benefit of including everything and then excluding some?

Compared to the negatives:
* Updating to a new version requires checking what new checks have been added and if we need to exclude them
* Makes you have to go look at the list of checks online to know what are run

**Comment by sondredl** [comment]
fair point. closing the pr

**Pull request closed without merging**
