### PR TITLE
fixes issue #1693 winmain and main unicode

### PR DESCRIPTION
**Pull request by SuperUserNameMan**
makes WinMain() and main() accepts unicode characters into arguments

fixes issue #1693

### CODE REVIEW

**Comment by reduz** [comment]
This fix is great! Also sorry to ask, did you test this? :) I'm a little afraid to merge it being the case that i'm currently in Linux and can't test

**Comment by SuperUserNameMan** [comment]
Oh sorry, I did not see your message here.

So the answer is yes, I tested it in a french version of Windows 8.1, in which I created a user account with a username written in cyrillic alphabet : "Українська"

I tested it several way :
1- from inside the Українська account.
2- from my usual account using this path : `C:\Users\Українська\Desktop\godot\godot.windows.tools.exe`
3- from my usual account and usual path by importing a project from this path : `C:\Users\Українська\Desktop\godot\godot-test`

Indeed, only more tests with different versions of windows and different default code-pages will tell us if this fix is as great as you expected .... !

**Comment by SuperUserNameMan** [comment]
also, I forgot to mention that I only tried to compile using VC2010, and I have no clue if it is still compatible with Wine.

**Comment by reduz** [comment]
Cool, Punto tested it yesterday and it all seemed to work fine, so he
merged it

**Pull request merged**
