### PR TITLE
spirv-reflect: Update to latest commit

### PR DESCRIPTION
**Pull request by RandomShaper**
I did the update commit since it looked that we needed some of the new features for something. It turned out it was not necessary, but since I already did it, let's use it.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
Seems fine to me. But do we need to increment our shader version each time we update spir-v reflect? If not, then this should be fine to merge

**Review by akien-mga — APPROVED** [review]
Looks good to me, pending discussion re: shader version.

**Comment by RandomShaper** [comment]
Shader cache key now includes the commit hash, so there's no need for manual version bump.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
