### PR TITLE
Added Comment node to Visual Shaders

### PR DESCRIPTION
**Pull request by Chaosus**
I know this feature is long-awaited and desired.
comment

### CODE REVIEW

**Comment by pycbouh** [comment]
Shouldn't the description use more spacious, multiline TextEdit?

**Comment by Chaosus** [comment]
> Shouldn't the description use more spacious, multiline TextEdit?

Yeah, thank you, fixed this to be like:
comment2

**Comment by LightningAA** [comment]
A suggestion, I don't know if this is even possible with godot's GraphNodes or if this has already been discussed, but I think it'd be more intuitive if instead of having to right click on it and use set title or set comment, if the title and comment were just a TextEdit and a multiline TextEdit that you could just left click on to edit.

**Comment by akien-mga** [comment]
> A suggestion, I don't know if this is even possible with godot's GraphNodes or if this has already been discussed, but I think it'd be more intuitive if instead of having to right click on it and use set title or set comment, if the title and comment were just a LineEdit and a TextEdit that you could just left click on to edit.

That would be nice indeed if it's not too complex to implement with the current system. Maybe it could just be a GraphNode with a text field like the Expression node?

A potential drawback is that the text field would always be editable, while it might be useful to have separate edit and read-only mode, to prevent accidental edition / focus grab when clicking around? There could maybe be a checkbox to turn the TextEdit to read-only and avoid accidental edition? Just throwing some ideas.

I guess with this approach adding an actual custom title to the comment box might not be well supported, but a side question is whether that part of the feature is really useful? Code comments rarely start with a title either, though the use case here might be a bit different.

I'm not against the current implementation though, just throwing some ideas. Like always we should find the right tradeoff between ease of implementation/maintainability and user experience (so we shouldn't need to add e.g. 500 lines of code to support being able to use a text edit directly in the GraphNode).

**Comment by Ansraer** [comment]
I have another suggestion: what if we make the comment not a node but a semitransparent colored area instead. That would allow us to place nodes on top of it and visually group them together.

**Comment by LightningAA** [comment]
> I have another suggestion: what if we make the comment not a node but a semitransparent colored area instead. That would allow us to place nodes on top of it and visually group them together.

Where would the comment go? On top like this?

Mockup

**Comment by Riteo** [comment]
> I have another suggestion: what if we make the comment not a node but a semitransparent colored area instead. That would allow us to place nodes on top of it and visually group them together.

Oh I thought it was supposed to work like that. Does the current proposed implementation just like add a text box in node space?

**Comment by pycbouh** [comment]
> I have another suggestion: what if we make the comment not a node but a semitransparent colored area instead. That would allow us to place nodes on top of it and visually group them together.

That's exactly what a comment node is though. It's a `GraphNode` with the `comment` flag turned on, and it is displayed behind other nodes and is used for visual grouping. It's an existing functionality of `GraphEdit`.

**Comment by Riteo** [comment]
> > I have another suggestion: what if we make the comment not a node but a semitransparent colored area instead. That would allow us to place nodes on top of it and visually group them together.
> 
> That's exactly what a comment node is though. It's a `GraphNode` with the `comment` flag turned on, and it is displayed behind other nodes and is used for visual grouping. It's an existing functionality of `GraphEdit`.

So It was supposed to work like that, nice :D

**Comment by pycbouh** [comment]
Yes, but looking at the code now, maybe this PR doesn't use existing functionality, but reimplements it instead. So I'm not sure anymore.

**Comment by Chaosus** [comment]
@pycbouh  
image

**Comment by pycbouh** [comment]
All is good then, this should indeed already act exactly like @Ansraer wanted it to.

**Comment by Riteo** [comment]
> All is good then, this should indeed already act exactly like @Ansraer wanted it to.

Yeah I just tested it locally, it works exactly like that.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
