### PR TITLE
Add a separate hue gradient for OKHSL mode

### LINKED ISSUE #67536: The default HSV slider is wrong for OKHSL mode
### Godot version

4.0 0d28820

### System information

Windows 10 x64

### Issue description

image
You can see 3 different colors here. S slider is being fixed by #67534, but H slider is completely wrong. It needs a separate texture.

### Steps to reproduce

1. Open any ColorPicker
2. Change color mode to OKHSL

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #67536
image

I generated the gradient with this code:
```GDScript
func _run() -> void:
	var strings: PackedStringArray
	
	for i in 15:
		strings.append('<stop offset="%s" stop-color="#%s"/>' % [i / 14.0, Color.from_ok_hsl(i * 1.0 / 14, 1, 0.5).to_html(false)])
	
	print("".join(strings))
```

It's not perfect, but it's more accurate.

### CODE REVIEW

**Comment by fire** [comment]
Do you think its possible to generate a gradient by code?

**Comment by KoBeWi** [comment]
Yes, we could use a GradientTexture2D. But none of the theme icons are like that, so I went with SVG.

**Comment by fire** [comment]
I have no opinion on svg vs gradient.

**Comment by KoBeWi** [comment]
Rebased. I added a second commit that changes both textures to generated GradientTexture2D and makes them horizontal.

**Review by fire — APPROVED** [review]

**Pull request merged**
