### PR TITLE
Properly handle wireframe mode in RendererRD pipeline cache

### LINKED ISSUE #76237: Objects that use a shader with render_mode wireframe will cause memory to increase continuously!!
### Godot version

4.0.2

### System information

Windows 10

### Issue description

I have a meshinstance3d with a shader attached, and this is inside a subviewport. ( I instanced a bunch to make the memory rise faster, for testing purposes ).
The shader uses render_mode wireframe.
Whenever the object is onscreen, the memory will increase continuously! If the object goes offscreen, it will stop.
If I remove render_mode wireframe from the shader, the memory won't increase.
If I set debug_mode to wireframe on the subviewport, the memory won't increase.

Edit: I originally thought a subviewport was required, but it isn't. It happens even when there are no subviewports being used!

### Steps to reproduce

Open the attached project, and run the test.tscn
Watch as your memory continues to go up.
It stops if you either remove render_mode wireframe from the shader, or if you set the subviewport debug_mode to wireframe.
It also stops if the object isn't onscreen.

### Minimal reproduction project

[subViewportWireframeBug.zip](https://github.com/godotengine/godot/files/11267138/subViewportWireframeBug.zip)

### PR DESCRIPTION
**Pull request by prominentdetail**
makes wireframe get cached properly so that it doesn't keep being recreated.
Bugsquad edit: fixes #76237

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks for opening a pull request!

Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) (`git commit --amend`). This way, people reading the Git log can easily figure out what's going on :slightly_smiling_face:

**Comment by prominentdetail** [comment]
> Thanks for opening a pull request!
> 
> Please [amend the commit to use a human-readable commit message](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind) (`git commit --amend`). This way, people reading the Git log can easily figure out what's going on 🙂

Not sure where to type that.. I'm trying to figure it out.

**Review by clayjohn — COMMENTED** [review]
The code changes look great! The final step before merging is to squash all the commits together so that the whole PR only contains 1 commit with all your changes. We like to merge one commit at a time to keep the git history clean and navigable. 

If you don't know how to do that, we have a helpful tutorial in the official documentation https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase

**Comment by prominentdetail** [comment]
ok, I think I squashed them. I never did that before, so hope I got it right.

**Review by clayjohn — APPROVED** [review]
Looks good now!

**Comment by akien-mga** [comment]
Sorry for yet another commit tweak request, but could you make the commit message more explicit? "cache wireframe" is a bit short and doesn't really explain what is being done here IMO. Could use the same as I added as PR title, if my understanding and description of the bug is accurate.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by prominentdetail** [comment]
Thanks! :)

**Pull request merged**
