### PR TITLE
Clamp Volumetric Fog Length property to prevent rendering issues

### PR DESCRIPTION
**Pull request by Calinou**
This creates visual artifacts similar to what's seen in https://github.com/godotengine/godot/issues/78500.

A length of 0 units doesn't make sense anyway.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]

**Comment by Calinou** [comment]
> cool also it would be cool to also clamp density or have a warning to avoid some issues that causes black and white square on the screen.

I didn't encounter similar issues with high density, even if I set **Density** to 200 while having **Length** set to `0.01`. Could you point to an issue with **Density** specifically?

**Review by aaronfranke — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by Saul2022** [comment]
> I didn't encounter similar issues with high density, even if I set **Density** to 200 while having **Length** set to `0.01`. Could you link to an issue with **Density** specifically?

After testing some bit i was not able to reproduce that white and black combining low density  with 0 lenght, and the black screen is fixed by this pr, so i guess it more or less fixed, sorry for my confussion.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
