### PR TITLE
Keep scaling even when redrawing a Container

### PR DESCRIPTION
**Pull request by xsellier**
Set a label as a child of a container, change the label scale to (0.5, 0.5), then change the content of the label, and its scale is going to be reset to (1, 1).

### CODE REVIEW

**Comment by xsellier** [comment]
The `fit_child_in_rect` function changes the scaling to (1, 1) for all children in the Container, to calculate the correct size for each child.

This function is called as soon as you change the content of a Label (for example). In other words, if we scale a Container to (0.5, 0.5) and then edit the contents of the Label, then the Container scaling returns to (1, 1) if this container is also the child of a Container.

This case occurs when PanelContainers are used in BoxContainers (for example).

This PR fixes this issue, but I wonder if it does not create a new one.

In my example, we have a Label. Let's assume that its scaling is at (0.5, 0.5), then we call the function `fit_child_in_rect`. Then the size of the Label will change to adapt to the size of the Container. But if we change the scaling of the Label to (1, 1), then the size of the Label will be multiplied by two, and therefore the Container will have to be enlarged.

I wonder if this behavior sounds like a bug to you?

**Comment by xsellier** [comment]
Found out a better way to do it. It should solve every concern I raised.

**Comment by groud** [comment]
I don't really know if this is the expected behavior. 
To be honest containers never meant to be used with scaled controls, so it is kind of hard to know what is the expected behavior. However I guess the situation is this PR is better than the current one, so I believe it could be merged.

**Comment by akien-mga** [comment]
I guess it make sense to respect the scale of controls in containers, even though I don't see much use case for actually scaling controls...

**Comment by xsellier** [comment]
This PR is now ready to be merged.
I wonder if you want me to manage also the rotation for every child. Because right now it is just reset the rotation angle to 0. (it has to be done in another PR).

**Pull request closed without merging**
