### PR TITLE
Disabled trim and normalize as default for wav import

### LINKED ISSUE #28728: Trimming and normalizing audio as default during wave import is a mistake.
**Godot version and OS**:
Godot 3.1.1-stable  64-bit,  Manjaro Linux v18.0.4-stable
**Issue** :
It seams that Godot, when importing waveform audio file format trims and normalizes the sound in the process. That should not be default behavior. Sounds should be imported as they are, unless normalize and trim options are checked in, but in Godot 3.1.1 there is no such option.
I remember in Godot 1.0/2.0 import audio dialog let users to check in/out the trim and normalize.

### PR DESCRIPTION
**Pull request by Keetz**
Fixes #28728

Note that the issue is still labelled as Discussion, I just thought I would do the small changes so it can be merged or discarded as soon as the discussion comes to an end.

### CODE REVIEW

**Comment by asheraryam** [comment]
Highly support this change, audio files should not be messed with without an explicit decision to do so.

**Comment by Calinou** [comment]
Judging by #24177, it seems this shouldn't break existing projects after all.

**Comment by akien-mga** [comment]
@reduz agrees with the change, and it makes sense to me too that those options are opt-in, so let's merge.

**Comment by akien-mga** [comment]
Thanks!

@Calinou Should go in the changelog of course.

**Pull request merged**
