### PR TITLE
ustring: Replace macros with inline functions.

### PR DESCRIPTION
**Pull request by AnilBK**
Removed macros from ustring and replace with inline functions. Use the functions where possible.
-Add new inline function to check if a character is lowercase or uppercase.
-Remove unused upper case macro.

_Experimental PR; Can be closed if unnecessary. :)_

### CODE REVIEW

**Comment by LightningAA** [comment]
I think even better would be to make these inline functions instead, see https://github.com/godotengine/godot-proposals/issues/2093#issuecomment-757352474

**Comment by AnilBK** [comment]
> 
> 
> I think even better would be to make these inline functions instead, see [godotengine/godot-proposals#2093 (comment)](https://github.com/godotengine/godot-proposals/issues/2093#issuecomment-757352474)

Redid the PR removing the macros.
With the new added functions,not sure if it's worth.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
