### PR TITLE
Change android orientations from sensor to user

### PR DESCRIPTION
**Pull request by HEAVYPOLY**
Replaces sensor orientations with user orientations for Android.  User functions the same as Sensor except it also respects user's rotation lock setting.

@pouleyKetchoupp and @m4gr3d
Thanks for the help on my first PR!

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
Looks good to me!

@m4gr3d In #39266 comments we were talking about adding more orientation options to allow sensor without taking user lock into account, but in the end it seems like too many extra options to add just for Android, and it's probably ok to start with making things consistent between Android and iOS.

After giving more thoughts to it, if there's a demand for these cases I would rather add a specific Android export boolean option to ignore user lock for orientation.

**Review by m4gr3d — CHANGES_REQUESTED** [review]
@HEAVYPOLY Looks good!
As mentioned in https://github.com/godotengine/godot/issues/39266, can you also add a check to only update the orientation when the new value differs from the current orientation.

**Comment by m4gr3d** [comment]
@HEAVYPOLY Ping on this PR!

**Comment by HEAVYPOLY** [comment]
@m4gr3d is this ok?

I am very new to C#, not confident yet.
```

	public void setScreenOrientation(int p_orientation) {
		Log.v("Godot", "ORIENTATION " + p_orientation ,"  ", activity.getRequestedOrientation());
		if (p_orientation == activity.getRequestedOrientation()) {
			return;
		}

		switch (p_orientation) {
			case SCREEN_LANDSCAPE: {
				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
			} break;
			case SCREEN_PORTRAIT: {
				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
			} break;
			case SCREEN_REVERSE_LANDSCAPE: {
				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE);
			} break;
			case SCREEN_REVERSE_PORTRAIT: {
				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_PORTRAIT);
			} break;
			case SCREEN_SENSOR_LANDSCAPE: {
				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_USER_LANDSCAPE);
			} break;
			case SCREEN_SENSOR_PORTRAIT: {
				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_USER_PORTRAIT);
			} break;
			case SCREEN_SENSOR: {
				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_FULL_USER);
			} break;
		}
	} 
```

**Comment by m4gr3d** [comment]
> @m4gr3d is this ok?
> 
> I am very new to C++/java, not confident yet.
> 
> ```
> 
> 	public void setScreenOrientation(int p_orientation) {
> 		Log.v("Godot", "ORIENTATION " + p_orientation ,"  ", activity.getRequestedOrientation());
> 		if (p_orientation == activity.getRequestedOrientation()) {
> 			return;
> 		}
> 
> 		switch (p_orientation) {
> 			case SCREEN_LANDSCAPE: {
> 				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
> 			} break;
> 			case SCREEN_PORTRAIT: {
> 				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
> 			} break;
> 			case SCREEN_REVERSE_LANDSCAPE: {
> 				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE);
> 			} break;
> 			case SCREEN_REVERSE_PORTRAIT: {
> 				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_PORTRAIT);
> 			} break;
> 			case SCREEN_SENSOR_LANDSCAPE: {
> 				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_USER_LANDSCAPE);
> 			} break;
> 			case SCREEN_SENSOR_PORTRAIT: {
> 				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_USER_PORTRAIT);
> 			} break;
> 			case SCREEN_SENSOR: {
> 				activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_FULL_USER);
> 			} break;
> 		}
> 	} 
> ```

Actually nevermind, the change looks good as is!

I forgot to notice that there was a slight translation from the given `p_orientation` value to what we pass to `activity.setRequestedOrientation(...)` so trying to compare beforehand would make the logic more complex than it needs to be.

**Review by m4gr3d — APPROVED** [review]
Looks good as is!

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by HEAVYPOLY** [comment]
Yay! Thanks for the help guys :D

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
