### PR TITLE
Update thorvg to 0.8.4

### LINKED ISSUE #75491: Update Thorvg to v0.8.4 with bugfixes to SVG
### Godot version

4.0.1 preview, doubles?

### System information

Windows 11, Nvidia 3000

### Issue description

Thorvg updated to a version that solves some of our bugs https://github.com/thorvg/thorvg/releases/tag/v0.8.4

We need to revisit to go through our list to see if they are fixed.

https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+thorvg

### Steps to reproduce

1. Load godot engine
2. Run svg
3. See if the new thorvg fixed bugs

### Minimal reproduction project

See https://github.com/godotengine/godot/issues/72478 for the mrp

### PR DESCRIPTION
**Pull request by RedworkDE**
- Fixes https://github.com/godotengine/godot/issues/75491
- https://github.com/godotengine/godot/issues/65083
  Not fixed, but the rendering is improved:
  - The outside border works now (on the original svg that has it)
  - Now the images are just significantly darker than the pngs, but notably chrome also renders the svgs darker than the png, tho not as dark as godot does.
  - Also the change is unrelated to this update in particular
- https://github.com/godotengine/godot/issues/72478 (that is updated was apparently supposed to help with)
  Nothing has changed in regard to this
  The change related to this (where I am not exactly sure what exactly it even fixed) is revered in the release (but not on master)
- All the other issues that mention thorvg have not changed since they were opened
- I gave the thorvg master a try as well, but that doesn't seem to help much either

cc @fire [^1]

[^1]: does mentioning someone in an edit even work on github?

### CODE REVIEW

**Review by fire — COMMENTED** [review]
# Spot check on the Godot outlined logo

image

@mgrudzinska I have attached a svg of the godot logo outlined.

## Raw SVG

logo_outlined

## Thorvg viewer

image

## Firefox

image

## 65083  mrp
I did a spot check using https://github.com/godotengine/godot/issues/65083 's mrp.


### Result in 4.0

image

### Result as of the pr.

image

## Summary

1. Need to check if the error is a regression from 4.0.
2. If it is, will need to push to the next release of thorvg
3. If it's not, the pr looks good to go.

**Comment by mgrudzinska** [comment]
@fire It's not a regression. the reason why your logo looks bad now, is the ```paint-order``` attribute, that is not supported in ThorVG (https://github.com/thorvg/thorvg/issues/1340). your current logo on master doesn't use this attrib and it renders correctly

**Review by fire — APPROVED** [review]
The different result was not because of a regression.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.3.

**Pull request merged**
