### PR TITLE
Remove signal _compat in favor of Callable

### PR DESCRIPTION
**Pull request by nathanfranke**
I am not sure whether we will want this to be merged any time soon since it may break compatibility for many other Pull Requests. We should use it as a reference for the future.

Java Program to remove all `_compat`:

This code is written by me and is public domain
```java
public static final String GODOT_PATH = "/home/nathanfranke/workspace/godot"; // Please replace with your Godot source path

public static void main(String[] args) throws IOException {
	
	Pattern pattern = Pattern.compile("_compat\\((?<p1>.+?),\\s+(?<callable>.+?, .+?)(?<param>, .+)*\\)");
	
	Files.walk(new File(GODOT_PATH).toPath()).forEach(path -> {
		
		if(!path.toString().endsWith(".cpp") && !path.toString().endsWith(".h")) return;
		
		try {
			String data = new String(Files.readAllBytes(path));
			
			Matcher matcher = pattern.matcher(data);
			
			StringBuffer buffer = new StringBuffer(data.length());
			while(matcher.find()) {
				String param = matcher.group("param");
				String newCall = "(" + matcher.group("p1") + ", Callable(" + matcher.group("callable") + ")" + (param == null ? "" : param) + ")";
				System.out.println(newCall);
				matcher.appendReplacement(buffer, newCall.replace("$", "\\$"));
			}
			matcher.appendTail(buffer);
			
			Files.write(path, buffer.toString().getBytes());
		} catch (IOException e) {
			e.printStackTrace();
		}
		
	});
	
}
```

Manual modifications made:
`core/object.h`
`core/object.cpp`
`modules/mono/signal_awaiter_utils.cpp`

### CODE REVIEW

**Comment by akien-mga** [comment]
The idea is to use `callable_mp`, see #36426.

**Comment by nathanwfranke** [comment]
@akien-mga In that case should I close this?

**Comment by nathanwfranke** [comment]
Looks like that's a yes

**Comment by akien-mga** [comment]
Yeah, this is just a cosmetic changes while #36426 is a functional change (which also breaks the engine, but that's another problem :P).

**Pull request closed without merging**
