### PR TITLE
[2.1] Enable autoload in editor

### PR DESCRIPTION
**Pull request by allkhor**
- Tool scripts will be executed and can be accessed by plugins.
- Other script languages can implement add/remove_named_global_constant
to make use of this functionality.
Thanks @vnen for the great work.
(cherry picked from commits decf178 and 55b4b30 and ed3776c)

### CODE REVIEW

**Comment by vnen** [comment]
Not sure if this is wanted in 2.1, but this should include the changes in #21252, otherwise it might cause issues.

**Comment by allkhor** [comment]
Thanks, now include ed3776c.

**Comment by akien-mga** [comment]
At this stage I'd prefer not to add such big features to the old 2.1 stable branch, as it can induce regressions (either some that were also in master and have been fixed since but not included here, or new ones specific to 2.1 as this code was never tested there).

We're about to release 3.1 with GLES2 support, and at this point the 2.1 branch will only receive support for critical bug fixes and platform compatibility. I don't think it's the right time to add such a major new feature.

**Comment by allkhor** [comment]
I'm agree with this. I will close this PR, if someone want this feature in 2.1, i don't delete my branch.

**Pull request closed without merging**
