### PR TITLE
Made node names in signal methods be lower case

### PR DESCRIPTION
**Pull request by YeldhamDev**

### CODE REVIEW

**Comment by TheYokai** [comment]
This is to keep consistency with function naming conventions, yes? Since nodes are case sensitive in the scene tree hierarchy, it may cause some confusion if you want to hook two nodes of the same name into the same class with automatic methods (I.E. Node vs node will produce the same auto-generated function.)

I'm in favor of this change though, just pointing out it will create some overlap cases (that already existed before anyway, when dealing with child-of relationships.)

**Comment by YeldhamDev** [comment]
@TheYokai Yes, is for convention sake. And I don't think that overlapping will be much of a problem, as I don't see why somebody would have nodes with the same name but with different casing.

**Comment by akien-mga** [comment]
I'm not sure about this change, I think it's good that the name injected in the method prototype is the exact name of your node in the scene tree, it makes things easy to identify. If you prefer it lowercase, it's easy to fix manually, but personally I like to keep it as created *or* to set a completely custom method name.

**Comment by YeldhamDev** [comment]
@akien-mga I don't see how the name being lower cased makes it any harder to identify anything. It also incentivizes respecting the [style guide](https://godot.readthedocs.io/en/3.0/getting_started/scripting/gdscript/gdscript_styleguide.html#functions-and-variables), which help create good coding habits.

**Comment by cbscribe** [comment]
The style guide calls for node names to use PascalCase. As it stands, you can customize the connecting function, but if you're letting the engine name the function automatically it should match the node's name.

**Comment by YeldhamDev** [comment]
@cbscribe Yes, node and class names, not functions. And I don't think that the process being automatic is a good justification.

**Comment by Zylann** [comment]
I disagree with this change. I know functions are usually lower case, but I name my nodes uppercase and I want such signal handlers to reflect that exactly, which also makes them stand out as "functions you should not be calling from code". When I want to connect an existing function then I edit the handler name anyways.
If your convention is different I would at least suggest an option?

**Comment by akien-mga** [comment]
I agree with @Zylann, and I don't think it's worth adding an option nobody would ever notice (and thus, use) in the project settings. Keeping the identifier unchanged is much better IMO (especially since if we wanted to do things properly for this feature, it should use `camelcase_to_underscore`, not `lowercase`, we can add more inconsistencies).

**Pull request closed without merging**
