### PR TITLE
Add support for set graphNode's title font color

### LINKED ISSUE #82085: There was no way to set GraphNode's title font color
### Godot version

v4.2.dev5.official [e3e2528ba]

### System information

Windows 10, 64bit

### Issue description

There was no way to set GraphNode's title font color

### Steps to reproduce

/

### Minimal reproduction project

/

### PR DESCRIPTION
**Pull request by SaNeOr**
Close #82085

### CODE REVIEW

**Comment by AThousandShips** [comment]
Did you mean to close this?

**Comment by AThousandShips** [comment]
Superseded by:
* #82129

**Comment by SaNeOr** [comment]
> Did you mean to close this?

I resubmitted once, maybe.... I can do something more correct?

**Comment by AThousandShips** [comment]
You opened a new PR and closes this one manually, unsure why you did that

**Comment by SaNeOr** [comment]
> You opened a new PR and closes this one manually, unsure why you did that

I don’t know how to make the remote squash submit twice, or should I just continue to submit one?

**Comment by AThousandShips** [comment]
Oh, just follow the [instructions](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html), do *not* open new PRs every time you make a new push

**Comment by SaNeOr** [comment]
> Oh, just follow the [instructions](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html), do _not_ open new PRs every time you make a new push

Oh, this is helpful!

**Pull request closed without merging**
