### PR TITLE
Escape `+/- key` in constant descriptions to avoid issues when generating RST

### PR DESCRIPTION
**Pull request by transistasis**
Hey all, this is my first pull request here.

## Problem Description

This PR fixes the problems raised in [#8127](https://github.com/godotengine/godot-docs/issues/8127). The issues stem from the _+_ and _-_ characters used in the `KEY_PLUS` and `KEY_MINUS` enumeration descriptions not being escaped after the _make_rst.py_ script is run. This results in the _+_ and _-_ characters being interpreted as bullet lists, rather than characters, as can be seen [here](https://docs.godotengine.org/en/4.1/classes/class_%40globalscope.html#enum-globalscope-key).

## Problem Solution

The cleanest solution that I can think of is to add additional escape logic to the `escape_rst` method in _make_rst.py_ for the _+_ and _-_ characters by searching for the strings `"+ key"` and `"- key"`. This will allow the `KEY_PLUS` and `KEY_MINUS` enumeration descriptions to display correctly after generating a _.rst_ file from _@GlobalScope.xml_. This solution will be transparent to all of the other _.xml_ files in the project.

I looked at trying to escape these characters in the same way that the _*_ is handled, but found that this can break bullet lists in _.rst_ files generated from other _.xml_ files, such as _EditorCommandPalatte.xml_. As a result, the proposed solution is the cleanest way that I can think of to fix the problem.

## Results
Upon diffing the generated `_build/rst` folders before and after applying the fix, only `class_@globalscope.rst` is modified:
image

 
Please let me know if someone has a cleaner solution!

### CODE REVIEW

**Comment by AsperTheDog** [comment]
It is also possible to fix this by editing [doc/classes/@GlobalScope.xml](https://github.com/godotengine/godot/blob/master/doc/classes/%40GlobalScope.xml) in the godot repo. Specifically by subsituting the `-` in [line 2171](https://github.com/godotengine/godot/blob/a2f90d565ad29edcb3bdab77bc7df51cdde8514a/doc/classes/%40GlobalScope.xml#L2171) (description for KEY_MINUS) with `&#45;` and the `+` in [line 2165](https://github.com/godotengine/godot/blob/a2f90d565ad29edcb3bdab77bc7df51cdde8514a/doc/classes/%40GlobalScope.xml#L2165) (description definition for KEY_PLUS) with `&#43;`

This is how keys like `<` in [line 2216](https://github.com/godotengine/godot/blob/a2f90d565ad29edcb3bdab77bc7df51cdde8514a/doc/classes/%40GlobalScope.xml#L2216) (description definition for KEY_LESS) and `>` in [line 2222](https://github.com/godotengine/godot/blob/a2f90d565ad29edcb3bdab77bc7df51cdde8514a/doc/classes/%40GlobalScope.xml#L2222) (description definition for KEY_GREATER) are handled right now.

I personally think this is cleaner since it does not add any additional code and it mimics the approach made in other parts of the xml file

**Comment by transistasis** [comment]
@AsperTheDog I gave it a shot, but I didn't end up being successful. I did the following tests without any of the `make_rst.py` changes included in this PR:

1. Try to brute force the escape sequence for `KEY_PLUS` by using `&#92;&#43;` or `\&#43;` in _@GlobalScope.xml_
2. Try to handle `KEY_MINUS` the same way that `KEY_LESS` is handled by using `&#45;` in _@GlobalScope.xml_

The first approach didn't work since the \ character is also escaped in the `escape_rst` method of _make_rst.py_, leading to an output of `\\+ key.` being generated in the associated _.rst_ file.

The second approach didn't work since it will generate an unescaped _-_ character in the generated _.rst_ file, leading to an output of `- key.`, which is what is currently happening in _master_. The use of `&lt;` for `KEY_LESS` works fine since this character doesn't need to be escaped in the generated _.rst_ file.

I've included a screenshot for completeness:
image

Do you know if I'm missing something? To your point, I would prefer not to add any additional code to _make_rst.py_, so I'd really like this alternative approach to work. 🙏

**Comment by AsperTheDog** [comment]
@transistasis it seems like it does not work as I expected. My bad. This issue is only present in the online docs, and not in the local docs of the engine. To test it looked as it should I compiled the engine and ran it with --doctool. Since the docs appeared to be correct I assumed it was working correctly.

So the approach I mention doesn't work.

**Comment by transistasis** [comment]
@AsperTheDog It's all good, thanks for taking another look at it! 

If you have any other ideas, let me know and I'll try them out. 🤘😼

**Comment by YuriSizov** [comment]
NumPad keys' descriptions avoid this by starting with a word.

> Add (+) key on the numeric keypad.

I think this can be done here as well, for all related descriptions.

**Pull request closed without merging**
