### PR TITLE
RichTextLabel: Added get_visible_line_count method

### PR DESCRIPTION
**Pull request by ghost**
Also exposed get_line_count to GDScript.

The inner-workings of RichTextLabel is quite involved, and the simpled way of counting visible lines I could think of was this: for each line, increment visible line counter whenever there is something visible on that line. I made use of the existing visibility tests during PROCESS_DRAW, so a proper counting will happen only during draw cycle. But I guess this is OK, since when the widget is non-visible, visible line count is zero anyway.

### CODE REVIEW

**Comment by tagcup** [comment]
Should fix #3854

**Comment by tagcup** [comment]
I found a problem with this implementation, so can we hold this off for the moment?

The problem is in `RichTextLabel::_notification`; essentially, the calculated `from_line` doesn't take line breaks due to word wraps. This is actually an existing bug, because widgets shouldn't draw regions which are not supposed to be visible anyway. I need to find a workaround for this, probably need to come up with a different way of counting visible lines.

**Comment by tagcup** [comment]
A related question: shouldn't `scroll_to_line` take word-wrapping into account?

**Comment by tagcup** [comment]
PTAL.

**Comment by tagcup** [comment]
Still not functioning properly. I hope someone familiar with the RichTextLabel code can take a look.

**Comment by tagcup** [comment]
It's puzzling but after disregarding font ascent in visibility test, it seems to be working correctly.

**Comment by tagcup** [comment]
This PR feels a bit hacky, I'm hoping someone more familiar with the intricate details of RichTextLabel can suggest doing things better in various places.

**Comment by akien-mga** [comment]
It would be nice to have @reduz's opinion on this. @tagcup mentioned the implementation was a bit hacky, so it would be good to have some advice for a better implementation if possible :)

**Comment by reduz** [comment]
Sorry, somehow missed this. Seems fine, RichTextLabel is a big hack that becomes a pain to maintain, so only hacks can be added over it.

**Comment by akien-mga** [comment]
So I guess, good to merge after a rebase if it still works as intended, and we should start thinking about completely refactoring RichTextLabel in a future release.

**Comment by tagcup** [comment]
Ah, cool. I'll revise it next week. I should at least add some comments to clarify the hack after some testing.

**Comment by akien-mga** [comment]
Bump :)

**Comment by reduz** [comment]
heh we should ask Github to develop some kind of AI to detect that someone mentions that he/she will do something in a certain amount of time ( then the issue becomes forgotten)

**Comment by tagcup** [comment]
Ah apologies, totally forgot about this one! I'll rebase it in a couple of days

Yeah, I only have a few PRs/issues but an integrated reminder system be a huge help for core devs

**Comment by akien-mga** [comment]
> heh we should ask Github to develop some kind of AI to detect that someone mentions that he/she will do something in a certain amount of time ( then the issue becomes forgotten)

In all seriousness, what they should do for a decent workflow is:
- Allow assigning issues to non-organisation members (e.g. to all people who have already contributed one merged PR - they now have logic to identify such people and tag them as "Contributor") - and of course allow those contributors to assign issues to themselves
- Have an option to send reminders at a given interval of time for issues where you are assigned

GitHub, if you listen to us... :)

**Comment by akien-mga** [comment]
Pretty bump :)

**Comment by tagcup** [comment]
Rebased

**Pull request merged**
