### PR TITLE
Fix drawing boxselection on GraphEdit

### PR DESCRIPTION
**Pull request by volzhs**
Box selection is drawn with previous area at mouse press when one or more GraphNode is connected.
graphedit_boxselection

### CODE REVIEW

**Comment by AnilBK** [comment]
By looking at this PR,I noticed a typo in line 1316."previus_selected" instead of "previous_selected".

**Comment by volzhs** [comment]
@AnilBK nice catch. I made another commit for it.

**Comment by KoBeWi** [comment]
I can't reproduce the issue.

**Comment by volzhs** [comment]
here is my full reproduction step.
reproduction

tested official rc6 from https://downloads.tuxfamily.org/godotengine/3.3/rc6/

**Comment by volzhs** [comment]
@KoBeWi Can't you reproduce it? I have this issue with master and 3.x both.

**Comment by KoBeWi** [comment]
Yeah I can reproduce. I was a bit busy and forgot to reply, sorry.

**Comment by volzhs** [comment]
Thanks for the confirmation.

**Review by KoBeWi — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.

**Pull request merged**
