### PR TITLE
Fix auto reload scripts on external change

### LINKED ISSUE #49298: Auto Reload Scripts On External Change does not work
**Godot version:**
v4.0.dev.custom_build.5d9cab3ae

**OS/device including version:**
Artix Linux 5.12.8
`$ uname -a` provides the following output:
`Linux x1e2 5.12.8-artix1-1 #1 SMP PREEMPT Fri, 28 May 2021 22:51:03 +0000 x86_64 GNU/Linux`

**Issue description:**
Editing scripts from an external editor and saving them does not trigger the Godot editor to reload the script.  Tried this with neovim within terminal, and also VS Code.

**Steps to reproduce:**
Open the editor settings and set the following:
 - *General > Text Editor > Files > Auto Reload Scripts on External Change* : True
 - *General > Text Editor > Files > Auto Reload and Parse Scripts On Save* : True
 - *General > Text Editor > External > Use External Editor* : True

For neovim:
 - *General > Text Editor > External > Exec Path* : `/usr/local/bin/st` (I use suckless terminal)
 - *General > Text Editor > External > Exec Flags* : `-n TerminalFloat /usr/bin/nvim -c "cd {project}" -c "call cursor ({line}, {col})" {file}`  -- this names the terminal TerminalFloat so that my window manager makes it floating (i3-gaps), launches /usr/bin/nvim (neovim), and issues to neovim the command `"cd {project}"` and `"call cursor ({line},{col})"`, and passes the filename `{file}`.

For VS Code:
 - *General > Text Editor > External > Exec Path* : `/usr/bin/code`
 - *General > Text Editor > External > Exec Flags* : `{project} --goto {file}:{line}:{col}` -- exactly as the docs say

In either case, continue:
 - Open a script (new or existing) from the Godot editor -- it will correctly open the file in the specified external editor
 - Edit and save the script from within the external editor, particularly making changes to exported variables
 - Observe that no Output log message appears stating that the script was reloaded, and observe that no changes appear in the inspector to reflect changes made from the external editor
 
**Minimal reproduction project:**

An empty new project, with external text editor settings enabled

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by cptchuckles**
fixes #49298

### CODE REVIEW

**Comment by KoBeWi** [comment]
So I tested this and it doesn't seem to work? I tested with a simple script
```
extends Node
@export var test = 4
```
When I change value of `test`, it's supposed to be updated in the inspector, no? It doesn't happen.

**Comment by cptchuckles** [comment]
@KoBeWi Without this patch, the editor actually doesn't reload the script **at all** and the major problem is when you *add or remove* export variables; you would have to close and reopen the entire scene in order to see the most current exports.  As I discovered and wrote in the related issue #49298, the problem is that `GDScriptCache::get_full_script()` doesn't check file modified time before returning what's in the cache when the editor regains focus, so it would never know if the script changed since it was cached.

However, like you I noticed recently that half of the time, the editor appears to first save the old value in the `.tscn` as a property of the node (and the reset button appears next to the value in the inspector), and other times the editor wouldn't save the old value but instead populate it with the new value from the script as expected.  I don't know why that happens now, though, nor especially why it's intermittent.  Months ago, when I first opened this PR, it actually *did* update values and would never save old values in the scene file, but now it does, so I'll probably have to track that down too.

**Comment by cptchuckles** [comment]
I tracked the latest bug related to this (new defaults getting overridden by old defaults) down to 4e6efd1b07f1c6d53d226977ddc729333b74306a, which introduced C++ iterators.  There were several places where `E->get()` was changed to just `E` where it shouldn't have been, one such occurrence being now fixed by #55350 which solves it.  Too bad I didn't check the latest build before going on a bisect... lol

This patch is now once again working as expected on the latest revision.  I still need a reviewer to tell me whether my solution is stupid or not though

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by nathanfranke** [comment]
I get a SIGSEGV in my main project after this commit.
```
#0  0x000055555825084e in Map<StringName, GDScriptCodeGenerator::Address, Comparator<StringName>, DefaultAllocator>::_find (
    this=<error reading variable: Cannot access memory at address 0x7fffff7fefc8>, 
    p_key=<error reading variable: Cannot access memory at address 0x7fffff7fefc0>) at ./core/templates/map.h:299
#1  0x000055555824dc92 in Map<StringName, GDScriptCodeGenerator::Address, Comparator<StringName>, DefaultAllocator>::find (this=0x7fffff800748, 
    p_key=...) at ./core/templates/map.h:598
#2  0x000055555824c3fb in Map<StringName, GDScriptCodeGenerator::Address, Comparator<StringName>, DefaultAllocator>::operator[] (this=0x7fffff800748, 
    p_key=...) at ./core/templates/map.h:671
#3  0x0000555558239312 in GDScriptCompiler::_parse_expression (this=0x7fffff801b80, codegen=..., r_error=@0x7fffff80027c: OK, 
    p_expression=0x5555b4816b40, p_root=false, p_initializer=false, p_index_addr=...) at modules/gdscript/gdscript_compiler.cpp:226
#4  0x000055555823c49a in GDScriptCompiler::_parse_expression (this=0x7fffff801b80, codegen=..., r_error=@0x7fffff80027c: OK, 
    p_expression=0x5555b4816ca0, p_root=false, p_initializer=false, p_index_addr=...) at modules/gdscript/gdscript_compiler.cpp:670
```

**Comment by fire** [comment]
Can report this breaks our project. I recommend to revert this change. We have a large project and it broke. 

> Teammate.
> "Generally using timestamps for change checking is problematic."

**Pull request merged**
