### PR TITLE
Update freetype to 2.10.0

### PR DESCRIPTION
**Pull request by volzhs**

### CODE REVIEW

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
Cherry-picked for 3.1.1.

**Comment by akien-mga** [comment]
Cherry-pick reverted due to #28335.

Can be considered again for 3.1.2 or later once we figure out how to fix #28335 properly.

**Comment by Faless** [comment]
This also seems to break HTML5 export:
```
[ 96%] Compiling ==> thirdparty/freetype/src/sfnt/sfnt.c
[ 99%] progress_finish(["progress_finish"], [])
[100%] In file included from thirdparty/freetype/src/sfnt/sfnt.c:22:
thirdparty/freetype/src/sfnt/pngshim.c:21:10: error: expected "FILENAME" or <FILENAME>
#include FT_INTERNAL_DEBUG_H
         ^
thirdparty/freetype/src/sfnt/pngshim.c:22:10: error: expected "FILENAME" or <FILENAME>
#include FT_INTERNAL_STREAM_H
         ^
[100%] In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
thirdparty/freetype/src/sfnt/sfdriver.c:20:10: error: expected "FILENAME" or <FILENAME>
#include FT_INTERNAL_DEBUG_H
         ^
thirdparty/freetype/src/sfnt/sfdriver.c:21:10: error: expected "FILENAME" or <FILENAME>
#include FT_INTERNAL_SFNT_H
         ^
thirdparty/freetype/src/sfnt/sfdriver.c:22:10: error: expected "FILENAME" or <FILENAME>
#include FT_INTERNAL_OBJECTS_H
         ^
[100%] In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:25:10: error: expected "FILENAME" or <FILENAME>
#include FT_INTERNAL_STREAM_H
         ^
thirdparty/freetype/src/sfnt/ttload.h:26:10: error: expected "FILENAME" or <FILENAME>
#include FT_INTERNAL_TRUETYPE_TYPES_H
         ^
thirdparty/freetype/src/sfnt/ttload.h:32:13: error: unknown type name 'TT_Table'
  FT_LOCAL( TT_Table  )
            ^
thirdparty/freetype/src/sfnt/ttload.h:32:3: error: invalid storage class specifier in function declarator
  FT_LOCAL( TT_Table  )
  ^
thirdparty/freetype/include/freetype/config/ftconfig.h:377:28: note: expanded from macro 'FT_LOCAL'
#define FT_LOCAL( x )      static  x
                           ^
[100%] In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:33:25: error: unknown type name 'TT_Face'; did you mean 'FT_Face'?
  tt_face_lookup_table( TT_Face   face,
                        ^~~~~~~
                        FT_Face
[100%] thirdparty/freetype/include/freetype/freetype.h:499:32: note: 'FT_Face' declared here
  typedef struct FT_FaceRec_*  FT_Face;
                               ^
In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:33:3: error: parameter named 'tt_face_lookup_table' is missing
  tt_face_lookup_table( TT_Face   face,
  ^
thirdparty/freetype/src/sfnt/ttload.h:36:3: error: invalid storage class specifier in function declarator
  FT_LOCAL( FT_Error )
  ^
thirdparty/freetype/include/freetype/config/ftconfig.h:377:28: note: expanded from macro 'FT_LOCAL'
#define FT_LOCAL( x )      static  x
                           ^
[100%] In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:37:23: error: unknown type name 'TT_Face'; did you mean 'FT_Face'?
  tt_face_goto_table( TT_Face    face,
                      ^~~~~~~
                      FT_Face
thirdparty/freetype/include/freetype/freetype.h:499:32: note: 'FT_Face' declared here
  typedef struct FT_FaceRec_*  FT_Face;
                               ^
In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:37:3: error: parameter named 'tt_face_goto_table' is missing
  tt_face_goto_table( TT_Face    face,
  ^
thirdparty/freetype/src/sfnt/ttload.h:43:3: error: invalid storage class specifier in function declarator
  FT_LOCAL( FT_Error )
  ^
thirdparty/freetype/include/freetype/config/ftconfig.h:377:28: note: expanded from macro 'FT_LOCAL'
#define FT_LOCAL( x )      static  x
[100%]                     ^
In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:44:26: error: unknown type name 'TT_Face'; did you mean 'FT_Face'?
  tt_face_load_font_dir( TT_Face    face,
                         ^~~~~~~
                         FT_Face
thirdparty/freetype/include/freetype/freetype.h:499:32: note: 'FT_Face' declared here
  typedef struct FT_FaceRec_*  FT_Face;
                               ^
In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:44:3: error: parameter named 'tt_face_load_font_dir' is missing
  tt_face_load_font_dir( TT_Face    face,
  ^
thirdparty/freetype/src/sfnt/ttload.h:48:3: error: invalid storage class specifier in function declarator
  FT_LOCAL( FT_Error )
  ^
thirdparty/freetype/include/freetype/config/ftconfig.h:377:28: note: expanded from macro 'FT_LOCAL'
#define FT_LOCAL( x )      static  x
                           ^
[100%] In file included from thirdparty/freetype/src/sfnt/sfnt.c:23:
In file included from thirdparty/freetype/src/sfnt/sfdriver.c:26:
thirdparty/freetype/src/sfnt/ttload.h:49:21: error: unknown type name 'TT_Face'; did you mean 'FT_Face'?
  tt_face_load_any( TT_Face    face,
                    ^~~~~~~
                    FT_Face
thirdparty/freetype/include/freetype/freetype.h:499:32: note: 'FT_Face' declared here
  typedef struct FT_FaceRec_*  FT_Face;
                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
[100%] 20 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
scons: *** [thirdparty/freetype/src/sfnt/sfnt.javascript.opt.bc] Error 1
scons: building terminated because of errors.
```

**Comment by Faless** [comment]
My bad, the error I'm encountering seems to be related to #28396 instead. I'll open an issue/PR

**Comment by akien-mga** [comment]
Removing the cherry-pick label, it's probably better to stick to 2.9.1 for 3.1 unless there are features or bugfixes of new releases that we want to use.

#28335 still needs to be investigated in the master branch.

**Pull request merged**
