### PR TITLE
Publish Godot source generators as library (.NET/C#)

### PR DESCRIPTION
**Pull request by benjiwolff**
Draft implementation of godotengine/godot-proposals#10913.

### CODE REVIEW

**Comment by Delsin-Yu** [comment]
That's some excellent work! I'm facing a similar issue in my project and wish to have some custom export logic.
I have several record classes that hold assets, packed scenes, and path references for each subsystem. Writing boilerplate code for export, null checks, and instantiation is a lot of work.
My current solution is to create a separate C# console project that references my game project and reflects and writes the code to the Godot directory using `File. WriteAllText`. This also means that I must make sure my game project compiles in the first place and run the console project every time I export a new record instance. Nevertheless, the generated file has no modification protection.
This PR allows me to move all these code generation into a proper source generator, making my life much easier.

**Comment by benjiwolff** [comment]
Is there a release workflow for Godot nugets?

**Comment by Delsin-Yu** [comment]
> Is there a release workflow for Godot nugets?

No, there isn't.

**Comment by raulsntos** [comment]
Thanks for the contribution but I'm afraid this is not something we're interested in. There's no precedent for publishing source generators as a library, we feel like it doesn't match the established conventions in the ecosystem. Instead, we feel like we should identify the use cases users want this for, and address those properly.

Publishing a library would also mean we'd have to maintain compatibility, which adds complexity to the maintainability of the source generators. We are also currently working on new C# bindings based on GDExtension, and the new source generators are completely different, this makes the compatibility story more complicated and we wouldn't want users to start relaying on legacy generators.

We are aware that users want to extend our source generators, and there are a number of proposals/issues already open about it:

- https://github.com/dotnet/roslyn/issues/57239
- https://github.com/godotengine/godot-proposals/issues/9140
- https://github.com/godotengine/godot/issues/66597
- https://github.com/godotengine/godot/issues/67624

For your specific use-case, it looks like you are interested in creating a custom `[Export]`-like attribute. This is something that users have requested in the past, as you can see in the proposals/issues linked above. We have a few ideas in mind and there are other options we're more likely to take. Unfortunately, we're not ready to share anything at this time.

However, you can workaround this today by forking Godot's source generators and referencing your own source generators package. Then, you can disable all or some of Godot's source generators to replace them with yours:

```csproj
<PropertyGroup>
    <!-- This disables all source generators by removing the package reference. -->
    <DisableImplicitGodotGeneratorReferences>true</DisableImplicitGodotGeneratorReferences>

    <!-- This only disables the listed source generators. -->
    <!--
      NOTE: There's currently a bug that prevents you from specifying more than one.
            See https://github.com/godotengine/godot/issues/91999
    -->
    <GodotDisabledSourceGenerators>ScriptProperties</GodotDisabledSourceGenerators>
</PropertyGroup>

<ItemGroup>
    <ProjectReference Include="..\CustomGodotSourceGenerators\CustomGodotSourceGenerators.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <!-- or -->
    <PackageReference Include="CustomGodotSourceGenerators" Version="*" />
</ItemGroup>
```

I'll close the PR and the linked proposal, thanks for the contribution nonetheless.

**Comment by InfiniteCactusDev** [comment]
@raulsntos I would just like to add that your proposed workaround:
>However, you can workaround this today by forking Godot's source generators and referencing your own source generators package. Then, you can disable all or some of Godot's source generators to replace them with yours:

Is currently not viable because of an outstanding bug with GodotDisabledSourceGenerators:
https://github.com/godotengine/godot/pull/88682

**Pull request closed without merging**
