### PR TITLE
Fix editor settings weird behavior

### LINKED ISSUE #13995: Default values in the editor setings are broken.
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, godot3 tip 03c1b6be23009ca67eb585783ec0f76d9c535c88

**Issue description:**
 Even after 
  rm -rf ~/.local/share/godot ~/.config/godot

and creating a new project, some of the editor settings are marked as changed.

After a clicking at the ↺ 'revert to default' button

:bug: fist time godot crashed in an endless loop
```
EditorSettings::_get - Warning, not found: text_editor/completion/callhint_tooltip_offset
EditorSettings::_get - Warning, not found: text_editor/completion/put_callhint_tooltip_below_current_line
…
```

:bug: the second time it out of blue started to import my whole
home directory. I could only stop that with `xkill` (and  `find -name '*.import' -print0 | xargs -0 rm`)

I didn't dare to test it again ;)

### PR DESCRIPTION
**Pull request by volzhs**
Fix #13995

in addition, The default value of text colors at `Text Editor` / `Highlighting` are now set to Adaptive or Default theme color.
so, color is back to adaptive when pressing revert button if current theme color is Adaptive, not to default theme color.

editor-setting

reverting back color does not change all colors to default color theme anymore.

### CODE REVIEW

**Comment by volzhs** [comment]
wait a sec. I like to change something for this PR.

**Comment by volzhs** [comment]
ok. it's done.

**Comment by akien-mga** [comment]
CC @djrm

**Comment by djrm** [comment]
looks good.

**Pull request merged**
