### PR TITLE
Fix viewports not inheriting their embedding state

### PR DESCRIPTION
**Pull request by HaSa1002**
If a parent viewport embeds windows then any child window will do it too.

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this still relevant as of 4.0 RC 1?

CC @Sauermann

**Comment by Sauermann** [comment]
I am not sure, if this PR is a good idea.
Basically this changes the `embedding`-property for Windows during entering the tree , if the Window itself is embedded.
This doesn't look like a transparent behavior.

**Comment by HaSa1002** [comment]
I have no idea honestly. It's been a while since the last time I dug in the Godot code base. I've too many things I do and have to. Feel free to close this PR as well as my other open PRs if they're not felt needed anymore. I won't get back to contributing on a regular basis anytime soon, probably. I am truely sorry as I don't want to just vanish as I did. I just don't have the time and energy anymore. Maybe in the future 👋

**Comment by akien-mga** [comment]
Closing for now as discussed above, as this may not implement expected behavior.

**Pull request closed without merging**
