### PR TITLE
Improve the SoftBody node editor icon

### PR DESCRIPTION
**Pull request by Calinou**
The new icon uses 2-pixel-thick lines for consistency with other icons.
Its pixels are also aligned to the 16 pixel grid.

## Preview

image

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
Certainly better than the old one, but also there's no newline at the end of the file, and the other icons are expanded to a few lines. I don't know what format is desirable, but I personally prefer at least newlines at the end of each file.

**Comment by Calinou** [comment]
@aaronfranke I used [svgcleaner](https://github.com/RazrFalcon/svgcleaner) to optimize the SVGs, which results in slightly different output compared to scour. It doesn't add newlines at the end of files to save one byte, but there's no option to disable that behavior.

**Comment by aaronfranke** [comment]
In any case, probably worth merging alongside https://github.com/godotengine/godot/pull/32035 after a discussion about this.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
