### PR TITLE
asset_dir method in Android modules' gradle config

### PR DESCRIPTION
**Pull request by PatrickKaster**
This adds a 'android_add_asset_dir("...")' method to Android modules' gradle build config, analogously to the existing 'android_add_res_dir("...")' method, in order to define assets on a per module basis.

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good, but could you squash the two commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase)

**Comment by PatrickKaster** [comment]
Oops, my bad! Done.

**Comment by akien-mga** [comment]
Thanks!

**Comment by vnen** [comment]
@akien-mga are you aware this PR went to the 3.0 branch?

**Comment by akien-mga** [comment]
Ah no, thanks for the notice. @PatrickKaster Please make future PRs on the master branch, that's where development happens (with some changes potentially backported to stable branches).

**Comment by akien-mga** [comment]
Cherry-picked to the master branch.

**Pull request merged**
