### PR TITLE
Add proper snapping to tile polygon editor

### LINKED ISSUE #5847: Add a snapping grid to polygon editors in the TileSet editor
### Describe the project you are working on

2D game with a tile map

### Describe the problem or limitation you are having in your project

In comparison to Godot 3 adding proper collisions to a tile map is tedious<br>

In godot 3 by changing the steps in "Snap Options" it was possible to quickly add collisions in a smaller grid
image

Now in godot 4 it's no longer possible to change the snap options to quickly add collisions
image

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Add the old snap options from Godot 3

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will work like in Godot 3 by setting the step size different to the tile size

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

It is a good feature that was already in Godot 3 and should be available in Godot 4

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/5847
godot windows editor dev x86_64_2jQS4NjZQ1
The grid does not draw, but I could add it if it's important.

### CODE REVIEW

**Comment by kleonc** [comment]
Made like that it's not possible to snap to subpixel values. So e.g. for odd sized tiles you won't be able to snap to the tile's center. Meaning being able to snap to half pixels is a must. So at least `min`/`step` for the spin boxes should be set to `0.5` (maybe even more granual step customization should be allowed?:thinking:).

**Comment by KoBeWi** [comment]
Odd-sized tiles are a weird use-case and I never understood why it was half-pixel in the first place, but setting step to 0.5 should be enough.

**Comment by groud** [comment]
I believe the feature is fine, but I think it takes too much space as it is and is not the best to configure IMO.
What I would do: 
- Replace "grid step" in pixels by a subdivision value (defaulting to 3 or 4 I guess ?), as I don't think there are uses cases where you would need the grid with a size that's not a division of the tile size. It is also easier to setup IMO.
- Move this subdivision settings to a popup, likely accessible from the option menu dropdown.
- Add a single toggle button to enable/disable grid snapping.
- If we consider the bar is getting too large, the "snap to pixel" option might be moved inside the dropdown menu.

**Comment by ygypt** [comment]
> I believe the feature is fine, but I think it takes too much space as it is and is not the best to configure IMO. What I would do:
> 
> * Replace "grid step" in pixels by a subdivision value (defaulting to 3 or 4 I guess ?), as I don't think there are uses cases where you would need the grid with a size that's not a division of the tile size. It is also easier to setup IMO.
> * Move this subdivision settings to a popup, likely accessible from the option menu dropdown.
> * Add a single toggle button to enable/disable grid snapping.
> * If we consider the bar is getting too large, the "snap to pixel" option might be moved inside the dropdown menu.

i really like your idea of a simple one-line subdivision value, although imo putting it into a dropdown would be unnecessary. i guess its time to learn c++, i'd love to contribute to this PR :)

**Comment by nklbdev** [comment]
I created [small editor plugin](https://github.com/nklbdev/godot-4-tile-set-polygon-snapper) to help with this problem. Maybe it helps to add custom vertex snapping in future

**Comment by KoBeWi** [comment]
Updated based on feedback (including #73495 feedback)

- changed grid size to subdivisions
- the subdivision SpinBox is made smaller, so it doesn't take much space
  - it can be even smaller if we only allow 1-digit subdivisions
- snap setting and subdivision is stored in project metadata
- the grid is drawn

The original feedback was to move half-pixel to popup and make it separate from grid snap, with grid taking priority. This has a problem though: if grid is enabled, toggling half-pixel snap has no effect. So there is awkward setup where there are 4 states, but 2 are effectively the same. So instead of weird toggle/button combo, I went with 3-state popup.

https://user-images.githubusercontent.com/2223172/235516730-40989b26-6747-4349-975e-61268948a04d.mp4

You can either disable snap, enable half-pixel snap or enable grid snap.

**Review by groud — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
