### PR TITLE
Add ability to extend the set of Git pre-commit hooks

### PR DESCRIPTION
**Pull request by RandomShaper**
This is very useful for forks of Godot with custom needs.

### CODE REVIEW

**Comment by akien-mga** [comment]
@Faless suggested on chat to add `misc/hooks/pre-commit-custom-*` to `.gitignore`.

In theory it shouldn't be needed as the custom hooks have to be placed in `.git/hooks/` and so they don't need to be in `misc/hooks/`. But I personally tend to make my `.git/hooks` a symlink to `misc/hooks` so that hooks update automatically, so for my use case I'd actually want to put custom hooks in `misc/hooks/`.

**Comment by RandomShaper** [comment]
I'm quite a noob in what comes to Git hooks. How does Git pick additional hooks normally without modifying the list of known pre-commit hooks in the main `pre-commit` script?

**Comment by akien-mga** [comment]
> I'm quite a noob in what comes to Git hooks. How does Git pick additional hooks normally without modifying the list of known pre-commit hooks in the main `pre-commit` script?

What I do is symlink the whole `misc/hooks/` folder to `.git/hooks/`. So if a new pre-commit hook is added upstream, and included in `misc/hooks/pre-commit`, then I get it automatically via the symlink.

**Review by akien-mga — APPROVED** [review]

**Comment by RandomShaper** [comment]
Oh, I wasn't getting it right. It's clear now.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Pull request merged**
