### PR TITLE
Add editor option for automatically closing the output when stopping the game

### PR DESCRIPTION
**Pull request by mablin7**
By default the option is disabled. 
BTW this is my first PR, so if something went wrong, forgive me :smiley:
Fixes: #7726

### CODE REVIEW

**Comment by magyar123** [comment]
Should work now.

**Comment by magyar123** [comment]
Maybe this time?

**Comment by bojidar-bg** [comment]
Would be nice if you squash all those _4_ commits into just one.
To do this, you can use `git rebase -i` combined with a `git push --force` (but make sure you keep a backup somewhere, just in case things do go wrong).
You might check #6739 for some details on those commands.

**Comment by magyar123** [comment]
Oh I didn't want to close it. I don't know how I did it.

**Pull request closed without merging**
