### PR TITLE
Make script type distinguishable by icon

### PR DESCRIPTION
**Pull request by KoBeWi**
This PR adds separate icons for built-in scripts (outline) and tool scripts (with wrench):
image
Only applies to GDScript and VisualScript.

The tool script icons seem not perfectly readable though 🤔

EDIT:
I added a second commit that changes tool script icons to regular, but different color.
image
Definitely looks better, but I wonder if it's obvious enough what it means.

EDIT2:
btw, the script editor will automatically use icon with `Internal` and `Tool` suffix if available, so we could easily add icons for any additional language supported by the editor.

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Yeah, the wrench is definitely not working out, extra detail is bad for such small icons. Maybe instead of a wrench you could color it differently?

**Comment by CrezyDud** [comment]
how about adding a wrench on top of the icon, instead of replacing the whole icon?

**Comment by YeldhamDev** [comment]
@CrezyDud It's not currently replacing the icon, just besides it. I doubt that moving it to the top will improve things much.

**Comment by CrezyDud** [comment]
> @CrezyDud It's not currently replacing the icon, just besides it. I doubt that moving it to the top will improve things much.

image
looks like it is though

**Comment by CrezyDud** [comment]
> The tool script icons seem not perfectly readable though thinking

ye

**Comment by YeldhamDev** [comment]
I meant visually.

**Comment by CrezyDud** [comment]
> I meant visually.

ok

**Comment by KoBeWi** [comment]
Here's color version:
image
My concern is whether users will know that "yellow" means tool script. It might be confusing for some.

**Comment by CrezyDud** [comment]
> Here's color version: image My concern is whether users will know that "yellow" means tool script. It might be confusing for some.

how about a yellow wrench?

**Comment by Xrayez** [comment]
I don't think there's much benefit in distinguishing `tool` vs normal scripts, but distinguishing built-in scripts makes sense to me, because unlike `tool` scripts, built-in scripts have known limitations to be aware of (in contrast, `tool` scripts work mostly the same way, with the only difference that those kind of scripts can be run within the editor).

> My concern is whether users will know that "yellow" means tool script. It might be confusing for some.

This may not look nice when using the light editor theme.

**Comment by KoBeWi** [comment]
>I don't think there's much benefit in distinguishing tool vs normal scripts, but distinguishing built-in scripts makes sense to me

I remember some people requested tool scripts to display differently. It doesn't hurt to implement both.

> This may not look nice when using the light editor theme.

I used a color from the palette mentioned [here](https://docs.godotengine.org/en/stable/development/editor/creating_icons.html#color-conversion-for-light-editor-themes), doesn't work really well though.

>how about a yellow wrench?

Same
image
Doesn't seem to look good in any color. Cog and wrench just don't work together.

**Comment by raulsntos** [comment]
| Only applies to GDScript and VisualScript.

It also applies to CSharpScript tool scripts, just need to add a `CSharpScriptTool.svg` icon to `/modules/mono/icons`.

**Comment by KoBeWi** [comment]
Added C# icon. I haven't tested, but it should be used automatically.

**Comment by akien-mga** [comment]
I like the idea :+1: 

Makes sense for me to distinguish both internal and tool scripts, both would be useful to me.

I agree that the wrench overlay wasn't readable enough, and the yellow seems OK, but might be *too* accentuated? I don't really have a better suggestion though.

**Comment by pycbouh** [comment]
Amazing!

I think color is a fine solution for now. Incidentally, that's the same approach I used for my own tools to distinguish tool scripts, though I just used accent color for modulation.

**Comment by akien-mga** [comment]
> Incidentally, that's the same approach I used for my own tools to distinguish tool scripts, though I just used accent color for modulation.

That could make sense here too, instead of having `Tool` variants of the icon, we could modulate the `<Class>` or `<Class>Internal` icon with the accent color, so it fits the rest of the theme, including user-defined changes.

**Comment by KoBeWi** [comment]
With accent color:
image

**Comment by akien-mga** [comment]
Looks good, though might send conflicting signals with the accent colors of the script name? Not sure what that one means, is that a remnant of the script hotness feature highlighting the most recently viewed ones?

**Comment by KoBeWi** [comment]
I tweaked the saturation:
image
The tool script icon is 50% more saturated, but it doesn't work on fully saturated colors, so I also decreased the saturation of full-hot color by 10%.

**Comment by akien-mga** [comment]
Let's squash, merge and give this a spin?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
