### PR TITLE
Fix xform_inv of Plane, intermediate results were ignored

### PR DESCRIPTION
**Pull request by maiself**

### CODE REVIEW

**Comment by akien-mga** [comment]
The changes on those two lines seem correct, but did you confirm that the results is then what one would expect of `Transform::xform_inv(Plane)`? The code seems to just be a copy-paste of  the `xform(Plane)` variant with `s/xform/xform_inv/` + the bug fixed here, is that sufficient to get an inverse transform of a plane?

**Comment by maiself** [comment]
The results will be correct assuming the transform basis is orthonormal. For a transform with scaling the inverse transpose would need to be calculated. I'm not sure if it's the intent of the `xform*` functions to support such transforms, so I kept the patch simple and direct to fixing the obvious error.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
