### PR TITLE
Fix inefficient list iteration in Node

### PR DESCRIPTION
**Pull request by KoBeWi**
Noticed some random code that iterates a List using indices.

### CODE REVIEW

**Review by Chubercik — APPROVED** [review]

**Review by Mickeon — APPROVED** [review]
So that's more efficient, huh?

Even if it weren't, this is standard across the codebase.

**Comment by KoBeWi** [comment]
> So that's more efficient, huh?

It's more efficient specifically in List. Accessing a linked list element by index requires iterating all prior elements.

**Comment by lawnjelly** [comment]
It would be nice to remove the `[]` operator entirely from `list`, and fix all the misuse cases. I have a feeling it was discussed long ago, but there was some technical barrier (perhaps in some template requiring certain algorithms to be available).

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
