### PR TITLE
Removed instance button from ResourcePreloader for non PackedScenes.

### LINKED ISSUE #22724: ResourcePreloader bottom panel shouldn't show "Open Scene" button for resources
**Godot version:**
3.1-alpha 8068d02

**OS/device including version:**
Linux Mint 19 Cinnamon x64

**Issue description:**
Files added to the ResourcePreloader bottom panel all have an "Open Scene" button, regardless of whether they can be opened as scenes or not:
image

Trying to open a resource as a scene gives you this prompt:
image
Clicking either of the two options doesn't do anything though.

**Steps to reproduce:**
1. Add ResourcePreloader node
2. Drag a resource (such as icon.png) into the ResourcePreloader bottom panel
3. Find the "open scene" button and I guess click on it

### PR DESCRIPTION
**Pull request by Piet-G**
Removed instance button from ResourcePreloader for non PackedScenes.

Fixes #22724

### CODE REVIEW

**Comment by williamd1k0** [comment]
Hey, I was trying to work on it but with a different approach.
I added an Open Resource button if the resource is not a PackedScene.
I also added a Remove button because the current UX is not that good.

What are your thoughts on it?

image


> Note: you are really fast 😅

**Comment by DualMatrix** [comment]
@williamd1k0  Looks good adding the open resource button makes a lot of sense, I like it.

**Comment by williamd1k0** [comment]
I don't know if I should open another PR to supersede it, because I also added the Remove button and removed some useless stuff instead of only fixing it 🤔

**Comment by akien-mga** [comment]
Superseded by #22750.

**Pull request closed without merging**
