### PR TITLE
rewrite multiplayer spawner and synchronizer, making it a module

### LINKED ISSUE #61711: MultiplayerSynchronizer server crash in alpha9+
### Godot version

eaffb88558b6ef2a4c20ad7d1da94e3d1d4c0f4a

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

When running the [bomber](https://github.com/godotengine/godot-demo-projects/tree/4.0-dev/networking/multiplayer_bomber) example, the server instance crashes after starting the game. The lobby itself works fine so basic communications works. This problem does not exist with alpha8.

I have the same issue in my project, and removing `MultiplayerSynchronizer` makes it go away.

```
Godot Engine v4.0.alpha.calinou.eaffb8855 - https://godotengine.org
Vulkan API 1.2.0 - Using Vulkan Device #0: AMD - AMD RADV RAVEN
 

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.calinou (eaffb88558b6ef2a4c20ad7d1da94e3d1d4c0f4a)
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib64/libc.so.6(+0x3ea70) [0x7fe5ada24a70] ()
[2] List<NodePath, DefaultAllocator>::front() const ()
[3] List<NodePath, DefaultAllocator>::List(List<NodePath, DefaultAllocator> const&) ()
[4] SceneReplicationInterface::_send_sync(int, unsigned long) ()
[5] SceneReplicationInterface::on_network_process() ()
[6] MultiplayerAPI::poll() ()
[7] SceneTree::process(double) ()
[8] Main::iteration() ()
[9] OS_LinuxBSD::run() ()
[10] /var/home/jgillich/Downloads/godot(main+0x168) [0x556a70394a4d] ()
[11] /lib64/libc.so.6(+0x29550) [0x7fe5ada0f550] ()
[12] /lib64/libc.so.6(__libc_start_main+0x89) [0x7fe5ada0f609] ()
[13] /var/home/jgillich/Downloads/godot(_start+0x2a) [0x556a7039482a] ()
-- END OF BACKTRACE --
================================================================
Aborted (core dumped)

```

### Steps to reproduce

1. Get the bomber example
2. Run two instances and start a game

### Minimal reproduction project

_No response_

### LINKED ISSUE #62027: MultiplayerSynchronizer does not sync properties on scene root
### Godot version

136f84fc3549fa22b700d80f86216c484174ffb6

### System information

Fedora Silverblue 36, Ryzen 2400G

### Issue description

MultiplayerSynchronizer does not sync properties if they are located on the root node of a scene. Instead they remain at their initial values. I have tested this with `CharacterBody2D` and `CharacterBody3D` nodes, not sure if it would be the same with a simple `Node` at the scene root.

### Steps to reproduce

Get the reproduction project: https://github.com/jgillich/gotodot-mp-repro (run with at least version 0df0a07ab86381c1580a0a38d11ec44c4c9fddf7, not alpha9)

1. Run 3 instances:
```
godot --server
godot --client
godot --client
```
2. In one of the client windows, use A/D or Left/Right to move your character
3. Observe how the position in the other client window does not update
4. Repeat the steps above but add `--use-child` to the run arguments
5. Observe how the position updates in all clients when a character is moved

There is potentially another bug, if you uncomment the `create_player` line in `world.gd` so the server is also a player, and then try to join with a client, you get a bunch of errors. In the bomber example the server is also a player, but I haven't managed to figure out what the difference is.

### Minimal reproduction project

https://github.com/jgillich/gotodot-mp-repro

### LINKED ISSUE #62320: MultiplayerSpawner not working when instantiated on client after the host
### Godot version

v4.0.alpha10.official [4bbe7f0b9]

### System information

Windows 10

### Issue description

I've been getting some very buggy behavior with the MultiplayerSpawner when instantiating it

If you're connected to a server as a client, and instantiate a scene containing a MultiplayerSpawner AFTER the host has already instantiated that same scene & the host has already instantiated scenes for the MultiplayerSpawner to spawn, the MultiplayerSpawner just won't work on the client

The following error will be spit out by the client:
error

### Steps to reproduce

Simply load a scene containing a MultiplayerSpawner as a client after the host has already loaded that same scene & has instantiated scenes for the MultiplayerSpawner to spawn

### Minimal reproduction project

[MultiplayerSpawner bug.zip](https://github.com/godotengine/godot/files/8960343/MultiplayerSpawner.bug.zip)

### PR DESCRIPTION
**Pull request by nathanfranke**
Fixes https://github.com/godotengine/godot/issues/62027
Fixes https://github.com/godotengine/godot/issues/61711
Fixes https://github.com/godotengine/godot/issues/62320

Testing project: [test7.zip](https://github.com/godotengine/godot/files/9078818/test7.zip)

Tests:
- Custom Spawn with MultiplayerSynchronizer as child
- Spawner inside another Spawner
- Spawn with MultiplayerSynchronizer as child
- Standalone MultiplayerSynchronizer

CC @Faless 

Note for reviewers: `replication_editor_plugin.*` and `scene_replication_config.*` are not modified, except for `#ifdef TOOLS_ENABLED` and some imports.
`multiplayer_spawner.*` and `multiplayer_synchronizer.*` have changed considerably.

---

Note the use of RPCs. It isn't going to be perfectly space efficient, but the majority of the data being sent is `Variant`s (which are encoded the same way regardless) so it's not a big deal. Only other issue is the methods are technically exposed to GDScript, allowing the user to override them. I worked around it by naming the methods ~~`_internal_rpc_`...~~, but there should be a better solution. See https://github.com/godotengine/godot/issues/32585.

Edit: I am only naming them `_rpc_` because thinking again, private methods should be inaccessible (un-overridable?) by default.

Edit 2: Just noting here for future reference. I do respect the way the previous spawner/synchronizer handles packets, it is more versatile for bare C++. However, given the current multiplayer system, I don't think it's possible for a module (or gdextension) to make a custom packet. If this is desired though, rather than moving it to core, it would be better to implement a way for any module/gdextension to make its own packets.

---

### CODE REVIEW

**Comment by jgillich** [comment]
Nice work! I'm not qualified enough to review the code but I can confirm that it resolves the scene root syncing issue (https://github.com/godotengine/godot/issues/62027)

While you're at it, do you happen to have any ideas regarding #62320? That issue is still present here

**Comment by nathanfranke** [comment]
I did take a look at #62320, but I don't think it'll be resolved here. I'll give it a test though!

**Comment by nathanfranke** [comment]
Well, that took quite a while! I believe I got https://github.com/godotengine/godot/issues/62320 resolved, and I also got spawner subchildren working.

### Explanation:

Problem:
image

Previously, when a client joined, the server would receive the peer_connected signal and each Spawner would send the client the nodes that were needed. However, since [signals are not called in a deterministic order](https://github.com/godotengine/godot/pull/12248), it was possible for the player spawner to send its RPC before the World spawner even created it.

Solution:

Now, the server doesn't listen to peer_connected, but rather the client requests the spawns/syncs when the spawner is initialized. This also prevents errors if for whatever reason the Spawner/Synchronizer exists on the server but not the client. This also paves the way for proposals such as https://github.com/godotengine/godot-proposals/issues/3904, since the server no longer expects all clients to have the same Spawners and Synchronizers. (Lots of work is still needed, however, as there is nothing preventing a client from pretending to have those nodes)

**Comment by Faless** [comment]
I wish you had written a proposal, or contacted me about this, I've been doing work on interest management that will collide with this PR.

**Comment by Faless** [comment]
Also in general, using `RPC` this way is really not okay, since it causes each synchronizer to send it's own data alone, unlike the previous design where updates from multiple synchronizers would be bulked together saving a ton of bandwidth for small states.

**Comment by Faless** [comment]
> I wish you had written a proposal, or contacted me about this, I've been doing work on interest management that will collide with this PR.

To expand on this, I really appreciate your work in trying to implement those features, and I like the idea of clients requesting spawns, which is something likely needed, but there are some issues with the way this has been rewritten:

- The `MultiplayerReplicationInterface` is there specifically to allow modules/extensions to implement the replication API, and should not be removed, to the contrary, it should be exposed to GDExtension once completed.
- The `MultiplayerSynchronizer` and `MultiplayerSpawner` are "configuration" nodes, they implement their behaviors by calling into the replication interface (which needs a global overview to perform the appropriate optimizations).
- As I mentioned above, `RPC`s for synchronizations are not okay, because we really need to pack updates together as much as possible or it will perform poorly as soon as the number of synchronized objects grow.

I am currently finishing my work on the interest management proposal, which should also solve some of the issues, I would be happy to discuss further changes on top of that if needed.

Again, I really appreciate you working on this, and I think there are good ideas, but it cannot be accepted as is, and I would advise against putting more work on this before I finish the work on interest management proposal, because that should solve most of the issues already, and would certainly conflict with this. This came at an unfortunate timing, I am sorry about it :/ .

**Comment by nathanfranke** [comment]
Attempting some trials:

Specification:
- Client connects to server.
- Server spawns N nodes for client using MultiplayerSpawner.
- After some idle time, client picks a random location and sends it directly to the server in an rpc. time starts now.
- Server receives the RPC, sets the position of all nodes, and should eventually synchronize all positions.
- Once ALL nodes are in the correct position, time stops and is recorded.

Task | Synced 10 nodes | Synced 100 nodes | Synced 1000 nodes
--- | --- | --- | ---
Godot Master - Average latency after 10 trials | 326ms | 469ms | 757ms
Pull request - Latency after 1 trials | 318ms | 333ms | 700ms - 3000ms

The fundamental problem with too many nodes:

- Assume connection has arbitrary bandwidth limit of 200 unreliable packets per frame
- Each node sends a packet, meaning 1000 unreliable packets
- Assuming 200 packets make it through every frame
- It will take 30-40 frames for all nodes to be synced.
 
Layman's terms:

- Given a group of 1000 people, every timestep 200 random people are given a glass of water. After 30 timesteps, it is still likely that some particular person has never received their water.

I think a great improvement would be bundling the data into a single packet

---



> The `MultiplayerReplicationInterface` is there specifically to allow modules/extensions to implement the replication API, and should not be removed, to the contrary, it should be exposed to GDExtension once completed.

Hmm. I don't see what is particularly important about abstracting the replication interface. I'd imagine the biggest use case for multiplayer modules would be another multiplayer peer type (e.g. a Steamworks module that makes RPCs go through steam). Even if someone wants to modify the replication interface, they could disable the module and write their own (or copy some code).

> The `MultiplayerSynchronizer` and `MultiplayerSpawner` are "configuration" nodes, they implement their behaviors by calling into the replication interface (which needs a global overview to perform the appropriate optimizations).

> As I mentioned above, `RPC`s for synchronizations are not okay, because we really need to pack updates together as much as possible or it will perform poorly as soon as the number of synchronized objects grow.

I agree with both! How about, following your work with interest management and approval, I move all the functionality (e.g. networked spawning/syncing) to a singleton, which manages the spawners/syncs and bundles requests together?

**Comment by Diddykonga** [comment]
>>The MultiplayerReplicationInterface is there specifically to allow modules/extensions to implement the replication API, and should not be removed, to the contrary, it should be exposed to GDExtension once completed.

>Hmm. I don't see what is particularly important about abstracting the replication interface. I'd imagine the biggest use case for multiplayer modules would be another multiplayer peer type (e.g. a Steamworks module that makes RPCs go through steam). Even if someone wants to modify the replication interface, they could disable the module and write their own (or copy some code).

I just want give my opinion in that, I believe every piece of code that can be made abstract/extendable should be, as that is one of the ultimate reasons why I enjoy Godot as an engine in the first place, and should hopefully remain so into the future. 

Generality is slower then specialization, but can often support specialization while still being generic.

**Comment by nathanfranke** [comment]
See https://github.com/godotengine/godot/pull/63049 :heart:

**Pull request closed without merging**
