### PR TITLE
Adds Object::emits_signal

### PR DESCRIPTION
**Pull request by ghost**
This PR adds `Object::emits_signal` to check if `emit_signal` will actually emit a signal. This came up while working on #10655, but I imagine this situation might crop up in other places as well. So this is one idea to solve it.

Details:

In `Polygon2D::set_polygon`, the calculation of the item rect is currently deferred using `rect_cache_dirty`:

```
void Polygon2D::set_polygon(const PoolVector<Vector2> &p_polygon) {
	polygon = p_polygon;
	rect_cache_dirty = true;
	update();
}
```

Adding a signal on item rect changes might look like this:

```
void Polygon2D::set_polygon(const PoolVector<Vector2> &p_polygon) {
	polygon = p_polygon;
	rect_cache_dirty = true;
	update();
	emit_signal("item_rect_changed"); // note: rect might not have changed
}
```

However, not each polygon change changes the item rect. In order to emit the signal only on actual changes, we need to break deferment:

```
void Polygon2D::set_polygon(const PoolVector<Vector2> &p_polygon) {
	const Rect2 old_rect = get_item_rect(); // breaks deferment

	polygon = p_polygon;
	rect_cache_dirty = true;
	update();

	const Rect2 new_rect = get_item_rect(); // breaks deferment
	if (new_rect != old_rect)
		emit_signal(item_rect_changed);
}
```

The problem with the code above is that this now completely breaks deferment, even if no actual signal is attached (i.e. `emit_signal` is a noop).

In order to keep the deferment and only break it when necessary we need a way to check if a signal is attached, which this PR's `emits_signal` is about:

```
void Polygon2D::set_polygon(const PoolVector<Vector2> &p_polygon) {

	if (emits_signal("item_rect_changed")) {
		const Rect2 old_rect = get_item_rect();

		polygon = p_polygon;
		rect_cache_dirty = true;
		update();

		const Rect2 new_rect = get_item_rect();
		if (new_rect != old_rect)
			emit_signal("item_rect_changed");
	} else {
		polygon = p_polygon;
		rect_cache_dirty = true;
		update();
	}
}
```

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Wouldn't `has_connections_for_signal` or similar be clearer?

**Comment by groud** [comment]
> Wouldn't has_connections_for_signal or similar be clearer?

To keep it consistent with the function "get_signal_connection_list", I would prefer the function named as "has_signal_connection".

**Comment by poke1024** [comment]
Renamed to `Object::has_signal_connection`, following the suggestion by @groud.

**Comment by groud** [comment]
> Renamed to Object::has_signal_connection, following the suggestion by @groud.

Thanks :)It makes the pur

**Comment by reduz** [comment]
I don't understand what this is for and why is it needed. Do you not have
is_connected?

**Comment by poke1024** [comment]
@reduz As far as I understand, `is_connected` checks for a specific connection to a specific object (`p_to_object`). This PR is about checking if there's any connection at all for a given signal name.

**Comment by groud** [comment]
> I don't understand what this is for and why is it needed. Do you not have is_connected?

I thinks what OP proposes is to be able to check if a signal will effectively be sent before calling it.
In specific cases where you need a complex operation in order to send a signal, this can prevent some useless treatment if no one is listening.

Even if this is a corner case, I believe the function is worth having. Not sure about the implementation tho, should be checked.

**Comment by reduz** [comment]
Is there not any other way to find this information with current API?

**Comment by groud** [comment]
> Is there not any other way to find this information with current API?

Probably with something like:
```
List<Connection> connections;
get_signal_connetion_list("My signal", &connections);
bool empty =  connection.size() == 0; 
```
But it's more complex

**Comment by reduz** [comment]
Emitting a signal that no one is connected to has the same penalty of checking if the signal is connected.. so I still don't understand the use case

**Comment by reduz** [comment]
@groud the feeling that something is worth having is no justification for actually having it. Avoiding bloat in core is top priority.

**Comment by groud** [comment]
> @groud the feeling that something is worth having is no justification for actually having it. Avoiding bloat in core is top priority.

I do understand why in some situations, if you need a heavy processing in order to send a signal or not (and only for that), it could be interesting to check, a priori, if this treatment is really needed or not. I think this is useful only for optimization purposes.

However, I don't know in OP's case if checking for connections is worth or not. Here the only treatment is to check if the old rect is different from the new one. Unless get_item_rect() is a complex function, the gain may no be that interesting.

**Comment by poke1024** [comment]
OK, so let's close this then and stick with `get_signal_connection_list` for the specific case where this occurred.

**Comment by groud** [comment]
> OK, so let's close this then and stick with get_signal_connection_list for the specific case where this occurred.

Wait ! not yet, let's discuss it in PR monday ^^

**Comment by akien-mga** [comment]
I'm not against the core addition if it has a proper use case, but I'm not even sure if I see the point of what is described in the OP. The code looks more complex than it was, do we really gain something from it? Also without comments, someone would factor out this part and break your logic:
```
	polygon = p_polygon;
	rect_cache_dirty = true;
	update();
```
How often are we going to set a new polygon that wouldn't imply changing the resulting item rect?

**Comment by groud** [comment]
> I'm not against the core addition if it has a proper use case, but I'm not even sure if I see the point of what is described in the OP

Note that this function can also be useful for optimizing "user" code (from GDscript), thus it might worth adding even if the editor does not benefit from the change.

**Comment by poke1024** [comment]
>> How often are we going to set a new polygon that wouldn't imply changing the resulting item rect?

Good question. Quite seldom, I believe. Personally I believe spurious signals are fine, if the alternative imposes such runtime and code complexity as seen here now. So item_rect_changed then really could mean item_rect_might_have_changed here. Signal users can always add their own additional checks.

To guarantee emitting only actual changes, one either has to completely drop the `rect_cache_dirty` logic from `Polygon2D` or come up with some type of "signal exists" check as described here. All this does not seem worth the effort to get rid of a minority of superfluous item_rect_changed signals.

**Comment by akien-mga** [comment]
As discussed on IRC, to add such helpers in the core there should be a concrete use case that justifies it. Here the use case seems to be premature optimization, and tbh I wouldn't both even with the workaround mentioned in https://github.com/godotengine/godot/pull/10714#issuecomment-325362697.

Emitting signals is not particularly expensive, and the workflow with signals is that you emit them anyway, regardless of whether there's a callback that will react to them.

Here indeed if you really want to optimize I would look at the `rect_cache_dirty` logic and see how to modify it so that you don't need a workaround.

**Pull request closed without merging**
