### PR TITLE
Set isGame flag as true on AndroidManifest

### PR DESCRIPTION
**Pull request by lucasnlm**
Adds `android:isGame` to AndroidManifest.

### CODE REVIEW

**Comment by Calinou** [comment]
For reference, here's what the documentation says:

> ### `android:isGame`
> Whether or not the application is a game. The system may group together applications classifed as games or display them separately from other applications.
>
> The default is `false`.

—https://developer.android.com/guide/topics/manifest/application-element

**Comment by akien-mga** [comment]
Could you amend the commit message to be more explicit about what the commit does?

**Comment by lucasnlm** [comment]
@akien-mga You mean change the commit message?
Updated to `Set isGame flag as true on AndroidManifest`

**Review by akien-mga — APPROVED** [review]
Seems good to me, but I'll let @m4gr3d review if this should be done as is or configurable as suggested by @Calinou. (Configurability could also be done later on if/when there's a need, and until then users can do custom builds and edit the manifest).

**Comment by akien-mga** [comment]
@m4gr3d I guess it might still be used by some Android-derived OSes that have game-specific categories in their launcher? I know my Pocophone F1's MIUI 12 has a Game category, though none of my installed games seem to be sorted in it.

Unity does seem to still have the `isGame` setting documented in their docs for 2020.3 LTS at least: https://docs.unity3d.com/Manual/android-manifest.html

It does sound like something that shouldn't *hurt* to enable for those launchers which do use this metadata? Otherwise I'd advise pushing internally for getting it marked as deprecated if there's no benefit to setting it: https://developer.android.com/guide/topics/manifest/application-element#isGame

**Comment by m4gr3d** [comment]
@akien-mga Thanks for the pointer to the Android TV documentation. It indeed sounds like it shouldn't hurt to give users the ability to set it if they want.

**Comment by m4gr3d** [comment]
@lucasnlm Based on @akien-mga's comment, it may be worth adding this feature, however this PR would have to be updated so that the feature is customizable by the user.
Is that something you'd feel comfortable doing? If not, feel free to close this PR and open an issue instead.

Thanks!

**Review by m4gr3d — CHANGES_REQUESTED** [review]
The feature should be togglable.

**Comment by lucasnlm** [comment]
@m4gr3d I will try to implement it.

**Comment by akien-mga** [comment]
Superseded by #50028.

**Pull request closed without merging**
