### PR TITLE
Fix for lose state on change parent with reparent method

### PR DESCRIPTION
**Pull request by HeartoLazor**
Recap from issues/requests:
https://github.com/okamstudio/godot/pull/1943
https://github.com/okamstudio/godot/issues/1905
http://www.godotengine.org/forum/viewtopic.php?f=11&t=1117#p9336

Some nodes loses his state on remove_child / add_child on change parent
For example, on this demo which moves a node called traveler with animation/timer from left container to right one, and viceversa on move button, the animation cicles the text from 3,2,1, start, then loops a,b,c,d,e,f,g on a label. Timer loops a countdown of 10 seconds:

with:

> child.get_parent().remove_child(child)
> destination_node.add_child(child)
> https://gfycat.com/AmpleTotalChanticleer

As you can see, when the node parent changes, the animation receives the notification exit_tree() and stop the animation, and if autoplay of an animation is on, when the ready notification is received, resets the animation too.

with:

> child.reparent(destination_node)
> https://gfycat.com/SmartDeadDoctorfish

With the reparent, the state from the traveler doesn't change

The objetive of the reparent method is to move a node from one parent to another, without the loss of state on node or his childrens or the need of patch each children with gdscripts aimed only to change this behaviour, all implemented in a non-destructive way (add_child/remove_child, enter_tree/exit_tree, ready, works as always if you don't reparent)

the signature of reparent is:
node_to_change_parent.reparent(destination_node)

Reparent ignores only ready event and give the tools for know when the node is reparenting and take actions on event enter_tree/exit_tree from each type of node, so reparent vs remove_child/add_child method:
- The reparent only ignores the ready event
- Now exist a new method for query called "is_reparenting()", this one should be queried on enter_tree or exit_tree for skip/change behaviour on problematic nodes who loses his state on reparent.
- Two new notifications,NOTIFICATION_REPARENTING and NOTIFICATION_REPARENTED, those are called when the reparenting process start and ends, its like an exit/enter tree. This events set the bool of is_reparenting to true and false on node.cpp

For now we modified/check this node as an example with the enter_tree /exit_tree on reparenting behaviour using the is_reparenting() flag:
Animation Player

Also the demo from video for testing reparenting is added to demos/misc/reparent_tester with many features for debbuging issues and test if some another nodes lose state on reparent or if you want to see the issue on action change this lines:
qu20zol 1
uncomment the two remove_child/add_child and comment reparent lines on main.gd and viceversa for move with reparent

We need some Help with the check and implement the behaviour of conserve state on another nodes with the demo, but the core for reparent is finished.

The behaviour of loss of state described here was a big issue on my shmup, which abuses of move bullets from a local node attached on the ships, to a global one. This with the aim of the burst of bullets follow the coordinates from the ship and when is finished moves to a global node, so the bullets doesn't follow the ship coordinates anymore. Without reparent the animations from the laser show the spawn animation again on mid air, same with timers or other strange behaviour.
On the next video is the shmup using reparent for local to global, where all is fixed, look at the behaviour of the laser:
https://gfycat.com/AnchoredMistyCoati

### CODE REVIEW

**Comment by reduz** [comment]
I would think that if nodes lose their state when entering/exiting the tree it's a bug in the nodes, and I think the nodes should be fixed instead.. which ones are causing trouble?

**Comment by guilhermefelipecgs** [comment]
In animation the problem is here:
```GDScript
case NOTIFICATION_EXIT_TREE: {
		
			stop_all();
			clear_caches();
		} break;
```
https://github.com/okamstudio/godot/blob/master/scene/animation/animation_player.cpp#L226

When remove a node with animation, the animation will stop, then when you add in scene again the animation is stopped, maybe a function for continue playing from where stopped solves.
With GDScript it's possible to do this.

I don't know if @HeartoLazor have others use cases with other nodes.

**Comment by reduz** [comment]
yeah I guess stop_all() might not be necessary, but clearing caches is
required


On Wed, May 20, 2015 at 11:16 AM, Guilherme Felipe <notifications@github.com

**Comment by guilhermefelipecgs** [comment]
Well, if only this line is removed, I know that this case will work, I've tested this.

**Comment by reduz** [comment]
oh cool, do you know of other cases where reparenting might lose state?

On Wed, May 20, 2015 at 11:23 AM, Guilherme Felipe <notifications@github.com

**Comment by guilhermefelipecgs** [comment]
Timer node reset the countdown when you remove and add, I don't know if it's desired.

**Comment by guilhermefelipecgs** [comment]
this is complicated, that's why I thought create the reparent method, because when you remove a node from scene, it makes sense stop animation/timer I think, otherwise, if you want remove node with animation, the animation will play in background.
I 'll leave that with you because I do not know what is best .

**Comment by HeartoLazor** [comment]
> I would think that if nodes lose their state when entering/exiting the tree it's a bug in the nodes, and I think the nodes should be fixed instead.. which ones are causing trouble?

Many nodes, we're checking some 2d nodes used in our game, but the most explicit and visual ones is the animation player and timer. I don't want to alter the base behaviour from add/remove, this could lead to many problems for old projects in a destructive way. I noticed when you want to conserve the state is only when you change from one parent to another one, for that reason the reparent is implemented with this filosofy in mind, if you want the old one, you could remove/add as always. The documentation for reparent should be like: Change the parent from child without altering his current state. Also a requirement to use this method is the child should have a parent.
I uploaded a rc2 friendly demo here, which illustrates the problem, the same demo using reparent is inside "demos/misc/reparent_tester" from this fork:
https://mega.co.nz/#!Gcx3UBLT!96vaRtluMvE1aaVCzIsELrYMIBqjJFD-yTSViYtTKyk

But we could translate some of the changes to the default add/remove if you really want it, the demo is very good for expose those cases.

I could generate a checklist here with all the nodes, but i don't know if i could give permission to another people to edit/maintain it, commenting his fixes here, something like:

- [x] **animation player**: some comment because yeah
- [x] **timer**: ready reset his state and reparent ignores it
....

**Comment by HeartoLazor** [comment]
Ok. I just finished looking through all the objects from the scene folder, and found some issues with state loss. I tried my best to fix the most relevant ones for my game (animation/timer/sound) and others at least on some I found a workaround on the meantime for conserve state on remove + add, so this could be merged and open an issue for the left to fix ones.
Also on the fixes I followed this advice from reduz:
> I would think that if nodes lose their state when entering/exiting the tree it's a bug in the nodes, and I think the nodes should be fixed instead.. which ones are causing trouble?

So NO new reparent method (reverted if you see the commit log) and all changes are on the actual classes for a consecutive add after remove.

### **First I will list the fixed ones:**

**Autoplay issues on Timer, Animation and Music (timer.cpp, animation_player.cpp, stream_player.cpp):** the autoplay flag, if is true resets always the animation after remove + add so now executes autoplay and put the flag to false, so subsequent remove+add doesn't break the state
If you want the old behavior on remove+add the equivalent after this change on gdscript is:
```
nodeA.remove_child(timerNode)
timerNode.set_autostart(true) #or nodeAnimation.set_autoplay("animation name") on animation case
nodeB.add_child(timerNode)
```

**Stop of Sound and Music on 2D and 3D (sound_player_2d.cpp, stream_player.cpp, spatial_stream_player.cpp, spatial_player.cpp):** When you remove a sound node or child, the ongoing music stop on exit_tree and restart on enter_tree, so if you want to move a child node with sound to another parent, you couldn't do it without a restart of the sound on the actual code.
Now the sound continues playing on all sound type nodes (stream and sound) after remove and add, the code for stop the sound is moved to NOTIFICATION_PREDELETE event from NOTIFICATION_EXIT_TREE, so a queue_free on the node stop the sound. Also only create source_rid if is not created on ENTER_TREE, this is for preserve reference after remove + add so PREDELETE correctly free the sound and stop it.
If you want the old behavior, the equivalent on gdscript is:
```
nodeA.remove_child(soundNode)
soundNode.stop() 
nodeB.add_child(soundNode)
```


### **Second The issues found, but not fixed, with suggestions for a possible fix or workaround:**

**Some Objects don't reflect change of position on remove+add, but updates if we change the transform after remove+add:**
examples: 
Light Occluder 2d as child: https://gfycat.com/HilariousSecondDobermanpinscher
Light 2d node as child: https://gfycat.com/OnlyWellgroomedBronco
Camera as child: https://gfycat.com/WelllitFrequentCusimanse

As note, this only happens with some 2D nodes, the 3d version of those nodes doesn't have the issue.

Affected nodes:
```
light_2d.cpp
light_occluder_2d.cpp
camera_2d.cpp
ray_cast_2d.cpp (the collision point doesn't update correctly)
```

Workaround:
```
nodeA.remove_child(problematicNode)
nodeB.add_child(problematicNode)
problematicNode.set_pos(problematicNode.get_pos()); #yes, this forces the position update
```

Possible Fix:
As you see on workaround, with a change of transform, the problem is fixed. On C++ executes this code on set_pos from node2d.cpp:
```
void Node2D::set_pos(const Point2& p_pos) {
	if (_xform_dirty)
		((Node2D*)this)->_update_xform_values();
	pos=p_pos;
	_update_transform();
	_change_notify("transform/pos");
}
```
I suspect that the key line is "_update_transform();", I'm not sure if "_update_xform_values();" is necessary, so the fix could be a way to call _update_transform(); on enter_tree from problematic nodes, but on actual code this is a node2d private method, maybe make public or protected _update_transform or expose with a new public method and call it?

**Joints 2d/3d Broken on remove+add:**
Well a video is more illustrative about this issue:
2d: https://gfycat.com/GrotesqueEnlightenedCorydorascatfish 
3d: https://gfycat.com/PoorScalyCoyote

Affected nodes:
```
joints_2d.cpp
physics_joint.cpp
```
I don't have idea how to fix this issue.

**On vehicle 3d node after remove+add the car seems to wake up from sleeping state on a platform after move, and readjust as if where falling again on the platform**

Affected nodes:
```
vehicle_body.cpp
```
I don't have idea how to fix this issue.

**All GUI components doesn't register clicks or input after change to another parent, but if the component returns to his original parent, the input works again**
example: https://gfycat.com/RareHotGlassfrog

Affected nodes:
```
all nodes who inherits from control and have user input 
(buttons, checkbox, textbox, scrolls from windows, etc)
```
I don't have idea how to fix this issue, and lets be realistic here, who puts a GUI component on a node, and change it from parent on the running game.

### **Third Nodes that should have issues, but they are broken on godot, so I couldn't test it and another issue could be created about this problems**

**Event Player (event_player.cpp):** Mod file player?, Seems impossible to load a file without an infinite error loop on console who locks the IDE, tested with free .s3m .mod .xm files. 
Looped Error: http://vgy.me/bSNwi8.png 
Also this node could share the same issues with autoplay and stop on exit_tree from sound.

**Video Player (video_player.cpp):** I couldn't figure how to load or import a video on this node. Tried with an .ogv
This node could share the same issues with autoplay and stop on exit_tree.

### Demo for test issues
If somebody want to test the issues or look for issues on new nodes implemented on the future, I committed the two demos used for my tests, one for 2d and other for 3d:
>\demos\misc\reparent_tester
\demos\misc\reparent_tester_3d

**Comment by reduz** [comment]
thanks enormously! will work on it as soon as possible

**Comment by akien-mga** [comment]
Thanks for your impressive work and documentation of your findings :)

Note that if we want to merge this, a cleanup of the branch might be nice as there is a lot of noise due to repo update, merge conflicts, reverts, etc.. The simplest solution would likely be to create a new branch and cherry-pick the relevant commits.

But you might want to wait for @reduz's input to know if he plans to reuse your work directly, or design another solution based on your research.

**Comment by HeartoLazor** [comment]
The last commit (https://github.com/HeartoLazor/godot/commit/19ad6428682a95bb5d57a5cc4026baa83b7108f8) applies all my changes on an updated version from godot engine without conflicts, so you could take the changes from that commit only

**Comment by reduz** [comment]
OK just for reference, many of these ARE supposed to not keep state while being reparented: 

1) Sound will stop and not resume, it is expected that if one of these exits the scene, sound stops immediately. 

2) For music, we might want to add a flag that sound was interrupted and seek/continue when re-added, so will add this.

3) For timer, fix is correct

4) Camera will not revert to current if it was set to current, it is expected that the next camera availale takes over if a camera is removed.

5) Joints have node paths to other nodes, reparenting it will break those paths if the nodes are not found, but will work if the nodes are found. This behavior is expected.

6) I think the issue with GUI components is now fixed

7) For many 2D objects this is weird, they should get the TRANSFORM_CHANGED callback. I'll give it a check.

8) Videoplayer will stop and not resume, as synchronizing video with audio is super difficult using theora. 

Thanks for your work! will be giving it a check tonight.

**Comment by reduz** [comment]
I can't reproduce for occluder2D or light2D, seems to update state fine

**Comment by reduz** [comment]
camera3d I understand it will use the drag marging from previous position, so it will be akin to move it, be it inside our outside the scene.

**Comment by HeartoLazor** [comment]
Hey about this one:
> 1) Sound will stop and not resume, it is expected that if one of these exits the scene, sound stops immediately.

On my approach to fix this is the code from the commit:

```
		case NOTIFICATION_ENTER_TREE: {
			//find the sound space


			if (!source_rid.is_valid()) {
				source_rid = SpatialSound2DServer::get_singleton()->source_create(get_world_2d()->get_sound_space());

				for(int i=0;i<PARAM_MAX;i++)
					set_param(Param(i),params[i]);

				SpatialSound2DServer::get_singleton()->source_set_transform(source_rid,get_global_transform());
			}


		} break;
		case NOTIFICATION_TRANSFORM_CHANGED: {

			SpatialSound2DServer::get_singleton()->source_set_transform(source_rid,get_global_transform());

		} break;
		case NOTIFICATION_EXIT_TREE: {

			//if (source_rid.is_valid())
			//	SpatialSound2DServer::get_singleton()->free(source_rid);

		} break;
		case NOTIFICATION_PREDELETE: {
			if (source_rid.is_valid())
				SpatialSound2DServer::get_singleton()->free(source_rid);

		} break;
```

As you see I moved the code for deletion from  EXIT_TREE to PREDELETE, with that change  the sound is correctly stopped/deleted when you delete the object and you could add/remove the node without stopping the sound, currently the engine doesn't have a form to do this, so if you really doesn't want to change this behaviour, maybe you could add a flag with my behaviour, like the music one?
Also take note on 
if (!source_rid.is_valid()) { 
inside ENTER_TREE, this is for only create source_rid if is not created on ENTER_TREE, this is for preserve reference after remove + add so PREDELETE correctly free the sound and stop it, aka don't change reference if you add/remove an object.

**Comment by reduz** [comment]
no.. because by convention, no node can work or do anything while removed
from the scene. Any node removed from the scene is completely disabled.

**Comment by reduz** [comment]
at much, you can find a way to resume previous state when readded, but
that's as much as it can be kept

**Comment by HeartoLazor** [comment]
What about pause the sound and when you add the sound node, continues playing at the state when you remove it?
Whit this if you use this code
nodeA.remove_child(soundNode)
nodeB.add_child(soundNode)
the sound should continue playing seamless

**Comment by reduz** [comment]
maybe if the start time for the sounds is saved they could be resumed at
the right position, so when created again they could be played back at that
offset..

**Comment by reduz** [comment]
ah no, but this is impossible for ima-adpcm samples, seeking is not
possible. Well, forget it then.

**Comment by HeartoLazor** [comment]
Hey don't forget the autoplay part

> Autoplay issues on Timer, Animation and Music (timer.cpp, animation_player.cpp, stream_player.cpp): the autoplay flag, if is true resets always the animation after remove + add so now executes autoplay and put the flag to false, so subsequent remove+add doesn't break the state

Downloaded and tested, animation_player, stream_player has issues with autoplay, timer is fine, basically is disable autoplay after the execution of the autoplay code

on animation_player:
```
		case NOTIFICATION_READY: {

			if (!get_tree()->is_editor_hint() && animation_set.has(autoplay)) {
				play(autoplay);
				set_autoplay(""); //this line is the fix for autoplay issues with animation
			}
		} break;
```

on stream_player:
```
		case NOTIFICATION_ENTER_TREE: {

			//set_idle_process(false); //don't annoy
			if (stream.is_valid() && !get_tree()->is_editor_hint()) {
				if (resume_pos>=0) {
					play(resume_pos);
					resume_pos=-1;
				} else if (autoplay) {
					play();
					autoplay = false; //this line fix autoplay issues
				}
			}
```

**Pull request closed without merging**
