### PR TITLE
fix portal_occlusion_culler compilation with target=debug tools=no

### PR DESCRIPTION
**Pull request by jeremyz**
usage of poly_source_id must be guarded with #ifdef TOOLS_ENABLED

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by lawnjelly** [comment]
Yeah well spotted. :+1:

I did notice this and wasn't sure whether to wrap in `TOOLS_ENABLED` at the time, I assumed that because `DEV_ENABLED` only occurred in tools builds this would only be a blank macro. But maybe some compilers can't deal with this.

**Comment by akien-mga** [comment]
> I did notice this and wasn't sure whether to wrap in `TOOLS_ENABLED` at the time, I assumed that because `DEV_ENABLED` only occurred in tools builds this would only be a blank macro. But maybe some compilers can't deal with this.


That's a wrong assumption, `DEV_ENABLED` is defined on `target=debug` - both for editor or template builds. (`target=debug` templates are not part of the usual distribution, but can be compiled for extra debugging).

**Comment by lawnjelly** [comment]
Ahh didn't know this I thought it was just editor builds. Noted! :+1:

**Pull request merged**
