### PR TITLE
GDScript: Avoid deadlock possibility in multi-threaded load

### LINKED ISSUE #85255: `ResourceLoader.load_threaded_request()` hangs for `use_sub_threads = true` with no error messages
### Godot version

v4.2.rc1.official [ad72de508]

### System information

Godot v4.2.rc1 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3758) - 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 Threads)

### Issue description

ResourceLoader.load_threaded_request() hangs indefinitely for use_sub_threads = true with no error messages.
It happens when you have an instance of a resource in a scene and are trying to preload the resource in the script of the scene.

I think it could be deadlock and the threads are stuck busy waiting, but I'm just speculating as there is no error message and I haven't looked into the source code.

Happens in v4.1.2.stable.official [399c9dc39] and v4.2.rc1.official [ad72de508]

might be similar to https://github.com/godotengine/godot/issues/71726

### Steps to reproduce

1. Create a scene "S1" with script 
2. Create a scene "S2" with script and preload "S1" within the script
3. Create an instance of "S1" within "S2"
4. Try to call "ResourceLoader.load_threaded_request()" on "S2" with "use_sub_threads = true"

### Minimal reproduction project
[ResourceLoaderTest.zip](https://github.com/godotengine/godot/files/13445888/ResourceLoaderTest.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
We already have a mechanism in `WorkerThreadPool` by which it collaborates with `CommandQueueMT` by unlocking its mutex before starting a wait and relocking it afterwards. That is a deadlock prevention mechanism that lets certain otherwise ill situations to make progress.

I found that in multi-threaded load situations (with `RESOURCE_CACHE_MODE_IGNORE`), the GDScript cache can incurr in a deadlock. That's the case if multiple threads interact with `GDScriptCache::get_full_script()`. By letting the `WorkerThreadPool` unlock the corresponding mutex, the deadlock is broken.

The first commit just makes the existing system more generic (mostly a refactor). The second makes `GDScriptCache` opt-in for it. It's interesting to keep both changes separate for bisections.

**NOTE:** Due to a risk of regressions, as this is slippery ground, you power maintainers may want to reschedule to 4.4.

**UPDATE:** Fixes #85255.

### CODE REVIEW

**Comment by clayjohn** [comment]
> NOTE: Due to a risk of regressions, as this is slippery ground, you power maintainers may want to reschedule to 4.4.

I agree. The code seems good, but since it isn't fixing any reported regressions it's best to wait until 4.4

**Comment by RandomShaper** [comment]
This turns out to fix an important issue. We may want to reasses milestone.

**Comment by akien-mga** [comment]
This seems to break the `threads=no` build:
```
In file included from platform/web/http_client_web.cpp:31:
In file included from platform/web/http_client_web.h:34:
In file included from ./core/io/http_client.h:34:
In file included from ./core/crypto/crypto.h:36:
In file included from ./core/io/resource_loader.h:36:
./core/object/worker_thread_pool.h:240:18: error: class member cannot be redeclared
  240 |         static uint32_t thread_enter_unlock_allowance_zone(BinaryMutex *p_mutex);
      |                         ^
./core/object/worker_thread_pool.h:239:18: note: previous declaration is here
  239 |         static uint32_t thread_enter_unlock_allowance_zone(Mutex *p_mutex);
      |                         ^
```

**Comment by RandomShaper** [comment]
> This seems to break the `threads=no` build:
> 
> ```
> In file included from platform/web/http_client_web.cpp:31:
> In file included from platform/web/http_client_web.h:34:
> In file included from ./core/io/http_client.h:34:
> In file included from ./core/crypto/crypto.h:36:
> In file included from ./core/io/resource_loader.h:36:
> ./core/object/worker_thread_pool.h:240:18: error: class member cannot be redeclared
>   240 |         static uint32_t thread_enter_unlock_allowance_zone(BinaryMutex *p_mutex);
>       |                         ^
> ./core/object/worker_thread_pool.h:239:18: note: previous declaration is here
>   239 |         static uint32_t thread_enter_unlock_allowance_zone(Mutex *p_mutex);
>       |                         ^
> ```

I wonder why it doesn't support the overloading. However, I can just preprocess out those for web builds. I'll push with that.

**Comment by akien-mga** [comment]
> I wonder why it doesn't support the overloading. However, I can just preprocess out those for web builds. I'll push with that.

That's because in `!defined(THREAD_ENABLED)`, those are defined to be the same:
```
using Mutex = MutexImpl;
using BinaryMutex = MutexImpl;
```

So it's the same definition twice.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
