### PR TITLE
added use_alpha so that drawing tranparent color is possible

### LINKED ISSUE #9811: Image.blit_rect_mask add optional use_alpha
I need to draw with an transparent color this is currently not possible so I added this with default value false

https://github.com/godotengine/godot/blob/master/core/image.cpp#L1687

```
void Image::blit_rect_mask(const Ref<Image> &p_src, const Ref<Image> &p_mask, const Rect2 &p_src_rect, const Point2 &p_dest, bool use_alpha) {

...

if ( (!use_alpha && msk->get_pixel(src_x, src_y).a != 0) || (use_alpha && msk->get_pixel(src_x, src_y).a == 0)) {
```

---

Another thing, calculating `src_y` on the inner for looks like it could be done only once in the outer for(line 1681) or am I seeing something wrong?

https://github.com/godotengine/godot/blob/master/core/image.cpp#L1685

Master branch

### PR DESCRIPTION
**Pull request by AlexHolly**
@dumitru-stama maybe there is a better way?

closes #9811

### CODE REVIEW

**Comment by groud** [comment]
Isn't the blend_rect and blend_rect_mask function for blending with alpha ?
I believe your proposal is interesting, but it should not introduce some kind of redundancy in the API.

**Comment by AlexHolly** [comment]
I will give it another try

**Comment by AlexHolly** [comment]
I can do what I want it is not working like my solution does, this is how it looks with `blend_rect_mask`

You can see that alpha=0 changes nothing

peek 2017-07-26 19-22

**Comment by groud** [comment]
Well, in any case I think this feature is not crealy understandable. I do get it, but well, this is no common processing. :/ 

In any case, I think that implementing this kind of image treatement within the Image API should not be done. Indeed, the case you are facing here (reducing the alpha using a texture) is quite specific, I think it should be done outside the Image API (using set_pixel and get_pixel). Unless we want to add more exiting method to blend two texture together (additive, soustractive, darken, multiply, hue... )

By now I think this would make complex an API that should be kept simple (In my humble opinion).

(Btw, I note that the alpha (or lightness) value of the mask is not used to modulate the amout of color applied to the destination (it's only either 0 or >0). Don't know if this is normal...)

**Comment by AlexHolly** [comment]
Okay I think I used it in a wrong way thanks.

**Comment by groud** [comment]
No problem. :)
I any case I'd say this is still open to discussion. Maybe more functionnalities could be added to the Image API.

**Pull request closed without merging**
