### PR TITLE
Improved stream paused fade code

### PR DESCRIPTION
**Pull request by marcelofg55**
Improved the code and made the fade duration really short.

### CODE REVIEW

**Comment by homer666** [comment]
This is related to the discussion in #19205, just to keep track of things.

**Comment by homer666** [comment]
I just tested this out (on Linux Mint 18.3 Cinnamon) and the clicks have returned. Is this also the case on your end?

**Comment by marcelofg55** [comment]
It didn't click for me yesterday, did you test it with AudioStreamPlayer? or AudioStreamPlayer2D? or AudioStreamPlayer3D?

**Comment by homer666** [comment]
I was testing with just AudioStreamPlayer, but testing it now, the clicking happens with all three. This is the stream I was testing wtih: [dungeon castle B2.ogg](https://github.com/godotengine/godot/files/2177675/dungeon.castle.B2.ogg.zip) (set Loop Offset to 12 for a seamless loop if you'd like) Oddly enough, the problem only happens with this; every other stream I throw at it seems to work fine. Give it a try.

**Comment by marcelofg55** [comment]
I was just testing that ogg file and it also clicks if you toggle the playing property on the editor.

**Comment by marcelofg55** [comment]
I just worked it out, I'm not getting any more clicks with that ogg with the stream_paused property.

**Comment by homer666** [comment]
Can confirm, thanks for the fix!

**Comment by mhilbrunner** [comment]
Thanks for the improvement :)

**Pull request merged**
