### PR TITLE
Minor UI tweaks

### PR DESCRIPTION
**Pull request by lalitshankarch**
1. Fix default font antialiasing method: Change the default antialiasing method to LCD subpixel, as the majority of users are not on HiDPI screens: [source](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam).

2. Fix create project dialog UI. Center some options to make the project creation dialog look more appealing.

## Before
Screenshot 2024-05-16 201213

## After
Screenshot 2024-05-16 204641

### CODE REVIEW

**Comment by Calinou** [comment]
> Fix default font antialiasing method: Change the default antialiasing method to LCD subpixel, as the majority of users are not on HiDPI screens: [source](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam).

Note that this can make text look bad on OLED displays, but since these are in the minority, it's probably fine. Ideally, we'd detect the font rendering style based on the OS settings, but querying this requires OS-specific code that is currently not present in Godot.

That said, I would definitely not enable LCD subpixel antialiasing on macOS, as macOS itself no longer offers it since macOS 10.15. HiDPI displays are also pretty common among macOS users these days.

**Comment by flaff** [comment]
Personally I don't think aligning radio options block to the center makes sense. This looks very out of place IMHO.

Design libraries that I worked with usually have radios aligned to the left for LTR.
Example: [Material design radio button](https://m3.material.io/components/radio-button/accessibility)

**Comment by lalitshankarchowdhury** [comment]
> That said, I would definitely not enable LCD subpixel antialiasing on macOS, as macOS itself no longer offers it since macOS 10.15. HiDPI displays are also pretty common among macOS users these days.

I understand the subpixel antialiasing is done by `freetype` itself, so it won't be a problem on macOS.

**Comment by lalitshankarchowdhury** [comment]
> Personally I don't think aligning radio options block to the center makes sense. This looks very out of place IMHO.
> 
> Design libraries that I worked with usually have radios aligned to the left for LTR. Example: [Material design radio button](https://m3.material.io/components/radio-button/accessibility)

So, this is to address the case where the Create New Project dialog is stretched horizontally:

image

In the case of no centering, both the renderer choice and version control chooser are left aligned, which leads to two questions:

1. Should we limit the maximum size of the dialog?
2. Should we center align both the renderer chooser and version control chooser to make it look appealing.

**Pull request closed without merging**
