### PR TITLE
Use proper depth buffer format for rgba shadows

### PR DESCRIPTION
**Pull request by clayjohn**
Helps: #37975

This continues #33844. There is still an outstanding issue with DirectionalLights, but this fixes the issue with the other light types.

### CODE REVIEW

**Comment by akien-mga** [comment]
IMO until we have GLES2 re-implemented in `master`, this could go to the `3.2` branch directly.
When we start porting GLES2 again, we might simply `rm drivers/gles2 && cp -r ../godot-3.2/drivers/gles2 drivers` to get the latest version.

**Comment by clayjohn** [comment]
@akien-mga Good thinking. I started making a 3.2 PR but then realized there would be no conflicts with master so I changed it. I forgot we already discussed just copying GLES2 over to master once we were ready to start porting.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
