### PR TITLE
Improve AudioEffectDistortion and AudioEffectFilter documentation

### LINKED ISSUE #3993: Incorrect wording in AudioEffectFilter page
**Your Godot version:**
3.2.2

**Issue description:**
Resonance is described as "amount of boost in the overtones near the cutoff frequency", which is wrong. It doesn't boost overtones, it boosts all frequencies. Overtones are multiples of the frequency of a pitch, but resonance also boosts frequencies when the audio isn't based on pitch. Better would be "amount of boost in the frequency range near the cutoff frequency".

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_audioeffectfilter.html

### LINKED ISSUE #3995: AudioEffectDistortion has bad description
**Your Godot version:**
3.2.2

**Issue description:**
Page describes the distortion effect as "modify the sound to make it dirty."
"Dirty" is very subjective and depends on the application, distortion is also used in the audio world for saturating a sound, which is often described as making it sound warmer. Better would be to keep using the distort verb, this audio effect is the most common effect in existence and its wording should be pretty clear anyway.

**URL to the documentation page (if already existing):**
https://docs.godotengine.org/en/stable/classes/class_audioeffectdistortion.html

### PR DESCRIPTION
**Pull request by skyace65**
Improves the description of distortion by removing the word dirty, since it isn't a good description. Fixes the description of resonance in AudioEffectFilter, resonance boosts all frequencies, not just overtones. Closes https://github.com/godotengine/godot-docs/issues/3993, closes https://github.com/godotengine/godot-docs/issues/3995.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @robbertzzz if you want to review the changes.

**Comment by akien-mga** [comment]
It might be worth adding a link to https://docs.godotengine.org/en/latest/tutorials/audio/audio_buses.html#adding-effects in the `<tutorials>` section.

And the matching effects descriptions in that tutorial probably need the same changes.

**Comment by skyace65** [comment]
I've added a link to the audio buses page. Once this is merged I'll open a PR to fix the descriptions there.

**Comment by robbertzzz** [comment]
Looks great to me!

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.3.

**Pull request merged**
