### PR TITLE
Exclude known thirdparty/ ubsan errors

### PR DESCRIPTION
**Pull request by hpvb**
In my quest to make ubsan failures a build failure I've added all current ubsan errors by type to a new suppression file which we will then also use with CI.

The idea is to only add known ubsan errors to this file, so this is not a blanket exclusion of thirdparty/ this means that if we get new or unexpected ubsan in thirdparty/ builds would fail.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks!

**Comment by WhalesState** [comment]
Is this the reason why github actions fails to run the test project in master?

image

**Comment by akien-mga** [comment]
I don't think those are failures, the test projects still run fine I believe.
But yes the suppressions don't seem to work, there's a mismatch between the relative path used and how it's resolved from the binary itself.

**Comment by WhalesState** [comment]
This seems to fix it
```
  TSAN_OPTIONS: suppressions=${{ github.workspace }}/misc/error_suppressions/tsan.txt
  UBSAN_OPTIONS: suppressions=${{ github.workspace }}/misc/error_suppressions/ubsan.txt
```

**Pull request merged**
