### PR TITLE
Add an `Edit Now` option to project dialog to allow opting out of immediately opening a project after creation/import/install

### LINKED ISSUE #88891: User is forced to open a project immediately after importing it in Project Manager
### Tested versions

Reproducible in 4.2.1 stable and 4.3 dev.

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.5161) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 Threads)

### Issue description

Whenever I import a project in the Project Manager window, it gives me the options to `Import & Edit` or `Cancel`.
This denies me the option to import another project, rename the one I imported, or anything else.
If I have 5 projects I want to import, I have to wait for each one to open, close it, restart the Project Manager, and repeat 5x.

The expected behaviour is for the options to be `Import` or `Cancel`, with neither forcibly quitting the Project Manager. There is no reason to batch the two operations together. After the user finishes importing, it's one key or click to start editing the newly imported project.

### Steps to reproduce

Try to import a project in the Project Manager, and observe the dialog that pops up.

### Minimal reproduction project (MRP)

N/A

### PR DESCRIPTION
**Pull request by MajorMcDoom**
This PR adds a little check button to the project dialog so the user can opt out of immediately opening a project after creation/import/install, which is useful when you want to perform multiple imports or installs or creations without interruption/restarting.

The check button is checked by default, so the current default behaviour is unchanged.

I've opted to maintain the state of this checkbox *per session*. i.e. if you uncheck it while doing an import, it will remain unchecked if you try to perform another import right after. I believe this makes sense for the intended workflow of potential consecutive operations. The current "edit-immediately" workflow will not be impacted by this decision because once the project opens, the project manager is closed anyway, and the option will once again be on the default **true** state the next time the project manager is opened.

Adding a third button to the dialog was an option that I considered, but I decided that keeping the two buttons would be the less confusing change for users who like the current flow (they don't have to remember/choose which new button to press).

Fixes #88891 

screenshot4
screenshot5
screenshot6

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
**Edit Now** should be a CheckBox, not a CheckButton, as it doesn't have an immediate effect on the form itself (the effect only applies when confirming the dialog).

I also suggest moving it so that it's centered, as it can be hard to spot currently.

**Comment by MajorMcDoom** [comment]
Hey @Calinou your requested changes have been made. Mind taking another look?

**Review by Calinou — APPROVED** [review]
Tested locally (rebased on top of `master` https://github.com/godotengine/godot/commit/77d6283d22731398e23c3f1e1b4eeedd22a93152), it works as expected.

**Comment by Mickeon** [comment]
Does this look fine for 4.4?

**Comment by adamscott** [comment]
In my mind, this should be added buttons. "Create and Edit", "Import and Edit", and "Install and Edit". No need for a new check button.

**Comment by MajorMcDoom** [comment]
> In my mind, this should be added buttons. "Create and Edit", "Import and Edit", and "Install and Edit". No need for a new check button.

@adamscott Just to make sure I'm understanding you correctly: are you proposing another approach that has not already been mentioned, or are you just expressing your support for the 3-button approach that has already been mentioned?

**Comment by adamscott** [comment]
> are you just expressing your support for the 3-button approach that has already been mentioned?

Sorry @MajorMcDoom, yes that's what I meant. I didn't read all the comments before commenting, sorry. 🙏

**Comment by MajorMcDoom** [comment]
@adamscott @akien-mga

The two different UX schemes suggested here appear superficially trivial in difference, but would actually require quite a bit of refactoring. The project manager code has the two-button layout pretty much baked into the API, such that all the dialogs are configured and listened to via abstracted concepts of "ok" and "cancel".

UX-wise, my gut feeling is that the three button approach would cause confusion, and it's a strong enough gut feeling that I couldn't in good conscience just concede it in this case, so I just want to make sure the three-button approach is worth the extra refactoring (i.e. if we have good reason to believe the checkbox isn't good).

In comparison, it would be simple to move the checkbox to the right-side of the buttons (in the same row) in order to alleviate the crowding concern. It would also be the smaller UX change overall, preserving most of the current layout and functionality. IMO that is less work, and less risk.

I'd like to give the smaller change a try, and if someone really wants to try the three-button approach, they can make a different PR for that.

**Comment by akien-mga** [comment]
I agree that the 3 buttons option, while we use it already in some dialogs in the editor, wouldn't necessarily be good UX.

A checkbox on the side could be tried I guess, though it would also be a bit unconventional. It would need to be next to the "ok" button, and remember for this that the position of the "ok" button is swapped on Windows and Unix platforms by convention. And if we want to do it right it should probably also swap position when using a RTL language (might already be handled automatically).

A third option would be to have the "ok" button be a drop-down button similar to this GitHub button:
image

With options "Install and Edit" and "Install Only", etc.
But this is also something that would require custom development and can't be achieved easily with existing controls (that I know of at least).

So we can also just go with what's implemented here, I just feel we keep adding bad design practices to these dialogs and I can't wait for the day someone rewrites them from scratch with proper UX and UI design in mind. Things are all over the place here:
image

**Comment by MajorMcDoom** [comment]
> So we can also just go with what's implemented here, I just feel we keep adding bad design practices to these dialogs and I can't wait for the day someone rewrites them from scratch with proper UX and UI design in mind. Things are all over the place here: image

I definitely agree that it is very busy and inconsistent. Since this is a not very highly requested feature for a pretty niche use case, I'm also ok with just closing this PR and the associated issue (also created by me). In the interest of not adding even more mess to be cleaned up later. Would that be preferable?

**Comment by akien-mga** [comment]
Well I personally think the proposal is useful, I've wanted that behavior a few times myself.

**Comment by adamscott** [comment]
I propose though that we merge with the edit now checkbox for now.

> I can't wait for the day someone rewrites them from scratch with proper UX and UI design in mind.

I could take a look at this.

**Review by akien-mga — APPROVED** [review]
Let's go with this, and see if someone is bothered enough by the additional clutter to find a proper UX solution.

**Comment by aaronfranke** [comment]
I can understand the use case when importing a project, but why would you need to be able to not edit a project when creating the project?

**Comment by MajorMcDoom** [comment]
> I can understand the use case when importing a project, but why would you need to be able to not edit a project when creating the project?

That's an interesting point. If it's a niche enough use-case, perhaps it could be selectively hidden from the project creation dialog, which is currently the most crowded dialog. Is that what you're suggesting, @aaronfranke ?

**Pull request merged**
