### PR TITLE
Add 3D skeleton preview to Advanced Importer

### LINKED ISSUE #6801: Show skeleton bones in the Advanced Import Settings preview
### Describe the project you are working on

A 3D game where meshes and animations come in different files

### Describe the problem or limitation you are having in your project

I need to preview animations with skeleton bones since meshes come in different files. In this case, the 3D preview window shows an empty scene

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

copy functionality as it is in the Skeleton3DGizmoPlugin to show bones according to 3D Gizmo Editor Settings values

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

This is a WIP

Screenshot from 2023-05-01 21-51-16

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Cant be done using a plugin

### Is there a reason why this should be core and not an add-on in the asset library?

This improves the 3D importing experience overall

### PR DESCRIPTION
**Pull request by SaracenOne**
- Supersedes #78188
- Closes https://github.com/godotengine/godot-proposals/issues/6801

This PR rebases and extends the earlier PR by @jeronimo-schreyer with the following additions:

* Fixes the preview of skeletons becoming deformed and mangled when importing a skeleton with scaling.
* Instead of retaining the preview of the skeleton when one is selected, when you select an animation there is now a dedicated button for making the skeleton visible when previewing animations.
godot windows editor dev x86_64_TjzQlWaFUn
* Factors the generation of the skeleton previews when calculating the scenes' overall bounding box.

### CODE REVIEW

**Review by fire — APPROVED** [review]
Looks ok to me.

* Did an online review
* Did not compile godot engine
* Did not run a test project

**Comment by fire** [comment]
@jeronimo-schreyer Feel free to test if you want, since this is an updated version of your old pr.

**Comment by jeronimo-schreyer** [comment]
Sure, I can test on Windows 10 and Linux Manjaro 24. Also test changes proposed by @AThousandShips

**Comment by SaracenOne** [comment]
I've implemented @AThousandShips' changes, so this should be good to merge now unless anyone has any additional changes to request.

**Comment by fire** [comment]
I reran the failed integration test job

**Review by AThousandShips — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
