### PR TITLE
Replace "Invert" import option with more useful "Normal Map Invert Y"

### LINKED ISSUE #785: Add an import option to make Godot read a normal map with inverted Y axis
**Describe the project you are working on:**

2d isometric game with normal maps for 3d looking lighting effects.

**Describe the problem or limitation you are having in your project:**

Godot can't read standart normal map. I need to flip Green channel in order for it to work. Without editing the Y axis is flipped when lights are applied.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

Have godot read the normal maps the default way so we don't have to flip green channels in a different software. Possibly have an option where you can flip it manually. But I don't see the use.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

I have no idea, still a beginner.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Not to my knowledge. I had to flip green channel in image editor.

**Is there a reason why this should be core and not an add-on in the asset library?:**

I 2 figuring out why doesn't it work before I found out Godot can't read normal maps as it should.

Here I linked how the normal map looks when rendered in blender. Godot reads it upside down.

Normal

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/48693.

This can be used to invert a normal map's direction.

The "Invert" import option is no longer useful in Godot 4.0 since it uses height maps instead of depth maps in StandardMaterial3D. If you still need to use a depth map, SpatialMaterial3D features several properties to invert the height:

image

This closes https://github.com/godotengine/godot-proposals/issues/785. This partially addresses https://github.com/godotengine/godot/issues/18299 (needs further testing).

## Preview

*Left: inverted*
*Right: not inverted*

image

[test_normal_map_direction.zip](https://github.com/godotengine/godot/files/4708087/test_normal_map_direction.zip) (build Godot with this PR before opening the project)

### CODE REVIEW

**Comment by clayjohn** [comment]
Wouldn't it be more consistent to move this option to SpatialMaterial3D? Seeing as we have the other flip options there already. 

We need to keep in mind that Godot users upgrading from 3.2 to 4.0 may have designed their assets with Godot in mind.

**Comment by Xrayez** [comment]
> This can be used to invert a normal map's direction.

> If this change is welcome, I'll make a 3.2 version of this PR that keeps the "invert" import option for compatibility.

I'm not sure if it's safe to assume that this option is not used for something else, because as of now it's quite general-purpose. Even if it's doesn't make sense to have this in the engine as of now, I'm sure other modules/plugins could possibly benefit from the existing logic, as this could cover more than just ability to invert green channel, I'd personally keep `invert` option and add whatever is necessary for normal map processing.

**Comment by fire** [comment]
Is this pr considered rejected? @Xrayez makes an accurate point that normal fixing is different from invent.

**Comment by Calinou** [comment]
@fire I don't think we've gotten enough opinions about this yet. Also, this pull request is only for 4.0, I can make a PR for `3.2` that keeps the current Invert import option.

**Comment by fire** [comment]
I don't think more opinions will arrive. What is our consensus?

**Comment by akien-mga** [comment]
For the reference, we discussed this in a PR review meeting today and agreed with the change. We agreed that referencing Y instead of green would likely be better, though there was some concern about potential confusing with flipping the texture vertically on the Y axis. We suggested using `normal_map_invert_y` or similar to make it clear that it's in the context of normal maps where inverting Y is a common concept.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
