### PR TITLE
MainLoop: Remove deprecated methods

### PR DESCRIPTION
**Pull request by HaSa1002**
Moved out of #43240

### CODE REVIEW

**Comment by Xrayez** [comment]
For reference, I raised a concern for this a while back: #32335, but I have little concrete use cases to show, and whether they're valid in the first place.

**Comment by akien-mga** [comment]
Note that the C++ methods should also be removed if this is being removed.

**Review by akien-mga — APPROVED** [review]

**Comment by Xrayez** [comment]
Tried #7269, I haven't got to use those methods, only override them:

[non_realtime_main_loop_test.zip](https://github.com/godotengine/godot/files/5470929/non_realtime_main_loop_test.zip)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
