### PR TITLE
[3.x] Bump the target SDK version to 33 (Android 13)

### PR DESCRIPTION
**Pull request by m4gr3d**
Fixes https://github.com/godotengine/godot/issues/74646

[main version](https://github.com/godotengine/godot/pull/75203)

### CODE REVIEW

**Comment by cengiz-pz** [comment]
@m4gr3d, @akien-mga, Android SDK version 33 introduces a new POST_NOTIFICATIONS permission.  I haven't seen anything related to this permission in the commit attached to this issue.  Has this been addressed elsewhere?  Even though the permission can be added manually, it would be nice to have it included in Godot's list of predefined permissions.

More info: https://developer.android.com/develop/ui/views/notifications/notification-permission

**Comment by SnailRabbids** [comment]
Hi, I'm a customer and using godot for my android app. When do you think you can update godot to be compatible with Android 13 (sdk 33)? Can I change the sdk version manualy (now I'm using godot 3.5.1) or I have to wait for new release (3.5.3-stable?) and then rebuild/reupload my app to Google Play?

**Comment by m4gr3d** [comment]
> @m4gr3d Hi, I'm a customer and using godot for my android app. When do you think you can update godot to be compatible with Android 13 (sdk 33)? Can I change the SDK version manually (I'm currently using godot 3.5.1) or do I have to wait for a new version (3.6-stable?) and then re-build/upload my app to Google Play?

@SnailRabbids If you're using Godot 3.5.1, you can change the target SDK version manually in the Android export window under the `Custom Build` section.

Screenshot 2023-03-26 at 9 56 37 AM

**Comment by m4gr3d** [comment]
> @m4gr3d, @akien-mga, Android SDK version 33 introduces a new POST_NOTIFICATIONS permission. I haven't seen anything related to this permission in the commit attached to this issue. Has this been addressed elsewhere? Even though the permission can be added manually, it would be nice to have it included in Godot's list of predefined permissions.
> 
> More info: https://developer.android.com/develop/ui/views/notifications/notification-permission

@cengiz-pz The permission will be added in a follow-up PR.

**Review by akien-mga — APPROVED** [review]

**Comment by cengiz-pz** [comment]
> Android SDK version 33 introduces a new POST_NOTIFICATIONS permission. I haven't seen anything related to this permission in the commit attached to this issue. Has this been addressed elsewhere? Even though the permission can be added manually, it would be nice to have it included in Godot's list of predefined permissions.
> 
> More info: https://developer.android.com/develop/ui/views/notifications/notification-permission

@m4gr3d, I have created issue #75673 to track this

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.3.

**Comment by djrain** [comment]
> If you're using Godot 3.5.1, you can change the target SDK version manually in the Android export window under the `Custom Build` section.

To confirm, it's fine to just do this and no other changes are needed?

**Comment by NianoTT** [comment]
> > If you're using Godot 3.5.1, you can change the target SDK version manually in the Android export window under the `Custom Build` section.
> 
> To confirm, it's fine to just do this and no other changes are needed? Since it looks like 3.5.3 will not release in time.

Just check if your app is affected by any of the behaviour changes in 33:
https://developer.android.com/about/versions/13/behavior-changes-13

**Pull request merged**
