### PR TITLE
libpng: New version 1.6.23

### LINKED ISSUE #3059: Update libpng to latest 1.6.x version
This is a followup on #2787, as I made a PR (#3058) to update libpng to the latest 1.5.x already, thus staying on the same branch.

Updating to 1.6.x would likely need more work, but should also be done in the long run IMO; I'm not sure how long 1.5.x will be supported upstream.

BTW I noticed that we have ```-I/usr/include/libpng16``` during the compilation already, does someone know how this external usage of libpng16 and simultaneous usage of builtin libpng15 works?

### PR DESCRIPTION
**Pull request by J08nY**
Updated libpng to version ~~1.6.27~~ 1.6.23
Needed to fix iCCp chunk in a lot of pngs, since libpng 1.6 is more strict in this matter. See [[1]](https://tex.stackexchange.com/questions/125612/warning-pdflatex-libpng-warning-iccp-known-incorrect-srgb-profile) [[2]](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile) [[3]](https://wiki.archlinux.org/index.php/Libpng_errors).
Projects will also need to fix their pngs if they have an incorrect iCC profile or will receive warnings like:
`ERROR: _png_warn_function: iCCP: known incorrect sRGB profile`
Will do a PR in the godot-docs repo about this, adding some documentation about the errors and fixing them.

fixes #3059, updates: #5248

### CODE REVIEW

**Comment by akien-mga** [comment]
Meh, I merged too fast and noticed too late that you made a typo in the version number :) 1.6.27 does not exist, what we have is 1.6.23.

**Comment by akien-mga** [comment]
I fixed with 9bf3ee7 the bug that made libpng warnings treated as errors; they now raise a Godot warning instead:
```
WARNING: _png_warn_function: iCCP: known incorrect sRGB profile
   At: drivers/png/image_loader_png.cpp:65.
```

**Comment by J08nY** [comment]
Oops, sorry on the version number, I guess we just have to wait for 1.6.27 and be like ha! We had that moths ago! :smiley:

**Comment by rgrams** [comment]
Well this is annoying. So is there a color profile that it will accept, or does everyone have to go through some rigmarole to remove the chunk for every new png?

**Comment by vnen** [comment]
@rgrams I fixed all my problems with ImageMagicks mogrify tool (just by running `find . -name '*.png' -exec mogrify {} \;` in my project's dir). If the profile is correct it'll accept, since not all of my project's PNGs were showing the warning.

**Comment by reduz** [comment]
I did some fixes to ScrollContainer some time ago, maybe it fixed it

**Comment by vnen** [comment]
@reduz maybe you meant to post on #3472?

**Comment by J08nY** [comment]
@rgrams I will do a PR in godot-docs shortly, explaining the warning and will give instructions to fix PNGs on all platforms hopefully.

**Comment by J08nY** [comment]
@akien-mga Hmm will look into it, afaik libpng has no knowledge of the image source file in godot, it just reads the raw data and does its job. Although something of that sort could be done in `image_loader_png.cpp`

**Comment by J08nY** [comment]
For everyone searching the repo for the error message:

```WARNING: _png_warn_function: iCCP: known incorrect sRGB profile```

Here is a [guide](http://docs.godotengine.org/en/latest/tutorials/asset_pipeline/managing_image_files.html#fixing-pngs-iccp-chunk) to fixing PNGs.

**Comment by Dillybob92** [comment]
@reduz please...

https://github.com/godotengine/godot/blob/d463b6e3d005ddef1a0e4ff8f297cfc60de1d764/thirdparty/libpng/png.c#L2350

Is it legal to remove this if?
```
                  /* Warn that this being done; this isn't even an error since
                   * the profile is perfectly valid, but it would be nice if
                   * people used the up-to-date ones.
                   */
```

**Comment by akien-mga** [comment]
No. We don't touch upstream sources.

**Pull request merged**
