### PR TITLE
[Draft] Update dynamic_font.cpp To fix Flickering

### PR DESCRIPTION
**Pull request by ghost**
Hello, this is a fix for the bug i reported here #39628

### CODE REVIEW

**Comment by akien-mga** [comment]
Doesn't this break font oversampling, instead of fixing it? There's more code that refers to it using floats and does float comparisons.

The commit log should be amended to be more explicit, see https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

**Comment by Gerarama** [comment]
Sorry , its My first time ever to use the pull requests system.

From tracking the bug i reported , I find out that the font_oversampling is float value of 1.0
I failed to find if this value changes anywhere.

I have done my tests , I find only 1 downsides of this,
When scalling down the size , the oversamlping value doesn't scale down.
Neather when scalling up.

That's all i have for know.

**Comment by akien-mga** [comment]
See this search for a list of locations where `font_oversampling` is used:
```
main/main.cpp
1947:                   bool font_oversampling = GLOBAL_DEF("rendering/quality/dynamic_fonts/use_oversampling", true);
1948:                   sml->get_root()->set_use_font_oversampling(font_oversampling);

scene/main/window.cpp
540:    float font_oversampling = 1.0;
619:                            font_oversampling = screen_size.x / viewport_size.x;
645:                    font_oversampling = 1.0;
647:            if (DynamicFontAtSize::font_oversampling != font_oversampling) {
648:                    DynamicFontAtSize::font_oversampling = font_oversampling;

scene/resources/dynamic_font.cpp
220:float DynamicFontAtSize::font_oversampling = 1.0;
633:    if (oversampling == font_oversampling || !valid) {
640:    oversampling = font_oversampling;
651:    oversampling = font_oversampling;

scene/resources/dynamic_font.h
182:    static float font_oversampling;
```

I'm not an expert on it myself so maybe this change will be OK, but it sounds to me like it will create issue whenever one would actually need a ratio different from 1. I guess this change will mean that values inferior to 1 (e.g. 0.7) will be rounded back to 1, and there will be a jump from 1 to 2 when the scale ratio passes 1.5.

**Comment by Gerarama** [comment]
As far as i can see , the float values are the reason for the problem.
But the default font doesn't have this problem. 
so the problem is deeper then just oversampling value.

**Comment by volzhs** [comment]
AFAIK, the default font is bitmap font not dynamic font.
So it is not related to oversampling.

**Comment by akien-mga** [comment]
OP has deleted their account and this change still seems bogus to me, so closing. The related issue is still open for investigating and fixing (possibly with the same fix if it turns out to be correct after further investigation).

**Comment by Calinou** [comment]
The font oversampling factor should remain a floating-point value as the scaling factor won't always be an integer.

**Pull request closed without merging**
