### PR TITLE
Store more shadows per quadrant for 3D point lights

### LINKED ISSUE #61747: Having many OmniLights causes them to turn off, look weird, flicker
### Godot version

Godot 4 Alpha 9

### System information

Windows 10, NVIDIA GeForce 1060 GTX 3GB, Vulkan

### Issue description

Hello!
I'm working on a project with many OmniLights in the map scenes. This causes them to turn off, flicker, and look weird.
Also had this problem in Godot 3.x and thought moving to Godot 4 would fix the issiu but it is still there.
The problem can also appear in the Godot editor preview windows.
testn
You can see the weird light on the right. It should look like the light on the left.

### Steps to reproduce

Walk around in the scene for a while, look towards lamps and away. Lights should start to behave weirdly.
I placed a red cube at a spot where it usually doesn't take long

### Minimal reproduction project

[Uploading light_bug.zip…]()

### PR DESCRIPTION
**Pull request by Calinou**
This has several benefits:

- Performance increases noticeably, especially when lights with shadows are moving, or when objects move close to point lights that have shadows.
- Point light shadows look less sharp and more consistent with directional shadows' default appearance. Previously, point light shadows had a tendency to look overly sharp compared to directional shadows in most scenes.
- Up to 16 lights with shadows can be placed in a scene until shadow quality degrades, instead of just 4. It's not always obvious for people why the quality degrades in this case, so it's good to have this happen as late as possible (and ideally never in some projects).

This closes https://github.com/godotengine/godot/issues/61747.

**Testing project:** [test_omni_spot_shadow_performance.zip](https://github.com/godotengine/godot/files/8173456/test_omni_spot_shadow_performance.zip)
Press <kbd>Space</kbd> to start/pause the animation.

## Preview

**OS:** Fedora 36
**GPU:** NVIDIA GeForce GTX 1080
**Screen resolution:** 2560×1440

*The scene has 2 OmniLights with shadows and 1 SpotLight with shadows. Most complex scenes will have more lights with shadows than that, on top of having more complex meshes. This means the real world performance difference is likely greater than what demonstrated here.*

### Static scene

*Since this is a simple scene and the shadow atlas doesn't need to be updated every frame, the performance difference is small.*

| Before | After
|-|-|
| 2022-06-11_17 00 15_static_2560_old | 2022-06-11_17 03 56_static_2560_new |

### Scene with moving object

*The shadow atlas needs to be updated every frame in this scenario, leading to a much more pronounced performance difference.*

| Before | After
|-|-|
| 2022-06-11_17 01 33_moving_2560_old | 2022-06-11_17 04 25_moving_2560_new |

### CODE REVIEW

**Comment by Calinou** [comment]
> just changing the quadrants to 16 16 64 256 would do, especially as there are up to 512 clustered elements right now. with 128 however, 16 16 64 64 makes more sense, not to mention at too low resolutions the lights (omni especially) turn into a mess, so 64 should be the most a quadrant should have for 4k, or 16 for 2k..

Can you try benchmarking the performance difference when keeping the shadow atlas size to 4096 but tweaking the quadrants as you mentioned?

**Comment by mrjustaguy** [comment]
i3 10105f (4.2 GHz 4c/8t), GTX 1050 Ti, W11
1024x600 (ran a couple of times, consistent output)
2k 4,4,16,64 - ~705/~622 FPS
4k 16,16,64,256 - ~750/~645 FPS

1920x1080 (ran once)
2k 4,4,16,64 - ~239/~230 FPS
4k 16,16,64,256 - ~240/~230 FPS

This first result surprised me a little, I didn't expect more FPS from the higher resolution with more quadrants (for same effective shadow resolution) but my guess is that having shadows in different quadrants is slightly less efficient, and it's unclear what the bottleneck is, as the GPU is running at 60% and CPU is using like 7-8% during the test in the 1st scenario

**Comment by clayjohn** [comment]
> This first result surprised me a little, I didn't expect more FPS from the higher resolution with more quadrants (for same effective shadow resolution) but my guess is that having shadows in different quadrants is slightly less efficient, and it's unclear what the bottleneck is, as the GPU is running at 60% and CPU is using like 7-8% during the test in the 1st scenario

If your GPU isn't maxed out then FPS is not a good measure of time it takes to do something on the GPU unfortunately. GPUs do all kinds of throttling, underclocking etc. in order to save power and heat when they are not fully needed. It may be the case that the GPU dedicated more resources to shadow rendering when using the 4K texture because it expected to do more work, while in the 2nd scenario it was already close to max so it didn't change between 2K and 4K. 

Overall, are we sure the decrease in quality is worth the performance gain here? To me, the shadows in the "after" images look significantly worse.

**Comment by mrjustaguy** [comment]
That explanation makes sense.. I think the lower resolution look fine, but instead of lowering to 2k, I'd opt for more shadows. 16 16 16 64 or 16 16 64 64 probably makes the most sense, as it gives 12 omni lights or 24 spot lights for the 1st option, and 24 additional omni lights (36 total increase) or 48 spot lights (for 72 total increase) with the second option.

This increase in Lights with shadows would go hand in hand with FCR's main advantage (plenty of lights) out of the box, and the decrease in memory usage with 2k instead of 4k shadow map is just non-existent for even the more memory limited systems, as if like a few dozen megabytes of VRAM make or break the memory budget, you've probably got other things to worry about.

As keeping the resolution wouldn't hurt performance, unless using the added light shadows, I'd go with the extra lights.
Furthermore I agree with the reduction in Default effective Shadow Resolution for general lights, to keep them inline with the appearance of the same resolution of the default Directional Shadows

**Comment by Calinou** [comment]
After doing testing in scenes with dozens of point lights, I can say that decreasing the default point light shadow atlas isn't a good idea – shadows will be very blurry and full of acne. Tweaking the number of lights in each shadow quadrant is still worth a try though.

**Comment by Calinou** [comment]
Redone based on @mrjustaguy's feedback. This benefits framerate just as much (if not more) than the previous solution, while allowing scenes to contain more point lights with shadows before quality degrades.

**Comment by reduz** [comment]
The point of this feature is quality, not performance. Sure you can get a bit more performance but quality sucks. I think this should be left as-is.

**Comment by akien-mga** [comment]
@reduz seems against it and Clay tends to agree. I also find that the quality loss in the provided example isn't justified by a 0.1 ms perf gain.

**Pull request closed without merging**
