### PR TITLE
Fix Snap 2d Transforms To Pixel gaps

### LINKED ISSUE #56793: Vulkan: 2D Pixel Snap not working
### Godot version

4.0dev (ce6de71)

### System information

Windows 10, NVIDIA GeForce GTX 960

### Issue description

I've seen other issues like this but they're all closed as fixed. I'm still having this issue. Pixels are not snapping correctly with either or both pixel snap options.
1 pixel gap in between collisions.

### Steps to reproduce

Create a project with a floor and characterbody2d with basic movement functions, gravity, etc.
Set display stretch mode to `viewport` and `keep`.
Enable `Snap 2d Transforms to Pixel` or `Snap 2d Vertices to Pixel` or both.

image

### Minimal reproduction project

[PixelSnapBug.zip](https://github.com/godotengine/godot/files/7872520/PixelSnapBug.zip)

### PR DESCRIPTION
**Pull request by jtakakura**
Fixes #56793

### CODE REVIEW

**Comment by akien-mga** [comment]
I haven't looked at details but I believe this might solve the issue in some cases, and worsen the situation in other cases. @lawnjelly did a deep dive into this stuff for Godot 3 and this was a huge can of worms.

**Comment by jtakakura** [comment]
@lawnjelly Please tell me how to test this issue if you know.
This issue is a significant impact on pixel game developers.

**Comment by lawnjelly** [comment]
Here's a list of some reading for you:
https://github.com/godotengine/godot/issues/57221#issuecomment-1022917087

We did try different round modes if I remember right (was a couple years ago).

**Comment by jtakakura** [comment]
@lawnjelly Thank you for your reply
I found the reason you revert the similar modifications in https://github.com/godotengine/godot/pull/46615#issuecomment-790647994
I understand this problem is very complicated

**Comment by lawnjelly** [comment]
BTW this is not trying to discourage work on this area, it is clearly quite important to a lot of users, but tricky to get right (I just gave up with lack of patience in the end :smiley: , might have to revisit it now we are doing 2D interpolation ).

Probably will need some proper thought and a proposal to discuss how to proceed to properly solve this area.

**Comment by jtakakura** [comment]
Sorry for the late reply.
I looked at ways to solve this issue but I couldn't come up with a one-size-fits-all solution.
Then I would like to consider how to solve referring to the following PR.
Thanks.

https://github.com/godotengine/godot/pull/46615

**Pull request closed without merging**
