### PR TITLE
[3.2] Check for motion in cast_motion() before doing Bullet convexSweepTest().

### PR DESCRIPTION
**Pull request by madmiraal**
This is a the 3.2 branch version of PR #34219, because master has changed so much #34219 is no longer cherry-pickable.

### CODE REVIEW

**Comment by madmiraal** [comment]
Changed all 0.f and 1.f's to 0.0f and 1.0f as per https://github.com/godotengine/godot/pull/34219#discussion_r443141838

**Review by AndreaCatania — APPROVED** [review]

**Comment by AndreaCatania** [comment]
Looks good, thanks.

**Comment by akien-mga** [comment]
I'll merge for 3.2.3 once 3.2.2-stable is out in a few days (unless you're confident that the change is 100% safe to merge now).

**Comment by madmiraal** [comment]
It's safe to merge. It all started from this [comment](https://github.com/godotengine/godot/pull/34210#issuecomment-563134988) which was to do the same check in `cast_motion()` that we implemented in `test_body_motion()` to avoid Bullet dividing by zero, which produces undefined results.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
