### PR TITLE
C#: Fix crash when errors occur before language initialization.

### LINKED ISSUE #72835: [Godot 4 Mono B17] VR game nearly instant crashes when debbuger is active
### Godot version

4.0 beta 17 Mono

### System information

Windows 10, RTX 2070, Game Ready 528.24, Vulkan, HTC Vive

### Issue description

Game crashes without any logs nearly instant when started from editor. Only what I see is:
```
--- Debugging process started ---
--- Debugging process stopped ---
```
After some tries I found that it happens when:
- I use VR (HTC Vive)
- Project uses Mono
- Game starts with remote debbuger and debugging server is online
After that I compiled engine from source and I got what caused instant shutdown - SIGSEGV. I built engine with debugging symbols and I saw that:
\modules\mono\csharp_script.cpp:585
```cpp
Vector<ScriptLanguage::StackInfo> CSharpLanguage::debug_get_current_stack_info() {
#ifdef DEBUG_ENABLED
	// Printing an error here will result in endless recursion, so we must be careful
	static thread_local bool _recursion_flag_ = false;
	if (_recursion_flag_) {
		return Vector<StackInfo>();
	}
	_recursion_flag_ = true;
	SCOPE_EXIT {
		_recursion_flag_ = false;
	};

	if (!gdmono->is_runtime_initialized()) { // Here crashes. gdmono is null
		return Vector<StackInfo>();
	}

	Vector<StackInfo> si;

	if (GDMonoCache::godot_api_cache_updated) {
		GDMonoCache::managed_callbacks.DebuggingUtils_GetCurrentStackInfo(&si);
	}

	return si;
#else
	return Vector<StackInfo>();
#endif
}
```
Temporary/my fix is to add condition `gdmono == nullptr` before access to `gdmono->is_runtime_initialized()`.

### Steps to reproduce

1. Load minimal project
2. Try to start it from editor (It should crash)
-----
3. Export project
4. Enable debugging server
5. Try to execute game from cmd using remote debugger param (It should crash too)
-----
6. Try to execute game without param (It should work normal - you cannot do anything, because there are nothing in scene)

### Minimal reproduction project

[MinimalVR.zip](https://github.com/godotengine/godot/files/10675840/MinimalVR.zip)

### PR DESCRIPTION
**Pull request by RedworkDE**
- Fixes https://github.com/godotengine/godot/issues/72835
- `3.x` version: https://github.com/godotengine/godot/pull/74128

Added two additional null checks to ensure that every runtime initialization check also handles a null gdmono.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by neikeq** [comment]
How can `debug_get_current_stack_info` be called before language initialization? I wonder if there's a problem somewhere else.

**Comment by neikeq** [comment]
Are the checks in `is_assembly_reloading_needed` and `reload_assemblies` just preemptive? If so, I would prefer not to add them. I think it's pretty safe to assume that will never be called unless the runtime was initialized before and some assemblies loaded. If there's such a possibility, I prefer to add the checks to the specific method that calls them that is prone to that.

**Comment by RedworkDE** [comment]
> How can `debug_get_current_stack_info` be called before language initialization? I wonder if there's a problem somewhere else.

Alternative patch that just prevents that (untested)

```diff
diff --git a/core/debugger/remote_debugger.cpp b/core/debugger/remote_debugger.cpp
index b7471d7c82..e9c18847a0 100644
--- a/core/debugger/remote_debugger.cpp
+++ b/core/debugger/remote_debugger.cpp
@@ -107,6 +107,10 @@ void RemoteDebugger::_err_handler(void *p_this, const char *p_func, const char *
 		return; //ignore script errors, those go through debugger
 	}
 
+	if (!ScriptServer::are_languages_initialized()) {
+		return;
+	}
+
 	RemoteDebugger *rd = static_cast<RemoteDebugger *>(p_this);
 	if (rd->flushing && Thread::get_caller_id() == rd->flush_thread) { // Can't handle recursive errors during flush.
 		return;
diff --git a/core/object/script_language.cpp b/core/object/script_language.cpp
index 71f40660f4..590b3e1b18 100644
--- a/core/object/script_language.cpp
+++ b/core/object/script_language.cpp
@@ -44,6 +44,7 @@ int ScriptServer::_language_count = 0;
 bool ScriptServer::scripting_enabled = true;
 bool ScriptServer::reload_scripts_on_save = false;
 bool ScriptServer::languages_finished = false;
+bool ScriptServer::languages_initialized = false;
 ScriptEditRequestFunction ScriptServer::edit_request_func = nullptr;
 
 void Script::_notification(int p_what) {
@@ -222,6 +223,7 @@ void ScriptServer::init_languages() {
 	for (int i = 0; i < _language_count; i++) {
 		_languages[i]->init();
 	}
+	languages_initialized = true;
 }
 
 void ScriptServer::finish_languages() {
diff --git a/core/object/script_language.h b/core/object/script_language.h
index 696c9a94a5..780af3c48e 100644
--- a/core/object/script_language.h
+++ b/core/object/script_language.h
@@ -52,6 +52,7 @@ class ScriptServer {
 	static bool scripting_enabled;
 	static bool reload_scripts_on_save;
 	static bool languages_finished;
+	static bool languages_initialized;
 
 	struct GlobalScriptClass {
 		StringName language;
@@ -97,6 +98,7 @@ public:
 	static void finish_languages();
 
 	static bool are_languages_finished() { return languages_finished; }
+	static bool are_languages_initialized() { return languages_initialized; }
 };
 
 class ScriptInstance;
```

> Are the checks in `is_assembly_reloading_needed` and `reload_assemblies` just preemptive? If so, I would prefer not to add them. I think it's pretty safe to assume that will never be called unless the runtime was initialized before and some assemblies loaded. If there's such a possibility, I prefer to add the checks to the specific method that calls them that is prone to that.

Yes, same in the 3x version, where only 2 are actually required for the crash. The logic was that at that point we already assume that this point is reachable in some unexpected state, so I added a check for the really unexpected state of gdmono being null.

**Comment by neikeq** [comment]
If debug methods can be called before language initialization, then I think the check in `debug_get_current_stack_info` is fine (I don't feel confident about patching the remote debugger).
I guess the other two checks are fine to be preemptive against crashes, but I would prefer to use `ERR_FAIL_COND` in this case, as I consider it a bug.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.

**Pull request merged**
