### PR TITLE
Fix mouse button release not sent to gui_input if it's different from the button that gave focus

### LINKED ISSUE #14373: Fly mode gets stuck when holding both middle and right mouse buttons then releasing rmb
Godot 3.0 Beta 1 Win10 64bit

Not sure if this is desirable behavior, but in the 3d viewport if you hold middle mouse button and then right click and at the same time release middle mouse button you can release right mouse button and you are still in the free look mode.

### PR DESCRIPTION
**Pull request by Zylann**
Fixes #14373
See comment https://github.com/godotengine/godot/issues/14373#issuecomment-350515100

### CODE REVIEW

**Comment by NathanWarden** [comment]
This commit seems to break many things when clicking between panels. For instance, now when I middle mouse rotate and then try to click on the scene panel nothing will be clicked. Likewise, if I can select a node in the Scene panel then try and middle mouse rotate the 3D view it doesn't work.

**Comment by volzhs** [comment]
I'm facing exact same issue with @NathanWarden 
And I need to click panel to be able to scroll on editor.
seems very buggy to me.

**Comment by Zylann** [comment]
To be honest I didn't understood why the code was the way it was, so changing it didn't seem to be much different from what it was before. I interpreted this as "as long as there is a button pressed on a given control, that control is still considered in mouse focus", which made sense to me. Before, that wasn't the case and the thing seemed to be arbitrary.

> when I middle mouse rotate and then try to click on the scene panel nothing will be selected

Are you doing this while you have MMB still pressed?

> if I select a node in the Scene panel then try and middle mouse rotate the 3D view it doesn't work

Uuuh that wasn't intented at all by my fix... all I wanted to do is, as long as there is a mouse button held on a given control, that controls keeps mouse focus. What you describe is not a direct cause of this, but seems to have exposed weird bugs...

**Comment by volzhs** [comment]
the problem is that the current focused control keeps it's focus even after mouse released.
it doesn't let go until LMB on another control.

**Comment by NathanWarden** [comment]
@volzhs Yep, middle clicked in another panel and it now works again in that panel.

@Zylann I think I see the code issue. The code changed is in the "else" block of "if (mb->is_pressed())". So, this is the mouse button released block. But, since the code now just says "0" instead of "gui.mouse_focus_button" it's only defocussing when the left click is no longer pressed, whereas before it was detecting whichever mouse button was the last one to be pressed down. So, when we middle mouse rotate it is never getting that the middle mouse was up.

There's code preventing selecting with other mouse buttons while a button is recorded as down at line 1643

``` C++
if (gui.mouse_focus && mb->get_button_index() != gui.mouse_focus_button) {
	//do not steal mouse focus and stuff
}
```

**Comment by volzhs** [comment]
I think this prevents possibility to catch drag over to another button.
we need to keep it works as it was and find a way to send a signal to last focused gui control.

**Comment by Zylann** [comment]
Should I improve my PR or you think another approach should be taken? I'm not well concentrated right now (as I'm preparing for something not-programmey at all) so feel free to make another PR that fixes the same original issue

**Comment by NathanWarden** [comment]
Okay, I finally looked at the other issue and your code here just exposed the problem more clearly :) My personal thought is that this entire portion of the code needs to be fixed. I'm *not* in favor of reverting your commit as it's just going to re-hide the actual issue.

**Comment by NathanWarden** [comment]
Unless you want this one @volzhs, or if anyone else wants it, I can try and tackle it. It'll be a few hours before I can get to it. So, if anyone wants it feel free to speak up before then :)

**Comment by volzhs** [comment]
@NathanWarden go ahead~ :) :+1:

**Comment by ptodorov0123** [comment]
I don't know If this is related to this but panels are now stealing the focus and keeping it. Should I open an issue for this?
ezgif com-video-to-gif

**Comment by NathanWarden** [comment]
@ptodorov0123 Yes, this is absolutely related... I'm working on a fix right now :)

**Comment by reduz** [comment]
I ended up reverting this for the time being, unless a better solution can be found. I'm not convinced the original problem is a bug also.

**Comment by NathanWarden** [comment]
The original problem is probably not *much* of an issue, but if a person accidentally does press the buttons in that order: click and hold middle, click and hold right, unclick middle, unclick right, they will now be seemingly stuck in the viewport in right mouse mode. This could happen from accidentally hitting right mouse while they were letting off middle mouse. Left clicking *doesn't* get them out of being stuck. Fortunately, pressing escape or clicking right again does. But, if this happens to a person and they don't know why I could see it being a little frustrating.

**Pull request merged**
