### PR TITLE
Add new window setting: always on top

### PR DESCRIPTION
**Pull request by RandomShaper**
Implemented for Windows and Linux. __EDIT__: Now also for Mac thanks to @bruvzg.

This code is donated by [AdPodnet](https://www.adpodnet.com/).

@akien-mga , I've set 3.1 as the milestone since this is a new feature and we are beta-frozen. But given it's short-scoped, if you find it may fit 3.0, please update the milestone accordingly.

### CODE REVIEW

**Comment by bruvzg** [comment]
Implementation for macOS ([Window Levels](https://developer.apple.com/documentation/appkit/nswindow/window_levels)):
```obj-c
void OS_OSX::set_window_always_on_top(bool p_enabled) {
	if (is_window_always_on_top() == p_enabled)
		return;

	if (p_enabled)
		[window_object setLevel:NSFloatingWindowLevel];
	else
		[window_object setLevel:NSNormalWindowLevel];
}

bool OS_OSX::is_window_always_on_top() const {
	return [window_object level] == NSFloatingWindowLevel;
}
```

**Comment by RandomShaper** [comment]
I could add this to my PR, but since you are the author, you deserve credit, so you can submit your own this this, based on mine.

**Comment by akien-mga** [comment]
Yeah let's wait for 3.1, I don't think this feature would add issues for 3.0 but I have to be consistent with what gets merged (otherwise contributors keep pushing enhancements in hope to make it for 3.0 instead of helping fix critical bugs :P - note that this is not a rebuke to anyone).

**Comment by RandomShaper** [comment]
@bruvzg, finally I've added your code, crediting you in the commit message. Thanks!

**Comment by RandomShaper** [comment]
I've just marked this one cherry-pickable for 3.0.

**Comment by hpvb** [comment]
tested on Linux and Windows, cherry picked into 3.0.3

**Pull request merged**
