### PR TITLE
Re-add a Camera3D icon gizmo to the 3D editor, renew Camera2D/3D icons

### LINKED ISSUE #53083: Spatial camera unselectable in editor and icon gizmo not shown
### Godot version

v3.4.beta5.official

### System information

Windows 10 gles 3

### Issue description

As shown on screenshot:
image
Worked in 3.3.2 and 3.3.3 where I also tested.
image

### Steps to reproduce

Create a 3d scene and add camera with the + button. It doesn't matter if it's an old scene or just created.

### Minimal reproduction project

_No response_

*Bugsquad edit (keywords for easier searching): Camera3D*

### PR DESCRIPTION
**Pull request by Calinou**
**Marked as draft, as new Camera2D and Camera3D node icons should be created to match the new icon gizmo design.**

The lack of icon gizmo made it no longer possible to select Camera3D nodes in the 3D viewport by clicking on them.

A new Camera3D icon gizmo was designed to be direction-neutral. This avoids the issue that the previous icon gizmo had, since it was always facing right.

This closes https://github.com/godotengine/godot/issues/53083.

## Preview

Before | After
-|-
Screenshot_20230808_155324 | Screenshot_20230808_155431

Before | After
-|-
Screenshot_20230808_155334 | Screenshot_20230808_160346

*Listener3D on the left, Camera3D in the middle, ReflectionProbe on the right.*

image

### CODE REVIEW

**Comment by reduz** [comment]
Looks good to me, what is it missing?

**Comment by Calinou** [comment]
> Looks good to me, what is it missing?

As I wrote in OP:

> Marked as draft, as new Camera2D and Camera3D node icons should be created to match the new icon gizmo design.

I've started working on those icons a while ago, I'll try to finish them ASAP.

**Comment by Calinou** [comment]
I pushed new icons:



Let me know if this is OK. CameraEffects, CameraTexture, ClippedCamera3D and XRCamera3D icons still need to be changed.

**Review by adamscott — APPROVED** [review]
Seems good to me.

**Comment by akien-mga** [comment]
It's been in draft for 2 years, maybe we can merge what's made already? Or poke MewPurPur if you need help ;)

**Comment by Calinou** [comment]
> It's been in draft for 2 years, maybe we can merge what's made already? Or poke MewPurPur if you need help ;)

I've finished all icons; it's ready for review now.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
