### PR TITLE
Reorganize editor top-left menu

### LINKED ISSUE #645: Improve main window open/close behaviour
**Describe the project you are working on:**

N/A - its just about day to day working with Godot.

**Describe the problem or limitation you are having in your project:**

Godot starts up in the project manager, then you get to edit a project and the editor opens up. However, closing the editor window terminates Godot. You can get back to the project manager but with a menu option named "Quit to the Project List".

At a lower level, the confirmation dialogs are asking the wrong questions and providing confusingly named options...

When you close the editor window with the close box at top right, you get asked to confirm exiting the editor. 

- Yes, the editor is going to exit, but only because the whole godot application is going to exit. So it's asking the wrong question - should be about 'is it ok to exit Godot'.

- The buttons in the confirmation dialog are "Quit" and "Cancel", where "Quit" cancels the dialog and "Cancel" quits the application. You get used to it, but its crazy.

- I suspect the whole reason for this dialog is to stop you exiting the application accidentally when all you really meant was to return to the project manager.

So the way you currently get back to the project manager is the option in the Project menu, "Quit to Project List" - which brings up a confirmation "Open Project Manager" (cancel/yes)

- the naming is confusing given this option is just closing the project.

- The menu option should be "Close Project..." (I got here by opening a project from the project manager, so I expect closing the project takes me back)

- The confirmation should be about closing the project

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The confirmation dialogs should be changed to ask the right questions and provide obvious responses. I'd have put that in as a bug except I think the close actions should be changed as well.

Closing the edit window should take you back to where you opened it from, rather than exiting Godot. i.e. just close the project edit window. It's less of a surprise that way.

The Project menu should have priority over the Scenes actions because the edit window is effectively a project edit window and manages a group of scenes. The Project menu is what would be called the File menu in almost every other IDE - you just 'know' that the File menu will have an option to Exit the application and one to close the file (project) you opened to get here in the first place (the same as the window closebox action). Again it's less of a surprise this way.

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

Modify the question and response text in the confirmation dialog box for closing the Godot application. Affects translations.
- "Exit the editor?" -> "Are you sure you want to exit Godot?"
- "Cancel"
- "Quit" -> "Exit"
- Note: Yes/No responses would work too

Modify the question and response text in the confirmation dialog box for closing the project editor. Affects translations.
- "Open Project Manager?" -> "Are you sure you want to close this project?"
- "Cancel"
- " "Yes" -> "Close"
- Note: Yes/No responses would work too

In the project editor window, adjust the existing Project menu
- Move the "Project" menu to be left of the "Scenes" menu
- Rename "Project" to "File"
- Rename menu item "Quit to Project List" to "Close Project..." (no change to action). Also move the menu itme up the list, under "Project Settings..."
- Add a new menu item "Exit" to the end of the menu - the action is to close the application, which is just the old closebox action.

The action for the project editor window close-box should be changed to use the Close Project... action rather than closing the application.

That's it really. No real impact on existing users but less confusing for new/casual users.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

Don't know, but doubt it. However its mostly tweaks to existing resources

**Is there a reason why this should be core and not an add-on in the asset library?:**

It rearranges existing functionality. There's not really any new code, the existing close actions move around a little and the resource text changes. 

A variation would be to do away with the standalone Project Manager and be like QtCreator, where the list of projects and the way to create a new one is just a big subwindow hiding any open project and providing something to show initially. That's a bigger change but I do wonder if the Project Manager window disappears while you are editing a project to stop you selecting another project at the same time.

### PR DESCRIPTION
**Pull request by Calinou**
- Swap Scene and Project menus' locations.
- Rename the Project menu to File for consistency with other applications.
- Move the Exit option to the File menu (formerly Project).
- Rename references from "quit" to "exit" for consistency (including in the shortcut name).

This is a big workflow change, so we need to decide whether it's desired for 4.0 (and if so, to what extent).

This closes https://github.com/godotengine/godot-proposals/issues/645. (Quit confirmation dialogs when there are no unsaved scenes are no longer present in Godot 4.0, so the rest of the proposal is no longer relevant here.)

### Before

| Scene | Project |
|-|-|
|  |  |

### After

*Scene and File (formerly Project) have been swapped around, but the screenshot order here is inverted for easier comparison.*

| Scene | File (formerly Project) |
|-|-|
|  |  |

### CODE REVIEW

**Comment by lufog** [comment]
I would also remove `Current` from `Reload Current Project`. Because neither `Close Scene` nor `Close Project` contain it.

**Comment by akien-mga** [comment]
Renaming Project to File doesn't make much sense to me. I get the argument of consistency with other applications but those other applications are file editors. Godot is a project and scene editor. None of the options listed under File in the After screenshot are file operations.

We also tried swapping Scene and Project in the 3.0 development and after a few weeks @reduz reverted it. We can try again but I'm not convinced of the added value.

**Comment by Calinou** [comment]
> Godot's Scene menu is actually much closer to a File menu than Project.

The Scene PopupMenu's variable is called `file_menu`, so that was probably the original intent. I decided to follow https://github.com/godotengine/godot-proposals/issues/645 in the end though, which proposed renaming the Project menu to File instead.

**Comment by reduz** [comment]
We went over this a lot of times and ultimately this is what people feel most comfortable with, hence further attempts to change it keep facing resistance. Different persons have different views on this matter and what we have works, hence there is no reason to change it.

**Pull request closed without merging**
