### PR TITLE
[C#] Remove useless `isFirstEntry` and useless `source.Append("else ")`

### PR DESCRIPTION
**Pull request by ZerxZ**
PR https://github.com/godotengine/godot/pull/90687#issuecomment-2073792331

Even removing the else keyword does not affect program execution.

### CODE REVIEW

**Review by raulsntos — COMMENTED** [review]
Thanks, this is a good cleanup. Make sure to also remove the remaining excessive whitespace.

**Comment by ZerxZ** [comment]
> Thanks, this is a good cleanup. Make sure to also remove the remaining excessive whitespace.

Thank! I'll fix it right away.

**Review by raulsntos — APPROVED** [review]
LGTM. Thanks!

**Comment by ZerxZ** [comment]
> LGTM. Thanks!

Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Comment by ZerxZ** [comment]
> Thanks!

Thanks!

**Pull request merged**
