### PR TITLE
Include global class resources in Resource property inspector

### PR DESCRIPTION
**Pull request by vixelz**
Much like how script defined global classes can be created from the
"New Resource..." button in the FileSystem panel, this allows the
creation of script defined resources to be embedded.

### CODE REVIEW

**Comment by reduz** [comment]
looks good, i thought it was working already but i guess i may have been wrong

**Comment by akien-mga** [comment]
Thanks!

**Comment by hpvb** [comment]
Look at again for 3.1.2

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
