### PR TITLE
Add `compositor_free` branch in Compatibility scene renderer free function

### LINKED ISSUE #88861: GL Compatibility preview generation leaks `RendererCompositorStorage::Compositor` struct on exit
### Tested versions

- Reproducible in 4.3.dev (8eb34cb78bc2df3715cfdfcf4562bd36ddf91f7f)
- Not reproducible in 4.3.dev3 (36e943b6b)

### System information

Fedora Linux 39 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) () - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

When generating previews for a GL Compatibility project (after deleting `~/.cache/godot` to force recreating previews), a struct of type `RendererCompositorStorage::Compositor` seems to be leaked, with this message:
```
ERROR: 1 RID allocations of type 'N25RendererCompositorStorage10CompositorE' were leaked at exit.
```

This doesn't happen with Vulkan renderers.

CC @RandomShaper @godotengine/rendering 

### Steps to reproduce

- Delete Godot previews cache (`~/.cache/godot` on Linux)
- Create new GL Compatibility project
- Open it
- Close Godot, and see the error in the console

### Minimal reproduction project (MRP)

New project with GL Compatibility and `icon.svg`

### PR DESCRIPTION
**Pull request by clayjohn**
Fixes: https://github.com/godotengine/godot/issues/88861

See the equivalent code in the other renderers:
https://github.com/godotengine/godot/blob/bb6b06c81343073f10cbbd2af515cf0dac1e6549/servers/rendering/dummy/rasterizer_scene_dummy.h#L171-L173

https://github.com/godotengine/godot/blob/bb6b06c81343073f10cbbd2af515cf0dac1e6549/servers/rendering/renderer_rd/renderer_scene_render_rd.cpp#L1199-L1200

CC @BastiaanOlij

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Looks correct, you probably also need to add:

```
} else if (is_compositor_effect(p_rid)) {
	compositor_effect_free(p_rid);
```

It's a bit weird with these (including environment) as their implementation is in the base system but then the free logic is in each renderer.

**Comment by clayjohn** [comment]
@BastiaanOlij Done!

**Review by BastiaanOlij — APPROVED** [review]
lgtm

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
