### PR TITLE
Changes output window to be able to reduce height to half

### LINKED ISSUE #26392: Can't reduce height of output window in IDE
**Godot version:**
3.1 beta 8

**Issue description:**
I always wonder why minimal height of Output window is so large? 
I tried to make it smaller, but size is locked. 
Is it possible to make this locked minimal height smaller (at least twice)?

### PR DESCRIPTION
**Pull request by ankitpriyarup**
_Bugsquad edit_ : Fixes #26392

### CODE REVIEW

**Comment by akien-mga** [comment]
Does it make the default size smaller in a new project?

**Comment by ankitpriyarup** [comment]
Yes, I reduced the height of the output window to half. It makes it the new minimum height. It makes it default size as well in a new project I tested it on Ubuntu.

**Comment by akien-mga** [comment]
IMO the default size should not be changed, only the minimum size (so that you can reduce the size if you want, but by default it stays as it is currently).

**Comment by ankitpriyarup** [comment]
That would be better, I will keep that in mind and create another PR fixing this.
Thanks!

**Pull request closed without merging**
