### PR TITLE
Add Festival library as module to support speech synthesis (text-to-speech) #14011

### PR DESCRIPTION
**Pull request by malcolmhoward**
https://en.wikipedia.org/wiki/Festival_Speech_Synthesis_System
http://www.cstr.ed.ac.uk/projects/festival/ 
There was a mention of text-to-speech as a possible means of increasing accessibility in Godot for developers and application end-users who use screen readers (https://github.com/godotengine/godot/issues/14011).

I'm new to Godot engine (and C++) development, and this is my first attempt at creating a module.  I wanted to create something portable and bound to an external C++ library.  The docs suggested that modules can be zipped up to share with others (http://docs.godotengine.org/en/latest/development/cpp/custom_modules_in_cpp.html?highlight=external#creating-a-new-module), but the majority of the relevant examples in the source seemed to be significantly more complex than the example provided in the documentation.

Right now, this module works on Linux from the build created by scons and Qt Creator, but I haven't tried other operating systems or an export of a game.  I may need to add another folder for voices, since Festival needs at least one to use as a default, but I haven't yet looked into configuring the module's path as the appropriate directory.

I'd appreciate any feedback on this, and I hope that it can be helpful to someone.  Thanks to anyone who worked on the documentation, as well as the following posts for pointing me in the right direction!: https://www.reddit.com/r/godot/comments/85q04a/how_to_get_text_to_speech_set_up_in_godot_need/ & https://godotengine.org/qa/3475/how-to-link-external-library-in-custom-modules-scsub

### CODE REVIEW

**Comment by Sslaxx** [comment]
Careful with this. The voices that Festival uses all have wildly varying licenses and terms of use; some (if not most) of them may be problematic with Godot, even if the Festival library itself is MIT license compatible.

**Comment by mysticfall** [comment]
Thanks for the explanation. In that case, I'll probably use the API myself when I'll be implementing dialog features for my project.

**Comment by malcolmhoward** [comment]
You're welcome.  I'm working on porting this module to a GDNative plugin.  I'll post an update here when that's ready.

**Comment by aaronfranke** [comment]
@malcolmhoward What's the status of this? Have you ported this to a GDNative plugin?

I don't think this is worth having built into Godot. Any text to speech that has a decent amount of localization support would be a huge amount of code which would simply be bloat for most users. It's not suitable as-is due to submodules, hasn't been updated, and the author said he's working on making this a GDNative plugin instead. As such, I suggest closing this PR.

**Comment by akien-mga** [comment]
I missed that this PR was still open. That's indeed both too niche and too much code and dependencies to add in the core engine, GDNative was created specifically for such use cases.

The module can still be distributed in a thirdparty repo and linked e.g. in https://github.com/Calinou/awesome-godot for users who would want to compile it themselves, until a GDNative alternative is made available.

**Pull request closed without merging**
