### PR TITLE
changing the shape of Raycast for better understanding

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by asheraryam** [comment]
I'm curious, what is the new shape?

A screenshot would be nice too.

**Comment by Calinou** [comment]
Please make before/after screenshots to make the comparison easier :slightly_smiling_face:

**Comment by aitorCerecetoGlovoApp** [comment]
Oh damn. Sorry. This still not finished. I thought this was in my own view.

**Comment by aitorCerecetoGlovoApp** [comment]
Maybe you can help me for calculating the rotation relative to the start of the shape. Maybe using AABB or Basis?

**Comment by CereEnder** [comment]
The shape will be something similar to this: 
imagen

The problem I am facing is to do the extremes of the arrow to be rotated in the same direction as the point of the arrow.

**Comment by Calinou** [comment]
Note that this pull request was superseded by https://github.com/godotengine/godot/pull/46529.

**Comment by unsignedFoo** [comment]
Much better than my idea of implementation @Calinou ! I'll delete this branch tho

**Pull request closed without merging**
