### PR TITLE
Rename ParticlesMaterial to ParticleMotionMaterial

### LINKED ISSUE #5047: Rename ParticleMaterial to ParticlesProcessMaterial
### Describe the project you are working on

Various VFX and Godot

### Describe the problem or limitation you are having in your project

Process material is a confusing name. Especially if we add another particle-first material (https://github.com/godotengine/godot-proposals/issues/5046) it could get confusing very fast.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Rename ParticlesMaterial to ~~ParticleMotionMaterial~~ ParticlesProcessMaterial

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

see above

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It's the name of a resource in godot

### Is there a reason why this should be core and not an add-on in the asset library?

It's the name of a resource in godot

### PR DESCRIPTION
**Pull request by Mickeon**
Closes https://github.com/godotengine/godot-proposals/issues/5047.

As according to the original proposal, the reasoning for this PR is because its original name could be too vague, should there be more types of Particle-related materials in the future.

Also affects their file names and documentation.

### CODE REVIEW

**Review by clayjohn — COMMENTED** [review]
This should get an entry in the project converter. See for example, how the SpatialMaterial -> StandardMaterial3D was handled https://github.com/godotengine/godot/blob/4dbb6ecc214375e107427976c19206563a810a43/editor/project_converter_3_to_4.cpp#L1383

**Comment by Mickeon** [comment]
I suppose I should do something like that for [the other class getting a rename](https://github.com/godotengine/godot/pull/64370), too?

**Comment by jcostello** [comment]
Does it make sense to still call it material when it no refers on how the particle renders?

**Comment by Mickeon** [comment]
Please feel free to discuss it, especially in the proposal. I just did this to close something on the 4.0 milestone.

For me, it's still technically a "Material", as it affects the way particles are rendered, but **most especially**, it inherits from `Material`.

**Comment by fire-forge** [comment]
ParticlesMaterial not only affects particles' motion, but also their color, scale, and emission location, whereas ParticleMotionMaterial implies that it is only useful for motion related properties. So I don't think this is a good rename.

**Comment by jcostello** [comment]
> ParticlesMaterial not only affects particles' motion, but also their color, scale, and emission location, whereas ParticleMotionMaterial implies that it is only useful for motion related properties. So I don't think this is a good rename.

Can it be separated? Maybe you want particles what have same motions but different scale, color, emission, etc

**Comment by Mickeon** [comment]
Closing, as the original Proposal has been modified.

**Comment by YuriSizov** [comment]
Indeed this could've just been force-pushed on top of the existing PR, but no matter at this point. It's already superseded by https://github.com/godotengine/godot/pull/64566.

**Pull request closed without merging**
