### PR TITLE
Add context menu to visual script editor

### PR DESCRIPTION
**Pull request by Chaosus**
Adds a menu similar to the existing one in VisualShader:

vst_context_menu

### CODE REVIEW

**Comment by fire** [comment]
I think this is compatible with @Gallilus ’s change. need to look at it.

**Comment by fire** [comment]
@akien-mga I'm in favour of merging @Gallilus 's change first and then @Chaosus can rebase. https://github.com/godotengine/godot/pull/56252

**Comment by Gallilus** [comment]
I set 56252 back to draft gone try to solve some issues first.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
