### PR TITLE
Fixing wrong blending rect methods

### LINKED ISSUE #31124: Image::blend_rect might not blend as expected
Godot 3.1.1

**tl;dr**: `Image::blend_rect()` may cause transparent regions to darken, contrary to what you would get with a drawing app.

Explanation:

When trying to work on a painting app in which you can paint on transparent images using shaders and a transparent viewport, I got to deal with alpha blending. I tried blending a diagonal white-to-transparent-white gradient with the Godot icon, and quickly stumbled on the following problem:

Expected (Paint.NET):
image

Obtained (Godot):
image

Notice the darkened corner. From a pure math standpoint, it's just the result of averaging colors from the "invisible" pixels of the destination image, ending up darkening the gradient. But it may not be the expected result, at least to me it wasn't.
So I went bulldozer mode and blended myself in shaders, coming up with this:
```
vec4 blend_alpha(vec4 a, vec4 b) {
	vec4 res;
	res.rgb = b.a * b.rgb + a.a * a.rgb * (1.0 - b.a);
	res.a = b.a + a.a * (1.0 - b.a);
	res.rgb /= res.a; // THIS
	return res;
}
```
That last division did the trick.

But then, looking at `Image::blend_rect`, I noticed it does the same thing, *except the division*. So I tested it, and it has the same issue.

So is this really expected or should it be patched?

### PR DESCRIPTION
**Pull request by azagaya**
Using Color.blend function instead of custom code

Fixes #31124
Related to #37503. Im leaving both PR's cause i'm not sure what would you prefer.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Looks good. I am more comfortable with this than #37503. Its nice to know that the various blend functions are consistent.

Since it is core, this will still need reduz' approval.

**Comment by akien-mga** [comment]
Approved by @reduz:
```
15:50 <reduz> Akien: yeah makes sense
15:50 <reduz> this is correct blending including source and destination alpha
15:51 <reduz> I am unsure why GPUs as of today cant do it
```

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
