### PR TITLE
[Net] NetworkedMultiplayerPeer(s) renames

### PR DESCRIPTION
**Pull request by Faless**
Rename multiplayer peers:

- `NetworkedMultiplayerPeer` -> `MultiplayerPeer`
- `NetworkedMultiplayerENet` -> `ENetMultiplayerPeer`
- `WebRTCMultiplayer` -> `WebRTCMultiplayerPeer`

### CODE REVIEW

**Comment by fire** [comment]
I am curious what the reasoning is for the rename.

**Comment by Faless** [comment]
> I am curious what the reasoning is for the rename.

You mean `MultiplayerPeer` vs `NetworkedMultiplayerPeer`?

Well, first it's painfully long, second it doesn't have to be "networked" (ideally a `LocalMultiplayerPeer` could exist at some point). The others are just for consistency.

**Review by fire — APPROVED** [review]
These all look like find and replace renames.

@Faless gave reasoning and the reasoning makes sense.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
