### PR TITLE
Decimal entries in Inspector

### LINKED ISSUE #21874: Decimal entries in Inspector for numbers less than 1 now require a preceding 0.
**Windows 64-bit v3.1.alpha.custom_build.4b6846a**

Small quality of life thing.  In previous versions it was fine to enter say .7, and it would understand that as 0.7.  Currently if you do that, it will revert back to the previous number and cancel your entry.

decimals

### PR DESCRIPTION
**Pull request by ghost**
Decimal entries in Inspector for numbers less than 1 automatically appends 0 if user does not type it.
Fixes #21874

### CODE REVIEW

**Comment by avencherus** [comment]
Very appreciated.  X)  Looking good on my latest build wit this cherry picked, looking forward to it.

**Comment by akien-mga** [comment]
Why delete `editor_export.cpp`?

Please rebase to undo the last commit and squash the previous ones together. See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by nedimmuminovic** [comment]
> Why delete `editor_export.cpp`?
> 
> Please rebase to undo the last commit and squash the previous ones together. See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

I am still learning git workflow. File is deleted by mistake

**Comment by akien-mga** [comment]
You should be able to undo it with `git reset HEAD~1 editor/editor_export.cpp`.

Then your `git status` will show that a staged change is readding the file, while unstaged changes are the deletion (i.e. current state of your commit). You can drop the unstaged changes with `git checkout .`, and commit the staged ones with `git commit --amend`.

**Comment by akien-mga** [comment]
Or well in this case it's better to just do `git rebase -i HEAD~4` and drop unnecessary commits.

**Comment by nedimmuminovic** [comment]
git rebase -i HEAD~4
error: The following untracked working tree files would be overwritten by checkout:
        editor/editor_export.cpp
Please move or remove them before you switch branches.
Aborting
could not detach HEAD

**Comment by akien-mga** [comment]
Note that my 
> Or well in this case it's better to just do git rebase -i HEAD~4 and drop unnecessary commits.

was to replace the whole of https://github.com/godotengine/godot/pull/22065#issuecomment-421984388, i.e. you should not try to run `git reset HEAD~1` etc. as I suggested.

Here's what you could likely do now:
```
git checkout .
git reset HEAD
git rebase -i HEAD~4
```

**Comment by avencherus** [comment]
@akien-mga Oh my, what's the fate of this one?  I hope it makes it.

**Comment by akien-mga** [comment]
The original issue this attempts to fix is but one use of the `Expression` class, which is primarily intended to parse and execute code (and is also used in `EditorSpinSlider::_evaluate_input_text()` to evaluate math expressions.

I'm not against this fix, but we need to ensure that it doesn't cause issues with other use cases of `Expression` (like inserting zeros in `print("Hello.5World")`).

**Comment by akien-mga** [comment]
I went ahead and implemented a cleaner approach in #22590, based on how the GDScript tokenizer handles this feature (the diff is bigger than this PR but only due to some refactoring, the actual changes are only in https://github.com/godotengine/godot/pull/22590/files#diff-f2d9f2850c8de50eaa7a453335f629a9R1034).

Thanks for the PR though as it helped find the proper fix :)

**Pull request closed without merging**
