### PR TITLE
autocomplete logic attempt 2, fixes #10695

### LINKED ISSUE #10695: Autocomplete behaviour
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux 64 bits Godot [bd282ff](https://github.com/godotengine/godot/commit/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0)

**Issue description:**

if you delete a line and the cursor lands on a word in the next line, if you delete characters in the middle of a word and if you uncomment a line while your cursor is on a word the autocomplete popup will show.

**Steps to reproduce:**
little animated GIFs that demonstrates the behaviour:

- deleting a line
deleting a line

- uncomment a line
uncommenting a line

- editing middle of word
middle of word

What other editors do is something like (using qtcreator as an example):

- deleting a line
deleting a line

- uncomment a line
uncommenting a line

- editing middle of word
middle of word

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by tuga3d**
second take at autocomplete logic, using a TextOperation check.

### CODE REVIEW

**Comment by volzhs** [comment]
I guess autocomplete should be updated when deleting a letter too. isn't it?

```gdscript
func func_ab():
    pass
func func_abc():
    pass
```

autocomplete will show `func_ab` and `func_abc` if type `func_ab`
and show only `func_abc` if adding `c`
and should show 2 again if deleting `c`

**Comment by tuga3d** [comment]
@volzhs the list will be updated when deleting, but deleting will not trigger the popup to appear. In your example if you delete the `c` the list will update and show the 2 functions, but only if you already have the autocomplete popup open. If i make the deleting action trigger the popup, we will have the problem of deleting a line will trigger it.

**Comment by volzhs** [comment]
oh i see :)

**Comment by akien-mga** [comment]
The implementation looks good - did someone try it? Does the autocomplete behave as expected?

**Comment by hpvb** [comment]
I've tested the PR locally and it seems to do what it sets out to. This is certainly a nice improvement!

**Pull request merged**
