### PR TITLE
String.is_absolute_path now checks for two dots

### PR DESCRIPTION
**Pull request by Rubonnek**
The following:

```gdscript
print("res://../".is_absolute_path())
```
returns `True` without this patch.

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Is this right? Isn't a path like `/root/dir/../file.txt` _still_ absolute, as it _always_ refers to `/root/file.txt`?
I.e. a relative path is relative because it may change depending on your current working directory?

For example, Python's `os.path.isabs()` returns `True` for the above path ( `/root/dir/../file.txt`).

**Comment by Rubonnek** [comment]
I've always consider paths containing two dots to be relative paths -- perhaps I'm confusing it with another library I've used in the past.

Closing in favor of @mhilbrunner's comment. I wasn't aware Python considered such paths to be absolute.

**Comment by Calinou** [comment]
We may want to clarify this in the documentation. Any ideas on how to phrase this?

**Comment by mhilbrunner** [comment]
Well, the docs say
> If the string is a path to a file or directory, returns true if the path is absolute.

This can be improved by actually defining what `absolute` means in this case.
NodePath's docs are a bit better than String's on this, they say:
> Returns true if the node path is absolute (as opposed to relative), which means that it starts with a slash character (/). Absolute node paths can be used to access the root node ("/root") or autoloads (e.g. "/global" if a "global" autoload was registered).

In a similar vein, Python's docs state:
> Return True if path is an absolute pathname. On Unix, that means it begins with a slash, on Windows that it begins with a (back)slash after chopping off a potential drive letter.

**Comment by Rubonnek** [comment]
Following that thought, in Linux the description for the command line tool `realpath` in the manual page reads:

>Print the resolved *absolute* file name; all but the last component must exist

And for the GNU C Library, the description for the `realpath` function in the manual page reads:

>realpath()  expands all symbolic links and resolves references to /./, /../ and extra '/' characters in the null-terminated string named by path to produce a *canonicalized absolute* pathname

Both the CLI tool and the library call return a canonicalized absolute path, and I use both quite frequently but I tend to read the manpages for the CLI tools more often which is why I wasn't aware there was a difference between paths that were `absolute` vs paths that were `canonical`.

Perhaps we could define...

Relative paths as:
-  a path to a file or directory whose starting point is implicitly defined within the context it is being used. The starting point may refer to the current directory or the current `Node`.

Absolute paths as:
- a path to a file or directory whose starting point is explicitly defined in the path itself. This includes `res://`, `user://`, `C:\`, `/`, etc.

And canonical paths as:
- a path to a file or directory whose starting point may be implicitly or explicitly defined but whose elements from the starting point and up to the last file or directly are explicitly defined. That is, the path does not contain the parent directory string `..`.

Along this vein, we may also want to define `String.is_canonical_path`. 

Previously I also took a stab at implementing an equivalent of `realpath` in GDScript because it turned out very useful for an `EditorImportPlugin` I was working on and I've been thinking that function should be built-in as `String.get_real_path`.

Anyways, here the `realpath` equivalent I came up with:

```gdscript
#  Normalize the file p_path this file replace all `\`  and `//` to `/ `
static func normalize(p_path : String) -> String:
	var replacement : Dictionary = {
		'\\': '/',
		'//': '/'
	}
	for key in replacement:
		p_path = p_path.replace(key, replacement[key])
	return p_path

static func realpath(p_path : String) -> String:
	# Replace Godot-specific references
	p_path = ProjectSettings.globalize_path(p_path)

	# Normalize path
	p_path = normalize(p_path)

	# Check if the path began with a "/"
	var did_path_begin_with_forward_slash : bool = false
	if p_path.begins_with("/"):
		did_path_begin_with_forward_slash = true

	# Split the path so it's easier to manipulate
	var split_path : PoolStringArray = p_path.split("/")

	# If the OS is Windows (or UWP), the path may contain the DOS drive letter.
	var os_name : String = OS.get_name()
	var dos_drive_letter : String = ""
	if os_name == "Windows" or os_name == "UWP":
		dos_drive_letter = split_path[0]
		split_path.remove(0)

	# First pass: Dump all empty entries (i.e. all the "/" characters)
	var remove_index_queue : Array = []
	for index in range(0, split_path.size()):
		# Debug:
		#print(index, ": ", split_path[index], " : ", split_path[index].empty())
		if split_path[index].empty():
			remove_index_queue.push_back(index)
	for index in range(0, remove_index_queue.size()):
		var popping_index : int = remove_index_queue.pop_back()
		# Debug
		#print("Popping: ", popping_index)
		split_path.remove(popping_index)

	# Second pass: Dump all entries that include the current directory only "i.e. '.'
	for index in range(0, split_path.size()):
		if split_path[index] == ".":
			remove_index_queue.push_back(index)
	for index in range(0, remove_index_queue.size()):
		var popping_index : int = remove_index_queue.pop_back()
		split_path.remove(popping_index)

	# Third pass: Create upper directory chains and drop them accordingly
	var skip_index_count : int = 0
	for index in range(0, split_path.size()):
		if skip_index_count > 0:
			skip_index_count -= 1
			continue
		if split_path[index] == "..":
			# Queue drop the current path entry
			remove_index_queue.push_back(index)
			# Queue drop next path entries as long as they only refer to the
			# upper directory
			var next_index : int = index + 1
			while true:
				if next_index < split_path.size() and split_path[next_index] == "..":
					skip_index_count += 1
					remove_index_queue.push_back(next_index)
					next_index += 1
				else:
					break
			# At this point we've build a chain of indexes that contain ".." We
			# can use the difference between next index and the current index
			# values to determine how many upper directories we need to remove.
			for parent_relative_index in range(1, next_index - index + 1):
				if (index - parent_relative_index) < 0:
					# Do not try to remove paths that don't exist -- this is
					# how realpath behaves in Linux
					break
				remove_index_queue.push_back(index - parent_relative_index)

	# Sort the remove index queue before we start dropping directories
	remove_index_queue.sort()

	# Drop directories
	for index in range(0, remove_index_queue.size()):
		var popping_index : int = remove_index_queue.pop_back()
		split_path.remove(popping_index)

	# Fourth pass: reconstruct the final path
	p_path = ""
	for entry in split_path:
		if did_path_begin_with_forward_slash:
			p_path += "/" + entry
		else:
			p_path += entry
			# Toggle the flag to keep prepending forward slashes from now on
			did_path_begin_with_forward_slash = true

	# Fifth pass: (Windows & UWP only) - Reattach the DOS drive letter
	if not dos_drive_letter.empty():
		p_path = dos_drive_letter + "/" + p_path

	return p_path
```

**Comment by mhilbrunner** [comment]
Yeah, I agree that having a `canonical`/`realpath` equivalent would be useful.

**Comment by Calinou** [comment]
> Yeah, I agree that having a `canonical`/`realpath` equivalent would be useful.

Feel free to open a [proposal](https://github.com/godotengine/godot-proposals) for this :slightly_smiling_face:

**Comment by Rubonnek** [comment]
I'll work on it

**Pull request closed without merging**
