### PR TITLE
Update JavaScript/Java plugins to solve known vulnerabilities

### PR DESCRIPTION
**Pull request by tygyh**
*Production edit:* Done using the [Snyk](https://snyk.io/) tool.

Replaces #99120

### CODE REVIEW

**Comment by akien-mga** [comment]
What does Snyk mean?

**Comment by tygyh** [comment]
> What does Snyk mean?

It's a company/tool I use to generate vulnerability fixes. In #99120 each of the commits was generated by it, so I kept it in the title

**Comment by akien-mga** [comment]
Makes sense. I edited your commit to improve the commit message to be more explicit about what the commit does, and moved the Snyk reference to the body of the commit.

**Review by akien-mga — APPROVED** [review]
Seems ok to me if it passes CI.

For clarity, the security vulnerabilities in the JavaScript dependencies most likely don't affect Godot in any way, so this is just cosmetic / helping keep the stack up to date.
Those packages are used for linting and don't affect Godot itself.

Bouncycastle for the Android editor is slightly more relevant, though I don't think we're using affected APIs. Still, it's a cryptographic library so definitely worth updating if it has known vulnerabilities. CC @m4gr3d

**Review by m4gr3d — APPROVED** [review]

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first contribution! 🎉

**Pull request merged**
