### PR TITLE
Some performance tweaking of string handling

### PR DESCRIPTION
**Pull request by ghost**
Nothing important, but this might be interesting.

Of the 2 seconds it takes to start up an optimized build (I really checked my build this time) of Godot, roughly 40% of the time are spent in `String::c_unescape`:

startup-profile

While this is not a problem, I found a couple of points in `String` we might want to look at at some point. The effect of the following changes is reducing the startup time in `String::c_unescape` from 800 ms to 40 ms without touching `String::c_unescape` itself:

with-pr

This PR collects the things I found:

(1) `String::find` currently always triggers an expensive `_copy_on_write` on its `p_str` (it's not accessed as read ptr):

copy_on_write

(2) Calls to `String::replace` currently always produce deep copies. Yet if no replacement takes place (quite often), it's faster to just return a reference, i.e.:

```
	if (search_from == 0) {

		return *this;
	}
```

(3) `String::c_unescape` creates and destroys quite a number of temporary Strings (the patterns and replacements, 22 with each call); a new variant `String::replace(const char *p_key, const char *p_with)` removes this overhead:

copy_from

(4) It seems beneficial to add an explicit constructor for `String(const String &p_str)`; profiling suggests that this is another 30%.

Apart from that:

(1) A couple of calls pass `String`s, others pass `const String&`. It seems logical to change the whole interface to `const String&` (even faster than adding an internal `Vector` ref).
(2) `empty()` and `length()` might want inlining, as `Vector::size()` is also inlined and `empty()` and `length()` get called quite often, e.g. in `substr()`.

### CODE REVIEW

**Comment by poke1024** [comment]
Added a no-op special case for `String::substr` that happens quite often.

**Comment by poke1024** [comment]
Added no-op cases for `String::to_lower` and `String::to_upper` to avoid reallocations in code like here:

```
Color Color::named(const String &p_name) {
	if (_named_colors.empty()) _populate_named_colors(); // from color_names.inc
	String name = p_name;
	// Normalize name
	name = name.replace(" ", "");
	name = name.replace("-", "");
	name = name.replace("_", "");
	name = name.replace("'", "");
	name = name.replace(".", "");
	name = name.to_lower();
```

**Comment by akien-mga** [comment]
Thanks a lot, those are great improvements. `String` is pretty old and greatly in need of such reviews and performance enhancements :)

**Comment by AlmightyScientist** [comment]
@poke1024 What's the tool you used to profile the code execution please?

**Comment by poke1024** [comment]
@AlmightyScientist I'm on macOS and I use Xcode's Instruments, which you find under `/Applications/Xcode.app/Contents/Applications/Instruments.app`.

**Comment by AlmightyScientist** [comment]
@poke1024 Thanks for the answer :)

**Pull request merged**
