### PR TITLE
Some 2d editor enhancements

### PR DESCRIPTION
**Pull request by groud**
See #10375

### CODE REVIEW

**Comment by toger5** [comment]
I know I could just compile your branch...
But would you still provide gif's for a better demonstration? would like to know how the features look.

**Comment by groud** [comment]
Sure:
output

**Comment by groud** [comment]
Update ! :D
output

**Comment by reduz** [comment]
looks great!!

**Comment by toger5** [comment]
Nice! looks really promising.
Are the red/yellow outlines also introduced by this pr?

**Comment by groud** [comment]
> Are the red/yellow outlines also introduced by this pr?

No it's a gif encoding artifact

**Comment by groud** [comment]
SMAAAAAAART SNAAAPPPIING ! \o/
output
Damn... that was a pain to implement! (and not really done yet, seems like there are still some little bugs)

**Comment by toger5** [comment]
Dude your chnages make godot better than interface builder...

**Comment by Webzen92** [comment]
This is some sorcery shit, reported to github's admins for code abuse

**Comment by groud** [comment]
I reorganized the menus :)
output

**Pull request merged**
