### PR TITLE
Fixes infinite loop in GridContainer

### LINKED ISSUE #17389: Bug GridContainer when change columns property
**Godot version:**
3.0.2 Stable, Official

**OS/device including version:**
Linux, KDENeon

**Issue description:**
[Sorry for my english xd]
When change columns in my GridContainer the editor it freezes

**Evidence:**
You can see the bug here: https://youtu.be/x072q4W8ia0

**Minimal reproduction project:**
[Bug.zip](https://github.com/godotengine/godot/files/1798648/Bug.zip)
For reproduce only change in GridContainer the property "Columns" to 4

Only I tested in my PC I don't know if the same thing will happen in another.

### PR DESCRIPTION
**Pull request by groud**
Fixes  #17389

### CODE REVIEW

**Comment by garyo** [comment]
You may also want to look at my recent PR #17191 which is in this same code.

**Comment by akien-mga** [comment]
So which fix is better? #17191 or #17410?

**Comment by groud** [comment]
> So which fix is better? #17191 or #17410?

Both should be merged. ;)

**Comment by groud** [comment]
(Wait I was pretty sure I already commented about that, but my comment disappeared... weird)

**Comment by garyo** [comment]
Yes, as @groud says they're fixes for two different issues.

**Comment by hpvb** [comment]
Cherrypicked into 3.0.3

**Pull request merged**
