### PR TITLE
Add ParticleShader Userdata

### PR DESCRIPTION
**Pull request by reduz**
* Adds optional vec4 USERDATA1 .. USERDATA6 to particles, allowing to store custom data.
* This data is allocated on demand, so shaders that do not use it do not cost more.

Why 6 and not 4 or 8? Too many would add too many shader versions, too few is not enough for something @QbieShay and @Chaosus wants to do with visual particle shaders. If more are needed, more can be added.

~~This is **UNTESTED** (I will test later when I have a bit more time).~~ It' s now ready for review!

### CODE REVIEW

**Comment by Chaosus** [comment]
@reduz Looks awesome but I've detected a critical bug:
particles_bug
(I've rebased this PR to b3507ab0cdf25e470b1e4d977ed0bea32a305c1b)

**Comment by reduz** [comment]
@Chaosus I was able to test it and it seems to work now for me after some fixes. I think its ready for review now!

**Comment by Chaosus** [comment]
@reduz It still continues to emit the same error - although after reloading a scene it stops doing it.

**Comment by reduz** [comment]
@Chaosus It should be hopefully ok now.

**Review by Chaosus — APPROVED** [review]
Works fine and should be really useful for the visual shaders.

**Comment by akien-mga** [comment]
Thanks!

**Comment by QbieShay** [comment]
Tested today, works for me!

Thanks for the addition!

**Pull request merged**
