### PR TITLE
Bullet: Fix detection of concave shape in Area

### LINKED ISSUE #35854: Area doesn't detect ConcaveCollisionShape StaticBody
**Godot version:** 3.2 stable

**OS/device including version:**
Linux Mint 19.3

**Issue description:** Area doesn't detect collisions with ConcaveCollisionShapes created from Meshes.

Note that I create the collision at runtime, because then I don't have to recreate the Create Trimesh Collision in the interface every time I edit the .glb on Blender. It happens even if I create the trimesh manually, tho.

**Steps to reproduce:**
Download MRP, enable visible collision shapes, run Spatial.tscn scene.

Note that the ball does collide with the ConcaveCollisionShape, but the Area ignores it.

**Minimal reproduction project:**
[MRP.tar.gz](https://github.com/godotengine/godot/files/4144680/MRP.tar.gz)

### PR DESCRIPTION
**Pull request by Phischermen**
Added a new property to the Area class that can make Areas perceive concave shapes. It is useful for jumping/crouching systems.

*Bugsquad edit:* Fixes #35854.

### CODE REVIEW

**Comment by AndreaCatania** [comment]
In the previous PR I miss read the purpose of this PR, but hopefully now I reviewed the code and everything is more clear.

However, the `if (other_body_shape->isConcave())` was inserted to fix this issue #25419. Now that I'm re-checking this issue I'm realizing that I solved that issue not in the best way.
I don't remember exactly what the problem was with concave that make me add that IF statement; however, I would remove that IF, and try to solve the issue #25419 correctly.

Do you want to do it, (in case I'm available for help)? Otherwise I can give it a check.

**Comment by Phischermen** [comment]
Today I looked at the issue you referenced and downloaded the minimal reproduction project. I ran it with "perceive_concave" on and off, and in both cases it worked as I expected it to. I modified the project a little so that I could transform the area (which was using a cube shape) into the static body (which was using a concave shape). With perceive_concave off, the "body_entered" signal was not emitted. With perceive_concave on, the "body_entered" was emitted.

I haven't run into any instances where I received or did not receive the signal when I expected. I'm still working on setting up a stress test, to see if using multiple areas with perceive_concave on has a big impact on performance. I'll let you know what kind of results I get.

**Comment by AndreaCatania** [comment]
> I'm still working on setting up a stress test, to see if using multiple areas with perceive_concave on has a big impact on performance. I'll let you know what kind of results I get.

I prefer to not have this option at all and rather allows the volume to emit a signal when it detects a concave.

Is strange that you can't reproduce the issue reported here #25419, so I'll re-try it and in case we can completely remove the `if`.

**Comment by Phischermen** [comment]
> I prefer to not have this option at all and rather allows the volume to emit a signal when it detects a concave.

Gotcha! I'd be happy to strip the option and just enable detecting concave shapes - after I find out if I fixed my bug :)

I was able to set up a simple stress test, and my conclusion is that the bottle neck for areas is the number of overlapping shapes in an area, not necessarily what kind of shape the area is overlapping with. I think we could safely enable the detection of concave shapes without worrying about a performance impact.

**Comment by Phischermen** [comment]
I removed the property, and it is working correctly when set to Bullet Physics. It does not work in Godot Physics, but Godot Physics is somewhat deprecated from what I understand. Let me know if there's anything else I can do.

Here's the project I used for testing by the way:
[AreaStressTest.zip](https://github.com/godotengine/godot/files/3873480/AreaStressTest.zip)

**Comment by AndreaCatania** [comment]
Can be merged, @Phischermen Thanks!

# Volume optimization
From time to time this is a recurrent issue that I work on, this is the last test that I did: https://github.com/AndreaCatania/godot/commits/area_optimization_try2

In this version, the collision information are taken directly from bullet , but turns out that is equally bad and sometimes slower.

The main problem is related to the collision algorithm used. Currently it's using GJK that returns a lot of information not required by the areas.

This algorithm is really slow when it checks two overlapping bodies, and use this algorithm for the volumes (that are supposed to always overlap things) is not optimal.

My next iteration will be change this algorithm, I just need some free time.

**Comment by akien-mga** [comment]
Could you amend the commit message to be less verbose and more explicit on the *functional* change, instead of describing the code diff? I'm not familiar with the physics engine's internal but it would likely be something like "Bullet: Fix detection of concave shape in Area".

**Comment by Phischermen** [comment]
I amended the commit message. How's this:
"Enabled concave collision detection with Areas in Bullet"

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.1.

**Pull request merged**
