### PR TITLE
Fix issues in last GameControllerDB sync

### PR DESCRIPTION
**Pull request by akien-mga**
We don't support 'misc1' as an output string yet (seems used for PS5 controller).
Yet another broken CSV line with 'CO.,LTD' (will send fix upstream. *Edit:* https://github.com/gabomdq/SDL_GameControllerDB/pull/426).

---

@madmiraal Not sure what this `misc1` is but it seems to be for a new type of button on the PS5 controller, I guess we need to add support for it somehow? Maybe we can find Godot users with a PS5 to test. Before this PR the last sync would give:
```
ERROR: misc1:b12
Unrecognised output string: misc1                                                                                                                                                                                  
   at: parse_mapping (core/input/input.cpp:1245)
ERROR: misc1:b13
Unrecognised output string: misc1                                                                                                                                                                                  
   at: parse_mapping (core/input/input.cpp:1245)
ERROR: misc1:b13
Unrecognised output string: misc1                                                                                                                                                                                  
   at: parse_mapping (core/input/input.cpp:1245)
```

### CODE REVIEW

**Comment by offalynne** [comment]
misc1 is the mic button in this case, it differs per controller. see sdl source for a few more new fields (misc2 as well and paddles iirc)

**Comment by offalynne** [comment]
See http://hg.libsdl.org/SDL/rev/56b3a5c20eec and http://hg.libsdl.org/SDL/rev/8fe13a9ef824

**Comment by madmiraal** [comment]
It's been changed since [56b3a5c20eec](http://hg.libsdl.org/SDL/rev/56b3a5c20eec) which added `aux1`, `aux2`, `aux3`, `aux4`.

https://hg.libsdl.org/SDL/rev/e5e22d42f2e2 replaced `aux1`, `aux2`, `aux3`, `aux4` with `misc1`, `paddle1`, `paddle2`, `paddle3` and `paddle4`.

https://hg.libsdl.org/SDL/rev/0be349835d8e added `touchpad`.

**Comment by akien-mga** [comment]
@offalynne Maybe the header of `gamecontrollerdb.txt` should be changed to say:
```
# Game Controller DB for SDL in 2.0.14 format
```

Since the new identifiers were added in 2.0.14, so I assume they wouldn't work on earlier SDL versions or other engines that implement the same format from an earlier SDL version.

**Pull request merged**
