### PR TITLE
Convert en_GB spelling to en_US with codespell

### PR DESCRIPTION
**Pull request by akien-mga**
Breaks compat as it renames `AcceptDialog.cancelled` signal to `canceled`.

### CODE REVIEW

**Comment by Zireael07** [comment]
What do you want to be documented? Now I'm confused...

About compat breaking, can't this one word be excluded from codespell somehow? IIRC there IS such an option somewhere

**Comment by Faless** [comment]
> we could put "use british spelling" in there.

Well, technically it would be "use american spelling" (the conversion is GB -> US). #godexit 

I think this just "normalize" things given most of the codebase already uses the american spelling (e.g. `Color` not `Colour`), though it make sense to document.

**Comment by YuriSizov** [comment]
The source of it all: https://github.com/godotengine/godot-docs/issues/1066 (and there have been many PRs fixing British spelling since, both in docs and in code).

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
> Uh, didn't know this. Is this documented somewhere?

It isn't currently, but yes this should be documented both in the code style guidelines, and in the documentation writing guidelines.

> Also I'm a tiny itty bit worried about the compat breaking, but it's only one signal and we're not in a RC yet, so, not that bad, I just find the reason a bit... Frivolous?

I think it's worth doing at this stage. We strive for consistency in the API, and that includes fixing typos. It's easy enough to change code accordingly.
I added a rename for it in the 3-to-4 project converter.

**Pull request merged**
