### PR TITLE
Fix edge cases of object lifetime when signals involved

### LINKED ISSUE #73889: Godot.RC3 .. RC5: breaks `timer.connect()`, the program is stopped forever
### Godot version

v4.0.rc5.official [6296b4600]

### System information

Windows 19

### Issue description

After upgration to Godot.RC3 .. RC4 .. RC5 my plugin is broken.

I provide a function to wait for a function to provide an expected value.

As example it waits for function 'obj_value' from the instance `TestIterativeValueProvider` is providing null.
```
func test_foo(timeout = 20000) -> void:
	var value_provider := TestIterativeValueProvider.new(RefCounted.new(), 5, null)
	await assert_func(value_provider, "obj_value").is_null()
````
Now the execution stops at await and is not executed further

I have reduced the code as much as possible to find the root of the cause.
The problem occurs when using `timer.connect("timeout", _on_timeout)`.

### Steps to reproduce

run the attached example 

a) if you run `await assert_that().it_works()` the function is continue after the signal `done` is emitted
b) if you run `await assert_that().not_works()` the function is stuck
 --  b1) also strange when using variant (b) and remove the return type from the function `assert_that` it works too

### Minimal reproduction project

[timer_await.zip](https://github.com/godotengine/godot/files/10828504/timer_await.zip)

### PR DESCRIPTION
**Pull request by RandomShaper**
Includes #74056, which is very related, although not strictly necessary for fixing the bug, but this way conflicts are already solved.

The MRP didn't work because of two reasons:
- GDScript's ability to chain operations on temporaries was negatively impacted by #73448.
- `RefCounted` objects need to survive signal emission. In the MRP there's a chain of signals due to await completions and user signals that is able to end up unreferencing the object down to zero, because the script there is not doing all on a temporary object, and the engine must ensure such an usage works. The object will be eventually destroyed after the chain completes.
This PR addresses both. Therefore, the non-working case in the MRP now works and the working case keeps working. And that keeps being true even if the `return self` statements there are removed, which is important because in that case the bug happens as well but finding a different pathological signal-lifetime situation.

Given that the situation able to trigger the bug is quite an edge case (the MRP could just have put the object in a variable to ensure its lifetime) and the changes may have some risk of regressions, I think this fix can wait for the next milestone. 

Fixes #73889.

### CODE REVIEW

**Comment by vnen** [comment]
That is interesting. I'll keep in mind for review after 4.0 is out. For now I see it's incomplete, since the `{start,end}_statement` are not being called, but we can discuss how this should be done.

**Comment by RandomShaper** [comment]
Oh, I've missed including the compiler file in the commit. Thanks. Pushed.

That said, yes, let's leave this for after the 4.0-stable frenzy.

**Comment by vnen** [comment]
I think this is a good approach. I just don't understand the `statement_level` bit. There are no nested statements so this will always alternate between 1 and 0.

As another note, since no temporaries are meant to live across statements, we could add an assertion on `end_statement()` to check that there are not used temporaries at this point.

**Comment by RandomShaper** [comment]
The way I understood the code, `_parse_block()` can be recursively called. An option may be to call `end_statement()` before any line that recurses into `_parse_block()`.

**Comment by vnen** [comment]
Ah, I see. The way it is done now it may consider a block to also be part of a statement.

The only "problem" is that a temporary may live longer than it needs to. For instance, if the condition of `while` is temporary, it will only be released at the end of the block instead of right after the condition is checked.

> An option may be to call `end_statement()` before any line that recurses into `_parse_block()`.

This may not be so bad TBH, since `_parse_block()` is only called recursively in a few places. I guess it would also need a new `start_statement()` afterwards to balance the one at end of the loop.

Though there's the problem that #73963 tries to solve: the clearing of the temporary may be skipped because of the conditional jumps. Having this at the end of the block makes it a non-issue, but it also makes the temporary live longer than it needs to.

**Comment by vnen** [comment]
I do think this works fine for all cases. Could not think of a situation where it would cause problems.

**Review by vnen — APPROVED** [review]
Thanks!

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
