### PR TITLE
Added scons tool to run black automatically during the build

### PR DESCRIPTION
**Pull request by dmoody256**
Runs black automatically on the git changeset, and only if the files have changed since the last time it ran.

### CODE REVIEW

**Comment by Calinou** [comment]
I would prefer switching to a more established tool with https://github.com/godotengine/godot/pull/46235.

**Comment by dmoody256** [comment]
> We already have a pre-commit hook for black: https://github.com/godotengine/godot/blob/master/misc/hooks/pre-commit-black

How do I make that work automatically?

**Comment by Calinou** [comment]
> How do I make that work automatically?

Follow the instructions in the [documentation](https://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html#pre-commit-hook). In short, you need to copy all the files from the repository's `misc/hooks` to your local `.git/hooks/` folder located at the repository root.

**Comment by dmoody256** [comment]
> > How do I make that work automatically?
> 
> Follow the instructions in the [documentation](https://docs.godotengine.org/en/stable/community/contributing/code_style_guidelines.html#pre-commit-hook). In short, you need to copy _all_ the files from the repository's `misc/hooks` to your local `.git/hooks/` folder located at the repository root. When you make a commit, the pre-commit hooks will run automatically. Use `git commit --no-verify` to skip pre-commit hooks if needed.
> 
> Switching to [pre-commit](https://pre-commit.com) would make this step easier, since you'd only have to run `pip3 install --user pre-commit && pre-commit install` at the repository root to get started. Partial commits are also handled automatically by pre-commit.

The pre-commit hook did not run on my new files in the ninja tool pr https://github.com/godotengine/godot/pull/52793, is that intended?

**Comment by YuriSizov** [comment]
Not sure why a pre-commit hook didn't run for you, but it should, so there is no reason for this enhancement. Drop by the contributors chat if you need help figuring your issue out. Thanks for your contribution nonetheless.

**Pull request closed without merging**
