### PR TITLE
[WIP] Add a crash reporter that sends to generic crashpad server.

### PR DESCRIPTION
**Pull request by fire**
## Why
As discussed on the irc development channel, this provides a crashpad uploader that works for both the editor and exported projects. I've provided this pull request for review.

The below settings are configured to work with sentry.io which is self-hostable or we can use their cloud services at https://sentry.io/for/open-source/

This changeset is inspired by Blender's crashpad implementation https://developer.blender.org/D3576

Regarding consent: The crash reporter asks every crash for consent to upload.

> It’s an unfortunate truth that any large piece of software will contain bugs that will cause it to occasionally crash. Even in the absence of bugs, software incompatibilities can cause program instability.

> Fixing bugs and incompatibilities in client software that ships to millions of users around the world is a daunting task. User reports and manual reproduction of crashes can work, but even given a user report, often times the problem is not readily reproducible. This is for various reasons, such as e.g. system version or third-party software incompatibility, or the problem can happen due to a race of some sort. Users are also unlikely to report problems they encounter, and user reports are often of poor quality, as unfortunately most users don’t have experience with making good bug reports.

> Automatic crash telemetry has been the best solution to the problem so far, as this relieves the burden of manual reporting from users, while capturing the hardware and software state at the time of crash.

> https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/overview_design.md

## Noted objections

* We're unable to deal with the number of crash issues on github, so more issues won't help. 

We're able to have an idea of the frequency and get the accurate state of the crashed program. So by using a crash reporter we can triage the crashes by frequency and priority.

The merged crash report in sentry is able to be ignored and merged to avoid duplication of developer effort.

* Consent and privacy

Each upload has a consent to upload form. (yes/no). Sentry.io strips indentifying information. https://docs.sentry.io/learn/sensitive-data/

* Off unless configured

The person providing the build or exporting a projects needs to configure the handler executable and the crashpad submission url.

* Security

> Crashpad may be used to capture the state of sandboxed processes and it writes minidumps to disk. It may therefore straddle security boundaries, so it’s important that Crashpad handle all data it reads out of the crashed process with extreme care. The Crashpad handler takes care to access client address spaces through specially-designed accessors that check pointer validity and enforce accesses within prescribed bounds. The flow of information into the Crashpad handler is exclusively one-way: Crashpad never communicates anything back to its clients, aside from providing single-bit indications of completion.

https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/overview_design.md#security-considerations

* Privacy

> Crashpad may capture arbitrary contents from crashed process’ memory, including user IDs and passwords, credit card information, URLs and whatever other content users have trusted the crashing program with. The client program must acquire and honor the user’s consent to upload crash reports, and appropriately manage the upload state in Crashpad’s database.

> Crashpad must also be careful not to upload crashes for arbitrary processes on the user’s system. To this end, Crashpad will never upload a process that hasn’t registered with the handler, but note that registrations are inherited by child processes on some operating systems.

https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/overview_design.md#privacy-considerations

* Avoiding spam

Crashpad by default only reports one crash per hour.

## Changes

* Add a function that will crash the engine.
* Add Breakpad project config variables for the server and handler location.

godot windows tools_2018-10-05_12-04-47

* Add video driver, Godot version and product name to be sent as annotations.
* Move defaults to project settings and use globalize_path.
* Add Google's crashpad to thirdparty folder.
* Add a confirmation dialog to Crashpad crash report uploading.
* If the handler or url config is empty, do nothing.
* Use a global static variable to disable crash reporting because the crash exception handler is a static function.
* Create scons options for crashpad_url and crashpad_handler_path

To compile your own engine:

```
scons p=windows vsproject=yes crashpad_url=https://sentry.io/api/1275580/minidump?sentry_key=ce8ff763e5ef4a0fae8fc1f2837b996d -j8
```

Then, open this project in the editor and run it on Windows:

[godot-sentry-crash-reporter.zip](https://github.com/godotengine/godot/files/2452369/godot-sentry-crash-reporter.zip)

It will crash.

crash reporter_2018-10-05_12-04-03

This project is exportable. I was able to abuse the gdnative export capabilities to put the crashpad_handler.com beside the exported project so the crash reporter will work for exported project. https://drive.google.com/a/chibifire.com/uc?id=1Z8odT9ZhJI9iB44_pwglkfcxNQn4rh7Z (Godot only reports once per hour)

## How to generate syms for upload to sentry.io:

https://github.com/google/breakpad/blob/master/src/tools/windows/binaries/dump_syms.exe
https://github.com/getsentry/sentry-cli/releases/

```ps1
.\dump_syms.exe godot.windows.tools.exe > godot.sym
dos2unix godot.sym
.\sentry-cli-Windows-x86_64.exe upload-dif --org some_organization--project some_project -t breakpad .
```

This is an alternative way to upload syms for mingw applications:

```ps1
# https://github.com/rainers/cv2pdb/releases
.\cv2pdb.exe -C godot.windows.tools.exe godot.exe godot.pdb
.\dump_syms.exe godot.exe > godot.sym
dos2unix godot.sym
.\sentry-cli-Windows-x86_64.exe upload-dif --org some_organization--project some_project -t breakpad .
```

## Web interface

Stacks can be easily shared (edited): 

* https://sentry.io/share/issue/0b694ce533604454b26a995d9e86c15d/
* https://sentry.io/share/issue/da7379c377c04cefb21e324be65e6570/

There is a web interface that can merge reports.

chrome_2018-10-05_15-12-06

chrome_2018-10-05_15-01-37
chrome_2018-10-05_15-01-50

### CODE REVIEW

**Comment by fire** [comment]
Todo:

* Mac, and Linux implementation rather than being Windows only
* Split the crashpad configuration variables into editor and project for the url and path.

**Comment by LikeLakers2** [comment]
image

I don't think we need to extract *everything* from upstream...

**Comment by fire** [comment]
1134 files is only 6.98 megabytes, so it's mostly uncompressed source code .

**Comment by fire** [comment]
godot windows tools_2018-10-06_23-12-24

Modified the configuration settings to be more explicit and add obvious off switches rather than depend on empty urls.

**Comment by samgreen** [comment]
Just want to say, I fully support this and I think this will be a huge win for Godot developers. Thanks for the effort!

**Comment by hpvb** [comment]
I am very much against adding native support to Godot by default for a non-free (as in freedom) and non-free as in paid-for service.

I really, really, really do not want this in Godot Git.

**Comment by dcramer** [comment]
Hey ya'll. David from Sentry. Let us know if there's anything we can be of help on with this.

**Comment by fire** [comment]
@dcramer Hi Sentry, thanks for the framework, I was wondering if it was possible for people to submit comments and an email. It may not be possible to save the email, but wanted to leave the possibility open. 

This patchset uses the crashpad system.

I had trouble creating a system that generates syms from a mingw godot engine. My prototype was a system that runs https://github.com/jon-turney/google-breakpad under Wine. Alternatively, https://github.com/rainers/cv2pdb works but doesn't run under wine / linux.

**Comment by groud** [comment]
I agree with @hpvb on this one. I am against merging if we have any pointer to a commercial product.

The Godot engine organisation is a charity, we are not meant to advertise for any commercial service.

**Comment by groud** [comment]
> If I may provide a counterpoint for the sake of debate: Our source code is hosted on GitHub, which is also a commercial service. Travis CI and Appveyor, which we also use in the production of Godot, could both also be considered commercial services. Yet I see no complaints about the project using Github, Travis CI, or Appveyor. Sentry.io would just be another one on top of that list in order to help the production of Godot, not as an advertisement for the product.

I agree on the reasoning behind. But the fact is, according to the discussions I remember on IRC, that not everyone was ok to add crash report to our workflow. IIRC, most people were against it because:
- A crash report by itself is not useful. If users do not provide feedback explaining what they were doing, without any reproduction steps, crash reports are almost useless.
- We already have too much work to do with the issues on Github.

So if I still record correctly, we agreed that the feature could still be implemented for users. So that games in production can focus on their bugs. A situation where I would not like to have a pointer to Sentry.io directly in our code, because that would be an advertisement for their service.

Also, if we still want to add this to the Godot engine development workflow, I think it is still not the same. Sending our users data to a proprietary service is not the same as using a platform for our developers only.

**Comment by dcramer** [comment]
I assume y’all know this, but Sentry isn’t just a random third party service - were fully open source as well  lhttps://github.com/getsentry/sentry - and crashpad/breakpad are industry standard at this point. I’d be interested in how we can help Godot users enable a Sentry workflow, which is how I stumbled upon this issue. Definitely get you don’t want to couple things to our SaaS service, but as long as you support a variable DSN (or minidumps endpoint specifically) you’re supporting any Sentry installation.

**Comment by hpvb** [comment]
@dcramer thank you for your offer to help! I think we'd like to run our own endpoint on Godotengine.org and then adding this feature would be great. I don't know how hard it is to actually run an endpoint though but I'll give it a go. If you could be available to answer questions should I mess something up that'd be great.

**Comment by fire** [comment]
https://github.com/getsentry/sentry-kubernetes makes setup look easy, but I'm not sure the difficulty of vm based setup.

**Comment by dcramer** [comment]
@fire its not super hard, but I'd def suggest use saas if you can. Also: https://sentry.io/for/open-source/

**Comment by hpvb** [comment]
@dcramer it's very important in my opinion that we do not hardcode any sentry.io addresses in any artifacts we ship. Then there's the issue of privacy etc with us just shipping data generated by our users to a third party. We may even have to have some kind of dialog to have people agree to YOUR ToS, in Europe there's the GDPR thing also.

In short, the software looks great but the SaaS option really isn't an option as far as I'm concerned.

**Comment by workless** [comment]
I've personally set up a sentry at work on aws, the guides and the installer works great but still it requires maintenance, why can't the project use saas at least for **editor only**?

**Comment by dcramer** [comment]
My advice:

- ask people if you can submit crash reports
- use our saas service (if nothing else because it’s free)
- allow override of the DSN so it’s not coupled to saas

**Comment by samgreen** [comment]
I see that this PR *already* comes with a setting override, and it defaults to blank. To that end, none of the arguments about privacy, GDPR, or data security actually matter if the *default is blank*

**Comment by fire** [comment]
Spring cleaning! Updated to latest Godot Engine master.

**Comment by fire** [comment]
https://github.com/getsentry/sentry/blob/master/LICENSE 

Sentry became NOT opensource during the period of this pull request. I'll be closing the pr after a research period.

**Comment by dcramer** [comment]
@fire whats the concern? you're still able to freely host it yourself if that's what you're after.

**Comment by starry-abyss** [comment]
I thought this PR used a standard protocol, and only address was set up to sentry?

**Comment by fire** [comment]
Ah yes, https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/overview_design.md#Upload-to-collection-server its been a while since I last looked at this code That said there are open source crash pad collectors.

**Comment by fire** [comment]
I've been investigating https://gitlab.com/glitchtip as an opensource alternative to Sentry. No results yet.

**Comment by API-Beast** [comment]
It would already be incredibly useful to simply have things like the stacktrace be logged to the log file. That way when a user reports a crash I can ask them for the log file, without automatically uploading anything. Is that something that could reasonably implemented?

**Comment by fire** [comment]
For whatever reason there is a lack on consensus on this feature. This crash reporting pr is salvageable. There has been no movement for two years.

Remaining tasks:

1. Make Godot crash reporting support as many platforms as possible. Support Mac, Windows and Linux.
2. Working out Glitchtip integration

**Comment by ePirat** [comment]
At VideoLAN we wrote [CrashDragon](https://code.videolan.org/videolan/CrashDragon), a custom, somewhat minimal crash report server implementation.

That said, even without this being enabled at all it would be useful for people that want to gather crash reports for their games, be it with Sentry or other Breakpad/Crashpad compatible solutions…

**Pull request closed without merging**
