### PR TITLE
Add 'Create Folder' button in Install Project dialog

### LINKED ISSUE #25454: Installing projects in a folder that doesn't exist
**Godot version:**
3.1 beta

**OS/device including version:**
GTX 1060 6GB on a Ubuntu 18.04

**Enhancement description:**
Installing projects in paths that don't exist should create the path on request. 

**Steps to reproduce:**
Install a project in a folder that doesn't exist. Godot refuses to create this folder on this own or at least ask to create it.

### PR DESCRIPTION
**Pull request by twaritwaikar**
Fixes #25454

### CODE REVIEW

**Comment by IronicallySerious** [comment]
I first went in the direction of creating a new UI element for installing the project but I later found out that there is already an element like that that we can use, so this PR eventually got reduced to a line change. 
Open for suggestions!

**Comment by IronicallySerious** [comment]
Screenshots for reference:
image
image

**Comment by akien-mga** [comment]
Please squash commits together, the second one completely obsoletes the code added in the first one.

**Comment by IronicallySerious** [comment]
@akien-mga Squashed the redundant commits

**Comment by akien-mga** [comment]
You also rebased an unrelated commit in the process it seems. Try `git rebase upstream master` to fix that. (Provided you added an `upstream` remote pointing to `godotengine/godot`).

**Comment by IronicallySerious** [comment]
Rebased the branch, now only my own changes are up

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
