### PR TITLE
Add type icons to Project Settings, Array, and Dictionary editors

### LINKED ISSUE #56916: Selecting Callable or Signal in Array and Dictionary editor crashes the editor
### Godot version

v4.0.dev.calinou [846c14eee]

### System information

Windows 10, Vulkan

### Issue description

The Array and Dictionary editors in the Inspector allow you to select from any data type when adding a new value. Callable and Signal are incorrectly included in that list, and when you click on one of them, the editor window closes instantly.

### Steps to reproduce

* Write `export var array: Array` in a script
* Edit the array in the Inspector
* Add a new value and open the type selector
* Click on Callable or Signal

This happens to Dictionary too.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by fire-forge**
This PR adds type icons to the Array editor, Dictionary editor, and Project Settings, and adds a plus icon to the "Add Key/Value Pair" button in the Dictionary editor.

image
image
image

### CODE REVIEW

**Comment by fire** [comment]
I am not sure about removing the icons for callable and others. Need to check if it breaks anything.

**Comment by fire-forge** [comment]
I removed the Callable and Signal types from the lists because selecting them causes strange bugs. If you select them in the Dictionary/Array editor it crashes the engine. If you add a Callable or Signal property in Project Settings, the property is created but doesn't appear. Since Callables and Signals are created through scripts, I don't think having them be selectable would be that useful anyways.

**Comment by fire-forge** [comment]
Alternatively, I could add new EditorProperty types for Callable and Signal that show the function/signal name. They would be similar to the RID EditorProperty in that they can't be edited in the Inspector but still display information (in case the exported Array/Dictionary's default value includes a Callable or Signal).

**Comment by akien-mga** [comment]
I would suggest splitting this PR in two as it does two fairly separate changes. Maybe keep this one for the implementation of type icons (which looks good as is), and make a new one for the handling of Callable and Signal specifically.

For Callable and Signal, I think it would make sense to add support for them especially so that they can be viewed in the remote scene tree and in the debugger. That would indeed require implement `EditorPropertyCallable` and `EditorPropertySignal`, similarly to what we have with `EditorPropertyObjectID`.

**Comment by fire-forge** [comment]
Thanks for the feedback. I'll remove the code that handles Callable and Signal in this PR and I'll open a new PR for `EditorPropertyCallable` and `EditorPropertySignal` later.

**Review by akien-mga — APPROVED** [review]

**Comment by fire-forge** [comment]
The `bug` and `crash` labels can be removed from this PR too because it no longer fixes a bug.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
