### PR TITLE
Add snap toggles/menus and coordinates toggle to the 3D viewport toolbar

### PR DESCRIPTION
**Pull request by guzzard**
- button to toggle between global and local coordinates
- buttons to enable/disable translation, rotation, scaling snap
- menus to quickly set common snap values
- remove "Use Snap" in Transform menu, and add check button for snap translation, rotation, scaling
- added simple validation of snap configuration window values
- added icons for the new buttons that look different from the tool buttons, to not confuse users

### CODE REVIEW

**Comment by reduz** [comment]
have a screenshot? :P

**Comment by guzzard** [comment]
Video showing the changes: https://youtu.be/pTm1JnmgFEU

**Comment by reduz** [comment]
Wow, this is really really cool! Great job!

For the sake of consistency I would change the following

1) Move these to between the mode icons (move, rotate, scale, etc) ad the
menus (Edit, Transform)
2) Implement the same features in the 2D engine, as to where it's possible
of course ( I guess just translation and rotation snap)

**Comment by guzzard** [comment]
Thanks @reduz! :-)

1. Where would you like me to put the menus/buttons? No.1 or no.2?
pic


2. Yes, I can look into the 2D viewport toolbar next week or so. Don't have any time this week to work more on this unfortunately.

**Comment by reduz** [comment]
Oh, I guess 2.
No hurry, we are still finishing the small batch of features, hoping to
release something like an alpha next with with a lot of luck

**Pull request closed without merging**
