### PR TITLE
Fixed antialiasing option for Polygon2D with concave/hollow shapes

### LINKED ISSUE #34568: Additional lines drawn when using draw_polygon
**Godot version:** Godot 3.2 Beta 3/4

**OS/device including version:** Windows 10

**Issue description:**
There are additional lines when drawing a concave polygon, that were not there in Beta 2 and all previous Godot versions

**Steps to reproduce:**
Draw a shape with a cutout shape inside it as a single concave polygon.
Or run the attached repro project.
Try the same in beta 3 and beta 2 and compare the results.

**Minimal reproduction project:**
[bug_repro_proj.zip](https://github.com/godotengine/godot/files/3995787/bug_repro_proj.zip)

Screenshots of repro project in Beta 2
image
 And that same project in Beta 3 and beyond:
image

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
This change fixes an issue introduced in PR #33857:
Some cases were not handled properly for Polygon2D after making changes in common code to fix Line2D antialiasing. Added an option for drawing polygons to differentiate the two use cases.

Fixes #34568

### CODE REVIEW

**Comment by pouleyKetchoupp** [comment]
@insomniacUNDERSCORElemon This PR should fix all the newly introduced issues with my changes made in #33857

**Comment by akien-mga** [comment]
Some comments from IRC:
```
19:00 <Akien> reduz: WDYT of #34726 ? I'm not fond of adding yet another template for more defvals and another VisualServerCanvas optional argument that I'll have to drop when rebasing the vulkan branch, but I can handle it. It fixes a bug and it's important for 3.2 users to have somewhat functional AA IMO.
19:07 <reduz> Akien: no idea, does not seem super important to me to be honest, and the code will be gone in 4.0
19:42 <clayjohn> reduz: #34726 fixes a bug introduced by the AA fix. Right now concave shapes are drawn with a bunch of extra lines.
19:56 <reduz> clayjohn: i guess.. for 4.0 I just want to make sure we simply support MSAA in 2D instead of doing so many workarounds
20:33 <clayjohn> reduz: I agree.
20:44 <clayjohn> reduz, we still need to fix #34568, so we may need to just find a better solution.
```

There was no conclusion, but I do agree with @clayjohn that we need a fix for #34568 in 3.2, even if I'm not so keen on adding yet another argument to this method... But if that's the best solution, it should be fine for 3.2.

**Comment by pouleyKetchoupp** [comment]
I don't know if it's the best solution, but it's a simple one. I don't think anybody should spend more time finding a better solution if this is going to be dropped for 4.0 anyway.

**Comment by akien-mga** [comment]
Thanks!

**Comment by insomniacUNDERSCORElemon** [comment]
@pouleyKetchoupp Figured it might be more relevant to speak on this issue. I'm not sure if I will make an issue before you could fix it, but I decided to try more with vertex colors and noticed something that should make the issue even more easy to debug:

https://i.imgur.com/QVWOVu3.png

It isn't actually specific to convex models, just anything with a decent amount of internal vertices (just add ~~water~~ vertex colors). The AA seems to be respecting vertex colors (see how some lines disappear), so it just seems to be an issue with how the AA is interpreting the geometry.

I do agree on MSAA though, it's probably a better solution... although the tools in Godot (particularly for polygon2D vertex color)  aren't good anyways (not easy to do by hand) so isn't doing much damage. That's a shame though as an extra loop of faces is an effective way of faking face colors (like the simple eye in my image here, softness not visible until zoomed enough that the eye is in most of the screen).

**Pull request merged**
