### PR TITLE
Add editor setting for display mode on file dialog and filesystem dock

### LINKED ISSUE #2179: Godot doesn't remember the files view I choose
Whenever I open a scene or choose a texture file I need to choose I want to see my files as list again, instead of thumbnails grid. Godot seems not to remember my decision.

### PR DESCRIPTION
**Pull request by ghost**
Add a editor settings for choosing the display mode of EditorFileDialog, similar to the hidden folder setting.

Closes #2179.

### CODE REVIEW

**Comment by reduz** [comment]
nice, make it work for the filesystem dock too if you can :D

On Tue, Dec 15, 2015 at 1:43 PM, Franklin Sobrinho <notifications@github.com

**Comment by akien-mga** [comment]
Ping @neikeq as he was also working on this very bug IINM :)

**Comment by neikeq** [comment]
I didn't work on it because I still had doubts about what we talked on irc (project specific settings).

**Comment by TheHX** [comment]
@reduz, done, now it will work on FileSystem dock too.

**Comment by akien-mga** [comment]
It doesn't seem to work for me in the FileSystem dock. It always load with the "expanded tree" view, even though I quit the editor with the "list" view (not tree, just list of what is in the current directory).

**Comment by akien-mga** [comment]
Nevermind, I misunderstood the feature, I thought it would be saved automatically, but it has to be set in the editor settings :) Which is totally fine IMO.

**Pull request merged**
