### PR TITLE
Unexpose subclasses of ResourceFormatLoader and -Saver

### PR DESCRIPTION
**Pull request by akien-mga**
ResourceFormatLoader and ResourceFormatSaver are meant to be overridden
to add support for different formats in ResourceLoader and ResourceSaver.
Those should be exposed as they can be overridden in plugins.

On the other hand, all predefined subclasses of those two base classes
are only meant to register support for new file and resource types, but
should not and cannot be used directly from script, so they should not
be exposed.

Supersedes part of #29851.

### CODE REVIEW

**Comment by neikeq** [comment]
These classes are not exposed. They're only exposed if they are registered manually. The reason they appear in the docs and the GDScript editor is because they were never updated to check if classes are exposed.

**Comment by akien-mga** [comment]
They were registered manually by `GDCLASS`, and they could be accessed from GDScript.
```
var test = ResourceFormatLoaderBMFont.new()
```
is valid, but raises an error as the class cannot be instantiated.

**Comment by akien-mga** [comment]
Or do you mean that additional code should be added to DocData and GDScript to filter out classes added to ClassDB with `GDCLASS` but which are not registered explicitly in ObjectDB?

**Comment by neikeq** [comment]
> Or do you mean that additional code should be added to DocData and GDScript to filter out classes added to ClassDB with GDCLASS but which are not registered explicitly in ObjectDB?

Yes. Registered is not the same as exposed here. Classes that use`GDCLASS` are registered automatically in ClassDB the first time an instance is created, but they are not marked as "exposed" this way. You have to use `register_class`/`register_virtual_class` for it to be exposed.

You can use `ClassInfo::exposed` or `ClassDB::is_class_exposed(name)` to determine whether a class is exposed or not. GDScript and DocData were never updated to check this.

That's why `ResourceFormatLoaderBMFont.new()` is treated as valid. GDScript only checks if the class is registered, it doesn't check if it's exposed. Same goes for the doc tools.

**Pull request merged**
