### PR TITLE
Add a API to add/remove items to the "Tools" menu

### LINKED ISSUE #1429: Add a "Plugins" or "Tools" menu option
Since godot features can be extended by plugins, later the editor will have no space for plugin buttons. So please add a Tools menu option in the editor itself. So that all plugin developers can add their menu items(may be categorized) into it.

### PR DESCRIPTION
**Pull request by ghost**
Make possible add and remove items to the "Tools" menu.
The API is based on my [initial proposal](https://github.com/godotengine/godot/issues/1429#issuecomment-235047820) but i changed some things during the implementation:
- I removed the `has_plugin_menu_item`(I don't added it since other functions don't have it's `has_*` counterpart).
- All function were renamed to use `*_tool_*` instead of `*_plugin_*`, IMO this way it's clear that the functions are related to the "Tools" menu.
- The `int ID` parameter of `add_tool_menu_item` was changed to `Variant ud`, used for the callback function. 
- The callback format now is `callback(Variant ud)`, which made the code simpler and more flexible.
- The name format for the items, were changed from `"my_category/my_item"`/`"MyCategory/MyItem`" to `ANY string_Format/My Item Name` where the first slice is the item category, this way the name parameter is friendlier to translation(e.g. `"category/"+TTR("My Item Name")` or `vformat("categoty/%s", TTR("My Item Name"))`).

Closes #1429.

### CODE REVIEW

**Comment by akien-mga** [comment]
There are now merge conflicts, could you have a look @TheHX?

**Comment by TheHX** [comment]
Sorry for the delay, rebased to current master.

**Comment by akien-mga** [comment]
Sorry, merge conflicts again. I promise I'll have a look at it for merging then, nobody expressed any concern about the added feature.

Also note that your commits are not linked to your GH account, you might want to fix that too (or not, it's up to you).

**Comment by akien-mga** [comment]
Ping ;)

**Comment by akien-mga** [comment]
Rebased and merged it myself in e427ece. Please check it still works as intended in the current master branch :)

**Comment by akien-mga** [comment]
Alright, fixed for real with b24b52d.

**Pull request closed without merging**
