### PR TITLE
More threading in AssetLib

### PR DESCRIPTION
**Pull request by Faless**
AssetLib now uses thread as requested to download previews and ItemDownload

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Tested it, the editor doesn't completely freezes anymore. :+1:

**Comment by Faless** [comment]
> And you can't close the editor completely until killing the process if you visit it.

@YeldhamDev That's not my experience actually, did you try waiting a bit? It always closes for me, although it might take a while. I believe that's because Godot waits for threads to finish before exiting. What platform are you on?

**Comment by YeldhamDev** [comment]
@Faless
Manjaro Linux. And yes, I waited a full minute and nothing.

**Comment by hpvb** [comment]
Cherrypicked into 3.0.3

**Pull request merged**
