### PR TITLE
Additions to how the create node window handles custom types

### PR DESCRIPTION
**Pull request by Piet-G**
Made it so custom types that extend custom types can now show up under their parent in the Create Node window.

This is now possible:

custom_button

### CODE REVIEW

**Comment by akien-mga** [comment]
Is this still relevant after a3f1ee5c5 (https://twitter.com/reduzio/status/1018622630323261444)?

**Comment by mhilbrunner** [comment]
(Which probably corresponds to the changes here: https://github.com/godotengine/godot/commit/a3f1ee5c57d7818eaa30c272dd97d1bbb06ca099)

**Comment by DualMatrix** [comment]
I'm not super sure, but it seems custom nodes will be deprecated, in that case this won't be needed anymore.

**Comment by reduz** [comment]
I think this was superseded by my work an that of @willnationsdev, so closing. Still, thanks for taking the effort to do the contribution!

**Pull request closed without merging**
