### PR TITLE
Fix EditorSpinSlider in popups (fix `mouse_set_mode`/`mouse_warp_to_position`)

### LINKED ISSUE #57383: Drag operations on UI controls don't get cancelled properly in popups or floating windows (DisplayServer regression)
### Godot version

4.0.alpha.custom_build.01f5d7c61 (also in official alpha build)

### System information

Windows 11, Vulkan Clustered/Vulkan Mobile, Nvidia 1650

### Issue description

Drag operations don't get cancelled on LMB up or when RMB is clicked on popups or floating windows.

https://user-images.githubusercontent.com/18116695/151652621-52c854f2-6668-4481-b688-2e0b70731052.mp4

https://user-images.githubusercontent.com/18116695/151652630-4a0e2241-1cea-40a6-91fa-e027f8bf6c39.mp4

### Steps to reproduce

- Drag any control on sun/environment preview popup

Or

- Make the inspector a floating window
- Select a node and drag any control on the floating inspector window

### Minimal reproduction project

Empty project

### PR DESCRIPTION
**Pull request by Geometror**
Animation4

The EditorSpinSlider in the project and editor settings dialog is not working correctly on (presumably) all desktop platforms. On Linux the cursor gets teleported to the wrong position after using the Slider, the same happens on Windows with the addition that the cursor is captured indefinitely. This is because in mouse_set_mode/mouse_warp_to_position the window ID is hardcoded (except in the Windows implementation of mouse_warp_to_position), which results in unexpected behavior since the main window handle is always used. This is fixed by keeping track of the currently focused window and using its ID in these methods.

Fixes #57383.

Tested on Linux and Windows, but since I don’t have access to an Mac it would be great if someone could test it on that platform.

Originally this was a part of #57494 but I thought it would be better to split it up.

### CODE REVIEW

**Comment by Chaosus** [comment]
Would it fix https://github.com/godotengine/godot/issues/57383?

**Comment by Logharaa** [comment]
I confirm it fixes #57383 on Windows 10 👍

**Review by bruvzg — APPROVED** [review]
On macOS is seems to be working fine, incorrect mouse release position is fixed.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
