### PR TITLE
Direct3D 12: Let NIR runtime data and push constants use the same register scheme as bindings

### PR DESCRIPTION
**Pull request by RandomShaper**
Before this PR, the fixed space-register used for the NIR runtime data and root constants were not using the same multipliers the regular bindings have applied to. This seemed not to be a problem in practice, but was not as safe for "namespacing" the inputs of the shader as applying the same scheme to everything. This PR makes register usage consisten again.

### CODE REVIEW

**Comment by YuriSizov** [comment]
@RandomShaper Seems like we never added the D3D12 driver's folder to [codeowners](https://github.com/godotengine/godot/blob/master/.github/CODEOWNERS#L38). Would you mind adding this change to this PR while you're at it?

**Comment by RandomShaper** [comment]
> @RandomShaper Seems like we never added the D3D12 driver's folder to [codeowners](https://github.com/godotengine/godot/blob/master/.github/CODEOWNERS#L38). Would you mind adding this change to this PR while you're at it?

Submitted separately (#87574). I would've just added another commit to this PR, but I'm making thousands of D3D12 PRs today, so one more is no big deal.

**Review by clayjohn — APPROVED** [review]
Looks fine to me. I don't know how I could test and confirm that it works, so I will just trust you :)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
