### PR TITLE
Fix: json parser bug when extra data found after parsing

### LINKED ISSUE #19611: JsonParseResult return error=0 in some invalid JSON strings
**Godot version:**

3.1 dev compiled last week

**OS/device including version:**

Win 7,8 10 and probably all systems

**Issue description:**

**Using JSON class to import JSON from invalid JSON file can return a valid JSON text.**
Example:

**File:**   test.json
**Content:**   true, false, [1,2,3],

In every JSON validator the mistake is finded behind first "true"  (is expected to reach EOF after true and not ","):

https://codebeautify.org/jsonvalidator

Code to test in Godot:

```
var JsonText = "true, false, [1,2,3],"
var JsonError = JSON.parse(JsonText).error
if JsonError == 0:
  print ("This should be an error", but Json is imported in this way:")
  print (JSON.parse(JsonText).result)
 #This print´s "true", Godot ignores that there is text after true.
```

### PR DESCRIPTION
**Pull request by ThakeeNathees**
Fix: #19611

### CODE REVIEW

**Comment by akien-mga** [comment]
See also #25977 which aims to solve the same issue.

**Comment by ThakeeNathees** [comment]
Yeah, I was testing that and there is a little bug on that, removing length argument in calls and not checking if the index valid (`while(true)` instead of `while (index < p_len)`) will fail when the json string is empty (size is 0). because the `get_token()` tries to get the first char without knowing the string doesn't have one cause the below crash

```
[0] JSON::_get_token (C:\dev\godot\core\io\json.cpp:131)
[1] JSON::parse (C:\dev\godot\core\io\json.cpp:463)
[2] _JSON::parse (C:\dev\godot\core\bind\core_bind.cpp:3185)
[3] MethodBind1R<_JSON,Ref<JSONParseResult>,String const &>::call (C:\dev\godot\core\method_bind.gen.inc:1053)
[4] Object::call (C:\dev\godot\core\object.cpp:903)
[5] Variant::call_ptr (C:\dev\godot\core\variant_call.cpp:1222)
[6] GDScriptFunction::call (C:\dev\godot\modules\gdscript\gdscript_function.cpp:1100)
[7] GDScriptInstance::call_multilevel (C:\dev\godot\modules\gdscript\gdscript.cpp:1305)
[8] Node::_notification (C:\dev\godot\scene\main\node.cpp:63)
[9] Node::_notificationv (C:\dev\godot\scene\main\node.h:46)
[10] CanvasItem::_notificationv (C:\dev\godot\scene\2d\canvas_item.h:166)
[11] Node2D::_notificationv (C:\dev\godot\scene\2d\node_2d.h:38)
[12] Object::notification (C:\dev\godot\core\object.cpp:915)
[13] SceneTree::_notify_group_pause (C:\dev\godot\scene\main\scene_tree.cpp:990)
[14] SceneTree::idle (C:\dev\godot\scene\main\scene_tree.cpp:527)
[15] Main::iteration (C:\dev\godot\main\main.cpp:2026)
[16] OS_Windows::run (C:\dev\godot\platform\windows\os_windows.cpp:3176)
[17] widechar_main (C:\dev\godot\platform\windows\godot_windows.cpp:162)
[18] _main (C:\dev\godot\platform\windows\godot_windows.cpp:184)
[19] main (C:\dev\godot\platform\windows\godot_windows.cpp:196)
[20] __scrt_common_main_seh (d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[21] BaseThreadInitThunk
```
@akien-mga

**Comment by ThakeeNathees** [comment]
the following line of code just work fine but the len doesn't change so it looks like an infinite loop and confusing ( https://github.com/godotengine/godot/issues/19611#issuecomment-466137089 )
https://github.com/godotengine/godot/blob/20664419492c1e38a53963e2c32b4d027f5b8061/core/io/json.cpp#L128
may be this line works better?
```c++
while (index <p_len) { 
```

**Comment by akien-mga** [comment]
This has likely been superseded by later refactoring of the JSON parser, since #19611 is fixed in `master`.

**Pull request closed without merging**
