### PR TITLE
New RegEx library

### PR DESCRIPTION
**Pull request by leezh**
I've finally managed to port over the improved regex library and included a regex tester in the demo files. I'm not entirely sure how much of the script-side API I've changed but I tried to keep it as close as possible to ease the transition.

https://github.com/leezh/nrex

This was discussed in Issue #2230 and should fix most of the issues people had with the old trex library.

### CODE REVIEW

**Comment by punto-** [comment]
Looks good, I guess "match" and "find" do the same work internally so
there's no reason to call find when you don't care about the captures? (I
don't remember the difference, but I think find was just a true/false
return, while match would do the whole work to get the captures, etc).
Anyway I don't think a lot of code will break.

I'd love it of someone could test this on a big endian machine (I'll try on
our PS3 today maybe), but this is great. Thanks!

**Comment by FEDE0D** [comment]
Any info on positive/negative lookahead support for the lib?

**Comment by leezh** [comment]
I tried implementing it early on but I didn't like how it turned out. I could try and revisit it if you'd like.

**Comment by FEDE0D** [comment]
I was trying to parse a custom language using the RegEx class in Godot, but it just didn't work.
But I just found a workaround to the problem making the language more restrictive and using only string splits.
It would be nice to have the complete regex functionality working tough :smile:

**Comment by punto-** [comment]
Didn't we merge this patch a while ago? what is the question exactly?

**Comment by FEDE0D** [comment]
I'm asking for some missing features like full grouping support.

**Comment by leezh** [comment]
Adding lookahead was simple enough. Lookbehind on the other hand seems tricky. I'll see how far I can take it before making a new pull request with the updates.

In  the meanwhile, feel free to test it out here: https://github.com/leezh/godot/tree/nrex-update

**Comment by slapin** [comment]
How compatible it is to POSIX regex?

**Comment by leezh** [comment]
Going by [this page](http://www.regular-expressions.info/posix.html) and [this page](https://en.wikipedia.org/wiki/Regular_expression#Standards) it should be backwards compatible to the POSIX Extended Regular Expression with a few exceptions:

1. Alternations return the first match instead of the longest. Adding support for this gets in the way of minimising memory allocations.
2. POSIX defines the back-references to be limited to `\1` - `\9` while nrex goes all the way to `\99`. Results would be different if double digit back-references are used.
3. No support for POSIX character classes such as `[:alnum:]`. This one is something I do plan on adding at some point.

**Pull request merged**
