### PR TITLE
Added has_signal method for Object

### LINKED ISSUE #36196: has_user_signal() returns false while it should not
**Godot version:** 3.2 stable

**OS/device including version:** Windows

**Issue description:**
The function `has_user_signal()` from object always return false, even if a signal is declared in the given node.

**Steps to reproduce:**
- Create a node with a "my_signal" signal defined at the top
- Try to call `has_user_signal("my_signal")` on the node

**Minimal reproduction project:**
[HasSignalBug.zip](https://github.com/godotengine/godot/files/4201443/HasSignalBug.zip)

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
List of changes:
- Add `has_signal(signal)` method to `Object` (exposed to scripts)
- Add documentation for `has_signal(signal)`
- Clarify `has_user_signal(signal)` in documentation (only signals from `add_user_signal()`)

edit: fixes #36196

### CODE REVIEW

**Comment by capnm** [comment]
https://github.com/godotengine/godot/issues/9800#issuecomment-323600194
Same question. Why do we need x different functions to do (almost) the same?

**Comment by groud** [comment]
It would be great if this PR could be merged.
Note, it would solve #36196

**Comment by pouleyKetchoupp** [comment]
Done, I did some cleanup and tested on 4.0.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
