### PR TITLE
Revert "Allow parameters passed to GDScript functions to be nulled"

### LINKED ISSUE #37312: Statically typed function argument silently converted to null if the type doesn't match
**Godot version:**
3.2.1.stable.official

**OS/device including version:**
Arch Linux (installed `godot-bin` from AUR)

**Issue description:**
Static typing on function arguments can under some circumstances result in an argument silently being converted to `null` when the type doesn't match, rather than throwing an error.

**Steps to reproduce:**
```gdscript
tool
extends EditorScript

func _run():
	var bar = "hello"
	print("bar outside foo: ", bar) # prints "hello"
	foo(bar)

func foo(bar: Node):
	print("bar inside foo: ", bar) # prints "Null"
```
Just paste the above code into a new GDScript file and hit Ctrl+Shift+X to run it.

**Expected result:**
Because `bar` has no type, the error can't be detected at compile time. So I would expect an error at runtime like this:
```
bar outside foo: hello
_ready; Invalid type in function 'foo' in base '...'. Cannot convert argument 1 from String to Node.
```
Alternatively, the `bar` variable should have the `String` value of `"hello"` inside the function `foo`, as would happen if there weren't any type annotations present:
```
bar outside foo: hello
bar inside foo: hello
```
This would be a worse outcome than a clear error, but I could understand it from a performance point of view if dynamic types aren't checked at every possible occasion.

**Actual result:**
No errors are reported; the function is called successfully but the incoming argument is mutilated into `null`:
```
bar outside foo: hello
bar inside foo: Null
```

Interestingly, the error is reported correctly if I change the function to take `Array` instead of `Node`:
```
bar outside foo: hello
_ready: Invalid type in function 'foo' in base '...'. Cannot convert argument 1 from String to Array.
```

**Minimal reproduction project:**
Copy-pasting the one snippet above is sufficient.

### PR DESCRIPTION
**Pull request by ttencate**
This reverts commit f0efc7521e7302e60ebaab31a42fafd3ea2bda68.

Fixes #37312.

### CODE REVIEW

**Comment by akien-mga** [comment]
By reverting #26528, you'll reintroduce #26047, no?

**Comment by ttencate** [comment]
@akien-mga No, the error messages have improved considerably since then. See #37312.

**Comment by ttencate** [comment]
I'm guessing it's something to do with signals vs. function calls, but I can't for the life of me figure out how to hook up signals in the 4.0 way despite having read [Juan's update](https://godotengine.org/article/core-refactoring-progress-report-1). None of these work:

```gdscript
signal my_signal

my_signal.connect(self.handler) # Nope, the identifier "my_signal" isn't declared in the current scope
connect("my_signal", self.handler) # Nope, invalid get index 'handler'
connect("my_signal", self, "handler") # Nope, assigned type 'self' doesn't match the function argument's type (Callable)
connect("my_signal", Callable(self, "handler")) # Nope, "no constructor of 'Callable' matches the signature 'Callable(self, String)'
```

**Comment by ttencate** [comment]
I've already spent more time on this than I should have, and the rabbit hole is deeper than I expected.

I think having a confusing error message is much better than silently nullifying arguments, so in my opinion this PR is still an improvement over the status quo. But if everyone shared that opinion, the nullifying would never have been added in the first place.

I'll leave this PR open for discussion.

**Comment by vnen** [comment]
I think this is correct, we should revert the change. It should not silently convert the value to `null`. We need to find a way to improve the error message.

**Comment by vnen** [comment]
I just noticed that I was the one who merged this. I guess I didn't fully understand the consequences back then.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
