### PR TITLE
Fixed MenuButton signature inconsistencies 

### LINKED ISSUE #39497: Node and MenuButton _unhandled_key_input function signature inconsistency
**Godot version:**

 3.2.2.rc.custom_build.6c9b7c27d

**OS/device including version:**

 Any

**Issue description:**

I encountered a function signature inconsistency when working with `godot-headers` and writing some codegen against the `api.json`. here are the methods of interest:
```
Node._unhandled_input(InputEvent);
Node._unhandled_key_input(InputEventKey);
```

```
MenuButton._unhandled_key_input(InputEvent);
```
I found this after encountering a function overloading error developing my golang nativescript bindings. [Node](https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L2905)'s `_unhandled_key_input` accepts a `InputEventKey` type, but the [MenuButton](https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/scene/gui/menu_button.h#L45)'s version accepts an `InputEvent`. Was this intended? should the MenuButton version be renamed to `_unhandled_input` ?

The workaround is easy enough; use a different function name during code gen.
**Steps to reproduce:**
N/A

**Minimal reproduction project:**

N/A

Here's a short set of [discord messages](https://discord.com/channels/212250894228652034/342047011778068481/721066977942044792) discussing this issue

### PR DESCRIPTION
**Pull request by joshnix**
Fixes #39497 

Changed menu button override from `_unhandled_key_input` to `_unhandled_input`

### CODE REVIEW

**Comment by akien-mga** [comment]
Could you amend the commit message (with `git commit --amend`) to be more explicit? See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

**Comment by JoshMarshall756** [comment]
> Could you amend the commit message (with `git commit --amend`) to be more explicit? See https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind

Yes will do. Sorry for the mistake!

**Comment by JoshMarshall756** [comment]
@akien-mga Is the current state of the PR ok? Is there anything else that I should do?

**Comment by akien-mga** [comment]
The commits would have to be squashed into one (see [PR workflow]()).

But actually I don't think it's a correct change as is. All `_unhandled_key_input` definitions actually use `InputEvent` currently, not just `MenuButton`:
```
$ rg _unhandled_key_input.*InputEvent
editor/scene_tree_dock.cpp
74:void SceneTreeDock::_unhandled_key_input(Ref<InputEvent> p_event) {

editor/editor_audio_buses.h
94:     void _unhandled_key_input(Ref<InputEvent> p_event);

editor/plugins/node_3d_editor_plugin.h
741:    void _unhandled_key_input(Ref<InputEvent> p_event);

editor/plugins/animation_player_editor_plugin.h
201:    void _unhandled_key_input(const Ref<InputEvent> &p_ev);

editor/editor_help.cpp
59:void EditorHelp::_unhandled_key_input(const Ref<InputEvent> &p_ev) {

editor/plugins/node_3d_editor_plugin.cpp
5772:void Node3DEditor::_unhandled_key_input(Ref<InputEvent> p_event) {

editor/plugins/canvas_item_editor_plugin.h
457:    void _unhandled_key_input(const Ref<InputEvent> &p_ev);

editor/plugins/animation_player_editor_plugin.cpp
1207:void AnimationPlayerEditor::_unhandled_key_input(const Ref<InputEvent> &p_ev) {

editor/plugins/canvas_item_editor_plugin.cpp
474:void CanvasItemEditor::_unhandled_key_input(const Ref<InputEvent> &p_ev) {

editor/scene_tree_dock.h
195:    void _unhandled_key_input(Ref<InputEvent> p_event);

editor/editor_audio_buses.cpp
548:void EditorAudioBus::_unhandled_key_input(Ref<InputEvent> p_event) {

editor/editor_help.h
162:    void _unhandled_key_input(const Ref<InputEvent> &p_ev);

scene/main/node.cpp
2905:   BIND_VMETHOD(MethodInfo("_unhandled_key_input", PropertyInfo(Variant::OBJECT, "event", PROPERTY_HINT_RESOURCE_TYPE, "InputEventKey")));

scene/gui/menu_button.h
45:     void _unhandled_key_input(Ref<InputEvent> p_event);

scene/gui/menu_button.cpp
36:void MenuButton::_unhandled_key_input(Ref<InputEvent> p_event) {
```

The logic in `MenuButton`'s then handles events which may not be of type `InputEventKey`, so either it's bogus and actually never satisfies those checks, or `_unhandled_key_input` actually receives non-key events too.

**Comment by aaronfranke** [comment]
@JoshMarshall756 Is this still desired? If so, it needs to be [rebased](https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#the-interactive-rebase) and tested on the latest master branch. Additionally, the above feedback needs to be addressed. If it's not desired, this can just be closed.

**Pull request closed without merging**
