### PR TITLE
LSP: root_uri will fail to replace due to no uri_decoding #63388

### PR DESCRIPTION
**Pull request by A-Lamia**
correcting incomplete fix for #63388

### CODE REVIEW

**Comment by akien-mga** [comment]
This is starting to get confusing :D 

I think this flow might be worth rethinking a bit because with gradual changes like #63388 and its fixup #64099, and now this second fixup, we start losing the big picture.

A URI should be URI encoded, so IMO the URI decode should be done only when the file path is retrieved. I'm starting to think that both #63388 and #64099 are wrong and that the problem you were trying to solve was not properly understood.

CC @Razoric480

**Comment by A-Lamia** [comment]
the only other place to do it would be in `get_file_path()` this was supposed to be apart of the above commit you might be able to do. @akien-mga 

```cpp
String GDScriptWorkspace::get_file_path(const String &p_uri) const {
	String path = p_uri;
	path = path.uri_decode();
        String root_uri = root_uri.uri_decode();
	path = path.replacen(root_uri + "/", "res://");
	return path;
}
```

**Comment by A-Lamia** [comment]
@akien-mga let me know if this sounds correct.

**Comment by akien-mga** [comment]
Yeah I think sanitizing the two URIs in `get_file_path()` before doing the `replacen()` would be the right solution (at least from the basic understanding I have of how this code flows, I never really worked on it or with it :)).

**Comment by A-Lamia** [comment]
@akien-mga if root_uri is supposed to be encoded we wouldn't need to decode it directly we would do replacen with 2 encoded strings then decode path after. What do you think ?

**Comment by akien-mga** [comment]
Well isn't that what the original code would do before your first PR?

**Comment by A-Lamia** [comment]
> Well isn't that what the original code would do before your first PR?

Original code would set root_uri to an encoded uri in the if statement and in the else it would use workspace root none encoded path. Original get_file_path was expecting 2 encodes on replace that was part of the issue.

**Comment by A-Lamia** [comment]
after doing some reading and research it seems how the uri is formatted is client specific and not an LSP specification. neovim for instance does not use uri encodes but does use escapes for slashes.

knowing this i think encodes should be handled at initialization to keep consistency.

**Comment by A-Lamia** [comment]
@akien-mga I've tested this for a little over a week now with no issues so it should be ok for merge.

**Comment by akien-mga** [comment]
So this change by itself seems good to me, but what I'm still not sure of is whether we still need the other changes merged in #64099 to `GDScriptLanguageProtocol`.

**Comment by A-Lamia** [comment]
@akien-mga these are unrelated issues so yes, the old code results in `file://` on windows and that is incorrect if we append `file:///` then every other os that starts with a forward slash would be `file:////`.

**Comment by akien-mga** [comment]
I don't see why it would start with `file:////`?

The original code was this:
```
workspace->root_uri = "file://" + workspace->root;
```

On Windows with a `c:\some\file` URI, it would be `file://` + `c:\some\file` i.e. `file://c:\some\file` (possible with upper case C, or the semi colon encoded, but this is handled by this present PR).

On Linux/macOS with a `/some/file` URI, it would be `file://` + `/some/file` i.e. `file:///some/file`.

Am I missing something?

**Review by akien-mga — APPROVED** [review]
Looks good.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
