### PR TITLE
changes theme button name to edit theme

### LINKED ISSUE #12151: Theme button does not look like a button
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
MacOS 10.12.6, Godot 3.0 deefc2a

**Issue description:**

I was looking for how to edit the theme, and I didn't get it intuitively after poking around the interface. Only got a hint from [docs with screenshots of old UI](http://docs.godotengine.org/en/latest/learning/features/gui/gui_skinning.html).

image

The text "Theme" looks more like a label than a button/menu. Given that it's the only item on the whole row, I would expand it and have icon buttons for the submenus.

Intuitively, I was looking for something either in the Inspector panel or something in the toolbar of the scene:
image

### PR DESCRIPTION
**Pull request by AlexHolly**
Can anyone tell me how to add an icon?

How can I access this one? `editor/icons/icon_edit.svg`

`theme_menu->set_icon(get_icon(??, ??));`

image

closes #12151

### CODE REVIEW

**Comment by djrm** [comment]
@AlexHolly `get_icon("Edit", "EditorIcons")`, but you have to do it on a notification like 'READY or EDITOR_THEME_CHANGED (not sure if thats the one)', also i would suggest to add the "Theme" icon and making it a non flat button

**Comment by AlexHolly** [comment]
Looking good thanks.

image

**Comment by djrm** [comment]
also usually `..` is appended to menu buttons so `Edit theme..` would be even better

**Comment by AlexHolly** [comment]
image

**Review by djrm — APPROVED** [review]

**Comment by Noshyaar** [comment]
Could you also TTR around tooltip text? Thanks!

**Comment by akien-mga** [comment]
Merged manually as a9876869d with added `TTR()`.

**Pull request closed without merging**
