### PR TITLE
Visual Script construct node

### LINKED ISSUE #9067: Visual Scripting: Object Constructor Node
**Operating system or device - Godot version:**

**Issue description:**
It would be awesome to have a node to create objects. This is useful to use Godot’s file functionality. The GDScript code for this look something like this:

`File.new()`

the Node could look something like this:

constructorvs

**Steps to reproduce:**

**Link to minimal example project:**

### PR DESCRIPTION
**Pull request by swarnimarun**
Not complete yet but,

This should fix https://github.com/godotengine/godot/issues/9067

### CODE REVIEW

**Comment by fire** [comment]
Can you run clang-format? There are some errors.

**Comment by fire** [comment]
Instance should also add the entries to the list.

image

image

**Comment by aaronfranke** [comment]
@swarnimarun  Is this still desired? If so, it needs to be rebased on the latest master branch. Also, the above feedback should be addressed. Also, since this PR is a feature proposal, you should consider opening a [proposal](https://github.com/godotengine/godot-proposals/issues) which explains example use cases and how this approach will solve the problem.

Otherwise, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by swarnimarun** [comment]
I think this should be closed as I may not have time before finishing up on all the bugs to get to this.
And it pretty much needs a rewrite as per the new idea for implementation that I now have. So closing.

**Pull request closed without merging**
