### PR TITLE
TextEdit/LineEdit: Handle numpad when NumLock is disabled

### PR DESCRIPTION
**Pull request by neikeq**
A small request from the list on #2982:

> numpad arrow/home/end/pgup/pgdn should work as usual when numlock is off
> -- grigi

### CODE REVIEW

**Comment by akien-mga** [comment]
What about PageUp, PageDown; Home and End?

**Comment by neikeq** [comment]
Totally forgot those! :P
Should I rebase to merge both commits?

**Comment by akien-mga** [comment]
>  Should I rebase to merge both commits?

As you prefer, IMO it's fine like that two as both commits can work fine independently from one another, but it wouldn't hurt to have them merged either. Your call :)

**Comment by akien-mga** [comment]
LineEdit can also support Home and End: https://github.com/neikeq/godot/blob/a825cfd93288b4418f445cb1d8bfb4d4d2857f44/scene/gui/line_edit.cpp#L288

If you do a third commit, then yeah you can merge them ;)

**Comment by neikeq** [comment]
Right... I must have my head in the clouds :)

**Comment by akien-mga** [comment]
Looks good.

**Pull request merged**
