### PR TITLE
Exposes a way to retrieve the RPCMode of a given method or property

### PR DESCRIPTION
**Pull request by ghost**
There previously was no way to check whether a method or property had a RPCMode set, even though you were able to change it at runtime. This PR exposes two functions: `get_rpc_config` and `get_rset_config` which return the RPCMode of the given method/property name.

I'm open to any suggestion on how to improve the PR. My need of changing this arose while writing custom networking without using the High-Level API (I'd need to see the RPCMode for using my own handlers with the convenience of already having the syntax in place)

Tested on both 3.2 (da4eb7101d986af0ba6a15efaaed3dee77370d80) and master (20edf69f96160fcf7c0ea2449f4daf50f572ce99). 

Below is a simple demo project.
[Expose_RPC_Mode_Demo.zip](https://github.com/godotengine/godot/files/4370888/Expose_RPC_Mode_Demo.zip)

### CODE REVIEW

**Comment by andreyrk** [comment]
Travis threw an error while building the documentation, I assume I should use just `RPCMode` instead of `MultiplayerAPI.RPCMode` for the type? Although the documentation showed properly for me locally

**Comment by aaronfranke** [comment]
The source repo associated with this PR has been deleted, so this PR is no longer valid. Closing.

@andreyrk If this is still desired, you can open a new PR.

**Comment by Calinou** [comment]
@aaronfranke I can still see changes in the Files changed tab, couldn't it still be merged?

**Comment by aaronfranke** [comment]
@Calinou Not if the PR needs to be rebased/updated, especially if there are conflicting files.

**Pull request closed without merging**
