### PR TITLE
[doc] Fix a param name in DisplayServer's global_menu_add_multistate_item()

### PR DESCRIPTION
**Pull request by asmaloney**

### CODE REVIEW

**Comment by YuriSizov** [comment]
Heh, I noticed that one, but thought that it may be worth do get a few of those together. The ones that require changing the binding code lines as well as the docs.

**Comment by asmaloney** [comment]
😄 I mentioned it in #64331 - I just didn't want to forget it.

While we're talking about the binding stuff - we have mentioned at least three things that should probably be added to the [guidelines](https://docs.godotengine.org/en/latest/community/contributing/docs_writing_guidelines.html):

- `index` vs. `idx`
- `arg_name` vs. `argname`
- consistent use of `enable/disable` throughout (or `enabled/disabled` if you so choose)

The guidlines also need to be updated for `[param foo]` and `[constant bar]`.

**Comment by YuriSizov** [comment]
Yeah, guidelines and the BBCode reference need some updating to include a few of the newer things.

Regarding the naming standards, we'll need to discuss this with other maintainers to confirm the rules, though there was at least some support for moving away from shortened names.

**Comment by asmaloney** [comment]
> at least some support for moving away from shortened names.

Hopefully it will be more than _some_ support!

In the very first paragraph:

> Users come from all around the world. Some of them are young, and many aren't native English speakers. That's why we must all write using a clear and a common language.

😄

**Comment by mhilbrunner** [comment]
Closing, as this change already is in master/4.0. Thanks for contributing!

**Pull request closed without merging**
