### PR TITLE
Fixed crash when calling Type.new() with wrong number of arguments.

### PR DESCRIPTION
**Pull request by koalefant**
If .new() call fails engine crashes while accessing null pointer.

Repro is here:
https://github.com/koalefant/godot-bug-new-arguments

### CODE REVIEW

**Comment by akien-mga** [comment]
Hi and thanks for the PR, I'll try it asap.
For the sake of repo cleanness, could you try to run ```git rebase``` and then force push with ```git push``` to get rid of the "Merge branch 'master' ..." commit?

See http://codeinthehole.com/writing/pull-requests-and-other-good-practices-for-teams-using-github/#cleaning-your-history-optional for more tips about cleaning the history in PRs.
It's just a tip though, if you can't or don't want to do it, your PR is already good enough to be merged I think.

**Comment by akien-mga** [comment]
Would fix #2280.

**Comment by koalefant** [comment]
Awesome, thanks for the link to guide (going to be useful as I am new to git).
Will rebase in a moment...

**Comment by akien-mga** [comment]
Your change does seem to fix the crash, so that's definitely an improvement. The debugger does not seem to catch the error though, but the engine raises an error nevertheless which can be access in the "Errors" tab:
```
ERROR: _create_instance: Condition ' err.error!=Variant::CallError::CALL_OK ' is true. returned: __null
   At: modules/gdscript/gd_script.cpp:1475.
```
So that's a start :)

**Comment by koalefant** [comment]
Would you like me to figure out the debugger part as a part of this pull request as well?

**Comment by akien-mga** [comment]
If you have ideas out to do it, that would be awesome yes. But if you prefer to get this change merged and work on it in another PR, it would be fine too.

**Comment by koalefant** [comment]
Since I am new to the codebase this may take a while, so it may be more useful to have it in other PR.

**Comment by koalefant** [comment]
Added a rebased version: https://github.com/godotengine/godot/pull/2937
I guess this one could be deleted.

**Comment by akien-mga** [comment]
Thanks. Note that you could have kept the same branch and rebased it, the pull request would have been updated automatically.

**Pull request closed without merging**
