### PR TITLE
[3.x] Ensure node's area tree signals are disconnected when clearing monitoring, even if nodes are no longer in the tree.

### PR DESCRIPTION
**Pull request by madmiraal**
3.2 version of #41469.

### CODE REVIEW

**Comment by Yogoda** [comment]
Hello, is it possible to get this fix in 3.2.3?

**Review by akien-mga — APPROVED** [review]
Should be fine to merge as we merged the `master` counterpart without issue AFAICT.
A bit late now for 3.3 so let's merge for 3.4.

**Comment by Yogoda** [comment]
Is this still going into 3.4? Seems there is an issue with the merge

**Comment by akien-mga** [comment]
Indeed, it seems like I forgot to merge this after releasing 3.3.

This could be merged for the next 3.4 beta, it just needs a rebase.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
