### PR TITLE
Rename the ".mono" folder to ".godot/mono"

### PR DESCRIPTION
**Pull request by aaronfranke**
To be merged after (or alongside) #38607.

I tested this on a minimal project with one C# script and it works.

### CODE REVIEW

**Comment by neikeq** [comment]
This needs to be rebased and we must check if there were no new locations using `.mono/` recently. An example is Godot.NET.Sdk which must be updated too:

https://github.com/godotengine/godot/blob/72aaf81518253e25f28b3a23b5d3509e1264a5ad/modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/Sdk.props#L17-L19
https://github.com/godotengine/godot/blob/72aaf81518253e25f28b3a23b5d3509e1264a5ad/modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/Sdk.props#L24-L25
https://github.com/godotengine/godot/blob/72aaf81518253e25f28b3a23b5d3509e1264a5ad/modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/Sdk.props#L103-L110

**Comment by akien-mga** [comment]
Did you make sure that it works even if the `.godot` folder doesn't exist yet? (i.e. will the Mono code create `.godot/mono` recursively before attempting writing to it if it's missing)

**Comment by aaronfranke** [comment]
@akien-mga It does, even though I didn't explicitly code it to do that. In the import PR I had to code it to make `.godot/` explicitly.

**Review by neikeq — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by kilojool** [comment]
I've been experiencing some issues after this commit. The assemblies are placed in .godot/mono as they should, but when building the project it still looks in the old .mono folder.

[Test.zip](https://github.com/godotengine/godot/files/5321405/Test.zip)

[msbuild_log.txt](https://github.com/godotengine/godot/files/5321389/msbuild_log.txt)

**Comment by aaronfranke** [comment]
@kilojool This is because @neikeq needs to publish a new version of the `Godot.NET.Sdk` package.

> btw, once the PR is merged i need to publish the package here: https://www.nuget.org/packages/Godot.NET.Sdk
> btw, since not many people is using latest master anyway, if you prefer i can make the changes to the sdk in a new PR

In the future this will be done automatically and allow for offline builds.

**Comment by opl-** [comment]
Of course I happened to be part of the "not many people". Looking through Microsoft's documentation I was not able to figure out how to make my MSBuild use a local version of the Sdk, so my current (flawless) solution was to create my own, fake, local version of the NuGet package by hand. Obviously this is a silly solution, so for future reference, what is the recommended way of pointing a project at a local version of the Sdk for development?

(If for some weird reason you want to do what I did: For Linux, create directory in `~/.nuget/packages/Godot.NET.Sdk/4.0.0-local/` based on the `4.0.0-dev2` version found next to it, then link the `Sdk` directory inside to the `modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/` directory in your local Godot repository. Next, edit the `GodotSdkVersionToUse` constant in `modules/mono/editor/GodotTools/GodotTools.ProjectEditor/ProjectGenerator.cs` to `4.0.0-local` and rebuild the project.)

**Comment by neikeq** [comment]
C# should be working fine after #43029. It should also make it simpler to test changes to Godot.NET.Sdk before publishing it.

**Pull request merged**
