### PR TITLE
Add color option for img bbcode tag in RichTextLabel to tint images

### PR DESCRIPTION
**Pull request by pouleyKetchoupp**
*edit: changed to add a `color` option in `img` tag instead of a new tag `img-color`.*

Allows `RichTextLabel` to display an image with tint using a new option `color` in `img` tag.

~Allows `RichTextLabel` to display an image with tint using a new bbcode tag `img-color`.~

~It works the same way as the `color` tag, but only affects images. It was added as a separate tag to keep the expected behavior that `color` only affects the font color and images are not affected by color changes by default.~

bbcode = `Text with icon [img width=16]res://icon.png[/img]`

bbcode = `Text with icon[img width=16 color=#00FF00]res://icon.png[/img]`

### CODE REVIEW

**Comment by akien-mga** [comment]
Maybe this could be an optional parameter in [img] instead of a new tag?

**Comment by Calinou** [comment]
If breaking compatibility isn't an issue, we could make `[color]` affect images instead. I guess the concern was to have something cherry-pickable to the `3.2` branch, so we could have a separate PR with a dedicated tag there.

**Comment by groud** [comment]
> we could make [color] affect images instead.

I think this would be annoying to have to close a color tag just to have your icon to be displayed with the original colors. As it is kind of a corner case, I think I like @akien-mga's solution better.

**Comment by pouleyKetchoupp** [comment]
Thanks all for the feedback!

@Calinou If possible, I would rather not break compatibility and keep the two branches in sync, but my main concern is that I think intuitively you would not expect the font color to affect images too.

I agree the idea proposed by @akien-mga to have an optional parameter instead of a dedicated tag seems like a good compromise.

The syntax for images with color could be:
`[img color=<color>]{path}[/img]`
`[img=<width> color=<color>]{path}[/img]`
`[img=<width>x<height> color=<color>]{path}[/img]`
And it would be just a `Color` parameter added to image items, so the code changes would be much simpler than what I did so far.

**Comment by akien-mga** [comment]
I'd say the `size` parameter should probably be made explicit too as `[img=<width>]` is a bit weird currently. So:
```
[img size=<width> color=<color>]{path}[/img]
[img size=<width>x<height> color=<color>]{path}[/img]
```

**Comment by dalexeev** [comment]
Maybe `[tint={color}][img]{path}[/img][/tint]` or `[modulate={color}][img]{path}[/img][/modulate]`?

**Comment by pouleyKetchoupp** [comment]
@akien-mga Yes, I would rather keep this PR simple for now and have more involved syntax changes separated.

About changing the syntax:
The way image path & size is handled seems to follow some standard bbcode syntax:
https://www.bbcode.org/reference.php

So if we want to keep our syntax consistent with this reference we could add this version as an alternative to set the size:
`[img width=<width> height=<height>]{path}[/img]`

That said, we could use a custom syntax, but I don't know if it should be called bbcode if it's too different from the original version, to make sure it's not misleading to users.

**Comment by akien-mga** [comment]
I think we should aim to stay BBcode compatible as far as possible yeah, even though we do have extra tags that BBcode doesn't have (so it's more like "Godot Extended BBcode").

**Comment by pouleyKetchoupp** [comment]
Just pushed the changed to make color an option in `img` tag instead of a new tag.

Since I've added easier-to-use code to check for options in tags, I've also added `width` & `height` options to `img` as an alternative and updated the code handling built-in effects to use it too.

**Comment by pouleyKetchoupp** [comment]
I've pushed a little update on comments styling.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
