### PR TITLE
Fix Bezier Editor throwing error when adding key with Ctrl+Click

### LINKED ISSUE #87861: Adding a Keyframe with Ctrl+Click in Animation Bezier Editor throws error
### Tested versions

Reproducible in both 4.2.1 and 4.3.dev [9adb7c7d]

### System information

Windows 10

### Issue description

Inserting a key with ctrl+click in the Bezier Animation Editor throws the following error:
`core/object/undo_redo.cpp:345 - Error calling UndoRedo method operation 'bezier_track_insert_key': 'Animation::bezier_track_insert_key': Cannot convert argument 3 from [missing argptr, type unknown] to float`
InsertTrackThrowsError

### Steps to reproduce

1. Have a scene with an animation player and add a bezier track to it
2. In the Bezier view, Ctrl+Click to add a keyframe
3. Observe error in output

### Minimal reproduction project (MRP)

[AnimationTestProject.zip](https://github.com/godotengine/godot/files/14138748/AnimationTestProject.zip)

### PR DESCRIPTION
**Pull request by CookieBadger**
fixes #87861

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by CookieBadger** [comment]
I don't really know how cherry-picking works yet, but note that this code relies on the `make_default_bezier_key` method I added in the copy-paste PR #87250

**Comment by akien-mga** [comment]
Thanks for the headsup. That other PR likely won't be cherry-picked, so it might be worth making a dedicated backport of this PR for the `4.2` branch to fix the bug there, keeping the manually defined array.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
