### PR TITLE
Fix popups not longer stealing focus from MainWindow (Windows)

### LINKED ISSUE #37531: Focus problems with popup menus
**Godot version:**
b50387c8b

**OS/device including version:**
Windows 10

**Issue description:**
The new popup menus will unfocus the editor, which leads to problems like this
image
These buttons no longer get hover event (you can see that different button is hovered from clicked). Also you always need to click them to open the menu.

It seems weird to me that the popup menus are basically sub-windows. I mean, uncofusing editor on menu open... I don't know any other application that does that.

### PR DESCRIPTION
**Pull request by HaSa1002**
Fixes that the Popups no longer steal focus, when they are pop-uped. This
commit provides the general structure for the implementation, but only
the the Windows Display Server is implemented.

I need help in orrder to test how those changes affect the other displayservers.

~~The Big open ToDo is reimplementing unfocus behaviour, which turns out to be tricky (at least around 2 AM), since the Popups are always unfocused. I am general not so happy about the path I hacked together, but I think the alternative would be to have a WINDOW_POPUP flag, to tell the Displayserver to tell the OS to visually be it a popup (as implemented), but with focus support. I have no idea how to get there.~~

Sideeffect: The popup sets the no focus flag, since I believe it shouldn't be focused from the os point of view. However this likely breaks it across all other displayservers.

Partially fixes #37531 along with #37771

### CODE REVIEW

**Comment by guilhermefelipecgs** [comment]
> Sideeffect: The popup sets the no focus flag, since I believe it shouldn't be focused from the os point of view. However this likely breaks it across all other Displayservers.

What about using `set_transient(true)` instead of `set_flag(FLAG_NO_FOCUS, true)`?

**Comment by guilhermefelipecgs** [comment]
Nevermind, popup is already setted to be transient.

**Comment by HaSa1002** [comment]
From IRC:
```
[16:13:27] <reduz> HaSa: your PR is pretty good, I am still not entirely sure what the benefit is to have the popup not steal focus
[16:14:32] <reduz> as in, I think we can still fix the problem within the UI code
[16:14:58] <HaSa> It behaves similar to how other native programs show popups
[16:17:05] <reduz> yeah, I was thinking we can simply modify PopupMenu to search if another menu button is below, no matter the window, and just activate it.. similar to how the DND works
[16:17:22] <reduz> so we dont have to add more code to Window and DisplayServer
[16:18:36] <HaSa> Sorry, what is DND?
[16:18:48] <reduz> oh, apologies, I meant drag and drop
[16:19:40] <HaSa> The problem was, that you don't get input, if your popup is not stealing focus
[17:03:24] <HaSa> Ah found it https://www.codeproject.com/tips/751520/custom-context-menu
[17:16:22] <reduz> HaSa: yeah the problem is that supporting this makes the core API in godot more complex, I prefer to solve this issue in a bit diferent (even if more hacky) way
[17:18:48] <HaSa> Okay. I leave it as it is then. I am still interested in a working DisplayServer, but it isn't really the code I am familiar writing.
```

**Comment by HaSa1002** [comment]
Tried to rebase, but does not fix the issue anymore. Mouse moves sadly update the focus.

**Comment by HaSa1002** [comment]
superseded by #46464

**Pull request closed without merging**
