### PR TITLE
Add a `get_or_add` method to Dictionary

### LINKED ISSUE #7059: Add a `get_or_set_default` method to Dictionary
### Describe the project you are working on

A game with a lot of dynamic code.

### Describe the problem or limitation you are having in your project

I often find myself needing this pattern:

```gdscript
var value
if dict.has(name):
	value = dict[name]
else:
	value = default_value
	dict[name] = value
```

This code could also be written like this, but it involves accessing the Dictionary 3 times instead of 2:

```gdscript
if not dict.has(name):
	dict[name] = default_value
var value = dict[name]
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

I propose adding a method to handle this pattern. I'm not certain of what to call it, the best thing I can think of at the moment is `get_or_set_default`. I think this should be readable and convey what it does well.

Example use case:

```gdscript
func _ready() -> void:
	var dict: Dictionary = {}
	_add_to_array_in_dict(dict, "test1", "hi1")
	_add_to_array_in_dict(dict, "test1", "hi2")
	_add_to_array_in_dict(dict, "test2", "hi3")
	print(dict) # { "test1": ["hi1", "hi2"], "test2": ["hi3"] }


func _add_to_array_in_dict(dict: Dictionary, key: String, value: Variant) -> void:
	var array: Array = dict.get_or_set_default(key, [])
	array.append(value)
```

Without `get_or_set_default`, the `_add_to_array_in_dict` method would need to be 2 to 5 lines longer. The proposed `get_or_set_default` would also be naturally faster because it would be written in C++ instead of GDScript.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

https://github.com/godotengine/godot/pull/78095 Add a `get_or_set_default` method to Dictionary and expose it.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be worked around in a few lines of script, but it will be used often. At least, I am using it often. I have no idea how common this pattern is in other people's Godot games.

### Is there a reason why this should be core and not an add-on in the asset library?

It's very tiny and heavily related to Dictionary, so it would be most optimal to put it there.

### PR DESCRIPTION
**Pull request by aaronfranke**
Implements this proposal and closes https://github.com/godotengine/godot-proposals/issues/7059

### CODE REVIEW

**Review by ajreckof — APPROVED** [review]
The implementation is quite simple and in line with other dictionary functions. I'm just not sure about the name but I can't find a better one and python `setDefault` is even worse so this might be the best name😓

**Comment by RandomShaper** [comment]
My issue with `get_or_set_default()` is that it can be read as "get or set-default" and "get-or-set default." I'd say it's intended to be the former. `get_ensuring_default()` sounds better to me.

**Comment by aaronfranke** [comment]
I am good with either of the proposed names, none seems obviously better to me.

**Comment by RandomShaper** [comment]
Don't you like `get_ensuring_default()` more the more you read it? 😁

**Comment by AThousandShips** [comment]
I think `get_ensuring_default()` risks seeming like it always sets it, unsure how to state it clearly

**Comment by RandomShaper** [comment]
At this point I don't think the full behavior of the method can be summarized enough without leaving some thought to the user. In the defense of `get_ensuring_default()` I'll say that the "ensuring default," idea can't really mean anything else than "return if the key exists, otherwise set first," because there's already `set()`.

**Comment by Repiteo** [comment]
What about `ensure_key_then_get()`? This makes the order of operations clear, as you're retrieving the value at the specified key regardless; if the key already exists, you just get the stored value — if the key didn't exist, you ensure it does via a default value, then you retrieve said default value

**Comment by felaugmar** [comment]
Fixes https://github.com/godotengine/godot-proposals/issues/7059

**Comment by Iniquitatis** [comment]
How about `get_or_add` or something along these lines?

**Comment by RandomShaper** [comment]
> How about `get_or_add` or something along these lines?

I support that. Just let's be sure that `Dictionary`'s jargon has room for "add"; in other words, it's not already using "insert" or the like for the same meaning.

**Comment by ajreckof** [comment]
No function use either of them yet and doc use both even in the same sentence like so : 
image

**Comment by RandomShaper** [comment]
Maybe "insert" is more used in Godot containers in general.`

`get_or_insert()` then?

**Comment by SysError99** [comment]
We should instead use what similar languages were offering, in this case `set_default` is a great candidate since it's very similar to Python.

https://docs.python.org/2/library/stdtypes.html

If this PR gets merged successfully, I'll try to cherry pick this to 3.x

**Comment by ajreckof** [comment]
I really don't like the Python set_default as it is really unclear on what it does

**Comment by peterhoglund** [comment]
I read `get_or_set_deafault` as getting or setting the default. I also agree Python's `set_default` is bad since it doesn't explain what is happening. What about just `get_or_set`?

**Comment by aaronfranke** [comment]
@RandomShaper "Insert" is usually associated with some kind of order, like with [Array.insert()](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-insert), so I would prefer to not use that terminology here. This method does not affect the order, if anything is added then it always goes to the "end".

**Comment by RandomShaper** [comment]
Back to `get_or_add()`, then?

**Comment by peterhoglund** [comment]
Sorry, I didn't see `get_or_add()` was suggested. I like it since it's obvious what it does. `get_or_insert()` is equally good imo, but since get_or_add is shorter it wins for me.

**Comment by akien-mga** [comment]
The commit message also needs to be amended.

**Review by AThousandShips — APPROVED** [review]

**Comment by YuriSizov** [comment]
Thanks!

**Pull request merged**
