### PR TITLE
Added boolean generation method to RNG

### PR DESCRIPTION
**Pull request by Chaosus**
Added simple boolean generation function to RandomNumberGenerator called `randb` ~~and also boolean generation with probability ratio, named `chance `- I think this one will be very useful for diablo-like games where items should be dropped with different chances :)~~

### CODE REVIEW

**Comment by toasteater** [comment]
The `chance` functions: seems like they cast to double/float anyway so why not just `randd() < p_ratio`? 100 cannot perfectly divide PCG32's 2^32 range, so those modulo operations will introduce some bias on the upper end (well it's like 1/42949673 or something but still...)

**Comment by Chaosus** [comment]
Ah.. really ,then I 100% sure that @reduz will say that its simple enough for user to make it himself without adding such easy functionality to Godot. I better cut-off this function then, and leave randb alone

**Comment by Chaosus** [comment]
Closed - I start thinking that its not a good proposal - randb is not unique or complex function and just simple shortcut of

> rnd.randi() % 2

**Comment by Xrayez** [comment]
For reference, I've implemented `Random.condition` in goostengine/goost#31 as a property which mostly does similar thing, so I'd say it's not useless, at least it makes the code more readable. 🙂

**Comment by Calinou** [comment]
If you need a biased random boolean, you can also use the one-liner: `randf() > 0.4` (60% chance of being `true`).

**Pull request closed without merging**
