### PR TITLE
Documentation for WeakRef

### PR DESCRIPTION
**Pull request by CombustibleLemonade**

### CODE REVIEW

**Comment by eska014** [comment]
A popular practice is to store (a reference to) a `Node` in a `WeakRef`.Then, before calling any functions on the node, one can check `if weakref.get_ref() != null` to make sure the node wasn't already freed.

Maybe this should be mentioned, but I'm not sure if we should advocate this practice. It's kinda hacky

**Comment by akien-mga** [comment]
> Maybe this should be mentioned, but I'm not sure if we should advocate this practice. It's kinda hacky

I think it would be good to mention. @reduz has been describing several times to people having issues trying to access "previous freed instances" and getting crashes because of that.

**Comment by akien-mga** [comment]
@CombustibleLemonade Could you try to squash the two commits edff81c and e301ca3 together with ``git rebase -i HEAD~2`` (but keep the first commit separate)? If not it's no big deal, but it will be easier to cherry-pick for the 2.0 branch if the additions are in a single commit.

**Comment by CombustibleLemonade** [comment]
I tried that, but now it tells me I'm not currently on a branch. 


fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

**Comment by akien-mga** [comment]
Hm, strange. Nevermind it's not a big deal, let's merge as is :)

**Pull request merged**
