### PR TITLE
Use inline code for isinf with gcc versions <6.

### LINKED ISSUE #9166: [3.0] Godot fails to compile on Linux master a8e845a because of a core/math function
**Operating system or device - Godot version:**
Linux Ubuntu 16.04 64bits
3.0 master commit a8e845a474c01c4cde1416ed00e6ae456786c1fb

**Issue description:**
with the latest master 3.0 there is a compilation error, yesterday it was compiling O.K.

**Steps to reproduce:**
updated the code with git pull, try to compile as usual with scons platform=x11 -j 4
an error appears:
core/math/math_funcs.h: In static member function 'static bool Math::is_inf(double)':
core/math/math_funcs.h:123:21: error: 'isinf' was not declared in this scope

### PR DESCRIPTION
**Pull request by ghost**
Fixes #9166.

### CODE REVIEW

**Comment by akien-mga** [comment]
The current master branch builds just fine for me on GCC 5.4.0, so I think the issue might be something else.

**Comment by tagcup** [comment]
Not sure, Ubuntu might be custom patches.
We can ask someone familiar to try to dig into it to pinpoint the problem. But on the other hand, gcc major < 6 is a very simple test, and I don't think there is much harm in using the inline version of isinf in all gcc 5 builds.

**Comment by tagcup** [comment]
So what I'm trying to say is, I don't think this problem exists in gcc 6+, and the workaround we use (inline version of isinf) should work OK for any version of any compiler. So rather than spending time on pinpointing a compiler issue, we can use the workaround as a blanket fix for all potentially affected compiler versions.

**Comment by tagcup** [comment]
This might also be related to a particular old version of libc version too of course, but I don't imagine any distro would keep the old version of libc while upgrading to gcc 6+

**Pull request merged**
