### PR TITLE
 Add Python-style list comprehensions to GDScript

### LINKED ISSUE #2972: Add Python-style list comprehensions to GDScript
### Describe the project you are working on

Creating constant dictionaries, filtering and mapping arrays, conditional logic in array creation.

### Describe the problem or limitation you are having in your project

```gdscript
newlist = []
for x in fruits:
  if "a" in x:
    newlist.append(x)
```
this could be written in a single line like so:
```gdscript
newlist = [x for x in fruits if "a" in x]
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

As discussed in this [pull request](https://github.com/godotengine/godot/pull/15222) and this [issue](https://github.com/godotengine/godot/issues/4716), it isn't harder for people to read list comprehensions, even easier to read than multiple nested for loops.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```gdscript
newlist = [x for x in fruits if "a" in x]
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It will be used often

### Is there a reason why this should be core and not an add-on in the asset library?

This changes gdscript.

### PR DESCRIPTION
**Pull request by Lucrecious**
## Code Explanation
Hi, this is my first attempt at contributing to Godot!

I'm a fan of languages even though I've never done anything formal, but I decided to give this a shot with the little knowledge I remember from my favourite language classes in university.

Aside from a little clean-up, refactoring and figuring out a small bug, I think this is close to code-review quality.

To implement this I created a new `ForIfClauseNode` that gets recognized in the parser.

Here's the additional section to the language grammer I added logically to GDScript:
```ebnf
arrayDecl = "[" [ expression { "," expression } "," ] "]"
    | "[" [ expression forIfClauses ] "]";
dictDecl = "{" [ keyValue { "," keyValue } "," ] "}"
    | "{" [ keyValue forIfClauses] "}"
 ;
keyValue
    = expression ":" expression
    | IDENTIFIER "=" expression
    ;
forIfClauses = forIfClause { forIfiClauses } ;
forIfClause
    = "for" IDENTIFIER "in" logicOr { "if" expression } ;
```

The reason for the `logicOr` instead of an `expression` is so that the ternary operator doesn't get considered. This is sort of how the python one works as well, and I assume it's partly because of their ternary operator.

Here's python's for-if-clause:
```ebnf
for_if_clauses:
    | for_if_clause+
for_if_clause:
    | ASYNC 'for' star_targets 'in' ~ disjunction ('if' disjunction )* 
    | 'for' star_targets 'in' ~ disjunction ('if' disjunction )* 
```

Our syntax allows either for a for-if-clause or a comma separated list of expressions but not both.

This works for both `Dictionary` and `Array`.

The compiler essentially converts this
```gdscript
var array := [ expression_template for identifier in expression_range if condition ]
```
into this
```gdscript
var array := []
for identifier in expression_range:
    if condition:
        array.push_back(expression_template)
```

And it does something similar for dictionaries.

I have a test file written as well that tests a number of different scenarios. I plan for it to be more comprehensive in the actual pull request.

### Bug!
There's a bug that stems from my ignorance with the compiler, I'm hoping I'm missing something small.
```gdscript
prints('3x3 grid only diagonals:',[Vector2(x, y) for x in range(3) for y in range(3) if x == y])
```
This should print an array that looks something like `[(0, 0), (1, 1), (2, 2)]` but it only prints `[(0, 0)]`. I'm assuming this is a scope issue? But this also works in other scenarios. The code is very, very simple so I'm hoping the language gods can see what I'm missing.

### Building the Array or Dictionary
In the PR you'll see two ways I'm appending the template element to the array or dictionary.

With the array, I simply use the `write_call_builtin_type` which feels messy. I'm sure there's a cleaner way to do it.

With the dictionary, I created a new `OPCODE` that allows me to insert value into the dictionary. This seems like the way to go, but again, not sure and would like guidance here.

_Bugsquad edit: closes https://github.com/godotengine/godot-proposals/issues/2972_

### CODE REVIEW

**Comment by LightningAA** [comment]
FYI the commits should be squashed: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html#the-interactive-rebase. It doesn't really matter until the PR is ready for review though :)

**Comment by Calinou** [comment]
> This should print an array that looks something like [(0, 0), (1, 1), (2, 2)] but it only prints [(0, 0)]. I'm assuming this is a scope issue? But this also works in other scenarios. The code is very, very simple so I'm hoping the language gods can see what I'm missing.

Try with Vector2i instead of Vector2 to sidestep possible issues with floating-point precision.

**Comment by LightningAA** [comment]
```gdscript
var array := [ expression_template for identifier in expression_range if condition ]
```
This is the same as this, right?
```gdscript
var array := expression_range.filter(func(indentifier): return condition))
```

**Comment by Lucrecious** [comment]
> ```gdscript
> var array := [ expression_template for identifier in expression_range if condition ]
> ```
> 
> This is the same as this, right?
> 
> ```gdscript
> var array := expression_range.filter(func(indentifier): return condition))
> ```
> 
> If you need to modify it you could do:
> 
> ```gdscript
> var array := expression_range.filter(func(indentifier): return condition)).map(func(expression_template): return 2)
> ```

Yes! And honestly, with the addition of lambdas and these methods, list comprehension isn't really necessary. Every benefit I like about this is already what we get with the new GDScript.

I still like these and luckily, I only spent a couple of hours on this, so I'm cool abandoning this. I'm also cool working on it and including it if people actually want it.

**Comment by sairam4123** [comment]
Well, I feel like List comprehensions are readable more than filter and map functions, also please don't abandon this cool work, this is certainly desired by a lot of people, who come from Python.

**Pull request closed without merging**
