### PR TITLE
Hopefully fix the random crashes with threads

### LINKED ISSUE #21685: OS singleton not thread-safe when launched from the editor
Contrary to the [documentation](http://docs.godotengine.org/en/latest/tutorials/threads/thread_safe_apis.html), the OS singleton appears to be **not** thread-safe. And if that's the case, then possibly other things too.

Here is a simple test program I've made. Just create a new scene with Spatial main node, add a camera at (0, 2, 4), and run this code inside the Spatial:
```
extends Spatial

var thread = Thread.new()
var mymesh
var mi

func generate(size): # Runs in a thread and calls the main thread
	print("Generator thread started")
	for y in range(size):
		for z in range(size):
			for x in range(size):
				OS.delay_msec(1)
				call_deferred("addblock", x, y, z)
	print("Generator thread finished")

func _ready(): # Starts the generator thread
	thread.start(self, "generate", 20) # ALWAYS returns 0 due to a bug - so no sense checking

func addblock(x, y, z): # Adds a small cube at requested coordinates
	mymesh = CubeMesh.new() # Create a new mesh
	mymesh.size = Vector3(0.1, 0.1, 0.1)
	mi = MeshInstance.new() # Create a MeshInstance with this mesh
	mi.translate(Vector3(x/10.0,y/10.0,z/10.0))
	mi.mesh = mymesh
	add_child(mi) # Add this MeshInstance to the tree
```
If you run it several times, you'll see that half of the times the generator thread just dies halfway through. Interestingly, if I comment out the `OS.delay_msec(1)` call, then it works correctly - but since the whole cube gets built before you even see it, maybe the actual problem is related to something else?.. (Or maybe my code is incorrect, but I did it exactly like it says in the documentation - "calling OS is allowed, accessing the scene tree must be done via deferred calls".)

This issue exists in both Godot 3.0 stable and Godot master. I've [translated](https://github.com/godotengine/godot/files/2343065/test_godot2.zip) this code into Godot 2, and there it works correctly - there are other issues like graphical glitches and the first half of the cube getting built in a weird way, but the thread always finishes correctly.

### PR DESCRIPTION
**Pull request by santouits**
fixes #21685
possibly other random things too

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Will conflict with #30801, though if it does fix thread-related crashes...

**Comment by santouits** [comment]
> Will conflict with #30801, though if it does fix thread-related crashes...

To be honest I don't know if that check I put there helps with the fix, I just thought that it shouldn't be interacting with the debugger if it is a function running in a thread. The example in the issue stopped crashing after I added the lock in object.h, but I left that change too. I will see if it works without that check.

**Comment by santouits** [comment]
Alright it fixes the issue without that code. I removed it and it can be added in another PR, I think without it it will mess the debugger if you are on a breakpoint in the main thread and another thread keeps running.

**Comment by akien-mga** [comment]
For the reference, that's also what #28791 implemented (together with a new method).

Let's give this PR a spin (pun intended) :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Pull request merged**
