### PR TITLE
Add GDScript global yield-like "function": sleep.

### PR DESCRIPTION
**Pull request by willnationsdev**
This is 150-ish lines worth of parser magic so that

    yield(get_tree().create_timer(1), "timeout")

becomes...

    sleep(1)
    # or, if not executing in a Node class, pass in a SceneTree instance
    sleep(1, node.get_tree())

Don't know if that's a waste or not, but I've heard enough people on social media wondering why the heck GDScript doesn't support "such a basic feature" that I figured I'd add it. People evidently find it difficult to have to find (documentation issue) or difficult to use overall in comparison to the alternatives they find in other languages. This solves the second issue which consequently makes it more conventional, thereby reducing the need for the former issue.

### CODE REVIEW

**Comment by MidZik** [comment]
If you're going to do this I recommend against calling this function `sleep`. It doesn't pause execution, so the function that called the sleeper will continue running. This is different from what `sleep` does in other languages that support it. Something like `yield_seconds` would work better as an alias.

**Comment by willnationsdev** [comment]
@MidZik I'm confused. As far as I understand it, it does pause execution in the calling context. In my tests, I did...

    extends Node
    func _ready():
        while true:
            print("Hi")
            sleep(1)

And the node would only print once every second. So, it wasn't constantly printing "Hi" while some other context was yielding. It yields the current function, until the timer runs out (which results in the code suspending for N seconds, exactly what other languages do).

Am I just misunderstanding how this thing works?

**Comment by MidZik** [comment]
```
extends Node
func _ready():
	var result = get_result_after_wait()
	print(result) # prints [GDScriptFunctionState:1134]

func get_result_after_wait():
	sleep(1) # equivalent to yield(get_tree().create_timer(1), "timeout")
	return "result"
```

**Comment by vnen** [comment]
I feel wary of adding such thing. Ii can only be called from a Node and it needs to be on the tree. There's a potential for failure and I'm not sure if the error message will be clear. Even though most of scripts are attached to nodes, but it's not always the case.

**Comment by willnationsdev** [comment]
@vnen I see. Well, is there perhaps a valid implementation of `sleep` or `wait` that would actually do what people expect (I'm guessing writing something at the engine level and then exposing it as a global function in @GDScript or something). I had thought this was the right way to do it based on feedback I saw others give as advice, but if that's not the case, then...

**Comment by vnen** [comment]
If you want to pause the thread, you can call [`OS.delay_msec()`](http://docs.godotengine.org/en/latest/classes/class_os.html#class-os-method-delay-msec).

`yield(get_tree().create_timer(1), "timeout")` is already a shortcut (so you don't need to actually create a Timer node and it to the tree). I fear that hiding this context from the users will lead to confusion, especially if using `sleep` as the name. It's easier to detect why `get_tree()` fails when it's explicitly on userland code.

I'm also not fond of making the parser inject a bunch of instructions like that. It makes the parser more complex and more coupled with the engine API. And will likely mislead users in term of performance expectation (maybe not a big concern in a `sleep` function, but still an issue IMO).

**Comment by willnationsdev** [comment]
If OS.delay_msec is already a thing, why do people even use the whole yield with timeout thing? lol. Seems like I didn't read the write advice about how to approach the issue.

Alright, it sounds like this PR just isn't really useful in the first place (and not the best way to solve the problem even if it were fully applicable). I'll just go ahead and close it.

**Comment by vnen** [comment]
> If OS.delay_msec is already a thing, why do people even use the whole yield with timeout thing?

Because `delay_msec` will pause the thread execution, if you call it on the main thread you'll pause the whole game. `yield` will return the control to the caller and let everything happen until the signal resumes the function.

**Pull request closed without merging**
