### PR TITLE
Create spritesheet for SpriteFrames by drag and dropping.

### LINKED ISSUE #378: Create spritesheet for SpriteFrames by drag and dropping
**Describe the project you are working on:**
2D game with spritesheets.

**Describe the problem or limitation you are having in your project:**
I started using AnimatedSprite node more after it got support for atlases and I faced a big usability inconvenience. You can create the spritesheet only by clicking the button
image
which opens the file dialog to select the file. Now, I try to avoid this dialog as much as possible, because the filesystem dock is infinitely easier to navigate and find things. However, in this one case I can't avoid it.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
Creating spritesheets for AnimatedSprites would be less annoying if I could do it by drag and dropping. Normally when you drop texture to SpriteFrames editor, it adds it as frame. But it could open the spritesheet creator when holding Ctrl.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**
Proposal

**Describe implementation detail for your proposal (in code), if possible:**
When you drop the texture on SpriteFrames editor while holding Ctrl, open the spritesheet creator with that texture. Should be easy to do.

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**
It's an editor things, non-pluginable.

**Is there a reason why this should be core and not an add-on in the asset library?:**
> non-pluginable

### PR DESCRIPTION
**Pull request by dankan1890**
Close https://github.com/godotengine/godot-proposals/issues/378

### CODE REVIEW

**Comment by KoBeWi** [comment]
@dankan1890 Why was this closed?

**Comment by dankan1890** [comment]
Sorry, my mistake :(

**Review by KoBeWi — APPROVED** [review]
Needs rebase, but otherwise it's ok.

We have to somehow indicate the existence of this option, but could be done in another PR probably.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs a rebase, otherwise should be OK to merge.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.4.

**Pull request merged**
