### PR TITLE
[#7212] Fixed missing 'Variant' return values in documentation.

### PR DESCRIPTION
**Pull request by ducdetronquito**
Sorry for this 3rd PR on the same simple issue. I didn't know it is not possible to re-open a PR when the head branch is recreated. 🙇

There is still methods in `Dictionary` where the return value needs to be defined: shall I create a `_bind_methods()` in `Dictionary.cpp` with the proper bindings ?

### CODE REVIEW

**Comment by ducdetronquito** [comment]
Oh, I'm just going the re-author the commit.

**Comment by ducdetronquito** [comment]
Finally, it should be fine 🤞

**Comment by vnen** [comment]
Dictionary functions are bound in `core/variant_call.cpp`, but the style there is different. I think it needs some changes in that workflow to fix this problem, but that would out of the scope for this PR anyway.

**Comment by ducdetronquito** [comment]
Fine :)

**Pull request merged**
