### PR TITLE
Add support libc++_shared on android ( v2.1 )

### PR DESCRIPTION
**Pull request by rdhafidh**
This commit is targeting with 2.1 branch, will open another PR to adapt with v3.0 branch

My reason using primary libc++  build is that will open wider c++ developer audiance.

### CODE REVIEW

**Comment by hpvb** [comment]
Could you please squash the commits? See our [pr workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) documentation. Thanks!

**Comment by rdhafidh** [comment]
done, waiting ci status

**Comment by hpvb** [comment]
LGTM @akien-mga?

**Comment by akien-mga** [comment]
> My reason using primary libc++ build is that will open wider c++ developer audiance.

Please be more specific about the use case, I'm not willing to change the buildsystem of a branch used in production without knowing why it's needed, if at all.

**Comment by rdhafidh** [comment]
>  I'm not willing to change the buildsystem of a branch used in production 

Yes I see, but libc++_shared is just [more maintained ](https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#ndk-r18) plus with a lot other [goodies](https://libcxx.llvm.org/cxx1y_status.html) and licensed under MIT License compared to libstdc++ ABI. I'm not willing to change build system nor adding on it as you can see that on changed files.

**Comment by akien-mga** [comment]
These changes should be made in the master branch at any rate, reviewed and merged there, then tested, and eventually backported to the stable branches. We're not merging buildsystem changes in stable branches before master.

**Comment by rdhafidh** [comment]
> These changes should be made in the master branch

OK thanks for the feedback,  will do that certainly when  I have enough time.

**Comment by akien-mga** [comment]
Now that #20507 is merged we can consider merging this one too - I think maybe the `android_stl` check needs to be moved up as was done in #20507?

**Comment by rdhafidh** [comment]
> Now that #20507 is merged we can consider merging this one too - I think maybe the android_stl check needs to be moved up as was done in #20507? 

yes I can do that later.

**Comment by akien-mga** [comment]
Merged manually as 6e62a1e4d.

**Pull request closed without merging**
