### PR TITLE
[macOS] Add empty translation files to the editor app bundle, to allow translation detection by the OS.

### PR DESCRIPTION
**Pull request by bruvzg**
Adds a bunch of empty `Info.plist` translation files to ensure macOS is detecting supported languages correctly.

System language settings:
Screenshot 2021-09-22 at 20 42 27

### CODE REVIEW

**Comment by bruvzg** [comment]
macOS detects all locales, except `"pr" Pirate`.

But locale auto selection does not work with some languages since editor do not check only for a full match or locale with the language code only.

Editor locales are `zh_CN`, `zh_TW`, `zh_HK` and `sr_Cyrl`.
OS locales `zh_Hans_{your_countly_code}`, `zh_Hant_{your_countly_code}`, `zh_Hant_HK` and `sr_{your_countly_code}`.

Locale selection code definitely need some improvement.

**Comment by Calinou** [comment]
> macOS detects all locales, except "pr" Pirate.

I think the Pirate locale could be removed at this point. This would also [reduce editor binary size](https://github.com/godotengine/godot-proposals/issues/3421) slightly.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.3.

**Pull request merged**
