### PR TITLE
Add parameters to Directory.list_dir_begin() to skip navigational or hidden entries

### PR DESCRIPTION
**Pull request by RayKoopa**
Implements https://github.com/godotengine/godot/issues/7320

I added the following two parameters to `_Directory::list_dir_begin`:
- `skip_navigational`: When `true`, iterating through the directory does not return the `.` and `..` directories.
- `skip_hidden`: When `true`, iterating through the directory does not return hidden subdirectories and files (as defined by `DirAccess::current_is_hidden()`).

I'm a bit unsure about the "navigational" parameter name. Maybe someone knows a better term for it.

### CODE REVIEW

**Comment by RayKoopa** [comment]
Woops, sorry about the merge conflict... I didn't see it. Seems to be the new return type of `_Directory::list_dir_begin` (was a bool before).

**Comment by bojidar-bg** [comment]
Aww, my! Quick!  `git rebase -i HEAD~3` to squash the commits before Aki sees them!

**Comment by RayKoopa** [comment]
Sorry, but I don't understand squashing. I'd rather make a new PR if that's really wanted...

**Comment by akien-mga** [comment]
```
git rebase -i HEAD~3
// opens a texture editor
// follow the instructions given in the command to prepend the last two commits with `squash` or `fixup` instead of `pick`
// save
// tadaa :)
```

**Comment by bojidar-bg** [comment]
@akien-mga You forgot the force-push `git push --force`, which would ensure that no merge commits are generated through it.

**Comment by akien-mga** [comment]
> You forgot the force-push git push --force, which would ensure that no merge commits are generated through it.

Well if you don't force push it does not generate merge commits. It just yells at you :)

**Comment by RayKoopa** [comment]
I already tried `git rebase -i HEAD~3`. It opened vim with a lot, lot of commits, I changed all to squash once, exited vim, nothing happened. There was some error saying it cant be rebased, I can be more exact when I'm home later on. Though I'm slowly tired of this... :D

**Comment by akien-mga** [comment]
This is likely this remote tracking commit which doesn't play nice. Maybe if you do a plain `git rebase` it would be sufficient to get rid of it, and then you could `git rebase -i HEAD~3`.

**Comment by akien-mga** [comment]
As always, if it doesn't seem to work as it should, abort with `git rebase --abort`.

**Comment by RayKoopa** [comment]
I can try retrying... already had several aborts like a women not taking the pill. :3

**Comment by RayKoopa** [comment]
Gonna recreate the PR in a few :)

**Pull request closed without merging**
