### PR TITLE
[Windows, 3.2] Add tablet driver selection.

### PR DESCRIPTION
**Pull request by bruvzg**
Same as #38874 for 3.2

Test project: [press_test_32.zip](https://github.com/godotengine/godot/files/4655027/press_test_32.zip)

### CODE REVIEW

**Comment by SleepProgger** [comment]
Thank you for this.
It seem to work fine (mostly) on windows 10.

The only "problem" i noticed is that when windows ink is DISABLED in the driver utils and `--tablet-driver winink` is selected it uses WM_MOUSEMOVE again instead of winTab which is what i would expect.


Strange thing though: Before this PR i got WinTab events using Wine, now i only get WM_MOUSEMOVE events. This is ofc not dramatic, but if there is a way to get it working under wine again that would be awesome.

**Comment by bruvzg** [comment]
> The only "problem" i noticed is that when windows ink is DISABLED in the driver utils and --tablet-driver winink is selected it uses WM_MOUSEMOVE again instead of winTab which is what i would expect.

Why would you expect WinTab events when you have selected Windows Ink with `--tablet-driver winink`. Disabling Windows Ink in the driver, only disables it from the device, interface is still available and will work.

> Strange thing though: Before this PR i got WinTab events using Wine, now i only get WM_MOUSEMOVE events. This is ofc not dramatic, but if there is a way to get it working under wine again that would be awesome.

What's the available driver list in the `godot --help` output? Is it detected on Wine at all, usualy `wintab.dll` is part of tablet driver, unless Wine have some sort of built-in emulator.

> Btw: is this going to be changeable at runtime ? AFAIR Project settings change requires a restart or am i wrong here ?

It requires restart right now, but it should be easy to add ability to change it in runtime.

**Comment by SleepProgger** [comment]
> Why would you expect WinTab events when you have selected Windows Ink with --tablet-driver winink. Disabling Windows Ink in the driver, only disables it from the device, interface is still available and will work.

That would be ok too, but is not what i see.
After disabling windows ink in the driver and selecting windows ink with `--tablet-driver winink` i get  neither winTab nor windows ink events but WM_MOUSEMOVE ones.


> What's the available driver list in the godot --help output? Is it detected on Wine at all, usualy wintab.dll is part of tablet driver, unless Wine have some sort of built-in emulator.

I assume you mean: `Tablet input driver ('wintab') (Windows only)`
I am not sure how its done in wine tbh, but i get Wintab events just fine on the current 3.2 branch but not with this PR.

> It's now can be changed in runtime.

Awesome, thank you.

**Comment by bruvzg** [comment]
> After disabling windows ink in the driver and selecting windows ink with --tablet-driver winink i get neither winTab nor windows ink events but WM_MOUSEMOVE ones.

Both WinTab and Windows Ink fallback to sending MouseMove events if tablet events are unhandled (it's done to work with the apps without tablet support), I do not think it's possible to avoid it from the app side, but driver might have "Control cursor" (or something like this) option to disable it.

> I am not sure how its done in wine tbh, but i get Wintab events just fine on the current 3.2 branch but not with this PR.

That's strange, nothing in the wintab detection seems to be changed. I'll take a look.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
