### PR TITLE
[4.2] Make an early return when rendering buffer failed to allocate instead…

### PR DESCRIPTION
**Pull request by MarianoGnu**
**This PR is sponsored by Prehensile Tales and the MSEP.one project**

This unhandled errors caused a crash if not caught. `master` branch has changed too much from 4.2.x to make a pull request to it tho

### CODE REVIEW

**Comment by MarianoGnu** [comment]
**GHA / 📊 Static checks / Code style, file formatting, and docs (pull_request)** seems to be complaining about some part of the file that was not modified by this PR (it wants to change an #include)

**Review by RandomShaper — APPROVED** [review]
LGTM.

**Comment by akien-mga** [comment]
I pushed a fix for the static checks issue in the `4.2` branch, it should solve the problem if you rebase.

> `master` branch has changed too much from 4.2.x to make a pull request to it tho

Is the `master` branch affected by that issue though?

There's little point in fixing a bug in 4.2 only if we're about to release 4.3 with the same bug.

**Comment by akien-mga** [comment]
For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by RandomShaper** [comment]
Also, regarding 4.3+ all those error checks are performed driver-agnostically at `RenderingDevice`, so there's no need to forward-port anything.

**Comment by MarianoGnu** [comment]
> I pushed a fix for the static checks issue in the `4.2` branch, it should solve the problem if you rebase.

Rebased

> For the record, your commit seems not to be linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

Fixed

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
