### PR TITLE
Fix text margins in property editor pop-up.

### LINKED ISSUE #12352: Editor UI: Popup for entering values (e.g. transform/position) needs text margins
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 x64, Godot 3.0 master@804cab3, NVIDIA GTX 980 Ti

**Issue description:**
The popup for entering values into properties (for example for transform/position/scale) has too small a margin between the labels and inputs. The labels are squished into the input fields. See attached screenshots.

**Steps to reproduce:**
Create project, add Node2D, select it and enter values in the inspector.

**Link to minimal example project:**
godotoffset

### PR DESCRIPTION
**Pull request by zedutch**
I've also refactored the variable names to be a bit more readable (as suggested on IRC)

This fixes #12352

### CODE REVIEW

**Comment by groud** [comment]
This PR is probably better than mine (#12384). ;)

**Comment by groud** [comment]
Your PR does not comply with the format style. Could you apply clang-format to the modified files and amend your commit ? See : http://docs.godotengine.org/en/2.1/community/contributing/code_style_guidelines.html

**Comment by groud** [comment]
Arf sorry, you did not amend the commit but created a new one. 
Please squash the two commits together: see http://docs.godotengine.org/en/2.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase.

**Comment by zedutchgandalf** [comment]
@groud I'm sorry, it should be fixed now. I outlined the '=' signs under each other but I didn't realize this doesn't comply with the clang-format - I though that said "at least one space" instead of exactly one :P
I'll just always run clang-format in the future.

**Comment by groud** [comment]
Arf sorry, you did not amend the commit but created a new one.
Please squash the two commits together: see http://docs.godotengine.org/en/2.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase.

**Comment by groud** [comment]
Also to avoid other clang-format errors, you can read: http://docs.godotengine.org/en/2.1/community/contributing/code_style_guidelines.html?highlight=hook#pre-commit-hook :)

**Pull request merged**
