### PR TITLE
[Mono] Rename Fposmod to PosMod, fix output

### PR DESCRIPTION
**Pull request by aaronfranke**
https://github.com/godotengine/godot/issues/18364#issuecomment-392367739

1. None of the other float-returning methods start with the letter F

2. It's not PascalCase if you count `pos` and `mod` as words

3. ~~The `pos` distinction is not necessary because for "non-positive modulus" also known as "remainder" there's already [an operator in C# called %](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/operators/remainder-operator). People using the Mathf function would only ever be looking for something that wasn't in the C# language.~~ In the interest of clarity and somewhat keeping consistency with the C++ math, I've kept the word `Pos`.

4. `PosMod()` looks a lot cleaner than `Fposmod()`.

Also, I've changed the code inside the method. In my tests, this version works much better. The previous version of the code produces incorrect output for some values.

As someone who uses this function a lot in my code, I would definitely appreciate this change.

### CODE REVIEW

**Comment by neikeq** [comment]
There is nothing in the name `Mod()` that tells me it's any different from the modulo operator. I'm in favor of `PosMod()` or `PositiveMod()`.

**Comment by KellyThomas** [comment]
The example from the docs indicates that it sound return within the range `[1, b]`.

http://docs.godotengine.org/en/3.0/classes/class_@gdscript.html#class-gdscript-fposmod

**Comment by aaronfranke** [comment]
@KellyThomas This is inconsistent with the positive values, and thus with the wording "wraps equally in positive and negative". I've submitted another PR to fix the C++ code: https://github.com/godotengine/godot/pull/19279

**Comment by aaronfranke** [comment]
@neikeq I've changed the function name to `PosMod` instead of `Mod` as you requested.

Since you've already concluded that the fix is correct, we should merge so that we have a consistent API before Godot 3.1 Alpha on July 1st. Unlike in the C++ code, nothing depends on this function (yet).

**Review by neikeq — APPROVED** [review]
Looks good to me. However, if this code is a mirror of the new implementation being introduced in #19279, then I would prefer both PRs to be merged at the same time to avoid problems.

**Comment by hpvb** [comment]
Cherry picked into 3.0.6

**Pull request merged**
