### PR TITLE
Move inspector help from inside tool menu to separate button

### PR DESCRIPTION
**Pull request by ghost**
Follow up of https://github.com/godotengine/godot/pull/13391

The inspector help function should be visible more prominently. This PR moves it from inside the tools menu to its own visible button. Now we only need to find a good place for it. Suggestion:

doc-button

### CODE REVIEW

**Comment by leoddd** [comment]
Maybe move it to the left of the Node2D symbol? So it's closer to the icon of the node/resource being inspected, as well as because the top row is already pretty crowded when you shrink the dock as far as possible, while the bottom row is largely filled by the variable-width node name - which isn't as important to see in its entirety.

**Comment by groud** [comment]
Hum, instead I think another solution might be better. We could have a pop-up menu (or double click) on the different inherited classes of the current node (in the property panel) . In that case that would allow opening the documentation of either node2d/canvasitem/node.

But making the docs more accessible here looks a good idea to me.

**Comment by poke1024** [comment]
I like the suggestion by @leoddd. Updated:

helpbutton

Wondering a bit if this is too prominent. For comparison, here's a variation:

variant2

The latter photo is photoshopped, as reducing the node name width currently completely breaks the name display and popup (would probably need rewriting part of `EditorPath` ui).

@groud Not sure I understand, would this still imply a help button (producing a popup) or would the help be opened by clicking on the name somehow?

**Comment by leoddd** [comment]
IFF you were to go with my suggestion, the top one is much better.
You always want as many elementy to be static as possible in UI design, so having the DOC button move around depending on the node name length would be bad.

@groud's idea doesn't sound bad either, but I feel like it would defeat the purpose of making the DOC button easier to see at a glance, unless you actually want to put a DOC button into every single property header.
Clicking on DOC and then clicking on the desired inheritance at the top isn't many more clicks anyway.


Alternatively, to sort of combine these ideas: Clicking on the DOC button could produce a small pop-up that lists all the classes this Node inherits, so you can cherrypick which documentation to look up from there.

**Comment by groud** [comment]
More like by clicking or right clicking on the name I think. Or maybe a button on the right I don't know. But in the bottom property panel, for each inherited class, instead of the top of the inspector.

**Comment by djrm** [comment]
i would not put that button next to current object, because that area gets usually crowded, and even more when you are editing saved resources (they can have long names), another option would be next to the history button (either left or right).

also i would use this icon, that is used for specific documentation, the one you are using is for search.
screenshot from 2017-12-03 14-37-42

**Comment by leoddd** [comment]
@groud Placing DOC buttons in the property panel strikes me as a kind of dirty solution, just UI wise. I would prefer not to have to scroll around the Inspector panel to find the right DOC button instead of having a single DOC button always available at the top.

**Comment by reduz** [comment]
I think that menu needs to be reorganized

**Comment by poke1024** [comment]
Also see https://github.com/godotengine/godot/pull/13953.

**Comment by puppetmaster-** [comment]
I like your first Idea more than the others
image
also because it "will" would work for ressources.

I personally would never had the idea to press on the doc button in Node (is usless)
This is never needed and gets the gui dirty with unnecessary buttons.
image

Once the documentation is open, you can easily jump to the other inherited nodes.

**Comment by poke1024** [comment]
After sleeping over this, and as there's very little consensus here, I'm going back to the original design with the corrected icon:

v1

@djrm `Help` is somewhat darker than `HelpSearch` so it looks disabled above; we can fix this should we use this PR.

I tried the following history area placements, but at the end of the day they look jumbled to me, as does putting the button before the node class name; I think history area should only contain history buttons:

v2

v3

**Comment by leoddd** [comment]
If it has to be there, the left area is best, yeah.
Would personally still prefer bottom row (next to search icon if the left isn't possible), since it kind of doesn't fit on the left either (which is all file management related buttons), but as long as it's there it's fine.

**Comment by djrm** [comment]
i dont think we should put those buttons there

see https://github.com/godotengine/godot/pull/13953#issuecomment-349445850

**Comment by akien-mga** [comment]
To be honest, I don't really see a use case for any of the variants proposed. The help is focused on the scripting API, so it makes sense to check quickly from the script editor, but not so much from the inspector IMO. If the use case is to get some documentation on the properties, it would be much better to have it included automatically in the tooltips when hovering the properties.

**Comment by akien-mga** [comment]
> If the use case is to get some documentation on the properties, it would be much better to have it included automatically in the tooltips when hovering the properties.

Which is actually implemented already, albeit it had been broken since a month or two. It's now fixed with #14478.

**Comment by akien-mga** [comment]
Closing as per the above comments.

**Pull request closed without merging**
