### PR TITLE
Fix custom shortcuts not being saved in some cases

### LINKED ISSUE #42862: Make Sub-Resources Unique shortcut clears itself randomly
**Godot version:**

3.2.3

**Issue description:**
This is a weird one, but I created a shortcut for the Make Sub-Resources Unique action and my problem is that it's cleared randomly. I mean some time after creating it I find out that it's gone, so I have to bind it again, but it keeps happening. I have other custom shortcuts and this doesn't happen. No idea what could be the cause.

**Steps to reproduce:**
1. In Editor Settings bind a shortcut for Make Sub-Resources (in my case I use `Ctrl + Shift + D`
2. Close and reopen Godot few times?
3. Wait few days???
4. Notice that eventually the shortcut is gone

### PR DESCRIPTION
**Pull request by gvaneyck**
Fixes: #42862
Can be cherry-picked to 3.0+

### CODE REVIEW

**Comment by gvaneyck** [comment]
This probably breaks the intended functionality of `optimize_save`, if optimize save is supposed to remove shortcuts for actions that no longer exist.

**Comment by KiritoAM** [comment]
I wouldn't say that your change breaks optimize_save at all by adding an "original", as an "original" is added to each shortcut in ED_SHORTCUT when it is added to the editor settings. Your fix is correctly replicating that behaviour, so the fix looks good to me. Taking property_editor/make_subresources_unique as an example, an "original" gets added to it's shortcut on startup via InspectorDock::update, shortly after we save shortcuts out the disk.

**Review by KiritoAM — APPROVED** [review]

**Comment by gvaneyck** [comment]
The reason I say `optimize_save` will partially break is the following scenario:
1) Shortcut X is added to Godot
2) A user assigns a custom key to shortcut X
3) Shortcut X is removed from Godot
4) The user saves settings

With Patch: `optimize_save` will never remove the shortcut because original is populated
Without Patch: `optimize_save` will remove the shortcut

**Comment by mhilbrunner** [comment]
Original issue not reproducible anymore on current master; closing as its :been gathering dust for a while. Still, thank you! :)

**Pull request closed without merging**
