### PR TITLE
Add shift + [1-5] keyboard shortcuts to zoom out

### PR DESCRIPTION
**Pull request by AaronRecord**
While testing https://github.com/godotengine/godot/pull/48252, it occurred to me it'd probably be useful to be able to zoom out quickly as well, for tilemaps/wordbuilding etc.
<kbd>shift + 1</kbd>: zoom to 50%
<kbd>shift + 2</kbd>: zoom to 25%
<kbd>shift + 3</kbd>: zoom to 12.5%
<kbd>shift + 4</kbd>: zoom to 6.25%
<kbd>shift + 5</kbd>: zoom to 3.125%

3.x version here: https://github.com/godotengine/godot/pull/50499

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
I didn't think about this at first, but it seems like a good idea to me.

Maybe GIMP could do the same eventually… :eyes: 

My only concern is that web browsers use <kbd>Alt</kbd> + (number key) to switch between tabs, and we may want to implement this in Godot eventually. If we go forward with this, we may have to replace the use of <kbd>Alt</kbd> with another modifier such as <kbd>Ctrl</kbd> or <kbd>Shift</kbd>. However, holding <kbd>Shift</kbd> may be required to trigger the number keys in the first place on non-QWERTY keyboard layouts.

**Comment by LightningAA** [comment]
> Maybe GIMP could do the same eventually… 👀

Haha, possibly, although I think it makes more sense in the context of Godot because in Gimp you generally work mainly in one area that you can see all of when you're at 100% zoom, but in Godot your scenes often take up more than one full screen.

**Comment by timothyqiu** [comment]
FYI: `Alt+[1-4]` are used to open different editor workspaces on macOS:

https://github.com/godotengine/godot/blob/60add98a4cff0d27c6aa2f52042555eccb86ed70/editor/editor_node.cpp#L7013-L7024

**Comment by LightningAA** [comment]
@timothyqiu Maybe <kbd>shift</kbd> instead?

**Comment by timothyqiu** [comment]
Yeah, GIMP uses `Shift+2` to zoom to 50%. But personally, I have never triggered that successfully, and I don't know why 😓

**Comment by LightningAA** [comment]
Alright, I've changed it to use <kbd>shift</kbd> instead. Another alternative I considered was using [6-0] for zooming out, but I thought that wasn't the most intuitive because [1-5] gets more and more zoomed in and then after [6-0] it'd switch to getting more and more zoomed out. I also considered making <kbd>1</kbd> the most zoomed out and <kbd>0</kbd> the most zoomed in (so it gets more and more zoomed in as you go along), but this might be confusing to people coming from GIMP etc.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
