### PR TITLE
[.NET] Upgrade user project's TargetFramework to `net8.0`

### PR DESCRIPTION
**Pull request by raulsntos**
- Upgrades the TFM for new created projects to `net8.0`.
- Implements system to upgrade TFM for existing projects to `net8.0`.
- Supersedes https://github.com/godotengine/godot/pull/82927.

### CODE REVIEW

**Comment by Delsin-Yu** [comment]
I'm not sure if it's an appropriate place to mention this, but the existing upgrade mechanism seems to removes the blank lines in csproj when updating, that is, the following csproj:

<details>

```csproj
<Project Sdk="Godot.NET.Sdk/4.3.0">

    <PropertyGroup>

        <TargetFramework>net8.0</TargetFramework>

        <LangVersion>12</LangVersion>

        <Nullable>enable</Nullable>

        <EnableDynamicLoading>true</EnableDynamicLoading>

    </PropertyGroup>

    <ItemGroup>

        <PackageReference Include="GDTask" Version="1.3.0"/>

        <PackageReference Include="gdUnit4.api" Version="4.3.1"/>

    </ItemGroup>

</Project>
```

</details>

will becomes this after the upgrade:

<details>

```csproj
<Project Sdk="Godot.NET.Sdk/4.4.0">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12</LangVersion>
        <Nullable>enable</Nullable>
        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="GDTask" Version="1.3.0"/>
        <PackageReference Include="gdUnit4.api" Version="4.3.1"/>
    </ItemGroup>
</Project>
```

</details>

**Comment by raulsntos** [comment]
It's somewhat unrelated but an easy fix so I decided to include it.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Needs rebase.

For the record the 4.4-dev7 build is planned for Thursday, do you want this PR included by then, or do you prefer to wait for it to be merged right after, and then included in beta1 in January?

**Comment by raulsntos** [comment]
I would prefer to include it in 4.4-dev7 so it's in the same release that makes `net8.0` the new minimum. But we can also just tell users to modify their `.csproj` manually until beta1.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
