### PR TITLE
change scale random in particles, now it pivots around the scale value

### LINKED ISSUE #2405: Make particles use random ranges
### Describe the project you are working on
Various VFX

### Describe the problem or limitation you are having in your project
Most particle properties that support random only have a "base value" and a "random" percentage.
This approach is not optimal, in particular for scale: it is not possible to have particles range
from scale 0.9 to 1.3 for example, because the random of the scale is always done between the value
specified, and 1.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation
Change the way that random is used in particles material: instead of having a randomness value, have
2 sliders that specify min and max values.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
remove value + random range with min and max values

### If this enhancement will not be used often, can it be worked around with a few lines of script?
It requires a custom particle shader

### Is there a reason why this should be core and not an add-on in the asset library?
This is an improvement for the default particles material.

### PR DESCRIPTION
**Pull request by QbieShay**
Implements https://github.com/godotengine/godot-proposals/issues/2405

Fixes: https://github.com/godotengine/godot-proposals/issues/2405

### CODE REVIEW

**Comment by KoBeWi** [comment]
Soo this handles only scale. How does this resolve the proposal? Unless it was always only about the scale.
(from what I see other particle parameters use a different randomising formula)

**Comment by QbieShay** [comment]
@KoBeWi I had a tentative PR for all the parameters, but after discussing a bit on the rendering channel, I think that the other parameters are okay as-is. Scale was the only real problem for me, so i trimmed the PR down to scale.

**Comment by KoBeWi** [comment]
According to doc, the randomness works like this `initial_value = param_value + param_value * randomness`
This is extremely limiting as you can't express arbitrary ranges. I always find it confusing to use and just put *random* values. Fixing it was on my wishlist for a long time.

Also, why would scale be the only one that works differently?

**Comment by QbieShay** [comment]
Other values can be changed later on if they are a problem for more people. I only really had troubles with scale, so in Godot's philosophy of having real usecases, I'm making a PR only for scale.

Do you have any other parameter in mind that should be changed?

**Comment by KoBeWi** [comment]
Maybe just leave the PR as is, but don't close the proposal.

**Comment by Cykyrios** [comment]
Just as an example of other parameters that could need the same change, consider tangential acceleration: if you put a value, say 5, and add randomness, it will vary between 0 and 5. Now what if you want particles to accelerate one way or the other randomly? Well you can't, because randomness won't change the sign of the initial value.

I would personally prefer that all parameters use the value +/- randomness instead of modifying only specific ones, but I agree scale is somewhat special in that it randomizes between 1 and the scale value.

**Comment by QbieShay** [comment]
Superseded by https://github.com/godotengine/godot/pull/50434

**Pull request closed without merging**
