### PR TITLE
Web: Disable raycast module by default (no occlusion culling)

### LINKED ISSUE #70621: WebAssembly maximum memory 2GB causes Out of Memory error on iOS Safari 16.2
### Godot version

4.0.dev (f382a2b)

### System information

iOS 16.2 Safari, iPhone 13 Pro

### Issue description

When exporting for Web and running on iOS 16.2 Safari, out of memory error occurs at WebAssembly.Memory initialization.
This error comes because `maximum` argument is 2048MB which is quite bigger for iOS.
When I changed `WASM_MEM_MAX` to 256MB for example at platform/web/detect.py: 197, the error disappeared.

```Python
    env.Append(LINKFLAGS=["-s", "WASM_MEM_MAX=256MB"])
```

### Steps to reproduce

1. Build Godot Web export with option `module_raycast_enabled=no` to disable WebAssembly SIMD usage which seems to be not yet supported on iOS Safari 16.2.
2. Export minimal reproduction project to Web.
3. Out of memory error log will be found on JavaScript console (reproduced).
4. Change WASM_MEM_MAX to 256MB and rebuild Web export.
5. Re-export minimal reproduction project.
6. Rotating unlit white cube is correctly rendered (reproduced).

### Minimal reproduction project

[simple_rotating_white_cube.zip](https://github.com/godotengine/godot/files/10306671/simple_rotating_white_cube.zip)

### PR DESCRIPTION
**Pull request by akien-mga**
This means no CPU occlusion culling (and not compiling Embree), unless you compile custom export templates with `module_raycast_enabled=yes`.

This reduces the memory footprint significantly, and binary size.

Fixes #70621.

@Calinou I'm not too familiar with the occlusion culling and lightmap documentation, could you tell me where to add some notes that this is not supported in default Web templates?

### CODE REVIEW

**Comment by Calinou** [comment]
> I'm not too familiar with the occlusion culling and lightmap documentation, could you tell me where to add some notes that this is not supported in default Web templates?

Probably in these classes' descriptions:

- https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/doc/classes/Occluder3D.xml#L1
- https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/doc/classes/OccluderInstance3D.xml#L6

And in these properties:

- https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/doc/classes/ProjectSettings.xml#L2518
- https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/doc/classes/Viewport.xml#L364
- https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/doc/classes/RenderingServer.xml#L3769

I can open a separate PR on godot-docs for https://docs.godotengine.org/en/latest/tutorials/3d/occlusion_culling.html.

**Review by ryanabx — APPROVED** [review]
I approve I approve I approve.

Most people exporting for web won't even know about the raycast module anyways, and this has been a compatibility issue with Webkit/iOS for a while now!

Pending the docs change, of course, but it looks like Calinou has already brought attention to that. It'd be good to put a notice in there for the person who comes by every so often who would need to know this.

**Comment by akien-mga** [comment]
Thanks @Calinou, added docs. I didn't put the note in Occluder3D and Viewport to avoid being too redundant, as both places refer to the other class or property for more details already.

**Comment by clayjohn** [comment]
We use raycasts for importing meshes with LODs. We need to check that this change does not break mesh importing

**Comment by AThousandShips** [comment]
How feasible is importing meshes with LOD on web editor?

**Comment by Calinou** [comment]
> How feasible is importing meshes with LOD on web editor?

It is technically feasible, but you probably don't want to work on a project with highly complex meshes in the web editor anyway.

**Comment by ryanabx** [comment]
> > How feasible is importing meshes with LOD on web editor?
> 
> It is technically feasible, but you probably don't want to work on a project with highly complex meshes in the web editor anyway.

In my opinion, the limitation should be clarified in documentation. I don't know if there is a section about using the web editor, but clarifying that would be helpful. Other than that, I do think this change is for the better.

**Comment by ryanabx** [comment]
I've tested importing a gltf scene into the godot web editor on this PR.

Sample model:
https://github.com/KhronosGroup/glTF-Sample-Models/raw/master/2.0/AnimatedCube/screenshot/screenshot.gif

It imported successfully: (ignore the watermark, had to compress the video)

https://github.com/godotengine/godot/assets/56272643/486d5c2c-b535-43b9-9815-8eb091423108

Let me know if any more testing is required!

**Comment by ryanabx** [comment]
Follow-up:
I was asked by @clayjohn to test LOD bias on an imported gltf model. I chose a dragon model from the same repo as the rotating cube.

LOD Bias = 1:
image

LOD Bias = 0.001 (Lowest):
image

The detail does in fact change on web with this PR!

**Comment by clayjohn** [comment]
Thanks @ryanabx for confirming that compiling out RayCast won't break our LOD import logic!

**Review by clayjohn — APPROVED** [review]
Seems like a good change. If there is demand, we can add a slim StaticRayCast fallback implementation for memory constrained systems.

**Comment by akien-mga** [comment]
Cherry-picked for 4.1.2.

**Pull request merged**
