### PR TITLE
Use KeyList, ButtonList and JoystickList instead of int where possible

### PR DESCRIPTION
**Pull request by neikeq**
As discussed in #16388

I only made platform dependent changes for Windows, so build is expected to fail on other platforms.

I don't know whether this change is correct or not, but as #16388 has been sitting there without response I though I at least could make a proposal to be reviewed.

The main motivation for this is that in C# casting a enum to `int` has to be explicit, making it an annoyance.

### CODE REVIEW

**Comment by reduz** [comment]
It seems good to me, up to @akien-mga to merge if passes checks

**Comment by neikeq** [comment]
All right, I will make it pass for all platforms tomorrow then.

**Comment by neikeq** [comment]
All right, CI is passing for all platforms now. We're still missing haiku, javascript and uwp, which I don't have a build setup configured for.

**Comment by neikeq** [comment]
Some code may still be using int instead of the appropriate enum, but it's internals.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
@neikeq What's the status on this PR?

**Comment by neikeq** [comment]
@akien-mga It's mostly done. But it may not build on haiku, javascript and uwp. Need to make sure of that first.

**Comment by akien-mga** [comment]
> But it may not build on haiku, javascript and uwp. Need to make sure of that first.

Haiku is on a "best effort" support, so if you do the changes that seem necessary by comparison with other platforms, it should be good enough, even if you can't test building it.

I'll test Javascript now.
Testing UWP to make sure it builds would be nice indeed, maybe @vnen can help.

**Comment by akien-mga** [comment]
Javascript fails building indeed:
```
platform/javascript/os_javascript.cpp:221:19: error: cannot initialize a parameter of type 'KeyList' with an rvalue of type 'int'
        ev->set_scancode(dom2godot_scancode(emscripten_event->keyCode));
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./core/os/input_event.h:288:28: note: passing argument to parameter 'p_scancode' here
        void set_scancode(KeyList p_scancode);
                                  ^
platform/javascript/os_javascript.cpp:337:22: error: cannot initialize a parameter of type 'ButtonList' with an lvalue of type 'int'
        ev->set_button_mask(mask);
                            ^~~~
./core/os/input_event.h:322:34: note: passing argument to parameter 'p_mask' here
        void set_button_mask(ButtonList p_mask);
                                        ^
platform/javascript/os_javascript.cpp:361:22: error: cannot initialize a parameter of type 'ButtonList' with an lvalue of type 'int'
        ev->set_button_mask(input_mask);
                            ^~~~~~~~~~
./core/os/input_event.h:322:34: note: passing argument to parameter 'p_mask' here
        void set_button_mask(ButtonList p_mask);
                                        ^
platform/javascript/os_javascript.cpp:634:22: error: cannot initialize a parameter of type 'ButtonList' with an rvalue of type 'int'
        ev->set_button_mask(input->get_mouse_button_mask() | button_flag);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./core/os/input_event.h:322:34: note: passing argument to parameter 'p_mask' here
        void set_button_mask(ButtonList p_mask);
                                        ^
platform/javascript/os_javascript.cpp:638:22: error: cannot initialize a parameter of type 'ButtonList' with an rvalue of type 'int'
        ev->set_button_mask(input->get_mouse_button_mask() & ~button_flag);
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./core/os/input_event.h:322:34: note: passing argument to parameter 'p_mask' here
        void set_button_mask(ButtonList p_mask);
                                        ^
platform/javascript/os_javascript.cpp:741:30: error: cannot initialize a parameter of type 'JoystickList' with an lvalue of type 'int'
                                        input->joy_axis(joypad, button, joy_axis);
                                                                ^~~~~~
./main/input_default.h:252:43: note: passing argument to parameter 'p_axis' here
        void joy_axis(int p_device, JoystickList p_axis, const JoyAxis &p_value);
                                                 ^
platform/javascript/os_javascript.cpp:743:32: error: cannot initialize a parameter of type 'JoystickList' with an lvalue of type 'int'
                                        input->joy_button(joypad, button, value);
                                                                  ^~~~~~
./main/input_default.h:251:45: note: passing argument to parameter 'p_button' here
        void joy_button(int p_device, JoystickList p_button, bool p_pressed);
                                                   ^
platform/javascript/os_javascript.cpp:751:29: error: cannot initialize a parameter of type 'JoystickList' with an lvalue of type 'int'
                                input->joy_axis(joypad, axis, joy_axis);
                                                        ^~~~
./main/input_default.h:252:43: note: passing argument to parameter 'p_axis' here
        void joy_axis(int p_device, JoystickList p_axis, const JoyAxis &p_value);
                                                 ^
```

**Comment by akien-mga** [comment]
@neikeq Would be good to rebase now - though you might want to wait for #38151 to be merged first if it impacts it.

**Comment by aaronfranke** [comment]
#38054 should be merged first, then this should be rebased on top of that.

**Comment by akien-mga** [comment]
This should be rebased (or redone from scratch, which might be simpler).

**Comment by aaronfranke** [comment]
Closing because of the conflicts and the lack of progress, but I will personally redo this PR from scratch after #38054 is merged. Don't worry @neikeq, I got this one.

**Pull request closed without merging**
