### PR TITLE
Add annotations support for property setter/getter functions

### PR DESCRIPTION
**Pull request by heppocogne**
- Update error messages setter/getter functions.
   -  When setter is defined and an unexpected identifier appears:
      `Error at (10, 5): Expected "get" for property declaration.`
   -  When getter is defined and an unexpected identifier appears:
      `Error at (10, 5): Expected "set" for property declaration.`
- Add annotation support for setter/getter functions.
```gdscript
var value:int:
	@warning_ignore(unused_variable,unused_local_constant)
	get:
		const x=1
		var y
		return value

	@warning_ignore(unused_local_constant)
	@warning_ignore(unused_variable)
	set(a):
		var y
		const x=1
		value=a
```

### CODE REVIEW

**Comment by Calinou** [comment]
@heppocogne Does this close existing open issues? If so, please link to them so they can be closed once this PR is merged :slightly_smiling_face:

**Comment by heppocogne** [comment]
@Calinou 
No, there are no related issues to this PR.

**Comment by akien-mga** [comment]
Updated the PR title so that contributors can understand more easily what this aims to do.

Would need a rebase, and I'd suggest squashing the commits.

**Comment by heppocogne** [comment]
I closed this PR by mistake. So, I creates new one #78341.

**Pull request closed without merging**
