### PR TITLE
Bullet physics wrapper

### PR DESCRIPTION
**Pull request by AndreaCatania**
Check this for backtracking: https://github.com/godotengine/godot/pull/10013

### CODE REVIEW

**Comment by AndreaCatania** [comment]
Now Bullet is merged and it is the default physics engine, you don't need to change the settings in order to use it.

**Comment by NathanWarden** [comment]
Great work @AndreaCatania !

**Comment by aaronfranke** [comment]
Bullet uses vertical-by-default collision meshes. For ideal compatibility, we should fix https://github.com/godotengine/godot/issues/5813.

**Comment by AndreaCatania** [comment]
To avoid misunderstanding: Bullet capsule shape is meant to have 3 type of orientation. And the default orientation is not better than the others.. Also the compatibility order is Godot <- bullet... so bullet must fit Godot requirements and in this moment it does

**Pull request merged**
