### PR TITLE
Correctly use fallback for default fonts

### LINKED ISSUE #39235: Multiple editor theme propagation errors.
**Godot version:**

master, a8787d1

**OS/device including version:**

Any

**Issue description:**

After OS/DisplayServer split, multiple editor UI elements use default bitmap font (no scaling and latin characters only), and have missing interface icons.

Elements with the wrong font:

- "Load errors" dialog.
- "Description" field in the "Create new node", "Create new resource" and "Search visual script", "Visual script > Change base type", "Visual shader > Add node".
- "Visual script" and "Visual shader" note titles.
- Table headers in the "Project settings" > "Input map", "Localization/Remaps", "Autoload" "Plugins" - and "GDNative"
- "Animation Tree" > "State machine" and "Blend tree" note names.
- "Feature List" field in the "Export" > "Features"
- Table header in the "Orphan resource explorer"
- Table header in "Editor settings" > "Shortcuts"
- Table headers in bottom bar "Debugger" (on multiple tabs)
- All text in the theme preview (might be intentional or was broken before split, see #25585)

File dialog icons are missing in the following dialogs:
- All file dialogs opened from "Export"
- All file dialogs opened from "Inspector"

Related PRs: #39123 (Tooltip font), #38917 (Some documentation fonts).

### PR DESCRIPTION
**Pull request by reduz**
closes #39235

### CODE REVIEW

**Comment by bruvzg** [comment]
> closes #39235

All font issues from the #39235 seems to be fixed.

Editor icon issues are not (probably unrelated to theme):
> File dialog icons are missing in the following dialogs:
    - All file dialogs opened from "Export"
    - All file dialogs opened from "Inspector"

Screenshot 2020-07-04 at 01 59 42

**Review by akien-mga — APPROVED** [review]

**Comment by txj-mssl** [comment]
good

**Comment by reduz** [comment]
> > closes #39235
> 
> All font issues from the #39235 seems to be fixed.
> 
> Editor icon issues are not (probably unrelated to theme):

Should be fixed now.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
