### PR TITLE
Fix new quick open dialog to be showed at the center of the screen

### LINKED ISSUE #69417: Editor: Quick Load option window opens minimised and in wrong location, when 'single window mode' is enabled
### Godot version

v4.0.beta.custom_build [cd491c6e4]

### System information

Windows 10

### Issue description

When 'single window mode' is enabled in the Editor Settings, the Quick Load option in the inspector will open a minimised window at the top left of the screen. Examples where this occurs in the inspector: material_override (GeometryInstance3D), texture (TextureRect).
The window will always appear this way, even after manually resizing it, which is frustrating given how useful Quick Load is to load a resource specific to the property you want to load it in.
This issue doesn't seem to occur when 'single window mode' is disabled. Additionally, if you use Quick Load in a property when it's disabled, the issue will no longer occur for that property after turning 'single window mode' back on.

This is a recent-ish regression, I tried bisect it but the official [Godot 4.0 beta 6] doesn't have this issue, so it's something between that and v4.0.beta.custom_build [cd491c6e4] .

### Steps to reproduce

Click Quick Load in the inspector of a MeshInstance3D, anywhere where a material can go into, while having 'single window mode' enabled.

image

### Minimal reproduction project

[quick load bug.zip](https://github.com/godotengine/godot/files/10127857/quick.load.bug.zip)

### PR DESCRIPTION
**Pull request by Chaosus**
Fix #69417

### CODE REVIEW

**Comment by Sauermann** [comment]
I have tested the implementation for `EditorQuickOpen::popup_dialog` and it fixes the linked bug.

Size and position of the Window get restored after reopening "Quick Load", however they don't get restored after selecting a different node.

**Comment by MewPurPur** [comment]
Supersedes https://github.com/godotengine/godot/pull/67517?

**Comment by Chaosus** [comment]
> Supersedes https://github.com/godotengine/godot/pull/67517?

It's overlap, not superseded, so if it's merged that PR needs to be rebased.

**Comment by Chaosus** [comment]
> Size and position of the Window get restored after reopening "Quick Load", however they don't get restored after selecting a different node.

Well, there are two different quick edit dialogs (global and resource-based), that's why it's a bit of confusion.

**Comment by Chaosus** [comment]
> however they don't get restored after selecting a different node.

@Sauermann Check again, I think I've fixed it.

**Comment by Sauermann** [comment]
> Check again, I think I've fixed it

I have tested the implementation for `EditorQuickOpen::popup_dialog` and it fixes the issue for me.

Making `prev_rect` static in order to store the previous size and keep it for newly created popups makes sense to me.

Previous values are stored when the visibility of the popup is changed to hidden. Is it possible, that the previous popup gets removed/destroyed, without `NOTIFICATION_VISIBILITY_CHANGED` being called?

**Comment by Chaosus** [comment]
> Is it possible, that the previous popup gets removed/destroyed, without NOTIFICATION_VISIBILITY_CHANGED being called?

There is no such code in the sources currently, and this class is not opened for the users, but if this happens the prev_rect will not be saved, unless we add a handle for `NOTIFICATION_PREDELETE`.

**Review by Sauermann — APPROVED** [review]
Looking good to me

**Review by akien-mga — APPROVED** [review]

**Pull request merged**
