### PR TITLE
Improve looks and consistency of tabs

### PR DESCRIPTION
**Pull request by YeldhamDev**
This PR does the following:
- Make `TabBar` draw the select tab on top, like `TabContainer`.
- Make `TabBar` draw its unselected tabs in the same way as `TabContainer`.
- Modify the "tab_current" texture used by both `TabBar` and `TabContainer` to better blend in with the panel.

| **Before:** | **After:** |
| - | - |
| Screenshot_20220112_195856 | Screenshot_20220112_195530 |

### CODE REVIEW

**Comment by pycbouh** [comment]
Note that the theme changes would have to be redone when the new default theme PR is merged, though at least the icon is likely fixed there already as the style is now flatter.

**Comment by YeldhamDev** [comment]
@pycbouh Still, no harm and making it look nicer until that's finished. Besides, I'm going to backport that once this is merged.

**Review by bruvzg — COMMENTED** [review]
Even if the issue is fixed in the new theme, it should be good for the custom themes, and separate `_draw_tab` function is more readable.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
@Calinou might want to give this a check before we merge (at least to be aware of the need to rebase the theme changes in #51159).

**Review by Calinou — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
