### PR TITLE
Add able to select scene camera in editor viewport. (3.0)

### PR DESCRIPTION
**Pull request by dkrutskikh**
Port of https://github.com/godotengine/godot/pull/12705 for master branch

### CODE REVIEW

**Comment by akien-mga** [comment]
What's the point of this feature, given that there is already a "preview" button in all viewports when you select a Camera in the SceneTree? When you press it, that Camera is set as the preview for that viewport, and it's persistent.

So the feature you're implementing already exists.

**Comment by DmitryKrutskikh** [comment]
@akien-mga  The preview mode does't make it possible to apply any modifiers to the objects of the scene. In my opinion, it's worth letting game designers edit the scene from the game camera.

**Comment by akien-mga** [comment]
Maybe there could be a toggle to enable editing when a viewport is assigned a Camera in preview mode?

**Comment by DmitryKrutskikh** [comment]
@akien-mga I think complicate preview mode interface is a bad idea.

**Comment by akien-mga** [comment]
Well adding another interface for the same feature doesn't seem like a good idea either :)

**Comment by reduz** [comment]
Current preview interface is fine IMO, we did not have much complaints about it. 
What doesn't work and it should is probably editing while in preview mode..

**Comment by reduz** [comment]
Closing this, as there is not much agreement. I think it may be more desirable to allow editing from the camera previwe

**Pull request closed without merging**
