### PR TITLE
[GDNative] updates to string API and const fixes

### PR DESCRIPTION
**Pull request by karroffel**
Hopefully the last time I change the API struct before the release.

cc @sheepandshepherd, @endragor, @touilleMan and also @BastiaanOlij, those should be affected by the changes the most.

### CODE REVIEW

**Comment by akien-mga** [comment]
Note to binding authors: we're likely going to release a RC1 build tomorrow or on Saturday, in case you want to sync your bindings with this breaking change before that.

**Comment by endragor** [comment]
@karroffel Shouldn't there be a method for creating `godot_string` from `godot_char_string`? Given a UTF-8 string, how do you construct `godot_string` with this new API?

**Comment by karroffel** [comment]
@endragor,

```cpp
godot_string str;
api->godot_string_new(&str);
api->godor_string_parse_utf8(&str, some_text);
```

**Comment by endragor** [comment]
@karroffel got it, thanks!

**Comment by BastiaanOlij** [comment]
So far I don't like this change... makes it far harder to do something that should be simple especially has GDNative will do a lot of interfacing with 3rd party apis which all have simple char buffers for strings and we'll be doing this alot.

The parse utf8 works around things, there should be a godot_string_parse_ascii then as well.  

What I can't see is how to obtain a char * to the data held within a godot string.

**Comment by karroffel** [comment]
@BastiaanOlij every ASCII text is also valid UTF-8, so there is no need for a `parse_ascii` function.

To get a char pointer you do this
```cpp
godot_char_string buf = api->godot_string_utf8(&str);

char *t = api->godot_char_string_get_data(&buf);
int len = api->godot_char_string_length(&buf);

// copy the data or use it otherwise

// free the Godot-allocated buffer
api->godot_char_string_destroy(&buf);
```

**Comment by BastiaanOlij** [comment]
Ah.. by ascii you mean text purely using the first 7 bits? the last 128 characters can't be used directly.
I figured it out in the end and got everything working again but I still feel its too many steps for something so often used :)

but hey, it works..

**Pull request merged**
