### PR TITLE
Fixes a canvas item set to clip children being drawn as black if no children are visible

### LINKED ISSUE #69179: CanvasItem with clip_children in any enabled mode draws black if all children are invisible
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

macOS Ventura 13.0.1, Radeon Pro 560X (MacBook Pro 15" 2018)

### Issue description

If a CanvasItem-inheriting object (Sprite2D, Polygon2D, etc) has `clip_children` set to "Clip Only" or "Clip + Draw", the entire object will render opaque black if either it has no children at all, or if all its children have `visible` set to `false`. Setting the alpha of the `modulate` color of the children is the same as setting `visible == false`, however setting `self_modulate` does not produce this effect, and thus can be used as a workaround.

### Steps to reproduce

- In a new or existing scene, create a CanvasItem-inheriting object, such as a Sprite2D / Polygon2D.
- Assign a texture / otherwise ensure it has some clippable area to draw.
- Create a child on this object that is also a CanvasItem-inheriting object, such as a Sprite2D / Polygon2D.
- Set `clip_children` on the parent object to "Clip Only" or to "Clip + Draw".
- Toggle visibility of the child object and observe the result.

https://user-images.githubusercontent.com/4956530/204049323-9af1e633-23a2-4e1a-a0bd-3a6209926deb.mov

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by SlugFiller**
…hildren are visible

Fixes #69179. And a couple of other minor things.

### CODE REVIEW

**Review by clayjohn — APPROVED** [review]
Changes look good. Tested locally and can confirm that this works. I also tested out the normal case and the case where the parent item has a custom material and I didn't notice any regressions.

**Comment by akien-mga** [comment]
Thanks!

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1.

**Comment by felbecker** [comment]
Possible regression in 4.0.1: Nested clip only nodes do not work correctly. I would expect if both parent and grandparent of a node have clip only, that only the intersect of both parent and grand parent is visible. This was working as expected before 4.0.1.

Is this intended?

**Comment by felbecker** [comment]
Yes you are right, what I described does not work,

However, there is still a difference in behavior not described in this PR (as far as I can tell). For clarity, say I have the described setup:

grandparent (clip only)
. parent (clip only)
.. node 

In 4.0.1, changing clip only of `parent` does not make a difference in how `node` is clipped, but it swappes the drawing order of `parent` and `node`.
Whereas in 4.0.0 the mask of `parent` **is** applied to `node` but **inverted**. 

It can be reproduced with `icon.svg` in empty 4.0.0 and 4.0.1 projects respectively.

Since I am not deeply into this, it might very well be the case that the behavior of 4.0.0 was a bug that was fixed by this PR. If that's so, how could I reproduce the behavior of 4.0.0 in 4.0.1 in a "correct" way?

**Comment by SlugFiller** [comment]
This PR doesn't make any changes to draw order. However, if that's the behavior you want, you can simply use "Draw behind parent" on the child node, and that would do the trick. No need to give the parent a clipping that would only be ignored. There was also a report on cascaded clip being inconsistent between renderers in 4.0. So whatever effect you were seeing may have been different between GLES3 and Vulkan, and may have just been an artifact that could just as easily result in corrupt display.

**Pull request merged**
