### PR TITLE
Ensure that Lambert is energy conserving.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tagcup** [comment]
Quick note: this also fixes a problem with the Oren-Nayar PR that just got merged today.

**Comment by groud** [comment]
cc @reduz

**Comment by reduz** [comment]
Ok, I finally undestand why it had to be divided, it makes it energy conserving.. This bit did not make sense before for Lambert but now it does.

**Comment by tagcup** [comment]
But that's the whole point of PBR, isn't it ;)

Also, for non-physical lighting models such as toon which can't be expressed in terms of a BRDF (such that there's nothing to normalize), I think it's probably best to introduce an overall such that they visually compare OK to normalized Lambert. Or actually better yet, if their contribution to total radiance is in the form h(L,V,N) baseColor, we can simply integrate this over the upper hemisphere to find a normalization factor such that it won't emit more than incoming, of course that needs to be done together with it's corresponding BSDF

**Comment by tagcup** [comment]
err I mean there is no BSDF either for toon etc, I meant their specular contribution

**Pull request merged**
