### PR TITLE
zlib/minizip: Update to version 1.3

### PR DESCRIPTION
**Pull request by akien-mga**
Upstreams the fix from #73310, so we can remove that patch. Remove `infback.c` which we stopped compiling after #79273. (Note for `3.x` cherrypick: that file should be removed from `core/SCsub` too.)

The `OF` macro was also removed so I can drop the patch where I yell at Gentoo developers.

Would be nice if we could look at upstreaming the seek functionality we added to minizip, so that we no longer need to rely on a hard fork and can compile Godot against distro minizip too.

### CODE REVIEW

**Review by RedworkDE — APPROVED** [review]
Not sure how reviewing 3rd party update are normally supposed to work, but the changed files look expected, it still compiles and appears to still work correctly, so I guess this looks good to me.

**Comment by YuriSizov** [comment]
Cherry-picked for 4.1.3

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.4.

**Pull request merged**
