### PR TITLE
Convert simple uses of `WorkerThreadPool` to parallel `for_range()`

### PR DESCRIPTION
**Pull request by myaaaaaaaaa**
Simplifies threading compared to direct usage of `WorkerThreadPool`, since there is no longer a need for intermediate functions or structs.

`image_compress_cvtt()` may experience performance regressions until #72716 is merged.

This has not been tested. Tread with caution.

### CODE REVIEW

**Review by RandomShaper — APPROVED** [review]
I think I already said I'm loving all this parallel for refactor.

**Comment by RandomShaper** [comment]
Regarding the review, everything looks correct to me. Let's test it in the wild.

**Review by clayjohn — COMMENTED** [review]
This PR warrants some discussion with the production team as it strongly encourages the use of lambdas. Currently we discourage the use of lambdas in the codebase except for in a few key places.

**Comment by RandomShaper** [comment]
Other `for_range` PRs have been already merged. Of course, feel free to discuss the matter, but I'm sure you'll come to the conclusion that this is one of those key cases that should be considered. 😁 I myself have used lambdas in other PRs where they avoided the need for the boilerplate of adding a one or two-lined static member functiton because of syntactic needs. That said, this for-range use case is even more natural, as lambdas allow to get closer to first-class support in the language (similar to what OMP makes possible).

**Comment by clayjohn** [comment]
> for_range

Ah, I see I was mistaking this PR for https://github.com/godotengine/godot/pull/72784 which was already merged awhile ago. Oh well, I'll defer to your judgement here

**Pull request closed without merging**
