### PR TITLE
AnimationPlayer - Fixed Audio playback and implemented offsets and blending for AnimationKeys (new feature)

### PR DESCRIPTION
**Pull request by TypeOverride**
I solved 3 bugs. And asking for a merge.

Furthermore i changed the AnimationKey that was StringName and not a structure like the other Keys that are definied (for example AudioKey). Now i made an AnimationKey structure like the other have. So it can be extended more easily and i can implement new features.

I dont know if you can seperate it from the pull request on merging.... the offsets vars in the AnimationKey structure are right now not used in code for logic.

But some small fixes i made are in, as well, that should be merged (and the rest i do i hope as well):
(there are some comments of mine in :S i hope they can merged out somehow!?)

AudioTrack on AnimationPlayer is playing in loop when there is no end offset [FIX INCLUDED]
https://github.com/godotengine/godot/issues/26555

Audio playback on AnimationPlayer is not stopping when reaching end of track [FIX INCLUDED] 
https://github.com/godotengine/godot/issues/26559

AnimationPlayer AnimationTrack Bug - No animation via moving the timeline cursor [FIX INCLUDED]
https://github.com/godotengine/godot/issues/26548

My goal is to make: 
1) transitions / blendings for AnimationKeys on the AnimationTrack.
2) make offsets like the AudioKey has, but on AnimationKeys. 
3) make a loop feature. So the AnimationKey is shown looped on the timeline.

So the AudioKey and the AnimationKey should look like this in the end:
```
struct AnimationKey {
		StringName animation;
		float start_offset; //offset from start
		float end_offset; //offset from end, if 0 then full length or infinite
                bool loop;
		AnimationKey() {
			start_offset = 0;
			end_offset = 0;
                        loop = false;
		}
	};
```
Transitions / blendings could be solved by overlapping or maybe a transition value. Or via the space between the different AnimationKeys. I will see what works out best.

The "Applied an AnimationKey structure for further work with AnimationTrack" commit, included the fix of the "AnimationPlayer AnimationTrack Bug - No animation via moving the timeline cursor (https://github.com/godotengine/godot/issues/26548)"

### CODE REVIEW

**Comment by akien-mga** [comment]
While I'm interested in the bugfixes for the issues reference, the rest is way too intrusive for 3.1.

**Comment by akien-mga** [comment]
The code style is also wrong, please see [Code style guidelines](http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html).

**Comment by TypeOverride** [comment]
> The code style is also wrong, please see [Code style guidelines](http://docs.godotengine.org/en/latest/community/contributing/code_style_guidelines.html).

I reworked the "Audio Playing" now on the AnimationPlayer.
There were 2 more bugs i fixed. One is on from "Play from start". It was ignoring the key. And one on loop where he ignores the key as well when the key was shifted into negative values on the timeline a little bit.

Now its working like excepted. Tested much variations. Seems fine.
functional Audio backwards playing are not supported right now. But i know how to solve i easily. But with one drawback. 

I have no clue. How to merge it.... maybe you fix it on your own. Or try to look what i made to get around the bugs / fix the bugs.

**Comment by TypeOverride** [comment]
Maybe i post here my code in and you can merge it? Its not much ..but fixing everything on Audio_playing (forward and one bug backwards):

"animation_player::_animation_process_animation(...)"

```
case Animation::TYPE_AUDIO: {
				if (!nc->node)
					continue;
				if (p_delta == 0) {
					continue;
				}

				int idx = -1;
				if (p_seeked) { //find whathever should be playing
					idx = a->track_find_key(i, p_time);
				} else { //find stuff to play
					List<int> to_play;
					a->track_get_key_indices_in_range(i, p_time, p_delta, &to_play); //not working for backward playing. Looking for different solution. Maybe using only track_find_key and check idx if left or enter
					if (to_play.size()) {
						idx = to_play.back()->get();
					}
				}

				bool stop = false;
				if (idx != -1) {
					Ref<AudioStream> stream = a->audio_track_get_key_stream(i, idx);
					if (stream.is_valid()) {
						float start_ofs = a->audio_track_get_key_start_offset(i, idx);
						if (p_seeked) {
							start_ofs += p_time - a->track_get_key_time(i, idx);
						}
						float end_ofs = a->audio_track_get_key_end_offset(i, idx);
						float len = stream->get_length();

						float diff = (len - end_ofs) - start_ofs;
						if (diff > 0) { //if (start_ofs > len - end_ofs) {
							nc->node->call("set_stream", stream);
							nc->node->call("play", start_ofs);

							nc->audio_playing = true;
							playing_caches.insert(nc);

							nc->audio_len = MIN(MAX(0, len - start_ofs - end_ofs), len);
							nc->audio_start = p_time;
						} else {
							stop = true;
						}
					}
				}

				if(!stop && nc->audio_playing) {
					int dir = sgn(p_delta);
					if ((dir > 0 && p_time < nc->audio_start) || (dir > 0 && p_time >= a->get_length()) || (dir < 0 && p_time > nc->audio_start) || (dir < 0 && p_time <= 0)) {
						stop = true;

					} else {
						float audio_clamp_len = MAX(MIN((nc->audio_start + nc->audio_len), a->get_length()), 0);
						float value = audio_clamp_len - p_time;
						if (value <= 0) {
							stop = true;
						}
					}
				}

				if (stop) {
					//time to stop
					nc->node->call("stop");
					nc->audio_playing = false;
					playing_caches.erase(nc);
				}

			} break;
```
And in animation_player::animation_process_data(...)
```
...
                //
		bool has_dir_changed = (sgn(delta) != sgn(next_pos - cd.pos)); //<-------
		if (has_dir_changed && cd.pos != next_pos) { //<-------
			p_seeked = true; //<-------
		}
	}

	cd.pos = next_pos;

	_animation_process_animation(cd.from, cd.pos, delta, p_blend, &cd == &playback.current, p_seeked, p_started);
```

AnimationPlayerEditor::_play_pressed():
```
if (current != "") {

		if (current == player->get_assigned_animation())
			player->stop(); //so it won't blend with itself
		player->play(current);

		float time = player->get_current_animation_position(); //<-------
		player->seek(time); //<-------
	}
```

Thats all to fix the Audio playback

**Comment by TypeOverride** [comment]
in my latest update forward audio playing should work fine in all cases i can imagine.

Tomorrow i will make the backward playing working. For nice gameplay effects as well.

At all i fixed 5 Bugs i recognized. And backward playing should be possible now as well more easily.

**Comment by TypeOverride** [comment]
> While I'm interested in the bugfixes for the 3 issues referenced, the rest is way too intrusive for 3.1.

in my latest update forward audio playing should work fine in all cases i can imagine.

Tomorrow i will make the backward playing working. For nice gameplay effects as well.

At all i fixed 5 Bugs i recognized. And backward Audio playing should be possible now as well more easily to implement.

**Comment by TypeOverride** [comment]
> While I'm interested in the bugfixes for the 3 issues referenced, the rest is way too intrusive for 3.1.

Maybe I have your interest now?

I've implemented the same Key-Behaviour on the AnimationPlayer for an Animation that a Audio-Key has too.

I can make a video of it later and post it here. But i think its a need need feature. It helps me a lot now in my project to make further progress. 

I will have to make some fixes today on my implementation here, but it should be realtive bug-free (in comparsion). There is one case where im not very lucky about. But i will look later on Unity if the behaviour is similar. Maybe it should be the default behaviour. Maybe not. I will see.

**Comment by TypeOverride** [comment]
Here is a video of the new feature on Animation Track.
More or less i used same / simlar code like for the AudioKey. So it was not such a big deal. And i rewrote the TYPE_ANIMATION code on timeline. Like i did with TYPE_AUDIO. Both should now work like it should be.

https://www.youtube.com/watch?v=0t3_yYInLuY

**Comment by TypeOverride** [comment]
sorry guys. I think i requested a hole bunch of developers here. I only did:
https://help.github.com/en/articles/syncing-a-fork

because someone commited something on the animation stuff. So i had to make a merge.

I think i have to use here "rebase" or something? I think i committed all the files you guys made the last 2 or 3 days as well with this now. 

how can i clean it up? Using rebase?

**Comment by TypeOverride** [comment]
Here is a video of the blending feature ( https://www.youtube.com/watch?v=cBgXhTBTPN4 ) - you will see that the AnimationKey are now blend together on playing:
[](https://www.youtube.com/watch?v=cBgXhTBTPN4)

Its not finished right now. Its only working on playing right now. Not a seeking or delta 0.

**Comment by reduz** [comment]
This looks super intereting, but the PR is a mess, maybe start over from a new one?

**Comment by TypeOverride** [comment]
> This looks super interesting, but the PR is a mess, maybe start over from a new one?

I have no clue how to make it cleaner with all this synchronizing on version control systems. I dont make it build-compatible. Only coding my features in to make cutscenes in a good way. Everyone can look into my code if they think they need something and implement it somehow in their code.

My new feature now will be a BlendShapeTrack. I hate to animate BlendShapes on a Track.

**Comment by TypeOverride** [comment]
Here is a video of the BlendShapeTrack feature ( https://www.youtube.com/watch?v=pWCkWOc6I60 ) - you will see that you can use one BlendShapeTrack instead use multiple ValueTracks for BlendShapes on an AnimationPlayer:
[](https://www.youtube.com/watch?v=cBgXhTBTPN4)

**Comment by vnen** [comment]
We have a small guide about the PR workflow with some Git instructions: http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html

One problem is that you have a lot of redundant commits that fix your own code. Since those are pointless in the long history, we ask you to rebase onto a single commit (or a few relevant commits if that's the case). Also it's not passing the CI, so you need to fix the errors.

Other problem is that you are adding commented code. If those aren't used you can simply remove them. You don't even need to comment old code since those will be tracked by Git anyway.

If you don't want to change your fork's master branch, you can create another one and make a PR from that new branch so you can work in both branches separately. You might also want to split the bugfixes in a different PR since those are usually more interesting and easier to merge, then add the features on a new one so it can be reviewed for a longer time (if it's not finished, it's better if wait until it's done before opening the PR).

**Comment by akien-mga** [comment]
Closing as this can't be merged as is.

**Pull request closed without merging**
