### PR TITLE
Better looking spatial editor grid

### PR DESCRIPTION
**Pull request by djrm**
Adds grid that fades with the distance, also has major grid lines
screenshot from 2017-09-08 18-49-10

### CODE REVIEW

**Comment by toger5** [comment]
Love it, merge IT.

**Comment by hpvb** [comment]
Looks great!

**Comment by Zylann** [comment]
I find there is an issue with the divisions of the grid, their colors are bleeding on neighbor lines. It would be cleaner if minor line colors weren't affected by major lines, like this:

image

**Comment by djrm** [comment]
@Zylann yeah i think i will implement that

**Pull request merged**
