### PR TITLE
Add often used built-ins (camera-pos, object-pos, camera-eye etc.) to spatial shaders

### PR DESCRIPTION
**Pull request by paddy-exe**
Implements this proposal: https://github.com/godotengine/godot-proposals/issues/4957

## (Updated) Syntax of implementation for written shaders
```glsl
vec3 node_pos_world = NODE_POSITION_WORLD;
vec3 camera_pos_world = CAMERA_POSITION_WORLD;
vec3 camera_dir_world = CAMERA_DIRECTION_WORLD;
vec3 node_pos_view = NODE_POSITION_VIEW;
```

## (Updated) Showcase in visual shaders:
image

## (Old syntax) Showcase in written shaders:

https://user-images.githubusercontent.com/38077837/181753591-213fff1c-b6e5-4267-b286-5ac65cba0a3e.mp4

### CODE REVIEW

**Comment by QbieShay** [comment]
Hey @paddy-exe , thank you so much for this!

**Comment by QbieShay** [comment]
Because the fragment is in view space, I think it could be useful to have those variables as well in view space

**Comment by Chaosus** [comment]
It's more of the rendering stuff (which is not my strong side), I don't know how useful is it, honestly. On the visual shader side, it looks correct.

**Comment by Chaosus** [comment]
Seems useful, especially for visual shaders.

**Review by Chaosus — APPROVED** [review]

**Comment by William-Godwin** [comment]
Is it possible to add the same variables to the particle shader? This would be very handy for some effects. I think...

**Comment by QbieShay** [comment]
Proposition to rename "ObjectViewPosition" and "ObjectWorldPosition" to "NodePositionView" and "NodePositionWorld"

Of note, all other engines work in either world or object space, we are the only one working in view space.

@clayjohn @Calinou @reduz opinions on the names?

**Comment by clayjohn** [comment]
> Proposition to rename "ObjectViewPosition" and "ObjectWorldPosition" to "NodePositionView" and "NodePositionWorld"
> 
> Of note, all other engines work in either world or object space, we are the only one working in view space.
> 
> @clayjohn @Calinou @reduz opinions on the names?

I have no strong opinion on the naming. Object to me sounds more natural, but Node fits better with the naming we use outside of shaders so it is likely more approachable for users. I would go with Qbie's suggested names for now.

I am a little confused about ``CAMERA_WORLD_EYE`` The eye vector usually refers to the direction between a fragment/vertex and the camera. I expected this to return the direction between the object center and the Camera in world space, but of course that is not what this does. Can you clarify what it is ``CAMERA_WORLD_EYE`` is supposed to represent so we can figure out a more intuitive name?

**Review by akien-mga — APPROVED** [review]
Approved in PR review meeting.

Last change requested would be to rename `CAMERA_EYE_WORLD` to `CAMERA_DIRECTION_WORLD` (proposed by @JFonS and approved by @QbieShay and @reduz).

**Comment by akien-mga** [comment]
Thanks!

**Comment by celyk** [comment]
`actions.renames["CAMERA_DIRECTION_WORLD"] = "scene_data.view_matrix[3].xyz";`

Shouldn't that be using `-scene_data.inv_view_matrix[2].xyz`, as in the camera forward vector?

**Pull request merged**
