### PR TITLE
CI: Update Linux runners to Ubuntu 24.04

### PR DESCRIPTION
**Pull request by Repiteo**
Updates Linux runners from 20.04/22.04 to 24.04. The only exception is `linux_builds`, going from 20.04 to 22.04, for the sake of artifact portability

### CODE REVIEW

**Comment by Repiteo** [comment]
Hmm, so the minimum Python version that 22.04 supports is `3.7`. I'll add a conditional to use 20.04 for the legacy check, but we might want to update our Python minimum soon

**Comment by akien-mga** [comment]
Yeah Python 3.6 has been EOL for 3 years now, we can likely drop support for it too.

Python 3.8 just went EOL, we could probably use it as our new min version and not cut off too many users on legacy distros or Python setups.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Testing locally, I also need to do this fix, like in my `3.x` PR:
```diff
diff --git a/scene/2d/tile_map.cpp b/scene/2d/tile_map.cpp
index ddb0635f6b..1bfd1fed5a 100644
--- a/scene/2d/tile_map.cpp
+++ b/scene/2d/tile_map.cpp
@@ -75,7 +75,8 @@ void TileMap::_set_tile_map_data_using_compatibility_format(int p_layer, TileMap
 	for (int i = 0; i < c; i += offset) {
 		const uint8_t *ptr = (const uint8_t *)&r[i];
 		uint8_t local[12];
-		for (int j = 0; j < ((p_format >= TileMapDataFormat::TILE_MAP_DATA_FORMAT_2) ? 12 : 8); j++) {
+		const int buffer_size = (p_format >= TileMapDataFormat::TILE_MAP_DATA_FORMAT_2) ? 12 : 8;
+		for (int j = 0; j < buffer_size; j++) {
 			local[j] = ptr[j];
 		}
 
```

For the PacketPeerUDP / RingBuffer stringop-overflow, I don't reproduce it locally with GCC 14 for some reason.
But I wondered if this would solve it?
```diff
diff --git a/core/io/packet_peer_udp.h b/core/io/packet_peer_udp.h
index c69a138c53..724a902960 100644
--- a/core/io/packet_peer_udp.h
+++ b/core/io/packet_peer_udp.h
@@ -49,7 +49,7 @@ protected:
 	uint8_t recv_buffer[PACKET_BUFFER_SIZE];
 	uint8_t packet_buffer[PACKET_BUFFER_SIZE];
 	IPAddress packet_ip;
-	int packet_port = 0;
+	uint32_t packet_port = 0;
 	int queue_count = 0;
 
 	IPAddress peer_addr;
```

**Comment by fire** [comment]
Seems to be a requirement for https://github.com/godotengine/godot/pull/89660 because of GCC versions?

**Comment by akien-mga** [comment]
You _might_ be able to remove this, if Ubuntu 22.04 has a recent enough version of Mesa.
```
      # Need newer mesa for lavapipe to work properly.
      - name: Linux dependencies for tests
        if: matrix.proj-test
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB8B81E14DA65431D7504EA8F63F0F2B90935439
          sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
          sudo apt-get install -qq mesa-vulkan-drivers
```
If not, the `focal` part needs to be updated to `jammy` (Ubuntu version codename).

**Comment by Repiteo** [comment]
I'll keep this a draft until your implementation is merged, so I'll know what to reference

In the meantime, I'll cook up a PR making 3.8 the minimum Python version

**Comment by Calinou** [comment]
> Python 3.8 just went EOL, we could probably use it as our new min version and not cut off too many users on legacy distros or Python setups.

Doing so will break [Pyston](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_linuxbsd.html#using-pyston-for-faster-development) though, which I still rely upon as it allows for faster rebuilds. CPython 3.13 onwards is starting to focus on performance, but it's not at the level of Pyston yet.

**Review by Calinou — APPROVED** [review]

**Review by aaronfranke — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by clayjohn** [comment]
This caused a regression for tilemaps. This is how the Isometric demo looks now:

image

**Comment by dustdfg** [comment]
> > Python 3.8 just went EOL, we could probably use it as our new min version and not cut off too many users on legacy distros or Python setups.
> 
> Note that raising the requirement _above_ Python 3.8 will break [Pyston](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_linuxbsd.html#using-pyston-for-faster-development) though, which I still rely upon as it allows for faster rebuilds.
> 
> CPython 3.13 onwards is starting to focus on performance, but it's not at the level of Pyston yet. (There is also an experimental JIT, but it doesn't work with SCons.)
> 
> Unfortunately, Pyston is unmaintained these days, so it won't see any support newer than Python 3.8. Sphinx has already dropped Python 3.8 support, but SCons still supports it for now.

Today I've tested speed of Pyston in comparison to CPython and it is not so astonishing now. I've run builds on already built repo so it just needed to execute python:
 

**Pyston 2.3.5: ~17.5s
CPython 3.12.6: ~20.2s**

And these are results of my low-end i3 which makes clean build 1.5 hours. I think you even won't notice any difference on your hardware. I even didn't try CPython 3.13 with enabled JIT...

**Pull request merged**
