### PR TITLE
TileSetEditorPlgn: Fix a leak

### LINKED ISSUE #17061: Leaks found in tile_set_editor_plugin.cpp
**Godot version:**
master branch commit 7568a455397aeefc1e08600534ec4df279abab70

**Issue description:**
The following two `memnew` calls are leaking:
https://github.com/godotengine/godot/blob/636e48b707e0b3d062ca073b92e2fff47460baf5/editor/plugins/tile_set_editor_plugin.cpp#L319

```
==9077== 464 (272 direct, 192 indirect) bytes in 1 blocks are definitely lost in loss record 199 of 264
==9077==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==9077==    by 0x1C3FCF1: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==9077==    by 0xCB5633: TileSetEditor::initialize_bottom_editor() (tile_set_editor_plugin.cpp:319)
==9077==    by 0xCB918E: TileSetEditor::TileSetEditor(EditorNode*) (tile_set_editor_plugin.cpp:561)
==9077==    by 0xCB9430: TileSetEditorPlugin::TileSetEditorPlugin(EditorNode*) (tile_set_editor_plugin.cpp:1874)
==9077==    by 0xAEDB03: EditorNode::EditorNode() (editor_node.cpp:5683)
==9077==    by 0x2D941E: Main::start() (main.cpp:1441)
==9077==    by 0x2BA6D5: main (godot_x11.cpp:54)
```

https://github.com/godotengine/godot/blob/636e48b707e0b3d062ca073b92e2fff47460baf5/editor/plugins/tile_set_editor_plugin.cpp#L404

```
==9077== 1,456 (1,096 direct, 360 indirect) bytes in 1 blocks are definitely lost in loss record 217 of 264
==9077==    at 0x4C2CEDF: malloc (vg_replace_malloc.c:299)
==9077==    by 0x1C3FCF1: Memory::alloc_static(unsigned long, bool) (memory.cpp:83)
==9077==    by 0xCB6231: TileSetEditor::initialize_bottom_editor() (tile_set_editor_plugin.cpp:404)
==9077==    by 0xCB918E: TileSetEditor::TileSetEditor(EditorNode*) (tile_set_editor_plugin.cpp:561)
==9077==    by 0xCB9430: TileSetEditorPlugin::TileSetEditorPlugin(EditorNode*) (tile_set_editor_plugin.cpp:1874)
==9077==    by 0xAEDB03: EditorNode::EditorNode() (editor_node.cpp:5683)
==9077==    by 0x2D941E: Main::start() (main.cpp:1441)
==9077==    by 0x2BA6D5: main (godot_x11.cpp:54)
```

I'm not quite sure where and how to free these.

### PR DESCRIPTION
**Pull request by ghost**
fixes #17061 

Thanks Rubonnek!

### CODE REVIEW

**Comment by akien-mga** [comment]
Nothing to cherry-pick actually, there was no leak in `AutotileEditor` in 3.0.

**Comment by Noshyaar** [comment]
It is actually fixed before 3.0 by #15963 but reintroduced in #16742.

@damarindra is this revert intentional?

**Comment by akien-mga** [comment]
I think @damarindra missed a few changes when rebasing their branch on top of the current master, and some fixes were lost.

**Comment by Rubonnek** [comment]
@Noshyaar Thanks for fixing this!

**Comment by damarindra** [comment]
Sorry for it, will be more careful next time.

**Pull request merged**
