### PR TITLE
Add some folders which would benefit from scu to scu pipeline

### PR DESCRIPTION
**Pull request by ghost**
Used SCU and saw that some big/medium size folders aren't processed with SCU

### CODE REVIEW

**Comment by lawnjelly** [comment]
Yes it's super possible that this will be a good idea, as there have been folder changes / new folders since the original SCU PR, and we may be missing out on speedup.

Timings for full rebuilds before / after are particularly useful for this kind of thing.

I'll try the PR. :+1:

**Comment by dustdfg** [comment]
It is only several folders but they contain many files. Timings of my rebuilds usually take 30min so honestly it is not what I really want to measure (because to make consistent measurements I need 1h doing nothing with device)... I can make a screenshots of the build process where lots of lines are not scu...

**Comment by lawnjelly** [comment]
On my machine with clean builds:

Before: 2mins 54
After: 2mins 39

Some of the folders added won't make a whole lot of difference (where there are e.g. just 2 cpp files) but on the whole this seems worth doing. The checks indicate it compiles fine with different platforms but we should watch for any build regressions in the next few days after merging.

Other than that it should be pretty safe if no name conflicts are detected by compiler.

**Review by lawnjelly — APPROVED** [review]

**Review by Repiteo — APPROVED** [review]
Makes sense to me!

**Comment by Repiteo** [comment]
Thanks!

**Pull request merged**
