### PR TITLE
[Scene] Add `SceneStringNames::panel`

### PR DESCRIPTION
**Pull request by AThousandShips**
See also:
* https://github.com/godotengine/godot/pull/91939

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by AThousandShips** [comment]
Rebased on top of https://github.com/godotengine/godot/pull/91949 for conflicts, should merge safely if done in order

**Comment by akien-mga** [comment]
Thanks!

**Comment by AThousandShips** [comment]
Thank *you*!

**Pull request merged**
