### PR TITLE
Create Checkbox class with support for Radio Buttons

### PR DESCRIPTION
**Pull request by MarianoGnu**

### CODE REVIEW

**Comment by MarianoGnu** [comment]
I think i'll refactor this to have better radio buttons

**Comment by reduz** [comment]
as you wish, when i'm done with the features i'll start merging

**Comment by MarianoGnu** [comment]
Previus issues sems to be fixed... please someone test this?

**Comment by theuserbl** [comment]
Have tried to compile it on Linux and become this error:
scene/gui/check_box.cpp:64:5: warning: identifier 'nullptr' is a keyword in C++11 [-Wc++0x-compat]
     } while (parent != nullptr);
     ^
scene/gui/check_box.cpp: In member function 'bool CheckBox::is_radio()':
scene/gui/check_box.cpp:64:24: error: 'nullptr' was not declared in this scope
     } while (parent != nullptr);
                        ^
Seems for your changes the compiler needs some additional options.
Or can you replace the 'nullptr'-parts with code of an older C++ standard?

**Comment by MarianoGnu** [comment]
Replacing nullptr for NULL or 0 should be enought. Sorry about that, I use C++98 compiler.

**Comment by MarianoGnu** [comment]
@theuserbl test this again please.

**Comment by theuserbl** [comment]
Hmmm.. it compiles now fine.
And it is a nice Checkbox. But wasn't there something with an Option that it could be also a Radiobutton?
If I select in the properties under "Custom Icons"
"Radio checked" or "Radio Uncheked", there comes the error

ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:228.
ERROR: add_icon_override: Condition ' p_icon.is_null() ' is true.
   At: scene/gui/control.cpp:1965.

And it still looks all like an Checkbox.

I also deliberate, if it wouldn't be better, to have the Radiobutton as an own control instead of an Checkbox-skin?
Normally Radiobuttons have also an other function, then Checkboxes. Checkboxes are for its alone checked ("x") or unchecked (" ") or in some cases an unsure or so ("-").
But Radiobuttons are mostly in groups, where at maximum one is checked. And if an other Radiobutton is checked, the current checked one will be automatically uncheckt.

**Comment by MarianoGnu** [comment]
@theuserbl it "becomes" automatically a radio buttons when it's child of a button group.

**Comment by MarianoGnu** [comment]
You have two choices to manage the selection: conecting every set_pressed signal to a different method or use the buttongroup signal pressed wich sends a reference to the pressed button.

**Comment by theuserbl** [comment]
That with the buttongroup works. Nice. :-)
The only sad thing is, that your control needs a little documentation. If you don't know, that the Checkbox mutates to a Radiobutton, if it is in a Buttongroup, you probably never find it out.

The helpfile to your Checkbox control is also only the automatic generated.
Possible you can in doc/base/classes.xml or tools/docdump/class_list.xml write a more detailed documentation for your file.

But the images for your Radiobutton have sadly the wrong colors for that theme. The colors of the Checkboxes are right.
I have now tested a little bit, how a Radiobutton in Godot could look like:
chk

First column your Checkboxes. Secon column your Radiobuttons. The next columns I have tried out some other Radiobuttons.

**Comment by MarianoGnu** [comment]
My Radiobuttons are extracted from slider handler, so it matches the current theme... I feel the other options doesn't look very much as a radiobox, The 5th one is the best so far... lets hear someone else's opinion on this?

About Buttongroup ussage, the reason to use it is because that's the use thought for, if you think of it, the only difference beatwhen checkbox and checkbutton are auto-styleboxes. i could have modified checkbutton's styleboxes and add the is_radio() check, But this would make current dialogs to look wrong...

**Pull request merged**
