### PR TITLE
Android and iPhone location manager implementation

### PR DESCRIPTION
**Pull request by cagdasc**
### Android 
I have implement **Fused Location Provider Client** for get user locations and make creative games like Pokemon. With this implementation I have to migrate Android project to AndroidX because of latest location library has androidx libraries and it gives errors while compiling java project. In additional I have implement **ACCESS_COARSE_LOCATION** and **ACCESS_FINE_LOCATION** permissions.

### iPhone
I have implement **CLLocationManager** for get user locations and make creative games like Pokemon. In iPhone you need to ask location usage permission to user so I have implement `request_permission(const String &p_name)` method to iPhone such as Android and add `NSLocationWhenInUseUsageDescription` check box to export options.

### Comments
This is basic implementation and I opened this PR to see missing things such as true implementation of `LocationManager`, `LocationParam`, `LocationResult`, memory usage(memnew and memdelete) and module definition and usage. After if review is okay, I will add documentation. I will push commits for master branch.

### Sample Project
You can test this branch with [this sample project](https://github.com/cagdasc/godot-samples)

Thank you.
Cagdas.

*Bugsquad edit:* This closes https://github.com/godotengine/godot-proposals/issues/57.

### CODE REVIEW

**Comment by volzhs** [comment]
does it compile successfully with `scons platform=android module_location_enabled=no` also?

**Comment by m4gr3d** [comment]
@cagdasc This type of functionality should belong in a Godot plugin, and not in the main codebase.

**Comment by cagdasc** [comment]
@volzhs I think it does not compile successfully because `app_delegate` and `Godot.java` depends on location library/framework. Maybe it can be part of core.

@m4gr3d why this type of functionality should not in main codebase?

**Comment by m4gr3d** [comment]
@cagdasc For several reasons, but the most prominent would be:
- It's not a core use-case for the Godot engine. 
- On Android, the functionality is dependent on a closed source library (`com.google.android.gms:play-services-location:17.0.0`) that's updated often (e.g: would we need a new PR every time the play-services-location is updated).
- Same level of functionality can be achieved via a Godot plugin which has the added benefit of keeping the Android (& iOS) codebase clean, modular and easily maintainable.

As an additional point, the play services library has a lot of [functionality](https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project). Making location a core part of Godot means that we would need to do the same for other play services apis (e.g: cast, Google pay, etc...).

**Comment by cagdasc** [comment]
@m4gr3d I mentioned about this type of reservations in **Comments** section. While I was writing this code, I think `app_delegate.mm` and `Godot.java` were dependent on my module. So I will convert them into custom module written with `java` and `objective-c`.

 Thank you for your advice.

**Comment by Calinou** [comment]
> On Android, the functionality is dependent on a closed source library (`com.google.android.gms:play-services-location:17.0.0`) that's updated often (e.g: would we need a new PR every time the play-services-location is updated).

This is problematic for builds that target [F-Droid](https://f-droid.org/), as proprietary libraries can't be linked into applications.

**Comment by cagdasc** [comment]
Okay. I understand your concern but in other game engines like Unity, Cocos2d how they can handle this, I think(lcoations service is in core at Unity) they are bundled this services in engine. I don't insist for PR but only want to take your comments.

**Comment by cagdasc** [comment]
@volzhs First time I started this project locate in core but where? So I start coding make a module. I can easily move core.

**Comment by volzhs** [comment]
I guess this source will help.
https://github.com/kloder-games/godot-admob/tree/master/admob

**Comment by cagdasc** [comment]
I know writing module. I think and write this is core functionality. I only [specified](https://github.com/godotengine/godot/pull/32156#issuecomment-532106922) why not location manager core functionality?

https://github.com/cagdasc/godot-remote-config/tree/master/remoteconfig

**Comment by volzhs** [comment]
I think it can be included in core but also should compile templates without it too.
most of devs and games do not need it and keep it small and simple.

**Comment by volzhs** [comment]
https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/platform/iphone/detect.py#L161-L163

https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/platform/iphone/os_iphone.cpp#L171-L175

do these codes help?

**Comment by cagdasc** [comment]
This make sense. This approach can implemented with custom modul but in Android I need to ise jni for java bridging. I will try some examples.

**Comment by cagdasc** [comment]
@volzhs I don't understand one thing. Godot 3.1 build/export apk from build templates. So build templates already prepared and it has to include location or other libraries. For example I am a new game developer and choose Godot. I download engine from web site and download build templates in engine. After I don't want to use location but build templates already include location lib. So we can custom build with `module_location_enabled=no` and prepare our templates, this is clean way but in Godot release templates include libraries. But in master branch it could be different because we can export Android project.

**Comment by cagdasc** [comment]
I will make different implement for your review.

**Comment by m4gr3d** [comment]
@cagdasc Should this PR be closed?

**Comment by m4gr3d** [comment]
@cagdasc Closing this for now based on discussion. Feel free to re-open if you think it's still necessary.

**Pull request closed without merging**
