### PR TITLE
Fix import grayscale EXR

### LINKED ISSUE #27299: Godot fails to import greyscale EXR image (2)
Godot 3.1 stable
Windows 10 64 bits

https://github.com/godotengine/godot/issues/24247 has regressed and Godot still can't load greyscale EXR images.

Project:
[EXRSupport.zip](https://github.com/godotengine/godot/files/2993764/EXRSupport.zip)

### PR DESCRIPTION
**Pull request by goodyttoor**
Fix #27299

### CODE REVIEW

**Comment by Zylann** [comment]
This should be PRed to TinyEXR, but it's not the first time this problem occurred: https://github.com/syoyo/tinyexr/issues/99#issuecomment-445637063
So I'm surprised TinyEXR needs another fix.

**Comment by Zylann** [comment]
It appears the image will end up as RGBH, with 2 useless channels.

**Comment by goodyttoor** [comment]
I simply matched tinyexr method. This will result in extra (probably unused?) channels.

I will investigate the single channel import. Thank you very much.

**Comment by reduz** [comment]
Well, if it makes images open that did not open before this should be fine I guess, there are no other hdr formats you can import to anyway.

**Comment by Zylann** [comment]
@reduz that was the original request way back then, I wanted to be able to import an EXR that imports into an RH or RF image :p

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.1.

**Pull request merged**
