### PR TITLE
Fixes auto completion for singletons

### LINKED ISSUE #32873: Broken autocompletion for variables from singletons
**Godot version:**
Godot Engine v3.2.alpha2.official
**OS/device including version:**
Windows 10 (1709)
**Issue description:**
There's no autocompletion for custom (not built into the inherited class, on gif it is Node) vars from singletons, only for custom functions
**Steps to reproduce:**
p4mOKgN6w3

**Minimal reproduction project:**
[SingletonAutocompletion.zip](https://github.com/godotengine/godot/files/3734817/SingletonAutocompletion.zip)

### PR DESCRIPTION
**Pull request by EbbDrop**
Fixes: #32873

This is my first PR. Let me know if I did anything wrong.

### CODE REVIEW

**Comment by vnen** [comment]
Note that the email you used to commit is not linked to your GitHub account. It's not really a problem to merge, but the commit won't be attributed to your account. You can solve this by linking the used email to your account or changing your configured email in Git and amending the commit.

**Review by nathanfranke — APPROVED** [review]
Confirmed broken in master, after PR working flawlessly

**Comment by EbbDrop** [comment]
Changed email, thanks for the heads up.

**Comment by vnen** [comment]
It is a map, so a seconds insertion will replace the old one, which isn't really a problem.

**Review by vnen — APPROVED** [review]

**Comment by nathanwfranke** [comment]
If there is a second insertion, can one of them be removed to simplify code?

**Comment by bojidar-bg** [comment]
@nathanwfranke The one inside the `if` was added by #28122 to ensure that tool-mode scripts can have their properties defined in `_get_property_list` listed.

**Comment by EbbDrop** [comment]
It seems to work perfectly without the code from #28122. Singletons and tool-mode scripts.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
