### PR TITLE
Fix Automatic switch to viewport when playing a scene

### LINKED ISSUE #16357: Automatic switch to viewport in background when playing a scene
**Godot version:** 
Commit 4ab522799d833c5118f7335a7849d488f7fb3e35
(3.0)

**OS/device including version:**
Windows 10 x64
NVIDIA GeForce GTX 970

**Issue description:**
Hi!
When you play a 2d or 3d scene, the editor view tab automaticaly switches to 2d or 3d viewport (respectively) no matter the viewport you're currently using (gdscript editor included!).

It's maybe not a bug, but it becomes very annoying when you have to go back to the gdscript editor each time you launch your scene when debugging (yes I'm this kind of lazy guys :p).

As I think I'm not the only one to find it inconvenient I prepared a PR for this.

Just waiting your feedback before publish it (as it currently disables this autoswitch for 2d, 3d viewports and gdscript editor).

**Steps to reproduce:**
1 - Create a New Project
2 - Create a new Scene with either a 2D node or a Spatial node
3 - Go to the Script tab with F3
4 - Play the scene

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by Overblob**
Fixes #16357.
It's my first ever PR on Github. Hope it's fine :3

### CODE REVIEW

**Comment by akien-mga** [comment]
@Geequlim Is this fix OK? Or will there be a loss of functionality in the local debugger?

**Comment by Geequlim** [comment]
I'm not sure this won't break anything. But it is fine to the local debugger.

**Comment by Overblob** [comment]
Currently, the calling function (SceneTreeDock::_local_tree_selected) is only used when we want to hide the remote scene tree (by displaying the local tree instead) while stopping the script debugger. 
No other instance elsewhere.
Anyway, the deleted line enforced a node selection (the first one of the list or the last one selected, I dont remember exactly) in the local scene tree when switching to it. 
Maybe I'm wrong but in my opinion it shouldn't be necessary nor mandatory.

**Comment by akien-mga** [comment]
Yeah, it should be fine. Thanks!

**Comment by hpvb** [comment]
Cherrypicked into 3.0.3

**Pull request merged**
