### PR TITLE
Implement occlusion "soft-culling" to reduce LOD of occluded meshes rather than skipping drawing entirely

### LINKED ISSUE #2600: Autogenerated ShadowMesh uses same LoD level geometry as source Mesh
**Godot version:**
Godot 4.x
commit b4b7c97d3839170180e4f3f7c2bd3179b374057a

**OS/device including version:**
Win 10 64x

**Issue description:**
After testing the new ShadowMeshes in Godot 4.x and comparing the new feature with manual ShadowMeshes created for Godot 3.x I couldn't help but feel very disappointed by the performance (~80% less than Godot 3.x).

So I looked at the shadowmesh source code and I consider this an implementation bug and not a missing feature for a proposal.

Autogenerated shadowmeshes in Godot 4.x are matched to the same source mesh LoD level while they should be matched 1-3 LoD levels lower. A shadow imposter mesh created manual by an artist always starts at least 1-2 LoD levels below the visible LoD mesh but never at the same level. A typical example would be a characters hair mesh, starting at 150.000 vertex. The shadow looks the same with a LOD3 mesh that has only 5.000 vertex cause the outside mesh shape stays the same and this is enough for shadow casting on solid objects. In the current implementation the shadow casting mesh has a 145.000 vertex overhead that does nothing for the endresult and just consumes performance.

Due to this as mentioned in godotengine/godot#45452 pull request there is currently only a little performance gain with shadow imposters while it should be a considerable one.

I suggest that the autogenerated shadow imposters should be generated and matched with LOD2 or LOD3 meshes by default to fix this issue and give the expected performance boost from shadow imposters.

There is no reason to ever use the same mesh geometry detail for a shadow-only casting object except for edgecases like meshes mixed with semi-transparent surfaces and very lowpoly meshes (that don't need shadow imposters to begin with). A Shadowmesh LoD selection option in the new ResourceImporter would be welcome to solve those edgecases.

**Steps to reproduce:**

**Minimal reproduction project:**

### LINKED ISSUE #53288: Raster occlusion incorrectly culls objects through gaps
### Godot version

4.0 dev df57aa670

### System information

Linux Mint 20, Intel HD graphics 630

### Issue description

Objects are being culled when they should be visible, in cases where there are small gaps between occluders.

Setup:
Screenshot from 2021-10-01 08-45-37
What should be seen:
Screenshot from 2021-10-01 08-45-23
What is seen:
Screenshot from 2021-10-01 08-45-09
Occlusion buffer:
Screenshot from 2021-10-01 08-46-23

### Steps to reproduce

Create a couple of boxes as occluders and place them with a small gap, then attempt to view a 3rd object through the gap. Vary the viewing angle / distance.

### Minimal reproduction project

[TestOcclusion.zip](https://github.com/godotengine/godot/files/7265271/TestOcclusion.zip)

### Discussion

I'm just having a look at some situations likely to trip up the raster occlusion, especially edges / joins between objects. I'm guessing this is caused by the rendering of the occlusion buffer not being conservative (or rather the opposite of conservative rasterization :smile: ), i.e. gaps between objects are being joined. This makes occlusion more effective, but produces visual artifacts.

This one can be quite disturbing as objects flicker in and out of view according to the viewing angle, and whether or not a gap is rendered in the occlusion buffer.

### LINKED ISSUE #63771: Vulkan: Raster occlusion margin is too big on baked occluders
### Godot version

v4.0.alpha.custom_build.d29e95687

### System information

Win 10/64 NVIDIA GeForce GTX 1060/PCIe/SSE2

### Issue description

Simple scene w/ baked occluders

image

The background meshes do not occlude properly. Here you can see even at the start of the video the back ones should be hidden as soon as they are fully occluded, such as the left one as it begins. However, I have to move the camera until it is nearly inside the front object before the back ones turn off. But once you do go inside, the back objects turn on. So the camera is a few centimeters from the object before they turn off.

https://user-images.githubusercontent.com/632766/182137576-e34e0f0f-dd05-4ec1-9c16-2d042fc6e4a3.mp4

Here I made the front object 10x the size and pulled it back so the objects didn't overlap. Now the left back object is on, even though it's fully occluded. This is the border. If I move the camera just a hair right, the left object will turn off. 

image

image

### Steps to reproduce

Look at the MRP in overdraw mode.

### Minimal reproduction project

[test_occbake.zip](https://github.com/godotengine/godot/files/9233543/test_occbake.zip)

### PR DESCRIPTION
**Pull request by myaaaaaaaaa**
Occlusion "soft-culling" has less noticeable artifacts (LOD popping) than standard "hard-culling" (disappearing/flickering meshes):

https://user-images.githubusercontent.com/103326468/233419333-795560f0-39c7-465b-9a49-86ccf17b152f.mp4

This opens the door for more aggressive occlusion settings, and allows meshes that wouldn't normally be considered candidates for acting as occluders (trees/vegetation, vents, rough/dirty windows, smoke and other particles, etc) to be made feasible for that purpose.

This puts a greater reliance on depth testing to prevent overshading (Hierarchical Z makes this very cheap for low polycounts) and HLOD/visibility ranges to reduce draw calls.

Adds three new project settings:

- `rendering/occlusion_culling/soft_cull_lod_bias`
  LOD bias multiplier for occluded objects. 0 disables soft-culling (reverts to standard hard-culling)

https://github.com/godotengine/godot/assets/103326468/84a1520a-fd69-47d8-835c-967dc9b65f45

Left: `soft_cull_lod_bias` = 0 (hard-culling)
Right: `soft_cull_lod_bias` = 0.05

- `rendering/occlusion_culling/bounds_scale`
  Scale factor for occludee bounding boxes. Allows objects to be culled before they're fully occluded. Changing this is not recommended when hard-culling is active.

https://user-images.githubusercontent.com/103326468/233420140-6d67c867-9112-4ae7-a3bd-8fd529f7a3d3.mp4

Left: `bounds_scale` = 0.6
Right: `bounds_scale` = 0.1 (extreme value for demonstration purpose)

- `rendering/mesh_lod/lod_change/shadow_lod_bias`
  LOD bias multiplier for shadow passes. This had to be separated out from the normal LOD bias to avoid shadow popping artifacts, so it was easier to just include it in this PR.

Depends on #74118, marked as draft until that one is merged 

Fixes #53288
Fixes #63771
Fixes godotengine/godot-proposals#2600

### CODE REVIEW

**Comment by mrjustaguy** [comment]
regarding culling, would make sense for lights to be able to turn of shadows if they're culled, that way they are much cheaper, reduce atlas usage and don't pop in (aside from shadows)

Shouldn't Shadow Lod Bias be under Mesh LOD if it's not Occlusion culling related?

**Comment by Calinou** [comment]
Regarding shadow LOD bias, see also https://github.com/godotengine/godot-proposals/issues/2600.

**Comment by myaaaaaaaaa** [comment]
> regarding culling, would make sense for lights to be able to turn of shadows if they're culled, that way they are much cheaper, reduce atlas usage and don't pop in (aside from shadows)

Disabling lights whose corresponding meshes have been soft-culled is out of scope for this PR. Hopefully, this basic implementation of soft-culling is performant enough to make additional optimizations unnecessary :slightly_smiling_face: 

> Shouldn't Shadow Lod Bias be under Mesh LOD if it's not Occlusion culling related?

Yeah, I didn't really think these names through.

Should be fixed now.

**Comment by mrjustaguy** [comment]
You misunderstood, I'm talking if the light's AABB is occluded, instead of it getting turned off, you just turn off it's shadow casting, to free up the Shadow Atlas, and reduce it's cost a little too, while reducing visual issues from hard culling.

**Comment by jcostello** [comment]
What happen to this?

**Comment by Zireael07** [comment]
myaaaaaa has been closing all of their PRs for some time already - no clue why

**Pull request closed without merging**
