### PR TITLE
Optimize CSG icons and more

### PR DESCRIPTION
**Pull request by MewPurPur**
Saves ~4 kB from optimizing the CSG icons and some related stuff.

Other than the optimizations, I've changed a few icons significantly, feel free to bikeshed:

| Icon | Old | New |
| --- | --- | --- |
| CSGPolygon3D | image | image |
| CollisionPolygon3D |  image | image |
| CollisionShape3D | image | image |

### CODE REVIEW

**Review by fire — APPROVED** [review]
I don't have much opinion on the design @Calinou ?

**Review by Calinou — APPROVED** [review]
Design looks good to me.

Icons in context with other node icons:

image

**Comment by akien-mga** [comment]
Needs rebase.

**Comment by MewPurPur** [comment]
██████╗░███████╗██████╗░░█████╗░░██████╗███████╗██████╗░
██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝██╔══██╗
██████╔╝█████╗░░██████╦╝███████║╚█████╗░█████╗░░██║░░██║
██╔══██╗██╔══╝░░██╔══██╗██╔══██║░╚═══██╗██╔══╝░░██║░░██║
██║░░██║███████╗██████╦╝██║░░██║██████╔╝███████╗██████╔╝
╚═╝░░╚═╝╚══════╝╚═════╝░╚═╝░░╚═╝╚═════╝░╚══════╝╚═════╝░

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
