### PR TITLE
Fix error when switching to another `GridMap` with an item with higher index selected

### LINKED ISSUE #64126: Multiple gridmaps in same scene cause issues with mesh selection
### Godot version

3.5.rc7

### System information

Windows 10

### Issue description

If using multiple gridmaps in the same scene and switching between them, the editor will try to pick the MeshLibrary item from the previously selected gridmap's meshlibrary and choose it in the newly selected gridmap. If it doesn't have the mesh item, it will display an error:
```
scene/gui/item_list.cpp:237 - Index p_idx = 1 is out of bounds (items.size() = 1).
Requested for nonexistent MeshLibrary item '4'.
```
It will also no longer allow you to select a new mesh item from the meshlibrary until you go back to the previous gridmap and select an item number the other gridmap has.

The chosen item should be separated between each gridmap, so switching between them keeps the item chosen last independently.

### Steps to reproduce

1. Add two gridmaps to a scene
2. Have them both use separate MeshLibraries of different sizes
3. Pick an item from one gridmap meshlibrary for painting with and switch to the other gridmap
4. Godot will attempt to select the previously chosen item from the other gridmap in the newly chosen gridmap, and won't allow you to pick the correct item.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by YeldhamDev**
Fixes #64126.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.6.

**Comment by akien-mga** [comment]
Cherry-picked for 3.5.1.

**Comment by elvisish** [comment]
This is great that it's fixed the problem, but there still seems to be an issue with returning to the previously selected mesh, it seems to choose one mesh higher in the MeshLibrary when you return to the gridmap.

**Pull request merged**
