### PR TITLE
Fix "About C# Support"

### PR DESCRIPTION
**Pull request by piratesephiroth**
Second attempt at solving issue #21933

### CODE REVIEW

**Comment by aaronfranke** [comment]
This isn't a C#-specific problem, this is an issue with Godot dialogs in general. See https://github.com/godotengine/godot/issues/21975

**Comment by piratesephiroth** [comment]
#21975 is related to high resolution screens. This one isn't.

**Comment by LikeLakers2** [comment]
While I'm not a developer of Godot, and thus can't speak for the others, this just seems like a wrong solution to the issue. #21933 is describing an issue with text going off the bottom of the dialog, which sounds like an issue with how text wrapping is handled. I don't think adding newlines to the dialog is really the right course of action here, as that's just hiding a bug rather than fixing the bug.

With your comment over at https://github.com/godotengine/godot/issues/21933#issuecomment-422490629, you determined the following:

> That happens because `Control::SIZE_EXPAND_FILL` ignores `set_autowrap`.
> It's resizing the control height properly according to the original strings.

This to me says you should be working with the code that handles setting the control height, not the text itself.

**Comment by akien-mga** [comment]
Thanks but that's still a hack, not a fix. You identified the problem in #21933, and that's what should be fixed: `Control::SIZE_EXPAND_FILL` *should* take autowrap into account (as it used to).

**Pull request closed without merging**
