### PR TITLE
ColorPicker: Fix OKHSL circle in HSV mode

### LINKED ISSUE #68286: Editor ColorPicker color wheel preview incorrect in OKHSL / HSV mode
### Godot version

4.0.beta4

### System information

macOS 12.6.1

### Issue description

It seems the color picker panel color wheel previews are rendering incorrectly if you modify the color in HSV mode. Possibly it's interpreting the values as something other than HSV? It works correctly as long as you use the RGB sliders, but if you switch to HSV mode the selected color is still correct, but the preview color wheel and gradient thing are incorrect. Possibly color wheel and gradient above is rendering the values as HSL (where lightness L=1 is white) instead of the intended HSV (where V=1 is a bright color). For difference see https://en.wikipedia.org/wiki/HSL_and_HSV 

See the attached screen capture.

https://user-images.githubusercontent.com/17763524/200117422-aec4de9d-7187-4124-880d-869e4cdc5632.mov

### Steps to reproduce

- Click a color parameter in the editor (for example a material Albedo color) to bring up the color picker
- Switch to HSV sliders by clicking the HSV tab
- Change the HSV sliders and observe the color wheel/gradient above to see the indicated location doesn't match the selected color

### Minimal reproduction project

This should be a general editor issue, rather than project specific

### PR DESCRIPTION
**Pull request by beicause**
Fixes #68286.
OKHSL and HSV are different things, they should be stored separately in different fields.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

image

**Review by fire — APPROVED** [review]

**Comment by beicause** [comment]
In addition to fixing the issue, I think it should be allowed to use other color wheels in okhsl mode, not just okhsl circle. If possible I would like to update this PR, or I will open a new PR after this merges.

**Comment by fire** [comment]
Please do it in a separate pr!

**Comment by KoBeWi** [comment]
#99515 should make it easier to add new shapes.

**Comment by beicause** [comment]
Actually in my test, after this pr, we just need to remove the `get_shape_override` and `_get_actual_shape` in okhsl mode to let it work in other color wheels. IMO the shape override is unnecessary and this why I want to also do it in this pr.

Of course, Refactoring and cleaning are great and necessary.

**Comment by Repiteo** [comment]
Thanks! Congratulations on your first merged contribution! 🎉

**Pull request merged**
