### PR TITLE
[3.x] Move collision layer and mask into CollisionObject.

### PR DESCRIPTION
**Pull request by madmiraal**
3.2 version of #42770.

### CODE REVIEW

**Comment by madmiraal** [comment]
Rebased following merge of 4287af51483505deb.

**Comment by madmiraal** [comment]
Rebased following merge of 015973df04.

**Comment by madmiraal** [comment]
Updated the documentation as suggested [here](https://github.com/godotengine/godot/pull/42770#discussion_r616047560).

**Review by pouleyKetchoupp — APPROVED** [review]

**Comment by madmiraal** [comment]
Rebased following e4addffde196c8c1c16.

**Comment by akien-mga** [comment]
I wonder how this impacts compatibility for GDNative or other language bindings? Moving methods to a parent class should be transparent to GDScript but it does break the ABI, no?

**Comment by madmiraal** [comment]
> I wonder how this impacts compatibility for GDNative or other language bindings? Moving methods to a parent class should be transparent to GDScript but it does break the ABI, no?

It doesn't, because the inherited methods have the same signature as before. This PR simply removes the duplication of defining (and in this case also declaring) them in their child classes. It resolves #26680: the current duplicate declaration prevents people using a pointer to the parent class to call the methods defined in the child classes. However, everyone can continue to call the individual methods in each child class as before.

**Comment by akien-mga** [comment]
Thanks for the confirmation, sounds good to me then 👍

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
