### PR TITLE
Make OccluderPolygon2D draggable in the editor

### PR DESCRIPTION
**Pull request by YeldhamDev**

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @groud

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and *release freeze* for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

**Comment by YeldhamDev** [comment]
@groud Could you take a little look on this?

**Comment by groud** [comment]
LGTM ;)

**Comment by groud** [comment]
@YeldhamDev please don't merge PRs (especially when they are yours), in general the bugsquad should not merge PRs unless they are minor changes and they are expert in this area. ^^ (Unless Akien or reduz told you to merge it which in this case it's ok) 

But don't worry it's ok this time, Akien will likely confirm :)

**Comment by YeldhamDev** [comment]
@ground That PRs that I have merged have been very minor, I'm being very careful about those. I thought that this one was OK since its age, being added to the 3.2 milestone, and you giving the green flag.

**Pull request merged**
