### PR TITLE
Prevent to add node to selection when node is not inside tree

### LINKED ISSUE #6244: Editor hangs - caused by EditorSelection
**Operating system or device - Godot version:**
Godot 2.1 stable 64 bit, Windows 7

**Issue description** (what happened, and what was expected):
Editor hangs when you pass node to add_node (from EditorSelection) which isn't in the scene tree. It is a wrong way of using add_node but it shouldn't hang. There should be a check if selected node is inside the tree.

**Steps to reproduce:**
1. Create an editor plugin
2. Make a new node in script: `var newMeshInstance = MeshInstance.new()`
3. Try to select this node: `get_selection().add_node(newMeshInstance)`

### PR DESCRIPTION
**Pull request by volzhs**
Fix #6244

### CODE REVIEW

**Comment by neikeq** [comment]
Wouldn't it be better to print an error? e.g: `ERR_FAIL_COND(!p_node->is_inside_tree());`

**Comment by volzhs** [comment]
@neikeq indeed

**Comment by neikeq** [comment]
My fear was that the property _"advanced/disable_filter"_ could be saved somewhere. But if that's not the case, nvm.

**Comment by volzhs** [comment]
I was worried about that. So I searched it and found `advanced/disable_filter` in `.fnt` file.
But it doesn't affect re-import font.

**Comment by bojidar-bg** [comment]
@neikeq ~ Wrong issue?

**Comment by neikeq** [comment]
Yes, wrong PR. Sorry :P

**Pull request merged**
