### PR TITLE
Fix Unix temp file creations when using is_backup_save_enabled.

### LINKED ISSUE #75078: Godot creates a lot of temporary files in the project directory on Linux/macos
### Godot version

4.1.dev (a7d0e18a31)

### System information

Linux (Ubuntu 22.04), Vulkan, Radeon RX Vega 64 (eGPU)

### Issue description

A regression was introduced in https://github.com/godotengine/godot/pull/73156 (both a git bisection and the PR itself mentions it) where temp files would be created in the project directory.

image

#75074 seems to fix this issue.

### Steps to reproduce

1. Open any project in Linux since #73156
2. See that temp files are created

### Minimal reproduction project

N/A

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes https://github.com/godotengine/godot/issues/75078. (Also see comments in https://github.com/godotengine/godot/issues/74968.)

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Does this really fix the linked issue? It mentions 4.0.1.rc1 but the PR this is fixing up was merged after 4.0 and not cherrypicked.

**Comment by bruvzg** [comment]
> Does this really fix the linked issue?

It's hard to say what was the crash reason of the issue (it might be massive descriptor leak, or something else), but comments are mostly related to the temp files.

**Comment by bruvzg** [comment]
For the reference, it is fixing the regression from #73156, `mkstemp` writes temp file path to its argument and opens the file, returning file descriptor.
So `if (!mkstemp(path.utf8().ptrw()))` was:
- writing path to the temporary UTF-8 string, which is not saved.
- leaking open file descriptor.

Now it's using the returned descriptor and converting file path back to `String`. `fdopen` do not duplicate the descriptor, so there's no need to close it if it was successful, but it should be closed and deleted if it fails.

**Comment by adamscott** [comment]
@yudi-azvd said in #74968:

> @YuriSizov I think you are correct. First I've built the master branch by mistake. I noticed it then built the 4.0 and it's the one I'm using now. Since then these extra files did not appeared.

So I don't think it fixes #74968.

**Comment by YuriSizov** [comment]
Indeed it doesn't fix the original problem from the linked issue, just a side-comment that uncovered a problem with a recent PR in `master`.

**Comment by adamscott** [comment]
@bruvzg I created the issue #75078 so you can tag your PR with it.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
