### PR TITLE
iPhone platform fixes {resubmit}

### PR DESCRIPTION
**Pull request by kurikaesu**
Hi all, here's the new pull request that doesn't have unecessary commits in it. I've spent time messing with the rebase functionality in order to get it right.

There is a fix in this pull request to get Godot compiling under Msys2 as it was complaining about having too long of an argument list during linkage.

### CODE REVIEW

**Comment by punto-** [comment]
Can we use #ifdefs to detect the SDK version and add or remove those extern
"C" that are causing trouble? We use SDK 8.something on the build server, I
think those are too old for this code. I don't mind supporting the latest
SDKs, but also I'd like to not have to update the build server for a while.

**Comment by kurikaesu** [comment]
This should do the trick.

**Comment by punto-** [comment]
Can you put tabs on SCsub instead of spaces? :)

**Comment by kurikaesu** [comment]
Details details details! ;)

**Comment by punto-** [comment]
looks good.. what's the theora stuff for?

**Comment by kurikaesu** [comment]
It's a little speedup (5-10%) when playing theora videos. Definitely more noticeable on less powerful hardware like the ipad mini I'm testing on.

Considering that unless I port/write the arm/neon optimised code it doesn't increase the play-back speed enough to be useful, I'm not going to be working on that part of the code any more.

**Comment by punto-** [comment]
ok, looks good, thanks!

**Pull request merged**
