### PR TITLE
Fix PopupMenu's letter jumping on any InputEventKey (instead of just a press)

### LINKED ISSUE #37355: OptionButton/PopupMenu's letter jumping jumps multiple times when pressing a key
**Godot version:**
3.2.1 stable

**OS/device including version:**
Fedora 31

**Issue description:**
When using an OptionButton or PopupMenu and trying to jump to an item in the list by pressing a key every single input event gets registered. For example by pressing a key for the first time you will jump to the second item (to the first upon the press and to the second on the release; holding the key cycles through everything). ItemList and Tree work normally.

**Steps to reproduce:**
Create an OptionButton/PopupMenu. Add multiple items that start the same and press a key to jump to one of those items.

**Minimal reproduction project:**
[OptionButtonPopupMenu.zip](https://github.com/godotengine/godot/files/4393875/OptionButtonPopupMenu.zip)

### PR DESCRIPTION
**Pull request by Leleat**
fixed #37355

### CODE REVIEW

**Comment by Leleat** [comment]
I just found #36734, which includes a fix to my opened issue (and some more stuff). 

I only searched through the open issues and not PRs/proposals. Should I close/delete this PR? Sorry, still new to all of this.

**Comment by akien-mga** [comment]
No I think this PR can be kept, it's easy to review and merge/cherry-pick to fix a well-defined issue.
#36734 has a bigger scope and might be more controversial (for example change the default value of a member variable depending on whether it's running in the editor or not is a bit hacky).

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.2.2.

**Pull request merged**
