### PR TITLE
Fix RenderingServerDefault usage of `has_os_feature`

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Fixes Reduz's PR https://github.com/godotengine/godot/pull/61436
Prevents crash that we were having here

(originally created this PR on reduz's fork but it gets lost there :))

### CODE REVIEW

**Comment by akien-mga** [comment]
Looks good to me. I would suggest squashing the commits, so that there's no intermediate broken state that we might land upon when bisecting. You can add yourself as co-author to Juan's amended commit with `Co-authored-by: name <email>` in the commit log.

**Review by akien-mga — APPROVED** [review]

**Comment by clayjohn** [comment]
Where is ``has_os_feature`` getting called so early? 

I am concerned that this might result in certain areas caching incorrect values if they check for features too early.

**Comment by akien-mga** [comment]
Stacktrace for the crash in #61436 as reference:
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000058ef501 in has_server_feature_callback (p_feature=...) at servers/register_server_types.cpp:102
#2  0x00000000061eb9e4 in OS::has_feature (this=0x7fffffffd140, p_feature=...) at core/os/os.cpp:466
#3  0x0000000006719bf8 in ProjectSettings::_set (this=0x9e12730, p_name=..., p_value=...) at core/config/project_settings.cpp:269
#4  0x0000000006726b16 in ProjectSettings::_setv (this=0x9e12730, p_name=..., p_property=...) at core/config/project_settings.h:40
#5  0x00000000066a0127 in Object::set (this=0x9e12730, p_name=..., p_value=..., r_valid=0x0) at core/object/object.cpp:451
#6  0x00000000067216bf in _GLOBAL_DEF (p_var=..., p_default=..., p_restart_if_changed=false, p_ignore_value_in_docs=false, p_basic=false) at core/config/project_settings.cpp:1000
#7  0x0000000005988b7b in RenderingServer::RenderingServer (this=0xaa7ce50) at servers/rendering_server.cpp:2838
#8  0x0000000005c80254 in RenderingServerDefault::RenderingServerDefault (this=0xaa7ce50, p_create_thread=false) at servers/rendering/rendering_server_default.cpp:386
#9  0x00000000022a97bf in Main::setup2 (p_main_tid_override=0) at main/main.cpp:1701
#10 0x00000000022a732f in Main::setup (execpath=0x7fffffffdb0e "/home/akien/.local/bin/godot-git", argc=1, argv=0x7fffffffd680, p_second_phase=true) at main/main.cpp:1528
#11 0x0000000002263ee5 in main (argc=2, argv=0x7fffffffd678) at platform/linuxbsd/godot_linuxbsd.cpp:61
```

**Comment by clayjohn** [comment]
It looks like the core of the issue comes from the fact that ``OS::has_feature`` is both used for detecting features (texture support, OS name, etc.) and things like actions defined in the project settings. 

What ends up happening is ``has_os_feature()`` is called dozens of times when the editor is being set up. 

On close inspection neither @akien-mga or I could find any place where ``has_os_feature`` may be called and the early return would cause an issue. My concern was that we may be checking for the presence of a feature in order to set a setting that will impact things later on, but it seems that it isn't a reaistic concern.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
