### PR TITLE
AudioServer: Fix code style issues

### PR DESCRIPTION
**Pull request by RandomShaper**
- Drop STL copy in favor of old-school for loops.
- Be explicit about loads and stores to atomic value. (This also fixes an error in certain compiler toolchains.)

### CODE REVIEW

**Review by AThousandShips — APPROVED** [review]
LGTM!

**Comment by akien-mga** [comment]
Thanks!

**Comment by RandomShaper** [comment]
Now I've realized, I'm labeling it as cherry-pickable into 4.3, for the sake of keeping both codebases convergent for easier potential future cherry-picks.

**Comment by akien-mga** [comment]
Cherry-picked for 4.3.1.

**Pull request merged**
