### PR TITLE
Fix shader tokenizer/compiler reporting wrong error location (2.2)

### PR DESCRIPTION
**Pull request by RandomShaper**
Raname shader tokenizer methods for clarity

### CODE REVIEW

**Comment by RandomShaper** [comment]
By the way, the _2.2_ supersedes the _2.1_ one and is where the 2.x work should go on, isn't it?

**Comment by akien-mga** [comment]
> By the way, 2.2 supersedes the 2.1 one and is where the 2.x work should go on, isn't it?

Not really. 2.2 is a snapshot of the master branch just before we merged the gles3 work into it, and since we have no plans to release 2.2-stable, it's just there for the convenience of people who want to use unreleased features like high level multiplayer API without putting up with the current breaking in 3.0-alpha.

So the 2.2 branch is not really meant to be worked on. Changes should be made either on master or on 2.1, or both.

**Comment by RandomShaper** [comment]
Thanks for the explanation.

**Comment by akien-mga** [comment]
I'll still merge as it doesn't hurt per se, even if we don't plan to maintain the branch ;)

**Pull request merged**
