### PR TITLE
Clarify VisibilityEnabler2D description

### LINKED ISSUE #2211: Clarify VisibilityEnabler (2D)
https://docs.godotengine.org/en/latest/classes/class_visibilityenabler2d.html

> It will only affect other nodes within the same scene as the VisibilityEnabler2D itself.

What is considered to be "in the same scene"? My guess would be: Any node with the same Owner?

### PR DESCRIPTION
**Pull request by skyace65**
Fixes [this docs issue](https://github.com/godotengine/godot-docs/issues/2211). Makes the node description more specific.

### CODE REVIEW

**Comment by bojidar-bg** [comment]
I think "parent" is more proper than "root" here.

**Comment by skyace65** [comment]
> 
> 
> I think "parent" is more proper than "root" here.

Wouldn't that be inaccurate? The root node of the scene isn't every nodes parent

**Comment by bojidar-bg** [comment]
Ah wait, my bad -- misread the code :smiley:

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
