### PR TITLE
Fix Tweeners to emit `finished()` when underlying object is deleted

### LINKED ISSUE #10575: Implement a new `invalidated` signal for tweens
### Describe the project you are working on

A Balatro-like

### Describe the problem or limitation you are having in your project

I've got a global animation queue system that queues tweens and triggers the next one when the `finished` signal is emitted for the last played tween. If a node the current tween is targeting gets `queue_free()`ed then the tween gets into a state where `is_valid()` returns `false` and `is_running()` returns `true`. The `finished` signal is never emitted (and that is supposedly *by design*, ie. not subject to change.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Adding a new signal `invalidated` that is emitted if the tween changes from being valid to invalid would allow us to handle these edge cases without breaking backwards compatibility, and should be a fairly straightforward change to make(?)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

n/a, the feature ask is self-explanatory

### If this enhancement will not be used often, can it be worked around with a few lines of script?

Yes, the workaround I've had to resort to is to add a check against the currently running tween within a `func _process(delta)` defined on my animation queue singleton. It's... *fine* but I really shouldn't have to check that every frame, reacting to a signal would be much cleaner.

### Is there a reason why this should be core and not an add-on in the asset library?

It's a change to a core class, `Tween`

### PR DESCRIPTION
**Pull request by BlackShift**
Fixes https://github.com/godotengine/godot-proposals/issues/10575

### CODE REVIEW

**Comment by Alzurana** [comment]
Hey there, you were a bit faster than me. MethodTweener and CallbackTweener have the same problem. I linked it in the issue.

**Comment by Mickeon** [comment]
If this is the way to go it absolutely needs to be documented in `finished`'s description. By the original definition, the Tween is not finished, it is interrupted.

**Comment by Alzurana** [comment]
Hello there  @Mickeon 
I just went through the documentation, interestingly MethodTweener and CallbackTweener already feature this in their documentation. So for these two this PR actually brings the code closer to the documentation.
"The tweener will finish automatically if the callback's target object is freed."

PropertyTweener is missing this line in their documentation, it should probably be added with this PR.

@BlackShift I'm sure this is the last piece of the puzzle, the documentation change would go here:
https://github.com/godotengine/godot/blob/108c603f91b94100a1adc989316a372f0a6f8989/doc/classes/PropertyTweener.xml#L8

Here is an example of how the other classes already do it:
https://github.com/godotengine/godot/blob/108c603f91b94100a1adc989316a372f0a6f8989/doc/classes/CallbackTweener.xml#L8

**Comment by KoBeWi** [comment]
The description of Tweener's finished should be adjusted:
https://github.com/godotengine/godot/blob/fd7239cfab228c50777cd54a8bf6eb279a02ef81/doc/classes/Tweener.xml#L14
I'd add "It can happen either when the tweening has completed or when it was interrupted (e.g. by target object becoming invalid)."

I checked the new behavior and the only case when it can cause undesired effects is when you relied on Tweener not finishing after target is freed (which resulted in hanging await until the awaiting object is also freed). It's not really a reasonable use-case though.
Personally I only use that signal for one-liner animations on self, which would work either way. I think the fix is fine.

**Review by KoBeWi — APPROVED** [review]

**Comment by BlackShift** [comment]
@KoBeWi 
for the doc change would this work?

`Emitted when the [Tweener] has just finished its job or becomes invalid due to a freed object.`

**Comment by KoBeWi** [comment]
I would make mention of freed objects less prominent, because Tweener can become invalid for other reasons (e.g. CallbackTweener is invalid when method does not exist).

`Emitted when the [Tweener] has just finished its job or became invalid (e.g. due to a freed object).`

**Review by Mickeon — APPROVED** [review]
This is good enough by me documentation-wise

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Pull request merged**
