### PR TITLE
Change display scale when moving the window from monitor to monitor [macOS]

### LINKED ISSUE #5688: MacOS: Moving Godot Editor Window from Retina Display to non Retina display does not resize the content appropriately
**Operating system or device - Godot version:**
2.1 beta 20160712 osx

_**Not reproducible with 2.0 stable version**_ 

**Issue description** (what happened, and what was expected):
When moving the window from a 'zoomed' monitor (Retina Display) to a non zoomed (Full HD) monitor the window content is too big

Retina before:
image

After moving to Non Retina Monitor:
image

**Steps to reproduce:**
(Using a MacBook Pro MBP)
- 1 External DVI monitor via Lightning Cable attached to MBP
- Start Godot on the Retina screen (Builtin screen) and open a project
- Move the window over to non retina screen

### PR DESCRIPTION
**Pull request by bruvzg**
Fixes #5688.

Tested with two 1440p external displays (first in scaled 720p HiDPI mode, second in 1440p mode).

Also I am unsure why window resize is necessary (lines 188-190), but it does not work without it (display red background until resized manually).

Update: Resizing to non zero size is better, `windowDidChangeBackingProperties` triggers only once (was triggering on both resizes before).

### CODE REVIEW

**Comment by akien-mga** [comment]
cc @BastiaanOlij @marcelofg55 for review from macOS devs :)

**Comment by bruvzg** [comment]
Additional note: To test this on non-retina displays you can enable HiDPI modes with this command:
`sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayResolutionEnabled -bool true`

**Comment by marcelofg55** [comment]
I've just tested it with two monitors (two lo-res using one with the HiDPI option) and the window updates correctly when moving from one screen to the other.

**Comment by BastiaanOlij** [comment]
Finally had a chance to test this as well, indeed moving it from one screen to the other works well but it doesn't adjust for dpi on the second screen so everything becomes large :) Better then it completely not working.

I did get once or twice the screen going all one colour, moving it to the other screen and back fixes that. I'm guessing that is related to the same resize issue you mentioned @bruvzg.

Anyway just thought I'd add that bit of late info.

**Pull request merged**
