### PR TITLE
Removed Redundant initialization of probe_half_size

### LINKED ISSUE #50903: Redundant initialization of `probe_half_size`
### Godot version

4.0 088722beaaba8d219dcb2e61ae6b8df9a9af5283

### System information

-

### Issue description

https://github.com/godotengine/godot/blob/088722beaaba8d219dcb2e61ae6b8df9a9af5283/servers/rendering/renderer_rd/renderer_scene_gi_rd.cpp#L796-L797

### Steps to reproduce

-

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by vitika9**
Fixes #50903

### CODE REVIEW

**Comment by raulsntos** [comment]
If this variable is initialized to `Vector3(0, 0, 0)` and then only used later in line 800, then it seems unnecessary for this variable to exist.

https://github.com/godotengine/godot/blob/088722beaaba8d219dcb2e61ae6b8df9a9af5283/servers/rendering/renderer_rd/renderer_scene_gi_rd.cpp#L801

Since `world_position + Vector3(0, 0, 0)` is the same as just `world_position`.

**Comment by Vitika9** [comment]
> If this variable is initialized to `Vector3(0, 0, 0)` and then only used later in line 800, then it seems unnecessary for this variable to exist.
> 
> https://github.com/godotengine/godot/blob/088722beaaba8d219dcb2e61ae6b8df9a9af5283/servers/rendering/renderer_rd/renderer_scene_gi_rd.cpp#L801
> 
> Since `world_position + Vector3(0, 0, 0)` is the same as just `world_position`

should it be initilized to Vector3(1, 1, 1) * cascade.cell_size * float(cascade_size / SDFGI::PROBE_DIVISOR) * 0.5
or + probe_half_size should be removed from line 800?

**Comment by raulsntos** [comment]
Not sure, I'd wait for a review from someone from the rendering team.

**Comment by akien-mga** [comment]
As discussed above, this is only hiding the problem which is that `probe_half_size` is never used. I'll close this PR and keep the issue as a reminder for the rendering team to look into this.

**Pull request closed without merging**
