### PR TITLE
OptionButton: allow reselection of currently selected item

### PR DESCRIPTION
**Pull request by okla**
Implementation of https://github.com/godotengine/godot-proposals/issues/4539

### CODE REVIEW

**Comment by kleonc** [comment]
I think current implementation might not be the best solution as reemitting/reselecting might be undesirable for some users (and in that sense it kinda breaks compatibility). Probably a better solution would be to introduce a flag like the one in the `Tree` class: [`allow_reselection`](https://docs.godotengine.org/en/3.4/classes/class_tree.html#class-tree-property-allow-reselect). This way it could be `false` by default so nothing would break (so it could be added in `3.x` too) and you could just check it for your needs.

**Comment by okla** [comment]
@kleonc I think you are right, will try to add a flag. How do such changes backport to 3.x? By cherry-picking from master or by separate proposal/PR?

**Comment by kleonc** [comment]
> How do such changes backport to 3.x? By cherry-picking from master or by separate proposal/PR?

If the changes in `3.x` will be the same then it can be just cherry-picked from the `master`-version PR. If there are differences then a seperate PR against `3.x` would be needed. But no additional proposal is needed.

**Comment by Calinou** [comment]
> I think current implementation might be not the best solution as reemitting/reselecting might be undesirable for some users (and in that sense it kinda breaks compatibility).

For `master`, I think this new behavior would make sense by default. If users need to opt-out, they can check whether the new value is equal to the old value in the signal's receiver method.

**Comment by okla** [comment]
Looks like I've messed up the git branch

**Pull request closed without merging**
