### PR TITLE
README.md with Godot 3.1 interface screenshot

### PR DESCRIPTION
**Pull request by Toshiwoz**
An up-to date image, with the good looking TPS demo is probably now a good choice.

### CODE REVIEW

**Comment by groud** [comment]
I think the orange bar should be removed, it takes too much attention.

**Comment by groud** [comment]
Also, I think the image should be hosted elsewhere, as I am not sure github usercontents may least if the associated comment gets deleted.

**Comment by Toshiwoz** [comment]
> 
> 
> Also, I think the image should be hosted elsewhere, as I am not sure github usercontents may least if the associated comment gets deleted.

I totally agree, should that be on tuxfamiliy.org, or even in the code repository, so that in the future would be even easier to update eventual screenshots.

**Comment by groud** [comment]
Also, to bit a little bit picky, I think it would be better to use the default theme for the screenshot. Otherwise it might disturb people.

And finally, you will have to rebase your branch and merge your commits together. See the [PR woprkflow documentation](https://docs.godotengine.org/en/3.0/community/contributing/pr_workflow.html)

**Comment by Toshiwoz** [comment]
Oh, I forgot my theming thing..
image
Is this the default theme? (apart from the top bar accent that is my windows config)

**Comment by groud** [comment]
Yes it is :) The central picture likely needs to be a little less cluttered, like the first you proposed, but else it's good (if you remove the top bar :) )

**Comment by Toshiwoz** [comment]
Ok, still,
I believe that even for future updates, would be much easier to keep all the screenshots in the repository, in a specific folder.
But I'm guessing that also some build scripts will need to be updated in order to ignore the new folder.

**Comment by Toshiwoz** [comment]
Godot-3 1_editor
I finally solved the multiple commits, dang, I can't really use git.. thanks tortoise.

**Comment by Calinou** [comment]
@Toshiwoz See the screenshot I posted at https://github.com/godotengine/godot/issues/27324#issuecomment-475693107. I'd give it a try as it looks less cluttered.

**Comment by reduz** [comment]
Looks nice to me

**Comment by akien-mga** [comment]
Superseded by e40aea7f, but thanks for the proposal!

**Pull request closed without merging**
