### PR TITLE
Respect visibility change by Scene dock when using Sync Scene Changes

### LINKED ISSUE #18757: Sync Scene Changes does not work with visibility change on Scene dock
**Godot version:**

3.1.dev fe82b5a12

**OS/device including version:**

Kubuntu 18.04

**Issue description:**

Debug > Sync Scene Changes option does not work with 3.1.dev
3.0.3-rc1 works fine.

**Steps to reproduce:**
1. Check ON Debug > Sync Scene Changes
2. Run
3. Change visibility any node on Scene dock

**Minimal reproduction project:**

### PR DESCRIPTION
**Pull request by volzhs**
Fix #18757 with keeping a feature introduced at 8343c9fbd

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by volzhs** [comment]
to make sure, 3.0.3-rc2 does not have this problem.

**Comment by volzhs** [comment]
@akien-mga current 2.1 HEAD has this issue. need to cherrypick this PR on 2.1 branch.

**Comment by akien-mga** [comment]
It would be best if you can do a PR for 2.1, the code is a bit different so it needs to be cherry-picked manually and tested to make sure it works as expected.

**Comment by volzhs** [comment]
@akien-mga I will make one this weekend then.

**Pull request merged**
