### PR TITLE
Fixed texture animation speed when using random lifetime 

### LINKED ISSUE #54993: Particles2D - texture animation speed problem with random lifetime
### Godot version

3.4 stable

### System information

Windows 10 (GLES3)

### Issue description

When setting up a Particle2D or CPUParticle2D node with a animated texture (frames setup via a CanvasItemMaterial), the animation won't be fully played when using a random lifetime in the particle system.

The animation will always be played a speed depending on the full lifetime and will be cut off if the particle dies earlier (due to random lifetime)

It can be fixed in the Particle2D node by converting to a shader and changing `CUSTOM.y` to `tv` at the anim_speed line.

https://user-images.githubusercontent.com/9423774/141766384-797a590e-8ff0-482a-9885-dd455e5296f0.mp4

### Steps to reproduce

- Add a Particle2D or CPUParticle2D node
- Add a texture (using a spritesheet)
- Setup the CanvasItemMaterial to be a animated particle texture
- Add a random lifetime to the Particle node

### Minimal reproduction project

[3.4_particle_texture_animation_speed.zip](https://github.com/godotengine/godot/files/7537900/3.4_particle_texture_animation_speed.zip)

### PR DESCRIPTION
**Pull request by RPicster**
This fix includes changes for cpu and gpu Particle2D nodes.
 
 It's my first PR, sorry if I did anything wrong - I did my best 🙈
 
Fixes https://github.com/godotengine/godot/issues/54993
(was also reproducable on master)

A cherrypick would be fantastic, I have the changes ready for a PR - just let me know if I should open it.

### CODE REVIEW

**Comment by akien-mga** [comment]
It would be good to fix it in 3D too for consistency. 2D and 3D particles shared much of the same logic (and `ParticlesMaterial` is actually shared by both for 3D GPU particles, so it should already be fixed for GPUParticles3D, but now inconsistent in CPUParticles3D).

**Comment by RPicster** [comment]
> It would be good to fix it in 3D too for consistency. 2D and 3D particles shared much of the same logic (and `ParticlesMaterial` is actually shared by both for 3D GPU particles, so it should already be fixed for GPUParticles3D, but now inconsistent in CPUParticles3D).

I'll take care about that!

**Comment by RPicster** [comment]
So, I also looked into the 3D Particles:
For 3D GPU Particles it was working with the first commit as you said.
For 3D CPU Particles I fixed that but also found another problem that stopped the parameters from working completely:

The default values for many variables were 0 instead of 1, so the min/max values weren't working until a curve texture was present.

I fixed these problems too, the parameters do now also work without a curve texture.

**Comment by RPicster** [comment]
I closed this PR as it was done from my master branch, here is the new PR from a branch:
https://github.com/godotengine/godot/pull/55271

**Pull request closed without merging**
