### PR TITLE
Improved "Quick Open" dialog navigation

### LINKED ISSUE #3362: Arrow keys and enter don't work anymore in "Quick open" dialog
@TheHX @neikeq @MarianoGnu

### PR DESCRIPTION
**Pull request by ghost**
I changed the dialog Tree navigation for when the search box is focused, now it will behave like in Godot 1.1, when the multiple selection is enabled and navigating with up, down, page-up and page-down.

Closes #3362.

### CODE REVIEW

**Comment by akien-mga** [comment]
It works great :)

I did however get a crash, but I think it's related to @reduz's changes and not this PR specifically.
But if you can have a look to confirm before I merge, that would be great.

To reproduce the crash:
- start typing some letters in the search box, so that it does not match any item in the tree (the tree is then empty)
- try to move up or down with the arroy keys -> segfault

**Comment by akien-mga** [comment]
Actually I can't reproduce the segfault without this PR as the arrow keys are not working as per #3362 ;)

**Comment by TheHX** [comment]
@akien-mga sorry my fault i forgot to commit one thing.

**Comment by akien-mga** [comment]
It works great, thanks! :D

**Pull request merged**
