### PR TITLE
Add AnimatedSprite2D and 3D `is_playing_backwards()`

### LINKED ISSUE #4506: Expose AnimatedSprite's `is_playing_backwards()`
### Describe the project you are working on

Your typical 2D Godot project with extensive use of **AnimatedSprite**.

### Describe the problem or limitation you are having in your project

In my project, I have a **AnimatedSprite** that plays a charge animation forward so long as the button is held. When released, it plays **backwards** from where it left off, then switches back to the idle animation.

However, I was stumped to realise that there's no way to check if an animation is **playing backwards** at any given time. This is odd, given the fact that there's no way the Engine wouldn't know. It's got to be there in the code _somewhere_, just not exposed.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Expose **AnimatedSprite** and **AnimatedSprite3D**'s `is_playing_backwards()`, or something similarly named, but for consistency it should at least contain "_backwards_".

Its functionality is really self-explanatory. 

Given the fact that it's a **method**, implementing it would also not pollute the **Inspector** with a confusing property name _(`playing` VS. `playing_backwards`? Puzzling. If it were just `backwards` it'd be too ambiguous...)_

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

```GDScript
var sprite : AnimatedSprite = $AnimatedSprite

sprite.play("default", false)
print(sprite.is_playing_backwards() ) # prints "false"

sprite.play("default", true)
print(sprite.is_playing_backwards() ) # prints "true"
```

### If this enhancement will not be used often, can it be worked around with a few lines of script?

With a custom script extending from AnimatedSprite, you may overwrite the `play()` method:

```GDScript
extends AnimatedSprite

var playing_backwards := false

func play(anim: String = "", backwards: bool = false) -> void:
    .play(anim, backwards)
    
    playing_backwards = backwards
```

Isn't this a bit odd, though? Once again, **AnimatedSprite** _already_ has this information, otherwise it wouldn't even play right! It's like noting down the same property twice.

### Is there a reason why this should be core and not an add-on in the asset library?

**AnimatedSprite** and **AnimatedSprite3D** are core.

### LINKED ISSUE #5286: Expose AnimatedSprite's 'play_backwards()' method as an inspector property
### Describe the project you are working on

(using Godot 3.5 stable)

I am creating a 2D game with a ton of decorative animations all over the environments that shouldn't require scripting because the majority of these animations are purely aesthetic.

### Describe the problem or limitation you are having in your project

As a non-scripter, I am unable to easily reverse the playback of an AnimatedSprite's animation.
As a result I have to use less convenient methods to achieve my goal.
___

Godot has been mostly great for the project's needs so far but as I add more and more decorative animations I am taking a liking to the simple convenience of the AnimatedSprite node because it does more than enough of what many of my simple looping animations require. I like that it doesn't require an AnimationPlayer in order to animate, like the default Sprite node does - cleaner scene trees to manage, less clicks, less time.

After getting into the habit of using AnimatedSprite lately, I believe our inability to reverse AnimatedSprite node animations without using a script is an easily mendable weakness of the node.
Allowing non-scripters to reverse AnimatedSprite animations would also make the node more consistent with the AnimationPlayer, which does provide a means of reversing animation in the inspector properties.

I'm not a scripter. I handle art and implementing art into the engine. If there's an elegant way to enable users like me to create the visual effects they want, without code, it seems consistent with Godot's user friendly engine style.

**AnimatedSprite inspector properties:**
insp

_Speed Scale does not accept negative values. If it did, there would be no problem._
I believe it makes perfect sense to allow a negative Speed Scale AND also have a play_backwards boolean. It may be an edge case to toggle play_backwards with a negative speed scale in effect but it's not an unreasonable thing to do in some circumstances.

___
**USE CASE**
wateryshapeanim
Here you see me adding an animated watery shape to a pool of green liquid.
This "warbler" AnimatedSprite has a directional watery flow movement to its animation.
I want all watery animated elements to have a consistent rightward directional movement to them.
I can achieve more visual variations, using the same animation, by X-flipping and/or Y-flipping selective instances.
But, X-flipping results in the animation "going the other way". My solution for this problem is always to simply reverse the loop.
But I can't - not with an AnimatedSprite.

Yet, with only inspector properties, I _can_ reverse animations handled by an AnimationPlayer:
animplayer
Setting "Speed" to -1 works great.

I find it strange and confusing that I can't do the same with an AnimatedSprite.

___

**Existing github posts:**
play_backwards was added in 2018, but only as a method: [https://github.com/godotengine/godot/pull/18044](https://github.com/godotengine/godot/pull/18044)
play_backwards as a property, being discussed: [https://github.com/godotengine/godot/pull/41821](https://github.com/godotengine/godot/pull/41821)

AnimatedSprite node docs: [https://docs.godotengine.org/en/stable/classes/class_animatedsprite.html](https://docs.godotengine.org/en/stable/classes/class_animatedsprite.html)

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

In essence, I just want a way to reverse a AnimationSprite's playback.

It seems best to me, to try to match the AnimationPlayer node's functionality when it comes to playback features, so Godot's core animation ui is a little more consistent.

**Proposed changes:**
1)  Add the "play_backwards" boolean to the inspector properties for AnimatedSprite nodes.

2)  Allow negative values be input for an AnimatedSprite's "speed_scale" property.
(The AnimationPlayer node allows negative values and uses a slider control in the inspector.)

3)  Rename the inspector panel label for the AnimationPlayer node's "playback_speed" property from "Speed" to "Speed Scale".
This way both nodes use the same inspector property label for the same function.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

I hope I covered this well enough above. Please see above.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

I'm not a scripter so this is outside my wheelhouse, but the issue is more about user friendliness and convenience, therefore saving users time while they're working on common tasks.

### Is there a reason why this should be core and not an add-on in the asset library?

This proposal entails a minor unobtrusive change to a very commonly used node.
It's intended to potentially benefit anyone configuring animations in Godot.

### PR DESCRIPTION
**Pull request by Mickeon**
Closes https://github.com/godotengine/godot-proposals/issues/5286.
Closes https://github.com/godotengine/godot-proposals/issues/4506.
Supersedes https://github.com/godotengine/godot/pull/41821.
Alternative to https://github.com/godotengine/godot/pull/65973

Finally, it's been done. These Proposals can all rest in peace.

### CODE REVIEW

**Comment by TokageItLab** [comment]
As I mentioned in https://github.com/godotengine/godot/pull/65973#issuecomment-1250072594, I think documentation is sufficient for this.

Also, is_playing gives the impression that it is playing, which is confusing because it returns a value even when speed_scale is 0 or when play() is not being called.

This is a case of being able to work around it with a few lines, and is a proposal that is generally rejected.

**Comment by Mickeon** [comment]
It may not be a common use-case, but one has to at least note that a bunch of people were essentially requesting the same thing. Who knows, it may happen once more, which will make this PR worth considering again someday, instead of redirecting them to the alternative.

**Comment by TokageItLab** [comment]
Previously, negative `speed_scale` was not allowed in `AnimatedSprite`, which would have made it difficult. But now that negative `speed_scale` is properly implemented, we will have to monitor it for a while.

However, considering that no one has actually complained so far about `AnimationPlayer` having negative `speed_scale` and not having an `is_playing_backwards()` method, I think this is not so needed.

**Comment by akien-mga** [comment]
Superseded by #71907.

**Pull request closed without merging**
