### PR TITLE
Add Android mouse support

### PR DESCRIPTION
**Pull request by m4gr3d**
Based off PR #37158, this PR adds mouse support functionality to the Godot Android platform through a cleaner and more thorough implementation.
In the process, several input related logic was cleaned up and simplified.

[3.2 backport](https://github.com/godotengine/godot/pull/37761)

### CODE REVIEW

**Comment by m4gr3d** [comment]
@thebestnom can you confirm via testing that this PR provides all the functionality you were attempting to add in PR #37158 
If it does, we can close PR #37158 and move the review to this one.

**Comment by thebestnom** [comment]
I tested your code on the editor, it works... kinda... 
the click don't work about half of the time, and after click the mouse just stops working... (hover and click) drag doesn't work, and double click doesn't work.
I can't use my tseting device because it deosn't suport vulkan, so I can't test other buttons for now...
To be honest I think that the fastest way is to get the Ideas from this PR and merge them with my working PR... (I already ported to disaply server as I needed it for testing the editor...)

**Comment by m4gr3d** [comment]
> I tested your code on the editor, it works... kinda...
> the click don't work about half of the time, and after click the mouse just stops working... (hover and click) drag doesn't work, and double click doesn't work.
> I can't use my tseting device because it deosn't suport vulkan, so I can't test other buttons for now...
> To be honest I think that the fastest way is to get the Ideas from this PR and merge them with my working PR... (I already ported to disaply server as I needed it for testing the editor...)

@thebestnom I've added a [3.2 backport](https://github.com/godotengine/godot/pull/37761) so it may be easier to use that and test against a 3.2 version of your test since the 3.2 branch is more stable.
Can you also provide what you're using for testing so I can try to replicate the issue you're seeing.

**Comment by thebestnom** [comment]
Im using the first commit of the android editor rebased onto this branch, testing 3.2 is harder for me because the editor 3.2 branch is still a mess

**Comment by thebestnom** [comment]
The android editor branch have the mouse implemention, you can test that against your implemention

**Comment by thebestnom** [comment]
I pushed the test branch if you havn't tried yet `mouse_testing`

**Comment by thebestnom** [comment]
created another smaller test https://github.com/thebestnom/Android-Tester

**Comment by thebestnom** [comment]
[Heres how your implementaion looks](https://youtu.be/3ZU-R0vqR3M)
[Here how it should beahave](https://youtu.be/B8TBKy_N5qo)
As I mentioned above I can only test left click and scroll, on PC you could see in the button mask all the buttons clicked

**Comment by m4gr3d** [comment]
Replaced by PR #37158

**Pull request closed without merging**
