### PR TITLE
Add tint property to TextureProgress

### PR DESCRIPTION
**Pull request by nikibobi**
I added a color tint property to TextureProgress, because it wasn't easy to only change the color of the progress texture. I know modulate exists, but it changes all 3 texture colors. This way it will be easier to reuse the same bar for health/mana/etc.

Example:
image

### CODE REVIEW

**Comment by volzhs** [comment]
nice feature

**Comment by toger5** [comment]
Tint does not make it obvious that only the process part gets tinted.
maybe rename it to:
`Tint_Progress`

this also is amazing for fading to a different color if the bar gets low!!!

**Comment by nikibobi** [comment]
Given what @toger5  suggested I decided to go further and add tint for under and over textures and move them to a Tint group.

image

**Comment by volzhs** [comment]
got much better :+1:

**Pull request merged**
