### PR TITLE
Don't translate ColorPicker color labels

### PR DESCRIPTION
**Pull request by KoBeWi**
Prevents this

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Review by YeldhamDev — APPROVED** [review]

**Review by timothyqiu — APPROVED** [review]

**Comment by timothyqiu** [comment]
An alternate solution is to use context for these labels, something like `ETR("B", "Color Channel")`.

**Comment by akien-mga** [comment]
Btw, we should likely add translation context to the other `ETR("B")` regardless of this change. (And the other kB, MB, etc. for consistency.)

**Comment by timothyqiu** [comment]
> Is translating "RGB" even a thing? I never seen a software that does it.

I've never seen that either. Maybe some languages do that. Just checked GIMP does i18n for R, G, and B for its colorpicker.

https://github.com/GNOME/gimp/blob/97d6aa59044c44d0bdf934e7174d6c61abdbfd6d/libgimpwidgets/gimpwidgetsenums.c#L130-L140

**Comment by AThousandShips** [comment]
At least the Wikipedia page has the acronym translated and not just transcribed in some languages, so I think there's room for it

**Comment by dalexeev** [comment]
I can imagine КЗС (красный, зелёный, синий) in Russian localization, but I think that most often RGB is not translated. On the other hand, providing context will allow translators of each locale to decide whether to translate it or not.

**Comment by KoBeWi** [comment]
How to add localization for labels if they are constant strings stored in a raw array? It would require some rewrite of color modes.

**Comment by timothyqiu** [comment]
> How to add localization for labels if they are constant strings stored in a raw array? It would require some rewrite of color modes.

That could be a separate PR.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
