### PR TITLE
Fix android build script

### PR DESCRIPTION
**Pull request by masoudbh3**
some fixes for android build script.
remove "armv6","x86" options and add "android_arch" option for select compiler architecture (armv7,armv6,x86)(default armv7).
add architecture suffix for output files and you can compile for several architecture simultaneously.
example:
libgodot.android.opt.debug.armv7.so
libgodot.android.opt.debug.armv7.neon.so
libgodot.android.opt.debug.armv6.so
libgodot.android.opt.debug.x86.so
now we can enable/disable neon on armv7 with "android_neon" option (default enable).
add "NDK_TARGET_X86" option for select toolchain to use for the NDK x86 (default x86-4.8).
change inputs model for "ndk_platform" option (default android-15).
fix armv7 ccflags.
with this patch, must put libgodot_android.so file in specific architecture folder:
armv7 (default): [android-java]/libs/armeabi-v7a/
armv6: [android-java]/libs/armeabi/
x86: [android-java]/libs/x86/

libgodot_android.so before:
before
libgodot_android.so after:
after

after apply this patch, i run "Isometric 2D + Lighting" on my galaxy note 3 and the result is very faster from before.

### CODE REVIEW

**Comment by volzhs** [comment]
:+1:

**Comment by punto-** [comment]
Do we know how to pack the .so with and without neon on the same apk? I
think that was the issue a while ago..

**Comment by masoudbh3** [comment]
we can't pack armv7 neon and vpfv3 .so file on the same apk.
we need create several game apk or like 'mx player' create several library apk.

**Comment by punto-** [comment]
So you can't target phones that have neon and not neon with the same apk
like you can target phones that have armv6 and armv7 with the same apk? or
arm and x86? isn't there a lib/<architecture>/ directory where we can put
the different versions?

**Comment by masoudbh3** [comment]
there isn't libs/\<with-neon\>/ and libs/\<without-neon\>/ directories but we can put two .so file in armeabi-v7a directory that first .so name is libgodot_android.so and second .so name is libgodot_android_neon.so and finally use below code for load library in android java : 

```java
boolean neon = false;
String neon_lib=getApplicationInfo().nativeLibraryDir
                          +"/"+System.mapLibraryName("godot_android_neon");
if ( Build.CPU_ABI.equalsIgnoreCase("armeabi-v7a") && 
    (new File(neon_lib).canRead()) && (new File("/proc/cpuinfo").canRead()) ) {
    try {
        BufferedReader br = new BufferedReader(new FileReader(new File("/proc/cpuinfo")));
        String line;
        while ((line = br.readLine()) != null) {
            if(line.contains("neon")) neon = true;
        }
        if (br != null)  br.close();
    } catch (IOException e) { e.printStackTrace(); }
}
if(neon) System.loadLibrary("godot_android_neon");
else System.loadLibrary("godot_android");
```

**Comment by volzhs** [comment]
Sounds good.
But I like apk is small.
so, I prefer to have a way to select which cpu arch supporting. (include neon or not)

**Comment by masoudbh3** [comment]
yes, I agree with you. smaller apk is better. and that code only one idea.
with this patch you can enable/disable neon and you can select architectures between (armv6,armv7,x86) and you can compile all simultaneously.

**Comment by volzhs** [comment]
@masoudbh3 I really love this commit. Thank you. :)

**Comment by reduz** [comment]
will have to fix the buildscript for templates but oh well :)

**Pull request merged**
