### PR TITLE
small optimization in multiplayer_synchronizer.cpp

### PR DESCRIPTION
**Pull request by virophagesp**
i changed it to instead of dividing by 1000 then by 1000 again, it will divide by the result of 1000 times 1000

### CODE REVIEW

**Review by aaronfranke — APPROVED** [review]
This PR is a good improvement. Edit: Godbolt proof, different even with -O3 https://godbolt.org/z/x78qvcTqe

**Comment by mrjustaguy** [comment]
why not just divide by 1000 000.0?

**Comment by RedworkDE** [comment]
Just like your previous 2 attempts at such optimization PRs, this change does just about nothing.

Even if this PR does get merged, please do not take that as encouragement to post more such "optimization" PRs and instead focus on bugfixes and actual improvements if you want to contribute to Godot.

**Comment by akien-mga** [comment]
I agree with RedworkDE, the only thing this optimizes is when the engine is compiled without optimization (and even then it's a micro-optimization that has no impact on anything).

With `-O1` or higher, both variants compile to the exact same assembly:
https://godbolt.org/z/MYabhjYGj

So I'll reiterate my comment from https://github.com/godotengine/godot/pull/78424#issuecomment-1596653212

If you want to actually help improve the engine, please coordinate with us to work on something that will indeed make things better.

**Pull request closed without merging**
