### PR TITLE
Flip 2D icon to match Godot's handedness

### LINKED ISSUE #1818: Flip 2D icon to match Godot's 2D handedness
**Describe the project you are working on:** 2D projects.

**Describe the problem or limitation you are having in your project:**

old

In the 2D icon, the Y axis arrow points upwards. This is fine-ish, but Godot's 2D coordinate system has Y pointing down. The icon as it currently is can be a bit misleading if people don't know that Y is down in 2D, so users could be confused and think that Y is up like they teach in schools. I think it's important to convey to the user that Y is down in 2D.

**Describe the feature / enhancement and how it helps to overcome the problem or limitation:**

The proposal is to flip the icon so that the Y axis arrow points down:

new

This may look a bit weird, but it makes more sense in context:

There are already other icons shaped in this way, such as all the curve icons and GraphEdit:

Screenshot from 2020-11-12 01-03-53

**Describe how your proposal will work, with code, pseudocode, mockups, and/or diagrams:**

This SVG image: https://raw.githubusercontent.com/aaronfranke/godot/2d-flip/editor/icons/2D.svg

Branch: https://github.com/aaronfranke/godot/tree/2d-flip

PR: https://github.com/godotengine/godot/pull/37013 (also https://github.com/godotengine/godot-design/pull/51)

**If this enhancement will not be used often, can it be worked around with a few lines of script?:**

The workaround is to ignore the problem and accept the current icon.

**Is there a reason why this should be core and not an add-on in the asset library?:**

This can't be an add-on in the asset library.

### PR DESCRIPTION
**Pull request by aaronfranke**
Implements and closes https://github.com/godotengine/godot-proposals/issues/1818

There are already other icons shaped in this way, such as all the curve icons and graph edit.

See: https://github.com/godotengine/godot-design/pull/51

### CODE REVIEW

**Comment by YeldhamDev** [comment]
Shouldn't the 3D icon be flipped as well, then?

**Comment by aaronfranke** [comment]
@YeldhamDev I don't see why it would be. In Godot, Y is up in 3D, but down in 2D.

**Comment by groud** [comment]
Honestly, I don't think it's worth breaking the consistency of the two icons just to match the axis orientation of the engine...

**Comment by aaronfranke** [comment]
One of the big reasons I think this is a good change is because there are many users who jump into Godot and are confused because they didn't know Y was down. Or at least, the users that are confused by this are quite a vocal minority.

If this icon is shaped in this way, hopefully it means that people will look at it, think "huh?", and will figure out that Godot uses a Y is down coordinate system for 2D.

**Comment by akien-mga** [comment]
I'm also not sure that the gain in "correctness" will actually be a gain in usability, as the 2D and 3D icons are next to each other and are meant to convey the meaning of 2 versus 3 dimensions.

The flipped 2D axes might not be as recognizable as two axes, especially since we're so used from math school to have 2D axes pointing up and right. The fact that nobody ever asked for this icon to be changed likely comforts the idea that this icon is not what causes the confusion for new users on the OpenGL / graphics flipped Y axis.

Still, I'm not strongly against either. It would be nice to include before/after screenshots for comparison (including the 3D button next to it).

**Comment by aaronfranke** [comment]
old
new

It does make more sense when given some context. For example:

**Comment by groud** [comment]
I find it pretty confusing when put next to the 3D icon personally.

**Comment by groud** [comment]
Also, to be honest, I think you are overestimating how confusing our convention is to newcomers.
Indexing 2D things like that is very common. It's what most image editing software use, and even a lot of game engines use it (like RPGMaker for example). This convention corresponds basically to the orientation we use to read.

I understand that it's different to what you learn in math, but honestly, children is less our target than professionals who are used to computer conventions. IMHO, we don't need to more than what is already done, consistency between the two icons is more important to me.

**Comment by aaronfranke** [comment]
> but honestly, children is less our target than professionals who are used to computer conventions.

Isn't that an argument in favor of flipping it? Professionals who are used to Y is down may prefer the consistency of having Y being down in the icon too. Also, why not target everyone?

Really I'm fine either way, I just think that this is an improvement, so I opened the PR. It would have made more sense to discuss this in godot-design before coming here with a PR for the engine, but nobody commented there for 3 months.

**Comment by groud** [comment]
> Isn't that an argument in favor of flipping it? Professionals who are used to Y is down may prefer the consistency of having Y being down in the icon too. Also, why not target everyone?

Not really, it was more to emphasize that we don't have to make so many effort not to confuse users.

> It would have made more sense to discuss this in godot-design before coming here with a PR for the engine, but nobody commented there for 3 months.

For such small change, I believe it's ok just to open a PR, which kind of forces us to talk about it. ^^

Anyway, I am not strongly opposed too. If a majority of people is for the change I am ok.

**Comment by MCrafterzz** [comment]
Makes sense imo

**Comment by Xrayez** [comment]
> > but honestly, children is less our target than professionals who are used to computer conventions.
> 
> Isn't that an argument in favor of flipping it? Professionals who are used to Y is down may prefer the consistency of having Y being down in the icon too. Also, why not target everyone?

According to my experience interacting with Godot members, the engine's development is actually in-between the two camps, so @groud's opinion is probably not actual by now.

Unfortunately, I think it's difficult to make something both professional and beginner-friendly (out of the box), so Godot chooses to cater beginner use cases more. Also, I treat "beginner-friendly" almost on the same level of "children-friendly", else it would be just age discrimination to say otherwise. Children nowadays pick up technologies faster than some adults.

That said, I have no strong opinion about this either. I had no problem with the icon so far, and I wouldn't rely on the icon to teach me the math behind Godot, what I did back in the days is to look up "Getting Started" tutorials in Godot. The "professionals" would probably to the same, if they're completely new to Godot/game development in general.

**Comment by DeerTears** [comment]
I think this is an interesting change that would get more people to recognize how Godot does 2D differently. You've already done the work, I think it's a decent idea to change this just for consistency's sake. Though I wouldn't say the arrows being the wrong direction actually provides confusion. It just feels like a missed opportunity to subliminally reinforce the engine's features. Adding X and Y values to one object in 2D is the fastest and easiest way to learn how Godot orients things in 2D, and looking at this icon has never made me think twice about it. I click it and forget it. But we might as well take advantage of your change and subliminally reinforce Godot's 2D axis anyways.

**Review by KoBeWi — APPROVED** [review]
This spawned lots of discussion but doesn't seem like anyone is really opposed. Also we did similar thing with 2D gizmos already. I'd just merge it.

**Review by Calinou — APPROVED** [review]
I think we can give this a try in `master` at least and see if there are any significant complaints. If there are none, we can keep it and merge it in `3.x` as well.

**Comment by groud** [comment]
Well, I don't mind much. It's a change no one asked for but well... If we want to try it for the sake of it that's ok...

**Pull request merged**
