### PR TITLE
Allows to map an action to all devices.

### PR DESCRIPTION
**Pull request by Nibodhika**
This is accomplished by setting a special value (-1) to the device variable
in the InputEvent that's being used to compare with the one received from the OS.

This special value is invalid for a regular input, so it should be safe.
Implements #17942

### CODE REVIEW

**Comment by Nibodhika** [comment]
Before this gets reviewed here's what I already intend on doing because of the fails:

- Fix clang-format rules
- Rename ```DeviceMode::SINGLE_DEVICE``` and ```DeviceMode::ALL_DEVICES``` to ```DeviceMode:::SINGLE_DEVICE_MODE``` and ```DeviceMode::ALL_DEVICES_MODE``` and use ```SINGLE_DEVICE_MODE``` and ```ALL_DEVICES_MODE``` on the cpp to fix the compilation fails with clang.

**Comment by bojidar-bg** [comment]
I think hardcoding the -1 value to mean "all devices" would be good enough.

**Comment by Nibodhika** [comment]
The problem with hardcoding -1 is that it's used on two different places, but it you think the variable shouldn't exist it should at least be documented somewhere that -1 means all devices, where should that be?.

**Comment by reduz** [comment]
This is pretty cool, can you show a screenshot on how selecting this on the editor looks?

**Comment by Nibodhika** [comment]
Sure, this is the default view (equivalent to the current one)
single_device
The selection box
choose_device
And how it looks when the user selects all devices
all_device
And how the action appears listed
after_selection

**Pull request merged**
