### PR TITLE
GDScript Built-in: add inverse_lerp & range_lerp

### LINKED ISSUE #10195: Add map() function, for mapping values from a range to another
I used [Processing](http://processing.org) and it contains a very useful function **map()**
it works like this: `var result = map(v, a,b, x,y)` you pass a value **v** which is between **a** and **b** and the function will return a number between **x** and **y**

ex: `var r = map(60, 20,100, 200, 240)` this will return **220**
or: `var g = map(0.43, 0,1, 0,255)`

From [here](https://forum.processing.org/one/topic/recreate-map-function.html) i saw that the actual java code used is:
`static public final float map(float value, float istart, float istop, float ostart, float ostop) {`
 `    return ostart + (ostop - ostart) * ((value - istart) / (istop - istart));`
`}`

I really love to add it myself but i never worked in other's codes and i don't know how and where to put it so please somebody add it .. its very usefull

### PR DESCRIPTION
**Pull request by ghost**
WIP

It's useful to me and some other people.
Fixes #10195

### CODE REVIEW

**Comment by vnen** [comment]
I don't like the `rlerp` name, it's too cryptic. I would prefer `range_lerp` or simply `remap`.

**Comment by Noshyaar** [comment]
`remap` sounds nice as it has the original `map` name and might be harder to get mixed-up with other uses of "Map". Will change to that.

**Comment by groud** [comment]
Also, I figured out that Unity has an InverseLerp function. Maybe you could add this function too ?
In that case I think `range_lerp` would make more sense, so that all three end with "lerp", it help understanding that those finctions works together.

Also that would mean that you could implement range_lerp with something like:

**Comment by tagcup** [comment]
I don't find this function useful, and I don't agree that it should be in the core for reasons I've reiterated several times in #10195.

**Comment by Noshyaar** [comment]
I don't find VisualScript useful and it should be removed from the core.

**Comment by Noshyaar** [comment]
@groud I'm not sure what InverseLerp would return if, `InverseLerp(min,max,val)`
1. `min` is equal to `max`
2. All params are equal

**Comment by fracteed** [comment]
I agree with @vnen that remap is a much better name for it, or even rangemap which is the name I tend to use.

**Comment by groud** [comment]
@Noshyaar min should not be equal to max. Just raise an error if so with ERR_COND...(i don't remember the exact name) and return 0 or something like that.

**Comment by bojidar-bg** [comment]
@groud Well, if they are equal, you get a division by zero, but since you use floating-point numbers, you get either +Infinity or -Infinity, no?

**Comment by groud** [comment]
Well in any case having min==max is not a valid argument, an error should be raised. 
The result of a division by 0 is by definition undefined, so the function can return anything, this will allways be wrong and the error **sould** be handled. :) The best would be to have a NaN value but this is not possible in C++.

**Comment by Zylann** [comment]
Just a note, working with Unity for years and never used InverseLerp, even though I know it exists. Must be the habit of doing things explicitely though.

If they are added, I think `inverse_lerp` is better than `remap`, because it refers to that same well known operation, there is no `map` function, and it's a quite small name to be put in global space. Also, it only concerns floats (not ints, not vectors, not colors, nothing interpolable but floats).

**Comment by groud** [comment]
Could you rename the parameters of `lerp` and `inverse_lerp` to make them a little bit more explicit ?
Maybe like what you did with `range_lerp` ?

**Comment by akien-mga** [comment]
As [discussed on IRC](http://godot.eska.me/irc-logs/devel/2017-08-22.log) (from 0:14), since we provide `lerp()` it makes sense to include `inverse_lerp`, which is `lerp`'s inverse operation and can be used to undo a `lerp()`.

**Pull request merged**
