### PR TITLE
Put misc. 3D tool visible instances on their own layer

### PR DESCRIPTION
**Pull request by RandomShaper**
This makes that visible stuff invisible to `ReflectionProbe`s, whose preview in the editor shouldn't involve them.

Otherwise you get this in the editor (not a big deal, but neither desirable):

image
image

---
**This code is generously donated by IMVU.**

### CODE REVIEW

**Review by JFonS — APPROVED** [review]

**Comment by akien-mga** [comment]
Can this be used to fix #8485 / #8140?

**Comment by RandomShaper** [comment]
Good question, but I don't think so.

**Comment by JFonS** [comment]
They are separate issues. Post-process effects are applied after everything is rendered to the viewport, by then any information on the render layer is already lost. 

In order to keep gizmos unaffected by post-processing we would have to render the scene first, apply the effects, and then render the gizmos on top of that.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
