### PR TITLE
doc (NodePath): Rewrite description and all methods.

### PR DESCRIPTION
**Pull request by JoshuaGrams**
I think this completely documents NodePath: see what you think, or if there's anything that I'm forgetting...?

### CODE REVIEW

**Comment by akien-mga** [comment]
It's great, I've learned quite a few things about NodePath :D

**Comment by JoshuaGrams** [comment]
OK, I think I fixed all the links. I was just testing in the engine/editor and links in general seem to work somewhat intermittently. Dunno what that's about. But I'm pretty sure I saw every one work at least once...

**Comment by akien-mga** [comment]
Looks good yes. Could you merge both commits into one with ```git rebase -i HEAD~2```?

**Comment by JoshuaGrams** [comment]
Ack. That just seemed to make it worse? I don't know how to get github to back up and change existing history...hmm. Time to go read the docs, I guess.

**Comment by akien-mga** [comment]
Hm normally ```git rebase -i HEAD~2``` in your class-docs branch, and changing the second commit's ```pick``` for ```fixup``` should have done the trick.
Though I've already seen weird behaviours like above on GitHub, but never understood what could cause it. On my end it works fine most of the time.

**Comment by akien-mga** [comment]
But git can be weird sometimes :D

**Comment by JoshuaGrams** [comment]
Yeah, that's what I did, but it just added a merge commit on top. I'll reset it and try a force push, see what it thinks of that...

**Comment by JoshuaGrams** [comment]
There we go.

**Comment by akien-mga** [comment]
Ok that worked well now. Just be careful with your master branch, it seems to have diverged a bit from master (16 commits ahead).

**Comment by JoshuaGrams** [comment]
Oh, that's on purpose; I'm using branches from upstream for fixes and my master for other stuff.

**Comment by akien-mga** [comment]
Ah, nevermind my comment then :D

**Pull request merged**
