### PR TITLE
Improve area method descriptions

### LINKED ISSUE #4446: GetOverlappingAreas() definition is not clear
**Your Godot version:**
3.2.3 stable mono (C#)
**Issue description:**
I am heavily relying on using Area2D objects. Area2D object has a method `GetOverlappingAreas()`.

The Method [GetOverlappingAreas()](https://docs.godotengine.org/en/stable/classes/class_area.html#class-area-method-get-overlapping-areas) is defined as 
**Returns a list of intersecting Areas.** 

It is not clear to me does this mean `Area2D.GetOverlappingAreas()` :
1) returns all areas who are defined in the collision mask of the Area2D
2) ALL areas who are intersecting Area2D (regardles of their collision layer and of Area2D collisionMask)

**URL to the documentation page:**
https://docs.godotengine.org/en/stable/classes/class_area.html#class-area-method-get-overlapping-areas

### PR DESCRIPTION
**Pull request by skyace65**
Improves the description of the methods `get_overlapping_areas()` and `get_overlapping_bodies()` for Area2D and Area3D. It now specifies that it only returns nodes in the same collision layer or collision mask. Closes https://github.com/godotengine/godot-docs/issues/4446

### CODE REVIEW

**Comment by KoBeWi** [comment]
The new description is a bit misleading. Area intersects if the mask matches layer of the other object (or vice versa), not if the masks/layers are the same.

**Comment by skyace65** [comment]
Ok, I've changed the descritpion. How is it now?

**Comment by KoBeWi** [comment]
Seems too verbose, but at least it's true.

**Review by pouleyKetchoupp — CHANGES_REQUESTED** [review]
Sorry for the delay before reviewing.

Thanks for making this improvement, I've just made some suggestions to take recent changes into account and make the text a little bit clearer.

**Pull request closed without merging**
