### PR TITLE
Enables parent-children relationship line drawing in scene tree editor

### PR DESCRIPTION
**Pull request by UgisBrekis**
Helps to distinguish better which children nodes belong to which parent.
Can be turned on/off in editor settings + line color change available as
well

### CODE REVIEW

**Comment by ScotFlux** [comment]
Very Cool... :+1: 

ub_bifo

ub_afte

**Comment by reduz** [comment]
Tree used to have this a long time ago, I think it can be seen in early screenshots somewhere and some might remain in code.

I'm not sure if this is a win, I always found these really confusing. If some people seriously needs this we could add an option to enable them but definitely would not add them by default..

**Comment by ScotFlux** [comment]
It already has : 

1) Disabled by default. We need to enable it via Editor Settings.
2) Color switcher for the line.

drl

**Comment by slapin** [comment]
Thanks for this, it is really a good thing!

**Comment by akien-mga** [comment]
Looks good, and apparently it's already opt-in, so I'm all for merging it. Could you maybe just make the default colour a bit less noticeable? IMO a grey slightly lighter than the background colour would already make the guides quite prominent, without grabbing too much the attention away from the important stuff.

**Comment by UgisBrekis** [comment]
scene-tree-relationship-lines

The default color is like in this. @ScotFlux has already player around with it in his example.

**Comment by akien-mga** [comment]
Awesome then :)

**Pull request merged**
