### PR TITLE
Added a few notes to classes.xml

### PR DESCRIPTION
**Pull request by Brickcaster**
I added a few tidbits of documentation regarding matrix32, array, and color, and sprite classes.

### CODE REVIEW

**Comment by Brickcaster** [comment]
It appears commit baa59c067031a790912239277f5fdff96193af7a supercedes and makes commit d222e82559014430d64142a6c373543bf4f2233e irrelevant.

**Comment by akien-mga** [comment]
> It appears commit baa59c0 supercedes and makes commit d222e82 irrelevant.

Could you then rebase to remove d222e82? See ```git rebase -i HEAD~5``` and remove the line corresponding to d222e82. This will prevent merge conflicts with @vnen's PR.

**Comment by Brickcaster** [comment]
Alright, I did a rebase and removed the conflict.

**Comment by akien-mga** [comment]
Thanks. Note that 44057ed might be overridden next time the template is updated from the source code; if those arguments are really Vector2s, then the issue might be in the source code directly. But we'll see, let's merge.

**Pull request merged**
