### PR TITLE
Don't try updating wrong NodePaths in resources

### LINKED ISSUE #83209: [4.2 beta1] Relative paths in nodes referenced as PackedScenes cause errors in console
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Godot v4.2.beta1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3742) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Having exported PackedScene (and any structure using them, such as Array[PackedScene]), which reference a complex scene that contains internal references (exports own nodes) will cause `Found invalid node path` spammed in console, specifically in this version of Godot

### Steps to reproduce

1. Make a separate scene, and 2 children of it (for example, AnimatedSprite2D, and Node2D that will be acting as a component)
2. Attach a script to Node2D, that exports variable of type AnimatedSprite2D, and assign previously made sprite to it, in that scene
3. Save that scene, and add it in any place that exports variable of type `PackedScene` (or contains it)
4. Add a child to the node exporting PackedScene and remove that child

At that point you'll get the following:
```
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 Found invalid node path '../AnimatedSprite2D' on node 'Main'
 ```
 
 Presumably now there's a code that checks node paths, and as exported variables within scenes use relative paths - which cannot be resolved by node that contains references to them for some reason.
 
 MRP contains stuff above, all you really need to do is to add any child to `Main` (in `main.tscn`) and remove it afterwards.

### Minimal reproduction project

[bug_repro_1.zip](https://github.com/godotengine/godot/files/12886295/bug_repro_1.zip)

### PR DESCRIPTION
**Pull request by KoBeWi**
Fixes #83209

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by tom95** [comment]
Thanks a lot @KoBeWi!

The one error is indeed fixed, I just verified as well.

The error with renaming nodes used in an AnimationPlayer persists. As I understand it, it occurs because the AnimationPlayer handles its tracks specially (it is the only Resource that already supported renaming nested NodePaths, controlled via the `autorename_animation_tracks` setting). Consequently, when first encountering the AnimationPlayer, the special-cased code performs the rename, and then we descend into the AnimationPlayer object and try to perform the rename once again, thus erroring. A suggested fix that I verified fixed the other scenario, too, is to add this check:

```diff
diff --git a/editor/scene_tree_dock.cpp b/editor/scene_tree_dock.cpp
index a38487635f..81805a45d2 100644
--- a/editor/scene_tree_dock.cpp
+++ b/editor/scene_tree_dock.cpp
@@ -1689,6 +1689,10 @@ bool SceneTreeDock::_check_node_path_recursive(Node *p_root_node, Variant &r_var
                                break;
                        }
 
+                       if (Object::cast_to<Animation>(r_variant)) {
+                               break;
+                       }
+
                        List<PropertyInfo> properties;
                        resource->get_property_list(&properties);
```
...such that we never descend into Animation resources.

**Comment by KoBeWi** [comment]
I can't reproduce the renaming error. The track gets correctly updated too.

**Comment by tom95** [comment]
@KoBeWi yep you're right. I must have mixed up branches. Everything is working perfectly with your change.

Sorry for the noise and thanks again for the swift fix :)

**Comment by akien-mga** [comment]
Thanks!

**Comment by eviltrout** [comment]
Thanks so much this bug was really slowing me down! I can confirm it works for me too.

**Pull request merged**
