### PR TITLE
Allowing double-axis lock in RigidBody & KinematicBody (Fixes #12500)

### LINKED ISSUE #12500: Physics improvement: Add the ability to constrain bodies along a given axis.
When making side scrolling game with 3D assets, the objects can push each other in any direction, including forwards and backwards off the level (along the Z axis).
image

I've solved this for my project by creating a scene with a single Node and script that constrains objects on a set axis:
image
and script:
image

I just instance this node as a child of every single physics object I create. It would be great to have an in-engine solution for this however, similar to Unity where a RigidBody has a series of checkboxes for constraining objects on specific axes.

Ideally it would be available on KinematicBody and RigidBody in Godot, so it would be implemented for PhysicsBody i guess?

A screenshot from the Unity docs for reference:
image

### PR DESCRIPTION
**Pull request by ericrybick**
Fixes #12500 
Adds the ability to constrain bodies along a given axis for kinematic bodies
Adds XY, XZ & YZ combined constraints.

C++ is a very new playground for me so please review before merging and let me know if something needs to be adjusted. 

The Platformer 3D demo is a good preset to test my fix. ;)

### CODE REVIEW

**Comment by groud** [comment]
As suggested in #12500, it may have been better to have checkboxes. But I guess this might be ok too :)
Could you please **amend** your commit and give it a more descriptive message ? Something like "Allowing double-axis lock in RigidBody"

**Comment by Stratos695** [comment]
Thanks for your feedback. The commit has been amended. I thought Checkboxes are just a personal taste. Do you think that it would improve the usability? If so I can implement them instead.

**Comment by cart** [comment]
I think checkboxes would be an improvement:
1. it shows what is disabled
2. it allows locking all axes
3. if angular locks become a thing the axes will line up

this is much easier to read at a glance:
```
movement: x [✓] y [ ] z [✓]
rotation: x [ ] y [✓] z [✓]
```
compared to this: 
```
movement: xz
rotation: yz
```

**Comment by groud** [comment]
I personally think checkboxes are easier to read. 
The only drawback I see is that it would allow to lock all three axis, which could be confusing when the user tries to move the object and nothing happens. Still for me checkboxes stay better. ^^

**Comment by Stratos695** [comment]
Here they are. :)
My Code has become a bit hacky, because I had some trouble with passing arrays/vectors to thephysics_server_sw class and therefore decided to stick with the enum. (lacking C++ skills)

However it works and looks like desired.

preview

**Comment by groud** [comment]
Hum, maybe a little bit too hackish, the API get's too messed up for such simple change. I'd be ok merging if at least the API can stay clean, which implies: 
- Removing `preset_axis_lock()`, `set_axis_lock()` and `get_axis_lock()`.
- Remove the AxisLock enum
- Remove `apply_axis_lock()`

**Comment by Stratos695** [comment]
Thanks groud! I'm on it

**Comment by Stratos695** [comment]
Done. :)

**Comment by groud** [comment]
A lot better :)

**Comment by groud** [comment]
But sorry to bother you again, but could you please [squash the three commits](http://docs.godotengine.org/en/2.1/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase) together ?

**Comment by Stratos695** [comment]
No problem, thanks for guiding me through everything. I have squashed the commits.

**Comment by Stratos695** [comment]
And now it is adapted to the new bullet engine.

**Comment by akien-mga** [comment]
CC @AndreaCatania to review the Bullet changes.

**Comment by AndreaCatania** [comment]
@Stratos695 Fix these please:

- Instead of an int you should use an enum to point the axes to lock
- Then please insert the angular lock, in order to have something like below in the editor:
> ### Axis lock
> Linear X
Linear Y
Linear Z
Angular X
Angular Y
Angular Z

- The physics server API "get_axis_lock" should return the lock state of a particular axis.
- Please replace these function: `set_axis_lock_x, set_axis_lock_y, etc..` with one central function in order to have only one function that accept the axis to lock. You should handle editor properties using **_get** and **_set** function.

Bullet side:
- Add a function `reload_axis_lock();` then replace all lines `set_axis_lock(0, locked_axis[0]);` with reload_axis_lock();.

### Side note:
Use only one array and one enum to store both Linear and Angular lock so you'll have less code to write.

**Comment by AndreaCatania** [comment]
@Stratos695 even better if you use an int to store this data as bitmask

**Comment by akien-mga** [comment]
Ping :)

**Comment by akien-mga** [comment]
Time is running out for 3.0. @AndreaCatania Should we merge and you can do the changes you requested on top of it?

**Comment by ScottMakesGames** [comment]
(yes)

**Comment by Alexia-AT-Digitecnology** [comment]
Please, add constraints for rotation too. It's an easy change.

**Comment by AndreaCatania** [comment]
@akien-mga Sure, i'll do it

**Comment by akien-mga** [comment]
Great. I'll merge this one as a base, and so that @Stratos695 gets the relevant credits, and you can build from there.

**Comment by Stratos695** [comment]
Sorry, last weeks I've been busier the than expected. Thanks @AndreaCatania  and @akien-mga ! Btw. I don't really care about credits, just wanted to help and to learn some c++ by using it. :)

**Pull request merged**
