### PR TITLE
Fix total weight calculation to separate track types

### LINKED ISSUE #94685: AnimationPlayer CallMethod Track causes issues with other animation tracks of the same node.
### Tested versions

4.3 Beta

### System information

Windows 10 - Godot 4.3 Beta - Forward+

### Issue description

CallMethod Track causes issues with other animation tracks on the same node. If the CallMethod Track is first, the other tracks will not work. If the CallMethod Track is not first, it will not work. Tested in both C# and GDScript as suggested.

### Steps to reproduce

From a new project:

Create MeshInstance3D named Floor.
Select a New PlaneMesh and resize to 20x20.
As a child node of Floor, add a Camera3D.
As a child node of Floor, add a CharacterBody3D named Character.
As a child node of Character, add a MeshInstance3D and select a New CapsuleMesh.
Attach the appropriate script below to Character and build the project.
In the 3D viewer, move Character in front of the Camera3D.
As a child node of Character, add an AnimationPlayer.
Add a new animation to the AnimationPlayer called "Test" and set it to Looping.

Add a CallMethod Track for Character.
Add key frames for the F1() and F2() methods at any point within the track.
Run in Debug. "1" and "2" will print as expected.

Add a Position Track for Character.
Add key frames with a new position for Character at any point within the track.
Run in Debug. "1" and "2" will print, but Character will not move.

Delete the CallMethod Track.
Run in Debug. Character will now move.

Re-add the CallMethod Track with F1() and F2() at any points on the new track.
Run in Debug. Character will move, but "1" and "2" will not print.

Results are the same using C# or GDScript.
Note: Adding additional tracks like a Rotation Track, will have Character both move and rotate as expected. Only CallMethod Track doesn't work.

```
using Godot;

public partial class Character : CharacterBody3D
{
    public override void _Ready()
    {
        GetNode<AnimationPlayer>("AnimationPlayer").Play("Test");
    }


    public void F1()
    {
        GD.Print("1");
    }


    public void F2()
    {
        GD.Print("2");
    }
}
```

```
extends CharacterBody3D

func _ready():
    get_node("AnimationPlayer").play("Test")
	
func F1():
    print("1")
	
	
func F2():
    print("2")
```

### Minimal reproduction project (MRP)

[CallMethodTrackTest_CS.zip](https://github.com/user-attachments/files/16357632/CallMethodTrackTest_CS.zip)
[CallMethodTrackTest_GD.zip](https://github.com/user-attachments/files/16357636/CallMethodTrackTest_GD.zip)

### PR DESCRIPTION
**Pull request by TokageItLab**
- Fixes https://github.com/godotengine/godot/issues/94685

The total weight was added to normalize the blend amount in non-deterministic blending by https://github.com/godotengine/godot/pull/80813.

Before https://github.com/godotengine/godot/pull/86687, checking by blend idx was sufficient due to track type conflicts, since it was not working due to a bug in the first place. Now that the type is managed as a hash for each cache type, it should be changed to a check by that.

**Explanation of their differences:**
- blend_idx is for **filtering**, one per track path.
- track_hash is for **blending**, one per blendable track group.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Welp, I merged this PR locally just before you pushed a new commit, and now pushed it to `master`.

So it's 04ac6a74dfa6c49e399d622a9bf87a3631078578 that got merged, if more changes are needed this will need to be in another PR.

**Comment by TokageItLab** [comment]
Oops, sorry

**Comment by akien-mga** [comment]
No problem, I actually noticed the yellow "CI running" icon just after pushing to `master`, I should have double checked before.

**Comment by TokageItLab** [comment]
@akien-mga Alright I sent https://github.com/godotengine/godot/pull/94722, I should have checked carefully too, sorry.

**Pull request closed without merging**
