### PR TITLE
Internal hints for Dictionary

### PR DESCRIPTION
**Pull request by ghost**
Speeds up `Dictionary` iteration by 10% to 20% in `release_debug` builds (depending on the dictionary size) by keeping an internal hint and thus skipping unnecessary calls to `OrderedHashMap ::find()`.

This PR adds various `_FORCE_INLINE_` to `OrderedHashMap` that are obviously only one or two assembler instructions - this is not related to the performance measurements above (**EDIT** i.e the performance was measured while these `_FORCE_INLINE_` were in place for both hints and non-hints).

GDScript performance test code used:

```
	var t0 = OS.get_ticks_msec()
	
	var d = Dictionary()
	for i in range(100):
		d[i] = i + 1

	for r in range(10000):
		var z = 0
		for key in d:
			z += d[key]
	
	print(OS.get_ticks_msec() - t0)
```

Code like the following benefits by (1) saving one `find` during iteration in `for` and (2) saving one `find` in `d[key]`:

```
		for key in d:
			z += d[key]
```

Loosely related to https://github.com/godotengine/godot/pull/15496, as with this current PR there's no performance hit of iterating and then accessing `d[key]`.

### CODE REVIEW

**Comment by akien-mga** [comment]
Moving to 3.2 milestone as we're about to enter the beta stage and release freeze for Godot 3.1. Only bug fixes against issues of the 3.1 milestone (or enhancements to core features of the 3.1 roadmap) will be considered until 3.1-stable is released.

Note: If it's merged after 3.1-stable is released, this change might be considered for cherry-picking into a later 3.1.x release.

**Comment by akien-mga** [comment]
Sorry for the lack of update in over a year :|

This PR has been buried by a pretty huge backlog, and as it's a low priority enhancement that only a few senior contributors would likely be confident reviewing, it is still waiting on any of them to do a proper review.

I'll move to the next milestone as it's too late for 3.2 to receive such enhancements, but I hope contributors like @reduz @hpvb @vnen or @RandomShaper can have a look once they have more bandwidth.

**Comment by aaronfranke** [comment]
@poke1024 Is this still desired? If so, it needs to be rebased on the latest master branch.

If not, abandoned pull requests will be closed in the future as announced [here](https://godotengine.org/article/headsup-vulkan-merged-master-branch-unstable).

**Comment by aaronfranke** [comment]
This PR has not received any new commits for almost 2 years and is abandoned, closing.

**Pull request closed without merging**
