### PR TITLE
Added Always Visible property to ScrollContainer scrollbars

### PR DESCRIPTION
**Pull request by Oen44**
Dynamically changing `ScrollContainer` width/height can result in scrollbar not visible anymore and leaving unnecessary empty space which in some cases might not look that great. Now it's possible to have scrollbars visible all the time.

### CODE REVIEW

**Comment by dalexeev** [comment]
We also need to implement the "Never show scrollbars" mode (but so that the content can be scrolled with the mouse wheel).

```
enum ScrollMode {
    SCROLL_MODE_DISABLED,
    SCROLL_MODE_AUTO,
    SCROLL_MODE_SHOW_ALWAYS,
    SCROLL_MODE_SHOW_NEVER
};

ScrollMode scroll_horizontal_mode;
ScrollMode scroll_vertical_mode;

```

**Comment by Calinou** [comment]
@dalexeev Out of curiosity, what do you need this for?

**Comment by Oen44** [comment]
> 
> 
> @dalexeev Out of curiosity, what do you need this for? Can you give some use case examples?

Also interested, scrollbars indicate that there is more content, from user point, this can be misleading.

**Comment by dalexeev** [comment]
@Calinou @Oen44 I need this to save space.

> this can be misleading

In some cases, it is obvious that the content is not fully displayed.

**Comment by dalexeev** [comment]
@Calinou Also, scrollbars are not the only way to indicate that content is not fully displayed.

**Review by Calinou — APPROVED** [review]

**Comment by reduz** [comment]
I agree that it makes sense to do this in some cases (there may be other custom ways that you might want to do to show there is more content) and an enum to always show and always hide (with default still to automatic) may be desired.

That said, this PR is entirely broken somehow, and as is this can't be merged.

**Review by reduz — CHANGES_REQUESTED** [review]
This PR is entirely broken, I don't think this is the right code.

**Comment by Oen44** [comment]
> 
> 
> This PR is entirely broken, I don't think this is the right code.

Let me quickly set it up again as I don't have this repo on my local machine anymore so I can resolve conflicts and fix whatever there is to be fixed. Everything was working (functionality wise) when I created this PR.

**Comment by KoBeWi** [comment]
It can't be implemented like this. ScrollContainer has `scroll_enabled` property, the recently added `scroll_visible` (#48008) and now you want to add `scroll_always_visible`, which is conflicting with the two. The enum suggested by dalexeev would be the way to go IMO.

**Comment by Oen44** [comment]
> 
> 
> It can't be implemented like this. ScrollContainer has `scroll_enabled` property, the recently added `scroll_visible` (#48008) and now you want to add `scroll_always_visible`, which is conflicting with the two. The enum suggested by dalexeev would be the way to go IMO.

Yeah, my way won't work anymore, changes between creation of this RP and now are too significant.

**Comment by akien-mga** [comment]
Closing as it would need further work to follow up on #48008. Thanks for the contribution nevertheless!

**Pull request closed without merging**
