### PR TITLE
Fix focus issues of `EditorSpinSlider`.

### PR DESCRIPTION
**Pull request by zaevi**
Fixes #53832

### CODE REVIEW

**Comment by clofresh** [comment]
I tried this PR on Arch Linux and tabbing still doesn't work.

**Comment by KoBeWi** [comment]
I tried on Windows and it fixes the issue.
There is some bug with Shift+Tab, but probably unrelated.

**Comment by KoBeWi** [comment]
Is this PR still relevant after #67397?

**Comment by YuriSizov** [comment]
Superseded by https://github.com/godotengine/godot/pull/71271

**Pull request closed without merging**
