### PR TITLE
Add lambda functions to GDScript

### LINKED ISSUE #2431: Add lambda functions in GDScript
### Describe the project you are working on

GDScript.

### Describe the problem or limitation you are having in your project

There are many times when you need to pass a function around, like when connecting signals, using the Tween node, or even sorting an array. This requires you to declare a function in another place in the file, which has a few issues.

If you're not using the function anywhere else, it's still available publicly to be called, which might not be wanted. It also has to live decoupled from where it's defined, which is not great for reading code, as it requires a context switch. This is particularly problematic if you want to rely on a local variable in scope when you connect the signal (you are forced to add it as a bind).

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

With lambdas, you are able to create functions in place. This allows you to make temporary functions without having to define it in the class scope somewhere else, solving the issues above. So you can write the signal callback at the same place you connect it. No need to switch context nor make a publicly available function.

This also allows for more functional constructs, like mapping a function over an array instead of a `for` loop, or passing a function to sort an array.

#### Syntax

The syntax for lambdas can be very similar to functions themselves, reusing the `func` keyword and using indentation to delimit the body:

```gdscript
func _ready():
    var my_lambda = func(x):
        print(x)
```

They can also be written in a single line, like regular functions:

```gdscript
func _ready():
    var my_lambda = func(x): print(x)
```

You can add a name to it, for debugging purposes (useful when looking at call stacks):

```gdscript
func _ready():
    var my_lambda = func my_lambda(x): print(x)
```

You can pass an inline lambda as a function argument:

```gdscript
func _ready():
    button_down.connect(func():
        print("button was pressed")
    )
```

Lambdas are treated like `Callable`s so to call those you need to explicitly use its `call()` method:

```gdscript
func _ready():
    var my_lambda = func(x): print(x)
    my_lambda.call("hello")
```

They're also closures and capture the local environment. Local variables are passed by copy, so won't be updated in the lambda if changed in the local function.

```gdscript
func _ready():
    var x = 42
    var my_lambda = func(): print(x)
    my_lambda.call() # Prints "42"
    x = "Hello!"
    my_lambda.call() # Prints "42"
```

This still allows you to create lambdas that act differently given the context, like this:

```gdscript
func make_lambda(x):
    var my_lambda = func(): print(x)
    return my_lambda

func _ready():
    var lambda1 = make_lambda(42)
    var lambda2 = make_lambda("Hello!")

    lambda1.call() # Prints "42"
    lambda2.call() # Prints "Hello!"
```

#### Implementation

Under the hood lambdas are like any ol' GDScript function, compiled to the same bytecode. They will be stored in a different place since they won't be publicly accessible, so you can't call a lambda without passing a reference to it.

Lambdas will use a Callable wrapper when they are created at runtime, pointing to the already compiled function. This will be a custom callable that will also have references to the enclosing environment, allowing closures to work as expected. When a function exits it will copy the closed on variables and store on that Callable, so the lambda can still exists after the function where it was created is out of the stack. This can be done efficiently by copying only values that were actually used in the lambda.

In the end it should have about the same performance of any function call.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

This can be worked around somewhat by defining the functions elsewhere and using Callables, but it does fall into the same issues described here. In particular, you cannot make this function private to ensure it won't be called outside its scope. You cannot easily work around closures.

### Is there a reason why this should be core and not an add-on in the asset library?

It needs to be part of the language implementation.

### PR DESCRIPTION
**Pull request by vnen**
Closes godotengine/godot-proposals#2431

See the referenced proposal for the syntax details.

Lambda functions are compiled as GDScriptFunctions and stored on their parent function, allowing lambdas to be nested too. At rumtime, they create a GDScriptLambdaCallable, which is used to reference the function itself and the potential captures. The captures are applied as extra arguments in the beginning of the list, but this is transparent to the users. This does incur in an extra performance penalty for lambdas with captures, but it shouldn't be too much.

### CODE REVIEW

**Comment by KoBeWi** [comment]
So I tried this line
```
$AnimationPlayer.animation_finished.connect(func(a): $Sprite2D.queue_free())
```
And it crashes with
```
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] Variant::get_validated_object_with_check (C:\godot_source\core\variant\variant.cpp:2075)
[1] Variant::get_validated_object_with_check (C:\godot_source\core\variant\variant.cpp:2075)
[2] GDScriptFunction::call (C:\godot_source\modules\gdscript\gdscript_vm.cpp:1629)
[3] GDScriptLambdaCallable::call (C:\godot_source\modules\gdscript\gdscript_lambda_callable.cpp:85)
[4] Callable::call (C:\godot_source\core\variant\callable.cpp:51)
[5] Object::emit_signal (C:\godot_source\core\object\object.cpp:1045)
[6] Object::emit_signal (C:\godot_source\core\object\object.cpp:1100)
[7] AnimationPlayer::_animation_process (C:\godot_source\scene\animation\animation_player.cpp:942)
[8] AnimationPlayer::_notification (C:\godot_source\scene\animation\animation_player.cpp:216)
[9] AnimationPlayer::_notificationv (C:\godot_source\scene\animation\animation_player.h:63)
[10] Object::notification (C:\godot_source\core\object\object.cpp:795)
[11] SceneTree::_notify_group_pause (C:\godot_source\scene\main\scene_tree.cpp:811)
[12] SceneTree::process (C:\godot_source\scene\main\scene_tree.cpp:442)
[13] Main::iteration (C:\godot_source\main\main.cpp:2495)
[14] OS_Windows::run (C:\godot_source\platform\windows\os_windows.cpp:622)
[15] widechar_main (C:\godot_source\platform\windows\godot_windows.cpp:163)
[16] _main (C:\godot_source\platform\windows\godot_windows.cpp:185)
[17] main (C:\godot_source\platform\windows\godot_windows.cpp:199)
[18] __scrt_common_main_seh (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[19] BaseThreadInitThunk
-- END OF BACKTRACE --
```

**Comment by vnen** [comment]
@KoBeWi this shouldn't crash (and I couldn't reproduce here, it fails without crashing). But it's actually not possible to do this, at least not yet, because the lambda has no concept of `self`, so you can just call `get_node()` with or without the shorthand notation (`$`).

I've updated the PR to check for this and give an error. You can use a capture to achieve the wanted behavior:

```
var sprite = $Sprite2D
$AnimationPlayer.animation_finished.connect(func(a): sprite.queue_free())
```

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by pietrodito** [comment]
I see it was merged with ` master`  25 days ago. Does it mean it is available in Godot 3.3.1 released May 18, 2021? Because I cannot make it work with:

```
func _ready() -> void:
	var l = func foo() -> void:
		pass
```

which says: `Error parsing: misplaced; fund`

**Comment by dalexeev** [comment]
No, this is merged into `master` (4.0-dev), not `3.x`.

**Comment by Calinou** [comment]
The `master` branch uses an entirely different implementation of GDScript, so this can't be backported to `3.x`.

**Pull request merged**
