### PR TITLE
Improvements and fixes to occluders

### PR DESCRIPTION
**Pull request by JFonS**
### Improvements
* Occluder3D is now an abstract type inherited by: ArrayOccluder3D, QuadOccluder3D,
  BoxOccluder3D, SphereOccluder3D and PolygonOccluder3D. ArrayOccluder3D serves the same purpose as the old occluder3D (triangle mesh occluder) while the rest are primitives that can be used to manually place simple occluders.

* Occluder baking can now apply simplification. The "bake_simplification_distance" property can be used to set a world-space distance as the desired maximum error, set to 0.1 by default.

* Occluders can now be generated on import. Using the "occ" and "occonly" keywords (similar to "col" and "colonly" for colliders) or by enabling on MeshInstance3Ds in the scene's import window.

### Fixes
* Fixed saving of occluder files after bake.
* Fixed a small error where occluders didn't correctly update in the rendering server.

### Bonus content
* Generalized "CollisionPolygon3DEditor" so it can also be used to edit Resources. Renamed it to "Polygon3DEditor" since it was already being used by other things, not just colliders.
* Fixed a small bug in "EditorPropertyArray" where a call to "remove" was left after the "remove_at" rename.

image

### CODE REVIEW

**Comment by JFonS** [comment]
I just realized I didn't add docs for the new classes, I will do that in a bit.

**Comment by reduz** [comment]
I think this is ok, but at some point we will need to implement dynamic occluders (those that are just rastered to the depth buffer and hence can move without any cost), so I believe we should differentiate between those.

Additionally, would it not make more sense to have StaticOccluder3D and the occluder type being a resource?

**Comment by lawnjelly** [comment]
It looks good to me. I can't pretend I've gone through with a fine toothed comb, and there are some aspects I'm not really very expert in, like importing, so yes probably anyone else who can look through this would be good as well.

I've also tested the artifact for the occluders and they seem to work fine from what I tried.

**Comment by Calinou** [comment]
I gave this a quick try locally and it seems to work as expected. :+1: 

As a bonus (in a future PR), I wonder if there could be a "Create Occluder" option in the MeshInstance context menu:

image

This would complement the other collider and navigation options.

**Review by akien-mga — APPROVED** [review]
Consensus seems to be that it's a good step in the right direction, and follow-up work should go in new PRs, so we can merge this.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
