### PR TITLE
Added tooltip for a few buttons in sample library editor

### PR DESCRIPTION
**Pull request by ivanskodje**
I have added appropriate tool-tips on a few buttons that did not have any tool tips or descriptive text associated with them.

### CODE REVIEW

**Comment by jackmakesthings** [comment]
:+1:

**Comment by eska014** [comment]
The tooltips should use the term 'sample' rather than 'audio'. Audio can also be a stream, a voice, etc.

**Comment by Tybobobo** [comment]
Better now? :)

**Comment by eska014** [comment]
:ok_hand:

**Comment by eska014** [comment]
However, now you're adding a file `/build.bat` to the repository.

**Comment by akien-mga** [comment]
@Tybobobo Could you merge the three commits into one, using ```git rebase -i HEAD~4``` and then replacing "pick" by "fickup" before the last two commits?

**Comment by Tybobobo** [comment]
Not sure what to do after I type in "git rebase -i HEAD~4". 
( http://i.imgur.com/TzDoyS9.png ) 

I am unable to see the last commit in the list, but I can see the commit before that.

**Comment by akien-mga** [comment]
Hm strange. Do you see the last commit with ```git log```? Try maybe ```git checkout HEAD``` to make sure you are not in a "detached HEAD state" (yeah git has a funny vocabulary :p).

Try also ```git rebase -i HEAD~3```, I've seen strange behaviours too sometimes when trying to rebase too many commits at once (like asking for 7 commits and getting 25...).

**Comment by Tybobobo** [comment]
It says I am up to date with "git checkout HEAD". When I check git log, the last commit noted is the Audio to Sample in tooltip. Very odd

**Comment by akien-mga** [comment]
Assuming your local repo is a clone of your own fork, try maybe:
```
git checkout sample-lib-editor
git pull --rebase origin/sample-lib-editor
```
And see if you get this 3rd commit back :)

**Comment by Tybobobo** [comment]
I got it - I just don't know what to do in the rebase menu - or rather, how to do it :)

**Comment by akien-mga** [comment]
Good. So what you get when you start the rebase is a text editor (hopefully one that you know, i.e. not vim if you're a nano guy like me :p). Then you can replace the word "pick" by "fixup" for the last two commits listed in the top section, i.e.:

```
pick eedd2fb Added tooltip for a few buttons in sample library editor
pick 3366295 Changed Audio to Sample in tooltip
pick 78433e4 Deleted a custom file
```

should become:
```
pick eedd2fb Added tooltip for a few buttons in sample library editor
fixup 3366295 Changed Audio to Sample in tooltip
fixup 78433e4 Deleted a custom file
```

And then save the changes and exit the editor, it should do the rebase.

**Comment by akien-mga** [comment]
Once that is done, you need to force push your changes to your remote repo, like with: ```git push -f```

**Comment by Tybobobo** [comment]
I am not on Linux, and it wont allow me to edit the text after entering the rebase command - no matter what I press.

**Comment by vnen** [comment]
@Tybobobo looks like the Vim editor. You should press `I` to enable insert mode and it'll let you type. When you finish, press `Esc` to return to normal mode and then `:wq` to save and close. Also, there might be a way to set another editor (maybe if you do `export EDITOR=notepad` before doing the rebase).

**Comment by akien-mga** [comment]
Yeah if you don't have experience with vim already, I would advise to try to define a different default editor, as vim has a very steep learning curve. Maybe try:
```
git config core.editor '"C:\Program Files\Windows NT\Accessories\wordpad.exe"'
```

**Comment by reduz** [comment]
can this be merged?

**Comment by akien-mga** [comment]
> can this be merged?

Almost, but my maniac self doesn't like to see the addition and subsequent removal of a build.bat in the repo :) I'll quickly do another cleaner PR by cherry-picking those commits.

**Comment by akien-mga** [comment]
Done in #2815.

**Pull request closed without merging**
