### PR TITLE
Refactor VS specific `glob_recursive_2` function

### PR DESCRIPTION
**Pull request by ghost**
It also:
* Deletes old unused `add_to_vs_project` function
* Ensures that list passed to `json.dumps` is properly sorted

Both these additional "bugs" were added in 7638a6c9811590a384e2126dd004e302f76d3e4a

1. `add_to_vs_project` function was just overlooked
2. `sort_keys` parameter of `json.dumps` doesn't have any sense when you pass there a **list** which doesn't have any keys... Before consistent order was provided by deterministic nature of search code and list concatenation but now it will be ensured by using `sorted()`. And `sorted()` in this PR is mandatory because when you do `[*list, *set]`, order of elements will be random when you expand sets...

### CODE REVIEW

**Comment by dustdfg** [comment]
CC @shana

**Review by shana — CHANGES_REQUESTED** [review]
This change is dropping directories without files but that have subdirectories with files in them, which means the filters file will not have complete entries and some files will be missing. Compare the output of vcxproj.filters before and after this change (sort the file in an editor for an easier comparison, and note that, for instance, the `Filter` entries `Source Files\misc`, `Source Files\misc\dist` and `Source Files\misc\dist\ios_xcode` are all missing for the path `misc\dist\ios_xcode\godot_ios\dummy.cpp`. These entries are required for the filtering to work, and without them, the project will have all of those files dumped into the root of the project instead of sorted into the respective folders. You should open the project after generating to see if there are any orphan files at the root of the project - there shouldn't be any loose files outside of folders.

**Comment by dustdfg** [comment]
First of all. I use Linux... Yeah, I understand what you think that I am proposing changes to vs code while not use... But this info is crucial for context of my following questions...

1. You can generate vs proj files under different platforms and they should be identical?
    1.1. If running `scons vsproj="yes"` under linux isn't supposed, so why does it appear possible to run it on linux! 
2. Running `scons vsproj="yes"` must produce not only `<Filter Include="Source Files\misc\dist\ios_xcode\godot_ios">` but also `<Filter Include="Source Files\misc\dist\ios_xcode">`
   2.1 Are you sure that master behaves differently? Because when I run `scons vsproj="yes"` I see inside `godot.vcxproj.filters` only `Source Files\misc\dist\ios_xcode\godot_ios` it doesn't produce `Source Files\misc`
3. It should be `Source Files\misc` not `Source Files\misc/dist/ios_xcode` (different slahes)?

**Comment by dustdfg** [comment]
Do you agree about `add_to_vs_project` deletion?

**Comment by dustdfg** [comment]
Just thought that I forgot to look at variables of `add_to_vs_project` and where they are used. They are used in following places:

https://github.com/godotengine/godot/blob/e65a23762b36b564eb94672031f37fdadba72333/SConstruct#L1057-L1060

https://github.com/godotengine/godot/blob/e65a23762b36b564eb94672031f37fdadba72333/platform/windows/SCsub#L83-L91

But looks like the only real place where they were is used is a function deleted in the same commit as in the description of PR

**Comment by shana** [comment]
@dustdfg oh sorry, totally missed your question there. Yeah, I left the code in because the new implementation was optional initially, but there's no point in keeping the old code around now, deleting is great.

As for the sorting, I didn't realize it wasn't actually sorting, so yeah, using sorted is good. Sorting is important there because we're calculating an md5 hash of all the content so we can avoid touching the file if it hasn't been changed, to avoid VS reloading projects and potentially some user customizations that might be lost in that unavoidable process, so we should keep those keys sorted.

**Comment by dustdfg** [comment]
As all fruitful and non destructive changes are extracted in a separate PR, I am closing this because see that probably refactoring will use more SCons internals than necessary, can impact performance (I don't think that much but can), possibly can't be tested by me, I am a bit tired of this concrete topic and maybe will return to it later

@shana but I would appreciate if you answer other questions which will allow me to get deeper knowledge

**Pull request closed without merging**
