### PR TITLE
Specify MINGW_HAS_SECURE_API=1

### PR DESCRIPTION
**Pull request by yeonghoey**
Fix https://github.com/godotengine/godot/issues/33062

### CODE REVIEW

**Comment by akien-mga** [comment]
I wish homebrew fixed their mingw distribution instead to be consistent with what Linux and Windows mingw distributions provide. But in the meantime I guess this doesn't hurt.

**Comment by akien-mga** [comment]
BTW, no need to make two pull requests, PRs should be made against the `master` branch only, and we take care of cherry-picking changes to relevant stable branches.

**Comment by yeonghoey** [comment]
Just so you know, I made two because I noticed that the way of specifying flags changed a little bit.

**Comment by akien-mga** [comment]
Ah I see, my bad. Let's keep this one open then.

**Comment by akien-mga** [comment]
Thanks!

**Comment by yeonghoey** [comment]
Thank you :)

**Pull request merged**
