### PR TITLE
Revert to the old Camera icons

### PR DESCRIPTION
**Pull request by MewPurPur**
People weren't very in favor of the new camera icons according to Juan's twitter poll, for many reasons, mainly:
- The film camera was a very good analogy for how the camera continuously looks at a region in the game world, while the new camera suggests you snap it to take a photo.
- The reason for the change was direction-neutrality, but the new icon was still not completely neutral, looking at the viewer.
- People aren't used to it and we shouldn't change user expectations unless the improvement is clear to everyone.

Agreed with Calinou (original PR author) on the following:
- We revert all icons to their old state...
- But we keep CameraTexture, as it represents a physical camera attached to your device. Calinou's camera type will now be the mascot of external cameras.
- We also do a small change to GizmoCamera, removing its insides so it's more see-through.
- We also keep the idea of CameraAttributesPhysical and CameraAttributesPractical. I swapped the asterisk colors because I noticed blue is often used for physics-related classes.
- We remove the now unused ClippedCamera.

### CODE REVIEW

**Review by Calinou — APPROVED** [review]

**Review by akien-mga — APPROVED** [review]
No strong opinion personally, so let's follow the user feedback :)

**Review by aaronfranke — APPROVED** [review]
The gizmo icon seems kinda weird to me, but overall I think this PR is an improvement.

I think it would make sense to have the old gizmo icon, and just... tell people it doesn't indicate direction. Maybe we need to make the wireframe bigger when you zoom out to avoid the problem? Anyway, I'm not sure how to best solve that problem, I just like the old icon better.

**Comment by akien-mga** [comment]
Thanks!

**Comment by MewPurPur** [comment]
Same as Aaron honestly

**Comment by JekSun97** [comment]
Oh, it's a pity, I already managed to fall in love with them

**Pull request merged**
