### PR TITLE
Fix assetlib crash on theme change

### PR DESCRIPTION
**Pull request by Chaosus**
A regression after https://github.com/godotengine/godot/pull/56832
I don't know how I missed a `// FIXME: The editor crashes if 'NOTICATION_THEME_CHANGED' is used.` above that, sorry about that...

### CODE REVIEW

**Comment by pycbouh** [comment]
From looking at code, I bet it crashed because we are adding an override to the current control itself, which triggers NOTIFICATION_THEME_CHANGED on that controls, hence an infinite loop. Proper solution would be to move that panel into a separate control node under `EditorAssetLibraryItemDownload` itself.

**Comment by akien-mga** [comment]
Might be worth killing two bugs with one stone and fixing that FIXME then?

**Comment by Chaosus** [comment]
@akien-mga Done

**Review by YuriSizov — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
