### PR TITLE
Changing the default blend importer material option to EXPORT

### LINKED ISSUE #62412: Godot 4.0 alpha 10 crash on extract materials from .blend file
### Godot version

Godot Engine v4.0.alpha10.official.4bbe7f0b9 and Godot Engine v4.0.alpha.calinou.c87f9fe4c

### System information

Kubuntu 22.04, NVIDIA GeForce GTX 1650, Intel® Core™ i5-9300H CPU @ 2.40GHz

### Issue description

When i try to extract materials from "godot web.blend", it always crash. the blender path used by godot version is 3.2
Backtrace:
```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.0.alpha.calinou (c87f9fe4cec15dcfa8ddb68e2de55d2bfab40d32)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f6de82fd520] (??:0)
[2] CowData<TreeItem::Cell>::_get_size() const (??:0)
[3] CowData<TreeItem::Cell>::size() const (??:0)
[4] Vector<TreeItem::Cell>::size() const (??:0)
[5] TreeItem::get_text(int) const (??:0)
[6] SceneImportSettings::_save_dir_callback(String const&) (??:0)
[7] void call_with_variant_args_helper<SceneImportSettings, String const&, 0ul>(SceneImportSettings*, void (SceneImportSettings::*)(String const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[8] void call_with_variant_args<SceneImportSettings, String const&>(SceneImportSettings*, void (SceneImportSettings::*)(String const&), Variant const**, int, Callable::CallError&) (??:0)
[9] CallableCustomMethodPointer<SceneImportSettings, String const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[10] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[11] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[12] Error Object::emit_signal<String>(StringName const&, String) (??:0)
[13] EditorFileDialog::_action_pressed() (??:0)
[14] void call_with_variant_args_helper<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[15] void call_with_variant_args<EditorFileDialog>(EditorFileDialog*, void (EditorFileDialog::*)(), Variant const**, int, Callable::CallError&) (??:0)
[16] CallableCustomMethodPointer<EditorFileDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[17] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[18] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[19] Error Object::emit_signal<>(StringName const&) (??:0)
[20] AcceptDialog::_ok_pressed() (??:0)
[21] void call_with_variant_args_helper<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, Callable::CallError&, IndexSequence<>) (??:0)
[22] void call_with_variant_args<AcceptDialog>(AcceptDialog*, void (AcceptDialog::*)(), Variant const**, int, Callable::CallError&) (??:0)
[23] CallableCustomMethodPointer<AcceptDialog>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[24] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[25] Object::emit_signalp(StringName const&, Variant const**, int) (??:0)
[26] Error Object::emit_signal<>(StringName const&) (??:0)
[27] BaseButton::_pressed() (??:0)
[28] BaseButton::on_action_event(Ref<InputEvent>) (??:0)
[29] BaseButton::gui_input(Ref<InputEvent> const&) (??:0)
[30] Control::_call_gui_input(Ref<InputEvent> const&) (??:0)
[31] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (??:0)
[32] Viewport::_gui_input_event(Ref<InputEvent>) (??:0)
[33] Viewport::push_input(Ref<InputEvent> const&, bool) (??:0)
[34] Window::_window_input(Ref<InputEvent> const&) (??:0)
[35] void call_with_variant_args_helper<Window, Ref<InputEvent> const&, 0ul>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, Callable::CallError&, IndexSequence<0ul>) (??:0)
[36] void call_with_variant_args<Window, Ref<InputEvent> const&>(Window*, void (Window::*)(Ref<InputEvent> const&), Variant const**, int, Callable::CallError&) (??:0)
[37] CallableCustomMethodPointer<Window, Ref<InputEvent> const&>::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[38] Callable::call(Variant const**, int, Variant&, Callable::CallError&) const (??:0)
[39] DisplayServerX11::_dispatch_input_event(Ref<InputEvent> const&) (??:0)
[40] DisplayServerX11::_dispatch_input_events(Ref<InputEvent> const&) (??:0)
[41] Input::_parse_input_event_impl(Ref<InputEvent> const&, bool) (??:0)
[42] Input::flush_buffered_events() (??:0)
[43] DisplayServerX11::process_events() (??:0)
[44] OS_LinuxBSD::run() (??:0)
[45] /home/ku/Desktop/godot(main+0x168) [0x5602769beacd] (??:0)
[46] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f6de82e4d90] (??:0)
[47] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f6de82e4e40] (??:0)
[48] /home/ku/Desktop/godot(_start+0x2a) [0x5602769be8aa] (??:0)
-- END OF BACKTRACE --
================================================================
```
full console output:
[console output.txt](https://github.com/godotengine/godot/files/8985543/console.output.txt)

### Steps to reproduce

Use ubuntu 22.04 or similar to reproduce. i did not tried on other linux distribution yet.
1. set blender path with blender 3.2
2. extract material from godot web.blend
3. save the material in "material" folder
4. and it crash

### Minimal reproduction project

[godot minimal reproduction project.zip](https://github.com/godotengine/godot/files/8985544/godot.minimal.reproduction.project.zip)

### PR DESCRIPTION
**Pull request by n0tank3sh**
Fixes #62412

### CODE REVIEW

**Review by fire — APPROVED** [review]

**Comment by akien-mga** [comment]
Doesn't that defeat the purpose of having a `blender/materials/export_materials` option?

**Comment by MightiestGoat** [comment]
> Doesn't that defeat the purpose of having a `blender/materials/export_materials` option?

**Comment by MightiestGoat** [comment]
14

**Comment by MightiestGoat** [comment]
@akien-mga  The editor imports the files with the default settings so there will be no material export in the blend file while materials are exported by default during fbx to gltf conversion.

**Comment by akien-mga** [comment]
Superseded by #59834.

**Pull request closed without merging**
