### PR TITLE
Fix missing shader params in headless export 

### LINKED ISSUE #66842: Shader parameters specified in the inspector are not included when exporting a project in headless mode
### Godot version

4.0.beta2.official.f8745f2f7

### System information

Void linux

### Issue description

When exporting a project using `--headless --export-pack`, any shader parameters/uniforms specified in the inspector are not included in the exported project. All shader parameters are reverted to their default values (or null).

### Steps to reproduce

Project setup:
1. Create a cube mesh.
2. Add a shader material to the cube with the following simple shader:
```
shader_type spatial;
render_mode unshaded;

uniform vec4 color: source_color = vec4(0.0, 1.0, 0.0, 0.0); // Green

void fragment() {
        ALBEDO = color.rgb;
}
```
3. In the inspector, set the 'color' shader parameter/uniform to be a red color.
4. When running the project from the editor, the cube is now red.

Export without `--headless` option:
```
rm -rf .godot
./Godot_v4.0-beta2_linux.x86_64 --editor --export-pack Linux/X11 export.zip
./Godot_v4.0-beta2_linux.x86_64 --main-pack export.zip
# Cube is red (correct behavior)
```

Export with `--headless` option:
```
rm -rf .godot
./Godot_v4.0-beta2_linux.x86_64 --editor --headless --export-pack Linux/X11 export_headless.zip
./Godot_v4.0-beta2_linux.x86_64 --main-pack export_headless.zip
# Cube is green (incorrect behavior)
```

The behavior can be reproduced on Godot 4.0 alpha 16 through Godot 4.0 beta 2.

### Minimal reproduction project

[ShaderParameterHeadless.zip](https://github.com/godotengine/godot/files/9700232/ShaderParameterHeadless.zip)

### PR DESCRIPTION
**Pull request by cgsdev0**
Fixes https://github.com/godotengine/godot/issues/66842

> When exporting a project using --headless --export-pack, any shader parameters/uniforms specified in the inspector are not included in the exported project. All shader parameters are reverted to their default values (or null).

I'm not confident this change is 100% correct; I did some testing with my project where I first observed the behavior, and the change did resolve the issue.

This is the function we used to call previously:
https://github.com/godotengine/godot/blob/a7276f1ce0c2911216a2c4718efddab98ddffd8f/scene/resources/shader.cpp#L117-L141

I don't really understand what this group logic is doing, and I think my change potentially loses that information. Definitely open to feedback, this is my first time exploring the Godot codebase 😄 

(This change isn't needed for 3.x)

### CODE REVIEW

**Comment by cridenour** [comment]
Applying this on top of 4.0.3 solved my shader params missing from headless exports. I am going to do some wider testing to see if there are any other material side effects from this change. 

Thank you @cgsdev0

**Comment by bitsawer** [comment]
This PR kind of works, but it will only export uniforms that previously have their values set and saved in the inspector ui. After applying this PR, adding new uniforms in the shader code no longer appear in the inspector UI, because `shader->get_shader_uniform_list()` is responsible for fetching these new (and old) uniforms from the RenderingServer. They are not exported, either.

The --headless export problem is a pretty tricky as in the headless mode many Godot servers are not initialized and instead use dummy versions. For example to fix some mesh --headless export issues people have been fixed by patching the dummy MeshStorage to keep enough mesh data so that export works. Same kind of issues plage shader uniforms, multimesh etc.

I feel it would required some major refactoring to make --headless export reliable, currently it's pretty much a combination of ad-hoc hacks to fix any errors that people encounter when exporting their specific projects using --headless.

**Comment by cridenour** [comment]
Thanks for the additional testing @bitsawer - I'll probably roll this back in our build and just avoid headless for the time being.

**Comment by cgsdev0** [comment]
> adding new uniforms in the shader code no longer appear in the inspector UI, because `shader->get_shader_uniform_list()` is responsible for fetching these new (and old) uniforms from the RenderingServer. They are not exported, either.

thanks for this comment - I feel like this is the piece that I was lacking understanding of

**Comment by QbieShay** [comment]
Hey, what's the state of this?

**Comment by cgsdev0** [comment]
in the spirit of the existing 'ad-hoc hacks', we _could_ gate this change behind a check if we're in headless mode. It's not really a long-term solution, but it should at least fix this issue without regressions in the editor.

I've pushed an updated commit with this change.

**Comment by QbieShay** [comment]
I think considering the criticality of this issue, we can be okay with a hack for 4.1.1 and then find better solutions that require significant refactors later. Losing uniform on export is pretty critical imo.

Reminder for people reading, clay's opinion and bitsawer's one definitely override mine, it's their expertise way more than mine, but from the point of view of a professional, i think this is a really critical issue that if it can be addressed quickly, even with a hack, it's better than being unable to export the game on CI until a refactor (which takes way more effort and time) is done.

**Comment by cgsdev0** [comment]
@bitsawer that change seems reasonable to me. Let me know if you think there's a better central place to move the `is_headless_exporting` function to; I wasn't really sure, so I just left it local for now

I'll do some further testing of this change once the CI builds are done

**Comment by RevoluPowered** [comment]
could be a little cleaner with this:
```
		const bool headless = DisplayServer::get_singleton()->get_name() == "headless";
		if (headless) {
			// we have to use the cached parameters as we can't query it from the display server
			for (const KeyValue<StringName, Variant> &P : param_cache) {
				list.push_back(PropertyInfo(P.value.get_type(), P.key));
			}
		} else {
			shader->get_shader_uniform_list(&list, true);
		}
```

**Comment by tcoxon** [comment]
The proposed fix doesn't seem to preserve texture parameters on materials. MRP: [66842.zip](https://github.com/godotengine/godot/files/12624096/66842.zip)

It seems like more info might need to be added to the PropertyInfo to preserve them, but I couldn't figure out what exactly.

**Comment by clayjohn** [comment]
Just an update on this PR. I think we should aim to solve it properly. The ideal solution is that we store enough data on the DummyRenderingServer to allow the call to `get_shader_parameter_list()` to return the correct information. The problem here is that shaders/materials rely on passing data to the RenderingServer while loading, and then retrieving that data back before saving. The Dummy server currently just tosses out the data it receives on load. So when the exporter retrieves the data back to save it, it gets default values instead.

**Comment by clayjohn** [comment]
> The proposed fix doesn't seem to preserve texture parameters on materials. MRP: [66842.zip](https://github.com/godotengine/godot/files/12624096/66842.zip)
> 
> It seems like more info might need to be added to the PropertyInfo to preserve them, but I couldn't figure out what exactly.

Fixed this in https://github.com/godotengine/godot/pull/87392

_Headless export from 4.2.1_
Screenshot from 2024-01-19 19-24-10

_Headless export from #87392 (I never opened the project in the editor)_
Screenshot from 2024-01-19 19-25-07

**Comment by cgsdev0** [comment]
@clayjohn i dont think i have bandwidth for this any time soon

feel free to take over the branch and/or close the PR

**Comment by clayjohn** [comment]
> @clayjohn i dont think i have bandwidth for this any time soon
> 
> feel free to take over the branch and/or close the PR

No problem! Thank you very much for your initial work and ensuring that this got the attention it needed. 

Superseded by https://github.com/godotengine/godot/pull/87392

**Pull request closed without merging**
