### PR TITLE
Use interleaved gradient noise for distance fade

### PR DESCRIPTION
**Pull request by Calinou**
`master` version of https://github.com/godotengine/godot/pull/64052. Follow-up to https://github.com/godotengine/godot/pull/50294.

This provides better visuals and performance compared to the previous ordered dither. On my GTX 1080 in a 4K editor, I get 230 FPS in locations where I would get 210 FPS previously.

The new shader performs better since it has much less instructions and branching to do.

I also tested this PR on the `3.x` branch together with https://github.com/godotengine/godot/pull/50294 and it works fine there, both in GLES3 and [GLES2](https://github.com/godotengine/godot/pull/50295).

## Preview

***Note:** These images should be viewed on a desktop device at 1:1 resolution by clicking them. Otherwise, they will not look as expected due to the nature of dithering.*

### Pixel Alpha (for comparison)

Pixel Alpha

### Pixel Dither (new)

Pixel Dither

### CODE REVIEW

**Comment by reduz** [comment]
This looks great, but give me a bit more time before merging as I may need to do more changes in shadow mapping when I get some clues on the remaining bugs.

**Review by reduz — APPROVED** [review]

**Comment by akien-mga** [comment]
Would be good to rebase to be safe.

**Comment by Calinou** [comment]
Rebased and tested again, it works as expected.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
