### PR TITLE
Add option to not expand tree on node select

### LINKED ISSUE #3095: Add an option to prevent the auto-expansion in the Scene Tree dock when selecting nodes in the scene
### Describe the project you are working on

An indie project in which the levels require many scenes of enemies, items etc ... and the tree becomes a nuisance.

### Describe the problem or limitation you are having in your project

When a node belonging to a subtree is selected in the main tree, the subtree is automatically expanded.
I suggest adding an option so that this only happens if the user does it manually, this could help to keep the tree somehow better organized, it also helps to move faster through the tree.
Notice the gif, when I select a node that is inside a collapsed node, the collapsed node expands automatically.
I suggest an option to avoid this and have the node only expand if the user expands it manually.
https://imgur.com/OAwqGZp

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The addition of an option in the "Editor configuration" section that allows the option to avoid the auto-expansion of the nodes in the tree.

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

The editor will check the status of the option before auto-expanding.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No

### Is there a reason why this should be core and not an add-on in the asset library?

No idea

### PR DESCRIPTION
**Pull request by KoBeWi**
Closes https://github.com/godotengine/godot-proposals/issues/3095

Added as button in the toolbar, next to list select:
image

Not sure about the button placement. Right now it's both in 2D and 3D editor and they are synced. But the worst thing is that there is now mutual dependency between SceneTreeEditor and CanvasItem/Node3DEditor. If anyone has a better idea where to put it (perfectly somewhere within scene tree dock), suggestions welcome.

Also seems like expand to selected is broken on master, so this can't be fully tested lol

### CODE REVIEW

**Comment by EricEzaM** [comment]
I would probably put it somewhere here, but understand that it has to do with node selections in the 2d/3d editors, and not just the scene tree. But I would think it could fit better here (and also the functionality wouldn't be duplicated between the two editors).

image

Additionally, @pycbouh pointed out the other day in Rocket Chat that the toolbar can already get very bloated, and needs some reorganising (as below). So I would hesitate before adding to it further. Although putting it in the scene tree dock may give similar issues re: button bloat.

image

**Comment by KoBeWi** [comment]
My idea was to put it in place of the script button when no node is selected. There is free space in there:
jBD92bTJo2
But having a button conditionally hidden under another button is not very intuitive, so not sure.

**Comment by groud** [comment]
I think a button is too much for this. It's behavior seems quite a corner case (I do not feel like it was a bother to a lot of users), so I'd rather move that to a checkbox somewhere in a context menu.

As @EricEzaM suggested, I agree this should be moved to the scene tree dock, but I think I would probably add a three-dot menu there or something like that. 

Maybe it could simply be added to a right-click menu when you right-click anywhere in the dock. We already have such a popup with generic options in the FileSystem dock, where, if you right-click anywhere, you can still create scene/resource/etc... in the root folder. I guess other options could be added there too, like "expand all" or add node (that would be added to the root).

**Comment by KoBeWi** [comment]
Ok added an entry in the context menu
image

**Comment by YeldhamDev** [comment]
Shouldn't it be bellow "Expand/Collapse All"? Seems like it would be a better fit. Maybe that would also justify adding a separator bellow "Instantiate Child Scene" as well.

**Comment by KoBeWi** [comment]
The problem is that "Expand/Collapse All" only appears when only one node is selected. The sub-section with "Open Documentation" is the only one that doesn't change depending on context.

**Comment by YeldhamDev** [comment]
> The problem is that "Expand/Collapse All" only appears when only one node is selected.

I don't see why this would interfere. Just don't put it inside the same logic that makes that option disappear.

**Comment by KoBeWi** [comment]
Ok changed
image
image

**Review by EricEzaM — APPROVED** [review]

**Comment by akien-mga** [comment]
So IIUC it's in the contextual menu for each node, but it applies to the whole scene tree? That seems a bit non-intuitive to me.

I'm not so sure about the feature itself, if that's wanted for some projects, wouldn't it be simpler to just make it a project or editor setting? Will users really have to toggle it on and off often prior to selecting nodes to avoid messing their carefully folded scene tree?

It seems weird to me to have a workflow that would be like this:
- Open scene A, work normally, selecting nodes will focus them in the scene tree, including auto-expansion if they were in a folded tree.
- Move to scene B, remember that this scene has lots of props and that you don't want to change the scene tree, so right click a random node to toggle the option.
- Later on you actually want to access a node in the scene tree so you need to remember to untoggle the option, or you have to search for it manually.

I would suggest the following instead:
- Add an editor setting that disables the behave to auto expand the scene tree to focus selected nodes.
- Add a keyboard modifier that can force tree expansion on demand, for users who have this option toggled off (e.g. Ctrl+Click or Shift+Click, provided they're not used already).

**Comment by KoBeWi** [comment]
I already added the editor setting, the checkbox is just for easy toggling. Ctrl + click could work too. Or even I could remove the setting and just make Ctrl+click not auto-expand. But then it's not very discoverable.

As for the workflow, the option would be used in level scenes (based on the proposal) and not used on e.g. UI scenes or object scenes. It's common to switch between them a lot, so having this option easily toggleable is useful.

The reason why you have to click a node is that we don't have a generic context menu in the scene tree. You have to click a node to open the menu.

**Comment by groud** [comment]
> The reason why you have to click a node is that we don't have a generic context menu in the scene tree. You have to click a node to open the menu.

You could probably create a popup when you right-click outside of a node in the scene-tree. The Tree node has a `"empty_rmb"` signal for that.

**Comment by akien-mga** [comment]
I think it would be better to add a proper "options" icon menu to the Scene Tree dock with the actions which affect the whole scene tree and not a specific node, like the Inspector has.

It takes space, but we're bound to have more such actions we want to expose in the future and that's the proper way to have them IMO.

The existing "Expand/Collapse All" action should go in it too, as it's not a node-specific action.

**Comment by KoBeWi** [comment]
> You could probably create a popup when you right-click outside of a node in the scene-tree.

This only works in the area below all nodes. On big tree, you have to scroll all the way down and click this tiny space
image
A button sounds like the best option. The 3-dots one is rather thin, so should be ok.

**Comment by groud** [comment]
> This only works in the area below all nodes. On big tree, you have to scroll all the way down and click this tiny space
image

Yeah of course you would still have to add the option to the menu when you click on a node. So it would have been in both menus. But anyway, a 3-dots menu for global options is fine to me too.

**Comment by KoBeWi** [comment]
Ok added the menu
image
Although the button has actually normal size, so there is very little space now :/ Maybe the instance scene button could be moved into the menu? There are multiple ways to instance a scene and that button *might* be the least used one.

**Comment by Torguen** [comment]
Hello, in which version will this be added?
I am using 3.4 RC1 and the option does not appear here.

**Comment by akien-mga** [comment]
@Torguen This PR hasn't been merged yet, so that's normal. It's not present in any version.

**Comment by pycbouh** [comment]
There is also no 3.4 RC 1 yet. You probably mean 3.3.4 RC 1, which was published the other day.

**Comment by Torguen** [comment]
Ok, I'll be on the lookout to see when they add it.
Yes, I was wrong, I am with 3.3.4 RC1.
Ok, thanks.

**Comment by akien-mga** [comment]
Thanks!

**Comment by KoBeWi** [comment]
I just realized that moving `Expand/Collapse All` was a mistake. It can also be used on a selected branch (despite the name suggesting otherwise), that's why it was in the RMB menu.

**Comment by KoBeWi** [comment]
Please open a [proposal](https://github.com/godotengine/godot-proposals).

**Pull request merged**
