### PR TITLE
[4.3] XRNode - fix visibility issue

### PR DESCRIPTION
**Pull request by BastiaanOlij**
This is an extract of a fix from #95153 for Godot 4.3

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by dsnopek** [comment]
There's two other little changes from #95153, that I'm not sure if we need here as well.

In `openxr_hand_tracking_extension.cpp`:

- The `godot_tracker->invalidate_pose("default");` [here](https://github.com/godotengine/godot/pull/95153/files#diff-9f96beb327a3902454ef8397b5c38cc515f28ca1ad09778be6149c93b573f0f1R242), and
- Moving `godot_tracker->invalidate_pose("default");` from [here](https://github.com/godotengine/godot/pull/95153/files#diff-9f96beb327a3902454ef8397b5c38cc515f28ca1ad09778be6149c93b573f0f1L238) to [here](https://github.com/godotengine/godot/pull/95153/files#diff-9f96beb327a3902454ef8397b5c38cc515f28ca1ad09778be6149c93b573f0f1R318)

I think those both could potentially have an effect on whether or not the node thinks it has data or not, in a couple of edge cases.

**Comment by BastiaanOlij** [comment]
Thanks @dsnopek , 

Made the changes you suggested, indeed will help. I also fixed the issue with the wrong bit being checked.

**Review by dsnopek — APPROVED** [review]
Looks great to me!

I just tested on Quest 3, and the visibility checks seem to be working correctly.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
