### PR TITLE
[Linux/X11] Add some missing keycodes/scancodes.

### PR DESCRIPTION
**Pull request by bruvzg**
See https://github.com/godotengine/godot/issues/74578 (I do not have any keyboard with `KP_EQUAL` to test).

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
@RobTheFiveNine Could you test and confirm if that fixes the issue for you? You can test the PR by building it from source, or downloading the artifacts from the CI (see https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html).

**Comment by akien-mga** [comment]
Thanks!

**Comment by RobTheFiveNine** [comment]
> @RobTheFiveNine Could you test and confirm if that fixes the issue for you? You can test the PR by building it from source, or downloading the artifacts from the CI (see https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html).

Sure! I can't do it right now, but I should be able to in around 7 or 8 hours time. I'll let you know the results 👍🏼

**Comment by RobTheFiveNine** [comment]
I gave it a test using one of the builds produced by GitHub and tried compiling manually from the branch @ https://github.com/bruvzg/godot/tree/x11_kc but didn't seem to work on either 😢 

I tried running `xev` to check the events that are fired when using the two different keys (i.e. the `+/=` key and the numpad `=` key), and interestingly the x11 events for the numpad equals key (the second pair of events) make reference to `KP_Equal`, which seems to be the keycode references in the changes that were made - so not 100% sure why it's not working:

```
KeyPress event, serial 37, synthetic NO, window 0x2800001,
    root 0x1d1, subw 0x0, time 37109758, (627,824), root:(3287,961),
    state 0x10, keycode 21 (keysym 0x3d, equal), same_screen YES,
    XLookupString gives 1 bytes: (3d) "="
    XmbLookupString gives 1 bytes: (3d) "="
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2800001,
    root 0x1d1, subw 0x0, time 37109846, (627,824), root:(3287,961),
    state 0x10, keycode 21 (keysym 0x3d, equal), same_screen YES,
    XLookupString gives 1 bytes: (3d) "="
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x2800001,
    root 0x1d1, subw 0x0, time 37110814, (627,824), root:(3287,961),
    state 0x10, keycode 125 (keysym 0xffbd, KP_Equal), same_screen YES,
    XLookupString gives 1 bytes: (3d) "="
    XmbLookupString gives 1 bytes: (3d) "="
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x2800001,
    root 0x1d1, subw 0x0, time 37110870, (627,824), root:(3287,961),
    state 0x10, keycode 125 (keysym 0xffbd, KP_Equal), same_screen YES,
    XLookupString gives 1 bytes: (3d) "="
    XFilterEvent returns: False
```

If you can think of any more information that would be useful, ping me and I'll try to help 😃

**Comment by YuriSizov** [comment]
Cherry-picked for 4.0.1. While the reported problem may not be resolved yet, the improvements themselves seem good to have.

**Pull request merged**
