### PR TITLE
Betsy: Add signed mode for BC6

### PR DESCRIPTION
**Pull request by BlueCube3310**
Implements a signed mode for Betsy. Currently, it has some quality issues and therefore it's not meant for lightmap compression. This is done to improve compatibility with CVTT, which although supports signed compression, exhibits significant artifacting.

| CVTT | Betsy |
|-------|------|
| cvtt | betsy |

Testing image: [testout.zip](https://github.com/user-attachments/files/16824434/testout.zip)

### CODE REVIEW

**Comment by jcostello** [comment]
Will be ready for lightmaps in the future?

**Comment by BlueCube3310** [comment]
There is no need for that, since #96114 already allows compressing directional lightmaps in an unsigned format. This one is mainly done to minimize the differences between betsy and cvtt.

**Review by clayjohn — APPROVED** [review]
Looks good to me, but would be nice to have @darksylinc take a look as well before merging

**Comment by darksylinc** [comment]
Assuming the changes to support signed formats is error-free (big if)

The reason for the artifacts is that `EncodeP2Pattern` (i.e. the "Quality") preset heavily relies on MSLE, i.e. the return value of `CalcMSLE()`, to determine who is the best candidate.

However a simple test shows `CalcMSLE()` that CalcMSLE() is broken for negative values:

```cpp
#include <cmath>
#include <stdio.h>

float CalcMSLE( float a, float b )
{
	float err = log2( ( b + 1.0f ) / ( a + 1.0f ) );
	err = err * err;
	return err;
}

int main()
{
	printf( "%f\n", CalcMSLE( 0.0f, 4.0f ) );
	printf( "%f\n", CalcMSLE( 4.0f, 0.0f ) );
	printf( "%f\n", CalcMSLE( 0.0f, 5.0f ) );
	printf( "%f\n", CalcMSLE( 0.0f, 0.5f ) );
	printf( "%f\n", CalcMSLE( 0.0f, -1.0f ) );
	printf( "%f\n", CalcMSLE( 2.0f, -2.0f ) );
	return 0;
}
```

```
5.391350
5.391350
6.682032
0.342181
inf -> OOOPS!!!!
nan -> OOOPS!!!
```

Thus the any random pattern may be chosen instead of the most fit one.

**Comment by darksylinc** [comment]
We need to handle negative values in CalcMSLE

Probably the question is "how" but that makes me want to cry.

MSLE is being used because it uses log space.
It uses log space because when doing HDR encoding, a difference of 1.0 - 65.0 is not too different from 2.0 - 65.0.
But a difference from 0.5 - 0.9 vs 0.4 - 0.9 is a huge one in LDR space.

So MSLE works well on both.

And we have the same problem when going -1.0 vs 1.0 vs -2.0 vs 2.0.
There's also the question what is "not very important" in the context of negative values?

MSLE was chosen because on HDR (or LDR) we are measuring error difference in photo luminosity. But negative values? What sort of data are you encoding?

I suspect a CalcMSLE that accounts for negative values would be somewhere of the following:

```cpp
// Note: I don't use sign() because of the case sign() returns -1, 0, & 1
bool isNegative( float a )
{
	return a < 0.0f;
}

float CalcSignlessMSLE( float a, float b )
{
	float err = log2( ( b + 1.0f ) / ( a + 1.0f ) );
	err = err * err;
	return err;
}

float CrossCalcMSLE( float a, float b )
{
	float result = 0;
	result += CalcSignlessMSLE( 0, abs( a ) );
	result += CalcSignlessMSLE( 0, abs( b ) );
	return result;
}

float CalcMSLE( float a, float b )
{
	if( isNegative( a ) != isNegative( b ) )
		return CrossCalcMSLE( a, b );

	return CalcSignlessMSLE( abs( a ), abs( b ) );
}
```

For:

```cpp
int main()
{
	printf( "%f\n", CalcMSLE( 0.0f, 4.0f ) );
	printf( "%f\n", CalcMSLE( 4.0f, 0.0f ) );
	printf( "%f\n", CalcMSLE( 0.0f, 100.0f ) );
	printf( "%f\n", CalcMSLE( 0.0f, 0.5f ) );
	printf( "%f\n", CalcMSLE( -2.0f, 2.0f ) );
	printf( "%f\n", CalcMSLE( -3.0f, -2.0f ) );
	return 0;
}
```

I get:

```cpp
5.391350
5.391350
44.331783
0.000000
5.024212
0.172256
```

Is this the best way? I don't know, but it's worth the shot.

**Comment by clayjohn** [comment]
I tested out the CalcMSLE variant and it doesn't appear to quite work. I had to change the code to:
```
bool isNegative(float3 a) {
	return any(lessThan(a, float3(0.0)));
}

float CalcSignlessMSLE(float3 a, float3 b) {
	float3 err = log2((b + 1.0f) / (a + 1.0f));
	err = err * err;
	return err.x + err.y + err.z;
}

float CrossCalcMSLE(float3 a, float3 b) {
	float result = 0;
	result += CalcSignlessMSLE(float3(0.0), abs(a));
	result += CalcSignlessMSLE(float3(0.0), abs(b));
	return result;
}

float CalcMSLE(float3 a, float3 b) {
	if (isNegative(a) != isNegative(b))
		return CrossCalcMSLE(a, b);

	return CalcSignlessMSLE(abs(a), abs(b));
}

```

The result is slightly worse than the original MSLE calculation

_With this PR_
Screenshot from 2024-09-01 12-25-49
_With new MSLE calculation from darksylinc_
Screenshot from 2024-09-01 12-25-05

**Comment by clayjohn** [comment]
It could also be worth looking at the improvements to [GPURealTimeBC6H](https://github.com/knarkowicz/GPURealTimeBC6H) that happened after Betsy was created

https://github.com/knarkowicz/GPURealTimeBC6H/commit/8b4d12037e9dd34f54f5e8a34ac50f4eb3ffbf92
https://github.com/knarkowicz/GPURealTimeBC6H/commit/e21d4ef94c6c4c074014ac2cabe29e1afb3d5759
https://github.com/knarkowicz/GPURealTimeBC6H/commit/b75d698617c7bae84db5930272515adf4f9be039
https://github.com/knarkowicz/GPURealTimeBC6H/commit/025f339f3062f36028dc1df0189f394fba92ae4f

These seem to both increase the speed and quality

**Comment by darksylinc** [comment]
> I had to change the code to:

Oh I see the issue. The way I wrote the code was NOT meant to call `CrossCalcMSLE()` for both values being positive.

Basically:

```cpp
a = vec3( -1, 2, 1 );
b = vec3( 2, 3, 4 );

// Your version will do this:
CrossCalcMSLE( -1, 2 ); // .x
CrossCalcMSLE( 2, 3 ); // .y
CrossCalcMSLE( 1, 4 ); // .z

// While it should be doing this:
CrossCalcMSLE( -1, 2 ); // .x
CalcSignlessMSLE( 2, 3 ); // .y
CalcSignlessMSLE( 1, 4 ); // .z
```

It must be done per component.

**Comment by clayjohn** [comment]
I see, with that change it looks much better, but the quality ends up being exactly the same as without the change

_Improved MSLE_
image

_This PR_
Screenshot from 2024-09-01 12-25-49

```
bool isNegative(float a) {
	return a < 0.0f;
}

float CalcSignlessMSLE(float a, float b) {
	float err = log2((b + 1.0f) / (a + 1.0f));
	err = err * err;
	return err;
}

float CrossCalcMSLE(float a, float b) {
	float result = 0.0f;
	result += CalcSignlessMSLE(0.0f, abs(a));
	result += CalcSignlessMSLE(0.0f, abs(b));
	return result;
}

float CalcMSLE(float3 a, float3 b) {
	float result = 0.0f;
	if (isNegative(a.x) != isNegative(b.x)) {
		result += CrossCalcMSLE(a.x, b.x);
	} else {
		result += CalcSignlessMSLE(abs(a.x), abs(b.x));
	}
	if (isNegative(a.y) != isNegative(b.y)) {
		result += CrossCalcMSLE(a.y, b.y);
	} else {
		result += CalcSignlessMSLE(abs(a.y), abs(b.y));
	}
	if (isNegative(a.z) != isNegative(b.z)) {
		result += CrossCalcMSLE(a.z, b.z);
	} else {
		result += CalcSignlessMSLE(abs(a.z), abs(b.z));
	}

	return result;
}
```

**Comment by BlueCube3310** [comment]
Could you try multiplying the compressed image by -1 in a shader material? The negative data typically suffers from more artifacting

**Comment by clayjohn** [comment]
> Could you try multiplying the compressed image by -1 in a shader material? The negative data typically suffers from more artifacting

I'm not in front of a computer now. But I did that previously and I couldn't tell the difference so I opted not to post the screenshots

**Comment by clayjohn** [comment]
Also, to be clear, I am happy to merge this PR without the quality being perfect. It looks like most compressors really struggle to get good quality for signed BC6, so I doubt it is something that needs to be perfect. The current quality is already quite good in comparison to CVTT

**Comment by BlueCube3310** [comment]
This could also be an issue with the indices, I will try to look into it later today

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
