### PR TITLE
Added ERR_FAIL checks for `Animation::track_set_key_value` and `AnimationNodeStateMachine::remove_node`

### LINKED ISSUE #29869: Editor crash in Animation::track_set_key_value
**Godot version:**
3.2.dev.custom_build. 0f543ba99

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7fb3f147cf60] (??:0)
[2] VectorWriteProxy<Animation::TKey<StringName> >::operator[](int) (/home/rafal/Pulpit/godot/./core/vector.h:49 (discriminator 7))
[3] Animation::track_set_key_value(int, int, Variant const&) (/home/rafal/Pulpit/godot/scene/resources/animation.cpp:1487)
[4] MethodBind3<int, int, Variant const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:2303 (discriminator 26))
[5] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[6] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[7] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[8] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[9] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[10] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[11] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[12] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[13] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[14] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[15] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[16] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1920)
[17] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[18] /usr/bin/godot(main+0xdf) [0x13969a1] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[19] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fb3f145fb6b] (??:0)
[20] /usr/bin/godot(_start+0x2a) [0x139680a] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 68a65acce08662733304867b31412deac4ce5ed8
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/68a65acce08662733304867b31412deac4ce5ed8.zip

### LINKED ISSUE #29879: Editor crash in AnimationNodeStateMachine::remove_node
**Godot version:**
3.2.dev.custom_build. 0f543ba99

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
```
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x43f60) [0x7f1bca1d7f60] (??:0)
[2] HashMap<StringName, Object::Signal, HashMapHasherDefault, HashMapComparatorDefault<StringName>, (unsigned char)3, (unsigned char)8>::getptr(StringName const&) (/home/rafal/Pulpit/godot/./core/hash_map.h:318)
[3] Object::_disconnect(StringName const&, Object*, StringName const&, bool) (/home/rafal/Pulpit/godot/core/object.cpp:1542 (discriminator 2))
[4] Object::disconnect(StringName const&, Object*, StringName const&) (/home/rafal/Pulpit/godot/core/object.cpp:1538)
[5] AnimationNodeStateMachine::remove_node(StringName const&) (/home/rafal/Pulpit/godot/scene/animation/animation_node_state_machine.cpp:602 (discriminator 5))
[6] MethodBind1<StringName const&>::call(Object*, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/./core/method_bind.gen.inc:775 (discriminator 12))
[7] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/home/rafal/Pulpit/godot/core/object.cpp:940 (discriminator 1))
[8] Variant::call_ptr(StringName const&, Variant const**, int, Variant*, Variant::CallError&) (/home/rafal/Pulpit/godot/core/variant_call.cpp:1071 (discriminator 1))
[9] GDScriptFunction::call(GDScriptInstance*, Variant const**, int, Variant::CallError&, GDScriptFunction::CallState*) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript_function.cpp:1078)
[10] GDScriptInstance::call_multilevel(StringName const&, Variant const**, int) (/home/rafal/Pulpit/godot/modules/gdscript/gdscript.cpp:1192)
[11] Node::_notification(int) (/home/rafal/Pulpit/godot/scene/main/node.cpp:58)
[12] Node::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/main/node.h:46 (discriminator 14))
[13] CanvasItem::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/canvas_item.h:166 (discriminator 3))
[14] Node2D::_notificationv(int, bool) (/home/rafal/Pulpit/godot/./scene/2d/node_2d.h:38 (discriminator 3))
[15] Object::notification(int, bool) (/home/rafal/Pulpit/godot/core/object.cpp:952)
[16] SceneTree::_notify_group_pause(StringName const&, int) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:975)
[17] SceneTree::idle(float) (/home/rafal/Pulpit/godot/scene/main/scene_tree.cpp:522 (discriminator 3))
[18] Main::iteration() (/home/rafal/Pulpit/godot/main/main.cpp:1920)
[19] OS_X11::run() (/home/rafal/Pulpit/godot/platform/x11/os_x11.cpp:3163)
[20] /usr/bin/godot(main+0xdf) [0x138a9a1] (/home/rafal/Pulpit/godot/platform/x11/godot_x11.cpp:56)
[21] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f1bca1bab6b] (??:0)
[22] /usr/bin/godot(_start+0x2a) [0x138a80a] (??:?)
```

**Steps to reproduce:**
1. Run minimal project and wait

**Minimal reproduction project:**
https://github.com/qarmin/The-worst-Godot-test-project/
commit 79fc7368fc0e5cbb144f5869a0122bb74274a2f8
ZIP - https://github.com/qarmin/The-worst-Godot-test-project/archive/79fc7368fc0e5cbb144f5869a0122bb74274a2f8.zip

### PR DESCRIPTION
**Pull request by Dentrax**
In addition to, I think it fixes #29869 and fixes #29879

### CODE REVIEW

**Comment by akien-mga** [comment]
Seems good, could you squash the commits together? See [PR workflow](http://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#mastering-the-pr-workflow-the-rebase).

**Comment by Dentrax** [comment]
@akien-mga I squashed them. But still, i couldn't see the _trailing tab_ on the Terminal. Is it still there? :)

**Comment by akien-mga** [comment]
> I squashed them. But still, i couldn't see the trailing tab on the Terminal. Is it still there? :)

It's good, the trailing tab does not appear in the diff.

There are still 4 commits though, squashing them means that all of them should be merged together in one single commit.

**Comment by Dentrax** [comment]
@akien-mga Fixed, i guess. :)

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
