### PR TITLE
C#: Optimize InvokeGodotClassMethod source generation to check for argument count first

### PR DESCRIPTION
**Pull request by roookeee**
The following code is currently generated for `InvokeGodotClassMethod`:
```C#
  protected override bool InvokeGodotClassMethod(in godot_string_name method, NativeVariantPtrArgs args, out godot_variant ret)
  {
      if (method == MethodName._Ready && args.Count == 0) {
          _Ready();
          ret = default;
          return true;
      }
      if (method == MethodName._Process && args.Count == 1) {
          _Process(global::Godot.NativeInterop.VariantUtils.ConvertTo<double>(args[0]));
          ret = default;
          return true;
      }
      return base.InvokeGodotClassMethod(method, args, out ret);
  }
```
Comparing `args.Count` first is trivially more performant in multiple scenarios:

1. a simple `int` comparison is faster than `StringName.Equals` as it does multiple null checks and conversions via `CustomUnsafe` and `Unsafe`)
2. All but the first `if`-statements require comparatively expensive string compares  (compared to an `int` compare) for functions which have an argument count mismatch, this especially "hurts" `_Process` here

**TODOs**

- [x] check whether the .cpp base module generation [here](https://github.com/godotengine/godot/blob/f5f7d11ac47244e4cc02cd7336ba86e0ed272dc3/modules/mono/editor/bindings_generator.cpp#L1633) should be adapted as well
- [ ] perform benchmarks if possible, `StringName.Equals` could be as performant if everything is inlined properly (it's at least one more dereference as `StringName` is an object)

**Note**
I am pretty inexperienced in regards to the Godot codebase and have not setup a build environment for this. I am grateful for any pointers to existing benchmarks or test cases I probably overlooked.
I also need feedback if the mentioned cpp file should be adapted as well.

### CODE REVIEW

**Comment by akien-mga** [comment]
For the record, your commit seems to be not linked to your GitHub account. See: [Why are my commits linked to the wrong user?](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more info.

**Comment by roookeee** [comment]
**Big warning: The below test is not representative of a real benchmark, I couldn't get it to work more properly though**

I whipped up the following Benchmark.NET:
```c#
public class TestCase {
    public new class MethodName : Node3D.MethodName {
        public new static readonly StringName _Ready = "_Ready";
        public new static readonly StringName _Process = "_Process";
    }

    public bool InvokeGodotClassMethodOld(in godot_string_name method, NativeVariantPtrArgs args, out godot_variant ret) {
        if (method == MethodName._Ready && args.Count == 0) {
            ret = default;
            return true;
        }

        if (method == MethodName._Process && args.Count == 1) {
            ret = default;
            return true;
        }

        ret = default;
        return false;
    }
    
    public bool InvokeGodotClassMethodNew(in godot_string_name method, NativeVariantPtrArgs args, out godot_variant ret) {
        if (args.Count == 0 && method == MethodName._Ready) {
            ret = default;
            return true;
        }

        if (args.Count == 1 && method == MethodName._Process) {
            ret = default;
            return true;
        }

        ret = default;
        return false;
    }
}

public class TestCases {
    private static Random random = new Random(42);
    private TestCase _testCase = new TestCase();

    [Benchmark]
    public bool New() {
        var _args = new NativeVariantPtrArgs();
        var str = new godot_string_name();
        return _testCase.InvokeGodotClassMethodNew(in str, _args, out var _);
    }
    
    [Benchmark]
    public bool Old() {
        var _args = new NativeVariantPtrArgs();
        var str = new godot_string_name();
        return _testCase.InvokeGodotClassMethodOld(in str, _args, out var _);
    }
}
```

While the whole test case is pretty flawed in a lot of ways:

1.  test data has to be generated during the benchmark run as `godot_string_name` is a `ref struct`
2. `str` is always empty as I can't instantiate `internal` structs of Godot from an external assembly  without skewing the benchmark results too much (e.g. via `NativeFuncs.godotsharp_string_name_new_from_string(TestCase.MethodName._Ready)`)
3. **The test was done run in a debug build as I can't figure out how to force Godot to compile and reference NuGets in Release mode from my IDE and Benchmark.NET fails with console related errors when started via Godot**
 
 Considering the given context, here's the result, pretty substantial gains:
 ```
 | Method |     Mean |    Error |   StdDev |
|------- |---------:|---------:|---------:|
|    New | 37.40 ns | 0.184 ns | 0.172 ns |
|    Old | 53.48 ns | 0.460 ns | 0.408 ns |
```

**Comment by raulsntos** [comment]
The method names are of type `StringName`, this is not the same as a normal `String`, it was created specifically to do fast comparisons. In the end comparing `StringName`s comes down to a simple `IntPtr` comparison (which is basically an `int` or a `long`).

It's true that there is some overhead in converting `StringName` to `godot_string_name` using `CustomUnsafe.AsRef` and `Unsafe.AsPointer` but I wouldn't expect that to be noticeable. Your benchmark shows they both take nanoseconds to execute, this is an unit much smaller than a millisecond, so it's hard to see if it really makes much of a difference.

Try creating a benchmark where there are more than 2 ifs, let's say 100, and see if that's noticeable.

Also, what build configuration did you use? If you used `Debug`, it's likely that the `Release` configuration would make the difference even less noticeable due to optimization.

Having said that, I'm not opposed to this change, it should not result in a different behavior.

---

> check whether the .cpp base module generation [here](https://github.com/godotengine/godot/blob/f5f7d11ac47244e4cc02cd7336ba86e0ed272dc3/modules/mono/editor/bindings_generator.cpp#L1633) should be adapted as well

Yes, that generates the equivalent code for the C# classes generated for the Core Godot classes, so it should be changed in there as well.

**Comment by roookeee** [comment]
> The method names are of type `StringName`, this is not the same as a normal `String`, it was created specifically to do fast comparisons. In the end comparing `StringName`s comes down to a simple `IntPtr` comparison (which is basically an `int` or a `long`).
I was and am aware of this :)
> It's true that there is some overhead in converting `StringName` to `godot_string_name` using `CustomUnsafe.AsRef` and `Unsafe.AsPointer` but I wouldn't expect that to be noticeable. Your benchmark shows they both take nanoseconds to execute, this is an unit much smaller than a millisecond, so it's hard to see if it really makes much of a difference.
While this is true, projects using lots of `Node`s will feel this, see this example .NET trace for a sample run with lots of `Node`s:
image

> Try creating a benchmark where there are more than 2 ifs, let's say 100, and see if that's noticeable.
I just wanted to show that there is a difference in the most simple situation, the benefit will add up with more `if`s and multiple invocations via the `Node` hierarchy (e.g. your Node calls into Node3D, which calls into Node, which calls into Object which all use the shown method of checking.
> Also, what build configuration did you use? If you used `Debug`, it's likely that the `Release` configuration would make the difference even less noticeable due to optimization.
As I said, this was run in a debug configuration as I had a hard time to get Godot to run with Benchmark .NET at all. Any other testing metholody besides Benchmark .NET is deeply flawed because of JIT dead code elimation or disregarding JIT warmup behaviour.

If you can point me to a NuGet package of the the core C# files like `godot_string_name` that is not based on setting the SDK I could write the benchmark in a standalone C# application. As far as I know only the Godok Sharp SDK is on NuGet which make building a simple C# console application that uses Godot C# objects too complicated, at least for me.

My other outlined issues with creating a proper benchmark scenario exist as well, which makes creating a solid benchmark for this a quite tedious task, unless I have overlooked some existing Godot C# benchmarking infrastructure.
> Having said that, I'm not opposed to this change, it should not result in a different behavior.
✔️ 
> > check whether the .cpp base module generation [here](https://github.com/godotengine/godot/blob/f5f7d11ac47244e4cc02cd7336ba86e0ed272dc3/modules/mono/editor/bindings_generator.cpp#L1633) should be adapted as well
> 
> Yes, that generates the equivalent code for the C# classes generated for the Core Godot classes, so it should be changed in there as well.
I will adapt it accordingly then.

Thank you for the feedback!

**Comment by raulsntos** [comment]
> If you can point me to a NuGet package of the the core C# files like `godot_string_name` that is not based on setting the SDK I could write the benchmark in a standalone C# application.

The SDK adds a reference to the `GodotSharp` package which is the assembly that contains all the types and APIs. It's available in NuGet.org: https://www.nuget.org/packages/GodotSharp/4.0.0-beta.12. However, anything that uses C++ interop won't work in a standalone C# application and the `StringName` constructor uses interop.

**Comment by roookeee** [comment]
I noticed another peculiarity: it seems like `override` C# class methods bubble down to their base class instead of taking the generated shortcut, e.g. a user defined `_Process` is invoked via `Node`s internal `InvokeGodotClassMethod` instead:
image
The generated code includes a check for the `override` `_Process` method, but falls through because it doesn't check for the snake-case variant like the C++ generated class does:
image
Compared to the C++ generated C# class for node:
image
Does that mean that the generated shortcut-generation per script is never used or am I missing implementation details that force `_process` to be handled differently compared to a `_Process` call ? Is `_Process` even ever supplied to `InvokeGodotClassMethod`? 

It might be worthwhile to check if this is some sort of regression.

**Comment by roookeee** [comment]
I just noticed that I closed this PR by accident (had to clean up my fork and deleted the forks `master` for a moment).

While closing this PR was an accident, I don't think we should continue here anyways. The PR has been dormant for a while and lacks some proper benchmarks and evaluation, I will do better next time.

**Pull request closed without merging**
