### PR TITLE
Add bookmarks for easier code navigation

### PR DESCRIPTION
**Pull request by KoBeWi**
[Bookmarks!](https://gfycat.com/pl/giftedspiffydowitcher)

This PR is related to issue #2746, but probably won't close it fully. In short, it adds support for code editor bookmarks. You can toggle bookmarks on specific line and jump between them easily. Bookmarks are stored per-file and not saved between sessions.

From technical side, I pretty much copy-pasted breakpoint code, so bookmarks are basically breakpoints without anything besides navigation features and with different icon. They use the same gutter, which is now shown when either of their gutters are enabled, and they don't look bad together:
image

I'm submitting this PR as draft for now, as it's the most advanced feature I added so far, so I expect it to have lots of problems before it can be merged. I guess the biggest issue is the awkward interaction between breakpoint and bookmark gutters. Is bookmark gutter even needed as an option? Maybe it should be always enabled? It doesn't make sense to disable it as it makes bookmark markers invisible. Aside from that, there are probably some interactions with e.g. shader editor I didn't properly implement (right now it's untouched). If there's anything more I missed or someone has advice for improvements, I'd really like to know.

From other notes, bookmarks occupy Ctrl + B hotkey, so I moved the old duplicate line to Ctrl + D (original shortcut didn't make sense anyways). Sadly using F2 was impossible, because it interferes with editors.

There are number of issues that might arise when this is merged, but which won't be adressed by this PR. My implementation is supposed to be base for bookmarks and it just has a few potentially missing features (which I hope will be easy to add without scrapping what I made). These are:

- ability to see all bookmarks across opened scripts and navigate between them
- save bookmarks for each session/file when closing editor/file //done, but only for sessions
- toggle bookmarks with e.g. middle click in the gutter (I could actually make this one, but not sure if it's needed)
- potentially a different bookmark icon, as it's a simple circle right now. It doesn't look bad, but I thought about adding a [texture from VS Code Extension](https://github.com/alefragnani/vscode-bookmarks/blob/master/images/bookmark.svg) (it's MIT and looks nice).

As I said, any feedback/criticism is welcome >.>

### CODE REVIEW

**Review by Paulb23 — COMMENTED** [review]
Looks good!

I don't think there's a need to create a separate gutter for bookmarks, as its quite common for them to share the same space as breakpoints in other IDEs. Though I would keep the setting.

As for supporting the `Shader` and `TextFile` editor. Besides the shortcut registration, you'll have to copy the `script_text_editor` changes across into `shader_editor_plugin` and `text_editor`. It also might be worth extracting the `_edit_option` code into methods in `CodeTextEditor`, rather then duplicating it across each editor.

For shortcuts, I've seen `Ctrl+M` used a lot as 'mark' line, I don't know if that would be preferred?

I've been thinking for a while about turning breakpoints into a large dot, similar to what you've got here, so swapping to an icon would be ideal. 

In addition the `edit` drop down is getting quite full. As a result, I would push these actions off into a "bookmark" sub-menu.

Finally, for storing state between sessions, you've already seen #27979, so it would be a matter of copying breakpoints there as well.

**Comment by KoBeWi** [comment]
> As for supporting the Shader and TextFile editor. Besides the shortcut registration, you'll have to copy the script_text_editor changes across into shader_editor_plugin and text_editor.

I've looked into them once and there's lots of code duplication happening in there. Is there any reason why we have the same editor 3 times?

> For shortcuts, I've seen Ctrl+M used a lot as 'mark' line, I don't know if that would be preferred?

M is rather far apart from Ctrl, so it's more difficult to use. And when using bookmarks, you usually want to navigate between them quickly.

> swapping to an icon would be ideal.

I hope leaving it for another PR will be acceptable.

> In addition the edit drop down is getting quite full. As a result, I would push these actions off into a "bookmark" sub-menu.

That menu sounds like breakpoints would fit there too. Should I move them, to make edit menu even less cluttered?

**Comment by KoBeWi** [comment]
So uh ;_;

I did changes to CodeTextEditor, but it resulted in conflicts. I'd really like to know exact instructions how to resolve it (i.e. a set of git commands), because every time I do a de-conflicting rebase, terrible things happen :/

Anyways, I implemented bookmarks for all code editors and moved them to the new menu. I'll add bookmark session storing after the conflict is resolved.

**Review by Paulb23 — CHANGES_REQUESTED** [review]
> Is there any reason why we have the same editor 3 times?

Rather then re-typing, a general explanation of them can be found here: https://github.com/godotengine/godot/pull/28190#issuecomment-487693407

> I hope leaving it for another PR will be acceptable

Sure.

> That menu sounds like breakpoints would fit there too. Should I move them, to make edit menu even less cluttered?

I wouldn't do it as part of this PR, but my bad in explaining. The bookmarks sub-menu should be placed under the `edit` menu, not as an entirely new menu. e.g `edit` --> `bookmarks` --> `Toggle Bookmarks` etc.  

Finally, only one other minor issue. The `bookmark_color` needs to be set in editor setting `_load_default_text_editor_theme` method, and loaded in each of the sub-editor `_load_theme_settings` methods.

Otherwise, functionality wise it looks good to me.

**Comment by KoBeWi** [comment]
> Rather then re-typing, a general explanation of them can be found here: #28190 (comment)

Still, there's loooots of code duplication happening there, which could be done better. I already created an issue for that: #28607

> The bookmarks sub-menu should be placed under the edit menu, not as an entirely new menu.

Right, fixed .-.

> Finally, only one other minor issue. The bookmark_color needs to be set in editor setting _load_default_text_editor_theme method, and loaded in each of the sub-editor _load_theme_settings methods.

Done.

I also squashed the commits. Hopefully it's alright now.

**Review by Paulb23 — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Comment by girng** [comment]
[How I feel right now](https://www.youtube.com/watch?v=HBxt_v0WF6Y). This is a massive game changer in terms of workflow. Thanks @KoBeWi, amazing!

**Pull request merged**
