### PR TITLE
Add force step method to physics

### PR DESCRIPTION
**Pull request by RevenantX**
This method helps implementing best network FPS physics.

### CODE REVIEW

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by RevenantX** [comment]
@pgruenbacher i tested this code and it works well.
@reduz like in unity3d - there is Physics.Simulate method. Very usable for client side prediction (you can freeze or rewind all physical objects and then resimulate some number of frames at one time)

**Comment by AndreaCatania** [comment]
This could be useful but not in that way. When you need to sync physics you have to instantiate more then one physics space and "step" only it when necessary.

In the way you implemented it, the force step will force the processing of all spaces and not a particular one, and this is always wrong.

**Comment by RevenantX** [comment]
@AndreaCatania you can deactivate spaces before step.
Look at https://docs.unity3d.com/ScriptReference/Physics.Simulate.html

**Comment by AndreaCatania** [comment]
I don't know unity, but this is really depend on the kind of project and approach. But from Godot side advance all spaces all together has no sense.

So I would add an API that accept the space RID to be stepped.

**Comment by AndreaCatania** [comment]
@RevenantX why did you close it?

**Comment by RevenantX** [comment]
@AndreaCatania because better will be create another pull request with "space" step?

**Comment by AndreaCatania** [comment]
Usually we change the current commit, to keep a track of discussion. But it's not a problem do it in the way you are more comfortable.

**Pull request closed without merging**
