### PR TITLE
Able to change visibility when ancestor node is hidden

### LINKED ISSUE #7369: cannot change visibility of child node if parent node is hidden
**Operating system or device - Godot version:**
Godot 2.1.1

**Issue description** (what happened, and what was expected):
When you are trying to use the eye icon in the hierarchy to change the visibility of a node that is a child of an invisible node you get an error message saying "This item cannot be made visible because the parent is hidden. Unhide the parent first.".
It's fine that there is a warning for people who would wonder why there are no visible changes, but it should be possible to change the value nevertheless. E.g. I might have a complex scene with two states in it of which one is always hidden. It should be possible to switch those states without having to unhide the root node first.

Apart from that changing the Visible-Flag in the CanvasItem section of the inspector works, but doesn't update the eye-symbol in the hierarchy.

**Steps to reproduce:**
Create a new scene.
Create a root node of type Node2D.
Create a child node of type Node2D.
Hide the root node.
a) Try to hide the child node.
b) Unset the Visible-flag in the inspector.

### PR DESCRIPTION
**Pull request by volzhs**
Fix #7369

### CODE REVIEW

**Comment by volzhs** [comment]
Demo for second commit.

visibility_final

**Comment by bojidar-bg** [comment]
@volzhs There! You rightfully gained the feature proposal tag as well :stuck_out_tongue:

**Comment by volzhs** [comment]
@bojidar-bg Thanks man, I feel like gained enough exp to open new skill slot! :)

**Comment by akien-mga** [comment]
And there, you get the `usability` achievement too, +6 in Agility and +3 in Charisma. :)

**Pull request merged**
