### PR TITLE
Mono inherited scene bug 3.2

### LINKED ISSUE #18293: PackedScene.Pack() ignores changed properties of target nodes
**Godot version:**
`master` / 9ce8d8ddda35cda781364e9b648325a2953d3f63

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When saving a scene with `PackedScene.Pack()`, all nodes get saved with their exported properties reset to their default values.

It's reproducible in a C# project, and it's not clear if it happens in GDScript too.

### LINKED ISSUE #36480: C# inherited [Export] variables null in child scene
**Godot version:**
Godot Engine v3.2.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
[Export] NodePath set on a parent scene is null from a child scene.

**Steps to reproduce:**

1. Create a parent scene (Parent.tscn) with a root node, and a child node (in my example, a Sprite).
2. Create a script (Parent.cs) and export a nodepath:
`[Export]
	NodePath BuggyNodePath;`
3. Build the project and set the NodePath
4. Create a child scene (Child.tscn) that inherits from Parent.tscn. The editor shows BuggyNodePath as being set correctly:
image
5. Override _Ready(), and try to use BuggyNodePath (ie, GD.Print(BuggyNodePath))
5.a From the parent this will be a valid node path.
5.b From the child it will be null.

I've attempted to replicate this with GDScript as well, but didn't encounter the bug. So I believe it's a mono-specific thing. I've never worked on Godot before, so I'm not sure where to start looking.

Interestingly, if you do anything to change the node structure in the child scene, it forces BuggyNodePath to be written into the Child.tscn file, which can then be correctly loaded.
For example, changing the name of the root node of Child.tscn to "Child" forces Godot to update the BuggyNodePath to ../Child/ParentsNode, which gets written to Child.tscn and so can be loaded. In a pinch, this is a viable workaround.

I'm guessing whatever Mono glue code loads [Export] variables isn't correctly pulling from the parent scene. If anyone could point me in the right direction to start looking, I'd gladly dig into it.

**Minimal reproduction project:**
[InheritedNodePathBug.zip](https://github.com/godotengine/godot/files/4240726/InheritedNodePathBug.zip)

### LINKED ISSUE #37581: C# Mono [Export] not working in heirs if value is default
**Godot version:** Godot_v3.2.1-stable_mono_x11.64

**OS/device including version:** Linux mint

**Issue description:** 
I have two classes
Unit:
```
using Godot;

public class Unit : Node2D
{
    [Export] 
    public int Health;
    
    public override void _Ready()
    {
        GD.Print("Health: " + Health);
    }
} 
```
and Player:
```
public class Player : Unit
{
}
```

Two scenes
Unit.tscn:
```
[gd_scene load_steps=2 format=2]

[ext_resource path="res://Unit.cs" type="Script" id=1]

[node name="Unit" type="Node2D"]
script = ExtResource( 1 )
Health = 50
```

and Player.tscn inherited from Unit.tscn:
```
[gd_scene load_steps=3 format=2]

[ext_resource path="res://Unit.tscn" type="PackedScene" id=1]
[ext_resource path="res://Player.cs" type="Script" id=2]

[node name="Player" instance=ExtResource( 1 )]
script = ExtResource( 2 )
```

Player.tscn prints "Health: 0". But the value must be taken from the parent.
If you change Health in Player.tscn, it works correctly.

**Minimal reproduction project:** [cstest.zip](https://github.com/godotengine/godot/files/4431504/cstest.zip)

### PR DESCRIPTION
**Pull request by kappa54m**
Fixes #36480, fixes #37581, fixes #18293 for 3.2 branch
This is a manual 3.2 backport of https://github.com/godotengine/godot/pull/38638

Since I haven't been able to compile without tools on mono for whatever reason (it couldn't load the assembly) even before making any modifications, testing with tools enabled might be required.

Edit: I am able to compile 3.2 branch without tools, but the script won't load at runtime. I will test this one more time before creating its own issue.

### CODE REVIEW

**Comment by akien-mga** [comment]
There are warnings due to reusing the same local variable name several times for different objects, shadowing previous ones:
```
odules/mono/csharp_script.cpp:2367:12: error: declaration of 'tmp_native' shadows a previous local [-Werror=shadow=local]
 2367 |    Object *tmp_native = GDMonoMarshal::unbox<Object *>(CACHED_FIELD(GodotObject, ptr)->get_value(tmp_object));
      |            ^~~~~~~~~~
modules/mono/csharp_script.cpp:2340:11: note: shadowed declaration is here
 2340 |   Object *tmp_native = nullptr;
      |           ^~~~~~~~~~
modules/mono/csharp_script.cpp:2367:12: error: unused variable 'tmp_native' [-Werror=unused-variable]
 2367 |    Object *tmp_native = GDMonoMarshal::unbox<Object *>(CACHED_FIELD(GodotObject, ptr)->get_value(tmp_object));
      |            ^~~~~~~~~~
```

You should also rebase on the upstream 3.2 branch to remove the "Merge commit" from the PR you did on your own branch.

**Comment by pepegadeveloper123** [comment]
> You should also rebase on the upstream 3.2 branch to remove the "Merge commit" from the PR you did on your own branch.

Do you know how I can do that? Do I just delete my current branch and commit on a new branch?

**Comment by pepegadeveloper123** [comment]
Why does this always happen

**Comment by neikeq** [comment]
My recommendation is to use cherry-pick for this. Something like this:

```bash
git checkout 3.2
# Make sure it's up-to-date
git fetch --all
git pull origin 3.2
# Create your branch from 3.2 and cherry-pick the commit
git checkout -b 3.2-inherited-scene-bug
git cherry-pick 4e00d8520db33de62645043af3d9d3ca83b1153f
# FIX CONFLICTS here and commit
git commit -m "Inherited C# scene not inheriting parent's fields"
```

That should avoid most of these issues.

**Comment by pepegadeveloper123** [comment]
Thank you @neikeq I will try that method next time.
Sorry to bother you with my commit f*ckup.

**Comment by akien-mga** [comment]
I'm updating the instructions from the PR workflow in https://github.com/godotengine/godot-docs/pull/3540 to avoid this issue, which likely happened if you used `git rebase -i HEAD~2` as advised in that tutorial, instead of `git rebase -i upstream/master` which would work better in this case.

**Pull request closed without merging**
