### PR TITLE
Fixed optional idx argument in add_item (PopupMenu)

### LINKED ISSUE #26909: Bug on OptionButton add_item (also PopupMenu)
**Godot version:**
Last master 3.1 RC1

**OS/device including version:**
N/A

**Issue description:**

The description for `add_item` method in `OptionButton` states the following:

`void add_item( String label, int id=-1 )`
Add an item, with text "label" and (optionally) id. If no "id" is passed, "id" becomes the item index. New items are appended at the end.

this is NOT happening, providing no id will make the item id to become "-1" and not its index

EDIT: this falls back to its parent class

### PR DESCRIPTION
**Pull request by xDGameStudios**
Fixes #26909

### CODE REVIEW

**Comment by reduz** [comment]
seems good

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
Cherry-picked for 3.1.2.

**Comment by akien-mga** [comment]
This was incomplete, there are many other methods which add `Item`s with default `p_id` of -1, and don't use this logic.

**Pull request merged**
