### PR TITLE
Always disable low-processor usage mode on mobile platforms

### PR DESCRIPTION
**Pull request by Calinou**
This partially addresses https://github.com/godotengine/godot/issues/19304.

**Note:** It may be easier to cherry-pick this PR by copy-pasting the relevant parts rather than using `git cherry-pick`.

### CODE REVIEW

**Comment by tavurth** [comment]
@Calinou Thank you for this! 🎉

**Comment by akien-mga** [comment]
I don't think it's a good idea, the proper fix would be to make low processor usage actually work reliably on Android.
Additionally, there might still be use cases for it for non-game apps that don't use high FPS features.

I'm not against adding a workaround as a stopgap solution for now, but this should be done via feature tags, not hardcoded.

**Comment by Lauson1ex** [comment]
Instead of opening [yet](https://github.com/godotengine/godot/issues/6727) [another](https://github.com/godotengine/godot/issues/7980) [issue](https://github.com/godotengine/godot/issues/30417) [report](https://github.com/godotengine/godot/issues/19304) about this problem that have been present in the engine _for almost 5 years_ , I would like to report that I, too, am facing this issue. Currently I'm working on a project which introduces a novelty control interface, where the project is controlled by its companion phone app. The thing is, the companion phone app doesn't _need_ all the resources it consumes, which is undesired — it only needs to update logic/inputs and send UDP packets every 33 millisecs. The solution is the low processor mode, which works for the most part by making the phone use less CPU resources and even enabling fast app switching, but this introduces the aforementioned graphical glitches in Control nodes described in the aforementioned issue reports. Low processor mode is _crucial_ for my project.

> I don't think it's a good idea, the proper fix would be to make low processor usage actually work reliably on Android.
> Additionally, there might still be use cases for it for non-game apps that don't use high FPS features.
> 
> I'm not against adding a workaround as a stopgap solution for now, but this should be done via feature tags, not hardcoded.

As @akien-mga said, it would probably be a good idea to implement a proper solution to this long-standing issue, rather than eliminating the feature altogether for Android, as it will also greatly benefit non-game mobile app developers.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/pull/55604.

**Pull request closed without merging**
