### PR TITLE
Ensure special characters are escaped in TSCN connections and editable hint

### LINKED ISSUE #86347: "\" used in node names prevents parsing of .TSCN
### Tested versions

Reproduce able in 4.3.stable

### System information

Windows 10 - vulkan Forward+ renderer, v4.3.stable

### Issue description

Initial Issue:
Currently in live Godot 4.3 branch, accidentally inserted the "\" key at the end of a Node name. While adding and implemented the node, I connected a signal, saved and ran the scene, causing an issue with it immediately crashing, saved and relaunched to see the file could not be parsed, at some point in the process the following offending line was added.
image

### Steps to reproduce

Rename a node to include \
example: new_button\
create a signal from the renamed node to any given node using the editor panel
save the scene
close and re-open scene to get parser error

### Minimal reproduction project (MRP)

[errorissue.zip](https://github.com/godotengine/godot/files/13721775/errorissue.zip)

### PR DESCRIPTION
**Pull request by LimestaX**
Fixes issue regarding #86347

* _Bugsquad edit:_ Fixes #86347.

### CODE REVIEW

**Comment by LimestaX** [comment]
Originally was under #86348 , but I properly bricked my branch, this is a fresh build properly following guidelines, this was my first PR, and I tried using the web editor with Github, I didn't realize how bad that would make things, I couldn't properly rebase.

**Review by dalexeev — APPROVED** [review]
Looks good to me. Please correct the commit message, it must start with a capital letter, see [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#format-your-commit-messages-with-readability-in-mind).

**Comment by LimestaX** [comment]
All set! Thank you all for being patient.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
I confirm the bug and the fix seems correct.

I skimmed through the file and found another occurrence that can have the same bug:
```diff
diff --git a/scene/resources/resource_format_text.cpp b/scene/resources/resource_format_text.cpp
index 29cd9f648d..b75b0280a0 100644
--- a/scene/resources/resource_format_text.cpp
+++ b/scene/resources/resource_format_text.cpp
@@ -2319,7 +2319,7 @@ Error ResourceFormatSaverTextInstance::save(const String &p_path, const Ref<Reso
 			if (i == 0) {
 				f->store_line("");
 			}
-			f->store_line("[editable path=\"" + editable_instances[i].operator String() + "\"]");
+			f->store_line("[editable path=\"" + editable_instances[i].operator String().c_escape() + "\"]");
 		}
 	}
 
```
Could you add it to this commit?

Overall I wonder if:
- We should prevent using `\` in Node names/paths
- We should ensure NodePaths are always encoded with `VariantWriter` (i.e. as `NodePath("Node\\")`)

But both changes would be compat breaking, so this approach is the simplest solution for now.

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 4.2.2.

**Pull request merged**
