### PR TITLE
Fix GridMap erasing octants in the wrong order

### LINKED ISSUE #33648: Dynamic Gridmap unloading causes physics engine errors and FPS issues
**Godot version:** 3.1.1

**OS/device including version:** Ubuntu 19.10, AMD RX580, Mesa 19.2.1 

**Issue description:**
Dynamically unloading GridMap tiles via `set_cell_item(x,y,z,-1)` (e.g. in a project that manages a large world) causes errors in the internal physics engine that are then shown in the editor error log. At the same time, unloading seems to not have the expected effect, as the FPS slows down noticeable the more world has been "covered" - even when the tiles actually have been removed.

Following errors are spammed in my error log (over 1000 errors in a short time; depending on how much unloading is done):

```
E 0:00:01:0791   Condition ' !id_map.has(p_rid.get_data()) ' is true. returned: __null
  <C Source>     ./core/rid.h:154 @ get()

E 0:00:01:0791   Condition ' !body ' is true.
  <C Source>     modules/bullet/bullet_physics_server.cpp:567 @ body_clear_shapes()

E 0:00:01:0791   Invalid ID
  <C Source>     modules/bullet/bullet_physics_server.cpp:1552 @ free()
```

Although the errors seem to be related to the physics server, they still come up if only mesh instances without physics or navigation are used as tiles.

**Steps to reproduce:**
Please see example project

**Minimal reproduction project:**
[reproduce.zip](https://github.com/godotengine/godot/files/3853401/reproduce.zip)

### LINKED ISSUE #43712: GridMap reports errors to the Physic server on removing cells
**Godot version:**
3.2.3 - 3.2.4

**OS/device including version:**
Win10/GTX1060

**Issue description:**
Removing the cell by calling `set_cell_item(x, y, z, -1)` will cause errors in the PhysicServer even if there is no physic body attached to cells.

**Steps to reproduce:**
Run attached project.
The following code will spam errors to the Output:

image

```
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150
ERROR: body_set_state: Condition "!body" is true.
   At: modules/bullet/bullet_physics_server.cpp:675
ERROR: Invalid ID.
   At: modules/bullet/bullet_physics_server.cpp:1551
```

**Minimal reproduction project:**
[GridMapBug.zip](https://github.com/godotengine/godot/files/5571950/GridMapBug.zip)

### LINKED ISSUE #49995: The GridMap freezes if meshes are changed frequently
### Godot version

3.3.2-stable

### System information

Windows 10, GTX 1050ti, GLES3

### Issue description

GridMap freezes and throws errors if grids change frequently

```
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150
ERROR: body_add_shape: Condition "!body" is true.
   At: modules/bullet/bullet_physics_server.cpp:504
```

see this video: [https://www.youtube.com/watch?v=ckImAKQaIuw](https://www.youtube.com/watch?v=ckImAKQaIuw)

Maybe this is related to [issue](https://github.com/godotengine/godot/issues/14795)? 

### Steps to reproduce

Create a GridMap project and change tiles frequently, in large numbers in one frame.
Decreasing the octave will increase the errors.

### Minimal reproduction project

This project. Run Test.tscn 
[SCP Manager.zip](https://github.com/godotengine/godot/files/6732845/SCP.Manager.zip)

LEFT_CLICK - Set block/Remove block
RIGHT_CLICK - Move Camera
WHILE_MOUSE - Zoom

GitHub: [https://github.com/Valeryn4/Godot-GridMap-Err](https://github.com/Valeryn4/Godot-GridMap-Err)

### PR DESCRIPTION
**Pull request by Valeryn4**
Fix GridMap problem issues:  [#33648](https://github.com/godotengine/godot/issues/33648), [#43712](https://github.com/godotengine/godot/issues/43712) and [#49995 ](https://github.com/godotengine/godot/issues/49995)

*Bugsquad edit:* fixes #33648, fixes #43712, fixes #49995

### CODE REVIEW

**Review by pouleyKetchoupp — APPROVED** [review]
Works well, thanks!

**Comment by Valeryn4** [comment]
I don't like the abundant use of List in the code.
memory allocation occurs too often.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks! And congrats for your first merged Godot contribution :tada:

**Comment by akien-mga** [comment]
Cherry-picked for 3.4.

**Comment by akien-mga** [comment]
Cherry-picked for 3.3.3.

**Pull request merged**
