### PR TITLE
 RPCMode refactor, more sync modes (2)

### PR DESCRIPTION
**Pull request by Faless**
Same as #19021 ,

All `RPCMode` enums references has been moved to `MultiplayerAPI`.
More RPC mode checks has been moved from `Node` to `MultiplayerAPI`.
Three new `RPCMode`s where added.

As #16733 mentions, some users expected `sync` to behave like `slave` (i.e. only be callable by the network master).
To keep compatibility though, `sync` was left with the current behaviour (like `remote`) and should be deprecated in the future. Three new keywords where added: `remotesync`, `mastersync`, `slavesync`, they behave like their base counterpart (`remote`, `master`, `slave`) but also apply the function/property locally in the caller.

I can't seem to make the whole MS/Mono bs to work, can someone please test if the fix works (it should honestly, but better test it @mhilbrunner )

### CODE REVIEW

**Comment by mhilbrunner** [comment]
Will test Mono later :) thanks for the new PR

**Comment by Valentactive** [comment]
Since I was the one who talked about not building with Mono in the irc channel, I felt the need to test this now too. It builts with Mono now :)

**Comment by Faless** [comment]
Thank you for testing it :)

**Comment by mhilbrunner** [comment]
Thanks for testing it, @Valentactive - and also thanks for the feedback, no worries, I didn't take it personally or see it as an attack. You're mostly right. :P

**Review by mhilbrunner — APPROVED** [review]

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
