### PR TITLE
Sort xml files, so order is constant

### LINKED ISSUE #473: xml scenes reorder on saving
I know xml does not enforce any order... thats why maybe changing to other format or other  more drastic solution is due.

Thing is that is hard to keep projects under source control with more than one contributor if xml keep on changing on every save

Thanks

### PR DESCRIPTION
**Pull request by est31**
Makes xml format work better with version control systems. Mostly fixes #473. There are still some reorder problems left, e.g. with fonts, but mostly the xml is remaining the same. Of course, if this gets applied, there will be some changes due to sorting, but after that the order won't change.

### CODE REVIEW

**Comment by adolson** [comment]
This is working great! PLEASE merge in time for 1.1, unless 1.1 will have a new plain-text resource format that doesn't change with every save.

**Comment by philiplb** [comment]
+1 :)

**Comment by bojidar-bg** [comment]
+3 :D

**Comment by reduz** [comment]
actually nevermind, i misunderstood your code, what you did is perfect

**Pull request merged**
