### PR TITLE
Fix enums coming from other classes without preload

### LINKED ISSUE #19704: export doesn't work with enums from another script/class
neither of the following work, where `g` is set to autoload
```gdscript
export var type = g.BMW
export(g.Type) var type = g.BMW
```
gives error:
```
built-in:7 - Parse Error: invalid index 'BMW' in constant expression
modules/gdscript/gdscript.cpp:583 - Method/Function Failed, returning: ERR_PARSE_ERROR
```
this works tho':
```gdscript
var type = g.BMW
```

See attached project 
[godot-dbg.zip](https://github.com/godotengine/godot/files/2124482/godot-dbg.zip)

*edit*
although it seems that if you close&reopen the project (possibly the scene, didn't try that one) the error disappears so you might have to recreate from scratch the simple project I attached.

### LINKED ISSUE #26001: Accessing constant members from a globally-named class is not considered constant
Godot 3.1 beta5

As found in Q&A: https://godotengine.org/qa/40827/how-to-declare-a-global-named-enum
It has limiting consequences: if you define an enum inside a named class for the purpose of having it accessible globally, using it with `export` does not work:

my_enum.gd
```gdscript
class_name MyEnum

enum MyEnum {
	ONE,
	TWO,
	THREE
}
```

main.gd
```gdscript
extends Node

export(MyEnum.MyEnum) var test
```
Godot complains that the expression is not constant.

The only workaround so far is to use `preload` instead:

```gdscript
extends Node

const MyEnum = preload("my_enum.gd")

export(MyEnum.MyEnum) var test
```

Similarly, you can't define constants using other constants from that globally-named class, and using `preload` is also the only workaround.

Was there an issue about this? Is there plan to support it?

### PR DESCRIPTION
**Pull request by bojidar-bg**
Fix #19704, fix #26001.

### CODE REVIEW

**Comment by akien-mga** [comment]
Tested locally and it seems to work well in a `tools=yes target=debug` build. Both referenced issues are fixed, and I did not face any issue when running some bigger projects like the 2D platformer, the TPS demo or Jetpaca. None of them use those features specifically though.

It would be good to check a `tools=no target=release` build too to be sure.

**Comment by akien-mga** [comment]
I did see this once when opening the TPS demo in the editor though, but then couldn't reproduce it on subsequent runs.
```
ERROR: set_path: Another resource is loaded from path: res://door/door.gd (possible cyclic resource inclusion)
   At: core/resource.cpp:79.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
   At: res://door/door.gd:19.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:580.
SCRIPT ERROR: GDScript::reload: Parse Error: Could not fully preload the script, possible cyclic reference or compilation error. Use 'load()' instead if a cyclic reference is intended.
   At: res://door/door.gd:19.
ERROR: reload: Method/Function Failed, returning: ERR_PARSE_ERROR
   At: modules/gdscript/gdscript.cpp:580.
ERROR: set_path: Another resource is loaded from path: res://player/player.gd (possible cyclic resource inclusion)
   At: core/resource.cpp:79.
ERROR: mesh_surface_get_index_array: Condition ' surface->index_array_len == 0 ' is true. returned: PoolVector<uint8_t>()
   At: drivers/gles3/rasterizer_storage_gles3.cpp:3770.
ERROR: set_path: Another resource is loaded from path: res://player/blue_myst.png (possible cyclic resource inclusion)
   At: core/resource.cpp:79.
ERROR: set_path: Another resource is loaded from path: res://player/bullet.tscn (possible cyclic resource inclusion)
   At: core/resource.cpp:79.
```

**Comment by akien-mga** [comment]
Tested with a release build, everything seems to work fine too.

The parse errors above might not be related to this PR, I've seen other cases where the import system seems to make a mess of things the first time you open it.

**Review by vnen — APPROVED** [review]
LGTM

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
